### ISSUE TITLE
One-To-Many (hasMany) relationship through a join table

### ISSUE THREAD

**Issue by jumojer** [sequelize/sequelize#10000]
## What are you doing?

```js
 Book.hasMany(models.Page, {
      through: {
        model: models.BookPage
      },
      foreignKey: "page_id"
    });
```

## What do you expect to happen?
I expect the 1:n relationship to use the through the table to link the two models

## What is actually happening?
I get this error message: "N:M associations are not supported with hasMany. Use belongsToMany instead"

This might be only a documentation issue since i'm following the association tutorial ([http://docs.sequelizejs.com/manual/tutorial/associations.html#n-m](http://docs.sequelizejs.com/manual/tutorial/associations.html#n-m)) 

and at the end of the `n:m` section, an example uses `hasMany` with a `through` option.

Here's the example in the docs:
```js
Post.hasMany(Tag, {
  through: {
    model: ItemTag,
    unique: false,
    scope: {
      taggable: 'post'
    }
  },
  scope: {
    status: 'pending'
  },
  as: 'pendingTags',
  foreignKey: 'taggable_id',
  constraints: false
});
```

**Comment by sushantdhiman** [comment]
Yes documentation issue, this has been fixed in master https://github.com/sequelize/sequelize/blob/master/docs/associations.md#nm

Docs are currently using v4 (stable) branch
