### ISSUE TITLE
can sequelize.col() support automanually fill table alias?

### ISSUE THREAD

**Issue by muyu66** [sequelize/sequelize#10010]
Under normal circumstances, I want to search for a value, do it by the following method

    await this.userDao.findAll({
      where: {
        name: {
			[Op.like]: `%${searchValue}%`,
        },
      },
      include: [{
	      model: Book,
      }]
    });

Now I want to implement " lower('name') = searchValue " like Sql
Because of using include, there will be hava a ambiguous problem

    await this.userDao.findAll({
      where: {
        name: Sequelize.where(Sequelize.fn('lower', Sequelize.col('name')), {
			[Op.like]: `%${searchValue.tolowerCase()}%`,
        }),
      },
      include: [{
	      model: Book,
      }]
    });

	throw 'Column \'name\' in where clause is ambiguous',

Because of code restrictions or considering database compatibility, I don't know what the table alias is. I can't use raw sql to query, how can I do it, or is this a bug?...

**Comment by sushantdhiman** [comment]
No I don't think so this will be supported, `Sequelize.col` etc deals with query directly, so you need to scope them with correct alias yourself

**Comment by muyu66** [comment]
Yes, you are right, Sequelize.col() should be like this directly. But can using other function to implement this effect ? (add table alias into Sequelize.fn() column  automanully)

**Comment by muyu66** [comment]
I have read the sequelize source code, when passing the Where Object, sequelize has automatically filled the table alias automatically for the Object key, why not in sequelize.fn()

**Comment by sushantdhiman** [comment]
That would mean changing values passed to `fn` which is mostly not desired as they are targeted specifically to query.

This would lead to issues like why my `col(xyz)` gets converted to `col(abc)`. I think when dealing with raw query constructs it is better to let user scope thing as they want to

**Comment by PatrickGeyer** [comment]
@sushantdhiman, how can we do this when we don't know where the model will be included from? Do you have any tips for this?

**Comment by si4dev** [comment]
I'm running into the same issue. I don't like to "hardcode" the alias of the table. I cannot find many reasons why not but maybe it is changing later although most tables names are not changing. However in sequelize the alias name is known. So maybe a solution is to allow the col() method on the model itself. This line Sequelize.col('name') will result in an ambitious column. Currently to be solved with Sequelize.col('book.name'). My proposal would be to allow Book.col('name')

The Book model will know the table alias and is able to return the correct field without ambiguous problem.

**Comment by papb** [comment]
Hello @si4dev, I like what you are proposing. Can you please open a new feature request and fill the template accordingly? (And link to this issue as a reference)

**Comment by abelosorio** [comment]
I can't understand why features like this are being discarded...

+1 to keeping this open
