### ISSUE TITLE
How to get count of object in many to many relationship

### ISSUE THREAD

**Issue by poojaharchirkar** [sequelize/sequelize#10012]
My  db structure  is as follows:
I have "assessment" ,"question", "tag" table. The association between these table is as follows : 
1. assessment and question are linked by third table "assessment_questions"
2. question and tag is linked by third table "question_tag" that is  many to many relationship.
I usecase is , I have assessmentId from which I fetch questions associated with it and also I want tagCount of each question fetched for given assessmentId.
To fetch questions and tags I m using below sequelize api : 

assessment.findAll({
            where: {
                id: assessmentId,
                is_active: true
            },include:[{
                model: question,
                where : {
                    is_active: true
                },
                required: false,
                through: {attributes: []},
                include: [{
                    model:tag,
                    through: {attributes: []}
                }]
            }]
          }) 
To get the tagCount for the questions I tried sequelize.fn("count") and  sequelize .literal but it not fetching the  tagCount of question. 
Please  help me how to use count function for many to many relationship. 
Please update above sequelize query to get tagCount.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
