### ISSUE TITLE
PostgreSQL URI connection strict ?sslmode=require should enable dialectOptions.ssl=true

### ISSUE THREAD

**Issue by ceefour** [sequelize/sequelize#10015]
## What are you doing?

`"use_env_variable": "POSTGRESQL_URI"` in `config.json`

The `POSTGRESQL_URI` contains `?sslmode=require` as described in official libpq: https://www.postgresql.org/docs/9.3/static/libpq-ssl.html

(alternative to `require`: `verify-ca` and `verify-full`)

## What do you expect to happen?

sequelize connects via SSL, i.e. implicitly sets `dialectOptions.ssl=true`

## What is actually happening?

sequelize connects regularly.

Workaround is to set `dialectOptions.ssl=true` manually, however correct behavior is that this can be set from env variable.

Note: This is related to previous issues #9712, #6932, #5891, 

__Dialect:__ postgresql
__Dialect version:__ 7.5.0
__Database version:__ 10
__Sequelize version:__ 4.39.0
__Tested with latest release:__ Yes, 4.39.0

**Comment by justinkalland** [comment]
It appears that with the node-postgres module you can't use `sslmode=mode`. However you can use `ssl=true` and that defaults to `sslmode=require` (found a note on that [in the docs](https://www.postgresql.org/docs/9.3/static/libpq-connect.html)).

It is also possible with the node-postgress module to pass an object for `ssl` ([code](https://github.com/brianc/node-postgres/blob/04a0ec71b48f89e68ddaa365f0b9a8a0d9e738d8/lib/connection-parameters.js#L90-L95)).

I will submit a pull request that adds support for `?ssl=true` to the URI for Postgres. If needed I can add support for `sslmode` `sslca` `sslkey` `sslcert` `sslrootcert` but I suspect it unnecessary.

**Comment by ceefour** [comment]
@justinkalland this is really great!
