### ISSUE TITLE
Code comment asserts that "where option" is vulnerable to sql injection.

### ISSUE THREAD

**Issue by RichardEb** [sequelize/sequelize#10011]
The code comments  asserts that "where option" is vulnerable to sql injection. See: https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1125

But as far as I understood where is safe to use from v4 on. So the comment is wrong?!

**Comment by sushantdhiman** [comment]
Yes, raw where options were removed in v4, this comment can be removed
