### ISSUE TITLE
defaultScope use include

### ISSUE THREAD

**Issue by acodercat** [sequelize/sequelize#10022]
## What are you doing?
defaultScope use include 
error:Cannot read property 'getTableName' of undefined

```js
   defaultScope: {
      attributes: { exclude:['password'] },
      include: [
        {
          model: app.model.AccountBasicInfo,
          as: 'basicInfo'
        }
      ]
    }
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ postgres
__Dialect version:__ last
__Database version:__ last
__Sequelize version:__ last
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Are you sure `app.model.AccountBasicInfo` is defined?

Please follow the issue template, specify package versions properly
