### ISSUE TITLE
Email validation doesn't comply with RFC

### ISSUE THREAD

**Issue by DerKnerd** [sequelize/sequelize#10023]
## What are you doing?
We are trying to validate email adresses such as `test@domain` is seen as invalid. This is wrong.

## What do you expect to happen?
We would like to get a correct validation of email addresses.

## What is actually happening?
The email address is marked as invalid.

__Dialect:__ postgres
__Dialect version:__ 7.4.3
__Database version:__ 10.4
__Sequelize version:__ 4.37.10
__Tested with latest release:__ No

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
We use https://github.com/chriso/validator.js for validations, can you open an issue on that repository?

**Comment by DerKnerd** [comment]
I opened an issue in validator.js see here: https://github.com/chriso/validator.js/issues/908

**Comment by DerKnerd** [comment]
The issue in validator.js showed, that it actually is a problem on your site. You can say that it should validate rfc compliant. For that you need to pass the option `require_tld: false`.

**Comment by justinkalland** [comment]
I believe leaving the defaults of chriso/validator.js is appropriate. But you can use `require_tld: false` in sequelize. It would look like this:

```js
const Email = sequelize.define('Email', {
  email: {
    type: Sequelize.TEXT,
    unique: true,
    validate: {
      isEmail: {args: {require_tld: false}}
    }
  }
});
```

**Comment by DerKnerd** [comment]
Why do you think it is appropriate to ignore standards? Every other ORM with validation, like Doctrine, Entity Framework or Hibernate, use the RFC as base.

**Comment by justinkalland** [comment]
My point wasn't that you should "ignore standards". From the perspective of sequelize, it provides an easy way to use the validator module. The documentation clear about that. I was stating that I thought making specific changes to the behavior of `chriso/validator.js ` for sequelize was inappropriate.

Discussion of what a valid email is, and the definition of "valid". Is more appropriate in `chriso/validator.js`.

**Comment by DerKnerd** [comment]
But validator.js gives you the option to validate RFC compliant, why not use it?

**Comment by sushantdhiman** [comment]
We are using whatever defaults `validator.js` is using, there is a way to override them per usecase. If `validator.js` change their email validation to be more RFC compliant, you will automatically get that update.

Closing this issue as it is more dependent on validation library and your can override validator args pretty easily

**Comment by DerKnerd** [comment]
Actually I don't think that solves anything. You should measure yourself with the other major ORM out there and they accept non TLD emails. Do you have a good reason why you think the business world is unimportant? We can't be the only ones that need valid email address as stated by the RFC and not by how some guys on github think it is.
