### ISSUE TITLE
There is not creating the relationship among the Tables

### ISSUE THREAD

**Issue by wcorderolara** [sequelize/sequelize#10029]
## What are you doing?

I'm creating two models/tables, just check

Categorias Model
```js
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Categorias = sequelize.define('Categorias', {
    nombre: DataTypes.STRING,
    descripcion: DataTypes.STRING,
    imagen: DataTypes.STRING,
    estado: DataTypes.BOOLEAN
  }, {
    classMethods: {
      associate: function(models) {
        // Categorias.hasMany(models.SubCategorias);
        Categorias.hasMany(models.CategoriaLicitacion);
      }
    },
    freezeTableName: true,
    tableName: "Categorias"
  });

  return Categorias;
};
```

CategoriaLicitacion Model
```js
'use strict';

module.exports = function (sequelize, DataTypes) {
    let CategoriaLicitacion = sequelize.define("CategoriaLicitacion", {
        estado: {
            type: DataTypes.BOOLEAN,
            defaultValue: true
        }
    }, {
        classMethods: {
            associate: function(models) {
                CategoriaLicitacion.belongsTo(models.Categorias);
            }
          },
        freezeTableName: true,
        tableName: "CategoriaLicitacion"
    });

    return CategoriaLicitacion;
};
```

## What do you expect to happen?
I remember that in the previous version of Sequelize when you execute the process to synchronize your models with your database if you have the above code, Sequelize create the relationship among the database.

## What is actually happening?
Sequelize is doesn't creating the relations, I mean I'm applying the re-engineering in my database to generate the ER diagram, so, when I check the ER doesn't appear the migrations and doesn't appear the foreign keys in the target model

__Dialect:__ mysql 
__Dialect version:__ 5.7
__Database version:__ 5.7.3
__Sequelize version:__ 4.38.0
__Tested with latest release:__ yes with 3.12.2 version

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`classMethods` has been removed in v4. Please follow this upgrade guide https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v4.md
