### ISSUE TITLE
create/dropDatabase failed on postgresql

### ISSUE THREAD

**Issue by ALiangLiang** [sequelize/sequelize#10030]
## What are you doing?

In [this post says](https://stackoverflow.com/questions/18389124/simulate-create-database-if-not-exists-for-postgresql), postgresql not support `CREATE DATABASE IF NOT EXISTS...`. But in https://github.com/sequelize/sequelize/pull/10027, I use `if not exists` as MySQL.

I'm trying to fix this issue.

## What do you expect to happen?

Run createDatabase correctly on postgresql.

## What is actually happening?

Failed with `ERROR: syntax error at or near "NOT"`

__Dialect:__ postgres 
__Dialect version:__ XXX
__Database version:__ sushantdhiman/postgres:9.5
__Sequelize version:__ https://github.com/sequelize/sequelize/commit/a7fa31616f46957fabf9499ea32f09ce658e0846
__Tested with latest release:__ Yes, https://github.com/sequelize/sequelize/commit/a7fa31616f46957fabf9499ea32f09ce658e0846

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by ALiangLiang** [comment]
__Note__: `CREATE DATABASE` cannot executed within multi-command string.

Two ways:

1. Abandon checking the db exists
2. Take out the exists checking to QueryInterface. It's take two queries in one time API invoking.
```js
  createDatabase(database, options) {
    options = options || {};
    const sql = this.QueryGenerator.createDatabaseQuery(database, options);
    if (IS_POSTGRES) {
      return this.sequelize.query(`SELECT 1 as exists FROM pg_database WHERE datname = '${database}'`)
        .then(result => {
          if (result[0].exists !== 1) {
            return this.sequelize.query(sql, options);
          }
        });
    } else {
      return this.sequelize.query(sql, options);
    }
  }
```

I prefer method 2.

**Comment by sushantdhiman** [comment]
Yeah, go with simplest for now

1. Abandon checking the db exists
