### ISSUE TITLE
Implicit install of `debug` twice.

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#10054]
## What are you doing?

I wrote a utility that detects duplicate packages with different versions, sequelize uses `debug` 3.10 but one of sequelizes dependencies uses 2.6.9.
```
Duplicate dependency debug installed 2 times 3.1.0,2.6.9!
     3.1.0: sequelize
     2.6.9: sequelize > retry-as-promised
```

**Comment by sushantdhiman** [comment]
We are using `debug@4` (in master), but as for this issue we can't control dependencies installed by other packages. You may submit a PR to retry-as-promised so it use `debug@4` or use it as peer dependency

**Comment by SimonSchick** [comment]
I tried to contact the author before but he's unresponsive https://github.com/mickhansen/retry-as-promised/issues/19

**Comment by SimonSchick** [comment]
Resolved via https://github.com/mickhansen/retry-as-promised/issues/19

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/pull/10065
