### ISSUE TITLE
Missing information about dataTypeOrOptions & options in docs

### ISSUE THREAD

**Issue by rico345100** [sequelize/sequelize#10057]
## What are you doing?
I'm trying to update my previous field to something different, like set "not null" to false. However I read whole documentation and searched a lot, there's no information about what is "dataTypeOrOptions" and "options" parameter in changeColumn method.

This is the all I can found about changeColumn:

```text
changeColumn(tableName, attributeName, dataTypeOrOptions, options)
This method changes the meta data of an attribute. It is possible to change the default value, allowance of null or the data type. Please make sure, that you are completely describing the new data type.

queryInterface.changeColumn(
  'nameOfAnExistingTable',
  'nameOfAnExistingAttribute',
  {
    type: Sequelize.FLOAT,
    allowNull: false,
    defaultValue: 0.0
  }
)
```

## What do you expect to happen?
I wanted to describe all information about each part of API as detail as possible. It's really hard to do something without proper documentation.

## What is actually happening?
Stuck in the various issues. I will create new issue for this.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/blob/4b39e530389c97b937afb480a2891ac5260d818e/lib/query-interface.js#L540-L549

Attribute definition can be found in https://github.com/sequelize/sequelize/blob/master/docs/models-definition.md

**Comment by aymkin** [comment]
> https://github.com/sequelize/sequelize/blob/4b39e530389c97b937afb480a2891ac5260d818e/lib/query-interface.js#L540-L549
> 
> Attribute definition can be found in https://github.com/sequelize/sequelize/blob/master/docs/models-definition.md

The reply does not give a clear idea about:

- what is the dataTypeOrOptions object

- what kind of keys are available to use and what are the options for values

- examples of how to achieve the most common results
