### ISSUE TITLE
How to use array datatype while creating migration with postgresh db

### ISSUE THREAD

**Issue by web-innovation** [sequelize/sequelize#10063]
## What are you doing?
Create an array datatype but getting error everytime

```js
// code here
```
module.exports = {
  up: (queryInterface, Sequelize) =>
    queryInterface.createTable('templates', {
      statues: {
        type: Sequelize.ARRAY(Sequelize.STRING),
      },
    }),
  down: (queryInterface) => queryInterface.dropTable('templates'),
};
## What do you expect to happen?
should create a array datatype column

## What is actually happening?
    if (type instanceof DataTypes.ARRAY && dialectTypes[type.type.key]) {
                                                             
TypeError: Cannot read property 'key' of undefined

_Output, either JSON or SQL_

__Dialect:__  postgres
__Dialect version:9.5.14
__Database version:9.5.14
   "pg": "^7.4.1",
    "sequelize": "^4.33.4",
    "sequelize-cli": "^4.0.0",
__Tested with latest release:yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by Gbahdeyboh** [comment]
Hi @web-innovation, how were you able to fix this issue? I'm currently stuck at a similar issue.
