### ISSUE TITLE
Unique field violation throws Error after calling "before" hooks.

### ISSUE THREAD

**Issue by ugogiordano87** [sequelize/sequelize#10066]
## What are you doing?

Simply using a unique field constraint.

```js
ipAddress: {
     type: DataTypes.STRING(15),
     allowNull: false,
     unique: {
         name: 'ak_tcp_communicator',
         msg: 'IP address already taken',
     },
}
```

## What do you expect to happen?
When a unique constraint is violated Sequelize should raise the corresponding 
`SequelizeUniqueConstraintError` without running the **before** hooks, as it happens with the `ValidationError`.

A possible workaround is to define a custom validator as depicted in #2640:

```js
ipAddress: {
     type: DataTypes.STRING(15),
     allowNull: false,
     unique: {
         name: 'ak_tcp_communicator',
         msg: 'IP address already taken',
     },
     validate: {
        isIPv4: { msg: 'Please provide a valid IP address.' },
        isUnique(value, next) {
        TcpCommunicator.find({
              where: { ipAddress: value },
              attributes: ['id']
         }).done((instance) => {
               if (instance) return next('errors.ipAddress.unique');
                    next();
               });
         }
      },
}
```
However, in my opinion writing a validate for each unique constraint inside the models is not the right approach, and it's not going to work for composite unique constraint. 

## What is actually happening?
The **before** hooks are called.

__Dialect:__ mysql 
__Dialect version:__ last
__Sequelize version:__ 4.39.0

**Comment by sushantdhiman** [comment]
I have reopened #2640

**Comment by ugogiordano87** [comment]
@sushantdhiman how I can contribute to solve this issue? 
What are the files I should look into?

**Comment by sushantdhiman** [comment]
@ugogiordano87 I don't think I will accept this in core, you can create a plugin for this validator which can be easily shared
