### ISSUE TITLE
Invalid logging of single INSERT and UPDATE SQL queries

### ISSUE THREAD

**Issue by ezze** [sequelize/sequelize#10067]
## What are you doing?

Here is a [repo reproducing the issue](https://github.com/ezze/sequelize-log-sql-issue).

In Sequelize `5.0.0-beta.13`:

```js
const connection = new Sequelize(database, username, password, {
    dialect,
    host,
    define: {
        freezeTableName: true,
        underscored: false,
        createdAt: 'createdAt',
        updatedAt: 'updatedAt'
    },
    logging: message => {
        console.log(message);
    }
});

const Task = connection.define('task', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    createdAt: {
        field: 'created_at',
        type: Sequelize.DATE,
        allowNull: false
    },
    updatedAt: {
        field: 'updated_at',
        type: Sequelize.DATE,
        allowNull: false
    },
    name: {
        type: Sequelize.TEXT,
        allowNull: false
    },
    status: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: 0
    }
});

(async() => {
    ...
    await Task.create({ name: 'First task', status: 1 }, { transaction });
    await Task.update({ status: 2 }, { where: { status: 1 }, transaction });
})();
```

## What do you expect to happen?

Output valid SQL queries with inserted binded parameters' values in console:

```sql
INSERT INTO "task" ("id","created_at","updated_at","name","status") VALUES (DEFAULT,'2018-10-23 13:58:05.380 +00:00','2018-10-23 13:58:05.380 +00:00','First task',1) RETURNING *
UPDATE "task" SET "status"=2,"updated_at"='2018-10-23 13:58:05.398 +00:00' WHERE "status" = 1
```

## What is actually happening?

I get SQL queries with tokens starting with `$` instead of parameters' values:

```sql
INSERT INTO "task" ("id","created_at","updated_at","name","status") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING *;
UPDATE "task" SET "status"=$1,"updated_at"=$2 WHERE "status" = $3
```

Note that `bulkCreate` method works fine.

__Dialect:__ postgres
__Dialect version:__ 7.5.0
__Database version:__ 9.5.14
__Sequelize version:__ 5.0.0-beta.13
__Tested with latest release:__ Yes (latest beta version 5.0.0-beta.13)

**Comment by sushantdhiman** [comment]
Sequelize v5 is using bound parameters for INSERT and UPDATE statements. I guess we can append data in query logs

**Comment by spearmootz** [comment]
this is still happening in beta.14

**Comment by lerit** [comment]
same question [here](https://stackoverflow.com/questions/52750937/sequelize-how-disable-output-sql-with-bindparam-when-logging)

**Comment by sheldhur** [comment]
As a temporary solution, you can get bindings from the logger args.

```js
(sql, ...args) => {
  let instance = args.pop();
  let banchmark = args.pop();

  console.log(sql, banchmark, instance.bind);
}
```

PS. @sushantdhiman It would be nice to pass a logger args as one object ```{sql, banchmark, bind, instance}```

**Comment by eggerand13** [comment]
Is there already some kind of solution for this?
Today we were forced to update to v5 due to the critical SQL injection vulnerability in Sequelize (https://snyk.io/vuln/SNYK-JS-SEQUELIZE-450221) but now we are lacking the ability to see the insert logs.

**Comment by superlbr** [comment]
it's better to have a timetable for closing issues, not just let it hang, let pr hang

**Comment by papb** [comment]
Hello @superlbr, I understand that you are anxious for fixes, we all are! Unfortunately, open source development has this kind of problems...

If you really need the fix from that PR the way it currently is, [read this comment I wrote on another issue](https://github.com/sequelize/sequelize/pull/10281#issuecomment-511789054) and do something similar.

**Comment by superlbr** [comment]
@papb for me, just modify code in node_modules, 1 min. What I suggest is merge pr first and implement later or by someone else.

**Comment by Nogias9x** [comment]
Sorry, any updates?

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/11267

**Comment by hiteshgarg14** [comment]
Set `logQueryParameters: true` while creating a new Sequelize class instance.

For eg,

```
const sequelize = new Sequelize('database', 'username', 'password', {
  host: 'localhost',
  dialect: /* one of 'mysql' | 'mariadb' | 'postgres' | 'mssql' */,
  logQueryParameters: true,
});
```

**Comment by ezze** [comment]
@sushantdhiman @papb I believe that it should be reopened. Still the issue in 5.21.5.

I updated the [repo to reproduce](https://github.com/ezze/sequelize-log-sql-issue).

**Comment by ezze** [comment]
Ok, settings `logQueryParameters` to `true` doesn't work for me. Result is the same.

```javascript
const connection = new Sequelize(database, username, password, {
    dialect,
    host,
    define: {
        freezeTableName: true,
        underscored: false,
        createdAt: 'createdAt',
        updatedAt: 'updatedAt'
    },
    logQueryParameters: true,
    logging: message => {
        console.log(message);
    }
});
```

Anyway, if it would worked, there are still questions for me.

1. Why do we need `logQueryParameters` at all and why do we need to log placeholders by default? v4 was working without it.

2. Current default behavior is useless. Even if we consider that logging placeholders is what we need it doesn't work as expected. Placeholders are logged for single inserts and updates while values are logged for bulk inserts and selects.

**Comment by Nogias9x** [comment]
Works with `"sequelize": "^5.21.2"` @ezze 

```js
const sequelize = new Sequelize(
  process.env.DB_DATABASE_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: 'mysql',
    logQueryParameters: true,
    logging: statement => { console.log(statement); }
  }
);
```

However, I agree with you, for debugging, I have to copy params into placeholders before I can execute them at DB.

**Comment by ezze** [comment]
@Nogias9x, does it depend on dialect? I use `pgsql` and `logQueryParameters` doesn' work for me with the repo I mentioned above.

**Comment by Nogias9x** [comment]
Sorry, I'm not sure @ezze

**Comment by phoenixweiss** [comment]
`logQueryParameters: true` still not working for a single `update` or `insert` in `"sequelize": "^6.6.2"`.

**Comment by YavorK** [comment]
> As a temporary solution, you can get bindings from the logger args.
> 
> ```js
> (sql, ...args) => {
>   let instance = args.pop();
>   let benchmark = args.pop();
> 
>   console.log(sql, benchmark, instance.bind);
> }
> ```
> 
> PS. @sushantdhiman It would be nice to pass a logger args as one object `{sql, benchmark, bind, instance}`

I refined the function a bit because it was outputting too much info sometimes so here it is only for query + params
```js
function logToConsole(sql, ...args) {
    let instance = args.pop();
    console.log('---')
    // query has bound params (insert, delete, update)
    if(instance && instance.bind ){
        // log query + query params
        console.log(sql, instance.bind)
    } else {
        // log a query that has no bound params (select, raw)
        console.log(sql)
    }
}
```
