### ISSUE TITLE
Order by through table field.

### ISSUE THREAD

**Issue by kasora** [sequelize/sequelize#10074]
I have a n:m associate: `User` and `Work` is associated through `UserWork`
I want to get someone's work order by `UserWork.order`.
How can I do it without `Sequelize.literal`.

I find the same issue #7634 .
But There is no useful solution and it is closed...
Here is the demo. May I get any help?
```js
let User = sequelize.define('user', { name: Sequelize.STRING });
let Work = sequelize.define('work', { name: Sequelize.STRING });
let UserWork = sequelize.define('user_work', { order: Sequelize.INTEGER });

let init_db = async () => {
  Work.belongsToMany(User, { through: UserWork, constraints: false });
  User.belongsToMany(Work, { through: UserWork, constraints: false });

  await User.sync({ force: true });
  await Work.sync({ force: true });
  await UserWork.sync({ force: true });
};

let insertData = async () => {
  await User.create({ id: 1, name: 'userA' });
  await Work.create({ id: 1, name: 'workA' });
  await Work.create({ id: 2, name: 'workB' });
  await UserWork.create({ userId: 1, workId: 1, order: 1 })
  await UserWork.create({ userId: 1, workId: 2, order: 2 })
};

let start = async () => {
  await init_db();
  await insertData();

  let userRes = await User.findAll({
    where: { id: 1 },
    include: [
      {
        model: Work,
      }
    ],
    order: [
      // I would't like to use literal...
      [Sequelize.literal('`works.user_work.order`')]
    ]
  });
};

start();
```
Sequelize version: 4.41.0
Tested with latest release: yes 4.41.0

**Comment by kasora** [comment]
```js
    order: [
      [Work, UserWork, 'order']
    ]
```
Resolved.

**Comment by josecolella** [comment]
@kasora I'm having the same issue, but the solution you have posted does not work for me

https://github.com/RobinBuschmann/sequelize-typescript/issues/559

**Comment by kasora** [comment]
I tried again in 
```
{
  "dependencies": {
    "mysql2": "^1.6.5",
    "sequelize": "^4.42.1",
  }
}

```
It works fine for me...
Maybe we used the different version of Sequelize?
Could you try the following code again?
You can change the order field in function `insertData`. I think it will works as expect.
```js
let User = sequelize.define('user', { name: Sequelize.STRING });
let Work = sequelize.define('work', { name: Sequelize.STRING });
let UserWork = sequelize.define('user_work', { order: Sequelize.INTEGER });

let init_db = async () => {
  Work.belongsToMany(User, { through: UserWork, constraints: false });
  User.belongsToMany(Work, { through: UserWork, constraints: false });

  await User.sync({ force: true });
  await Work.sync({ force: true });
  await UserWork.sync({ force: true });
};

let insertData = async () => {
  await User.create({ id: 1, name: 'userA' });
  await Work.create({ id: 1, name: 'workA' });
  await Work.create({ id: 2, name: 'workB' });
  await UserWork.create({ userId: 1, workId: 1, order: 2 })
  await UserWork.create({ userId: 1, workId: 2, order: 1 })
};

let start = async () => {
  await init_db();
  await insertData();

  let userResList = await User.findAll({
    where: { id: 1 },
    include: [
      {
        model: Work,
      }
    ],
    order: [
      [Work, UserWork, 'order']
    ]
  });

  console.log(JSON.stringify(userResList.map(userRes => userRes.toJSON()), null, 2));
};

start();
```

**Comment by kyomic** [comment]
> > ```js
> > order: [
> >   [Work, UserWork, 'order']
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Resolved. It seem strange... The real chain is `User`-`UserWork`-`order`. But the way to use order must be written like `Work`-`UserWork`-`order` And if includes more models such as `group`. It will be written like
> 
> > 
> 
> Yeah, strange that aliases like ['Work', 'UserWork', 'order'] don't working. Got same case with api upon sequelize 5. If i use models in order array elements - it's working. When aliases or names - not working, however many to many association sequelize converts to model internally but through table not. Example:
> 
> if I have **cars** model and **serviceProviders** model with **BelongsToMany** association and through table **cars_service_providers** Ordering cars by through table fileld **active**: Works: "order":[["serviceProviders", {"model":"cars_service_providers"}, "active","asc"]] but Not work: "order":[["serviceProviders", "cars_service_providers", "active","asc"]] (it tries to join cars_service_providers with active without dot and crashes.

NICE!!! it work at version 6.12.0
