### ISSUE TITLE
Setters dont work with hooks disabled

### ISSUE THREAD

**Issue by nuance-heramb** [sequelize/sequelize#10070]
## What are you doing?
I have noticed that the setters don't actually work if hooks are disabled. I cannot find anything about it online.

```js
// In the model
'quantity'     : {
  set(quantity) {
    this.setDataValue('quantity', quantity * 100);
  }

// When updating using both bulk update method
.update({
   'quantity' : quantity,
}, {
    'hooks':false,
    'individualHooks':true
})

//When updating using instance update method
.update({
   'quantity' : quantity,
}, {
    'hooks':false
})
```

## What do you expect to happen?
I expected the quantity in the db to be multiplied by 100

## What is actually happening?
The quantity is not being multiplied by 100. However if i add a console log in the setting, i can see its being called!

__Dialect:__ postgres
__Database version:__ 10.4.0
__Sequelize version:__ 4.39.0
__Tested with latest release:__ No

**Comment by ugogiordano87** [comment]
I just replied you example and It's working for me and I think it's working for you too.
How are you calling the update methods? 
Are you **waiting** for the returned `Promise`?
