### ISSUE TITLE
How to intercept connections to the database

### ISSUE THREAD

**Issue by onhernandes** [sequelize/sequelize#10083]
I'm trying to write tests for some functions that depends on Sequelize and consume data from MySQL, but I don't want my tests to really hit the db, I want just to mock the return. I tried to look on the source code but didn't find anything helpful - I know I can mock the whole Sequelize but this would be like the last shot for me now.

Is there any way to intercept the connections made to the database or the Model's methods?

I'm using jest for testing.

Other way of doind this would be mocking the Model's declaration file itself(the one that I use `sequelize.define`) and force the return.

**Comment by sushantdhiman** [comment]
You can stub out `sequelize.query` which is used by all methods to actually run query against database. You can study how sequelize do its[ unit testing](https://github.com/sequelize/sequelize/tree/master/test/unit), which also never hits any database

**Comment by onhernandes** [comment]
Thanks! I mocked everything with just one file. :)

```
const Sequelize = require('sequelize');

let __mocks = {};

const Document = function (doc) {
  return {
    get: key => {
      if (typeof key === 'string') {
        return doc[key];
      }

      if (key.plain) {
        return doc;
      }

      return doc;
    }
  };
};

Sequelize.setMock = function (op, data) {
  __mocks[op] = Array.isArray(data) ? data.map(Document) : Document(data);
};

Sequelize.resetMock = function (op) {
  if (op) {
    __mocks[op] = {};
  } else {
    __mocks = {};
  }
};

Sequelize.prototype.query = function (sql, opt) {
  const returnData = __mocks[opt.type] || [];
  return Sequelize.Promise.resolve(returnData);
};

module.exports = Sequelize;
```
