### ISSUE TITLE
Virtual fields that rely on sibling fields

### ISSUE THREAD

**Issue by ryanburnette** [sequelize/sequelize#10082]
## What are you doing?

When you have a model with virtual fields that rely on other fields then you exclude that field in a query, your custom getter doesn't work. Is this a feature that should be added? Or is there a better pattern I should be using?

```js
module.exports = function (sequelize,DataTypes) {
  var Widget = sequelize.define('Widget',{
    data: {
      type: DataTypes.TEXT
    },
    info: {
      type: DataTypes.VIRTUAL,
      get: function () {
        return JSON.parse(this.data).info;
      }
    }
  });
};
```

Excluding the `data` field would break the query.

## What do you expect to happen?

Wanted my virtual field tow work

## What is actually happening?

My virtual field doesn't work when the requisite sibling fields are excluded from the query.

__Dialect:__ sqlite
__Dialect version:__
__Database version:__
__Sequelize version:__ 4.41.0
__Tested with latest release:__ 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by ryanburnette** [comment]
I guess I could parse the JSON once and put the parsed results into real fields, but I'm asking the question partially in principle.

**Comment by sushantdhiman** [comment]
Virtual type accepts dependent attributes which get pulled when virtual field is used

```js
{
  active: {
    type: new DataTypes.VIRTUAL(DataTypes.BOOLEAN, ['createdAt']),
    get: function() {
      return this.get('createdAt') > Date.now() - (7 * 24 * 60 * 60 * 1000)
    }
  }
}
```

**Comment by ryanburnette** [comment]
Thanks for the help comprehending the doc.
