### ISSUE TITLE
getting an association should be possible through get

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#10084]
When you retrieve an association, against a sequelize instance, AFAIK, you need to use something like `item.getAssociatedInstance()`.

That is very unpractical in generic functions, because it requires you to construct a function from a key, capitalize the first character and call it. It also requires me to know which key is an association and 
which is not. It just feels very artificial to me.

Why can't I just `item.get('associatedInstance')` based on the  `as` key in the association definition.

## What are you doing?

```js
        Item.associate = models => {
		Item.belongsTo(models.AssociatedInstance, {
			foreignKey: 'itemId',
			as: 'associatedInstance'
		});
	};
```

## What do you expect to happen?
`item.get('associatedInstance')` should retrieve the associated instance.

it should be smart enough to re execute the query if there's already a reference there.

## What is actually happening?
`item.get('associatedInstance')` returns undefined if the association is not already retrieved through an `include` query.

`item.getAssociatedInstance()` does execute the query.

__Dialect: mysql
__Sequelize version: 4.38.0
__Tested with latest release: Yes

**Comment by sushantdhiman** [comment]
No, `get` should never execute a query to retrieve data, that will have huge performance implication, not to mention `get` will become async. I think having `get` to just proxy `dataValues` just like it do for now is perfectly valid
