### ISSUE TITLE
@types/sequelize: 4.27.29 needs updated, findByPk not included

### ISSUE THREAD

**Issue by TENDesign** [sequelize/sequelize#10089]
I am currently using` "sequelize": "^4.41.0"` and `"@types/sequelize": "4.27.29"` in my typescript app. I 've recently been getting warnings that `findById` is deprecated and to use `findByPk`. After some research, there seems to not be a typing for `findByPk`

**Comment by eseliger** [comment]
this repository is not including @types/sequelize. Please raise this issue at DefinitelyTyped if you believe this is an error with the types
