### ISSUE TITLE
TypeError for disabled timestamp `deletedAt` column 

### ISSUE THREAD

**Issue by onhernandes** [sequelize/sequelize#10099]
## What are you doing?
First define a Schema and disable `deletedAt`, when you try to create or list data from Sequelize, it throws an error because it tries to use `hasOwnProperty` on `undefined` attribute. I don't know if this happens with `updatedAt` too.

```js
// Model definition
...
const options = {
  timestamps: false,
  deletedAt: false
};
```

## What do you expect to happen?
`deletedAt` should be removed from my schema and shouldn't have any validation for that column.

## What is actually happening?
It throws error(sorry for the printscreen, I can't get the error itself now): 
![image](https://user-images.githubusercontent.com/12698656/47750302-e10be800-dc6d-11e8-8d74-ce197fda0011.png)

__Dialect:__ mysql
__Dialect version:__ 5.7
__Database version:__ 5.7
__Sequelize version:__ 4.38.0
__Tested with latest release:__ No

**Comment by tsasaki609** [comment]
I checked with a simple model definition, but no error occurred on master and v4 branch.
I'll try to fix it if it occurs in the latest version...

**Comment by sushantdhiman** [comment]
Yep, I tested this on `master`. no error

```js
const Parent = sequelize.define('Parent', {
  data: {
    type: Sequelize.INTEGER,
    allowNull: false
  }
}, {
  timestamps: false,
  deletedAt: false
});

sequelize.sync({ force: true }).then(async () => {
  const p = await Parent.create({ data: 1 });
  console.log(p);
})
```

**Comment by heinosasshallik** [comment]
@sushantdhiman @tsasaki609 
I'm getting the same problem, except in my case, timestamps has to be enabled. This is roughly the setup needed to replicate the issue:

Postgresql:
```
create table test (
   id integer primary key,
   creation_time timestamptz,
   updatetime timestamptz
)
```
model.js:
```
module.exports = function (sequelize, DataTypes) {
  return sequelize.define('test', {
    creationTime: {
      type: DataTypes.DATE,
      field: 'creation_time',
      defaultValue: DataTypes.NOW,
    },
    updateTime: {
      type: DataTypes.DATE,
      field: 'update_time',
      defaultValue: DataTypes.NOW,
    },
    id: {
      type: DataTypes.BIGINT,
      field: 'id',
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
    },
  }, {
    tableName: 'test',
    timestamps: true,
    createdAt: "creation_time",
    updatedAt: "update_time",
    deletedAt: false,
  });
};
```
code:
```
test = sequelize.import(`${__dirname}/model.js`)
return test.findAll();
```
