### ISSUE TITLE
SQlite3 dialect promise rejection returning undefined promise

### ISSUE THREAD

**Issue by jordantogether** [sequelize/sequelize#10093]
## What are you doing?
Trying to create a SQlite3 instance, when using an incorrect file path. 
```js
var Sequelize = require('sequelize');

var sequelize = new Sequelize('mainDB', null, null, {
    dialect: "sqlite",
    storage: './nonexistent.path.sqlite',
});

const isWorking= await sequelize.authenticate(); // Should be error, isn't.

// OR
var sequelize = new Sequelize('mainDB', null, null, {
    dialect: "sqlite",
    storage: './nonexistent.path.sqlite',
});

  sequelize.authenticate()
  .then(function(err) {
    console.log('Connection has been established successfully.');
  }, function (err) {
    console.log('Unable to connect to the database:', err);
  });

// Errors - sequelize is undefined.

```

## What do you expect to happen?
Get an error saying can't find the file. 

## What is actually happening?
Get an error saying sequelize authenticate is undefined (i.e. doesn't return promise).

_Output, either JSON or SQL_

## Pull request
I've added a pull request to resolve the issue, creating the bug to resolve. 👍 

__Dialect:__ sqlite
__Dialect version:__ Latest
__Database version:__ Latest
__Sequelize version:__ Latest
__Tested with latest release:__ Yes (If yes, specify that version) : __v5.0.0-beta.13__

## More info
* __NodeJs__: nodeJs version 10.0.0
* __NPM__: npm version 6.4.1
* __OS__: Windows 10 Pro, 10.0.15063 Build 15063 on VMWare Virtual Machine, Intel Xeon E5-2699A v4 @ 2.40GHz, 2394 Mhz, 2 Core(s), 2 Logical Processor(s)
* __SQLite Version__: "sqlite3": "^4.0.2"

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
> Sequelize version: Latest
> Tested with latest release: Yes (If yes, specify that version)

You failed to specify most important detail :)

**Comment by jordantogether** [comment]
Updated, my apologies. Also, I'm doing the pull request and it looks like there are existing errors in master, do I need to fix those before I do a pull request? There's over 25 errors currently.

**Comment by sushantdhiman** [comment]
latest master build looks green to me https://travis-ci.org/sequelize/sequelize/builds/447361698?utm_source=github_status&utm_medium=notification

**Comment by sushantdhiman** [comment]
Make sure to do git pull from upstream not your fork which might be outdated

**Comment by sushantdhiman** [comment]
Actually this is not a bug, at least not at Sequelize / SQLite level as they create file path if it doesn't exists. Also I had close look at your code and error is `sequelize is undefined`, looks like userland issue

**Comment by jordantogether** [comment]
This is sadly not true, though. Sequelize *is* defined, but when the SQLite instance is called, Sequelize *becomes* undefined. I'll submit the PR again when I get chance.

**Comment by sushantdhiman** [comment]
`Sequelize becomes undefined`? Let's first try to reproduce this rather than fixing it, do you have something that reproduce that error like a SSCCE

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396 that error
