### ISSUE TITLE
Sequelize - Promise.all returning “cannot ready property 'getTableName' of undefined”

### ISSUE THREAD

**Issue by Maverick96** [sequelize/sequelize#10112]
I have three tables :
**Orders**
orderId | price | quantity | areaId | customerId

**Areas**

areaId | name | areaCode

**Customers**

customerId | name | email | mobile

I'm using sequelize as my ORM.

I have created the following associations:

```
Orders.belongsTo(models.Customers, {
        foreignKey: 'customerId',
        as: 'Customer'
    });

    Orders.belongsTo(models.Area, {
        foreignKey: 'areaId',
        as: 'Area'
    });
```
I want to fetch Orders which belong to particular areas and run a search query on the result I get.

I also have to implement pagination on the server side. I'm executing two queries right now, one to fetch the Orders with limit applied(for pagination) and the other fetch the total number of records.

```
Promise.all([ /*Query 1 to get paginated result*/
            Orders.findAll({
                attributes: ['orderId', 'addressLine1', 'addressLine2', 'Price','Quantities',
                    'areaId', 'customerId'
                ],
                where: {
                    [Op.and]: {
                        areaId: areaId,
                        [Op.or]: {
                            '$Area.name$': {
                                [Op.like]: '%' + searchTerm + '%'
                            },
                            '$Customer.name$': {
                                [Op.like]: '%' + searchTerm + '%'
                            },
                            addressLine1: {
                                [Op.like]: '%' + searchTerm + '%'
                            },
                            addressLine2: {
                                [Op.like]: '%' + searchTerm + '%'
                            }
                        }

                    }
                },
                include: [{
                        model: Area,
                        as: 'Area',
                        attributes: ['name', 'areaId']
                    },
                    {
                        model: Customers,
                        as: 'Customer',
                        attributes: ['name', 'id']
                    }
                ],
                limit,
                offset
            }),
            /*Query 2 to get total number of records*/
            Orders.findAll({
                attributes: ['orderId'],
                where: {
                    [Op.and]: {
                        areaId: areaId,
                        [Op.or]: {
                            '$Area.name$': {
                                [Op.like]: '%' + searchTerm + '%'
                            },
                            '$Customer.name$': {
                                [Op.like]: '%' + searchTerm + '%'
                            },
                            addressLine1: {
                                [Op.like]: '%' + searchTerm + '%'
                            },
                            addressLine2: {
                                [Op.like]: '%' + searchTerm + '%'
                            }
                        }

                    }
                },
                include: [{
                        module: Area,
                        as: 'Area',
                        attributes: ['name', 'areaId']
                    },
                    {
                        module: Customers,
                        as: 'Customer',
                        attributes: ['name', 'customerId']
                    }
                ]
            })
        ])
    })
    .then(orderData => {
        res.json({
            data: orderData[0],
            total: orderData[1].length
        })
    })
```

I'm getting this error on executing the above queries:

> TypeError: Cannot read property 'getTableName' of undefined at Function._validateIncludedElement (/home/dell/Desktop/24klen_backend/node_modules/sequelize/lib/model.js:465:30)

**Note :** I'm getting the result if I only run the 1st query. Executing both queries using Promise.all throws the above error. So my hunch is that executing both queries asynchronously is causing this issue.

Let me know if further clarification is required. Thank You.

**Comment by sushantdhiman** [comment]
Please follow the issue template :)

------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
