### ISSUE TITLE
Hooks only work when define inside options

### ISSUE THREAD

**Issue by Oskang09** [sequelize/sequelize#10135]
## What are you doing?

Here is mine lifecycle builder for concat all hooks. but unfortunately only work via this way. when i apply generated object to `options.hooks` before model define not working at all, also Model direct method hooks not working too. 

Using with [Sails-Hook-Sequelize](https://github.com/KSDaemon/sails-hook-sequelize)

* Tried `runHooks(hookname, instance, options)` myself and work well returned true mean exists & undefined mean no hooks rite?.
* Since using with `sails-hook-sequelize` tried to define after model definition `modelClass.addHook('hooktype', 'fn')`, `modelClass[hooktype](fn)` not working too.
*  Add generated hooks object to `options.hooks` not working too.

```js
options: 
    {
        timestamps: true,
        paranoid: true,
        hooks: require('@lifecyclebuilder')([
            'joi-schema',
            'status-former',
            {
                beforeCreate: async (instance, opt) =>
                {
                    let query;
                    let randomPin;
                    do
                    {
                        randomPin = Math.floor(1000 + Math.random() * 9999).toString();
                        query = await employee.findOne({
                            where: {
                                merchantId: instance.merchantId,
                                employee_pin: randomPin
                            }
                        });
                    }
                    while (query);
                    instance['employee_pin'] = randomPin;
                    return instance;
                },
            }
        ]),
    },
```
**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Follow the issue template

----------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
