### ISSUE TITLE
Sequelize should warn when illegal option keys are used

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#10136]
I spent a couple of hours debugging an issue that lead to a hard crash of node. It turned out to be a simple and stupid mistake, but it did make we wonder why Sequelize didn't catch this issue.

## What are you doing?
I have a model that looks something like this

```js
import CustomError from '../../helpers/CustomError';
import { searchText } from '../../helpers/urlParameters';

export default (sequelize, DataTypes) => {
	const Sector = sequelize.define(
		'Sector',
		{
			id: {
				type: DataTypes.UUID,
				defaultValue: DataTypes.UUIDV4,
				primaryKey: true,
				lowercase: true,
			},
			label: {
				type: DataTypes.STRING(255),
			},
		},
		{
			tableName: 'Sectors',
			timestamps: true,
		}
	);

	Sector.filterAttributes = Object.keys(Sector.rawAttributes);

	Sector.getInclude = () => [{
              model: sequelize.models.SomethingElse,
              as: 'widgets',
              include: sequelize.models.getInclude()
        }];

	Sector.addInclude = () => [{
              model: sequelize.models.SomethingElse,
              as: 'widgets',
              include: sequelize.models.SomethingElse.addInclude()
        }];

	Sector.associate = models => {
                 Sector.hasMany(models.SomethingElse, { 
                         foreignKey: 'somethingElseId' 
                 });
		Sector.belongsTo(models.Site, {
			foreignKey: 'tenantId',
		});
	};

	return Sector;
};

```

the `getInclude` and `addInclude` arrays I use in the service layer when I construct `findAll`, `create` and `update` sequelize method calls to construct the correct `includes`

## What do you expect to happen?
I would expect Sequelize to warn me that `include: sequelize.models.getInclude()` is wrong in some way. It should validate the input.

## What is actually happening?
Node crashes completely. There is no proper reference to why or how. In a large code base this typo is hard to find.

__Dialect:__ mysql
__Sequelize version:__ 4.38.0
__Tested with latest release:__ Yes

**Comment by mschipperheyn** [comment]
So, just had another one of these. The common theme of all these kinds of issues is that sequelize doesn't warn you when you use illegal option keys. I used an `include` on an association definition, also leading to a crash. 

What should be happening is sequelize warning that `include` is an illegal key

**Comment by frlinw** [comment]
I'm using custom key on associations & fields and I'm glad there is no restriction.
If there is a strict check of allowed params, think about adding a property to hold custom properties

**Comment by papb** [comment]
Closing in favor of #11872
