### ISSUE TITLE
Release v4 npm package - 4.42.0

### ISSUE THREAD

**Issue by tzellman** [sequelize/sequelize#10131]
Due to the semantic-release change made at 8f39f4538399f08429a29938a26dffbe633b8a06, it is not possible to use sequelize as a dependency installed directly from the github repository along with `sequelize-typescript`. `sequelize-typescript` references the `package.json` of `sequelize` in order to determine which version is being used, and thus will try to use the v0 Models.

Can we get a version bump for the v4 branch in order to get the latest changes that were pushed? Specifically, https://github.com/sequelize/sequelize/pull/10121.

Thanks!

**Comment by sushantdhiman** [comment]
Build breaking due to https://github.com/sidorares/node-mysql2/issues/872

**Comment by sushantdhiman** [comment]
I have locked `mysql2` version on v4 branch, it should get released now
