### ISSUE TITLE
Sequelize has no built-in methods for allowing/disallowing parameters on update/create

### ISSUE THREAD

**Issue by aaronfulkerson** [sequelize/sequelize#10139]
## What are you doing?
Trying to exclude some parameters from the model I want to update so that a malicious user can't send attributes that I don't want updated.

```js
scopes: {
  update () {
    return {
      attributes: {
        exclude: [ ...atributes ]
}}}}
```

## What do you expect to happen?
I was thinking it would be fantastic if the attributes became inaccessible whenever they were excluded with a scope on class methods like update()

## What is actually happening?
See above.

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
This is now supported in v5
