### ISSUE TITLE
scope not working correctly under include in v4

### ISSUE THREAD

**Issue by abhinavj13** [sequelize/sequelize#10147]
## What are you doing?
Table A 
id | participantType | participantId | comment
1     B                            1                     "some comment"
1     C                            2                    "another comment"
1     B                            2                    "one more comment"

Table B
id | otherData
1    "I am 1"
2    "I am 2"

models.A.belongsTo(models.B, {
     foreignKey: 'participantId',
     scope:{
          participantType: 'B'
     },
     constraints: false
});

## What do you expect to happen?
select * from A inner join B (on A.participantId = B.id) where A.participantType = 'B'

## What is actually happening?
select * from A inner join B (on A.participantId = B.id) where B.participantType = 'B'

__Dialect:__ mysql 

This was working fine till v3, but is generating the latter sql query in v4.
Any help is appreciated.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
