### ISSUE TITLE
Double timestamps in JSON

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#10151]
I dont know from which version but this bug #6426 is back in 4.41.1 & 4.41.2 at least.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by sushantdhiman** [comment]
@JSteunou Can you pinpoint breaking version?

**Comment by sushantdhiman** [comment]
@JSteunou You can see there is an additional test which specifically tests presence of `createdAt` against `created_at` https://github.com/sequelize/sequelize/pull/6219/files

Do you think this test is incorrect?

**Comment by sushantdhiman** [comment]
Also try removing node_modules and may be clear npm cache etc

**Comment by JSteunou** [comment]
The test does not set `timestamps: true`

**Comment by sushantdhiman** [comment]
@JSteunou right, i'll reopen this.

**Comment by sushantdhiman** [comment]
@JSteunou Can you also try with `master` branch?

**Comment by JSteunou** [comment]
Nope sorry. I tried but to much error to solve going on from 4.41 to v5 beta to get my test working.

**Comment by sushantdhiman** [comment]
I have verified that test is working properly, I forgot last time that `timestamps: true` by default

**Comment by JSteunou** [comment]
That does not make the bug going away, I still have the issue :(

**Comment by sushantdhiman** [comment]
@JSteunou Then submit a SSCCE or any reproducible code
