### ISSUE TITLE
Can't create a sequelize instance without a pool

### ISSUE THREAD

**Issue by Wolfie010** [sequelize/sequelize#10153]
## What are you doing?
Trying to create a sequelize instance without pool.  

## What do you expect to happen?
I don't want a pool created

## What is actually happening?
The library says setting pool to false is now invalid.Can you update the latest docs to mirror this? 

__Dialect:mysql
__Dialect version:mysql
__Database version:5.6
__Sequelize version:4

**Comment by sushantdhiman** [comment]
Use `min: 0` and `max: 1`, you will essentially get a single connection sequelize instance, although I wont recommend this for any thing production
