### ISSUE TITLE
Modifications in afterCreate hooks are not saved

### ISSUE THREAD

**Issue by zypA13510** [sequelize/sequelize#10155]
## What are you doing?
I'm creating a column that depends on the value of other columns. So I've created a hook to automatically generate the value. However, it is not working as expected. The actual code is much more complex but the following example should give you an idea of what I'm trying to accomplish.

```js
const Employee = sequelize.define('employee', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  firstName: {
    type: Sequelize.STRING(50),
    field: 'first_name',
  },
  lastName: {
    type: Sequelize.STRING(50),
    field: 'last_name',
  },
  emailAddress: {
    type: Sequelize.STRING(50),
    field: 'email_address',
  },
}, {
  timestamps: false,
  hooks: {
    afterCreate: (employee, options) => {
      employee.update({
        // John Doe (ID: 2048) -> John.D_48@example.com
        // Jane Doe (ID: 2)    -> Jane.D_02@example.com
        emailAddress: `${employee.firstName}.${employee.lastName.slice(0, 1)}_${String(employee.id).slice(-2).padStart(2, '0')}@example.com`,
      });
      // Alternatively, assign the attribute directly, also not working
      /* employee.emailAddress = `${employee.firstName}.${employee.lastName.slice(0, 1)}_${String(employee.id).slice(-2).padStart(2, '0')}@example.com`; */
    },
  },
});

(async () => {
  let johnDoe = await sequelize.transaction((transaction) => Employee.create({
    firstName: 'John',
    lastName: 'Doe',
  }, {transaction: transaction}));
  console.log(johnDoe.emailAddress);
})();
```

## What do you expect to happen?
Console output `John.D_01@example.com` and saved to `email_address` column.

## What is actually happening?
Console output
```
Executed (b671eb2a-92f7-49b6-aca5-2f6057f6b871): START TRANSACTION; Elapsed time: 1ms
Executed (b671eb2a-92f7-49b6-aca5-2f6057f6b871): INSERT INTO `employees` (`id`,`first_name`,`last_name`,`email_address`) VALUES (DEFAULT,'John','Doe',''); Elapsed time: 1ms
Executed (b671eb2a-92f7-49b6-aca5-2f6057f6b871): COMMIT; Elapsed time: 10ms
John.D_01@example.com
```
**Not saved** to `email_address` column!

------
__Dialect:__ mysql
__Database version:__ mariadb-server 5.5.60-1.el7_5
__Sequelize version:__ 4.41.2

**Comment by zypA13510** [comment]
Maybe related:
* #3534 mentioned that it is _only_ not working in `beforeValidate` and `afterValidate` hooks. However this is not true, as demonstrated here.
* Adding `options.fields.push('YOUR_MODIFIED_FIELD');` as mentioned in #8586 does not work.

------
Also, I've traced the bug to here, but I cannot understand why it happened:

#### [lib/model.js#L3597](/sequelize/sequelize/blob/v4.41.2/lib/model.js#L3597)
```
    return Promise.try(() => {
      // Validate
      if (options.validate) {
        return this.validate(options);               // L3600, breakpoint 1
      }
    }).then(() => {
      // Run before hook
      if (options.hooks) {                           // L3604, breakpoint 2
        const beforeHookValues = _.pick(this.dataValues, options.fields);
        let ignoreChanged = _.difference(this.changed(), options.fields); // In case of update where it's only supposed to update the passed values and the hook values
        let hookChanged;
        let afterHookValues;
```
Here, I've placed two breakpoints, one at line 3600, another at line 3604. At the first breakpoint, `this._changed` evaluated to `{firstName: true, lastName: true, id: true, emailAddress: true}`. I've also traced various operations in `this.validate`, I cannot find anywhere `this._changed` being modified. Then at the second breakpoint, `this._changed` suddenly became all `false`. Eventually, sequelize did a final check at line 3664, it determined that `this` is not changed, and `this` is not a new record, so it just aborted saving.

#### Call stack (at the first breakpoint, line 3600)
Promise.try (model.js:3600)
tryCatcher (util.js:16)
Promise.attempt.Promise.try (method.js:39)
save (model.js:3597)
update (model.js:3857)
afterCreate (my-example.js:34)

**Comment by akmozo** [comment]
I think that you should only return that promise : 
```javascript
    afterCreate: (employee, options) => {
      return employee.update({
        emailAddress: `${employee.firstName}.${employee.lastName.slice(0, 1)}_${String(employee.id).slice(-2).padStart(2, '0')}@example.com`,
      });
    },
```

**Comment by zypA13510** [comment]
@akmozo Ok, I think this along with passing `options.transaction` to `employee.update` did it.

However, I've seen several examples [here in the doc](http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks) that use direct assignment, e.g. `user.mood = 'happy';`. If returning the Promise is required then the examples are wrong, that they did not return any `Promise` in the hook, aren't they?

**Comment by sushantdhiman** [comment]
`afterCreate` needs `transaction` if record was created in transaction as you have figured out. Promise is necessary when you are doing an async operation like `.update` here.  `user.mood = 'happy';` will work in `before*` hooks as record is not yet saved

**Comment by kwanso-nadeem** [comment]
> @akmozo Ok, I think this along with passing `options.transaction` to `employee.update` did the trick.
> 
> However, I've seen several examples [here in the doc](http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks) that use direct assignment, e.g. `user.mood = 'happy';`. If returning the Promise is required then the examples are wrong, that they did not return any `Promise` in the hook, aren't they?

This is what worked for me. http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks

used `{transaction: options.transaction}`
