### ISSUE TITLE
model define incorrectly, the tablename with 's' suffix

### ISSUE THREAD

**Issue by Aopodo** [sequelize/sequelize#10163]
when i test the model define:
![image](https://user-images.githubusercontent.com/16433585/48486116-8b326500-e855-11e8-8598-3890c77ef025.png)

I get this result:
![image](https://user-images.githubusercontent.com/16433585/48486173-bcab3080-e855-11e8-937c-a4525d0dd070.png)

thy the tablename has a suffix???

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by sushantdhiman** [comment]
you have defined the name `gm_user`

**Comment by Aopodo** [comment]
i use the model Configuration tablename to set this correct

`
var gm_user = gm.define('gm_user ', {
    id: { type: Sequelize.INTEGER, primaryKey: true },
    name: Sequelize.STRING
},{
    tableName: 'gm_user '
})
`
