### ISSUE TITLE
Sequelize is not rightly updating hash value

### ISSUE THREAD

**Issue by dilagurung** [sequelize/sequelize#10160]
There is a weird issue popping out
i have a hash having value = `hash`='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk0NDY5YWY1MjdkM2RlZjBkZGMxYTRlYWU1MjdmZWQ0IiwiaWF0IjoxNTQyMTgxMzkwLCJleHAiOjE1NDIxOTIxOTB9.SxShzkA_j3wSprlt8bHwJwzxirQ-

I have update a hash attribute of my table using the following
 TempUser.update(
        {hash:hash},
        { where: { user: req.body.TempUser.user } }
    );

and the result in log is 
: **UPDATE `temp_user` SET `hash`='$2a$10$e35JRfRZdyitrkJOtrogOeuCUq1Dtwz9I0jHRytRv2z.zEYAmul9K',`updated_at`='2018-11-14 07:34:32' WHERE `user` = 'd@d.com'.**

I cannot figure out why this is happening .

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by dilagurung** [comment]
I think, this is the issue with Sequelize.

**Comment by dilagurung** [comment]
@sushantdhiman , issue is  specific to seqeulize. please dont close the issue

**Comment by sushantdhiman** [comment]
@dilagurung Follow the issue template then
