### ISSUE TITLE
Feature Request: Includes all with scope.

### ISSUE THREAD

**Issue by Oskang09** [sequelize/sequelize#10164]
Included everything with specific scope. 
```js
include: [{
    all: true,
    scope: 'scope_name'
}]
```

**Comment by sushantdhiman** [comment]
Need more clear "code" examples for your use case

**Comment by Oskang09** [comment]
for include everything we must do 
```
include: [{
    all: true
}]
```

for specific we need ```include: [{ model: model }]``` or with scope ```include: [{model: model.scope() }]```, for easier way to do this include all with scope hope added such like 


```
include: [{ all: true, scope: 'scope_name' }]
```

**Comment by ephys** [comment]
There has been no demand in 4 years, I'll close this issue
