### ISSUE TITLE
Model is not associated with another model

### ISSUE THREAD

**Issue by mi-mazouz** [sequelize/sequelize#10174]
Hello, I'm trying to create an association between user and picture models.

User model:

```
module.exports = (Sequelize, DataTypes) => {
  const Model = Sequelize.define(
    'User',
    {
      firstName: {
        type: DataTypes.STRING(50),
        allowNull: false
      },
      lastName: {
        type: DataTypes.STRING(50),
        allowNull: false
      },
      username: {
        type: DataTypes.STRING(16),
        allowNull: false
      },
    },
    {
      tableName: 'User'
    }
  )

  Model.associate = models => {
    Model.hasMany(models.Picture, { as: 'pictures', foreignKey: 'userId' })
  }

  return Model
}

```

Picture model:

```
module.exports = (Sequelize, DataTypes) => {
  const Model = Sequelize.define(
    'Picture',
    {
      path: {
        type: DataTypes.STRING(50),
        allowNull: false
      },
      isProfile: {
        type: DataTypes.BOOLEAN,
        defaultValue: false
      }
    },
    {
      tableName: 'Picture'
    }
  )

  Model.associate = models => {
    Model.belongsTo(models.User, {
      foreignKey: 'userId',
      as: 'user'
    })
  }

  return Model
}

```

My query:

```
UserModel.findByPk(userId, {
    include: [
      {
        association: 'pictures',
        attributes: ['path'],
        where: {
          isProfile: true
        }
      }
    ]
  })
```

But I got this error: Picture is not associated to User! Does anyone have ideas?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by mi-mazouz** [comment]
Nobody answer me in slack!
