### ISSUE TITLE
model::build is not being affected from scopes.

### ISSUE THREAD

**Issue by overflowz** [sequelize/sequelize#10178]
## What are you doing?

**model.js**
```js
module.exports = function (sequelize, DataTypes) {
  const model = sequelize.define('topic', {
    id: {
      primaryKey: true,
      autoIncrement: true,
      type: DataTypes.INTEGER(11).UNSIGNED,
    },
    subject: { // indexing maybe?
      type: DataTypes.STRING(255),
      allowNull: false,
      required: true,
    },
    creatorId: { // references to user.id
      type: DataTypes.INTEGER(11).UNSIGNED,
      required: true,
      allowNull: false,
    },
  });

  /* class methods */

  model.loadScopes = function (models) {
    this.addScope('withContent', {
      include: [{
        model: models.Content,
        required: false,
      }],
    });

    this.addScope('withUser', {
      include: [{
        model: models.User,
        as: 'author',
        required: false,
        attributes: ['id', 'firstname', 'lastname'],
      }],
    });
  };

  model.associate = models => {
    model.belongsTo(models.User, { as: 'author', foreignKey: 'creatorId' });
    model.hasOne(models.Content);
  };

  model.getFullTopic = function (params) {
    return this.scope('withContent', 'withUser').findOne({ where: { id: params.id } }); // works fine.
  };

  model.buildTopic = function (params) {
    return this.scope('withContent', 'withUser').build(params); // scopes are not being applied.
    // return this.build(params, { include: [{ ... }] }); // this way it works.
  };

  /* instance methods */

  model.prototype.createTopic = function () {
    return this.save();
  };

  return model;
};
```

**index.js**
```js
const topic = Model.buildTopic({ subject: 'test', content: { data: 'test data' } });
topic.createTopic(); // <-- does not save content, but it does save if I have `include` instead of scope in `buildTopic` method.
```

## Output
```
Executing (default): INSERT INTO `topics` (`id`,`subject`,`creatorId`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'abc',1,'2018-11-19 14:35:41','2018-11-19 14:35:41');
```

## What do you expect to happen?
_I was expecting this to save the content alongside with the topic._

## What is actually happening?
_It is not saving content. It is saving only topic without content when I have scopes included. If I remove scopes and add `include` property instead, it does save._

__Dialect:__ mysql
__Dialect version:__ 1.6.4
__Database version:__ 8.0.1
__Sequelize version:__ 4.41.1
__Tested with latest release:__ 4.41.2

**Comment by sushantdhiman** [comment]
No build wont apply any scopes as it is not dealing with any database operations, you can apply scopes when calling `save`

**Comment by overflowz** [comment]
@sushantdhiman Before closing, could you please write more details how can I really use that? There is no documentation for that. The `save` method does not accept any scope options, even instance does not have `scope` method itself. Also another question is, if I don't include models on `build`, when assigning nested properties (e.g. content in this case) they won't get assigned because model does not have it included. Please re-open this, it's either a bug or a feature.

**Comment by sushantdhiman** [comment]
I realize there is no way to invoke scopes on instance method, but you can workaround by invoking scopes when creating, something like this should work

```js
model.prototype.createTopic = function (object) {
   return this.constructor.scope('withContent', 'withUser').create(object);
};
```

**Comment by overflowz** [comment]
@sushantdhiman Well, if I understood correctly, calling `Model.scope(...).create(...)` and your example makes not much difference. Also I don't have parameter passed to createTopic (`object`), since it's a instance method, I don't really feel it's right to pass same parameters as instance has already. In my current scenario, I want to build model first, then do some manipulations over it and then save it with scopes.

I'm doing this because architecture I am using forbids me to create models directly (calling save). Instead, I need more control over it and then decide to save or do something else.

Another problem I see here is that, as I described below, if I don't build model with associations, the nested properties are not being assigned to that built model.

Either way, it would be nicer for `build` method to respect the `scope` , just like other methods do as I see in source (`_injectScope`).

For now, I won't be able to use scopes for that anyways.

**Comment by sushantdhiman** [comment]
You can get current instance object with `this.get()`, will looks something like

```js
model.prototype.createTopic = function () {
   return Model.scope('withContent', 'withUser').create(this.get());
};
```

**Comment by overflowz** [comment]
mhm, thanks! I'll do like that from now, but seems kinda hacky solution to me.

**Comment by overflowz** [comment]
EDIT: does not seems to work. `Content` is not being saved, only `Topic`.
SQL Output:
```
Executing (default): INSERT INTO `topics` (`id`,`subject`,`creatorId`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'test subject2',1,'2018-11-20 12:35:53','2018-11-20 12:35:53');
```

As you can see, there is no insert log for Content (nested property).

**Comment by overflowz** [comment]
EDIT: this does not work:
```js
// saves only topic.
return this.scope('withContent').create(data);
```

```js
// saves topic & associated content as well.
return this.create(data, {
  include: 'content',
});
```

**Comment by sushantdhiman** [comment]
Scopes are used for finder functions, mainly as access control. In methods like this you can pass `options.include`

**Comment by overflowz** [comment]
It is also confusing because syntax is valid for scopes, but it is ignoring them without letting user to know.
e.g.

```js
model.scope('somescope').create(obj);
```
This says that everything is cool, it does what you're expecting, but it does not.

Please re-open this thread and mark it either as a bug or a feature.

**Comment by sushantdhiman** [comment]
Can you show me your full model, I want to see how you are planning to reuse scopes like `saveTopicWithContent`, `saveTopicWithoutContent` etc among different methods, I'll try to suggest alternative.

As for using scopes in save / build, I am not going to accept that change. You can clearly reuse options object in different methods by having it generated by some helper on the fly.

```js
model.scope('somescope').create(obj); // or build, whatever.
```

It doesn't throw because scope can't see beyond its own invocation so what really going is

```js
const newModel = model.scope('somescope')

newModel.create(object);
```

scope returns a new model implement a given scope on all finder methods, then you can call any other valid methods on that new model

**Comment by overflowz** [comment]
But that is really confusing an user! just like it did to me for example and I lost like 3 hours to really understand where the bug was.

"It doesn't throw because scope can't see beyond its own invocation so what really going is"

This is not an excuse, but implementation problem (no offense). To not confuse, instead it should be like:

```js
.findAll({ ... }, { scope: 'somescope' });
```

by allowing `.scope` method instead, it is really confusing since it won't work for all the other methods.
This is the same as if there was implementation like this (rough example):

```js
.belongsToMany(...);
// vs
.belongsToMany(...).through(...);
// vs
belongsTo(...).through(...);
```

First example would throw error, by saying "through is required", second would work fine, but last one would just ignore it since it does not work with `through`, but the method is valid (should be option IMO as it is).

My question is, why scope syntax isn't the same as this one for example? Why it is not in options instead of class method?

As for the example, I'll show you what I really mean.

Imagine I have a model like this:
```js
module.exports = function (sequelize, DataTypes) {
  const model = sequelize.define('my_defined_table', {
    id: {
      primaryKey: true,
      autoIncrement: true,
      type: DataTypes.INTEGER(11).UNSIGNED,
    },
    name: {
      type: DataTypes.STRING,
    }
  });

  /* class methods */

  model.associate = models => {
    model.belongsTo(models.Model1); // optional ref
    model.belongsTo(models.Model2); // optional ref
    model.belongsTo(models.Model3); // optional ref
    model.belongsTo(models.Model4); // optional ref
    model.belongsTo(models.Model5); // optional ref
  };

  return model;
};
```

Just like I want to use scopes for .findAll, .find, etc. I want to be able to use them for creation/updating or building as well.

For example, I want to save this model with model1, model3 and model5 with some criterias.
```js
model.create({ ... }, {
  include: [{
    model: 'Model1',
    attributes: ['value1', 'value2'], // let's assume we have 10 valueX fields, but I only want to save 1 and 2.
  }, {
    model: 'Model3',
    attributes: [...],
  }, {
    model: 'Model5',
    attributes: [...],
  }]
});
```

Now for next creation from a different place, I would like to save Model1 and Model2 instead. But I want to save different attributes for Model1.
```js
model.create({ ... }, {
  include: [{
    model: 'Model1', // lost reusability here, since I have to declare it again
    attributes: ['value1', 'value2', 'value5', 'value6'], // ...?
  }, {
    model: 'Model3',
    attributes: [...],
  }, {
    model: 'Model5',
    attributes: [...],
  }],
});
```

I can go with a lot of combinations here and all I have is to re-write same thing over and over.

versus:
```js
scopes: {
  modelThreeAndFive: {
    include: [{ model: 'Model3', attributes: [...] }, { model: 'Model5', attributes: [...] }]
  },
  model1WithAttributesOneAndTwo: {
    include: 'Model1',
    attributes: ['value1', 'value2'],
  },
  model1WithAttributesFiveAndSix: {
    include: 'Model1',
    attributes: ['id', 'value5', 'value6'],
  },
}
```

```js
.scope('modelThreeAndFive').create(...);
.scope('model1WithAttributesOneAndTwo').create(...);
.scope('model1WithAttributesFiveAndSix').create(...);
.scope('model1WithAttributesOneAndTwo', 'model1WithAttributesFiveAndSix').create(...);
```

This is REALLY rough example, but I hope you get the point. If you're not planning to change this nor add a support for it, I'll have to write my own scope implementation which will wrap sequelize instead, because in this case scopes lose the meaning for me.

Maybe this is a really rare case to do so, but it still can be happening right?

**Comment by shotexa** [comment]
Same issue here and I find this as a limitation too. I'm splitting up my code i started sequelize scopes for that, but stopped using it after a while, since it is confusing that it only works on a certain methods rather than all the methods, while there is no technical limitations for that. It's seems inconsistent for me.  just like as you said: syntax is okay, but the sql generation is wrong (when relying on scopes). We had a similar issue at work though, We wanted to save a model with it's associations and we tried to use scopes, but after a while we realized that it does not work for e.g. creation and we had to remove scope handling completely to not confuse other devs.

**Comment by sushantdhiman** [comment]
@overflowz Again I want to reiterate this kind of scheme is already possible using class/instance methods, imho which will be far clearer.

The way you want scope to be injected, you will have proper structure for includes so you can create with related models. But returned response will also be affected by that scope and you will missing any data that was not included by that scope.

My only concern is using scope for something is was not built for, scope presents set of options that will be applied on finder methods to serve as a access control cleanly, not for randomly injecting options to all methods

If you want this, here you can use this pattern

```js
Model.prototype.scopedBuild = function(values, options = {}) {
   this._injectScope(options);
   return this.build(values, options);
}

```

**Comment by overflowz** [comment]
@sushantdhiman I understood your point of view, but I'm not totally sure should I stick to that solution or not (since it looks 'hacky' because you're using internal method that should not be available outside).

Anyways, I'll play with it and see how it goes. Thanks for the discussion though!
