### ISSUE TITLE
Query belongsToMany association with 

### ISSUE THREAD

**Issue by acanimal** [sequelize/sequelize#10181]
Hi, I was looking for help on SO and here but without success.
I really want to know if Sequelize is able to do what I need or I must change my model.

I have the next scenario: 

```javascript
const User = sequelize.define('user', {})
const Project = sequelize.define('project', {})
const UserProjects = sequelize.define('userProjects', {
    status: DataTypes.STRING
})
const Tag = sequelize.define('tag', {})

User.belongsToMany(Project, { through: UserProjects })
Project.belongsToMany(User, { through: UserProjects })
UserProject.hasOne(Tag)
```

I would like to, given a User instance, query for all the projects but returning the `Tag` associated to each project.

I made an instance level method like next without success:

```javascript
User.prototype.getActiveProjects = async function () {
    const query = {
      through: {
        where: {
          status: { [Op.eq]: 'active' }
        }
      },
      include: [
        { model: models.Project }
      ]
    }

    return this.getProjects(query)
  }
```

Also adding `{ model: models.Tag}` to the `include` option do not works because `User` is not associated with `Tag`.

Thanks in advance

**Comment by sushantdhiman** [comment]
Have you tried `through.include: [models.Tag]` ?

**Comment by acanimal** [comment]
Do not works. Also it is not a valid options, see: http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll

**Comment by sushantdhiman** [comment]
In the include block, pass `through.include: [Tag]`

**Comment by acanimal** [comment]
Thanks @sushantdhiman but that do not works.

Finally I updated my implementation to use `hasMany` from `User` to `UserProject` and `Project` to `UserProject`.
