### ISSUE TITLE
Setting local configuration parameters for transactions

### ISSUE THREAD

**Issue by samrit** [sequelize/sequelize#10182]
Apologies if this is not the right place to request new features or if this already exists and I have missed it in the documentation.

I want to achieve the following when using transaction

```
START TRANSACTION;
SET LOCAL jwt.claims.roles = 'admin';
SELECT * FROM users WHERE username='foo';
COMMIT;
```

The `options` parameter on the current transactions does not seem to support doing this and I cannot see any other way of achieving this.

Is there a way to support setting the `jwt.claims` configuration parameter in postgres?

**Comment by sushantdhiman** [comment]
After starting transaction you can manually issue this query using `await query('sql', { transaction }`)

-----------------------------------------------


Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by samrit** [comment]
Duh! Thanks for the quick response.
