### ISSUE TITLE
object destructing does not work on  promise result from model.create()

### ISSUE THREAD

**Issue by mortenko** [sequelize/sequelize#10195]
## What are you doing?
I'm trying to destruct response from returned promise model.create() when creating new model instance. 

with spread operator:
```js
    const {
          dataValues: { customerID, ...restCustomer }
        } = await models.Customer.create(customer);
```
If I don't use spread operator and destruct all object properties like following example everything works fine
```
    const {
          dataValues: { customerID, firstname, lastname, email }
        } = await models.Customer.create(customer);
```

## What do you expect to happen?
I don't want destruct whole object's properties but use spread operator. 

## What is actually happening?
SQL INSERT statement is executed twice (I have sequelize sql logger turned on, so I see it in console) which cause different issues.  In my case I have some columns unique so sequelize throw uniqueConstrainValidationError when trying to insert the same data into table again. 

Does anyone has with this experience ? 

__Dialect: postgres 
__Dialect version: 9.6.2
__Sequelize version: 4.37.10

**Comment by sushantdhiman** [comment]
Seems to work properly (on `master`), did you forgot to pass extra props to create?

```js
'use strict';

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const User = sequelize.define('user', {
  userId: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  firstName: {
    type: Sequelize.STRING,
    allowNull: false
  },
  lastName: {
    type: Sequelize.STRING,
    allowNull: false
  }
}, {
  timestamps: false,
  underscored: true
});

(async () => {
  await sequelize.sync({
    force: true
  });
  const expectedUser1 = {
    firstName: 'test 1',
    lastName: 'test 11'
  };

  const {
    dataValues: {
      userId,
      ...restCustomer
    }
  } = await User.create(expectedUser1);

  console.log(userId, restCustomer);
})();
```

```sql
1 { firstName: 'test 1', lastName: 'test 11' }
```
