### ISSUE TITLE
include where{'$nested.table.field$': 'value'}.  doesn't work for me pls help

### ISSUE THREAD

**Issue by ytxDaXiong** [sequelize/sequelize#10194]
include: [
        {model: this.ctx.model.TradeEntryItemModel, as: 'items', required: false, include:[{model: this.ctx.model.ItemModel, as: 'itemDetail'}]},
        {model: this.ctx.model.ShopMartModel, as: 'shopMart', required: false},
        {model: this.ctx.model.UserModel, as: 'user', required: false},
        {model: this.ctx.model.OrderTradeModel, as: 'orderTrade', required: true} 
      ],

where :{  '$orderTrade.id$' : null } 
it doesn't work for me, i see the solution in  #3095 
if the way has changed,please tell me. thanks
my sequelize version is 4.38.0

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
