### ISSUE TITLE
Potentially unwanted behavior: string in where clause cast to 0 in MySQL

### ISSUE THREAD

**Issue by zypA13510** [sequelize/sequelize#10206]
## What are you doing?

```js
const Employee = sequelize.define('employee', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  firstName: {
    type: Sequelize.STRING(50),
    field: 'first_name',
  },
  lastName: {
    type: Sequelize.STRING(50),
    field: 'last_name',
  },
  number: {
    type: Sequelize.INTEGER.UNSIGNED,
    unique: true,
  },
}, {
  timestamps: false,
});

(async (userInput) => {
  let johnDoe = await Employee.create({
    firstName: 'John',
    lastName: 'Doe',
    number: 0,
  });
  console.log(await Employee.findOne({
    where: {number: userInput},
  }));
})('hello world');
```

## What do you expect to happen?
_console output `null` because there is no employee whose number is 'hello world'_

## What is actually happening?
_console output the `johnDoe` instance we've just created_

_Output, either JSON or SQL_
```
SELECT `id`, `first_name` AS `firstName`, `last_name` AS `lastName`, `number` FROM `employees` AS `employee` WHERE `employee`.`number` = 'hello world';
```

__Dialect:__ mysql <strike>/ postgres / sqlite / mssql / any </strike>

__Database version:__ MariaDB 5.5.60
__Sequelize version:__ 4.41.2

## Additional information
I understand this is caused by MySQL type casting, any string that isn't a decimal representation of number would be cast to 0 where a numeric value is expected (run `SELECT 'hello world'=0;`). However, I believe this behavior is probably undesirable and tends to cause confusion? My proposal is, maybe we can move the type casting to sequelize layer, and convert any value in where clause according to the column definition, and then pass the converted value to SQL.

**Comment by papb** [comment]
I believe this can already be done by setting `typeValidation: true` to [Sequelize instantiation options](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor).

Ping me if this is still an issue.

**Comment by zypA13510** [comment]
I haven't tested it yet, but the document says "on insert and update", which means where clause in select is not validated?

**Comment by papb** [comment]
@zypA13510 Ah, you're right, makes sense. But please test it anyway, just in case, and let me know. Thanks.

**Comment by zypA13510** [comment]
Yeah, I will once I get back to the environment with sequelize set up.

**Comment by zypA13510** [comment]
@papb Ok, actually that works on the where clause. A validation exception is thrown if `typeValidation` is set to `true`. I'm creating a PR to clarify this in the docs.
