### ISSUE TITLE
ignoreDuplicate on bulkCreate() returns "mssql does not support the 'ignoreDuplicates' option."

### ISSUE THREAD

**Issue by KarlGW** [sequelize/sequelize#10209]
## What are you doing?

I'm trying to ignore duplicates on a primary key when doing inserts with `bulkCreate()`.

```js
await this.model.bulkCreate(data, { ignoreDuplicates: true });
```

## What do you expect to happen?
I expect the ignoreDuplicate to make the insert ignore duplates. Per the documentation at:
[bulkCreate](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-bulkCreate)

(not supported by postgres < 9.5)

## What is actually happening?
It throws and returns:
`mssql does not support the 'ignoreDuplicates' option.` 

__Dialect:__ mssql
__Database version:__ SQL Server 2017 (Express)
__Sequelize version:__ 4.41.2
__Tested with latest release:__ 4.41.2

**Comment by sushantdhiman** [comment]
Docs updated https://github.com/sequelize/sequelize/commit/61a9b268b15b8ef4882bf45ddcc0cf5c10f7991e
