### ISSUE TITLE
401 Unauthorized: @types/geojson@latest

### ISSUE THREAD

**Issue by ashishdommety** [sequelize/sequelize#10207]
I'm trying to install sequelize, but keep getting this 401 error about `@types/geojson@^1.0.0`

![image](https://user-images.githubusercontent.com/21207555/49133385-c5a7f300-f294-11e8-938a-b0045daa75d6.png)

In my attempt to solve the issue I updated npm to version 6.4.1, and even used an `.npmrc` to at the root that contains
```
@types:registry="https://registry.npmjs.org"
```

But it still doesn't work. Any pointers?

**Comment by sushantdhiman** [comment]
This is not related to Sequelize, probably something wrong with registry, usually resolves itself. You may ask for help on `npm` repo

**Comment by crisward** [comment]
Having the same problem... let me know if you discover anything.

**Comment by ashishdommety** [comment]
@sushantdhiman This issue seemed to pop up for someone in the past as well..
#7587 - Opened by RakeshKulangara on May 1, 2017

Are there any plans for sequelize to wean off of using `@types/geojson@^1.0.0` as a dependency? I love using seqeulize, but it's a bummer that a dependency is preventing me from downloading it..

**Comment by ashishdommety** [comment]
> Having the same problem... let me know if you discover anything.

For sure! Please let me know if you come across something as well

**Comment by ashishdommety** [comment]
@crisward  This seems to a windows specific issue - I tried to download sequelize on a mac machine and it worked

**Comment by ashishdommety** [comment]
Seems to have resolved itself now - thanks!
