### ISSUE TITLE
Error with Sequelize.sync and ENUMs: enum label already exists

### ISSUE THREAD

**Issue by jessefulton** [sequelize/sequelize#1020]
I thought this was the same as #546, but I think it may be a new issue. When I start up my app I am receiving the following errors from Postgres using Sequelize 2.0.0 beta:

```
15:11:47 db.1   | ERROR:  enum label "pending" already exists
15:11:47 db.1   | STATEMENT:  ALTER TYPE "enum_users_status" ADD VALUE 'pending' BEFORE 'active'
15:11:47 db.1   | ERROR:  enum label "active" already exists
15:11:47 db.1   | STATEMENT:  ALTER TYPE "enum_users_status" ADD VALUE 'active' BEFORE 'inactive'
15:11:47 db.1   | ERROR:  enum label "inactive" already exists
15:11:47 db.1   | STATEMENT:  ALTER TYPE "enum_users_status" ADD VALUE 'inactive' AFTER 'active'
```

The model in question looks like

``` coffeescript
module.exports = User = db.define("user", {
    display_name: Sequelize.STRING
    avatar_url: Sequelize.STRING
    role: 
        type: Sequelize.ENUM
        values: ["basic", "admin"]
        allowNull: false
        defaultValue: "basic"
        validate:
            isIn: [['basic', 'admin']]
    status: 
        type: Sequelize.ENUM
        values: ["pending", "active", "inactive"]
        allowNull: false
        defaultValue: "pending"

})
```

I've tried running the sync with `sequelize.sync({force: true});` and `sequelize.sync();` - both cause the error above. If I go into psql and drop the database, then recreate it, everything works fine on the next start. But then after restart it happens again and renders my application unusable... Any thoughts?

**Comment by Aweary** [comment]
Hey @mickhansen @janmeier I'm seeing this issue with the current version of sequelize.

I have a schema which looks like:
```js
sequelize.define('test', {
   testValue: { type: ENUM('first', 'second')
})
```

Which is exported.

I then have a `mocha` block that looks like:
```js
describe('Test Model', () => {
  before(done => {
    Property = sequelize.import('../../lib/models/test.js');
    Property.sync().then(() => done()).catch(done);
  });

  before('should allow object initialization', done => {
    Property.create(_data).then(result => {
      property = result;
      done();
    });
  });
```

If I run this with `Property.sync({force: true})` it works. But if the table isn't being dropped then I get the error:

```js
  1) Test Model "before all" hook:
     SequelizeDatabaseError: enum label "second" already exists
      at [object Object].Query.formatError (node_modules/sequelize/lib/dialects/postgres/query.js:433:14)
      at [object Object].<anonymous> (node_modules/sequelize/lib/dialects/postgres/query.js:108:19)
      at [object Object].Query.handleError (node_modules/pg/lib/query.js:108:8)
      at [object Object].<anonymous> (node_modules/pg/lib/client.js:171:26)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

**Comment by faceleg** [comment]
This is happening for me as well. Oddly, the issue went away when I removed any spaces present in the offending model's enum values.

The following failed:

```JS
sequelize.define('test', {
   testValue: { type: ENUM('first', 'sec ond')
})
```

**Comment by janmeier** [comment]
@faceleg It identifies the enum correctly though, but not the value  `enum label "se cond" already exists`

Mind opening a new issue for this?

**Comment by faceleg** [comment]
Opened #4770

**Comment by JoshSGman** [comment]
+1 Ran into this as well, removing spaces in the enum values fixes the issue for me.

**Comment by faceleg** [comment]
@JoshSGman it does, see my unfinished PR for details on how to fix it for good.

**Comment by KlonD90** [comment]
Same for me.
It's from my migration.
```
{ [SequelizeDatabaseError: type "enum_Orders_type" already exists]
  name: 'SequelizeDatabaseError',
  message: 'type "enum_Orders_type" already exists',
  parent:
   { [error: type "enum_Orders_type" already exists]
     name: 'error',
     length: 89,
     severity: 'ERROR',
     code: '42710',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'typecmds.c',
     line: '1133',
     routine: 'DefineEnum',
     sql: 'CREATE TYPE "public"."enum_Orders_type" AS ENUM(\'yandex\', \'ios\');ALTER TABLE "public"."Orders" ADD COLUMN "type" "public"."enum_Orders_type" NOT NULL;' },
  original:
   { [error: type "enum_Orders_type" already exists]
     name: 'error',
     length: 89,
     severity: 'ERROR',
     code: '42710',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'typecmds.c',
     line: '1133',
     routine: 'DefineEnum',
     sql: 'CREATE TYPE "public"."enum_Orders_type" AS ENUM(\'yandex\', \'ios\');ALTER TABLE "public"."Orders" ADD COLUMN "type" "public"."enum_Orders_type" NOT NULL;' },
  sql: 'CREATE TYPE "public"."enum_Orders_type" AS ENUM(\'yandex\', \'ios\');ALTER TABLE "public"."Orders" ADD COLUMN "type" "public"."enum_Orders_type" NOT NULL;' }
```

Can i help someone with that problem?

**Comment by Edudjr** [comment]
Try using migration with the following code:

```javascript
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.query("ALTER TYPE enum_type_name ADD VALUE 'new_value'");
  },

  down: (queryInterface, Sequelize) => {
    var query = 'DELETE FROM pg_enum ' +
      'WHERE enumlabel = \'new_value\' ' +
      'AND enumtypid = ( SELECT oid FROM pg_type WHERE typname = \'enum_type_name\')';
    return queryInterface.sequelize.query(query);
  }
};
```
change **enum_type_name** and **new_value** to fit your needs.

**Comment by theSuiGenerisAakash** [comment]
@Edudjr But how do I use the type to create a column? Please help me out with my question [here](https://stackoverflow.com/questions/48730477/sequelize-migration-queryinterface-removecolum-fails-to-work).

**Comment by ProfJigsaw** [comment]
> Try using migration with the following code:
> 
> ```js
> 'use strict';
> 
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.sequelize.query("ALTER TYPE enum_type_name ADD VALUE 'new_value'");
>   },
> 
>   down: (queryInterface, Sequelize) => {
>     var query = 'DELETE FROM pg_enum ' +
>       'WHERE enumlabel = \'new_value\' ' +
>       'AND enumtypid = ( SELECT oid FROM pg_type WHERE typname = \'enum_type_name\')';
>     return queryInterface.sequelize.query(query);
>   }
> };
> ```
> 
> change **enum_type_name** and **new_value** to fit your needs.

Brilliant!

**Comment by luismavlo** [comment]
Revisen las relaciones que estén bien realizadas, Le paso lo mismo a un alumno y el problema estaba en que estaba relacionando ejemplo

ModeloA.hasMany(ModeloB)
ModeloB.hasMany(ModeloA)

y eso era el problema. y causaba el error del ENUM, en la relacion deberia colocar belongsTo.

**Comment by ikonduktor** [comment]
Have the same issue. Any suggestions?

**Comment by ephys** [comment]
Please open a new bug report with reproducible steps if you're still experiencing this issue, this thread is 10 years old and unlikely to still be relevant
