### ISSUE TITLE
Model.decrement taking too long to return result

### ISSUE THREAD

**Issue by imjeffparedes** [sequelize/sequelize#10205]
## What are you doing?

```js
sequelize.transaction(function (t) {
	//time from here

        logger.info(' : charge user ...')
	return user.decrement('balance', {
		by: order.userCharge,
		transaction: t
	}).then(function () {
	       //to here takes up to 20 seconds
                logger.info(' : saving transaction...')
		return order.save({
			transaction: t
		})
	})
}).then(function (result) {
	callback(null, result);
	return result;
}).catch(callback);
```

## What do you expect to happen?
Result of user.decrement() should be < 1s . 

## What is actually happening?
Result takes up to 20 seconds in batch processing
Sample sql log:
```
Executing (48f66632-3947-41e5-b34c-699f3a6c9f1c): UPDATE `users`
 SET `balance`=`balance` + -6,`lastmodifieddate`='2018-11-27 08:51:13' WHERE `id` = 1822 

```

I'm using batch api request processing using Siege.
Here is my sample transaction data:

```
Lifting the server siege...
Transactions:		        3438 hits
Availability:		      100.00 %
Elapsed time:		      299.25 secs
Data transferred:	        0.44 MB
Response time:		       25.05 secs
Transaction rate:	       11.49 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		      287.84
Successful transactions:        3438
Failed transactions:	           0
Longest transaction:	       47.51
Shortest transaction:	        5.16
```

You can see the longest transaction is **47.51**
Upon checking debug logs, this is caused by increment or decrement call to model User.
Here is the sample log:
```
2018-11-27T07:14:38.404Z info : charge user ...
2018-11-27T07:14:47.504Z info : saving transaction...
```
You can see that there is a 9 seconds delay between the logs. 

Checking mysql slow query logs does not reveal any long query at all except for my tests.

```
Reading mysql slow query log from /var/lib/mysql/cti-mysql-db-slow.log                      
Count: 2  Time=5.00s (10s)  Lock=0.00s (0s)  Rows=1.0 (2),                                    
  SELECT SLEEP(5)                                                                           
                                                                                            
Count: 1  Time=3.00s (3s)  Lock=0.00s (0s)  Rows=1.0 (1),                                                 
  SELECT SLEEP(3)                                                                           
                                                                                            
Count: 1  Time=2.00s (2s)  Lock=0.00s (0s)  Rows=1.0 (1),                                   
  SELECT SLEEP(2)                                                                           
                                                                                            
Count: 1  Time=1.00s (1s)  Lock=0.00s (0s)  Rows=1.0 (1),                          
  SELECT SLEEP(1)   
```

__Dialect:__ mysql 
__Database version:__ MySQL 5.6
__Sequelize version:__ 3.33.0
__Tested with latest release:__ Yes to v4.41.2

**Comment by sushantdhiman** [comment]
Try passing `benchmark: true` and `logging: console.log`, then you can see how much time is spent on query. Show those logs, I suspect actual query is taking that time

**Comment by imjeffparedes** [comment]
@sushantdhiman  I tried, but all I can see is this:

```
Executing (48f66632-3947-41e5-b34c-699f3a6c9f1c): UPDATE `users`
 SET `balance`=`balance` + -6,`lastmodifieddate`='2018-11-27 08:51:13' WHERE `id` = 1822 

```

**Comment by sushantdhiman** [comment]
@imjeffparedes How are you passing these options, pass them to `decrement` method

**Comment by imjeffparedes** [comment]
@sushantdhiman Here are the options:

```
return user.decrement('balance', {
	by: order.userCharge,
	benchmark: true,
	logging: function(msg){
		logger.log(msg)
	},
	transaction: t
}).then(function () {
})
```

Also `benchmark: true` is not present in version 3

**Comment by sushantdhiman** [comment]
If you run this transaction in MySQL server directly, what differences you observe?

**Comment by imjeffparedes** [comment]
@sushantdhiman Significantly faster than from the code. It will just take <1s .

**Comment by sushantdhiman** [comment]
Can you show me the full SQL code that you tried?

**Comment by imjeffparedes** [comment]
Sample run in MySQL server:
```
mysql> UPDATE `users`  SET `balance`=`balance` + -6,`lastmodifieddate`='2018-11-27 08:51:13' WHERE `id` = 1
822;                                                                                                       
Query OK, 1 row affected (0.00 sec)                                                                        
Rows matched: 1  Changed: 1  Warnings: 0                                                                   
                                                                                                           
mysql>                        
```

**Comment by sushantdhiman** [comment]
Yeah that is without transaction, Your sequelize code is using transaction. Try running same transaction based code in console

**Comment by imjeffparedes** [comment]
Ok so I tried while running the transactions:
```                                                                                                   
mysql> UPDATE 'users'  SET 'balance'='balance' + -6,'lastmodifieddate'='2018-11-27 08:51:13' WHERE 'id' =18
22;                                                                  
Query OK, 1 row affected (2.96 sec)                                                                        
Rows matched: 1  Changed: 1  Warnings: 0                                                                                                          
mysql> UPDATE 'users'  SET 'balance'='balance' + -6,'lastmodifieddate'='2018-11-27 08:51:13' WHERE 'id' =18
22;                           
Query OK, 1 row affected (2.03 sec)                                                                        
Rows matched: 1  Changed: 1  Warnings: 0                                                                                                         
mysql> UPDATE 'users'  SET 'balance'='balance' + -6,'lastmodifieddate'='2018-11-27 08:51:13' WHERE 'id' =18
22;                                                                  
Query OK, 1 row affected (2.00 sec)                                                                        
Rows matched: 1  Changed: 1  Warnings: 0                                                                                                          
mysql> UPDATE 'users'  SET 'balance'='balance' + -6,'lastmodifieddate'='2018-11-27 08:51:13' WHERE 'id' =18
22;                           
Query OK, 1 row affected (3.45 sec)                                                                        
Rows matched: 1  Changed: 1  Warnings: 0                                                                                                         
mysql> UPDATE 'users'  SET 'balance'='balance' + -6,'lastmodifieddate'='2018-11-27 08:51:13' WHERE 'id' =18
22;                                                                  
Query OK, 1 row affected (1.08 sec)                                                                        
Rows matched: 1  Changed: 1  Warnings: 0                                                                                                          
mysql> UPDATE 'users'  SET 'balance'='balance' + -6,'lastmodifieddate'='2018-11-27 08:51:13' WHERE 'id' =18
22;                           
Query OK, 1 row affected (2.24 sec)                                                                        
Rows matched: 1  Changed: 1  Warnings: 0                                                                                                          
mysql>                                                                                                     
```

Woah those are pretty high query time. 
But it does not conclude why it takes up to 20 seconds?
Is there something I am missing from the database?

**Comment by imjeffparedes** [comment]
Ok I'll try with transaction.

**Comment by imjeffparedes** [comment]
So I tried using transaction but nothing changed:

mysql> START TRANSACTION; UPDATE users  SET balance=balance + -6,lastmodifieddate='2018-11-2
7 08:51:13' WHERE id=1822;UPDATE reloads_UAT set usercharge=usercharge+1 where id=1;COMMIT; 
Query OK, 0 rows affected (0.00 sec)                                                        
                                                                                            
Query OK, 1 row affected (1.76 sec)                                                         
Rows matched: 1  Changed: 1  Warnings: 0                                                    
                                                                                            
Query OK, 1 row affected (0.00 sec)                                                         
Rows matched: 1  Changed: 1  Warnings: 0                                                    
                                                                                            
Query OK, 0 rows affected (0.00 sec)                                                        
                                                                                            
mysql> START TRANSACTION; UPDATE users  SET balance=balance + -6,lastmodifieddate='2018-11-2
7 08:51:13' WHERE id=1822;UPDATE reloads_UAT set usercharge=usercharge+1 where id=1;COMMIT; 
Query OK, 0 rows affected (0.00 sec)                                                        
                                                                                            
Query OK, 1 row affected (3.08 sec)                                                         
Rows matched: 1  Changed: 1  Warnings: 0                                                    
                                                                                            
Query OK, 1 row affected (0.00 sec)                                                         
Rows matched: 1  Changed: 1  Warnings: 0                                                    
                                                                                            
Query OK, 0 rows affected (0.00 sec)                                                        
                                                                                            
mysql> START TRANSACTION; UPDATE users  SET balance=balance + -6,lastmodifieddate='2018-11-2
7 08:51:13' WHERE id=1822;UPDATE reloads_UAT set usercharge=usercharge+1 where id=1;COMMIT; 
Query OK, 0 rows affected (0.00 sec)                                                        
                                                                                            
Query OK, 1 row affected (3.26 sec)                                                         
Rows matched: 1  Changed: 1  Warnings: 0                                                    
                                                                                            
Query OK, 1 row affected (0.00 sec)                                                         
Rows matched: 1  Changed: 1  Warnings: 0                                                    
                                                                                            
Query OK, 0 rows affected (0.00 sec)                                                        
                                                                                            
mysql>

**Comment by imjeffparedes** [comment]
I will try to upgrade to version 4. Hopefully that works.

**Comment by imjeffparedes** [comment]
I tried upgrading to version 4.41.2 but that part still has long delay.
