### ISSUE TITLE
Unable to check instanceof Fn

### ISSUE THREAD

**Issue by DaveStein** [sequelize/sequelize#10223]
## What are you doing?
I have a JSON column `metadata`. I want to safeguard my code such that a developer can't do this:

```
// Wants to add one column, inadvertently deletes everything else
instance.update({metadata: { newcolumn: true}});
```

I have a method that does this:
```
return Sequelize.fn('JSON_MERGE_PATCH', Sequelize.col('metadata'), JSON.stringify(params));
```

Unfortunately I can't update my models `update` method to look for something like this:

```
if (params.metadata && !params.metadata instanceof Fn) {
 throw new Error("oops");
}
```

## What do you expect to happen?
I expect to be able to import the class that is the type here. Unfortunately it's defined in Utils which is not inherently exposed on `Sequelize` or my instance of `Sequelize` in a usable way.

## What is actually happening?
There is no way to compare types. Doing `returnvalue instanceof Sequelize.fn` tells me it's in invalid right hand assignment.

__Dialect:__ mysql
__Dialect version:__ 5.7
__Database version:__ 5.7
__Sequelize version:__ 4.37.10
__Tested with latest release:__ No, ^^

Looking at codebase makes it seem this is also an issue.

**Comment by sushantdhiman** [comment]
Use `Sequelize.Utils.Fn` https://github.com/sequelize/sequelize/blob/2874c54915b2594225e939809ca9f8200b94f454/lib/sequelize.js#L1191
