### ISSUE TITLE
Simple Model.findOne() is running extremely slow

### ISSUE THREAD

**Issue by taufnrsyd** [sequelize/sequelize#10229]
## What are you doing?
I am just trying to query my data using the ORM.

```js
Foo.getTheData = async function () {
    const data = await Foo.findOne({
        where: {
            status: 'SOME_STATUS'
        }
    })

    if (!data) return false

    // do something
    return otherThing
}
```

## What do you expect to happen?
I expect the query to return result immediately.

## What is actually happening?
It returns the correct result, but it takes forever for the function to do so. What is even more baffling is that I can see on my console that the DB completed in just 1ms. FYI, the function is located inside my model definition.

Additionally, my model has two 1-to-many associations set up, both associated model/tables currently do not have any entry yet. But I find it hard to believe that the associations might've caused this. I then re-run the function but this time with a raw query.

```js
const data = await sequelize.query("SELECT * FROM Foo WHERE status = 'SOME_STATUS'")
```

This time the query returns the result immediately. This just doesn't make sense since I have another query which also uses `findOne` in another part of my code and it works just fine.

__Dialect:__ mysql2
__Dialect version:__ 1.6.1
__Database version:__ MySQL 5.7.24
__Sequelize version:__ 4.41.2
__Tested with latest release:__ No

**Comment by taufnrsyd** [comment]
So I logged the query result, and it actually includes the objects from associated values even though I don't specify any `include` field. I just want to get the data from the model only, why does Sequelize automatically inject the associated models? And how can I disable this behavior?

**Comment by sushantdhiman** [comment]
If you can reproduce this issue we can fix this, this seems like something dependent on production data? Perhaps missing indexes. Do you have any index on ``status`` column?

**Comment by knoxcard** [comment]
@taufnrsyd - close ticket?

Where you able to rectify the situation? Please share, either way.
