### ISSUE TITLE
Difference between timestamps value while creating and quering the model

### ISSUE THREAD

**Issue by guidsen** [sequelize/sequelize#10225]
I'm having issues with the timestamps on the Sequelize models. When creating a new record via the model, the `createdAt` timestamp contains milliseconds, but when I query the database using `findOne()`, it doesn't contain milliseconds. The `createdAt` column in the database is of type `timestamp`.

Value while creating model: `2018-12-04T07:18:14.075Z`
Value while retrieving model via query: `2018-12-04T07:18:14.000Z`

Anyone know what to do? Why is this even inconsistent?

I'm using Sequelize `4.41.2`.

**Comment by sushantdhiman** [comment]
Verify this against master, then follow the issue template properly

---------------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
