### ISSUE TITLE
Embedded fields

### ISSUE THREAD

**Issue by victorschinaider** [sequelize/sequelize#10221]
I don't know if it's a question or a request of feature.
Is there a way to create embedded fields in a model (http://typeorm.io/#/embedded-entities)?

I know i can use relations to simulate this, but it demands too much work, create many models.

Example:

Table
```
Person {
  id,
  field2,
  field3,
  field4
}
```

Model (I want to return something like this)
```
{
  id: number;
  someFieldName: {
    field2: string;
    field3: number;
  },
  otherVirtualName: {
    field4: string;
  }
}
``

**Comment by victorschinaider** [comment]
This link (https://stackoverflow.com/questions/41785936/sequelize-object-property-mapping-to-multiple-fields) gives a possible solution ( but it works like a hack to me). But, it's not a solution, because it not resolves fields inside nested fields. E.g:

```
{
  id: number;
  someFieldName: {
    field2: string;
    field3: number;
    otherNestedField: {
      fieldHere: string;
    }
  },
  otherVirtualName: {
    field4: string;
  }
}
```

**Comment by sushantdhiman** [comment]
You can use VIRTUAL fields to return object of desired shape. VIRTUAL can compute output based on other fields, but beyond that I would not like to support this feature

**Comment by victorschinaider** [comment]
@sushantdhiman, I would like to thank for the excellent tool that is Sequelize. I don't know if VIRTUAL is a solution here, i recalls in same problema i presented in last comment. If is it possible, could you explain why you would not like to support? It think it's good for, for example, write less code, and i think it's a important feature, many ORM frameworks support this feature in anyways. 

And i thank you for your response!
