### ISSUE TITLE
Belongs-To-Many options.through not working

### ISSUE THREAD

**Issue by robbyklein** [sequelize/sequelize#10220]
I'm on the latest version of Sequelize (4.41.2) and am trying to use the instance add method and options.through is not being added to the join table columns.

### Exercise Model
```
module.exports = (sequelize, DataTypes) => {
    const Exercise = sequelize.define(
        'Exercise',
        {
            title: DataTypes.STRING,
            liftType: DataTypes.STRING,
            difficulty: DataTypes.STRING,
            rating: DataTypes.FLOAT,
            imageStart: DataTypes.STRING,
            imageEnd: DataTypes.STRING,
            equipment: DataTypes.STRING,
            muscle: DataTypes.STRING,
        },
        {
            timestamps: false,
        }
    )

    return Exercise
}
```

### Workout Model
```
module.exports = (sequelize, DataTypes) => {
    const Workout = sequelize.define('Workout', {}, {})
    Workout.associate = function({ User, Exercise }) {
        Workout.belongsTo(User)
        Workout.belongsToMany(Exercise, {
            through: 'ExerciseWorkouts',
        })
    }
    return Workout
}
```

### Join Model
```
module.exports = (sequelize, DataTypes) => {
    const ExerciseWorkout = sequelize.define(
        'ExerciseWorkout',
        {
            variable: DataTypes.BOOLEAN,
            sets: DataTypes.INTEGER,
            reps: DataTypes.JSON,
            weight: DataTypes.JSON,
        },
        {}
    )

    return ExerciseWorkout
}
```

Then I'm trying to add exercises to a model instance:

```
exports.create = async (req, res) => {
    const UserId = req.user.id
    const { name } = req.body

    const workout = await Workout.create({ name, UserId })
    const exercise = await Exercise.findOne({ where: { id: 15 } })

    await workout.addExercise(exercise, { through: { sets: 4, variable: true } })

    res.send({ workout })
}
```

All the rows and associations get created properly but non of the extra fields in the join table get populated.

<img width="1057" alt="screenshot 2018-12-02 23 39 35" src="https://user-images.githubusercontent.com/6813372/49359642-9ece3000-f68b-11e8-8a53-bd70029cdd24.png">

## What do you expect to happen?
Sets to equal 4 and variable to equal true

## What is actually happening?
null and null

**Comment by Schavras** [comment]
Ι had the same problem today, and that's how i found your issue.

In my case, my error was that in the though option, (in your case "through: 'ExerciseWorkouts', " of Workout Model ) should not be a string, but reference to the actual Model (ExerciseWorkout)

**Comment by robbyklein** [comment]
Thank you! That did the trick. Wonder why the docs show a string...

**Comment by acaciomartins** [comment]
Tks very much.

**Comment by maxmx03** [comment]
For some reason this not work for me, seen like UserProject cant have more than one User or Project.
User.belongsToMany(Project, { through: UserProjects })
Project.belongsToMany(User, { through: UserProjects })

This bellow works for me
User.hasMany(UserProjects )
UserProjects .belongsTo(User)
Project.hasMany(UserProjects )
UserProjects .belongsTo(Project)
