### ISSUE TITLE
`ssl` of dialectOptions can not set true after mysql2 upgraded

### ISSUE THREAD

**Issue by kunyan** [sequelize/sequelize#10238]
I had run a `yarn install` last week and got error 

```
Cannot create property 'rejectUnauthorized' on boolean 'true'
```

I found it is a `mysql2` bug. and create PR for it.

However, according from https://github.com/sidorares/node-mysql2/pull/896#issuecomment-444851736, the `ssl` can not be set as `true`.

the latest `mysql2` has merged https://github.com/sidorares/node-mysql2/pull/895
It will throw a error if `ssl` been set to `true`.

Pls update the code and docs for mysql ssl connection
such like 

- https://github.com/sequelize/sequelize/blob/master/test/unit/configuration.test.js#L162
- https://github.com/sequelize/sequelize/blob/master/docs/migrations.md#connecting-over-ssl

**Comment by sushantdhiman** [comment]
I have improved docs section. Those tests can't fail as they never talk with connector library https://github.com/sequelize/sequelize/commit/850a47912c668c33992ef29d2373947042c0452f
