### ISSUE TITLE
How to establish Associations when using Migrations?

### ISSUE THREAD

**Issue by marbuser** [sequelize/sequelize#10235]
So I had a few questions regarding migrations and their usage. I understand this isn't a support forum but from my searching, all the relevant answers I can find are either inadequate or are years old.

My first question is what is the benefit of migrations? Previously I was using Sync and while I understand you don't want that in production since it wipes data, when using migrations isn't that essentially exactly the same as what migrations does? I don't see the benefit and when I've searched all I've found is people saying you "Should use them" but never any actual reasons as to why you should use them. Like I'm not really sure how to decide if I should be using migrations or sync since they feel like they basically do the same thing except migrations takes more work to setup??

My second and more important question is how can you define associations inside migration files? I've seen in a couple of posts from like 2015-16, that you can do it manually, AKA basically defining the foreign key and all that, but that doesn't really feel like the best way of doing it.

Is there some way where I can just do what I do in JS which is import the model, and just define it under some property inside the migration?

Any help is appreciated. Thanks

**Comment by itsaakashpatel** [comment]
Hi,

I'm looking for the same. Actually I have tried to use foreign key by declaring a reference inside the migrations but I'm not getting proper results. 

Here, I'm getting _**Can't create table `ds_hub_jms`.`role_user` (errno: 150 "Foreign key constraint is incorrectly formed")**_ error.

> ` **user.js migration**
> 'use strict';
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.createTable('users', {
>       id: {
>         allowNull: false,
>         autoIncrement: true,
>         primaryKey: true,
>         type: Sequelize.INTEGER
>       },
>       firstName: {
>         type: Sequelize.STRING,
>         field: 'first_name'
>       },
>       middleName: {
>         type: Sequelize.STRING,
>         field: 'middle_name'
>       },
>       lastName: {
>         type: Sequelize.STRING,
>         field: 'last_name'
>       },
>       ldap: {
>         type: Sequelize.STRING,
>         field: 'ldap'
>       },
>      /*Some other stuff */
>       createdAt: {
>         allowNull: false,
>         type: Sequelize.DATE,
>         field: 'created_at'
>       },
>       updatedAt: {
>         allowNull: false,
>         type: Sequelize.DATE,
>         field: 'updated_at'
>       }
>     });
>   },
>   down: (queryInterface, Sequelize) => {
>     return queryInterface.dropTable('users');
>   }
> };`

> `
> **role.js migration**
> 
> 'use strict';
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.createTable('roles', {
>       id: {
>         allowNull: false,
>         autoIncrement: true,
>         primaryKey: true,
>         type: Sequelize.INTEGER,
>       },
>       name: {
>         type: Sequelize.STRING,
>         field: 'name',
>       },
>       createdAt: {
>         allowNull: false,
>         field: 'created_at',
>         type: Sequelize.DATE
>       },
>       updatedAt: {
>         allowNull: false,
>         field: 'updated_at',
>         type: Sequelize.DATE
>       }
>     });
>   },
>   down: (queryInterface, Sequelize) => {
>     return queryInterface.dropTable('roles');
>   }
> };
> `

> `
> **role_user migration**
> 
> 'use strict';
> 
> module.exports = {
>   up: (queryInterface, Sequelize) => {
> 
>     return queryInterface.createTable('role_user', {
>       roleId: {
>         type: Sequelize.INTEGER(11),
>         field: 'role_id',
>         primaryKey: true,
>         references: {
>           model: 'Role',
>           key: 'id'
>         },
>         onUpdate: 'CASCADE',
>         onDelete: 'SET NULL',
>       },
>       userId: {
>         type: Sequelize.INTEGER(11),
>         field: 'user_id',
>         primaryKey: true,
>         references: {
>           model: 'User',
>           key: 'id'
>         },
>         onUpdate: 'CASCADE',
>         onDelete: 'SET NULL',
>       },
>       createdAt: {
>         allowNull: false,
>         field: 'created_at',
>         type: Sequelize.DATE
>       },
>       updatedAt: {
>         allowNull: false,
>         field: 'updated_at',
>         type: Sequelize.DATE
>       }
>     });
>   },
>   down: (queryInterface, Sequelize) => {
>     return queryInterface.dropTable('role_user');
>   }
> };
> `
> 

Please check and let me know if you can help in this case.

**Comment by rota-rossi** [comment]
The parameter name is somewhat misleading. Besides being named 'model', it actually expects the table name.
So, in the sample code shown above you should use: `model: 'roles'` instead. 

(For more info, take a look at the example shown [here](http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-createTable)).
