### ISSUE TITLE
Getting previous day instead of current for MSSQL DATEONLY

### ISSUE THREAD

**Issue by spearmootz** [sequelize/sequelize#10231]
## What are you doing?
storing and retrieving a dateOnly field from mssql using tedious

```js
 @IsDate
  @Column({
    type: DataType.DATEONLY,
    get(): moment.Moment | null {
      const date = this.getDataValue('date_of_birth');
      return moment(date);
    },
    set(date: moment.Moment | null) {
      return this.setDataValue(
        'date_of_birth',
        date == null ? null : date.format()
      );
    }
  })
  date_of_birth?: moment.Moment;
```

## What do you expect to happen?
get date in database

## What is actually happening?
getting the previous day

_Output, either JSON or SQL_
SQL returns '1992-10-10'
Actual result is '1992-10-09'

__Dialect:__  mssql 
__Dialect version:__ 4.1.0
__Database version:__ XXX
__Sequelize version:__ 5.0.0-beta.14
__Tested with latest release:__ No (If yes, specify that version)

I did my research and i found that in data-types.js in the dialect was doing the following

`return moment(value).format('YYYY-MM-DD');`

based on this code i can infer that its expecting value to be either an iso format or a date object. it is indeed getting a moment object but with a parsed time in GM (Sat May 05 2018 20:00:00 GMT-0400) so when formatting to 'YYYY-MM-DD' it gets the previous day.

i changed it to 
``return moment.utc(value).format('YYYY-MM-DD');`

and it started working. i am not making this a PR because i dont think this is the right approach based on what ive seen and that im not a sequelize expect.

**Comment by dengue8830** [comment]
same problem here, i fixed adding 1 day to the obtained date 😢
