### ISSUE TITLE
Upsert with returning:true returns false when it fails to create/update

### ISSUE THREAD

**Issue by getmetorajesh** [sequelize/sequelize#10232]
## What are you doing?
Trying upsert.

```js
try {
  const [model, created] = await CartModel.upsert({data: "update"}, { transaction, returning: true })
} catch (err) => {
   console.log(err) // When upsert fails becoz of an error expecting to get error here. But the above statement returns false
}
```

## What do you expect to happen?
On error expecting to `upsert` throw an error, as the signature says `Promise<Model, created>`. 
Expecting to follow signature: `Promise<Model, created>`

## What is actually happening?
But getting a single value `false`, not an array.
But behaves like: `Promise<Model, created> || Promise<Boolean>`

PS: If its new created or correct data it succeeds without issues(i.e returns <Model, created> array). Only if its incorrect data it fails. 

__Dialect: postgres 
__Dialect version: 7.4.1
__Database version: 10.4
__Sequelize version: 4.37.10

**Comment by sushantdhiman** [comment]
Please submit a SSCCE which can be used to reproduce this issue so it can be fixed.

-------------------------

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
