### ISSUE TITLE
$or doesn't work with $like operator in include.where

### ISSUE THREAD

**Issue by stringbeans** [sequelize/sequelize#10230]
## What are you doing?

```js
MyModel.findAll({
  where: {
    id: 1
  },
  include: [{
    model: Connector.AnotherModel,
    as: 'AnotherModel',
    where: {
      $or: [{
        firstname: {
          $like: `%test%`
        },
        lastname: {
          $like: `%test%`
        }
      }]
    }
  }]
})
```

## What do you expect to happen?
I would expect the JOIN clause to contain the OR operator on the two LIKE comparisons

## What is actually happening?
When looking at the resulting SQL generated, the JOIN condition only uses the AND operator with `firstname` and `lastname`, not the `OR` operator

The query ends up looking like this:

```
SELECT 
  ... <MyModel fields>
FROM `MyModel` AS `MyModel` 
INNER JOIN `AnotherModel` AS `AnotherModel` ON `MyModel`.`fk_id` = `AnotherModel`.`id` AND ((`AnotherModel`.`firstname` LIKE '%blah%' AND `AnotherModel`.`lastname` LIKE '%blah%')) ;
```

(redacted specifics from the query above)

__Dialect:__ mysql2
__Dialect version:__ 1.5.3
__Database version:__ 10.2.13-MariaDB
__Sequelize version:__ 4.41.2
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by stringbeans** [comment]
@sushantdhiman please reopen... i accidentally hit "save" before finishing the writeup of the issue :) ive updated with the full writeup

**Comment by sushantdhiman** [comment]
Show the SQL statement as well

**Comment by stringbeans** [comment]
@sushantdhiman thanks, updated the intitial description

**Comment by sushantdhiman** [comment]
```js
     $or: [{
        firstname: {
          $like: `%test%`
        }
      }, {
        lastname: {
          $like: `%test%`
        }
      }]
```

**Comment by stringbeans** [comment]
@sushantdhiman were you able to identify the issue here? Can I provide more information?

**Comment by sushantdhiman** [comment]
See my last comment, you are passing `$or` an array with single element, where you need to pass two elements if you want to have them separated by OR statement
