### ISSUE TITLE
SQL2000 issue

### ISSUE THREAD

**Issue by gaifo** [sequelize/sequelize#10246]
Hi 

I have use SQL2000 and I had config the tdsVerison to 7_1, when I run "sequelize db:migrate, sequelize throw an error.

```
Sequelize CLI [Node: 11.1.0, CLI: 5.3.0, ORM: 4.41.2]

Loaded configuration file "config/database.js".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual
/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
tedious deprecated The default value for `options.encrypt` will change from `false` to `true`. Please pass `false` explicitly if you want to retain current behaviour.
 node_modules/sequelize/lib/dialects/mssql/connection-manager.js:70:26

```
I have check the code and found that there is no sql2000 syntax because in sql2000, sp_helpindex belongs dbo, not sys. and I found same issue in others.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
