### ISSUE TITLE
errno: 150 "Foreign key constraint is incorrectly formed

### ISSUE THREAD

**Issue by itsaakashpatel** [sequelize/sequelize#10244]
Hi,

If migrations are the best ways to create tables for the database then I went with migration option. Now, when it comes to defining a foreign key then sequelize doesn't have a proper tutorial which shows how to define associations in migrations and how to define foreign keys in the migrations.

Here's my code, I can't figure out what's the issue here. Please help me.

Here, I'm getting _**Can't create table `ds_hub_jms`.`role_user` (errno: 150 "Foreign key constraint is incorrectly formed")**_ error.

> ` **user.js migration**
> 'use strict';
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.createTable('users', {
>       id: {
>         allowNull: false,
>         autoIncrement: true,
>         primaryKey: true,
>         type: Sequelize.INTEGER
>       },
>       firstName: {
>         type: Sequelize.STRING,
>         field: 'first_name'
>       },
>       middleName: {
>         type: Sequelize.STRING,
>         field: 'middle_name'
>       },
>       lastName: {
>         type: Sequelize.STRING,
>         field: 'last_name'
>       },
>       ldap: {
>         type: Sequelize.STRING,
>         field: 'ldap'
>       },
>      /*Some other stuff */
>       createdAt: {
>         allowNull: false,
>         type: Sequelize.DATE,
>         field: 'created_at'
>       },
>       updatedAt: {
>         allowNull: false,
>         type: Sequelize.DATE,
>         field: 'updated_at'
>       }
>     });
>   },
>   down: (queryInterface, Sequelize) => {
>     return queryInterface.dropTable('users');
>   }
> };`

> `
> **role.js migration**
> 
> 'use strict';
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.createTable('roles', {
>       id: {
>         allowNull: false,
>         autoIncrement: true,
>         primaryKey: true,
>         type: Sequelize.INTEGER,
>       },
>       name: {
>         type: Sequelize.STRING,
>         field: 'name',
>       },
>       createdAt: {
>         allowNull: false,
>         field: 'created_at',
>         type: Sequelize.DATE
>       },
>       updatedAt: {
>         allowNull: false,
>         field: 'updated_at',
>         type: Sequelize.DATE
>       }
>     });
>   },
>   down: (queryInterface, Sequelize) => {
>     return queryInterface.dropTable('roles');
>   }
> };
> `

> `
> **role_user migration**
> 
> 'use strict';
> 
> module.exports = {
>   up: (queryInterface, Sequelize) => {
> 
>     return queryInterface.createTable('role_user', {
>       roleId: {
>         type: Sequelize.INTEGER(11),
>         field: 'role_id',
>         primaryKey: true,
>         references: {
>           model: 'Role',
>           key: 'id'
>         },
>         onUpdate: 'CASCADE',
>         onDelete: 'SET NULL',
>       },
>       userId: {
>         type: Sequelize.INTEGER(11),
>         field: 'user_id',
>         primaryKey: true,
>         references: {
>           model: 'User',
>           key: 'id'
>         },
>         onUpdate: 'CASCADE',
>         onDelete: 'SET NULL',
>       },
>       createdAt: {
>         allowNull: false,
>         field: 'created_at',
>         type: Sequelize.DATE
>       },
>       updatedAt: {
>         allowNull: false,
>         field: 'updated_at',
>         type: Sequelize.DATE
>       }
>     });
>   },
>   down: (queryInterface, Sequelize) => {
>     return queryInterface.dropTable('role_user');
>   }
> };
> `
> 

Please check and let me know if you can help in this case.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
