### ISSUE TITLE
How to save complex changes to MySQL JSON data type

### ISSUE THREAD

**Issue by ghost** [sequelize/sequelize#10241]
When I make more complex changes to my users JSON col “preferences” like this:

```
user.preferences.notifications.disable_emails = {
	issues: true,
	reports: true,
	comments: true
}
user.save().then(user2 => { 
	console.log(user2) 
})
```

My changes are correctly in user2, but not in the database, it stays NULL or keeps the previous value.
Is there a callback I can call after complex changes so its detecting something is different?
I guess auto watch for changes in a multidimensional JSON is too complex - am I right?

**Comment by knoxcard** [comment]
user is your model.  `model.save()` is correct, but you can't have your data variable be the same as the Model itself.
```
var userData = {}
userData.name = 'Tom'
userData.logged_in = 'true'
userData.preferences.notifications.disable_emails = {
	issues: true,
	reports: true,
	comments: true
}

// update record
user.update(userData)

// save new record
user.build(userData).save().then(user2 => { 
	console.log(user2) 
})
```

**Comment by knoxcard** [comment]
When I first started using Sequelize, I made the same exact mistakes! lol, hours and hours of reading and trial/error to get things right.  To this day,  I am still enhancing my Sequelize/Session code...
