### ISSUE TITLE
Exception thrown on column default value null

### ISSUE THREAD

**Issue by stefansaravolac** [sequelize/sequelize#10256]
## What are you doing?
Inserting row in database (after updating Sequelize version).

## What do you expect to happen?
I expect  that row is inserted in database.

## What is actually happening?
Upon updating Sequelize to 4.41.2, from Sequelize 3, on NodeJS 10.13.0
Model .create where column has default value seems to throw this exception:

TypeError: Right-hand side of 'instanceof' is not an object
    at Object.toDefaultValue (/home/developer/Project/node_modules/sequelize/lib/utils.js:312:20)
    at model._initValues (/home/developer/Project/node_modules/sequelize/lib/model.js:3141:33)
    at new Model (/home/developer/Project/node_modules/sequelize/lib/model.js:3097:10)
    at new glo_error (/home/developer/Project/node_modules/sequelize/lib/sequelize.js:340:19)
    at Function.build (/home/developer/Project/node_modules/sequelize/lib/model.js:1966:12)
    at Function.create (/home/developer/Project/node_modules/sequelize/lib/model.js:2017:17) 

__Dialect:__ mysql
__Dialect version:__ Unknown 
__Database version:__ 5.6.22
__Sequelize version:__ 4.41.2
__Tested with latest release:__ Yes, 4.41.2

I have narrowed down error to this file and method

/node_modules/sequelize/lib/utils.js

When value=null, then check with instanceof causes exception.
```
function toDefaultValue(value, dialect) {
  if (typeof value === 'function') {
    const tmp = value();
    if (tmp instanceof DataTypes.ABSTRACT) {
      return tmp.toSql();
    } else {
      return tmp;
    }
  } else if (value instanceof DataTypes.UUIDV1) {
    return uuid.v1();
  } else if (value instanceof DataTypes.UUIDV4) {
    return uuid.v4();
  } else if (value instanceof DataTypes.NOW) {
    return now(dialect);
  } else if (_.isPlainObject(value) || _.isArray(value)) {
    return _.clone(value);
  } else {
    return value;
  }
}
```

When I added check for (value === null) first, insert row was successful.

```
function toDefaultValue(value, dialect) {
  //Added this check 
  if(value === null){
     return value;
  } else if (typeof value === 'function') {
    const tmp = value();
    if (tmp instanceof DataTypes.ABSTRACT) {
      return tmp.toSql();
    } else {
      return tmp;
    }
  } else if (value instanceof DataTypes.UUIDV1) {
    return uuid.v1();
  } else if (value instanceof DataTypes.UUIDV4) {
    return uuid.v4();
  } else if (value instanceof DataTypes.NOW) {
    return now(dialect);
  } else if (_.isPlainObject(value) || _.isArray(value)) {
    return _.clone(value);
  } else {
    return value;
  }
}
```

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
You need to include some code that is throwing this error
