### ISSUE TITLE
fieldValueHashes is not iterable

### ISSUE THREAD

**Issue by dejesus2010** [sequelize/sequelize#10252]
## What you are doing?

I am following the tutorial in [docs.sequelize](http://docs.sequelizejs.com/manual/tutorial/migrations.html#creating-first-seed) for migrations and I'm trying to seed the database using a seeder. I've mimicked the steps for my data model. Running the migration to create the db table works fine as it creates the table, but when I run the seeder it fails with a **ERROR: fieldValueHashes is not iterable**. To verify if it was a mistake on my end, I copied the steps in the tutorial for creating a User table with a demo-user seed. Running the same steps in the tutorial produces the same error... I suspect it may be due to a different config file or a different .sequelizerc, but I _think_ these are correct because populating the db with a table works...

I haven't traced through the source code for seeding a db yet, but hoping someone may have an idea why this issue is occurring! If nothing else, I can just trace through the code, but hoping to save some time/effort if someone already knows the fix. Thanks!

### .sequelizerc
```
const path = require('path');

module.exports = {
  'config': path.resolve('db/config', 'database.js'),
  'models-path': path.resolve('db', 'models'),
  'seeders-path': path.resolve('db', 'seeders'),
  'migrations-path': path.resolve('db', 'migrations')
}
```

### config/database.js
```js
module.exports = {
  "development": {
    "username": "ryandejesus",
    "password": null,
    "database": "ryandejesus",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "test": {
    "username": "root",
    "password": null,
    "database": "database_test",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "production": {
    "username": "root",
    "password": null,
    "database": "database_production",
    "host": "127.0.0.1",
    "dialect": "postgres"
  }
}
```

### migrations/create-user.js
```js
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Users', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      firstName: {
        type: Sequelize.STRING
      },
      lastName: {
        type: Sequelize.STRING
      },
      email: {
        type: Sequelize.STRING
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Users');
  }
};
```

### models/user.js
```js
'use strict';
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    firstName: DataTypes.STRING,
    lastName: DataTypes.STRING,
    email: DataTypes.STRING
  }, {});
  User.associate = function(models) {
    // associations can be defined here
  };
  return User;
};
```

### db/seeders/demo-user.js
```js
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Users', [{
        firstName: 'John',
        lastName: 'Doe',
        email: 'demo@demo.com'
      }], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Users', null, {});
  }
};

```

### command:
```
sequelize db:seed:all
```

## What do you expect to happen?

I expect the User table to be populated with the given seeding data (seeders/demo-user.js).

## What is actually happening?

Loaded configuration file "db/config/database.js".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
== 20181212015657-demo-product: migrating =======

ERROR: fieldValueHashes is not iterable

__Dialect:__ postgres 
__Database version:__ 9.5.14
__Sequelize CLI version:__ CLI: 5.4.0
__Sequelize version:__ 4.41.2

**Comment by sushantdhiman** [comment]
Pass `--debug` to enable stacktrace

**Comment by dejesus2010** [comment]
Thanks that helped.

The fix was save the seed fields in an array variable then pass the variable into the function:

```js
const fields = [{
        firstName: 'John',
        lastName: 'Doe',
        email: 'demo@demo.com'
      }];
return queryInterface.bulkInsert('Users', fields, {});
```

**Comment by jonesmac** [comment]
Ironically, I was doing the tutorials and I saw the same error when I forgot to return:
`queryInterface.bulkInsert('Users', fields, {});` was supposed to be
`return queryInterface.bulkInsert('Users', fields, {});`.

Not really clear from the error but hope it helps someone.
