### ISSUE TITLE
...What? Raw Query Insanely difficult to get

### ISSUE THREAD

**Issue by bradennapier** [sequelize/sequelize#10251]
Extremely confused as-to why this model was utilized...

```javascript
const [[value]] = await this.sequelize.query('SELECT BIN_TO_UUID(:binary, true)', {
    type: this.sequelize.QueryTypes.SELECT,
    replacements: { binary: this.get('id') },
  });
  const result = value['BIN_TO_UUID(:binary, true)'];
  return result;
```

Nope

Oh wait.. it's impossible to get the data without mapping this object it returns because it gives me a value that is formatted by sequelize directly -- otherwise I would not use replacements at all and just build the string myself. 

So i guess im super confused as-to how I am supposed to get this value in a way that makes any logical sense?

I am sure I am just missing something but there aren't any examples.

In my case the replacement is binary data as well so its even harder to capture

In my case its returning an object but I have no way of knowing the key:

```javascript
{ 'BIN_TO_UUID(X\'11e8fd02a176f998a5f70242ac110002\', true)': 'a176f998-fd02-11e8-a5f7-0242ac110002' }
```

Would it not make more sense to:

- Use a Map
- Use a Set
- Use an Array

And return the pre-replacement string rather than the one that I don't know about at all

```javascript
[
   [
        'SELECT BIN_TO_UUID(:binary, true)',
         'a176f998-fd02-11e8-a5f7-0242ac110002'  
    ]
]
```

Either way if the return type FORCES me to iterate then it should return an iterable value not an object that I then need to convert to use anyway.

Also since its returning an array in the first place it blows my mind even further that it's specifically this difficult to get the value.  I may seem like I am complaining over small things but its kind of crazy to have to do 

```javascript
const key = Object.keys(result)[0];
const value = result[key];
```

Perhaps an object makes more sense that defines:

```javascript
{
   raw: 'SELECT BIN_TO_UUID(:binary, true)',
   query: 'BIN_TO_UUID(X\'11e8fd02a176f998a5f70242ac110002\', true)',
   result: 'a176f998-fd02-11e8-a5f7-0242ac110002'  
}
```

**Comment by sushantdhiman** [comment]
Why don't you use a name `SELECT BIN_TO_UUID(:binary, true) AS something`

**Comment by bradennapier** [comment]
Yep - would be nice if that were documented somewhere that it is using the name.  Had assumed it was using the query string it generated as a map due to the value it was giving.

Thanks.
