### ISSUE TITLE
Adding a column to multiple tables

### ISSUE THREAD

**Issue by sgatana** [sequelize/sequelize#10253]
## What are you doing?
I am trying to add a single column `isDeleted`  to multiple tables through a migration script.

```js
module.exports = {
  up: (queryInterface, Sequelize) => {
    queryInterface.addColumn(
      ['category', 'products', 'orders', 'purchases'],
      'isDeleted',
      {
        type: Sequelize.BOOLEAN,
      },
    )
  },

  down: queryInterface =>
    queryInterface.removeColumn(
      ['category', 'products', 'orders', 'purchases'],
      'isDeleted',
    ),
}

```

## What do you expect to happen?
I expect this migration script to execute

## What is actually happening?
I am getting an error
== 20181212035825-add-column-for-deleted-items: migrating =======
ERROR: s.replace is not a function

Dialect: postgres
Database version: 9.5.14
Sequelize CLI version: CLI: 5.4.0
Sequelize version: 4.41.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
I don't think this is supported, you will have to call `addColumn` multiple times iirc.

**Comment by sgatana** [comment]
Thanks for pointing out this. I have achieved this by calling `addColumn` multiple times and specifying the model name as shown below
```
module.exports = {
  up: async (queryInterface, Sequelize) => {
    Promise.all(
      await [
        queryInterface.addColumn('sales', 'isDeleted', { type: Sequelize.STRING }),
        queryInterface.addColumn('products', 'isDeleted', {
          type: Sequelize.STRING,
        }),
        queryInterface.addColumn('purchases', 'isDeleted', {
          type: Sequelize.STRING,
        }),
      ],
    )
  },

  down: async queryInterface => {
    Promise.all(
      await [
        queryInterface.removeColumn('sales', 'isDeleted'),
        queryInterface.removeColumn('products', 'isDeleted'),
        queryInterface.removeColumn('purchases', 'isDeleted'),
      ],
    )
  },
}
```
