### ISSUE TITLE
sequelize is escaping double quotes

### ISSUE THREAD

**Issue by jcastell7** [sequelize/sequelize#10258]
Im trying to use sequelize Op.like to search for a string in a small table using this code:

` cronJobs = await cron_jobs.cron_jobs.findAll({where:{params:{[Op.like]: '%abc123%'}}});`

The cron_jobs table contains an "_id", "description", "params" and "dueDate".

what I want to do is to search in the params column and compare which registers contains the desired substring.
 
but when I execute the code this is the query it makes to the db:

`SELECT _id, description, params, dueDate FROM cron_jobs AS cron_jobs WHERE cron_jobs.params LIKE '\"%abc123%\"';`

Any idea on why it does that, or how could I do what i need?
 
Im using sequelize version 4.37.7 and mysql2 version 1.5.3, my db Mysql version is 5.6.39

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
