### ISSUE TITLE
Installation sequize failed missing .sequelize.DELETE folder

### ISSUE THREAD

**Issue by Jinryon** [sequelize/sequelize#10264]
## What are you doing?

I am trying to install for first time Sequelize on a CentOS7 server.
node -v : 10.14.2
npm -v: 6.4.1
express accounts-nodejs --view=ejs
sudo npm install express-generator -g
express accounts-back
cd accounts-back
npm install
sudo npm install -g sequelize-cli
npm install --save sequelize

## What do you expect to happen?
To install it ?!....

## What is actually happening?
npm ERR! path /mnt/hgfs/vms_shared/dev/accounts-back/node_modules/.sequelize.DELETE/node_modules/debug
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/mnt/hgfs/vms_shared/dev/accounts-back/node_modules/.sequelize.DELETE/node_modules/debug' -> '/mnt/hgfs/vms_shared/dev/accounts-back/node_modules/sequelize/node_modules/debug'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by Jinryon** [comment]
[2018-12-13T13_57_54_450Z-debug.log](https://github.com/sequelize/sequelize/files/2676433/2018-12-13T13_57_54_450Z-debug.log)

**Comment by sushantdhiman** [comment]
Looks like you are using `npm link`? In any case not related to Sequelize itself
