### ISSUE TITLE
How to load all models at once?

### ISSUE THREAD

**Issue by MunMunMiao** [sequelize/sequelize#10263]
## What are you doing?
How to load all models at once?

just like this import a directory
```js
const sequelize = require('sequelize')
sequelize.import('./models/')
```
or
```js
sequelize.import('./models/*')
```

## What do you expect to happen?
I need a function to add a directory

## What is actually happening?

__Dialect:__ mysql
__Dialect version:__ 8.0
__Database version:__ 8.0
__Sequelize version:__ 4.41.2
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/express-example

**Comment by MunMunMiao** [comment]
> https://github.com/sequelize/express-example

Can it be implemented on koa?

**Comment by mariusa** [comment]
Could this be supported natively, please?
I'm not sure this code works anymore in v6: https://github.com/sequelize/express-example/blob/master/express-main-example/sequelize/index.js
