### ISSUE TITLE
Support for zero values for deletedAt

### ISSUE THREAD

**Issue by ecdeveloper** [sequelize/sequelize#10273]
## What are you doing?

I'm trying to implement paranoid models, where `deletedAt` has a non-NULL default value (for the sake of having soft deletes and unique keys). I'm trying to use zero-date (0000-00-00) as a default value.

```js
module.exports = (sequelize, type) => {
    return sequelize.define('someModel', {
        id: {
          type: type.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        deletedAt: {
                type: DataTypes.DATE,
                defaultValue: 0
        }
    })
}
```

## What do you expect to happen?
When querying, I'm expecting the query to look like `SELECT * FROM someModel WHERE deletedAt = 0`, which would match the dummy `0000-00-00 00:00:00` date.

## What is actually happening?
The actual query looks like `SELECT * FROM someModel WHERE deletedAt > "2018-17-12 12:00:00"` (where deletedAt is greater than the current time). 

Dialect: mysql
Database version: 5.6.38
Sequelize version: 4.37.6
Tested with latest release: No

**Comment by sushantdhiman** [comment]
`defaultValue` works by setting default value for a column during insert if nothing else is passed. It does not specify what value to compare against.

As for paranoid mode it compares with current time by design, this although has been changed in v5 where it just check for `IS NULL`

Sorry I don't think paranoid can be customized for your needs. If you can explain your use case I may be able to suggest another approach

**Comment by ecdeveloper** [comment]
Of course. The use case is the following: let's say there's a User table, which has `id` and `email` fields. Email should be unique. A deleted user can be re-added. 

Now say we (soft) delete a user and then re-add with same email. In order to make it work - the unique key should be on `email + deletedAt`. To make sure that no users with same email are added (none are deleted) - the default value for deletedAt should be not null. MySQL has the so called dummy 0-datetime value, which is `0000-00-00 00:00:00`. If I specify this value as `defaultValue` in the model, then Sequelize will try to transform it into a JS date, which will result into a query which looks like `SELECT * FROM user where deletedAt = "Invalid date"`.

Hopefully it makes sense.

**Comment by sushantdhiman** [comment]
> Now say we (soft) delete a user and then re-add with same email. In order to make it work - the unique key should be on email + deletedAt. 

If you have soft deleted a user, why dont you just restore that record if they try to register that same `email`. I am not sure of your domain logic, may be enforced by your employer :) but restoring old record is a better approach.

Now coming to the technical point, have to tried setting a literal value as `defaultValue`, should look something like this `Sequelize.literal('0000-00-00 00:00:00')`, that should work

**Comment by ecdeveloper** [comment]
The user example was extremely simplified :) In fact, if an entity is deleted - it should stay deleted forever. I also try to avoid restoring deleted rows to ensure everything stays logically right, in other words - if something is deleted, it should be considered deleted even if it was soft deleted. 

Thanks for the advice! I'll try Sequelize.literal and will see if that resolves the issue.
