### ISSUE TITLE
Hook for destory and update NOT WORKING

### ISSUE THREAD

**Issue by tmirun** [sequelize/sequelize#10270]
## What are you doing?

```js
this.sequelize = new Sequelize(dbConfig.database, dbConfig.user, dbConfig.password, {
....
      define: {
        hooks: {
          beforeCreate() { console.log('before create'); },
          beforeDestroy() {console.log('before destroy'); },
          beforeUpdate() {console.log('before update'); },
          beforeFind() {console.log('before find'); },
          afterCreate() { console.log('after create'); },
          afterDelete() {console.log('after delete'); },
          afterDestroy() {console.log('after destroy'); },
          afterUpdate() {console.log('after update'); },
          afterFind() {console.log('after find'); }
        }
      }
    });
```

my update and delete methods:
```js
....
update(uuid, value) {
    return this.model.update(value, {
      where: { uuid },
      returning: true
    });
  }

  delete(uuid) {
    return this.model.destroy({
      where: { uuid: uuid }
    })
  }
....

```
## What do you expect to happen?
invoke beforeDestroy, beforeUpdate, afterDestroy, afterUpdate when destroy or update items

## What is actually happening?
beforeDestroy, beforeUpdate, afterDestroy, afterUpdate is not invoked 

__Dialect: postgres
__Dialect version:__ XXX
__Database version: postgresql 10
__Sequelize version: 4.42.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`Model.update` and `Model.destroy` can update/delete multiple records so we invoke `beforeBulkUpdate/beforeBulkDestroy` for these methods

http://docs.sequelizejs.com/manual/tutorial/hooks.html#model-hooks
