### ISSUE TITLE
Support for MySQL JSON_MERGE_PATCH?

### ISSUE THREAD

**Issue by DaveStein** [sequelize/sequelize#10274]
## What are you doing?
I want to perform a JSON_MERGE_PATCH in a supported way. This would be so performing a patch would automatically update the internal state of the JSON field. 

```js
const myObject = MyModel.findOne(whereObject);

let json = myObject.get('json_field');
console.log(json); // { "a": 1, "b": 2}

const params = { "b": 3 };
myObject.update({
  json_field: Sequelize.fn('JSON_MERGE_PATCH', Sequelize.col('json_field'), JSON.stringify(params))
});

json = myObject.get('json_field');
console.log(json); // the stringified Sequelize fn method
```

## What do you expect to happen?
It should return `{ "a": 1, "b": 3}`

## What is actually happening?
It returned the literal value of what I set via sequelize fn. It would be great if there was some operator-like syntax to do:

```js
myObject.update({
  [Op.mergePatch]: {
    {
      "json_field": params 
    }
  }
});
```

__Dialect:__ mysql
__Dialect version:__ 5.7.22
__Database version:__ 5.7.22
__Sequelize version:__ 4.37.10
__Tested with latest release:__ 4.37.10

**Comment by sushantdhiman** [comment]
For now you can call `reload` to get correct json data, there is an [open issue](https://github.com/sequelize/sequelize/issues/9151) regarding return value of `.fn / .literal` types. But as MySQL does not support `RETURNING` I don't think if this can be implemented for MySQL

**Comment by sushantdhiman** [comment]
No I would like to avoid that as JS merge may be different from MYSQL merge, Ideally we can just use return value from MySQL.

Once https://github.com/sequelize/sequelize/issues/9151 is fixed all supported dialects will have this features, others can use `reload`

**Comment by DaveStein** [comment]
Yeah I was just hoping to avoid another select, but `reload` will work and probably be advantageous (ie getting back new modified_on values in datetime columns and such). Thanks for replies.
