### ISSUE TITLE
DataTypes.DATE got "Invalid Date" for mysql DATETIME column

### ISSUE THREAD

**Issue by lukanovak124** [sequelize/sequelize#10279]
## What are you doing?

documents.js

```js
const moment = require('moment');

module.exports = function(sequelize, DataTypes) {
    return sequelize
        .define('documents', {
            document_id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                autoIncrement: true
            },
            file_name: DataTypes.STRING(256),
            identifier: DataTypes.STRING(64),
            page_num: DataTypes.INTEGER,
            status: DataTypes.INTEGER,
            size: DataTypes.INTEGER,
            created_at: DataTypes.DATE,
            parsed_at: DataTypes.DATE,
        },
        {
            freezeTableName: true,

            hooks: {
                beforeCreate(instance) {
                    instance.created_at = moment().format('YYYY-MM-DD HH:mm:ss');
                },
            },

            getterMethods: {

            },

            classMethods: {

            },
        });
```

DocumentsController.js

```js
var moment = require('moment');

module.exports = {
  get_documents(req, res) {
    return db.documents
      .findAll()
      .then(documents => {
        console.log(documents[0].created_at);
        console.log(typeof documents[0].created_at);
        return res.send(documents);
      })
  }
};
```

## What do you expect to happen?
I want to get created_at from mysql datetime column.

## What is actually happening?
But output is 

_Invalid Date_

__Dialect:__ mysql
__Dialect version:__ 1.6.4
__Database version:__ 5.7.24-0ubuntu0.16.04.1(Ubuntu)
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No

**Comment by knoxcard** [comment]
Is `documents[0],created_at = null`?

**Comment by lukanovak124** [comment]
Nope, documents[0].created_at = 'Invalid Date'

**Comment by sbonami** [comment]
My understanding is that Sequelize expects us to define that field as follows:

```js
module.exports = function(sequelize, DataTypes) {
    return sequelize
        .define('documents', {
            ...
            created_at: {
                type: DataTypes.DATE,
                defaultValue: DataTypes.NOW,
            },
            ...
        }, {
            ...
        });
```

However, the fallback to source this from the DBMS is currently not implemented:
https://github.com/sequelize/sequelize/blob/c6d733383dd9b877988784f28f23d47e256125f8/lib/utils.js#L280-L291

I was able to get this to generate a default from the DBMS using the code following, however I'm not 100% sure how Sequelize will react in all cases (validations, hooks, etc):
```js
module.exports = function(sequelize, DataTypes) {
    return sequelize
        .define('documents', {
            ...
            created_at: {
                type: DataTypes.DATE,
                defaultValue: sequelize.literal('CURRENT_TIMESTAMP'),
            },
            ...
        }, {
            ...
        });
```

**Comment by mkaufmaner** [comment]
Why don't you use the `timestamps` configuration option?

See
- http://docs.sequelizejs.com/manual/tutorial/models-definition.html#timestamps
- http://docs.sequelizejs.com/manual/tutorial/models-definition.html#configuration

**Comment by aichelnokov** [comment]
I have the same problem, `"sequelize": "^6.33.0"`

After create i see in console output correct dates:
```js
{
  // ...
  updatedAt: 2023-10-08T06:08:24.572Z,
  createdAt: 2023-10-08T06:08:24.572Z
}
```

But if i get user again (ex. by findOne method) then i see in output wrong data:
```js
{
  // ...
  createdAt: Invalid Date,
  updatedAt: Invalid Date
}
```

My configuration of modex includes:
```js
// attributes of model
declare createdAt: CreationOptional<Date>;
declare updatedAt: CreationOptional<Date>;
  
// init options
timestamps: true
```

**Comment by erik-sc** [comment]
@aichelnokov, did you find some fix for your error? I am having similar trouble when trying to query sqlite entities with DateTime fields in my database...

**Comment by zeid0ne** [comment]
Same problem on sequelize 6.37.3 with sqlite and DateTime fields
I tried to define a getter, but the getter is called after the conversion of my date to the 'Invalid date' string

**Comment by aichelnokov** [comment]
@erik-sc Hi.

No, i'm not fix it, but avoid the problem:
```js
dialectOptions: {
  dateStrings: true,
  typeCast: function (field: any, next: () => void) {
    if (field.type === "DATETIME") {
      return field.string();
    }
    return next();
  },
}
```

... and anyway, when i read value i must use dayjs: `dayjs(someDateTimeFieldAsString)`, and then convert to any format what i need.
