### ISSUE TITLE
does support postgresql ltree ?

### ISSUE THREAD

**Issue by qianfangyuan** [sequelize/sequelize#10278]
postgresql have value type ltree ?
https://www.postgresql.org/docs/current/ltree.html

does support postgresql ltree ?

**Comment by nithishjv** [comment]
Has there been any momentum on this? Do we have a workaround to use ltree with Sequelize?

**Comment by papb** [comment]
@nithishjv Not that I know of. Also, it would be great if you (or someone else) could open a new issue about this, filling our feature request template, since this issue is too far from our current feature request standards. If you do, I will close this one as a duplicate of the new one. Thanks!

**Comment by papb** [comment]
Duplicate of #11629
