### ISSUE TITLE
duplicate values when overriding column name using the field attribute

### ISSUE THREAD

**Issue by iaptsiauri** [sequelize/sequelize#10271]
## What are you doing?

This is the duplicate of the issue #10269, as it was closed without proper explanation. I did the digging and in the latest release v4.42.0 the issue still persists, even though it is fixed on the master branch.
At this line timestamp attribute is checked from options, wheres the timestamp is defined in attributes param.
https://github.com/sequelize/sequelize/blob/d2428dd580c1adb0a4c763a30499da2d87b19b3d/lib/model.js#L820

On the master branch, this is changed, I didn't go into details, but when I have installed the master version I got the correct response.
https://github.com/sequelize/sequelize/blob/66a453367c79808121a8e659b7a63ed2ae59551d/lib/model.js#L1002

Can there be any timeline when these changes be included in release?

**Comment by sushantdhiman** [comment]
>This is the duplicate of the issue #10269, as it was closed without proper explanation.

IMHO there is no better explanation than a sscce :) 

We only track fixes for master branch due to limited resources we have, you can backport a fix and I'll merge it. Thanks
