### ISSUE TITLE
Debugging an intermittent ECONNRESET between API and MYSQL database

### ISSUE THREAD

**Issue by priyath** [sequelize/sequelize#10289]
Apologies if this is not the place to raise this issue. 

I have an API written in NodeJS that communicates with a  MYSQL database. The API is running inside a Docker container. The database connection is handled via the Sequelize library.

Recently, I have started seeing the following error intermittently on my API server logs:
```
{ Error: read ECONNRESET
    at TCP.onread [as _originalOnread] (net.js:622:25)
```

Any subsequent query request from the API results in the following error:
```
SequelizeDatabaseError: Cannot enqueue Query after fatal error.
```

Recovery is only possible via a restart of the API. But the same issue sporadically re-appears, sometimes within an hour of a restart, sometimes almost immediately.

I use the following connection pool configuration for my Sequelize instance:
```
  pool: {
    max: 5,
    min: 1,
    evict: 300000,
    idle: 10000
  }
```

I gather that the ECONNRESET error is thrown when the other side of the TCP conversation abruptly closes its end of the connection.

**I have the following questions:**

1. Why does the sequelize connection continuously fail after an ECONNRESET? Is it correct to assume this is because the API server is attempting to re-use the failed TCP connection continuously for subsequent requests? Does this mean the library is unaware of the terminated connection?

2. What could be the reasons for the connection to be terminated with an ECONNRESET error? I understand there could be a variety of reasons. Some general pointers here would be helpful.

3. Is this something I should handle at a code level by adding a periodic heartbeat or something similar to ensure that my connection to the database is alive?

And any other pointers on how I can proceed to debug this issue would be hugely appreciated!

Node version: 8.12.0 (recently upgraded from 6.9.4)
Sequelize version: 3.30.2

**Comment by sushantdhiman** [comment]
Please follow the issue template next time

First `evict` is not supported by v3

> Why does the sequelize connection continuously fail after an ECONNRESET? Is it correct to assume this is because the API server is attempting to re-use the failed TCP connection continuously for subsequent requests? Does this mean the library is unaware of the terminated connection?

Usually dead connections are removed automatically, are you calling `getConnection` in your codebase?

> What could be the reasons for the connection to be terminated with an ECONNRESET error? I understand there could be a variety of reasons. Some general pointers here would be helpful.

Network errors, killed by server etc. Can't be predicted in most cases

> Is this something I should handle at a code level by adding a periodic heartbeat or something similar to ensure that my connection to the database is alive?

Pool should take care of that, may be use `config.retry` for `ECONNRESET`
