### ISSUE TITLE
Unhandled rejection Error: Invalid value user

### ISSUE THREAD

**Issue by shiqikai** [sequelize/sequelize#10282]
## What are you doing?

```
There is an associations
    User.belongsToMany(Community, { as: 'Communitys', through: communityUser })
    Community.belongsToMany(User, { through: communityUser })
below is my code:
 const community = await CommunityModel.getCommunityById(communityId);
 const user = await UserModel.findUserById(userId);
 community.addUser(user)

IN CommunityModel:
static async getCommunityById(id) {
        return await Community.findById(id);
    }
IN  UserModel:
static async findUserById(id) {
        return await User.findById(id);
    }
```

## What do you expect to happen?
No error

## What is actually happening?
Unhandled rejection Error: Invalid value user {
  dataValues:
   { id: 1,
     username: 'sqk',
     password: '$2a$10$yQWSBtHOiR1OcyHKSyyLEOsdajzH4hsSrx69ES/GAxOG8h5LliHZ6',
     session_key: null,
     phone: null,
     email: null,
     money: null,
     city: null,
     avatarUrl: null,
     sex: null,
     birthday: null,
     lastLoginTime: null,
     registerTime: 2018-12-19T04:20:11.000Z,
     wxOpenid: 'test',
     createdAt: 2018-12-19T04:20:11.000Z,
     updatedAt: 2018-12-19T04:20:11.000Z },
  _previousDataValues:
   { id: 1,
     username: 'sqk',
     password: '$2a$10$yQWSBtHOiR1OcyHKSyyLEOsdajzH4hsSrx69ES/GAxOG8h5LliHZ6',
     session_key: null,
     phone: null,
     email: null,
     money: null,
     city: null,
     avatarUrl: null,
     sex: null,
     birthday: null,
     lastLoginTime: null,
     registerTime: 2018-12-19T04:20:11.000Z,
     wxOpenid: 'test',
     createdAt: 2018-12-19T04:20:11.000Z,
     updatedAt: 2018-12-19T04:20:11.000Z },
  _changed: {},
  _modelOptions:
   { timestamps: true,
     validate: {},
     freezeTableName: true,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: { id: 1 },
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [],
     name: { plural: 'users', singular: 'user' },
     omitNull: false,
     sequelize:
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [Object],
        queryInterface: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: [Object],
        test: [Object] },
     hooks: {},
     uniqueKeys: { user_wxOpenid_unique: [Object] } },
  _options:
   { isNewRecord: false,
     _schema: null,
     _schemaDelimiter: '',
     raw: true,
     attributes:
      [ 'id',
        'username',
        'password',
        'session_key',
        'phone',
        'email',
        'money',
        'city',
        'avatarUrl',
        'sex',
        'birthday',
        'lastLoginTime',
        'registerTime',
        'wxOpenid',
        'createdAt',
        'updatedAt' ] },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false }
    at Object.escape (D:\project\koa2-community\node_modules\sequelize\lib\sql-string.js:66:11)
    at Object.escape (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:934:22)
    at _joinKeyValue.value.map.item (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2369:69)
    at Array.map (<anonymous>)

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version:__ 5.7
__Sequelize version:__ 4.37.10
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by knoxcard** [comment]
Can you post your full user model with column attributes definitions?

**Comment by sushantdhiman** [comment]
Can you post a SSCCE? Looks like you are passing instance as id

**Comment by shiqikai** [comment]
> Looks like you are passing instance as id
Sorry  but I  don't  understand what you mean actually. Sorry! Can you  describe more  clearly? Thanks

**Comment by sushantdhiman** [comment]
You are passing an Instance instead of id to `findById` method, not sure how to convery this more clearly :)

**Comment by shiqikai** [comment]
> You are passing an Instance instead of id to `findById` method, not sure how to convery this more clearly :)
Not actually.  I can get the user via findById .  the log is shown before.  The error occurs when `community.addUser`.
And now I try  `findById(1)`  . The Error still occurs

**Comment by sushantdhiman** [comment]
Well your logs are bit hard to read, there is no formatting at all :) Can't you see by stack trace which method is throwing error? Then we can hopefully recommend something. Please try to submit SSCCE next time as it take too much time replying and waiting just to reproduce the issue.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by shiqikai** [comment]
> Well your logs are bit hard to read, there is no formatting at all :) Can't you see by stack trace which method is throwing error? Then we can hopefully recommend something. Please try to submit SSCCE next time as it take too much time replying and waiting just to reproduce the issue.
> 
> ( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )
> 
> A few good example of SSCCE
> 
> 1. [#8014 (comment)](https://github.com/sequelize/sequelize/issues/8014#issue-245907597)
> 2. [#7318 (comment)](https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530)
> 3. [#8749 (comment)](https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396)

I rewrite the comment above。 thanks a lot!

**Comment by shiqikai** [comment]
> Can you post your full user model with column attributes definitions?

I rewrite the comment above。sorry for wasting your time the see it. If you are not busy , can you help me to solve this problem?

**Comment by shiqikai** [comment]
> Yep stacktrace point to `findAll` which is called by `findById`, looks like you are accidentally passing instance (an object) instead of `id`. Try commenting or passing ids in `findById` one by one to discover the bug or add logs before passing `id` to `findById`

**Comment by shiqikai** [comment]
> Yep stacktrace point to `findAll` which is called by `findById`, looks like you are accidentally passing instance (an object) instead of `id`. Try commenting or passing ids in `findById` one by one to discover the bug or add logs before passing `id` to `findById`
>```js
> static async findUserById(id) {
>         console.log(typeof id);
>         console.log(id)
>         return await User.findByPk(id);
>     }
>```

> number
> 1
> Executing (default): SELECT `id`, `username`, `password`, `session_key`, `phone`, `email`, `money`, `city`, `avatarUrl`, `sex`, `birthday`, `lastLoginTime`, `registerTime`, `wxOpenid`, `createdAt`, `updatedAt` FROM `user` AS `user` WHERE `user`.`id` = 1;

**Comment by shiqikai** [comment]
> Yep stacktrace point to `findAll` which is called by `findById`, looks like you are accidentally passing instance (an object) instead of `id`. Try commenting or passing ids in `findById` one by one to discover the bug or add logs before passing `id` to `findById`

the log show the id is number .   I really don't know  how to fix it.  Looking for your help  eagerly 。Thanks

**Comment by sushantdhiman** [comment]
Try `community.addUser(user) => community.addUsers([user])`

**Comment by shiqikai** [comment]
> Try `community.addUser(user) => community.addUsers([user])`

now log is:
>```js
> 'updatedAt' ] },
>   __eagerlyLoadedAssociations: [],
>   isNewRecord: false }
>     at Object.escape (D:\project\koa2-community\node_modules\sequelize\lib\sql-string.js:66:11)
>     at Object.escape (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:936:22)
>     at _joinKeyValue.value.map.item (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2372:69)
>     at Array.map (<anonymous>)
>     at Object._whereParseSingleValueObject (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2372:52)
>     at Object.whereItemQuery (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2130:19)
>     at Utils.getComplexKeys.forEach.prop (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1997:25)
>     at Array.forEach (<anonymous>)
>     at Object.whereItemsQuery (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1995:35)
>     at Object.getWhereConditions (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2459:19)
>     at Object.selectQuery (D:\project\koa2-community\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1143:28)
>     at QueryInterface.select (D:\project\koa2-community\node_modules\sequelize\lib\query-interface.js:1105:27)
>     at Promise.try.then.then.then (D:\project\koa2-community\node_modules\sequelize\lib\model.js:1598:34)
>     at tryCatcher (D:\project\koa2-community\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (D:\project\koa2-community\node_modules\bluebird\js\release\promise.js:512:31)
>     at Promise._settlePromise (D:\project\koa2-community\node_modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (D:\project\koa2-community\node_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (D:\project\koa2-community\node_modules\bluebird\js\release\promise.js:693:18)
>     at Async._drainQueue (D:\project\koa2-community\node_modules\bluebird\js\release\async.js:133:16)
>     at Async._drainQueues (D:\project\koa2-community\node_modules\bluebird\js\release\async.js:143:10)
>     at Immediate.Async.drainQueues (D:\project\koa2-community\node_modules\bluebird\js\release\async.js:17:14)
>     at runCallback (timers.js:810:20)
>```

**Comment by shiqikai** [comment]
why closed?

**Comment by sushantdhiman** [comment]
I didn't closed this issue, you did :) 

But there is no point in opening/closing this issue as you can't reproduce it as SSCCE. May be ask your colleagues to help you?

You said earlier you were using `addUser` but now I read the description it says you are using `community.setUser(user)`? Have you tried `setUsers([user])`? This could also happen if `user` is not linked with community

**Comment by shiqikai** [comment]
I tried. but the result is the same as before

**Comment by sushantdhiman** [comment]
You posted your models earlier but I dont see 

```js
static async findUserById(id) {
        return await User.findById(id);
    }
```

Where is that defined, post full model dont hide anything that you think is un-necessary :) Also do you have any model with same name? Do a recheck

**Comment by shiqikai** [comment]
> You posted your models earlier but I dont see
> 
> ```js
> static async findUserById(id) {
>         return await User.findById(id);
>     }
> ```
> 
> Where is that defined, post full model dont hide anything that you think is un-necessary :) Also do you have any model with same name? Do a recheck

sorry,  now i have posted my code in [github](https://github.com/shiqikai/mysql-koa2-suquelize)

If you have time to review my code, I would be grateful.  Thanks!

**Comment by shiqikai** [comment]
> You posted your models earlier but I dont see
> 
> ```js
> static async findUserById(id) {
>         return await User.findById(id);
>     }
> ```
> 
> Where is that defined, post full model dont hide anything that you think is un-necessary :) Also do you have any model with same name? Do a recheck

Hello  dear friend , can you waste a munite to review my code commited yesterday?   my sincerely gratefulness

**Comment by shiqikai** [comment]
> You posted your models earlier but I dont see
> 
> ```js
> static async findUserById(id) {
>         return await User.findById(id);
>     }
> ```
> 
> Where is that defined, post full model dont hide anything that you think is un-necessary :) Also do you have any model with same name? Do a recheck

Hello dear friend , can you waste a munite to review my code commited yesterday? my sincerely gratefulness

**Comment by shiqikai** [comment]
> You posted your models earlier but I dont see
> 
> ```js
> static async findUserById(id) {
>         return await User.findById(id);
>     }
> ```
> 
> Where is that defined, post full model dont hide anything that you think is un-necessary :) Also do you have any model with same name? Do a recheck

Hello dear friend , can you waste a munite to review my code commited yesterday? my sincerely gratefulness

**Comment by shiqikai** [comment]
> You posted your models earlier but I dont see
> 
> ```js
> static async findUserById(id) {
>         return await User.findById(id);
>     }
> ```
> 
> Where is that defined, post full model dont hide anything that you think is un-necessary :) Also do you have any model with same name? Do a recheck

Or can you show me an example about manytomany associations in practice ? Not the uncompleted codes in your tutorial。

**Comment by shiqikai** [comment]
can you finger out what's the problem in my code ? :)
