### ISSUE TITLE
How can I get a flat array instead of json array?

### ISSUE THREAD

**Issue by hiowenluke** [sequelize/sequelize#10298]
Hi guys,

I wanna to get a flat array from mssql/mysql, like this:
[['id', 'field1', 'field2'], [1, 'a', 'b'], [2, 'c', 'd'], ...]

instead of this:
[{"id": 1, "field1": "a", "field2": "b"}, {"id": 2, "field1": "c", "field2": "d"}]

What should I do?

Yes, I can convert the json array to  a flat array, but it's too wasteful. 
So, if Sequelize can return a flat array directly (not converted to a json array) after fetching data from the database, that will be great.

Thanks.
Owen Luke

**Comment by mkaufmaner** [comment]
This is not possible at the moment with existing Sequelize methods.  You could try to use the dialect modules (pg, mysql, etc) consumed by Sequelize but I am unsure of their capabilities.  You could also try casting the columns into an array from the database itself but this can only be done if the database supports arrays (postgres).

However, I would recommend that you determine if that data suture is even necessary.  Sure, it would be efficient in terms of memory but the downside would be an increased level of effort when it comes to implementation.
