### ISSUE TITLE
Sequelize.cast(column, 'DECIMAL(m,d)) not working

### ISSUE THREAD

**Issue by mfatima96** [sequelize/sequelize#10294]
## What are you doing?
I am using sequelize operations to build my query for searching an SQL column with JSON datatype column.

Raw query against my sequelized search query is as follow.

`SELECT 'id' FROM 'devices' AS 'Devices' WHERE ((CAST(('Devices'.'metadataFields'->>'$."longitude"') AS DECIMAL) >= 30.788 AND 'Devices'.'clientId' = 1))` 

where metadataFields is my sql column with data type JSON and longitude is a key upon which I want to search. In short I am searching a json on the basis of its keys.

The above query is casting the number to decimal digit with zero precision. i-e DECIMAl(10,0) according to the default values. By the way this conversion of DECIMAL is the default behavior of sequelize.

## What do you expect to happen?
It should return all devices having metadataFields.longitude >= 30.788

## What is actually happening?
It is returning all devices where longitude >= 30 which means it is searching only the integer part that is the precision is zero. As you can see in the above mentioned raw query.

## What I tried to solve this ?
I tried sequelize.cast(colomn_name, DECIMAL(m,d)) with m = 10, d = 5.

sequelize.cast("metadataFields.longitude", 'DECIMAL(10,5)) returns the following object

Cast {
 val: Col { col: 'metadataFields.longitude' },
 type: 'DECIMAL(10,5)',
 json: false
}

which seems fine because it is casting the number into the Decimal of my own requirment.

When I pass this casted column in my where clause I get this kind of raw query.

SELECT `id` FROM `devices` AS `Devices` WHERE ((`Devices`.`{"val":{"col":"metadataFields.longitude"},"type":"DECIMAL(10,2)","json":false}` >= 30.788) AND `Devices`.`clientId` = 1));

but running this query gives me unknown column error.

"sqlMessage": "Unknown column 'Devices.{\"val\":{\"col\":\"metadataFields.longitude\"},\"type\":\"DECIMAL(2,5)\",\"json\":false}' in 'where clause'" because of casting this field.

By the way, raw query which works fine is as follows.

SELECT id from devices where cast(JSON_EXTRACT(metadataFields, "$.latitude") as decimal(10,2)) > 24.4

So, I want to find how we can achieve this using sequelize?

__mysql version:__ 5.7.24
__Sequelize version:__ 4.41.2
__Tested with latest release:__ No

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._
```

**Comment by sushantdhiman** [comment]
You can't pass these constructs like `col, fn etc` to `sequelize.query` as they are not strings, they are only valid when using sequelize where format.

You can possible translate them to proper SQL statement by `queryGenerator.whereItemQuery` etc but that is a private API.

So if you are using raw queries, construct queries yourself or use https://github.com/sequelize/sequelize/blob/5296da9c5df678c32310f7ff20b7da0e16a04097/lib/query-interface.js#L1103
