### ISSUE TITLE
Table created with wrong name

### ISSUE THREAD

**Issue by GermanDevCoding** [sequelize/sequelize#10297]
## What are you doing?
```js
const AccountSecurity = connection.define('AccountSecurity',
	{
		UID: sequelize.INTEGER,
		Password: sequelize.STRING,
	});
```

## What do you expect to happen?
_Create a table called "AccountSecurity"_

## What is actually happening?
_A table called "AccountSecurities" is created_

__Dialect:__ mysql
__Dialect version:__ 1.6.4
__Database version:__ 5.7.24
__Sequelize version:__ 4.42.0
__Tested with latest release:__ yes

**Comment by sbonami** [comment]
This is expected behavior. See the `freezeTableName` and/or `tableName` [configuration options](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#configuration):

```js
const Bar = sequelize.define('bar', { /* bla */ }, {
  // disable the modification of table names; By default, sequelize will automatically
  // transform all passed model names (first parameter of define) into plural.
  // if you don't want that, set the following
  freezeTableName: true,

  // define the table's name
  tableName: 'my_very_custom_table_name',
})
```

**Comment by jasontianxie** [comment]
use sequelize.getQueryInterface().createTable（） to create a table
http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-createTable

by the way ，the first parameter of createTable (table name) ,will automatically call toLowerCase(),so when you want to create "AccountSecurity" ,actually ,you will get "accountsecurity"

**Comment by GermanDevCoding** [comment]
Allright, didn't expected that 👍
