### ISSUE TITLE
Does model definition support native point datatype in postgresql?

### ISSUE THREAD

**Issue by zhengdai** [sequelize/sequelize#10295]
I want to use pg native point datatype, but I only find the GEOMETRY('point') which need postgis?

**Comment by mkaufmaner** [comment]
Currently, Sequelize only supports PostGIS data types using the GEOMETRY and GEOGRAPHY data types.  See http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

IMHO, I would recommend using PostGIS for all geospatial types and operations.  It is a very powerful and mature Postgres extension.  Also, most, if not all, Postgres DBaaS providers support the PostGIS extension.

**Comment by rnukala** [comment]
Does it support defining a column as multipolygon in model? If not how do I define my column as multipolygon.
