### ISSUE TITLE
findOrCreate throws validation error 

### ISSUE THREAD

**Issue by paulowski** [sequelize/sequelize#10302]
## What are you doing?
I want to create a super-user (see below) (if he does not exist already) whenever I start my node.js server in order to have at least one admin in the database.

```js
import md5 from 'md5';
import Sequelize from 'sequelize';
import loggerFactory from '../logging';

const logger = loggerFactory('models-user', false, true);
import getConfiguredSequelize from '../database/configuredSequelize';
// TODO: User 'instanceMethods and classMethods'
const sequelize = getConfiguredSequelize();
// setup User models and its fields.
const User = sequelize.define('users', {
  username: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    validate: {
      notEmpty: false,
    },
  },
  email: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    validate: {
      isEmail: true,
    },
  },
  password: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      notEmpty: false,
    },
  },
  subscribed: {
    type: Sequelize.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  },
  isAdmin: {
    type: Sequelize.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  },
}, {
  hooks: {
    beforeCreate: (user) => {
      user.password = md5(user.password);
    },
    beforeDestroy: (user) => {
      if (user.username === process.env.SUPER_ADMIN_NAME) {
        throw new Error('Cannot destroy super-admin.');
      }
    },
  },
});

User.prototype.validPassword = (password) => {
  return md5(password) === this.password;
};

User.prototype.toString = function() {
  return `User[${this.username} /w ${this.email}]`;
};
// create all the defined tables in the specified database.
sequelize.sync().
    then(() => {
      logger.info(
          'Users table has been successfully created, if one doesn\'t exist');
      // super-admin means that this admin cannot be deleted
      User.findOrCreate({
        where: {
          username: process.env.SUPER_ADMIN_NAME,
        }, default: {
          username: process.env.SUPER_ADMIN_NAME,
          email: process.env.SUPER_ADMIN_EMAIL,
          isAdmin: true,
          password: process.env.SUPER_ADMIN_PASSWORD, // NOT NULL (certainly)
        },
      }).spread((a, b) => {
        console.log(a);
        console.log(b);
      }).catch(
          (error) => {
            logger.error({
              message: 'Unable to check and' +
                  ' - if it is necessary - create the super-admin.',
              error: error,
            });
            throw error;
          });
    }).
    catch(
        (error) => logger.error(
            'This error occurred while creating users table',
            error));

export default User;
```

## What do you expect to happen?
Should create a super-user because database is empty.

## What is actually happening?
I got an error:

_Output, either JSON or SQL_
Unhandled rejection SequelizeValidationError: notNull Violation: users.email cannot be null,
notNull Violation: users.password cannot be null

__Dialect:__ sqlite
__Dialect version:__ 3
__Database_version__: ? don't know that you mean
__Sequelize version:__ 4
__Tested with latest release:__ Yes

**Comment by paulowski** [comment]
It works with:
`import md5 from 'md5';
import Sequelize from 'sequelize';
import loggerFactory from '../logging';

const logger = loggerFactory('models-user', false, true);
import getConfiguredSequelize from '../database/configuredSequelize';
// TODO: User 'instanceMethods and classMethods'
const sequelize = getConfiguredSequelize();
// setup User models and its fields.
const User = sequelize.define('users', {
  username: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    validate: {
      notEmpty: false,
    },
  },
  email: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    validate: {
      isEmail: true,
    },
  },
  password: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      notEmpty: false,
    },
  },
  subscribed: {
    type: Sequelize.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  },
  isAdmin: {
    type: Sequelize.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  },
}, {
  hooks: {
    beforeCreate: (user) => {
      user.password = md5(user.password);
    },
    beforeDestroy: (user) => {
      if (user.username === process.env.SUPER_ADMIN_NAME) {
        throw new Error('Cannot destroy super-admin.');
      }
    },
  },
});

User.prototype.validPassword = (password) => {
  return md5(password) === this.password;
};

User.prototype.toString = function() {
  return `User[${this.username} /w ${this.email}]`;
};

          
sequelize.sync()
  .then(() => {
    console.log('`users` table successfully synced.');
    // look if super-admin exists
    return User.count({ where: { username: process.env.SUPER_ADMIN_NAME} })
      .then((count) => {return count !== 0});
  })
  .then((superAdminExists) => {
    if(superAdminExists) return;
    return User.create({
      username: process.env.SUPER_ADMIN_NAME,
      password: process.env.SUPER_ADMIN_PASSWORD,
      email: process.env.SUPER_ADMIN_EMAIL,
      isAdmin: 1
    });
  })
  .catch(logger.error)

export default User;

/*
then((result) => {
        if (result[1] === true) {
          logger.log('Created super-admin. ' + result[0].toString() +
              ' already exists.');
        } else {
          logger.log('Did not create super-admin. ' + result[0].toString() +
              ' is already super-admin.');
        }})
 */`
But anyways, the problem persists

**Comment by sushantdhiman** [comment]
`findOrCreate` need `defaults` not `default`

**Comment by shamseerahammedm** [comment]
@sushantdhiman saved hours of debugging 👍
