### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by who93** [sequelize/sequelize#10304]
Hi,
Is there a fix for this issue? I already tried some suggestions posted here in github, but none of them worked.
```
const sequelize = new Sequelize('db', 'root', 'root', {
  host: 'localhost',
  dialect: 'sqlite',
  retry: {
        match: [
          /SQLITE_BUSY/,
        ],
        name: 'query',
        max: 5
      },
  pool: {
        maxactive: 1,
        max: 5,
        min: 0,
        idle: 20000
      },
  storage: database
})
```
I am adding items to a sqlite database in a for loop (3 times). The first one gets posted to the database, on the other two I get the "SequelizeTimeoutError: SQLITE_BUSY: database is locked" error. Any fixes for that? Or any suggestion how I can add elements to the DB using a loop?

**Comment by rahuljayaraman** [comment]
Try setting `transactionType: 'IMMEDIATE'`. To understand why it works, have a look at https://www.activesphere.com/blog/2018/12/24/understanding-sqlite-busy and 
https://github.com/sequelize/sequelize/issues/10262

**Comment by sushantdhiman** [comment]
x

**Comment by alacret** [comment]
@rahuljayaraman 

For additional info, in my use case, I was using Sequelize wth SQLite in a test runner, which creates multiple instances to run tests in parallel; if you re-use a database in multiple tests, and those tests have a transaction, you get the deadlock error.

There were 2 scenarios identified:

1. Using the same database in 2 different tests creates a Deadlock, as each tests request a transaction, and SQLite does not support multiple transactions
2. Using the same data in the same tests. When you call .transaction on sequelize, you have to cache the value of the transaction and return it the next time.

**Comment by Griffinxaxa** [comment]
great
