### ISSUE TITLE
Update Typescript definitions for TransactionOptions

### ISSUE THREAD

**Issue by Nelrohd** [sequelize/sequelize#10305]
## What are you doing?
The Typescript definition of Sequelize does not contain the `transaction` object in `interface TransactionOptions`:

```
// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts
// Type definitions for Sequelize 4.27.11
// ...
interface TransactionOptions {

    autocommit?: boolean;

    /**
     *  See `Sequelize.Transaction.ISOLATION_LEVELS` for possible options
     */
    isolationLevel?: TransactionIsolationLevel;

    /**
     *  See `Sequelize.Transaction.TYPES` for possible options
     */
    type?: TransactionType;

    /**
     * A function that gets executed while running the query to log the sql.
     */
    logging?: Function;

}
```

## What do you expect to happen?
I want to be able to use in Typescript without errors:
```
sequelize.transaction({ transaction: transactionParent }, async transaction => {
  ...
}
```

## What is actually happening?
I get the `transaction` object does not exist in type `TransactionOptions`.

__Dialect:__ mysql
__Dialect version:__ 2.16.0
__Database version:__ mysql  Ver 14.14 Distrib 5.7.18, for osx10.12 (x86_64) using  EditLine wrapper
__Sequelize version:__ 4.38.0
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
We don't maintain typescript definitions but we plan to ship them officially with v5

**Comment by jwigley** [comment]
The [reference]( http://docs.sequelizejs.com/class/lib/transaction.js~Transaction.html#instance-constructor-constructor) and [usage](http://docs.sequelizejs.com/manual/tutorial/transactions.html#options) documentation also does not list`transaction` as a valid option.
