### ISSUE TITLE
The QueryTypes.SELECT option in sequelize.query() is not working along with model option

### ISSUE THREAD

**Issue by gauravsinghaec** [sequelize/sequelize#10301]
## Problem Statement
Trying to get the result after **sequelize.query** but it is returning both results and metadata even after passing the option **type: models.sequelize.QueryTypes.SELECT**,
```js
                await models.sequelize.query(
                  `select en.*, el.query as manual_search_queries  
                    from entities en join exchanges ex 
                    on en.exchange = ex.accern_id
                    left join entity_lucene_queries el on en.id = el.entity_id
                    WHERE en.status not in(:status)
                    and en.end_date is null`,
                  { type: models.sequelize.QueryTypes.SELECT,
                    replacements: { status: ['live', 'approved']},
                    model: Entity,
                    mapToModel: true
                  }
                ).then(entity => {
                  console.log(entity)
```

## What do you expect to happen?
_entity in .then should be the array of results_

## What is actually happening?
_But the output was results and metadata, even though I have set the options type:_

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
