### ISSUE TITLE
Model.findOne() and Model.findAll() return columns in the wrong order

### ISSUE THREAD

**Issue by styx7308** [sequelize/sequelize#10303]
## What are you doing?
 Here is my model:

```js
module.exports = (sequelize, DataType) => {
  const survey = sequelize.define(
    'survey',
    {
      id: {
        type: DataType.UUID,
        defaultValue: DataType.UUIDV4,
        primaryKey: true
      },
      farmerId: {
        type: DataType.STRING,
        allowNull: false
      },
      result: {
        type: DataType.JSON,
        allowNull: false
      }
    },
    {}
  )

  return survey
}
```
When I call Model.findOne(), the returned result has all the attributes in the different order than the database columns.

## What do you expect to happen?
I would expect the result maintain the attribute order defined in the model, so the result should look like

```js
{
   "id": "xxx",
   "farmerId": "xxx",
   "result": "xxx",
   "createdAt": "xxx",
   "updatedAt": "xxx"
}
```

This will match the exact column orders in the database.

## What is actually happening?

But here is the actual result:

```js
{
   "createdAt": "xxx",
   "farmerId": "xxx",
   "id": "xxx",
   "result": "xxx",
   "updatedAt": "xxx"
}
```

You can see the order of attributes is changed.

**Comment by justinkalland** [comment]
Hello @styx7308. I am trying to understand, do you have a use case where the properties need to be in a specific order?

**Comment by styx7308** [comment]
Not a functional concern, just for better readability for business users. 

I also believe in the previous version, the order was indeed preserved as specified in the model definition. Is this new behavior introduced for some good reason?

**Comment by weexpectedTHIS** [comment]
Wouldn't the order they are listed completely depend on the method you are using to output them? In which case this has nothing to do with Sequelize?

**Comment by mkaufmaner** [comment]
When you do not explicitly pass attributes in a find method, the order of the attributes and their respective values for each instance returned will reflect the order of the columns in the table.  Also, even if you explicitly pass the attributes you want to return, there is still the inherit caveat that the order of properties in objects are **not guaranteed** in JavaScript.

**Comment by sushantdhiman** [comment]
Object key order is not guaranteed in Node.js anyway, so we can't support this
