### ISSUE TITLE
about utf8mb4

### ISSUE THREAD

**Issue by formattedzzz** [sequelize/sequelize#10300]
#### It's not work after setting database's  codeformat to 'utf8mb4'. still to excute mysql syntax manually

**Comment by knoxcard** [comment]
Please post your code :-)

Does your connection code contain this?
```
  define: {
    charset: 'utf8mb4',
    timestamps: false,
    dialectOptions: {
      collate: 'utf8mb4_general_ci'
    }
  }
```

**Comment by formattedzzz** [comment]
ok ! no problem. it's my mistake on sql setting
