### ISSUE TITLE
Referencing other table's column in where query is not working?

### ISSUE THREAD

**Issue by deepak057** [sequelize/sequelize#10319]
Lets say I have this DB criteria object-

    let criteria = {
      include: [

          {
            model: Comments,
            include: [
              {
                model: User.scope('public')
              },
              {
                model: Likes
              }
            ]
          },
          {
            model: User.scope('public')
          },
          {
            model: AdOptions,
          },
          {
            model: Images,
          },
          {
            model: Questions,
          },
          {
            model: Likes,
          },
          {
            model: Videos
          },
          {
            model: Tags
          }
        ] ,
      
      /*
      * Get only those posts which are from user's friends, public, self created or ads
      */
      where: {
        [op.or]: [
          {
            UserId: friendIds
          },
          {
            AdOptionId: { [op.ne]: null}
          },
          {
            public: { [op.eq]: true},
            '$Tags.id$': TagsIdsArray
          }
        ]}
    };

And I use it like this-  
         
    Posts.findAll(criteria)
.
.

I get following error-

    {"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'Tags.id' in 'where clause'","sql":"SELECT `Posts`.*, `Comments`.`id` AS `Comments.id`, `Comments`.`type` AS `Comments.type`, `Comments`.`comment` AS `Comments.comment`, `Comments`.`createdAt` AS `Comments.createdAt`, `Comments`.`updatedAt` AS `Comments.updatedAt`, `Comments`.`PostId` AS `Comments.PostId`, `Comments`.`UserId` AS `Comments.UserId`, `Comments->PostComments`.`createdAt` AS `Comments.PostComments.createdAt`, `Comments->PostComments`.`updatedAt` AS `Comments.PostComments.updatedAt`, `Comments->PostComments`.`PostId` AS `Comments.PostComments.PostId`, `Comments->PostComments`.`CommentId` AS `Comments.PostComments.CommentId`, `Comments->User`.`id` AS `Comments.User.id`, `Comments->User`.`first` AS `Comments.User.first`, `Comments->User`.`last` AS `Comments.User.last`, `Comments->User`.`phone` AS `Comments.User.phone`, `Comments->User`.`pic` AS `Comments.User.pic`, `Comments->Likes`.`id` AS `Comments.Likes.id`, `Comments->Likes`.`createdAt` AS `Comments.Likes.createdAt`, `Comments->Likes`.`updatedAt` AS `Comments.Likes.updatedAt`, `Comments->Likes`.`UserId` AS `Comments.Likes.UserId`, `Comments->Likes`.`PostId` AS `Comments.Likes.PostId`, `Comments->Likes`.`CommentId` AS `Comments.Likes.CommentId`, `Comments->Likes->CommentLikes`.`createdAt` AS `Comments.Likes.CommentLikes.createdAt`, `Comments->Likes->CommentLikes`.`updatedAt` AS `Comments.Likes.CommentLikes.updatedAt`, `Comments->Likes->CommentLikes`.`CommentId` AS `Comments.Likes.CommentLikes.CommentId`, `Comments->Likes->CommentLikes`.`LikeId` AS `Comments.Likes.CommentLikes.LikeId`, `User`.`id` AS `User.id`, `User`.`first` AS `User.first`, `User`.`last` AS `User.last`, `User`.`phone` AS `User.phone`, `User`.`pic` AS `User.pic`, `AdOption`.`id` AS `AdOption.id`, `AdOption`.`postIsAd` AS `AdOption.postIsAd`, `AdOption`.`cpc` AS `AdOption.cpc`, `AdOption`.`cpv` AS `AdOption.cpv`, `AdOption`.`clickURL` AS `AdOption.clickURL`, `AdOption`.`createdAt` AS `AdOption.createdAt`, `AdOption`.`updatedAt` AS `AdOption.updatedAt`, `AdOption`.`UserId` AS `AdOption.UserId`, `Images`.`id` AS `Images.id`, `Images`.`path` AS `Images.path`, `Images`.`createdAt` AS `Images.createdAt`, `Images`.`updatedAt` AS `Images.updatedAt`, `Images`.`UserId` AS `Images.UserId`, `Images`.`PostId` AS `Images.PostId`, `Images->PostImages`.`createdAt` AS `Images.PostImages.createdAt`, `Images->PostImages`.`updatedAt` AS `Images.PostImages.updatedAt`, `Images->PostImages`.`PostId` AS `Images.PostImages.PostId`, `Images->PostImages`.`ImageId` AS `Images.PostImages.ImageId`, `Question`.`id` AS `Question.id`, `Question`.`question` AS `Question.question`, `Question`.`description` AS `Question.description`, `Question`.`createdAt` AS `Question.createdAt`, `Question`.`updatedAt` AS `Question.updatedAt`, `Question`.`UserId` AS `Question.UserId`, `Likes`.`id` AS `Likes.id`, `Likes`.`createdAt` AS `Likes.createdAt`, `Likes`.`updatedAt` AS `Likes.updatedAt`, `Likes`.`UserId` AS `Likes.UserId`, `Likes`.`PostId` AS `Likes.PostId`, `Likes`.`CommentId` AS `Likes.CommentId`, `Likes->PostLikes`.`createdAt` AS `Likes.PostLikes.createdAt`, `Likes->PostLikes`.`updatedAt` AS `Likes.PostLikes.updatedAt`, `Likes->PostLikes`.`PostId` AS `Likes.PostLikes.PostId`, `Likes->PostLikes`.`LikeId` AS `Likes.PostLikes.LikeId`, `Video`.`id` AS `Video.id`, `Video`.`title` AS `Video.title`, `Video`.`description` AS `Video.description`, `Video`.`path` AS `Video.path`, `Video`.`createdAt` AS `Video.createdAt`, `Video`.`updatedAt` AS `Video.updatedAt`, `Video`.`UserId` AS `Video.UserId`, `Tags`.`id` AS `Tags.id`, `Tags`.`name` AS `Tags.name`, `Tags`.`icon` AS `Tags.icon`, `Tags`.`UserId` AS `Tags.UserId`, `Tags`.`createdAt` AS `Tags.createdAt`, `Tags`.`updatedAt` AS `Tags.updatedAt`, `Tags->PostsTags`.`createdAt` AS `Tags.PostsTags.createdAt`, `Tags->PostsTags`.`updatedAt` AS `Tags.PostsTags.updatedAt`, `Tags->PostsTags`.`PostId` AS `Tags.PostsTags.PostId`, `Tags->PostsTags`.`TagId` AS `Tags.PostsTags.TagId` FROM (SELECT `Posts`.`id`, `Posts`.`type`, `Posts`.`content`, `Posts`.`public`, `Posts`.`createdAt`, `Posts`.`updatedAt`, `Posts`.`UserId`, `Posts`.`QuestionId`, `Posts`.`AdOptionId`, `Posts`.`VideoId` FROM `Posts` AS `Posts` WHERE (`Posts`.`UserId` IN (1) OR `Posts`.`AdOptionId` IS NOT NULL OR (`Posts`.`public` = true AND `Tags`.`id` IN (1))) ORDER BY `Posts`.`updatedAt` DESC LIMIT 0, 10) AS `Posts` LEFT OUTER JOIN ( `PostComments` AS `Comments->PostComments` INNER JOIN `Comments` AS `Comments` ON `Comments`.`id` = `Comments->PostComments`.`CommentId`) ON `Posts`.`id` = `Comments->PostComments`.`PostId` LEFT OUTER JOIN `Users` AS `Comments->User` ON `Comments`.`UserId` = `Comments->User`.`id` LEFT OUTER JOIN ( `CommentLikes` AS `Comments->Likes->CommentLikes` INNER JOIN `Likes` AS `Comments->Likes` ON `Comments->Likes`.`id` = `Comments->Likes->CommentLikes`.`LikeId`) ON `Comments`.`id` = `Comments->Likes->CommentLikes`.`CommentId` LEFT OUTER JOIN `Users` AS `User` ON `Posts`.`UserId` = `User`.`id` LEFT OUTER JOIN `AdOptions` AS `AdOption` ON `Posts`.`AdOptionId` = `AdOption`.`id` LEFT OUTER JOIN ( `PostImages` AS `Images->PostImages` INNER JOIN `Images` AS `Images` ON `Images`.`id` = `Images->PostImages`.`ImageId`) ON `Posts`.`id` = `Images->PostImages`.`PostId` LEFT OUTER JOIN `Questions` AS `Question` ON `Posts`.`QuestionId` = `Question`.`id` LEFT OUTER JOIN ( `PostLikes` AS `Likes->PostLikes` INNER JOIN `Likes` AS `Likes` ON `Likes`.`id` = `Likes->PostLikes`.`LikeId`) ON `Posts`.`id` = `Likes->PostLikes`.`PostId` LEFT OUTER JOIN `Videos` AS `Video` ON `Posts`.`VideoId` = `Video`.`id` LEFT OUTER JOIN ( `PostsTags` AS `Tags->PostsTags` INNER JOIN `Tags` AS `Tags` ON `Tags`.`id` = `Tags->PostsTags`.`TagId`) ON `Posts`.`id` = `Tags->PostsTags`.`PostId` ORDER BY `Posts`.`updatedAt` DESC;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'Tags.id' in 'where clause'","sql":"SELECT `Posts`.*, `Comments`.`id` AS `Comments.id`, `Comments`.`type` AS `Comments.type`, `Comments`.`comment` AS `Comments.comment`, `Comments`.`createdAt` AS `Comments.createdAt`, `Comments`.`updatedAt` AS `Comments.updatedAt`, `Comments`.`PostId` AS `Comments.PostId`, `Comments`.`UserId` AS `Comments.UserId`, `Comments->PostComments`.`createdAt` AS `Comments.PostComments.createdAt`, `Comments->PostComments`.`updatedAt` AS `Comments.PostComments.updatedAt`, `Comments->PostComments`.`PostId` AS `Comments.PostComments.PostId`, `Comments->PostComments`.`CommentId` AS `Comments.PostComments.CommentId`, `Comments->User`.`id` AS `Comments.User.id`, `Comments->User`.`first` AS `Comments.User.first`, `Comments->User`.`last` AS `Comments.User.last`, `Comments->User`.`phone` AS `Comments.User.phone`, `Comments->User`.`pic` AS `Comments.User.pic`, `Comments->Likes`.`id` AS `Comments.Likes.id`, `Comments->Likes`.`createdAt` AS `Comments.Likes.createdAt`, `Comments->Likes`.`updatedAt` AS `Comments.Likes.updatedAt`, `Comments->Likes`.`UserId` AS `Comments.Likes.UserId`, `Comments->Likes`.`PostId` AS `Comments.Likes.PostId`, `Comments->Likes`.`CommentId` AS `Comments.Likes.CommentId`, `Comments->Likes->CommentLikes`.`createdAt` AS `Comments.Likes.CommentLikes.createdAt`, `Comments->Likes->CommentLikes`.`updatedAt` AS `Comments.Likes.CommentLikes.updatedAt`, `Comments->Likes->CommentLikes`.`CommentId` AS `Comments.Likes.CommentLikes.CommentId`, `Comments->Likes->CommentLikes`.`LikeId` AS `Comments.Likes.CommentLikes.LikeId`, `User`.`id` AS `User.id`, `User`.`first` AS `User.first`, `User`.`last` AS `User.last`, `User`.`phone` AS `User.phone`, `User`.`pic` AS `User.pic`, `AdOption`.`id` AS `AdOption.id`, `AdOption`.`postIsAd` AS `AdOption.postIsAd`, `AdOption`.`cpc` AS `AdOption.cpc`, `AdOption`.`cpv` AS `AdOption.cpv`, `AdOption`.`clickURL` AS `AdOption.clickURL`, `AdOption`.`createdAt` AS `AdOption.createdAt`, `AdOption`.`updatedAt` AS `AdOption.updatedAt`, `AdOption`.`UserId` AS `AdOption.UserId`, `Images`.`id` AS `Images.id`, `Images`.`path` AS `Images.path`, `Images`.`createdAt` AS `Images.createdAt`, `Images`.`updatedAt` AS `Images.updatedAt`, `Images`.`UserId` AS `Images.UserId`, `Images`.`PostId` AS `Images.PostId`, `Images->PostImages`.`createdAt` AS `Images.PostImages.createdAt`, `Images->PostImages`.`updatedAt` AS `Images.PostImages.updatedAt`, `Images->PostImages`.`PostId` AS `Images.PostImages.PostId`, `Images->PostImages`.`ImageId` AS `Images.PostImages.ImageId`, `Question`.`id` AS `Question.id`, `Question`.`question` AS `Question.question`, `Question`.`description` AS `Question.description`, `Question`.`createdAt` AS `Question.createdAt`, `Question`.`updatedAt` AS `Question.updatedAt`, `Question`.`UserId` AS `Question.UserId`, `Likes`.`id` AS `Likes.id`, `Likes`.`createdAt` AS `Likes.createdAt`, `Likes`.`updatedAt` AS `Likes.updatedAt`, `Likes`.`UserId` AS `Likes.UserId`, `Likes`.`PostId` AS `Likes.PostId`, `Likes`.`CommentId` AS `Likes.CommentId`, `Likes->PostLikes`.`createdAt` AS `Likes.PostLikes.createdAt`, `Likes->PostLikes`.`updatedAt` AS `Likes.PostLikes.updatedAt`, `Likes->PostLikes`.`PostId` AS `Likes.PostLikes.PostId`, `Likes->PostLikes`.`LikeId` AS `Likes.PostLikes.LikeId`, `Video`.`id` AS `Video.id`, `Video`.`title` AS `Video.title`, `Video`.`description` AS `Video.description`, `Video`.`path` AS `Video.path`, `Video`.`createdAt` AS `Video.createdAt`, `Video`.`updatedAt` AS `Video.updatedAt`, `Video`.`UserId` AS `Video.UserId`, `Tags`.`id` AS `Tags.id`, `Tags`.`name` AS `Tags.name`, `Tags`.`icon` AS `Tags.icon`, `Tags`.`UserId` AS `Tags.UserId`, `Tags`.`createdAt` AS `Tags.createdAt`, `Tags`.`updatedAt` AS `Tags.updatedAt`, `Tags->PostsTags`.`createdAt` AS `Tags.PostsTags.createdAt`, `Tags->PostsTags`.`updatedAt` AS `Tags.PostsTags.updatedAt`, `Tags->PostsTags`.`PostId` AS `Tags.PostsTags.PostId`, `Tags->PostsTags`.`TagId` AS `Tags.PostsTags.TagId` FROM (SELECT `Posts`.`id`, `Posts`.`type`, `Posts`.`content`, `Posts`.`public`, `Posts`.`createdAt`, `Posts`.`updatedAt`, `Posts`.`UserId`, `Posts`.`QuestionId`, `Posts`.`AdOptionId`, `Posts`.`VideoId` FROM `Posts` AS `Posts` WHERE (`Posts`.`UserId` IN (1) OR `Posts`.`AdOptionId` IS NOT NULL OR (`Posts`.`public` = true AND `Tags`.`id` IN (1))) ORDER BY `Posts`.`updatedAt` DESC LIMIT 0, 10) AS `Posts` LEFT OUTER JOIN ( `PostComments` AS `Comments->PostComments` INNER JOIN `Comments` AS `Comments` ON `Comments`.`id` = `Comments->PostComments`.`CommentId`) ON `Posts`.`id` = `Comments->PostComments`.`PostId` LEFT OUTER JOIN `Users` AS `Comments->User` ON `Comments`.`UserId` = `Comments->User`.`id` LEFT OUTER JOIN ( `CommentLikes` AS `Comments->Likes->CommentLikes` INNER JOIN `Likes` AS `Comments->Likes` ON `Comments->Likes`.`id` = `Comments->Likes->CommentLikes`.`LikeId`) ON `Comments`.`id` = `Comments->Likes->CommentLikes`.`CommentId` LEFT OUTER JOIN `Users` AS `User` ON `Posts`.`UserId` = `User`.`id` LEFT OUTER JOIN `AdOptions` AS `AdOption` ON `Posts`.`AdOptionId` = `AdOption`.`id` LEFT OUTER JOIN ( `PostImages` AS `Images->PostImages` INNER JOIN `Images` AS `Images` ON `Images`.`id` = `Images->PostImages`.`ImageId`) ON `Posts`.`id` = `Images->PostImages`.`PostId` LEFT OUTER JOIN `Questions` AS `Question` ON `Posts`.`QuestionId` = `Question`.`id` LEFT OUTER JOIN ( `PostLikes` AS `Likes->PostLikes` INNER JOIN `Likes` AS `Likes` ON `Likes`.`id` = `Likes->PostLikes`.`LikeId`) ON `Posts`.`id` = `Likes->PostLikes`.`PostId` LEFT OUTER JOIN `Videos` AS `Video` ON `Posts`.`VideoId` = `Video`.`id` LEFT OUTER JOIN ( `PostsTags` AS `Tags->PostsTags` INNER JOIN `Tags` AS `Tags` ON `Tags`.`id` = `Tags->PostsTags`.`TagId`) ON `Posts`.`id` = `Tags->PostsTags`.`PostId` ORDER BY `Posts`.`updatedAt` DESC;"},"sql":"SELECT `Posts`.*, `Comments`.`id` AS `Comments.id`, `Comments`.`type` AS `Comments.type`, `Comments`.`comment` AS `Comments.comment`, `Comments`.`createdAt` AS `Comments.createdAt`, `Comments`.`updatedAt` AS `Comments.updatedAt`, `Comments`.`PostId` AS `Comments.PostId`, `Comments`.`UserId` AS `Comments.UserId`, `Comments->PostComments`.`createdAt` AS `Comments.PostComments.createdAt`, `Comments->PostComments`.`updatedAt` AS `Comments.PostComments.updatedAt`, `Comments->PostComments`.`PostId` AS `Comments.PostComments.PostId`, `Comments->PostComments`.`CommentId` AS `Comments.PostComments.CommentId`, `Comments->User`.`id` AS `Comments.User.id`, `Comments->User`.`first` AS `Comments.User.first`, `Comments->User`.`last` AS `Comments.User.last`, `Comments->User`.`phone` AS `Comments.User.phone`, `Comments->User`.`pic` AS `Comments.User.pic`, `Comments->Likes`.`id` AS `Comments.Likes.id`, `Comments->Likes`.`createdAt` AS `Comments.Likes.createdAt`, `Comments->Likes`.`updatedAt` AS `Comments.Likes.updatedAt`, `Comments->Likes`.`UserId` AS `Comments.Likes.UserId`, `Comments->Likes`.`PostId` AS `Comments.Likes.PostId`, `Comments->Likes`.`CommentId` AS `Comments.Likes.CommentId`, `Comments->Likes->CommentLikes`.`createdAt` AS `Comments.Likes.CommentLikes.createdAt`, `Comments->Likes->CommentLikes`.`updatedAt` AS `Comments.Likes.CommentLikes.updatedAt`, `Comments->Likes->CommentLikes`.`CommentId` AS `Comments.Likes.CommentLikes.CommentId`, `Comments->Likes->CommentLikes`.`LikeId` AS `Comments.Likes.CommentLikes.LikeId`, `User`.`id` AS `User.id`, `User`.`first` AS `User.first`, `User`.`last` AS `User.last`, `User`.`phone` AS `User.phone`, `User`.`pic` AS `User.pic`, `AdOption`.`id` AS `AdOption.id`, `AdOption`.`postIsAd` AS `AdOption.postIsAd`, `AdOption`.`cpc` AS `AdOption.cpc`, `AdOption`.`cpv` AS `AdOption.cpv`, `AdOption`.`clickURL` AS `AdOption.clickURL`, `AdOption`.`createdAt` AS `AdOption.createdAt`, `AdOption`.`updatedAt` AS `AdOption.updatedAt`, `AdOption`.`UserId` AS `AdOption.UserId`, `Images`.`id` AS `Images.id`, `Images`.`path` AS `Images.path`, `Images`.`createdAt` AS `Images.createdAt`, `Images`.`updatedAt` AS `Images.updatedAt`, `Images`.`UserId` AS `Images.UserId`, `Images`.`PostId` AS `Images.PostId`, `Images->PostImages`.`createdAt` AS `Images.PostImages.createdAt`, `Images->PostImages`.`updatedAt` AS `Images.PostImages.updatedAt`, `Images->PostImages`.`PostId` AS `Images.PostImages.PostId`, `Images->PostImages`.`ImageId` AS `Images.PostImages.ImageId`, `Question`.`id` AS `Question.id`, `Question`.`question` AS `Question.question`, `Question`.`description` AS `Question.description`, `Question`.`createdAt` AS `Question.createdAt`, `Question`.`updatedAt` AS `Question.updatedAt`, `Question`.`UserId` AS `Question.UserId`, `Likes`.`id` AS `Likes.id`, `Likes`.`createdAt` AS `Likes.createdAt`, `Likes`.`updatedAt` AS `Likes.updatedAt`, `Likes`.`UserId` AS `Likes.UserId`, `Likes`.`PostId` AS `Likes.PostId`, `Likes`.`CommentId` AS `Likes.CommentId`, `Likes->PostLikes`.`createdAt` AS `Likes.PostLikes.createdAt`, `Likes->PostLikes`.`updatedAt` AS `Likes.PostLikes.updatedAt`, `Likes->PostLikes`.`PostId` AS `Likes.PostLikes.PostId`, `Likes->PostLikes`.`LikeId` AS `Likes.PostLikes.LikeId`, `Video`.`id` AS `Video.id`, `Video`.`title` AS `Video.title`, `Video`.`description` AS `Video.description`, `Video`.`path` AS `Video.path`, `Video`.`createdAt` AS `Video.createdAt`, `Video`.`updatedAt` AS `Video.updatedAt`, `Video`.`UserId` AS `Video.UserId`, `Tags`.`id` AS `Tags.id`, `Tags`.`name` AS `Tags.name`, `Tags`.`icon` AS `Tags.icon`, `Tags`.`UserId` AS `Tags.UserId`, `Tags`.`createdAt` AS `Tags.createdAt`, `Tags`.`updatedAt` AS `Tags.updatedAt`, `Tags->PostsTags`.`createdAt` AS `Tags.PostsTags.createdAt`, `Tags->PostsTags`.`updatedAt` AS `Tags.PostsTags.updatedAt`, `Tags->PostsTags`.`PostId` AS `Tags.PostsTags.PostId`, `Tags->PostsTags`.`TagId` AS `Tags.PostsTags.TagId` FROM (SELECT `Posts`.`id`, `Posts`.`type`, `Posts`.`content`, `Posts`.`public`, `Posts`.`createdAt`, `Posts`.`updatedAt`, `Posts`.`UserId`, `Posts`.`QuestionId`, `Posts`.`AdOptionId`, `Posts`.`VideoId` FROM `Posts` AS `Posts` WHERE (`Posts`.`UserId` IN (1) OR `Posts`.`AdOptionId` IS NOT NULL OR (`Posts`.`public` = true AND `Tags`.`id` IN (1))) ORDER BY `Posts`.`updatedAt` DESC LIMIT 0, 10) AS `Posts` LEFT OUTER JOIN ( `PostComments` AS `Comments->PostComments` INNER JOIN `Comments` AS `Comments` ON `Comments`.`id` = `Comments->PostComments`.`CommentId`) ON `Posts`.`id` = `Comments->PostComments`.`PostId` LEFT OUTER JOIN `Users` AS `Comments->User` ON `Comments`.`UserId` = `Comments->User`.`id` LEFT OUTER JOIN ( `CommentLikes` AS `Comments->Likes->CommentLikes` INNER JOIN `Likes` AS `Comments->Likes` ON `Comments->Likes`.`id` = `Comments->Likes->CommentLikes`.`LikeId`) ON `Comments`.`id` = `Comments->Likes->CommentLikes`.`CommentId` LEFT OUTER JOIN `Users` AS `User` ON `Posts`.`UserId` = `User`.`id` LEFT OUTER JOIN `AdOptions` AS `AdOption` ON `Posts`.`AdOptionId` = `AdOption`.`id` LEFT OUTER JOIN ( `PostImages` AS `Images->PostImages` INNER JOIN `Images` AS `Images` ON `Images`.`id` = `Images->PostImages`.`ImageId`) ON `Posts`.`id` = `Images->PostImages`.`PostId` LEFT OUTER JOIN `Questions` AS `Question` ON `Posts`.`QuestionId` = `Question`.`id` LEFT OUTER JOIN ( `PostLikes` AS `Likes->PostLikes` INNER JOIN `Likes` AS `Likes` ON `Likes`.`id` = `Likes->PostLikes`.`LikeId`) ON `Posts`.`id` = `Likes->PostLikes`.`PostId` LEFT OUTER JOIN `Videos` AS `Video` ON `Posts`.`VideoId` = `Video`.`id` LEFT OUTER JOIN ( `PostsTags` AS `Tags->PostsTags` INNER JOIN `Tags` AS `Tags` ON `Tags`.`id` = `Tags->PostsTags`.`TagId`) ON `Posts`.`id` = `Tags->PostsTags`.`PostId` ORDER BY `Posts`.`updatedAt` DESC;","success":true}

Why I am getting the error Unknown column 'Tags.id' in 'where clause' ?

Please help. I hope I have provided enough information and if not, please let me kow if you'd like to know anything else? Thank you!

**Comment by deepak057** [comment]
Hi Guys, any comments please?

**Comment by mubaidr** [comment]
Use `include` within `where` to filter out items based on child. like this: 

```js
include: [
        {
          model: Team,
          as: 'HomeTeam',
          where: {
            name: {
              [Op.like]: 'search'
            }
          }
        }
```

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
