### ISSUE TITLE
MSSQL newid() default

### ISSUE THREAD

**Issue by mirshahreza** [sequelize/sequelize#10317]
When a column is guid by default value of newid() sequelize generates insert sql statement included the column so sql server raises an error.

model:
            {
                "id": {
                    "type": "UNIQUEIDENTIFIER", "allowNull": false, "defaultValue": "(newid())",
                    "primaryKey": true, "autoIncrement": false
                },
                "role_name": {
                    "type": "NVARCHAR", "allowNull": false, "defaultValue": null,
                    "primaryKey": false, "autoIncrement": false
                }
            }

result:
INSERT INTO [roles] ([id],[role_name]) OUTPUT INSERTED.* VALUES (N'(newid())',N'managers')

error:
Unhandled rejection SequelizeDatabaseError: Conversion failed when converting from a character string to uniqueidentifier

by the way 
1- I get the model from sequelize by define method.
2- the version of tedios is 4.1.0
3- the version of sequelize is 4.42.0

**Comment by sushantdhiman** [comment]
Can you pass `defaultValue: sequelize.literal('newid()')`, I think by default we are trying to convert `newid` to string
