### ISSUE TITLE
Order by sequelize.fn for underscored columns and left joins

### ISSUE THREAD

**Issue by pyephyomaung** [sequelize/sequelize#10315]
Hello, I have the models equivalent to the following
```
const TableA = sequelize.define('TableA', {id: Sequelize.UUID, somethingName: Sequelize.STRING}),
      TableB = sequelize.define('TableB', {id: Sequelize.UUID, title: Sequelize.STRING});
TableA.hasMany(TableB, {as: 'Bs'});
TableA.addScope('includeB', {include: [{model: TableB}]});
```

Then I do, something like
```
return models.TableA.scope('includeB').findAll({
  where: {
    somethingName: {[Op.like]: '%bla%abcd%'}
  },
  limit: 20,
  offset: 100,
  order: [
    [sequelize.fn('similarity', sequelize.col('somethingName'), 'bla'), 'DESC']
  ]
})
```

it generates the query like this:
```
SELECT "TableA".*
    ,"TableB"."title" AS "TableB.title"
  ,"TableB"."id" AS "TableB.id"
  ,"TableB"."table_a_id" AS "TableB.tableAId"
FROM (
    SELECT "TableA"."id"
    FROM "table_as" AS "TableA"
    WHERE "table_as"."something_name" ILIKE '%bla%abcd%'
    ORDER BY similarity("somethingName", 'bla') DESC LIMIT 21 OFFSET 100
    ) AS "TableA"
LEFT JOIN "table_bs" AS "TableB" ON "TableA"."id" = "TableB"."table_a_id"
ORDER BY similarity("somethingName", 'bla') DESC;
```

When underscored column names are used in postgres, the `ORDER BY` clause inside the subquery is not working.

**Comment by sushantdhiman** [comment]
Follow the issue template

----------------------------------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
