### ISSUE TITLE
Plain, individualHooks and returning cause update to crash

### ISSUE THREAD

**Issue by perusopersonale** [sequelize/sequelize#10313]
Update with options { plain: true and individualHooks: true, returning: true } cause error

```js
  Models.update({ foo: "bar"}, { plain: true, individualHooks: true, returning: true })
```

## What do you expect to happen?
Individual hooks called and value returned

## What is actually happening?
An error is raised

I've done some investigation: 
in https://github.com/sequelize/sequelize/blob/2a4e1113a3bea957998ea7967eef66718e4e5eb4/lib/dialects/abstract/query.js#L285
if plain options set return the element instead of an array

in https://github.com/sequelize/sequelize/blob/2a4e1113a3bea957998ea7967eef66718e4e5eb4/lib/model.js#L2999
if options.returning is is assigned to instances but is only a single record

then in
https://github.com/sequelize/sequelize/blob/2a4e1113a3bea957998ea7967eef66718e4e5eb4/lib/model.js#L3007
Promise.map take instances that is not an array and it raise an error

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by Moses-Bassey** [comment]
> Update with options { plain: true and individualHooks: true, returning: true } cause error
> 
> ```js
>   Models.update({ foo: "bar"}, { plain: true, individualHooks: true, returning: true })
> ```
> 
> ## What do you expect to happen?
> Individual hooks called and value returned
> 
> ## What is actually happening?
> An error is raised
> 
> I've done some investigation:
> in
> 
> https://github.com/sequelize/sequelize/blob/2a4e1113a3bea957998ea7967eef66718e4e5eb4/lib/dialects/abstract/query.js#L285
> 
> 
> if plain options set return the element instead of an array
> in
> 
> https://github.com/sequelize/sequelize/blob/2a4e1113a3bea957998ea7967eef66718e4e5eb4/lib/model.js#L2999
> 
> 
> if options.returning is is assigned to instances but is only a single record
> then in
> https://github.com/sequelize/sequelize/blob/2a4e1113a3bea957998ea7967eef66718e4e5eb4/lib/model.js#L3007
> 
> 
> Promise.map take instances that is not an array and it raise an error

Thanks for the piece of information. I had a similar challenge using individualHooks and the solution in my case was to remove Plain and Returning from the query
