### ISSUE TITLE
postgres: ARRAY(UUID)

### ISSUE THREAD

**Issue by vosho** [sequelize/sequelize#10321]
I have a table Team with a field members:
**members** field is array of uuid.
Model defined as : 
```javascript
members: ARRAY(UUID),
```
Db DLL : 
```
"members" uuid[]
```
I am trying to insert data 
```json
{
    "team_name": "a",
    "members": [
        "8f0f86cc-88cd-4e0b-8420-e51536053e52", 
        "8f0f86cc-88cd-4e0b-8420-e51536053e52"
    ]
}
```

But I got error as following:
```java
column "members" is of type uuid[] but expression is of type text[]
```

Could anyone give me some hints?

Thanks

**Comment by sushantdhiman** [comment]
We dont support `ARRAY(UUID)` yet https://github.com/sequelize/sequelize/blob/master/docs/data-types.md

Will accept PR with this addition

**Comment by vaulstein** [comment]
Still no support for ARRAY(UUID)?

**Comment by WikiRik** [comment]
Support for ARRAY(UUID) in Postgres is part of v7. Alpha versions are already out, see [@sequelize/core](https://www.npmjs.com/package/@sequelize/core)
