### ISSUE TITLE
Getting wrong order of numbers when saving them as a STRING data type

### ISSUE THREAD

**Issue by RahmatAliMalik5** [sequelize/sequelize#10325]
## What are you doing?
I would like to fetch the numbers form a PostgreSQL database in descending order in NodeJS application. I am saving those numbers as String because the numbers can be very big as BIGINT can't be able to deal with it. The problem is that, the fetched values are not in a right order. Because, String values compared in a different logic than the real number, I am getting `13` smaller than `9'. The Code I am using is as follows:

My Model:
```
var log = sequelize.define('log', {
        id: {
            type: type.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        statusCode: type.INTEGER,
        status: type.STRING,
        message: type.TEXT,
        lastRecordId: type.STRING,
        lastRecordTime: type.DATE
    });
};
```

My query:

```
LoggerModel
.findAll({
    order: [ [ 'lastRecordId', 'DESC' ]],
})
```

## What do you expect to happen?
I want to fetch the numbers in the right descending order.

2019010139996
2019010120000
        209922311

## What is actually happening?
I am getting wrong number orders. Like in the snapshot below:

"209922311"
"2019010139996"
"2019010120000"

**Comment by sushantdhiman** [comment]
You are trying to order string as interger, without casting you will get incorrect results.

- https://wiki.postgresql.org/wiki/FAQ#Why_do_my_strings_sort_incorrectly.3F
- https://stackoverflow.com/questions/8502505/order-varchar-string-as-numeric

**Comment by RahmatAliMalik5** [comment]
After a lot of searches, I found a solution specific to sequelizeJS. What worked for is as follows:

```

        LoggerModel
            .findAll({
                order: [
                    [ sequelize.cast(sequelize.col('lastRecordId'), 'BIGINT') , 'DESC' ]
                ]
            })
            .then((logs) => { /// });
```
Thanks a lot for the comments from the participants.

**Comment by ezze** [comment]
How do I sort by JSON property of included model?

It doesn't work.

```
order: [
    [Product, Sequelize.cast(Sequelize.literal('metadata->>\'orbitNumber\'', 'INTEGER')), sortDirection]
]
```

The generated SQL part is the following:

```sql
ORDER BY "product".CAST(metadata->>'orbitNumber' AS ) ASC
```

that leads to a syntax error obviously.

**Comment by ezze** [comment]
For anyone interested here is a [workaround](https://github.com/sequelize/sequelize/issues/4553#issuecomment-569133647) for my example above.

**Comment by dhirendrathakulla** [comment]
How can we achieve for many varchar columns? 
Something like that
` order: [
              [
                Sequelize.literal(
                  Sequelize.cast(Sequelize.col("month"), "INT"),
                  Sequelize.cast(Sequelize.col("week"), "INT")
                ),
                "ASC",
              ],`
