### ISSUE TITLE
Error in Tutorial -> Model usage -> Data retrieval / Finders 

### ISSUE THREAD

**Issue by a-kon** [sequelize/sequelize#10328]
Greetings!

## What are you doing?
Read the docs on http://docs.sequelizejs.com/manual/tutorial/models-usage.html

## What do you expect to happen?
Read actual example

## What is actually happening?
It's not actual

The example on http://docs.sequelizejs.com/manual/tutorial/models-usage.html still shows `Project.findById`, but in markdown file `sequelize/docs/models-usage.md` it's `Project.findByPk` and in http://docs.sequelizejs.com/class/lib/model.js~Model.html there is also no method `findById`.

Fix that, please.

![image](https://user-images.githubusercontent.com/37555845/50738110-96649a00-11e1-11e9-9a55-6bb96a1befeb.png)

**Comment by mubaidr** [comment]
I believe tutorial and github repo docs are updated to match v5 (not released yet) while the documentation is for v4.

**Comment by sushantdhiman** [comment]
Fixed in master https://github.com/sequelize/sequelize/blob/master/docs/models-usage.md#find---search-for-one-specific-element-in-the-database

Docs are still pointing to v4, will be released soon
