### ISSUE TITLE
can't use partial indexes on tables with soft delete activated

### ISSUE THREAD

**Issue by AiDirex** [sequelize/sequelize#10330]
## What are you doing?
I am using sequelize with soft delete feature, when I query models with paranoid activated, the generated SQL add this where expression `("Entity"."deletedAt" > '2019-01-07 11:42:25.770 +00:00' OR "Entity"."deletedAt" IS NULL)` to filter soft deleted records. However, I use Postgres [partial indexes](https://www.postgresql.org/docs/10/indexes-partial.html) to create an index on records which are not soft deleted yet.
```
CREATE INDEX not_deleted_rec_index ON "Entities" (cols...)
    WHERE "deletedAt is null;
```
But your SQL has this `"Entity"."deletedAt" > '2019-01-07 11:42:25.770 +00:00'` part which blocks the postgres to use the created index.

## What do you expect to happen?
I wanted to know that is there any specific reason for this behavior, or can it be fixed so we can use partial indexes.

__Dialect:__  postgres
__Dialect version:__ XXX
__Database version:__ PostgreSQL 10.6 (Ubuntu 10.6-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609, 64-bit
__Sequelize version:__ 4.41.0
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
This has been discussed before and main reason why we started with v5. In v3 and now v5-beta as well, we dont compare against date values. We now just check for `IS NULL`

https://github.com/sequelize/sequelize/issues/8496
