### ISSUE TITLE
sequelize findAll null

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#10333]
Take a look at the query below.
If no records are found, you have to do
`if(!disp_rx.length)`

shouldn't this work as well?
`if(!disp_rx)`

```
		dispensary.findAll({
			where: {
				processed: 'Y',
				location: null
			},
			attributes: [
				'id',
				'latitude',
				'longitude'
			],
			limit: [index, rows]
		}).then(disp_rx => {
                        // this doesn't work
                        if(!disp_rx)

                        // you need to disp_rx.length
			if(!disp_rx.length) {
				console.log('DONE - updating dispensary Geo points')
				return
			}
              })
```

**Comment by mubaidr** [comment]
This is expected behavior, this query will return an array (whether or not contains elements to maintain a consistent behavior)

**Comment by knoxcard** [comment]
Right, just doesn't seem right to me.  If the collection is empty, for some reason I'd expect it to be falsy.  I'll close ticket.
