### ISSUE TITLE
model does not contain association after doing model.create[model]()

### ISSUE THREAD

**Issue by toymachiner62** [sequelize/sequelize#10336]
model does not contain association after doing `model.create[model]()`

```js
db.organization.findOne({
      where: {
        id: req.params.id
      },
      include: ['tags']
    })
      .then(org => {
        myOrg = org

        let promises = []
        promises.push(myOrg.createTag({ name: tag }))
        return Promise.all(promises)
     .then(tags => {
        console.log('tags = ', tags) <-- Contains my new tag
        console.log('myOrg.get() = ', myOrg.get()) <-- Does NOT contain my new tag. Why not??
        return res.status(HttpStatus.OK).send(myOrg)
      })
```

## What do you expect to happen?
I would expect `myOrg` to contain the new `tag` object and it doesn't.

## What is actually happening?
`myOrg` doesn't contain the new tag object. If i subsequently do a `findOne()` query i see that the tag actually does exist in the db

__Dialect:__ sqlite
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.41.2
__Tested with latest release:__ No (If yes, specify that version)

**Comment by mubaidr** [comment]
This is not related to issue but please can you point me to documentation of `model.create[model]()`?

**Comment by toymachiner62** [comment]
@mubaidr I can not seem to find where I figured that out. Most likely from Stackoverflow b/c there's so much undocumented magic with sequelize IMO.

**Comment by sushantdhiman** [comment]
@mubaidr Please read new docs which are not live yet https://github.com/sequelize/sequelize/blob/master/docs/associations.md they should be more clear

@toymachiner62 You need to do reload on `myOrg`, sequelize wont update parent object when `create` is called. If you expect parent object to be changed after any operation you should call `reload` on that to get most current data

**Comment by toymachiner62** [comment]
There is nothing in the new docs link you pointed me to that mentions anything about `reload()`.

This should be documented somewhere with examples. The reference page http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-reload is worthless b/c it doesn't talk about associated objects and good luck on someone actually finding this in the first place.
