### ISSUE TITLE
Update documentation for updating model associations b/c it just flat out doesn't work

### ISSUE THREAD

**Issue by toymachiner62** [sequelize/sequelize#10334]
Please update this documentation on this page http://docs.sequelizejs.com/class/lib/associations/base.js~Association.html#instance-member-source b/c it flat out doesn't work.

This documentation is so vague and doesn't provide any real examples and i'm running out of hair to rip out of my head.

I've got a fairly simple case `hasMany` setup here https://stackoverflow.com/questions/54082222/sequelize-model-association-not-setting-as-expected and these magical `set[Model]` methods do NOT work as the documentation says they should.

![image](https://user-images.githubusercontent.com/485782/50852928-c1f89900-1335-11e9-9b68-131e5bf641f4.png)

**Comment by sushantdhiman** [comment]
It is update in master no deployed yet
