### ISSUE TITLE
PgSql : Query generator crashing for JSON column query.

### ISSUE THREAD

**Issue by pankajthadani** [sequelize/sequelize#10337]
## What are you doing?

I am using the sequelize js library on a postgres db. I need to retrieve the raw query generated using the attributes passed . I need to query players database and find the players by their zip code location.
-------------------------------------------------------------
Table schema is as follows
id |    name                | address
------------------------------------------------
1  |{"first": "Sachin"}|{"home":[{"street":"", "zip":"", "city":""}]}

If the same queryObject is used in the findAll method, query generated is generated correctly, but failing for dialect querygeneration.

```js
let subquery =  serviceModel.sequelize.dialect.QueryGenerator.selectQuery("Location" ,queryObject).slice(0,-1);
```

## What do you expect to happen?
The raw query should be generated 

## What is actually happening?
Gives an invalid value error

_Output, either JSON or SQL_
{"_logLevel":"error","msg":"Error occurred in  :: LocationController :: summary() :: Error: Invalid value { home: [ { zip: '75418-4' } ] }\n    at Object.escape (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/sql-string.js:66:11)\n    at Object.escape (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:936:22)\n    at Object._whereParseSingleValueObject (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2432:41)\n    at Object.whereItemQuery (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2134:21)\n    at value.map.item (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2220:38)\n    at Array.map (<anonymous>)\n    at Object._whereBind (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2220:21)\n    at Object.whereItemQuery (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2114:19)\n    at Utils.getComplexKeys.forEach.prop (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1997:25)\n    at Array.forEach (<anonymous>)\n    at Object.whereItemsQuery (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1995:35)\n    at Object.getWhereConditions (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2459:19)\n    at Object.selectQuery (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1143:28)\n    at Function.<anonymous> (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/services/common/dataService.ts:548:69)\n    at Generator.next (<anonymous>)\n    at /Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/common/dataService.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/common/dataService.js:3:12)\n    at Function.getAggregatedResults (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/common/dataService.js:485:16)\n    at Function.<anonymous> (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/services/observation/observationService.ts:60:55)\n    at Generator.next (<anonymous>)\n    at /Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/observation/observationService.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/observation/observationService.js:3:12)\n at Function.getSummary (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/observation/observationService.js:25:16)\n    at /Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/services/observation/observationController.ts:261:47\n    at Generator.next (<anonymous>)\n at /Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/observation/observationController.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/observation/observationController.js:3:12)\n    at summary (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/.build/services/observation/observationController.js:215:16)\n    at handler (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/serverless-offline/src/index.js:866:25)\n    at Object.internals.handler (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/handler.js:96:36)\n    at request._protect.run (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/handler.js:30:23)\n    at module.exports.internals.Protect.internals.Protect.run (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/protect.js:64:5)\n    at exports.execute (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/handler.js:24:22)\n    at each (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/items/lib/index.js:36:13)\n    at done (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/items/lib/index.js:28:25)\n    at internals.Auth.payload (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/auth.js:223:16)\n    at each (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/items/lib/index.js:36:13)\n    at done (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/items/lib/index.js:28:25)\n    at onParsed (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/route.js:402:20)\n    at Subtext.parse (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hapi/lib/route.js:423:20)\n    at next (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/subtext/lib/index.js:45:26)\n    at Wreck.read (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/subtext/lib/index.js:242:16)\n    at finish (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/subtext/node_modules/wreck/lib/index.js:374:20)\n    at wrapped (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/hoek/lib/index.js:879:20)\n    at module.exports.internals.Recorder.onReaderFinish (/Users/pthadani/Documents/SourceTreeRoot/Cricket/CPH Services/node_modules/subtext/node_modules/wreck/lib/index.js:449:16)\n    at Object.onceWrapper (events.js:273:13)\n    at module.exports.internals.Recorder.emit (events.js:187:15)\n    at module.exports.internals.Recorder.EventEmitter.emit (domain.js:460:23)\nat finishMaybe (_stream_writable.js:641:14)\n    at endWritable (_stream_writable.js:649:3)\n    at module.exports.internals.Recorder.Writable.end (_stream_writable.js:589:5)\n    at IncomingMessage.onend (_stream_readable.js:625:10)\n    at Object.onceWrapper (events.js:273:13)\n    at IncomingMessage.emit (events.js:187:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:442:20)\n    at endReadableNT (_stream_readable.js:1081:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","_tags":["log","error"]}

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version: 9.6.8
__Sequelize version:4.42.0
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
You are passing something incorrect to `selectQuery`, ` { home: [ { zip: '75418-4' } ] }`

Please show what data are your passing
