### ISSUE TITLE
Sync({alter: true}) does not work.

### ISSUE THREAD

**Issue by Hazarapet** [sequelize/sequelize#10345]
I had just a simple code, when I've created a model, synced it, then added a field. After calling sync({alter: true}) it does not work. column is not added into the database.

I'm using mysql 8.0.13
sequelize: 4.42.0

**Comment by papb** [comment]
Can you add the code you mentioned?

**Comment by Hazarapet** [comment]
It's just a simple code.
`module.exports = (sequelize) => {
  return sequelize.define('user', {
    email: Sequelize.STRING,
    name: Sequelize.STRING,
    surname: Sequelize.STRING
  });
};

...
model.sync();
...
module.exports = (sequelize) => {
  return sequelize.define('user', {
    email: Sequelize.STRING,
    name: Sequelize.STRING,
    surname: Sequelize.STRING,
    birth_date: Sequelize.DATE
  });
};

 model.sync({alter: true})
// after this the table does not change. it remains the same.
`

**Comment by papb** [comment]
I cannot reproduce. Works for me.
