### ISSUE TITLE
Update Validator to fix Regular Expression Denial of Service (ReDoS) on version 3.X

### ISSUE THREAD

**Issue by NerminImamovic** [sequelize/sequelize#10348]
## What are you doing?

package.json

```js
  "dependencies": {
     "validator": "^5.2.0",
  },
```

## What do you expect to happen?
I want to upgrade version of validator to be `10.9.0`, that it is possible to solve vulnerability reported by Snyk tool.

## What is actually happening?

Snyk tool reports vulnerability `Regular Expression Denial of Service (ReDoS)` on dependency validator (Low Severity).

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Sequelize version:__ 3.34.0
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
That is from v3 right, we don't support that version any longer.

If you can submit a pull request with dependency update and fixing any breaking changes in `validator`, I'll release a new v3 version

**Comment by NerminImamovic** [comment]
Thank you. I will make PR with changes.
