### ISSUE TITLE
SOLVED: JSON_VALUE - requires unncessary stringify then parse

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#10340]
## What are you doing?

I have a JSON column `blob` in my `users` model and I want to access the attribute `blob.full_name`.
```
[app.model.sequelize.literal(`JSON_VALUE(\`blob\`, '$.full_name')`), 'full_name']
```

The raw SQL generated is correct, I even get this output in MariaDB.

```
Raw SQL  (logging: true): `Executing (default): SELECT `id`, `email`, JSON_VALUE(`blob`, '$.full_name') AS `full_name` FROM `users` AS `users` ORDER BY RAND() LIMIT 1;
```

```
id              email                                       full_name
----          ----------                                  ------------
"349"	"fran.miller14@gmail.com"	"Fran Miller"

```

```
var attributes = [],
	having = []
attributes.push('id')
attributes.push('email')
attributes.push([app.model.sequelize.literal(`JSON_VALUE(\`blob\`, '$.full_name')`), 'full_name'])
app.model.users.findOne({
	attributes: attributes,
	order: [app.model.sequelize.literal('RAND()')]
}).then(user => {
	console.log(Object.keys(user.dataValues))
	// console.log(Object.keys(user))
	console.log('user.id: ' + user.id)
	console.log('user.email: ' + user.email)
	console.log('user.full_name: ' + user.full_name)
	var range = {
		min: 50,
		max: 150
	},
	out = {
		name: user.full_name,
		amount: (Math.random() * (range.max - range.min + 1) + range.min).toFixed(2)
	}
	console.log('out: ' + JSON.stringify(out, null, 4))
	res.json(out)
})
```

## What do you expect to happen?
I want the full_name attribute to return its value.

## What is actually happening?
full_name is always undefined

**Comment by sushantdhiman** [comment]
Wat, follow the template please :)

**Comment by knoxcard** [comment]
Updated

**Comment by sushantdhiman** [comment]
Have you tried `sequelize.json` instead ?

**Comment by knoxcard** [comment]
Ahh great point...I was super excited...but then same output :-(

```attributes.push([app.model.sequelize.json(`JSON_VALUE(\`blob\`, '$.full_name')`), 'full_name'])```

**Comment by knoxcard** [comment]
OMG I solved it...

var user = JSON.parse(JSON.stringify(user))

**Comment by knoxcard** [comment]
Cleaner code for future reference

```
		var attributes = []
		attributes.push([app.model.sequelize.fn('JSON_VALUE', app.model.sequelize.col('blob'), '$.full_name'), 'full_name'])
		app.model.users.findOne({
			attributes: attributes,
			order: [app.model.sequelize.literal('RAND()')]
		}).then(user => {
			var user = JSON.parse(JSON.stringify(user))
			var range = {
				min: 50,
				max: 150
			},
			out = {
				name: user.full_name,
				amount: (Math.random() * (range.max - range.min + 1) + range.min).toFixed(2)
			}
			res.json(out)
		})
```

**Comment by knoxcard** [comment]
@sushantdhiman - see what I mean?

**Comment by contra** [comment]
@knoxcard 	You can use `raw: true` in the query, or do `user.toJSON()` to get a pure JS object

**Comment by knoxcard** [comment]
I've used `raw: true` in the past but removed all instances within my platform.  It causes too many problems, i'd rather stick with Sequelize 100%.

**Comment by knoxcard** [comment]
@janmeier - YES!  Thank you!  That is a clean solution! 

```
    app.model.users.findOne({
      where: where,
      attributes: attributes,
      order: [app.model.sequelize.literal('RAND()')],
      having: app.model.sequelize.literal(`full_name_exists = 1`)
    }).then(user => {
      var first_name,
        last_name,
        full_name = user.get('full_name')
      // console.log(full_name.split(' ').length)
      if(full_name.split(' ').length == 2) {
        first_name = full_name.split(' ')[0]
        last_name =  full_name.split(' ')[1].substr(0, 1)
      }
      else {
        last_name = 'R'
      }
      var hidden_name = full_name.split(' ')[0] + ' ' + last_name + '.',
        range = {
          min: 50,
          max: 150
        }
      res.json({
        name: hidden_name,
        amount: (Math.random() * (range.max - range.min + 1) + range.min).toFixed(2)
      })
    })
```

CASE CLOSED

**Comment by rhuyck** [comment]
Thank you so much for posting the solution that you found

**Comment by rhuyck** [comment]
> You can only access values using `.value` for attributes defined in the schema. So if you have a `fullName` defined in the schema you can access `user.fullName`. For all other attributes you need to use `user.get()`. Attributes in the schema are defined as getters using `defineProperty`
> 
> [sequelize/lib/model.js](https://github.com/sequelize/sequelize/blob/0f0255eed3d88efb179a47fe7763b7309517428a/lib/model.js#L1210)
> 
> Line 1210 in [0f0255e](/sequelize/sequelize/commit/0f0255eed3d88efb179a47fe7763b7309517428a)
> 
>  Object.defineProperty(this.prototype, key, attributeManipulation[key]); 
> `user.get('full_name')` should work

<33333
