### ISSUE TITLE
Sequelize hasMany include to return 1 (object rather than array)

### ISSUE THREAD

**Issue by noonesstudios** [sequelize/sequelize#10349]
#Feature Request#

Model Definitions:

```
sequelize.define('Parent', {name: DataTypes.STRING})
sequelize.define('Child', {name: DataTypes.STRING})
```
Associations:

```
Parent.hasMany(Child, {
  foreignKey: 'parent_id',
  as: 'child'
})

Child.belongsTo(Parent)
```
Include function:

```
Parent.findByPk(pk, {
  include: [{
    model: Child,
    as: 'child',
    where: {
      name: 'benny'
    }
  }]
})
```
What it returns (usual behavior):

```
{
  "id": 1,
  "name": "parent name",
  "child": [
    {
      "id": 2
      "name": "benny",
      "parent_id": 1
    }
  ]
}
```
What I wish it to return (I do not see any support or mention in docs)

```
{
  "id": 1,
  "name": "parent name",
  "child": {
    "id": 2
    "name": "benny",
    "parent_id": 1
  }
}
```
Difference is Child is configured to return as object

Where do I think this belongs to:

```
Parent.findByPk(pk, {
  include: [{
    model: Child,
    as: 'child',
    where: {
      name: 'benny'
    },
    single: true || false // false unless specified true
  }]
})

```

__Dialect:__ mysql
__Dialect version:__ 1.4.2
__Database version:__ 5.7.23 
__Sequelize version:__ 4.13.5

Is such a modification available / possible?

**Comment by sushantdhiman** [comment]
`hasMany` indicate many children, so officially there wont be any way to return object for that case, but again this can be transformed using lodash or plain js pretty easily

**Comment by yisibl** [comment]
What's confusing here is that the child returned by the `Parent.getChild()` method is an object。
