### ISSUE TITLE
We are trying to migrate the project from Mongoose to Sequelize but couldn't find about some commands for replacing.

### ISSUE THREAD

**Issue by crazycodewriter** [sequelize/sequelize#10357]
We are trying to migrate the project from Mongoose to Sequelize but confused and didn't find in the docs which commands should be replaced with these ones?

```
async GetAllMessages(req, res) {
    const { sender_Id, receiver_Id } = req.params;
    const conversation = await Conversation.findOne({
      $or: [
        {
          $and: [
            { 'participants.senderId': sender_Id },
            { 'participants.receiverId': receiver_Id }
          ]
        },
        {
          $and: [
            { 'participants.senderId': receiver_Id },
            { 'participants.receiverId': sender_Id }
          ]
        }
      ]
    }).select('_id');
...

    Conversation.find(
      {
        $or: [
          {
            participants: {
              $elemMatch: { senderId: sender_Id, receiverId: receiver_Id }
            }
          },
          {
            participants: {
              $elemMatch: { senderId: receiver_Id, receiverId: sender_Id }
            }
          }
        ]
      },
...
 {
              $push: {
                chatList: {
                  $each: [
                    {
                      receiverId: req.params.receiver_Id,
                      msgId: newMessage._id
                    }
                  ],
                  $position: 0
                }
```

talking about these ones from mongoose: $or, $and, $elemMatch,  $push, $each, $position, $set, { $unwind: '$message' }, $pull. What are the commands in Sequelize that will replace these ones?

**Comment by sushantdhiman** [comment]
`$or` and `$and` can be replaced with `Op.or` and `Op.and`.

Other operators are No-SQL based operators which would be converted to joins and similar SQL concepts, if normalized tables are used. Other choice could be to use JSON in SQL based system, but that also require different operators from No-SQL world.

Both of the choices above will require to switch to different SQL concepts as there is no direct alternative to No-SQL operations in SQL realm and vice versa
