### ISSUE TITLE
Pool configuration issue when upgrading to v5 (type validation)

### ISSUE THREAD

**Issue by KhaledSoliman** [sequelize/sequelize#10365]
## What are you doing?

```js
pool: {
        max: process.env.RDS_POOL_MAX_CONNECTIONS,
        min: process.env.RDS_POOL_MIN_CONNECTIONS,
    }
```

## What do you expect to happen?
_The pool to initialize_

## What is actually happening?
_The new pool library validation breaks on different types and environment variables are strings_

__Sequelize version:__ 5.0.0-beta.16

This is not really a major issue (can be fixed by simply parsing env vars to integers), but I expect many users use environment variables to initialize their pool settings, especially in serverless architectures utilizing aws lambda

**Comment by knoxcard** [comment]
Agreed, the values passed (max, min) should be converted from STRING to INT, if the values are indeed STRINGS.

**Comment by sushantdhiman** [comment]
Please submit a PR to https://github.com/sushantdhiman/sequelize-pool

**Comment by knoxcard** [comment]
Here ya go...

https://github.com/sequelize/sequelize-pool/pull/4

**Comment by knoxcard** [comment]
@sushantdhiman
