### ISSUE TITLE
incretment shows sql synax error after query with scope

### ISSUE THREAD

**Issue by 7insummer** [sequelize/sequelize#10367]
## What are you doing?
I just want increment a field after scope query. see codes below:
   Movie.scope('bh').findOne({where:{id:1}}).then(movie=>{
        movie.increment('fav_nums',{by:1})
    })

very simple code ,but will cause sql errors。because the code above will be translated into sqls like this:

UPDATE `movie` SET `fav_nums`=`fav_nums`+ 1,`exclude`='created_at', 'updated_at', 'deleted_at',`updated_at`='2019-01-21 15:59:18' WHERE `id` = 1

Obviously，the sql is wrong.

_Output, either JSON or SQL_

__Dialect:__ mysql 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
