### ISSUE TITLE
dropAllSchemas doesn't work correctly with Jest

### ISSUE THREAD

**Issue by marbuser** [sequelize/sequelize#10371]
## What are you doing?

I'm using the `globalSetup` and `globalTeardown` functions of Jest to setup my database once at the start and then drop all the tables at the end. While the first one works perfectly, the second one doesn't. I'm 100% confident the function is executing due to console.log's as well as me executing other code inside of there previously.

teardown.js
```js
import { db } from '../../src/startup/database';

module.exports = async () => {
  await db.dropAllSchemas({});
};
```

If I can provide any other logs/code, let me know.

## What do you expect to happen?
All tables should be dropped.

## What is actually happening?
The tables are staying in the database and when logging is enabled, no drop statement is made.

__Dialect:__ mysql 8.0.13
__Dialect version:__ N/A
__Database version:__ 8.0.13
__Sequelize version:__ 4.42.0
__Tested with latest release:__ Yes.

**Comment by sushantdhiman** [comment]
> The tables are staying in the database and when logging is enabled, no drop statement is made.

May be add console.log to your `globalTeardown` to see if it is ever called, good idea to add two logs one before one after the `dropAllSchemas` call, just to be sure
