### ISSUE TITLE
INSERT OR REPLACE

### ISSUE THREAD

**Issue by jesslilly** [sequelize/sequelize#1037]
Sqlite supports `INSERT OR REPLACE` syntax.  I'd love to see this in Sequelize.  (Not sure if this syntax is supported by MySQL And Postgres)

I should talk more about the use case.  Right now I am using a `bulkCreate` to insert 100 records at once.  If there is a duplicate in my data or it already exists in the database, the batch will error out.  In my case, I don't care about the duplicate.  It can either be ignored or replaced.

I may try `findOrCreate`, but then I lose the ability to create in bulk.  In sqlite, creating many records at once in a transaction is more efficient than inserting one at a time.

**Comment by JanisE** [comment]
Beware of `INSERT OR REPLACE` if foreign relations are in place – https://github.com/sequelize/sequelize/issues/485#issuecomment-37977970:

> `REPLACE` deletes then inserts if the row  already exists. Because it actually deletes the old row, it will delete  all associated foreign rows if you have an `ON DELETE CASCADE` constraint on the relationship. Generally you'll want to use `INSERT ... ON DUPLICATE KEY UPDATE` instead, which inserts or updates.
