### ISSUE TITLE
Model init options underscored and underscoredAll ignored for field names

### ISSUE THREAD

**Issue by brentjanderson** [sequelize/sequelize#10373]
## What are you doing?

When using the `underscored` option, camelCase field names are not underscored into snake_case. __This is tested against v4.42.0 of Sequelize using Postgres 10.4.__ A full repo demonstrating the issue is here: https://github.com/brentjanderson/sequelize-underscore-not-working (

```js
const Sequelize = require('sequelize')

const sequelize = new Sequelize('postgres', 'postgres', 'postgres', {
  host: 'localhost',
  dialect: 'postgres',
});

const User = sequelize.define('user', {
  userName: Sequelize.STRING,
  birthDay: Sequelize.DATE
}, { underscored: true });

sequelize.sync({ force: true })
  .then(() => User.create({
    userName: 'janedoe',
    birthDay: new Date(1980, 6, 20)
  }))
  .then(() => {
    return sequelize.query('SELECT * FROM users');
  }).then(([resultSet]) => {
    console.log(resultSet);
    process.exit(0);
  });

```

## What do you expect to happen?
When defining a model, the `underscored` option will translate model attributes in camelCase to snake_case. Using postgres 10.4.

```sql
-- The underlying table should look like this:

  Column    |           Type
======================================
 id         | integer
 user_name  | character varying(255) -- Note the snake case
 birth_day  | timestamp with time zone -- Note the snake case
 created_at | timestamp with time zone
 updated_at | timestamp with time zone

```

## What is actually happening?
```sql
-- The underlying actually looks like this

  Column    |           Type
======================================
 id         | integer
 userName   | character varying(255)
 birthDay   | timestamp with time zone
 created_at | timestamp with time zone
 updated_at | timestamp with time zone

```

## Additional notes

[v4.42.0 includes the `underscoredIf` function](https://github.com/sequelize/sequelize/blob/v4.42.0/lib/utils.js#L39-L48), but this function is not called when setting each attribute's `field` property.

**Comment by sushantdhiman** [comment]
This has been fixed in `master`, we can still discuss to port changes to v4 in that PR, if they are non-breaking
