### ISSUE TITLE
 Sequelize is using my URL path in router.get('/urlpath'…) as part of DB SQL query

### ISSUE THREAD

**Issue by savovicmark** [sequelize/sequelize#10379]
## What are you doing?
I am setting two get routes with diferent URL to do almost same thing.

```js
1)studentRouter.get('/', (req, res) =>  {
   studentEntity.findAll({include : [predmetEntity]}).then(students =>{
       res.send(students)
   })
2)studentRouter.get('/best', (req, res)=> {
    studentEntity.findAll().then(result => res.send(result))
})
```

## What do you expect to happen?
In the 1) code it should get me every row from studentEntity table and all associated member of predmetEntity, and in case of code 1) everything is working just fine. The generated sql query is ==>
==============================================================
Executing (default): SELECT `student`.`id`, `student`.`ime`, `student`.`prezime`, `student`.`brIndexa`, `predmets`.`id` AS `predmets.id`, `predmets`.`naziv` AS `predmets.naziv`, `predmets`.`brKredita` AS `predmets.brKredita`, `predmets->polaze`.`ocjena` AS `predmets.polaze.ocjena`, `predmets->polaze`.`studentId` AS `predmets.polaze.studentId`,
`predmets->polaze`.`predmetId` AS `predmets.polaze.predmetId` FROM `students` AS `student` LEFT OUTER JOIN ( `polazes` AS `predmets->polaze` INNER JOIN `predmets` AS `predmets` ON `predmets`.`id` = `predmets->polaze`.`predmetId`) ON `student`.`id` = `predmets->polaze`.`studentId`;
=========================================================
In the case of code 2) the problem comes it should get me every row in studentEntity table but...
## What is actually happening?
...but the generated sql query is not correct===========================
====================================================
Executing (default): SELECT `student`.`id`, `student`.`ime`, `student`.`prezime`, `student`.`brIndexa`, `predmets`.`id` AS `predmets.id`, `predmets`.`naziv` AS `predmets.naziv`, `predmets`.`brKredita` AS `predmets.brKredita`, `predmets->polaze`.`ocjena` AS `predmets.polaze.ocjena`, `predmets->polaze`.`studentId` AS `predmets.polaze.studentId`,
`predmets->polaze`.`predmetId` AS `predmets.polaze.predmetId` FROM `students` AS `student` LEFT OUTER JOIN ( `polazes` AS `predmets->polaze` INNER JOIN `predmets` AS `predmets` ON `predmets`.`id` = `predmets->polaze`.`predmetId`) ON `student`.`id` = `predmets->polaze`.`studentId` WHERE `student`.`id` = 'best';
==============================================================
The problem is obvious in the end of SQL query where it says:  WHERE `student`.`id` = 'best';
So he is using URL from router.get==>studentRouter.get('/best', (req, res)=> {
    studentEntity.findAll().then(result => res.send(result))<== as part of SQL query

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by papb** [comment]
Please include a [MCVE](https://stackoverflow.com/help/mcve).

Please fix the formatting of your issue, see [Markdown Guide](https://www.markdownguide.org/) if you're new to markdown. Use ` ```sql ``` ` where appropriate.

Please include the version of Sequelize that you're using.
