### ISSUE TITLE
Model.bulkCreate calls custom setter twice

### ISSUE THREAD

**Issue by acdibble** [sequelize/sequelize#10390]
## What are you doing?
I am using a model with a custom setter method with bulkCreate to insert data for tests.

```js
const Model = sequelize.define('Model', {
  date: {
    type: DataTypes.STRING(10),
    set(val) {
      // A date parsing function using the Luxon library
      // parses a date of the format 2019-01-26-06:00
      const date = parseDate(val);

      if (date.invalid) {
        throw new Error(`Date is of invalid format: ${date.invalidExplanation}`);
      }
      // sets the date parsed by Luxon in the DB as 01-26-2019
      this.setDataValue('date', date.toFormat('MM-dd-yyyy'));
    },
  },
}, {});

Model.bulkCreate([
  { date: '2019-01-26-06:00' },
]);
// this throws an error:
// Date is of invalid format: the input "01-26-2019" can't be parsed as format yyyy-MM-ddZZ
```

## What do you expect to happen?
I would expect the custom setter to be called once before data is inserted into the database.

## What is actually happening?
The custom setter gets called twice, which causes an error to be thrown the second time.

__Dialect:__ postgres
__Dialect version:__ 7.7.1
__Database version:__ PostgreSQL 10.5 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit
__Sequelize version:__ 4.42.0
__Tested with latest release:__ Yes

**Comment by acdibble** [comment]
Closing this because I'm assuming that I just misunderstood the point of custom setters and that they get called on create, update, or save.

**Comment by frlinw** [comment]
I noticed the same thing for getters but I could workaround it

**Comment by knoxcard** [comment]
Change the datetype for date to be the correct datatype...

```
		date: {
			type: DataTypes.DATE
		}
```

**Comment by acdibble** [comment]
Date would be the incorrect data type. I don't need the timestamp, just the date. I want to store the date in that specific format so I don't have to format it with every query, which is why I chose string and not date or date only.

**Comment by knoxcard** [comment]
Hmmm, what is parseDate? that's not native JS

https://stackoverflow.com/questions/15395703/how-to-use-parsedate

Replace:
`const date = parseDate(val);`

with:
`var d = new Date(val);`
