### ISSUE TITLE
Security: data sanitation

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/sequelize#10393]
I am thinking about XSS and SQL Injections.

## What are you doing?

Using a form on the frontend that would be submitted to the backend, I tried to input the following:

```html
<script>
  console.log('XSS attack!');
</script>
```

## What do you expect to happen?

I was expecting that sequelize would somehow *sanitize* the data to avoid security issues.

## What is actually happening?

Sequelize inserted the data AS IS. I was expecting to see it converted to their html entities or something.

__Dialect:__ mysql2
__Dialect version:__ 1.6.4
__Database version:__ mysql  Ver 15.1 Distrib 10.3.12-MariaDB, for osx10.14 (x86_64) using readline 5.1
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No

**Comment by SimonSchick** [comment]
All sequelize is an ORM, it deals with db injection security just fine, I think it's very much out of scope to force web security into it, that's the consumers responsibility.
What I did is something like this:

```
export function htmlMixin(
  fieldName,
  object,
) {
  object.set = function set(this, value) {
   // Using external sanitiser function
    this.setDataValue(fieldName, sanitize(value));
  };
  return object;
}


// in model definition:
description: htmlMixin('description', {
  type: TEXT,
}),
```

**Comment by SimonSchick** [comment]
Also you mentioned `SQL Injections.` can you please give an example where sequelize is explicitly vulnerable where the consumer is not at fault?

**Comment by aprilmintacpineda** [comment]
I haven't tried out SQL Injection. I tried to look for a place in the documentation that talks about security issues that sequelize DOES and DOES NOT handle. I couldn't find it so I opened a ticket about this concern.

**Comment by eseliger** [comment]
How would sequelize be able to tell if data is provided by a user or from a trusted source? 
Sample:

WYSIWYG editor in the comments section of your blog: user content, should be sanitized.

Backend logic that converts some given data into html which is then stored for later retrieval: generated trustworthy content, should not be sanitized, as you would take it as "trusted" when rendering it into your page.

So I do think this is quite obvious that it cannot be handled unopinionated by an ORM and would not have to be documented. Another example, we also don't tell people to add >= 0 checks for money flow amounts either, which could be a risk for some users, but would also make sense for other use-cases.
Your opinion?

**Comment by aprilmintacpineda** [comment]
> How would sequelize be able to tell if data is provided by a user or from a trusted source?
Sample: 
> 
> WYSIWYG editor in the comments section of your blog: user content, should be sanitized.

Yes that makes sense.

Should the word *obvious* be used for an open-source project that can literally be used by anyone and everyone?

I mean, if I would use it, it's VERY OBVIOUS that you have to install this in order to use this. You still included the `npm install --save sequelize` in the docs. I'm not as smart as you, you know.

**Comment by eseliger** [comment]
Touche. I think it's still a valid argument, don't you agree?

**Comment by aprilmintacpineda** [comment]
I don't.

**Comment by aprilmintacpineda** [comment]
But hey, you're smarter than me, you already enforce what's obvious and what's not obvious. So feel free to decide that.
