### ISSUE TITLE
Add support for specifying attributes in RETURNING (postgres)

### ISSUE THREAD

**Issue by negezor** [sequelize/sequelize#10391]
At the moment, I have 15 columns in the table, and I need to return 3 when updating. But instead, all 15 are returned to me. It would be nice to add an array of the required columns for the 'returning' option.

For example:
```js
Some.update({...}, {
  returning: ['some_name', 'some_value']
});
```

__Dialect:__  postgres
__Database version:__ PostgreSQL 10
__Sequelize version:__ 5.0.0-beta.16

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/11170
