### ISSUE TITLE
Trying to add more than 10 dbs

### ISSUE THREAD

**Issue by tamal-appsbee** [sequelize/sequelize#10398]
Hi,

Getting following error when adding more than 10 db into sequalize: 
`_(node:16935) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit_`

Using following versions:
    "mysql": "^2.13.0",
    "sequelize": "^3.30.4",

Thanks

**Comment by sushantdhiman** [comment]
> 10 db into sequalize

Not sure how you are doing that but Sequelize only supports one database at a time. You are creating more 10 instances perhaps?

If you are adding more than 10 event listeners, which is expected as you are creating 10 instances, this warning can be ignored
