### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by amirzandi** [sequelize/sequelize#10396]
## What are you doing?

```js
// code here
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

Unfortunately, Sequelize put a large performance problem on both API and Database server which leads server to go down.

Sequelize is not compatible for large scale projects.

**Comment by janmeier** [comment]
Please show something concrete - Some numbers, comparison what raw sql, anything that we can try to replicate. http://sscce.org/

Right now your issue is equivalent to saying "nothing works, throw it all out and start from scratch" :D

**Comment by amirzandi** [comment]
@janmeier Actually we are running a game like HQ(live trivia). When the users come to app, home page shows some information to user such as: Rank, Points, Balance and level.

Home page creates 10 Database query that currently we use Sequelize to fetch data from MariaDB database. When 2500 users concurrently come to home page, it takes more than 30seconds to response to requests which is very high.

After I changed Sequelize to MYSQL2 in node.js, it takes about 350 milliseconds at most.

here is our problem!
