### ISSUE TITLE
Like Statement is not working for me in sequelize

### ISSUE THREAD

**Issue by cisdev213** [sequelize/sequelize#10407]
## What are you doing?

```js
/* Code for Pagination */
    let limit = 4;   // number of records per page
    let offset = 0;
    let countallCompanies = 1000; 
    let page = req.body.page;      // 1 by default page number
    let order_by = req.body.order_by;  // id by default
    let order_by_ASC_DESC = req.body.order_by_ASC_DESC; // ASC by default
    let pages = Math.ceil(countallCompanies.count / limit);
    offset = limit * (page - 1); 
    /* End code for Pagination */
[err, companies] = await to(Company.findAll({ 
        where: { company_name: { like: '%'+ req.body.q +'%' } },
        limit: limit,
        offset: offset,
        order: [[order_by, order_by_ASC_DESC]]        
    }));
```

## What do you expect to happen?
SELECT * FROM `Companies` AS `Company` WHERE company_name LIKE '%aa%' ORDER BY `Company`.`id` ASC LIMIT 0, 4

## What is actually happening?
SELECT * FROM `Companies` AS `Company` ORDER BY `Company`.`id` ASC LIMIT 0, 4

I don't know why where condition is not adding on my query and rest of the clauses are added like Order by, limit, sort etc but where clause is not add. Please let me know how i it will add. I have tried `like` and `$like` both. Its not working for both. If i add where: `{ id: 53 }` then where clause is working but not working for like. 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
