### ISSUE TITLE
support empty value

### ISSUE THREAD

**Issue by s97712** [sequelize/sequelize#10402]
## What are you doing?

```js
const name = sequelize.empty;
const email = "foo@foo.com"
const password = "passwd"
model.find({where:{name, email ,password}});
```

## What do you expect to happen?
_that will remove empty conditional instead of use `null` value_
_it generated sql like ```select * from model where email = 'foo@foo.com' and password = 'passwd' ```_
## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Just omit key which you want to be ignored, we discussed this before and this was implemented than removed in current beta cycle

**Comment by s97712** [comment]
I know I can omit key to ignored, but if support it that will very convenient, we can omit a lot of conditional statement. consider the following code:
```
const start_time = undefined;
const end_time = undefined;


if(start_time && ! end_time) {
    Task.find({
        where: {
            release_at: {
                [Op.gt]: start_time,
            }
        }
    });
}else if(!start_time && end_time) {
    Task.find({
        where: {
            release_at: {
                [Op.lt]: end_time
            }
        }
    });
}else if(start_time && end_time) {
    Task.find({
        where: {
            release_at: {
                [Op.gt]: start_time,
                [Op.lt]: end_time
            }
        }
    });
}else {
    // !start_time && !end_time
    Task.find({
        where: {}
    });
}
```
if support empty value, just simply set the value to sequelize.empty
```
const start_time = sequelize.empty;
const end_time = sequelize.empty;

Task.find({
    where: {
        release_at: {
            [Op.gt]: start_time,
            [Op.lt]: end_time
        }
    }
})
```

**Comment by sushantdhiman** [comment]
You can rewrite that as

```js
Task.findOne({
    where: {
        release_at: {
            ...(start_time ? { [Op.gt]: start_time } : {}),
            ...(end_time ? { [Op.lt]: end_time } : {})
        }
    }
})
```
