### ISSUE TITLE
Cannot determine type of empty array on db:seed on postgres

### ISSUE THREAD

**Issue by davidcostadev** [sequelize/sequelize#10400]
Hello, Recently updating all packages and now project is crashed when I run the seed.

This is my PR that i trying to fix my project

https://github.com/withmoney/withmoney-api/pull/78

## What are you doing?

I'm trying to run seed:

`sequelize db:seed:all`

*User Model*
https://github.com/withmoney/withmoney-api/blob/fix/migrations/src/models/users.js

*Category Model*
https://github.com/withmoney/withmoney-api/blob/fix/migrations/src/models/categories.js

I think that problem is begin in this code below

```js
const timestamp = {
  createdAt: new Date(),
  updatedAt: new Date(),
};

const user = {
  password: bcrypt.hashSync('P@ssw0rd', bcrypt.genSaltSync(config.BCRYPT_SALT)),
  enabled: true,
  ...timestamp,
};

const userOne = {
  name: 'David Costa',
  email: 'davidcostadev@gmail.com',
  ...user,
};

const lancheCategory = {
  name: 'Lanche',
  type: 'out',
  ...timestamp,
};

const userOneId = await queryInterface.bulkInsert('Users', [userOne]);

lancheCategory.UserId = userTwoId;

const lancheCategoryTwoId = await queryInterface.bulkInsert('Categories', [lancheCategory]);
```

## What do you expect to happen?

That 'queryInterface.bulkInsert' return the ID of user, but is returning just '[]' an empty array

## What is actually happening?

```
yarn run v1.12.3
$ node -r dotenv/config ./node_modules/.bin/sequelize db:seed:all

Sequelize CLI [Node: 10.11.0, CLI: 5.4.0, ORM: 4.42.0]

Loaded configuration file "config/database.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
Executing (default): SELECT 1+1 AS result
== 20180401123352-Seed: migrating =======
Executing (default): INSERT INTO "Users" ("name","email","password","enabled","createdAt","updatedAt") VALUES ('David Costa','davidcostadev@gmail.com','$2b$08$AIYdjUlKZU1J4krCjLtCz.z00o7IPE17odLkEwkdAEc6Wr1k.a3Se',true,'2019-01-29 23:58:04.500 +00:00','2019-01-29 23:58:04.500 +00:00');
Executing (default): INSERT INTO "Users" ("name","email","password","enabled","createdAt","updatedAt") VALUES ('Halan Pinheiro','Halan@gmail.com','$2b$08$AIYdjUlKZU1J4krCjLtCz.z00o7IPE17odLkEwkdAEc6Wr1k.a3Se',true,'2019-01-29 23:58:04.500 +00:00','2019-01-29 23:58:04.500 +00:00');
Executing (default): INSERT INTO "Categories" ("name","type","createdAt","updatedAt","UserId") VALUES ('Lanche','out','2019-01-29 23:58:04.500 +00:00','2019-01-29 23:58:04.500 +00:00',ARRAY[]);

ERROR: cannot determine type of empty array
```

## What i tried

I already delete node_modules
I already drop database and create again
I already run 'undo' command

NOTE: This problem is only happing on POSTGRES, I try to use with *mysql* but are working!

See the tests on my CI
https://travis-ci.org/withmoney/withmoney-api/builds/488524683

node: v10.11.0
__Dialect:__ postgres
__Database version:__ 9.5.14
__Sequelize version:__ 4.1.1 (CLI)
__Tested with latest release:__ 4.37.10

The Repository
https://github.com/withmoney/withmoney-api/tree/fix/migrations

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by davidcostadev** [comment]
I find a solution temporary to make the seed works. But i`m not happy with this.

https://github.com/withmoney/withmoney-api/pull/78/commits/09f41ddeabee5509adfb9acd533ceef3d53da841

**Comment by davidcostadev** [comment]
:-(

**Comment by SqrtMinusOne** [comment]
Seems like the easiest workaround is a literal with explicit type cast, like:
```typescript
auditoriumTypes: queryInterface.sequelize.literal('ARRAY[]::"enum_Auditoriums_auditoriumTypes"[]'),
```
