### ISSUE TITLE
sequelize.sync() enforces match parameter even when force is false

### ISSUE THREAD

**Issue by aramando** [sequelize/sequelize#10408]
I expect the `match` option of the _sync_ method to provide a safeguard against executing table drops (i.e. option `force` set to true) on production databases, as implied in the docs (emphasis mine): 

> Match a regex against the database name before syncing, __a safety check for cases where force: true is used in tests but not live code__

However a mismatch is also causing sync to throw even when force is false. That means the following convenient code does not work for anything other than a test database:

```js
await sequelize.sync({ 
  force: process.env.NODE_ENV === "test", 
  match: /_test$/  
});
```

And you get error:
```
Error: Database "data_dev" does not match sync match parameter "/_test$/"
    at Sequelize.sync (/path/to/node_modules/sequelize/lib/sequelize.js:694:31)
```

Admittedly the current behaviour is as suggested by the first part of the documented description of the match option, but counter-intuitive to the intended purpose described by the second part.

__Dialect:__ postgres
__Dialect version:__ ?
__Database version:__ PostgreSQL 10.6 (Ubuntu 10.6-1.pgdg16.04+1)
__Sequelize version:__ 4.42
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
You can remove match for other env just like you did for `force` option, match act as a safely net and indicate you are doing something wrong in current env
