### ISSUE TITLE
N:M Association Insert

### ISSUE THREAD

**Issue by edwingook** [sequelize/sequelize#10401]
I have 2 classes A and B , 3 tables A , B and AB
```

A.belongsToMany(B,as:'Bs', through: models.AB) 
B.belongsToMany(A,as:'As', through: models.AB)
```
Until now the associations are working im able to fetch A with B included and the other way around.
when im trying to create A , i am sending the JSON including the chosen B values. My JSON :

```
{
"name" : "A"
"Bs": [
        {"id_B" : 1},
        {"id_B" :2},
        {"id_B" :3}
    ]
}
```
My code to insert rows is :
```
A= await models.A.build(req.body, 
           {
             transaction:transaction,
             include:[
                { as:'Bs',required:true,model:models.B},
             ]
           }
)
```
What i expect the outcome to be is for sequelize to create rows inside AB table with the id's provided and the newly created id_A , but instead it is trying to create a row id_B inside table B and failing because of other attributes that cannot be null.

__Dialect:__ mysql
__Sequelize version:__  "^4.42.0",
__Tested with latest release: Yes

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
