### ISSUE TITLE
Sequelize Decorators (NOT AN ISSUE)

### ISSUE THREAD

**Issue by weagle08** [sequelize/sequelize#10418]
A lot of people are liking TypeORM for the decorators so I've wrapped a lot of the sequelize definitions in decorators because I prefer the Sequelize querying much better than TypeORM. Would appreciate some use and feedback of the wrapper though.
https://www.npmjs.com/package/sequelizejs-decorators

Thanks,

Ben

**Comment by sushantdhiman** [comment]
Thanks, you are free to add this to our `Plugins` wiki. I am closing this ticket
