### ISSUE TITLE
String based operators are now deprecated.

### ISSUE THREAD

**Issue by catamphetamine** [sequelize/sequelize#10414]
Our code has no "operators".
Calling `new Sequelize(...)` outputs the warning.

> sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:242:13

When we comment-out `new Sequelize(...)` there's no warning being output.

**Comment by catamphetamine** [comment]
As suggested here, an `operatorsAliases: false` workaround seems to get rid of the warning.
https://github.com/sequelize/sequelize/issues/8417#issuecomment-445427478

The warning text should be changed to something like:
> String based operators are now deprecated. Please use Symbol based operators for better security. When instantiating `Sequelize` class instance pass `operatorsAliases: false` option.

**Comment by sushantdhiman** [comment]
This has been fixed in master

**Comment by mahnunchik** [comment]
Any news? I still have a warning:

```bash
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
```

```json
"sequelize": "^4.43.0",
```

**Comment by francodoshii** [comment]
Im getting the same issue.

**Comment by netojose** [comment]
Same issue here
```
"sequelize": "^4.44.4",
```

**Comment by cyber-eternal** [comment]
Same issue

` "sequelize": "^4.44.3"`

**Comment by cyber-eternal** [comment]
Updating to version
`"sequelize": "^5.8.6"`
is a solution.
It's working well on my side and doesn't need operatorsAliases in params.
