### ISSUE TITLE
Tedious 4 authentication - The "config.password" property must be of type string.

### ISSUE THREAD

**Issue by FlandersBurger** [sequelize/sequelize#10416]
## What are you doing?

Opening a connection after an upgrade to Tedious 4

```js

var config = {
  sqlServer: {
    username: 'username',
    password: 'password',
    authentication: {
      options: {
        userName: 'username',
        password: 'password',
      }
    },
    server: '127.0.0.1',
    options: {
      driver: 'SQL Server Native Client 11.0',
      port: 1433,
      database: 'DBname',
      rowCollectionOnRequestCompletion: true,
      encrypt: false,
    }
  },
}

var sequelize = new Sequelize (
  config.sqlServer.options.database,
  config.sqlServer.username,
  config.sqlServer.password,
  {
    dialect: 'mssql',
    dialectOptions: {
      encrypt: false
    },
    port: config.sqlServer.options.port,
    host:  config.sqlServer.server,
    logging: false,
    pool: {
      max: 5,
      min: 0,
      idle: 10000
    },
    operatorsAliases: operatorsAliases
  }
);
```

## What do you expect to happen?
Tedious 4 requires "authentication.options" to be used when authenticating

## What is actually happening?
However Sequelize does not have a way to pass "authentication.options" to make the connection so defining authentication is useless in my config since it's not used and i keep getting the deprecation warning

tedious deprecated The "config.userName" property is deprecated and future tedious versions will no longer support it. Please switch to using the new "config.authentication" property instead. node_modules\sequelize\lib\dialects\mssql\connection-manager.js:70:26

__Dialect:__ mssql
__Dialect version:__ N/A
__Database version:__ SQL Server Native Client 11.0
__Sequelize version:__ 4.42.0
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._
![image](https://user-images.githubusercontent.com/8195826/52294724-ddec5c00-292e-11e9-9239-9ff5912186cf.png)

**Comment by Eder87rh** [comment]
I'm having the same warning. Let me know if you find a workaround

**Comment by maxalone** [comment]
also blocked me

**Comment by dcasati** [comment]
adding a `type: "default"` to   `authentication: {}` solved for me.
here's how it looks in my case:

```
var config =
{
    authentication: {
        type: "default",
        options: {
            userName: 'MYUSER',
            password: 'MYPASSWD', 
        }
    },
    server: 'MYDB.database.windows.net',
    options:
    {
        database: 'MYDB', 
        encrypt: true
    }
}
```

**Comment by FlandersBurger** [comment]
> adding a `type: "default"` to `authentication: {}` solved for me.
> here's how it looks in my case:
> 
> ```
> var config =
> {
>     authentication: {
>         type: "default",
>         options: {
>             userName: 'MYUSER',
>             password: 'MYPASSWD', 
>         }
>     },
>     server: 'MYDB.database.windows.net',
>     options:
>     {
>         database: 'MYDB', 
>         encrypt: true
>     }
> }
> ```

Hi @dcasati , i actually tried that but it didn't change anything. as long as sequelize doesn't read authentication then it's moot to define it.

**Comment by VBAkevin** [comment]
I'm new to this, so forgive me if I am doing this incorrectly. I solved this specific issue by changing the following:

File Location ../node_modules/sequelize/lib/dialects/mssql/connection-manager.js 

Starting at line 29 or 42 depending on your version:

```javascript
// FROM:
  connect(config) {
    const connectionConfig = {
      userName: config.username, // line deleted
      password: config.password, // line deleted
      server: config.host,
      options: {
        port: config.port,
        database: config.database,
        encrypt: false
      }
    };

// TO:
  connect(config) {
    const connectionConfig = {
      server: config.host,
      options: {
        port: config.port,
        database: config.database
        encrypt: false
      },
      authentication: { // Edits begins here
        type: "default",
        options: {
          userName: config.username,
          password: config.password,
        },
      },
    };
```

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/10494
