### ISSUE TITLE
Backport MSSQL-fix to v4

### ISSUE THREAD

**Issue by sebikeller** [sequelize/sequelize#10425]
Could you backport [this fix](https://github.com/sequelize/sequelize/commit/0cbb7b9f54fa385b233dbbef69c346c3fc369145) to v4?

That would be essential to use sequelize with MSSQL and some more sophisticated model relations until v5 becomes a stable release?

Many thanks!

**Comment by sushantdhiman** [comment]
If you can open a PR with that fix I'll merge that
