### ISSUE TITLE
You are using a node deprecated package

### ISSUE THREAD

**Issue by DarkestMisery** [sequelize/sequelize#10428]
The package of 'node-uuid' is already deprecated, it has almost two years without any commit and its author gives the advise to use the 'uuid' package to generate and manage UUID's.

I know this package is maybe 'complete' but, if in a future, you will need some help from the author/s (for possible failures with the package), you will have any help or suggestions from the authors or administrators of the package.

**Comment by sushantdhiman** [comment]
We aren't using `node-uuid`

**Comment by knoxcard** [comment]
@DarkestMisery  close ticket?
