### ISSUE TITLE
Previous data values changed on each change of property

### ISSUE THREAD

**Issue by VoronFX** [sequelize/sequelize#10423]
## What are you doing?

I want to set property several times, save it once and on afterUpdate trigger produce side effect based on difference between values. (similar to db trigger with NEW and OLD)
But sequelize doesn't provide old value, only literally "previous" that is changed on every property update. Is that by design? 

```js
    const Foo = sequelize.define('Foo', {
        id: {
            type: Sequelize.BIGINT,
            allowNull: false,
            primaryKey: true
        },
        bar: {
            type: Sequelize.BIGINT
        }
    });

    const foo = await Foo.build({
        id: 1,
        bar: 0
    });

    console.log('Previous', foo.previous('bar'));
    console.log('Current', foo.bar);

    console.log('___ setting property to 1 ____');
    foo.bar = 1;

    console.log('Previous', foo.previous('bar'));
    console.log('Current', foo.bar);

    console.log('___ setting property to 2 ____');
    foo.bar = 2;

    console.log('Previous', foo.previous('bar'));
    console.log('Current', foo.bar);

    console.log('___ setting property to 3 ____');
    foo.bar = 3;

    console.log('Previous', foo.previous('bar'));
    console.log('Current', foo.bar);
```

## What do you expect to happen?
I expect previous value to be value that was on creation or retrieval of entity and NOT to change after EACH property update.
```
Previous undefined
Current 0
___ setting property to 1 ____
Previous 0
Current 1
___ setting property to 2 ____
Previous 0
Current 2
___ setting property to 3 ____
Previous 0
Current 3
```
## What is actually happening?
Now it is literally "previous" value.
```
Previous undefined
Current 0
___ setting property to 1 ____
Previous 0
Current 1
___ setting property to 2 ____
Previous 1
Current 2
___ setting property to 3 ____
Previous 2
Current 3
```
_Output, either JSON or SQL_

__Dialect:__ any
__Dialect version:__ doesn't matter
__Database version:__ doesn't matter
__Sequelize version:__ 4.42.0
__Tested with latest release:__ 4.42.0

**Comment by sushantdhiman** [comment]
In Sequelize terms. previous is last changed value. This change can be triggered by response from `find / update` or changing value manually with `instance.set` or `instance.value = ???`.

This is how our previous value behavior is defined, so i would say it works correctly

**Comment by VoronFX** [comment]
Okay, so there is no something like "unmodified" values to use in after update trigger? You have to query db for them or perform a save after each property modification for triggers to work correctly if they rely on value difference. Sadly.

**Comment by sushantdhiman** [comment]
Yep, modifications can be tracked with `previous` and `changed` but those modification can come from both database or user actions on instance

**Comment by Strate** [comment]
@sushantdhiman any chance to change this behavior? Or, maybe, introduce a new key for "original values, which actually in db right now?

**Comment by schieck0** [comment]
For me its a bug, not a feature.

**Comment by karpy47** [comment]
Idea: You could save the "original" db values in your instance using the afterFind hook (as a global hook) that is triggered after a select query. Something like... (using lodash also)
```
afterfind (instance, options) {
  instance.originalDataValues = _.clone(instance._previousDataValues)
}
```
