### ISSUE TITLE
Scope not overriding properties of previous scopes in 4.x

### ISSUE THREAD

**Issue by FREEZX** [sequelize/sequelize#10436]
I'm trying to call multiple scopes in order, starting from the 'defaultScope', so i'm passing something like this before my findAll call:

```
[ 'defaultScope',
  { method: [ 'sortByDate', 'ASC' ] } ]
```

here are the definitions for the relevant scopes:

```
		defaultScope: {
			order: [
				['createdAt', 'DESC']
			]
		},
			sortByDate: function(dir) {
				console.log(dir);
				return {
					order: [
						['createdAt', dir]
					]
				}
			},

```
_I want the sortByDate to override the ordering, as stated in the documentation_

```
limit, offset, order, paranoid, lock and raw are overwritten, while where and include are shallowly merged. This means that identical keys in the where objects, and subsequent includes of the same model will both overwrite each other.
```

_The query is always ordering by DESC_

__Dialect:__ postgres
__Sequelize version:__ ^4.42.0
__Tested with latest release:__ 4.42.0

I found the source of the issue, it's right here: 
https://github.com/sequelize/sequelize/blob/v4/lib/model.js#L1417

So, if an object value already exists, it is taken anyways, no matter if a new value is passed.
I was confused by lodash's documentation on this, but reading carefully here:
https://lodash.com/docs/4.17.11#assign
It is obvious that the objectValue is the original value on top of which the other values are applied.

It might be fixed in version 5.x, i'm checking that one next.

**Comment by FREEZX** [comment]
5.x seems to have issues with my use of gin_trgm_ops, so have to stay at 4.x for now.
I fixed the issue in my fork here: https://github.com/FREEZX/sequelize/tree/v4

**Comment by sushantdhiman** [comment]
Fixed on master
