### ISSUE TITLE
Tuple are well inserted to database, but created tuple is missing from findAll 

### ISSUE THREAD

**Issue by Nexmind** [sequelize/sequelize#10434]
## What are you doing?
Fetch all tuples from a 'Maker' table just after a creation.

Creation and FindAll
```js
/* CREATE A MAKER */
exports.create = (request, response) => {
    var maker = request.body
    Maker.create(maker).then(function (createdMaker) {
        response.status(201).json(JSON.stringify(createdMaker))
    }).catch(function (err) {
        response.status(500).json({ error: err })
    })
}

/* GET ALL MAKERS */
exports.getAll = (request, response) => {
    Maker.findAll({
        order: [
            ['name', 'ASC']
        ]
    }).then(function (makers) {
        response.status(200).json(JSON.stringify(makers))
    }).catch(function (err) {
        response.status(500).json({ error: err })
    })
}
```

Setup of my connection
```js
var sequelize = new Sequelize(sqlConnection.database, sqlConnection.username, sqlConnection.password, {
      host: sqlConnection.host,
      port: sqlConnection.port,
      logging: false,
      dialect: sqlConnection.dialect,
      dialectOptions: {
        socketPath: sqlConnection.socket
      }
  }
);
```

## What do you expect to happen?
After create a maker, this maker should be in the maker list I get with the findAll method

## What is actually happening?
[in prod only] When I create a new tuple (of Maker table) in prod through my API (using express and sequelize) the new tuple is well present in my database, but when I try to fetch them all after, the previously created tuple is not in the list. I must wait a random time before I finally get it in my FindAll.

This bug is only present when I put my application in a prod environment. Everything is well in local. I tested on multiple database (AWS and Gandi).

Is Sequelize have a cache system ? It was like Sequelize had a cache and need some time to refresh this cache after an insert. 

It's my third project with Sequelize and it's the first time I have this weird bug (But my two others projects were made with Sequelize 3)

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ 5.7
__Sequelize version:__ 4.42
__Tested with latest release:__ Tested with 4.38 then 4.42.

**Comment by sushantdhiman** [comment]
Odd, are you using replication? Probably you are missing proper return in some promise, may be returning response before record is created?
