### ISSUE TITLE
Postgres connection never closed in AWS - SequelizeConnectionError

### ISSUE THREAD

**Issue by angelmartinez-wz** [sequelize/sequelize#10439]
## What are you doing?

I have an AWS Lambda in node/apollo server that has the following configuration:
```js
module.exports = {
  username: DB_USER,
  password: DB_PASSWORD,
  database: DB_NAME,
  host: DB_HOST,
  port: DB_PORT,
  dialect: 'postgres',
  maxReconnectRetries: 10,
  logging: false,
  pool: {
    max: 5,
    min: 2,
    idle: 10000,
    acquire: 10000,
    evict: 10000,
    handleDisconnects: true,
  },
};
```
The handlers config is the following: 
```js
const server = new ApolloServer(serverParams);

const handler = server.createHandler();

export default handler;
```
## What do you expect to happen?
The Lambda/RDS integration must be following as expect

## What is actually happening?
I get a lot of times the following error `SequelizeConnectionError: Connection terminated unexpectedly` the POSTGRES max connections is set to 67 connections, the RDS dies with 5 connections

__Dialect:__postgres
__Dialect version:__ ^7.4.3
__Database version:__ 10.4
__Sequelize version:__ ^4.1.1
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`min: 2` means pool will keep two connections open at all times, if you are using lambda environment you don't need that setting.

Also try calling `sequelize.close()` just before you call lambda context callback.

**Comment by marcogrcr** [comment]
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.
