### ISSUE TITLE
update with mulitples same belongsToMany and scope 

### ISSUE THREAD

**Issue by julienperrault** [sequelize/sequelize#10444]
## What are you doing?
I have two models : Post and Form. Form model have a field "type" and i use it as a scope for Post entites.

```js
Post.belongsToMany(Form, {
    through: PostForm,
    as: 'mains',
    scope: {
        type: 'main',
    },
});
Post.belongsToMany(Form, {
    through: PostForm,
    as: 'alternatives',
    scope: {
        type: 'alternative',
    },
});
```

## What do you expect to happen?
I just want to remove Main Forms of a post. But when i do it, it's also clear Alternative Forms.
```js
await post = await Post.findByPk(postId);
/* {
    id: "8972344d-9485-4351-8834-1d0140f61441",
    createdAt: "2019-01-11T09:52:45.000Z"
    deletedAt: null
    updatedAt: "2019-02-13T16:10:22.000Z"
    ..., 
    mains: [],
    alternatives: [{ id:'29b5b646-971a-48fe-a2f8-d5c796c5a890', ... }]
} */

await post.setMains([]);
// DELETE FROM `post__form` WHERE `postId` = '8972344d-9485-4351-8834-1d0140f61441' AND `formId` IN ('29b5b646-971a-48fe-a2f8-d5c796c5a890') - SQL QUERY PERFORMED
```

__Dialect:__ mysql
__Dialect version:__ 5.7.24
__Sequelize version:__ 4.42.0
__Tested with latest release:__ Yes (4.42.0)

**Comment by sushantdhiman** [comment]
Include full example, or better SSCCE. What scopes are you using etc.

--------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
