### ISSUE TITLE
BaseError -> Error alias is confusing

### ISSUE THREAD

**Issue by broofa** [sequelize/sequelize#10445]
`BaseError` is referred to all [over the place](https://www.google.com/search?q=site%3Adocs.sequelizejs.com+baseerror) in the API docs.  And the docs for `BaseError` (that all the other error classes refer to) say this:

> All of these errors are exposed on the sequelize object and the sequelize constructor.

Thus, one would assume that something like `err instanceof Sequelize.BaseError` would be a reasonable thing to do.

Nope. `Sequelize.BaseError` is not a thing.

Only after groveling around does [the truth](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1271-L1277) reveal itself (that `BaseError` is exported as `Sequelize.Error`).  While this may be semi-obvious in hindsight (no, not really), *this is not at all obvious to unfamiliar readers*.

~~This quirk should be well and clearly documented or, better yet,~~ `BaseError` should be exported as such.

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/ae7d4b96c3738145d1ba664f3acaccf0619a748e
