### ISSUE TITLE
Model.build() 1st attribute is null, and others undefined

### ISSUE THREAD

**Issue by easywaru** [sequelize/sequelize#10446]
## What are you doing?
I Just testing default values created by Model.build()
My model, spec defined like below.
 
```js
// sample.model.js
module.exports = (sequelize, DataTypes) => {
  const Sample = sequelize.define(
    'Sample',
    {
      attr1: {
        allowNull: false,
        primaryKey: true,
        type: DataTypes.STRING,
      },
      attr2: {
        allowNull: false,
        primaryKey: true,
        type: DataTypes.STRING,
      },
    },
    {
      tableName: 'Sample',
      underscored: false,
      paranoid: false,
    }
  );

  return Sample;
};

// sample.model.spec.js
describe('sample.model.test', async () => {
  it('check set, get', async () => {
    let transaction;
    let params;
    let sample;

    try {
      transaction = await sequelize.transaction();
      params = {
      };
      sample = await Sample.build(params, { transaction });
      expect(sample.attr1).toBeUndefined();
      expect(sample.attr2).toBeUndefined();
    } finally {
      if (transaction) transaction.rollback();
    }
  });
});
```

## What do you expect to happen?
expect(sample.attr1).toBeUndefined(); => OK

## What is actually happening?
expect(sample.attr1).toBeUndefined(); => NG
My debug console's value like below
sample.attr1 = null
sample.attr2 = undefined
sample.attr3 = undefined

__Dialect:__ mysql(aws)
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
Sequelize automatically set `null` to primaryKey if they are not specified, but it was doing so for first primary key. I've fixed that behavior, now all primary keys are set to null if build is passed without them https://github.com/sequelize/sequelize/commit/786b19b9dd285b51c6fc4a84f8cfc74763957586
