### ISSUE TITLE
Is there any option for call validation on find method?

### ISSUE THREAD

**Issue by Acathur** [sequelize/sequelize#10449]
## What are you doing?
I'm trying to find an option for call validation on `find` method (`findOne`, `findAll`, etc.)

I think most of the applications will check the column value in code before execute `SELECT` query, this will filter out the unnecessary requests to the database. Developers will be appreciated if Sequelize can provide an option for this situation.

**Comment by sushantdhiman** [comment]
May be I don't get what you meant by call validation?

Do you want Sequelize to verify if columns specified in `attributes` are defined in model or not? I think that won't be possible as there may be some columns which are not defined in the model. There are dynamic columns as well.

Also what should Sequelize do if it finds any extra columns in `attributes`, throw? I think database engine is best source of truth and better let it throw.
