### ISSUE TITLE
Postgres Schema quoting inconsistent

### ISSUE THREAD

**Issue by mtfurlan** [sequelize/sequelize#10450]
When you create a schema in postgres with
```js
await sequelize.createSchema('Users');
```
it does not quote the schema, so postgres treats it as case insensitive.

## What are you doing?
```js
const sequelize = new Sequelize(process.env.DB_DATABASE, process.env.DB_USER, process.env.DB_PASSWORD, {
    host: process.env.DB_HOST,
    dialect: 'postgres',
    operatorsAliases: false,

    // Default options for a Model definition
    define: {
        createdAt: 'DateCreated',
        updatedAt: 'DateUpdated',
        freezeTableName: true,
        schema: 'Users',
    },

    migrationStorage: 'sequelize',
    migrationStorageTableSchema: 'Users',
});

await sequelize.createSchema('Users');

const User = sequelize.define('User', {});

await sequelize.sync();
```
I can create a demonstration project if needed, but I'm confident that that is the relevant information.

## What is actually happening?
```
CREATE SCHEMA Users;
CREATE TABLE IF NOT EXISTS "Users"."User" ...
```
```
error: schema "Users" does not exist
```

## What do you expect to happen?
```
CREATE SCHEMA "Users";
CREATE TABLE IF NOT EXISTS "Users"."User" ...
```

__Dialect:__ postgres
__Dialect version:__ I have the `pg` package at 7.8.0, I think that's the dialect version?
__Database version:__ 11.1
__Sequelize version:__ 4.42.0
__Tested with latest release:__ I just have the version from NPM, which package lock says 4.42.0 which is the latest on the releases page, so yes?

**Comment by mtfurlan** [comment]
I haven't tested if this is still an issue, but given the lack of activity in the thread I suspect it is.

**Comment by papb** [comment]
Thanks for the report, can you please test with the latest 5.x version?

**Comment by WikiRik** [comment]
This should already be fixed and in the `main` branch we are testing for this;
https://github.com/sequelize/sequelize/blob/096ed3ac40babc71004ea65637497fcd3a7478b0/test/unit/query-generator/create-schema-query.test.ts#L11-L19
