### ISSUE TITLE
belongsToMany needs to support targetKey

### ISSUE THREAD

**Issue by createthis** [sequelize/sequelize#10469]
`targetKey` seems to have no affect on `belongsToMany` associations. In the situation where the target table has a primary key but you are not joining on the primary key, it seems to be impossible to use `belongsToMany`. Instead, the workaround appears to be using two `hasMany` associations, which is clunky at best.

I found https://github.com/sequelize/sequelize/issues/6612 related to this issue, but it has been closed for some reason.

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/4092
