### ISSUE TITLE
Associations list on after import from different path

### ISSUE THREAD

**Issue by Wolvan** [sequelize/sequelize#10460]
## What are you doing?

**Model** Products.js
```js
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('Products', {
        VendorID: {
            type: DataTypes.TEXT,
            allowNull: false
        },
        Name: {
            type: DataTypes.TEXT,
            allowNull: true,
            defaultValue: 'N/A'
        }
    }, {
        tableName: 'Products'
    });
};
```
**Model** Companies.js
```js
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('Companies', {
        Name: {
            type: DataTypes.TEXT,
            allowNull: false
        },
        KndNr: {
            type: DataTypes.TEXT,
            allowNull: true
        }
    }, {
        tableName: 'Companies'
    });
};
```
main.js
```js
const Company = sqlize.import("./models/Companies.js");
const Product = sqlize.import("./models/Products.js");

Product.belongsTo(Company);
Company.hasMany(Product);

const res = await Product.findAll({include: Company});
```
lib/worker.js
```js
const Company = sqlize.import("../models/Companies.js");
const Product = sqlize.import("../models/Products.js");

const res = await Product.findAll({include: Company});
```

## What do you expect to happen?
Calling `sequelize.import` on a model from a different file/path keeps associations in tact and returns the cached instance.

Querrying for a Product and trying to include the Company model should properly return a result.

## What is actually happening?
The model is loaded again from the model definition file, causing the import cache to be overwritten and additional settings like associations to be lost.
This seems to come from the fact that the path and not the model name is used for caching purposes, see [sequelize.js Line 407](https://github.com/sequelize/sequelize/blob/c463314d851a7e4fad8a0f4031e472056e12be6d/lib/sequelize.js#L407).

The result is the querry throwing a `SequelizeEagerLoadingError: Companies is not associated to Product!`

__Dialect:__ any
__Sequelize version:__ 5.0.0-beta.16
__Tested with latest release:__ 4.42.0, 5.0.0-beta.16

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
It is better to share sequelize as singleton, you can follow this format https://github.com/sequelize/express-example/blob/master/models/index.js
