### ISSUE TITLE
afterBulkCreate got the error ID

### ISSUE THREAD

**Issue by fakership** [sequelize/sequelize#10465]
## What are you doing?

I meet some problems, afterBulkCreate hook。
for example, I insert 2 rows to mysql, the mysql id is autoIncrement, such as 1 2。
But, I got   2 3  id from afterBulkCreate hook!!!!!

```js
// no
```

## What do you expect to happen?
got 1 2

## What is actually happening?
got 2 3

_Output, either JSON or SQL_
SQL

__Dialect:__ mysql
__Dialect version:__ latest
__Database version:__ latest
__Sequelize version:__ latest
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
