### ISSUE TITLE
Relationship column is nullable unless explicitly set in model definition

### ISSUE THREAD

**Issue by aaronfulkerson** [sequelize/sequelize#10479]
## What are you doing?

https://gist.github.com/aaronfulkerson/43abb1e19713c301775c541ffa6eb681

## What do you expect to happen?
Column should not be nullable!

## What is actually happening?
The CustomerId column accepts null as a value even though it shouldn't!

_Output, either JSON or SQL_

__Dialect:__ postgres
__Dialect version:__ 11
__Database version:__ 11
__Sequelize version:__ 4.42
__Tested with latest release:__ yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by furqanaziz** [comment]
@aaronfulkerson I think this is a feature, not a problem. I certainly need to reference to put foreign key constraints along-with allowing null values too. But yeah if you have to put restriction to not allow null values, you can do that manually.

**Comment by sushantdhiman** [comment]
A foreign key can be null, this is perfectly valid condition. This is why it is generated as such. By defining that attribute you can override its behavior, like your example gist is doing.

Some cases where both parent and child row can exists without relationship need this. For example relation between a reader and book.

User may be reading a book at given time, so you can set `user.book_Id = <some_book_pk>` for that case. If user is not reading any book, then you can set `user.book_id = null`.

Both situation are valid and only possible if `user.book_id` is nullable.

**Comment by aaronfulkerson** [comment]
Yes, a foreign key CAN be null, however, if you define the relationship like this:

`Model1.belongsTo(Model2, {
  foreignKey: { allowNull: false }
})`

Then it should just work. Do you guys see what I'm saying?
