### ISSUE TITLE
Poorly documented addScope, functionality in provided findAll() potentially missing in docs

### ISSUE THREAD

**Issue by dmeehan1968** [sequelize/sequelize#10474]
## What are you doing?
I was trying to define a through association that had a constraint (the associated table is used to hold tags which belong to categories, the table referencing the tags pulls in those from specific categories, and some tables have more than one category of tag.

I reached out on StackOverflow ([here](https://stackoverflow.com/questions/54785460/aliasing-a-constrained-1m-association/54863538#54863538)) but didn't get a response, so I looked for related issues here and got an insight in how to solve the problem, but it appears the Sequelize documentation fails to mention this ability.

Generally the Scopes documentation is not clear or well reflected in the API docs (the scope config object is not documented).  I was able to infer from the findAll() docs what might be possible on scopes.

In the snippet below, the `through` clause I had to guess at, but it works.  The findAll() docs show `through` as an object, and the object contains keys `where` and `attributes`.  The `through` clause can also be a string table name, but this is not specified in the docs.

I've marked up the snippet with the undocumented keys
```js
  db.models.events.addScope('defaultScope', {
    include: [
      {
        association: 'venue',
        include: [
          {
            // Previously: association: 'regions',
            model: db.models.tags,
            as: 'regions',
            through: {
              model: db.model.venue_relatesto_tags, // UNDOC
              attributes: [],
            },
            foreignKey: 'venue_id',     // UNDOC
            otherKey: 'tag_id',         // UNDOC
            attributes: ['id', 'description'],
            include: [
              {
                association: 'categories',
                attributes: [],
                where: {
                  category: 'region'
                }
              }
            ],
          }
        ]
      },
    ],
    order: [ 'title' ]
  }, {
    override: true
  })```

## What do you expect to happen?
The docs should reflect the functionality.  If the functionality is not intended, then tests should be constructed to reflect the intended functionality.

__Dialect:__ mysql
__Dialect version:__ 5.7.23
__Database version:__ InnoDB 10
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No (If yes, specify that version)


**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by dmeehan1968** [comment]
I've just realised that this still doesn't work, it relies on the association named `regions` to still be described, which I originally had as a workaround (as outlined in the StackOverflow issue).

```js
  db.models.venues.belongsToMany(db.models.tags, {
    through: 'venue_relatesto_tags',
    foreignKey: 'venue_id',
    otherKey: 'tag_id',
    as: 'regions'
  })
```

Without the through association being defined, Sequelize seems to produce an erroneous error message:

```text
SequelizeEagerLoadingError: tags is associated to venues multiple times. To 
identify the correct association, you must use the 'as' keyword to specify 
the alias of the association you want to include.
```

**Comment by papb** [comment]
Hello, I would be willing to help but I did not follow. I also looked at your question on stackoverflow but I am confused. Also, if you could add a [MCVE](https://stackoverflow.com/help/mcve) highlighting the undocumented features you are mentioning, that would be great (and if you do that, thanks for the effort, the Sequelize community says thanks!)

Also, are you sure those `// UNDOC` things are indeed making a difference? Does removing them altogether makes the scope stop working?

**Comment by dmeehan1968** [comment]
Closing as this was down to my misunderstanding of Sequelize.  Answer provided on the StackOverflow question helped greatly.
