### ISSUE TITLE
`Upsert` Returns Wrong Row for Tables with Composite Primary Key

### ISSUE THREAD

**Issue by ami-kumar** [sequelize/sequelize#10470]
### What are you doing?
We are calling `upsert` on a table with a composite primary key. We are using the value returned by `upsert` to emit data into our data pipeline about the record that was added/modified. We use Postgres to store our data.

In the following example, we'd use the three constants to emit metrics:

```typescript
const upsertReturn1 = await dataAccessor.upsert({ keyA: '1', keyB: '1', other_properties: 'other' });
const upsertReturn2 = await dataAccessor.upsert({ keyA: '1', keyB: '2', other_properties: 'other' });
const upsertReturn3 = await dataAccessor.upsert({ keyA: '1', keyB: '3', other_properties: 'other' });
```

Here, (`keyA`, `keyB`) is the composite primary key for this table.

### What do you expect to happen?
We expect `upsert` to return the value from the table that corresponds to the record that was added or modified.

From the above example, we'd expect:

* `upsertReturn1` returns the row with `keyB = '1'`
* `upsertReturn2` returns the row with `keyB = '2'`
* `upsertReturn3` returns the row with `keyB = '3'`

### What is actually happening?
It does a lookup using only one of the keys in the composite key and does not return the expected record. I believe this is because the [upsert query](https://github.com/sequelize/sequelize/blob/2874c54915b2594225e939809ca9f8200b94f454/lib/dialects/postgres/query-generator.js#L344) is getting a single [primary field](https://github.com/sequelize/sequelize/blob/2874c54915b2594225e939809ca9f8200b94f454/lib/model.js#L1219) which it uses in the `insert`/`update` queries. This does not work when you have a table with a composite primary key. What we’re seeing is that it does a lookup on just one key, which returns the very first record added that matches the value for that key. 

What we're seeing from my example is:
* `upsertReturn1` returns the row with `keyB = '1'`
* `upsertReturn2` returns the row with `keyB = '1'`
* `upsertReturn3` returns the row with `keyB = '1'`

**Comment by ami-kumar** [comment]
We are still experiencing this issue

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

**Comment by ehenon** [comment]
We're having the same problem as @ami-kumar, with composite primary key in our table. It would be relevant to make a development to solve this issue.

**Comment by dyuan-boxlabs** [comment]
Are there any updates to this? We are having the exact same issue.
