### ISSUE TITLE
Mysql: prefix for column names

### ISSUE THREAD

**Issue by nichdiekuh** [sequelize/sequelize#1047]
Hi,

I'm just starting off with my first sequelize'd project. 
Would it be possible to add a prefix config option to prepend the mysql column names?

For instance :
```js
var User = seq.define('User', {

    firstname   : { type: Sequelize.STRING(40), allowNull: false},
    lastname    : { type: Sequelize.STRING(40), allowNull: false},
    password    : { type: Sequelize.STRING(40), allowNull: false},
    email       : { type: Sequelize.STRING(80), allowNull: false},
    locked      : { type: Sequelize.BOOLEAN, defaultValue : false},
    confirmed   : { type: Sequelize.BOOLEAN, defaultValue : false},
    hash        : { type: Sequelize.STRING(40), allowNull: false}

});
```
At the moment Sequelize would create a table using the defined fieldnames (+ID) exactly how they were defined. What I'd like to see is the singular table name as prefix for each field.

Column "id" would become "user_id", "firstname" would become "user_firstname" and so on. 
I like those very strict naming conventions for database tables and fields - each column name should be unique across the entire database IMO. This comes handy when you'r debugging code/queries or simply having a look at "mytop" on a production server. You always know where a certain field (columnname) is coming from.

**Comment by Nosthertus** [comment]
+1 for this suggestion

**Comment by mickhansen** [comment]
This should be trivially solveable with beforeDefine hooks now. Not making it into core.
