### ISSUE TITLE
Support for JSON object column type

### ISSUE THREAD

**Issue by enyosolutions** [sequelize/sequelize#10488]
## What are you doing?

```js
// model 
    data: {
        type: Sequelize.JSON,
        allowNull: false,
      },


db.event.create({data:{foo: 1, bar: 2}});

```

## What do you expect to happen?

I expected sequelize to store the data as a json object 

## What is actually happening?

The json is saved as a json string `"{\"data\":{\"foo\": 1, \"bar\": 2}}"`

_Output, either JSON or SQL_

`"{\"data\":{\"foo\": 1, \"bar\": 2}}"`

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by knoxcard** [comment]
1) Please post the your db model code and JSON data as well.
2) Are you using postgres, MySQL, or MariaDB?

[Workaround]
In your model code, set the JSON field type, but set your database field type manually to "LONGTEXT".

**Sample JSON Model Code**
```
blob: {
	type: DataTypes.JSON,
	allowNull: false,
	defaultValue: {}
},
```

**Comment by knoxcard** [comment]
@enyosolutions - please let us know if the workaround solution worked for you, so future programmers can also find this ticket, even after it has been closed.

**Comment by enyosolutions** [comment]
@knoxcard  i'm sorry this post is actually completely incomplete and false.

The documentation referring to the type being JSON string, but if you put a json object, it's correctly saved.

this issue can be closed. 

Sorry again.
