### ISSUE TITLE
Getter/setter asymmetry on create with associated instances

### ISSUE THREAD

**Issue by javiertury** [sequelize/sequelize#10484]
When you [create an instance with associations](http://docs.sequelizejs.com/manual/tutorial/associations.html#creating-with-associations), the primary key of the created instance is copied to the associations. There is a problem with custom getters and custom setters. The primary key is extracted using `get(field, { raw: true })`, which does not invoke the custome getter, but the it is pasted on the foreign key of the association using `set(field, value)`, which invokes the custom setter.

I use custom getters and setters to change the format of values. Internally, I use uuids on the database. But on my program, I use base58 ids.
 
The problematic code is on [this line](https://github.com/sequelize/sequelize/blob/2429146758e444716fe6f29897a787dd2dc37d48/lib/model.js#L3831):

```
instance.set(include.association.foreignKey, this.get(include.association.sourceKey || this.constructor.primaryKeyAttribute, { raw: true }));
```

## What are you doing?

```js
const Parent = sequelize.define('Parent', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      get() {
           // uuid to base58
      },
      set(string) {
           // base58 to uuid
      },
    },
})

const Child = sequelize.define('Child', {
    id: ...
    parent: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      field: 'id',
      get() {
           // uuid to base58
      },
      set(string) {
           // base58 to uuid
      },
    },
})

Child.belongsTo(Parent);
Parent.hasMany(Child);

Parent.create({
    ....
    Childs: [{
       ....
    }],
}, {
    include: Child,
})
```

## What do you expect to happen?

I would expect Sequelize to,

- Call both: custom getter on instance and custom setter on association
- Call none

## What is actually happening?

Custom getter is not invoked, but custom setter is. In this case, the custom setter throws `Invalid base58 input`

## Proposal

I propose to use

```
instance.set(include.association.foreignKey, this.get(include.association.sourceKey || this.constructor.primaryKeyAttribute, { raw: true }), { raw: true });
```

Is there anything I have overlooked?

**Comment by papb** [comment]
Fixed by #10635
