### ISSUE TITLE
Can't handle all errors at once

### ISSUE THREAD

**Issue by itsaakashpatel** [sequelize/sequelize#10485]
## What are you doing?

```js
user.findOne({
        where: {
            emil: email,
        },
    }).then(result => {
        console.log(result)
    })
```

## What do you expect to happen?
"error": {
        "name": "SequelizeDatabaseError" }

I want to get JSON response like this at client side. I want to declare one catch block for entire system from where sequelize should be able to handle all errors. Because it's always better to have one global catch for database thing than writing catch block for each query

## What is actually happening?
_Unhandled rejection SequelizeDatabaseError: Unknown column 'users.ldp' in 'where clause' in console log._

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ mysqlnd 5.0.12
__Sequelize version:__ 4.41.2
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Yes promise doesn't work like that, you still need to catch that error and pass it to some error handler, like for express passing `next(error)`. Then you can handle / format error as per your need in global error handler for express
