### ISSUE TITLE
useUTC on Postgres not working

### ISSUE THREAD

**Issue by StevenWung** [sequelize/sequelize#10480]
Hi, 
I am use Sequelize on PostgresDb, 
I have a table with field **StartTime** defined as `'timestamp without time zone'`
I have inserted value of **StartTime** as `2019-01-01 01:01:01`, 
I have config of db: 
```javascript
        dialectOptions: {
            useUTC: false,
            dateStrings: true,
        },
```
After I query all of the table the result is : <br>
`
StartTime: "2018-12-31T17:01:01.000Z"
`

What I expected is : 
`
StartTime: "2019-01-01 01:01:01"
`

Does sequelize support this config on Postgres? 
Is the sequelize wrongly configured?

Thanks

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
