### ISSUE TITLE
Feature Request: Support of updating other columns on soft delete and restore

### ISSUE THREAD

**Issue by furqanaziz** [sequelize/sequelize#10497]
## What are you doing?
I have `beforeDestroy` and `beforeRestore` hooks added to models and trying to keep track of `deletedBy` and `updatedBy` columns to see who (the user) have deleted a row and who have restored it later. This is just for logging the extra details to provide later support + audit purpose. Below is the codebase of my hooks.

```js
const attachActor = function (_options) {
  // actor is being used in afterHooks for some further logs and socket events also
  _options.actor = _options.actor || ns.get('user') || { id: null };
};

const setActionBy = function (_record, _options, _field) {
  if (hasOwnProperty.call(_record.rawAttributes, _field)) {
    _record.setDataValue(_field, _record.getDataValue(_field) || _options.actor.id);
  }
};

const beforeDestroy = function (_record, _options) {
  attachActor(_options);
  // NOTE: sequelize is updating deletedAt explicity
  setActionBy(_record, _options, 'deletedBy');
};

const beforeRestore = function (_record, _options) {
  attachActor(_options);
  // NOTE: sequelize is updating deletedAt explicity
  setActionBy(_record, _options, 'restoredBy');
};
```

## What do you expect to happen?
I wanted these `actionBy` columns to be saved along-with updating `deletedAt` value.

## What is actually happening?
It is only updating the `deletedAt` column and ignoring anything changed inside hooks. I can see that it is not possible with `Model.destroy`, `instance.destroy` and `Model.restore` at the moment. After looking the code, I could see that `deletedAt` field is explicitly updated during these operations and no respect to any other changed `dataValue`.

## Quick workaround atm
I am currently making another update call inside `afterHooks` to set these values, which is not ideal and I have to bear the cost of two updates. On the otherway I have to make delete possible with manual update but in that case, hooks triggered are not correct obviously.

**Comment by jchamb** [comment]
@furqanaziz Did you ever find another work around for this or are you still relying on the second update?

**Comment by GooBall** [comment]
This seems like such a simple thing to be able to do. I need to mutate a user email address with a "_trashed" or the like.

Is there no better way to do it?

**Comment by jchamb** [comment]
@GooBall I never found a work around I ended up with a similar approach to original poster. I have not updated to v6 yet, so not sure if it was resolved there.

**Comment by GooBall** [comment]
@jchamb Yeah, that's more or less what I went with in the end too. I'm also not running v6 yet, would be interested to see if it makes a difference.

**Comment by toymachiner62** [comment]
v6 does not address this behavior.

**Comment by rap2hpoutre** [comment]
ANy news?
