### ISSUE TITLE
sequelize.query typings are not allowing model property in typings (v5)

### ISSUE THREAD

**Issue by damianb** [sequelize/sequelize#10506]
## What are you doing?

```js
sequelize.query(/* my query here */, {
  type: QueryTypes.SELECT,
  model: ResolvedTag,
  transaction: tx
})
```

## What do you expect to happen?

Should permit specifying the model that should be returned (populated) for rows selected.

## What is actually happening?

`error TS2345: Argument of type '{ type: QueryTypes; model: typeof ResolvedTag; transaction: Transaction; }' is not assignable to parameter of type 'QueryOptions \| QueryOptionsWithType \| u ndefined'.`

__Dialect:__ mysql
__Dialect version:__ 1.6.5
__Database version:__ `mariadb:10.2` - `907f5f6c749d`
__Sequelize version:__ 5.0.0-beta.16
__Tested with latest release:__ Yes

**Comment by SimonSchick** [comment]
Can you please provide a full example?

**Comment by SimonSchick** [comment]
@sushantdhiman can we add a `TypeScript` tag for this kind of stuff?

**Comment by sushantdhiman** [comment]
There is a "typings" label for this sort of stuff @SimonSchick
