### ISSUE TITLE
On update the return rows doesn't contain timestamps

### ISSUE THREAD

**Issue by pasupulaphani** [sequelize/sequelize#10504]
## What are you doing?
Updating with flag returning: true doesn't return row timestamps.

```js
  sequelize.define('User',  { /* bla */
    createdAt: {
      field: "created_at",
      type: Sequelize.DATE
    },
    updatedAt: {
      field: "updated_at",
      type: Sequelize.DATE
    } }, {
    timestamps: true,
  }
    const result = await User.update(
      { /*bla*/},
      { returning: true, where: { id: userId }}
    );
```

## What do you expect to happen?
The returned rows contain timestamps createdAt and updatedAt

## What is actually happening?
The returned rows contain timestamps created_at ad updated_at instead of createdAt and updatedAt

__Dialect:__ postgres 
__Dialect version:__ 10
__Database version:__ XXX
__Sequelize version:__ 4.42.1
__Tested with latest release:__ Yes

**Comment by furqanaziz** [comment]
@pasupulaphani Do you mind trying this? This should work:
```js
  sequelize.define('User',  
  {
    createdAt: {
      field: "created_at",
      type: Sequelize.DATE
    },
    updatedAt: {
      field: "updated_at",
      type: Sequelize.DATE
    }
  }, {
    timestamps: true,
    underscored: false, // This should make timestamps camelCase instead snack_case
  }
});
```

**Comment by pasupulaphani** [comment]
Thank you for the suggestion. However, in my case, I need snake_case for columns and camelCase in models. For that reason, I get both createdAt and created_at when I do a ```find``` query. But in the event of ```update``` I do not get createdAt (camel-cased one).

**Comment by toymachiner62** [comment]
I'm also seeing this same issue. I'm using sequlize 4.44.0
