### ISSUE TITLE
After update from 4.42.1 to 4.43.0 problem with sql update query!

### ISSUE THREAD

**Issue by slaawwa** [sequelize/sequelize#10505]
## What are you doing?

```js
UserModel.update(
  { is_active: true },
  {
    where: { id: 1 },
  }
);
```

## What do you expect to happen?
_UPDATE `user` SET `is_active`=true WHERE `id` = 1_

## What is actually happening?
_UPDATE `user` SET `is_active`='true' WHERE `id` = 1_

__Dialect:__ mysql
__Sequelize version:__ 4.42.1
__Tested with latest release:__ 4.43.0

**Comment by arielshad** [comment]
same here,
