### ISSUE TITLE
Is there any way to add two columns value in single query?

### ISSUE THREAD

**Issue by mawais78** [sequelize/sequelize#10516]
I'm trying to perform this query with model 

```update tableName set col = col+col1 where col = "value"```

How can I do this?

This method is not working because col expects integer value 

```

Model.update({
	col: 'col + col1'
}, {
	where: {
		col: 1
	}
});

```

**Comment by JSandmark** [comment]
Could you please try this method:
```
Model.update({
        col: sequelize.literal('col + col1'),
      }, {
        where: {
          col: 1,
        },
      });
```
By using literal it "creates an object representing a literal, i.e. something that will not be escaped" from the docs.

**Comment by balexandre** [comment]
@mawais78 this is not an issue, you have [StackOverflow](https://stackoverflow.com) and so many others wesbites for questions like that ... use **Issues** when you encounter a bug and want to report it

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/7268#issuecomment-280904532
