### ISSUE TITLE
5.0.0-beta.16 underscored mode bug

### ISSUE THREAD

**Issue by dwjft** [sequelize/sequelize#10515]
## What are you doing?

```js
const model = Model.create({
someRelatedId: 1,
});
// expected
model.someRelated.id === 1
// instead
model.some_related.id === 1
```

## What do you expect to happen?

I expect the related model to be camelCased in underscored mode.

## What is actually happening?

The related model has to be referenced by its table name. (table_name instead of tableName)

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ Yes (see title)

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by dwjft** [comment]
I'm not sure why you would close this bug. Everything you need is right there.

Ignoring fatal flaws in your system because you expect someone else to do all the work for you is a terrible attitude.
