### ISSUE TITLE
Boolean doesn't convert to integer

### ISSUE THREAD

**Issue by maatMa** [sequelize/sequelize#10517]
Before the update from 4.42.1 a boolean value was converted to an integer value.

## What do you expect to happen?
The boolean value should be converted to 0 or 1

INSERT INTO [foo] 
            ([bar]) 
output      inserted.* 
VALUES      (0) 

## What is actually happening?
The SQL got a string wth "true" / "false" inside.

INSERT INTO [foo] 
            ([bar]) 
output      inserted.* 
VALUES      (N'false') 

Dialect: mssql
Dialect version: ?
Database version: 2014
Sequelize version: 4.43.0

**Comment by knoxcard** [comment]
Curious as to why this would be a great deal of concern.
Can you provide your specific use case scenario?

Good Reference:
https://stackoverflow.com/questions/263965/how-can-i-convert-a-string-to-boolean-in-javascript

```
String(true) == "true"     //returns true
String(false) == "true"    //returns false
String("true") == "true"   //returns true
String("false") == "true"  //returns false
```

**Comment by knoxcard** [comment]
Best Solution (In my opinion)

Change your boolean column data type to enum and set two integer values: 0 and 1

Boom!

**Comment by knoxcard** [comment]
@maatMa - close ticket?

**Comment by zeev-kell** [comment]
`  
await Model['user'].update({
    isDeleted: true
  }, {
    where: {
      id: 0
    }
  })
`

Executing (default): UPDATE `user` SET **`isDeleted`='true'** WHERE `id` = 0

The SQL got a string wth "true" / "false" inside.

**Comment by gabegorelick** [comment]
See #10600.

#10644 should fix this once it's backported to v4.

**Comment by gabegorelick** [comment]
This should be fixed now (booleans will never be converted to strings when passed to number fields). Let me know if it's not.
