### ISSUE TITLE
'subQuery' option for find is not documented

### ISSUE THREAD

**Issue by serge1peshcoff** [sequelize/sequelize#10511]
I was recently trying to find the solution for this issue: https://github.com/sequelize/sequelize/issues/9869, where the following example was throwing the `missing FROM-clause` error:

```js
Event.findAll({
    where: {
        deleted: false,
        '$applications.user_id$': req.user.id
    },
    include: [{
        model: Application,
        required: true
    }]
})
```

I've found one question on StackOverflow that suggested to use `subQuery: false`, so I've updated my example and now it's working, here's the working solution:

```js
Event.findAll({
    where: {
        deleted: false,
        '$applications.user_id$': req.user.id
    },
    subQuery: false,  // <----------- this line
    include: [{
        model: Application,
        required: true
    }]
})
```

But as I've found out the `subQuery` option for `findAll()` (and I suppose that for `findOne()` it's the same) is not documented or at least I couldn't find it.

Is it possible to document it so other people would be aware of it?
Thanks in advance ;)

**Comment by knoxcard** [comment]
@serge1peshcoff - great recommendation, you should submit a pull request.

**Comment by serge1peshcoff** [comment]
done :D
