### ISSUE TITLE
Why multi call? 

### ISSUE THREAD

**Issue by mdmasumbillah** [sequelize/sequelize#10510]
async getUserData(partner) {

        await models.Users.findAll().then(result=>{return result});

        return await models.Users.findOne({

            where: {
                originalId: partner.ownerId
            },
            raw: true

        }).then(result => {
            return result;
        }).catch(error => {
            return error;
        });
    }

Here getUserData() is class method. But my need  return await models.Users.findOne() value but why  await models.Users.findAll().then(result=>{return result}); .
when I call two times then return actual value. But only  return await models.Users.findOne()  then return null.

I did not want to call  two times. Avoid this methods
 await models.Users.findAll().then(result=>{return result});

Please help me

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
