### ISSUE TITLE
Timeouts and TypeError: Cannot read property 'then' of undefined at ConnectionManager._refreshDynamicOIDs

### ISSUE THREAD

**Issue by akoufatzis** [sequelize/sequelize#10521]
Hey there. I observed that I get timeouts and errors related to sequelize and Postgres. 

## What are you doing?

```js
this.sequelize = new Sequelize(database, user, pass, {
				dialect: "postgres",
				host: config.host,
				port: config.port,
				logging: false,
				pool: {
					max: maxConnections,
					min: minConnections,
					acquire: 30000,
					idle: 30000,
					evict: 30000
				}
			})
Then I am using following commands. findOrCreate , findAll, findOne
```

## What is actually happening?

<img width="551" alt="screenshot 2019-03-08 at 11 13 24" src="https://user-images.githubusercontent.com/4354310/54026790-bf84b500-41a7-11e9-977d-145b7a7290c4.png">

__Dialect:__ postgres
__Dialect version:__ 7.7.1
__Database version:__ 10.5
__Sequelize version:__ 4.43.0
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by akoufatzis** [comment]
I observed that this is being fired before I get the error: `SET standard_conforming_strings=on;SET client_min_messages TO warning; SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE;`

**Comment by basti1302** [comment]
As mentioned in https://github.com/instana/nodejs-sensor/issues/125 this is definitely an issue with the `instana-nodejs-sensor` package, so I recommend to close this issue here.

**Comment by sushantdhiman** [comment]
Thanks @basti1302
