### ISSUE TITLE
Allow to specify returning fields instead of 'RETURNING *' for PostgreSQL

### ISSUE THREAD

**Issue by Mikhus** [sequelize/sequelize#10523]
## What are you doing?
I'm trying to update or insert a record, but I want to return only specified fields. For example:
```js
// somewhere in my create user function
// (this case could be valuable for update as well)
const user = new User(createData);
// that's what I want to have
user.save({ returning: ['id', 'name', 'email'] });
// instead of 
user.save({ returning: true });
```

## What do you expect to happen?
I want my created/updated model to have fields defined only those which being specified within returning option of the save() operation. Actually, PostgreSQL allows me to do that, like
```sql
INSERT INTO "User" ("id", "name", "lastName", "email", "password")
VALUES (DEFAULT, 'John', 'Doe', 'john@doe.com', 'xxxxxx')
RETURNING id, name, email;
```

## What is actually happening?
Database will return whole set of fields for the user which are populated to the model, so after I serialize and send the model data through the network it will contain even those fields which I don't need.

__Dialect:__ postgres 
__Dialect version:__ any
__Database version:__ 9.6
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Those extra fields aren't defined in model?

**Comment by Mikhus** [comment]
Defined. But when I use 
```js
User.findByPk(42, { attributes: ['id', 'name', 'email'] });
```
I get exactly what I need. when serialize it it will contain only those fields which was requested to have. It could be used as a workaround (but will cause an extra query execution) or i would need to use 'returning *' and then handle extra fields removal manually after serialization... I think specifying the fields I need within returning statement is a proper improvement for orm, as far, as datavase itself works exactly in this way, but orm does not reflect such behavior correctly

**Comment by thurt** [comment]
This would be a nice feature to have. I feel like scopes should be utilized in this problem as well. For example, if I have a `defaultScope` in my model then the `returning: true` option should respect that by returning only the fields specified in the `defaultScope`

**Comment by Mikhus** [comment]
Working through `sequelize-typescript` package I've been able to achieve this overriding `Sequrlize.query()` method in a following way:

```typescript
import { Sequelize as SequelizeOrigin, Model } from 'sequelize-typescript';

export class Sequelize extends SequelizeOrigin {
    public query(
        sql: string | { query: string, values: any[] },
        options?: QueryOptions,
    ): Promise<any> {
        if (options &&
            Array.isArray(options.returning) &&
            options.returning.length
        ) {
            const sqlText = (typeof sql === 'string' ? sql : sql.query)
                .replace(/returning\s+\*/i, `RETURNING ${
                    options.returning.map(field => `"${field}"`).join(', ')
                }`);

            if (typeof sql === 'string') {
                sql = sqlText;
            } else {
                sql.query = sqlText;
            }
        }

        return super.query(sql, options).then(entities => {
            if (!(entities && Array.isArray(entities) && entities.length)) {
                return entities;
            }

            for (const entity of entities) {
                if (entity instanceof Model && options) {
                    (entity as any)._options.returning = options.returning;
                }
            }

            return entities;
        });
    }
}
```

BTW, to make it work correctly with the existing typings I would also need to mock and override native option types, like `QueryOptions`, `UpsertOptions`, `BuildOptions`, etc and rely on them everywhere in my code instead of native definitions which is kindly boring. The most unlike part for me is that I need additional traversing over models after mapping, so it's definitely better to have this feature as a part of ORM implementation itself. Hence, for those who looking for this feature today it may be a way to proceed, while there would be any decision on this right here...

**Comment by gabegorelick** [comment]
This has been brought up a lot before (https://github.com/sequelize/sequelize/issues/10391, and probably a bunch of other issues).

More generally, `returning` should support everything that the `attributes` option of `Model.findAll` supports, not just a list of columns. E.g. the following is valid in Postgres:
```sql
insert into foo values ('bar') returning 'hi';
```

So ideally, stuff like `Sequelize.fn` would work in a `returning` clause.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/11170

**Comment by Mike-Savin** [comment]
As for now only bulk insert query supports array values for `returning` parameter. Could this be implemented for insert/update queries?
