### ISSUE TITLE
SequelizeUniqueConstraintError can't find unique index name in MS SQL

### ISSUE THREAD

**Issue by joaoe** [sequelize/sequelize#10536]
## What are you doing?

In my project some code is trying to add a duplicate row on some table with a unique index. We're using Microsoft SQL.

The error reported lacks information to help fix the problem.

SQL Example:
```
CREATE TABLE AA(name varchar(16));
CREATE UNIQUE INDEX AA_u ON AA(name);
INSERT INTO AA VALUES('a'), ('a');
```

This produces the error message by MS SQL.
```
Cannot insert duplicate key row in object 'dbo.AA' with unique index 'AA_u'. The duplicate key value is (a).
```

## What do you expect to happen?
At the very least.
```
SequelizeUniqueConstraintError: AA_u
```
Ideally, `UniqueConstraintError.toString()` should print something much more verbose like `AA_u ON <table>(<columns>)`. Trying to debug exceptions from a test server log is no fun.

## What is actually happening?

Sequelize reports the following exception
```
SequelizeUniqueConstraintError: Validation error
  at Query.formatError (node_modules\sequelize\lib\dialects\mssql\query.js:293:14)
```
The index name is not reported in the exception message. The table name is also not stored in the Exception object.

__Dialect:__ mssql
__Dialect version:__ XXX
__Database version:__ 14
__Sequelize version:__ 4.43
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
Please try with latest version, original error with all other fields is available as `parent / original` property

**Comment by joaoe** [comment]
> original error with all other fields is available as parent / original property

That is not visible when printing the exception to a log or terminal.
