### ISSUE TITLE
afterDefine model hook is not invoked

### ISSUE THREAD

**Issue by Celadora** [sequelize/sequelize#10542]
I believe this line has an error that prevents the afterDefine hook from being invoked when on a model.

https://github.com/sequelize/sequelize/blob/f862e6bbf4b16bc2191b6becadfb0c16e4fbfd00/lib/model.js#L1043

` 
    this.sequelize.runHooks('afterDefine', this);
`

If it were to become
`
    this.sequelize.runHooks.apply(this, ['afterDefine', this])
`

Then the afterDefine hook on a model will run properly.

**Comment by SimonSchick** [comment]
I don't think this is meant to run on the model as the library consumers in control of the `define` calls and it's not really sequelize's responsibility to provide this hook on a per-model bases.

**Comment by Celadora** [comment]
Fair enough. Right now I'm using a work around wherein I place a hook on the database, then check to see if the model passed to the hook function is the one I'm looking for, and then run some operation that's required before the application is fully initialized.

 In my case I need a list of countries that are kept in a table that might change and so can't be hard-coded. I prefer keeping that list of countries directly on the model so that it can be used throughout the app.

I use a hook to gather that data before the application begins to listen, but I could do it by decorating the model after the database has connected without using hooks (and before the application begins to listen).

**Comment by Celadora** [comment]
It could be made more clear in the hooks file which hooks can be called from the database options, and which can be called from the model options.

https://github.com/sequelize/sequelize/blob/master/lib/hooks.js#L7
