### ISSUE TITLE
Update() calls getterMethods, but dataValues are not present

### ISSUE THREAD

**Issue by mromanuk** [sequelize/sequelize#10555]
## What are you doing?

```js
var player = sequelize.define('player',
  {
// more code

     email: DataTypes.STRING,
   },
  getterMethods: {
   displayUsername: function() {
          return (
            this.username ||
            this.completeName ||
            `Erudito (${this.id.slice(-12)})`
          )
  }
}
```

```js
await table.update(
      {
        email: 'erudito@erudito.com'
      },
      {
        where: {
          id: id
        }
      }
    )
```

## What do you expect to happen?

the operation should write email to the database

## What is actually happening?

Any update(), call the getterMethods (not sure why) and displayUsername doesn't have the `id` set.

console output
```bash

in displayUsername player {
  dataValues:
     id: null,
     email: 'erudito@erudito.com',
     updatedAt: 2019-03-14T20:24:05.471Z },
  _previousDataValues: { email: undefined, updatedAt: undefined },
```
Is calling getterMethods in update an expected behavior?
If that is correct, why id and is not there?

__Dialect:__  postgres 
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.1.0 /  5.0
__Tested with latest release:__ yes

**Comment by knoxcard** [comment]
Do you have setter methods defined?

**Comment by mromanuk** [comment]
> Do you have setter methods defined?

Nope

**Comment by dsamojlenko** [comment]
Same issue. Any luck figuring this out?
