### ISSUE TITLE
Can i connect to MysqlFabric through it ?

### ISSUE THREAD

**Issue by gyh9457** [sequelize/sequelize#10560]
## What are you doing?

I want connect to MysqlFabric through it,
the parameter maybe a url like `jdbc:mysql:fabric://xxx.xxx.xxx.xxx:32274/pms?fabricServerGroup=spfood-dev&fabricUsername=admin&fabricPassword=admin123#`

## What do you expect to happen?
I want to determine if I can do it.

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
We don't offer official support for this but if you can connect to that using [`node-mysql2`](https://github.com/sidorares/node-mysql2) then it should be possible to do the same with Sequelize
