### ISSUE TITLE
Circular structure when using spread operator

### ISSUE THREAD

**Issue by LeandroDoldan** [sequelize/sequelize#10562]
Hello everyone!

I'm using sequelize with express. I found a strange behavior and didn't find an issue reporting it.

I have a model called `Product`, and I'm retrieving a row from the database:
```
const product = Product.findById(req.params.id);
```

Then, I wanted to add some properties to this object, and as that is not possible with a sequelize instance, **I decided to create a new object using the spread operator**:
```
const newProduct = {
  ...product,
  otherProperties
}
```

Finally, I'm sending the response: 
```
 res.status(200).send(newProduct);
```

And I had this error: ` TypeError: Converting circular structure to JSON`

If I send back the `product` constant (the one retrieved from the database) I don't have that problem. I already tried deleting `otherProperties` from the object, so I am sure it is the spreading operation the one causing the problem. I have tried it using the `Object.assign` function too.

Any idea why this is happening?

**Comment by ClickerMonkey** [comment]
Just a guess, product has a bunch of properties you don't want to copy, try doing `...product.get()` or `...product.toJSON()`

**Comment by LeandroDoldan** [comment]
> Just a guess, product has a bunch of properties you don't want to copy, try doing `...product.get()` or `...product.toJSON()`

Thanks for your reply! I forgot to mention that this is how I ended up doing it! I sill don't understand why it doesn't work with the spread operator though.

**Comment by sushantdhiman** [comment]
`product` is an instance of [Model](http://docs.sequelizejs.com/class/lib/model.js~Model.html) which contains internal properties, Sequelize stuff and even link to other models. As suggested by others you can use [`toJSON`](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-toJSON) or [`get()`](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-get)

**Comment by yusufkhan07** [comment]
If my model has some helper properties which aren't associated with columns, `toJSON` will ignore those properties when converting to json. Any tips for it?
