### ISSUE TITLE
Unable to compile in a typescript project

### ISSUE THREAD

**Issue by pasupulaphani** [sequelize/sequelize#10566]
## What are you doing?
I'm compiling my typescript project.

```js
tsc
```

## What do you expect to happen?
Compile successfully

## What is actually happening?
Failing with failed type declaration missings.
```
node_modules/sequelize/types/lib/promise.d.ts(2,27): error TS7016: Could not find a declaration file for module 'bluebird'. '/opt/api/node_modules/bluebird/js/release/bluebird.js' implicitly has an 'any' type.
  Try `npm install @types/bluebird` if it exists or add a new declaration (.d.ts) file containing `declare module 'bluebird';`
node_modules/sequelize/types/lib/utils/validator-extras.d.ts(2,22): error TS7016: Could not find a declaration file for module 'validator'. '/opt/api/node_modules/validator/index.js' implicitly has an 'any' type.
  Try `npm install @types/validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'validator';`
```

__Dialect:__ any
__Sequelize version:__ 5.1.0
__Tested with latest release:__ Yes

**Comment by SimonSchick** [comment]
We haven't defined these packages as dependencies to avoid bloating non-ts installations, please install `@types/bluebird` and `@types/validator` separately.

**Comment by SimonSchick** [comment]
Documented at http://docs.sequelizejs.com/manual/typescript.html#installation-

**Comment by DScheglov** [comment]
Hey, @SimonSchick 

We currently have the following deps:
```
<our-project>
└─┬ sequelize@5.22.4
  └── validator@10.11.0 
```

The last version of `validator` is `13.7.0`. 
So, to install `@types/validator` correctly we should specify the version `sequelize` depends on:
```
npm i -D @types/validator@10
```

It solves the issue for now, however we will meet it again when `sequelize` migrates to new major version of `validator`.

Also we got the restriction on what version of `validator` we can use in our project. Sure we can use package aliases and install both versions of `@types/validator`, but it complicates our development and can cause unexpected issues with imports.

So, please declare `sequelize` dependencies correctly. I guess it is not a big deal for non-ts projects to have `validator` type definitions installed.

**Comment by WikiRik** [comment]
Hi @DScheglov the latest version of Sequelize is 6.11.0. It might be good to upgrade to that version so Sequelize uses the same validator version

**Comment by DScheglov** [comment]
> Hi @DScheglov the latest version of Sequelize is 6.11.0.

Actually it is a good point, however:
1. it is not so trivial (the other major version can contain some breaking changes) especially for project in the production.
2. `sequelize@6.11.0` depends on `"@types/validator": "^13.1.4",`, what if some other project needs `validator@11.*.*` or `@12.*.*`.

So, it is better to declare type dependencies explicitly as production deps.

**Comment by WikiRik** [comment]
Ah yes, having the types in the devDependencies when they might also be used in production might not be the best thing. I will discuss this with the team. Thanks for your quick response

**Comment by DScheglov** [comment]
Hey, @WikiRik 

Happy New Year!

Is any updates on the issue? )
