### ISSUE TITLE
set `underscored: true`, but `seq` is ``created_at` AS `createdAt`, `updated_at` AS `updatedAt``

### ISSUE THREAD

**Issue by yupeilin123** [sequelize/sequelize#10574]
## What are you doing?

I'm looking for data, but data do not conform to the deadline.

## What do you expect to happen?
_I wanted Foo!_

SELECT `id`, `bid`, `created_uid`, `updated_uid`, `book_name`, `author`, `treat_content`, `operation_type`, `remark`, `is_treat`, `is_pass`, `created_at` `, `updated_at`  FROM `book_records` AS `book_record` WHERE `book_record`.`bid` = '1000007' ORDER BY `book_record`.`updated_at` DESC LIMIT 0, 10;

## What is actually happening?
_But the output was bar!_

SELECT `id`, `bid`, `created_uid`, `updated_uid`, `book_name`, `author`, `treat_content`, `operation_type`, `remark`, `is_treat`, `is_pass`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `book_records` AS `book_record` WHERE `book_record`.`bid` = '1000007' ORDER BY `book_record`.`updated_at` DESC LIMIT 0, 10;

__Dialect: mysql 
__Dialect version: 1.6.5
__Database version: 8.0.13
__Sequelize version: 5.1.0

**Comment by sushantdhiman** [comment]
Yes this is intended behavior, we only set `field` to underscored name but original model attributes are still camel cased. If you want them to be snake cased as well you need to define them manually like this

```js
sequelize.define('model', {
}, {
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at'
})
```
