### ISSUE TITLE
API Reference Docs are broken

### ISSUE THREAD

**Issue by snowyfox** [sequelize/sequelize#10578]
When v5 was recently released, the docs were not published quite right. There is no way to navigate around the API reference section ([link](http://docs.sequelizejs.com/identifiers)) like you could with v4. Instead of dropping you into the root of the API, it puts you in a subsection on `Identifiers`. There is no way to get to the API reference for the Model class for instance, without clicking through into `Association` and then find a method that has a reference to `Model`. Before, the API Reference had all of the main classes listed in the side bar that you could drill down into.

The v4 docs are also mostly unusable currently, as the link for them just points to the docs folder in the v4 branch. The API Reference docs are generated by code, and are not usable via browsing the git branch. I've had to resort to a third party [mirror?](https://sequelize.readthedocs.io/en/latest/) to be able to get access to v4 API Reference docs.

Issue where docs were updated: #10475

**Comment by sushantdhiman** [comment]
Model, Sequelize, QueryInterface are all there

![image](https://user-images.githubusercontent.com/9989487/54659204-deb00a80-4af6-11e9-99e8-902843f27c7c.png)

**Comment by SimonSchick** [comment]
@sushantdhiman it might be helpful to group datatypes into their own category, I will look into this.

**Comment by SimonSchick** [comment]
Going to close this as invalid for now, I have a PR prepared to separate these things out.

**Comment by papb** [comment]
It was I who suggested OP to open the issue. I missed those links too, with all these datatypes cluttering the menu, my mistake as well, sorry about that...

I also think grouping datatypes is a good idea. @SimonSchick - this PR you mentioned, did you start working on it already? I might be able to help. I am curious as to how you thought to tackle this. I would probably do it on the `docs/plugins/esdoc-sequelize.js` file, using [cheerio](https://github.com/cheeriojs/cheerio), but that file [was deleted](https://github.com/sequelize/sequelize/commit/1ce34286655304360b2775546d8ea2af579810c3#diff-4a64923c1e0045356f42f2c425d1aea3) when esdoc was upgraded to 1.1.0. Any ideas? :grimacing:

**Comment by SimonSchick** [comment]
The easiest way to fix it would be to move the data type file into a subfolder.
The _cleaner_ solution would be to split all data types into separate files inside of the `data-types` folder.
