### ISSUE TITLE
Case statement issue

### ISSUE THREAD

**Issue by enkc06** [sequelize/sequelize#10571]
## What are you doing?

```js
// code here
```
 const type = 'emv'
  const numberArray = [];
  let start = 0;
  let end = 0;
  let total = 0;

  total = await Property.count();

  for (let i = 1; i <= 20; i++) {
    numberArray.push(i);
  }

  let query = '';

  query += `CASE WHEN "${type}" IS NULL THEN '0'`;

  for (const value of numberArray) {
    start = end + 1;
    end = value * 50000;

    query += ` WHEN "${type}" <= ${end} THEN '${value}'`;
  }

  query += " ELSE '21' END";

Property.findAll({
    where: {},
    include: [
      {
        model: Acquisition,
        required: true,
        attributes: ['leadTypeId'],
        where: {
          leadTypeId: {
            [Op.in]: [1],
          },
        },
      },
    ],
    attributes: [[sequelize.literal(`${query}`), 'x'], [sequelize.fn('COUNT', '*'), 'y']],
    group: [sequelize.literal(`${query}`)],
    order: [[sequelize.fn('MIN', sequelize.col(type)), 'ASC']],
  })

## What do you expect to happen?
_I wanted Foo!_

SELECT
	CASE WHEN "emv" IS NULL THEN
		'0'
		WHEN "emv" <= 50000 THEN
		'1'
		WHEN "emv" <= 100000 THEN
		'2'
		WHEN "emv" <= 150000 THEN
		'3'
		WHEN "emv" <= 200000 THEN
		'4'
		WHEN "emv" <= 250000 THEN
		'5'
		WHEN "emv" <= 300000 THEN
		'6'
		WHEN "emv" <= 350000 THEN
		'7'
		WHEN "emv" <= 400000 THEN
		'8'
		WHEN "emv" <= 450000 THEN
		'9'
		WHEN "emv" <= 500000 THEN
		'10'
		WHEN "emv" <= 550000 THEN
		'11'
		WHEN "emv" <= 600000 THEN
		'12'
		WHEN "emv" <= 650000 THEN
		'13'
		WHEN "emv" <= 700000 THEN
		'14'
		WHEN "emv" <= 750000 THEN
		'15'
		WHEN "emv" <= 800000 THEN
		'16'
		WHEN "emv" <= 850000 THEN
		'17'
		WHEN "emv" <= 900000 THEN
		'18'
		WHEN "emv" <= 950000 THEN
		'19'
		WHEN "emv" <= 1000000 THEN
		'20'
	ELSE
		'21'
	END AS "x",
	COUNT('*') AS "y",
	"acquisition"."leadTypeId" AS "acquisition.leadTypeId"
FROM
	"properties" AS "properties"
	INNER JOIN "acquisition" AS "acquisition" ON "properties"."id" = "acquisition"."propertyId"
		AND "acquisition"."leadTypeId" IN (1)
	GROUP BY
		CASE WHEN "emv" IS NULL THEN
			'0'
			WHEN "emv" <= 50000 THEN
			'1'
			WHEN "emv" <= 100000 THEN
			'2'
			WHEN "emv" <= 150000 THEN
			'3'
			WHEN "emv" <= 200000 THEN
			'4'
			WHEN "emv" <= 250000 THEN
			'5'
			WHEN "emv" <= 300000 THEN
			'6'
			WHEN "emv" <= 350000 THEN
			'7'
			WHEN "emv" <= 400000 THEN
			'8'
			WHEN "emv" <= 450000 THEN
			'9'
			WHEN "emv" <= 500000 THEN
			'10'
			WHEN "emv" <= 550000 THEN
			'11'
			WHEN "emv" <= 600000 THEN
			'12'
			WHEN "emv" <= 650000 THEN
			'13'
			WHEN "emv" <= 700000 THEN
			'14'
			WHEN "emv" <= 750000 THEN
			'15'
			WHEN "emv" <= 800000 THEN
			'16'
			WHEN "emv" <= 850000 THEN
			'17'
			WHEN "emv" <= 900000 THEN
			'18'
			WHEN "emv" <= 950000 THEN
			'19'
			WHEN "emv" <= 1000000 THEN
			'20'
		ELSE
			'21'
END
ORDER BY
	MIN("emv") ASC;

## What is actually happening?
_But the output was bar!_

SELECT
	CASE WHEN "emv" IS NULL THEN
		'0'
		WHEN "emv" <= 50000 THEN
		'1'
		WHEN "emv" <= 100000 THEN
		'2'
		WHEN "emv" <= 150000 THEN
		'3'
		WHEN "emv" <= 200000 THEN
		'4'
		WHEN "emv" <= 250000 THEN
		'5'
		WHEN "emv" <= 300000 THEN
		'6'
		WHEN "emv" <= 350000 THEN
		'7'
		WHEN "emv" <= 400000 THEN
		'8'
		WHEN "emv" <= 450000 THEN
		'9'
		WHEN "emv" <= 500000 THEN
		'10'
		WHEN "emv" <= 550000 THEN
		'11'
		WHEN "emv" <= 600000 THEN
		'12'
		WHEN "emv" <= 650000 THEN
		'13'
		WHEN "emv" <= 700000 THEN
		'14'
		WHEN "emv" <= 750000 THEN
		'15'
		WHEN "emv" <= 800000 THEN
		'16'
		WHEN "emv" <= 850000 THEN
		'17'
		WHEN "emv" <= 900000 THEN
		'18'
		WHEN "emv" <= 950000 THEN
		'19'
		WHEN "emv" <= 1000000 THEN
		'20'
	ELSE
		'21'
	END AS "x",
	COUNT('*') AS "y",
	"acquisition"."leadTypeId" AS "acquisition.leadTypeId"
FROM
	"properties" AS "properties"
	INNER JOIN "acquisition" AS "acquisition" ON "properties"."id" = "acquisition"."propertyId"
		AND "acquisition"."leadTypeId" IN (1)
	GROUP BY
		CASE WHEN "emv" IS NULL THEN
			'0'
			WHEN "emv" <= 50000 THEN
			'1'
			WHEN "emv" <= 100000 THEN
			'2'
			WHEN "emv" <= 150000 THEN
			'3'
			WHEN "emv" <= 200000 THEN
			'4'
			WHEN "emv" <= 250000 THEN
			'5'
			WHEN "emv" <= 300000 THEN
			'6'
			WHEN "emv" <= 350000 THEN
			'7'
			WHEN "emv" <= 400000 THEN
			'8'
			WHEN "emv" <= 450000 THEN
			'9'
			WHEN "emv" <= 500000 THEN
			'10'
			WHEN "emv" <= 550000 THEN
			'11'
			WHEN "emv" <= 600000 THEN
			'12'
			WHEN "emv" <= 650000 THEN
			'13'
			WHEN "emv" <= 700000 THEN
			'14'
			WHEN "emv" <= 750000 THEN
			'15'
			WHEN "emv" <= 800000 THEN
			'16'
			WHEN "emv" <= 850000 THEN
			'17'
			WHEN "emv" <= 900000 THEN
			'18'
			WHEN "emv" <= 950000 THEN
			'19'
			WHEN "emv" <= 1000000 THEN
			'20'
		ELSE
			'21'
END
ORDER BY
	MIN("emv") ASC;

_Output, either JSON or SQL_
SequelizeDatabaseError: column &quot;acquisition.id&quot; must appear in the GROUP BY clause or be used in an aggregate function

I didn't need
"acquisition"."leadTypeId" AS "acquisition.leadTypeId"
to be added to case statement

__Dialect: postgres
__Dialect version:__ XXX
__Database version:9.6
__Sequelize version:5.1.0
__Tested with latest release:yes
pg: 7.9.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Clearly present your problem please

---------------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
