### ISSUE TITLE
getterMethods not working when defining as part of model options

### ISSUE THREAD

**Issue by ask007learning** [sequelize/sequelize#10577]
## What are you doing?
I just defined a getter method but the getter field is not present when I do findAll. Example code below
```js

sequelize.define(
    'search_history',
    {
      id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      userName: Sequelize.STRING,
      label: Sequelize.STRING 
    },
    {
      underscored: true,
      timestamps: true,
      createdAt: false,
      getterMethods: {
        hello() {
          return fmtDateForClient(this.label);
        }
      }
    }
  );


// Find query 
 SearchHistory.findAll({
          limit: req.query.limit || 10,
          order: [['updatedAt', 'DESC']],
          where: {
            userName: req.query.userName
          }
        });

```

## What do you expect to happen?
I expect the getter field 'hello' to be present when I call findAll.

## What is actually happening?
The getter field 'hello' is not presesnt when I call findAll.

__Dialect: mysql2
__Dialect version: 1.6.4
__Database version: 5.7.22
__Sequelize version:5.1.0
__Tested with latest release: 5.1.0

**Comment by SimonSchick** [comment]
This is a partial example, can you please provide a full repro?

**Comment by yusbel80** [comment]
It is not working for me either, I had to create a VIRTUAL field on the model definition to obtain this

**Comment by SimonSchick** [comment]
```
➜  common git:(master) node
> void(S = require('sequelize'))
undefined
> S.version
'5.1.0'
> void(i = new S('mysql://root:test@localhost/test123'))
undefined
> void(U = i.define('User', { id: { type: S.INTEGER, primaryKey: true } }, { tableName: 'users', timestamps: false, getterMethods: { something() { return `${this.id}.asd`; } } }))
undefined
> void(U.create({ id: 1 }).then(m => console.log('success', m.something)))
undefined
> Executing (default): INSERT INTO `users` (`id`) VALUES (?);
success 1.asd
> void(U.findByPk(1).then(m => console.log('success', m.something)))
undefined
> Executing (default): SELECT `id` FROM `users` AS `User` WHERE `User`.`id` = 1;
success 1.asd
> 
```

This appears to work as intended, I cannot reproduce any issues.

Please note that `(g|s)setterMethods` defines getters and setters which are non-enumerable by default which means they will not show up when doing `console.log(modelInstance)`

```
> Object.getOwnPropertyDescriptor(U.prototype, 'something')
{ get: [Function],
  set: undefined,
  enumerable: false,
  configurable: true }
```

**Comment by yusbel80** [comment]
It is not working on some models,

I cannot see it in the datavalues, however it does console.log on the server. But when it is sent to the client, the value is empty

<img width="1558" alt="Screen Shot 2019-03-20 at 8 40 30 AM" src="https://user-images.githubusercontent.com/8496256/54684998-18c7df00-4aec-11e9-9d5d-03f0da87472d.png">
<img width="911" alt="Screen Shot 2019-03-20 at 8 40 39 AM" src="https://user-images.githubusercontent.com/8496256/54685012-1d8c9300-4aec-11e9-9ceb-131b8810ae62.png">
<img width="301" alt="Screen Shot 2019-03-20 at 8 40 56 AM" src="https://user-images.githubusercontent.com/8496256/54685018-21201a00-4aec-11e9-968c-361888f8cdfc.png">

**Comment by SimonSchick** [comment]
As I said, getters are not enumerable and are probably not being serialised by whatever mechanism are you using.
They will also never show up in `dataValues` as `dataValues` only contains data from the DB, you want to use a `VIRTUAL` data field here.

**Comment by yusbel80** [comment]
Alright, thank you for the reply
