### ISSUE TITLE
the 'create' method with option.raw=true make a not pure object

### ISSUE THREAD

**Issue by GodEngine** [sequelize/sequelize#10583]
## What are you doing?
when i add data into database,for example {name: 'a'} with option.raw is true. the return value should be {name: 'a'},but actually the return was {dataValue: {name: 'a'}}. so what the raw mean?
```js
 const re = await this.create({name: 'a'}, {
      raw: true,
    })
```

## What do you expect to happen?
the re should be {name: 'a'}

## What is actually happening?
the re  was {dataValue: {name: 'a'}}

**Comment by SimonSchick** [comment]
Can you please create a full repro of the issue?

**Comment by soncodi** [comment]
This occurs in both of these cases:

```ts
// 1. raw: true default all queries
const sequelize = new Sequelize('', '', '', {
  dialect: 'mysql',
  ...
  query: {  raw: true  }
});

const obj = await Obj.create({ ... }); // wrong: obj is Sequelize-wrapped object
```
and
```ts
// 2. raw: true per create query
const obj = await Obj.create({ ... }, { raw: true }); // wrong: obj is Sequelize-wrapped object
```

Other methods e.g. `Obj.update()` work correctly.

**Comment by Electoratium** [comment]
Hi @soncodi I know you've asked this question a long time ago but I've found a solution to your problem - you can add those options to .create query - at it should return plain object as we expect
```
{
      raw: true,
      isNewRecord: true,
}
```
