### ISSUE TITLE
underscored:true not returning snake_case on queries

### ISSUE THREAD

**Issue by yusbel80** [sequelize/sequelize#10581]
on sequelize@5.1.0, setting the underscored property on the model definition is not working when reading or writing to the foreign fields.

Even when I manually define the foreign key on the association, it returns both snake_case and camelCase of the same field

**Attached is an example with only underscored: true:**

<img width="1787" alt="Screen Shot 2019-03-20 at 7 12 16 AM" src="https://user-images.githubusercontent.com/8496256/54680314-ed3ef780-4adf-11e9-8930-a9edc5d5c068.png">

**Attached is an example with underscored: true and associate forgeinkey name:**

<img width="2238" alt="Screen Shot 2019-03-20 at 7 13 01 AM" src="https://user-images.githubusercontent.com/8496256/54680260-c5e82a80-4adf-11e9-8c0b-aaaf93906f54.png">

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by yusbel80** [comment]
So you are closing this issue because it's not pretty enough?

**Comment by karltaylor** [comment]
I am also having the same problem.

**Comment by miladmeidanshahi** [comment]
same damet bug :angry:
