### ISSUE TITLE
TypeError:Answer is null tolowercase

### ISSUE THREAD

**Issue by amirush786** [sequelize/sequelize#10598]
## What are you doing?
let answercorrect = answer.toLowerCase().trim();

```js 
const quiz= [
    ["Best state to live in?","Ca"],
    ["Capital of California","Jose"],
    ["Best beach","San"]
]
let score=0;

for(let i = 0;i<quiz.length;i++){
    let answer = prompt(quiz[i][0]);
 let answercorrect = answer.toLowerCase().trim();
     
    if( answercorrect === quiz[i][1]){
        score++; 
    }
    else{
        alert('Wrong ans the correct answer is' + quiz[i][1]);
    }
}



```

## What do you expect to happen?
when answer is CA and when I type ca it should work

## What is actually happening?
It takes the value from the prompt and the directly goes to else part

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ JS ES6(If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
This doesn't appear to be related to sequelize at all.
