### ISSUE TITLE
Transforming attributes in scope breaks getters

### ISSUE THREAD

**Issue by aramando** [sequelize/sequelize#10592]
Any transformation of attribute names breaks getters/setters for those attributes.

```js
const Sequelize = require('sequelize');
const connectionStr = 'YOUR_CONNECTION_STRING_TO_A_TEST_DB';
const sequelize = new Sequelize(connectionStr, { logging: false });

const attributes = {
  id: {
    type: Sequelize.DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  fullName: Sequelize.DataTypes.STRING
};

const Person = sequelize.define("Person", attributes);

async function main () {
  await sequelize.sync({ force: true });
  await Person.create({ fullName: "Atticus Finch" });
  let instance = await Person.findOne({ attributes: [['fullName', 'full_name']] })
  
  console.log(`*** Should be defined: ***`);  
  console.log(instance.dataValues.full_name);
  console.log(instance.full_name); // undefined

  console.log(`*** Original getter also doesn't work: ***`);  
  console.log(instance.fullName); // undefined
}

main();
```

## What do you expect to happen?
I expect that model instances fetched using a scope or on-query specification of attributes that alias some properties to new names will allow me to directly access those properties, ideally on their aliased names, without having to go via `.dataValues` or using the `get()` or `toJSON()` methods.

## What is actually happening?
`model.originalName` and `model.aliasedName` are _both_ undefined.

__Dialect:__ postgres & sqlite
__Sequelize version__: 5.0.0-b16
__Tested with latest release:__ Almost (current is b17)

**Comment by SimonSchick** [comment]
Iirc when aliasing you'll need to use `.get('properyName')`.

**Comment by aramando** [comment]
@SimonSchick OK, wasn't sure if this was a bug or just undocumented expected behaviour. Thanks for the rapid documentation change!

**Comment by cirosantilli** [comment]
It would be great if this could also be documented at: https://sequelize.org/master/class/lib/model.js~Model.html#static-method-getTableName which currently just says:

```
instance.field
// is the same as
instance.get('field')
```

**Comment by WikiRik** [comment]
Hi @cirosantilli, I do not really understand what you are asking for, but if you have a suggestion on how to improve the docs feel free make a PR with the changes. You can change this part of the docs by changing the JSDoc in the [model.js file](https://github.com/sequelize/sequelize/blob/main/lib/model.js)
