### ISSUE TITLE
Enable QueryUpdate Options to be extensible

### ISSUE THREAD

**Issue by smoore2386** [sequelize/sequelize#10591]
## What are you doing?
I am adding an extra parameter to my querys. So I can log the data via hooks.

```js

export interface AuditableCreateOptions extends CreateOptions {
  auditLog?: AuditEventsOptions;
}
        const something = await db.SomeThing.create(req.body, {
          auditLog: { //hooks check for auditLog information
            request: req,
            type: SOME_CODE,
            subType: 'Something Create'
          }
        } as AuditableCreateOptions);
```

## What do you expect to happen?
I would not like to have to extend all of the sequelize options

## What is actually happening?
Types check failure because we cannot extend query options

## Recommendation

Update the Typings for query options to handle generics.
```js
    /**
     * Options for Model.create method
     */
    interface CreateOptions extends BuildOptions, InstanceSaveOptions {

        /**
         * On Duplicate
         */
      onDuplicate?: string;
      [x: string]: any;
    }
```

__Dialect: any
__Dialect version:...
__Database version:__ XXX
__Sequelize version:4.39.1
__Tested with latest release:__ No 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
Not going to add an `any` index signature as this would allow invalid properties to be specified.

You can augment existing interfaces like this:

```ts
declare module 'sequelize' {
  export interface CreateOptions {
    auditLog?: ...;
  }
}
```

See https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by smoore2386** [comment]
> Not going to add an `any` index signature as this would allow invalid properties to be specified.
> 
> You can augment existing interfaces like this:
> 
> ```ts
> declare module 'sequelize' {
>   export interface CreateOptions {
>     auditLog?: ...;
>   }
> }
> ```
> 
> See https://www.typescriptlang.org/docs/handbook/declaration-merging.html

Ty. I knew . I saw something similar before this save me a bit ty.
