### ISSUE TITLE
v4.4.3 - Associated child objects are not nested as an array of childs into the parent

### ISSUE THREAD

**Issue by ErgoTobi** [sequelize/sequelize#10604]
## What are you doing?
I am trying to get all testset object with all its respective scenarios available at once.

Model parent
```js
'use strict';
module.exports = (sequelize, DataTypes) => {
  const Testset = sequelize.define('testset', {
    name: DataTypes.STRING
  }, {});
  Testset.associate = function(models) {
  };
  return Testset;
};
```
Model child
```js
'use strict';
module.exports = (sequelize, DataTypes) => {
  const Scenario = sequelize.define('scenario', {
    name: DataTypes.STRING,
    mode: DataTypes.STRING,
    route: DataTypes.STRING,
    runQuantity: DataTypes.INTEGER,
    isTextOnly: DataTypes.BOOLEAN,
    testsetId: DataTypes.INTEGER
  }, {});
  Scenario.associate = function(models) {
  };
  return Scenario;
};
```
Service 
```js
const Promise = require('promise');
Scenario.belongsTo(Testset);
Testset.hasMany(Scenario);

    readAllTestsets () {
        return fromPromise(Testset.findAll({
            raw: true,
            include: [{
                model: Scenario,
                where: {
                    //testsetId: Testset.id
                }
            }]
        }));
    }

    readTestsetById (testsetId: number) {
        return fromPromise(Testset.findByPk(testsetId, {
            include: [{
                model: Scenario,
                where: {
                    testsetId: testsetId
                }
            }]
        }));
    }
```

## What do you expect to happen?
I expect to attach all scenarios as an array to the referenced testset (foreign key: testsetId) while requesting all available testsets. It works for a single testset with the readTestsetById method. I do not understand why it replicates the testset object for the amount of scenarios available in the database instead and attaches the scenario attributes as scenario.attribute.

## What is actually happening?
SELECT `testset`.`id`, `testset`.`name`, `testset`.`createdAt`, `testset`.`updatedAt`, `scenarios`.`id` AS `scenarios.id`, `scenarios`.`name` AS `scenarios.name`, `scenarios`.`mode` AS `scenarios.mode`, `scenarios`.`route` AS `scenarios.route`, `scenarios`.`runQuantity` AS `scenarios.runQuantity`, `scenarios`.`isTextOnly` AS `scenarios.isTextOnly`, `scenarios`.`testsetId` AS `scenarios.testsetId`, `scenarios`.`createdAt` AS `scenarios.createdAt`, `scenarios`.`updatedAt` AS `scenarios.updatedAt` FROM `testsets` AS `testset` INNER JOIN `scenarios` AS `scenarios` ON `testset`.`id` = `scenarios`.`testsetId`;
The object:
![image](https://user-images.githubusercontent.com/26577392/54856248-d1af3900-4cf9-11e9-99d6-34b7dad0b4cd.png)

__Dialect:__ mysql
__Dialect version:__ 8.0
__Sequelize version:__ 4.4.3
__Tested with latest release:__ Yes

**Comment by SimonSchick** [comment]
1) There is no sequelize 5.4
2) Have you tried to not use `raw: true`?

**Comment by ErgoTobi** [comment]
Thanks a lot!
1) You are right. Added the cli version by mistake
2) That´s it. Stupid mistake on my side....
