### ISSUE TITLE
request: create() to return full model

### ISSUE THREAD

**Issue by bblack** [sequelize/sequelize#1060]
If I have a model `Model` with attributes `a, b, c, d` and I do
```
var newModel;
Model.create({a: 1})
.then(function(m){
  newModel = m;
});
```
then `newModel` will be an object with only the options passed to `create` (here, just `a`). I would like to have the full object returned, with keys present for any blank attributes, and the auto-incremented primary key if applicable.

**Comment by BridgeAR** [comment]
Is this still an issue or might this be already fixed?

**Comment by janmeier** [comment]
Yep, seems to be fixed, id is set correctly on the returned model

**Comment by handmilkingsoftware** [comment]
Hi. I've been experience something similar as talked here before. Sorry for reopening the discussion but I'm in fact receiving null as person_id on my model after create.

Here is this image (bulk.js) is actually the script that insert the new person into the database, next to it is the model it self and at the bottom, well you know is the the print from bulk.js@line 17
........................
![image](https://cloud.githubusercontent.com/assets/7492810/9042380/792580a4-39cb-11e5-9c0f-36326f96f0c4.png)
............................
Thanks any help you can bring. Great product by the way just want to get it working finally :(

**Comment by handmilkingsoftware** [comment]
hope this image you can read more clearly.
I tried to reload() as read in this very post but didn't work neither
The intention is within the success insert related elements like driver and such
...........
![image](https://cloud.githubusercontent.com/assets/7492810/9042556/bf26814c-39cc-11e5-9439-03683d86f098.png)

**Comment by bblack** [comment]
As far as I know, `bulkCreate` does not return any autoincremented primary keys, because

1. the database, not sequelize, is responsible for choosing that value
2. there is no way in general (i.e. across all flavors of SQL) to get back all the rows created as part of a multi-row insert

If you are only creating one record, you can get back the full model with autoincremented values if you use `create()` instead of `bulkCreate()`.

**Comment by handmilkingsoftware** [comment]
haha yeah Notice that. Thanks
The intention was actually create several rows but yeah guess I would need to use regular create and iterate through the array...

**Comment by lai32290** [comment]
@bblack  Thank you! you resolved my `ID` problem, is needing add `autoIncrement: true`.

You are genius!

**Comment by guotie** [comment]
If a field has default value, and create() did not set the default value, such as 
```
ret = Model.create({....})
```

then,  ret has no default field values
