### ISSUE TITLE
can we limit deletedAt to delete permanently after 30 days?

### ISSUE THREAD

**Issue by harmnot** [sequelize/sequelize#10603]
when using paranoid to be true, and I deleted some data by destroy(),
will that deleted data destroy permanently in 30 days ? or we should set it up?? 
I was curios about this, after look this [https://github.com/sequelize/sequelize/commit/014f2f5b28712f2304aa16c02883d19b1b43b5ab](url)

**Comment by SimonSchick** [comment]
No, a paranoid model will never be hard deleted by sequelize without explicitly setting the required parameters to do that (`force: true`).

You can probably setup a simple cronjob (or similar) that will do this for you.
