### ISSUE TITLE
v5.1.0 Typings - InstanceDestroyOptions does not extend Filterable

### ISSUE THREAD

**Issue by iofluxdev1** [sequelize/sequelize#10601]
## What are you doing?
I am upgrading from v4 to v5 and have come across the following IDE error when attempting to destroy a model:

```js
function deleteUser(userId, transaction, hardDelete) {

  return User.destroy({
        transaction: transaction,
        force: hardDelete,
        where: {
            user_id: {
                [Op.eq]: userId
            }
        }
    });

}
```

## What do you expect to happen?
No IDE errors for typescript linting.

## What is actually happening?
Getting typescript linting error.

Argument of type '{ transaction: any; force: true; where: { user_id: { [Op.eq]: any; }; }; }' is not assignable to parameter of type 'InstanceDestroyOptions'.
  Object literal may only specify known properties, and 'where' does not exist in type 'InstanceDestroyOptions'.

This is only a typings issue as the source shows that it does support where as per previous versions:
https://github.com/sequelize/sequelize/blob/0b868c837bb2d2a4ea1f9eeb6367f86aa7ef1f47/lib/model.js#L2689

But the typings do not extend Filterable as can be seen here:
https://github.com/sequelize/sequelize/blob/0b868c837bb2d2a4ea1f9eeb6367f86aa7ef1f47/types/lib/model.d.ts#L781

__Dialect:__ any
__Dialect version:__ NA
__Database version:__ NA
__Sequelize version:__ 5.1.0
__Tested with latest release:__ Yes (5.1.0)

**Comment by SimonSchick** [comment]
😱

**Comment by SimonSchick** [comment]
Actually... I don't think specifying `where` is support on an *instance* delete, your example uses the `static` destroy variant which supports `where`, please clarify.

**Comment by iofluxdev1** [comment]
Hi Simon, you are correct. For some reason the linter/intellisense seems to be detecting the instance method and not the static method. I will dig a bit more tomorrow as to why the IDE has got it knickers in a twist. To be clear this is only a listing issue as running our integration tests confirms it is working.
