### ISSUE TITLE
Mapping non model columns in response

### ISSUE THREAD

**Issue by anupareek** [sequelize/sequelize#10608]
Hi, 

I have a model that only contains tablename with an id attribute. 
I want to query (not via raw query) on an existing database using this model and read values of other columns (like name, status etc) which might be present in existing database. 

Can sequelize auto map new columns that it finds or it can only map the names that are mentioned in it's model definition? 

Thanks you for looking at it!.

**Comment by SimonSchick** [comment]
```
<!--

Please note this is an issue tracker, not a support forum.
For general questions, please use StackOverflow or Slack.

For bugs, please fill out the template below.

-->
```

Define them on the model, for further questions, see above.
