### ISSUE TITLE
Bulk create missing columns

### ISSUE THREAD

**Issue by Emsal92** [sequelize/sequelize#10619]
I'm trying to do a bulkCreate, but columns are missing. 

The operation:
`            models.Init_values.findAll().then((response) => {
                response.forEach(function (item) {
                    item.game_id = game_id;
                });
                models.Values.bulkCreate(response).then((response) => {
                    res.send(response);
                });
            });`

init_values:

'use strict';
module.exports = (sequelize, DataTypes) => {
  const Init_values = sequelize.define('Init_values', {
    init_value_id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      hexColor: DataTypes.STRING,
      color: DataTypes.STRING,
      limit: DataTypes.STRING,
      pari: DataTypes.STRING,
      '1stock': DataTypes.STRING,
      '2stock_s': DataTypes.STRING,
      '3stock': DataTypes.STRING,
      '4stock': DataTypes.STRING,
      '5stock': DataTypes.STRING,
      '6stock': DataTypes.STRING,
      type: DataTypes.INTEGER,
      elasticValue: DataTypes.STRING,
      rent_increase: DataTypes.STRING,
      shares: DataTypes.INTEGER
  }, {});
  Init_values.associate = function(models) {
    // associations can be defined here
  };
  return Init_values;
};

values:
`'use strict';
module.exports = (sequelize, DataTypes) => {
  const Values = sequelize.define('Values', {
    value_id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    game_id: DataTypes.INTEGER,
    hexColor: DataTypes.STRING,
    color: DataTypes.STRING,
    limit: DataTypes.STRING,
    pari: DataTypes.STRING,
    '1stock': DataTypes.STRING,
    '2stock_s': DataTypes.STRING,
    '3stock': DataTypes.STRING,
    '4stock': DataTypes.STRING,
    '5stock': DataTypes.STRING,
    '6stock': DataTypes.STRING,
    type: DataTypes.INTEGER,
    elasticValue: DataTypes.STRING,
    rent_increase: DataTypes.STRING,
    shares: DataTypes.INTEGER

  }, {});
  Values.associate = function(models) {
    models.Values.hasOne(models.Game, {
      foreignKey: {
        name: 'game_id',
        allowNull: false
      }
    });
  };
  return Values;
};`

Sql:
`SELECT `init_value_id`, `hexColor`, `color`, `limit`, `pari`, `1stock`, `2stock_s`, `3stock`, `4stock`, `5stock`, `6stock`, `type`, `elasticValue`, `rent_increase`, `shares`, `createdAt`, `updatedAt` FROM `Init_values` AS `Init_values`;
Executing (default): INSERT INTO `Values` (`value_id`,`game_id`,`createdAt`,`updatedAt`) VALUES (NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28'),(NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28'),(NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28'),(NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28'),(NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28'),(NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28'),(NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28'),(NULL,8,'2019-03-25 12:59:28','2019-03-25 12:59:28');`

**Comment by SimonSchick** [comment]
You cannot pass Model[] into bulkCreate, call `toJSON` or `.get()` on the model instance first.
