### ISSUE TITLE
META: http://docs.sequelizejs.com/ not using https

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#10610]
See title, we should fix that, certs are free nowadays.

**Comment by papb** [comment]
Closing in favor of #11209

**Comment by papb** [comment]
Actually, even if we `301 REDIRECT` to the new docs, if the original request is HTTP technically it is still insecure, right?

**Comment by sushantdhiman** [comment]
No @papb new website will automatically redirect you to `https` version
