### ISSUE TITLE
typescript: extend interfaces

### ISSUE THREAD

**Issue by jaulz** [sequelize/sequelize#10617]
## What are you doing?
Is it possible to extend the interfaces? I would like to add a new property but if I do something like this it will not be considered in update methods:
```ts
declare module 'sequelize' {
    interface InstanceUpdateOptions {
        audit?: {
            log: {
                action: Audits.Field.Action
            }
        }
    }
}
```

## What do you expect to happen?
The following should not throw a warning:
```js
entity.update({}, { 
  transaction,
  audit: { log: 'test' } 
});
```

## What is actually happening?
There is a Typescript warning:
```
Object literal may only specify known properties, and 'audit' does not exist in type 'InstanceUpdateOptions'.
```

__Dialect:__ any
__Dialect version:__ n/a
__Database version:__ n/a
__Sequelize version:__ 5.1.0
__Tested with latest release:__ yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
You need to augment the file the interface is defined in, in this case this should be `sequelize/lib/model` not `sequelize`.

**Comment by jaulz** [comment]
@SimonSchick thanks a lot! Not only for replying so fast to my question but also for putting all the effort into the annotations!

**Comment by jaulz** [comment]
@SimonSchick oops, sorry, I closed it to early because it seems my patched version was still in the cache and it still worked. It seems your suggestions does not work as expected. Hovering `'sequelize/lib/model'` does not even resolve to the sequelize module.

**Comment by jaulz** [comment]
Okay, your hint was still very good 😊 Via `declare module 'sequelize/types/lib/model'` I can change the provided interface. Thanks again!
