### ISSUE TITLE
mariadb timezone error with named timezones

### ISSUE THREAD

**Issue by seally1186** [sequelize/sequelize#10612]
## What are you doing?
Using mariadb with a named timezone and doing any query:

```js
const sequelize = new Sequelize("mariadb://...", { timezone: "America/Los_Angeles" });
sequelize.query("SELECT 1");
```

## What is actually happening?
```
SequelizeConnectionError: timezone format error. must be 'local'/'Z' or ±HH:MM. was 'America/Los_Angeles'
    at lib.createConnection.then.catch.err (/var/project/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:122:19)
```

It looks like connection-manager.js is handling the timezone (via momentTz), but it's also passing the timezone string directly to the `mariadb` library, which rejects it.

__Dialect:__ mariadb
__Dialect version:__ `mariadb@2.0.3`
__Database version:__ N/A
__Sequelize version:__ `5.1.1` and `master`
__Tested with latest release:__ Yes

**Comment by knoxcard** [comment]
@rusher - check this out...any ideas?

**Comment by rusher** [comment]
As indicate by error message, Timezone support is currently limited to "local'/'Z' or ±HH:MM. That's something that will be handled in next version (in about 2 weeks)

**Comment by knoxcard** [comment]
@rusher - two weeks is quick!  Thanks for the quick replies, as always, much appreciated!

**Comment by sushantdhiman** [comment]
I believe this https://github.com/sequelize/sequelize/pull/10705 will fix this issue
