### ISSUE TITLE
Multiple Op.eq inside Op.or or Op.and don't work as expected

### ISSUE THREAD

**Issue by abhidhillon94** [sequelize/sequelize#10611]
I am querying a column by following 2 conditions in where clause :
column1 IS NOT NULL
AND
column1 != 0

My code looks like this:
column1: {
     [Op.and] : {
          [Op.ne]: null,
          [Op.ne]: 0,
     }
}

I expect the above code to generate a query like this:
where column1 IS NOT NULL AND column1 != 0

but it generates query like this:
where column1 != 0

I tried a lot of things to make it work but only the condition specified in the last is considered in generated query

Dialect: mysql 
Database version: Mysql 5.7.23
Sequelize version: 4.42.0

Please let me know a workaround for this until its resolved.

**Comment by abhidhillon94** [comment]
I have figured out a workaround for this by querying in the following way : 
column1 > 0

By doing this I do not really need 2 different conditions.

**Comment by SimonSchick** [comment]
You cannot use the same key twice in a javascript objects, the last key declared key will always override all previous ones, this is not a sequelize issue.
