### ISSUE TITLE
mariadb: showAllTables lists tables from other databases

### ISSUE THREAD

**Issue by seally1186** [sequelize/sequelize#10629]
## What are you doing?
With mariadb, `showAllTables` lists all tables on the server (except system tables), rather than only those tables in the current database (which seems to be the behavior with other dialects, in particular mysql and postgres).

```js
  const sequelize = new Sequelize(config.dbUrl);
  console.log(await sequelize.getQueryInterface().showAllTables());
```

## What do you expect to happen?
`[]`

## What is actually happening?
Tables from other databases on the server.

Notably, this means that `dropAllTables` will attempt to clear out other databases, too.

The query seems to be using `information_schema.tables`, but (unlike Postgres) information_schema is global in MySQL/MariaDB. (Switching dialect to mysql, which uses `SHOW TABLES`, works.)

__Dialect:__ mariadb
__Dialect version:__ `mariadb@2.0.3`
__Database version:__ 10.3
__Sequelize version:__ master
__Tested with latest release:__ Yes

**Comment by knoxcard** [comment]
@rusher - seems like an easy fix, assuming the mariadb module needs a listener function to be invoked when referencing showAllTables()?

**Comment by rusher** [comment]
Sequelize documentation about [showAllTables](https://sequelize.readthedocs.io/en/latest/docs/migrations/#showalltablesoptions) indicate 

> This method returns the name of all existing tables in the database.

So either documentation must be changed to "all existing tables in the schema". or current implementation is ok. 

I think there is some confusion here : 

first compare with MySQL sequelize implementation. MySQL implementation in sequelize has no schema handling (a table 'TABLE' with schema 'SCHEMA' will result creating a table 'SCHEMA_TABLE' in current schema). MariaDB sequelize implementation result creating a SCHEMA.TABLE table. So thing are not really comparable. 

When comparing with other DB that support schema in sequelize (mssql and postgresql) Other do : 

- mssql : "SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES"  meaning listing all tables in all schemas of current database.
- postgresql: "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';" listing all tables for 'public' schema. 
  
So not sure what to do there. 

If to be done, correction would be:

```
--- lib/dialects/mariadb/query-generator.js	(revision 96f5b0e93fb396ef540afc61c1f626534963695e)
+++ lib/dialects/mariadb/query-generator.js	(date 1553764748334)
@@ -29,7 +29,7 @@
   }
 
   showTablesQuery() {
-    return 'SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN (\'MYSQL\', \'INFORMATION_SCHEMA\', \'PERFORMANCE_SCHEMA\') AND TABLE_TYPE = \'BASE TABLE\'';
+    return 'SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = SCHEMA() AND TABLE_TYPE = \'BASE TABLE\'';
   }

```

**Comment by seally1186** [comment]
Hi @rusher,

Thanks for your reply.

I agree that the comparison with MySQL may not be quite right. Maybe it's a misunderstanding on my part, but my understanding is that MariaDB doesn't support schemas, but rather treats them the same as databases. For example, in the documentation for CREATE DATABASE, it says

> CREATE SCHEMA is a synonym for CREATE DATABASE.

(Likewise, the documentation for `SCHEMA()` says, "This function is a synonym for DATABASE().")

So my confusion with `showAllTables` was that it wasn't just listing all tables in the current database but in all databases (/ schemas).

Maybe it boils down to a documentation or terminology issue. But IMHO the current behavior is a bit tricky/unintuitive to use (e.g. with `dropAllTables`).

**Comment by rusher** [comment]
I agree that terminogy is confusing. In commands, MariaDB schema is synonym of database. 
MariaDB doesn't have databases but schemas. In fact, to try to be clear, MariaDB handle like there is only one database named 'def'. 

Example : SELECT * FROM INFORMATION_SCHEMA.TABLES;
![image](https://user-images.githubusercontent.com/618074/55218686-b0b77e00-51fa-11e9-81c8-946b0aacfa28.png)

**Comment by seally1186** [comment]
Thanks for your continued replies and clarifications.

I suppose this is a bigger question then (and one of personal opinion), of whether to see the server as having one database with multiple schemas or multiple databases each with one schema (as sequelize's mysql dialect views it).

I can definitely see the benefits of supporting schemas like this, and I think by some definitions it's correct to see it as single database with multiple schemas (e.g. you can have foreign key references between tables of different schemas).

I guess for my part, I just worry that the behavior is a bit surprising since the database/schema is specified on connection. For example, if I connect to `mariadb://root@localhost/foo`, I wouldn't expect operations to affect anything outside of foo (unless I explicitly specified it).

Also, I glossed over a part of your first response: it does seem like other dialects (mssql and postgres) don't quite agree on how to handle different schemas too.

**Comment by sushantdhiman** [comment]
Apart from MySQL (and SQLite perhaps) most standard SQL implementation treat schema, table and database something like this

```
DB [
   SCHEMA(s) [
      TABLE(s), FUNCTION(s) etc
   ]
]
```

I think this is what Sequelize should implement, thus making MariaDB implementation and `showAllTables` documentation correct. I can see Postgres implementation is incorrect currently

As for MySQL it is my understanding that they treat `DB === SCHEMA`, so that is why we basically doesn't support schemas for MySQL.

**Comment by seally1186** [comment]
I guess one thing I'm unclear about is why MariaDB would be treated differently than MySQL on this. Please correct me if I'm mistaken, but as far as I understand, both servers handle databases and schemas the same way. (For example, on the MySQL 5.1 server I checked, `TABLE_CATALOG` in `INFORMATION_SCHEMA.TABLES` is NULL, and `TABLE_SCHEMA` works as it does in MariaDB above.)
