### ISSUE TITLE
findAll promise warning

### ISSUE THREAD

**Issue by waynebloss** [sequelize/sequelize#10628]
## What are you doing?

```js
module.exports = {
  async getSeries(req, res) {
    const limit = req.swagger.params.limit.value || 5;
    const offset = req.swagger.params.offset.value || 0;
    const allSeries = await series
      .findAll({
        limit,
        offset,
      });
    res.json(allSeries);
  },
};
```

The query works, there are no errors.

## What do you expect to happen?
 
No warnings.

## What is actually happening?
Warning:

```
(node:21938) Warning: a promise was created in a handler at domain.js:126:23 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/a/project/node_modules/bluebird/js/release/promise.js:196:13)
```

_Output, either JSON or SQL_

Everything works. Just want to get rid of the warning.

__Dialect:__ mysql
__Dialect version:__ idk
__Database version:__ 8
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
https://github.com/coopernurse/node-pool/issues/251 Update to latest v4

**Comment by waynebloss** [comment]
~~Looking at the code for findAll in `node_modules/sequelize/lib/model.js` I see a bunch of calls to `.then()` which don't return anything.~~

~~This seems to go against the advice of Bluebird~~ https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

Thank you! I'll see if we can update.

**Comment by waynebloss** [comment]
Wait @sushantdhiman  - I'm on v4 of sequelize and I don't see node-pool anywhere in my `package-lock.json` file...

**Comment by waynebloss** [comment]
@sushantdhiman Can you clarify what I should upgrade to v4 or reopen the issue?

**Comment by waynebloss** [comment]
OK, for any future readers - the answer is to upgrade to `4.43.0` of `sequelize`.

Also, `node-pool` is called `generic-pool` on NPM.

**Comment by bohrshaw** [comment]
This warning still occurs on Sequelize V5.

**Comment by bohrshaw** [comment]
This [commit](https://github.com/coopernurse/node-pool/commit/9471ff2429ca2b3ee5542d4e8366c29295e32670) seems not merged into https://github.com/sequelize/sequelize-pool.

**Comment by ratulSharker** [comment]
I'm facing this warning in `v6-beta`. I'm using `findOne` in one of my express middleware as following

```
Middlewares.injectActiveStatus = (req, res, next) => {
	UserStatusModel.findOne({
		where : {
			name : "ACTIVE"
		}
	})
	.then( userStatus => {
		if (userStatus) {
                        res.locals.userStatus = userStatus
			next()
		} else {
			res.status(500)
			res.json({
                           msg: "Server side error"
                        })
		}

               return null // as suggested here  http://goo.gl/rRqMUw
	})
	.catch( error => {
		console.log(error)
		res.status(400)
		res.json(Renderer.render( Messages.invalidUserStatus, {
		}))
		return error // even propagating the error too
	})
}
```

The code is pretty self explanatory, i'm reading a model using sequelize and injecting it into `res.local`.

The warning shows like following 

> (node:11735) Warning: a promise was created in a handler at domain.js:126:23 but was not returned from it, see http://goo.gl/rRqMUw
>     at Function.Promise.attempt.Promise.try (/home/ratul/Desktop/bitbucket-dev/backend/node_modules/bluebird/js/release/method.js:29:9)

If i stop calling this middleware from my router, then the warning disappears. Please let me know how to get rid of this warning.

Thanks in advance.

**Comment by papb** [comment]
@ratulSharkter Please create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) showing this warning so we can work on it.

**Comment by ratulSharker** [comment]
Hi @papb 
Sorry for late response, i was struggling with the warning to come up into the terminal. Setting the `NODE_ENV=development` was the missing link.

Demonstrating the warning can be found [here](https://github.com/papb/sequelize-sscce/pull/19).
I added it as a pull-request. I only configured the `NODE_ENV` for the travis ci, so for now you can see the warnings [here](https://travis-ci.com/papb/sequelize-sscce/jobs/249622747).

I didn't added the `NODE_ENV` thats why appvoyer ci, that is why [log](https://ci.appveyor.com/project/papb/sequelize-sscce/builds/28386054) did not shows the warning. 

 I'm also getting this warning while running in `NODE_ENV=development` mode.

[Bluebird doc](http://bluebirdjs.com/docs/api/promise.config.html) confirms that setting the `NODE_ENV=development` mode, enables `BLUEBIRD_WARNINGS`

> Both features are automatically enabled if the BLUEBIRD_DEBUG environment variable has been set or if the NODE_ENV environment variable is equal to "development".

**Comment by chengshubei** [comment]
Yes, I also find this warning occured when i set NODE_ENV=development with version  5.21.5
It`s bluebird`s problem.

**Comment by glennposadas** [comment]
Hi everyone. I'm a newbie in node-express, and I can confirm this :). I removed my NODE_ENV in my .env file and voila, error's gone!
