### ISSUE TITLE
Association Fields - Optional camel case

### ISSUE THREAD

**Issue by dsbert** [sequelize/sequelize#10637]
## What are you doing?

Associations are added using the same casing as the model class name. In the past, models were not defined as classes, so the association field names were naturally camel case if that is how the models were defined. Now, to get the same behavior, either every association has to use `as`, every model definition has to use `modelName`, or the models need to be defined with camel case class definitions, which typically creates linting errors.

Changing the names automatically could be confusing. Ideally, there would be an option to set associations as camel case by default to prevent a lot of extra string constants just to change one character.

```js
class Group extends Model {
    static associate(db) {
      this.belongsToMany(db.User, {
        through: db.UserGroup
      });
    }
  }

  class User extends Model {
    static associate(db) {
      this.belongsToMany(db.Group, {
        through: db.UserGroup
      });
    }
  }

class UserGroup extends Model {}

const groups = await db.Group.findAll({
    include: [
      {
        model: db.User,
		through: { attributes: [] }
      }
    ]
});

console.log(groups.map(g => g.get({ plain: true })));
```

## What do you expect to happen?

Since the associated models are not the class definitions, stylistically I would expect them to be lower case.

```js
/**
[
	{
		users: [...]
		// ...
	},
	// ...
]
**/
```

## What is actually happening?

```js
/**
[
	{
		Users: [...]
		// ...
	},
	// ...
]
**/
```

__Dialect:__ any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.2.0
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
I agree this is some extra hassle with class based models but we have no plans to fix this before we can properly deprecate `define`.

I think `define` is still the primary method for creating models. Class based declarations can use `modelName` as you suggested

**Comment by JoeDoyle23** [comment]
I just ran into this as well doing a v4 -> v5 upgrade. I also switched over to `class` based Model definitions. The live docs to make it look like using classes is the primary method for creating models.  http://docs.sequelizejs.com/manual/models-definition.html
