### ISSUE TITLE
Validate min/max does not work on string

### ISSUE THREAD

**Issue by pickfire** [sequelize/sequelize#10638]
## What are you doing?

```js
const Model = sequelize.define('User', {
  pass: {
    allowNull: false,
    type: Sequelize.STRING,
    validate: {
      min: 8
    }
  }
})

Model.create({ pass: 'x' })
```

## What do you expect to happen?

An error is expected to be throw because pass is below the minimum length.

## What is actually happening?

It just creates.

__Dialect:__ any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.2.1
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Yes because `min / max` works properly with integer. You have two options, first is to use `INTEGER` type OR use custom validator method

**Comment by pickfire** [comment]
@sushantdhiman Should we add that to documentation to avoid any surprises?

**Comment by husnaram** [comment]
> "`min / max` works properly with integer"

Any other alternative for `min/max` validate? 
The `len` validate cannot to separate min ro max.
