### ISSUE TITLE
TypeDefinition(Sequelize): transaction types are missing

### ISSUE THREAD

**Issue by eddiemonge** [sequelize/sequelize#10642]
@5 `Sequelize.Transaction.TYPES.EXCLUSIVE` throws `error TS2339: Property 'Transaction' does not exist on type 'typeof Sequelize`

**Comment by SimonSchick** [comment]
This is intentional.
Please use `import { Transaction } from 'sequelize'`

**Comment by eddiemonge** [comment]
ok then the bug is that the docs are not updated
