### ISSUE TITLE
findAll() and findAndCountAll() inconsistency: schema not applied in findAll()

### ISSUE THREAD

**Issue by vigalo** [sequelize/sequelize#10647]
Hello : 

## What are you doing?
When I do : 
```
Model.findAll({ schema: {'4cfdc1df-a993-4029-8009-d9c2e5b46db3'}}).then(result => console.log(result))
```
the data is fetched from the public schema in the database, but when I do : 
```
Model.findAndCountAll({ schema: {'4cfdc1df-a993-4029-8009-d9c2e5b46db3'}}).then(result => console.log(result))
```
the data is fetched from the intended schema as expected.

## What do you expect to happen?
Two commands must return the same data from the right schema

## What is actually happening?
findAll() is returning allways data from the public schema. findAndCountAll() is working as expected

__Dialect: postgres
__Sequelize version: 4.42.0
__Tested with latest release: No

**Comment by sushantdhiman** [comment]
I don't think we support passing `schema` option in both `findAll` and `findAndCountAll`, model can have a schema, which worked properly for me.

Please submit SSCCE to I can reproduce this issue

-----------------------------

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
