### ISSUE TITLE
Table hints do not apply to joined tables

### ISSUE THREAD

**Issue by dsbert** [sequelize/sequelize#10643]
## What are you doing?

I am attempting to use a table hint on an included model

```js
Model.findAll(
          {
            tableHint: db.Sequelize.TableHints.NOLOCK,            
			include: [
              { model: db.Other, tableHint: db.Sequelize.TableHints.NOLOCK }
            ],
          });
```

## What do you expect to happen?
I want the table hint to be applied on the join

## What is actually happening?
The table hint is ignored on the join and only applied to the primary table.

_Output, either JSON or SQL_

__Dialect:__ mssql
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.2
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Yes table hints are not supported for includes. We don't plan to support includes for now, they will only be added to sequelize if someone contribute this feature.

**Comment by andres-flores-espol** [comment]
Workaround (NOT RECOMMENDED, modifying sequelize prototypes may cause unexpected behavior)

I'm ussing sequelize@6.37.7

*some_file.d.ts*
```ts
import type { TableHints } from 'sequelize';

declare module 'sequelize' {
  declare interface FindOptions {
    tableHint?: TableHints;
  }

  declare interface IncludeOptions {
    tableHint?: TableHints;
  }
}
```

*another_file.ts* (It needs to be imported at the beginning of the script)
```ts
import { TableHints } from 'sequelize';
import AbstractQueryGenerator from 'sequelize/lib/dialects/abstract/query-generator';
import QueryGenerator from 'sequelize/lib/dialects/mssql/query-generator';
import Utils from 'sequelize/lib/utils';

QueryGenerator.prototype.generateJoin = function (include, topLevelInfo) {
  const join = AbstractQueryGenerator.prototype.generateJoin.call(this, include, topLevelInfo);
  join.body = Utils.joinSQLFragments([
    join.body,
    include.tableHint && TableHints[include.tableHint] && `WITH (${TableHints[include.tableHint]})`
  ]);
  return join;
};
```

*usage_file.ts*
```ts
const rows= await Model.findAll({
  tableHint: TableHints.NOLOCK,
  include: {
    model: Other,
    tableHint: TableHints.NOLOCK,
  },
  logging: console.log,
});
```

*output*
```sql
SELECT [model].[id], [model].[name], [other].[id] AS [other.id], [other].[name] AS [other.name], [other].[model_id] AS [other.model_id] FROM [models] AS [model] WITH (NOLOCK) LEFT OUTER JOIN [others] AS [other] WITH (NOLOCK) ON [model].[id] = [other].[model_id];
```
