### ISSUE TITLE
TypeDefinition(Model): version is missing in the model definition

### ISSUE THREAD

**Issue by eddiemonge** [sequelize/sequelize#10641]
@5 the TypeScript definition for model is missing the `version` attribute (which controls optimistic locking).

**Comment by SimonSchick** [comment]
Can you link the docs to that?

**Comment by eddiemonge** [comment]
@SimonSchick This breaks Sequelize instances. I get:

`Property 'models' does not exist on type 'Sequelize'. Did you mean 'model'?`

After doing `const db = new Sequelize({...}); db.models`

Specifically the `version?:...` line. Removing that restores the type recognition for Models (but obviously removes the types for the version property.


Left this same comment in the PR.
