### ISSUE TITLE
[Feature Request] Implement force add option on BelongsToMany

### ISSUE THREAD

**Issue by ALiangLiang** [sequelize/sequelize#10650]
## What are you doing?
I have three tables and there are N:M relationship below. I want to use relations between `User` and `Coupon` to present somebody has many same coupons.

```
User {
  id (primany key): Interger
  ...
}
```

```
Coupon {
  id (primany key): Interger
  ...
}
```

```
User_Coupon {
  id (primany key): Interger
  expiredAt: Date
  UserId: Interger
  CouponId: Interger
}
```

## What do you expect to happen?

Implement `force` option on `BelongsToMany.prototype.add`

```
User.addCoupon(couponInstance, { force: true })
```

Whatever the pivot row exists or not. It always create a new one row.

## What is actually happening?

If I use `User.addCoupon(couponInstance, { through: { expiredAt: Date.now() + 86400 } })` many times, it's always update the pivot rows after first time and even I created multiple pivot rows manually.

__Dialect:__ mysql
__Dialect version:__ 
__Database version:__ 5.7
__Sequelize version:__ 5.2.6
__Tested with latest release:__ 5.2.6

## Quick workaround

https://github.com/sequelize/sequelize/blob/HEAD/lib/associations/belongs-to-many.js#L651

```js
    const updateAssociations = currentRows => {
      const promises = [];
      const unassociatedObjects = [];
      const changedAssociations = [];
      for (const obj of newInstances) {
        const existingAssociation = currentRows && currentRows.find(current => current[foreignIdentifier] === obj.get(targetKey));

        // If force option set, always present unassociated. They will be created.
        if (!existingAssociation || option.force) {
          unassociatedObjects.push(obj);
        } else {
          const throughAttributes = obj[association.through.model.name];
          const attributes = _.defaults({}, throughAttributes, defaultAttributes);

          if (Object.keys(attributes).some(attribute => attributes[attribute] !== existingAssociation[attribute])) {
            changedAssociations.push(obj);
          }
        }
      }
```

**Comment by sushantdhiman** [comment]
What about using [`BelongsToMany.create`](https://github.com/sequelize/sequelize/blob/HEAD/lib/associations/belongs-to-many.js#L741)

**Comment by sushantdhiman** [comment]
Also please follow the issue template next time

**Comment by ALiangLiang** [comment]
@sushantdhiman 

`BelongsToMany.create` is used to create a new instance of the associated model instead of pivot model. 😰

btw I filled on the env info on issue.

**Comment by sushantdhiman** [comment]
In that case you can just use pivot model to create extra rows, that is a decent option rather than introduction of another option.

You missed dialect, dialect version, sequelize version etc so I not sure if this is for v4 or v5 or even v3
