### ISSUE TITLE
webpack can't compile the code by sequelize.import(path_model)

### ISSUE THREAD

**Issue by incompletude** [sequelize/sequelize#10657]
Hello guys,

I'm deploying a GraphQL to Lambda using Serverless, and I have the same problem listed in the closed issue below. The issue does not contain a viable workaround or solution.

https://github.com/sequelize/sequelize/issues/7600

Please can someone provide a workaround excluding the "do not use webpack"? Without webpack sourcemaps debugging is a nightmare.

**Comment by incompletude** [comment]
Ok, this is less than ideal, but works.

```
import Sequelize from 'sequelize'
import user from './user'
import message from './message'

const sequelize = new Sequelize(process.env.DATABASE_POSTGRESQL)

const models = {
  User: sequelize.import('User', user),
  Message: sequelize.import('Message', message),
}

Object.keys(models).forEach(key => {
  if ('associate' in models[key]) {
    models[key].associate(models)
  }
})

export { sequelize }

export default models
```

**Comment by SimonSchick** [comment]
Either: Don't use `import` which I would recommend or use https://webpack.js.org/api/module-methods/#requirecontext
