### ISSUE TITLE
[queryInterface] Support MySQL Online DDL Operations

### ISSUE THREAD

**Issue by ali-essam** [sequelize/sequelize#10653]
## What is missing?
Starting from MySQL 5.6, InnoDB Online DDL was introduced to allow altering table schema in place without locking the table.

## How to support it?
Add support for optionally specifying MySQL `ALGORITHM` and `LOCK` options when performing any DDL operation using `queryInterface`

## References
- [MySQL Online DDL Operations](https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl-operations.html)
- [A Primer on MySQL Online Schema Change](https://medium.com/web-engineering-vox/a-primer-on-mysql-online-schema-change-575fccdfa0ab)

Note: I'm willing to work on it if this is an option we want to support in sequelize

**Comment by nicoabie** [comment]
This is important. I'm having the issue described here https://github.com/sequelize/sequelize/issues/6729 because of this.
