### ISSUE TITLE
Table Names cannot be made CamelCase pluralized without the tableName flag.

### ISSUE THREAD

**Issue by bodaro** [sequelize/sequelize#10672]
## What are you doing?
I want sequelize to underscore the timestamp column names but not the table name.

I want sequelize to auto-fill _created_at_.
I want the column name to be _created_at_.
I want the table name to be the pluralized version of the model name.
I don't want to have to set _tableName_ in each model.

The underscored flag should only affect the auto-generated columns (created_at, updated_at) but not the table name itself.

This is my model:
```js

module.exports = (sequelize, DataTypes) => {
  var MyAccount = sequelize.define(
    'MyAccount', {
      some_column: {
        type: DataTypes.STRING
      }, {
    underscored: true,
})
  return MyAccount
}
```

## What do you expect to happen?
The table name is MyAccounts.

## What is actually happening?
The table name is my_accounts

__Dialect:__ sqlite
__Dialect version: 4.0.6
__Database version: sqlite3 3.24.0
__Sequelize version: 5.2.1
__Tested with latest release: yes, 5.2.1

**Comment by ALiangLiang** [comment]
Option `underscored ` is just add the underscored field to all attributes, this covers user defined attributes, timestamps and foreign keys.

https://github.com/sequelize/sequelize/blob/4ec86a4bd43aa65e45546e2d4177ffcbeb2b4bac/lib/model.js#L886

**Comment by sushantdhiman** [comment]
Implementation `underscored` flag has been change and it now controls everything, if you want to fine tune your names I suggest don't use this flag and set `field` and `tableName` manually.

What you want is mix of underscored and camel casing that wont work with current underscored implementation. I don't think we will move towards that direction.
