### ISSUE TITLE
JSDoc documentation versus documentation in `*.d.ts`

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#10673]
Is it intended that the two parameter documentations below aren't the same?

https://github.com/sequelize/sequelize/blob/abfe7e51c716e622dfd8aa23820c460dd3c57f96/lib/sequelize.js#L319

https://github.com/sequelize/sequelize/blob/abfe7e51c716e622dfd8aa23820c460dd3c57f96/types/lib/sequelize.d.ts#L1017-L1018

Also, since now we have duplicated documentation on the source files and on `.d.ts` files, is there a concrete way to prevent documentation from being updated only in one place?

Pinging @SimonSchick since I know you're highly involved in the typescript things in Sequelize. Thanks for looking!

**Comment by SimonSchick** [comment]
tl;dr the typings used to be separate, so documentation was duplicated in many places.
I hope we can eventually use TS for sequelize itself and/or generate documentation entirely from the type definitions and make it a single point of truth as the typings are subjectively better documentation than the current jsdoc in the source.

**Comment by papb** [comment]
@SimonSchick - I see. Thanks for the fast response :grin: While sequelize itself doesn't use TS, do you know any tool to generate documentation from `*.d.ts` files?

Also, is it possible to use syntax similar to `{@link}` in the `*.d.ts` documentation? (I am very new to TS, sorry if it is a trivial question). If not, what is a good strategy when documenting to replace things like `{@link}` in the `*.d.ts` documentation?

**Comment by SimonSchick** [comment]
I don't think that `@link` works very well in TS but you're welcome to try.

As for generating documentation, I worked with some generators before but their capabilities were extremely limited, you are welcome to make suggestions.

**Comment by papb** [comment]
I see. I've asked a [question in typedoc](https://github.com/TypeStrong/typedoc/issues/1002) to see if it would be possible to use that. Other than that, I have no idea...

Maybe we will have to put up with duplicated docs while sequelize doesn't move to TS. It's not ideal but I don't think it's that terrible either...

**Comment by papb** [comment]
@SimonSchick - Apparently [it is possible to use typedoc](https://github.com/TypeStrong/typedoc/issues/1002). I do not have the time to try it out though... Just letting you know.

**Comment by ALiangLiang** [comment]
I just tried to use this generator.
```bash
typedoc --exclude node_modules/ --includeDeclarations --out typedoc/ types/lib
```

**Comment by SimonSchick** [comment]
Ultimately this is up to @sushantdhiman as this would drastically alter the current documentation and might make it harder for non TS users to read, we could co-host a type-doc version but that's not my call 😄
