### ISSUE TITLE
Cannot set created_at for both model and database column

### ISSUE THREAD

**Issue by bodaro** [sequelize/sequelize#10671]
## What are you doing?
For timestamps, I want sequelize to auto-fill _created_at_.
I want the column name to be _created_at_
I want the model attribute to be _created_at_ as well.

The only way to have auto-filled created_at is to set `underscored = true` in the model. But then the attribute is still _createdAt_ (not _created_at_).

This is my model:
```js

module.exports = (sequelize, DataTypes) => {
  var Account = sequelize.define(
    'Account', {
      created_at: {
        type: DataTypes.DATE
      }, {
    underscored: true,
})
  return Account
}
```

## What do you expect to happen?
I want the column to be named created_at and the attribute to be created_at and the column to be auto-populated by Sequelize.

## What is actually happening?
With the above model, the database column is created_at but the attribute name is createdAt

__Dialect:__ sqlite
__Dialect version: 4.0.6
__Database version: sqlite3 3.24.0
__Sequelize version: 5.2.1
__Tested with latest release: yes, 5.2.1

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
```js
module.exports = (sequelize, DataTypes) => {
  var Account = sequelize.define(
    'Account', {
      created_at: {
        type: DataTypes.DATE
      }, {
    underscored: true,
    createdAt: 'created_at'
})
  return Account
}
```
