### ISSUE TITLE
application - TypeError: _sequelize2.default.transaction is not a function

### ISSUE THREAD

**Issue by lingxiao-Zhu** [sequelize/sequelize#10679]
## What are you doing?

```js
const PetServices = {
  async addPet(openid) {
    return Sequelize.transaction(t => {
      // chain all your queries here. make sure you return them.
      return User.findOne(
        {
          where: {
            openid
          }
        },
        { transaction: t }
      );
    })
      .then(result => {
        // Transaction has been committed
        // result is whatever the result of the promise chain returned to the transaction callback
      })
      .catch(err => {
        console.log(err);
        // Transaction has been rolled back
        // err is whatever rejected the promise chain returned to the transaction callback
      });
  }
};
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
application - TypeError: _sequelize2.default.transaction is not a function

_Output, either JSON or SQL_

__Dialect:__ mysql
__Dialect version:__ 2.15.0
__Database version:__ 8.0.15
__Sequelize version:__ ^4.37.10
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
It seems you are trying to call this as a static method rather than in instance method.
