### ISSUE TITLE
Property 'useCLS' does not exist on type 'typeof Sequelize'.

### ISSUE THREAD

**Issue by xiabaiyang** [sequelize/sequelize#10684]

**Comment by danuharja** [comment]
No problem

**Comment by xiabaiyang** [comment]
why? static method useCLS dont need export?




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            夏柏阳
                            
                            
                                
                                    邮箱：baiyangfe@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


On 04/03/2019 01:35, danuharja wrote: No problem

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sequelize/sequelize","title":"sequelize/sequelize","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sequelize/sequelize"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danuharja in #10684: No problem"}],"action":{"name":"View Issue","url":"https://github.com/sequelize/sequelize/issues/10684#issuecomment-479110801"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sequelize/sequelize/issues/10684#issuecomment-479110801",
"url": "https://github.com/sequelize/sequelize/issues/10684#issuecomment-479110801",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xiabaiyang** [comment]
> No problem

Do you mean that this result is in line with expectations?

**Comment by SimonSchick** [comment]
@xiabaiyang while I understand your issue report, other contributors and maintainers may not.

Please do **not** ignore the issue template, thank you.

From template:
```
<!-- Post a minimal, self-contained code sample that reproduces the issue, including models and associations -->
```
