### ISSUE TITLE
underscored:true not returning snake_case on queries

### ISSUE THREAD

**Issue by yusbel80** [sequelize/sequelize#10689]
on sequelize@5.1.0, setting the underscored property on the model definition is not working when reading or writing to the foreign fields.

Even when I manually define the foreign key on the association, it returns both snake_case and camelCase of the same field.

## What are you doing?

Model Definition:

```js
    const Model =  sequelize.define('tasks', {
        task_id: {
            type: dataTypes.INTEGER,
            primaryKey: true,
            allowNull: false,
            autoIncrement: true
        },
        task_status: {
            type: dataTypes.INTEGER,
            allowNull: false,
            defaultValue: 1,
            comment: "[1]Created [2]Done"
        },
        created_at: {
            type: 'TIMESTAMP',
            defaultValue: sequelize.literal('CURRENT_TIMESTAMP'),
            allowNull: false
        },
    },{
        underscored: true,
        timestamps: false,
    });

    Model.associate = function (models) {
        Model.belongsTo(models.appointment, {   onDelete: "NO ACTION", onUpdate: "NO ACTION" });
    };
    return Model;
```

## What do you expect to happen?
The default foreign key for appointments should be 'appointment_appointment_id' since I have defined this model as 'underscored:true'.

In my DB it is also defined as 'appointment_appointment_id'

## What is actually happening?
It is, however, returning a camelCase field name as 'appointmentAppointmentId. 

<img width="2238" alt="2" src="https://user-images.githubusercontent.com/8496256/55423773-9bb95280-554c-11e9-9dfb-788f3f95ee49.png">

_Output, either JSON or SQL_

__Dialect: mysql 
__Dialect version: mysql2@1.6.5
__Database version: MySQL 5.7
__Sequelize version: sequelize@5.1.

__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by yusbel80** [comment]
Adding association on appointment model 'hasOne' and defining the foreignKey solved this issue.
However, I should not be having to define the foreignKey name when wanting to use the default underscored snake_case naming convention.

**Comment by sushantdhiman** [comment]
`underscored: true` will keep all attributes as camel cased but their `field` will be set to snake cased. So you can use `camelCase` on JS side but database columns will be `snake_cased`
