### ISSUE TITLE
HasMany / BelongsToMany association does not working

### ISSUE THREAD

**Issue by emilianito** [sequelize/sequelize#10682]
## What are you doing?
I was checking some examples in the official documentation, but this one is not working for me.

```js

class Tag extends Sequelize.Model {}

Tag.init({
  name: Sequelize.STRING
}, { sequelize });

class Product extends Sequelize.Model {}

Product.init({
    title: Sequelize.STRING
}, { sequelize });

Product.hasMany(Tag);

Product.create({
  id: 1,
  title: 'Chair',
  tags: [
    { name: 'Alpha'},
    { name: 'Beta'}
  ]
}, {
  include: [ Tag ]
})
```

## What do you expect to happen?
I expect that code creates a Product and two Tags.. 

## What is actually happening?
This creates just a Product, generates just one query insert:

Executing (default): INSERT INTO "Products" ("id","title","createdAt","updatedAt") VALUES (1,'Chair','2019-04-01 23:01:08.877 +00:00','2019-04-01 23:01:08.877 +00:00') RETURNING *;

The code don't create any Tag.

__Dialect:__ postgres 
__Dialect version:__ XXX
__Database version:__ "sequelize":  PostgreSQL 11.2
__Sequelize version:__ "sequelize": "sequelize": "^5.2.8"
__Tested with latest release:__ Yes 5.2.8

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by ALiangLiang** [comment]
The document has some typos. You need to use `Tags` instead of `tags`.

```
Product.create({
  id: 1,
  title: 'Chair',
  Tags: [
    { name: 'Alpha'},
    { name: 'Beta'}
  ]
}, {
  include: [ Tag ]
})
```

**Comment by emilianito** [comment]
It works now! thank you!
