### ISSUE TITLE
defaultScope mutates after applying .scope(['defaultScope', 'otherScope'])

### ISSUE THREAD

**Issue by robbyphillips** [sequelize/sequelize#10696]
## What are you doing?

With the code below, the default scope of the model seems to be overridden after doing `Model.scope(['defaultScope', 'withBar'])`, leading to unexpected results.

```js
const config = require('./config/config.json')
const Sequelize = require('sequelize')
const sequelize = new Sequelize(config['development'])

  const User = sequelize.define('User', {
    name: Sequelize.STRING,
    foo: Sequelize.BOOLEAN,
    bar: Sequelize.BOOLEAN,
    baz: Sequelize.BOOLEAN
  }, {});

  User.addScope('defaultScope', {
    where: { foo: true }
  }, { override: true })

  User.addScope('withBar', {
    where: { bar: true }
  })

  User.addScope('noBaz', {
    where: { baz: false }
  })

const users = [
  {
    name: 'Alice',
    foo: true,
    bar: true,
    baz: true
  },
  {
    name: 'Bob',
    foo: true,
    bar: true,
    baz: false,
  },
  {
    name: 'Charlie',
    foo: true,
    bar: false,
    baz: false,
  },
  {
    name: 'Danika',
    foo: false,
    bar: false,
    baz: false
  }
]

async function doStuff() {
  await sequelize.sync({force: true})
  await User.bulkCreate(users)

  const defaultscope = await User
    .findAll()
    .then(result => result.map(u => u.name))

  const withBar = await User
    .scope('withBar')
    .findAll()
    .then(result => result.map(u => u.name))

  const withBarAndDefault = await User
    .scope(['defaultScope', 'withBar'])
    .findAll()
    .then(result => result.map(u => u.name))

  const defaultscope2 = await User
    .findAll()
    .then(result => result.map(u => u.name))

  const noBaz = await User
    .scope('noBaz')
    .findAll()
    .then(result => result.map(u => u.name))

  const unscoped = await User
    .unscoped()
    .findAll()
    .then(result => result.map(u => u.name))

  const defaultscope3 = await User
    .findAll()
    .then(result => result.map(u => u.name))

  console.log('defaultscope: ', defaultscope)
  console.log('withBar: ', withBar)
  console.log('withBarAndDefault: ', withBarAndDefault)
  console.log('defaultscope2: ', defaultscope2)
  console.log('noBaz: ', noBaz)
  console.log('unscoped: ', unscoped)
  console.log('defaultscope3: ', defaultscope3)

  process.exit(0)
}

doStuff()
```

## What do you expect to happen?
According to the docs `.scope()` should return a new model with the scope applied, so multiple invocations of `User.scope().findAll()` should have no bearing on each other.

Expected results:
```
defaultscope:  [ 'Alice', 'Bob', 'Charlie' ]
withBar:  [ 'Alice', 'Bob' ]
withBarAndDefault:  [ 'Alice', 'Bob' ]
defaultscope2:  [ 'Alice', 'Bob', 'Charlie' ]
noBaz:  [ 'Bob', 'Charlie', 'Danika' ]
unscoped:  [ 'Alice', 'Bob', 'Charlie', 'Danika' ]
defaultscope3:  [ 'Alice', 'Bob', 'Charlie' ]
```

## What is actually happening?
Instead, later invocations of `User.findAll()` _were_ affected.

Actual results:
```
// correct
defaultscope:  [ 'Alice', 'Bob', 'Charlie' ] 

// correct
withBar:  [ 'Alice', 'Bob' ]

// correct
withBarAndDefault:  [ 'Alice', 'Bob' ] 

// should include 'Charlie'
defaultscope2:  [ 'Alice', 'Bob' ]

 // correct
noBaz:  [ 'Bob', 'Charlie', 'Danika' ]

// correct
unscoped:  [ 'Alice', 'Bob', 'Charlie', 'Danika' ]

// should include 'Charlie'
defaultscope3:  [ 'Alice', 'Bob' ] 
```

__Dialect:__ mysql
__Dialect version:__ XXX  (where do I find this?)
__Database version:__ mysql  Ver 15.1 Distrib 10.3.13-MariaDB, for Linux (x86_64) using readline 5.1
__Sequelize version:__ 5.2.11
__Tested with latest release:__ Yes, 5.2.11 (updated today)

**Comment by WaylonOKC** [comment]
It also is merging and NOT overwriting attributes.  According to the docs:

> When invoking several scopes, keys from subsequent scopes will overwrite previous ones (similarly to Object.assign), except for where and include, which will be merged.

However, I have the following scenario that 1) shows that's not happening and 2) shows the defaultScope is being mutated.

My user model contains the following scopes (modified to show the issue):
```
defaultScope: {
  include: {
    model: sequelize.models.Owner,
    attributes: ["id", "name"]
  },
  attributes: {
    include: ["ownerId"],
    exclude: ["password"]
  }
},
scopes: {
  withPassword: {
    attributes: {
      include: ["password"],
      exclude: ["name"]
    }
  }
}
```

Using the following to view what's happening with the scopes:

```
console.log("DEFAULT SCOPE");
console.dir(db.user.scope("defaultScope")._scope);
    
console.log("PASSWORD SCOPE");
console.dir(db.user.scope("withPassword")._scope);
    
console.log("DEFAULT + PASSWORD SCOPE");
console.dir(db.user.scope("defaultScope", "withPassword")._scope);
    
console.log("DEFAULT SCOPE");
console.dir(db.user.scope("defaultScope")._scope);
```

### What I expect to get
I would expect the attribute.include/exclude to be reversed via replacement and the `defaultScope` not to be altered.
```
DEFAULT SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: [ 'ownerId' ], 
    exclude: [ 'password' ] 
  }
}

PASSWORD SCOPE
{ 
  attributes: { 
    include: [ 'password' ], 
    exclude: [ 'name' ] 
  } 
}

DEFAULT + PASSWORD SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: [ 'password' ],
    exclude: [ 'name' ] 
  } 
}

DEFAULT SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: [ 'ownerId' ],
    exclude: [ 'password' ] 
  } 
}
```

### What I actually get
The attribute.include/exclude are merged and `defaultScope` has been mutated as Robby mentioned.
```
DEFAULT SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: [ 'ownerId' ], 
    exclude: [ 'password' ] 
  }
}

PASSWORD SCOPE
{ 
  attributes: { 
    include: [ 'password' ], 
    exclude: [ 'name' ] 
  } 
}

DEFAULT + PASSWORD SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: [ 'ownerId', 'password' ],
    exclude: [ 'password', 'name' ] 
  } 
}

DEFAULT SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: [ 'ownerId', 'password' ],
    exclude: [ 'password', 'name' ] 
  } 
}
```

**Comment by jorgelf** [comment]
We are having this problem as well.

I'm no expert in Sequelize code, but I'd say the main culprit is method __mergeFunction_ inside _model.js_:
```javascript
static _mergeFunction(objValue, srcValue, key) {
    if (Array.isArray(objValue) && Array.isArray(srcValue)) {
      return _.union(objValue, srcValue);
    }
    if (key === 'where') {
      if (srcValue instanceof Utils.SequelizeMethod) {
        srcValue = { [Op.and]: srcValue };
      }
      if (_.isPlainObject(objValue) && _.isPlainObject(srcValue)) {
        return Object.assign(objValue, srcValue);
      }
    } else if (key === 'attributes' && _.isPlainObject(objValue) && _.isPlainObject(srcValue)) {
      return _.assignWith(objValue, srcValue, (objValue, srcValue) => {
        if (Array.isArray(objValue) && Array.isArray(srcValue)) {
          return _.union(objValue, srcValue);
        }
      });
    }
    return srcValue === undefined ? objValue : srcValue;
}
```
The last line seems to return a reference for each scope parameter (e.g. _where_, _order_) in the first scope that has it instead of copying it, thus modifying the scope itself when merging it with other scopes. I think just modifying that last line to something like this should avoid the problem:
```javascript
    return srcValue === undefined ? objValue : _.clone(srcValue);
```

**Comment by SimonSchick** [comment]
Weird, I can't repro this issue.
Can you create a PR with a test case and your suggested (clone) change?

**Comment by robbyphillips** [comment]
FWIW, it seems like order matters as well.  `.scope(['defaultScope', 'otherScope'])` mutates the defaultScope, but `.scope(['otherScope', 'defaultScope'])` does not.

**Comment by jorgelf** [comment]
Ok, here is an example with an _SQLite_ memory DB (took the code posted by @robbyphillips and modified it, so thanks mate):
```javascript
const Sequelize = require('sequelize')
const sequelize = new Sequelize({
  dialect: 'sqlite'
})

  const User = sequelize.define('User', {
    name: Sequelize.STRING,
    foo: Sequelize.BOOLEAN,
    bar: Sequelize.BOOLEAN,
    baz: Sequelize.BOOLEAN
  }, {});

  User.addScope('defaultScope', {
    where: { foo: true }
  })

  User.addScope('withBar', {
    where: { bar: true }
  })

  User.addScope('noBaz', {
    where: { baz: false }
  })

const users = [
  {
    name: 'Alice',
    foo: true,
    bar: true,
    baz: true
  },
  {
    name: 'Bob',
    foo: true,
    bar: true,
    baz: false,
  },
  {
    name: 'Charlie',
    foo: true,
    bar: false,
    baz: false,
  },
  {
    name: 'Danika',
    foo: false,
    bar: false,
    baz: false
  }
]

async function doStuff() {
  console.log(User._scope)
  
  await sequelize.sync({force: true})
  await User.bulkCreate(users)

  const defaultscope = await User
    .findAll()
    .then(result => result.map(u => u.name))

  const withBar = await User
    .scope('withBar')
    .findAll()
    .then(result => result.map(u => u.name))

  const withBarAndDefault = await User
    .scope(['defaultScope', 'withBar'])
    .findAll()
    .then(result => result.map(u => u.name))

  const defaultscope2 = await User
    .findAll()
    .then(result => result.map(u => u.name))

  const noBaz = await User
    .scope('noBaz')
    .findAll()
    .then(result => result.map(u => u.name))

  const unscoped = await User
    .unscoped()
    .findAll()
    .then(result => result.map(u => u.name))

  const defaultscope3 = await User
    .findAll()
    .then(result => result.map(u => u.name))

  console.log(User._scope)

  process.exit(0)
}

doStuff()
```

It prints the default scope stored inside _User_ before and after the queries, and it always appears modified to me:

```
{ where: { foo: true } }
Executing (default): DROP TABLE IF EXISTS `Users`;
Executing (default): DROP TABLE IF EXISTS `Users`;
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255), `foo` TINYINT(1), `bar` TINYINT(1), `baz` TINYINT(1), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Users`)
Executing (default): INSERT INTO `Users` (`id`,`name`,`foo`,`bar`,`baz`,`createdAt`,`updatedAt`) VALUES (NULL,'Alice',1,1,1,'2019-04-05 18:36:04.700 +00:00','2019-04-05 18:36:04.700 +00:00'),(NULL,'Bob',1,1,0,'2019-04-05 18:36:04.700 +00:00','2019-04-05 18:36:04.700 +00:00'),(NULL,'Charlie',1,0,0,'2019-04-05 18:36:04.700 +00:00','2019-04-05 18:36:04.700 +00:00'),(NULL,'Danika',0,0,0,'2019-04-05 18:36:04.700 +00:00','2019-04-05 18:36:04.700 +00:00');
Executing (default): SELECT `id`, `name`, `foo`, `bar`, `baz`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`foo` = 1;
Executing (default): SELECT `id`, `name`, `foo`, `bar`, `baz`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`bar` = 1;
Executing (default): SELECT `id`, `name`, `foo`, `bar`, `baz`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`foo` = 1 AND `User`.`bar` = 1;
Executing (default): SELECT `id`, `name`, `foo`, `bar`, `baz`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`foo` = 1 AND `User`.`bar` = 1;
Executing (default): SELECT `id`, `name`, `foo`, `bar`, `baz`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`baz` = 0;
Executing (default): SELECT `id`, `name`, `foo`, `bar`, `baz`, `createdAt`, `updatedAt` FROM `Users` AS `User`;
Executing (default): SELECT `id`, `name`, `foo`, `bar`, `baz`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`foo` = 1 AND `User`.`bar` = 1;
{ where: { foo: true, bar: true } }
```
And as @robbyphillips said:

> FWIW, it seems like order matters as well. `.scope(['defaultScope', 'otherScope'])` mutates the defaultScope, but `.scope(['otherScope', 'defaultScope'])` does not.

Yes, the scope order matters. If you have multiple scopes with _where_ parameters, it modifies the first scope inside the array that has that parameter, and same with any other, like _order_. Obviously this isn't a problem if you are using function scopes which return different objects each time they are executed. In that second example you supply I think it's _otherScope_ the one that has been modified instead of the _defaultScope_.

I'm pretty sure this bug is happening because of __mergeFunction_, which should never pass references of _srcValue_, which is the original scope it's merging with _objValue_, the resulting scope merge object to apply to the query.

If all this makes sense to you, I'll make a PR next week changing the last line of that function.

**Comment by robbyphillips** [comment]
Glad that snip was useful @jorgelf !  And thanks for showing me the `._scope` property.  That would have made initially tracking this down a lot nicer for me...

**Comment by papb** [comment]
@jorgelf - I see you suggested using `_.clone`, I have a question related to that: would it be better to use [Utils.cloneDeep](https://github.com/sequelize/sequelize/blob/b6c9117f279d3df19565797ae3fc1be0a1a5eda9/lib/utils.js#L126) instead? What do you think? I've asked myself this question but didn't have much time to think about it.

**Comment by jorgelf** [comment]
You are right, @papb, `_.clone` makes a shallow copy and it's probably safer to create a deep one. Not sure there are actually cases where a shallow copy wouldn't be enough, but better safe than sorry.

I'll make a PR proposing to change that last line to make a deep clone of `srcValue` instead of simply returning it.

**Comment by jorgelf** [comment]
Just a quick note to point out that both [Utils.cloneDeep](https://github.com/sequelize/sequelize/blob/b6c9117f279d3df19565797ae3fc1be0a1a5eda9/lib/utils.js#L126) and Lodash's `_.cloneDeep` raise _JavaScript heap out of memory_ errors when running the tests. My guess is there are some instances where the scopes can contain complex objects that should not be cloned. Avoided this problem by calling Lodash's `_.cloneDeepWith` specifying a function that results in cloning only plain objects.

> Glad that snip was useful @jorgelf ! And thanks for showing me the `._scope` property. That would have made initially tracking this down a lot nicer for me...

After digging a bit more into the code I should make clear that the `._scope` property isn't exactly the _defaultScope_. As far as I understand that class, it contains the scope to apply in the next query, which should reference the _defaultScope_ (if we defined one) under normal circumstances. If you want to make sure you are checking the _defaultScope_, it's usually better to check `.options.defaultScope`. In the provided example, both attributes work the same.
You can also check other scopes through `.options.scopes[<scope_name>]` (the _defaultScope_ is not included inside that object).

**Comment by WaylonOKC** [comment]
This does not fix the issue of it merging the attributes that I mentioned [above](https://github.com/sequelize/sequelize/issues/10696#issuecomment-479695327). Would you like me to open a separate ticket for that?

**Comment by jorgelf** [comment]
You are right, @WaylonOKC, that problem is still happening and though its cause it's probably located in the same functions, looks unrelated to the scope overwriting. I'd say it's happening again because of `Model._mergeFunction`. If we look around line [804](https://github.com/sequelize/sequelize/blob/47c5f30f926577658fafabef93e35881ce5aeb07/lib/model.js#L804):
```
    } else if (key === 'attributes' && _.isPlainObject(objValue) && _.isPlainObject(srcValue)) {
      return _.assignWith(objValue, srcValue, (objValue, srcValue) => {
        if (Array.isArray(objValue) && Array.isArray(srcValue)) {
          return _.union(objValue, srcValue);
        }
      });
```
It's clearly mixing the _attributes_ objects by merging its inner arrays, which is the problem you are having (non-array properties are actually overwritten as you expect). Maybe it's a bug, though it looks like a very explicit block of code to me. Probable better to wait for a core developer to shed some light onto this.

**Comment by papb** [comment]
@WaylonOKC - I suggest you open a new issue about that, and add a link to this one. You can probably just copy-paste [your comment](https://github.com/sequelize/sequelize/issues/10696#issuecomment-479695327) for the new issue.

**Comment by hsynlms** [comment]
Seems this issue consists of 2 parts and seems only one of both was fixed. How about unioning arrays in the options? I am not able to overwrite default scope's `order` option by giving `order ` option in the query.

So it breaks flexibility. Using lodash union method causes that issue in `_mergeFunction`. I will propose a PR about a possible fix.

### What I expect to get ###
```
PRODUCT'S DEFAULT SCOPE
{ 
  order: [
    ['displayOrder', 'ASC']
  ]
}

PRODUCT SCOPE IN THE QUERY
{ 
  order: [
    ['price', 'ASC']
  ]
}

LATEST SCOPE RESULT
{ 
  order: [
    ['price', 'ASC']
  ]
}
```

### What I actually get ###
```
PRODUCT'S DEFAULT SCOPE
{ 
  order: [
    ['displayOrder', 'ASC']
  ]
}

PRODUCT SCOPE IN THE QUERY
{ 
  order: [
    ['price', 'ASC']
  ]
}

LATEST SCOPE RESULT
{ 
  order: [
    ['displayOrder', 'ASC'],
    ['price', 'ASC']
  ]
}
```
