### ISSUE TITLE
Method name 'toJSON' should rename as 'toPlain'

### ISSUE THREAD

**Issue by s79** [sequelize/sequelize#10698]
[File: lib/model.js
](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L4226)
```
  /**
   * Convert the instance to a JSON representation. Proxies to calling `get` with no keys. This means get all values gotten from the DB, and apply all custom getters.
   *
   * @see {@link Model#get}
   * @return {object}
   */
  toJSON() {
    return _.clone(
      this.get({
        plain: true
      })
    );
  }

```
This method should return a JSON string, that's make sense, but not a plain Object.
Change it's name to toPlain is better.

**Comment by devoto13** [comment]
[toJSON name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior) has a special meaning.

**Comment by SimonSchick** [comment]
@dovoto13 is right, it's also clearly documented.

**Comment by s79** [comment]
In general, JSON should be a string, not a plain object, So toJSON should return a string...

**Comment by SimonSchick** [comment]
This is not going to change, please see @devoto13's comment.

**Comment by s79** [comment]
You're right. I misunderstand.
