### ISSUE TITLE
[MSSQL] yarn sequelize db:migrate ERROR: Login failed for user ''. 

### ISSUE THREAD

**Issue by vaibhav6233m** [sequelize/sequelize#10700]
## What are you doing?

```js
  development: {
    username: 'xxx',
    userName: 'xxx',
    user: 'xxx',
    password: 'xxx',
    database: 'Test3',
    host: '127.0.0.1',
    dialect: 'mssql',
    port: 1433,
  },
```
```bash
```
## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Report CLI issues to https://github.com/sequelize/cli please, `login failed for user` means your credentials are incorrect

**Comment by vaibhav6233m** [comment]
Hi, @sushantdhiman I accidentally posted incomplete issue. Please check the updated issue. Thanks.

**Comment by Royalsspirit** [comment]
Same issue is occured in my side with latest version of tedious. 
I created an issue in tedious repository thinking that is on their side. Finally, connection work well with updated object configuration but it sill don't work with sequelize. You can see more details [here](https://github.com/tediousjs/tedious/issues/890)

**Comment by moemar** [comment]
Any news on this? I still get the same error with blank username.
```
"sequelize": "^4.39.0"
"tedious": "^6.2.0"
```

**Comment by papb** [comment]
@moemar can you try a connection URI instead?
