### ISSUE TITLE
Sequelize upgrade v3 to 4 docs link does not work

### ISSUE THREAD

**Issue by TheVedhaGuy** [sequelize/sequelize#10706]
I tried to access the upgrade doc link and it returns a 404

http://docs.sequelizejs.com/manual/upgrade-to-v4.html#breaking-changes

Has this been moved?

**Comment by chrisgo** [comment]
Try this https://github.com/sequelize/sequelize/blob/v4/docs/upgrade-to-v4.md

**Comment by TheVedhaGuy** [comment]
Thanks @chrisgo, any idea why it was removed from the sequelize docs?

**Comment by papb** [comment]
This was a indeed mistake, it is now available [here](https://sequelize.org/v4/manual/tutorial/upgrade-to-v4.html).
