### ISSUE TITLE
increment shows sql error after use scope query

### ISSUE THREAD

**Issue by 7insummer** [sequelize/sequelize#10719]
## What are you doing?
I just want increment field of  a model instance after scope query.
see codes below:

```js
Movie.scope('bh').findOne({where:{id:1}}).then(movie=>{
movie.increment('fav_nums',{by:1})
})
```

bh is name of a scope，defined by code below：
```js
  scopes: {
            bh: {
                attributes: { exclude: ['created_at', 'updated_at','deleted_at'] }
            }
        }
```

## What do you expect to happen?
when query ，i need this scope to exclude some attributes，after query，i just want increment a field of model instance 。but see the sql below，wrong sql generated。

## What is actually happening?
very simple code ,but will cause sql errors。because the code above will be translated into sqls like this:

```sql
UPDATE movie SET fav_nums=fav_nums+ 1,exclude='created_at', 'updated_at', 'deleted_at',updated_at='2019-01-21 15:59:18' WHERE id = 1
```

Obviously，the sql is wrong。

__Dialect:__ mysql
__Dialect version: 
__Database version:5.6
__Sequelize version: 5.2.12
__Tested with latest release:yes，5.2.12

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Similar https://github.com/sequelize/sequelize/issues/10411 , https://github.com/sequelize/sequelize/issues/9572

**Comment by ALiangLiang** [comment]
reproduce: https://github.com/ALiangLiang/sequelize/commit/be036536028b4cee28ac08b2c63e2f94070fb139

**Comment by mhio** [comment]
Same problem in sqlite
```
  defaultScope: {
    attributes: { exclude: ['no'] },
  },
```
```
Executing (default): UPDATE `fives` SET `count`=`count`+ 1,`exclude`='no',`updated_at`='2019-11-13 02:04:09.956 +00:00' WHERE `id` = '63cb2731-0dd7-4c1e-9aef-b6f65201301f'
(node:75249) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: SQLITE_ERROR: no such column: exclude
    at Query.formatError (/project/node_modules/sequelize/lib/dialects/sqlite/query.js:422:16)
    at Query._handleQueryResponse (/project/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
    at afterExecute (/project/node_modules/sequelize/lib/dialects/sqlite/query.js:250:31)
    at Statement.errBack (/project/node_modules/sqlite3/lib/sqlite3.js:16:21)
```
