### ISSUE TITLE
Model with belongsTo relationship in typescript

### ISSUE THREAD

**Issue by alexnfsc175** [sequelize/sequelize#10715]
## when I try to start the application

```js
/usr/app/node_modules/sequelize/lib/associations/mixin.js:93
      throw new Error(`${source.name}.${_.lowerFirst(Type.name)} called with something that's not a subclass of Sequelize.Model`);
      ^

Error: Comment.belongsTo called with something thats not a subclass of Sequelize.Model
    at Function.<anonymous> (/usr/app/node_modules/sequelize/lib/associations/mixin.js:93:13)
    at Object.<anonymous> (/usr/app/dist/src/api/server/models/Comment.js:24:9)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/app/dist/src/api/server/models/User.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/app/dist/src/api/server/routes/products.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
```

## my classes
_User_
```ts
import {
  Model,
  Sequelize,
  DataTypes,
  Association,
  BuildOptions,
  HasManyAddAssociationMixin,
  HasManyHasAssociationMixin,
  HasManyGetAssociationsMixin,
  HasManyCountAssociationsMixin,
  HasManyCreateAssociationMixin
} from 'sequelize';
import { Comment } from './Comment';
import { sequelize } from './db';
export class User extends Model {

  id?: number;
  name: string;




  // timestamps!
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // Since TS cannot determine model association at compile time
  // we have to declare them here purely virtually
  // these will not exist until `Model.init` was called.

  public getComments: HasManyGetAssociationsMixin<Comment>;
  public addComment: HasManyAddAssociationMixin<Comment, number>;
  public hasComment: HasManyHasAssociationMixin<Comment, number>;
  public countComments: HasManyCountAssociationsMixin;
  public createComment: HasManyCreateAssociationMixin<Comment>;

  // You can also pre-declare possible inclusions, these will only be populated if you
  // actively include a relation.
  public readonly comments?: Comment[];

  public static associations: {
    comments: Association<User, Comment>;
  };
}
User.init({
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    autoIncrement: true,
    primaryKey: true,
  },
  name: {
    type: new DataTypes.STRING(128),
    allowNull: false,
  }
}, {
    sequelize, // this bit is important
    tableName: 'users',
  });

// Here we associate which actually populates out pre-declared `association` static and other methods.
User.hasMany(Comment, {
  foreignKey: 'author',
  as: 'comments' // this determines the name in `associations`!
});

```
_Comments_

```ts
import {
  Model,
  Sequelize,
  DataTypes,
  Association,
  BuildOptions,
  HasManyAddAssociationMixin,
  HasManyHasAssociationMixin,
  HasManyGetAssociationsMixin,
  HasManyCountAssociationsMixin,
  HasManyCreateAssociationMixin,
  BelongsToManyCreateAssociationMixin,
  BelongsToManySetAssociationsMixin,
  BelongsToManyAddAssociationsMixin,
  BelongsToManyAddAssociationMixin,
  BelongsToManyRemoveAssociationMixin,
  BelongsToManyRemoveAssociationsMixin,
  BelongsToManyHasAssociationMixin,
  BelongsToManyHasAssociationsMixin,
  BelongsToManyCountAssociationsMixin
} from 'sequelize';
import { User } from './User';
import { sequelize } from './db';


export class Comment extends Model {

  id?: number;
  text: string;




  // timestamps!
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // Since TS cannot determine model association at compile time
  // we have to declare them here purely virtually
  // these will not exist until `Model.init` was called.

  public getUpvoters: HasManyGetAssociationsMixin<User>;
  public setUpvoters: BelongsToManySetAssociationsMixin<User, User['id']>;
  public addUpvoters: BelongsToManyAddAssociationsMixin<User, User['id']>;
  public addUpvoter: BelongsToManyAddAssociationMixin<User, User['id']>;
  public createUpvoters: BelongsToManyCreateAssociationMixin<User>;
  public removeUpvoter: BelongsToManyRemoveAssociationMixin<User, User['id']>;
  public removeUpvoters: BelongsToManyRemoveAssociationsMixin<User, User['id']>;
  public hasUpvoter: BelongsToManyHasAssociationMixin<User, User['id']>;
  public hasUpvoters: BelongsToManyHasAssociationsMixin<User, User['id']>;
  public countUpvoters: BelongsToManyCountAssociationsMixin;

  // Você também pode pré-declarar possíveis inclusões, elas só serão preenchidas se você
  // incluir ativamente uma relação.
  public readonly upvoters?: User[];
  public readonly author?: User;

  public static associations: {
    upvoters: Association<User, Comment>;
    author: Association<Comment, User>;
  };
}

Comment.init({
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    autoIncrement: true,
    primaryKey: true,
  },
  text: {
    type: new DataTypes.STRING(128),
    allowNull: false,
  }
}, {
    sequelize, // this bit is important
    tableName: 'comments',
  });

// Here we associate which actually populates out pre-declared `association` static and other methods.
Comment.belongsTo(User, { 
  foreignKey: 'id',
  targetKey: 'id',
  as: 'author' // this determines the name in `associations`!
});
// console.log(User);

```

## User class always seems to be null
```ts
Comment.belongsTo(User, { 
  foreignKey: 'id',
  targetKey: 'id',
  as: 'author' // this determines the name in `associations`!
});
```
## my  package.json
```json
  "dependencies": {
    "koa": "^2.7.0",
    "koa-mount": "^4.0.0",
    "koa-router": "^7.4.0",
    "nodemon": "^1.18.10",
    "pg": "^7.9.0",
    "pg-hstore": "^2.3.2",
    "sequelize": "^5.2.12",
    "ts-node": "^8.0.3",
    "tslint": "^5.15.0",
    "typescript": "^3.4.1"
  },
  "devDependencies": {
    "@types/koa": "^2.0.48",
    "@types/koa-mount": "^3.0.1",
    "@types/koa-router": "^7.0.40",
    "@types/node": "^11.11.3",
    "tslint-clean-code": "^0.2.9"
  }
```
## Any other way to load relationships between classes into separate files?

_Output, either JSON or SQL_

__Dialect:__ postgres
__Dialect version:__ 7.9.0
__Database version:__ postgres:11.2
__Sequelize version:__ 5.2.12

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
This sounds like you have a cycling dependency, try moving the associations into a separate file.

**Comment by peabnuts123** [comment]
Just posting this around on all these similar issues; I ran into this error because i was importing my Models from another folder i.e. the file where my model was defined was importing `sequelize` from a different node_modules. This meant that the `instanceof` check was false because, even though my models WERE inheriting from `Model` from `sequelize` - it was a different class, technically (with all the same properties and attributes). 

You can think of a `foo instanceof MyClass` check as comparing the prototype of `foo` all the way up the chain e.g. `foo.__proto__ === MyClass.prototype`, `foo.__proto__.__proto__ === MyClass.prototype` etc. until either `__proto__` is `null` (in which case `instanceof = false`) or the `===` equality check is true (in which case `instanceof = true`). So this is why a different instance of the `Sequelize.Model.prototype` object would return `false` for an `instanceof` check. 

This is a pretty unique scenario so I solved it by symlinking the `node_modules` from my database project to my "shared code" project. Just wanted to post this in case anybody else was doing a similar thing, in an attempt to save somebody from a couple of hours of WTFing.

**Comment by Narsinhs** [comment]
Hi, I am using sequelize-typescript and trying to use @belongTo One-to-Many not returning  reponse in object properly as TYPEORM anyone can help.?

` public async findOne(whereParams, raw = true, include = [] as any): Promise<T> {
        return await this.Repository.findOne<T>({ where: whereParams, raw: raw, include: [{ model: sequelize.models.UserModel, as: "user",foreignKey : "user_id" }] });
    }`

response 
`{
  Id: 1,
  EmojiUrl: 'string',
  Name: 'string',
  userId: 1,
  createdAt: 2020-12-24T13:59:43.000Z,
  updatedAt: 2020-12-24T13:59:43.000Z,
  user_id: 1,
  'user.Id': 1,
  'user.Pincode': 2243,
  'user.ExpiryPincode': 1608825579421,
  'user.SystemGeneratedPassword': null,
  'user.Email': 'user@example.com',
  'user.Password': '$2b$10$wHuuXi8unMhklqS6ZWO9IeorGQrfucoMeQvzElPXQshzHb7oJ6fym',
  'user.UserStatus': 3,
  'user.UserType': 0,
  'user.Name': null,
  'user.ProfileImage': null,
  'user.createdAt': 2020-12-24T13:59:39.000Z,
  'user.updatedAt': 2020-12-24T13:59:39.000Z
}`
want response Like  -->
`{
  Id: 1,
  EmojiUrl: 'string',
  Name: 'string',
  userId: 1,
  createdAt: 2020-12-24T13:59:43.000Z,
  updatedAt: 2020-12-24T13:59:43.000Z,
  user_id: 1,
'user' : {
'user.Id': 1,
  'Pincode': 2243,
  'ExpiryPincode': 1608825579421,
  'SystemGeneratedPassword': null,
  'Email': 'user@example.com',
  'Password': '$2b$10$wHuuXi8unMhklqS6ZWO9IeorGQrfucoMeQvzElPXQshzHb7oJ6fym',
  'UserStatus': 3,
  'UserType': 0,
  'Name': null,
  'ProfileImage': null,
  'createdAt': 2020-12-24T13:59:39.000Z,
  'updatedAt': 2020-12-24T13:59:39.000Z
}
  `
}

**Comment by nbkhope** [comment]
@peabnuts123 I have a project that defines some models as a separate npm package. When I import those models in my project and start my application, I get an error when it calls `.associate`:

```
Error: ModelNameGoesHere.hasMany called with something that's not a subclass of Sequelize.Model
```

`ModelNameGoesHere` is a model that is defined in a separate npm package. That is, it comes from

```
import ModelNameGoesHere from 'some-separate-npm-package'
```

When I copy the code from the package into my application, the problem goes away.

Is there any solution to this?

**Comment by peabnuts123** [comment]
@nbkhope Sorry it's been a long time, I haven't checked my GitHub in a while. You've maybe solved your problem but the only thing I can think of off the top of my head is that your `some-separate-npm-package` has a different version of `sequelize` as its dependency and is thus still importing from a different package.

**Comment by Viditjoshi** [comment]
const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
const Product = require('./Product');

const Question = sequelize.define('Question', {
  id: {
    type: DataTypes.INTEGER,
    autoIncrement: true,
    primaryKey: true,
    allowNull: false,
  },
  product_id: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Products', 
      key: 'id',
    },
    onDelete: 'CASCADE', 
  },
  questions: {
    type: DataTypes.JSON,  
    allowNull: false,
  },
}, {
  timestamps: true,
  tableName: 'Questions',
});

Question.belongsTo(Product, {
  foreignKey: 'product_id',
  
});

module.exports = Question;
const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
const Question = require('./Questions'); 

const Product = sequelize.define('Product', {
    id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
    },
    name: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    price: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: false,
    },
    description: {
        type: DataTypes.TEXT,
    },
    category: {
        type: DataTypes.STRING,
        allowNull: false,
    },
});

Product.hasMany(Question, {
    foreignKey: 'product_id',               
    onDelete: 'CASCADE',
});

module.exports = Product;



Error: Question.belongsTo called with something that's not a subclass of Sequelize.Model
    at Question.<anonymous> (/Users/vt/StickerWebsite/backend/node_modules/sequelize/lib/associations/mixin.js:63:13)
    at Object.<anonymous> (/Users/vt/StickerWebsite/backend/models/Questions.js:30:10)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/vt/StickerWebsite/backend/models/Product.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

Node.js v20.11.1
[nodemon] app crashed - waiting for file changes before starting...
