### ISSUE TITLE
modelInstance.isSoftDeleted() erroneously returns true right after creating the instance

### ISSUE THREAD

**Issue by saifulss** [sequelize/sequelize#10714]
## What are you doing?

```js
it('should soft-delete record when destroy is called', async () => {
    const user = await User.create({
      firstName: 'xxx',
      lastName: 'yyy',
      email: 'xxx@example.com',
    });
    console.log(user.isSoftDeleted());    // true
}
```

## What do you expect to happen?
_Right after creating the user record, user.isSoftDeleted() should be false._

## What is actually happening?
_It returns true instead._

__Dialect:__ mysql
__Dialect version:__ ?
__Database version:__ mysql:5.7.22
__Sequelize version:__ ^5.2.12
__Tested with latest release:__ Yes (5.2.12)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
We need more info here, please post a full repro including the model definition etc.

**Comment by sushantdhiman** [comment]
Bug with `MySQL` but may also affect other dialects which do no support returning on insert.

Can be fixed by setting `deletedAt` default value to `null` when building instance OR fix `isSoftDeleted` check to take care of undefined `deletedAt` value.

Users can temporarily fix this by passing `deletedAt: null` or calling `reload` on created instance

**SSCCE**

```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

(async () => {
  class Model extends Sequelize.Model {}

  Model.init({
    firstName: Sequelize.STRING,
    lastName: Sequelize.STRING
  }, {
    sequelize,
    paranoid: true
  });

  await Model.sync({ force: true });

  const m = await Model.create({
    firstName: 'abc'
  });

  console.log(await m.isSoftDeleted());
})();
```

**Comment by sushantdhiman** [comment]
Fixed with https://github.com/sequelize/sequelize/pull/10799
