### ISSUE TITLE
Models methods are building query with wrong table name. (Camel Case)

### ISSUE THREAD

**Issue by frnk94** [sequelize/sequelize#10717]
## What are you doing?

- created a model/migrations using CLI
`sequelize model:create --name User --attributes first_name:STRING`
- querying that model (```findAll() ```)

## What do you expect to happen?
Receive data from database.

## What is actually happening?
The ORM Raw querry is querying the wrong table because it doesn't put the uppercase.
relation \"users\" does not exist

```sql
SELECT "id", "first_name", "created_at" AS "createdAt", "updated_at" AS "updatedAt", "deleted_at" AS "deletedAt" FROM "users" AS "User" WHERE ("User"."deleted_at" IS NULL);
```

it should:
```sql
FROM "Users" AS "User"
```

__Dialect:__ postgres 
__Sequelize version:__ 5.2.8

**Comment by dsmackie** [comment]
Can you please paste the model that has been created by the CLI.

**Comment by frnk94** [comment]
@dsmackie
```js
'use strict';
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    first_name: DataTypes.STRING
    
  }, {});
  User.associate = function(models) {
    // associations can be defined here
  };
  return User;
};
```

this was created by running:
`sequelize model:create --name User --attributes first_name:STRING`

**Comment by sushantdhiman** [comment]
This definition is missing paranoid, timestamps etc. Are you defining them globally when sequelize is initialized? Can we see what config you are using for initializing Sequelize

**Comment by kshitijpurwar** [comment]
Facing the same issue. Found a workaround by defining the appropriate `tableName` in the model definition.

**Comment by createthis** [comment]
👍 seeing the same thing in 5.12.2 and 5.15.1 using https://github.com/nielsgl/sequelize-paper-trail

What's really weird is that for the same code base deployed on different working copies on the same machine and other machines, I am seeing different default behavior.

Sometimes sequelize outputs `revisions` and sometimes it outputs `Revisions` for the table name. Setting `tableName` manually fixes it, but it's really weird that it isn't consistent.

**Comment by papb** [comment]
I was unable to reproduce, using the code posted above.

```js
const User = sequelize.define('User', {
  first_name: DataTypes.STRING
}, {});
```

The call works for me correctly, with `"Users"` in uppercase.

```js
sequelize.sync().then(() => User.findAll());
```

```sql
SELECT `id`, `first_name`, `createdAt`, `updatedAt` FROM `Users` AS `User`;
```

Can anyone please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))?

**Comment by createthis** [comment]
I put something together to reproduce this. It would be super useful to provide bug reporters with a basic SSCCE environment for this sort of thing in the future. It is fairly time consuming to create one from scratch. Something like a jsfiddle would be ideal.

In my particular case, this happens because of the change in the behavior of the `underscored` attribute in v5+. See https://github.com/sequelize/sequelize/issues/6423#issuecomment-379472035

Check it out: https://github.com/createthis/repro_sequelize_issue_10717

If people are seeing this problem without `underscored: true`, feel free to fork my branch and change it to demonstrate your use case.
