### ISSUE TITLE
Types missing `.models` usage with import vs require

### ISSUE THREAD

**Issue by eddiemonge** [sequelize/sequelize#10728]
## What are you doing?
Trying to use `.models` property on a Sequelize instance when using TypeScript according to the docs at http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-member-models

If I `import` Sequelize, I get:

```
import { Sequelize } from 'sequelize'

Property 'models' does not exist on type 'Sequelize'. Did you mean 'model'?
```

If I use require, it works.

```
const Sequelize = require('sequelize').Sequelize;
```

Full sample code

`app.ts`
```js
const Sequelize = require('sequelize').Sequelize;
// import { Sequelize } from 'sequelize'

const sequelize = new Sequelize('db', 'dbUser', 'dbPass', {
  host: 'db',
  dialect: 'postgres'
});

Object.keys(sequelize.models)
```

`package.json`
```json
{
  "scripts": {
    "start": "ts-node app.ts"
  },
  "dependencies": {
    "sequelize": "^5.2.13",
    "ts-node": "^8.0.3",
    "typescript": "^3.4.2"
  }
}
```

**Comment by SimonSchick** [comment]
I'm sorry I cannot reproduce your issue, there is no definition for `models` in the typings, please provide a full, code sample, not just excerpt.

I don't believe this is related to #10681 at all.

**Comment by eddiemonge** [comment]
I created a repo that shows the problem: https://github.com/eddiemonge/sequelize-10728

I assumed it was 5.2.9 because in my actual code, I could remove the `version?: ...` typing and it then worked but I can't reproduce that using my sample repo.

**Comment by SimonSchick** [comment]
Mhh, I mean, we could add `models` to the instance with the signature `models: { [key: string]: typeof Model }`, I didn't do this before as reduces type safety and you'd have to cast to the right model type all the time.
