### ISSUE TITLE
Comment ALTER Query Error

### ISSUE THREAD

**Issue by knighthell** [sequelize/sequelize#10720]
## What are you doing?

```
module.exports = (sequelize, DataTypes) => sequelize.define('UserPlace', {
    isVisited: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
        comment: 'check visited place'
    }
}, {
    timestamps: true,
    paranoid: true,
    associate: function (model) {

    },
    indexes: []
});
```

## What do you expect to happen?
ALTERED MODEL

## What is actually happening?
SQL Error about ALTER COMMENT
{
error: syntax error at or near "COMMENT",
sql:
   'ALTER TABLE "UserPlaces" ALTER COLUMN "isVisited" SET NOT NULL;ALTER TABLE "UserPlaces" ALTER COLUMN "isVisited" SET DEFAULT false COMMENT check visited place;ALTER TABLE "UserPlaces" ALTER COLUMN "isVisited" TYPE BOOLEAN;' 
}

__Dialect:__ postgres
__Dialect version:__ ^7.9.0
__Database version:__ 9.6, 11(latest) with PostGIS
__Sequelize version:__ 5.2.12
__Tested with latest release:__ Yes (If yes, specify that version)

on postgres 9.6
SQL Query is NOT able to ALTER COMMENT
```
ALTER TABLE "UserPlaces"
  ALTER COLUMN "isVisited" SET DEFAULT false COMMENT 'comment content text';
```
--> This Query is able to ALTER COMMENT
```
ALTER TABLE "UserPlaces"
  ALTER COLUMN "isVisited" SET DEFAULT false;
COMMENT ON COLUMN "UserPlaces"."isVisited" IS  'comment content text';
```
![image](https://user-images.githubusercontent.com/1873884/55706722-dfb0c980-5a1c-11e9-8599-9b3e5ed18e64.png)

**Comment by mirkojotic** [comment]
Hi @knighthell we introduced comments not too long ago and I think the scope of it at the time was to only allow for comments when table was created (so no alter functionality) and I think the docs reflect this (if not I'll make a PR to docs first and make sure it's clear) . However I'm willing to implement this so I'll be taking a look.
