### ISSUE TITLE
Sequelize expecting Integer despite of making the type for the field as Float.

### ISSUE THREAD

**Issue by BikalNepal** [sequelize/sequelize#10735]
I'm trying to create a table using the model I have made using Sequelize.
```js
//Model:
const Sequelize = require("sequelize");
const sequelize = new Sequelize({
  database: process.env.PGDATABASE,
  username: process.env.PGUSER,
  password: process.env.PGPASS,
  host: process.env.PGHOST,
  port: process.env.PGPORT,
  dialect: "postgres"
});

var MessageRating = sequelize.define(
  "MessageRating",
  {
    chatId: {
      type: Sequelize.STRING,
      primaryKey: true,
      allowNull: false
    },
    ratingType: {
      type: Sequelize.ENUM,
      values: ["NEGATIVE", "POSITIVE", "NEUTRAL", "MIXED"],
      allowNull: false
    },
    rating: {
      type: Sequelize.FLOAT,
      allowNull: false
    }
  },
  {
    indexes: [
      {
        unique: false,
        fields: ["ratingType"]
      }
    ]
  }
);

module.exports = MessageRating;
```

## What do you expect to happen?
I wanted to save all the fields as defined in the types in the model.

## What is actually happening?
But, the rating field always expects an integer. I have made it to be Sequelize.FLOAT, but it throws an error as seen in the link below:
https://gist.github.com/BikalNepal/51fd28f877b422fcc16825d61cd95847

The code I'm using to create the table is such:
```
var messageRatingStored = sequelize
          .sync()
          .then(() =>
            MessageRating.create({
              chatId: chatId,
              ratingType: amazonComprehendResult.ResultList[0].Sentiment,
              rating: roundOffRating
            })
          )
          .then(messageRating => {
            console.log("MessageRating json", messageRating.toJSON());
          });
```
When I put a static integer value (82, 10 etc) in the rating field, instead of roundOffRating which will always give decimal, then I get no errors and it saves properly.

__Dialect:__ postgres 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
Can you please post a self contained reproduction case?

**Comment by SimonSchick** [comment]
Cool
