### ISSUE TITLE
Scope attributes merging rather than overwritten

### ISSUE THREAD

**Issue by WaylonOKC** [sequelize/sequelize#10742]
## What are you doing?
When using multiple scopes, the attributes are being merged rather overwritten.
According to the docs:

> When invoking several scopes, keys from subsequent scopes will overwrite previous ones (similarly to Object.assign), except for where and include, which will be merged.

However, I have the following scenario that shows that's not happening.

My user model contains the following scopes (modified to show the issue):

```js
defaultScope: {
  include: {
    model: sequelize.models.Owner,
    attributes: ["id", "name"]
  },
  attributes: {
    include: ["id", "firstName", "ownerId"],
    exclude: ["password"]
  }
},
scopes: {
  withPassword: {
    attributes: {
      include: ["id", "ownerId", "password"],
      exclude: [ "firstName" ]
    }
  }
}
```

Using the following to view what's happening with the scopes:
```js
console.log("DEFAULT SCOPE");
console.dir(db.user.scope("defaultScope")._scope);
    
console.log("PASSWORD SCOPE");
console.dir(db.user.scope("withPassword")._scope);
    
console.log("DEFAULT + PASSWORD SCOPE");
console.dir(db.user.scope("defaultScope", "withPassword")._scope);
```

## What do you expect to happen?
I would expect the attribute.include/exclude to be overwritten and contain what is in the password scope. 
```js
DEFAULT SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: ['id', 'firstName', 'ownerId' ], 
    exclude: ['password'] 
  }
}

PASSWORD SCOPE
{ 
  attributes: { 
    include: ['id', 'ownerId', 'password' ], 
    exclude: ['firstName'] 
  } 
}

DEFAULT + PASSWORD SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
     include: ['id', 'ownerId', 'password' ], 
     exclude: ['firstName'] 
  } 
}
```

## What is actually happening?
The attribute.include/exclude are merged
```js
DEFAULT SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: ['id', 'firstName', 'ownerId' ], 
    exclude: ['password'] 
  }
}

PASSWORD SCOPE
{ 
  attributes: { 
    include: ['id', 'ownerId', 'password' ], 
    exclude: ['firstName'] 
  } 
}

DEFAULT + PASSWORD SCOPE
{ 
  include: [ { model: [Function], attributes: [Array] } ],
  attributes: { 
    include: ['id', 'firstName', 'ownerId', 'password' ], 
    exclude: ['password', 'firstName'] 
  }
}
```

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.2.11
__Tested with latest release:__ Yes.  5.2.15

First mentioned in https://github.com/sequelize/sequelize/issues/10696

**Comment by sushantdhiman** [comment]
Attribute merging is correct here, I remember this discussion. Our goal was to let users merge various attributes so exclude are always preserved.

Consider you applied two scope, one includes `password` attribute and other excludes `password` attribute, I expect `password` will still be excluded not accidentally leaked in final scope.

This is how it works now, merge both include and exclude separately from all scopes being applied. Final `options.attributes` will be based on those merged include and exclude attributes

Tagging this as documentation change

**Comment by sushantdhiman** [comment]
Now there is a note about attributes merging as well

**Comment by tutok** [comment]
looks like `attriutes: []` can overdrive  `attributes: [include [] ]` defined on scope level, I believe this is an issue.
