### ISSUE TITLE
startsWith and endsWith operators are reversed

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#10743]
## What are you doing?

https://github.com/sequelize/sequelize/pull/9999 introduced the `startsWith` and `endsWith` operators, but they seem to be reversed:

![image](https://user-images.githubusercontent.com/610129/55835818-6f6c7b80-5ae2-11e9-8b8c-e5c44d454418.png)

## What do you expect to happen?
`[Op.startsWith]: 'hat'` should be defined as `hat%`, i.e. the string begins with `hat` and then has anything afterwards.

`[Op.endsWith]: 'hat'` should be defined as `%hat`, i.e. the string begins with anything but ends with `hat`.

## What is actually happening?

`startsWith` and `endWith` are the reverse of what I expect. The [unit tests for this feature](https://github.com/sequelize/sequelize/blob/3dbb318ed6a603bd87284c8edfceabe760e9baf8/test/unit/sql/where.test.js#L437-L453) exhibit the same behavior.

__Dialect:__  any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ master
__Tested with latest release:__ yes

**Comment by ferfabricio** [comment]
Sorry I'd not see this in my work, I'll fix this ASAP
