### ISSUE TITLE
model.count doesn't always return a Promise<number>

### ISSUE THREAD

**Issue by mjdavidson** [sequelize/sequelize#10757]
https://github.com/sequelize/sequelize/blob/728707cda2de842439130a6e7a20be0e36c8a91b/types/lib/model.d.ts#L1751

if you use group/attributes it will return an array of objects

**Comment by SimonSchick** [comment]
Could you add a specific overload that when `group` is defined it yields `{ [key: string]: number }`?

You'd have to create an interface like `interface CountWithOptions extends CountOptions { group:/*note the lack of ?*/ GroupOptions/*or whatever it was called*/ }`

**Comment by mjdavidson** [comment]
The fix is incorrect. It should be { [key:string]: number }[],
also if you group by multiple columns this should be accounted for,

eg:
```ts
const observations = await Observation.count({
  include: [
    {
      model: User,
      association: 'createdBy',
      attributes: ['id', 'name', 'avatar']
    },
  ],
  attributes: ['createdBy.name', 'createdBy.color', 'createdBy.id'],
  group: ['createdBy.name', 'createdBy.color', 'createdBy.id']
});
```
returns 
```json
[ { "name": "Matt Davidson",                                                   
    "color": "#0000",                                                           
    "id": "aa6776b8-d402-4817-8335-d12257d13df4",                                
    "count": "1" } ]      
```
Note that count is not a number it's actually a string

**Comment by mjdavidson** [comment]
@sushantdhiman

**Comment by DG-Wangtao** [comment]
Maybe it should be 
```
Promise<{ [key: string]: object }>
```

**Comment by papb** [comment]
@mjdavidson Is this still an issue?

**Comment by mjdavidson** [comment]
don't think so, 
https://github.com/sequelize/sequelize/blob/v5.10.3/types/lib/model.d.ts#L1811
stopped using sequelize with typescript... was 'too hard basket'
