### ISSUE TITLE
(mysql) BIGINT gets stored with incorrect precision after upgrading to v5

### ISSUE THREAD

**Issue by jozsefsallai** [sequelize/sequelize#10765]
## What are you doing?
After upgrading to v5.3.0, some of the BIGINTs created with Sequelize are added with incorrect precision. The exact same code works with older versions (i.e. v4.43.0). Here's a repro of the issue: https://github.com/jozsefsallai/sequelize-create-bigint-precision-repro

I'm not sure if I'm missing something or if I had looked over an upgrade guideline but I couldn't figure it out why the same code worked in v4 but doesn't work in v5. 

## What do you expect to happen?
Expecting 245890903133257730 to be inserted.

## What is actually happening?
The inserted value is 245890903133257728. (last two digits are different).

__Dialect:__ mysql
__Dialect version:__ v1.6.5
__Database version:__ mysql Ver 14.14 Distrib 5.7.25
__Sequelize version:__ v5.3.x
__Tested with latest release:__ Yes

**Comment by SimonSchick** [comment]
Could you perhaps perform a bisect to figure out what exactly changed this?
IIrc all bigint values should always be treated as strings

**Comment by mirkojotic** [comment]
I've dag around quite a bit to understand what's happening here and couldn't find an obvious reason why this would be happening. 
I've managed to reproduce the issue in our tests with:
```
    it('bigint precision off when using int instead of string', function() {
      const User = this.User;
      const aNumberI = 190067261967433730;
      return User.create({ aNumber: aNumberI }).then(user => {
        expect(user.aNumber).to.equal(aNumberI); // user.aNumber is still an int here
        return User.findAll().then(_user => {
          expect(parseInt(_user.aNumber, 10)).to.equal(aNumberI); // _user.aNumber is a string here, but also instead of 190067261967433730 it's "190067261967433728"
        })
      });
    });

```
Simple workaround is to use a string instead of an int when creating an object, but I understand this is not a solution.
Odd thing is that it doesn't fail when using 481267216386621440 int.

**Comment by SimonSchick** [comment]
@mirkojotic 

Probably JS rounding error:

```
$ node
> 190067261967433730
190067261967433730
> 190067261967433732
190067261967433730
>
> Number.MAX_SAFE_INTEGER < 190067261967433730
true
```

**Comment by SimonSchick** [comment]
That said, we might look into the use of JS native bigint, but only if we can skip v8 for sequelize v6 😅

**Comment by jozsefsallai** [comment]
I've compared the two versions I've tested but couldn't really figure out the reason behind this issue. As a workaround I've reverted to the old version until I have enough time to refactor my own code.

The rounding error seems reasonable, but based on my tests, it only struggles with values that don't end in a 0. There's still no explanation on why my value (which does end in a 0), gets turned into `245890903133257728`. Running it in the console doesn't seem to have any issues.

```js
$ node
> 245890903133257730
245890903133257730
> Number.MAX_SAFE_INTEGER < 245890903133257730
true
> 24589090313325728  // sequelize behaves the opposite way
24589090313325730
```

**Comment by SimonSchick** [comment]
This is out of the scope of sequelize, integers beyond MAX_SAFE_INTEGER are inherently unsafe to use as any operation (arithmetic, etc.) may result in rounding errors to occur.
If you do a `git bisect` you might be able to figure out if there's a related cause on sequelizes side but I doubt that is the case.
