### ISSUE TITLE
Create, Insert or Upsert doesnt have option to include Schema

### ISSUE THREAD

**Issue by gullyy** [sequelize/sequelize#10760]
The hierarchy is 

A Database is one compute unit/pricing unit.(Debatable yes!But mostly this is the case)
A Database contain Multiple Schemas .
A Schema contain multiple Tables.

So if I have to execute `create` or simply add one row to the table I have to provide the schema details as well.

Today I don't see any mechanism(from the Documentation) to provide the Schema name at runtime ? Is this possible? Or I am missing something here?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
