### ISSUE TITLE
How to use or in include?

### ISSUE THREAD

**Issue by 651778286** [sequelize/sequelize#10761]
How to implement  the goal like this mysql example  ?

```sql
SELECT `Course`.`id`, `Course`.`name`, `Course`.`description`, `Course`.`thumbnail`, `Course`.`program`
	, `Course`.`free`, `Course`.`state`, `Course`.`created_at`, `Course`.`updated_at`, `Course`.`deleted_at`
	, `Organizations`.`id` AS `Organizations.id`, `Organizations`.`name` AS `Organizations.name`, `Organizations`.`type` AS `Organizations.type`, `Organizations`.`created_at` AS `Organizations.created_at`, `Organizations`.`updated_at` AS `Organizations.updated_at`
	, `Organizations`.`deleted_at` AS `Organizations.deleted_at`, `Organizations`.`district_id` AS `Organizations.district_id`, `Organizations->Organization_Course`.`created_at` AS `Organizations.Organization_Course.created_at`, `Organizations->Organization_Course`.`updated_at` AS `Organizations.Organization_Course.updated_at`, `Organizations->Organization_Course`.`deleted_at` AS `Organizations.Organization_Course.deleted_at`
	, `Organizations->Organization_Course`.`course_id` AS `Organizations.Organization_Course.course_id`, `Organizations->Organization_Course`.`organization_id` AS `Organizations.Organization_Course.organization_id`
FROM `t_course` `Course`
	INNER JOIN (`r_organization_course` `Organizations->Organization_Course`
		INNER JOIN `t_organization` `Organizations`
		ON `Organizations`.`id` = `Organizations->Organization_Course`.`organization_id`
			AND (`Organizations->Organization_Course`.`deleted_at` > '2019-04-12 21:18:04'
				OR `Organizations->Organization_Course`.`deleted_at` IS NULL))
	ON `Course`.`id` = `Organizations->Organization_Course`.`course_id`
		AND ((`Organizations`.`deleted_at` > '2019-04-12 21:18:04'
				OR `Organizations`.`deleted_at` IS NULL)
			AND (`Organizations`.`id` = 3 or `Course`.`free` = 1))
WHERE (`Course`.`deleted_at` > '2019-04-12 21:18:04'
		OR `Course`.`deleted_at` IS NULL);
```

And here's the key thing: "AND (`Organizations`.`id` = 3 or `Course`.`free` = 1))"

**Comment by sbonami** [comment]
Questions like these are best suited for [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js). Sequelize's Github issues are reserved for issues or feature requests on the library itself, not specific use-cases or implementations.

We've even got a tag set up: https://stackoverflow.com/questions/tagged/sequelize.js

**Comment by 651778286** [comment]
> Questions like these are best suited for [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js). Sequelize's Github issues are reserved for issues or feature requests on the library itself, not specific use-cases or implementations.
> 
> They've even got a tag set up: https://stackoverflow.com/questions/tagged/sequelize.js

OK, Thank you anyway.I will do it

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
