### ISSUE TITLE
Where can I check sequelize.fn list?

### ISSUE THREAD

**Issue by kkangil** [sequelize/sequelize#10772]
It isn't bug issue.
I've searched docs whole day but I can't.
I'm sorry to create issue, but I don't know how to contact.

I know some `sequelize.fn` like YEAR, MONTH ...
I want to check every `sequelize.fn` list.
How can I check it?

**Comment by sushantdhiman** [comment]
`sequelize.fn` just call the database engine functions. You can use various functions available for each database engine. For example list of various functions available in posgres are https://www.postgresql.org/docs/10/functions.html
