### ISSUE TITLE
sequelize.query doesn't support "WITH queries (common table expression)" postgres

### ISSUE THREAD

**Issue by johnparra** [sequelize/sequelize#1077]
When is executed "with sql as (select \* from mytable) select \* from sql", the result of this is [ ]
[With Queries Postgres](http://www.postgresql.org/docs/current/static/queries-with.html)

**Comment by intellix** [comment]
Was there ever at least a workaround for this? Written a CTE and was expecting with sequelize.query() and raw SQL for it to at least return the resultset
