### ISSUE TITLE
Detecting n+1 queries 

### ISSUE THREAD

**Issue by goldcaddy77** [sequelize/sequelize#10770]
Does sequelize expose any hooks that allow monitoring for n+1 queries? Or does anybody know of a library that works with sequelize that already does this? I'm thinking of something like [bullet](https://github.com/flyerhzm/bullet) for Ruby.

**Comment by papb** [comment]
What exactly do you mean by n+1 queries? Can you expand on your question, adding links, references, examples, ideas?

**Comment by goldcaddy77** [comment]
For sure, borrowing from [here](https://www.sitepoint.com/silver-bullet-n1-problem/):

> What is the N+1 Query Problem ?

> This problem occurs when the code needs to load the children of a parent-child relationship (the “many” in the “one-to-many”). Most ORMs have lazy-loading enabled by default, so queries are issued for the parent record, and then one query for EACH child record. As you can expect, doing N+1 queries instead of a single query will flood your database with queries, which is something we can and should avoid.

This article goes on to describe the bullet Ruby gem that "listens" for patterns where it has detected that your app hasn't queried for records properly.

It would be great if there were a way to have sequelize detect and alert that the app has let an n+1 query in.

**Comment by papb** [comment]
Ah, I understand now. Sequelize doesn't support this, and I don't know know of any library that works with sequelize and does this... This looks very complex to implement, do you have any idea on how to start?

**Comment by papb** [comment]
I just noticed this in the first line of [graphql-sequelize](https://github.com/mickhansen/graphql-sequelize)'s readme:

> Should be used with dataloader-sequelize to avoid N+1 queries

Perhaps you can find some insight there?

**Comment by goldcaddy77** [comment]
Right, that's how you prevent n+1s... The ask is that if somebody incorrectly wires things up that you can programmatically determine this.

I think to do this you need to put some code into sequelize that can determine if a single request makes a lot of calls to the DB. I have no idea where in sequelize youd do this though.

**Comment by zwallacedev** [comment]
Any update on this? I've used `bullet` before, and it's an absolute game-changer. This would be an incredible feature on sequelize.
