### ISSUE TITLE
s.replace is not a function for literal attribute

### ISSUE THREAD

**Issue by PatrickGeyer** [sequelize/sequelize#10784]
## What are you doing?
Adding a custom attribute to a model, but the literal type doesn't get recognized correctly in query builder.

```js
import Sequelize from 'sequelize';

@DefaultScope({
    attributes: {
        include: [[Sequelize.literal(`'https://storage.googleapis.com'`), 'host']]
    }
})

```

## What do you expect to happen?
The literal should be evaluated correctly as a literal.

## What is actually happening?

The query generator code doesn't recognise it as a literal.
If I console.log ```attr[0] instanceof Utils.Literal``` it returns false when it should be true.
This leads to it trying to escape the literal:

```
TypeError: s.replace is not a function
    at Object.removeTicks 
```
This happens in query-generator.js around line 1435:

```
if (Array.isArray(attr) && attr.length === 2) {
          if (attr[0] instanceof Utils.SequelizeMethod && (
            attr[0] instanceof Utils.Literal ||
            attr[0] instanceof Utils.Cast ||
            attr[0] instanceof Utils.Fn
          )) {
            verbatim = true;
          }

```
__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.6 & 5.4
__Tested with latest release:__ Yes

**Comment by alikhanoitan** [comment]
@PatrickGeyer how did you solve this? I have the same issue. Already spent hours on this.
