### ISSUE TITLE
Typescript Literal for WhereOperators

### ISSUE THREAD

**Issue by mtryba** [sequelize/sequelize#10789]
## What are you doing?
Before update to v5 my code was like this

```js
    Sequelize.where(
      Sequelize.cast(Sequelize.col('SOME_COL'), 'integer'), {
        [Op.lt]: Sequelize.literal(SOME_STRING),
      },
    ),
```

## What do you expect to happen?
Unfortunately it's not working because `Op.lt` in interface `WhereOperators` has just `number`, `string` or `Date`. For me best option would be add `Literal` to it because now I have something like `[Op.lt]: Sequelize.literal(SOME_STRING) as any`

## What is actually happening?
```
Argument of type '{ [Op.lt]: Literal; }' is not assignable to parameter of type 'LogicType'.
  Type '{ [Op.lt]: Literal; }' is not assignable to type 'WhereOperators'.
    Types of property '[Op.lt]' are incompatible.
      Type 'Literal' is not assignable to type 'string | number | Date'.
        Type 'Literal' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 37 more
```

__Dialect:__ postgres
__Dialect version:__ 7.8.0
__Database version:__ 10
__Sequelize version:__ 5.6.0 (latest)
__Tested with latest release:__ yes

**Comment by mirkojotic** [comment]
@SimonSchick any specific reason why this wasn't included in type definition. If not I can add it.

**Comment by SimonSchick** [comment]
@mirkojotic Sequelize has a very ~~complicated~~ rich API, correctly mapping all possible types is difficult, PR is welcome.

**Comment by mirkojotic** [comment]
@SimonSchick sorry I didn't see there is already a PR open for this. You can close mine if it doesn't prove useful.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/e3d6795ddc19f78a26d4d98a1a633161fe1182ab
