### ISSUE TITLE
underscored potion not work?

### ISSUE THREAD

**Issue by fuguohong** [sequelize/sequelize#10786]
## What are you doing?

```js
app.model.define('Flight', {
        id: {
            type: STRING,
            primaryKey: true,
        },
        taskId: STRING,
}, {
        tableName: 'flight_history',
        timestamps: false,
        underscored: true,
    })

// .....
Flight.findOne()
```

## What do you expect to happen?
i want model attr named taskId, in sql  anemd task_id
SELECT `id`, `task_id` FROM `flight_history` AS `Flight` LIMIT 1;

## What is actually happening?
SELECT `id`, `taskId` FROM `flight_history` AS `Flight` LIMIT 1;

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.43.2
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Fixed in v5
