### ISSUE TITLE
Can only order 2 models deep 

### ISSUE THREAD

**Issue by mjdavidson** [sequelize/sequelize#10780]
Currently the OrderItem only can have 1 or 2 models and then 2 strings

How many inclusions deep are you able to order on?

Can we add more types to the list

## What are you doing?
trying to order a model that's nested 3 models deep
```js
order: [
  [Check, Criteria, 'createdAt', 'DESC'],
  [Check, Observation, 'createdAt'],
  [Project, Role, User, 'name'],
],
```

## What do you expect to happen?
Be able to order as many models deep as I want

## What is actually happening?
TypeError
https://github.com/sequelize/sequelize/blob/2c18e084509469c7e8b9fdbabcb4c713312c216d/types/lib/model.d.ts#L408-L415

__Dialect:__ ~mysql~ / ~postgres~ / ~sqlite~ / ~mssql~ / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 5.6
__Tested with latest release:__ yes

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by mjdavidson** [comment]
@sushantdhiman
