### ISSUE TITLE
Typing for model.get function

### ISSUE THREAD

**Issue by PatrickGeyer** [sequelize/sequelize#10781]
It would appear that sequelize chooses the wrong return type when I call model.get.

I call it like this ```userRecord.get('name')``` and for every get call it returns type ```unknown```.

Shouldn't it return the type that I specify in the model definition, i.e. ```string```?

```/**
   * If no key is given, returns all values of the instance, also invoking virtual getters.
   *
   * If key is given and a field or virtual getter is present for the key it will call that getter - else it
   * will return the value for key.
   *
   * @param options.plain If set to true, included instances will be returned as plain objects
   */
  public get(options?: { plain?: boolean; clone?: boolean }): object;
  public get(key: string, options?: { plain?: boolean; clone?: boolean }): unknown; <---- switch order of these
  public get<K extends keyof this>(key: K, options?: { plain?: boolean; clone?: boolean }): this[K]; <----
```

If I manually edit the definition file to change the order of the overloads as seen above it seems to work fine.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
