### ISSUE TITLE
sequelize.sync({force: true}) keeps using obsolete model schema

### ISSUE THREAD

**Issue by emclab** [sequelize/sequelize#10798]
My nodejs(10.15.0)/sequelizejs (4.42.0)/postgres (11) app has a socketlist model which has been  updated:

const SocketList = db.define('socketlist', {
    user_ids: {type: Sql.ARRAY(Sql.INTEGER),
    },
    fort_token: { 
      type: Sql.STRING      
    },
    server_id: {type: Sql.STRING
    },
}, {
    timestamps: false,
    indexes: [
          {
            fields: ['fort_token']
          },
          {
            fields: ['server_id']
          },
        ]   
});

I am using the sync to create db tables:

db.sync({force:true})
    .then((res) => {
        console.log("db done!");
        console.log(res);  
    }); //create db 

The problem is that the socketlist table created is still based on the old schema which has already been updated and I have no clue where the sync cached the obsolete schema code. I tried to delete the whole db or the table but the result is always the same - old and obsolete schema. The sync has been working fine until now. Is it a bug with sequelizejs?

**Comment by emclab** [comment]
Upgraded to latest version of 5.6.1 and the problem is the same.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
