### ISSUE TITLE
Underscored option does not snake_case

### ISSUE THREAD

**Issue by karltaylor** [sequelize/sequelize#10814]
## What are you doing?

I have a model and associations, but using `{ underscored: true }` does not create snake_cased keys.

```js
module.exports = (sequelize, DATATYPES) => {
  const Workout = sequelize.define(
    'workout',
    {
      name: { type: DATATYPES.STRING },
      duration: { type: DATATYPES.STRING },
      level: { type: DATATYPES.STRING },
      equipment: { type: DATATYPES.STRING },
      week_index: { type: DATATYPES.INTEGER },
      type: { type: DATATYPES.STRING },
    },
    { underscored: true } //- should snake_case
  )

  Workout.associate = function(models) {
    models.Workout.hasOne(models.WorkoutPlanWorkout, {
      foreignKey: 'workout_id'
    })
    models.Workout.hasMany(models.Circuit)
    models.Workout.belongsTo(models.Warmup) //- should be warmup_id
    models.Workout.belongsTo(models.Cooldown) //- should be cooldown_id
  }
  return Workout
}

```

## What do you expect to happen?
The data to be have snaked_cased keys:

```js
{
  id: 9,
  name: "Strength 2 - Upper Body",
  duration: 30,
  level: "beginner",
  equipment: "Mat",
  week_index: 2,
  type: null,
  created_at: null, // snaked
  updatet_at: null, // snaked
  cooldown_id: null, // snaked
  warmup_id: null // snaked
},
```

## What is actually happening?

the data is being returned in camelCase

```js
{
  id: 9,
  name: "Strength 2 - Upper Body",
  duration: 30,
  level: "beginner",
  equipment: "Mat",
  week_index: 2,
  type: null,
  createdAt: null, // not snaked
  updatedtAt: null, // not snaked
  cooldownId: null, // not snaked
  warmupId: null // not snaked
},
```

sql:

```sql
Executing (default): SELECT "id", "name", "duration", "level", "equipment", "week_index", "type", "created_at" AS "createdAt", "updated_at" AS "updatedAt", "cooldown_id" AS "cooldownId", "warmup_id" AS "warmupId" FROM "workouts" AS "workout";
```

__Dialect:__ postgres
__Sequelize version:__ 5.7.0

**Comment by sushantdhiman** [comment]
Yes, `underscored` implementation has changed in v5. It will keep attribute names in camel case but field (or column) name will be snake cased.

You can read more about this [here](https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md)

**Comment by karltaylor** [comment]
Sorry @sushantdhiman I do not follow, this isn't explained entirely too well or i'm just not getting it. What is the 'field' option you are talking about?

From the link you pasted: 

> • underscored will control all attributes including timestamps, version and foreign keys. It will not affect any attribute which already specifies the field option.

This should make everything snake_cased/

**Comment by ox** [comment]
Running into this during my upgrade as well. From what I can gather, the attribute name (what you reference in your JS code) will always be camelCase, but the fields will be stored in the DB as snake_case. So your call sites will have to change from `model.created_at` to `model.createdAt`, though the column name will be `created_at` in the DB.

Is that correct @sushantdhiman? 

You can change timestamps field names to what you expect by specifying their field names in the model init options:

```js
options = {
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  deletedAt: 'deleted_at',
};
```

That will let you call `model.created_at`.

Probably also worth digging into http://docs.sequelizejs.com/manual/associations.html#underscored-option. I'm still not entirely sure how to fix your `warmupId` issue, but that page is where I would look.
