### ISSUE TITLE
Type expected for model.d.ts file

### ISSUE THREAD

**Issue by leogoesger** [sequelize/sequelize#10810]
## What are you doing?

upgrading from V4 - V5. 

```js
interface IAllergenExtend extends Model {
  id?: number;
  name: string;
  description: string;
  updatedAt?: string;
  createdAt?: string;
}

type AllergenModel = typeof Model &
  (new (values?: object, options?: BuildOptions) => IAllergenExtend) & {
    associate: (model: IDB) => any;
  };

const allergenFactory = (sequalize: Sequelize) => {
  const Allergen = (<AllergenModel>sequalize.define('Allergen', {
    id: {
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
      type: DataTypes.INTEGER
    },
    name: {
      allowNull: false,
      type: DataTypes.TEXT
    },
    description: {
      allowNull: false,
      type: DataTypes.TEXT
    }
  })) as AllergenModel;

  Allergen.associate = (model: IDB) => {
    Allergen.belongsToMany(model.Dish, {
      through: db.AllergenDish,
      foreignKey: 'allergenId',
      as: 'dishes'
    });
  };

  return Allergen;
};

export { allergenFactory, AllergenModel };
```

## What is actually happening?
Error message for type:

> node_modules/sequelize/types/lib/model.d.ts:108:29 - error TS1110: Type expected.
> 
> 108 method: string | [string, ...unknown[]];

I removed those couple lines in the lib, and everything works afterward.

@latest

**Comment by SimonSchick** [comment]
Sequelize typings only support TS 3.x

**Comment by sagitsofan** [comment]
I have Node 12.13.0 with TS Version 3.7.2 and i am receiving this error when using Sequelize 5.21.2:

> node_modules/sequelize/types/lib/model.d.ts:118:29 - error TS1110: Type expected.
> 
> 118   method: string | [string, ...unknown[]];

Can we except for a fix ?

**Comment by SimonSchick** [comment]
@sagitsofan I cannot repro your issue.
Please open a new issue with a proper reproduction setup.

**Comment by dave-dm** [comment]
I'm also getting this error, any way to just suppress it from typescript all together? I don't really care about what's going on in my node_modules

**Comment by papb** [comment]
@dave-dm What version of typescript are you using?

Also, can you please open a new issue with a complete reproduction setup, as Simon asked above? Thanks
