### ISSUE TITLE
Change default referential action

### ISSUE THREAD

**Issue by bminer** [sequelize/sequelize#10824]
**Problem**
Associations (foreign keys) in Sequelize define a rather opinionated default referential action for `ON UPDATE` / `ON DELETE` clauses.

For `ON UPDATE`, Sequelize defaults to `CASCADE`.
For `ON DELETE`, Sequelize defaults to `SET NULL` if the source field allows null values; otherwise, `CASCADE` is the default.

It would be convenient to set `RESTRICT` or `NO ACTION` as the default (database-wide) in some circumstances.  In MySQL, for example, the default referential action is `RESTRICT` when not explicitly specified; Sequelizes seems to override these defaults.

**Describe the solution you'd like**
It would be nice to override the "default" referential action for `ON UPDATE` and `ON DELETE` when associations are created.  It can get annoying to override this behavior for every single association in the database if `RESTRICT` is the general rule / policy.  This could be done in the `options` Object passed to the new Sequelize instance (see usage example below).

**Why should this be in Sequelize**
This is a small change (probably ~10 lines of code), but it gives extra flexibility to the developer without requiring the developer to be verbose with association definitions.

**Describe alternatives you've considered**
Another possible solution is creating some sort of hook that allows one to change the default `onDelete` and `onUpdate` options of an association.  I don't know of any such hook at this time.

**Usage example**
```js
const db = new Sequelize(config.database, config.username, config.password, {
	host: config.host,
	// New `associations` key
	associations: {
		onDelete: 'RESTRICT',
		onUpdate: 'CASCADE',
	}
})
```

**Comment by bminer** [comment]
Also, I would be willing to submit a PR if there's a good change it will be accepted.

**Comment by SimonSchick** [comment]
I think this is a reasonable request, feel free to submit a request.

**Comment by catamphetamine** [comment]
I agree: it was unexpected for me to find out that Sequelize doesn't use `RESTRICT` by default — using something other than `RESTRICT` (or `undefined`) seems like a bad opinionated practice.
Sequelize already has things like `paranoid` but still doesn't provide such basic safeguards against loosing valuable data by default.

**Comment by igordeoliveirasa** [comment]
I totally agree! I'd like to set my default behavior to: , onDelete: "NO ACTION".

**Comment by ephys** [comment]
We discussed whether to accept this feature request at today's meeting.
We did not feel it was necessary to implement this, as this is already achievable with hooks, and we felt the demand was too low for the extra complexity.

Example of how this can be handled with hooks:

```typescript
Projects.beforeAssociate((data, options) => {
  options.onDelete = 'NO ACTION';
});
```

We can revisit this at a later date if there is enough demand for it.

**Comment by bminer** [comment]
Thanks for the workaround, and I appreciate your thoughtful consideration!

**Comment by bminer** [comment]
Also, thanks to you, I just learned that `||=` is a thing in JavaScript.
