### ISSUE TITLE
Async scope function

### ISSUE THREAD

**Issue by PatrickGeyer** [sequelize/sequelize#10829]
**Describe the solution you'd like**
In some of my scopes, I need more complicated subqueries and don't want to be repeating/typing them by hand. So I extended sequelize functionality with a basic query builder.
I would like to generate queries for sequelize like this:
```
static async getQuery(params: FindOptions = {}): CustomLiteral {

        const getFixedOptions = (options: any): Promise<any> => {
            const id = uuid().substr(0, 8);
            options.trackingid = id;
            return new Promise((resolve) => {
                // tslint:disable-next-line:no-shadowed-variable
                this.addHook('beforeFindAfterOptions', id, (options): any => {
                    if (options.trackingid === id) {
                        this.removeHook('beforeFindAfterOptions', id);
                        resolve(options);
                        return new Promise(() => { });
                    }
                });
                return this.findAll(options);
            });
        };

        return new CustomLiteral('(' + (this.sequelize.getQueryInterface().QueryGenerator as any)
            .selectQuery(this.name, await getFixedOptions(params), this).slice(0, -1) + ')');
    }
```
I would then do something along the lines of this: 

```
User.addScope('test', async () => {
    return {
        where: {
            id: {
                 [Sequelize.Op.in]: await Task.getQuery({attributes: ['UserId']})
            }
        }
    };
});
```

Of course the getQuery function now has to be async due to the ```beforeFindAfterOptions``` hook and so I cannot use this function in scopes as the functions have to be synchronous.

**Why should this be in Sequelize**
Allows for more complicated queries
**Describe alternatives you've considered**
Using the ```getQueryInterface().selectQuery(options)``` works quite well, except the options and validated/transformed like they are when I call ```findAll```.
**Usage example**
See above
**Additional context**
Maybe just an options validator function would work as well.

**Comment by SimonSchick** [comment]
This is somewhat complicated given how scopes are currently handled internally as they are cached upon calling `.scope()`, for the time being you are probably better off creating a your own solution maybe involving hooks.

**Comment by ephys** [comment]
We discussed whether to accept this feature request at today's meeting.
The resolution was that this feature would increase the complexity of the code too much to be worth it, especially since there doesn't seem to be high demand for it.

The good news is: We're working on improving literals, adding a query builder, and making `QueryGenerator` a clean public API. These should hopefully help with subqueries.
