### ISSUE TITLE
V6: Removing support for NodeJS v6

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#10821]
Node v6 is approaching the end of it's long term support window and will be end of life on 4/30.

We will no longer be supporting node v6 and you will not be able to use sequelize v6 in node v6 without the use of transpilers and polyfills.

**Comment by SimonSchick** [comment]
See related PR https://github.com/sequelize/sequelize/pull/10739/commits

**Comment by janmeier** [comment]
:+1:

**Comment by mrrinot** [comment]
Tests suite are still run under node 6 on Travis.  
Is there a plan to update these as well ?

**Comment by gabegorelick** [comment]
Node 8 reaches end of life December 31, 2019. Should support for that be dropped too?

**Comment by papb** [comment]
Hmmm, probably :)

**Comment by sushantdhiman** [comment]
Supporting Node >= 10, https://github.com/sequelize/sequelize/pull/11580

**Comment by harshdeep-jft** [comment]
I dont think sequelize supports node v18. Cannot lift the application with it, Its working on node v16 fine.

**Comment by WikiRik** [comment]
> I dont think sequelize supports node v18. Cannot lift the application with it, Its working on node v16 fine.

What version of sequelize are you using? The latest v6 release should work with Node 18

**Comment by harshdeep-jft** [comment]
@WikiRik I am using Sequelize: 6.23.0 and tedious: 15.1.0 and mssql: 7.3.0

**Comment by harshdeep-jft** [comment]
> @WikiRik I am using Sequelize: 6.23.0 and tedious: 15.1.0 and mssql: 7.3.0

It throws this error : `ConnectionError [SequelizeConnectionError]: Failed to connect to 192.168.106.10:1433 - socket hang up
    at ConnectionManager.connect (/home/test project/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:109:17)`

**Comment by SimonSchick** [comment]
Can you provide a min repro?

**Comment by harshdeep-jft** [comment]
> Can you provide a min repro?

I just create an app with express-generator in node v18 and configured it with sequelize, that's all, can you try the same in your machine?
