### ISSUE TITLE
error connection postgresql 9.0

### ISSUE THREAD

**Issue by fabio-basedev** [sequelize/sequelize#10839]
Hi!

I have problem to connect in Postgres 9.0 version with sequelize. Show me an error about not exist 'pg_range' (error message: 'relation "pg_range" dows not exist'). 

When I try connect in Postgre 9.5 it works (because 9.5 have pg_range on pg_catalog). How can I connect in Postgres 9.0??

```js
const sequelize = new Sequelize(
      'DatabaseTest',
      'postgres',
      'postgres',
      {
        host: '[ip]',
        dialect: 'postgres',
        port: 5432
      }
    );
    sequelize
      .authenticate()
      .then(() => {
        toast.success('Conexão realizada com sucesso!');
        return true;
      })
      .catch(err => {
        toast.error(`Não foi possível conectar na fonte de dados ${err}`);
      });
```
**To Reproduce**
Just try connect!

## What do you expect to happen?
Connect.

## What is actually happening?
raise this error:  'relation "pg_range" dows not exist'

## Environment
Dialect:
- [ ] mysql
- [X] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any

Dialect **library** version: 7.9.0
Database version: 9.0
Sequelize version: 5.2.11
Node Version: 10.15.1
OS: Win 10

Tested with latest release:
- [X] No
- [ ] Yes, specify that version:

**Comment by fabio-basedev** [comment]
I've found a workaround!!

I've downgrade 'pg' library version to pg@6.4.2 and now its working.... 

Sequelize has some incompatibility with latest pg library version....

**Comment by SimonSchick** [comment]
Iirc we don't support anything below 9.4 in v5 cc @sushantdhiman

**Comment by dberardo** [comment]
is this problem still persisting? 
i am trying to connect to a postgres db version 8.x through sequelize and i get the same error message as @fabio-basedev 
unfortunately i cannot find any documentation on PG version compatibility of sequelize so i can't figure out whether postgres 8.x is too low for sequelize 5.x 

any clue?

**Comment by dberardo** [comment]
> 
> 
> is this problem still persisting?
> i am trying to connect to a postgres db version 8.x through sequelize and i get the same error message as @fabio-basedev
> unfortunately i cannot find any documentation on PG version compatibility of sequelize so i can't figure out whether postgres 8.x is too low for sequelize 5.x
> 
> any clue?

i have solved this, by downgrading sequelize to the deprecated version 4.44 it seems to work.

hope they will improve their documentation, it took me quite a while to figure that out.

thanks @SimonSchick for your message, that helped me out

**Comment by mar-ale-fer** [comment]
pg_range exists in Posgres since version 9.2. Source: https://pgpedia.info/p/pg_range.html

**Comment by sinonsrt** [comment]
Did you have some new clue ?

**Comment by mar-ale-fer** [comment]
No, I change the connection to another server with Postgres 9.6 version and the problem disappear.

**Comment by sinonsrt** [comment]
Ok, i'm change to use the ORM Prisma, and it's working now, thank you

**Comment by macroramesh6** [comment]
It's not resolved yet. Any workaround?

**Comment by ephys** [comment]
Postgres 9 is not supported by Sequelize. We only support versions that are still officially supported by postgres https://www.postgresql.org/support/versioning/

The only solution I can offer is to either update your database to postgres >= 10, or use an older version of sequelize and the pg library.
