### ISSUE TITLE
Add cache middleware to Query prototype

### ISSUE THREAD

**Issue by Gil707** [sequelize/sequelize#10842]
I want to add caching layer for some queries in all models, that turned on by trigger (function like cache() appended to model).
For example if I want use cache it'll be
```
let media = await Medias
            .cache({key: req.params.id})
            .findOne({
                where: {media_id: req.params.id},
            });
```

Or, if I do not want to use cache the query will be without this line
```
.cache({key: req.params.id})
```
I realized this with service, here is it

```
const Sequelize = require('sequelize');
const redis = require('redis');
const { promisify } = require('util');
const redisUrl = require('@config/db').cache.redis;
const client = redis.createClient(redisUrl);
client.hget = promisify(client.hget);

const exec = Sequelize.Model.findOne;

Sequelize.Model.cache = function(options = {}) {

    this.useCache = true;
    this.hashKey = JSON.stringify(options.key || '');

    return this;
};

Sequelize.Model.findOne = async function () {

    if (!this.useCache) {
        return exec.apply(this, arguments);
    }

    const cacheValue = await client.hget(this.name, this.hashKey);

    if (cacheValue) {
        return JSON.parse(cacheValue);
    }

    const result = await exec.apply(this, arguments);
    client.hset(this.name, this.hashKey, JSON.stringify(result));

    return result;
};
```
But there is a problem, when I apply cache for one of model query it applied to all model's queries, ignoring `.cache()`, because `this.useCache` is setted to `true` for all Model's I think.
I try to fix it with additional parameter, that must be inside options and default `false` value to `this.useCache` var.

```
Sequelize.Model.cache = function(options = {}) {

    this.useCache = options.enable || false;
    this.hashKey = JSON.stringify(options.key || '');

    return this;
};
```

And in model i should write 
```
let media = await Medias
            .cache({enable: true, key: req.params.id})
            .findOne({
                where: {media_id: req.params.id},
            });
```
Also there is a problem, that I need to reassign each query that I need to cache
```
const exec = Sequelize.Model.findOne;
const execAll = Sequelize.Model.findAll;
...
```
etc. for each Model function

May be there are some another way to realize this functionality, 
like I make it in Mongoose with 
```
mongoose.Query.prototype.exec = async function() {
  if (!this.useCache) {
    return exec.apply(this, arguments);
  }
.......
``` 
and it applies to all specified query when I run it with `.cache()` (`this.useCache` setting to `true` only for query) and I do not need to rewrite each model method with own with cache implementation.

**Comment by SimonSchick** [comment]
This would require massive refactors and would apply a state to `Model` classes which is something we have refrained from in the past due to a myriad of possible issues.

I'd strongly suggest you create your cache outside of sequelize which is a much cleaner solution.
