### ISSUE TITLE
Request is blocked when it can't find data

### ISSUE THREAD

**Issue by Tryliom** [sequelize/sequelize#10845]
## What are you doing?
I have a expressjs server who use sequelize to connect to my db with some token to keep connection on. When the client send a existing token, the request get the token and let it go to next function but when the client send an empty or incorrect token, it blocks for few minutes and doesn't respond anymore.<br>
Issue linked to [stackoverflow](https://stackoverflow.com/questions/55863064/why-mysql-request-timeout-when-it-cant-find-data)

Server
```js
const Token = require('./models/token');

function isAuth(req, res, next) {
    if (req.cookies.token) {
        Token.findOne({where: {token: req.cookies.token}}).then(token => {
            console.log("TOKEN");
            if (!token) {
                console.log("2");
                res.clearCookie('token');
                res.redirect("/");
            } else
                next();
        })
    } else {
        console.log("1");
        res.redirect("/");
    }
};
```
Token model
```
var Sequelize = require('sequelize');
var sequelize = new Sequelize(process.env.DATABASE_URL);

var Token = sequelize.define('token', {
    token: {
        type: Sequelize.STRING,
        unique: true,
        allowNull: false
    }
});

sequelize.sync().then(() => {
    console.log('token table has been successfully created, if one doesn\'t exist');
}).catch(error => console.log('This error occured', error));

module.exports = Token;
```
**To Reproduce**
1. Run server.
2. Send request with a cookie `token` to it who is incorrect.

## What do you expect to happen?
The server must redirect me and delete my cookie `token`.

## What is actually happening?
When 2 minutes are gone, browser stop request and server doesn't display any error but has blocked all the time.

Server log
```
Executing (default): SELECT `id`, `token`, `createdAt`, `updatedAt` FROM `tokens` AS `token` WHERE `token`.`token` = 'token_invalid';
GET /api/loadUserCurrent - - ms - -
```
## Environment
Dialect:
- [x] mysql
Dialect **library** version: nginx:1.15.7-alpine
Sequelize version: 4.41.0
Node Version: v10.2.1
OS: Mac OS Mojave 10.14.4

**Comment by SimonSchick** [comment]
This is not a sequelize issue, you probably have missing error handling somewhere, please join the sequelize slack if you need help in using sequelize vs actual bugs.
