### ISSUE TITLE
JSON attribute reports changed for non-primitives

### ISSUE THREAD

**Issue by seally1186** [sequelize/sequelize#10848]
## What are you doing?
JSON attributes are marked as changed even when set to their exact value, if the value is not a primitive.

```js
  const test = sequelize.define("test", {
    foo: DataTypes.JSON
  });
  await test.sync({force: true});
  for (let value of [null, 1, "asdf", new Date(), [], {}]) {
    let t = new test({ foo: value });
    await t.save();
    t.foo = t.foo;
    if (t.changed()) console.log(value);
  }

  await test.drop();
```

## What do you expect to happen?
No output--setting to current value won't trigger changed()

## What is actually happening?
```
2019-04-27T01:44:34.152Z
[]
{}
```

The issue affects objects only--primitives are handled correctly. I believe adding an `_isChanged` method to the JSONTYPE can fix this, but not sure if that's the way to go.

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [x] any (tested on mariadb)
Dialect **library** version: `mariadb@2.0.3`
Database version: mariadb 10.3
Sequelize version: 5.7.6 and master
Node Version: 10
OS: Linux
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: master

**Comment by SimonSchick** [comment]
I do believe this is due to these values being deep cloned on assignment, will look into.

**Comment by SimonSchick** [comment]
Actually this might be intended behaviour based on a test case I found in the code base.
