### ISSUE TITLE
Docu unclear about hasMany and belongsTo

### ISSUE THREAD

**Issue by realsony** [sequelize/sequelize#10843]
I use the present Sequelize version and try to build as said in the docu the associations between two models. Should be actually pretty simple since Sequelize offers `hasMany` and `belongsTo`.

But the call has no effect at all. I tried it with a new SQL DB. The tables itself are created but without any foreign key. Any idea what's wrong?

**db controller**

    const userModel = require('../model/user')
    const subjectModel = require('../model/subject')
    const database = require('../db/database').sequeliceInstance
    
    async function setupAssociations () {
      await database.sync()
    
      // user + subject
      userModel.hasMany(subjectModel)
      subjectModel.belongsTo(userModel)
    
      // subject and topic
      subjectModel.hasMany(topicModel)
      topicModel.belongsTo(subjectModel)
    
      // topic and question
      topicModel.hasMany(questionModel)
      questionModel.belongsTo(topicModel)
    
      // question and answer
      questionModel.hasMany(answerModel)
      answerModel.belongsTo(questionModel)
      return Promise.resolve()
    }

**user.js**

    const Sequelize = require('sequelize')
    const db = require('../db/database').sequeliceInstance
    
    const user = db.define('user', {
      // attributes
      firstName: {
        type: Sequelize.STRING,
        allowNull: false
      },
      lastName: {
        type: Sequelize.STRING,
        allowNull: false
      },
      email: {
        type: Sequelize.STRING,
        allowNull: false
      },
      title: {
        type: Sequelize.STRING,
        allowNull: false
      },
      password: {
        type: Sequelize.TEXT,
        allowNull: false
      }
    })
    
    module.exports = user

**subject.js**

    const Sequelize = require('sequelize')
    const db = require('../db/database').sequeliceInstance
    
    const subject = db.define('subject', {
      // attributes
      subjectName: {
        type: Sequelize.TEXT,
        allowNull: false
      }
    })
    
    module.exports = subject

**Comment by janmeier** [comment]
You are calling `await database.sync()` (createing the tables) before you add the associations - So at the point in time where you are creating the tables sequelize doesn't know anything about the associations

**Comment by realsony** [comment]
ty a lot you are my hero for today :)
