### ISSUE TITLE
TypeScript documentation doesn't work in v5

### ISSUE THREAD

**Issue by TidyIQ** [sequelize/sequelize#10849]
## What was unclear/insufficient/not covered in the documentation

I followed the support doc at http://docs.sequelizejs.com/manual/typescript.html to include TypeScript, however it returns errors. 

Here is my full code:

```
import { Model, DataTypes } from "sequelize";
import { sequelize } from "./index";
import bcrypt from "bcrypt";

class User extends Model {
  public test!: string;                // No error message received for being missing in User.init()
  public userId!: number;
  public orgId!: number;
  public role!: string;
  public name!: string;
  public email!: string;
  public password!: string;
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
  public findByLogin: (email: string) => Promise<User | null>;     // Error message received
  public generatePasswordHash: () => Promise<string>;     // Error message received
  public validatePassword: (password: string) => Promise<boolean>;     // Error message received
}

User.init(
  {
    userId: {
      type: new DataTypes.INTEGER.UNSIGNED(),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      validate: {
        notEmpty: true,
        notNull: true
      }
    },
    orgId: {
      type: new DataTypes.INTEGER.UNSIGNED(),
      allowNull: false,
      validate: {
        notEmpty: true,
        notNull: true
      }
    },
    role: {
      type: new DataTypes.STRING(),
      allowNull: false,
      validate: {
        notEmpty: true,
        notNull: true,
        isAlpha: true
      }
    },
    name: {
      type: new DataTypes.STRING(),
      allowNull: false,
      validate: {
        notEmpty: true,
        notNull: true,
        isAlpha: true
      }
    },
    email: {
      type: new DataTypes.STRING(),
      unique: true,
      allowNull: false,
      validate: {
        notEmpty: true,
        notNull: true,
        isEmail: true
      }
    },
    password: {
      type: new DataTypes.STRING(),
      allowNull: false,
      validate: {
        notEmpty: true,
        notNull: true
      }
    }
  },
  {
    sequelize,
    tableName: "users",
    modelName: "user"
  }
);

User.findByLogin = async (email: string) => {        // Error message received here
  return await User.findOne({
    where: { email }
  });
};

const encryptPasswordIfChanged = async (user: User) => {
  if (user.changed("password")) {
    user.password = await user.generatePasswordHash();
  }
};
User.beforeCreate(encryptPasswordIfChanged);
User.beforeUpdate(encryptPasswordIfChanged);

User.prototype.generatePasswordHash = async function() {
  const saltRounds = 10;
  return await bcrypt.hash(this.password, saltRounds);
};

User.prototype.validatePassword = async function(password) {
  return await bcrypt.compare(password, this.password);
};

export default User;
```

However I get errors at:

```
  public findByLogin: (email: string) => Promise<User | null>;

// Error message:
Property 'findByLogin' has no initializer and is not definitely assigned in the constructor.ts(2564)
```

```
  public generatePasswordHash: () => Promise<string>;

// Error message:
Property 'generatePasswordHash' has no initializer and is not definitely assigned in the constructor.ts(2564)
```

```
  public validatePassword: (password: string) => Promise<boolean>;

// Error message:
Property 'validatePassword' has no initializer and is not definitely assigned in the constructor.ts(2564)
```

```
User.findByLogin = async (email: string) => {

// Error message:
Property 'findByLogin' does not exist on type 'typeof User'.ts(2339)
```

Also, I have specified that the User model should include a `test` field, as per:

```
  public test!: string;
```

However no errors are displayed to indicate that this is missing from User.init

It seems the documentation is outdated or incorrect. What is the correct way to use the Typescript with Sequelize.js? I've searched for hours and no other topics exist that address this issue.

Also, I was previously using sequelize.define() instead of sequelize.init() however I had to abort that as I get even more errors following the documented example for using Typescript with sequelize.define()

### If possible: Provide some suggestion how we can enhance the docs

> Provide a clear and working example for using Typescript with Sequelize, for both sequelize.define() and sequelize.init()

**Comment by SimonSchick** [comment]
The first 4 errors are user errors, this has nothing to do with sequelize.
The fifth one is a limitation of TS, TS does not generate member metadata therefor we cannot check for consistency at compile and/or runtime.

I agree that we need to improve documentation a bit as currently examples are not very in depth, but that's already a tracked issue.

**Comment by TidyIQ** [comment]
Can you please expand on the user errors? I followed the guide provided in the documentation so I'm not sure what the error is or how to fix it.

**Comment by SimonSchick** [comment]
With strict property initialisation you have to assign a value to class members immediately or use a null assertion `!` on the model properties.
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

**Comment by TidyIQ** [comment]
Thanks for that. Yeah the documentation is incomplete in that case. It doesn't initialize the methods or use a null assertation. See below for how the documentation says to do it:

```
  public getProjects: HasManyGetAssociationsMixin<Project>;
  public addProject: HasManyAddAssociationMixin<Project, number>;
  public hasProject: HasManyHasAssociationMixin<Project, number>;
  public countProjects: HasManyCountAssociationsMixin;
  public createProject: HasManyCreateAssociationMixin<Project>;
```
I added the null assertation `!` to it and that removed the first 3 errors, but I'm still getting the 4th error:

```
Property 'findByLogin' does not exist on type 'typeof User'.ts(2339)
```

**Comment by SimonSchick** [comment]
That's because it's static.

**Comment by TidyIQ** [comment]
That is how the documentation says to do it though - http://docs.sequelizejs.com/manual/models-definition.html#expansion-of-models

Am I doing it wrong?

**Comment by TidyIQ** [comment]
I'm also getting another error now when I attempt to run the app:
```
    type: new _sequelize.DataTypes.INTEGER.UNSIGNED(),
          ^

TypeError: _sequelize.DataTypes.INTEGER.UNSIGNED is not a constructor
```
If I remove the `new` then I get the error:

```
TypeError: _sequelize.DataTypes.INTEGER.UNSIGNED is not a function
```

However if I also remove the parenthesis then it works. 

The documentation shows the example as
```
  id: {
    type: new DataTypes.INTEGER.UNSIGNED(), // you can omit the `new` but this is discouraged
    autoIncrement: true,
    primaryKey: true,
  },
```
So this appears to be another error with the documentation.

**Comment by SimonSchick** [comment]
This works because it's JS, not TS, please note that a lot of the documentation is still JS.
TS is much stricter about assignments.
That said, I am going to improve the docs you just mentioned, they should not be telling you to assign methods after class creation, that's an anti-pattern.

**Comment by TidyIQ** [comment]
Thank you. If it's not too much trouble can you please send me a message or reply back when the new documentation is ready? I'm getting error after error by following the documentation and at this stage I can't get my app to run at all. 

Here's the latest error:

```
      this.importCache[importPath] = defineCall(this, DataTypes);
                                     ^

TypeError: Class constructor User cannot be invoked without 'new
```

**Comment by SimonSchick** [comment]
I'd ask you to join our slack for further support.

**Comment by TidyIQ** [comment]
Sure, can you please send an invite to dev@tidy-iq.com

**Comment by SimonSchick** [comment]
http://sequelize-slack.herokuapp.com/
