### ISSUE TITLE
Logging loses CLS context

### ISSUE THREAD

**Issue by dhans** [sequelize/sequelize#10855]
We use cls-hooked via express-http-context to track all actions connected to a request for logging purposes. We have a custom Sequelize logging method. Trying to get the CLS request ID in a afterFind hook works as expected; trying to get that same request ID within the logging function appears to give a random ID from a previous request, likely from the connection pool. 

In express setup:
```
const express = require('express');
const httpContext = require('express-http-context');
let app = express();
app.use(httpContext.middleware);
app.use((req, res, next) => {
  httpContext.set('requestId', uuidV4());
  next();
});
```

In Sequelize setup:
```
const httpContext = require('express-http-context');
function logNow(message, timespan) {
    console.log(`logging: ${httpContext.get('requestId')}`);
}
const sequelize = new Sequelize('db', dbUser, dbPassword, {
    dialect: 'postgres', 
    host: dbEndpoint,
    port: dbPort,
    logging: logNow,
}
```

## Environment
Dialect:
- [x] postgres
Database version: 11
Sequelize version: 5
Node Version: 10
OS: Windows
Tested with latest release:
- [ ] No
- [x] Yes 5.7.5

**Comment by SimonSchick** [comment]
Does cls-hooked work with bluebird?
I'm not sure if this is strictly a sequelize issue.

**Comment by dhans** [comment]
Ah, that sounds correct. Looks like there's finally progress on CLS support in bluebird: https://github.com/petkaantonov/bluebird/pull/1472

Decidedly a different can of worms - but what's the reason for keeping bluebird promises vs moving to native promises?

**Comment by SimonSchick** [comment]
@dhans it's a HUGE amount of work and a big breaking change.
I'm actually working on it but haven't made too much progress, you are welcome to contribute at https://github.com/sequelize/sequelize/tree/chore/remove-bluebird

**Comment by dhans** [comment]
That's indeed a huge change, thanks for putting in the work to make it happen! It's easy to forget how much complexity is hidden away below the surface. I don't think I can commit to putting in time right now, though it's a very worthwhile effort.

**Comment by SimonSchick** [comment]
@dhans We are currently inclined to remove (and have in the v6 branch) CLS support due to various issues with CLS, for reasoning please see the related issue and PR.

**Comment by dhans** [comment]
I saw the discussion though assumed it was limited to the use of CLS for Sequelize transactions - am I misunderstanding the impact? Would this change break all use of CLS in a code base that uses Sequelize?

Presumably transitioning from Bluebird to native promises should resolve these issues in the long term?
