### ISSUE TITLE
the inner data in multiple result set not is an array

### ISSUE THREAD

**Issue by jimwei** [sequelize/sequelize#10868]
Hi,
i use sequelize.query to get a mutiple result set, such as
const results = await sequelize.query('select * from user; select * from region;', {type: sequelize.QueryTypes.SELECT});

the results is an array, and the inner data in results is not an array, but an object.
is this a bug?

thank you!

**Comment by SimonSchick** [comment]
Multiple queries inside `.query` are not supported.
