### ISSUE TITLE
Associations not return with `{include: all}` when using multiple `belongsTo` on same model

### ISSUE THREAD

**Issue by tamoyal** [sequelize/sequelize#10864]
I have an Appointment model that has both a student and a teacher. So teachers have many appointments, students have many appointments, and appointments belong to one teacher and one student through distinct foreign keys referencing the same model.

```js
  Appointment.associate = function (models) {
    Appointment.Teacher = Appointment.belongsTo(models.Account, {
      as: 'teacher',
      foreignKey: 'teacherId'
    });
  };

  Appointment.associate = function (models) {
    Appointment.Student = Appointment.belongsTo(models.Account, {
      as: 'student',
      foreignKey: 'studentId'
    });
  };
```

If I query and include all associations, neither the student nor the teacher is included:
```js
  const appointment = await db.Appointment.findOne({
    where: { id: req.params.id },
    include: { all: true }
  });
```

If I query and specify the associations specifically, I get an error:
```js
const appointment = await db.Appointment.findOne({
    where: { id: req.params.id },
    include: [{ model: db.Account, as: 'student' }, { model: db.Account, as: 'teacher' }]
  });
// Gives me SequelizeEagerLoadingError: account is not associated to appointments!
```

Is this a bug or am I doing something wrong? I've seen a few other posts about this but still can't resolve. I'm using sequelize `5.8.0` with mysql.

**Comment by tamoyal** [comment]
Hoping someone can comment on this soon...

**Comment by papb** [comment]
Hello! Sorry to take so long to reply... Have you figured it out? At least, a workaround?

Also, you have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Con you please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))? I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.
