### ISSUE TITLE
 [ Security ISSUE: SQL Injection] sequelize 4.43.2

### ISSUE THREAD

**Issue by iwaduarte** [sequelize/sequelize#10866]
## What are you doing?

Snyk reports a SQL injection vulnerability in version sequelize@4.43.2.

https://snyk.io/vuln/SNYK-JS-SEQUELIZE-174167

The only change it is a breaking change update that does not work with **.sync({alter:true))** properly as reported here:
#10788

Would you guys offer a reasonable solution or explanation for that? Most of the changes in the new v5 breaks my existent code. It is just unfair to the users and community that support sequelize to have to cope with a forceful update that it is not helping legacy systems.

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any

Sequelize version: 4.43.2
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by SimonSchick** [comment]
Yea this should have been backported, not sure why this hasn't happened.
I will look into it once my jetlag is gone, you're free to make a pr against v4 as well.

**Comment by SimonSchick** [comment]
Fixed by: https://github.com/sequelize/sequelize/pull/10897

**Comment by sahatnicholas-gdp** [comment]
Hi, commenting on closed issue because of no response [here](https://github.com/sequelize/sequelize/issues/11202).
Based on Snyk Security Team https://www.npmjs.com/advisories/1018, there is also SQL Injection vulnerability on sequlize v4.44.*
Any suggestion other than migrating to v5?

**Comment by SimonSchick** [comment]
Willing to accept PRs, I currently don't have enough capacity to work on sequelize, not sure about other maintainers.

**Comment by sahatnicholas-gdp** [comment]
Thanks for responding so fast. I tried to work on this with https://github.com/sequelize/sequelize/pull/10897/files as reference. In my understanding, SQL Injection may happen due to program didn't escape string properly (CMIIW). Unfortunately, I have difficulty identifying the piece of code that cause such problem. Can someone point me to the right direction?
