### ISSUE TITLE
dialectModule option missing in typescript typings

### ISSUE THREAD

**Issue by ivan-brunet** [sequelize/sequelize#10862]
this option, added in the #9972 PR, is missing in the typescripts definitions (see [sequelize.d.ts#L162](https://github.com/sequelize/sequelize/blob/04e3592e7f69593efbbd4c5ec43096e6a3bb02d2/types/lib/sequelize.d.ts#L162))

## What are you doing?
trying to use sequelize with webpack
example code:
```ts
import tedious from 'tedious';
[...]
const connection = new Sequelize(db, user, pass, { dialectModule: tedious });
```
**To Reproduce**
(see above)

## What do you expect to happen?
the dialectModule option should be available

## What is actually happening?
the dialectModule option is not recognized

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [x] any

Sequelize version: 5.7.6
Node Version: 9.3.0
TypeScript version: 3.4.3

**Comment by SimonSchick** [comment]
PR welcome, on a plane atm and my connection is super unstable 😅
