### ISSUE TITLE
How can sort a field to insensitive locale character ?

### ISSUE THREAD

**Issue by dreadful44** [sequelize/sequelize#10861]
When I use order method in query, i'm getting ignored locale character. I set the **charset: 'utf8'** and **collate: 'utf8_turkish_ci'**

For example: 

|name|limit|
|--|--|
|İzmir  | 50  |
|Ankara  | 50  |
|Trabzon  | 50  |

select * from table order by name ASC;

I must get Ankara -> İzmir -> Trabzon.
But i'm getting Ankara -> Trabzon -> İzmir.

Can anyone help ?

**Comment by SimonSchick** [comment]
Please join our slack and ask questions there.
