### ISSUE TITLE
Merge strategy option for multiple scopes

### ISSUE THREAD

**Issue by PatrickGeyer** [sequelize/sequelize#10873]
**Is your feature request related to a problem? Please describe.**
I think it would be useful to be able to define a merge strategy when querying using scopes.

E.g. the examples show the following:
```
{
  scope1: {
    where: {
      firstName: 'bob',
      age: {
        [Op.gt]: 20
      }
    },
    limit: 2
  },
  scope2: {
    where: {
      age: {
        [Op.gt]: 30
      }
    },
    limit: 10
  }
}
```
Calling .scope('scope1', 'scope2') will yield the following query
```
WHERE firstName = 'bob' AND age > 30 LIMIT 10
```
I would like to merge the two ```age``` where indexes using Sequelize.and.
For example if I wanted to get everyone with an age above 30 AND their age being in a list. I would call it like this:

```
User.scope2().findAll({
   where: {
        age: {
            [Sequelize.Op.in]: [20, 23, 40, 41, 50, 55]
        }
   }
})
```
However, now the age parameter from the scope is overwritten. 
**Describe the solution you'd like**
Be able to specify the merge strategy of the where parameters, in the scope definition and in the FindParams options. See below.

**Describe alternatives you've considered**
Using [Sequelize.and] in the findAll parameters after calling the scope so that age and [Sequelize.and] are NOT merged. I.e.

```
User.scope2().findAll({
   where: {
[Sequelize.Op.and]: [{
        age: {
            [Sequelize.Op.in]: [20, 23, 40, 41, 50, 55]
        }
}]
   }
})
```
However, this only lets me do it once, as the next time I use the Sequelize.and symbol, it will overwrite the previous one.

**Usage example**
Ideal scenario:
```
User.scope2().findAll({
    whereMergeStrategy: 'AND'
})
```

And
```
{
     scope2: () => ({
         whereMergeStrategy: 'AND',
         where: {
             age: {
            [Op.gt]: 30
            }
         },
    })
}

```

**Comment by PatrickGeyer** [comment]
@SimonSchick @knoxcard @sushantdhiman if I created a PR for this would you consider merging?

**Comment by SimonSchick** [comment]
Can't hurt.

**Comment by ephys** [comment]
This should be resolved thanks to:

https://github.com/sequelize/sequelize/pull/14110
https://github.com/sequelize/sequelize/pull/14152
