### ISSUE TITLE
About Model.update?

### ISSUE THREAD

**Issue by qqaimh** [sequelize/sequelize#10877]
I want to use Model.update to plus a number variable based on the  initial value of some cols。
This case  we often see in our project. But how to  solve  it if I use Model.update?
The Document about   Model.update  is so simple

**Comment by SimonSchick** [comment]
Sounds like you want to use Model.increment.

**Comment by qqaimh** [comment]
> Sounds like you want to use Model.increment.

Thank you. You are right.
