### ISSUE TITLE
How can I update a row on N:M table ? 

### ISSUE THREAD

**Issue by jossephalvarez** [sequelize/sequelize#10870]
Hello everyone. 

This is my escenary : 
I've created a relation N:M between supplies and products, the generated table is supplyproducts and in this table has a quantity colum

The bd image is :
https://user-images.githubusercontent.com/17790050/56949780-0baefe80-6b34-11e9-8850-452453240211.png

And my complete example you can see on this repo: https://github.com/jossephalvarez/RA_develpmentv2

My supply controller list supply with products:

listProducts(req, res) {
        return Supply
            .findAll({
                include: [{
                    model: Product,
                    as: 'products'
                }],
            })
            .then((supplies) => res.status(200).send(supplies))
            .catch((error) => {
                res.status(400).send(error);
            });
    },
But i cant see supplyproducts id ( I need to show this id to edit the quantity on another request) 
[
{
        "id": 1,
        "date": "13/04/2019",
        "location_id": 1,
        "UserId": 2,
        "createdAt": "2019-04-29T11:15:12.000Z",
        "updatedAt": "2019-04-29T11:15:12.000Z",
        "products": [
            {
                "id": 1,
                "name": "Primera",
                "price": 1.2,
                "type_id": 1,
                "createdAt": "2019-04-29T11:15:12.000Z",
                "updatedAt": "2019-04-29T11:15:12.000Z",
                "SupplyProduct": {
                    "supply_id": 1,
                    "product_id": 1,
                    "quantity": 10,
                    "createdAt": "2019-04-29T11:15:12.000Z",
                    "updatedAt": "2019-04-29T11:15:12.000Z"
                }
            }
        ]
    }
]

Finally I want to edit the supplyProduct row like this : 
But, if I dont know the Id I cant do the next 👍 

updateSupplyProduct(req, res) {
        return SupplyProduct
            .findById(req.params.id)
            .then(supplyProduct => {
                if (!supplyProduct) {
                    return res.status(404).send({
                        message: 'supplyProduct Not Found',
                    });
                }
                return supplyProduct
                    .update({
                        quantity: req.body.quantity,
                    })
                    .then(() => res.status(200).send(supplyProduct))
                    .catch((error) => res.status(400).send(error));
            })
            .catch((error) => res.status(400).send(error));
    },

Any idea about to edit the quantitty on N:M table ?

**Comment by seromenho** [comment]
Hey, I would say this would be more a general question than an issue. 
[Belongs-To-Many associations documentation](http://docs.sequelizejs.com/manual/associations.html#belongs-to-many-associations) if you know product and supply id's there's no reason to have another id.

**Comment by qqaimh** [comment]
> Hey, I would say this would be more a general question than an issue.
> [Belongs-To-Many associations documentation](http://docs.sequelizejs.com/manual/associations.html#belongs-to-many-associations) if you know product and supply id's there's no reason to have another id.

Can you have a look at my question https://github.com/sequelize/sequelize/issues/10934#issue-442992244
