### ISSUE TITLE
Default UUID value not working

### ISSUE THREAD

**Issue by Swaglis** [sequelize/sequelize#10879]
## What are you doing?
I am trying to define model which has a uuid column which gets automatically generated upon insert.

This is my model: 
```js
export default class PasswordGroupModel extends Model {
}

PasswordGroupModel.init({
    uuid: {
        type: DataTypes.UUID,
        allowNull: false,
        defaultValue: DataTypes.UUIDV1
    },
    name: {
        type: DataTypes.STRING,
        allowNull: false
    }
}, {
    sequelize
});
```

## What do you expect to happen?
After creating new entry I would expect the uuid column to contain a generated uuid.

## What is actually happening?
Instead of an actual uuid the column contains literally the string "UUIDV1". Same result when trying to use UUIDV4

## Environment
Dialect: sqlite 4.0.6
Sequelize version: 5.3.1
OS: WIN10
TypeScript version: 3.4.5
Tested with latest release version: 5.8.2

**Comment by SimonSchick** [comment]
Can you please provide a minimal repro and tell us if this is also happening in v4?

**Comment by knoxcard** [comment]
```
var Todo = sequelize.define('Todo', {
    id: {
      primaryKey: true,
      type: DataTypes.UUID
    }
    // rest of properties
 });
```

https://stackoverflow.com/questions/49864723/sequelize-primarykey-as-uuid-in-mysql-database-not-working

**Comment by knoxcard** [comment]
`Looks like Sequelize has removed the generateUUID() utility method, and started using node-uuid for default UUID values github.com/sequelize/sequelize/blob/master/lib/utils.js#L8 – Chris Oct 28 '15 at 22:30 `

**Comment by SimonSchick** [comment]
@knoxcard that's not a minimal repro, please give me an executable piece of code that demonstrates the behaviour.

**Comment by knoxcard** [comment]
@SimonSchick - lol, i am not the guy who posted this question, I am helping them as you are.  The original poster is @Swaglis

**Comment by Swaglis** [comment]
I've tried creating the minimal repo and it works there as expected. The weird thing is that my repo is actually almost the same as the minimal I've created, with the difference being in my repo models are split into files. Another difference would be that I have more packages installed there so something might interfere with my code. I'll to remake the file structure from my original repo.

**Comment by Swaglis** [comment]
So I've found my error...
In the file where I am creating the Sequelize instance I had this import

`
import { Sequelize } from "Sequelize";
`
it should have been
`
import { Sequelize } from "sequelize";
`

If this is intended behavior(I hope it's not) I guess I'll close this issue.

**Comment by SimonSchick** [comment]
Wait, what?

**Comment by Swaglis** [comment]
Yea well, exactly my reaction. Besides the issue I described up, I had another one when using the "Sequelize" import. When using hasMany relationship, I was getting error that my model is not a subclass of the sequelize Model. This issue also magically disappeared after using lower case 's'.
I really would not expect half of the sequelize functionality to work and other half not to work with "wrong" import.
I'll create the minimal repo tonight.

**Comment by SimonSchick** [comment]
I guess you are running an case insensitive filesystem and the commonjs cache just failed, nice.

**Comment by knoxcard** [comment]
@Swaglis - glad it's all coming to light.  

Thanks for reporting all your findings in a clear detailed manner, so others experiencing similar issues will now have solutions.

Close issue?

**Comment by InclinedScorpio** [comment]
import {Sequelize} from "sequelize" will give error! I am still facing this issue, has anyone found solution?

**Comment by WikiRik** [comment]
> import {Sequelize} from "sequelize" will give error! I am still facing this issue, has anyone found solution?

Please create a new bug report including a SSCCE as per the instructions here; https://github.com/sequelize/sequelize/issues/new?assignees=&labels=&template=bug_report.md&title=
