### ISSUE TITLE
Add logging for `undefined` value of `key`

### ISSUE THREAD

**Issue by vafada** [sequelize/sequelize#10878]
**Is your feature request related to a problem? Please describe.**
It's hard to debug whats causing the error thrown by:

https://github.com/sequelize/sequelize/blob/1b8c389840566d9b31a52e47287725cb604de928/lib/dialects/abstract/query-generator.js#L2059

**Describe the solution you'd like**

Maybe include the Model name in the `Error` string. Something like:

```
throw new Error(`${options.prefix} WHERE parameter "${key}" has invalid "undefined" value`);
```

**Why should this be in Sequelize**

upgrading to v5 now throws this Error which wasn't the case in v4

**Comment by SimonSchick** [comment]
PR welcome.

**Comment by ephys** [comment]
Done in https://github.com/sequelize/sequelize/pull/15598
