### ISSUE TITLE
SELECT GROUP_CONCAT() in Raw Query

### ISSUE THREAD

**Issue by selected-pixel-jameson** [sequelize/sequelize#10876]
I'm running sequelize 5.8.1 and I'm executing a raw query within a promise using MySQL.

```
    sequelize.query(query, { replacements: replacements }).then(([response, metadata]) => {
         return resolve(response)
     }).catch(function (e) {
        return reject(e)
     })
```

This is the query. 

```
SELECT users.*,
      subscriptions.*,
      subscription_plans.*,
      group_concat(DISTINCT user_talk_favorite.talk_id) as favorites,
      group_concat(DISTINCT user_channel_favorite.group_id) as channels,
      group_concat(DISTINCT group_user.group_id) as groups,
      group_concat(DISTINCT roles.name) as roles 
      FROM users 
      LEFT JOIN subscriptions ON subscriptions.user_id = users.id 
      LEFT JOIN subscription_plans ON subscriptions.plan_id = subscription_plans.id 
      LEFT JOIN user_talk_favorite ON user_talk_favorite.user_id = users.id 
      LEFT JOIN user_channel_favorite on user_channel_favorite.user_id = users.id 
      LEFT JOIN group_user ON group_user.user_id = users.id 
      LEFT JOIN model_has_roles ON model_has_roles.model_id = users.id 
      LEFT JOIN roles ON model_has_roles.role_id = roles.id 
      WHERE users.legacy_id = ?
```

The query always returns successful. But the `group_concat()` values randomly don't return. Sometimes none of the `group_concat()` values return sometimes one returns sometimes all of them return. It seems to be completely random. 

If I run this query directly in my MySQL GUI it works fine every time. I also tried using just the mysql2 node library and it works fine as well. I'm not sure what else to try here. 

Thanks!

**Comment by knoxcard** [comment]
In the mean time, try turning on logging. It will show you the exact SQL that Sequelize generates.  I've used this a dozen times to self diagnose these crazy SQL issues.  Please report your findings when you can, thanks!

For example...
```
  var Sequelize = require('sequelize'),
    sequelize = new Sequelize(process.env.db_name, process.env.db_user, process.env.db_pass, {
      dialect: 'mariadb',
      port: process.env.db_port,
      pool: {
        min: 1,
        max: 60,
        idle: 10000
      },
      define: {
        charset: 'utf8mb4'
      },
      benchmark: false,
      logging: true
    })
```

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.
