### ISSUE TITLE
Uncatchable Validation Errors

### ISSUE THREAD

**Issue by houseofrayne** [sequelize/sequelize#10888]
I have an Node/Express/Sequelize API that I have been attempting to backfill sequelize field based validations into. It was when I was about to hack out my error handler configurations and such to accomplish this task, when it came to my attention that there seems to be no clean or correct way to get the thrown SequelizeValidationError to be caught within my catch block and sent via next to my error handler, so the route then inevitably returns an error html page for the uncaught error. This is absolutely not the expectation.

I have brought this same issue up on the Sequelize Slack channel, and got no results there either.

I have also cobbled together a little example api that demonstrates the issue well. If you clone the repo, copy the .env.example to .env, then set your postgres configuration info in the .env.

Then run sequelize db:migrate npm i and npm start, there is a swagger document that should serve itself on port 8000/api-docs.

The easiest way to reproduce this issue from here is to try the user create route in swagger. http://localhost:8000/api-docs/

Keep the example object here the same, causing the valid email validation to trigger, since "string" is not a valid email. The associated error, as you can see, is thrown, but not catchable and passable to my error handler in /server/config/errors.

I have already tried replacing the await in /server/controllers/user.js in the create route with the .then.catch syntax, and I cannot seem to get the error to throw into the catch block for that method.

I have also tried wrapping the query in it's own try catch. I have even tried a wrapper function, in hopes that would give me access. It seems the validation errors though are thrown outside of the controller flow.

https://bitbucket.org/draconusdesigns/sequelize-api-example/src/master/

My expected results are that I can catch the sequelize validation errors the same as I would any other errors, without having to implement nasty anti patterns to compensate for this issue.

**Comment by houseofrayne** [comment]
I am convinced after trying so many permutations to resolve this that there is a bug within the SequelizeValidationError itself.

**Comment by houseofrayne** [comment]
Once I can get this figured out I'm more than willing to write a Sequelize tutorial for version 5 that includes not only validation but also examples of the various relations as well, to give a more comprehensive getting started guide, via a solid tutorial with backing repo of an example project.

**Comment by SimonSchick** [comment]
Can you please provide a minimal repro? I believe this is a usage error because I can catch them locally just fine

**Comment by SimonSchick** [comment]
Also there seems to be no `auth.js`?

**Comment by houseofrayne** [comment]
I did provide a repo with an example, and described within the example how to simply reproduce the issue, see above. https://bitbucket.org/draconusdesigns/sequelize-api-example/src/master/

The easiest way to reproduce this issue from here is to try the user registration route in swagger. http://localhost:8000/api-docs/#/Auth/post_auth_register

Keep the example object here the same, causing the valid email validation to trigger, since "string" is not a valid email. The associated error, as you can see, is thrown, but not catchable and passable to my error handler in /server/config/errors.

**Comment by houseofrayne** [comment]
So the route I suggest trying this with is /auth/register.

**Comment by houseofrayne** [comment]
I have now made it even more simple. user create

**Comment by eseliger** [comment]
the last commit was 2 days ago

**Comment by houseofrayne** [comment]
Nervmind, this is why this bug has persisted in this shitty ORM since 2011. You refuse to read or understand the issue and you blame every engineer who comes across it. fuck you, I will switch to type orm or bookshelf. at least their community support isn't a bunch of assholes.

**Comment by SimonSchick** [comment]
@houseofrayne please be aware this kind of behaviour will not be tolerated.
