### ISSUE TITLE
Reuse same pool across diferente sequelize instances

### ISSUE THREAD

**Issue by seromenho** [sequelize/sequelize#10887]
**Is your feature request related to a problem? Please describe.**
Having same models on multiple schemas:
1) either we create multiple instances passing schema for each one
2) or we create one passing `searchPath` on each query
3) or some other i'm not considering but open to do so please let me know

So my problem is either have different pools or pass searchPath on each query. I would like to avoid have one pool per sequelize instance.

**Describe the solution you'd like**
I would like to have just one pool, but at the same time I don't like to manually pass searchPath on each query because if I miss to pass in one query then it will search on the previous set search path.
I would prefer the first options since we just need to pass the schema once on the constructor.

**Why should this be in Sequelize**
Sequelize already handles schema and searchPath. I don't see the need of an exernal package, or maybe this should belong on `sequelize-pool` package.

**Describe alternatives you've considered**
I've considered to pass searchPath on each and every query having just one instance of sequelize. 
Another alternative would be not passing searchPath at all, but having schema instead to pass on queries so it prepend the schema name on the table names like it does when is specified on the constructor. 
I guess either passing a pool on the constructor or schema on each query is fine. 

**Usage example**
Not really sure, first would like to hear from you if at least this makes sense.
But I was thinking in somethink like passing let's say a name for the pool instead of the `sequelize` default one. When creating the pool on sequelize-pool cache it somehow by name.
When it's time to create a new one, first check if we have one already cached by name.
```javascript
const options = {
  dialect: 'postgres',
  pool: {
    name: 'reuse-me'
  }, 
  schema: 'dev'
};
const sequelize = new Sequelize(url, options);
```

**Additional context**

**Comment by ephys** [comment]
I'll close as it's unlikely this is ever going to be implemented. The only element we could share from the pool is the limit. The elements in the pool themselves cannot be shared between two sequelize instances.

It's a large change for what looks like low demand. I think you're better off specifying the schema on the models themselves. I don't have a real solution for raw queries unfortunately
