### ISSUE TITLE
Why do Endpoints not work in AWS?

### ISSUE THREAD

**Issue by VishalUZ** [sequelize/sequelize#10882]
Today I did my very first AWS setup for an Angular project with the following connection to AWS database:
  "database": "testdb",
  "username": "username",
  "password": "secret",
  "host": "xxx.yyy.zzz.rds.amazonaws.com ",
  "protocol": "postgres",
  "logging": true,
  "dialect": "postgres",
  "port": 5432
For "host" (see above) if I enter the IP of my AWS then all works fine but, if I enter my "endpoint string" like shown above then it gives me an error as, “Unhandled rejection SequelizeHostNotFoundError”.
Kindly advise on a solution for this issue.
Thanks in advance.

**Comment by eseliger** [comment]
This most likely is a problem with your DNS resolution
please check 

```js
const dns = require('dns')
dns.resolve('YOUR_RDS_HOST', (err, result) => err ? console.error(err) : console.log(result))
```
