### ISSUE TITLE
Using a findAll with where including both Op.in and Op.notIn arguments

### ISSUE THREAD

**Issue by alignsoft** [sequelize/sequelize#10905]
## What was unclear/insufficient/not covered in the documentation
How to make use of multiple operators to create a fetch of objects with an exclusion clause.

### If possible: Provide some suggestion how we can enhance the docs

I have a table of images with a bidirectional hasMany relationship to a table of keywords through a join table.

I want to find all images that include keyword IDs in an array of IDs [kewordsAnd], excluding images that have keyword IDs in an array to exclude [keywordsNot].

The code right now is as follows:

```
Image.findAll({
  include: [ {
    model: Keywords,
    as: 'Keywords',
    attributes: ['id', 'name'],
    where: {
      id: {
        [Op.and]: [
          { [Op.in]: keywordsAnd },
          { [Op.notIn]: keywordsNot }
        ]
      }
    }
  } ]
});
```

This correctly fetches all images that have IDs in the keywordsAnd array, but the keywordsNot array is completely ignored.

This is the generated SQL (line breaks added for readability)

```
const objectsAnd:  [ 430 ]
const objectsNot:  [ 779 ]
Executing (default): 

SELECT `image`.`id`, `image`.`status`, `image`.`image_type`, `image`.`embed`, 
`image`.`raw_path`, `image`.`thumb_path`, `image`.`detail_path`, `image`.`story_title`, 
`image`.`image_title`, `image`.`original_filename`, `image`.`description`, 
`image`.`geo_info`, `image`.`year_taken`, `image`.`credit_info`, 
`image`.`width`, `image`.`height`, `image`.`format`, `image`.`duration`, 
`image`.`created_at` 

AS `createdAt`, `image`.`updated_at` AS `updatedAt`, `keywords`.`id` AS `keywords.id`, 
`keywords`.`name` AS `keywords.name`, `keywords`.`created_at` AS `keywords.createdAt`, 
`keywords`.`updated_at` AS `keywords.updatedAt`, `keywords->image_keywords`.`id` AS 
`keywords.image_keywords.id`, `keywords->image_keywords`.`image_id` AS 
`keywords.image_keywords.image_id`, `keywords->image_keywords`.`keyword_id` AS 
`keywords.image_keywords.keyword_id`, `keywords->image_keywords`.`created_at` AS 
`keywords.image_keywords.createdAt`, `keywords->image_keywords`.`updated_at` AS 
`keywords.image_keywords.updatedAt` 

FROM `image` AS `image` INNER JOIN ( `image_keywords` AS `keywords->image_keywords` 
INNER JOIN `keywords` AS `keywords` 
ON `keywords`.`id` = `keywords->image_keywords`.`keyword_id`) 
ON `image`.`id` = `keywords->image_keywords`.`image_id` 
AND (`keywords`.`id` IN (430) AND `keywords`.`id` NOT IN (779));
```

I'm not clear if this is an issue with how I'm structuring the query, or a bug, or a complete misunderstanding on my part as to how this should work, but I'm really hoping for some guidance.

**Comment by papb** [comment]
Hello, I agree with you that your call should work as you were expecting...

You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Can you provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))?
