### ISSUE TITLE
'attributes' option in findAll does not overwrite scope

### ISSUE THREAD

**Issue by vekexasia** [sequelize/sequelize#10904]
## What are you doing?
```ts
it('test2', async () => {
    class Brocca extends Model {}
    const s = new Sequelize('test', 'test', 'password', {dialect: 'postgres', logging: true});
    Brocca.init({}, {
      defaultScope: {
        attributes: ['a', 'b', 'c'],
      },
      sequelize: s,
      tableName: 'brocca',
    });
   // here -> Error!
    await Brocca.findAll({attributes:['a']});
  });
```

**To Reproduce**
1. Define models above
2. Run the code
3. See Sql statement

## What do you expect to happen?
Should run: `SELECT "a" FROM "brocca" AS "Brocca";`

## What is actually happening?
But it runs: `SELECT "a", "b", "c" FROM "brocca" AS "Brocca";`

## Environment
Dialect:
- [x] postgres
Dialect **library** version: ?
Database version: irrelevant
Sequelize version: 5.8.5
Node Version: 10
OS: ubuntu
If TypeScript related: TypeScript version: irrelevant
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.8.5

## Additional infos.

Looks like https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3115-L3118 is the cause of expanding the `options`.
`_injectScope` is called here: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1697

**Comment by vekexasia** [comment]
Hello guys, did you have the time to take a look at this?

**Comment by papb** [comment]
@vekexasia Hello! Thanks for the issue, sorry to take long to reply.

Quoting the docs:

> Note that `attributes` keys of multiple applied scopes are merged in such a way that `attributes.exclude` are always preserved. This allows merging several scopes and never leaking sensitive fields in final scope.

This does not make clear what is the desired behavior for your code. I could imagine people arguing that both behaviors are acceptable.

I have marked this as 'discussion' so that it can be decided which behavior is more desirable.

**Comment by andrejleitner** [comment]
Hey folks! It seems, that this issue also breaks the transition between versions 4 and 5.
