### ISSUE TITLE
 Cannot find module './dialects/mysql/data-types'

### ISSUE THREAD

**Issue by devprakashbinary** [sequelize/sequelize#10908]
my code is 
import  Sequelize from 'sequelize';
const connnection = new Sequelize('gmc', 'root', 'root@123', {
  host: 'localhost',
  dialect: 'mysql',

  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
});

connnection
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });

export default connnection;

![Screen Shot 2019-05-07 at 07 40 12](https://user-images.githubusercontent.com/38106321/57266846-64821800-709b-11e9-897d-f00638193232.png)

**Comment by vicse** [comment]
I have the same error, would you tell me how you solved it?

**Comment by amaanrajput940** [comment]
I am getting same error, Anyone can help me how can I fix it ?

**Comment by papb** [comment]
@amaanrajput940 Please open a new issue following the standard bug report template and we will look into it. Thanks.

**Comment by amaanrajput940** [comment]
@papb Actually I deployed my node js app on AWS Ec2 and when I go to execute this command sequelize db:migrate then I get this error Cannot find module './dialects/mysql/data-types'

**Comment by papb** [comment]
@amaanrajput940 If you need help, I really need you to open a new issue... Good luck!

**Comment by ankitkataria9** [comment]
In my case **node_modules/sequelize/lib/dialects** don't contain **mysql** dialects.
So, I copied them from the github repo [here](https://github.com/sequelize/sequelize/tree/master/lib/dialects).
this resolves my issue.
Good Luck

**Comment by vinaynagpal9** [comment]
the repo is not opening? which you mentioned

**Comment by WikiRik** [comment]
I'm not sure if you still need it, but for the stable v6 version that folder is now [here](https://github.com/sequelize/sequelize/tree/v6/src/dialects/mysql) (and [here](https://github.com/sequelize/sequelize/tree/main/src/dialects/mysql) for the main branch)

**Comment by ojimcy** [comment]
I fixed this use by switching node version

Node version 15 worked for "sequelize": "^6.21.3",

**Comment by jcplus** [comment]
I remove the sequelize then reinstall fixed the issue. hope this helps
