### ISSUE TITLE
how to use multi mysql funcction to query data?

### ISSUE THREAD

**Issue by jjeejj** [sequelize/sequelize#10919]
eg: 
```js
where: 
sequelize.where(
            sequelize.fn('DATE_FORMAT', sequelize.col('Start_Time'), '%Y-%m-%d'), '2019-11-12'
        )
 and sequelize.where(
            sequelize.fn('DATE_FORMAT', sequelize.col('End_Time'), '%Y-%m-%d'), '2019-12-12'
        )
```
how use query data by  Start_Time and End_Time condition ?

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
