### ISSUE TITLE
TypeScript toJSON should return real schema

### ISSUE THREAD

**Issue by zjy01** [sequelize/sequelize#10917]
**Describe the solution you'd like**
I want to get the  real schema when i use toJSON();

**Why should this be in Sequelize**
It is more good for TypeScript

**Usage example**
How can the requested feature be used to approach the problem it's supposed to solve.
```js
const result = await Model.findOne();
const obj =  result.toJSON(); // model schema
const id = obj.id; // number
```

**Comment by papb** [comment]
Hello, it is not clear to me what you mean. Can you give a more detailed description, please?

**Comment by sunwukonga** [comment]
Currently, for the lack of a model schema on `toJSON()` return:
```
const result = await Model.findOne();
const obj =  result.toJSON(); 
const id = obj.id; //  Typescript error: Property 'id' does not exist on type 'object'.
```

Ultimately, this would be because `.get()` doesn't have a model schema attached. Since, (I believe), `toJSON()` is really calling `.get()`

**Comment by alvadorn** [comment]
Why `.get({ plain: true })` returns typed object and `.toJSON()` doesn't?

**Comment by ephys** [comment]
Because the point of `toJSON` is to be compatible with `JSON.stringify` and nothing else, it's not meant for direct consumption.

Closing this thread, use `.get()`
