### ISSUE TITLE
Prettify JSON - MySQL/MariaDB

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#10913]
Recently I found the need to "prettify" my JSON columns in my database.
https://stackoverflow.com/questions/2614862/how-can-i-beautify-json-programmatically

**Before** (_yeesh!_)
```
{"city": "Vassar", "referer": "https://www.google.com/", "state": "MI", "zip": "48768", "country": "US", "latitude": "43.0000", "longitude": "-84.0000", "useragent": { "isBot": false,   "browser": "Safari",   "version": "12.0",   "os": "OS X",   "platform": "iPhone"}}
```

**After** (_Ahhh!_)
```
{
    "city": "Vassar",
    "referer": "https://www.google.com/",
    "state": "MI",
    "zip": "48768",
    "country": "US",
    "latitude": "43.0000",
    "longitude": "-84.0000",
    "useragent": {
        "isBot": false,
        "browser": "Safari",
        "version": "12.0",
        "os": "OS X",
        "platform": "iPhone"
    }
}
```

Currently, with Sequelize, the JSON datatype columns are stored as LONGTEXT and the objects are stored as hard to read one liners.

I decided to create global hooks on afterUpdate and afterInsert to autodetect the JSON columns on all models, JSON.stringify'ing with 4 spaces.  Now it's permanently stored as beautiful human readable data, ya dig?  

Two writes and one read will occur on models that contain JSON columns. 

(Advertisement: https://github.com/HeidiSQL/HeidiSQL viewer rocksfor MySQL/MariaDB/MSSQL!  Use it!)

**Full Config **
```
  var Sequelize = require('sequelize'),
    sequelize = new Sequelize(process.env.db_name, process.env.db_user, process.env.db_pass, {
    host: process.env.db_host,
    port: process.env.db_port,
    dialect: 'mariadb',
    dialectOptions: {
      timezone: process.env.db_timezone
    },
    pool: {
      min: 0,
      max: 2,
      idle: 10000
    },
    define: {
      charset: 'utf8',
      timestamps: false,
      hooks: {
        afterCreate: (model, fn) => {
          formatCols(model)
        },
        afterUpdate: (model, fn) => {
          formatCols(model)
        }
      }
    },
    benchmark: false,
    logging: false
  })
function formatCols(model) {
    for(let json_key in model.rawAttributes) {
      if(model.rawAttributes[json_key].type.key.toUpperCase() == 'JSON') {
        var obj = app.get('functions').objEscapeDblQuotes(model[json_key]),
          json_val = JSON.stringify(obj, null, app.get('json spaces'))
        json_val = json_val.replace(/\\([\s\S])|(")/g, "\\$1$2")
        json_val = json_val.replace(/'/g, "\\'")
        var raw_sql_string = "UPDATE `" + model.constructor.name + "` SET `" + json_key + "` = \'" + json_val + "\' WHERE id = " + model.id
        app.get('sequelize').query(raw_sql_string).then(([results, metadata]) => {
        })
      }
    }
}
```

**Comment by papb** [comment]
I did not understand what is going on here.

> ```js
> app.get('sequelize').query(raw_sql_string).then(([results, metadata]) => {
> })
> ```

This, inside a for loop, seem to dispatch several queries in parallel and `.then` do nothing?

Regardless, I am confused, are you trying to beautify the text present in the database itself? Or what? Can you describe your goal a bit more? Thanks and sorry for not understanding at the first read!

**Comment by knoxcard** [comment]
@papb - updated the code, can you give it a try and let me know?

**Comment by papb** [comment]
> Regardless, I am confused, are you trying to beautify the text present in the database itself? Or what? Can you describe your goal a bit more? Thanks and sorry for not understanding at the first read!

Can you respond to this directly? I am still confused...

**Comment by knoxcard** [comment]
This code is to beautify the text in the database itself.

**Comment by papb** [comment]
Ah, I see. Why not use `before` hooks instead of `hooks`? You wouldn't need extra queries.

**Comment by knoxcard** [comment]
@sushantdhiman - see what I've done here?  It is supperr helpful in reading mysql JSON data from the DB.

**Comment by knoxcard** [comment]
@papb - wouldn't you still need two beforeHooks: **beforeUpdate()** and **beforeUpdate()**?

**Comment by papb** [comment]
Hello, let me try to understand this better. Your goal is to save formatted JSON directly in the database, right? That doesn't make sense to me, can you please elaborate? Why should I spend a lot of extra bytes with `\n`, `t`, spaces and such things?

**Comment by knoxcard** [comment]
I do this because that's how I view all my site information.  Lots of people do not have admin sections to their site and they view their raw mysql data.  I use a database viewer: HeidiSQL,

**Comment by papb** [comment]
@knoxcard Hmm, I see... Still, I think it's a bit too specific to be built-in in sequelize. Perhaps you can write a plugin or something?

Also:

> @papb - wouldn't you still need two beforeHooks: **beforeUpdate()** and **beforeUpdate()**?

What did you really mean here?

**Comment by knoxcard** [comment]
@papb - agreed, too much for Sequelize, already moved it over to the mariadb driver npm. 
https://github.com/MariaDB/mariadb-connector-nodejs/issues/68
