### ISSUE TITLE
bluebird lose typescript

### ISSUE THREAD

**Issue by zjy01** [sequelize/sequelize#10916]
## What are you doing?

I wan't to use Model.findAll but i get result type = any.
Then I find that bluebird do not has typescript itself.
```js
// code here
```
**To Reproduce**
1. Define models X, Y, ...
2. Run the following
3. See error

## What do you expect to happen?
_I wanted get really model when i use Model.findAll without any other dependencies!_

## What is actually happening?
_But now i need to add `@types/bluebird` myself!_

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: XXX
Sequelize version: XXX
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: 3.4.5
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.8.5

**Comment by SimonSchick** [comment]
https://github.com/sequelize/sequelize/blob/master/docs/typescript.md

This is currently intended but might change in the future.

**Comment by zjy01** [comment]
OK, I'm sorry I ignored it.
