### ISSUE TITLE
sequelize.sync hang on SHOW INDEX,  promise not resolve on CentOS

### ISSUE THREAD

**Issue by nfwyst** [sequelize/sequelize#10915]
## What are you doing?
I have a user model, and a company model,  and the user belongs to company

```js
// user.js
User.belongsTo(Company, { foreignKey: 'cid', targetKey: 'id' })
```

then I start my express server by following code:

```js
    const {
      mongodb: { url, option },
      server: { port }
    } = this.config
    const mongoPromise = mongoose.connect(url, option)

    // sync mysql model
    const syncPromise = this.db.sync({ force: true })

    // wait for sync 
    Promise.all([
      mongoPromise,
      syncPromise
    ]).then(() => {
      const server = app.listen(port, () => {
        console.log(
          `${new Date().toLocaleString()} server is running on port: http://localhost:${port}`
        )
      })
      //...
    }).catch(e => {
      console.error(e)
      process.exit(0)
    })
```

I want Promise.all resolve correctly, there is no problem on mac os,  but its hang on syncing
when running on CentOS, so the server cant be started.

## Environment
Dialect:
-  mysql

Dialect **library** version: XXX
Database version: Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper
Sequelize version: 5.8.5
Node Version: 10.14.1
OS: CentOS

Tested with latest release:
- Yes, specify that version: 5.8.5

**Comment by papb** [comment]
Which of the promises hangs on CentOS, `mongoPromise` or `syncPromise`?

**Comment by nfwyst** [comment]
> Which of the promises hangs on CentOS, `mongoPromise` or `syncPromise`?

its syncPromise, but I solved this temporarily by setTime to start server

**Comment by papb** [comment]
Looks like this is a problem with your setup involving async thigns, not sequelize itself. Have you tried chaining the promises instead of using `Promise.all`?
