### ISSUE TITLE
the performance of sequelize (sqlite) is very very low on Ubuntu 16.04

### ISSUE THREAD

**Issue by yuanqiuqian** [sequelize/sequelize#10927]
## What are you doing?
the performance of sequelize is very low on Ubuntu 16.04

```js
const Sequelize = require("sequelize");
var sqlite3 = require("sqlite3");

const sequelize = new Sequelize({
  dialect: "sqlite",
  storage: "./zaap.db"
});

const tbUser = sequelize.define(
  "TbUser",
  {
    username: {
      type: Sequelize.STRING(50),
      allowNull: false
    }
  },
  { timestamps: false, paranoid: true }
);

sequelize
  .sync({ force: true })
  .then(async () => {
    var timestamp = Date.now();
    for (var i = 0; i < 1000; i++) {
      await tbUser.create({ username: "hello,world" });
    }
    console.log("sequelize-----", Date.now() - timestamp);
  })
  .then(async () => {
    var sqlitedb = new sqlite3.Database("zaap.db");

    var timestamp = Date.now();
    for (var i = 0; i < 1000; i++) {
      await sqlitedb.run(
        "insert into TbUsers('username') values('hello,world')"
      );
    }
    console.log("sqlite3-----", Date.now() - timestamp);
  });

```
**To Reproduce**
1. node run.js
2. Run the following
3. See result
## What is actually happening?
![image](https://user-images.githubusercontent.com/20298940/57518532-c8cb0300-734b-11e9-880a-440ad0379f9a.png)

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [x] sqlite
- [ ] mssql
- [ ] any
Database version: 4.0.7
Sequelize version: 5.8.5
Node Version: v8.11.3
OS: Ubuntu 16.04
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by SimonSchick** [comment]
I think this benchmark isn't exactly valid, iirc sqlite3 doesn't have native promise support, you would have to promisify `run` first.

**Comment by ephys** [comment]
Yep, `database.run` doesn't return a promise so it's normal that the execution time is incredibly small - you're not waiting for the operation to complete

Thread has been dead for 3 years, closing
