### ISSUE TITLE
Typescript: Model.findAll returns any

### ISSUE THREAD

**Issue by nicgirault** [sequelize/sequelize#10928]
```typescript
import { Sequelize, Model, DataTypes } from 'sequelize'

const sequelize = new Sequelize('postgres://user:password@localhost:5432/db')

export class User extends Model {
  public id?: number
  public name!: string
}

User.init(
  {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  },
  {
    sequelize,
    tableName: 'user',
  }
)

async function test() {
  const users = await User.findAll()
}
```

`users` is typed as any. I would have expected it to be of type `User[]`. I use sequelize 5.8.5 and typescript 3.4.5.

It seems that the static definition of `findAll` is overrided by a method.

![image](https://user-images.githubusercontent.com/551837/57519976-d74df600-731c-11e9-8c5b-6a91d8ee6a8d.png)

**Comment by upcyoung** [comment]
see [typescript install](https://sequelize.org/master/manual/typescript.html)

@types/node (this is universally required)
@types/validator
@types/bluebird

**Comment by anault** [comment]
`@types/bluebird` isn't needed anymore. See https://sequelize.org/master/manual/typescript.html Commit: https://github.com/sequelize/sequelize/commit/5a807c514c00364d0fcd56ae682a06750c398df8#diff-32aa50e374d64b4bb35a1d2298bf5e79

**Comment by Andrew1431** [comment]
I'm having this issue still. 

![image](https://user-images.githubusercontent.com/9736372/86009868-b0eb8e00-b9e8-11ea-9fe8-cc5b48003a99.png)

```json

    "@types/node": "^14.0.14",
    "@types/validator": "^13.1.0",

    "typescript": "^3.9.2"

    "sequelize": "^5.21.11"
```

And to add the insult to injury, when I cmd+click (follow) the `findAll` method (amongst every other function), they all resolve properly and point to what should be functioning properly. This also seems to just have popped out of nowhere for some reason.

![image](https://user-images.githubusercontent.com/9736372/86010048-e6907700-b9e8-11ea-90b7-0c11dff4a6bf.png)

**Comment by dougmaitelli** [comment]
I am also facing exactly the same

**Comment by Andrew1431** [comment]
I’ll hook you up with my solution later today. It uses namespace
declaration merging feature of ts

**Comment by Andrew1431** [comment]
Oops sorry I thought your response was for another issue. 

If you're on <v6 of sequelize, you need to add bluebird types as a dependency. Otherwise upgrade sequelize to v6. That is what their current documentation represents regarding only needing validators and node types
