### ISSUE TITLE
TypeScript operatorsAliases can't set boolean

### ISSUE THREAD

**Issue by zjy01** [sequelize/sequelize#10923]
## What are you doing?

I wan't to set `operatorsAliases = false` in config.

```js
// code here
```
**To Reproduce**
1. set `operatorsAliases = false`
2. see `(property) operatorsAliases?: PowerPartial<OperatorsAliases>`, but no `boolean`

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any

If TypeScript related: TypeScript version: 3.4.5
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.8.5

**Comment by SimonSchick** [comment]
This is intended.

https://github.com/sequelize/sequelize/blob/379b56c873d1c68bee1f48a828b14662de070834/lib/utils/deprecations.js#L10
