### ISSUE TITLE
findByPk options where does't work 

### ISSUE THREAD

**Issue by YinghaoFu** [sequelize/sequelize#10925]
"sequelize": "^5.6.0"  
in docment:
"See:
Model.findAll for a full explanation of options"
I try add 'where' to findByPk's options,but it's did't work.

**Comment by seromenho** [comment]
There is no `where` on the options to [findByPk.
Documentation here](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findByPk)

**Comment by YinghaoFu** [comment]
> There is no `where` on the options to `findByPk`
> [Documentation here](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findByPk)
Documentation here

> Model.findAll for a full explanation of options 
It's does't say no `where` on on the options to `findByPk`.

**Comment by smuralimohan** [comment]
Hi, I am testing Sequelize using Postgres dialect. For some reason, **findByPk(1)** (with id = 1) does not work at all. And it is not just findByPk(1) that does not work, but also **findOne({where: {id:1}}), findAll({ where: {id:1} })** and **findAll({ where: { id: { [Op.eq] : 1}  }})** don't work.

However, for ids > 1 it is working fine. I tested using in-memory SQLite also and the problem exists there as well. 
My sequelize and node versions are as below.

"pg": "^8.7.1",
 "pg-hstore": "^2.3.4",
 "sequelize": "^6.12.0",

Node: v16.13.0

My database table have the following records.
id      name                notes
1	"Daily Dose"	"Diabetes, BP"
2	"Daily Dose"	"Diabetes, BP"
3	"Daily Dose"	"Sugar, BP"
