### ISSUE TITLE
Can `update()` return `[0]` when the row exists?

### ISSUE THREAD

**Issue by catamphetamine** [sequelize/sequelize#10922]
For some reason calling `Model.update(values, { where: ... })` returns `[0]` as if the updated row wasn't found but at the same time `Model.findOne({ where: ... })` returns the row and it is found.

**Comment by SimonSchick** [comment]
Was the row actually changed?

**Comment by catamphetamine** [comment]
@SimonSchick Thanks, I found the reason: `values` was `undefined`.
Perhaps in some future major version Sequelize could throw is `values` is `undefined` because it's a "no op".

**Comment by catamphetamine** [comment]
@SimonSchick Actually, `values` wasn't `undefined`.
The reason was that `values` didn't contain any valid SQL fields to update.

> The promise returns an array with one or two elements. The first element is always the number of affected rows

**Comment by catamphetamine** [comment]
@SimonSchick but, consider a case where there's a home-made version locking with a `version: INT` column.
Then the `UPDATE` query is `version = 124 WHERE version = 123` and if that doesn't update the record then the error is shown: "Someone already edited that row".
Now, if a user saves the same data Sequelize will still return `0` and the error message will be shown.
Returning the "changed rows count" is broken and should instead be "updated rows count" regardless of whether the actual values changed.

**Comment by axellosantos** [comment]
Same problem on Sequelize v6. There is no way to handle when there was an update of 0 rows affected but row exists. It should return if execution was OK instead of rows affected. Any chance to solve this?

**Comment by MysteriousMsn** [comment]
I am trying to update the totalLikes but getting [0];
await communityService.updateTotalLikes({ totalLikes }, { where: { id: communityId } });

communityService.updateTotalLikes = (data, query) => {
  return communityModel.update(data, query);
};

**Comment by HimanshuMishir** [comment]
Yes if the row is already updated with the same value!

**Comment by BilalLatif** [comment]
> @SimonSchick Thanks, I found the reason: `values` didn't contain any valid SQL fields to update.
> 
> > The promise returns an array with one or two elements. The first element is always the number of affected rows
> 
> So seems that Sequelize returns `0` if no data was updated (for example, if data was the same).

Hi @catamphetamine can you please elaborate on what do you mean by valid SQL fields? I am facing a similar issue, everytime i tried to update any column other than 'id' column the update function returns [0] but when it comes to 'id' column it works perfectly fine, please advise if you know about this behaviour. TIA. my database id 'mariadb'

**Comment by catamphetamine** [comment]
@BilalLatif 

> can you please elaborate on what do you mean by valid SQL fields? 

I don't remember but judging from the context I guess it meant that the object argument that the `.update()` function was called with didn't contain any known model properties, so the update was a "no op", i.e. any unknown properties of the object argument were ignored.
