### ISSUE TITLE
Formatting of createdAt and updatedAt columns undocumented

### ISSUE THREAD

**Issue by range-of-motion** [sequelize/sequelize#10929]
## What was unclear/insufficient/not covered in the documentation

How to format the `createdAt` and `updatedAt` columns' values into something useable like YYYY-MM-DD.

### If possible: Provide some suggestion how we can enhance the docs

I had to use the following dialect options to make sure I didn't get weird date formatting (why the hell would you show my timezone in the format as "Central European"?).

Would be nice if this would be documented and explained what these options actually do. I still don't know.

```js
dialectOptions: {
  dateStrings: true,
  typeCast: true
}
```

**Comment by papb** [comment]
@range-of-motion Which dialect were you using? What was the behavior without those options and with those options? Thanks!

**Comment by range-of-motion** [comment]
MySQL. No clue. I just wanted to grab the createdAt and updatedAt values in YYYY-MM-DD format.

**Comment by papb** [comment]
Ah, I thought you found out how to use those options. Looks like you still don't know, right?

(I don't know either, would have to check)

**Comment by ephys** [comment]
These `dialectOptions` are not from Sequelize, they are passed as-is to your connector library (eg `pg`, `mysql2`, etc), you can find the relevant documentation about it there.

`createdAt` / `updatedAt` are always datetimes. There is [an issue](https://github.com/sequelize/sequelize/issues/14257) about supporting other types which apply to these two as well

I will close this issue seeing as it's a bit dead and the issue I linked covers the remainder of this issue
