### ISSUE TITLE
Included models are failing to properly inject attributes for virtual fields

### ISSUE THREAD

**Issue by imathews** [sequelize/sequelize#10930]
## What are you doing?
I have defined a model, `Image`, with the virtual field `url`. This virtual field is dependent on another attribute, `path`.

```js
path: Sequelize.STRING,
url: {
	type: Sequelize.VIRTUAL(Sequelize.STRING, ['path']),
		get: function() {
		if (this.getDataValue('path')) {
			return `${process.env.IMAGE_ROOT}/${this.getDataValue('path')}`;
		} else {
			return null;
		}
	},
},
```
This model is associated with the User model. I have a User w/ id 1, and an Image belonging to that user (also w/ id 1). This image has a path, `'my-path'`.

If I look up the image by id, everything works as expected:
```js
// image.path === `${process.env.IMAGE_ROOT}/my-path`
const image = await Image.findByPk(1, { attributes: ['id', 'url'] })
```

However, if we look up the image by including on the user, image.path is null:
```js 
// user.image.path === null; should === `${process.env.IMAGE_ROOT}/my-path`
const user = await User.findByPk(1, { 
    attributes: ['id'], 
    include: { model: Image, attributes: ['id', 'url']} 
})
```
I can confirm Sequelize is generating the proper DB query, but isn't assigning the `path` attribute on the retrieved image instance when it's included, preventing us from generating the appropriate (virtual field) `url` in the getter.

I was able to solve this issue with the following modification, but am not familiar enough with the codebase to know if this is appropriate:
https://github.com/redivis/sequelize/commit/d4ad97d33819ee1d6110909c761de98cd52be73f

## Environment
Dialect:
- [x] postgres
Database version: 11.x
Sequelize version: 5.x
Node Version: 12.x
Tested with latest release:
- [ ] No
- [ ] Yes, specify that version:

**Comment by ajmueller** [comment]
I am running into the same issue and it's causing some frustration.  It leads to writing a lot of extra, explicit code, but only for included models.

**Comment by leonardorb** [comment]
Any updates on this? This completely broke our app. `Sequelize` is actually looking for a column at the database level and completely ignoring the `VIRTUAL` type. And this is happening only when a model is at the `include` level. So, I'm getting:
```
error: column users.full_name does not exist
```
And this is my setup:
```
full_name: {
  type: DataTypes.VIRTUAL,
  get() {
    return `${this.getDataValue('first_name')} ${this.getDataValue('last_name')}`
  },
},
```

**Comment by stevelacy** [comment]
Also getting this, our entire stack uses virtuals for included models.

**Comment by papb** [comment]
Related: #10932

**Comment by papb** [comment]
Note: I have started investigating this. Hopefully I will have time to complete it soon.

**Comment by thieman** [comment]
Big +1 here, we'd like to get on v5 but if we can't trust our includes to work correctly then we're stuck on 4.

**Comment by stevelacy** [comment]
@papb the fix by @imathews does indeed work for us and passes all tests.
@imathews do you want to send a PR with this fix? I'll 👍it, cheers

**Comment by imathews** [comment]
@papb @stevelacy @thieman https://github.com/sequelize/sequelize/pull/11713

I don't have the bandwidth to update the tests, if anyone else wants to tackle...
