### ISSUE TITLE
[Op.like]: example from documentation throws SQL error

### ISSUE THREAD

**Issue by alignsoft** [sequelize/sequelize#10940]
## What are you doing?

Using the following example from the documentation throws a SQL error on MySQL
```
    Media.findAll({
        where: {
            image_title: {
                [Op.like]: { [Op.any]: ['cat', 'hat']}
            }
        }
    })
```

**To Reproduce**

Perform the above query - generated SQL in Node/Express is as follows:
```
`Executing (default): SELECT `id`, `story_title`, `image_title`, `original_filename`, 
`created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `media` AS `media` 
WHERE `media`.`image_title` LIKE ANY ('cat', 'hat');`
```
## What do you expect to happen?

I expected to get a list of Media where the image_title contains either 'cat' or 'hat'

## What is actually happening?

I get a console error in Chrome that reads:

"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('cat', 'hat')' at line 1"

And no images.

## Environment
Dialect:
- [x ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect ** mysql2** version: 1.6.5
Database version: 8.0.13
Sequelize version: 5.8.5
Node Version: 11.1.0
OS: Mac OSX 10.14.4
If TypeScript related: TypeScript version: N/A
Tested with latest release:
- [ ] No
- [x ] Yes, specify that version: 5.8.6

**Comment by papb** [comment]
Can you give a link for that page of the docs? Thanks!

**Comment by alignsoft** [comment]
https://sequelize.org/master/manual/querying.html

**Comment by papb** [comment]
After further investigation, it seems that `LIKE ANY` is supported in Postgres only, since the `ARRAY` datatype is itself PG only. What SQL query were you expecting instead? Are you sure this should work in MySQL?

> I expected to get a list of Media where the image_title contains either 'cat' or 'hat'

For this you can use `Op.or`, for example, I believe.

**Comment by MateoArgalle** [comment]
El Op.or ya que se necesita que traiga todos los datos que contengan los parametros recividos.
es como si tuviera que ejecutar está consulta 

SELECT [user]  FROM [pruebas] where [user] like '%Scott%' OR  [user] like '%lEIDY%' OR  [user] like '%ARGALLE%'

**Comment by adonaidiofanes** [comment]
I used regexp to simulate like to array and it work.

```
    Media.findAll({
        where: {
            image_title: {
                [Op.regexp]: ['cat', 'hat']
            }
        }
    })
```

**Comment by ephys** [comment]
Closing with resolution that `Op.any` is a postgres specific feature that cannot be used in MySQL.
