### ISSUE TITLE
Primary Key Field Check is Case-Sensitive in Model.create

### ISSUE THREAD

**Issue by dsbert** [sequelize/sequelize#10957]
## What are you doing?

Calling Model.create does not return the newly created row ID.

```js
	// model = { id, description }
    const instance = await this.Model.create({ description: 'test' });
	console.log(instance.get({plain: true}))
	// { id: undefined, description: 'test4' }
```

## What do you expect to happen?

I expected the following

```js
	// { id: 1, description: 'test4' }
```

## What is actually happening?

ID is undefined in the returned instance. I can see the ID field is populated correctly in the database (IDENTITY PRIMARY KEY)

Looking into this more, it seems the issue is that I do not explicitly define a primary key on my model. This means the default primary key is `id`. However, the database column has the primary key defined as uppercase `ID`. When performing an insert query (and maybe any type of query), this results in a mismatch between the column name and the model field. This check is done in `query.handleInsertQuery()`

Case-sensitivty in SQL Server column names is dictated by the collation setting and is off by default. For the purposes of these queries via sequelize, I would not expect the column case to matter.

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [X] mssql
- [ ] any
Dialect **library** version: 6.1.0
Database version: 2016
Sequelize version: 5.8.5
Node Version: 10.15.3
OS: Windows 10
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [ ] Yes, specify that version:

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Can you (or someone else) please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))? This will help tackling the issue faster.

**Comment by dsbert** [comment]
I no longer actively develop with sequelize and I haven't had time to come back around and create a self-contained example for this. I will leave it up to the maintainers if you want to close this issue. Thanks.
