### ISSUE TITLE
queryInterface.addColumn ignores transaction and takes the 'after' option in the wrong place

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [sequelize/sequelize#10950]
## What was unclear/insufficient/not covered in the documentation

The documentation suggests the `after` and `transaction` options are passed in the last options parameters, but in fact after must be specified in the attributes (second to last) and transactions are not working at all.

documentation and tests:
```js
// in the reference - http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addColumn
queryInterface.addColumn('tableA', 'columnC', Sequelize.STRING, {
   after: 'columnB' // after option is only supported by MySQL
});

// or in migrations.md - https://github.com/sequelize/sequelize/blob/e7c862833e9ed389a5411c281ab3b8bc80b7a17b/docs/migrations.md
return Promise.all([
    queryInterface.addColumn('Person', 'petName', {
        type: Sequelize.STRING
    }, { transaction: t }),
    queryInterface.addColumn('Person', 'favoriteColor', {
        type: Sequelize.STRING,
    }, { transaction: t })
])
```
But this is how it actually works for `after`:
```js
queryInterface.addColumn(
  'account',
  'type',
  {
    type: DataTypes.INTEGER,
    after: 'id',
  }
);
```
The worse problem are transactions that are not working, here is a simple reproduction migration file:
```js
const { DataTypes } = require('sequelize');

module.exports = {
  up: async queryInterface => {
    const { sequelize } = queryInterface;

    return sequelize.transaction(async transaction => {
      await queryInterface.addColumn(
        'account',
        'type',
        {
          type: DataTypes.INTEGER,
          after: 'id',
        },
        {
          transaction,
        }
      );

      throw new Error('err');
    }
  }
}
```
**The new column will be created every time, no matter if the transaction fails or not.**

---

Tested on **Sequelize: 5.7.6**

**Comment by devzsolt** [comment]
v4.42.0 has the same issue, at least regarding the `after` option. Thanks for the hint

**Comment by cschuff** [comment]
Still seeing this on `5.8.12` 
Both problems (wrong placement of after + transaction not considered) persist.

**Comment by cschuff** [comment]
This also is not only a documentation issue. It is a severe Bug (--> transaction not considered).

BR
Chris

**Comment by automatensalat** [comment]
For everyone running into the same issue: This seems to be a MySQL issue, not the fault of sequelize. 

According to the MySQL docs, DDL statements like ALTER COLUMN which are generated by sequelize.addColumn() calls are not subject to transactions and so are not rolled back regardless of whether the transaction fails or succeeds:
`Some statements cannot be rolled back. In general, these include data definition language (DDL) statements, such as those that create or drop databases, those that create, drop, or alter tables or stored routines.`
See: [https://dev.mysql.com/doc/refman/8.0/en/cannot-roll-back.html]()

**Comment by papb** [comment]
Hmmm, thanks for sharing this, it seems this needs more investigation then :)

Can anyone reproduce the posted problem in another dialect, such as SQLite for example?

**Comment by RocheVal** [comment]
So I confirm that the problem of rollback come from MySQL and only for DDL statement.

But considering the problem of the "after" attribute, it would be nice to update the doc or to put it in the good place.
A second issue link to this problem, is that in Typescript "after" is not present in any Types used by the addColumn function (nor in `ModelAttributeColumnOptions | AbstractDataTypeConstructor | AbstractDataType` for the "attribute" input and nor in the `QueryInterfaceOptions` for the "options" input).
So Typescript complains that this property doesn't exist and we have to use @ts-ignore to make it work, which is a bit ugly.

Just for information I'm currently using sequelize 5.21.5 and sequelize-typescript 1.1.0.

**Comment by RocheVal** [comment]
Just to add one more point on the MySQL rollback problem, MySQL 8.0 support Atomic DDL which can be rollback, here the docs [](https://dev.mysql.com/doc/refman/8.0/en/atomic-ddl.html#atomic-ddl-statement-behavior).
I'm not really familiar with this but it looks like it will just rollback the failing operation and not all the transaction, because an Atomic DDL is considered as a kind of transaction in itself.

So I don't know if it can be of any help but that's what I found on this.

**Comment by Zikoel** [comment]
Hi, the after typescript bug is still present in version `6.3.5`

**Comment by Vlad-KVR** [comment]
Issue with wrong types for "after" attribute is still present in "sequelize": "6.37.3"
