### ISSUE TITLE
Associations - Automatic methods not working

### ISSUE THREAD

**Issue by ashishsanjayrao** [sequelize/sequelize#10955]
I'm new to Node.js, Express and Sequelize (v5.8.6). In my project, I have defined a hasMany-belongsTo relationship. Location is the source model and User is the target model. After having defined the association, I am supposed to have access to the magic methods (getUsers(), setUsers(), etc.). But when I try to Location.getUsers(), I get the error:

`TypeError: Location.getUsers is not a function`

I've used <a href="https://github.com/sequelize/cli">Sequelize-CLI</a> to generate my models and migrations.
My files look like this:

<b>models/index.js</b>
```
'use strict';

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'production';
const config = require(__dirname + '/../config/config.js')[env];
const db = {};

var sequelize = new Sequelize(config.database, config.username, config.password, config);

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    const model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

<b>models/location.js</b>
```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const Location = sequelize.define('Location', {
    name: {
      allowNull: false,
      type: DataTypes.STRING
    },
  }, {
    sequelize,
    modelName: 'location',
    underscored: true,
  });

  Location.associate = function(models) {
    Location.hasMany(models.User);
  };

  return Location;
};
```

<b>models/user.js</b>
```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    email: {
      allowNull: false,
      type: DataTypes.STRING
    },
    location_id: {
      type: DataTypes.INTEGER
    },
  }, {
    sequelize,
    modelName: 'user',
    underscored: true
  });
  User.associate = function(models) {
    User.belongsTo(models.Location);
  };
  return User;
};
```

When I try doing `console.log(Location.associations)` from my location.js file, I just get `{}` but when I try to log it in my index.js file, I get `{Users: Users}` but I still can't access `Location.getUsers()`

Any help would be appreciated. Thanks in advance!

**Comment by ccemeraldeyes** [comment]
@ashishsanjayrao why did you close this? I'm having the same issue.

**Comment by papb** [comment]
Hmm, `Location.getUsers` seems wrong (assuming `Location` is the model) since the `getUsers()` method is not static, it is executed on a model instance. Were you also trying to call it statically, @ccemeraldeyes?

**Comment by ccemeraldeyes** [comment]
nah, in my case the method was just named wrong lol
You're probably right that that was @ashishsanjayrao 's issue though

**Comment by ThomasTopuz** [comment]
> nah, in my case the method was just named wrong lol You're probably right that that was @ashishsanjayrao 's issue though

Same here lol, I've copied and pasted the model to create a new one and didn't change the entity name on the define funciton.

**Comment by Pedro-99** [comment]
guys, I have the same issue, how did you solve that?

**Comment by Tzvetelin88** [comment]
Same issue here, even when doing exactly as documented: https://github.com/sequelize/sequelize/discussions/14625

**Comment by Pedro-99** [comment]
> guys, I have the same issue, how did you solve that?

in my case, I was adding "_" in the model's name and that causes to this error, just pay attention to your model's name

**Comment by saurabhverma2892** [comment]
I was having the same issue. 
to have a many to many association between users and clients(companies)
had to search a lot to finally find this:
**BelongsToManyGetAssociationsMixin**
**BelongsToManyAddAssociationMixin**

import { Model,  BelongsToManyGetAssociationsMixin, BelongsToManyAddAssociationMixin } from 'sequelize'

class User extends Model< InferAttributes<User>, InferCreationAttributes<User> > {
    declare id: CreationOptional<number>;
    declare name: string;
    declare email: string;
    declare password?: string;
    **public getClients!: BelongsToManyGetAssociationsMixin<Client>;**
    **public addClient!: BelongsToManyAddAssociationMixin<Client, number>;**
    public static associations: {
      clients: Association<User, Client>;
    };
}

Hope this helps!
