### ISSUE TITLE
Custom Data Types

### ISSUE THREAD

**Issue by KenLFG** [sequelize/sequelize#10964]
I was looking to create a custom data type for MySQL's TIMESTAMP (I know you can just do the 'TIMESTAMP' thing but there were data format issues I wanted to address (not necessarily with getters/setters but I may go that way now).

The docs have an example (though they go the postgre route) that is confusing me on a couple of points.
http://docs.sequelizejs.com/manual/data-types.html#extending-datatypes

First, the outer code (first code sample, where you're calling sequelizeAdditions) is attempting to pass Sequelize.DataTypes in. But in the sequelizeAdditions include's function, it treats that as "Sequelize" and attempts to assign DataTypes:

`DataTypes = Sequelize.DataTypes;`

So it's effectively assigning Sequelize.DataTypes.DataTypes? Or am I missing something? If I follow the example to the letter, I'll get:

`"TypeError: Cannot read property 'ABSTRACT' of undefined"`

Which is understandable if the example is wrong. Passing the Sequelize instance on its own gets past this but I'm wondering if I'm doing that wrong because maybe there's something I'm missing (incorrect or missing include/requires statement?).

Second, attempting to mimic the postgre-specific example for MySQL, I have the following:

```js
  DataTypes.TIMESTAMP.types.mysql = ['TIMESTAMP'];

  MySqlTypes = DataTypes.mysql;

  MySqlTypes.TIMESTAMP = function TIMESTAMP() {
    if (!(this instanceof MySqlTypes.TIMESTAMP)) return new MySqlTypes.TIMESTAMP();
    DataTypes.TIMESTAMP.apply(this, arguments);
  };
  util.inherits(MySqlTypes.TIMESTAMP, DataTypes.TIMESTAMP);

  MySqlTypes.TIMESTAMP.parse = Sequelize.BaseTypes.TIMESTAMP.parse;
```

However, if I get past the first issue I discussed above, I get:

`"ReferenceError: MySqlTypes is not defined",`

On the MySqlTypes assignment line (`MySqlTypes = DataTypes.mysql`). If I skip out on 'use strict', I'll end up on the parse assignment line with a BaseTypes is not defined for the line: 

`MySqlTypes.TIMESTAMP.parse = BaseTypes.TIMESTAMP.parse;`

I'm new to sequelize so I realize I could be making a bunch of mistakes here but I'm not new to coding and know documentation often can fall out of date or will make a lot of assumptions to avoid cluttering up examples.

Is there anything I should know about that I should be adding to the example that isn't shown which would help me get past these errors? I'm using Node 8.1, by the way, in case that has some bearing on it.

Thanks!

**Comment by papb** [comment]
Hello, the docs really need updating. Thanks for the issue.

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/11177
