### ISSUE TITLE
Sequelize does not properly use mysql sessions

### ISSUE THREAD

**Issue by misos1** [sequelize/sequelize#10975]
## What are you doing?

When I start transaction with `isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_UNCOMMITTED` :

1. It runs `SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;` after `START TRANSACTION;` so it does not affect the current ongoing transaction as is stated in mysql manual https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html#set-transaction-isolation-level

2. But it affects another transactions that runs on same (reused) connection from pool.

When I start new transaction it always appears in logs with new "session" identifier like `9101e35d-e571-491b-8fc3-c03c6fed1811`. But this is different from mysql session which is defined by sequelize connection and sequelize reuses connections in pool. So when I (or sequelize) change session isolation level for some transaction with sequelize session like `9101e35d-e571-491b-8fc3-c03c6fed1811` it can affect future transactions in different sequelize sessions like `494a41f6-4fe9-4710-9c52-ab016d4d6378` which unhappily used same connection from sequelize connection pool. Once is set session transaction isolation level it will be here permanently for particular sequelize connection not only for current sequelize "session" (or transaction) because sequelize uses connection pool and reuses connections for its "sessions".

```node.js
await sequelize.transaction(async function(transaction)
{
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): START TRANSACTION;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SELECT @@TX_ISOLATION;
	// REPEATABLE-READ
	await sequelize.query("SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;", { transaction });
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SELECT @@TX_ISOLATION;
	// READ-UNCOMMITTED
	await sequelize.transaction(async function(transaction)
	{
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): START TRANSACTION;
		console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SELECT @@TX_ISOLATION;
		// REPEATABLE-READ
		// good as we started new transaction before was first finished we forced sequelize to use new connection so we still have repeatable read
		await sequelize.query("SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;", { transaction });
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SELECT @@TX_ISOLATION;
		// READ-UNCOMMITTED
	});
	// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): COMMIT;
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): COMMIT;
});
await sequelize.transaction(async function(transaction)
{
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): START TRANSACTION;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): SELECT @@TX_ISOLATION;
	// READ-UNCOMMITTED
	// so why we have read uncommitted in new session 494a41f6-4fe9-4710-9c52-ab016d4d6378? probably was reused one of above connections
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): COMMIT;
});
```

Just to clarify this:

``` node.js
await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_UNCOMMITTED }, async function(transaction)...
```

Executes:

```
Executing (95ca9deb-53c4-4327-a6d9-fd07e41539fb): START TRANSACTION;
Executing (95ca9deb-53c4-4327-a6d9-fd07e41539fb): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
```

So I used `SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;` manually to see what is TX_ISOLATION in between.

**To Reproduce**

1. Create sequelize instance with mysql dialect.
2. Run sample code (in async function)
3. See output and logs

## What do you expect to happen?
Last TX_ISOLATION should be REPEATABLE-READ. Sequelize should start new mysql session for each transaction and change session isolation level before starting transaction. **Or change isolation level using `SET TRANSACTION ISOLATION LEVEL;` immediately before `START TRANSACTION` and then should not be needed to start new mysql session for each transaction**.

## What is actually happening?
Last TX_ISOLATION is READ-UNCOMMITTED. Cannot use isolation levels per transaction.

## Environment
Dialect:
- [x] mysql
- [x] mariadb
Dialect **library** version: any
Database version: any
Sequelize version: 5.8.6
Node Version: any
OS: any
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by ralexandr** [comment]
It seems i have same problem =/

**Comment by poldridge** [comment]
We are encountering this now too. Setting the isolation level for a transaction doesn't work at all in MySQL. Instead the isolation level is applied to the next transaction that happens to use the same connection.

The `SET TRANSACTION` statement needs to come before the transaction starts for MySQL. I can look into making a PR some time this week.
