### ISSUE TITLE
model associate foreignKey name don't be assigned.

### ISSUE THREAD

**Issue by JeffreyLinWeiYou** [sequelize/sequelize#10978]
## What are you doing?

```js
Models1.hasMany(Models2,  {
  foreignKey: 'gps_id',
  sourceKey: 'id',
});

Models2.belongsTo(Models1, {
  foreignKey: 'gps_id',
  targetKey: 'id',
});
```
**To Reproduce**
1. Define models1 and models2 association
2. different create : gpId
3. original column gps_id also create

## What do you expect to happen?
 foreignKey: 'gps_id'

## What is actually happening?
 foreignKey: 'gpId'

_Output, either JSON or SQL_

## Environment
Dialect:
postgres
Dialect **library** version: 
Database version: 10.7
Sequelize version: 4.42.0
Node Version: >=10
OS: Windows
Tested with latest release:

**Comment by santiagodoldan** [comment]
I spent some time yesterday trying to understand how `foreignKey`, `targetKey` and `sourceKey` work, looking at your snippet, I feel that you have to define them like this

_I guess that `gps_id` is part of Models1_

```
Models1.hasMany(Models2,  { foreignKey: 'id', sourceKey: 'gps_id' });
Models2.belongsTo(Models1, { foreignKey: 'gps_id', targetKey: 'id' });
```
