### ISSUE TITLE
When i add "underscored" attribute, creating 2 table.

### ISSUE THREAD

**Issue by yusufilkeroguz** [sequelize/sequelize#10971]
Hello;

I created a model "FooBars" and i added "--underscored". 

    sequelize model:generate --name "FooBars" --attributes "name:string" --underscored

Table created and name is **FooBars**. Everthing seems ok. now i am calling "FooBars" model in my router.js

```js

// Require all models
const db = require('./../models/index')

db.FooBars.sync({ force:process.env.DROP_TABLES })
```

Output:

    Executing (default): CREATE TABLE IF NOT EXISTS `foo_bars` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;

<img width="100%" alt="Screen Shot 2019-05-20 at 11 17 39" src="https://user-images.githubusercontent.com/3788174/58006561-06205500-7af1-11e9-8534-20355888610a.png">

MySQL version: 5.6
Sequelize version: ^5.8.6
Node Version: 8.15.0
OS: 10.14.3

**Comment by yusufilkeroguz** [comment]
Excuse me;

i am adding models/index.js and models/fooBars.js

**FooBars**

```js

'use strict';
module.exports = (sequelize, DataTypes) => {
  const FooBars = sequelize.define('FooBars', {
    name: DataTypes.STRING
  }, {
    underscored: true,
  });
  FooBars.associate = function(models) {
    // associations can be defined here
  };
  return FooBars;
};

```
**Index**

```js
'use strict';

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = require(__dirname + '/../config/config.js')[env];
const db = {};

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    const model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

**Comment by papb** [comment]
Closing in favor of #11225.

When #11225 gets closed, if anyone thinks this particular issue is still an issue, please ping me.

**Comment by waulkrie** [comment]
For anyone who is upgrading from v4 to v6 and is having this bug use the tableName attribute in the model

`  const FooBars = sequelize.define('FooBars', {
    name: DataTypes.STRING
  }, {
    underscored: true,
    tableName: 'FooBars',
  });`
