### ISSUE TITLE
Underscored lost its vital purpose in sequelize 5

### ISSUE THREAD

**Issue by misos1** [sequelize/sequelize#10977]
## What are you doing?
Seems new change is based entirely on this comment: https://github.com/sequelize/sequelize/issues/6423#issuecomment-379472035

Partially it looks as good change except that part about auto-generated attributes. One can make all own attributes underscored by simply naming them underscored so `underscored` option was good for having also timestamps and foreign keys underscored. Now it is not so hard to make timestamp underscored but one must specify names of all foreign keys manually.

## What do you expect to happen?
There should be option to generate underscored foreign keys and timestamps in model.

## What is actually happening?
Underscored does not work for model auto-generated attributes.

## Environment
Sequelize version: 5.8.6

**Comment by papb** [comment]
Closing in favor of #11225.

When #11225 gets closed, if anyone thinks this particular issue is still an issue, please ping me.
