### ISSUE TITLE
belongTo isn't enough for "include" queries from other table

### ISSUE THREAD

**Issue by demosglok** [sequelize/sequelize#10974]
## What are you doing?

Is it intended that sole "belongsTo" isn't enough to run queries on both sides

User.hasOne(Device)
Device.belongsTo(User)

i want to User.find({include:[Device]}) and Device.find({include: [User]})
but i need both relations (one per model) for that. I expected (according to docs) that single
hasOne or belongsTo is enough to run both queries, User.find and Device.find
**To Reproduce**
1. Define models User, Device
2. set belongsTo association: Device.belongsTo(User)
run query from User side: User.find({include:[Device]})
3. See error that User is not associated to Device

## What do you expect to happen?
Users with their devices

## What is actually happening?
User is not associated to Device

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ x] sqlite
- [ ] mssql
- [ ] any
Sequelize version: 5.7.3
Node Version: 10.x
OS: window10

**Comment by papb** [comment]
Hello :) Which part of the docs made you think that only one relation is enough? Sequelize can't infer the `hasOne` from the `belongsTo` because it could also be a `hasMany` for example.

**Comment by demosglok** [comment]
hi, nice to have question answered so quickly:)
actually as for docs, smth from this chapter
http://docs.sequelizejs.com/manual/associations.html#difference-between-hasone-and-belongsto

especially "or" between "hasOne" and "belongsTo"

**Comment by papb** [comment]
I will try to clarify the docs.
