### ISSUE TITLE
Completely confused on how to eager load through table data.

### ISSUE THREAD

**Issue by csalvato** [sequelize/sequelize#10989]
## What was unclear/insufficient/not covered in the documentation

Thank you so much for putting together a comprehensive SQL ORM!

I am desperately trying to figure out how to load data from my through table on eager load. Here's an example of a kids skill-class tracking program I'm working on:

```javascript
const parent = await models.User.findOne({
      where: { email: req.user.email },
      attributes: ['email', 'firstName', 'lastName', 'phone'],
      include: [
        {
          model: models.Student,
          include: [
            {
              model: models.Program,
              through: {
                model: models.StudentProgram
              }
            }
          ]
        }
      ]
    })
```

This works totally fine, and creates something that will respond to this:

`parent.Students[0].Programs[0].StudentProgram`

Wonderful. The documentation got me this far...

But my `StudentProgram` model has an association that I want to access:

```javascript
StudentProgram.SkillLevels = StudentProgram.belongsToMany(
      models.SkillLevel,
      {
        through: models.ProgramSkillLevel
      }
    )
```

I can get this data by running this code:

```javascript
programSkillLevels = await parent.Students[0].Programs[0].StudentProgram.getSkillLevels()
```

But that doesn't cut it, because I have something called `ProgramSkills` which is nested within a `ProgramSkillLevel`...

I am hoping that I can do something like this:

```javascript
const parent = await models.User.findOne({
      where: { email: req.user.email },
      attributes: ['email', 'firstName', 'lastName', 'phone'],
      // include: [{ all: true, nested: true }]
      include: [
        {
          model: models.Student,
          include: [
            {
              model: models.Program,
              through: {
                model: models.StudentProgram,
                include: [
                  {
                    model: models.SkillLevel,
                    through: {
                      model: models.StudentProgram
                    },
                    include: [
                      {
                        model: models.Skills,
                        through: { model: models.ProgramSkillLevel }
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }
      ]
    })
```

But this produces an error.

TBH I have had a lot of struggles with the documentation around `BelongsToMany` relationships and through tables. My app is pretty reliant on many through tables, which has made development incredibly slow, where I was hoping Sequelize would speed up dev :(

### If possible: Provide some suggestion how we can enhance the docs

In order for me to provide a concrete suggestion, I need to understand how to do this first, or if it's at all possible.  I have a feeling this is possible, because accessing the same data with a getter is working just fine...I just have no idea how to nest this data on load.

**Comment by papb** [comment]
Hello, I will try to improve the docs on this later. It is indeed possible! But I don't have much time to explain right now - it's not so simple (if I understood you correctly).

Please wait just a bit more! We are happy that you are thankful for Sequelize.
