### ISSUE TITLE
DATEONLY in MSSQL converted to localtime

### ISSUE THREAD

**Issue by tonyguinta** [sequelize/sequelize#10982]
## What are you doing?
Using DATEONLY, when querying the database directly the date is '2019-06-01', but Sequelize returns '2019-05-31'. I'm in the US Central timezone, so I assume it is still treating it as a UTC date and converting it to my timezone.

It is only returning the string in 'YYYY-MM-DD' format, which is good, but it is converting it based on my local time, which is bad.

Sequelize:  5.8.5
Tedious: 6.1.1
MS SQL Server 2017

## What do you expect to happen?
Return the date string as stored without converting based on local timezone.

## What is actually happening?
The date string is converted to local time, which displays as the previous day. '2019-06-01' is stored in the database, but '2019-05-31' is returned by Sequelize.

I rolled back to Sequelize 4.41.2 and Tedious 3.0.1 and the same date is returned as '2019-06-01T05:00:00.000Z'. So, it seems that DATEONLY has since been fixed to only return a date string without time and timezone, but it now assumes that the stored date is in UTC and incorrectly converts it to local time.

## Summary:
SQL Server DATEONLY Field Value: '2019-06-01'
Sequelize 5.8.5 returns: '2019-05-31'
Sequelize 4.41.2 returns: '2019-06-01T05:00:00.000Z'
My timezone: US Central Time (currently -5:00 with Daylight Saving Time)

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [x] mssql
- [ ] any
Dialect **library** version: Tedious 6.1.1
Database version: MS SQL Server 2017
Sequelize version: 5.8.5
Node Version: 8.11.0
OS: Windows 10
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.8.6

**Comment by c1oud45** [comment]
Hi, did you find any workaround for this issue?

**Comment by tonyguinta** [comment]
Hi, sorry for the delay in responding. 

My workaround was to roll back to Sequelize 4.41.2 and Tedious 3.0.1, which still returns a full datetime string for DATEONLY data types, but at least it returns it in the correct timezone.

**Comment by dead** [comment]
https://github.com/sequelize/sequelize/blob/555dbe1f0110ec423190ce31dcd912f936f63368/lib/dialects/mssql/data-types.js#L130

Changing to:
```js
return moment.utc(value).format('YYYY-MM-DD');
```

Fix this issue to me.

**Comment by papb** [comment]
@dead Hmm... While you're at it, can you test two other things as well?

**Test 1** - Removing the [extended DATEONLY class](https://github.com/sequelize/sequelize/blob/555dbe1f0110ec423190ce31dcd912f936f63368/lib/dialects/mssql/data-types.js#L128) entirely (also removing [here](https://github.com/sequelize/sequelize/blob/555dbe1f0110ec423190ce31dcd912f936f63368/lib/dialects/mssql/data-types.js#L206))

**Test 2** - Changing parse to an string-casting function:

```js
static parse(value) {
  return '' + value;
}
```

Thanks!

**Comment by dead** [comment]
@papb 
**Test 1** - It worked.
**Test 2** - Didn't work, the parsed date was in invalid format.

**Comment by papb** [comment]
@dead Nice! Can you submit a PR with my first suggestion?

**Comment by nmeeda** [comment]
I hope is it still Open?

**Comment by tonyguinta** [comment]
This is still a problem with Sequelize 6.3.5 and Tedious 9.2.1 on Node 11.3. 

Server Timezone:                                                                                  'UTC -5:00'
Date stored in SQL Server:                                                                    '2020-10-01'
Value returned from Sequelize 6.3.5   and Tedious 9.2.1 via Postman: '2020-09-30'
Value returned from Sequelize 4.41.2 and Tedious 3.0.1 via Postman: '2020-10-01T05:00:00.000Z'

If I change my timezone to UTC and start up Node, then Sequelize 6.3.5 and Tedious 9.2.1 return '2020-10-01'. It's pretty clear that the stored date is treated as UTC and is converting it to the Node server's timezone.

**Comment by tonyguinta** [comment]
[Pull request 11409](https://github.com/sequelize/sequelize/pull/11409) does indeed fix this issue, but it has yet to be included in a Sequelize release. 

As a workaround, I've made the change directly to my installation in node_modules and used [patch-package](https://github.com/ds300/patch-package/issues/85), which allows me to include the change in my source code and deploy it to my higher environments.

**Comment by azterix** [comment]
If you're looking for a workaround and don't want to get in to patching the package while we await that PR making it to release, I discovered this workaround that works for me using the moment-timezone package: 

`import moment from 'moment-timezone';
moment.tz.setDefault('UTC');`

Thanks to @dengue8830 for the workaround over on #11597

**Comment by spearmootz** [comment]
instead of changing the dependency you can just do this

class DATEONLY extends BaseTypes.DATEONLY {
    static parse(value) {
      return moment.utc(value).format('YYYY-MM-DD');
    }
  }


so add .utc(value)

**Comment by nandanv2702** [comment]
Hey, I recently came across this issue too - using Sequelize version 6.6.5 with the workaround suggested in [Pull Request 11409](https://github.com/sequelize/sequelize/pull/11409#issuecomment-726892029)
