### ISSUE TITLE
postgresql json numeric field order

### ISSUE THREAD

**Issue by acodercat** [sequelize/sequelize#10985]
## What are you doing?
postgresql json numeric field order

```sql
ORDER BY ("grid_day_air_quality_rank"."data" #>> '{aqi,rank}')::numeric ASC
```
**To Reproduce**
1. Define models X, Y, ...
2. Run the following
3. See error

## What do you expect to happen?
```sql
ORDER BY ("grid_day_air_quality_rank"."data" #>> '{aqi,rank}')::numeric ASC
```

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

## Environment
Dialect:
- [ ✓ ] postgres
Dialect **library** version: 10.0.*
Database version: XXX
Sequelize version: 5.8.6
Node Version: 10
OS: UBUNTU18.04
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [ ] Yes, specify that version:

**Comment by acodercat** [comment]
please

**Comment by papb** [comment]
Please explain in more detail what you want.
