### ISSUE TITLE
Migration transaction not rolled back on error

### ISSUE THREAD

**Issue by waynebloss** [sequelize/sequelize#10988]
## What are you doing?
```js
module.exports = {
  /**
   * @param {import("sequelize").QueryInterface} queryInterface
   * @param {import("sequelize").DataTypes} DataTypes
   */
  up: (queryInterface, DataTypes) => {
    return queryInterface.sequelize.transaction(async transaction => {
      // Categories
      await queryInterface.createTable(
        "categories",
        {
          id: {
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER,
          },
          name: { type: DataTypes.STRING },
          parent: { type: DataTypes.INTEGER },
          parent_order: { type: DataTypes.INTEGER },
          slug: { type: DataTypes.STRING },
        },
        { transaction },
      );
      await queryInterface.addIndex("categories", {
        unique: false,
        fields: ["parent"],
      });
      // Locations
      await queryInterface.createTable(
        "locations",
        {
          id: {
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER,
          },
          name: { type: DataTypes.STRING },
        },
        { transaction },
      );
    });
  },
  /**
   * @param {import("sequelize").QueryInterface} queryInterface
   * @param {import("sequelize").DataTypes} DataTypes
   */
  down: (queryInterface, DataTypes) => {
    return queryInterface.sequelize.transaction(async transaction => {
      await queryInterface.dropTable("categories", { transaction });
      await queryInterface.dropTable("locations", { transaction });
    });
  },
};
```
**To Reproduce**
1. Create a migration that will cause an error.
2. Run the migration.
3. See error and confirm that transaction was not rolled back.

## What do you expect to happen?
The transaction should have been rolled back. Tables created should have been dropped.

According to [the docs](http://docs.sequelizejs.com/manual/transactions.html) it should have been rolled back.

## What is actually happening?
Created tables were not dropped.

## Environment
Dialect:
- [X] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: 1.6.5
Database version: 8.0.16
Sequelize version: 4.43.0
Node Version: 11.15.0
OS: Arch Linux
If TypeScript related: TypeScript version: N/A
Tested with latest release:
- [X] No
- [ ] Yes, specify that version:

**Comment by SimonSchick** [comment]
I don't think most databases support migration transactions.

**Comment by waynebloss** [comment]
OK, thanks. The [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html) say that any statements that modify tables are an implicit commit (and therefore do not get rolled back).

[This answer on StackOverflow](https://stackoverflow.com/a/4736346/16387) shows that most datababases (well the ones on that list at least) do support transactional data-definition language. So, I guess that's why sequelize lets you pass the transaction option to the `createTable` method.
