### ISSUE TITLE
Sequelize automatically sets a default value for NOT NULL columns

### ISSUE THREAD

**Issue by Brammz** [sequelize/sequelize#10984]
I am currently running Sequelize.js code on my MySQL database, that is created using migrations. I have a table with persons that is defined like this:

```
return queryInterface.createTable('Persons', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        unique: true,
        type: Sequelize.INTEGER
      },
      email: {
        allowNull: false,
        unique: true,
        type: Sequelize.STRING
      },
      firstName: {
        type: Sequelize.STRING
      },
      lastName: {
        type: Sequelize.STRING
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
```

and the resulting table looks like this:

```
`Persons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `firstName` varchar(255) DEFAULT NULL,
  `lastName` varchar(255) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `email` (`email`)
)
```

When I add an entry to the database using Model.create({}) (with nothing between the brackets), the following object is added to the database:

```
id  email   firstName   lastName    createdAt   updatedAt
1   ''      NULL        NULL        2019-05-21 15:33:13 2019-05-21 15:33:13
Every NOT NULL column I have in my database gets a default value (empty string for varchar, false for boolean, NOW() for datetime).
```

The Sequelize.js docs state the following:

> setting allowNull to false will add NOT NULL to the column, which means an error will be thrown from the DB when the query is executed if the column is null. If you want to check that a value is not null before querying the DB, look at the validations section below.
> 
> title: { type: Sequelize.STRING, allowNull: false },

I never get this error. When trying to insert a new row with NULL as value for email in the database directly, I do get an error, but not with Sequelize.js

**Comment by papb** [comment]
Do you have `allowNull: false` also set in the model itself? Or you have it only in the migration?

**Comment by Brammz** [comment]
@papb No, they simple stated the datatype of the attribute. I remember trying this and getting declaration issues. However, I tried this again and now I do get the error. Thank you!

**Comment by papb** [comment]
> and now I do get the error

You mean "don't", right?

You're welcome :+1:

**Comment by Brammz** [comment]
Well, I don’t get the declaration error anymore indeed. But I do get an error when violating the null constraint, as it is supposed to go!

**Comment by Brammz** [comment]
Well, I don’t get the declaration error anymore indeed. But I do get an error when violating the null constraint, as it is supposed to go! (also misclicked..)

**Comment by papb** [comment]
Ah, I see! :+1:
