### ISSUE TITLE
Sequelize doesn't have protection for sql injection in queries raw

### ISSUE THREAD

**Issue by johnparra** [sequelize/sequelize#1099]
# [Usage raw queries](http://sequelizejs.com/documentation#usage-raw-queries)

When we're using the following code:

```
sequelize.query("select * from mytable where id=:id"
,null,{raw: true}
,{id: 'id_post'}).success(function(myTableRows) {
  console.log(myTableRows)
})

```

And we send parameters with sql injection.

```
1;insert into 1
```

No there protection and execute, following:

```
executing...
select * from mytable where id='1;insert into 1'
```

**Comment by wbpmrck** [comment]
what aboud in where clause?

```javascript
const subjects = await models.subject.findAll({
            where: {
                enable: 1,
                name:{
                    $like: `%${name}%`
                }
            }
        });
```

my logs:
```bash
DEBUG 14723: 指定路由不做检查
Executing (default): SELECT `id`, `name`, `desc`, `enable`, `create_time`, `update_time` FROM `subject` AS `subject` WHERE `subject`.`enable` = 1 AND `subject`.`name` LIKE '%;select * from subject%';
```

**Comment by jschatz1** [comment]
@mickhansen I think it is possible to inject SQL. I'm no expert but can you tell me where I'm wrong?
I'm using express. Normally I would use models, but I am working on something a little more dynamic. 

```javascript
module.exports.show = async function show(req, res) {
  const id = req.params.id;
  const model = req.params.model;
  try {
    const models = await models.sequelize.query(`SELECT * FROM "${model}" WHERE "id" = ${id}`, { type: QueryTypes.SELECT });
    return res.json({results: models})
  } catch (error) {
    console.trace(error);
    return res.status(422).json({ msg: "unable to find model", error });
  }
};
```

In my routes I have 
```javascript
routes.get("/:project/:model/:id", intakeController.show);
```

If I call: 
```
http://localhost:3000/api/v1/jschatz1/Cookies/1;%20DELETE%20FROM%20%22Cookies%22;
```

It does in fact return the first `Cookie` but then also deletes all cookies. I confirmed. 

I'm sure I must be doing something wrong... It doesn't seem to protect it from injecting SQL which does get run.

**Comment by jschatz1** [comment]
Nevermind. I found Replacements. https://sequelize.org/master/manual/raw-queries.html#replacements

**Comment by papb** [comment]
@jschatz1 Glad you figured it out. Indeed, your code was constructing a SQL query by joining string parts and user input; this indeed was very vulnerable to SQL injection, but that was not Sequelize's fault :)

I will see if I can add/rewrite part of our manuals to give some security hints.

**Comment by olliequ** [comment]
> I will see if I can add/rewrite part of our manuals to give some security hints.

@papb Out of curiosity, did you end up doing this? Would love to read further.

**Comment by ephys** [comment]
I don't think he did, but the rule is basically: never concatenate something in raw SQL (in both `literal()`, and `sequelize.query()`), unless you're 100% sure the value you're concatenating is safe.

```js
const id = '1; DROP TABLE users;';

// unsafe
sequelize.query(`SELECT * FROM users WHERE id = ${id}`);

// safe
sequelize.query(`SELECT * FROM users WHERE id = :id`, {
  replacements: { id },
});

// also safe
sequelize.query(`SELECT * FROM users WHERE id = $id`, {
  bind: { id },
});

// unsafe
User.findAll({
  where: {
    id: literal(`= ${id}`)
  },
});

// safe
User.findAll({
  where: {
    id: literal(`= :id`)
  },
  replacements: { id },
});

// also safe (and equivalent to above)
User.findAll({
  where: { id },
});

// also safe
User.findAll({
  where: {
    id: literal(`= $id`)
  },
  bind: { id },
});
```

With an extra exception if/when we add [the `sql` tag function](https://github.com/sequelize/sequelize/issues/14299), the following would also be safe:

```js
// id will be properly escaped by the `sql` tag.
sequelize.query(sql`SELECT * FROM users WHERE id = ${id}`);
```

**Comment by olliequ** [comment]
@ephys Oh wow, thanks so much for the examples!

Just to clarify, where above you wrote 
```javascript
const id = '1; DROP TABLE users;';

// safe (sequelize will escape the ID)
sequelize.query(`SELECT * FROM users WHERE id = :id`, {
  replacements: { id },
});```
When you say this query is 'safe', which of the following do you mean:
**1)** No bad SQL will be executed (`user` table won't be dropped), **_and_** the query executes as desired (e.g. user with id `1` is returned)
**2)** Or, no bad SQL will be executed, but the query does **not** return `user 1` as the query fails because ` '1; DROP TABLE users;'` isn't a valid ID in the `users` table.

Thanks :)

**Comment by ephys** [comment]
Option 2, it will result in 

```sql
SELECT * FROM users WHERE id = '1; DROP TABLE users;'
```

**Comment by papb** [comment]
Hi @olliequ, as @ephys said I did not... But what she said above is perfect :)
