### ISSUE TITLE
Missing Docs, 404 result

### ISSUE THREAD

**Issue by polarathene** [sequelize/sequelize#10999]
## What was unclear/insufficient/not covered in the documentation

The [dialects doc](http://docs.sequelizejs.com/manual/dialects.html) links to the old usage doc for `options`. I've since found out why it's 404, [this recent PR](https://github.com/sequelize/sequelize/pull/10899).

### If possible: Provide some suggestion how we can enhance the docs

I am not sure if it exists anymore in the official docs, at least it was not clear where. 

---

While at it, when I first came across the docs and went to `Getting Started` I was a bit confused as I thought maybe that was the top-level doc that I had landed on(index) originally but it wasn't, that requires you to click the logo or manually adjust the url. Minor UX thing.

As a new user, I also came across [these older docs](https://sequelize.readthedocs.io/) last updated in 2016. It's not immediately clear that they're out of date either, if that's something under this projects control, perhaps it should be pulled down or given some notice to the maintained docs.

**Comment by papb** [comment]
> The [dialects doc](http://docs.sequelizejs.com/manual/dialects.html) links to the old usage doc for `options`. I've since found out why it's 404, [this recent PR](https://github.com/sequelize/sequelize/pull/10899).

Thanks for reporting! I will fix it soon.

> While at it, when I first came across the docs and went to `Getting Started` I was a bit confused as I thought maybe that was the top-level doc that I had landed on(index) originally but it wasn't, that requires you to click the logo or manually adjust the url. Minor UX thing.

Thanks for the info. I questioned myself what would be the best way to do it. What are you suggesting though? That having an *Index* entry above *Getting Started* would be better?

> As a new user, I also came across [these older docs](https://sequelize.readthedocs.io/) last updated in 2016. It's not immediately clear that they're out of date either, if that's something under this projects control, perhaps it should be pulled down or given some notice to the maintained docs.

You're right, I will see what can be done about that.

**Comment by polarathene** [comment]
> What are you suggesting though? That having an Index entry above Getting Started would be better?

Based on context, perhaps a good title for it on the sidebar would be "About" / "About Sequelize"? Followed by some header for the section after *Quick example*, maybe.. "Jump to page" or something else descriptive of what purpose that section of page previews is serving.

**Comment by papb** [comment]
Fixed by #11193

**Comment by papb** [comment]
@polarathene Can you create a new issue with the *"while at it"* part?

**Comment by polarathene** [comment]
@papb done: https://github.com/sequelize/sequelize/issues/11220
