### ISSUE TITLE
UniqueConstraintError and TimeoutError has wrong parent

### ISSUE THREAD

**Issue by ojurkiewicz** [sequelize/sequelize#10995]
UniqueConstraintError has wrong parent in documentation. It says that this class extends DatabaseError when in reality it extends ValidationError.

Same is true for TimeoutError (DatabaseError should be BaseError).

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/class/lib/errors/validation/unique-constraint-error.js~UniqueConstraintError.html

Docs look OK to me
