### ISSUE TITLE
Get column attribute of multi-nested association from main Model

### ISSUE THREAD

**Issue by je-poy** [sequelize/sequelize#10996]
## What are you doing?
Im trying to get the column from a nested association from the main model:

wherein :
User hasOne User_Role
User_Role hasOne Role

```js
User.findAll({
            attributes: [
                [Sequelize.col('user_role.role_code'), 'role_code'],
                [Sequelize.literal('user_role.role.description'), 'role_desc'] //this gives error
            ],
            include: [{
                model: User_Role,
                attributes: [],
                include: [{
                    model: Role,
                    attributes: [],
                }]
            }],
            // raw: true
        })
```
## What do you expect to happen?
_I want to have this result_
```
[
    {
      "role_code": "MMGR1",
"role_desc":"Manager"
    },
]
```

## What is actually happening?
_But it gives error_

> Unhandled rejection SequelizeDatabaseError: missing FROM-clause entry for table "role"

## Environment
Dialect:
-  postgres
Database version: 11
Sequelize version: ^5.7.4
Node Version: v10.15.3
OS: Windows 10

**Comment by papb** [comment]
Can you please post:

* The SQL query generated by sequelize, ans
* Which query should it generate instead

**Comment by je-poy** [comment]
I solve it by trying this one
attributes: [fn('trim', col('table1->table2->table3.col_name')), 'col_alias']
