### ISSUE TITLE
Incorrect IndexHint.value typing

### ISSUE THREAD

**Issue by MusienkoSergey** [sequelize/sequelize#11008]
Hello everyone. I found issue in types file:

https://raw.githubusercontent.com/sequelize/sequelize/master/types/lib/model.d.ts
```
export interface IndexHint {
  type: IndexHints;
  value: string[];
}
```
**IndexHint** contains **value** key but query-generator use **values** key (with suffix s)

https://raw.githubusercontent.com/sequelize/sequelize/master/lib/dialects/abstract/query-generator.js

```
selectFromTableFragment(options, model, attributes, tables, mainTableAs) {
  let fragment = `SELECT ${attributes.join(', ')} FROM ${tables}`;
  
  if (mainTableAs) {
    fragment += ` AS ${mainTableAs}`;
  }
  
  if (options.indexHints && this._dialect.supports.indexHints) {
    for (const hint of options.indexHints) {
      if (IndexHints[hint.type]) {
        fragment += ` ${IndexHints[hint.type]} INDEX (${hint.values.map(indexName => this.quoteIdentifiers(indexName)).join(',')})`;
      }
    }
  }
  
  return fragment;
}
```
So the code (${hint.**values**.map... doesn't work if we use the current interface.

Expected IndexHint interface:

```
export interface IndexHint {
  type: IndexHints;
  values: string[];
}
```

## Environment
Dialect: mysql
mysql2 version: 1.6.5
Database version: 5.7
Sequelize version: 5.8.6
Node Version: 11.12.0
OS: macOS
TypeScript version: 3.1.6

**Comment by SimonSchick** [comment]
PR welcome.
