### ISSUE TITLE
why encrypt: false and never use dialectOptions passed by user

### ISSUE THREAD

**Issue by thuanpq** [sequelize/sequelize#11000]
## What are you doing?
Under  dialects/mssql/connection-manager.js line 42

`  connect(config) {
    const connectionConfig = {
      server: config.host,
      authentication: {
        type: 'default',
        options: {
          userName: config.username || undefined,
          password: config.password || undefined
        }
      },
      options: {
        port: parseInt(config.port, 10),
        database: config.database,
        encrypt: false
      }
    };`

why the encrypt options not load options passed by user but always false??

**Comment by admaduranga** [comment]
Still it ignores encrypt: false on version sequelize: 6.3.5
any thoughts?

**Comment by admaduranga** [comment]
found it, you have to use the options inside dialectOptions.

host: '192.168.31.247',
    dialect:'mssql',
    dialectOptions: {
            options: {
                encrypt: false
            }
        }

**Comment by rom5jp** [comment]
> found it, you have to use the options inside dialectOptions.
> Thank you @creffect
> `host: '192.168.31.247', dialect:'mssql', dialectOptions: { options: { encrypt: false } }`

You saved my life. Thank you so much!
