### ISSUE TITLE
Typed create

### ISSUE THREAD

**Issue by DanielRamosAcosta** [sequelize/sequelize#11001]
**Is your feature request related to a problem? Please describe.**
Right now, when calling `create` on a model, the `values` parameter is of [object type](https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L1895), hiding possible type problems passed to the `create`.

**Describe the solution you'd like**
It would be nice to have a generic type here, so we would be able to force some type.

**Why should this be in Sequelize**
Becouse types are now shipped here.

**Usage example**
It would be nice to have it at the class definition in some way, some generic type like `class MyModel extends Model<CreationAttrbutes>` or in the create method `MyModel.create<CreationAttributes>(values)`.

**Comment by papb** [comment]
You probably mean [this line](https://github.com/sequelize/sequelize/blob/6e0b13762bfdeac80b3acd580e75f68985c211bd/types/lib/model.d.ts#L1910), right?

This is a good idea. Hopefully someone will be able to take this soon.

**Comment by aryem** [comment]
#12405 Closes this issue.

@DanielRamosAcosta @papb

**Comment by DanielRamosAcosta** [comment]
Cosing then, @aryem
