### ISSUE TITLE
[Typescript] new Sequelize connect

### ISSUE THREAD

**Issue by mtryba** [sequelize/sequelize#11007]
## What are you doing?
I'm refactoring my code so also I would like to change the method of connecting with database. I use typescript and the latest version of sequelize. Now, my code looks like 

```js
export const sequelize = new Sequelize(name, userDb, password, options);
```
Unfortunately when I doing something like  this
```js
import Sequelize from 'sequelize
```
or
```js
import * as Sequelize from 'sequelize'
```

## What is actually happening?
I received info from typescript: 
`Cannot use 'new' with an expression whose type lacks a call or construct signature`

`const Sequelize = require('sequelize')` works correct but I would like to use typescript's import syntax

## Environment
Dialect:
- [x] postgres
Dialect **library** version: 7.8.0
Database version: 10
Sequelize version: latest (5.8.6)
Node Version: 10
OS: Mac Os
If TypeScript related: TypeScript version: 3.4.3
Tested with latest release:
- [ ] No
- [x] Yes, specify that version:

**Comment by eseliger** [comment]
it's possible using 

```ts
import { Sequelize } from 'sequelize'
```
