### ISSUE TITLE
Query inner join table without association for Posgresql

### ISSUE THREAD

**Issue by yunyeatra** [sequelize/sequelize#11006]
Hello everyone,

Please help me to get the result as below.

I have two table Staffs and Locations.
Table Locations:
![Capture1](https://user-images.githubusercontent.com/40712853/58395931-a982e400-8074-11e9-8082-a6cea1b20eff.PNG)
Level:  1 is City/Province, 2 is District, 3 is Commune
Parent is id field to store relation record:
Example: record { id:3,  name: "Pur SenChey", parent: 1, level: 2 } this is mean the records of district (level: 2) and this records is relate to {id: 1, name: "Phnom Penh ", parent:0, level: 1 } depend on (parent: 1)

Table Staffs:
![Capture2](https://user-images.githubusercontent.com/40712853/58395945-b99ac380-8074-11e9-83f2-35fe1d325f88.PNG)
How to get id, name, commune, district, province for staffs
The result will be like this:
![Capture3](https://user-images.githubusercontent.com/40712853/58395948-c0c1d180-8074-11e9-9a86-456c0eb27a36.PNG)

Best Regards
YUN Yeatra

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
