### ISSUE TITLE
ERROR: getaddrinfo ENOTFOUND postgres postgres:5432 on migrations in docker-compose

### ISSUE THREAD

**Issue by Rolilink** [sequelize/sequelize#11014]
## What are you doing?
I am running a microservice with sequelize and postgres it seems to properly connect to the database when running node app but on migrations it throws this error
```
Sequelize CLI [Node: 8.16.0, CLI: 5.4.0, ORM: 5.7.4]

Loaded configuration file "lib/sequelize/config.js".


ERROR: getaddrinfo ENOTFOUND postgres postgres:5432
```

```js
// code here
```

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: Don't Know
Database version: Don't Know
Sequelize version: 5.4.0 CLI
Node Version: 8.16.0
OS: docker
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by papb** [comment]
Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? Perhaps a gitlab repo where you can use docker-compose to show the problem?

**Comment by okabamac** [comment]
Please were you able to solve this? My connection is established but when I run migration it tells the address is not found

**Comment by gqsmoov** [comment]
> Please were you able to solve this? My connection is established but when I run migration it tells the address is not found

Same here

**Comment by WinjayYu** [comment]
> > Please were you able to solve this? My connection is established but when I run migration it tells the address is not found
> 
> Same here

Same...

**Comment by ngambino0192** [comment]
> Please were you able to solve this? My connection is established but when I run migration it tells the address is not found

Same issue here.

**Comment by sahilsharmafrank** [comment]
in your config.json use hopefully it will solve the problem
`"development": {
  ...
  "host": "host.docker.internal"
  ....
}`

**Comment by raulneitor** [comment]
> in your config.json use hopefully it will solve the problem
> `"development": { ... "host": "host.docker.internal" .... }`

it works for meee

**Comment by MadaShindeInai** [comment]
> in your config.json use hopefully it will solve the problem `"development": { ... "host": "host.docker.internal" .... }`
"development": { ... "host": "localhost" .... }. - solved my problem

**Comment by masioware** [comment]
> in your config.json use hopefully it will solve the problem `"development": { ... "host": "host.docker.internal" .... }`

that solves my problem.

https://github.com/masioware/nodejs-docker-template

**Comment by ephys** [comment]
I'm removing the bug label, this doesn't sound like a Sequelize issue but a general issue with node and docker's domain name resolver (it looks like the URL in the original post uses `postgres` as the domain name). Using localhost or 0.0.0.0 instead usually works

**Comment by PradoPHA** [comment]
> in your config.json use hopefully it will solve the problem `"development": { ... "host": "host.docker.internal" .... }`

IT WORKED! Thanks!!!
