### ISSUE TITLE
LEFT JOIN custom query based on association table

### ISSUE THREAD

**Issue by tsirolnik** [sequelize/sequelize#11025]
I want to include a left join of a count, based on the association table.

Assuming I've got the following many-to-many tables and associations - 

Tables: owner, chest, item, chest_item
Relationships:
owner -> chest (via ownerId on chest)
owner -> item (via ownerId on item)
chest_item -> item (via itemId on chest_item)
chest_item -> chest (via chestId on chest_item)

This is my current query, where I basically load all chests and their items based on the chest's distance and the items' category, or -
select all chests, their items and their owner, where the chest is nearby and the items' category id equals given category id . 

```js
  return await this.findAll({
      attributes: {
        include: [
          [
            Sequelize.fn(
              'ST_Distance',
              Sequelize.col('chest_location'),
              Sequelize.cast(Sequelize.fn('ST_MakePoint', lat, lng), 'geography')
            ),
            'distance'
          ]
        ]
      },
      where: [
        {},
        Sequelize.where(
          Sequelize.fn(
            'ST_DWithin',
            Sequelize.col('chest_location'),
            Sequelize.cast(Sequelize.fn('ST_MakePoint', lat, lng), 'geography'),
            myDistance
          ),
          true
        ),
        Sequelize.where(
          Sequelize.col(
            'item.id'
          ),
          { [Op.not]: null }
        ),
        Sequelize.where(
          Sequelize.col(
            'item.categoryId'
          ),
          { [Op.eq]: categoryId }
        )
      ],
      order: Sequelize.literal('distance ASC'),
      include: [
        {
          model: this.sequelize.models.item,
          through: {
            attributes: []
          },
        }, { model: this.sequelize.models.owner }
        ]
    });
```

This generates the following query - 

```SQL
SELECT
  "chest"."id",
  "chest"."ownerId",
  ST_Distance(
    "chest_location",
    CAST(ST_MakePoint(:lat, :lng) AS GEOGRAPHY)
  ) AS "distance",
  "items"."id" AS "items.id",
  "items"."categoryId" AS "items.categoryId",
  "items"."ownerId" AS "items.ownerId",
  "items->chest_item"."chest_item_location" AS "items.chest_item.chest_item_location",
  "items->chest_item"."chestId" AS "items.chest_item.chestId",
  "items->chest_item"."itemId" AS "items.chest_item.itemId",
  "owner"."id" AS "owner.id",
  "owner"."userId" AS "owner.userId"
FROM
  "chests" AS "chest"
  LEFT OUTER JOIN (
    "chest_items" AS "items->chest_item"
    INNER JOIN "items" AS "items" ON "items"."id" = "items->chest_item"."itemId"
  ) ON "chest"."id" = "items->chest_item"."chestId"
  LEFT OUTER JOIN "owneres" AS "owner" ON "chest"."ownerId" = "owner"."id"
WHERE
  (
    ST_DWithin(
      "chest_location",
      CAST(ST_MakePoint(:lat, :lng) AS GEOGRAPHY),
      10000
    ) = true
    AND "items"."id" IS NOT NULL
    AND "items"."categoryId" = :categoryId
  )
ORDER BY
  distance ASC;

```

Which results in the following output:
```
[
  chest : {
       ....
       items: [ ... ]
       owner: {...}
   }
]
```

Now, I want to include a count of the total items that a chest has (no matter the items' category) Something like this - 
```SQL
LEFT JOIN (SELECT COUNT(*) as totalitems, "chestId" FROM chest_items GROUP BY "chestId") t ON t."chestId" = "chest"."id"
```

I've tried to run the **raw** modified query (with my join) and it worked flawlessly.
It resulted in the following output (which I want):

```
[
  chest : {
      id: 1
       ....
       totalItems: <t.totalItems>
       items: [ ... ] 
       owner: {...}
   },
   chest : {
      id: 2
       ....
       totalItems: <t.totalItems>
       items: [ ... ]
       owner: {...}
   }
  ...
]
```

Now, my problem is that I can't find a way to do this **programmatically** with Sequelize.
 I've tried several methods and they've all failed me. It's a simple addition to the query, but I can't find a way to perform it. I would appreciate any help as I couldn't find a proper solution to this. At the moment I'm using a raw query.

To phrase it it simple words, I want to use Sequelize to execute the following query - 
select all chests, their items and their owner, where the chest is nearby and the items' category id equals given category id, also include the totalItems per each chest. 

I use PostgreSQL 9.6.8  with PostGIS

**Comment by papb** [comment]
Hello! Have you tried [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or [Slack](https://sequelize.slack.com)?

Please try those first, if they don't give you a result please post again later (and include links to your question).

I would help further if I had the time but I don't, sorry. Good luck, and we are glad that you're using Sequelize!
