### ISSUE TITLE
Sequelize.fn not escaping arguments

### ISSUE THREAD

**Issue by Nilos** [sequelize/sequelize#11028]
## What are you doing?
```js
const x = "'ff";
const y = 2;
await model.create({ point: sequelize.fn('ST_MakePoint', x, y) })
```
**To Reproduce**
1. Define a model with a point
2. Execute the example javascript
3. SQL Injection is visible

## What do you expect to happen?
x and y should be escaped!

## What is actually happening?
x and y are not escaped and can be used to trigger an sql injection

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Sequelize version: 4.44.0
Node Version: v8.10.0
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by contra** [comment]
Can you post more info about this + the output you're seeing? Sequelize is escaping this just fine for me.
