### ISSUE TITLE
silent is missing from UpdateOptions type 

### ISSUE THREAD

**Issue by koblas** [sequelize/sequelize#11022]
## What are you doing?

```js
      await MyModel.update(
        {
          updatedAt: overrides.updatedAt,
        },
        { where: { id: someId }, sideEffects: false, silent: true },
      );
```

**To Reproduce**
1. Compile under TypeScript
2. See error

Argument of type '{ where: { id: number; }; sideEffects: false; silent: boolean; }' is not assignable to parameter of type 'UpdateOptions'.

## What do you expect to happen?
Compile without warning

## What is actually happening?
Argument of type '{ where: { id: number; }; sideEffects: false; silent: boolean; }' is not assignable to parameter of type 'UpdateOptions'.

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [x] any
Dialect **library** version: 5.8.7
Database version: XXX
Sequelize version: 5.8.7
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: 3.4.5
Tested with latest release:
- [ ] No
- [X] Yes, specify that version: 5.8.7

## Fix 
```
  /**
   * If true, the updatedAt timestamp will not be updated.
   */
  silent?: boolean;
```

**Comment by papb** [comment]
Fixed by #11115
