### ISSUE TITLE
Missing Typings for QueryInterface

### ISSUE THREAD

**Issue by a88zach** [sequelize/sequelize#11027]
Many of the QueryInterface methods accept `string | { tableName: string, schema: string }` as the first argument.  For instance, the following is valid and will run successfully.

```
queryInterface.bulkDelete({ tableName: 'foo', schema: 'bar' } as any, {}, {});
```

However, the typings only support a `string` as the first argument.

**To Reproduce**
Create a migration with the above code using typescript

## What do you expect to happen?
The code should compile without error

## What is actually happening?
TSC will not compile without casting to any

## Environment
TypeScript version: XXX
Tested with latest release: 3.4.5
- [ ] No
- [X] Yes, specify that version:

**Comment by papb** [comment]
Would you be willing to submit a PR?

**Comment by ephys** [comment]
I believe this has since been fixed, as these methods now accept `TableName` which is equal to

```ts
export type TableName = string | TableNameWithSchema;
```
