### ISSUE TITLE
Transaction LOCK.UPDATE and associations

### ISSUE THREAD

**Issue by aaronovz1** [sequelize/sequelize#11023]
If you use LOCK.UPDATE on the top query are the associations also locked?

ie:

```
const query = {
  where: {
    id: user_id
  },
  include: [
    { model: Account }
  ],
  lock: t.LOCK.UPDATE,
  transaction: t
};

User.findOne(query)
```

Is User and associated Account row locked? If not, how can this be achieved with Sequelize?

**Comment by aaronovz1** [comment]
Anyone got some insight here?

**Comment by papb** [comment]
Hello! Can you test it and post your findings? Thanks!!

**Comment by aaronovz1** [comment]
I was hoping to reduce time on my side by asking the developers directly if this is supported. Looks like I will have to manually test this to confirm if no one knows. Is there not a unit test for this?

**Comment by papb** [comment]
Not that I know of, please test it and let us know, thanks!

**Comment by obo20** [comment]
From testing this out, it doesn't appear that Sequelize locks associations, or even has the ability to lock associations, which is fairly problematic for us.

It would be great if you could also lock joined rows in a transaction.
