### ISSUE TITLE
Why allowNull default value is true?

### ISSUE THREAD

**Issue by s97712** [sequelize/sequelize#11030]
In the document
> setting allowNull to false will add NOT NULL to the column, which means an error will be thrown from the DB when the query is executed if the column is null. If you want to check that a value is not null before querying the DB, look at the validations section below.
> title: { type: Sequelize.STRING, allowNull: false },

It's confusing the default value is `true`,  if the `allowNull` is not set, that mean `allowNull` is `undefiend`, why `undefined` as `true`?

**Comment by thesaintzion** [comment]
knk,nkml.

**Comment by ephys** [comment]
I'll keep this issue closed
I agree that boolean properties should be named based on what the default value is. Ideally undefined should be treated as false. So if attributes are nullable by default, a better name for the option could have been `nonNullable` or `disallowNull`

Unfortunately it's not worth it to make this breaking change, it would have a massive impact for little gain

We're tracking in https://github.com/sequelize/sequelize/issues/14260 whether fields should be non-nullable by default.

**Comment by skoniks** [comment]
> I'll keep this issue closed I agree that boolean properties should be named based on what the default value is. Ideally undefined should be treated as false. So if attributes are nullable by default, a better name for the option could have been `nonNullable` or `disallowNull`
> 
> Unfortunately it's not worth it to make this breaking change, it would have a massive impact for little gain
> 
> We're tracking in #14260 whether fields should be non-nullable by default.

Why not to add something in Sequelize contrstuctor options like
`defaultModelOptions: {
    allowNull: false
}`
