### ISSUE TITLE
defaultValue support async function

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#11033]
I hope defaultValue can support async function in model defintiton,for example:
```
sequelize.define('foo', {
 id: { type: Sequelize.TEXT, allowNull: false, defaultValue: async ()=>{ return await doSome();}}
});
```

**Comment by frlinw** [comment]
`defaultValue` is computed in model `constructor` and a `constructor` cannot be a promise.
It could be possible with the "old" `Model.build()` syntax, it's impossible with the `new Model()` syntax.

**Comment by ephys** [comment]
We discussed whether to accept this feature request at today's meeting.
The resolution was that this feature is incompatible with how Sequelize works. It would require making `Model.build()` async, which we don't think would be good design.

We recommend creating your own `build` async function to handle this use case
