### ISSUE TITLE
Bulk Update fail seemingly when getDataValue is involved

### ISSUE THREAD

**Issue by jusfeel** [sequelize/sequelize#11041]
## What are you doing?

```js
// tt.js
const Sequelize = require('sequelize');
const db = require('./dbconnection_sequelize');

const User = db.define('user', {
    id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.UUIDV4
    },
    status: {
        type: Sequelize.STRING,
        defaultValue: 'active'
    },
    roles: {
        type: Sequelize.STRING,
        allowNull: false,
        get() {
            return this.getDataValue('roles').split(',');
        },
        set(val) {
            this.setDataValue('roles', val.join(','));
        }
    }
});

User.sync().then(() => {
    User.create({
        roles: ['authenticated user']
    });
    User.create({
        roles: ['authenticated user']
    });
    User.create({
        roles: ['authenticated user']
    });
});


// tt1.js - same model, try bulk update
const Sequelize = require('sequelize');
const Op = Sequelize.Op;
const db = require('./dbconnection_sequelize');

const User = db.define('user', {
    id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.UUIDV4
    },
    status: {
        type: Sequelize.STRING,
        defaultValue: 'active'
    },
    roles: {
        type: Sequelize.STRING,
        allowNull: false,
        get() {
            return this.getDataValue('roles').split(',');
        },
        set(val) {
            this.setDataValue('roles', val.join(','));
        }
    }
});

User.update(
    { status: 'blocked' }, {
        where: {
            id: {
                [Op.ne]: null
            }
        }
    }
);

```

**To Reproduce**
1. Define model User and add some records by running:  node tt.js
2. Bulk update by running: node tt1.js
3. Error out: Unhandled rejection TypeError: Cannot read property 'split' of undefined

## What do you expect to happen?
Update user status as expected like when you update each record one by one

## What is actually happening?
 Unhandled rejection TypeError: Cannot read property 'split' of undefined

## Environment
Dialect:
- [ ] MariaDB
Dialect **library** version: XXX
Database version: 10.1.38
Sequelize version: 4.42.0
Node Version: 8.10.0
OS: Ubuntu 18.04
Tested with latest release:
- [ ] No

**Comment by papb** [comment]
Can you please test if this happens in another dialect as well, such as sqlite? You can instantiate an in-memory sqlite connection by using `new Sequelize('sqlite::memory:')`.

**Comment by Betree** [comment]
Same here, ad dedicated error message would be really helpful.

**Comment by Mhashh** [comment]
### checked on v6, still failing. 
**Reason :** 
 
1. Inside **update(value,option)**, **build = build(value)** is called to create an **model instance**. This **build** does not contain all the **dataValues**.
2. Undefined is encountered when **build.get()** is called which should return all **dataValues while invoking all virtual getters** (in this case **build.dataValues** will have **keys:[id, status, updatedAt]**).
3. Inside **getDataValue(key) dataValue['roles']_ return 'undefined'**.

**Error code inside get(key,vlaue) 3603-3616 no check for if options are undefined or dataValues has this key**
reaches this part when no key passed
```
if (this._hasCustomGetters) {
        for (_key in this._customGetters) {
          //options are undefined so continue is not called
          if (
            this._options.attributes
            && !this._options.attributes.includes(_key)
          ) {
            continue;
          }
         //option undefined should not reach here
          if (Object.prototype.hasOwnProperty.call(this._customGetters, _key)) {
            values[_key] = this.get(_key, options);
          }
        }
      }
```

then  _values[_key] = this.get(_key, options)_ call reaches this line causes error 3577, 

```
if (key) {
      if (Object.prototype.hasOwnProperty.call(this._customGetters, key) && !options.raw) {
        //calls getDataValue('roles')
        return this._customGetters[key].call(this, key, options);
      }
```

### v7(current main brach) does not have this issue as conditions are corrected

```
for (const attributeName2 of attributesWithGetters) {
         //options are undefined so continue is called
          if (!this._options.attributes?.includes(attributeName2)) {
            continue;
          }

          values[attributeName2] = this.get(attributeName2, options);
        }
```
