### ISSUE TITLE
Transaction rollback on destroy - does not roll back

### ISSUE THREAD

**Issue by redevill** [sequelize/sequelize#11057]
## Environment:
Angular 6 project with Sequelize 5.8.8 and Tedious 6.1.2 and SqlServer Express 2012

## What are you doing?

Deleting a record from the database and if there is an error in the transaction rollback the deletion.

However when looking in the database, the record is gone!!!

```js
  deleteTestWithErrorManagedTransaction(): Promise<boolean | Error>
  {
    return this._dbConnection.transaction((t: Transaction) =>
    {
      return this.models.tLookups_Notify_PropStatus.destroy({
        where:
          {
            pNotifyPropStatusID: 6
          }
      }, { transaction: t })
        .then(
          () => {
            throw new Error('Hello World');
          }, { transaction: t })
        .then((result: any) => { 'placeholder'; })
        .catch(
          (err: Error) => {
            console.log('catching an error');
            return Promise.reject(err.message);
          }
        );
    });
  }

module.exports = function(sequelize, DataTypes) {
  var tLookups_Notify_PropStatus = sequelize.define('tLookups_Notify_PropStatus', {
      pNotifyPropStatusID: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
      },
      NotifyPropStatus: {
        type: DataTypes.STRING(50),
        allowNull: false,
        unique: true
      },
      RecordInActive: {
        type: DataTypes.BOOLEAN,
        allowNull: false
      }
    },
    {
      timestamps: false,
      tableName: 'tLookups_Notify_PropStatus'
    });

  tLookups_Notify_PropStatus.associate = function () {
    var tAdmin_Notify_PropStatus = sequelize.models.tAdmin_Notify_PropStatus;

    tLookups_Notify_PropStatus.hasMany(tAdmin_Notify_PropStatus, { foreignKey: 'fNotifyPropStatusID' });
  };

  return tLookups_Notify_PropStatus;
};
```
**To Reproduce**
1. Define models as above, against table in database (msSql via tedious)
2. Add record to be deleted
2. Connect to database
3. Call the test function
4. Check the database to see if the record exists.

## What do you expect to happen?
The record should still exist after the rollback of the attempted delete.

## What is actually happening?
The test record is gone

_Output, from the console...

From the console it appears to be working:
Executing (e240c1503e0f5158a753): BEGIN TRANSACTION;
Executing (default): DELETE FROM [tLookups_Notify_PropStatus] WHERE [pNotifyPropStatusID] = 6; SELECT @@ROWCOUNT AS AFFECTEDROWS;
catching an error
Executing (e240c1503e0f5158a753): ROLLBACK TRANSACTION;

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ x] mssql
- [ ] any
Dialect **library** tedios: 6.1.2
Database version: 
Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64) 
	Jun 17 2016 19:14:09 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

Sequelize version: 5.8.8
Node Version: 10.14.0
OS: Client running on Mac High Sierra 10.13.6 
If TypeScript related: TypeScript version: 3.5.1
Tested with latest release:
- [x ] Yes, specify that version: as above

**Comment by redevill** [comment]
Repeated this test with the Unmanaged version of code, with the same result.

  runTransactionRollbackOnErrorUnmanagedCode(): Promise<boolean | Error>
  {
    return this._dbConnection.transaction().then((t: Transaction) =>
    {
      return this.models.tLookups_Notify_PropStatus.destroy({
        where:
          {
            pNotifyPropStatusID: 7
          }
      }, { transaction: t })
        .then(
          () => {
            throw new Error('Hello World');
          }, { transaction: t })
        .then((result: any) => { t.commit(); })
        .catch(
          (err: Error) => {
            console.log('catching an error');
            return t.rollback();
          }
        );
    });
  }

**Comment by eseliger** [comment]
the transaction needs to be part of the first object 

`{ where: {}, transaction: t }`

**Comment by redevill** [comment]
Thank you for the reply - Perhaps the docs need some adjustment?
http://docs.sequelizejs.com/manual/transactions.html#managed-transaction--auto-callback-

Excerpt - somewhat misleading, the docs showing 2 anonymous objects being passed.
```js
return sequelize.transaction(t => {

  // chain all your queries here. make sure you return them.
  return User.create({
    firstName: 'Abraham',
    lastName: 'Lincoln'
  }, {transaction: t}).then(user => {
    return user.setShooter({
      firstName: 'John',
      lastName: 'Boothe'
    }, {transaction: t});
  });

}).then(result => {
  // Transaction has been committed
  // result is whatever the result of the promise chain returned to the transaction callback
}).catch(err => {
  // Transaction has been rolled back
  // err is whatever rejected the promise chain returned to the transaction callback
});
```

**Comment by Kripesh4569** [comment]
transaction (and where) are params of the options object. 
create expects two objects as args : values and options (and thus the second arg = options has the transaction) 
delete expects only one arg: options (and thus transaction is part of the first arg = options)
