### ISSUE TITLE
Doesn't create foreign key when defining association

### ISSUE THREAD

**Issue by ratulSharker** [sequelize/sequelize#11052]
Referencing from an old #2031 , `hasOne` association does not creating the **foreign key**, as it intend to do according to [hasOne Documentation](http://docs.sequelizejs.com/class/lib/associations/has-one.js~HasOne.html) .

## What are you doing?
I was creating an `UserModel` and `UserStatus` model. Status like `waiting for approval`, `approved`, `rejected` etc. Association i meant to create like, Every user should have a status. So i put code like this

```js
// UserModel is created using `sequelize.define`
// UserType is created using `sequelize.define`
UserModel.hasOne(UserType, { foreignKey: { allowNull : false }, onDelete: "CASCADE" })
```
**To Reproduce**
1. Define models UserModel, UserType.
2. Run the following
3. See error

## What do you expect to happen?
i expect to create a foreign key `userTypeId` to be created inside the `users` table.

## What is actually happening?
No foreign key association was created in the `user` table

```sql
CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `firstName` VARCHAR(30) NOT NULL, `lastName` VARCHAR(30) NOT NULL, `email` VARCHAR(30) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL);
```
## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [x] sqlite
- [ ] mssql
- [ ] any

Dialect **library** version: 4.0.8
Database version: sqlite3
Sequelize version: 5.8.8
Node Version: 8.10.0
OS: Ubuntu 18.04

Tested with latest release:
- [ ] No
- [x] Yes, specify that version:

**Comment by hugo1707** [comment]
same problem

**Comment by papb** [comment]
Does creating the opposite association as well, i.e., `UserType.belongsTo(UserModel)` solves your problem?

**Comment by ratulSharker** [comment]
Yes it does @papb

**Comment by MemoryDewey** [comment]
I received the same problem as you. Have you solved it？

**Comment by ratulSharker** [comment]
I didn't solved it, but used a workaround, Given my `User` & `UserType` analogy, I was intend to use `hasOne` association, instead of that, i used `belongsTo`. Note that `belongsTo` & `belongsToMany` works just fine as the documentation says.

**Comment by mjsa-git** [comment]
Facing the same issue

**Comment by papb** [comment]
@mjsa-git did the workaround above work for you?

**Comment by axolo** [comment]
```js
App.belongsTo(User, { foreignKey: { allowNull: false }, onDelete: 'cascade', hooks: true });
User.hasMany(App);
```

`app.userId` foreign key references `user.id` **NOT** created in mysql 8.0.17 engine InnoDB

**Comment by Qarun-Qadir-Bissoondial** [comment]
Can confirm, I'm having this same problem using PostgreSQL

**Comment by elnur0000** [comment]
any solutions to this issue?
I am having the same problem 
will probably add the reference manually but documentation should be more clear about this

**Comment by ephys** [comment]
Since #14280, HasOne automatically creates a BelongsTo association too & BelongsTo is the only one responsible for creating a foreign key. I can't reproduce this issue anymore in v7. I think it's fixed
