### ISSUE TITLE
Adding multiple new enum values may cause model sync errors (ensureEnums, postgres)

### ISSUE THREAD

**Issue by Equals182** [sequelize/sequelize#11053]
## What are you doing?
I'm trying to add several new enum values to already existing type in postgres

**To Reproduce**

1. Have any model with enum column like this:

```
{
  ...
  myEnumColumn: {
    type: Sequelize.ENUM([
      'type1',
      'type2'
    ])
  }
  ...
}
```

2. Sync this model and then apply changes:
```
{
  ...
  myEnumColumn: {
    type: Sequelize.ENUM([
      'type-1', // new
      'type0', // new
      'type1',
      'type2',
      'type3', // new
      'type4', // new
      'type5' // new
    ])
  }
  ...
}
```
3. Sync again and this should fail with errors like:
`[SequelizeDatabaseError]: "type0" is not an existing enum label`
or
`[SequelizeDatabaseError]: "type4" is not an existing enum label`

## What do you expect to happen?
I wanted values to be added to enum type based on already existing types

## What is actually happening?
It looks like ensureEnum function uses not-added-yet types as reference for BEFORE or AFTER, making queries like these:

```
ALTER TYPE "public"."enum_db_myenumcolumn" ADD VALUE IF NOT EXISTS 'type-1' BEFORE 'type0'
```
or
```
ALTER TYPE "public"."enum_db_myenumcolumn" ADD VALUE IF NOT EXISTS 'type3' BEFORE 'type4'
```

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Database version: 11.3
Sequelize version: 5.8.8
Node Version: 12

**Comment by Equals182** [comment]
I digged it a bit and it looks like in [lib/dialects/postgres/query-interface.js#L84](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-interface.js#L84) there is a check for next value in array of all enum values (including new ones). 

For example, this check will pass for 'type-1' since there is 'type0' in new array of enum values. But there's no 'type0' enum value in postgres yet.

Maybe checking for next value before checking for previous one is not that good idea. Checking for previous value first should resolve issues with appending new values to enum, but it will probably not help with prepending values. I believe proper solution must include checking for already existing enum values to use them as reference for new values in AFTER/BEFORE part of query.

But even then, there is a [`Promise.all` in the end of file](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-interface.js#L99), that does not guarantee execution order. So when we use `AFTER new_enum_value` or `BEFORE new_enum_value` these new values may not yet exist in postgres. This will result in same error as before and require couple of tries to sync model, before it succeeds.

**Comment by papb** [comment]
Thanks for reporting and digging!

Perhaps you would be willing to dig more and submit a PR? :grimacing:

**Comment by Equals182** [comment]
I tried my best to fix this issue. Sorry my PR is very raw, I wasn't able to setup proper testing environment and didn't write any new tests for this particular problem. I sure hope someone could help me with this stuff. 

It seems like Travis and AppVeyor are stuck at MSSQL and SQLite tests, which is not related to my fix, I believe.
