### ISSUE TITLE
Issue with datetime format for sqlite3 

### ISSUE THREAD

**Issue by mchusovlianov** [sequelize/sequelize#11061]
It looks like there uses a wrong format for datetime for sqlite3 dialect:
```
Executing (default): INSERT INTO `case_attachments` (`case_attachment_id`,`case_id`,`filename`,`source`,`hash`,`attached_date`) VALUES (NULL,5,'90003177A (1).pdf','Added Manually','88298cfb58488448ee9ac4629f50e8719d5137caaa60c71d226c5911cab9a27d','2019-06-13 11:49:31.237 +00:00');
```

I suppose there is the extra space before timezone (+00:00). Is there a way how to specify own format for storing datetime?

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [X] sqlite
- [ ] mssql
- [ ] any

**Comment by paulodiovani** [comment]
> I suppose there is the extra space before timezone (+00:00).

I don't think so. This is a valid format.

> Is there a way how to specify own format for storing datetime?

The stored value should be consistent and always the same. You can, however, convert to a desired after reading, or just use a string column.

**Comment by mchusovlianov** [comment]
@paulodiovani I have an issue when I tried to read this data with golang. It doesn't expect the space before timezone and can't parse the time. I don't want to use string column to store datetime data as it will require some duplicated extra code for storing and formatting datetime.

**Comment by paulodiovani** [comment]
@mchusovlianov so the problem is more likely with the sqlite lib you're using with go lang, not with sequelize nor with sqlite.

Consider converting the values when reading/saving yourself.

According to sqlite maual,

> Applications can chose to store dates and times in any of these formats and freely convert between formats using the built-in date and time functions.

Here is an example of using `datetime()` function to read.

```sql
sqlite> .schema foo
CREATE TABLE foo (id integer, now datetime);
sqlite> SELECT id, now FROM foo;
1|2019-06-13 11:49:31.237 +00:00
2|2019-06-28 17:40:59 -03:00
sqlite> SELECT id, datetime(now) FROM foo;
1|2019-06-13 11:49:31
2|2019-06-28 20:40:59
```
