### ISSUE TITLE
[sqlite] QueryInterface.addConstraint fails on 2nd use.

### ISSUE THREAD

**Issue by knoid** [sequelize/sequelize#11066]
## What are you doing?

Using sqlite, I'm trying to add two constraints to the same table. After a lot of digging I found out that in order to add a constraint to a table in sqlite, sequelize creates a new table called %s_backup and then renames it back with ``ALTER TABLE `%s_backup` RENAME TO `%s`;``. When adding the 2nd constraint, sequelize checks the create table statement from sqlite itself by doing `SELECT sql FROM sqlite_master WHERE tbl_name='%s';` that returns the statement almost as you would expect it, with the distinction that the table name is quoted with double quotes. This makes the 2nd constraint fail because of this replace: https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query-generator.js#L428 .

**To Reproduce**
```
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table `users` (id integer primary key);
sqlite> select sql from sqlite_master where tbl_name='users';
CREATE TABLE `users` (id integer primary key)
sqlite> alter table `users` rename to `users1`;
sqlite> select sql from sqlite_master where tbl_name='users1';
CREATE TABLE "users1" (id integer primary key)
```

## What do you expect to happen?
I want to have two constraints in the table.

## What is actually happening?
It's throwing an error saying that the table already exists.

_Output, either JSON or SQL_

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [x] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: 4.0.9
Database version: 3.24.0
Sequelize version: 5.8.9
Node Version: 10.16.0
OS: mac
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.8.9

**Comment by knoid** [comment]
Did this branch to show a failing test about this issue: https://github.com/sequelize/sequelize/compare/master...knoid:test/addConstraint?expand=1

**Comment by sushantdhiman** [comment]
Fixed with https://github.com/sequelize/sequelize/pull/11067
