### ISSUE TITLE
Support Tarantool

### ISSUE THREAD

**Issue by wormen** [sequelize/sequelize#11060]
Is it planned to add support for TarantoolDB?
https://www.tarantool.io/en/doc/2.1/book/sql/

**Comment by sushantdhiman** [comment]
No

**Comment by wormen** [comment]
Tell me, for what reason you do not want to add support for this database?

how can I add support for this database myself, in the form of a plug-in / module for ORM?

**Comment by papb** [comment]
Hello, as maintainers we do not want to do this because we consider it low priority in comparison to other things that we have to do asap.

**Comment by wormen** [comment]
@papb can you answer the second question?

**Comment by papb** [comment]
For your other question, please look at #11975 (I have just created it, inspired by your question). Thanks!

**Comment by wormen** [comment]
it would be nice to see how to do this in the documentation

... waiting for documentation updates

**Comment by papb** [comment]
@wormen Thanks for the patience, I wish days had 48 hours so I could give more of my personal time to Sequelize :)
