### ISSUE TITLE
typescript definition: function inside operator inside where

### ISSUE THREAD

**Issue by fareshan** [sequelize/sequelize#11079]
This does not work:
```ts
import { col, fn, Op, where } from "sequelize/types";

const whereName = where(
      fn("unaccent", col("name")),
      { [Op.iLike]: fn("unaccent", "john") },
);
```

The typescript error:
```bash
Argument of type '{ [Op.iLike]: Fn; }' is not assignable to parameter of type 'LogicType'.
  Type '{ [Op.iLike]: Fn; }' is not assignable to type 'WhereOperators'.
    Types of property '[Op.iLike]' are incompatible.
      Type 'Fn' is not assignable to type 'string | Literal | AnyOperator | AllOperator | undefined'.
        Property '[Op.all]' is missing in type 'Fn' but required in type 'AllOperator'.ts(2345)
model.d.ts(137, 3): '[Op.all]' is declared here.
```

## Environment
**sequelize-typescript**: 1.0.0-beta.3
Dialect:
- [ ] mysql
- [ X ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: pg version 6.4.2
Database version: 9.6.12
Sequelize version: 5.8.10
Node Version: 8.11.4
OS: macOS 10.14.3
TypeScript version: 3.4.3 (or 3.3.3 same issue)
Tested with latest release:
- [ ] No
- [ X ] Yes, specify that version: 5.8.10

**Comment by DakotaLarson** [comment]
For those who reach this in the future, I was able to resolve the issue:
`attributes: [[fn("max", col("colC")), "theAlias"], "colA", "colB"]`. It's noted in the TS definition, but it's challenging to read. Use an array for this function argument and pass an alias as the second argument.
