### ISSUE TITLE
I can't extends dataTypes, how to do?

### ISSUE THREAD

**Issue by zhangbuding** [sequelize/sequelize#11072]
http://docs.sequelizejs.com/manual/data-types.html#extending-datatypes

hello, when I try to extends data type in my project, but this doc is not available.
First of all, it's should be `module`, not `modules`,
and then, `DataTypes.ENCRYPT.prototype.key = DataTypes.ENCRYPT.key = 'ENCRYPT';`
This line throw **XXX is undefined**
obviously, not assign on `DataTypes` before using.

even if solved these little problems, 
the results is still unexpected, the `_stringify` fn not effect, and the same with others fn.
em.. 
so I debug  time and time again..

![image](https://user-images.githubusercontent.com/28292755/59591021-d5e3ca80-911f-11e9-821c-a0858f406c95.png)

then,  `DataTypes.ABSTRACT` is a proxy, how to use class extends it?

I think i need some help, 
thanks！

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/11177
