### ISSUE TITLE
Why update statement print "?" insted of values?

### ISSUE THREAD

**Issue by xXLokerXx** [sequelize/sequelize#11084]
# This is more a question than issue

I'm pretty new with version 5, when i execute update this prints the query in cmd.
v5 prints:
`Executing (default): UPDATE `productos` SET `cantidad`=?,`updatedAt`=? WHERE `ARTICULO` = ?`
old versions prints:
`Executing (default): UPDATE `productos` SET `cantidad`=1,`updatedAt`='2019-06-19 15:03:15' WHERE `ARTICULO` = '0001'`

theres any way to configure this output to show values i sent to update query?

**Comment by zhangbuding** [comment]
Maybe in order to parameterized query. I use this method 👇
`  
 logging(str, ...args) {
    let instance = args.pop();
    console.log(str, instance.bind, '\n');
}
`

**Comment by xXLokerXx** [comment]
> Maybe in order to parameterized query. I use this method 👇
> ` logging(str, ...args) { let instance = args.pop(); console.log(str, instance.bind, '\n'); }`

i'm looking for this function and i cant find it, do you think theres a way to show params in the log?

**Comment by superlbr** [comment]
it happens randomly, insert also

**Comment by xXLokerXx** [comment]
Ok, then i'll log by myself, thanks for your answers @superlbr @zhangbuding
