### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by nthsense** [sequelize/sequelize#11087]
**Is your feature request related to a problem? Please describe.**
This is related to #10476 
**Describe the solution you'd like**
I'd like Sequelize to work in React Native

**Why should this be in Sequelize**
I don't think this can be a separate package, as this relates to internals.

**Describe alternatives you've considered**
I've considered using a different ORM.

**Usage example**

**Additional context**
Original bug was closed as not on the roadmap - I ran into this issue myself, and was disappointed. Adding this feature request because I thought it would be more appropriate than a simple "+1" on the original bug report.

**Comment by sushantdhiman** [comment]
As stated in original thread, React native support is currently out of scope

**Comment by nthsense** [comment]
Sure - but how does one get something on the roadmap that is currently "out of scope", if not by feature request?  Is there a different ticket type for a roadmap suggestion?
