### ISSUE TITLE
Can't do 50k insertion using bulkCreate

### ISSUE THREAD

**Issue by abdallahokasha** [sequelize/sequelize#11092]
Using **v4.38.0** with mysql dialect i can't do large scale insertion in database like 50k record, although it should be solved and merged on this PR #7391.

I've tried to use **v4.44.0** but no gain even when using `{raw: true}` 
ex: `Model.bulkCreate(MY_ARRAY_50k_SIZE, {raw:true})`

I noticed that it actually executed as separated insert sql queries !!!

Could you help me to find a proper way to insert such a big bulk of data in O(1) as only **one insert** statement or even O(N) ?

@sdepold @sushantdhiman @mickhansen

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
