### ISSUE TITLE
Running migrations against postgres on Heroku throws an error when pooling values are not set in config.json

### ISSUE THREAD

**Issue by rschooley** [sequelize/sequelize#1110]
This happens during the sync process of `Migrator.prototype.findOrCreateSequelizeMetaDAO`

I have traced the cause down to this line:
https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connector-manager.js#L130

If the pooling values are not set the code calls to the native driver (because SSL is required to hit the Heroku DB and that requires the native setting):
https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connector-manager.js#L13

The value of `client` in the callback here is null in this scenario
https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connector-manager.js#L89

However, the control statements in that function don't check for a null error and undefined client (which is what happens).

``` bash
$ sequelize -m
Loaded configuration file "config/config.json".
Using environment "development".

/Users/robert/.nvm/v0.10.22/lib/node_modules/sequelize/lib/dialects/postgres/query.js:26
      , query         = this.client.query(sql)
                                    ^
TypeError: Cannot call method 'query' of null
    at module.exports.Query.run (/Users/robert/.nvm/v0.10.22/lib/node_modules/sequelize/lib/dialects/postgres/query.js:26:37)
    at EventEmitter.<anonymous> (/Users/robert/.nvm/v0.10.22/lib/node_modules/sequelize/lib/dialects/postgres/connector-manager.js:62:22)
    at EventEmitter.emit (events.js:92:17)
    at connectCallback (/Users/robert/.nvm/v0.10.22/lib/node_modules/sequelize/lib/dialects/postgres/connector-manager.js:119:17)
    at Connection.connectCallback (/Users/robert/.nvm/v0.10.22/lib/node_modules/pg/lib/native/index.js:40:9)
    at Connection.g (events.js:175:14)
    at Connection.EventEmitter.emit (events.js:117:20)
```

in the config:

```
{
    ...
    "dialect": "postgres",
    "native": true
}
```

This is where I hop off as I have my fix (add the pooling settings).  Hopefully someone can find the actual issue with the connection.

**Comment by corbanb** [comment]
All this worked for me pushing to heroku from my local. Thought I would share.

```
"development": {
    "username": "xxxxxxxx",
    "password": "xxxxxxxxxxxxxxxx",
    "database": "xxxxxxxxxxxxxx",
    "host": "xxxxxxxxxx.compute.amazonaws.com",
    "port": 5432,
    "dialect": "postgres",
    "protocol": "postgres",
    "native": true
  }
```
