### ISSUE TITLE
this.setDataValue() does not type-check correctly inside an attribute setter

### ISSUE THREAD

**Issue by wbget** [sequelize/sequelize#11114]
I want use 'setDataValue', 'getDataValue' in typescript,so I write in this way.

```this.setDataValue('points', JSON.stringify(val)); // error```

but it's error, so I write like this.
```
const Model = app.model.define(
    'area',
    {
      areaId: {
        type: INTEGER,
        primaryKey: true,
        allowNull: false,
        autoIncrement: true,
      },
      name: { type: STRING(32), allowNull: false },
      points: {
        type: TEXT,
        set(val) {
          // this.setDataValue('points', JSON.stringify(val)); //error.
          Model.prototype.setDataValue.bind(this)(             //correct
            'points',
            JSON.stringify(val),
          );
        },
        get() {
          return JSON.parse(Model.prototype.getDataValue.bind(this)('points'));
        },
      },
    },
    {
      timestamps: false,
    },
  ) as IArea;

```

**Comment by rolandleth** [comment]
Was about to open the same issue; I suppose it's an OK solution in the meantime.

More info about the problem: `this` is inferred to have a type of `String | DataTypes.AbstractDataTypeConstructor | DataTypes.AbstractDataType | ModelAttributeColumnOptions` and none of those have a `setDataValue` method.

TS error:

```js
Property 'setDataValue' does not exist on type 'String | AbstractDataTypeConstructor | AbstractDataType | ModelAttributeColumnOptions'.
Property 'setDataValue' does not exist on type 'String'.ts(2339)
```

**Comment by papb** [comment]
@rolandleth What is the difference? What you said seems the same thing posted by OP, no?

By the way `Account.prototype.setDataValue("passwordHash", hash)` won't work because it loses the bind context, what would make sense is something like `Account.prototype.setDataValue.call(this, "passwordHash", hash)`.

**Comment by rolandleth** [comment]
Oh, I totally missed OP's `bind(this)` 😞 I thought it behaves differently because I'm using classes, which is why I also thought about a different issue. Thank you for the `call(this...` suggestion!

Have a great Saturday, @papb!

**Comment by papb** [comment]
@rolandleth Thanks! You too!

**Comment by wbget** [comment]
```
const Model = app.model.define(
    'area',
    {
      areaId: {
        type: INTEGER,
        primaryKey: true,
        allowNull: false,
        autoIncrement: true,
      },
      name: { type: STRING(32), comment: '名称', allowNull: false },
      points: {
        type: TEXT,
        set(this: InstanceType<IArea>, val) { // bind this type
          this.setDataValue('points', JSON.stringify(val));
        },
        get(this: InstanceType<IArea>) { // bind this type
          return JSON.parse(this.getDataValue('points'));
        },
      },
    },
    {
      comment: '区域表',
      timestamps: false,
    },
  ) as IArea;
```

**Comment by ephys** [comment]
This has since been fixed. The `this` parameter has been configured:

![image](https://user-images.githubusercontent.com/1280915/163682789-74e23ef6-2dd9-46ac-9d22-e9e3bbc4c799.png)
