### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by PedroGao** [sequelize/sequelize#11111]
## What are you doing?

```js
  try {
    await User.create({
      nickname: 'super',
      admin: UserAdmin.ADMIN,
      password: '123456'
    });
  } catch (error) {
    console.log(error);
  }
  db.close();
```
**To Reproduce**
1. Define a model User .
2. Call the static method `create`
3. But see an error

```js
TypeError: Cannot read property 'length' of undefined
    at User._initValues (/Users/pedro/projects/nodejs/cms/lin-cms-koa/node_modules/sequelize/lib/model.js:140:49)
    at new Model (/Users/pedro/projects/nodejs/cms/lin-cms-koa/node_modules/sequelize/lib/model.js:118:10)
    at new User (/Users/pedro/projects/nodejs/cms/lin-cms-koa/node_modules/lin-mizar/lin/core.js:181:1)
    at run (/Users/pedro/projects/nodejs/cms/lin-cms-koa/tests/helper/add_super.js:7:18)
    at Object.<anonymous> (/Users/pedro/projects/nodejs/cms/lin-cms-koa/tests/helper/add_super.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

## What do you expect to happen?
create an user successful!

## What is actually happening?
there was an error! and happened on this line:

```js
     // set id to null if not passed as value, a newly created dao has no id
      // removing this breaks bulkCreate
      // do after default values since it might have UUID as a default value
      if (this.constructor.primaryKeyAttributes.length) {
        this.constructor.primaryKeyAttributes.forEach(primaryKeyAttribute => {
          if (!Object.prototype.hasOwnProperty.call(defaults, primaryKeyAttribute)) {
            defaults[primaryKeyAttribute] = null;
          }
        });
      }
```

when creating an user, the constructor.primaryKeyAttributes is undefined，so why this caused.

_Output, either JSON or SQL_

no sql and no json, just crashed on the sequelize , the core file is `sequelize/lib/model.js`

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: 1.6.5
Database version: 5.7.24
Sequelize version: 5.3.5
Node Version: v10.15.3
OS: mac 10.14.5
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by PedroGao** [comment]
solved!

**Comment by nolan-m** [comment]
@PedroGao What was the solution?  Running in this myself.

**Comment by BobGneu** [comment]
@nolan-m 	
Check your connections and that your models are all registered.

**Comment by MahmoudAbdo90** [comment]
@PedroGao  @nolan-m  @BobGneu 
running into the same issue, on Model.create
anyone got it working ?

**Comment by nolan-m** [comment]
@MahmoudAbdo90 
I fixed mine by making sure the models where initialized before using them.

I had some unit tests that used Sequelize models, but I never loaded the file that initialized all them in the unit tests.

**Comment by MahmoudAbdo90** [comment]
I figured the problem out, It was a configuration problem. 
@nolan-m Thanks man

**Comment by Valves133** [comment]
I was having the same problem. Because I was importing my Model as an instance. I just imported the class alone normal and if it was the error

**Comment by Cardoso-CHM** [comment]
Solved here!

I just forgot to add my new model inside my "models" array inside sequelize class configuration file, in my project this file is located at:  src/database/index.js

**Comment by andersonlthome** [comment]
I did the same as @Cardoso-CHM

**Comment by kylecombes** [comment]
My solution was to use `MyModel.sync({ force: true })` to drop and recreate the table (only do that if you want to drop though!).

**Comment by kylecombes** [comment]
My solution was to use `MyModel.sync({ force: true })` to drop and recreate the table (only do that if you want to drop though!).

**Comment by cosmoarunn** [comment]
@PedroGao  Thanks!

I was running into this problem and very much troubled to find the solution
few things can be the primary reason, the seq authentication check, await the sync  and model initialization
here's the working sample: 
```
try {
      await sequelize.authenticate();  //do authentication
      await User.initialize(sequelize);  /**/initialize user model**
      console.log('Connection has been established successfully.');
    } catch (error) {
      console.error('Unable to connect to the database:', error);
      return response('Database connection error!')
    }
```

and the User Model, 
```
//define the class
class User extends Model {}
User.init({
  username: DataTypes.STRING,
  birthday: DataTypes.DATE
}, { sequelize, modelName: 'user' });
```
and create,
```
(async () => {
  await sequelize.sync();   // call the sync before creating
  const jane = await User.create({
    username: 'janedoe',
    birthday: new Date(1980, 6, 20)
  });
  console.log(jane.toJSON());
})();
```

**Comment by johnatan-etges** [comment]
> Solved here!
> 
> I just forgot to add my new model inside my "models" array inside sequelize class configuration file, in my project this file is located at: src/database/index.js

This was the solution to me! Many tanks!
