### ISSUE TITLE
removeHook and addHook

### ISSUE THREAD

**Issue by aminsol** [sequelize/sequelize#11126]
Please be explicit that methods like removeHook and addHook do not work on Instances. The documentation gives the impression that these methods also work on instances but they do not. If you use removeHook on an instance node will throw this error from **lodash**:

```
/home/xxxx/PhpstormProjects/some-project/node_modules/lodas/lodash.js:15709
              var result = object(this.__wrapped__),
                           ^

TypeError: Class constructor Model cannot be invoked without 'new'
    at self.object.(anonymous function) [as removeHook] (/home/xxxx/PhpstormProjects/some-project/node_modules/lodash/lodash.js:15709:28)
    at removeHook (/home/xxxx/PhpstormProjects/some-project/src/controllers/user.js:44:22)
    at callback (/home/xxxx/PhpstormProjects/some-project/src/util/loginStrategy.js:9:18)
```
At first I thought there is a problem with babel but then I found out that instances do not have such methods and I have to use Models to remove hooks from instances. Here is a question that I posted on [stackOverflow](https://stackoverflow.com/questions/56802060/sequelize-five-5-babel-seven-7-typeerror-class-constructor-model-cannot-be-in)

**Comment by 2kindsofcs** [comment]
I'd like to help this one. Do you mind if I make a PR regarding this issue?

**Comment by papb** [comment]
@2kindsofcs Sorry to take long to reply!! If you want to help that is great :grimacing: please do!! Thanks!!

**Comment by aminsol** [comment]
Thank you
