### ISSUE TITLE
Execute query with timezone -03:00

### ISSUE THREAD

**Issue by mateo2181** [sequelize/sequelize#11136]
## What are you doing?

I save data with timezone +00:00. I want to set time zone -03:00 before execute a query. I have tried with PgAdmin and it is working but I can't do it with sequelize.

```js
// PG ADMIN Query
SET TIME ZONE INTERVAL '-03:00';
SELECT SUM(total)
FROM ventas
where "empresaId"='3' and estado='cerrada' and "createdAt" between '2019-07-01T00:00:00' and '2019-07-01T23:59:59';

// Output 120 
```

## What do you expect to happen?
Excuted query with timezone -03:00
I have to get 120.

## What is actually happening?
When I tried to do this from sequelize my output is 260 because the timezone used is +00:00. 

## Environment
Dialect:
- [ ] mysql
- [*] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any

Database version: 10.4
Sequelize version: 4.37.7
Node Version: 8.9.1
OS: Ubuntu 18

**Comment by papb** [comment]
You can use a [raw query](https://sequelize.org/master/manual/raw-queries.html) to call `SET TIME ZONE INTERVAL '-03:00'` before doing the rest of your queries.
