### ISSUE TITLE
Setting deletedAt to false in model throws TypeError: Cannot read property 'hasOwnProperty' of undefined when table has no deletedAt column

### ISSUE THREAD

**Issue by heinosasshallik** [sequelize/sequelize#11138]
## What are you doing?

Postgresql:
```
create table test (
   id integer primary key,
   creation_time timestamptz,
   updatetime timestamptz
)
```
model.js:
```
module.exports = function (sequelize, DataTypes) {
  return sequelize.define('test', {
    creationTime: {
      type: DataTypes.DATE,
      field: 'creation_time',
      defaultValue: DataTypes.NOW,
    },
    updateTime: {
      type: DataTypes.DATE,
      field: 'update_time',
      defaultValue: DataTypes.NOW,
    },
    id: {
      type: DataTypes.BIGINT,
      field: 'id',
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
    },
  }, {
    tableName: 'test',
    timestamps: true,
    createdAt: "creation_time",
    updatedAt: "update_time",
    deletedAt: false,
  });
};
```
code:
```
test = sequelize.import(`${__dirname}/model.js`)
return test.findAll();
```

**To Reproduce**
1. Create table in database
2. Define and import the model
3. Run query on the model

## What do you expect to happen?
Expected no error. According to the documentation, sequelize should treat it as a table where there is no deleted_at column

## What is actually happening?
Getting error on any query with the model.
`TypeError: Cannot read property 'hasOwnProperty' of undefined`

## Environment
Dialect:
- [ ] mysql
- [X] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version:    ` "pg": "^7.11.0",` (from package.json)
Database version: `PostgreSQL 11.3 (Debian 11.3-1.pgdg90+1) on x86_64-pc-linux-gnu`
Sequelize version: `"sequelize": "^5.8.6",`
Node Version: v10.15.3
OS: Mac OS

**Comment by papb** [comment]
Can you please retry with the latest version?

**Comment by heinosasshallik** [comment]
Unfortunately I cannot, as I no longer have the computer or the project in which this error occurred, so my feedback is as good as any other

**Comment by ephys** [comment]
Ran a SSCCE with the following code, and could not replicate the issue in Sequelize 6:

```ts
const Test = sequelize.define('test', {
  creationTime: {
    type: DataTypes.DATE,
    field: 'creation_time',
    defaultValue: DataTypes.NOW,
  },
  updateTime: {
    type: DataTypes.DATE,
    field: 'update_time',
    defaultValue: DataTypes.NOW,
  },
  id: {
    type: DataTypes.BIGINT,
    field: 'id',
    allowNull: false,
    primaryKey: true,
    autoIncrement: true,
  },
}, {
  tableName: 'test',
  timestamps: true,
  createdAt: "creation_time",
  updatedAt: "update_time",
  deletedAt: false,
});

await sequelize.sync({ force: true });

await Test.create({});
await Test.findAll();
```

However, in your example, the `update_time` column has different names in the database and in sequelize. May be the root of the issue.

As this thread is dead, and I couldn't replicate, I'll close the issue.
