### ISSUE TITLE
Migration: "up" provided a third argument halts, gives no errors and creates the table

### ISSUE THREAD

**Issue by svennidal** [sequelize/sequelize#11133]
## What are you doing?

```js
module.exports = {
  up: (queryInterface, { UUID, BOOLEAN, UUIDV4, STRING, DATE }, thirdArgument) =>
    queryInterface.createTable("Users", {
      id: {
        allowNull: false,
        defaultValue: UUIDV4,
        primaryKey: true,
        type: UUID,
        unique: true,
      },
      username: {
        type: STRING,
        unique: true,
      },
      name: STRING,
      email: STRING,
      role: STRING,
      password: STRING,
      active: {
        type: BOOLEAN,
        allowNull: false,
      },
      lastLogin: DATE,
      createdAt: {
        allowNull: false,
        type: DATE,
      },
      updatedAt: {
        allowNull: false,
        type: DATE,
      },
    }),
  down: queryInterface => queryInterface.dropTable("Users"),
};

```
**To Reproduce**
1. Define migration with a third argument
2. Run migrations
3. See no error

## What do you expect to happen?
To see some sort of error.

## What is actually happening?
1. Runs and hangs on migrations.
2. Creates the table
3. Says it's done, but does not say that it has migrated
4. Does not save the migration in SquelizeMeta

_Output, either JSON or SQL_
== 20190511134535-create-user: migrating =======
Done in 11.32s

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **pg** version: 7.11.0
Database version: 11.3
Sequelize version: 5.8.5
Node Version: 12.2.0
OS: Ubuntu
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.9.0

**Comment by 2kindsofcs** [comment]
it happens in mysql, too. but the sequelize-cli doesn't say something like `Done in 11.32s`.

```
Sequelize CLI [Node: 10.16.0, CLI: 5.5.1, ORM: 5.19.4]

Loaded configuration file "config\config.json".
Using environment "development".
== 20191009102358-create-user: migrating =======
```

**Comment by ephys** [comment]
You can declare any number of arguments you want in a JS function, we won't throw an error because your function accepts a third one, it'll just receive undefined
