### ISSUE TITLE
include option typescript type check doesn't accept strings

### ISSUE THREAD

**Issue by bogdan** [sequelize/sequelize#11132]
## What are you doing?

``` typescript
class User extends Model {
}

User.belongsTo(Country)

User.findAll({include: ['Country']}) // => raises error
User.findAll({include: ['Country'] as any}) // =>  works fine
```

## What do you expect to happen?

No error in the first call.

## What is actually happening?

```
lib/models/index.ts:17:19 - error TS2345: Argument of type '{ include: string[]; }' is not assignable to parameter of type 'FindOptions'.
  Types of property 'include' are incompatible.
    Type 'string[]' is not assignable to type 'Includeable[]'.
      Type 'string' is not assignable to type 'Includeable'.
```

## Environment

Sequelize version: 5.9.0
Node Version: 8
OS: Mojave 10.14.5
If TypeScript related: 3.4.4

**Comment by papb** [comment]
What is a use case for passing a string instead of a Model?

**Comment by bogdan** [comment]
At first it is documented.
But in general I can have multiple associations with the same class like:

``` js
Comment.hasMany(Comment, {as: 'children', foreignKey: 'parentId'})
Comment.belongTo(Comment, {as: 'parent', foreignKey: 'parentId'})
Subscription.belongsTo(User, {as: 'author', foreignKey: 'authorId'})
Subscription.belongsTo(User, {as: 'subscriber', foreignKey: 'subscriberId'})
```

**Comment by papb** [comment]
If you need to disambiguate, you can do:

```js
User.findAll({
    include: [{
        model: Comment,
        as: 'children'
    ]}
})
```

Right? Looks more type-safe to me, what do you think?

**Comment by bogdan** [comment]
I think that it is ambiguous to specify two option instead of one. I feel myself in nineties when I see that: back then people had to understand machines. Right now, if a software knows what I mean it just does that without asking additional questions aka options.

Woundn't it be so much easier to read:

``` js
findAll({include: ['children', 'parent']})
// then
findAll({include: [{model: Comment, as: 'children'}, {model: Comment, as: 'parent'}])
```

&lt;OFFTOPIC&gt;
I don't even tell you how much easier it would be to have, then its expanded nested hashes equivalent:

``` js
findAll({include: {parent: ['parent'], children: ['children']}) 
// suppose to load parent of a parent and children of children
```
But that is a story for another time.

**Comment by papb** [comment]
I'm convinced :+1:

**Comment by ephys** [comment]
This has since been resolved, the issue isn't present in Sequelize 6 anymore

I also agree that specifying the name of the association:

```js
include: ['children']
```

is generally better than specifying a model+as pair:

```
include: [{ model: User, as: 'children' }]
```

**Comment by blheson** [comment]
I currently use version 6.29.0 and I face the same error


 Code
```
 User.findAll({
    where: {
      status: {
        [Op.or]: [0,1,10] //throw error
      }
     }
```
```
 User.findAll({
    where: {
      status: {
        [Op.or]: [0,1,10] as any // does not throw error
      }
     }
```

Error Message
Type '{ [OpTypes.or]: number[]; }' is not assignable to type 'string | number | boolean | Buffer | WhereAttributeHash | AndOperator | OrOperator | Literal | Where | ... 5 more ... | (string | ... 2 more ... | WhereAttributeHash)[]'.
  Types of property '[Op.or]' are incompatible.
    Type 'number[]' is not assignable to type 'undefined'

**Comment by ephys** [comment]
That error is unrelated to this thread, please open a new bug report

**Comment by blheson** [comment]
Okay, got it
