### ISSUE TITLE
Sequelize ORM doesn't read numeric value 9xxxxxxx9.0000000000 properly

### ISSUE THREAD

**Issue by adityajaroli** [sequelize/sequelize#11131]
## What are you doing?
I am using Sequelize ORM in NodeJs to connect to MSSQL server. 
Recently I encountered an issue where one particular value gets represented differently when read via sequelize. That value is 9xxxxxxx9.0000000000

Ex: Suppose the value is 999999999.0000000000
When read via sequelize the value which comes is 999999999.0000001
In Sequelize the model has type DataTypes.INTEGER and allowNull is true

**To Reproduce**
1. In MsSql server, define a table and have a column name quantity with type as  numeric(28,10)
2. Insert a row with value 999999999.0000000000
3. Create a NodeJs app in which have a sequelize model for above created table and give the 
type of column as DataTypes.Integer 
4. Now read this table via sequelize.

## What do you expect to happen?
999999999

## What is actually happening?
999999999.0000001

## Environment
Dialect:
- [ ] mssql

Dialect **library** version: Latest
Database version: 2017
Sequelize version: 5.9.0
Node Version: 8.10.0
OS: OS X

Tested with latest release:
- [ ] No
- [YES] Yes, specify that version: 5.9.0

**Comment by amuzalevskiy** [comment]
In chrome debugger console
> parseFloat("999999999.00000001");
999999999
> parseFloat("999999999.00000006")
999999999.0000001

NodeJS v8 gives the same output

Is this mssql driver issue?

**Comment by eugene-matvejev** [comment]
you cannot do much about it, other than switch to bignumber.js 

https://www.w3schools.com/js/js_numbers.asp
