### ISSUE TITLE
How to get current table schema before defining one?

### ISSUE THREAD

**Issue by cbennington** [sequelize/sequelize#11142]
I am building an API endpoint where you can send SQL database settings and it will create a sequelize instance and define a model based on other settings passed in the request body. So it is all happening dynamically, there is no file holding the Model and it will be different a majority of the time this endpoint is called. It then syncs to the db and inserts or updates the data in the table after getting the data from an external API.

If a user had already used this endpoint to create a table in their database, and they want to change the schema but keep the data, how can I get the current schema from the database to compare to the request body schema they are asking for? Like I said I am doing it all on the fly so I am defining the model based on the current request body. This doesn't make a new table every time if the schema is the same, I just have to define it every time because I am doing this all in one method. So pretty much I want to check if the current schema is different than the schema they have sent in the request body so I can then know if I need to use the QueryInterface to add or remove columns to the table.

**Comment by papb** [comment]
I believe you should just do a [raw query](https://sequelize.org/master/manual/raw-queries.html) for this.
