### ISSUE TITLE
Why underscoredAll option is removed

### ISSUE THREAD

**Issue by ahas** [sequelize/sequelize#11154]
I think that underscoredAll option is necessary.
I defined 30 models and updated to v5 for supporting typescript.

then I will write specific foreignKeys for example ChannelId to channel_id and CustomerId to customer_id...
It is annoying process.

I used my model definition well until before underscoredAll option is removed.

Why? This update will only increase useless specific declaration for foreignKeys.

Therefore, the "underscoredAll" option must be rolled back.

**Comment by papb** [comment]
Closing in favor of #11225.

When #11225 gets closed, if anyone thinks this particular issue is still an issue, please ping me.
