### ISSUE TITLE
Superfluous data passed to create and update statements should be logged

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#11155]
When you pass additional data columns than supported by the sequelize model, they are ignored. However, that may be because someone forgot to add a  column. It would make sense to log a warning when this happens.

**Describe the solution you'd like**
An optional warning indicating that a data column is passed that doesn't match the model. Ideally, the data value should be logged. So, in case someone does fuck up, they can at least retrieve the data from the logs.

**Why should this be in Sequelize**
To avoid undetected bugs

**Comment by papb** [comment]
Closely related: #10136

**Comment by papb** [comment]
Closing in favor of #11872
