### ISSUE TITLE
compositeIndex unique not work

### ISSUE THREAD

**Issue by liuhaoliang** [sequelize/sequelize#11150]
When I write as document like this,bu it doesn't work. I use mysql in my project.

```
 uniqueOne: { type: Sequelize.STRING,  unique: 'compositeIndex' },
 uniqueTwo: { type: Sequelize.INTEGER, unique: 'compositeIndex' },
```

**Comment by papb** [comment]
Please provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).
