### ISSUE TITLE
Sequelize cuts keys of column

### ISSUE THREAD

**Issue by mtryba** [sequelize/sequelize#11153]
Hello, I have structure of my query like this

```
method.findOne({
    where: { id: 'ID' },
    include: [
      {
        model: db.deliveryMaterial, attributes: ['id'],
        include: [{ model: db.deliveryMaterialInspection ],
      },
    ],
  });
```
Generally, I have the first time the problem with it because I have more nested objects and everything was correct but now I receive from `deliveryMaterialInspection` `deliveryMaterialI` but I should receive `deliveryMaterialId`. When I do one more include in `deliveryMaterialInspection`, I have again no all key but now I have fewer chars of a key. Next include has key `fu` than `fullName`. I don't know where is the problem. I checked the result of SQL and generally, it's fine so the problem is in sequelize.

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version:7.8.0
Database version: 10
Sequelize version: latest
Node Version: 10
OS: macos
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.9.2

**Comment by papb** [comment]
This is a known problem with Postgres, it has a nested identifier limit of 63 characters, truncating anything that goes beyond that. For more information, see #2084.

Also, fortunately, looks like someone started working towards a fix very recently: #11095
