### ISSUE TITLE
Count with associations

### ISSUE THREAD

**Issue by kaikash** [sequelize/sequelize#11162]
## What are you doing?

**To Reproduce**
Let's imagine we have two models `User` and `Image`. And `Image` has two fields:
```js
imageableType: {
  type: DataTypes.STRING,
  field: 'imageable_type'
},
imageableId: {
  type: DataTypes.INTEGER,
  field: 'imageable_id'
}
```
Somewhere in `User` model:
```js
this.images = User.hasMany(Image, {
  foreignKey: 'imageableId',
  as: 'images',
  scope: {
    imageableType: 'user'
  }
};
```

We try to call `count` method
```js
const count = await User.count({
  include: [{
    association: User.images
  }]
});
```

*Update*: I didn't mention I have `underscored: true` option in models

## What do you expect to happen?
We want to get a number!

## What is actually happening?
But we get error: `column images.imageableType does not exist`

SQL: `SELECT count("User"."id") AS "count" FROM "users" AS "User" LEFT OUTER JOIN "images" AS "images" ON "User"."id" = "images"."imageable_id" AND ("images"."imageableType" = 'user');`
Actually, there should be `"images"."imageable_type" = 'user'`

And we get same error if we call `findAndCountAll`

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: 11.2
Sequelize version: 5.6.1
Node Version: 11.7.0
OS: macOS Mojave
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by nordikafiles** [comment]
Same problem

**Comment by kaikash** [comment]
@sushantdhiman

**Comment by papb** [comment]
Could you please test with another dialect, such as SQLite?

You can connect to an in-memory sqlite db by using `new Sequelize('sqlite::memory:')`.

**Comment by kaikash** [comment]
@papb I'm on vacation now, so I can't check it now.

**Comment by papb** [comment]
@kaikash No problem, take your time! @nordikafiles Can you help?

**Comment by kaikash** [comment]
@papb when using SQLite it makes query like this:

```SELECT count(*) AS `count` FROM `users` AS `User` LEFT OUTER JOIN `images` AS `image` ON `User`.`id` = `image`.`imageable_id` AND (`image`.`deleted_at` IS NULL AND `image`.`imageableType` = 'user') WHERE (`User`.`deleted_at` IS NULL);```

As you can see there is still `imageableType` instead of `imageable_type`

**Comment by papb** [comment]
Closing in favor of #11225.

When #11225 gets closed, if anyone thinks this particular issue is still an issue, please ping me.
