### ISSUE TITLE
Error: Please install tedious package manually

### ISSUE THREAD

**Issue by mostafa8026** [sequelize/sequelize#11168]
## What are you doing?
using the pkg (npm pacckager) and create an exe package.
```js
// A simple tedious application
```
**To Reproduce**
1- create a simple node application with tedious
2- npm install -g pkg
3- pkg -t win-x64 index.js -o apptedious
4- apptedious

## What do you expect to happen?
Run without any error.

## What is actually happening?
Error: Please install tedious package manually

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [x] mssql
- [ ] any
Dialect **tedious ** version:6.2.0
Database version: mssql 2016
Sequelize version: 5.9.4
Node Version: 8.11.3
OS: Windows 10
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.9.4

**Comment by papb** [comment]
I don't think this is a problem with sequelize. It is more likely to be a problem with pkg (or you did something wrong).

Are you sure `tedious` is in your package.json?

**Comment by mostafa8026** [comment]
Yes, I', sure.

**Comment by mostafa8026** [comment]
It is my dependencies:
"dependencies": {
    "chalk": "^2.4.2",
    "cli-progress": "^2.1.1",
    "cliui": "^5.0.0",
    "delay": "^4.3.0",
    "json-diff": "^0.5.4",
    "request-promise": "^4.2.4",
    "sequelize": "^5.9.4",
    "tty-table": "^2.7.1",
    "xml2js": "^0.4.19",
    "yargs": "^13.2.4",
    "tedious": "^6.2.0"
  }

**Comment by papb** [comment]
Can you try using pkg with the `-b` option?

> -b, --build      don't download prebuilt base binaries, build them

If that doesn't work, can you try using [nexe](https://github.com/nexe/nexe) instead of pkg?

**Comment by mostafa8026** [comment]
pkg -b cause this error:

```
$ pkg -b -t win-x64 index.js -o sync
> pkg@4.4.0
> Building base binary from source:
  built-v8.16.0-win-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v8.16.0
> Applying patches

> Error! Error: spawn patch ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

`nexe` does not encounter with the `Please install tedious package manually` error, but it cause another error:

```
TypeError: Cannot read property 'getServerCounter' of undefined
```

which the `getServerCounter` is one of my functions. 
consider that the program works correctly without packaging.

**Comment by papb** [comment]
Hmm... I am starting to believe that this is being caused by the dynamic require call to `tedious` by sequelize. Pkg does not solve this automatically, but it can be solved manually.

Please take a look at the following:

* [Pkg config guide](https://github.com/zeit/pkg/blob/master/README.md#config)
* [Pkg issue 564](https://github.com/zeit/pkg/issues/564)
* [Pkg issue 127](https://github.com/zeit/pkg/issues/127)

Let me know if from these you can solve your problem.

**Comment by mostafa8026** [comment]
Thanks a lot, I solved problem with referencing the needed stuff in assets and scripts like follow:

``` json
"pkg": {
    "scripts": ["node_modules/tedious/lib/tedious.js", "models/*.js"],
    "assets": ["config/log.json"]
  }
```

**Comment by papb** [comment]
Nice :grimacing:

Can you close the issue?

**Comment by mostafa8026** [comment]
OFCOURSEEEEEE

**Comment by LiamKarlMitchell** [comment]
Was getting this error when trying to use sequelize-auto.
Installing tedious globally seems to resolve it...

```
npm install -g tedious sequelize-auto
sequelize-auto -o "./models" -d databasenameHere -h hostnameHere -u usernameHere -p portHere -x passwordHere -e mssql
```

**Comment by JonLopezGarcia** [comment]
I had this issue when building my node server app and bundling all the dependencies in a single file.

Webpack was unable to guess that my app was depending on `tedious` therefore not bundling with the rest of my dependencies.
I solved the issue by providing the `tedious` module in the `sequelize` configuration like so : 

``` js
import * as tedious from 'tedious';
...
const db = new Sequelize({
  dialect: 'mssql',
  dialectModule: tedious,
  ...
});
```

By writing a static import Webpack embeds the `tedious` module in the bundle 🚀 

**Official documentation** [here](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html) ; Search for **dialectModule** option

**Comment by papb** [comment]
Hi @JonLopezGarcia, great that you figured it out. Maybe you can help me with #13169 as well?
