### ISSUE TITLE
navigation in docs

### ISSUE THREAD

**Issue by eugene-matvejev** [sequelize/sequelize#11167]
### If possible: Provide some suggestion how we can enhance the docs

by reading [QueryInterface](http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-bulkInsert) manual

as a user i am pushed to search a lot, rather than navigate smoothly just by clicking link/hover

for example: 

if we go in table of arguments:
options | Object |   | Various options, please see Model.bulkCreate options

as a user, I am pushed to search it manually, it would be nice if Model.bulkCreate would be a link

e.g. make it like this:
options | Object |   | Various options, please see [Model.bulkCreate](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-bulkCreate) options

there are other examples like this, it would improve user experience :)

i assume, documentation auto-generator need to be changed, not sure how I could help here :)

**Comment by ephys** [comment]
We're slowly doing this when possible, but I'll close this issue as there is no definite end point where this can be considered done. PRs to do this in more places in our TSDoc are welcome
