### ISSUE TITLE
`queryInterface.createFunction` should default to `CREATE OR REPLACE` syntax.

### ISSUE THREAD

**Issue by mannol** [sequelize/sequelize#11165]
## What are you doing?

```js
    queryInterface.createFunction(
            'is_timezone',
            [{ type: 'TEXT', name: 'tz', direction: 'IN' }],
            'BOOLEAN',
            'plpgsql',
            `
                PERFORM now() AT TIME ZONE tz;
                RETURN TRUE;
                EXCEPTION WHEN invalid_parameter_value THEN
                    RETURN FALSE;
            `,
            ['IMMUTABLE', 'LEAKPROOF'],
        );
```
**To Reproduce**
1. Call the above function twice, and you'll get an error

## What do you expect to happen?
Expecting following sql to run:
```sql
CREATE OR REPLACE FUNCTION is_timezone(IN tz TEXT) RETURNS BOOLEAN AS $func$ BEGIN 
  PERFORM now() AT TIME ZONE tz;
  RETURN TRUE;
  EXCEPTION WHEN invalid_parameter_value THEN
    RETURN FALSE;
END; $func$ language 'plpgsql'IMMUTABLE LEAKPROOF;
```

## What is actually happening?
```sql
CREATE FUNCTION is_timezone(IN tz TEXT) RETURNS BOOLEAN AS $func$ BEGIN 
  PERFORM now() AT TIME ZONE tz;
  RETURN TRUE;
  EXCEPTION WHEN invalid_parameter_value THEN
    RETURN FALSE;
END; $func$ language 'plpgsql'IMMUTABLE LEAKPROOF;
```
(Note the lack of `OR REPLACE` syntax)

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: ^7.9.0
Database version: 9.6
Sequelize version: ^5.3.5
Node Version: 8.x
OS: Linux
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by papb** [comment]
Perhaps an option would be better, something like `{ replaceIfNecessary: true }` (which would default to false)? I think this would be a safer option. Replacing by default seems dangerous. What do you think?

**Comment by eugene-matvejev** [comment]
I think parameter like { force: true } or as @papb referred is better, as we would stay back-wards compatible :)

**Comment by mannol** [comment]
Yeah, `{ force: true }` flag would be good.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/11172
