### ISSUE TITLE
Custom datatype not working

### ISSUE THREAD

**Issue by Bene-Graham** [sequelize/sequelize#11177]
## What are you doing?

```ts
// Custom Type File
import Big from "big.js";

export default function sequelizeAdditions(Sequelize) {

    const DataTypes = Sequelize.DataTypes;

    /*
     * Create new types
     */
    class BIGJS extends DataTypes.DECIMAL {
        public static parse(value) {
            return new Big(value);
        }

        private _precision: number;
        private _scale: number;

        constructor(precision: number, scale: number) {
            super();

            this._precision = precision;
            this._scale = scale;
        }

        public toSql() {
            if (this._precision || this._scale) {
                return `DECIMAL(${[this._precision, this._scale].filter(this.identity).join(",")})`;
            }

            return "DECIMAL";
        }

        // Optional, validator function
        public validate(value, options) {
            if (value instanceof Big) {
                return true;
            } else {
                return false;
            }
        }
    }

    DataTypes.BIGJS = BIGJS;

    // Mandatory, set key
    DataTypes.BIGJS.prototype.key = DataTypes.BIGJS.key = "BIGJS";

    // For convenience
    // `classToInvokable` allows you to use the datatype without `new`
    Sequelize.BIGJS = Sequelize.Utils.classToInvokable(DataTypes.BIGJS);
}

// Connection File
import { Sequelize } from "sequelize";
import BigJsCol from "./types/BigJsColumn";

BigJsCol(Sequelize);

const sequelize = new Sequelize(...);

// Model File
MyModel.init({
    id: {
        type: DataTypes.INTEGER.UNSIGNED,
        autoIncrement: true,
        primaryKey: true,
    },
    amount: new DataTypes.BIGJS(13, 4)
}, {
    sequelize: Connection,
    tableName: "MyModel",
});

// Simple Query
await MyModel.findAll();
```
**To Reproduce**
1. Defined models, and get everything wired up
2. Run simple query
3. Result for the field amount is not wrapped in a BigJs object

## What do you expect to happen?
I would like the result coming back from the database to be wrapped

## What is actually happening?
It is just returning a number :(

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect mysql2 version: 1.6.5
Database version: 5.7.26
Sequelize version: 5.9.3
Node Version: 12.x
OS: Mac OS 10.14.5
If TypeScript related: TypeScript version: 3.5.3
Tested with latest release:
- [ ] No
- [x] Yes, specify that version:

**Comment by papb** [comment]
Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? You included a lot of code but it doesn't seem self contained. I can't just copy-paste. Thanks!

**Comment by papb** [comment]
Also, can you check if this problem happens in another dialect?

**Comment by Bene-Graham** [comment]
I added a little sample project in this repo: https://github.com/Bene-Graham/SequelizeCustomColumnTypeBug

Couple of things I have noticed:

1. Copying the custom type that is shown in the doc does nto work either: https://sequelize.org/master/manual/data-types.html
2. ```.sync()``` does not work with custom types it puts the wrong DB type in the create table statement

```sql
CREATE TABLE IF NOT EXISTS `MyTestModel` 
(
`id` INTEGER UNSIGNED auto_increment , 
`amount` DECIMAL, 
`myInt` ABSTRACT, 
`createdAt` DATETIME NOT NULL, 
`updatedAt` DATETIME NOT NULL, 
PRIMARY KEY (`id`)
) ENGINE=InnoDB;
```

**Comment by papb** [comment]
Was this intended? (I switched to sqlite)

![](https://i.imgur.com/MgpVqL2_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by Bene-Graham** [comment]
Yes, as far as I can tell the current set of types with v5 don't have a way of not throwing a compile error.

**Comment by papb** [comment]
Ignoring the compile error, I got `ReferenceError: connection is not defined` now.

**Comment by Bene-Graham** [comment]
interesting, can you give me the stack trace? I do not get that on my machine.

**Comment by papb** [comment]
Nevermind, I messed up the typescript execution

I got:

```
SequelizeDatabaseError: SQLITE_ERROR: no such table: MyTestModel
{ Error: SQLITE_ERROR: no such table: MyTestModel
     errno: 1,
     code: 'SQLITE_ERROR',
     sql: 'DELETE FROM `MyTestModel` WHERE `id` > 0' }
```

Which I believe to be the intended reproduction of the bug :+1:

**Comment by Bene-Graham** [comment]
for that error you may need to uncomment:
```ts
await connection.sync();
```

in the index.ts file, I had that commented out due to it not working with the custom type(s) and mysql. In the end I just manually created the table and columns.

**Comment by moberegger** [comment]
Taking a peak it your reproduction, I think the steps from https://sequelize.org/master/manual/data-types.html#postgresql are missing, where it says:
> After creating this new datatype, you need to map this datatype in each database dialect and make some adjustments.

It is hard to make sense of that example, though. The example given is for Postgres, so it's not clear what is required for other dialects (they all seem to have types assigned slightly differently in the source). Furthermore, it uses an `inherits` API which isn't available anywhere (I think it used to be part of `utils` in V4).

Another issue (https://github.com/sequelize/sequelize/issues/10964) was posted where the author was having the same problem. 

Is this feature fully supported?

**Comment by papb** [comment]
@moberegger It should be, I believe, although the docs really need fixing. I will hopefully be able to take a look soon. If you could dig a bit and find out how to do it, that would be awesome... But if you don't have the time, I shall do it in the near future.

**Comment by moberegger** [comment]
Yeah, I was looking through how the "proper" types are done and was gonna try just mimicking that to see if it worked. There is quite a bit of boilerplate involved (... at least at first glance) that makes me think that it could be easier to make a nice API around it, rather than trying to thoroughly document the current way.

For my purposes, I am just trying to get a `SMALLDATETIME` type working for MSSQL. It's been discussed before (https://github.com/sequelize/sequelize/issues/7879#issuecomment-329971730) and a solution was proposed a _long_ time ago (https://github.com/sequelize/sequelize/pull/10167). The API of the internals look to be much much nicer now, so this may be easier to do.

The one thing I am uncertain of is how something would behave for a type that is only provided for one dialect (MSSQL, in this case). I imagine that we would have to provide `SMALLDATETIME` for each dialect, even if it were to just default to a regular `DATE`?

**Comment by papb** [comment]
@moberegger There are already some datatypes which are available for a single dialect, such as [INET](https://sequelize.org/master/class/lib/data-types.js~INET.html) for postgres, so I think it is fine to have a `SMALLDATETIME` for MSSQL only - just try to mimick what was done for INET for example.

If you're willing to submit a PR that would be great!

**Comment by moberegger** [comment]
@papb Oh nice, I'll take a look at those then. If I can get something working, maybe it can serve as a good example.

**Comment by segersniels** [comment]
I seem to be stuck on creating custom DataTypes in v5 as well. It never seems to call the `toSql()` when actually running queries. So instead of trying to execute (`CREATE TABLE`) `'id' OBFUSCATEDID NOT NULL auto_increment` it's trying to do `'id' OBFUSCATEDID NOT NULL auto_increment` which obviously doesn't work.

```
import { obfuscator } from '../registry';
import { ValidationError } from 'sequelize';
const { ABSTRACT } = require('sequelize/lib/data-types');

export const sequelizeAdditions = (Sequelize: any) => {
  /*
   * Create new types
   */
  class OBFUSCATEDID extends ABSTRACT {
    escape = false;
    key = 'OBFUSCATEDID';
    dialectTypes = '';

    toSql() {
      return 'BIGINT(20) UNSIGNED';
    }

    validate(value: any) {
      if (typeof value !== 'number') {
        throw new ValidationError(`${value} is not a valid obfuscated ID`);
      }

      return true;
    }

    sanitize(value: any, options: any) {
      if (typeof options !== 'object' || options.raw !== true) {
        return value;
      }

      if (value === null || typeof value === 'undefined') {
        return value;
      }

      return obfuscator.encode(parseInt(value));
    }

    stringify(value: any) {
      if (value === null || typeof value === 'undefined') {
        return value;
      }

      return obfuscator.decode(value);
    }
  }

  Sequelize.DataTypes.OBFUSCATEDID = OBFUSCATEDID;

  Sequelize.DataTypes.OBFUSCATEDID.prototype.key = Sequelize.DataTypes.OBFUSCATEDID.key =
    'OBFUSCATEDID';

  Sequelize.OBFUSCATEDID = Sequelize.Utils.classToInvokable(
    Sequelize.DataTypes.OBFUSCATEDID,
  );
};
```

**Comment by papb** [comment]
I will try to figure this out :)

**Comment by segersniels** [comment]
@papb Any progress on this? Haven't figured it out myself, still can't get it to work with v5. It used to work in v4 though but yeah, that was using the old way.

**Comment by ktret** [comment]
RE: It never seems to call the toSql() when actually running queries.

More-so it seems to call ABSTRACT's toSql.  My new data type extends ABSTRACT, and ABSTRACT's toSql is `return this.key` so if when I manage to set key to the postgres type, it creates the column in the database fine.  But an instance `x` of said type for a field does not pass `x instanceof NEWTYPE` check.  Sorry, probably not making much sense, and no time to provide code right now.

Anyway, if you can make your key be 'BIGINT(20) UNSIGNED' or whatever you want the database to get, it might create the column fine, but you may still have issues if you check instanceof and such.

**Comment by sm2017** [comment]
@papb I have same issue , Any temporary solution?

**Comment by papb** [comment]
Hello, I haven't made any progress on this, sorry, but if I'm not mistaken there is someone who looks to have a custom data type working - see #11550

**Comment by itsmebasti** [comment]
@sm2017 as mentioned by @ktret overriding the `key` propperty seems to work at least for the created sql statements, I implemented it like this:
```
    class CUSTOM extends DataTypes.ABSTRACT {
        constructor() {
            super();
            this.key = 'VARCHAR(255)';
        }
```
but as he mentioned it is not a solid workaround, since it fails for `instanceof` checks.

**Comment by mcuelenaere** [comment]
The issue lays with `classToInvokable`, which doesn't allow access to the actual constructor. The following code shows how we worked around that:

```javascript
const DataTypes = require('sequelize/lib/data-types');
const { classToInvokable } = require('sequelize/lib/utils/classToInvokable');

// since DataTypes.ABSTRACT is wrapped with classToInvokable(), we can't get to
// the actual class directly, so use this indirection
const ABSTRACT = DataTypes.ABSTRACT.prototype.constructor;

class Custom extends ABSTRACT {
  static key = 'CUSTOM';

  toSql() {
    return 'BIGINT(20) UNSIGNED';
  }

  ...
}
DataTypes.CUSTOM = classToInvokable(Custom);
```

**Comment by Aaron-Bird** [comment]
Is there a solution to this problem?

**Comment by awwit** [comment]
@papb hi, I think I know how to solve this problem. Try using the solution from here: https://stackoverflow.com/a/47268401/3684944

**Comment by Mygod** [comment]
So could anyone *please* update the documentations to reflect the correct way to implement custom datatypes?

**Comment by anthonyorona** [comment]
This is a snippet of code that shows how I was able to add the ltree extension as a custom datatype using the workaround of @mcuelenaere 

`const util = require('util'); // Built-in Node package
const DataTypes = require('../../../node_modules/sequelize/lib/data-types');
const { classToInvokable } = require('../../../node_modules/sequelize/lib/utils/class-to-invokable');

const ABSTRACT = DataTypes.ABSTRACT.prototype.constructor;

const sequelizeAdditions = (Sequelize) => {
  let DataTypes = Sequelize.DataTypes;
  
  // CREATE NEW TYPE
  class LTREE extends ABSTRACT {
    // Mandatory, complete definition of the new type in the database
    toSql() {
      return 'ltree';
    }
    static parse(value) {
      return value;
    }
  }
  DataTypes.LTREE = classToInvokable(LTREE);
  DataTypes.LTREE.prototype.key = 'ltree';
  DataTypes.LTREE.key = DataTypes.LTREE.prototype.key;
  Sequelize.LTREE = Sequelize.Utils.classToInvokable(DataTypes.LTREE)
  DataTypes.LTREE.types.postgres = ['ltree']

  let PgTypes = DataTypes.postgres

  PgTypes.LTREE = function LTREE() {
    if (!(this instanceof PgTypes.LTREE)) return new PgTypes.LTREE();
    DataTypes.LTREE.apply(this, arguments);
  }
  
  util.inherits(PgTypes.LTREE, DataTypes.LTREE);
  PgTypes.LTREE.parse = DataTypes.LTREE.parse;
  PgTypes.LTREE.types = {postgres:['ltree']};
  DataTypes.postgres.LTREE.key = 'ltree';
}

export default sequelizeAdditions;
`

**Comment by brtdv** [comment]
+1 
This also does not work for me, any updates here?

I followed all steps from the docs (https://sequelize.org/master/manual/extending-data-types.html - Example + Creating a MySQL specific data type), but when instantiating my Sequelize object, I get a `TypeError: Cannot read property 'mysql' of undefined`. 

I'm using Sequelize 6.6.2.

```
/...project-root.../node_modules/sequelize/lib/dialects/abstract/connection-manager.js:72
          if (dataType.types[_this.dialectName]) {
                            ^

TypeError: Cannot read property 'mysql' of undefined
    at iteratee (/...project-root.../node_modules/sequelize/lib/dialects/abstract/connection-manager.js:48:13)
    at baseFor (/...project-root.../node_modules/lodash/lodash.js:4967:15)
    at eachFunc (/...project-root.../node_modules/lodash/lodash.js:3032:24)
    at func (/...project-root.../node_modules/lodash/lodash.js:4936:18)
    at Function.each [as forEach] (/...project-root.../node_modules/lodash/lodash.js:9410:14)
    at ConnectionManager.refreshTypeParser (/...project-root.../node_modules/sequelize/lib/dialects/abstract/connection-manager.js:46:7)
    at new ConnectionManager (/...project-root.../node_modules/sequelize/lib/dialects/mysql/connection-manager.js:26:10)
    at new MysqlDialect (/...project-root.../node_modules/sequelize/lib/dialects/mysql/index.js:15:30)
    at new Sequelize (/...project-root.../node_modules/sequelize/lib/sequelize.js:340:20)
    at Object.<anonymous> (/...project-root.../src/models/index.js:10:18)
```

The `src/models/index.js:10:18` is the place where I start up Sequelize with `const instance = new Sequelize(dbCfg.dbname, dbCfg.user, dbCfg.password, { ...dbCfg });`

I did the mapping of a custom type like this:

```js
const util = require('util');

module.exports = (Sequelize) => {
  const DataTypes = Sequelize.DataTypes

  /*
   * Create new types
   */
  class INTDATETIME extends DataTypes.ABSTRACT {
    // Mandatory, complete definition of the new type in the database
    toSql() {
      return 'INTEGER(11) UNSIGNED NULL'
    }

    // Optional, value stringifier before sending to database
    _stringify(value) {
      return Math.floor(value.getTimestamp() / 1000);
    }

    // Optional, parser for values received from the database
    static parse(value) {
      return (new Date()).setTimestamp(value * 1000)
    }
  }

  DataTypes.INTDATETIME = INTDATETIME;

  // Mandatory, set key
  DataTypes.INTDATETIME.prototype.key = DataTypes.INTDATETIME.key = 'INTDATETIME'

  // For convenience
  // `classToInvokable` allows you to use the datatype without `new`
  Sequelize.INTDATETIME = Sequelize.Utils.classToInvokable(DataTypes.INTDATETIME)



  const MySQLTypes = DataTypes.mysql;

  // Mandatory: map postgres datatype name
  DataTypes.INTDATETIME.types.mysql = ['my_int_datetime'];

  // Mandatory: create a postgres-specific child datatype with its own parse
  // method. The parser will be dynamically mapped to the OID of mysql_int_datetime.
  MySQLTypes.INTDATETIME = function INTDATETIME() {
    if (!(this instanceof MySQLTypes.INTDATETIME)) {
      return new MySQLTypes.INTDATETIME();
    }
    DataTypes.INTDATETIME.apply(this, arguments);
  }
  const util = require('util'); // Built-in Node package
  util.inherits(MySQLTypes.INTDATETIME, DataTypes.INTDATETIME);

  // Mandatory: create, override or reassign a postgres-specific parser
  // MySQLTypes.INTDATETIME.parse = value => value;
  MySQLTypes.INTDATETIME.parse = DataTypes.INTDATETIME.parse || ((x) => x);

  // Optional: add or override methods of the postgres-specific datatype
  // like toSql, escape, validate, _stringify, _sanitize...
}
```

This file is imported in `src/models/index.js` like this:
```js
const { Sequelize, DataTypes, Utils } = require('sequelize');
const intDateTimeDataType = require('../datatypes/intDateTime.js')(Sequelize);
const instance = new Sequelize(dbCfg.dbname, dbCfg.user, dbCfg.password, { ...dbCfg });
```

Is there *anyone* that got custom datatypes to work? I've also tried searching code examples on Github in other libraries but this feature seems pretty obscure?

**Comment by Mygod** [comment]
From my testing, it does not seem the `parse` function is ever invoked?

https://github.com/sequelize/sequelize/blob/1c1aa33068c608ad5c66a18d8aae27c697a5d89e/lib/dialects/abstract/query-interface.js#L1006-L1021

**Comment by wasiq-naqi** [comment]
> The issue lays with `classToInvokable`, which doesn't allow access to the actual constructor. The following code shows how we worked around that:
> 
> ```js
> const DataTypes = require('sequelize/lib/data-types');
> const { classToInvokable } = require('sequelize/lib/utils/classToInvokable');
> 
> // since DataTypes.ABSTRACT is wrapped with classToInvokable(), we can't get to
> // the actual class directly, so use this indirection
> const ABSTRACT = DataTypes.ABSTRACT.prototype.constructor;
> 
> class Custom extends ABSTRACT {
>   static key = 'CUSTOM';
> 
>   toSql() {
>     return 'BIGINT(20) UNSIGNED';
>   }
> 
>   ...
> }
> DataTypes.CUSTOM = classToInvokable(Custom);
> ```

This works perfect for me, Thank you soo much

**Comment by jedwards1211** [comment]
@ephys is this only going to be fixed in v7?

I had a custom data type working in v4, just tried upgrading to v6 and I'm also struggling, but really need to be able to upgrade to a non-beta version.

**Comment by jedwards1211** [comment]
As far as I can tell from reading the code and testing, it's not actually mandatory to subclass the custom data type for a dialect.  `normalizeDataType` will replace a data type with a dialect-specific one if it exists, but otherwise it will keep it as is.

It also seems unnecessary to monkeypatch new data types onto `Sequelize.DataTypes`.  I'm exporting my custom data type from one module and importing it directly into the module where I'm defining a model class and it works just fine.
