### ISSUE TITLE
ERROR: Please install sqlite3 package manually

### ISSUE THREAD

**Issue by elenaaralla** [sequelize/sequelize#11174]
after installing sequelize-cli and express-generator
`npm install -g sequelize-cli express-generator`

I create my express app with:
`express --view=pug todos-manager`

Then I installed sequelize and sqlite3
```
cd todos-manager && npm install
npm install --save sequelize
npm install --save sqlite3
```
I initialized sequelize
`sequelize init`
and corrected config/config.json with data to connect to my sqlite db

Then created a model and migtation
`sequelize` model:create --name Todo --attributes title:string,description:string

Running this 
`sequelize db:migrate `

I got the error:

```
Sequelize CLI [Node: 10.16.0, CLI: 5.5.0, ORM: 5.8.12]

Loaded configuration file "config\config.json".
Using environment "development".

ERROR: Please install sqlite3 package manually
```
I've tried to rebuild, with no success.

Any ideas?

**Comment by eugene-matvejev** [comment]
i had same issue, `npm rebuild` helped me

**Comment by elenaaralla** [comment]
npm rebuild done with no success :(

**Comment by eugene-matvejev** [comment]
try `npm i sqlite3 -D &&  rm -rf node_modules && npm i && npm rebuild` these are all steps which come in my mind :)

**Comment by elenaaralla** [comment]
Thank you, I'll try it asap.

Have a nice day.

**Comment by elenaaralla** [comment]
I got this error
```
"rm" it is not recognized as an internal or external command,
 an executable program or a batch file.
```

**Comment by eugene-matvejev** [comment]
@elenaaralla i think you got windows, i use macbook, rm is unix command :)
rm -rf = force remove of node_modules

**Comment by elenaaralla** [comment]
@eugene-matvejev : yes, windows 10 virtual machine

I tryed... no success.

this is the cmd output:
[sequelizetest.txt](https://github.com/sequelize/sequelize/files/3376826/sequelizetest.txt)

**Comment by papb** [comment]
@elenaaralla Try the following:

1. `npm i -g rimraf`
2. `npm i -D sqlite3`
3. `rimraf node_modules`
4. `npm i`

**Comment by elenaaralla** [comment]
Hi all,

the error does not occur if I use the statement:

`npx sequelize-cli db:migrate`

instead of

sequelize db:migrate

`and migration is successful!`

Thanks to all.

**Comment by papb** [comment]
@elenaaralla Nice! Looks like you have the sequelize-cli installed both locally and globally, is that right? Can you check this please?

(I know you already found a solution but understanding the problem is important to prevent this for other users)

**Comment by liees** [comment]
> 我在vue-cli-plugin-electron-builder构建的项目中遇到这个问题 node-v10.14.2
> ![image](https://user-images.githubusercontent.com/22437483/67463199-8f751e00-f673-11e9-8466-8f23ac6c504c.png)

hi, 
I use vue-cli add electron-builder too,
install sqlite3 & rebuild is success, but I got "Please install sqlite3 package manually"

Did you find a solution?

**Comment by huan0118** [comment]
No, I used KNEX

**Comment by liees** [comment]
> No, I used KNEX

I also browsed knex, can you communicate with me?

**Comment by erickTrettel** [comment]
For those who still have this error, I installed sqlite3 globally as a workaround and it worked
`npm i -g sqlite3`

**Comment by terrapanda** [comment]
Update your node version to latest. Worked for me.

**Comment by kylegoetz** [comment]
I'm been getting this, too. I have tried a project install of sqlite3 and a global install. Same error in file `connection-manager.js` on line 

`this.lib = require(sequelize.config.dialectModulePath || 'sqlite3').verbose();`

leading to 

`throw new Error('Please install sqlite3 package manually');`

**Comment by MaximKing1** [comment]
> I'm been getting this, too. I have tried a project install of sqlite3 and a global install. Same error in file `connection-manager.js` on line
> 
> `this.lib = require(sequelize.config.dialectModulePath || 'sqlite3').verbose();`
> 
> leading to
> 
> `throw new Error('Please install sqlite3 package manually');`
> 
> Have deleted and re-installed all node_modules, too.

im having this issue aswell any fixes yet?

**Comment by gimousanna** [comment]
Hi,

i have the same issue

**Comment by desiquinn** [comment]
Ran into the same Issue. However, it began working for me after running `npm rebuild`

**Comment by fedulovivan** [comment]
for everyone who faced with this problem: check out this one - #15657. the root cause could be not in missing sqlite3 package.

**Comment by LunaticMuch** [comment]
I have the issue, and yes the rebuild does not fix. Sqlite is well installed.

**Comment by icodejsx** [comment]
none of this is not working

**Comment by s1nistr4** [comment]
This is more webpack's fault than it is sequelize. Webpack has gotta be one of the worst pieces of software I've used. Constant extremely crucial issues like this where if the devs tested their code before they shipped it they'd immediately notice this software breaking problem and how awful it is to use

Switch to Esbuild. You copy like 5 lines of code to make it work and done, no bs, no searching through github repos and issues trying to get webcrap to be compatible with (insert software name here), and the code is faster and smaller bundle size. Webpack is 80% of the reason people hate the js ecosystem
