### ISSUE TITLE
Discrepancy in docs vs typescript types for locks

### ISSUE THREAD

**Issue by michaelfarrell76** [sequelize/sequelize#11178]
## What are you doing?

I am attempting to lock a table when I perform a find query. The documentation seems to have a discrepancy in how these locks can be created, however the typescript types do not sync up

The following will produce a type error:

```ts
await MigrationLock.findAll({
  where: { isLocked: false },
  transaction,
  lock: true,
});
```

See below for all of the typescript warnings that also seem to be valid code as stated in the docs [here](http://docs.sequelizejs.com/manual/transactions.html#locks) and [here](http://docs.sequelizejs.com/class/lib/transaction.js~Transaction.html#static-get-LOCK)

![Screen Shot 2019-07-10 at 1 02 16 PM](https://user-images.githubusercontent.com/10264973/61000950-65415f80-a313-11e9-8c74-4823ed624f07.png)
![Screen Shot 2019-07-10 at 1 02 37 PM](https://user-images.githubusercontent.com/10264973/61000951-65d9f600-a313-11e9-9723-8bc74b12ef36.png)
![Screen Shot 2019-07-10 at 1 02 41 PM](https://user-images.githubusercontent.com/10264973/61000953-65d9f600-a313-11e9-8778-6b22e32bb733.png)

**To Reproduce**
1. Define model `MigrationLock` using typescript
2. Try to provide `lock: true` in `findAll`
3. See typescript error

## What do you expect to happen?
I want to be able to have a type-safe find lock on a table

## What is actually happening?
Typescript keeps yelling at me

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any

Dialect **library** version: 10.4
Database version: 10.4
Sequelize version: 5.9.4
Node Version: v10.15.0
OS: OSX Mojave 10.14.5

If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 3.5.2

**Comment by aecorredor** [comment]
Having the same issue here. 

When I do something like:

```js
const user = await models.sequelize.transaction(async t => {
      const contest = await models.Contest.findByPk(id, {
        transaction: t,
        lock: true,
      });
    });
```

I get `Type 'true' is not assignable to type 'LOCK | { level: LOCK; of: typeof Model; } | undefined'.`

**Comment by aecorredor** [comment]
Any updates?

**Comment by papb** [comment]
@aecorredor No, would you like to try to make a PR?

**Comment by aecorredor** [comment]
@papb sure thing, I'll give it a shot, just wanted to make sure that it was indeed a bug in the types and not me doing something wrong.

**Comment by papb** [comment]
@aecorredor Ah, ok! Indeed looks like a bug. Thank you very much. I will fix the issue label

**Comment by aecorredor** [comment]
@papb PR for this issue is here: https://github.com/sequelize/sequelize/pull/11620. Let me know if everything looks good or if I need to do something else. It's my first time making a PR for this repo, so I might have missed something.

**Comment by ephys** [comment]
Looks like this was fixed by https://github.com/sequelize/sequelize/pull/11620
