### ISSUE TITLE
IncludeThroughOptions missing definition for 'as'

### ISSUE THREAD

**Issue by a88zach** [sequelize/sequelize#11185]
## What are you doing?
IncludeThroughOptions typing does not contain the 'as' property

```typescript
through: {
        as: 'physicianSpecialty',
        attributes: ['isPrimary']
      } as IncludeThroughOptions // must cast here since 'as' is not defined in typings
```

## What do you expect to happen?
TS should compile without having to cast the through options

## Environment
If TypeScript related: TypeScript version: 3.5.3
Tested with latest release:
- [ ] No
- [X] Yes, specify that version:

**Comment by JohnRostislavovich** [comment]
Have the same problem

**Comment by a88zach** [comment]
When you have a many to many table that you need to query through, the name of the property in the instance will be the model name of the through table by default.

When you set the as property of the IncludeThroughOptions it renames that property in the instance.  This is useful when you want to always return camelCase names through your API

If I have a Book, Author, and BookAuthor table and I want to get all books written by an author, the instance would look like this by default
```
{
  authorId: 'foo',
  authorName: 'John Doe',
  BooksAuthor: [{
    id: 'foo',
    bookId: 'foo',
    authorId: 'foo',
    Book: {
      bookId: 'foo',
      bookName: 'foo'
    }
  }]
}
```

The `as` property controls the naming of `BookAuthor` so that I can set it to `bookAuthor` per my naming conventions

**Comment by mrcrow85** [comment]
Alright I will try to create a sscce

**Comment by mrcrow85** [comment]
@papb [SSCCE here](https://github.com/papb/sequelize-sscce/pull/21). Please let me know if that's enough or I need to do something else :slightly_smiling_face:

**Comment by papb** [comment]
@mrcrow85 Fantastic!! Thank you very much. I will comment on your PR

**Comment by avrtau** [comment]
This is still an issue in v6

**Comment by ephys** [comment]
The type does seem to be present in v6: https://github.com/sequelize/sequelize/blob/a25005855b5282533a17235b3dd2d2a5eb8723c2/src/model.d.ts#L626
