### ISSUE TITLE
{ alter: true } conflict width sqlite_sequence initialAutoIncrement

### ISSUE THREAD

**Issue by zdsjason** [sequelize/sequelize#11180]
{ alter: true }
and 
insert into sqlite_sequence(name, seq) values('tests', 10000)
is conflicted

```js
await Test.sync({ alter: true });
const rows = await sequelize.query(`select * from sqlite_sequence where name='tests'`)
if (rows[0].length == 0) {
    await sequelize.query(`insert into sqlite_sequence(name, seq) values('tests', 10000)`)
}
```
![image](https://user-images.githubusercontent.com/4597830/61019537-1eb03b80-a3cd-11e9-8b2a-bc85c82559f3.png)

## Environment
Dialect:
- [ ] sqlite
Database version: 4.0.9
Sequelize version: 5.9.2
Node Version: 10.15.3
OS: mac

**Comment by papb** [comment]
Can you provide a full code to reproduce the issue? You have given only a part of the code. Take a look at [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).
