### ISSUE TITLE
sequelize error for mariaDB queries which use WITH statements

### ISSUE THREAD

**Issue by matthias62** [sequelize/sequelize#11198]
Hello

The following RAW query produces an ER_NO_DB_ERROR despite of fully qualified table names. 
The problem just happens if the query contains WITH statements. With a remote mariaDB server instead of a local mysql Server a different error is produced "UNKNOWN_CODE_PLEASE_REPORT" with errno 2003 and sqlMessage: "Lost connection to backend server"

The Raw query should execute without explicit USE database commands. 

Environment: mysql, mariadb

var Sequelize = require('sequelize');

var db = new Sequelize('mariadb://ih-galaxy:ih-galaxy@localhost:3306', {
      logging: false,
      storage: 'dev.sqlite',
      define: {
        timestamps: false,
        freezeTableName: true,
        charset: 'utf8',
        collate: 'utf8_general_ci'
      }
    }
  );

/* test tables
CREATE TABLE basetable (idcol int, valcol int);
INSERT INTO basetable VALUES(1,1);
INSERT INTO basetable VALUES(2,2);
*/  
 
// causes "ER_NO_DB_ERROR" despite of fully qualified table names. Error just happens if the query contains a WITH statement  
let s = "WITH t1 as (SELECT SUM(valcol) AS tval FROM test.basetable GROUP BY idcol) SELECT SUM(tval) AS v FROM t1";
 
db.query(s, {type: db.Sequelize.QueryTypes.SELECT})
  .then(function(res) {
    console.log('success: ' + JSON.stringify(res));
  })
  .catch(function(res) {
    console.log('failed' + JSON.stringify(res));
  });

**Comment by papb** [comment]
Please format your code with markdown js-triple-backticks next time, like this:

````
```js
// Your code here
```
````

Result:

```js
var Sequelize = require('sequelize');

var db = new Sequelize('mariadb://ih-galaxy:ih-galaxy@localhost:3306', {
    logging: false,
    storage: 'dev.sqlite',
    define: {
        timestamps: false,
        freezeTableName: true,
        charset: 'utf8',
        collate: 'utf8_general_ci'
    }
});

/* test tables
CREATE TABLE basetable (idcol int, valcol int);
INSERT INTO basetable VALUES(1,1);
INSERT INTO basetable VALUES(2,2);
*/

// causes "ER_NO_DB_ERROR" despite of fully qualified table names. Error just happens if the query contains a WITH statement
let s = "WITH t1 as (SELECT SUM(valcol) AS tval FROM test.basetable GROUP BY idcol) SELECT SUM(tval) AS v FROM t1";

db.query(s, {type: db.Sequelize.QueryTypes.SELECT})
    .then(function(res) {
        console.log('success: ' + JSON.stringify(res));
    })
    .catch(function(res) {
        console.log('failed' + JSON.stringify(res));
    });
```

**Comment by matthias62** [comment]
Additional comments:

- The above mentioned problems are bound to mariaDB columnstore engine tables. 
- The test statement above is using the WITH sql statement. Together with a columnstore table
that forces the application to apply the USE database statement - even with fully qualified table names. With normal SELECT without the WITH statement that is not necessary.
- The next columnstore related problem happens if one tries to solve the WITH-statement problem by
using the "multipleStatements" property of the "dialectOptions". That does not work reasonably. If the USE statement and the payload statement above are sent as a multi statement sequelize blocks for multiple minutes until the result is produced. In my test environment HeidiSQL needed less then 1s for the statement and sequelize 15 minutes. That problem I could only solve by sending USE and the payload statement individually in serialized manner without using "multipleStatements".

best regards
Matthias

**Comment by papb** [comment]
If I understood correctly, this is a problem with both mysql and mariadb, although the error messages are different? Is this correct?
