### ISSUE TITLE
SSL Certificate issue on documentation page

### ISSUE THREAD

**Issue by jbauerrfid** [sequelize/sequelize#11196]
## SSL Certificate issue on documentation page

The documentation page on https://docs.sequelizejs.com/ returns an invalid SSL certificate

SSL Labs reports "Certificate name mismatch"

See also:
* https://www.ssllabs.com/ssltest/analyze.html?d=docs.sequelizejs.com
* https://www.ssllabs.com/ssltest/analyze.html?d=docs.sequelizejs.com&ignoreMismatch=on&latest

**Comment by papb** [comment]
Thanks for reporting. Hopefully this will be fixed soon.

@sushantdhiman Can you take a look?

**Comment by sushantdhiman** [comment]
New documentation site https://sequelize.org/
