### ISSUE TITLE
Error when adding count attribute after joining table

### ISSUE THREAD

**Issue by passion0470** [sequelize/sequelize#11191]
Hi. I do not know how to do it.
Your framework and ORM use express and sequelize.
On the bulletin board, when I call the list, I want to create an API that adds a property that counts the number of comments.
We try to join the reply (comment) table to the post table, count the number of comments in each post, add the attribute, and return it as json at API call.
However, when I call the API from the front,
Unhandled rejection Error: WHERE parameter "post_id" has invalid "undefined" value
I get this error. I can not find the cause even though I can find the cause for several days.
I do not know how to fix it, but I would appreciate it if you know.

-----------

My mistake is solved.
Fixed with some code modifications and client modifications.

**Comment by papb** [comment]
Hello. Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? In a way that we can easily reproduce your problem. Thanks.

Also, screenshots are better than nothing but next time please provide the code and data as formatted text (with markdown triple-backtick formatting).
