### ISSUE TITLE
Query with Op failed in include query

### ISSUE THREAD

**Issue by dukemai** [sequelize/sequelize#11206]
## What are you doing?

I tried to query joined tables and there is a condition from a field of an included table that smaller then a certain number 

```js
my query looks like this
{
include: [
{ model: A,
  where: { TheField: { [Symbol(lte)]: 0.001 } },
  include:
   [ { model: B, where: {} },
     { model: C, where: {} },
     { model: D, where: {} } ] }

]
}

```
**To Reproduce**

## What do you expect to happen?
it should work as normal

## What is actually happening?
I got an error, "message": "Invalid value {}",

_Output, either JSON or SQL_

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: XXX
Sequelize version: XXX
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [ ] Yes, specify that version:

**Comment by papb** [comment]
Your code is too reduced to reproduce the issue. Please provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example). Thanks!

**Comment by dukemai** [comment]
thanks, I figured it out because I used merge from lodash to merge options to send in query and it seems that merge does not like "op" which uses symbol so maybe merge cannot recognize symbol. sometime it is a little bit trouble to have op in query and we need transform query.

**Comment by papb** [comment]
@dukemai what do you mean? The problem was with lodash?

**Comment by dukemai** [comment]
yes, it was lodash. The problem was that I used merge from lodash to merge several where objects into one and it stripped Op methods
