### ISSUE TITLE
Association with Other Not Null Values

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [sequelize/sequelize#11208]
**Is your feature request related to a problem? Please describe.**
Well i hope i haven't found after my 6 hours research the solution on the internet. The main Problem i got is some 3 Table Join. Lets just take this simple scenario:

Meal, User, Canteen.
each of these got an id which of cause is unique.

I would like to make it possible to get a table: "MealComments". Since in my Scenario it would be great if there could be a primaryKey `(meal,user,canteen)` but I'm already dealing, that this isn't possible.
Well this table MealComments should have an other key "commentText", which is a String. Since comments wihtout content are not usefull a "Not Null" is pretty obvious.

This is my MealComments Model:
`queryInterface.createTable('MealRatings', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      value: {
        type: Sequelize.FLOAT,
        allowNull: false
      },
      mealId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Meals",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      canteenId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Canteens",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      userId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Users",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });`

**Describe the solution you'd like**

Let's assume I got an Instance of Meal(fries), Canteen(burgerKing),User(me)

What would be great would be this:

`let mealComment = new models.MealComment({commentText: "Nice Fries"});
    await mealComment.setUser(me,{save: false});
    await mealComment.setMeal(fries,{safe:false});
    await mealComment.setCanteen(burgerKing,{safe:false});
    await mealComment.save();`

The MealComments model looks like this:

`'use strict';
module.exports = (sequelize, DataTypes) => {
  const MealComment = sequelize.define('MealComment', {
    commentText: DataTypes.STRING
  }, {});
  MealComment.associate = function(models) {
    // associations can be defined here
    MealComment.belongsTo(models.Meal,
            {
              onUpdate: "CASCADE",
              onDelete: 'CASCADE'
            });
            MealComment.belongsTo(models.Canteen,
                        {
                          onUpdate: "CASCADE",
                          onDelete: 'CASCADE'
                        });
                        MealComment.belongsTo(models.User,
                                    {
                                      onUpdate: "CASCADE",
                                      onDelete: 'CASCADE'
                                    });
  };
  return MealComment;
};`

The Problem is, that as soon as I try to assign a User,Meal,Canteen it throws me an error, that 
commentText does not have a value. As User,Meal,Canteen should be additional Not Null, but I'm dealing that this isn't possible also.
I hope either I'm stupid as fuck and couldn't figure this out, or that someone got a nice solution for my pitty problem.
Worst case would be ... if this would be a feature request.

**Why should this be in Sequelize**
It would be very nice, to assign Associations and Values at once.

**Describe alternatives you've considered**
- I thout about using only Integers and managing the whole setting on my own, but that was one of the reasons I started using Sequelize.
- I also tried turning off the NotNull enforcment, but well I need it.
- I thought about abstracting Comment-User to UserComment, with an ID, which then would'nt be a problem at all. but It's pretty ugly having an extra table for that.
- I thought about using other ORM's for Node (TypeOrm, Prisma, ...) but, they don't support much as Sequelize.

**Usage example**
`let mealComment = new models.MealComment({commentText: "Nice Fries"});
    await mealComment.setUser(me,{save: false});
    await mealComment.setMeal(fries,{safe:false});
    await mealComment.setCanteen(burgerKing,{safe:false});
    await mealComment.save();`

**Additional context**
Thanks for reading this

**Comment by papb** [comment]
> The Problem is, that as soon as I try to assign a User,Meal,Canteen it throws me an error, that
commentText does not have a value.

Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce this error? Thanks!

**Comment by NilsBaumgartner1994** [comment]
Sure but tomorrow. It's 2 am and I'm kinda sleepy. But thanks for fast reply

**Comment by NilsBaumgartner1994** [comment]
`const Sequelize = require('sequelize')
const sequelize = new Sequelize({username: 'root', password: '', database: 'test', dialect: 'mysql', logging: false})

var User = sequelize.define('User', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      name: {
         type: Sequelie.String
      }
});

var Meal = sequelize.define('Meal', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      name: {
         type: Sequelie.String
      }
});

var Canteen = sequelize.define('User', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      name: {
         type: Sequelie.String
      }
});

var CanteenMealComment = sequelize.define('CanteenMealComment', {
      text: {
        type: Sequelize.STRING,
        allowNull: false
      },
      mealId: {
        type:Sequelize.INTEGER,
        allowNull: false,
        primaryKey: true,
        references: {
          model: "Meals",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      canteenId: {
        type:Sequelize.INTEGER,
        allowNull: false,
        primaryKey: true,
        references: {
          model: "Canteens",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      userId: {
        type:Sequelize.INTEGER,
        allowNull: false,
        primaryKey: true,
        references: {
          model: "Users",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
});

// Associations
CanteenMealComment.belongsTo(User);
CanteenMealComment.belongsTo(Meal);
CanteenMealComment.belongsTo(Comment);

// At this point you could define the opposite association, but this wont happen here


// Creating Instances
 let fries = Meal.build( {
      name: 'Pommes'
    } );
    await fries.save();

 let me = User.build( {
      name: 'Nils'
    } );
    await me.save();

 let burgerKing = Canteen.build( {
      name: 'BurgerKing'
    } );
    await burgerKing.save();

// Now the real part which makes the problem:

let mealComment = CanteenMealComment.build({text: "Nice fries"}); // not saved in db yet 
    console.log(mealComment); // show me how it would look like
    await mealComment.setUser(me,{save: false}); // here the error happens ... it does not have text in anymore
    await mealComment.setMeal(fries,{safe:false});
    await mealComment.setCanteen(burgerKing,{safe:false});
    console.log(mealComment);
    await mealComment.save(); //

**Comment by NilsBaumgartner1994** [comment]
I'm sorry the code formation doesn't seem to worked

**Comment by NilsBaumgartner1994** [comment]
As I said, I dont want to create new Instances, because I got them already ...

**Comment by papb** [comment]
I've fixed formatting for you. You have to wrap the code in triple backticks, like this:

` ```js `
` CODE_HERE `
` ``` `

**Comment by NilsBaumgartner1994** [comment]
Thank you

**Comment by NilsBaumgartner1994** [comment]
Funny thing here, when i change the order, setUser works, but not the rest

**Comment by papb** [comment]
Your MCVE doesn't run... There are a few typos and other errors. I see `Sequelie`, `CanteenMealComment.belongsTo(Comment);` but `Comment` is not defined anywhere...

Please post a code that you are 100% sure that I will be able to copy-paste and see your problem at once.

**Comment by NilsBaumgartner1994** [comment]
My Migration Create User: (reduced, and removed some other keys)
```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Users', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Users');
  }
};
```

My User Model:
```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
  }, {});
  User.associate = function(models) {
      User.hasMany( // Since we save our foreign key in MealComment we use hasMany here
        models.MealComment,
      );
  };
  return User;
};
```


My Meal Migration:
```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Meals', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      unique_name: {
        type: Sequelize.STRING,
        allowNull: false
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Meals');
  }
};
```

My Meal Model
```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const Meal = sequelize.define('Meal', {
    unique_name: DataTypes.STRING
  }, {});
  Meal.associate = function(models) {
      Meal.hasMany( //since the association is saved in MealComment we use here hasMany
          models.MealComment,
      );
  };
  return Meal;
};
```


My Canteen Migration:
```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Canteens', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Canteens');
  }
};
```

My Canteen Model:
```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const Canteen = sequelize.define('Canteen', {
  }, {});
  Canteen.associate = function(models) {
    // associations can be defined here
      Canteen.hasMany( // also hasMany here, since we dont save the reference in our table
          models.MealComment,
      );
  };
  return Canteen;
};
```

=====================
=====================
My MealComment Migration:
```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('MealComments', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      text: {
        type: Sequelize.STRING,
        allowNull: false
      },
      canteenId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Canteens",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      mealId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Meals",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      userId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Users",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('MealComments');
  }
};
```

My MealComment Model:
```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const MealComment = sequelize.define('MealComment', {
    text: DataTypes.STRING
  }, {});
  MealComment.associate = function(models) {
    // associations are used with belongsTo, because we want to save the reference to the other Table

//MealComment.belongsTo(models.User, { foreignKey: { allowNull: false }, onDelete: 'CASCADE' });
// for allowNull on foreign Keys I only found this, which would work I think

    MealComment.belongsTo(models.User,
        {
          onUpdate: "CASCADE",
          onDelete: 'CASCADE'
        });
     MealComment.belongsTo(models.Canteen,
         {
          onUpdate: "CASCADE",
          onDelete: 'CASCADE'
         });
     MealComment.belongsTo(models.Meal,
        {
          onUpdate: "CASCADE",
          onDelete: 'CASCADE'
        });
  };
  return MealComment;
};
```

====================
====================
Now inside my seeders file, where I just want to create some tests instances and save them:

```
'use strict';
var models = require('./../models');

module.exports = {
  up: async (queryInterface, Sequelize) => {

    let modelSync = await models.sequelize.sync();
    console.log("Okay models should now be synced");

    // Build a User
    let nils = await models.User.build( {
    } );
    await nils.save();

    // Build a Meal
    let pommes = await models.Meal.build( {
      unique_name: 'Pommes'
    } );
    await pommes.save();

   // Build a Canteen
    let mensa = await models.Canteen.build( {
    } );
    await mensa.save();

    // Now the MealComment building
    let mealComment = models.MealComment.build({text: "Tolle Wurst"}); // <-- here I set the Text

    console.log("1");
    console.log(mealComment); //<-- clearly seen on console
    //await mealComment.save();

    console.log("2");
    console.log(mealComment);
    await mealComment.setUser(nils,{save: false}); //<-- funny thing, this works
   // i use {safe:false} to not include it inside the DB yet.

    console.log("3");
    console.log(mealComment);
    //mealComment.CanteenId = mensa.id; //<-- this would work
    await mealComment.setCanteen(mensa,{safe:false}); //<-- this not

    console.log("4");
    console.log(mealComment);
    //mealComment.MealId = pommes.id; //<-- same here as in 3
    await mealComment.setMeal(pommes,{safe:false});

    console.log("Completed Building");
    console.log(mealComment);
    await mealComment.save(); //now please save it in my DB

    let allMealComments = await models.MealComment.findAll();
    console.log("Meal Comment amount should be 1 now: "+pommesComments.length);
    console.log("Meal Comment should contain Text,UserId,MealId,CanteenID : "+pommesComments[0]);


    console.log("All Done");

    return;
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('MealComments', null, {}); // i will just delete this Table, instead of all others, just because user, meal and canteen are not so important at this moment
  }
};

```

**Comment by NilsBaumgartner1994** [comment]
That is now my code, which because of reasons don't work

Funny Thing is: setUser works, but only this, the others dont if i change order.

// Assigning the value on my Own works, but not with the Set Methode
mealComment.mealId = pommes.id;
await mealComment.setMeal(pommes,{safe:false});

**Comment by NilsBaumgartner1994** [comment]
On my console i get this:

Position 1 & 2:
```
MealComment {
  dataValues: { id: null, text: 'Tolle Wurst' },
...
```

Position 3:
as we see setUser worked as expected
```
MealComment {
  dataValues: { id: null, text: 'Tolle Wurst', UserId: 15 },
...
```

Then the program terminated:
```
ERROR: Field 'text' doesn't have a default value
```

**Comment by NilsBaumgartner1994** [comment]
mealComment.canteenId = mensa.id;
mealComment.mealId = pommes.id;

Only works when using both at same time

**Comment by papb** [comment]
Can you test if the same problem happens in another dialect, like SQLite for example?

You can connect to an in-memory sqlite using `new Sequelize('sqlite::memory:`)`. Remember to install the `sqlite3` package manually.

**Comment by papb** [comment]
Also, can you try to create a MCVE that does not use migrations? Try to start from scratch, create a new empty project, install sequelize, etc, try to keep everything in only one file. Makes it easier for me to investigate. Thanks.

**Comment by NilsBaumgartner1994** [comment]
Hello here I am again :-)
I expect that sqlite3,Sequelize,... is installed.
Also included some console logs in case you want to have a look on them.
In console it terminates again on the same place with following message:

```
Executing (default): INSERT INTO `MealComments` (`CanteenId`,`updatedAt`,`createdAt`) VALUES ($1,$2,$3);
```

ERROR: Validation error

Thanks for helping me :-)

```
let sequelize = new Sequelize('sqlite::memory:');

    console.log("Define User");
    const User = sequelize.define('User', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      }
    }, {});

    console.log("Define Meal");
    const Meal = sequelize.define('Meal', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false
      }
    }, {});

    console.log("Define Canteen");
    const Canteen = sequelize.define('Canteen', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      }
    }, {});

    console.log("Define MealComment");
    const MealComment = sequelize.define('MealComment', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      text: {
        type: Sequelize.STRING,
        allowNull: false
      },
      UserId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Users",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      CanteenId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Canteens",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
      MealId: {
        type:Sequelize.INTEGER,
        references: {
          model: "Meals",
          key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
      },
    }, {});





    console.log("User Associate");
    User.hasMany( // Since we save our foreign key in MealComment we use hasMany here
          MealComment,
    );

    console.log("Meal Associate");
    Meal.hasMany( // Since we save our foreign key in MealComment we use hasMany here
          MealComment,
    );

    console.log("Canteen Associate");
    Canteen.hasMany( // Since we save our foreign key in MealComment we use hasMany here
          MealComment,
      );

    console.log("MealComment Associate");
    MealComment.belongsTo(User,
      {
      onUpdate: "CASCADE",
      onDelete: 'CASCADE'
    });
    MealComment.belongsTo(Canteen,
      {
      onUpdate: "CASCADE",
      onDelete: 'CASCADE'
    });
    MealComment.belongsTo(Meal,
      {
      onUpdate: "CASCADE",
      onDelete: 'CASCADE'
    });


    console.log("Syncronize all Tables");

    let modelSync = await sequelize.sync();
    //console.log("Okay models should now be synced");

    // Build a User
    let nils = await User.build( {
    } );
    await nils.save();

    console.log("User Created");
    console.log(nils);

    // Build a Meal
    let pommes = await Meal.build( {
      name: 'Pommes'
    } );
    await pommes.save();

    console.log("Meal Created");
    console.log(pommes);

    // Build a Canteen
    let mensa = await Canteen.build( {
    } );
    await mensa.save();

    console.log("Canteen Created");
    console.log(mensa);

    console.log("Creating now MealComment");
    let mealComment = MealComment.build({text: "Tolle Wurst"}); // <-- here I set the Text

    console.log("1");
    console.log(mealComment); //<-- clearly seen on console
    //await mealComment.save(); // only works when i first save the instance, but i want to make the other foreign keys also allowNull: false

    console.log("2");
    console.log(mealComment);
    await mealComment.setUser(nils,{save: false}); //<-- funny thing, this works
    // i use {safe:false} to not include it inside the DB yet.

    console.log("3");
    console.log(mealComment);
    //mealComment.CanteenId = mensa.id; //<-- this dont work
    await mealComment.setCanteen(mensa,{safe:false}); //<-- this not

    console.log("4");
    console.log(mealComment);
    //mealComment.MealId = pommes.id; //<-- this dont work
    await mealComment.setMeal(pommes,{safe:false});


    console.log("Completed Building");
    console.log(mealComment);
    await mealComment.save(); //now please save it in my DB

    console.log(mealComment);
```

**Comment by papb** [comment]
You had typos: in three places you wrote `{safe:false}` where it should have been `{save:false}`.

Fixing this makes it work, apparently.

**Comment by papb** [comment]
By the way, here are some tips for making your shortened code even much shorter:

* You don't have to explicitly define the `id` fields of models, Sequelize will do that automatically (unless you want to change a default behavior, which you didn't)
* You can join two consecutive `console.log`s by passing multiple arguments
* To make logs more readable, you should convert the model instances to JSON before logging.

Here is your improved code:

```js
const sequelize = new Sequelize('sqlite::memory:');

const User = sequelize.define('User', {});
const Meal = sequelize.define('Meal', {
    name: {
        type: Sequelize.STRING,
        allowNull: false
    }
});
const Canteen = sequelize.define('Canteen', {});
const MealComment = sequelize.define('MealComment', {
    text: {
        type: Sequelize.STRING,
        allowNull: false
    },
    UserId: {
        type:Sequelize.INTEGER,
        references: {
            model: "Users",
            key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
    },
    CanteenId: {
        type:Sequelize.INTEGER,
        references: {
            model: "Canteens",
            key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
    },
    MealId: {
        type:Sequelize.INTEGER,
        references: {
            model: "Meals",
            key: "id",
        },
        onUpdate: "CASCADE",
        onDelete: "CASCADE",
    }
});
User.hasMany(MealComment); // Since we save our foreign key in MealComment we use hasMany here
Meal.hasMany(MealComment); // Since we save our foreign key in MealComment we use hasMany here
Canteen.hasMany(MealComment); // Since we save our foreign key in MealComment we use hasMany here
MealComment.belongsTo(User, { onUpdate: "CASCADE", onDelete: "CASCADE" });
MealComment.belongsTo(Canteen, { onUpdate: "CASCADE", onDelete: "CASCADE" });
MealComment.belongsTo(Meal, { onUpdate: "CASCADE", onDelete: "CASCADE" });

await sequelize.sync();

let nils = await User.build({});
await nils.save();
console.log("User Created:", nils.toJSON());

// Build a Meal
let pommes = await Meal.build({ name: 'Pommes' });
await pommes.save();
console.log("Meal Created:", pommes.toJSON());

// Build a Canteen
let mensa = await Canteen.build({});
await mensa.save();
console.log("Canteen Created:", mensa.toJSON());

console.log("Creating now MealComment");
let mealComment = MealComment.build({ text: "Tolle Wurst" }); // <-- here I set the Text
console.log("1:", mealComment.toJSON()); //<-- clearly seen on console

// await mealComment.save(); // only works when i first save the instance, but i want to make the other foreign keys also allowNull: false
// console.log("2:", mealComment.toJSON());

await mealComment.setUser(nils,{save: false}); //<-- funny thing, this works
// i use {save:false} to not include it inside the DB yet.

console.log("3:", mealComment.toJSON());
//mealComment.CanteenId = mensa.id; //<-- this dont work
await mealComment.setCanteen(mensa,{save:false}); //<-- this not

console.log("4:", mealComment.toJSON());
//mealComment.MealId = pommes.id; //<-- this dont work
await mealComment.setMeal(pommes,{save:false});

console.log("Completed Building:", mealComment.toJSON());
await mealComment.save(); //now please save it in my DB

console.log("5:", mealComment.toJSON());
```
