### ISSUE TITLE
[Security ISSUE: SQL Injection] sequelize 4.44.*

### ISSUE THREAD

**Issue by sahatnicholas-gdp** [sequelize/sequelize#11202]
# What are you doing?
Snyk reports a SQL injection vulnerability in version sequelize@4.44.*.

https://www.npmjs.com/advisories/1018

Would you help offering a solution or explanation to that? Currently, the only remedy is to upgrade sequelize to v5, which breaks a lot of my existing code.
Thanks before.

# Environment

Dialect:
- [x]   mysql
- [ ]   postgres
- [ ]   sqlite
- [ ]   mssql
- [ ]   any

Sequelize version: 4.44.*
Tested with latest release:
- [x]   No
- [ ]   Yes, specify that version:

**Comment by papb** [comment]
Thanks for reporting, PRs are welcome, unfortunately I don't have time to take a look into this right now...

**Comment by sushantdhiman** [comment]
Fixed with https://github.com/sequelize/sequelize/pull/11332
