### ISSUE TITLE
Two Op.in in where clause, only the last Op.in returned on the query

### ISSUE THREAD

**Issue by jeranluna** [sequelize/sequelize#11219]
This is the example of my where clause:

`Company.findAndCountAll({
    offset: offset,
    limit: limit,
    include: [Email, Linkedin, User],
    where: {
      [Op.or]: {
        name: {
          [Op.like]: `%${search}%`
        },
        id: {
          [Op.or]: {
            [Op.in]: Sequelize.literal(`(SELECT companyId FROM linkedins WHERE url LIKE '%${search}%')`),
            [Op.in]: Sequelize.literal(`(SELECT companyId FROM emails WHERE email LIKE '%${search}%')`)
          }
        }
      }
    },
    order: [['create_datetime', 'desc'], ['id', 'desc']],
    distinct: true
  })`

Result:

`SELECT `Company`.*, `Emails`.`id` AS `Emails.id`, `Emails`.`companyId` AS `Emails.companyId`, `Emails`.`email` AS `Emails.email`, `Emails`.`create_datetime` AS `Emails.create_datetime`, `Emails`.`userId` AS `Emails.userId`, `Emails`.`status` AS `Emails.status`, `Linkedins`.`id` AS `Linkedins.id`, `Linkedins`.`companyId` AS `Linkedins.companyId`, `Linkedins`.`name` AS `Linkedins.name`, `Linkedins`.`url` AS `Linkedins.url`, `Linkedins`.`create_datetime` AS `Linkedins.create_datetime`, `Linkedins`.`userId` AS `Linkedins.userId`, `Linkedins`.`status` AS `Linkedins.status`, `User`.`id` AS `User.id`, `User`.`first_name` AS `User.first_name`, `User`.`last_name` AS `User.last_name`, `User`.`email` AS `User.email`, `User`.`create_datetime` AS `User.create_datetime`, `User`.`userId` AS `User.userId`, `User`.`status` AS `User.status` FROM (SELECT `Company`.`id`, `Company`.`name`, `Company`.`url`, `Company`.`create_datetime`, `Company`.`userId`, `Company`.`status` FROM `Companies` AS `Company` WHERE (`Company`.`name` LIKE '%test%' OR (`Company`.`id` IN (SELECT companyId FROM emails WHERE email LIKE '%test%'))) ORDER BY `Company`.`create_datetime` DESC, `Company`.`id` DESC LIMIT 10, 10) AS `Company` LEFT OUTER JOIN `Emails` AS `Emails` ON `Company`.`id` = `Emails`.`companyId` LEFT OUTER JOIN `Linkedins` AS 
`Linkedins` ON `Company`.`id` = `Linkedins`.`companyId` LEFT OUTER JOIN `Users` AS `User` ON `Company`.`userId` = `User`.`id` ORDER BY `Company`.`create_datetime` DESC, `Company`.`id` DESC;`

The company.id IN (SELECT companyId FROM linkedins WHERE url LIKE '%test%') is removed on the Sequelize console log:

`WHERE (`Company`.`name` LIKE '%test%' OR (`Company`.`id` IN (SELECT companyId FROM emails WHERE email LIKE '%test%')))`

**Comment by papb** [comment]
Please provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by jeranluna** [comment]
Hi Perdro,

This is part of the where clause I am using which has two IN operator.

`id: { [Op.or]: { [Op.in]: Sequelize.literal((SELECT companyId FROM linkedins WHERE url LIKE '%${search}%')), [Op.in]: Sequelize.literal((SELECT companyId FROM emails WHERE email LIKE '%${search}%')) } } } },`

But only the last of the IN operator is getting returned on the Sequelize logging.

`(Company.id IN (SELECT companyId FROM emails WHERE email LIKE '%test%')))`

**Comment by papb** [comment]
Can you post a code that I can copy-paste and execute immediately (without further preparation, except for installing sequelize itself)?

**Comment by jeranluna** [comment]
> Can you post a code that I can copy-paste and execute immediately (without further preparation, except for installing sequelize itself)?

Here is the sample code on my controller.

exports.search = (req, res) => {
const search = req.body.search;
Company.findAndCountAll({
    offset: offset,
    limit: limit,
    include: ['Email', 'Linkedin', 'User'],
    where: {
      [Op.or]: {
        name: {
          [Op.like]: `%${search}%`
        },
        id: {
          [Op.or]: {
            [Op.in]: Sequelize.literal(`(SELECT companyId FROM linkedins WHERE url LIKE '%${search}%')`),
            [Op.in]: Sequelize.literal(`(SELECT companyId FROM emails WHERE email LIKE '%${search}%')`)
          }
        }
      }
    },
    order: [['create_datetime', 'desc'], ['id', 'desc']],
    distinct: true
  }).then(companies => {
    res.json('done');
  });
};

[20190703223002-create_users_table.txt](https://github.com/sequelize/sequelize/files/3429469/20190703223002-create_users_table.txt)
[20190703223027-create_companies_table.txt](https://github.com/sequelize/sequelize/files/3429470/20190703223027-create_companies_table.txt)
[20190703225201-create_emails_table.txt](https://github.com/sequelize/sequelize/files/3429471/20190703225201-create_emails_table.txt)
[20190704053010-create_linkedins_table.txt](https://github.com/sequelize/sequelize/files/3429472/20190704053010-create_linkedins_table.txt)
[Company.txt](https://github.com/sequelize/sequelize/files/3429475/Company.txt)
[Email.txt](https://github.com/sequelize/sequelize/files/3429476/Email.txt)
[Linkedin.txt](https://github.com/sequelize/sequelize/files/3429477/Linkedin.txt)
[User.txt](https://github.com/sequelize/sequelize/files/3429478/User.txt)

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by jeranluna** [comment]
Pablo thanks for responding but I manage to resolved the issue by modifying the code.

Before:
`id: {
  [Op.or]: {
    [Op.in]: Sequelize.literal((SELECT companyId FROM linkedins WHERE url LIKE '%${search}%')),
    [Op.in]: Sequelize.literal((SELECT companyId FROM emails WHERE email LIKE '%${search}%'))
  }
}`

Now:
`id: {
  [Op.or]: [{
    [Op.in]: Sequelize.literal(`(SELECT companyId FROM emails WHERE email LIKE '%${search}%')`)
  }, {
   [Op.in]: Sequelize.literal(`(SELECT companyId FROM linkedins WHERE url LIKE '%${search}%')`)
  }]
}`
