### ISSUE TITLE
npm i sequelize-sqlite fails

### ISSUE THREAD

**Issue by jaenelleisidro** [sequelize/sequelize#11213]
hi, i'm new to this node and npm but it seems like this keeps failing because amazon server is down? any suggestion how to fix this? thank you

> [sqlite3]: http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v46-linux-x64.tar.gz not found, falling back to source compile (Error: Server returned 403)

the full log below
> vagrant@vagrant-ubuntu-trusty-64:~/UAPI$ npm i sequelize-sqlite
npm WARN package.json UAPI@1.3.0 No repository field.
npm WARN package.json UAPI@1.3.0 No README data
npm WARN package.json UAPI@1.3.0 No license field.
npm WARN deprecated sequelize@1.7.11: security issues fixed in v3.32.0
npm WARN engine sqlite3@2.1.19: wanted: {"node":">= 0.6.13 < 0.11.0"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN deprecated lingo@0.0.5: This project is abandoned
npm WARN deprecated circular-json@0.1.6: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tar.gz@0.1.1: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN installMany mkdirp was bundled with sqlite3@2.1.19, but bundled package wasn't found in unpacked tree
npm WARN installMany tar.gz was bundled with sqlite3@2.1.19, but bundled package wasn't found in unpacked tree
npm WARN installMany progress was bundled with sqlite3@2.1.19, but bundled package wasn't found in unpacked tree
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
sqlite3@2.1.19 install /home/vagrant/UAPI/node_modules/sequelize-sqlite/node_modules/sqlite3
node build.js
[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v46-linux-x64.tar.gz
[sqlite3]: http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v46-linux-x64.tar.gz not found, falling back to source compile (Error: Server returned 403)
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: sequelize-sqlite not found (cwd: /home/vagrant/UAPI/node_modules/sequelize-sqlite/node_modules/sqlite3) while trying to load sequelize-sqlite
gyp ERR! configure error 
gyp ERR! stack Error: 'gyp' failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 3.13.0-170-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "sequelize-sqlite"
gyp ERR! cwd /home/vagrant/UAPI/node_modules/sequelize-sqlite/node_modules/sqlite3
gyp ERR! node -v v4.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
[sqlite3]: Error: Failed to execute 'node-gyp rebuild sequelize-sqlite' (1)
npm ERR! Linux 3.13.0-170-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "sequelize-sqlite"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! sqlite3@2.1.19 install: 'node build.js'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@2.1.19 install script 'node build.js'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/UAPI/npm-debug.log

**Comment by papb** [comment]
You are installing the incorrect package. Please pay attention to what you're typing along `npm i` so you don't install unintended packages.

Follow the [official getting-started guide](https://sequelize.org/master/manual/getting-started.html).
