### ISSUE TITLE
add ability for flow typing in seeds/migrations

### ISSUE THREAD

**Issue by jpirzent** [sequelize/sequelize#11224]
**Is your feature request related to a problem? Please describe.**
Yes. Using either the seeds or migrations template, I can't `flow-type` the QueryInterface or Sequelize parameters.
For example:
`[...]` 
`up: (queryInterface: QueryInterface, Sequelize: SequelizeType) => {` 
`[...]` 
gives an error:
`ERROR: Unexpected token :`

**Describe the solution you'd like**
I would like to be able to do something as described in the example above.

**Why should this be in Sequelize**
Flow is gaining a lot of traction. In issue #6957, it was said that types wouldn't be added, however, I think it would be a good idea to be able to type the variables.

**Comment by sushantdhiman** [comment]
Sorry, currently there are no plans to introduce flow types.
