### ISSUE TITLE
Several bugs/questions regarding underscored/underscoredAll in Sequelize v5

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11225]
Several issues related to the use of `underscore` (and the now inexistent `underscored_all`) have been opened recently:

#10565
#10754
#10857
#10971
#10977
#11037
#11047
#11062
#11112
#11149
#11154
#11162
#11306
#11417
#11423
#11574

I am creating this issue to track them all in a single place.

<s>I haven't looked deeply into it yet, but I believe some of them are caused mostly by a misunderstanding of how to upgrade from v4 to v5 (most likely the first thing I will do is expand on the documentation on how to do it correctly, I agree that the docs didn't go too deep into this).</s>

I'm convinced this is not just a docs issue; this is something that should change / be improved.

Stay tuned!

**Comment by frastlin** [comment]
Well, the documentation is rather clear on how to use the underscored functionality, and if there is another way to use it, I would love to know.
I'm making a couple hooks today for my server to simulate the underscored functionality until this gets resolved.
I don't mind how the tables look in the database, when I use this, I want foreignId to be foreign_id when I add and query items in the database.

**Comment by seanmrichards** [comment]
Unless this is the expected new behavior, https://github.com/sequelize/sequelize/issues/10857 explains the issue with foreign keys being converted into camelCase (when setting underscored:true) the most clearly.  To workaround in the mean time explicitly define the foreign key option in belongsTo which causes the model to return the key as both camelCase and underscored properties on the object.

**Comment by Ancinek** [comment]
@frastlin Would you like to share those hooks? I would greatly appreciate it! :tada:

**Comment by frastlin** [comment]
My solution is pretty unique to FeathersJS, the framework I'm using.
I have a before hook and an after hook. The before hook checks on a create method, if any of the keys in the objects end with "_id". If they do, they are added to a list. Then that list is checked if the key.slice(0, key.length-3) is in the list of hooks that I have manually created. If it is, then the hook is run through a camelize function.
The after hook also has a list of keys that may have the Id after them. So on find and get functions, I filter all the keys by the ones that end with "Id", then check if the key without "Id" is in the list of keys that I provided. Then I run an underscore function on the resulting keys.
It's not the best method and I really can't wait until this bug is fixed!

**Comment by Ancinek** [comment]
@frastlin Thanks a lot for the input. The bug is indeed frustrating. Cost me spending at least 2 hours of looking what I do wrong that it does not work.

**Comment by matiasmenker** [comment]
Some update about the issues? Some one that solve this problem?

**Comment by matiasmenker** [comment]
> Well, the documentation is rather clear on how to use the underscored functionality, and if there is another way to use it, I would love to know.
> I'm making a couple hooks today for my server to simulate the underscored functionality until this gets resolved.
> I don't mind how the tables look in the database, when I use this, I want foreignId to be foreign_id when I interact with items in the database.

Can you please share?

**Comment by papb** [comment]
Hello, just passing by to say that I did not forget about this. Finding time is not easy... Thanks everyone for the patience so far :+1:

**Comment by yoshiya0503** [comment]
[My Workaround Plan]

[1] first of all
```

**Comment by yoshiya0503** [comment]
[My workaround plan]

**Comment by serge1peshcoff** [comment]
For those stumbled upon this issue, here's how I've fixed it:
1) converted timestamps to lowercase manually, like this:

```js
const Model = sequelize.define('application', {
    // some fields
}, {
    underscored: true,
    createdAt: 'created_at', // <====== this line and the following one
    updatedAt: 'updated_at',
}
```

2) converted all the foreign keys to lowercase like this:

```js
// Declaring 2 models, Parent and Child, Child model has the reference to Parent model
// via 'parent_id' foreign key.

Parent.hasMany(Child, { foreignKey: 'parent_id' }); // note the 'foreign_key' parameter
Child.belongsTo(Parent, { foreignKey: 'parent_id' }); // and here as well
```

**Comment by papb** [comment]
By the way sorry guys I am taking long to look at this. Haven't had much time, thanks for the patience, stay tuned! Also rest assured that I will not consider this 'done' until every "sub-issue" listed in the first post is properly addressed.

**Comment by aaronovz1** [comment]
Any update on this? I can't upgrade to V5 until this is resolved. Cheers.

**Comment by papb** [comment]
Hi @aaronovz1 and everyone else, there is no update on this yet, thanks everyone for the patience so far!

**Comment by papb** [comment]
#3722 is probably related too...

**Comment by stop-error-code** [comment]
Hi people, we know that are very busy at the time.. anyway, are there any update about this issue?

**Comment by 1valdis** [comment]
Wow, seems like I shouldn't have upgraded to Sequelize 5 if there are issues like this.

**Comment by vviotto** [comment]
An issue like this should be priority number one, I'm sure a lot of people are used to using underscore for column and table names in a database.
It has been almost an year since this issue was opened, I'know its an open source project and that its hard for maintainers to find the time, but we at least need an update of the progress on this and a rough ETA.

I greatly appreciate the work you guys have done with sequelize, its a wonderful library, but please gives us more than "no updates on this", its an important feature that is broken for a long time now.

**Comment by frastlin** [comment]
I just stopped using Sequelize, as this is kind of a breaking feature for me.

**Comment by kdex** [comment]
@frastlin In favor of what, if I may ask? I'm interested to explore alternatives as well.

**Comment by frastlin** [comment]
I've been using no SQL. For SQL though, there is [knex](http://knexjs.org/)

**Comment by euqen** [comment]
Does anyone has update about this issue?

**Comment by papb** [comment]
> An issue like this should be priority number one, I'm sure a lot of people are used to using underscore for column and table names in a database.
> It has been almost an year since this issue was opened, I'know its an open source project and that its hard for maintainers to find the time, but we at least need an update of the progress on this and a rough ETA.
> 
> I greatly appreciate the work you guys have done with sequelize, its a wonderful library, but please gives us more than "no updates on this", its an important feature that has been broken for a long time now.

Thanks for understanding :) The problem is, if I promise a solution for next week for example, and end up being unable to do it, I would feel worse than if I just didn't promise anything. I'm sorry!

However, I agree this issue has been open for way too long... I will try to put an extra effort, maybe sleep less hours to make this happen... But I cannot guarantee it, as I said. Sorry I can't do better for now.

**Comment by Leeiio** [comment]
@serge1peshcoff You save my life !

> For those stumbled upon this issue, here's how I've fixed it:
> 
> 1. converted timestamps to lowercase manually, like this:
> 
> ```js
> const Model = sequelize.define('application', {
>     // some fields
> }, {
>     underscored: true,
>     createdAt: 'created_at', // <====== this line and the following one
>     updatedAt: 'updated_at',
> }
> ```
> 
> 1. converted all the foreign keys to lowercase like this:
> 
> ```js
> // Declaring 2 models, Parent and Child, Child model has the reference to Parent model
> // via 'parent_id' foreign key.
> 
> Parent.hasMany(Child, { foreignKey: 'parent_id' }); // note the 'foreign_key' parameter
> Child.belongsTo(Parent, { foreignKey: 'parent_id' }); // and here as well
> ```

**Comment by sushantdhiman** [comment]
IMO these issues are stemmed from lack of documentation for changes in underscored system in v5. This [comment](https://github.com/sequelize/sequelize/issues/6423#issuecomment-379472035) explains how this new approach works.

I understand some dev just want to use snake case for everything, there is a solution for that (in comment linked) but a bit more verbose than v4/v3.

**Comment by joshparolin** [comment]
Just a note that you still have to assign a "foreignKey" value and explicitly name your underscored value as of v6.3.3. Otherwise, `findAll` will return both your underscored version and a camel case version.

**Comment by sfratini** [comment]
In addition to what @joshparolin is saying, that is still not working on some cases. I have all my foreign keys specified as snake_case and when i try to run a setXXX with a many-to-many relationship it fails but only when I am trying to add new records to the join table. Not if I try to delete. 

Eg. if the community has features [1, 2, 3] and I run setFeatures([1,2]) it works. But if the community has [1, 2, 3] and I run setFeatures([3, 4, 5]) it breaks. 

But the error that I get is this:
```

{
                    "message": "CommunityFeature.idDdFeature cannot be null",
                    "type": "notNull Violation",
                    "path": "idDdFeature",
                    "value": null,
                    "origin": "CORE",
                    "instance": {
                      "idCommunity": null,
                      "idDdFeature": null,
                      "id_community": 1,
                      "id_dd_feature": 2
                    },
                    "validatorKey": "is_null",
                    "validatorName": null,
                    "validatorArgs": []
                  }
                ]
```

As you can see, the instance has both camelCase and snake_case but in this case only one of them has the right values so the entire query is failing.  

My goal is to use snake_case on the DB but camelCase on my GraphQL API. 

My solution was to actually point my join table model foreignKeys to the camelCase that I defined on the model. While I can see why this works, these are some manual steps I don't think I should be doing when all the information for the fields is available:

```
Community.belongsToMany(DdFeature, {
        as: 'features',
        through: CommunityFeature,
        foreignKey: 'idCommunity', //This is the field I define in the model
        otherKey: 'idDdFeature', ///This is the field I define in the model
        onDelete: 'RESTRICT',
        onUpdate: 'CASCADE'
    });
```

**Comment by jony89** [comment]
since it's been over than a year with this issue, def should be added in the documentation as a known issue under the "Upgrade to V6" section.

**Comment by TheOptimisticFactory** [comment]
Don't mind me, I am just un-staling this issue

**Comment by yisibl** [comment]
Hi everyone, any progress here?

**Comment by ephys** [comment]
That depends on what your issue is, since this issue regroups a bunch of them.

I'm actually going to close this issue as we have no idea which bug has been fixed and which bug remains.

If you're still experiencing an issue, please either comment in the relevant closed issue (listed in the first post of this thread) that you're still experiencing that issue and it should be re-opened, or open a new bug report.

**Comment by yevhen309** [comment]
What a surprise for people who need to update some old projects with the newer version of sequelize... What if you have zillions of models and _ is used everywhere in the codebase (and it's not typescript). Do you have to search and fix it manually? This option is required for backwards compatibility.

**Comment by mysuf** [comment]
Not only the old projects. I use snake case in my javascript codebase on purpose to distinguish ORM object's names from rest of the code. Then it is obvious that those data came from database and it is in line with the reality, so I don't have to change the variable names for any raw query replacements. Current state doesn't break anything, it just bloats the query with unnecessary aliases so it is true pain to read it while debugging. Such a simple fix which doesn't brake anything and yet ignored.
