### ISSUE TITLE
Sequelize.DATE, defaultValue: null not working

### ISSUE THREAD

**Issue by SamVerschueren** [sequelize/sequelize#1122]
Hi everyone

So in my MySQL database, I have a date field that can be NULL. Now with sequelizejs, it doesn't seem possible to set the default value of a date field to NULL. It will always set it to an empty string which is not the behaviour I want. Because then the date in the database is 0000-00-00.

Am I missing something here or is this a minor bug? Looked a little bit in the code but could not find something.

Thanks in advance!

**Comment by einicher** [comment]
Does not work, inserts 0000-00-00 00:00:00 into the database by default, on select returns a Date object saying "Invalid date". If you need this behavior you have to explicitly set the date to null on create.

**Comment by sushantdhiman** [comment]
Seems to work fine for me

``` js
const User = sequelize.define('user', {
  name: {
    type: Sequelize.STRING,
    defaultValue: null
  },
  date: {
    type: Sequelize.DATE,
    defaultValue: null
  }
}, {
  timestamps: false
});

sequelize.sync({ force: true, logging: console.log }).then(() => {
  return User.create({

  }, {
    logging: console.log
  });
}).then(user => {
  console.log(user.toJSON());
});
```

This creates the following SQL:

``` sql
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) DEFAULT NULL, `date` DATETIME DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
Executing (default): INSERT INTO `users` (`id`,`name`,`date`) VALUES (DEFAULT,?,?);


{ name: null, date: null, id: 1 }
```

Could you provide some code to reproduce your problem :) ?

**Comment by jiovanniro** [comment]
@SamVerschueren  so I'm running into this error too except I want the user to be able to send an empty string. Do you know or why Sequelize cant handle this out of the box when you set the defaultValue?
