### ISSUE TITLE
Include defined by model does not support sorting

### ISSUE THREAD

**Issue by leowutao** [sequelize/sequelize#11222]
Include defined by model does not support sorting.

I want to add the order parameter to the model in include.

Example Code:

```js
User.associate = function(){
   app.model.User.hasMany(app.model.UserLog, {
       foreignKey:'userId',sourceKey:'id', as: 'userLogs'
   });
}
```

```js
this.ctx.model.User.findByPk(id,{
   include: {
       model: this.ctx.model.UserLog.
       as: 'userLogs',
       order: [['updatedAt','Desc']]
   }
});
```

I need to sort 'UserLog' by 'updatedAt' settings.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
