### ISSUE TITLE
Op.like not working but executing wrong sql with LIKE '[object Object]%'

### ISSUE THREAD

**Issue by nfwyst** [sequelize/sequelize#11221]
# model

```javascript
db.define('port', {
  id: {
    type: INTEGER(11).UNSIGNED,
    primaryKey: true,
    autoIncrement: true,
    allowNull: false,
  },
  name: {
    type: STRING(100),
    allowNull: false,
  },
  nameEn: {
    type: STRING(100),
    defaultValue: null,
  },
  code: {
    type: STRING(5),
    defaultValue: null,
  },
  countryId: {
    type: INTEGER(11).UNSIGNED,
    defaultValue: null,
  },
  routeId: {
    type: INTEGER(11).UNSIGNED,
    allowNull: false,
  },
})

db.define('country', {
  id: {
    type: INTEGER(11).UNSIGNED,
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
  },
  name: {
    type: STRING(30),
    allowNull: false,
  },
  nameEn: {
    type: STRING(100),
    allowNull: false,
  },
})

db.define('route', {
  id: {
    type: INTEGER(11).UNSIGNED,
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
  },
  name: {
    type: STRING(255),
    allowNull: false,
  },
  nameEn: {
    type: STRING(255),
    defaultValue: null,
  },
  code: {
    type: STRING(10),
    allowNull: false,
    unique: true,
  },
})
```

# association

```javascript
portModel.belongsTo(countryModel, { as: 'country', foreignKey: 'countryId' })
countryModel.hasMany(portModel, { as: 'ports', foreignKey: 'countryId' })

portModel.belongsTo(routeModel, { as: 'route', foreignKey: 'routeId' })
routeModel.hasMany(portModel, { as: 'ports', foreignKey: 'routeId' })
```

## raw query

`const ports = await db.query(```SELECT id, name, name_en AS nameEn, code, country_id AS countryId, route_id AS routeId, create_time AS createTime, update_time AS updateTime FROM port AS port WHERE port.name LIKE '%${req.query.name}%'```)
`

## model query

```javascript
const ports = await portModel.findAll({
          where: {
            name: {
              [require('sequelize').Op.like]: `%{req.query.name}%`
            }
          }
        })
```

the executing sql will be 

**Executing (default): SELECT `id`, `name`, `name_en` AS `nameEn`, `code`, `country_id` AS `countryId`, `route_id` AS `routeId`, `create_time` AS `createTime`, `update_time` AS `updateTime` FROM `port` AS `port` WHERE `port`.`name` LIKE '[object Object]${req.query.name.slice(1)}%';**

Whether raw query or find when name is alphabet  like s, d...

# To Reproduce

1. Define models port, country, port
2. db.query(`SELECT id, name, name_en AS nameEn, code, country_id AS countryId, route_id AS routeId, create_time AS createTime, update_time AS updateTime FROM port AS port WHERE port.name LIKE '%${s}%'`)
3. see error 

Executing (default): SELECT `id`, `name`, `name_en` AS `nameEn`, `code`, `country_id` AS `countryId`, 
`route_id` AS `routeId`, `create_time` AS `createTime`, `update_time` AS `updateTime` FROM `port` AS 
`port` WHERE `port`.`name` LIKE '[object Object]s%';

## Environment
Dialect:
- [x] mysql
Database version:  8.0.12
Sequelize version:  5.10.2
Node Version: 11.14.0
OS: macos mojave 10.14.5
Tested with latest release:
- [x] Yes, specify that version:  5.10.2

**Comment by sushantdhiman** [comment]
You forgot `$` in `%{req.query.name}%`. It should be `%${req.query.name}%`

**Comment by nfwyst** [comment]
I am sorry that it was just an editorial error.

**Comment by nfwyst** [comment]
I really met a big pit....
