### ISSUE TITLE
ER_TABLE_EXISTS_ERROR

### ISSUE THREAD

**Issue by chiraggmodi** [sequelize/sequelize#11228]
i am geting Table already exists error on altering table.
attached is the screenshot and here is my Associations

```
LifeArea.belongsTo(User, { constraints: true});
// LifeArea.belongsToMany(User, { through: lineLifeArea, as: 'lineLifeArea', foreignKey: 'lifeArea_id' });

PurposeList.belongsToMany(User, { through: PurposeUser });
PurposeUser.belongsTo(PurposeList, { constraints: true, onDelete: 'CASCADE'});
PurposeList.hasMany(PurposeUser);

PassionsList.belongsToMany(User, { through: PassionsUser });
PassionsUser.belongsTo(PassionsList, { constraints: true, onDelete: 'CASCADE'});
PassionsList.hasMany(PassionsUser);

flowValue.belongsToMany(User, {through: user_flowValue});
user_flowValue.belongsTo(flowValue, {constraints: true, onDelete: 'CASCADE'});
flowValue.hasMany(user_flowValue);

topValue.belongsToMany(User, {through: user_topValue});
user_topValue.belongsTo(topValue, {constraints: true, onDelete: 'CASCADE'});
topValue.hasMany(user_topValue);

User.hasMany(LifeArea);
User.hasMany(user_flowValue);
User.hasMany(user_topValue);
User.hasMany(lineLifeArea);
User.hasMany(linePurpose);
User.hasMany(linePassion);
User.hasMany(PurposeUser);
User.hasMany(lineFlowvalue);
User.hasMany(lineTopvalue);
```

![Screenshot_2](https://user-images.githubusercontent.com/10358945/61945493-c88eeb00-afbd-11e9-954e-5ac242455a25.png)

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by chiraggmodi** [comment]
sorry, before is was not clear here is full markup of my code

here is model

**User Top Value**
```
const Sequelize = require('sequelize');
const sequelize = require('../database/database');

const userTopValue = sequelize.define('user_top-value', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
    allowNull: false
  },
  weighting: {
    type: Sequelize.STRING,
    allowNull: false
  },
  color: {
    type: Sequelize.STRING,
    allowNull: false
  },
  menuOrder: {
    type: Sequelize.INTEGER,
    allowNull: true
  }
})

module.exports = userTopValue;
```
**Top Value modle**
```
const Sequelize = require('sequelize');
const sequelize = require('../database/database');

const topValue = sequelize.define('topValue', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
    allowNull: false
  },
  title: {
    type: Sequelize.STRING,
    allowNull: false
  },
  color: {
    type: Sequelize.STRING,
    allowNull: false
  },
  weighting: {
    type: Sequelize.STRING,
    allowNull: false
  },
  iconsUrl: {
    type: Sequelize.STRING,
    allowNull: false
  }
})

module.exports = topValue;
```
Associations
```
topValue.belongsToMany(User, {through: user_topValue});
user_topValue.belongsTo(topValue, {constraints: true, onDelete: 'CASCADE'});
topValue.hasMany(user_topValue);
User.hasMany(user_topValue);
```
I am using sequelize  **5.8.6** with **mysql**
attached is the screesnhot of error.
![Screenshot_2](https://user-images.githubusercontent.com/10358945/61993484-f3df0c00-b089-11e9-90e4-81a1549fe5cf.png)

**Comment by papb** [comment]
From the looks of your error, it seems that you are using `sequelize.sync({ alter: true }). Your code is still not a SSCCE/MCVE. Make sure we can copy paste and reproduce the problem - try it yourself first - create a new npm project, install sequelize, etc, see the error, and then post the full SSCCE.
