### ISSUE TITLE
Query 10000000 data JavaScript heap out of memory

### ISSUE THREAD

**Issue by acodercat** [sequelize/sequelize#11227]
**Is your feature request related to a problem? Please describe.**
Query 10000000 data JavaScript heap out of memory

**Describe the solution you'd like**
Query 10000000 data JavaScript heap out of memory

**Usage example**
await this.ctx.model.GridDynamicFeature.findAll();

**Comment by sushantdhiman** [comment]
Yes that is possible if you have records with large data. It can happen without Sequelize. If you have something concrete which can be tested properly, you can add that to issue description. 


------------------------------


Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
