### ISSUE TITLE
What if both association directions could be defined at once?

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11237]
Very often, when I define associations in Sequelize, I define them in all possible directions:

## 1:1

```js
A.hasOne(B);
B.belongsTo(A);
```

## 1:N

```js
A.hasMany(B);
B.belongsTo(A);
```

## M:N

```js
A.belongsToMany(B, { through: C });
B.belongsToMany(A, { through: C });
```

## M:N supercharged

Often I do what I call a "supercharged" many-to-many association:

```js
A.belongsToMany(B, { through: C });
B.belongsToMany(A, { through: C });
A.hasMany(C);
B.hasMany(C);
C.belongsTo(A);
C.belongsTo(B);
```

## Feature

I think Sequelize should be able to do that automatically. Something like:

```js
Sequelize.oneToOne(A, B);
Sequelize.oneToMany(A, B);
Sequelize.manyToMany(A, B, C);
```

## Discussion

Is there a major flaw in this that I'm missing? What do you guys think? Is there a reason to prefer just one side of the association? Perhaps a performance reason?

(Especially: @sushantdhiman @SimonSchick @eseliger @felixfbecker @javiertury @overlookmotel and such)

**Comment by SimonSchick** [comment]
This is actually somewhat sensible.
Associations in general could use an overhaul.
Tiny bit OT: It would be nice if we could, rather than generating aliases ala. `(get\set\add)Association`, create a `.associations.association` object which would contain all the methods, this way we could reduce the usage of mixins.

**Comment by PAStheLoD** [comment]
Hello,

I was trying to get a clarification from the documentation on why there are seemingly two ways to create foreign keys, but did not find any. I found this ticket as the closest to a tracking issue regarding associations.

So, Column Options on the Model Basics page mentions the ability to set up a key as a foreign key, set up which model it references, and what is the "primary key" in that model. This seems almost complete, basically only a "cardinality" type property is missing. (One-to-One, or One-to-Many, plus a "through" option for Many-to-Many)

However the Associations page is very-very long, and I'm still confused after spending quite some time reading it. Somehow writing SQL seems simpler, but alas that does not give rise to the rich connected JS model objects.

Could someone provide a quick answer on what the sequelize.define foreign key setup means, and how it differs from using the associations, and maybe/importantly when to use which? Thanks!

**Comment by ephys** [comment]
This was implemented in https://github.com/sequelize/sequelize/pull/14280
