### ISSUE TITLE
Null is not supported as LogicType in TypeScript

### ISSUE THREAD

**Issue by GalenWong** [sequelize/sequelize#11241]
## What are you doing?

The following expression is allowed in JavaScript, but not TypeScript.
```js
Sequelize.where(Sequelize.col('someColumn', '=', null))
```

**To Reproduce**
1. Compile the above expression in TypeScript 
2. The compiler gives "Argument of type 'null' is not assignable to parameter of type 'LogicType'."

## What do you expect to happen?
__TL;DR__: `null` should be allowed in TypeScript if it is allowed in JavaScript. 

I am relatively new to this library. I was trying to perform an LEFT OUTER JOIN and get rows with some column equaling to null. The use case scenario can be found in this issue comment: https://github.com/sequelize/sequelize/issues/1385#issuecomment-157387208

I adapted the solution from that comment to TypeScript but the compiler is not happy about it. 
If the behavior is allowed in JavaScript, it should be available in TypeScript. 
But I don't know if passing `null` to `Sequelize.where` should even be allowed in the first place. Therefore, I opened up this issue.

## What is actually happening?
The compiler gives "Argument of type 'null' is not assignable to parameter of type 'LogicType'."

## Environment
Dialect:
-  postgres

Dialect **library** version:
- "pg": "^7.12.0",
- "pg-hstore": "^2.3.3",
Database version: 11.4
Sequelize version: 5.11.0
Node Version: 12.3.1
OS: macOS 10.14.5
If TypeScript related: TypeScript version: 3.5.3
Tested with latest release: No

**Comment by GalenWong** [comment]
My temporary workaround is to use `// @ts-ignore`. But I would like to confirm if this behavior is appropriate at all. 

Thank you for this amazing repo. 😃

**Comment by papb** [comment]
@GalenWong Thanks for the compliments and for the detailed issue.

> `Sequelize.where(Sequelize.col('someColumn', '=', null)`

I am assuming you forgot a `)`, right?

Hopefully someone will be able to take a look on this soon (I can't right now, sorry)

**Comment by GalenWong** [comment]
@papb Yes, thank you and fixed!

**Comment by 2kindsofcs** [comment]
I agree with that "If the behavior is allowed in JavaScript, it should be available in TypeScriptt." as GalenWong said.

I think I could fix this. Can I take this one? @papb

**Comment by papb** [comment]
Hi @2kindsofcs, sorry to take so long to reply, are you still interested in helping here? If yes, please do!

**Comment by 2kindsofcs** [comment]
Hi @papb , I just read checked your comment as I was on my holidays. Would you assign this issue to me? I'm still interested.

**Comment by papb** [comment]
Hi @2kindsofcs, in fact we already have a PR for this: #11843

**Comment by aniketbiprojit** [comment]
Is this done? I am still getting an error.

**Comment by svallory** [comment]
@aniketbiprojit it got into v6 I'm preparing a PR to patch v5
