### ISSUE TITLE
SELECT * FROM my_table WHERE slot&16

### ISSUE THREAD

**Issue by o7z** [sequelize/sequelize#11242]
My table like this:
```sql
CREATE TABLE `my_table` (
  `id` int(11) NOT NULL,
  `slot` int(11) NOT NULL,
  `name` char(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO my_table VALUES 
(1,127,'a'),
(2,96,'b'),
(3,63,'c'),
(4,44,'c');
```
---
I want query by `slot` like this : 
```sql
SELECT * FROM my_table WHERE slot&16
```
---
please tell me, if sequelize has that feature.

**Comment by papb** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
