### ISSUE TITLE
updating an array with unshift does not work

### ISSUE THREAD

**Issue by fareshan** [sequelize/sequelize#11247]
## What are you doing?
This issue happens after upgrading to sequelize v5.

In this example, product is a table and urls is a column of type ```DataType.ARRAY(DataType.STRING)```:
This does not work:
```ts
product.urls.unshift('some-string');
await product.save();
```
And this works:
```ts
const urls = product.urls;
urls.unshift('some-string');
product.urls = urls;
await product.save();
```
The issue is with **changed fields detection** in the model.js file.

## Environment
Dialect:
- [ ] mysql
- [X] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **pg** version: 6.4.2
Database version: 10
Sequelize version: 5.10.3
Node Version: 10.16.0
OS: macos 10.14.5
If TypeScript related: TypeScript version: 3.4.3
Tested with latest release:
- [X] No
- [ ] Yes, specify that version:

**Comment by papb** [comment]
> Tested with latest release: No

Could you please test with the latest release, just in case?

**Comment by fareshan** [comment]
@papb I tested it with the latest release v5.12.0 and I got the same behavior

**Comment by Sydneyisachampion1** [comment]
What is that

**Comment by ephys** [comment]
This is a know issue. Sequelize can't currently detect that change. You need to use `Model#changed('urls', true)` ; or ,as you did, reassign (`product.urls = urls;`).

I don't consider it a bug but it's still something I'm looking into resolving as it pops up often.
I've opened a discussion here https://github.com/sequelize/meetings/issues/16 regarding changing how we detect changes.
