### ISSUE TITLE
upsert fails on MSSQL with composite unique key

### ISSUE THREAD

**Issue by massivex** [sequelize/sequelize#11240]
## What are you doing?
upsert in MSSQL with composite unique key
```js
// Define a Model with a composite unique key
class Project extends Sequelize.Model { }
Project.init({
    department: { type: Sequelize.STRING(20), unique: 'ak__project', allowNull: false },
    code: { type: Sequelize.STRING(20), unique: 'ak__project', allowNull: false }
}, { sequelize, modelName: 'project' });

Project.upsert({ department: 'DEV', code: '' }); // => Error: Primary Key or Unique key should be passed to upsert query

```
**To Reproduce**
1. Define model with a composite key with at least a string field
2. Execute an upsert with a key set to empty string
3. See error **Primary Key or Unique key should be passed to upsert query**

## What do you expect to happen?
Unique key values specified must be used as where even if a key value is an empty string

## What is actually happening?
Sequelize mssql dialect exclude unique keys value from where because one of the key values is an empty string.
This behaviour happens because empty string is evaluated falsy exactly at
https://github.com/sequelize/sequelize/blob/f3b5f99b342cb5d47865daa49a2aa6316064507c/lib/dialects/mssql/query-generator.js#L442

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [x] mssql
- [ ] any

Dialect **tedious** version: 5.0.3
Database version: SQL SERVER 2017 - 14.0.3045.24
Sequelize version: 4.44.2
Node Version: 8.11.2
OS: Linux
If TypeScript related: TypeScript version: XXX

Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.11.0

**Comment by massivex** [comment]
I suggest to change this line
https://github.com/sequelize/sequelize/blob/f3b5f99b342cb5d47865daa49a2aa6316064507c/lib/dialects/mssql/query-generator.js#L442
with ```
if (clause[key] != null) {
```
to esclude undefined and null values but keep string empty and other falsy values like 0 and false that are both valid for unique key values.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/12453
