### ISSUE TITLE
Minor duplicate code in transaction

### ISSUE THREAD

**Issue by JamesJansson** [sequelize/sequelize#11257]
## What are you doing?
Looking at /lib/transaction.js

```js
    this.id = this.parent ? this.parent.id : generateTransactionId();

    if (this.parent) {
      this.id = this.parent.id;
      this.parent.savepoints.push(this);
      this.name = `${this.id}-sp-${this.parent.savepoints.length}`;
    } else {
      this.id = this.name = generateTransactionId();
    }
```
This is probably unnecessary ` this.id = this.parent ? this.parent.id : generateTransactionId();`

**Comment by papb** [comment]
Does `generateTransactionId()` have any side effect? In the current code it can be called twice apparently...

**Comment by JamesJansson** [comment]
`generateTransactionId()` is just a uuidv4 generator. No side effect, just could cause future confusion about setting `this.id`.

**Comment by papb** [comment]
@JamesJansson I see... Would you like to send a PR?

**Comment by JamesJansson** [comment]
PR here: https://github.com/sequelize/sequelize/pull/11299
