### ISSUE TITLE
Is current .travis.yml docs deploy setting correct?

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11251]
https://github.com/sequelize/sequelize/blob/d2f33830b8bec035ac175acd3ec7622b694e00b8/.travis.yml#L78

@sushantdhiman Is this correct, or outdated? Now that `sequelize.org` contains the official docs?

**Comment by sushantdhiman** [comment]
Yes config is correct.

Someone may try to load a page from `docs.sequelizejs.com` which is still not redirected, so this handles those cases.

On other hand `sequelize.org` deploys itself every 24 hours
