### ISSUE TITLE
Soft-deleting paranoid model with custom deletedAt DB column name sets wrong attribute on instance

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#11253]
## What are you doing?

```js
const ParanoidUser = this.sequelize.define('ParanoidUser', {
  username: Support.Sequelize.STRING,

  // Custom DB column name
  deletedAt: {type: Support.Sequelize.DATE, field: 'deleted_at'}
}, {paranoid: true});

return ParanoidUser.sync({force: true}).then(() => {
  return ParanoidUser.create({
    username: 'username'
  });
}).then(user => {
  return user.destroy();
}).then(user => {
  // Both these assertions fail. Sequelize sets dataValues.deleted_at instead of deletedAt
  expect(user.dataValues.deletedAt).to.be.ok;
  expect(user.dataValues.deleted_at).to.not.be.ok;
});
```

**To Reproduce**
1. Define paranoid model with `deletedAt` that declares custom `field`
2. Soft delete model instance
3. Check resulting model instance

## What do you expect to happen?
`deletedAt` should be set.

## What is actually happening?
`deleted_at` is set.

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [x] any
Dialect **library** version: any
Database version: any
Sequelize version: master
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: master

**Comment by papb** [comment]
Looks like you have a typo here: `username: type: Support.Sequelize.STRING,`

Also, I didn't know `user.destroy()` returns itself. Perhaps a docs update is needed... If you fetch the user again from database, is it returned correctly?

**Comment by gabegorelick** [comment]
> Looks like you have a typo here: username: type: Support.Sequelize.STRING,

Sorry, that was a copy-paste error. Fixed. 

> Also, I didn't know user.destroy() returns itself.

Even if it's not supposed to return an updated instance, `user.destroy` mutates the instance in question. So the issue remains: https://github.com/sequelize/sequelize/blob/c32ac0142032977d968105e400804ed791ee7efb/lib/model.js#L4064

> If you fetch the user again from database, is it returned correctly?

Yes. The underlying UPDATE call works fine. So if you instantiate a totally new instance, everything is fine. But you can't do things like this:
```js
await model.destroy();
await model.restore(); // Sequelize gets confused because dataValues is messed up
```
