### ISSUE TITLE
MSSQL sorting by primaryKey and limit rows fetch (duplicate order by column error)

### ISSUE THREAD

**Issue by big-o-notation** [sequelize/sequelize#11263]
## What are you doing?
I am fetching from model by limitting and using offset.
The primary key is "id"

```js
MyModel.findAndCountAll({
  limit: 100,
  offset: 0,
  where: {},
  order: [ [ 'id', 'DESC' ] ] 
})
```

## What do you expect to happen?
I expect to get rows ordered by id DESC or ASC according to what I give in order properrty with offset and limit rows

## What is actually happening?
When method `addLimitAndOffset` in query-generator.js gets limit and offset (which are part of order by) the method includes in final query `order by <<MyModel.primaryKeyField>> offset N rows fetch next X ROWS ONLY`

Here is the problem when I try to sort by id (Primary Key) - it throws error: `duplicate order by column error`

As OFFSET and FETCH NEXT comes with/after ORDER BY then ORDER BY must have been provided a field/column to sort, in method the default field for ORDER BY is used primary key of model (implicitly) and what I explicitly give in `order` property in `findAndCountAll` is also primary key. So, the `id` (primary key) field is duplicated

```sql
ORDER BY [MyModel].[id] DESC, [MyModel].[id] OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY
```

## Environment
Dialect:
- [X] mysql
Dialect **library** version: XXX
Database version: MSSQL 2016
Sequelize version: 5.8.5
Node Version: 10.15.3

Tested with latest release:
- [X] No
- [ ] Yes, specify that version:

**Comment by zakhefron** [comment]
Any updates?

**Comment by papb** [comment]
@zakhefron Hello, can you or someone else create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) to show this? Thanks

**Comment by zakhefron** [comment]
Hey @papb, i've created a SSCCE, Kindly check the ink [](https://github.com/papb/sequelize-sscce/pull/22). Thanks

**Comment by zakhefron** [comment]
Hey @papb, i've created a SSCCE, Kindly check the link => https://github.com/papb/sequelize-sscce/pull/22 . Thanks

**Comment by papb** [comment]
Fantastic, thanks!!

**Comment by zakhefron** [comment]
Thanks

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/12257
