### ISSUE TITLE
instance.validate does not do typeValidation

### ISSUE THREAD

**Issue by simonbrent** [sequelize/sequelize#11266]
## What are you doing?

```js
const sequelize = new Sequelize('database', 'username', 'password', { typeValidation: true });
const model = sequelize.define('foo', {
  bar: { type: Sequelize.INTEGER },
});
model.build({ id: 1, bar: 'bar' }).validate();
model.create({ id: 1, bar: 'baz' });
```
**To Reproduce**
Run the code above

## What do you expect to happen?
When creating a Sequelize instance with typeValidation turned on, I expect that types are validated when calling the validate method on an instance. I expect output from the above code 
to be two SequelizeValidationErrors - one saying '"bar" is not a valid integer' and one saying '"baz" is not a valid integer'.

## What is actually happening?
Only one error way thrown - the one saying '"baz" is not a valid integer'.
This is because the InstanceValidator does not do anything with typeValidation, while the QueryGenerator (which isn't being used in the build/validate process) does.

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: 10.5
Database version: 10
Sequelize version: 5.10.0
Node Version: 10.16.0
OS: Ubuntu 16.04

Tested with latest release:
- [x] No (but looking at the code on github, nothing seems to have changed with regards to typeValidation since 5.10.0)
- [ ] Yes, specify that version:

**Comment by papb** [comment]
Actually, I have just checked the docs, what is says for `options.typeValidation` is this:

> Run built in type validators on insert and update, e.g. validate that arguments passed to integer fields are integer-like.

So apparently I think your example behaves like the docs say it should.

However, I agree this might be a valid change...

**Comment by simonbrent** [comment]
I think the behaviour as it stands is problematic because all the write functions in model.js (save, update, upsert, bulkCreate) start by doing instance.validate if options.validate is true. It should therefore be possible to skip a lot of code if type validation fails, instead of finding out much later that the query is invalid.

**Comment by simonbrent** [comment]
I have come across another problem relating to this issue.

If you are doing `bulkCreate` with an array of data containing multiple entries with type validation errors, the way `typeValidation` works results in an error being thrown containing only the details of the first validation error, rather than a `BulkRecordError` like you get for other types of validation.

**Comment by simonbrent** [comment]
This is still an issue with version 6.9.0
