### ISSUE TITLE
 Foreign key constraint cannot be implemented when using UUID on PosgresQL

### ISSUE THREAD

**Issue by harrytran998** [sequelize/sequelize#11269]
## What are you doing?

**User Migration Model**
```js
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";').then(() =>
      queryInterface.createTable(
        'users',
        {
          id: {
            allowNull: false,
            primaryKey: true,
            type: Sequelize.UUID,
            defaultValue: Sequelize.literal('uuid_generate_v4()')
          },
      )
}
```

**User Facebook Migration Model**

```js
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface
      .createTable(
      'facebook_users',
        {
      ....
          user_id: {
           type: Sequelize.UUID,
          allowNull: false,
          references: {
            model: 'users',
            key: 'id'
          },
          onUpdate: 'CASCADE',
          onDelete: 'CASCADE'
           }
      )
}
```

## ERROR

![Screen Shot 2019-08-02 at 12 01 23](https://user-images.githubusercontent.com/24296018/62345639-45b9e300-b51d-11e9-89aa-5701153d2fe1.png)

## What do you expect to happen?
I installed the "uuid-ossp" postgres extension.
I dont know why, I using dialect Postgres, I tried to change to UserID = Integer => It's worked! But I want to using UUID!

## Environment
Dialect:
- [X] postgres
Dialect **postgres** version: 11.3
Sequelize CLI [Node: 12.6.0, CLI: 5.5.0, ORM: 5.9.2]
OS: 14.2

**Comment by papb** [comment]
Can you please test this with another dialect? This is important to know whether the problem is dialect-specific or not.

You can instantiate an in-memory SQLite instance very easily:

1. `npm install sqlite3`
2. `new Sequelize('sqlite::memory:')`

**Comment by jetaimefrc** [comment]
> Can you please test this with another dialect? This is important to know whether the problem is dialect-specific or not.
> 
> You can instantiate an in-memory SQLite instance very easily:
> 
> 1. `npm install sqlite3`
> 2. `new Sequelize('sqlite::memory:')`

Sorry, Im a newbie, I dont know how to use sqlite3 using connect string and migration on it :(

**Comment by papb** [comment]
Since you're using migrations, you probably have a `config/config.js` file, right? Just temporarily change the connection configuration there to use sqlite. Good luck

**Comment by jetaimefrc** [comment]
> Since you're using migrations, you probably have a `config/config.js` file, right? Just temporarily change the connection configuration there to use sqlite. Good luck

Yes, but I used connect string and parse it to config new Sequelize, if I change to sqlite => Change a lot of code :(

**Comment by papb** [comment]
@jetaimefrc You should try to create a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)). Put your project aside, create a new empty folder, start a new project (`npm init -y`) where you begin from scratch with the sole goal of reproducing the above problem with the least code as possible... Without this we won't be able to help you, sorry.

**Comment by jetaimefrc** [comment]
> @jetaimefrc You should try to create a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)). Put your project aside, create a new empty folder, start a new project (`npm init -y`) where you begin from scratch with the sole goal of reproducing the above problem with the least code as possible... Without this we won't be able to help you, sorry.

Okie, I create a reposity on github, hope you can fix it!
Link: [https://github.com/jetaimefrc/test-sequelize](https://github.com/jetaimefrc/test-sequelize)

**Comment by papb** [comment]
Hello, I have cloned your repository, and after executing `npm i && npm run migrate:up`, I got no errors:

```
Sequelize CLI [Node: 10.15.0, CLI: 5.5.0, ORM: 5.12.2]

Loaded configuration file "config\config.js".
Using environment "development".
== 01-user: migrating =======
== 01-user: migrated (0.179s)

== 02-user-facebook: migrating =======
== 02-user-facebook: migrated (0.205s)
```

Did I miss something?

**Comment by jetaimefrc** [comment]
Oop, I don't know why when I change file 00-User on the top file of migration => It's worked! But when I change the position to 08-User => Foreign key constraint ...
(Note: 01 => 07 Do not have any constraint with User Table)

![Screen Shot 2019-08-05 at 09 43 42](https://user-images.githubusercontent.com/24296018/62435207-8a37bf80-b765-11e9-836b-c8d08e78f622.png)

**Comment by papb** [comment]
Yeah, the order in which migrations are executed is very relevant... In fact, when using `sequelize.sync()` instead of migrations, the models are automatically [topologically sorted](https://en.wikipedia.org/wiki/Topological_sorting) to get the right order.

Some clarification in the docs would be nice. I will leave this open as a documentation issue.

**Comment by jetaimefrc** [comment]
Thank for your help! Keep going!

**Comment by pyramation** [comment]
This is a postgres error. You probably aren't seeing the detail, and only the error. In your postgres DB if you can see the logs should show something like:

```
 ERROR:  foreign key constraint "facebook_users_user_id_fk" cannot be implemented
 DETAIL:  Key columns "user_id" and "id" are of incompatible types: uuid and integer.
```

Just make sure to keep consistent types for your identifiers.
