### ISSUE TITLE
Upsert for MySQL/MariaDB

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#11278]
why not add upsert for MySQL/MariaDB, any objections?

```js
const SequelizeModel = require('sequelize/lib/model')
SequelizeModel.upsert = function() {
  return this.findOne({
    where: arguments[0].where
  }).then(obj => {
    if(obj) {
      obj.update(arguments[0].defaults)
      return
    }
    return this.create(arguments[0].defaults)
  })
}
```

**Comment by papb** [comment]
Isn't it already implemented? At least for MySQL, apparently? From [the docs](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-upsert):

> **Implementation details:**
> 
> * MySQL - Implemented as a single query `INSERT values ON DUPLICATE KEY UPDATE values`
> * [...]

**Comment by knoxcard** [comment]
My code is wayyyy better, lol

**Comment by sushantdhiman** [comment]
You can keep that optimization as user defined model class method. I don't think I would like to include this to library. We already got native upsert for MySQL, so not need for this method.

**Comment by knoxcard** [comment]
Totally understood.  Maybe others can benefit from reading this ticket in the future.  I am just glad I know how to do all this. :-)
