### ISSUE TITLE
Sequelize not creating association fields 

### ISSUE THREAD

**Issue by simkessy** [sequelize/sequelize#11280]
I'm a little confused with when Sequelize creates the fields for associations. 

I've created my migrations using sequelize-cli. This generated a migration and model file. Then in the model file I populated my associations. Then ran `npx sequelize-cli db:migrate`. 

This creates the tables but not the foreign keys needed for the associations defined in the model. 

For example: 
migration-quesions: 

    "use strict";
    module.exports = {
      up: (queryInterface, Sequelize) => {
        return queryInterface.createTable("questions", {
          id: {
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            type: Sequelize.INTEGER
          },
          category: {
            type: Sequelize.INTEGER
          },
          question: {
            type: Sequelize.STRING
          },
          createdAt: {
            allowNull: false,
            defaultValue: new Date(),
            type: Sequelize.DATE
          },
          updatedAt: {
            allowNull: false,
            defaultValue: new Date(),
            type: Sequelize.DATE
          }
        });
      },
      down: (queryInterface, Sequelize) => {
        return queryInterface.dropTable("questions");
      }
    };

model-questions: 

    "use strict";
    module.exports = (sequelize, DataTypes) => {
      const questions = sequelize.define(
        "questions",
        {
          question: DataTypes.STRING,
          weight: DateTypes.INTEGER
        },
        {}
      );
      questions.associate = function(models) {
        // associations can be defined here
        models.questions.hasOne(models.question_categories);
        models.questions.hasMany(models.question_answers);
      };
      return questions;
    };

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/0eMxk.png

**Comment by papb** [comment]
I believe the docs could use some extra clarification, indeed. The behavior you are seeing is correct, in principle. The migration is something that changes the database according to what you told it to do, there isn't much extra magic behind the scenes, so you have to put the foreign keys explicitly in your migration.

**Comment by simkessy** [comment]
I realized I could use the sync() method to have the database reflect the models. I don't see the point of the migration files however in that case. It's a lot simpler for me to setup the models then it is to go through and update migration files to add additional columns. Docs should be updated, it's not very clear.

**Comment by papb** [comment]
Let me keep this open to clarify the docs :+1:
