### ISSUE TITLE
Force bind

### ISSUE THREAD

**Issue by sm2017** [sequelize/sequelize#11296]
How can I force sequelize to always **Bind Parameter** not **Replacements**

Sometimes findAll , findByPk replaces parameters

**Comment by papb** [comment]
Oops! For some reason I missed your issue among the others. I usually look at issues much faster than these 17 days... Sorry!

Now, as for the issue, we really need more info. You were too succinct. Please elaborate on what you mean, showing examples of situations in which you didn't get what you wanted, and so on.

**Comment by sm2017** [comment]
Currently I cannot provide you code to reproduce issue ( if you need let me know)

In sequelize we have 2 way to set parameters , binding and replacement

I see that , we I use sequelize models to generate query, sometimes it generate queries with replacement method , like

```sql
SELECT name from user WHERE id=123
```

I want force sequelize always bind parameters, like

```sql
SELECT name from user WHERE id=:id
```

Or

```sql
SELECT name from user WHERE id=$1
```

**Comment by papb** [comment]
Thanks. I would like to see an example that generates each case please!

**Comment by sm2017** [comment]
@papb , for simplicity I reproduce it using sqlite dialectic (I am using postgres)


```js
const Sequelize = require('sequelize');
const Model = Sequelize.Model;


(async function(){
	
	const sequelize = new Sequelize('database', 'username', 'password', {
	  // sqlite! now!
	  dialect: 'sqlite',

	  // the storage engine for sqlite
	  // - default ':memory:'
	  storage: './database.sqlite'
	})



	class Project extends Model {}
	Project.init({
	  id: {
	  type: Sequelize.INTEGER,
	  primaryKey: true,
	  autoIncrement: true,
        },
	  title: Sequelize.STRING,
	  description: Sequelize.TEXT
	}, { sequelize, modelName: 'project' });

	await Project.sync();

	//INSERT INTO `projects` (`id`,`title`,`description`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3,$4);
	await Project.create({
		title: 'foo',
		description: 'bar',
	})

	//SELECT `id`, `title`, `description`, `createdAt`, `updatedAt` FROM `projects` AS `project` WHERE `project`.`id` = 1;
	const project = await Project.findByPk(1);
	project.title='foobar';
	
	// UPDATE `projects` SET `title`=$1,`updatedAt`=$2 WHERE `id` = $3
	await project.save();
	

})()
```


In the above mentioned code ,  findByPk generate replacement parameter

**Comment by sm2017** [comment]
@papb I want to know when you can fix it?

**Comment by papb** [comment]
Hello, I am very busy these days, unfortunately... Sorry :( I can't give an estimate. Certainly not this month though :(
