### ISSUE TITLE
Before hooks should be able to cancel the query

### ISSUE THREAD

**Issue by HKFiliatix** [sequelize/sequelize#11298]
Sometimes need to cancel query in hook, if some conditions not met. 

**Describe the solution you'd like**
As I can see from code (example findAll) result of hook execution aren't used - so maybe `return false` can be used to cancel the query and exit from promise chain?

Now I do this by throwing cancelQuerySequelizePseudoException and catch it outside, but this way is tricky.

**Comment by papb** [comment]
Actually this could be done without being a breaking change if we provided a "token object" `Sequelize.CANCEL_QUERY` or something similar, that cancels the query if returned from the hook.

**Comment by sushantdhiman** [comment]
You can throw in hooks to reject query processing. This is better because caller actually gets notified that query was not executed, rather than silently canceling promise chain execution.
