### ISSUE TITLE
addingAssociation `hasMany`  generate invalid SQL

### ISSUE THREAD

**Issue by maruo34** [sequelize/sequelize#11308]
**product.js**
```js
module.exports = (sequelize, DataTypes) => {
  const Product = sequelize.define('Product', {
    name: DataTypes.STRING,
    price: DataTypes.DECIMAL(10, 2),
    profit: DataTypes.DECIMAL(10, 2),
    category: DataTypes.STRING,
    brand: DataTypes.STRING,
  }, {
    tableName: 'products'
  });

  Product.associate = function (models) {
    this.hasMany(models['ProductPicture'], {
      foreignKey: 'product_id',
      as: 'pictures'
    });

    this.hasMany(models['ProductFeature'], {
      foreignKey: 'product_id',
      as: 'features'
    })
  };

  return Product;
};
```
**code**
```js
Product.findByPk(1)
    .then(product => {
        product.addPicture({
                picture: '/images/foo.png'
            })
            .then(pictures => {
                // console.log(pictures);
            }).catch(err => {
                console.log(err);
            });
    }).catch(err => {
        console.log(err);
    });
```
**Output**
```bash
Executing (default): SELECT `id`, `name`, `price`, `profit`, `category`, `brand`, `createdAt`, `updatedAt` FROM `products` AS `Product` WHERE `Product`.`id` = 1;
Executing (default): UPDATE `product_pictures` SET `product_id`=? WHERE `id` IN (NULL)
```

why it happens?

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner.

Note that this issue will be closed for not following the issue template (specifically, for not including a SSCCE). You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
