### ISSUE TITLE
.sync({alter:true)} causes issue with Boolean Default Values in MSSQL

### ISSUE THREAD

**Issue by Taher62** [sequelize/sequelize#11301]
## What are you doing?

```js
// code here
```
**To Reproduce**
1. Define models X, Y, ...
2. Run the following
3. See error

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: XXX
Sequelize version: XXX
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [ ] Yes, specify that version:

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).

**Comment by papb** [comment]
Refer to #11303
