### ISSUE TITLE
how to left join or left outer join in sequelize 6.0 

### ISSUE THREAD

**Issue by jitendrachhipa** [sequelize/sequelize#11302]
how to left join or left outer join in  two table without any associations?

I want to execute a query on two table for reports without any relations of foreign key

**Comment by papb** [comment]
I recommend using sequelize v5 for now unless you have a very specific reason to be using v6.

----------------------------

Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
