### ISSUE TITLE
Virtual column ends up in SQL query when associated model has default scope with attributes configuration

### ISSUE THREAD

**Issue by bparan** [sequelize/sequelize#11316]
## What are you doing?

```js
const Sequelize = require('sequelize');

const sequelize = new Sequelize('sqlite::memory:');

const Game = sequelize.define('Game', {
    name: Sequelize.TEXT,
    version: {
        type: Sequelize.VIRTUAL,
        get() {
            return 1;
        }
    }
});

const User = sequelize.define('User', {
    login: Sequelize.TEXT,
    session: {
        type: Sequelize.VIRTUAL,
        get() {
            return 'New';
        }
    }
}, {
    defaultScope: {
        attributes: {
            exclude: ['login']
            /*include: ['login']*/
        }
    }
});

Game.hasMany(User);
await sequelize.sync({force: true});

const games = await Game.findAll({
    include: [{
        model: User
    }]
});

console.log(games.length);
```
**To Reproduce**
1. Define model to be associated with defaultScope that includes `attributes` configuration
2. Define a parent model
3. Associate the parent model with child model using `hasMany`.
4. Query the parent records including the association.

## What do you expect to happen?
_On empty tables I'd expect `0` to be printed to the console_

## What is actually happening?
_I got SequelizeDatabaseError_

_SequelizeDatabaseError: SQLITE_ERROR: no such column: Users.session
      at Query.formatError (C:\Proj\node_modules\sequelize\lib\dialects\sqlite\query.js:419:16)
      at Query._handleQueryResponse (C:\Proj\node_modules\sequelize\lib\dialects\sqlite\query.js:73:18)
      at afterExecute (C:\Proj\node_modules\sequelize\lib\dialects\sqlite\query.js:247:31)
      at replacement (C:\Proj\node_modules\sqlite3\lib\trace.js:19:31)
      at Statement.errBack (C:\Proj\node_modules\sqlite3\lib\sqlite3.js:16:21)_

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [x] sqlite
- [x] mssql
- [ ] any
Dialect **library** version: pg@7.0.0, pg-hstore@2.3.3, sqlite3@4.0.9, tedious@6.0.0
Database version: sqlite3, PostgreSQL 11.4, MSSQL 2017
Sequelize version: 5.12.1
Node Version: 10.13.0
OS: Windows 10
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.14.0

**Comment by papb** [comment]
Thanks for the excellent issue report!

What is the reason you didn't select `mysql`? Is it just because you didn't test on it or because you tested and the problem doesn't happen with it?

**Comment by bparan** [comment]
@papb I didn't tested on `mysql`. MSSQL, PostgreSQL and Sqlite are installed on my machine. I debugged the issue a bit and I saw it in the code that is common for all dialects.
I need time to focus on a different issue in our project. I will try to reproduce the issue on `mysql` when I have time.

**Comment by MegaFAX** [comment]
+1 with PostgreSQL, my temporary solution is 
```js
include: [{
        model: User,
        attributes: {
                exclude: ['session']
        }
}]
```

**Comment by papb** [comment]
> @papb I didn't tested on `mysql`. MSSQL, PostgreSQL and Sqlite are installed on my machine. I debugged the issue a bit and I saw it in the code that is common for all dialects.
> I need time to focus on a different issue in our project. I will try to reproduce the issue on `mysql` when I have time.

@bparan Don't worry! Testing with three dialects is excellent already :+1: use your time for other things! I was asking just to be sure I didn't misunderstand you.

**Comment by javaguy** [comment]
Hitting this issue as well, but unfortunately not an option to just exclude all virtual attributes from my nested model. Any other suggestions for workarounds?

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/11327
