### ISSUE TITLE
Add findAll option for unique results

### ISSUE THREAD

**Issue by oleprohon** [sequelize/sequelize#11314]
Greetings,

I use two models User and Account.
User.hasMany(Account) and Account.belongsTo(User)

One user may have multiple accounts and each account has a role. One user can have multiple accounts with the same role.

I want to get all unique users having one or more "driver" Accounts.

```
User.findAll({
      where: { status: 1 },
      include: [{
        model: Account,
        as: 'account',
        attributes: ['id', 'role'],
        where: { role: 'driver' },
        required: true
      }]
    }).then(users => {
      for (let user of users) {
        // my stuff
      }
    }).catch(console.log);
```

If a given user has 2 accounts with the role "driver", I get two instances of the user.

I looked at the include option "duplicating", but I don't think this is meant for this case. I tried adding a limit of 1 to Account include but it is not supported because of the belongs to.

Am I missing something or there is no option to specify that? For now I will simply use a filter on users before processing each users.

Using latest Sequelize v5.latest with MySQL and Node 11.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by oleprohon** [comment]
Hi thanks for taking the time to answer and sorry about the format, this is my first post on github! 

If anyone is facing the same problem, it was actually on my side, so no issue from Sequelize. I had 2 associations between users and accounts:

User.hasMany(Account, { as: 'accounts', foreignKey: 'userId' });
User.hasOne(Account, { as: 'account', foreignKey: 'userId' });

In my query I used "as: 'account'" so using the one-to-one association probably causing the duplicate users.
