### ISSUE TITLE
Calling fn('NOW')  as a static method gets error

### ISSUE THREAD

**Issue by xuchaobei** [sequelize/sequelize#11315]
## What are you doing?
I want to set current timestamp as below:

```js
import {Sequelize} from "sequelize";

User.create({ user_id:'1234',  created_at: Sequelize.fn('NOW') })  //User is a Model
```

Got the error:
> sequelizedatabaseerror: the first argument must be one of type string, buffer, arraybuffer, array, or array-like object. received type object

However, when I call fn("NOW") on the sequelize intance, it works:

```js
import {Sequelize} from "sequelize";

const sequelize = new Sequelize('database', 'username', null, {
    dialect: 'mysql'
 })

User.create({ user_id:'1234',  created_at: sequelize.fn('NOW') })
```

I digged into the source code, fn should be a static method of Class Sequelize, 
`Sequelize.prototype.fn = Sequelize.fn;`.

Then why I can't use Sequelize.fn('NOW')? What's the difference?

## What do you expect to happen?

Calling `fn("NOW")` as a static method can work properly as calling it as a instance method.

## Environment
Dialect: mysql
Dialect version: NA
Database version: 5.6
Sequelize version: 5.10.1
Node Version: 10.15.3
OS: Linux/Mac

**Comment by papb** [comment]
I was unable to reproduce.

```js
const Sequelize = require('sequelize');
console.log(Sequelize.fn("NOW")); // works for me, does not throw any error
```

You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

**Comment by xuchaobei** [comment]
> I was unable to reproduce.
> 
> ```js
> const Sequelize = require('sequelize');
> console.log(Sequelize.fn("NOW")); // works for me, does not throw any error
> ```
> 
> You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

@papb  `console.log(Sequelize.fn("NOW"));` works. You need to execute the real  insert/update operation to get the error. Like this:
```
import {Sequelize} from "sequelize";

user.create({ user_id:'1234',  created_at: Sequelize.fn('NOW') })  //user is a model instance
```

**Comment by papb** [comment]
I was unable to reproduce with postgres (the DB that I have available right now) - both ways worked. I suspect you are doing something else wrong. Especially because I agree with you, it doesn't make sense to make a difference.

Also, the code you posted still isn't a SSCCE/MCVE/reprex.
