### ISSUE TITLE
Support of Escaping query identifiers

### ISSUE THREAD

**Issue by ghost** [sequelize/sequelize#1132]
Hi,

I am using Sequelize 2.0.0 in my project and my dialect is mysql.

For now, i am preferring to use raw SQL queries instead of using Sequelize ORM methods.

I am not able to find any example or documentation regarding "How to use Escaping query identifiers with raw SQL queries" in Sequelize.

I want to escape quotes in some case while performing insert or update operations.

Thanks

**Comment by jcalfee** [comment]
Looking at the code, I guess `sequelize.escape` is better.  It calls a dialect specific `QueryGernerator.escape` method.  I just hope that it will be supported in the future.

**Comment by kuriel-trivu** [comment]
SqlString is not available for v6

any replacement?

**Comment by WikiRik** [comment]
@kuriel-trivu  The raw queries page for v6 can be found at https://sequelize.org/master/manual/raw-queries.html
Is the answer for you in that file?

**Comment by kuriel-trivu** [comment]
> @kuriel-trivu The raw queries page for v6 can be found at https://sequelize.org/master/manual/raw-queries.html Is the answer for you in that file?

No, I meant to require('sequelize/lib/sql-string').escape
