### ISSUE TITLE
[Docs] Typescript example breaks automagic field getters

### ISSUE THREAD

**Issue by psalz** [sequelize/sequelize#11326]
I followed the documentation on how to [set up a model with Typescript](https://sequelize.org/master/manual/typescript.html) and ran into an issue: If fields are declared on the model class as described here, they will be initialized to `undefined` upon instantiation and overwrite the automagic getters generated by Sequelize. I.e., if following the documentation, the `console.log(newUser.id, newUser.name, newUser.preferredName);` at the bottom will actually print `<some id> undefined undefined`.

I'm currently working around this by deleting all of the undefined properties on an instance, so that any field lookup will fall back to the prototype's automagic getters:
```js
  MyModel.addHook('afterCreate', (instance, options) => {
    for (const [prop, desc] of Object.entries(
      Object.getOwnPropertyDescriptors(instance)
    )) {
      if (
        desc.get === undefined &&
        desc.set === undefined &&
        desc.value === undefined
      ) {
        delete (instance as any)[prop]
      }
    }
  })
```

I'm wondering if something like this should be done by Sequelize itself, perhaps enabled through an option on `Model.init`? In any case, the documentation should be updated to properly handle this.

## Environment
Sequelize version: 5.15.0
Node Version: 10.15.0
TypeScript version: 3.2.2

**Comment by papb** [comment]
Hello, thanks for the detailed report. I am not familiar with the TypeScript usage of Sequelize, so let's wait for @SimonSchick to take a look later.

**Comment by SimonSchick** [comment]
Please follow the issue template.

**Comment by sunwukonga** [comment]
I had the same issue and opened a [question](https://stackoverflow.com/questions/57542074/sequelize-findone-returned-instance-row-is-in-datavalues-but-direct-properties/57550292#57550292) on SE.

Long story short, it was a babel plugin `"@babel/proposal-class-properties"`. Which causes the model fields to be defined/initialized on the model as undefined.

Removing the plugin should clear it up as it did for me.

**Comment by SimonSchick** [comment]
We should really discourage the use of babel with sequelize, it causes so many issues...

**Comment by psalz** [comment]
Thanks @sunwukonga , that indeed appears to be the culprit. I did some more testing and it turns out that if you ensure that the `@babel/plugin-transform-typescript` plugin runs before `@babel/proposal-class-properties`, everything works fine ([Babel REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECyCeBhcVoG8BQ1oFt4DEBLAUxABMBCALmgDsBXHAI2ICdoMBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-9&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.5.5%2C%40babel%2Fplugin-proposal-class-properties%407.5.5))!
