### ISSUE TITLE
Can't Create with Associations

### ISSUE THREAD

**Issue by simkessy** [sequelize/sequelize#11335]
I'm trying to create a record with associations from existing records. 

For example: 

```
        const surveys = await Surveys.create(
          {
            UserToId: args.UserToId,
            UserFromId: args.UserFromId,
            statusId: args.statusId,
            sourceId: args.sourceId,
            link: args.link,
            score: args.score
          },
          {
            include: [
              { model: Users, as: "UseToId" },
              { model: Users, as: "UserFromId" },
              { model: Statuses },
              { model: Sources }
            ]
          }
        );

        console.log("survey:", surveys);
        return surveys;
```

I get the message: 

> users is associated to surveys multiple times. To identify the correct association, you must use the 'as' keyword to specify the alias of the association you want to include.

It seems like that's what I did in the includes but it's still not allowing me to create the items. 

Why can I not create items with just their IDs, I don't understand why I need the include if I just want to insert and ID into a ForeignKey column.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

**Comment by simkessy** [comment]
I updated my post, re-open the issue please.

**Comment by papb** [comment]
It is still not a SSCCE/MCVE/reprex.

Also, you have `as: "UseToId"` and `as: "UserFromId"` on your call but `{ as: "to" }` and `{ as: "from" }` in your definition.

**Comment by hengkx** [comment]
same error
