### ISSUE TITLE
M:M relationship not creating intermediary table.

### ISSUE THREAD

**Issue by Aldarean** [sequelize/sequelize#11339]
Using the little documentation that is available to create a M:M relationship with the MSSQL dialect I either found a bug or totally didn't understand the documentation.

I set up 2 models for now only with an Id to create a M:M relationship by specifying it with the ".belongsToMany()" method. They both reference an intermediary model and the model gets created with the Id's. However thats where it stops. The relationship between the model is not created and thus the extra crud functionality does not get created when using the parent.

now there is a worksround by using belongsto on the intermediary table, but I want to use belongsToMany as that is the specified way through the docs.

My code: 
https://stackoverflow.com/questions/57571587/sequelize-manytomany-relationship-doesnt-create-the-relationship

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
