### ISSUE TITLE
mysql abstraction always uses prepared statements

### ISSUE THREAD

**Issue by l-jonas** [sequelize/sequelize#11330]
## What was unclear/insufficient/not covered in the documentation

When using the mysql2 module, then sequelize uses ``connection.execute()`` from mysql2. The [Readme](https://www.npmjs.com/package/mysql2) says ``// execute will internally call prepare and query`` In my case this created more and more prepared statements which I did not expect and caused reaching the limit for prepared statements which causes queries to fail until I restart the application.

When using the mariadb module, then no prepared statements are created.

### If possible: Provide some suggestion how we can enhance the docs

Tell users which db abstractions use prepared statements. Would be better to add a option "use prepared statements if possible", eventually per query instead of per sequelize instance.

**Comment by duncanmapes** [comment]
+1

**Comment by bellomimarc** [comment]
I have the same problem with mysql. Please fix it or I'll change library :(

**Comment by xiabaiyang** [comment]
Our self-developed database currently does not support prepare statements, so I hope you can support the unprepare query，just like `new sequelize({ prepare: false })`

**Comment by ephys** [comment]
It looks like this was resolved in https://github.com/sequelize/sequelize/pull/12981
