### ISSUE TITLE
updateOnDuplicate error with postgres >= 9.5

### ISSUE THREAD

**Issue by Delagardi** [sequelize/sequelize#11333]
## What are you doing?
I am trying to use "bulkUpdate" functionality with `bulkCreate` + updateOnDuplicate option.

I need to update all `relatedToLead` fields at table `contacts` WHERE `contactId` === `contactId`

I am getting an error: 
"postgres does not support the 'updateOnDuplicate' option."

But my version of Postgres is 9.5.16. 
[Here ](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-bulkCreate ) docs said:
> options.updateOnDuplicate -- Fields to update if row key already exists (on duplicate key update)? (only supported by MySQL, MariaDB & **Postgres >= 9.5**)

```js
const entitiesData = [ 
  { 
    contactId: '16', 
    relatedToLead: '7' 
  },
  { 
    contactId: '17', 
    relatedToLead: '8' 
  },
  { 
    contactId: '18', 
    relatedToLead: '9' 
  } 
]

const contacts = await Contact.bulkCreate(entitiesData, { 
    returning: true,
    updateOnDuplicate: ['contactId'], 
  });
```
## What do you expect to happen?
I wanted update all `relatedToLead` fields at table `contacts` WHERE `contactId` === `contactId`

## What is actually happening?
I got an error:
**"postgres does not support the 'updateOnDuplicate' option."**

## Environment
Dialect:
- [ ] mysql
- [X] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: ^7.7.1 | ^2.3.2
Database version: 9.5.16
Sequelize version: 4.42.0
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.
