### ISSUE TITLE
Adding a column after a specified column 

### ISSUE THREAD

**Issue by Dlas1212** [sequelize/sequelize#11349]
### What are you doing?

I am trying to add a column to my table after a specified column.

### What do you expect to happen?

Example If i got [title - locations - slug ] I want to add in the column 'salary' and place it between title and locations.

### What is actually happening?

The column just gets added to the end of SQL table

```
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

    return Promise.all([
      queryInterface.addColumn(
        'jobs',
        'salary',
        Sequelize.STRING, {
          allowNull: true,
            after: "location"
          
        
        }
      )
    ])

  },

  down: (queryInterface, Sequelize) => {

    return Promise.all([
      queryInterface.removeColumn('jobs', 'salary')
    ])
  }
};

```

### Environment

- Sequelize version: sequelize@5.15.1
- Node.js version: v10.15.3
- Operating System: MAC OS Majove

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Can you post which SQL query was generated and what SQL query did you want instead?

**Comment by sushantdhiman** [comment]
https://sequelize.org/master/class/lib/query-interface.js~QueryInterface.html#instance-method-addColumn

We support passing `after` as 4th argument options. This is only supported for MySQL.
