### ISSUE TITLE
Unexpected result of onDelete cascade for mixed paranoid and not paranoid models

### ISSUE THREAD

**Issue by JayAndCatchFire** [sequelize/sequelize#11346]
## Issue Description
I'm having an issue with cascading deletion in cases where the child model is set to paranoid but the parent model is not.  In that case, paranoid is not respected on the child model for the cascading deletion.

### What are you doing?

```js
const Book = sequelize.define('Book', {
  // columns
}, {
   paranoid: true,
   classMethods: {
     associate: function(models) {
       Book.belongsTo(models.Author);
    },
  },
});

const Author = sequelize.define('Author', {
  // columns
}, {
  classMethods: {
    associate: function(models) {
      Author.Books = Module.hasMany(models.Book, {
        hooks: true,
        onDelete: 'CASCADE',
      });
    },
});
```

For a particular Author with one or more Books associated with it, I'm calling `.destroy()` on the Author instance.

### What do you expect to happen?

I would perhaps expect the instance of Author to be hard-deleted and the associated Books to be soft-deleted.

### What is actually happening?

Both the Author and the Books are hard-deleted from the database.

### Additional context

I don't know if this is a known limitation/expected behavior, or if it's a bug? I can see it both ways. On the one hand, it was an unexpected result from my point of view when I ran into this, but it also kind of makes sense as any relationship is now broken as those Books' foreign keys would point to non-existent entities in the Authors table. (That's assuming foreign key constraints were enforced. They are not enforced on the database level in my setup.)

If it matters, I'm seeing this behavior occur on a Postgres database.

I originally commented about this on #2586 because I thought it might be related. 🤷‍♂ 

### Environment

- Sequelize version: 3.35.1
- Node.js version: 10.15.3
- Operating System: Debian GNU/Linux 9 (stretch)
- ~If TypeScript related: TypeScript version: XXX~

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
`3.35.1` is not supported

**Comment by papb** [comment]
Does this happen in latest Sequelize as well?

Regardless, as sushantdhiman said, you're using an old version that only receives security patches now, any chance you could upgrade to latest sequelize?

**Comment by JayAndCatchFire** [comment]
This is for work and the team is pretty serious about "stable" versions of dependencies.  I could try this myself just to see if it's fixed in more recent versions, but I doubt I'll have time to test it in the near future.

**Comment by hemantreddy** [comment]
@sushantdhiman would this work on the latest version?
