### ISSUE TITLE
Sequelize bulkCreate() saves previous day

### ISSUE THREAD

**Issue by marcpre** [sequelize/sequelize#11352]
### What are you doing?

I am trying to save the following array of json in my db:
```
    dataArray = [{
      "name": "Product 1",
      "rating_date": "8/16/2019",
      "producer": "producer 1",
      "action": "Sell",
      "previous": "Buy",
      "to": "Sell",
    }]
```
When saving the above array with `bulkCreate()` it looks like the following in my mysql db:
```
  {
     "id": 3,
     "name": "Product 1",
     "rating_date": "2019-08-15T22:00:00.000Z", // <--- THIS DATE IS WRONG!
     "producer": "producer 1",
     "action": "Sell",
     "previous": "Buy",
     "to": "Sell",
  }
```
My sequelize definition looks like the following:
```
      const Product = sequelize.define('Product', {
        name: DataTypes.STRING,
        rating_date: DataTypes.DATE,
        producer: DataTypes.STRING,
        action: DataTypes.STRING,
        previous: DataTypes.STRING,
        to: DataTypes.STRING,
      }, {});
```
Any suggestions why the previous day is saved instead of the exact given date?

### What do you expect to happen?

I would like to save the day that I hand over to `bulkCreate()`

### What is actually happening?

The wrong day is saved.

### Environment

- Sequelize version: ^5.8.6 
- Node.js version: v10.15.3
- Operating System: Windows 8
- MYSQL VERSION: 10.1.39-MariaDB

### How does this problem relate to dialects?

- [ x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
This looks like a timezone issue, have you considered this?

Sequelize allows configuring the timezone in the constructor options
