### ISSUE TITLE
findOrCreate transaction

### ISSUE THREAD

**Issue by epyx25** [sequelize/sequelize#11351]
## Issue Description

I am using Sqlite 3 (4.0.6) with Sequalize (4.38.0). Models are Tournament what hasMany Season (unique index year and tournamentId). Here is the flush class:

```JS
  async flush(tournamentJSON) {
    this.tournamentJSON = tournamentJSON
    const {sequelize} = await this.orm
    this.transaction = await sequelize.transaction()
    try {
      const tournament = await this.flushTournament()
      const season = await this.flushSeason(tournament)
      // commit
      await this.transaction.commit();

    } catch (err) {
      console.log(err)
      // Rollback transaction if any errors were encountered
      if (err) await this.transaction.rollback();
    }
  }

  async flushTournament() {
    const {tournamentJSON} = this
    const {models: {Tournament}} = await this.orm
    const [tournament, created] = await Tournament.findOrCreate({
      where: {
        country: tournamentJSON.country,
        type: tournamentJSON.type,
        identifier: tournamentJSON.identifier
      },
      transaction: this.transaction
    })
    return tournament

  }

  async flushSeason(tournament) {
    const {tournamentJSON} = this
    const {models: {Season}} = await this.orm
    const [season, created] = await Season.findOrCreate({
      where: {
        name: tournamentJSON.name,
        finCommit: tournamentJSON.finCommit,
        start: moment(tournamentJSON.start.replace(/\./g, '-')).toISOString(),
        year: Number(this.year),
        tournamentId: tournament.id
      },
      transaction: this.transaction
    })
    console.log(created)
    console.log(season)
    return season
  }
```

And here is how I use it in my test:

```JS
  const flush = new Flush()
  const flush1 = new Flush()
  flush.year = 2011
  flush1.year = 2012
  let tournamentJSON = await Helper.loadJSON(`${t.context.fixtures}/someTournament.json`)
  await flush.flush(tournamentJSON)
  await flush1.flush(tournamentJSON)
```

I expect one tournament and two seasons (with year 2011 and 2012) to be created, but only one season is created, with the year 2012. The flushSeason method runs twice. In two lines of console.log I can see, that in booth case created is true.

From the log
```
Executing (cb4f89f4-8e00-4fd0-b329-0c263f389922): 
INSERT INTO `season` (`id`,`name`,`year`,`start`,`finished`,`scraped`,`finCommit`,`createdAt`,`updatedAt`,`tournamentId`) 
VALUES (NULL,'Some name',2011,'2011-08-12 00:00:00.000 +00:00',0,0,'2000','2019-08-23 15:26:02.528 +00:00','2019-08-23 15:26:02.528 +00:00',1);
Executing (2ee2b03e-b127-491e-9da7-572e89d2ba70): 
INSERT INTO `season` (`id`,`name`,`year`,`start`,`finished`,`scraped`,`finCommit`,`createdAt`,`updatedAt`,`tournamentId`) 
VALUES (NULL,'Some name',2012,'2011-08-12 00:00:00.000 +00:00',0,0,'2000','2019-08-23 15:26:02.528 +00:00','2019-08-23 15:26:02.528 +00:00',1);

```

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.
https://stackoverflow.com/questions/57629164/sequelize-findorcreate-transaction

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.
