### ISSUE TITLE
typings could be improved when executing queries with QueryTypes.RAW

### ISSUE THREAD

**Issue by jpollard-cs** [sequelize/sequelize#11356]
## Issue Description

The current definition for the `query` method overload looks like this:

 ```
// Options and SQL types are artificially added here for readability
type Options = QueryOptions | QueryOptionsWithType<QueryTypes.RAW>;
type SQL = { query: string; values: unknown[] };
public query(sql: string | SQL, options?: Options): Promise<unknown[]>;
```

this means you end up with an error whenever attempting to check `results[0].length`

this could instead use a tuple:

 ```
interface RawQueryMetadata {
  rowCount?: number;
  // etc... not sure exactly what should go in here
}

type Options = QueryOptions | QueryOptionsWithType<QueryTypes.RAW>;
type SQL = { query: string; values: unknown[] };
public query(sql: string | SQL, options?: Options): Promise<[unknown[], RawQueryMetadata]>;
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
- [x] maybe .. depends on feedback

**Comment by papb** [comment]
> maybe .. depends on feedback

Can you post a code snippet that doesn't compile currently, and that you would like to see compiling?
