### ISSUE TITLE
MySQL undo migration fails to remove column if no foreign keys

### ISSUE THREAD

**Issue by amites** [sequelize/sequelize#11363]
## Issue Description

When running `npx sequelize-cli db:migrate:undo` migration fails to run `queryInterface.removeColumn` where there is not a foreign key associated with the column

### What are you doing?

```js
            await queryInterface.removeColumn('table_name', 'column_text', {
                type: Sequelize.TEXT,
            }, { transaction });
```

### What do you expect to happen?

Migration undo would run removing columns

### What is actually happening?

```
`ERROR: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined`
    at qi.sequelize.query.then (.../sequelize/lib/dialects/mysql/query-interface.js:34:11)
```

### Additional context
Cross compiled from typescript

Code has changed from `5.16.0` to master -- the failing line is part of
`function removeColumn(qi, tableName, columnName, options) {`
...
```
.then(([results]) => {
```

##### Work Around

Use `Promise`

```
        return queryInterface.sequelize.transaction((t) => {
            return Promise.all([
                queryInterface.removeColumn('table', 'columna', { transaction: t }),
                queryInterface.removeColumn('table', 'columnb', { transaction: t }),
            ]);
        ]);
```

**UPDATE**
tried a range of things, one block or another popped up
what is working now is using `return Promise.all([` vs `await`

I'll make a note to get an SSCCE created -- ran against my time limit on making a PR 

### Environment

- Sequelize version: 5.16.0
- Node.js version: 8.16.0
- Operating System: Ubuntu 19.04
- If TypeScript related: TypeScript version: 3.5.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): MySQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by amites** [comment]
👍 updated the original issue with the workaround -- the original `await` method is straight out of the docs -- suspect it's actually how bluebird is handling an empty set but didn't nail down root cause

**Comment by sushantdhiman** [comment]
https://sequelize.org/master/class/lib/query-interface.js~QueryInterface.html#instance-method-removeColumn

`removeColumn` only accepts 3 arguments, you are passing 4 arguments to it. It does not need `{type: Sequelize.TEXT}`
