### ISSUE TITLE
Update maps returned instance to the wrong model

### ISSUE THREAD

**Issue by a88zach** [sequelize/sequelize#11364]
## Issue Description

When multiple models are wired up to the same table. The model's static update method can incorrectly map the returned instance to the wrong model

### What are you doing?
```
class Foo extends Model {}
Foo.init({ /* bla */ }, {
  tableName: 'table_with_discriminator',
  sequelize
})

class Bar extends Model {}
Bar.init({ /* bla */ }, {
  tableName: 'table_with_discriminator',
  sequelize
})


const updates = await Bar.update(
      { prop: 'value' },
      {
        where: { id: 'xxx },
        returning: true
      }
    );
const updatedInstance = updates[1][0]; // this is an instance of Foo
```

### What do you expect to happen?

The updated instance should be an instance of Bar

### What is actually happening?

The updated instance is an instance of Foo

### Additional context
The root cause if this line:
https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L1040
Which is called from the update method here:
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3219

The returned instances are being mapped to a model based on the underlying table name.  The instance should be mapped to the same model used to call the update method

### Environment

- Sequelize version: 5.16.0
- Node.js version: 10.15.3
- Operating System: Mac

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
@a88zach I guess it might make sense... But have you considered just using multiple names scopes instead?

```js
const FastFoodRestaurant = Restaurant.scope("FAST_FOOD");
await FastFoodRestaurant.findAll();
// And same idea defining other scopes for the other types
```

**Comment by sushantdhiman** [comment]
Interesting usecase, possible fix will be to remove https://github.com/sequelize/sequelize/blob/398ae59354973348d49d12a08bda2c07bdd7514e/lib/query-interface.js#L1040 altogether and have `Model` class set `options.model` whenever using `queryInterface.bulkUpdate`

**Comment by a88zach** [comment]
@papb, that, indeed, would solve the issue for the example I gave above.  However, that is not my real use case as it's a bit more complicated.

We publish a shared npm package that exposes our data repositories and domain models that are derived from the sequelize models.  This package is then consumed in our api and client projects so that the domain models can be used consistently throughout our code.

However, we don't want to expose the sequelize methods to consumers as we only allow certain operations and consumers must go through our repository methods to interact with our database.  Those repositories essentially wrap the sequelize methods we want to expose.

For the domain models, we use a custom typing to strip away the sequelize stuff before we export so that we only expose the pojo.  This is a Typescript project by the way.

```
export type RawModel<T extends Model<T>> = Pick<
  T,
  Exclude<keyof T, keyof Model<T>>
> & { id?: string };

export type RecursiveRawModel<T extends Model<T>> = {
  [K in keyof RawModel<T>]: T[K] extends
    | Date
    | number
    | string
    | boolean
    | undefined
    ? T[K]
    : T[K] extends (infer X)[]
    ? X extends Model<X>
      ? RecursiveRawModel<X>[]
      : T[K]
    : T[K] extends (infer Y)[] | undefined
    ? Y extends Model<Y>
      ? RecursiveRawModel<Y>[] | undefined
      : T[K]
    : T[K] extends infer U
    ? U extends Model<U>
      ? RecursiveRawModel<U>
      : T[K]
    : T[K] extends infer V | undefined
    ? V extends Model<V>
      ? RecursiveRawModel<V> | undefined
      : T[K]
    : never
};
```

We then export our raw domain models like so:
`export type AppSetting = RecursiveRawModel<models.AppSetting>;`

This means that consumers can only build domain objects using the pojo and do not have access to all the sequelize goodies. This enforces that all consumers go through our data repositories

Our models that are bound to the same database table are also made up of different attributes in some situations, so we cannot just use the scopes or the exposed models would contain properties that do not belong to specific domain models.

However, regardless of the approach, I still feel like this is a bug with the update method that should be fixed.  This specific bug only affects the update command and not others like create

**Comment by papb** [comment]
@a88zach Thanks for the detailed response. Looks complicated indeed. Well, I agree with you, if `update` is the only one acting differently regarding this, it should be changed.

Can you try sushantdhiman's suggestion above and tell us if it works?

**Comment by a88zach** [comment]
@papb, the suggestion above is to make a change in the sequelize source code.  I'm not set up right now, nor have the bandwidth to make/test changes to the source code.

**Comment by papb** [comment]
@a88zach I understand, if later you have the time for it let us know.

If someone else is willing to check it as well, it would be great.
