### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#11369]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'includes' of undefined
    at /etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1418:22
    at Array.map (<anonymous>)
    at MariaDBQueryGenerator.escapeAttributes (/etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1396:37)
    at MariaDBQueryGenerator.selectQuery (/etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1162:28)
    at QueryInterface.select (/etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/query-interface.js:1119:27)
    at /etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/model.js:1754:34
    at tryCatcher (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by knoxcard** [comment]
Nevermind, problem on my end...

```
		var attributes_arr = [],
		   where_arr = []
		attributes_arr.push([type.fn('JSON_VALUE', type.col('blob'), '$.full_name'), 'full_name'])
		attributes_arr.push([type.fn('JSON_EXISTS', type.col('blob'), '$.full_name'), 'full_name_exists'])
		if(typeof(session.id) !== 'undefined') {
			where_arr.push({
				id: {
					[Op.ne]: session.id
				}
			})
		}
```

**Comment by MJB-Khorasani** [comment]
Hi. what's wrong with this code? i can not figure it out.

```
categories = await CategoryModel.findAll({
  group: ["categories"],
  includeIgnoreAttributes: false,
  include: [{ model: PostModel }],
  attributes: [
    'id', 'title', 'createdAt', 'updatedAt', 'describtion'
    [Sequelize.fn("COUNT", Sequelize.col("posts.id")), "postNumber"]
  ]
});
```

i use node.js 12.18.3, postgres 12, sequelize 6.3.0, pg 8.2.1, pg-hstore 2.3.3

**Comment by MJB-Khorasani** [comment]
> Hi. what's wrong with this code? i can not figure it out.
> 
> ```
> categories = await CategoryModel.findAll({
>   group: ["categories"],
>   includeIgnoreAttributes: false,
>   include: [{ model: PostModel }],
>   attributes: [
>     'id', 'title', 'createdAt', 'updatedAt', 'description'
>     [Sequelize.fn("COUNT", Sequelize.col("posts.id")), "postNumber"]
>   ]
> });
> ```
> 
> i use node.js 12.18.3, postgres 12, sequelize 6.3.0, pg 8.2.1, pg-hstore 2.3.3
> 
> it throw the same error
> 
> ```
> TypeError: Cannot read property 'includes' of undefined
>     at /home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1441:22
>     at Array.map (<anonymous>)
>     at PostgresQueryGenerator.escapeAttributes (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1413:37)
>     at PostgresQueryGenerator.selectQuery (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1168:28)
>     at PostgresQueryInterface.select (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-interface.js:939:27)
>     at Function.findAll (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/model.js:1741:47)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async Function.readCategories (/home/mjbkhorasani/money-network/src/services/index.js:190:30)
>     at async getCategories (/home/mjbkhorasani/money-network/src/middlewares/controllers/admin-category.js:14:51)
> ```

All was because of the coma. yes i should use coma after 'description' in attributes.
just a little mistake create a big BUG

**Comment by odravison** [comment]
> > Hi. what's wrong with this code? i can not figure it out.
> > ```
> > categories = await CategoryModel.findAll({
> >   group: ["categories"],
> >   includeIgnoreAttributes: false,
> >   include: [{ model: PostModel }],
> >   attributes: [
> >     'id', 'title', 'createdAt', 'updatedAt', 'description'
> >     [Sequelize.fn("COUNT", Sequelize.col("posts.id")), "postNumber"]
> >   ]
> > });
> > ```
> > 
> > 
> > i use node.js 12.18.3, postgres 12, sequelize 6.3.0, pg 8.2.1, pg-hstore 2.3.3
> > it throw the same error
> > ```
> > TypeError: Cannot read property 'includes' of undefined
> >     at /home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1441:22
> >     at Array.map (<anonymous>)
> >     at PostgresQueryGenerator.escapeAttributes (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1413:37)
> >     at PostgresQueryGenerator.selectQuery (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1168:28)
> >     at PostgresQueryInterface.select (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/dialects/abstract/query-interface.js:939:27)
> >     at Function.findAll (/home/mjbkhorasani/money-network/node_modules/sequelize/lib/model.js:1741:47)
> >     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> >     at async Function.readCategories (/home/mjbkhorasani/money-network/src/services/index.js:190:30)
> >     at async getCategories (/home/mjbkhorasani/money-network/src/middlewares/controllers/admin-category.js:14:51)
> > ```
> 
> All was because of the coma. yes i should use coma after 'description' in attributes.
> just a little mistake create a big BUG

You save me, bro! hahahahhaha ;)
