### ISSUE TITLE
table name pluralize error (staff)

### ISSUE THREAD

**Issue by heekyu** [sequelize/sequelize#11370]
## Issue Description

word 'staff' 's plural format is also 'staff'
but sequelize change this name to 'staffs'

> p = require('pluralize')
> p.plural('staff')
'staff'
> p.plural('apple')
'apples'

### What are you doing?

```js
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Please open this issue on [dreamerslab/node.inflection](https://github.com/dreamerslab/node.inflection). In the meantime you can force the name of the table to be `staff` by using the explicit table name declaration
