### ISSUE TITLE
the value of createdAt and updatedAt is 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by xiabaiyang** [sequelize/sequelize#11375]
## Issue Description
After upgrading from v4 to v5, when the create function is called, the createdAt and updatedAt field is displayed 0000-00-00 00:00:00。
I checked this problem and found out that the problem is in the upgrade code of the v5.0.0-beta.8 version.

From
```js
values.push(this.escape(value, modelAttributeMap && modelAttributeMap[key] || undefined, { context: 'INSERT' }));
```
To
```js
if (value instanceof Utils.SequelizeMethod || options.bindParam === false) {
     values.push(this.escape(value, modelAttributeMap && modelAttributeMap[key] || undefined, { context: 'INSERT' }));
} else {
    values.push(this.format(value, modelAttributeMap && modelAttributeMap[key] || undefined, { context: 'INSERT' }, bindParam));
}
```

### What are you doing?

```js
const XXX = sequelize.define('xxx', {
        ...
        createdAt: {
           type: DataTypes.TIME,
           field: 'created_at',
        },
        updatedAt: {
           type: DataTypes.TIME,
           field: 'updated_at',
        },
       ...
});
```

### What do you expect to happen?

I want the record to show the result as 2019-09-02 17:54:56 after inserting the database.

### What is actually happening?

```
The record to show the result is 0000-00-00 00:00:00.
```

### Environment

- Sequelize version: after 5.0.0-beta.8 
- Node.js version: v10.13.0 
- Operating System: Mac 10.14.4 (18E226)

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Can you provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))?
