### ISSUE TITLE
Typescript issue with date in where

### ISSUE THREAD

**Issue by waypar** [sequelize/sequelize#11381]
## Issue Description
Date types are not accepted as an option in a findAll where.

### What are you doing?

```js
import { Sequelize, Model, DataTypes, BuildOptions } from 'sequelize';

const sequelize = new Sequelize('mysql://root:asd123@localhost:3306/mydb');

// We need to declare an interface for our model that is basically what our class would be
interface MyModel extends Model {
    readonly id: number;
    dt: Date;
  }

  // Need to declare the static model so `findOne` etc. use correct types.
  type MyModelStatic = typeof Model & {
    new (values?: object, options?: BuildOptions): MyModel;
  }

  // TS can't derive a proper class definition from a `.define` call, therefor we need to cast here.
  const MyDefineModel = <MyModelStatic>sequelize.define('MyDefineModel', {
    id: {
      primaryKey: true,
      type: DataTypes.INTEGER.UNSIGNED,
    },
    dt: { type: DataTypes.DATE, allowNull: true },
  });

  function stuffThree() {
    MyDefineModel.findAll({ where: { dt: new Date() } });
  }
```

### What do you expect to happen?

tsc should compile the file without issue.

### What is actually happening?

tsc complains that a Date is not assignable to `WhereAttributeHash`
I feel like `WhereValue` should contain Date, but I assume it is not there for a reason?

```
test.ts:26:29 - error TS2322: Type '{ dt: Date; }' is not assignable to type 'WhereOptions'.
  Type '{ dt: Date; }' is not assignable to type 'WhereAttributeHash'.
    Property 'dt' is incompatible with index signature.
      Type 'Date' is not assignable to type 'string | number | boolean | WhereAttributeHash | AndOperator | OrOperator | Literal | Where | Fn | Col | WhereOperators | WhereGeometryOptions | (string | number | WhereAttributeHash)[]'.
        Type 'Date' is not assignable to type 'WhereAttributeHash'.
          Index signature is missing in type 'Date'.

26     MyDefineModel.findAll({ where: { dt: new Date() } });
                               ~~~~~

  node_modules/sequelize/types/lib/model.d.ts:64:3
    64   where?: WhereOptions;
         ~~~~~
    The expected type comes from property 'where' which is declared here on type 'FindOptions'


Found 1 error.
```

### Environment

- Sequelize version: 5.17.2
- Node.js version: v10.15.3
- Operating System: Ubuntu 18.04.3 LTS
- If TypeScript related: TypeScript version: 3.4.5

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by hzlu** [comment]
I have reached the same error

**Comment by yassernascimento** [comment]
Using the type `FindOptions`; The code:
```
{ where: { my_date_column: { [Op.between]: [dateStart, dateEnd] } }}
``` 
Causes this error:
```
Type '{ [Op.between]: [Date, Date]; }' is not assignable to type 'string | number | boolean | Date | WhereAttributeHash | AndOperator | OrOperator | Literal | Where | Buffer | ... 4 more ... | (string | ... 2 more ... | Buffer)[]'.
  Types of property '[Op.between]' are incompatible.
    Type '[Date, Date]' is not assignable to type 'string | number | boolean | Date | WhereAttributeHash | AndOperator | OrOperator | Literal | Where | Buffer | ... 5 more ... | [...]'.
```

**Comment by obabovic** [comment]
Having the same issue. Trying to compare two dates in the following manner:

```
const appointments = await Appointment.findAll({
  where: {
    dateTime: {
      [Op.between]: [
        moment(this.dateTime).startOf('day').toDate(),
        moment(this.dateTime).endOf('day').toDate()
      ]
    }
  }
});
```

The error that typescript reports is:
```
Type '{ [between]: [Date, Date]; }' is not assignable to type 'string | number | boolean | Date | WhereAttributeHash | Buffer | AndOperator | OrOperator | Literal | ... 6 more ... | null'.
  Types of property '[Op.between]' are incompatible.
    Type '[Date, Date]' is not assignable to type 'string | number | boolean | Date | WhereAttributeHash | Buffer | AndOperator | OrOperator | Literal | ... 8 more ... | undefined'.
      Type '[Date, Date]' is not assignable to type '[number, number]'.
```

**Comment by l2ysho** [comment]
> Having the same issue. Trying to compare two dates in the following manner:
> 
> ```
> const appointments = await Appointment.findAll({
>   where: {
>     dateTime: {
>       [Op.between]: [
>         moment(this.dateTime).startOf('day').toDate(),
>         moment(this.dateTime).endOf('day').toDate()
>       ]
>     }
>   }
> });
> ```
> 
> The error that typescript reports is:
> 
> ```
> Type '{ [between]: [Date, Date]; }' is not assignable to type 'string | number | boolean | Date | WhereAttributeHash | Buffer | AndOperator | OrOperator | Literal | ... 6 more ... | null'.
>   Types of property '[Op.between]' are incompatible.
>     Type '[Date, Date]' is not assignable to type 'string | number | boolean | Date | WhereAttributeHash | Buffer | AndOperator | OrOperator | Literal | ... 8 more ... | undefined'.
>       Type '[Date, Date]' is not assignable to type '[number, number]'.
> ```

I have found a simple workaround, just use alias as unknown (but i think there is missing a Date[] type in definition, or any[])


```
dateTime: {
      [Op.between]: [
        moment(this.dateTime).startOf('day').toDate(),
        moment(this.dateTime).endOf('day').toDate()
      ] as unknown
    }

**Comment by juancarlosgras** [comment]
Try to convert the Date object to string:
```js
MyDefineModel.findAll({
  where: {
    createdAt: {
      [Op.between]: [new Date('2020-02-02').toISOString(), new Date().toISOString()]
    }
  }
})
```
