### ISSUE TITLE
MSSQL newsequentialid() default value

### ISSUE THREAD

**Issue by Palpie** [sequelize/sequelize#11380]
I have a uniqueidentifier column with sequential ID:s using `newsequentialid()` to get the value. How can I use this when inserting with sequelize?

I've tried using it as a defaultValue:

    id: {
        type: 'UNIQUEIDENTIFIER',
        primaryKey: true,
        defaultValue: sequelize.literal('newsequentialid()'),
    }

But that is used in the insert statement which is not allowed and the MSSQL server prevents it. 

I've tried to changed the defaultValue to `sequelize.literal('default')`, but then I get the error `ID cannot represent value: { val: "default" }` from sequelize.

Can I somehow tell sequelize to not include `id` in the insert statement?

**Comment by Palpie** [comment]
If I add `autoIncrement: true` the insert works, but then the id is null afterwards.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
