### ISSUE TITLE
Array-typed field contained Schema Table fails while Sync

### ISSUE THREAD

**Issue by dalisoft** [sequelize/sequelize#11398]
#### `models/Order.ts`

```ts
import { Model as ModelClass, DataTypes, BuildOptions } from 'sequelize';
import uuidv4 from 'uuid/v4';
import sequelize from '../connections/mysql';

export class Model extends ModelClass {
  public id!: string;

  public name: string;

  // ...

  public monitors: string[];

  public costPerMonth: string;
}

type OrderModel = typeof ModelClass & {
  new (values?: object, options?: BuildOptions): Model;
};

const Order = sequelize.define('Order', {
  id: {
    type: DataTypes.UUID,
    defaultValue() {
      return uuidv4();
    },
    primaryKey: true
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false
  },
  // ...
  monitors: {
    type: DataTypes.ARRAY(DataTypes.UUID),
    allowNull: false
    // foreignKey: true
  },
  costPerMonth: {
    type: DataTypes.STRING,
    allowNull: false
  }
  }
}) as OrderModel;

export default Order;
```

#### `connection/mysql.ts`
```ts
const sql = new Sequelize(db, username, password, {/* config here */});

sql
  .sync()
  .catch((err) =>
    console.error(
      'SQL [MySQL::Connection]: Unable to the sync tables from server; ',
      err.message,
      '; with these SQL Query',
      '\n',
      err.parent.sql
    )
  )
  .then(() => sql.authenticate())
  .then(() =>
    console.done(
      'SQL [MySQL::Connection]: ',
      'Connection has been established successfully.'
    )
  )
  .catch((err) =>
    console.error(
      'SQL [MySQL::Connection]: Unable to connect to the database',
      err.message
    )
  );

export default sql;
```

### What do you expect to happen?

Just success sync, nothing more

### What is actually happening?

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[] NOT NULL, `costPerMonth` VARCHAR(255) NOT NULL, `periods` VARCHAR(255)[], `or' at line 1 ; with these SQL Query 
 CREATE TABLE IF NOT EXISTS `Orders` (`id` CHAR(36) BINARY , `name` VARCHAR(255) NOT NULL, `projectId` CHAR(36) BINARY, `userId` CHAR(36) BINARY NOT NULL, `monitors` CHAR(36) BINARY[] NOT NULL, `costPerMonth` VARCHAR(255) NOT NULL, `periods` VARCHAR(255)[], `orderDuration` INTEGER NOT NULL, `type` VARCHAR(255) NOT NULL, `createdAt` VARCHAR(255), PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
```

### Environment

- Sequelize version: `v5.16.0`
- Node.js version: `v12.9.1`
- Operating System: macOS Mojave 10.14.6 
- If TypeScript related: TypeScript version: `v3.5.3`

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): `mysql`
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Your code is too long to be a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)). Is all that really needed to reproduce the issue?

**Comment by dalisoft** [comment]
@papb Thanks for quick response, i am reduced snippet.

**Comment by dalisoft** [comment]
@papb Online linter shows this error
![](http://joxi.ru/823RdG4C9YEPlm?d=1)

So, this is related to Array for MySQL

**Comment by dalisoft** [comment]
Oww, sorry, Array only for Postgres, i tried to use this on MySQL. My fault. Thanks for help and response.
