### ISSUE TITLE
Models are not well type checked

### ISSUE THREAD

**Issue by antoine-pous** [sequelize/sequelize#11397]
## Issue Description
Create a Model and set `allowNull: null` don't throw an error. Setting up to `allowNull: 'hello world'` works too.

### What are you doing?
Something completely dumb

### What do you expect to happen?

Throwing an exception when i put wrong parameters type values.

### What is actually happening?

Nothing, the library don't care about what we do

### Additional context
Nope

### Environment

- Sequelize version: 5.16.0 
- Node.js version: 12.8.0 
- Operating System: MacOS 10.14.6

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by SimonSchick** [comment]
You didn't provide an explicit example, also if you want type safety, use typescript, we are not going to add runtime type assertions to every possible input.
