### ISSUE TITLE
Making allowNull a Function that Has Access to this Context

### ISSUE THREAD

**Issue by Musigwa** [sequelize/sequelize#11401]
## Issue Description

I've been using sequelize with Nodejs, and I loved it's flawless functionality and support of various databases. I especially am a huge fan of customizing the model validation functionality, but I thought that if there may be a way to define `allowNull` as a function that can access `this` context, it would surely help to conditionally validate the model.

### Is your feature request related to a problem? Please describe.
The problem I usually face while validating my model is, I can't allow any of the fields to be null depending on the value any other field(s) may have.

An example would be the following:

When you have a user access level that should allow some of the other fields to be null/optional:
Example:  `isAgent: false` then `email` should be optional.

### Describe the solution you'd like
I'm not sure about the solution, but I think this may be possible by making the `allowNull` either a boolean as it is for now or a function that can access the `this` context. This would enable checking for the other fields' value and then return a boolean value conditionally.
```
const User = sequelize.define(
  "User",
  {
    id: {
      allowNull: false,
      primaryKey: true,
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4
    },
    isAgent: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false
    },
    email: {
      type: DataTypes.STRING,
      allowNull: function() {
        if (this.isAgent) return true;
        else return false;
      },
      validate: { isEmail: true },
      unique: { args: true, msg: "Email address already in use!" }
    }
  },
  {}
);

```

### Why should this be in Sequelize
This is a functionality that can add value to Sequelize model validation and make it a bit stronger than it was.

### Describe alternatives/workarounds you've considered
- None
### Additional context
- None
### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
I had this same problem in the past, it can be done already. See #9143 and [here](https://sequelize.org/master/manual/models-definition.html#per-attribute-validators-and--code-allownull--code-).

**Comment by Musigwa** [comment]
Thanks, @papb I was able to implement it.
