### ISSUE TITLE
How to return simple result of all methods `.create, findAll, .....` (async/await)?

### ISSUE THREAD

**Issue by thearabbit** [sequelize/sequelize#11403]
I base on `Meteor JS`.
I used `async/await`.
How to get the simple/raw result of all methods `create, findAll, .....` 
Example:
```js
Meteor.methods({
  async createEmployee(params) {
    let result = await Employee.create(params)
    console.log(result)

    return result
  },
  async getEmployees() {
    let result = await Employee.findAll()
    console.log(result)

    return result
  },
})
..........
```
Server log

![image](https://user-images.githubusercontent.com/4495160/64483621-ba282600-d22f-11e9-8005-d705e544218a.png)

```js
UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
```
Please help me

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by thearabbit** [comment]
Very thanks for your reply.
