### ISSUE TITLE
I can't fetch data using sequelize model with same id from mysql database 

### ISSUE THREAD

**Issue by edatoprak** [sequelize/sequelize#11407]
Hello,
I have one datagrid table. I can retrieve the data from my database with vuex. I'm bringing data from two tables to this datagrid. One is the product table, the other is the product description table. For a product in my product table, there are two separate rows with two identical ids in the product description. I'm using the sequelize model (orm). But when I bring the data into my datagrid, it only brings one of the same ids.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
