### ISSUE TITLE
Sequelize model is trying to insert null where value is not null

### ISSUE THREAD

**Issue by tareqtms** [sequelize/sequelize#11417]
### What are you doing?

```js
//So here is my Sequelize model, which is a join table between the tables shows and tags (I commented out the associations to make sure that the issue is not with associations):

    module.exports = (sequelize, DataTypes) => {
      const ShowsTag = sequelize.define('ShowsTag', {
        showId: {
          type: DataTypes.BIGINT,
          allowNull: false,
          field: 'show_id'
        },
        tagId: {
          type: DataTypes.BIGINT,
          allowNull: false,
          field: 'tag_id'
        },
        tagConnectType: {
          type: DataTypes.STRING,
          allowNull: true,
          field: 'tag_connect_type'
        }
      }, {
        tableName: 'shows_tags',
        timestamps: true,
        underscored: true
      });
      ShowsTag.associate = function(models) {
        // associations can be defined here
        //models.ShowsTag.belongsTo(models.Tag, {as: 'tag'});
        //models.ShowsTag.belongsTo(models.Show, {as: 'show'});
      };
      return ShowsTag;
    };

 //Here is the code where I am creating a new record:

    db.ShowsTag.create({showId: 3, tagId: 3, tagConnectType: 'channel'}).then(d =>
      console.log(d)
    )
```

### What do you expect to happen?

It should insert with `showId = 3` and `tagId = 3`.

### What is actually happening?

It's sending to database, `showId = null` and `tagId = null`.

_The output was: (Note that `show_id` is equivalent to `showId`, as it is an underscored model)

```
Executing (default): INSERT INTO "shows_tags" ("show_id","tag_id","tag_connect_type","created_at","updated_at") VALUES (NULL,NULL,'channel','2019-09-08 21:51:33.930 +06:00','2019-09-08 21:51:33.930 +06:00') RETURNING *;
Unhandled rejection SequelizeDatabaseError: null value in column "show_id" violates not-null constraint
```

### Environment

- Sequelize version: sequelize@5.15.2 -> sequelize-auto@0.4.29 ->sequelize@3.35.1 
- Node.js version: v10.16.2
- Operating System: MacOS Mojave - 10.14.6 (18G95)
- If TypeScript related: N/A

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect. (I am using Postgres)

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by bclark-systech** [comment]
Having the same problem. I did find a workaround by passing in the fields option. Not sure if this is a bug or a feature.

```
db.OrganizationContact.create(
     { organizationId: 123, accountContactId: 456 },
     { fields: ["organizationId", "accountContactId"] }
);
```

**Comment by gon-escalante** [comment]
adding the primaryKey attribute to one of the fields in model solved this issue for me, there seems to be a problem with the underscored fields

**Comment by papb** [comment]
Closing in favor of #11225

**Comment by normandanielmq** [comment]
This is still a thing.

**Comment by ephys** [comment]
Can you open a new issue with the information the template will request and a SSCCE?

**Comment by fhyfr** [comment]
I still have this issue, I use "sequelize": "^6.28.0".

**Comment by tovaru** [comment]
I had this issue because I was using [super many-to-many](https://sequelize.org/docs/v6/advanced-association-concepts/advanced-many-to-many/#the-best-of-both-worlds-the-super-many-to-many-relationship), where I defined both hasMany and belongsToMany between tables. 

I solved it by changing the order in which I define relations; by setting belongsToMany before hasMany.

**Comment by egmontaska** [comment]
Had this issue in many-to-many relation while models having property `underscore: true`. Resolved by adding foreignKey property to association definition.
Before:
```
User.belongsToMany(Company, {
  through: CompanyUser,
  as: 'companies'
})

Company.belongsToMany(User, {
  through: CompanyUser,
  as: 'users'
})
```
After:
```
User.belongsToMany(Company, {
  through: CompanyUser,
  as: 'companies',
  foreignKey: 'user_id'
})

Company.belongsToMany(User, {
  through: CompanyUser,
  as: 'users',
  foreignKey: 'company_id'
})
```
