### ISSUE TITLE
Possibilty to define UID for MSSQL

### ISSUE THREAD

**Issue by Rednas83** [sequelize/sequelize#11413]
## Issue Description
Looking at the documentation it is currently not possible to define you're own id for the dialect "MSSQL", because it is automatically generated only.

> Sequelize.UUID                        // UUID datatype for PostgreSQL and SQLite, CHAR(36) BINARY for MySQL (use defaultValue: Sequelize.UUIDV1 or Sequelize.UUIDV4 to make sequelize generate the ids automatically)

### Describe the solution you'd like
Add support for defining custom id for the dialect "MSSQL"

```js
// If applicable, add a code snippet showing how your feature would be used in a real use-case
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [X] Yes. This issue only applies to the following dialect(s): MSSQL

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
I didn't understand. I think this is a misunderstanding. Doesn't the following work?

```js
const Foo = sequelize.define('foo', {
  id: {
    type: DataTypes.INTEGER
    primaryKey: true,
    allowNull: false,
    autoIncrement: true
  }
});
```

I'm pretty sure the above should work. If it doesn't please clarify the problem and I will reopen the issue.
