### ISSUE TITLE
Combine Two or more queries using UNION DISTINCT In sequelize.

### ISSUE THREAD

**Issue by Hammza1** [sequelize/sequelize#11414]
## Issue Description
Sequelize support of the UNION DISTINCT Operation

### Is your feature request related to a problem? Please describe.
I am trying to perform two queries at once time, but I do not find any support in sequelize docs.

### Describe the solution you'd like

```js
// If applicable, add a code snippet showing how your feature would be used in a real use-case
```

### Why should this be in Sequelize
Short explanation why this should be part of Sequelize rather than a separate package.

### Describe alternatives/workarounds you've considered
A clear and concise description of any alternative solutions or features you've considered. If any workaround exists to the best of your knowledge, include it here.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Please fill the issue template completely
