### ISSUE TITLE
Timestamp inserting wrong date on database Postgres

### ISSUE THREAD

**Issue by astrO1** [sequelize/sequelize#11411]
## Issue Description
I have an application that makes a simple insert, but when I insert Sequelize stores a wrong date to my database 
### What are you doing?

```js
// CONFIGURATION CODE
const options = {
      operatorsAliases: false,
      dialect: tenants.db_username,
      host: tenants.db_host,
      logging: false,
      dialectOptions: {
        useUTC: true,
      },
      timezone: 'America/Sao_Paulo',
    };
    const databaseConfig = {
      db: {
        database: tenants.db_name,
        user: tenants.db_username,
        password: tenants.db_password,
        options,
        pool: {
          max: 5,
          min: 0,
          acquire: 30000,
          idle: 10000,
        },
      },
    };


// INSERTING CODE
async storeAction(action) {
    try {
      console.log(action);
      const res = await this.model.action.create(action, { logging: console.log });
      return res;
    } catch (error) {
      throw error;
    }
  }
```

This is the log that is showing to me

```
// This is the log that is showing to me
{ user_id: 2,
  action_lat: -8.0277473,
  action_long: -34.8955087,
  action_time: '2019-09-09 19:06:32',
  action_type: 'ENTRADA',
  action_obs: '' }
Executing (default): INSERT INTO "pb_action" ("action_id","action_lat","action_long","action_time","action_type","action_obs","createdAt","updatedAt","user_id") VALUES (DEFAULT,-8.0277473,-34.8955087,'2019-09-09 19:06:32.000 -03:00','ENTRADA','','2019-09-09 19:06:59.825 -03:00','2019-09-09 19:06:59.825 -03:00',2) RETURNING *;
```
### What do you expect to happen?

I'm expecting that in my database store a createdAt date like this **'2019-09-09 19:06:59.825 -03:00'** like the select above

### What is actually happening?

Sequelize is storing a wrong date like this **2019-09-09 22:06:59.825+00** + 3 hours from my correct time to all fields DATE type like action_time, createdAt ( automatic field created by Sequelize ) and updatedAt ( automatic field created by Sequelize ) 

### Additional context
Don't need

### Environment

- Sequelize version: sequelize@4.44.3
- Node.js version: v10.16.0
- Operating System: Ubuntu
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by fauker** [comment]
Same here.

**Comment by papb** [comment]
Hello! You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

Also, a few more things:

Have you double-checked the timezone configuration in your sequelize constructor? 

> I think this problem happens only for the following dialect(s): Postgres

Why?

> Yes, I have the time and I know how to start.

Great! Thanks! Please reply to my questions above before starting to work on a PR though.
