### ISSUE TITLE
Not crash on startup when connect ECONNREFUSED

### ISSUE THREAD

**Issue by heekyu** [sequelize/sequelize#11412]
## Issue Description

Sequelize version : 5.8.12

on initializing sequelize,
if database server is not running, app crashes.
I want not to crash and want to run well even after late database server up.

But node process terminates with follwing error
[UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432]
at connection.connect.err (/Users/heekyu/medi/git/ehr/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:170:24)
    at Connection.connectingErrorHandler (/Users/heekyu/medi/git/ehr/node_modules/pg/lib/client.js:191:14)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.reportStreamError (/Users/heekyu/medi/git/ehr/node_modules/pg/lib/connection.js:72:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

source code:
var sequelize = new _sequelize.Sequelize(database, user, password, _objectSpread({
    dialect: dialect,
    host: host,
    logging: console.log,
    pool: {
      acquire: 30000,
      idle: 10000,
      max: 10,
      min: 0
    }
  }, props));

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: I'm always frustrated when [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. How can the requested feature be used to approach the problem it's supposed to solve?

```js
// If applicable, add a code snippet showing how your feature would be used in a real use-case
```

### Why should this be in Sequelize
Short explanation why this should be part of Sequelize rather than a separate package.

### Describe alternatives/workarounds you've considered
A clear and concise description of any alternative solutions or features you've considered. If any workaround exists to the best of your knowledge, include it here.

### Is this issue dialect-specific?

- [O] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [O] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, this is the expected behavior. I don't think we will be adding support for this directly in Sequelize. If you want to wait for the server automatically, you should create your own code to handle this, perhaps using a tool like [wait-on](https://github.com/jeffbski/wait-on), [wait-for](https://github.com/eficode/wait-for) or [wait-for-it](https://github.com/vishnubob/wait-for-it) (or roll your own). Good luck.

**Comment by jedwards1211** [comment]
@papb but this also seems to happen later if the database goes down...a connection pool is supposed to gracefully recover when the database comes back up, not crash the app.  We should at least be able to catch this error
