### ISSUE TITLE
Warning about incorrect timezone passed to connection

### ISSUE THREAD

**Issue by snax4a** [sequelize/sequelize#11426]
## Issue Description
Sequelize v5.18.4 gives me this warning when i pass this in my configuration options ```"timezone": "Europe/Warsaw"```
"Ignoring invalid timezone passed to Connection: Europe/Warsaw. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection"

### What are you doing?
I just try queries with different timezones set in sequelize configuration, for example: ```America/New_York``` ```Europe/Warsaw``` or ```SYSTEM```
The warning is saying that it is ignoring invalid timezone but it is actually not ignoring it because everything works, when I change timezones i get proper dates.

### What do you expect to happen?

I want to get rid of that warning. 

### Environment

- Sequelize version: sequelize@5.18.4
- Node.js version: v10.16.1
- Operating System: OSX

### How does this problem relate to dialects?

- [x] I think this problem happens only for the following dialect(s): MySQL

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by papb** [comment]
Hello, thanks for the report. However, I am a bit confused, do you get this warning only for `Europe/Warsaw` or do you get it for whatever value you put there?

**Comment by snax4a** [comment]
I got it for all the values, I tried with different timezones.

Yes it might be an issue with mysql its just strange that changing timezone works.

**Comment by papb** [comment]
I confirmed this is not on sequelize: [here](https://github.com/sidorares/node-mysql2/blob/c460c0fe9c9b47282f573801f6e883913752916f/lib/connection_config.js#L70)

**Comment by Seth10001** [comment]
Doesn't appear that mysql2 has fixed this yet, did anyone find a workaround?

**Comment by Truth1984** [comment]
"+08:00" / "-08:00"
