### ISSUE TITLE
"String cannot represent value" issue

### ISSUE THREAD

**Issue by jayragshukla** [sequelize/sequelize#11428]
## Issue Description
I'm trying to have ssl connection with postgress hosted on cloud using sequelize but consistently getting "String cannot represent value" error.

### What are you doing?

Plugins used:
node: 8.10
"pg": "^7.8.0",
"pg-hstore": "^2.3.2",
"sequelize": "^5.7.5"

// connect sequelize
const dbconf = {
      host: process.env.PG_DB_HOST,
      port: parseInt(process.env.PG_DB_PORT),
      ssl: true,
      native: false,
      pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000
      },
      dialect: 'postgres',
      protocol: 'postgres',
      dialectModule: require('pg'),
      dialectOptions: { ssl: true }
    };
const sequelize = new Sequelize(process.env.PG_DB_NAME, secureProperties[process.env.PG_DB_USER_SECRET_KEY], token, dbconf);
this.Sequelize = Sequelize;
this.sequelize = sequelize;
this.FormMap = require('./models/FormMap')(sequelize, Sequelize);

//model
const FormMap = sequelize.define('FormMap', 
  {
...........all columns using 
DataTypes.INTEGER
DataTypes.DATE
DataTypes.STRING
DataTypes.UUID ---------
},
  {
    timestamps: true,
    underscored: true,
    freezeTableName: true,
    tableName: 'form_map',
    schema: 'test',
    createdAt: 'createTs',
    updatedAt: 'updateTs',
    deletedAt: false
  });
  return FormMap;
};

Response received:
{
  "errors": [
    {
      "message": "String cannot represent value: { dataValues: { formTestId: \"1d08b388-a739-11e9-853e-0e4911960a36\", asmtForkId: \"5748460\", createBy: \"392\", createTs: {}, updateBy: \"392\", updateTs: {} }, _changed: {}, _modelOptions: { timestamps: true, validate: {}, freezeTableName: true, underscored: true, paranoid: false, rejectOnEmpty: false, whereCollection: [Object], schema: \"test\", schemaDelimiter: \"\", defaultScope: {}, scopes: {}, indexes: [], name: [Object], omitNull: false, tableName: \"test_map\", createdAt: \"createTs\", updatedAt: \"updateTs\", deletedAt: false, sequelize: [O], hooks: {} }, _options: { isNewRecord: false, _schema: \"test\", _schemaDelimiter: \"\", raw: true, attributes: [Array] }, isNewRecord: false }",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ],
      "path": [
        "greet"
      ]
    }
  ],
  "data": null
}

```js
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

Should return valid json document with no error

_I wanted Foo!_

### What is actually happening?

response errored out

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Please [learn to format your issue using Markdown](https://guides.github.com/features/mastering-markdown/) and fill the issue template completely.

**Comment by sujin-lifology** [comment]
Please post the error not some full bullshits
