### ISSUE TITLE
sequelize instance does not have a Model field (import docs)

### ISSUE THREAD

**Issue by masterl** [sequelize/sequelize#11424]
## Issue Description

The [import docs](https://sequelize.org/master/manual/models-definition.html#import) present a wrong code:

```js
module.exports = (sequelize, DataTypes) => {
  class Project extends sequelize.Model { }
```

### What was unclear/insufficient/not covered in the documentation

The problem here is that there is no field called `Model` on the `sequelize` instance.

### If possible: Provide some suggestion on how we can enhance the docs

Throughout the docs, `sequelize` is used for the `Sequelize` instance.
And `Sequelize` is used for what we get when we `require('sequelize')`.
Since `Model` is a part of `Sequelize` (with capital S), this part of the doc should be rewritten to `Sequelize.Model`.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thanks! I will fix this while I'm making the other docs changes.
