### ISSUE TITLE
Error processing include elements

### ISSUE THREAD

**Issue by AndreiPanasuk** [sequelize/sequelize#11422]
An error occurs when generating a request when processing calculated attributes include elements in module lib/models.js, line 591 
currently 
`include.originalAttributes = this._injectDependentVirtualAttributes(include.attributes);`

should be
`include.originalAttributes = include.model._injectDependentVirtualAttributes(include.attributes);`

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.
