### ISSUE TITLE
Destroy records with many to many relationship does not delete the records in through Table

### ISSUE THREAD

**Issue by Xilesun** [sequelize/sequelize#11435]
## Issue Description

The Association part of the doc is really misunderstanding. How to delete a record with many to many relationship and the record in through table at the same time?

### What are you doing?

I am trying to destory some records with many to many relationship and the following are the codes: 

The models

```js
User.belongsToMany(models.folder, { through: models.userFolder })
Folder.belongsToMany(models.user, { through: models.userFolder })
Folder.belongsToMany(models.guide, { through: models.guideFolder, onDelete: 'cascade', hooks: true })
Guide.belongsToMany(models.folder, { through: models.guideFolder })
```

The destroy code:

```js
sequelize.transaction(async (t) => {
    try {
      let folder = await db.folder.findOne({ where: { id: folderId }})
      await user.removeFolder(folder, { transaction: t })
      await folder.destroy({ transaction: t })
    } catch (err) {
      throw err
    }
})
```

### What do you expect to happen?

userFolder: the relationship record is removed
Folder: the record is removed
Guide: the records belong to the folder are removed
guideFolder: the relationship records are removed

### What is actually happening?

userFolder: the relationship record is removed
Folder: the record is removed
Guide: the records belong to the folder are removed
guideFolder: the relationship records are still exist

### Environment

- Sequelize version: 5.17.1

**Comment by papb** [comment]
Hello!

> The Association part of the doc is really misunderstanding

I agree! I am currently working in heavily improving the whole docs. Stay tuned.

Now, for your question: from your description, the only thing that happened and you didn't expect is:

> guideFolder: the relationship records are still exist

Just to make sure I understand: since the record itself was deleted, this guide-folder relation becomes invalid, right? Therefore you think the guide-folder record should be deleted as well, is this correct? Did I miss something?

Also, does the `onDelete: 'cascade'` is your code mean something or is it just leftover code?

**Comment by Xilesun** [comment]
@papb Thanks for replying. 

> Therefore you think the guide-folder record should be deleted as well, is this correct? Did I miss something?

Right. Actually, I try to find an easy way to do things like this:

Users and folders have many to many relationship, folders and articles also have many to many relationship. When a user delete a folder, the record in two through tables (userFolder, guideFolder) and the record in Folder table are deleted, as well as all records in Guide table which belong to the folder.

> Also, does the onDelete: 'cascade' is your code mean something or is it just leftover code?

Since folders and articles have many to many relationship, I think `onDelete: 'cascade', hooks: true` can remove all the articles belong to the folder when `folder.destroy()` triggers.

**Comment by ajmueller** [comment]
@Xilesun I see you have `hooks: true` set in just one of your association definitions.  Do you find that those hooks get run?  I'm looking all over to try and find others who have run into issues with hooks getting run on the through table of a many-to-many relationship and found this issue you filed.

@papb is it a known issue that the through table of a many-to-many relationship doesn't have its destroy hooks run when its associated model has rows destroyed?

**Comment by ulisesBasurto** [comment]
Hello.
You can try with ....
// remove the association with task1
project.setTasks([task2]).then(associatedTasks => {
  // you will get task2 only
})

// remove 'em all
project.setTasks([]).then(associatedTasks => {
  // you will get an empty array
})

// or remove 'em more directly
project.removeTask(task1).then(() => {
  // it's gone
})

Documentation: https://sequelize.org/v5/manual/associations.html#belongs-to-many-associations
