### ISSUE TITLE
Property 'getDatabaseName' does not exist on type 'Sequelize'.

### ISSUE THREAD

**Issue by scottsj** [sequelize/sequelize#11431]
## Issue Description

Trying to call `getDatabaseName` using Sequelize with Typescript however the method is not declared in `sequelize.d.ts`

### What are you doing?

```js
import { Sequelize, Model, DataTypes } from 'sequelize';

const sequelize: Sequelize = new Sequelize(
    ...
);
sequelize
  .authenticate()
  .then(() => {
    log.info(`Successfully connected to database '${sequelize.getDatabaseName()}'
  })

```

### What do you expect to happen?

Function already declared

### What is actually happening?

TS Compile error
(other methods like getDialect are declared and work fine)

### Environment

- Sequelize version: `sequelize@5.18.4`
- Node.js version: `v10.15.1`
- Operating System: MacOS 
- TypeScript version: `typescript@3.6.3`
- dialect: postgres
### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- I think I could find the time and means to do this

**Comment by papb** [comment]
Thanks for the report.

> I think I could find the time and means to do this

Awesome!! Please do. Also, I recommend you take a look on these PRs to see how we prefer typings PRs to be done:

* https://github.com/sequelize/sequelize/pull/11115/files
* https://github.com/sequelize/sequelize/pull/11379/files

As you can see, it's easy :grimacing: Thanks!!
