### ISSUE TITLE
Deleting single instance removes multiple records

### ISSUE THREAD

**Issue by bclark-systech** [sequelize/sequelize#11448]
## Issue Description

When destroying a many to many through instance, multiple records where removed. It appears the where clause that was originally used to find the instance, is then used to delete. Problem is, if your where query matches many records, and only want to delete one, they are all deleted.

This is the intermediate table linking the tables together. I also noticed I could not access the id of the instance, so maybe this is how its suppose to work?

### What are you doing?

```js

found = await org.getOrganizationContacts(
    { where: { accountContactId: ctx.params.contactId }, limit: 1 });

await found[0].destroy();

```

### What do you expect to happen?

I would expect only the single instance to be removed.

### What is actually happening?

Its removing all records in the db that match the original where clause

```sql
SELECT "organization_id" AS "organizationId", "account_contact_id" AS "accountContactId", "created_at" AS "createdAt", "updated_at" AS "updatedAt", "account_contact_id" AS "AccountContactId", "organization_id" AS "OrganizationId" FROM "organization_contacts" AS "OrganizationContact" WHERE ("OrganizationContact"."organization_id" = 1 AND "OrganizationContact"."account_contact_id" = '10') LIMIT 1;

DELETE FROM "organization_contacts" WHERE "account_contact_id" = 10 AND "organization_id" = 1
```

### Additional context

I will try to do further debugging in the next couple days to provide more information.

### Environment

- Sequelize version: sequelize@5.18.4
- Node.js version: 10.16
- Operating System: Alpine Linux Docker

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello! You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

**Comment by bclark-systech** [comment]
After doing more testing and reading through source code, it appears this is not really a bug. I resolved the issue by adding the id field into model definition. I missed that part in the docs.

**Comment by papb** [comment]
@bclark-systech Wait, if I understood the problem correctly, I don't want this issue to be closed, even though you found a solution, the behavior is very weird. I will try to reproduce later, and will tag this appropriately as a bug or docs issue.

**Comment by bclark-systech** [comment]
In the docs it says

> By default the code above will add projectId and userId to the UserProjects table, and remove any previously defined primary key attribute - the table will be uniquely identified by the combination of the keys of the two tables, and there is no reason to have other PK columns. To enforce a primary key on the UserProjects model you can add it manually. 
https://sequelize.org/master/manual/associations.html#belongs-to-many-associations

I had already created my through tables manually, with a primary key, once i added the code below to my model, then everything worked as expected. 
```
id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
```

**Comment by papb** [comment]
I see! Thanks!! I will still leave this as a docs issue to see if I can further improve it :+1:

**Comment by ephys** [comment]
I'll close this issue, once https://github.com/sequelize/sequelize/issues/14402 is implemented, calling that method on a model that does not have a primary key will print a clear error
