### ISSUE TITLE
findByPk doesn't consider rejectOnEmpty when parameter is null or undefined

### ISSUE THREAD

**Issue by talyssonoc** [sequelize/sequelize#11449]
### What are you doing?

I'm running a `findByPk` query that may receive a `null` as argument with the `rejectOnEmpty` option set to true:

```js
  const userId = null;
  await User.findByPk(userId, { rejectOnEmpty: true });
```

### What do you expect to happen?

I expected that Sequelize would throw a `SequelizeEmptyResultError` since this query will never return a value.

### What is actually happening?

It returns `null`.

### Additional context

I see this is intentional and explicit here https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1872-L1874

### Environment

- Sequelize version: 5.14.0
- Node.js version: 12.9.0
- Operating System: Ubuntu 18.04.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thanks for the report, I don't have the time to look into it right now but will do later. Feel free to ping me if it looks like I am taking too long.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/9341#issuecomment-386343308

I don't think it should be changed, `SequelizeEmptyResultError` means we queried but no record was found.

ECMA `null / undefined` are invalid `pk` values (as sane assumption). As we can't query them, we simply resolve `null`

**Comment by papb** [comment]
Indeed, that makes sense. However, this makes me think we should have some sanity checks on the inputs of our methods... For example, I think `User.findByPk(null)` should probably throw a `TypeError` regardless of the `rejectOnEmpty` option. What do you think?

**Comment by talyssonoc** [comment]
@sushantdhiman I agree with you about being a valid pk value, but it won't be a valid value depending of the dialect, maybe this could be dialect dependent then?

I like @papb's idea as well.
