### ISSUE TITLE
Sequelize v5 ignoring pool min option?!

### ISSUE THREAD

**Issue by Jasenkoo** [sequelize/sequelize#11440]
## Issue Description

Recently I used sequelize v4.44.3 and updated to 5.18.4. In my sequelize configuration, I've set 

```js
pool: {
    min: 10,
    max: 30
}
```
The problem is that on v4 sequelize keeps at least 10 connection and on v5 only 2.

### What are you doing?

**dbConfig.js**

```js
module.exports = {
    username: process.env['DB_USERNAME'],
    password: process.env['DB_PASSWORD'],
    database: process.env['DB_NAME'],
     host: process.env['DB_HOST'],
     dialect: 'postgres',
     seederStorage: 'sequelize',
     pool: {
          min: 10,
          max: 30,
     },
};
```
**in the singleton**
```js
const { database, username, password, ...options } = dbConfig;
const sequelize = new Sequelize(database, username, password, options);
```

Executing following command in pgAdmin I noticed the issue

```sql
SELECT * FROM pg_stat_activity;
```

### What do you expect to happen?

_To have 10 open connection to my database_

### What is actually happening?

_Only 2 connections shown_

The main reason why I am submitting this as an issue is that on v4 with the same configuration it works without problems. In the changelog, I didn't see any braking changes regarding this, only that it now uses sequelize-pool.

### Environment

- Sequelize version: 5.18.4
- Node.js version: 10.16.0
- Operating System: Ubuntu 19.04
- PostgreSQL: 9.6.15

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thank you for the detailed report, I will try to reproduce it soon

**Comment by Shahor** [comment]
I have the same issue.

Just started testing increasing the pool minimum connections by increasing to 800.

This is what I see in my connection graphs: 

![image](https://user-images.githubusercontent.com/204561/77652369-646a5f80-6f6e-11ea-90c3-7621b4605342.png)

**Comment by SergeyCherman** [comment]
@papb I tried to fix this so I could issue a PR but I'm not sure where the best place for the logic to be. Should it be inside the the sequelize pool to ensure and ensureMinimum after acquiring, or should each connect method create as many as the min pool config? 

If you could point me in the right direction I could try to contribute.

**Comment by tyzion** [comment]
Hey, I'm still having this issue.

The min option doesn't work for me too

**Comment by ephys** [comment]
This issue is for a very old version of Sequelize, please open a new issue if you're still encountering this issue in the latest version of sequelize 6 or 7

**Comment by WikiRik** [comment]
It was mentioned before, but conversation about this issue can continue in https://github.com/sequelize/sequelize-pool/issues/22
