### ISSUE TITLE
beforeDisconnect and afterDisconnect are auto called when it is connected

### ISSUE THREAD

**Issue by msheep** [sequelize/sequelize#11442]
Hi, could I know why beforeDisconnect and afterDisconnect are auto called even it is not disconnected? Thank you!
![501568681848_ pic](https://user-images.githubusercontent.com/3865432/65003051-06631c80-d93a-11e9-9b93-d8959a8a660f.jpg)

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
