### ISSUE TITLE
Sequelize.where col not null

### ISSUE THREAD

**Issue by dodderjs** [sequelize/sequelize#11447]
## Issue Description

Can't query col is not NULL with Sequelize.where function.

### What are you doing?
Write a select query with the following where state.

```
where: [{}, 
    sequelize.where(sequelize.col('id'), Op.ne, null),
    {'id': {
        [Op.ne]: null
    }}]
```

### What do you expect to happen?

The first one is for not getting `literal replacements` error but it's a different topic.
Second and the third object should generate the same `id IS NOT NULL`.

### What is actually happening?

The second (`sequelize.where(sequelize.col('id'), Op.ne, null)`) generate `id IS NULL`.

```
id IS NULL AND id IS NOT NULL
```

### Environment

- Sequelize version: 5.18.4 
- Node.js version: v12.0.0
- Operating System: OSX -> Docker node:12.0 container
- MySql version: 5.7.23

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MySQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello! You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

**Comment by papb** [comment]
Also:

> The first one is for not getting `literal replacements` error but it's a different topic.

I would like to know more about this, can you open another issue about this please? Thank you very much!!

**Comment by dodderjs** [comment]
Hello,

Just copy and past it to the `getWhereConditions` unit test in `test/unit/sql/where.test.js` file:

```
    testsql(current.where(current.col('name'), Op.ne, null), {
      default: '[name] IS NOT NULL'
    });

    testsql(current.where(current.fn('lower', current.col('name')), Op.ne, null), {
      default: 'lower([name]) IS NOT NULL'
    });
```

Correct me if I'm wrong but it should pass.

**Comment by dodderjs** [comment]
> Also:
> 
> > The first one is for not getting `literal replacements` error but it's a different topic.
> 
> I would like to know more about this, can you open another issue about this please? Thank you very much!!

https://github.com/sequelize/sequelize/issues/11452

**Comment by papb** [comment]
@dodderjs I will take a look into it later.
