### ISSUE TITLE
hooks beforeQuery and afterQuery are not supported on ts 

### ISSUE THREAD

**Issue by msheep** [sequelize/sequelize#11441]
Hi, I want to use beforeQuery and afterQuery hooks on my typescript project but I found they are not included in the hooks.d.ts. I noticed that hooks.js contains these functions. 

BTW, could I know why beforeDisconnect and  afterDisconnect are auto called even it is not disconnected? Thank you!

**Comment by papb** [comment]
> Hi, I want to use beforeQuery and afterQuery hooks on my typescript project but I found they are not included in the hooks.d.ts. I noticed that hooks.js contains these functions.

Understood, thanks for reporting!

> BTW, could I know why beforeDisconnect and afterDisconnect are auto called even it is not disconnected? Thank you!

Can you please open a new issue showing with a SSCCE an example of this happening?

**Comment by msheep** [comment]
> > Hi, I want to use beforeQuery and afterQuery hooks on my typescript project but I found they are not included in the hooks.d.ts. I noticed that hooks.js contains these functions.
> 
> Understood, thanks for reporting!
> 
> > BTW, could I know why beforeDisconnect and afterDisconnect are auto called even it is not disconnected? Thank you!
> 
> Can you please open a new issue showing with a SSCCE an example of this happening?

Of course

**Comment by wallzero** [comment]
I am trying to run a function before and after every query and I am also running into this issue. `beforeQuery` and `afterQuery` are included in `hooks.js` [v5](https://github.com/sequelize/sequelize/blob/v5/lib/hooks.js) and the upcoming [v6](https://github.com/sequelize/sequelize/blob/v6/lib/hooks.js) but missing in `hooks.d.ts` for [v5](https://github.com/sequelize/sequelize/blob/v5/types/lib/hooks.d.ts) and  [v6](https://github.com/sequelize/sequelize/blob/v6/types/lib/hooks.d.ts).
