### ISSUE TITLE
Mapping a column/field to the same name in a query causes the field to be omitted

### ISSUE THREAD

**Issue by cressie176** [sequelize/sequelize#11458]
## Issue Description
Mapping a column/field to the same name in a query causes the field to be omitted from the response.

### What are you doing?
```js
const Sequelize = require('sequelize');
const assert = require('assert');

const sequelize = new Sequelize('postgres', 'postgres', 'password', {
  dialect: 'postgres',
  host: 'localhost',
});
sequelize.query("SELECT 'Star Wars' AS title, 1977 AS year_of_release", {
  type: 'SELECT',
  fieldMap: {
    title: 'title',
    year_of_release: 'yearOfRelease',
  },
}).then((rows) => {
  assert.deepEqual(rows, [{ title: 'Star Wars', yearOfRelease: 1977 }])
});

setInterval(() => {}, Number.MAX_SAFE_INTEGER)
```

### What do you expect to happen?

The `title` field should have been mapped.

### What is actually happening?

The `title` field was deleted from the output

```
Unhandled rejection AssertionError [ERR_ASSERTION]: [ { yearOfRelease: 1977 } ] deepEqual [ { title: 'Star Wars', yearOfRelease: 1977 } ]
```

### Additional context
We can work around by removing columns that do not need to be mapped, but this makes it slightly harder to see the columns returned from a query. The cause of the deletion is [this](https://github.com/sequelize/sequelize/blob/8b53f721a07e4ea5a42d74199b319f813f2c109c/lib/dialects/abstract/query.js#L253) line. I would be happy to create a PR where either
1. The field is only deleted if the name field differ
2. A new object is returned rather than mutating the existing one (I would be concerned about performance / memory for large queries) 

### Environment

- Sequelize version: sequelize@5.18.4 
- Node.js version: v8.11.3
- Operating System: osx

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please submit a PR if you can :)

**Comment by cressie176** [comment]
Will do

**Comment by gwpmad** [comment]
PR: https://github.com/sequelize/sequelize/pull/11492
