### ISSUE TITLE
update sequelize v5 cannot use sequelize-comment

### ISSUE THREAD

**Issue by LiZhouYang5612** [sequelize/sequelize#11455]
These Sequelize methods will generate SQL fragments that then include (starts with) comments that look like this:
`/* DEBUG: Running a SELECT command. */ SELECT ...
/* DEBUG: Running an INSERT command. */ INSERT INTO ...
/* DEBUG: Running an UPDATE command. */ UPDATE ...`
I want to print some useful information，such as the project name。
It can easily locate sql information to which project in our log platform

**Comment by papb** [comment]
Closing this as a [sequelize-comment issue](https://github.com/bennadel/sequelize-comment/issues/5).
