### ISSUE TITLE
v6: make documentation mobile friendly

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#11453]

**Comment by soryy708** [comment]
Where does this need to be implemented? [here](https://github.com/sequelize/sequelize.org) or [here](https://github.com/sequelize/sequelize/tree/master/docs)?

**Comment by sushantdhiman** [comment]
@soryy708 Documentation is generated in this main repository, https://github.com/sequelize/sequelize/tree/master/docs this is based on https://esdoc.org/

Look at `css` folder, we need to add appropriate styles in there

**Comment by soryy708** [comment]
Alright. I can take this on myself and make a PR.

**Comment by soryy708** [comment]
Are we concerned about browser support? If yes, what version(s) of what browsers?

**Comment by soryy708** [comment]
ESDoc is dead. Maybe migrate to something else?
