### ISSUE TITLE
Conversion failed when converting date and/or time from character string.

### ISSUE THREAD

**Issue by ghmd86** [sequelize/sequelize#11460]
I am trying to update/insert a datetime stamp value in a table, I am getting the 'Conversion failed when converting date and/or time from character string':
Example for an update code:
CODE:
 ```js
 return userTableDto.update({
                        'firstName': user.firstName,
                        'lastName': user.lastName,
                        'LastUpdatedBy': user.lastUpdatedBy,
                        'LastUpdatedOn': new Date()
                    }).then((userDtoResult: UserDto) => {
                                resolve(userDtoResult);
             });
```
### What do you expect to happen?
I expect it to store / update the value.

### What is actually happening?
It is throwing an SequelizeDatabaseError error with following message:

'Conversion failed when converting date and/or time from character string.'
ERROR I get:
message: 'Conversion failed when converting date and/or time from character string.',
code: 'EREQUEST',
number: 241,
state: 1,
class: 16,
serverName: 'sqlServerDev',
procName: '',
lineNumber: 1,
sql: 'UPDATE [UserTable] SET [LastUpdatedOn]=@0 OUTPUT INSERTED.* WHERE [userId] = @1',
parameters:
       { '0': '2019-09-20 16:58:52.256 +00:00',
         '1': 'E1000C5A-43E1-4F52-88A1-4EE6A869FE28' } },
  original:
    { RequestError: Conversion failed when converting date and/or time from character string.
     at Parser.tokenStreamParser.on.token (C:\...\node_modules\tedious\lib\connection.js:779:27)

### Environment

- Sequelize version: 5.19.0 
- Node.js version: v8.16.0 
- Operating System: Windows 10 64bit
- If TypeScript related: TypeScript version: 3.3.3333
- sequelize-typescript: 1.0.0
### How does this problem relate to dialects?
mssql

- [ ] I think this problem happens regardless of the dialect.
- [Y] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [N] No, I don't have the time and I wouldn't even know how to start.

**Comment by ghmd86** [comment]
I used the following and it resolved the issue:
'LastUpdatedOn': Sequelize.fn('GETDATE')

**Comment by jose-aguirre-global** [comment]
> I used the following and it resolved the issue:
> 'LastUpdatedOn': Sequelize.fn('GETDATE')

Muchas gracias, me sirvió!

**Comment by ghmd86** [comment]
> > I used the following and it resolved the issue:
> > 'LastUpdatedOn': Sequelize.fn('GETDATE')
> 
> Muchas gracias, me sirvió!

Or you can try this method too: https://stackoverflow.com/questions/58034185/inserting-or-updating-a-date-field-give-the-following-error-conversion-failed-wh
