### ISSUE TITLE
Require references wrong

### ISSUE THREAD

**Issue by cskiwi** [sequelize/sequelize#11466]
### What are you doing?

When adding sequelize to a netlify lambda project, the project has it's references wrong (I think)
reproduction:

- clone from: https://github.com/netlify/create-react-app-lambda.git
- add sequelize `yarn add sequelize sqlite3`
- add following code to one of the 2 functions in the `src/lambda` folder:
```js
const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: './db.sqlite'
});
```

### What do you expect to happen?

When going to `http://localhost:8888/.netlify/functions/<your used function>`
Should initialize a sequelize instance 

### What is actually happening?

I get an error that a package is not installed

```
Error: Please install sqlite3 package manually
```

### Additional context
You would think this issue is related to netlify. But all other packages are loaded correctly and behaving as wanted. So I think this is related to sequelize (or the combination of the 2)

### Environment

- Sequelize version: `sequelize@5.19.0` 
- Node.js version: `v10.16.0` 
- Operating System: `Windows 10`

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
I don't have windows, so can't reproduce this. Perhaps remove your node_module and try installing it again.

**Comment by papb** [comment]
I tried to reproduce but the API call returned the raw contents of `index.html`, no error occurred (except that `unexpected token <` when parsing the JSON (I had to change it to `.text()` to see it), do you know what may be going on here?

**Comment by papb** [comment]
I [figured that out](https://stackoverflow.com/a/44853428/4135063). So weird.

Now I am getting a `400 Bad Request` response but I can't find out the error.

Where can I see this `Error: Please install sqlite3 package manually`?

**Comment by papb** [comment]
Hello, I believe Netlify uses Webpack under the hood, right? I will concentrate all efforts involving Webpack problems in this new issue: #13169 - Please help me there if possible.
