### ISSUE TITLE
Sequelize creates weird query

### ISSUE THREAD

**Issue by bsienn** [sequelize/sequelize#11463]
## Issue Description

Sequelize created query is not efficient when explained and it creates a weird query although i could simply create a simple join in raw query that works better. Please have a look in the SO link below where I posted the relation and code in there.

Please see and help me out whether I'm doing somthing wrong or its the behaviour of sequelize.

### StackOverflow / Slack attempts

I have asked the question  on StackOverflow, the link to that is the following.
[SO Link](https://stackoverflow.com/questions/58030940/sequelise-creates-weird-query)

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): 5.18.0
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by soryy708** [comment]
Does sequelize claim to generate optimized SQL?

**Comment by bsienn** [comment]
Maybe, I didn't phrased it well, I really liked the simplicity of the code but the queries I was getting was slow for my use case, All I was hoping for is to use same code but maybe somehow force it to generate some optimal query. Anyway, I'm not using this anymore, Thanks for reply.
