### ISSUE TITLE
Unable to search multiple tables.

### ISSUE THREAD

**Issue by martt70** [sequelize/sequelize#11462]
I am trying to search two(2) TABLES using promises but it doesn't seem to work.

router.get("/search", (req, res) => {
const { term } = req.query;

Promise.all([boiler_houses.findAll({ where: { equipment_type: { [Op.like]: '%' + term + '%'  } } }),compressor_houses.findAll({ where: { equipment_type: { [Op.like]: '%' + term + '%'  } } }) ]).then(gigs=>
res.render('gigs', {
      gigs})).catch(err => console.log(err));
    });

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
