### ISSUE TITLE
[create, update] method  print sql  no parameters

### ISSUE THREAD

**Issue by LiZhouYang5612** [sequelize/sequelize#11461]
Is this done for safety? 
Not friendly for our positioning problem
Can it be used as a configuration option?

**Comment by sushantdhiman** [comment]
![image](https://user-images.githubusercontent.com/9989487/65814367-655c4780-e1fe-11e9-9c9b-f93f7ef261fe.png)


https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor
