### ISSUE TITLE
Options missing in QueryInterface::bulkDelete

### ISSUE THREAD

**Issue by flashspys** [sequelize/sequelize#11473]
### What was unclear/insufficient/not covered in the documentation

In `QueryInterface::bulkDelete` the option `restartIdentity` and `cascade` are not documented.

https://sequelize.org/master/class/lib/query-interface.js~QueryInterface.html#instance-method-bulkDelete

I'm not using TypeScript, but if somebody (probably me) will solve this MR, one should check if the TypeScript definitions are correct for this parameter.

### If possible: Provide some suggestion on how we can enhance the docs

Add `restartIdentity` and `cascade` to the options, like in `Model::destroy`

https://sequelize.org/master/class/lib/model.js~Model.html#static-method-destroy

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by flashspys** [comment]
Dear lovely maintainers, what would be the process if I want to solve this issue by my own?

**Comment by papb** [comment]
Hello :grimacing: Thanks for the report!

> [X] Yes, I have the time but I don't know how to start, I would need guidance.

This is great.

> Dear lovely maintainers, what would be the process if I want to solve this issue by my own?

The documentation you linked is automatically generated from JSDoc block-comments. For example, the docs that you observed to exist in `Model::destroy` are defined [here](https://github.com/sequelize/sequelize/blob/fb3f0734e1c5e1620433d0ce7176f159ad15e8b4/lib/model.js#L2878-L2879).

What you have to do is simply update the [JSDoc block-comment here](https://github.com/sequelize/sequelize/blob/fb3f0734e1c5e1620433d0ce7176f159ad15e8b4/lib/query-interface.js#L1086).

> I'm not using TypeScript, but if somebody (probably me) will solve this MR, one should check if the TypeScript definitions are correct for this parameter.

Great observation, I will guide you on this later though (I am a busy right now), you can start with what I said above for now!
