### ISSUE TITLE
String based operators are deprecated

### ISSUE THREAD

**Issue by bssergy** [sequelize/sequelize#11471]
I'm using string based operators with POST request to get filtered data:
```
{
  user: {
    id: {
      not: 2
    }
  }
}
```
`User.findAll({ where: body.user });`
What should I do without string based operators?

**Comment by LiZhouYang5612** [comment]
const Op = require('sequelize').Op;

**Comment by bssergy** [comment]
> const Op = require('sequelize').Op;
> Op.not

But it means, I need manually parse my body and change "not" with Op.not. It can be hard to implement with nested and, not, or operators

**Comment by LiZhouYang5612** [comment]
instance.update({
  count: sequelize.literal('count + 1'),
});
It causes the value on this column to be 0,
Do you know how to solve it?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

**Comment by papb** [comment]
See #10820
