### ISSUE TITLE
don't work psql "pg-native"

### ISSUE THREAD

**Issue by lich666dead** [sequelize/sequelize#11470]
## hello guys.
I have a problem with sequelize:
i want make a connection cluster via psql,

for example 
```bash
psql "host=127.0.0.1,localhost,10.66.81.146 port=5432 dbname=test user=postgres password=123 target_session_attrs=read-write"
``` 
This work for pg-native lib, i tried override prototype connection but receive this error

```javascript
Unhandled rejection TypeError: cb is not a function
    at /Users/node_modules/pg-native/index.js:66:21
```

**Comment by sushantdhiman** [comment]
You will need to use `native: true` when initializing sequelize. https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html


-------------------------------------


Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
