### ISSUE TITLE
Sequeluze v5, mimic arrays as string using getters/setters not supported anymore?

### ISSUE THREAD

**Issue by mayankiitg** [sequelize/sequelize#11477]
We are using getters/setters in v4 for mimicking arrays and storing strings in the DB. 
when I am trying to upgrade to v5, it now throws an error and it seems it's not supported anymore, Can someone please help, what is the new way to achieve this?
```
@Column({ type: DataType.TEXT })
    get coordinates(): string[] {
        return this.getDataValue("coordinates").split(";");
    }

    set coordinates(value: string[]) {
        this.setDataValue("coordinates",  string.join(value, ';'));
    }```

**Comment by papb** [comment]
I have successfully mimicked arrays as string using getters/setters in sequelize v5. So this is most certainly an issue somewhere else. Looks like you're using sequelize-typescript, so this is most likely not a problem with Sequelize. Therefore I will close this.

Note: If you disagree, please post a complete issue, following the bug report template, including a SSCCE that does not use sequelize-typescript.
