### ISSUE TITLE
Importing with async function in same code raises TypeError

### ISSUE THREAD

**Issue by AlbertEmil** [sequelize/sequelize#11482]
## Issue Description
Trying to import/require sequelize module raises `TypeError` when async function is in code

### What are you doing?

```js
#!/usr/bin/env node

'use strict';

const Sequelize = require('sequelize')

(async () => {
    console.log('Nothing to do here');
})();
```

### What do you expect to happen?

Module should be imported without an error and available for use.

### What is actually happening?

`TypeError` is raised:

```
TypeError: Class constructor Sequelize cannot be invoked without 'new'
    at Object.<anonymous> (/Users/Albert/projectname/debug.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

### Environment

- Sequelize version: 5.19.0 
- Node.js version: 10.9.0 
- Operating System: Mac OS X 10.10.5

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by AlbertEmil** [comment]
I missed a semi-colon on the `require` statement. The line

`const Sequelize = require('sequelize')`

needs to be

`const Sequelize = require('sequelize');`

**Comment by xandery-geek** [comment]
I also met this issue, thank you!
