### ISSUE TITLE
findAndCountAll should allow you to exclude certain keys from the count query (loadMore)

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#11481]
`findAndCountAlL` is a nice convenience method for getting an array of results and a total count for pagination purposes. 

There is one common scenario in which this breaks: cursor based loadMore loading.
A cursor allows you to load "more" by saying something like `createdAt < createdAt of last item in the list`. 

Unfortunately, the resulting findAndCountAll will contain a new count using the cursor field based selector as a filter. You are selecting the next x items, but the count will be the total count - the previous items count.

So, I wonder if it would be an idea to allow one to add an `excludeFromCount` field or array of fields, that the `findAndCountAll` query will use to remove those fields from the count query.

**Comment by papb** [comment]
Hello, thanks for this, sorry to take long to reply.

Can you show a full SQL example that you were thinking Sequelize could generate? Thanj
