### ISSUE TITLE
6.0.0 and 7.0.0 are published on npm

### ISSUE THREAD

**Issue by poldridge** [sequelize/sequelize#11485]
## Issue Description

npm has versions 6.0.0 and 7.0.0 of sequelize even though those are not valid releases yet:

https://www.npmjs.com/package/sequelize/v/6.0.0
https://www.npmjs.com/package/sequelize/v/7.0.0

[Someone ran into an issue](https://stackoverflow.com/q/57846020/772035) where running `npm audit fix` "upgraded" them to 6.0.0, which as far as I can tell, is not actually a [valid release right now](https://github.com/sequelize/sequelize/milestone/19).

I was able to reproduce this by creating a new directory and then running `npm init -y; npm i -E sequelize@4.28.8; npm audit fix --force` inside it. After following those steps you will end up with sequelize@6.0.0 installed.

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.

**Comment by papb** [comment]
Hmm, curious. @sushantdhiman can you take a look?

**Comment by sushantdhiman** [comment]
![image](https://user-images.githubusercontent.com/9989487/65813105-33db8000-e1ee-11e9-9a89-e2391c2b9587.png)

**Comment by sushantdhiman** [comment]
Can't unpublish them either, will just have to wait till we launch v6/v7. I hope there will be a good alternative to `npm` registry in future, so we can switch to that.

**Comment by papb** [comment]
Yeah... The fact that `npm audit fix` updates it to v6 is a bit unfortunate.

Perhaps we could change the [current "v6 milestone"](https://github.com/sequelize/sequelize/milestone/19) to be the "v7 milestone" and publish a 6.1.0 version equivalent to the latest v5?

**Comment by poldridge** [comment]
This page says to send an email to support@npmjs.com if you are trying to unpublish a package that has been published more than 72 hours ago. Perhaps they can be accommodating if a package owner contacts them.

**Comment by papb** [comment]
@poldridge That's what I thought too :) Not sure what @sushantdhiman thinks about it though.

**Comment by jayhjha** [comment]
Are there any updates on this?

I have been using 6.0.0 for a while now, but npm started complaining today that it's unable to find it. I also can't find it in npm version history, but it's available in https://registry.npmjs.org/sequelize/-/sequelize-6.0.0.tgz.

**Comment by trustyknave** [comment]
Also interested to know if there are any updates, since my project recently ended up in the same state as described by @jayhjha above.

**Comment by papb** [comment]
Ping @sushantdhiman again - what do you think of messaging the NPM team asking to remove versions 6.0.0 and 7.0.0? I think they would probably do it

**Comment by batrudinych** [comment]
hey everyone,
npm started responding with `Not Found - GET https://registry.npmjs.org/sequelize/-/sequelize-6.0.0.tgz`. Seems it's been an issue for some time but I've faced it only today.
Any updates on that?

**Comment by papb** [comment]
@batrudinych none that I know of - @sushantdhiman do you know something about it?

**Comment by prathapcoder** [comment]
@batrudinych remove sequelize from package.json file and save the file. now run the following command npm install sequelize.

**Comment by ephys** [comment]
Now that v6 and v7 actually exist, I suppose we can close this :)
