### ISSUE TITLE
Unique msg error does not work

### ISSUE THREAD

**Issue by sergionwc10** [sequelize/sequelize#11488]
Hello
the custom error message in unique doesn't work

class User extends Model {}
User.init(
  {
    // attributes
    Name: Sequelize.STRING,
    Email: {
      type: Sequelize.STRING,
      allowNull: false,
      unique: {
        args: true,
        msg: 'This email id is already registered.'
      },
      validate: {
        len: {
          args: [6, 128],
          msg: 'Email address must be between 6 and 128 characters in length'
        },
        isEmail: {
          msg: 'Email address must be valid'
        }
      }
    },
    Password: Sequelize.STRING,
    Alias: Sequelize.STRING,
    DeletedOn: Sequelize.DATE,
    UserTypeId: Sequelize.INTEGER,
    RoleId: Sequelize.INTEGER,
    AdvertiserId: Sequelize.INTEGER,
    WebsiteId: Sequelize.INTEGER
  },
  {
    sequelize,
    modelName: 'User',
    timestamps: false
    // options
  }
);

Give me 

"message": "Validation error"

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
