### ISSUE TITLE
Bulkcreate: Ignore if single row fails

### ISSUE THREAD

**Issue by siddmv** [sequelize/sequelize#11483]
## Issue Description
Perhaps this already exists but, I could not find a way to achieve it. When using Bulkcreate, I would like the bulk insertions to proceed if a single row fails. It seems to me, presently, the entire array of objects does not proceed further if one error is encountered.

### Describe the solution you'd like
I have a bunch of objects that I could potentially create one at a time, handle (log and ignore) failure and proceed. It appears sub-optimal to me in contrast to using bulkCreate with a mechanism to ignore failures.

### Is this issue dialect-specific?
No

### Would you be willing to resolve this issue by submitting a Pull Request?
Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by siddmv** [comment]
Can you help give a pointer pls? Is this something one can already do today? Any help will be appreciated.

**Comment by sushantdhiman** [comment]
We do support `ignoreDuplicates / updateOnDuplicate` etc, https://sequelize.org/master/class/lib/model.js~Model.html#static-method-bulkCreate

These are dialect specific so I don't know if they will work for you, as you did not specified tour dialect in issue

**Comment by siddmv** [comment]
Thank you for the reply. I am using Sequelize against Postgres. I did come across Duplicate handling. 

But, what if a row fails because of some particular entries invalid data, lets say a DB level non-null constraint violated by an object. In such scenario, I would want the remaining objects to proceed normally, and get hold of the failed entries to inspect and handle later, if need be.

Is this already possible?

**Comment by sushantdhiman** [comment]
`ignoreDuplicates / updateOnDuplicate` just handle that, but you can't see which entries were ignored/updated I think. You just have to test, or take a look at our tests

**Comment by siddmv** [comment]
Ok, Thank you. I will try it out.

Appreciate the help.

**Comment by siddmv** [comment]
Hi, I just tried it out in the following scenario:
1. I have a table with one of the columns being non-nullable.
2. The bulkCreate call is passed an array of objects, with one of the objects missing the non-nullable field.
3. Set ignoreDuplicates to true. 
4. On running the code, got the following exception:

`Unhandled rejection SequelizeDatabaseError: null value in column "content" violates not-null constraint`

This is how I am calling bulkCreate:
```
	RiskData.bulkCreate(data, {ignoreDuplicates:true}).
		then(
			function() { 
				logger.debug("Done importing data") 
			});
```


I would have guessed ignoreDuplicates would be a way to ignore failures due to duplicates, not DB constraint violations. But, still tried it out.

Can you advise if there is a way to ignore such validation errors for specific errored rows?

**Comment by siddmv** [comment]
Perhaps, even if there is a per row after hook flexibility that I may use to subdue such an error and allow the remaining array to be processed?

**Comment by siddmv** [comment]
I @sushantdhiman .. Can you help me with this pls?

**Comment by sushantdhiman** [comment]
Follow the template, present issue as an SSCCE. I don't even know which dialect are we talking about

**Comment by siddmv** [comment]
Though didn't put the dialect as a part of the original description, I mentioned Postgres when you pointed out I missed it earlier.

**Comment by papb** [comment]
Hi @siddmv, please create an SSCCE showing the current behavior, I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce), this will really help us be able to help you.

**Comment by gap777** [comment]
I am also looking for a "best effort" bulkCreate, that inserts the valid rows and reports back the invalid ones. Any update on this?
