### ISSUE TITLE
How to force duplicated data on belongstomany relationship?

### ISSUE THREAD

**Issue by diego-augusto** [sequelize/sequelize#11498]
## Issue Description

How to force duplicated data on belongstomany relationship?

### Additional context

Database

![Imgur](https://i.imgur.com/YjiwJ6k.png)

Expected

![Imgur](https://i.imgur.com/nkM73Zl.png)

Received

![Imgur](https://i.imgur.com/pxgEQ0I.png)

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by diego-augusto** [comment]
I believe the responsible method is

**static _groupJoinData(rows, includeOptions, options)** 

https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query.js

**Comment by papb** [comment]
Hello, why did you close the issue?
