### ISSUE TITLE
How make sql INSERT INTO ... SELECT ?

### ISSUE THREAD

**Issue by heekyu** [sequelize/sequelize#11490]
## Issue Description
SQL(postgresql) : INSERT INTO table1 (ord, "refId", "createdAt", "updatedAt") SELECT (SELECT MAX(ord) FROM table1) + 1, 4, now(), now();

### What are you doing?
How can I make this SQL with Sequelize?

```js
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: 5.18.1 
- Node.js version: 10.15.3 
- Operating System: MacOS
- Postgresql: 11.1
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [O] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jpinkster** [comment]
@heekyu you could either first use a raw query to get your `select` data and then create a new instance from there since it looks like you are just trying to insert 1 row .. other wise just use raw query

https://sequelize.org/master/manual/raw-queries.html

**Comment by papb** [comment]
I don't think this is currently possible, please open a feature request filling our template completely, in the meantime you can do what jpinkster said, thanks
