### ISSUE TITLE
Mention known issues involving Babel + Sequelize in docs

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11494]
### What was unclear/insufficient/not covered in the documentation

[Sequelize and Babel don't get along well sometimes...](https://github.com/sequelize/sequelize/issues/11326#issuecomment-522424850)

For example, @levibostian made [a thorough analysis of one of these issues](https://github.com/sequelize/sequelize/issues/11032#issuecomment-533661568), involving specifically the babel plugin called [`@babel/plugin-proposal-class-properties`](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties).

### If possible: Provide some suggestion on how we can enhance the docs

We could have a section on the docs about this.

### Additional context
None

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Done in https://github.com/sequelize/sequelize/pull/13877
