### ISSUE TITLE
Type of InstanceError not found in "sequelize/types"

### ISSUE THREAD

**Issue by HopefulLlama** [sequelize/sequelize#11509]
### What are you doing?

I am attempting to import the InstanceError type from "sequelize/types" to be used in a function declaration. 

```js
import { InstanceError} from "sequelize/types";
```

### What do you expect to happen?

_I wanted InstanceError to be usable!_

### What is actually happening?

_I receive the following error!_

```
import InstanceError
Module '"../node_modules/sequelize/types"' has no exported member 'InstanceError'.ts(2305)
```

### Environment

- Sequelize version 5.18.4 
- Node.js version: 12.9.1 
- Operating System: MacOS Sierra
- If TypeScript related: TypeScript version: 3.6.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Don't use `/types`, only import from the root package:

```
import { InstanceError } from 'sequelize';
```
