### ISSUE TITLE
TypeError: errors.ConnectionAcquireTimeoutError is not a constructor

### ISSUE THREAD

**Issue by metjka** [sequelize/sequelize#11503]
## Issue Description
This is not happening really often. I think it is related to connection timeout and sequelize cant find specific error to throw. 

### What are you doing?

I am just querying data from a database for every request that comes to my server. Nothing special'. 

### What do you expect to happen?

I just want an error about connection timeout.

### What is actually happening?

```
Caused by: TypeError: errors.ConnectionAcquireTimeoutError is not a constructor
   at pool.acquire.catch.error (/srv/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
```

### Environment

- Sequelize version: 5.9.4  
- Node.js version: v10.16.3 
- Operating System: OSX 10.14.6
- TypeScript version: 3.5.1

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Hmm, connection error is exported [here](https://github.com/sequelize/sequelize/blob/3834fe200f4c3cb40a52c71b4a56a449d33d11d3/lib/errors/index.js#L19)

Will check

**Comment by sushantdhiman** [comment]
Also try with latest version

**Comment by metjka** [comment]
> Also try with latest version

The problem is that I don't know how to reproduce it. And the most strange thing, that it only occurred on my live server, and never on any of my dev environments.

**Comment by sushantdhiman** [comment]
Not sure what is wrong with your setup but I can ensure `ConnectionAcquireTimeoutError` is a valid error. There is even a test case for this code path https://github.com/sequelize/sequelize/blob/3834fe200f4c3cb40a52c71b4a56a449d33d11d3/test/integration/pool.test.js#L253

Please update to latest version, may be remove your node_modules folder. Please share detailed error stack or other code if you still face this issue with latest version.
