### ISSUE TITLE
Model.increment throws an exception when incrementing array element.

### ISSUE THREAD

**Issue by mskec** [sequelize/sequelize#11511]
### What are you doing?

I am trying to increment a value in an array using `Model.increment` method.

```js
product.increment('rating[2]');
```

My model has this definition for `ratings` column.
```js
rating: { type: Sequelize.ARRAY(Sequelize.INTEGER) }
```

### What do you expect to happen?

I expect that the `rating[2]` is incremented successfully.

### What is actually happening?

The command fails and an exception is thrown.

Postgres error log:
```
STATEMENT:  UPDATE "products" SET "rating[2]"="rating[2]"+ 1 WHERE "id" = 'u-u-i-d' RETURNING *
ERROR:  column "rating[2]" does not exist at character 35
```
The problem here is that sequelize is adding double quotes `"` around column names.

The correct query would be:

```sql
UPDATE "products" SET rating[2] = rating[2] + 1 WHERE "id" = 'u-u-i-d';
```

### Environment

- Sequelize version: 5.8.12
- Node.js version: v12.4.0
- Operating System: MacOS 10.14.6
- TypeScript version: 3.6.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using postgres, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, is this possibility documented somewhere? I think this is more like a feature request than a bug, do you agree?

**Comment by sushantdhiman** [comment]
Try this

```js
product.increment(sequelize.literal('rating[2]'));
```

**Comment by mskec** [comment]
Thank you for quick replies.

@papb  I didn't see it documented anywhere, but I assume it should work for any field. 

@sushantdhiman It's also not working. Now I'm getting these errors:
```
error SequelizeDatabaseError: column "val" does not exist
```

Generated query:
```sql
UPDATE "products" SET "val"="val"+ 'rating[2]' WHERE "id" = 'u-u-i-d'
```

**Comment by ub1x** [comment]
actually
