### ISSUE TITLE
Problem with Sequelize.ARRAY(Sequelize.FLOAT)

### ISSUE THREAD

**Issue by uvesten** [sequelize/sequelize#1151]
I'm using an array of FLOAT's in one of my models. 

Setting the value manually and saving works fine, like 

     coordinates: [58.31260, 14.28514]

However, when I want to update the instance containing the float array I get an error: 

    error: column "coordinates" is of type double precision[] 
    but expression is of type text[]

And when I inspect the value from the database I see that Sequelize has made them into strings: 

    "coordinates"=ARRAY['58.3126','14.28514']

(the column in Postgresql has the right type, though.) 

     coordinates     | double precision[]       |

I've tried to understand where the bug is in the sequelize.js code base, but I can't figure it out. Could someone with more knowledge of the code please write a fix for this?

**Comment by janmeier** [comment]
Works on 2.0

**Comment by uvesten** [comment]
Cool!
