### ISSUE TITLE
Association table entries not getting created

### ISSUE THREAD

**Issue by Subbup101** [sequelize/sequelize#11527]
## Issue Description

I have hasMany relation in my model in Maria DB. When I try to create a new record, no data is getting inserted in association table
// My Model file
const AnsprechPartner = db.define('ansprechPartner', {
    anrede: { type: Sequelize.STRING },
    titel: { type: Sequelize.STRING },
    vorname: { type: Sequelize.STRING },
    nachname: { type: Sequelize.STRING },
    email: { type: Sequelize.STRING },
    telefonNummer: { type: Sequelize.STRING },
    createDate: { type: Sequelize.DATE },
    changeDate: { type: Sequelize.DATE },
    createdBy: { type: Sequelize.STRING },
    changedBy: { type: Sequelize.STRING },
    deleted: { type: Sequelize.STRING, defaultValue: false }
}, {
    timestamps: false,
    hooks: {
        afterUpdate: function (object, options) {
            changes = triggers.afterUpdate(object, options);
            if (changes) {
                APartnerAudit.bulkCreate(changes);
            }
        },
        afterCreate: function (object, options) {
            insertAuditBulk = triggers.afterCreate(object, options);
            if (insertAuditBulk) {
                APartnerAudit.bulkCreate(insertAuditBulk);
            }
        },
        afterBulkCreate: function (instances, options) {
            for (let i = 0; i < instances.length; i++) {
                insertAuditBulk = triggers.afterCreate(instances[i], options);
                if (insertAuditBulk) {
                    APartnerAudit.bulkCreate(insertAuditBulk);
                }
            }
        }
    }
});

const Partner = db.define('partner', {
    id: { type: Sequelize.STRING, primaryKey: true },
    firmenName: { type: Sequelize.STRING },
    strasse: { type: Sequelize.STRING },
    hausNummer: { type: Sequelize.STRING },
    plz: { type: Sequelize.STRING },
    ort: { type: Sequelize.STRING },
    email: { type: Sequelize.STRING },
    telefonNummer: { type: Sequelize.STRING },
    iban: { type: Sequelize.STRING },
    bank: { type: Sequelize.STRING },
    type: { type: Sequelize.STRING },
    priority: { type: Sequelize.STRING },
    ablehnen: { type: Sequelize.STRING },
    active: { type: Sequelize.BOOLEAN },
    createDate: { type: Sequelize.DATE },
    changeDate: { type: Sequelize.DATE },
    createdBy: { type: Sequelize.STRING },
    changedBy: { type: Sequelize.STRING },
    deleted: { type: Sequelize.BOOLEAN, defaultValue: false }
}, {
    timestamps: false,
    hooks: {
        afterUpdate: function (object, options) {
            changes = triggers.afterUpdate(object, options);
            if (changes) {
                PartnerAudit.bulkCreate(changes);
            }
        },
        afterCreate: function (object, options) {
            insertAuditBulk = triggers.afterCreate(object, options);
            if (insertAuditBulk) {
                PartnerAudit.bulkCreate(insertAuditBulk);
            }
        }
    }
});

Partner.hasMany(AnsprechPartner, { as: 'ansprechPartners' }); // , onDelete: 'cascade', hooks: true
// AnsprechPartner.belongsTo(Partner);
Partner.sync();
AnsprechPartner.sync();

// Function API

async function createPartner(req, res) {
    try {
        const duplicate = await Partner.findOne({
            where: {
                'firmenName': req.body.firmenName
            }
        });
        if (duplicate) {
            return res.status(409).json({
                message: `Firm '${req.body.firmenName}' is already created.`
            });
        } else {
            try {
                var newPartner1 = new Partner(req.body);
                newPartner = newPartner1.dataValues;
                newPartner.id = await Partner.getNextSequenceValue('partner');
                newPartner.createDate = Date.now();
                newPartner.createdBy = req.query.autor;
                var ansprechPartner = req.body.ansprechPartner;
                for (let i = 0; i < ansprechPartner.length; i++) {
                    ansprechPartner[i].partnerId = newPartner.id;
                    ansprechPartner[i].createDate = Date.now();
                    ansprechPartner[i].createdBy = req.query.autor;
                }
                newPartner.ansprechPartners = ansprechPartner;
                console.log(newPartner);
                Partner.create(newPartner, { include: [{model: AnsprechPartner, as: 'ansprechPartners'}] }).then(result => {
                    // AnsprechPartner.bulkCreate(ansprechPartner);
                    return res.status(501).json(result);
                });
            } catch (err) {
                return res.status(501).json(err);
            }
        }
    } catch (err) {
        return res.status(501).json(err);
    }
}

// Example data I am trying to insert

{ deleted: false,
  id: 'P1000011',
  firmenName: 'test111',
  strasse: 'test',
  hausNummer: '3546',
  plz: '354678',
  ort: 'test',
  email: 'thfgjk@test',
  telefonNummer: '456879',
  iban: 'ftg',
  bank: 'rtzfg',
  type: 'werkstatt',
  priority: 'A',
  ablehnen: false,
  createDate: 1570640888786,
  createdBy: 'subbup101',
  ansprechPartners:
   [ { id: null,
       anrede: 'Frau',
       titel: '',
       vorname: 'Test',
       nachname: 'p',
       email: 'subbu@test',
       telefonNummer: '6578',
       deleted: null,
       partnerId: 'P1000011',
       createDate: 1570640888786,
       createdBy: 'subbup101' } ] }

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [. ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
