### ISSUE TITLE
queryInterface.addColumns always adds "public." to the table name for Postgres

### ISSUE THREAD

**Issue by pablote** [sequelize/sequelize#11522]
Not sure if I'm doing anything wrong, but this is a pretty big blocker for me right now. I need to add a column to an existing table which is in a schema different from "public".

Simply using the table name throws this error:
```"relation \"public.mytable\" does not exist"```

Adding the schema to the table name throws (this works for addIndex):
```"relation \"public.default.mytable\" does not exist"```

I've tried adding a `schema` property to the options object, like for the createTable method, but it seems to be ignored.

Is there a way to avoid "public" always getting added? I've also haven't seen a way to send arbitrary sql statements to the queryInterface, this way I could just send the "alter table" myself.

sequelize version: 5.19.4

**Comment by papb** [comment]
> Not sure if I'm doing anything wrong, but this is a pretty big blocker for me right now. I need to add a column to an existing table which is in a schema different from "public".
> 
> Simply using the table name throws this error:
> `"relation \"public.mytable\" does not exist"`
> 
> Adding the schema to the table name throws (this works for addIndex):
> `"relation \"public.default.mytable\" does not exist"`
> 
> I've tried adding a `schema` property to the options object, like for the createTable method, but it seems to be ignored.

Please provide an [SSCCE](http://sscce.org) - you can use the [sequelize-sscce](https://github.com/papb/sequelize-sscce) repository, for example.

> I've also haven't seen a way to send arbitrary sql statements to the queryInterface, this way I could just send the "alter table" myself.

You mean [raw queries](https://sequelize.org/master/manual/raw-queries.html)?

**Comment by allenwu1973** [comment]
For those who are like me found this from google search, this is duplicate of #11742

It seems like there's no way to specify a default schema for migrations (won't work with addColumn), you can however, change all your migrations to specify schema instead

**Comment by PanopticaRising** [comment]
This PR looks like it should address this issue by shortcutting the missing `options` in addColumns and similar functions.

https://github.com/sequelize/sequelize/pull/13045
