### ISSUE TITLE
find column that is define as bigint, more than 10000000000000000 . can't find it.

### ISSUE THREAD

**Issue by loumt** [sequelize/sequelize#11524]
#Issue Description
 Database : Mysql 5.7 
 When find a column that is define as bigint(20) . Can't find result where column = 10000000000000001 

### What are you doing?

  use module method : findByPk
  database:   mysql  
  mysql server install at windows.
  column:   bigint(20) not null
  column content:  10000000000000001 (more than 10000000000000000)

### What do you expect to happen?
  bigint  -9223372036854775808 ~ 9223372036854775807

### What is actually happening?
  Can't find more than 10000000000000000

### Environment

- Sequelize version: 5.19.1
- Node.js version: 10.16.0
- Operating System: Window

Mysql 5.7 
Windows

**Comment by papb** [comment]
Can you please create an [SSCCE](https://github.com/papb/sequelize-sscce)?

**Comment by ephys** [comment]
Closing due to not having enough information to resolve the issue.
