### ISSUE TITLE
SequelizeDatabaseError: read ECONNRESET

### ISSUE THREAD

**Issue by joseph-animasds** [sequelize/sequelize#11535]
## Issue Description

A clear and concise description of what is this issue about.
- I am getting this error, that I've posted in the title, every once in a while. My app is using Azure web app and Azure db. My app also pulls data from an api every 2 minutes. My error log shows that it happened while pulling the data from the api.
If applicable, you can add some code. In this case, an SSCCE/MCVE/reprex is much better than just an isolated code snippet.
Unable to produce a reprex with a complicated app I've built but here are the properties for my sequelize object
![image](https://user-images.githubusercontent.com/45604274/66605090-a7757980-eb6c-11e9-94c8-0b612395a2b8.png)

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.

### Additional context
Add any other context or screenshots about the issue here.
![image](https://user-images.githubusercontent.com/45604274/66605171-c8d66580-eb6c-11e9-8a7b-a5d091f25183.png)
Here is the db capacity with 20 DTU's
![image](https://user-images.githubusercontent.com/45604274/66605262-f4595000-eb6c-11e9-9a9f-9d95ebbb7279.png)

### Is this issue dialect-specific?

- [x ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, can you try to verify if Sequelize is opening and closing a connection for every query as opposed to keeping one single connection for the whole time?

**Comment by papb** [comment]
Hmm... Hard to reproduce bugs are hard :( :( do you know what kind of things can cause `ECONNRESET`?

**Comment by mlavery36** [comment]
facing same error..... but I use mariadb
![ERROR ECONNRESET](https://user-images.githubusercontent.com/93502826/196391713-1a3f713d-1b69-47e3-bd66-32a37ae27e13.png)
