### ISSUE TITLE
Connection error : EAGAIN

### ISSUE THREAD

**Issue by MagixInTheAir** [sequelize/sequelize#11531]
## Issue Description
Sequelize issues EAGAIN error randomly

### What are you doing?
Stressful event of multiple file uploadings in parallel at high bandwidth

### What do you expect to happen?
Not to crash

### What is actually happening?
[This](https://gist.github.com/MagixInTheAir/267ddf406dea1800536b234687d70f09)

### Additionnal information
Can't be replicated easily, so no minimal example, sorry. It only happens 

### Environment

- Sequelize version:  sequelize@5.19.4 
- Node.js version: v8.16.1 
- Operating System: SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux in Vagrant box

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X] I don't know, I was using 'mysql', with connector library version XXX and database version `mysql  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2` _(how am I supposed to find the connector version ?)_

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
> Can't be replicated easily, so no minimal example, sorry. It only happens

This is unfortunate... I'm sorry, but without a replication for this we won't be able to help you.

I've found [this](https://bugs.mysql.com/bug.php?id=48929) and [this](https://engineering.mixpanel.com/2012/12/07/debugging-mysql-performance-at-scale/) so I'm pretty sure this is a MySQL issue, not a Sequelize issue. So I will have to close this... Good luck!

**Comment by MagixInTheAir** [comment]
This was indeed a problem with Sequelize. The connection pool I used had a minimum of five connections, and those connections would get into an invalid state after being inactive after some time. Trying to use them before they get evicted from the pool, but after getting into this invalid state, triggers the error. I hope this can help someone in the future

**Comment by papb** [comment]
Hmmm interesting, how did you work around it?

**Comment by MagixInTheAir** [comment]
Reduced the pool minimum number of connections to zero. Trying to reliably fix and test that for a production environment would be a nightmare and I don't mind a tiny bit of latency when reconnecting since database is local

**Comment by papb** [comment]
I see, thanks!! Hopefully this will help others in the future :)
