### ISSUE TITLE
"has" method of BelongsToMany not working when data type of key is binary

### ISSUE THREAD

**Issue by tsasaki609** [sequelize/sequelize#11545]
## Issue Description
I tried to use belongsToMany association with binary key,
but it's not working fine, always return false.

### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/13 

### What do you expect to happen?

return ture when already have association

### What is actually happening?

Please see SSCCE link.

### Environment

- Sequelize version: 5.19.6 
- Node.js version: 10.16.3 
- Operating System: Mac
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
> Yes, I have the time and I know how to start.

Awesome!!
