### ISSUE TITLE
Docs use outdated Slack logo

### ISSUE THREAD

**Issue by marks** [sequelize/sequelize#11548]
## Issue Description

The old Slack logo is used at the top of the documentation pages

### What was unclear/insufficient/not covered in the documentation

Content is great, just needs an updated Slack logo :) 

### If possible: Provide some suggestion on how we can enhance the docs

Update the Slack logo (from https://brandfolder.com/slack/logos)

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Fixed by #11549

Thanks!!
