### ISSUE TITLE
limit and offset options not working with not required nested model

### ISSUE THREAD

**Issue by shcyiza** [sequelize/sequelize#11555]
## Issue Description
setting limit option on a query with a where statement that contains dollars signs doesn't work.
### What are you doing?
I'm trying to paginate reports (if you follow my sscce example) that has nested comments which has nested users.

**Here is the link to the SSCCE for this issue:** LINK-HERE https://gist.github.com/shcyiza/2a87db67253c9f293295984133ede8f5

### What do you expect to happen?
Having a list of 10 reports maximum with nested comments of user that are more then 18.

### What is actually happening?

```
missing FROM-clause entry for table \"user\"
```

### Additional context
I want to use limit to paginate a complex set of query.

### Environment

- Sequelize version: 5.19.0
- Node.js version: 12.12.0 
- Operating System: Mac OS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X] I don't know, I was using Postgres

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by shcyiza** [comment]
any new with this issue?

**Comment by papb** [comment]
Sorry to take long to reply, I have been astronomically busy, no news I'm afraid, thanks for the patience so far

**Comment by ephys** [comment]
From what I can see this is the same issue as what we are tracking [in this issue](https://github.com/sequelize/sequelize/issues/12971#issuecomment-1128838800), progress is reported over there
