### ISSUE TITLE
I have defined getterMethod in model, so when I call model.findAll the getter method called instantly and I get data duplications

### ISSUE THREAD

**Issue by sargsyanvlad** [sequelize/sequelize#11554]
#4525  Issue Description

const UserOptions = {
  getterMethods: {
    view() {
      const user = {
        id: this.dataValues.id,
        role: this.role,
        firstName: this.firstName,
        lastName: this.lastName,
        position: this.position,
        email: this.email,
        provider: this.provider,
        providerId: this.providerId,
        avatar: this.avatar,
        verified: this.verified,
        confirmed: this.confirmed,
        completed: this.completed,
      };
      if (this.jobSeeker) user.jobSeeker = this.jobSeeker;
      if (this.blockedUsers) user.blockedUsers = this.blockedUsers;
      if (this.company) user.company = this.company;
      user.online = getDuration(this.activeDate, Date.now()).asMinutes() < 5;
      return user;
    },
  },
  timestamps: true,
};
### StackOverflow / Slack attempts

https://stackoverflow.com/questions/58394927/is-there-any-solutions-to-exclude-data-returned-by-model-getter-method

### Additional context
I expect to get:
    { "email": "test2@test.com",
                "avatar": "images/aef887-1562065565705.png",
                "firstName": "John",
                "lastName": "Doe",
                "provider": "email",
                "providerId": null,
                "activeDate": "2019-10-14T13:39:48.298Z",
                "verified": false,
                "confirmed": false,
                "completed": true, };
but actual is array of duplicate values, attirbutes:{ exclude: ['view'] } doesn't help
    [ { "view": {
                        "firstName": "John",
                        "lastName": "Doe",
                        "email": "test@test.com",
                        "provider": "email",
                        "providerId": null,
                        "avatar": "images/aef887-1562065565705.png",
                        "verified": false,
                        "confirmed": false,
                        "completed": true,
                     } 
                      "email": "test@test.com",
                      "avatar": "images/aef887-1562065565705.png",
                      "firstName": "John",
                      "lastName": "Doe",
                      "provider": "email",
                      "providerId": null,
                      "activeDate": "2019-10-14T13:39:48.298Z",
                      "verified": false,
                      "confirmed": false,
                      "completed": true,
     }]
### Is this issue dialect-specific?
NO
- [x] No. This issue is relevant to Sequelize as a whole.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.

**Comment by papb** [comment]
When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

Also, please edit your issue formatting it with [markdown](https://guides.github.com/features/mastering-markdown/).

Once you do those I will reopen the issue

**Comment by papb** [comment]
> #4525 Issue Description

Also what does this have to do with #4525?
