### ISSUE TITLE
bindParam missing from AbstractDataType type definition

### ISSUE THREAD

**Issue by defunctzombie** [sequelize/sequelize#11550]
The `bindParam` function is missing from the AbstractDataTypes type definition. The result is that a user who implements a custom type must be aware to also implement the bindParam function if they want to do custom escaping or formatting of their type when used with the bind query interface.

Previously it was enough to just support `stringify` but this is no longer the case with the new bind based query builder.

**Comment by papb** [comment]
Hello, can you please show some code that should compile but doesn't? Thanks

**Comment by defunctzombie** [comment]
Absolutely. Tho the issue isn't that the code doesn't compile - its that without the bindParam being a required method to define my custom type did not work properly.

Below is my custom type definition which is meant to be a wrapper around the postgres NUMERIC type using the `big.js` library to support arbitrary precision and accurate decimal math operations in my application logic.

```typescript
import { AbstractDataType } from 'sequelize';
import Big from 'big.js';

export default class BigType implements AbstractDataType {
  public dialectTypes: string = '';
  public key: string = 'NUMERIC';

  toSql(): string {
    return 'NUMERIC';
  }

  toString(): string {
    return 'NUMERIC';
  }

  stringify(value: Big): string {
    return value.toString();
  }

  bindParam(value: Big): string {
    return value.toString();
  }

  _sanitize(value: string): Big {
    return Big(value);
  }

  parse(value: string): Big {
    return Big(value);
  }
}
```

When I ported from v4 to v5 I noticed that my queries were failing. I traced the problem down to missing the `bindParam` method from my implementation. Without this method present in the class, the queries were not serializing properly - this was a runtime error rather than compile time error.

After debugging by digging into the query generator code, I realized that I needed to add the `bindParam` method but this method was not part of `AbstractDataType` and so was not obvious to me that I needed to include it in my type for it to properly serialize. If the `bindParam` method was in the interface I would have gotten a build time error (what I wanted to see) and it would be obvious that I am missing an important method for proper functioning of my custom type.

**Comment by papb** [comment]
Ah, interesting! Thanks for the explanation and sorry to take so long to reply. It looks like fixing this is quite simple then, just adding one line to the type declarations, am I right? Or did I misunderstand something?

Also, by the way, since I noticed you are implementing a custom data type, is there any chance you could take a look at this issue to see if you have any ideas? #11177 Many people is currently having trouble to make a custom data type work - myself included. The steps provided in our [current docs](https://sequelize.org/master/manual/extending-data-types.html) don't work. Thank you!!

**Comment by defunctzombie** [comment]
> just adding one line to the type declarations, am I right

Yep. I believe that would do it.

> Also, by the way, since I noticed you are implementing a custom data type, is there any chance you could take a look at this issue to see if you have any ideas? #11177 Many people is currently having trouble to make a custom data type work - myself included.

I took a quick look at the issue and my initial impression is maybe the missing `bindParam` implementation. The referenced issue starts with someone wanting to implement a custom big number datatype - which is exactly what I needed. The code I pasted above should work for that use case (it does for me) granted I am using postgres rather than mysql as the original issue states.

**Comment by papb** [comment]
@defunctzombie Thank you!! I will look into it

**Comment by defunctzombie** [comment]
Is this issue still awaiting any other feedback?
