### ISSUE TITLE
Typing of findAll seems to be missing the support of undefined values in where

### ISSUE THREAD

**Issue by T0TProduction** [sequelize/sequelize#11564]
## Issue Description
When using sequelize with typescript, we run into the issue of not being able to use objects that have potentially undefined attributes for the `where` attribute of a `findAll` call. 

### What are you doing?

```js
import Sequelize from 'sequelize';

class class user extends Sequelize.Model {
/* define your table here, it shouldn't matter for types */
}
const queryObj:{id:string, optionalValue?:string} = { id: 'someID'};

user.findAll({ where: queryObj }); // This is where the issue appears
```

### What do you expect to happen?

According to my understanding of the discussion in [issue #8583](https://github.com/sequelize/sequelize/issues/8583) the function should support undefined values as input. (If as null, or ignoring it completely, is irrelevant for this issue)

### What is actually happening?

We get type errors, not allowing undefined values inside the `where`object.

### Additional context

none

### Environment

- Sequelize version: 5.19.6
- Node.js version: ^10, should not be relevant in any way
- Operating System: OS X and WIN 10, should also make no difference
- If TypeScript related: TypeScript version: 3.6.2

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start. (if it is simply adjusting the types)
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
> * [x]  Yes, I have the time and I know how to start. (if it is simply adjusting the types)

Awesome! Please do :+1: It's just fixing the types, yes (and adding a type test to prevent regressions).

Let me know if you need any help.

**Comment by T0TProduction** [comment]
Whilst looking for the type definition, I found something that might make this a bit more complicated :

According to [this( 4th bullet point) ](https://github.com/sequelize/sequelize/blob/master/docs/manual/upgrade-to-v5.md#others) from the "migrate to v5" docs, `undefined` as **value** of a key throws errors.
This does imply, that the type should not allow `undefined` as well.
Considering the example I provided on the top though, it still is a "bug". 
We would supply no key, that has the value `undefined` , but the typing still does not allow it.
Changing the typing would allow runtime errors through accidentally added keys, that have the value `undefined` though. Therefore, the best solution is probably to gracefully degrade if such a value is handed in, as the option to have optional query parameters is very important imo.
In fact, if we set the type in the example above to `any` the code works just as expected. We lose the typing though...

Any thoughts on what would be the best solution? I don't want to spend time on fixing something that is then discarded anyways.

**Comment by papb** [comment]
> Changing the typing would allow runtime errors through accidentally added keys, that have the value `undefined` though. 

Personally I think this drawback is a small price to pay.

I've found [typescript#13195](https://github.com/microsoft/TypeScript/issues/13195) though, so I guess there isn't a better way until that issue is fixed (if ever?).

Let's see what @SimonSchick thinks about it :)

**Comment by T0TProduction** [comment]
Any update on this?

**Comment by papb** [comment]
Not from me, perhaps @SimonSchick may have an idea :)

**Comment by Altimar21** [comment]
Hi ! Did you have time to check this one ?
