### ISSUE TITLE
Sequelize V5 & Model Loading

### ISSUE THREAD

**Issue by nealdyrkacz** [sequelize/sequelize#11561]
### What was unclear/insufficient/not covered in the documentation

I have had Sequelize V4 up and running previously.  Currently trying to create a project using Sequelize V5 & Typescript.

I have peeked at 
https://sequelize.org/master/manual/typescript.html#usage
https://sequelize.org/master/manual/typescript.html#usage-of--code-sequelize-define--code-

I have tried to follow the 2nd setup with define, but still run in to issues when trying to load the models. In the usual Model Loader format, it is searching the dir for *js files, but since they are Typescript nothing is found.  Changing to look for *ts files,  I get the error of `TypeError: defineCall is not a function`.  But since Typescript will build javascript, will this still cause issues since in the built js files, it will now be looking for ts files that don't exist?

Now I have been looking at the other set up with out using the define.  I am confused by the documentation as when to call the Model.init() functions to add them to sequelize... should these init functions be exported and called in a looping fashion while passing the sequelize instance to it to add them?

### If possible: Provide some suggestion on how we can enhance the docs

Documents could be flushed out a little more with easier to understand working examples

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): 
- [X] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, thanks for the report, this is indeed something that I believe that needs to be improved asap, sadly I am super busy these days... This is one of my next goals with Sequelize, after I finish the major documentation updates I'm currently working on.

**Comment by nealdyrkacz** [comment]
@papb Thanks!  
I have been able to get it up and running.  Maybe in a not 'best practice' approach.  but I understand what is going on a little better after a lot of trial and error.  I had this question up on stackoverflow and went ahead and answered it myself.  Hopefully it will get some feedback on streamlining my approach.

https://stackoverflow.com/questions/58420410/model-loader-for-sequelize-v5-typescript/58436580#58436580

**Comment by ephys** [comment]
Changes made in Sequelize 7 simplified the process, and the new documentation includes TypeScript examples throughout, including in how to define a model: https://sequelize.org/docs/v7/models/defining-models/

I believe this can therefore be closed
