### ISSUE TITLE
'fieldMap' property is missing in 'QueryOptions' typings

### ISSUE THREAD

**Issue by zanctor** [sequelize/sequelize#11567]
### What are you doing?

```ts
const query = `any query here`;

const result = await sequelize.query(query, {
    replacements: {
        ...
    },
    type: QueryTypes.SELECT,
    fieldMap: {
        ...
    }
});
```

### What do you expect to happen?

There are no compilation errors.

### What is actually happening?

```
error TS2769: No overload matches this call.
The last overload gave the following error.
    Argument of type '{ replacements: { groupId: number; offset: number; perPage: number; fromDate: any; toDate: any; }; type: QueryTypes.SELECT; fieldMap: {}' is not assignable to parameter of type 'QueryOptions | QueryOptionsWithType<QueryTypes.RAW>'.
      Object literal may only specify known properties, and 'fieldMap' does not exist in type 'QueryOptions | QueryOptionsWithType<QueryTypes.RAW>'.
```

### Additional context

<img width="928" alt="Screen Shot 2019-10-17 at 17 24 36" src="https://user-images.githubusercontent.com/11874442/67017909-14f04f80-f103-11e9-9370-b67efc0ab0b8.png">

### Environment

- Sequelize version: 5.19.8
- Node.js version: 10.16.1
- Operating System: macOS 10.14.6
- TypeScript version: 3.6.4

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thanks, this looks wrong indeed.

**Comment by techguysid** [comment]
Willing to fix this.

**Comment by papb** [comment]
Hi @techguysid, thank you! Let me know if you need help/guidance. I suggest you take a look at [recently merged pull requests with the `type: typescript` label](https://github.com/sequelize/sequelize/pulls?utf8=%E2%9C%93&q=is%3Amerged+is%3Apr+label%3A%22type%3A+typescript%22+) to see how others fixed similar problems.

**Comment by techguysid** [comment]
@papb - pinged you on sequelize's slack.

**Comment by papb** [comment]
Hello @techguysid, sorry to take so long, are you still interested in going forward with this? I will try to reply faster now

**Comment by papb** [comment]
Ha, actually the PR was already merged. Haha. Don't worry about it. This issue should have been closed already.

Thanks!!
