### ISSUE TITLE
Standardize the API of the `queryInterface.showAllSchemas` method

### ISSUE THREAD

**Issue by misos1** [sequelize/sequelize#11568]
## Issue Description

Similar situation as in: https://github.com/sequelize/sequelize/issues/11451

According to documentation method `queryInterface.showAllSchemas` returns Promise\<Array\>. But actual content differs per dialect.

mysql (lists only actual database with tables):
``` js
[
  { Tables_in_database1: 'table_1' },
  { Tables_in_database1: 'table_2' }
]
```

mariadb (lists all databases):
``` js
[ 'database1', 'database2' ]
```

I did not check other dialects.

Both dialects were tested with mariadb database.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

**Comment by ephys** [comment]
I think this has been fixed in #14999, but we're missing an [integration test](https://github.com/sequelize/sequelize/tree/main/test/integration/query-interface) to make sure

**Comment by WikiRik** [comment]
We have the following test already;
https://github.com/sequelize/sequelize/blob/fcbdb5165d056c81bed1fb7756415ba24e080ea4/test/integration/model.test.js#L2145-L2159

**Comment by ephys** [comment]
Ah so confirmed fixed, nice :)
