### ISSUE TITLE
sequelize doesn't return columns which include dot symbol

### ISSUE THREAD

**Issue by nairihar** [sequelize/sequelize#11563]
# Issue Description

SQL group Query Result:
<img width="235" alt="Screen Shot 2019-10-17 at 10 47 04 AM" src="https://user-images.githubusercontent.com/15065065/66984286-78f72180-f0cb-11e9-868d-47fae6c404a8.png">

JavaScript log after `findAll`:
<img width="286" alt="Screen Shot 2019-10-17 at 10 47 33 AM" src="https://user-images.githubusercontent.com/15065065/66984323-890f0100-f0cb-11e9-96b1-ce0ec7184b1d.png">

Is it a bug? Can I use `.` symbol in my column name?

If possible: Provide some suggestion on how we can enhance the docs
-
Additional context
-

Issue Template Checklist
Is this issue dialect-specific?
 - [ ] No. This issue is relevant to Sequelize as a whole.
 - [ ] Yes. This issue only applies to the following dialect(s):
 - [x] I don't know.

Would you be willing to resolve this issue by submitting a Pull Request?
 - [ ] Yes, I have the time and I know how to start.
 - [ ] Yes, I have the time but I don't know how to start, I would need guidance.
 - [ ] No, I don't have the time, although I believe I could do it if I had the time...
 - [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by nairihar** [comment]
seems `QUERY.raw = true` helped

**Comment by papb** [comment]
Hmmm, great that you found a workaround, but I think this should be investigated anyway, it should work well.

**Comment by nairihar** [comment]
Sure that a good idea.

**Comment by WikiRik** [comment]
Does this issue still occur on the latest version?

**Comment by nairihar** [comment]
I'm not sure

**Comment by WikiRik** [comment]
Can you try it out? And possibly also provide an [SSCCE/MVCE](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#opening-issues) in case it still does not work? That makes it easier for us to fix the possible bug.
