### ISSUE TITLE
order: sequelize.literal option to order by associated models columns breaks the query

### ISSUE THREAD

**Issue by ulyr** [sequelize/sequelize#11565]
## Issue Description
If the sequelize.literal you put in the order option of findAll orders by a column in an associated row the query that gets executed is broken and will return a database error.

### What are you doing?

```js
model.findAll({
  where: { ... },
  include: [associatedModel],
  order: sequelize.literal('greatest("model"."updatedAt", "associatedModel"."updatedAt") DESC'),
})
```

### What do you expect to happen?

Expected the query to return the rows ordered by the greatest date.

### What is actually happening?

The query that is generated by sequelize is broken resulting in the following error,
`SequelizeDatabaseError: missing FROM-clause entry for table "associatedModel"`
this is because sequelize adds an ORDER BY clause in two places, one is correct and the second is incorrect.

example of generated query:
```sql
SELECT "model".*,
       "associatedModel"."updatedAt" AS "associatedModel.updatedAt"
FROM (SELECT "model"."id",
       FROM "models" AS "models"
       WHERE ...
       -- this is where sequelize inserts an unnecessary order by
       ORDER BY greatest("models"."updatedAt", "associatedModel"."updatedAt") DESC
       LIMIT 20 OFFSET 0) AS "models"
       LEFT OUTER JOIN "associatedModel" AS "associatedModel" ON "models"."id" = "associatedModel"."associatedId"
-- it also puts an order by here, which is correct
ORDER BY greatest("models"."updatedAt", "associatedModel"."updatedAt") DESC;
```

### Environment

- Sequelize version: 5.8.10
- Node.js version: 10.15.3
- Operating System: Ubuntu 16.04

### How does this problem relate to dialects?

- [ x ] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

I would suggest to search for the associatedModel in the sequelize.literal string before deciding if to add it to the subQuery, but I'm not sure where the code that does that is located or if it's the best solution.

- [ x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thanks for the report. For we to be able to really work on this and fix it, I need you to create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) for this. Can you do it? Let me know if you have trouble, thanks for understanding :)
