### ISSUE TITLE
Add multiple foreign keys on BelongsToMany() association

### ISSUE THREAD

**Issue by guilmarc** [sequelize/sequelize#11577]
## Issue Description
For now it's impossible to generate N:M relationship with multi fields primary key table.  The sync() method generates a relation table with the FIRST primary key element only.

```js
module.exports = (sequelize, type) => {
    return sequelize.define( 'group', {
        course_code: {
            type: type.STRING(3),
            primaryKey: true
        },
        year: {
            type: type.INTEGER,
            primaryKey: true
        },
        number: {
            type: type.INTEGER,
            primaryKey: true
        }
    })
}


module.exports = (sequelize, type) => {
    return sequelize.define('student', {
        id: {
            type: type.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        code: {
            type: type.STRING(8)
        },
        name: {
            type: type.STRING
        }
    })
}

Group.belongsToMany(Student, {through: "students_groups"})
Student.belongsToMany(Group, {through: "students_groups"})
```

### Is your feature request related to a problem? Please describe.
Yes, many of my projects are using multiple fields primary key.

### Describe the solution you'd like
The sync() method should consider multiple fields primary key for a model and create the association table using those fields.

### Why should this be in Sequelize
Because it's in the core of sync() method !

### Describe alternatives/workarounds you've considered
Don't use any multiple fields primary key tables in my databases.  That's not a real solution !

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, can you please post what SQL was generated by Sequelize with your code above and which SQL you wanted it to generate instead? Thanks

**Comment by soryy708** [comment]
Looks like a general problem with composite foreign keys https://github.com/sequelize/sequelize/issues/311
