### ISSUE TITLE
UNSIGNED is not supported in postgres dialect

### ISSUE THREAD

**Issue by luiscubal** [sequelize/sequelize#1157]
This is a test to reproduce the issue:

```javascript
var Sequelize = require('sequelize');
var sequelize = new Sequelize('dbname', 'username', 'password', {
	'host': 'localhost',
	'port': 5432,
	'dialect': 'postgres'
});

var test = sequelize.define('test', {
	'value' : Sequelize.INTEGER.UNSIGNED
}, {});

sequelize.sync({force: true}).done(function(err) {
	if (err) console.log('Got error', err);
});
```

Expected: Empty output
Got:
```
`Got error [ { [error: syntax error at or near "UNSIGNED"]
    name: 'error',
    length: 90,
    severity: 'ERROR',
    code: '42601',
    detail: undefined,
    hint: undefined,
    position: '53',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    file: 'scan.l',
    line: '1001',
    routine: 'scanner_yyerror' } ]
```

It seems that Postgres has no unsigned types at all ([source](http://www.postgresql.org/message-id/CAEcSYX+Arn7y4FeYPp6ZgbiiiMfZYmsn9aUyotZB-MA1n5hTOw@mail.gmail.com)).  Perhaps it could be implemented by adding 1 bit to the size and adding a [constraint](http://www.postgresql.org/docs/8.1/static/ddl-constraints.html)?

**Comment by DNizovtsev** [comment]
the issue still not fixed

**Comment by mickhansen** [comment]
@DNizovtsev Hence it not being closed.
Although with the new data types it could likely easily be fixed by removing the UNSIGNED keyword when using postgres - However i'm not sure i like it failing silently.

**Comment by BridgeAR** [comment]
Wrong types won't be inserted any more. Instead unsigned/similar will be truncated.
I'll open a new PR soon to add warnings if data types are used in a way that is not supported in the specific dialect.
