### ISSUE TITLE
SequelizeValidationError: Validation error

### ISSUE THREAD

**Issue by emko** [sequelize/sequelize#11589]
## Issue Description

any type of validation i do and make it fail i get a error even though i am doing try catch, what am i doing wrong? or is this normal? thanks

### What are you doing?
```
  try {
    await db.User.update({ username: username, isActive: true},{ where: { id: user.id } });
"email"] } }))
  } catch (err) {
    console.error(err)
  }
```
```
"use strict";
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define(
    "User",
    {
      username: {
        type: DataTypes.STRING(15),
        allowNull:false,
        validate: {
          isAlphanumeric: true,
          notNull: true,
          notEmpty: true,
          len: { args: [4,15], msg: "username has to between 4 and 15 characters"}
          
        }
      },
```

### What do you expect to happen?

to get validation result not a this kind of error

### What is actually happening?

> { SequelizeValidationError: Validation error: username has to between 4 and 15 characters
>     at Promise.all.then (api\node_modules\sequelize\lib\instance-validator.js:74:15)
>     at tryCatcher (api\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (api\node_modules\bluebird\js\release\promise.js:547:31)
>     at Promise._settlePromise (api\node_modules\bluebird\js\release\promise.js:604:18)
>     at Promise._settlePromise0 (api\node_modules\bluebird\js\release\promise.js:649:10)
>     at Promise._settlePromises (api\node_modules\bluebird\js\release\promise.js:729:18)
>     at Promise._fulfill (api\node_modules\bluebird\js\release\promise.js:673:18)
>     at PromiseArray._resolve (api\node_modules\bluebird\js\release\promise_array.js:127:19)
>     at PromiseArray._promiseFulfilled (api\node_modules\bluebird\js\release\promise_array.js:145:14)
>     at Promise._settlePromise (api\node_modules\bluebird\js\release\promise.js:609:26)
>     at Promise._settlePromise0 (api\node_modules\bluebird\js\release\promise.js:649:10)
>     at Promise._settlePromises (api\node_modules\bluebird\js\release\promise.js:729:18)
>     at _drainQueueStep (api\node_modules\bluebird\js\release\async.js:93:12)
>     at _drainQueue (api\node_modules\bluebird\js\release\async.js:86:9)
>     at Async._drainQueues (api\node_modules\bluebird\js\release\async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (api\node_modules\bluebird\js\release\async.js:15:14)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
>   name: 'SequelizeValidationError',
>   errors:
>    [ ValidationErrorItem {
>        message: 'username has to between 4 and 15 characters',
>        type: 'Validation error',
>        path: 'username',
>        value: 'eee',
>        origin: 'FUNCTION',
>        instance: [User],
>        validatorKey: 'len',
>        validatorName: 'len',
>        validatorArgs: [Array],
>        original: [Error] } ] }

### Environment

Sequelize CLI [Node: 10.15.3, CLI: 5.5.1, ORM: 6.0.0-beta.3] 
Mysql
i am using latest v5 just tested out 6 and it does the same

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using mysql , with connector library version     "mysql2": "^1.7.0",
and database version 8.0.17

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.

**Comment by soryy708** [comment]
> **What do you expect to happen?**
> to get validation result not a this kind of error

This is a validation error. I don't see the problem.
