### ISSUE TITLE
Associations  table & Multiple query criteria

### ISSUE THREAD

**Issue by 841660202** [sequelize/sequelize#11585]
## Issue Description
i use egg.js + egg-sequelize + sequelize

```js
async findAndCountAll({ size, page }) {
    const { ctx } = this;
    const result = await ctx.model.Apk.findAndCountAll({
      limit: size,
      offset: size * (page - 1),
      include: [{
        model: ctx.model.ApkDes,
        as: 'infos',
        where: { apk_id: { $col: 'apk.id' } }, // here
      }],
      order: [[ 'created_at', 'desc' ]],
      distinct: true,
    });
    return result;
  }

```

 - run log result

> 2019-10-20 17:24:05,506 INFO 30504 [egg-sequelize](1ms) Executed (default): SELECT `apk`.*, `infos`.`id` AS `infos.id`, `infos`.`apk_id` AS `infos.apkId`, `infos`.`version` AS `infos.version`, `infos`.`content` AS `infos.content`, `infos`.`created_at` AS `infos.createdAt`, `infos`.`updated_at` AS `infos.updatedAt`, `infos`.`deleted_at` AS `infos.deletedAt` FROM (SELECT `apk`.`id`, `apk`.`platform`, `apk`.`package_name` AS `packageName`, `apk`.`url`, `apk`.`version`, `apk`.`app_name` AS `appName`, `apk`.`created_at` AS `createdAt`, `apk`.`updated_at` AS `updatedAt`, `apk`.`deleted_at` AS `deletedAt` FROM `apk` AS `apk` WHERE (`apk`.`deleted_at` IS NULL) AND ( SELECT `version` FROM `apk_des` AS `infos` WHERE ((`infos`.`deleted_at` IS NULL AND `infos`.`apk_id` = '[object Object]') AND `infos`.`version` = `apk`.`version`) LIMIT 1 ) IS NOT NULL ORDER BY `apk`.`created_at` DESC LIMIT 0, 10) AS `apk` INNER JOIN `apk_des` AS `infos` ON `apk`.`version` = `infos`.`version` AND (`infos`.`deleted_at` IS NULL AND `infos`.`apk_id` = '[object Object]') ORDER BY `createdAt` DESC;

- result log img
![image](https://user-images.githubusercontent.com/18305361/67157442-c9d27880-f35e-11e9-85ef-f9bef04bb9b4.png)

- result log sql formatter
```sql
SELECT
	`apk`.*,
	`infos`.`id` AS `infos.id`,
	`infos`.`apk_id` AS `infos.apkId`,
	`infos`.`version` AS `infos.version`,
	`infos`.`content` AS `infos.content`,
	`infos`.`created_at` AS `infos.createdAt`,
	`infos`.`updated_at` AS `infos.updatedAt`,
	`infos`.`deleted_at` AS `infos.deletedAt` 
FROM
	(
	SELECT
		`apk`.`id`,
		`apk`.`platform`,
		`apk`.`package_name` AS `packageName`,
		`apk`.`url`,
		`apk`.`version`,
		`apk`.`app_name` AS `appName`,
		`apk`.`created_at` AS `createdAt`,
		`apk`.`updated_at` AS `updatedAt`,
		`apk`.`deleted_at` AS `deletedAt` 
	FROM
		`apk` AS `apk` 
	WHERE
		( `apk`.`deleted_at` IS NULL ) 
		AND (
		SELECT
			`version` 
		FROM
			`apk_des` AS `infos` 
		WHERE
#here 
			( ( `infos`.`deleted_at` IS NULL AND `infos`.`apk_id` = '[object Object]' ) AND `infos`.`version` = `apk`.`version` ) 
			LIMIT 1 
		) IS NOT NULL 
	ORDER BY
		`apk`.`created_at` DESC 
		LIMIT 0,
		10 
	) AS `apk`
	INNER JOIN `apk_des` AS `infos` ON `apk`.`version` = `infos`.`version` 
 #here 
	AND ( `infos`.`deleted_at` IS NULL AND `infos`.`apk_id` = '[object Object]' ) 
ORDER BY
	`createdAt` DESC;

```

- Expect

```sql
SELECT
	`apk`.*,
	`infos`.`id` AS `infos.id`,
	`infos`.`apk_id` AS `infos.apkId`,
	`infos`.`version` AS `infos.version`,
	`infos`.`content` AS `infos.content`,
	`infos`.`created_at` AS `infos.createdAt`,
	`infos`.`updated_at` AS `infos.updatedAt`,
	`infos`.`deleted_at` AS `infos.deletedAt` 
FROM
	(
	SELECT
		`apk`.`id`,
		`apk`.`platform`,
		`apk`.`package_name` AS `packageName`,
		`apk`.`url`,
		`apk`.`version`,
		`apk`.`app_name` AS `appName`,
		`apk`.`created_at` AS `createdAt`,
		`apk`.`updated_at` AS `updatedAt`,
		`apk`.`deleted_at` AS `deletedAt` 
	FROM
		`apk` AS `apk` 
	WHERE
		( `apk`.`deleted_at` IS NULL ) 
		AND (
		SELECT
			`version` 
		FROM
			`apk_des` AS `infos` 
		WHERE
			( ( `infos`.`deleted_at` IS NULL AND `infos`.`apk_id` = `apk`.`id` ) AND `infos`.`version` = `apk`.`version` ) 
			LIMIT 1 
		) IS NOT NULL 
	ORDER BY
		`apk`.`created_at` DESC 
		LIMIT 0,
		10 
	) AS `apk`
	INNER JOIN `apk_des` AS `infos` ON `apk`.`version` = `infos`.`version` 
	AND ( `infos`.`deleted_at` IS NULL AND `infos`.`apk_id` = `apk`.`id` ) 
ORDER BY
	`createdAt` DESC;

```

### try

- I have tried docs

```js
Project.findAll({
    include: [{
        model: Task,
        where: { state: Sequelize.col('project.state') }
    }]
})
```
my code
```js
  async findAndCountAll({ size, page }) {
    const { ctx } = this;
    const result = await ctx.model.Apk.findAndCountAll({
      limit: size,
      offset: size * (page - 1),
      include: [{
        model: ctx.model.ApkDes,
        as: 'infos',
        // where: { apk_id: { $col: 'apk.id' } },
         where: { apk_id: Sequelize.col('apk.id') },  // here
      }],
      order: [[ 'created_at', 'desc' ]],
      distinct: true,
    });
    return result;
  }
```
- result
![image](https://user-images.githubusercontent.com/18305361/67157613-0b642300-f361-11e9-8710-55528fef9675.png)

- have see others  issues， but can not solve it
i need help

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.
