### ISSUE TITLE
updateOnDuplicate and Postgres 12

### ISSUE THREAD

**Issue by Vadyanga** [sequelize/sequelize#11598]
Hello

I have [the following code](https://imgur.com/ZPUqgwR), Sequelize 5.21.1 and Postgres 12(>9.4), when I run code, it creates all rows as in array without updating

I need to update rows if keys match and if they don't match - add. = [`if(inTable_reviewID == _data_reviewID) => update_line, else => add_newline`

```javascript
const atd=(_data, _table = options.bd.table)=>{
	const sequelize = new Sequelize(options.bd.db, options.bd.login, options.bd.password, options.bd.options);
	let Table = sequelize.define(_table, {
		rating: Sequelize.INTEGER,
		// more lines
		reviewID: Sequelize.STRING
	}, {freezeTableName: true});
	sequelize.sync().then(()=>{
		Table.bulkCreate(_data, {
			updateOnDuplicate: ['reviewID']
		});
	});
};
```

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by Vadyanga** [comment]
bump

**Comment by cjancsar** [comment]
@Vadyanga you need to follow the issue template as @sushantdhiman has mentioned.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.

**Comment by Vadyanga** [comment]
```javascript
const Sequelize = require('sequelize');
const atd=(_data, _table = options.table)=>{
	const sequelize = new Sequelize(options.db, options.login, options.password, options.options);
	let Table = sequelize.define(_table, {
		rating: Sequelize.INTEGER,
		// more lines
		reviewID: Sequelize.STRING
	}, {freezeTableName: true});
	sequelize.sync().then(()=>{
		Table.bulkCreate(_data, {
			updateOnDuplicate: ['reviewID']
		});
	});
};

const options = {
	table: 'two',
	db: '11',
	login: 'postgres',
	password: '123',
	options: {
		host: 'localhost',
		port: 5414,
		protocol: 'tcp',
		logging: false,
		dialect: 'postgres'
	}
};

const a = [{
	reviewID: 'asdasd2',
	rating: 2,
},{
	reviewID: 'asdasd1',
	rating: 1,
},{
	reviewID: 'asdasd0',
	rating: 0,
}];
const b = [{
	reviewID: 'asdasd2',
	rating: 9,
},{
	reviewID: 'asdasd1',
	rating: 9,
},{
	reviewID: 'asdasd00',
	rating: 9,
}];
console.log('z');
atd(a); // set to b, after 1 or more starts
```

**Comment by Vadyanga** [comment]
Are you working on it? I have a time limit... 
https://imgur.com/a/jVeb9gx

**Comment by Vadyanga** [comment]
Hello, any updates?

**Comment by papb** [comment]
Please try to make your code more readable and convert it into a [sequelize-sscce](https://github.com/papb/sequelize-sscce)

**Comment by Vadyanga** [comment]
Are you ahuel tam? Code is very simple and readable ALOT. Btw, can you just say - https://imgur.com/a/jVeb9gx is it possible to do with your orm? and by this: "updateOnDuplicate" or I'm need to create updating and another yolo func, thanks
