### ISSUE TITLE
Typescript bindings incomplete when using `sequelize.query()`

### ISSUE THREAD

**Issue by segersniels** [sequelize/sequelize#11595]
###  Issue Description
It seems that the Typescript bindings are incomplete when using `.query()` with the `plain: true`.
It always returns an array of objects and doesn't take the `plain` option into account which should return a single row.

Adding the following typing resolves the issue but not entirely sure if it's the way to go.

```
public query<T extends object>(sql: string | { query: string; values: unknown[] }, options: QueryOptionsWithType<QueryTypes.SELECT> & { plain: true }): Promise<T>;
```

### What are you doing?

```js
const { count } = await sequelize.query(
    `
    SELECT COUNT(1) as count
    FROM foo f
    WHERE
      f.status = 'OK'
  `,
    {
      plain: true,
    },
  );
```

### What do you expect to happen?

The above query should return a single row and successfully destructure `count` from the single row that was returned using the `plain` option.

### What is actually happening?

Instead Typescript complains about the following:
`Property 'count' does not exist on type 'object[]'.`

### Environment

- Sequelize version: `5.21.1`
- Node.js version: `10.15.3`
- Operating System: `macOS Mojave`
- If TypeScript related: TypeScript version: `3.6.2`

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s):
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sergeyjsg** [comment]
There is no issue here. Select query returns array of rows. It is not clear why do expect sequelize to take first row and return only it. Why should it abandon all other rows? What if this query returns multiple rows? It is raw query. It is not analyzed.

**Comment by segersniels** [comment]
Because that's what the `plain` property does? It sets QueryType `SELECT` and then returns the first row. @sergeyjsg

**Comment by papb** [comment]
@sergeyjsg - @segersniels is right. SSCCE:

```js
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize('sqlite::memory:');
sequelize.define('foo', { status: DataTypes.STRING }, { timestamps: false });
await sequelize.sync();
const { count } = await sequelize.query(`SELECT COUNT(1) as count FROM foos f WHERE f.status = 'OK'`, { plain: true });
console.log(count); // 0
```

**Comment by SimonSchick** [comment]
Is this actually supported behaviour, I always used `const [{ count }] = ...`.
In any case PR needs test.

**Comment by papb** [comment]
@SimonSchick yeah it works indeed, I tested it

**Comment by bdinesh** [comment]
When I upgraded to v6 from v5.21.8 this issue popped up again
