### ISSUE TITLE
Unexpected error timeout, after running serverless

### ISSUE THREAD

**Issue by pisangGoreng** [sequelize/sequelize#11593]
## Issue Description
I have some issues with serverless & sequelize. After I’m running serverless offline on my local computer, I always get error like SequelizeConnectionError: connect ETIMEDOUT

### What are you doing?
Here, I'm using sequelize with serverless too. So I'm trying to increase more time out in sequelize connection, but I still get the same error. Below Im share my config for sequelize connection 

```
  const configSequelize = {
    logging: process.env.NODE_ENV === 'abc' ? console.log : null,
    dialect: Config.dialect,
    port: Config.port,
    host: Config.host,
    pool: {
      max: 5,
      min: 0,
      idle: 60000,
      acquire: 60000,
      handleDisconnects: true
    },
    dialectOptions: {
      multipleStatements: true,
      decimalNumbers: true,
      compress: true
    },
    retry: {
      match: [
        /ETIMEDOUT/,
        /EHOSTUNREACH/,
        /ECONNRESET/,
        /ECONNREFUSED/,
        /ETIMEDOUT/,
        /ESOCKETTIMEDOUT/,
        /EHOSTUNREACH/,
        /EPIPE/,
        /EAI_AGAIN/,
        /SequelizeConnectionError/,
        /SequelizeConnectionRefusedError/,
        /SequelizeHostNotFoundError/,
        /SequelizeHostNotReachableError/,
        /SequelizeInvalidConnectionError/,
        /SequelizeConnectionTimedOutError/
      ],
      max: 5
    },
    isolationLevel:
      Sequelize.Transaction.ISOLATION_LEVELS.SERIALIZABLE || 'SERIALIZABLE'
  };
```

### What do you expect to happen?
the SequelizeConnectionError: connect ETIMEDOUT is gone.

### What is actually happening?
```
Sequelize Connection Error -----------------------------

  SequelizeConnectionError: connect ETIMEDOUT
      at /Users/endysantoso/Desktop/tms-driver-delivery/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19
      at tryCatcher (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/endysantoso/Desktop/tms-driver-delivery/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.11.1
     Framework Version:         1.54.0
     Plugin Version:            3.1.2
     SDK Version:               2.1.2
     Components Core Version:   1.1.1
     Components CLI Version:    1.4.0

[nodemon] app crashed - waiting for file changes before starting...
```

### Environment
"mysql2": "^1.7.0",
"nodemon": "^1.19.2",
"sequelize": "^4.42.0",
"serverless": "^1.53.0",
"serverless-offline": "^5.11.0"

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Thanks

**Comment by papb** [comment]
Hello, I am not familiar with serverless, but I this doesn't seem like a problem with Sequelize. To be able to try to help you I would need an example github repository which reproduces the problem. Have you tried [serverless support](https://forum.serverless.com/) first?

I will close this for now, if you can really convince me that Sequelize is the core of the problem I may reopen, thanks for understanding!

**Comment by sharipovshoxrux** [comment]
Did find a solution, I have the same error

**Comment by pisangGoreng** [comment]
@sharipovshoxrux nope, Still find a solution for this error.

**Comment by papb** [comment]
Did one of you try their support? What did they say?

**Comment by qiqingfu** [comment]
@sharipovshoxrux I have the same problem. How did you solve it?

**Comment by goodniceweb** [comment]
@pisangGoreng @sharipovshoxrux @qiqingfu 
Did you find a solution?

BTW, this PR looks promising https://github.com/sequelize/sequelize/pull/12642. If you like it, here is a link to the doc in a human-readable way https://github.com/sequelize/sequelize/blob/ee3f724753f92d0b17ee2d38cb985196a06bc820/docs/manual/other-topics/aws-lambda.md. Even through I didn't come up with a solution yet, thanks to that guide I understand the problem area much better.
