### ISSUE TITLE
[Op.and] not working with multiple [Op.and].

### ISSUE THREAD

**Issue by ultimateakash** [sequelize/sequelize#11594]
```js
        var products, includeArr, query = {}; 
        query = _.map(req.body, function(value, key) { 
            return {
                [Op.and]: [
                    {
                        category_field_id: key
                    },
                    {
                        value: value
                    }
                ]
            };
        });
        includeArr = [{
            model: ItemDetail,
            required: true,
            where: {
                [Op.and]: query
            }
        }]

 
        products = await Item.findAll({
            attributes: {
                exclude: [
                    'createdAt',
                    'updatedAt'
                ]
            },
            where: {
                category_id: req.body.category_id
            },
            include: includeArr,
            order: [
                ['status', 'desc'],
                ['id', 'desc']
            ]
        });
```
its not giving any result.
```js
where: {
      [Op.and]: query       // and of multiple and
}
```
query 
```js
[ { [Symbol(and)]: [ { category_field_id: '1' }, { value: 'xxx' } ] },
  { [Symbol(and)]: [ { category_field_id: '2' }, { value: '12345' } ] },
  { [Symbol(and)]: [ { category_field_id: '3' }, { value: 'test type' } ] },
  { [Symbol(and)]: [ { category_field_id: '4' }, { value: 'test brand' } ] } ]
```

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). This issue will be closed for not following the issue template. Take a look in our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues).

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).

**Comment by mehmeteminsari** [comment]
What is the solution? Can you give an url ?
