### ISSUE TITLE
Adding a relation in a belongsToMany fires the beforeBulkCreate/afterBulkCreate hook in through model when using add function

### ISSUE THREAD

**Issue by BigsonLvrocha** [sequelize/sequelize#11600]
## Issue Description

Firing a hook in a model defined as through in a belongsToMany relationship is not covered in the documentation.

### What was unclear/insufficient/not covered in the documentation

The Hook section in Association subsection states only that
> When using add/set functions the beforeUpdate/afterUpdate hooks will run.

It doesn't mention that BulkCreate hooks will run in the through model when a record is inserted in target table

### If possible: Provide some suggestion on how we can enhance the docs

Add third item in the list stating that in a belongsToMany relationship, using add function will fire beforeBulkCreate/afterBulkCreate hooks defined in the model passed as through

### Additional context
Example
In a belongsToMany relashionship defined as 
`User.belongsToMany(Team,  { through: UserTeam })`
using 
`team.addUser(user)`
will run beforeBulkCreate/afterBulkCreate hooks in UserTeam model

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Interesting, nice catch. I wonder if `beforeBulkDestroy` and `afterBulkDestroy` are also executed when the `remove` method is called as well?

**Comment by BigsonLvrocha** [comment]
Yes, according to the source, with remove functions hooks will behave the same as the source is:
```javascript
/**
   * Un-associate one or more instance(s).
   *
   * @param {Model} sourceInstance instance to un associate instances with
   * @param {Model|Model[]|string|string[]|number|number[]} [oldAssociatedObjects] Can be an Instance or its primary key, or a mixed array of instances and primary keys
   * @param {Object} [options] Options passed to `through.destroy`
   *
   * @returns {Promise}
   */
  remove(sourceInstance, oldAssociatedObjects, options) {
    const association = this;

    options = options || {};

    oldAssociatedObjects = association.toInstanceArray(oldAssociatedObjects);

    const where = {
      [association.identifier]: sourceInstance.get(association.sourceKey),
      [association.foreignIdentifier]: oldAssociatedObjects.map(newInstance => newInstance.get(association.targetKey))
    };

    return association.through.model.destroy(_.defaults({ where }, options));
  }
```
beforeBulkDestroy/afterBulkDestroy hooks will run and individual beforeDestroy/afterDestroy hooks will only run when individualHooks is set to true in the options

**Comment by papb** [comment]
> as is already covered in the docs

Oops you're very right!! Sorry :grimacing:
