### ISSUE TITLE
queryinterface.sequelize.models is empty 

### ISSUE THREAD

**Issue by jy95** [sequelize/sequelize#11604]
## Issue Description

When running a seeder, `queryinterface.sequelize.models` is a empty object

### What are you doing?

I used the `sequelize init` command of the cli to set up a project.
I created manually some models ( without the cli )  and then I fill the file given by `sequelize seed:generate` 
I also created a `.sequelizerc` file with the following setup :
```js
const path = require('path');

module.exports = {
  'config': path.resolve('config', 'config.json'),
  'models-path': path.resolve('./models'),
  'seeders-path': path.resolve('./seeders'),
  'migrations-path': path.resolve('./migrations')
}
```

### What do you expect to happen?

I want to access my models.

### What is actually happening?

![image](https://user-images.githubusercontent.com/9306961/67500727-6c526a80-f683-11e9-9da3-f9da5136cb05.png)

### Environment

- Sequelize version: 5.21.1
- Cli version : 5.5.1
- Node.js version: 10.16.0

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Can you please try `const models = require('./relative/path/to/models/index.js')` and see if it gets your models? Let me know, thanks

**Comment by jy95** [comment]
What is the purpose to set "models-path" key in `.sequelizerc` if it is ignored ?
( I will test your solution in a short time )

**Comment by papb** [comment]
Well, it changed something, since the error is now different.

> What is the purpose to set "models-path" key in `.sequelizerc` if it is ignored ?

Wait, I never said it is working as intended, I am just trying to help you debug the issue so we can figure it out.

> I got a "ERROR: SequelizeDatabaseError: relation "Tag_Category" does not exist

Hmm, and have you triple checked that it does exist? What happens when you read your models outside the seeder context (i.e. in your real app)?

**Comment by jy95** [comment]
The table exists ( I can access it on PgAdmin 4 ) and it works in the main app , but not in seeders context
