### ISSUE TITLE
Model.create duplicated timestamps

### ISSUE THREAD

**Issue by charlitos85** [sequelize/sequelize#11602]
### What are you doing?
when create a new document using Model.create({...}) duplicated with all in lowercase the timestamps

return this

`
{
    "id": "123",
    "name": "xxxx",
    "lastname": "yyyy",
    "active": true,
    "updatedAt": "2019-10-24T11:58:39.484Z",
    "createdAt": "2019-10-24T11:58:39.484Z",
    "createdat": "2019-10-24T11:58:39.484Z",
    "updatedat": "2019-10-24T11:58:39.484Z"
}
`

the table was created by .sync() function

### Environment

- Sequelize version: 5.21.1 
- Posgress database: 10.7
- Posgress lib version: pg@7.12.1
- Node.js version: 10.16.3 
- Operating System: macOS mojave 10.14.6

**Comment by papb** [comment]
When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

This issue will be closed for lacking enough information to work on. Please update your issue and I will reopen it, thanks for understanding.
