### ISSUE TITLE
MYSQL dialect inserting no SRID

### ISSUE THREAD

**Issue by pieczorx** [sequelize/sequelize#11616]
## Issue Description
MYSQL dialect inserts no SRID

### What are you doing?
```javascript

const location = {
  type: 'Point',
  coordinates: [longitude, latitude],
  crs: { type: 'name', properties: { name: 'EPSG:4326'} }
};
const venue = await models.Venue.create({
  location,
})
```

### What do you expect to happen?
Insert record with SRID
`GeomFromText(POINT(19.495705 51.738169), 4326)`

Sequelize code:
![image](https://user-images.githubusercontent.com/14796199/67638124-aa4cca00-f8e1-11e9-9e9e-b9a3e77448b8.png)

### What is actually happening?
It inserts record without SRID:
`GeomFromText(POINT(19.495705 51.738169))`

Sequelize code:
![image](https://user-images.githubusercontent.com/14796199/67638127-b042ab00-f8e1-11e9-9a89-e45fa43b902c.png)

It may be related with wkx library, but i'm not sure where to post it.

### Environment
- Sequelize version: 5.21.1
- Node.js version: 6.9.0
- Operating System: Windows 10

### How does this problem relate to dialects?
- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MYSQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by pieczorx** [comment]
Similar issue happening to postgres: #11615

**Comment by papb** [comment]
@pieczorx Thanks for the report, I will close this one in favor of #11615 as you observed :)

**Comment by papb** [comment]
Hmmm looks like issue #11615 being fixed still leaves the problem in MySQL, so I will reopen this one
