### ISSUE TITLE
limit option produces 'missing FROM-clause entry for table' error

### ISSUE THREAD

**Issue by mahnunchik** [sequelize/sequelize#11617]
## Issue Description

findOne produces 'missing FROM-clause entry for table' error on PostgreSQL.

### What are you doing?

User.js
```js
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'users',
    paranoid: false,
    timestamps: false,
  });
  User.associate = function(models) {
    // associations can be defined here
    User.hasMany(models.Project, {
      foreignKey: {
        name: 'userId',
        allowNull: false,
      },
    });
  };
  return User;
};
```

Project.js
```js
module.exports = (sequelize, DataTypes) => {
  const Project = sequelize.define('Project', {
    value: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'projects',
    paranoid: false,
    timestamps: false,
  });
  Project.associate = function(models) {
    // associations can be defined here
    Project.belongsTo(models.User, {
      foreignKey: {
        name: 'userId',
        allowNull: false,
      },
    });
  };
  return Project;
};
```

I'd like to find any (`findOne`) user without projects.

```js
const user = await models.User.findOne({
  where: {
    '$Project.value$': { [models.Sequelize.Op.eq]: null }
  },
  include: [{
    model: models.Project,
    required: false,
  }],
});
```

### What do you expect to happen?

A user without projects.

### What is actually happening?

`error: missing FROM-clause entry for table "Projects"`

### Additional context

`findAll` works as expected.

```js
const users = await models.User.findAll({
  where: {
    '$Project.value$': { [models.Sequelize.Op.eq]: null }
  },
  include: [{
    model: models.Project,
    required: false,
  }],
});
```

### Environment

- Sequelize version: 5.21.1
- Node.js version: v10.16.3
- Operating System: macOS/Docker
- If TypeScript related: TypeScript version: no

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by mahnunchik** [comment]
Update `limit` option brakes `findAll` query like `findOne`.

**Comment by papb** [comment]
Thanks for the report, can you please post what SQL query was generated by Sequelize and what SQL query it should have generated instead? Thanks

**Comment by mahnunchik** [comment]
Hi,

`subQuery: false,` helps me, but it was not obvious.

**Comment by papb** [comment]
Thanks, indeed the fact that it is not obvious is enough for this to be still an issue, even if you found a solution. So if possible, please post what SQL query was generated by Sequelize and what SQL query it should have generated instead :)

**Comment by mahnunchik** [comment]
Expected:

```sql
SELECT "User"."id", "User"."kind", "User"."value" FROM "users" AS "User" LEFT OUTER JOIN "projects" AS "Project" ON "User"."id" = "Project"."userId" WHERE "Project"."value" IS NULL LIMIT 1000;
```

Actual:

```sql
SELECT "User".* FROM (SELECT "User"."id", "User"."kind", "User"."value" FROM "users" AS "User" WHERE "Project"."value" IS NULL LIMIT 1000) AS "User" LEFT OUTER JOIN "projects" AS "Project" ON "User"."id" = "Project"."userId";
```

**Comment by papb** [comment]
And what SQL did you get after adding `subquery: false`? Did you get your exact expected output?

**Comment by mahnunchik** [comment]
Yep, I've got expected output. But I don't know about performance.

**Comment by papb** [comment]
Can you post the SQL generated please?

**Comment by mahnunchik** [comment]
Both of them are generated. With and without `subquery: false`.

**Comment by papb** [comment]
Sorry, I still don't understand

> Actual:
> 
> ```sql
> SELECT "User".* FROM (SELECT "User"."id", "User"."kind", "User"."value" FROM "users" AS "User" WHERE "Project"."value" IS NULL LIMIT 1000) AS "User" LEFT OUTER JOIN "projects" AS "Project" ON "User"."id" = "Project"."userId";
> ```

This is what you got without `subquery: false`, right? So what SQL query did you get with `subquery: false`?

**Comment by mahnunchik** [comment]
```js
const users = await models.User.findAll({
  where: {
    '$Project.value$': { [models.Sequelize.Op.eq]: null }
  },
  include: [{
    model: models.Project,
    required: false,
  }],
  limit: 1000,
});
```

Produces:

```sql
SELECT "User".* FROM (SELECT "User"."id", "User"."kind", "User"."value" FROM "users" AS "User" WHERE "Project"."value" IS NULL LIMIT 1000) AS "User" LEFT OUTER JOIN "projects" AS "Project" ON "User"."id" = "Project"."userId";
```

And the error: `error: missing FROM-clause entry for table "Projects"`

---

```js
const users = await models.User.findAll({
  where: {
    '$Project.value$': { [models.Sequelize.Op.eq]: null }
  },
  include: [{
    model: models.Project,
    required: false,
  }],
  limit: 1000,
  subQuery: false,
});
```

Produces:

```sql
SELECT "User"."id", "User"."kind", "User"."value" FROM "users" AS "User" LEFT OUTER JOIN "projects" AS "Project" ON "User"."id" = "Project"."userId" WHERE "Project"."value" IS NULL LIMIT 1000;
```

**Comment by mahnunchik** [comment]
Hi @papb `limit` option still brakes `find*` queries even in `6.0.0-beta.5`

**Comment by rodrigoachilles** [comment]
> Hi @papb `limit` option still brakes `find*` queries even in `6.0.0-beta.5`

@mahnunchik, i have the same problem with the `limit` when i use `subQuery: false`. Someone resolved this issue?

**Comment by mahnunchik** [comment]
Yep `subQuery: false` helps me.

**Comment by rodrigoachilles** [comment]
> Yep `subQuery: false` helps me.

Ok, but the `limit` stopped working. How can you resolve this issue?

**Comment by lautarobock** [comment]
is this expected to be solved?

**Comment by jokopain** [comment]
is it still issue?

**Comment by lautarobock** [comment]
AFAIK yes

**Comment by cmccann702** [comment]
Is anyone looking at this currently? Issue for me is with multiple includes and limit

**Comment by jmwielandt** [comment]
I had the same problem but a findOne without any limit. `subQuery: false` solved it but it should be documented (see #7865 )

**Comment by GhifariSiregar** [comment]
> ```js
> const users = await models.User.findAll({
>   where: {
>     '$Project.value$': { [models.Sequelize.Op.eq]: null }
>   },
>   include: [{
>     model: models.Project,
>     required: false,
>   }],
>   limit: 1000,
> });
> ```
> 
> Produces:
> 
> ```sql
> SELECT "User".* FROM (SELECT "User"."id", "User"."kind", "User"."value" FROM "users" AS "User" WHERE "Project"."value" IS NULL LIMIT 1000) AS "User" LEFT OUTER JOIN "projects" AS "Project" ON "User"."id" = "Project"."userId";
> ```
> 
> And the error: `error: missing FROM-clause entry for table "Projects"`
> 
> ```js
> const users = await models.User.findAll({
>   where: {
>     '$Project.value$': { [models.Sequelize.Op.eq]: null }
>   },
>   include: [{
>     model: models.Project,
>     required: false,
>   }],
>   limit: 1000,
>   subQuery: false,
> });
> ```
> 
> Produces:
> 
> ```sql
> SELECT "User"."id", "User"."kind", "User"."value" FROM "users" AS "User" LEFT OUTER JOIN "projects" AS "Project" ON "User"."id" = "Project"."userId" WHERE "Project"."value" IS NULL LIMIT 1000;
> ```

I found something with this. I am trying to include the attributes such as:
```const users = await models.User.findAll({
  where: {
    '$Project.value$': { [models.Sequelize.Op.eq]: null }
  },
  attributes: {
      include: ['col1', 'col2']
  },
  include: [{
    model: models.Project,
    required: false,
  }],
  limit: 1000,
});```

And the query is working without u need to add `subQuery: false`

**Comment by GhifariSiregar** [comment]
I found something with this. I am trying write the attributes with:
```
const users = await models.User.findAll({
  where: {
    '$Project.value$': { [models.Sequelize.Op.eq]: null }
  },
  include: [{
    model: models.Project,
    required: false,
  }],
  limit: 1000,
});
```

And the query is working without u need to add `subQuery: false`

**Comment by visoft** [comment]
This is still an issue with v6.7.0. No combination works when including `limit` on an `include`.

**Comment by ldonjibson** [comment]
any update ? I seriously facing this issue

**Comment by mehmetalpsumer** [comment]
Also facing this issue. Tried adding `required: true` to the included models, but did not work still.

**Comment by ldonjibson** [comment]
I think subQuery: false solved it for me. on the parent Model

**Comment by carsonweinand** [comment]
Hi, what is the status of this. I'm facing this issue and it is a serious problem for my application. When adding limit to .findAll or .findAndCountAll I receive the "missing FROM-clause entry for table" error. 

I upgraded from Sequelize version 6.8.0 to version 6.17.0 and still get the error.

**Comment by ephys** [comment]
Looks like I missed this one

In an effort the centralize this issue, I'll redirect the conversation to https://github.com/sequelize/sequelize/issues/12971#issuecomment-1016336123, as it seems to be the same issue

**Comment by vosho** [comment]
`subQuery: false`
makes the result `distinct`. 
It's not the prefect anwser.

**Comment by bugrevealingbme** [comment]
5 years and still no solution?

**Comment by TannerS** [comment]
false on subquery fixes this same bug i am hving but breaks limit. ANy word?

**Comment by notAxion** [comment]
for my case adding `separate: true` fixed the problem
