### ISSUE TITLE
PostGIS Geometry column loses its SRID after selecting from a database

### ISSUE THREAD

**Issue by t0lik** [sequelize/sequelize#11615]
## Issue Description
If I have a column of the Geometry type (PostGIS) and tries to select its value I get GeoJSON without SRID information

### What are you doing?
I select records from a table with geometry column (Postgres DB with PostGIS) and I get them without SRID information, only geometry itself.
Here is an example:

1. Create a table
```sql
CREATE TABLE public.test_geom
(
  id integer NOT NULL DEFAULT nextval('test_geom_id_seq'::regclass),
  geom geometry
)
WITH (
  OIDS=FALSE
);
```
2. Insert a test record with SRID:
```sql
insert into test_geom
(geom)
values(ST_SETSRID(ST_GeomFromText('POINT(30 60)'), 4326));
```
3. Check geometry and SRID in the table:
```sql
select st_srid(geom),* from test_geom
```
Output:
![изображение](https://user-images.githubusercontent.com/400628/67623584-b8daa900-f82f-11e9-90f7-6810af53b1ad.png)

4. Create a sequelize connection and define the table model:
```js
const Sequelize = require('sequelize')

const sequelize = new Sequelize('test_gis', 'postgres', 'postgres', {
  host: 'localhost',
  dialect: 'postgres'
})

const TestGeom = sequelize.define('testGeom', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true,
    allowNull: false
  },
  geom: {
    type: Sequelize.GEOMETRY
  }
}, {
  schema: 'public',
  tableName: 'test_geom',
  timestamps: false
})
```
### What do you expect to happen?
In the case I have SRID in the geometry column of the DB record I expect to retrieve it with SRID information:

```js
  const geomObj = await TestGeom.findOne()
  console.log(geomObj.geom)
```
Output:
```
Executing (default): SELECT "id", "geom" FROM "public"."test_geom" AS "testGeom" LIMIT 1;
{ type:'Point', crs:{ type: 'name', properties: { name: 'EPSG:4326'} }, coordinates: [30,60] }
```
and updating the record with this geometry does not lose SRID info:
Output:
![изображение](https://user-images.githubusercontent.com/400628/67623584-b8daa900-f82f-11e9-90f7-6810af53b1ad.png)

### What is actually happening?
1. Get the record from db via sequelize
```js
  const geomObj = await TestGeom.findOne()
  console.log(geomObj.geom)
```
Output:
```
Executing (default): SELECT "id", "geom" FROM "public"."test_geom" AS "testGeom" LIMIT 1;
{ type: 'Point', coordinates: [ 30, 60 ] }
```
There is no "crs" property in retrieved GeoJSON object.

2. Update retrieved geometry in the table:
```js
  await TestGeom.update({
    geom: geomObj.geom
  }, {
    where: {
      id: geomObj.id
    }
  })
```
Output:
```
Executing (default): UPDATE "public"."test_geom" SET "geom"=ST_GeomFromGeoJSON('{"type":"Point","coordinates":[30,60]}') WHERE "id" = 3
```
3. Check geometry and SRID in the table once again:
```sql
select st_srid(geom),* from test_geom
```
Output:
![изображение](https://user-images.githubusercontent.com/400628/67623693-0acffe80-f831-11e9-856f-e16ec40156e5.png)

There is no "SRID" in retrieved record.

### Environment

- Sequelize version: sequelize@4.44.3
- Node.js version: v10.16.3
- Operating System: Windows 10 1903

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I'm not sure I can correctly fix this issue by PR.
I can show the issue location in the source code and you can decide how to fix it:
file: postgres/data-types.js
```js
GEOMETRY.parse = GEOMETRY.prototype.parse = function parse(value) { 
  const b = new Buffer(value, 'hex'); 
  return wkx.Geometry.parse(b).toGeoJSON(); 
}
```
This can be resolved by passing options.shortCrs or options.longCrs to toGeoJSON function call.
To indicate what exact form of crs to use short or long you can add option in the column definition of the model, for example:
```js
  geom: {
    type: Sequelize.GEOMETRY,
    crs: 'none' // possible values: none - old behaviour, short - return GeoJSON with the short form of crs (options.shortCrs), long - return GeoJSON with the long form of crs (options.longCrs)
  }
```

**Comment by papb** [comment]
Thanks for the report, hopefully someone can investigate it further soon :)

**Comment by t0lik** [comment]
In #11616 there is no SRID after saving, which is not my case, but can be also related to wkx library.
In my case I get geometry with no SRID but if I manually add "crs" prop to geometry then it is saved in the db correctly (i.e. with SRID).

**Comment by Nymria** [comment]
Confirmed, selected GEOMETRY is losing SRID info. Waiting for a fix, or workaround if possible

**Comment by t0lik** [comment]
What major versions of sequelize will be affected by this fix?

**Comment by papb** [comment]
@t0lik Only v6, since this PR was merged to master. If you would like to see this in v5, you are welcome to open a new PR targeting it (just cherry-pick [this commit](cb22281) on top of v5 and fix whatever conflicts may arise)
