### ISSUE TITLE
Mysql DEFAULT CURRENT_TIMESTAMP on create() return value is not timestamp

### ISSUE THREAD

**Issue by phoenixsky** [sequelize/sequelize#11610]
## Issue Description
when I insert one  record use sequelize.create()
the return value like this 
```js
 {
            "name": "1",
            "createAt": {
                "val": "CURRENT_TIMESTAMP"
            },
            "updateAt": {
                "val": "CURRENT_TIMESTAMP"
            },
            "id": 1
}
```

I query this record after create 
it's ok 
```js
     {
            "id": 36,
            "name": "1",
            "createAt": "2019-10-25T03:21:20.000Z",
            "updateAt": "2019-10-25T03:21:20.000Z"
        },
```

How can i define 

### mysql stucture like this
```sql 
CREATE TABLE `channel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL, 
  `createdAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
###  sequelize-auto generate the define file

```js
module.exports = function(sequelize, DataTypes) {
	return sequelize.define('channel', {
		id: {
			type: DataTypes.INTEGER(11),
			allowNull: false,
			primaryKey: true,
			autoIncrement: true
		},
		name: {
			type: DataTypes.STRING(255),
			allowNull: true
		},
		createAt: {
			type: DataTypes.DATE,
			allowNull: true,
			defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
		},
		updateAt: {
			type: DataTypes.DATE,
			allowNull: true,
			defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
		}
	}, {
		tableName: 'channel',
		timestamps: false
	});
};

### node.js 
```js
   let data = {name :'foo'};
    // channelDao is Sequelize model
    let channel = await channelDao.create(data);
    console.log(channel);
```

> the channel like this

```
 {
            "name": "1",
            "createAt": {
                "val": "CURRENT_TIMESTAMP"
            },
            "updateAt": {
                "val": "CURRENT_TIMESTAMP"
            },
            "id": 1
}
```

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). This issue will be closed for not following the issue template. Take a look in our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues).

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).

**Comment by Congee** [comment]
Use `defaultValue: DataTypes.NOW`
