### ISSUE TITLE
How to make custom query method?

### ISSUE THREAD

**Issue by dimaninc** [sequelize/sequelize#11630]
### Is your feature request related to a problem? Please describe.
I want to create predefined requests inside models like I do them in Mongoose (example below), but I can't find this ability in manuals

### Describe the solution you'd like
In Mongoose i can do something like this:

```js
UserSchema.query.byAgeAndGender = function(age, gender) {
    return this.find({
        age,
        gender,
    });
};

// and then use it

UserModel.find().byAgeAndGender({
    age: 20,
    gender: 'm',
});
```

### Why should this be in Sequelize
This will prevent copy-pasting of code for queries

### Describe alternatives/workarounds you've considered
A clear and concise description of any alternative solutions or features you've considered. If any workaround exists to the best of your knowledge, include it here.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
You can simply do the following:

```js
// Definition
UserModel.findAllByAgeAndGender = function(age, gender) {
  return UserModel.findAll({
    where: {
      age,
      gender
    }
  });
};

// Usage
UserModel.findAllByAgeAndGender(20, 'm').then(users => {
  console.log(users.length);
});
```

For more flexibility, allowing extra options, such passing a transaction and other things, you can do:

```js
// Definition
UserModel.findAllByAgeAndGender = function(age, gender, options) {
  const options = Object.assign({}, options);
  options.where = { age, gender };
  return UserModel.findAll(options);
};

// Usage
UserModel.findAllByAgeAndGender(20, 'm', { transaction: t }).then(users => {
  console.log(users.length);
});
```
