### ISSUE TITLE
Order to main query

### ISSUE THREAD

**Issue by Devoldini** [sequelize/sequelize#11636]
```
    models.modelOne.findOne({
    attributes: [ 'id', 'name' ],
    where: { name },
    include: [
      {
        model: models.modelTwo,
        attributes: ['id', 'name'],
        where: {name: nameTwo},
        required: false
      }
    ],
    order: [
      [ ???? ]
    ]
  });
```

How to order by modelOne by 'id'? I need to order it by modelOne by 'id' in 'DESC'
If i do like 

```
    order: [
      [ 'id', 'DESC' ]
    ]
```

it says me next: 

message: 'A column has been specified more than once in the order by list. Columns in the order by list m ust be unique.'

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.

**Comment by Devoldini** [comment]
**models/users.js**

`module.exports = (dbTravelDocsApi, DataTypes) => {
    const User = dbTravelDocsApi.define('user', {
        id: {
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            type: DataTypes.INTEGER
        },
        tBotId: {
            allowNull: false,
            type: DataTypes.INTEGER
        },
        name: {
            allowNull: false,
            type: DataTypes.STRING
        },
        role: {
            allowNull: false,
            type: DataTypes.INTEGER
        },
        activity: {
            allowNull: false,
            type: DataTypes.BOOLEAN
        }
    }, {
        timestamps: false
    });

    User.associate = models => {
        models.User.hasMany(
          models.TelegramCode,
          { foreignKey: 'userId', sourceKey: 'id' }
          );
    };

    return User;
};`

**models/telegramcode.js**

`module.exports = (dbTravelDocsApi, DataTypes) => {
    const TelegramCode = dbTravelDocsApi.define('telegramcode', {
        id: {
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            type: DataTypes.INTEGER
        },
        userId: {
            allowNull: false,
            type: DataTypes.INTEGER
        },
        passcode: {
            allowNull: false,
            type: DataTypes.INTEGER
        },
        expiredOn: {
            allowNull: false,
            type: DataTypes.DATE
        }
    }, {
        timestamps: false
    });

    TelegramCode.associate = models => {
        models.TelegramCode.belongsTo(
          models.User,
          { foreignKey: 'userId', targetKey: 'id' }
          );
    };

    return TelegramCode;
};`

**query:**
`
  const code = await models.TelegramCode.findOne({
    attributes: [ 'passcode', 'expiredOn' ],
    include: [
      {
        model: models.User,
        attributes: ['id', 'name'],
        where: {name: userName},
        required: false
      }
    ],
    order: [
      [ models.User, 'id', 'ASC' ]
    ]
  });
`
Hope i've done it right.
So i need to order all my output from query by 'id' field by 'ASC' NOT models.User, i need to order it by models.TelegramCode

**Comment by papb** [comment]
> Hope i've done it right.

Hi, what you posted may be enough, I don't know, but if you have time, please follow the instructions on [sequelize-sscce](https://github.com/papb/sequelize-ssce), start by forking the repository.

If you do that, you will save a lot of time from people that try to help you :)
