### ISSUE TITLE
Sequelize associate a array field to a model

### ISSUE THREAD

**Issue by thiagofernando** [sequelize/sequelize#11637]
I need to associate two tables one of them have a array field (the values is the id of that another one) and generating a query.

on table associations i have tried belongsToMany and just belongsTo. No success.

this is the query I hope to generate through sequelize

```select
    basket.basket_id, as BasketId,
    item.item_id as ItemId,
    item.description as ItemDescription 
from  basket
inner join item on
    item.item_id = any(basket.item_array) 
where
    "some field"
```

the structure of tables
```
CREATE TABLE basket(
  basket_id SERIAL PRIMARY KEY,
  customer_id integer,
  item_array INTEGER[],
... some other fields
);

CREATE TABLE item(
  item_id SERIAL PRIMARY KEY,
  description text NOT NULL,
... some other fields
);
```

I think it would be very useful to make this kind of association in the sequelizes core

Im using sequelize with postgres. (latest version of both).

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x ] Yes. This issue only applies to the following dialect(s): dialects with nosql support 

### Would you be willing to resolve this issue by submitting a Pull Request? No

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
> this is the query I hope to generate through sequelize

Is it a SELECT?

Also, can you please post your model definitions?

**Comment by thiagofernando** [comment]
yes, its a select.

```
module.exports = (sequelize, DataTypes) => {
  
  const basket = sequelize.define('Basket', {
    
      basket_id       : {
        type         : DataTypes.INTEGER,
        primaryKey   : true,
        autoIncrement: true
      },
      customer_id   : {
        type     : DataTypes.INTEGER,
        allowNull: false
      },
      item     : {
        type     : DataTypes.ARRAY(DataTypes.INTEGER),
        allowNull: false
      },
    },
    {
      tableName: 'basket',
    }
  );
  
  basket.associate = models => {
    basket.belongsTo(models.Item, {foreignKey: 'item'});
  };
  
  return basket;
};
```

```
module.exports = (sequelize, DataTypes) => {
  
  const item = sequelize.define('Item', {
    
      item_id       : {
        type         : DataTypes.INTEGER,
        primaryKey   : true,
        autoIncrement: true
      },
      description   : {
        type     : DataTypes.TEXT,
        allowNull: false
      },
      category     : {
        type     : DataTypes.INTEGER,
        allowNull: false
      },
      value     : {
        type     : DataTypes.DECIMAL(17, 9),
        allowNull: false
      },
    },
    {
      tableName: 'item',
    }
  );
  
  item.associate = models => {
    item.hasMany(models.Basket, {foreignKey: 'item'});
  };
  
  return item;
};
```

**Comment by jamunasasi** [comment]
Any update for this?

**Comment by StevenWung** [comment]
Any update for this?

**Comment by thiagofernando** [comment]
> 
> 
> > this is the query I hope to generate through sequelize
> 
> Is it a SELECT?
> 
> Also, can you please post your model definitions?

any news on this?

**Comment by ardaorkin** [comment]
is there anyone who succeeded to solve the issue?

**Comment by ephys** [comment]
I don't know if such a feature is going to be added to sequelize unless a dialect starts supporting arrays of foreign keys.

I would recommend using a through-table. Or, if you really want to use an array of FKs, https://github.com/sequelize/sequelize/issues/11788 is the issue about being able to define custom joins.
