### ISSUE TITLE
Add support for schema in queryInterface.addConstraint method inside references attribute

### ISSUE THREAD

**Issue by AlexVanHell** [sequelize/sequelize#11650]
## Issue Description
queryInterface.addConstraint method does not have support for schema specification inside references attribute

### What are you doing?
Trying to add a foreign key to a table that does not belong to 'public' schema in postgres

```ts
await queryInterface.addConstraint({
    schema: 'something',
    tableName: 'person'
}, ['company_id'], {
    type: 'foreign key',
    name: 'fk_name',
    references: {
        schema: 'something', // <--- This
        table: 'company',
        field: 'id'
    },
    onUpdate: 'cascade',
    onDelete: 'cascade'
});
```

### What do you expect to happen?
That resulting query outputs:

```sql
ALTER TABLE "something"."person"
ADD CONSTRAINT "fk_name"
FOREIGN KEY ("company_id")
REFERENCES "something"."company" ("id")
ON UPDATE CASCADE
ON DELETE CASCADE
```

### What is actually happening?

_The output was Bar!_

Due to there is no an option to specify the schema inside references attribute I'm getting the following sql output

```sql
ALTER TABLE "something"."person"
ADD CONSTRAINT "fk_name"
FOREIGN KEY ("company_id")
REFERENCES "company" ("id")
ON UPDATE CASCADE
ON DELETE CASCADE
```

And then an error: `Error relation "company" does not exist`

### Additional context

What am I doing wrong, is there another way to achive this?

I also tried something like this:

```ts
await queryInterface.addConstraint({
    schema: 'something',
    tableName: 'person'
}, ['company_id'], {
    type: 'foreign key',
    name: 'fk_name',
    references: {
        table: 'something.company', // '"something"."company"'
        field: 'id'
    },
    onUpdate: 'cascade',
    onDelete: 'cascade'
});
```

And none worked succesfully 

To solve my problem temporarily I wrote this code

```ts
import { QueryInterface } from 'sequelize';

interface AddForeignKeyOptions {
	name: string;
	references: {
		schema: string;
		table: string;
		field: string;
	};
	onUpdate: string;
	onDelete: string;
	logging?: boolean | ((sql: string) => void);
}

export const addForeignKey = (queryInterface: QueryInterface, table: { tableName: string, schema: string }, attributes: string[], options: AddForeignKeyOptions) => {
	const sql = `ALTER TABLE "${table.schema}"."${table.tableName}"
		ADD CONSTRAINT "${options.name}"
		FOREIGN KEY (${attributes.map(a => '"' + a + '"').join(', ')})
		REFERENCES "${options.references.schema}"."${options.references.table}" ("${options.references.field}")
		ON UPDATE ${options.onUpdate.toUpperCase()}
		ON DELETE ${options.onDelete.toUpperCase()}`;

	if (typeof options.logging === 'function') {
		options.logging(`Executing (default): ${sql}`);
	}

	return queryInterface.sequelize.query(sql);
};
```

### Environment

- Sequelize version: 5.21.2 
- Node.js version: 10.16.0 
- Operating System: XXX
- If TypeScript related: TypeScript version: 3.5.1

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ekeuus** [comment]
Any update with this?

**Comment by CharlesEgan** [comment]
Best bet is to use the workaround described by the OP.

**Comment by Rc85** [comment]
This needs attention and implemented.

**Comment by lyridwan** [comment]
I tried something like this, and it works for me:
tested on: v6.6.5

```javascript
queryInterface.addConstraint("Posts", {
    fields: ["username"],
    type: "foreign key",
    name: "custom_fkey_constraint_name",
    references: {
        table: {
            tableName: target_table_name,
            // define schema here
            schema: target_table_schema,
        },
        field: "target_column_name",
    },
    onDelete: "cascade",
    onUpdate: "cascade",
});
````

**Comment by Josh-Zirena** [comment]
> 

Thanks for sharing, I found your solution super helpful!

**Comment by Josh-Zirena** [comment]
> I tried something like this, and it works for me: tested on: v6.6.5
> 
> ```js
> queryInterface.addConstraint("Posts", {
>     fields: ["username"],
>     type: "foreign key",
>     name: "custom_fkey_constraint_name",
>     references: {
>         table: {
>             tableName: target_table_name,
>             // define schema here
>             schema: target_table_schema,
>         },
>         field: "target_column_name",
>     },
>     onDelete: "cascade",
>     onUpdate: "cascade",
> });
> ```

Thanks for sharing, I found your solution very helpful!

**Comment by ephys** [comment]
> I tried something like this, and it works for me:

That is the actual officially supported solution. Should be clearer once we're done strictly typing queryInterface. :)
