### ISSUE TITLE
Creating an OR relationship between parent and nested model where clauses

### ISSUE THREAD

**Issue by jamesperi** [sequelize/sequelize#11658]
### What are you doing?

I'm trying to create a query that returns a record if the where clause on the parent model OR the where clause in an "included" child model match the condition

https://github.com/jamesperi/sequelize-sscce/blob/patch-1/src/sscce.js

### What do you expect to happen?

I would expect a row to return if (based on the example SSCCE provided, either Author.name OR Author.nickname OR Reader.username matches the query term

### What is actually happening?

No records are returned. In my own enviornment I'm using SQL. and the resulting snippet shows the issue:

![image](https://user-images.githubusercontent.com/4944422/68336749-e1666c80-0093-11ea-815d-684bb5645bbb.png)

### Environment

- Sequelize version: 5.21.2
- Node.js version: 10.13.0
- Operating System: Centos

### How does this problem relate to dialects?

- [X ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jamesperi** [comment]
Update:

In digging through this issue, I did come up with what "may?" be the correct approach to this but in doing so, i think i've either stumbled into a different bug?

Using the attached SSCCE, if the query is changed to the following:

```
log(
    await Author.findAll({
      where: { [Op.or]: [{ name: searchTerm }, { nickname: searchTerm }, { '$Books.Readers.username$': searchTerm }] },
      include: [{ model: Book, include: [{ model: Reader }] }]
    })
  )
```



Then everything seems to work as I'd expect, the SQL looks as follows:


```
SELECT 
    `Author`.`id`,
    `Author`.`name`,
    `Author`.`nickname`,
    `Author`.`createdAt`,
    `Author`.`updatedAt`,
    `Books`.`id` AS `Books.id`,
    `Books`.`title` AS `Books.title`,
    `Books`.`createdAt` AS `Books.createdAt`,
    `Books`.`updatedAt` AS `Books.updatedAt`,
    `Books`.`AuthorId` AS `Books.AuthorId`,
    `Books->Readers`.`id` AS `Books.Readers.id`,
    `Books->Readers`.`username` AS `Books.Readers.username`,
    `Books->Readers`.`createdAt` AS `Books.Readers.createdAt`,
    `Books->Readers`.`updatedAt` AS `Books.Readers.updatedAt`,
    `Books->Readers`.`BookId` AS `Books.Readers.BookId`
FROM
    `Authors` AS `Author`
        LEFT OUTER JOIN
    `Books` AS `Books` ON `Author`.`id` = `Books`.`AuthorId`
        LEFT OUTER JOIN
    `Readers` AS `Books->Readers` ON `Books`.`id` = `Books->Readers`.`BookId`
WHERE
    (`Author`.`name` = 'Steve'
        OR `Author`.`nickname` = 'Steve'
        OR `Books->Readers`.`username` = 'Steve');
```



The issue is that when I add a limit in, the query fails..

```
log(
    await Author.findAll({
      where: { [Op.or]: [{ name: searchTerm }, { nickname: searchTerm }, { '$Books.Readers.username$': searchTerm }] },
      include: [{ model: Book, include: [{ model: Reader }] }],
      limit: 10
    })
  )
```

SequelizeDatabaseError: SQLITE_ERROR: no such column: Books->Readers.username


The SQL changed to:

```
SELECT 
    `Author`.*,
    `Books`.`id` AS `Books.id`,
    `Books`.`title` AS `Books.title`,
    `Books`.`createdAt` AS `Books.createdAt`,
    `Books`.`updatedAt` AS `Books.updatedAt`,
    `Books`.`AuthorId` AS `Books.AuthorId`,
    `Books->Readers`.`id` AS `Books.Readers.id`,
    `Books->Readers`.`username` AS `Books.Readers.username`,
    `Books->Readers`.`createdAt` AS `Books.Readers.createdAt`,
    `Books->Readers`.`updatedAt` AS `Books.Readers.updatedAt`,
    `Books->Readers`.`BookId` AS `Books.Readers.BookId`
FROM
    (SELECT 
        `Author`.`id`,
            `Author`.`name`,
            `Author`.`nickname`,
            `Author`.`createdAt`,
            `Author`.`updatedAt`
    FROM
        `Authors` AS `Author`
    WHERE
        (`Author`.`name` = 'Steve'
            OR `Author`.`nickname` = 'Steve'
            OR `Books->Readers`.`username` = 'Steve')
    LIMIT 10) AS `Author`
        LEFT OUTER JOIN
    `Books` AS `Books` ON `Author`.`id` = `Books`.`AuthorId`
        LEFT OUTER JOIN
    `Readers` AS `Books->Readers` ON `Books`.`id` = `Books->Readers`.`BookId`;
```

**Comment by dnguyen-accor** [comment]
i think this is related https://github.com/sequelize/sequelize/issues/7344

**Comment by ephys** [comment]
Unfortunately I can't debug this because the SSCCE has been deleted :(

**Comment by WikiRik** [comment]
> Unfortunately I can't debug this because the SSCCE has been deleted :(

https://github.com/sequelize/sequelize-sscce/pull/24 I can see this code

**Comment by ephys** [comment]
Thanks! I'll add it to my list

**Comment by Mena489** [comment]
Any updates on this issue?

**Comment by Mena489** [comment]
@ephys 

Any updates on this issue?

**Comment by ephys** [comment]
OK so I looked into this and there is no bug here.

What's happening is that `include` produces a simple LEFT JOIN by default. Making it possible to reference the association attribute from the top where clause.

When `limit` is added, the AUTHOR select is turned into a subquery to apply the limit only to that model (in this instance, the `Author` model).

You can force this to use a LEFT JOIN again by using `subquery: false`, but then the limit will apply globally to the whole query.

This is a very issue caused by the API being difficult to understand. This will be solved by [the redesign](https://github.com/sequelize/sequelize/issues/15260) as it splits `include` and `join` to make their restrictions more obvious.

**Comment by sacalito** [comment]
@jamesperi  THANKYOU!!!
