### ISSUE TITLE
Automatically ensure path for storage.db when setting up SQLite

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11663]
### Is your feature request related to a problem? Please describe.
`SQLITE_CANTOPEN` error occurs when Sequelize is setup with a path to `storage.db` with folders that don't exist.

### Describe the solution you'd like
Sequelize could automatically create the necessary folders when this happens.

### Why should this be in Sequelize
Just for convenience

### Describe alternatives/workarounds you've considered
Leave to users do it themselves

### Additional context
See #3551

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [X] Yes. This issue only applies to the following dialect(s): SQLite

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Suggestion for anyone considering to take this: use [fs-jetpack](https://github.com/szwacz/fs-jetpack).

Note: fs-jetpack is already a dev-dependency in sequelize, don't forget to change it into a standard dependency in this case

**Comment by multum** [comment]
@papb Hi! I would like to contribute. Can i take this?

**Comment by papb** [comment]
Hi @multum, sorry to take so long to reply. I have been immensely busy :sweat_smile: are you still interested in helping? Thank you!!

**Comment by multum** [comment]
@papb, it's okay. Yes, i'm still interested😊

**Comment by papb** [comment]
@multum awesome. Feel free to start working on it whenever you want. I suggest using fs-jetpack, and I would do the following: test if the given file exists; if it doesnt, create the folder for it. A trick I use to create the folder in cases like this is writing an empty file there (because fs-jetpack will create all necessary folders) and then deleting the file afterwards (the intermediate folders will be kept)

Let me.know if you need more guidance :grimacing:
