### ISSUE TITLE
bulkCreate failing on conflict

### ISSUE THREAD

**Issue by T0TProduction** [sequelize/sequelize#11667]
## Issue Description
When using postgres 11+ and `bulkCreate`, sequelize unexpectedly fails on duplicates.
According to [the documentation](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-bulkCreate) it should work.
When actively defining the `updateOnDuplicate` Array, it does not fail anymore.

### What are you doing?

```js
// this is in async context, so that we can use awaits
import Sequelize from 'sequelize';
const sequelize =new Sequelize.Sequelize(ourInternalSequelizeconfig);

export class fortnite_items extends Sequelize.Model { }
fortnite_items.init({
  itemid: { type: Sequelize.STRING, primaryKey: true },
  name: Sequelize.STRING,
  description: Sequelize.STRING,
  }, { sequelize });

const itemlist = [{itemid:'test1', name:'test1name', description:'test1desc'},
{itemid:'test2', name:'test2name', description:'test2desc'}];

await fortnite_items.bulkCreate(itemlist); // works
await fortnite_items.bulkCreate(itemlist); // fails because of duplicates
// this works, and handles the duplicates correctly :
await fortnite_items.bulkCreate(itemlist, {updateOnDuplicate: ['name', 'description']}); 
```

### What do you expect to happen?

I expect the function to default to updating everything on conflict, as the documentation says.

### What is actually happening?

The code fails:
`UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error`

### Environment

- Sequelize version: 5.21.1  
- Node.js version: v10.15.0 
- Operating System: Mac OS 10.15.1
- If TypeScript related: TypeScript version: 3.6.4 

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using postgres, with connector library version 7.12.1 (if "pg" is meant) and database version 11.5

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hmm... I admit I am confused here. Hi @thaddeusmt, can you help me? Is `updateOnDuplicate` really supposed to be on by default on all fields? Or is this a big documentation mistake? Thanks

**Comment by papb** [comment]
Hmm actually I figured it out, it is indeed a documentation mistake, I will close this in favor of #11090, and hopefully take care of it in the close future. For now please continue passing the attributes explicitly , or use [the workaround mentioned in the other issue](https://github.com/sequelize/sequelize/issues/11090#issuecomment-515669559).
