### ISSUE TITLE
Unexpected fieldname convertion when including an entity

### ISSUE THREAD

**Issue by leysys** [sequelize/sequelize#11669]
### What are you doing?

```js
Sequelize.define('unit', {
  // ...
  complex_id: {
    field: 'building_id', // 'building_id' is the pysical field for 'complex_id'
    reference: {
      model: 'complex',
      key: 'id'
    },
  },
  building_id: {
    field: 'immeuble_id', // 'immeuble_id' is the pysical field for 'building_id'
    reference: {
      model: 'building',
      key: 'id',
    },
  },
})

// query A
unit.findAndCount({
  where: { complex_id: 123 }
})

// query B
another_entity.findAndCount({
  where: {  },
  include: [{
    model:unit,
    where: { complex_id: 123 },
  }],
})

```

### What do you expect to happen?

_both finds unit where building_id_

```
// query A
// SELECT * FROM unit WHERE building_id = 123
// query B
// SELECT * FROM onother_entity INNER JOIN unit ON .... AND building_id = 123
```
### What is actually happening?

_when using include, fieldname of where statement has unexpected result_

```
// query A
// SELECT * FROM unit WHERE building_id = 123 // correct
// query B
// SELECT * FROM onother_entity INNER JOIN unit ON .... AND immeble_id = 123 // wrong!
```

### Additional context

Sequelize converts logical fieldname to pysical fieldname in both case.
When I directly select the entity, it just use converted fieldname and send: works fine.
However, when I select the entity with 'include', it tries to convert the fieldname again until it cannot find the same name regardless whether it's already physical fieldname or not

### Environment

- Sequelize version: 5.21.2 
- Node.js version: 10.15.3 
- Operating System: windows 10

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Oh, nice catch, this is an ugly bug...

**Comment by Zapotoczny-Rafal** [comment]
Hello @papb, I know that this problem is almost 2 years old, so I would like to make sure that it has not been solved because I would like to contribute.

**Comment by Bhuvnesh875** [comment]
i would like to work on this issue, but a little guidance of how to start would be appreciable. :)

**Comment by GAURAV1-ui** [comment]
I would like to work on this issue.

**Comment by WikiRik** [comment]
Feel free to work on this! I would recommend starting with writing some tests so you can see if this is still present in the main branch.

**Comment by shubham-sharmas** [comment]
@WikiRik I attempted to reproduce the issue using the Sequelize main branch, but based on the results, I don't believe it's present in the main branch, as we are getting the expected outcome. Please check the [Gist](https://gist.github.com/shubham-sharmas/24644934133c10eee3a185f1ed9f9430) for reference.

**Comment by ephys** [comment]
Thanks for checking!
