### ISSUE TITLE
Sequelize where condition for nested include going into inner join

### ISSUE THREAD

**Issue by techuila** [sequelize/sequelize#11664]
I'm having trouble customizing the where condition on the nested includes, it keeps on adding it on the JOIN rather than the WHERE. Is there a solution to this?

"sequelize": "^5.18.4",

**Comment by illud** [comment]
How can i do this query in sequelize
SELECT rol FROM roles INNER JOIN user_roles ON roles.id = user_roles.roleId

**Comment by techuila** [comment]
```
models.rol.findAll({ 
   include:[{
      association: __association__
   }]
})
```

**Comment by papb** [comment]
There is a [new guide focused on eager loading](https://sequelize.org/master/manual/eager-loading.html), please take a look if it helps, perhaps the part about *top-level wheres*.

If you still have trouble let me know and I will reopen this.
