### ISSUE TITLE
Typings for QueryInterface do not match actual code.

### ISSUE THREAD

**Issue by Vilsol** [sequelize/sequelize#11673]
### What was unclear/insufficient/not covered in the documentation

The typings for QueryInterface upsert function is wrong. The library function has a `where` parameter, whereas the typings don't have it.

### If possible: Provide some suggestion on how we can enhance the docs

Please update the typings to match actual code.

### Additional context

Typings: https://github.com/sequelize/sequelize/blob/master/types/lib/query-interface.d.ts#L444
Actual Function: https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L891

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thanks for taking the time to post a great issue. The additional context you posted was very helpful.
