### ISSUE TITLE
Perform db password change on production

### ISSUE THREAD

**Issue by HunterJS-bit** [sequelize/sequelize#11679]
## Issue Description

Hi guys, I'm having a problem with sequelize, well not exactly a problem but an issue.

I would like to change my DB password in production.
While my app is running, are there any options or would I need to make bash script that updated in the database and changes in migration.config.json or is there some other solution??
Also how would I prevent it from being overridden next time I deploy new version of app

### Additional context
Add any other context or screenshots about the issue here.

## Issue Template Checklist
Here is my sample migration.config
```
{
  "development": {
    "username": "postgres",
    "password": "postgres",
    "database": "db",
    "host": "localhost",
    "dialect": "postgres",
    "logging": false,
    "seederStorage": "sequelize",
    "operatorsAliases": false
  },
  "test": {
    "username": "test",
    "password": "stest",
    "database": "test_db",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "logging": false,
    "seederStorage": "sequelize",
    "operatorsAliases": false
  },
  "production": {
    "username": "prod",
    "password": "prod",
    "database": "db_prod",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "seederStorage": "sequelize",
    "operatorsAliases": false
  }
}
```

### Is this issue dialect-specific?
4.42.0

**Comment by papb** [comment]
You shouldn't have the database connection password in plaintext in your config file, you should actually read the password from an environment variable for example `process.env.DB_PASSWORD`

**Comment by HunterJS-bit** [comment]
@papb Ok I will move it to env variables, so you suggest I should just alter password with psql and then change env variable that would be enough ?

**Comment by HunterJS-bit** [comment]
anyway managed to solve the problem, switched variables from migarations.config to env variables, and will just change env variable and restart server
