### ISSUE TITLE
Encryption Functions

### ISSUE THREAD

**Issue by hegdeashwin** [sequelize/sequelize#1167]
Hi,

For some reason currently i am using raw SQL queries instead of using ORM functions and i am using MYSQL Enterprise.

Is there any way to use mysql encryption/decryption functions like AES, DES, SHA, SHA1 or SHA2.

I want to a way or example to use one of these functions in my password field to inserting/updating/selecting.

Thanks.

**Comment by ht10vn** [comment]
Hi,
I want to ask, how to use encryption(AES, DES) with the ORM ?
Thanks,

**Comment by janmeier** [comment]
@ht10vn what do you mean? Do you want to encrypt the data before inserting or using sql?

**Comment by jpodwys** [comment]
I was also hoping for some clarification on using mysql's built-in AES functions from within sequelize. If possible, I'm looking for the "sequelize way" rather than writing my own queries. I've written my own queries and I'm interested if it's simpler with sequelize. Thanks!

**Comment by mickhansen** [comment]
@jpodwys We don't have any native support for it at the moment. What does your query look like atm? Maybe i can help you make it a little bit more sequelizey

**Comment by jpodwys** [comment]
Here's what my queries looked like while working in PHP with PHP's native PDO:

`INSERT`

```mysql
INSERT INTO entries (OwnerId, IsPublic, Body, HistoricalDate, CreationDate)
VALUES (:ownerId, :isPublic, AES_ENCRYPT(:body, :key), :historicalDate, NOW())
```

`LIKE` plain text search

```mysql
SELECT EntryId, IsPublic, HistoricalDate, AES_DECRYPT(Body, :key) AS Body
FROM entries
WHERE OwnerId = :ownerId AND LOWER(CAST(AES_DECRYPT(Body, :key) AS CHAR)) LIKE CONCAT('%' , :query, '%')
ORDER BY HistoricalDate desc
LIMIT :index, :offset
```

Basically, I want `body` to be encrypted in the table, so all reads and writes need to handle that.

I also need a count of all the matching records. Would I be better of just doing `sequelize.query` and writing it myself?

**Comment by mickhansen** [comment]
@jpodwys I'm biased so i think you shoudl give db.fn() a go, it lets you keep the rest declarative.

**Comment by mickhansen** [comment]
You could add beforeCreate, beforeUpdate & beforeFind hooks to easen your load :)
