### ISSUE TITLE
How to use the calculation(+, -,*,/) in the function(Sequelize.fn)?

### ISSUE THREAD

**Issue by oneWalker** [sequelize/sequelize#11678]
## Issue Description

- Now, I am failed to try the Sequelize as Orm to calculate the number in my database such as counting the sum, avg, max. However, the time stored in my database is unixtime in milliseconds, the origin function, `FROM_UNIXTIME('TIME',"%y%m%d")`, transferring the unixtime to formatted time in MySQL dialect needs time in seconds. 

### Attempt

- For example,  I want to get the executing SQL is

-  `SELECT FROM_UNIXTIME(`created_at`/1000,"%y%m%d") AS `days`, COUNT(`username`) AS `count1`, AVG(`created_at`) AS `average` FROM `users` AS `user`;` 

or

- SELECT FROM_UNIXTIME(`created_at` MOD 1000,"%y%m%d") AS `days`, COUNT(`username`) AS `count1`, AVG(`created_at`) AS `average` FROM `users` AS `user`;`

- But, when I want to use the Sequelize to solve the problem, I have tried some ways in the next context and all things are failed. The framework will transfer the COLUMN as adding string.

- ` let query1=await ctx.model.User.findAll(

    {
      attributes:[
        [fn('FROM_UNIXTIME',col('created_at/1000',"%y%m%d")),'days'],
        [fn('COUNT',col('name')),'counts'],
        [fn('COUNT',col('username')),'count1'],
        [fn('AVG',col('created_at')),'average'],
      ],
    }
  );`

- ` let query1=await ctx.model.User.findAll(

    {
      attributes:[
        [fn('FROM_UNIXTIME',col('created_at mod 1000',"%Y%m%d")),'days'],
        [fn('COUNT',col('name')),'counts'],
        [fn('COUNT',col('username')),'count1'],
        [fn('AVG',col('created_at')),'average'],
      ],
    }
  );`

- So, Which ways or something else can help you to solve the problem. Now, I am used the origin SQL dialect to succeed in it.

**Comment by 1valdis** [comment]
The only way I found to be readable and still using all ORM goodies is to use sequelize.literal in attributes. Such as: `attributes: ['id', [sequelize.literal('"col1"+"col2"'), 'sumofcol1andcol2']],`

**Comment by oneWalker** [comment]
> The only way I found to be readable and still using all ORM goodies is to use sequelize.literal in attributes. Such as: `attributes: ['id', [sequelize.literal('"col1"+"col2"'), 'sumofcol1andcol2']],`

Yeah， I found the way is available and Thanks for your answering.
Sequelize.literal can transfer the words to original SQL  dialect without formatting it.

Now, I found a new problem that it cannot connect two tables with `include` when we user `Sequelize.literal` and other functions when using the Orm of Sequelize.
Could you tell me about the way to solve it?

**Comment by papb** [comment]
> Now, I found a new problem that it cannot connect two tables with `include` when we user `Sequelize.literal` and other functions when using the Orm of Sequelize.
> Could you tell me about the way to solve it?

@oneWalker Have you figured out how to do this? Can you please explain better what you are trying to accomplish?

**Comment by oneWalker** [comment]
> > Now, I found a new problem that it cannot connect two tables with `include` when we user `Sequelize.literal` and other functions when using the Orm of Sequelize.
> > Could you tell me about the way to solve it?
> 
> @oneWalker Have you figured out how to do this? Can you please explain better what you are trying to accomplish?

No, I use another logical way to finish my task without using the syntax in the same one. Sorry for replying to you so late.
