### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by jy95** [sequelize/sequelize#11687]
## Issue Description

When reading the docs on this [page](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-define) , I saw a dead link :

![image](https://user-images.githubusercontent.com/9306961/69007943-e4d7de80-0944-11ea-88bc-af00bf839206.png)

[Model definition](https://sequelize.org/manual/tutorial/models-definition.html) Manual related to model definition

When I clicked on this, I got this 404 page : 

![image](https://user-images.githubusercontent.com/9306961/69007951-0afd7e80-0945-11ea-87db-07fda7cf649a.png)

### If possible: Provide some suggestion on how we can enhance the docs

Remove it ( or change it )

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Oops, thanks for the report, this is my fault, will fix it soon :)

**Comment by jy95** [comment]
There is also this dead link in this findAll option : [transaction#lock](https://sequelize.org/master/transaction#lock)
![image](https://user-images.githubusercontent.com/9306961/71251289-35ff3780-2322-11ea-83d6-13dddc0ba985.png)
