### ISSUE TITLE
MySQL: Loss of precision in JSON columns

### ISSUE THREAD

**Issue by HayDegha0917** [sequelize/sequelize#11689]
### What are you doing?

Insert the following into a MySQL table where `content` is defined as JSON.

```JSON
{
     "$": {
         "Id": "",
         "Name": "WebTarget_3-ARAK8",
         "Owner": "Not Specified",
         "Version": 0,
         "WriteProtected": false
     },
     "Properties": {
         "Property": [{
             "$": {
                 "Name": "Name"
             },
             "String": "Web OnSight"
         }]
     },
     "Point": {
         "XYZUVW": {
             "$": {
                 "U": -90071992547409913,
                 "V": -90071992547409912,
                 "W": -90071992547409911,
                 "X": 2.629361152648926,
                 "Y": 0.6798138618469238,
                 "Z": 5.4606475830078125,
                 "RMC": "31, 1330",
                 "Frame": "LOCAL_LEVEL",
                 "NormalEstimated": false,
                 "LocationEstimated": false
             }
         },
         "ImageIJ": {
             "$": {
                 "I": -9007199254740991,
                 "J": -9007199254740991,
                 "ImageId": ""
             }
         }
     }
 }
```
Noe the precision of the `U`, `V`, and `W` properties.

### What do you expect to happen?

I would expect the values to be inserted exactly as specified, since MySQL JSON supports double-precision properties.

### What is actually happening?

Sequelize is converting the JSON object to a string, then inserting it into MySQL as a string. The generated INSERT statement is:

```SQL
INSERT INTO `planning_tgt` 
(`uuid`,`name`,`sol`,`rmc`,`site`,`drive`,`location`,`version`,`status`,`owner`,`write_protected`,`creator`,`creation_date`,`updated_by`,`update_date`,`content`) 
VALUES 
('aa4287a5-90a3-4f0c-966b-9c2a4783fc02','WebTarget_3-ARAK8',0,'31, 1330','31','1330',GeomFromText('POINT (2.629361152648926 0.6798138618469238)'),0,'UNASSOCIATED','Not Specified',false,'local-akassabi2',CURRENT_TIMESTAMP,'local-akassabi2',CURRENT_TIMESTAMP,'{\"$\":{\"Id\":\"aa4287a5-90a3-4f0c-966b-9c2a4783fc02\",\"Name\":\"WebTarget_3-ARAK8\",\"Owner\":\"Not Specified\",\"Version\":0,\"WriteProtected\":false},\"Properties\":{\"Property\":[{\"$\":{\"Name\":\"Name\"},\"String\":\"Web OnSight\"}]},\"Point\":{\"XYZUVW\":{\"$\":{\"U\":-90071992547409920,\"V\":-90071992547409920,\"W\":-90071992547409900,\"X\":2.629361152648926,\"Y\":0.6798138618469238,\"Z\":5.4606475830078125,\"RMC\":\"31, 1330\",\"Frame\":\"LOCAL_LEVEL\",\"NormalEstimated\":false,\"LocationEstimated\":false}},\"ImageIJ\":{\"$\":{\"I\":-9007199254740991,\"J\":-9007199254740991,\"ImageId\":\"\"}}}}');
```

Note the loss of precision on the attributes due to rounding by `JSON.stringify()`.

There is further loss of precision when the record is inserted into MySQL because MySQL then converts the string into its internal JSON representation. The final value inserted into MySQL is:

```
{"$": {"Id": "aa4287a5-90a3-4f0c-966b-9c2a4783fc02", "Name": "WebTarget_3-ARAK8", "Owner": "Not Specified", "Version": 0, "WriteProtected": false}, "Point": {"XYZUVW": {"$": {"U": -90071992547409920, "V": -90071992547409920, "W": -90071992547409900, "X": 2.629361152648926, "Y": 0.6798138618469238, "Z": 5.4606475830078125, "RMC": "31, 1330", "Frame": "LOCAL_LEVEL", "NormalEstimated": false, "LocationEstimated": false}}, "ImageIJ": {"$": {"I": -9007199254740991, "J": -9007199254740991, "ImageId": ""}}}, "Properties": {"Property": [{"$": {"Name": "Name"}, "String": "Web OnSight"}]}}
```

### Additional context

n/a

### Environment

- Sequelize version: 4.44.3 
- Node.js version: v10.16.3 
- Operating System: Windows
- If TypeScript related: TypeScript version: n/a

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MySQL 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by HayDegha0917** [comment]
I have roughly found the area of code where the transformations happen but need to pinpoint it. Essentially, the JSON object needs to be transformed into an expression using the MySQL `JSON_OBJECT()` function.

**Comment by papb** [comment]
Hello, can you please create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) showing this?
