### ISSUE TITLE
Using string as a primary key with dialect Postgres produces SequelizeDatabaseError: syntax error at or near "ON" in Typescript (not with SQLite)

### ISSUE THREAD

**Issue by tmscer** [sequelize/sequelize#11681]
### What are you doing?

I am creating 3 models while using Postgres dialect. One model uses a string as its primary key (Permission).

The 3 models are (purposefully omitting imports):

```ts
@Table
export default class User extends Model<User> {
  @Column
  name!: string;

  @Column
  email!: string;

  @BelongsToMany(() => Permission, () => UserPermission)
  permissions?: Permission[];
}
```

```ts
export enum PermissionEnum {
  ROOT = "ROOT"
}

@Scopes(() => ({
  users: {
    include: [
      {
        model: User,
        through: { attributes: [] }
      }
    ]
  }
}))
@Table
export default class Permission extends Model<Permission> {
  @PrimaryKey
  @Column({
    type: DataType.ENUM(PermissionEnum.ROOT)
  })
  name: PermissionEnum;

  @BelongsToMany(() => User, () => UserPermission)
  users?: User[];
}
```

```ts
@Table
export default class UserPermission extends Model<UserPermission> {
  @ForeignKey(() => User)
  @Column
  userId!: number;

  @ForeignKey(() => Permission)
  @Column
  permissionName!: string;
}
```

### What do you expect to happen?

I expect sequelize to create tables.

### What is actually happening?

An error is outputed when using Postgres dialect but not when using SQLite. I have not tested any other dialects. I have found out that removing `@PrimaryKey` from Permission's name field (and modifying fields in UserPermission) resolves this issue.

Posting the last SQL statement and the error it is producing.

```
...
Executing (default): CREATE TABLE IF NOT EXISTS "UserPermissions" ("userId" INTEGER  REFERENCES "Users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "permissionName" "public"."enum_UserPermissions_permissionName" ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("userId", "permissionName"), PRIMARY KEY ("userId","permissionName"));
Unhandled rejection SequelizeDatabaseError: syntax error at or near "ON"        
    at Query.formatError (/code/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at /code/node_modules/sequelize/lib/dialects/postgres/query.js:72:18        
    at tryCatcher (/code/node_modules/bluebird/js/release/util.js:16:23)        
    at Promise._settlePromiseFromHandler (/code/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/code/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/code/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/code/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/code/node_modules/bluebird/js/release/async.js:93:12)  
    at _drainQueue (/code/node_modules/bluebird/js/release/async.js:86:9)       
    at Async._drainQueues (/code/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/code/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

### Environment

- Sequelize version: 5.19.6
- Node.js version: v12.13.0
- Operating System: Linux 5.3.8-3-MANJARO
- If TypeScript related: TypeScript version: 3.6.3
- Postgres Version: 12.0 (via docker)
- pg package version: 7.12.1
- pg-hstore package version: 2.3.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, from your code, since you're using typescript with decorators, I would guess you are using [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript), right?

Can you reproduce the issue without it? If not, please open an issue on their repository, thanks

**Comment by soryy708** [comment]
I think that the problem is not with using a string as a primary key, rather using a primary key that is a foreign key.

**Comment by tmscer** [comment]
Decided to use Mongo a few months ago and lost context surrounding the issue.
