### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by epifanovmd** [sequelize/sequelize#11690]
rewrite the types so that you can transfer the model interface to the Model `<IModel>` class instead of `Model <T = any, T2 = any>`, and this model will also be thrown in the export type 

```ts
FindAttributeOptions <T> = top
   | (keyof T) []
   | {
   exclude: (keyof T) [];
   include ?: (keyof T) [];
}
   | {
   exclude ?: (keyof T) [];
   include: (keyof T) [];
};
```

and in other places.

**Comment by epifanovmd** [comment]
export interface ModelAttributes {
  /**
   * The description of a database column
   */
  [name: string]: DataType | ModelAttributeColumnOptions;
}

export interface ModelAttributes<T> {
  [name: keyof T]: DataType | ModelAttributeColumnOptions;
}

**Comment by epifanovmd** [comment]
public static findAll<M extends T>(this: { new (): M } & typeof Model, options?: FindOptions): Promise<Pick<T,...options.attributes>[]>;

**Comment by ThomasEg** [comment]
Isn't this related to https://github.com/sequelize/sequelize/issues/11250 aswell?

**Comment by papb** [comment]
I didn't understand this issue to be honest, title is not helpful and description is lacking, can anyone clarify? Once it's done I will reopen
