### ISSUE TITLE
Unicode characters showing as "??????" (question mark)

### ISSUE THREAD

**Issue by ameetdhage** [sequelize/sequelize#11696]
## Issue Description
Sequelize query result showing unicode characters as  question marks (e.g "???????")

### What are you doing?
I am using sequelize with mysql. 
mysql database has _posts_ table in which some column may contain unicode characters. When I query database via sequelize then the query result showing unicode characters as question marks (e.g "???????")
Below is the minimal code sample to reproduce the issue
 
```js
// sequelize.js
let sequelize = new Sequelize('database', {
    host: 'localhost',
    dialect: 'mysql',
    query: { raw: true }
});

// model
module.exports = (sequelize, DataTypes) => {
  let posts = sequelize.define('posts', {
            ID: { type: DataTypes.BIGINT, primaryKey: true },
            post_author: { type: DataTypes.BIGINT },
            post_title: { type: DataTypes.STRING },
            post_content: { type: DataTypes.STRING },
            post_status: { type: DataTypes.STRING },
            post_type: { type: DataTypes.STRING },
            post_date: { type: DataTypes.DATE },
        }, {
            freezeTableName: true,
            timestamps: false,
            charset: 'utf8mb4',
            collate: 'utf8mb4_unicode_520_ci'
  });

  return posts;
};
```

### What do you expect to happen?
_I want to see unicode characters in the query result._

### What is actually happening?
In query result I am getting data as
```
{
	post_id: 134385,
	post_author: 12,
	post_title: '??????? ???? ?? ???? ?????? ?? ?????? ?? ??? ?? ???? ?? ???? ?? ?? ??-??????? ??',
	post_date: 2018-07-01T18:45:40.000Z,
}
```

### Additional context
Here is the screenshot of the db table for your reference

![mysql posts table](https://user-images.githubusercontent.com/27812434/69245912-c1739480-0bcd-11ea-9171-477b58b5b7a8.PNG)

Data is getting set from CMS tool. 
I also tried setting charset and collate at db level. This didn't work.

### Environment
- Dialect: mysql
- Sequelize version: 5.18.1 
- Node.js version: 10.16.3 
- Operating System: Windows 8.1
- TypeScript version: 3.6.2
- mysql2 version: 1.7.0
- mysql version: 2.17.1

**Comment by MarquesDev** [comment]
Hello :) Did you have found a fix ?

If yes, what was the problem ?

**Comment by papb** [comment]
Can someone please construct a complete [sequelize-sscce](https://github.com/papb/sequelize-sscce) from this?

**Comment by soryy708** [comment]
Are the "question marks" persisted as question marks in the database? or only printed to the console that way?
