### ISSUE TITLE
Dialect and schema formatting

### ISSUE THREAD

**Issue by jacobtuma** [sequelize/sequelize#11693]
Issue Description
Need for breaking out the schema and table name
### What was unclear/insufficient/not covered in the documentation
Documentation for defining schema is listed below:
Apply a schema to this model. For postgres, this will actually place the schema in front of the table name - "schema"."tableName", while the schema will be prepended to the table name for mysql and sqlite - 'schema.tablename'.

I have mysql, not postgres, and I need the option to, if possible, write my schema in the postgres syntax

### If possible: Provide some suggestion on how we can enhance the docs
Maybe list the boolean we can switch on to force this syntax

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): mysql, sqllite
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Do you know a way to do this? I am asking to understand if this is really a docs issue or a feature request.

Have you managed to work around it by using `sequelize.literal` for example, to force a unescaped content with whatever you want?
