### ISSUE TITLE
How to do alias when i build nested relationship tables .

### ISSUE THREAD

**Issue by MoonSupport** [sequelize/sequelize#11709]
## Issue Description

I was building nested relationship tables through include

```ts
      const A = await A.findAll({
      include: [
          {
            attributes: [],
            association: A.B,
            required: true,
            include: [
              {
                attributes: [],
                association: B.C,
                required: true,
              },
            ],
          },
        ],
```

i have result like this.
```
INNER JOIN "C" AS "B->C" 
ON "B"."C_id" = "B->C"."id"
```

but i want to get like this ( i don't want that arrow alias )

```
INNER JOIN "C" AS "C" 
ON  "B"."C_id" = "B->C"."id"
```

where can i do Alias ?

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

**Comment by papb** [comment]
Can you post the complete SQL you wanted to have? You posted only a part of it

```sql
INNER JOIN "C" AS "C" 
ON  "B"."C_id" = "B->C"."id"
```

From this part only it looks to me that the query you wan't wouldn't work, since `"B->C"` would have no meaning

**Comment by mauriziocarella** [comment]
Hi, sorry for digging this out but I think I have the same problem and maybe I can contribute with more use-cases.

I tryed this on a new example project where I have three models: Poll, PollOption and PollVote.

**Relationships**
```
Poll.Options = Poll.hasMany(models.PollOption, {
  as: 'options',
});
...
PollOption.Votes = PollOption.hasMany(models.PollVote, {
  as: 'options_votes',
});
```

**Query**
```
Poll.findOne({
  where: {
    id: pollId,
  },
  include: [
    {
      association: Poll.Options,
      attributes: {
        include: [
          [Sequelize.fn('COUNT', Sequelize.col('options_votes.id')), 'votes'],
        ]
      },
      include: [
        {
          attributes: [],
          association: PollOption.Votes,
        }
      ],
    },
  ],
});
```

**Generated SQL**
```
SELECT
    `Poll`.`id`,
    `Poll`.`name`,
    `options`.`id` AS `options.id`,
    `options`.`label` AS `options.label`,
    `options`.`pollId` AS `options.pollId`,
    COUNT(`options_votes`.`id`) AS `options.votes`
FROM
    `Polls` AS `Poll`
LEFT OUTER JOIN `polls_options` AS `options`
ON
    `Poll`.`id` = `options`.`PollId`
LEFT OUTER JOIN `polls_votes` AS `options->options_votes`
ON
    `options`.`id` = `options->options_votes`.`optionId`
WHERE
    (`Poll`.`id` = '1');
```

Query result is the error:  **_SequelizeDatabaseError: Unknown column 'options_votes.id' in 'field list'_** 

Shouln't nested includes take table alias from relationship '_as_' attribute?

Thank you.

Sequelize and mysql2 versions:

```
"mysql2": "^2.2.5",
"sequelize": "^6.5.0",
```

**Comment by anuccio1** [comment]
Is there a workaround for this?

**Comment by anuccio1** [comment]
> Is there a workaround for this? Either a way to dynamically generate the alias name or a way to stop sequelize from adding `->` to alias names?

I believe [this line](https://github.com/sequelize/sequelize/blob/cb8ea88c9aa37b14c908fd34dff1afc603de2ea7/src/dialects/abstract/query-generator.js#L1836) is where I want to be able to intercept
