### ISSUE TITLE
1:n relationship - select only last row from second table (join with subselect)

### ISSUE THREAD

**Issue by sneznaovca** [sequelize/sequelize#11715]
## Issue Description
I have two table with 1:N relationship. User and payments I need select all data from first table and only last row from second table (all user with last payment).
 
In sql something like
```
SELECT  u.*, p.*
FROM users u 
    LEFT JOIN payments p
        ON u.id = p.user_ID
    INNER JOIN
    (
        SELECT payment_ID, MAX(date) maxDate
        FROM payments
        GROUP BY user_ID
    ) b ON p.payment_ID = b.payment_ID
WHERE u.package = 1
```
I don't know how write this query in sequelize

My last try:
```
Users.findAll({
  where: {package: 1},
  include: [{
    model: Payments,
    where: {
    	"payment_ID": sequelize.literal('MAX(date)')
    }}
   }]
});
```
### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Take a look at the [new guide on sub queries](https://sequelize.org/master/manual/sub-queries.html). If you still have trouble let me know.

**Comment by sdpanteon** [comment]
Has anyone got an answer?

I want to use sequelize model syntex only not the raw query. 
I am facing the same problem and do not understand what to do.

**Comment by WikiRik** [comment]
> Has anyone got an answer?
> 
> I want to use sequelize model syntex only not the raw query. I am facing the same problem and do not understand what to do.

Did the [guide on subqueries](https://sequelize.org/master/manual/sub-queries.html) not give you sufficient help?

**Comment by sdpanteon** [comment]
> > Has anyone got an answer?
> > I want to use sequelize model syntex only not the raw query. I am facing the same problem and do not understand what to do.
> 
> Did the [guide on subqueries](https://sequelize.org/master/manual/sub-queries.html) not give you sufficient help?

@WikiRik 

Absolutely, I have been checking that documentation for two days now still it does not solve my problem.
I need to create a subquey at join table, just like above mentioned example not into selection attribute or at where filter.

And, Sequelize does not support sequelize.literal syntex with eager load (join) syntax.

Expected query result:
```
SELECT *
FROM `category` AS `category`
         LEFT JOIN (SELECT *
                    FROM settlement
                    order by created_at DESC
                    LIMIT 0, 10) AS `settlement` ON `category`.`settlement_id` = `settlement`.`settlement_id` 
ORDER BY `categoryTurnover`.`cash_settlement_id` ASC;
```

The sequelize I have prepared so far:
```
CategoryModel.findAndCountAll({
                attributes: [],
                include: {
                    model: SettlementModel, <---- Here It does not support literal syntax
                    attributes: [],
                    required: false,
                    where: {},
                },
                where: {},
                limit: 10,
                raw: false
            })
```

**Comment by ephys** [comment]
Related issue: https://github.com/sequelize/sequelize/issues/11788
