### ISSUE TITLE
Virtual dependency fields are being ignored if virtual field is set as attribute

### ISSUE THREAD

**Issue by zcuric** [sequelize/sequelize#11710]
## Issue Description

Virtual dependency fields are being ignore if virtual field is set as attribute in included association, 

### What are you doing?

```js
// Pseudo representation of the issue
const pick = require('lodash/pick');

class User extends Model {
  static fields(DataTypes) {
    return {
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: { isEmail: true, notEmpty: true },
        unique: { msg: 'This email address is already in use.' }
      },
      firstName: {
        type: DataTypes.STRING,
        field: 'first_name'
      },
      lastName: {
        type: DataTypes.STRING,
        field: 'last_name'
      },
      createdAt: {
        type: DataTypes.DATE,
        field: 'created_at'
      },
      updatedAt: {
        type: DataTypes.DATE,
        field: 'updated_at'
      },
      deletedAt: {
        type: DataTypes.DATE,
        field: 'deleted_at'
      },
      profile: {
        type: new DataTypes.VIRTUAL(DataTypes.ABSTRACT, ['id', 'firstName', 'lastName', 'email']),
        get() {
          return pick(this,
            ['id', 'firstName', 'lastName', 'email']);
        }
      }
    };
  }
// ... Somehere in controller

const getPost = (req, params, next) => {
  const include = {
    model: User,
    as: 'author',
    attributes: ['profile']
  };
  return Post.findByPk(req.params.id, { include })
    .then(post => res.json({ post }));
};
```

### What do you expect to happen?

Post output should be:
```js
{
	id: 5, 
	title: "Foo",
	body: "Bar",
	author: { profile: { 
		id: 1,
		firstName: "John",
		lastName: "Doe",
		email: "john.doe@sequelize.com"
	} }
}
```
### What is actually happening?

Post output was:
```js
{
	id: 5, 
	title: "Foo",
	body: "Bar",
	author: { profile: {} }
}
```

If I explicitly set wanted attributes and virtual one, for example:
```
...
attributes: ['id', 'firstName', 'lastName', 'email', 'profile']
...
```

Output will be
```js
{
	id: 5, 
	title: "Foo",
	body: "Bar",
	author: { 
		id: 1,
		firstName: "John",
		lastName: "Doe",
		email: "john.doe@sequelize.com", 
		profile:  { 
		id: 1,
		firstName: "John",
		lastName: "Doe",
		email: "john.doe@sequelize.com"
	} }
}
```

### Additional context

It looks like virtual field dependencies are being ignored here: 
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3799

### Environment

- Sequelize version: latest 
- Node.js version: 10 
- Operating System: MacOS Catalina
- If TypeScript related: TypeScript version: false

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by mhaamann** [comment]
I can reproduce same issue for me in Sequelize 5.21.3.
This is halting our migration from 4 to 5

**Comment by mhaamann** [comment]
I believe that I solved my case. 

Have you tried including all attributes @zcuric? That seemed todo the trick for me.

Example:
```
const getPost = (req, params, next) => {
  const include = {
    model: User,
    as: 'author',
    attributes: ['profile', 'id', 'firstName', 'lastName', 'email']       <------
  };
  return Post.findByPk(req.params.id, { include })
    .then(post => res.json({ post }));
```

**Comment by zcuric** [comment]
@mhaamann Yes. But bug is still present.

**Comment by amoqaddam** [comment]
this issue still exists in versions 6 and 7
