### ISSUE TITLE
Primary Key not respected, Sequelize tries to insert into id field

### ISSUE THREAD

**Issue by gamburgm** [sequelize/sequelize#11714]
## Issue Description
I am trying to use a string as the primary key for one of my tables instead of `id`, but on `create` Sequelize always tries to insert a default `id`, which crashes.
### What are you doing?

The relevant piece of my `config.json`:
```json
{
    "development": {
        "username": null,
        "password": null,
        "database": "experiment",
        "host": "127.0.0.1",
        "dialect": "postgres"
    }
}
```

After initializing the project, I ran `npx sequelize-cli models:generate --name Foo --attributes foo:string,bar:string,quux:integer` and edited the `migrations/...-create-foo.js` file as such:

```js
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Foos', {
      foo: {
        allowNull: false,
        autoIncrement: false,
        primaryKey: true,
        type: Sequelize.STRING
      },
      bar: {
        type: Sequelize.STRING
      },
      quux: {
        type: Sequelize.INTEGER
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Foos');
  }
};
```

Small test script:
```js
const db = require('./models/index.js');

const Foo = db.Foo;

Foo.create({ foo: "Foo", bar: "Bar", quux: 42 }).then(() => console.log("It worked!"));
```

### What do you expect to happen?

I expect the record to get created and log `It worked!`.

### What is actually happening?
Sequelize tries to insert a default `id`, which isn't present in the table.

```
Executing (default): INSERT INTO "Foos" ("id","foo","bar","quux","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5) RETURNING *;
Unhandled rejection SequelizeDatabaseError: column "id" of relation "Foos" does not exist
    at Query.formatError (/Users/Mitch/sequelize/sequelize-bug/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at query.catch.err (/Users/Mitch/sequelize/sequelize-bug/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)
    at tryCatcher (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

### Additional context
The table looks like I would expect it to, without an `id` field and with a primary key on `foo`.

![Screen Shot 2019-11-27 at 10 31 31 PM](https://user-images.githubusercontent.com/33709622/69775093-b1c3f500-1165-11ea-93a8-c89124bd276f.png)

Additional note: if I rename `foo` to `id`, it works. I don't think, however, that the user should be restricted to naming the primary key `id`, especially since that's not a restriction that `psql` enforces (or any other dialect, as far as I know . . . ?).

### Environment

- Sequelize version: 5.21.2
- Node.js version: 10.16.3
- Operating System: macOS Mojave 10.14.5

### How does this problem relate to dialects?

- [x] I don't know, I was using Postgres, with connector library version pg@7.21.1 and database version PostgreSQL 11.3

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need (a very small amount of) guidance. --> a good starting point would help

**Comment by pawel2105** [comment]
Can confirm this is happening for me as well. Using:

```
"sequelize": "^5.16.0"
"pg": "^7.6.1"
```

**Comment by ryan-sandy** [comment]
I am having this same issue using mysql dialect.

**Comment by GinaMaronov** [comment]
Any update on this? Much of my postgres database is bigserial and would appreciate a fix or work around.

    "pg": "7.14.0",
    "pg-hstore": "2.3.3",
    "sequelize": "5.21.2",
    "sequelize-typescript": "1.1.0",

**Comment by promgamer** [comment]
is this solved?

**Comment by rapelt** [comment]
I'm having this issue with     "sequelize": "^6.3.5",

**Comment by Anonyma** [comment]
Still having this issue on "sequelize": "^6.5.0"

**Comment by peronvidal** [comment]
Maybe this can help (extracted from the docs)

Primary keys
Sequelize will assume your table has a id primary key property by default.

To define your own primary key:

class Collection extends Model {}
Collection.init({
  uid: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true // Automatically gets converted to SERIAL for postgres
  }
}, { sequelize });

class Collection extends Model {}
Collection.init({
  uuid: {
    type: DataTypes.UUID,
    primaryKey: true
  }
}, { sequelize });
And if your model has no primary key at all you can use Model.removeAttribute('id');

**Comment by odedbendov** [comment]
Still seeing this on 6.6.5

Is it because the field is a string and not an integer? Is something broken? Is anyone reading this? :)

**Comment by mareebsiddiqui** [comment]
Facing the same issue.

**Comment by AleOjeda** [comment]
same issue

**Comment by supercrafter100** [comment]
Issue still exists.

**Comment by AaronR2021** [comment]
same issue. I set email as primary key. when the table was created it created its own column called id, which acts as a primary key.

**Comment by imadueno** [comment]
I have the same issue. Not sure if I need to create a new one, but I'll post here my case:

### Model

```
class Productos extends Model {}
Products.init({
    ProductoId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    // rest of fields
  },
  {
    sequelize,
    tableName: "STORE_Producto",
    timestamps: false
  }
);
```
### Controller ( create )

Note: the body contains all the fields of the table excep the primary key
```
const create  = async (req, res) => {
  try{
    const { body } = req
    const result = await ProductosModel.create(body);
    res.send({result})
  }catch(error){
    console.log(error);
  }
}
```

### Error

`'Executing (default): INSERT INTO 'STORE_Producto' ('ProductoId','ProductoCategoriaId','ProductoNombre','ProductoPrecio','ProductoDescripcionCorta','ProductoDescripcionLarga','ProductoDescripcionCarrito','ProductoFoto','ProductoImagen','ProductoStock','ProductoDisponible','ProductoFechaActualizacion','ProductoBorrado') VALUES (DEFAULT,?,?,?,?,?,?,?,?,?,?,?,?);'
`

The table products has an auto increment primary key and Im lost at this point, can't insert yet.

**Comment by WalterClementsJr** [comment]
I'm using SQL Server. I don't create my tables with Sequelize, it already exist. My primary key is a IDENTITY column, which cannot be inserted with anything, even with NULL values, which was what Sequelize was trying to do.
```
'INSERT INTO [TBL_ORDER] ([ld_id],[amount],[price]) OUTPUT INSERTED.[ld_id],INSERTED.[amount],INSERTED.[price]
VALUES (@0,@1,@2,@3,@4);',
    parameters: { '0': null, '1': '200', '2': 3000 }
```

My solution:
- Don't put primaryKey to the id column when defining the model
- Allow the id column to null
- Remove Sequelize default 'id' when your model doesn't have a PK column
```
Order.init({
    orderId: {
        field: 'ld_id',
        type: DataTypes.INTEGER,
        allowNull: true
    },
    amount: {
        type: DataTypes.INTEGER,
        allowNull: false
    },
    price: {
        type: DataTypes.DOUBLE(20, 4),
        allowNull: false
    }
}, {
    sequelize,
    modelName: 'Order',
    tableName: 'TBL_ORDER'
});
Order.removeAttribute('id');
```

**Comment by damms005** [comment]
I think this is closed by [#14386 ](https://github.com/sequelize/sequelize/pull/14386)

**Comment by ephys** [comment]
You're right, I think it is :)
Until the feature is released, it's also possible to do `Foo.removeAttribute('id')` to remove the auto-generated primary key

**Comment by lesichkovm** [comment]
Same issue
