### ISSUE TITLE
Can not use primary table columns in where of separated joined table

### ISSUE THREAD

**Issue by NNSTH** [sequelize/sequelize#11711]
## Issue Description
I want to query a table with nested include table as separate (in order to prevent duplicate rows), but I can not find a way to use columns of the primary table within where clause of the nested included table (as if it was not separate: true)

### Describe the solution you'd like
I need an expression to use within where clause something like:
`where: {
    userId: '$payment.studentId$'
}`
or something like this, this way hasMany will be able to add this to options.where on get function.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by papb** [comment]
Hi, can you show an SSCCE for what your whole query would look like?

**Comment by saulomano** [comment]
Si, can read https://sequelize.org/master/manual/eager-loading.html in the section top level
