### ISSUE TITLE
Typescript: Can't use `sequelize.models` or `sequelize.model()`

### ISSUE THREAD

**Issue by noritama** [sequelize/sequelize#11718]
### What are you doing?

```
async () => {
  const sequelize = new Sequelize(mysqlOptions);

  class Foo extends Model {
    public id!: number;
    public value!: string;
  }

  Foo.init(
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true
      },
      value: {
        type: DataTypes.STRING,
        allowNull: false
      }
    },
    {
      sequelize,
      modelName: 'Foo',
      tableName: 'foo',
    }
  );

  const f1 = await Foo.findOne();
  console.log(f1.id); // OK

  const f2 = await sequelize.models.Foo.findOne();
  console.log(f2.id); // Property 'id' does not exist on type 'Model<unknown, unknown>'.
  
  const f3 = await sequelize.model('Foo').findOne();
  console.log(f3.id); // Property 'id' does not exist on type 'Model<unknown, unknown>'.
};
```

### What do you expect to happen?

Should be able to get `id`.

### What is actually happening?

A TypeScript error occured.
```
Property 'id' does not exist on type 'Model<unknown, unknown>'.
```

### Environment

- Sequelize version: 5.21.2
- Node.js version: v11.3.0
- Operating System: Mac
- If TypeScript related: TypeScript version: 3.7.2

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using mysql, with connector library version 2.0.1 and database version 5.7

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
@SimonSchick do you think there is an easy way to fix this?

**Comment by SimonSchick** [comment]
No, `models` and `model` are inherently unsafe as they rely on runtime type information.

**Comment by papb** [comment]
Thanks! So @noritama I'm afraid this won't have a solution. You will have to refactor your code to be able to reference your models directly, without this "shortcut" provided by sequelize.

**Comment by kevkevinpal** [comment]
I'm getting a similar error here, not sure why this is happening as it was working before

https://github.com/stakwork/sphinx-relay/runs/6819507922?check_suite_focus=true
