### ISSUE TITLE
Sequelize disregards the result of COMMIT statement in PostgreSQL

### ISSUE THREAD

**Issue by yktv4** [sequelize/sequelize#11729]
## Issue Description
Sequelize receives `ROLLBACK` as a result of `COMMIT` statement in PostgreSQL, but never shows it and silently resolves the promise of `.commit()` call;

### What are you doing?
I am:
1. creating a transaction
2. making some action that results in database-level exception within this transaction
3. trying to `commit` the transaction by sequelize

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/28
Please notice that SSCCE does not show the issue since it probably runs the latest sequelize version and I can confirm the issue with sequelize version `3.24.6`. You will have to copy the code from SSCCE to your local env with that version of sequelize to check my words.

Here is the main code snippet from SSCCE that shows the issue

```js
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

const transaction = await sequelize.transaction();
try {
  // notice I did not use `await` here intentionally to show the issue
  sequelize.query('Invalid sql code', { transaction });
  // the line above will execute within our transaction because we allow enough time (1 second in this case)
  await delay(1000);
  // sequelize issues a `COMMIT` statement into PostgreSQL which results in `ROLLBACK` performed
  await transaction.commit();
  // but sequelize does not listen to the postgres result of `COMMIT` call and thus resolves the promise
  // although the `.commit()` sequelize call should resulted in a rejected promise
  log('success, although `COMMIT` postgres statement actually was rolled back');
  log('we should have never seen these lines');
} catch (error) {
  await transaction.rollback();
}
```

### What do you expect to happen
I expect sequelize to reject the `await transaction.commit()` promise since PostgreSQL does not actually commit a transaction.

### What is actually happening?
Sequelize silently resolves the `transaction.commit()` promise as if the `commit()` went successfully.

### Additional context
Sequelize v`3.24.6` uses `pg@4.4.6`, so I tried to reproduce the issue using `pg` module to point you to the place that sequelize disregards. Here is the code snipper using `pg` module:

```js
const pg = require('pg');
const conString = "postgresql://localhost:5432/sequelize_test";

const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

pg.connect(conString, async (err, client, done) => {
  if (err) {
    return console.error('error fetching client from pool', err);
  }

  const queryAsync = (...params) => new Promise((resolve, reject) => {
    client.query(...params, function (err, result) {
      if (err) return reject(err)
      resolve(result);
    })
  });

  await queryAsync('START TRANSACTION;');
  queryAsync('Invalid sql;');
  await delay(1000);
  const resultOfCommit = await queryAsync('COMMIT;');

  console.log(resultOfCommit);   // ROLLBACK

  done();
});
```

see how `resultOfCommit.command` equals to `ROLLBACK` and not to `COMMIT`? this is what sequelize does not look at when resolving the promise of `transaction.commit()` call.

### Environment

- Sequelize version: 3.24.6
- Node.js version: 10.16.0
- Operating System: MacOS
- PostgreSQL version: 10.6

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): PostgreSQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, thanks for the detailed report, sorry to take long to reply.

A few things:

* If I understood you correctly, this problem no longer exists in Sequelize v4 and v5? Am I right?
* You can force the sequelize-sscce suite to use whatever version of sequelize you want, just commit a change to the number in package.json under your PR
* Is there any way to reproduce this issue without the trick of not using `await`? This looks too contrived to me, can you explain a little bit more what kind of situation you are that causes this kind of error?
