### ISSUE TITLE
Ignoring invalid timezone passed to Connection: Europe/Amsterdam

### ISSUE THREAD

**Issue by Whitebytes** [sequelize/sequelize#11721]
## Issue Description
Unable to set timezone to Europe/Amsterdam with mysql dialect.
Due to daylight savings, I would like to set de timezone to a named timezone instead of fixed hour offset. However, when I fill timezone with 'Europe/Amsterdam', it throws a warning on connect:
**Ignoring invalid timezone passed to Connection: Europe/Amsterdam. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection**

I'm sure momenjs is loaded with timezones, and mysql has de timezones table loaded, so both frameworks are aware of timezone 'Europe/Amsterdam'.
Unable to fix this.

### Additional context
Add any other context or screenshots about the issue here.
node version: v10.17.0
sequelize: 5.21.2
mysql:5.7.28 

mysql timezone-output in mysql cli
mysql> SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
+--------------------+---------------------+
| @@GLOBAL.time_zone | @@SESSION.time_zone |
+--------------------+---------------------+
| Europe/Amsterdam   | Europe/Amsterdam    |
+--------------------+---------------------+
1 row in set (0.00 sec)

this is my DB setup:
require('dotenv').config();
const timezone = 'Europe/Amsterdam'
require('moment-timezone').tz.setDefault(timezone)

module.exports = {
	development: {
		username: process.env.DB_USER,
		password: process.env.DB_PASSWORD,
		database: process.env.DB_NAME,
		host: process.env.DB_HOST,
		port: process.env.DB_PORT,
		dialect: "mysql",
		timezone: timezone,
		logging: false
	}
};
 

### Is this issue dialect-specific?
- [ ] Yes. This issue only applies to the following dialect(s):Mysql

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by Noxillio** [comment]
Same problem here with `America/New_York`

**Comment by UziTech** [comment]
Looks like mysql doesn't allow timezone name strings ([docs](https://github.com/mysqljs/mysql#connection-options)).

I'm not sure if this is the best way, but you can override the sequelize option by setting the `timezone` in `dialectOptions` to `"local"`

```js
new Sequelize(
	...
	{
		...
		timezone: "America/New_York",
		dialectOptions: {
			timezone: "local",
		}
		...
	}
)
```

**Comment by papb** [comment]
> Looks like mysql doesn't allow timezone name strings ([docs](https://github.com/mysqljs/mysql#connection-options)).

Precisely, thanks @UziTech, so this is not an issue with Sequelize.

**Comment by soonsam123** [comment]
@UziTech answer helped me.

In my case I need the time zone to `America/Sao_Paulo`, therefore I just googled: America Sao Paulo GMT and it gave me UTC-3

Then, I changed my config:
```
  config.dialectOptions = {
    // useUTC: false, // for reading from database
  };
  // config.timezone = "America/Sao_Paulo";
  config.timezone = "-03:00";
```

For mysql2 `useUTC` was not having any effect in my database, therefore I commented it and just -03:00 solved my problems.
