### ISSUE TITLE
String `id` field + bulkCreate does not escape the String primary key—SQL injection vulnerability?

### ISSUE THREAD

**Issue by gamburgm** [sequelize/sequelize#11723]
# Issue Description
Due to #11714, I have decided to just name my String primaryKey `id`. However, when using a String primary key with `bulkCreate`, it does not add the quotation marks to the String that gets inserted, which blows up.

The relevant piece of my config.json:
```json
{
    "development": {
        "username": null,
        "password": null,
        "database": "experiment",
        "host": "127.0.0.1",
        "dialect": "postgres"
    }
}
```

After initializing the project, I ran npx sequelize-cli models:generate --name Foo --attributes foo:string,bar:string,quux:integer and edited the migrations/...-create-foo.js file as such:

```js
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Foos', {
      id: {
        allowNull: false,
        autoIncrement: false,
        primaryKey: true,
        type: Sequelize.STRING
      },
      bar: {
        type: Sequelize.STRING
      },
      quux: {
        type: Sequelize.INTEGER
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Foos');
  }
};
```

Small test script:

```js
const db = require('./models/index.js');

const Foo = db.Foo;

Foo.bulkCreate([{ id: "Foo", bar: "Bar", quux: 42 }]).then(() => console.log("It worked!"));
```

### What do you expect to happen?

`It worked!`

### What is actually happening?

The generated SQL inserted `Foo` directly into the query and does not add the quotation marks with it.

```
Executing (default): INSERT INTO "Foos" ("id","bar","quux","createdAt","updatedAt") VALUES (Foo,'Bar',42,'2019-12-02 02:29:43.780 +00:00','2019-12-02 02:29:43.780 +00:00') RETURNING *;

Unhandled rejection SequelizeDatabaseError: column "foo" does not exist
    at Query.formatError (/Users/Mitch/sequelize/sequelize-bug/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at query.catch.err (/Users/Mitch/sequelize/sequelize-bug/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)
    at tryCatcher (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Mitch/sequelize/sequelize-bug/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

### Additional context

This seems like a weird corner-case, as I've only seen this behavior with `bulkCreate` paired with a string `id` field (that in this case at least is the primary key). I'm not sure if there are other weird situations where something like this might happen. This also definitely feels like it's rife for a SQL injection attack.

Follow-up: contrived example, but this SQL injection will work. 

```js
Foo.bulkCreate([
    { 
        id: "'Foo', '1', 2, '2019-12-02 04:05:46.971 +00:00', '2019-12-02 04:05:46.971 +00:00'); \
            select count(*) from \"Foos\"; \
            drop table \"Foos\"; \
            insert into \"Foos\" (\"id\", \"bar\", \"quux\", \"createdAt\", \"updatedAt\") values ('hello'", 
        bar: "Bar", 
        quux: 42 
    }
]).then(() => console.log("It worked!"));
```

### Environment

- Sequelize version: 5.21.2
- Node.js version: 10.16.3
- Operating System: macOS Mojave 10.14.5

### How does this problem relate to dialects?

- [x] I don't know, I was using Postgres, with connector library version pg@7.21.1 and database version PostgreSQL 11.3

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance. --> (bulkCreate isn't the easiest thing to parse :) )

**Comment by alirizwan** [comment]
I don't think it's an issue with sequelize itself rather with your code. The first problem I see in the code is the migration, you are using 
```
foo: {
        allowNull: false,
        autoIncrement: false,
        primaryKey: true,
        type: Sequelize.STRING
      },
```
for your primary key but in bulkCreate you are specifying `id: 'Foo'` you are specifying a column which doesn't exist in the migration. By default id is an integer which is the reason why there are no quotes around Foo in the query. Secondly match your model with migration and with the actual table structure in your database, it's pretty clear that they don't match.

**Comment by gamburgm** [comment]
My mistake, that was a typo—it is supposed to say `id` rather than `foo` in the migration. Same issue.

**Comment by alirizwan** [comment]
I have tried to re-produce your case and it works fine for me, can you please share your model definition? I think you have have not defined your id column explicitly like you did in your migrations, your model should have an attribute like this:
```
id: {
      allowNull: false,
      autoIncrement: false,
      primaryKey: true,
      type: DataTypes.STRING
    },
```

**Comment by gamburgm** [comment]
The model that got generated for me looks like this: 

```js
module.exports = (sequelize, DataTypes) => {
  const Foo = sequelize.define('Foo', {
    bar: DataTypes.STRING,
    quux: DataTypes.INTEGER
  }, {});
  Foo.associate = function(models) {
    // associations can be defined here
  };
  return Foo;
};
```

If I manually specify the `id` column by adding the line `id: DataTypes.STRING`, then doing anything causes the error:
```
A column called 'id' was added to the attributes of 'Foos' but not marked with 'primaryKey: true'
```

I didn't find a way to specify that the `id` was a primaryKey, but at the same time, if I do not include `id` in the model, then regular `create` works for me.

**Comment by alirizwan** [comment]
Exactly this is the problem. When you want to use a custom primary key column you have to explicitly define that column in your model definition, if that doesn't exist then sequelize will try to use default column. Just put full definition in model and your code will work fine, `id: DataTypes.STRING` will not work you have to write:

```
id: {
      allowNull: false,
      autoIncrement: false,
      primaryKey: true,
      type: DataTypes.STRING
    },
```

or at least
```
id: {
      primaryKey: true,
      type: DataTypes.STRING
    },
```

**Comment by gamburgm** [comment]
Yes, that stops those errors. However, it is strange that this error only gets raised on `bulkCreate`—with that broken definition, `create`, `save`, and every other model method I've tried so far work without errors. I am using the above 'buggy' model definition in a production environment without any issues so far, which probably shouldn't be the expected behavior. 

I would propose either a) having some sort of check for model definitions that blow up if something is wrong (an additional validation), b) having `create` and the other methods blow up similarly, or c) have all of the methods (including bulkCreate) work by always escaping the String.

Would be happy to implement it :)

**Comment by papb** [comment]
Hi @alirizwan, thanks for helping @gamburgm solve this issue :)

As for your last comment, @gamburgm, I agree that the current 'developer experience' on this is quite messy. I have opened #11830 with a different idea on how to improve this. Please share your thoughts :)

**Comment by papb** [comment]
I will close this in favor of #11830 now since your original problem was solved.
