### ISSUE TITLE
TS method overloads need to be re-ordered

### ISSUE THREAD

**Issue by dancrumb** [sequelize/sequelize#11726]
## Issue Description
The method overloading order is incorrect for a number of Model methods. This results in the wrong method signature being returned.

### What are you doing?

I'm passing a `NonNullFindOptions` object into `Model.findOne`.

**Here is the link to the SSCCE for this issue:** [TS Playground](http://www.typescriptlang.org/play/?ssl=27&ssc=43&pln=27&pc=91#code/JYOwLgpgTgZghgYwgAgGKgCYHkAOZgD2IAzsgN4CwAUMsgO4AW0EAXMgEoQIFQYA8xMFFABzADTJBwkCIB81AL7VqEAB44eYZKEixEKAHJEDAVwA2Z9CGx5CJZGsjXSVm-iKlKNZFAgArLjAsEABRAFs8AE82ACMCAjMIOBBkAB9kEKgoHgBuRWUqNQ0oLW4SLUZmcLhgMwBJUgBeZAAKSEEAVWJoNilRAEo2IxBTC1dcd3tG2XIC2l8wEygUr1paSt82MnawLugFMWo1n39A4PCotiETCEPvBWQ4UmHRy0wJu2I8qgVv6gQzE9SABZAgYCBmcjIJRUf6A4ikAAiJjCYUis28OBMMTMwAQkjAcHw+Jg7xAED4wIcqicGBBYIhsjaDGAxC2yHJdBag2QVIeADJkGBIjgIAQYLyGWYJARbB4APxscZykg8gAK2TCrIpVPSIHMZlk31oWJxeIJRPNpOswR11Np9PBhuZrPZnO5bD5yEFwtF4slTplKrZyBeBuVk2I6s12spRqOyFNuPxgktJLJdscEGcAcZLpDZA5EC5PK9PpFYoloMDyFlkaV72DaVDxnDjcj0YIWu6cebGq7sd1HINM1WawWSxS-e7EAAdL5iAkAG4QFpkB5PXn9Y3Q-KwqhlQTIGDxNjT2PI1GRGbNS9o2fW7Dktf0JibKE7PZQNgAch-0IkXwAgQIJQgiYUrigG5oW3AoAHo4OQAB1Bh0TAJgHCyHh5X+DwtBiOBv2Qc8ezva9kFvFF70fW0Wg2CBqlqBoWj-fpYP3BDkNQoUMOgbIoBwg88NrJtmnoxj6mIFif3Yw98LgAAvM8Y1IqjyMoq8HwzFo60+djqE4lC0N4rCBNw8oRMjAAZYBdDgSFmkLej2U-boiL-ACTmA0CLggoUoJQX5zKPABHExVGUgdVKvG9kDIrSbWfXSPBsuyzG3IA)

### What do you expect to happen?

I expect to get a `Promise<Model>` back.

### What is actually happening?

I get a `Promise<Model | null>` instead.

### Additional context

[The TS handbook](https://www.typescriptlang.org/docs/handbook/functions.html#overloads) outlines that

> ... it’s customary to order overloads from most specific to least specific.

### Environment

- Sequelize version: 5.21.2
- Node.js version: 12.13.0
- Operating System: macOS Catalina
- If TypeScript related: 3.7.2

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Just linking the relevant discussion here: https://github.com/microsoft/TypeScript/issues/35472

**Comment by papb** [comment]
Fixed by #11727
