### ISSUE TITLE
Result modification from 'afterFind' hook.

### ISSUE THREAD

**Issue by xobotyi** [sequelize/sequelize#11728]
### What was unclear/insufficient/not covered in the documentation

Hooks itself are not documented, tbh it is not needed for all of them, but several need clarification, 4ex: `afterFind`.

I wanted to add hook that will modify results after entries are fetched (to delete some of them) and found that there is no way to modify the result and there is not a word in description about results modification from hooks.

As i understood i can modify result items, but can't modify result itself, 4ex: return null instead of an array of items in case i deleted them all.

### If possible: Provide some suggestion on how we can enhance the docs

Add some more detailed docs in terms of interaction with query results.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by cbarlow1993** [comment]
Can't see this documented anywhere either. I'd really appreciate improved documentation on this
