### ISSUE TITLE
Sequelize v3 update to v4 : belongToMany not working anymore for an association

### ISSUE THREAD

**Issue by badbytes1** [sequelize/sequelize#11732]
Since i have update my sequelize version to 4.28 (previously 3), a belongs to many association seems not working.

the table name is UserCapabilities (many to many table). With the version 3 a sql insert was triggered by the addCapability method, but with the v4 sequelize no more sql insert.

Thanks for your help

Here is the code:

user.model.ts

    export const UserCapabilityModel: models.user.capability.Model =
        db.define<models.user.capability.Instance, models.user.capability.Attributes>('UserCapability', {
        });
    
    UserModel.belongsToMany(CapabilityModel, {
        through: UserCapabilityModel,
        foreignKey: 'userId',
        as: 'capabilities'
    });
    
    CapabilityModel.belongsToMany(UserModel, {
        through: UserCapabilityModel,
        foreignKey: 'capabilityId'
    });

 service.ts

    await developmentUser.addCapability(capabilityId, { transaction: transaction });

user.d.ts

    import * as Sequelize from 'sequelize';
    
    declare module 'models' {
    
        export namespace models {
            namespace user {
    
                interface Attributes {
                    id?: number;
                    firstName?: string;
                    lastName?: string;
                    username?: string;
                    email?: string;
                    persNr?: string;
                }
    
                interface Instance extends Sequelize.Instance<Attributes>, Attributes {
                    roles?: models.role.Instance[];
                    team?: models.team.Instance;
                    teamId?: number;
                    managerId?: number;
                    manager?: models.user.Instance[];
                    capabilities?: models.capability.Instance[];
    
                    addRole(args: string, options?: Sequelize.InstanceSaveOptions): Promise<Instance>;
                    setRoles(keyss: string[], options?: Sequelize.InstanceSaveOptions): Promise<Instance>;
                    getRoles(): Promise<models.role.Instance[]>;
                    // Only for the oauth user
                    hasRole(key: string): boolean;
    
                    getTeam(): Promise<models.team.Instance>;
                    setTeam(id: number): Promise<models.team.Instance>;
                    getManager(): Promise<models.user.Instance>;
                    setManager(id: number): Promise<models.user.Instance>;
    
                    addCapability(id: number, options?: Sequelize.RestoreOptions): Promise<capability.Instance>;
                    removeCapability(id: number, options?: Sequelize.RestoreOptions): Promise<capability.Instance>;
                    setCapabilities(ids: number[], options?: Sequelize.RestoreOptions): Promise<capability.Instance[]>;
                    getCapabilities(options?: Sequelize.FindOptions): Promise<models.capability.Instance[]>;
                    getOnlyCapabilities(): Promise<models.capability.Instance[]>;
    
                    getSkills(): Promise<models.capability.Instance[]>;
                    getExpiringDevelopments(): Promise<models.development.Instance[]>;
                }

**Comment by papb** [comment]
Hello, can you please try to isolate the problem in a snippet in pure javascript (no TS)? Thanks
