### ISSUE TITLE
Support ESCAPE syntax for MSSQL LIKE

### ISSUE THREAD

**Issue by dsbert** [sequelize/sequelize#11735]
### Is your feature request related to a problem? Please describe.

Support ESCAPE syntax for MSSQL LIKE

```sql
SELECT * FROM table WHERE colum LIKE 'te/%est' ESCAPE '/'
```

### Describe the solution you'd like

Not sure about exact syntax but something like...

```js
let where = 
{
  column: { [Sequelize.Op.like]: { value:val, escape:'/' }
}
```

### Why should this be in Sequelize

Without this it is not possible to perform a like operation on strings containing '%' or '_' without a lot of work-arounds.

### Work-around

I tried the following work around but run into issues on joins where the nested query is being geneated as `like '[object Object]'`

```js
{
  [Sequelize.Op.like]: Sequelize.literal(
    `'${val.replace("_", `/_`)}' ESCAPE '/'`)
}
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [X] Yes. This issue only applies to the following dialect(s): MSSQL

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
`Sequelize.literal` is supported in `like` and `iLike` nowadays, in theory this is resolved
