### ISSUE TITLE
Wrong date in where clause with postgre

### ISSUE THREAD

**Issue by DoYouRockBaby** [sequelize/sequelize#11743]
Hi

I noticed that with postgre, sequelize treat the date as string. If i use a where clause like this :
`options.where.createdAt = { [Op.between]: [args.minCreationDate, args.maxCreationDate] };`

my range is exprimed with the type Date

The generated sql is :
`SELECT "id", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "UsersActions" AS "UsersActions" WHERE "UsersActions"."user_id" = 'ed3997de-502b-46ce-9eab-0db3d3a008a7' AND "UsersActions"."created_at" BETWEEN '2019-12-11 23:00:00.000 +00:00' AND '2019-12-12 22:59:59.999 +00:00';`

Which is of course incorrect, postgre need a ::date suffix to work. So I should have :
`SELECT "id", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "UsersActions" AS "UsersActions" WHERE "UsersActions"."user_id" = 'ed3997de-502b-46ce-9eab-0db3d3a008a7' AND "UsersActions"."created_at" BETWEEN '2019-12-11 23:00:00.000 +00:00'::date AND '2019-12-12 22:59:59.999 +00:00'::date;`

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.

Once you do I will reopen this
