### ISSUE TITLE
Make  public of some methods in `queryInterface` 

### ISSUE THREAD

**Issue by nodejh** [sequelize/sequelize#11740]
### Is your feature request related to a problem? Please describe.

Currently the `queryInterface.showIndex` method is marked as `@private` and therefore does not appear in the docs.  Also, `databaseVersion` `showAllTables` `quoteIdentifier` `quoteIdentifiers`  are marked as `@private`, I think these methods should be `public`. 

And I was frustrated with the return type `Promise<Array>`.  The return values of many methods are `Promise`,  maybe we can add more type definitions and document these.

https://github.com/sequelize/sequelize/blob/bc87076a651acee84696f49ddc126dee4c94ec3d/lib/query-interface.js#L671

### Describe the solution you'd like

- Make `queryInterface.showIndex` public, like: https://github.com/sequelize/sequelize/issues/11451
- Add type definitions, for example:

```js
// query-interface.d.js
export interface IndexInterface {
     attribute: string;
     order: string;
}


// query-interface.js
  /**
   * Show indexes on a table
   *
   * @param {string} tableName table name
   * @param {Object} [options]   Query options
   *
   * @returns {Promise<IndexInterface[]>}
   */
  showIndex(tableName, options) {
    const sql = this.QueryGenerator.showIndexesQuery(tableName, options);
    return this.sequelize.query(sql, Object.assign({}, options, { type: QueryTypes.SHOWINDEXES }));
  }
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
> Yes, I have the time and I know how to start.

Hi, are you still interesting in working on this?

**Comment by ephys** [comment]
Resolved in v7 https://sequelize.org/api/v7/classes/queryinterface#showIndex
