### ISSUE TITLE
sequelize global hook not getting called.

### ISSUE THREAD

**Issue by ubreddy** [sequelize/sequelize#11741]
Version : 5.21.2
## Issue Description
I added couple of hooks to sequelize as global hooks. Expected them to be triggered on sequelize.query but they are not.

### What are you doing?

```js

const db = new Sequelize(config.database.name, config.database.username, config.database.password, {
    host: config.database.host,
    dialect: config.database.dialect,
    operatorsAliases: Sequelize.Op,
    logging: false,
    dialectOptions: {
        ssl: config.database.ssl != undefined ? JSON.parse(config.database.ssl) : true
    },
    pool: {
        max: 5,
        min: 0,
        acquire: 60000,
        idle: 10000
    },
    define: {
        underscored: true,
        freezeTableName: true,
        schema: config.database.schemaName,
        hooks:{
            beforeUpdate: (a,b,c)=>{
                console.log(`a: ${JSON.stringify(a)}`)
                console.log(`b: ${JSON.stringify(b)}`)
                console.log(`c: ${JSON.stringify(c)}`)
            },
            afterQuery: (a,b,c) =>{
                console.log(`a: ${JSON.stringify(a)}`)
                console.log(`b: ${JSON.stringify(b)}`)
                console.log(`c: ${JSON.stringify(c)}`)
            }
        }
    },
});
db.query(`update schema.mytable set name = 'abcd' where id= 1 returning *`, { type: Sequelize.QueryTypes.UPDATE }).then((res) => {
    console.log(JSON.stringify(camelize(res[0])))

}).catch((e) => {
    console.log(e)

})
db.close()
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Hooks are not triggered on query operations, they are triggered for Model/Instance based operation.

-----------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
