### ISSUE TITLE
Azure MS SQL gets completely different decimals

### ISSUE THREAD

**Issue by obermobber** [sequelize/sequelize#11754]
## Issue Description

High decimals are not saved correctly in the Azure MS SQL database.
For example:
18728.4 turns into 281.655926290
21345.4 turns into 2898.655926290
625348.4 turns into 16605.845567585
34348.42 turns into 15901.675926290

This only happens after breaking a certain (unknown to me) threshold, 12304.53 actually works and will be written into the DB just like that.

#### POST request

```ts
@Post('/test')
	private async postDecimalTest(
		@Body() body: testCaseBody
	) {
		try {
			const transaction = await sequelize.transaction();
			
			await DB.TestExecutionValues.create({
				testId: body.testId,
				numResult: body.numResult,
				strResult: body.strResult,
				enumResultSid: body.enumResult,
				unitId: body.unitId,
				ynPassed: body.ynPassed,
				comment: body.comment,
			}, { transaction });

			await transaction.commit();
			return { message: 'success posting test' };
		} catch (e) {
			console.log(e);
			throw e;
		}
	}
```

#### Table definition
```ts
const TestExecutionValues = sequelize.define('TestExecutionValues', {
	sid: {
		type: INTEGER,
		autoIncrement: true,
		primaryKey: true,
		allowNull: false,
	},
	testId: {
		type: STRING,
		references: {
			model: Tests,
			key: 'testId',
		},
	},
	numResult: {
		type: DECIMAL(18, 9),
	},
	strResult: {
		type: STRING,
	},
	enumResultSid: {
		type: INTEGER,
		references: {
			model: EnumResults,
			key: 'sid',
		},
	},
	unitId: {
		type: STRING,
		references: {
			model: Units,
			key: 'unitId',
		},
	},
	ynPassed: {
		type: BOOLEAN,
	},
	comment: {
		type: TEXT,
	},
}, {
	timestamps: false,
});
```

### What do you expect to happen?

I expect every decimal to be written into the database correctly.
This is the body I'm sending:

```ts
{
    "testId": "LEVEL",
    "numResult": 465324.75,
    "strResult": "testcase",
    "enumResult": "1",
    "unitId": "m³",
    "ynPassed": 1,
    "comment": ""
}
```

### What is actually happening?

Execution running smoothly:
```
Executing (036ca06b3c1869b4851b): BEGIN TRANSACTION;
Executing (036ca06b3c1869b4851b): INSERT INTO [TestExecutionValues] ([testId],[numResult],[strResult],[enumResultSid],[unitId],[ynPassed],[comment]) OUTPUT INSERTED.* VALUES (@0,@1,@2,@3,@4,@5,@6);
Executing (036ca06b3c1869b4851b): COMMIT TRANSACTION;
```
But they are not written into the DB correctly.

```ts
{
                "testId": {
                    "id": "LEVEL",
                    "description": null
                },
                "numResult": 4156.148157261,
                "strResult": "testcase",
                "enumResult": {
                    "id": "#N/A",
                    "description": null
                },
                "unit": {
                    "id": "m³",
                    "description": null
                },
                "ynPassed": true,
                "comment": ""
}
```

### Additional context

Already opened an issue with the guys from tedious but we were running some tests and it was clearly not an error on the tedous side of things.

### Environment

- Sequelize version: 5.15.2 
- Node.js version: 10.15.3 
- Operating System: macOS (but it's behaving like that when hosting in a Docker container on azure as well)
- TypeScript version: 3.3.4000
- tedious version: 6.6.5
- routing-controllers: 0.7.7
- an Azure MS SQL database

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X] I don't know, I was using mssql, with connector library version 6.6.5

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Please run your code again with the `logQueryParameters` option enabled (see #11267), so that we can see what values are really being passed in the `VALUES (@0,@1,@2,@3,@4,@5,@6)` part of the SQL call

**Comment by qianwang1013** [comment]
@papb , 

I am seeing similar issue and here is the query that is generated.
```
  INSERT INTO [Table] ([DecimalValue]) OUTPUT INSERTED.* VALUES (@0); {"0":22222.22}
```
and the result that got actually saved in the database is 3775.48
