### ISSUE TITLE
Anyway to add Getters and Setters after models defined.

### ISSUE THREAD

**Issue by chiendv** [sequelize/sequelize#11753]
Hello.

I using sequelize-auto to sync models with MySQL database and it automatically generate model schemas to files.

is there anyway which I can add Getters/Setters method to a model when the app load schemas or after models are defined.

Thank you.

**Comment by papb** [comment]
Please open an issue on [sequelize-auto](https://github.com/sequelize/sequelize-auto/issues) about it. Good luck.
