### ISSUE TITLE
Throw when symmetric associations are defined with conflicting options 

### ISSUE THREAD

**Issue by broofa** [sequelize/sequelize#11755]
## Issue Description
Symmetric associations in Sequelize (where both sides of an association are defined), are expected to be declared [with the same options](https://github.com/sequelize/sequelize/issues/6997#issuecomment-267664250).  However this is not currently enforced.

### Is your feature request related to a problem? Please describe.
Where symmetric associations are concerned, validation is currently done on a "first one wins" basis.  For example:
```
(async function() {
  const Sequelize = require('sequelize');
  const sequelize = new Sequelize({dialect: 'sqlite', storage: '/tmp/sequelize_test.sqlite'});

  const Foo = sequelize.define('foo', );
  const Bar = sequelize.define('bar', {fooId: {type: Sequelize.STRING}});

  await Foo.sync();
  await Bar.sync();

  // Switch the order of these two lines to get "bar.fooId cannot be null" error
  Foo.hasOne(Bar, {foreignKey: {name: 'fooId', allowNull: true}});
  Bar.belongsTo(Foo, {foreignKey: {name: 'fooId', allowNull: false}});

  await Bar.create({});
}())
```

The code above runs with no error.  However if you switch the order of the `hasOne` and `belongsTo` definitions, you'll get a "bar.fooId cannot be null" error when attempting to `create()` the Bar instance.

This can lead to subtle issues that are difficult to track down.  For example, I'm filing this issue because our tests started failing when we renamed a  model.  (We load models based on the order files appear in `fs.readdir()`.  Renaming changed the load order, which changed which options were validated. :-( )

### Describe the solution you'd like
Sequelize should throw an error when incompatible options (like `allowNull:false` vs. `allowNull` true) are defined for opposite sides of the same association.

### Why should this be in Sequelize
This leads to confusing errors, like #6997 

### Describe alternatives/workarounds you've considered
None

### Is this issue dialect-specific?
- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by broofa** [comment]
Still valid.

**Comment by ephys** [comment]
This has been implemented in Sequelize 7
