### ISSUE TITLE
Instance.destroy() is throwing the error: WHERE parameter "id" has invalid "undefined" value

### ISSUE THREAD

**Issue by rsshilli** [sequelize/sequelize#11756]
## Issue Description
Sequelize was throwing the following error:
```
     Error: WHERE parameter "id" has invalid "undefined" value
         at Array.forEach (<anonymous>)
         at runCallback (timers.js:705:18)
         at tryOnImmediate (timers.js:676:5)
         at processImmediate (timers.js:658:5)
         at process.topLevelDomainCallback (domain.js:126:23)
```

This was pretty hard to diagnose, but I eventually tracked it down to this code:
```
  return User.findOne({
    attributes: ["id", "username", "firstName", "lastName", "email"],
    where: {username: "user@whatever.com"}
  }).then(user => {
    if (user) {
      return user.destroy();
    } else {
      return Promise.resolve();
    }
  }).then(() => { ...
```
The destroy command works.  There's a user in the Users table with that username.  That user is properly deleted.  I can see the delete SQL on the console log. It's just that it's throwing that strange error as well.

### What do you expect to happen?

I would expect no error to be thrown on a successful delete.

### What is actually happening?

I get the error in the `Issue Description` above.

### Environment

- Sequelize version: sequelize@5.21.3
- Node.js version: v10.16.3
- Operating System: Windows 10
- If TypeScript related: (Not related)

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using MySQL, with connector library version mysql2@1.7.0 and database version 5.7.25

### Would you be willing to resolve this issue by submitting a Pull Request? Maybe.  I have a workaround though.

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

# Workaround

The workaround is just to NOT select only a few attributes.  This is the working code:
```
  return User.findOne({
    // attributes: ["id", "username", "firstName", "lastName", "email"],  <-- DON'T DO THIS
    where: {username: username}
  }).then(user => {
    if (user) {
      return user.destroy();
    } else {
      return Promise.resolve();
    }
  }).then(() => { ...
```

**Comment by papb** [comment]
I converted your code to an SSCCE here: https://github.com/papb/sequelize-sscce/pull/35

The goal is to see if I can reproduce

**Comment by papb** [comment]
Hi @rsshilli as you can see from the linked SSCCE, I was unable to reproduce, I don't see any errors. I will close for now. Please let me know if I did something wrong and I can reopen the issue. Thanks!

**Comment by rsshilli** [comment]
Huh. That's really strange. It must be something else in my code base causing this although I can't dream of what it might be. Removing the attributes worked though.
