### ISSUE TITLE
Add static instance of sequelize to each model class

### ISSUE THREAD

**Issue by cressie176** [sequelize/sequelize#11768]
### Is your feature request related to a problem? Please describe.
It's not obvious how to obtain an instance of sequelize from a static model function. I often need to do this when executing raw queries. e.g.
```js
static getMostActiveUsers() {
  return new User()._getMostActiveUsers();
}

_getMostActiveUsers() {
  return this.sequelize.query(
    User.GET_MOST_ACTIVE_USERS_SQL, 
    {
      type: QueryTypes.SELECT,
      model: User
    }
  })
}
```

### Describe the solution you'd like
I would like an instance of sequelize to be available as a static class property. 

```js
static getMostActiveUsers() {
  return User.sequelize.query(
    User.GET_MOST_ACTIVE_USERS_SQL, 
    {
      type: QueryTypes.SELECT,
      model: User
    }
  })
}
```

### Why should this be in Sequelize
Because it's common to want to use sequelize from static methods

### Describe alternatives/workarounds you've considered
I've tried using `this.constructor.sequelize` (at least I think that was the magic line), which worked OK, but it's undocumented so I didn't want to rely on it.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance.

I'd be happy to have a go at this, but suspect there's a good reason why you added sequelize to the Model constructor rather than making it a static property of the Model to begin with

**Comment by papb** [comment]
Thanks for the report, I will think about it a bit and let you know

**Comment by ephys** [comment]
the `sequelize` static property is available on models once the model has been initialized
