### ISSUE TITLE
Retrieve through attributes non-nested in eager loading

### ISSUE THREAD

**Issue by sujeet-agrahari** [sequelize/sequelize#11760]
Whenever I do a `findAll()` or `findOne()` on a model and it involves nested association. All the property of the association also get nested. Like below :
```
ProductQCStatus.findAll({
            include:[
                {
                    model:Product,
                    include:{
                        model:ProductImage
                    },
                    attributes:["product_name","product_description","category"]
                }
            ],
        })
```
It will result in something like below.
```
[{
   //fields from ProductQCStatus table 
    Product:{
         product_name: value
         product_description: value,
         ... 
         ProductImage:{
             images:[]
         }
  },
{
   //fields from ProductQCStatus table 
    Product:{
         product_name: value
         product_description: value,
         ... 
         ProductImage:{
             images:[]
         }
  }
......
]
```
**_I want the result not be nested but just one object with all the attributes defined inside nested associations._**

I have already tried `map()`, also using other functions through which I can iterate and get the desired fields. But in that case, I have to traverse whole objects. I don't want that.I went through documentation, and I couldn't find anything there.

_I wonder if there is any native method in sequelize itself to achieve this._

**Comment by papb** [comment]
Let me see if I understood correctly. Instead of:

```js
{
  Product: {
    product_name: value
    product_description: value,
    ProductImage: {
      images: []
    }
  }
}
```

what you want is:

```js
{
  Product: {
    product_name: value
    product_description: value,
    images: []
  }
}
```

That is currently not possible as far as I know...

You will have to operate on your results manually...

```js
for (const result of results) {
  result.Product.images = result.Product.ProductImage.images;
}
```

**Comment by ephys** [comment]
This is by design and I don't think we should do this ourselves, it will lead to collisions between attributes from the model & attributes from the association
