### ISSUE TITLE
queryInterface: Support DROP COLUMN IF EXISTS

### ISSUE THREAD

**Issue by jy95** [sequelize/sequelize#11774]
### Is your feature request related to a problem? Please describe.

When doing some migrations, I would like to delete a column created in a previous migration.
However, this is not possible with the current code for some scenarios.

An example : 
**migration v3**
```js
'use strict';

let opts = {tableName: 'Exercises'};

module.exports = {
    up: (queryInterface, Sequelize) => {
        if (queryInterface.sequelize.options.schema) {
            opts.schema = queryInterface.sequelize.options.schema;
        }
        return Promise.all([
            queryInterface.addColumn(opts, "isValidated", {
                type: Sequelize.BOOLEAN,
                allowNull: false,
                defaultValue: false
            })
        ]);
    },

    down: (queryInterface, Sequelize) => {
        if (queryInterface.sequelize.options.schema) {
            opts.schema = queryInterface.sequelize.options.schema;
        }
        return Promise.all([
            queryInterface.removeColumn(opts, "isValidated")
        ]);
    }
};
```

**migration v4**
```js
'use strict';

let opts = {tableName: 'Exercises'};

module.exports = {
    up: (queryInterface, Sequelize) => {
        if (queryInterface.sequelize.options.schema) {
            opts.schema = queryInterface.sequelize.options.schema;
        }
        return Promise.all([
            queryInterface.removeColumn(opts, "isValidated"),
            queryInterface.addColumn(opts, "state", {
                type: Sequelize.ENUM("42", "42-42"),
                default: "42"
            })
        ]);
    },

    down: (queryInterface, Sequelize) => {
        if (queryInterface.sequelize.options.schema) {
            opts.schema = queryInterface.sequelize.options.schema;
        }
        return Promise.all([
            queryInterface.removeColumn(opts, "state")
        ]);
    }
};
```

![image](https://user-images.githubusercontent.com/9306961/71560279-2d1c0d80-2a68-11ea-8691-852ba4cdcf0e.png)

### Describe the solution you'd like

Just add an option in the [options of removeColumn](https://sequelize.org/v5/class/lib/query-interface.js~QueryInterface.html#instance-method-removeColumn)

If I take the [test in the codebase](https://github.com/sequelize/sequelize/blob/master/test/unit/sql/remove-column.test.js#L21) as example : 

```js
      it('schema', () => {
        expectsql(sql.removeColumnQuery({
          schema: 'archive',
          tableName: 'user'
        }, 'email', { mustExist: false } ), {
          mssql: 'ALTER TABLE [archive].[user] DROP COLUMN [email];',
          mariadb: 'ALTER TABLE `archive`.`user` DROP `email`;',
          mysql: 'ALTER TABLE `archive.user` DROP `email`;',
          postgres: 'ALTER TABLE IF EXISTS "archive"."user" DROP COLUMN "email";'
        });
      });
```

### Why should this be in Sequelize

Just read what I said above ;)

### Describe alternatives/workarounds you've considered

None as truncate removeColumn promise to deal with this case is horrible :( 

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): PostgreSQL

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thanks for the request; are you sure this is postgres-only? None of the other dialects support `DROP COLUMN IF EXISTS`?

**Comment by jy95** [comment]
It depends : 

- In SQL Server, it exists only on [2016+ version](https://docs.microsoft.com/en-us/archive/blogs/sqlserverstorageengine/drop-if-exists-new-thing-in-sql-server-2016)
- In Maria DB, it exists [in their docs](https://mariadb.com/kb/en/alter-table/)
- In SQLITE, it doesn't exist [if I trust the docs](https://www.sqlite.org/lang_altertable.html)
- In Mysql, it doesn't exist

**Comment by papb** [comment]
Hmm okay, so at best it is not so straightforward in the other dialects; let's keep this request postgres-only then, to make things easier for everyone :)

**Comment by nassimmoussa** [comment]
i would like to work on this, can you give any suggestions or just go for it on my own ?

**Comment by joaoe** [comment]
For MSSQL, the best way is to use the `COL_LENGTH` builtin function. Example:
```
IF COL_LENGTH('[schemaName].[tableName]', '[colName]') IS NOT NULL
    ALTER TABLE [schemaName].[tableName] DROP COLUMN [colName];
```

**Comment by WikiRik** [comment]
Thanks to @frostzt support for this has been added in postgres through #15119 

Support for [mssql](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-2017) and [mariadb](https://mariadb.com/kb/en/alter-table/) will be added in future PRs. After those have been merged we can close this issue.
