### ISSUE TITLE
Autoload column types from db

### ISSUE THREAD

**Issue by Satont** [sequelize/sequelize#11770]
## Issue Description
Right now we need describe type for each column
```js
class Foo extends Model {}
Foo.init({
 flag: { type: Sequelize.BOOLEAN, allowNull: false, defaultValue: true },
})
```
It can me simplified to 
```js
class Foo extends Model {}
Foo.init({
  // something there, i.e hooks, e.t.c
})
```
Otherwise we have much duplication's and overhead in code.

We write migrations, where we describe types, and after that we need write model definitions with same types definitions.

So, field options can be loaded from db, like defaultValue, allowNull, e.t.c.

### Is your feature request related to a problem? Please describe.

Write overhead code is take much time.

### Describe the solution you'd like

```ts
import { Sequelize, Model } from 'sequelize'

export default class Test extends Model {
  public id!: number
  public myField!: string
}

const sequelize = new Sequelize('postgres://user:password@localhost:5432/test')

Test.init({}, { sequelize, tableName: 'tests_table', timestamps: false })

sequelize.authenticate().then(() => {
  Test.findAll().then((r) => console.log(JSON.stringify(r)))
})

```
This example is working, but returning only rows id's, so, maybe that can be extended? 

### Why should this be in Sequelize
Will save us do not write overhead, if it's not needed.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?
Nope, haven't good knowledge of this library.

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
This reminds me of [sequelize-auto](https://github.com/sequelize/sequelize-auto).

I don't think we will be supporting this in the near future... This would be very hard to do

**Comment by Satont** [comment]
Ok, got it.
