### ISSUE TITLE
Import not working while using ESM

### ISSUE THREAD

**Issue by jumpman255** [sequelize/sequelize#11777]
### What are you doing?

```node --es-module-specifier-resolution=node index.js``` or ```npm start```

https://github.com/cardi3m/sequelize-esm-bug-exemple

### What do you expect to happen?
I expected the models would be imported.

### What is actually happening?

```
Must use import to load ES Module: D:\sequelize-esm-bug-exemple\models\Model1.js
require() of ES modules is not supported.
require() of D:\sequelize-esm-bug-exemple\models\Model1.js from D:\sequelize-esm-bug-exemple\node_modules\sequelize\lib\sequelize.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename Model1.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\sequelize-esm-bug-exemple\package.json.
```

### Environment

- Sequelize version: v5.21.3
- Node.js version: v13.5.0
- Operating System: Windows 10

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
This reminds me of https://github.com/sequelize/cli/issues/861

**Comment by dmikester1** [comment]
I have been fighting with this now for probably over a year now.  Anyone figured out a good way to import the models with ESM.

**Comment by WikiRik** [comment]
https://github.com/sequelize/sequelize/pull/13689 should fix this, right?

**Comment by ephys** [comment]
This isn't actually a Sequelize issue so #13689 wouldn't fix it.

The problem with this code is that it tries to load an ESM module using `sequelize.import`. `sequelize.import` uses `require` under the hood. 

Don't use `sequelize.import`, Use the native `import()` instead: https://nodejs.org/api/esm.html#import-expressions / https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports

**Comment by ephys** [comment]
I think we can close this with the recommendation to move away from `sequelize.import` and use native import instead. Wdyt @WikiRik?

**Comment by WikiRik** [comment]
Sounds good!
