### ISSUE TITLE
How to order a query by a join table property using model instance getters

### ISSUE THREAD

**Issue by uncvrd** [sequelize/sequelize#11776]
## Issue Description

I am having issues ordering by a join table when using a model instance's `getter` methods. For example, I have a project with `Playlists`, `Tracks`, and a join table of `PlaylistTracks` that contains an `order` property. When I try to query and order by the join table `order` property using the `Playlist` model instance: 

```js
playlist.getTracks({
    include: [{ model: Playlist }],
    order: [[ Playlist, PlaylistTrack, "order", "ASC" ]]
})
```

The results **don't always return in the correct order**. I've described this issue in depth on StackOverflow below:

### StackOverflow / Slack attempts

Here's my StackOverflow question: https://stackoverflow.com/q/59528178/6480913

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Can you please let me know if [this new section of the docs](https://sequelize.org/master/manual/eager-loading.html#ordering-eager-loaded-associations) solves your problem?

**Comment by plusor** [comment]
> Can you please let me know if [this new section of the docs](https://sequelize.org/master/manual/eager-loading.html#ordering-eager-loaded-associations) solves your problem?

Apparently not, How to order with customized column?

Imagine for Tag has many items, per items has own ordering logic of Tag.
