### ISSUE TITLE
Docs on "save" do not mention associations

### ISSUE THREAD

**Issue by jcalfee** [sequelize/sequelize#11787]
### What was unclear/insufficient/not covered in the documentation

This says "save" will save the "fields" .. If I query a parent and a bunch of child objects, update some child objects, then call save on the parent will all changes get persisted?

https://sequelize.org/master/class/lib/model.js~Model.html#instance-method-save

### If possible: Provide some suggestion on how we can enhance the docs

It would be good to document this either way.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
I will update the docs soon. Thanks for pointing this out.

For now, here is the answer: `save()` is not aware of associations, and will simply ignore any changes you make to some child (eager-loaded) object.
