### ISSUE TITLE
sequelize关联导致查询失败

### ISSUE THREAD

**Issue by diy4869** [sequelize/sequelize#11780]
![image](https://user-images.githubusercontent.com/29079700/71638330-dbf26080-2c97-11ea-96ff-b4ca0f295637.png)
![image](https://user-images.githubusercontent.com/29079700/71638336-ee6c9a00-2c97-11ea-946c-6a0dd98c2f14.png)
![image](https://user-images.githubusercontent.com/29079700/71638339-f593a800-2c97-11ea-8f0c-cbcc0ecec0b2.png)
数据库上是有数据的，然而当我companyId为null的时候，会导致我查询不到这条数据
![image](https://user-images.githubusercontent.com/29079700/71638345-2d9aeb00-2c98-11ea-82cc-8f2079a5c54a.png)
![image](https://user-images.githubusercontent.com/29079700/71638346-3be90700-2c98-11ea-8997-1eb1614adc48.png)
这是我关联和查询的相关代码，company关联bangumi的关系是一对多，我bangumi里面的companyId为空就会查询失败，也没有任何报错信息

**Comment by papb** [comment]
I can't understand. Please provide a [sequelize-sscce](https://github.com/papb/sequelize-sscce).

**Comment by diy4869** [comment]
The problem has been solved

**Comment by soryy708** [comment]
If it was solved then the issue should be closed.
