### ISSUE TITLE
Sequelize constructor define.attributes.exclude ignored

### ISSUE THREAD

**Issue by jacob-fueled** [sequelize/sequelize#11789]
### What are you doing?

I'm trying to globally exclude a column which is present in all tables.

```js
new Sequelize('example', 'jacob', 'test123', {
  define: {
    attributes: {
      exclude: [
        'sensitiveColumn',
      ],
    },
    paranoid: true,
    timestamps: true,
    underscored: true,
  },
  dialect: 'mysql',
  host: 'localhost',
});
```

### What do you expect to happen?

According to the [Sequelize constructor's docs](https://sequelize.org/v5/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor), I can pass any option supported by `Module.init`:

Sequelize constructor:

Name | Type | Attribute | Description
--- | --- | --- | ---
`options.define` | `Object` | optional default: `{}` | Default options for model definitions. See [Model.init](https://sequelize.org/v5/class/lib/model.js~Model.html#static-method-init).

Model.init:

Name | Type | Attribute | Description
--- | --- | --- | ---
`options.attributes.exclude` | `Array<string>` | optional | Select all the attributes of the model, except some few. Useful for security purposes e.g. `{ attributes: { exclude: ['password'] } }`

### What is actually happening?

The excluded column is not excluded.

### Environment

- Sequelize version: 5.21.3
- Node.js version: 13.3.0
- Operating System: macOS 10.14.5

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using mysql, with mysql2 version 2.0.2 and database version 8.0.18

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
I think you're mistaken, the `options.attributes.exclude` you posted above is not from `Model.init`, it seems to be `model.findAll`.

That said, what you want can be achieved with a default scope:

```js
define: {
  defaultScope: {
    attributes: {
      exclude: ['sensitiveColumn']
    }
  }
}
```

However, keep in mind that if you use any other scope in a finder query, this configuration will be overriden by that query.

Learn more at our [scopes guide](https://sequelize.org/master/manual/scopes.html). Hope I helped :)

**Comment by jacob-fueled** [comment]
@papb I tried `defaultScope` first (stumbling upon it in this [SO post](https://stackoverflow.com/a/47021460)). It did not work.

>if you use any other scope in a finder query, this configuration will be overriden by that query

I'm sorry, but that is absolutely ridiculous. I could understand if there was some kind of collision (like `where` defined in both) that the default would get overridden (because that's exactly how defaults are supposed to work), but to just throw the baby out with the bath water is nuts.

**Comment by papb** [comment]
> I linked the documentation and copy+pasted it into my post. How am I mistaken?

I have no idea, but what I am sure is that the docs you linked do not show any `options.attributes.exclude` in `Model.init`, although I could find it in `Model.findAll`.

> I'm sorry, but that is absolutely ridiculous. I could understand if there was some kind of collision (like `where` defined in both) that the default would get overridden (because that's exactly how defaults are supposed to work), but to just throw the baby out with the bath water is nuts.

Hmm, we could change the behavior for what you're saying but that would be a breaking change. Currently, as our docs show, if you don't want the defaultScope to be automatically removed you have to explicitly mention it again:

[![image](https://user-images.githubusercontent.com/20914054/72687433-6e8a6080-3adc-11ea-8ce2-4316c57cf69b.png)](https://sequelize.org/master/manual/scopes.html)

It looks like you wanted `Project.scope('deleted')` to be equivalent to `Project.scope('defaultScope', 'deleted')`, right? We could make this change but it would be breaking... I suggest you implement a workaround for that, let me know if you don't know how to do it

> @papb I tried `defaultScope` first (stumbling upon it in this [SO post](https://stackoverflow.com/a/47021460)). It did not work.

That's unfortunate, it has to work, if it is not working it is a bug. I couldn't reproduce it though, please create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) to show it happening, thanks

**Comment by jacob-fueled** [comment]
>It looks like you wanted Project.scope('deleted') to be equivalent to Project.scope('defaultScope', 'deleted'), right?

Well, not specifically. I want to be able to set global default options for queries, whether that's done with a scope or with a purple unicorn is not too important as long as it actually behaves like a default (where, most importantly I don't have to do anything special to receive the default):

```js
const sql = new Sequelize('example', 'jacob', 'test123', {
  defaults: {
    attributes: {
      exclude: [
        'sensitiveColumn',
      ],
    },
  },
});
```

```js
await Project.findOne({ where: { id: params.projectId } })
{
  id: 'abc123',
  name: 'test project',
  // notice that there is no 'secretColumn' here
  // because it was globally excluded in the defaults
}
```

and it would be overridden with something like:

```js
await Project.findOne(
  { where: { id: params.projectId } },
  { attributes: { include: ['secretColumn'] } },
);
{
  id: 'abc123',
  name: 'test project',
  secretColumn: 42, // present due to the explicit include
}

```
