### ISSUE TITLE
Same relation/association with different foreign key always return same data solution

### ISSUE THREAD

**Issue by devzainali** [sequelize/sequelize#11781]
## Issue Description
i am using sequelize with nodejs
i have two user roles
1-owner
2-renter
when i using these two relation in two different modules they always gives data related to ownerId..
PendingRequest.belongsTo(User, {  foreignKey: 'ownerId' });
PendingRequest.belongsTo(User, {  foreignKey: 'renterId' });

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.
