### ISSUE TITLE
How to get a GTID value?

### ISSUE THREAD

**Issue by jjeejj** [sequelize/sequelize#11795]
### What was unclear/insufficient/not covered in the documentation

When an updated transaction is executed successfully, how to get the transaction **GTID** value?

**Comment by papb** [comment]
> Executed (9e1d032a-ea39-4b5b-ab8b-a9803b926536): SELECT 1+1 AS result

You mean this UUID? Or something else?

**Comment by jjeejj** [comment]
@papb  not UUID,; GTID : **Global Transaction ID**
