### ISSUE TITLE
create returns JSONB as string

### ISSUE THREAD

**Issue by osmanraifgunes** [sequelize/sequelize#11790]
## Issue Description
Table coulmn has a column named history and default JSONB value as '[]'

When using `findAll` method, table returns JSONB as json in history attribute.

But create method returns as string. like "[]"

**Here is the link to the SSCCE for this issue:** LINK-HERE 

### What do you expect to happen?

I want history column to be returned as json.

### What is actually happening?

```
Sample output : "[]"
Wanted output : []
```

### Environment

- Sequelize version: 5.21.3
- Node.js version: 12
- Operating System: windows

### How does this problem relate to dialects?

- [  ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [  ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Please provide a [sequelize-sscce](https://github.com/papb/sequelize-sscce) to allow contributors to work on this on a timely manner. Once you do I will reopen.
