### ISSUE TITLE
Getting null reference exception in query.js when creating a record in a table.

### ISSUE THREAD

**Issue by SolutiaMR** [sequelize/sequelize#11791]
This is occurring after **successfully** writing a record to a table in my MSSQL database?

> TypeError: Cannot read property 'id' of undefined
>     at Query.handleInsertQuery (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\sequelize\lib\dialects\mssql\query.js:377:39)
>     at Query.formatResults (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\sequelize\lib\dialects\mssql\query.js:145:12)
>     at Request.userCallback (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\sequelize\lib\dialects\mssql\query.js:76:24)
>     at Request.callback (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\lib\request.js:37:27)
>     at Connection.endOfMessageMarkerReceived (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\lib\connection.js:2185:20)
>     at Connection.dispatchEvent (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\lib\connection.js:1172:36)
>     at Parser.<anonymous> (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\lib\connection.js:975:14)
>     at Parser.emit (events.js:210:5)
>     at Parser.<anonymous> (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
>     at Parser.emit (events.js:210:5)
>     at addChunk (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:297:12)
>     at readableAddChunk (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:279:11)
>     at Parser.Readable.push (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:240:10)        
>     at Parser.Transform.push (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32)      
>     at Parser.afterTransform (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:88:10)       
>     at Parser._transform (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\lib\token\stream-parser.js:41:7)
>     at Parser.Transform._read (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:177:10)     
>     at Parser.Transform._write (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:164:83)    
>     at doWrite (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:405:139)
>     at writeOrBuffer (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:394:5)
>     at Parser.Writable.write (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:303:11)       
>     at Parser.addEndOfMessageMarker (C:\Projects\StraightFlush\StraightFlushApp\build\server\node_modules\tedious\lib\token\token-stream-parser.js:45:24)

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). This issue will be closed for not following the issue template. Take a look in our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues).

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
