### ISSUE TITLE
Creating with recently created id in include

### ISSUE THREAD

**Issue by tbveloso** [sequelize/sequelize#11792]
### What was unclear/insufficient/not covered in the documentation

I`m trying to create a INSERT using the command:

`
    const newUser = await Users.create(
      {
        name,
        username,
        password,
        userEmails: [{ email, default: true, createdBy: this.id }]
      },
      {
        include: "userEmails"
      }
    ).catch(err => {
      console.log("ERROR -> ", err);
    });
`
in userEmails, i need to insert the recently created user id in the column createdBy.

i put **_this.id_**, but obviously it didn't work...

I am not finding anything about this in the docs...

How can I do it? 

### If possible: Provide some suggestion on how we can enhance the docs

No suggestions!

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by tbveloso** [comment]
somebody?

**Comment by papb** [comment]
This is a great question. I don't know...

What would be the SQL query that sequelize should generate in this case?

**Comment by tbveloso** [comment]
up!

**Comment by ephys** [comment]
What you want seems to be this feature: https://github.com/sequelize/sequelize/issues/5325.

I'll remove the `type: docs` label so stale bot can close this issue if the original poster is inactive because I think this issue can be deduplicated
