### ISSUE TITLE
Multi-tenancy scenario support

### ISSUE THREAD

**Issue by pragmaticivan** [sequelize/sequelize#11800]
### What was unclear/insufficient/not covered in the documentation

Is there a reasonable way to support multi-tenancy with a schema-based tenant?

ex, I have 3 DBS, each DB has the same table structures so it could use the same modules, but it requires 3 Knex connections, how would someone manage to kee the 3 connections and selecting the right one when using a model?

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
I have no experience with multi-tenancy, I don't know if this is supported

**Comment by pragmaticivan** [comment]
For ref: https://vincit.github.io/objection.js/recipes/multitenancy-using-multiple-databases.html
