### ISSUE TITLE
For some reason, some records are not getting updated

### ISSUE THREAD

**Issue by fzamperin** [sequelize/sequelize#11807]
### What are you doing?

I'm using sequelize on a production project, there's a feature that updates the records of a table called Pedido (Order), when the order is delivered to the user who ordered I execute an update in this record in order to update the payment method, observations and to update the status to delivered, but for some reason some records update successfully and other don't, here is the code I'm using to update the records, I query the records based on ownid or id. The database is MariaDB v10.2.21, but I'm using Mysql dialect with sequelize, mysql2 version is 1.4.2

```js
router.post('/atualizastatuspagamento', async (req, res, next) => {
  try {
    let ownid = req.body.ownid
    let id = req.body.id
    let formapagamento = req.body.formapagamento
    let observacoes = req.body.observacoes

    let pedido = null

    if (id) {
      pedido = await db.Pedido.findById(id)
    } else {
      pedido = await db.Pedido.findOne({
        where: {
          ownid: ownid
        }
      })
    }

    if (!pedido) {
      throw Error('Pedido não encontrado')
    }

    if (pedido.status !== 'Entregue') {
      await pedido.update({
        status_pagamento_fisico: 'Pago',
        status: 'Entregue',
        formapagamento: formapagamento,
        observacoes: observacoes
      });
    } else if (pedido.status === 'Entregue') {
      throw Error('O pedido já foi retirado')
    } else {
      throw Error('Erro ao atualizar o status do pedido')
    }

    res.status(200).send({})

  } catch (err) {
    console.log(err)
    const erro = errormessage.generateError('Erro ao atualizar o status do pedido', err)
    res.status(400).send(erro)
  }
})
```

### What do you expect to happen?

For all the records to be updated.

### What is actually happening?

Some records are not getting updated

### Additional context

Those below are the logs, I put a log after the update you can see that the instance in memory is updated and the command is executed, but in the database the record is not getting updated. I identified a pattern in here, when two different records tries to update in the same time (or in a time close to each other) both of them are not getting updated. PS: A record does not get called in the same update in this case, it's always a different record.

```
Executing (default): UPDATE `Pedido` SET `status_pagamento_fisico`='Pago',`status`='Entregue',`formapagamento`='Sodexo',`updatedAt`='2020-01-09 12:26:51' WHERE `id` = 74922
Atualizou, {"id":74922,"ownid":"fd27497c-0ee3-49fd-945e-3a07c1be073a","status":"Entregue","status_pagamento_fisico":"Pago","statuspagamento":"CREATED","formapagamento":"Sodexo","tipoentrega":"Foodtruck","quantidade":1,"previsaoinicial":null,"previsaofinal":null,"observacoes":null,"createdAt":"2020-01-09T14:52:55.000Z","updatedAt":"2020-01-09T15:26:51.404Z","AvaliacaofornecedorId":null,"AvaliacaousuarioId":null,"CupomId":null,"OfertadodiaId":16202,"UsuarioId":11942,"CartaoId":null,"EnderecousuarioId":null}
Executing (default): UPDATE `Pedido` SET `status`='Entregue',`updatedAt`='2020-01-09 12:26:52' WHERE `id` = 74845
Atualizou, {"id":74845,"ownid":"4934bedb-cb1a-4453-943f-2b55ac8789a2","status":"Entregue","status_pagamento_fisico":"Pago","statuspagamento":"CREATED","formapagamento":null,"tipoentrega":"Foodtruck","quantidade":1,"previsaoinicial":null,"previsaofinal":null,"observacoes":null,"createdAt":"2020-01-09T13:39:42.000Z","updatedAt":"2020-01-09T15:26:52.880Z","AvaliacaofornecedorId":null,"AvaliacaousuarioId":null,"CupomId":null,"OfertadodiaId":16226,"UsuarioId":21388,"CartaoId":5855,"EnderecousuarioId":null}
```

### Environment

- Sequelize version: 4.18.0
- Node.js version: 8.9.4
- Operating System: Ubuntu 16.04

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): mysql/mariadb
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.
