### ISSUE TITLE
Can we get an isDeleted flag on an instance?

### ISSUE THREAD

**Issue by amaster507** [sequelize/sequelize#11806]
### I was looking through a console of the single instance and see the `isNewRecord` flag. Would it be possible to add a flag for `isDeleted`?

```js
db.tags.findAll({where: MyWhereObj, attributes: MyFieldArray}).then(tags => {
  _.forEach(tags, tag => {
    //more processing scripts for tag
    tag.destroy().then(deleted => {
      console.log(deleted.isDeleted)
    })
  })
})
```

### Workarounds considered
To know if the record was deleted I could either do a reload using `.reload()` of the instance to send another SELECT command to the database, or I could try to catch the destroy method... IDK, I am newer to sequelize.

### Additional context
I am using MySQL 8.0.16 and running sequelize 5.21.2

### Is this issue dialect-specific?

- [x] No. This issue is relevant to sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
In which scenario would you call `.destroy` but the instance will not get destroyed? Is this possible?

**Comment by amaster507** [comment]
> In which scenario would you call `.destroy` but the instance will not get destroyed? Is this possible?

Isn't it possible that the database connection is lost or that there is a foreign key constraint on the record that would keep the instance from really getting destroyed at the database level?

**Comment by papb** [comment]
Hmm, in those cases yes, but I think both cases would cause an error anyway, so the `.then` callback wouldn't even execute. So you can detect those things in a `.catch` block, what do you think?

**Comment by amaster507** [comment]
> Hmm, in those cases yes, but I think both cases would cause an error anyway, so the `.then` callback wouldn't even execute. So you can detect those things in a `.catch` block, what do you think?

I have not yet run these situations. I will setup the two scenarios at hand when I get some more time and see how they are currently handled and if a catch block is sufficient. Thank you for the feedback and time.

I will close this issue for now until I have further example of a catch not working.
