### ISSUE TITLE
AddIndex method use wrong interface type

### ISSUE THREAD

**Issue by ThingUroboros** [sequelize/sequelize#11816]
I wanted to use this

```
  await query.addIndex('Foo', {
    name: 'foo_created_at_DESC_id',
    fields: [{ name: 'createdAt', order: 'DESC' }, 'id'],
  });
```

Type is wrong defined

after this small modification everything is OK

```
  public addIndex(
    tableName: string,
    options: QueryInterfaceIndexOptions & { fields: string[] },
    rawTablename?: string
  ): Promise<void>;
```
Change & on |
```
  public addIndex(
    tableName: string,
    options: QueryInterfaceIndexOptions | { fields: string[] },
    rawTablename?: string
  ): Promise<void>;
```
 
### Environment
* Sequelize version: sequelize@5.21.3
* Node.js version: v13.5.0
* Operating System: Linux Mint 19.1 Tessa
* TypeScript: 3.7.4
 
 ## Issue Template Checklist
 ### Is this issue dialect-specific?
 * [x] No. This issue is relevant to Sequelize as a whole.
 * [x] Yes. This issue only applies to the following dialect(s): 5.21.3
 * [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?
* [ ] Yes, I have the time and I know how to start.
* [x] Yes, I have the time but I don't know how to start, I would need guidance.
* [ ] No, I don't have the time, although I believe I could do it if I had the time...
* [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by up73k** [comment]
>  fields: [{ name: 'createdAt', order: 'DESC' }, 'id'],

@papb please add info about columns order for addIndex to docs, I spent a hour in digging issues before found it. Thanx.
