### ISSUE TITLE
Creating instance with include of multiple child-instances does mix up order sometimes

### ISSUE THREAD

**Issue by pkyeck** [sequelize/sequelize#11813]
## Issue Description
I have models setup like this:

File ---hasMany---> FileLogs ---belongsTo---> FileStatus

When creating a `File` instance with an array of `FileLogs` the order of the items in the array is sometimes different from the entries in the DB. Most of the times it's fine, but sometimes CI is complaining and the tests fail because of this. Which is really annoying.

### What are you doing?

Setup of the models:

```js
const File = sequelize.define('File', {
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
  },
  name: {
    type: DataTypes.STRING,
    unique: true,
  },
  meta: DataTypes.JSON,
  originalName: DataTypes.STRING,
});

File.associate = models => {
  File.LOGS = File.hasMany(models.FileLog, { as: 'logs', foreignKey: 'fileId' });
};

const FileLog = sequelize.define('FileLog', {
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    primaryKey: true,
    autoIncrement: true,
  },
});

FileLog.associate = models => {
  FileLog.STATUS = FileLog.belongsTo(models.FileStatus, {
    as: 'status',
    foreignKey: 'statusId',
    targetKey: 'statusId',
  });
};

const FileStatus = sequelize.define(
  'FileStatus',
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
    },
    statusId: {
      type: DataTypes.INTEGER.UNSIGNED,
      unique: true,
    },
    name: {
      type: DataTypes.STRING,
      unique: true,
    },
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
```

Then, when creating like this:

```js
await File.create({
  name: 'test', 
  meta: {},
  originalName: 'test.jpg',
  logs: [
    { statusId: 101 },
    { statusId: 102 },
    { statusId: 201 },
  ],
}, { includes: [File.LOGS] })
```

### What do you expect to happen?

I was thinking/hoping that the Logs would always get created in the order of the array.

```js
[
  { id: 1, fileId: 1, statusId: 101 },
  { id: 2, fileId: 1, statusId: 102 },
  { id: 3, fileId: 1, statusId: 201 },
]
```

### What is actually happening?

```js
expect(received).toEqual(expected) // deep equality
```

```diff
- Expected
+ Received

@@ -32,21 +32,21 @@
          "id": 2,
          "logs": Array [
            Object {
              "createdAt": "2017-12-24T00:00:00.000Z",
              "id": 1,
-             "statusId": 101,
+             "statusId": 102,
            },
            Object {
              "createdAt": "2017-12-24T00:00:00.000Z",
              "id": 2,
-             "statusId": 102,
+             "statusId": 201,
            },
            Object {
              "createdAt": "2017-12-24T00:00:00.000Z",
              "id": 3,
-             "statusId": 201,
+             "statusId": 101,
            },
          ],
          "meta": Object {
            "templateName": "h265",
          },

   473 |           ),
   474 |         });
 > 475 |         expect(response.body).toEqual(res);
```

### Environment

- Sequelize version: 4.44.2 
- Node.js version: 10.15.1 
- Operating System: Docker: node:10.15.1-alpine

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using MySQL, with connector library version mysql2-1.6.5 and database version mysql:5.7.20

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hi, thanks for the report, can you please post which SQL is being generated by Sequelize? Please enable `logQueryParameters: true` in the Sequelize constructor so we can see the parameters as well

**Comment by pkyeck** [comment]
@papb The logs look ok, but when the test fails and I look into the DB, the order is wrong.

Logs:

```
sequelize:sql:mysql Executing (default): INSERT INTO `Files` (`id`,`name`,`type`,`ext`,`originalName`,`createdAt`,`updatedAt`,`resourceId`) VALUES (DEFAULT,?,?,?,?,?,?,?); "ebaeb453fea8b08ef212585f4b721a9ae9f5af90", "video/mp4", "mp4", "test.mp4", "2017-12-24 00:00:00", "2017-12-24 00:00:00", 1 +0ms
  sequelize:sql:mysql parameters(["ebaeb453fea8b08ef212585f4b721a9ae9f5af90","video/mp4","mp4","test.mp4","2017-12-24 00:00:00","2017-12-24 00:00:00",1]) +0ms
  sequelize:sql:mysql Executed (default): INSERT INTO `Files` (`id`,`name`,`type`,`ext`,`originalName`,`createdAt`,`updatedAt`,`resourceId`) VALUES (DEFAULT,?,?,?,?,?,?,?); "ebaeb453fea8b08ef212585f4b721a9ae9f5af90", "video/mp4", "mp4", "test.mp4", "2017-12-24 00:00:00", "2017-12-24 00:00:00", 1 +0ms
  sequelize:sql:mysql Executing (default): INSERT INTO `FileLogs` (`id`,`createdAt`,`updatedAt`,`statusId`,`fileId`) VALUES (DEFAULT,?,?,?,?); "2017-12-24 00:00:00", "2017-12-24 00:00:00", 101, 1 +0ms
  sequelize:sql:mysql parameters(["2017-12-24 00:00:00","2017-12-24 00:00:00",101,1]) +0ms
  sequelize:sql:mysql Executed (default): INSERT INTO `FileLogs` (`id`,`createdAt`,`updatedAt`,`statusId`,`fileId`) VALUES (DEFAULT,?,?,?,?); "2017-12-24 00:00:00", "2017-12-24 00:00:00", 101, 1 +0ms
  sequelize:sql:mysql Executing (default): INSERT INTO `FileLogs` (`id`,`createdAt`,`updatedAt`,`statusId`,`fileId`) VALUES (DEFAULT,?,?,?,?); "2017-12-24 00:00:00", "2017-12-24 00:00:00", 102, 1 +0ms
  sequelize:sql:mysql parameters(["2017-12-24 00:00:00","2017-12-24 00:00:00",102,1]) +0ms
  sequelize:sql:mysql Executing (default): INSERT INTO `FileLogs` (`id`,`createdAt`,`updatedAt`,`statusId`,`fileId`) VALUES (DEFAULT,?,?,?,?); "2017-12-24 00:00:00", "2017-12-24 00:00:00", 201, 1 +0ms
  sequelize:sql:mysql parameters(["2017-12-24 00:00:00","2017-12-24 00:00:00",201,1]) +0ms
  sequelize:sql:mysql Executed (default): INSERT INTO `FileLogs` (`id`,`createdAt`,`updatedAt`,`statusId`,`fileId`) VALUES (DEFAULT,?,?,?,?); "2017-12-24 00:00:00", "2017-12-24 00:00:00", 102, 1 +0ms
  sequelize:sql:mysql Executed (default): INSERT INTO `FileLogs` (`id`,`createdAt`,`updatedAt`,`statusId`,`fileId`) VALUES (DEFAULT,?,?,?,?); "2017-12-24 00:00:00", "2017-12-24 00:00:00", 201, 1 +0ms
```

DB: 
<img width="438" alt="Screenshot 2020-01-20 at 10 49 44" src="https://user-images.githubusercontent.com/870980/72716513-9a582580-3b72-11ea-9590-e9c7cddb1269.png">

**Comment by papb** [comment]
@pkyeck Hmmm, I see...

I would like to try to reproduce this, but you have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Can you please provide a [sequelize-sscce](https://github.com/papb/sequelize-sscce) for this? Thanks

**Comment by pkyeck** [comment]
@papb I created a SSCCE but the associations are not working - at least not when I'm trying to use the includes option like this: `File.create({}, { includes: XXX })` (see https://github.com/pkyeck/sequelize-sscce/blob/patch-1/src/sscce.js#L79-L88)

plus: the error does not happen everytime - only sporadic.

**Comment by papb** [comment]
@pkyeck Thanks, I will try to take a look later. Are you sure MySQL guarantees the insertion order though? I looked around for information on bulk insert for mysql ([1](https://dev.mysql.com/doc/refman/5.5/en/optimizing-myisam-bulk-data-loading.html), [2](https://dev.mysql.com/doc/refman/5.5/en/optimizing-innodb-bulk-data-loading.html), [3](https://dev.mysql.com/doc/refman/5.5/en/insert-optimization.html), [4](https://www.guru99.com/insert-into.html), [5](https://www.geeksengine.com/database/data-manipulation/bulk-insert.php)) but I couldn't find anything explicitly guaranteeing that the insertion order is preserved, what do you think about this?

**Comment by pkyeck** [comment]
@papb don't know - I was always expecting it to be guaranteed.
Couldn't find anything either, so I opened a question on SO: https://stackoverflow.com/questions/59893125/mysql-is-the-order-of-a-multi-insert-guaranteed

Is sequelize doing a `INSERT INTO ... VALUES (), (), ()`? Looking at the logs it looks like it is doing single INSERTS instead...
