### ISSUE TITLE
Destroy() method where condition not working with createdAt

### ISSUE THREAD

**Issue by Mayankyadav123** [sequelize/sequelize#11810]
### What are you doing?
I am trying to delete all database entries based on createdAt time. I will keep only 5 min buffered captcha from captcha Token Table and remove all entries which are less than 5 min old.

```js
//Captchas is model with destroy method
const database = config.get(APP_CONSTANTS.AUTH_DB);
const Captchas = request.getModel(database, APP_CONSTANTS.CAPTCHA_TABLE);
const val = await Captchas.destroy({
    where: {
      createdAt: {
        $lt: new Date(new Date() - 5 * 60 * 1000) //remove entries created less than 5 min old
      }
    },
    force: true
  });
console.log(val);
```

### What do you expect to happen?

I wanted entries to delete and val to return 1(it returns 1 when deleted and 0 when not deleting)

### What is actually happening?

It was not deleting anything 

```
val =0
```
### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). This issue will be closed for not fully following the issue template. Take a look in our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues).
