### ISSUE TITLE
Which Sequelize data type should I use for a MySQL `BIT` column?

### ISSUE THREAD

**Issue by rajajwaliya** [sequelize/sequelize#11817]
Which Sequelize data type should I use for a MySQL `BIT` column?

**Comment by goonerify** [comment]
Boolean seems to be the logical choice

https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/data-types.js#L397

**Comment by MithileshHinge** [comment]
A/c docs:
`DataTypes.BOOLEAN            // TINYINT(1)`

which is not the same. In MySQL, TINYINT(1) still consumes 1 byte of memory and accepts values from -128 to 127.
One the other hand BIT(1) takes 1 bit in storage but needs to be aligned in whole bytes (multiple BIT columns can be packed in the same byte). This is closer to a Boolean than Tinyint.
Would love to see a MySQL BIT implementation in sequelize. I think it is much needed.
