### ISSUE TITLE
Improving test suite for typescript

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11829]
Our current method of testing typings is a bit weak, only checking if certain things compile.

I've wanted to have a better testing suite for this for a while; now I've stumbled upon a explicit need for this: [here](https://github.com/sequelize/sequelize/pull/11820#issuecomment-574523114).

Suggestion: use [tsd](https://github.com/SamVerschueren/tsd) - thanks @RobinBuschmann for the idea.

**Comment by papb** [comment]
@SimonSchick what do you think?

**Comment by SimonSchick** [comment]
Not oppose to it, personally I'd try to just move the test files to TS themselves which would sorta solve this problem.

**Comment by RobinBuschmann** [comment]
Hey @SimonSchick, can you clarify what you mean with “move the test files to TS”? I don’t understand it

**Comment by papb** [comment]
Hi @RobinBuschmann, I think he meant to change our whole Sequelize test files to typescript (as opposed to having only the typings tests in typescript).

What do you think? Apart from the fact that it would be a huge task, would that really solve what you want to solve our would it still not be enough?

Intuitively it seems to me that the special assertions from tsd such as `ExpectType` are still stronger that that (but I'm not sure)

**Comment by RobinBuschmann** [comment]
Hey @papb, thanks for clarifying this. But yes, this wouldn't solve the issue. In order to ensure that only properties defined on the model class are allowed in `create` and so on we need to be able to expect compiler errors and don't cause the tests to fail.

**Comment by papb** [comment]
@RobinBuschmann great, please let me know if you stumble into anything blocking so I can help you get your PRs merged :)
