### ISSUE TITLE
sql_mode setup for connections

### ISSUE THREAD

**Issue by damaon** [sequelize/sequelize#11826]
## Issue Description

I wonder how to best setup session SQL mode for each connection using Sequelize. Similar issue to https://github.com/sidorares/node-mysql2/issues/565

Should I simply modify `createConnection` from dialect? Or is there better way to do this?

I think it would best if there was some API that allowed to configure this via `connectionConfig`:

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hi! Thanks for the report. I don't know if there is currently a way to do this. If it does, it should be added to the manuals...

Have you tried using the `beforeConnect` hook? (just throwing ideas here)

**Comment by papb** [comment]
> Yes, I have the time and I know how to start.

Oh, great! Please feel free to send a PR.

**Comment by YxxY** [comment]
the hooks solve my problem,   FYI
```js
const { Sequelize, QueryTypes } = require('sequelize');
const logger = console.log.bind(console)

const db = new Sequelize(database, user, password, {
    host: host,
    dialect: 'mysql',
    timezone: '+08:00',
    logging: logger,
});

db.addHook('beforeConnect', async (config) => {
    logger('connect to db: "%s", database: "%s"', config.host, config.database)
})

db.addHook('afterConnect', async (connection, config) => {
    const res = await connection.promise().query("select @@global.sql_mode", { type: QueryTypes.QUERY })
    logger('get sql_mode: %o', res)

    await connection.promise().query("SET @@SESSION.sql_mode='IGNORE_SPACE,NO_ENGINE_SUBSTITUTION'", { type: QueryTypes.UPDATE });

    const ret = await connection.promise().query("select @@SESSION.sql_mode", { type: QueryTypes.QUERY })
    logger('set sql_mode: %o', ret)
});

db.afterDisconnect( ()=>{
    logger('disconnect from db')
})
```
