### ISSUE TITLE
id in dataValues is null after create model (mssql) but does exist elsewhere

### ISSUE THREAD

**Issue by leetmachine** [sequelize/sequelize#11827]
### Issue Description
I use Model.create() to build and save a model instance. Why is  report.dataValues.id = null, when the report.id value is populated? 

I read multiple other issue spanning from 2014-2019. In those cases they mention:
1) make sure autoIncrement is set and spelled correctly. 
**- confirmed it is correct.**
2) make sure the field name is correctly the same as in the db. 
**- confirmed it is correctly named 'id'. With and without the field set. bonus: the id field is selectable when I query it and gives the correct record. My Issue seems to be isolated to the create call.**
3) omit defining id because sequelize does it for you by default. 
**-tried that with no success.**

### What are you doing?
```js
//model definition below in additions

const report = await Report.create({name: 'test'});

// will yield
report.dataValues.id === null;
report.id: === 43;

//bonus:
it also yields:
report.dataValues.name === 'test';
report.name === undefined; 
//for all fields defined on my model.
```

### What do you expect to happen?
I expect report.dataValues.id to have the same value as report.id so that I can 
1) easily return the created object including the output.id field
2) do other stuff with the model.

### What is actually happening?
console.log shown below. 
The dataValues.id is causing other usage of the model methods to break. for instance Model.reload will output the query with the WHERE claus  **IS NULL:**
```sql
SELECT [id], [name], [createdAt], [updatedAt] 
FROM [Reports] AS [ReportModel] 
WHERE [ReportModel].[id] IS NULL
 ORDER BY [ReportModel].[id] 
OFFSET 0 ROWS 
FETCH NEXT 1 ROWS ONLY;
```
here's the console.log of the model.create() output:
```js
report ReportModel {
  dataValues: {
    id: null,
    name: 'test',
    updatedAt: 2020-01-15T02:47:53.705Z,
    createdAt: 2020-01-15T02:47:53.705Z
  },
  _previousDataValues: {
    name: 'test',
    id: null,
    shortDescription: undefined,
    description: undefined,
    externalLink: undefined,
    createdAt: 2020-01-15T02:47:53.705Z,
    updatedAt: 2020-01-15T02:47:53.705Z
  },
  _changed: {
    name: false,
    id: false,
    createdAt: false,
    updatedAt: false
  },
  _modelOptions: {
    timestamps: true,
    validate: {},
    freezeTableName: false,
    underscored: false,
    paranoid: false,
    rejectOnEmpty: false,
    whereCollection: { id: null },
    schema: null,
    schemaDelimiter: '',
    defaultScope: {},
    scopes: {},
    indexes: [],
    name: { plural: 'ReportModels', singular: 'ReportModel' },
    omitNull: false,
    sequelize: Sequelize {
      options: [Object],
      config: [Object],
      dialect: [MssqlDialect],
      queryInterface: [QueryInterface],
      models: [Object],
      modelManager: [ModelManager],
      connectionManager: [ConnectionManager],
      importCache: {}
    },
    tableName: 'Reports',
    hooks: {}
  },
  _options: {
    isNewRecord: true,
    _schema: null,
    _schemaDelimiter: '',
    attributes: undefined,
    include: undefined,
    raw: undefined,
    silent: undefined
  },
  isNewRecord: false,
  id: 43,
  name: undefined,
  createdAt: undefined,
  updatedAt: undefined
}
```

### Additional context

Model defintion:
```js
//typescript stuff from the docs:
export default class ReportModel extends Model {
  public id!: number;
  public name!: string;

  // timestamps generated by sequelize
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  //model association declarations
}

  ReportModel.init(
    {
      id: {
          field: 'id',
          type: DataTypes.INTEGER,
          autoIncrement: true,
          primaryKey: true,
          allowNull: false,
      },
      name: {
        type: new DataTypes.STRING(64),
        allowNull: false,
      },
    },
    {
      sequelize,
      tableName: 'Reports',
    },
  );
```

CREATE TABLE statement:
```sql
CREATE TABLE Reports (
     id int IDENTITY(1,1) PRIMARY KEY,
     name varchar(64) not null,
     createdAt DATETIME2(7) not null,
     updatedAt DATETIME2(7) not null
 );
```

### Environment

- Sequelize version: 5.21.2
- Node.js version: 12.13
- Operating System: osx 10.15
- If TypeScript related: TypeScript version: 3.6

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using MSSQL, with TEDIUS version 6.6 and database version MSSQL 2014  12.0

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Very weird... Can you please convert the code you posted into a full [sequelize-sscce](https://github.com/papb/sequelize-sscce) so I can fix it? Thanks

**Comment by papb** [comment]
Also:

> I read multiple other issue spanning from 2014-2019

Can you please post links to them?

**Comment by SantiagoMinian** [comment]
We had the same issue using dialect mysql. 

```javascript
export default class ReportModel extends Model {
  // Removing this line solved the issue temporarily but left our types broken
  public id!: number;
  public name!: string;

  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}
```

In the end we solved it by removing `"@babel/plugin-proposal-class-properties" and adding `public id!: number;` back to our Model,` which seems to have been causing some sort of conflict. We got the solution from this comment: https://github.com/sequelize/sequelize/issues/11675#issuecomment-553783795

**Comment by Silly-V** [comment]
@SantiagoMinian I have been having this issue which started the moment I had included the `public id!: number;` in my class.
Since it was working fine before this, and given your clue here, I have switched my code to `export class MyClass extends Model implements IMyClass {...` where the interface has all the items except the `id`. I do not have the `"@babel/plugin-proposal-class-properties"` in my project anywhere that I can see though, but in any case I also had to resolve this issue by removing the `id` from the class.

**Comment by reduardo7** [comment]
> We had the same issue using dialect mysql.
> 
> ```js
> export default class ReportModel extends Model {
>   // Removing this line solved the issue temporarily but left our types broken
>   public id!: number;
>   public name!: string;
> 
>   public readonly createdAt!: Date;
>   public readonly updatedAt!: Date;
> }
> ```
> 
> In the end we solved it by removing `"@babel/plugin-proposal-class-properties"` and adding `public id!: number;` back to our Model, which seems to have been causing some sort of conflict. We got the solution from this comment: [#11675 (comment)](https://github.com/sequelize/sequelize/issues/11675#issuecomment-553783795)

Probably, related with https://github.com/sequelize/sequelize/issues/11675 - https://stackoverflow.com/a/69289067/717267
