### ISSUE TITLE
Don't select all fields by default

### ISSUE THREAD

**Issue by Nomanoclass** [sequelize/sequelize#11823]
### Is your feature request related to a problem? Please describe.
Currently, for example, when include a model and if don't set "attributes" property, the query retrieve all model fields.

### Describe the solution you'd like
Add a configuration (or set by default), to disable select all attributes by default.

### Why should this be in Sequelize
For now, isn't a viable security strategy.

### Describe alternatives/workarounds you've considered
= N.A. =

### Additional context
= N.A. =

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
This is already possible:

```js
(async () => {
    const sequelize = new Sequelize('sqlite::memory:', {
        define: {
            defaultScope: {
                // Assuming all your models have an `id`
                attributes: ['id']
            }
        }
    });
    const Foo = sequelize.define('foo', { bar: DataTypes.INTEGER });
    await sequelize.sync();
    await Foo.findAll(); // Will fetch only `id`
})();
```
