### ISSUE TITLE
AWS Certificate Authority 

### ISSUE THREAD

**Issue by scriptsure** [sequelize/sequelize#11839]
AWS is changing the certificate to connect to RDS. The deadline is March 5. Right now using the current certificate:

`rds-ca-2015`

My dialectOptions connection section looks like this:

  ```
  "dialectOptions": {
      "ssl": "Amazon RDS"
    },
```

This of course no longer works after I update the certificate on RDS to the latest certificate:

`rds-ca-2019`

I have installed the certificates to the local store on the ubuntu machine as required by AWS. 

Do I have to reference a .pem file directly? Or should this still work?

**Comment by papb** [comment]
Hello... I don't know, have you tried stackoverflow as well? If not please ask there and link to this issue. Also if you figure it out please let us know.

**Comment by NickKellett** [comment]
In case it's related - there is an open issue at https://github.com/mysqljs/mysql/issues/2288 suggesting that module's ssl_profiles.js file may need to be updated with the RDS 2019 and 2015 combined certificates. It's that profile that loads when "Amazon RDS" string is referenced, so I guess (but haven't been able to prove) that if it doesn't include the new certificates it won't validate the SSL connection.

**Comment by scriptsure** [comment]
@NickKellett will that update also be applied to version 3.30.4?

**Comment by sushantdhiman** [comment]
Updating dialect library should be enough, SSL setup is handled by dialect libraries directly.

**Comment by papb** [comment]
Nice, I will close this then, if the problem persists after the dialect library is updated, please let us know

**Comment by scriptsure** [comment]
@papb this issue still exists after i updated the mysql client... any ideas?

**Comment by charlie-s** [comment]
It looks like mysql2 supports the new certificate in their 2.x release, but not in 1.x (https://github.com/sidorares/node-mysql2/issues/1117). Following up in that issue.
