### ISSUE TITLE
findAll returns nothing while generated MySQL returns multiple.

### ISSUE THREAD

**Issue by robstev0** [sequelize/sequelize#11846]
This is a very strange problem that I have been trying to hunt down for a few days now and have been all over the internet.

The following code returns no records (incorrect).  If I copy and paste the raw sequelize generated MySQL and paste it into the database console, I get 20 records (correct).  I would like to know what could possibly be contributing to this sort of error.  If I change the where clause to a different value or different column then it works as expected.  The error only happens for a few specific values with this specific column.

```js
return models.Examination.findAll({
    include:[
        {
            model: models.Event,
            where: {
                sample_id: 23
            }
        }
    ]
});
```

I can verify that all 20 records returned by the console do in fact have a valid sample_id of 23 so there is nothing strange going on there.  As I mentioned earlier, the raw sequelize output works fine, but the value returned by 'findAll' is incorrect.

**Comment by robstev0** [comment]
https://github.com/sequelize/sequelize/issues/7667

**Comment by robstev0** [comment]
Another example of the issue:

```
   models.Examination.findAndCountAll({
        include: [
            {
                model: models.Event,
                where: {
                    track_id: {
                        [sequelize.Op.in]: [21, 22, 23, 24, 25, 26]
                    }
                }
            }
        ]
    }).then(result => {
        console.log(result);
        res.status(200).json(result);
    }).catch(error => {
        res.sendStatus(500);
        logger.error(error);
    });
```

Returns:

`{ count: 0, rows: [] }`


The generated MySQL:

`SELECT count(`Examination`.`id`) AS `count` FROM `examinations` AS `Examination` INNER JOIN `events` AS `Event` ON `Examination`.`event_id` = `Event`.`id` AND `Event`.`track_id` IN (21, 22, 23, 24, 25, 26);`

Returns:

**Count
>303**

**Comment by papb** [comment]
Hi, thanks for the report. If I understand correctly:

* Sequelize is generating the correct SQL
* When you run the generated SQL manually, it works
* However in Sequelize it doesn't work

Am I right? If yes that is very odd indeed... Try to create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) for it...

**Comment by robstev0** [comment]
After disabling the 'sync()' command during sequelize startup and restarting MySQL workbench, this problem has now resolved itself completely which raises even more questions.  Why would either of these two factors have anything to do with sequelize returning the correct result?  This seems like some kind of stability or state-based issue.

**Comment by papb** [comment]
Hmmm, that is weird. Happy to hear the problem is gone though!

**Comment by EMANSO** [comment]
Hello. We are experimenting the same issue. Disabling sync() does not solve it. Any clue of what else it could be?

**Comment by djordjelacmanovic** [comment]
I ran into exactly the same issue, on Postgres 9.6 (though I'm sure it's an issue with sequelize).

e.g.

```javascript
// this returns correct results
await models.Product.findAll({
  ... some query stuff...
  include: [
    { model: models.Category, ...some filters }, // belongsTo
    { model: models.Review }, // hasMany
  ]
}

// this returns []

await models.Product.findAll({
  ... some query stuff...
  include: [
    { model: models.Category, ...some filters }, // belongsTo
    { model: models.Review }, // hasMany
    { model: models.Channel } // belongsTo
  ]
}
```

if I remove the last eager load the data is returned. I'm able to call `product.getChannel()` on each returned product and get the Channel, so I think the associations are registered correctly. If I run the generated SQL myself I also get the correct results. Seems like whatever sequelize is doing to hydrate the models is what is causing this hiccup.

**Comment by aabhaskarma** [comment]
Did anyone found any solution or workaround?

**Comment by TannerS** [comment]
same issue here...

**Comment by Buckits** [comment]
I experienced this exact same issue..generated SQL was correct and returned results, but sequelize was returning empty results. 

In my case it was the limit option on the main table i was searching on that was causing the issue. By removing it everything started working as normal. My included tables did not have limit but did have where clauses.

**Comment by rsshilli** [comment]
I created a little video to explain why `separate: true` is helpful in making this work. https://www.loom.com/share/33bea5a0111a4b54913deb51506c6622
