### ISSUE TITLE
Feature request: Expose the connection pool via the Sequelize object

### ISSUE THREAD

**Issue by dberke711** [sequelize/sequelize#11841]
I would like to access the various properties available on the connection pool object (size, available, using, waiting, etc.) but currently this isn't possible as it's not exposed through any public interface.

I propose adding a new property to the Sequelize object - ConnectionPool - that exposes the pool object so that we can access its properties.

In my case, I want to monitor how many requests are waiting for a database connection to become available.  This metric could be used to scale out resources when the average number of waiting queries hits some threshold.

This can be accomplished by a single addition to the Sequelize constructor:
```
...
this.modelManager = new ModelManager(this);
this.connectionManager = this.dialect.connectionManager;

Sequelize.ConnectionPool = this.connectionManager.pool;    // Expose connection pool
...
```

Does this sound like a reasonable addition?

Thanks!
DB

**Comment by papb** [comment]
Hello!`Can't you just use `sequelize.connectionManager.pool`? Example

```js
const sequelize = new Sequelize({ /* ... */ });
const ConnectionPool = sequelize.connectionManager.pool;
```

This is [present in our TypeScript typings](https://github.com/sequelize/sequelize/blob/365d7c35eb9badf42d0e45513338194fb1c549be/types/lib/sequelize.d.ts#L796) so I consider that public.

I will close the issue but if you think this does not fit your needs let me know and I will reopen.

**Comment by dberke711** [comment]
I don't know how I missed that... I even pasted the line in my suggested change!

Switching to use sequelize.connectionManager.pool worked fine for my needs, thanks!
