### ISSUE TITLE
404 broken link on documentation v5

### ISSUE THREAD

**Issue by mrdulin** [sequelize/sequelize#11854]
### What was unclear/insufficient/not covered in the documentation

The link is broken for the section of https://sequelize.org/v5/manual/models-definition.html#defining-as-part-of-the-model-options 

When I click the `VIRTUAL datatype.` link

Broken link(404) is: https://sequelize.org/variable/index.html#static-variable-DataTypes

### If possible: Provide some suggestion on how we can enhance the docs

Fix the broken link.

### Additional context

No

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
This has been fixed in the v6 docs, please use it instead for now.

**Comment by papb** [comment]
@sushantdhiman perhaps I should backport my manual changes to v5? what do you think?

**Comment by mrdulin** [comment]
@papb I am using sequelize v5. `"sequelize": "^5.21.3"`. Does documentation for v6 also apply to v5?

**Comment by sushantdhiman** [comment]
> perhaps I should backport my manual changes to v5? what do you think?

I don't think we should rewrite docs for v5. We can fix this broken though.

**Comment by papb** [comment]
@mrdulin most of it does. I suggest using v5 docs and checking the v6 breaking changes to be aware of the most important differences.

**Comment by ephys** [comment]
The broken link has been fixed
