### ISSUE TITLE
Default query with set timezone

### ISSUE THREAD

**Issue by mtryba** [sequelize/sequelize#11857]
## Issue Description
Hello, I have question about the query:

`SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE;`

When I executing query `select query from pg_stat_activity` I often see this query before executing my queries. I would like to disable the query. My columns have a timestamp with timezone but my default timezone is UTC. What can I do to remove it? Does it affect performance?

**Comment by sanketCactus** [comment]
@mtryba did you find resolution for this?

Thank you.

**Comment by safilsunny** [comment]
how did you resolved this issue ?

**Comment by MikeNitsenko** [comment]
@mtryba hello, could you please share if this additional query can be disabled/removed?

**Comment by gokulk16** [comment]
if you pass `clientMinMessages: false,` in the options as mentioned here. 
https://github.com/sequelize/sequelize/blob/fbd19d986170ad1edeeba123a0730854824aa515/lib/dialects/postgres/connection-manager.js#L206

you should be able to disable these queries.
