### ISSUE TITLE
unclear documentation for the types of options

### ISSUE THREAD

**Issue by mrdulin** [sequelize/sequelize#11856]
## Issue Description

The TS types of  the `options` argument for many APIs are just JS `Object` with an MDN doc link:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object.

It's not useful for developers. We want to know more detail of the options, not just a JS `Object`. A more specific interface is required, including an explanation for each attribute

### What was unclear/insufficient/not covered in the documentation

Doc link(Not just this one): https://sequelize.org/v5/class/lib/model.js~Model.html

For example, the `build()` static method of Model on the documentation like this:

> build(values: Object | Array, options: Object): Model | Array<Model> 
   Builds a new model instance.

The `options` argument has an `Object` type, but we want to know its properties.

### If possible: Provide some suggestion on how we can enhance the docs

I find the TS type definition (`model.d.ts`) of `sequelize` v5 and comments for the `build()` static method of Model. It's better than the documentation. 

E.g.

```ts
  /**
   * Builds a new model instance. Values is an object of key value pairs, must be defined but can be empty.
   */
  public static build<M extends Model>(
    this: { new (): M } & typeof Model,
    record?: object,
    options?: BuildOptions
  ): M;
```

```ts
/**
 * Options for Model.build method
 */
export interface BuildOptions {
  /**
   * If set to true, values will ignore field and virtual setters.
   */
  raw?: boolean;

  /**
   * Is this record new
   */
  isNewRecord?: boolean;

  /**
   * an array of include options - Used to build prefetched/included model instances. See `set`
   *
   * TODO: See set
   */
  include?: Includeable[];
}
```

After checking the type definition and comments, so I can figure out what properties of the `options` are there. But this information should be added to the documentation, right?  Or, do I miss anything about how to read the documentation?

### Additional context

`"sequelize": "^5.21.3"`

The reason why I found this issue is I try to find the documentation about the `includeOptions` and the `Association`. 

```ts
/**
 * Options for eager-loading associated models, also allowing for all associations to be loaded at once
 */
export type Includeable = typeof Model | Association | IncludeOptions | { all: true } | string;
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Thanks for the report, this is indeed something that deserves improvement.
