### ISSUE TITLE
Sqlite: using `attributes: []` produces broken select statement

### ISSUE THREAD

**Issue by eridal** [sequelize/sequelize#11858]
## Issue Description

The following code will generate an invalid sql statement when running against an sqlite database

```js
const found = await Foo.findOne({
  attributes: [],
})
```

The generated sql is something like: 

```sql
SELECT  FROM "database"."table"
```

A common workaround is adding a fixed result column, like `SELECT 1 FROM ...`, although I'm not sure how that will play with the next step, when the records are parsed.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): SQLITE
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Actually this happens with all dialects except postgres
