### ISSUE TITLE
Sequelize returns a string for decimal types from postgres

### ISSUE THREAD

**Issue by FredSoares** [sequelize/sequelize#11855]
## It's returning strings for my decimal data types
I have a model with a DECIMAL column. Whenever I query that model the column is returned as a string.
### When i try to get data from my postgres DB

```js
app.get('/itens', function(req, res) {
	models.itens.findAll().then(function(itens) {
		res.json(itens);
	});
});
```

### The return always is a String value

```
{
	"price": "196",
}
```

### I am using

- Sequelize version: 5.21.2
- Node.js version: 10.15.3
- Operating System: mac Os

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect:
- [x] I don't know, I was using postgres, with connector library version 7.12.1 and database version 12

**Comment by papb** [comment]
I think this is already known behavior, see [here](https://github.com/sequelize/sequelize/issues/4870#issuecomment-157311158). Also related: #11840

This should be better documented though.

For now if you want to lose precision and get a Number you can define a [custom getter](https://sequelize.org/master/manual/getters-setters-virtuals.html#getters) on that field to perform the type conversion via javascript

**Comment by white-stallion** [comment]
I am having similar issues too, with a column type of DECIMAL.UNSIGNED.

**Comment by murilokrugner** [comment]
same here!!

**Comment by hcurnor** [comment]
### Suggested workaround

```
sequelize.define("user", {
  foo: {
    type: Sequelize.DECIMAL,
    get() {
      // Workaround until sequelize issue #8019 is fixed
      const value = this.getDataValue('foo');
      return value === null ? null : parseFloat(value);
    }
  }
})

```

**Comment by ephys** [comment]
This is the expected behavior for `decimal`, you should use `float` or `double` if you want to use the `number` type in javascript

Nonetheless, https://github.com/sequelize/sequelize/issues/14296 proposes a way to return `number` out of the box

I'll close as this issue in favor of https://github.com/sequelize/sequelize/issues/8019

**Comment by leandroluk** [comment]
I have a simple solution to fix that problem. In our sequelize instace file add this:

```js
const { Sequelize } = require('sequelize');
Sequelize.DataTypes.postgres.DECIMAL.parse = parseFloat;
const sequelize = new Sequelize(/* ... */);
```

```ts
import { Sequelize } from 'sequelize';
(Sequelize as any).DataTypes.postgres.DECIMAL.parse = parseFloat;
const sequelize = new Sequelize(/* ... */);
```

**Comment by ephys** [comment]
Be aware that this workaround will stop working in sequelize 7, as it's using an internal API that has been rewritten. You'll need to update it to use the public API (see our guide on custom data types in the documentation of sequelize 7)
