### ISSUE TITLE
Didn't find docs about `queryInterface.sequelize.query` API.

### ISSUE THREAD

**Issue by mrdulin** [sequelize/sequelize#11860]
## Issue Description

I generate the seed file like this:
```js
'use strict';

const faker = require('faker');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Language', [
      { ID: 1, Name: faker.random.locale(), Last_Update: Sequelize.fn('NOW') },
      { ID: 2, Name: faker.random.locale(), Last_Update: Sequelize.fn('NOW') },
      { ID: 3, Name: faker.random.locale(), Last_Update: Sequelize.fn('NOW') },
    ]);

    const languages = await queryInterface.sequelize.query(`select * from "Language";`);
    console.log(languages);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Language', null, {});
  },
};
```
I say people use `queryInterface.sequelize.query` to execute the raw SQL query.
But didn't find the explanation about this on the documentation. Actually, I didn't find this API.

### What was unclear/insufficient/not covered in the documentation

I read this doc: https://sequelize.org/master/class/lib/query-interface.js~QueryInterface.html

But didn't find any information about `queryInterface.sequelize.query`.

### If possible: Provide some suggestion on how we can enhance the docs

Add docs for `queryInterface.sequelize.query` API.

### Additional context

I found this API according to this post: https://stackoverflow.com/a/48753999/6463558

```json
"sequelize": "^5.21.3",
"sequelize-cli": "^5.5.1"
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
The fact that `queryInterface` has a `sequelize` field seems undocumented indeed; I am not sure if this is intentional or not. This `sequelize` field is simply a normal Sequelize instance, so the API you're looking for is [here](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-query).

Thanks for the report.
