### ISSUE TITLE
bulkCreate ignores id field if autoIncrement is true

### ISSUE THREAD

**Issue by richardleggett** [sequelize/sequelize#1186]
This may just be by design so forgive me if so, but when prepopulating a database with some "seed data" for testing I'm noticing that the id column values are ignored (even when "id" is passed in options.fields).

So something like this:

```
var records = [
  ...
  {id:12, name:'Test', url:'http://lorempixel.com/g/100/100/' }
  {id:13, name:'Test', url:'http://lorempixel.com/g/100/100/' }
];
Records.bulkCreate(records, null, {validate: true});
```

`bulkCreate()` ignores the values for "id", but `create()` does not - using the latter I get the correct IDs in the DB.

Ignoring for the moment why I need fixed pre-populated IDs at all when we have autoIncrement(!) I'm wondering if this is a problem, or an intentional difference between `create()` and `bulkCreate()`?

*When inserting records with hardcoded IDs there's a little bit of code which updates the auto-increment sequence `nextval()` below to make sure we don't get conflicts thereafter:

```
function resequenceTable(tableName) {
    var RESEQUENCE_TABLES_SQL = "SELECT setval('TABLENAME_id_seq', (SELECT MAX(id) FROM TABLENAME));";
    return sequelize.query(RESEQUENCE_TABLES_SQL.replace(/TABLENAME/g, tableName), null, {raw: true});
}
```

**Comment by Bayra1** [comment]
i had the same problem here:
