### ISSUE TITLE
TypeScript 3.7 property declaration conflict

### ISSUE THREAD

**Issue by ElijahKaftanov** [sequelize/sequelize#11863]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

> The two biggest changes are the following:
> Declarations are initialized with Object.defineProperty.
> Declarations are always initialized to undefined, even if they have no initializer.

The second change is breaking for sequelize model type declaration, at least how it offers in [documentation](https://sequelize.org/v5/manual/typescript.html). Is there any other workaround for v5 and what actions are being taken for this for the next releases? Thanks

**Comment by papb** [comment]
Thanks for the report, @SimonSchick what do you think of this?

**Comment by ephys** [comment]
It is now recommended to use `define` on attributes: https://sequelize.org/docs/v6/other-topics/typescript/
