### ISSUE TITLE
Cannot find how to query model where association is null in the docs

### ISSUE THREAD

**Issue by Ccastillo06** [sequelize/sequelize#11873]
### How to exclude the associations inside an include?

Hello everyone, I've been trying for really long to query for a model where its associations are null, but cannot find it in the docs o solve it anyway with the query.
As I'm paginating the results, I'm offsetting and limiting the query result, so I really need to get the models where I have no associations in the form of an array.

Example snippet:

```
const words = await models.Word.findAll({
  order: [['id', 'ASC']],
  limit: 20,
  offset,
  include: [
    {
      model: models.Synonym,
      attributes: ['id', 'name'],
    },
  ],
  // I've tried so many things here so I don't really know what else to try out
  where: {
    $Word.Synonyms$: null,
  }
});
```

Using this query (and many other variations...) I tried to bring all the words where synonyms was null instead of an array, but couldn't get to do that and had to do it with code after the query, but it breaks the pagination.

In my case the models are related this way:

```
models.Word.hasMany(models.Synonym);
models.Synonym.belongsTo(models.Word);
```

Thank you so much in advance, hope someone had solved this problem before. Would be great to have it in the docs with an example (I'm up to writing it and opening a PR if I get the problem solved).

**Comment by andres112013** [comment]
**Good day**

Try to make your query like this

```typescript
import { Op } from "sequelize";
const words = await models.Word.findAll({
  order: [["id", "ASC"]],
  limit: 20,
  offset,
  include: [
    {
      model: models.Synonym,
      attributes: ["id", "name"]
    }
  ],
  //  When you need to condition the associations, use Sequelize.where
  where: Sequelize.where(Sequelize.col(`word.synonymId`), Op.is, null)
});
```
**I hope it works for you**

**Comment by luqimin** [comment]
> **Good day**
> 
> Try to make your query like this
> 
> ```ts
> import { Op } from "sequelize";
> const words = await models.Word.findAll({
>   order: [["id", "ASC"]],
>   limit: 20,
>   offset,
>   include: [
>     {
>       model: models.Synonym,
>       attributes: ["id", "name"]
>     }
>   ],
>   //  When you need to condition the associations, use Sequelize.where
>   where: Sequelize.where(Sequelize.col(`word.synonymId`), Op.is, null)
> });
> ```
> 
> **I hope it works for you**

Sry, I'm suffering the same problem, but I have many different relation types inside a model, this method faileds, did you have any other solutions?

**Comment by andres112013** [comment]
Hi luqimin

Try to make your query like this

```typescript
import { Op } from "sequelize";
const words = await models.Word.findAll({
  ...
  where: Sequelize.and(
    Sequelize.where(Sequelize.col(`...`), Op.is, null),
    Sequelize.where(Sequelize.col(`...`), Op.is, null),
    ...
  )
});
```

**Comment by luqimin** [comment]
Thank you @andres112013 , I solved it by param `subQuery: false`

**Comment by KhudoleyS2** [comment]
Thank you so much @luqimin

**Comment by ankitshubham97** [comment]
This worked for me:

```
const comments = await this.replyRepository.findAll({
      where: {
        replyText: {[Op.is]: undefined}
      }
    });
```
