### ISSUE TITLE
Sequelize.Op is undefined in version 3.29 and version 4.0.0

### ISSUE THREAD

**Issue by bwoodlt** [sequelize/sequelize#11883]
## Issue Description
When using `Sequelize.Op`, this returns undefined the above versions. Our database still uses version 3.29.1. When we attempted to upgrade to version 5, all our models returned errors hence the need to stay on 3.29.1 before we have time to properly migrate.

## What are you doing?
I'm trying to use the `Operator` from Sequelize by doing 
```const Op = Sequelize.Op```. 

Op returns `undefined` each time

### What do you expect to happen?
I wanted to have access to the `Operators` e.g `$gt` $lt$` e.t.c when I call `Sequelize.Op`

### What is actually happening?
The output is `undefined`

### Environment

- Sequelize version: 3.29.1 
- Node.js version: 10.x 
- Operating System: MacOS

### How does this problem relate to dialects?

- [ ] I don't know, I was using postgres, with connector library version 3.29 and database version 6

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by sushantdhiman** [comment]
Operators were introduced in Sequelize >= `4.12.0`. So they won't be available in lower versions.
