### ISSUE TITLE
bulkCreate with associate and individualhooks:true 

### ISSUE THREAD

**Issue by nechama** [sequelize/sequelize#11886]
bulkCreate with associate and individualhooks:true try to create the associate row twice(or multiple) and throw duplicatekey error

User.bulkCreate(users, {
        individualhooks:true,
        include: [{
            model: Project
        }]
    });

And in User model:
hooks:{
  afterCreate:(instance,options) {
  }
}

Users shuld be created with their project for each one  and to do the code in afterCreate hook for each created user.

But actually:

The user created successfuly, then the project created. and after it, the afterCreate hook done,
Then It try again to create project and fail with sequelize duplicatekey error.

Sequelize version: 5.21.3
Node.js version: v10.17.0
Operating System: Linux

**Comment by jozekcore** [comment]
same happens to me

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
