### ISSUE TITLE
Hooks don't work with paranoid table

### ISSUE THREAD

**Issue by adsellor** [sequelize/sequelize#11898]
## Issue Description
As said in the title, the hooks are not working for `paranoid` tables. I've had the implementation for regular tables, and hooks were called as expected. However, after switching to `paranoid` tables to persist the data, the hooks are not being called.

### What are you doing?

Here is the code 
```js
module.exports = (sequelize, DataTypes) => {
  const task = sequelize.define(
    'task',
    {
      name: DataTypes.STRING,
      days: {
        type: DataTypes.STRING,
        defaultValue: '1,2,3,4,5,6,7'
      },
      hasDecendants: DataTypes.BOOLEAN,
      isActive: { type: DataTypes.BOOLEAN, defaultValue: true },
      pos: {
        type: DataTypes.FLOAT,
        defaultValue: 0.25
      }
    },
    {
      paranoid: true
    },
    {
      hooks: {
        beforeUpdate: _ => {
           console.log("Task was updated")
        },
        afterDestroy: async task => {
          const { id } = task.dataValues
          await sequelize.models.subTask.destroy({
            where: {
              taskId: id
            }
          })
          await sequelize.models.taskDetails.destroy({
            where: {
              taskId: id
            }
          })
        }
      }
    }
  )
  task.associate = models => {
    models.task.hasMany(models.subTask, {
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
      hooks: true,
      paranoid: true
    })
    models.task.hasOne(models.order)
    models.task.hasMany(models.taskDetails)
    models.task.belongsTo(models.template, {
      onDelete: 'CASCADE',
      hooks: true,
      paranoid: true,
      foreignKey: {
        allowNull: false
      }
    })
  }
  return task
```

### What do you expect to happen/What is actually happening?
When I call `Task.destroy()`, or `Task.update()` the hooks should work. However, with `paranoid: true`, they are not being called

### Environment

- Sequelize version: 5.1.1
- Node.js version: 10
- Operating System: MacOS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using `postgres`, with connector library version `pg: 7.9.0` and daabase version 9.4
### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Bezoyan** [comment]
I have the same issue while working with paranoid tables

**Comment by adsellor** [comment]
Ok, this was a mistake from our side, I apologize.

**Comment by Talbot3** [comment]
> Ok, this was a mistake from our side, I apologize.
i have same problem.

**Comment by kysen** [comment]
Yeah how did you resolve it? @adsellor

**Comment by rabrowne85** [comment]
I'm going to leave this here in case anyone else comes looking for a possible answer.

The trick appears to be to include the option: `individualHooks: true,` if you're doing a 'bulkDestroy' as follows:

```js
db.ModelName.destroy({
    where: {
        id: id,
    },
    individualHooks: true,
});
```
