### ISSUE TITLE
The following leaks were detected:@@any-promise/REGISTRATION

### ISSUE THREAD

**Issue by mahnunchik** [sequelize/sequelize#11899]
## Issue Description

The following leaks were detected:@@any-promise/REGISTRATION

```
└─┬ sequelize@5.21.3
  └─┬ retry-as-promised@3.2.0
    └── any-promise@1.3.0 
```

### What do you expect to happen?

No any leaks =)

### Environment

- Sequelize version: 5.21.3
- Node.js version: v12.14.1
- Operating System: macOS 10.15.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Did you registered any promise version? ``retry-as-promise`` will need to support native promises for newer node versions and remove `any-promise`

**Comment by SalathielGenese** [comment]
I have been seeing in my tests from this morning... Since I am playing around with Hapi.js `@hapi/lab`, I have been thinking the error was from that new library to me.

Seeing this issue, I tried `yarn lab --dry` and (1) it skips all my tests (2) but the error is still poisoning my tests exist status - not good for Continuous Deployment.

Now, I don't know how you connected this to sequelize b/c I just removed every direct and transitive call to anything-sequelize from my tests and I still have the error.

- - -
Here's what else I have

**package.json**
```json
  "devDependencies": {
    "@hapi/code": "^8.0.1",
    "@hapi/lab": "^22.0.4",
    "nodemon": "^2.0.2",
    "sequelize-cli": "^5.5.1",
    "uuid": "^7.0.2",
    "yarpm": "^0.2.1"
  },
  "dependencies": {
    "@hapi/hapi": "^19.1.1",
    "debug": "^4.1.1",
    "env-cmd": "^10.1.0",
    "find": "^0.3.0",
    "pg": "^7.18.2",
    "pg-hstore": "^2.3.3",
    "sequelize": "^5.21.5"
  }
```

`$ yarn why any-promise`
```plain
yarn why v1.22.0
[1/4] Why do we have the module "any-promise"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "any-promise@1.3.0"
info Reasons this module exists
   - "sequelize#retry-as-promised" depends on it
   - Hoisted from "sequelize#retry-as-promised#any-promise"
info Disk size without dependencies: "148KB"
info Disk size with unique dependencies: "148KB"
info Disk size with transitive dependencies: "148KB"
info Number of shared dependencies: 0
Done in 0.28s.
```

**Comment by unlimittt** [comment]
Use `lab --leaks` to avoid this message
