### ISSUE TITLE
Mysql SequelizeDatabaseError: write EPIPE at Query.formatError

### ISSUE THREAD

**Issue by jhapankaj4u** [sequelize/sequelize#11897]
I am getting following error  on saving or selecting in mysql

SequelizeDatabaseError: write EPIPE at Query.formatError (/var/www/worldadmins-api/node_modules/sequelize/lib/dialects/mysql/query.js:247:16) at Query.handler [as onResult] 

(/var/www/worldadmins-api/node_modules/sequelize/lib/dialects/mysql/query.js:68:23) at Connection._notifyError (/var/www/worldadmins-api/node_modules/mysql2/lib/connection.js:190:21) at Connection._handleFatalError (/var/www/worldadmins-api/node_modules/mysql2/lib/connection.js:153:10) at Connection._handleNetworkError (/var/www/worldadmins-api/node_modules/mysql2/lib/connection.js:162:10) at stream.write.err (/var/www/worldadmins-api/node_modules/mysql2/lib/connection.js:223:14) at onwriteError (_stream_writable.js:434:5) at onwrite (_stream_writable.js:461:5) at _destroy (internal/streams/destroy.js:49:7) at Socket._destroy (net.js:613:3) at Socket.destroy (internal/streams/destroy.js:37:8) at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
