### ISSUE TITLE
coun() and Distinct = syntax error

### ISSUE THREAD

**Issue by AuHau** [sequelize/sequelize#11894]
### What are you doing?

Using `count()` and `distinct: true` option. 
Not directly but through [feathers-sequalize](https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/index.js#L131). 

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/43

### What do you expect to happen?

Count returned

### What is actually happening?

SQL generaged:
```
SELECT count(DISTINCT(*)) AS `count` FROM `StorageOffers` AS `StorageOffer`;
```

Error returned:
```
SQLITE_ERROR: near \"*\": syntax error
```

### Environment

- Sequelize version: sequelize@5.21.3 
- Node.js version: v12.9.0 
- Operating System: macos
- If TypeScript related: TypeScript version: 3.7.5

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using SQLite, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by TimMensch** [comment]
Good timing! I just submitted a PR for this: #11893

I'm using Feathers-Sequelize and ran into the same problem. 

It also fails in PostgreSQL, and looking at other (closed and ignored?!) bug reports, in MySQL as well.

Sequelize just shouldn't generate invalid SQL given reasonable parameters. There _is_ a workaround, but the real fix is absolutely brain-dead trivial, so in my opinion should be an easy merge decision. 

The workaround, for what it's worth, is to set `sequelize.col = Model.primaryKeyAttributes` in a before hook. Here's what my Feathers-Sequelize code looks like (though with TypeScript):

```typescript
export function fixCount(ThisModel: typeof Model) {
    return (context: HookContext) => {
        const sequelize = context.params.sequelize || {};
        context.params.sequelize = sequelize;

        sequelize.col = ThisModel.primaryKeyAttributes;
    };
}
```

And you'd use this like so:

```typescript
const hooks = {
    before: {
        find: [fixCount(MyModel)],
    }
}
```

...where MyModel is the model you created from Sequelize. 

But maintainers, please, please, apply the PR to fix Sequelize v5 (and pull that change to v6 -- it's really brain-dead simple).
