### ISSUE TITLE
Max Size in Connection Pooling in Sequelize

### ISSUE THREAD

**Issue by UrvashiCapillaryTech** [sequelize/sequelize#11895]
## Issue Description

According to my understanding the "max:" in pool shows the max number of connection we can create. So if I set the value of max as 0. Then it should not established any connection. But then also the connection gets created. Please correct me if I am wrong.

`var sequelize = new Sequelize(
    process.env.DATABASE_NAME,
    process.env.DATABASE_USERNAME,
    process.env.DATABASE_PASSWORD, {
        pool:{
                 max: 0,
                 min: 0,
                 idle: 10000,
                 acquire:30000
             },
        logging: console.log("connection created"),
        host: process.env.DATABASE_HOST,
        dialect: 'mysql',
        operatorsAliases: false
    }
);`

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
