### ISSUE TITLE
Validate functions should not be run on null fields

### ISSUE THREAD

**Issue by broofa** [sequelize/sequelize#11890]
## Issue Description

The sequelize documentation [says](https://sequelize.org/v5/manual/models-definition.html#per-attribute-validators-and--code-allownull--code-) the following:

> If a particular field of a model is set to allow null (with allowNull: true) and that value has been set to null , its validators do not run. 

This does not appear to be the case.

### What are you doing?

Creating a model with custom validation function(s) on a column that has a default value of null.

**Here is the link to the SSCCE for this issue:** https://gist.github.com/broofa/2d85e249d219406e54ab14b3c8f4f36c

### What do you expect to happen?

Running the SSCCE above should exit normally.

### What is actually happening?

It throws inside the custom validation function

```
kieffer$ node sequelize_validate_issue.js
Executing (default): CREATE TABLE things (id INTEGER PRIMARY KEY, aColumn TEXT DEFAULT NULL)
Unhandled rejection SequelizeValidationError: Validation error: This should not run!
... etc.
```

### Additional context

Note that while the above SSCCE does not explicitly set `defaultValue: null` on the schema or pass `aColumn: null` when creating the model instance, neither of these actions should be necessary, and doing so does not change the behavior of Sequelize.

### Environment

- Sequelize version: sequelize@5.21.2
- Node.js version: v12.10.0
- Operating System: MacOSX

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
You are linking to way older docs for v2 version. This behavior was changed in v5 https://sequelize.org/v5/manual/models-definition.html#per-attribute-validators-and--code-allownull--code-

As dev define custom validator themselves, they can skip `null` or empty values in that code to make this work.

**Comment by broofa** [comment]
I'm confused.

**Comment by broofa** [comment]
Ah, my bad.  Did not notice that I landed on old docs there.
