### ISSUE TITLE
Custom schema indexes error

### ISSUE THREAD

**Issue by wdh-1025** [sequelize/sequelize#11908]
```
Example:
const model = sequelize.define('test', { a: {type: Sequelize.STRING}, b : {type: Sequelize.STRING} }, { indexes:[{ unique: true, fields: ['a','b'] }] })
model.sync({ schema:"myschema" })

Execute results:
CREATE UNIQUE INDEX "test_a_b" ON "test" ("a",b")

Expect execution:
CREATE UNIQUE INDEX "test_a_b" ON "myschema"."test" ("a",b")
```

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
