### ISSUE TITLE
sequelize nested include result set parent object

### ISSUE THREAD

**Issue by Chiragsorathiya** [sequelize/sequelize#11900]
I have multiple includes in the single query of sequelize but I can't get the result as I want. please refer below code

```
const users = await User.findAll({
  include: {
    model: Tool,
    as: 'Instruments',
    include: {
      model: Teacher,
      include: [ /* etc */ ]
    }
  }
});
```

output:

```
[{
  "name": "John Doe",
  "id": 1,
  "Instruments": [{ 
    "name": "Scissor",
    "id": 1,
    "userId": 1,
    "Teacher": { 
      "name": "Jimi Hendrix"
    }
  }]
}]
```

now I want output like

```
[{
      "name": "John Doe",
      "id": 1,
      "Instruments": { 
        "name": "Scissor",
        "id": 1,
        "userId": 1
      },
      "Teacher": { 
        "name": "Jimi Hendrix"
      }
    }]
```

It's possible if yes then how ??

**Comment by sushantdhiman** [comment]
It looks like `User` has many `Instruments` and each `Instrument` is has one `Teacher`.

You can either choose to modify those relationships OR parse this data to format you want with something like `lodash` or modern ES setup etc

**Comment by kamal0808** [comment]
@sushantdhiman If the SQL result is a table, and Sequelize is nesting relationships in JSON through dottie.js, shouldn't there be a way to bypass JSON nesting, or may be to provide a way to define the skeleton of required JSON?
Parsing through nested objects and arrays every time is just redundant and increases code complexity.
