### ISSUE TITLE
Postgres RETURNING: options.returning [fields] doesn't have effect

### ISSUE THREAD

**Issue by mahnunchik** [sequelize/sequelize#11904]
## Issue Description

`options.returning` [fields] doesn't have any effect. All columns are returned.

### What are you doing?

```js
const item = await Item.create({
  foo: 'foo',
  bar: 'bar',
  baz: 'baz',
}, {
  returning: ['foo'],
});
```

### What do you expect to happen?

Item is:
```js
{
  foo: 'foo',
}
```

### What is actually happening?

Item is:
```js
{
  id: 123,
  foo: 'foo',
  bar: 'bar',
  baz: 'baz',
}
```

### Environment

- Sequelize version: 6.0.0-beta.4 (supports array in returning)
- Node.js version: v12.14.1
- Operating System: macOS 10.15.3
- If TypeScript related: TypeScript version: no
- Postgres version: 12

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by rdsedmundo** [comment]
Same here, but using 5.21.11 instead.

I'm passing an array of columns but the query getting executed has a `RETURNING *` instead.

**Comment by Romick2005** [comment]
We hane the opposite behaviour on postgres. When we used returning: true on model update then we got sql:

**Comment by Romick2005** [comment]
Finally discovered the root of the issue.
It seems that hasMany automaticaly add new attribute on the users model, but this relation was in timezones model.
```
  time_zone.associate = function (models) {
    time_zone.hasMany(models.users, {
      foreignKey: "time_zone_name",
      targetKey: "name"
    });
  };
```

**Comment by JacobSiegle** [comment]
> Same here, but using 5.21.11 instead.
> 
> I'm passing an array of columns but the query getting executed has a `RETURNING *` instead.

You need to use a v6 version of sequelize to be able to use custom returning. Unfortunately if you use custom col names the feature is broken. It will map the col names directly as given not mask them.

```
            _id: {
                type: DataTypes.INTEGER,
                field: 'id',
                autoIncrement: true
            },
```
Results in

`RETURNING "_id"`

**Comment by pashka4281** [comment]
> It's not a bug, this is how we designed returning to work. It's used to update data on the model by returning values from the database after insertion, but it's not going to delete data that is already available on it

I see it apply on the sql query level, so just to confirm my understanding:

if our model `Record` has  fields `id`, `foo`, `bar`, 'baz'
and we're creating it like this:
```
const record = Record.create({
  foo: 1,
  bar: 2
}, {returning: ['id', 'foo']}); // "bar" not included in the "returning" list

// - the resulting record object has `id`, `foo` and `bar` even though we didn't specify `bar` in the returning list
// - the resulting record object does not have `baz` since it was neither part of original input params nor listed in the returning list
```

**Comment by ephys** [comment]
The intended use is to refresh values on the instance to match what they are in the database, which is useful for values that are generated by the database (such as default values written in SQL) or when using things like `update` where the value is a `literal()` or `fn()` call

`baz` will be present on the instance if one of the following is true:

- it is provided to the create method
- returning is not disabled
- it has a default value (with the exception of default values that are generated by the database)
- in a future version: if it is null able

**Comment by pashka4281** [comment]
Thanks @ephys
