### ISSUE TITLE
Validate Length of Unique Constraints for MySQL

### ISSUE THREAD

**Issue by chinyavadav** [sequelize/sequelize#11901]
## Issue Description
MySQL Unique Constraint has a maximum length depending on the MySQL engine.  As described on this [link](https://stackoverflow.com/questions/16568128/max-size-of-unique-index-in-mysql)

### What do you expect to happen?

Sequelize should give a more specific error to make it easy for developers to resolve the issue

**Comment by sushantdhiman** [comment]
It should throw that error on `sync` or when you are creating that model equivalent table with migrations. What error do you get currently?

---------------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
