### ISSUE TITLE
Sequelize console printing question marks

### ISSUE THREAD

**Issue by noman-ih** [sequelize/sequelize#11917]
Sequelize console queries printing question rather than query values
Here is a screenshot of console
![image](https://user-images.githubusercontent.com/53823645/74099840-a91a7280-4b49-11ea-8f9a-72b13e4c11fa.png)

This is my sequelize config.json file

```
"development": {
    "username": "root",
    "password": "root1234",
    "database": "sabzimandi",
    "host": "127.0.0.1",
    "dialect": "mysql",
    "logging": true,
    "operatorsAliases": false,
    "define": {
      "timestamps": true,
      "paranoid": true,
      "freezeTableName": true
    },
    "query": {
      "raw":true
    }
  }
```

**Comment by soryy708** [comment]
I think that's intended behavior.
Parameterized statements make sure that the parameters (i.e. inputs) passed into SQL statements are treated in a safe manner. This is to mitigate SQL Injection type attacks.

**Comment by mistypig** [comment]
add a configure params in your config file : logQueryParameters: true
