### ISSUE TITLE
Distinct Rows in Sequelize

### ISSUE THREAD

**Issue by madhu-gogineni** [sequelize/sequelize#11914]
Hello ! I have Message model and History model. The associations are History belongs to message with foreign_key being 'message_id' and Message hasMany History on foreign_key being 'message_id'. 

I am trying to get distinct messages. The query I am using is 
 History.findAll({
    where: where,
    attributes: [[Sequelize.fn('DISTINCT', Sequelize.col('message.id')), 'distinct_id']],
    include: [{
      model: Message,
      where: joinwhere,
      as: 'message'
    }]
  })

When the query is being executed, the raw query generated becomes 
SELECT `history`.`id`, DISTINCT(`message`.`id`) AS `distinct_id`, `message`.`id` AS `message.id`, `message`.`comms_type` AS `message.comms_type`, `message`.`campaign_name` AS `message.campaign_name`, `message`.`subject` AS `message.subject`, `message`.`text` AS `message.text`, `message`.`image` AS `message.image`, `message`.`url` AS `message.url`, `message`.`cta_button_text` AS `message.cta_button_text`, `message`.`created_at` AS `message.created_at`, `message`.`updated_at` AS `message.updated_at` FROM `history` AS `history` INNER JOIN `message` AS `message` ON `history`.`message_id` = `message`.`id` AND `message_id`;

The problem is that distinct keyword only works when its used right after select. Anyone know what has to be done in my case?

**Comment by MillesC** [comment]
Did you finded a solution?

**Comment by madhu-gogineni** [comment]
> Did you finded a solution?

No, Instead I used raw query. I think that is the only option to execute 'distinct' key word for myql in sequelize
