### ISSUE TITLE
Order main query (hasMany) by nested association's column's sum

### ISSUE THREAD

**Issue by Dea7h-cyber** [sequelize/sequelize#11920]
## Issue Description

Hi! What I am trying to do seems pretty tricky but hopefully doable.
I have a Model called "Guild" and that guild hasMany GuildMember[] which hasOne Character.
What I am trying to do is I am trying to sort Guild by the Sum of the Character's "Resets" column (which is a number/int).

So basically for every GuildMember we get one Character which has a column named "Resets" and I am trying to sort Guild by the sum of all GuildMember's Character's Resets 😕 
Edit: and if possible even get the final sum of the Resets for each Guild in the result would be amazing...

I went through the docs quite a few times and couldn't find an example or explanation on how to do something similar... Hopefully you guys can help out! 

### Additional context
This is how my findAll looks so far:
```javascript
    const result = await model.Guild.findAll({
      limit: 5,
      offset: 0,
      include: [
        {
          model: model.GuildMember,
          include: [
            {
              model: model.Character,
              attributes: ['Resets']
            }
          ]
        }
      ]
    });
```

### Is this issue dialect-specific?

- Yes. This issue only applies to the following dialect(s): mssql
- [ ] I don't know.
- [x] No. This issue is relevant to Sequelize as a whole.

Thanks a lot for your time guys!

**Comment by Dea7h-cyber** [comment]
```sql
SELECT G.G_Name, (
    SELECT SUM(Resets) FROM Character C
    LEFT JOIN GuildMember GM ON C.Name=GM.Name
    WHERE GM.G_Name=G.G_Name
) AS TotalResets
FROM Guild G
ORDER BY TotalResets DESC
```

This is the sql version. Still need help to make it work with sequelize... 😕

**Comment by jy95** [comment]
No proper solution as [CTE (Common Table Expression)](https://github.com/sequelize/sequelize/pull/5434) aren't available in sequelize yet ...

A [filter clause](https://modern-sql.com/feature/filter) ( in mysql, it requires an extension) may be better for you but as also [it isn't implemented yet](https://github.com/sequelize/sequelize/issues/5732) that I used a workaround in my postgres code : 

```js
            count_summary: function () {
                const filterGen = (where) => Sequelize.literal(`COUNT(*) FILTER ${where}`);

                return {
                    attributes: [
                        "id",
                        ["kind", "category"],
                        [
                            filterGen(`(WHERE "tags"."id" IS NOT NULL)`),
                            "total"
                        ],
                        [
                            filterGen(`(WHERE "tags"."isValidated" = true)`),
                            "total_validated"
                        ],
                        [
                            filterGen(`(WHERE "tags"."isValidated" = false)`),
                            "total_unvalidated"
                        ],
                    ],
                    group: ["Tag_Category.id", "Tag_Category.kind"],
                    include: [{
                        model: sequelize.models.Tag,
                        as: "tags",
                        attributes: []
                    }]
                }
            }
```

**Comment by Dea7h-cyber** [comment]
Thank you for your reply @jy95 !
I was playing around with it and kinda came up with similar solution, but it still doesn't completely work for me because the order won't recognize my "new" column names.

```javascript
const result = await model.Guild.findAll({
  limit: 5,
  offset: 0,
  attributes: [
    [
      sequelize.literal(`(
      SELECT COUNT(*)
      FROM GuildMember as guild_memb
      WHERE guild_memb.G_Name = guild.G_Name
    )`),
      'MembersCount'
    ],
    [
      sequelize.literal(`(
        SELECT SUM(Resets) FROM Character as C
        LEFT JOIN GuildMember as GM ON C.Name=GM.Name
        WHERE GM.G_Name=guild.G_Name
    )`),
      'TotalResets'
    ]
  ],
  order: [['TotalResets', 'DESC']]
});
```

This kinda works (in the result I have the MembersCount and TotalResets working just fine) but if I try the to order them by either MembersCount or TotalResets it gives me an error ```Invalid column name 'TotalResets'```
