### ISSUE TITLE
Renaming attributes does not work in association `include`

### ISSUE THREAD

**Issue by remjx** [sequelize/sequelize#11921]
## Issue Description

When using `include` to grab association data, it is not possible to rename attributes on these models using `['attr_name', 'new_attr_name']` syntax

There was a previous issue for this https://github.com/sequelize/sequelize/issues/1556, but it was closed and I'm not sure why as this functionality does not seem to be working.

### Is your feature request related to a problem? Please describe.
This works:
```
include: [
        {
          model: db.mymodel,
          attributes: ['my_attr'],
        },
```

But this does not:
```
include: [
        {
          model: db.mymodel,
          attributes: [['my_attr', 'myAttrRenamed']],
        },
```

### Why should this be in Sequelize
The need for this is essentially the same as the need on the primary model (which is working).

### Describe alternatives/workarounds you've considered
The workaround of setting a getter method as mentioned here https://github.com/sequelize/sequelize/issues/1556#issuecomment-41256955 does not work in my case because there is not a 1:1 relationship between the columns and what I want to rename them to. In other words, in query 1, colA should be referred to as "col". In query 2, colB should be referred to as "col". So I can't set a getter for "col".

### Additional context
None

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by ronyeh3** [comment]
```
            attributes:[
                 [models.sequelize.literal('"foo"') , "fieldname"]
            ],
			/// will rename/add fieldname to foo (or value of [foo] when removing "")
```

**Comment by markjackson02** [comment]
@ronyeh3 that works! Except it's the reverse. So mine looks like this:

```
attributes: [
    [db.sequelize.literal('"oldFieldName"'), "newFieldName"],
],
```
Tested on Sequelize 5.21.5.

**I think this should be added to the documentation**, as it's not at all obvious this is how to do it.
