### ISSUE TITLE
sequelize get table by id

### ISSUE THREAD

**Issue by muhamadfathoni27rpl** [sequelize/sequelize#11932]
I will display data => Toni (this is the contents in the name rows), Class (class contents).
example output : toni , School Math
and I get the 'name + class' from another table Mysql By ID.

MODEL Sequelize Name : 
const Sequelize = require("sequelize");
const db = require("./sequelize");
module.exports = db.sequelize.define(
  "user_name",
  {
    uuid_kategori: {
      type: Sequelize.UUID,
      defaultValue: Sequelize.UUIDV1,
      primaryKey: true
    },
     name: {
      type: Sequelize.STRING
    }    
  },
  { timestamps: false }
);

MODEL Sequelize CLASS : 
const Sequelize = require("sequelize");
const db = require("./sequelize");
module.exports = db.sequelize.define(
  "user_class",
  {
    uuid_class: {
      type: Sequelize.UUID,
      defaultValue: Sequelize.UUIDV1,
      primaryKey: true
    },
    class: {
      type: Sequelize.STRING
    }    
  },
  { timestamps: false }
);

What should I do so that app.js can display data from other tables?

**Comment by soryy708** [comment]
Try asking on [stackoverflow](https://stackoverflow.com/questions/tagged/sequelize.js)
