### ISSUE TITLE
RAM Killer

### ISSUE THREAD

**Issue by scriptsure** [sequelize/sequelize#11942]
## Issue Description
Seems that on RDS MySql connections are not closing. As a result we are running into RAM issues. Gigs of RAM being taken up by very intensive queries... but the RAM is never released. AWS is saying that the connections seem to stay alive.

### What are you doing?
```    
   "dialectOptions": {
      "ssl": "Amazon RDS"
    },
    "pool": {
      "max": 5,
      "min": 0,
      "acquire": 30000,
      "idle": 10000
    }

```

### What do you expect to happen?
Thought, based on the config above, if a thread is idle for 10 seconds that the thread would be force-ably closed. 

### What is actually happening?
Connections are staying open along with any pages pulled in to RAM.
 

### Environment

- Sequelize version: 3.30.4
- Node.js version: 8.9.4
- Operating System: Ubuntu 16
  
### How does this problem relate to dialects?

- [ X ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

**Comment by EduardsE** [comment]
@scriptsure did you manage to resolve this issue?
