### ISSUE TITLE
Sequelize V5: Missing rows when trying to select nested joins

### ISSUE THREAD

**Issue by nairihar** [sequelize/sequelize#11944]
## Issue Description

I'm trying to do a select query with nested joins, my code works fine with **Sequelize v4** but with **Sequelize  v5** there is a missing row...

Basically I have 5 tables.

**Table1** many to many **Table2** through **Table3**

**Table1** many to many **Table4** through **Table5**

I'm doing something like this:

**Table5.findAll** include **Table4** Also include
**Table1** which inside also includes **Table3**

**Sequelize v4** returns 2 rows, but **Sequelize v5** returns one row.
The interesting thing here: if I take the generated **SQL query** from **Sequelize v5**  and run it in dbeaver(sql explorer) it will return two rows. So there is something wrong with the processing logic.
If I use **raw: true**, it will also return two rows.

Also, the **Table1** object should have an array of **Table3**, because we have many to many relationships, but Sequelize returns an object instead of an array, whose name is **Table3s**

**Comment by Luis-Palacios** [comment]
I'm having the exact same issue but on version 6, how did you solve this?
