### ISSUE TITLE
After file upload, response update not working in node js using sequelize update function. 

### ISSUE THREAD

**Issue by subhasis01** [sequelize/sequelize#11955]
I am trying to update the uploaded path using sequelize update function. This is working from my local system but not working in live server. My code is - 

businesstest.post('/test-update/:id', async function (req, res, next) {
	var paramID = req.params.id;
	var ValidImageTypes = ["image/jpg", "image/jpeg", "image/png"];
	if (req.files) {
		var in_array = require('in_array');
		if (!in_array(req.files.logo.mimetype, ValidImageTypes, true)) {
			return callback({ code: 500, status: 'error', message: "Image extension not valid.", errors: { avater: "Please provide jpg/jpeg/png type file." } });
		}
	}
	console.log("Execute 1");
	//===Image upload and update in db
	var filePath = '/images/test/' + parseInt(paramID) + '/';
	var fileUploadResp = await fileLib.awaitUploadFile(req.files.logo, filePath, req.files.logo.name.split('.').slice(0, -1).join('.'));
	console.log("Execute 2");
	if (fileUploadResp.status !== 'success') {
		return callback({ code: 500, status: 'error', message: 'File not uploaded!' });
	}
	console.log("Execute 3");
	var updateData = {};
	updateData['description'] = fileUploadResp.filename;
	console.log(fileUploadResp);
	console.log("Execute 4");
	try {
		var updatedResp = await Testmodel.update({ description: 'images/test/1/bali.jpg' }, { where: { id: parseInt(paramID) } });
		console.log("Execute 5");
		if (updatedResp) {
			return res.status(200).json(fileUploadResp);
		}
	} catch (e) {
		if (Settings.DEBUG_MODE) {
			console.log(e);
		}
		return res.status(500).json({ code: 500, status: 'error', message: 'Please check your internet connection!', data: {} });
	}
});

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ 
![error](https://user-images.githubusercontent.com/61449192/75223463-85535f80-57cc-11ea-88ca-6e6b45ebbb8b.png)
] No, I don't have the time and I wouldn't even know how to start.

**Comment by sarkar4540** [comment]
Please say the response codes, logs or any other data of what might have happened.

**Comment by atha-cyanberg** [comment]
Same issue here please help.
Sequelize version: 5.21.3
Node.js version: 12.14.0
Operating System: Ubuntu 16.04
