### ISSUE TITLE
Sequelize.NOW doesn't work still...

### ISSUE THREAD

**Issue by mahnunchik** [sequelize/sequelize#11957]
## Issue Description

`Sequelize.NOW` doesn't work for `defaultValue` as expected.

### What are you doing?

```js
up: (queryInterface, Sequelize) => {
  return queryInterface.changeColumn('test', 'timestamp', {
    type: Sequelize.DATE,
    allowNull: false,
    defaultValue: Sequelize.NOW,
  });
}
```

### What do you expect to happen?

Column default to `now()`

### What is actually happening?

Column default is empty.

### Additional context

`Sequelize.fn('NOW')` works as expected.

### Environment

- Sequelize version: 6.0.0-beta.5
- Node.js version: v12.15.0
- Operating System: Docker
- Postgres: postgres:12

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by herzog0** [comment]
Have you tried this?: 
```
defaultValue: Sequelize.fn('NOW')
```
It worked for me on newer versions of sequelzie-cli.

**Comment by Echoes93** [comment]
Sequelize.fn('NOW') doesn't work for sqlite. It generates query with appended braces to NOW, which is syntax error as sqlite requires just function name with no braces.
