### ISSUE TITLE
associations don't return error foreignKey

### ISSUE THREAD

**Issue by major697** [sequelize/sequelize#11956]
I have api writed in Express.js. I using Sequelize. I have a method create:

    exports.story = async (req, res) => {
      try {
        const userId = await authController.userId(req);
        const { type, firstTeam, secondTeam, date, place, leagueId } = req.body;
        const newEvent = {
          userId,
          type,
          firstTeam,
          secondTeam,
          date,
          place,
          leagueId,
        };
    
        const storeLeague = await models.Event.create(newEvent);
        return res.status(200).json(storeLeague);
      } catch (error) {
        return res.status(500).json(error);
      }
    };

**In this method I sending `firstTeam` = 1 and `secondTeam` = 5. This `id` is from table teams.**

Next I have Event model associate:

    ...
      Event.associate = models => {
        Event.belongsTo(models.Team, { foreignKey: 'firstTeam', as: 'teamFirst' });
        Event.belongsTo(models.Team, { foreignKey: 'secondTeam', as: 'teamSecond' });
      };
    ...

and Team model associate:

    ...
      Team.associate = models => {
        Team.hasMany(models.Event, { foreignKey: 'eventId', as: 'event' });
      };
    ...

In table teams I have:

    +----+--------+----------------+------+------+----------+---------------------+---------------------+
    | id | userId |      name      | logo | type | leagueId |      createdAt      |      updatedAt      |
    +----+--------+----------------+------+------+----------+---------------------+---------------------+
    |  1 |      1 | Arsenal Londyn | test |    1 |        1 | 2020-02-24 09:13:23 | 2020-02-24 09:13:23 |
    |  2 |      1 | Chelsea Londyn | test |    1 |        1 | 2020-02-24 09:22:23 | 2020-02-24 09:22:23 |
    +----+--------+----------------+------+------+----------+---------------------+---------------------+

How I can check did exist row by `teams.id` = 5 ? Why Sequelize don't return me error? In table `teams` I don't have `id` = 5.

I'm using MySQL databse.

this same on [stackoverflow](https://stackoverflow.com/questions/60373270/check-exist-id-in-table-using-method-create-in-sequelize-in-express)

**Comment by soryy708** [comment]
This was solved on the stackoverflow question linked, so I think this should be closed.
