### ISSUE TITLE
43069.0122916667 value will not be written correctly to mssql

### ISSUE THREAD

**Issue by MartinJLee** [sequelize/sequelize#11959]
## Issue Description
43069.0122916667 value will not be written correctly to mssql
### What are you doing?

```js
const value = 43069.0122916667;
getSQLTypeFromJsType(value, connection.lib.TYPES);
```

### What do you expect to happen?

For the value '43069.0122916667', it ended up written '6175.5241442476'

### What is actually happening?

when 43069.0122916667 is passed to getSQLTypeFromJsType, the precision and scale will be set to 30 and 15.
Which in tedios isn't handled correctly.
see issue https://github.com/tediousjs/tedious/issues/1058

### Additional context

https://github.com/tediousjs/tedious/issues/1058

### Environment

- Sequelize version: 5.21.5
- Node.js version: v10.16.0
- Operating System: osx 10.14.6 

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): mssql
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, thanks for filing the issue and writing a PR! It is not clear to me however if your PR #11962 fixed your problem entirely or just part of it.

Is the problem solved? Can this issue be closed? Thanks

**Comment by MartinJLee** [comment]
Hi @papb 
for now, it will fix the issue. Ideally, we also want to set a correct precision value as per the comment in the code.
https://github.com/sequelize/sequelize/blob/c845f0bc4f2a51fe681a271845f22f5673725b69/lib/dialects/mssql/query.js#L36

**Comment by papb** [comment]
Nice! Do you have any idea on how to set the correct precision?

**Comment by papb** [comment]
Closed by #11962

**Comment by MartinJLee** [comment]
I might need to have a look to figure that out.

**Comment by papb** [comment]
@MartinJLee if you could do that it would be great! No need to go deep into it, just give me some direction... For instance, currently the precision is set to a constant (30). What it should depend on?

**Comment by MartinJLee** [comment]
@papb You can find the detail in the following link
https://docs.microsoft.com/en-us/sql/t-sql/data-types/precision-scale-and-length-transact-sql?view=sql-server-ver15
> Precision is the number of digits in a number. Scale is the number of digits to the right of the decimal point in a number. For example, the number 123.45 has a precision of 5 and a scale of 2.
