### ISSUE TITLE
Strings can not be escaped if operators like `iLike` is using.

### ISSUE THREAD

**Issue by Delagardi** [sequelize/sequelize#11961]
## Issue Description
Hello!

This code return filtered result by `searchTerm` as expected. 
```
const organisationsDB = await db.organisation.findAll({
  where: {
    name: {
      // String is not escaped 
      [Op.iLike]: `${searchTerm}%`,
    },
  },
});
```
But if the `searchTem` will be something like `%org` logic would be broken, bcs Sequelize read it like %org%. 
If I try to escape the string with sequelize.escape operator `iLike` is not working. 
```
[Op.iLike]: db.sequelize.escape(`${searchTerm}%`),
// or
[Op.iLike]: `${db.sequelize.escape(`${searchTerm}`)}%`,
```
As far as I understand the reason he gets something like: `'org%'` or `'org'%`.

### What are you doing?

Btw I got **500 error** on this link: https://github.com/papb/sequelize-sscce

### What do you expect to happen?
I expected to get result filtered by `searchTerm` (string) and `searchTerm` escaped by `sequelize.escape()`

### What is actually happening?
When I using escape function with `iLike` operator I am getting empty array instead of filtered result

```
[]
```

### Additional context
[-]
### Environment

- Sequelize version: 4.44.3
- Node.js version: v12.13.0 
- Operating System: Windows 10
- If TypeScript related: TypeScript version: not related.

### How does this problem relate to dialects?
I am using PostreSQL but not sure if this the reason 

- [ x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by reedfeng** [comment]
I modified the string with

`replace(/\\/g, '\\\\').replace(/%/g, '\\%').replace(/_/g, '\\_');`

**Comment by snewcomer** [comment]
Same here. v3.30.  I'm not sure if this might be fixed on the latest versions.

**Comment by oyepez003** [comment]
Use:

```ts
const { Op, Sequelize } = require('sequelize');

const organisationsDB = await db.organisation.findAll({
  where: {
    name: {
      [Op.iLike]: Sequelize.literal(`'%${searchTerm}%'`),
    },
  },
});
```
