### ISSUE TITLE
It is impossible to create a Postgres partitioned table 

### ISSUE THREAD

**Issue by tumdav** [sequelize/sequelize#11960]
# Issue Description
Since from POSTGRES 10, it is available to create a partitioned table. And there is one way to do that. Add a `partition by (column)` definition while creating a table. It is impossible to ALTER a table in order to change this definition.
Currently, SEQUELIZE offers to define only those parameters

```js
{
   engine: 'MYISAM',   
  charset: 'latin1',  
  schema: 'public',    
  comment: 'my table',
  collate: 'latin1_danish_ci' 
}
```

### What are you doing?

Just I am trying to create a table using QueryInterface

### What do you expect to happen?

To make available add  "custom"(dialect  based) options as well

### What is actually happening?

It is impossible to add "custom" options

### Environment

- Sequelize version: 5.21.4
- Node.js version: 12.6.0
- Operating System: Mac OS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): **postgres**
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by MichaelTendoSsemwanga** [comment]
+1
