### ISSUE TITLE
More sensible default behaviour of bulkCreate

### ISSUE THREAD

**Issue by leventov** [sequelize/sequelize#11967]
## Issue Description

The documentation for `options.updateOnDuplicate` in `Model.bulkCreate` says:

>  Fields to update if row key already exists (on duplicate key update)? (only supported by MySQL, MariaDB, SQLite >= 3.24.0 & Postgres >= 9.5). By default, all fields are updated.

This reads like the default behaviour of `bulkCreate` is upsert-like. However, in fact, it's not: it fails with `UniqueConstraintError` on the primary key field of the table.

### Describe the solution you'd like

I think the implementation should be aligned with the doc and by default not trying to update primary key fields on duplicates.

### Describe alternatives/workarounds you've considered
Workaround: provide `updateOnDuplicate: [...list all your fields, except the primary key fields, and, perhaps, `created_at`]` to each `bulkCreate()` call.

Alternative: align the documentation with the current implementation, saying that by default duplicates are not tolerated, and document how to circumvent that (like the above workaround), or add a new boolean flag to `options` so that users don't have to manually list all fields in `updateOnDuplicate`.

### Additional context
Using Postgres backend.
This issue is also reported here: https://github.com/sequelize/sequelize/issues/5899#issuecomment-380299908

### Is this issue dialect-specific?

- Not sure

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time, although I believe I could do it if I had the time...

**Comment by leventov** [comment]
https://github.com/sequelize/sequelize/pull/11611 might also fix this

**Comment by omerts** [comment]
This issue exists also in sqlite. When ```updateOnDuplicate``` isn't passed as a parameter, there is no ``` ON CONFLICT...``` syntax added to the query.
