### ISSUE TITLE
Getter not called after findOrCreate

### ISSUE THREAD

**Issue by GadiManorH** [sequelize/sequelize#11972]
## Issue Description
Getter method not called on instance created on `findOrCreate`.
### What are you doing?
I have a model `Users`. The user has a getter defined the following way:
```
      getterMethods: {
        getName() {
          return `${this.firstName}  ${this.lastName};
        },
      },
```

The getter is working as expected.
However, I noticed that when I call `Users.findOrCreate` the getter isn't called on the created instance. In case the instance already existed the getter is working fine.

I tried calling `findByPk` after `findAndCreate` and on that instance the getter is called as expected.

### What do you expect to happen?
I expected that the getter will work on the instance returned from `findOrCreate` on the scenario it wasn't existed before. 

### What is actually happening?
```
const newUser = User.findOrCreate({...});
console.log(newUser[1]); //true
console.log(newUser[0].name); //undefined - getter not called
```
### Environment

- Sequelize version: 5.19.0
- Node.js version: 10.17
- Operating System: MacOS

**Comment by sushantdhiman** [comment]
Use VIRTUAL instead of getter/setter, later will be deprecated soon

```js
(async () => {
    const User = sequelize.define('user', {
      firstName: Sequelize.DataTypes.TEXT,
      lastName: Sequelize.DataTypes.TEXT,
      fullName: {
        type: Sequelize.DataTypes.VIRTUAL,
        get() {
          return `${this.firstName} ${this.lastName}`;
        },
>>      set(value) {
          throw new Error('Do not try to set the `fullName` value!');
        }
      }
    });
                                      
    await sequelize.sync();
                                   
    const [user] = await User.findOrCreate({
      where: {
        firstName: 'Bob',
        lastName: 'Builder'
      }
    });
                                   
    console.log(user.fullName);
  })();
```
