### ISSUE TITLE
Add support for the Snowflake database

### ISSUE THREAD

**Issue by IgorP120** [sequelize/sequelize#11979]
## Issue Description

Snowflake cloud database is not supported currently.

### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Implement new driver for Snowflake database, see https://docs.snowflake.net/manuals/sql-reference-commands.html

### Why should this be in Sequelize
Snowflake popularity [grows](https://www.forbes.com/sites/petercohan/2019/08/16/growing-at-237-snowflake-says-its-taking-business-from-teradata-and-ibm)

### Describe alternatives/workarounds you've considered
I don't see any alternatives to implementing a dedicated Snowflake driver.

### Additional context
None

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
> Yes, I have the time and I know how to start.

Nice! May I ask what will be your first steps?

**Comment by IgorP120** [comment]
Thanks for your response. Unfortunately my schedule has changed, I'll be busy with other projects in the foreseeable future, so won't be able to work on this anytime soon. Maybe next year, to be decided.

**Comment by sshivananda** [comment]
@IgorP120 , @papb  I will be taking a stab at this. However I would fall into the "Yes, I have the time but I don't know how to start, I would need guidance." category - so it might take longer to submit a change. In the meanwhile - if you have suggestions on where I can start : it might be helpful.

**Comment by joliveros-altus** [comment]
Hi @sshivananda , did you happen to start with this one. I'm also interested in this one. We're considering a jump to Snowflake as well, and having this in `sequelize` would be a game-changer.

**Comment by sshivananda** [comment]
@joliveros-altus I started - but didnt make great progress on this one.

**Comment by wonderfulolanrewaju** [comment]
Hello. @joliveros-altus and @sshivananda I am also interested in we bringing the snowflake dialect support into sequelize.
