### ISSUE TITLE
SequelizeDatabaseError: Connection closed before request completed. - on AWS Lambda - very long string in JSON field

### ISSUE THREAD

**Issue by eminord** [sequelize/sequelize#11970]
Hi all,

I have an API developed with Node.Js and deployed on AWS Lambda

This API connects to a SQL Server via sequelize. For Dev and Testing we have 2 different servers

This is the model

module.exports = function(sequelize, DataTypes) {
    const Account = sequelize.define('Account', {
        FK: {
            type: DataTypes.INTEGER(),
            primaryKey: true
        },
        LargeText: {
            type: DataTypes.TEXT()
        }
    }, {
        hasTrigger: true,
        timestamps: false,
        tableName: 'TABLE'
    });
    return Account;
};

One of my endpoints receives a large text on the request body and updates table TABLE

When I run this app locally with serverless-offline, connecting to our Dev SQL Server DB, the endpoint works fine and the table gets updated with any text I send trough Postman

But when I deploy this same code to Lambda (connecting to out Test SQL Server DB), suddenly the endpoint responds with a 500 error, and this gets logged:

**SequelizeDatabaseError: Connection closed before request completed.**

I tried shortening the text from the input json field and the Lambda endpoint works fine.

To be sure it wasn't a SQL Server issue, i tried connecting the API in Lambda to our Dev SQL Server (wich worked fine with my local instance of the API), and I get the same error. And again, it works fine after shortening the text field

The code running locally and the code deployed are exactly the same

What could be the issue? What am I missing?

Thank you!

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
