### ISSUE TITLE
Cannot force order by out of subquery when the order by is a function

### ISSUE THREAD

**Issue by a88zach** [sequelize/sequelize#11983]
## Issue Description

Normally you can force the order by clause on the correct query, main or subquery,  by specifying a model in the OrderItem `[[{ model: Child, as: 'child' }, 'order' ]]`.  However, if the order by clause is a function, there is no way to force it, and the order by clause ends up on the subquery and main query.

We need a way to force the order by clause from being added to the subquery when using a function for the order by clause

### What are you doing?

**Here is the link to the SSCCE for this issue:*
https://github.com/papb/sequelize-sscce/pull/56

### What do you expect to happen?

The query should run successfully

### What is actually happening?

The query is failing b/c the order by clause gets attached to the subquery

```
SELECT
	`GrandParent`.*,
	`parent->child`.`id` AS `parent.child.id`,
	`parent->child`.`name` AS `parent.child.name`,
	`parent->child`.`order` AS `parent.child.order`,
	`parent->child`.`ParentId` AS `parent.child.ParentId`
FROM (
	SELECT
		`GrandParent`.`id`,
		`GrandParent`.`name`,
		`parent`.`id` AS `parent.id`,
		`parent`.`name` AS `parent.name`,
		`parent`.`order` AS `parent.order`,
		`parent`.`parentId` AS `parent.parentId`
	FROM
		`GrandParents` AS `GrandParent`
		INNER JOIN `Parents` AS `parent` ON `GrandParent`.`id` = `parent`.`parentId`
	WHERE
		`GrandParent`.`name` = 'Foo'
		AND(
			SELECT
				`parent`.`parentId` FROM `Parents` AS `parent`
				INNER JOIN `Children` AS `child` ON `parent`.`id` = `child`.`ParentId`
					AND `child`.`name` = 'Baz'
			WHERE (`parent`.`parentId` = `GrandParent`.`id`)
		LIMIT 1) IS NOT NULL
	ORDER BY
		NULLIF(
			CASE "parent->child"."order" ~ '^[1-5]$'
			WHEN TRUE THEN
				"parent->child"."order"
			ELSE
				''
			END, '')::INT DESC NULLS LAST
	LIMIT 1) AS `GrandParent`
	INNER JOIN `Children` AS `parent->child` ON `parent.id` = `parent->child`.`ParentId`
		AND `parent->child`.`name` = 'Baz'
	ORDER BY
		NULLIF(
			CASE "parent->child"."order" ~ '^[1-5]$'
			WHEN TRUE THEN
				"parent->child"."order"
			ELSE
				''
			END, '')::INT DESC NULLS LAST;
```

### Environment

- Sequelize version: latest
- Node.js version: 12
- Operating System: OSX
- If TypeScript related: latest

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by pzrq** [comment]
Looks like the same issue (why is there an ORDER BY in a subquery?) as https://github.com/sequelize/sequelize/issues/6513

**Comment by pzrq** [comment]
At least in my case, commenting out [these three lines](https://github.com/sequelize/sequelize/blob/a5a60f9ff1ca0b0e8d4743f82b4047227153fadb/lib/dialects/abstract/query-generator.js#L1362-L1364) worked. I'm not sure how to retain TOP ORDER BY subquery support for Microsoft SQL Server though.

**Comment by alex-jgr** [comment]
In my case it worked by adding the option
`subQuery: false `
to the options of the main query.
Apparently it's not a documented option and there is a [stackoverflow question](https://stackoverflow.com/questions/42439183/sequelize-associations-causing-sub-query)  on a similar issue.
This results in moving all the table fields from the subquery select into the main select and in your case "FROM" will only be followed by the table name GrandParent , instead of a subquery and then there isn't a subquery anymore to add the "ORDER BY" to.
I think this answer will however not work for every situation and it does not answer the question, it only offers an alternative. Maybe in some cases that I can not think of right now one would actually need a subquery, so I don't recommend closing this issue unless there is a solution for the actual problem.

**Comment by a88zach** [comment]
@alex-jgr, yes, that works, but is not a great option if you are concerned with performance and are doing paged queries

**Comment by joacub** [comment]
this works with subQuery

[Sequelize.literal(`'${column}'`), direction]
