### ISSUE TITLE
model.js update method's bug

### ISSUE THREAD

**Issue by joe-221** [sequelize/sequelize#11980]
sequelize's version: "5.21.1",
## Issue Description
I want to use sequelize's  optimistic lock， I had set [version: true] in my model, when I execute update method, it calls the model.js, but in 3144 lines, it is defined that [let different = false], but there is no place for it to reset the value, because in 3143 lines [let changedValues;] was defined, in the following code [                
if (!changedValues) {
        changedValues = thisChangedValues;
 } else {
         different = !_.isEqual(changedValues, thisChangedValues);
}] , it can only enter if branch, so the parameter [different] is always false,  so it will never call the code [return instance.save(individualOptions);] , the optimistic lock handling will also not be executed.

### What are you doing?
in the code
[
                if (!changedValues) {
                  changedValues = thisChangedValues;
                } else {
                  different = !_.isEqual(changedValues, thisChangedValues);
                }
]
in if branch I add [different = true;], the optimistic lock handle will be executed.
Is that the sequelize's bug? 

### What do you expect to happen?
if I set version = true, optimistic lock function can be executed.

### Environment

- Sequelize version: 5.21.1
- Node.js version: 12.14.1
- Operating System: Win 10
- If TypeScript related: TypeScript version: 3.7.3

### How does this problem relate to dialects?

- [●] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version : MYSQL 5.7

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by joe-221** [comment]
model.js
// Get instances and run beforeUpdate hook on each record individually
      if (options.individualHooks) {
        return this.findAll({
          where: options.where,
          transaction: options.transaction,
          logging: options.logging,
          benchmark: options.benchmark,
          paranoid: options.paranoid
        }).then(_instances => {
          instances = _instances;
          if (!instances.length) {
            return [];
          }

          // Run beforeUpdate hooks on each record and check whether beforeUpdate hook changes values uniformly
          // i.e. whether they change values for each record in the same way
          let changedValues;                        // 3143 lines
          let different = false;                        // 3144 lines

          return Promise.map(instances, instance => {
            // Record updates in instances dataValues
            Object.assign(instance.dataValues, values);
            // Set the changed fields on the instance
            _.forIn(valuesUse, (newValue, attr) => {
              if (newValue !== instance._previousDataValues[attr]) {
                instance.setDataValue(attr, newValue);
              }
            });

            // Run beforeUpdate hook
            return this.runHooks('beforeUpdate', instance, options).then(() => {
              if (!different) {
                const thisChangedValues = {};
                _.forIn(instance.dataValues, (newValue, attr) => {
                  if (newValue !== instance._previousDataValues[attr]) {
                    thisChangedValues[attr] = newValue;
                  }
                });

                if (!changedValues) {
                  changedValues = thisChangedValues;
                } else {
                  different = !_.isEqual(changedValues, thisChangedValues);
                }
              }

              return instance;
            });
          }).then(_instances => {
            instances = _instances;

            if (!different) {
              const keys = Object.keys(changedValues);
              // Hooks do not change values or change them uniformly
              if (keys.length) {
                // Hooks change values - record changes in valuesUse so they are executed
                valuesUse = changedValues;
                options.fields = _.union(options.fields, keys);
              }
              return;
            }
            // Hooks change values in a different way for each record
            // Do not run original query but save each record individually
            return Promise.map(instances, instance => {
              const individualOptions = _.clone(options);
              delete individualOptions.individualHooks;
              individualOptions.hooks = false;
              individualOptions.validate = false;

              return instance.save(individualOptions);
            }).tap(_instances => {
              instances = _instances;
            });
          });
        });
      }

**Comment by joe-221** [comment]
who can help me?

**Comment by sushantdhiman** [comment]
Create a SSCCE https://github.com/papb/sequelize-sscce and comment here
