### ISSUE TITLE
Type Error in belongsTo only thrown when using extends instead of sequelize.define(

### ISSUE THREAD

**Issue by itsmebasti** [sequelize/sequelize#11985]
### What are you doing?
I am having some really basic models, that I want to associate to each other using `belongsTo`.

planet.js
```
"use strict";

const { DataTypes, Model } = require('sequelize');

module.exports = function(sequelize) {
    const Planet = class Planet extends Model {};

    Planet.init({
        name: DataTypes.STRING,
    } , {sequelize, modelName: 'Planet'});
};
```

fleet.js
```
"use strict";

const { DataTypes, Model } = require('sequelize');

module.exports = function(sequelize) {
    const Fleet = class Fleet extends Model {};

    Fleet.init({
        name: DataTypes.STRING,
    } , {sequelize, modelName: 'Fleet'});
};
```

sequelize.js
```
"use strict";

const { Sequelize } = require('Sequelize');

const instance = module.exports = new Sequelize(process.env.DATABASE_URL, {
    logging: false,
    define: { freezeTableName: true },
    dialect: "postgres",
    dialectOptions: { ssl: { require: true, rejectUnauthorized: false } }
});

require("../model/planet")(instance);
require("../model/fleet")(instance);

instance.models.Fleet.belongsTo(instance.models.Planet, {as: 'source'});
instance.models.Fleet.belongsTo(instance.models.Planet, {as: 'target'});
```

### What do you expect to happen?

I expect extending the Model class, to work the same as when using `sequelize.define()`

### What is actually happening?

```
22:03:09 web.1   |  Error: Fleet.belongsTo called with something that's not a subclass of Sequelize.Model
22:03:09 web.1   |      at Function.<anonymous> (C:\Users\seb_s\WebstormProjects\gwio\node_modules\sequelize\lib\associations\mixin.js:93:13)
22:03:09 web.1   |      at Object.<anonymous> (C:\Users\seb_s\WebstormProjects\gwio\src\database\sequelize.js:15:23)
```

### Additional context

The problem does not occur when using `sequelize.define()`
So defining my models like this, works just fine. (I just personally prefer working with classes and objects)
```
    const Planet = sequelize.define("Planet", {
        name: DataTypes.STRING,
    });
```

I don't understand how they behave differently since in the documentation they are described as being equivalent

> Internally, sequelize.define calls Model.init, so both approaches are essentially equivalent.

### Environment

- Sequelize version: sequelize@5.21.5 
- Node.js version: v12.13.0 
- Operating System: Windows 10 (executing this on heroku local)

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by WolfieZero** [comment]
I've noticed this as well.

This file is fine: 
```javascript
// airport.model.js
const sequelize = require('../services/sequelize.service');
const ReviewModel = require('./review.model');

class AirportModel extends Model {}
AirportModel.init(attributes, { sequelize, modelName });
AirportModel.hasMany(ReviewModel);
```

This will fail with `Error: airport.hasMany called with something that's not a subclass of Sequelize.Model`
```javascript
// review.model.js
const sequelize = require('../services/sequelize.service');

class ReviewModel extends Sequelize.Model {}
ReviewModel.init(attributes, { sequelize, modelName });
```

But this is fine
```javascript
// review.model.js
const sequelize = require('../services/sequelize.service');

const ReviewModel = sequelize.define(modelName, attributes);
```

But interestingly, when I add `ReviewModel.belongsTo(AirportModel);` to the working `review.model.j` file it fails again with `Error: review.belongsTo called with something that's not a subclass of Sequelize.Model`

Seems to be an issue with the class base call for sure.

**Comment by itsmebasti** [comment]
I was able to solve it, it seems to be related to how the static ` init ` method is called, in my current and working version I just override the super.init.
I followed this [really nice blog](https://codewithhugo.com/using-es6-classes-for-sequelize-4-models/) article and now it works like a charm:

```
module.exports = class Fleet extends Model {
	static fields = {
		name: DataTypes.STRING,
	};
	
	static init(sequelize) {
		return super.init(this.fields, { sequelize });
	}
}
```

and later I call it this way:

```
const Fleet = require("../model/fleet");
.
.
.
Fleet.init(sequelize);
Fleet.belongsTo(Planet, {as: 'source' });
```

**Comment by peabnuts123** [comment]
Just posting this around on all these similar issues; I ran into this error because i was importing my Models from another folder i.e. the file where my model was defined was importing `sequelize` from a different node_modules. This meant that the `instanceof` check was false because, even though my models WERE inheriting from `Model` from `sequelize` - it was a different class, technically (with all the same properties and attributes). 

You can think of a `foo instanceof MyClass` check as comparing the prototype of `foo` all the way up the chain e.g. `foo.__proto__ === MyClass.prototype`, `foo.__proto__.__proto__ === MyClass.prototype` etc. until either `__proto__` is `null` (in which case `instanceof = false`) or the `===` equality check is true (in which case `instanceof = true`). So this is why a different instance of the `Sequelize.Model.prototype` object would return `false` for an `instanceof` check. 

This is a pretty unique scenario so I solved it by symlinking the `node_modules` from my database project to my "shared code" project. Just wanted to post this in case anybody else was doing a similar thing, in an attempt to save somebody from a couple of hours of WTFing.

**Comment by nitinshyamk** [comment]
Man, can't thank you both enough for this - this resolves a long attempt trying to debug a downstream error in associations.
