### ISSUE TITLE
add cdn for https://sequelize.org/

### ISSUE THREAD

**Issue by icai** [sequelize/sequelize#11986]
### What was unclear/insufficient/not covered in the documentation

add cdn for https://sequelize.org/

### If possible: Provide some suggestion on how we can enhance the docs

https://www.cloudflare.com/  has free plan

**Comment by papb** [comment]
I don't understand, you wanted https://sequelize.org/ to work as a CDN for sequelize? But sequelize is not meant to run in the browser, what do you mean?

**Comment by icai** [comment]
@papb I  can't open this website in China, it is very crazy.

**Comment by papb** [comment]
You can't access https://sequelize.org from China?

**Comment by icai** [comment]
@papb  china gov recently block the `Github Pages` ip (may some people host `bad` content in github pages) a lot of ISPs ping timeout. 
you can check the ping result  https://defense.yunaq.com/tools/dnslookup/?domain=sequelize.org and https://www.whatsmydns.net/#A/sequelize.org. by the way  "探测点超时" mean timeout.

**Comment by papb** [comment]
@sushantdhiman What do you think of this?

**Comment by sushantdhiman** [comment]
@papb I think @icai want us to use cloudflare name servers instead of github name servers. This should be possible, I'll see when I get some time to have this setup.

**Comment by icai** [comment]
@sushantdhiman  only bind the domain dns to cloudflare,  you don't need to change anything, Github Pages ip is available.

**Comment by sushantdhiman** [comment]
https://sequelize.org is now using Cloudflare name servers
