### ISSUE TITLE
Paranoid as option when creating many-to-many association

### ISSUE THREAD

**Issue by Leithal3** [sequelize/sequelize#11991]
## Issue Description
I want to be able to create a belongs-to-many association that is paranoid. The association should create a join table that has a deletedAt column. 

I found this in `lib/associations/belongs-to-many.js`. Why does it say that a paranoid join table doesn't make sense?
```js
    if (typeof this.through.model === 'string') {
      if (!this.sequelize.isDefined(this.through.model)) {
        this.through.model = this.sequelize.define(this.through.model, {}, Object.assign(this.options, {
          tableName: this.through.model,
          indexes: [], //we don't want indexes here (as referenced in #2416)
          paranoid: false, // A paranoid join table does not make sense
          validate: {} // Don't propagate model-level validations
        }));
      } else {
        this.through.model = this.sequelize.model(this.through.model);
      }
    }
```

### Describe the solution you'd like
I was thinking something along the lines of a `paranoid` key in the options object and you would create the association like: 
```js
Customer.belongsToMany(PhoneNumber, {
  through: 'CustomerPhoneNumbers',
  as: 'SecondaryPhoneNumbers',
  paranoid: true
})
```

### Describe alternatives/workarounds you've considered
A workaround is to define the join table as a separate model and have the model be paranoid. 
But this requires potentially many models that are only required because we want to add a deletedAt column.

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
It should be easy to do by passing `options.paranoid` here https://github.com/sequelize/sequelize/blob/5822bc793abe1cffd6220ba7888a5f925c51cb02/lib/associations/belongs-to-many.js#L148

May I know your use-case?

**Comment by Leithal3** [comment]
Hi Sushant, 

My use case is relatively similar to the example solution I gave. I have an n:m relationship between customers and locations and I want the join table to be paranoid as I don't want to actually remove the associations on delete and I need to keep track of this information. 

This is one example and it is currently possible to solve this problem by creating an explicit model for the join table but I was hoping to avoid that because it is not the only example of behaviour like this that I want to have in my application. 

I am wanting to create multiple join tables through model associations that are paranoid and creating a separate model for each of them (as I see it) needlessly leads to many models that have no value other than to add the `deletedAt` column. 

What are your thoughts? Is my reasoning clear?
