### ISSUE TITLE
Model.toJSON Incorrectly returns Object

### ISSUE THREAD

**Issue by Danebrouwer97** [sequelize/sequelize#11990]
## Issue Description
When using the method `toJSON()` on a `Model` it returns an `Object` where it should be returning a `String`.

See Definition of JSON:
https://www.json.org/json-en.html
https://en.wikipedia.org/wiki/JSON

### What are you doing?
```js
const User = sequelize.define(...);
User.findAll().then(arUsers => {
    console.log(arUsers[0].toJSON()); 
    console.log(typeof arUsers[0].toJSON());
});
```

### What do you expect to happen?
I would expect a function named `toJSON` to return JSON

### What is actually happening?
It returns an `Object`

```js
User.findAll().then(arUsers => {
    console.log(arUsers[0].toJSON());
    console.log(typeof arUsers[0].toJSON());
})
// { ... }
// "Object"
```

### Environment

- Sequelize version: "^5.21.5"
- Node.js version: "v12.15.0"
- Operating System: Windows 10

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by SimonSchick** [comment]
This is the intended behaviour, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior
