### ISSUE TITLE
JSONB: SequelizeDatabaseError: operator does not exist: double precision = integer[]

### ISSUE THREAD

**Issue by mahnunchik** [sequelize/sequelize#11998]
# Issue Description 

I got the following error: `[error] message: operator does not exist: double precision = integer[], stack: SequelizeDatabaseError: operator does not exist: double precision = integer[]`

### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/57

### What do you expect to happen?

1. No error.
2. Working query.

### What is actually happening?

```
[error] message: operator does not exist: double precision = integer[], stack: SequelizeDatabaseError: operator does not exist: double precision = integer[]
```

### Environment

- Sequelize version: v5 and v6
- Node.js version: 12
- Operating System: any

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by kingjerod** [comment]
I'm getting this problem too. No matter what I do, it casts my key to double precision and then compares it to my value. 
Example:
```
 await UserModel.findAll({where: {meta: {x: [1, 3]}});
```

The generated query is this:
```
WHERE CAST(("UserModel"."meta"#>>'{x}') AS DOUBLE PRECISION) = ARRAY[1,3];
```
