### ISSUE TITLE
Query to JSONB in v5 and v6

### ISSUE THREAD

**Issue by mahnunchik** [sequelize/sequelize#11996]
### What was unclear/insufficient/not covered in the documentation

Is it possible to query JSON/JSONB data in v5 and v6?

### If possible: Provide some suggestion on how we can enhance the docs

Docs for v4 https://sequelize.org/v4/manual/tutorial/querying.html#jsonb

### Additional context

Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): postgres
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
v5, https://sequelize.org/v5/manual/querying.html#jsonb
v6, https://sequelize.org/master/manual/other-data-types.html
