### ISSUE TITLE
"Truncated incorrect DOUBLE value" when calling model.destroy with array of IDs

### ISSUE THREAD

**Issue by tresheffron** [sequelize/sequelize#12004]
```javascript
var del = [];
 ...
del.push(id); //id is of type INT
...
importer.model.destroy({
  where: { id: { [Op.in]: [del] } }
})
```

When logging `del` to the console, it shows an array of INTs.
> 1178323, 1178324, 1178325, 1178326, 1178327, 1178328, 1178329,
  1178330, 1178331, 1178332, 1178333, 1178334, 1178335, 1178336,
  1178337, 1178338, 1178339, 1178340, 1178341, 1178342, 1178343,
  1178344, 1178345, 1178346, 1178347, 1178348, 1178349, 1178350,
  1178351, 1178352, 1178353, 1178354, 1178355, 1178356, 1178357,
  1178358, 1178359, 1178360, 1178361, 1178362, 1178363, 1178364,
  1178365, 1178366, 1178367, 1178368, 1178369, 1178370, 1178371,
  1178372, 1178373, 1178374, 1178375, 1178376, 1178377, 1178378,
  1178379, 1178380, 1178381, 1178382, 1178383, 1178384, 1178385,
  1178386, 1178387, 1178388, 1178389, 1178390, 1178391, 1178392,
  1178393, 1178394, 1178395, 1178396, 1178397, 1178398, 1178399,
  1178400, 1178401, 1178402, 1178403, 1178404, 1178405, 1178406,
  1178407, 1178408, 1178409, 1178410, 1178411, 1178412, 1178413,
  1178414, 1178415, 1178416, 1178417, 1178418, 1178419, 1178420,
  1178421, 1178422,
  ... 6 more items

model.destroy then fails with the following:
> code: 'ER_TRUNCATED_WRONG_VALUE',
    errno: 1292,
    sqlState: '22007',
    sqlMessage: "Truncated incorrect DOUBLE value: '1178323,1178324,1178325,1178326,1178327,1178328,1178329,1178330,1178331,1178332,1178333,1178334,1178335,1178336,1178337,1178338,'",
    sql: "DELETE FROM `fulfilled_shipments` WHERE `id` IN ('1178323,1178324,1178325,1178326,1178327,1178328,1178329,1178330,1178331,1178332,1178333,1178334,1178335,1178336,1178337,1178338,1178339,1178340,1178341,1178342,1178343,1178344,1178345,1178346,1178347,1178348,1178349,1178350,1178351,1178352,1178353,1178354,1178355,1178356,1178357,1178358,1178359,1178360,1178361,1178362,1178363,1178364,1178365,1178366,1178367,1178368,1178369,1178370,1178371,1178372,1178373,1178374,1178375,1178376,1178377,1178378,1178379,1178380,1178381,1178382,1178383,1178384,1178385,1178386,1178387,1178388,1178389,1178390,1178391,1178392,1178393,1178394,1178395,1178396,1178397,1178398,1178399,1178400,1178401,1178402,1178403,1178404,1178405,1178406,1178407,1178408,1178409,1178410,1178411,1178412,1178413,1178414,1178415,1178416,1178417,1178418,1178419,1178420,1178421,1178422,1178423,1178424,1178425,1178426,1178427,1178428')"

Notice the quotes around the entire set of values inside the parens that causes the list of ids to be treated as one string.

This started after upgrading from 4.38.0 to 4.44.4.

**Comment by tresheffron** [comment]
Changing
```javascript
importer.model.destroy({
  where: { id: { [Op.in]: [del] } }
})
```
to
```javascript
importer.model.destroy({
  where: { id: { [Op.in]: del } }
})
```
fixed it. It's been like the former for a couple of years. Not sure if it's just luck that it used to work and something changed to make it more strict? Or if something else changed.

**Comment by sushantdhiman** [comment]
Correct `Op.in` supports an array, not array of arrays.
