### ISSUE TITLE
Can't save an instance with excluded primary key

### ISSUE THREAD

**Issue by phlegmatron** [sequelize/sequelize#12009]
### What are you doing?

```js
const Model = sequelize.define('table', {
      key_1: {
        type: DataTypes.STRING
      },
      key_2: {
        type: DataTypes.INTEGER
      }
    })

    const data = await Model.findOne({
      attributes: ['key_2'],
      where: {
        key_1: 'foo'
      }
    })

    data.key_2 = 5
    await data.save()
```

### What do you expect to happen?

Instance is saved.

### What is actually happening?

Error is thrown

```
'You attempted to save an instance with no primary key, this is not allowed since it would result in a global update'
```

### Environment

- Sequelize version: 5.17.2 
- Node.js version: 8.12.0 

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using mysql

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Won't be fixing this. Don't want to keep an hidden store for primary keys, which might get un-synced with attributes value. You need to include primary key in attributes to fix this.
