### ISSUE TITLE
Embed validators and remove `validator.js`

### ISSUE THREAD

**Issue by jun-sheaf** [sequelize/sequelize#12003]
## Issue Description
`validator.js` should be removed. Almost every function from `validator.js` can be made into pure regex (following RFC specs) and/or taken from `lodash`.  Moreover, `sequelize` (as far as I can see) does not embed some of the more important features of `validator.js` such as email normalization.

### Is your feature request related to a problem? Please describe.
Redundancy and bloatware.

### Describe the solution you'd like
Replace all validation functions using regex or lodash (or vanilla, but I highly doubt there will exists some dreadful parsing problem) and remove validator.js.
Another solution, which I don't recommend since validator.js is actually just bad in general, is to implement the es-modules rather than the entire package, and also remove the optional validation option and simply allow for custom validations (precisely like mongoose)

```js
 const UUIDRegEx = /^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$/
```

### Why should this be in Sequelize
Short explanation why this should be part of Sequelize rather than a separate package.
Validator.js is meant for API endpoints. An ORM such as `sequelize` should embed *some* validation, but only those required by the database. Implementing unnecessary validators when the developer is *probably* validating his/her/their own data will just cause bloating.

### Describe alternatives/workarounds you've considered
Forking the entire project and redefining everything was an option, but obviously this would imply updating would be an issue.

### Additional context
No.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, thanks for the issue, I was thinking of something like this as well.
