### ISSUE TITLE
minifyAliases does not minify through tables

### ISSUE THREAD

**Issue by Vilsol** [sequelize/sequelize#12010]
### What are you doing?

Running in postgres, if you have through tables with long names, they don't get minified alongside others.

```js
const {Sequelize} = require('sequelize');

const sequelize = new Sequelize('test', 'postgres', 'bmslsa-pwd', {
  host: 'localhost',
  dialect: 'postgres',
  minifyAliases: true
});

const User = sequelize.define('User', {});
const Address = sequelize.define('Address', {});

User.belongsToMany(Address, {
  through: 'UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding'
});

User.findAll({
  include: {
    model: Address,
  }
});
```

### What do you expect to happen?

When `minifyAliases` is true, all names in postgres should be shortened to <63 characters.

### What is actually happening?

It generates names that are longer than 63 characters.

```sql
SELECT "User"."id",
       "User"."createdAt",
       "User"."updatedAt",
       "Addresses"."id"                                                                       AS "_0",
       "Addresses"."createdAt"                                                                AS "_1",
       "Addresses"."updatedAt"                                                                AS "_2",
       "Addresses->UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding"."createdAt" AS "_3",
       "Addresses->UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding"."updatedAt" AS "_4",
       "Addresses->UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding"."UserId"    AS "_5",
       "Addresses->UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding"."AddressId" AS "_6"
FROM "Users" AS "User"
         LEFT OUTER JOIN ( "UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding" AS "Addresses->UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding"
             INNER JOIN "Addresses" AS "Addresses" ON "Addresses"."id" = "Addresses->UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding"."AddressId")
                         ON "User"."id" = "Addresses->UserAddressWithExtraNamePaddingHelloWorldWithExtraNamePadding"."UserId";
```

### Environment

- Sequelize version: master (c845f0bc4f2a51fe681a271845f22f5673725b69)
- Node.js version: v12.16.1
- Operating System: Linux

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by STEVEOO6** [comment]
I'm seeing the same problem.

The truncation leads to a `table name has been repeated error` being thrown by Sequelize. Just thought I'd mention this as others might be running into the same issue and not realising what the cause is.

e.g.
`SequelizeDatabaseError: table name "ProgramMeals->ProgramAssignedMenus->ProgramMenu->ProgramItems->" specified more than once`

**Comment by tapz** [comment]
minifyAliases: true, but still getting this with nested joins (Postgre 12):

identifier "AbcdefghijklMnopqrstuvwxy->Skills->abcdefghijkl_abcdefghijklm_skills" will be truncated to "AbcdefghijklMnopqrstuvwxy->Skills->abcdefghijkl_abcdefghijklm_s"

**Comment by eiskalteschatten** [comment]
Is there an update here? We're running into this problem as well.

**Comment by eiskalteschatten** [comment]
This is still an issue.... Any progress here?

**Comment by rbjarnason** [comment]
Any news on this? :) Everything works, but this one error message takes up large amounts of log space.

022-04-10T16:39:15.000000+00:00 app[postgres.20911]: [DATABASE] [17-1]  sql_error_code = 42622 NOTICE:  identifier "AcActivities->User->OrganizationUsers->OrganizationLogoImages->OrganizationLogoImage" will be truncated to "AcActivities->User->OrganizationUsers->OrganizationLogoImages->"

**Comment by ephys** [comment]
I reopened https://github.com/sequelize/sequelize/pull/13140
