### ISSUE TITLE
Bind parameters from queries being logged as $1, $2, etc instead of values

### ISSUE THREAD

**Issue by markjackson02** [sequelize/sequelize#12012]
## Issue Description

I am not sure if this is a BUG or FEATURE REQUEST, but when my INSERT queries get logged, they show up like this: 
```
INSERT INTO "userTokens" ("tokenId","tokenType","userId","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING *;
```
(it shows $1, $2, etc instead of the actual values that are being inserted).

### Is your feature request related to a problem? Please describe.
This makes it more challenging to debug when looking back through query history

### Describe the solution you'd like
Values should be shown instead of $1, $2, etc.

### Why should this be in Sequelize
Showing $1, $2, etc is not valuable information

### Describe alternatives/workarounds you've considered
None

### Additional context
None

### Is this issue dialect-specific?

Not sure.
- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

## Environment

I am running Sequelize v5.21.3

**Comment by sushantdhiman** [comment]
Insert query now use parameters. You can use pass `logQueryParameters: true` to sequelize constructor https://sequelize.org/v5/class/lib/sequelize.js~Sequelize.html
