### ISSUE TITLE
migrationStorageTableName is missing in types

### ISSUE THREAD

**Issue by heroic** [sequelize/sequelize#12017]
## Issue Description
migrationStorageTableName is missing in the config Options

### What are you doing?
Using Typescript

### What do you expect to happen?

migrationStorageTableName should be declared as a possible key.

### What is actually happening?

migrationStorageTableName is missing in the type.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
`migrationStorageTableName` is not a valid config option for Sequelize constructor, it is a cli only config https://github.com/sequelize/cli/blob/master/docs/README.md
