### ISSUE TITLE
sequelize.authenticate doesn't resolve with mssql DB

### ISSUE THREAD

**Issue by saurabhchourasia9** [sequelize/sequelize#12026]
Current application which uses nodejs 6.11.3/sequelize 4.43.0/sequelize-msnodesqlv8 0.2.5/msnodesqlv8 0.2.11 works fine and authenticate resolves properly but as I am upgrading node to 10.13.0, I am upgrading msnodesqlv8 to 0.6.12 as it has pre built binaries for node 10.13.0 and sequelize-msnodesqlv8 to 0.2.6-beta.8. With new combination sequelize.authenticate doesn't resolve and hangs there.

Configuration:
 dialect: 'mssql',
            dialectModulePath: 'sequelize-msnodesqlv8',
            dialectOptions: {
                connectionString: 'Driver={SQL Server};Server=XXXX\\XXXX;Database=XXXX;Trusted_Connection=yes;'
            },
            pool: {
                min: 0,
                max: 5,
                idle: 10000
            }

   try {
                let sequelize = new Sequelize(db);
                return sequelize.authenticate().then(() => {
                    log.info('xxxx');
                    this[_db] = sequelize;
                    resolve();
                }).catch(err => {
                    log.error('xxxx', err);
                    reject();
                });
            } catch (err) {
                log.error('xxxx', err);
                reject(err);
            }

- Sequelize version: 4.43.0
- Node.js 10.13.0
- Operating System: Win 7
- msnodesqlv8: 0.6.12
- sequelize-msnodesqlv8: 0.2.6-beta.8

### How does this problem relate to dialects?

- [ ] I don't know, I was using mssql, with connector library version 06.12 and database version Microsoft SQL Server 2012 11.0.7493.4 (X64)

**Comment by sushantdhiman** [comment]
4.43.0 is not supported
