### ISSUE TITLE
postgres: migrations that change enum fields do not work

### ISSUE THREAD

**Issue by realies** [sequelize/sequelize#12028]
Migrations that modify the ENUM fields do not work wheg using Sequelize 5.21.3 and Postgres 12.2-2.pgdg100+1.

```
ERROR:  type "enum_jobs_status" already exists
STATEMENT:  ALTER TABLE "jobs" ALTER COLUMN "status" DROP NOT NULL;ALTER TABLE "jobs" ALTER COLUMN "status" DROP DEFAULT;CREATE TYPE "public"."enum_jobs_status" AS ENUM('creating', 'created', 'processing', 'complete', 'failed', 'uploading');ALTER TABLE "jobs" ALTER COLUMN "status" TYPE "public"."enum_jobs_status" USING ("status"::"public"."enum_jobs_status”);
```

```
module.exports = {	
  up: (queryInterface, Sequelize) => {	
    return queryInterface.changeColumn('jobs', 'status', {	
      type: Sequelize.ENUM('creating', 'created', 'processing', 'complete', 'failed', 'uploading'),	
    });	
  },	

  down: (queryInterface, Sequelize) => {	
    return queryInterface.changeColumn('jobs', 'status', {	
      type: Sequelize.ENUM('creating', 'created', 'processing', 'complete', 'failed'),	
    });	
  },	
};
```

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by realies** [comment]
@sushantdhiman, updated

**Comment by sushantdhiman** [comment]
@realies Yes this is a known issue with migrations as they can run multiple times and code always tries to create that same enum type.

Some related issues which may help you

- https://github.com/sequelize/sequelize/pull/9641
- https://github.com/sequelize/sequelize/issues/2554
- https://github.com/sequelize/sequelize/issues/2577
- https://github.com/sequelize/sequelize/issues/7649

**Comment by realies** [comment]
@sushantdhiman, what is the official recommendation on handling this use-case? It is not clear if PRs in the aforementioned issues are going to resolve this.

**Comment by saanderson1987** [comment]
> @sushantdhiman, what is the official recommendation on handling this use-case? It is not clear if PRs in the aforementioned issues are going to resolve this.

Looks like we're still waiting for this to be officially fixed, but in the meantime, the script in the comment left by aristov on Mar 5 in [this issue](https://github.com/sequelize/sequelize/issues/7649) fixed it for me, if that helps you and others.

**Comment by danilvalov** [comment]
Thanks @zephyrosjyd and @saanderson1987 for a temporary solution. It works for me!
Direct link to the solution: https://github.com/sequelize/sequelize/issues/7649#issuecomment-662234712
