### ISSUE TITLE
Eager loading not loading all associated record for tables without primary key

### ISSUE THREAD

**Issue by rydevops** [sequelize/sequelize#12029]
## Issue Description

If you create two tables TableA and TableB where TableA hasMany TableB records but TableB does not contain a primary key (on purpose) you are unable to return more than a single TableB record when performing an eager query of TableA even though the logging shows a SELECT/JOIN that returns many records.

### What are you doing?

Here is an example model setup:
```js
class Person extends Sequelize.Model {}
Person.init({
    PersonID: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        primaryKey: true
    },
    Name: {
        type: Sequelize.STRING(255),
        allowNull: false
    }
},{
    sequelize
})

class Task extends Sequelize.Model {}
Task.init({
    TaskID: {
        type: Sequelize.INTEGER,
        allowNull: false
    },
    Description: {
        type: Sequelize.STRING(255),
        allowNull: false
    },
    PersonID: {
        type: Sequelize.INTEGER,
        allowNull: false
    }
}, { 
    sequelize,
})
Task.removeAttribute('id')  // Purposefully remove the primary key
```

The following is the association setup:
```js
Person.hasMany(Task, {
    foreignKey: "PersonID",
    sourceKey: "PersonID"
})

Task.belongsTo(Person, {
    foreignKey: "PersonID",
    targetKey: "PersonID"
})
```

The Person table contains 1 record and the Task table contains three records with the PersonID set to the ID of the only Person in the Person table. 

If the following eager query is perform only one result is returned for the task even though there are three possible entries:
```js
Person.findOne({
    where: {
        Name: "Jim Brown"
    },
    include: [Task]
}).then(person => {
    console.log(JSON.stringify(person, null, 4))
}) 
```

Result: 
```js
{
    "PersonID": 1,
    "Name": "Jim Brown",
    "createdAt": "2020-03-25T02:29:00.971Z",
    "updatedAt": "2020-03-25T02:29:00.971Z",
    "Tasks": [  // << SHOULD BE MORE
        {
            "TaskID": 1,
            "Description": "Task 1",
            "PersonID": 1,
            "createdAt": "2020-03-25T02:29:00.985Z",
            "updatedAt": "2020-03-25T02:29:00.985Z"
        }
```

If I add `raw: true` to query and change the query to `findAll`, I get three records back as if there were three Person records (which is expected):
```js
Person.findAll({
    where: {
        Name: "Jim Brown"
    },
    include: [Task],
    raw: true
}).then(person => {
    console.log(JSON.stringify(person, null, 4))
}) 
```

Result: 
```js
[
    {
        "PersonID": 1,
        "Name": "Jim Brown",
        "createdAt": "2020-03-25 02:32:59.378 +00:00",
        "updatedAt": "2020-03-25 02:32:59.378 +00:00",
        "Tasks.TaskID": 1,
        "Tasks.Description": "Task 1",
        "Tasks.PersonID": 1,
        "Tasks.createdAt": "2020-03-25 02:32:59.385 +00:00",
        "Tasks.updatedAt": "2020-03-25 02:32:59.385 +00:00"
    },
    {
        "PersonID": 1,
        "Name": "Jim Brown",
        "createdAt": "2020-03-25 02:32:59.378 +00:00",
        "updatedAt": "2020-03-25 02:32:59.378 +00:00",
        "Tasks.TaskID": 2,
        "Tasks.Description": "Task 2",
        "Tasks.PersonID": 1,
        "Tasks.createdAt": "2020-03-25 02:32:59.385 +00:00",
        "Tasks.updatedAt": "2020-03-25 02:32:59.385 +00:00"
    },
    {
        "PersonID": 1,
        "Name": "Jim Brown",
        "createdAt": "2020-03-25 02:32:59.378 +00:00",
        "updatedAt": "2020-03-25 02:32:59.378 +00:00",
        "Tasks.TaskID": 3,
        "Tasks.Description": "Task 3",
        "Tasks.PersonID": 1,
        "Tasks.createdAt": "2020-03-25 02:32:59.385 +00:00",
        "Tasks.updatedAt": "2020-03-25 02:32:59.385 +00:00"
    }
]
```

Using `findAll` doesn't make a difference in the result set if raw is set to false or omitted. 

### What do you expect to happen?

When using an eager query I am assuming the Task array should contain all three results regardless if the foreign key table has a primary key. 

### What is actually happening?

Many association is not being fully populated.

### Additional context

I have tried this with SQLite and MS SQL and get the same results on both. 

### Environment

- Sequelize version: 5.21.5
- Node.js version: 13..10.1
- Operating System: Mac OS X & RedHat Linux 7.7

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Sequelize has poor support for tables without primary key. We may fix this issue if you submit a PR but you will generally get better results if you add a primary key.
