### ISSUE TITLE
Dynamic require running after Jest is done

### ISSUE THREAD

**Issue by babramczyk** [sequelize/sequelize#12027]
## Issue Description

When testing with Jest, the dynamic require in `handshakeResult` causes Jest to spit out an error since it's happening asynchronously and after Jest is done running

### What are you doing?
Running a Jest test that includes starting up the app, which initializes a `Sequelize` instance and connects to a db.

### What do you expect to happen?

Jest runs as normal with no errors

### What is actually happening?

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at ClientHandshake.handshakeResult (node_modules/mysql2/lib/commands/client_handshake.js:145:26)
      at ClientHandshake.execute (node_modules/mysql2/lib/commands/command.js:39:22)
      at Connection.handlePacket (node_modules/mysql2/lib/connection.js:417:32)
      at PacketParser.Connection.packetParser.p [as onPacket] (node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:75:16)
```

### Additional context

Related: https://github.com/sequelize/sequelize/issues/9526

### Environment

- Sequelize version: 5.2.15
- Node.js version: 10.19.0
- Operating System: macOS 10.14.6

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using MySQL2

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
This is not related to Sequelize, it looks like `mysql2` use this to handle MySQL 8 Auth switch https://github.com/sidorares/node-mysql2/blob/master/lib/commands/client_handshake.js#L145

You can open an issue or PR with `mysql2` so this code is not dynamically imported
