### ISSUE TITLE
update doesn't work

### ISSUE THREAD

**Issue by Ladvace** [sequelize/sequelize#12025]
## Issue Description

When I try to update some value in the db with the `update` method, the value is not update

```
const Tags = sequelize.define("leaderboard", {
name: {
    type: Sequelize.STRING,
    unique: true
  },
  messages_count: {
    type: Sequelize.INTEGER,
    defaultValue: 0,
    allowNull: false
  },
  rank: {
    type: Sequelize.INTEGER,    defaultValue: 1,
    allowNull: false
  },
});const reset = await Tags.update(
        { rank: 0 },
        { where: { name: message.author.username } }
 );
```
### What do you expect to happen?
to update the value in the db

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
