### ISSUE TITLE
Postgres Generated Columns

### ISSUE THREAD

**Issue by remjx** [sequelize/sequelize#12034]
## Issue Description

PostgresQL "Generated Columns" is not possible to use in Sequelize https://www.postgresql.org/docs/12/ddl-generated-columns.html

### Describe the solution you'd like
Ability to define a column in Model with type Generated Column.

### Why should this be in Sequelize
It is standard Postgres functionality

### Describe alternatives/workarounds you've considered
My current workaround is to use hooks to update the column.

### Additional context
N/A

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): PostgreSQL

Note: there is a related issue open for MySQL: https://github.com/sequelize/sequelize/issues/7240

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
You can use `VIRTUAL` datatype to emulate this feature. I will mark this as a feature request

**Comment by mariusa** [comment]
> A virtual value that is not stored in the DB.

Note that we need to read GENERATED columns from DB, but not write them.

**Comment by mariusa** [comment]
ping

**Comment by ephys** [comment]
I'll close in favor of https://github.com/sequelize/sequelize/issues/12718
