### ISSUE TITLE
Model.update fails to escape bind `$` bind parameter when using `in` style where.

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#12039]
### What are you doing?

```
'use strict';

/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

class MyModel extends Sequelize.Model {

}
MyModel.init({
  id: {
    primaryKey: true,
    type: Sequelize.DataTypes.INTEGER
  },
  name: {
    type: Sequelize.DataTypes.STRING,
  }
}, { sequelize });

sequelize.sync().then(() => {
  return MyModel.update({ name: 'test' }, {
    where: {
      name: ['$test']
    }
  });
});
```

### What do you expect to happen?

The update should succeed.

### What is actually happening?

```
/Users/simon/projects/vendor/sequelize/test/support.js:25
  throw e;
  ^

Error: Named bind parameter "$test" has no value in the given object.
    at /Users/simon/projects/vendor/sequelize/lib/dialects/abstract/query.js:102:15
    at String.replace (<anonymous>)
    at Function.formatBindParameters (/Users/simon/projects/vendor/sequelize/lib/dialects/abstract/query.js:87:15)
    at Function.formatBindParameters (/Users/simon/projects/vendor/sequelize/lib/dialects/mysql/query.js:26:25)
    at /Users/simon/projects/vendor/sequelize/lib/sequelize.js:616:52
```

### Additional context

None.

### Environment

- Sequelize version: v5, master
- Node.js version v12, v13
- Operating System: MacOS
- If TypeScript related: TypeScript version: n/a

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ahmed-anas** [comment]
Any update on resolution for this?

**Comment by sushantdhiman** [comment]
Similar issue was fixed today by https://github.com/sequelize/sequelize/pull/12250.

This issue it still relevant, someone can use linked PR as a hint to improve that regex even further.
