### ISSUE TITLE
how to use select and extract date into month and year from timestamp in sequelize ORM?

### ISSUE THREAD

**Issue by wawasm** [sequelize/sequelize#12032]
## Issue Description

I have this query in sql:
`select to_char (created_at,'Mon') as month,
extract (year from created_at) as year,
id_activity as activity
from event
group by 1, 2, 3`

i tried to understand and make a simple sequelize query out of mysql query shown. I did something like this:
`model.findAll({ attributes: [[ sequelize.fn('extract(year)', sequelize.col('created_at')), 'data']] });`
however, it does not work. 
i played around other aggregate function using 'sum', 'min', 'max'.. it does work.
how could i resolve this?.. 
thank you so much 

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/60849911/how-to-use-select-and-extract-date-into-month-and-year-from-timestamp-in-sequeli

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [/ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [/ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
