### ISSUE TITLE
SequelizeEagerLoadingError: Categorie is not associated to Probleme!

### ISSUE THREAD

**Issue by ihebmanai** [sequelize/sequelize#12038]
Hi Sequelize comm  , i am stuck here for 3 days . and I really need your help .
i always get : SequelizeEagerLoadingError: Categorie is not associated to Probleme!
```
var express = require("express");
var router = express.Router();
const sequelize = require("../connection");
const { DataTypes } = require("sequelize");
const Probleme = require("../database/models/probleme")(sequelize, DataTypes);
const Categorie = require("../database/models/categorie")(sequelize, DataTypes);

router.get("/:id", async (req, res, next) => {
  Probleme.findOne({
    where: { id: req.params.id },
    include: [{ as: 'categorie', model: Categorie }]
  }).then(data => {
    res.json(data)
  });
});

```
and  This is my model :
 
```
"use strict";
module.exports = (sequelize, DataTypes) => {
  const Probleme = sequelize.define(
    "Probleme",
    {
      objet: DataTypes.STRING,
      description: DataTypes.STRING,
      userId: DataTypes.INTEGER,
      categorieId: DataTypes.INTEGER
    },
    {}
  );
  Probleme.associate = function (models) {
    // associations can be defined here
    Probleme.belongsTo(models.User, {
      foreignKey: "userId",
      as: "client"
    });
    Probleme.belongsTo(models.Categorie, {
      foreignKey: "categorieId",
      as: "categorie"


    });
  };
  return Probleme;
};

```

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
