### ISSUE TITLE
cannot get the 'options.model' in hook ''beforeFindAfterOptions', when the options have no include.

### ISSUE THREAD

**Issue by lioaphy** [sequelize/sequelize#12036]
## Issue Description

cannot get the 'options.model' in hook ''beforeFindAfterOptions', when the options have no include.

### my code
```js
    this['beforeFindAfterOptions'] = (options) => {
      (function flat(opt) {
        _.pull(opt.attributes, 'rowid');
        if (typeof opt.model === 'function') {
          if (hooks[opt.model.name]) {
            let option = hooks[opt.model.name](this.user);
            _.defaults(opt.where, option)
          }
        }
        if (Array.isArray(opt.include)) { opt.include.forEach(a => flat.call(this, a)) }
      }).call(this, options);
    }
```

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

```js
  static _validateIncludedElements(options, tableNames) {
    if (!options.model) options.model = this;

    tableNames = tableNames || {};
    options.includeNames = [];
    options.includeMap = {};
```

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: 5.21.5 
- Node.js version: 12 
- Operating System: Win 10
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
```js
// Hooked function is executed in model context, you can get model from that

(async () => {
  const Model = sequelize.define('Foo', {
    name: Sequelize.DataTypes.STRING
  });

  Model.addHook('beforeFindAfterOptions', function(options) {
    console.log(options);
    console.log(this);
  });

  await sequelize.sync({ force: true });

  await Model.findAll();
})();
```
