### ISSUE TITLE
Issue with `instance.reload()` when using `options.where`

### ISSUE THREAD

**Issue by franciscocardoso** [sequelize/sequelize#12046]
### What are you doing?
I'm reloading an instance with `options.where` and the [base](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L4140) is completely lost, which causes the fetch of a entirely different instance.

https://github.com/papb/sequelize-sscce/pull/69

### What do you expect to happen?
I would expect sequelize to throw a SequelizeValidationError or any other error that fits better on this situation.

### What is actually happening?

A different instance is loaded.

### Additional context

Lets consider the scenario where I have the following method:

```js
function method(instance, options) {
  await instance.reload({ lock: LOCK.NO_KEY_UPDATE, ...options });  

  // rest of the code here
  ...
}
```

If I use it like this:

```js
await method(instance, { where: { foo: 'bar' }, paranoid: false });

```

I'll endup with the method `method()` receiving an instance and handling a different one because of the reload. To fix this I would need to:

```js
await method(instance, { where: { id: instance.id, foo: 'bar' }, paranoid: false });
```

### Environment

- Sequelize version: 5.21.2
- Node.js version: v10.13.0
- Operating System: macOS Mojave (10.14.6)

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.

_**I would like to discuss which approach do you guys think is best.**_

**Comment by Americas** [comment]
Makes sense that `reload` should not accept a `where` property in its options, since the instance itself should be used for that.

Omitting it seems like a valid approach, putting the `where: this.where()` into the first object sent to `default` should solve it.
