### ISSUE TITLE
Supported versions of database drivers missing in documentation

### ISSUE THREAD

**Issue by remjx** [sequelize/sequelize#12047]
## Issue Description

I don't see anywhere in the documentation the supported versions of these packages: `pg`, `pg-hstore`, `mysql2`, `sqlite3`, `mariadb`. Postgres `pg` package was recently upgraded to version 8 and I am wondering if it is safe to upgrade.

### What was unclear/insufficient/not covered in the documentation

In the "Getting Started" section of the documentation it does not specify which versions of all the drivers are supported.  https://sequelize.org/v5/manual/getting-started.html

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by markjackson02** [comment]
Database engine support is [here](https://github.com/sequelize/sequelize/blob/master/ENGINE.md) but it does not list the corresponding npm packages.
