### ISSUE TITLE
Unclear how to update  association belongsToMany

### ISSUE THREAD

**Issue by aardudvtm** [sequelize/sequelize#12049]
## Issue Description
Unclear how to update a modal that has an belongsToMany association.

**database**
```
//USER
db.user.hasMany(db.cv);
db.cv.belongsTo(db.user);

//SKILL
db.skill.belongsToMany(db.cv, { through: 'cv_skill' });

export const db = {
    Sequelize: Sequelize,
    sequelize: sequelize,
    user: User(sequelize, Sequelize),
    cv: CV(sequelize, Sequelize),
    skill: Skill(sequelize, Sequelize),
    summary: Summary(sequelize, Sequelize), };
```

**addSkillToCV**
```
export const addSkillToCv = async (req, res) => {

    const { id, sid } = req.params;

    SKILL.findOne({id: sid}).then(function (skill) {
        //update skill here and add skill to the cv model
    });
};
```

## Question
How can I add an existing skill to the CV model? And how to delete it? I tried multiple functions on the cv model (addSkill, setSkills, ..) and nothing seems to work for me.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
