### ISSUE TITLE
Is there a sane way to search in the docs website? 

### ISSUE THREAD

**Issue by KerimG** [sequelize/sequelize#12050]
## Issue Description

The search functionality of the docs is either broken or quite frankly just bad. 

### What was unclear/insufficient/not covered in the documentation

2 examples:

When starting my Node project with Sequelize, I get the DeprecationWarning for options.operatorsAliases. Cool, but what does it actually do? Searching for it in the docs does nothing. Fine, whatever, I'll google it. 

Then I read about being able to freeze the table name so Sequelize doesn't use plurals. I find out on SO that there is an option named `freezeTableName`, I want to read the documentation entry on it before using it but again the search results in nothing. Well, it's an option used in the sequelize.define method, so I searched for "sequelize.define", again nothing. Ended up searching 'define' and clicking on the right entry, then using Ctrl+F to find the option. 

There 'freezeTableName' is mentioned exactly once without explanation or anything. Turns out it's part of the options.define object which has a reference to Model.init. 

EDIT: Another perfect example: sequelize-cli creates models with a ModelName.associate method stub. Can't find any info on that `associate` method. Ended up searching in the issues and finding [this](https://github.com/sequelize/cli/issues/65). Are the docs that difficult to edit to not include something like that in the docs after an issue has been opened?

### If possible: Provide some suggestion on how we can enhance the docs

If the problem is ReadTheDocs, ditch it. Use MKDocs or so, least it has a decent search. Right now just grepping the documentation files seems to be miles ahead of whatever the docs search can provide.

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I wouldn't mind contributing to this but how even?

**Comment by oscardianno** [comment]
I was looking at a course that apparently was released in 2018 and I noticed that many times in the lessons, the instructor opens the documentation and searches stuff and finds them effortlessly, as it was giving different results and in a much better way
![imagen](https://user-images.githubusercontent.com/46467428/107836294-38acbf80-6d62-11eb-935f-e3d42af80e4c.png)

It seems like it was using Algolia search in the past. Can it be implemented again?

**Comment by KerimG** [comment]
@oscardianno Ah, that might explain why the search is pretty much useless. That exact same search result yields this today:

![image](https://user-images.githubusercontent.com/9061713/107848094-2037b600-6df1-11eb-889f-9a70eb637841.png)

Even more hilarious example:

![image](https://user-images.githubusercontent.com/9061713/107848126-4f4e2780-6df1-11eb-88f4-cb9ee3ff6a2f.png)

It mentions "freezeTableName" on the very page I initiated the search and it can't find anything, at all.

**Comment by papb** [comment]
Hello! Thanks for this report. Sorry to take long to reply.

> I wouldn't mind contributing to this but how even?

Can you try to investigate what changed with our docs source code since 2018 so we can find out what is the cause of this regression?

**Comment by KerimG** [comment]
@papb Sure, I can try!

**Comment by rjaus** [comment]
Hey, I'm keen to give fixing search a crack (because it's been the only pain in an otherwise really great experience working with sequelize).

But I've pulled main down locally and I'm getting errors trying to compile the docs:

```
output: /home/rj/Sites/sequelize/esdoc/class/lib/data-types.js~INET.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/data-types.js~INTEGER.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/errors/instance-error.js~InstanceError.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/errors/connection/invalid-connection-error.js~InvalidConnectionError.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/data-types.js~JSONB.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/data-types.js~JSONTYPE.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/data-types.js~MACADDR.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/data-types.js~MEDIUMINT.html
output: /home/rj/Sites/sequelize/esdoc/class/lib/dialects/mssql/query-interface.js~MSSqlQueryInterface.html

SyntaxError: Invalid regular expression: /[~][Model$/: Unterminated character class
    at new RegExp (<anonymous>)
    at ClassDocBuilder._findByName (/home/rj/Sites/sequelize/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:116:20)
    at ClassDocBuilder._buildDocLinkHTML (/home/rj/Sites/sequelize/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:782:22)
    at ClassDocBuilder._buildTypeDocLinkHTML (/home/rj/Sites/sequelize/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:764:19)
    at /home/rj/Sites/sequelize/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:743:23
    at Array.map (<anonymous>)
    at /home/rj/Sites/sequelize/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:741:29
    at Array.map (<anonymous>)
    at ClassDocBuilder._buildTypeDocLinkHTML (/home/rj/Sites/sequelize/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:740:43)
    at ClassDocBuilder._buildSignatureHTML (/home/rj/Sites/sequelize/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:860:36)

```

Node Version: v12.13.0 && 14.17.4


I've gone back quite a few commits and pulled down versions, and I haven't found one that generates the docs yet.

Let me where I'm going wrong here, sure I can fix the search once I get the docs generated.
