### ISSUE TITLE
Dynamic Where Clause

### ISSUE THREAD

**Issue by scriptsure** [sequelize/sequelize#12053]
## Issue Description
I am migrating from sequelize 3.x to 5. In v3 I was able to add a dynamic where clause by creating an array out an $and/$or and using that as my where against a sequelize model. Now when I run the code I seem to get a `Invalid value`. Clearly a syntax issue but I can't seem to find it anywhere in the docs or online.

So for instance depending on the filter that enters into the function call, the array will be added to the where clause appropriately.

```
var queryOptionsObj = {where: {[Op.and]: [], [Op.or]: []}, limit: 100};

queryOptionsObj.where.[[Op.and]].push({[Op.and]: {[Op.or]: [{removeSearch: false}, {removeSearch: null}]}});
        
```

I understand the syntax is wrong but just wondering how to do it with the new style of Operator Aliases in v5.

### StackOverflow / Slack attempts

I have not tried yet, I thought asking questions about version 5 might be better asked here.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ x ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ x ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by scriptsure** [comment]
My bad is this the correct approach:

```
var queryOptionsObj = {where: {[Op.and]: [], [Op.or]: []}, limit: 100};

queryOptionsObj.where[Op.and].push({[Op.and]: {[Op.or]: [{removeSearch: false}, {removeSearch: null}]}});
```

**Comment by Awatatah** [comment]
Not sure if this answeres your question but this is how I am doing it in v5 (w/typescript)

```typescript
const Op = Sequelize.Op
let data: any[] = []
const query: any[] = []

// customer is an object of dynamically set key + value e.g. { email: 'test', lastName: 'test' }
for (const [k, v] of Object.entries(customer)) {
  // here I check if I need to do a equals query instead of LIKE
  if (validator.isUUID(v) || !isNaN(v)) {
    // push the dynamic key value to query array
    query.push({
      [k]: v
    })
  } else {
    // push the dynamic key value to query array
    query.push({
      [k]: {
        [Op.iLike]: '%' + v + '%'
      }
    })
  }
}
await Customer.findAll({
  where: {
    [Op.and]: query
  }
}).then((results: any) => {
  if (results.length > 0) {
    data = results
  }
})
return data
```

reference here: https://sequelize.org/master/manual/model-querying-basics.html#operators

**Comment by sushantdhiman** [comment]
You can build where object similarly just use `Op.operator` instead of `$operator` unlike v3
