### ISSUE TITLE
If column contains '+' in value, LIKE query does not work

### ISSUE THREAD

**Issue by Awatatah** [sequelize/sequelize#12052]
#11727  Issue Description
LIKE query where column contains `+` returns 0 results
### What are you doing?
With the below LIKE query on `customer` column `email` where email contains `+`

```typescript
const Op = Sequelize.Op
let data: any[]
await Customer.findAll({
  where: {
    [Op.and]: [
      lastName: 'test',
      email: {
        [Op.iLike]: '%some+email+test@gmail.com%'
      }
    ]
  }
}).then((results: any) => {
  if (results.length > 0) {
    data = results
  }
})
```
### What do you expect to happen?

Should result in 1 or more in `data` array

```typescript
[
  {
    lastName: 'test',
    email: 'some+email+test@gmail.com'
  }
]
```

### What is actually happening?

data is empty
```typescript
[]
```

If I set the `email` query to `[Op.iLike]: '%some%'`, then I get results.
```typescript
[
  {
    lastName: 'test',
    email: 'some+email+test@gmail.com'
  }
]
```
### Environment

- Sequelize version: 5.21.5 
- Node.js version: 12.10.0
- Operating System: MacOS Catalina 10.15.4 (19E266)
- TypeScript version: 3.7.5

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Yes, you want to escpace `+` as it is valid pattern matching operator https://www.postgresql.org/docs/9.6/functions-matching.html
