### ISSUE TITLE
Real one-to-one relationship?

### ISSUE THREAD

**Issue by codyng** [sequelize/sequelize#12055]
Hi there,

The methods "belongsTo", "hasOne" or "hasMany" are all just creating a single foreign key to the source/target, according to the document. I am wondering that if they all are real one-to-one relationship in RDBMS.

For example, from https://sequelize.org/v5/manual/associations.html#belongsto

```
class Player extends Model {}
Player.init({/* attributes */}, { sequelize, modelName: 'player' });
class Team extends Model {}
Team.init({/* attributes */}, { sequelize, modelName: 'team' });

Player.belongsTo(Team); // Will add a teamId attribute to Player to hold the primary key value for Team
```

The heading is talking about one-to-one association, suppose each Player must have one Team and one Team must have one Player.

However, as there is the foreign key teamId added to the Player model, If we have another row of player whose teamId is the duplicated as other player, it violates the one-to-one DBMS relationship.

The three methods: belongsTo, hasOne, hasMany all create one foreign key to the source/target (depends on how we call based on the source or target). It is more likely the 1 to n relationship.

Sorry I am quite confused about its one-to-one relationship. Or it has several approaches??

By this guy said: (https://vladmihalcea.com/database-table-relationships/)
"In a relational database system, a one-to-one table relationship links two tables based on a Primary Key column in the child which is also a Foreign Key referencing the Primary Key of the parent table row."

Not sure this guy mentions one of the approach, or a real one-to-one relationship is better to have two-way navigation (adding the reverse foreign key to the child model)???

Correct me if I am wrong. I just want to learn better........
Thanks!!

**Comment by sushantdhiman** [comment]
> However, as there is the foreign key teamId added to the Player model, If we have another row of player whose teamId is the duplicated as other player, it violates the one-to-one DBMS relationship.

You can enforce true one to one relationship by having using `teamId`, may be useful for some usecases.

`hasOne` or `belongsTo` in Sequelize terminology represent that one row has exactly one matching row in other table. It is not limited by other rows which can match same row on other table. Like having many players match to one team. For each player there is only one team
