### ISSUE TITLE
Request For Direction:  Exposing new maxUses pool config option

### ISSUE THREAD

**Issue by chriskchew** [sequelize/sequelize#12057]
Hello!

I have recently helped contribute a new pool configuration option `maxUses` that helps with rebalancing connections after a read-replica autoscaling event (e.g. AWS aurora).  https://github.com/sequelize/sequelize-pool/pull/18

How can I help surfacing the new config in Sequelize in terms up updating the sequelize-pool dependency version and exposing the config option?

During our testing we have been using a fork that exposes the config option, would it be helpful if we submit that to this repo as a PR?  If so, would you want that against the v5 branch, master, or both?

Thank you!

**Comment by sushantdhiman** [comment]
Hi @chriskchew 

Please add this options to here

- https://github.com/sequelize/sequelize/blob/45570b2811275617595b68d4b1df40da9ec66f38/lib/dialects/abstract/connection-manager.js#L139
- https://github.com/sequelize/sequelize/blob/45570b2811275617595b68d4b1df40da9ec66f38/lib/dialects/abstract/connection-manager.js#L207
- https://github.com/sequelize/sequelize/blob/45570b2811275617595b68d4b1df40da9ec66f38/lib/dialects/abstract/connection-manager.js#L222

Finally add documentation here
https://github.com/sequelize/sequelize/blob/45570b2811275617595b68d4b1df40da9ec66f38/lib/sequelize.js#L160

New name for this config can be `options.pool.maxUses`
