### ISSUE TITLE
Testing convenience: why not default SEQ_DB, SEQ_PW, SEQ_USER to sequelize_test?

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#12067]
It would make running the tests locally a bit less of a hassle, I don't understand why anyone would want to use anything besides `sequelize_test`, since that's the value in `docker-compose.yml`.

**Comment by sushantdhiman** [comment]
When I am testing locally I use docker based commands like

```
DIALECT=postgres npm run test-docker
DIALECT=mariadb npm run test-docker-integration
```

These commands pickup default values from `test/config/.docker.env`, so never had to supply these variables manually

**Comment by jedwards1211** [comment]
that's convenient enough...in any case would it hurt for the base tests to use defaults for these environment vars?

**Comment by sushantdhiman** [comment]
Looks like at-least username are defaulted to their database engine specific defaults. SEQ_DB already defaults to `sequelize_test`. It wont make sense to default SEQ_PW as it depends upon database setup generally.

https://github.com/sequelize/sequelize/blob/master/test/config/config.js
