### ISSUE TITLE
When findOptions has attributes, fail when  neither is a recognized option

### ISSUE THREAD

**Issue by emafriedrich** [sequelize/sequelize#12062]
A lot of times when I wont use finder functions, i wrote:

```js
let product = await models.Product.findOne({ code: aCode  });
``` 

wrongly, forgetting to put "where" before.

But sequelize doesn't fail and retrieve the first object order by id, covering a posible bug.

I think that if sequelize throw an error in this cases, or recognized this options like `where` options, it would be useful.

Thanks

PD: mi english is bad

**Comment by sushantdhiman** [comment]
I think there is always a warning on invalid options https://github.com/sequelize/sequelize/blob/b495d5ed4afc0597725c4bf56bb8382311a5a1e5/lib/model.js#L1689

Throwing won't make sense, as it is possible to call `findOne` without `where` for example
