### ISSUE TITLE
SequelizeDatabaseError: Unknown column 'table_name.field_name' in 'field list'~ On select ~ Typescript , MySQL 

### ISSUE THREAD

**Issue by alfredruhara** [sequelize/sequelize#12061]
## Issue Description

The issue is all about Unknown column 'table_name.column_name' in 'field list' -> when fetching something from the database

**Here's the whole story**

When running Sequelize on Windows environment, **everything is okay** , there's no what Am currently reporting when on Win OS. but, sudden when I pass to a linux environment now **all selection calls are failing .** the fact is why is that working on Windows Os env perfectly but when **reach On a a linux selcetions request are failing** ?

### What are you doing?

**Here a model :**
``` 
 const  Article= sequelize.define(
    'Article',
    {
      user_id {
        type: DataTypes.BIGINT(20),
        allowNull: false,
      },
      article_id: {
        type: DataTypes.BIGINT(20),
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
      },
    etc....

 },
    {
      tableName: 'articles',
      timestamps: false,
    },
    {},
  );

etc... assossiations
```
**Here is the Service** 
```
const query: string = `
        SELECT
        articles.article,
        articles.cover,
   etc.... ;
```
`

### What do you expect to happen?

Work .

### What is actually happening?

**Here a snap of the error :** 
```
SequelizeDatabaseError: Unknown column 'articles.articleid' in 'field list' ... etc
```

### Environment

- Sequelize version:  sequelize": "^5.21.3
- Node.js version:  v8.17.0
- Operating System: Linux
- If TypeScript related: TypeScript version: 3.8.3

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by alfredruhara** [comment]
issue got fixed .. if you encounter in future the same experience, open back & comment bellow .

**Comment by emiljamel** [comment]
Hi @alfredruhara , I came across this problem. can you help me? I also use mysql with Linux OS.

**Comment by alfredruhara** [comment]
@emiljamel  Can you share a screenshot of your console, the Model and services  so that I see ...

**Comment by emiljamel** [comment]
yes of course, you can see it in the question I asked here: https://stackoverflow.com/questions/63859887/sqlmessage-unknown-column-degree-teacherteachersid-in-field-list-when-i

**Comment by alfredruhara** [comment]
Have seen ~ Can you remove the case-sensitive issue before all ...

 **Degree.TeachersIdTeachersId** -> Can you fix this  to **Degree.teachersId**  , can u also check the spelling on how that field was migrated in the Database ...

**Comment by hansyahridho07** [comment]
Hi @alfredruhara I have the same issue with you. I have an issue with table payment_channels. When I create is fine, but when findOne or findAll, in payment_channel I have 11 column, but when I use method find is 13 column.
![image](https://user-images.githubusercontent.com/32156079/122364945-d45a7080-cf8c-11eb-93d9-4ac7250c6788.png)

maybe like this error:
![image](https://user-images.githubusercontent.com/32156079/122365337-29968200-cf8d-11eb-8685-31cdced26f66.png)
I have 2 extra column ChannelChannelId, PaymentPaymentId.

**Comment by hansyahridho07** [comment]
I use Linux Ubuntu 20, and database is mysql

**Comment by lashe** [comment]
> issue got fixed .. if you encounter in future the same experience, open back & comment bellow .

how was this solved please?
