### ISSUE TITLE
Setting a failover portal

### ISSUE THREAD

**Issue by perrosnk** [sequelize/sequelize#12075]
## Issue Description

One deployment in which my database is hosted is going under maintenance and I want to set a failover URL. I can't find a way to do it.
 
### Describe the solution you'd like
I would like to have the ability to set a failover URL in case the connection is stopped and can't be restarted.

```js
const db = new Sequelize(DATABASE_URL, {
  logging: false,
  pool: {
    max: 15,
    min: 1,
    idle: 10000,
    acquire: 10000,
  },
});

// URL should be set to either:
postgres://[username]:[password]@gcp-us-east1-cpu.2.dblayer.com:16070/compose
postgres://[username]:[password]@gcp-us-east1-cpu.0.dblayer.com:16070/compose

```

### Describe alternatives/workarounds you've considered
Any alternatives?

### Is this issue dialect-specific?

- [x ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
I think this should be handled by your database provider, which could proxy multiple servers behind same postgres address.

Alternatively you can modify connection config with `beforeConnect` hook. Whenever you detect failover in `beforeConnect` use alternative config
