### ISSUE TITLE
Setting variables creates parameter errors

### ISSUE THREAD

**Issue by mcampos087** [sequelize/sequelize#12076]
Sequelize is interpreting the colon operator ":=" in my query below as named parameters, which is giving me error "parameters undefined".

`sequelize.query(
      "SET @number:=0;UPDATE table SET column = (@number :=@number+1) ORDER BY id ASC;"
);`

I tried this solution on stackoverflow but it did not work:
[https://stackoverflow.com/a/59493860](https://stackoverflow.com/a/59493860)

How I can get this query working?

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
