### ISSUE TITLE
Comments in TypeScript doc are confusing

### ISSUE THREAD

**Issue by dsoegijono** [sequelize/sequelize#12081]
## Issue Description

https://github.com/sequelize/sequelize/blob/master/docs/manual/other-topics/typescript.md

### What was unclear/insufficient/not covered in the documentation

1. In the Usage section, there's this:
    ```typescript
    Project.init({
      id: {
        type: DataTypes.INTEGER.UNSIGNED, // you can omit the `new` but this is discouraged
        autoIncrement: true,
        primaryKey: true,
      },
    ```
    There's no `new` in that line nor the lines around it so I'm not sure what `new` is referring to.

2. Further down, there's this:
    ```typescript
    Address.init({
      userId: {
        type: DataTypes.INTEGER.UNSIGNED,
      },
      address: {
        type: new DataTypes.STRING(128),
        allowNull: false,
      }
    }, {
      tableName: 'address',
      sequelize: sequelize, // this bit is important
    });
    ```
    It might be helpful to add why that bit is important?

### If possible: Provide some suggestion on how we can enhance the docs

1. Maybe that comment belongs to a different line?

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, thanks for the report. Indeed the docs deserve clarification.

### 1.

It is referring to a `new` that the example itself omitted, haha :sweat_smile: `DataTypes.INTEGER.UNSIGNED` is equivalent to `new DataTypes.INTEGER.UNSIGNED()`.

This being "discouraged" is debatable, in fact I don't agree with it myself. Anyway it's best to just remove that comment, as @JuarezLustosa already did in his PR.

### 2.

> It might be helpful to add why that bit is important?

Definitely. Thanks for catching that. Suggestion:

```diff
- sequelize: sequelize, // this bit is important
+ sequelize: sequelize, // passing the `sequelize` instance is required
```

By the way this is true not only for TypeScript usage. This option is required for whatever call to `Model.init`, including pure javascript, of course. I think the goal of this comment was to emphasize the difference between the other usual model definition method, which is by calling `sequelize.define()`...

**Comment by JuarezLustosa** [comment]
@papb Changed. Thank you for supporting me.
