### ISSUE TITLE
Using updateOnDuplicate in include with bulkCreate does not work

### ISSUE THREAD

**Issue by srslyimthebest** [sequelize/sequelize#12080]
### What are you doing?
I am trying to use bulkCreate with include that has updateOnDuplicate option.

```js
await Product.bulkCreate(products, {
        updateOnDuplicate: ['name', 'description', 'subscriptionId', 'creditId'],
        include: [{
          model: Subscription,
          as: 'subscription',
          updateOnDuplicate: ['subscriptionFee', 'subscriptionReoccurrence'],
        }],
      });
```
My input is as following:
```
      const products = [
        {
          id: 70,
          subscription: {
            id: 59,
            subscriptionFee: 10,
          },
          name: 'New Plan name',
          description: '10% off',
        },
      ];
```
### What do you expect to happen?

_Nested Subscription on Product to be updated._

### What is actually happening?

_SQL is correctly generated. I am able to run it in in my database. However, I receive an internal server error where product.setSubscription is supposed to happen._

```
INSERT INTO "subscriptions" ("id","subscription_fee","created_at","updated_at") VALUES (59,10,'2020-04-07 22:33:39.324 +00:00','2020-04-07 22:33:39.324 +00:00') ON CONFLICT ("id") DO UPDATE SET "subscription_fee"=EXCLUDED."subscription_fee","subscription_reoccurrence"=EXCLUDED."subscription_reoccurrence" RETURNING *;
```
Stacktrace:
```
"TypeError: instance[include.association.accessors.set] is not a function",
" at /Users/marina.lohova/Work/graphql-server/node_modules/sequelize/lib/model.js:2663:60",
```
### Additional context

I followed the example here for bulkCreate with include https://github.com/sequelize/sequelize/pull/11307
### Environment

- Sequelize version: 5.21.4 
- PostgreSQL 10.7
- Node.js version: v12.12.0
- Operating System: MacOS Catalina 10.15.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jeffersonveloso** [comment]
Have any solution for this problem ?

**Comment by jeffersonveloso** [comment]
Have any solution for this problem ? @srslyimthebest  or @sushantdhiman
