### ISSUE TITLE
Validation hooks always runs twice on previously existed objects

### ISSUE THREAD

**Issue by baryshev** [sequelize/sequelize#12085]
https://github.com/sequelize/sequelize/blob/cf5b2f54641db263ea266e08b7bb2e5e8cd18195/lib/model.js#L3973

Even if ``hookChanged`` is an empty array this condition will be satisfied. ``if (hookChanged && hookChanged.length) { `` seems to be the right way to check this condition.

**Comment by sushantdhiman** [comment]
Related to https://github.com/sequelize/sequelize/issues/3243?

Should be easy fix by checking length of array. Closing issue for not following issue template
