### ISSUE TITLE
SequelizeConnectionError: self signed certificate

### ISSUE THREAD

**Issue by Dave3of5** [sequelize/sequelize#12083]
Using version the following versions:

    "pg": "^8.0.0",
    "pg-hstore": "^2.3.3"
    "sequelize": "^5.21.6"

I'm getting the following exception when trying to connect to a postgres db on heroku and I'm getting the above error. The code I am trying:

```
    let conString = 'postgres://senmqzvgnanlse:5493b61d735244b7662c26a49f3e55deb1699df937df66d3479f2343a69f20d1@ec2-54-197-48-79.compute-1.amazonaws.com:5432/duv1dtt8gctq9?ssl=true';
    let seq = new Sequelize(conString);
    await seq.authenticate();
```

Note that this is a dev db so I'm not bothered about leaving the connection details here. What on earth does that error mean ? I presume it's coming back from Heroku.

**Comment by sushantdhiman** [comment]
> I'm getting the following exception

Your issue does not include any stack traces? Follow the template please

--------------------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by Dave3of5** [comment]
@sushantdhiman What template are you referring to this one:

https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/other_issue.md

This doesn't ask for a stack trace I'll update the question to be exactly equal to that template.

**Comment by Dave3of5** [comment]
@sushantdhiman I have updated this to be exactly equal to the template can you re-open ?

**Comment by sushantdhiman** [comment]
@Dave3of5 this is not related to Sequelize, I think you will need to modify your server configuration to allow self signed certificates

**Comment by Mars079** [comment]
This is a problem that i faced not only with sequelize, but also with knex. The real problem is with the PG module, from the version 8+ this problem had been happening.
I installed the version 7.12.0 and the connection worked fine with both sequelize/knex.

**Comment by manoellribeiro** [comment]
dialectOptions: {
            ssl: {
                require: true,
                rejectUnauthorized: false
            }
        }
It worked for me using  sequelize 5.21.11 and pg 8.2.1

**Comment by rap2hpoutre** [comment]
@manoellribeiro Thanks! Is `require: true,` necessary? I did not see any occurrence in the documentation, I may have missed something!

**Comment by manoellribeiro** [comment]
@rap2hpoutre I'm not sure, but I think it is safer to use.

**Comment by dcsan** [comment]
this did not work for me.  DigitalOcean requires a certificate file it seems.
I don't see how changing the connection params on the client would override this?

is there a way to pass in a CA certificate with sequelize?

I also tried passing a certificate as an arg via `ca: ` param

any other options?

https://community.hedgedoc.org/t/getting-rid-of-postgresql-ssl-certificate-errors/478

**Comment by ephys** [comment]
This is all handled by `pg` through `dialectOptions` (which are passed as-is to pg), here is the relevant documentation: https://node-postgres.com/features/ssl

Here is an example of how to use these options:

```typescript
new Sequelize({
  // ... other options
  dialectOptions: {
    ssl: {
    rejectUnauthorized: false,
    ca: fs.readFileSync('/path/to/server-certificates/root.crt').toString(),
    key: fs.readFileSync('/path/to/client-key/postgresql.key').toString(),
    cert: fs.readFileSync('/path/to/client-certificates/postgresql.crt').toString(),
  },
});
```

I don't know which options are the ones you need for your issue, but if anywhere this is where you'll find them

**Comment by dcsan** [comment]
thanks so much!

do I need an `ssl: true` outside the dialect options? I saw something like the following.

also the `readFileSync` should be converted `.toString` - 
should it be read as a buffer or using an encoding option?

`{encoding:'utf8', flag:'r'});`

// const certFile = fs.readFileSync(AppConfig.getenv('certPath'));

        // ssl: true,
        // dialectOptions: {
        //     ssl: {
        //         // ca: certFile,
        //         require: true,
        //         rejectUnauthorized: false
        //     }
        // },
