### ISSUE TITLE
PostgreSQL: enumeration type declarations only found when all lowercase

### ISSUE THREAD

**Issue by princefishthrower** [sequelize/sequelize#12094]
## Issue Description

It appears that one can only declare preexisting types with Sequelize if the type is in all lowercase, even though it _**is**_ allowed in PostgreSQL to have types withVaRYINGCaseLikeThis.

### What are you doing?

Just trying to define a column in a model with a custom enumeration type (that I made separately and previously directly through pgAdmin)

Ex.: let's say I made an enumeration `Grades` and it already exists on the database, having values like 'A', 'B', 'C', and so on.

I define my model:

```js
// define model (table)
const grades = sequelize.define('grades', {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
// some more columns
        grade: {
            type: 'Grades', // won't work if enum on database is defined as 'Grades'; works fine however if it is defined as 'grades' on database
            allowNull: false,
        }
// some more columns
);

// try to create table
grades.sync({ force: true });

```

The table won't be created and Sequelize will complain: 

`SequelizeDatabaseError: type "grades" does not exist`

As soon as I change the `Grades` enumeration to `grades` on my database, it works, and the table column is correctly linked to that `grades` type.

### What do you expect to happen?

Sequelize should respect capitalization when providing a custom type (provided as a string) for the `type:` parameter.

### What is actually happening?

Creation of a table through Sequelize only works if the types created on the database are in all lowercase.

### Environment

- Sequelize version: sequelize@5.21.6
- Node.js version: v10.19.0
- Operating System: macOS Mojave
- If TypeScript related: TypeScript version: 3.8.3 (my guess is this has nothing to do with TypeScript, but I _am_ using it)

### How does this problem relate to dialects?

- [ X ] I think this problem happens only for the following dialect(s): postgres

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ X ] No, I don't have the time, although I believe I could do it if I had the time...

For now I can live with all lowercase types on my side, but fixing this bug would be greatly helpful for readability and code organization. 👍

**Comment by princefishthrower** [comment]
Correction here after more experimenting: it seems that case is respected for all but the first letter, so camelCase is respected, for example.

**Comment by princefishthrower** [comment]
All the above is true, however, when you wish to be it an array of enums, for example from my example with `grades`, trying to define `grades[]`, the entire name needs to be lowercase. Camel case won't work here.

**Comment by sushantdhiman** [comment]
I think this is because we are quoting identifiers by default. This can be disabled when initializing constructor https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html

Although that option can lead to SQL injection attacks so be sure to sanitize your user inputs

**Comment by princefishthrower** [comment]
@sushantdhiman ah, thank you!

For anyone else who finds this, this would be setting the `quoteIdentifiers` option parameter to false found in the same link as above.

I'm using this only for my own internal migrations, so the injection issue is not a problem for me.
