### ISSUE TITLE
Wrong SQL query is generated when the function 'count()` is used

### ISSUE THREAD

**Issue by theosotr** [sequelize/sequelize#12099]
## Issue Description

Sequelize generates a wrong query when function `count()` is used for a model containing a column named `count`

### What are you doing?

I have a simple model named `foo`.

```js
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('foo', {
    id: {
      type: "serial",
      allowNull: false,
      primaryKey: true
    },
    count: {
      type: DataTypes.DOUBLE,
      allowNull: false
    }
  }, {
    tableName: 'foo'
  });
};
```

I perform the following query that counts the number of records.

```js
Foo = sequelize.import('foo.js')
Foo.count({
  attributes: [
    "id",
    "count"
  ]
})
```

### What do you expect to happen?

I expected the resulting SQL query to be

```sql
  SELECT count(*) AS `count` FROM `foo` AS `foo`;
```
### What is actually happening?

Instead, the generated SQL query is

```sql
 SELECT `id`, `count` FROM `foo` AS `foo`;
```

### Environment

- Sequelize version: 5.21.5
- Node.js version: 10.19.0

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] No, I don't have the time, although I believe I could do it if I had the time...

**Comment by sushantdhiman** [comment]
Not sure if this is a bug, you can omit `attributes`. Internally `aggregate` method is used which use attributes for its own API.

Not critical, but will accept PR for a fix. Fix could be to simply set `options.attributes = []` for `Model.count` by default

**Comment by theosotr** [comment]
@sushantdhiman Thank you for your reply.

In practice, I am using `sqlite` and I need to use `attributes` because I construct a compound column which I finally use in `where` clause For example

```js
Foo.count({
  attributes: [
    [sequelize.literal('...some complex expression...'), 'count']
  ],
  where: {
    "$count$": {
      [Op.gte]: 100
    }
  }
})
```
So the problem above is that the generated query is a simple select query rather than an aggregate query (as already described in my report).

Beyond that, depending on the name of column, sequelize behaves completely differently.
For example, when I rename the compound column from `count` to a different name (let's say `foo`)

```
Foo.count({
  attributes: [
    [sequelize.literal('...some complex expression...'), 'foo']
  ],
  where: {
    "$count$": {
      [Op.gte]: 100
    }
  }
})
```
The resulting SQL query **is** an aggregate query of the form:

```sql
 SELECT <complex expression> AS `foo`, count(*) AS `count` FROM `Foo` AS `listing` WHERE `count` >= 100;
```

What are your thoughts?

**Comment by sushantdhiman** [comment]
So based on attribute `count` different query is generated, will mark this as a bug.
