### ISSUE TITLE
1:n association not work as expected

### ISSUE THREAD

**Issue by lyudad** [sequelize/sequelize#12098]
## Issue Description
```
Brand.hasMany(CountryBrand, { foreignKey: 'brand_id' });
CountryBrand.belongsTo(Brand, { foreignKey: 'brand_id' });
```

```
const testBrands = await Brand.findAll({
    attributes: [
      'id',
    ],
    include: [CountryBrand],
    raw: true,
  });
```
I have country_brand object
```
[
    {
        "id": 1,
        "CountryBrands.id": 8,
        "CountryBrands.country_id": 1,
        "CountryBrands.brand_id": 1
    }]
```
But Expect country_brand array
```
[
    {
        "id": 1,
        CountryBrands: [{
              "id": 8,
              "brand_id": 1,
              "country_id": 1
         }]   
    }]

```
### What are you doing?
```

'use strict';
module.exports = (sequelize, DataTypes) => {
  const Brand = sequelize.define(
    'Brand',
    {
      english_name: DataTypes.STRING,
      arabic_name: DataTypes.STRING,
    },
    {
      underscored: true,
      timestamps: false,
      tableName: 'brands',
    }
  );
  Brand.associate = function(models) {
    const { CountryBrand } = models;
    Brand.hasMany(CountryBrand, { foreignKey: 'brand_id' });
  };
  return Brand;
};

```
```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const CountryBrand = sequelize.define(
    'CountryBrand',
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true
      },
      country_id: DataTypes.INTEGER,
      brand_id: DataTypes.INTEGER,
    },
    {
      underscored: true,
      timestamps: false,
      tableName: 'country_brands',
    }
  );
  CountryBrand.associate = function(models) {
    const { Brand, Country } = models;
    CountryBrand.belongsTo(Brand, { foreignKey: 'brand_id' });
    CountryBrand.belongsTo(Country, { foreignKey: 'country_id' });
  };
  return CountryBrand;
};

```
```
const testBrands = await Brand.findAll({
    attributes: [
      'id',
    ],
    include: [CountryBrand],
    raw: true,
  });
```
### What do you expect to happen?

CountryBrands are array

### What is actually happening?

CountryBrands is object 

### Additional context

-

### Environment

- Sequelize version: 5.21.6
- Node.js version: 10.15.3
- Operating System: Mac 10.14.6 
- If TypeScript related: TypeScript version: no

## Issue Template Checklist

-

### How does this problem relate to dialects?

- [x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Remove `raw: true,`
