### ISSUE TITLE
Cannot find module './../type-helpers/set-required'

### ISSUE THREAD

**Issue by ynhhoJ** [sequelize/sequelize#12109]
## Issue Description
It seems bug from: https://github.com/sequelize/sequelize/issues/11973 is not resolved yet.
### What are you doing?
I'm using typescript with sequelize `v6.0.0-beta.5`.
Code:
```ts
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize('db', 'username', 'password', {
    host: 'localhost',
    dialect: 'postgres',
    pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000
    }
});

sequelize
    .authenticate()
    .then(() => {
        console.log('Connection has been established successfully.');
    })
    .catch((err: string) => {
        console.error('Unable to connect to the database:', err);
    });

export default sequelize;
```

### What do you expect to happen?

Resolve error.

### What is actually happening?

On `tsc --noEmit` i get this error:
```
node_modules/sequelize/types/lib/query-interface.d.ts(7,29): error TS2307: Cannot find module './../type-helpers/set-required'
```

### Environment

- Sequelize version: 6.0.0-beta.5 
- Node.js version: 12.8.0 
- Operating System: Windows 10, v1909
- If TypeScript related: TypeScript version: 3.6.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, in fact there has been no version release yet, PR #12000 was merged after v6.0.0-beta.5.

If you need this asap, you can install directly from the github commit tarball:

```
npm install https://github.com/sequelize/sequelize/tarball/9785c585de010dca015b345dab9caa6b27f952a3
```

Thanks!
