### ISSUE TITLE
Large float values are lost when inserted

### ISSUE THREAD

**Issue by saifalhaneefa** [sequelize/sequelize#12100]
**Issue Description**
When inserting large float values , the values get corrupted.

**What are you doing?**
Trying to insert large float values into a FLOAT-type column. For example: 12345678.67733

**What do you expect to happen?**
The large value is correctly stored on the database.

**What is actually happening?**
Some corrupted values are stored
version : 5.21.3

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/12086

**Comment by saifalhaneefa** [comment]
Thank you, When will be it available ? I can see that it is not resolved in **5.21.6**. Can you refer the version ?
