### ISSUE TITLE
Memory Leak when using bulkCreate|create and mssql dialect

### ISSUE THREAD

**Issue by Dimesio** [sequelize/sequelize#12105]
What you are doing?
I am attempting the creation of 10 rows in my database using bulkCreate. I also performed this manually with multiple creates called and still had memory issues as well. This is for 10 items to add to the DB, none of which hold more than ~50KB of information a piece.

```models.Users.sync().then(() => {
    var ohsnap = []
    for (i=1;i++;i<10){
        var fname = faker.name.firstName()
        var lname = faker.name.lastName()
        var SAMAccountName = lname+"."+fname
        var DN = "CN="+SAMAccountName+",OU=something,OU=Users,OU=something,OU=com"
        var OU = "OU=something,OU=Users,OU=something,OU=com"
        ohsnap.push({
            //'UserId': faker.random.number(),
            'StatusId': faker.random.number(),
            'FirstName': fname,
            'LastName': lname,
            'DisplayName': lname+"_"+fname,
            'Description': faker.name.jobDescriptor(),
            'SAMAccountName': SAMAccountName,
            'AccountSID': faker.random.uuid(),
            'DistinguishedName': DN,
            'OriginalOU': OU,
            'CurrentOU': faker.fake("OU={{company.companyName}},OU=Users,OU=something,OU=com"),
            'EmailAddress': faker.internet.email()
    })}
    models.Users.bulkCreate(ohsnap)
})
```

What do you expect to happen?

I expect that my mssql DB will have 10 fake entries

What is actually happening?

node takes up 4.5GB RAM (from around 300mb) before crashing

Which dialect you are using (postgres, mysql etc)?

mssql

Which sequelize version you are using?

sequelize@5.21.6

**Comment by christianbundy** [comment]
What was the resolution here? I'm experiencing something similar with SQLite.

**Comment by Dimesio** [comment]
yeap, a bit new to JS, so my line: `for (i=1;i++;i<10){` basically created an infinite loop filling the list of items until everything crashed..turns out to be my mistake rather than an issue with Sequelize.
