### ISSUE TITLE
options.pool.validate doesn't work as expected in case of AWS RDS Failover

### ISSUE THREAD

**Issue by monothorn** [sequelize/sequelize#12104]
## Issue Description

`options.pool.validate` is called only for _non_-SELECT queries which causes error in the following raw query to get the next sequence id 

- sequelize v5.x
- postgres dialect
- postgres sequence - `post_seq`
- query that fails - `select nextval(post_seq)`
- error in nodeJS application log- `SequelizeDatabaseError: cannot execute nextval() in a read-only transaction\n`
- pool configuration used - 

```
{
      max: 10,
      min: 1,
      acquire: 30000,
      idle: 10000,
      validate: async pgClient => {
        const result = await pgClient.query('SELECT pg_is_in_recovery()');
        const isReadOnly = result.rows[0].pg_is_in_recovery;
        console.log(isReadOnly, 'isReadOnly:src/utils/db.js')
        return !isReadOnly;
      }
    }
```

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/61204439/options-pool-validate-in-sequelize-node-js

### Additional context
- We are using cluster writer endpoint to connect to RDS in NodeJS application 
- When the failover happens, we notice the error as shared above. Now if `options.pool.validate` was called for the query shared above , sequelize would be able to discard the connection because of the pool configuration we are using. But that doesn't seem to be happening at all.
- `SELECT pg_is_in_recovery()` returns _true_ for a read-only connection. We use this to let sequelize figure out which connections need to be discarded.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by monothorn** [comment]
@sushantdhiman  @felixfbecker

**Comment by sushantdhiman** [comment]
`pool.validate` is a [synchronous](https://github.com/sequelize/sequelize-pool/blob/04a098b73472a60f3c91df13f870a156d34e49b4/lib/Pool.js#L19) function. It won't work like this. You can catch `pool is in recovery` errors with `options.retry` and retry them, but I don't think that is what you are looking for.

Not sure if this work for you but you can issue this query in `validate` and set a flag on connection. Then use that flag to synchronously determine validity of connection next time.

```js
validate: connection => {
   connection.query('check validity' ).then(result => {
     connection.isValid = !!result; // set validity based on result, as per your logic
  });

  return connection.isValid;
}
```

Other option could be to empty all connections from pool when failover happens

**Comment by monothorn** [comment]
@sushantdhiman Let me try the first approach and get back to you. This would just take a tad bit since it requires some time to get this DR setup on the instance. 

Regarding 2nd approach of emptying connections from pool when failover happens, could you refer me to some documentation..  that clarifies how to do this in sequelize?

**Comment by monothorn** [comment]
Also my bad if i wasn't clear earlier, my concern is specifically with `options.pool.validate` not being called for SELECT queries because in case of `select nextval(post_seq)` , it's not just a select query but also modifies the sequence table in the post gres side which would be impossible to do in case of read-only conn. 
Now, since sequelize is unable to check the validity of the connection (through options.pool.validate), this nextval query is allowed to execute against read-only DB leading  to error  

`SequelizeDatabaseError: cannot execute nextval() in a read-only transaction\n`

First of all , please confirm if my observation here is correct?
If _yes_, then I am not sure if going with the first approach you suggested in your comment would prove useful in determining the validity of conn. 
If _no_, let me know how to confirm that it's still working since I am not able to reproduce the expected behavior.

**Comment by sushantdhiman** [comment]
> Regarding 2nd approach of emptying connections from pool when failover happens, could you refer me to some documentation.. that clarifies how to do this in sequelize?

[pool.destroyAllNow](https://github.com/sequelize/sequelize-pool/blob/04a098b73472a60f3c91df13f870a156d34e49b4/lib/Pool.js#L508)

> First of all , please confirm if my observation of options.pool.validate being called only for connection that's used for non-SELECT queries here is correct?

`validate` has nothing do with type of queries, it is only [executed](https://github.com/sequelize/sequelize-pool/blob/04a098b73472a60f3c91df13f870a156d34e49b4/lib/Pool.js#L243) when a connection which was earlier returned to pool is being acquired once again. It is just a way to test if idle sitting connection is reusable.

**Comment by monothorn** [comment]
@sushantdhiman Oh Ok, that clarifies a lot about `options.pool.validate`. Now going by the theory, we have rejected the earlier approach and I am trying to use [Hooks](https://sequelize.org/master/manual/hooks.html) for this use-case

Code that I have tried this with in my local setup - 

```
const Sequelize = require('sequelize');
const instance = new Sequelize(uri, options);
  instance.addHook('beforeQuery', async (conn, config) => {
    const res = Math.random() >= 0.5; // this is to simulate the response from pg_is_in_recovery query 
    if (res) {
      await auroraDb.connectionManager.pool.destroyAllNow(); //destroys all connections if pg_is_in_recovery returns true 
    }
  })
```

Just to clarify what I have done here - 
1.`beforeQuery` Hook will be running before making any query 
2. Removed `validate` from pool config as it's only working on idle connections and not really on the new connections that are/were created as per your comment above
3.  if pg_is_in_recovery returns true for any connection, it means it's a read-only connection and we are pro-actively deleting all the connections from the pool using [pool.destroyAllNow](https://github.com/sequelize/sequelize-pool/blob/04a098b73472a60f3c91df13f870a156d34e49b4/lib/Pool.js#L508)
4. after deleting all the connections, fresh connections are expected to be made and these will again through the same hook before running any query
5. The reason for discarding read-only connections, which might already be clear, is that majority of our queries in any API request involve some kind of non-_SELECT_ operation.

**Comment by sushantdhiman** [comment]
> My only concern now is with the efficiency of this in a production environment?

I can't say anything as it is your environment specific. Emptying all connections might give your reduced performance. Perhaps remove just that connection.

**Comment by saurabhray91** [comment]
@sushantdhiman  I have both , removing all the connections & just one connection but looks like it's not working as expected  

Code that I have tried with - 

```
 const seq = new Sequelize(uri , options);
  seq.addHook('beforeQuery', async (conn, Query) => {
    try {
      const res = await Query.connection.query('SELECT pg_is_in_recovery()');
      const isReadOnly = res.rows[0].pg_is_in_recovery;
      console.log(isReadOnly, 'isReadOnly:src/utils/db.js');
      if (isReadOnly) {
        console.log(
          Query.sequelize.connectionManager.pool._availableObjects.length,
          'count of objects that will be destroyed'
        );
        await Query.sequelize.connectionManager.pool.destroyAllNow();
      }
    } catch (err) {
      console.log(err);
    }
  });
```

The response that we see in the logs is as follows -

```
true 'isReadOnly:src/utils/db.js'
0 'count of objects that will be destroyed'
2020-04-20T12:51:05.440Z sequelize:sql:pg Executing (default): select nextval('schem.post_seq')
Executing (default): select nextval('schem.post_seq')
{"scope":"controller","errorName":"SequelizeDatabaseError","stackTrace":"SequelizeDatabaseError: cannot execute nextval() in a read-only transaction\n"   }
```

**Comment by monothorn** [comment]
@sushantdhiman  I have tried both, removing all the connections & a single connection but looks like it's not working as expected  

Code that I have tried with - 

```
 const seq = new Sequelize(uri , options);
  seq.addHook('beforeQuery', async (conn, Query) => {
    try {
      const res = await Query.connection.query('SELECT pg_is_in_recovery()');
      const isReadOnly = res.rows[0].pg_is_in_recovery;
      console.log(isReadOnly, 'isReadOnly:src/utils/db.js');
      if (isReadOnly) {
        console.log(
          Query.sequelize.connectionManager.pool._availableObjects.length,
          'count of objects that will be destroyed'
        );
        await Query.sequelize.connectionManager.pool.destroyAllNow();
        // await Query.sequelize.connectionManager.pool.destroy(Query.connection);
      }
    } catch (err) {
      console.log(err);
    }
  });
```

The response that we see in the logs is as follows -

```
true 'isReadOnly:src/utils/db.js'
0 'count of objects that will be destroyed'
2020-04-20T12:51:05.440Z sequelize:sql:pg Executing (default): select nextval('schem.post_seq')
Executing (default): select nextval('schem.post_seq')
{"scope":"controller","errorName":"SequelizeDatabaseError","stackTrace":"SequelizeDatabaseError: cannot execute nextval() in a read-only transaction\n"   }
```
