### ISSUE TITLE
I can't add extra column value in a pivot table

### ISSUE THREAD

**Issue by gabrielklose** [sequelize/sequelize#12107]
## I can't add extra column value in a pivot table

**Class Mergulhador:**

```js
import Sequelize, { Model } from 'sequelize';
class Mergulhador extends Model {
  static init(sequelize) {
    super.init(
      {
        nome: Sequelize.STRING,
        cpf: Sequelize.STRING,
        email: Sequelize.STRING,
      },
      { tableName: 'mergulhador', sequelize }
    );
    return this;
  }
  static associate(models) {
    this.belongsToMany(models.FormularioSaude, {
      through: 'mergulhador_formulariosaude',
      as: 'formulariosaude',
      foreignKey: 'mergulhador_id'
    });
  }
  
}
```

**Class FormularioSaude:**

```js
import Sequelize, { Model } from 'sequelize';
class FormularioSaude extends Model {
  static init(sequelize) {
    super.init(
      {
        pergunta: Sequelize.STRING
      },
      { tableName: 'formulariosaude', sequelize }
    );
    return this;
  }
  static associate(models) {
   this.belongsToMany(models.Mergulhador, {
      through: 'mergulhador_formulariosaude',
      as: 'mergulhadores',
      foreignKey: 'formulariosaude_id'
    });
  }
  
}
```
### Scenario

```js
if (req.body.formulariosaude !== undefined) {
    mergulhador.addFormulariosaude(req.body.formulariosaude, {
        through: { resposta: true }
     });
}
```

## Insominia send:{ "formulariosaude": [1,2] }

# Result
![image](https://user-images.githubusercontent.com/26801238/79268962-03012680-7e72-11ea-8938-126ee7d4db8e.png)

### Environment

- Sequelize version: @5.21.5 
- Node.js version: 12.14.1 
- Operating System: MacOS catalina

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Can you try `setFormulariosaude` instead of `addFormulariosaude`?
