### ISSUE TITLE
Waiting for database readiness after 'docker-compose up -d'

### ISSUE THREAD

**Issue by multum** [sequelize/sequelize#12103]
## Description

Recently I ran into the problem of using databases right after the launch of containers. At the time of starting the tests, the database is not yet ready. I spied a solution to the problem in [Sequelize repo](https://github.com/sequelize/sequelize) :grin:

It suited me too. But the `giorgos/takis` interface seemed to me incomplete and poorly parameterized :pensive:

I found in the article https://docs.docker.com/compose/startup-order a good alternative - [jwilder/dockerize](https://hub.docker.com/r/jwilder/dockerize)

Advantages:

1. informative logs
2. `-timeout` option to cancel long wait
3. great interface

I think it will make `CI` better

```bash
"if [ $MYSQL_VER ]; then docker run --net sequelize_default jwilder/dockerize -wait tcp://${MYSQL_VER}:3306 -timeout 2m; fi"
```

> [_My solution_](https://github.com/multum/metalize/blob/master/.github/workflows/test.yml#L20)

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
I will welcome PR with this change, I am closing this issue. Thanks
