### ISSUE TITLE
MySQL Syntax Error: Functions in DEFAULT Constraint must be wrapped in parentheses

### ISSUE THREAD

**Issue by DRKSLV** [sequelize/sequelize#12102]
## Issue Description
Built-In Function Calls within MySQL Default constraints must be enclosed in parantheses, sequelize omits these and causes a SyntaxError.

### What are you doing?
I am trying to use a built-in db function within a default constraint. (MySQL Inno-DB)

```js
const foo = sequelize.define("foo", {
    uuid: {
        type: "BINARY(16)",
        defaultValue: Sequelize.fn("UUID_TO_BIN", Sequelize.fn("UUID")),
        primaryKey: true
    }
}, { 
    timestamps: false //to simpify the query generated
});
```

### What do you expect to happen?
As described in [this answer](https://stackoverflow.com/a/52769071) SQL-Functions within the Default Constraint must be enclosed by parentheses. If they are added to the output below, the query completes successfully.
(Running `INSERT INTO foos () VALUES ();` shows the constraint is working)

### What is actually happening?
The Output misses the required Parentheses enclosing the Function Calls, as seen below:

```
Executing (default): 
CREATE TABLE IF NOT EXISTS `foos` 
(
`uuid` BINARY(16) 
DEFAULT UUID_TO_BIN(UUID()) , 
PRIMARY KEY (`uuid`)
) ENGINE=InnoDB;
```

### Environment

- Sequelize version: 5.21.6
- Node.js version: 12.14.0
- Operating System: Windows 10 Home (1909)

### How does this problem relate to dialects?

- [ ] I don't know, I was using MySQL (InnoDB), with connector library version 2.1.0 and database version 8.0.17 (MySQL Community Server -GPL)

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by DRKSLV** [comment]
changing line 364 in sequelize\lib\dialects\mysql\query-generator.js to:
```template += ` DEFAULT (${this.escape(attribute.defaultValue)})`;```
seemes to have fixed this issue for me.

i dont know if this issue e xists in other dialects or if this "fix" creates other problems.
unfortunately i dont have the means to investigate this further.

**Comment by FawzyMokhtar** [comment]
@DRKSLV , I came out with a temporary solution that will work for you until this bug is fixed.

You can use the `Sequelize.literal` function instead of `Sequelize.fn` function since your are not passing any external parameters to the `UUID_TO_BIN` function.
So, in your case it should be
```javascript
const foo = sequelize.define(
  'foo',
  {
    uuid: {
      type: 'BINARY(16)',
      defaultValue: Sequelize.literal('(UUID_TO_BIN(UUID()))'),
      primaryKey: true
    }
  },
  {
    timestamps: false
  }
);
```
**Now** the value `(UUID_TO_BIN(UUID()))` will be passed to the **MySQL Server** as it is.
This is described here in [MySQL Docs](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html).

And you will have this SQL statement generated.
```SQL
CREATE TABLE IF NOT EXISTS `foo` 
(
  `uuid` CHAR(16) DEFAULT (UUID_TO_BIN(UUID())) 
)
```

**Comment by DRKSLV** [comment]
@FawzyMokhtar
This is a great temporary solution!

As of Updates: my adjustment to the source code as described above has so far not caused any issues for me. 
I think _all_ Values in the default clause can be enclosed in parentheses without negative Effects.

If someone with more Knowledge of the libraries internal workings could look over this and run the tests, we could resolve this issue fairly quickly

**Comment by FawzyMokhtar** [comment]
@DRKSLV, I can confirm that your solution will not break other usages of `Sequelize.fn` function, As below
```javascript
fooInstance.update({
   username: Sequelize.fn('upper', Sequelize.col('username'))
});
```
This will create an SQL update statement like this.

```SQL
UPDATE foos 
    SET username = UPPER(username)
WHERE id = 1;
```
And with your solution it will be

```SQL
UPDATE foos 
    SET username = (UPPER(username))
WHERE id = 1;
```
The syntax differs but the result is the same.

**Note**

> Changing the source of a third-part package is not an optimal solution as every time you run 
`npm i` or `yarn`
you will get a fresh copy of package source code which unfortunately doesn't includes your solution. 

I suggest you go with my temp solution until it officially gets updated.
