### ISSUE TITLE
--local-infile connection

### ISSUE THREAD

**Issue by scriptsure** [sequelize/sequelize#12119]
## Issue Description
I have upgraded to the latest version of sequelize and as a result had to upgrade to mysql2. I am performing simple load data calls like this:
```
LOAD DATA LOCAL INFILE '/home/ubuntu/sites/load/60_6221eba7-4271-4c15-bfc3-63157e6a3475.txt' INTO TABLE import FIELDS TERMINATED BY '|'
```

### What was unclear/insufficient/not covered in the documentation

Write here.
I do have the local-infile enabled on the server. BUT i cannot figure out to enable the flag on the connection client as well... for example a client connection on the command line would look like this:
```
mysql -h xxx -u xxx -p --local-infile dbname
```
If after i connect i make the load data call it works fine.  

### If possible: Provide some suggestion on how we can enhance the docs

Write here.
I just need to know how i pass the --local-infile flag to the connection options for sequelize?

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ x ] Yes. This issue only applies to the following dialect(s): MySql
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ X ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
https://github.com/sidorares/node-mysql2/issues/919#issuecomment-615563222

**Comment by sushantdhiman** [comment]
I think this has been sufficiently answered. You can set flags and hook into connections to pass inline data as mentioned in linked thread
