### ISSUE TITLE
 Accessing properties when querying with aggregation returns undefined

### ISSUE THREAD

**Issue by pperezp306** [sequelize/sequelize#12118]
## Issue Description

When i want to access to the properties if the next query, im getting undefined values, but if i print it in the screen it displays the correct values, I thought it was for doing 2 queries at the same time, but it was not, doing the same exercise as the unique query i had the same issues

### Controller code
const devicesPromise = Devices.findAll();
    const statusesPromise = Devices.findAll({
                        attributes: [
                                        [sequelize.fn('SUM', sequelize.literal('CASE WHEN connState=0 THEN 1 ELSE 0 end')), 'desconectados'],
                                        [sequelize.fn('SUM', sequelize.literal('CASE WHEN connState=1 THEN 1 ELSE 0 end')), 'conectados'],
                                        [sequelize.fn('SUM', sequelize.literal('CASE WHEN connState=2 THEN 1 ELSE 0 end')), 'peligro'],
                                        [sequelize.fn('SUM', sequelize.literal('CASE WHEN connState=3 THEN 1 ELSE 0 end')), 'inactivos']
                                    ]
                    });
    const [devices, statuses] = await Promise.all([devicesPromise, statusesPromise]);

### Additional context
Does anyone had the same issue?,Could you solve it?

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
