### ISSUE TITLE
Model.init discrepancy between docs and type defs

### ISSUE THREAD

**Issue by sam-dt** [sequelize/sequelize#12112]
## Issue Description

API Reference states that Model.init returns Model. The model.d.ts file definition states that it returns void. This causes the TypeScript compiler to error when e.g. calling a method on the returned Model.

### Additional context

![image](https://user-images.githubusercontent.com/53523625/79462190-784a3400-7ff7-11ea-9ffc-e04a948c3cbe.png)

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): TypeScript
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please submit a PR if you can spare some time.
