### ISSUE TITLE
Large float values are lost when inserted

### ISSUE THREAD

**Issue by shameer-m** [sequelize/sequelize#12111]
Issue Description
When inserting large float values , the values get corrupted.
What are you doing?
Trying to insert large float values into a FLOAT-type column. For example: 12345678.67733
What do you expect to happen?
The large value is correctly stored on the database.
What is actually happening?
Some corrupted values are stored
version : 5.21.3 and When will be it available ? I can see that it is not resolved in 5.21.6. Can you refer the version ?
When will be it available ? I can see that it is not resolved in 5.21.6. Can you refer the version ?

**Comment by sushantdhiman** [comment]
Please check for issue before reporting it

https://github.com/sequelize/sequelize/issues/12100
https://github.com/sequelize/sequelize/issues/12086

It is fixed in master. If you want to port this over to v5, submit a PR

**Comment by shameer-m** [comment]
When will be it available ? I can see that it is not resolved in 5.21.6. Can you refer the version ?

**Comment by shameer-m** [comment]
> Please check for issue before reporting it
> #12100
> #12086
> It is fixed in master. If you want to port this over to v5, submit a PR

When will be it available ? I can see that it is not resolved in 5.21.6. Can you refer the version ?

**Comment by sushantdhiman** [comment]
> When will be it available ? I can see that it is not resolved in 5.21.6. Can you refer the version ?

It is fixed in master. If you want to port this over to v5, submit a PR

**Comment by shameer-m** [comment]
> When will be it available ? I can see that it is not resolved in 5.21.6. Can you refer the version ?
> 
> It is fixed in master. If you want to port this over to v5, submit a PR

When will be it available ? I can see that it is not resolved in latest release 5.21.7 . 
As mentioned It seems that it is fixed on 04573fd and is in master .Are you planning on integrating that into v5? We need it urgently.

**Comment by sushantdhiman** [comment]
I am not going to port this over to v5, as I have already told you.

"**It is fixed in master. If you want to port this over to v5, submit a PR**"

PS - http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/index.html#catbmain

**Comment by shameer-m** [comment]
Issue is resolved in new release v5.21.12.
Thanks firefueled and sushantdhiman to resolve issue.
