### ISSUE TITLE
Postgres connection URI not escaped

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#1212]
The PostgreSQL [connection string](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L585) isn't URI encoded. So if, for example, your password contains a character that should be escaped, you'll get an error in pg: 

    error: password authentication failed for user "foo"

**Comment by BridgeAR** [comment]
This is solved and can be closed
