### ISSUE TITLE
Include with required=true doesn't works

### ISSUE THREAD

**Issue by rogerrafael7** [sequelize/sequelize#12133]
## Issue Description
I'm trying do execute the findAll method using includes with required=true. The sql dynamically created by sequelize did correct, but the result did not.

### What are you doing?

I have two Models: ModelA `hasMany` ModelB, then I'm trying this code:
```
ModalA.findAll({
include: [
  {
    "required":true,
    "model": ModelB,
    "as":"itens",
    "limit":1,
    "attributes":["id", "cardapioPrincipal"],
     "where":{
          "cardapioPrincipal":1
      }
    }
  ]
})
```

The SQL generated is correct! I did copy the SQL and paste into psql, and run it successfully! Just 4 itens has been returned! Perfect!

BUT! The findAll method returned ALL itens(approximately 10)! 

I noticed a other SQL executed before, and that no contains my filters and parameters of include. In this second SQL already contains. In other words, two SQLs did executed with just one call findAll!

First SQL:
```
SELECT "ModalA"."id", "ModalA"."hora_criacao" AS "horaCriacao", "ModalA"."nome", "ModalA"."descricao" FROM "gestao_pedidos"."tb_categoria" AS "ModalA";
```

Second SQL:
```
SELECT "ModelB".*
FROM (SELECT *
      FROM (SELECT "id", "id_categoria"
            FROM "gestao_pedidos"."tb_cardapio_item" AS "ModelB"
            WHERE ("ModelB"."cardapio_principal" = 1)
              AND "ModelB"."id_categoria" = 1
            LIMIT 1) AS sub
      UNION ALL
      SELECT *
      FROM (SELECT "id", "id_categoria"
            FROM "gestao_pedidos"."tb_cardapio_item" AS "ModelB"
            WHERE ("ModelB"."cardapio_principal" = 1)
              AND "ModelB"."id_categoria" = 2
            LIMIT 1) AS sub
      UNION ALL
(...too larger)
```

### What do you expect to happen?
Exists 10 itens, I expected 4 itens and not 10. The SQL(with Unions) return 4 itens, but the findAll method return 10

### What is actually happening?

The SQL did returned a result and sequelize has been returned other

### Additional context

![image](https://user-images.githubusercontent.com/3722299/79700286-01b56c80-826b-11ea-956d-b4bbfe8cfb68.png)

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
> Sequelize version: XXX
Node.js version: XXX
Operating System: XXX

Please provide all details

**Comment by papb** [comment]
I see you edited the details in, thanks. Can you please go one step further and create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) showing your issue directly? We maintainers are overloaded with issues, please help us help you, thanks!
