### ISSUE TITLE
How to query by foreign key without explicitly specifying alias?

### ISSUE THREAD

**Issue by acidos** [sequelize/sequelize#12143]
I have the following associations in Sequelize model

```
class Bet extends Model {};
class User extends Model {};

User.hasMany(Bet);
Bet.belongsTo(User);
```

This creates UserId FK column in Bet table, but I really don't want to care how Sequelize will name it.

Now having in hand User instance I want to query a single Bet row, where its UserId foreign key column equals to id from instance.

The query should not be converted to LEFT or other JOIN. I would like to have a query similar to `SELECT * FROM Bets WHERE UserID = 6`

I've tried to use include but it's always causing joins, which is not what I want. So the only way I know is
```
Bet.findOne({
    where: {
        UserId: user.id
    }
});
```

but I want to avoid using explicit foreign key column name.

Question: How to query a table containing foreign key column without specifying column name and without joins.

**Comment by sushantdhiman** [comment]
`user.getBets()` read docs https://sequelize.org/master/manual/assocs.html#-code-foo-hasmany-bar---code-

**Comment by acidos** [comment]
@sushantdhiman I rather need `user.getBet()` because the fk is in the `Bet` table. This doesn't work giving me `user.getBet is not a function` despite the documentation have relevant example:

```
Ship.belongsTo(Captain); 
const ship = Ship.findOne();
console.log((await ship.getCaptain()).toJSON());
```
This is exactly what I want, but I guess it's not available in v5, right?

`user.getBets()` returning an array, but there is no `many` connection so it's supposed to be singular, unless I have to do something in addition to make `user.getBet()` work in v5.
