### ISSUE TITLE
include.model.getTableName is not a function

### ISSUE THREAD

**Issue by LuisBuelvas** [sequelize/sequelize#12149]
I am using the documentation to query between associated tables, this is my model of the two tables
Model City
"use strict";
module.exports = (sequelize, DataTypes) => {
const City = sequelize.define(
"City", {
name: DataTypes.STRING,
divipola: DataTypes.STRING,
stateId: DataTypes.INTEGER,
}, {}
);
City.associate = function(models) {
City.belongsTo(models.State, {
as: "state"
});
City.hasMany(models.Person);
City.hasMany(models.Infringement);
};
return City;
};

Model State
'use strict';
module.exports = (sequelize, DataTypes) => {
const State = sequelize.define('State', {
name: DataTypes.STRING
}, {});
State.associate = function(models) {
State.hasMany(models.City)
};
return State;
};

and this is the query code guiding me from the documentation

City.findAll({
attributes: ["id", "name", "divipola", "stateId"],
where: { stateId: idState },
include: [{
attributes: ["id", "name"],
model: "state"
}]

});

giving this result
"include.model.getTableName is not a function"

someone who can help me with this

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please provide clear reproduction as an SSCCE, https://github.com/papb/sequelize-sscce
