### ISSUE TITLE
"include.model.getTableName is not a function"

### ISSUE THREAD

**Issue by LuisBuelvas** [sequelize/sequelize#12147]
## Issue Description

I am using the documentation to query between associated tables, this is my model of the two tables
Model City
"use strict";
module.exports = (sequelize, DataTypes) => {
    const City = sequelize.define(
        "City", {
            name: DataTypes.STRING,
            divipola: DataTypes.STRING,
            stateId: DataTypes.INTEGER,
        }, {}
    );
    City.associate = function(models) {
        City.belongsTo(models.State, {
            as: "state"
        });
        City.hasMany(models.Person);
        City.hasMany(models.Infringement);
    };
    return City;
};

Model State
'use strict';
module.exports = (sequelize, DataTypes) => {
    const State = sequelize.define('State', {
        name: DataTypes.STRING
    }, {});
    State.associate = function(models) {
        State.hasMany(models.City)
    };
    return State;
};

and this is the query code guiding me from the documentation

City.findAll({
        attributes: ["id", "name", "divipola", "stateId"],
        where: { stateId: idState },
        include: [{
            attributes: ["id", "name"],
            model: "state"
        }]

 });

giving this result
"include.model.getTableName is not a function"

someone who can help me with this

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/12149#issuecomment-619330452
