### ISSUE TITLE
eslint --fix unskips tests

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#12151]
I had been wondering why that SQLite DAO test that was skipped in master kept reappearing and failing again in my PRs, like a zombie...turns out it's because `eslint --fix` removes the `.skip` from `it.skip`.

This is easy to miss (if I even noticed changes in that file I probably assumed it just got a formatting fix) so I think we should disable it.

**Comment by sushantdhiman** [comment]
disabling eslint with a line should fix it

**Comment by jedwards1211** [comment]
That's true...I don't guess it's possible to leave the warning in place but globally disable the autofix?

**Comment by sushantdhiman** [comment]
Default lint command doesn't fix automatically https://github.com/sequelize/sequelize/blob/master/package.json#L124, I don't see `--fix` flag there.

Are you running `eslint --fix` directly, in that case I see a line comment as a way to prevent removal of `.skip` OR we can change our eslint rules to skip the `.skip`

**Comment by jedwards1211** [comment]
Yeah, what I meant was a way I can `--fix` everything else without removing any `.skip`s, even if they're not ignored.  Oh well, ignoring isn't so bad

**Comment by jedwards1211** [comment]
oh IIRC I disabled eslint for that line
