### ISSUE TITLE
[MySQL] timezone:"local" or "dialectOptions"{timezone:"local"}" do not works

### ISSUE THREAD

**Issue by fernetmatt** [sequelize/sequelize#12150]
## Issue Description
My DB is on another timezone but I don't want to override the timezone setting on the session. I want to keep my MySQL server's default. So i've tried to set "local" on the timezone setting like i do in my [mysql](https://www.npmjs.com/package/mysql) legacy library.
Actually neither sequelize nor mysql2 accept the "local" setting or get it to work correctly. I've tried many combinations but there is no clear documentation about this.

This is my last attempt:

```js
 dialect: 'mysql', 
 keepDefaultTimezone: true,
  dialectOptions: {
      timezone: "local"
  }
```

And this statement:
```
const now = moment(); // it evaluate to 2020-04-22 18:22:00 +02:00

const start = now.startOf('day'); // it evaluate to 2020-04-22 00:00:00 +02:00
const end = now.endOf('day'); // it evaluate to 2020-04-22 23:59:59 +02:00

const where = {
      bot_id: 99,
      when: {
        $between: [start , end]
      },
    };
    return Message.count({ where });
```
Become:
```
[...] AND `table`.`when` BETWEEN '2020-04-21 22:00:00' AND '2020-04-22 21:59:59'
```

I'm expecting the sequelize connection/session  to correctly handle *datetime* fields without override the mysql server setting if the "local" timezone setting is given.

**Comment by sushantdhiman** [comment]
Yes we don't support local timezone, you have to specify your server's timezone manually 


_____________________

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
