### ISSUE TITLE
Model.destroy returns NaN as destroyed count

### ISSUE THREAD

**Issue by AuHau** [sequelize/sequelize#12164]
### What are you doing?

Calling `destroy()` on `Model` in order to truncate table. Based on documentation this call should return `Promise<number>` with count of destroyed entries.

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/72 

### What do you expect to happen?

Count of destroyed entries

### What is actually happening?

`NaN is returned instead`

### Environment

- Sequelize version: 5.21.7
- Node.js version: v12 
- Operating System: macos
- If TypeScript related: TypeScript version: 3.8

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): postgres, MySQL, mariadb
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by SimonSchick** [comment]
Cannot reproduce on windows (same node and Sequelize version).
Going to test on macos in a bit.
