### ISSUE TITLE
The counting of associations

### ISSUE THREAD

**Issue by Vanguardo66** [sequelize/sequelize#12176]
Hi guys.
I want to get all categories and count of the associated posts using below code:

`const categories = await Category.findAll({
        attributes:[[sequelize.fn('COUNT', 'Post.id'), 'PostCount'], 'Category.name','Category.slug','Category.id'],
        include:[Post],
        group: ['Category.name','Category.slug','Category.id']
    });`

I also tried to expand the attributes property to:
`attributes:{include:[...],exclude:[...]}`
This in throwing this:

> Executing (default): SELECT `Category`.`id`, COUNT('Post.id') AS `PostCount`, `Category`.`name`, `Category`.`slug`, `Posts`.`id` AS `Posts.id`, `Posts`.`title` AS `Posts.title`, `Posts`.`slug` AS `Posts.slug`, `Posts`.`introImage` AS `Posts.introImage`, `Posts`.`content` AS `Posts.content`, `Posts`.`categoryId` AS `Posts.categoryId`, `Posts`.`createdAt` AS `Posts.createdAt`, `Posts`.`updatedAt` AS `Posts.updatedAt`, `Posts`.`CategoryId` AS `Posts.CategoryId` FROM `Categories` AS `Category` LEFT OUTER JOIN `Posts` AS `Posts` ON `Category`.`id` = `Posts`.`CategoryId` GROUP BY `Category`.`name`, `Category`.`slug`, `Category`.`id`;
(node:31164) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'nini_db.Posts.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

1- Why it is including every attribute in both tables?
2- How to get it done?

**Comment by Vanguardo66** [comment]
I have changed it to: 
`const categories = await Category.findAll({
        attributes:[[sequelize.fn('COUNT', 'Post.id'), 'PostCount'], 'name','slug','id'],
        include:[{
            model:Post,
            attributes:[]
        }],
        group: ['Category.name','Category.slug','Category.id']
    });`

and it works but with a flaw, as it returns PoastCount of 1 for the categories that have no posts.

**Comment by Vanguardo66** [comment]
Guys I think it is because of `LEFT OUTER JOIN` but I don,t know how.

**Comment by Vanguardo66** [comment]
For guys who hit this page through searching:
I have got the desired output by including a where clause in the associate model `Post` to check  if the id is not null:
`const categories = await Category.findAll({
        attributes:[[sequelize.fn('COUNT', 'Posts.id'), 'PostCount'], 'name','slug','id'],
        include:[{
            model:Post,
            attributes:[],
            where:{
                id:{
                    [Sequelize.Op.not]:null
                }
            }
        }],
        group: ['Category.name','Category.slug','Category.id']
    });`

This actually returns only the categories with posts.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
