### ISSUE TITLE
add another field to update on paranoid

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/sequelize#12178]
## Issue Description

I want to add another field that needs to be updated on soft delete, `isDeleted`, so besides updating the `deletedAt`, I would also need the paranoid update query to set the `isDeleted` to true. How is that going to be possible without making an extra `model.update`?

### Is your feature request related to a problem? Please describe.

Minimizing database queries during delete because when you need to soft delete a record and also update other records. I could do `model.update` instead of `model.destroy` but doing so will not fire the correct sequelize hook `afterDestroy` which I also need to do some other stuff.

### Describe the solution you'd like

Hmmm... I'm unsure how to answer this.

```js
// If applicable, add a code snippet showing how your feature would be used in a real use-case
```

### Why should this be in Sequelize

Hmmm... I'm unsure how to answer this.

### Describe alternatives/workarounds you've considered

Running a separate `model.update` after `model.destroy` but that's not really ideal and it also fires the update hooks.

### Additional context

None.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance (edit: Also I don't know WHERE to start).
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
We wont support this but it seems like a good fit for [`TRIGGER`](https://www.postgresql.org/docs/9.5/sql-createtrigger.html)
