### ISSUE TITLE
Hook function not called with async modification

### ISSUE THREAD

**Issue by acidos** [sequelize/sequelize#12170]
I have the following model with hook

```
    User.init({ },{ 
        hooks: {
            beforeUpdate: async (user, options) => {
                console.log('updated');
                // some async job here with await
            }
        }
    });
```

Now I am trying to update a row:

```
    const user = await User.findOne({ ... });
    user.balance = 1000002;
    await user.save(); // here can be also other function such as increment, result is same
```

Above is not triggering the hook for some reason.
If I remove await and just call 

`    user.save();`
 
then the hook is called. 
How can I modify instance asynchronously while having hook triggered?

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by sushantdhiman** [comment]
It works

```js

(async () => {  
  const BooleanTable = sequelize.define(                                      
    "BooleanTable",  
    {  
      status: {  
        type: Sequelize.BOOLEAN,  
        defaultValue: true,  
        allowNull: false,  
      },  
    },  
    {  
      freezeTableName: true,  
      hooks: {  
        beforeCreate: async () => {  
          console.log('Enter hook');  
          await new Promise(resolve => {                                      
            setTimeout(() => {  
              console.log('Resolve hook');                                    
              resolve();  
            }, 1000);                                                                                                                    
          });  
        }  
      }  
    }  
  );  
  
  await BooleanTable.sync({ force: true });

  await BooleanTable.create({ status: false });

  console.log('Done');
})();

```

```sql
> sequelize@6.0.0-beta.5 sscce-sqlite /var/projects/oss/sequelize
> cross-env DIALECT=sqlite npm run sscce


> sequelize@6.0.0-beta.5 sscce /var/projects/oss/sequelize
> env-cmd $npm_package_options_env_cmd node sscce.js

Enter hook
Resolve hook
Done
```
