### ISSUE TITLE
tedious 8.3.0 deprecation

### ISSUE THREAD

**Issue by UziTech** [sequelize/sequelize#12181]
## Issue Description

`tedious` will require calling `.connect()` on the connection in v9 it currently reports a deprecation in v8.3.0

### What are you doing?

using `tedious` v8.3.0 to connect to MS SQL Server

### What do you expect to happen?

No deprecation notice

### What is actually happening?

tedious is showing deprecation notice:

```
In the next major version of `tedious`, creating a new `Connection`
instance will no longer establish a connection to the server automatically. Please use
the new `connect` helper function or call the `.connect` method on the newly created
`Connection` object to silence this message.
```

### Additional context

The `tedious` PR with this deprecation: https://github.com/tediousjs/tedious/pull/1069

### Environment

- Sequelize version: 5.21.7
- Node.js version: 12.6.1
- Operating System: Windows 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MSSQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ionut-gheorghe** [comment]
Missing connect() method in typescript
