### ISSUE TITLE
Notice: Database engine support change

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#12186]
With v6 we are planning to adopt official database engine support policy. You can find this in [`ENGINE.md`](https://github.com/sequelize/sequelize/blob/master/ENGINE.md)

|  Engine |  Minimum supported version |
| ------------ | :------------: |
|  Postgre | [9.5 ](https://www.postgresql.org/docs/9.5/ ) |
|  MySQL |  [5.7](https://dev.mysql.com/doc/refman/5.7/en/) |
|  MariaDB |  [10.1](https://mariadb.com/kb/en/changes-improvements-in-mariadb-101/) |
|  Microsoft SQL |  ? |
|  SQLite |  [3.0](https://www.sqlite.org/version3.html) 

This means older versions for these database engines will not work with Sequelize v6. If you have any comments related to this please let us know.

**Note :** `MSSQL` minimum supported version is still pending investigation

**Comment by salihkaragoz** [comment]
Hi,
My MariaDB database engine version is 10.3. I'm still getting the following warning

`[SEQUELIZE0006] DeprecationWarning: This database engine version is not supported, please update your database server. More information https://github.com/sequelize/sequelize/blob/master/ENGINE.md `

Node Version: v10.13.0
"dependencies": {
    "express": "^4.17.1",
    "mariadb": "^2.4.2",
    "sequelize": "^6.3.4"
  }

10.3.23-MariaDB-log - MariaDB Server

**Comment by stomvi** [comment]
I am using `mysql v8.0.22` and keep getting `SEQUELIZE0006` warnings.

**Comment by julesnuggy** [comment]
I'm also getting this error. I'm using `mysql2^2.2.5` and my laptop has MySQL Server 8.0.23 installed. My server still spins up and works, but just not sure why the error message is appearing.

**Comment by jonathanGroupRoot** [comment]
Eu também estou com esse problema, ele mostra a mensagem mas não acontece nada, continua normalmente, alguém consegue me ajudar??

**Comment by divinebovine** [comment]
@sushantdhiman I'm getting this error as well with PostgreSQL 11.

**Comment by HARRISKING** [comment]
mysql V8.0.22，show the error: 
![image](https://user-images.githubusercontent.com/23523674/107193825-3b3dab00-6a2a-11eb-85cf-95efc77219b5.png)

**Comment by nricks** [comment]
I'm getting this deprecation warning as well and it only started recently:

I have the following setup

galera nodes:
`mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for Linux (x86_64) using readline 5.1`

proxysql:
`ProxySQL version 2.1.0-544-g17a4b4a7, codename Truls`

package.json

```json
    "mariadb": "^2.5.2",
    "sequelize": "^6.5.0",
```

I no longer receive this warning after replacing mariadb npm package with the mysql2 package and setting up the driver to use mysql as dialect, as follows:

package.json

```json
    "mysql2": "^2.2.5",
```

connector

```js
const sequelize = new Sequelize(conf.mariadb.db, conf.mariadb.username,
  conf.mariadb.password, {
    host: conf.mariadb.host,
    port: conf.mariadb.port,
    dialect: "mysql",
```
I'm not  sure this only stopped the deprecation warning and I will have trouble in the future for it.
