### ISSUE TITLE
Insert query runs when destroying model object

### ISSUE THREAD

**Issue by tresdev** [sequelize/sequelize#12184]
## Issue Description
Insert query runs when I tried to destroy model object.

### What are you doing?
```
const user = await User.findByPk(userId)

user.destroy({transaction})
```
### What do you expect to happen?
Just simply destroying that row in the DB.

### What is actually happening?
I got an error.
It tried to run an insert query on `User` table, with values of `user `.
And primary key duplication error occured, since it was not deleted yet.

So instead I just tried,

```
User.destroy({
    where: {
        id: userId
    },
    transcaction
})
```

And it worked.

### Additional context
I used transaction.

### Environment
- Sequelize version: 5.9.0
- Node.js version: 10.15.3
- Operating System: Tested on Linux and Windows environment.
- If TypeScript related: Not.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Destroy doesn't issue INSERT, perhaps primary key field was deleted from instance. You need to give us a SSCCE https://github.com/papb/sequelize-sscce
