### ISSUE TITLE
MSSQL upsert query generation error

### ISSUE THREAD

**Issue by IanBurganMod** [sequelize/sequelize#12190]
## Issue Description
When performing an `upsert` without any non-key / non-unique attributes, the generated query is not valid SQL.

### What are you doing?
I am calling `upsert` and only supplying fields that are part of a unique constraint.

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/75 

### What do you expect to happen?
Sequelize should generate valid SQL or error in some way before generating invalid SQL

### What is actually happening?
Sequelize generates invalid SQL. The portion of the query that errors is below.

```
... WHEN MATCHED THEN UPDATE SET  WHEN NOT MATCHED THEN INSERT ...
```

### Environment

- Sequelize version: 5.21.5 
- Node.js version: 10.16.3 
- Operating System: Windows 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): MSSQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by IanBurganMod** [comment]
Misdiagnosis of the problem. Apologies

**Comment by papb** [comment]
Hello, happy that you figured it out! :smiley:  I see you took the time to fill our issue template and create a sequelize-sscce, thanks for that, I wish everyone did it like you...
