### ISSUE TITLE
The Philosophy Goal Implementation links all point to One-to-One

### ISSUE THREAD

**Issue by louy2** [sequelize/sequelize#12197]
### What was unclear/insufficient/not covered in the documentation

The Philosophy, Goal, Implementation links under One-to-Many and Many-to-Many all point to the headings with the same names under One-to-One.

### If possible: Provide some suggestion on how we can enhance the docs

Fix the links to point to their corresponding headings.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello! Thanks for reporting this. This seems a nontrivial bug from esdoc since it generates the heading 'names' simply from their own text, and since the texts are identical, this ends up happening.

Maybe we can perform a manual fix...

**Comment by papb** [comment]
https://github.com/sequelize/sequelize/tree/master/docs/transforms

**Comment by louy2** [comment]
Found the offending code in the publish html plugin, but not sure how much work it is to swap it out.

https://github.com/esdoc/esdoc-plugins/blob/master/esdoc-publish-html-plugin/src/Builder/util.js#L65

```javascript
  const renderer = new marked.Renderer();
  renderer.heading = function (text, level) {
    const id = escapeURLHash(text);
    return `<h${level} id=${id}>${text}</h${level}>`;
  };
```

**Comment by louy2** [comment]
Oh, you forgot to specify `cheerio` in the dev dependencies. Interesting how you could use it from transitive dependency position. I'm using `pnpm` which doesn't allow that.
