### ISSUE TITLE
The static method Model.create ignores options.include

### ISSUE THREAD

**Issue by yanickrochon** [sequelize/sequelize#12206]
## Issue Description

Model static `create` method ignores `options.include` value.

### What are you doing?

```js
import Product from './Product';
import ProductCategory from './ProductCategory';
import ProductType from './ProductType';

Product.Category = Product.hasOne(ProductCategory, { foreignKey: 'id', sourceKey: 'categoryId' });
Product.Type = Product.hasOne(ProductType, { foreignKey: 'id', sourceKey: 'productTypeId' });
Product.ALL = [ Product.Category, Product.Type ];

const saveProduct = async ({ sku, name, categoryId, productTypeId }) => {
   return Product.create({ sku, name, categoryId, productTypeId }, { include: Product.ALL, logging: console.log });
}

saveProduct({ sku: "foo", name: "Foo", categoryId: "6", productTypeId: "12" }).then(product => {
  console.log(product.toJSON());
});
// -> Executing (default): INSERT INTO `inv_products` (`id`,`name`,`sku`,`categoryId`,`productTypeId`) VALUES (DEFAULT,?,?,?,?);
// -> { id: 76, sku: "foo", name: "Foo", categoryId: 6, productTypeId: 12 }
```

### What do you expect to happen?

When calling the `findOne` method, given the previous SQL, it would return :

```js
const product = await Product.findOne({ where: { id: 76 }, include: Product.ALL });
// -> { id: 76, sku: "foo", name: "Foo", categoryId: 6, productTypeId: 12, ProductCategory: { id: 6, name: "CatTest" }, ProductType: { id: 12, name: "TypeTest" } }
```

So I would expect creating the object would return the relations if specified the same.

```js
const product = await Product.create({ sku: "foo", name: "Foo", categoryId: 6, productTypeId: 12 }, { include: Product.ALL } });
// -> { id: 76, sku: "foo", name: "Foo", categoryId: 6, productTypeId: 12, ProductCategory: { id: 6, name: "CatTest" }, ProductType: { id: 12, name: "TypeTest" } }
```

### What is actually happening?

It seems like the relatins are ignored when creating a model; they are not returned even if specified.

### Environment

- Sequelize version: 5.21.7
- Node.js version: 12.13.1
- Operating System: Ubuntu 20.04 LTS

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please check docs https://sequelize.org/master/manual/creating-with-associations.html, you need to put aliases object in `create` payload.

It should then return full data for each included object

**Comment by yanickrochon** [comment]
This does not make any sense. No other method needs this and all work just fine as it is. Plus, the example you're showing is for a nested model. The example I provided in this issue already define these aliases by default in the provided associations.

**Comment by yanickrochon** [comment]
By the way, at the moment, this is how I patched this issue, which is pretty dumb as it forces to select the model TWICE.

```js
  const product = await Product.create({ sku, name, categoryId, productTypeId }, { include: Product.ALL });
  return product.reload();
```
This does exactly what it should, but completely redundant and silly.

**Comment by sushantdhiman** [comment]
> No other method needs this and all work just fine as it is

Yes, all finders works with this but for create, as suggested in docs pattern is different.

> The example I provided in this issue already define these aliases by default in the provided associations.
> Product.create({ sku, name, categoryId, productTypeId }

I don't see any aliases in payload, you are directly passing FKs

**Comment by yanickrochon** [comment]
The point is that the `create` method does not behave like other methods.

**Comment by sushantdhiman** [comment]
Yes I understand but if we don't include aliases in payload, how can we set extra attributes on included models. This is why you have to use alias names instead of FKs if you want to properly use `options.include` with `create`

**Comment by yanickrochon** [comment]
No other method seem to care about that, and set the properties as they should (which I'm perfectly comfortable with, IMO). So you're saying that every method return unspecified results and `create` is the only one that's standard?

What about the `reload` method?

The `create` method is the _only_ one behaving differently.

**Comment by sushantdhiman** [comment]
> No other method seem to care about that
> What about the reload method?

Yes because they are **FINDER METHODS**, they behave differently from **CREATE METHODS**

**Comment by yanickrochon** [comment]
Even if the create method ultimately finds the newly created model? Because the executed query, as specified in the first post in this issue, shows that it does not return anything because **RETURNING** is not supported by all RDBMS, and so the `create` method **must** execute a SELECT query anyway.
