### ISSUE TITLE
When Sequelize tries to replace binding value, it also tries to replace table name which has "$" sign. 

### ISSUE THREAD

**Issue by charles-chen-wtw** [sequelize/sequelize#12203]
### What are you doing?

Background:

- We have an existing SQL database with data.
- I used sequelize-auto to generate definitions. 
- Most of the tables we have contain "$" dollar sign

So I am trying to use sequelize to insert some data to the table. 

```js
let contract_name = {
  Version: 1,
  ID: 50,
  Position: 50,
  Value: "SomeName",
};

db.RI_Contracts_Names$DIM.create(contract_name).then(() => {
  console.log("saved: " + contract_name.Value);
});

db.RI_Contracts_Names$DIM.findAll({ limit: 20 }).then((rows) => {
  console.log(JSON.stringify(rows));
});
```

### What do you expect to happen?

I wanted the data inserted as a new row in the table

### What is actually happening?

```
Unhandled rejection Error: Named bind parameter "$DIM" has no value in the given object. 
```

### Additional context

I think the problem is inside the `abstract\query.js` line 87, when it's trying to replace the binds, it's replacing the whole sql. 

The sql after trim is:

```
INSERT INTO [RI_Contracts_Names$DIM] ([Version],[ID],[Position],[Value]) OUTPUT INSERTED.* VALUES ($1,$2,$3,$4);
```

Can sequelize just replace the ones inside `VALUES`? Or ignore the ones inside square brackets?
Thank you.

### Environment

- Sequelize version: 5.21.7
- Node.js version: 14.1.0
- Operating System: Linux
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): mssql
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/12250
