### ISSUE TITLE
Add new node versions to CI

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#12216]
## Issue Description

It would be prudent to run our CI against node v12 and v14, we can safely assume that a non insignificant amount of the users run something higher than v10.

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.

### Additional context

Nope.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Our build matrix is huge and adding new Node versions will just increase testing time. I think it is better to just stick to lowest supported version

**Comment by SimonSchick** [comment]
This does pose the risk of not working in newer versions though, this was a huge issue recently: https://news.ycombinator.com/item?id=22979245 / https://github.com/then/is-promise/issues/13

**Comment by sushantdhiman** [comment]
Users can report any incompatibilities like https://github.com/sequelize/sequelize/issues/12158 and we can fix them. Adding more node version to build will hinder our day to day productivity with no immediate gains
