### ISSUE TITLE
SQLite migrations (add/remove columns)

### ISSUE THREAD

**Issue by psikoi** [sequelize/sequelize#12229]
### What are you doing?
When running integration tests using sequelize and **SQLite**, i tried to add multiple columns in the same migration.
The table I'm trying to alter (named "snapshots") is created in a previous migration.

Migration:
```js
module.exports = {
  up: (queryInterface, Sequelize) => {
    return Promise.all([
      queryInterface.addColumn('snapshots', 'testColumn', {
        type: Sequelize.INTEGER,
        defaultValue: -1
      }),
      queryInterface.addColumn('snapshots', 'otherTestColumn', {
        type: Sequelize.INTEGER,
        defaultValue: -1
      })
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return Promise.all([
      queryInterface.removeColumn('snapshots', 'testColumn'),
      queryInterface.removeColumn('snapshots', 'otherTestColumn')
    ]);
  }
};
```

Schema definition:
```js
const snapshotSchema = {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    playerId: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    importedAt: {
      type: DataTypes.DATE
    },
    testColumn: {
      type: DataTypes.INTEGER
    },
    otherTestColumn: {
      type: DataTypes.INTEGER
    }
  };
```

### What do you expect to happen?

I expected the migration create both `testColumn` and `otherTestColumn` on migration up (sequelize db:migrate), and then successfully remove both columns on migration down. (sequelize db:migrate:undo:all)

### What is actually happening?

It correctly adds both columns to the table, which I can see by printing the table attributes:
`console.log(Object.keys(Snapshot.tableAttributes));`

But unfortunately, it fails to undo the migration (migration down), with the following error:

```
Sequelize CLI [Node: 13.8.0, CLI: 5.5.1, ORM: 5.21.7]

Loaded configuration file "src\database\config.js".
== 20200504010320-add-test-columns: reverting =======

ERROR: SQLITE_ERROR: no such table: snapshots_backup
```

### Environment

- Sequelize version: 5.21.7 
- Node.js version: 13.8.0 
- Operating System: Windows 10
- If TypeScript related: TypeScript version: ---

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using sqlite, with connector library version 4.2.0

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please show SQL logs, due to limitation of SQLite platform we usually create a backup table and copy data to it excluding attribute you want to remove.

https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite

It seems like create table operation failed?

**Comment by psikoi** [comment]
The create table is performed on a previous migration, and between the migrations up and down, I'm doing plenty operations using that table with no issue. I'll post SQL logs if it'll help.

**Comment by sushantdhiman** [comment]
Let me know when you have SQL logs or SSCCE so this can be investigated properly, I'll reopen this issue
