### ISSUE TITLE
Does cascade works abnormally without { force: true } while tables set { paranoid:true }?

### ISSUE THREAD

**Issue by JHPTFarm** [sequelize/sequelize#12233]
## Issue Description
Cant delete data of the associated table.

### What are you doing?

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// Book model
export default connection.define('book',
  {
    id: {
      type: INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: STRING,
      allowNull: false,
    },
  },
  {
    paranoid: true,
    underscored: true,
  }
)

// BookStore model
export default connection.define('book_store',
  {
    id: {
      type: INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: STRING,
      allowNull: false,
    },
    address: {
      type: STRING,
      allowNull: false,
    }
  },
  {
    paranoid: true,
    underscored: true,
  }
)

// Set association
BookStore.hasMany(Book, {
  onDelete: 'cascade',
  onUpdate: 'cascade',
  hooks: true,
  foreignKey: {
    allowNull: false,
  }
})
Book.belongsTo(BookStore, {
  foreignKey: {
    name: 'bookStoreId',
  },
})

// Delete one of the BookStore data and its related rows
await BookStore.destroy({
  where: {
    id: 1,
  },
  cascade: true,
  // force: true,
  truncate: true,
  logging: console.log,
  benchmark: true,
})
```

### What do you expect to happen?

I expect both BookStore and Book tables are going to have a timestamp in deleted_at column.

### What is actually happening?

The destroy method only works on the row of the BookStore table,
and the deleted_at column is staying null in the Book table.

I found the query is not complete with my imaging when I set { logging: console.log, benchmark: true } in the destroy command. (See below)

```
Executed (default): UPDATE "book_stores" SET "deleted_at"=$1 WHERE "deleted_at" IS NULL AND "id" = $2 Elapsed time: 1ms
```

### Environment

- Sequelize version: 5.21.2
- Sequelize-typescript version: 1.0.0
- Node.js version: 12.13.0 
- Operating System: maxOS 10.14.5
- If TypeScript related: TypeScript version: 3.6.4
- Database: postgres 11

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
No it doesn't as `cascade` is database enforced, https://github.com/sequelize/sequelize/issues/2586
