### ISSUE TITLE
Seed using native query.

### ISSUE THREAD

**Issue by th1m0r** [sequelize/sequelize#12234]
### What was unclear/insufficient/not covered in the documentation

The possibility of using native query instead of bulkCreate or bulkInsert to populate tables using Seed

### If possible: Provide some suggestion on how we can enhance the docs
showing a note about if is possible or not.  And show a example like this,  being is possible.

up: (queryInterface, Sequelize) => {
    return Sequelize.query(
       "INSERT INTO table VALUES (field1, field2) VALUES ("A", "B"),("C","D")...
    )
      }], {});
  },

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ x ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ X ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
I don't think we should add this, this is covered in API documentation that `query` can be used to make queries. It wont help anyone if they aren't reading docs & api

**Comment by th1m0r** [comment]
> I don't think we should add this, this is covered in API documentation that `query` can be used to make queries. It wont help anyone if they aren't reading docs & api

I know this, and i alread use raw queries. But, where is in docs & api the information about use it, on migration? that is my point. I read all, all, api & docs and there don't have all features. for example, map raw queries with join return objects model? don't have.
