### ISSUE TITLE
Need help using "Where $or"

### ISSUE THREAD

**Issue by neko1101** [sequelize/sequelize#12236]
Hey guys, im new using sequelize.

My code:
`const findOne = async (email) => {
    return await user.findOne({
        where: {
            $or: {
                email,
                username: email
            }
        }
    })
    .catch(err => console.log(err));
}`

Error:
`Error: Invalid value { email: 'abc@gmail.com' }`

Can someone point out where did i do wrong ? 

Thanks!

**Comment by sushantdhiman** [comment]
`$or` should be replaced with `Op.or`

------------------

Follow the template so I know about your setup if want more help
