### ISSUE TITLE
I want to dynamically add join statement

### ISSUE THREAD

**Issue by Mayank-prod** [sequelize/sequelize#12232]
This is my first model.

I am able to generate join query because of associations

```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const servicelocation_engineer = sequelize.define('servicelocation_engineer', {
    ServiceLocationEngineerID: {
      allowNull: false,
      primaryKey: true,
      unique: true,
      type: DataTypes.BIGINT
    },
    PartnerID: DataTypes.INTEGER,
    PartnerServiceLocationID: DataTypes.INTEGER,
    Name: DataTypes.STRING,
    MaxProductivityPerDay: DataTypes.INTEGER,
    ProductivityPerDay: DataTypes.INTEGER,
    IsActive: DataTypes.INTEGER,
    Type: DataTypes.STRING
  }, {
    freezeTableName: true
  });
  servicelocation_engineer.associate = function (models) {
    servicelocation_engineer.belongsTo(models.partner, {
      foreignKey: 'PartnerID',
      as: 'partner'
    });
    servicelocation_engineer.belongsTo(models.partner_servicelocation, {
      foreignKey: 'PartnerServiceLocationID',
      as: 'partner_serviceloaction'
    });
    servicelocation_engineer.belongsTo(
      models.servicelocation_engineer_product, {
        targetKey: 'ServiceLocationEngineerID',
        foreignKey: 'ServiceLocationEngineerID'
      }
    )
    servicelocation_engineer.belongsTo(
      models.servicelocation_engineer_pincode, {
        targetKey: 'ServiceLocationEngineerID',
        foreignKey: 'ServiceLocationEngineerID'
      }
    )
    servicelocation_engineer.belongsTo(
      models.servicelocation_servicetype, {
      }
    )
  };
  return servicelocation_engineer;
};
```

I want to dynamically generate join query for a third table 
I am able to join two tables which are related
but Want to generate below query

```
INNER JOIN "servicelocation_servicetype" ON ("partner_servicelocation"."PartnerServiceLocationID" = "servicelocation_servicetype"."PartnerServiceLocationID")
```
Is there any way?

**Comment by sushantdhiman** [comment]
Ask questions on Stackoverflow / Slack. Follow the template


---------------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
