### ISSUE TITLE
[Question] Run queries without transactions?

### ISSUE THREAD

**Issue by srodriki** [sequelize/sequelize#12244]
Hi everyone,

I'm currently facing an issue using Sequelize 4.42.0 and MySQL Community 5.7.28. 
The problem is simply every time I run a query via sequelize (findAll, findOne) a new transaction gets started at the DB level. Is there any way to prevent this from happening?

In my server logs I see the following:

Query START TRANSACTION
Query SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
Query SELECT [...]
Query COMMIT

This seems to be happening for every query and I've not been able to find any place where it explains how to simply run the SELECT part without the other parts.

Any help is much appreciated

**Comment by papb** [comment]
Per [our docs](https://sequelize.org/master/manual/transactions.html):

> Sequelize does not use transactions by default.

So you must be doing something wrong. Perhaps [CLS](https://sequelize.org/master/manual/transactions.html#automatically-pass-transactions-to-all-queries) is set up?

Regardless, please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
