### ISSUE TITLE
SQLite dialect: composite key with autogenerated `id` column results in syntax error

### ISSUE THREAD

**Issue by soryy708** [sequelize/sequelize#12242]
## Issue Description

This is related to https://github.com/sequelize/sequelize/issues/12194

### What are you doing?

```js
const Sequelize = require('sequelize');

const weakEntity = (sequelize, dataTypes) => {
    const model = sequelize.define('weak', {});

    model.associate = (models) => {
        model.belongsTo(models.parent, {foreignKey: {primaryKey: true}});
    };

    return model;
};

const parentEntity = (sequelize, dataTypes) => {
    const model = sequelize.define('parent', {
        name: {
            type: dataTypes.STRING,
            primaryKey: true,
        },
    });

    model.associate = (models) => {
        model.hasOne(models.weak);
    };

    return model;
};

const models = {
    weak: weakEntity,
    parent: parentEntity,
};

const sequelize = new Sequelize({ dialect: 'sqlite', logging: message => console.log(message) });
Object.keys(models).forEach(modelName => {
    const modelDef = models[modelName];
    const model = modelDef(sequelize, Sequelize);
    models[modelName] = model;
});
Object.keys(models).forEach(modelName => {
    const model = models[modelName];
    if (model.associate) {
        model.associate(models);
    }
});
sequelize.authenticate()
.then(() => sequelize.sync())
.then(() => {
    console.log('Done initializing database');
})
.catch(err => {
    console.log(err);
});
```

### What do you expect to happen?

Created table called "parent" with column called "name"
Created table called "weak" with column called "parentName" that is primary key

### What is actually happening?

Error when attempting to create table called "weak" which has an autoincremented "id" column, in addition to the "parentName" expected column.

```
CREATE TABLE IF NOT EXISTS `weak` (`id` INTEGER NOT NULL AUTOINCREMENT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `parentName` VARCHAR(255) NOT NULL REFERENCES `parent` (`name`) ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY (`id`, `parentName`));
```

Note the `AUTOINCREMENT` for the `id` column. According to [sqlite documentation](https://www.sqlite.org/autoinc.html):

> Because AUTOINCREMENT keyword changes the behavior of the ROWID selection algorithm, AUTOINCREMENT is not allowed on WITHOUT ROWID tables **or on any table column other than INTEGER PRIMARY KEY**. Any attempt to use AUTOINCREMENT on a WITHOUT ROWID table or on a column other than the INTEGER PRIMARY KEY column results in an error.

While `id` is part of the composite key, it's not a `PRIMARY KEY` on it's own.

### Additional context

N/A

### Environment

- Sequelize version: 5.21.8
- Node.js version: 12.16.2
- Operating System: Windows 10 Home x64
- If TypeScript related: TypeScript version: N/A

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): sqlite
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by soryy708** [comment]
In my use case I don't really need the `id` column.
But for the general case, I'm not sure how to auto-generate an `id` column to be part of the composite primary key, s.t. it's handled behind the scenes (apparently without `AUTOINCREMENT` explicitly). This may need some design effort.
Maybe an `UUID` instead of an `INTEGER`?

**Comment by sushantdhiman** [comment]
When creating a model you can define your own `id` attribute, Sequelize will use it. `Model.removeAttribute('id')` can be used to remove auto-generated attribute altogether.

Sequelize has poor support for composite primary keys, you will run into issues with that.

**Comment by soryy708** [comment]
related? https://github.com/sequelize/sequelize/issues/311

**Comment by sushantdhiman** [comment]
Yes, I am closing this issue as primary issue is lack of composite key support.
