### ISSUE TITLE
[Question] Have anyone tried using AWS Lambda Proxy with RDS

### ISSUE THREAD

**Issue by muriloSanto** [sequelize/sequelize#12245]
Have anyone tried using AWS Lambda Proxy with RDS to reuse connections ?

**Comment by marcogrcr** [comment]
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.
