### ISSUE TITLE
notNull Violation when creating an association with the property filled.

### ISSUE THREAD

**Issue by dilizarov** [sequelize/sequelize#12252]
## Issue Description

I have a model, Project, and another one, Testy, which has a required column (amount).

Even if this column is filled on a built **but not persisted** Testy, then creating the association through the association helpers fails with this error:

`Unhandled rejection SequelizeValidationError: notNull Violation: Testy.amount cannot be null` 

### What are you doing?

Here are two very simplified Models built with `sequelize-typescript`. While the syntax might be foreign, the example is straightforward enough.

```ts
@Table({
  timestamps: true,
})
class Testy extends Model<Testy> {
  @AllowNull(false)
  @Column(DataType.DECIMAL(12, 2))
  amount: number;

  @ForeignKey(() => Project)
  @Column
  projectId: number;

  @BelongsTo(() => Project)
  project: Project;
}

@Table({
  timestamps: true,
})
class Project extends Model<Project> {
  @HasMany(() => Testy)
  testies: Testy;
}

Project.create({}).then((project) => {
    const testy = Testy.build({ amount: 3 })

    project.createTesty(testy); // THIS LINE WILL PRODUCE ERROR
})
```

### What do you expect to happen?

The expectation is that because the `amount` property is provided, then the Testy will be persisted to the database with the `projectId` properly filled in.

### What is actually happening?

`Unhandled rejection SequelizeValidationError: notNull Violation: Testy.amount cannot be null`

### Environment

- Sequelize version: 5.21.5
- Node.js version: 12.10.0
- Operating System: macOS Catalina 10.15.3
- If TypeScript related: TypeScript version: 3.7.5

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by soryy708** [comment]
Can you paste the SQL sequelize is generating? You can view it by adding `logging: (message) => console.log(message),` to the configuration object passed to the sequelize constructor.

I have a hunch that sequelize adds a `ON DELETE SET NULL` to your column, but that doesn't make sense for a column with the `notNull` constraint.

**Comment by dilizarov** [comment]
@soryy708 I don't think I'm even getting to to SQL:

This is what I get in the output:

```
Thrown:
ValidationError [SequelizeValidationError]: notNull Violation: Testy.amount cannot be null
    at /Users/david/Code/mink/packages/server/node_modules/sequelize/lib/instance-validator.js:74:15
    at bound (domain.js:420:14)
    at runBound (domain.js:433:12)
    at tryCatcher (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/david/Code/mink/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)
```

**Comment by soryy708** [comment]
Can you make a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by dilizarov** [comment]
I think the above is a MCVE... kinda (aside from the sequelize-typescript). Unless you want a code box to execute in or something?

**Comment by dilizarov** [comment]
@soryy708 

MCVE:

```js
class Project extends Model {}
Project.init({}, { sequelize, modelName: 'project' });
class Testy extends Model {}
Testy.init({ amount: Sequelize.STRING, allowNull: false }, { sequelize, modelName: 'testy' });

Project.hasMany(Testy);
Testy.belongsTo(Project);

Project.create({}).then((project) => {
    const testy = Testy.build({ amount: "value" })

    project.createTesty(testy); // THIS LINE WILL PRODUCE ERROR
})
```

Does that work for you? First time using sequelize syntax, but I think it's right?

**Comment by soryy708** [comment]
```js
const Sequelize = require('sequelize');
const Model = Sequelize.Model;

const sequelize = new Sequelize({
    dialect: 'sqlite',
    logging: message => console.log(message),
});

sequelize.sync();

class Project extends Model {}
Project.init({}, { sequelize, modelName: 'project' });
class Testy extends Model {}
Testy.init({ amount: Sequelize.STRING, allowNull: false }, { sequelize, modelName: 'testy' });

Project.hasMany(Testy);
Testy.belongsTo(Project);

Project.create({}).then((project) => {
    const testy = Testy.build({ amount: "value" })
    project.createTesty(testy); // THIS LINE WILL PRODUCE ERROR
})
```
> Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: projects

Please make something I can run as-is.

**Comment by dilizarov** [comment]
You don't get an error?

**Comment by soryy708** [comment]
Here's my full output:

> Executing (default): SELECT 1+1 AS result
> Executing (default): CREATE TABLE IF NOT EXISTS `projects` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
> Executing (default): PRAGMA INDEX_LIST(`projects`)
> Executing (default): CREATE TABLE IF NOT EXISTS `testies` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `amount` VARCHAR(255), `allowNull` false, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `projectId` INTEGER REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);
> Executing (default): PRAGMA INDEX_LIST(`testies`)
> Executing (default): INSERT INTO `projects` (`id`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2);
> Executing (default): INSERT INTO `testies` (`createdAt`,`updatedAt`) VALUES ($1,$2);

**Comment by dilizarov** [comment]
It doesn't look like your SQL inserts amount?

**Comment by soryy708** [comment]
I agree, but it doesn't throw a notNull violation.

**Comment by dilizarov** [comment]
Hmm. That doesn't make sense to me. I'm using postgres, but I don't think that matters. What version are you using of sequelize?

**Comment by soryy708** [comment]
It may be a postgres specific issue then.
I ran this with sequelize version 5.21.8.

**Comment by dilizarov** [comment]
Would a dialect really be the problem if it doesn't get to the SQL? My failure is in the validation before that.

**Comment by dilizarov** [comment]
The following works:

```
(async () => {
    const testy = await Testy.create({ amount: "test" });
    const project = await Project.create({});

    await project.addTesty(testy);
});
```

My SQL I get for the `project.addTesty(testy)`: `Executing (default): UPDATE "Testies" SET "projectId"=$1,"updatedAt"=$2 WHERE "id" IN (4)`

Maybe I should just avoid using the `createAssociation` method for now. Doesn't make sense.

**Comment by sushantdhiman** [comment]
@soryy708 Your SSCCE is actually not defining column `amount` with `allowNull`

@dilizarov It is expected, `createAssociation` creates a new linked row, it does not use already defined instance passed to it, thus it is called `create*`. On other hand `add*` works because it is expecting an instance passed to it.

You can use this

```js
await project.createTesty({ amount: "some" });
```

Or use

```js
await project.addTesty(instance);
```

**Comment by dilizarov** [comment]
@sushantdhiman thank you for the explanation!!

One question:

Does `await project.addTesty(instance)` work both for built AND created instances? I use it for created instances and it works, but would this work?

`await project.addTesty(Testy.build({ amount: "some" }));`

**Comment by sushantdhiman** [comment]
@dilizarov No it won't work with `build` instance, unless you have built that instance with PK.
