### ISSUE TITLE
How can I delete by a property from a column described as DataTypes.Array(DataTypes.JSONB)?

### ISSUE THREAD

**Issue by danoseun** [sequelize/sequelize#12264]
Please I have tried and searched severally for an answer on how to do this but I couldn't find. Please I need help.
[https://stackoverflow.com/questions/61806256/how-to-delete-a-resource-based-on-the-property-of-jsonb-array-in-sequelizepostg](url)

**Comment by sushantdhiman** [comment]
Someone answered on Stackoverflow, If you are still not satisfied with that answer please present your case as a SSCCE which I can execute quickly. Also I don't think you need `ARRAY(JSONB)` just `JSONB` will work.

---------------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by danoseun** [comment]
@sushantdhiman Thanks. I found another way around the problem.
