### ISSUE TITLE
The queryInterface doc is missing, returns 404

### ISSUE THREAD

**Issue by danberger1** [sequelize/sequelize#12270]
### What was unclear/insufficient/not covered in the documentation
The queryInterface link is broken and cannot be found -
https://sequelize.org/master/class/lib/query-interface.js~QueryInterface.html

(The link is from here - https://sequelize.org/master/manual/query-interface.html)

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Oops, good catch, thanks for the report, this was an oversight from #12217
