### ISSUE TITLE
mssql transaction error

### ISSUE THREAD

**Issue by Messilimeng** [sequelize/sequelize#12276]
## Issue Description
let insert1="insert xxx"
let insert2="insert xxx"
trans = sequelize.startransaction();
option={
transaction: trans
type:"INSERT"
}
sequelize.query(insert1,option)
sequelize.query(insert2,option)
 when i insert1 and insert 2 use type=“INSERT” then get error,but when i delete type="INSERT" OR type="anyother" then it works
uncaughtException TypeError: Cannot convert undefined or null to object
can you tell me how to do?

### What are you doing?

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: 5.21.6 
- Node.js version: v10.16.3
- Operating System: windows
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please provide a proper SSCCE https://github.com/papb/sequelize-sscce, I can't understand your issue from description
