### ISSUE TITLE
`id` column is autogenerated despite having a primaryKey defined in an association

### ISSUE THREAD

**Issue by soryy708** [sequelize/sequelize#12288]
### What are you doing?

```js
const Sequelize = require('sequelize');
const Model = Sequelize.Model;

const sequelize = new Sequelize({
    dialect: 'sqlite',
    logging: message => console.log(message),
});

const weakEntity = (sequelize, dataTypes) => {
    const model = sequelize.define('weak', {});

    model.associate = (models) => {
        model.belongsTo(models.parent, {foreignKey: {primaryKey: true}});
    };

    return model;
};

const parentEntity = (sequelize, dataTypes) => {
    const model = sequelize.define('parent', {});

    model.associate = (models) => {
        model.hasOne(models.weak);
    };

    return model;
};

const models = {
    weak: weakEntity,
    parent: parentEntity,
};

(async () => {
    Object.keys(models).forEach(modelName => {
        const modelDef = models[modelName];
        const model = modelDef(sequelize, Sequelize);
        models[modelName] = model;
    });
    Object.keys(models).forEach(modelName => {
        const model = models[modelName];
        if (model.associate) {
            model.associate(models);
        }
    });

    await sequelize.authenticate();
    await sequelize.sync();
})();
```

### What do you expect to happen?

`weak` table to have only 1 column: `parentId`

### What is actually happening?

`weak` table has 2 columns: `parentId` and `id`

### Environment

- Sequelize version: 5.21.8
- Node.js version: 12.16.2
- Operating System: Windows 10 Home x64

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Yes, because `model` was created before relationship was invoked. Thus it created a default `id` primary key.

You can either predefine your `primaryKey` attribute in model, so `id` is not created. Or call `removeAttribute('id')`
