### ISSUE TITLE
Nothing returned from raw query unless options.type is set to SELECT

### ISSUE THREAD

**Issue by jon64digital** [sequelize/sequelize#12283]
## Issue Description

I am upgrading a project which used ...

"sequelize": "4.41.0",
"tedious": "2.6.4"

to new versions....

"sequelize": "5.21.5",
"tedious": "8.2.0"

... and my raw queries now return [undefined, 1] as the result unless I change the query type to SELECT. Has something changed to break returning data from RAW or INSERT query types?

```js

            let sqlResult
            try {

                sqlResult = await sequelize.query(
                    `   
                        INSERT INTO players (username, emailAddress, phoneNumber, passwordHash) 
                            OUTPUT Inserted.*
                            VALUES ($username, $emailAddress, $phoneNumber, $passwordHash)
                    `,
                    { 
                        bind: sqlData, 
                        type: sequelize.QueryTypes.INSERT
                    }
                )

            } catch (error) {
                .. removed
            }

            console.log("sqlResult", sqlResult)
```

### What do you expect to happen?

The returned data to be in sqlResult[0]

### What is actually happening?

result has no data in it, but it does have the new record if I change the queryType to SELECT

### Environment

- Sequelize version: 5.21.5
- Node.js version: 13.1.0
- Operating System: Win10

### How does this problem relate to dialects?
- [x] I think this problem happens only for the following dialect(s):  MSSQL

### Would you be willing to resolve this issue by submitting a Pull Request?
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Not sure when this got broken but it has been fixed in master now, https://github.com/sequelize/sequelize/pull/12305

I don't think this can be safely ported over to stable v5. For now you will have to use `SELECT` whenever data got `RETURNING *` like signature
