### ISSUE TITLE
Can't create a transaction for nested objects.

### ISSUE THREAD

**Issue by AleKrabbe** [sequelize/sequelize#12282]
## Issue Description

The documentation does not cover how to deal with a deeply nest object chain. Say we had to create a transaction for saving something like this:

```
{
  "generalInfo": {
    "name": "Tipologia ",
    "ross_heidecke": 123,
    "index": 1.3
  },
  "UnityCompositions": [
    {
      "text": "teste",
      "status": true
    },
    {
      "text": "teste2",
      "status": false
    }
  ],
  "BuildPatternGroups": [
    {
      "description": "teste",
      "index": 1.3,
      "options": [
        {
          "name_description": "dasasd",
          "value": 213,
          "status": true
        },
        {
          "name_description": "asdasd",
          "value": 213,
          "status": true
        },
        {
          "name_description": "adasd",
          "value": 12312,
          "status": false
        }
      ],
      "status": false
    }
  ]
}
```

### What was unclear/insufficient/not covered in the documentation

The documentation only provides a example of a simple object transaction, byt creating it and then chaining setting some other object in it:

```
return sequelize.transaction(t => {

  // chain all your queries here. make sure you return them.
  return User.create({
    firstName: 'Abraham',
    lastName: 'Lincoln'
  }, {transaction: t}).then(user => {
    return user.setShooter({
      firstName: 'John',
      lastName: 'Boothe'
    }, {transaction: t});
  });

}).then(result => {
  // Transaction has been committed
  // result is whatever the result of the promise chain returned to the transaction callback
}).catch(err => {
  // Transaction has been rolled back
  // err is whatever rejected the promise chain returned to the transaction callback
});
```

### If possible: Provide some suggestion on how we can enhance the docs

Include a better expiation on how to create a transaction to save a deeply nested object

### Additional context

Here is what I expected to be able to do, how are we supposed to save this?

```
return db.sequelize
      .transaction((t) => {
        return Typology.create(
          {
            name,
            ross_heidecke,
            index,
          },
          { transaction: t }
        ).then((typology) => {
          UnityCompositions.forEach((uc) => {
            return UnityComposition.create(
              { ...uc, typology_id: typology.id },
              { transaction: t }
            ).then((uc) => {
              return typology.addUnityComposition(uc, {
                transaction: t,
              });
            });
          });
        });
      })
      .then(() => {
        res.status(200).json({ MSG: "SAVE_SUCCESS" });
      })
      .catch((err) => {
        res.status(500).json({ MSG: "SAVE_ERROR" });
      });
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
`forEach` doesn't wait for those calls to finish, try alternative from https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop
