### ISSUE TITLE
Sequelize failing to create table with sync()

### ISSUE THREAD

**Issue by perfoWorks** [sequelize/sequelize#12280]
I'm having trouble to create a table with sequelize sync() method. The table is not being created in the schema when I start the server

Here is my database.js file

```
const Sequelize = require('sequelize');

const sequelize = new Sequelize('test-schema', 'root', 'mypassword',{dialect:'mysql', host:'localhost'});

module.exports = sequelize;
```

Here is my model Product file

```
const Sequelize = require('sequelize');

const sequelize = require('../util/database')

const Product = sequelize.define('product', {
    id: {type: Sequelize.INTEGER, autoIncrement: true, allowNull: false, primaryKey: true},
    title: Sequelize.STRING,
    price: {type: Sequelize.DOUBLE, allowNull: false}
});

module.exports = Product;
```
and here is my server.js file

```
const express = require('express');

const sequelize = require('./util/database')

const app = express();

sequelize.sync().then(result=>{
    //console.log(result);
    app.listen(3000);
}).catch(err => {
    console.log(err);
});
```
Once I start server I get

> Executing (default): SELECT 1+1 AS result

I tried to change the name of my schema in my database file to wrong name and I get an error schema doesn't exist so I believe that connection to db is correct

Here are my installed packages

```
  "dependencies": {
    "express": "^4.17.1",
    "mysql2": "^2.1.0",
    "sequelize": "^5.21.10"
  }
```
**--------------UPDATE -----------------**
I just managed to fixed it by adding empty import of my model file in my server.js

`const product = require('./models/products')`

Now new question is why do I have to create an empty import to my model class to make it work?? What is the logic behind having unused import in server.js file to make it work??

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
