### ISSUE TITLE
Sequelize asking for multiple values of association when explicitly defining foreign key

### ISSUE THREAD

**Issue by ahsan98** [sequelize/sequelize#12284]
### I am trying to create a model with named foreign key and create a row in it.

```js
const Desk = sequelize.define('Desk', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
    },
    number: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  },
  {
    indexes: [
      {
        unique: true,
        fields: ['store_id', 'number'],
      }
    ],
    tableName: 'desk',
    underscored: true,
  });

  Desk.associate = function (models) {
    Desk.belongsTo(models.Store, {
      foreignKey: {
        allowNull: false
      }
    });
  };
```
Tried to create using
```
const data = {storeId: 1, number: 1};
Desk.create(data);
```
as well as
```
const data = {StoreId: 1, number: 1};
Desk.create(data);
```

### What do you expect to happen?

I expected the object to be created succesfully.

### What is actually happening?

I got an exception from sequelize in both scenarios. When I used storeId it said that StoreId cannot be null vice versa when I used StoreId I get the exception storeId cannot be null. Even though the table is mapped as expected in database on running sequelize.sync(). No duplicate fields there

### Environment

- Sequelize version: 5.21.7
- Node.js version: 12.6.0 
- Operating System: MacOS Catalina 10.15.4

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by soryy708** [comment]
What SQL is generated out of this?
I think it may be an issue with sequelize automatically adding an "ON DELETE SET NULL" on your foreign key which doesn't make sense for a column with a "NOT NULL" constraint. Try adding `onDelete: 'CASCADE'` and see if it fixes it.
https://sequelize.org/master/class/lib/associations/base.js~Association.html

**Comment by ahsan98** [comment]
> What SQL is generated out of this?
> I think it may be an issue with sequelize automatically adding an "ON DELETE SET NULL" on your foreign key which doesn't make sense for a column with a "NOT NULL" constraint. Try adding `onDelete: 'CASCADE'` and see if it fixes it.
> https://sequelize.org/master/class/lib/associations/base.js~Association.html
The storeId is added when onDelete and onUpdate CASCADE. I don't think the issue arises at database level but at sequelize itself. Since there are no duplicate keys in database. I think sequelize gives the error before the query is ever executed. Since I donot see any insert query running in the logs either.

**Comment by sushantdhiman** [comment]
I can't reproduce this issue, perhaps you are missing `underscored` in another table (which is missing from issue description), or defining reverse relationship with `hasOne` incorrectly

```js
(async () => {
  const Desk = sequelize.define(
    "Desk",
    {
      id: {
        type: Sequelize.BIGINT,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
      },
      number: {
        type: Sequelize.INTEGER,
        allowNull: false,
      },
    },
    {
      indexes: [
        {
          unique: true,
          fields: ["store_id", "number"],
        },
      ],
      tableName: "desk",
      underscored: true,
    }
  );

  const Store = sequelize.define(
    "Store",
    {},
    {
      underscored: true,
      tableName: "store",
    }
  );

  Desk.belongsTo(Store, {
    foreignKey: {
      allowNull: false,
    },
  });

  await sequelize.sync({ force: true });
  const s = await Store.create({});
  const d = await Desk.create({ number: 1, StoreId: 1 });
})();
```

```sql
Executing (default): DROP TABLE IF EXISTS `desk`;
Executing (default): DROP TABLE IF EXISTS `store`;
Executing (default): DROP TABLE IF EXISTS `store`;
Executing (default): CREATE TABLE IF NOT EXISTS `store` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`store`)
Executing (default): DROP TABLE IF EXISTS `desk`;
Executing (default): CREATE TABLE IF NOT EXISTS `desk` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `number` INTEGER NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `store_id` INTEGER NOT NULL REFERENCES `store` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE);
Executing (default): PRAGMA INDEX_LIST(`desk`)
Executing (default): CREATE UNIQUE INDEX `desk_store_id_number` ON `desk` (`store_id`, `number`)
Executing (default): INSERT INTO `store` (`id`,`created_at`,`updated_at`) VALUES (NULL,$1,$2);
Executing (default): INSERT INTO `desk` (`id`,`number`,`created_at`,`updated_at`,`store_id`) VALUES (NULL,$1,$2,$3,$4);
```

**Comment by ahsan98** [comment]
> I can't reproduce this issue, perhaps you are missing `underscored` in another table (which is missing from issue description), or defining reverse relationship with `hasOne` incorrectly
> 
> ```js
> (async () => {
>   const Desk = sequelize.define(
>     "Desk",
>     {
>       id: {
>         type: Sequelize.BIGINT,
>         allowNull: false,
>         primaryKey: true,
>         autoIncrement: true,
>       },
>       number: {
>         type: Sequelize.INTEGER,
>         allowNull: false,
>       },
>     },
>     {
>       indexes: [
>         {
>           unique: true,
>           fields: ["store_id", "number"],
>         },
>       ],
>       tableName: "desk",
>       underscored: true,
>     }
>   );
> 
>   const Store = sequelize.define(
>     "Store",
>     {},
>     {
>       underscored: true,
>       tableName: "store",
>     }
>   );
> 
>   Desk.belongsTo(Store, {
>     foreignKey: {
>       allowNull: false,
>     },
>   });
> 
>   await sequelize.sync({ force: true });
>   const s = await Store.create({});
>   const d = await Desk.create({ number: 1, StoreId: 1 });
> })();
> ```
> 
> ```sql
> Executing (default): DROP TABLE IF EXISTS `desk`;
> Executing (default): DROP TABLE IF EXISTS `store`;
> Executing (default): DROP TABLE IF EXISTS `store`;
> Executing (default): CREATE TABLE IF NOT EXISTS `store` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL);
> Executing (default): PRAGMA INDEX_LIST(`store`)
> Executing (default): DROP TABLE IF EXISTS `desk`;
> Executing (default): CREATE TABLE IF NOT EXISTS `desk` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `number` INTEGER NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `store_id` INTEGER NOT NULL REFERENCES `store` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE);
> Executing (default): PRAGMA INDEX_LIST(`desk`)
> Executing (default): CREATE UNIQUE INDEX `desk_store_id_number` ON `desk` (`store_id`, `number`)
> Executing (default): INSERT INTO `store` (`id`,`created_at`,`updated_at`) VALUES (NULL,$1,$2);
> Executing (default): INSERT INTO `desk` (`id`,`number`,`created_at`,`updated_at`,`store_id`) VALUES (NULL,$1,$2,$3,$4);
> ```

I just reviewed the opened issue. The code example I provided was incorrect. Sorry for the mistake. Actually the issue arises when foreign key is explicitly named, Following is the correct association example

```
Desk.belongsTo(models.Store, {
  foreignKey: {
    name: 'storeId',
    allowNull: false
  }
});
```
When foreign key is explicitly named, I am unable to create a row in the model Desk.

When I try
```
const data = {storeId: 1, number: 1};
Desk.create(data);
```
I get the error 'StoreId cannot be null' and Vice versa when I try

```
const data = {StoreId: 1, number: 1};
Desk.create(data);
```
It gives the error 'storeId cannot be null'.

**Comment by ahsan98** [comment]
I have also updated the original comment to fix the code to reproduce
