### ISSUE TITLE
`instance.describe()` works, but should it?

### ISSUE THREAD

**Issue by mmkal** [sequelize/sequelize#12296]
### What are you doing?

Trying to use `model.describe()` in `sequelize@6.0.0-beta.6`.

```js
import * as sequelize from 'sequelize'

const model = new sequelize.Model(...)
model.describe().then(console.log)
```

### What do you expect to happen?

It to work at runtime, and to surface no typescript errors.

### What is actually happening?

It works at runtime, but there's a typescript error:

```
Property 'describe' is a static member of type 'Model<any, any>' ts(2576)
```

### Additional context

Here's the line where `describe` is declared as static in js. It looks wrong to me since it uses `this`, which shouldn't be allowed for static functions: https://github.com/sequelize/sequelize/blob/8a1429d6044123bba3a3f312b2e0c74b0c829990/lib/model.js#L3195-L3197

Here's the typescript declaration: https://github.com/sequelize/sequelize/blob/5a807c514c00364d0fcd56ae682a06750c398df8/types/lib/model.d.ts#L2064

I'm not totally sure why this only started happening recently, since the code looks like it was added months ago.

See https://github.com/sequelize/umzug/pull/226 for a repro (first commit, failing on travis CI) and the workaround required (second commit, using `// @ts-ignore`) - cc @papb 

### Environment

- Sequelize version: 6.0.0-beta.6
- Node.js version: 12.
- Operating System: Windows 10
- If TypeScript related: TypeScript version: 3.9.2

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Oh, I think I know what happened. This is not a typings issue, this is actually a misunderstanding in Sequelize typings usage that also happened to me several times already. The thing is, when you declare a something as `let x: Model`, what you are declaring in fact is an instance of the `Model`. This is similar to doing `let x: Person` in which you are declaring an instance of `Person`, not a subclass of `Person`. Since in that Umzug usage we want the class itself, `typeof Model` should be used instead of `Model`.

**Comment by papb** [comment]
Edit:

> It works at runtime

Hmmm, this is weird. Reopening. I think it shouldn't.

But the good news is that it should not matter for what you want to do in Umzug :)

**Comment by SimonSchick** [comment]
```
  static get queryInterface() {
    return this.sequelize.getQueryInterface();
  }

  static get queryGenerator() {
    return this.queryInterface.queryGenerator;
  }
```

Works as intended I guess, this is certainly weird and would be nice to refactor but..

**Comment by mmkal** [comment]
@papb I think you're right, the types are just confusing and I now suspect there's some type wrongness in umzug tests.

When I said it works at runtime I just meant that the types said something was wrong but the test succeeds. I'll look into it a bit more in umzug and reopen if I think there's anything wrong with sequelize.
