### ISSUE TITLE
Idea: funding

### ISSUE THREAD

**Issue by soryy708** [sequelize/sequelize#12291]
The maintainers and other team members of Sequelize contribute very little time due to it being voluntary and unpaid. Most of the time they're busy with their day work.

This causes a large backlog of issues, and some issues take very long (years) to get resolved.

Some projects (like [webpack](https://webpack.js.org/)) actually raise funds to fund the development and maintenance of the open source project.

Some options:
* [opencollective](https://opencollective.com/)
* [npm-fund](https://docs.npmjs.com/cli-commands/fund.html)
* [github sponsors](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/)
* [patreon](https://www.patreon.com/)

**Comment by sushantdhiman** [comment]
I used to get such emails when Sequelize was popular, nowadays not much. But just like before, this project has never looked for any financial funding. If you want to help only way to do so is by writing code or helping others in threads / StackOverflow.

I do like the idea of bounties but

1. Not sure if our current user-base is willing to support this project by bounties
2. There are other tasks like improving code-base internally which I am sure will never get any user interest (for bounties) but are important for future of this project.
3. Not sure which platform works best for bounties, keeping (2) in mind

All choices you have listed are good platforms, but they are ultimately based on donations. For personal reasons, I won't accept any kind of donation money. So those platforms won't work for our use-case.

May be there are other ways, like commercial licensing but that will require shipping some features which are not available for others + that could become a support hell for me.

So this project will keep on going as long as quality contributions keep coming from developers who are using it.

**Note :-** _I am pinning this so everyone knows what is my stance on funding_

**Comment by ronyeh3** [comment]
Hi,
first of all im grateful your work, this project make our life much easier.

i believe that time has come, and you need to embrace new approach so the project stays relevant, in this modern times so people want ditch it in favor of other solution.
the humble way doesn't seem fit the scale of project anymore , ive seen mush smaller project raising thousands from sponsors, be sure, that is mainly a gratitude from those who dont have time to actively contribute the project. but wants to help. and happily done.
beside sponsors, a bounty on one of the 800 open issues, will encourage the developer to resolve it by caring and bring food the his table, then you not?

we are all share the same willing to make the project better, robust. better pragmatic actions must be take in favor of your community.

**Comment by papb** [comment]
Hello! Thank you very much for this thought. I'm happy to know that some people think it is plausible for us maintainers to have monetary incentive to keep working.

However, personally, I don't think I'd be comfortable receiving money for this. It would certainly give me a sense of duty to solve more issues, and I would definitely work more on here due to this feeling, but it would make contributing to Sequelize an obligation instead of something I just do whenever I want in my free time. I don't think I would want that (unless the amount of money could replace my current job, which would make this probably one of the best jobs ever, but I doubt that would be the case :sweat_smile:).

**Comment by RongxinZhang** [comment]
Would you all consider advertising from companies if they were done well or in a non-obtrusive way?
I see a lot of podcasters, bloggers doing sponsorships from large companies and they seem to do alright.

**Comment by evenfrost** [comment]
Can anyone from the maintainers create a profile for Sequelize on https://opencollective.com/? I believe it would be a good start.

**Comment by papb** [comment]
Hi @evenfrost, thanks for the suggestion, I will discuss again with other maintainers the possibility of funding :)

**Comment by soryy708** [comment]
Looks like someone created a profile on [opencollective.com](https://opencollective.com/sequelize) and configured and wrote a [funding.yml](https://github.com/sequelize/sequelize/blob/main/.github/FUNDING.yml). Has this issue been resolved and therefore ought to be closed?

**Comment by WikiRik** [comment]
Yes, we can indeed close this issue. If people are interested in how we divide the donations over the team members they can look to https://github.com/sequelize/meetings/tree/main/analyse-contributions
