### ISSUE TITLE
There's no way to know alias for nested entity field

### ISSUE THREAD

**Issue by bssergy** [sequelize/sequelize#12307]
I need to use mysql CONCAT to my nested entity fields, but when I try to use col() function to pass fields like arguments, they don't have aliases and query craches.

Here is small demo for the situation:

```js
const sequelize = new Sequelize('sqlite::memory:');

class A extends Model {}
A.init({
  a1: DataTypes.STRING,
  a2: DataTypes.STRING,
}, { sequelize, modelName: 'A' });

class B extends Model {}
B.init({
  b1: DataTypes.STRING,
  b2: DataTypes.STRING
}, { sequelize, modelName: 'B' });

class C extends Model {}
C.init({
  c1: DataTypes.STRING,
  c2: DataTypes.STRING
}, { sequelize, modelName: 'C' });

class D extends Model {}
D.init({
  d1: DataTypes.STRING,
  d2: DataTypes.STRING
}, { sequelize, modelName: 'D' });

A.hasOne(B, { as: 'B' });
B.hasOne(C, { as: 'C' });
C.hasOne(D, { as: 'D' });

sequelize.sync()
  .then(() => A.findAll({
    include: [{
      model: B,
      as: 'B',
      include: [{
        model: C,
        as: 'C',
        include: [{
          model: D,
          as: 'D',
          where: {
            [Op.and]: [{ d1: 'test' }, fn('CONCAT', col('d1'), col('d2'))]
          }
        }]
      }]
    }]
  }))
  .then(result => {
    console.log(result);
  });
```

As the result I've got the next sql:

```sql
SELECT
  `A`.`id`,
  `A`.`a1`,
  `A`.`a2`,
  `A`.`createdAt`,
  `A`.`updatedAt`,
  `B`.`id` AS `B.id`,
  `B`.`b1` AS `B.b1`,
  `B`.`b2` AS `B.b2`,
  `B`.`createdAt` AS `B.createdAt`,
  `B`.`updatedAt` AS `B.updatedAt`,
  `B`.`BId` AS `B.BId`,
  `B->C`.`id` AS `B.C.id`,
  `B->C`.`c1` AS `B.C.c1`,
  `B->C`.`c2` AS `B.C.c2`,
  `B->C`.`createdAt` AS `B.C.createdAt`,
  `B->C`.`updatedAt` AS `B.C.updatedAt`,
  `B->C`.`CId` AS `B.C.CId`,
  `B->C->D`.`id` AS `B.C.D.id`,
  `B->C->D`.`d1` AS `B.C.D.d1`,
  `B->C->D`.`d2` AS `B.C.D.d2`,
  `B->C->D`.`createdAt` AS `B.C.D.createdAt`,
  `B->C->D`.`updatedAt` AS `B.C.D.updatedAt`,
  `B->C->D`.`DId` AS `B.C.D.DId`
FROM
  `As` AS `A`
  LEFT OUTER JOIN `Bs` AS `B` ON `A`.`id` = `B`.`BId`
  LEFT OUTER JOIN (
    `Cs` AS `B->C`
    INNER JOIN `Ds` AS `B->C->D` ON `B->C`.`id` = `B->C->D`.`DId`
    AND (
      `B->C->D`.`d1` = 'test'
      AND CONCAT(`d1`, 'd2')
    )
  ) ON `B`.`id` = `B->C`.`CId`;
```

As you can see, field d1 handled correct like \`B->C->D\`.\`d1\`, but all what I need to pass into fn() as argument - didn't handle at all - CONCAT(\`d1\`, 'd2').

Of course, I can hardcode this alias like fn('CONCAT', col('\`B->C->D\`.\`d1\`'), col('\`B->C->D\`.\`d2\`')) but it's terrible. I don't know how does alias looks like while I'm coding.

I think it's very popular usecase and there are should be some correct way to use functions for nested entities with handled aliases.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
