### ISSUE TITLE
Create Junction Table

### ISSUE THREAD

**Issue by scriptsure** [sequelize/sequelize#12302]
## Issue Description
I have already tried to submit this question on StackOverflow and no one knew the answer. I have a VERY simple question. 

Is it possible to create a record in a junction table stored in mysql within a single .create method? So if you have Model1 and Model2 being created could it also write to the junction table in Model3 at the same time? OR must we call the .addModel3 for each junction entity...

### What was unclear/insufficient/not covered in the documentation
The documents do not address this. They do indicate that you perform creates then an add call...
 
Write here.

### If possible: Provide some suggestion on how we can enhance the docs

Write here.
Just indicate that you can or cannot add the through table to an include array of a create method...

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [x ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/commit/6d87cc583da1250e3f7b968f215b7f736c22347e
