### ISSUE TITLE
Sequelize-CLI does not work on EC2 linux instance

### ISSUE THREAD

**Issue by Mahagney** [sequelize/sequelize#12311]
## Issue Description
I developed a project using Sequelize with Postgres and Nodejs. Everything worked well until I moved to EC2 Linux instance. I created a new ec2 instance and connected to the same RDS instance as I do from localhost. 
Also when I run the server from Localhost on windows everything works and it can fetch data from DB but when I start it on Linux using ec2 I don't get any response in the promise I use to fetch data.
I also tried with a local database on ec2 instance and had the same result.
### What are you doing?
I try to run Sequelize migrate and I don't get an answer even if I write another hostname, but everything works just fine from localhost using windows, on localhost if I write a bad host I get "connect ETIMEDOUT" but nothing on EC2 instance and with the correct host I can run migrations and everything is ok. RDS works well while I can connect from ec2 to RDS using psql.

### What do you expect to happen?

I expect to run migrations and when I start the server to connect to DB and fetch data.

### What is actually happening?
I just run migrations and get the following output and nothing more.

```
$ npx sequelize-cli db:migrate

Sequelize CLI [Node: 14.3.0, CLI: 5.5.1, ORM: 5.21.2]

Loaded configuration file "database/config/config.js".
Using environment "development".
$
```

### Additional context

I also asked a question on StackOverflow but no luck. 
https://stackoverflow.com/questions/61911924/connect-to-postgres-rds-from-ec2-using-sequelize/62000951#62000951

### Environment

- Sequelize version: 5.21.2
- Node.js version: v14.3.0
- Operating System: ami-0a9e2b8a093c02922   and  Ubuntu Server 18.04 LTS  same behaviour

**Comment by mroobert** [comment]
Solution for this problem is to install a version < 14 for node js. Instal nvm ( node version manager) on the EC2 and then install a node js version < 14 and then the migrations + seeds will work.

**Comment by Mahagney** [comment]
> Solution for this problem is to install a version < 14 for node js. Install nvm ( node version manager) on the EC2 and then install a node js version < 14. After this go to the project folder run npm install and the migrations + seeds should work.

It works. Thank you!

**Comment by sushantdhiman** [comment]
It looks related to pg https://github.com/sequelize/sequelize/issues/12158

**Comment by bradley** [comment]
So does sequelize not work with Node 14 or higher?

**Comment by sfarthin** [comment]
> So does sequelize not work with Node 14 or higher?

Sequelize doesn't seem to work with Node 14 from what I can tell

**Comment by gildniy** [comment]
It don't work with Node 14 :'(
