### ISSUE TITLE
Accessing result with await

### ISSUE THREAD

**Issue by dyanakiev** [sequelize/sequelize#12314]
```
const [row] = await Tag.findOrCreate({...});

if (!row.name) {
    row.name = 'test'
    await row.save();
}
```
Is this good way to access the row result, mainly the deconstructing [row] part?

**Comment by sushantdhiman** [comment]
Yes

**Comment by dyanakiev** [comment]
Okay, thank you, i firstly tried directling using
```
const row = await Tag.findOrCreate({...});
```
and surprisingly i couldnt access row.name, row.save(), sorry for the stupid question im quite new in node/js

**Comment by sushantdhiman** [comment]
You can always check return type of various method here https://sequelize.org/master/class/lib/model.js~Model.html

Some return array and some return row directly
