### ISSUE TITLE
OR block with nested AND not generated to SQL

### ISSUE THREAD

**Issue by tapz** [sequelize/sequelize#12319]
## Issue Description

An OR block is ignored in a query when generating SQL. Changing the order of the OR blocks causes always only the last one to be generated. The nested AND is generated correctly when moving the first OR block after the last one.

### What are you doing?

```js
await MyTable.findAll({
where: {
  checkedAt: null,
  abcId: {[Op.not]: null},
  [Op.or]: [
    {cancelledAt: {[Op.lt]: moment().subtract(3, 'minutes')}},
    {[Op.and]: [
      {orderId: null},
      {orderDate: {[Op.lt]: moment().subtract(2, 'hours')}}
    ]}
  ],
  [Op.or]: [
    {something: {[Op.not]: 'qwerty'}},
    {fooBar: {[Op.not]: null}}
  ]
}
});
```

### What do you expect to happen?

```
WHERE (deleted_at IS NULL 
AND (
(something != 'qwerty' OR foo_bar IS NOT NULL) 
AND (cancelled_at < '...' OR (order_id IS NULL AND order_date < '...')) 
AND (something != 'qwerty' OR foo_bar IS NOT NULL) 
AND checked_at IS NULL AND abc_id IS NOT NULL)
);
```

### What is actually happening?

```
WHERE (deleted_at IS NULL 
AND (
(something != 'qwerty' OR foo_bar IS NOT NULL) 
AND checked_at IS NULL AND abc_id IS NOT NULL)
);
```

### Environment

- Sequelize version: 5.21.10
- Node.js version: 12.16.3
- Operating System: MacOS Catalina 10.15.4 (19E287)

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X] I don't know, I was using PostgreSql, with connector library version 8.2.1 and database version 9.6.17

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
:) Yeah it wont work, object key is `Op.or` so last one will always override. For example

```js
{
  a: 1,
  a: 2
}
```
 will always give you

```js
{
  a: 2
}
```

For your usecase, perhaps wrap both `Op.or` blocks under `Op.and`

```js
{
  where: {
    checkedAt: null,
    abcId: {
      [Op.not]: null
    },
    [Op.and]: [{
        [Op.or]: [{
          cancelledAt: {
            [Op.lt]: moment().subtract(3, 'minutes')
          }
        }, {
          [Op.and]: [{
            orderId: null
          }, {
            orderDate: {
              [Op.lt]: moment().subtract(2, 'hours')
            }
          }]
        }]
      }, {
        [Op.or]: [{
          something: {
            [Op.not]: 'qwerty'
          }
        }, {
          fooBar: {
            [Op.not]: null
          }
        }]
      }
    }
  }
}
```

**Comment by tapz** [comment]
Didn't realize they actually are keys :-) Sequelize should provide something like Op.or2, Op.or3 etc. so that I would not need to add more nesting.
