### ISSUE TITLE
afterConnect Hook with MSSQL (tedious)

### ISSUE THREAD

**Issue by ShaharHD** [sequelize/sequelize#12323]
## Issue Description

While trying to inject prepared statements like I do with Postgres, but this time with MSSQL (tedious) - once I'm trying to execute the request I'm getting the following error:

`Database connection failed: Requests can only be made in the LoggedIn state, not the SentClientRequest state`

### What are you doing?

The imports:
```typescript
import { Connection, Request } from 'tedious';
```

The hook:
```typescript
public static async afterConnect(connection, options): Promise<void> {
    const client = connection['resource'] as Connection;

    let request = new Request('select 42', (err, rowCount, rows) => {
      console.log(`${err} ${rowCount} rows`);
    });

    client.execSql(request);
  }
```

### What do you expect to happen?

The query request to be executed.

### What is actually happening?

It seems that when sequelize passes the connection to the `afterConnect` hook, it will try to execute other requests during or after it still have an active request with the connection (the `SELECT 1+1 AS result`)- and I couldn't find a way for me to "chain" the requests like `tedious` documentation suggests.

### Additional context

None

### Environment

- Sequelize version: 5.21.11
- Node.js version: 12.16.3
- Operating System: Mac OS, alpine (docker)
- TypeScript version: 3.9.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): `mssql`
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ShaharHD** [comment]
After some digging inside the sequelize code base (and maybe understanding some of the basic event flow) - I found this workaround:


```js
public static async afterConnect(connection, options): Promise<void> {
    const client = connection['resource'] as Connection;

    await new Promise((resolve) => {
      let request = new Request('select 42', (err, rowCount) => {
        logger.debug(method, `${err} - ${rowCount} rows`);

        resolve();
      });

      client.execSql(request);
    });
}
```

**Comment by sushantdhiman** [comment]
`afterConnect` hook does not exclusively grant connection to hooked method, there can be multiple hooks. As `tedious` requires caller to serially call their queries one by one, `afterConnect` may not work well for you. Sequelize and other hooks will still use that connection.

With v6 this behavior has been improved, you can now call `connection.queue.enqueue`  to add your query to queue https://github.com/sequelize/sequelize/blob/59b8a7bfa018b94ccfa6e30e1040de91d1e3d3dd/lib/dialects/mssql/query.js#L118

For v5, I will suggest to get a connection directly from pool which no one else is using.

```js
const connection = await sequelize.connectionManager.getConnection();

// do something with connection

// release it back to pool, so it can be reused by other queries
await sequelize.connectionManager.releaseConnection(connection)
```

**Comment by ShaharHD** [comment]
@sunshinewyin I'm on v5 - as v6 is not production ready yet.

The issue is that I'm using the `afterConnect` event to inject prepared statements into the MSSQL - so getting a random connection defeats the whole purpose of the event ...

for now - the solution I have on top - actually seems to solve the problem (I'm not using any other hooks on the connection event).

The question is what is `connection. previous`? from what I could gather, it seems I'm running just before the `SELECT 1+1` - and main issue I was having was that my commands were returning too soon (hence the solution with the Promise / resolve)

**Comment by sushantdhiman** [comment]
`previous` comes from resource lock

https://github.com/sequelize/sequelize/blob/41237ae1ef63d2f3258dc0f69a926c4a96647ff0/lib/dialects/mssql/resource-lock.js#L8

You can perhaps use this pattern to lock your queries

https://github.com/sequelize/sequelize/blob/41237ae1ef63d2f3258dc0f69a926c4a96647ff0/lib/dialects/mssql/query.js#L115
