### ISSUE TITLE
findOrCreate should accept 'fields' to save

### ISSUE THREAD

**Issue by sonirico** [sequelize/sequelize#12325]
### Is your feature request related to a problem? Please describe.

`CreateOptions` has a optional property named 'fields' which describes which fields are writable, in order to prevent additional and/or malicious fields sent on payloads persisted in databases. However, `FindOrCreateOptions` does not provide such configuration to be set. Is that intentional?

### Describe the solution you'd like
Some configuration flag to enable writes applicable to certain fields, as `CreateOptions` does.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
`findOrCreate` does pass options to `create` method. I think typings can be improved. Please send a PR if you can spare some time

**Comment by sonirico** [comment]
Ok, I will spare some time to do it this week.

**Comment by sushantdhiman** [comment]
Fixed by 12338, Thanks @sonirico
