### ISSUE TITLE
EExist: File already exists when using SQLite3

### ISSUE THREAD

**Issue by lakeshadow0** [sequelize/sequelize#12329]
## Issue Description

I'm currently just trying to use SQLite 3 with the following,

```
new Sequelize({
    dialect: 'sqlite',
    storage: '/path/to/db/db.sqlite'
});
```
but when I try to sync it, I get the error 

```
EEXIST: file already exists, mkdir '/path/to/db'
```

### Additional context

I found this PR https://github.com/sequelize/sequelize/pull/11853/commits, but I'm not sure it's where it's coming from.

jetpack.dir says it'll throw an error if the path exists but is a file not a directory.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): sqlite
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Are you sure you don't have a file called `db` in the folder `/path/to`?

**Comment by lakeshadow0** [comment]
I do, but the error suggests it's trying to make a directory. 

Correct me if I'm wrong, but even if it does exist shouldn't I still be able to read from an existing database?

**Comment by papb** [comment]
If you have a file called `db` in `/path/to`, then you can't have a file called `db.sqlite` in `/path/to/db`, since `/path/to/db` is not even a folder to begin with, so it can't have a `db.sqlite` folder inside.

Sequelize is seeing that you have requested the file to be `/path/to/db/db.sqlite`, and is trying to create it for you, but since `/path/to/db` cannot be created as a folder (since it already exists and is a **file**, not a folder), you are getting an error.

If your database file happens to be this `db` (extensionless) file, then just use `storage: '/path/to/db'` instead.

**Comment by lakeshadow0** [comment]
Oh oof, I misread what you originally wrote. My apologies. The current path ``/path/to/db`` is a directory with the file ``db.sqlite`` inside. If I delete the file it still errors (``/path/to/db/db.sqlite``) but if I delete ``/path/to/db`` it works.

**Comment by papb** [comment]
Hmmm. That is really weird.

I just tried to reproduce but couldn't. The following code executed just fine multiple times with `sequelize@6.0.0-beta.6`:

```js
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize({
	dialect: 'sqlite',
	storage: 'foo/bar/baz/qux/storage.db'
});
sequelize.sync();
```

Are you doing something more complex? Perhaps you tried to make the issue super minimal but then the issue disappeared :thinking:

**Comment by lakeshadow0** [comment]
I'm not quite sure what I did, but the issue isn't happening. I had to pull the git repo again and after doing another dependency install it resolved. :shrug:

**Comment by Nisthar** [comment]
@lakeshadow0 i have the same issue with sequelize + electron. Nothing seems to work. only in memory is working for me.

**Comment by nbriz** [comment]
i'm also having this same issue, but only when i use sequelize version ^6.0.0 (if i drop down to 5 then i don't have the issue)

**Comment by triadium** [comment]
The mkdir(Sync) function had no recursive option until node.js v10.12.0.

**Comment by papb** [comment]
@triadium Ouch, thank you very much for pointing that out.

@Nisthar and @lakeshadow0 can you confirm you are using a version of node older than v10.12.0?

**Comment by felixbrucker** [comment]
I got a user with the same problem, he was using node 10.0.0 and updating to the current LTS (12.18.3) fixed the issue for him.

**Comment by nbriz** [comment]
@felixbrucker @papb  i was having the issue on an older version of node as well. just updated to LTS (12.18.3) && re-ran the project with sequalize 6.3.3 and the error did not show up this time.

**Comment by lakeshadow0** [comment]
@papb I'm on 14.4. I assume when I pulled everything down I also threw in a update command for node.

**Comment by AhmedOuali** [comment]
I had the same issue which disappeared when i upgraded nodejs from version 8.17 to version 12.18.
Now it works fine !!!

**Comment by kgaregin** [comment]
here's solution i found:

`new Sequelize({dialect: 'sqlite', storage, dialectOptions: {mode: 2}});`

essential part is a `dialectOptions: {mode: 2}` which means read/write access for sqlite3 repo.

some other codes, just in case:
```
OPEN_READONLY = 1
OPEN_READWRITE = 2
OPEN_CREATE = 4
OPEN_FULLMUTEX = 65536
OPEN_URI = 64
OPEN_SHAREDCACHE = 131072
OPEN_PRIVATECACHE = 262144
```

**Comment by mentormaya** [comment]
A simple solution for me is to this problem is to wrap the mkdirSync() from connection-manager.js of the SQLite dialect in a try-catch block and it solves the problem for me. 

i am currently working with : 
"electron": "^4.0.1",
"sequelize": "^6.3.5",
"sqlite3": "^5.0.0",

if (!options.inMemory && (options.readWriteMode & this.lib.OPEN_CREATE) !== 0) {
      // automatic path provision for `options.storage`
      try {
        fs.mkdirSync(path.dirname(options.storage), { recursive: true });
      } catch (error) {
        console.log('coulnot make dir')
      }
    }

**Comment by WelliRigo** [comment]
> here's solution i found:
> 
> `new Sequelize({dialect: 'sqlite', storage, dialectOptions: {mode: 2}});`
> 
> essential part is a `dialectOptions: {mode: 2}` which means read/write access for sqlite3 repo.
> 
> some other codes, just in case:
> 
> ```
> OPEN_READONLY = 1
> OPEN_READWRITE = 2
> OPEN_CREATE = 4
> OPEN_FULLMUTEX = 65536
> OPEN_URI = 64
> OPEN_SHAREDCACHE = 131072
> OPEN_PRIVATECACHE = 262144
> 

I have a different problem, i'm trying to use like this example, but in :memory:, however sequelize doesn't accept the OPEN_SHAREDCACHE code.
```
    dialect: 'sqlite',
    storage: ':memory:',
    dialectOptions: {
      mode: 131072 // also tested with sqlite3.OPEN_SHAREDCACHE
    },
```

**Comment by ephys** [comment]
The `mode` parameter is passed as-is to [sqlite3](https://github.com/TryGhost/node-sqlite3/wiki/API). Is is possible `OPEN_SHAREDCACHE` is not compatible with in-memory anonymous databases?

**Comment by WelliRigo** [comment]
I don't think so. SQLite docs shows that it is possible to have in-memory cached databases:

> Enabling shared-cache for an in-memory database allows two or more database connections in the same process to have access to the same in-memory database. An in-memory database in shared cache is automatically deleted and memory is reclaimed when the last connection to that database closes. [link](https://www.sqlite.org/sharedcache.html)

Also Sequelize Docs:

> The following fields may be passed to SQLite dialectOptions: readWriteMode: Set the opening mode for the SQLite connection. Potential values are provided by the sqlite3 package, and can include sqlite3.OPEN_READONLY, sqlite3.OPEN_READWRITE, or sqlite3.OPEN_CREATE. See the [SQLite C interface documentation for more details](https://www.sqlite.org/c3ref/open.html).

**Comment by ephys** [comment]
Testing against sqlite3 directly, I get the same error:

```
> const SQLite = require('sqlite3')
> new SQLite.Database(':memory:', 131072, console.log)
> [Error: SQLITE_MISUSE: bad parameter or other API misuse] {
  errno: 21,
  code: 'SQLITE_MISUSE'
}
```

I think you need to specify whether it's readwrite or readonly because these worked, but I don't know enough about sqlite to guarantee it:

```typescript
new SQLite.Database('', SQLite.OPEN_SHAREDCACHE | SQLite.OPEN_READ, console.log)
new SQLite.Database('', SQLite.OPEN_SHAREDCACHE | SQLite.OPEN_READONLY, console.log)
```

---

Yes, the Sequelize doc is outdated. The right option is `mode`

**Comment by ephys** [comment]
According to [sqlite's docs](https://www.sqlite.org/c3ref/open.html), you must always use one of the following options:
- `SQLITE_OPEN_READONLY`
- `SQLITE_OPEN_READWRITE`
- `SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE`

And on top of these you can add extra options such as `SQLITE_OPEN_SHAREDCACHE`

So specifying the mode to one of those:
- `SQLite.OPEN_SHAREDCACHE | SQLite.OPEN_READWRITE`
- `SQLite.OPEN_SHAREDCACHE | SQLite.OPEN_READONLY` 
- `SQLite.OPEN_SHAREDCACHE | SQLite.OPEN_READWRITE | SQLite.OPEN_CREATE`

Seems to be what sqlite requires

**Comment by WelliRigo** [comment]
Thank you very much!!!
I think part of the problem was my ignorance about the use of operator `|` to associate multiple modes. 

But looks like there's still a problem at sequelize when I use storage as `:memory:` and mode as `SQLite.OPEN_SHAREDCACHE | SQLite.OPEN_READWRITE`. It doesn't create a shared cache in-memory database. I have no hypothesis of the reason why.

An alternative solution that worked for me is to use mode `SQLite.OPEN_URI | SQLite.OPEN_READWRITE` to inform that the storage info is an URI and set storage as `file::memory:?cache=shared`. [sqlite uri](https://www.sqlite.org/uri.html).

The code:
```
  const sequelize = new Sequelize({
    dialect: 'sqlite',
    storage: 'file::memory:?cache=shared',
    dialectOptions: {
      mode: SQLite.OPEN_URI | SQLite.OPEN_READWRITE
    }
  }
```
