### ISSUE TITLE
bulkCreate updates null values in the table.

### ISSUE THREAD

**Issue by taran-1898** [sequelize/sequelize#12324]
I have a table I need to use bulkCreate (updateOnDuplicate) to insert data into it.
Some random columns can come as null at times. It updates the previously filled values in this field to null if it is updating.

I expect it to update only the values which have a value and ignore null fields.

### Environment

- Sequelize version: 3.32.1
- Node.js version: 10.17.0
- Operating System: Ubuntu 18.04

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [~] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
v3 not supported

**Comment by sushantdhiman** [comment]
And is a security risk if you are using it in production
