### ISSUE TITLE
DISTINCT query not working with include in attributes

### ISSUE THREAD

**Issue by himanshu31shr** [sequelize/sequelize#12326]
### What are you doing?

I am including additional attribute, while the attributes are being automatically generated. Now, this attribute contains `DISTINCT` which should go on top or there should be a flag or any other way to move the included attribute to the top.

Please see the code below:
```
Model.findAll({
       where: Sequelize.literal('Some query here'),
       attributes: {
               include: [[Sequelize.literal('DISTINCT subscriber.id'), 'dId']]
       },
       include: [{
           model: Model,
           include: IncludeArray
       }],
})
```

### What do you expect to happen?

Main aim is to get distinct row, with generated attributes. I cannot change the other contexts, as the system might break because of interdependent keys between modules. Is there a way to move the included attribute to the top of the attributes list, allowing `DISTINCT` to work as per its operation.

### What is actually happening?

Currently, as `DISTINCT` is somewhere in between the attributes, it is not returning distinct rows

### Environment

- Sequelize version: 4.44.3 
- Node.js version: 9.11.x 
- Operating System: Ubuntu 18

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using MySQL, with database version 14.14

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
v4 is not supported. It is a security risk if you are using it in production. If you still expect some help, Please present your case as a SSCCE https://github.com/papb/sequelize-sscce
