### ISSUE TITLE
Setting attribute in join table of many to many relationship in typescript

### ISSUE THREAD

**Issue by mgljinchin** [sequelize/sequelize#12321]
### What are you doing?
I have many to many relationship between Properties and Currency model and the join property_currency model for junction table. Migration files are written accordingly and database tables are created correctly. So I am trying to add row to property_currency model in db and set rate column of this new row.

Here is property, currency and property_currency models

    export class PROPERTIES extends Model {
      public userid!: number;
      public id!: number;
      public property_name!: string;
      public addCurrency!: HasManyAddAssociationMixin<CURRENCY, number>;
      public getCurrencies!: HasManyGetAssociationsMixin<CURRENCY>;
      public hasCurrency!: HasManyHasAssociationMixin<CURRENCY, number>;
      public countCurrencies!: HasManyCountAssociationsMixin;
      public createCurrency!: HasManyCreateAssociationMixin<CURRENCY>;
      public static associations: {
        projects: Association<PROPERTIES, CURRENCY>;
      };
    }
    PROPERTIES.init(
      {
        id: {
          allowNull: false,
          autoIncrement: true,
          primaryKey: true,
          type: DataTypes.INTEGER,
        },
        property_name: {
          allowNull: true,
          type: DataTypes.STRING(50),
        }
      },
      {
        sequelize,
        tableName: "properties",
        timestamps: true,
      }
    );

    CURRENCY.belongsToMany(PROPERTIES, {
      as: "Properties",
      through: "property_currency",
      foreignKey: "currency_id",
      otherKey: "property_id",
    });

    PROPERTIES.belongsToMany(CURRENCY, {
      as: "Currency",
      through: "property_currency",
      foreignKey: "property_id",
      otherKey: "currency_id",
    });

    export default PROPERTIES;

** Currency model
```
export class CURRENCY extends Model {
  public id!: number;
  public name: string;
  public short_name: string;
  public rate: number;
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}

CURRENCY.init(
  {
    id: {
      autoIncrement: true,
      primaryKey: true,
      type: DataTypes.INTEGER,
    },
    name: {
      allowNull: true,
      type: DataTypes.STRING(50),
    },
    short_name: {
      allowNull: true,
      type: DataTypes.STRING(10),
    },
  },
  {
    sequelize,
    tableName: "currency",
    timestamps: true,
  }
);

``` 

Here is the Property_currency model
```
class PROPERTY_CURRENCY extends Model {
  public id!: number;
  public property_id: number;
  public currency_id: number;
  public rate: number;
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}

PROPERTY_CURRENCY.init(
  {
    id: {
      autoIncrement: true,
      primaryKey: true,
      type: DataTypes.INTEGER,
    },
    property_id: {
      allowNull: true,
      type: DataTypes.INTEGER,
    },
    currency_id: {
      allowNull: true,
      type: DataTypes.INTEGER,
    },
    rate: {
      allowNull: true,
      type: DataTypes.DOUBLE,
    }
  },
  {
    sequelize,
    tableName: "property_currency",
    timestamps: true,
  }
);
export default PROPERTY_CURRENCY;
```

### What do you expect to happen?

When I call addCurrency like following, it should add row to property_currency table and set rate column.
```
let property = await Properties.findByPk(property_id);
let currency = await Currency.findByPk(currency_id);
property.addCurrency(currency, {through: { rate: rate}});
```

### What is actually happening?

Instead I get the following error
```
Object literal may only specify known properties, and 'through' does not exist in type 'HasManyAddAssociationMixinOptions'
```

### Environment

- Sequelize version: 5.21.7 
- Node.js version: 12.16.2 
- Operating System: Ubuntu 18.04
- If TypeScript related: TypeScript version: 3.8.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
-   I don't know, I was using POSTGRES, with connector library version XXX and database version 12.3-1

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
-  No, I don't have the time and I wouldn't even know how to start.

**Comment by leovux** [comment]
i stuck 10 days with this :(

**Comment by otmi100** [comment]
The workaround of @timbilt does work, but it would be nice if the types are fixed. Please do not close the issue.

**Comment by eziz-hudayberdiyev** [comment]
When using many-to-many relationship mixins need to be declared with `BelongsToMany...`. Change your code with below:
`HasMany...<TModel, TModel['id']>` => `BelongsToMany...<TModel, TModel['id']>`

**Comment by ephys** [comment]
I agree, this does not seem to be a bug. You're using `HasMany` types, but your association is a `BelongsToMany` one.
