### ISSUE TITLE
Is it possible using model instance to update the value of the ID column ?

### ISSUE THREAD

**Issue by gabrielborc** [sequelize/sequelize#12331]
## Issue Description

So, Is it possible using model instance to update the value of the ID column, for example?

```js
const object = model.findByPk(1);
object.update({id: 2}); 
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Yes

**Comment by gabrielborc** [comment]
My Log, don't update the value of the ID column

```
{
  id: 'setting_header2',
  description: 'Configurações do cabeçalho da loja2.',
  values_default: {
    backgroundColor: '#0000ff2',
    color: '#fff7ff2',
    name_store: 'Nome da Loja2'
  }
}

Executing (default): UPDATE `settings` SET `description`=$1,`values_default`=$2,`updated_at`=$3 WHERE `id` = $4
```,

**Comment by sushantdhiman** [comment]
Can you try with

```js
instance.changed('id');
instance.update(data)
