### ISSUE TITLE
[Op.like]: combinations with [Op.any] example from documentation throws SQL error

### ISSUE THREAD

**Issue by MateoArgalle** [sequelize/sequelize#12339]
I am using the like and any combination to get a query like this
SELECT * FROM FACEBOOK
 WHERE FBK_PUBLICACION LIKE '% SEGURIDAD%' OR FBK_PUBLICACION LIKE '% MAESTRO%'

but by following the steps in the documentation
I get an error Incorrect syntax near the keyword 'ANY'

How can I implement it to get that result

I am using mmsql

**Comment by sushantdhiman** [comment]
Can you show the documentation link?

**Comment by MateoArgalle** [comment]
https://sequelize.org/master/manual/model-querying-basics.html

**Comment by MateoArgalle** [comment]
I could already solve it in another way, now I have another problem as I can bring the information from a table that I do not create but someone else. What is the procedure to obtain the data from that table

**Comment by sushantdhiman** [comment]
![image](https://user-images.githubusercontent.com/9989487/83937241-c5bd7300-a7e8-11ea-985b-cd737d117bb5.png)

Documentation also state that this only works for `Postgres`
