### ISSUE TITLE
Another Error: WHERE parameter "XX" has invalid "undefined" value

### ISSUE THREAD

**Issue by jayheavner** [sequelize/sequelize#12334]
## Issue Description

WHERE parameter "id" has invalid "undefined" value. No SQL statement generated. A Raw query works just fine.

### What are you doing?

\\ This doesn't work
`const update = await sequelize.models.AdministrativeCalendar.update({ isActive: true }, { where: 11, logging: console.log});
`
\\ This does
`const [results, metadata] = await sequelize.query('UPDATE "AdministrativeCalendar" SET "isActive" = true WHERE id = 11');`

I can use other verbs against my model (find, findAll, destroy) but update, with any combination doesn't work. I've tried constructing the query multiple ways. I have other models that update just fine.

Here's my model and associations. All pretty straightforward.

```
module.exports = (sequelize, DataTypes) => {
  const AdministrativeCalendar = sequelize.define('AdministrativeCalendar', {
    name: DataTypes.STRING,
    leaveTypeId: DataTypes.INTEGER,
    startDate: DataTypes.DATE,
    endDate: DataTypes.DATE,
    canBeBooked: DataTypes.BOOLEAN,
    isActive: DataTypes.BOOLEAN,
    createdBy: DataTypes.INTEGER,
    updatedBy: DataTypes.INTEGER
  }, { 
    tableName: 'AdministrativeCalendar'
  });

  AdministrativeCalendar.associate = function(models) {
    AdministrativeCalendar.belongsTo(models.AccountType, { foreignKey: 'id' })
    AdministrativeCalendar.belongsTo(models.User, { foreignKey: 'createdBy', as: 'createdByUser' })
    AdministrativeCalendar.belongsTo(models.User, { foreignKey: 'updatedBy', as: 'updatedByUser' })
  };
```

I even removed all foreign keys from the table and all associations to see if that was the issue and it still threw the same error. I'd seen other issues where this error was thrown but the update did occur. My data is not being updated.

### What do you expect to happen?

I wanted the record with id of 11 to have the value of column isActive updated to a value of true.

### What is actually happening?

I'm getting an error: 
`Error: WHERE parameter "id" has invalid "undefined" value`

I get this error even if I don't reference the id field in the update. 

### Environment

- Sequelize version: 5.21.7
- Node.js version: 14.0.0
- Operating System: MacOs Catalina v 10.15.4

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X] I don't know, I was using POSTGRES, with connector library version XXX and database version PostgreSQL 12.2 on x86_64-apple-darwin, compiled by Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn), 64-bit

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
`where: 11` that won't work :), `where` usually accepts object or special functions. Try `where: { id: 11 }`

**Comment by jayheavner** [comment]
> `where: 11` that won't work :), `where` usually accepts object or special functions. Try `where: { id: 11 }`

I've tried every possible combination, including full object as you mention. Although, I'm pretty confident it does work if the field in question is the primary ID field.

**Comment by jayheavner** [comment]
Why was my issue closed? 

This line does not work either.
`const update = await sequelize.models.AdministrativeCalendar.update({ isActive: true }, { where: { id: 11 }, logging: console.log});
`
Throws the exact same error. I could debug the error if it wasn't nonsensical. It also does not log the SQL statement to the console.

This does work but it feels more verbose than necessary.

```
const record =  await AdministrativeCalendar.findOne({ where: { id: id }  });
record.isActive = true;
record.save();

```

**Comment by sushantdhiman** [comment]
You are using this example

```js
const update = await sequelize.models.AdministrativeCalendar.update({ isActive: true }, {
  where: { id: 11 },
  logging: console.log
}); 
```

Is this the exact code used in your application, I specifically mean `id` part being hard coded to `11`? If this exact code is used with (id = 11 hard-coded), it can **never** throw `WHERE parameter "id" has invalid "undefined" value`.

I suspect you are getting `id` as part of user input, which is `undefined` sometimes. Are you sure `id` is not undefined, Error pretty much says that.

**Comment by jayheavner** [comment]
That is the exact code I'm using. I'm copying and pasting my exact code. I've hard-coded the id to 11 to simplify the test. It clearly can throw the error. I can get replicate the error (`WHERE parameter "id" has invalid "undefined" value`) if my where clause doesn't contain the id field. 

Suspect what I'm telling you is true. It can throw the error, it does, I have the tshirt.

**Comment by sushantdhiman** [comment]
Please read my earlier response.

> That is the exact code I'm using. I'm copying and pasting my exact code. I've hard-coded the id to 11 to simplify the test.

So you are using hard coded `id=11`, in production? 

> Suspect what I'm telling you is true. It can throw the error, it does, I have the tshirt.

Yes, it will throw error, when `id` you are passing to it is `undefined`. Try `console.log` to check if that is not the case
