### ISSUE TITLE
Skip parameter in where statement when parameter value is null

### ISSUE THREAD

**Issue by perfoWorks** [sequelize/sequelize#12336]
Skip parameter in where statement when parameter value is null

```
const Sequelize = require('sequelize');
const sequelize = require('../../util/database'); 
const Speed = sequelize.define('speed', {
   id: {type: Sequelize.INTEGER, autoIncrement: true, allowNull: false, primaryKey: true},
   level: Sequelize.INTEGER,
   ...
})
module.exports = Speed;
```
and query

```
exports.getSpeed = async (req, res, next) => {
   const level = req.body.level
   try {
      const speed = await Speed.findAll({
         where: {level: level, ...}
      });
      res.status(200)
         .json({result: speed})
   }
   catch (err) {
      console.log(err)
   }
}
```

I want to get result of all speeds (skip that parameter) when level from body request is null or undefined

I found 2 solution for the so far

**1/ build where in variable with if statement to check for null values**

```
   const level = req.body.level
   let where = {}; 

   if(level)
      where = { level: level}

   try {
      const speed = await Speed.findAll({where});
```

which is a bit tedious specially when you have more columns like that or mixture of others. 

**2/ check if value is null, if so query the table and get all values into array** 

```
if (!level) {
         const speed = await Speed.findAll();
         level = speed.map(i => i.level);
      }
```

which makes extra querying. 

It would be nice to have this covered in `Op` attributes so we can simply skip the parameter if value passed to were statement is null.

` where: {level: {[Op.skipIfNull]: level}, ...}`

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by perfoWorks** [comment]
@sushantdhiman I did my best to follow your SSCCE for feature request... My question for this issue is already on SO [https://stackoverflow.com/questions/62162725/how-to-skip-query-in-column-where-statement-when-value-is-null](url) and also have been asked on Slack with same answer which makes me believe that there is no other way to do that so I requested this feature...

**Comment by sushantdhiman** [comment]
Sorry @perfoWorks I thought this was an issue, we need to change the feature request template.

Have you tried `omitNull` from sequelize options https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

**Comment by perfoWorks** [comment]
@sushantdhiman No .. I have missed that. It looks like this is what I was looking for however it doesn't seems to work. Can you please tell me how to use that? I tried to put it in my database initialisation file
```
const sequelize = new Sequelize('milljet', 'root', 'password', {
   dialect: 'mysql', host: 'localhost', logging: false, options: {omitNull: true}
})
```
that didn't work. (null are still accepted in queries). I have tried to put it in my findAll query

`Speed.findAll({where: { level: req.body.level }, options: {omitNull: true}});`

that didn't work as well. What am I doing wrong

**Comment by sushantdhiman** [comment]
Last argument to constructor is called `options`, so try this

```js
{ dialect: 'mysql', host: 'localhost', logging: false, omitNull: true }
```

**Comment by perfoWorks** [comment]
@sushantdhiman I tried that as well... Doesn't work

**Comment by sushantdhiman** [comment]
It only works for `create` / `update` queries. Not sure if this should work for where queries as it could lead to unexpected leakage of data.

If you are using lodash or similar perhaps try this https://stackoverflow.com/a/33432857

**Comment by perfoWorks** [comment]
@sushantdhiman Unfortunately it doesn't seems to work in where query.. I've never heard of loadash so I would have to look into it. Is there any chance to implement this feature into sequelize? I think this is pretty much common desirable feature for where query.. If we don't want to look from our front end in some column then we pass null value there.

**Comment by sushantdhiman** [comment]
`omitNull` for insert/update data is ok, but implementing that for where conditions can unexpectedly leak data. So I don't think we are going to change this behavior.

`lodash` is a utility library, should give you a good enough solution for case by case basis.

**Comment by perfoWorks** [comment]
@sushantdhiman ok then.. I will look into that library. Thank you very much for your help. Really appreciate that.
