### ISSUE TITLE
BigInt field return number or string?

### ISSUE THREAD

**Issue by zhangbuding** [sequelize/sequelize#12330]
Hello, my db model like this
```
     id: {
        type: DataTypes.BIGINT,
        allowNull: false,
        primaryKey: true,
        field: 'id',
      },
```
then, when i run select query,  sometimes this filed return string,  and sometimes return number.

for example, when id = `6628040699352457229`, the type is `string`,
and id = `6811331575891043000`, the type is `number`.

why like this？

**Comment by zhangbuding** [comment]
db: mysql 
version: 5.7.23

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
