### ISSUE TITLE
HasMany renturns only one item of the many part

### ISSUE THREAD

**Issue by linxingwu** [sequelize/sequelize#12335]
## Issue Description
HasMany returns only one item of the many part 

### What are you doing?

`product_brand_reco` is the middle table of the association between `product_top_class` and `company` but I don't need `product_top_class` any more , So I try to query `product_brand_reco` with `include` `company`. Are there anything wrong?

here is my model definition
```js
const {
  DataTypes
} = require('sequelize');

module.exports = sequelize => {
  const attributes = {
    rowId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: null,
      comment: "行码",
      primaryKey: true,
      field: "row_id",
      autoIncrement: false
    },
    topClassId: {
      type: DataTypes.STRING(50),
      allowNull: false,
      defaultValue: null,
      comment: "一级分类号",
      primaryKey: false,
      field: "top_class_id",
      autoIncrement: false
    },
    companyId: {
      type: DataTypes.STRING(50),
      allowNull: true,
      defaultValue: null,
      comment: "公司号",
      primaryKey: false,
      field: "company_id",
      autoIncrement: false
    }
  };
  const options = {
    tableName: "product_brand_reco",
    comment: "",
    indexes: []
  };
  const ProductBrandRecoModel = sequelize.define("productBrandRecoModel", attributes, options);
  return ProductBrandRecoModel;
};
```
```js
const {
  DataTypes
} = require('sequelize');

module.exports = sequelize => {
  const attributes = {
    rowId: {
      type: DataTypes.BIGINT,
      allowNull: true,
      defaultValue: null,
      comment: "行码",
      primaryKey: false,
      field: "row_id",
      autoIncrement: false
    },
    companyId: {
      type: DataTypes.STRING(50),
      allowNull: true,
      defaultValue: null,
      comment: "公司号",
      primaryKey: true,
      field: "company_id",
      autoIncrement: false
    },
    companyName: {
      type: DataTypes.STRING(60),
      allowNull: true,
      defaultValue: null,
      comment: "公司名称",
      primaryKey: false,
      field: "company_name",
      autoIncrement: false
    }
  };
  const options = {
    tableName: "company",
    comment: "",
    indexes: []
  };
  const CompanyModel = sequelize.define("companyModel", attributes, options);
  return CompanyModel;
};
```
my query code
```js
productBrandReco.hasMany(company,{foreignKey:"company_id",sourceKey:"companyId",as:"hotBrands"})

        topclass_ = await productBrandReco.findAll({
            attributes: ["topClassId"],
            include: [
                {
                    model: company,
                    attributes: ['companyId', 'companyName'],
                    as: "hotBrands"
                }
            ]
        });
```

### What do you expect to happen?

```json
[
    {
        "topClassId": "10001",
        "hotBrands": [
            {
                "companyId": "13",
                "companyName": "aaa投资有限公司"
            },
            {
                "companyId": "36",
                "companyName": "bbb信息科技有限公司"
            }
        ]
    }
]
```

### What is actually happening?

```json
[
    {
        "topClassId": "10001",
        "hotBrands": [
            {
                "companyId": "13",
                "companyName": "aaa投资有限公司"
            }
        ]
    },
    {
        "topClassId": "10001",
        "hotBrands": [
            {
                "companyId": "36",
                "companyName": "bbb信息科技有限公司"
            }
        ]
    }
]
```

### Additional context

It would work fine if I use ManyToMany assacition through  `product_top_class` and `company`

### Environment

- Sequelize version: "^5.3.5" 
- Node.js version: v12.16.1 
- Operating System: Window 10

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Are your using `raw: true`, looks like that

**Comment by linxingwu** [comment]
> Are your using `raw: true`, looks like that

Thanks for replying .
The code I wrote is what I run exactly. I didn't use `raw:true`.

**Comment by sushantdhiman** [comment]
`foreignKey:"company_id"` should this be `foreignKey:"companyId"`

**Comment by linxingwu** [comment]
no, it works well and generate right sql. or sequelize must throw some error.

**Comment by linxingwu** [comment]
> Are your using `raw: true`, looks like that

Actually I have found a situation： if the many part don't have primary key ,the result looks seem as mine. But my `company` do have primary key. So I have no idea what's wrong.

**Comment by sushantdhiman** [comment]
I think your model `ProductBrandRecoModel` has now two attributes `companyId` and `company_id`, both pointing to `company_id` column.

Use `foreignKey:"companyId"` and try again

**Comment by sushantdhiman** [comment]
If other model has not PK (but from your definition, looks like both model got `rowId/companyId` as PK) issue could be related to https://github.com/sequelize/sequelize/issues/5193, but I think this is related to `foreignKey:"company_id"`

**Comment by sushantdhiman** [comment]
In any case I can help you better if there is a https://github.com/papb/sequelize-sscce representation of issue.

**Comment by linxingwu** [comment]
I used 
```js
productBrandReco.hasMany(company,{foreignKey:"companyId",sourceKey:"companyId",as:"hotBrands"})
```
It doesn't change anything.

**Comment by linxingwu** [comment]
I have checked my database , they two only have one PK. I'll try https://github.com/papb/sequelize-sscce later tonight .

**Comment by linxingwu** [comment]
I have run locally by change your `package.json` to 
```js
    "start": "cross-env LOCAL_SSCCE=true DIALECT=postgres node setup/runner.js",
```
I got  the same result.

**Comment by sushantdhiman** [comment]
If you want help, I humbly request you to present your issue properly. Your SSCCE is not even creating any records and you are saying it is not working. I don't see how I can use that SSCCE to test this out, without having your local database instance available.

Please follow the issue template properly next time

-------------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
