### ISSUE TITLE
When I use UUID as the primary key and use bulkCreate+updateOnDuplicate to update records in batches, the primary key UUID will be recognized as a numeric type, resulting in an SQL execution error. This problem occurs only when autoIncrement: true.

### ISSUE THREAD

**Issue by habitshine** [sequelize/sequelize#12347]
When I use UUID as the primary key and use bulkCreate+updateOnDuplicate to update records in batches, the primary key UUID will be recognized as a numeric type, resulting in an SQL execution error. This problem occurs only when autoIncrement: true.

`const model = sequelize.define(name, {
        id: {
            type: UUIDV4,
            primaryKey: true,
            autoIncrement: true
        },
        productId: UUIDV4,`

`ctx.model.product_variants
                            .bulkCreate(
                                (() => {
                                    return input.variants.map(v => ({
                                        productId: id,
                                        ...v
                                    }))
                                })(),
                                {
                                    transaction,
                                    updateOnDuplicate: ['options', 'sku']
                                }
                            )`

`
INSERT INTO "app_public"."product_variants" ("id","product_id","options","sku","original_price","selling_price","weight","inventory","created_at","updated_at") VALUES (fb100d9e-05be-43d1-b391-e55e8394fa43,'adb04f9e-d35a-49d1-a6b3-ef879a62663d','["银","镀铂金"]','TYNL55A','70','29.95','6.1',12,'2020-06-06 03:54:30.899 +00:00','2020-06-06 03:54:30.899 +00:00'),(67ee460a-a095-4ef0-ac5b-8c78cfc51d9a,'adb04f9e-d35a-49d1-a6b3-ef879a62663d','["银","镀玫瑰金"]','TYNL55A','8','3.95','6.1',99,'2020-06-06 03:54:30.899 +00:00','2020-06-06 03:54:30.899 +00:00') ON CONFLICT ("id") DO UPDATE SET "options"=EXCLUDED."options","sku"=EXCLUDED."sku" RETURNING *;
`

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
