### ISSUE TITLE
invalid input syntax for type bigint: "[object Object]"

### ISSUE THREAD

**Issue by wollerman** [sequelize/sequelize#12342]
## Issue Description
We have a definition for a `createdAt` column as `BIGINT` in postgres. We've had the `defaultValue` in sequelize defined and working as:

```
createdAt: {
    type: DataTypes.INTEGER,
    defaultValue: Sequelize.literal('current_millis()'),
  }
```

This has been working consistently without issue until approximately June 1st, 11am PST.

Now when performing inserts we receive the error message:

```
 Unexpected error: invalid input syntax for type bigint: "[object Object]"
SequelizeDatabaseError: invalid input syntax for type bigint: "[object Object]"
```

### What are you doing?

Nothing has changed on our end, so I'm not sure how to provide reproduction to the issue..

### What do you expect to happen?

We expect the inserts to interpolate the `defaultValue` correctly and pass our literal `current_millis()` function to postgres.

### What is actually happening?

We see the error. 

### Additional context

Inspecting the values being passed it seems that the literal function is not being run and instead a javascript string representation of the `sequelize.literal` is being set. Inspecting the `createdAt` definition returns:
```
{
  type: [Function: INTEGER] {
    types: {
      postgres: [Array],
      mysql: [Array],
      mariadb: [Array],
      sqlite: [Array],
      mssql: [Array]
    },
    key: 'INTEGER'
  },
  defaultValue: Literal { val: 'current_millis()' }
}
```

Looking into the code base it seems that there are some places that explicitly call out when to run the value as a function, e.g. https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1206-L1214

I'm not sure that exact location is where our issue stems from, but hopefully it helps tracking down what is going wrong.

### Environment

- Sequelize version: 5.21.5 
- Node.js version: v13.8.0 
- Operating System: mac

### How does this problem relate to dialects?

- [ x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
I think somewhere in your code, you are now saving record with `createdAt: object`.

Otherwise `defaultValue: Literal { val: 'current_millis()' }` is correct. It is supposed to inject `current_millis()` for `createdAt`, only when no value for `createdAt` is provided by default.

Check recent changes in code, somewhere now you are saving/updating record with `createdAt: <object>`

**Comment by nmargaritis** [comment]
Why you have the variable BIGINT in postgres yet in your models is as 
```
type: DataTypes.INTEGER,
```
and not `DataTypes.BIGINT` ?
