### ISSUE TITLE
You attempted to save an instance with no primary key, this is not allowed since it would result in a global update

### ISSUE THREAD

**Issue by Lagsing** [sequelize/sequelize#12344]
buenas tarde lo que pasa es que estoy intentando hacer un actualizar y me sale este error
You attempted to save an instance with no primary key, this is not allowed since it would result in a global update

me pueden ayudar por favor gracias

export async function updatefinca(req, res) {
    try {
        const { id_finca } = req.params;
        const { nombre_finca, fecha_registro_finca } = req.body;

        const Fincas = await finca.findAll({
            attributes: ['id_finca', 'nombre_finca', 'fecha_registro_finca'],
            where: {

                id_finca

            },
        });
        if (Fincas.length > 0) {
            Fincas.forEach(async finca => {
                await finca.update({
                    nombre_finca,
                    fecha_registro_finca
                });
            })
        }
        return res.json({
            message: 'finca actualizada correctamente',
            data: Fincas
        })
    } catch (error) {
        console.log(error);
        console.log(id_finca);
        res.status(500).json({
            message: 'error de al actualizar',
            data: {}
        })

    }
'''''''''''''''''''''''''''''''''''''

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
