### ISSUE TITLE
Error when I'm use separate:true flag

### ISSUE THREAD

**Issue by MikeBazhenov** [sequelize/sequelize#12352]
### What are you doing?

I'm trying to get entities with HasMany relations, and it is works slow so I decided to add separate true flag in include options.

```typescript
include.push({
        model: PostTags,
        required: true,
        separate: true,
        attributes: [],
        where: {
          tag_id: filter.tag,
        },
      });

const result = await this.TABLE.findAndCountAll<Post>({
      where,
      offset: (page - 1) * limit,
      limit,
      order: [['created_at', 'DESC']],
      include: include.concat([Agency]),
    });
```

### What is actually happening?
Sequelize throws an exception

```TypeError: Cannot read property 'length' of undefined
at Function._groupJoinData (/opt/project/node_modules/sequelize/lib/dialects/abstract/query.js:668:33)
at Query.handleSelectQuery (/opt/project/node_modules/sequelize/lib/dialects/abstract/query.js:278:31)
at /opt/project/node_modules/sequelize/lib/dialects/postgres/query.js:196:23
```

### Environment

- Sequelize version: 5.21.12
- Node.js version: 12
- Operating System: alpine
- If TypeScript related: TypeScript version: 3.6.3

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
1. What is the error?
2. Also you missed the dialect section from template. What dialect is being used here?

Please don't be lazy, take time to properly file your issue request. Don't copy paste code and assume we can run it, provide a self contained code which I can execute or use https://github.com/papb/sequelize-sscce

-----------------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
