### ISSUE TITLE
MySQL raw query performance much worse than directly in Workbench

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#12357]
## Issue Description
Executing a raw query with sequelize DEBUG turned on in .env results in about 100-150ms for this query. When I execute the same query against the same db in MySQL workbench I see around 5ms.

This seems weird to me. Curious if this should be considered a bug.

The model

```
class SocialPost extends Sequelize.Model {
    static init(sequelize, DataTypes) {
        return super.init(
            {
                id: {
                    type: DataTypes.UUID,
                    defaultValue: DataTypes.UUIDV1,
                    primaryKey: true,
                    lowercase: true,
                },
                txt: {
                    type: DataTypes.TEXT,
                },
                publishedAt: {
                    type: DataTypes.DATE(),
                    defaultValue: DataTypes.NOW,
                },
            },
            {
                tableName: 'SocialPosts',
                scopes: {
                    comment: {
                        where: {
                            commentPostId: {
                                [Op.is]: null,
                            },
                        },
                    },
                    share: {
                        where: {
                            postId: {
                                [Op.isNot]: null,
                            },
                        },
                    },
                },
                indexes: [
                    {
                        fields: ['userId', 'commentPostId', 'publishedAt'],
                    },
                    {
                        fields: ['commentPostId', 'publishedAt'],
                    },
                ],
                sequelize,
            },
        );
    }


    static associate = models => {
        SocialPost.belongsTo(models.SocialUser, {
            foreignKey: 'userId',
            as: 'user',
            allowNull: true,
        });

        SocialPost.belongsTo(models.SocialPost, {
            foreignKey: 'commentPostId',
            as: 'commentPost',
            allowNull: true,
        });

        SocialPost.belongsTo(models.SocialPost, {
            foreignKey: 'postId',
            as: 'post',
            allowNull: true,
        });
    };
}

SocialPost.init(seq, DataTypes);
```
The query:
```
const posts = await sequelize.query(
    `
    SELECT *
    FROM SocialPosts p
    INNER JOIN 
        (SELECT 
            commentPostId, max(publishedAt) as publishedAt
            FROM
                SocialPosts
            GROUP BY commentPostId
        ) AS latest_posts
    ON latest_posts.commentPostId = p.commentPostId
    AND latest_posts.publishedAt = p.publishedAt
    WHERE
        p.commentPostId IN (${ids.map((_, idx) => `$${idx + 1}`)})
`,
    {
        bind: ids,
        raw: true,
        type: QueryTypes.SELECT,
    },
);
```

Same result if I don't use query binding.

### What are you doing?
Selecting the top comment for each post

### What do you expect to happen?

I would expect to see a similar query time as in workbench, since I'm executing a raw query

### What is actually happening?

```
INFO :   sequelize Executing (default): SELECT *
  sequelize 					FROM SocialPosts p
  sequelize 					INNER JOIN 
  sequelize 						(SELECT 
  sequelize 							commentPostId, max(publishedAt) as publishedAt
  sequelize 							FROM
  sequelize 								SocialPosts
  sequelize 							GROUP BY commentPostId
  sequelize 						) AS latest_posts
  sequelize 					ON latest_posts.commentPostId = p.commentPostId
  sequelize 					AND latest_posts.publishedAt = p.publishedAt
  sequelize 					WHERE
  sequelize 						p.commentPostId IN (?,?,?,?,?,?,?,?,?,?,?,?) +134ms
```

### Additional context
Same query in MySQL Workbench

<img width="1031" alt="Screen Shot 2020-06-09 at 11 47 53" src="https://user-images.githubusercontent.com/384959/84162774-221dce00-aa47-11ea-87d1-c56de3d152d0.png">

### Environment

- Sequelize version: 4.44.4
- Node.js version: 12.16.1
- Operating System: Mac OS / Docker

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x ] I don't know, I was using MySQL, with connector library mysql2 version 2.1.0 and database version 5.7

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Version `4.44.4` is not supported.

When a query executes in node, first we have to acquire connection and then we can start executing that query.

Have you tested this directly with `mysql2` client library. As sequelize use `typeCast` it is also affected by https://github.com/sidorares/node-mysql2/issues/889
