### ISSUE TITLE
N:M Association : "SequelizeEagerLoadingError: N is not associated to M!"

### ISSUE THREAD

**Issue by AhmedAyman0** [sequelize/sequelize#12355]
Hello,
I've been trying to solve this problem for multiple hours now and I've got no idea if it's a bug or I'm doing it wrong.

I've two models : user and organization and they've many-to-many relation 
here's the snippet

User Model:

```
'use strict';
const uuid = require('uuid');

module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    firstName: DataTypes.STRING,
    lastName: DataTypes.STRING,
    middleName: DataTypes.STRING,
    userName: DataTypes.STRING,
    email: DataTypes.STRING,
    status:DataTypes.STRING,
    mobile: DataTypes.STRING,
    extention: DataTypes.STRING,
    password: DataTypes.STRING,
    salt: DataTypes.STRING,
    isNew: DataTypes.BOOLEAN,
    title: DataTypes.STRING,
    status: DataTypes.STRING,
    isAdmin: DataTypes.BOOLEAN,
    phone:DataTypes.STRING,
    jobId:DataTypes.INTEGER,
    idNumber:DataTypes.STRING,
    idType:DataTypes.ENUM(['National ID', 'Passport']),
    dateOfBirth:DataTypes.DATE,
  }, {});
  User.beforeCreate(user => user.id = uuid.v4());

  User.associate = (models)=> {
    // associations can be defined here
    User.belongsToMany(models.Organization,{through:models.OrganizationEmployees,foreignKey:'employeeId',otherKey:'orgId',as:'orgs'});
  };
  return User;
};
```
Organization Model:

```
'use strict';
const uuid = require('uuid');

module.exports = (sequelize, DataTypes) => {
  const Organization = sequelize.define('Organization', {
    name: DataTypes.STRING,
    code: DataTypes.STRING,
    website: DataTypes.STRING,
    contact: DataTypes.STRING,
    idNum: DataTypes.STRING,
    idType: DataTypes.STRING,
    status: DataTypes.STRING,
    spokeId: DataTypes.UUID
  }, {});

  Organization.beforeCreate(org => org.id = uuid.v4());

  Organization.associate =  (models)=> {

    Organization.belongsToMany(models.User,{through:models.OrganizationEmployees,foreignKey:'orgId',otherKey:'employeeId',as:'users'});
  };
  return Organization;
};
```

And finally the junction model:
```
'use strict';

module.exports = (sequelize, DataTypes) => {
  const OrganizationEmployees = sequelize.define('OrganizationEmployees', {
    status: DataTypes.STRING,
    employeeId:DataTypes.UUID,
    orgId:DataTypes.UUID,
    roleId: DataTypes.NUMBER,
    isActive: DataTypes.BOOLEAN
  }, {timestamps:false});
  OrganizationEmployees.associate = function(models) {
    OrganizationEmployees.belongsTo(models.Organization,{foreignKey:'orgId'});
    OrganizationEmployees.belongsTo(models.User,{foreignKey:'employeeId'});
  };
  return OrganizationEmployees;
};
```

and since I'm using migration I've created the junction table with its fields referencing the other two tables.

**Comment by sushantdhiman** [comment]
You need to call `associate` method yourself, are you doing that somewhere? Usually setup includes a [`index.js`](https://github.com/sequelize/express-example/blob/master/models/index.js#L28) file which will call `associate` on all models defined

**Comment by sushantdhiman** [comment]
Closing this issue for ignoring issue template


------------------------------------


Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
