### ISSUE TITLE
setDataValue wont work to set a primary key, invoked from other field

### ISSUE THREAD

**Issue by ronyeh3** [sequelize/sequelize#12356]
## Issue Description

 using setter

### What do you expect to happen?

setDataValue wont work if setting field from another field, if the field is primary key

### Environment

- Sequelize version:  sequelize@5.21.10
- Node.js version: 12 
- Operating System: win
- If TypeScript related: TypeScript version: XXX

## Issue Template Checklist

    //surrogate primary key
    UserIDpk: {
      type: DataTypes.STRING,
      primaryKey: true,
    },

    UserID: {
      type : DataTypes.STRING,
      unique: true,  
      allowNull: true,
      set(val) {
        this.setDataValue('UserIDpk', val);  /// wont work to set primary keys
        this.setDataValue('UserID', val);
      }
    },

            user = await models.Users.create({UserID:"foo"});

### How does this problem relate to dialects?

- [x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
You didn't specified dialect, so I tried with `sqlite`. It works with `master`

```js
(async () => {
  const User = sequelize.define("user", {
    UserIDpk: {
      type: DataTypes.STRING,
      primaryKey: true,
    },

    UserID: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: true,
      set(val) {
        this.setDataValue("UserIDpk", val); /// wont work to set primary keys                                  
        this.setDataValue("UserID", val);
      },
    },
  });
                                 
  await sequelize.sync({ force: true });
                                 
  const result = await User.create({ UserID: "foo" });
                                 
  console.log(result);
})().catch((e) => console.error(e));
```

```sql
Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`UserIDpk` VARCHAR(255) PRIMARY KEY, `UserID` VARCHAR(255) UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_2`)
Executing (default): INSERT INTO `users` (`UserIDpk`,`UserID`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4);
user {
  dataValues:
   { UserIDpk: 'foo',
     UserID: 'foo',
     updatedAt: 2020-06-11T04:44:25.034Z,
     createdAt: 2020-06-11T04:44:25.034Z },
  _previousDataValues:
   { UserID: 'foo',
     UserIDpk: 'foo',
     createdAt: 2020-06-11T04:44:25.034Z,
     updatedAt: 2020-06-11T04:44:25.034Z },
  _changed: Set {},
  _options:
   { isNewRecord: true,
     _schema: null,
     _schemaDelimiter: '',
     attributes: undefined,
     include: undefined,
     raw: undefined,
     silent: undefined },
  isNewRecord: false,
  null: 1 }

```

**Comment by ronyeh3** [comment]
Hi , 
thanks for your response.
its not working with **_Mysql_**, 
sorry for not mention it.

have a nice day ahead!

**Comment by sushantdhiman** [comment]
I tried with MySQL, it works for both `master` and `v5`. Can you create a SSCCE https://github.com/papb/sequelize-sscce
