### ISSUE TITLE
Intermittent connection hanging with no errors using .authenticate()

### ISSUE THREAD

**Issue by nickr-davey** [sequelize/sequelize#12364]
## Intermittent connection hanging with no errors using .authenticate()

I am using v5 with lambda functions and RDS postgres 10.6, node 12

Using both v4 and v5 and pg 7+ and 8+ I get an issue where sometimes the connection is never established I think. It seems to just hang in the authenticate() function where it is not returning an error or resolving. 
I have gone through the other issues where people were running into this issue on v4 so I updated to v5 but I still see the same problem. When it happens once it wont get out of this state until and new instance of the function is created. It is really hard to debug when there are no errors happening and my function will just timeout.

It makes no difference using context.callbackWaitsForEmptyEventLoop = false; or increasing or decreasing the idle time.

### How I am setting up my connection
```javascript
  let sequelize: Sequelize = null;
export const db = () => {
  if (sequelize == null) {
    console.log("new db connection");
    return createInstanceDB();
  } else {
    console.log("old db connection");
    return sequelize
      .authenticate()
      .then(() => sequelize)
      .catch((err) => {
        console.log("SEQ_ERROR", err);
        return err
      });
  }
};

export const createInstanceDB = async () => {
  const { database, username, password, host } = JSON.parse(process.env.DB);

  // Open database connection
  sequelize = new Sequelize(database, username, password, {
    host: host,
    dialect: "postgres",
    pool: { max: 1, min: 0, idle: 2000},
    logging: process.env.DB_DEBUG === "true" ? console.log : false,
  });

  // Initialize each model in the database
 
// setting up associations here

  
  try {
    await sequelize.authenticate();
    console.log("Connection has been established successfully.");
    return sequelize;
  } catch (error) {
    console.error("Unable to connect to the database:", error);
    throw error;
  }
};
```

### Environment
Node 12.x
PG 8.21.x
Sequelize 5.21.10
AWS Lambda
AWS RDS postgres

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [X] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
By default `acquire` time is set to `60 seconds` https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

`authenticate` or any method using connection will wait for that much time before throwing an related `ConnectionAcquireTimeoutError`.

As you are using lambda, I suspect you are exhausting total connection pool from RDS. Your lambdas are waiting to acquire new connection but timeout before connection is acquired, due to lambda execution timeout set lower than `60 seconds` (i.e. `poo.acquire`) 

Also why `idle` is set to  `2000`?

**Comment by nickr-davey** [comment]
@sushantdhiman thanks for the reply
I will try reduce the time out on acquire and see what happens, I have a 30sec timeout on the functions, so it spending that long on a connection is a bit intense.

I am not running out of connections though. I have well over 100 available and am maxing out at 5 at the moment. 

I set idle to 2000 so they don't sit around for a while. It is just what I have read to do going through the other issues here.

**Comment by sushantdhiman** [comment]
>  have well over 100 available and am maxing out at 5 at the moment.

How are you verifying this?

**Comment by nickr-davey** [comment]
rds connection mon

> How are you verifying this?

RDS Connection monitor

**Comment by nickr-davey** [comment]
@sushantdhiman why closed? I still see the issue

**Comment by sushantdhiman** [comment]
I don't think this bug is related to Sequelize, more likely related to `pg` or environment setup. We can continue to discuss this issue though.

Please set env variable to `DEBUG=sequelize*` for better logs. Share those logs here

**Comment by sushantdhiman** [comment]
You can also try connecting with `pg` directly and try executing queries. See if that works

**Comment by nickr-davey** [comment]
Thanks, will do.

I have just created a seperate method to check if pg can connect when sequelize. The issue is very random, so it has been very hard to debug. I will report back when I get some logs when it happens again.

**Comment by nickr-davey** [comment]
Finally got some information from those debug logs. It doesn't really give me much though. There is no timeout error or anything like I would have imagined there to be.

```
  | 2020-06-17T14:17:04.357+10:00 | 2020-06-17T04:17:04.357Z sequelize:pool pool created with max/min: 2/0, no replication
-- | -- | --
  | 2020-06-17T14:17:07.443+10:00 | 2020-06-17T04:17:07.443Z sequelize:pool connection drain due to process exit
```

Those are the only two messages I get from sequelize when the issue happens. 

the same function working when successful looks like this

```

2020-06-17T04:11:23.399Z sequelize:pool pool created with max/min: 2/0, no replication
--

  | 2020-06-17T14:11:23.647+10:00 | 2020-06-17T04:11:23.647Z sequelize:connection:pg connection acquired
  | 2020-06-17T14:11:23.695+10:00 | 2020-06-17T04:11:23.695Z sequelize:connection:pg connection acquired
  | 2020-06-17T14:11:23.699+10:00 | 2020-06-17T04:11:23.699Z sequelize:pool connection acquired
  | 2020-06-17T14:11:23.700+10:00 | 2020-06-17T04:11:23.700Z sequelize:sql:pg Executing (default): SELECT 1+1 AS result
  | 2020-06-17T14:11:23.700+10:00 | 2020-06-17T04:11:23.700Z be2dcf1a-a5d1-41bd-af98-c9b6174831d0 INFO Executing (default): SELECT 1+1 AS result
  | 2020-06-17T14:11:23.702+10:00 | 2020-06-17T04:11:23.702Z sequelize:sql:pg Executed (default): SELECT 1+1 AS result
  | 2020-06-17T14:11:23.703+10:00 | 2020-06-17T04:11:23.703Z sequelize:pool connection released

```

**Comment by nickr-davey** [comment]
Looks like an issue with using AWS Lambda, and node versions greater than 8, along with pg. Unfortunately aws does not support node 8.10 anymore, which is when this issue started happening.

So the issue is really with pg by the looks of it - https://github.com/brianc/node-postgres/issues/2112

**Comment by sushantdhiman** [comment]
Pool does not swallow any errors, https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L86

I suspect neither `connect` nor `end` callbacks are being fired. Are you using `optiion.clientMinMessages`?

**Comment by tersers** [comment]
I am experiencing the same issue on v5.21.13, it appears a connection to the database is never established. I threw a breakpoint and a print statement in `dialects/postgres/connection-manager.js` around line 166 but it does not appear execution reaches that point.

I tried using `pg` directly and I was able to successfully establish a connection and query the database.

**Comment by tersers** [comment]
I just fixed it by setting the pg version to 8 and above.

**Comment by nickr-davey** [comment]
I have tried above 8 and still do see it. Currently testing 8.0.3 of PG.

@sushantdhiman Not using ```option.clientMinMessages``` should I be?

I saw on the database logs that the connection was interrupted by the client. So it does try, but does not send or try to do anything from there. 

@tersers I was able to connect and execute a qurey using PG directly when this issue arrises. 

For now since this only happens once every 100-200 api calls, I created a manual timeout that will return an error, and end the process. This way the lambda function only fails once, rather than locking it up. Not ideal, but when I get time I will try switch to the mysql db and test to see if the issue is still there, if not I will make the switch on the production side.

**Comment by tersers** [comment]
@nickr-davey Perhaps the node version has something to do with it? My coworker says his setup with the older versions worked on node10, but I had no luck with my local node14 until I upgraded pg and sequelize.

**Comment by sushantdhiman** [comment]
> Not using option.clientMinMessages should I be?

No, just leave it to default.

I would like to fix this issue, at sequelize level, if it is due to how we are using `pg`. Need some reproduction. Meanwhile I have pinned https://github.com/sequelize/sequelize/issues/12158, so users are aware that recent changes in `pg` might give them issues.

**Comment by nickr-davey** [comment]
Just an update, I have left majority of the code alone and changed to mysql using mysql2 v2.1.0 and am still seeing the same issue. However I do get the ETIMEDOUT error back with mysql.

I am only seeing this when a new lambda functions spins up, but if it does happen, which is about every 50-100 FRESH initialisations over 6 hours or so (only hitting 5 con current connections) . That instance of the lambda function will never make a connection. 

The only way I have been able to replicate it for testing is by constantly updating the function to make sure they are new instances.

**Comment by nickr-davey** [comment]
@tersers I think it is the node version. I have been working on this project for 6 months or so, and I was on node v8 and didn't see this issue. However, I may have never noticed it if the issue did pop up.

**Comment by marcogrcr** [comment]
Keep in mind that AWS has released a product for AWS Lambda called [Amazon RDS Proxy](https://aws.amazon.com/rds/proxy/) where you don't have to worry about connection pooling and you can create a new connection for every request.

Additionally, if you use `new Sequelize({ pool: { max: 1 }, /* (...) */ })` (common config for AWS Lambda functions based on the fact that Lambda containers only process one request at a time) and use `Model.findAndCountAll()`, you may experience `SequelizeConnectionAcquireTimeoutError` errors for expensive (latency-wise) queries. See #12633 for more details.

**Comment by marcogrcr** [comment]
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.

**Comment by henhal** [comment]
I'm having a very similar issue to this, and I've followed the guide at https://sequelize.org/docs/v6/other-topics/aws-lambda/.

* I have an RDS proxy set up
* From my lambda function, if I call `client.connect()` using `pg` directly, I get an instant success.
* From my lambda function, if I call `authenticate()` on my `sequelize` instance, it hangs.

I added `DEBUG: sequelize*` and all it says during the function invocation when using `Sequelize` is:

```
sequelize:pool pool created with max/min: 2/0, no replication
sequelize:connection:pg connection acquired
```

The Lambda function then times out (15 seconds).

My dependencies:

    "pg": "^8.7.3",
    "pg-native": "^3.0.0",
    "sequelize": "^6.18.0"

Any ideas?

**Comment by henhal** [comment]
Hmm: After further investigation, everything works with a direct RDS instance, but fails with a RDS proxy...

With RDS proxy endpoint, `client.connect()` call succeeds using `pg`, but executing a query or calling `sequelize.authenticate()` fails.
With RDS instance endpoint, connect and query and sequelize all works.

**Comment by CooperEdmunds** [comment]
Using an RDS Proxy. I'm able to successfully connect _and query_ using pg directly, but `sequelize.authentiate()` hangs

**Comment by LBeckX** [comment]
> Using an RDS Proxy. I'm able to successfully connect and query using pg directly, but sequelize.authentiate() hangs

Same here.
