### ISSUE TITLE
camelCase'd Foreign keys in an update's where clause are not converted to underscore

### ISSUE THREAD

**Issue by slifty** [sequelize/sequelize#12366]
### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/slifty/sequelize_sscce/blob/master/index.js

1. I am using `underscored` and postgres.
2. I have defined a model association (`hasMany` + `belongsTo`).
3. When updating, I am not able reference the foreign key in a `where` clause using camelCase.

```
// Executing (default): UPDATE "items" SET "test"=$1,"updated_at"=$2 WHERE "created_at" = $3
models.Item.update(
  { test: 'this_works' },
  {
    where: {
      createdAt: 0,
    },
  },
)

// Executing (default): UPDATE "items" SET "test"=$1,"updated_at"=$2 WHERE "category_id" = $3
models.Item.update(
  { test: 'this_works' },
  {
    where: {
      category_id: 0,
    },
  },
)

// Executing (default): UPDATE "items" SET "test"=$1,"updated_at"=$2 WHERE "categoryId" = $3
// Unhandled rejection SequelizeDatabaseError: column "categoryId" does not exist
models.Item.update(
  { test: 'this_errors' },
  {
    where: {
      categoryId: 0,
    },
  },
)
```

### What do you expect to happen?

I want generated queries to properly convert `categoryId` to `category_id`, as it does for other columns.

_I want the generated query to be `UPDATE "items" SET "test"=$1,"updated_at"=$2 WHERE "category_id" = $3`_

### What is actually happening?

_The generated query reflects `categoryId` as `categoryId`, without converting to snake_case_

```
Executing (default): UPDATE "items" SET "test"=$1,"updated_at"=$2 WHERE "categoryId" = $3
Unhandled rejection SequelizeDatabaseError: column "categoryId" does not exist
```

### Additional context

None.

### Environment

- Sequelize version: 5.21.12
- Node.js version: 13.1.0
- Operating System: OSX
- If TypeScript related: TypeScript version: N/Aaaaa

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using `Postgres`, with connector library version `8.2.1` and database version `12.2`

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start. :: NOTE: I would love to try if my time situation changes.

**Comment by sushantdhiman** [comment]
I tried this equivalent version, which worked for me with `master` and latest `v5`

```js
const Sequelize = require("./index");
const DataTypes = Sequelize.DataTypes;
const sequelize = require("./test/support").createSequelizeInstance({
  define: {
    underscored: true,
  },
});

(async () => {
  const User = sequelize.define("user", {
    name: DataTypes.STRING,
  });

  const Category = sequelize.define("category", {
    name: DataTypes.STRING,
  });

  User.hasMany(Category);
  Category.belongsTo(User);

  await sequelize.sync({ force: true });

  await Category.update(
    {
      name: "abc",
    },
    {
      where: {
        userId: 12,
      },
    }
  );
})().catch((e) => console.error(e));
```

**Comment by slifty** [comment]
First - thank you for showing me how to actually write a SSCCE!  I apologize that my first attempt was so convoluted.

Second - I'm able to replicate now using that format:

```
const Sequelize = require("./index");
const DataTypes = Sequelize.DataTypes;
const sequelize = require("./test/support").createSequelizeInstance({
  define: {
    underscored: true,
  },
});

(async () => {
  const User = sequelize.define("User", {
    name: DataTypes.STRING,
  });

  const Category = sequelize.define("Category", {
    name: DataTypes.STRING,
  });

  User.hasMany(Category);
  Category.belongsTo(User);

  await sequelize.sync({ force: true });

  await Category.update(
    {
      name: "abc",
    },
    {
      where: {
        userId: 12,
      },
    }
  );
})().catch((e) => console.error(e));
```

Specifically, by changing `user` to `User` and `category` to `Category` in the model definition the issue manifests.

**Comment by sushantdhiman** [comment]
Attribute name are constructed from model name, so foreign key attribute's actual name here will be `UserId`. With code below

```js
await Category.update(
    {
      name: "abc",
    },
    {
      where: {
        userId: 12,
      },
    }
  );
```
Sequelize try to find `userId` attribute, but there isn't any (there is `UserId` attribute). So we pass this attribute directly to SQL query, thinking that it could be some column that is not defined in model. Which throws an error for unknown column.

With upper-cased model name, like this
```js
const User = sequelize.define("User", { // <-- NOTE THE CASE CHANGE "U" vs "u"
  name: DataTypes.STRING,
});
```
You have to query with `UserId`, like this

```js
await Category.update(
    {
      name: "abc",
    },
    {
      where: {
        UserId: 12,
      },
    }
  );
```

Alternatively we allow you to set `foreignKey` option when defining association, which can be used to override auto-generated foreign key attribute name. https://sequelize.org/master/manual/assocs.html#options-2

**Comment by slifty** [comment]
Thank you for that explanation and the flag about the `foreignKey` option, and apologies this ultimately turned into a StackOverflow question (I'll actually re-post it as a question there just so the answer appears there too).

Before I close this out, wanted to mention that this behavior does seem unintuitive to me. It strikes me that neither column names nor object attributes are ever upper case as a best practice, whereas model names are always upper case as best practice.

Has there been consideration of making the default association column names default to camelCase instead of Upper (basically, reversing the default behavior, and having folks use foreignKey if they *don't* want lower case column names / object attributes)?

**Comment by sushantdhiman** [comment]
> It strikes me that:
> - column names and object attributes are generally never upper case as a best practice
> - whereas model names are always upper case as best practice.

I agree, I think this idea has been coined in some discussions in the past.

This is old behavior and I feel it has less magic. We are using model name directly, so it up to developer to name their model. Although it seems to go against usual favored behavior, but once you understand it, it makes sense.

I will close this issue now. If you want to invite more discussions on the topic of generating pure camelCase names, please open a new issue.

**Comment by slifty** [comment]
Much appreciated, and thank you for the project and talking through this one!

**Comment by augusto-dmh** [comment]
I noticed something else that can be interesting to add up to this discussion:

I've got a junction table model which foreign keys are defined on camelCase (in the dbConfig i used `underscore: true`), but the model name is defined on PascalCase:

```
export default class CourseModality extends Model {
  static init(sequelize) {
    super.init(
      {
        courseId: {
          type: DataTypes.INTEGER,
          allowNull: false,
        },
        modalityId: {
          type: DataTypes.INTEGER,
          allowNull: false,
        },
      },
      { sequelize, timestamps: false },
    );

    return this;
  }
}
```
When i tried to retrieve the results of a query on the model using where clause with the foreign keys as "courseId" and "modalityId" (camelCase) i got the *SqlError* `"Column 'course_id' cannot be null"`. And when i tried as "course_id" and "modality_id" (snake_case), i got the *SequelizeValidationError* error `CourseModality.courseId cannot be null`. And what is quite strange is that, when i tried using the foreign keys as "CourseId" and "ModalityId" (PascalCase), i received another *SequelizeValidationError*: `CourseModality.courseId cannot be null`.

It seems that Sequelize is considering "courseId" and "modalityId" from the model as fields different and totally independent from "course_id" and "modality_id" on database (i'm using MYSQL). On querying all courses on db including all modalities associated with them, that's the result on JSON:

```
{
    "id": 2,
    "name": "Design",
    "category": "Arquitetura e Urbanismo & Design",
    "durationSem": 6,
    "degree": "Bachelor",
    "createdAt": "2023-10-24T21:27:30.000Z",
    "updatedAt": "2023-10-24T21:27:30.000Z",
    "modalities": [
        {
            "name": "On-campus",
            "CourseModality": {
                "courseId": 2,
                "modalityId": 1,
                "CourseId": 2,
                "ModalityId": 1
            }
        }
    ]
},
```
(i'm using the LTS version of sequelize).

The way solved the problem was changing all my models' names to lowercase (all were in UpperCase) and mentioning the foreign keys as camelCase, but i don't know for sure how sequelize works on namings and aliases related to foreign keys...

The query result after the changes:
```
{
    "id": 2,
    "name": "Design",
    "category": "Arquitetura e Urbanismo & Design",
    "durationSem": 6,
    "degree": "Bachelor",
    "createdAt": "2023-10-24T21:27:30.000Z",
    "updatedAt": "2023-10-24T21:27:30.000Z",
    "modalities": [
        {
            "name": "On-campus",
            "CourseModality": {
                "courseId": 2,
                "modalityId": 1
            }
        }
    ]
},
```
