### ISSUE TITLE
about Models cannot be packaged question

### ISSUE THREAD

**Issue by yongruning** [sequelize/sequelize#12365]
## Issue Description
After my application is packaged, the prompt Models is not found
### What are you doing?
I want to solve this problem

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?
Models are packaged correctly into applications

### What is actually happening?
Uncaught Error: Cannot find module 'D:\webstrom_workspace\khala_rpa\build\win-unpacked\resources\app.asar\dist\models/rpa_user.js'
    at Module._resolveFilename (module.js:543)
    at Function.Module._resolveFilename (D:\webstrom_workspace\khala_rpa\build\win-unpacked\resources\electron.asar\common\reset-search-paths.js:35)
    at Function.Module._load (module.js:473)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at Sequelize.import (D:\webstrom_workspace\khala_rpa\build\win-unpacked\resources\app.asar\node_modules\sequelize\lib\sequelize.js:481)
    at Module.<anonymous> (renderer.js:7)
    at b (renderer.js:1)
    at renderer.js:1
    at renderer.js:1

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: ^5.21.7 
- Node.js version: v12.16.1 
- Operating System: windows10
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by yongruning** [comment]
I did some research,Is it because of dynamic import of sequelize.import,lead to models cannot be packaged into applications,If so, what should be the solution

**Comment by sushantdhiman** [comment]
`sequelize.import` has been deprecated, you can directly require models. See sequelize/cli v6 for new format

**Comment by yongruning** [comment]
@sushantdhiman 
I've seen the V6 documentation, and it doesn't seem to cover how to use a defined model

**Comment by sushantdhiman** [comment]
You just require it

**Comment by yongruning** [comment]
@sushantdhiman Do I need to upgrade Sequelize to v6 beta

**Comment by sushantdhiman** [comment]
No, this was always possible even with v3. See how v6 of [`sequelize/cli`](https://github.com/sequelize/cli/blob/master/src/assets/models/index.js#L24) is using `require` instead of `sequelize.import`

**Comment by yongruning** [comment]
@sushantdhiman Using sequelize. models.User results in undefind

**Comment by yongruning** [comment]
@sushantdhiman I didn't see the use of 'require', could you be more specific

**Comment by yongruning** [comment]
The Sequelize V6 documentation describes creating a model using sequelize.define and then importing the model directly using Require, hopefully to help anyone with similar issues
@sushantdhiman thank you for your help
