### ISSUE TITLE
Model.findOne doesn't automatically add limit 1?

### ISSUE THREAD

**Issue by theoephraim** [sequelize/sequelize#12379]
## Issue Description
It seems that calling findOne (and findByPk) doesn't automatically add limit 1 to the query?

Can someone confirm this is the expected behaviour and not something I introduced with hooks and my code?

### What do you expect to happen?
I expected `LIMIT 1` to be added automatically to the query.

In my case this means thousands of rows are being returned by the db when I really just need 1. In the code it didn't make a difference as only the first is being returned by findOne but this has horrible implications for db performance and is not what I expected to happen at all.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
