### ISSUE TITLE
5.21.13 overly strict setDataValue()

### ISSUE THREAD

**Issue by koblas** [sequelize/sequelize#12372]
## Issue Description 

specified 'this' for getters and setters in fields - is incorrect

This was introduced by the only PR on 5.12.13 

### What are you doing?

The following code is no longer valid:

    export class TaxFormInstance extends Model implements Writeable<TaxFormEntity> {
        withholdingPercentage!: Amount;
    }

    TaxFormInstance.init(
        set: function set(val: Amount) {
          if (val !== undefined) {
            //
            // ERROR: Argument of type 'string' is not assignable to parameter of type 'Amount'.
            // 
            this.setDataValue("withholdingPercentage", val.toFixed(1));
          }
        },
    }

### What do you expect to happen?

Having getters and setters apply typing to setDataValue() makes it impossible to store higher-order types in the database.  

### What is actually happening?

Typing is being applied to something that needs to convert to an underlying type, not the type of input.

- Sequelize version: 5.21.13
- Node.js version: 12
- Operating System: MacOS
- If TypeScript related: TypeScript version: 3.9.2

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by koblas** [comment]
Should have added this:

https://github.com/sequelize/sequelize/pull/12370/files

The underlying bug is:

      public setDataValue<K extends keyof this>(key: K, value: this[K]): void;

Where `value: this[K]` assumes that type is the same as the datatype, which is incorrect.

**Comment by a88zach** [comment]
Same issue with getDataValue in 5.12.13

**Comment by ephys** [comment]
Closing in favor of https://github.com/sequelize/sequelize/issues/11558
