### ISSUE TITLE
UpdatedAt field cannot be updated manually

### ISSUE THREAD

**Issue by hverlin** [sequelize/sequelize#12386]
### What are you doing?

https://github.com/papb/sequelize-sscce/pull/84

```js
const sequelize = createSequelizeInstance({
  logQueryParameters: true,
  benchmark: true,
});

const Foo = sequelize.define('Foo', {name: DataTypes.TEXT});

await sequelize.sync();

const foo = await Foo.create({name: 'foo'});

assert.equal(foo.createdAt, foo.updatedAt);

await foo.update({name: 'foo2'})
assert.isAbove(foo.updatedAt, foo.createdAt);

const previousUpdatedAt = foo.updatedAt;
const newUpdatedAt = new Date()
foo.update({updatedAt: newUpdatedAt})

// this fails as the "updatedAt" field was not updated
assert.isAbove(foo.updatedAt, previousUpdatedAt);
```

### What do you expect to happen?

I would like to be able to update the `updatedAt` manually.

### What is actually happening?

The `updatedAt` field cannot be updated manually for sequelize >= 5. This is a breaking change and I did not find any options to revert that behavior.

### Additional context

- Why do we need this?
We are sometimes updating the `updatedAt` field of a parent object when a child object has been updated. 

### Environment

- Sequelize version: latest 5 and 6 version
- Node.js version: 12

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

I can help fixing this if it does not involve large changes.

- [x] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by papb** [comment]
Hello, thank you very much for the detailed and well-written report including the SSCCE! That is very helpful.

Can you please take a look at issues #3759 and #10419 and let me know how (if) your issue relates to them? And if any of the comments in #3759 helps you?

**Comment by hverlin** [comment]
Thanks @papb 

The workaround mentioned in #3759 works (i.e. using `instance.changed('updateAt', true)`.
You cannot set the exact date that you want, but at least it will update the value.

Here is the updated example:
```js
const sequelize = createSequelizeInstance({
  logQueryParameters: true,
  benchmark: true,
});

const Foo = sequelize.define('Foo', {name: DataTypes.TEXT});

await sequelize.sync();

const foo = await Foo.create({name: 'foo'});

assert.equal(foo.createdAt, foo.updatedAt);

await foo.update({name: 'foo2'})
assert.isAbove(foo.updatedAt, foo.createdAt);

const previousUpdatedAt = foo.updatedAt;
const newUpdatedAt = new Date();
foo.changed('updatedAt', true)

foo.update({updatedAt: newUpdatedAt})

// this now works
assert.isAbove(foo.updatedAt, previousUpdatedAt);

// however this fails
 assert.equal(foo.updatedAt, newUpdatedAt);
```

The workaround should be good enough, thanks!
Would it be ok to document the workaround in the description of the `update` method?

**Comment by hverlin** [comment]
This also makes it harder to update several instances at once.
This does not work e.g.

```js
const newUpdatedAt = new Date();
await Foo.update({ updatedAt: newUpdatedAt }, { where: { id: { [Op.gte]: 1 } }})
```

**Comment by hverlin** [comment]
this is still relevant

**Comment by jzyds** [comment]
use sequelize.query

`
await sequelize.query( `UPDATE TableName SET updatedAt = '${new Date().toISOString()}' WHERE id = ${id}`);
`

**Comment by ephys** [comment]
Considering this is the same issue as https://github.com/sequelize/sequelize/issues/3759, and that other issue is more complete, I'll close this issue in favor of that one
