### ISSUE TITLE
postgreSQL - A.belongsToMany(B, {through: X}) : error when inserting

### ISSUE THREAD

**Issue by Kitcat711** [sequelize/sequelize#12388]
## Issue Description
Having two tables: orders and products. 
I define that  `Order.belongsToMany(Product, {through: OrderItem});`
But `order.addProducts([product1, product2]);` or `order.addProduct(product);` always return 
an **invalid value** about product

### What are you doing?
(sorry for not using sscce, I did not manage to make it run :(
**_order Model_**
```
const { nanoid } = require('nanoid');
const { customAlphabet} = require('nanoid');

const Sequelize = require('sequelize');
const sequelize = require('../util/database');

const order = sequelize.define('order', {
    uuid : {
      type: Sequelize.STRING(10),
      autoIncrement: false,
      allowNull: false,
      primaryKey: true,
      defaultValue: () => nanoid(10)
    },
    reference : {
      type: Sequelize.STRING(14),
      autoIncrement: false,
      allowNull: false,
    },
    status: Sequelize.STRING(14)
  },
  {schema: 'public'});


module.exports = order;
```
**_product Model_**
```
const Sequelize = require('sequelize');
const sequelize = require('../util/database');

const product = sequelize.define('product', {
  sku : {
    type: Sequelize.STRING(12),
    autoIncrement: false,
    allowNull: false,
    primaryKey: true,
    unique: true
  },
  title: Sequelize.STRING(64),
});

module.exports = product;
```
**_orderItem Model_**
```
const { nanoid } = require('nanoid');
const Sequelize = require('sequelize');

const sequelize = require('../util/database');

const OrderItem = sequelize.define('orderItem', {
  uuid : {
    type: Sequelize.STRING(10),
    autoIncrement: false,
    allowNull: false,
    primaryKey: true,
    defaultValue: () => nanoid(10)
  },
  quantity: Sequelize.INTEGER
});

module.exports = OrderItem;
```

**_call of order.addProducts in a method_**

```
order.create({
        status: 'new'
      })
.then((order) => {
  const skus = orderFormData.orderItems.map(item => {
    return item.sku
  });
  return product.findAll({
    where: {
      sku: {
        [Op.in]: skus
      }
    }
  })
  .then(products => {
      return order.addProducts(
        products.map(product => {
          product.orderItem = { quantity: 1 };
          return product;
        })
      )
    })

})
```
### What do you expect to happen?

I wanted a row in table orderItems, with orderUuid, productSku and quantity.

### What is actually happening?
_got an error: "invalid value" dans no row insterted_

```
Unhandled rejection Error: Invalid value product {
```
Please see the attached file for the whole error.log
[sequelize.belongToMany.error.log](https://github.com/sequelize/sequelize/files/4799682/sequelize.belongToMany.error.log)

### Additional context
This is how I found a temporary solution:
```
.then(products => {
            // todo: lorsque addProducts fonctionnera..
            //   return order.addProducts(
            //     products.map(product => {
            //       product.orderItem = { quantity: 1 };
            //       return product;
            //     })
            //   )
            // })
            return products.forEach((product) => {
              orderItem.create({
                quantity: 1,
                orderUuid: order.uuid,
                productSku: product.sku
              })
            })
          })
```
### Environment

- Sequelize version: 5.21.13
- Node.js version: 12.16.3
- Operating System: Mac Os X 10.15.5
- postgreSQL: PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
`dialect: 'postgres',`
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please submit a proper SSCCE which reproduce this issue. See https://github.com/papb/sequelize-sscce or https://github.com/sequelize/sequelize/labels/Great%20SSCCE
