### ISSUE TITLE
Unable to Upsert/bulkCreate with tables having trigger on msssql with hasTrigger: true

### ISSUE THREAD

**Issue by kid101** [sequelize/sequelize#12384]
below is the Seqluize quey created at the time of upsert:
`SET IDENTITY_INSERT [InfoTable] ON;
MERGE INTO [InfoTable] WITH(HOLDLOCK) AS [InfoTable_target] USING (VALUES(N'Comp', N'delh2', N'London', N'UK', N'level 2', N'www.company.com', N'12312asda', N'12312asdass', N'12312asda', N'incomplete', N'some Value', N'Mr Name', 1728930455, N'Name@gmail.com', N'VP', 1, N'1', NULL, '2020-06-18 04:55:45.517')) AS [InfoTable_source]([PersonName], [City], [State], [Country], [Level], [Website], [CCode], [NameCode], [SubCode], [Status], [Valueumber], [ContactPerson], [CellNumber], [Email], [Designation], [CompId], [InfoTableId], [CreatedAt], [UpdatedAt]) ON [InfoTable_target].[InfoTableId] = [InfoTable_source].[InfoTableId] WHEN MATCHED THEN UPDATE SET [InfoTable_target].[PersonName] = N'Comp', [InfoTable_target].[City] = N'delh2', [InfoTable_target].[State] = N'London', [InfoTable_target].[Country] = N'UK', [InfoTable_target].[Level] = N'level 2', [InfoTable_target].[Website] = N'www.company.com', [InfoTable_target].[CCode] = N'12312asda', [InfoTable_target].[NameCode] = N'12312asdass', [InfoTable_target].[SubCode] = N'12312asda', [InfoTable_target].[Status] = N'incomplete', [InfoTable_target].[Valueumber] = N'some Value', [InfoTable_target].[ContactPerson] = N'Mr Name', [InfoTable_target].[CellNumber] = 1728930455, [InfoTable_target].[Email] = N'Name@gmail.com', [InfoTable_target].[Designation] = N'VP', [InfoTable_target].[CompId] = 1, [InfoTable_target].[UpdatedAt] = '2020-06-18 04:55:45.517' WHEN NOT MATCHED THEN INSERT ([PersonName], [City], [State], [Country], [Level], [Website], [CCode], [NameCode], [SubCode], [Status], [Valueumber], [ContactPerson], [CellNumber], [Email], [Designation], [CompId], [InfoTableId], [CreatedAt], [UpdatedAt]) VALUES(N'Comp', N'delh2', N'London', N'UK', N'level 2', N'www.company.com', N'12312asda', N'12312asdass', N'12312asda', N'incomplete', N'some Value', N'Mr Name', 1728930455, N'Name@gmail.com', N'VP', 1, N'1', NULL, '2020-06-18 04:55:45.517') OUTPUT $action, INSERTED.*; SET IDENTITY_INSERT [InfoTable] OFF;`

Below error: 
`The target table 'dbo.InfoTable_target' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.`

model hasTrigger: true
if instead of upsert operation, I use update operation on the model, it will work.

Also for bulkCreate operations, hasTrigger: true is simply not recognized. 

Sequelize and Tedious version: 
"sequelize": "5.21.12",
"tedious": "8.3.0",

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by kid101** [comment]
reopen now?

**Comment by sushantdhiman** [comment]
@kid101 Please provide me some code which I can execute. Look at [these issues](https://github.com/sequelize/sequelize/issues?q=is%3Aissue+label%3A%22Great+SSCCE%22+is%3Aclosed) to check how to present your issue as a good SSCCE.

**Comment by iantrudell** [comment]
I am also having the same issue. Here is some code to illustrate the problem:

Model (Take note of the hasTrigger: true)
```
import {
    DataTypes,
    Model,
    Sequelize,
    InferCreationAttributes,
    InferAttributes,
    CreationOptional,
} from 'sequelize'
import { HookDestroyOptions } from 'types/models'

export class Product_Process extends Model<
    InferAttributes<Product_Process>,
    InferCreationAttributes<Product_Process>
> {
    declare id: CreationOptional<number>
    declare product_id: number
    declare process_id: number

    static associate({ Product, Process }) {
        Product_Process.belongsTo(Process)
        Product_Process.belongsTo(Product)
    }
}

export const product_processFactory = (sequelize: Sequelize) =>
    Product_Process.init(
        {
            id: {
                type: DataTypes.INTEGER,
                allowNull: false,
                autoIncrement: true,
                primaryKey: true,
            },
            product_id: {
                type: DataTypes.INTEGER,
            },
            process_id: {
                type: DataTypes.INTEGER,
            },
        },
        {
            sequelize,
            tableName: 'products_processes_links',
            underscored: true,
            schema: 'bio',
            paranoid: true,
            hasTrigger: true,
            createdAt: 'created_at',
            updatedAt: 'updated_at',
            deletedAt: 'deleted_at',
            hooks: {
                afterDestroy: async (instance, options: HookDestroyOptions) => {
                    instance.update(
                        {
                            deleted_by: options.deleted_by,
                        },
                        {
                            ...options.where,
                        }
                    )
                },
            },
        }
    )
```

Controller (Take note of the bulkCreate)
```
import db from '../../models'
const {Product_Process} = db
export const createTest = async (
    req: SessionRequest,
    res: Response,
    next: NextFunction
) => {
    try {
        if (!req.body.length) throw badRequestError()

        let created_by = 0

        if (req.authSession) {
            const { user_id } = req.authSession
            created_by = user_id
        }

        if (!created_by) throw authorizationError()

        await Product_Process.bulkCreate(req.body)

        res.status(201).send()
    } catch (err) {
        next(err)
    }
}
````

Generated Sequelize Query (Approx, I stripped out a few fields)
```
INSERT INTO [bio].[products_processes_links] ([process_id],[created_at],[updated_at]) OUTPUT INSERTED.[id],INSERTED.[product_id],INSERTED.[process_id],INSERTED.[created_by],INSERTED.[updated_by],INSERTED.[published],INSERTED.[deleted_by],INSERTED.[created_at],INSERTED.[updated_at],INSERTED.[deleted_at] VALUES (123,'2023-05-01 23:26:56.128 +00:00','2023-05-01 23:26:56.128 +00:00')
```

**Comment by redhatva** [comment]
Running into same issue

**Comment by almasantiago** [comment]
I'm also experiencing the same issue --
"sequelize": "6.32.1"
"tedious": "16.1.0"
