### ISSUE TITLE
Default scope with include is overridden when using reload

### ISSUE THREAD

**Issue by hverlin** [sequelize/sequelize#12387]
### What are you doing?

https://github.com/papb/sequelize-sscce/pull/85

```js
const sequelize = createSequelizeInstance({
  logQueryParameters: true,
  benchmark: true,
  define: { timestamps: false }
});

const Bar = sequelize.define('Bar', {
  name: DataTypes.TEXT,
  fooId: DataTypes.INTEGER
});

const Foo = sequelize.define('Foo', {
  name: DataTypes.TEXT,
}, {
  defaultScope: {
    include: [{model: Bar}],
  }
});

Bar.belongsTo(Foo, {
  foreignKey: 'fooId',
});

Foo.hasMany(Bar, {
  foreignKey: {
    name: 'fooId',
    allowNull: false,
  },
  onDelete: 'cascade',
});


await sequelize.sync();

const foo = await Foo.create({name: 'foo'});

const bar = await Bar.create({name:'bar', fooId: foo.id});

const fooFromFind = await Foo.findByPk(foo.id);
assert.ok(fooFromFind.Bars)
assert.equal(fooFromFind.Bars[0].name, 'bar')

// here I would expect the defaultScope to be used as well
await foo.reload();

assert.ok(foo.Bars) // fails
assert.equal(foo.Bars[0].name, 'bar')
```

### What do you expect to happen?

I was expecting sequelize to use the default scope when using `reload`. 

### What is actually happening?

It seems that the default scope is overridden. In the `reload` function, if not `include` is passed, it is set to `null` by default. 

### Additional context

This was working with Sequelize 4. One workaround is to override the `reload` instance method with something like: 

```
async reload(options) {
    return this.originalMethod.reload.call(this, Object.assign({}, defaultScope, options));
}
```

If this is the expected behavior, it should be documented as a breaking change and mentioned in the documentation for `reload`.

### Environment

- Sequelize version: 5 and 6
- Node.js version: 12

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time, although I believe I could do it if I had the time...

**Comment by hverlin** [comment]
Thanks for the quick fix @sushantdhiman!

**Comment by sushantdhiman** [comment]
Thanks for the good SSCCE :)
