### ISSUE TITLE
bulkCreate on duplicate with composite unique key

### ISSUE THREAD

**Issue by brianschardt** [sequelize/sequelize#12383]
I am currently on the latest version 5.21.13 of sequelize, I am also using postgres
I have a composite unique key on 2 columns, when i do a bulk create and use updateOnDuplicate I get an error saying there is a conflict on the composite key.

```
await OrderEntity.bulkCreate(formattedOrders, {
      updateOnDuplicate:
        ['fullffilledAt', 'cancelledAt', 'rejectedAt', 'rejectedReason'],
    });
```

The raw sql has but it should be the composit key. 
```
ON CONFLICT ("orderKey")
```
Please help :)

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
