### ISSUE TITLE
Sequelize define association on Array

### ISSUE THREAD

**Issue by vaulstein** [sequelize/sequelize#12385]
## Feature Description

This maybe the wrong place to ask for this, but I don't find this in the docs nor does anyone have an answer to this on Stackoverflow and this seems like a feature that should be used by many so asking for it here.

I am trying to define an Association between an array value in one table and another field in another table. I could not find anything specific to this in the documentation.

I have two models in Sequelize as below:

```js
export const User = db.define('user', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
  },
});

export const Class = db.define('class', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
  },
  students: Sequelize.ARRAY({
    type: Sequelize.UUID,
    references: { model: 'users', key: 'id' },
  })
});
```
How can I define an association between my Class model and the user model?

```js
Class.hasMany(User, { foreignKey: 'students' });
User.belongsTo(Class);
```

### Possible Solution

I was thinking if we could link it using **through** maybe if this is not possible now?

### Why should this be in Sequelize

Cases where we don't want duplication of data by creating several rows for a one to many mapping and would still want to maintain an association seems to be solved by this

### Is this feature dialect-specific?

- [ x ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Even if we support such association, I don't think any database engine supports foreign key to array element. For example https://stackoverflow.com/questions/41054507/postgresql-array-of-elements-that-each-are-a-foreign-key. So concept of `references` wont make sense here, as this reference is not enforceable by database.

Can you elaborate upon data duplication? I think you need `belongsToMany` instead of `hasMany`, it seems like a `N:M` relationship
