### ISSUE TITLE
Why there is no "where" option with findByPk?

### ISSUE THREAD

**Issue by mrrishimeena** [sequelize/sequelize#12392]
Why there is no "where" option with findByPk?

**Comment by GoudekettingRM** [comment]
I would expect because a primary key is unique by default. Since there can only be one entry with that specific primary key, adding a where clause is a bit over the top.

There might be more/other reasons, I'm no expert.

**Comment by sushantdhiman** [comment]
Because it is strictly used for finding by primary key. If you want to find a single record with `where`, use `findOne`
