### ISSUE TITLE
upsert method and increment field

### ISSUE THREAD

**Issue by Tampacz** [sequelize/sequelize#12391]
### What was unclear/insufficient/not covered in the documentation

Don't know how to increment field by using "upsert" method

### If possible: Provide some suggestion on how we can enhance the docs

examples

### Additional context

Regular sql query:
```
    INSERT INTO myTable (id, name) 
    VALUES  ('123', 'John Smith')
    ON DUPLICATE KEY UPDATE points = points + '1'
```

Tried it with sequelize (but for sure bad code):
```
const records = {
      id: 123,
      name: 'John Smith',
};
const options = {
     fields: ['points', 1]
};

const x = await model.upsert(records, options); // output: true 
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
This is not supported, input payload has to be used with INSERT command as well
