### ISSUE TITLE
model.bulkCreate modifies the "options" by assigning "model" as an attribute to the object

### ISSUE THREAD

**Issue by sandeepraheja** [sequelize/sequelize#12406]
## Issue Description
While using model.bulkCreate, as we pass the options, an object which contains transaction, it comes modified after the execution

### What are you doing?

We have called bulkCreate on a model object. The options object which is prepared as an argument to the function, if we check it after execution, it contains the reference to the model object.

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_The options object should not have been modified._

### What is actually happening?

_The options object now have a reference to "model" object._

```
Output here
```

### Additional context
When we checked the code in sequelize -> model.js, it reflected the assignment on the passed in argument, instead of using the cloned copy of "options"

![image](https://user-images.githubusercontent.com/2988299/85297810-df390d00-b4c0-11ea-929d-74a68ec33986.png)

### Environment

- Sequelize version: 5.21.10
- Node.js version: 12.16.3
- Operating System: MacOS Catalina, Ubuntu 18.04
- If TypeScript related: TypeScript version: 4.28.9

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time, although I believe I could do it if I had the time...

**Comment by walkerps** [comment]
Hey!, It's my first time contribution. I would like to take a stab at this issue.

Please correct me if i'm wrong here , in this issue all we need to do is create a copy of Model's object and assign it to `option.model` rather than assigning the reference to model's object right?

**Comment by sandeepraheja** [comment]
Nope, I think you need to clone options (just like other implementations in the same file) using Object.assign,
Assign the cloned object to options.
and then let the model assignment in options work as it is.

This will make sure the passed in object reference is not polluted

**Comment by walkerps** [comment]
oh yeah, thanks. On it

**Comment by JuarezLustosa** [comment]
Hello, @walkerps are still working on this?

**Comment by darkmtr** [comment]
@JuarezLustosa I went ahead and raised a fix. Do review it
