### ISSUE TITLE
Rollbacks within transactions when using stored procedure does not work.

### ISSUE THREAD

**Issue by CodTicker** [sequelize/sequelize#12400]
I have a mysql db and I have created a stored procedure that inserts data into multiple tables. 

I am using sequelize in my node express server and I am using transactions. 

The scenario in the proc is the following: 

**INSERT INTO TABLE1 --- SUCCESS
INSERT INTO TABLE2 --- SUCCESS
INSERT INTO TABLE3 -- FAIL SINCE I DELIBERATELY SEND IN A FAULTY VALUE.** 

What happens via sequalize: 

**Executing (798e1c55-ae4a-475c-beb2-d6187a2a3065): START TRANSACTION;
Executing (default): CALL registerUser (ALL PARAMS)
Executing (798e1c55-ae4a-475c-beb2-d6187a2a3065): ROLLBACK;
ERROR { SequelizeDatabaseError: Incorrect string value: '\x9BB\xB3\xD0\xB2'...' for column** 

**PROBLEM:** 

The first two inserts which were successfull are not rolledback. I can see values in TABLE1 and TABLE2 but obviosly no value in TABLE3. I would expect that when rollback is called that all inserts would get removed, to be 100% clear I would expect the data that was inserted in TABLE1 and TABLE2 to be removed on rollback. 

The code: 

```
export const executor = async (query: Function, db: any) => {
  try {
    const result = await db.sequelize.transaction({ autocommit: false }, async t => {
      const resp = await query(t);

      return resp;
    });

    // If the execution reaches this line, the transaction has been committed successfully
    // `result` is whatever was returned from the transaction callback.
    return result;
  } catch (error) {
    // If the execution reaches this line, an error occurred.
    // The transaction has already been rolled back automatically by Sequelize!

    // log here

    console.log('ERROR', error);

    throw new Error('Internal server error');
  }
};
```
Called like this: 

```
        const r = await executor(
          param =>
            db.sequelize.query(
              'CALL registerUser (:email, :password, :roleId, :firstName, :lastName, :age, :jobTitle, :prefLanguageId, :assigned, :eventId, :imageId, :tableId, :position)',
              {
                replacements: {
                  email: args.input.Email,
                  password: PasswordHash,
                  roleId: 1,
                  firstName: args.input.FirstName,
                  lastName: args.input.LastName,
                  age: new Date(new Date(args.input.Age).toUTCString()),
                  jobTitle: args.input.JobTitle,
                  prefLanguageId: 1,
                  assigned: false,
                  eventId: '9b42b3d0-b227-11ea-b63f-9746e0754cfe', // context user eventId id
                  imageId,
                  tableId: null,
                  position: null,
                },
              },
              { transaction: param }
            ),
          db
        );
```

Using version : "^5.21.12"

Im not sure if this is a bug or if Im doing it wrong.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
