### ISSUE TITLE
Rollbacks within transactions when using stored procedure does not work.

### ISSUE THREAD

**Issue by CodTicker** [sequelize/sequelize#12402]
## Issue Description

I have a mysql db and I have created a stored procedure that inserts data into multiple tables. 

I am using sequelize in my node express server and I am using transactions. 

The scenario in the proc is the following: 

**INSERT INTO TABLE1 --- SUCCESS
INSERT INTO TABLE2 --- SUCCESS
INSERT INTO TABLE3 -- FAIL SINCE I DELIBERATELY SEND IN A FAULTY VALUE.** 

What happens via sequalize: 

**Executing (798e1c55-ae4a-475c-beb2-d6187a2a3065): START TRANSACTION;
Executing (default): CALL registerUser (ALL PARAMS)
Executing (798e1c55-ae4a-475c-beb2-d6187a2a3065): ROLLBACK;
ERROR { SequelizeDatabaseError: Incorrect string value: '\x9BB\xB3\xD0\xB2'...' for column** 

**PROBLEM:** 

The first two inserts which were successfull are not rolledback. I can see values in TABLE1 and TABLE2 but obviosly no value in TABLE3. I would expect that when rollback is called that all inserts would get removed, to be 100% clear I would expect the data that was inserted in TABLE1 and TABLE2 to be removed on rollback. 

The code: 

```
export const executor = async (query: Function, db: any) => {
  try {
    const result = await db.sequelize.transaction({ autocommit: false }, async t => {
      const resp = await query(t);

      return resp;
    });

    // If the execution reaches this line, the transaction has been committed successfully
    // `result` is whatever was returned from the transaction callback.
    return result;
  } catch (error) {
    // If the execution reaches this line, an error occurred.
    // The transaction has already been rolled back automatically by Sequelize!

    // log here

    console.log('ERROR', error);

    throw new Error('Internal server error');
  }
};
```
Called like this: 

```
        const r = await executor(
          param =>
            db.sequelize.query(
              'CALL registerUser (:email, :password, :roleId, :firstName, :lastName, :age, :jobTitle, :prefLanguageId, :assigned, :expId, :imageId, :tableId, :position)',
              {
                replacements: {
                  email: args.input.Email,
                  password: PasswordHash,
                  roleId: 1,
                  firstName: args.input.FirstName,
                  lastName: args.input.LastName,
                  age: new Date(new Date(args.input.Age).toUTCString()),
                  jobTitle: args.input.JobTitle,
                  prefLanguageId: 1,
                  assigned: false,
                  expId: '9b42b3d0-b227-11ea-b63f-9746e0754cfe', // context user eventId id
                  imageId,
                  tableId: null,
                  position: null,
                },
              },
              { transaction: param }
            ),
          db
        );
```

Using version : "^5.21.12"

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/62491971/sequelize-transactioons-with-stored-procedures

### Is this issue dialect-specific?

- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?
- [x] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by CodTicker** [comment]
As a comment ot this. I have managed to go arround this by adding a transaction inside of the proecedure but it defeats the purpose of using sequelize and I would like to know if this is a bug or if Im simply doing something wrong.

**Comment by sushantdhiman** [comment]
I don't see how I can execute this code. Can you submit a SSCCE? See [these issues](https://github.com/sequelize/sequelize/issues?q=is%3Aissue+label%3A%22Great+SSCCE%22+) to learn how to file a good issue

---------------------------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by abhilashnamdeo** [comment]
Can anybody please help me to create stored procedure using sequelize..

**Comment by ephys** [comment]
Use `sequelize.query`:

```typescript
sequelize.query(`
  CREATE PROCEDURE insert_data(a integer, b integer)
  LANGUAGE SQL
  BEGIN ATOMIC
    INSERT INTO tbl VALUES (a);
    INSERT INTO tbl VALUES (b);
  END;
`);
```

Then, to call it:

```
sequelize.query(`CALL insert_data(:a, :b);`, {
  replacements: {
    a: 1,
    b: 2,
  },
});
```

Source for postgres https://www.postgresql.org/docs/current/sql-createprocedure.html, syntax may vary based on dialect

**Comment by abhilashnamdeo** [comment]
Hi @ephys - Getting sql syntax error
Error details:- 
code: 'ER_PARSE_ERROR',
errno: 1064,
sqlState: '42000',
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''USP_USER_METRICS_INFORMATION'()\n" +
' BEGIN\n' +
" ' at line 1",

**Comment by ephys** [comment]
> syntax may vary based on dialect

Use the syntax for stored procedure that correspond to MySQL 
https://dev.mysql.com/doc/refman/8.0/en/create-procedure.html
https://dev.mysql.com/doc/refman/8.0/en/call.html
