### ISSUE TITLE
Sqlite upsert returns nothing, but the docs are vague

### ISSUE THREAD

**Issue by EyePulp** [sequelize/sequelize#12414]
## Issue Description
I'm using the `sqlite` dialect and when using **upsert** it consistently returns `undefined` under sqlite, and returns a two element array under `postgres` using the same call.
```js
const foo = await db.models.Organization.upsert(
        { name: 'fake-test-org', isActive: true },
        { returning: true }
    );

// foo is undefined under sqlite
// foo is [instance, boolean] under postgres
``` 

### What was unclear/insufficient/not covered in the documentation
The [documentation](https://sequelize.readthedocs.io/en/latest/api/model/#upsertvalues-options-promisecreated) notes that:

> Note that SQLite returns undefined for created, no matter if the row was created or updated. This is because SQLite always runs INSERT OR IGNORE + UPDATE, in a single query, so there is no way to know whether the row was inserted or not.

What's not clear is that **no** values are going to be returned from the upsert -- not the `instance` or the `created` status.

### If possible: Provide some suggestion on how we can enhance the docs
If nothing is returned at all, then the "note" in the docs could be more explicit about that -- as they're written currently it leaves the expectation that just the boolean `created` value will be undefined, but leaves the impression you might still get back the model instance.

### Additional context
Using versions:
```js
    "sequelize": "^5.21.13",
    "sqlite3": "^4.2.0"

   // OS Binary -- SQLite version 3.28.0
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): `sqlite`
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
You are reading incorrect docs https://sequelize.org/v5/

**Comment by EyePulp** [comment]
Thanks for the correction @sushantdhiman.  It wasn't apparent what version of the docs I was using.  My mistake!
