### ISSUE TITLE
Arrays are not being overwritten after merging options

### ISSUE THREAD

**Issue by hsynlms** [sequelize/sequelize#12418]
### What are you doing?

I am trying to overwrite `defaultScope` to be able to run my custom `order by` claus.

### What do you expect to happen?

If the target array (provided in the query by myself) is provided and it is not an empty array, it should have been used. Otherwise the source array. Current approach breaks flexibility.

```
PRODUCT'S DEFAULT SCOPE
{ 
  order: [
    ['displayOrder', 'ASC']
  ]
}

PRODUCT SCOPE IN THE QUERY
{ 
  order: [
    ['price', 'ASC']
  ]
}

LATEST SCOPE RESULT
{ 
  order: [
    ['price', 'ASC']
  ]
}
```

### What is actually happening?

```
PRODUCT'S DEFAULT SCOPE
{ 
  order: [
    ['displayOrder', 'ASC']
  ]
}

PRODUCT SCOPE IN THE QUERY
{ 
  order: [
    ['price', 'ASC']
  ]
}

LATEST SCOPE RESULT
{ 
  order: [
    ['displayOrder', 'ASC'],
    ['price', 'ASC']
  ]
}
```

### Additional context

Using Lodash union method causes that issue in `_mergeFunction`.

And this issue related with the following one:
https://github.com/sequelize/sequelize/issues/10696

### Environment

- Sequelize version: 6.0.0-beta.6
- Node.js version: 12.18.0
- Operating System: Windows 10

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by alex-parra** [comment]
I've faced a similar situation and posted a solution (while the PRs aren't merged) at:
https://github.com/sequelize/sequelize/issues/11415#issuecomment-735018005
