### ISSUE TITLE
Package exports for '...\node_modules\uuid' do not define a valid '.' target.

### ISSUE THREAD

**Issue by ynhhoJ** [sequelize/sequelize#12419]
### What do you expect to happen?

Run code without errorss.

### What is actually happening?

Error: ``Package exports for '...\node_modules\uuid' do not define a valid '.' target.``

### Environment

- Sequelize version: sequelize@6.0.0-beta.7
- Node.js version: v13.13.0 
- Operating System: Windows 10
- If TypeScript related: TypeScript version: 3.8.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Not related to Sequelize https://github.com/uuidjs/uuid/issues/466

**Comment by ynhhoJ** [comment]
But in ``sequelize@6.0.0-beta.6`` everything is okay

**Comment by sushantdhiman** [comment]
Not sure but this is not related to Sequelize, try removing / reinstalling `node_modules`

**Comment by elmoura** [comment]
Hey there! I was having the same problem using the `Node.js v13.1.0` version.

It looks like this error occurs at some not LTS versions of Node. I installed the `v12.18.3` and it solved my problem.
Hope it helps you too.

**Comment by 4ch1** [comment]
Hi, I had the same problem  using Node.js v13.0.0 version.

I have changed my version to Node.js v14.0.0( for example command : nvm install v14.0.0)  and and fixed issue
