### ISSUE TITLE
Select, insert and unique key 

### ISSUE THREAD

**Issue by emilianito** [sequelize/sequelize#12424]
I need to select an integer field  (based on certain conditions) and then insert a new register with value N+1 
Here an example:

I'm using Postgres

```javascript

let transaction = await this.db.sequelize.transaction()

const ticket = await this.db
      .Ticket.findOne({
        where: {
          CenterId: centerId,
        },
        order: [['number', 'DESC']]
      }, { transaction })

newTicket.number = ticket.number + 1

await this.db.Ticket.create(ticketId, { transaction })

```

unique key (centerId, number)

Sometimes, this code crashes due to unique key violation.

I think I should run both queries (select and insert) in an atomic way.

Would you recommend something to solve this problem?

Thanks!

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
