### ISSUE TITLE
ID not being generated with unique UUID

### ISSUE THREAD

**Issue by chrishj59** [sequelize/sequelize#12425]
## Issue Description
The value for the id column is not passed in the SQL INSERT statement where the  data type  UUID and  the default value is Sequelize.UUIDV4.
The documentation states that sequelize will generate a unique UUID where the default is specified
### What are you doing?

I create a table with id having a data type of UUID and the default that should generate a new UUID as per the documentation.
The minimal table definition is:
"use strict";
module.exports = {
	up: (queryInterface, Sequelize) => {
		return queryInterface.createTable("Flevels", {
			id: {
				defaultValue: Sequelize.UUIDV4,
				allowNull: false,
				autoIncrement: false,
				primaryKey: true,
				type: Sequelize.UUID,
			},
			name: {
				type: Sequelize.STRING,
			},
			rank: {
				type: Sequelize.INTEGER,
			},
			createdAt: {
				allowNull: false,
				type: Sequelize.DATE,
			},
			updatedAt: {
				allowNull: false,
				type: Sequelize.DATE,
			},
		});
	},
	down: (queryInterface, Sequelize) => {
		return queryInterface.dropTable("Flevels");
	},
};

### What do you expect to happen?
I expect the record to be inserted

### What is actually happening?

```
The validation error shown below is reported
null value in column "id" violates not-null constraint
```

### Environment

- Sequelize version: sequelize@5.21.5
- Node.js version: v12.16.1
- Operating System: macOPS Catalina 10.15.5

### How does this problem relate to dialects?

- [ X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
I don't see any code to insert the record, how are you doing that.

**Comment by chrishj59** [comment]
I populate using the below:
rows.map(async (el, idx) => {
		const flevel = {};
		flevel.name = el[0];
		flevel.rank = el[1];
		try {
			await models.Flevel.create(flevel);
			
		} catch (err) {
			console.error(err.message);
			res.status(424).send({ error: err.message });
			return;
		}

The manual has  the below for UUIDs

For UUIDs, use DataTypes.UUID. It becomes the UUID data type for PostgreSQL and SQLite, and CHAR(36) for MySQL. Sequelize can generate UUIDs automatically for these fields, simply use Sequelize.UUIDV1 or Sequelize.UUIDV4 as the default value:

{
  type: DataTypes.UUID,
  defaultValue: Sequelize.UUIDV4 // Or Sequelize.UUIDV1
}

**Comment by sushantdhiman** [comment]
Works for me with `master` branch, if you want more help present your issue as a SSCCE

**SSCCE**

```js
const Sequelize = require("./index");
const DataTypes = Sequelize.DataTypes;
const sequelize = require("./test/support").createSequelizeInstance({});

(async () => {
  const Foo = sequelize.define(
    "Foo",
    {
      id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        allowNull: false,
        autoIncrement: false,
        primaryKey: true,
      },
      name: {
        type: Sequelize.STRING,
      },
      rank: {
        type: Sequelize.INTEGER,
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
    },
    {
      timestamps: true,
    }
  );

  await sequelize.sync({ force: true });

  const record = await Foo.create({ name: "some-name" });

  console.log(record.toJSON());
})().catch((e) => console.error(e));
```

**SQL**

```sql
Executing (default): DROP TABLE IF EXISTS `Foos`;
Executing (default): DROP TABLE IF EXISTS `Foos`;
Executing (default): CREATE TABLE IF NOT EXISTS `Foos` (`id` UUID NOT NULL PRIMARY KEY, `name` VARCHAR(255), `rank` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Foos`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Foos_1`)
Executing (default): INSERT INTO `Foos` (`id`,`name`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4);
{ id: '019941ab-40cb-4805-b6da-d10b3b71380b',
  name: 'some-name',
  updatedAt: 2020-06-27T06:14:01.332Z,
  createdAt: 2020-06-27T06:14:01.332Z }
```

**Comment by morgancmartin** [comment]
Unless I'm misunderstanding, I think the reason for this ticket is due to a typo in the UUID documentation at https://sequelize.org/master/manual/model-basics.html#uuids

> {
  type: DataTypes.UUID,
  defaultValue: Sequelize.UUIDV4 // Or Sequelize.UUIDV1
}

should be:

> {
  type: DataTypes.UUID,
  defaultValue: DataTypes.UUIDV4 // Or DataTypes.UUIDV1
}
