### ISSUE TITLE
get in response the through attribute from table linker

### ISSUE THREAD

**Issue by jechazelle** [sequelize/sequelize#12427]
I would like to know how can I get the extra field in result on belongsToMany/belongsToMany link ?

I have three tables :
> Courses, Sections, CoursesSections

I try this request, but in the result I don't found the "position" field :

    db.Course.findOne({
        where: {
            id: 1,
        },
        include: [
            {
                model: db.Section,
                as: "sections",
                through: {
                    attributes: ["position"],
                },
            },
        ],
        order: [[Sequelize.literal("position"), "ASC"]],
    }).then((response) => {
        return response // <= I don't found the "position" field
    })

> Migration linker table, with 2 foreign key and 1 extra field :

    return queryInterface.createTable("CoursesSections", {
        id: {
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            type: Sequelize.INTEGER,
        },
        fk_course_id: {
            allowNull: false,
            type: Sequelize.INTEGER,
            references: {
                model: "courses",
                key: "id",
            },
        },
        fk_section_id: {
            allowNull: false,
            type: Sequelize.INTEGER,
            references: {
                model: "sections",
                key: "id",
            },
        },
        position: {
            defaultValue: 0,
            type: Sequelize.INTEGER,
        },
    })

> Course model :

    Course.associate = (models) => {
        models.Course.belongsToMany(models.Section, {
            as: "sections",
            through: "CoursesSections",
            foreignKey: "fk_course_id",
            otherKey: "fk_section_id",
        })
    }

> Section model :

    Section.associate = (models) => {
        models.Section.belongsToMany(models.Course, {
            as: "courses",
            through: "CoursesSections",
            foreignKey: "fk_section_id",
            otherKey: "fk_course_id",
        })
    }

I use sequelize 5.22.0

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
