### ISSUE TITLE
Website is broken, all 404

### ISSUE THREAD

**Issue by janpio** [sequelize/sequelize#12439]
https://sequelize.org/master, https://sequelize.org/master/manual/model-instances.html and all other sub pages give a Github Pages 404 for me.

**Comment by sushantdhiman** [comment]
Comments used in https://github.com/sequelize/sequelize/pull/12435 can't be parsed by `marked.js`, I have fixed this in https://github.com/sequelize/sequelize/commit/eca352414afe4cd7baed08ede4f2c5589f8e77e1

Website will be live soon

**Comment by sushantdhiman** [comment]
https://sequelize.org/v5 should be working, you can use that until I redeploy changes

**Comment by sushantdhiman** [comment]
`master` version is online again, let me know if you are still facing any issues.

**Comment by janpio** [comment]
Thanks for the quick fix, seems working again now.
