### ISSUE TITLE
SequelizeDatabaseError: The multi-part identifier "User.name" could not be bound.

### ISSUE THREAD

**Issue by Devoldini** [sequelize/sequelize#12436]
## Issue Description
Hello.
I getting an error: **'SequelizeDatabaseError: The multi-part identifier "User.name" could not be bound.'**

### What are you doing?

```js
order.findAll({
  attributes: [
    'id',
    'number',
    [Sequelize.col('User.name'), 'user_name'],
  ],
  include: [
    {
      model: m_users,
      as: 'User',
      required: false,
      attributes: [],
    },
  ],
 offset: 0,
 limit: 5,
  order: [
    ['id', 'DESC'],
  ],
})
```

It's generate a query:
```
SELECT 
	[order].*, 
FROM 
	(SELECT 
		[order].[id], 
		[order].[number],
		[User].[name] AS [user_name],
		[order].[author] 
	FROM 
		[order] AS [order] 
	ORDER BY 
		[order].[id] DESC 
	OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY
	) AS [order] 

 LEFT OUTER JOIN [users] AS [User] 
 ON [order].[author] = [User].[id] 
 
 ORDER BY 
	[order].[id] DESC;
```

if i comment up 'offset & limit' block it will generate a query:

```
SELECT 
	[order].[id], 
	[order].[number], 
	[User].[name] AS [user_name], 
FROM [order] AS [order]

LEFT OUTER JOIN [users] AS [User] 
ON [order].[author] = [User].[id] 

ORDER BY 
	[order].[id] DESC;
```
Now it's works but now i haven't my 'user_name' column outside 'User' model if i want to use 'offset & limit' block.

The problem is that Sequelize add **[User].[name] AS [user_name]** to 'order' sub-query where no any 'User' table in FROM statement.

And one more question. 
Why it's duplicate 'ORDER BY' statement in main block and sub-query? 
Is it not enough to leave it only in sub-query block?

Thanks.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
