### ISSUE TITLE
Ability to overwrite column attributes without requiring them in the creation attributes

### ISSUE THREAD

**Issue by j-m** [sequelize/sequelize#12448]
#### Short version
To be able to do this:
```ts
Session.create({ UserId: user.id })
```
instead of this
```ts
Session.create({ id: null, createdAt: null, expiresAt: null, version: null, UserId: user.id })
```
when using ```Model.init``` with Typescript and extending model interfaces.

#### Long version
Let's say I have the following:

```ts
import { Model, DataTypes } from 'sequelize'
import { database } from '../connection'

export interface SessionAttributes extends SessionCreationAttributes {
  id: string
  createdAt: Date
  updatedAt: Date
  expiresAt: Date
  version: string
}

export interface SessionCreationAttributes {
  UserId: number
}

export class Session extends Model<SessionAttributes, SessionCreationAttributes>
  implements SessionAttributes {
  public id!: string
  public UserId!: number
  public version!: string

  public readonly createdAt!: Date
  public readonly updatedAt!: Date
  public readonly expiresAt!: Date
}

Session.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      autoIncrement: false,
      primaryKey: true,
      allowNull: false,
    },
    UserId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    version: {
      type: DataTypes.STRING(11),
      defaultValue: process.env.npm_package_version,
      allowNull: false,
    },
    expiresAt: {
      type: DataTypes.DATE,
      defaultValue: new Date(
        Date.now() +
          Number(process.env.COOKIE_EXPIRE_MINUTES || 60 * 24) * 60 * 1000
      ),
    },
  },
  {
    sequelize: database,
    tableName: 'sessions',
  }
)
```

I had to add non creation attributes to the init method because I want to override the datatypes and default values.

I want to be able to create an instance of the model without having to specify null for all the other values, feels clunky and is asking for something to go wrong. 

### Describe the solution you'd like

For the proposed code to work; I don't mean that in a snarky way, the only alternative I think can think of is having another subset of attributes, like how you have creationAttributes, but dedicated to overriding default/assumed properties.

### Why should this be in Sequelize

Far too tightly coupled to sequelize to realistically be its own package.

### Describe alternatives/workarounds you've considered

Use
```ts
export class Session extends Model<SessionAttributes, SessionAttributes>
```
and
```ts
Session.create({ id: null, createdAt: null, expiresAt: null, version: null, UserId: user.id })
```
instead of the ideal
```ts
export class Session extends Model<SessionAttributes, SessionCreationAttributes>
```
and
```ts
Session.create({ UserId: user.id })
```

### Additional context

None

### Is this feature dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by j-m** [comment]
(pressed Ctrl + Enter by mistake, will delete the comment when actually done)

**Comment by j-m** [comment]
Sorry, my example was wrong, but the principle remains.

You cannot do
```
Session.create({ id: null, createdAt: null, expiresAt: null, version: null, UserId: user.id })
```

UserId is a foreign key and there is a 1:m assosication for User:Session so you would normally create a Session using a `HasManyCreateAssociationMixin user.createSession`

However, lets ignore the foreignkey and pretend there is other data. Given the attributes are notNull and have default values, it would make sense to be able to omit them from `.create`, otherwise what would be the point in having default values.

**Comment by Keimeno** [comment]
Id version expires at

You can already do that. Please check the docs [here](https://sequelize.org/master/manual/typescript.html).

```ts
  ...
  Optional
} from 'sequelize';

Type SessionCreationAttributes = Optional<SessionAttributes, 'id' | 'version' | 'expiresAt'>
```

Then you must only add the userId.

Also if you want to see how that's done with an interface, check the docs above.

**Comment by j-m** [comment]
Perfect! Hardly mentioned at all in the docs... I can see why a lot of focus is on improving them
