### ISSUE TITLE
SaveOptions type is missing hooks option

### ISSUE THREAD

**Issue by cnorthwood** [sequelize/sequelize#12441]
### What are you doing?

This TypeScript fails a type check in V6 (given a model is defined)

```js
  const user = await User.findByPk(id);
  if (user === null) {
    return;
  }
  user.lastLogin = new Date();
  await user.save({ hooks: false });
```

The typing for SaveOptions is missing `hooks?: boolean` in it. Looking at the code, it appears the `hooks` option is still there, and it is documented, so this is a type error I think.

### What do you expect to happen?

The snippet above should pass a typecheck.

### What is actually happening?

```
error TS2345: Argument of type '{ hooks: boolean; }' is not assignable to parameter of type 'SaveOptions<any>'.
```

### Environment

- Sequelize version: 6.2.3
- Node.js version: v14.1.0
- Operating System: macOS
- If TypeScript related: TypeScript version: 3.9.5

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance. (specifically I don't know where the types are actually defined, I can't see them in this repo)
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
You can submit a PR for `v6` branch, here is the relevant code 

https://github.com/sequelize/sequelize/blob/945af927db60e964eba7e344665ed0594ee63231/types/lib/model.d.ts#L967
