### ISSUE TITLE
unexpected error when using findOne() instead of findAll()

### ISSUE THREAD

**Issue by FranckFreiburger** [sequelize/sequelize#12455]
## Issue Description

When trying to find entries with no association, I noticed that `findOne()` does not work whereas `findAll()` works properly

### What are you doing?

```
import sequelizeModule from 'sequelize'
const { Sequelize, Model, DataTypes, Op } = sequelizeModule;

;(async () => {

	const sequelize = new Sequelize('sqlite:./test.db');

	class A extends Model {}
	A.init({
		aField: DataTypes.STRING,
	}, { sequelize, timestamps: false });

	class B extends Model {}
	B.init({
		bField: DataTypes.STRING,
	}, { sequelize, timestamps: false });

	A.hasMany(B);

	//await sequelize.drop();
	await sequelize.sync();


        // populate

	await A.create({
		aField: 'fooA',
		Bs: [{ bField: 'fooB' }]
	}, { include: [B] });

	await A.create({ aField: 'barA' });

	await A.create({ aField: 'bazA' });

	let result = await A.findAll({
		include: [{
			model: B,
			required: false,
		}],
		where: {
			'$Bs.AId$': null,
		},
	});
	// SQL: Executing (default): SELECT A.id, A.aField, Bs.id AS Bs.id, Bs.bField AS Bs.bField, Bs.AId AS Bs.AId FROM As AS A LEFT OUTER JOIN Bs AS Bs ON A.id = Bs.AId WHERE Bs.AId IS NULL;

	// returns barA and bazA (as expected)

	console.log( result );


	result = await A.findOne({
		include: [{
			model: B,
			required: false,
		}],
		where: {
			'$Bs.AId$': null,
		},
	});
	// SQL: SELECT A.*, Bs.id AS Bs.id, Bs.bField AS Bs.bField, Bs.AId AS Bs.AId FROM (SELECT A.id, A.aField FROM As AS A WHERE Bs.AId IS NULL LIMIT 1) AS A LEFT OUTER JOIN Bs AS Bs ON A.id = Bs.AId;

	// error: no such column: Bs.AId

	console.log( result );

})().catch(err => console.error(err));
```

Note that I am not sure to use the best way do what I am trying to do: get entries with associated model is empty (in this case, just return bar and baz): ```SELECT * FROM `As` LEFT JOIN `Bs` ON `Bs`.`AId` = `As`.`id` WHERE `Bs`.`id` IS NULL LIMIT 1```

### Environment

- sequelize v6.2.4
- Node.js v12.17.0
- Operating System: win7

### How does this problem relate to dialects?

I don't know, I was using SQLITE, with connector library sqlite3@5.0.0

**Comment by qq578023708** [comment]
A.hasMany(B)   need you associate model foreignKey ?

**Comment by FranckFreiburger** [comment]
`B` foreignKey is automatically created (`B.AId`).
`A.hasMany(B).foreignKey` seems properly set

**Comment by sushantdhiman** [comment]
`'$Bs.AId$': null,` this syntax is an escape hatch to inject conditions into join statements with exact column name, when passing attribute does not work for your use-case.

You will always have to change this column based on query generated. `findAll` and `findOne` generates different queries, so you need to change this for each query.

**Comment by patricktan98** [comment]
Hey guys,
I notice 1 issue when using findOne with attributes. If without attribute specification, it works as expect and the query also generated with where conditions.
User.findOne({attributes:['id','fullName','email','dob','createdAt','numOfDevice',[db.sequelize.literal(`(SELECT role FROM UserRoles WHERE UserRoles.id = User.role)`), 'role']]},{where:{email:'jacob@slack.com'},raw:true})
Sequelize interpretes it as 'SELECT `id`, `fullName`, `email`, `dob`, `createdAt`, `numOfDevice`, (SELECT role FROM UserRoles WHERE UserRoles.id = User.role) AS `role` FROM `Users` AS `User` LIMIT 1;'
It is a known bug? or I did something wrong?
