### ISSUE TITLE
(POSTGRES) upsert returned record does not work for composite keys

### ISSUE THREAD

**Issue by dyuan-boxlabs** [sequelize/sequelize#12457]
## Issue Description
When using upsert() with option {returning: true} on a table with composite keys, only one portion of the composite key is used when returning the upserted record.

### What are you doing?
Upserting two records with different data, then comparing the returned records. (Refer to SSCCEE)

[Sequelize] Executed (default): CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert(OUT created boolean, OUT primary_key text)  AS $func$ BEGIN INSERT INTO "Foos" **("key1","key2","data") VALUES (1,1,'1') RETURNING "key1"** INTO primary_key; created := true; EXCEPTION WHEN unique_violation THEN UPDATE "Foos" SET "key1"=1,"key2"=1,"data"='1' WHERE (("key1" = 1 AND "key2" = 1)) RETURNING "key1" INTO primary_key; created := false; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert(); [Elapsed time: 2 ms] 
[Sequelize] Executed (default): SELECT "key1", "key2", "data" FROM "Foos" AS "Foo" **WHERE "Foo"."key1" = '1'**; [Elapsed time: 0 ms] 
[Sequelize] Executed (default): CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert(OUT created boolean, OUT primary_key text)  AS $func$ BEGIN INSERT INTO "Foos" **("key1","key2","data") VALUES (1,2,'2') RETURNING "key1"** INTO primary_key; created := true; EXCEPTION WHEN unique_violation THEN UPDATE "Foos" SET "key1"=1,"key2"=2,"data"='2' WHERE (("key1" = 1 AND "key2" = 2)) RETURNING "key1" INTO primary_key; created := false; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert(); [Elapsed time: 1 ms] 
[Sequelize] Executed (default): SELECT "key1", "key2", "data" FROM "Foos" AS "Foo" **WHERE "Foo"."key1" = '1'**; [Elapsed time: 0 ms] 

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/90

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

Expect the returned records to be different.

"{\"key1\":\"1\",\"key2\":\"1\",\"data\":\"1\"}"
"{\"key1\":\"1\",\"key2\":\"1\",\"data\":\"1\"}"
{ AssertionError: expected '1' to not equal '1'
    at module.exports (/home/travis/build/papb/sequelize-sscce/src/sscce.js:45:45)
  message: 'expected \'1\' to not equal \'1\'',
  showDiff: true,
  actual: '1',
  expected: '1' }

### What is actually happening?

The second returned record is incorrect.

```
Output here
```

"{\"key1\":\"1\",\"key2\":\"1\",\"data\":\"1\"}"
"{\"key1\":\"1\",\"key2\":\"1\",\"data\":\"1\"}"
{ AssertionError: expected '1' to not equal '1'
    at module.exports (/home/travis/build/papb/sequelize-sscce/src/sscce.js:45:45)
  message: 'expected \'1\' to not equal \'1\'',
  showDiff: true,
  actual: '1',
  expected: '1' }

### Environment

- Sequelize version: sequelize@5.21.5 
- Node.js version: v12.13.1 
- Operating System: Windows 10 Pro
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): Postgres 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Update to v6, Upsert implementation has changed with v6
