### ISSUE TITLE
Sqlite dialect reports UniqueConstraintError for Non-null constraints

### ISSUE THREAD

**Issue by jondot** [sequelize/sequelize#12465]
If you check the flow here: https://github.com/sequelize/sequelize/blob/master/src/dialects/sqlite/query.js#L420
Any constraint that will fail (specifically non-null) will be wrapped in a UniqueConstraintError. The Sequelize instance will contain the _correct_ sqlite error, but will not show it, and mistakenly misinform users.

**Comment by sushantdhiman** [comment]
Thanks for reporting this

-----------------------------

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
