### ISSUE TITLE
Retry sequelize.authenticate multiple times

### ISSUE THREAD

**Issue by lucbas** [sequelize/sequelize#12460]
## Issue Description

I try to implement a retry logic that tries and waits for a defined time before making a new authentication call.

As I'm not aware of a built-in logic, I tried the following code but without success and would appreciate ideas for this issue.

```javascript
const retries = 10;

const tryTimeout = async (currentTry, retries) => {
  setTimeout(function () {
    logger.info(`Try: ${currentTry}, ${retries} retries left.`);
  }, 1000);
};

for (let i = 1; i <= retries; i++) {
  try {
    // Establish database connection
    SEQ_CONNECTION.authenticate()
      .then(() => {
        logger.info('*** Database connection has been established successfully.');
      })
      .catch(async (err) => {
        logger.info('Error in connect database function: ', err);
        throw err;
      });
    SEQ_HEALTHCHECK_CONNECTION.authenticate()
      .then(() => {
        logger.info(
          '*** Database connection for healthcheck has been established successfully.',
        );
      })
      .catch(async (err) => {
        logger.error('Error in connect database function for healthcheck: ', err);
        throw err;
      });
  } catch (error) {
    logger.error('Error in connectDB retry function');
    await tryTimeout(i, retries - i);
  }
}
```

### Additional context

I require such a logic, as sequelize has to wait before the Google CloudSQL proxy to become ready. Afterwards migrations are executed with Umzug.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
