### ISSUE TITLE
Inconsistent typing of Create functions

### ISSUE THREAD

**Issue by Shahaed** [sequelize/sequelize#12463]
## Issue Description

`BelongsToCreateAssociationMixin` typing does not seem consistent with standard `Create` types.

https://github.com/sequelize/sequelize/blob/9a45509e3f4b23b957a195190dd989ea33cae8d8/types/lib/associations/belongs-to.d.ts#L119 Seems to expect an object with an implicit key signature of string while https://github.com/sequelize/sequelize/blob/9a45509e3f4b23b957a195190dd989ea33cae8d8/types/lib/model.d.ts#L1979 expects a standard JavaScript object. 

### What do you expect to happen?

If we had:
```ts
interface UserData {
  id: number;
  name: string;
}

interface ProjectData {
  id: number;
}

class Project extends Model {
  id!: number;
  
  public addUser: BelongsToCreateAssociationMixin<User>;
}

// Project.init etc...

const newProjectData : ProjectData = { id: 1};
const newProject = Project.create(newProjectData); // Works

const newUser: UserData = { id: 1, name: "John"};
newProject.addUser(newUser); // Throws type error
```

Since this behavior works for the standard create function, we would expect no errors from the TSC. 

### What is actually happening?

`Project.addUser(newUser); ` throws the following error: `Argument of type 'UserData' is not assignable to parameter of type '{ [attribute: string]: unknown; }'.
  Index signature is missing in type 'UserData '.`

### Additional context

This error makes sense when looking at the type definitions files. A simple change of https://github.com/sequelize/sequelize/blob/9a45509e3f4b23b957a195190dd989ea33cae8d8/types/lib/associations/belongs-to.d.ts#L120 from ` values?: { [attribute: string]: unknown },` to ` values?: object,` (like it is on the standard `create()` would fix this. For consistency all create functions should use the same type signatures. 

### Environment

- Sequelize version: 5.xx  BUT THE CODE I LINKED IS FROM V6
- If TypeScript related: TypeScript version: 3.9

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Shahaed** [comment]
Not stale

**Comment by WikiRik** [comment]
Thanks for letting us know the issue is not stale. I quickly made a [PR](https://github.com/sequelize/sequelize/pull/13640) that implements your suggested change. Would this fix your issue?

**Comment by WikiRik** [comment]
@Shahaed I believe that https://github.com/sequelize/sequelize/pull/13678 and https://github.com/sequelize/sequelize/pull/13685 have fixed this issue, do you agree?

**Comment by ephys** [comment]
After working on these recently, I'm pretty sure the issue isn't there anymore. Let us know if that's not the case and we'll reopen this issue.
