### ISSUE TITLE
v7 Typescript Migration, Change Code Style

### ISSUE THREAD

**Issue by Keimeno** [sequelize/sequelize#12470]
### Describe the solution you'd like

I believe it to be a very good step to migrate the codebase to Typescript for v7, however I'd like to propose some code style conventions.

For instance in the [index-hints.ts][index] file, currently we are:
1. exporting with older node styles
2. using default exports

I believe it would be a better approach to change the code in [index-hints.ts][index] to the following:
```ts
...
export enum IndexHints {
  USE = 'USE',
  FORCE = 'FORCE',
  IGNORE = 'IGNORE'
}
```
[index]: https://github.com/sequelize/sequelize/blob/master/src/index-hints.ts

### Why should this be in Sequelize

Named exports have better auto-completion support, and I believe that the new es module exports are easier to use.

### Is this feature dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### Additionally

I'd like to help migrate the codebase to typescript. Are there any written guidelines for Typescript provided? Also could you provide an example file that I could work on, so we don't have any merge conflict in the end?

**Comment by sushantdhiman** [comment]
>Named exports have better auto-completion support, and I believe that the new es module exports are easier to use.

I have not used named exports to prevent changing import/require statement where ever those enums are used. I am avoiding unnecessary changes, for now.

> I'd like to help migrate the codebase to typescript. Are there any written guidelines for Typescript provided? Also could you provide an example file that I could work on, so we don't have any merge conflict in the end?

I would like to migrate this project to Typescript myself :) But please keep reviewing related PRs/commits and suggest changes freely.
