### ISSUE TITLE
Sequelize Models and Migrations for component based folder strucutre

### ISSUE THREAD

**Issue by sujeet-agrahari** [sequelize/sequelize#12479]
For small project, I usually go with role based folder structures having controllers, models, migrations etc.

But as the project size grows, It is very hard manage all the files and services.

So I have decided to go with component based folder structure for one of my project. But the problem I am facing is that 

_There is no option to specify models and migrations path to sequelize_

Below is my folder strcuture.

```
|---src
     |---user
     |    |--- user.controller.js
     |    |--- user.service.js
     |    |--- model.js
     |    |--- index.js
     |    |--- migrations
     |            |--- xxx123-migration.js
     |            |--- xxx1235-migration.js
     |---payment
          |--- payment.controller.js
          |--- payment.service.js
          |--- payment.model.js
          |--- index.js
          |--- migrations
                  |--- xxx123-migration.js
                  |--- xxx1235-migration.js
```

Is it possible, somehow, to specify path for these files in sequelize and sequelize-cli?

This is what I have tried for models but it's not working.
```

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');

const env = process.env.NODE_ENV || 'development';
const config = require(`${__dirname}/../config/config.json`)[env];
const db = {};

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(`${__dirname}/../`)
  .filter((file) => file.endsWith('.model.js'))
  .forEach((file) => {
    const model = sequelize.import(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});
db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by Jefry16** [comment]
Did you find any answer to this situation @sujeet-agrahari ?

**Comment by ephys** [comment]
The next Sequelize 7 release includes a new [`importModels`](https://github.com/sequelize/sequelize/blob/main/src/import-models.ts) function, that is designed for this purpose:
https://github.com/sequelize/sequelize/blob/main/src/sequelize.d.ts#L328-L330

In v6, [Sequelize-TypeScript](https://www.npmjs.com/package/sequelize-typescript#globs) offers this feature as well

Otherwise the problem with the implementation in the top post is that their readdirSync is not recursive, so it only reads the first level of folders, but their models are in nested folders

**Comment by sujeet-agrahari** [comment]
I used ‘glob’ which scans the ‘src’ directly for files ending with ‘.model.js’ but migrations needs to be in one directory only.
