### ISSUE TITLE
minifyAliases: true with literals

### ISSUE THREAD

**Issue by wertlex** [sequelize/sequelize#12472]
## Issue Description
It turns out that there is no way to use literal both in attributes and ordering, when `minifyAliases = true`

### What are you doing?
Running in postgres, if you using literal in attributes and want to order result by the same literal, generated query is incorrect.

```js
const postgresConfig = {
	url:     'postgres://postgres:postgres@localhost:5432/sequelize_issue_sample',
	options: {
		dialect:        'postgres',
		logging:        console.log,
		minifyAliases:  true,
		dialectOptions: {
			ssl: false
		}
	}
};

const sequelize = new Sequelize(
	postgresConfig.url,
	postgresConfig.options
);

const User = sequelize.define('User', {
	id: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		autoIncrement: true
	},
	notice_period: {
		type: Sequelize.INTEGER,
		allowNull: false
	},
	end_date: {
		type: Sequelize.DATE
	}
});

async function main() {
	await User.sync();

	const cancellationDateLiteral = Sequelize.literal(`end_date - interval '1 month' * coalesce(notice_period,0)`);

	await User.findAll({
		attributes: ['id', [cancellationDateLiteral, 'cancellation_date']],
		order: [[Sequelize.literal('cancellation_date')]]
	});
}

main();

```

### What do you expect to happen?

Here is a query generated when `minifyAliases = false`:

```SQL
SELECT "id", end_date - interval '1 month' * coalesce(notice_period,0) AS "cancellation_date" 
FROM "Users" AS "User" 
ORDER BY cancellation_date;
```

### What is actually happening?

Here is a query generated when `minifyAliases = true`: 
```SQL
SELECT "id", end_date - interval '1 month' * coalesce(notice_period,0) AS "_0" 
FROM "Users" AS "User" 
ORDER BY cancellation_date;
```

Attribute `end_date - interval ...` aliased as `_0`, while it is not aliased in `ORDER BY`. Obviously it leads to error: `column "cancellation_date" does not exist`.

### Additional context

I have a suspicion that replacing literals with shorter `_n` mapping could be potentially erroneous. So, the question is how to deal with that kind of queries using Sequelize, when ordering by literal?
Maybe literals shouldn't be minified at all?

### Environment

- Sequelize version: 6.3.0 
- Node.js version: 10.21.0 
- Operating System: macOS

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by RomanYankovsky** [comment]
According to the source code we can workaround this by using `subquery_order_0` as column name.
https://github.com/sequelize/sequelize/blob/9f950cbcbdd659d559496b77c40e0f827b108561/lib/dialects/abstract/query-generator.js#L1626-L1643

Doesn't look very nice, but works for me.

**Comment by globalmatt** [comment]
I've just run into this issue too. @RomanYankovsky's workaround works for now, but it would be good to have a more robust solution going forward, such as being able to disable minification for a specific query or alias.

**Comment by ephys** [comment]
Sequelize will use the contents of literals (almost) as-is. If you want to refer to an alias using a literal, you should define it as a literal too:

```typescript
await User.findAll({
  attributes: ['id', literal(`(end_date - interval '1 month' * coalesce(notice_period,0)) AS cancellation_date`)],
  order: [[literal('cancellation_date')]],
});

// SELECT "id", (end_date - interval '1 month' * coalesce(notice_period,0)) AS cancellation_date FROM "Users" AS "User" ORDER BY cancellation_date;
```

That being said, IMO the following should work, but it doesn't:

```typescript
await User.findAll({
  attributes: ['id', [literal(`end_date - interval '1 month' * coalesce(notice_period,0)`), 'cancellation_date']],
  order: [['cancellation_date']],
});
```

**Comment by bodolawale** [comment]
@mrrinot  If we could use `minifyAliases:  true` at the query level, as defined in the [docs](https://sequelize.org/api/v7/interfaces/_sequelize_core.findoptions#minifyAliases) it would have been easier to manage.
But having this option at a global level is scary.
