### ISSUE TITLE
_ModelOptions removed from instance in V6

### ISSUE THREAD

**Issue by WaylonOKC** [sequelize/sequelize#12486]
## Issue Description

In Sequelize v5, my instance would look like:
```
recentItem {
  dataValues: {
    id: 't4qupOzsuPrxLuHkLiYwA',
    createdAt: 2019-07-23T22:07:43.727Z,
    updatedAt: 2020-07-08T19:30:13.348Z,
    entityId: 'SJleJVAA_z'
  },
  _previousDataValues: {
    id: 't4qupOzsuPrxLuHkLiYwA',
    createdAt: 2019-07-23T22:07:43.727Z,
    updatedAt: 2020-07-08T19:30:00.122Z,
    entityId: 'SJleJVAA_z'
  },
  _changed: { updatedAt: true },
  _modelOptions: {
    timestamps: true,
    validate: {},
    freezeTableName: false,
    underscored: false,
    paranoid: false,
    rejectOnEmpty: false,
    whereCollection: {
      entityId: 'SJleJVAA_z'
    },
    schema: null,
    schemaDelimiter: '',
    defaultScope: {},
    scopes: {},
    indexes: [],
    name: { plural: 'recentItems', singular: 'recentItem' },
    omitNull: false,
    sequelize: Sequelize {
      options: [Object],
      config: [Object],
      dialect: [PostgresDialect],
      queryInterface: [QueryInterface],
      models: [Object],
      modelManager: [ModelManager],
      connectionManager: [ConnectionManager],
      importCache: [Object],
      Op: [Object],
      Promise: [Function]
    },
    hooks: {}
  },
  _options: {
    isNewRecord: false,
    _schema: null,
    _schemaDelimiter: '',
    raw: true,
    attributes: [ 'id', 'createdAt', 'updatedAt', 'entityId' ]
  },
  isNewRecord: false
}
```

In Sequelize v6, I do not have the `_modelOptions`. How can I get the model information (_modelOptions)? It's needed because the instance could be one of several different models.

### StackOverflow / Slack attempts

[StackOverflow Question](https://stackoverflow.com/questions/62802524/getting-instance-modeloptions-in-sequelize-6)

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Use `instance.constructor.options`

**Comment by WaylonOKC** [comment]
Thanks!

**Comment by jalopez526** [comment]
> Use `instance.constructor.options`

Have this been written on docs? I spent some hours looking for something like this.

**Comment by jackilex** [comment]
> > Use `instance.constructor.options`
> 
> Have this been written on docs? I spent some hours looking for something like this.
