### ISSUE TITLE
cli is failing to generate all fields in model

### ISSUE THREAD

**Issue by mickeypuri** [sequelize/sequelize#12489]
### I am trying to use the CLI to generate the model file

`npx sequelize-cli model:generate --name users --attributes name:string,email:string,fav_pizza:string,space_invaders:integer`

### What do you expect to happen?

I expected to create a model file for users with the fields name, email, fav_pizza, space_invaders

### What is actually happening?

The model is created but it only has the first field declared after attributes, in this case the name field. If I change the field order, then whatever field is first declared is the only field created in the model file.

```
module.exports = (sequelize, DataTypes) => {
  const users = sequelize.define('users', {
    name: DataTypes.STRING
  }, {});
  users.associate = function(models) {
    // associations can be defined here
  };
  return users;
};
```

### Environment

Sequelize CLI [Node: 12.16.2, CLI: 5.5.1, ORM: 5.22.3]

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Report this to CLI repository
