### ISSUE TITLE
Leaving the project

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#12501]
Due to some personal reasons I will no longer actively maintain this project or other child projects. Sequelize team will internally decide which member(s) will take care of issues & PRs especially security issues.

I have added other members to various packages so they can continue to push changes. Semantic release & documentation will keep updating automatically for now.

**Comment by papb** [comment]
Thank you so much @sushantdhiman for all the hard work you've done in this project, all these years!! It has been great. Be well, stay safe!

**Comment by papb** [comment]
Me, @eseliger and @SimonSchick will be taking care of things for now, stay tuned :eyes:

**Comment by JuarezLustosa** [comment]
Thank you @sushantdhiman for all support.

**Comment by stevemarksd** [comment]
Hi! If you guys need a typescript dev, I can offer my help :) I have +10 years of js and +2y of typescript experience. I think I can really help on the project

**Comment by papb** [comment]
Hi @stevemarksd! Thank you very much! Sorry to take so long to reply. I and other maintainers were very busy with non-sequelize things but we should have more time now. Are you still interested in helping?
