### ISSUE TITLE
Unable to order findAll results by nested associations

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#1250]
When eager-loading nested includes in findAll(), it is not possible to order by attributes of the nested associations.

e.g.:

```
var Company = sequelize.define('Company', {
    name: Sequelize.STRING
});

var Division = sequelize.define('Division', {
    name: Sequelize.STRING
});

var Department = sequelize.define('Department', {
    name: Sequelize.STRING
});

Company.hasMany(Division);
Division.hasMany(Department);

Company.findAll({include: [{model: Division, include: [Department]}], order: ['name', 'Divisions.name', 'Divisions.Departments.name']})
```

The findAll statement fails as it produces SQL:

```
ORDER BY `name`, `Divisions`.`name`, `Divisions`.`Departments`.`name`
```

rather than:

```
ORDER BY `name`, `Divisions`.`name`, `Divisions.Departments`.`name`
```

Of course, you can get around it by using {raw: '`Divisions.Departments`.`name`'}, but since the intention of the ORM is to distance the user from the underlying SQL, I feel it'd be better if using raw could be avoided.

Looks like this could be achieved by modifying QueryGenerator.quote() (or QueryGenerator.quoteIdentifiers() but I don't know if that change would impact elsewhere in negative ways).

Apologies that I'm producing a lot of issues - just using (and loving) Sequelize a lot at the moment, and am coming across a few things as I go...

**Comment by JacopoDaeli** [comment]
This should help: http://sequelize.readthedocs.org/en/latest/docs/models-usage/index.html#nested-eager-loading

**Comment by zouchengzhuo** [comment]
order:[["order_index","asc"]]
this way can work :)
