### ISSUE TITLE
MSSQL Stored Procedure

### ISSUE THREAD

**Issue by sencersoylu** [sequelize/sequelize#12511]
I'm trying to execute stored procure but i'm getting error 
`DatabaseError [SequelizeDatabaseError]: There is already an object named 'sp_ISEMRI_PLAN_TEMP' in the database.`

My code 

`query(
        "exec sp_ISEMRI_YARAT @xSTOKNO =:STOCKCODE, @xMIKTAR = :xMIKTAR ,@xDERECE = :xDERECE ,@xDIFIZYON = :xDIFIZYON,@xARAC_SIRANO = :xARAC_SIRANO ,@xISE_TURU = :xISE_TURU", {
          type: db.Sequelize.QueryTypes.RAW,
          replacements: {
            STOCKCODE: stockCode,
            xMIKTAR: 1,
            xDERECE: '',
            xDIFIZYON: '',
            xARAC_SIRANO: '',
            xISE_TURU: ''
          }
        }
      )`

**Comment by testn** [comment]
sounds like this is a problem in your code that was trying to create a stored procedure.
