### ISSUE TITLE
Cannot Update an instance using set if primary key was changed to custom field from id

### ISSUE THREAD

**Issue by itsMagondu** [sequelize/sequelize#12514]
### What are you doing?

I have a model that I created with `id` as the primary key. Over time I changed my mind on this and made a custom field the primary key. I can save new items into the database successfully. Updating using `set` is what fails.

```
module.exports = (sequelize, DataTypes) => {
  const Item = sequelize.define('Item', {
    name: DataTypes.STRING,
    itemRef: {
      type: DataTypes.STRING,
      primary: true,
    },
  }, {
    paranoid: true,
    defaultScope: {
      attributes: { exclude: ['deletedAt', 'createdAt', 'updatedAt', 'id'] },
    },
  });
  return Item;
};
```
```
const item = await Item.findOne({ where: { itemRef:'ref1' } });
await item.set({ name:'updated name' });
await item.save()
```

### What do you expect to happen?
I expect the instance to save the updated data into the database successfully.

### What is actually happening?

Whenever I create an instance of the object `item`, update it and try to save, I keep getting the error
```
You attempted to save an instance with no primary key, this is not allowed since it would result in a global update
```

### Environment

- Sequelize version: sequelize@6.3.3
- Node.js version: v14.4.0
- Operating System: MacOS 10.15.5

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by alxndrsn** [comment]
I've recreated this behaviour with the following script:

```
/*
 * Dependencies:
 * - "sequelize": "^6.3.5",
 * - "sqlite3": "^5.0.0"
 */

const { Sequelize, Model, DataTypes } = require('sequelize');
const sequelize = new Sequelize('sqlite::memory:');

const Item = sequelize.define(
  'Item',
  {
    name: DataTypes.STRING,
    itemRef: {
      type: DataTypes.STRING,
      primary: true,
    },
  },
  {
    paranoid: true,
    defaultScope: {
      attributes: { exclude: ['deletedAt', 'createdAt', 'updatedAt', 'id'] },
    },
  }
);

(async () => {
  await sequelize.sync();
  await Item.create({ itemRef:'ref1', name:'alice' });
  const item = await Item.findOne({ where:{ itemRef:'ref1' } });
  await item.set({ name:'updated name' });
  await item.save()
})();
```

This creates the following table:
```
CREATE TABLE IF NOT EXISTS `Items` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255), `itemRef` VARCHAR(255),
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `deletedAt` DATETIME);
```

Could this be a typo in your model definition?  (ref https://sequelize.org/v5/manual/legacy.html#primary-keys)

Changing `primary: true` to `primaryKey: true` makes the code run without throwing an error.  The table creation becomes:

```
CREATE TABLE IF NOT EXISTS `Items` (
  `name` VARCHAR(255),
  `itemRef` VARCHAR(255) PRIMARY KEY,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `deletedAt` DATETIME);
```

Alternatively, if you want to keep the `id` column, you could remove `'id'` from `defaultScope.attributes.exclude`.

**Comment by itsMagondu** [comment]
Thanks @alxndrsn I have tested it and you are correct. fixing the typo fixed the issue.
