### ISSUE TITLE
`model.update()` fails when combining `{ returning: true, individualHooks: true }`

### ISSUE THREAD

**Issue by nitsanavni** [sequelize/sequelize#12530]
### What are you doing?

I'm running `model.update(..., { returning: true, individualHooks: true })`

here's a minimal running example:
https://github.com/nitsanavni/sequelize-returning-individual-hooks

### What do you expect to happen?

not to fail

### What is actually happening?

it fails with error:

```
TypeError { message: 'instances.map is not a function' }
    › Function.update (node_modules/sequelize/lib/model.js:3173:35)
```

reproduce the failure by running:
```
npm i -g git+https://github.com/nitsanavni/sequelize-returning-individual-hooks.git
```

failure also can be seen here:
https://github.com/nitsanavni/sequelize-returning-individual-hooks/runs/888942781?check_suite_focus=true

### Additional context

NA

### Environment

- Sequelize version: 6.3.3
- Node.js version: v12.18.1
- Operating System: Mac Os
- If TypeScript related: TypeScript version: 3.9.7 (don't think it's related to typescript)

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by djalmar-gutierrez** [comment]
Got the same problem here, anyone found a solution or a workaround?
