### ISSUE TITLE
TABLESAMPLE support

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#12554]
### Is your feature request related to a problem? Please describe.

SQL:2003 defines the `TABLESAMPLE` clause to select random rows of a table. It is supported in Postgres 9.5,  SQL Server 2005, and many other database systems in one form or another ([Oracle](https://blogs.oracle.com/machinelearning/to-sample-or-not-to-sample-part-2), [DB2](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.perf.doc/doc/c0010970.html)), although not MySQL nor SQLite to my knowledge.

From the [Postgres docs](https://www.postgresql.org/docs/current/sql-select.html):

> A TABLESAMPLE clause after a table_name indicates that the specified sampling_method should be used to retrieve a subset of the rows in that table. This sampling precedes the application of any other filters such as WHERE clauses. 

### Describe the solution you'd like

Options added to `Model.findAll` to support `TABLESAMPLE`. 

A naive version of the API could look like
```js
Model.findAll({
  sample: {
    method: 'system', // or 'bernoulli' or whatever other methods are supported in your DB
    percent: 50, // or whatever percent you want
    repeatableSeed: x // optional seed to make sampling more deterministic
  }
});
```

Complicating this is the fact that databases may implement [custom sampling methods via extensions](https://www.postgresql.org/docs/current/tablesample-method.html). Such custom sampling methods may not deal in percents and may even take multiple arguments.

For example, SQL Server also supports a [ROWS syntax](https://www.mssqltips.com/sqlservertip/1308/retrieving-random-data-from-sql-server-with-tablesample/) in addition to the standard percent form. Postgres has a comparable `SYSTEM_ROWS` feature via the [`tsm_system_rows` extension](https://www.postgresql.org/docs/current/tsm-system-rows.html) as well as `SYSTEM_TIME` via the [`tsm_system_time` extension](https://www.postgresql.org/docs/current/tsm-system-time.html). 

A more flexible API supporting custom sampling methods, including ones not know to Sequelize, could look like this
```js
Model.findAll(
  tableSample: {
    sampleMethod: {
      name: 'CUSTOMSAMPLINGMETHOD',
      args: [1, 2, 'whatever'] // not sure how to safely escape this
    }
  }   
);
```

To my knowledge `TABLESAMPLE` is [only supported in `SELECT` queries](https://www.2ndquadrant.com/en/blog/tablesample-in-postgresql-9-5-2/), so support need not be added to `Model.update` or `Model.destroy`: 

> Although it cannot be used for UPDATE or DELETE queries, it can be used with any join query and aggregation.

### Why should this be in Sequelize

This would add support for a part of the SQL standard that is implemented (in one form or another) by most major databases systems.

### Describe alternatives/workarounds you've considered

The common alternative is to order by a random value. However, this can be both slower and less accurate than TABLESAMPLE.

### Additional context

More resources:
https://www.postgresql.org/docs/current/tablesample-method.html
https://wiki.postgresql.org/wiki/TABLESAMPLE_Implementation
https://www.2ndquadrant.com/en/blog/tablesample-in-postgresql-9-5-2/
https://docs.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-2016

### Is this feature dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): Postgres, SQL Server 

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Artiesy** [comment]
Still waiting for implementation

**Comment by 0ui0** [comment]
这个特性可以用了吗
