### ISSUE TITLE
Migrations: allow env variables to added to config.json

### ISSUE THREAD

**Issue by maddy2get** [sequelize/sequelize#1255]
Hi there,

Is there any change that we can write config.json as https://github.com/kunklejr/node-db-migrate have?

The problem is: My production env is on Engine Yard and when I clone an env, I have to update my db settings depending on which env I push my code to.

If this can be done, that would be great. Is this request implemented? -https://github.com/sequelize/sequelize/issues/1173

Thanks,

Sanjay

**Comment by janmeier** [comment]
This belongs in https://github.com/sequelize/umzug

**Comment by alditis** [comment]
Review section "Using Environment Variables" of: [http://docs.sequelizejs.com/manual/tutorial/migrations.html#configuration](http://docs.sequelizejs.com/manual/tutorial/migrations.html#configuration)

**Comment by fadykstas** [comment]
solution https://github.com/sequelize/cli/issues/77
