### ISSUE TITLE
How to define default scope using Typescript

### ISSUE THREAD

**Issue by vinkaga** [sequelize/sequelize#12555]
### What was unclear/insufficient/not covered in the documentation

How to define default scope for a model, e.g.
```ts
interface UserAttributes {
  id: number;
  name: string;
  preferredName: string | null;
}
interface UserCreationAttributes extends Optional<UserAttributes, "id"> {}

class User extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes {
  public id!: number; // Note that the `null assertion` `!` is required in strict mode.
  public name!: string;
  public preferredName!: string | null; // for nullable fields
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}
```
How would I define default scope with `updatedAt desc` sort order?

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by arthur-conde** [comment]
Have you had any success defining _any_ scopes at all?

Using the [example here](https://github.com/sequelize/sequelize/blob/v6/docs/manual/other-topics/typescript.md) and ``yarn add sequelize@latest`` I am getting an error.

```js
User.addScope('default', {
    include: [
        {
            model: Project
        }
    ]
});
```

![image](https://user-images.githubusercontent.com/16407164/96378148-6765b100-1147-11eb-8f41-29903f33bc48.png)
