### ISSUE TITLE
defaultValue: false doesn't work right

### ISSUE THREAD

**Issue by bartmelton** [sequelize/sequelize#12560]
Creating a boolean column with a defaultValue: false doesn't work right.  Essentially it is being ignored entirely.

Sequelize v6.3.0 
MySql v8.21

```
fieldName: {
  type: DataTypes.BOOLEAN,
  defaultValue: false
}
```
If you omit [fieldName] when you create a row, the value gets set to null.  This breaks all sorts of queries because you have to query as != true instead of = false.

```
fieldName: {
  type: DataTypes.BOOLEAN,
  defaultValue: false,
  allowNull: false
}
```
Throws an error if you omit [fieldName] during a create.

I checked MySql by doing an INSERT directly both with and without the NOT NULL flag and omitting the field and it gets populated with the default value in both cases.  That means in the first case, sequelize is explicitly setting NULL instead of omitting the field and in the second case sequelize is just throwing an error for no reason other than it ignores false as a default value.

**Comment by bartmelton** [comment]
After thinking about this for a minute, I think it only happens with bulkCreate().

**Comment by papb** [comment]
Can you please create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) showing this?
