### ISSUE TITLE
[Postgres] Alter: true doesn't delete existing constraints

### ISSUE THREAD

**Issue by Igorjan94** [sequelize/sequelize#12569]
## Issue Description
When I use postgres with schema, `{alter: true}` on `sync` doesn't drop existing constraints

### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/98

### What do you expect to happen?
I expect table 'Bars' contains only one foreign key

### What is actually happening?
'Bars' contain two foreign keys

### Environment

- Sequelize version: 6.3.3
- Node.js version: v14.5.0
- Operating System: Linux archlinux 4.19.101-1-lts #1 SMP Sat, 01 Feb 2020 16:35:36 +0000 x86_64 GNU/Linux

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by KreativJos** [comment]
This is also an issue in sqlserver. 
My guess is this can be quite easily solved by querying for existing constraints for that table:
```sql
SELECT obj.name AS FK_NAME,
    sch.name AS [schema_name],
    tab1.name AS [table],
    col1.name AS [column],
    tab2.name AS [referenced_table],
    col2.name AS [referenced_column]
FROM sys.foreign_key_columns fkc
    INNER JOIN sys.objects obj ON obj.object_id = fkc.constraint_object_id
    INNER JOIN sys.tables tab1 ON tab1.object_id = fkc.parent_object_id
    INNER JOIN sys.schemas sch ON tab1.schema_id = sch.schema_id
    INNER JOIN sys.columns col1 ON col1.column_id = parent_column_id AND col1.object_id = tab1.object_id
    INNER JOIN sys.tables tab2 ON tab2.object_id = fkc.referenced_object_id
    INNER JOIN sys.columns col2 ON col2.column_id = referenced_column_id AND col2.object_id = tab2.object_id
WHERE sch.name = '' AND tab1.name = '' --AND col1.name = ''
```

Which should be possible for pgsql & mysql. Sqlite seems a bit more complicated.
