### ISSUE TITLE
Typescript does not allow col() as part of ProjectionAlias

### ISSUE THREAD

**Issue by JacobLey** [sequelize/sequelize#12572]
(Opening a Docs issue assuming typescript typings count as docs)

## Issue Description

When writing a sequelize query using the col() function in the `attributes` array, Typescript throws an error `Type 'Col' is not assignable to type 'string | Fn | Literal'.`

This is caused by the typing here: https://github.com/sequelize/sequelize/blob/v6/types/lib/model.d.ts#L482
> `export type ProjectionAlias = [string | Literal | Fn, string];`

As a bare minimum example, the goal is to write a query like so:

```
import { col, Model } from 'sequelize';

class MyModel extends Model {}
class MyIncludedModel extends Model {}

MyModel.findAll({
    attributes: [
        'id',
        [col('MyIncludedModel.id'), 'includedId'],
    ],
    include: [{
        model: MyIncludedModel,
        attributes: [],
    }],
    raw: true,
});
```

(obviously some more setup is required to _actually_ work, but this is enough to trigger the Typescript error).

Using the `col()` method in attributes is totally supported in code.

### What was unclear/insufficient/not covered in the documentation

The definition for ProjectionAlias is missing Col
e.g. export type ProjectionAlias = [string | Literal | Fn` | Col`, string];

### If possible: Provide some suggestion on how we can enhance the docs

Add Col to ProjectionAlias

### Additional context

I hit this issue right away, but it feels like it is explicitly left out. If there is a good reason not to use `Col` and to leave it out, I'd appreciate hearing the justification.

I'll open a PR updating typings, but the reasoning for the issue is to actually discuss why _not_ to include it (if such reason exists, and is not just oversight)

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Ctesias** [comment]
Is there a workaround for this in the meantime?

**Comment by JacobLey** [comment]
My hack is to overwrite the col typing to make it usable in other places:

```
declare module 'sequelize' {
    export function col(val: string): string;
}
```

Use at your own risk since the object returned is definitely not a string, but it tricks typescript into letting us use it. Haven't run into an issue yet

**Comment by intellix** [comment]
I think this is the same problem related to Literals as well when using them in places like group?
```
Sequelize.literal(`"AffiliateReport"."affiliateUserId"`),
```

Gives:
```
Type 'Literal' is not assignable to type 'string | Fn | Col'.
  Property 'col' is missing in type 'Literal' but required in type 'Col'.
```

**Comment by JacobLey** [comment]
https://github.com/sequelize/sequelize/issues/13104 duplicate

**Comment by papb** [comment]
Hi @JacobLey, thank you!!

**Comment by maximinetto** [comment]
Hi, in versión 6.6.2 i have the same issue
```
Model.findOne({
    attributes: [fn('MAX', col('modelId'))],
    where: {
      idSeccion,
    },
    raw: true,
  }).then((value) => {
    if (value === null) {
      return 0;
    }

    return value;
  }); 
```
It's resolve if I change the types in model.d.ts for 
`export type ProjectionAlias = readonly string | Literal | Fn | Col;`
But I don't know if it's a bad practice or broken something.

Sorry i'm a noob and my first languaje is spanish
