### ISSUE TITLE
Sequelize crash - mariaDB 10.5.4 & JSON field

### ISSUE THREAD

**Issue by usb248** [sequelize/sequelize#12583]
## Issue Description
![plantage](https://user-images.githubusercontent.com/7659927/89119973-90fd2d80-d4b2-11ea-9268-ab3b58f8ba40.png)
mariaDB 10.4 OK, but mariaDB 10.5.X crashes my app
![image](https://user-images.githubusercontent.com/7659927/89120135-1af9c600-d4b4-11ea-849d-37751384b383.png)

### What are you doing?

```js
    data: {
      type: db.Sequelize.JSON,
      allowNull: false
    },
```

```js
Store.findOne({ 
			where: { ... },
			limit: 1,
			attributes: [ 'data'], // is the json field
			include: [{
		        model: model2,
		        attributes: [...],
		        required: true,
		        include: [{
			     	model: model3,
			     	attributes: [...],
			     	required: true
			    }]
		    }]
		})
```

### What do you expect to happen?

no crash ?

### What is actually happening?

trying to `JSON.parse` on something wrong
https://github.com/sequelize/sequelize/blob/master/src/dialects/mariadb/query.js#L180-L185

### Environment

- Sequelize version: sequelize@6.3.3
- Node.js version: v12.18.3
- Operating System: debian 10
- If TypeScript related: TypeScript version: no ts

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): mariadb
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

EDIT:
After debugging, i noticed that `row[modelField.fieldName]` is already an object, so obviously, if sequelize tries to json.parse an object it throws this error.... please fix this bug.

**Comment by miladmeidanshahi** [comment]
same error
```
server error SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /opt/bazzino-backend/node_modules/sequelize/lib/dialects/mariadb/query.js:183:72
    at Array.map (<anonymous>)
    at Query.handleJsonSelectQuery (/opt/bazzino-backend/node_modules/sequelize/lib/dialects/mariadb/query.js:182:21)
    at Query.formatResults (/opt/bazzino-backend/node_modules/sequelize/lib/dialects/mariadb/query.js:127:12)
    at Query.run (/opt/bazzino-backend/node_modules/sequelize/lib/dialects/mariadb/query.js:72:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/bazzino-backend/node_modules/sequelize/lib/sequelize.js:619:16
    at async MySQLQueryInterface.select (/opt/bazzino-backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:938:12)
    at async Function.findAll (/opt/bazzino-backend/node_modules/sequelize/lib/model.js:1753:21) {

```

**Comment by seally1186** [comment]
Looked into this a bit after encountering the same issue. It seems like this is coming from the `mariadb` connector itself. With 10.4, it returns the data as a string (thus Sequelize needs to parse it), whereas it's parsing the result with server 10.5.

[This test case](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/test/integration/datatype/test-json.js#L108) would suggest that this behavior is intentional, though seemingly undocumented. It also shows a temporary workaround (which is also undocumented from what I can tell): we can pass `autoJsonMap: false` as a dialect option.

```js
const sequelize = new Sequelize(..., {
  dialectOptions: { autoJsonMap: false }
});
```

**Comment by miladmeidanshahi** [comment]
@seally1186 doesn't worked :thinking:

**Comment by ciknowles** [comment]
Came across the same error with the same setup. Obviously it also occurs in findOrCreate. Can be worked around by including the following in the migration to create the table/column

type: Sequelize.JSON,
defaultValue: '{}'

I tried just defaultValue:{} but this doesn't work. It needs to be '{}'

**Comment by ciknowles** [comment]
I was wrong. This fixes the issue on the 'create' bit of findOrCreate but still throws the error on 'find'. Sorry

**Comment by ciknowles** [comment]
Found a work around. This function mentioned above can be corrected (I replaced the .prototype in the top level of my project)

https://github.com/sequelize/sequelize/blob/master/src/dialects/mariadb/query.js#L180-L185

if (modelField.type instanceof DataTypes.JSON) {
        //value is return as String, no JSON
        rows = rows.map(row => {
          row[modelField.fieldName] = (row[modelField.fieldName] **&& (typeof row[modelField.fieldName] === 'string')**)? JSON.parse(row[modelField.fieldName]) : null;
          if (DataTypes.JSON.parse) {
            return DataTypes.JSON.parse(modelField, this.sequelize.options, row[modelField.fieldName]);
          }
          return row;
        });
      }

**Comment by usb248** [comment]
Solution : Encode your column to : utf8mb4_unicode_ci (was in utf8mb4_bin). Worked for me

**Comment by remoreichsoellner** [comment]
> @seally1186 doesn't worked 🤔

Thanks! Works for me on Maria DB Server 10.5.9 Homebrew Mac (Local Install), hopefully also working on production Server.

**Comment by remoreichsoellner** [comment]
> Looked into this a bit after encountering the same issue. It seems like this is coming from the `mariadb` connector itself. With 10.4, it returns the data as a string (thus Sequelize needs to parse it), whereas it's parsing the result with server 10.5.
> 
> [This test case](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/test/integration/datatype/test-json.js#L108) would suggest that this behavior is intentional, though seemingly undocumented. It also shows a temporary workaround (which is also undocumented from what I can tell): we can pass `autoJsonMap: false` as a dialect option.
> 
> ```js
> const sequelize = new Sequelize(..., {
>   dialectOptions: { autoJsonMap: false }
> });
> ```

Thanks! Works for me on Maria DB Server 10.5.9 Homebrew Mac (Local Install), hopefully also working on production Server.

**Comment by Arose-Niazi** [comment]
If this is still open I tried the fixes above those did not work for me.
```
const result = await logs.findAll({
            where: {
                [Op.and]: [{ Rank: { [Op.lte]: req.user.Rank } }, { ...where }],
            },
            offset: skipRecords,
            limit: perPage,
            order: [["ID", "DESC"]], //Works properly without this line
        });
```

As soon as I add this order line I get error.
```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\node_modules\sequelize\lib\dialects\mariadb\query.js:186:72
    at Array.map (<anonymous>)
    at Query.handleJsonSelectQuery (D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\node_modules\sequelize\lib\dialects\mariadb\query.js:185:21)
    at Query.formatResults (D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\node_modules\sequelize\lib\dialects\mariadb\query.js:130:12)
    at Query.run (D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\node_modules\sequelize\lib\dialects\mariadb\query.js:74:17)        
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\node_modules\sequelize\lib\sequelize.js:619:16
    at async MySQLQueryInterface.select (D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\node_modules\sequelize\lib\dialects\abstract\query-interface.js:953:12)
    at async Function.findAll (D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\node_modules\sequelize\lib\model.js:1753:21)
    at async D:\Development\Projects\NodeJS\Chashma-Seed-Portal-API\routes\api\logs.js:35:24
GET /api/logs 500 173.942 ms - 35
```

**Comment by Arose-Niazi** [comment]
Leaving a comment to remove it from stale
