### ISSUE TITLE
[BUG]Can't set UTC timezone for postgres since the connection-manager doesn't pick the timezone value from options

### ISSUE THREAD

**Issue by yedhink** [sequelize/sequelize#12599]
## Issue Description
```
DIalect: Postgres
My Local Timzone : IST(+05:30)
```

**All I wanted to do was to execute the following postgres statement's equivalent using sequelize config: `alter database dbname set timezone='UTC';`.**

By default when I create the postgres db using sequelize and then select the pg_settings using `select * from pg_settings where name = 'TimeZone';`, the following is the output:-
```sql
-[ RECORD 1 ]---+----------------------------------------------------------------
name            | TimeZone
setting         | localtime
unit            |
category        | Client Connection Defaults / Locale and Formatting
short_desc      | Sets the time zone for displaying and interpreting time stamps.
extra_desc      |
context         | user
vartype         | string
source          | configuration file
min_val         |
max_val         |
enumvals        |
boot_val        | GMT
reset_val       | localtime
sourcefile      |
sourceline      |
pending_restart | f
```

As you can see the `setting` field is `localtime`. I want it to be `UTC`, so that when ever i store some `Sequelize.DATE` data into the DB using sequelize, it should be stored in `UTC` format. Currently no matter what I try using sequelize, it is getting stored in localtime or my local timezone which is IST(+05:30).
****

### What are you doing?
**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/102
```js
// this is the sequelize config.js
module.exports = {
  "development": {
    "url": "postgres://postgres@localhost:5432/dbname",
    "dialect": "postgres",
    "keepDefaultTimezone": false,
    "timezone": '+00:00', // ----------------------> isn't this good enough to set the localtimezone of postgres to UTC?
    "operatorsAliases": '0'
  },
}
```

### What do you expect to happen?
If I set the database timezone to `UTC` via postgres console like this  `alter database dbname set timezone='UTC';` and then try to insert a `Sequelize.DATE` value of some other timezone, say `2020-08-06T12:30:00+05:30`, then it would get auto-converted to UTC time which is `2020-08-06T07:00:00+00:00`. I wanted to set the local-timezone of the database to `UTC` from sequelize. But event when i use `dialectOptions` like `useUTC:true` and explicitly set the `timezone` as `+00:00`, the database timezone `setting` still remains as `localtime` and not `UTC.`

### What is actually happening?
Assume I tried to create db and set `timezone` to `UTC` using above mentioned `sequelize config` file. Then even if i try to insert a `IST` datetime like say `2020-08-06T12:30:00+05:30`, then it gets stored to db as IST itself. Meaning no change to the datetime.

But if I try to insert `2020-08-06T07:00:00+00:00`, which is a `UTC` date, into DB, then it gets converted to `IST` even though I had set `timezone:"+00:00"` from sequelize config.

Maybe it's because the postgresql query for setting timezone is wrong? Shouldn't it be `SET TIMEZONE="VALUE"`. But check the current code here:-
https://github.com/sequelize/sequelize/blob/e1446837196c07b8ff0c23359b958d68af40fd6d/src/dialects/postgres/connection-manager.js#L215

### Additional context
I tried looking into the sequelize codebase for the connection-manager and found out that, there exists no `dialectOptions` set timezone for sequelize. The lodash picks only certain attributes, where `useUTC` or other attributes doesn't exists. Check out: https://github.com/sequelize/sequelize/blob/e1446837196c07b8ff0c23359b958d68af40fd6d/src/dialects/postgres/connection-manager.js#L97-L119

### Environment

- Sequelize version:  ^5.21.13
- Sequelize-Cli version:  ^6.2.0
- Postgres version: PostgreSQL 10.12
- Node.js version: v12.18.3
- Operating System: Ubuntu 18.04.4 LTS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by yedhink** [comment]
Closing this issue, since I think this is not an issue with Sequelize.

The dates are stored in UTC by default to postgres. But when viewing the inserted DB data via say:
- psql
- postico

The application or postgres itself displays the UTC time in the local timezone of the user/system.

Meaning if i'm in IST, then the UTC time stored in DB will be converted and displayed in IST.

You can confirm the same by running sequelize find for the date attribute from say `node repl` and displaying it's value. It should be UTC itself.

**Comment by RSS1102** [comment]
i want to ask how to read  database use UTC use `findAll`
