### ISSUE TITLE
Timezone with daylight saving is not properly working with MySQL

### ISSUE THREAD

**Issue by PasinduSenanayake** [sequelize/sequelize#12590]
### What are you doing?
sequelize config
```
import mysql2 from 'mysql2';
import Sequelize from 'sequelize';
import dbConfigs from '../config/getDbConfigs';
export default class DbManager {

  static init() {
    const configs = dbConfigs();
    DbManager.poolObj = new Sequelize(configs.database, configs.user, configs.password, {
      host: configs.host,
      dialect: 'mysql',
      timezone: "US/Central",
      dialectOptions: {
        timezone: "z",
      },

      dialectModule: mysql2,
      operatorsAliases: false,
      logging: false,
      pool: {
        max: 5,
        min: 0,
        acquire: 60000,
        idle: 10000,
      },
    });
  }

  static getConnectionPool() {
    return DbManager.poolObj;
  }
}
```

model class
```
export default function (sequelize, DataTypes) {
  const attributes = {
    operationPrimaryId: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      defaultValue: null,
      primaryKey: false,
      autoIncrement: false,
      comment: null,
      field: 'operation_primary_id',
    },
    createdBy: {
      type: DataTypes.STRING(100),
      allowNull: false,
      defaultValue: null,
      primaryKey: false,
      autoIncrement: false,
      comment: null,
      field: 'created_by',
    },
    modifiedBy: {
      type: DataTypes.STRING(100),
      allowNull: true,
      defaultValue: null,
      primaryKey: false,
      autoIncrement: false,
      comment: null,
      field: 'modified_by',
    },
    createdDate: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: null,
      primaryKey: false,
      autoIncrement: false,
      comment: null,
      field: 'created_date',
    },
    modifiedDate: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: null,
      primaryKey: false,
      autoIncrement: false,
      comment: null,
      field: 'modified_date',
    },
  };
  const options = {
    tableName: 'eligibility_operation',
    comment: '',
    createdAt: 'createdDate',
    updatedAt: 'modifiedDate',
  };
  const modal = sequelize.define('modal', attributes, options);
  return modal;
}
```

### What do you expect to happen?

I wanted the createdAt and modifiedAt to be changed accordingly. I have two records in the database.

1. created date : 2020-03-06 04:15:32 || modified date :2020-03-06 04:15:32
2. created date : 2020-07-06 04:15:32 || modified date :2020-07-06 04:15:32
Both these records are in UTC.
I fetched those two entities (on 2020-08-05) and since I specified timezone as 'US/Central' I expected the output to be following
1. created date : 2020-03-05 22:15:32 || modified date :2020-03-05 22:15:32
2. created date : 2020-07-05 23:15:32 || modified date :2020-07-05 23:15:32
I expected the difference of daylight saving should have been captured.

### What is actually happening?
When I fetched those entities on (2020-08-05) both entities are identical
1. created date : 2020-03-05 23:15:32 || modified date :2020-03-05 23:15:32
2. created date : 2020-07-05 23:15:32 || modified date :2020-07-05 23:15:32

### Additional context

When I checked the codebase I realized the issue is with the implementation.
```
    // set timezone for this connection
    // but named timezone are not directly supported in mysql, so get its offset first
    let tzOffset = this.sequelize.options.timezone;
    tzOffset = /\//.test(tzOffset) ? momentTz.tz(tzOffset).format('Z') : tzOffset;
    await promisify(cb => connection.query(`SET time_zone = '${tzOffset}'`, cb))();
```

with MySQL, the offset is injected at the moment the connection is made. Because of that, the daylight saving nature of the existing records is not captured. Offset is always relative to the time that the connection is made.

### Environment

- Sequelize version: 6.3.4  
- Node.js version: 8.12.0
- Operating System: ubuntu 18.04

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MySQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by wondie** [comment]
I have this issue too. It converts to +5 time zone event though the server and user is in -5 time zone (US Central)

**Comment by lukegalea16** [comment]
Any update on this? The timezone which I am trying to save in my DB is totally being ignored.

**Comment by abagmut** [comment]
Has someone been able to find a solution for this?
