### ISSUE TITLE
sequelize missing FROM-clause entry for table

### ISSUE THREAD

**Issue by MatteoGioioso** [sequelize/sequelize#12593]
## Issue Description

I am trying to make a join and apply a filter after the join, and so far nothing has working, either no filter was applied nor the query was successful

### What are you doing?

This is the pseudo query I am trying to achieve:

```javascript
const result = await ModelA.findAll({
          where: {
             '$ModelB.prop3$': 'SOMETHING ELSE'
             $or: [{
                  prop1: {
                      $eq: 'SOMETHING',
                  },
              },
             {
                prop2: {
                  $eq: null,
               },
              },
           ];
          },
          include: [
            {
              model: ModelB,
            },
          ],
          limit: 1000,
          transaction,
        });

```

This query produce the following error:

```
        "missing FROM-clause entry for table \"ModelB\""

```

So far I have tried all the proposed solutions: 

- `subQuery: false`
- `duplicating: false`
- `require: true`
- Eager loading filtered at the associated model level, like showed here https://sequelize.org/master/manual/eager-loading.html
This last one produce nothing, the filter does not appear in the query
```
          include: [
            {
              model: ModelB,
              where: {
                       props3: {
                           $eq: 'SOMETHING_ELSE',
                      },
                     as: 'ModelBs'
              }
            },
          ],
```

But none of those worked

### What do you expect to happen?

Should execute the query correctly

### What is actually happening?

error

```
 "missing FROM-clause entry for table \"ModelB\""
```

### Environment

- Sequelize version: 5.22.3 
- Node.js version: 8.10
- Operating System: Ubuntu

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by deema089786** [comment]
Same issue. If I use 'logging' and execute generated SQL query directly  in db all works as expected

**Comment by donleistman** [comment]
@MatteoGioioso I think I'm running into the same issue. Were you able to find a solution?
