### ISSUE TITLE
Retry on transaction level (postgres)

### ISSUE THREAD

**Issue by Alex-Wauters** [sequelize/sequelize#12608]
### Is your feature request related to a problem? Please describe.

Sequelize features automatic retry on a query level. For dialects such as Postgres, query level retries will still cause the transaction to fail with the following error:

`SequelizeDatabaseError: current transaction is aborted, commands ignored until end of transaction block`

### Describe the solution you'd like

Apply options.retry signature to the sequelize.transaction function.

```js
await sequelize.transaction({
  isolationLevel: Transaction.ISOLATION_LEVELS.SERIALIZABLE,
  retry: {
      match: [],
 },
}, async (t) => {
  // Your code
});
```

Care has to be taken how this would work with query retries defined in the Sequelize constructor.
Perhaps one option could be to simply indicate to enable retries, as per the options provided in sequelize constructor.

### Why should this be in Sequelize

The documentation & sequelize options include a retry functionality, but this will not function correctly for postgres transactions.
https://github.com/sequelize/sequelize/issues/1478#issuecomment-233950442

### Describe alternatives/workarounds you've considered

Performing retries in application code. If this is the recommended case, I would suggest updating the documentation to mention transaction retries are not supported for postres and what the recommended approach is; as asked in this comment
https://github.com/sequelize/sequelize/issues/1478#issuecomment-319145953

### Is this feature dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [X] Yes. This issue only applies to the following dialect(s): postgres, perhaps other dialects as well which abort the transaction once a query fails.

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by bpetty-formfast** [comment]
I would love to see this feature, specifically for retrying due to deadlock.

**Comment by arminm** [comment]
we are seeing the same issue... Any updates from the maintainers?

**Comment by cirosantilli** [comment]
My workaround, please send suggestion if anyone finds a problem with it: https://stackoverflow.com/questions/68427796/sequelize-transaction-retry-doenst-work-as-expected/70204395#70204395

```
async function transactionWithRetry(sequelize, transactionArgs, cb) {
  let done = false
  while (!done) {
    try {
      await sequelize.transaction(transactionArgs, cb)
      done = true
    } catch (e) {
      if (
        sequelize.options.dialect === 'postgres' &&
        e.original.code === '40001'
      ) {
        await sequelize.query(`ROLLBACK`)
      } else {
        // Error that we don't know how to handle.
        throw e;
      }
    }
  }
}
```

**Comment by ruankotovich** [comment]
I am currently trying something like this: 

```ts
export async function retrySerializableTransaction<T>(callback: (t: Transaction) => PromiseLike<T>, transactionOptions?: TransactionOptions) {
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const transaction: Transaction = await sequelize.transaction({
      ...transactionOptions,
    });
    try {
      const response = await callback(transaction);
      await transaction.commit();
      return response;
    } catch (e) {
      if (e.original?.code !== '40001') {
        await transaction.rollback();
        throw e;
      }
      logger.info('Retrying transaction due to concurrent operations (serialization error 40001)');
    }
  }
}
```

**Comment by siddhsql** [comment]
the solution by @cirosantilli rolls back if e.original.code === '40001' whereas solution by @ruankotovich does exactly the opposite. which of these is correct?

**Comment by clarencedesmarais** [comment]
It would be nice if this remained opened. The underlying issue hasn't been addressed.
