### ISSUE TITLE
ambiguous error in node12

### ISSUE THREAD

**Issue by mecoepcoo** [sequelize/sequelize#12614]
### What are you doing?

I'm trying to join one-to-many like this:

- model
```js
model.Module.belongsTo(model.ModuleDetail, {
    foreignKey: 'md_id',
    targetKey: 'md_id',
    as: 'detail',
  })
```

- query
```js
model.Module.findAll({
  include: [
    {
      model: model.ModuleDetail,
      as: 'detail',
    },
  ],
})
```

### What do you expect to happen?

maybe the SQL would be given like:
```sql
SELECT
`bar`.`md_id`,
`bar`.`md_name`,
`detail`.`id` AS `detail.id`,
`detail`.`md_id` AS `detail.md_id`,
`detail`.`img` AS `detail.img`
FROM `module` AS `bar`
LEFT OUTER JOIN `module_detail` AS `detail`
ON `bar`.`md_id` = `detail`.`md_id`;
```

### What is actually happening?

actually I get:

```sql
SELECT
``.`md_id`,
``.`md_name`,
`detail`.`id` AS `detail.id`,
`detail`.`md_id` AS `detail.md_id`,
`detail`.`img` AS `detail.img`
FROM `module` AS ``
LEFT OUTER JOIN `module_detail` AS `detail`
ON ``.`md_id` = `detail`.`md_id`;
```

and there is an error like: `Column 'md_id' in field list is ambiguous`.

### Additional context

I think the empty alias is the reason why I get this error.

when I switch the node version to 10, it won't happend.

### Environment

- Sequelize version: 5.22.3
- Node.js version: 12.18.3
- Operating System: windows10, docker image node:12-alpine, mac os catalina
- TypeScript version: 3.9.7

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by amundsen-roald** [comment]
me too.

**Comment by Robert-Ro** [comment]
can you use [n](https://classic.yarnpkg.com/zh-Hans/package/n) to downgrade your node version?
i fix this issue with this method

**Comment by mecoepcoo** [comment]
> can you use [n](https://classic.yarnpkg.com/zh-Hans/package/n) to downgrade your node version to 10.x?
> i fix this issue with this method, my node version is 10.16.0

I downgrade node version to 10 and it works well, but it is not a long term solution.

**Comment by zjjjjjjjjjjd** [comment]
same problem
