### ISSUE TITLE
Associate one column to multiple columns in another table

### ISSUE THREAD

**Issue by jrs40492** [sequelize/sequelize#12613]
## Issue Description

Hi all,

I'm creating a sports website that has a games table and a teams table. The games table has two columns for teams: homeTeamId and awayTeamId which link to the id column in the teams table. This example is found in the relations tutorial on the sequelize website, but does not show how to properly use it in a query.

I've set up the following associations:

Teams Table:
```javascript
teams.hasMany(models.games, {
  as: 'homeTeam',
  foreignKey: {
    allowNull: false,
    name: 'homeTeamId'
  },
  onDelete: 'CASCADE',
});

teams.hasMany(models.games, {
  as: 'awayTeam',
  foreignKey: {
    allowNull: false,
    name: 'awayTeamId'
  },
  onDelete: 'CASCADE',
});
```

Games Table:
```javascript
games.belongsTo(models.teams, {
  as: 'games',
  foreignKey: {
    allowNull: false,
  },
  onDelete: 'CASCADE',
});
```

Query I'm trying to produce:
```sql
SELECT teams.id, teams.name
FROM teams
INNER JOIN games
  ON teams.id IN (games.homeTeamId, games.awayTeamId)
WHERE games.week = 1
```

What I think that'd look like is this but it gives the error "SequelizeEagerLoadingError: games is associated to teams multiple times"
```javascript
Teams.findAll({
  attributes: [
    'id',
    'name'
  ],
  include: [
    {
      model: models.games,
      as: 'games',
      required: true,
      attributes: [],
      on: {
        '$teams.id$': {
          [Op.in]: [
            models.sequelize.col('games.homeTeamId'),
            models.sequelize.col('games.awayTeamId')
          ]
        }
      },
    },
  ]
```

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/63386407/sequelize-multiple-associations-between-two-tables

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by LittleLama** [comment]
Hi ! I'm interested in resolving the same problem. Did you find a solution ?
