### ISSUE TITLE
Unhandled rejection TypeError: sequelize.getQueryInterface(...).quoteIdentifier is not a function

### ISSUE THREAD

**Issue by khabLexander** [sequelize/sequelize#12627]
### What are you doing?
I dont know if this is a bug but I solve this error installing a old version of sequelize 6.3.3 before 6.3.4
this error throws when I run the comand sequelize db:drop, this morning I update sequelize on his latest version, the solution for me was install the 6.3.3 version.

**Here is the link to the SSCCE for this issue:** LINK-HERE 

### What do you expect to happen?

I dont know why this problem hapens but can u solve this plz :D I am new in this world of web development 

### What is actually happening?

No so much to say the problem was solve but with a old version of sequelize.
 

### Environment

- Sequelize version: 6.3.4 
- Node.js version: 13.9.0 
- Operating System: Windows 10
- If TypeScript related: TypeScript version: 3.9.7

### How does this problem relate to dialects?

- [*] I think this problem happens regardless of the dialect.
- [* ] I think this problem happens only for the following dialect(s):  sequelize db:drop sequelize db:create
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [* ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by placiderapson** [comment]
@albertfdp is right, the latest **sequelize-cli** version has fixed the issue for me. If you installed **sequelize-cli** globally a long time ago, you need to update it to the latest version to become compatible with the **sequelize** package.

**Comment by khanarbazz579** [comment]
you just need to install latest version of `sequelize-cli `

**Comment by PolymathWhiz** [comment]
This problem persists on `sequelize-v6.6.2` and `sequelize-cli-v6.2.0`

**Comment by PolymathWhiz** [comment]
> This problem persists on `sequelize-v6.6.2` and `sequelize-cli-v6.2.0`

Current solution is to use `sequelize-v5.x.x`

**Comment by Sulokit** [comment]
It got resolved when I used the npx command like this `npx sequelize db:create`

**Comment by lucasgonze** [comment]
This issue should be reopened. It prevents users from upgrading to 6.x.x in order to upgrade a dependency with a known vulnerability.

**Comment by sdepold** [comment]
Hey all,

I'm not yet entirely sure what we are talking about tbh but from what I get, you are facing the issue that the following code no longer works:

```
sequelize.getQueryInterface().quoteIdentifier('prop')
```

Running this code with v5, results in something like this (with pg):

```
> sequelize.getQueryInterface().quoteIdentifier('prop')
'"prop"'
```

Now, with Sequelize 6, the situation is this:

```
> sequelize.getQueryInterface().quoteIdentifier('prop')
Uncaught TypeError: sequelize.getQueryInterface(...).quoteIdentifier is not a function
```

The reason for that is, that `quoteIdentifier` ever since has been an alias for `queryGenerator.quoteIdentifier('prop')` which means you can do the following with Sequelize 6:

```
> sequelize.getQueryInterface().queryGenerator.quoteIdentifier('prop')
'"prop"'
```

Is that good enough or do you think we should still bring back the quoteIdentifier function to the queryInterface?

**Comment by sdepold** [comment]
Or you upgrade to v6.12.2 and make use of the back ported queryInterface.quoteIdentifier :D

**Comment by lucasgonze** [comment]
> Or you upgrade to v6.12.2 and make use of the back ported queryInterface.quoteIdentifier :D

I appreciate the insight and the patch. I'll explore both directions.
