### ISSUE TITLE
Seeding does not execute hooks in the model

### ISSUE THREAD

**Issue by varunrayen** [sequelize/sequelize#12629]
### What are you doing?

I am trying to seed the db, but when using model with beforeCreate hooks. Those hooks are not being executed and seeding fails

### What do you expect to happen?

Expected to run the hooks and modify the data as needed

### What is actually happening?

Seeding fails or seeding does not execute the hooks causing some null values and erroneous values

### Environment

- Sequelize CLI: 6.2.0
- Sequelize version: 6.3.4
- Node.js version: 12.13.1
- Operating System: MacOS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using postgres, with connector library version XXX and database version 12

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
This is an unfortunate consequence on how the documentation around seeding is written still today. I hope to improve it in the near future. The issue is that the `.bulkInsert` calls do not trigger any hook. To trigger hooks, you must use `.bulkCreate` instead of `.bulkInsert`.

Let me know if this works for you. I will keep this issue open as a documentation improvement.

**Comment by varunrayen** [comment]
i tried using `.bulkCreate`, I still have an issue. It throws the following error 

```shell
ERROR: queryInterface.bulkCreate is not a function
```

```javascript
module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkCreate("user", users, {});
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("user", null, {});
  },
};
```

**Comment by abdulwd** [comment]
`bulkCreate ` is defined on Model, not on QueryInterface. You can require your model and then use it.

**Comment by zanisis** [comment]
up please
