### ISSUE TITLE
_groupJoinData is not working as expected in IOS

### ISSUE THREAD

**Issue by pravintamil** [sequelize/sequelize#12630]
### I'm using the sequelize with React application that runs inside on my Electron and Capacitor application. 
I've two models namely GroupModel and EventTypeModel. The EventTypeModel belongs to GroupModel. I performed a query on GroupModel with the join of EventTpeModel. The resulting array looks valid before passing into the `_groupJoinData` function. The array returned by the `_groupJoinData` function in broken.
This code working well in Electron(Windows/Linux/Mac) and Android-Capacitor but not working in the IOS Platform.

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
const GroupModel = sequelize.define('groups', {
  name: {
    type: Sequelize.STRING,
  },
  type: {
    type: Sequelize.STRING,
    defaultValue: 'radio',
  },
  repeat_days: {
    type: Sequelize.STRING,
  },
  status: {
    type: Sequelize.STRING,
    defaultValue: 'In Progress',
  },
  event_type_id: {
    type: Sequelize.INTEGER,
    references: {
      model: EventTypeModel,
    },
    onDelete: 'SET NULL',
    allowNull: true,
  },
});
const EventTypeModel = sequelize.define(
  'event_types',
  {
    name: {
      type: Sequelize.STRING,
    },
    short_name: {
      type: Sequelize.STRING,
    },
    status: {
      type: Sequelize.BOOLEAN,
      defaultValue: 1,
    },
  },
  {
    underscored: true,
  }
);

GroupModel.belongsTo(EventTypeModel);

await EventTypeModel.create({ name: 'Event 1', short_name: 'e1' });
await GroupModel.create({name: 'Group 1', repeat_days: Tue, Wed, Thu, Fri', event_type_id: 1 });
const groups = await GroupModel.findAll({
    include: [
      { model: EventTypeModel, required: false, attributes: ['id', 'name'] },
    ],
    limit: 1,
  });
```

### What do you expect to happen?

The value of the groups variable is 
```json
[
  {
    "id": 1,
    "name": "Group 1",
    "type": "radio",
    "repeat_days": "Tue, Wed, Thu, Fri",
    "status": "In Progress",
    "event_type_id": 1,
    "createdAt": "2020-08-12T11:42:13.909Z",
    "updatedAt": "2020-08-20T08:25:04.501Z",
    "eventTypeId": 1,
    "event_type": {
      "id": 1,
      "name": "Event 1"
    }
  }
]
```
Console log
```json
Before _groupJoinData, results: 
[
  {
    "id": 1,
    "name": "Group 1",
    "type": "radio",
    "repeat_days": "Tue, Wed, Thu, Fri",
    "status": "In Progress",
    "event_type_id": 1,
    "createdAt": "2020-08-12T11:42:13.909Z",
    "updatedAt": "2020-08-20T08:07:05.665Z",
    "eventTypeId": 1,
    "event_type.id": 1,
    "event_type.name": "Event 1"
  }
]

After _groupJoinData results: 
[
  {
    "id": 1,
    "name": "Group 1",
    "type": "radio",
    "repeat_days": "Tue, Wed, Thu, Fri",
    "status": "In Progress",
    "event_type_id": 1,
    "createdAt": "2020-08-12T11:42:13.909Z",
    "updatedAt": "2020-08-20T08:23:20.089Z",
    "eventTypeId": 1,
    "event_type": {
      "id": 1,
      "name": "Event 1"
    }
  }
]
```

### What is actually happening?

The value of the groups variable is 
```json
[
  {
    "id": 1,
    "repeat_days": "Tue, Wed, Thu, Fri",
    "status": "In Progress",
    "event_type_id": 1,
    "event_type": {
      "name": "Group 1"
    }
  }
]
```
Console log
```json
Before _groupJoinData, results: 
[
  {
    "status": "In Progress",
    "event_type_id": 1,
    "repeat_days": "Tue, Wed, Thu, Fri",
    "id": 1,
    "event_type.id": 1,
    "eventTypeId": 1,
    "event_type.name": "Event 1",
    "updatedAt": null,
    "type": "radio",
    "createdAt": null,
    "name": "Group 1"
  }
]

After _groupJoinData results: 
[
  {
    "status": "In Progress",
    "event_type_id": 1,
    "repeat_days": "Tue, Wed, Thu, Fri",
    "id": 1,
    "event_type": {
      "name": "Group 1",
      "updatedAt": null,
      "type": "radio",
      "createdAt": null
    }
  }
]
```

### Environment

- Sequelize version: 6.3.3 
- Node.js version: 12.18.0
- Operating System: IOS
- Browser: Safari
- FrameWork: Capacitor

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by orionsongs** [comment]
@pravintamil So sorry that this is not an answer to your question, but your post is the only mention I can find anywhere online of someone using Capacitor with Sequelize. I am trying to do the same but I get the error `Can't find variable: process` any time I include sequelize in my Capacitor project.  Any chance you can point me to any clues on how you accomplished that? I would be ever so grateful as I'm quite stuck, and facing  rewriting tons of sequelize code to straight sqlite3.

**Comment by kishanio** [comment]
Hey there. I have been trying to compile sequalize inside capacitor by embedding nodejs mobile. Is this the right approach? Just wondering since you have already got past this part.

**Comment by orionsongs** [comment]
@pravintamil thank you so much for sharing your info. Any chance your dialect module is available somewhere or could be shared? I would be happy to contribute to it, but I'm not sure where to start if starting from scratch. Or do you have any documentation you can recommend that would help clarify what needs to be included in the dialect module? Any help would be greatly appreciated as info on this is very limited!
