### ISSUE TITLE
Feature Request: Association hooks

### ISSUE THREAD

**Issue by FredrikAppelros** [sequelize/sequelize#1264]
Currently there is no way to add a hook that triggers on a change in a many-to-many relation except to create the join table manually and add hooks to that. Other types of relations triggers the normal update hook of a model since the foreign key is part of that model's table. This creates a discrepancy in the way that associations triggers update hooks. A more user-friendly alternative would be to be able to add hooks directly to associations.

It could look something like this:

```
B.hasMany A
association = A.hasMany B
association.addHook 'afterUpdate', (instance, done) ->
    # do hooky stuff
    done()
```

With this approach you could, if you wanted to, separate association changes to have their own hooks and thus remove triggering of e.g. the normal `afterUpdate` trigger when just modifying the associations of an object.

**Comment by thefabulousdev** [comment]
+1 and -1 for the coffeescript example

**Comment by shriramshankar** [comment]
This will be a good feature to add.

**Comment by zekenie** [comment]
I've managed to get this to work, but it requires some interesting tweeks.

1) Your join table must be a model in its own right
2) You must use bulk hooks

```js
const User = db.define('user');
const Tag = db.define('user');
const UserTag = db.define('user_tag', {...}, {
  hooks: {
    // regular hooks will not fire, but bulk ones will
    afterBulkCreate() {
      // this code will run when a user is associated with a tag
      console.log('fooooO!');
    }
  }
})

User.belongsToMany(Tag, { through: UserTag });
Tag.belongsToMany(User, { through: UserTag });

someUser.addTag(someTag);
// 'foooooO!' will bein the console
```

**Comment by noonesstudios** [comment]
This is very useful, although running into problems with a correct implementation to cover my usecase:

     sequelize.define('User', {...});
     User.belongsToMany(User, {
        as: 'sibling',
        through: models.Siblings,
        foreignKey: 'one_id',
        otherKey: 'another_id',
      });
     sequelize.define('Siblings',
        {...},
        {
          hooks: {
           beforeBulkCreate: function([{dataValues}], {fields}) {
              if (Number(dataValues['one_id']) === Number(dataValues['another_id'])) {
                throw 'You cannot be your own sibling'
             }
           }
        }
     });`

This stops the creation and throws the specified error as expected.

But it also generates this error in `stdout`: 

> (node:18640) Warning: a promise was rejected with a non-error: [object String]
> (node:18640) Warning: a promise was rejected with a non-error: [object String]
> (node:18640) Warning: a promise was rejected with a non-error: [object String]

With neither `beforeValidate` / `afterValidate` hooks properly firing I remained with this question.

How can I drop a reference with my own custom validation without it generating errors?
