### ISSUE TITLE
Can't update password on Sequelize 5+ Config

### ISSUE THREAD

**Issue by jpollard-cs** [sequelize/sequelize#12646]
### What are you doing?

attempting to update the config password from a rotating token store (as shown in Sequelize documentation) is incompatible with the typings

```js
// from sequelize docs here: https://sequelize.org/master/manual/hooks.html
sequelize.beforeConnect(async (config) => {
  config.password = await getAuthToken();
});
```

this won't work with TypeScript typings without some hacking as all properties for the `Config` type are marked as `readonly`

### What do you expect to happen?

`Config` properties are not `readonly` or at least `Config.password` is not `readonly`

### What is actually happening?

`Config` properties are `readonly` - unclear if there is any specific reason for this?

My current workaround is just doing:

```typescript
type DeepWriteable<T> = { -readonly [P in keyof T]: DeepWriteable<T[P]> };
export const sequelizeConfig: SequelizeOptions = {
  dialect: 'postgres',
  hooks: {
    beforeConnect: (config: DeepWriteable<Config>): void => {
      config.password = await getAuthToken();
    }
  }
}
```

### Environment

- Sequelize version: 5.22.3 (also appears to be the same issue in latest 6.x version)

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jpollard-cs** [comment]
also while we're on the subject - why are `Config.dialectOptions` typed as

**Comment by kimxogus** [comment]
I'm having the same issue. Thanks for the workaround

**Comment by kf6kjg** [comment]
Yep, it's very annoying.  I used patch-package to convert the type defs directly, but basically the same concept.

**Comment by Bshah88** [comment]
Hello Guys, I am having same issue.
I am using NestJS with Typescript, Sequelize v6.6.2, @jpollard-cs I also used your workaround but it seems not working for me. Can you guys suggest some other solutions?
@jpollard-cs @kimxogus @kf6kjg

**Comment by jpollard-cs** [comment]
sorry @Bshah88 Sequelize 6 is an entirely different beast that I'm not yet familiar with :/

**Comment by Bshah88** [comment]
> sorry @Bshah88 Sequelize 6 is an entirely different beast that I'm not yet familiar with :/

Thanks for response. But when I tried with Sequelize v5.22.3 and Sequelize-typescript v1.1.0, your solution still don't work for me.
I am using NestJS framework.

**Comment by jpollard-cs** [comment]
@Bshah88 first of all do you actually need to be using this method? Do you have a password that is likely to change frequently between connections? Secondly I'm assuming your username, host and port aren't changing - you can set these at time of initialization of Sequelize by providing a config then (where the config is writeable and you don't need all this hackery). I'm not sure how much of the config you can actually overwrite in this hook. It's possible the username, host and/or port cannot be overwritten. I imagine there's a decent reason the type is marked as `ReadOnly` here.

**Comment by Bshah88** [comment]
> @Bshah88 first of all do you actually need to be using this method? Do you have a password that is likely to change frequently between connections? Secondly I'm assuming your username, host and port aren't changing - you can set these at time of initialization of Sequelize by providing a config then (where the config is writeable and you don't need all this hackery to make the type writeable). I'm not sure how much of the config you can actually overwrite in this hook. It's possible the username, host and/or port cannot be overwritten. I imagine there's a decent reason the type is marked as `ReadOnly` here. 

@jpollard-cs I got your point and changed my stuff accordingly. Luckily it's has started working as expected in Sequelize v5.22.3. let me try with Sequelize V6.

**Comment by msenatori** [comment]
Thanks @jpollard-cs for the workaround, i was going mad!

**Comment by Bshah88** [comment]
> > @Bshah88 first of all do you actually need to be using this method? Do you have a password that is likely to change frequently between connections? Secondly I'm assuming your username, host and port aren't changing - you can set these at time of initialization of Sequelize by providing a config then (where the config is writeable and you don't need all this hackery to make the type writeable). I'm not sure how much of the config you can actually overwrite in this hook. It's possible the username, host and/or port cannot be overwritten. I imagine there's a decent reason the type is marked as `ReadOnly` here. 
> 
> @jpollard-cs I got your point and changed my stuff accordingly. Luckily it's has started working as expected in Sequelize v5.22.3. let me try with Sequelize V6.
> 

Hello @jpollard-cs your workaround works for Sequelize v6 also.👍

**Comment by aks3213** [comment]
![image](https://github.com/user-attachments/assets/975e0758-d237-4a66-8b49-94698417ee4a)
Can someone help me with this?
