### ISSUE TITLE
"* fs in ./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js" : Impossible to use Sequelize

### ISSUE THREAD

**Issue by IazLur** [sequelize/sequelize#12657]
I installed project with npx create-nuxt-app.
I added sequelize.
I make this (photo).
I runned compilation : * fs in ./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js.
Impossible to continue my project.
I don't have WEBPACK not necessary on my nuxt app.
Please do something, your package is useless right now with nuxt.
I have also tried installing fs or bunch of another things, nothing working.

![image](https://user-images.githubusercontent.com/18015556/91662737-a0d55500-eae4-11ea-842f-648b2a110830.png)

**Comment by IazLur** [comment]
nuxt.config.js : 

add this : 

```
build: {
    extend (config, { isDev, isClient }) {
      config.node = {
        fs: 'empty'
      }
    }
  }
```

**Comment by papb** [comment]
Sequelize is intended to be used in a NodeJS environment (i.e. back-end), so it won't work in a front-end environment such as Vue.

By the way, may I ask what was your intent to use Sequelize in a Vue app?

**Comment by IazLur** [comment]
Nuxt is a back-end vuejs framework. He work on nodejs.

**Comment by papb** [comment]
Hmm, I see. I found [this](https://github.com/nuxt/nuxt.js/issues/1485#issuecomment-325102185) in a quick search, so please try wrapping the `require('sequelize')` in an `if (process.server)` block and let me know.

**Comment by IazLur** [comment]
> nuxt.config.js :
> 
> add this :
> 
> ```
> build: {
>     extend (config, { isDev, isClient }) {
>       config.node = {
>         fs: 'empty'
>       }
>     }
>   }
> ```

This is the fix I posted before :)
