### ISSUE TITLE
Why aren't my models being synced?

### ISSUE THREAD

**Issue by msrumon** [sequelize/sequelize#12658]
## Issue Description

Trying to sync models with database, but failed. In my *app.js* file, I am doing the sync:
```js
const db = require('./utils/database');
const start = async () => {
  const PORT = process.env.PORT || 4444;
  await db.sync({ alter: true }); // here
  await new Promise((resolve, reject) => {
    app.listen(PORT, resolve);
  });
  console.log(`Server is up & running on port ${PORT}...`);
};
start();
```
...but I see no queries getting executed for my models. That little utility script (*utils/database.js*) is nothing but this:
```js
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: 'database.sqlite',
});
module.exports = sequelize;

```

### StackOverflow / Slack attempts

[Asked](https://sequelize.slack.com/archives/C0CELV3N1/p1598781929006300) on Slack, but got no reply yet.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by msrumon** [comment]
I dug deep into this issue and found that the models I defined were not being attached w/ the *sequelize* instance:
```js
const { Model, DataTypes } = require('sequelize');
const sequelize = require('../utils/database');
const User = require('./user');
const Like = require('./like');
const Comment = require('./comment');
class Post extends Model {}
Post.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    title: { type: DataTypes.STRING, allowNull: false },
    body: { type: DataTypes.TEXT, allowNull: false },
  },
  { sequelize }
);
Post.belongsTo(User);
Post.hasMany(Like);
Post.hasMany(Comment);
module.exports = Post;
```
But it works if I import the models in **app.js** (entry file):
```js
const User = require('./models/user');
const Post = require('./models/post');
const Like = require('./models/like');
const Comment = require('./models/comment');
Post.belongsTo(User);
Post.hasMany(Like);
Post.hasMany(Comment);
```
Why is that? I don't want to pollute my entry file w/ the associations, I want to keep them w/ the model definitions. Is there any way I can make it work?

**Comment by papb** [comment]
Hello! If your file is just this:

```js
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: 'database.sqlite',
});
module.exports = sequelize;
```

Then it won't have any models attached indeed. Where are you calling `sequelize.define` (or equivalently, `Model,init({ ... }, { sequelize });`)?

Also, please take a look at our [express-example](https://github.com/sequelize/express-example/tree/master/express-main-example) (recently updated) and see if the way it is organized helps you understand what is going on.

**Comment by msrumon** [comment]
Thanks for the response. No, that's not the only file. That file is responsible to export a sequelize instance. Models are as follows:
```js
const { Model, DataTypes } = require('sequelize');
const bcrypt = require('bcryptjs');
const sequelize = require('../utils/database'); //<= that file
const Post = require('./post');
class User extends Model {}
User.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: { isEmail: true },
    },
    password: {
      type: DataTypes.STRING,
      allowNul: false,
      set(value) {
        bcrypt
          .hash(value, 12)
          .then((hash) => this.setDataValue('password', hash));
      },
    },
  },
  { sequelize }
);
User.hasMany(Post);
module.exports = User;
```
Another one:
```js
const { Model, DataTypes } = require('sequelize');
const sequelize = require('../utils/database'); //<= that file
const User = require('./user');
const Comment = require('./comment'); //<= another model
class Post extends Model {}
Post.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    title: { type: DataTypes.STRING, allowNull: false },
    body: { type: DataTypes.TEXT, allowNull: false },
  },
  { sequelize }
);
Post.belongsTo(User);
Post.hasMany(Comment);
module.exports = Post;
```
The entry file looks something like this:
```js
const path = require('path');
const express = require('express');
const session = require('express-session');
const SequelizeStore = require('connect-session-sequelize')(session.Store);
const app = express();
const mainRoutes = require('./routes/main');
const postRoutes = require('./routes/post');
const db = require('./utils/database'); //<= that file
// const User = require('./models/user');
// const Post = require('./models/post');
// const Like = require('./models/like');
// const Comment = require('./models/comment');
// User.hasMany(Post);
// Post.belongsTo(User);
// Post.hasMany(Like);
// Post.hasMany(Comment);
// Like.belongsTo(User);
// Comment.belongsTo(User);
app.set('view engine', 'pug');
app.set('x-powered-by', false);
app.use(express.static(path.join(__dirname, 'public')));
app.use(
  session({
    store: new SequelizeStore({ db }),
    secret: process.env.SESSION_SECRET || 'secret',
    resave: false,
    saveUninitialized: false,
  })
);
app.use(mainRoutes);
app.use('/posts', postRoutes);
async function start(port) {
  console.log(db.models);
  await db.sync({ alter: true });
  await new Promise((resolve, reject) => {
    app.listen(port, resolve);
  });
  console.log(`Server is up & running on port ${port}...`);
}
start(process.env.PORT || 4444);
```
If I comment in the commented-out lines above, all models get synced. But not w/ the current setup.

**Comment by msrumon** [comment]
# Update:
Currently I have the following models:
```js
const { DataTypes } = require('sequelize');
const sequelize = require('../utils/database');
const User = require('./user');
const Post = require('./post');
const Comment = sequelize.define('comment', {
  text: { type: DataTypes.STRING, allowNull: false },
});
// Comment.belongsTo(User);
// Comment.belongsTo(Post);
module.exports = Comment;
```
```js
const sequelize = require('../utils/database');
const Post = require('./post');
const User = require('./user');
const Like = sequelize.define('like', {});
Post.belongsToMany(User, { through: Like });
User.belongsToMany(Post, { through: Like });
module.exports = Like;
```
```js
const { DataTypes } = require('sequelize');
const sequelize = require('../utils/database');
const User = require('./user');
const Comment = require('./comment');
const Post = sequelize.define('post', {
  title: { type: DataTypes.STRING, allowNull: false },
  body: { type: DataTypes.TEXT, allowNull: false },
});
// Post.belongsTo(User);
Post.hasMany(Comment);
module.exports = Post;
```
```js
const { DataTypes } = require('sequelize');
const bcrypt = require('bcryptjs');
const sequelize = require('../utils/database');
const Post = require('./post');
const User = sequelize.define('user', {
  name: { type: DataTypes.STRING, allowNull: false },
  email: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true,
    validate: { isEmail: true },
  },
  password: { type: DataTypes.STRING, allowNul: false },
});
User.beforeCreate(async (instance) => {
  instance.password = await bcrypt.hash(instance.password, 12);
});
User.hasMany(Post);
module.exports = User;
```
Look at the commented-out lines in 1st (`comment`) and 3rd (`post`) models. I get `${source.name}.${_.lowerFirst(Type.name)} called with something that's not a subclass of Sequelize.Model` error if I comment in those lines. Can you explain what's wrong?

**Comment by msrumon** [comment]
# Update-2:
I placed `console.log` inside all the model files, and found out that the models are being registered in a sequential order.
```js
const { DataTypes } = require('sequelize');
const sequelize = require('../utils/database');
const User = require('./user');
const Post = require('./post');
const Comment = sequelize.define('comment', {
  text: { type: DataTypes.STRING, allowNull: false },
});
console.log('comment:', sequelize.models);
// Comment.belongsTo(User);
// Comment.belongsTo(Post);
module.exports = Comment;
```
```js
const sequelize = require('../utils/database');
const Like = sequelize.define('like', {}, { updatedAt: false });
console.log('like:', sequelize.models);
module.exports = Like;
```
```js
const { DataTypes } = require('sequelize');
const sequelize = require('../utils/database');
const User = require('./user');
const Like = require('./like');
const Comment = require('./comment');
const Post = sequelize.define('post', {
  title: { type: DataTypes.STRING, allowNull: false },
  body: { type: DataTypes.TEXT, allowNull: false },
});
console.log('post:', sequelize.models);
// Post.belongsTo(User);
// Post.belongsToMany(User, { through: Like });
Post.hasMany(Comment);
module.exports = Post;
```
```js
const { DataTypes } = require('sequelize');
const bcrypt = require('bcryptjs');
const sequelize = require('../utils/database');
const Post = require('./post');
const Like = require('./like');
const User = sequelize.define('user', {
  name: { type: DataTypes.STRING, allowNull: false, validate: { isAlpha: true } },
  email: { type: DataTypes.STRING, allowNull: false, unique: true, validate: { isEmail: true } },
  password: { type: DataTypes.STRING, allowNul: false },
});
User.beforeCreate(async (instance) => {
  instance.password = await bcrypt.hash(instance.password, 12);
});
console.log('user:', sequelize.models);
User.hasMany(Post);
User.belongsToMany(Post, { through: Like });
module.exports = User;
```
And the output is:
```
like: { like: like }
comment: { like: like, comment: comment }
post: { like: like, comment: comment, post: post }
user: { like: like, comment: comment, post: post, user: user }
```
**This is why I get `called with something that's not a subclass of Sequelize.Model` error!** Sequelize doesn't find `user` model inside `comment` model. But I AM EXPORTING A WELL-DEFINED MODEL there! Why is it complaining? And why is the models being registered in that way? Isn't it the fact that a model gets registered as soon as I call `sequelize.define()`?

**Comment by papb** [comment]
Hello again! First I will reply to [this comment](https://github.com/sequelize/sequelize/issues/12658#issuecomment-687273973):

Observe the requires you are making in your entry file:

```js
const path = require('path');
const express = require('express');
const session = require('express-session');
const SequelizeStore = require('connect-session-sequelize')(session.Store);
const app = express();
const mainRoutes = require('./routes/main');
const postRoutes = require('./routes/post');
const db = require('./utils/database'); //<= that file
```

Observe that you never require any of your model definitions. That's why nothing is getting synchronized. Even though you have written `.js` files for your models, you're never requiring them, so Node doesn't even run them. That's why it works if you uncomment the following lines:

```js
// const User = require('./models/user');
// const Post = require('./models/post');
// const Like = require('./models/like');
// const Comment = require('./models/comment');
```

**Comment by papb** [comment]
Now replying to your [update](https://github.com/sequelize/sequelize/issues/12658#issuecomment-687322090):

> Look at the commented-out lines in 1st (comment) and 3rd (post) models. I get ${source.name}.${_.lowerFirst(Type.name)} called with something that's not a subclass of Sequelize.Model error if I comment in those lines; also: 2nd (like) model doesn't get synced. Can you explain what's wrong?

What's happening is that you have a require cycle. When a require cycle happens, NodeJS will resolve these cyclic references to an empty object (which will become whatever was exported as soon as the `module.exports =` part of that file is reached. So Sequelize is actually seeing your call to be like `SomeModel.belongsTo({})` and giving that error. Maybe we can detect empty objects and give a better error message such as `Is a require cycle happening?`.

**Comment by papb** [comment]
Now replying to your [update 2](https://github.com/sequelize/sequelize/issues/12658#issuecomment-687555047):



> **This is why I get `called with something that's not a subclass of Sequelize.Model` error!** Sequelize doesn't find `user` model inside `comment` model.

Precisely! :)

> But I AM EXPORTING A WELL-DEFINED MODEL there! Why is it complaining?

Actually you're not, because there is a require cycle. Note that from `./user.js` you require `./post.js`, and vice-versa. Therefore depending on which one NodeJS reaches first, it will actually resolve to an empty object.

> And why is the models being registered in that way? Isn't it the fact that a model gets registered as soon as I call sequelize.define()?

Models indeed get registered as soon as you call `sequelize.define()`, but NodeJS processes your files one at a time, so it will follow some order (the same order in which your requires happen).

**Comment by papb** [comment]
It turns out I might have answered you in [the other comment in express-example](https://github.com/sequelize/express-example/commit/a01fcc77d97c1da5078f3381243411a85d63965f#commitcomment-42061824) as well :grimacing:

**Comment by papb** [comment]
I was about to close this, but I will leave it open as a documentation issue, maybe we can be clearer about this.

Let me know if you need any further help.

**Comment by msrumon** [comment]
Okay, so **require-cycle** is the thing which is happening in my case as per your explanations. I will research about this by myself. Until I find something, thank you so much for your replies. I see why you made that extra step in the example, to avoid this cyclic imports. I also don't like to do that extra step, it looks like unnecessary to me. It makes more sense to me if all the associations should stay with their models. Thanks again. Have a good day!
> I am closing the issue, but it may be needed to reopen.
