### ISSUE TITLE
[proposal] defaultValue is duplicated in model, we'd prefer to store just in db

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize#12662]
### Is your feature request related to a problem? Please describe.
(posted on Slack too, no replies)
Hi,

We store default values in db tables. Some of the columns (JSONB) have more complex defaults.

Sequelize models also store default values (manually or extracted with sequelize-auto)
Therefore, when we update defaults, we have to update 2 places, both db & models.

We'd like to store the default in a single place. If that place is NOT the database, that means we can no longer run a simple INSERT manually. So it has to be the database.

I'd like to propose a way for Sequelize to handle this:
We would no longer set defaultValue in model.
Introduce a new model attribute property, hasDefaultValue. If set to true, those columns would be excluded from INSERTs. That's all. 
The INSERT should use RETURNING *, so that the full model data is set in nodejs after INSERT.

What do you think?

### Describe alternatives/workarounds you've considered

maintain default values in 2 places (some JSONB fields have long, complex defaults)

### Is this feature dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by mariusa** [comment]
Note: if we remove defaults from model and also remove `allowNull: false`, the INSERT works fine with just a few properties set. It doesn't try to insert all properties.
It also returns all fields in model (RETURNING), so the created record has all data that was set by default in db. All good!

Would this be the best way to handle this use case?

**Comment by mariusa** [comment]
ping

**Comment by ephys** [comment]
You don't have to set the `defaultValue` property on your model if you don't want to. I believe it works perfectly well if you only set it on your database - with the exception of the few defaultValues that are handled in JavaScript instead of SQL, like [UUIDV4](https://sequelize.org/docs/v7/other-topics/other-data-types/#built-in-default-values-for-uuid)

**Comment by mariusa** [comment]
Yes, thanks, it works. Need to also remove `allowNull: false`, but I guess that's ok.
