### ISSUE TITLE
How to auto increase primary key with default value?

### ISSUE THREAD

**Issue by hh54188** [sequelize/sequelize#12673]
## Issue Description

In sequelize.js I try to use migration to create a table, here is how I define an id column in my code:

```javascript
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.createTable(tableName, {
      id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        primaryKey: true,
        defaultValue: 100,
```

I want the id column auto increase from 100

However, when I try to run this migration, the terminal tell me:

> ERROR: Invalid default value for 'id'

I find out if I commentted the autoIncrement attribute, it could work. But maybe it cannot auto increase.

How can I let the id column auto increase from a default value?

### StackOverflow / Slack attempts

[Node,js sequelize.js: How to auto increase primary key with default value](https://stackoverflow.com/questions/63779345/node-js-sequelize-js-how-to-auto-increase-primary-key-with-default-value)

### Additional context

No

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by aakashs007** [comment]
Hello @hh54188 , It is already present in the sequelize.

`async function myTest() {
	await sequelize.queryInterface.createTable('User', {
		id: {
			type: DataTypes.INTEGER,
			autoIncrement: true,
			primaryKey: true
		},
		firstName: {
			type: DataTypes.STRING,
			allowNull: false
		}
	}, {
		initialAutoIncrement: 1000
	});
}`

Above code will set an initial value for auto increment.
