### ISSUE TITLE
Question/Issue BeforeQuery hook - changing schema of the query

### ISSUE THREAD

**Issue by karpikpl** [sequelize/sequelize#12670]
## Issue Description

I'm trying to change the schema live in the `beforeQuery' hook but it doesn't seem to be behaving the way I expected.

Here's the code:
```js
    if (!sequelize.hasHook('beforeQuery')) {
        console.log('no hook -- adding new hook');

        sequelize.addHook('beforeQuery', (options, query) => {

            if (query.sequelize.models) {
                for (m in query.sequelize.models) {
                    query.sequelize.models[m]._schema = currentSchema;
                }
            }
            log('Running BEFORE query:', currentSchema);
            console.log('Im in BEFORE query', currentSchema);
        });
    }
```
**Expected behavior**:
Sequelize waits for before hook to execute.

**Actual behavior**:
The change seems to have an effect after 2nd query is executed...
My framework complains that `log` is called after HTTP call completes, which would indicate that hook doesn't wait for the query...

I'll be ok with providing SSCCE if someone confirms that I'm using this feature correctly :)

### StackOverflow / Slack attempts

<haven't tried SO yet - there are issues for `beforeQuery`

### Additional context
n/a

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?
I'd be ok with doing a PR once I confirm the issue, I'm concerned by number of open issues (>900) and PRs (>90) though - are you looking for maintainers?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by pushker-git** [comment]
@karpikpl Did you get any solution here ?  I am facing similar issue

**Comment by karpikpl** [comment]
I don't believe I did, sorry!
