### ISSUE TITLE
db:seed should act the same as db:migrate

### ISSUE THREAD

**Issue by efiShtain** [sequelize/sequelize#12674]
## Feature Description
db:seed should act like db:migrate

### Is your feature request related to a problem? Please describe.

When I run db:seed, I expect it to act as db:migrate, meaning it should run all the seeds that did not run until now.
In practice, if I run db:seed it does nothing if I don't provide a specific seed. db:seed:all runs all the seeds, but if I run it again by mistake, or in an automated script, it will run all seeds again and duplicate my database or fail on unique constraints, making it kind of useless

### Describe the solution you'd like
db:seed should act just like db:migrate. Handle seeds that ran before in the database. 
In order to save current behaviour, a --force/rerun (any other option) flag can be added so it won't check the database before running

A clear and concise description of what you want to happen. How can the requested feature be used to approach the problem it's supposed to solve?

```js
// If applicable, add a code snippet showing how your feature would be used in a real use-case
```

### Why should this be in Sequelize

It is already part of Sequelize, it is just kind of useless in the way it is

### Describe alternatives/workarounds you've considered

An alternative is just using migrations instead of seeds. That's a valid option, and in case it is the only options, seeds might be removed from Sequelize. 

### Is this feature dialect-specific?

- [X ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by PandyaSmit** [comment]
Just add seederStorage option in your config file and sequelize will maintain a table for already executed seeders.
