### ISSUE TITLE
sync with alter fails if new column has comment

### ISSUE THREAD

**Issue by yann-h** [sequelize/sequelize#12688]
### What are you doing?

I'm adding a colum to a model, then using ```Sequelize.sync({ alter : true})``` to have the database automatically modified.

### What do you expect to happen?

The new column should be created.

### What is actually happening?

An error is thrown ```error: column "<column>" of relation "<table>" does not exist```.

The problem is due to the addition of a ```comment``` property on the model column declaration.

The Sequelize synchronization executes a ```CREATE TABLE IF NOT EXISTS "public"."<table>"``` request first, then a ```COMMENT ON COLUMN "public"."<table>"."<column>"```. As the new column does not exist yet, the request fails and the alteration is not executed.

As a workaround, removing the ```comment``` from the model column declaration solved the problem.

### Additional context

N/A

### Environment

- Sequelize version: 5.22.3, 6.3.5
- Node.js version: 12.16.3
- Operating System: Mac OS Catalina
- If TypeScript related: TypeScript version: 3.9.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using Postgresql, with connector library version 7.18.2 and database version 11

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by RaulAlcaraz** [comment]
the same with version 6
