### ISSUE TITLE
Database cleaning

### ISSUE THREAD

**Issue by wambugucoder** [sequelize/sequelize#12686]
When cleaning my database, the primary key doesnt not reset  back to 1 .
Any help would be highly appreciated

**Comment by Spekpannenkoek** [comment]
Deleting records doesn't 'clear up' auto incremented ID counts in any database that I know of. It's not something Sequelize will do for you either. 

In MySQL you can reset the auto increment by just [setting it to 1](https://stackoverflow.com/questions/8923114/how-to-reset-auto-increment-in-mysql). MySQL will make sure the number won't overlap with any existing records.

Before:

```
id | name
-- | ----
 1 | Foo
 2 | Bar
 3 | Baz
# The next ID will be 4.
```

After deletion:

```
id | name
-- | ----
 1 | Foo
 2 | Bar
# The next ID will be 4
```

After resetting auto increment to 1:

```
id | name
-- | ----
 1 | Foo
 2 | Bar
 # The next ID will be 3 (not 1 or 2: those already exist).
```

You can run a query manually with [`sequelize.query`](https://sequelize.org/master/manual/raw-queries.html).

```
await sequelize.query("ALTER TABLE tablename AUTO_INCREMENT = 1");
```

Other databases (Postgres, SQLite) do this differently.

**Comment by SqrtMinusOne** [comment]
Here is how it's done it in Postgres:
```sql
SELECT setval('"table_id_seq"', 1);
```

However that you shouldn't rely on any consistency within the numbering of autoincremented primary keys, e.g. you can't count the number of elements in a table with `MAX(id)`. For example, if an element is deleted, its key will never be reused.
