### ISSUE TITLE
TypeScript issue with nesting Sequelize.or in Sequelize.and (and vice-versa)

### ISSUE THREAD

**Issue by yjwong** [sequelize/sequelize#12682]
## Issue Description

When nesting `Sequelize.or()` within `Sequelize.and()`, an error is reported:

```
Argument of type 'OrOperator' is not assignable to parameter of type 'WhereAttributeHash | Where | WhereOperators'.
  Type 'OrOperator' has no properties in common with type 'WhereOperators'
```

### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/yjwong/sequelize-sscce/tree/patch-1 

### What do you expect to happen?

This should be an acceptable usage.

It seems that the `and` and `or` declaration is too restrictive?
https://github.com/sequelize/sequelize/blob/933b3f62640e218587d34ec141029b2416ff7845/types/lib/sequelize.d.ts#L1455

Should it just simply be `WhereOptions`?

```ts
export function and(...args: WhereOptions[]): AndOperator<any>; 
```

### What is actually happening?

TypeScript produces this error:

```
Argument of type 'OrOperator' is not assignable to parameter of type 'WhereAttributeHash | Where | WhereOperators'.
  Type 'OrOperator' has no properties in common with type 'WhereOperators'
```

### Environment

- Sequelize version: 5.22.3 and 6.3.5 
- Node.js version: 10.22.0 
- Operating System: Ubuntu 20.04.1 LTS
- If TypeScript related: TypeScript version: 3.8.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
This is still an issue 
![image](https://user-images.githubusercontent.com/1280915/140039459-3c7b60b3-1c88-4d49-8b13-b909e6175a85.png)

**Comment by ephys** [comment]
Not stale :)

**Comment by ephys** [comment]
I believe https://github.com/sequelize/sequelize/pull/14368 fixed this
