### ISSUE TITLE
filter with include and limit causes missing FROM-clause entry on included table

### ISSUE THREAD

**Issue by echoi92** [sequelize/sequelize#12681]
## Issue Description
I'm implementing a general keyword search on Post that will filter by Post's column as well as its associated table's columns (Category)
 
Post belongsTo Category.
Post hasMany Like. 

When I try this filter by combining where.$or, limit/offset, and order, i get an error `missing FROM-clause entry for table "category"`.

I think it's because sequelize seems to only apply outer join of the included models on the main query, and not the inner query used for filter/limit. I'm not 100% sure if this is a bug but also could not find a solution in the doc.

### What are you doing?
Below are by sequelize query and the logged sql.

query
```
const { rows: posts, count } = await Post
    .findAndCountAll({
      where: {
        $or: [ 
          { title: { $iLike: `%${searchKeyWord}%` } },
          { '$category.label$': { $iLike: `%${searchKeyword}%` } },
        ],
      },
      include: [
        { model: Category },
        // Like is not used in the where clause above, but this is required to reproduce the issue.
        { model: Like },
      ],
      limit: 25,
      offset: 0,
      order: [['id', 'desc'],
    })
   
```

logged sql. commented line is added by me, not by sequelize
```
SELECT          "post".*, 
                "likes"."id"           AS "likes.id", 
                "likes"."userId"       AS "likes.userId", 
                "likes"."postId"       AS "likes.postId", 
                "likes"."createdAt"    AS "likes.createdAt", 
                "likes"."updatedAt"    AS "likes.updatedAt", 
                "likes"."deletedAt"    AS "likes.deletedAt", 
                "category"."id"        AS "category.id", 
                "category"."label"     AS "category.label", 
                "category"."createdAt" AS "category.createdAt", 
                "category"."updatedAt" AS "category.updatedAt", 
                "category"."deletedAt" AS "category.deletedAt" 
FROM            ( 
                         SELECT   "post"."id", 
                                  "post"."title", 
                                  "post"."content", 
                                  "post"."createdAt", 
                                  "post"."updatedAt" 
                         FROM     "posts" AS "post" 
// adding left outer join for category here seems to solve the problem. ex)
//                       LEFT OUTER JOIN "categories" AS "category" 
//                       ON              "post"."categoryId" = "category"."id" 
                         WHERE    ( 
                                           "post"."title" ilike '%english%' 
                                  OR       "category"."label" ilike '%english%') 
                         ORDER BY "post"."id" DESC limit 25 offset 0) AS "post" 
LEFT OUTER JOIN "likes"                                               AS "likes" 
ON              "post"."id" = "likes"."postId" 
LEFT OUTER JOIN "categories" AS "category" 
ON              "post"."categoryId" = "category"."id" 
ORDER BY        "post"."id" DESC;
```

### What do you expect to happen?

I expect the first 25 Posts that match searchKeyword against post.title OR category.label

### What is actually happening?

`SequelizeDatabaseError: missing FROM-clause entry for table "category"`

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 10.22.0 
- Operating System: Mac Catalina 10.15.6

### How does this problem relate to dialects?

- [v] I think this problem happens regardless of the dialect, but i'm using postgresql 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [v] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by justraman** [comment]
try adding subQuery:false to your findAndCountAll
