### ISSUE TITLE
Sequelize ignores different includes of the same model

### ISSUE THREAD

**Issue by echoi92** [sequelize/sequelize#12684]
## Issue Description
Sequelize seems to ignore different includes of the same model even if they represent a different join 
ex) required: true for inner join + required: false for outer.

### What are you doing?
```
const { rows: posts, count } = await PG.Post
    .findAndCountAll({
       where: {
         $or: [ 
           { title: { $iLike: `%${searchKeyWord}%` } },
           { '$category.label$': { $iLike: `%${searchKeyword}%` } },
         ],
       },
      include: [
          // inner join. needed for where clause and limit/offset
          {
            model: PG.Category,
            required: true,
          },
         // outer join. needed for sorting
          {
            model: PG.Category,
            required: false,
          },
      ],
      order: [['category', 'updatedAt', 'desc']],
      limit: 25,
      offset: 0, 
  });
```

### What do you expect to happen?
Category to be in inner join and outer join

### What is actually happening?

category is only part of outer join, so applying where results in `SequelizeDatabaseError: missing FROM-clause entry for table "category"`

### Environment

Sequelize version: 6.3.5
Node.js version: 10.22.0
Operating System: Mac Catalina 10.15.6

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by michael-d-t** [comment]
@echoi92 Have you tried with Alias'?

`
              {
                model: PG.Category,
                as: 'sortCategory',
                required: false,
              },
`

**Comment by echoi92** [comment]
@michael-d-t 
Do you mean add each model association twice (two foreign keys: categoryId, sortCategoryId) and use one of them for sorting and another for filtering? 

That approach will create a lot of duplication in the code base tho. I would have to duplicate every single association and make sure the two foreign keys are synced.
