### ISSUE TITLE
How to update the instance from the instnace method?

### ISSUE THREAD

**Issue by kevinmamaqi** [sequelize/sequelize#12692]
## Issue Description
I declared an instance method to update the password of my user. It is as follows:
```

Users.prototype.validatePassword = (password) => {
		try {
			return bcrypt.compare(password, this.password); // Why this.password is undefined.?
		} catch (error) {
			throw new Error(error);
		}
	};

```
### What was unclear/insufficient/not covered in the documentation
How to properly declare instance methods and how to access the current instance properties from them when using define.

### If possible: Provide some suggestion on how we can enhance the docs
Clear example in which it is possible to declare instance methods using Sequelize.define.

### Additional context
Full CODE:
```
const bcrypt = require("bcryptjs");
module.exports = function (sequelize, Sequelize) {
	const Users = sequelize.define(
		"Users",
		{
			password: {
				type: Sequelize.TEXT,
				allowNull: true,
			},
		},
		{
			timestamps: false,
			tableName: "Users",
		}
	);
	Users.prototype.validatePassword = (password, curPWD) => {
		try {
			return bcrypt.compare(password, curPWD);
		} catch (error) {
			throw new Error(error);
		}
	};
	return Users;
};

```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [X] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
[Arrow functions have no `this`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

> An arrow function expression is a compact alternative to a traditional function expression, but is limited and can't be used in all situations.
> ...
> Does not have its own bindings to this or super, and should not be used as methods.

Use:

```
Users.prototype.validatePassword = function (password) {
	// ...
};
```
