### ISSUE TITLE
return of sequelize.define not an instanceof Model

### ISSUE THREAD

**Issue by jpgilchrist** [sequelize/sequelize#12699]
## Issue Description

I need to check if an argument type is of type `Model`, but `instanceof` is returning false.

### What are you doing?

```js
const {Sequelize, Model, DataTypes} = require("sequelize");
const sequelize = require("../index").getConnection();

const Item = sequelize.define('Item', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true
    },
    name: {
        type: DataTypes.STRING,
        allowNull: false
    }
})

Item.associate = models => {
 // associations...
}

const isSequelizeModel = Item instanceof Model; // this is returning false

module.exports = Item
```

### What do you expect to happen?

It seemingly should return true

### What is actually happening?

It is returning false

### Environment

- Sequelize version: 6.3.4
- Node.js version: 12.18.3
- Operating System: Win 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jpgilchrist** [comment]
After some testing, this is invalid.

**Comment by nitinshyamk** [comment]
Any chance you could clarify what you did to fix @jpgilchrist ? I'm running into an identical issue which is blocking me implementing other things like associations as a result.

**Comment by jpgilchrist** [comment]
I'm sorry, but no I don't recall. I actually ended up going with a more basic approach with knexjs
