### ISSUE TITLE
useMaster true by default

### ISSUE THREAD

**Issue by arbazsiddiqui** [sequelize/sequelize#12694]
## Feature Description
Sequelize allows us to create read and write replicas, however after doing so ALL read queries are directed to read replicas unless given an option `useMaster: true`. The idea is to send only few read queries to slave nodes on DB and not all. So do we have a global setting to make `useMaster: true` by default on all queries and the override it with `false` when we want to send the query to read replica.

### Is this feature dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by dmattia** [comment]
Why was this closed? This seems like a useful feature

**Comment by arbazsiddiqui** [comment]
Hey @dmattia 
I closed the issue as I found a way to do this.
You can pass in global defaults for query while initialising Sequelize in options :
```
const sequelize = new Sequelize(
  database,
  username,
  password,
  { query: { useMaster: true } }
);
```
[Link](https://github.com/sequelize/sequelize/blob/febc083adee2cd3e6f24b18a556acdc4c4f50f96/src/sequelize.js#L138)

Then for the queries you want to send to slaves instead of master you can pass `useMaster` as `false`

```
const users = await User.findAll({
  where: {...},
  ...
  useMaster: false
});
```
