### ISSUE TITLE
Sequelize is not working in Heroku, but works in local

### ISSUE THREAD

**Issue by vulongc3** [sequelize/sequelize#12715]
I use **Sequelize** to connect to my **Amazon RDS SQL Server**. It's working good, without any problem when I run app in local by using **nodemon**. But when I deploy to **Heroku**, It always throws ```AccessDeniedError [SequelizeAccessDeniedError]: Login failed for user 'myuser'```  

**node version**
>```
>PS C:\Windows\system32> node -v
>v14.3.0
>```

**package.json**
>```
>{
>    "dependencies": {
>        ...
>        "sequelize": "^6.3.5",
>        "tedious": "^9.2.1"
>        ...
>    }
>}
>```  

**database.js**
>```
>const { DB, USER, PWD, HOST, DB_INSTANCE } = process.env;
>    
>return new Sequelize(DB, USER, PWD, {
>    host: HOST,
>    dialect: 'mssql',
>    dialectOptions: {
>        instanceName: DB_INSTANCE,
>        options: {
>            validateBulkLoadParameters: false
>        }
>    }
>});
>```

**Comment by adderpositive** [comment]
Hey, I don't know if is the same problem, but my problem is, that included tables don't have same names. 
More here: https://stackoverflow.com/questions/65772179/sequelize-different-included-table-names-between-dev-build-mode
