### ISSUE TITLE
TS typing seems to be broken when using a query with `include: []` option

### ISSUE THREAD

**Issue by robertrossmann** [sequelize/sequelize#12716]
## Issue Description

I cannot seem to get the typing right when trying to find a record and resolve an association, code samples included.

### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/117

### What do you expect to happen?

TypeScript happily compiles

### What is actually happening?

TypeScript reports the following issue placed at the `include` object key:

```
No overload matches this call.
  Overload 1 of 2, '(this: ModelStatic<User>, options: NonNullFindOptions<IUserAttributes>): Promise<User>', gave the following error.
    Type 'typeof Company' is not assignable to type 'Includeable'.
      Type 'typeof Company' is not assignable to type 'typeof Model'.
        Construct signature return types 'Company' and 'Model<TModelAttributes, TCreationAttributes>' are incompatible.
          The types of '_attributes' are incompatible between these types.
            Type 'ICompanyAttributes' is not assignable to type 'TModelAttributes'.
              'ICompanyAttributes' is assignable to the constraint of type 'TModelAttributes', but 'TModelAttributes' could be instantiated with a different subtype of constraint '{}'.
  Overload 2 of 2, '(this: ModelStatic<User>, options?: FindOptions<IUserAttributes>): Promise<User>', gave the following error.
    Type 'typeof Company' is not assignable to type 'Includeable'.
      Type 'typeof Company' is not assignable to type 'typeof Model'.
```

### Environment

- Sequelize version: 6.3.5
- Node.js version: 14.7
- Operating System: macOS 10.15.6
- If TypeScript related: TypeScript version: 3.9

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by luis-carlos-campos** [comment]
I've got the same error here.

**Comment by cwyu57** [comment]
i've got the same issue.
thanks to @luis-carlos-campos solution
but using association in include options seems to not having the ability of include model using alias ( as 'xxx' )
is there any update or fix about it?

**Comment by JeongJuhyeon** [comment]
Any updates?

**Comment by Daspy11** [comment]
This one's killing me, could really use a fix to this.

**Comment by adhimos** [comment]
Same issue, quite a pain.

As a temporary fix, i am casting to <typeof Model>
 ` await Hotel.findAll({
      include: [{
        model: <typeof Model> HotelRoom
      }]
    })`

**Comment by Daspy11** [comment]
I'm trying to use it with creation and typescript is just not having it. 

```
Customer.create(
      {
        type: "individual",
        AppId: res.locals.AppId,
        status: "active",
        environment: res.locals.environment,
        individual: {
          AppId: res.locals.AppId,
          firstName: req.body.firstName,
          middleName: req.body.middleName,
          lastName: req.body.lastName,
          nickName: req.body.nickName,
          suffix: req.body.suffix,
          nationality: req.body.nationality,
          ssn: req.body.ssn,
          dateOfBirth: req.body.dateOfBirth,
          address: {
            line1: req.body.address.line1,
            line2: req.body.address.line2,
            city: req.body.address.city,
            region: req.body.address.region,
            country: req.body.address.country,
            postcode: req.body.address.postcode,
          },
          email: req.body.email,
          phone: {
            country: req.body.phone.country,
            number: req.body..phone.number,
          },
          environment: req.body.environment,
        }
      },
      {
        include: [
          {
            association: Customer.associations.individual,
            as: "individual",
            include: [
              {
                association: Individual.associations.phone,
                as: "phone",
              },
              {
                association: Individual.associations.address,
                as: "address",
              },
            ],
          },
        ],
      },
    );
```

This is a pretty fundamental problem with creating associated elements, and I don't know enough about how sequelize works under the hood to know if there's another way to do it without running multiple queries which I'm trying to avoid.

**Comment by Daspy11** [comment]
**Type assertion workaround for model creation for anyone arriving here after me:**

I added a type assertion to the creation params of the code pasted above like so:

```
Customer.create(
      <ICustomer & { individual: IIndividual & { phone: ICreatePhone; address: IAddress } }>{
        type: "individual",
        AppId: res.locals.AppId,
        status: "active",
...etc
```

after doing this, Typescript no longer yells at me. It's hacky and suboptimal, but it works.

**Comment by robertrossmann** [comment]
I believe this is still an issue. 🤔

**Comment by robertrossmann** [comment]
Still relevant. ✅

**Comment by robertrossmann** [comment]
Still relevant. ✅

**Comment by ephys** [comment]
Is this still an issue with the latest v6? We had a few TS changes since this was first opened.

**Comment by vanthome** [comment]
Good point, will need to check it as I'm using an older fork. Wil let you kow.

**Comment by ephys** [comment]
Just tested with the latest sequelize and it worked without type errors:

![image](https://user-images.githubusercontent.com/1280915/149329926-a46c810f-e557-4cab-bcea-5ef1aa34ff05.png)

I think it was fixed by https://github.com/sequelize/sequelize/pull/13890

I'll close but let us know if it turned out to still be an issue

**Comment by robertrossmann** [comment]
Thanks, I'll take a look at this once we get the time for an upgrade attempt. Awesome! ❤️🎉
