### ISSUE TITLE
Cannot read property 'name' of undefined sequelize in lambda

### ISSUE THREAD

**Issue by Vlad1slavIP74** [sequelize/sequelize#12710]
I am using such kind model [initializing](https://github.com/Vlad1slavIP74/SequelizeBugReport)
And get error when work with 
`await sequelize.transaction(async () => {
      try {
        const user = await User.findAll({
             include: [
                 {
                      association: User.MusicInstruments
                }
             ]
         })
       } catch (error) {
           console.log(error)
           throw error
       }
          })`

Sequelize version 6.0.0
NodeJs version 12
dialect: "postgres"

**Comment by papb** [comment]
Please take a look if the guide in #12642 helps you, and let me know
