### ISSUE TITLE
Sync force: true does not do what I understand it to do (force db recreation)

### ISSUE THREAD

**Issue by togakangaroo** [sequelize/sequelize#12714]
### What was unclear/insufficient/not covered in the documentation

The documentation on the `force` parameter of the [sync method](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-sync) states

> If force is true, each Model will run DROP TABLE IF EXISTS, before it tries to create its own table

I take that to mean that every table will be dropped and recreated every time this runs. I am doing this with an in-memory sqlite db in my tests and am seeing that this is not the case. While everything happens as expected on the first test run, on the second nothing is dropped nor created.

I understand that this isn't technically incorrect as it hinges on the definition of the word "sync". The documentation says this method does

> Sync all defined models to the DB.

However, there is no further discussion that I'm able to find on what exactly the "sync" operation entails and as I was confused by this, I assume others are as well.

### If possible: Provide some suggestion on how we can enhance the docs

1. More details on what exactly `sync` does. Is there metadata about the current state of the model or db stored somewhere and compared against?
2. As others like me might be coming to the `force` parameter with a similar use case (wanting to recreate the db entirely for tests every time), can you link to an FAQ o something on how to accomplish that? Even if its just a "here's how you truncate all tables instead", that would also work.

### Is this issue dialect-specific?

Yes and no. The core docs issue isn't dialect specific, the context within which this is most likely to be relevant is sqlite

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

(I do believe this is a quick fix for someone else versus a lot of trawling through source for me however)

**Comment by togakangaroo** [comment]
By the way [this StackOverflow question I posted](https://stackoverflow.com/questions/63985693/sequelize-in-memory-sqlite-tests-isolated-db) is related

**Comment by fzn0x** [comment]
Since you mention everything was fine on the first run, I assume there is something wrong within the code, not the `sync: method` itself,  can you try as well without using the test library code? if it returns the same behavior, we will surely take this issue much further :)

**Comment by togakangaroo** [comment]
@fzn0x I'm sorry but you're asking me to try doing something (I'm not sure what) to code from 18 months and 2 jobs ago I can't do that 😄 

I believe I described the issue well here though. I never said database creation didn't work - it does! What I'm saying is that it doesn't *sync* as described or as the word "sync" is usually understood in this context. The request is specifically to update the documentation with what exactly the `sync` operation does and ideally to create an FAQ for how to drop and recreate the database entirely every time (as you would want in a test suite)

**Comment by fzn0x** [comment]
> @fzn0x I'm sorry but you're asking me to try doing something (I'm not sure what) to code from 18 months and 2 jobs ago I can't do that 😄 
> 
> I believe I described the issue well here though. I never said database creation didn't work - it does! What I'm saying is that it doesn't *sync* as described or as the word "sync" is usually understood in this context. The request is specifically to update the documentation with what exactly the `sync` operation does and ideally to create an FAQ for how to drop and recreate the database entirely every time (as you would want in a test suite)

Nevermind. I will move the discussion to other maintainers to improve the documentation about the sync option including adding example for recreating a database on tests if applicable. Since it's could be the same means with https://github.com/sequelize/sequelize/issues/537 PR, I will close this issue.
