### ISSUE TITLE
select based on reference table node.js sequelize

### ISSUE THREAD

**Issue by JonasGroenbek** [sequelize/sequelize#12723]
### What was unclear/insufficient/not covered in the documentation

I am specifically referring to the example in the bottom of the Belongs-To-Many associations section. Where it performs a select based on a reference table.  https://sequelize.org/v3/docs/associations/ 

Versions 
```js
        "sequelize": "^6.3.5",
        "pg": "^8.3.3",
        "pg-hstore": "^2.3.3",
```

So I had some difficulties performing the operation
```sql
SELECT *
FROM clothes c
INNER JOIN reservations r ON c.reservation_id = r.id
WHERE r.user_id = { userId };
```

So I tried to apply the example given in your documentation

```js
Clothes.findAll({
    include: [
        {
            model: Reservations,
            through: {
                attributes: [],
                where: { user_id: id },
            },
        },
    ],
})
```

and I am getting this ``error : Error: TypeError: Cannot read property 'getTableName' of undefined↵``. I have confirmed that the association works as expected in pgadmin, and that the columns referenced is named correctly
```js
    class Clothes extends Model {
        static associate(models) {
            const { Reservations, Clothes } = models
            Clothes.belongsTo(Reservations, {
                foreignKey: {
                    allowNull: false,
                    name: 'reservation_id',
                },
                targetKey: 'id',
            })
        }
    }
    Clothes.init(
    ...

class Reservations extends Model {
        static associate(models) {
            const { Users, Reservations, Stores, Clothes } = models
            Reservations.belongsTo(Users, {
                allowNull: false,
                foreignKey: {
                    name: 'user_id',
                    allowNull: false,
                },
                targetKey: 'id',
            })
            ...
```
important note I do not get any errors when excluding the where clause

I ended up using 
```js 
sequelize.query(
    'SELECT *\n' +
    'FROM clothes c\n' +
    'INNER JOIN reservations r ON c.reservation_id = r.id\n' +
    'WHERE r.user_id = :userId;',
    {
        replacements: { userId: id },
        type: QueryTypes.SELECT,
    }
)
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

No

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by apteles** [comment]
Hi @JonasGroenbek. Based on the version of sequelize are you using, I suggest you see the follow [documentation](https://sequelize.org/master/manual/assocs.html).

I have a simple example that I think that can be used like reference:
https://github.com/apteles/gobarber-oministack/blob/master/backend/src/app/models/Appointment.js

Can you see if is usefull and report us?
