### ISSUE TITLE
DataTypes.VIRTUAL produces SQL syntax error during migration

### ISSUE THREAD

**Issue by ahansson** [sequelize/sequelize#12739]
# Issue Description

Model with datatype Virtual and a get method copied directly from the Sequelize manual gives SQL syntax error when running db:migration with sequelize-cli. Any other possible errors in the file has been ruled out by trial.

MySQL 5.7.31 and Sequelize ^6.3.5 with Express 4.17.1 and mysql2 2.1.0.

### What are you doing?

20200101010101-create-user.js (migrations file)

```js
'use strict'
const { DataTypes } = require('sequelize')

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.createTable('users', {
      id: {
        type: DataTypes.UUID,
        defaultValue: Sequelize.UUIDV4,
        primaryKey: true,
        allowNull: false, // constraint on mysql
        unique: true,// constraint on mysql
        validate: {
          isUUID: {
            args: 4,
            msg: 'User ID must be a UUID4 string.'
          }
        }
      },
      firstName: {
        type: DataTypes.STRING,
        required: true,
        allowNull: false,
        notEmpty: true,
        validate: {
          len: {
            args: [2, 90],
            msg: 'The first name must contain between 2 and 90 characters.'
          }
        }
      },
      lastName: {
        type: DataTypes.STRING,
        required: true,
        allowNull: false,
        notEmpty: true,
        validate: {
          len: {
            args: [2, 90],
            msg: 'The last name must contain between 2 and 90 characters.'
          }
        }
      },
     // Code that breaks the migration process:
      fullName: {
        type: DataTypes.VIRTUAL,
        get() {
          return `${this.firstName} ${this.lastName}`;
        }
      },
     // End code that breaks migration process
      email: {
        type: DataTypes.STRING,
        unique: true,
        required: true,
        allowNull: false,
        validate: {
          isEmail: {
            args: [true],
            msg: 'Incorrect email format'
          },
          isLowercase: {
            args: [true],
            msg: 'Email address must be lowercase'
          }, 
          len: {
            args: [2, 50],
            msg: 'The email address must have between 2 and 50 characters',
          },
          notEmpty: {
            args: [true], 
            msg: 'The email field can\'t be empty.'
          },
        }
      },
      password: {
        type: DataTypes.STRING,
        required: true,
        allowNull: false,
        validate: {
          len: {
            args: [8, 99],
            msg: 'Your password must contain at least 8 characters.',
          },
          notEmpty: {
            args: [true],
            msg: 'The password field cannot be empty.'
          }
        }
      },
      resetPasswordToken: {
        type: DataTypes.STRING
      },
      resetPasswordExpire: {
        type: DataTypes.INTEGER
      },
      createdAt: {
        type: DataTypes.DATE,
        required: true,
        allowNull: false
      },
      updatedAt: {
        type: DataTypes.DATE,
        required: true,
        allowNull: false
      },
      deletedAt: {
        type: DataTypes.DATE
      }
    },
    {
      paranoid: true,
      tableName: 'users'
    })
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.dropTable('users');
  }
};
```

### What do you expect to happen?

Run `sequelize-cli db:migrate` without any errors.

### What is actually happening?

Console output:

```
ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VIRTUAL, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL,' at line 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
etc.
```
If the `fullName` field is removed from the model the migration runs successfully. The get() method is copied 1:1 from the example [in the manual](https://sequelize.org/master/manual/getters-setters-virtuals.html#virtual-fields).

### Environment

- Sequelize version: ^6.3.5
- Node.js version: 12.18.3
- Operating System: MacOS
- MySQL 5.7.31
- Express 4.17.1
- npm package mysql2 version 2.1.0.

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X ] I don't know, I was using MySQL, with connector library version 2.1.0 and database version 5.7.31

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X ] No, I wouldn't even know how to start (although I have plenty of time).

**Comment by apteles** [comment]
Hi @ahansson. I will try help you solve this problem. 
I belive that Virtual DataTypes are defined in Model level as you can see in [documentation](https://sequelize.org/master/manual/getters-setters-virtuals.html).

For your objective I think that you should do something like this:

```js

const { DataTypes } = require("sequelize");

const User = sequelize.define('user', {
  firstName: DataTypes.TEXT,
  lastName: DataTypes.TEXT,
  fullName: {
    type: DataTypes.VIRTUAL, // HERE DEFINED THE VIRTUAL DATA TYPE
    get() {
      return `${this.firstName} ${this.lastName}`;
    },
    set(value) {
      throw new Error('Do not try to set the `fullName` value!');
    }
  }
});
```
I realy hope that's help you. That's is my first trying to contribute with this project.

**Comment by ahansson** [comment]
@apteles Thank you for your helping out! 

Yes, my model is basically like just like your suggestion. 

The seeder files usually contain a 1:1 copy of the model fields, so I thought they could include virtual fields, too. The easiest to maintain and most logical would be that models and seeders could be 1:1 without the need to edit out certain lines from one of them. That way you could more easily automate the generation of seeder files.

At the model level the DataTypes.VIRTUAL work fine. If the virtual fields from the models are never supposed to be included in the seeders, the documentation seem to lack this information and it would be nice if the Sequelize team could mention this (or better: automaticsally exclude virtual fields from the query altogether). I'll leave this open in case in is interesting to come up with a solution for it.

My model (simplified) for the record:

```
const User = db.define('users', {
  id: {
    type: DataTypes.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true,
    allowNull: false,
    unique: true,
    validate: {
      isUUID: {
        args: 4,
        msg: 'User ID must be a UUID4 string.'
      }
    }
  },
  firstName: {
    type: DataTypes.STRING,
    required: true,
    allowNull: false,
    notEmpty: true,
    validate: {
      len: {
        args: [2, 90],
        msg: 'The first name must contain between 2 and 90 characters.'
      }
    }
  },
  lastName: {
    type: DataTypes.STRING,
    required: true,
    allowNull: false,
    notEmpty: true,
    validate: {
      len: {
        args: [2, 90],
        msg: 'The last name must contain between 2 and 90 characters.'
      }
    }
  },
  fullName: {
     type: DataTypes.VIRTUAL,
     get() {
       return `${this.firstName} ${this.lastName}`;
    }
  },
},
{
  paranoid: true,
 })

module.exports = User
```
