### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by YoannBuzenet** [sequelize/sequelize#12733]
Hello there,

I love Sequelize and I'm using it for my projects on Node. I'm quite a noob but I love coding.

I searched for quite a long time how to use my models methods these lasts days, and searched a lot on Internet, stackoverflow included, to find how to use a model. I couldn't find it.

After asking on a Node slack I finally got the answer which was very simple : I just had to import `db` from models/index.js.

However, I found a bit frustrating that an info so useful was so hard to find. A lot of examples show how to use User model for example, but not how to get it. I wanted to know if you could add some lines about that matter in the documentation ? It could be [here](https://sequelize.org/master/manual/model-querying-basics.html), at the beginning of the page, something like : 

_To use models, you can importe db object from models/index.js. It holds all your models if you did set them up in /models folder._

I think it could help a lot. I know it's a very simple information and maybe people should look more before asking, but I thought it could be a plus for some beginners.

Anyway thank you for this amazing work, I'll continue to use it.

Bests,
Yoann

**Comment by papb** [comment]
Was the `models/index.js` file generated via Sequelize CLI? Or in another way? Did you create everything from scratch or you started to work on already existing code?

**Comment by YoannBuzenet** [comment]
Yes it was generated from the Sequelize CLI - I generated everything from scratch on a new project.
