### ISSUE TITLE
removeColumn on sqlite removes foreign key constraints from table

### ISSUE THREAD

**Issue by martineso** [sequelize/sequelize#12741]
## Issue Description
When using Sequelize along with an sqlite db to remove a column via `queryInterface.removeColumn` the foreign key constraints from the table are removed. 

### What are you doing?
I am doing a migration and want to remove a column from a table. When doing so, the result table does not have any foreign key constraints which were put on the original table.

Given the schema below
```sql
CREATE TABLE IF NOT EXISTS `User` (
  `id` UUID PRIMARY KEY, 
  `name`  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Actor` (
  `id` UUID PRIMARY KEY, 
  `name` VARCHAR(255) NOT NULL, 
  `userId` UUID NOT NULL REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
```
Say I am doing a migration to remove the `name` column from **Actor** schema as it is redundant

```js

 function up(queryInterface, Sequelize) {
    return queryInterface.removeColumn('Actor', 'name');
}

```

### What do you expect to happen?

It should keep the foreign key constraint on the **Actor** table.

### What is actually happening?

The foreign key constraints are removed from the **Actor** table and there is no reference to the **User** table after this query is done.

### Additional context

I have looked through the source code of Sequelize for the sqlite driver and mainly at the `query-generator.js` [(line)](https://github.com/sequelize/sequelize/blob/febc083adee2cd3e6f24b18a556acdc4c4f50f96/src/dialects/sqlite/query-generator.js#L376) where it seems that the approach taken is to create a backup table and then recreate the original one without the aforementioned column. This is fine however there is one thing missing and that is recreating the original table does not keep any foreign key constraints as mentioned in the sqlite docs [here](https://sqlite.org/lang_altertable.html). This is a major problem but can be fixed without too much hassle. There is another big issue with the current approach - since foreign key constraints are not disabled before starting the process for removing a column, when the table is dropped, all foreign key constraints with ON DELETE CASCADE will delete records in the referenced table. This is a major issue which I am facing right now.

### Environment

- Sequelize version: 5.19.1 
- Node.js version: v12.18.2 
- Operating System: Ubuntu 20.04.1 LTS
### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ x ] I think this problem happens only for the following dialect(s): sqlite
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

I most likely can fix this issue and send a pull request but I am not sure what is the exact process or how long it will take to be reviewed.

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ x ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by martineso** [comment]
I have a solution working, just need to get it working with the sequelize source because at the moment I am working around it. It is however very close to how it would be implemented in `queryInterface.removeColumn` method.

**Comment by Marco-Veio** [comment]
I'm having the same issue. Also, I noticed that it also removes the "not null", "auto increment" and "unique" attributes.

**Comment by ephys** [comment]
@Marco-Veio on which version of Sequelize are you?

**Comment by Marco-Veio** [comment]
@ephys The dialect I'm using is sqlite.
I tried with these 2 versions:
 - Sequelize CLI [Node: 16.13.0, CLI: 6.3.0, ORM: 6.9.0]
 - Sequelize CLI [Node: 16.13.0, CLI: 6.3.0, ORM: 6.13.0]

Btw, the attributes I mentioned are only removed from the id column, maybe because it's the primary key (not sure).

**Comment by martineso** [comment]
> I'm having the same issue. Also, I noticed that it also removes the "not null", "auto increment" and "unique" attributes from other columns

I solved the issue by working around the `queryInterface.removeColumn` and implementing my own logic following the guidelines in the sqlite docs.


```js
function generateBackupTableName(tableName) {
    return `${tableName}_${Math.round(Math.random() * 100)}_backup`;
}

const formatFKsPragmaToSequelizeFK = fk => ({
    references: {
        model: fk.table,
        key: fk.to
    },
    constraints: {
        onDelete: fk['on_update'],
        onUpdate: fk['on_delete']
    }
});

/**
 * Extends the Sequelize describeTable function to include the foreign keys constraints in sqlite dbs
 * @param {import('sequelize').QueryInterface} queryInterface
 * @param {String} tableName - The table name
 */
async function describeTableWithFKs(queryInterface, tableName) {
    const execQuery = queryInterface.sequelize.query.bind(queryInterface.sequelize);
    const quotedTableName = queryInterface.quoteTable(tableName);
    const foreignKeys = await execQuery(`PRAGMA foreign_key_list(${quotedTableName});`);

    const foreignKeysByColName = foreignKeys.reduce((prev, curr) => {
        const fk = formatFKsPragmaToSequelizeFK(curr);
        return { ...prev, [curr.from]: fk };
    }, {});

    const tableDescription = await queryInterface.describeTable(tableName);

    const tableDescriptionWithFks = Object.entries(tableDescription).reduce((prev, [col, attributes]) => {
        let extendedAttributes = attributes;

        if (foreignKeysByColName[col]) {
            extendedAttributes = {
                ...extendedAttributes,
                references: foreignKeysByColName[col].references,
                ...foreignKeysByColName[col].constraints
            };
        }
        return { ...prev, [col]: extendedAttributes };
    }, {});

    return tableDescriptionWithFks;
}

/**
 * Removes a column from a table in sqlite table, preserving foreign key constraints.
 * This method also handles cases where the foreign key constraints would otherwise
 * delete records in the relational table by disabling them during the migration process.
 * The method follows the guide from the sqlite docs:
 * https://sqlite.org/lang_altertable.html
 * @param {import('sequelize').QueryInterface} queryInterface
 * @param {String} tableName - The table name
 * @param {String} columnName - The column name
 */
async function removeColumn(queryInterface, tableName, columnName) {
    const execQuery = queryInterface.sequelize.query.bind(queryInterface.sequelize);

    const quotedTableName = queryInterface.quoteTable(tableName);
    const backupTableName = generateBackupTableName(tableName);
    const quotedBackupTableName = queryInterface.quoteTable(backupTableName);
    const columnToDelete = columnName;

    // Disable foreign key constraints for the next sequence of operations
    await execQuery(`PRAGMA foreign_keys = OFF;`);

    try {
        await queryInterface.sequelize.query(`BEGIN TRANSACTION;`);

        const tableDescriptionWithFks = await describeTableWithFKs(queryInterface, tableName);

        // Remove the selected column
        delete tableDescriptionWithFks[columnToDelete];

        const attributes = queryInterface.QueryGenerator.attributesToSQL(tableDescriptionWithFks);

        // Create the backup table
        await queryInterface.createTable(backupTableName, attributes);

        const attributeNames = Object.keys(attributes)
            .map(attr => queryInterface.quoteIdentifier(attr))
            .join(', ');

        // Copy all data from the target table to the backup table
        await execQuery(`INSERT INTO ${quotedBackupTableName} SELECT ${attributeNames} FROM ${quotedTableName};`);

        // Drop the old (original) table
        await queryInterface.dropTable(tableName);

        // Rename the backup table to the original table's name
        await queryInterface.renameTable(backupTableName, tableName);

        // Validate that all foreign key constraints are correct
        const result = await execQuery(`PRAGMA foreign_key_check(${quotedTableName});`, {
            type: Sequelize.QueryTypes.SELECT
        });

        // There are foreign key violations, exit
        if (result.length) {
            await execQuery(`ROLLBACK;`);
            return Promise.reject(`Foreign key violations detected: ${JSON.stringify(result, null, 2)}`);
        }

        await execQuery(`COMMIT;`);
        await execQuery(`PRAGMA foreign_keys = ON;`);
        return Promise.resolve();
    } catch (err) {
        await execQuery(`ROLLBACK;`);
        await execQuery(`PRAGMA foreign_keys = ON;`);
        return Promise.reject(err);
    }
}
```

## Note that the code above is using internal APIs which are available in **Sequelize v5** and may not work in newer releases.

**Comment by Marco-Veio** [comment]
Thank you very much for sharing your solution, @martineso! I changed it a bit and made it work in the newest version.

**Comment by martineso** [comment]
I am glad it was helpful to you, @Marco-Veio.

**Comment by WikiRik** [comment]
If one of you could make a PR for this we would really appreciate it :)

**Comment by martineso** [comment]
I will get to it this weekend.

**Comment by WikiRik** [comment]
@martineso did you get around to making the PR? If you need any help, feel free to let us know :)

**Comment by martineso** [comment]
I am sorry, it was a bit hectic for me the last couple of weeks. This weekend I will have more time on my hands. I will let you know if I have any questions @WikiRik regarding the PR process.

**Comment by WikiRik** [comment]
No worries, thanks for the update!

**Comment by damms005** [comment]
@martineso @WikiRik I noticed that [the PR with the fix](https://github.com/sequelize/sequelize/pull/14070) is labelled **released on @v7**. Does this mean that the bug will only be available in the not-yet-released sequelize v7? My confusion is that the PR target is the **main** branch of this repo, meaning it was merged to the **main** branch. So, it will be inappropriate to open an issue as this bug persists in current v6, right?

**Comment by damms005** [comment]
> ```js
> const formatFKsPragmaToSequelizeFK = fk => ({
>     references: {
>         model: fk.table,
>         key: fk.to
>     },
>     constraints: {
>         onDelete: fk['on_update'],
>         onUpdate: fk['on_delete']
>     }
> });
> ```

I believe there is a bug at
```
const formatFKsPragmaToSequelizeFK = fk => ({
    references: {
        model: fk.table,
        key: fk.to
    },
    constraints: {
        onDelete: fk['on_update'],
        onUpdate: fk['on_delete']
    }
});
```

In the `constraints` key, `on_update` and `on_delete` are spapped
