### ISSUE TITLE
bulkCreate updateOnDuplicate ignores unique keys

### ISSUE THREAD

**Issue by oxyii** [sequelize/sequelize#12742]
## Issue Description

(ref #11569)

bulkCreate `updateOnDuplicate` bug if unique composite index declared in model options instead of field options.

### What are you doing?

```js
const dbInstance = require('./db');

const Model1 = dbInstance.define('Model1', {
  field1: DataTypes.STRING,
  field2: DataTypes.STRING,
}, {
  indexes: [
    {
      name: 'compositeUnique',
      fields: ['field1', 'field2'],
      unique: true,
    },
  ],
})

const Model2 = dbInstance.define('Model2', {
  field1: {
    type: DataTypes.STRING,
    unique: 'compositeUnique',
  },
  field2: {
    type: DataTypes.STRING,
    unique: 'compositeUnique',
  },
})
```

### What do you expect to happen?

The same behavior in both cases

### What is actually happening?

```js
// get Model1.uniqueKeys
{}
// get Model2.uniqueKeys
{
  "compositeUnique": { /* fields, name.... */ },
}
```

because of this `Insert` request with `ON CONFLICT` fragment use `primaryKey` only in first case (Model1)

### Additional context

nope

### Environment

- Sequelize version: **6.3.5**
- Node.js version: **12.18.4**
- Operating System: tested on **Ubuntu 18.04, 20.04** and **MacOS 10.15**
- If TypeScript related: TypeScript version: **irrelevant**, tried on TS 4.0.3 and pure js

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by kreinholt** [comment]
Some relevant pull requests that might solve this are: https://github.com/sequelize/sequelize/pull/12516 and https://github.com/sequelize/sequelize/pull/12547
