### ISSUE TITLE
Postgres pg parseRow slow

### ISSUE THREAD

**Issue by lukas1994** [sequelize/sequelize#12744]
## Issue Description

I just profiled my app and it turns out that a lot of time is spent parsing rows in the pg library:
![image](https://user-images.githubusercontent.com/6901762/95452368-0d076c00-0961-11eb-98b3-e95fdc6562bb.png)

I do have some larger json columns. Is there anything I can do to speed that up?  I read about `pg-native` — would that help?

Thanks

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): postgres
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by LucCADORET** [comment]
Same as you, I am surprised that there aren't more comments on this. After profiling my node app, the time taken by parseRow is about 50% of my total CPU time ! I do quite a lot of queries to the database - more than necessary, there are a lot of optimisation to be done - but still I would like to turn down the parsing when it is not necessary, e.g. when I insert a new record but don't care about the immediate return value (returning: false) is not working.

**Comment by ephys** [comment]
If you have returning set to false, then we have nothing to parse. I don't think the parser would be called

Getting the parser function itself is a [simple map lookup](https://github.com/sequelize/sequelize/blob/ephys/ts-data-types/src/dialects/postgres/connection-manager.ts#L340) on our end, as it is cached. The parsers themselves are also [simple functions that do minimal work](https://github.com/sequelize/sequelize/blob/ephys/ts-data-types/src/dialects/postgres/data-types-db.ts)

I don't see anything here that would cause any sort of perf issue. Maybe pg's default [getTypeParser](https://github.com/sequelize/sequelize/blob/ephys/ts-data-types/src/dialects/postgres/connection-manager.ts#L354) re-creates a new parser every time? But from what I see, it's also just [a simple table lookup](https://github.com/brianc/node-pg-types/blob/8594bc6befca3523e265022f303f1376f679b5dc/index.js#L23)

**Comment by ephys** [comment]
We take the values you pass to `Model.create` and assign them to the new instance, but they don't go through the parser as these values don't come from the database. When returning is true, we then replace these values by what the database returned (useful for columns with default values)
