### ISSUE TITLE
describeTable returns an invalid defaultValue on Postgresql for `timezone('utc'::text, now())`

### ISSUE THREAD

**Issue by ghusse** [sequelize/sequelize#12749]
### What are you doing?

With a table define like this, on postgresql

```sql
CREATE TABLE public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    name text COLLATE pg_catalog."default",
    updatedat timestamp with time zone DEFAULT timezone('utc'::text, now())
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

I'm getting the `tableDescription` like this:

```js
const sequelize = require('sequelize')

const connection = new sequelize.Sequelize('postgres://user:pass@localhost:5432/database')

const qi = connection.getQueryInterface();

qi.describeTable('users').then(x => console.log(x))
```

The output for the `updatedat` field gives:

```
  {
    type: 'TIMESTAMP WITHOUT TIME ZONE',
    allowNull: true,
    defaultValue: 'timezone(utc',
    comment: null,
    special: [],
    primaryKey: false
  }
```

The default value is truncated

### What do you expect to happen?

At least a non-truncated value, something like `timezone('utc'::text, now())`. I don't know why quotes are removed from the default value of the id, which is `nextval(users_id_seq::regclass)`

### What is actually happening?

The default value is `timezone(utc`

### Additional context

The transformation is done by this code: https://github.com/sequelize/sequelize/blob/master/src/dialects/postgres/query.js#L251

### Environment

- Sequelize version: on master, on v5.22.0
- Node.js version: 12.13.0
- Operating System: Mac OS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): Postgresql
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ghusse** [comment]
I'm OK to do the necessary modifications, but is it possible to discuss what they should be? It seems that something special is done to transform the value when it's `nextval(users_id_seq::regclass)`, and in my case, what should be the expected value?

**Comment by ghusse** [comment]
It seems to have been introduced by this change: https://github.com/sequelize/sequelize/pull/7888/files#diff-511bdc848dd4105907ae495f78229bd9ab118a742c840af98c6974a796291b14R213 from #7888 by @alitaheri 

Any chance that someone give me some inputs on this?

**Comment by tmudford** [comment]
Just checking if someone has a fix for this yet?
