### ISSUE TITLE
Getting: "Warning: a promise was created in a handler but was not returned from it"

### ISSUE THREAD

**Issue by Raynesz** [sequelize/sequelize#12769]
## Issue Description

I have a nodejs server as a REST API with various routes and i am using sequelize to access and manage a database. I have realized that all routes, that are using sequelize to access the database, log this message in my console when i am in development environment:
`(node:13176) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (D:\{my_project_directoruy}\node_modules\bluebird\js\release\method.js:29:9)`
But at this point, i dont know if this is an issue with sequelize or bluebird. I initially thought it was a mistake in my code or bad practice using promises in my part but i have tried a lot of suggestions around and nothing seems to get this error to go away.

If applicable, you can add some code. In this case, an SSCCE/MCVE/reprex is much better than just an isolated code snippet.

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x] No, I don't have the time and I wouldn't even know how to start.

**Comment by dkMorlok** [comment]
Witch version of sequelize do you use? I have same error using sequelize 5.x caused by model method `upsert`
