### ISSUE TITLE
How can we migrate a table which has foreign key constraints?

### ISSUE THREAD

**Issue by BoxSo** [sequelize/sequelize#12789]
## Issue Description

We use sequelize and Umzug within our nodejs project for database changes needed. It is very important that all data within the database will survive a migration from version to version as we talk about migrations at several productively used instances of our solution. Sequelize works good as long as there are no foreign key constraints at play.

In our scenario we have an existing table "devices", which has a foreign key constraint set to another table "basedata" -> "id". Now i need to remove a not null constraint within table "devices". I tried to do this with the following migration script:

`const { Sequelize } = require('sequelize');

module.exports = {
  up: async (queryInterface) => {
    await queryInterface.changeColumn('devices', 'basedataId', {
      type: Sequelize.BIGINT,
      allowNull: true,
      references: {
        model: 'basedata',
        key: 'id'
      }
    });
  }
};`

this fails with the following error:

`<rejected> ForeignKeyConstraintError [SequelizeForeignKeyConstraintError]: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
      at Query.formatError (C:\....\node_modules\sequelize\lib\dialects\sqlite\query.js:366:18)
      at Query._handleQueryResponse (C:\....\node_modules\sequelize\lib\dialects\sqlite\query.js:72:18)
      at Statement.afterExecute (C:\....\node_modules\sequelize\lib\dialects\sqlite\query.js:246:27) {
    parent: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
      errno: 19,
      code: 'SQLITE_CONSTRAINT',
      sql: 'DROP TABLE `devices`;'
    },
    original: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
      errno: 19,
      code: 'SQLITE_CONSTRAINT',
      sql: 'DROP TABLE `devices`;'
    },
    sql: 'DROP TABLE `devices`;',
    parameters: undefined,
    fields: undefined,
    table: undefined,
    value: undefined,
    index: undefined,
    reltype: undefined
  }
  }
} reason: SequelizeForeignKeyConstraintError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed`

What is the correct approach to make changes to a table which has foreign key constraints set or is a target for a foreign key constraint of another table in database?

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/64533732/process-of-changing-a-table-with-sequelize-migration-if-foreign-key-constraint-i

### Additional context
Environment:
- sqlite
- nodeJS 10 LTS
- sequelize / umzug npm packages
- windows / linux (debian)

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by martineso** [comment]
I have faced the same issue and had to write my own alter table logic following the sqlite process documented [here](https://sqlite.org/lang_altertable.html). 
Here is a working code for `changeColumn`:


```js
function generateBackupTableName(tableName) {
    return `${tableName}_${Math.round(Math.random() * 100)}_backup`;
}

const formatFKsPragmaToSequelizeFK = fk => ({
    references: {
        model: fk.table,
        key: fk.to
    },
    constraints: {
        onDelete: fk['on_update'],
        onUpdate: fk['on_delete']
    }
});

/**
 * Extends the Sequelize describeTable function to include the foreign keys constraints in sqlite dbs
 * @param {import('sequelize').QueryInterface} queryInterface
 * @param {String} tableName - The table name
 */
async function describeTableWithFKs(queryInterface, tableName) {
    const execQuery = queryInterface.sequelize.query.bind(queryInterface.sequelize);
    const quotedTableName = queryInterface.quoteTable(tableName);
    const foreignKeys = await execQuery(`PRAGMA foreign_key_list(${quotedTableName});`);

    const foreignKeysByColName = foreignKeys.reduce((prev, curr) => {
        const fk = formatFKsPragmaToSequelizeFK(curr);
        return { ...prev, [curr.from]: fk };
    }, {});

    const tableDescription = await queryInterface.describeTable(tableName);

    const tableDescriptionWithFks = Object.entries(tableDescription).reduce((prev, [col, attributes]) => {
        let extendedAttributes = attributes;

        if (foreignKeysByColName[col]) {
            extendedAttributes = {
                ...extendedAttributes,
                references: foreignKeysByColName[col].references,
                ...foreignKeysByColName[col].constraints
            };
        }
        return { ...prev, [col]: extendedAttributes };
    }, {});

    return tableDescriptionWithFks;
}

/**
 * Changes a column in a table in sqlite db, preserving foreign key constraints.
 * This method also handles cases where the foreign key constraints would otherwise
 * delete records in the relational table by disabling them during the migration process.
 * The method follows the guide from the sqlite docs:
 * https://sqlite.org/lang_altertable.html
 * @param {import('sequelize').QueryInterface} queryInterface
 * @param {String} tableName - The table name
 * @param {String} columnName - The column name
 * @param {import('sequelize').ModelAttributeColumnOptions|import('sequelize').DataType} definition
 */
async function changeColumn(queryInterface, tableName, columnName, definition) {
    const execQuery = queryInterface.sequelize.query.bind(queryInterface.sequelize);

    const quotedTableName = queryInterface.quoteTable(tableName);
    const backupTableName = generateBackupTableName(tableName);
    const quotedBackupTableName = queryInterface.quoteTable(backupTableName);
    const targetColumn = columnName;

    let newColumnDefinition = definition;
    if (definition in Sequelize.DataTypes) {
        newColumnDefinition = {
            type: definition,
            allowNull: true
        };
    }

    newColumnDefinition = queryInterface.sequelize.normalizeAttribute(newColumnDefinition);
    // Disable foreign key constraints for the next sequence of operations
    await execQuery(`PRAGMA foreign_keys = OFF;`);

    try {
        await queryInterface.sequelize.query(`BEGIN TRANSACTION;`);

        const tableDescriptionWithFks = await describeTableWithFKs(queryInterface, tableName);

        Object.assign(tableDescriptionWithFks, { [targetColumn]: newColumnDefinition });

        const attributes = queryInterface.QueryGenerator.attributesToSQL(tableDescriptionWithFks);

        // Create the backup table
        await queryInterface.createTable(backupTableName, attributes);

        const attributeNames = Object.keys(attributes)
            .map(attr => queryInterface.quoteIdentifier(attr))
            .join(', ');

        // Copy all data from the target table to the backup table
        await execQuery(`INSERT INTO ${quotedBackupTableName} SELECT ${attributeNames} FROM ${quotedTableName};`);

        // Drop the old (original) table
        await queryInterface.dropTable(tableName);

        // Rename the backup table to the original table's name
        queryInterface.renameTable(backupTableName, tableName);

        // Validate that all foreign key constraints are correct
        const result = await execQuery(`PRAGMA foreign_key_check(${quotedTableName});`, {
            type: Sequelize.QueryTypes.SELECT
        });

        // There are foreign key violations, exit
        if (result.length) {
            await execQuery(`ROLLBACK;`);
            return Promise.reject(`Foreign key violations detected: ${JSON.stringify(result, null, 2)}`);
        }

        await execQuery(`COMMIT;`);
        await execQuery(`PRAGMA foreign_keys = ON;`);
        return Promise.resolve();
    } catch (err) {
        await execQuery(`ROLLBACK;`);
        await execQuery(`PRAGMA foreign_keys = ON;`);
        return Promise.reject(err);
    }
}
```
