### ISSUE TITLE
BelongsToManyGetAssociationsMixinOptions incomplete

### ISSUE THREAD

**Issue by fabrykowski** [sequelize/sequelize#12782]
### What are you doing?

I am trying to query in TypeScript models linked via `belongsToMany` with conditions to the through model.

**Here is the link to the SSCCE for this issue:** papb/sequelize-sscce#123 

### What do you expect to happen?

The code to compile.

### What is actually happening?

The compilation fails

```
src/sscce.ts:161:5 - error TS2345: Argument of type '{ through: { where: { isManager: boolean; }; }; }' is not assignable to parameter of type 'BelongsToManyGetAssociationsMixinOptions'.
  Object literal may only specify known properties, and 'through' does not exist in type 'BelongsToManyGetAssociationsMixinOptions'.
```

### Additional context

n.a.

### Environment

- Sequelize version: 5.22.3 in SSCCE; 6.3.5 locally
- Node.js version: v14.13.0
- Operating System: OS X
- TypeScript version: 4.0.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by fabrykowski** [comment]
Still an issue

**Comment by fabrykowski** [comment]
Bump

**Comment by WikiRik** [comment]
Hi, sorry about needing to bump a few times. We have done some edits to this since 6.3.5. Does this still occur on the latest release? (6.11.0 at the time of writing)

**Comment by ephys** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/14280
