### ISSUE TITLE
Sequelize use latest validator

### ISSUE THREAD

**Issue by zwzw911** [sequelize/sequelize#12783]
## Issue Description
sequelze use validator@10.11.0, while the latest validator is 13.1.17, is it possible use the latest one?

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [X]  No. This issue is relevant to Sequelize as a whole.

- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by DevRCRun** [comment]
It looks like this has also now become security relevant per https://snyk.io/test/npm/validator/10.11.0 (i.e. the recent fixes for reDOS vulns)

**Comment by uralsemih** [comment]
+1

**Comment by uralsemih** [comment]
Is there any estimation date for this issue ?

**Comment by papb** [comment]
Upgraded to v13 (#13350), this is now available at [v6.6.5](https://github.com/sequelize/sequelize/releases/tag/v6.6.5), thank you all, sorry to take long!
