### ISSUE TITLE
MSSQL- set default value

### ISSUE THREAD

**Issue by tonysader** [sequelize/sequelize#12797]
## Issue Description
When using mssql and set the default value to a column, it executes the wrong syntax query, 

### What do you expect to happen?

Modify the default query to alter defaults for mssql

### What is actually happening?

```
Executing (default): ALTER TABLE [TABLENAME] ALTER COLUMN [COLUMNNAME] INTEGER NOT NULL DEFAULT 1;
```
Should be

```
ALTER TABLE [TABLENAME] ADD CONSTRAINT [INDEXNAME] DEFAULT 50 FOR [COLUMNNAME];
```

### How does this problem relate to dialects?

-  I think this problem happens only for the following dialect(s): mssql

### Would you be willing to resolve this issue by submitting a Pull Request?

-  No, I don't have the time, although I believe I could do it if I had the time...

**Comment by tayyabferozi** [comment]
How did you fix the issue? It seems like they didn't look at it and its been approximately a year

**Comment by timhaak** [comment]
Bug is still there unfortunately

Executing (default): ALTER TABLE [sms_test].[accounts] ALTER COLUMN [commodity_classification] BIT NOT NULL DEFAULT 0;
✖ Incorrect syntax near the keyword 'DEFAULT'.

 commodityClassification: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
      },

**Comment by avalencia-vso** [comment]
I ran into the same issue.  Can the official documentation at least be updated to say "defaultValue" does not work with MSSQL?

**Comment by gsbenjamin** [comment]
I have this same issue with the wrong SQL statement generated by sequeilize when adding a defaultvalue for an integer field.
