### ISSUE TITLE
Spurious UNIQUE property added during migration

### ISSUE THREAD

**Issue by chscott** [sequelize/sequelize#12798]
### What are you doing?

```js
const columns = ['timestampLow', 'timestampHigh']

    for (const column of columns) {
      log.info(`Removing unique constraint on ${column} column...`)
      await queryInterface.changeColumn('monitor', column, {
        type: DataTypes.INTEGER,
        allowNull: false,
        unique: false,
      })
    }
```

### What do you expect to happen?

I expected the UNIQUE property to be removed for the timestampLow and timestampHigh columns. In this case, the monitor table did not have those properties set, so I expected essentially a no-op, resulting in a monitor table in the same state as prior to the migration.

### What is actually happening?

The monitor_backup table is created with the UNIQUE property set on the timestampHigh column even though that property does not exist in the monitor database.

### Additional context

![image](https://user-images.githubusercontent.com/9805298/97603075-10c76500-19da-11eb-898a-594391eed69e.png)

```sql
CREATE TABLE `monitor_backup` (`id` INTEGER PRIMARY KEY, `pid` INTEGER NOT NULL, `jobID` INTEGER NOT NULL, `currentFolder` VARCHAR(512) NOT NULL, `hostName` VARCHAR(512) NOT NULL, `currentFolderNumber` INTEGER NOT NULL, `totalFolders` INTEGER NOT NULL, `totalItemCount` INTEGER NOT NULL, `attachmentCount` INTEGER NOT NULL, `dataRate` INTEGER NOT NULL, `totalKb` INTEGER NOT NULL, `action` INTEGER NOT NULL, `completed` INTEGER NOT NULL, `stalled` INTEGER NOT NULL, `timestampLow` INTEGER NOT NULL, `timestampHigh` INTEGER NOT NULL UNIQUE, `applied` TINYINT(1) NOT NULL DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `itemMigratedCount` INTEGER NOT NULL, `itemDuplicateCount` INTEGER NOT NULL, `itemFilteredCount` INTEGER NOT NULL DEFAULT '0', `cpuUsage` INTEGER NOT NULL DEFAULT '0')
```

Note the **`timestampHigh` INTEGER NOT NULL UNIQUE**.

The monitor database does have a unique index that includes these two columns.

```sql
CREATE UNIQUE INDEX `monitor_timestamp` ON `monitor` (`timestampHigh`, `timestampLow`)
```

### Environment

- Sequelize version: 5.22.3
- Node.js version: 12.8.1
- Operating System: Windows 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): sqlite
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by kr99** [comment]
This also looks somewhat similar to https://github.com/sequelize/sequelize/issues/7078 but it's not clear to me yet.  We are on a higher version than when that issue was fixed, so probably similar but not the same bug.

**Comment by mikealeonetti** [comment]
Same issue here. Before the update I have this on the table:

CREATE UNIQUE INDEX `trades_account_key_symbol` ON `trades` (`accountKey`, `symbol`);

After update it looks like this:

 `accountKey` VARCHAR(255) NOT NULL UNIQUE, `symbol` VARCHAR(255) NOT NULL UNIQUE,

So one unique becomes split into two.
