### ISSUE TITLE
Typescript error when using `unscoped` on model

### ISSUE THREAD

**Issue by fTrestour** [sequelize/sequelize#12809]
### What are you doing?

I define my model pretty much as follows and try to use it with the `unscoped` method:

```ts
import { Model, Optional } from 'sequelize/types'

export interface ExampleModelAttributes {
  id: number
  name: string
}

export class ExampleModel
  extends Model<ExampleModelAttributes, Optional<ExampleModelAttributes, 'id'>>
  implements ExampleModelAttributes {
  public id!: number
  public name!: string
  public readonly createdAt!: Date
  public readonly updatedAt!: Date
}

ExampleModel.scope()
ExampleModel.unscoped() // The 'this' context of type 'typeof ExampleModel' is not assignable to method's 'this' of type 'typeof Model'.
```

### What do you expect to happen?

I expected to be able to call `ExampleModel.unscoped()` without a TS error

### What is actually happening?

There is a TS error

```
The 'this' context of type 'typeof ExampleModel' is not assignable to method's 'this' of type 'typeof Model'.
  Types of parameters 'values' and 'values' are incompatible.
    Type 'TCreationAttributes | undefined' is not assignable to type 'Optional<ExampleModelAttributes, "id"> | undefined'.
      Type 'TCreationAttributes' is not assignable to type 'Optional<ExampleModelAttributes, "id"> | undefined'.
        Type '{}' is not assignable to type 'Optional<ExampleModelAttributes, "id">'.
          Type '{}' is not assignable to type 'Pick<ExampleModelAttributes, "name">'.
            Type 'TCreationAttributes' is not assignable to type 'Optional<ExampleModelAttributes, "id">'.
              Type '{}' is not assignable to type 'Optional<ExampleModelAttributes, "id">'.
                Type '{}' is not assignable to type 'Pick<ExampleModelAttributes, "name">'.
                  Type 'TCreationAttributes' is not assignable to type 'Pick<ExampleModelAttributes, "name">'.
                    Property 'name' is missing in type '{}' but required in type 'Pick<ExampleModelAttributes, "name">'.
```

### Environment

- Sequelize version: 6.3.5
- Node.js version: v12.13.1
- Operating System: MacOS Catalina 10.15.6
- If TypeScript related: TypeScript version: 4.0.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by PurkkaKoodari** [comment]
This is especially irritating given that `scope()`'s signature does not accept `null`, which is the other way of removing the default scope.

`unscoped()` is defined as such:

https://github.com/sequelize/sequelize/blob/4063c2ab627ad57919d5b45cc7755f077a69fa5e/types/lib/model.d.ts#L2129

The `this` and return types differs from that used in `scope()`:

https://github.com/sequelize/sequelize/blob/4063c2ab627ad57919d5b45cc7755f077a69fa5e/types/lib/model.d.ts#L1729

Changing `unscoped()`'s signature to match `scope()` seems to fix the error. I think `scope()`'s signature and documentation should be updated to accept `null` as well, as the [documentation](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-scope) mentions that `null` is a valid argument.
