### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] when running sequelize

### ISSUE THREAD

**Issue by chelouUSC** [sequelize/sequelize#12806]
## Issue Description
When trying to run sequelize im getting an error shown below. This is running fine on all unix based machines but it is not working on Windows 10. 

### What are you doing?
Running `sequelize db:migrate.` 
It also happens for any sequelize cli command. 

Here is our config.json. We are using the development environment
```js
{
  "development": {
    "database": "nomi-dev",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "define": {
      "freezeTableName": true
    }

  },
  "production": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres",
    "define": {
      "freezeTableName": true
    }
  }
}
```

### What do you expect to happen?
For the command to run without errors. 
### What is actually happening?
There is an error.

```
Sequelize CLI [Node: 14.5.0, CLI: 6.2.0, ORM: 6.3.5]

Loaded configuration file "config\config.json".
Using environment "development".
internal/crypto/keys.js:324
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received null
    at prepareSecretKey (internal/crypto/keys.js:324:11)
    at new Hmac (internal/crypto/hash.js:111:9)
    at Object.createHmac (crypto.js:143:10)
    at createHMAC (C:\Users\chadh\Documents\Projects\Nomi\menu-service\node_modules\pg\lib\sasl.js:133:17)
    at Hi (C:\Users\chadh\Documents\Projects\Nomi\menu-service\node_modules\pg\lib\sasl.js:137:13)
    at Object.continueSession (C:\Users\chadh\Documents\Projects\Nomi\menu-service\node_modules\pg\lib\sasl.js:32:24)
    at Client._handleAuthSASLContinue (C:\Users\chadh\Documents\Projects\Nomi\menu-service\node_modules\pg\lib\client.js:257:10)
    at Connection.emit (events.js:314:20)
    at C:\Users\chadh\Documents\Projects\Nomi\menu-service\node_modules\pg\lib\connection.js:109:12
    at Parser.parse (C:\Users\chadh\Documents\Projects\Nomi\menu-service\node_modules\pg-protocol\dist\parser.js:40:17)
    at Socket.<anonymous> (C:\Users\chadh\Documents\Projects\Nomi\menu-service\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Environment

- Sequelize version: ^6.3.5 
- Node.js version: ^14.4.0
- Operating System: Windows 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x ] I think this problem happens only for the following dialect(s): postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by NicoRiquelmeCTI** [comment]
hi, i have the same issue here, have you fixed it?

**Comment by bd901029** [comment]
Hi guys, I have same problem. Anyone fixed it?

**Comment by cchyung** [comment]
i have this problem as well, has anyone managed to fix?

**Comment by bboynton97** [comment]
I just inexplicably started getting this error recently without any known changes to how sequelize is being set up and used

**Comment by bboynton97** [comment]
As a followup, I am only experiencing this issue on Windows. When I've run the exact same code on mac I have no issue at all. Not sure what's up but I would certainly like to be able to work on each OS

**Comment by jonassunandar** [comment]
Hi guys, I get the problem as well on mac m1

**Comment by Hiroki111** [comment]
I saw a similar error. This was solved by specifying the environment with`:`.

e.g.
```
// package.json
  "scripts": {
    // other commands here
    "db:create:test": "cross-env NODE_ENV=test npx sequelize-cli db:create"
  },

// in Command line prompt
yarn run db:create:test
```

**Comment by kopigreenx** [comment]
u guys need fix in this line 
before i got error with
`"password": 12345`
to
`"password": "12345"` or ``"password": null``

**Comment by mithunmumbai** [comment]
in my case a small change in config.json. to change the password from integer to string.

**Comment by bowtiedalien** [comment]
> u guys need fix in this line before i got error with `"password": 12345` to `"password": "12345"` or `"password": null`

Thank you! This worked.
