### ISSUE TITLE
AWS Lambda randomly get SequelizeConnectionAcquireTimeoutError: Operation timeout after 50ms

### ISSUE THREAD

**Issue by hungnv-sr** [sequelize/sequelize#12819]
## Issue Description
 SequelizeConnectionAcquireTimeoutError: Operation timeout after only 50s. 

### What are you doing?
I'm running nodejs with sequelize on Lambda, my config:
```
	pool: {
		max: 5,
		min: 0,
		acquire: 20000,
		idle: 10000
	}
```
### What do you expect to happen?
I also have another Lambda function with the same exact settings (but with node 12 instead of node 10), which handle much more request per hour, but less executions per request, and it work perfectly fine.

### What is actually happening?

This Lambda function with nodejs 10 randomly encounter timeout errors (about 2-3 times in 1000 times)

**The problem is, setting timeout of Lambda is already 60s, sequelize aquire 20s, no transaction used, and this timeout error happens after 50ms (0.05s)**
Traces:

```
ERROR	Unhandled Promise Rejection	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "SequelizeConnectionAcquireTimeoutError: Operation timeout",
    "reason": {
        "errorType": "SequelizeConnectionAcquireTimeoutError",
        "errorMessage": "Operation timeout",
        "name": "SequelizeConnectionAcquireTimeoutError",
        "parent": {
            "errorType": "Error",
            "errorMessage": "Operation timeout",
            "stack": [
                "Error: Operation timeout",
                "    at Timeout._timeout.setTimeout (/var/task/node_modules/sequelize-pool/lib/Deferred.js:17:25)",
                "    at ontimeout (timers.js:436:11)",
                "    at tryOnTimeout (timers.js:300:5)",
                "    at listOnTimeout (timers.js:263:5)",
                "    at Timer.processTimers (timers.js:223:10)"
            ]
        },
        "original": {
            "errorType": "Error",
            "errorMessage": "Operation timeout",
            "stack": [
                "Error: Operation timeout",
                "    at Timeout._timeout.setTimeout (/var/task/node_modules/sequelize-pool/lib/Deferred.js:17:25)",
                "    at ontimeout (timers.js:436:11)",
                "    at tryOnTimeout (timers.js:300:5)",
                "    at listOnTimeout (timers.js:263:5)",
                "    at Timer.processTimers (timers.js:223:10)"
            ]
        },
        "stack": [
            "SequelizeConnectionAcquireTimeoutError: Operation timeout",
            "    at ConnectionManager.getConnection (/var/task/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:288:48)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: SequelizeConnectionAcquireTimeoutError: Operation timeout",
        "    at process.on (/var/runtime/index.js:37:15)",
        "    at process.emit (events.js:198:13)",
        "    at process.EventEmitter.emit (domain.js:448:20)",
        "    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)",
        "    at process._tickCallback (internal/process/next_tick.js:69:34)"
    ]
}
```

### Additional context

I tried to change max pool from 4 to 20, min pool to 1, but it still doesn't work

### Environment

- Sequelize version: 6.3.5
- Node.js version: 10.X
- Operating System: AWS Lambda

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect. (It work fine with my other function)

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by hungnv-sr** [comment]
The problem was caused by random Exception in my code. The problem is this error hinder stack trace from that exception and I couldn't debug it.

**Comment by nullisusername** [comment]
Did you find a solution? I'm encountering a very similar problem.

**Comment by hungnv-sr** [comment]
@nullisusername In my case, after you established a connection to your database, any unhandled error will not be logged to stack trace, and this error is returned instead of the exception from error. 
I thought it happened randomly but in fact, it happened in some specific case I didn't expect.I don't really know the reason behind this, but you should debug your application instead of trying to solve this error.
