### ISSUE TITLE
Better TS support possible with the upcoming TS 4.1

### ISSUE THREAD

**Issue by Sun-2** [sequelize/sequelize#12816]
## Feature Description

In the upcoming TS 4.1, a feature called [Template Literals](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-rc/#template-literal-types) will be added. This release should be out in less than 2 weeks.

Template literals allow for the following:
```
type World = "world";
type Greeting = `hello ${World}`;
```

It looks like it could help with auto-generating types for models basing just on the data provided to `init` (the `getAssociated` methods in particular), rather than forcing the user to type it all manually.

### Describe alternatives/workarounds you've considered
Manual typing as it is takes quite a bit of work and is error-prone.

### Is this feature dialect-specific?

**No. This issue is relevant to Sequelize as a whole.** At least I believe so.

### Would you be willing to implement this feature by submitting a Pull Request?

**Yes, I have the time but I don't know how to start, I would need guidance.**

I'm a Sequelize newcomer. One of the irksome things I found while reading the docs is the amount of TS code you've got to write the type the models. With TS 4.1, inferring type data could be fully (or at least - mostly) automated, or at least it seems so to me at the first glance. I'm willing to give it a try.

**Comment by papb** [comment]
Awesome!! Great idea!
