### ISSUE TITLE
 Can't create unsigned int

### ISSUE THREAD

**Issue by cyberinvalid** [sequelize/sequelize#12817]
### What are you doing?

```js
import sequelizeLib from 'sequelize';
import sequelize from '..';

const { Model, DataTypes } = sequelizeLib;

export default class Test extends Model {}

Test.init({
    priceId: {
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false,
        primaryKey: true
    },
    price: {
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false
    },
    type: {
        type: DataTypes.STRING(30),
        allowNull: false
    }
}, {
    sequelize,
    modelName: 'Test',
    indexes: [{
        unique: true,
        fields: ['type']
    }]
});

```

### What do you expect to happen?

_I wanted the fields "priceId", "price" to be unsigned int_

### What is actually happening?

_But the created table fiels instead of unsigned int is integer_

```sql
-- Table: public.Tests

-- DROP TABLE public."Tests";

CREATE TABLE public."Tests"
(
    "priceId" integer NOT NULL,
    price integer NOT NULL,
    type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "Tests_pkey" PRIMARY KEY ("priceId")
)

TABLESPACE pg_default;

ALTER TABLE public."Tests"
    OWNER to postgres;
-- Index: tests_type

-- DROP INDEX public.tests_type;

CREATE UNIQUE INDEX tests_type
    ON public."Tests" USING btree
    (type COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
```

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 14.14.0 
- Operating System: Windows 10 x64
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using postgres, with connector library version "pg": "^8.4.2" and database version 13

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by cyberinvalid** [comment]
Sorry didt notice that for postgres is not supported unsigned int.

**Comment by TokugawaTakeshi** [comment]
@cyberinvalid 

> Sorry didt notice that for postgres is not supported unsigned int.

Is one of `smallserial` , `serial` and `bigserial` what you want?
https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC
