### ISSUE TITLE
update: WHERE parameter "xx" has invalid "undefined" value

### ISSUE THREAD

**Issue by krisQT** [sequelize/sequelize#12818]
## Issue Description
right: 
```
const classify = await Classify.findOne({
      where: {
        id
      }
    })
classify.name = 'xxx'
classify.save()
```
error: 
```
Classify.update({ name: 'xxx' }, {
      where: {
        id: 1
      }
    });
```
Why can't I use model.update
### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by GusevDV** [comment]
Hello! Have you solved this problem?

**Comment by HappyPHANTHOM** [comment]
Tengo el mismo problema y no encuentro una respuesta :/

**Comment by ephys** [comment]
@HappyPHANTHOM If you can manage to reproduce your issue with https://github.com/sequelize/sequelize-sscce, we'll be able to help you more
