### ISSUE TITLE
When migrating a SQLITE database which has a unique constraint on 2 or more columns, some migrations rebuild the table with a unique constraint on each column.

### ISSUE THREAD

**Issue by evantahler** [sequelize/sequelize#12823]
## Issue Description

Say you have a table with a unique constant on 2 or more columns:

```
Executing (default): CREATE UNIQUE INDEX `posts_name_image` ON `posts` (`name`, `image`)
``` 

When migrating a SQLITE database which has a unique constraint on 2 or more columns, some migrations in SQLITE (ie: those that remove a column or change one) cause a table rebuild like:
```
Executing (default): CREATE TABLE IF NOT EXISTS `posts_backup` (`id` VARCHAR(255), `name` VARCHAR(255) UNIQUE, `image` VARCHAR(255) UNIQUE, `position` BIGINT NOT NULL DEFAULT '0');
```
If you have an index spanning more than one column like the below, it gets messed up.  Notice how in the above SQL, now both image and name are each `unique`, when they were not before.

### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/evantahler/sequleize-sqlite-migrations

In a nutshell, these 2 migrations cause the problem:

```js
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.createTable("posts", {
      id: Sequelize.DataTypes.STRING,
      name: Sequelize.DataTypes.STRING,
      image: Sequelize.DataTypes.STRING,
    });

    await queryInterface.addIndex("posts", ["name", "image"], {
      unique: true,
      fields: ["name", "image"],
    });
  },
  down: (queryInterface, Sequelize) => {},
};
```

```js
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.addColumn("posts", "position", {
      type: Sequelize.DataTypes.BIGINT,
      allowNull: true,
      defaultValue: 0,
    });

    await queryInterface.changeColumn("posts", "position", {
      type: Sequelize.DataTypes.BIGINT,
      allowNull: false,
    });
  },
  down: (queryInterface, Sequelize) => {},
};

```

### What do you expect to happen?

I would expect both `image` and `name` to not be uniquely constrained at the column level, and for the compound unique index to remain. 

### What is actually happening?

The migration lost the compound unique index, and added a `unique` constraint to columns that should not have one.

### Additional context

<img width="1477" alt="Screen Shot 2020-11-09 at 5 54 33 PM" src="https://user-images.githubusercontent.com/303226/98619057-4c560f00-22b7-11eb-8c98-ff663328e83b.png">

### Environment

- Sequelize version: 5.22.3
- Node.js version: 12.x
- Operating System: OSX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): SQLITE
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by evantahler** [comment]
I can confirm that this issue is also present on sequelize v6 (tested with v6.3.5)

**Comment by evantahler** [comment]
The problem is located here https://github.com/sequelize/sequelize/blob/042cd693635ffba83ff7a2079974692af6f710a7/src/dialects/sqlite/query-interface.js

In the case where there is a compound index looks like:

```json
[
    {
        "seq": 0,
        "name": "posts_name_image",
        "unique": true,
        "origin": "c",
        "partial": 0,
        "fields": [
            {
                "attribute": "name"
            },
            {
                "attribute": "image"
            }
        ],
        "primary": false,
        "constraintName": "posts_name_image"
    }
]
```

You are assuming that since `index.unique` is true, the field should be unique... but that's not the case with compound indexes.

**Comment by evantahler** [comment]
The above problem still exists on the master branch @ https://github.com/sequelize/sequelize/blob/master/src/dialects/sqlite/query-interface.js

**Comment by rickbergfalk** [comment]
This is a duplicate of #12488

**Comment by rickbergfalk** [comment]
If it helps anyone out there, I worked around this by staying on Sequelize 6.2.2 until I no longer needed the migration that rebuilt the SQLite table.

**Comment by evantahler** [comment]
Has this been fixed in a new release? That would be great!  

Reading the release notes, I can’t find anything related…

**Comment by rickbergfalk** [comment]
@evantahler I don't think so. It's just the stale bot cleaning things up. #12488 is still open and covers same issue if you want to follow it.
