### ISSUE TITLE
Increment or Decrement value using Sequelize upsert() does not work when updating

### ISSUE THREAD

**Issue by Rffrench** [sequelize/sequelize#12834]
## Issue Description

`upsert()` method in `sequelize` does not increment value when it updates using `sequelize.literal()`, it only modifies it.

### What are you doing?
In Sequelize with a MySQL Database I am using upsert() to insert a new row if it doesn't exist or increment one of its field values by some other value if it exists.

Inserting works fine but when the value gets updated it is not getting incremented but completely updated

    let x = 5;

    OrderDetails.upsert({ 
       menuItemId: 1234, 
       orderId: 4321, 
       quantity: sequelize.literal((`quantity + ${x}`)
    })

This results in this query:

    INSERT INTO `OrderDetails` (`menuItemId`,`orderId`,`quantity`,`createdAt`,`updatedAt`) VALUES (?,?,quantity + 5,?,?) 
    ON DUPLICATE KEY UPDATE `menuItemId`=VALUES(`menuItemId`),`orderId`=VALUES(`orderId`),`quantity`=VALUES(`quantity`),`updatedAt`=VALUES(`updatedAt`);

So if for example the previous value was `10` then after the query the updated value will be `5` instead of `15`. 

My guess is that there is a kind of bug in Sequelize when using `upsert()` with `sequelize.literal()`. Apparently, it is only recognized in the insertion and not in the update.

**_NOTE:_** This obviously **works** if I use `update()` with `sequelize.literal()`

### What do you expect to happen?

The specified field should be incremented instead of completely modified and replaced with the value

### What is actually happening?

If the previous value in my table was `10` then after executing the query the updated value will be `5` instead of `15`. 

### Additional context

None.

### Environment

- Sequelize version: `6.3.5`
- Node.js version: `12.18.1`
- Operating System: `Linux Ubuntu 18.04.1`

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and **I wouldn't even know how to start.**

**Comment by HsinHeng** [comment]
> ## Issue Description
> `upsert()` method in `sequelize` does not increment value when it updates using `sequelize.literal()`, it only modifies it.
> 
> ### What are you doing?
> In Sequelize with a MySQL Database I am using upsert() to insert a new row if it doesn't exist or increment one of its field values by some other value if it exists.
> 
> Inserting works fine but when the value gets updated it is not getting incremented but completely updated
> 
> ```
> let x = 5;
> 
> OrderDetails.upsert({ 
>    menuItemId: 1234, 
>    orderId: 4321, 
>    quantity: sequelize.literal((`quantity + ${x}`)
> })
> ```
> 
> This results in this query:
> 
> ```
> INSERT INTO `OrderDetails` (`menuItemId`,`orderId`,`quantity`,`createdAt`,`updatedAt`) VALUES (?,?,quantity + 5,?,?) 
> ON DUPLICATE KEY UPDATE `menuItemId`=VALUES(`menuItemId`),`orderId`=VALUES(`orderId`),`quantity`=VALUES(`quantity`),`updatedAt`=VALUES(`updatedAt`);
> ```
> 
> So if for example the previous value was `10` then after the query the updated value will be `5` instead of `15`.
> 
> My guess is that there is a kind of bug in Sequelize when using `upsert()` with `sequelize.literal()`. Apparently, it is only recognized in the insertion and not in the update.
> 
> **_NOTE:_** This obviously **works** if I use `update()` with `sequelize.literal()`
> 
> ### What do you expect to happen?
> The specified field should be incremented instead of completely modified and replaced with the value
> 
> ### What is actually happening?
> If the previous value in my table was `10` then after executing the query the updated value will be `5` instead of `15`.
> 
> ### Additional context
> None.
> 
> ### Environment
> * Sequelize version: `6.3.5`
> * Node.js version: `12.18.1`
> * Operating System: `Linux Ubuntu 18.04.1`
> 
> ## Issue Template Checklist
> ### How does this problem relate to dialects?
> * [x]  I think this problem happens regardless of the dialect.
> * [ ]  I think this problem happens only for the following dialect(s):
> * [ ]  I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX
> 
> ### Would you be willing to resolve this issue by submitting a Pull Request?
> * [ ]  Yes, I have the time and I know how to start.
> * [ ]  Yes, I have the time but I don't know how to start, I would need guidance.
> * [ ]  No, I don't have the time, although I believe I could do it if I had the time...
> * [x]  No, I don't have the time and **I wouldn't even know how to start.**

you can reference my comment [here](https://github.com/sequelize/sequelize/issues/12807#issuecomment-889240489).
