### ISSUE TITLE
Model associations between 2 tables in 2 databases with different schemas

### ISSUE THREAD

**Issue by AaronMcCloskey** [sequelize/sequelize#12839]
## Issue Description

I have 2 different Databases, with different Schemas. I am able to connect to both databases successfully.

My problem comes when trying to make associations between a table in one Database to another table in a different Database?

I've updated the `models/index.js` file a little that gets generated when running `sequelize init`

#### models/index.js ####
```
'use strict';

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const envVars = require("../config/config");
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config1 = envVars.default[env];
const config2 = envVars.default["openx"];
const db = {};

const config = { ...config1, ...config2 };

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    const model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

Currently when I make a request to the server I get an error like;

```
 {
    "code": "ER_NO_SUCH_TABLE",
    "errno": 1146,
    "sqlState": "42S02",
    "sqlMessage": "Table 'openx.users' doesn't exist",
     "sql": "SELECT `id`, `name`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`id` = 1;"
 }
```

Which is correct, there is no table by that name in the `openx` database.

Let's say that I have a model `Model1.js` that references a table in the table for the `config1` connection config and another model `Model2.js` that references a table in the table for the `config2` connection config.

How can I best define that `Model1.js` uses `config1` and `Model2.js` uses `config2` while allowing me to associate the 2 models by a `foreignKey`? For example...

```
Model1.associate = (models) => {
    Model1.hasMany(models.Model2, {
        as: 'activities',
        foreignKey: 'userId'
     });
}

Model2.associate = (models) => {
    Model2.belongsTo(models.Model1, {
        as: 'user',
        foreignKey: 'userId'
     });
}
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): MySQL
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by AaronMcCloskey** [comment]
Solution was to add

`sequelize .dialect.supports.schemas = true;` after initializing a new Sequelize connection

Then in a model, define the database schema in the options

`{ schema: 'openx' } `

**Comment by LorenzoVianello** [comment]
Hi, i'm fancing the same situation.
I've a MYSQL db and a MSSQL db, and 'iv to reach a table from the 2nd one.
The firts is in my localhost, and the other is in a server on my work's network, reached by a DB instance of Sequelize, through IP address, db name, table name and credentials.
I treid to add the dialect support and the schema name, but it's still trying to find the table inside the 1st website.
Can I've your help?
THX
