### ISSUE TITLE
Insert additional field values in junction table

### ISSUE THREAD

**Issue by cybercoder** [sequelize/sequelize#12837]
as described in ```sequelize``` documentation [here][1],

```Foo.belongsToMany(Bar, { through: Baz })```
then there is a method to insert into junction table:

```fooInstance.addBars([5,4])```

It will insert into ```Baz``` junction table two fields: ```FooId,BarId```.
But i need to insert another field value too. sth like this:

```fooInstance.addBars([{BarId: 5, otherField:'xxx'}, ...]```

Is this supporting?

  [1]: https://sequelize.org/master/manual/assocs.html

**Comment by 1Luc1** [comment]
+1
