### ISSUE TITLE
Timeout during migration

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#12832]
## Issue Description

I had a hell of a time trying to process a migration that takes a long time to execute. It basically didn't complete because of a timeout. Is there any way to change a timeout for a single migration only? 

Write here.

Perhaps add to the documentation?

**Comment by lacom** [comment]
@mschipperheyn I've run into this with a long-running `UPDATE` command in a migration. I was able to get around it by batching the update into smaller chunks.

**Comment by leonardoResendeLima** [comment]
I was able to increase the timeout for the sequelize-cli on the **config.js** file.

This config is specific for the MSSQL database, with the extra (confusing) object options.

```
module.exports = {
    local: {
        username: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_NAME,
        host: process.env.DB_HOST,
        dialect: "mssql",
        dialectOptions: {
            options: {
                requestTimeout: 50000,
            },
            ssl: {
                rejectUnauthorized: false
            }
        },
    }
```

**Comment by a7mdRadwan** [comment]
> I was able to increase the timeout for the sequelize-cli on the **config.js** file.
> 
> This config is specific for the MSSQL database, with the extra (confusing) object options.
> 
> ```
> module.exports = {
>     local: {
>         username: process.env.DB_USER,
>         password: process.env.DB_PASS,
>         database: process.env.DB_NAME,
>         host: process.env.DB_HOST,
>         dialect: "mssql",
>         dialectOptions: {
>             options: {
>                 requestTimeout: 50000,
>             },
>             ssl: {
>                 rejectUnauthorized: false
>             }
>         },
>     }
> ```

Is it possible to pass this option in the CLI command arguments?
