### ISSUE TITLE
PostgreSQL doesn't  handle not found rows correctly when looking by UUID.

### ISSUE THREAD

**Issue by Classy-Bear** [sequelize/sequelize#12831]
## UUID when not found throws an error
Postgres returns an error if the UUID doesn't exist:
```bash
ERROR:  invalid input syntax for type uuid: "893e434e-53cf-4e95-8b7e-e785ae126d0"
```
More on that [here](https://stackoverflow.com/questions/46433459/postgres-select-where-the-where-is-uuid-or-string). Meanwhile the work around is using a raw query (not tested).
### What are you doing?
<details>
<summary>JS code -> Model</summary>
<br>

```js
const { DataTypes } = require('sequelize');
const databaseConfig = require('../config/databse');
module.exports = databaseConfig.define('chat_user', {
  chatUserUuid: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  chatUserUser: {
    type: DataTypes.STRING,
    allowNull: false,
  },
});
```
</details>
<details>
<summary>JS code -> Function consuming the table</summary>
<br>

```js
const userModel = require('../../models/Users');
async function getUserByID(req, res) {
  const { id } = req.params;
  try {
    const user = await userModel.findOne({ where: { chatUserUuid: id } });
    if (!user) {
      return res.status(404).json({ msg: 'User doesn't exist.', id });
    }
    const { chatUserUuid, chatUserUser } = user;
    return res.json({ id: chatUserUuid, user: chatUserUser });
  } catch (err) {
    return error(res, err);
  }
}
```
</details>
<details>
<summary>JS code -> Sequelize Config</summary>
<br>

```js
const { Sequelize } = require('sequelize');
const database = 'postgres://postgres@localhost:5432/postgres';
const timestamps = false;
const underscored = true;
const freezeTableName = true;
const options = {
  define: {
    timestamps,
    underscored,
    freezeTableName,
  },
};
module.exports = new Sequelize(database, options);
```
</details>
<details>
<summary>Sequelize error</summary>
<br>

```json
"err": {
"name": "SequelizeDatabaseError",
"parent": {
"length": 108,
"name": "error",
"severity": "ERROR",
"code": "22P02",
"position": "148",
"file": "uuid.c",
"line": "137",
"routine": "string_to_uuid",
"sql": "SELECT \"chat_user_uuid\" AS \"chatUserUuid\", \"chat_user_user\" AS \"chatUserUser\" FROM \"chat_user\" AS \"chat_user\" WHERE \"chat_user\".\"chat_user_uuid\" = 'sajkjsak';"
},
"original": {
"length": 108,
"name": "error",
"severity": "ERROR",
"code": "22P02",
"position": "148",
"file": "uuid.c",
"line": "137",
"routine": "string_to_uuid",
"sql": "SELECT \"chat_user_uuid\" AS \"chatUserUuid\", \"chat_user_user\" AS \"chatUserUser\" FROM \"chat_user\" AS \"chat_user\" WHERE \"chat_user\".\"chat_user_uuid\" = 'sajkjsak';"
},
"sql": "SELECT \"chat_user_uuid\" AS \"chatUserUuid\", \"chat_user_user\" AS \"chatUserUser\" FROM \"chat_user\" AS \"chat_user\" WHERE \"chat_user\".\"chat_user_uuid\" = 'sajkjsak';"
}
```
</details>

### What do you expect to happen?

Sequelize returning null if no rows were returned.

### What is actually happening?

Sequelize throws an error.

### Environment

- Sequelize version: sequelize@5.21.12
- Node.js version: v12.14.0
- Operating System: macOS 10.13.6
- If TypeScript related: TypeScript version: not using

**NOTE**: I also upgraded PostgreSQL to see if this was fixed in future versions, 12.4 -> 13.0 and nothing happen.

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): PostgreSQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Also I haven't contribute to this package before so I don't know if this is enough information, if you need any other details let me know!

**Comment by Spekpannenkoek** [comment]
Your example UUID isn't valid: in `893e434e-53cf-4e95-8b7e-e785ae126d0`, the last grouping should have 12 characters, but it has 11 (`'e785ae126d0'.length === 11`).

You get the same error as in your sample code (`WHERE "chat_user"."chat_user_uuid" = 'sajkjsak'`) because, just like `sajkjsak`, Postgres can't convert the value to a valid UUID.

You could adapt the StackOverflow answer to something 'Sequelize-like'. First define the custom function with a raw query, then use regular non-raw queries: with [`sequelize.fn()`](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#static-method-fn): `{ where: chat_user_uuid: sequelize.fn('uuid_or_null', 'sajkjsak') }`.

**Comment by Classy-Bear** [comment]
Thanks, I didn't know UUID has to be 12 chars long.  One more question: When you refer to a custom raw query function, do you refer to [this](https://www.postgresql.org/docs/current/functions.html)? I don't know SQL in depth that's why I ask.

**Comment by Spekpannenkoek** [comment]
Only the last grouping in a typical representation of a UUID is 12 characters. It's 8-4-4-4-12, for a total of 32 hexadecimal characters, separated by dashes. Your example was 8-4-4-4-11, missing one.

You can define the custom function from the StackOverflow answer you linked like so:

```javascript
await sequelize.query(`
  CREATE OR REPLACE FUNCTION uuid_or_null(str text)
  RETURNS uuid AS $$
  BEGIN
    RETURN str::uuid;
  EXCEPTION WHEN invalid_text_representation THEN
    RETURN NULL;
  END;
  $$ LANGUAGE plpgsql;
`);
```
It is referred to as a 'raw query' in the Sequelize documentation because Sequelize will not do any escaping, casting or parsing the output value of this function and it's written in SQL.

You can use this function in a regular query like so:

```javascript
await ChatUser.findOne({
  where: { chatUserUuid: sequelize.fn('uuid_or_null', 'invalid') }
}),
```
`sequelize.fn` is needed because otherwise the query would be this behind the scenes:

`WHERE "chatUserUuid" = "uuid_or_null('invalid')"`

Rather than:

`WHERE "chatUserUuid" = uuid_or_null('invalid')`

You can test the custom function yourself:

```javascript
const { strict: assert } = require('assert');
// Include your database connection, etc.

(async () => {
  await assert.rejects(
    ChatUser.findOne({
      where: { chatUserUuid: 'invalid' }
    }),
    'Querying for "invalid" SHOULD reject'
  );

  await assert.doesNotReject(
    ChatUser.findOne({
      where: { chatUserUuid: sequelize.fn('uuid_or_null', 'invalid') }
    }),
    'Querying for "invalid" with the custom function wrapped around it SHOULD NOT reject'
  );

  const chatUserUuid = "893e434e-53cf-4e95-8b7e-e785ae126d0F"; // added an F to the end.
  assert.doesNotReject(
    ChatUser.findOne({
      where: { chatUserUuid: sequelize.fn('uuid_or_null', chatUserUuid) }
    }),
    'Querying for a uuid with the custom function wrapped around it SHOULD NOT reject'
  );
})();

```

**Comment by Classy-Bear** [comment]
Thanks for the example! It's much clearer what I have to do now. Feel free to close this issue. Is there a way to identify when it is a database error or Sequelize error? I just feel dumb after opening this issue since it was a database error and not a Sequelize one. Other databases that I have tested return `0 rows` instead, that's why I also thought there was a problem with Sequelize managing Postgres UUID.

**Comment by Classy-Bear** [comment]
Closing this issue due to awesome help :)
