### ISSUE TITLE
Feature Request: Optionally turn off "RETURNING *" behavior for record inserts

### ISSUE THREAD

**Issue by aaronbean** [sequelize/sequelize#1284]
This seems to be an option in updates (in query-generator.js):
```
if (this._dialect.supports['RETURNING'] && (options.returning || options.returning === undefined)) {
```
That same ability is not afforded to inserts.

**Comment by sushantdhiman** [comment]
Now we support it https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1751,

Implemented in https://github.com/sequelize/sequelize/pull/1624
