### ISSUE TITLE
Typescript: 'belongsToMany' fails with custom 'through' Model if we provide TModelAttributes

### ISSUE THREAD

**Issue by LostInCode404** [sequelize/sequelize#12842]
## Issue Description

When I try to create many-to-many relation using custom 'through' Model, it fails with an error if we use TModelAttributes. Providing scaled down examples below.

Please note that the association code works fine if I don't give `TModelAttributes`, so there is likely no issue with the association reference fields in junction table or the way the association is defined. However, I want to use `TModelAttributes` for better type checking in `init` call to the model.

### What are you doing?

User model defined this way:
```ts
interface UserAttributes {
    id: number;
    name: string;
    ...
}

class User extends Model<UserAttributes> implements UserAttributes {
    ...
}
```

Project model defined this way:
```ts
interface ProjectAttributes {
    id: number;
    name: string;
    ...
}

class Project extends Model<ProjectAttributes> implements ProjectAttributes {
    ...
}
```

The junction model, UserProject is defined this way:
```ts
interface UserProjectAttributes {
    id: number;
    customField: string;
    ...
}

class UserProject extends Model<UserProjectAttributes> implements UserProjectAttributes {
    ...
}
```

Defining associations this way:
```ts
User.belongsToMany(Project, { through: { model: UserProject } });
Project.belongsToMany(User, { through: { model: UserProject } });
```

### What do you expect to happen?

I expect the code to compile.

### What is actually happening?

It does not compile. I get an error like this:
```ts
Type 'typeof UserProject' is not assignable to type 'string | typeof Model'.
  Type 'typeof UserProject' is not assignable to type 'typeof Model'.
    Types of parameters 'values' and 'values' are incompatible.
      Type 'TCreationAttributes | undefined' is not assignable to type 'UserProjectAttributes | undefined'.
        Type 'TCreationAttributes' is not assignable to type 'UserProjectAttributes | undefined'.
          Type '{}' is not assignable to type 'UserProjectAttributes'.
            Type 'TCreationAttributes' is not assignable to type 'UserProjectAttributes'.
              Type '{}' is missing the following properties from type 'UserProjectAttributes': id, customField <other field names here> and 10 more.ts(2322)
```

### Additional context

Please note that the association code works fine if I don't give `TModelAttributes`, so there is likely no issue with the association reference fields in junction table or the way the association is defined. However, I want to use `TModelAttributes` for better type checking in `init` call to the model.

I have also tried the documentation way of making models using different creation attributes, but that also does not help:
```ts
interface UserAttributes {
    id: number;
    name: string;
    ...
}
interface UserCreationAttributes extends Optional<UserAttributes, "id"> {}

class User extends Model<UserAttributes, UserCreationAttributes> implements UserAttributes {
    ...
}
```

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 14.13.1 
- Operating System: Debian 10
- If TypeScript related: TypeScript version: 3.9.7

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ehrensteins** [comment]
I'm experiencing exactly the same issue.

- TS version:  4.0.5
- sSequelize version: 6.3.5
- Sequelize types version: 4.28.9
- OS: Ubuntu 18.04
- Node version: v14.15.0

**Comment by Brobin** [comment]
Same issue

- TS: 4.1.3
- Sequelize: 6.4.0

**Comment by papb** [comment]
Hi @LostInCode404 and everyone else, sorry to take long!
