### ISSUE TITLE
Sequelize vectorized logo

### ISSUE THREAD

**Issue by mondeja** [sequelize/sequelize#12844]
## Issue Description

This is a question and/or feature request about documentation/branding. I can see that you have shared the Sequelize logo in raster PNG format. Do you have the vectorized version of the logo? If not, can this be created and shared.

Thanks for this library!

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sdepold** [comment]
Hey @mondeja,

would SVG suffice?
