### ISSUE TITLE
Reason for so many Pull Requests.

### ISSUE THREAD

**Issue by fateslayer** [sequelize/sequelize#12846]
I was thinking of fixing issues but saw 115 pull requests pending here. I just had a few questions regarding that.

1. Why there are so many pull requests pending?
2. If I fix some issues, will my pull requests get merged or not?
3. Is this project still suitable for production app use?

Thanks for making such an amazing project, I know most of us can't work on it full-time but if just a few of us got together and solved just 1 issue every day, we could get this project maintained again.

**Comment by papb** [comment]
Hello!

> I was thinking of fixing issues but saw 115 pull requests pending here. I just had a few questions regarding that.
> 
>     1. Why there are so many pull requests pending?

Unfortunately because I (and other maintainers) have been very busy.

>     2. If I fix some issues, will my pull requests get merged or not?

Yes, definitely.

>     3. Is this project still suitable for production app use?

It is, absolutely.

> Thanks for making such an amazing project

:heart: 

> I know most of us can't work on it full-time but if just a few of us got together and solved just 1 issue every day, we could get this project maintained again.

Indeed, *none* of us can work on it full-time. I am assigned myself to several issues but haven't had time to look at them properly.

By the way, there is another reason for things being particularly slower currently - we are in the middle of a large code refactor and ideally the best scenario would be getting that done and release a v7 as a milestone (without breaking changes though) in order to be able to start fixing issues with a more maintainable codebase.

**Comment by papb** [comment]
And thank you for your interest! I look forward for more PRs from you :+1: 

I often think about the many things that must be done for Sequelize, rest assured I am paying attention, just haven't had the time really.

**Comment by fateslayer** [comment]
Thank you so much for maintaining this project. You have cleared all of my doubts. I will do my best and try to fix as many issues as I can.
I just have one more question regarding the flow of the project. I was thinking if there's a small explanation of project structure and flow of information then that'll be very helpful for beginners like me to contribute. Otherwise almost everyone new has to figure it out by themselves.

**Comment by papb** [comment]
> I was thinking if there's a small explanation of project structure and flow of information then that'll be very helpful for beginners like me to contribute. Otherwise almost everyone new has to figure it out by themselves.

Unfortunately, no... Sorry... What we have is a guide on how to [contribute / setup local development](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md). I also have a [SSCCE repository](https://github.com/papb/sequelize-sscce) that anyone can use to quickly test things out on any supported dialect. Feel free to use it.

If you want, I would be happy to accept a PR with some explanation of the project structure and flow of information. Perhaps you can write it while you learn. Only if you really like the idea :+1:

**Comment by fateslayer** [comment]
Thanks for the SSCCE link, I will think about it once I have learned it myself.
