### ISSUE TITLE
underscored option in sequelize constructor does not work

### ISSUE THREAD

**Issue by RossHathaway** [sequelize/sequelize#12847]
## Issue Description
Setting `underscored` option globally should make the names of the new column titles in the database snake-cased, but it does not.

### What are you doing?
This is where I set the option
```js
const sequelize = new Sequelize('postgres://username:password@127.0.0.1/db_name', {
    define: {
        underscored: true,
    }
})
```

I used sequelize-cli to `init` and created a model and migration by running 
```
sequelize-cli model:generate --name User --attributes firstName:string,lastName:string,email:string
```
And then I ran `sequelize-cli db:migrate` to put the data in the database. 

**As far as I can tell, SSCCE does not have a way to query the database without sequelize, so it is not relevant for this issue** 

### What do you expect to happen?
When I connect to the postgres database with psql, the column names in "Users" should be `id | first_name | last_name | email | created_at | updated_at`.

### What is actually happening?
 The column names in postgres are `id | firstName | lastName | email | createdAt | updatedAt`.

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 12.18.4 
- Operating System: MacOS Catalina

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using Postgres, with connector library (node-pg) version 8.5.1 and database version 12.4

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I might have the time to fix it if you identify the problem and maybe provide a general idea of some possible solutions, but I don't have time to look for the problem.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
`sequelize-cli model:generate --underscored  --name User ...` should work.

When Sequelize CLI [creates the options object for the new model](https://github.com/sequelize/cli/blob/master/src/core/yargs.js#L22), it adds a value for the option `underscored`, which comes from a [CLI argument](https://github.com/sequelize/cli/blob/master/src/core/yargs.js#L64) that has a default value of `false`. 

Because `Sequelize.Model.constructor` gets an explicit value (which as stated is `false` by default), rather than `undefined`, it doesn't look at the value you've passed to `Sequelize.constructor.options`.

**Comment by RossHathaway** [comment]
Thanks @Spekpannenkoek, I guess it is not a bug then. Nice to have your help!

**Comment by RenatoLopes771** [comment]
> `sequelize-cli model:generate --underscored --name User ...` should work.
> 
> When Sequelize CLI [creates the options object for the new model](https://github.com/sequelize/cli/blob/be5b445619b59115f36f06507bfff7aa87528db8/src/commands/model_generate.js#L6), it adds a value for the option `underscored`, which comes from a [CLI argument](https://github.com/sequelize/cli/blob/be5b445619b59115f36f06507bfff7aa87528db8/src/core/yargs.js#L64) that has a default value of `false`.
> 
> Because `Sequelize.Model.constructor` gets an explicit value (which as stated is `false` by default), rather than `undefined`, it doesn't look at the value you've passed to `Sequelize.constructor.options`.
> 
> Edit (2): The `--underscored` argument is [only used for createdAt and modifiedAt](https://github.com/sequelize/cli/blob/be5b445619b59115f36f06507bfff7aa87528db8/src/helpers/migration-helper.js#L11) and not for the table as a whole, because there's [no reference to the variable `underscored` in this file](https://github.com/sequelize/cli/blob/be5b445619b59115f36f06507bfff7aa87528db8/src/assets/migrations/create-table.js). The solution is probably to pass `--underscored` for the column names you have no influence over and explicitly name the others: `--underscored --attributes first_name:string,last_name:string,email:string`

What about other global options? For instance, there's no timestamps command. In fact for some reason there's only the underscore command. 

Do you know what's the best approach for setting these options when working with sequelize CLI without having to manually go and put timestamps on each model I create.
