### ISSUE TITLE
How do I access an existing table in a remote database without defining its schema in my app

### ISSUE THREAD

**Issue by 12sam12** [sequelize/sequelize#12853]
## Issue Description

In the docs Im unable to find the suitable way to get a handle on a table in a remote database. Only way currently (as mentioned in the docs) to use the models ORM way of syntax to query or manipulate data in a remote database seems to be to first define its schema in my app itself and then persist it first to get a hold of it so that we can query the existing data. I basically do not want to use sequelize.models.query method and mention my sql query explicitly like 

`sequelize.models.query("SELECT * FROM <tablename>" )`

and run it. But rather want to use the ORM methods of querying the data something like

```
await <table_name>.findAll({
        where: {
          userid: id
        }
});
```

### What was unclear/insufficient/not covered in the documentation

From the docs I get to see the only method to query data is first to define the tables and then query using the findall or any kind of methods.

### If possible: Provide some suggestion on how we can enhance the docs

Im expecting some method of loading the existing tables in the database and expose the commonly available and other sequelize methods to query the existing tables.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by kinothUI** [comment]
I would probably guess sequelize-cli is what you are looking for
