### ISSUE TITLE
bulkDelete cascade not working.

### ISSUE THREAD

**Issue by benfiratkaya** [sequelize/sequelize#12856]
## Issue Description
I have a seed and I use bulkDelete with query interface. It's okay but I need to truncate table. I set truncate: true options and I catch a error:
Cannot truncate a table referenced in a foreign key constraint (`vexus_panel`.`visits`, CONSTRAINT `visits_ibfk_4` FOREIGN KEY (`countryId`) REFERENCES `vexus_panel`.`countries` (`id`))
And then I enable cascade like this: cascade: true but still not working 

### What are you doing?
**My code**:
```
  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete("Countries", null, {
      truncate: true,
      cascade: true,
    });
  },
```
**Error:**
ERROR: Cannot truncate a table referenced in a foreign key constraint (`vexus_panel`.`visits`, CONSTRAINT `visits_ibfk_4` FOREIGN KEY (`countryId`) REFERENCES `vexus_panel`.`countries` (`id`))

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 14.15.0 
- Operating System: Windows 10
- Dialect: MySQL

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using MySQL with connector library version XXX and database version 10.4.14-MariaDB

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by DewangS** [comment]
in my case I even don't have any dependent records and I am getting an error on dependency i.e. trying to remove all records from the seed\master table when all other dependent data tables are empty. Also the restartIdentity doesn't reset the auto sequence.

**Comment by Kibria7533** [comment]
await queryInterface.bulkDelete('modules', null, {
      truncate: true,
      cascade: true,
    }, { primaryKeys:[], primaryKeyAttributes:[] });
