### ISSUE TITLE
Question about CLI : target one of several seed files

### ISSUE THREAD

**Issue by YoannBuzenet** [sequelize/sequelize#12869]
### What was unclear/insufficient/not covered in the documentation

Hello ! And thank you for Sequelize, I love it !
I searched how to target one of various specific seed file in my script, but I couldn't find how to do so. The doc says this : 
`sequelize db:seed                           Run specified seeder`
But I can't understand what I should write after that. Could you show me an example of how to target two seed files please ?

### If possible: Provide some suggestion on how we can enhance the docs

It would be great to add this info in the FAQ of the CLI.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [X ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Thank you for your time and your work !!

**Comment by YoannBuzenet** [comment]
Hey, I found a way to do it, group seeds by folder depending on my testing scenario, and just indicate the path in my command like this : 

Sequelize db:seed:all --seed /path/to/location

And I have several script with different seeds.

Could I add a sentence like this in the FAQ ? For the future in the same case ?

Thank you anyway. Love Sequelize !

**Comment by Spekpannenkoek** [comment]
If you run the following, you get details on the sub-command `db:seed`:

```bash
$ sequelize --help db:seed

[...]

Options:
  --version          Show version number                                                                 [boolean]
  --help             Show help                                                                           [boolean]
  --env              The environment to run the command in                       [string] [default: "development"]
  --config           The path to the config file                                                          [string]
  --options-path     The path to a JSON file with additional options                                      [string]
  --migrations-path  The path to the migrations folder                            [string] [default: "migrations"]
  --seeders-path     The path to the seeders folder                                  [string] [default: "seeders"]
  --models-path      The path to the models folder                                    [string] [default: "models"]
  --url              The database connection string to use. Alternative to using --config files           [string]
  --debug            When available show various debug information                      [boolean] [default: false]
  --seed             List of seed files                                                                    [array]
```

So you should be able to use `sequelize db:seed --seed one-of-your-file-names another-of-your-files`.

**Comment by YoannBuzenet** [comment]
Didn't see it could be a list, my bad. Thank you, I'll close this issue.
