### ISSUE TITLE
Cannot read property 'Client' of undefined `{dialect= 'postgres', native=true}` for Postgres sslmode=require

### ISSUE THREAD

**Issue by maohieng** [sequelize/sequelize#12864]
- sequelize: v6.3.5
- nodejs: v12
- Postgres DB: v12
- Sequelize config:
```
production: {
    username: DO_DB_USER,
    password: DO_DB_PASS,
    database: DO_DB_NAME,
    host: DO_DB_HOST,
    port: DO_DB_PORT,
    // a flag for using a native library or not.
    // in the case of 'pg' -- set this to true will allow SSL support
    // - default: false
    native: true,
    dialect: 'postgres'
  }
```

```
Sequelize: Unable to connect to the database: TypeError: Cannot read property 'Client' of undefined
at connection (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:126:39)
at new Promise (<anonymous>)
at ConnectionManager.connect (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:123:30)
at ConnectionManager._connect (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:61)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async /usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
at async ConnectionManager.getConnection (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
at async /usr/src/app/node_modules/sequelize/lib/sequelize.js:613:26
```

Is it a library bug or any advice for workaround? 
Thank you,

**Comment by Spekpannenkoek** [comment]
When you installed Sequelize, you also installed the peer dependency `pg`. This is a Postgres driver written in JavaScript and is used as the default bindings.

When you set `native: true`, the [`pg` library lazily loads _its_ peer dependency, the `pg-native` library](https://github.com/brianc/node-postgres/blob/0b9bb349dcb10f6473737001062082b65efc74be/packages/pg/lib/index.js#L32) _if installed_. The `pg` library does not give a warning or error if this is not the case:

```javascript
node -p 'require("pg").native === null'
// returns true
```

It seems Sequelize does not check if something other than `null` is returned, either.

Run `npm install pg-native --save`.

```javascript
node -p 'require("pg").native === null'
// returns false
```

You will need to [install some dependencies](https://www.npmjs.com/package/pg-native) for pg-native.

**Comment by maohieng** [comment]
Thank you. I also was messing up with my `node_modules`.
