### ISSUE TITLE
I need help working with nested objects

### ISSUE THREAD

**Issue by bediu** [sequelize/sequelize#12863]
I'm sorry if this doesn't fit any category, but I've posted on stackoverflow 
https://stackoverflow.com/questions/64970197/find-by-nested-object-value-in-sequelize-with-postgres

I've asked on reddit and have 0 replies, and I've been googling for 2 days now. My whole project is at halt because there are no answers how to work with arrays of nested objects. 

sequelize: v6
pg

---

I'm trying to work with arrays of objects but I just can't seem to find a proper way to do it and sequelize doesn't really explain how ARRAYs and JSONB work together.

Let's say I have  a table called `Form`, this table has a column called `collaborators`, the typeof this column is `DataType.ARRAY(DataType.JSONB)`  

The data of the `collaborators` column is like this:   
```
[{
    "id": 1,
    "name": "John"
},
{
    "id": 2,
    "name": "Angela"
},
{
    "id": 3,
    "name": "Joe"
}]
```
There's two things which I want to learn how to do with sequelize: 

Find all `Form`s where `collaborator.name === "joe"`

Edit id of collaborator where `collaborator.name === "joe"`

(If there is a guide on how to work with even more nested objects then that would help as well.)

**Comment by Spekpannenkoek** [comment]
I don't have time to write a full StackOverflow worthy answer nor to set up an example environment. If you want a faster and/or higher chance of a response to a question, ideally you'd have [a running example](https://github.com/papb/sequelize-sscce#readme) and explain what you've tried and where things go wrong—make it as easy as can be for people to answer your question. :-)

Not quite sure why you're doing `DataType.ARRAY(DataType.JSONB)`, JSONB supports arrays. If you change it to just `DataType.JSONB`, then you should be able to query with:

```javascript
{ 
  collaborators: { 
    [Op.contains]: { 
      name: 'joe',
    },
  },
}
```
(After changing datatypes you might need to truncate or re-insert data into the affected column)

[This SO question](https://stackoverflow.com/questions/51025837/sequelize-find-in-json-array) is not quite the same as what you're asking but will be helpful.
