### ISSUE TITLE
DateTime saving incorrect Time

### ISSUE THREAD

**Issue by lukegalea16** [sequelize/sequelize#12860]
## Issue Description

Whenever I save a date time entry the time is always saved one hour 'earlier' (i.e. minus 1 hour). For example I am getting the following time from Moment JS (2020-11-24T16:35:14+01:00). When saving this in my DB, it is being saved as '2020-11-24T15:35:14+01:00' instead. I tried configuring the timezone in dialectOptions but don't know what else to try.

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by soryy708** [comment]
How did you get the `2020-11-24T15:35:14+01:00` timestamp?
Is it possible that the software you used to get it automatically converted it to local timezone?
