### ISSUE TITLE
Options parameter gets mutated between uses

### ISSUE THREAD

**Issue by roikoren755** [sequelize/sequelize#12868]
## Issue Description
First of all, I'd like to thank the contributors and maintainers of this library. We are using Sequelize heavily, talking with a PostgreSQL database, across 5 different Node.JS services, each with its own schema.

Starting with v5.13.0, and as recently as v6.3.5, we are having issues with scopes defined in associations. Prior to that version (tested and verified with v5.12.3), when using, for example, Foo's addBars method, everything will come out ok. Since v5.13.0 (and tested and verified with versions between v5.13.10 and v6.3.5, inclusive), the updated records are missing the field set in the scope, inside the association definition.

### What are you doing?
The following description has the names of models and fields changed, for simplicity.

We have a Foo model, with a hasMany association to a Bar model. When defining this association, we also add a scope, to set a field, called 'someField', to 'foo', on Bars added to a Foo. This field is in camelCase in our code, but snake_case in the db

One of our services, on request, finds all Bars in the DB that match a select query, duplicates them, omitting the scoped field, and inserts the new records to the DB. Then, the service creates a new Foo record, and adds the newly created Bars to that Foo, using `foo.addBars(bars)`.

**Here is the link to the SSCCE for this issue:** LINK-HERE 
(I haven't been able to create a simple reproduction of this just yet, but I am still working on it. Will update this issue when I manage that).

### What do you expect to happen?
The update query for the Bars should be `UPDATE "bars" SET "some_field"=$1,"updated_at"=$2 WHERE id IN (...)`.
The rows in the DB should have some_field set to the value defined in the scope inside the association.

### What is actually happening?
The update query for the Bars comes out as `UPDATE "bars" SET "updated_at"=$1 WHERE id IN (...)`.
The rows in the DB should have some_field set to NULL.

### Additional context
I tried to pinpoint the change, between v5.12.3 and v5.13.0, that led to the issue I am describing, and I think I found the specific change that causes it.

In #11281, the library switched some places that used it's custom Utils.cloneDeep method to simpler `Object.assign({}, ...)` calls. One such change is in the select method in the query-interface.js file (was in lib, moved to src/dialects/abstract, and the line has changed since then to `{ ...options, ... }`, but the issue remains). When I revert that specific change, so it uses Utils.cloneDeep again, everything works perfectly, both in v6.3.5 and in v5.13.0.

We had similar issues in our repositories, where using `Object.assign({}, ...)` or using `immutability-helper` left some of the nested fields as references to the original, and updating the result of the assign altered the original as well. It seems to be a similar case in this issue.

I couldn't understand why that would cause the issue, and on further investigation, I saw that inside the update method, defined on the Model class, the `build.validate` function was passed an options parameter. This parameter changes between v5.12.3 and v5.13.0, specifically the `fields` field on the options object.

As you can see below (with the original fields and models), the fields passed to the validate function contain one field written in snake_case, and the rest in camelCase. This causes the resulting attributes.dataValues to not contain the scoped field (some_field in the simplification, asset_type in our actual code), meaning that line 3079 in model.js overwrites values, dropping the field we wanted to add.

I'm not sure where in the library is that fields array accessed or changed, prior to getting to the update method, and I couldn't find any obvious places where it might happen...

```
{
  transaction: Transaction {
    sequelize: Sequelize {
      options: [Object],
      config: [Object],
      dialect: [PostgresDialect],
      queryInterface: [PostgresQueryInterface],
      models: [Object],
      modelManager: [ModelManager],
      connectionManager: [ConnectionManager]
    },
    savepoints: [],
    _afterCommitHooks: [],
    options: { type: 'DEFERRED', isolationLevel: null, readOnly: false },
    parent: undefined,
    name: undefined,
    id: '0c535f38-33e0-42e7-98e2-8d7b557f6054',
    connection: Client {
      ...
    }
  },
  where: { id: [ 2274 ] },
  validate: true,
  hooks: true,
  individualHooks: false,
  returning: false,
  force: false,
  sideEffects: true,
  type: 'BULKUPDATE',
  fields: [ 'assetId', 'updatedAt', 'asset_type' ],
  model: Permission,
  skip: [ 'id', 'flag', 'assetType', 'targetType', 'targetId', 'createdAt' ]
}
```

A simple (and verified) fix would be to revert the changes in query-interface.js.

```
    const options = Utils.cloneDeep(optionsArg);
    options.type = QueryTypes.SELECT;
    options.model = model;
    // const options = { ...optionsArg, type: QueryTypes.SELECT, model }; // This is the current lint
```

A more complicated to implement, but what might be a safer solution, would be to update the entire library, to not modify the parameters passed to it, as is often the case (with options and values parameters, for example).

If there is any more information needed, I'd be glad to help. I'm working on writing a test for us, that will verify the sequelize version we are using won't be affected by this issue. Once done, hopefully by early next week, I'll be more than happy to port it over to this library.

### Environment

- Sequelize version: >=5.13.0 
- Node.js version: 13.14.0 
- Operating System: MacOS
- If TypeScript related: TypeScript version: 4.1.2

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by roikoren755** [comment]
On further inspection, it would seem that the affected model's scope is changed between defining it and using it in the update query. It starts off with `this.scope = { assetType: 'folder' };` and ends up with the same object, but with the key in snake_case when used. I'll try and pinpoint the place where that changes...

**Comment by roikoren755** [comment]
Finally got back to this, and I found some more information.

In our usecase, we first of all run Foo.findAll, including Foo.associations.bars as the association and some where clause. When this happens, in model.js, in line 667 (base off of current master), the where clause is changed, and the scope is added, by placing include.association.scope (which equals `{ someField: 'foo'}`) in an array with the original where clause, under an Op.and.

Later on, before actually querying the DB, in line 1490 of abstract/query-generator.js, inside the generateInclude function, a call is made to Utils.mapFinderOptions with the include that has the association. This function calls mapOptionFieldNames in the same utils.js file, which then calls mapWhereFieldNames with the where clause and the Foo model.
After going through the first level of the include's where clause (the Op.and) and the original where clause (before the scope was added), it calls itself with `{ someField: 'foo' }` as the attributes parameter (and Foo as the Model). Line 190 finds the right `rawAttribute`, with `rawAttribute.field === 'some_field' && rawAttribute.fieldName === 'someField'`. Then, line 193 mutates the passed attributes parameter. This goes all the way back to the scope that is defined on the association, which is now mutated to be `{ some_field: 'foo' }`.

From this point, when we try and use the created mixins to addBar on any Foo instance, the scope adds what is an unknown field, which is simply dropped from the UPDATE query.

There are a few fixes I tried that worked, I'll open a PR with one of them, and we can have a discussion on how best to fix this issue there.

**Comment by papb** [comment]
Hello! Great work, thank you very much!

**Comment by zaggino** [comment]
Hi @roikoren755 @papb , after updating today from `6.6.2` to `6.6.4` I run into a bug in our test-suite:

```
SequelizeDatabaseError: column "userId" does not exist
```

Using `git bisect` that lead to the commit https://github.com/sequelize/sequelize/commit/1a16b915ff45ac621a0517aea6c2d86557149500

The previous commit in the tree https://github.com/sequelize/sequelize/commit/39299a63a513c8539c0d9e0171916eeb22ee11aa does not replicate this issue.

As for the details of the code, the failing query looks like this:
```
const p = await db.Participation.findOne({
    where: { userId: user.id, campaignId: campaign.id }
});
```

And Participation model is defined:
```
Participation.init(
    {
      ...
      userId: { field: 'user_id', type: DataTypes.BIGINT, allowNull: false },
      campaignId: { field: 'campaign_id', type: DataTypes.BIGINT, allowNull: false },
      ...
    },
    {
      sequelize,
      name: { singular: 'participation', plural: 'participations' },
      underscored: true,
      timestamps: true,
      paranoid: false,
      tableName: 'participation',
    }
  );
```

I don't have yet time to supply a failing isolated testcase, but this should at the very least be considered a breaking change?

**Comment by roikoren755** [comment]
> Hi @roikoren755 @papb , after updating today from `6.6.2` to `6.6.4` I run into a bug in our test-suite:
> 
> ```
> SequelizeDatabaseError: column "userId" does not exist
> ```
> 
> Using `git bisect` that lead to the commit [1a16b91](https://github.com/sequelize/sequelize/commit/1a16b915ff45ac621a0517aea6c2d86557149500)
> 
> The previous commit in the tree [39299a6](https://github.com/sequelize/sequelize/commit/39299a63a513c8539c0d9e0171916eeb22ee11aa) does not replicate this issue.
> 
> As for the details of the code, the failing query looks like this:
> 
> ```
> const p = await db.Participation.findOne({
>     where: { userId: user.id, campaignId: campaign.id }
> });
> ```
> 
> And Participation model is defined:
> 
> ```
> Participation.init(
>     {
>       ...
>       userId: { field: 'user_id', type: DataTypes.BIGINT, allowNull: false },
>       campaignId: { field: 'campaign_id', type: DataTypes.BIGINT, allowNull: false },
>       ...
>     },
>     {
>       sequelize,
>       name: { singular: 'participation', plural: 'participations' },
>       underscored: true,
>       timestamps: true,
>       paranoid: false,
>       tableName: 'participation',
>     }
>   );
> ```
> 
> I don't have yet time to supply a failing isolated testcase, but this should at the very least be considered a breaking change?

First of all, very sorry to hear that, and I'm willing to work on fixing it.

Are there any queries performed prior to the `Participation.findOne`? In our case, we had some successful queries that mutated the class and lead to other queries breaking.

I see in your configuration that you both provide custom column names to the init method and pass `underscored: true`, which does the same thing. Can you try removing one or the other, see if it changes anything?

**Comment by papb** [comment]
Hi @zaggino, sorry to hear that, hopefully you'll have time to supply a failing isolated testcase soon, so we can work on it.

Thank you very much @roikoren755 for the quick response as well.

> this should at the very least be considered a breaking change?

An accidental breaking change, yes (i.e. a regression), that we must fix asap (but for that we'll have to wait until you or someone else can send the test case).

**Comment by davidgeorgeuk** [comment]
+1 on the regression that @zaggino raised. We're seeing a similar error relating to an underscored column in a failing unit test after updating to `6.6.4` Rolling back the change in commit 1a16b915ff45ac621a0517aea6c2d86557149500 makes the problem go away. I'm going to try to build a simple case for it, but it looks a lot like the same problem.

**Comment by gurpreetatwal** [comment]
Running into a similar issue, in our case it was `Model#destroy` that was failing. It seems like `Model#destroy` is missing a call to some util method that modifes the attribute's key to be the value of `field`. This was working before because some other method (e.g. `findAll`) invoked the method and mutated the model. I'll try digging into a fix tonight, but I was able to put together a test case.


```js
      it('should be able to destory() with no primary key and custom field name', async function () {
        const queryInterface = this.sequelize.getQueryInterface();

        const Event = this.sequelize.define(
          'event',
          {
            user: {
              type: DataTypes.STRING
            },
            eventName: {
              type: DataTypes.STRING,
              field: 'event_name'
            }
          },
          {
            tableName: 'events',
            timestamps: false
          }
        );

        await queryInterface.createTable('events', {
          user: {
            type: DataTypes.STRING
          },
          event_name: {
            type: DataTypes.STRING
          }
        });

        const user = await Event.create({ user: 'testing', eventName: 'surprise!' });
        await user.destroy();
      });
```

**Comment by davidgeorgeuk** [comment]
Big thanks to @gurpreetatwal for that repro. I have created [a sscce for this](https://github.com/papb/sequelize-sscce/pull/179). It looks as though the problem relates specifically to tables with underscored names and no primary key.

When you `fetchAll` with a where option that includes attributes with underscored column names, the generated sql for updates like `save` try to use the camelCase attribute names instead of the underscored column names.

**Comment by davidgeorgeuk** [comment]
I've opened the column not found problem as a new issue.

**Comment by gurpreetatwal** [comment]
Should this patch be reverted until a fix can be put in place? The patch is effectively a breaking change for normal usage
