### ISSUE TITLE
please tell me how to export the data inside sqlite3 to an excel file.

### ISSUE THREAD

**Issue by radiorz** [sequelize/sequelize#12866]
### should i install a thirdpart module to deal with this issue?
such as
- https://github.com/exceljs/exceljs/blob/HEAD/README_zh.md
- https://www.npmjs.com/package/sequelize-import-export
or are there a better way to get it done
### expect: 
- i want to export some data in database outto an excel file.

**Comment by csauvage** [comment]
It's not the right place, you should ask your question on Stackoverflow. 
GH Issues is for bugs or feature request. 

IMO taking a look at `@grapecity/spread-sheets` should help.

Maintainers can close.

**Comment by radiorz** [comment]
thanks anyway. i will go to stackoverflow to look for help /(ㄒoㄒ)/~~

**Comment by radiorz** [comment]
i use exceljs to export the data out to excel . it works!!!
