### ISSUE TITLE
custom field (FK) problem

### ISSUE THREAD

**Issue by mfinity168** [sequelize/sequelize#12876]
### What was unclear/insufficient/not covered in the documentation

reference: https://sequelize.org/master/manual/assocs.html #Customizing the foreign key

**groups table:**
group_id PK
name varchar

**users table:**
uid PK
username varchar

I want to create users table and custom field (FK)
**My Code:**
```
groups.hasMany(users)
users.belongsTo(groups, {
  foreignKey: 'groupid'
})
```

Why users table created 2 field ?
**users table:**
uid PK
username varchar
groupid FK
groupGroupId FK

**Comment by x-yuri** [comment]
By `groupGroupId` you probably mean `GroupId`. If not, there's probably some information missing in your description.

`hasMany()` adds a field `GroupId` to the `users` model, `belongsTo` adds a field `groupid` to the `users` model. Together that amounts to 2 fields. If you need 1 field, make the names match. Either change what you pass to `belongsTo()`, or switch to the [`underscored` naming strategy][a] (plus add the missing underscore).

[a]: https://sequelize.org/master/manual/naming-strategies.html

**Comment by mfinity168** [comment]
Thanks
