### ISSUE TITLE
REF #5757, #5970, #1679

### ISSUE THREAD

**Issue by limyandi** [sequelize/sequelize#12875]
REF #5757, #5970, #1679

My **workaround** is very simple but **it worked for me**:

- Coded my *base model* as always.
- Coded my *child model* using the **same fields and relationships** than the *base model* (I exported a function that returns the fields of the base model so I can reuse them).
- In the migration I use to **create the child model** I've added an `ALTER TABLE` setting the inheritance within a single transaction:
```javascript
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.transaction((transaction) => {
      return queryInterface.createTable('eventRecurrenceRecords', {
        // .. All fiields from parent (recurrenceRecords)
        // Plus this one
        eventId: {
          type: Sequelize.INTEGER,
          allowNull: false,
          references: {
            model: 'events',
            key: 'id'
          },
          onUpdate: 'cascade',
          onDelete: 'cascade'
        }
      }, {
        transaction
      })
        // This is the magic
        .then(() => queryInterface.sequelize.query(`
          ALTER TABLE "eventRecurrenceRecords"
            INHERIT "recurrenceRecords"
        `, { transaction }));
    });
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('eventRecurrenceRecords');
  }
};
```

https://www.postgresql.org/docs/current/static/sql-altertable.html:
> INHERIT parent_table
>
> This form adds the target table as a new child of the specified parent table. Subsequently, queries against the parent will include records of the target table. To be added as a child, the target table must already contain all the same columns as the parent (it could have additional columns, too). The columns must have matching data types, and if they have NOT NULL constraints in the parent then they must also have NOT NULL constraints in the child.
>
> There must also be matching child-table constraints for all CHECK constraints of the parent, except those marked non-inheritable (that is, created with ALTER TABLE ... ADD CONSTRAINT ... NO INHERIT) in the parent, which are ignored; all child-table constraints matched must not be marked non-inheritable. Currently UNIQUE, PRIMARY KEY, and FOREIGN KEY constraints are not considered, but this might change in the future.

_Originally posted by @abelosorio in https://github.com/sequelize/sequelize/issues/1243#issuecomment-405624147_

**Comment by limyandi** [comment]
Hi @abelosorio, I am using your concept for this, but am getting stuck with an issue where multiple inheritances uses the same id for different table it inherited i.e.
<img width="1332" alt="Screen Shot 2020-11-30 at 6 28 18 pm" src="https://user-images.githubusercontent.com/19499685/100582874-d4b95400-3339-11eb-86e9-6e88db2c87f6.png">

The migration inheritance looks like this:
**Parent - Postingans**
<img width="624" alt="Screen Shot 2020-11-30 at 6 29 56 pm" src="https://user-images.githubusercontent.com/19499685/100583006-0e8a5a80-333a-11eb-860a-ec279e43d275.png">

**Children - Pekerjaans**
<img width="539" alt="Screen Shot 2020-11-30 at 6 29 45 pm" src="https://user-images.githubusercontent.com/19499685/100582988-07634c80-333a-11eb-8dd5-fe85469ae403.png">
<img width="1385" alt="Screen Shot 2020-11-30 at 6 31 17 pm" src="https://user-images.githubusercontent.com/19499685/100583162-3da0cc00-333a-11eb-97ef-e9594e8b5ea9.png">

**Children - Makanans**
<img width="584" alt="Screen Shot 2020-11-30 at 6 30 32 pm" src="https://user-images.githubusercontent.com/19499685/100583059-2366ee00-333a-11eb-8ba2-8b0f1f195736.png">
<img width="840" alt="Screen Shot 2020-11-30 at 6 31 08 pm" src="https://user-images.githubusercontent.com/19499685/100583138-37aaeb00-333a-11eb-92ad-e9c8d87f7f4d.png">

This is done in postgres.

packages version
    "sequelize": "^5.22.3",
    "sequelize-cli": "^5.5.1",
    "pg": "^7.18.2",

Any input will be appreciated.

**Comment by abelosorio** [comment]
Hey @limyandi, there is a while I used that workaround, so I don't remember exactly how it worked.

Can you provide more info on:
- Parent's definition (all its fields)
- Tables' details in Postgres (ie, `\d+ "Makanans"`)

Thanks

**Comment by limyandi** [comment]
Hi @abelosorio, Thanks for replying,

Here you go:

- Parent Data
<img width="394" alt="Screen Shot 2020-12-01 at 7 15 15 pm" src="https://user-images.githubusercontent.com/19499685/100717102-8bd0d080-3409-11eb-9630-8b9cb8a722d8.png">
<img width="337" alt="Screen Shot 2020-12-01 at 7 14 33 pm" src="https://user-images.githubusercontent.com/19499685/100717044-7360b600-3409-11eb-92ed-41ff69626697.png">

- Postingans (Parent) Sequel Structure
<img width="1440" alt="Screen Shot 2020-12-01 at 7 16 45 pm" src="https://user-images.githubusercontent.com/19499685/100717269-c175b980-3409-11eb-8d70-e3f69a3bb60e.png">


- Makanans (Children) Sequel Structure
<img width="1435" alt="Screen Shot 2020-12-01 at 7 15 46 pm" src="https://user-images.githubusercontent.com/19499685/100717165-a014cd80-3409-11eb-87e6-fc0eaa65b993.png">

Thanks.

**Comment by abelosorio** [comment]
@limyandi I think I know what's going on. You're overriding fields in the child table.

With your function `product_common_properties` you're creating all the fields from the parent table in the child table, again. That way, the `id` field (and the rest of them) from the child table is not inherited from the parent table, instead, it's being re-created.

The solution (and I didn't test this, so this is just a proposal) would be:
```javascript
.createTable('Makanans', {
  ...product_common_properties, <--- REMOVE THIS LINE
  ...makanans_properties
})
```

I think I may have caused the confusion with my example:
```javascript
      return queryInterface.createTable('eventRecurrenceRecords', {
        // .. All fields from parent (recurrenceRecords) <------- MY BAD
        // Plus this one
        eventId: {
          type: Sequelize.INTEGER,
          allowNull: false,
          references: {
            model: 'events',
            key: 'id'
          },
          onUpdate: 'cascade',
          ...
```
"All fields from parent" means "all fields from the parent will be inherited... Sorry!

_You do need to explicitly define them in the model._

Let me know if that helps.

**Comment by limyandi** [comment]
> @limyandi I think I know what's going on. You're overriding fields in the child table.
> 
> With your function `product_common_properties` you're creating all the fields from the parent table in the child table, again. That way, the `id` field (and the rest of them) from the child table is not inherited from the parent table, instead, it's being re-created.
> 
> The solution (and I didn't test this, so this is just a proposal) would be:
> 
> ```js
> .createTable('Makanans', {
>   ...product_common_properties, <--- REMOVE THIS LINE
>   ...makanans_properties
> })
> ```
> 
> I think I may have caused the confusion with my example:
> 
> ```js
>       return queryInterface.createTable('eventRecurrenceRecords', {
>         // .. All fields from parent (recurrenceRecords) <------- MY BAD
>         // Plus this one
>         eventId: {
>           type: Sequelize.INTEGER,
>           allowNull: false,
>           references: {
>             model: 'events',
>             key: 'id'
>           },
>           onUpdate: 'cascade',
>           ...
> ```
> 
> "All fields from parent" means "all fields from the parent will be inherited... Sorry!
> 
> _You do need to explicitly define them in the model._
> 
> Let me know if that helps.

Wait so how do I inherit them then?

**Comment by abelosorio** [comment]
That's the magic of inheritance...

From https://www.postgresql.org/docs/current/tutorial-inheritance.html:
```
CREATE TABLE cities (
  name       text,
  population real,
  elevation  int     -- (in ft)
);

CREATE TABLE capitals (
  state      char(2) UNIQUE NOT NULL
) INHERITS (cities);
```
> In this case, a row of capitals inherits all columns (name, population, and elevation) from its parent, cities. The type of the column name is text, a native PostgreSQL type for variable length character strings. The capitals table has an additional column, state, which shows its state abbreviation. In PostgreSQL, a table can inherit from zero or more other tables.

**Comment by limyandi** [comment]
Hi @abelosorio , I tried to remove the line, but I am getting a different issue now that it does not detect any properties from the parent (i.e. id, judul etc.)
<img width="544" alt="Screen Shot 2020-12-06 at 2 23 57 pm" src="https://user-images.githubusercontent.com/19499685/101270992-bbe3ef00-37ce-11eb-9ee1-902cfea3a487.png">

When I try to migrate:
<img width="446" alt="Screen Shot 2020-12-06 at 2 25 50 pm" src="https://user-images.githubusercontent.com/19499685/101271012-f2ba0500-37ce-11eb-903b-1a736e411537.png">

It's saying ID is missing, and when I do add the id attribute:
<img width="539" alt="Screen Shot 2020-12-06 at 2 26 35 pm" src="https://user-images.githubusercontent.com/19499685/101271025-0cf3e300-37cf-11eb-8649-82d006ab0a4f.png">

It's now saying judul is missing:
<img width="417" alt="Screen Shot 2020-12-06 at 2 27 07 pm" src="https://user-images.githubusercontent.com/19499685/101271039-1f6e1c80-37cf-11eb-9513-fe437ada5bcc.png">

**Comment by limyandi** [comment]
@abelosorio Hi Abel, is there any update on this? Thank you.
