### ISSUE TITLE
node app: Sequelize related dependencies build fail on Jenkins / Linux

### ISSUE THREAD

**Issue by nocturnalcodehack** [sequelize/sequelize#12891]
## Issue Description

Trying to build a webpack app with sequelize on in Jenkins on a linux server. Getting error after error with module not found. First: "Module not found: Can't resolve 'pg', then 'pg_hstore', then 'ph_native', then 'pg-config', then 'tedious'. Why require these to build because I'm not even using postgress nor mssql -- I'm using 'mysql' dialect. Funny, that even the instructions on sequlize.org indicate to install 'one of' these--not all.  Also erroring on libpq and node.gyp.  Note sure why this is happening.

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/65150423/sequelize-6-all-dialects-required-at-build-on-linux

### Additional context
Jenkins build on AWS, using nextjs, sequelize 6, babel, webpack.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [X ] Yes. This issue only applies to the following dialect(s): mysql
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, I will concentrate all efforts involving Webpack problems in this new issue: #13169 - Please help me there if possible.
