### ISSUE TITLE
Failing to connect to Azure SQL database using active directory password authentication

### ISSUE THREAD

**Issue by TaiHovanky** [sequelize/sequelize#12919]
**Issue Description**
When trying to connect to an instance of an Azure SQL database using Azure active directory password authentication, I keep getting this error when using Sequelize v4 (with Tedious 5.0.2 installed as a dev-dependency) "There was an issue connection to the database AccessDeniedError [SequelizeAccessDeniedError]: Login failed for user '<user account>@<my company>.com'." 

Alternatively, when I tried upgrading to Sequelize 5.22.3 (with Tedious 6.7.0 installed as a dev-dependency) and used the same config, I got this error: "There was an issue connection to the database ConnectionError [SequelizeConnectionError]: Security token could not be authenticated or authorized.". 

What's the correct configuration for the object passed into sequelize (for Azure active directory password authentication)? Do I need to upgrade to a new minor or major version of Sequelize? Ideally, I'd prefer to stick to v4 if possible.

**What are you doing?**
```
const newDb = new sequelize({
        name,
        username: <svc account>@<my-company.com>@<database server>, // not sure if this should be null for AD auth
        password: <svc account password> // not sure if this should be null for AD authentication
        dialect: 'mssql',
        encrypt: true,
        host: <database host>,
        port: 1433,
        dialectOptions: {
          encrypt: true,
          packetSize: 32768,
          options: {
            useUTC: false,
            dateFirst: 1,
            database: <my database>,
          },
          authentication: {
            options: {
              userName: <svc account>@<my-company.com>@<database server>, 
              password: <svc account password>
            },
            type: 'azure-active-directory-password',
          },
          server: <database host>,
        },
      });
```

**What do you expect to happen?**
I'm expecting to be able to log into the Azure SQL database from my API. When I use the credentials for the service account to log into the database using Azure Data Studio, I'm able to do so using Azure Active Directory.

**What is actually happening?**
Environment
Sequelize version: 4.17.3
Node.js version: v12.16.3
Operating System: macOS 10.15.7
Tedious 5.0.2 is installed as a dev-dependency of the project. 

**How does this problem relate to dialects?**
 This is happening with the MSSQL dialect.

**Would you be willing to resolve this issue by submitting a Pull Request?**
 No, I don't have the time and I wouldn't even know how to start.

**Comment by AlameerAshraf** [comment]
Any update about this issue?

**Comment by ahmedbenkamal** [comment]
I had faced same issue on my current project, But when i have used the same code of @TaiHovanky it is working fine , the only differences are the versions of Environment
**Environment:**
1. Sequelize version: **6.3.5**
2. Node.js version: **v14.16.0**
3. Operating System: **windows 10**
4. Tedious : "**9.2.1**"

`const sequelize = new Sequelize({
    name: dbServerCredentials.dbName,
    username: dbServerCredentials.dbName,//<svc account>@<my-company.com>@<database server>, // not sure if this should be null for AD auth
    password: dbServerCredentials.password,//<svc account password> // not sure if this should be null for AD authentication
    dialect: 'mssql',
    encrypt: true,
    host: dbServerCredentials.host,//<database host>,
    port: 1433,
    dialectOptions: {
        encrypt: true,
        packetSize: 32768,
        options: {
            useUTC: false,
            dateFirst: 1,
            database: dbServerCredentials.dbName,//<my database>,
        },
        authentication: {
            options: {
                userName: dbServerCredentials.userName,//<svc account>@<my-company.com>@<database server>, 
                password: dbServerCredentials.password,// <svc account password>
            },
            type: 'azure-active-directory-password',
        },
    },
});`

**Comment by jamesderrick** [comment]
Similar issue for me, but without sequelize and with newer versions of the packages.
I'm using node v16.13 and tedious v14.3
The error I get is "Security token could not be authenticated or authorized"
I can connect to the Azure SQL DB using Azure Data Studio and I am using the exact same credentials that I use for that within my nodeJS application
My config follows the same setup as the original question

**Comment by jamesderrick** [comment]
My apologies, came here via a link and didn't realise it was sequelize specific.
