### ISSUE TITLE
CLI does not support db:create and db:drop for MariaDB

### ISSUE THREAD

**Issue by pbstriker38** [sequelize/sequelize#12917]
## Feature Description

The Sequelize CLI does not support db:create or db:drop for MariaDB. The syntax is identical to MySQL so it's an easy addition.

### Is your feature request related to a problem? Please describe.

I can't create the database with the CLI.

### Describe the solution you'd like

Allow db:create and db:drop to be used with the `mariadb` dialect

### Why should this be in Sequelize

Other dialects have these features

### Describe alternatives/workarounds you've considered

Manually create the database by logging on to the server.

### Is this feature dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): MariaDB

### Would you be willing to implement this feature by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jerptrs** [comment]
Hey @pbstriker38, any updates on this or a workaround? I'm facing exactly this issue.

**Comment by cyrilchapon** [comment]
This issue history is a wonderful joke
