### ISSUE TITLE
Creating two tables having foreign keys of each other giving error: Cyclic dependency found.

### ISSUE THREAD

**Issue by muzamalidrees** [sequelize/sequelize#12914]
## Issue Description

I have two tables named 'users' and 'roles' and I want to create two relationships between them.
1- 	roles.hasMany(users);
	users.belongsTo(roles, {
		as: 'role',
		onDelete: 'SET NULL',
		foreignKey: { name: 'role_id', type: BIGINT }
	});

2-	users.hasMany(roles)
	roles.belongsTo(users, {
		as: 'creator',
		onDelete: 'SET NULL',
		foreignKey: { name: 'created_by', type: BIGINT }
	});

First one is to find which user have which role
and
Second one is to find that which role is created by which user

When I call sequelize.sync() this gives me following error:
Error: Cyclic dependency found. users is dependent of itself.
Dependency chain: permissions -> users -> roles => users
   
### Is this issue dialect-specific?
I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?
 No, I don't have the time and I wouldn't even know how to start.

**Comment by markvp** [comment]
You're doing many-to-many relationships wrong.

Read [the associations manual](https://sequelize.org/master/manual/assocs.html#many-to-many-relationships).

Good luck!
