### ISSUE TITLE
Error: Values for ENUM have not been defined.

### ISSUE THREAD

**Issue by akhilthakurmusic** [sequelize/sequelize#12915]
Facing issue..

sequelize.js:1235
throw new Error('Values for ENUM have not been defined.');
^
****
**Error: Values for ENUM have not been defined.**

**Migration File**

'use strict';

const { DataTypes, Model } = require("sequelize/types");

module.exports = {
up: async (queryInterface, Sequelize) => {
await queryInterface.createTable('Categories', {
id: {
allowNull: false,
autoIncrement: true,
primaryKey: true,
type: Sequelize.INTEGER
},
name: {
type: Sequelize.STRING(50),
allowNull:false
},
status: {
type: Sequelize.ENUM('1','0'),
defaultValue: '1'
},
createdAt: {
allowNull: false,
type: Sequelize.DATE,
defaultValue:Sequelize.literal("CURRENT_TIMESTAMP")
},
updatedAt: {
allowNull: false,
type: Sequelize.DATE,
defaultValue: Sequelize.literal("CURRENT_TIMESTAMP")
}
});

},
down: async (queryInterface, Sequelize) => {
await queryInterface.dropTable('Categories');
}
};

**Model File**

'use strict';
const {
Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
class Category extends Model {
/**
* Helper method for defining associations.
* This method is not a part of Sequelize lifecycle.
* The models/index file will call this method automatically.
*/
static associate(models) {
// define association here
}
};
Category.init({
name: DataTypes.STRING,
status: DataTypes.ENUM('1', '0')
}, {
sequelize,
modelName: 'Category',
});
return Category;
};

**Comment by markvp** [comment]
firstly, try:
```
status: {
  type: Sequelize.ENUM,
  values: ['0', '1'],
  defaultValue: '1'
},
```
but secondly, if your values are 0/1 you would probably be better off using a binary/bit type?

**Comment by hallex-abreu** [comment]
class Emprestimos extends Model {
    static init(sequelize){
        super.init({
            data_parcela: DataTypes.DATE,
            data_inicio: DataTypes.DATE,
            data_fim: DataTypes.DATE,
            valor_parcela: DataTypes.DECIMAL,
            quantidade_parcelas: DataTypes.INTEGER,
            status: DataTypes.ENUM(['parcela-em-atraso', 'em-dias', 'concluido']),
        },{
            timestamps: false,
            sequelize
        })
    }
    static associate(models){
        this.belongsTo(models.Clientes, { foreignKey: 'cliente_id', as: 'clientes' });
        this.hasMany(models.Parcelas, { foreignKey: 'emprestimo_id', as: 'parcelas' });
    }
}
