### ISSUE TITLE
customizing error for unique constraint

### ISSUE THREAD

**Issue by opeyemidy** [sequelize/sequelize#12929]
```
email: {
        allowNull: false,
        type: DataTypes.STRING,
        unique: {
          msg:
            'Oops. Looks like you already have an account with this email address. Please try to login.',
        },
      },
```
i'm trying to customize error message for unique constraint, the code above isn't working, can someone help please.
## Issue Description

A clear and concise description of what is this issue about.

If applicable, you can add some code. In this case, an SSCCE/MCVE/reprex is much better than just an isolated code snippet.

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
`unique` only takes a boolean (true/false) or a string (in case it's a unique contraint over multiple columns). You can't customize the exception error that is thrown.

You could add a validator to your field that before saving checks if the value already exists. You can customize error messages for validators. The documentation has a short explanation on the [differences between constraints and validators](https://sequelize.org/master/manual/validations-and-constraints.html) and how to add them.

You should leave the unique index intact. There's a very small chance that between the time that your validator runs and when the model is actually saved, a different model is updated. You validate value X@Y.Z and it passes the validator; someone else saves X@Y.Z as well; and _then_ you save. The unique constraint error will probably never pop up, but it's a good last line of defense.

```
email: {
  validate: {
    // As a bonus; You may also be interested in this:
    isEmail: {
      msg: 'This is not a valid e-mail address'
    },
    // (You can find it on the linked documentation page, above)

    async isUniqueEmail(value) {
      const count = await User.count({
        where: { 
          // Find records where the e-mail address is the same as the new value
          email: value,
          // You should be able to use 'this' here to refer to the current model,
          // you should check that yourself to be sure! Pretty sure this will work.
          // If the model hasn't been saved yet, `this.id` be undefined / null, which is fine.
          id: { [Sequelize.Op.ne]: this.id }
        },
        limit: 1
      });
      if (count !== 0) {
        throw new Error('Oops. Looks like you already have an account with this email address. Please try to login.');
      }
    }
  }
}
```

A validator that is async / returns a promise that rejects with an error will use the given error message.

If the validator does not reject, the model will be saved.

**Comment by opeyemidy** [comment]
cool!, this should solve my problem especially the custom validator part. thanks!

**Comment by opeyemidy** [comment]
i'm also having issue auto generating uuids  as primary keys, i'll be glad you if you can help. thanks

**Comment by opeyemidy** [comment]
Cool, this solves my problem especially the custom validator part. thanks!
