### ISSUE TITLE
Increased database connections in sequelize 6

### ISSUE THREAD

**Issue by saigorantla** [sequelize/sequelize#12923]
## Issue Description
I am running into mysql database showing error messages too many connections. I am using pool config in sequelize.

### What are you doing?
Here is how my system is setup, I have multiple micro services hosted on one ubuntu server, each micro service establishes mysql connection using sequelize. 
pool config=>
    "pool": {
      "max": 5,
      "min": 0,
      "acquire": 30000,
      "idle": 10000,
      "handleDisconnects": true
    },

### What do you expect to happen?

Since I am specifying max as 5 I am expecting sequelize to pool max of 5 connections but looks like that config is not getting honored.

### What is actually happening?
services are getting timed out after max pool is reached

### Environment

- Sequelize version: "sequelize": "6.3.5"
- Node.js version: 11.0.0
- Operating System: ubuntu

### How does this problem relate to dialects?

- [ X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by dsibiski** [comment]
I seem to be having this issue in v5.17.2 as well. It seems like perhaps it's a dependency of Sequelize that is having the issue. This happened after a recent deployment where nothing in the code changed expect that the build was rebuilt, making me think it's some sort of dependency that changed.

**Comment by dsibiski** [comment]
@saigorantla Have you found out any more about this? Any sort of workaround?

**Comment by camachojua** [comment]
I have the exact same issue, with this pool configuration:

```json
    "pool": {
      "max": 50,
      "min": 2,
      "maxUses": 1000,
      "acquire": 10000,
      "idle": 10000,
      "evict": 10000,
      "handleDisconnects": true
    }
```
