### ISSUE TITLE
N:M relationship, two inserted values in one 'add' function

### ISSUE THREAD

**Issue by ggj0418** [sequelize/sequelize#12939]
## Issue Description

I tried to add a child row in junction table with 'add' function(N:M). But it failed. I searched the log and found that there were two values inserted when the add function was changed to sql query.

### Model

column_info.js

```
const Sequelize = require('sequelize');

module.exports = class Column extends Sequelize.Model {
  static init(sequelize) {
    return super.init({
      column_title: {
        type: Sequelize.STRING(200),
        allowNull: false,
        unique: true,
      },
      column_content_text: {
        type: Sequelize.STRING(10000),
        allowNull: false,
      },
      column_content_html: {
        type: Sequelize.STRING(10000),
      },
      column_thumbnail_url: {
        type: Sequelize.STRING(300),
      },
    }, {
      sequelize,
      timestamps: true,
      underscored: true,
      modelName: 'Column',
      tableName: 'columns',
      paranoid: true,
      charset: 'utf8',
      collate: 'utf8_general_ci',
    });
  }

  static associate(db) {
    db.Column.belongsToMany(db.Category, {
      through: 'ColumnCategory',
      unique: false,
    });
    db.Column.belongsToMany(db.Tag, {
      through: 'ColumnTag',
      unique: false,
    });
  }
};
```

category_info.js
```
const Sequelize = require('sequelize');

module.exports = class Category extends Sequelize.Model {
  static init(sequelize) {
    return super.init({
      category_name: {
        type: Sequelize.STRING(50),
        allowNull: false,
        unique: true,
      },
    }, {
      sequelize,
      timestamps: false,
      underscored: true,
      modelName: 'Category',
      tableName: 'categorys',
      paranoid: false,
      charset: 'utf8',
      collate: 'utf8_general_ci',
    });
  }

  static associate(db) {
    db.Category.belongsToMany(db.Column, {
      through: 'ColumnCategory',
      unique: false,
    });
  }
};
```

insert Function
```
await sequelize.transaction(async transaction => {
    try {
      var column = await Column.create({
        column_title: column_title,
        column_content_text: column_content_text,
        column_content_html: column_content_html,
        column_thumbnail_url: column_thumbnail_url,
      });

      for(var i in column_categorys) {
        var category = await Category.findOrCreate({
          where : {
            category_name: column_categorys[i],
          }
        });

        await column.addCategory(category);
      }

      for(var j in column_tags) {
        var tag = await Tag.findOrCreate({
          where : {
            tag_name: column_tags[j],
          },
        });

        await column.addTag(
          tag,
          { through:
            { selfGranted: false }
          }
        );
      }
    } catch (err) {
      console.log(err);
      isFail = true;
    }
  });
```

### Main Error

ForeingKeyConstraintError

### Suspicious part

INSERT INTO ColumnCategory (created_at,updated_at,column_id,category_id) VALUES ('2021-01-02 20:57:10','2021-01-02 20:57:10',12,1),('2021-01-02 20:57:10','2021-01-02 20:57:10',12,false);

I think the add function is converted to this sql (it was on the logged message)

### StackOverflow / Slack attempts
https://stackoverflow.com/questions/65543213/how-to-add-child-row-in-related-table-sequelzie-nm-relationship

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [O] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [O] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ferryfw** [comment]
I also have this issue. Any help will be appreciated.
