### ISSUE TITLE
Type more precisely find query return type

### ISSUE THREAD

**Issue by ambreelmee** [sequelize/sequelize#12930]
### Is your feature request related to a problem? Please describe.

When I make a `find` query on a model, it returns the entire model regardless of the attribute I specify. I would like the return type to take into account the attribute I specify and narrow the type to this attributes only. For instance : 

```js
  const user = await User.findOne({ attributes: ['id'] }) // user type should be Pick<User, "id"> | null instead of User | null
```

### Describe the solution you'd like

I tried to do it myself and came up with this non perfect solution:

```js
type FindOne<M extends Model> = <
  O extends {attributes: Array<keyof M>} | FindOptions<M['_attributes']>
>(
  this: ModelStatic<M>,
  options: O
) => Promise<
  O extends  {attributes: Array<keyof M>} ? Pick<M, ValuesType<O['attributes']>> : M | null
>
```

We could also improve this by taking into account association included.

### Why should this be in Sequelize

It should be in sequelize in order to type more precisely what is actually returned by the function. Without it, it lacks consistency and can lead to bugs (when you try by mistake to access an attribute that you didn't specify and you get no sequelize error)

### Is this feature dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [X] Yes. This issue only applies to the following dialect(s): typescript

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [] No, I don't have the time and I wouldn't even know how to start.

**Comment by vinay-naik** [comment]
Sequelize typing need to improve for return types. This feature will really help.

**Comment by vinay-naik** [comment]
Should I raise another issue for returning types of included models as well? Currently if I include any associations in the query it doesn't return their types.

**Comment by mvelebit** [comment]
This is still an issue, any known solutions?
