### ISSUE TITLE
Update method now working

### ISSUE THREAD

**Issue by huntleight** [sequelize/sequelize#12946]
I use MySQL ORM. But update method not working.

```
User.update({
  ResetPasswordToken : resetPasswordToken
},{
  where: {
      UserName: 'testuser'
  }
})
```

Sequelize Log:

`Executing (default): UPDATE Users SET ResetPasswordToken=?,updatedAt=? WHERE UserName = ?
`

### Environment

- Sequelize version: 6.3.5
- Node.js version: 14.15.3
- Operating System: macOS Big Sur

**Comment by dfm212** [comment]
I'm having the same issue, any news on how to fix it?
