### ISSUE TITLE
TypeError: connection.query is not a function

### ISSUE THREAD

**Issue by umair210** [sequelize/sequelize#12958]
I'm trying to fetch data from MS access 16 using odbc but I'm getting error above mentioned
Here's my code
var express = require('express');
var app = express();
const odbc=require('odbc')
//var sql = require("mssql");

app.get('/', function (req, res) { 
    
    //res.send('Hello world');
    //var connection=odbc.connect('DSN=nodeexpress')

        const connection =  odbc.connect(`DSN=expressdata`);
        const data =  connection.query('SELECT *From customerdata_table');
        res.send(data)
        console.log(data);
        
       
});
var server = app.listen(5000, function () {
    console.log('Server is running..');

})

**Comment by vlapo** [comment]
How is this related to `sequelize`? Looks like problem in `odbc` library.

**Comment by umair210** [comment]
Yes, the issue was related to odbc. I needed to find the right string to put in the connection. I found the right connection string from this link https://www.connectionstrings.com/microsoft-sql-server-odbc-driver/
connection=odbc.connect('connection string')
