### ISSUE TITLE
Can't add child objects in a one-to-many relationship

### ISSUE THREAD

**Issue by nareshbhatia** [sequelize/sequelize#1295]
I am using sequelize 2.0.0-beta.7 and can't figure out how to add child objects in a one-to-many relationship. The first object is being added correctly, but the same code is not adding the second object.

My relationship is as follows:

```
Order.hasMany(Execution);
Execution.belongsTo(Order);
```

Here's the code to add an execution to an order:

```
var orderId = req.params.id;
var execution = models.Execution.build(req.body);

models.Order.find({where: {id: orderId}})
    .success(function(order) {
        order.addExecution(execution)
            .success(function() {
                res.send(execution);
            });
    })
```

The first call to this code results in 2 SELECTs followed by an INSERT:

```
Executing (default): SELECT * FROM `Orders` WHERE `Orders`.`id`='2' LIMIT 1;
Executing (default): SELECT * FROM `Executions` WHERE `OrderId` = 2;
Executing (default): INSERT INTO `Executions` (`id`,`quantity`,`createdAt`,`updatedAt`,`OrderId`)
                     VALUES (DEFAULT,20,'2014-01-26 01:59:20','2014-01-26 01:59:20',2);
```

The second call results in only the 2 selects but no INSERT!

Please help.

**Comment by mohitgp** [comment]
@mickhansen, Did the team include this or something similar to what you proposed?

Execution.create({
  quantity: 20,
  order: [instance of Order]
});

**Comment by mickhansen** [comment]
@mohitgp Yep we've had nested create for a bit

**Comment by mohitgp** [comment]
@mickhansen Let me detail out the problem

1. We have referential integrity enforced in the database through foreign keys.
2. The parent is already persistent before creation of a child.
3. The child doesn't exist yet.

Model is as follows:
a) Parent
`sequelize.define('CostType', {
  name: {allowNull: false, type: DataTypes.STRING},
},
{
    classMethods: {
      associate: function(models) {
        CostType.hasMany(Expression);
    }
  }
});`

b) Child:
`sequelize.define('Expression', {
      expression: DataTypes.STRING,
      driverName:DataTypes.STRING
},
{
    classMethods: {
      associate: function(models) {
      //Hope I don't need the following
      //Expression.belongsTo(CostType);
    }
  }
});`

I have a cost type(parent) in database whose id I know. Can I now write create()/ save() an expression which just creates the expression under the already existing cost type.

**Comment by mickhansen** [comment]
Nested create only works with a fully nested create. In your example you can just create with the foreign key value

**Comment by hassanajazch** [comment]
where is the solution man? stop disucssion if u dont know the solution

**Comment by apappasadap** [comment]
Hi, this might be the right place to post my issue but I have a similar problem to this.
The models and their relationship is:

- A _Routing_ has many _Operation_
- An _Operation_ has many worker

The issue is on the third level. I am not able to save the workers in the operations but the operations and the routing is alright.

Here is what I have so far

        const routingInfo = req.body;
        operations = routingInfo.operations;

        [err, routing] = await to(Routings.create(routingInfo, {
            include: [
            { model: RoutingOperations, as: 'operations' }
            ]
        }));
        if (err) return ReS(res, err, 422);

        const routingCode = ConverterService.generateCode('RTG', routing);
        const routingID = routing.routingID;

        [err, routing] = await to(routing.update({ code: routingCode }));
        if (err) {
            [err, routing] = await to(Routings.destroy({ where: { routingID }, force: true }));
            return ReD(res, { err, errCode: 1, code: 422 });
        }

        routing.addOperation(operations, { through: { status: 'started' } });
        [err, operations] = await to(routing.save());
        if (err) return ReS(res, err, 422);

        [err, routes] = await to(routing.getOperations({
            include: [
            { model: WorkstationGroups, as: 'workstationGroup' },
            { model: Workers, as: 'workerOperation' }
            ]
        }));

        if (typeof operations !== 'undefined') {
            for (let index = 0; index < operations.length; index++) {
           //workerOperations is an array of workerID's
            const workers = operations[index].workerOperations;

            if (typeof workers !== 'undefined') {
                await to(routes.addWorkerOperations(workers));
                if (err) return ReD(res, { err, errCode: 0, code: 422 });
            }
            }
        }
        // let routingJSON = routes.toWeb();
        return ReS(res, { routing, message: 'Successfully added routing' }, 201);
