### ISSUE TITLE
Many-to-Many association does not force NOT NULL and can't be set through options either

### ISSUE THREAD

**Issue by marcoburato** [sequelize/sequelize#12963]
## Issue Description

The [documentation for One-To-One associations](https://sequelize.org/master/manual/assocs.html#mandatory-versus-optional-associations) explains that associations are nullable by default, but they can be made required by passing the option `foreignKey: { allowNull: false }`.

For Many-to-Many relationships using a "through" table, I don't think it makes sense for the FKs to be nullable, as that would make a row in that table pointless.

But the biggest problem is that I can't find a way to force the NOT NULL constraint.
passing `{ allowNull: false }` for `foreignKey` and `otherKey` actually breaks the through table.
If I also pass the `name` field, then it works again but it still doesn't add the NOT NULL constraint.

### What are you doing?

```js
const { Sequelize, Op, Model, DataTypes } = require("sequelize");

const sequelize = new Sequelize('sqlite::memory:');

const A = sequelize.define('A', { something: DataTypes.STRING });
const B = sequelize.define('B', { something: DataTypes.STRING });

// 1) Works but does not add NOT NULL constraint
//A.belongsToMany(B, { through: 'Rel_A_B' });
//B.belongsToMany(A, { through: 'Rel_A_B' });

// 2) This produces a broken through table
//A.belongsToMany(B, { through: 'Rel_A_B', foreignKey: { allowNull: false }, otherKey: { allowNull: false } });
//B.belongsToMany(A, { through: 'Rel_A_B', foreignKey: { allowNull: false }, otherKey: { allowNull: false } });

// 3) Works, but still doesn't add NOT NULL constraint
//A.belongsToMany(B, { through: 'Rel_A_B', foreignKey: { name: 'A_id', allowNull: false }, otherKey: { name: 'B_id', allowNull: false } });
//B.belongsToMany(A, { through: 'Rel_A_B', foreignKey: { name: 'B_id', allowNull: false }, otherKey: { name: 'A_id', allowNull: false } });

async function main() {
    await sequelize.drop();
    await sequelize.sync();
    await sequelize.close();
}

main();
```

### What do you expect to happen?

I expected the columns in Rel_A_B to be created with the NOT NULL constraint.

### What is actually happening?

Either Rel_A_B is missing the constraint (cases 1 and 3):
```sql
CREATE TABLE IF NOT EXISTS "Rel_A_B" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "AId" INTEGER  REFERENCES "As" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "BId" INTEGER  REFERENCES "Bs" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("AId","BId"));
```

Or Rel_A_B is broken (case 2):
```sql
CREATE TABLE IF NOT EXISTS "Rel_A_B" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "undefined" INTEGER NOT NULL  REFERENCES "As" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("undefined"));
```

### Environment

- Sequelize version: 6.3.5
- Node.js version: v14.15.1
- Operating System: macOS 11.1

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

_Note: I'm choosing the last option because I'm new to JS and I wouldn't feel comfortable fiddling with sequelize source code._

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by LichaDC** [comment]
Could you solve it?

**Comment by marcoburato** [comment]
I ended up manually defining a "Rel_A_B" model instead of letting Sequelize synthesize it.
Something like

    const Rel_A_B = sequelize.define('Rel_A_B', {
        AId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'A',
                key: 'id'
            }
        },
        BId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'B',
                key: 'id'
            }
        }
    });

    A.belongsToMany(B, { through: Rel_A_B });
    B.belongsToMany(A, { through: Rel_A_B });

**Comment by pmer-hh** [comment]
This did not resolve the issue for me on Sequelize 5.19.2. My join-relational had its columns overridden and the `allowNull` was stripped from them.

**Comment by pmer-hh** [comment]
Apologies for the late reply, but I think this issue is still present.

**Comment by gernotpokorny** [comment]
Yes it seems, that this issue is still present :(

**Comment by ephys** [comment]
If I'm not mistaken, the foreign keys created by belongsToMany are non-null by default, and can be made nullable, in Sequelize 7

**Comment by Unkrass** [comment]
Did anyone ever manage to solve this without creating an explicit junction model or upgrading to sequelize 7?
