### ISSUE TITLE
hooks do not get CLS transaction

### ISSUE THREAD

**Issue by heroic** [sequelize/sequelize#12973]
## Issue Description
If using CLS to set a transaction, then the transaction is not received in the hooks.

### What are you doing?
We set a transaction on the HTTP request using CLS. We expect the transaction to be available inside the hooks to be able to use the afterCommit transaction hook. However, `options` does not contain the transaction.

**Here is the link to the SSCCE for this issue:** LINK-HERE 

This is inside a Koa2 app.
```js
app.use(async (_, next) => {
  await sequelize.transaction(() => next());
});
```

In the model hook
```js
beforeSave: (instance, options) => {
  console.warn(options.transaction);
},
```

The output is undefined.

### What do you expect to happen?
options.transaction should be the same as the transaction set in the CLS.

### What is actually happening?
options.transaction is undefined

```
undefined
```

### Additional context
It appears that this logic is missing inside `save`: https://github.com/sequelize/sequelize/blob/83be13fa1dc73fb37508fe3eab638267003f8618/lib/model.js#L2289

Adding this to `save` fixes this issue.

### Environment

- Sequelize version: 6.4.0
- Node.js version: 12.20.0
- Operating System: Mac OSX

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start, but I don't know if this was left out intentionally
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by heroic** [comment]
Also discussed here #8585

**Comment by heroic** [comment]
@papb could you take a look at this? I can raise a PR for this, is this is a miss and there is no real reason to have skipped passing the transaction to the hooks

**Comment by heroic** [comment]
not stale

**Comment by heroic** [comment]
not stale

**Comment by WikiRik** [comment]
Sorry about the late response, it would be nice if you could make a PR for this @heroic

**Comment by heroic** [comment]
@WikiRik Added!
