### ISSUE TITLE
[BUG] ForeignKey and non-ForeignKeys as unique generates extra constraint

### ISSUE THREAD

**Issue by cskiwi** [sequelize/sequelize#12988]
### What are you doing?

My many to many releationship is unique for a combination of 3 values (the 2 foreign keys and a date).
However any configuration creates a unique constraint on the 2 ForeignKeys and one on the date. So this doesn't allow inserts even if that 3th value is different

Here is the configuration I use:

```ts
@Table
export class ClubMembership extends Model<ClubMembership> {
  @ForeignKey(() => Player)
  @Unique('unique_constraint')
  @Column
  playerId: string;

  @ForeignKey(() => Club)
  @Unique('unique_constraint')
  @Column
  clubId: string;

  @Unique('unique_constraint')
  @Column
  start: Date;

}


@Table()
export class Player extends Model {
  @Default(DataType.UUIDV4)
  @IsUUID(4)
  @PrimaryKey
  @Column
  id: string;
}

@Table()
export class Club extends Model {
  @Default(DataType.UUIDV4)
  @IsUUID(4)
  @PrimaryKey
  @Column
  id: string;
}
```

### What do you expect to happen?

if you have `unique constriaints` on ForeignKeys and non-Foreignkeys, a combined constrained should be created

I tried numerous combinations of `@PrimaryKey`, `@Unique` but non seem to give any correct result

### What is actually happening?

this generates:
![image](https://user-images.githubusercontent.com/847540/106381086-cda0d780-63b6-11eb-9d37-9054f0bdd19f.png)

And thus the following error when inserting something that should pass:
```
ERROR:  duplicate key value violates unique constraint "ClubMemberships_playerId_clubId_key"
DETAIL:  Key ("playerId", "clubId")=(1, 1) already exists.
SQL state: 23505
```

### Additional context

I know I'm using sequelize-typescript, but I have a strong feeling this issue is related to sequelize itself.
However I have the same issue open there: https://github.com/RobinBuschmann/sequelize-typescript/issues/894

### Environment

- Sequelize version: ^6.5.0
- Node.js version: v14.5.0
- Operating System: Win 10 pro
- If TypeScript related: TypeScript version: 3.8.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by cskiwi** [comment]
For other people coming across this issue, I've found a hacky way to make it work:

By placing the following **exact** key on the start column : `@Unique('ClubMemberships_clubId_playerId_unique')`.
it combined the 2 unique instances and gave the wanted result.

If you are having issues finding the unique string:
- on `node_modules/sequelize/lib/dialects/abstract/query-interface.js` 
- Go to line: 205 (ctrl + G o on most editors)
- insert `console.log(tableName, options.uniqueKey)` below 
```
if (model) {
  options.uniqueKeys = options.uniqueKeys || model.uniqueKeys;
}
```

this will spit out each unique key when doing a sync

**Comment by cskiwi** [comment]
this isn't solved as far as I know

**Comment by arvindnarang1i11y** [comment]
+1

**Comment by ephys** [comment]
Does this happen when defining the models using only Sequelize (which would mean it's caused by sequelize-typescript)?

**Comment by cskiwi** [comment]
Not fixed

**Comment by ephys** [comment]
This is likely fixed in v7: https://github.com/sequelize/sequelize/pull/14619
