### ISSUE TITLE
Updating single field in JSON column not working when using Model

### ISSUE THREAD

**Issue by samuliasmala** [sequelize/sequelize#12983]
### What are you doing?

I'm trying to update JSON column property using `Model.update()` but it's not preserving the existing other properties.

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/146

### What do you expect to happen?

I expect to be able to add properties to JSONB column using both `Model.update()` and `instance.update()`. Thus after updating the JSONB `data` column two times I except the final value to be `{ first: 1, second: 2, third: 3 }`.

### What is actually happening?

The `Model.update()` is replacing the whole column value and not preserving the old values and the output is `{ third: 3 }`

### Environment

- Sequelize version: 6.5.0
- Node.js version: 12.18.3 
- Operating System: Windows 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): dialects supporting JSON-column type
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
I can't judge if this is by design or a defect, but [a workaround exists](https://github.com/sequelize/sequelize/issues/4387#issuecomment-369275830) if you want to merge two objects in a `Model.update` call without fetching first / atomically.

**Comment by samuliasmala** [comment]
That workaround is told to do an atomic append to an array. Is it also working for object properties?

**Comment by Spekpannenkoek** [comment]
Yes, the listed syntax (for Postgres) [works on arrays as well as objects](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSONB-OP-TABLE):

> ```
> '["a", "b"]'::jsonb || '["a", "d"]'::jsonb → ["a", "b", "a", "d"]
> '{"a": "b"}'::jsonb || '{"c": "d"}'::jsonb → {"a": "b", "c": "d"}
> ```

The only difference from the example is that you would not add a `[` and `]` around the value that you want to concatenate.

**Comment by samuliasmala** [comment]
Excellent, thanks! That's a nice workaround.
