### ISSUE TITLE
 TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by g3tl0st** [sequelize/sequelize#12990]
### Environment

- Sequelize version: 6.5.0
- Node.js version: 14.15.4
- Operating System: Ubuntu
- Database: Postgres

Trying to create simple App with ***NodeJS*** and Use ***Sequelize ORM***. I'm having ***problem*** when trying to ***Model***.

 I use command `npx sequelize-cli init` to generate some stuff for me.

<b>`In index.js`</b>
```
fs.readdirSync(__dirname)
    .filter((file) => {
        return (
            file.indexOf(".") !== 0 &&
            file !== basename &&
            file.slice(-3) === ".js"
        );
    })
    .forEach((file) => {
        const model = require(path.join(__dirname, file))(
            sequelize,
            Sequelize.DataTypes
        );                                <--- This Line
        db[model.name] = model;
    });
```

When i run `npm start`, its show ***error*** like above.
```
var model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);

TypeError: require(...) is not a function
```

<b>`In app.js`</b>
```
const express = require("express");
const app = express();
const port = 5000;

const db = require("./models");
db.sequelize.sync().then((req) => {
    console.log(req.models);
});

app.listen(port, () => {
    console.log(`App running on localhost:${port}`);
});
```

Any help will be appreciate. ***Gracias***  : )

**Comment by diptigajjar** [comment]
Hi, Have you found any solution?

**Comment by g3tl0st** [comment]
@diptigajjar It turn out, i ***occured*** this ***bug*** in Node ver. <b>14.*.*</b>.
Now, i use Nodejs Version <b>12.*.*</b> is gone.

**Comment by tolumide-ng** [comment]
My approach to resolving this:
In the models/index.js file, I made the following changes:
1. change 
```const  db = {}````
to ```export const db = {}````

2. on Line 22, Add:

```db.sequelize = sequelize```, this means that you can comment out `Line 45`


3. Replace `Line 31 - Line 37` with:
```
.forEach((file) => {
        const model = require(path.join(__dirname, file));
        db[model.name] = model;
    });
````

4. comment out ```module.exports = db``` on `Line 48`

5. This is a typical example of what each individual model would look like, you might have to tailor this to your problem:

In my case "/models/upload.js" becomes
```
import { Model, DataTypes } from "sequelize";
import { sequelize } from "../models";

export class Upload extends Model {
    static associate(models) {
        // define association here
    }
}
Upload.init(
    {
        fileName: DataTypes.STRING,
        fileUrl: DataTypes.STRING,
        fileId: DataTypes.UUID,
        convertTo: DataTypes.STRING,
    },
    {
        sequelize,
        modelName: "Upload",
    },
);
```

**Comment by danoseun** [comment]
@tolumide-ng Your approach worked thanks a lot but I don't understand what happened between now and just 3weeks ago I used sequelize and everything worked well. I literally spent the whole of today troubleshooting this for God's sake!😡😬😫

**Comment by yogithesymbian** [comment]
> export const db = {}

export const db = {};
^^^^^^

SyntaxError: Unexpected token 'export'

**Comment by 14thchief** [comment]
1. Check that you do not have files in models directory that are not exporting anything.
2. Check that your exports are functions with same parameters as the instance it is being called in the require statement.
In any case like mine, I had empty files in my models directory. require(...) is not a function simply because the index logic is iterating over and importing files that do not export anything from the models directory.

**Comment by walidmaouche** [comment]
in my case i replaced 
this code 
`const model = require(path.join(__dirname, file))(
            sequelize,
            Sequelize.DataTypes
        );  `
with this :
`const model = require(path.join(__dirname, file)).default(sequelize, Sequelize.DataTypes);`

tell me does it work?

**Comment by Procech20** [comment]
@walidmaouche This worked for me. Thanks 🥳

**Comment by MartinZani** [comment]
Hello, I had the same problem as you guys but it turned out the problem was the old index.js that I stored as index-backup.js. Maybe you have the same problem as me so I suggest using the debugger of your ide and set a breakpoint at
"const model = ..."
and check the file name in each iteration so you will know which file causes the problem.
Hope I helped.

**Comment by Simeone-Holanda** [comment]
O meu problema era exatamente esse e consegui resolver mudando a forma de exporta o modelo
Como estava: export default (sequelize: any, DataTypes: any).......
Como ficou: module.exports = (sequelize: any, DataTypes: any).....

**Comment by Alexandre-Lustosa-Escossio** [comment]
@14thchief apparently if you export your models as objects you'll get that error as well. For me if I export like that:
`module.exports = { Model }`
I get an error, while if I export as default like that:
`module.exports = Model`
it works just fine.

**Comment by maodaisuki** [comment]
In my case, I deleted the files that don't export model in models directory(but index.js). And it works. I guess this will help someone.

**Comment by CynthiaWahome** [comment]
I tried what @maodaisuki  suggested and it worked for me too. By deleting the files in the models directory that don’t export a model (except index.js), the issue was resolved. Thanks for the tip!
