### ISSUE TITLE
Support for custom dialect adapters

### ISSUE THREAD

**Issue by talyssonoc** [sequelize/sequelize#13003]
### Is your feature request related to a problem? Please describe.

Based on the code in the main branch right now I see we're not able to use externally-developed dialect adapters unless it's in the form of some patching to some of the existing ones (https://github.com/sequelize/sequelize/blob/main/lib/sequelize.js#L320-L338). We're working on the adapter for the CockroachDB dialect, which currently does this patch, but it would be awesome to provide a way to support external dialects.

### Describe the solution you'd like

Ideally, it would be good to be able to pass both a string (to select one of the Sequelize native dialects) or a function/class that would be used when the dialect is instantiated (here https://github.com/sequelize/sequelize/blob/main/lib/sequelize.js#L340). Something like this:

```js
    let Dialect;

    const dialectOption = this.getDialect();

    if(typeof dialectOption === 'string') {
      // Requiring the dialect in a switch-case to keep the
      // require calls static. (Browserify fix)
      switch (dialectOption) {
        case 'mariadb':
          Dialect = require('./dialects/mariadb');
          break;
        case 'mssql':
          Dialect = require('./dialects/mssql');
          break;
        case 'mysql':
          Dialect = require('./dialects/mysql');
          break;
        case 'postgres':
          Dialect = require('./dialects/postgres');
          break;
        case 'sqlite':
          Dialect = require('./dialects/sqlite');
          break;
        default:
          throw new Error(`The dialect ${this.getDialect()} is not supported. Supported dialects: mssql, mariadb, mysql, postgres, and sqlite.`);
      }
    } else {
      Dialect = dialectOption
    }

    this.dialect = new Dialect(this);
```

### Why should this be in Sequelize

Right now we don't have a defacto officially supported way to develop custom dialects, that would be a good improvement.

### Describe alternatives/workarounds you've considered

It's possible to have some kind of workaround for it patching some of the native ones (e.g. https://github.com/cockroachdb/sequelize-cockroachdb/blob/master/index.js#L42) but it comes with the drawback that it makes me no longer able to use both PostgreSQL and CockroachDB in the same app with different Sequelize instances.

### Is this feature dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello! Thank you! This is a great idea.

> Yes, I have the time and I know how to start.

Awesome, PR is very welcome. Don't forget to update the TypeScript typings for the option as well.

**Comment by ephys** [comment]
We're working on this for v7. See https://github.com/sequelize/sequelize/issues/13894

**Comment by ephys** [comment]
This is now well underway. We are tracking the progress in https://github.com/sequelize/sequelize/issues/13722
