### ISSUE TITLE
No proper typescript type information on *AssociationMixins

### ISSUE THREAD

**Issue by tkausl** [sequelize/sequelize#13000]
`AssociationMixin`s don't support proper model typings, for example `HasManyCreateAssociationMixin` is defined as

```
export type HasManyCreateAssociationMixin<TModel> = (
  values?: { [attribute: string]: unknown },
  options?: HasManyCreateAssociationMixinOptions
) => Promise<TModel>;
```

It takes values as `{ [attribute: string]: unknown }` while it should take them as `TModel`s creation attributes.

### Environment

- Sequelize version: 6.5.0 
- Node.js version: 14.15.4
- Operating System: Windows 10
- If TypeScript related: TypeScript version: 4.0.5

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
- [X] Maybe. I have some basic understanding of typescript metaprogramming, not a pro though.

**Comment by mmahalwy** [comment]
Bumping this up - running into this too
