### ISSUE TITLE
Can't order by boolean value (true) in query

### ISSUE THREAD

**Issue by aphavichitr** [sequelize/sequelize#13008]
## Issue Description
Can't order by true values first in query

### What are you doing?
order: [
 [ 'test', true]
]

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?
Should order all rows that are true first in the specified

_I wanted Foo!_

### What is actually happening?
Doesn't return rows with fields that are true first

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: 5.21.5 
- Node.js version: 13.7.0 
- Operating System: MacOS
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by NeroZonbolt** [comment]
No help yet? :c

**Comment by ephys** [comment]
Unfortunately the task does not really describe anything. If you need help using the ORM you can always open a help thread in https://github.com/sequelize/sequelize/discussions
