### ISSUE TITLE
when use sqlite，hooks for beforeConnect, afterConnect, beforeDisconnect, afterDisconnect are not work

### ISSUE THREAD

**Issue by flyingbirdhub** [sequelize/sequelize#13005]
## Issue Description

when i use sqlite for testing the hooks during sql connecting and disconnecting, i found the related hooks are not called. Finally, i found the reason, sqlite connectManager rewrite the getConnection and releaseConnection function, however sqlite should rewrite the connect and disconnect function.

**Comment by medi11** [comment]
I'm still facing the same issue with sqlite and typescript-sequelize `2.0.0-beta.1` and sequelize `6.3.5`

**Comment by chareice** [comment]
@WikiRik It seems that in version v6, the `getConnection` function of sqlite `ConnectionManager` did not trigger the `beforeConnect` and related hooks. This is indeed an existing issue. https://github.com/sequelize/sequelize/blob/252e6d29efef360526695c6ef57fad5a186f369b/src/dialects/sqlite/connection-manager.js#L45
