### ISSUE TITLE
How to use/add custom operators?

### ISSUE THREAD

**Issue by TrurlMcByte** [sequelize/sequelize#13011]
## Issue Description

Can't find way to create query with Postgresql jsonpath operators "@?" and "@@"

### Additional context
for example something like:
```js
    where: {
      body: {
        "@?": "$.** ? (@.tagName == \"a\" && (@.attr.href like_regex \"^/[^/]\") )"
      }
    }
```
where body is jsonb type field must produce 
```sql
WHERE "body" @? '$.** ? (@.tagName == "a" && (@.attr.href like_regex "^/[^/]") )' 
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [X] Yes. This issue only applies to the following dialect(s): PostgreSQL
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
Don't know off the top of my head how to define a custom `Sequelize.Op`, but you can drop down to raw SQL with `literal`:

```
    where: {
      body: Sequelize.literal(
        `@? '$.** ? (@.tagName == "a" && (@.attr.href like_regex "^/[^/]") )'`
      )
    }
```

Use placeholders if the queried value is dynamic:

```
    where: {
      body: Sequelize.literal(
        `@? '$.** ? (@.tagName == :MyTagName && (@.attr.href like_regex "^/[^/]") )'`
      )
    }
    replacements: {
      MyTagName: 'a'
    }
```

This might contain a little mistake or two but it should be an okay starting-off point. If you search Google, you'll find some useful pointers on its usage.

**Comment by TrurlMcByte** [comment]
this code loose field name in generated query. Like ```WHERE @? '$.** ? (@.tagName == "a" && (@.attr.href like_regex "^/[^/]") )'```
working only crazy construction  
```
body: Sequelize.literal(`body @? '$.** ? (@.tagName == "a" && (@.attr.href like_regex "^/[^/]") )'`)
```
but this way not compatible with includes ( just "body" in this case must be "some_table_alias"."body" )

**Comment by rusekr** [comment]
Hello! Want to reopen this because lot of json postgresql operators absent in Sequelize. In particular it will be convinient to have some function to register own operators like '?' for searching in jsonb postgreslq arrays and do not use raw in business logic.

**Comment by ephys** [comment]
I think the best way to support custom operators is going to be by implementing https://github.com/sequelize/sequelize/issues/14299 & https://github.com/sequelize/sequelize/issues/14297. Once they are ready, a custom operator could be implemented like this:

```typescript
import { sql } from '@sequelize/core';

function greaterThan(value) {
  // thanks to the sql tag, value will be escaped before inlining.
  return sql` >= ${value}`;
}

User.findAll({
  friendCount: greaterThan(10),
})
```

The alternative would be to support hooking into QueryGenerator, which would be incredibly complicated to do & to use. I don't think we want to do that.

**Comment by GuillaumeCisco** [comment]
Is it possible to achieve this using v6?
`sql` in only available in v7, and migrating from v6 to v7 is like recoding our entire project.
This is a total no go.

**Comment by ephys** [comment]
Somewhat, but definitely not with the same ergonomics

The best we have in Sequelize 6 is a mix of `literal` and `sequelize.escape`, but there is no good alternative to `sql.attribute`, nor can you easily reference a column in `literal`

Best I can come up with in Sequelize 6:

```js
import { literal } from 'sequelize';

function greaterThan(left, right) {
  return literal(`${left} >= ${right}`;
}

User.findAll({
  where: greaterThan(
    '"friend_count"',
    sequelize.escape(10),
  ),
})
```

**Comment by GuillaumeCisco** [comment]
Ok looks like it can be achieved by wrapping everything in an `Op.and` operator...

**Comment by GuillaumeCisco** [comment]
And by the way, `escape` is not present in v6...
https://github.com/sequelize/sequelize/issues/13225

**Comment by ephys** [comment]
It's `sequelize.escape`, not `queryInterface.escape`

**Comment by GuillaumeCisco** [comment]
`sequelize.escape` does not exist either...

**Comment by ephys** [comment]
Woops, misclick

sequelize.escape: https://github.com/sequelize/sequelize/blob/a3213f053bcc4534073e56def64f22392edaf28c/src/sequelize.js#L704

**Comment by GuillaumeCisco** [comment]
```
TS2305: Module '"sequelize"' has no exported member 'escape'.
```

```
(0 , sequelize_1.escape) is not a function
```

**Comment by GuillaumeCisco** [comment]
`escape` works on a sequelize instance, not on the sequelize package

**Comment by ephys** [comment]
`escape` is an instance method, not a static one

**Comment by mysuf** [comment]
It looks like atleast in v6, it can be done also this way:

`where(col('body'), "@?", "$.** ? (@.tagName == \"a\" && (@.attr.href like_regex \"^/[^/]\") )")`

While digging, I found out that other issues. E.g. sequelize is not able to build simple MySQL query like: `WHERE NOT (a <=> 2)`
NOT implementation probably can't handle more complex right side.
