### ISSUE TITLE
Step 2 of CONTRIBUTING.md fails

### ISSUE THREAD

**Issue by mattdeluco** [sequelize/sequelize#13023]
## Issue Description
Step 2 of the docs in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md) say to run `npm ci`, but the command fails because there's no `package-lock.json`.

In 22d3595 `.npmrc` was configured with `package-lock=false`. Should the file be deleted when we're trying to get the project setup to make contributions?

Also, the command `npm run tsc` fails.

### What are you doing?

I am trying to setup the project and run all necessary tests as part of the PR checklist to make a contribution.

### What do you expect to happen?

_I wanted step 2 of CONTRIBUTING.md to run correctly_

### What is actually happening?

_The output was ERR!_

```
~/D/sequelize ❯❯❯ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
```

```
~/D/sequelize ❯❯❯ npm run tsc
npm ERR! missing script: tsc
```

### Additional context

n/a

### Environment

- Sequelize version: 4063c2a 
- Node.js version: v14.5.0 
- Operating System: macOS 11.1
- If TypeScript related: TypeScript version: n/a

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

There isn't any context around why `package-lock=false` was added; it's unclear if it can be removed.

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Oops, thanks for catching this, sorry for the confusion, will fix soon. 

Feel free to ask me here if you have more difficulties to contribute. I can help you. Thanks!
