### ISSUE TITLE
Problem of translating a native request into a ORM request

### ISSUE THREAD

**Issue by bogdanaks** [sequelize/sequelize#13022]
Hey! Who can tell you how to translate a native postgres query of this kind:
```SELECT * FROM users WHERE date_2 >= date_1 + '2 day' AND date_2 IS NULL;```

In a request using sequelize, I tried to do this:
```
await User.findAll({
      where: {
        date_2: {
          [Op.or]: {
            // [Op.gte]: col('date_1') + '2 day',
            // [Op.and]: literal(`${col('date_1')} >= ${col('date_2')} + INTERVAL '2 day'`),
            [Op.eq]: null,
          },
        },
      },
    });
```

The commented out lines are what I tried to do, but without success
Basically, the problem is to get the field value by the column name and add a certain number of days to it
All dates are type of timestamp with timezone

**Comment by dintores** [comment]
I am also interested in this question!

**Comment by soryy708** [comment]
`SELECT * FROM users WHERE date_2 >= date_1 + '2 day' AND date_2 IS NULL;`
How can `date_2` be both `>= date_1 + '2 day` and `NULL` at the same time?
