### ISSUE TITLE
The port option should be either number or string type

### ISSUE THREAD

**Issue by mattdeluco** [sequelize/sequelize#13025]
## Issue Description
 The port option should accept both strings and numbers. The NodeJS URL
API defines port as a string, where this value ultimately ends up.

It should not be necessary to `parseInt(process.env.PORT)`, for example.

### What are you doing?
I am trying to create an instance of `Sequelize`, configuring the port for the connection using an environment variable `process.env.PORT`.

```js
import { Sequelize } from 'sequelize';

const seq = new Sequelize({
  port: process.env.PORT || '5432'
});
```

### What do you expect to happen?

_I wanted to use environment variables for the port option_

### What is actually happening?

_I am having to use parseInt() to convert a string to a number_

```
No overload matches this call.
  Overload 1 of 4, '(options?: Options): Sequelize', gave the following error.
    Type 'string' is not assignable to type 'number'.
  Overload 2 of 4, '(uri: string, options?: Options): Sequelize', gave the following error.
    Argument of type '{ port: string; }' is not assignable to parameter of type 'string'.ts(2769)
sequelize.d.ts(239, 3): The expected type comes from property 'port' which is declared here on type 'Options'
```

### Environment

- Sequelize version: 4063c2a 
- Node.js version: v14.5.0 
- Operating System: macOS 11.1
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?
I have created draft pull request #13024, I do not have time to carry it further.

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by arman-amiri** [comment]
port: Number(process.env?.DB_PORT),
