### ISSUE TITLE
changed('field_name') returns true even on updating with same value

### ISSUE THREAD

**Issue by chandiramouli-ramachandran** [sequelize/sequelize#13037]
## Issue Description
- Passing the same value to `model.update` function and asserting the value has model_instance.changed(field) in the `afterUpdate` hook returns true.
- model_instance.previous() returns a value with string datatype while the field's datatype is BIGINT
### Attribute Defintion
`state: {
    type: DataTypes.BIGINT,
    allowNull: true
  }`
### Value changed assertion
```
afterUpdate: (app, options) => {
      console.log('Previous value', app.previous(), typeof app.previous().state );
      console.log('Current value', app.state, typeof app.state);
      if (!app.changed('state')) {
        // handle not changed
      }
    // handle changed
    }
```
### Supporting logs
```
Previous value { state: '9' } string
Current value 9 number
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nainkunal933** [comment]
Hi @chandiramouli-ramachandran,

Thank you for opening the issue. For this part of your issue,
> Passing the same value to model.update function and asserting the value has model_instance.changed(field) in the afterUpdate hook returns true.

That's the expected behavior. So, let me know if there is an issue there.
For the second part of the issue, let me get back to you.

**Comment by chandiramouli-ramachandran** [comment]
Hi @nainkunal933 , thank you for your response. My assumption was on with passing the same value, sequelize makes a comparison to conclude on whether the value has changed. If so, may I know how it identifies the value has changed?
