### ISSUE TITLE
Check if deletedAt column is lesser than current date

### ISSUE THREAD

**Issue by Ionys320** [sequelize/sequelize#13034]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I try to use deletedAt column with a date greater than the current date, because the row is marked as deleted by Sequelize

### Describe the solution you'd like

Instead of checking if the column is null, check if it value is lesser or equal with the current date.

### Why should this be in Sequelize

Paranoid is an important part of Sequelize, it wouldn't make sens to put this in another package.

### Is this feature dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
This is actually something that was in a previous major release for Sequelize and has been [deliberately removed](https://github.com/sequelize/sequelize/issues/8496). 

> In Sequelize v4, if deletedAt was set to a timestamp in the future, then a record would not be considered as deleted. This was useful to schedule records for deletion. But as pointed out in this issue, it can lead to consistency issues. Thus, it was removed in v5 in favor of considering a record as deleted if deletedAt is set at all.

If you're aware of the issues raised in the thread I linked then you could emulate the old behavior.

```
class Project extends Model {}
Project.init({
  obsoleteAt: DataTypes.DATE // a field with a date, like deleteAt
  // you probably want to add a (sparse) index to this field.
}, {
  defaultScope: { // every query by default should have these options mixed in
    where: {
      // You might want to use a client-side timestamp, rather than the DB's NOW() 
      // (or you might not!). 
      obsoleteAt: { [Op.lt]: sequelize.fn('NOW') } 
      // If relevant, you could add a NOT NULL

      // Client-side dates can be done, but you'll need to update the scope just before
      // the query is executed in a .beforeFind() hook.
    }
  },
  scopes: {
    obsoleteOnly: {
      where: {
        obsoleteAt: { [Op.gte]: sequelize.fn('NOW') } 
      }
    },
  }
});
Project.find();   // WHERE obsolete < NOW()
Project.scope('obsoleteOnly');   // WHERE obsolete >= NOW()
Project.find({ where: { id: 5 } });   // WHERE id = 5 AND obsolete < NOW()
```

Rather than doing this, you probably could also remove the `WHERE deletedAt` clause was that added by Sequelize's `paranoid:true` yourself with a `.beforeFind` hook or similar. I personally would shy away from modifying the default behavior and implement something like the above.

**Comment by Ionys320** [comment]
I understand, and a big thank you for this great answer. 
But I find it a shame that it is not possible to ask Sequelize to do this natively with an option, despite the fact that I have seen the explanations linked to that. In my opinion, everyone should be able to have a choice.
