### ISSUE TITLE
error using Op.between in Sequelize.where() 

### ISSUE THREAD

**Issue by markvp** [sequelize/sequelize#13040]
### What are you doing?

When using `[Op.between]` in a standard where clause, you can provide an array of values (e.g. `[0,10]`) and this is successfully mapped to `0 AND 10` in the SQL.

When using the `Sequelize.where()` function, however, an error is thrown for invalid SQL as this mapping does not occur - the incorrectly generated SQL is `0, 10`.

```js
Post.findAll({
  where: sequelize.where(sequelize.fn('char_length', sequelize.col('content')), Op.between, [0, 7])
});
```

### What do you expect to happen?

Generated SQL is:

`WHERE char_length(content) BETWEEN 0 AND 7`

### What is actually happening?

Generated SQL is:

`WHERE char_length(content) BETWEEN 0, 7`

### Additional context

N/A

### Environment

- Sequelize version: 6.4.0
- Node.js version: 13.11.0
- Operating System: macOS BigSur

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ruchenshanghai** [comment]
have you tried to use where with between to filter date type field?
I got error for that case. @papb @markvp
