### ISSUE TITLE
Model.getByPk or Model.getOne ignores model.scopes.attributes.excluded

### ISSUE THREAD

**Issue by SerdarSanri** [sequelize/sequelize#13047]
I think title is pretty descriptive but in cases like, if you have a role based system and scopes has different colums visibility per scopes 
i.e 
```
Customer.init({
    ...
    account_number: DataTypes.STRING
    ....
}, {
   scopes: {
       owner: {
          attributes: {exclude: []}
      },
       employee: {
          attributes: {exclude: ['account_number']}
       }
    } 
})
```

if you call 
Customer.scope('employee').findAll(); returns correct result. account_number column is hidden from all rows. But if you call Customer.scope('employee').findByPk('someId'), any exclude option in scope is ignored which makes scopes useless and dangerous enough in a REST api based system. if you can get a list of data, and you know there is an endpoint you can request individual records, you can get all sensitive data.

here is a real-life example. Below is my user model scope definition. and logged in user's role is passed as scope to query 
![image](https://user-images.githubusercontent.com/651202/108455516-63a08300-723c-11eb-8a70-4335e2b356bb.png)

if I request get all users endpoint, I get expected result
![image](https://user-images.githubusercontent.com/651202/108455604-8a5eb980-723c-11eb-8253-c2e44887dd5b.png)

but if I call get user with exact same scope, scope is totally ignored and simply pulls entire row
![image](https://user-images.githubusercontent.com/651202/108455753-cc87fb00-723c-11eb-9047-17e604380334.png)

**Comment by SerdarSanri** [comment]
lovely, that means sequelize no longer maintained, or devs doesn't really care about bug reports anymore

**Comment by WikiRik** [comment]
With 700 issues open and all maintainers being volunteers we cannot answer to all issues. Feel free to update or create a new bug report with the current template.
