### ISSUE TITLE
findAll missing options 'group'

### ISSUE THREAD

**Issue by lfp1024** [sequelize/sequelize#13056]
## Issue Description
[public static async findAll](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findAll) can not find options 'group' , but [model usage](https://sequelize.org/v5/manual/models-usage.html#manipulating-the-dataset-with-limit--offset--order-and-group) find。

### If possible: Provide some suggestion on how we can enhance the docs

how can i find correct Docs?  which is correct Docs ? Thanks so much.

**Comment by lifaith** [comment]
fuck doc

**Comment by ephys** [comment]
Please refrain from making this kind of comment

However you are right that it is missing from the JSDoc.
It's documented in our [typescript typings here](https://github.com/sequelize/sequelize/blob/main/src/model.d.ts#L564), this should be improved once https://github.com/sequelize/sequelize/pull/13914 is complete

**Comment by lifaith** [comment]
> 

thx

**Comment by lifaith** [comment]
> Please refrain from making this kind of comment
> 
> However you are right that it is missing from the JSDoc. It's documented in our [typescript typings here](https://github.com/sequelize/sequelize/blob/main/src/model.d.ts#L564), this should be improved once #13914 is complete

thx
