### ISSUE TITLE
Autoincrement field gets incremented even with invalid data

### ISSUE THREAD

**Issue by Glafuski** [sequelize/sequelize#13054]
## Issue Description
I am testing my system by inserting unique data to database. Models are working correctly and any data is not being sent to database. However for some reason every request still sends autoincrement through to database. So for example if latest correct user is registered with ID 99 and lets say that 5 registers fail it still increments auto increment field to 104. Next user that registers correctly gets ID 105.  So there is something going on with autoIncrement in Sequelize as MariaDB should not increment autoincrement field with invalid data. 

TL;DR

Invalid data does not get passed to database but for some reason autoincrement field is being incremented.

### What are you doing?
I am testing that copies of unique data does not go through to database and that all checks are right.

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?
I expected that invalid data would not increment autoincrement field in database. 

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
// Users create function
try {
    await Users.create({
      username: req.body.username,
      email: req.body.email,
      password: hash,
      rsnick: req.body.rsnick
    });
  }
  catch(error) {
    error.errors.forEach((err) => {
      if(err.type === 'unique violation') {
        switch(err.path) {
          case 'username':
            res.send(messages.errors.usernameinuse);
          break;
          case 'email':
            res.send(messages.errors.emailinuse);
          break;
          case 'rsnick':
            res.send(messages.errors.rsnickinuse);
          break;
        }
      }
    });
    return;
  }

// Users.js -model
Users.init({
    uid: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false
    },
```

### Additional context

![invalid_autoincrement](https://user-images.githubusercontent.com/29288977/108785604-6e2f8500-757a-11eb-82d7-7e95dd39706a.png)

### Environment

- Sequelize version: 6.5.0 
- Node.js version: 14.15.3 
- Operating System: Windows 10
- If TypeScript related: TypeScript version: -

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
- [x] No, I have time but i would not even know how to start.

**Comment by LetrixZ** [comment]
Same thing is happening to me. Inserting or updating, even if it detects collisions or updates successfully on upsert, it will autoincrement.

**Comment by adams-family** [comment]
I confirm that the same thing is happening to me, too: autoincrement field is incremented even when `upsert` results in an UPDATE, causing gaps in the autoincrement column and reducing the maximal number of records in the table.

Please reopen this ticket.

**Comment by ephys** [comment]
We won't reopen this ticket, that behavior is intended in most dialects:

For [postgres](https://www.postgresql.org/docs/9.5/functions-sequence.html)

> Important: To avoid blocking concurrent transactions that obtain numbers from the same sequence, a nextval operation is never rolled back; that is, once a value has been fetched it is considered used and will not be returned again. This is true even if the surrounding transaction later aborts, or if the calling query ends up not using the value. For example an INSERT with an ON CONFLICT clause will compute the to-be-inserted tuple, including doing any required nextval calls, before detecting any conflict that would cause it to follow the ON CONFLICT rule instead. Such cases will leave unused "holes" in the sequence of assigned values. Thus, PostgreSQL sequence objects cannot be used to obtain "gapless" sequences.

For [MySQL](https://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html)

> In all lock modes (0, 1, and 2), if a transaction that generated auto-increment values rolls back, those auto-increment values are “lost”. Once a value is generated for an auto-increment column, it cannot be rolled back, whether or not the “[INSERT](https://dev.mysql.com/doc/refman/8.0/en/insert.html)-like” statement is completed, and whether or not the containing transaction is rolled back. Such lost values are not reused. Thus, there may be gaps in the values stored in an AUTO_INCREMENT column of a table.
