### ISSUE TITLE
The documentation of the hasMany() typings wrongly advertises N:M associations

### ISSUE THREAD

**Issue by owme** [sequelize/sequelize#13052]
## Issue Description

Sequelize version: 6.5.0

### What was unclear/insufficient/not covered in the documentation

The documentation of the hasMany association in the "/types/lib/model.d.ts" is wrong. It states that it can "[c]reate an association that is either 1:m or n:m.", but it doesn't support N:M associations. The actual HasMany class in the "/lib/association/has-many.js" actually throws an error('N:M associations are not supported with hasMany. Use belongsToMany instead'), when getting initialized with an option object that has a "through" property. 

### If possible: Provide some suggestion on how we can enhance the docs

Please consider deleting the corresponding N:M part in the documentation of the hasMany typings, as this is clearly neither supported by the actual class, nor the HasManyOptions interface (one cannot provide a through property, because the HasManyOptions interface correctly doesn't contain this attribute).

### Additional context

![sequelize](https://user-images.githubusercontent.com/40660312/108626570-147f6b80-7451-11eb-808a-43a7b62c4509.png)

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): 
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start. #

**Comment by owme** [comment]
I'm a first time contributor and would like to push this change. Unfortunately I cannot push it because I don't have the necessary access rights to this repository. I have all changes committed locally in a branch. Would anyone be able to help me to push my commit and start a pull request?

**Comment by ppicom** [comment]
To submit pull requests you need to fork the project, and then submit a pull request from the forked project.
