### ISSUE TITLE
[SO Link Included] Is it possible for me to model these associations with Sequelize?

### ISSUE THREAD

**Issue by anthonyorona** [sequelize/sequelize#13076]
## Issue Description

![XGze1](https://user-images.githubusercontent.com/70772352/110247931-7c3eb780-7f23-11eb-9073-edeba9e73c20.png)

I have these relations in my SQL database. There are two entity types A and B. These entities are owners of a resource and I manage this via a mapping table. The relations are:

Entity A has one or more Owner entries. Entity B has one or more Owner entries.

Each Owner entry has zero or one Entity A entry. Each Owner entry has zero or one Entity B entry.

Each Resource has zero or more owners. Each Owner entry tracks one resource.

I am using this to model individuals and groups owning a resource. The problem is when I go to use the ORM it complains that I have not given an association between Owners and Entities. I'm not really sure how to do this with Sequelize. What I would like to do is have a composite key like so:

(entity_type, entity_id)

where entity_type is from enum (EntityA, EntityB) and entity_id is an id corresponding to a record in either of those tables. In this way I can guarantee that the composite key is unique. But again, I'm not really sure how I can implement this via Sequelize.

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/66500977/how-can-i-have-a-sequelize-composite-key-a-non-unique-unique-pair-and-then-us

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x ] Yes. This issue only applies to the following dialect(s): postgresql
- [ ] I don't know.

**Comment by soryy708** [comment]
Looks like the stackoverflow link provided has an accepted answser. Should this issue be closed?

**Comment by anthonyorona** [comment]
Yes thanks
