### ISSUE TITLE
Geometry broken in MySQL 8

### ISSUE THREAD

**Issue by thomasmost** [sequelize/sequelize#13086]
### What are you doing?
I can't use Sequelize methods to set Geometry types like POINT since GeomFromText was fully deprecated and removed in favor of ST_GeomFromText in MySQL 8.

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/149

### What do you expect to happen?

Sequelize should presumably check the MySQL version and use ST_GeomFromText in 5.7 and up. Failing that, perhaps an 'ST' param could be passed to the DataType options to tell it to use the renamed function.

### What is actually happening?

Results in this error:
```
  Fails with error: SequelizeDatabaseError: FUNCTION db.GeomFromText does not exist
```

### Environment

- Sequelize version: 6.5.0
- Node.js version: 14.16.0
- Operating System: MacOs Catalina

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): **MySQL ^8.0**
- [ ] I don't know

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by thomasmost** [comment]
This may be a stupid thing that I've missed: Does Sequelize not officially support MySQL 8??

**Comment by tamal-appsbee** [comment]
Any update on it ?

**Comment by WikiRik** [comment]
MySQL 8.0 tests & support have been added in 6.10.0. @thomasmost is this still an issue in the latest release?

**Comment by thomasmost** [comment]
Hi @WikiRik !

Let me give it a shot this afternoon and I'll let you know :)

**Comment by WikiRik** [comment]
@thomasmost not sure if you remember if you gave this a shot, but if you did would be nice so we can close this issue

**Comment by thomasmost** [comment]
@WikiRik apologies. I'd moved on to a different project in November and this slipped my mind.

I've got the old project bootstrapped though, so I think I should be able to test this week! Thank you!

**Comment by WikiRik** [comment]
Awesome! Thanks for your work on this

**Comment by thomasmost** [comment]
Thank you for the reminder!

**Comment by thomasmost** [comment]
Boy, follow-through has not been my strength on this ticket... till now that is! (Mea culpa!)

I just tested with `sequelize@6.17.0` and my spatial index on non-null POINT column is now usable, since I can actually populate the coordinates column on `create` rather than with raw SQL! 

🎉 Consider this issue FIXED 💚

**Comment by ephys** [comment]
Very good news :)
