### ISSUE TITLE
create() on polymorphic use case does not always work

### ISSUE THREAD

**Issue by quocvu** [sequelize/sequelize#13098]
## Issue Description

I have a use case that is exactly like the example in the Polymorphism section of the docs. My app is an express app.
When I call `picture.createComment()` it often fails but restarting express, and retrying the same operation usually works.
So there is some kind of state that is interferring here. 

### What are you doing?

**Here is the link to the SSCCE for this issue:** LINK-HERE 

This is my models definition which is pretty much a straight compy & paste from the example

```js
const uppercaseFirst = str => `${str[0].toUpperCase()}${str.substr(1)}`;

class Comment extends Model {
  getCommentable(options) {
    if (!this.commentableType) return Promise.resolve(null);
    const mixinMethodName = `get${uppercaseFirst(this.commentableType)}`;
    return this[mixinMethodName](options);
  }
};

Comment.init({
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  userId: {
    type: DataTypes.UUID,
    allowNull: false,
  },
  commentableType: {
    type: DataTypes.STRING(255),
    allowNull: false
  },
  commentableId: {
    type: DataTypes.UUID,
    allowNull: false,
  },
  comment: {
    type: DataTypes.TEXT,
    allowNull: false
  },
}, {
  sequelize: db,
  modelName: 'comment',
});

Comment.addHook('afterFind', findResult => {
  if (!Array.isArray(findResult)) findResult = [findResult];
  for (const instance of findResult) {
    if (instance.commentableType === 'picture' && instance.picture !== undefined) {
      instance.commentable = instance.picture;
    } else if (instance.commentableType === 'contest' && instance.contest !== undefined) {
      instance.commentable = instance.contest;
    }
    // To prevent mistakes:
    delete instance.picture;
    delete instance.dataValues.picture;
    delete instance.contest;
    delete instance.dataValues.contest;
  }
});


Contest.hasMany(Comment, {
  foreignKey: 'commentableId',
  constraints: false,
  scope: {
    commentableType: 'contest'
  }
});
Comment.belongsTo(Contest, { foreignKey: 'commentableId', constraints: false });

Picture.hasMany(Comment, {
  foreignKey: 'commentableId',
  constraints: false,
  scope: {
    commentableType: 'picture'
  }
});
Comment.belongsTo(Picture, { foreignKey: 'commentableId', constraints: false });
```

### What do you expect to happen?

If my models are not properly setup, I would expect to fail all the time. Else it should work on the time. In my case it is intermittent without any code change

### What is actually happening?

This is the error that happen often but not always when I make this call

```
const com = await picture.createComment({
        userId: this.id,
        comment: text,
      }, { transaction: t });
```

```
[2021-03-12T01:01:19.283] [WARN] dev - Unable to add comment ValidationError [SequelizeValidationError]: notNull Violation: comment.commentableType cannot be null
    at InstanceValidator._validate (/Users/.../node_modules/sequelize/lib/instance-validator.js:78:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async InstanceValidator._validateAndRunHooks (/Users/.../node_modules/sequelize/lib/instance-validator.js:111:7)
    at async InstanceValidator.validate (/Users/.../node_modules/sequelize/lib/instance-validator.js:93:12)
    at async Comment.save (/Users/.../node_modules/sequelize/lib/model.js:3877:7)
    at async Function.create (/Users/.../node_modules/sequelize/lib/model.js:2207:12)
    at async HasMany.create (/Users/...node_modules/sequelize/lib/associations/has-many.js:483:12)
    at async User.writeComment (/Users/.../models/user.js:163:19)
    at async exports.addComment (/Users/.../controllers/comments.js:14:13) {
  name: 'SequelizeValidationError',
  errors: [
    ValidationErrorItem {
      message: 'comment.commentableType cannot be null',
      type: 'notNull Violation',
      path: 'commentableType',
      value: null,
      origin: 'CORE',
      instance: [comment],
      validatorKey: 'is_null',
      validatorName: null,
      validatorArgs: []
    }
  ]
}
```

### Environment

- Sequelize version: 6.5.0 
- Node.js version: 12.10 
- Operating System: MacOS Big Sure
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by joenas** [comment]
@quocvu sorry for resurrection but did you manage to find a solution?

**Comment by quocvu** [comment]
@joenas I use a workaround.  When I call the `createComment()`, I explicitly set the value of the `commentableType` field.  It should have been derived based on the object type.
