### ISSUE TITLE
Roadmap for v7?

### ISSUE THREAD

**Issue by soryy708** [sequelize/sequelize#13097]
Is there a roadmap for v7? Any specific goals/milestones to hit for it to be ready for stabilization and release?
I found https://github.com/sequelize/sequelize/issues/2869 but last activity is 2017. Is it still relevant?

**Comment by boobo94** [comment]
Curious too 😄

**Comment by ephys** [comment]
We're thinking about it.
Right now the closest we have to a roadmap is https://github.com/orgs/sequelize/projects/1/views/1

Our goal is to rework the foundations of Sequelize, release v7, then start implementing new features in minor releases.

We're getting close, as you can see in the "Before v7" column.

**Comment by boobo94** [comment]
Thanks for your reply. The link is not available, probably I don’t have the permissions.

**Comment by ephys** [comment]
Changed :)

**Comment by boobo94** [comment]
> Changed :)

Thanks. I like too see how many tasks are about improving the docs. 💪🤩

**Comment by fzn0x** [comment]
> > Changed :)
> 
> Thanks. I like too see how many tasks are about improving the docs. 💪🤩

👍  Yup we will like to address more and more docs improvement in v7 😃
