### ISSUE TITLE
TypeScript: The Transactionable interface should also accept null

### ISSUE THREAD

**Issue by yjwong** [sequelize/sequelize#13092]
### What are you doing?

When using TypeScript with `strictNullChecks` turned on, and with the following snippet:

```ts
await sequelize.query("SELECT 1", { transaction: null });
```

### What do you expect to happen?

Should not produce a compilation error. Passing `null` to `transaction` allows a query to be run outside the context of a transaction when auto-transactions are enabled.

I think the correct definition of the `Transactionable` interface should be:

```ts
export interface Transactionable {
  /**
   * Transaction to run query under
   */
  transaction?: Transaction | null;
}
```

### What is actually happening?

Compilation error:

```
Type 'null' is not assignable to type 'Transaction | undefined'.
```

### Environment

- Sequelize version: 5.22.3 
- Node.js version: v12.21.0 
- Operating System: Ubuntu 20.04 LTS
- If TypeScript related: TypeScript version: 4.2.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hi! Thanks for this issue and for sending the PR - I commented there.

I have another question, I noticed that `transaction: null` does not work on SQLite, do you happen to know if this is due to some SQLite limitation or is it a Sequelize bug?

**Comment by yjwong** [comment]
Hi @papb! Thanks for the PR review, will revise it to include typing tests.

My team uses the Postgres dialect in production, so I'm not super sure about why it doesn't work with SQLite. The behaviour seems to be implicitly documented here, where `null` was passed into via `transaction`: https://sequelize.org/master/manual/transactions.html#with-cls-enabled

There's a small note above the code example that says that SQLite doesn't support more than 1 transaction at a time. If "running outside the transaction" is also considered a another transaction, that might explain why it doesn't work.

**Comment by papb** [comment]
> There's a small note above the code example that says that SQLite doesn't support more than 1 transaction at a time. If "running outside the transaction" is also considered another transaction, that might explain why it doesn't work.

Ahh, that's it!! Thank you very much!
