### ISSUE TITLE
Where the $nested.column$ code is made?

### ISSUE THREAD

**Issue by calebeaires** [sequelize/sequelize#13099]
This issue is just a clarification of where on the Sequelize lib a transformation is made. At this [point of the documentation](https://sequelize.org/master/manual/eager-loading.html#complex-where-clauses-at-the-top-level) is told that $nested.column$ syntax also works for columns that are nested several levels deep, such as $some.super.deeply.nested.column$. 

For the sake of understanding the code I have tried to found where the identification is made and where the joins from $nested.column$. May the community help me identify the part of Sequelize code this is done?

**Comment by robertjustjones** [comment]
Since I single stepped to it, here's the line after the check for $..$ where it's stripping them and just before it handles them. 

https://github.com/sequelize/sequelize/blob/23aa67e9abe440027aa07091beb35834e584e42e/lib/dialects/abstract/query-generator.js#L2524
