### ISSUE TITLE
Many to many relationship creating duplicates instead of referring to existing row

### ISSUE THREAD

**Issue by atultw** [sequelize/sequelize#13109]
## Many to many relationship creating duplicates instead of referring to existing row

What I am doing:

### Adding tag to post using many to many relationship:
Following the example at https://sequelize.org/master/manual/creating-with-associations.html (last section, many to many) I'm trying to add tags to a post in my nodejs app using Sequelize (and MS SQL Server). Here's how I'm doing it:

Create the tag:
```js
Tag.create({
        name: "Photography",
        description: "tag for photo related things."
    })
```

Yes, it saved to db. I checked. On to creating the post:

```
Post.create({
    name: "a photo",
    description: "a description",
    Tags: [{name: 'Photography'}]
}, {
    include: [ Tag ]
})
```

**Here is the link to the SSCCE for this issue:** https://gist.github.com/atultw/2ca55fa53d13f3a327912d5cb28a67bf
(gist, self contained other than sqlconnection which is just the standard ``sequelize.Sequelize`` after connection.

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

I wanted a row to be created in the middle table (``PostTags``) with the id of post and id of tag for each tag specified (on line 49). That's what's described in the documentation I followed. Just like this:
![diagram](https://bezkoder.com/wp-content/uploads/2020/04/sequelize-many-to-many-relationship-node-js-diagram.png)

This is the most common way of modeling such a relation. 

### What is actually happening?

Instead, it is creating a new tag with the supplied details instead of using ID of the existing one. For example, it creates a new row in table ``Tags`` with just ``name: "Photography"`` instead of referencing existing row with said property. 

### Why this is an issue
Since the sample in documentation describes a tagging system, and this is the best way to do it, we have one of the following:

- **Documentation is suggesting the proper way (one instance of the tag, linked to product via a third table.)**  ==> The documentation is broken.
- **Documentation is suggesting a really odd and inefficient way of doing it** ==> If indeed the idea is to create duplicates of each tag every time it's referenced, that shouldn't be suggested in the docs. Besides, something like this seems like a main use case and should thus be well documented.

I can't seem to find one preferred way to go about this. There were some people suggesting .setTag, .addTag etc but those don't work (error being that those aren't methods of the model). 

**Really hoping there will be a working sample using the solution described at the docs linked, as it is by far the most elegant and it would be great if it worked.**

### Additional context

Models defined as:
```js
class Post extends Model {
}

Post.init({
    name: DataTypes.STRING,
    description: DataTypes.STRING
}, {
    sequelize: sqlconnection,
    modelName: 'Post'
})

class Tag extends Model {
}

Tag.init({
    name: DataTypes.STRING,
    description: DataTypes.STRING
}, {
    sequelize: sqlconnection,
    modelName: 'Tag'
})
```
Relationships defined as:

```js
Tag.belongsToMany(Post, {
    through: {
        model: 'PostTags'
    }
})

Post.belongsToMany(Tag, {
    through: {
        model: 'PostTags'
    }
})
```
Also tried using id instead of name as follows, but it throws a 

``UniqueConstraintError [SequelizeUniqueConstraintError]: Validation error``
specifically: ``original: RequestError: Violation of PRIMARY KEY constraint 'PK__Tags__3213E83F58EED7F3'. Cannot insert duplicate key in object 'dbo.Tags'. The duplicate key value is (1).`` 

I think this is because of the above issue, instead of using an existing row it tries to create a new one with given info, which of course wouldn't work since PK is unique.

```js
Post.create({
    name: "a photo",
    description: "a description",
    Tags: [{id: 1}]
}, {
    include: [ Tag ]
})
```

When inspecting source of the generated table that joins the two:
```sql
-- auto-generated definition
create table PostTags
(
    createdAt datetimeoffset not null,
    updatedAt datetimeoffset not null,
    PostId    int            not null
        references Posts
            on delete cascade,
    TagId     int            not null
        references Tags
            on delete cascade,
    primary key (PostId, TagId)
)
go
```

### Environment

- Sequelize version: 6.5.1
- Node.js version: v14.15.3
- Operating System: Win10 64-bit
- TypeScript version: N/A

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
> Documentation is suggesting a really odd and inefficient way of doing it ==> If indeed the idea is to create duplicates of each tag every time it's referenced, that shouldn't be suggested in the docs. Besides, something like this seems like a main use case and should thus be well documented.

I _think_ this is the case, if I interpret the first sentence of the linked documentation page:

> An instance can be created with nested association in one step, provided all elements are new.

To make this work as you expect, I figure Sequelize would have to do this during a `save` with `include`:

- Insert new the tags
- Return the new IDs
- Except for the ones which can't be inserted due to duplicate entries (unique index on `name`); return IDs for those
- Add all of these IDs to the 'through table' to link the Post and Tag(s). 

That seems a little bit "too much work" or "too smart" for a convenience feature like this to me, but that's my unqualified opinion.

You could do these steps yourself which is not too much typing. It seems MSSQL doesn't support `ignoreDuplicates:true` and `returning: ['id']` in `bulkCreate` so the DB needs to do a find (and possibly an insert) query per tag:

```javascript
// Untested but ought to work
const tagIds = await Promise.all(tags.map(
  tag => sequelize.findOrCreate({ where: { name: tag } }).then(instance => instance.id)
));
Post.setTags(tagIds);
```

_(Probably not worth it, but you could reduce the query count by doing a `findAll`, filter out tags that were not found, `bulkCreate` those, then maybe one extra `findAll` to get the new IDs—I don't know if `bulkCreate` can return the new IDs in MSSQL)_

If the behavior of `create( )`—always creating new entries and errorring out when encountering a duplicate key—is indeed intentional (can someone confirm this?) then you could suggest a change to the documentation to make it more clear to others encountering your question in the future.

**Comment by atultw** [comment]
This sounds like a good solution. I will look into it, sorry for the late response. Thanks!
