### ISSUE TITLE
Order by Object and Include field

### ISSUE THREAD

**Issue by RodPaDev** [sequelize/sequelize#13116]
I need for the request to be ordered back by `user.fullname` which is joined by using `include` and by `mockUser.fullname` which is a  JSON field. 

One important thing to keep in mind however is that `user` is nullable in the case a `mockUser` is present.

This is what I have so far, it is ordering by `mockUser.fullname` and `user.fullname`, However, it is doing so separately, meaning there are two correct orders but they're not ordered into one single order which is the desired result.

```js
      const options = {
        where: args,
        include: ['user'],
        limit,
        offset,
        order: [['user', 'fullname', 'ASC'], ['mockUser.fullname', 'ASC']]
      }
```
SQL equivalent-ish of the above sequelize representation, it's spit out by sequelize but I cleaned it up
**Note: it turns every "user"."column" as "user.column"**

```sql
SELECT * FROM "table" 
LEFT OUTER JOIN "user" ON "table"."userId" = "user"."id" 
WHERE "table"."columnId" = '9efcbd5a-4dc7-4102-ad59-b6f6cd9adaa4'
ORDER BY "user"."fullname" ASC, ("table"."mockUser"#>>'{fullname}') ASC 
LIMIT 10 
OFFSET 0;
```
*I'm using `table` and `column` to obfuscate the real names*

Example output:
```
Adam Smith -> user
Beatrice Westfield -> user
John Smith -> user
Andy Brook -> mockUser
Mario Jimenez -> mockUser
Nadia Martinez -> mockUser
```

As you can see it first sorts user and then mockUser, but how could I combine both?

EDIT: Expand question

**Comment by Spekpannenkoek** [comment]
There's a SQL function that returns the first non-null argument.

`COALESCE("alice", null)` --> `alice`  
`COALESCE(null, "bob")` --> `bob`

Then simply sort by its return value.

```
order: [
  [sequelize.fn( // calls a native SQL function with 2 arguments
    'COALESCE', 
    sequelize.col('user.fullname'), 
    sequelize.col('mockUser.fullname')
  ), 'ASC']
]
```

**Comment by RodPaDev** [comment]
Sorry for not updating, I tried it after figuring I needed COALESCE but it seems that since mockUser is in camelCase it just throws errors, I just ahead and proposed a different solution but I can test it later and show the errors. 

I think the errors were 'From-table missing' or something and 'mockUser -> fullname' is not a column. I will double check later
