### ISSUE TITLE
QUESTION: Can you pass AWS IAM credentials?

### ISSUE THREAD

**Issue by gsogol** [sequelize/sequelize#13114]
One of the ways AWS RDS (MySql or Postgres) works is an ability to create an AWS RDS Proxy in front of it that manages connections for you as well as many other things. To connect to the proxy, you can pass username/password or an IAM credntials which the proxy authenticates and then uses a Secret Manager internally to retrieve username and password.

This is obviously better than passing and storing credentials with sequelize. Can one pass IAM credentials to sequelize instead of username and password?

**Comment by papb** [comment]
Hello! I don't know much about AWS usage like this, can you please check the information provided in #12642 and see if it helps you somehow? I will probably be merging that PR soon

**Comment by gsogol** [comment]
Thank you. Although this is a super important document and thank you for putting much thought into it, my question is not so much about lambda but anyone wanting to use RDS Proxy and when initiating a connection, instead of passing a username and password, how does one pass IAM credentials instead?

**Comment by gsogol** [comment]
Another way to ask this question, can I override the way sequelize creates a connection. Can I implement and pass a function?

**Comment by papb** [comment]
Sorry for the delay. Can you post some code showing how to create the connection using pg (without sequelize)?

Something similar to the examples given here: https://node-postgres.com/features/connecting

**Comment by gsogol** [comment]
Thank you @papb for your responses.

I'm actually creating a proxy (AWS basically has a managed service that does pooling, retries, load balancing and other features) that sits in front of our db cluster (AWS Aurora based on MySql). In order to connect to it, you specify 2 endpoints, writer and reader which sequelize already supports. AWS and many other cloud providers do not recommend passing username and password. They recommend connecting using AWS IAM credentials for security reasons. The [link](https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/) I reference including javascript code can be found [here](https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/). It talks about creating a proxy and thus connecting to it via IAM Credentials. I reference a piece of code it's using under the section "Using the proxy" towards the very bottom.

Hope you can point me in the right direction.

**Comment by papb** [comment]
Oh, thanks for the explanation and the link! I always wanted to learn more about how all that works, and that code example was great.

Please try the following and let me know:

```js
const AWS = require('aws-sdk');
const { Sequelize } = require('sequelize');

exports.handler = async (event) => {
  console.log("Starting query ...\n");
  console.log("Running iam auth ...\n");

  const signer = new AWS.RDS.Signer({
    region: '[insert your region here]', // example: us-east-2
    hostname: '[insert your RDS Proxy endpoint here]',
    port: 3306,
    username: '[Your RDS User name]'
  });

  const token = signer.getAuthToken({
    username: '[Your RDS User name]'
  });

  console.log("IAM Token obtained\n");

  const sequelize = new Sequelize({
    dialect: 'mysql',
    host: process.env.endpoint, // Store your endpoint as an env variable
    database: process.env.my_db, // Store your DB schema name as an env variable
    username: '[Your RDS User name]',
    password: token,
    dialectOptions: {
      ssl: { rejectUnauthorized: false },
      authSwitchHandler(data, cb) {
        console.log("Running authSwitchHandler");
        if (data.pluginName === 'mysql_clear_password') {
          console.log("pluginName: " + data.pluginName);
          const password = token + '\0';

          // Why does the official example declare a unused variable like this??
          // const buffer = Buffer.from(password);

          cb(null, password);
        }
      }
    }
  });

  await sequelize.authenticate();

  console.log('SUCCESS!');
};
```

**Comment by gsogol** [comment]
Thank you @papb ! Looks like password simply passes the token. I shall try and let you know.  Thank you!
