### ISSUE TITLE
Have a method to get model attributes

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize#13119]
### Is your feature request related to a problem? Please describe.

Need a way to get model attributes from a previously defined model.
https://stackoverflow.com/questions/33858334/is-there-a-way-to-get-attributes-associations-by-previously-defined-sequelize

### Describe the solution you'd like

Instead of model.rawAttributes (undocumented), have a method at https://sequelize.org/master/class/lib/model.js~Model.html
to return the same, eg `getAttributes()`

### Why should this be in Sequelize

Short explanation why this should be part of Sequelize rather than a separate package.

### Describe alternatives/workarounds you've considered

model.rawAttributes is undocumented and could go away

### Is this feature dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by mariusa** [comment]
@mattiamalonni @sdepold 
7 days to close an issue is extremely aggressive, common... Especially as maintainers don't even look at these valid requests.

**Comment by mariusa** [comment]
still needed

**Comment by sdepold** [comment]
Looks like a solid feature request. Any interest in implementing it?

**Comment by Bishwodahal** [comment]
It is solved with
https://github.com/sequelize/sequelize/commit/b6510df2bdb5fb22c508c3f348e11cbaf7065fbc
You can use this from 
https://www.npmjs.com/package/sequelize/v/6.12.0-beta.3

**Comment by mariusa** [comment]
Thank you!
