### ISSUE TITLE
How to use "concat(round(( surveys/employees * 100 ),2),'%') AS percentage" in sequelize ?

### ISSUE THREAD

**Issue by prioarief** [sequelize/sequelize#13118]
### What was unclear/insufficient/not covered in the documentation

Write here.

### If possible: Provide some suggestion on how we can enhance the docs

Write here.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
Native SQL functions can be used with [`sequelize.fn`](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#static-method-fn) ([example](https://sequelize.org/master/manual/model-querying-basics.html#advanced-queries-with-functions--not-just-columns-)). Raw SQL, for the math part, can be used with [`sequelize.literal`](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#static-method-literal) ([example](https://sequelize.org/master/manual/sub-queries.html#using-sub-queries-for-complex-ordering)).

```javascript
SomeModel.findAll({
  attributes: {
    include: [
      [
        // first array value is the computed result
        sequelize.fn(
          'CONCAT', 
          sequelize.fn('ROUND', sequelize.literal(' surveys / employees * 100 '), 2),
          '%'
        ), 
        // second array value is the 'AS'
        'percentage'
      ]
    ]
  }
})
```

Please do try to keep in mind that the people here are volunteers. If you don't put any effort in your question then you can't expect anyone to put a big effort into answering your question. When asking for help online, try to make your topic such that it can _help someone else too_ if they ever stumble upon it in the future. _Give and_ take. StackOverflow—an excellent place to ask questions like this—[says it best](https://stackoverflow.com/help/how-to-ask).
