### ISSUE TITLE
Package subpath './v1' is not defined by "exports"

### ISSUE THREAD

**Issue by UziTech** [sequelize/sequelize#13123]
## Issue Description

Sequelize v5 throws the error `Package subpath './v1' is not defined by "exports"` seems like this is an issue with a [deprecation in uuid](https://github.com/uuidjs/uuid#deep-requires-no-longer-supported).

I don't really understand why it happens since sequelize v5 uses uuid@v3 which should work but for some reason it doesn't.

### Additional context

Anywhere in the codebase `require("uuid/v1")` should be changed to `require("uuid").v1` like in Sequelize v6

### Environment

- Sequelize version: 5.22.4
- Node.js version: 14.15.4
- Operating System: Windows 10

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
:thinking: Thanks for the report, any idea why is it possible for [our v5 tests](https://github.com/sequelize/sequelize/runs/2107585617) to be green in spite of this?

**Comment by UziTech** [comment]
I don't think this is actually an issue with sequelize v5 since uuidv3 doesn't show this error. I think I have come across this error because of a unique setup where (for whatever reason, probably security related) npm is installing the latest version of uuid instead of the requested v3.

In any case, I don't see a good reason not to update uuid in sequelize v5 like i did in #13124

**Comment by papb** [comment]
Fair enough! Thank you.

Fixed by #13124

**Comment by papb** [comment]
Hello, semantic-release did not trigger a new release for a dependency update, can you use `npm install https://github.com/sequelize/sequelize/tarball/aca4fbc14893ba8fca1ba8221360e588e821a429` for now?

**Comment by UziTech** [comment]
Ya it is working
