### ISSUE TITLE
Return database affected Rows

### ISSUE THREAD

**Issue by joaobalzer** [sequelize/sequelize#13143]
### What are you doing?
Hi im trying to return the effected rows from my database after i update an record, is that possible?

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
https://sequelize.org/master/class/lib/model.js~Model.html#static-method-update

> **Return**
> `Promise<Array<number, number>>`
> The promise returns an array with one or two elements. The first element is always the number of affected rows (...)

```javascript
const [affected] = SomeModel.update(...);
```

`someInstance.save()` does not return the number of affected rows. It can only be 0 or 1. Because many models will have an `updatedAt` field, you can pretty much assume it'll always be 1.

**Comment by joaobalzer** [comment]
Thank! Really Helped me.
