### ISSUE TITLE
Typescript creation attributes: extends Optional multiple fields

### ISSUE THREAD

**Issue by spinlud** [sequelize/sequelize#13151]
Is it possible to provide multiple optional fields for creation attributes?

The following doesn't seem to compile:

```ts
interface UserAttributes {
    id: number;
    name: string;
    email: string;
}

interface UserCreationAttributes extends Optional<UserAttributes, 'id'>, Optional<UserAttributes, 'email'>  {}
```

`sequelize`: `6.6.2`

**Comment by KapitanOczywisty** [comment]
You need union for keys
```ts
interface UserCreationAttributes extends Optional<UserAttributes, 'id' | 'email'>  {}
```

**Comment by KapitanOczywisty** [comment]
You need to use type union for keys
```ts
interface UserCreationAttributes extends Optional<UserAttributes, 'id' | 'email'>  {}
```

**Comment by spinlud** [comment]
Thanks!

Just wondering if it is just easier to makes fields optional directly:

```ts
interface UserAttributes {
    id?: number;
    name: string;
    email?: string;
}

class User extends Model<UserAttributes, UserAttributes> implements UserAttributes {
    // ...
}
```

**Comment by KapitanOczywisty** [comment]
Probably yes, I'm not aware of any case which would be broken because of this. And `CreationAttributes` are optional (defaulted to the first parameter), so code bellow is the same as with `Model<UserAttributes, UserAttributes>`:

```ts
class User extends Model<UserAttributes> implements UserAttributes {
    // ...
}
```

**Comment by spinlud** [comment]
Got it, thank you!

**Comment by mayowadabiri** [comment]
> You need to use type union for keys
> 
> ```ts
> interface UserCreationAttributes extends Optional<UserAttributes, 'id' | 'email'>  {}
> ```

Yo!, thanks for this. Works perfectly.

**Comment by nhattien015** [comment]
What is Optional do? I cannot understand it's mean. Why id, email fields is optional 
while I'ts can is primary key and mandatory in table ?

**Comment by nhattien015** [comment]
> What is Optional do? I cannot understand it's mean. Why id, email fields is optional
> while It can is primary key and mandatory in table ?

What is Optional do? I cannot understand it's mean. Why id, email fields is optional
while It can is primary key and mandatory in table ?

**Comment by nhattien015** [comment]
Explain to me. Thank you

**Comment by mayowadabiri** [comment]
> What is Optional do? I cannot understand it's mean. Why id, email fields is optional while It can is primary key and mandatory in table?

It basically tells typescript to make the fields optional at creating the record, say User.create or User.build. This means if you don't put the id or email field in User.create({}), typescript would not throw an error.

**Comment by nlukic97** [comment]
@nhattien015 here is what an error looks like when we have the **id** field defined in a User model, but not an id submitted in the **create:** method.

![image](https://user-images.githubusercontent.com/56925545/151681748-0b62448d-7315-47de-9429-32260d6a29e0.png)
