### ISSUE TITLE
findOrBuild not working as expected

### ISSUE THREAD

**Issue by gbarton** [sequelize/sequelize#13164]
I think its a misunderstanding on my part, I am looking for the behavior of 'pull from the db by where, if no results, instantiate a new model object'.

my model:
```javascript
const CaseFiles = sequelize.define('CaseFiles', {
  // Model attributes are defined here
  caseId: {
    type: DataTypes.STRING(256),
    field: 'case_id',
    allowNull: false,
    primaryKey: true,
  },
  pathSha256: {
    type: DataTypes.STRING(64),
    field: 'path_sha256',
    allowNull: false,
    primaryKey: true,
  },
  path: {
    type: DataTypes.STRING(2048),
    field: 'path',
    allowNull: false,
  },
  sha256: {
    type: DataTypes.STRING(64),
    field: 'sha256',
    allowNull: false,
  },
// .... more
}, {
  // Other model options go here
  createdAt: false,
  updatedAt: false,
  timestamps: false,
  tableName: 'case_files',
});
```

Following code snippet where I try my above goal
```javascript
  log('coord finished routing, saving updates', msg);
  // const cf = CaseFiles.build(msg);
  // TODO: why doesnt save/update work with this
  const cf = await CaseFiles.findOrBuild({
    where: {
      caseId: msg.caseId,
      pathSha256: msg.pathSha256,
    },
    defaults: msg,
  });
  log('cf', cf);
  await cf.update(msg); // line 202, this doesnt work, sf.save(); doesnt work either
  log('saved');
```

LOG output (w/ sql enabled)
```
  test:coord coord finished routing, saving updates {
  caseId: '1617196302',
  sha256: '238b754da8469c1e25a2699d2994a59b16308b2abee671cbf9c476a0b8d9bd67',
  fileUri: 's3://s3/test-bucket/23/8b/238b754da8469c1e25a2699d2994a59b16308b2abee671cbf9c476a0b8d9bd67',
  'content-length': 14722063,
  path: '/headless/Downloads/k9s_Linux_x86_64.tar.gz',
  filename: 'k9s_Linux_x86_64.tar.gz',
  pathSha256: 'ad523223329628f48aff4bbc0eed6d0eca505ae805a0467d2fddb2b1eac3a8d4'
} +1ms
Executing (default): SELECT `case_id` AS `caseId`, `path_sha256` AS `pathSha256`, `path`, `sha256`, `done`, `filename`, `file_format` AS `fileFormat` FROM `case_files` AS `CaseFiles` WHERE `CaseFiles`.`case_id` = '1617196302' AND `CaseFiles`.`path_sha256` = 'ad523223329628f48aff4bbc0eed6d0eca505ae805a0467d2fddb2b1eac3a8d4';
  test:coord cf [
  CaseFiles {
    dataValues: {
      done: false,
      fileFormat: 'unknown',
      caseId: '1617196302',
      sha256: '238b754da8469c1e25a2699d2994a59b16308b2abee671cbf9c476a0b8d9bd67',
      path: '/headless/Downloads/k9s_Linux_x86_64.tar.gz',
      filename: 'k9s_Linux_x86_64.tar.gz',
      pathSha256: 'ad523223329628f48aff4bbc0eed6d0eca505ae805a0467d2fddb2b1eac3a8d4'
    },
    _previousDataValues: {
      caseId: undefined,
      sha256: undefined,
      path: undefined,
      filename: undefined,
      pathSha256: undefined
    },
    _changed: Set { 'caseId', 'sha256', 'path', 'filename', 'pathSha256' },
    _options: {
      isNewRecord: true,
      _schema: null,
      _schemaDelimiter: '',
      where: [Object],
      defaults: [Object]
    },
    isNewRecord: true
  },
  true
] +12ms
  test:coord error handling routing TypeError: cf.update is not a function
    at Object.route (/headless/wrk/coordinator/lib/coord.js:10:202)
    at async Context.<anonymous> (/headless/wrk/coordinator/test/test-coord.js:85:5) +3ms

```

If I use `CaseFiles.build(msg);` The object creates and the save/update functions work (they just error since record already exists.  In either case dumping the object to log doesnt show the save/update functions present, but clearly whatever is returning from `findOrBuild()` does not have save or update available to it.

**Comment by gbarton** [comment]
Little bit of progress. I just noticed that findOrCreate and FindOrBuild are returning arrays, this seems incorrect.  The documentation says I should get a `Promise<Model|null>` back, not `Promise<[Model]|null>`. I still cannot get it to save/update either if i just try to work with the first element in the array.

**Comment by gbarton** [comment]
And as these things go, its not till you look at it sideways (in a bug report no less) that you figure it out.

`findOrBuild() and findOrCreate()` return arrays of [Model, bool], so destructure that out to get the actual value.

```javascript
const [cf] = await CaseFiles.findOrBuild({
        where: {
          caseId: msg.caseId,
          pathSha256: msg.pathSha256,
        },
        defaults: msg,
      });
```

I'm not going to close this because someone needs to update the documentation that says I get a `Promise<Model|null>` back from those functions, it should say `Promise<[Model,boolean>|null>` to save a lot of head scractching.

**Comment by Spekpannenkoek** [comment]
Where are you seeing that documentation? On the site the v6 [docs](https://sequelize.org/master/class/lib/model.js~Model.html) say:

> public static async findOrBuild(options: object): Promise<Model, boolean>
> Find a row that matches the query, or build (but don't save) the row if none is found. The successful result of the promise will be (instance, built)

`findOne`, which is directly above it does return `Promise<Model|null>`.

**Comment by gbarton** [comment]
Ahh I think I get my confusion now.  Like you said `findOne` returns `Promise<Model|null>` while `findOrBuild` returns `Promise<Model, boolean>`.  For me that was non-obvious staring at the docs for a really long time that `findOrBuild` was a tuple return vs an either/or like findOne.  I think if it were written as `Promise<[Model, boolean]>` it would be crystal clear what was being returned.

Thank you for the reply.  I'll close this since docs are indicitave of the difference, just not clear that its actually an array/tuple being returned.
