### ISSUE TITLE
MySQL cast as integer

### ISSUE THREAD

**Issue by SimonChaumet** [sequelize/sequelize#13163]
## Issue Description
When using sequelize.cast, the result is a cast in decimal.

### What are you doing?
I am using aggregation functions but the result is always a string.

**Here is the link to the SSCCE for this issue:** [https://github.com/SimonChaumet/sequelize-sscce/blob/patch-1/src/sscce.js#L34-L41](https://github.com/SimonChaumet/sequelize-sscce/blob/patch-1/src/sscce.js#L34-L41)

### What do you expect to happen?
I expect to have a request with a cast as integer and get an integer as a result

### What is actually happening?

The result is a cast as decimal and the json output is a string (See request [https://github.com/papb/sequelize-sscce/pull/155/checks?check_run_id=2235443995#step:7:34](https://github.com/papb/sequelize-sscce/pull/155/checks?check_run_id=2235443995#step:7:34) )

### Additional context

I'm using MySQL v5.
It could be nice to add more documentation if it's the expected behavior.

### Environment

- Sequelize version: v5.22.4
- Node.js version: 12.19.0
- Operating System: Arch linux 

### How does this problem relate to dialects?

- [X] I think this problem happens only for the following dialect(s): MySQL

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by SimonChaumet** [comment]
> The MySQL2 driver [always returns decimal numbers as strings](https://github.com/sidorares/node-mysql2/blob/6ffcb8605a403f96952e87be491a3c5b0ce01a2f/documentation/Readme.md#known-incompatibilities-with-node-mysql) so it's happening at a level 'above' Sequelize.

As you can see I ask Sequelize to cast as an integer not a decimal number. It seems that somewhere sequelize decides to convert my integer into a decimal

**Comment by Spekpannenkoek** [comment]
Seems that way in your source & Sequelize somewhere changes the 'as integer' to 'as decimal'. From your SSCCE:

> [Sequelize] Executed (default): SELECT CAST(SUM(`value`) AS DECIMAL) AS `sum` FROM `Foos` AS `Foo` GROUP BY `name`; [Elapsed time: 1 ms] 

The commit that introduced the following function refers to adding MySQL JSON support. Without diving too deep into it, it seems like that is done here: https://github.com/sequelize/sequelize/blob/ac368c966906786dc9eb20e4a006329b2854f9c3/lib/dialects/mysql/query-generator.js#L274

My theory is that to support `cast( some_json->someNumber as integer )` the 'integer' is mapped to 'decimal' for whatever reason [in MySQL]. Not sure if this could introduce precision errors for larger integers and it seems odd to me to map it to a different data type, but know too little of this.

Passing the `{decimalNumbers: true}` option to `new Sequelize(..., {driverOptions: ...})` should still fix the problem.

**Comment by SimonChaumet** [comment]
I am not querying a json as you can see so how does this comes even if I don't query a json ?

The problem with the driver options are that they apply to the entire project and not just one query, or is there a way to pass it only for a query ?

**Comment by Spekpannenkoek** [comment]
I don't think there is a way to do that, no. 

Again, I don't know too much about this code path, but if you look at the function I linked, the `else if (smth instanceof Utils.Cast)` is next to but not within `if (smth instanceof Utils.Json)` so I think it was added for but not _exclusively_ for casting values when using JSON functions (just a theory!), collateral damage, so to speak.

**Comment by SimonChaumet** [comment]
> I don't think there is a way to do that, no.
> 
> Again, I don't know too much about this code path, but if you look at the function I linked, the `else if (smth instanceof Utils.Cast)` is next to but not within `if (smth instanceof Utils.Json)` so I think it was added for but not _exclusively_ for casting values when using JSON functions (just a theory!), collateral damage, so to speak.

So you agree in modifying the condition to check if we are querying a json if I understand correctly ?

**Comment by Spekpannenkoek** [comment]
> After some test with the code I found a way to override this by using a cast as UNSIGNED INT instead of INTEGER/UNSIGNED INTEGER and it works but the code from sequelize seems to be a problem if you want to cast correctly.

Yeah, that would work around the `/integer/i` regular expression check. A creative solution. :-)

> So you agree in modifying the condition to check if we are querying a json if I understand correctly ?

Well, I'm not a maintainer or contributor so my agreeing wouldn't matter, but it seems to me that this cast to DECIMAL should indeed not occur in your use-case. Other dialects like Postgres and SQLite don't seem to need this in any case. It seems unnecessary and confusing. 

Not sure how to add a condition like that. 

Perhaps @sushantdhiman, who was involved with that commit [1], can shed some light on the reasoning behind this code? Is it a defect or documented somewhere?

[1] (the author seems to not be active in this repository anymore)

**Comment by SimonChaumet** [comment]
By the way do you know if there is a way to pass these dialect options per query ?

**Comment by SimonChaumet** [comment]
up
