### ISSUE TITLE
Order issue with 1:M Association (query with included model)

### ISSUE THREAD

**Issue by Alejopdp** [sequelize/sequelize#13160]
## Issue Description
I'm trying to return some ordered records by an included model column, but the order clause is being ignored.

### What are you doing?
I have a 1:M relationship between **Delivery** and **HourRange**. For clarifying, deliveries should be done within an hour range, which has 2 Date fields **minHour** and **maxHour**.

This is how i've defined the associations:

`Delivery.belongsTo(HourRange, { foreignKey: "hourRangeId" });`
`HourRange.hasMany(Delivery, { foreignKey: "hourRangeId" });`

To give more context, i also have the following associations, they aren't relevant tho:

```
User.hasMany(Address, { foreignKey: "userId" });
User.hasMany(Order, { foreignKey: "userId" });
User.hasMany(Delivery, { foreignKey: "userId" });
```
```
Address.belongsTo(User, { foreignKey: "userId" });
Address.hasMany(Delivery, { foreignKey: "addressId" });
```
```
Order.belongsTo(Delivery, { foreignKey: "deliveryId" });
Order.belongsTo(userId, { foreignKey: "userId" });
```
These are the options i'm using for a **FindAndCountAll** query in order to get the records i want:

```
{
      where: conditions,
      limit: 10,
      offset: 0,
      distinct: true,
      include: [
        {
          model: models.Address,
        },
        {
          model: models.User,
        },
        {
          model: models.Order,
        },
        {
          model: models.HourRange,
          as: "HourRange",
          order: [[{ model: models.HourRange, as: "HourRange" }, "minHour", "DESC"]],
          required: true,
        },
      ],
    };

```
And it generates the following Query (I've removed a lot of columns to keep the query small):

```
SELECT 
  "Delivery".*, 
  "Address"."id" AS "Address.id", 
  "Address"."userId" AS "Address.userId", 
  "User"."id" AS "User.id", 
  "Orders"."id" AS "Orders.id", 
  "Orders"."deliveryId" AS "Orders.deliveryId", 
  "Orders"."userId" AS "Orders.userId" 
FROM 
  (
    SELECT 
      "Delivery"."id", 
      "Delivery"."addressId", 
      "Delivery"."userId", 
      "Delivery"."hourRangeId", 
      "HourRange"."id" AS "HourRange.id", 
      "HourRange"."minHour" AS "HourRange.minHour" 
    FROM 
      "Delivery" AS "Delivery" 
      INNER JOIN "HourRange" AS "HourRange" ON "Delivery"."hourRangeId" = "HourRange"."id" 
    LIMIT 
      10 OFFSET 0
  ) AS "Delivery" 
  LEFT OUTER JOIN "Address" AS "Address" ON "Delivery"."addressId" = "Address"."id" 
  LEFT OUTER JOIN "User" AS "User" ON "Delivery"."userId" = "User"."id" 
  LEFT OUTER JOIN "Order" AS "Orders" ON "Delivery"."id" = "Orders"."deliveryId"

```

### What do you expect to happen?

I want to have the **Deliveries ordered by its HourRange minHour**, so i need the following query as output:

```
SELECT 
  "Delivery".*, 
  "Address"."id" AS "Address.id", 
  "Address"."userId" AS "Address.userId", 
  "User"."id" AS "User.id", 
  "Orders"."id" AS "Orders.id", 
  "Orders"."deliveryId" AS "Orders.deliveryId", 
  "Orders"."userId" AS "Orders.userId" 
FROM 
  (
    SELECT 
      "Delivery"."id", 
      "Delivery"."addressId", 
      "Delivery"."userId", 
      "Delivery"."hourRangeId", 
      "HourRange"."id" AS "HourRange.id", 
      "HourRange"."minHour" AS "HourRange.minHour" 
    FROM 
      "Delivery" AS "Delivery" 
      INNER JOIN "HourRange" AS "HourRange" ON "Delivery"."hourRangeId" = "HourRange"."id" 
    ORDER BY
      "HourRange"."minHour" DESC
    LIMIT 
      10 OFFSET 0
  ) AS "Delivery" 
  LEFT OUTER JOIN "Address" AS "Address" ON "Delivery"."addressId" = "Address"."id" 
  LEFT OUTER JOIN "User" AS "User" ON "Delivery"."userId" = "User"."id" 
  LEFT OUTER JOIN "Order" AS "Orders" ON "Delivery"."id" = "Orders"."deliveryId"

```
but i cannot find a way for including that order clause there.

I would like to add the order clause outside the subquery also, for a stronger ordering clause, but this is desirable.

### Additional context
These are the things i've tried,

**Regarding the order clause in the included model, i've tried writing the order clause in the following formats**:
`order: [[models.hourRange, "minHour", "DESC"]]`
`order: [["minHour", "DESC"]]`
`order: "minHour DESC"`

none of them worked, it seems that Sequelize is ignoring the order instruction. I've also tried them with the alias in the included model removed.

**Moving the order clause outside the include array:**

This gives me the famous **"missing FROM-clause entry for table "HourRange""** error
`order: [[models.HourRange, "minHour", "DESC"]]`

These give me the **"Cannot read property 'type' of undefined"** error
`order: [["$HourRange.minHour$", "DESC"]]`
`order: [["$Delivery.HourRange.minHour$", "DESC"]]`

And i've tried almost every possible combination without any result.

Using `subQuery: false` doesn't help as it breaks the limit clause.

I've seen the following issues but none of them worked for me

[8325](https://github.com/sequelize/sequelize/issues/8325)
[4553](https://github.com/sequelize/sequelize/issues/4553)
[7897](https://github.com/sequelize/sequelize/issues/7897)

### Environment

- Sequelize version: ^6.3.4 
- Node.js version: 10.16.3 
- Operating System: Windows 10 64 bits
- If TypeScript related: TypeScript version: ^3.9.7

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X ] I don't know, I was using postgres, with pg 8.3.0 and pg-hstore ^2.3.3

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X ] No, I don't have the time and I wouldn't even know how to start.

**Comment by cozmoc** [comment]
facing the same issue for a year now, not a single workaround mentioned worked for me. I am on v5.22.4

**Comment by osvaldokalvaitir** [comment]
facing the same problem, and still nothing?

**Comment by cozmoc** [comment]
the only workaround that worked for me:

> ChatRoom.findAll({
    where: { id: '1' },
    attributes: {
      include: [
        [
          context.models.Sequelize.literal(`(SELECT timestamp FROM "Messages" WHERE "Messages"."ChatRoomId" = "ChatRoom".id ORDER BY timestamp DESC)`),
          'chatRoomMessageTimestamp'
        ]
      ]
    },
    offset: 0,
    limit: 10,
    order: [[sequelize.literal('"chatRoomMessageTimestamp"'), 'DESC NULLS LAST']],
    include: [{
      model: context.models.Message,
      as: 'Messages',
      order: [['timestamp', 'DESC']],
    }]
  });

**Comment by osvaldokalvaitir** [comment]
??
