### ISSUE TITLE
Slow Response with Sequelize Pagination for Larger Offset

### ISSUE THREAD

**Issue by developer-i-am** [sequelize/sequelize#13172]
I have Huge Data regarding the Product I guess 140 fields split into different Tables. It's Working fine when I select the first page of data but as I go for the 19th or 20th page it gets very slow.

When I Request for Page=1 and pageSize=100 I get response in 35seconds. But As I increase the Page Numbers say 19 It Responds in 8min or even More. Guide me to Some Optimal and More Professional Way. Any Hint would be Appreciated.

`
const page = req.query.page || 1

    const pageSize = req.query.pageSize || 30

    try {

        const data = await BasicProductDetail.findAll({

            include: [

                { model: AdditionalProductDetail },

                { model: Catalog },

                { model: ImageDetail },

                { model: Manufacturer },

                { model: Measurement },

                { model: PriceAndCost },

                { model: ProductClass },

                { model: Selling },

                { model: UPC },

                { model: Usage }

            ],

            limit : pageSize,

            offset : (page - 1) * pageSize,

            order : [ ['id', 'ASC']]

        })

        const count = await BasicProductDetail.count({ })

        res.json({

            data: data,

            count : count

        })

    } catch (error) {

        console.log(error)

        return res.status(500).send(Something Went Wrong!!!)

    }
   `

**Comment by Spekpannenkoek** [comment]
This issue is not related to Sequelize. It's how databases work: https://use-the-index-luke.com/no-offset

Summary of that page (the site is a wonderful resource in general): Don't use pagination with an offset if you need performance. Use something like `/?after=120&pageSize=30` & `WHERE id > 120 LIMIT 30` rather than `/?page=4&pageSize=30`
