### ISSUE TITLE
updateOnDuplicate is ignored for associatiation tables in bulkCreate

### ISSUE THREAD

**Issue by hexerei** [sequelize/sequelize#13181]
### What are you doing?

Tried implementing the _Game, Player, Team_ sample from the documentation with models to test the `bulkCreate` with including associated models. This first didn't work because it obviously creates duplicate entries. So I went for including the `updateOnDuplicate` option, which works fine for the main model object table, and the associated table, but it does not work for the association table itself, as then `ON DUPLICATE KEY UPDATE` is added there without parameters, which throws an error:

```Javascript
  await Game.bulkCreate([
    { name: 'The Big Clash', Teams: [{ id: 1, name: 'The Martians' }, { id: 2, name: 'The Earthlings' }] },
    { name: 'Winter Showdown', Teams: [{ id: 1, name: 'The Martians' }, { id: 3, name: 'The Plutonians' }] },
    { name: 'Summer Beatdown', Teams: [{ id: 2, name: 'The Earthlings' }, { id: 3, name: 'The Plutonians' }] }
  ], { include: [{ model: Team, updateOnDuplicate: ['name'] }] });
```

The SQL sequelize creates looks like this then:

```SQL
INSERT INTO `Games` (`id`,`name`,`createdAt`,`updatedAt`) VALUES
  (NULL,'The Big Clash','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (NULL,'Winter Showdown','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (NULL,'Summer Beatdown','2021-04-09 12:33:20','2021-04-09 12:33:20');
INSERT INTO `Teams` (`id`,`name`,`createdAt`,`updatedAt`) VALUES
  (1,'The Martians','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (2,'The Earthlings','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (1,'The Martians','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (3,'The Plutonians','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (2,'The Earthlings','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (3,'The Plutonians','2021-04-09 12:33:20','2021-04-09 12:33:20')
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `GameTeam` (`createdAt`,`updatedAt`,`TeamId`,`GameId`) VALUES
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',1,1),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',2,1),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',1,2),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',3,2),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',2,3),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',3,3)
  ON DUPLICATE KEY UPDATE;

```

So it works fine for the Games and Teams tables, but the `GameTeam` insert query throws an error because of the `ON DUPLICATE KEY UPDATE` without parameters.

Tried overcoming this by creating models for the `GameTeam` table, so I could add this to the includes and state the update fields:

```Javascript
  await Game.bulkCreate([
    { name: 'The Big Clash', Teams: [{ id: 1, name: 'The Martians' }, { id: 2, name: 'The Earthlings' }] },
    { name: 'Winter Showdown', Teams: [{ id: 1, name: 'The Martians' }, { id: 3, name: 'The Plutonians' }] },
    { name: 'Summer Beatdown', Teams: [{ id: 2, name: 'The Earthlings' }, { id: 3, name: 'The Plutonians' }] }
  ], { include: [{ model: Team, updateOnDuplicate: ['name'] }, { model: GameTeam, updateOnDuplicate: ['GameID','TeamId']}] });

```

This gave another error, stating that `GameTeam` is not related to `Game`. So simply defining my models association with:

```Javascript
Team.belongsToMany(Game, { through: GameTeam });
Game.belongsToMany(Team, { through: GameTeam });
```

was not enough, I had to do the full many-to-many-to-many definition:

```Javascript
Team.belongsToMany(Game, { through: GameTeam });
Game.belongsToMany(Team, { through: GameTeam });
GameTeam.belongsTo(Game);
GameTeam.belongsTo(Team);
Game.hasMany(GameTeam);
Team.hasMany(GameTeam);
```

Now `GameTeam` was allowed in the includes, but the `updateOnDuplicate` for `GameTeam` was still ignored, and the resulting 
SQL still had the `ON DUPLICATE KEY UPDATE` for the `GameTeam` table without parameters, hence still throwing an error.

**Here is the link to the SSCCE for this issue:** [#157](https://github.com/papb/sequelize-sscce/pull/157/) 

### What do you expect to happen?

Now really nice would have been, that I don't need to add the associative GameTeam table to my includes in the bulkCreate options, but unfortunately, if I add an `updateOnDuplicate` option to the included Team model, then sequelize adds the `ON DUPLICATE KEY UPDATE` without parameters to the `INSERT` of the GameTeam table, which causes an error.

First then I added the GameTeam table (which I had not created a model for) with `model: 'GameTeam'` hoping it would be identified as the auto-generated GameTeam table, which was not the case. Fine, created that model then and added it, but still the `updateOnDuplicate` for the GameTeam model was ignored.

_I would have expected sequelize to add my `updateOnDuplicate` fields to the `ON DUPLICATE KEY UPDATE` in the `INSERT` statement._

### What is actually happening?

_The generated SQL for the GameTeam table still had an invalid SQL_

```SQL
INSERT INTO `GameTeam` (`createdAt`,`updatedAt`,`TeamId`,`GameId`) VALUES
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',1,1),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',2,1),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',1,2),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',3,2),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',2,3),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',3,3)
  ON DUPLICATE KEY UPDATE;
```

### Environment

- Sequelize version: 6.6.2
- Node.js version: v14.15.4
- Operating System: macOS Big Sur version: 11.2.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using **mysql**, with connector library mysql2 version 2.2.5 and database version 5.7.1

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by hexerei** [comment]
Actually seems to happen regardless of dialect, because also the run of my SSCCE failed with the same error on all database versions tested. The error is always the same, the table holding the ids for the many-to-many relation is not extended with the updateOnDuplicate parameters.

**Comment by hexerei** [comment]
Noticed today, that this happens on all `.belongsToMany()` associations, where an association table is created, but instead of like my sample above, where the `ON DUPLICATE KEY UPDATE` is passed with an empty clause, I had the situation that the `updateOnDuplicate` parameter I passed to the options of the linked object in the `create()` command, was passed on to the association table, which led to an invalid query of type:

```lang-sql
INSERT INTO `vacancy_certificates` (`created_at`,`updated_at`,`vacancy_id`,`certificate_id`) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
```

Which obviously fails, because the association table has no value _name_.

the create options included:

```lang-javascript
{ model: db.Certificate, updateOnDuplicate: ['name'] }
```

Which I would expect to be correct, as the _name_ field is part of the certificate table, but this parameter was just passed down to the query insert for the association table. Would be smarter to automatically use the association field of association table, if the target has an `updateOnDuplicate` defined, and if there is no custom definition for the association table itself.

**Comment by Luisgustavom1** [comment]
Haven't they corrected it yet?
