### ISSUE TITLE
Specific query option unix_timestamp not being correctly handled by Sequelize

### ISSUE THREAD

**Issue by 64J0** [sequelize/sequelize#13199]
## Issue Description

I'm trying to unix_timestamp syntax in a query with a Model created with Sequelize.

### What are you doing?

**Here is the link to the SSCCE for this issue:** LINK-HERE 

I have a model created with Sequelize and I'm trying to execute a query in a MariaDB database where it uses the *unix_timestamp* syntax to correctly handle the dates passed in the command. The syntax I'm using is this:

```js
const scheduledVideos = await ScheduledVideos
  .findAll({
    where: {
      id_plan: app_id,
      ts: {
        [Op.between]: [`unix_timestamp('${start}')`, `unix_timestamp('${end}')`],
      }
    },
    order: [["id", "ASC"]],
    raw: true,
    nest: true,
  });
```

### What do you expect to happen?

I wanted to get a syntax that works and gives me the correct values, like the one demonstrated in the next piece of code.

```bash
Executing (default): SELECT `id`, `ts`, `src` FROM `scheduled_videos` AS `ScheduledVideos` WHERE `ScheduledVideos`.`id_plan` = '36411' AND `ScheduledVideos`.`ts` BETWEEN unix_timestamp('2021-04-15T17:53:01.000Z') AND unix_timestamp('2021-04-15T17:53:38.000Z') ORDER BY `ScheduledVideos`.`id` ASC;
```

### What is actually happening?

Looking at the console I saw that Sequelize is transforming this command in:

```bash
Executing (default): SELECT `id`, `ts`, `src` FROM `scheduled_videos` AS `ScheduledVideos` WHERE `ScheduledVideos`.`id_plan` = '36411' AND `ScheduledVideos`.`ts` BETWEEN 'unix_timestamp(\'2021-04-15T17:53:01.000Z\')' AND 'unix_timestamp(\'2021-04-15T17:53:38.000Z\')' ORDER BY `ScheduledVideos`.`id` ASC;
```
This syntax is incorrect since the unix_timestamp should be outside the quotes, so it gives me the incorrect values.

### Additional context

https://www.w3resource.com/mysql/date-and-time-functions/mysql-unix_timestamp-function.php

### Environment

- Sequelize version: "^6.5.0" 
- Node.js version: "v14.16.0" 
- Operating System: Ubuntu 20.04
- If TypeScript related: TypeScript version: "^4.2.3"

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by 64J0** [comment]
I think that if there's a way to combine raw queries with models it would resolve my problem because in this situation I could only write this between syntax with query syntax and use it.

**Comment by Spekpannenkoek** [comment]
Use `sequelize.fn` ([some examples](https://sequelize.org/master/manual/model-querying-basics.html#advanced-queries-with-functions--not-just-columns-)).

Sequelize _needs to_ escape your input—what if the value for `end` contained SQL like `0 OR true` ?

```
[Op.between]: [sequelize.fn('unix_timestamp', start), sequelize.fn('unix_timestamp', end)]

// builds a condition like BETWEEN unix_timestamp("...") AND unix_timestamp("...")
```

**Comment by 64J0** [comment]
Thanks @Spekpannenkoek it worked!! But I think that I found a bug in the types of ```[Op.between]``` definition. This project I'm developing is using ```Typescript``` and when I use this syntax of two *sequelize.fn* for the *[Op.between]* the IDE shows this warning:

**Comment by 64J0** [comment]
Well, I think that this issue can be closed now since the problem has been resolved with the suggestion of @Spekpannenkoek . For this typescript definition bug I'll open other issue (#13203).
