### ISSUE TITLE
Model. increment returns [undefined, number] instead of the affected rows

### ISSUE THREAD

**Issue by eliezra236** [sequelize/sequelize#13205]
## Issue Description: I am trying to use the model.increment and it seem to not work properly. 
Instead of getting [AffectedRows, number] I am getting [undefined, number] although some arrows where affacted.

### What are you doing?

```js

// DB file

const SearchModel = sequelize.define(
  "SearchModel",
  {
    ID: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true
    },
    Name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
    },
    SearchesCounter: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
    },
  },
  { tableName: "SearchHistory" }
);

// then I do the search in another file after exporting sequelize 

  let DBResults = await searchModel.increment("SearchesCounter", {
    returning: true,
    where: {
      Name: {
        [Op.or]: searches, // searches is array of strings
      },
    },
  });
```

### What do you expect to happen?

I expected to get an array with the affected rows so I can use them later for read.

_I wanted Foo!_

### What is actually happening?

I am getting [ [undefined, number], number ]

### Environment

- Sequelize version: 6.6.2 
- Node.js version: 14.5.1 
- Operating System: windows 10

### How does this problem relate to dialects?

- [ V] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [V ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
I think only Postgres supports `RETURNING` (in Sequelize at least, anyway. SQLite itself has support for it, but it has some caveats). Are you using a different database, like MySQL?

**Comment by eliezra236** [comment]
> I think only Postgres supports `RETURNING` (in Sequelize at least, anyway. SQLite itself has support for it, but it has some caveats). Are you using a different database, like MySQL?
> 
> It's not as good as the increment & returning combo, but for most usages it'd be okay to do a `findAll`, followed by a `increment` with `where: { id: { [Op.in]: searchResults.map(row => row.id) } }`, I recon.

Yea, I am using MySQL.

So I should just do another query later with the same filter and do a findAll() to see which rows were affected?
I try to minimize on queries here

**Comment by bflatmajor** [comment]
Same issue in 6.23.2, any updates?
