### ISSUE TITLE
QueryInterface.escape is not a function - but defined in Types

### ISSUE THREAD

**Issue by intellix** [sequelize/sequelize#13225]
## Issue Description

Using Postgres adapter and have updated from 4.x to 6.5.x and this:

```ts
sequelize.getQueryInterface().escape('"hey"');
```

Gives the following error:

```
TypeError: getQueryInterface(...).escape is not a function
```

Method defined as being available here: 
https://github.com/sequelize/sequelize/blob/v6/src/dialects/abstract/query-interface.d.ts#L659-L662

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- x ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I can submit a PR but I'm not sure if this is dialect-specific or how much of QueryInterface type definition is true/false

**Comment by intellix** [comment]
not stale

**Comment by bgovi** [comment]
Did this ever get resolved?

**Comment by vird** [comment]
Maybe sequelize.Validator.escape is good alternative?

**Comment by ephys** [comment]
It's not fixed https://github.com/sequelize/sequelize/blob/v6/src/dialects/abstract/query-interface.d.ts#L662

**Comment by ephys** [comment]
Closed by https://github.com/sequelize/sequelize/pull/15944
