### ISSUE TITLE
Sequelize showing error: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by chuksdsilent** [sequelize/sequelize#13221]
I am trying to update a record in mysql database using sequelize but it is not working.

I am getting this error

Unexpected token u in JSON at position 0

Model

    module.exports = sequelize.define("branches", {
    address: Sequelize.TEXT(),
    company: Sequelize.STRING(),
     codeConfig: {
         type: Sequelize.STRING,
        allowNull: false,
       get: function () {
        return JSON.parse(this.getDataValue('codeConfig'));
       },
       set: function (val) {
        return this.setDataValue('codeConfig', JSON.stringify(val));
       }
      },

      });
Update function

     router.put('/:id', async (req, res) => {

     const { address, company} = req.body;

     try {

    const branches = await Branches.findOne({ where: { code: req.params.id } });
    if (!branches) return res.json({ msg: "Branch Not Found" });

    Branches.update({ "address": "No. 10 distreet street" }, {
        where: {
            code: "WHJ5uBdriI"
        }
    }).then(function (newBranch) {
        return res.json({ msg: "Updated" });
    });

     } catch (error) {
        console.error(error.message);
        res.status(500).send("Server Error");
     }

     });

Error output
Unexpected token u in JSON at position 0

**Comment by Spekpannenkoek** [comment]
It's very likely that the value for `codeConfig` is undefined. This is probably happening:

1. The value is `undefined`.
2. You call `JSON.parse()` on that value.
3. `undefined` starts with a `u`.
4. There's not supposed to be a `u` outside of a string in JSON: It's _an unexpected token_ (value).
5. It's the very first character (and we start counting from 0): _at position 0_.

The JSON standard does not support `undefined` but it does support `null`.
