### ISSUE TITLE
Can't get sequelize to recognize/use my custom foreign key

### ISSUE THREAD

**Issue by Sequoia** [sequelize/sequelize#13232]
*💡EDIT: If you're encountering this issue and need a workaround see [below](#issuecomment-828830030)*

### What are you doing?

* Associating two models (`User` hasMany `Letters`, `Letters` belongsTo `User`)
* Using a custom foreign key (`users.author_id`)
* Saving a "letter"

```js
const { DataTypes, Model } = require('sequelize');
// const sequelize = new Sequelize(process.env.DATABASE_URL, options); etc....
//
const sequelize = require('./database/sequelize-client');

class Letter extends Model {}

Letter.init({
  id: {
    type: DataTypes.STRING,
    primaryKey: true,
    allowNull: false,
    defaultValue: sequelize.fn('uuid_generate_v4')
  },
  contents: {
    type: DataTypes.TEXT,
    allowNull: false,
  },
  draft: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
  }
}, {
  tableName: 'letters',
  sequelize,
  createdAt: 'createdat',
  updatedAt: 'updatedat'
});

class User extends Model {}

User.init({
  id: {
    type: DataTypes.STRING,
    primaryKey: true,
    allowNull: false,
    defaultValue: sequelize.fn('uuid_generate_v4'),
  },
  email: {
    type: DataTypes.STRING,
    allowNull: false
  },
  password: {
    type: DataTypes.STRING,
    allowNull: true,
  },
  email_verified: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  }
}, {
  tableName: 'users',
  sequelize,
  createdAt: 'createdat',
  updatedAt: 'updatedat'
});


User.hasMany(Letter);
Letter.belongsTo(User,{
  foreignKey: {
    allowNull: false,
    name: 'author_id',
    field: 'author_id',
  },
  onDelete: 'CASCADE',
  as: 'author',
})

sequelize.sync({ force: true, match: /_test$/ });
```

### What do you expect to happen?

Table looks like this:
```
                              Table "public.letters"
  Column   |           Type           | Collation | Nullable |      Default
-----------+--------------------------+-----------+----------+--------------------
 id        | character varying(255)   |           | not null | uuid_generate_v4()
 contents  | text                     |           | not null |
 draft     | boolean                  |           |          | false
 createdat | timestamp with time zone |           | not null |
 updatedat | timestamp with time zone |           | not null |
 author_id | character varying(255)   |           | not null |
Indexes:
    "letters_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "letters_author_id_fkey" FOREIGN KEY (author_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
```

👉  **Uses _my_ foreign key name** ✅

Queries such as those produced by....

```js
User.create({
  email: "a@a.com",
  password: "abc123",
})
.then(user =>{
  return Letter.create({
    contents: "abc",
    draft: false,
    AuthorID: user.id, // I'm grasping at straws here....
    author_id: user.id
  })
});
```

👉  **DO NOT refer to** `UserId` ✅

### What is actually happening?

Table looks like this:

```
                              Table "public.letters"
  Column   |           Type           | Collation | Nullable |      Default
-----------+--------------------------+-----------+----------+--------------------
 id        | character varying(255)   |           | not null | uuid_generate_v4()
 contents  | text                     |           | not null |
 draft     | boolean                  |           |          | false
 createdat | timestamp with time zone |           | not null |
 updatedat | timestamp with time zone |           | not null |
 UserId    | character varying(255)   |           |          | ⁉️
 author_id | character varying(255)   |           | not null |
Indexes:
    "letters_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "letters_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL ⁉️
    "letters_author_id_fkey" FOREIGN KEY (author_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
```

👉 Has `UserId` ❌ 

Query like produced by above refers to `UserID` ❌:

```sql
Executing (default): INSERT INTO "letters" ("id","contents","draft","createdat","updatedat","author_id") VALUES (uuid_generate_v4(),$1,$2,$3,$4,$5) RETURNING "id","contents","draft","createdat","updatedat","UserId","author_id";
```

Where did `RETURNING ... "UserId"` come from?

### Additional context

* Postgres
* Using uuid extension

### Environment

- Sequelize version: 6.6.2 
- Node.js version: v14.16.1 
- Operating System: osx 10.15.6 (19G2021)
- If TypeScript related: TypeScript version: N/A

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Depends on complexity. I am happy to help but my time is limited.
- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Sequoia** [comment]
I'm either using this completely wrong or this custom foreign key feature is not working properly (I suspect the latter in either case). In order to get this to work, I've had to discard all custom everything (field name, `as: "Author"` relation name) and go with built-in defaults (column name `"UserId"` in quotes for postgres to capitalize it, field name `.UserId`) to get it to work.

* The query builder adds `RETURING ... "UserId"` *no matter what, in all cases*, I can't make it stop doing this
* If I add `as: "Author"` to the relation, it tries to return an `AuthorId` *and* a `UserId`
  * it also complains that I'm missing either AuthorId or UserId or both... it seems to be aware that there should be a column called AuthorId but *still thinks there should also be a column named `UserId`
* No amount of customizing the foreignKey `field`, `name` or anything makes it stop trying to `RETURING ... "UserId"`

### Workaround
Strip away all foreign key/field customization and go with whatever sequelize expects by default ☹️

**Comment by Sequoia** [comment]
# Better workaround: `Letter.removeAttribute('UserId')`

This works:
```
// ... from above
User.hasMany(Letter);
Letter.belongsTo(User,{
  foreignKey: {
    allowNull: false,
    name: 'author_id',
    field: 'author_id',
  },
  onDelete: 'CASCADE',
  as: 'Author',
})

Letter.removeAttribute('UserId');

sequelize.sync({ force: true, match: /_test$/ })
.then(() =>{
  return User.create({
    email: "a@a.com",
    password: "abc123",
  })
})
.then(user =>{
  return Letter.create({
    contents: "abc",
    draft: false,
    author_id: user.id
  })
})
.then(letter => console.log(letter.toJSON()));
```

It shouldn't be necessary I don't think (?) If I add a **named** relation, Sequelize should not also add a field/relation based on the other name, but this workaround lets me use custom foreign keys :+1:

**Comment by alok182011** [comment]
I found a solution to this after trying a lot of things the way you can make it recognize your custom foreign key is by providing it in both , example -

User.hasOne(models.Address, {
        foreignKey: "user_id",
      });

Address.belongsTo(models.User, {
        foreignKey: "user_id",
      });

**Comment by rikinhim2** [comment]
> I found a solution to this after trying a lot of things the way you can make it recognize your custom foreign key is by providing it in both , example -
> 
> User.hasOne(models.Address, { foreignKey: "user_id", });
> 
> Address.belongsTo(models.User, { foreignKey: "user_id", });

you save my day!

**Comment by dapabe** [comment]
This is rather an implicit behaviour that should be pinned to be referenced when working with Foreign Keys in Sequelize
