### ISSUE TITLE
reDOS in validator dependency 10.11.0

### ISSUE THREAD

**Issue by DevRCRun** [sequelize/sequelize#13239]
in various functions including isEmail and detailed at https://snyk.io/test/npm/validator/10.11.0

Is it possible to switch to using 13.6.0 so we can resolve this alert please?

**Comment by mvlasovatl** [comment]
Hey guys! My team is also affected by the vulnerability in old `validator` version. Are there any estimates for it to be fixed?

**Comment by uralsemih** [comment]
We also affected.. Is there any estimation date for this fixing ?

**Comment by Keimeno** [comment]
Will track this in #12783, thanks for raising the issue!

**Comment by papb** [comment]
Upgraded to v13 (#13350), this is now available at [v6.6.5](https://github.com/sequelize/sequelize/releases/tag/v6.6.5), thank you all, sorry to take long!
