### ISSUE TITLE
TypeError: attr[0].includes is not a function

### ISSUE THREAD

**Issue by Jazcash** [sequelize/sequelize#13249]
## Issue Description

I get the same error whenever I try to use any kind of `Sequelize.fn` function. 

E.g. `await players.findAll({ attributes: [[Sequelize.fn('DISTINCT', Sequelize.col('teamId')) ,'teamId']] });`

Compiles fine, but spits out:
```
(node:21204) UnhandledPromiseRejectionWarning: TypeError: attr[0].includes is not a function
    at C:\Users\jaz\Repos\bar-db\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1438:29
```

I put a log at that point in query-generator.js and it logs out: `[ Fn { fn: 'DISTINCT', args: [ [Col] ] }, 'teamId' ]`, but for some reason still skips past the `if (attr[0] instanceof Utils.SequelizeMethod) {` check, I suspect this is the issue but I don't know why it doesn't recognise it as a Sequelize method.

### Environment

- Sequelize version: 6.6.2 
- Node.js version: 12.8.3 
- Operating System: Windows 10
- If TypeScript related: TypeScript version: 4.1.3
- Dialect: PostgreSQL 13.1, compiled by Visual C++ build 1914, 64-bit

**Comment by Jazcash** [comment]
Nvm, just realised it's because I was using `npm link` and have my database abstraction layer as another local module and for some reason my `import { Sequelize, WhereAttributeHash } from "sequelize";` import was referencing the version in that module's node_modules folder. So the `instanceof` check failed because the class it was checking against was sourced from a different file...

**Comment by pratham-scaletech** [comment]
Any Update, I got the same issue

**Comment by 7-happy** [comment]
got the same error, but if i remove Sequelize.fn from attributes, the error disappear
  attributes: [[Sequelize.fn('count', Sequelize.col('ticketNo')), 'sum']]            ==> error occur
  attributes: []																								  ==> correct		
  
  async findAllTicketsum(serviceId, type) {
    const device = new XCEBikeStock(this.agentId || 2);
    const deviceDAO = await device.daoWithAgentId();
    this._DAO.belongsTo(deviceDAO, { foreignKey: 'imei', targetKey: 'imei' });
    const deviceInfo = {};
    let queryInfo = {
      type: type,
      state: FIXHANDLE_TYPE.To_prcd
    }
    if (serviceId) deviceInfo.serviceId = serviceId;
    const result = await this._DAO.findAndCountAll({
      include: [{
        model: deviceDAO,
        where: deviceInfo,
        required: true
      }],
      where: queryInfo,
      attributes: [
        [Sequelize.fn('count', Sequelize.col('ticketNo')), 'sum']
      ],
      raw: true,
    });
    return result;
  }

**Comment by anderson-matheus** [comment]
I update my sequelize from `6.6.5` to `6.33.0`, after that, it works

**Comment by magicdawn** [comment]
It's caused by multi version sequelize.

and cause fail detect of `instanceof Utils.SequelizeMethod`

```
if (attr[0] instanceof Utils.SequelizeMethod) {
  attr[0] = this.handleSequelizeMethod(attr[0]);
  addTable = false;
} else if (this.options.attributeBehavior === "escape" || !attr[0].includes("(") && !attr[0].includes(")")) {
  attr[0] = this.quoteIdentifier(attr[0]);
}
```

Maybe a symbol match can handle these cases better:

```
const sSequelizeMethod = Symbol()

// attach symbol in SequelizeMethod constructor
class SequelizeMethod {
  constructor(){
    this[sSequelizeMethod] = true
  }
}

// use symbol detect insteadof `instanceof`
if (attr[0][sSequelizeMethod]) {
  // ...
}
```
