### ISSUE TITLE
Failed to connect to *name_server* - getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by eugenestepanyuk** [sequelize/sequelize#13242]
### What are you doing?

**tsconfig**

```
"compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
      "sourceMap": true,
      "outDir": "./dist",
      "rootDir": "./source",
      "moduleResolution": "node",
      "removeComments": true,
      "noImplicitAny": true,
      "strictNullChecks": true,
      "strictFunctionTypes": true,
      "noImplicitThis": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noImplicitReturns": true,
      "noFallthroughCasesInSwitch": true,
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "resolveJsonModule": true
    },
    "exclude": ["node_modules"],
    "include": ["./source/**/*.tsx", "./source/**/*.ts"]
  }
```

**Sequelize connection**

```
import { Sequelize } from 'sequelize'
import { environment } from '../config'
import { normalize, join } from 'path'

export default new Sequelize(environment.database.database, environment.database.username, environment.database.password,  {
  dialect: "mssql",
  host: environment.database.host,
  logging: !environment.production ? console.log : false,
  dialectOptions: {
    options: {
      enableArithAbort: true,
      cryptoCredentialsDetails: {
        minVersion: "TLSv1",
      },
    },
  },
})


try {
    await database.authenticate()

    express()
      .listen(environment.port, () =>
        !environment.production
          ? console.log(
              `Server was started up on http://localhost:${environment.port}`
            )
          : null
      )
  } catch (error) {
    console.log(error.message)
  }
```

### What do you expect to happen?

connection only by name (ANJUTA2 \ SQL2016)

### What is actually happening?

an error occurs when connecting the server to the database
`Failed to connect to ANJUTA2 \ SQL2016: 1433 - getaddrinfo ENOTFOUND ANJUTA2 \ SQL2016`

how to make a connection only by name (ANJUTA2 \ SQL2016), why does it tighten the port if I do not specify it?

### Environment

- Sequelize version: 6.3.5
- Node.js version: 13.10.1
- Operating System: Windows 10
- If TypeScript related: TypeScript version: 3.9.9

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by enkopvand** [comment]
I think you might need to use the domain specific login, in the documentations here: https://sequelize.org/v7/manual/dialect-specific-things.html

**Comment by enkopvand** [comment]
I think you might need to use the domain specific login, in the documentations here: https://sequelize.org/v7/manual/dialect-specific-things.html

I have a a DB on a domain called server.com\x2016 which I can connect perfectly to with tedious and doing:

```
const config = {
server: 'const s = server.com\x2016'
authentication: {
    type: 'default',
    options: {
      userName, // update me
      password, // update me
    },
  },
  options: {
    // If you are on Microsoft Azure, you need encryption:
    encrypt: true,
    database, // update me
  },
};
```

with Sequelize I need to do the following to connect:

```
const sequelize = new Sequelize(d, null, null, {
  host: 'server.com,
  dialect: 'mssql',
  dialectOptions: {
    authentication: {
      type: 'default',
      options: {
        userName:
        password,
      },
    },
    options: {
      instanceName: 'x2016',
      encrypt: true,
    },
  },
});
`

Notice how the host here is just 'server.com' while the instance where the MSSQL DB I want to connect to is in instanceName without the \
```

I hope this helps you.
