### ISSUE TITLE
Error parsing url: undefined

### ISSUE THREAD

**Issue by chuksdsilent** [sequelize/sequelize#13246]
I deployed my app I built with nodejs, sequelize and mysql

I ran my migrations and it is giving the following error.

    Loaded configuration file "config/config.json".
    Using environment "production".

     Error parsing url: undefined

Config.json

{
 "development": {
"username": "root",
"password": null,
"database": "erp",
"host": "127.0.0.1",
"dialect": "mysql"
 },
"test": {
"username": "root",
"password": null,
"database": "database_test",
"host": "127.0.0.1",
"dialect": "mysql"
},
 "production": {
"use_env_variable": "<url>",
"operatorAliases": "false",
"dialect": "mysql",
"dialectOptions": {
  "ssl": {
    "require": true,
    "rejectUnauthorized": false
  }
}
}
}

Production.json

{
   "use_env_variable": "<url>"
}

**Comment by AyresMonteiro** [comment]
I think that the "host" field is required to connect to your database, so, if you're using a database in the same server just put '127.0.0.1' in the "production.host" field. If you're using another server, use the server's IP Address. Don't forget the "production.port" field too, so you won't  be able to connect to the database.
