### ISSUE TITLE
I used the transaction twice, and I got into a deadlock.

### ISSUE THREAD

**Issue by sjLee-cashwalk** [sequelize/sequelize#13265]
## Issue Description

I used the transaction twice, and I got into a deadlock.
There was no error, and the ec2 instance was continuously created, and eventually the server died.
Using the transaction only once solved the problem, but I would like to know the exact reason. Could you please tell me a reference or why?

- Sequelize version: 5.19.8
- Node.js version: 10.15.0
- Operating System:amazon

**Comment by eseliger** [comment]
Can you please provide more details on what you are doing? Ie. a code snippet.

**Comment by S-cloud-art** [comment]
controller Logic

 const transaction = await sequelize.transaction();
await userUpdateInfo(user,transaction);

service Logic
exports.userUpdateInfo = async function userUpdateInfo({
  user = {}, // user object
  transactionFunction,
  transaction,
}) {
  const now = getDate();
  const yearMonthDate = getISOString({ date: now, length: 10 });
  const owner = user.id;


  // sequelize 트랜잭션이 생성되어있지 않다면 트랜잭션을 생성시켜준다
  const isTransactionInternal = !transaction;
  if (isTransactionInternal) transaction = await sequelize.transaction();

  try {
    const parallelList = [];
    const where = { id: user.id, date: yearMonthDate.slice(0, 7),};
    let userObj = await user.findOne({ where, transaction });

      userObj.total += point;
      userObj.totalPlus += point;

    parallelList.push(user.increase({ where, value, transaction }));
    parallelList.push(userlog.increase({ where: { id: user.id }, value: { click: user.click }, transaction }));

    await Promise.all(parallelList);

    if (transactionFunction) await transactionFunction({ pointObj, point, transaction });
  } catch (err) {
    if (isTransactionInternal) await transaction.rollback();
    throw err;
  }
  if (isTransactionInternal) await transaction.commit();

**Comment by S-cloud-art** [comment]
> I still don't understand, you pass in a `SequelizeTransaction` and then use it as `transactionFunction` and await it? That's not possible, a transaction is no async function.

Thanks, I found the reason.
It wasn't the problem that duplicate transactions were used, but the logic that triggered rollback and commit.
Thanks, thanks for letting me know that the transaction is not async logic.
But I have a question.
Why do we use await before sequelize.transaction on this page?

https://sequelize.org/master/class/lib/transaction.js~Transaction.html

**Comment by JFernando122** [comment]
There are (at least) 2 ways to do transactions.

The one you are using in the snippet above calls the transaction function with no params, which return the transaction object, that the you decide when/where to commit or rollback.

The second option (The one on the docs) passes a callback as a parameter, in that case the commit/rollback depends on the resolution of the promise (generated by the call back) if its resolved it commits, if its rejected it rollbacks.
This also returns whatever the callback function returns
