### ISSUE TITLE
[Help]How to use this SQL code in sequelize?

### ISSUE THREAD

**Issue by fish0373** [sequelize/sequelize#13275]
How to use this sql code in sequelize?
SQL engine is SQL Server
```
SELECT 
    Collect.*, books.bookCount
FROM 
    Collect
LEFT JOIN
    (SELECT book.collectId, COUNT(*) AS bookCount FROM Book group by collectId) AS books
    ON books.collectId = Collect.collectId
```
I tried some ways
like 'group by'
but I think that is not best
can someone help me?

**Comment by hanrea** [comment]
// reference


products.findAll({
    attributes: [Sequelize.col('u.userName'), 'prdName', 'price'],
    include: [{
        model: user,
        as: 'u',
        attributes: []
    }],
    where: {
        prdName: 'ipad',
        '$u.userId$': 1
    },
    raw: true
}).then(result => {
    console.log(JSON.stringify(result))
}).catch(err => {
    console.log(err)
})

// SQL 
SELECT u.userName, p.prdName, p.price FROM products AS p LEFT OUTER JOIN user AS u ON p.userId = u.userId WHERE p.prdName = ‘ipad’ AND u.userId = 1;


// Model

const DataTypes = Sequelize.DataTypes;
const user = sequelize.define('u', {
    userId: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    userName: {
        type: DataTypes.STRING,
        allowNull: true
    },
    birthDay: {
        type: 'TIMESTAMP',
        allowNull: false
    },
    gender: {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: 0
    },
    ctime: {
        type: 'TIMESTAMP',
        allowNull: false,
        defaultValue: Sequelize.literal('CURRENT_TIMESTAMP')
    },
    updatedAt: {
        type: 'TIMESTAMP',
        defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
        field: 'ctime'
    }
}, {
        tableName: 'user'
    })

const products = sequelize.define('p', {
    prdId: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    prdName: {
        type: DataTypes.STRING,
        allowNull: false
    },
    userId: {
        type: DataTypes.INTEGER,
        allowNull: false
    },
    price: {
        type: DataTypes.DECIMAL(5, 4),
        allowNull: false
    }
})

products.belongsTo(user, { foreignKey: 'userId', targetKey: 'userId', as: 'u' });
