### ISSUE TITLE
Sequelize fails to construct valid queries when searching for arrays inside of JSON columns.

### ISSUE THREAD

**Issue by mikefowler** [sequelize/sequelize#13272]
### What are you doing?

SSCCE: https://github.com/papb/sequelize-sscce/pull/161

```ts
class Foo extends Model {}

Foo.init({
  name: DataTypes.TEXT,
  criteria: DataTypes.JSON
}, {
  sequelize,
  modelName: 'Foo'
});

await Foo.create({
  name: "TS foo",
  criteria: { foo: [1, 2] },
});

// The following .findAll throws an error
await Foo.findAll({
  where: {
    criteria: {
      foo: [1, 2],
    },
  },
});
```

### What do you expect to happen?
I expect that:

1. No error is thrown
2. The instance of `Foo` I created is returned

### What is actually happening?

Sequelize is constructing an invalid and throwing an error at the database adapter level. For SQLite, the following (invalid) query is generated:

```sql
SELECT
  `id`,
  `name`,
  `criteria`
FROM
  `Foos` AS `Foo`
WHERE
  CAST(
    json_extract(`Foo`.`criteria`, '$.foo') AS DOUBLE PRECISION
  ) = 1,
  2;
```

The full error:

```
DatabaseError [SequelizeDatabaseError]: SQLITE_ERROR: near ",": syntax error
    at Query.formatError (/Users/mike_fowler/Code/Github/sequelize-sscce/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/Users/mike_fowler/Code/Github/sequelize-sscce/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/Users/mike_fowler/Code/Github/sequelize-sscce/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/Users/mike_fowler/Code/Github/sequelize-sscce/node_modules/sqlite3/lib/sqlite3.js:14:21) {
  parent: [Error: SQLITE_ERROR: near ",": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `id`, `name`, `criteria` FROM `Foos` AS `Foo` WHERE CAST(json_extract(`Foo`.`criteria`,'$.foo') AS DOUBLE PRECISION) = 1, 2;"
  },
  original: [Error: SQLITE_ERROR: near ",": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `id`, `name`, `criteria` FROM `Foos` AS `Foo` WHERE CAST(json_extract(`Foo`.`criteria`,'$.foo') AS DOUBLE PRECISION) = 1, 2;"
  },
  sql: "SELECT `id`, `name`, `criteria` FROM `Foos` AS `Foo` WHERE CAST(json_extract(`Foo`.`criteria`,'$.foo') AS DOUBLE PRECISION) = 1, 2;",
  parameters: undefined
}
```

### Additional context

n/a

### Environment

- Sequelize version: 6.6.2
- Node.js version: 12.22.1
- Operating System: macOS Big Sur

### How does this problem relate to dialects?

I discovered this issue while using MySQL, but found the same behavior with SQLite.

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MySQL, SQLite (at least)
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
To search for an array that contains an element, you'd use `[Op.contains]`, something like `"criteria.foo": { [Op.contains]: 1 }`. [Op.contains](https://sequelize.org/master/manual/model-querying-basics.html#postgres-only-range-operators) is Postgres only, however. MySQL, to my knowledge, has no operator to search in JSON objects. Neither does SQLite.

While SQLite doesn't have an operator or function to easily do what you want, you could do it as follows. It's long and messy but works. 

You first find the array with values you're interested in (`[1, 2]`), then join that as if it were a table (json_each), then run a WHERE on that. Wrap that in a subquery and you can use `IN`. 

```
  await Foo.findAll({
    where: {
      id: {[Op.in]: sequelize.literal(`
        (SELECT subquery.id
           FROM Foos as subquery,
                json_each(
                  json_extract(subquery.criteria, '$.foo')
                ) AS subquery_json
          WHERE subquery_json.value IN (1, 2) )
     `)},
    }
  });
```

If you want to look for 1 AND 2, it gets a bit longer:

```
  await Foo.findAll({
    where: {
      [Op.and]: [
        {id: {[Op.in]: sequelize.literal(`
          (SELECT subquery.id
             FROM Foos as subquery,
                  json_each(
                    json_extract(subquery.criteria, '$.foo')
                  ) AS subquery_json
            WHERE subquery_json.value = 1)
         `)},
        },
        {id: {[Op.in]: sequelize.literal(`
          (SELECT subquery.id
             FROM Foos as subquery,
                  json_each(
                    json_extract(subquery.criteria, '$.foo')
                  ) AS subquery_json
            WHERE subquery_json.value = 2)
         `)},
        },
      ] // end of OR/AND
    } // end of WHERE
  });
```

`json_extract(table.column, '$.path.to.value')` finds a value in a JSON object or array. In your case `[1, 2]`

`json_each` turns each element of a JSON object or array into a row.  
This virtual table has columns like `key` and `value`, the latter of which will be 1 or 2 in your example. Imagine that in the subquery, you're querying a table that looks like this:

```
subquery.id | subquery_json.key | subquery_json.value
          1 |                 0 | 1
          1 |                 1 | 2
```

In MySQL you should be able to use the function [JSON_CONTAINS](https://stackoverflow.com/questions/36249828/how-to-search-json-array-in-mysql) with `sequelize.fn` which returns a boolean if a column at a given path contains a value but I don't have a MySQL install to figure that out.
