### ISSUE TITLE
NodeJS api stop working when error generates from sequelize - UnhandledPromiseRejectionWarning: TypeError: errors.ConnectionAcquireTimeoutError is not a constructor

### ISSUE THREAD

**Issue by shaileshsakaria** [sequelize/sequelize#13285]
## We are facing the issue in production environment only. We are getting only the below error logs from it. Please note, we are using sequelize version v6.3.5. 

node:17620) UnhandledPromiseRejectionWarning: TypeError: errors.ConnectionAcquireTimeoutError is not a constructor at ConnectionManager.getConnection (W:\Q2C\Publish\fjt.api\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:288:48) at async W:\Q2C\Publish\fjt.api\node_modules\sequelize\lib\sequelize.js:613:26 at async MySQLQueryInterface.bulkUpdate (W:\Q2C\Publish\fjt.api\node_modules\sequelize\lib\dialects\abstract\query-interface.js:867:12) at async Function.update (W:\Q2C\Publish\fjt.api\node_modules\sequelize\lib\model.js:3175:28)

(node:17620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10100)

Can you please let me know how we can handle this error so that at least our api service can not be stopped. Or is it resolved in the latest version?

**Comment by hanrea** [comment]
This is a basic nodejs knowledge issue，Promise function  need catch error。 
Try it ：
```javascript
try{
      let  user = await UserModel.findOne({});
}catch(err){
      // catch it!
}

// OR
UserModel.findOne({}).then((result)=>{

},(err)=>{
   // catch it!
})

// OR
UserModel.findOne({}).then((result)=>{

}).catch((err)=>{
   // catch it!
})
```

Please study promise and async/await carefully!

**Comment by shaileshsakaria** [comment]
The error message is specific, like,
TypeError: errors.ConnectionAcquireTimeoutError is not a constructor

Is it due to something missing in sequelize package? as it shows the stack trace within line number in sequelize js (e.g. sequelize.js:613:26)

**Comment by hanrea** [comment]
Refer to this  ： https://github.com/sequelize/sequelize/issues/12364    !  Check whether the network is normal
