### ISSUE TITLE
Usages for Sequelize.where

### ISSUE THREAD

**Issue by Kstar0722** [sequelize/sequelize#13283]
## Issue Description
I am upgrading sequelize version from 4.x to 6.x and I have a problem with `Sequelize.where`
The problem is I can't compare `number` or `boolean` in `Sequelize.where`
I checked params of `Sequelize.where`. I am worried about second param LogicType.
I see there's no `number` or `boolean` type. also I can't use `[Op.and]` directly as well. b/c `WhereOperators` interface does not have property [Op.and].

(it was working in sequelize v4.x)

so I do like to use like `Sequelize.where(Sequelize.fn('month', Sequelize.col('dob')), month)` but it throws type error.
also I can't use `Sequelize.where(Sequelize.fn('month', Sequelize.col('dob')), { [Op.eq]: month })` either. b/c as I said above `WhereOperators` does not have `[Op.eq]` property.

so I have to use like

```
Sequelize.where(Sequelize.fn('month', Sequelize.col('dob')), { [Op.and]: [{ [Op.eq]: month }] })
```

Is there any other easier solution?
it's kind of messy to use `[Op.and]` with `[Op.eq]` for compare single value.

thanks

### StackOverflow / Slack attempts

I didn't post it to SlackOverflow

### Additional context
N/A

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by AllAwesome497** [comment]
A bit confused on what you're trying to accomplish here. 

Are you trying to get a where clause that ensures that both `dob` (a `BOOLEAN` column) and `month` (an `INTEGER` column) are truthy (ie not null)? 

If so, I'd imagine what you'd want would be similar to:
```js
Sequelize.where({
    [Op.and]: [
        {
            dob: true
        }, 
        {
            month: { [Op.ne]: null }
        },
    ],
});
```

Regardless, please provide more info such as:
- What you're trying to do at a high level. Eg, "Get every instance where a is false and b is null"
- What the model definitions specific to this example are. 

A bit more reference here [https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#tell-us](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#tell-us)

**Comment by AllAwesome497** [comment]
Also: to make code samples more readable, please [tag the code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) with the language of their content (adds syntax highlighting).

**Comment by kimpeupeu** [comment]
i faced exactly same problem.
I am trying to query some data which datetime column equals specific month.
sql: `where month(createdat) = 8`
ts: `Sequelize.where(
          Sequelize.fn('month', Sequelize.col('createdAt')),
          8,
        )`

but this code throw such error: `Argument of type 'number' is not assignable to parameter of type 'LogicType'.ts(2345)` at 8

**Comment by kimpeupeu** [comment]
use 
```ts
`${month}`
```
