### ISSUE TITLE
TypeScript complains about $nested.column$ syntax in query where clause.

### ISSUE THREAD

**Issue by MarkMurphy** [sequelize/sequelize#13288]
### What was unclear/insufficient/not covered in the documentation

TypeScript complains about `$nested.column$` syntax in query where clause. Because the where clause is typed as needing to be attributes of the model being queried, this syntax triggers an error since these object keys are not attributes of the model.

### If possible: Provide some suggestion on how we can enhance the docs

Maybe this is a bug if it's intended to work but otherwise the documentation seems to be lacking how to resolve this.

### Additional context

<img width="1380" alt="Screen Shot 2021-05-26 at 10 11 41 AM" src="https://user-images.githubusercontent.com/873474/119665455-ca6ca400-be0a-11eb-9589-f24ca025ff2d.png">

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by belisarenata** [comment]
Same problem here. TS indicates No overload match, but works just fine when a ts ignore flag is set to the nested clause as a workaround:   
![Screenshot from 2021-05-27 14-08-44](https://user-images.githubusercontent.com/40744589/119868161-172ca980-bef5-11eb-8389-e378fa3a5959.png)


Also, at Sequelize V.5 this does not raise any errors.

**Comment by aryem** [comment]
@MarkMurphy Can you specify sequelize version.
In v6.6.5 `WhereOptions` have `Literal` that should support nested column literal.
https://github.com/sequelize/sequelize/blob/56bb1d6ef9827f604d7bcef945abb7e213f2322d/types/lib/model.d.ts#L112

**Comment by aryem** [comment]
I have added additional tests to ensure nested column in where option in #13478

**Comment by ephys** [comment]
I have a PR in progress for this https://github.com/sequelize/sequelize/pull/13983
