### ISSUE TITLE
Multiple calls to findOrCreate() can cause memory leak on PostgreSQL

### ISSUE THREAD

**Issue by wfelipew** [sequelize/sequelize#13289]
## Issue Description

* Multiples calls to "findOrCreate()" on the same connection can cause a memory leak on PostgreSQL backend process
* The problem is related to the use of  "CREATE OR REPLACE FUNCTION pg_temp.testfunc().. " (query-generator.js) on each call to "findOrCreate()"
* A similar problem was reported on the PostgreSQL mailing list some years ago (https://www.postgresql-archive.org/BUG-14403-Large-numbers-of-CREATE-OR-UPDATE-function-causes-memory-exhaustion-td5928178.html).. PostgreSQL probably is creating cache
entries for these functions on first execution, and not reclaiming them before the end of the session.

### What are you doing?

Here is minimal code to reproduce the problem:
```js
( async () => {


const Sequelize = require('sequelize')
const sequelize = new Sequelize('memleak','memleak','PASSWORD',{
    dialect: 'postgres', host:'127.0.0.1',
    dialectOptions: {
        application_name: 'memleak_test'
    }})

const Memleak = sequelize.define( 'memleak', {
   
    id: {
        type: Sequelize.BIGINT,
        autoIncrement: false,
        allowNull: false,
        primaryKey: true
    },
    data : {
        type: Sequelize.STRING
    }
    },{
        timestamps : false,
        freezeTableName	: true,
        name: {
            singular: 'memleak',
            plural: 'memleak'
        }
    }
)

for (i=0;i<1000000;i++) {
    const result = await Memleak.findOrCreate({
        where: {
            id: i
        },
        defaults : {
            id: i,
            data: 'test'+i
        }
    })
}
//console.log(result)
})();
```

SQL schema:
```sql
CREATE TABLE public.memleak (
    id bigint NOT NULL PRIMARY KEY,
    data character varying
);
```

### What do you expect to happen?

I expected that the resident memory usage of the PostgreSQL backend process is constant over time.

### What is actually happening?

The resident memory usage of the PostgreSQL backend process is growing linearly over time. After 10 minutes the PostgreSQL backend is using more than 1GB of memory.

Shell script to monitor resident memory consumption:
```bash
#!/bin/bash

export PGPASSWORD=PASSWORD
psql -Aqt -U memleak -h 127.0.0.1 -d memleak -c "TRUNCATE TABLE memleak"

node index.js  > /dev/null &

PID=$(psql -Aqt -U memleak -h 127.0.0.1 -d memleak -c "SELECT pid FROM pg_stat_activity WHERE application_name='memleak_test'")

while true; do 
	sleep 2; 
	if [ ! -f /proc/$PID/status ]; then
		PID=$(psql -Aqt -U memleak -h 127.0.0.1 -d memleak -c "SELECT pid FROM pg_stat_activity WHERE application_name='memleak_test'")
	fi
	date=$(date '+%Y-%m-%d %H:%M:%S')
	memuse=$(grep VmRSS /proc/$PID/status | awk '{print $2}' ) ; 
	echo "$date , $memuse" >> reportjs.txt; 
done;
```
Metrics collected:
[https://pastebin.com/bbwJgcJU](https://pastebin.com/bbwJgcJU)
[https://imgur.com/2k7Rlz9](https://imgur.com/2k7Rlz9)

### Environment

- Sequelize version: 6.6.2 
- Node.js version: v14.17.0
- Operating System: Ubuntu 20.04

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Keimeno** [comment]
Does the issue linked in [this](https://github.com/sequelize/sequelize/issues/9276#issuecomment-845344960) comment solve your problem?

**Comment by wfelipew** [comment]
This problem can be mitigated by setting the "maxUses" on the connection pool which force a connection "recycle" after a specified number of operations.
Results running "maxUses=1000": https://imgur.com/a/No6VBeL

**Comment by Lele** [comment]
I stumbled upon the same issue with the following configuration:

* Sequelize version: 6.32.1
* Postgres version: 11.17

Frequent and subsequent calls to findOrCreate caused the leak described above.
