### ISSUE TITLE
Importing models defined in a separate npm package causes associate to error out (something not a subclass of Sequelize.Model)

### ISSUE THREAD

**Issue by nbkhope** [sequelize/sequelize#13280]
### What are you doing?

Defining a model that includes association in a separate npm package and requiring it in my project. That model associates with another model defined in the separate package.

When a server application that uses Sequelize is run it errors out.

Example:

```
// 'my-npm-package'
// Person.js model
module.exports = (sequelize, DataTypes) => {
  const Person = sequelize.define('Person', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
    },
  }, { tableName: 'persons' });

  Person.associate = (models) => {
    Person.hasMany(models.Pet);
  };

  return Person;
};
```

```
// 'my-npm-package'
// Pet.js
module.exports = (sequelize, DataTypes) => {
  class Pet extends Model {
    static associate(models) {
      Pet.belongsTo(models.Person);
    }
  };

  Pet.init({
    person_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'persons',
        key: 'id'
      }.
    }
  }, {
    tableName: 'pets'
  });
  return Pet;
};
```

```
// my-project
// models/Person.js
module.exports = require('my-npm-package/Person');
```

```
// my-project
// models/Pet.js
module.exports = require('my-npm-package/Pet');
```

### What do you expect to happen?

There is no error message.

### What is actually happening?

An error message occurs:

```
[...] /node_modules/sequelize/lib/associations/mixin.js:18
      throw new Error(`${this.name}.hasMany called with something that's not a subclass of Sequelize.Model`);
      ^

Error: Person.hasMany called with something that's not a subclass of Sequelize.Model
[...]
```

### Additional context

When you copy and paste the code from the separate package into your own project, it works without errors.

### Environment

- Sequelize version: 6.6.2
- Node.js version: v14.15.4
- Operating System: Ubuntu 18.04
- ~~If TypeScript related: TypeScript version: XXX~~

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by nbkhope** [comment]
My project uses `require('sequelize')` which is different from the `require('sequelize')` inside the npm package. Because of that this problem occurs.

For those who faced the same problem, I found a workaround by passing the imported Sequelize's Model from my project down to the external npm package. Wherever you do your hook to associate, add a parameter for Model from the side of the project, not the npm package:

```
const Sequelize = require('sequelize');
const sequelize = new Sequelize(...);

// ...

const db = {
  Person: require('../models/Person')(sequelize, Sequelize.DataTypes, Sequelize.Model),
  Pet: require('../models/Pet')(sequelize, Sequelize.DataTypes, Sequelize.Model),
}
```

From the perspective of you npm package:

```
// Person.js
module.exports = (sequelize, DataTypes, Model) => {
  // ...
}

// Do the same for other model. In this example, Pet.js.
```

**Comment by eliasrodeloso** [comment]
Opening this again since is still happening AND we shouldn't need to do a workaround to try to solve this.
