### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: model.js require() of ES modules is not supported.

### ISSUE THREAD

**Issue by mdodge-ecgrow** [sequelize/sequelize#13299]
## Issue Description

I have switched over to Node v14 and Sequelize v6 for my application.  I am also using ES modules with `"type": "module"` in my package.json file.  So in my models folder I have my index.js that auto-reads in all the model files and builds the models automatically.  With Sequelize v5, this code was working wonderfully:
```js
fs.readdirSync(__dirname)
	.filter((file) => {
		return (
			file.indexOf('.') !== 0 &&
			file !== basename &&
			file.slice(-3) === '.js'
		);
	})
	.forEach((file) => {
		const model = sequelize['import'](path.join(__dirname, file));
		db[model.name] = model;
	});
```

Now I have learned with v6, the import method has been removed for some reason.  And I discovered with lots of Googling that this is the recommended way to do it instead.
```js
const model = require(path.join(__dirname, file))(
			sequelize,
			Sequelize.DataTypes
		);
```

But then I get this error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\....\models\Permissions.js
require() of ES modules is not supported.
require() of C:\......\Permissions.js from C:\......\models\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename Permissions.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\.....\package.json.
```
And here is my Permissions.js file:
```js
'use strict';

module.exports = (sequelize, DataTypes) => {
	return sequelize.define(
		'Permission',
		{
			id: {
				type: DataTypes.INTEGER,
				autoIncrement: true,
				primaryKey: true,
			},
			type: {
				type: DataTypes.STRING,
				required: true,
				allowNull: false,
			},
			created_at: {
				type: DataTypes.DATE,
			},
			updated_at: {
				type: DataTypes.DATE,
			},
			deleted_at: {
				type: DataTypes.DATE,
			},
		},
		{
			underscored: true,
			paranoid: true,
		}
	);
};
```

This is where my Google-fu is failing me.  Changing the model file to .cjs does fix that error, but I'd rather not go that route.  I have several models I would have to rename and I would like a cleaner fix.

### StackOverflow / Slack attempts

If you have tried asking on StackOverflow / Slack about this, add a link to that here.
https://stackoverflow.com/questions/67827111/sequelize-v6-typeerror-sequelize-import-is-not-a-function

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): Sequelize v6
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
It's a little bit of a pain because it introduces a promise where previously everything was sync, but you can dynamically import a file like so:

```
const modules = Promise.all( fs.readdirSync(__dirname)
	.filter((file) => {
		return (
			file.indexOf('.') !== 0 &&
			file !== basename &&
			file.slice(-3) === '.js'
		);
	})
	// Map over every file & return a promise each.
	.map((file) => {
		// Change 'default' if you 'export const Xyz' rather than 'export default Xyz' 
		return import(file).then(module => module.default);
	}).map((module) => {
		return module(
			sequelize,
			Sequelize.DataTypes
		);
	})
);

// Export it so you can await the results elsewhere.
export default modules;
```

`import()` is for [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports). It returns a promise because `import` and `import()` can never be done sync.

You should await the `Promise.all()`. You might have `sequelize.sync` in your app somewhere already. That'd a good place:

```
import { sequelize } from './my-sequelize-db';
import promiseThatResolvesToModels from './file-listed-above.js';

await promiseThatResolvesToModels;
await sequelize.sync();

// or promiseThatResolvesToModels.then(() => sequelize.sync).then(...)

// start rest of app
```

**Comment by mdodge-ecgrow** [comment]
Wow, this is very helpful.  Thank you!

I am trying to implement it and getting the error `TypeError: module is not a function` on this line: `return module(sequelize, Sequelize.DataTypes);` inside the second "map" block.

**Comment by Spekpannenkoek** [comment]
You must have a file in that folder that does not export a function like your `Permissions.js` file does (`module.exports = (sequelize, Datatypes) => { ... }`). 

Why not just filter those out? `(typeof module !== 'function')` ?

Or do something like:

```
return import(file).then((module) => {
  if (typeof module.default !== 'function') {
    throw new Error(`Expected ${file} to export a function but got ${typeof module.default}, ${Object.keys(module)}`);
  }
  return module;
}).then(module => module.default);
```

You'll have to debug this yourself. If all of your files are the same shape as Permissions.js, this _should_ work fine.

**Comment by mdodge-ecgrow** [comment]
I think I am getting so close on this one.  Wondering if you can look at this code and see what the issue might be.

CreateModels.js
```js
import fs from 'fs';
import path from 'path';
import { dirname } from 'path';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const basename = path.basename(__filename);
import Sequelize from 'sequelize';
import config from '../config/config.js';
import { fileURLToPath } from 'url';

const sequelize = new Sequelize(config);

const modules = Promise.all(
	fs
		.readdirSync(__dirname)
		.filter((file) => {
			return (
				file.indexOf('.') !== 0 &&
				file !== basename &&
				file.slice(-3) === '.js'
			);
		})
		// Map over every file & return a promise each.
		.map((file) => {
			console.log({ file });
			// Change 'default' if you 'export const Xyz' rather than 'export default Xyz'
			// return import(file).then((module) => module.default);
			// return import(file)
			return import(file)
				.then((module) => {
					console.log({ module });
					if (typeof module.default !== 'function') {
						throw new Error(
							`Expected ${file} to export a function but got ${typeof module.default}, ${Object.keys(
								module
							)}`
						);
					}
					return module;
				})
				.then((module) => module.default);
		})
		.map((module) => {
			console.log({ module });
			return module(sequelize, Sequelize.DataTypes);
		})
);

// Export it so you can await the results elsewhere.
export default modules;
```

I'm getting `TypeError: module is not a function` on that last return statement.  That last console is printing out: `{ module: Promise { <pending> } }`.

**Comment by mdodge-ecgrow** [comment]
OK, so based on my last comment, I tried this:
`	.map((module) => {
			// console.log({ module });
			return module.then((r) => r(sequelize, Sequelize.DataTypes));
		})`

And it appears to be working.  Now I am getting other errors, but it does appear to be getting further now!  Let me know if that code above seems sketchy.  Thank you so much!

**Comment by mdodge-ecgrow** [comment]
Well, it was a long agonizing process, probably a week or more!!  But I finally got my project working with Node 14, Sequelize 6 and ES modules!!!  Hopefully the devs at Sequelize can create some up-to-date docs on how to properly import models using modern versions of the libraries.

Now time to go delete a whole ton of trial and error code!

**Comment by RealDrewKlayman** [comment]
@mdodge-ecgrow How'd you go about fixing this?

**Comment by mdodge-ecgrow** [comment]
@RealDrewKlayman  I never did get migrations or seeding working with this.  I'm still doing a lot manually which is a pain, but it is what it is.
