### ISSUE TITLE
Incorrect typescript typings for findAndCountAll function

### ISSUE THREAD

**Issue by vinay-naik** [sequelize/sequelize#13302]
### What are you doing?

I am trying to strongly type my application using Typescript and Sequelize. I have noticed the following behaviour of the `findAndCountAll` function. 
1. When no group by is supplied it returns `Promise<{ rows: M[]; count: number }>`.
2. When group by is supplied it returns `Promise<{ rows: M[]; count: { count: number }[]>>`

The current type of Sequelize `findAndCountAll` is 
```js
  public static findAndCountAll<M extends Model>(
    this: ModelStatic<M>,
    options?: FindAndCountOptions<M['_attributes']>
  ): Promise<{ rows: M[]; count: number }>;
```

### What do you expect to happen?

Since `findAndCountAll` returns two different results the type should ideally be 

```js
  public static findAndCountAll<M extends Model>(
    this: ModelStatic<M>,
    options?: FindAndCountOptions<M['_attributes']>
  ): Promise<{ rows: M[]; count: number | { count: number }[]>;
```
I have noticed other attributes also being returned inside the count object so just a `count :  { count: number }` might not work.

### What is actually happening?

As discussed in [this issue](https://github.com/sequelize/sequelize/issues/6148) to return the proper count I need to take a count of the returned count array. But since the type says count is a number I am unable to do so.

```js
    const allUsersRaw = await this.User.findAndCountAll({
        attributes,
        include,
        where,
        order,
        limit,
        offset,
        group: ["Order.id"],
        subQuery: false
    });
    const count = allUsersRaw.count.length;
```

Following error is thrown

```
Property 'length' does not exist on type 'number'. ts(2339)
 ```

### Environment

- Sequelize version: 6.6.2 
- Node.js version: v16.3.0 
- Operating System: MacOs BigSur 11.4
- If TypeScript related: TypeScript version: 4.3.2

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Keimeno** [comment]
Ideally, this should be done with function overloading.
```ts
public static findAndCountAll<M extends Model>(
  this: ModelStatic<M>,
  options?: FindAndCountOptions<M['_attributes']> & {group: undefined}
): Promise<{ rows: M[]; count: number }>;
public static findAndCountAll<M extends Model>(
  this: ModelStatic<M>,
  options?: FindAndCountOptions<M['_attributes']> & {group: GroupOption}
): Promise<{ rows: M[]; count: number[] }>;
```
This allows us to dynamically generate a return type based on the developer's input

**Comment by Patil2099** [comment]
I would love to take up this issue @Keimeno.

**Comment by vinay-naik** [comment]
@Keimeno I agree 

But just to ensure that we can pass generic va

**Comment by aryem** [comment]
#13477 would close this issue.
