### ISSUE TITLE
[Question] How to make associated model as `LEFT OUTER JOIN` in query without `required: true`

### ISSUE THREAD

**Issue by danilvalov** [sequelize/sequelize#13307]
## Issue Description

I have 3 tables:
- `Articles` (id, date, title, text)
- `Photos` (id, articleId, imageUrl)
- `TopArticleOrders` (id, articleId, order: number)

The last `topArticleOrders` table contains optional sorting rule for some articles. Containing articles in the table are on top of article list and have inner sorting using this table. Other articles are sorted by `article.date` field.

For the article table I made the following model (I use sequelize-typescript):

```typescript
@Table({
  timestamps: true,
})
export class Article extends Model {
  @CreatedAt
  @Default(DataType.NOW)
  @Column
  date: Date;

  @Column(DataType.STRING)
  title: string;

  @Column(DataType.TEXT)
  text: string;

  @HasMany(() => Photo)
  photos: Photo[];

  @HasOne(() => TopArticleOrder)
  top: TopArticleOrder | null;
}
```

And after I added a new method to get list of articles with sorting by:
1. `top ASC NULLS LAST` first (if article **has** record in TopArticleOrders table)
2. `date ASC` after (if article **doesn't have** record in TopArticleOrders table):

```typescript
static list(offset: number, limit: number): Promise<{ count: number; rows: Article[] }> {
  return this.findAndCountAll({
    include: [
      {
        model: Photo,
      },
      {
        model: TopArticleOrder,
        attributes: ['order'],
      },
    ],
    order: [
      [TopArticleOrder, 'order', 'ASC NULLS LAST'],
      ['date', 'ASC'],
    ],
    distinct: true, // to fix incorrect `count` value because `photos` field adds duplicates records
    offset,
    limit,
  });
}
```

But I get the following SQL:
```sql
SELECT "Article".*,
       "photos"."id"            AS "photos.id",
       "photos"."articleId"     AS "photos.articleId",
       "photos"."imageUrl"      AS "photos.imageUrl",
FROM (SELECT "Article"."id",
             "Article"."date",
             "Article"."title",
             "Article"."text",
             "top"."id"            AS "top.id",
             "top"."order"         AS "top.order"
      FROM "Articles" AS "Article"
      ORDER BY "Article"."date" ASC
      -- Sequelize limits in the subquery
      LIMIT 30 OFFSET 30) AS "Article"
-- Sequelize adds LEFT OUTER JOIN for `top` after limiting
LEFT OUTER JOIN "TopArticleOrders" AS "top" ON "Article"."id" = "top"."articleId"
LEFT OUTER JOIN "Photos" AS "photos" ON "Article"."id" = "photos"."articleId"
-- Ordering by `top` works incorrect because articles are limited already before sorting
ORDER BY "top"."order" ASC NULLS LAST, "Article"."date" ASC;
```

and I need to change my query to fix sorting problem to the following:
```sql
SELECT "Article".*,
       "photos"."id"            AS "photos.id",
       "photos"."articleId"     AS "photos.articleId",
       "photos"."imageUrl"      AS "photos.imageUrl",
FROM (SELECT "Article"."id",
             "Article"."date",
             "Article"."title",
             "Article"."text",
             "top"."id"            AS "top.id",
             "top"."order"         AS "top.order"
      FROM "Articles" AS "Article"
      -- Move LEFT OUTER JOIN to subquery
      LEFT OUTER JOIN "TopArticleOrders" AS "top" ON "Article"."id" = "top"."articleId"
      -- Move ORDER BY "top"."order" to subquery
      ORDER BY "top"."order" ASC NULLS LAST, "Article"."date" ASC
      LIMIT 30 OFFSET 30) AS "Article"
LEFT OUTER JOIN "Photos" AS "photos" ON "Article"."id" = "photos"."articleId";
```

My attempts to solve this problem:
1. If I add `subQuery: true` then Sequelize limits no articles, Sequelize limits records (with duplicates of articles because photos have multiple records).
2. If I add `required: true` for `TopArticleOrder` include, then Sequelize removes all articles without records in TopArticleOrders table, but I just need to sort articles by `top.order` if there is top order record for article and to sort by `date` if there is not top order record.

#### Question

How to move `LEFT OUTER JOIN "TopArticleOrders" AS "top" ON "Article"."id" = "top"."articleId"` and `ORDER BY "top"."order" ASC NULLS LAST, "Article"."date" ASC` to the subquery? I don't want to write the query manually using Sequelize.literal.

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

**Comment by danilvalov** [comment]
Solved my problem using attribute with sql.

```typescript
static list(offset: number, limit: number): Promise<{ count: number; rows: Article[] }> {
  return this.findAndCountAll({
    include: [
      {
        model: Photo,
      },
    ],
    attributes: {
      include: [
        [
          Sequelize.literal(
            `(
                SELECT "order" as "topOrder"
                FROM "TopArticleOrders"
                WHERE
                    "TopArticleOrders"."articleId" = "Article"."id"
                LIMIT 1
              )`
         ),
         'topOrder',
        ],
      ],
    },
    order: [
      [Sequelize.col('topOrder'), 'ASC NULLS LAST'],
      ['date', 'ASC'],
    ],
    distinct: true,
    offset,
    limit,
  });
}
```

But I won't close this issue because someone knows how to solve my problem nicely. I don't like my solution.

**Comment by ambrt** [comment]
I was searching a lot  for a way to do similar thing (operate on included model column) but all ways i tried and found were doing same as your first sql example.

I think that only way to access associated model column and operate on it is through sql in literal like in your solution post.

**Comment by danilvalov** [comment]
@ambrt You're right. I used Sequelize.literal to solve my problem
