### ISSUE TITLE
TSVECTOR DataType not in Typescript typings

### ISSUE THREAD

**Issue by nchen63** [sequelize/sequelize#13316]
`TSVECTOR` is missing in `datatypes.d.ts`

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, thanks for the report.

Next time please report problems with TypeScript like this one using the Bug template instead of the feature request template 😬
