### ISSUE TITLE
Sorting doesn't work for includes associations

### ISSUE THREAD

**Issue by EgoBrainProgrammer** [sequelize/sequelize#13319]
### I am selecting instances with associated records. And trying to sort related rows.

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
const records = await this.entityRepository.findAll<Entity>({
            include: [
                {
                    association: Entity.associations.entities1,
                    order: [['id', 'ASC']] //--Sorting doesn't work--
                }
            ]
        });
```

### What do you expect to happen?

_I wanted sorted array of entity1 objects!_

### What is actually happening?

_The output was unsorted array of entity1 objects!_

```
[14, 11, 12, 13]
```

### Environment

- Sequelize version: ^6.5.0 
- Node.js version: v12.18.1 
- Operating System: Windows 10
- sequelize-typescript version: ^2.1.0
- If TypeScript related: TypeScript version: ^4.0.5

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using PostgreSQL, with connector library version XXX and database version 11.10

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
The `include` option [doesn't have](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findAll) an `order` field.

To [order by an associated table's fields](https://sequelize.org/master/manual/model-querying-basics.html#ordering), put `order` outside the `include` object:

```
{
  include: ...,
  order: [ [Entity.associations.entities1, 'id', 'ASC'] ],
}
```

**Comment by Keimeno** [comment]
#13304 is related to this
If you set `separate` to `true` inside the `include`, ordering should work as well. See https://github.com/sequelize/sequelize/issues/13304#issuecomment-858036192

But as @Spekpannenkoek mentioned, it probably makes more sense to put the `order` statement outside `include`.

**Comment by Keimeno** [comment]
Also, the `order` field does exist on `include`, if `separate` is set to true. I'll keep this open as a docs issue.

**Comment by EgoBrainProgrammer** [comment]
> 
> 
> The `include` option [doesn't have](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findAll) an `order` field.
> 
> To [order by an associated table's fields](https://sequelize.org/master/manual/model-querying-basics.html#ordering), put `order` outside the `include` object:
> 
> ```
> {
>   include: ...,
>   order: [ [Entity.associations.entities1, 'id', 'ASC'] ],
> }
> ```

**Comment by Keimeno** [comment]
As mentioned, let's keep this open, since our documentation doesn't cover the `order` field (and probably more)
