### ISSUE TITLE
Sequelize returns empty array but sql-query returns correct records

### ISSUE THREAD

**Issue by danilvalov** [sequelize/sequelize#13311]
### What are you doing?

I have a simple structure:
Table of articles and table of comments for articles.
To count comments for some article by dates I make the following query:

```js
Comment.findAll({
  attributes: [
    [Sequelize.literal(`DATE("createdAt")`), 'date'],
    [Sequelize.literal(`COUNT(*)`), 'count'],
  ],
  raw: true,
  group: ['date'],
});
```

SQL from console:
```sql
SELECT DATE("createrdAt") AS "date", COUNT(*) AS "count"
FROM "Comments" AS "Comment"
GROUP BY "date";
```

I get the following response in sequelize:
```js
[
  '2021-06-12': 5,
  '2021-06-13': 2
]
```

It works correctly. But...

If I add `include` with `articles` relation (I have `ForeignKey` and `BelongsTo` relation in `Comments` table to `Articles` table) and condition + `required: true`, I receive empty array:

```js
const categoryId = 'test';

Comment.findAll({

  // I added the following `include` param:
  include: [
    {
      model: "Article",
      attributes: [],                      //   I don't need attributes, and I don't want to add `Article.id` to `group` of query
      where: {
        categoryId: categoryId,            // Article table has `categoryId` field
      },
      required: true                       // If `required: false` then result array is not empty! But I need `required: true` :\
    }
  ],

  attributes: [
    [Sequelize.literal(`DATE("createdAt")`), 'date'],
    [Sequelize.literal(`COUNT(*)`), 'count'],
  ],
  raw: true,
  group: ['date'],
});
```

SQL from console:
```sql
SELECT DATE("createrdAt") AS "date", COUNT(*) AS "count"
FROM "Comments" AS "Comment"
INNER JOIN "Articles" AS "Article" ON "Comment"."articleId" = "Article"."id" AND "Article"."categoryId" = 1
GROUP BY "date";
```

But if I copy sql query from console (I use `logging: true` in sequelize) and execute it manually I receive actual array with correct records

### What do you expect to happen?

I wanted to see not empty array

### What is actually happening?

The output was empty array

### Environment

- Sequelize version: 6.5.0
- Node.js version: 12.20.1
- Operating System: MacOS 11.4
- TypeScript version: 3.9.9
- Dialect: Postgres

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using Postgres, with connector pg library version 8.5.1 and database version 11.10

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by danilvalov** [comment]
Sorry, but that was my mistake. And I don't even know where I did something wrong. Just tried it again today and it works.

**Comment by akash87** [comment]
if you remove raw:true, it will not work.
