### ISSUE TITLE
queryInterface.dropTable('table_name') without options argument Object throws an Error when any Attribute Contains an ENUM for Postgres Dialect

### ISSUE THREAD

**Issue by JustinMGaiam** [sequelize/sequelize#13337]
## Issue Description
The `queryInterface.dropTable('table_name')` when used without an options argument Object throws an Error when any attribute Contains an ENUM for Postgres Dialect.

### What are you doing?
Attempting to run `queryInterface.dropTable('table_name')` with out providing optional options object.

```js
db.define('table_name', {
  uuid: {
    type: DataTypes.UUIDV4,
    allowNull: false,
    unique: true,
    primaryKey: true,
    comment: 'The primary identifier for this record',
  },
  status: {
    type: DataTypes.ENUM('paused', 'active'),
    allowNull: false,
    defaultValue: 'paused',
    comment: 'The status',
  },
})
// Throws TypeError: Cannot set property 'supportsSearchPath' of undefined
await queryInterface.dropTable('table_name')
```

### What do you expect to happen?

The table to be dropped

### What is actually happening?

An error is thrown

```
TypeError: Cannot set property 'supportsSearchPath' of undefined
```

### Environment

- Sequelize version: 6.6.2
- Node.js version: v14.16.1
- Operating System:  Mac OS 11.4 Big Sur

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by JustinMGaiam** [comment]
Here is the exact line where the error is thrown

https://github.com/sequelize/sequelize/blob/main/lib/dialects/postgres/query-interface.js#L237

**Comment by gabrielhpugliese** [comment]
Also happens to me but I am calling `sequelize.drop()` to drop all tables but if I call `.drop({force: true})` it does not happen.

**Comment by leviwheatcroft** [comment]
I just ran into this, exactly as described by @JustinMGaiam

Sequelize, postgres, same error when dropping a table with an enum datatype.

Sequelize version: 6.28.0
Node verison: 19.8.1
OS: Ubuntu

In my case, the table *is* actually dropped despite the error.

Also the workaround described by @gabrielhpugliese works. No error if called as in `await Model.drop({ force: true })`
