### ISSUE TITLE
Slow sequelize

### ISSUE THREAD

**Issue by sm2017** [sequelize/sequelize#13331]
## Issue Description

I an using `fetchAll` with `limit` to fetch result from postgres, the query takes 100-1500ms in sequelize, but if I copy past the qenerated query in psql it taks 2ms

Sequelize, psql and postgres are in the same machine

### StackOverflow / Slack attempts

https://stackoverflow.com/questions/68046141/slow-postgres-result

### Additional context

https://stackoverflow.com/questions/68046141/slow-postgres-result#comment120269621_68046141

> maybe node.js fetches the results one row at a time, leading to more than a few network round trips?

As far as I know by default sequelize fetches all rows once ready, is sequelize fetches the results one row at a time?

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Keimeno** [comment]
Can you please provide a [SSCCE](https://github.com/papb/sequelize-sscce) for this?

**Comment by sm2017** [comment]
@Keimeno  Added https://github.com/papb/sequelize-sscce/pull/168
