### ISSUE TITLE
Instance Methods and Properties returned from Query are undefined

### ISSUE THREAD

**Issue by jgudo** [sequelize/sequelize#13339]
## What you are doing?

I am querying for a user using ```findOne```  method but the methods and properties of the returned instance  are undefined. To be honest, it applies to all type of query that I perform. 

I am using ```Sequelize``` with ```TypeScript``` in defining my model. 

```
interface IUserAuthAttributes {
  user_auth_id: number;
  username: string;
  password: string;
  full_name: string;
  disable_user: number;
  user_level_id: number;
  created_modified: string | Date;
}

interface IUserAuthCreationAttributes
  extends Optional<IUserAuthAttributes, 'user_auth_id'> { }

export class UserAuth
  extends Model<IUserAuthAttributes, IUserAuthCreationAttributes>
  implements IUserAuthAttributes {
  public user_auth_id!: number;
  public username!: string;
  public password!: string;
  public full_name!: string;
  public disable_user: number;
  public user_level_id!: number;
  public created_modified: string | Date;

  public getRole: () => 'meter_reader' | 'evaluator' | null;
}

UserAuth.init({
  user_auth_id: {
    autoIncrement: true,
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: true,
    primaryKey: true
  },
  username: {
    type: DataTypes.STRING(20),
    allowNull: false,
    defaultValue: ""
  },
  password: {
    type: DataTypes.STRING(100),
    allowNull: false,
    defaultValue: ""
  },
  full_name: {
    type: DataTypes.STRING(100),
    allowNull: false,
    defaultValue: ""
  },
  disable_user: {
    type: DataTypes.TINYINT,
    allowNull: false,
    defaultValue: 0
  },
  user_level_id: {
    type: DataTypes.TINYINT,
    allowNull: false,
    defaultValue: 18
  },
  created_modified: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: Sequelize.literal('CURRENT_TIMESTAMP')
  }
},
  {
    sequelize: DBInstance,
    tableName: 'user_auth',
    timestamps: false
  }
);

UserAuth.prototype.getRole = function () {
  let role = null;

  if (this.user_level_id === 13) {
    role = 'meter_reader';
  } else if (this.user_level_id === 9) {
    role = 'evaluator';
  }

  return role;
}

```

### What do you expect to happen?
I expect the returned user to be able to execute the ```getRole```  instance method and return expected result but fails to execute it and says that ```TypeError: foundUser.getRole is not a function```. Trying to access to other properties like ```username``` also fails and I still have to use the ```getDataValue``` method like ```getDataValue('username')``` to access the username property. I could also use the ```get``` method ```const user = foundUser.get({ plain: true })``` or add the ```{ raw: true }``` on my query to have access on the properties but not on the instance method. 

### What is actually happening? 
This is the code that I'm trying to run. 
```
async login(req: Request, res: Response, next: NextFunction) {
        try {
            const { username, password } = req.body;

            // Check if username exists
            const foundUser = await UserAuth.findOne({
                where: {
                    [Op.or]: [
                        { user_level_id: 9 },
                        { user_level_id: 13 },
                    ],
                    username: username,
                    disable_user: 0
                },
                attributes: {
                    include: ['user_auth_id', 'username', 'password', 'disable_user']
                },
            });

            if (!foundUser) {
                return next(new ErrorHandler(401, 'Incorrect credentials.'));
            }

            console.log(foundUser.getRole()); // TypeError: foundUser.getRole is not a function

            res.status(200).json(foundUser);
        } catch (err) {
            next(err);
        }
    }
```

While inspecting the returned user from the query, using ```console.log(foundUser)```, this is what it returns.
```
UserAuth {
  dataValues: {
    user_auth_id: 11,
    username: 'dhel',
    password: '$2a$10$AgiooENdIcVvwK.KQCmAgecT04qgcYbTvzqJ/j0wW/MxvBBVTdV1m',
    full_name: 'ADELFA BALATBAT',
    disable_user: 0,
    user_level_id: 9,
    created_modified: 2021-06-21T11:37:29.000Z
  },
  _previousDataValues: {
    user_auth_id: 11,
    username: 'dhel',
    password: '$2a$10$AgiooENdIcVvwK.KQCmAgecT04qgcYbTvzqJ/j0wW/MxvBBVTdV1m',
    full_name: 'ADELFA BALATBAT',
    disable_user: 0,
    user_level_id: 9,
    created_modified: 2021-06-21T11:37:29.000Z
  },
  _changed: Set(0) {},
  _options: {
    isNewRecord: false,
    _schema: null,
    _schemaDelimiter: '',
    raw: true,
    attributes: [
      'user_auth_id',
      'username',
      'password',
      'full_name',
      'disable_user',
      'user_level_id',
      'created_modified',
      'user_auth_id',
      'username',
      'password',
      'disable_user'
    ]
  },
  isNewRecord: false,
  user_auth_id: undefined,
  username: undefined,
  password: undefined,
  full_name: undefined,
  disable_user: undefined,
  user_level_id: undefined,
  created_modified: undefined,
  toUserJSON: undefined,
  getRole: undefined
}
```

As you can see from the returned User from above, the instance methods ```getRole``` is undefined as well as properties outside ```dataValues```.

### Which dialect you are using ?
I am using ```mysql```

### Which sequelize version you are using?
I am using using ```sequlize: 6.6.2```  ```mysql2: 2.2.5``` ```typescript:.4.2.4```

### More info
I am using ```ts-node: 9.1.1``` , ```tsconfig-paths:3.9.0``` in order to compile and  resolve path aliases on my typescript code. 
and start my server with this script ```"start": "nodemon --exec ts-node --files -r tsconfig-paths/register src/index.ts"```

My tsconfig.json
```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [ "esnext", "esnext.asynciterable" ],
    "baseUrl": ".",
    "paths": { 
        "@/*": [  "./src/*" ]  
    },
    "typeRoots": [ "./node_modules/@types",  "./src/types" ],
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "pretty": true,
    "sourceMap": true,
    "outDir": "./build",
    "allowJs": true,
    "noEmit": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "include": [  "./src/**/*",  ".sequelizerc", ".env"  ],
  "exclude": [ "node_modules" ],
}
```

It would be really helpful if you can give me an insight as to why this is happening.

**Comment by jgudo** [comment]
To anyone who's been going through the same problem, I managed to solve the issue by setting methods inside the class definition. 

However, accessing properties directly like ```this.username``` will still return undefined. You can access properties using ```getDataValue``` method ```this.getDataValue('username')``` or with ```get``` method ```const user = this.get({ plain:true })```

```
export class UserAuth
  extends Model<IUserAuthAttributes, IUserAuthCreationAttributes>
  implements IUserAuthAttributes {

  public user_auth_id!: number;
  public username!: string;
  public password!: string;
  public full_name!: string;
  public disable_user: number;
  public user_level_id!: number;
  public created_modified: string | Date;

  // Set the method here
   getRole() {
    const user = this.get({ plain: true });

    let role = null;

    if (user.user_level_id === 13) {
      role = 'meter_reader';
    } else if (user.user_level_id === 9) {
      role = 'evaluator';
    }

    return role;
  }
}
```

**Comment by TheCelebrimbor** [comment]
@jgudo  I am having the same issue, using `.get` or `.getDataValue` defeats the purpose. Can you reopen this issue? I'd like to hear from the maintainers

**Comment by jgudo** [comment]
@TheCelebrimbor I'm with you. I don't know what caused this problem. Before, I was able to get properties directly from returned query. I didn't even upgrade/downgrade any of my dependencies.

**Comment by maximepalau** [comment]
Experiencing the same issue on my end, using: `sequelize: 6.6.5`, `mysql2: 2.2.5` and `typescript : 4.3.5`

**Comment by nabilzhafri** [comment]
Having same issue here. Works fine with `typescript 4.2.4`, but seems to break after upgrading to `typescript 4.3` and above

I did a simple query:
```
const setting = await Settings.findOne();
console.log(setting);
```

Typescript 4.2.4:
```
Setting {
    dataValues: {
      key: 'patientPassworExpiryInDays',
      value: 'null',
      createdAt: 2021-06-16T00:48:12.269Z,
      updatedAt: 2021-06-16T08:37:25.278Z
    },
    _previousDataValues: {
      key: 'patientPassworExpiryInDays',
      value: 'null',
      createdAt: 2021-06-16T00:48:12.269Z,
      updatedAt: 2021-06-16T08:37:25.278Z
    },
    _changed: Set(0) {},
    _options: {
      isNewRecord: false,
      _schema: null,
      _schemaDelimiter: '',
      raw: true,
      attributes: [Array]
    },
    isNewRecord: false
}
```

Typescript 4.3.5
```
  Setting {
    dataValues: {
      key: 'patientPassworExpiryInDays',
      value: 'null',
      createdAt: 2021-06-16T00:48:12.269Z,
      updatedAt: 2021-06-16T08:37:25.278Z
    },
    _previousDataValues: {
      key: 'patientPassworExpiryInDays',
      value: 'null',
      createdAt: 2021-06-16T00:48:12.269Z,
      updatedAt: 2021-06-16T08:37:25.278Z
    },
    _changed: Set(0) {},
    _options: {
      isNewRecord: false,
      _schema: null,
      _schemaDelimiter: '',
      raw: true,
      attributes: [Array]
    },
    isNewRecord: false,
    key: undefined,
    value: undefined,
    createdAt: undefined,
    updatedAt: undefined
}
```

I've checked against typescript release notes, but I don't see anything breaking in the release.

Any idea?

**Comment by nabilzhafri** [comment]
Okay, after trying a number of things, I managed to solve it by updating the `target` inside `tsconfig.json`  to `ES2020` and below. It used to be `ESNext`. Hopefully this helps someone.

Not too sure why `ESNext` was causing the issue though.

**Comment by Ortovoxx** [comment]
The (special methods/mixins)[https://sequelize.org/master/manual/assocs.html#special-methods-mixins-added-to-instances] are also undefined causing this error `TypeError: newUser.createProject is not a function`

But the suggestion from @nabilzhafri fixed it all. Seems strange as to why `ESNEXT` would break it

**Comment by jgudo** [comment]
Can confirm that changing the target property from ```ESNEXT``` to ```ES2020``` solved the problem as what @nabilzhafri  suggested.  Closing this issue..

**Comment by engineeringstuff** [comment]
This doesn't work - I've changed my `target`, `module` and `lib` to all point to `ES2020` instead of `ESNEXT` but it still doesn't hydrate the model.
The `dataValues` and the `_previousDataValues` properties are hydrated but the model is empty

**Comment by nabilzhafri** [comment]
@engineeringstuff I was using typescript 4.3. Try to revert to version 4.3 and below and see if that solves your problem?

However, I've tried typescript 4.4 with my project, and it seems to work fine. Here's my `tsconfig.json` for your reference:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2020",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/types/*"
      ]
    },
    "strict": false,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "strictBindCallApply": true,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false,
    "forceConsistentCasingInFileNames": true
  },
  "files": [
    "src/server.ts"
  ],
  "include": [
    "src/types/*.d.ts",
    "src/migrations/*.ts"
  ],
  "exclude": [
    "src/**/*.test.ts",
    "src/**/*.spec.ts"
  ]
}
```

**Comment by Chetan-Belwal** [comment]
I am also facing the same problem; it's giving the values as undefined but can be accessed using the dataValues,i tried changing migrations and models but still the response is same.

{
  dataValues: {
    name: 'scsc',
    password: '$2b$10$njSxvSyF9CpFfVCO1JsuDeuZ.JMc8v1DNZJyxWOzRXh8PTudIRuyG',
    email: 'test123@gmail.com',
    id: 1,
    profile_image: null,
    created_at: 2024-02-06T19:31:39.000Z,
    updated_at: 2024-02-06T19:31:39.000Z
  },
  _previousDataValues: {
    name: 'scsc',
    password: '$2b$10$njSxvSyF9CpFfVCO1JsuDeuZ.JMc8v1DNZJyxWOzRXh8PTudIRuyG',
    email: 'test123@gmail.com',
    id: 1,
    profile_image: null,
    created_at: 2024-02-06T19:31:39.000Z,
    updated_at: 2024-02-06T19:31:39.000Z
  },
  uniqno: 1,
  _changed: Set(0) {},
  _options: {
    isNewRecord: false,
    _schema: null,
    _schemaDelimiter: '',
    raw: true,
    attributes: [
      'name',
      'password',
      'email',
      'id',
      'profile_image',
      'created_at',
      'updated_at'
    ]
  },
  isNewRecord: false,
  name: undefined,
  password: undefined,
  email: undefined,
  profile_image: undefined,
  notes: undefined
}

**Comment by Chetan-Belwal** [comment]
I am also facing the same problem; it's giving the values as undefined but can be accessed using the dataValues,i tried changing migrations and models but still the response is same.

`{
  dataValues: {
    name: 'scsc',
    password: '$2b$10$njSxvSyF9CpFfVCO1JsuDeuZ.JMc8v1DNZJyxWOzRXh8PTudIRuyG',
    email: 'test123@gmail.com',
    id: 1,
    profile_image: null,
    created_at: 2024-02-06T19:31:39.000Z,
    updated_at: 2024-02-06T19:31:39.000Z
  },
  _previousDataValues: {
    name: 'scsc',
    password: '$2b$10$njSxvSyF9CpFfVCO1JsuDeuZ.JMc8v1DNZJyxWOzRXh8PTudIRuyG',
    email: 'test123@gmail.com',
    id: 1,
    profile_image: null,
    created_at: 2024-02-06T19:31:39.000Z,
    updated_at: 2024-02-06T19:31:39.000Z
  },
  uniqno: 1,
  _changed: Set(0) {},
  _options: {
    isNewRecord: false,
    _schema: null,
    _schemaDelimiter: '',
    raw: true,
    attributes: [
      'name',
      'password',
      'email',
      'id',
      'profile_image',
      'created_at',
      'updated_at'
    ]
  },
  isNewRecord: false,
  name: undefined,
  password: undefined,
  email: undefined,
  profile_image: undefined,
  notes: undefined
}`

**Comment by Chetan-Belwal** [comment]
```ef``
