### ISSUE TITLE
'Database connection was refused.' when connecting to AWS RDS MySQL instance

### ISSUE THREAD

**Issue by ExAmbitionAl** [sequelize/sequelize#13340]
RDS Instance is open publicly. I am able to login via my client app (Sqlectron) and I am able to create tables and everything. Once I enter my MySQL configuration in Sequelize config.json and try to run my server, my server starts but I get the error from the title. Googling didn't help much.

I used sequelize CLI (init command) to integrate sequelize.

config.json
----------------------------------------------
{
  "development": {
    "username": "user",
    "password": "rightPassword",
    "database": "dbName",
    "host": "**************.eu-west-1.rds.amazonaws.com",
    "port": 3306,
    "dialect": "mysql",
    "define":{
      "timestamps":false
    }
  },
 "test"...
  "production"...
}
------------------------------------------------
models/index.js
------------------------------------------------
'use strict';

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = require(__dirname + '/../config/config.json')[env];
const db = {};

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    const model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
----------------------------------------------

UPDATE: THIS IS HAPPENING ON ANY REMOTE DATABASES, NOT JUST ON RDS (STILL ABLE TO CONNECT TO REMOTE DB VIA CLIENT APP).

I need to deploy the backend app, but can't get past this. Any suggestions?

**Comment by carvalholeo** [comment]
Are you still getting this error? Maybe I'm with a similar problem that you.

**Comment by alex-polic** [comment]
@carvalholeo I think it was fixed by trying to connect to the database in the different part of my code. Sequelize is just something you can't trust completely. 

I would advise you to switch ORMs and use Prisma instead. Best of luck.

**Comment by ephys** [comment]
> Sequelize is just something you can't trust completely.

I honestly don't think that was caused by Sequelize. We simply pass your credentials over to the mysql2 library which handles connecting to your database. If moving the code somewhere else worked, you likely had an issue with the part of your code that selected the credentials, or you accidentally fixed them while refactoring 😅

I'd look into that @carvalholeo (console logging your credentials just before they're given to the Sequelize constructor to verify that they're correct). If that doesn't solve it, consider opening a [help discussion](https://github.com/sequelize/sequelize/discussions) with your error and other information that may be relevant
