### ISSUE TITLE
The project starts an error after updating the version

### ISSUE THREAD

**Issue by GracefulTing** [sequelize/sequelize#13349]
Last Friday, there was no problem using version 6.6.2. After installing the dependencies today, the project cannot be started, and the error is reported as follows：
--------
Class static side 'typeof import("d:/app-server-demo456/node_modules/sequelize-typescript/dist/model/model/model").Model' incorrectly extends base class static side 'typeof import("d:/app-server-demo456/node_modules/sequelize/types/lib/model").Model'.
  The types returned by 'init(...)' are incompatible between these types.
    Type 'Model<any, any>' is not assignable to type 'MS'.
      'MS' could be instantiated with an arbitrary type which could be unrelated to 'Model<any, any>'.

10 export declare abstract class Model<TModelAttributes extends {} = any, TCreationAttributes extends {} = TModelAttributes> extends OriginModel<TModelAttributes, TCreationAttributes> {

 Property 'model' in type 'Sequelize' is not assignable to the same property in base type 'Sequelize'.
  Type '<TCreationAttributes, TModelAttributes>(model: string | ModelType<TCreationAttributes, TModelAttributes>) => ModelCtor<Model<any, any>>' is not assignable to type '(modelName: string) => ModelCtor<Model<any, any>>'.
    Type 'import("d:/app-server-demo456/node_modules/sequelize-typescript/dist/model/model/model").ModelCtor<import("d:/app-server-demo456/node_modules/sequelize-typescript/dist/model/model/model").Model<any, any>>' is not assignable to type 'import("d:/app-server-demo456/node_modules/sequelize/types/lib/model").ModelCtor<import("d:/app-server-demo456/node_modules/sequelize/types/lib/model").Model<any, any>>'.
      Type 'ModelCtor<Model<any, any>>' is not assignable to type 'typeof Model'.
        The types returned by 'init(...)' are incompatible between these types.
          Type 'Model<any, any>' is not assignable to type 'MS'.
            'MS' could be instantiated with an arbitrary type which could be unrelated to 'Model<any, any>'.

12     model<TCreationAttributes, TModelAttributes>(model: string | ModelType<TCreationAttributes, TModelAttributes>): ModelCtor;

**Comment by fellainthewagon** [comment]
Have the same problem, i tried to downgrade sequelize to any version (6.0.0, 6.2.0, 6.6.2...), but it didn't help me(

**Comment by mlavina** [comment]
@GracefulTing any reason why this was closed? I am running into a similar issue

**Comment by BerniWittmann** [comment]
I had the same problem, but it seems to be related to sequelize-typescript and not sequelize itself. Upgrading sequelize typescript to 2.1.1 helped me (https://github.com/RobinBuschmann/sequelize-typescript/issues/1036)
