### ISSUE TITLE
How to use sequelize query view in mysql database

### ISSUE THREAD

**Issue by devsabai** [sequelize/sequelize#13359]
## Issue Creation Checklist

I have some problem about query data from view in mysql database

## Issue Description

I have create View in my databases, 
```
CREATE VIEW [Brazil Customers] AS
SELECT CustomerName, ContactName
FROM Customers
WHERE Country = 'Brazil';

```
Please recommend how to use sequelize query this view

**Comment by Keimeno** [comment]
Sequelize doesn't currently support views. As a workaround, you could:
1. Create a model, and specify fields and as table name the view name and don't synchronize the model.
2. Create a raw query
3. Or with sequelize you don't need views, you can easily create a function, that stores a select query, similar to what views do.
