### ISSUE TITLE
ERROR: connect ECONNREFUSED 127.0.0.1:3306 

### ISSUE THREAD

**Issue by wandriputra** [sequelize/sequelize#13364]
I get this error when try migration to Macbook M1 Processor and working well in old Macbook

```
Sequelize CLI [Node: 15.3.0, CLI: 6.2.0, ORM: 6.6.4]

Loaded configuration file "api/v1/config/connection.js".
Using environment "development".

ERROR: connect ECONNREFUSED 127.0.0.1:3306
```

I'm using Mamp for MySql Server

**Comment by mnemosdev** [comment]
Could you please attach your terminal output regarding the ports configuration? It appears that you might be missing the users or databases in this new MySQL installation, hence the ECONNREFUSED.

Thanks.
