### ISSUE TITLE
Chore: migrate away from moment.js

### ISSUE THREAD

**Issue by soryy708** [sequelize/sequelize#13372]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

Moment.JS is in maintenance mode, + it's a pretty old package which doesn't play well with modern build pipelines.
I propose we migrate away from MomentJS to something else, like [date-fns](https://date-fns.org/) or something else.

### Additional context

[Moment.JS docs](https://momentjs.com/docs/) say the following:

> We now generally consider Moment to be a legacy project in maintenance mode
> In most cases, you should not choose Moment for new projects
> There are several great options to consider using instead of Moment.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imwh0im** [comment]
i agree this issue. migrate from momentjs to dayjs

**Comment by soryy708** [comment]
> 
> 
> i agree this issue. migrate from momentjs to dayjs

Cool. Why dayjs specifically?

Moment recommends the following options:

* Luxon - 1.3m weekly dls on npm
* Day.js - 4.6m weekly dls on npm
* date-fns - 8.1m weekly dls on npm
* js-Joda - 0.2m weekly dls on npm

**Comment by imwh0im** [comment]
dayjs was almost the same as momentjs in usage.
I recommend to look at the this.
https://day.js.org/

> 2kb: low resource
> simple: If you use Moment.js, you already know how to use Day.js.
> immutable: this is helps prevent bugs and avoid long debugging sessions.
> I18n: Day.js has great support for internationalization

it's not a coercion. just a suggestion. :)

**Comment by soryy708** [comment]
https://date-fns.org/

> **modular**: works well with bundlers and supports tree shaking, which helps it be very light
> **immutable & pure**: helps to prevent bugs and avoid long debugging sessions
> **I18n**: date-fns has dozens of locales. Only the ones that you use will be included in your project
> **Simple**: always have one function that does one thing.
The API is unambiguous, and there is always a single approach to a problem.
> **reliable**: date-fns respects timezones & DST.
It follows semantic versioning so, always backward compatible.
Each build CI checks more than 650 000 examples in about 400 time zones.
> **fast**

**Comment by imwh0im** [comment]
The 'dayjs' and 'date-fns' has differences seem to be in usage.
I'd like to contribute to this work once it's decided.

**Comment by soryy708** [comment]
@sdepold The bot said 7 days but closed it after 5. Not fair! 😂
I'm interested in reopening this issue and contributing. Need a maintainer to decide which dates library we'd like to migrate to (if at all)

**Comment by sdepold** [comment]
The bot... Little liar :) I'll get back to you later today!

**Comment by soryy708** [comment]
@sdepold Hi! Looks like we haven't made contact.
As said previously, we need a maintainer to decide which dates library we'd like to migrate to (if at all).

**Comment by soryy708** [comment]
@sdepold Please make a decision. Which dates library do we want to migrate to (if at all)?

**Comment by WikiRik** [comment]
Personally I would go with date-fns. It manipulates the normale Date object. It is a bigger refactor than moving to Day.js but it has my personal preference

**Comment by WikiRik** [comment]
Apparently this is also mentioned in the meetings backlog, not sure why GitHub did not show that; https://github.com/sequelize/meetings/projects/1#card-73600663

**Comment by sdepold** [comment]
Any particular reasons against day.js? I don't have any strong opinion really, however I library that is 2kb and similar to the currently used lib seems relatively good to me

**Comment by WikiRik** [comment]
> Any particular reasons against day.js? I don't have any strong opinion really, however I library that is 2kb and similar to the currently used lib seems relatively good to me

Nothing in particular, date-fns just seems more interesting to me. But I'm fine with either.

**Comment by bach942** [comment]
I know this discussion hasn't been commented on in a while, but I would advocate for day.js. Date-fns is great, but it can't handle timezones like moment and moment-timezone does. I just tried to convert all my moment objects over to Date objects and using date-fns to handle the manipulation part and it became a nightmare (Once your string is converted to a Date object it now has the server timezone which creates all kinds of problems when trying to format, parse, and manipulate). Day.js has it built into the package just like moment did and seems like would work better to help migrate away from moment.

**Comment by bach942** [comment]
Also if you want I could see how it goes and make a PR with the migration to day.js?

**Comment by ephys** [comment]
What about sticking with moment until native Temporal is shipped? Sounds like a lot of work for something that's going to be migrated again soon after.

**Comment by bach942** [comment]
@ephys I can get on board with the Temporal Proposal, but I didn't know what kind of time frame it was going to be on. My goals was to just help migrate from moment, which has been deprecated for a while to something more supported and stable.

**Comment by ephys** [comment]
I agree, we can't know how long it's going to be. And I'm not pro using the polyfill before Temporal gets unflagged in at least some engines (just in case). I suppose Dayjs (or alternative lib) it is

**Comment by WikiRik** [comment]
> I know this discussion hasn't been commented on in a while, but I would advocate for day.js. Date-fns is great, but it can't handle timezones like moment and moment-timezone does. I just tried to convert all my moment objects over to Date objects and using date-fns to handle the manipulation part and it became a nightmare (Once your string is converted to a Date object it now has the server timezone which creates all kinds of problems when trying to format, parse, and manipulate). Day.js has it built into the package just like moment did and seems like would work better to help migrate away from moment.

Hearing this I think day.js would be better then. Looking forward to see a PR with the migration. Temporal would be nice but I don't think we can really use it until the end of 2022 (or later)

**Comment by sdepold** [comment]
👌 @ dayjs

**Comment by lachieh** [comment]
`day.js` is a good direct replacement for `moment.js` because it has the same api signatures, and if minimizing changes is the goal, then that is the right decision. I see a couple of comments comparing the library size, and just want to add some more information around that before a decision is finalized.

`day.js` gets imported as a whole package, whereas `date-fns` is a collection of individual functions imported as needed. With `date-fns`, if only 1 function is needed, then that is the only part of the package that is included in the bundle. All of `day.js` gets included, regardless of how many methods are in use.

For a backend library, performance should really be the focus over size (particularly for a saving of 2kb). I'm not really sure which library performs better, but it'd probably be a good idea to see what features sequelize actually needs from a date library.

I can try and assist with this if that is what's needed.

**Comment by WikiRik** [comment]
You raise a good point. I think that we can also do it in two steps. First minimize the changes and move to day.js so we are using a maintained library. And afterwards refactor to a smaller library if we notice that we do not use as many features

**Comment by sdepold** [comment]
Discussed in our Monthly Sequelize sync:

Let's do the drop-in replacement with day.js. Given it's only 2kb in size, we will stay with it till the Temporal API is available.

**Comment by bach942** [comment]
@sdepold yeah I can fill the PR.. When I do make the PR should I tag you @sdepold?

**Comment by sdepold** [comment]
Nice one :) Yes please ping me or add a link to the PR here :)

**Comment by ephys** [comment]
It's not perfect but since Moment is not going to change anymore it may be fine. We could detect something is a moment object by doing this:

`theObject.constructor.name === 'Moment' && theObject._isAMomentObject`

And, if a specific method needs to be called on it, check whether it exists first:

`theObject.constructor.name === 'Moment' && theObject._isAMomentObject && 'format' in theObject`

But that's only if it's not too much work, otherwise we can just drop moment support. It's possible some of the places that use `moment.isMoment` may be dropped

One of the places where it would be easy enough to preserve moment support would be here:
https://github.com/sequelize/sequelize/blob/main/src/data-types.js#L526

**Comment by soryy708** [comment]
`theObject.constructor.name === 'Moment'` may introduce a breaking change.
Some users use a bundler (like Webpack) on the back end to make the bundle size small, to save costs on bandwidth and storage. Another use case would be to use something like babel for access to modern ECMAScript features, while still targetting odler NodeJS releases.
The problem is that webpack/babel may mangle the names (like as part of uglification), and the fix would require the user to change their babel/webpack configuration to migrate.

**Comment by ephys** [comment]
That's true. and checking `_isAMomentObject` alone is not enough imo.
Then we may as well drop moment support altogether. I have plan on implementing something that lets users serialize/deserialize a datatype to their JS type of preference which could bring back this kind of support in a different way (https://gist.github.com/ephys/50a6a05be7322c64645be716fea6186a#support-for-alternative-js-types).

**Comment by soryy708** [comment]
Why was Sequelize coupled to Moment in the first place? What is the functionality we're talking about dropping support of?

**Comment by ephys** [comment]
Probably because it used to be the most popular way of handling dates in JS when this was introduced.

The functionality in question is the ability to assign a moment object to an attribute, having it be serialized and saved to the database just like if it were a Date object. (you could also use them in `where` I believe)

**Comment by bach942** [comment]
I think it would be good to decouple Sequelize from Moment (has to be a date object or string to save), but also I didn't want to break functionality or change the roadmap if this was something that the team wanted to keep.

**Comment by ephys** [comment]
This will be included starting with v7, so it's fine to drop moment support :)

**Comment by sdepold** [comment]
Agreed. Let's drop it!

**Comment by sdepold** [comment]
Seems that we have lost some traction here. What are we even using moment.js for? Should we just keep it as is until the Temporal API is implemented natively? 

Would Temporal actually be added to older versions of Node or only in the super latest version of Node?
It's still unclear right now but in the past new features have been added to LTS as well. Even if not we could use polyfills.

The core team is NOT going to work on this anymore but rather remove the external dependency altogether once Temporal lands in Node.

**Comment by bach942** [comment]
So I was actually wondering if putting day.js for moment.js is the right path. There is some logic to apply a timezone using moment-timezone, but wondering why Sequelize does that at all. It might be better to just use Date or String classes to save data to various databases (Either using ISO or standard date formats). I started the process of conversion, but wondered why Sequelize is doing some of this logic.

**Comment by bach942** [comment]
Quick search link for some of the moment objects: [https://github.com/sequelize/sequelize/search?p=1&q=moment](https://github.com/sequelize/sequelize/search?p=1&q=moment)

**Comment by ephys** [comment]
`Date` is really hard to use correctly. It has terrible timeZone support, it converts its input to either UTC or local timeZone based on the syntax of the string. It's too dangerous to use in a library like Sequelize.

> There is some logic to apply a timezone using moment-timezone, but wondering why Sequelize does that at all

It's related to the [`timezone`](https://github.com/sequelize/sequelize/blob/main/src/sequelize.d.ts#L277) Sequelize option which does two things:

- It sets the TimeZone to use in the DBMS (`SET time_zone = ...`). This part is fine.
- In `DataTypes.DATE`, it updates the TimeZone of the object being sent to / retrieved from the DBMS. This is something that I feel should be removed. It feels like a legacy solution to workaround the terrible `Date` object. It's not very useful now that we have [`Temporal.ZonedDateTime`](https://tc39.es/proposal-temporal/docs/#Temporal-ZonedDateTime)

However, this second behavior has been part of the code base for a very long time and removing it will annoy a lot of people.

I was already planning on deprecating `DataTypes.DATE` for other reasons. This is an extra one. Here is what I think we should do:

- Wait until Temporal lands in at least one LTS Node version
- Deprecate `DataTypes.DATE`
- Add `DataTypes.DATETIME` & `DataTypes.DATETIME.ZONED`
- `DataTypes.DATETIME.ZONED` accepts & returns *only* [`Temporal.ZonedDateTime`](https://tc39.es/proposal-temporal/docs/#Temporal-ZonedDateTime). It ignores the Sequelize `timezone` option.
- `DataTypes.DATETIME` accepts & returns *only* [`Temporal.PlainDateTime`](https://tc39.es/proposal-temporal/docs/#Temporal-PlainDateTime)
- require installing a Temporal polyfill or a node version that supports temporal to use the new `DataTypes.DATETIME`

**Comment by soryy708** [comment]
Another option would be to

1. Decouple Sequelize's mechanisms from moment, by using a delegator design pattern
2. Write a lot of tests for the delegator, to codify the expected behavior from moment
3. Replace the delegator's implementation (that uses moment) with a different one (that uses something like dayjs/date-fns)

This will do a few things:

1. It won't cause a breaking API change, therefore not annoying Sequelize's users (1.3m weekly downloads, a lot of users)
2. It will let us safely migrate away from moment, saving bundle size
3. If we chose to deprecate `DataTypes.DATE` and later drop support, the timezone code will be in one place, allowing easy ripping-out

**Comment by ephys** [comment]
As I said, we'll accept a PR to migrate to migrate to dayjs, and you're free to make one, but the final implementation will use Temporal once it's available for the simple reason that it's the built-in library

**Comment by fzn0x** [comment]
> As I said, we'll accept a PR to migrate to migrate to dayjs, and you're free to make one, but the final implementation will use Temporal once it's available for the simple reason that it's the built-in library

Wise choice to choose both long run and sustainability!

**Comment by DraftProducts** [comment]
I agree that this change would be nice.
Can I take care of the PR if no one has been assigned to it yet?

**Comment by ephys** [comment]
Sure :)
