### ISSUE TITLE
FindOrCreateOptions does not extend CreateOptions

### ISSUE THREAD

**Issue by devagrawal09** [sequelize/sequelize#13388]
## Issue Creation Checklist

- [X]  I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/172 

### What do you expect to happen?

The `findOrCreate` method should accept `hooks: boolean` as an option.

### What is actually happening?

While the `hooks` option does affect the functionality (`hooks: false` prevents the hooks from being called), the typescript interface `FindOrCreateOptions` does not include the `hooks: boolean` property, neither does it extend an interface that does.

### Additional context

I believe the `FindOrCreateOptions` interface should extend the `CreateOptions` interface just how it's extending the `FindOptions` interface.

### Environment

- Sequelize version: 6.5.0 
- Node.js version: 14.16.1 
- If TypeScript related: TypeScript version: 4.1.3 

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by devagrawal09** [comment]
Similar issue - https://github.com/sequelize/sequelize/issues/12954

**Comment by FreTimmerman** [comment]
neither does it extend `FindOptions`, fyi
