### ISSUE TITLE
Not Null field generated can't pass validations

### ISSUE THREAD

**Issue by SimonChaumet** [sequelize/sequelize#13383]
## Issue Creation Checklist

[X ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Is your feature request related to a problem? Please describe.

When creating an instance I need to generate a uid, but when I describe the field with `allowNull: false` while creating the uid with a hook I can't skip sequelize validations.

### Describe the solution you'd like

Allow an override of this feature only for SQL/Sequelize validations purposes.

```js
sequelize.define('foo', {
  bar: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
        allowNull: true,
    }
  }
});
```

### Why should this be in Sequelize

Because it's part of sequelize package and I can't do it without.

### Describe alternatives/workarounds you've considered

Set `allowNull` to true and remove sql validation.

### Is this feature dialect-specific?

- [X] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by SimonChaumet** [comment]
up

**Comment by KreativJos** [comment]
This is an issue for me as well, in the case of mssql rowversion.
