### ISSUE TITLE
Typescript issue, model.create property id does not exist on type

### ISSUE THREAD

**Issue by kwiksilver3441** [sequelize/sequelize#13384]
```js
// You can delete this code block if you have included a link to your SSCCE above!
export default async (sequelize: Sequelize) => {
  const { TranslationCode, User, Role, Employee, Document, Resource, Translation, Service } = sequelize.models

  const code = await TranslationCode.create({ code: 'en' })
  const translation = await Translation.bulkCreate([
    { text: 'titleTextTest', TranslationCodeId: code.id },
    { text: 'descriptionTextTest', TranslationCodeId: code.id }
  ])
  console.log(code.id)
}

```

### What do you expect to happen?
This is more of "getting help" than a bug report. So sorry about that. Doesn't seem to be a place to get help or a discord server where I could ask.

Everything works fine, but when I attempt to reference code.id, even though it exists, it does not exist on the type. I'm somewhat new to TS, so I think it might be just getting the wrong model. I always though this was something with Sequelize because I would try to console out "code.id" to see what the output was. Surprisingly it worked and gave me the ID, but it turns out TS was just having issues. 

Is there any way to specifically tell TS that it's using the TranslationCode model, and not Sequelizes type "Model"

### What is actually happening?
Everything is actually working correctly, just typescript getting the wrong model.

### Environment

- Sequelize version: 6.6.5 
- Node.js version: 16 latest
- If TypeScript related: TypeScript version: 4.2.4

**Comment by Keimeno** [comment]
In Typescript, a sequelize model instance doesn't automatically extend by the models fields. 

To get type safety, you need to write `code.get().id` instead.
