### ISSUE TITLE
How retry mechanism works?

### ISSUE THREAD

**Issue by acidos** [sequelize/sequelize#13380]
I don't understand how transaction retry works in `sequelize`.
I am using managed transaction, though I also tried with unmanaged with same outcome

    await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.REPEATABLE_READ}, async (t) => {

        user = await User.findOne({
            where: { id: authenticatedUser.id },
            transaction: t,
            lock: t.LOCK.UPDATE,
        });    

        user.activationCodeCreatedAt = new Date();
        user.activationCode = activationCode;
        await user.save({transaction: t});
    });

Now if I run this when the row is already locked, I am getting
 
    DatabaseError [SequelizeDatabaseError]: could not serialize access due to concurrent update 

which is normal. This is my retry configuration:

    retry: {
        match: [
            /concurrent update/,
        ],
        max: 5
    }

I want at this point `sequelize` to retry this transaction. But instead I see that right after `SELECT... FOR UPDATE` it's calling again `SELECT... FOR UPDATE`. This is causing another error

    DatabaseError [SequelizeDatabaseError]: current transaction is aborted, commands ignored until end of transaction block

How to use `sequelize`s internal retry mechanism to retry the whole transaction?

I am not sure if this issue is dialect specific as I only work with postgres.
Using `sequelize` version 6.6.5.

**Comment by clarencedesmarais** [comment]
This is still a good question. Can we reopen it ?
