### ISSUE TITLE
Declaring Index Keys in a Model's Definition

### ISSUE THREAD

**Issue by schonfeld** [sequelize/sequelize#1339]
We should have the ability to declare/define index keys within a model's definition, on a single-field basis. We already have this for "unique" keys. For example:

```
return sequelize.define("User", {
  type: {
    type: DataTypes.ENUM('individual', 'company', 'unknown')
    , key: true
  }
});
```

Which would effectively generate this CREATE statement:

```
CREATE TABLE `Users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` enum('individual', 'company', 'unknown') DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

I'd be happy to get a PR going for this. Thoughts?

**Comment by dianaflorez** [comment]
I did this and working for me... for postgres 
(I declared id_pais and codigo_pais how primaryKey: true) 

"use strict";

module.exports = function(sequelize, DataTypes) {
  
    var Pais = sequelize.define('pais', {
        id_pais:{
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        codigo_pais: {
            type: DataTypes.STRING(3),
            primaryKey: true
        },
        nombre: {
            type: DataTypes.STRING(50),
            allowNull : false
        },
       "createdAt":{
			type: DataTypes.DATE,
			defaultValue : sequelize.fn('now') 
		},
		"updatedAt":{
			type: DataTypes.DATE,
			defaultValue : sequelize.fn('now') 
		}
    });
  return Pais;
};

//**********************************************
The result in postgres was

-- Table: pais

-- DROP TABLE pais;

CREATE TABLE pais
(
  id_pais serial NOT NULL,
  codigo_pais character varying(3) NOT NULL,
  nombre character varying(50) NOT NULL,
  "createdAt" timestamp with time zone DEFAULT now(),
  "updatedAt" timestamp with time zone DEFAULT now(),
  CONSTRAINT pais_pkey PRIMARY KEY (id_pais, codigo_pais)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE pais
  OWNER TO diana;
