### ISSUE TITLE
Include/Exclude for nested models (for scopes for example) 

### ISSUE THREAD

**Issue by LeoLfL** [sequelize/sequelize#13404]
I have a question: How I can exclude some attributes from nested models? I know that i can just add : 
```  include: [
    {
      association: ModelName.associations.user,
       attributes: {
         exclude: ['id']
       }
    }
```
**but in some cases, it's not possible to use this syntax**. 
for example, if i use` default scope`, 
in some specific cases, i want to hide some attributes from the nested included table. 
for where clause I can use syntax `'$user.id$` . 
do we have something similar for attributes? if no, then it would be nice to have it.

of course i can just create scope and pass some args to the scope and then add this exclude/include list, but it looks not so nice

**Comment by dimd13** [comment]
+1
