### ISSUE TITLE
Using proxy with sequelize - exceeding max connection defined on the pool.

### ISSUE THREAD

**Issue by ShaharMynd** [sequelize/sequelize#13425]
## Issue Creation Checklist

[V] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

We started using AWS RDS PROXY recently,
We noticed that when we are using AWS RDS PROXY it keeps opening new connections that surpass the max connections defined on the pool.

However, **Without using AWS RDS PROXY, The pool works great.**

So my question is, how should I configure sequelize to use AWS RDS PROXY in the right way?

We tested some stuff:

- working with 1 max connection in the pool: 
Then we compared the usual way with a pool of 10 connections (WITHOUT PROXY) vs the AWS RDS PROXY with 1 connection pool.

    - We saw that the proxy with 1 connection is slower   
    - **It didn't open more connections (no bug)**

### What do you expect to happen?

Sequelize pool to not open more connections than defined on the pool.

### What is actually happening?

The connections continue to grow as time increase, we got over 40 connections (we defined a maximum of 10 connections)

### Additional context

Add any other context and details here.

### Environment

- Sequelize version: 6.6.5
- Node.js version: 10.15.3

### How does this problem relate to dialects?

- [V] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [V] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by iamakimmer** [comment]
@eyalroth is there any consideration on setting the connection pool idle property in sequelize with this flag? We have a similar issue and want to reduce wait_timeout, but if there are idle connections in the connection pool, would it inadvertently close those as well?
