### ISSUE TITLE
Soundex

### ISSUE THREAD

**Issue by mehrdadmms** [sequelize/sequelize#13428]
## Issue Creation Checklist

[X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description

Support for Soundex, fuzzy string match and difference function in PSQL

### Is your feature request related to a problem? Please describe.

I'd like to search in my table and get closest match for example if I searched "studt" instead of "student" I get the nearest match

### Describe the solution you'd like

If we have soundex and difference function in Sequelize.Op it'll be great 

### Why should this be in Sequelize

Because soundex is very useful in searching patterns and working with string.

### Describe alternatives/workarounds you've considered

The work around is using raw SQL but in this situation you can't use ORM features alongside your soundex query.

### Additional context

PSQL documentation on Soundex.
https://www.postgresql.org/docs/9.1/fuzzystrmatch.html

### Is this feature dialect-specific?

- [X] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Unfortunately, `Op` is for operators, not functions. You can already use functions using `fn()`, or `literal()`.

I agree that using `literal` means you have to opt out of some of the features of the ORM, but [we're fixing that](https://github.com/sequelize/sequelize/issues/14299)

With the above RFC, you will soon be able to do this:

```typescript
const name = 'john';

Users.findAll({
  where: sql`soundex(${attr('firstName')}) = soundex(${name})`
})
```

**Comment by ephys** [comment]
The above proposal syntax is now available in v7
