### ISSUE TITLE
Documentation mismatch? No type property on ForeignKeyOptions

### ISSUE THREAD

**Issue by xaragen** [sequelize/sequelize#13429]
Working on a project I ran into the documentation for customizing the Foreign Key.
The docs read:

```javascript
// https://sequelize.org/master/manual/assocs.html
// For example, to use UUID as the foreign key data type instead of the default (INTEGER), you can simply do:

const { DataTypes } = require("Sequelize");

Foo.hasOne(Bar, {
  foreignKey: {
    // name: 'myFooId'
    type: DataTypes.UUID
  }
});
Bar.belongsTo(Foo);
```

Good enough, but when I went to work on it, it threw an error :
```
 Object literal may only specify known properties, and 'type' does not exist in type 'ForeignKeyOptions'
```
Looking at the files, it seems true. Is this correct behavior, missing type or incorrect documentation?

https://github.com/sequelize/sequelize/blob/56bb1d6ef9827f604d7bcef945abb7e213f2322d/types/lib/associations/base.d.ts#L37

**EDIT**:

After working on this, looks like it does work but the option is not part of the ForeignKey Options as described in the docs.
```js
Foo.belongsTo(Bar, {
    foreignKey: {
        name: 'myFooId',
    },
    as: 'bars',
    keyType: sequelize.DataTypes.STRING,
});
```

**Comment by ephys** [comment]
This would be a good point to start an investigation: https://github.com/sequelize/sequelize/blob/main/src/associations/base.d.ts#L37
`ForeignKeyOptions` extends `ColumnOptions`, which doesn't include `type`
The only option bag that accepts `type` is `ModelAttributeColumnOptions`

The question is:
- can type be moved from `ModelAttributeColumnOptions` to `ColumnOptions` (what other methods use `ColumnOptions` and do they accept `type`)
- can foreign key extend `ModelAttributeColumnOptions`? Does it support all of these options
- or do we need to create an intermediary type

**Comment by bera5186** [comment]
Hey @ephys ,

`ModelAttributeColumnOptions` extends `ColumnOptions` , so all the properties of `ColumnOptions` should be accessible via extending `ModelAttributeColumnOptions`.

Looks like extending `ModelAttributeColumnOptions` in `ForeignKeyOptions` would work, but I think creating intermediary type is a better option.

Correct me if I am wrong. Waiting for your inputs on this !

**Comment by ephys** [comment]
https://github.com/sequelize/sequelize/issues/13429 fixes this issue
