### ISSUE TITLE
Sequelize Error: no such column with no primary key and underscores

### ISSUE THREAD

**Issue by davidgeorgeuk** [sequelize/sequelize#13421]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When a model with no primary key and underscored column names is retrieved using findAll and where option, and then updated, and error occurs. When a model is saved, the generated sql for the update tries to use the camelCase attribute names instead of the underscored column names.

### SSCCE

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/179

### What do you expect to happen?

The db record should be updated using the correct underscored column names.

### What is actually happening?

The generated sql uses the camelCase attribute names in the where clause, and an error occurs

```

DatabaseError [SequelizeDatabaseError]: SQLITE_ERROR: no such column: userId

```

### Additional context

This issue was introduced in sequelize@6.6.4 in https://github.com/sequelize/sequelize/commit/1a16b915ff45ac621a0517aea6c2d86557149500 . You can see further discussion of that fix and this issue in https://github.com/sequelize/sequelize/issues/12868

### Environment

- Sequelize version: 6.6.5
- Node.js version: v14.16.1
- If TypeScript related: TypeScript version: N/A

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by gurpreetatwal** [comment]
Fix still in progress, not stale

**Comment by ephys** [comment]
I'll close this PR as we do not plan on supporting these instance methods on models that do not include a PK, due to how unsafe it would be, per https://github.com/sequelize/sequelize/issues/14402
