### ISSUE TITLE
Set the default allowNull: false globally

### ISSUE THREAD

**Issue by zq0904** [sequelize/sequelize#13439]
First of all I want to thank you for this great project!

original intention
1. I don't want allowNull: false on every field, it's really troublesome
2. I personally think rigor is great. It is possible to determine the type of the query instead of null or some other type
Referred to [this](https://github.com/sequelize/sequelize/issues/504) but this issue has been closed

Hope to support:
```tsx
new Sequelize("db", "user", "pass", {
    define: {
        allowNull: false
    }
})
```

**Comment by r0ulito** [comment]
I'm facing the same problem today. It's really disturbing that you have to set `allowNull` to false for every fields whereas I'm used to set only a few fileds to nullable. DRY principle is not applicable there

**Comment by ephys** [comment]
Regrouped under https://github.com/sequelize/sequelize/issues/14260
