### ISSUE TITLE
Typescript: Cannot assign type Model<A, B> to ModelCtor<any>

### ISSUE THREAD

**Issue by e-e-e** [sequelize/sequelize#13436]
## Issue Creation Checklist

[X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

This is a typescript typing issue.

A class extending a typed model (eg: `Model<Foo, Bar>`) cannot be assigned to the type `ModelCtor<any>`. 

### SSCCE

```ts
type Foo = {
  id: string,
};
class FooModel extends Model<Foo> {}

// This throws a type error
const model: ModelCtor<any> = FooModel;
```

I will open a PR shortly with a test which shows the behaviour, and a fix that addresses it.

### What do you expect to happen?

I expect any class expending `Model` to be assignable to `ModelCtor<any>`;

### What is actually happening?

We are getting the following TS error: 

```
TS2345: Argument of type 'typeof FooModel' is not assignable to parameter of type 'ModelCtor<any>'.   Type 'typeof FooModel' is not assignable to type 'typeof Model'. (... much more output)
```

### Additional context

I diagnosed the issue and here is a TS playground demonstrating the general issue and a solution: [Playground](https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBAysCGwCWBjAPAFQHxQLxQG8oA7CAdwAoBKALigygF8BuAWAChRIoAlCAWwD2ANwgBJYgGcExFBAAKAJ0GRFyCJMxQIAD2ARiAE0mFGeKPGIgc+IgG0A0lCTEoAawghBAM3oBdOgxHPyYODgB6cPoACyQTOIsoRXhDVHgAG3SQKEkkfjB0pG8kCENtHXh89OgfKGjBMlgIAEcAVwhCgC9oAFlBQw6oLg1nYBNvVtlkQSkAGigIqK4XAHMoCamkGYtFFdb+AzGoACNs4GjoYahayygwRSRhRGh7lQg1EAA6DhR0+EkTAAhf4QLS6fRGEwEMy2Rg4AgcKBIqAAfWEgXMxFamQAhGF2Mi7q1joUUDkEMgyRt0D1yhDjFBgZIIFgKIjCcjznE6HBEKg0D0sPN2RyoOioD07AByNFSvwiqC0MWCJBlaFsdiMRZQACCFiMjJ20F0lQKI1q4IMqWIay5QJBUF+-xMhQ8UDIxr0Vol-Q6Pz+AN1dKt9uZaCI8Do0geNqY8K17CdgcBwchjJB4ZOdCx-GO7zjpnxkSDljKKeOgnOdXgonJyhtWSG4FK60mKA4gM+1IoRGOdAAjEwqBrO92I3QpfApUOoMXdJAUPoyt54Eh0q1FBAODqu22exYJ1Oh9vd7J932oIPGMPZ1F5xBFy2V2uN1v2NqmdAULc8xYwAUSjKYBBCbSBak-H4ZmkE4QQAYWAxQ6GGcCHXwCD2GLQFWmAEgICQc58z1QRFENb9XF-eB-0KFtgNAiAUOZE4H3gVpGLRZwTFSbxvHeQ5IKkHD4Hg4ikObBjoHwHVmFvcoFyXdZV3XTd+Og45hMQujxPMQFpLnHQ5KfRTXyLKIMFieITFuE0qhqXwCMdDdN2IHDjmUDxXGZNoOiQbo6I4K5ATcgx1LBL000-GxNN8T8oAAMkIXDKCVBgWA4aoXKC4h1LoQLBHckKdUiqSZLMhJJHqbEyjIYi3DSiAMry4KEM-HLMpCiLtJBDVtVKiz9XKU1qmuXx6kaD1HVuYodCGC5HSg4BFFaRdiNA1Z-ObKAQoYS1wpBSK+CEUQJGkSw5CUN41BKTRkOiva4oS0gkoxVL3wwqIdQBJAVmIVYhhA+ATmUFJ83U90asskx70fQxvnYdLAcEYHFGyzaELQDrJI1VzEYGZGEO0jVi2if4LBQORA1ok7KTFDJ2m1Y5sJmy4NoSYgQPSGYVnzTdo1QJd5hJ7GkdBhJjhBMotLIC5N1RYQOP1L4OCF3H1NPFAKEnKwuRtKVhxMqAAHUv1uDJJBAgZilIKAhBlyQFyKVBUZW4ZLINLmcJQYjN0XVabTqnC7YfB2UBRgqio1QOUGD1WxwPKApUkadrw4SPo4QtXzwnROhyAA)

### Environment

- Sequelize version: latest
- Node.js version: v12.22.1
- If TypeScript related: typescript@4.3.5

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.

**Comment by e-e-e** [comment]
This is still an issue and should not be closed.

**Comment by ephys** [comment]
@e-e-e can you check if this is still an issue after PR https://github.com/sequelize/sequelize/pull/13890?
It should have fixed it.

**Comment by s1nistr4** [comment]
Please reopen, ModelCtor is marked as deprecated but you literally have to use it to define a model with explicit static typing. This is a massive engineering issue and really all that needs to be done to fix it is not mark it as deprecated
