### ISSUE TITLE
Use sequelize with better-sqlite3? *cannot* use sqlite3 due to using node16.

### ISSUE THREAD

**Issue by xXnikosXx** [sequelize/sequelize#13446]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

I'm trying to use better-sqlite3 for my project that used to use sqlite3. Issue is, I had to upgrade to node v16.x in order for some packages to work on their latest version, and sqlite3 isnt working on any node version higher than 14. is there any way for me to use better-sqlite3 with sequelize? I already have both nstalled but sequelize keeps looking for sqlite3. 

### Additional context

Again, i can't change my node version to nay lower than 16, for my project to work.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
So there is an issue with publishing new builds for sqlite3, as per https://github.com/mapbox/node-sqlite3/issues/1508
There is [this issue](https://github.com/sequelize/sequelize/issues/11400) for moving to better-sqlite3. I will discuss with the team if it fits in the next major release.
