### ISSUE TITLE
Minor snippet issue in "Getters, Setters & Virtuals" section of docs

### ISSUE THREAD

**Issue by shakexu1** [sequelize/sequelize#13445]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

In "Getters" section ,the type of parameter which pass to function getDataValue should be "String",or it would report ReferenceError when copying example-code to run.
 
![QQ20210814153226](https://user-images.githubusercontent.com/58530871/129438837-8cc017fd-2c68-412d-a85d-2c956cc35c3e.png)

### If possible: Provide some suggestion on how we can enhance the docs
After adding double quote to _username_ , ReferenceError disappears .

![20210814153205](https://user-images.githubusercontent.com/58530871/129438846-0a52eccc-d038-4114-a10a-aa5fc8299a13.png)

### Additional context

Add any other context or screenshots about the issue here.

**Comment by aryem** [comment]
Duplicate #13062 #12811 #12655
[PR](https://github.com/sequelize/sequelize/pull/13074) that closes this issue.
