### ISSUE TITLE
Running migrations in lambda or other approaches (seeking guidance)

### ISSUE THREAD

**Issue by fostahgix** [sequelize/sequelize#13460]
## Issue Description

I am looking for guidance on the best way to run the Sequelize migrations for an AWS RDS MySQL/Aurora database that does not have public access. 

The main challenge I have in our CI/CD is that we are deploying everything via serverless framework (which deploys all of the lambda functions and resources), however when running our shell commands, the commands do not have access to the database. 

Therefore, running a script to run the migrations will not work because it can't connect to the database.

**A few approaches I have looked into:**

1. Building the project inside the VPC which allows me to run the db:migrate and connect to the database.  The downside to this approach is theres a huge amount of complexity and we need to scale up to 100 aws accounts which severely complicates our CI/CD cross account resource sharing configuration.

2. Running the db:migrate inside a lambda (I have not found anyone else who has done this successfully). However, this will drastically simplify our deployments if we could run the CLI inside a lambda as it will have access to the database and will not require configuring cross-account policies in aws for codebuild and codepipeline.
3. Running db:migrate from code (Similar to sequelize.sync()). However, this does not look possible, but would help avoid a ton of complexity on our deployment pipeline configuration.
4. Using a post-deploy hook script to run the migrations via serverless. Using the serverless plugin `serverless-sequelize-migrations`. However, this will not work as it runs the command locally and cannot connect to the database since it is not public.

Can anyone provide me with some guidance on an approach you would recommend to solve this issue? I

### Additional context
- Using CodeCommit, CodePipeline and CodeBuild on a AWS tools account to manage our Code and our CI/CD. 
- We are deploying to many other AWS accounts that are running inside their own VPC.
- Each account has its own RDS database(not publicly accesible) running inside a VPC.
- Using serverless to deploy services/lambdas
-

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by leandrosandoval** [comment]
@fostahgix were you able to make it work?

**Comment by Irshad-ideabits** [comment]
I found that adding the VPC and the private subnets to the existing codebuild project did not solve the issue and after a build is run once VPC is added , it fails and its configuration shows that the build was not actually associated with the VPC . But when I deleted the existing codebuild project and created a new one in the VPC and private subnets it worked like a charm

**Comment by lshaozhe** [comment]
The approach I did to run migrations/seeds (created with Sequelize) into AWS RDS was through a AWS Lambda acting as a bastion/jump host with Umzug.

1. You will need a lambda that requires umzug, sequilize and mysql2 (depending on what instance of DB you are running on RDS, for me it was mysql)

2. You can then create a index file for the lambda bastion as follows:

 ```
const { Sequelize } = require('sequelize');
const { Umzug, SequelizeStorage } = require('umzug');

const sequelize = new Sequelize(
// DB config here as per sequelize requirement
);

exports.handler = async () => {
  try {
    // Initialize Umzug for running migrations
    const umzug = new Umzug({
      migrations: {
        glob: [
          '{migrations/*.js,seeders/*.js}',
          // modify as required depending on where you place your migration/seeds folder within this bastion lambda
          { cwd: __dirname },
        ],
        resolve: ({ name, path, context }) => {
          const migration = require(path || '');
          return {
            name,
            up: async () => migration.up(context, Sequelize),
            down: async () => migration.down(context, Sequelize),
          };
        },
      },
      context: sequelize.getQueryInterface(),
      storage: new SequelizeStorage({ sequelize }),
      logger: console,
    });

    await umzug.down();
    // Run pending migrations
    const migrations = await umzug.up();
    console.log('Migrations executed:', migrations);

    return {
      statusCode: 200,
      body: JSON.stringify({ message: 'Migrations executed successfully' }),
    };
  } catch (error) {
    console.error('Error executing migrations:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({
        message: 'Error executing migrations',
        error: error.message,
      }),
    };
  }
};
```
