### ISSUE TITLE
Set schema of through table for M to N Associations in a multi tenant schema based approach

### ISSUE THREAD

**Issue by Johannes-** [sequelize/sequelize#13474]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Is your feature request related to a problem? Please describe.

I'm trying to use sequelize with a PostgreSQL to create a multi tenant schema based application. For simple queries this works fine as i can do things like that:

```js
User.schema('Tenant_a').findOne();
```

It even works for 1 to n Associations. There I can use it like this:

```js
User.schema('Tenant_a').getRoles({schema: 'Tenant_a'})
```

However in case of n to m Associations it is not possible to set the schema for the through table dynamically. This leads to the problem that the through table of the public schema is used or the one i used for the initialization of the association. But it is not possible to set the schema for the trough table dynamically.

```js
const user = await User.schema('Tenant_a').findOne();
const role = await Role.schema('Tenant_a').findOne();
user.addRole(role);
```

### Describe the solution you'd like

As soon as one uses one of the AssociationsMixin Functions it would be nice to be able to pass the schema for the through table.

```js
    const user = await User.schema('Tenant_a').findOne();
    const role = await Role.schema('Tenant_a').findOne();
    user.addRole(role); // <- Would be nice to have an option to set the schema for the through table
```

### Why should this be in Sequelize

I guess in many cases a multi tenant schema based approach is one of the best fitting solutions. Therefore it would be nice to be able to set the schema dynamically for all operations i can do with sequelize.

### Describe alternatives/workarounds you've considered

The only workaround I know is to use raw queries.

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): PostgreSQL

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nakjunizm** [comment]
Same here. Any updates?
