### ISSUE TITLE
$nested.column$ syntax throws "Unknown column in 'where clause"

### ISSUE THREAD

**Issue by awesomelike** [sequelize/sequelize#13480]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

```js
let where = { memberId };
if (req.query.search) {
  const like = { [Op.like]: `%${req.query.search}%` };
  where = {
    ...where,
    [Op.or]: [
      { '$bookItem.serial$': like },
      { '$bookItem.book.name$': like },
      { '$bookItem.book.ISBNCode$': like },
    ],
  };
}

const options = {
  where,
  include: [
    {
      model: models.BookItem,
      as: 'bookItem',
      required: false,
      include: [
        {
          model: models.Book,
          as: 'book',
          attributes,
          required: false,
        },
      ],
    },
  ],
});

const transactions = await models.Borrow.findAll(options);
```

### What do you expect to happen?

I am trying to use the Sequelize ORM's feature that allows referring the nested column from the included Models (See Sequelize Docs: Complex where clauses at the top-level). In the docs it states that, I can use `$nested.column$` syntax.

### What is actually happening?

However, for the code above, I am getting the following error:
```
"Unknown column 'bookItem.serial' in 'where clause"
```

### Additional context

This is my DB schema for your reference: https://dbdiagram.io/d/5e08b6aaedf08a25543f79cb

### Environment

- Sequelize version: "^5.21.3"
- Node.js version: "12.19.0"

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using mysql, with connector library version "2.1.0" and database version 10.1.48-MariaDB

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by rafay-tariq** [comment]
I am receiving this same issue.

**Comment by rafay-tariq** [comment]
I have corrected this error on my side. Initially, I am writing this query 

but now I have rearranged the query and it works
### **WRONG QUERY**
     let where = {
        [op.and]: [
            { id: partner_id },
            { [op.or]: [
              { '$customers.customer_name$': { [op.like]: '%' + query + '%'} },
              { '$customers.email$': { [op.like]: '%' + query + '%'} },
            ]},
        ],
    };
      // const where = {
      //   id: partner_id
      // }
      return await this.deliveryBoys.findOne({

        attributes: [
          ['id', 'partner_id'],
          'delivery_boy_name',
          'email',
          'profile_picture',
          'phone_number',
          'fcm_token',
        ],
        include: [
          {
            model: this.customers,
            as: 'customers',
            attributes: ['id', 'customer_name', 'email', 'profile_picture', 'phone_number'],
            require: true,
            where: {
              customer_name: {
                [op.like]: '%' + query + '%'
              }
            },
            include: [
              {
                model: this.company,
                as: 'company',
              },
              {
                model: this.address,
                as: 'address',
                required: false,
                where: {
                  status: 1
                }
              }
            ]
          },

        ],
        where,
      });


**### FINAL WORKING QUERY**
` let where = {
        [op.and]: [
            { '$deliveryBoys.id$': partner_id },
            { [op.or]: [
              { '$customers.email$': { [op.like]: '%' + query + '%'} },
              { '$customers.customer_name$': { [op.like]: '%' + query + '%'} },
              { '$customers.phone_number$': { [op.like]: '%' + query + '%'} },
              { '$company.name$': { [op.like]: '%' + query + '%'} },
            ]},
        ],
    };

     return await this.customers.findAll({
        attributes: ['id', 'customer_name', 'email', 'profile_picture', 'phone_number'],
        include:[
          {
            model: this.deliveryBoys,
            as: 'deliveryBoys',
            attributes: ['id','delivery_boy_name','phone_number','email','profile_picture','status',],
            where:{
              id: partner_id
            }
          },
          {
            model: this.company,
            as: 'company',
          },
          {
            model: this.address,
            as: 'address',
            required: false,
            where: {
              status: 1
            }
          }
        ],
        where

      });`

**Comment by kanwarmanish** [comment]
> Hope this will help someone. In my case I just need to put `subQuery: false` then the Sequelize produces the right query.
> 
> ```
> return OutwardDetail.findAll({
>         limit: take,
>         offset: offset,
>         subQuery: false,
>         include: [
>             {
>                 model: OutwardDetailInspection,
>                 as: 'inspections',
>                 required: false,
>             }
>         ],
>         where: { "$inspections.id$": null }
>     });
> ```
> 
> The error happened because the `inspections.id` column was mentioned inside the sub-query which is the part before left join with the inspections (OutwardDetailInspection) table.

God bless you. I was going crazy for this. At my wits end. Thank you so much.

**Comment by gwvwl** [comment]
> Hope this will help someone. In my case I just need to put `subQuery: false` then the Sequelize produces the right query.
> 
> ```
> return OutwardDetail.findAll({
>         limit: take,
>         offset: offset,
>         subQuery: false,
>         include: [
>             {
>                 model: OutwardDetailInspection,
>                 as: 'inspections',
>                 required: false,
>             }
>         ],
>         where: { "$inspections.id$": null }
>     });
> ```
> 
> The error happened because the `inspections.id` column was mentioned inside the sub-query which is the part before left join with the inspections (OutwardDetailInspection) table.

Bro, thanks, its work )

**Comment by rohitbaisane** [comment]
@kanwarmanish 

Thanks for your answer it is really helpful.

But, `subquery: false` is not possible to use  when you want` limit` and `offset` to be only applied to your main Model and not all the associations.

**Comment by spirituelle** [comment]
@rohitbaisane 
Yes the `subquery: false` impact the `limit` and `offset`  form me too. it limits the number of row returned but when i use `findAndCountAll ()` it seems that the count is not impacted and it return the real number of element in the where clause
