### ISSUE TITLE
how to use Modal.update(...) to run `UPDATE product SET stock = stock - 1 WHERE id = 1;`

### ISSUE THREAD

**Issue by syymo** [sequelize/sequelize#13503]
how to use Modal.update(...) to run `UPDATE product SET stock = stock - 1 WHERE id = 1;`

**Comment by hanrea** [comment]
let p  = await Product.findOne({where:{ id:! } })
await  p. decrement( {
stock: 1
})

**Comment by hanrea** [comment]
Product.update({stock:sequelize.literal('`stock ` -1')}, {where:{id:1}})
