### ISSUE TITLE
Use of Generate_series function in Sequelize for range dates

### ISSUE THREAD

**Issue by inane** [sequelize/sequelize#13516]
Hello,

I am trying to do this query in Sequelize with node but I am not being able.

Any clue? Here is the query working in postgresql console:

`SELECT generate_series(date_start, date_end, '1 day' ::interval)::date as date FROM "WorkingDays" where id_employee='e8bd7e92-fad7-4781-beda-195a62a5d75f'`

Thank you in advance.

**Comment by Codehouze** [comment]
What error are you getting when you run your code?

**Comment by inane** [comment]
> you can use raw sql in sequelize. like so :
> await sequelize.query(SELECT generate_series(date_start, date_end, '1 day' ::interval)::date as date FROM "WorkingDays" where id_employee='e8bd7e92-fad7-4781-beda-195a62a5d75f');

I tried that raw query and it is not working. I had multiple problems with the syntax and I did not continue...

**Comment by inane** [comment]
That was my solution to introduce the result in a findAll query.
```
attributes : [
         [ models.NonWorkingDays.sequelize.Sequelize.literal ( "generate_series(fecha_inicio, fecha_fin, '1 day' ::interval)::date " ),
         'dia' ] ]
```
