### ISSUE TITLE
HasMany association coming wrong with "raw" and "nest" as true

### ISSUE THREAD

**Issue by henriqueArrazao** [sequelize/sequelize#13517]
![image](https://user-images.githubusercontent.com/65516006/134721224-3d0bd538-6d1d-48cf-8646-19f8ac168866.png)

**Comment by alissonzampietro** [comment]
Doesn't make sense you use the both properties in the same time been the both are opposite functionality. 
When you set raw as true, sequelize will convert a property that represents a relationship, in the same level as the list of model's properties adding dots, for example:

"productCartItems": {"id": 1} would be: "productCartItems.id": 1


Hence use the nest as true gonna make the opposite.

**Comment by AllAwesome497** [comment]
I think what you're looking for is `plain: true`.  That will prevent sequelize from instantiating the results as non-standard JS objects while still getting digestible results.

**Comment by victorbojica** [comment]
The issue still seems to be ocurring. Any idea on how to work around this ? I need to get a plain object that contains all the relationships correctly.
