### ISSUE TITLE
Model synchronization - DELETE or SKIP CHECKS rows which are not referenced in other table

### ISSUE THREAD

**Issue by fzn0x** [sequelize/sequelize#13513]
## Feature Description

Unreferenced row may be a solution when you got stuck when using **Model synchronization** with `{ alter: true }` by unreferenced row.

### Describe the solution you'd like

Add a key to column on model definition wheres you want to delete the unreferenced rows.

```js
      id_city: {
        type: DataTypes.BIGINT(20),
        references: {
          model: "cities",
          key: "id_city",
        },
        no_unreferenced_row: true // false by default
      },
```

### Why should this be in Sequelize

May be a solution when you got stuck when using **Model synchronization** with `{ alter: true }` by unreferenced row.

## Feature Request Checklist

- [ ] DELETE rows which are not referenced in other table with `no_unreferenced_rows` option in model definition.

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by fncolon** [comment]
current solution: 
```js
  sequelize.query(
    "DELETE FROM postal_codes WHERE id_district not in (select id_district from districts)"
  );
```
