### ISSUE TITLE
Sequelize Slow Performance with MariaDB/MySQL

### ISSUE THREAD

**Issue by domenicomanna** [sequelize/sequelize#13524]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
When I hit an endpoint that performs a long sql query, any future requests to different endpoints that should be quick take a significantly longer time to finish.
### SSCCE

**Here is the link to the SSCCE for this issue:** [Repo](https://github.com/domenicomanna/sequelizeMysqlPerformance). Please follow the instructions provided in the [README](https://github.com/domenicomanna/sequelizeMysqlPerformance/blob/master/README.md) to get the project up and running locally.

### What do you expect to happen?
I expect that when one request is made to an endpoint that performs a large query, the response time of future requests made to different / simpler endpoints should not be dramatically increased.

### What is actually happening?

If I open two terminal instances, and in one terminal i run: 
`watch -n 1 time curl http://localhost:3000/helloWorld --silent`.
and in the other i run:
`watch -n .5 time curl localhost:3000/longQueryWithSequelize --silent`
the response time of the `helloWorld` request, shoots up from **~6ms to a consistent 500ms**.

If I restart the server, and instead run:
`watch -n .5 time curl localhost:3000/longQueryWithRawMysql --silent`
the response time of the `helloWorld` request consistently stays **UNDER 100ms**.

500ms for a response from an endpoint that does nothing seems excessive, and my guess is that somewhere sequelize is blocking the event loop more than it should be.

### Environment

- Sequelize version: 6.6.5
- Node.js version: 16.10.0
- TypeScript version: 4.4.3

### How does this problem relate to dialects?

- [x] I think this problem happens only for the following dialect(s): mysql, mariadb

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by rickbergfalk** [comment]
@domenicomanna I haven't tried your repo, but I did take a look at the code. 

I would say this behavior is somewhat expected, but you are seeing the worst of it since you are selecting 200,000 rows in a single query. 

For each row Sequelize instantiates a model, adding overhead compared to raw SQL. Sequelize is doing what the mysql client is doing plus its own stuff.

Something you could try is setting `raw: true`, which should return plain javascript objects.

```js
await Book.findAll( { limit: 200000, raw: true } );
```
