### ISSUE TITLE
Model.init running before sequelize instance created

### ISSUE THREAD

**Issue by kwiksilver3441** [sequelize/sequelize#13523]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
(typescript btw)
I've tried to separate out the models into their own files so I can have cleaner code. I've arranged it as 
-sequelize
--index.ts
--models
---Document.ts
---Service.ts
Where index.ts exports the sequelize instance, and the models init their values. 
Problem is, it seems the model instances attempt to use sequelize before it is initialized. Meaning it always errors "no sequelize instance passed". I would prefer to be able to sort my models and other config into their own file. Rather than building a super file like the typescript example. 
### SSCCE

I'm really not going to spend another 20 minutes on this.
**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
index.ts
import { Sequelize } from 'sequelize'
export const sequelize = new Sequelize('tester', 'root', '', {
   host: 'localhost',
   dialect: 'mysql',
   port: 3306
}
models/document.ts
import {sequelize} from '..'
import { DataTypes, Model } from 'sequelize'

export interface DocumentInterface {
    id?: number,
    path: string
}
export class Document extends Model<DocumentInterface> implements DocumentInterface {
    public id!: number
    public path!: string
}

Document.init(
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      autoIncrement: true,
      primaryKey: true
    },
    path: {
      type: DataTypes.STRING,
      allowNull: false
    }
  },
  {
    sequelize,
    tableName: 'Documents'
  }
)
```

### What do you expect to happen?
The program to await sequelize to finish before init is called. I am importing it after all. 

Not sure. Perhaps theres a different way to have them init, perhaps inside of my "index.ts" at the root of my sequelize folder, but while keeping all the attributes in the models. 

### What is actually happening?
Breaks

No sequelize instance passed

### Environment

- Sequelize version:sequelize@6.6.5
- Node.js version:v16.9.1
- If TypeScript related: typescript@4.2.4

### How does this problem relate to dialects?

- [x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x] No, I don't have the time and I wouldn't even know how to start.

**Comment by domenicomanna** [comment]
You want to initialize the models in the `index.ts` file (where you are creating the `sequelize` instance), and just make the model attributes a static property

so something like
```
const sequelize = new Sequelize('tester', 'root', '', {
   host: 'localhost',
   dialect: 'mysql',
   port: 3306
}
Document.init(Document.defnition, sequelize)
```

where the `Document.ts` file looks like:
```
import {sequelize} from '..'
import { DataTypes, Model } from 'sequelize'

export interface DocumentInterface {
    id?: number,
    path: string
}
export class Document extends Model<DocumentInterface> implements DocumentInterface {
    public id!: number
    public path!: string

    static definition = {
       id: {
            type: DataTypes.INTEGER.UNSIGNED,
            autoIncrement: true,
            primaryKey: true
       },
       path: {
            type: DataTypes.STRING,
            allowNull: false
        },
      ....
    }
}
```

See [this repo](https://github.com/domenicomanna/sequelizeMysqlPerformance) for more details (it contains the exact structure that you're looking for)

**Comment by kwiksilver3441** [comment]
> You want to initialize the models in the `index.ts` file (where you are creating the `sequelize` instance), and just make the model attributes a static property
> 
> so something like
> 
> ```
> const sequelize = new Sequelize('tester', 'root', '', {
>    host: 'localhost',
>    dialect: 'mysql',
>    port: 3306
> }
> Document.init(Document.defnition, sequelize)
> ```
> 
> where the `Document.ts` file looks like:
> 
> ```
> import {sequelize} from '..'
> import { DataTypes, Model } from 'sequelize'
> 
> export interface DocumentInterface {
>     id?: number,
>     path: string
> }
> export class Document extends Model<DocumentInterface> implements DocumentInterface {
>     public id!: number
>     public path!: string
> 
>     static definition = {
>        id: {
>             type: DataTypes.INTEGER.UNSIGNED,
>             autoIncrement: true,
>             primaryKey: true
>        },
>        path: {
>             type: DataTypes.STRING,
>             allowNull: false
>         },
>       ....
>     }
> }
> ```
> 
> See [this repo](https://github.com/domenicomanna/sequelizeMysqlPerformance) for more details (it contains the exact structure that you're looking for)

Thank you for this. This does contain the type of structure I am looking for and solves my issue that I was having. Now, if you can possibly help me one last time, I am having an issue with getting the associations right. If there is another, more thorough example for typescript that you can point me to, that would be great. The typescript docs on sequelize.org... is to put it plainly absolutely awful. It only references these "HasMany***AssocationMixin" for hasmany. When there are different relationship types. And meanwhile, all my create statements are including values that don't exist on the class and I've tried a bunch of different stuff to get it to work... It's been a bit of a pain lmao. Any help on this one would be appreciated as I think I'm pretty much done. I ran into these same kinds of issues at first as well, but decided since the project is almost done, I would refactor them to work _properly_ with typescript. I originally had a bunch of errors and decided just to write sequelize in JS to get it to work right.

**Comment by domenicomanna** [comment]
I never messed with the`HasMany***Associations`, I just declared associations in the most basic way possible like (using the example from https://sequelize.org/master/manual/typescript.html but with a lot of stuff trimmed off): 
```
// user.ts
class User extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes {
  public id!: number;
  public name!: string;
  public preferredName!: string | null; // for nullable fields

  public readonly projects?: Project[];

  public static associations: {
    projects: Association<User, Project>;
  };
}

// associations.ts or whatever
// Here we associate which actually populates our pre-declared `static association`
User.hasMany(Project, {
  sourceKey: "id",
  foreignKey: "ownerId",
  as: "projects", // this determines the name in `associations`!
});
```
And then when querying for users, if you also want the `Project` association loaded, you can just do something like
```
const user = User.findOne({
    include: {
        association: "projects"
    }
})
const projects = user.projects // do whatever you want with the projects...
```

Also, I can't close the issue because I'm not a maintainer. But, I'm pretty sure you can close it since you created it.

**Comment by kwiksilver3441** [comment]
Didn't really know what you were. But thanks anyways.
