### ISSUE TITLE
When doing a "create" , both the "afterSave" and "afterFind" hooks get called. Is this supposed to happen? 

### ISSUE THREAD

**Issue by AdamMarciniak** [sequelize/sequelize#13528]
When doing a "create" , both the "afterSave" and "afterFind" hooks get called. Is this supposed to happen? 

I'm doing a translate function for one of my columns that should be run when both "afterSave" and "afterFind" are triggered when I do a create or find. But in the case of a "create", both hooks get run. Is this supposed to work this way? I would have thought an afterFind happens after a "find" and not a "create".

**Comment by setanjan123** [comment]
I may be wrong on this since I have no idea how it is actually implemented but "create" returns to you the record you just created so maybe it executes a find after the record is created?
