### ISSUE TITLE
 timezone format incompatible with IANA standard timezone format was '+05:30'

### ISSUE THREAD

**Issue by rajnesh0409** [sequelize/sequelize#13536]
timezone format incompatible with IANA standard timezone format was '+05:30'
 "sequelize": "6.6.2"

**Comment by rajnesh0409** [comment]
`const sequelize = new Sequelize(process.env.DB_NAME, null, null, {
  replication: {
    read: [
      { host: process.env.SLAVE1_DB_HOST, username: process.env.SLAVE1_DB_USER, password: process.env.SLAVE1_DB_PASSWORD }
    ],
    write: { host: process.env.MASTER_DB_HOST, username: process.env.MASTER_DB_USER, password: process.env.MASTER_DB_PASSWORD }
  },
  pool: { // If you want to override the options used for the read/write pool you can do so here
    max: parseInt(process.env.DB_POOL_MAX),
    idle: parseInt(process.env.DB_POOL_IDLE_TIME)
  },
  dialect: process.env.DB_DATABASE,
  port: process.env.DB_PORT,
  timezone: "+05:30"
});`

**Comment by rajnesh0409** [comment]
``zxczxczxczxc
const sequelize = new Sequelize(process.env.DB_NAME, null, null, {
  replication: {
    read: [
      { host: process.env.SLAVE1_DB_HOST, username: process.env.SLAVE1_DB_USER, password: process.env.SLAVE1_DB_PASSWORD }
    ],
    write: { host: process.env.MASTER_DB_HOST, username: process.env.MASTER_DB_USER, password: process.env.MASTER_DB_PASSWORD }
  },
  pool: { // If you want to override the options used for the read/write pool you can do so here
    max: parseInt(process.env.DB_POOL_MAX),
    idle: parseInt(process.env.DB_POOL_IDLE_TIME)
  },
  dialect: process.env.DB_DATABASE,
  port: process.env.DB_PORT,
  timezone: "+05:30"
});

**Comment by soryy708** [comment]
Related? https://github.com/mariadb-corporation/mariadb-connector-nodejs/issues/48
Try one of these:
* Asia/Colombo
* Asia/Kolkata
(canonical names from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for +05:30 UTC offset)
