### ISSUE TITLE
How to do "LEFT JOIN ON AND" query in sequelize

### ISSUE THREAD

**Issue by orabudi** [sequelize/sequelize#13551]
I want to do a query in Sequelize but the Sequelize.JS documentation doesn't state how to do this.
The query is the following: 

``` sql
SELECT * FROM Computers AS c
LEFT JOIN ComputerPrograms AS cp 
ON c.ComputerId = cp.ComputerId AND cp.programName = 'windows_word'
WHERE cp.computerId is null
```
The problem is I don't know how to implement the ```ON c.ComputerId = cp.ComputerId AND cp.programName = 'windows_word'```
 part of the LEFT JOIN in the query and the ```WHERE cp.computerId is null```
 in sequelize.

Is there any way to implement the query in Sequelize?

**Comment by fabioalmeida100** [comment]
Hello my friend :-)

in this part of documentation you will find that you need:
https://sequelize.org/master/manual/eager-loading.html

But, I'll try help you, here:

- For you to do a LEFT JOIN you will to do any look like this:

```
YourSequelizeDefineComputers.findAll({
  include: [{
    model: ComputerPrograms // will create a left join
  }]
});
```

- With the WHERE that is it:
```
YourSequelizeDefineComputers.findAll({
  include: [{
    model: ComputerPrograms,
    where: { computerId : { [Op.ne]: null } } 
  }, 
 ],
});
```

But, remember: you need to have your model correctly set up, before do your command above, because this approach above will do a eager loading. For more info about associations, read: https://sequelize.org/master/manual/assocs.html

**Comment by fzn0x** [comment]
Did the answer above work for you? :)

**Comment by ephys** [comment]
It probably solved the issue but this brings up an interesting point: the `on` option to customize the `ON` clause is not documented

It's here in typings https://sequelize.org/api/v7/interfaces/includeoptions#on
But nothing in the association manual.

I'll transfer this issue to the documentation repository to include this in future revisions of the documentation :)

**Comment by fzn0x** [comment]
> It probably solved the issue but this brings up an interesting point: the `on` option to customize the `ON` clause is not documented
> 
> It's here in typings https://sequelize.org/api/v7/interfaces/includeoptions#on But nothing in the association manual.
> 
> I'll open an issue about that on the documentation: [sequelize/website#93](https://github.com/sequelize/website/issues/93)

Interesting catch

**Comment by AneriJoshi** [comment]
Hello friends, 
in the below query, I want a little change. I need "sender_id" instead of the receiver id.

for this => LEFT OUTER JOIN `users` AS `user` ON **`messages`.`receiver_id`** = `user`.`id` 
please suggest me :
 
 SELECT `messages`.`id`, 
        `messages`.`message_body`,
        `messages`.`sender_id`,
        `messages`.`receiver_id`,
        `messages`.`created_at`,
        `messages`.`updated_at`,
        `messages`.`viewed`,
        `user`.`id` AS `user.id`,
        `user`.`name` AS `user.name`,
        `user`.`email` AS `user.email`,
        `user`.`isActive` AS `user.isActive`,
        `user`.`socketID` AS `user.socketID`,
        `user`.`password` AS `user.password`,
        `user`.`createdAt` AS `user.createdAt`,
        `user`.`updatedAt` AS `user.updatedAt` FROM `messages` AS `messages` 
        
        LEFT OUTER JOIN `users` AS `user` ON **`messages`.`receiver_id`** = `user`.`id` 
        WHERE ((`messages`.`sender_id` = 7 AND `messages`.`receiver_id` = 6) 
                OR 
                (`messages`.`sender_id` = 6 AND `messages`.`receiver_id` = 7)
            );

**Comment by ephys** [comment]
Hi @AneriJoshi, please ask questions on how to use the ORM in https://github.com/sequelize/sequelize/discussions instead (don't forget to put your code in code blocks so we can read it)
