### ISSUE TITLE
Creating ordered Indexes

### ISSUE THREAD

**Issue by nikeee** [sequelize/sequelize#13550]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description
The docs state this sample for creating ordered indexes ([link](https://github.com/sequelize/sequelize/blob/main/docs/manual/other-topics/indexes.md)):
```ts
const User = sequelize.define('User', { /* attributes */ }, {
  indexes: [
    // Create a unique index on email
    {
      unique: true,
      fields: ['email']
    },

    // Creates a gin index on data with the jsonb_path_ops operator
    {
      fields: ['data'],
      using: 'gin',
      operator: 'jsonb_path_ops'
    },

    // By default index name will be [table]_[fields]
    // Creates a multi column partial index
    {
      name: 'public_by_author',
      fields: ['author', 'status'],
      where: {
        status: 'public'
      }
    },

    // A BTREE index with an ordered field
    {
      name: 'title_index',
      using: 'BTREE',
      fields: [
        'author',
        {
          attribute: 'title',
          collate: 'en_US',
          order: 'DESC',
          length: 5
        }
      ]
    }
  ]
});
```

### What was unclear/insufficient/not covered in the documentation
I tried creating an ordered index on the `itemId` attribute like so:

```ts
export default class Item extends Model {

    static initialize(sequelize) {
        this.init({
            id: {
                type: DataTypes.STRING(36),
                defaultValue: () => uuidv4(),
                primaryKey: true
            },
            itemId: {
                type: DataTypes.STRING(32),
                allowNull: false
            },
        }, {
            sequelize,
            indexes: [
                {
                    using: "BTREE",
                    fields: [
                        {
                            attribute: "itemId",
                            order: "ASC",
                        }
                    ]
                }
            ]
        });
    }
}
```

It seems that `attribute` that is used in the object in the `fields` is not right there. The TypeScript types suggest that `name` instead of `attribute` would be correct.

### If possible: Provide some suggestion on how we can enhance the docs
I think one of these three things is true:
- The types are wrong/outdated.
- The docs  are wrong/outdated.
- I am doing it wrong. In that case, a better :tm: sample would be nice. 

If this is a docs/typing issue, I'd fix this if this would be up for grabs.

**Comment by nikeee** [comment]
I think this hasn't changed.

**Comment by fzn0x** [comment]
Hello @nikeee, is this bug still exist?

**Comment by fzn0x** [comment]
Hello @nikeee, is this issue still exist?

**Comment by fzn0x** [comment]
I'll remove the `type: docs` since it was not confirmed yet to be typing issue or documentation issue.

**Comment by ephys** [comment]
This might have been fixed since this issue was opened since [the documentation](https://sequelize.org/docs/v6/other-topics/indexes/) does state to use `name` and not `attribute`

Let us know if there is still an issue
