### ISSUE TITLE
Error in findAndCountAll in model.d.ts

### ISSUE THREAD

**Issue by wingedrhino** [sequelize/sequelize#13560]
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1930
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1931
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1932
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1933
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1934
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1935
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1936
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1937
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1938
https://github.com/sequelize/sequelize/blob/5e9c209cc8eaa1d38f33bb3ac2de8b8ab33929f2/types/lib/model.d.ts#L1939

It looks like findAndCountAll is defined twice in this file, once with the count being an array of numbers, and another with the count being just a number. This is messing with TypeScript intellisense.

**Comment by fncolon** [comment]
This is typescript feature called `Function overloading`. It is not messing with Typescript intellisense.

> Only the three overloads are recognized by TypeScript as possible signatures for a method call, not the actual implementation.
