### ISSUE TITLE
During running sequelize migration I got **ERROR: Identifier name 'xxxx' is too long**

### ISSUE THREAD

**Issue by Fantast616** [sequelize/sequelize#13563]
## Bug Description

During running sequelize migration I got

== 20211015153017-update-derivative-commodity-purchased: migrating =======

**ERROR: Identifier name 'derivative_commodity_purchased_derivative_commodity_id_foreign_idx' is too long**

```js
'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add altering commands here.
     *
     * Example:
     * await queryInterface.createTable('users', { id: Sequelize.INTEGER });
     */
    await queryInterface.addColumn(
        "derivative_commodity_purchased",
        "derivative_commodity_id", {
          type: Sequelize.DataTypes.INTEGER,
          references: {
            model: {
              tableName: 'derivative_commodity',
            },
            key: 'derivative_commodity_id',
          },
        },
    );
  },

  down: async (queryInterface, Sequelize) => {
    
   }

};

```

### What do you expect to happen?

When migrating, it should also be possible to specify the foreign key index name of related content as internally, rather than compulsorily forming a composite name index

### What is actually happening?

Show error 

### Additional context

Add any other context and details here.

### Environment

- Sequelize version: 6.2.0 
- Node.js version: 12.18.1 

### How does this problem relate to dialects?

- [x] I don't know, I was using mysql,

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by fncolon** [comment]
Your identifier name had `66` character, and the maximum length of identifier name is `64` https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html

it has nothing to do with Sequelize.
