### ISSUE TITLE
Redundant JOIN when foreign key is null?

### ISSUE THREAD

**Issue by talberko** [sequelize/sequelize#13591]
## Issue Creation Checklist

[ x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description
I have a model with multiple "belongsTo" colums. For example:
```
const Profile = sequelize.define('profile', {
  houseId: {
    type: Sequelize.INTEGER,
    references: {
      model: 'houses',
      key: 'id',
    },
    allowNull: true,
  },
  carId: {
    type: Sequelize.INTEGER,
    references: {
      model: 'cars',
      key: 'id',
    },
    allowNull: true,
  },
})
```

I want to include all data when getting the model, so I added a scope:
```
Profile.addScope('somescope', {
  include: [House, Car]
})
```

When I look at the DB query, I see that there are 2 JOIN queries, even if some of the keys are null (for example person with `carId` is null.
I would expect that a JOIN query will be added only when the field is not null.

Any idea how can I include only when the foreignKey is not null?

### Is this issue dialect-specific?

- [x ] No. This issue is relevant to Sequelize as a whole.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by talberko** [comment]
@fncolon any idea?

**Comment by WikiRik** [comment]
@fncolon any ideas?
