### ISSUE TITLE
The cached transaction connection causes us to query the wrong database when working with multiple databases

### ISSUE THREAD

**Issue by jlw0** [sequelize/sequelize#13606]
## Issue Creation Checklist

- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

Code from sequelize.js --> async query(sql, options) --> line 663
```
const connection = await (options.transaction ? options.transaction.connection : this.connectionManager.getConnection(options));
```

### What do you expect to happen?

I would expect this code to not use the transaction and the transaction's connection when the transaction is associated with a different database.

### What is actually happening?

When the following code is run:
```
await mysqlDatabase.transaction(async t => {
   await postgresDatabase.models.users.findById('abc');
});
```

The postgres query will run against the mysql database and fail since it pulls the connection off of the transaction.

### Additional context

This issue occurred since we are using CLS to pass transactions to Sequelize.

### Environment

- Sequelize version: 6.7.0
- Node.js version: v12.22.6

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
That doesn't sound right.

The connection of the transaction will only be used if the query is run in that transaction.

The following `findById`:

```js
await mysqlDatabase.transaction(async t => {
   await postgresDatabase.models.users.findById('abc');
});
```

will only run on that connection if `CLS` is enabled, or the transaction is passed to the query. Otherwise another connection will be used.

If `CLS` is enabled, you can run a query outside of the transaction by setting it to null explicitely

```js
await mysqlDatabase.transaction(async t => {
   await postgresDatabase.models.users.findById('abc', { transaction: null });
});
```
