### ISSUE TITLE
Unique Field DB error custom message feature broken.

### ISSUE THREAD

**Issue by Puvipavan** [sequelize/sequelize#13601]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
One of the field in my model which has custom error message for unique field.

```js
phone: {
  type: DataTypes.STRING(13),
    allowNull: true,
    unique: {
      args: true,
      msg: "Phone already in use."
  },
  validate: {
    len: {
      args: [10, 12],
      msg: "Phone number can contain 10-12 numbers only"
    },
    isNumeric: {
      args: true,
      msg: "Phone number can contain numbers only"
    },
    checkPhoneNull(value) {
      if (value == null && this.email == null) {
        throw new Error('Please Enter valid Email or Phone Number');
      }
    }
  }
}
```

### What do you expect to happen?
It should throw the error message: "Phone already in use."

### What is actually happening?
It throws the error message: "users.users_phone_unique must be unique"

### Additional context
I started developing my project after several months(Maybe 4 or 5). Previously it worked fine but in the middle I think I have upgraded or changed my Database from MariaDB to MySQL. I tried updating Sequelize but it didn't work. This is the error message I got for the duplicate entry.
```
#1062 - Duplicate entry '0000000000' for key 'users.users_phone_unique'
```
The bad regex at following line: https://github.com/sequelize/sequelize/blob/eeb6a8fbeb6549be038f2dbb0eefb414c7450653/lib/dialects/mysql/query.js#L215
yields to the wrong `fieldKey ` at following line: https://github.com/sequelize/sequelize/blob/eeb6a8fbeb6549be038f2dbb0eefb414c7450653/lib/dialects/mysql/query.js#L219 which sets to unique key to false at line no 221. Also it's passing same `fieldKey` to the following line(): https://github.com/sequelize/sequelize/blob/eeb6a8fbeb6549be038f2dbb0eefb414c7450653/lib/dialects/mysql/query.js#L233

So the expected `fieldKey` should be `users_phone_unique` but the actual `filedKey` is `users.users_phone_unique`

I'm not expert at this, But I will try to give a PR by tomorrow night. Going to sleep, It's already morning 6:24 AM :(

### Environment
- Sequelize version: 6.8.0
- Node.js version: 10.19.0
- MySQL Server version(Community Server): 8.0.25

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): mysql
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sdepold** [comment]
Is this fixed in main? I'll have it released tomorrow

**Comment by Puvipavan** [comment]
@sdepold Yes, Now it is working as expected 😊😊😊

**Comment by Puvipavan** [comment]
This issue has been fixed as of https://github.com/sequelize/sequelize/releases/tag/v6.9.0, Hence closing.
