### ISSUE TITLE
`Op.not` operator is ignored when used with `Sequelize.where()`

### ISSUE THREAD

**Issue by ephys** [sequelize/sequelize#13602]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

the `NOT` operator is ignored when used with `Sequelize.where` like in [this exemple](https://github.com/ephys/sequelize-sscce/blob/master/src/sscce.js#L34)

### SSCCE

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/194

### What do you expect to happen?

`{ [Op.not]: Sequelize.where(col, op, value) }` generates as as `NOT(col op value)`

### What is actually happening?

The generated query is lacking a NOT operator: `{ [Op.not]: Sequelize.where(col, op, value) }` generates as as `col op value`

### Additional context

Add any other context and details here.

### Environment

- Sequelize version: 6.8.0
- Node.js version: 14.18.1

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Still an issue

**Comment by ephys** [comment]
not stale :)

**Comment by madguy02** [comment]
@WikiRik can i start looking into this issue? If you haven't taken it up already?

**Comment by WikiRik** [comment]
It would be great if you could look into this issue, thanks!
