### ISSUE TITLE
Allow customization for timestamp

### ISSUE THREAD

**Issue by CustomHaven** [sequelize/sequelize#13613]
Can you add customization object option for createdAt and updatedAt timestamps. 

Because sometimes a project requires that the timestamp to be snake case and formatted as ``YYYY-MM-DD HH:mm:ss`` and not have any milliseconds ie be truncated (which can easily be done with the ``pg`` package). So at the moment on how Sequelize define table method is set up it does not allow these timestamps to be customized with an object and throws this following error when we try to customize it:

```js
          throw new Error(`Value for "${key}" option must be a string or a boolean, got ${typeof this.options[key]}`);
          ^

Error: Value for "createdAt" option must be a string or a boolean, got object
```

And here is a code snippet of what I mean with "let us customize" inside the option section of define:

```js
    timestamps: true,
    createdAt: {
      type: DataTypes.DATE(3),
      defaultValue: sequelize.NOW,
      set(value) {
        return value.toISOString().replace(/T/, ' ').replace(/\..+/g, '')
// coming into the database as 2021-10-31 01:34:48.81+00 so we wanted to remove everything after the dot
      },
      field: 'created_at'
    },
```

## Issue Creation Checklist

[X ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. Example: I'm always frustrated when ...

### Describe the solution you'd like

A clear and concise description of what you want to happen. How can the requested feature be used to approach the problem it's supposed to solve?

```js
// If applicable, add a code snippet showing how your feature would be used in a real use-case
// My comment please refer above
```

### Why should this be in Sequelize

Short explanation why this should be part of Sequelize rather than a separate package.

### Describe alternatives/workarounds you've considered

A clear and concise description of any alternative solutions or features you've considered. If any workaround exists to the best of your knowledge, include it here.

### Is this feature dialect-specific?

- [X ] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ X] No, I don't have the time and I wouldn't even know how to start.

**Comment by fncolon** [comment]
You can use hooks for that, if it's timestamp, it's not correct to use setter and getter method because you must set it manually, in top of all models you can define the following :
````js
{
    tableName: 'users',
    hooks : {
        beforeCreate : (record, options) => {
            record.dataValues.createdAt = new Date().toISOString().replace(/T/, ' ').replace(/\..+/g, '');
            record.dataValues.updatedAt = new Date().toISOString().replace(/T/, ' ').replace(/\..+/g, '');
        },
        beforeUpdate : (record, options) => {
            record.dataValues.updatedAt = new Date().toISOString().replace(/T/, ' ').replace(/\..+/g, '');
        }
    }
}
```

**Comment by fzn0x** [comment]
Hooks example already added, closing,. :)
