### ISSUE TITLE
Make multiple databases possible

### ISSUE THREAD

**Issue by ValentinRgt** [sequelize/sequelize#13621]
Hey,

Have you planned to add the ability to instantiate multiple databases?
Or make a system like this:

```
{
    "development": {
        "server01": {
            "username": "root",
            "password": null,
            "database": "server01_dev",
            "host": "10.8.0.1",
            "dialect": "mysql"
        },
        "server02": {
            "username": "root",
            "password": null,
            "database": "server02_dev",
            "host": "10.9.0.1",
            "dialect": "mysql"
        }
    },
    "production": {
        "server01": {
            "username": "root",
            "password": null,
            "database": "server01_prod",
            "host": "10.8.0.1",
            "dialect": "mysql"
        },
        "server02": {
            "username": "root",
            "password": null,
            "database": "server02_prod",
            "host": "10.9.0.1",
            "dialect": "mysql"
        }
    }
  }
```

And make our requests according to an instance, example :

```
const {User} = require("./models");
User.findOne({ where: { id: 12 } }).instance("server01 or server02");
console.log(User.id) // 12
```

If tomorrow you add this, it would be of great help to me for some project.

**Comment by ValentinRgt** [comment]
The same for sequelize-cli, in the console we do
npx sequelize db: create --instance server01 or server02
npx sequelize db: drop --instance server01 or server02
npx sequelize db: migrate --instance server01 or server02 ....

**Comment by soryy708** [comment]
You should be able to create multiple instances of `Sequelize` and then manage the lifecycle and access to them in user code.
Something like

```js
const [db1, db2, db3] = [
  new Sequelize(...),
  new Sequelize(...),
  new Sequelize(...),
];
db1.findOne(...);
```

**Comment by ValentinRgt** [comment]
By doing this we lose the usefulness of the "models / index.js" file .... but that's not the point.
The idea is to keep the basic structure without having to cheat with a lot of weird stuff ... Just push Sequelize a little further.

**Comment by soryy708** [comment]
How does this affect the usefulness of `models/index.js`?
I imagine it depends on how exactly you set up your `models/index.js`
