### ISSUE TITLE
Regular Expression Denial of Service vulnerability in the ansi-regex package in versions < 6.0.1

### ISSUE THREAD

**Issue by prashant93** [sequelize/sequelize#13620]
https://github.com/sequelize/cli/issues/970

Can anyone from sequelize or sequelize cli 

update the vulenrable package

cli-color
yargs

As Sequelize CLI is  use for migration and seeding. I have seen sequelize is updating time to time but CLI is not ?

**Comment by prashant93** [comment]
https://snyk.io/test/npm/sequelize-cli/6.2.0

**Comment by fncolon** [comment]
Hello, already ping core members to handle this. Please kindly wait.

**Comment by fncolon** [comment]
close this issue, lets move to the CLI issue one.

**Comment by prashant93** [comment]
@fncolon  Thanks!!
