### ISSUE TITLE
"Complex" DELETE query

### ISSUE THREAD

**Issue by eldritch-dev** [sequelize/sequelize#13639]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

Information about complex DELETE queries which involves destroying tuples with constraints and foreign keys linked to other tables is not covered in the documentation.

### If possible: Provide some suggestion on how we can enhance the docs
Please provide an example of a destroy method that deletes a record of say, "a client, the last sale the company has made to him, and the detail of that sale".

### Additional context

I'm building a REST API with NodeJS, Sequelize and PostgreSQL, and though I can use the destroy method, I'm having a lot of problems when the record I want to delete has "child records" associated.

**Comment by fncolon** [comment]
This is relationship and `onDelete: 'cascade'` related, basic knowledge of MySQL is required for this, **Sequelize** doesn't handle cascade , and does a **MySQL** cascade delete instead except you using `paranoid` with your models.

**Comment by eldritch-dev** [comment]
Thanks @fncolon ! I looked at my DB and there is a problem with that property on one of my tables! So that seems to be the problem! I'll let the issue open until I solve it and keep this issue updated until then.

**Comment by fzn0x** [comment]
I will assume that you already solve it :)

**Comment by eldritch-dev** [comment]
Indeed I did.
