### ISSUE TITLE
How can I query the data that match with specific month and year in Node Js?

### ISSUE THREAD

**Issue by MrPhyaeSoneThwim** [sequelize/sequelize#13631]
I have usage table to store daily usage of electric meter unit
The table contains the following fields
id->deviceId->numOfUnits->date

For me, I use Postgres SQL. I want to calculate the toal numOfUnits by querying with specific month and year for date attribute

**Comment by nandanv2702** [comment]
You can try using the `Op` object as follows:

```js
const { Op } = require('sequelize');

const res = await Table.findAll({
  where: {
    date: {
       [Op.between]: [startDate, endDate],
    },
  },
});
```
The inputs can be JS Date objects (start date of month / end date of month, or whatever range you're looking for) or just a string, e.g., '2021-11-01,' which works too. This is a method I've used before (in MSSQL though) so I found a similar answer in a Stackoverflow post [here](https://stackoverflow.com/questions/54543566/query-with-date-range-using-sequelize-request-with-postgres-in-node) and [here](https://stackoverflow.com/questions/29798357/sequelize-where-statement-with-date).

Let me know if this worked for you!

**Comment by fzn0x** [comment]
Did the answer above work for you? :)
