### ISSUE TITLE
sync needs to be improved

### ISSUE THREAD

**Issue by joacub** [sequelize/sequelize#13641]
The sync method to have updated the tables with the models is a little not efficient, the script makes the changes all the times even if there is no changes I the tables, which is unexpected, sequelize should check if the table/column has any changes and then if there is any changes do the query if not skip and keep for the next table.

Thanks by the way for the work.

**Comment by fncolon** [comment]
>  the script makes the changes all the times

You should create a new npm scripts for syncing instead of using watch mode. e.g `npm run db:sync`

So what you only do is just to authenticate to the database in watch mode.

```js
db.sequelize
  .authenticate()
  .then(() => {
    console.log(
      "\u001b[33m",
      "DATABASE CONNECTION ",
      CONFIG.dbName,
      " ESTABLISHED",
      "\u001b[39m"
    );
  })
  .catch((err) => {
    console.error("Unable to connect to database : ", err);
    process.exit(1);
  });
```

**Comment by joacub** [comment]
> > the script makes the changes all the times
> 
> You should create a new npm scripts for syncing instead of using watch mode. e.g `npm run db:sync`
> 
> So what you only do is just to authenticate to the database in watch mode.
> 
> ```js
> db.sequelize
>   .authenticate()
>   .then(() => {
>     console.log(
>       "\u001b[33m",
>       "DATABASE CONNECTION ",
>       CONFIG.dbName,
>       " ESTABLISHED",
>       "\u001b[39m"
>     );
>   })
>   .catch((err) => {
>     console.error("Unable to connect to database : ", err);
>     process.exit(1);
>   });
> ```

sorry I do not follow you..., can you can explain better ?

**Comment by fncolon** [comment]
> > > the script makes the changes all the times
> > 
> > 
> > You should create a new npm scripts for syncing instead of using watch mode. e.g `npm run db:sync`
> > So what you only do is just to authenticate to the database in watch mode.
> > ```js
> > db.sequelize
> >   .authenticate()
> >   .then(() => {
> >     console.log(
> >       "\u001b[33m",
> >       "DATABASE CONNECTION ",
> >       CONFIG.dbName,
> >       " ESTABLISHED",
> >       "\u001b[39m"
> >     );
> >   })
> >   .catch((err) => {
> >     console.error("Unable to connect to database : ", err);
> >     process.exit(1);
> >   });
> > ```
> 
> sorry I do not follow you..., can you can explain better ?

Syncing is not part of application runtime, **never run `sequelize.sync` on runtime**, instead you must build independent script to be run with node inside npm scripts.

e.g

package.json :
```
scripts: {
  "db:sync": "./build/db-sync.js"
}
```

/build/db-sync.js :
```
const db = require("../core/db.sequelizer");

db.sequelize.authenticate().catch((err) => {
  console.error("Unable to connect to database : ", err);
  process.exit();
});
  
db.sequelize.sync({ force: true }).then(() => {
  processAfterSync();
});
```

/core/db.sequelizer : Example [here](https://github.com/sequelize/express-example/pull/113/commits/a2fb98102d0f7a31c543655979083e4841068df2)

**Comment by joacub** [comment]
> > > > the script makes the changes all the times
> > > 
> > > 
> > > You should create a new npm scripts for syncing instead of using watch mode. e.g `npm run db:sync`
> > > So what you only do is just to authenticate to the database in watch mode.
> > > ```js
> > > db.sequelize
> > >   .authenticate()
> > >   .then(() => {
> > >     console.log(
> > >       "\u001b[33m",
> > >       "DATABASE CONNECTION ",
> > >       CONFIG.dbName,
> > >       " ESTABLISHED",
> > >       "\u001b[39m"
> > >     );
> > >   })
> > >   .catch((err) => {
> > >     console.error("Unable to connect to database : ", err);
> > >     process.exit(1);
> > >   });
> > > ```
> > 
> > 
> > sorry I do not follow you..., can you can explain better ?
> 
> Syncing is not part of application runtime, **never run `sequelize.sync` on runtime**, instead you must build independent script to be run with node inside npm scripts.
> 
> e.g
> 
> package.json :
> 
> ```
> scripts: {
>   "db:sync": "./build/db-sync.js"
> }
> ```
> 
> /build/db-sync.js :
> 
> ```
> const db = require("../core/db.sequelizer");
> 
> db.sequelize.authenticate().catch((err) => {
>   console.error("Unable to connect to database : ", err);
>   process.exit();
> });
>   
> db.sequelize.sync({ force: true }).then(() => {
>   processAfterSync();
> });
> ```
> 
> /core/db.sequelizer : Example [here](https://github.com/sequelize/express-example/pull/113/commits/a2fb98102d0f7a31c543655979083e4841068df2)

ooo now I got you, yes that's what I have, I never run in a runtime any script that do that kind of things, is common sense, I just telling the separate script in big databases is super slow, it should not redo everything, it should check if is needed to do something if not does not touch the db, that's how almost all ORM works. I mean I have a lot of experience with other ORM and all of them do this, if there is n changes does not touch the db or alter of course.

**Comment by fncolon** [comment]
> > > > > the script makes the changes all the times
> > > > 
> > > > 
> > > > You should create a new npm scripts for syncing instead of using watch mode. e.g `npm run db:sync`
> > > > So what you only do is just to authenticate to the database in watch mode.
> > > > ```js
> > > > db.sequelize
> > > >   .authenticate()
> > > >   .then(() => {
> > > >     console.log(
> > > >       "\u001b[33m",
> > > >       "DATABASE CONNECTION ",
> > > >       CONFIG.dbName,
> > > >       " ESTABLISHED",
> > > >       "\u001b[39m"
> > > >     );
> > > >   })
> > > >   .catch((err) => {
> > > >     console.error("Unable to connect to database : ", err);
> > > >     process.exit(1);
> > > >   });
> > > > ```
> > > 
> > > 
> > > sorry I do not follow you..., can you can explain better ?
> > 
> > 
> > Syncing is not part of application runtime, **never run `sequelize.sync` on runtime**, instead you must build independent script to be run with node inside npm scripts.
> > e.g
> > package.json :
> > ```
> > scripts: {
> >   "db:sync": "./build/db-sync.js"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > /build/db-sync.js :
> > ```
> > const db = require("../core/db.sequelizer");
> > 
> > db.sequelize.authenticate().catch((err) => {
> >   console.error("Unable to connect to database : ", err);
> >   process.exit();
> > });
> >   
> > db.sequelize.sync({ force: true }).then(() => {
> >   processAfterSync();
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > /core/db.sequelizer : Example [here](https://github.com/sequelize/express-example/pull/113/commits/a2fb98102d0f7a31c543655979083e4841068df2)
> 
> ooo now I got you, yes that's what I have, I never run in a runtime any script that do that kind of things, is common sense, I just telling the separate script in big databases is super slow, it should not redo everything, it should check if is needed to do something if not does not touch the db, that's how almost all ORM works. I mean I have a lot of experience with other ORM and all of them do this, if there is n changes does not touch the db or alter of course.

I see, I will set this to performance issue.

**Comment by joacub** [comment]
> > > > > > the script makes the changes all the times
> > > > > 
> > > > > 
> > > > > You should create a new npm scripts for syncing instead of using watch mode. e.g `npm run db:sync`
> > > > > So what you only do is just to authenticate to the database in watch mode.
> > > > > ```js
> > > > > db.sequelize
> > > > >   .authenticate()
> > > > >   .then(() => {
> > > > >     console.log(
> > > > >       "\u001b[33m",
> > > > >       "DATABASE CONNECTION ",
> > > > >       CONFIG.dbName,
> > > > >       " ESTABLISHED",
> > > > >       "\u001b[39m"
> > > > >     );
> > > > >   })
> > > > >   .catch((err) => {
> > > > >     console.error("Unable to connect to database : ", err);
> > > > >     process.exit(1);
> > > > >   });
> > > > > ```
> > > > 
> > > > 
> > > > sorry I do not follow you..., can you can explain better ?
> > > 
> > > 
> > > Syncing is not part of application runtime, **never run `sequelize.sync` on runtime**, instead you must build independent script to be run with node inside npm scripts.
> > > e.g
> > > package.json :
> > > ```
> > > scripts: {
> > >   "db:sync": "./build/db-sync.js"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > /build/db-sync.js :
> > > ```
> > > const db = require("../core/db.sequelizer");
> > > 
> > > db.sequelize.authenticate().catch((err) => {
> > >   console.error("Unable to connect to database : ", err);
> > >   process.exit();
> > > });
> > >   
> > > db.sequelize.sync({ force: true }).then(() => {
> > >   processAfterSync();
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > /core/db.sequelizer : Example [here](https://github.com/sequelize/express-example/pull/113/commits/a2fb98102d0f7a31c543655979083e4841068df2)
> > 
> > 
> > ooo now I got you, yes that's what I have, I never run in a runtime any script that do that kind of things, is common sense, I just telling the separate script in big databases is super slow, it should not redo everything, it should check if is needed to do something if not does not touch the db, that's how almost all ORM works. I mean I have a lot of experience with other ORM and all of them do this, if there is n changes does not touch the db or alter of course.
> 
> I see, I will set this to performance issue.

I was trying to resolve that by overwriting the query interface checking the models but needs more work that I though, and is going to be super easy if sequelize check this internally is gonna be super easy, just checking is all the things are equal if not just alter then that, this is gonna do also the sync({alter: true}) super safe and skip the use of migrations which is in my opinion for other purposes and also is a little bit over helmet for simple things if you don't want to track changes.

**Comment by fncolon** [comment]
> > > > > > > the script makes the changes all the times
> > > > > > 
> > > > > > 
> > > > > > You should create a new npm scripts for syncing instead of using watch mode. e.g `npm run db:sync`
> > > > > > So what you only do is just to authenticate to the database in watch mode.
> > > > > > ```js
> > > > > > db.sequelize
> > > > > >   .authenticate()
> > > > > >   .then(() => {
> > > > > >     console.log(
> > > > > >       "\u001b[33m",
> > > > > >       "DATABASE CONNECTION ",
> > > > > >       CONFIG.dbName,
> > > > > >       " ESTABLISHED",
> > > > > >       "\u001b[39m"
> > > > > >     );
> > > > > >   })
> > > > > >   .catch((err) => {
> > > > > >     console.error("Unable to connect to database : ", err);
> > > > > >     process.exit(1);
> > > > > >   });
> > > > > > ```
> > > > > 
> > > > > 
> > > > > sorry I do not follow you..., can you can explain better ?
> > > > 
> > > > 
> > > > Syncing is not part of application runtime, **never run `sequelize.sync` on runtime**, instead you must build independent script to be run with node inside npm scripts.
> > > > e.g
> > > > package.json :
> > > > ```
> > > > scripts: {
> > > >   "db:sync": "./build/db-sync.js"
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > /build/db-sync.js :
> > > > ```
> > > > const db = require("../core/db.sequelizer");
> > > > 
> > > > db.sequelize.authenticate().catch((err) => {
> > > >   console.error("Unable to connect to database : ", err);
> > > >   process.exit();
> > > > });
> > > >   
> > > > db.sequelize.sync({ force: true }).then(() => {
> > > >   processAfterSync();
> > > > });
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > /core/db.sequelizer : Example [here](https://github.com/sequelize/express-example/pull/113/commits/a2fb98102d0f7a31c543655979083e4841068df2)
> > > 
> > > 
> > > ooo now I got you, yes that's what I have, I never run in a runtime any script that do that kind of things, is common sense, I just telling the separate script in big databases is super slow, it should not redo everything, it should check if is needed to do something if not does not touch the db, that's how almost all ORM works. I mean I have a lot of experience with other ORM and all of them do this, if there is n changes does not touch the db or alter of course.
> > 
> > 
> > I see, I will set this to performance issue.
> 
> I was trying to resolve that by overwriting the query interface checking the models but needs more work that I though, and is going to be super easy if sequelize check this internally is gonna be super easy, just checking is all the things are equal if not just alter then that, this is gonna do also the sync({alter: true}) super safe and skip the use of migrations which is in my opinion for other purposes and also is a little bit over helmet for simple things if you don't want to track changes.

For now, you can make it complex e.g using command line question whether you need normal sync, force sync or alter sync.

I'm using `inquirer` and `prompt` library for that

**Comment by joacub** [comment]
@fncolon yep the problem is not really in force, problem is in alter mode, which should be just alter is there is alterations *, not need for me make options to do force or alter, also force is not usable for me at all, but I do understand is maybe useful for others, if you can make alter working properly will be nice and super safe fast updating between changes.

Thanks in advance sir.

**Comment by fncolon** [comment]
> @fncolon yep the problem is not really in force, problem is in alter mode, which should be just alter is there is alterations *, not need for me make options to do force or alter, also force is not usable for me at all, but I do understand is maybe useful for others, if you can make alter working properly will be nice and super safe fast updating between changes.
> 
> Thanks in advance sir.

Okay I will forward this to our internal discussion, thanks @joacub

**Comment by fncolon** [comment]
That's good idea for you, and i hope my answer useful for everybody ;) I hope alter and force would merge to one simple function without options `sync` too ;)

**Comment by fncolon** [comment]
That's good idea from you, and i hope my answer useful for everybody ;) I hope alter and force would merge to one simple function without options `sync` too ;)

**Comment by joacub** [comment]
> That's good idea from you, and i hope my answer useful for everybody ;) I hope alter and force would merge to one simple function without options `sync` too ;)

yep that could be good too.

🙌

**Comment by damms005** [comment]
@fncolon @joacub I stumbled upon this issue by randomly searching for [migration related issues](https://github.com/sequelize/sequelize/issues?q=is%3Aissue+is%3Aopen+migration).

Weird I was doing such a search? Well, I just wanted to affirm my conviction that [model synchronization](https://sequelize.org/master/manual/model-basics.html#model-synchronization) is such a powerful Sequlize feature, so much that it relegates the [migrations feature](https://sequelize.org/master/manual/migrations.html) to when you really need to time-travel with your DB (please correct me if I am wrong) - which should really be handled by something like [umzug](https://github.com/sequelize/umzug) (who needs time-travel in prod anyways...pooof :) )

So, yeah, anything that further improves model sync is a huge win for Sequelize

**Comment by joacub** [comment]
is there any advance on this ?

**Comment by ephys** [comment]
I don't think anyone is working on this at the moment.
Unless someone else is interested is implementing this, your best chance at seeing this implemented would be to send a pull request.

**Comment by joacub** [comment]
no news on this, this is been painfull when updates needed

**Comment by ephys** [comment]
Improving sync's `alter` mode is not in our priorities, so my statement from last January remains true, your best chance at seeing this implemented would be to send a pull request

Forgive my extremism but I personally consider `alter` to be useless, and I do not plan on ever taking the time to improve it (this is my personal opinion and doesn't necessarily reflect the opinion of the other maintainers). I will take the time to review PRs that do it though

**Comment by joacub** [comment]
So was is your suggestion to implement when you change the db and wants to sync ???

> Improving sync's `alter` mode is not in our priorities, so my statement from last January remains true, your best chance at seeing this implemented would be to send a pull request
> 
> Forgive my extremism but I personally consider `alter` to be useless, and I do not plan on ever taking the time to improve it (this is my personal opinion and doesn't necessarily reflect the opinion of the other maintainers). I will take the time to review PRs that do it though

So was is your suggestion to implement when you change the db and wants to sync ???

**Comment by ephys** [comment]
In development: Sync with `force: true` + re-seed (https://github.com/sequelize/sequelize/issues/15187)

In production: Migrations

**Comment by joacub** [comment]
> In development: Sync with `force: true` + re-seed mock data (#15187)
> 
> In production: Migrations

that's reset the table data...

**Comment by ephys** [comment]
> that's reset the table data...

Yep! With good seed data for development, that works really well imo

> why is so difficult to just match if the current table 

We're not stopping you from sending us a PR that does just that

Last I used doctrine, they didn't have a method like sync that you run in your app code. They use a cli that does the same thing, but which you run manually when you need it, not automatically every time the app restarts.

That is a better approach than sync. Altering an existing table is not something that can be fully automated and, by using a cli, doctrine let's you get the SQL and tweak it when the automated system gets it wrong.

I'd welcome a PR that adds that feature to our cli with open arms

**Comment by joacub** [comment]
> 

we use sync like I was using before doctrine, as client, we don't want the system automatically updating tables all the time the apps goes up, that a really bad idea and is super painful, we use sync only when we change something in the db and same thing with doctrine, we run doctrine client whe new change something in the db, I don't see any good thing on running this every time systems goes up.

thanks again, I will try if I have time to implement this. but the way that the meta data is in the sequelize makes this difficult to me as the datas does not match and there is no way to do this as per now(at least if the metadata does not change to match the current existing datas).
