### ISSUE TITLE
When the table contains an index and sync ({alter: true}), an error is reported

### ISSUE THREAD

**Issue by kangtongshun** [sequelize/sequelize#13649]
## Bug Description
Here is my code, Don't care about "source", because it's fake
![image](https://user-images.githubusercontent.com/72067214/141085954-56401f31-bb6a-48f7-8a29-89974e47b679.png)

An error occurred

![image](https://user-images.githubusercontent.com/72067214/141085067-a3cb9209-d1c9-4011-9f38-67afec600fb5.png)

**Comment by kangtongshun** [comment]
How to solve this problem?

**Comment by fncolon** [comment]
As you see, you defining indexes with `unique: true` which has `type` on the `field` list, but I think, you had duplicate value in `type` column before you commit to `alter`.  🐱

**Comment by kangtongshun** [comment]
@fncolon Isn't this a joint index? Shouldn't you constrain a field alone?

**Comment by kangtongshun** [comment]
@fncolon At least there are no constraints in the database. hah🐱

**Comment by fncolon** [comment]
@kangtongshun the problem is one the `unique: true` 😾 do you had try doing it with `unique: false`?

**Comment by kangtongshun** [comment]
Thank you for your reply.I tried 'unique: false' to solve this problem, but another problem occurred. In fact, I want to use `chatid` and `type` as primary key

**Comment by kangtongshun** [comment]
@fncolon Thank you for your reply.I tried 'unique: false' to solve this problem, but another problem occurred. In fact, I want to use chatid and type as primary key

**Comment by WikiRik** [comment]
Reopened, @fncolon can you still take a look at the comment below?

> @fncolon Thank you for your reply.I tried 'unique: false' to solve this problem, but another problem occurred. In fact, I want to use chatid and type as primary key

**Comment by ephys** [comment]
If I understand correctly, the unique index is not being created properly and only checks type instead of type+chat_id?

Could you try creating a [SSCCE](https://github.com/papb/sequelize-sscce) that replicates your issue?
