### ISSUE TITLE
[Feature Request] Expose pool diagnostic information

### ISSUE THREAD

**Issue by benasher44** [sequelize/sequelize#13660]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description

After upgrading to Sequelize 5/6 (from 4), we lost access to the `Sequelize.ConnectionManager`'s pool property. This makes sense, since the pool's implementation is now an internal detail of Sequelize. We were using this to access information about the pool, which we would periodically report to DataDog for diagnostic purposes. Here's how we do this after the upgrade (after adding sequelize-pool to our package.json):

```typescript
  const pool = (instance.connectionManager as any).pool as Pool<any>;
  registerGaugeCallback("sequelize.pool.size", {}, () => pool.size);
  registerGaugeCallback("sequelize.pool.available", {}, () => pool.available);
  registerGaugeCallback("sequelize.pool.borrowed", {}, () => pool.using);
  registerGaugeCallback("sequelize.pool.pending", {}, () => pool.waiting);
```

`registerGaugeCallback` sets up a timer that periodically polls those values and reports them to DataDog.

It would be great to expose these variables through some sort of `PoolDiagnostic` interface, so then the pool implementation details could continue to remain an internal detail of Sequelize.

### Is your feature request related to a problem? Please describe.

It's not really a problem. Implementing this feature request would allow us to be less careful about upgrades, in the sense that we wouldn't need to re-check our usage of these internals (i.e. whether this usage is still valid) across upgrades.

### Describe the solution you'd like

Ideally, a new getter is added to Sequelize.ConnectionManager, maybe called something like poolDiagnostics, which just returns the following interface:

```typescript
export interface PoolDiagnostics {
    size: number;
    available: number;
    using: number;
    waiting: number;
    // any other diagnostics that others might use could be added on here
}
```

Here's a sample implementation, which would go in `Sequelize.ConnectionManager`:
```typescript
public get poolDiagnostics(): PoolDiagnostics {
    return {
        size: pool.size,
        available: pool.available,
        using: pool.using,
        waiting: pool.waiting,
    }
}
```

These examples are TypeScript, but they should translate well to JavaScript.

### Why should this be in Sequelize

As of recent Sequelize versions, it hides the implementation of the pool. Adding this to Sequelize would allow us to continue to not care about the underlying pool implementation.

### Describe alternatives/workarounds you've considered

At the top of this, I laid out the hack we're using to currently work around this.

### Additional context

None that I can think of at the moment.

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by schmod** [comment]
It'd also be great if we could get metrics about how long requests sit waiting for a connection from the pool.

**Comment by djui** [comment]
Any updates on this?

Is it possible already to imitate this behaviour maybe using https://sequelize.org/docs/v6/other-topics/hooks/#connection-hooks ?

**Comment by ephys** [comment]
You can access it through `sequelize.connectionManager.pool.{size,available,using,waiting}`.

I think all that is missing is proper typing support, which will come as we're migrating everything to TS

**Comment by djui** [comment]
Thanks @ephys for the update! Appreciated 🙇

**Comment by djui** [comment]
Small correction/extension:

```
sequelize.connectionManager.pool.read.{size,available,using,waiting} // and/or
sequelize.connectionManager.pool.write.{size,available,using,waiting}
```
