### ISSUE TITLE
How to do reverse regex search in sequelize

### ISSUE THREAD

**Issue by aromalanil** [sequelize/sequelize#13668]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Is your feature request related to a problem? Please describe.

It is clearly mentioned in the docs, how to do a regex match using `sequelize`. But what I wish to have is reverse regex search, which is in-turn supported by Postgresql

### Describe the solution you'd like

I want to perform something like this.

eg:
```SQL
SELECT * FROM users WHERE '<example email>' ~ email_regex
```
> Where email_regex is a column in the table and `<example email>` is a sample email

Initially I tried this

```js
User.findAll({
 where: {
   email_regex: {
      [Op.regexp]: '<example email>'
    }
});
```
But it resulted in following query

```SQL
SELECT * FROM users WHERE  email_regex ~ '<example email>'
```

Then I tried to do it like this

```js
User.findAll({
 where: {
   ['<example email>']: {
      [Op.regexp]: 'email_regex'
    }
});
```

But, I am getting this error, then how exactly can we do reverse regex matching?

```log
column User.test@gamil.com does not exist
```

### Why should this be in Sequelize

This is feature is available in Postgresql.

### Describe alternatives/workarounds you've considered

I haven’t got any alternatives yet, Please share if there are any.

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): Postgresql

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by aromalanil** [comment]
Please don't close the issue. An answer would me much appreciated.

**Comment by ephys** [comment]
Might not work but have you tried this?

```typescript
User.findAll({
  where: Sequelize.where(
    Sequelize.literal('<example email>'),
    Op.regexp,
    'email_regex',
  ),
});
```

It generates the following clause:

![image](https://user-images.githubusercontent.com/1280915/145051223-afad7a9c-5643-48c2-95b3-8f45d8859a15.png)
