### ISSUE TITLE
The coordinates appear flipped in the examples, should be lng,lat.

### ISSUE THREAD

**Issue by reyemtm** [sequelize/sequelize#13671]
https://github.com/sequelize/sequelize/blob/47c4494968422585bf265063925d1662ffcd4173/lib/data-types.js#L805

https://github.com/sequelize/sequelize/blob/47c4494968422585bf265063925d1662ffcd4173/lib/data-types.js#L825

In GeoJSON coordinates are coded as `[lng,lat]` while the coordinates in the examples appear to be in `[lat,lng]`.

**Comment by reyemtm** [comment]
Sorry I get so used to seeing -80*, 3* I didnt even take into account that
the reverse is also valid. Thanks for understanding and not reprimanding
me. 👍

**Comment by sdepold** [comment]
:D I did some investigation and noticed that the given coordinates are somewhere in the Antarctica and if you swap them you end up on the US coast somewhere. So it seemed like a reasonable change indeed :)
