### ISSUE TITLE
Postgres dialect removes extra options from connection string and makes SSL hard to configure

### ISSUE THREAD

**Issue by rafiss** [sequelize/sequelize#13672]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Is your feature request related to a problem? Please describe.

I want to connect to my database using a connection string like this:
```
postgresql://root:password@localhost:5432/my_db?sslmode=verify-full&sslrootcert=%2Ftmp%2Fcerts%2Fca.crt&options=--search_path%3dmy_schema
```

However, it doesn't work, and I get a message from the server saying that I did not connect with the proper SSL configuration. Note that the same connection string works for me if I connect with https://github.com/brianc/node-postgres directly.

If I disable SSL in the server, and just try connecting with
```
postgresql://root@localhost:5432/my_db?options=--search_path%3dmy_schema
```
then I see that the `search_path` option does not get passed correctly.

### Describe the solution you'd like

I'd like to be able to use my connection string as-is.

node-postgres already includes a package that can handle the connection string and get all the SSL options from it. See https://github.com/brianc/node-postgres/blob/947ccee346f0d598e135548e1e4936a9a008fc6f/packages/pg-connection-string/README.md

However, currently Sequelize doesn't support this because it has different URL parsing here: https://github.com/sequelize/sequelize/blob/47c4494968422585bf265063925d1662ffcd4173/lib/sequelize.js#L185

Also, this part of the postgresql dialect only allows a subset of options to be passed in `dialectOptions`: https://github.com/sequelize/sequelize/blob/3ca085db318201fa59422a2ce191bcf76e5f37dc/lib/dialects/postgres/connection-manager.js#L96

I'd like to change that to allow the `options` parameter to be passed in.

### Why should this be in Sequelize

It would simplify the process of connecting to Postgres in two ways:
1. easier to pass in additional session options in the URL
2. easier to configure SSL

### Describe alternatives/workarounds you've considered

The workaround for the SSL configuration is to pass it in the options like this:
```
{
  dialect: "postgres",
  username: "root",
  host: "localhost",
  port: 5432,
  database: "my_db"
  dialectOptions: {
    ssl: {
      ca: fs.readFileSync("/tmp/certs/ca.crt").toString())
    },
  },
  logging: false,
}
```

However, as far as I can see, there is *no* workaround available for passing in the session variable `options` at connection time.

### Additional context

I work on CockroachDB and help maintain https://github.com/cockroachdb/sequelize-cockroachdb -- it inherits from the postgresql dialect. 

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): postgresql

### Would you be willing to implement this feature by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
Hi, looks like a valid request. Looking forward to seeing your PR!

**Comment by rafiss** [comment]
Thanks! I've made a PR at https://github.com/sequelize/sequelize/pull/13673 -- please let me know what you think
