### ISSUE TITLE
Type change for toJSON method

### ISSUE THREAD

**Issue by seba-ban** [sequelize/sequelize#13683]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

I've noticed that type definition changed recently. Consider below typescript snippet:

```js
interface ExampleInterface {
  message: string;
  randomNumber: number;
}

class Example extends Model<
  ExampleInterface & { id: number },
  ExampleInterface
> {
  public id!: number;
  public message!: string;
  public randomNumber!: number;

  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  toJSON(): ExampleInterface {
    const { message, randomNumber } = this;
    return { message, randomNumber };
  }
}
```
In version `6.9.0`, this is a valid code. However, in versions `6.10.0` and `6.11.0`, typescript reports an error on the `toJSON` method. Here's an example runnable repo with the above: https://github.com/seba-ban/sequelize-ts-test

It seems that previously, `toJSON` was returning an `object` type.  Now it returns `T extends TModelAttributes`. 

Even something like this is not accepted by Typescript:

```js
  toJSON() {
    const { id, message, randomNumber } = this;
    return { id, message, randomNumber };
  }
```

```text
Property 'toJSON' in type 'Example' is not assignable to the same property in base type 'Model<ExampleInterface & { id: number; }, ExampleInterface>'.
  Type '() => { id: number; message: string; randomNumber: number; }' is not assignable to type '<T extends ExampleInterface & { id: number; }>() => T'.
    Type '{ id: number; message: string; randomNumber: number; }' is not assignable to type 'T'.
      '{ id: number; message: string; randomNumber: number; }' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'ExampleInterface & { id: number; }'
```

I was using `toJSON` method to drop or modify some properties. Due to the fact that my existing code is not compiling due to type errors, I would consider release `6.10.0` to be a breaking change, therefore more of a `major`, than a `minor` bump.

Question to the maintainers: would you consider this to be a bug or is this something that will stay for a while? 

### Additional context

Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
This change was made in https://github.com/sequelize/sequelize/pull/13661
@Nkmol @Keimeno any thoughts on this issue?

**Comment by Nkmol** [comment]
I can have a look at this. Indeed, it should not be a breaking change in my opinion. We want to allow to `extend` this method without explicit type definition.

In order to keep the type contract of the base class intact, we can define an overload type for the non-generic variant as shown in the OP:

```ts
   public toJSON<T extends TModelAttributes>(): T;
   public toJSON(): object;
```

Let me create a PR and some tests tomorrow to see this actually works as expected.

**Comment by Nkmol** [comment]
@WikiRik @seba-ban Please check the PR I opened https://github.com/sequelize/sequelize/pull/13694. I added this scenario in the typing test to catch this regression.
