### ISSUE TITLE
Hooks API reference missing from docs generated for v4 and above version onwards

### ISSUE THREAD

**Issue by abhi5658** [sequelize/sequelize#13698]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

- **Hooks API reference** is missing from docs generated for v4 and above version onwards.
  - It is present in v3 docs at https://sequelize.org/v3/api/hooks/.
  - But not able to find it anywhere in v4 docs https://sequelize.org/v4/identifiers.html)
    - or v5 docs (https://sequelize.org/v5/identifiers.html)
    - or latest docs (https://sequelize.org/master/identifiers.html)

### If possible: Provide some suggestion on how we can enhance the docs

- Need to track what went wrong from v3 to v4 which made the Hooks API reference missing form the docs.

### Additional context

N/A

**Comment by WikiRik** [comment]
Are these the pages you are looking for?
v4; https://sequelize.org/v4/manual/tutorial/hooks.html
v5; https://sequelize.org/v5/manual/hooks.html
latest; https://sequelize.org/master/manual/hooks.html

**Comment by sdepold** [comment]
is it this one? https://sequelize.org/master/manual/hooks.html

**Comment by sdepold** [comment]
Ah. :) What Rik said

**Comment by sdepold** [comment]
Going to close this.
