### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by CryptoThree** [sequelize/sequelize#13692]

**Comment by hoalongnatsu** [comment]
How long does it take to recover?

**Comment by sushantdhiman** [comment]
`npm run docs` is failing again https://github.com/sequelize/sequelize.org/runs/4293752088?check_suite_focus=true#step:7:128

@sequelize/maintainers Please test docs in CI build process as I suggested earlier https://github.com/sequelize/sequelize/issues/13612#issuecomment-955700647

**Comment by soryy708** [comment]
Docs for v5 and below are up, but v6 leads to a 404 (File not found) page from GitHub Pages.

**Comment by yatolstoy** [comment]
I confirm. V6 documentation not available (404)

**Comment by sdepold** [comment]
It's back again. I have now setup an uptime checker to make sure we know about such issues in the future.
