### ISSUE TITLE
Error enum with postgres

### ISSUE THREAD

**Issue by Nelie-Taylor** [sequelize/sequelize#13690]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### I have a option

```js
gender: {
        allowNull: true,
        defaultValue: null,
        type: DataTypes.ENUM('male', 'female', 'other'),
      },
```

I run first time this ok. But restart code with database created not work:

```js
E:\HDG\HDID\ID-API\node_modules\sequelize\lib\dialects\postgres\query-generator.js:795
    text = text.replace(/^{/, '').replace(/}$/, '');
                ^
TypeError: text.replace is not a function
    at PostgresQueryGenerator.fromArray (E:\HDG\HDID\ID-API\node_modules\sequelize\lib\dialects\postgres\query-generator.js:795:17)
    at PostgresQueryInterface.ensureEnums (E:\HDG\HDID\ID-API\node_modules\sequelize\lib\dialects\postgres\query-interface.js:89:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.createTable (E:\HDG\HDID\ID-API\node_modules\sequelize\lib\dialects\abstract\query-interface.js:210:5)
    at async Function.sync (E:\HDG\HDID\ID-API\node_modules\sequelize\lib\model.js:1299:5)
    at async Sequelize.sync (E:\HDG\HDID\ID-API\node_modules\sequelize\lib\sequelize.js:800:35)
[nodemon] app crashed - waiting for file changes before starting...
```

i try print text at node_modules\sequelize\lib\dialects\postgres\query-generator.js:795:
```js
[ 'male', 'female', 'other' ]
```

![image](https://user-images.githubusercontent.com/12018657/142895289-91e454a3-13b7-41f6-a47a-44d1af4f57a9.png)

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by madguy02** [comment]
Can you try this out and see if it works:

```
gender: {
        allowNull: true,
        defaultValue: null,
       {
        type: DataTypes.ENUM('male', 'female', 'other'),
       values: [
         'male',
         female',
        'others'
      ],
      defaultValue: 'online' //may be set a default value as well (?)
      },

```
If you found a way to fix this, please update the comments :) (cc: @Nelie-Taylor )

**Comment by Nelie-Taylor** [comment]
> Can you try this out and see if it works:
> 
> ```
> gender: {
>         allowNull: true,
>         defaultValue: null,
>        {
>         type: DataTypes.ENUM,
>        values: [
>          'male',
>          female',
>         'others'
>       ],
>       defaultValue: 'online' //may be set a default value as well (?)
>      }
>       },
> ```
> 
> If you found a way to fix this, please update the comments :) (cc: @Nelie-Taylor )

Thank you @madguy02, i was try, but there is no difference.
![image](https://user-images.githubusercontent.com/12018657/144980543-69c7b389-3f96-4683-b954-57d6346bf0c9.png)

**Comment by ephys** [comment]
@Nelie-Taylor could you provide a sscce of this issue as well as the version of postgres & sequelize you're using?
