### ISSUE TITLE
wrong count in findAndCountAll when many-to-many relations

### ISSUE THREAD

**Issue by cage1618** [sequelize/sequelize#13705]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
const { createSequelizeInstance } = require("./dev/sscce-helpers");
const { Model, DataTypes } = require(".");

const sequelize = createSequelizeInstance({ benchmark: true });

class User extends Model {
  schema = {
    name: DataType.STRING
  }
}
User.init();

class Tenant extends Model {
  schema = {
    name: DataType.STRING
  }
}
Tenant.init();

class TenantUser extends Model {}
TenantUser.init();

User.belongsToMany(Tenant, {through: TenantUser});
User.hasMany(TenantUser);
Tenant.belongsToMany(User, {through: TenantUser});
Tenant.hasMany(Tenant);
TenantUser.belongsTo(User);
TenantUser.belongsTo(Tenant);
```

### What do you expect to happen?

User records:
SELECT * FROM "public"."User";
![image](https://user-images.githubusercontent.com/2541448/143274538-57103f57-e757-439a-8b73-177e4eaa1035.png)

Tenant records:
SELECT * FROM "public"."Tenant";
![image](https://user-images.githubusercontent.com/2541448/143274695-c00fc0f8-8223-4a5c-ba48-def4d2749b2b.png)

TenantUser records:
SELECT * FROM "public"."TenantUser" ;
![image](https://user-images.githubusercontent.com/2541448/143274900-91d27243-9f2f-4988-b0ae-e84981d48f0c.png)

```

const {rows, count} = await User.findAndCountAll({
  where: {
    id: 1
  },
  include: {
    required: false,
    model: Tenant
  }
})
```
I want count is 1.

### What is actually happening?

But I got count is 2.

### Additional context

Add any other context and details here.

### Environment

- Sequelize version: 6.12.0-alpha.1 
- Node.js version: 16.1.0

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by fncolon** [comment]
It might your `include` also counted, you can use `distinct: true` to resolve.

```js
const {rows, count} = await User.findAndCountAll({
  distinct: true,
  where: {
    id: 1
  },
  include: {
    required: false,
    model: Tenant
  }
})
```

See related issue [here](https://github.com/sequelize/sequelize/pull/4016#issuecomment-116294996)

**Comment by cage1618** [comment]
> 

resolved, thank you very much

**Comment by cage1618** [comment]
> It might your `include` also counted, you can use `distinct: true` to resolve.
> 
> ```js
> const {rows, count} = await User.findAndCountAll({
>   distinct: true,
>   where: {
>     id: 1
>   },
>   include: {
>     required: false,
>     model: Tenant
>   }
> })
> ```
> 
> See related issue [here](https://github.com/sequelize/sequelize/pull/4016#issuecomment-116294996)

resolved, thank you very much
