### ISSUE TITLE
Yarn add/remove doesn't work, "Found incompatible module"

### ISSUE THREAD

**Issue by soryy708** [sequelize/sequelize#13714]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

When trying to `yarn add` or `yarn remove`, `yarn.lock` isn't changed and an error is written to the console:

```
error @typescript-eslint/eslint-plugin@5.3.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Keimeno** [comment]
This is about adding dependencies to sequelize itself right? 
Some of our sub-dependencies are not compatible with older versions of node. You either have to upgrade to node 14.17.0 or add dependencies with the `--ignore-engines` flag

**Comment by soryy708** [comment]
Yes, this is about modifying dependencies of sequelize itself.

I have Node v14.15.0. What's special about >14.17.0?

[package.json](https://github.com/sequelize/sequelize/blob/main/package.json#L19) specifies that Sequelize supports node >=10.0.0. Therefore I expect things to work for any version from 10.0.0.

If the sub-dependencies aren't compatible with older versions of node, why not set the engine to 14.17.0 in package.json?

**Comment by WikiRik** [comment]
Sequelize and its dependencies do indeed support Node 10.0.0, but not all devDependencies do. Therefore it is not needed to set the engine to `^12.22.0 || ^14.17.0 || >=16.0.0` in package.json in my opinion.

It might be good to add to https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md that development might require a higher version of Node. Or as @Keimeno mentioned; using `yarn install --ignore-engines` also does the trick.

I do not know what is so special about > 14.17.0 but it is the minimum minor version of Node 14 that ESLint 8 (which @typescript-eslint/eslint-plugin 5.3.0 supports) asks for.

**Comment by soryy708** [comment]
I agree with you that if Sequelize and its dependencies support Node 10.0.0, there's no need to touch the engine in package.json.

I agree that the nuance about the devDependencies is worth adding to [`CONTRIBUTING.md`](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md), with the `--ignore-engines` workaround.

**Comment by madguy02** [comment]
Have tested this bit about installation, the enigne version does say `>= 10`, it works uptil node 14 (14.15.0 works as well). The only thing is there is no support of node16 yet. Probably it would be beneficial to add the node version description in the https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md (contributing) page.

I think we should not modify the engine description right now because even though it does not support node16, but in near feature we might have it, updating the documentation would help (for first time contributors)
