### ISSUE TITLE
If a BigInt/Int field exists on update, the record is not updated. 

### ISSUE THREAD

**Issue by microvn** [sequelize/sequelize#13724]
Hi,  

I am having a problem related to BigInt data field.  If the Id of is BigInt, the other Field is also BigInt. When performing Update it will not be updated on the database.  Specifically:
 

### SSCCE

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/200 

```js
// You can delete this code block if you have included a link to your SSCCE above!
'use strict';

// Require the necessary things from Sequelize
const { Sequelize, Op, Model, DataTypes } = require('sequelize');

// This function should be used instead of `new Sequelize()`.
// It applies the config for your SSCCE to work on CI.
const createSequelizeInstance = require('./utils/create-sequelize-instance');

// This is an utility logger that should be preferred over `console.log()`.
const log = require('./utils/log');

// You can use sinon and chai assertions directly in your SSCCE if you want.
const sinon = require('sinon');
const { expect } = require('chai');

// Your SSCCE goes inside this function.
module.exports = async function() {
  if (process.env.DIALECT !== "mysql") return;

  const sequelize = createSequelizeInstance({
    logQueryParameters: true,
    benchmark: true,
    define: {
      timestamps: false // For less clutter in the SSCCE
    },
    dialect: 'mysql',
    dialectOptions: {
        supportBigNumbers: true,
        bigNumberStrings: true,
        decimalNumbers: true,
        connectTimeout: 60000
    },
  });

  const Foo = sequelize.define('Foo', { id: {
            type: DataTypes.BIGINT,
            allowNull: false,
            primaryKey: true,
            defaultValue: () =>124594734759940096n
        },name: DataTypes.TEXT, indexCo: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0
        } });

  const spy = sinon.spy();
  sequelize.afterBulkSync(() => spy());
  await sequelize.sync();
  expect(spy).to.have.been.called;

  const data = await Foo.create({ name: 'foo' });
  log(data);
  data.indexCo = 100;
  log(data.save());
  expect(await Foo.count()).to.equal(100);
};
```

### What do you expect to happen?

Data is updated on the database

### What is actually happening?

Database not updated

### Temporary repair solution

Temporary repair solution
```js
set(value) {
      this.setDataValue('indexCo', value.toString());
}
```
### Environment

- Sequelize version: 6.6.5 && Latest 
- Node.js version: v14.17.0 
- If TypeScript related: TypeScript version: XXX 

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by neilnguyendev** [comment]
I have the same issue :(

**Comment by microvn** [comment]
I have found a change. starting from this version it was not possible to update.

Maybe it has some error related to bind update


```
5.0.0-beta.8
feat(query-generator): Generate INSERT / UPDATE using bind parameters [#9431](https://github.com/sequelize/sequelize/pull/9431) [#9492](https://github.com/sequelize/sequelize/pull/9492)
performance: remove terraformer-wkt-parser dependency #9545
fix(constructor): set username, password, database via options in addition to connection string#9517
fix(associations/belongs-to-many): catch EmptyResultError in set/add helpers #9535
fix: sync with alter:true doesn't use field name #9529
fix(UnknownConstraintError): improper handling of error options #9547
```

**Comment by microvn** [comment]
UP.

**Comment by ephys** [comment]
This does not look like a sequelize issue, you're using `numbers` outside their safe integer range

```typescript
Number.isSafeInteger(124594734759940096)
> false
```

JavaScript is unreliable when it's unable to properly represent the number:

```typescript
124594734759940096 === 124594734759940094
> true
```

You need to use js [bigints](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) or strings instead.

```typescript
124594734759940096n === 124594734759940094n
> false
```

**Comment by microvn** [comment]
I have tried with BigInt many times. Result is still error. It just doesn't error for String.

Along with that test, we tried with version before 6.6.5. It's work well.

**Comment by ephys** [comment]
I've just tested your SSCCE and one thing does crash (the logging. We'll fix that), the rest works as expected:

- `124594734759940096` is out of range for js number, changed it to `124594734759940096n`
- Subsequent runs of your SSCCE fail because ID `124594734759940096` already exists as you don't reset the DB between runs. Fixed by adding `force` parameter to `sequelize.sync`.
- Setting `data.indexCo = 124594734759940094n;` crashes in mysql because `124594734759940094` is out of range for INT. Changed column type to bigint.
- disabled logging. That part does crash.

Here is your SSCCE with those changes:

```typescript
'use strict';

// Require the necessary things from Sequelize
const { Sequelize, Op, Model, DataTypes } = require('sequelize');

// This function should be used instead of `new Sequelize()`.
// It applies the config for your SSCCE to work on CI.
const createSequelizeInstance = require('./utils/create-sequelize-instance');

// This is an utility logger that should be preferred over `console.log()`.
const log = require('./utils/log');

// You can use sinon and chai assertions directly in your SSCCE if you want.
const sinon = require('sinon');
const { expect } = require('chai');

// Your SSCCE goes inside this function.
module.exports = async function () {
  if (process.env.DIALECT !== 'mysql') return;

  const sequelize = createSequelizeInstance({
    logQueryParameters: false,
    benchmark: true,
    define: {
      timestamps: false, // For less clutter in the SSCCE
    },
    dialect: 'mysql',
    dialectOptions: {
      supportBigNumbers: true,
      bigNumberStrings: true,
      decimalNumbers: true,
      connectTimeout: 60000,
    },
  });

  const Foo = sequelize.define('Foo', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      defaultValue: () => 124594734759940096n,
    }, name: DataTypes.TEXT,
    indexCo: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0,
    },
  });

  const spy = sinon.spy();
  sequelize.afterBulkSync(() => spy());
  await sequelize.sync({ force: true });
  expect(spy).to.have.been.called;

  const data = await Foo.create({ name: 'foo' });

  data.indexCo = 124594734759940094n;
  await data.save();

  const persisted = await Foo.findOne();
  console.log(persisted.indexCo);

  expect(persisted.indexCo).to.equal('124594734759940094');
};
```

**Comment by microvn** [comment]
Hi @ephys 
`// You can delete this code block if you have included a link to your SSCCE above!
'use strict';

// Require the necessary things from Sequelize
const { Sequelize, Op, Model, DataTypes } = require('sequelize');

// This function should be used instead of `new Sequelize()`.
// It applies the config for your SSCCE to work on CI.
const createSequelizeInstance = require('./utils/create-sequelize-instance');

// This is an utility logger that should be preferred over `console.log()`.
const log = require('./utils/log');

// You can use sinon and chai assertions directly in your SSCCE if you want.
const sinon = require('sinon');
const { expect } = require('chai');

// Your SSCCE goes inside this function.
module.exports = async function() {
  if (process.env.DIALECT !== "mysql") return;

  const sequelize = createSequelizeInstance({
    logQueryParameters: true,
    benchmark: true,
    define: {
      timestamps: false // For less clutter in the SSCCE
    },
    dialect: 'mysql',
    dialectOptions: {
        supportBigNumbers: true,
        bigNumberStrings: true,
        decimalNumbers: true,
        connectTimeout: 60000
    },
  });

  const Foo = sequelize.define('Foo', { id: {
            type: DataTypes.BIGINT,
            allowNull: false,
            primaryKey: true,
            defaultValue: () =>124594734759940096n
        },name: DataTypes.TEXT, indexCo: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0
        } });

  const spy = sinon.spy();
  sequelize.afterBulkSync(() => spy());
  await sequelize.sync();
  expect(spy).to.have.been.called;

  const data = await Foo.create({ name: 'foo' });
  log(data);
  data.indexCo = 100;
  log(data.save());
  expect(await Foo.count()).to.equal(100);
};`

Try it with configuration like this.

Only the ID is BigInt. And the other columns are Int. You will see that it is not updating that record.

The log of that statement will be similar to this, but it will still not be updated to the database.

UPDATE `table` SET `indexCo`= 100 WHERE `id` = '124594734759940096'

Everything is still the same, no updates have taken place

**Comment by ephys** [comment]
You're right. There is a bug. If the `id` is `>= 71999999999999991`, calling `save` does not seem to work anymore

Passing as either a string or a bigint doesn't change.

Here is the updated sscce that demonstrates that:

```typescript
'use strict';

const { Sequelize, Op, Model, DataTypes } = require('sequelize');
const createSequelizeInstance = require('./utils/create-sequelize-instance');
const sinon = require('sinon');
const { expect } = require('chai');

module.exports = async function () {
  if (process.env.DIALECT !== "mysql") return;
  const sequelize = createSequelizeInstance({
    // logQueryParameters: false,
    // benchmark: true,
    define: {
      timestamps: false, // For less clutter in the SSCCE
    },
    logging: false,
    dialect: 'mysql',
    dialectOptions: {
      supportBigNumbers: true,
      bigNumberStrings: true,
      decimalNumbers: true,
      connectTimeout: 60000,
    },
  });

  const Foo = sequelize.define('Foo', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
    },
    indexCo: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },
  });

  await sequelize.sync({ force: true });

  // This works

  const idOne = 71999999999999990n;
  const dataOne = await Foo.create({ id: idOne });
  dataOne.indexCo = 100;
  await dataOne.save();
  expect((await Foo.findOne({ where: { id: idOne } })).indexCo).to.equal(100);

  // this one fails

  const idTwo = 71999999999999991n;
  const dataTwo = await Foo.create({ id: idTwo });
  dataTwo.indexCo = 100;
  await dataTwo.save();
  expect((await Foo.findOne({ where: { id: idTwo } })).indexCo).to.equal(100, 'model with id ' + 71999999999999991n + ' did not save properly');
};
```

**Comment by ephys** [comment]
Parameters are passed as-is to `mysql2`'s `Connection.execute` so I don't think this is a sequelize issue as much as a mysql2 issue?

log of parameters right before being passed to `mysql2`:

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1280915/148256622-9d565743-55ca-4c46-a1d1-d629b1384568.png">

**Comment by ngocmobilefolk** [comment]
@ephys I tried to execute the query that Sequelize passes to Mysql directly by console. The query was executed well. So I don't think this issue belongs to Mysql. :(

**Comment by ephys** [comment]
I'm going to close this issue now that https://github.com/sidorares/node-mysql2/issues/1483 has been created.

If it turns out it was, in fact, a Sequelize bug, let us know and we'll reopen.
