### ISSUE TITLE
Missing optional key in findall docs

### ISSUE THREAD

**Issue by Alastair-L** [sequelize/sequelize#13726]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

The `nest` option, which is supported by `model.findAll`, is not in the documentation. This key may be applicable for other find methods as well, but I didn't check.
Here is how you would use this option:
```javascript
const cars = await models.Car.findAll({
    include: [
      {
        model: models.Wheel,
        as: 'wheel',
      }
    ],
    order: [['id', 'ASC']],
    raw: true,
    nest: true,
  });
```
WithOUT the nest option, the result would look something like:
```javascript
{
  id: 'abc',
  'wheel.size': 10,
}; 
```
And with the next option it looks like this:
```javascript
{
  id: 'abc',
  wheel: {
    size: 10,
  },
}; 
```
### If possible: Provide some suggestion on how we can enhance the docs

Nest: If the 'raw' option is true, returns nested objects rather than a flat object with dotted keys. Default: false, optional

**Comment by fzn0x** [comment]
PR welcome :)

**Comment by ephys** [comment]
It is documented here for v7 https://sequelize.org/api/v7/interfaces/findoptions#nest
But is indeed missing from v6 https://sequelize.org/api/v6/class/src/model.js~model#static-method-findAll

As @fzn0x said, PR to the v6 branch welcome :)

**Comment by krupalimakadiya** [comment]
Request to review the PR: https://github.com/sequelize/sequelize/pull/14683

**Comment by WikiRik** [comment]
Closing since #14683 has been merged
