### ISSUE TITLE
SequelizeORM 6 not creating relations for every model

### ISSUE THREAD

**Issue by LouieMartin** [sequelize/sequelize#13733]
So, my SequelizeORM 6 is not creating a relation in my PostgreSQL server, this has been happening to for a week, so please respond quickly, thank you.

**Error**
![image](https://user-images.githubusercontent.com/73145637/144413766-84d8dbc5-8272-4c5d-b668-ef2df8c0c32f.png)

**Code**
```ts
import { Sequelize, DataTypes, Model } from 'sequelize';

const sequelize = new Sequelize('postgres://postgres:1234@localhost:5432/postgres');

class User extends Model {}

User.init({
    firstName: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    lastName: {
        type: DataTypes.STRING,
        allowNull: false,
    },
}, {
    tableName: 'users',
    modelName: 'User',
    sequelize,
});

(async () => {
    await User.create({
        firstName: 'John',
        lastName: 'Doe',
    });

    try {
        await sequelize.authenticate();
        console.log('Successfully established a connection with postgres 🎉')
    } catch (err) {
        console.error('Unable to establish a connection with postgres 😢')
    }
})();
```

**Things I've Tried**

**Creating a user relation directly**
```sql
CREATE TABLE Users ();
```

**Using other connecting options**
```ts
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize('postgres', 'postgres', '1234', {
    host: 'localhost',
    dialect: 'postgres',
});
```

**Comment by LouieMartin** [comment]
> Hi! Did this start to happen because of an update to Sequelize?

Yes, right after I updated to Sequelize V6 this started happening.

**Comment by WikiRik** [comment]
No, it should work fine with v6. Can you check which tables are in your database?

**Comment by LouieMartin** [comment]
> No, it should work fine with v6. Can you check which tables are in your database?

Ok.
the user relation was the one I made with ```sql
CREATE TABLE Users ();
```
![image](https://user-images.githubusercontent.com/73145637/144573745-c34f6abc-729a-42e7-9d99-813913ddc48c.png)

**Comment by WikiRik** [comment]
Try making a Users table, with a capital U. Should be achievable with
```sql
CREATE TABLE "Users" ();
```
