### ISSUE TITLE
Expand CLS options for transactions.

### ISSUE THREAD

**Issue by benasher44** [sequelize/sequelize#13741]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description

The core problem is that sequelize managed transactions aren't possible to replicate without access to Sequelize internals because `Transaction.finished` and `Transaction.cleanup` are private (or at least not exposed in the type definitions), but there are CLS-specific behaviors we would like to have that require access to them. Rather than expose these APIs, I think it makes sense that sequelize continues to own "how to correctly manage a transaction," but this means expanding the configuration options for `Sequelize.transaction` to improve usability in various CLS-type contexts.

### Is your feature request related to a problem? Please describe.

Backing up a bit, we have a large code base that already uses managed transactions all over the place, and we're interested in introducing CLS to allow "upper layers" of code, that call "lower layers" of code that already do transactional things, to group those into a single transaction (without weaving a transaction through 8 layers of functions and remembering to pass it to each query). The issue is that by default, using a managed transaction appears to overwrite the current transaction in the CLS namespace—managed transactions always start a new transaction and set it in the CLS namespace. What we want to do is allow managed transactions to inherit the current transaction from the CLS namespace, if one exists. Additionally, there may be other cases where you want to ignore the transaction in the CLS namespace, entirely.

For now, we've been able to replicate this behavior we want internally by copying out what `Sequelize.transaction` does in the managed case (i.e. when a block is passed), but this has meant copying out references to sequelize internals, such as `Transaction.cleanup`. This also brings up the point that if you were to write your own version of sequelize's managed transaction (for any reason) and didn't know about `Transaction.cleanup`, you could be leaving edge cases on the table.

### Describe the solution you'd like

To accommodate this, I propose adding the following option to `TransactionOptions` (flexible on naming here):
```typescript
export namespace Transaction {
// ... other stuff already in here
  enum CLSOPTION {
    ALWAYSNEW = 'ALWAYSNEW',
    INHERIT = 'INHERIT',
    NONE = 'NONE',
  }
}
```

- `ALWAYSNEW` does what it does today
- `INHERIT` will use a transaction if one exists in the CLS namespace, otherwise, it falls back to the `ALWAYSNEW` behavior
- `NONE` ignores the transaction in the CLS namespace and also does not set a transaction in the CLS namespace (as if CLS id not enabled)

### Why should this be in Sequelize

Without this, if you want these behaviors, you have to carefully copy out sequelize internals to replicate managed transactions yourself and then implement this behavior. I don't think this should be in a separate package, given the number of internal details involved related to sequelize transactions.

### Describe alternatives/workarounds you've considered

We have a workaround now, where we copy out the implement of sequelize managed transactions and add in this behavior.

### Additional context

Happy to add more, but I think the above paragraphs are thorough.

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by benasher44** [comment]
Still important!

**Comment by ephys** [comment]
Hi Ben!

Could you confirm that I understand the feature request correctly?

- `ALWAYSNEW`: if a transaction already exists in CLS, it creates a nested transaction (a savepoint), if no transaction exist, it creates a transaction.
- `INHERIT`: if a transaction already exists in CLS, it continues using that one without creating a nested transaction (no savepoint). If no transaction already exists, it creates a new transaction.
- `NONE`: sets the transaction for the current block to null (equivalent to passing `transaction: null` to all queries in this block).

**Comment by benasher44** [comment]
Close! For `ALWAYSNEW`, it wouldn't be a save point or anything like that. It would just do what it does today where it creates a new transaction, ignoring whatever might already be in async local storage. Does that make sense?

Today any time you use Sequelize's automatic transaction handling, it overwrites what's in CLS: https://github.com/sequelize/sequelize/blob/ad5c0cd8fb58ace977b0810e91243292e0c2e227/src/transaction.ts#L157

**Comment by ephys** [comment]
Aah, that's surprising to me because I expected `sequelize.transaction` to have the same behavior when it comes to ALS as other methods that can accept transactions. I thought the default behavior for nesting transactions with ALS was to create a new savepoint unless `transaction` was set explicitly to null

I think that's something we should change too

Here's how I'd design the 4 possible behaviors (with and without ALS):

## 1. SavePoints

With ALS:

```ts
sequelize.transaction(() => {
  // it's the default behavior for ALS because transactions are automatically retrieved unless set explicitly to null (or to another transaction object)
  sequelize.transaction(() => {
    // this callback is running in the same transaction but a savepoint was created
  });
});
```

Without ALS:

```ts
sequelize.transaction(transaction => {
  sequelize.transaction({ transaction }, () => {
    // this callback is running in the same transaction but a savepoint was created
  });
});
```

## 2. Always new transaction

With ALS:

```ts
sequelize.transaction(() => {
  // with transaction set explicitly to null, the existing one won't be retrieved from ALS, and a new one will be created
  sequelize.transaction({ transaction: null }, () => {
    // this callback is running in a new, separate, transaction
  });
});
```

Without ALS:

```ts
sequelize.transaction(transaction => {
  sequelize.transaction(() => {
    // this callback is running in a new, separate, transaction
  });
});
```

## 3. Create a new transaction if one doesn't already exist, use the existing one otherwise

With ALS:

```ts
sequelize.transaction(() => {
  sequelize.transaction({ nestMode: 'reuse' }, () => {
    // this callback is running in a new, separate, transaction
  });
});
```

Without ALS:

```ts
sequelize.transaction(transaction => {
  // it can be useful without ALS too, because 
  sequelize.transaction({ transaction, nestMode: 'reuse' }, () => {
    // this callback is running in a new, separate, transaction
  });
});
```

## 4. Remove the transaction in the current block

This option only makes sense for ALS, so I'd propose to use a new function for it:

```ts
sequelize.transaction(transaction => {
  sequelize.withAlsTransaction(null, () => {
    // ALS transaction is set to null in this block
    // this function could be aliased to withoutAlsTransaction
  });

  sequelize.withAlsTransaction(transaction, () => {
    // Could also be used to switch to another transaction inside of this block, or to restore it when nested inside withAlsTransaction(null)
  });
});
```

**Comment by benasher44** [comment]
Overall, I think we're on the same page! From your description, It looks like nestMode would have a default, which would be to create save points inside a transaction, if one exists, which is fine (personally not what I would expect but the design decision is understandable — maybe copies other ORMs?). From there, you can override the nestMode. A few questions/feedback:

1. Would it be possible to set the default nestMode as configuration?
2. You might consider continuing to use the CLS name. I think [continuation](https://en.wikipedia.org/wiki/Continuation) local storage is the more general term, whereas ALS is the most modern implementation of it in node. Additionally, ALS is the name of a well-known (at least it's the acronym use in English, or at least American English?) disease 😬

Otherwise, looks good — thanks!

**Comment by ephys** [comment]
> personally not what I would expect but the design decision is understandable — maybe copies other ORMs?

It's because it's the current behavior when you pass a transaction to `sequelize.query`. I'm not opposed to changing the default but I need time to test the two options to figure out which one would be the better default

> Would it be possible to set the default nestMode as configuration?

Yes!

> You might consider continuing to use the CLS name.

Those are good points. We already renamed it to ALS in the code but I don't mind changing it back, we haven't released that alpha yet :)

**Comment by benasher44** [comment]
🙌 thanks!

**Comment by ephys** [comment]
I just discovered in https://github.com/sequelize/sequelize/pull/15559 that some dialects don't support savepoints. That's a strong argument in favor of having `nestMode: 'reuse'` be the default
