### ISSUE TITLE
Thoughts on moving docs to docusaurus?

### ISSUE THREAD

**Issue by mmahalwy** [sequelize/sequelize#13769]
I figured it's becoming a standard tool for libraries. Thoughts on converting the docs to this?

Happy to take lead and convert the existing docs to docusaurus if you think it's valuable.

**Comment by mmahalwy** [comment]
Could be a nice addition for v7 too!

**Comment by WikiRik** [comment]
I have never used it, but if it's really becoming more standard it might be good. Especially if it works well with the generation of the TypeScript things. @AllAwesome497 you might have more to say on this

**Comment by ephys** [comment]
We're encountering issues with `esdocs` in PR https://github.com/sequelize/sequelize/pull/13815

I've been researching alternatives, given `esdocs` hasn't been updated in 4 years, and I think `docusaurus` + `docusaurus-plugin-typedoc` could be a nice solution.

**Comment by ephys** [comment]
Did a small test and it works well enough. Still needs polish:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/1280915/148536734-3987438b-d3d3-4361-bdf3-a89561ea2579.png">

**Comment by mmahalwy** [comment]
thanks for making this happen @ephys !

**Comment by ephys** [comment]
My pleasure 💜. I also want to thank @sdepold and @WikiRik for all the work they put into the new website

I'm really liking docusaurus too. It's going to allow for so many improvements to our documentation

**Comment by Bishwodahal** [comment]
I feel like fonts are too big than normal blogs and websites. For reference, [mozilla](https://developer.mozilla.org) has perfect font for viewing. Adding to it, icons also feels too big.
