### ISSUE TITLE
Remove getterMethods and setterMethods

### ISSUE THREAD

**Issue by WikiRik** [sequelize/sequelize#13765]
As per https://sequelize.org/docs/v6/core-concepts/getters-setters-virtuals/#deprecated-in-sequelize-v7-gettermethods-and-settermethods getterMethods and setterMethods are deprecated in favor of using virtual attributes and should be removed in the next major release (v7)

**Comment by ephys** [comment]
Honestly, I wonder if it's not `DataTypes.VIRTUAL` that should be deprecated.
In the past few months I've seen many users have issues with these, I'll try to sum these up:

- People assume `DataTypes.VIRTUAL` are [`GENERATED VIRTUAL`](https://www.postgresql.org/docs/current/ddl-generated-columns.html) columns, and are surprised when no such column is added to the database.
- People are surprised `DataTypes.VIRTUAL` attributes are not present in `dataValues` / `previousDataValues`
- People go for the native getter & setters on classes, before even considering `DataTypes.VIRTUAL`, when creating their model classes. `getterMethods` & `setterMethods` is the equivalent approach for non-class based model definitions (`sequelize.define`).

The documentation doesn't explain what differences there are between `DataTypes.VIRTUAL` and `getterMethods`/`setterMethods` but I think we should enhance the later to bridge the gap, and deprecate `DataTypes.VIRTUAL`.

**Comment by ephys** [comment]
This was done in https://github.com/sequelize/sequelize/pull/15431
