### ISSUE TITLE
TS: consider migrating away from `.init` for model definition

### ISSUE THREAD

**Issue by mmahalwy** [sequelize/sequelize#13770]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description
One problem that I find with model definition and Typescript is there are 2 places to define _what a column is_. It's defined firstly within interfaces and classes:
```ts
interface UserAttributes {
  id: number;
  name: string;
  preferredName: string | null;
}

// Some attributes are optional in `User.build` and `User.create` calls
interface UserCreationAttributes extends Optional<UserAttributes, "id"> {}

class User extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes {
  public id!: number; // Note that the `null assertion` `!` is required in strict mode.
  public name!: string;
  public preferredName!: string | null; // for nullable fields
...
```

Then again with `.init`:
```ts
User.init(
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: new DataTypes.STRING(128),
      allowNull: false,
    },
    preferredName: {
      type: new DataTypes.STRING(128),
      allowNull: true,
    },
  },
  {
    tableName: "users",
    sequelize, // passing the `sequelize` instance is required
  }
);
```

The problem is that there can easily be a mismatch between the two. For example, the `name` column can be `type: new DataTypes.JSON` but the Typescript interface still has `name: string`. This is of course a simple example but there are many opportunities for mismatch in column type and the Typescript typing. 

Ideally, the definition happens in one place. 

One idea is to kill `init` completely (this is a huge idea and a breaking change, so bare with me). Sequelize borrows quite a bit from Active Record, and AR does not have column definition on the models. Instead, it's read during runtime/start time. We can't infer the types on runtime of course, but we can introspect the DB and build files that would represent the `init` file, and other Typescript types. 

Additions, changes or removals of tables and columns would be done via migration, not via model file change + migrations. 

### Is your feature request related to a problem? Please describe.
Yes. Having mismatch of column types.

### Describe the solution you'd like
Some ideas:

1. Have `init` return the typescript types:

```ts
class BaseUser extends Model {}

const User = BaseUser.init((s) => ({
  // Model attributes are defined here
  firstName: s.field({
    type: DataTypes.STRING,
    allowNull: false
  }),
  lastName: s.field({
    type: DataTypes.STRING
    // allowNull defaults to true
  })
}), {
  // Other model options go here
  sequelize, // We need to pass the connection instance
  modelName: 'User' // We need to choose the model name
});

// User model is a class with fields attached
```
2. Auto generate the interfaces for the model or class from `define` method. A developer would run a command where sequelize would introspect the models and generate the typescript types and classes. Those classes become the working models, not what is `define`d. This is, in a way, similar to what Prisma does with generating all the typescript types that get used. 

### Why should this be in Sequelize
Greatly improve type-safety and the DX of using Sequelize in a typescript world. 

### Describe alternatives/workarounds you've considered
Stitching another tool such as [sql-ts](https://www.npmjs.com/package/@rmp135/sql-ts) for interfaces. This still doesn't keep them in sync. 

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Have you considered the decorator approach, like with https://www.npmjs.com/package/sequelize-typescript?

**Comment by mmahalwy** [comment]
@ephys we have. Few things there:
1. the library is not getting much development. See the commit history
2. Avoiding decorators at all cost right now
3. Still won't solve the mismatch on column types. Yes, `@Column` on a string will be varchar, but won't be the case for others.

**Comment by ephys** [comment]
A decorator implementation with emitDecoratorMetadata could in theory warn you if you have a mismatch between the DataType & the typing.

I'd personally like to see a decorator implementation natively in sequelize. But part of a separate package until native decorators are actually stage 4

**Comment by ephys** [comment]
More on this: it's unlikely that Model.init is going away, however Sequelize.define is going to stay too. If you want to improve the output typing of Sequelize.define to implement what you have in mind, feel free to open a PR :)

**Comment by mmahalwy** [comment]
yeah @ephys i figured, because itd be a breaking change, but i do think that's the biggest limitation to Sequelize becoming fully typed. I know Sequelize borrows a lot of inspiration from Rails/ActiveRecord, and as the Ruby world embraces typing, we will see gems like this become first class: https://github.com/chanzuckerberg/sorbet-rails. Generating the types and methods from the db schema instead of explicitly as we have it with sequelize. That's why I think joist-ts is onto something: https://github.com/stephenh/joist-ts
