### ISSUE TITLE
Add `Sequelize.attr`

### ISSUE THREAD

**Issue by ephys** [sequelize/sequelize#13773]
I've completely dropped the previous RFC. See edits if you're interested in its history.

Here is the new draft:

## `Sequelize.attr`

Like `Sequelize.col` but where `Sequelize.col` is used to reference a column name, `Sequelize.attr` is used to reference an attribute name.

Because sometimes you need to be able to reference another attribute, and having to specify that other attribute's column name instead is inconsistent as column names are abstracted away almost everywhere else.

```typescript
// instead of having to write
User.findOne({
  where: {
    birthDate: { [Op.gt]: Sequelize.col('register_date') },
  },
})

// you'd write

User.findOne({
  where: {
    birthDate: { [Op.gt]: Sequelize.attr('registerDate') },
  },
})
```

`Sequelize.attr` would follow the same syntax as plain attribute references. Meaning it would support:

- `Sequelize.attr('$association.value$')`
- `Sequelize.attr('json.path')`

**Comment by ephys** [comment]
> I fear most users don't know there is a difference between the columns & attributes.

Thinking about this more I think that's actually an argument for using `.attr` instead of `.col`. Would help devs understand the difference between the two.

So the methods would be:

- `Sequelize.rawCol(col)` or `Sequelize.col(col)`
- `Sequelize.attr(Model, attr)
- `Model.attr(attr)`

**Comment by fncolon** [comment]
> > I fear most users don't know there is a difference between the columns & attributes.
> 
> Thinking about this more I think that's actually an argument for using `.attr` instead of `.col`. Would help devs understand the difference between the two.
> 
> So the methods would be:
> 
> * `Sequelize.rawCol(col)` or `Sequelize.col(col)`
> * `Sequelize.attr(Model, attr)`
> * `Model.attr(attr)`
> 
> If we go with `.col` instead of `.rawCol`, I can add this to v6 instead of v7

```
We add attributes to entities; we add columns to tables.
```

IMHO, I prefer using `col` instead of `attr`

**Comment by ephys** [comment]
> We add attributes to entities; we add columns to tables.

Yep!

> IMHO, I prefer using col instead of attr

I find it inconsistent that half of my query is using the attribute name and the other half is using the column name. But being able to use the column name is important too so I'm not planning on removing `col` either :)

**Comment by fncolon** [comment]
> > We add attributes to entities; we add columns to tables.
> 
> Yep!
> 
> > IMHO, I prefer using col instead of attr
> 
> I find it inconsistent that half of my query is using the attribute name and the other half is using the column name. But being able to use the column name is important too so I'm not planning on removing `col` either. But I'll take it as a vote against renaming `col` to `rawCol` & limit the rfc to just adding `attr` :)

If it's only an additional, i would say ok!

**Comment by ephys** [comment]
So yes let's just go for the addition or .attr to avoid needlessly introducing breaking changes :)
