### ISSUE TITLE
createdAt stiil return camelCase sequelize v6.11

### ISSUE THREAD

**Issue by zainiazhr14** [sequelize/sequelize#13784]
I have a project that uses Sequelize as ORM. I need the attribute names returned in snake_case, but although I've specified underscored: true in my model definition, the attributes are returned in camelCase instead. (The DB tables are in snake_case, as expected).

**Comment by Bishwodahal** [comment]
Couldn't exactly understand your question. This one could help you find solution
Note that in both cases the fields are still camelCase in the JavaScript side; this option only changes how these fields are mapped to the database itself. The field option of every attribute is set to their snake_case version, but the attribute itself remains camelCase.
https://sequelize.org/master/manual/naming-strategies.html
If possible include more information about topic

**Comment by ephys** [comment]
`underscored: true` impacts the column name, if you want to change the `attribute` name, use the `createdAt`, `updatedAt`, & `deletedAt` options:

```typescript
MyModel.init(attributes, {
   // make 'created_at', 'updated_at' & 'deleted_at' columns snake_case
  underscored: true,
  // rename the attributes (the JS values) to snake_case
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  deletedAt: 'deleted_at',
});
```

**Comment by zainiazhr14** [comment]
It Work Thank You Very Much
