### ISSUE TITLE
include.attributes.map is not a function

### ISSUE THREAD

**Issue by uptycs-rajesh** [sequelize/sequelize#13781]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

      await db.sequelize.query(sql, {
        model: Model,
        attributes: { exclude: ['attribute1'] }
      });

### What do you expect to happen?

Expect Model to accept the exclude attributes

### What is actually happening?
Throwing error  options.attributes.map is not a function

```
 options.attributes.map is not a function
```

### Environment

- Sequelize version: 6.6.5
- Node.js version: 12.22.6

### How does this problem relate to dialects?

- [x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
I don't think `query` supports an `attributes` option, and if it did, it's likely going to be an array of attributes to include and not going to support `exclude`

**Comment by ephys** [comment]
Confirmed that `Sequelize#query` does not support an `attributes` options. Options are passed as-is to Dialect#Query which is the reason why using `attributes` causes a crash.

Solution is to simply not pass `attributes` to `Sequelize#query`. 
This option doesn't really make sense in `query` as you're already writing the SQL yourself. What was your reason for using it?
