### ISSUE TITLE
Error Connecting to Amazon RDS over SSL

### ISSUE THREAD

**Issue by ghost** [sequelize/sequelize#1380]
I'm getting the following error connecting to Amazon RDS over SSL

ER_ACCESS_DENIED_ERROR: Access denied for user 'xxx'@'xxx.255.51.194' (using password: YES)

How do I use SSL ? Can I set it as {ssl:'Amazon RDS'} like below or do I need to explicitly set the .pem ?

var sequelize = new Sequelize('mydb', 'foo', 'pwd', {
host: 'mydb.xxxxx.us-west-2.rds.amazonaws.com',
port: 3306,
ssl:'Amazon RDS'});

Accessing RDS from the terminal works fine ...

mysql -h mydb.xxxxx.us-west-2.rds.amazonaws.com --ssl_ca=/Users/ciaranbyrne/Dropbox/ActionFinish/mysql-ssl-ca-cert.pem -P 3306 -u foo -p

**Comment by shubhamagarwal90** [comment]
Hello

I am trying to connect to mysql database in Amazon RDS with Node, and its failing mentioning the reason as 
"{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal:true"}"

The code I have written is

var con = mysql_db.createConnection({
	database: 'OCOC',
        hostname: 'ococ.xxxxxxxx.ap-southeast-1.rds.amazonaws.com:3306',
        //port: '3306',
        username: 'xxxxxx',
        password: 'xxxxxxx',
        dialectOptions: {ssl:'Amazon RDS'}        
	});

	con.connect(function(err) {
        if (err ) {
        	console.log(JSON.stringify(err));        }
        else {
        	console.log('Connection established');
        }
});

Directly giving ssl was not working, so after reading your post I added dialectOptions, but the issue still not resolved. Even if I remove the ssl command still it fails.

Hope you might give me some insight as I am stuck with it for 2 days now.  Also without adding ssl it is getting connected from cmd.

**Comment by felixfbecker** [comment]
@shubhamagarwal90 That isn't Sequelize code

**Comment by gustaflindqvist** [comment]
Is it still a dead-end to try getting Sequelize.js to work with Amazon RDS?

**Comment by wexoni** [comment]
What do we put in this setting:

```
 dialectOptions: {
    ssl:'Amazon RDS'
},
```
Just an Amazon RDS? Or Certificate?

**Comment by hitautodestruct** [comment]
@wexoni Just this will do:
```
 dialectOptions: {
    ssl:'Amazon RDS'
},
```
