### ISSUE TITLE
Expand on ValidationErrorItem

### ISSUE THREAD

**Issue by PythonCoderAS** [sequelize/sequelize#13812]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

The documentation specifies that a `ValidationError` contains one or more `ValidationErrorItem`s, but does not mention the attributes of a `ValidationErrorItem`.

### If possible: Provide some suggestion on how we can enhance the docs

Mention possible attributes that can be found.

### Additional context

N/A

**Comment by fzn0x** [comment]
Should be fixed on https://github.com/sequelize/sequelize/pull/14002 :)
