### ISSUE TITLE
Sequelize v6.12.0+ is throwing an Error when using a moment.js object in date fields

### ISSUE THREAD

**Issue by cmelendez** [sequelize/sequelize#13816]
## Bug Description

Sequelize is throwing an `Invalid value` error when using a `moment.js` object in `DATETIME` fields to do date comparisons. Additionally, when using a Moment object to set a date, the date value is set to `0000-00-00 00:00:00`

This is happening since v6.12.0.

```js
  User.findAll({
    where: {
      birthday: {
       [Op.gte]: moment()
      }
   }
  });
```

### What do you expect to happen?

Moment objects should be accepted for date comparison, creation, etc. as usual.

### What is actually happening?

An `Invalid value` error is thrown, crashing the app.

```
Invalid value Moment<2021-12-21T19:52:23+00:00>
```

### Additional context

* Using `mysql` as dialect
* Could be related to #13712 

### Environment

- Sequelize version: 6.12.0
- Node.js version: 16.13.0

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time, although I believe I could do it if I had the time...

**Comment by fncolon** [comment]
Hello, just adjust and created the fix in #13818, thanks for the issue.

**Comment by sdepold** [comment]
Could you please give it a try and see if it a try for you?

**Comment by cmelendez** [comment]
Hi @sdepold, thanks for the fix but shouldn’t this change be included in v6 instead of v7? It’s a breaking bug/change that will affect anyone upgrading a minor version that’s using momentjs (my guess is it could be a significant number).
Just keep in mind that this bug can also silenty set dates to 0000-00-00 without throwing an error (the error is thrown only when selecting/searching).

Thanks.

**Comment by sdepold** [comment]
Correct. There is also a new v6 bugfix version.

**Comment by cmelendez** [comment]
A bit late but just confirming that the fix is working properly. We are using v6.13.0.

Thanks a lot!

**Comment by yogithesymbian** [comment]
now 2022 .
```
sevenDaysAgoNew7 days ago:  Moment<2022-10-16T17:58:12+08:00>
Error: Invalid value Moment<2022-10-16T00:00:00+08:00>
```

**Comment by yogithesymbian** [comment]
```
"sequelize": "^6.6.5",
    "sequelize-cli": "^6.2.0",
"moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
```
here is my code
```
console.log('7 days ago: ', sevenDaysAgo) // would print Moment<2022-10-16T00:00:00+08:00>

          clock_in_time: {
            [Op.gte]: sevenDaysAgo // doesnt work
            // [Op.gte]: '2022-10-16T00:00:00+08:00' // work
          }
```

**Comment by yogithesymbian** [comment]
ah solved here https://stackoverflow.com/a/46390179/8122500 toDate()
