### ISSUE TITLE
Sequelize splits when using nested/raw = true.

### ISSUE THREAD

**Issue by faiwiz** [sequelize/sequelize#13829]
Hello, I am using raw:true, nested:true for following conditions which breaks into multiple records without nested/raw it's works, here is an example...

			userModel.findAll({
				nested:true,
				raw:true,
				includes:[ordersModel]
			});

			Result
			{
				users:{
					{		
						user_id:1,
						orders:{
							{
								order_id:1
								...,
							},
						}
					},
					{		
						user_id:1,
						orders:{
							{
								order_id:2
								...,
							},
						}
					},
				},
			}

			using without nested/raw

			userModel.findAll({
				includes:[ordersModel]
			});

			Result
			{
				users:{
					{		
						user_id:1,
						...
						orders:{
							{
								order_id:1
								...,
							},
							
							{
								order_id:2
								...,
							},
						}
					},
				},
			}

**Comment by faiwiz** [comment]
@github-action please remove stale label.

**Comment by WikiRik** [comment]
Hi! Can you update the issue with the bug report template so we have more information to help you? You can find the template here; https://github.com/sequelize/sequelize/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by ephys** [comment]
Specifically it's crucial that you include a [SSCCE](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#opening-an-issue-to-report-a-bug) that replicates your issue
