### ISSUE TITLE
Comparisons against UUIDs in postgres

### ISSUE THREAD

**Issue by themobiusproject** [sequelize/sequelize#13828]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**[Here](https://github.com/themobiusproject/sequelize-sscce) is the link to the SSCCE for this issue:** 

### What do you expect to happen?

```
SELECT count(*) AS "count" FROM "Foos" AS "Foo" WHERE "Foo"."uuid"::text LIKE '573b77ae%';
```

### What is actually happening?

```
SELECT count(*) AS "count" FROM "Foos" AS "Foo" WHERE "Foo"."uuid" LIKE '573b77ae%';
```

### Environment

- Sequelize version: sequelize@6.12.2
- Node.js version: v14.17.6
- If TypeScript related: TypeScript version: n/a

### How does this problem relate to dialects?

- [x] I think this problem happens only for the following dialect(s): Postgres

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by ephys** [comment]
I suppose we could cast this automatically :)

In the meantime you can cast it manually:

```typescript
await Foo.count({ 
  where: Sequelize.where(
    Sequelize.cast('uuid', 'text')
    Op.iLike,
    '573b77ae%'
  ),
})
```

let me know if it worked.

**Comment by ephys** [comment]
Following https://github.com/sequelize/sequelize/pull/15598, the cast syntax available on JSON paths will be available everywhere, so you can do this:

```ts
await Foo.count({ 
  where: {
    'uuid::text': {
      [Op.iLike]: '573b77ae%'
    },
  },
});
```
