### ISSUE TITLE
use SUM function int value is converted to string

### ISSUE THREAD

**Issue by ShawnZhangxxx** [sequelize/sequelize#13830]
Question : my table live_statistic   column  duration_time is int type  , but convert to string type  when using SUM(duration_time) 

My code:
;(async () => {
            let queryStr = `SELECT jj_uid  , SUM(duration_time) as total_time  FROM live_statistics WHERE start_time >= '2021-12-01 00:00:00' AND start_time < '2021-12-02 00:00:00'  GROUP BY jj_uid ` ;
            let paramArr = [];
            // paramArr.push("2021-12-02 00:00:00");
            // paramArr.push("2021-12-03 00:00:00");
            let rst1 = await sequelizeTest.query(queryStr, {
                    replacements: paramArr,
                    raw: true,
                    type: sequelize.QueryTypes.SELECT,
                }
            );
            console.log(rst1);
        })();

Result:
[
  {
    "jj_uid": 604898305,
    "total_time": "100"    // ### is String type ????
  },
  {
    "jj_uid": 604898306,
    "total_time": "986"
  },
  {
    "jj_uid": 604898314,
    "total_time": "31582"
  },
  {
    "jj_uid": 604898317,
    "total_time": "69960"
  }
]

**Comment by WikiRik** [comment]
Is this the same as https://github.com/sequelize/sequelize/issues/10533 ?

**Comment by ephys** [comment]
Closing in favor of https://github.com/sequelize/sequelize/issues/10533 then :)
