### ISSUE TITLE
how to use Promise.all?

### ISSUE THREAD

**Issue by dpolyakov** [sequelize/sequelize#1384]
Hello.
I want to use promises for making models associations 

```
User.hasMany(Group)
Group.hasMany(User)

User
  .sync({ force: true })
  .then(function() { return User.create({ username: 'John' }) })
  .then(function(john) { return Group.findOrCreate({id: 1}) })
  .then(function(group) {return group.setUsers([john])})
  .then(function(result) { console.log(result)})
})
```

maybe code should be something like this:

```
User
  .sync({ force: true })
  .then(function() {
    var user =  User.create({ username: 'John' })
    var group = Group.findOrCreate({id: 1});
    return Promise.all([group, user]);
  })
  .spread(function(group, users) {return group.setUsers(user)})
  .then(function(result) { console.log(result)})
})
```

but i don't understand which object should have promise-method .all.
Can you help me?

**Comment by atlantageek** [comment]
According to the API document for Sequelize it looks like Promise is already built into the API.
http://sequelize.readthedocs.org/en/latest/api/sequelize/#promise

But how do I reference this promise object.
all the other objects in the API documentation look like its part of the sequelize object.

Can someone give me example got of how to get a reference to the Promise class

**Comment by mickhansen** [comment]
@atlantageek You can access it through `Sequelize.Promise`, but generally you probably just want to use your own promise library.
