### ISSUE TITLE
Eager loading: select all rows without association in mn-table

### ISSUE THREAD

**Issue by nichdiekuh** [sequelize/sequelize#1385]
Again, the eager loading is bugging me and I can't figure how to achieve a select which selects all rows from given table, which do NOT join on a second model.

In pure SQL, I'd write my query like this:

``` sql

SELECT column1 from Parameters LEFT OUTER JOIN ParameterProjects ON (Project.id = ParameterProjects.parameter_id) WHERE ParameterProjects.parameter_id IS NULL;
```

It's usually a quite trivial task to fetch all rows which are not (yet) linked to table#2 (Projects). In sequelize however I the only way I know to get the mn-table involved is to include the associated model. My first idea was to use Sequelize.or() (which is technically working now, thanks Mick!) and query for `Sequelize.or({project_id: 1},{project_id:null})` , but I didn't pay enough attention at the generated query.

It looks like this:

``` sql
SELECT `Parameters` . * , `Projects`.`id` AS `Projects.id` , `Projects`.`name` AS `Projects.name` , `Projects`.`url` AS `Projects.url` , `Projects`.`api_key` AS `Projects.api_key` , `Projects`.`created_at` AS `Projects.created_at` , `Projects`.`customer_id` AS `Projects.customer_id` , `Projects.ParametersProject`.`project_id` AS `Projects.ParametersProject.project_id` , `Projects.ParametersProject`.`parameter_id` AS `Projects.ParametersProject.parameter_id`
FROM `Parameters`
INNER JOIN `ParametersProjects` AS `Projects.ParametersProject` ON `Parameters`.`id` = `Projects.ParametersProject`.`parameter_id`
INNER JOIN `Projects` AS `Projects` ON `Projects`.`id` = `Projects.ParametersProject`.`project_id`
AND (
`Projects`.`id` = '1'
OR `Projects`.`id` IS NULL
)
WHERE (
`Parameters`.`key` = 'cpu'
)
```

Table Parameters joins ParameterProjects on the Project.id, ParameterProjects joins Projects. Those are INNER JOINS and as far as I understand SQL (please correct if I'm wrong) `Projects.ParametersProject`.`parameter_id` can never be NULL.

Is there perhaps another way to achieve this? 

Oh, and btw: Where are the fancy subselects gone? I could swear the last time I tried to solve my issue the queries had subselects in it.

**Comment by YouriT** [comment]
@nichdiekuh would you mind sharing your code to achieve that?

I'm trying to do a bit the same (without intermediate table) but the result is not as expected:
```js
User
    .findAll({
        attributes: ['id', 'firstName', 'lastName'],
        where: {

        },
        include: [{
            model: Portfolio,
            attributes: ['id', 'name', 'userId'],
            where: {
                userId: null
            },
            required: false
        }]
    })
```
This results in all users with portfolios empty and the associated request is:
```SQL
SELECT "User"."id", "User"."firstName", "User"."lastName", "User"."email", "User"."locale", "portfolios"."id" AS "portfolios.id", "portfolios"."name" AS "portfolios.name", "portfolios"."userId" AS "portfolios.userId" FROM "Users" AS "User" LEFT OUTER JOIN "Portfolios" AS "portfolios" ON "User"."id" = "portfolios"."userId" AND "portfolios"."userId" IS NULL;
```
So obviously this is because the where is added to the join condition which is wrong. So I wanted to do:
```js
User
    .findAll({
        attributes: ['id', 'firstName', 'lastName'],
        where: {
             'portfolios.userId': null
        },
        include: [{
            model: Portfolio,
            attributes: ['id', 'name', 'userId'],
            required: false
        }]
    })
```
But it tries to do: ```WHERE "Users"."portfolios.userId"``` unsuccessful for me...

(I'm using pg adapter)

Thanks for your precious help!

**Comment by YouriT** [comment]
Well I spoke too quickly. I finally figured it out and will share my resulting request:
```js
User
    .findAll({
        attributes: ['id', 'firstName', 'lastName', 'email' ],
        where: Sequelize.where(Sequelize.col('portfolios.userId'), '=', null),
        include: [{
            model: Portfolio,
            required: false
        }]
    })
```
Which results in:
```sql
SELECT "User"."id", "User"."firstName", "User"."lastName", "User"."email", "portfolios"."id" AS "portfolios.id", "portfolios"."name" AS "portfolios.name", "portfolios"."heraclesRef" AS "portfolios.heraclesRef", "portfolios"."creationData" AS "portfolios.creationData", "portfolios"."deleted" AS "portfolios.deleted", "portfolios"."createdAt" AS "portfolios.createdAt", "portfolios"."updatedAt" AS "portfolios.updatedAt", "portfolios"."userId" AS "portfolios.userId" FROM "Users" AS "User" LEFT OUTER JOIN "Portfolios" AS "portfolios" ON "User"."id" = "portfolios"."userId" WHERE "portfolios"."userId" IS NULL;
```

So the solution was to use ```Sequelize.where``` and ```Sequelize.col``` to avoid ```"Users"``` prepention. If you need multiple wheres just enclose ```Sequelize.where(...)``` in a ```Sequelize.and(Sequelize.where(...))``` and it will do the job :)

**Comment by janmeier** [comment]
@YouriT You should be able to use  `where: {  '$portfolios.userId$': null },` to avoid prepending the parent name as well

**Comment by YouriT** [comment]
@janmeier unfortunately this gives me an error: ```SequelizeDatabaseError: column User.$portfolios.userId$ does not exist```

**Comment by janmeier** [comment]
I believe it was added around 3.12

**Comment by YouriT** [comment]
That must be the why then, I'm currently on 3.11 thanks for the note nevertheless @janmeier :)

**Comment by aryeharmon** [comment]
How do i do this in version 4?

**Comment by kukukk** [comment]
I'm also interested how can this be solved in version 4. Using required:false returns all rows (with and without having association).

**Comment by jgburet** [comment]
On v4, this answer works well https://github.com/sequelize/sequelize/issues/1385#issuecomment-157389824

```js
User
    .findAll({
        attributes: ['id', 'firstName', 'lastName', 'email' ],
        where:{ '$portfolios.userId$': null },
        include: [{
            model: Portfolio,
            required: false
        }]
    })
```

It retrieves only the users that have no portfolios.

**Comment by mrenigman** [comment]
How can this be solved in version 6?
