### ISSUE TITLE
Documentation links broke

### ISSUE THREAD

**Issue by ephys** [sequelize/sequelize#13864]
### What was unclear/insufficient/not covered in the documentation

Documentation links from search engines (and likely more) broke after the main branch rename.

Eg. https://sequelize.org/master/manual/model-basics.html

I'm not sure if that's the case but given main is V7, it's possible that https://sequelize.org/main/manual/model-basics.html is displaying the V7 version of the documentation.

### If possible: Provide some suggestion on how we can enhance the docs

- Add a redirect from `master` to /v6 ?
- ensure main branch is published as /v7 ? (Maybe by dropping the `main` branch altogether and renaming it to v7 in this repo)
- Add a version switcher in the header to be more explicit regarding which version of the docs the user is on

**Comment by fncolon** [comment]
If we access it through https://sequelize.org/master/ it will redirect you to the `main` branch

I'm go with: adds a redirect from `/master` to `/main`

**Comment by fncolon** [comment]
The problem here is https://sequelize.org/master/manual/model-basics.html we don't get redirected in the `/master` URL  subpath

**Comment by sdepold** [comment]
Should be back in a moment. I have now removed any hint on a master or main branch from the docs and only stated that we have v7 as the latest version. it will however build a main and master directory secretly based on the main branch and hence links from google or whatever should hopefully still work

**Comment by sdepold** [comment]
the version picker in the header would be nice indeed. I can have a look into that, too. It's depending on the v5/v6/v7 branches however, so I'll have to push a change to those branches

**Comment by sdepold** [comment]
Seems to work now

**Comment by ephys** [comment]
Yep, it's back. Thanks :) I'll keep it open for now to see about adding a version switch

**Comment by sdepold** [comment]
Version picker has landed.
