### ISSUE TITLE
Date properties in result of .toJSON() stay as a Date instance, but not string

### ISSUE THREAD

**Issue by mytharcher** [sequelize/sequelize#13882]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

The code of [line 4457](https://github.com/sequelize/sequelize/blob/main/lib/model.js#L4457) in `model.js` is using `_.cloneDeep`. And the `Date` type will not be convertet to string as it should be in JSON format (in which `Date` is not the type supported).

Since the API is `.toJSON()`, and also the document says it will return JSON, but the `Date` properties in result will stay as JavaScript object, which are not compatible with JSON.

### SSCCE

```js
// You can delete this code block if you have included a link to your SSCCE above!
const { createSequelizeInstance } = require("./dev/sscce-helpers");
const { Model, DataTypes } = require(".");

const sequelize = createSequelizeInstance({ benchmark: true });

class User extends Model {}
User.init(
  {
    username: DataTypes.STRING,
    birthday: DataTypes.DATE,
  },
  { sequelize, modelName: "user" }
);

(async () => {
  await sequelize.sync({ force: true });

  const jane = await User.create({
    username: "janedoe",
    birthday: new Date(1980, 6, 20),
  });

  const json = jane.toJSON();

  console.log('\nJane:', json);

  await sequelize.close();

  expect(typeof json.birthday).to.equal('string');
})();
```

### What do you expect to happen?

The `birthday` property of `jane.toJSON()` should be type of `string`.

### What is actually happening?

The `birthday` is an instance of `Date`.

```shell
$ node sscce.js 

Executed (default): DROP TABLE IF EXISTS "users" CASCADE; Elapsed time: 1ms
Executed (default): DROP TABLE IF EXISTS "users" CASCADE; Elapsed time: 0ms
Executed (default): CREATE TABLE IF NOT EXISTS "users" ("id"   SERIAL , "username" VARCHAR(255), "birthday" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id")); Elapsed time: 31ms
Executed (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname; Elapsed time: 7ms
Executed (default): INSERT INTO "users" ("id","username","birthday","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING "id","username","birthday","createdAt","updatedAt"; "janedoe", "1980-07-19 16:00:00.000 +00:00", "2022-01-02 17:23:21.675 +00:00", "2022-01-02 17:23:21.675 +00:00" Elapsed time: 1ms

Jane: {
  id: 1,
  username: 'janedoe',
  birthday: 1980-07-19T16:00:00.000Z,
  updatedAt: 2022-01-02T17:23:21.675Z,
  createdAt: 2022-01-02T17:23:21.675Z
}
An unhandled rejection occurred:
An unhandled exception occurred:

/Users/**/opensource/sequelize/test/support.js:24
  throw e;
  ^
AssertionError: expected 'object' to equal 'string'
    at Proxy.assertEqual (/Users/**/opensource/sequelize/node_modules/chai/lib/chai/core/assertions.js:1038:12)
    at Proxy.methodWrapper (/Users/**/opensource/sequelize/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at doAsserterAsyncAndAddThen (/Users/**/opensource/sequelize/node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
    at Proxy.<anonymous> (/Users/**/opensource/sequelize/node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)
    at Proxy.overwritingMethodWrapper (/Users/**/opensource/sequelize/node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)
    at /Users/**/opensource/sequelize/sscce.js:32:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  showDiff: true,
  actual: 'object',
  expected: 'string',
  operator: 'strictEqual'
}
```

### Environment

- Sequelize version: 0.0.0-development (1e2b771c)
- Node.js version: v14.16.1

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
This works as expected. `toJSON` isn't designed to be called by anything else than `JSON.stringify`. It's perfectly normal for `toJSON` to return something that's not one of the primitives JSON supports. `Date` has a toJSON method. `JSON.stringify(jane)` will produce the proper output.

**Comment by mytharcher** [comment]
Thanks for your explanation. But the name of this API still makes confusion (at least for me). Could its name be considered to have a change to `toJS()` (like in MobX)? Personally I think it will match the intention of design. And the `toJSON()` API could be provided for converting to primitives JSON object.

**Comment by ephys** [comment]
`Model#toJSON` has been implemented to support `JSON.stringify()`, as such it can't be renamed because it's a [standard function name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior).

`Model#toJS` already exists as `Model#get` (returns all attributes)

**Comment by ephys** [comment]
Considering resolved. Let us know if we should reopen.

**Comment by JSteunou** [comment]
A bit late, but I suffer the same issue. Nowadays with validators, parser, typing, etc. it is very common to be more careful than we were and even if having a true Date object, which can be JSON.stringified, its type is not string. It would still work, because indeed, when creating a final response object with a JSON body, Date.toJSON will be called somewhere.

But the name `toJSON` apply returning a JSON and not *a JS object that can be easily convert to JSON*. I was also expected a string and not a Date. This make it not easy with modern practice.

**Comment by yisibl** [comment]
The new code is here:
https://github.com/sequelize/sequelize/blob/bc35a52af967dd49bbc5969450d4d80ad2926d84/packages/core/src/model.js#L4190-L4196
