### ISSUE TITLE
queryInterface.removeConstraint() not removing table constraint

### ISSUE THREAD

**Issue by uzair004** [sequelize/sequelize#13893]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

```js
exports.mochaHooks = {
  beforeAll: async function () {
    // do something before all test once
    console.log("running migrations...");
    await migrate();
  },
  afterAll: async function () {
    // do something after all test once
    console.log("closing server");
    server.close();
  },
  beforeEach: async function () {
    // insert data before each test
    await sqlFixtures.create(dbConfig, userFixture);
    await sqlFixtures.create(dbConfig, userOTPFixture);
    await sqlFixtures.create(dbConfig, itemFixture);
  },
  afterEach: async function () {
    // truncate tables after each test
    
    await sequelize.queryInterface.removeConstraint(
       "ordered_items",
       "CK_unique_order_item"
     );

    await sequelize.truncate({ cascade: true });
  },
};
```

### What do you expect to happen?
```js
await sequelize.queryInterface.removeConstraint(
       "ordered_items",
       "CK_unique_order_item"
     );
``` 
     this line of code should be able to remove constraints from "ordered_items" table with name "CK_unique_order_item"

### What is actually happening?

throwing error: "No constraint found with name "CK_unique_order_item"

```
Error: unknow constraint "CK_unique_order_item"

```

### Additional context

truncating tables is regular practice in test cases, I am trying to achieve truncate tables in mocha Hooks after each test.
while raw SQL query does remove the constraint 
``` js
 sequelize.query(
      "ALTER TABLE ordered_items DROP CONSTRAINT CK_unique_order_item;"
    );
```

### Environment

- Sequelize version: 5.21 
- Node.js version: v14.18.1

### How does this problem relate to dialects?

- [x] I don't know, I was using MYSQL, with connector library version 2.3.3 and database version 8.0

**Comment by uzair004** [comment]
@ephys I have created this issue related to removeConstraint , hope it will clearify what problem I am facing

**Comment by ephys** [comment]
Can you log what query removeConstraint executes?  
Like this:

```typescript
   await sequelize.queryInterface.removeConstraint(
       "ordered_items",
       "CK_unique_order_item",
       { logging: console.log },
     );
```
