### ISSUE TITLE
Default to snake_case for table and column names

### ISSUE THREAD

**Issue by sdepold** [sequelize/sequelize#13896]
Historically, Sequelize has always been using CamelCase for table names and column names. Looking into the industry "standards", it seems that the majority prefer snake_case however making queries easier to read and also allowing to remove quotes in pg for example.

Example:

JS/TS:
```
define('User', {
  homeAddress: DataTypes.STRING
})
```

Database:
```
table name: users

columns:
id
home_address
created_at
updated_at
```

**Comment by ericyd** [comment]
My understanding is that the [`underscored`](https://sequelize.org/v6/class/lib/model.js~Model.html) property is for. When `true`, this property uses snake_case for the database columns and camelCase in the ORM. Since JS convention is camelCase I think this is the preferred method if you want to use snake_case in the DB

**Comment by ephys** [comment]
It is what that property is for, the idea for v7 would be to turn it on by default to follow sql conventions. Could still be turned off if you'd rather have camelCase names in the database.

**Comment by mariusa** [comment]
> Could still be turned off 

Would you please specify how to turn it off? We prefer `camelCase` naming for db columns too. 
Hope it's not per model. If so, `sequelize-auto` should also support this flag when generating models.

**Comment by ephys** [comment]
It's just an API draft but I suppose you'd turn it off the same way you turn it on today: by setting the `underscored` option

```typescript
UserModel.init({}, {
  // disable auto-snake_case
  underscored: false,
})
```

It looks like `underscored` can't be configured globally right now but it shouldn't be too hard to add a way to do it:

```typescript
const sequelize = new Sequelize({
  // disable auto-snake_case for all models (except those that specifically turn it back on)
  underscored: false,
});
```

**Comment by ephys** [comment]
Because not all dialects follow the same conventions, I'll close in favor of https://github.com/sequelize/sequelize/issues/15312 which define how dialects could specify their default naming strategy
