### ISSUE TITLE
Choice of dialect

### ISSUE THREAD

**Issue by sdepold** [sequelize/sequelize#13894]
In v7, we want to have the following way of choosing the dialect to be used:

```
new Sequelize(database, username, password, { dialect: PostgresDialect });
new Sequelize('mysql://localhost:3306/database', { dialect: MysqlDialect });
```

See https://github.com/sequelize/sequelize/pull/13798

**Comment by WikiRik** [comment]
Just as an update; we've rescoped v7 so this will land in v8 or a later release. We still plan on doing this with the splitting of the dialects
