### ISSUE TITLE
Typescript error when passing a ModelOptions argument in Sequelize.define method

### ISSUE THREAD

**Issue by jlmbrt** [sequelize/sequelize#13906]
## Issue Creation Checklist

[ x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

This is my first bug reporting, I hope i do it right !
*(Oh, and sorry for my english, I try to do my best )*

## Bug Description

Bug is related to the definition of the `define` method of the `Sequelize` class :
the `options` argument of type `ModelOptions` is not bind to the generic `M`

Code from the codebase :
```js
// model.d.ts - ModelOptions
export interface ModelOptions<M extends Model = Model> { 
    // ...
}
```
Real code [here](https://github.com/sequelize/sequelize/blob/d57c30c19ff3c42909ab84a9b9a18c682f0923ab/types/lib/model.d.ts#L1396)

```js
// sequelize.d.ts - Sequelize.define
public define<M extends Model, TAttributes = M['_attributes']>(
    modelName: string,
    attributes: ModelAttributes<M, TAttributes>,
    options?: ModelOptions // <-- nothing here !
): ModelCtor<M>;
```

Real code [here](https://github.com/sequelize/sequelize/blob/d57c30c19ff3c42909ab84a9b9a18c682f0923ab/types/lib/sequelize.d.ts#L1187)

### Situation
In my code I have :
- a custom Model : `UserModel extends Model<...>`
- with schema : `schema: ModelAttributes<UserModel, ...>`
-  and an option object : `options: ModelOptions<UserModel>`

But when I want to call `Sequelize.define`i have an error :
```js
interface Attributes {...}
interface UserModel extends Model<Attributes> {}

const schema: ModelAttributes<UserModel, Attributes> = {...}
const options: ModelOptions<UserModel> = {...}

const sequelize: Sequelize = {...}

sequelize.define("user",schema, options)
// Error :
// Argument of type 'ModelOptions<UserModel>' is not assignable to parameter of type 'ModelOptions<Model<any, any>>'.
```

More complete example [here](https://gist.github.com/jlmbrt/747113f1f6c9703af61d6ec463d11ee0)

### What do you expect to happen?

I want to be able to call `Sequelize.define` with and `options` argument which has a custom type `ModelOptions<CustomModel>`

### What is actually happening?

Actually I have a typescript compilation error :
Argument of type 'ModelOptions<CustomModel>' is not assignable to parameter of type 'ModelOptions<Model<any, any>>'.

### Environment

- Sequelize version: 6.12.5
- Node.js version: 17.3.0
- If TypeScript related: TypeScript version: 4.5.4

## Proposition of solution
If I just update the `Sequelize.define` definition it seems to work :
```js
public define<M extends Model, TAttributes = M['_attributes']>(
    modelName: string,
    attributes: ModelAttributes<M, TAttributes>,
    options?: ModelOptions<M> // <-- just had <M> here
): ModelCtor<M>;
```

### How does this problem relate to dialects?

- [ x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ x ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
This does look like an oversight. Seems like you've already figured out the solution. Would you mind sending a PR?

**Comment by jlmbrt** [comment]
Thank you !
I wanted to be sure it was only that and not a bigger problem. I am not (yet) a Sequelize expert ;)

PR is sent

**Comment by ephys** [comment]
I think it's also related to https://github.com/sequelize/sequelize/pull/13890, which hasn't been released on v6 yet
