### ISSUE TITLE
defaultValue: DataTypes.UUIDV4 not honored

### ISSUE THREAD

**Issue by AaronMBMorse** [sequelize/sequelize#13912]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
const { createSequelizeInstance } = require("./dev/sscce-helpers");
const { Model, DataTypes } = require(".");

const sequelize = createSequelizeInstance({ benchmark: true });

class User extends Model {}
User.init(
  {
    username: DataTypes.STRING,
    uuid: {
field: 'uuid',
      primaryKey: true,
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
    }
  },
  { sequelize, modelName: "user" }
);

(async () => {
  await sequelize.sync({ force: true });

  const jane = await User.create({
    username: "janedoe",
    birthday: new Date(1980, 6, 20),
  });

  console.log("\nJane:", jane.toJSON());

  await sequelize.close();
})();
```

### What do you expect to happen?

It should be creating the uuid on the record creation.

### What is actually happening?

It doesn't create a uuid and the field seems to be null. 

_The output was Bar!_

```
Output here
```

### Additional context

Add any other context and details here.

### Environment

I am using Postgres

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ericyd** [comment]
I don't believe this is the intended use of DataTypes. `defaultValue` is supposed to take a function or a value which returns the literal data type you are looking for. [DataTypes.UUIDV4](https://github.com/sequelize/sequelize/blob/287a9a1684b6cd3dfcf7d19fedad4b6be3e626be/lib/data-types.js#L664) is simply a class - it represents the _data type_ of a UUIDV4, not the actual data (e.g. a literal UUID)

You will need to either use a JS lib to generate a UUID, or if you have the `pgcrypto` extension enabled on your database, you could use the `gen_random_uuid()` function as a default value. Examples

Using a JS lib
```js
import { Uuid4 } from 'id128'

class User extends Model {}
User.init(
  {
    uuid: {
      field: 'uuid',
      primaryKey: true,
      type: DataTypes.UUID,
      defaultValue: () => Uuid4.generate().toCanonical(),
    }
  },
 // ...
);
```

or, with pgcrypto

```js
import { fn } from 'sequelize'

class User extends Model {}
User.init(
  {
    uuid: {
      field: 'uuid',
      primaryKey: true,
      type: DataTypes.UUID,
      defaultValue: fn('gen_random_uuid'),
    }
  },
 // ...
);
```

**Comment by ephys** [comment]
They're special types meant to be used as default values :) (see https://sequelize.org/master/manual/model-basics.html#uuids)

Not sure why it's not working. I'll take a look

**Comment by ephys** [comment]
I ran the SSCCE and it worked as expected.
Can you create a SSCCE using https://github.com/papb/sequelize-sscce that replicates your issue?

**Comment by ephys** [comment]
Considering solved, let me know if we should reopen
