### ISSUE TITLE
Sequelize.set mariadb supported too

### ISSUE THREAD

**Issue by Feverqwe** [sequelize/sequelize#13920]
Hi! Please add mariadb here too, thx!

https://github.com/sequelize/sequelize/blob/e161014d8116826a68b0fbdf740b0e21f52b4394/lib/sequelize.js#L669

Now I use it like this:
```js
await this.sequelize.query('set innodb_lock_wait_timeout=120', {
  transaction,
});
```

**Comment by ephys** [comment]
PR welcome :)
