### ISSUE TITLE
Sequelize AND Condition on hasMany association

### ISSUE THREAD

**Issue by razvanwaz** [sequelize/sequelize#13923]
## Issue Creation Checklist

[ #] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

A clear and concise description of what is this issue about.

If applicable, you can add some code. In this case, an SSCCE/MCVE/reprex is much better than just an isolated code snippet.

**I'm using Sequelize and I have 2 models (Article and Tag) associated with belongsToMany through another model called ArticleTags.

I want to fetch all the Articles that have one Tag with id=1 AND one Tag with id=2.

I've tried multiple solutions, but it always fetches the Articles that have one Tag with id=1 OR one Tag with id=2.

This is the code I have as of now:**
```


let articles = await Article.findAll({
limit: limit, 
offset: offset, 
subQuery: false,
where:[ {"$Tags.id$": {1,2} }]

include:{
    model: Tag, 
    required: false
}, 

});

```

### Additional context

Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [# ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ #] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
This looks like a job for a subselect (https://stackoverflow.com/questions/8824561/select-rows-with-multiple-tags-is-there-a-better-way).

You can use `Sequelize.literal` to pass a subselect to `where`.

**Comment by NicoSan20** [comment]
@razvanwaz Do you find a solution ? I'm currently on the same trouble. Any example will be appreciated. Thanks in advance.
