### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by gaurav16694** [sequelize/sequelize#13938]
Hello We are having this issues when using replication
const sequelize = new Sequelize('database', null, null, {
  dialect: 'mysql',
  port: 3306,
  replication: {
    read: [
      { host: '8.8.8.8', username: 'read-1-username', password: process.env.READ_DB_1_PW },
      { host: '9.9.9.9', username: 'read-2-username', password: process.env.READ_DB_2_PW }
    ],
    write: { host: '1.1.1.1', username: 'write-username', password: process.env.WRITE_DB_PW }
  },
  pool: { // If you want to override the options used for the read/write pool you can do so here
    max: 20,
    idle: 30000
  },
})

TypeError: Cannot read property 'destroy' of undefined
    at Object.destroy (/Users/gaurav/asparia/simplifimed-server/node_modules/sequelize/dist/lib/dialects/abstract/connection-manager.js:119:41)
    at Connection.<anonymous> (/Users/gaurav/asparia/simplifimed-server/node_modules/sequelize/dist/lib/dialects/mysql/connection-manager.js:80:23)
    at Connection.emit (events.js:400:28)
    at Connection.emit (domain.js:470:12)
    at Connection._notifyError (/Users/gaurav/asparia/simplifimed-server/node_modules/mysql2/lib/connection.js:212:12)
    at Connection._handleFatalError (/Users/gaurav/asparia/simplifimed-server/node_modules/mysql2/lib/connection.js:151:10)
    at Connection._handleNetworkError (/Users/gaurav/asparia/simplifimed-server/node_modules/mysql2/lib/connection.js:160:10)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)

**Comment by EgorCloud** [comment]
Hi, @gaurav16694. 
Try to set `databaseVersion` in options object

**Comment by gaurav16694** [comment]
Hi @EgorCloud i am not sure where to put databaseVersion as i am gettng this error while compilation
```
api/models/index.ts:44:5 - error TS2345: Argument of type '{ dialect: "mysql"; port: number; databaseVersion: number; replication: { read: { host: string; username: string; password: string; }[]; write: { host: string; username: string; password: string; }; }; pool: { ...; }; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'databaseVersion' does not exist in type 'Options'.

44     databaseVersion: 8,
       ~~~~~~~~~~~~~~~~~~

```

**Comment by EgorCloud** [comment]
Hi, @gaurav16694.
So, I spent a lot of time looking for this.
https://github.com/sequelize/sequelize/blob/v6/lib/dialects/abstract/connection-manager.js#L246

**Comment by EgorCloud** [comment]
```js
const { Sequelize } = require("sequelize");
const sequelize = new Sequelize("database", null, null, {
    port:3306,
    dialect:"mysql",
    databaseVersion: 8, // required field
    replication: {
        read: [{
            host:"8.8.8.8",
            username:"read-1-username",
            password:"read-1-password",

        }],
        write: {
            host:"1.1.1.1",
            username:"write-username",
            password:"write-password",
        },
    },
});
sequelize.authenticate()
```

**Comment by WikiRik** [comment]
I will close this issue in favor of https://github.com/sequelize/sequelize/issues/13537

**Comment by gaurav16694** [comment]
Hello @WikiRik what is the current solution to the problem
we are not able to add databaseVersion during Sequalize initialization?
