### ISSUE TITLE
no method 'set%modelname%' for multiassociations models

### ISSUE THREAD

**Issue by dpolyakov** [sequelize/sequelize#1394]
I have models with these associations:

```
db.Term
    .hasMany(db.Taxonomy, {foreignKey: 'term_id'});

db.Taxonomy
    .belongsTo(db.Term)
    .hasMany(db.Event, {through: 'event_taxonomy'})

db.Event
    .hasMany(db.Taxonomy, {through: 'event_taxonomy'})
```

in my controller i try to add new event, with relationship for taxonomy

```
db.Taxonomy.find(1).success(function(taxonomy) {
    db.Event.create({name: 'test'}).success(function(event) {

        // it works
        taxonomy.addEvent(event).success(function() {})

        // it crush with error "Object [object Object] has no method 'addTaxonomy'""
        event.addTaxonomy(taxonomy).success(function() {})

    })    
})
```

**Comment by Ygilany** [comment]
Can I know how did you print out the accessors for a specific model ?
Thanks
@dpolyakov

**Comment by janmeier** [comment]
@Ygilany `Model.prototype`

**Comment by timmyreilly** [comment]
Just to tag this along, as this thread helped me a lot. Their might also be a setWhatever on one mode but not the other model in a many-to-many relationship. So... don't forget to check the other object for a set in the prototype before pulling your hair out.
