### ISSUE TITLE
Connection pool and replica

### ISSUE THREAD

**Issue by sm2017** [sequelize/sequelize#13941]
I have a master-slave postgres setup, if a slave goes down, and sequelize have many ECONNREFUSED error

Why it don't use others replicas?

**Comment by ephys** [comment]
Please don't delete our [issue template](https://github.com/sequelize/sequelize/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). We need information to properly help you such as library versions, and what your setup looks like and how it is configured.
