### ISSUE TITLE
Node 18 support?

### ISSUE THREAD

**Issue by fncolon** [sequelize/sequelize#13955]
https://nodejs.org/en/about/releases/

Node 18 will release in a short time, we need update ci pipeline according to it.

**Comment by fncolon** [comment]
Let me see if you guys find out if this is important and interesting @WikiRik (should be master for handling this kind of thing)  @sdepold @ephys

**Comment by ephys** [comment]
It won't be released for another 4 months, we have time :)

**Comment by fncolon** [comment]
> It won't be released for another 4 months, we have time :)

Yup, just keep it on note

**Comment by WikiRik** [comment]
I'll hijack this issue for a similar discussion; do we only want to support LTS versions or also the current versions? So do we want to include Node 17 already and move to Node 18 once that comes out or do we want to wait until Node 18 is in an LTS state (which is in October 2022)? If we choose to only support LTS versions I think we should close this issue and store this (and similar) information elsewhere in the project to keep the number of open issues low.

**Comment by fncolon** [comment]
> I'll hijack this issue for a similar discussion; do we only want to support LTS versions or also the current versions? So do we want to include Node 17 already and move to Node 18 once that comes out or do we want to wait until Node 18 is in an LTS state (which is in October 2022)? If we choose to only support LTS versions I think we should close this issue and store this (and similar) information elsewhere in the project to keep the number of open issues low.

Decreasing open issues should be my point too now 😄 , and we can move this discussion to keep maintainers remember about it, thanks!

**Comment by ephys** [comment]
I vote to only officially support LTS, but to document it

**Comment by fncolon** [comment]
+1 for LTS, reason why package-support PR does.

**Comment by sdepold** [comment]
From the current readme:

Sequelize follows Semantic Versioning and the official Node.js LTS schedule. Version 7 of Sequelize officially supports the Node.js versions ^12.22.0, ^14.17,0, ^16.0.0. Other version might be working as well.

Does that suffice?

**Comment by WikiRik** [comment]
Yeah, for the end-users this would indeed suffice. But for maintainers it might be nice to have a list of the various support policies (Node, TypeScript and the database versions of the dialects) and a nice checklist what to do if any of those need to be updated

**Comment by prodoxx** [comment]
Sequelize v6 isn't working for Node 19 nor Node 18

**Comment by ephys** [comment]
Please open a separate bug report that details your problem

**Comment by ollyde** [comment]
Do we have support for node 18 yet? 
Since Node 16 is soon to be archived.

I tried it and seems it's broken?

**Comment by WikiRik** [comment]
Seuqelize v6 supports Node 18, please open a new bug report if you experience problems with it

**Comment by ollyde** [comment]
I'm using 
"sequelize": "^6.31.1",

Seeing a ton of errors simply switching from 16 to 18.

**Comment by WikiRik** [comment]
Strange, I've updated our CI to use Node 18 (see #16000 ) for v6 as well and there our tests pass

**Comment by GordonHPepBoys** [comment]
Is this still the case? that V6 still works with Nodejs version 18?
