### ISSUE TITLE
When SQL errors occur, add 'message 'to DEBUG log or DatabaseError

### ISSUE THREAD

**Issue by mprevdelta** [sequelize/sequelize#13978]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description

When SQL errors occur, make the 'message' property describing the error available.

### Is your feature request related to a problem? Please describe.

When invoking Sequelize methods that create errors, the 'message' attribute of the error often gets buried. This message often describes precisely where the error occurs and is very useful for debugging problems with Models.

I propose this be logged using 'debug', or perhaps added to the created Error. 

### Describe the solution you'd like

Either a 'message' property added to DatabaseError, or for each driver to invoke debug() with the message when an error occurs. For the debug solution, user could use the DEBUG env var and get messages like this:

  sequelize:sql:mssql The INSERT statement conflicted with the FOREIGN KEY constraint "fk_bla_bla_bla". The conflict occurred in database "yourdb", table "yourtable", column 'id'

### Additional context

This issue may be specific to the mssql dialect.

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole. It looks like 
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] Possibly, depending on the solution used. Some other dialects may handle errors better than the mssql dialect is.

### Would you be willing to implement this feature by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I'd be willing to submit a simple pull adding the debug() call in mssql query.js. If the solution involved reworking DatabaseError I wouldn't feel comfortable making the change because it'd affect all dialects.

**Comment by ephys** [comment]
We could use the new [`Error#cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error) option, that'd improve the error output for users on node >= 16.9.0
