### ISSUE TITLE
QueryInterface API doc is not found(404) when going through Sequelize V4 documentation

### ISSUE THREAD

**Issue by asingh04** [sequelize/sequelize#13998]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description
In the v4 documentation of Sequelize, I was going through the "Migration" page where I found the link to the queryInterface API doc. When clicking on that link I got a 404 error (the page was missing)

### What was unclear/insufficient/not covered in the documentation
Doc was not there at all

### If possible: Provide some suggestions on how we can enhance the docs
Please doc available as I need to go through the queryInterface API. Currently, I have to check the API doc for v5 and hope that nothing breaks if I do something based on the v5 doc.
Write here.

### Additional context

Link to the missing doc: https://sequelize.org/class/lib/query-interface.js~QueryInterface.html

**Comment by WikiRik** [comment]
Hi! You can use  https://sequelize.org/v4/class/lib/query-interface.js~QueryInterface.html 

Not sure if we really want to fix it since the documentation is generated based on the code of v4 and we'd rather not touch that anymore. I'll discuss it with the team

**Comment by asingh04** [comment]
@WikiRik is it possible to add a redirection then? I don't know how GitHub pages work.

**Comment by ephys** [comment]
The broken URL has been fixed on https://sequelize.org/v4/manual/tutorial/migrations.html

I don't think it's worth it to add a redirection, as we don't know whether https://sequelize.org/class/lib/query-interface.js~QueryInterface.html is v4 or v5, and it's unlikely it's been linked to by something else than the v4 documentation
