### ISSUE TITLE
Type errors in database errors code

### ISSUE THREAD

**Issue by andrejleitner** [sequelize/sequelize#14000]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** N.A.

### What do you expect to happen?

Typescript compilation to work smoothly.

### What is actually happening?

There are some type errors from `sequelize` codebase:

```bash
node_modules/sequelize/lib/errors/database/exclusion-constraint-error.ts:23:5 - error TS2322: Type '(DatabaseErrorSubclassOptions & ExclusionConstraintErrorOptions) | {}' is not assignable to type 'DatabaseErrorSubclassOptions & ExclusionConstraintErrorOptions'.
  Type '{}' is not assignable to type 'DatabaseErrorSubclassOptions & ExclusionConstraintErrorOptions'.
    Type '{}' is missing the following properties from type 'ExclusionConstraintErrorOptions': constraint, fields, table

23     options = options || {};
       ~~~~~~~

node_modules/sequelize/lib/errors/database/foreign-key-constraint-error.ts:29:5 - error TS2322: Type '(ForeignKeyConstraintErrorOptions & DatabaseErrorSubclassOptions) | {}' is not assignable to type 'ForeignKeyConstraintErrorOptions & DatabaseErrorSubclassOptions'.
  Type '{}' is not assignable to type 'ForeignKeyConstraintErrorOptions & DatabaseErrorSubclassOptions'.
    Type '{}' is missing the following properties from type 'ForeignKeyConstraintErrorOptions': table, fields, value, index, reltype

29     options = options || {};
       ~~~~~~~

node_modules/sequelize/lib/errors/database/unknown-constraint-error.ts:23:5 - error TS2322: Type '(UnknownConstraintErrorOptions & DatabaseErrorSubclassOptions) | {}' is not assignable to type 'UnknownConstraintErrorOptions & DatabaseErrorSubclassOptions'.
  Type '{}' is not assignable to type 'UnknownConstraintErrorOptions & DatabaseErrorSubclassOptions'.
    Type '{}' is missing the following properties from type 'UnknownConstraintErrorOptions': constraint, fields, table

23     options = options || {};
       ~~~~~~~


Found 3 errors.
```

### Additional context

Appeared after the version upgrade: `6.7.0` > `6.14.0`

### Environment

- Sequelize version: 6.14.0
- Node.js version: 16.13.1
- TypeScript version: 4.3.5

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s):
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
This problem does really exist but it's weird it went unreported. Maybe it was shadowed by `types/lib/errors.d.ts` which wasn't deleted.

The fact that tsc is reporting errors in /lib for end-users is also an issue. That's likely due to tsc not being able to map `/lib` to `/dist/lib` yet

I think we should move `/lib` to `/src` & make `/lib` the folder for runnable code again, like it was before. We can then add src to `.npmignore`

**Comment by WikiRik** [comment]
> The fact that tsc is reporting errors in /lib for end-users is also an issue. That's likely due to tsc not being able to map `/lib` to `/dist/lib` yet
> 
> I think we should move `/lib` to `/src` & make `/lib` the folder for runnable code again, like it was before. We can then add src to `.npmignore`

Can you make a separate PR for this?
