### ISSUE TITLE
Recent changes to not call overloaded model functions are a breaking change

### ISSUE THREAD

**Issue by toddbaert** [sequelize/sequelize#14003]
This change: https://github.com/sequelize/sequelize/commit/b253d8ed63c91bc2c7143f07806554b5a5ac67eb avoids calling overloaded functions internally. I understand why it was undertaken, but this effectively breaks the way some users (and even other libraries) use Sequelize with 6.14.x.

Specifically, I believe [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript) to be broken with this change. I believe this package overrides the default model functions: https://github.com/RobinBuschmann/sequelize-typescript/blob/b60c011be2e971e56cb783d4ade994965faab916/src/model/model/model.ts#L209. Our codebase is a complex one, so I'm having difficulty concluding 100% that this override is the cause...

In any case, I have confirmed that if the lines to avoid the overrides are reverted, 6.14.x works fine by manually reverting them in the sequelize dist in my `node_modules`. I'm not a contributor to to either of these repos, but IMHO, a minor version shouldn't cause significant breakages like this. I imagine that over the next week, many devs will have to track down why their code is suddenly not working with a minor sequelize update.

**Comment by WikiRik** [comment]
We've reverted this PR for v6. Thanks for notifying us!

**Comment by ephys** [comment]
Thanks :)
