### ISSUE TITLE
findByPk's entry in the API documentation does not indicate that null is a valid return type

### ISSUE THREAD

**Issue by bartdorsey** [sequelize/sequelize#14025]
## Issue Creation Checklist

[X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

The API documentation for findByPk shows this type definition: 
`async findByPk(param: number | string | Buffer, options: object): Promise<Model>`

This indicates that this function will always return a Model. However when it doesn't find
an entry for an id, it returns null...

### If possible: Provide some suggestion on how we can enhance the docs

It should be documented like findOne is documented and show the optional null.

`async findByPk(param: number | string | Buffer, options: object): Promise<Model|null>`

### Additional context

Link to documentation page in question: https://sequelize.org/v7/class/lib/model.js~Model.html#static-method-findByPk

**Comment by ephys** [comment]
Source of the issue: https://github.com/sequelize/sequelize/blob/main/lib/model.js#L1983
