### ISSUE TITLE
Runtime.UnhandledPromiseRejection -- SequelizeConnectionError: this.lib.Connection is not a constructor, when running a query

### ISSUE THREAD

**Issue by ANTGOMEZ** [sequelize/sequelize#14028]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description
Using this code, I receive the error below:

const AWS = require('aws-sdk')
var Sequelize = require('sequelize');
var tedious = require('tedious')

exports.exec_sql_cmd = async function(conn_store, cmd)
{
  const sequelize = new Sequelize('TestDB', 'user', 'pwd', { dialectModule: 'tedious', dialect: 'mssql', host: 'server.domain.sub.com'})

  sequelize.query(cmd, { type: sequelize.QueryTypes.INSERT})
}

--Package.json--
"dependencies": {
    "aws-sdk": "^2.1065.0",
    "sequelize": "^6.15.0",
    "tedious": "^6.0.0"
  }

--ERROR--
"errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "SequelizeConnectionError: this.lib.Connection is not a constructor",
  "trace": [
    "Runtime.UnhandledPromiseRejection: SequelizeConnectionError: this.lib.Connection is not a constructor",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:400:28)",
    "    at process.emit (domain.js:475:12)",
    "    at processPromiseRejections (internal/process/promises.js:245:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
  ]
}

### Additional context
This is running from AWS Lambda Layer calling an on-prem server, all proper network settings are configured correctly to allow Lambda --->> On-Prem.

Also tried calling the query with AWAIT, but same result.

The cmd query passed in is correct.

Also tried IP address for host, same result

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [X] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
`dialectModule` can't be a string, its value must be the dialect module itself

**Comment by ANTGOMEZ** [comment]
Thanks.

Now that error is gone but I get this error message: "SequelizeConnectionError: Failed to connect to [ip address]:1433 in 15000ms"

My call looks like this:
const sequelize = new Sequelize('TableauTest', user, pwd, { dialectModule: tedious, dialect: 'mssql', dialectOptions: { options: { encrypt: false }}, host: 'ip address'})

Do I need another option?
