### ISSUE TITLE
Wrong type for unique property in QueryInterface.createTable()

### ISSUE THREAD

**Issue by abrain** [sequelize/sequelize#14039]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

In `Sequelize.define()` it is possible to pass a string or an object to the `unique` property instead of a boolean like so:
```js
Sequelize.define('my_model', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: 'name_unique'
    }
  });
```

Here is the TypeScript definition for it:
https://github.com/sequelize/sequelize/blob/7cceb66b8315a1377d8cf32c48f3050d7323e02c/types/lib/model.d.ts#L1329-L1334

As reported in #8269, this is not possible with `QueryInterface.createTable()`. Only a boolean can be used there for `unique`.

Yet, with TypeScript, both methods use the same interface `ModelAttributeColumnOptions` for the attributes. This leads users to believe, that it is possible to pass a string or an object for `unique` in `createTable()` when it is not.

### If possible: Provide some suggestion on how we can enhance the docs

While `Sequelize.define()` and `QueryInterface.createTable()` do not use the same format for describing models/tables (see #5213), I think it would make sense to adjust the TypeScript types to reflect the actual behaviour.

### Additional context

The API docs for `createTable()` refer to the type of the attributes only as `object` (see #11474). That gives the TypeScript types even more importance as a source of information for developers.

**Comment by christinittyjohn** [comment]
HI I'd like to pick this.
