### ISSUE TITLE
Clarification on `pg` version constraints

### ISSUE THREAD

**Issue by kuritz** [sequelize/sequelize#14056]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

In #12158 there is a long running thread of folks detailing how node 14 breaks `pg@<8.0.3`. There are various posts by people claiming to have fixed the issue by updating `pg` past this version, while running `sequelize@^4.0.0 || 5.0.0`.

This seems to be in direct conflict with the guidance in the sequelize documentation. Version constraints are noted for `v4`, `v5`, and `v6` as follows:

#### v4 manual

> The library for PostgreSQL is pg@^5.0.0 || ^6.0.0

[link](https://sequelize.org/v4/manual/installation/usage.html#postgresql)

#### v5 manual

> For PostgreSQL, two libraries are needed, pg@^7.0.0 and pg-hstore

[link](https://sequelize.org/v5/manual/dialects.html#postgresql)

#### v6 manual

> The underlying connector library used by Sequelize for PostgreSQL is the [pg](https://www.npmjs.com/package/pg) npm package (version 7.0.0 or above). The module [pg-hstore](https://www.npmjs.com/package/pg-hstore) is also necessary.

[link](https://sequelize.org/v6/manual/dialect-specific-things.html#postgresql)

So according to the manuals, I interpret that the first version of sequelize to officially support `pg@>8.0.3`, which is needed to resolve the compatibility issue with node 14, is `sequelize@^6.0.0`. Is this correct, or do the manuals need updating?

Node 12 will be reaching end of maintenance in a few months. It is important to know which versions of `sequelize` are officially compatible with the versions of `pg` needed to upgrade node to the next LTS (node 14).

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s): Postgres
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance (Need confirmation this is a documentation issue).
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
#12300 upgraded pg to version 8, but there were no specific updates to support this upgrade. Therefore pg@>8.0.3 should be safe to use in sequelize v5. But since we are only supporting security fixes in sequelize v5 I do not think we will update earlier manuals. I will however look into the issue for Node 14 and see if we need to specify that pg@>8.0.3 should be used for the next major release of sequelize. Thanks for reporting this!

**Comment by kuritz** [comment]
Thanks, @WikiRik ! Let me know if theres anything I can help with.

**Comment by WikiRik** [comment]
As per https://node-postgres.com/#version-compatibility you should use pg@>=8.2.x with Node >=14.x. I have made a PR to reflect this for the next major release (v7).
