### ISSUE TITLE
2 identical DBs using the same Model definitions. An expected query to the first initialized DB actually queries the last initialized DB.

### ISSUE THREAD

**Issue by anthonyorona** [sequelize/sequelize#14050]
## Bug Description

I have 2 databases, DB1 and DB2, and they both have identical schemas.

      const sequelizeDB1 = new Sequelize(
        'DB1',
        process.env.USERNAME,
        process.env.PASSWORD
      );

      const sequelizeDB2 = new Sequelize(
        'DB2',
        process.env.USERNAME,
        process.env.PASSWORD
      );

    const modelsDB1 = {
       sequelize: sequelizeDB1,
       Items: Items(sequelizeDB1, DataTypes)
    };

    const modelsDB2 = {
       sequelize: sequelizeDB2,
       Items: Items(sequelizeDB2, DataTypes)
    };

    const items = await modelsDB1.Items.findAll();

### What do you expect to happen?

I expect to see records from the DB1 Items table.

### What is actually happening?

I actually see the records from the DB2 Items table.

This bug seems like an implementation error by me. I did not realize that the Model classes do not have an internal mapping between the connected DB and the tables. Instead, the last connected database using these models is the one that is queried. In other words, there is not an instance returned by a call to Items(<sequelize_instance>, DataTypes). Instead the static initializer just updates some property of the Items Model object.

How should I initialize my DB connections so that I am able to query multiple databases that have the same schema???

### Environment

- Sequelize version: 6.6.5
- Node.js version: 16.7

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by anthonyorona** [comment]
I will mark this as resolved. Someone else may have this issue in the future. This was my solution:

  const sequelizeDB1 = new Sequelize(
    'DB1',
    process.env.USERNAME,
    process.env.PASSWORD
  );

  const sequelizeDB2 = new Sequelize(
    'DB2',
    process.env.USERNAME,
    process.env.PASSWORD
  );

const modelsDB1 = {
   sequelize: sequelizeDB1,
   Items: sequelizeDB1.define('items', Items.Attributes, Items.Options)
};

const modelsDB2 = {
   sequelize: sequelizeDB2,
   Items: sequelizeDB2.define('items', Items.Attributes, Items.Options)
};

const items = await modelsDB1.Items.findAll();

If you call sequelize.define(...) you are able to define a new Model for each Database. Using classes, because the sequelize instance is bound to a static property on the class, it will always be the last sequelize instance bound. This is a large security bug for a DB-per-tenant model, I'm surprised at this behavior.

**Comment by ephys** [comment]
I don't have the important part of your code so I can't say for sure, but given the behavior you're experiencing I think you were calling `.init` on the same class twice. `.init` mutates the class, it does not return a new one. A model can only be used by one sequelize instance at a time. If you call `.init` twice, the last call will be the one taken into account (that could be changed to reject after the first call imo).

If you want to use identical models with two sequelize instances, you need to use a factory that returns a brand new model when called. Which is basically what `Sequelize#define` does.

**Comment by anthonyorona** [comment]
@ephys Thanks I figured that out. It might be helpful for new users to prefer the factory, I used sequelize-cli to generate my Models as ES6 classes but using the factory is now my preference

**Comment by jamaica474** [comment]
@ephys I'm having the same problem. 2 databases on 1 physical server, and I need data from both databases in one run. 
I am calling init and after reading the doc it's still not clear how do I use define to solve this issue. 
architecture is as follows: 
Models are defined as classes.

```
import { Model, NUMBER } from 'sequelize';

export const TABLE_NAME = 'analytics_stats';

export const FIELD_DEFINITION = {
  postingId: {
    type: NUMBER,
    field: 'posting_id',
    primaryKey: true,
  },
  views: {
    type: NUMBER,
    field: 'views',
  },
  clicks: {
    type: NUMBER,
    field: 'clicks',
  },
};

export class AnalyticsAnalyticsStatus extends Model {
  views!: number;
  clicks!: number;
  postingId!: number;
}

export const setupRelations = (): void => {};

export const initModels = (sequelize): void => {
  AnalyticsAnalyticsStatus.init(FIELD_DEFINITION, {
    sequelize,
    tableName: TABLE_NAME,
  });
};

```

Then there is "init" method that initiates sequelize and returns instance to abstraction layer

```
 export const init = async (props: Types.InitProps): Promise<Sequelize> => {
    const log = getLogger('sequelize-api');
    const {
      CORE_SQL_DATABASE_DATABASE,
      CORE_SQL_DATABASE_HOST,
      CORE_SQL_DATABASE_CONNECTION_IDLE,
      CORE_SQL_DATABASE_CONNECTION_MAX,
      CORE_SQL_DATABASE_PORT,
      CORE_SQL_DATABASE_REQUEST_TIMEOUT,
      CORE_SQL_REPLICA_HOST,
      CORE_SQL_DATABASE_USERNAME,
      CORE_SQL_DATABASE_PASSWORD,
    } = process.env;

    const config: SequelizeAPI.Types.InitProps = {
      database: CORE_SQL_DATABASE_DATABASE,
      host: CORE_SQL_DATABASE_HOST,
      replicaHost: CORE_SQL_REPLICA_HOST,
      username: CORE_SQL_DATABASE_USERNAME,
      password: CORE_SQL_DATABASE_PASSWORD,
      idle: parseInt(CORE_SQL_DATABASE_CONNECTION_IDLE, 0),
      max: parseInt(CORE_SQL_DATABASE_CONNECTION_MAX, 0),
      port: parseInt(CORE_SQL_DATABASE_PORT, 0),
      requestTimeout: parseInt(CORE_SQL_DATABASE_REQUEST_TIMEOUT, 0),
      ...props,
    };
    const isProd = process.env.NODE_ENV === 'production';

    const dialectConfig = {
      authentication: undefined,
      options: {
        requestTimeout: config.requestTimeout,
        trustServerCertificate: true,
        validateBulkLoadParameters: true,
        readOnlyIntent: true,
      },
    };

    const sequelizeProps: Options = {
      logging: (query, executionTime) =>
        log('Execution time: %o ms, Query: %o', executionTime, query),
      database: config.database,
      username: config.username,
      password: config.password,
      benchmark: true,
      port: config.port,
      dialect: 'mssql',
      dialectModule: tedious,
      dialectOptions: dialectConfig,
      replication: {
        read: [
          {
            host: config.replicaHost,
          },
        ],
        write: {
          host: config.host,
        },
      },
      host: config.host,
      pool: {
        idle: config.idle,
        max: config.max,
        min: 0,
      },
      retry: {
        match: [
          ConnectionError,
          ConnectionTimedOutError,
          TimeoutError,
          /Deadlock/i,
          'SQLITE_BUSY',
        ],
        max: 3,
      },
      define: {
        freezeTableName: true,
        // schema: props.schema || 'dbo',
        timestamps: false,
      },
    };

    const sequelize = new Sequelize(sequelizeProps);
    await sequelize.authenticate();

    return sequelize;
  };
```

Then on the top level I'm creating what I think are 2 independent instances of sequelize

```
const props: SequelizeAPI.Types.SequelizeGetInstanceProps = {
    database: 'db1',
    host: '***',
    replicaHost: '***',
    idle: 5000,
    max: 25,
    port: 1433,
    requestTimeout: 600000,
    username: process.env.CORE_SQL_DATABASE_USERNAME,
    password: process.env.CORE_SQL_DATABASE_PASSWORD,
  };

  const db1 = await SequelizeAPI.getInstance(props);
  const db2 = await SequelizeAPI.getInstance({...props, database: 'db2'});
```

And I'm having the same problem as the topic starter, the second config seems to overwrite first and I can't execute queries to db1. How do I use define to solve this problem?

**Comment by anthonyorona** [comment]
@jamaica474 When you call AnalyticsAnalyticsStatus.init(...) you are calling the static initializer on the class. In ES6 classes resolve to an object prototype for model instances. So what happens is that when you call AnalyticsAnalyticsStatus.init(...)  a second time, you are calling the static init method, and this mutates a property on the Model class. To use it as sequelize.define(...) factory you could do this:

    sequelize.define('AnalyticsAnalyticsStatus', FIELD_DEFINITION, { tableName: TABLE_NAME });

Note that you are no longer passing the sequelize instance as a property on the options object.

**Comment by anthonyorona** [comment]
https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-define

**Comment by jamaica474** [comment]
@anthonyorona  thank you, this makes sense. And would you know by any chance how do I make relations work with factory? Following code returns error: 'Posting.hasMany called with something that's not a subclass of Sequelize.Model'
```
 Posting.hasMany('AnalyticsAnalyticsStatus', {
    as: 'campaign',
    foreignKey: 'postingId',
  });
  
```

**Comment by ephys** [comment]
You can still use classes / `Model.init` in a way that works like `Sequelize#define`. Actually `Sequelize#define` calls `Model.init` under the hood:

```typescript
function initUserModel(sequelize) {
  class User extends Model {
  }

  User.init({ /* attributes */ }, sequelize);

  return User;
}
```
