### ISSUE TITLE
> > During running sequelize migration I got

### ISSUE THREAD

**Issue by Fantast416** [sequelize/sequelize#14057]
> > During running sequelize migration I got
> > `ERROR: Identifier name 'manufactured_products_downstream_manufacturing_value_id_foreign_idx' is too long`
> > ![image](https://user-images.githubusercontent.com/16143176/61694767-771efb80-ad32-11e9-8173-3712a1035140.png)
> > Is there any possibility to exceed that limitation?
> > `migration.js`
> > ![image](https://user-images.githubusercontent.com/16143176/61694966-dda41980-ad32-11e9-88f2-0a558b8f7a3c.png)
> 
> Hello，I also encountered the same problem as you when performing the migration. UniqueKey did not work. Do you have a solution?

DId you find out solution for this issue?

_Originally posted by @khanisak in https://github.com/sequelize/sequelize/issues/1944#issuecomment-1030772009_

**Comment by WikiRik** [comment]
Hi! There is no need to open a new issue for this comment, you can discuss this in #1944
