### ISSUE TITLE
Frequent and unexpected ECONNRESET

### ISSUE THREAD

**Issue by NoMercyLS** [sequelize/sequelize#14055]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

After successful connect to database and started data-transfer connection-manager throwing ECONNRESET

### Sequelize provider pool configuration
```typescript
pool: {
      max: 64,
      min: 2,
      acquire: 300000,
      idle: 30000,
    },
```

### What do you expect to happen?

Data was successfully handled, no occasional errors was thrown 

### What is actually happening?

```
2|hub  | [2022-02-05T15:20:19.238] [ERROR] DayInfoRepository - DatabaseError: read ECONNRESET
2|hub  |  ├─╼ name: SequelizeDatabaseError
2|hub  |  ├─╼ parent: Error: read ECONNRESET
2|hub  |  ├─╼ original: Error: read ECONNRESET
2|hub  |  ├─╼ sql: SOME SQL HERE
2|hub  |  ├─╼ parameters: undefined
2|hub  |  │
2|hub  |  ├─┬╼ node_modules/sequelize/lib/dialects/postgres/query.js
2|hub  |  │ │
2|hub  |  │ ├──╼ Query.formatError @ line 366
2|hub  |  │ │
2|hub  |  │ │    default:
2|hub  |  │ ├╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │ │    return new sequelizeErrors.DatabaseError(err);
2|hub  |  │ │    }
2|hub  |  │ │
2|hub  |  │ ├──╼ undefined @ line 72
2|hub  |  │ │
2|hub  |  │ │    err.parameters = parameters;
2|hub  |  │ ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │ │    throw this.formatError(err);
2|hub  |  │ │    })
2|hub  |  │ │
2|hub  |  │ ├──╼ Query.run @ line 64
2|hub  |  │ │
2|hub  |  │ └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │      return query.catch(err => {
2|hub  |  │      // set the client so that it will be reaped if the connection resets while executing
2|hub  |  │
2|hub  |  │
2|hub  |  ├─┬╼ node_modules/sequelize/lib/sequelize.js
2|hub  |  │ │
2|hub  |  │ ├──╼ undefined @ line 655
2|hub  |  │ │
2|hub  |  │ │    .then(() => checkTransaction())
2|hub  |  │ ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │ │    .then(() => query.run(sql, bindParameters))
2|hub  |  │ │    .finally(() => this.runHooks('afterQuery', options, query))
2|hub  |  │ │
2|hub  |  │ ├──╼ undefined @ line 655
2|hub  |  │ │
2|hub  |  │ │    .then(() => checkTransaction())
2|hub  |  │ ├╌╌╌╌╌╮
2|hub  |  │ │    .then(() => query.run(sql, bindParameters))
2|hub  |  │ │    .finally(() => this.runHooks('afterQuery', options, query))
2|hub  |  │ │
2|hub  |  │ ├──╼ undefined @ line 651
2|hub  |  │ │
2|hub  |  │ │    : this.connectionManager.getConnection(options);
2|hub  |  │ ├╌╌╌╌╌╌╌╮
2|hub  |  │ │    }).then(connection => {
2|hub  |  │ │    const query = new this.dialect.Query(connection, this, options);
2|hub  |  │ │
2|hub  |  │ ├──╼ undefined @ line 641
2|hub  |  │ │
2|hub  |  │ ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │ │    return Promise.resolve(retry(() => Promise.try(() => {
2|hub  |  │ │    if (options.transaction === undefined && Sequelize._cls) {
2|hub  |  │ │
2|hub  |  │ ├──╼ Sequelize.query @ line 590
2|hub  |  │ │
2|hub  |  │ └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │      return Promise.try(() => {
2|hub  |  │      if (typeof sql === 'object') {
2|hub  |  │
2|hub  |  │
2|hub  |  ├─┬╼ node_modules/retry-as-promised/index.js
2|hub  |  │ │
2|hub  |  │ ├──╼ undefined @ line 70
2|hub  |  │ │
2|hub  |  │ ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │ │    Promise.resolve(callback({ current: options.$current }))
2|hub  |  │ │    .then(resolve)
2|hub  |  │ │
2|hub  |  │ ├──╼ retryAsPromised @ line 60
2|hub  |  │ │
2|hub  |  │ └╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │      return new Promise(function(resolve, reject) {
2|hub  |  │      var timeout, backoffTimeout, lastError;
2|hub  |  │
2|hub  |  │
2|hub  |  ├─┬╼ node_modules/sequelize/lib/query-interface.js
2|hub  |  │ │
2|hub  |  │ ├──╼ QueryInterface.select @ line 1126
2|hub  |  │ │
2|hub  |  │ └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │      return this.sequelize.query(
2|hub  |  │      this.QueryGenerator.selectQuery(tableName, options, model),
2|hub  |  │
2|hub  |  │
2|hub  |  ├─┬╼ node_modules/sequelize/lib/model.js
2|hub  |  │ │
2|hub  |  │ ├──╼ undefined @ line 1759
2|hub  |  │ │
2|hub  |  │ │    const selectOptions = Object.assign({}, options, { tableNames: Object.keys(tableNames) });
2|hub  |  │ ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │ │    return this.QueryInterface.select(this, this.getTableName(selectOptions), selectOptions);
2|hub  |  │ │    }).tap(results => {
2|hub  |  │ │
2|hub  |  │ ├──╼ Function.findAll @ line 1757
2|hub  |  │ │
2|hub  |  │ │    }
2|hub  |  │ └╌╌╌╌╌╌╌╮
2|hub  |  │      }).then(() => {
2|hub  |  │      const selectOptions = Object.assign({}, options, { tableNames: Object.keys(tableNames) });
2|hub  |  │
2|hub  |  │
2|hub  |  ├─┬╼ src/modules/databaseDynamic/core/BaseRepository.ts
2|hub  |  │ │
2|hub  |  │ ├──╼ BaseRepository.findAllQuery @ line 170
2|hub  |  │ │
2|hub  |  │ │    }
2|hub  |  │ └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |  │      return await this.repository.findAll<Entity>(query);
2|hub  |  │      }
2|hub  |  │
2|hub  |  │
2|hub  |  └┬╼ src/modules/databaseDynamic/repositories/DayInfo.repository.ts
2|hub  |   │
2|hub  |   ├──╼ undefined @ line 86
2|hub  |   │
2|hub  |   │    )) as BaseRepository<DayInfoModel>;
2|hub  |   └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮
2|hub  |        return await repository.findAllQuery<DayInfoModel>(query);
2|hub  |        } catch (err) {
```

### Additional context

1. All connection credentials absolutely correct
2. Not all connections closes
3. We have 2 Node.js apps which located in different racks. First app is replicated by pm2 on 12 instances, second on 32 instances, all of them knocking to 5 different databases that have their own repository, and of course, their own config and Sequelize instance which just copy-pasted from another(with a little changes)
4. Database doesn't close any connection. Never
5. Queries are absolutely correct
6. No packet-loss(`cause of local network in DC)
7. No memory leaks
8. Almost 8,500 errors occur in an hour

We fighting this problem almost half year. It started when queries count per hour raised to 200-300K. The database cannot close the connection, firstly because of the settings, and secondly because of the Odyssey put between the application and the database.

### Environment

- Sequelize version: 5.22.3
- Node.js version: 14.17.0, 14.18.3, 16.13.2, 17.4.0
- TypeScript version: 3.9.4
- PostgreSQL version: PostgreSQL 13.5 (Ubuntu 13.5-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): postgres
- [ ] I don't know, I was using postgres, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by manojmula** [comment]
I face similar issue in my daily work , I think the issue is not on the networking side. its on the software side. when you are passing the query , you are giving undefined or null values(mostly in where condition variables).If I am not clear , please let me know.

**Comment by NoMercyLS** [comment]
> I face similar issue in my daily work , I think the issue is not on the networking side. its on the software side. when you are passing the query , you are giving undefined or null values(mostly in where condition variables).If I am not clear , please let me know.

To be honest, we also faced a similar problem, the solution was really obvious(just validation)
But now we have 'clear' queries
Like this:
`
2|hub           | [2022-02-11T10:32:54.334] [ERROR] DayInfoRepository - DatabaseError: read ECONNRESET
2|hub           |  ├─╼ name: SequelizeDatabaseError
2|hub           |  ├─╼ parent: Error: read ECONNRESET
2|hub           |  ├─╼ original: Error: read ECONNRESET
2|hub           |  ├─╼ sql: SELECT "articleId", "daySalesSum", "sizes" FROM "dayInfos" AS "DayInfo" WHERE "DayInfo"."articleDateKey" IN ('15-01-2022_36088257', '15-01-2022_20953714', '15-01-2022_43352423', '15-01-2022_43352425', '15-01-2022_58776360', '15-01-2022_58771663', '15-01-2022_40664139', '15-01-2022_58768549', '15-01-2022_39389880', '15-01-2022_58851478', '15-01-2022_44657097', '15-01-2022_40443098', '15-01-2022_40939020', '15-01-2022_43352404', '15-01-2022_39389893', '15-01-2022_45514014', '15-01-2022_40939013', '15-01-2022_45686532', '15-01-2022_39295906', '15-01-2022_40939065', '15-01-2022_43352419', '15-01-2022_40771532', '15-01-2022_30137284', '15-01-2022_37087430', '15-01-2022_45686525', '15-01-2022_43352414', '15-01-2022_40939026', '15-01-2022_42472266', '15-01-2022_40443108', '15-01-2022_29208967', '15-01-2022_35844952', '15-01-2022_43415071', '15-01-2022_40664174', '15-01-2022_39048162', '15-01-2022_33017023', '15-01-2022_41500929', '15-01-2022_39807960', '15-01-2022_44231482', '15-01-2022_39389913', '15-01-2022_46507301', '15-01-2022_57161216', '15-01-2022_34056988', '15-01-2022_41501154', '15-01-2022_46507308', '15-01-2022_57161285', '15-01-2022_31760185', '15-01-2022_39807964', '15-01-2022_41826952', '15-01-2022_37839173', '15-01-2022_44051713', '15-01-2022_39807968', '15-01-2022_43352401', '15-01-2022_37839339', '15-01-2022_39389914', '15-01-2022_39295958', '15-01-2022_43352432', '15-01-2022_44882954', '15-01-2022_40664173', '15-01-2022_41826933', '15-01-2022_45514023', '15-01-2022_33017022', '15-01-2022_40443088', '15-01-2022_58239828', '15-01-2022_39389909', '15-01-2022_44961597', '15-01-2022_37839132', '15-01-2022_45514057', '15-01-2022_35845325', '15-01-2022_27484680', '15-01-2022_37839218', '15-01-2022_38536472', '15-01-2022_42472257', '15-01-2022_37089617', '15-01-2022_45266664', '15-01-2022_52051673', '15-01-2022_34962041', '15-01-2022_36051025', '15-01-2022_45514022', '15-01-2022_57161208', '15-01-2022_33016831', '15-01-2022_42472406', '15-01-2022_49972342', '15-01-2022_45686566', '15-01-2022_41826951', '15-01-2022_45686612', '15-01-2022_35415124', '15-01-2022_58239890', '15-01-2022_47905685', '15-01-2022_45721291', '15-01-2022_40664079', '15-01-2022_54650388', '15-01-2022_41501033', '15-01-2022_54802991', '15-01-2022_28459068', '15-01-2022_39048076', '15-01-2022_46507285', '15-01-2022_57518192', '15-01-2022_45514024', '15-01-2022_45266683', '15-01-2022_60849864', '15-01-2022_46247294');
`

**Comment by NoMercyLS** [comment]
Still occurs
