### ISSUE TITLE
TypeScript docs out-of-sync?

### ISSUE THREAD

**Issue by lensbart** [sequelize/sequelize#14061]
Hello,

On https://sequelize.org/v7/manual/typescript.html#usage there is a code example with the following comment at the top:
```ts
/**
 * Keep this file in sync with the code in the "Usage" section in typescript.md
 */
```

However, when looking through the Sequelize code on GitHub, the corresponding file (https://github.com/sequelize/sequelize/blob/main/types/test/typescriptDocs/ModelInit.ts) seems out-of-sync with the docs. Specifically, both `InferAttributes` and `InferCreationAttributes` are missing from the docs.

I guess the latter file is the latest version?

**Comment by ephys** [comment]
They are. I don't quite know how to publish the docs. @sdepold?

**Comment by WikiRik** [comment]
> The website is out of date, but the documentation is present in the repo. I don't quite know how to publish the docs. @sdepold?

Should happen with every release, as per https://github.com/sequelize/sequelize.org/blob/master/.github/workflows/main.yml but there is a command there to trigger it manually as well

**Comment by WikiRik** [comment]
Looked into it a little bit more, seems to be that the dispatch needs to happen from the default branch (main) and therefore the v6 releases did not pick it up. So a manual trigger should do it, I'll try it in a few moments.
For future info; as per https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event, the access token requires the `repo` scope but if you need a Maintain role or Triage (or Admin even) I can not really find at this moment

**Comment by ephys** [comment]
Thanks for looking into it :)

**Comment by sdepold** [comment]
The main branch should actually not trigger the build but rather the release of a new version. Should we release a new v7 alpha?

**Comment by sdepold** [comment]
Ah it seems that I didn't include the pinging of the docs repo on the v6 branch. Will fix that :)

**Comment by sdepold** [comment]
We just released a new v7 version and updated the docs based on it. I think this should be fine now :)

**Comment by ephys** [comment]
Nice, thanks!

@lensbart if you're using sequelize v6 (since v7 is currently in beta), https://sequelize.org/v6/manual/typescript.html is the documentation you're looking for :)
