### ISSUE TITLE
Mssql - Comment on column throws errors @model.sync

### ISSUE THREAD

**Issue by KreativJos** [sequelize/sequelize#14078]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

The following line does not work:
https://github.com/sequelize/sequelize/blob/f69d76108d15d5ee4a94ae5f425faac665f8edce/src/dialects/mssql/query-generator.js#L276

`this.quoteIdentifier` should be `this.quoteTable`

This only occurs when a comment is set on a table column, when running model.sync.

### What do you expect to happen?

A newly created table with the set comments.

### What is actually happening?

The following error is thrown:

```
UnhandledPromiseRejectionWarning: TypeError: identifier.replace is not a function
    at MSSQLQueryGenerator.quoteIdentifier [as _quoteIdentifier] (/home/DOWNUNDER/jos/Workspace/service_scenario/build/server/node_modules/sequelize/lib/dialects/mssql/query-generator.js:798:27)
    at MSSQLQueryGenerator.quoteIdentifier (/home/DOWNUNDER/jos/Workspace/service_scenario/build/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:645:19)
    at MSSQLQueryGenerator.commentTemplate (/home/DOWNUNDER/jos/Workspace/service_scenario/build/server/node_modules/sequelize/lib/dialects/mssql/query-generator.js:255:194)
    at MSSQLQueryGenerator.createTableQuery (/home/DOWNUNDER/jos/Workspace/service_scenario/build/server/node_modules/sequelize/lib/dialects/mssql/query-generator.js:136:30)
    at MSSqlQueryInterface.createTable (/home/DOWNUNDER/jos/Workspace/service_scenario/build/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:93:31)
    at Function.sync (/home/DOWNUNDER/jos/Workspace/service_scenario/build/server/node_modules/sequelize/lib/model.js:930:5)
```

### Environment

- Sequelize version: 6.16.1
- Node.js version: 14.16.1

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): mssql (/ tedious)
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start. (see 'bug description')
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Could you provide a SSCCE that replicates your issue? https://github.com/sequelize/sequelize-sscce

**Comment by KreativJos** [comment]
That would be a lot of work for such a simple issue.
Debugger shows the value of 'table':
![image](https://user-images.githubusercontent.com/20839414/153599796-60fb9d0d-9a73-4f0b-9c04-9a9c86238a67.png)

Stack:
https://github.com/sequelize/sequelize/blob/f69d76108d15d5ee4a94ae5f425faac665f8edce/src/dialects/mssql/query-generator.js#L123
https://github.com/sequelize/sequelize/blob/f69d76108d15d5ee4a94ae5f425faac665f8edce/src/dialects/abstract/query-interface.js#L229

In the query-interface.js you can see `tableName` is an object.

**Comment by ephys** [comment]
I somehow understood this as adding a comment on the table name, which confused me.
If any comment on a mssql column causes a crash like this, it should be easy enough to replicate!

I see you checked that you were willing to work on it. Would you mind opening a PR with the fix and a test?

**Comment by KreativJos** [comment]
Ah, I see I was not explicit indeed.
A PR with the fix is easy enough. I would not know how to create a test, but I can find out how - I'd guess it should be in this file:
https://github.com/sequelize/sequelize/blob/main/test/unit/dialects/mssql/query-generator.test.js

**Comment by ephys** [comment]
I think so too. What's weird is that it looks like there already is a passing test for it https://github.com/sequelize/sequelize/blob/main/test/unit/dialects/mssql/query-generator.test.js#L96

I'd recommend first trying to replicate the issue in a test before fixing
