### ISSUE TITLE
Serverless Package Fails to build

### ISSUE THREAD

**Issue by pjcjonas** [sequelize/sequelize#14077]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

Building under normal circumstances does not cause issues. However when packaging with Serverless Framework within a workspace the following issue is observed:

```bash
➜ yarn workspace @..../.... serverless package

yarn workspace v1.22.17
yarn run v1.22.17
$ /..../..../..../..../node_modules/.bin/serverless package
Serverless: serverless-offline-ssm checking serverless version 2.72.2.
Serverless: Cleaning dependency symlinks
Serverless: Creating dependency symlinks
Serverless: Compiling to es2018 bundle with esbuild...
Serverless: Compiling with concurrency: Infinity
✘ [ERROR] Could not resolve "../../package.json"

    ../node_modules/sequelize/lib/sequelize.js:571:19:
      571 │     return require("../../package.json").version;
          ╵                    ~~~~~~~~~~~~~~~~~~~~

 
 Error ---------------------------------------------------
 
  Error: Build failed with 1 error:
  ../node_modules/sequelize/lib/sequelize.js:571:19: ERROR: Could not resolve "../../package.json"
```

### Additional context

![image](https://user-images.githubusercontent.com/2368056/153164294-71c698eb-95dc-4c04-bec0-7127d3a7331c.png)

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
We just published a fix :) https://github.com/sequelize/sequelize/releases/tag/v6.16.1

**Comment by pjcjonas** [comment]
> We just published a fix :) https://github.com/sequelize/sequelize/releases/tag/v6.16.1

Testing it now, this is amazing news!

**Comment by pjcjonas** [comment]
@ephys Awesome, I can confirm its working as expected! Thx for sorting this out!
