### ISSUE TITLE
API Reference Docs Broken

### ISSUE THREAD

**Issue by fierysolid** [sequelize/sequelize#14092]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

The api reference docs are broken entirely, all versions

### If possible: Provide some suggestion on how we can enhance the docs

The api reference docs are broken entirely, all versions

### Additional context

<img width="732" alt="Screen Shot 2022-02-10 at 9 25 35 PM" src="https://user-images.githubusercontent.com/7339664/153528594-24d281f1-a0cd-4b76-b4b9-c34fb2550b56.png">

**Comment by fierysolid** [comment]
Yup totally a duplicate of the ticket that was created after it

**Comment by ephys** [comment]
I'm confused, that ticket was created on `2022-02-10T10:18:57Z` and this one was created on `2022-02-11T02:25:51Z`. The other one is older. But even then, would it matter? The point of de-duplicating is to centralize the conversation, it doesn't matter which one came first
