### ISSUE TITLE
Link to Sequelize constructor docs in "Getting Started - Connections" section is a 404 (v7)

### ISSUE THREAD

**Issue by Pointy** [sequelize/sequelize#14104]
## Issue Creation Checklist

[ x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

In the first part of the "Connections" section in the v7 tutorial docs, there's a link for full documentation for the Sequelize constructor. Unfortunately, that link results in a 404.

Specifically here: https://sequelize.org/v7/manual/getting-started.html#connecting-to-a-database

### What was unclear/insufficient/not covered in the documentation

Well, there's nothing there, so everything is unclear and insufficient

### If possible: Provide some suggestion on how we can enhance the docs

Fulfill the link: https://sequelize.org/v7/class/src/sequelize.js~Sequelize.html#instance-constructor-constructor

**Comment by WikiRik** [comment]
Since v7 is still in alpha, the v6 documentation should still suffice for now; https://sequelize.org/v6/class/src/sequelize.js~Sequelize.html#instance-constructor-constructor

We'll still look into the issue and update you when it's fixed

**Comment by Pointy** [comment]
Oh OK, thanks. I did not realize that v7 is alpha; on the main page of the website it just says "Latest".

**Comment by ephys** [comment]
esdoc is failing on `sequelize.js` because it doesn't support a recent-ish syntax we use.

https://github.com/sequelize/sequelize/pull/13914 fixes this, I need to move forward with it
