### ISSUE TITLE
Executing (default): SELECT 1+1 AS result looping indefinitely

### ISSUE THREAD

**Issue by clarencedesmarais** [sequelize/sequelize#14113]
## Description

I've recently enabled logs (locally) on my project for sequelize and I'm noticing this log :

`Executing (default): SELECT 1+1 AS result`

This log is non-stop (infinite loop).

I've checked online to see what could be the cause but I am not quite sure. 

See thread here : https://stackoverflow.com/questions/63611772/sequelize-does-not-creating-a-table-shows-this-result-executing-default-se

From what I understand, I would need to call sequelize.sync(), but even when I do, I still see that log. 

Plus, I don't feel the need to call that sync function since we create and modify our tables via migrations. 🤔 

Any idea what could be the cause of this ?

**Comment by ephys** [comment]
That's a query Sequelize runs to test that the connection to the database works (https://github.com/sequelize/sequelize/blob/491ff159cda4aab72bad558fce533fc98e09ae7f/src/sequelize.js#L895)

You should see it once, but if it runs multiple times, it's possible that there is an issue with the connection to the database, as failed queries will be retried under certain circumstances.

Calling `sync` is not necessary (as far as I know)

**Comment by clarencedesmarais** [comment]
Thank you very much. That unblocked me today :) 

My issue was that I had a monitoring function in my code (within a lib) that was periodically performing a check on this authenticate function to see if the connection was alright (which it was).

Closing this issue !
