### ISSUE TITLE
does Sequilize support ternary relationships?

### ISSUE THREAD

**Issue by medAmineRg** [sequelize/sequelize#14122]
Does Sequilize support using associations in which participates three models ? eg :

Role
Permisssion
Menu

How to handle such associations using Sequilize ORM since it's never mentioned on the official documentation ?

**Comment by ephys** [comment]
Do you mean something like a [Many-To-Many](https://sequelize.org/v6/manual/assocs.html#many-to-many-relationships) relationship? Otherwise what you want is likely multiple [One-To-Many](https://sequelize.org/v6/manual/assocs.html#one-to-many-relationships) relationships

**Comment by medAmineRg** [comment]
yes many to many relationship between 3 models?

**Comment by medAmineRg** [comment]
like  how l can translate a ternary assocation in sequilize?

**Comment by ephys** [comment]
Many-To-Many are between 3 models as one of them need to act as the through-table (https://en.wikipedia.org/wiki/Many-to-many_(data_model))

**Comment by medAmineRg** [comment]
in my case l have a many to many relationships between three models: role, permission and menu so they gonna generate a new entity ROLE_PERMISSION_MENU where id_role and id_menu and id_permission gonna be its primary key @[ephys](https://github.com/ephys)

**Comment by medAmineRg** [comment]
my bad
