### ISSUE TITLE
Relations: set<relatedModel>/add<relatedModel> after build fails due to empty object in table

### ISSUE THREAD

**Issue by SirUli** [sequelize/sequelize#142]
Hello,

if the Instance of a Model is not saved yet (when creating it with "build" instead of "create") and i add a Instance of a related  Model with "add", sequelize tries to set the relation but as the first model is not saved yet, it fails. See the following example:

```javascript
System.create({ name: 'TheMasterSystem' }).success(function(systemActive) {
        Landscape.build({ name: 'TheMajorLandscape', description: 'Some descr.' }).addSystem(systemActive)
        	.success(function(landscape) {
        		console.log("Successfully saved");
        	})
        	.error(function(err) {
        		console.log(err);
        	});
    });
```

```mysql
Executing: INSERT INTO `system` (`name`,`id`,`created_at`,`updated_at`,`deleted_at`,`description`,`state_id`) VALUES ('TheMasterSystem',NULL,'2012-03-22 17:26:36','2012-03-22 17:26:36',NULL,NULL,NULL);
Executing: SELECT `system`.* FROM `system`, `landscape_has_system` WHERE `landscape_has_system`.`landscape_id` IS NULL AND `landscape_has_system`.`system_id`=`system`.`id`;
Executing: SELECT `system`.* FROM `system`, `landscape_has_system` WHERE `landscape_has_system`.`landscape_id` IS NULL AND `landscape_has_system`.`system_id`=`system`.`id`;
Executing: INSERT INTO `landscape_has_system` (`landscape_id`,`system_id`,`created_at`,`updated_at`,`deleted_at`) VALUES (NULL,1,'2012-03-22 17:26:36','2012-03-22 17:26:36',NULL);
[ { [Error: Column 'landscape_id' cannot be null]
    number: 1048,
    sqlStateMarker: '#',
    sqlState: '23000',
    message: 'Column \'landscape_id\' cannot be null',
    sql: 'INSERT INTO `landscape_has_system` (`landscape_id`,`system_id`,`created_at`,`updated_at`,`deleted_at`) VALUES (NULL,1,\'2012-03-22 17:26:36\',\'2012-03-22 17:26:36\',NULL);',
    setMaxListeners: [Function],
    emit: [Function],
    addListener: [Function],
    on: [Function],
    once: [Function],
    removeListener: [Function],
    removeAllListeners: [Function],
    listeners: [Function] } ]
```

The Models - ```landscape```:

```javascript
module.exports = function(sequelize, DataTypes) {
	var Table = sequelize.define("landscape", {
		id: {
			type: DataTypes.INTEGER,
			primaryKey: true,
			autoIncrement: true
		},
		name: DataTypes.STRING,
		description: DataTypes.STRING
	});
	
	return Table;
}
```

The Models - ```system```:

```javascript
module.exports = function(sequelize, DataTypes) {
	var Table = sequelize.define("system", {
		id: {
			type: DataTypes.INTEGER,
			primaryKey: true,
			autoIncrement: true
		},
		name: DataTypes.STRING,
		description: DataTypes.STRING,
	});
	
	return Table;
}
```

And their connection:

```javascript
System.hasMany(Landscape, {joinTableName: 'landscape_has_system'});
Landscape.hasMany(System, {joinTableName: 'landscape_has_system'});
```

Now my suggestion would be to either not save the relation until the model gets saved or to save the model to the database and then save the relation? Or at least to document that "add<relatedModel>" saves the relation but not the underlying models which causes errors if the underlying model is not saved first.

Is there any way to set a relation from the instanciated Model A to the instanciated Model B without saving Model A first? Why do i want to do this? If i want to set many relations at once i'd like to reduce the number of queries that are needed for saving them afterwards.

Thanks in advance!

Best Regards,
Uli

**Comment by phanect** [comment]
Is this issue solved now?
I think we can now avoid error even we created without association ID, but we cannot add associating on `create()` / `save()`, right?

**Comment by mickhansen** [comment]
We have prelim support for nested create which should mostly solve this.
We also have `setAssociation(instance, {save: false})` for belongsTo relations.

**Comment by phanect** [comment]
OK, thanks.

I believe I can write cleaner code if I could associate on `create()` / `save()`, so I will create another issue or PR if I have chance to implement it.

**Comment by mickhansen** [comment]
@phanect https://github.com/sequelize/sequelize/pull/3386

**Comment by phanect** [comment]
Oh, I see, `include` already supports it. Great news for me!
I can make my code more readable. Thanks ;)
