### ISSUE TITLE
Dead link to eslintrc.json in CONTRIBUTING.md

### ISSUE THREAD

**Issue by alluvm** [sequelize/sequelize#14204]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

Unable to check code guideline specifics due to link leading to a non existent file.

### If possible: Provide some suggestion on how we can enhance the docs

Link to the correct file (if it exists somewhere), or remove/edit paragraph.

**Comment by WikiRik** [comment]
Ah yes, it's eslintrc.js now. Feel free to make a PR to fix this, otherwise I can make one tomorrow

Thanks for reporting this!
