### ISSUE TITLE
New data type to store only time with timezone

### ISSUE THREAD

**Issue by Sasha-hk** [sequelize/sequelize#14211]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Is your feature request related to a problem? Please describe.

I need data type to store only time with timezone, but I did not find the data type

### Describe the solution you'd like

The solution is to create new data type.

PostgreSQL data type to solve this problem [`here`](https://www.postgresql.org/docs/9.5/datatype-datetime.html#DATATYPE-DATETIME "PostgreSQL data types") - `time [ (p) ] with time zone`

### Why should this be in Sequelize

It's useful data type.

### Additional context

Sequelize has data type `TIME` but is store `TIME WITHOUT TIMEZONE`

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): `postgres`

### Would you be willing to implement this feature by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
According to the documentation I could find, only postgres supports `TIME WITH TIME ZONE`

<table>
<tr>
	<th>dialect
	<th>supports time with time zone
<tr>
	<td>postgres
	<td>yes - [`time with time zone`](https://www.postgresql.org/docs/9.1/datatype-datetime.html)
<tr>
	<td>mariadb
	<td>no - https://mariadb.com/kb/en/time/
<tr>
	<td>mssql
	<td>no - https://docs.microsoft.com/en-us/sql/t-sql/data-types/time-transact-sql?view=sql-server-ver15
<tr>
	<td>mysql
	<td>no - https://dev.mysql.com/doc/refman/8.0/en/time.html
<tr>
	<td>sqlite
	<td>no - https://www.sqlite.org/datatype3.html
<tr>
	<td>db2
	<td>no - https://www.ibm.com/docs/en/db2-for-zos/11?topic=columns-date-time-timestamp-data-types
<tr>
	<td>ibmi
	<td>no - https://www.ibm.com/docs/en/i/7.3?topic=formats-time-data-type
<tr>
	<td>snowflake
	<td>no - https://docs.snowflake.com/en/sql-reference/data-types-datetime.html#time
</table>

The base TIME datatype is here: https://github.com/sequelize/sequelize/blob/main/src/data-types.js#L464

This could be implemented the same way we implement [`DataTypes.INTEGER.UNSIGNED`](https://github.com/sequelize/sequelize/blob/main/src/data-types.js#L269): by adding a static getter that sets a flag. i.e. `DataTypes.TIME.ZONED`

Then postgres's datatype can extend the TIME class to make its `toSql` method return `TIME WITH TIME ZONE` if the flag is set.
Other dialects should log a warning if the flag is set as they don't support it.
Example of how to do that: https://github.com/sequelize/sequelize/blob/main/src/dialects/postgres/data-types.js#L295

**Comment by Sasha-hk** [comment]
I need to add warning to each dialect that not support time with timezone ?

**Comment by ephys** [comment]
Unfortunately yes, thankfully there is only a handful of them right now

**Comment by Sasha-hk** [comment]
It's not a problem 😄 

It's just that I haven't worked with such large projects yet, all I did was up to 20,000 lines of code.

**Comment by Sasha-hk** [comment]
Where I need to add tests? 

I'm already adding unit tests here: https://github.com/sequelize/sequelize/blob/main/test/unit/sql/data-types.test.js

**Comment by ephys** [comment]
That's good for unit tests :)
For typing tests, the right place is this file https://github.com/sequelize/sequelize/blob/main/test/types/data-types.ts

**Comment by Sasha-hk** [comment]
How can I push changes? I  created new branch from main, but when I try to push it it return error:

`remote: Permission to sequelize/sequelize.git denied to Sasha-hk.`

**Comment by ephys** [comment]
You need to create a fork (only maintainers can create branches in this repository), then open a pull request. All changes (including ours) are done through pull requests :)

Since I think you cloned this repository directly, here is what you can do:

- Create a [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) of this repository
- No need to clone your fork, instead change the remote of your local repository:
  `git remote remove origin`
  `git remote add origin url_of_your_fork` (the same URL you would use to clone)
- Push your changes, this time it should work
- Send us a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by ephys** [comment]
I forgot to close this issue. Please see reasons for closing here: https://github.com/sequelize/sequelize/pull/14213#issuecomment-1343053562
