### ISSUE TITLE
SequelizeEagerLoading model not associated with the other model

### ISSUE THREAD

**Issue by serdarmutluu** [sequelize/sequelize#14210]
---
name: Bug report
about: Create a bug report to help us improve
title: ""
labels: ""
assignees: ""
---

## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
UnhandledPromiseRejectionWarning: SequelizeEagerLoadingError: family is not associated to file!
File.js
const db = require('../db'); const { Sequelize, DataTypes } = require('sequelize');
const File = db.define('file', { id: { allowNull: false, autoIncrement: true, primaryKey: true, type: Sequelize.INTEGER }, fileName: { type: Sequelize.STRING }, train: { type: Sequelize.STRING }, ipn: { type: Sequelize.STRING }, createdAt: { allowNull: false, type: Sequelize.DATE }, updatedAt: { allowNull: false, type: Sequelize.DATE } },{ freezeTableName:true });
module.exports = File;
family.js const db = require('../db'); const { Sequelize, DataTypes } = require('sequelize');
const Family = db.define('family', { id: { allowNull: false, autoIncrement: true, primaryKey: true, type: Sequelize.INTEGER }, familyName: { type: Sequelize.STRING }, createdAt: { allowNull: false, type: Sequelize.DATE }, updatedAt: { allowNull: false, type: Sequelize.DATE } },{ freezeTableName:true });
module.exports = Family;
Association.js
const File = require('./file'); const Wire = require('./wire'); const Component = require('./component'); const Family = require('./family'); const Project = require('./project'); const db = require('../db'); const { Sequelize, DataTypes } = require('sequelize');
Component.belongsToMany(File , {through:'component_file'}); File.belongsToMany(Component , {through:'component_file'});
Wire.belongsToMany(File,{through:'wire_file'}); File.belongsToMany(Wire,{through:'wire_file'});
File.belongsTo(Project); Project.hasMany(File);
File.belongsTo(Family); Family.hasMany(File);
db.sync();

### What do you expect to happen?

I tried to create a file that is associated with a family which is already created.

### What is actually happening?

UnhandledPromiseRejectionWarning: SequelizeEagerLoadingError: family is not associated to file!

```
Output here
```

### Additional context

Add any other context and details here.

### Environment

- Sequelize version:
- Node.js version:
- If TypeScript related: TypeScript version:
- Database & Version:
- Connector library & Version:

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Just pasting [the same code](https://github.com/sequelize/sequelize/issues/14209) in the middle of the template isn't going to get you very far either. So again:

- please [format your code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
- follow the contributing guidelines, and provide a [SSCCE](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#opening-an-issue-to-report-a-bug) that actually reproduces your issue. Simply showing us what your models look like does not give us enough information to help you.
- please answer the questions that are asked in the bug report template

No need to open a new issue, you can edit this one and let us know so we can re-open it

**Comment by ughstudios** [comment]
This is also broken for me.
