### ISSUE TITLE
How to connect through SSH?

### ISSUE THREAD

**Issue by LesliePing** [sequelize/sequelize#14228]
I install mysql on the server and use ssh tunnel to make it safer.
But I look through the documentation and can't find any way to connet remote server by private key file.

**Comment by WikiRik** [comment]
That should be a part of the documentation of the [MySQL connector](https://github.com/sidorares/node-mysql2)

**Comment by marutichintan** [comment]
My Suggestion is to use reverse tunnel the mysql port to your PC using Putty (for windows) or ssh. you don't have to change anything in code.

**Comment by ephys** [comment]
I'll close as the author hasn't been active since, but there is nothing special to do in Sequelize to connect to a DB through a SSH tunnel. Follow any mysql through SSH tunnels tutorial and it should work https://linuxize.com/post/mysql-ssh-tunnel/
