### ISSUE TITLE
How to subtract a function in sequelize

### ISSUE THREAD

**Issue by tuan231195** [sequelize/sequelize#14241]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

I need to subtract an `fn` expression. I know we can use `literal` to do that. However, it is not feasible if the fn expression is too complex/dynamic.

For example:

```DAYOFWEEK(expression) - 1```

expression might not just a column name.

### Additional context

Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
You can't quite do that today but I've been thinking of an API to make literals more powerful that may resolve your use-case: https://gist.github.com/ephys/50a6a05be7322c64645be716fea6186a#literaltag-template-string

**Comment by ephys** [comment]
This is now available in v7 thanks to the new `sql` tag
