### ISSUE TITLE
Transaction doesn't rollback

### ISSUE THREAD

**Issue by scruel** [sequelize/sequelize#14269]
## Bug Description
Just executing the following code:
```
const transactionx = await sequelize.transaction()
await workflowToken.update(
  { node_id: 1 },
  { where: { token_id: 50 } },
  { transaction: transactionx }
)
await transactionx.rollback()
```
And I got my database updated, it not did rollback as I called

### What do you expect to happen?
rollback the updated row after called the `rollback()` method

### What is actually happening?
Nothing happened when `rollback()` called 

```
Executing (77f10ce8-f18d-4ddb-9b14-78302ecdc4de): START TRANSACTION;                                              
Executing (default): UPDATE workflow_tokens SET node_id=? WHERE token_id = ?                                      
Executing (77f10ce8-f18d-4ddb-9b14-78302ecdc4de): ROLLBACK; 
```

### Additional context

Add any other context and details here.

### Environment

- Sequelize version:
    "sequelize": "^6.16.1",
    "sequelize-auto": "^0.8.8",

- Node.js version:
`node -v`
```
v16.14.0
```
- If TypeScript related: TypeScript version:
- Database & Version:
'Database': 10.7.3-MariaDB
- Connector library & Version:
mysql

**Comment by ephys** [comment]
Your second query is executed on the default connection, instead of the transaction one.

You're passing `transaction` in a 3rd parameter but `.update` only accepts 2 parameters. This should be correct:

```typescript
const transactionx = await sequelize.transaction()
await workflowToken.update(
  { node_id: 1 },
  { 
    where: { token_id: 50 },
    transaction: transactionx,
  },
)
await transactionx.rollback()
```

**Comment by rahmathi3675** [comment]
thank you @ephys , i have same problem , and now solved.
