### ISSUE TITLE
query object serialization

### ISSUE THREAD

**Issue by createthis** [sequelize/sequelize#14272]
As sequelize query objects become more complex, it is common to generate them programmatically. Debugging a programmatically generated query object can be time consuming. I frequently find myself wishing there was a good way to serialize a sequelize query object for debugging purposes. For example, `console.log()` and `JSON.stringify()` tend to be inadequate once operators and functions are part of the query object.

**Comment by ephys** [comment]
I don't think there is a serialization format we could provide that would be clearer than calling `console.dir`. We could improve its output through [`util.inspect.custom`](https://nodejs.org/api/util.html#utilinspectcustom).

Do you have examples of parts of queries for which the output `console.dir` is not ideal?

**Comment by ephys** [comment]
I'll close as there hasn't been follow up, but feel free to ping us and we can reopen
