### ISSUE TITLE
No matching TypeScript API to create a WHERE clause with an array value?

### ISSUE THREAD

**Issue by henhal** [sequelize/sequelize#14288]
## Issue Creation Checklist

[X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

When creating a `where` condition with a postgreSQL `ARRAY` value, there seems to be no properly typed function in the TypeScript API.

```
const items = await myModel.findAll({
  where: sequelize.where(sequelize.literal('data->\'myArray\''), '?|', ['foo', 'bar'])
});
```

This does not compile, as the string array passed is not assignable to `LogicType`.

The code works though, if ugly-casting the array into `any`; I've also verified that QueryGenerator outputs:

```
SELECT "id", "createdAt", "updatedAt" FROM "items" AS "items" WHERE data->'myArray' ?| ARRAY['foo','bar'];
```

This seems to be just a matter of how this is done properly when using TypeScript. Or is there a wrapper function to enclose arrays in, to wrap them as `LogicType`s?

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

The example uses PostgreSQL specific `?|` operator, but I think the problem with passing a string array as the value is common for all dialects.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I doubt that `LogicType` should simply be expanded to also allow arrays of primitives?

**Comment by WikiRik** [comment]
I think #14020 will take care of this @ephys

**Comment by henhal** [comment]
Actually I just realized I was on Sequelize 6.6.2, embarrassingly enough. After updating to 6.17.0, and fixing some changed import paths, this seems to have been resolved already. Sorry!

**Comment by WikiRik** [comment]
No worries, thanks for the quick update!

**Comment by ephys** [comment]
Actually I have some bad news,

starting with Sequelize 7 (probably), the second argument in `where(leftOp, operator, rightOp)` will have to be one of our supported operators (`Op.x`).

What operator is `?|`? I haven't encountered it yet. Do you have a link to its documentation?

The good news is that in exchange for this change we're also working on improving the support for raw SQL, so your query could become this in the future:

```typescript
const items = await myModel.findAll({
  where: sql`data->'myArray' ?| ${myArray}`,
});
```

**Comment by WikiRik** [comment]
> What operator is `?|`? I haven't encountered it yet. Do you have a link to its documentation?

https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSONB-OP-TABLE

**Comment by ephys** [comment]
Thanks :)
