### ISSUE TITLE
Model API Reference has disappeared from v6 docs

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#14316]
## Issue Creation Checklist

[x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

Model API Reference has disappeared from v6 docs

### If possible: Provide some suggestion on how we can enhance the docs

Add Model API Reference

### Additional context

Happened after doc update I think

**Comment by WikiRik** [comment]
We think it happened before already, we're tracking this issue in https://github.com/sequelize/website/issues/43
