### ISSUE TITLE
Add default validation based on attribute type

### ISSUE THREAD

**Issue by nrmitchi** [sequelize/sequelize#1431]
I've been doing some initial playing around, and I've noticed that basic type validation (that I would consider expected behaviour) is not performed unless it is explicitly stated, which seems overly verbose.

For example:

``` javascript
  var Test = sequelize.define('Test', {
      attribute : { 
        type: DataTypes.INTEGER ,
        allowNull: false,
        validate: {
          notNull: true,
          isInt: true
        }
      }
    }, { }
  );
```

In the above example, it seems unnecessary to require the notNull and isInt validations.

Any thoughts on adding default type validation based on the provided column type?

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/3472
