### ISSUE TITLE
www - v6 API HTML pages / broken links to Model and init()

### ISSUE THREAD

**Issue by jaalto** [sequelize/sequelize#14322]
[

## Issue Creation Checklist

- [ x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

At page https://sequelize.org/docs/v6/core-concepts/model-basics/

Links to "Model" and "Init()" are broken.

### SSCCE

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
const { createSequelizeInstance } = require("./dev/sscce-helpers");
const { Model, DataTypes } = require(".");

const sequelize = createSequelizeInstance({ benchmark: true });

class User extends Model {}
User.init(
  {
    username: DataTypes.STRING,
    birthday: DataTypes.DATE,
  },
  { sequelize, modelName: "user" }
);

(async () => {
  await sequelize.sync({ force: true });

  const jane = await User.create({
    username: "janedoe",
    birthday: new Date(1980, 6, 20),
  });

  console.log("\nJane:", jane.toJSON());

  await sequelize.close();
})();
```

### What do you expect to happen?

Links are corrected.

### What is actually happening?

Links do not open.

```
HTML status code returned: 404
```

### Environment

- Sequelize version: v6
- Node.js version: not applicaple
- If TypeScript related: TypeScript version: not applicaple
- Database & Version: not applicaple
- Connector library & Version: not applicaple

## Would you be willing to resolve this issue by submitting a Pull Request?

I don't have permissions to Web server.

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
](https://sequelize.org/docs/v6/core-concepts/model-basics/

Links to "Model" and "Init()" are broken.
)

**Comment by ephys** [comment]
Thanks for the report!

I'll close this issue because we're already tracking this specific problem here https://github.com/sequelize/website/issues/43#issuecomment-1086869656
