### ISSUE TITLE
model and foreignKey turn null in One to one association

### ISSUE THREAD

**Issue by NirinaTanjona** [sequelize/sequelize#14330]
I try to learn one to one association in sequelize and task is always null, even if I copy code on the documentation. I don't know why
![postman](https://user-images.githubusercontent.com/48290392/161942557-9905478e-adbd-4b95-bfc9-4a39111c7aeb.png)

these are the user and task model:
```javascript
module.exports = (sequelize, Sequelize) => {
  const User = sequelize.define(
    'user',
    { name: Sequelize.STRING },
    { timestamps: false }
  );
  return User;
};```

```javascript
module.exports = (sequelize, Sequelize) => {
  const Task = sequelize.define(
    'task',
    { name: Sequelize.STRING },
    { timestamps: false }
  );
  return Task;
};
```
and this is the association between them:
```javascript
const db = {};
db.sequelize = sequelize;
db.Sequelize = Sequelize;
db.user = require('../models/user.model.js')(sequelize, Sequelize);
db.task = require('../models/task.model.js')(sequelize, Sequelize);
db.task.belongsTo(db.user);
db.user.hasOne(db.task);
module.exports = db;```

**Comment by Bishwodahal** [comment]
Please mention which code did you copied from documentation?

According to your code sql code would be:
```
CREATE TABLE `tasks` (
  `id` int(11) NOT NULL PRIMARY KEY AUTO INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `userId` int(11) DEFAULT NULL
) ;

CREATE TABLE `users` (
  `id` int(11) NOT NULL PRIMARY KEY AUTO INCREMENT,
  `name` varchar(255) DEFAULT NULL
) ;

ALTER TABLE `tasks`
  ADD CONSTRAINT `tasks_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
```

I am curious if this code works or not.  it shouldn't be working.
Didn't you get error something like `require(...) is not a function`
```
db.user = require('../models/user.model.js')(sequelize, Sequelize);
```
Here you just use that require but on the `user.model.js` you have done `module.exports.User = ` 
Are you sure that database consists all table and data fields. Another problem I see here is 
!!!  Only do the step mentioned below if data in table doesn't matter to you. 
If you aren't sure about table, then use `db.sync({force:true})` this will create table according to your code.

Please include more details

**Comment by NirinaTanjona** [comment]
I tried to reproduce this code and clean all other code but problem still the same, I got "null" on my foreignKey. So include return null too.
```javascript
const User = sequelize.define('user', { name: DataTypes.STRING }, { timestamps: false });
const Task = sequelize.define('task', { name: DataTypes.STRING }, { timestamps: false });

User.hasOne(Task);
Task.belongsTo(User);

const tasks = await Task.findAll({ include: User });
console.log(JSON.stringify(tasks, null, 2));
```

and I got this: 

```javascript
[{
  "name": "A Task",
  "id": 1,
  "userId": 1,
  "user": Null
  }
}]
```
I don't know why. Then I check the foreignKey and It's also null. 

```javascript
db.user = require('../models/user.model.js')(sequelize, Sequelize);
db.task = require('../models/task.model.js')(sequelize, Sequelize);
```
about this, require('....') return a function with (sequelize, Sequelize) as argument:

```javascript
module.exports = (sequelize, Sequelize) => {
  const User = sequelize.define("users", {
    username: {
      type: Sequelize.STRING,
    },
    email: {
      type: Sequelize.STRING,
    },
    password: {
      type: Sequelize.STRING,
    },
  });
  return User;

```

**Comment by ephys** [comment]
You need to configure the `foreignKey` option to set `allowNull` to false if you want it to be non-nullable https://sequelize.org/docs/v6/core-concepts/assocs/#customizing-the-foreign-key

**Comment by NirinaTanjona** [comment]
> You need to configure the `foreignKey` option to set `allowNull` to false if you want it to be non-nullable https://sequelize.org/docs/v6/core-concepts/assocs/#customizing-the-foreign-key

But it should not be null

**Comment by ephys** [comment]
That's why you need to set it to false, it's true by default

**Comment by fzn0x** [comment]
Did `allowNull: true` solve your problem, let us know, I've removed `type: docs` and changed the label to `question` for this issue.

**Comment by NirinaTanjona** [comment]
No it didn't, but I think the problem lays somewhere else. I'll try to recreate the database with different way. Thank you all for your help though 🙏🙏🙏

**Comment by ephys** [comment]
Not `allowNull: true` but `allowNull: false`:

```js
User.hasOne(Task, {
  foreignKey: { allowNull: false },
});
Task.belongsTo(User, {
  foreignKey: { allowNull: false },
});
```

**Comment by NirinaTanjona** [comment]
Aah ok I understand, but why the hell is it true by default? Is there a way to visualize model in sequelize?

**Comment by ephys** [comment]
I wasn't there when it was decided but I would assume it was decided that attributes would be nullable by default because SQL columns are nullable by default

The naming is also unfortunate. I prefer all boolean options to be false by default, but it's a decision that was taken a long time ago

We're considering changing it: https://github.com/sequelize/sequelize/issues/14260

> Is there a way to visualize model in sequelize?

Not built-in in Sequelize, but you can use `sequelize.sync({ force: true })` (warning: will reset your database and delete all data!) and use database visualization tools to see what the end result is like (jetbrains has one in their IDEs)

You can also use the logging option to see what the executed SQL is like.

**Comment by NirinaTanjona** [comment]
Thank you for the explaination, it's clear. I think I'll close the issue as the problem solved.

**Comment by fzn0x** [comment]
> Not `allowNull: true` but `allowNull: false`:
> 
> ```js
> User.hasOne(Task, {
>   foreignKey: { allowNull: false },
> });
> Task.belongsTo(User, {
>   foreignKey: { allowNull: false },
> });
> ```

Ah yes sorry for the typo
