### ISSUE TITLE
Implementing custom logic in association setter methods

### ISSUE THREAD

**Issue by klausXR** [sequelize/sequelize#14331]
## Issue Creation Checklist

[x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description

Ability to overwrite Sequelize mixin methods ( getProduct, setAddress )

### Is your feature request related to a problem? Please describe.

Currently, the `save` method is part of the Model's prototype.

This allows for this code to work

```js
class Product extends Model {
    async save(options) {
        // .. do custom things here

        // Call the original save method
        await super.save(options)
    }
}
```
If I want to implement some logic for every save, I can overwrite the method, do my stuff, then call the original one.

This, however, does not work for the association methods that Sequelize adds, because they are not added to the Model's prototype, but to the class that I provide. Meaning, this code does not work

```js
class Category extends Model {}
class Product extends Model {
    async setCategory(category, options) {
        // ... do my things here

        await super.setCategory(category, options)
    }
}

// Associations
Product.belongsTo(Category)
Category.hasMany(Product)
```

This does not work, because Sequelize will add the mixins to my own model's prototype, overwriting my method irreversibly.

There are no configurable names for association methods, so that I can name the original something like `_setCategory` and do this

```js
class Product extends Model {
    async setCategory(category, options) {
        // ... do my things here

        await this._setCategory(category, options)
    }
}
```

Association names also take the meaningful names out my naming options, like `setCategory` would be the exact thing that I'd like to do, but the method name is taken, so I'm left with either having to figure out another name for it or add my custom one with a prefix, like `$setCategory`, neither of which is good.

I don't really have any propositions at the moment, but are there any workarounds to this problem currently?

**Comment by ephys** [comment]
The association mixins won't overwrite your methods:
https://github.com/sequelize/sequelize/blob/main/src/associations/helpers.js#L50

Here is how you can delegate to the mixin methods:

```javascript
class Product extends Model {
  async setCategory(category, options) {
    // ... do your things here

    await Product.associations.category.set(category, options)
  }
}
```

**Comment by klausXR** [comment]
Can't try it out at the moment. Are you sure this is the syntax? Because its going to need the product instance so that it can set the category, so it must have some concept of the current context?

**Comment by ephys** [comment]
You're right, it's this:
```javascript
 await Product.associations.category.set(this, category, options)
```

**Comment by klausXR** [comment]
Thanks for the quick replies. This is sort of verbose, but I'm not sure there is a way around it, since the `super` one can't really work. 

Perhaps could have been nice to choose custom names for the association methods.

It does seem to work, though, so I will try to create some helper methods to get around the verbosity of t he solution.

**Comment by ephys** [comment]
You may be interested in taking a look at https://github.com/sequelize/sequelize/issues/14302, which changes how these association methods are handled

**Comment by klausXR** [comment]
By the way, is the same thing possible for getters/setters of values, where Sequelize would ignore adding it manually if it was already added? When working with classes, its more semantic and easier to understand for custom setters to be added to the Model object, like so

```js
// This is better
class Product extends Model {
    set quantity(value) {
        if (value === 0) {
            this.setDataValue('status', 'OUT_OF_STOCK')
        }

        this.setDataValue('quantity', value)
    }
}

// Than this
Model.init({
    quantity: {
        type: Sequelize.INT,
        allowNull: false,
        set(value) {
            if (value === 0) {
                this.setDataValue('status', 'OUT_OF_STOCK')
            }
    
            this.setDataValue('quantity', value)
        }
    }
})
```

Had a glance at the Query builder proposition. I was gonna propose a migration to another ORM for the lack of this, because the current system can't handle subqueries very well, you have to drop down to raw SQL. I can't even explain what a difference that would make for my team.

You are doing wonderful work here.

**Comment by ephys** [comment]
I agree, it would be better (I've actually tried doing that in the past, it's more intuitive imo) and it's something we could consider when working on https://github.com/sequelize/sequelize/issues/14300

The Query Builder should nicely solve the use case of using a subquery in `WHERE` (thanks to `QueryBuilder#toSql`). Subqueries in `FROM` and `JOIN` will have to come later as the internals of Sequelize will need to be reworked, but I'm determined to implement them. I really want that feature too

> You are doing wonderful work here.

Thanks! 💜
