### ISSUE TITLE
Create with association not working after MxN associations include

### ISSUE THREAD

**Issue by jsvargas** [sequelize/sequelize#14347]
## Issue Creation Checklist

- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When you use the include option when creating a new object it works as expected, except when it's done after a many-to-many association, where the id is returned as "null" and the insert query is not executed.

### SSCCE

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
const { Sequelize, DataTypes } = require('sequelize');
const sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_USER, process.env.DB_PASSWORD, {
  host: 'localhost',
  dialect: 'mysql'
});


const User = sequelize.define('user', {name: DataTypes.STRING}, { timestamps: false });
const Course = sequelize.define('course', {name: DataTypes.STRING}, { timestamps: false });
const Book = sequelize.define('book', {title: DataTypes.STRING}, { timestamps: false });

User.belongsToMany(Course, { through: 'user-course' });
Course.belongsToMany(User, { through: 'user-course' });
Course.hasMany(Book, { foreignKey: 'courseId' });
Book.belongsTo(Course, { targetKey: 'id', foreignKey: 'courseId'});

const userToInsert = {
  name: 'Juan',
  courses: [
    {
      name: 'Math', 
      books: [
        { title: 'Algebra' }
      ]
    },
    { name: 'Physics' }
  ]
};

(async () => {
  try {
    await sequelize.authenticate();
    await sequelize.sync();
    const result = await User.create(userToInsert, {
      include: [
        {
          model: Course,
          include: [
            {
              model: Book
            }
          ]
        }
      ],
      logging: console.log
    })
    console.log(JSON.stringify(result))
    await sequelize.close();
  } catch (error) {
    console.error('Unable to connect to the database:', error);
  }
})()
```

### What do you expect to happen?

I wanted that the books where inserted in the database with the correct Course association.

### What is actually happening?

The insert query for the book table is never executed, and the return object from the creation, has the book ids with null values.

```
Executing (default): INSERT INTO `users` (`id`,`name`) VALUES (DEFAULT,?);
Executing (default): INSERT INTO `courses` (`id`,`name`) VALUES (DEFAULT,?);
Executing (default): INSERT INTO `courses` (`id`,`name`) VALUES (DEFAULT,?);
Executing (default): INSERT INTO `user-course` (`createdAt`,`updatedAt`,`userId`,`courseId`) VALUES (?,?,?,?);
Executing (default): INSERT INTO `user-course` (`createdAt`,`updatedAt`,`userId`,`courseId`) VALUES (?,?,?,?);
{"id":16,"name":"Juan","courses":[{"id":34,"name":"Math","books":[{"id":null,"title":"Algebra"}]},{"id":35,"name":"Physics"}]}
```

### Additional context

If you do only the insert of Course and include their Books, it executes the query as expected: 
```js
const a = await Course.create(userToInsert.courses[0], {
      include: [
        {
          model: Book
        }
      ],
      logging: console.log
    })
    console.log(JSON.stringify(a))
```

```
Executing (default): INSERT INTO `courses` (`id`,`name`) VALUES (DEFAULT,?);
Executing (default): INSERT INTO `books` (`id`,`title`,`courseId`) VALUES (DEFAULT,?,?);
{"id":36,"name":"Math","books":[{"id":4,"title":"Algebra","courseId":36}]}
```

### Environment

- Sequelize version: "^6.18.0"
- Node.js version: v16.13.1
- Database & Version: mysql:5.7
- Connector library & Version: "mysql2": "^2.3.3"

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
I believe this is the same issue as https://github.com/sequelize/sequelize/issues/14306
