### ISSUE TITLE
sequelize Datatype STRING error

### ISSUE THREAD

**Issue by akshay977** [sequelize/sequelize#14344]
I think this error is related to sequelize Datatype STRING so please help me fix this.

![image](https://user-images.githubusercontent.com/30543542/162436261-9d5f9072-3090-4005-b88c-d328105e794d.png)

**Comment by ephys** [comment]
I'm afraid we don't have enough information to be able to help you.
We need to see the piece of code that is causing your issue. Ideally as a [SSCCE](https://github.com/sequelize/sequelize-sscce)

We also need to know which version of Sequelize you're using, as well as the database (and version), and connector (and version)

**Comment by ephys** [comment]
I'll close as the issue is still invalid and there has not been any follow up
