### ISSUE TITLE
sequelize.query() handling of replacement params for valid SQL operators ?& , ?|

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize#14358]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Trying to run these 2 raw queries with `sequelize.query` and passing the array as a replacement, so it would handle escaping?
```
SELECT * FROM product where tags ?& ARRAY['tag1', 'tag2']; 
SELECT * FROM product where tags ?| ARRAY['tag1', 'tag2']; 
```
`product.tags` is a JSONB array in Postgres.

I tried
```
let [recs, meta] = await sequelize.query(`SELECT * FROM product WHERE tags ?| ?`, {
        replacements: [['tag1', 'tag2']]
    })
```

but the `?` in `?|` operator is parsed as a replacement.
Thanks!

### What do you expect to happen?

`?|`, `?&` should be left intact, these are valid Postgres operators

### What is actually happening?

the `?` in `?|` operator is parsed as a replacement.

### Environment

- Sequelize version: 6.18.0
- Node.js version: 16.x
- Database & Version: 'PostgreSQL 14'
- Connector library & Version: pg 8

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
I believe this is the part of the code at fault: https://github.com/sequelize/sequelize/blob/main/src/sql-string.js#L110-L124

It searches for any `?` character, without checking if it's part of something else.

We need to improve the regex, but at the same time other things should keep working, list casting `?::integer`

**Comment by fzn0x** [comment]
> I believe this is the part of the code at fault: https://github.com/sequelize/sequelize/blob/main/src/sql-string.js#L110-L124
> 
> It searches for any `?` character, without checking if it's part of something else.
> 
> We need to improve the regex, but at the same time other things should keep working, list casting `?::integer`

I think we should add unit tests for all the regex that is in the Sequelize internal, seems like a lot of similar issues in other functions.

**Comment by ephys** [comment]
PR opened: https://github.com/sequelize/sequelize/pull/14404
