### ISSUE TITLE
DataType.JSON generates a colum with type longtext on MariaDB

### ISSUE THREAD

**Issue by hardmaster92** [sequelize/sequelize#14356]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

```js
// You can delete this code block if you have included a link to your SSCCE above!
const { createSequelizeInstance } = require("./dev/sscce-helpers");
const { Model, DataTypes } = require(".");

const sequelize = createSequelizeInstance({ dialect: 'mariadb' });

class User extends Model {}
User.init(
  {
    username: DataTypes.STRING,
    birthday: DataTypes.DATE,
    testJson: DataTypes.JSON, // the additional field that I've added
  },
  { sequelize, modelName: "user" }
);

(async () => {
  await sequelize.sync({ force: true });

  const jane = await User.create({
    username: "janedoe",
    birthday: new Date(1980, 6, 20),
    testJson: { field1: 12, field2: '444' };
  });

  console.log("\nJane:", jane.toJSON());

  await sequelize.close();
})();
```

### What do you expect to happen?

When opening the database using phpMyAdmin or any client I expected to see the column for `testJson` to have a `JSON` type, just like it's defined in the Sequelize model. The official Sequelize documentation [clearly states that the JSON data type is supported by MySQL and MariaDB](https://sequelize.org/docs/v6/other-topics/other-data-types/#json-sqlite-mysql-mariadb-and-postgresql-only).

### What is actually happening?

The column `testJson` has a type of `LONGTEXT` instead despite MariaDB supporting JSON and me having the ability to manually select JSON type from phpMyAdmin (showed in the attached screenshot).
![image](https://user-images.githubusercontent.com/15238282/162624611-e9ca9421-e586-455c-a71b-2969e7c68d9d.png)

### Additional context

Additionally, the generated column has a collation that doesn't match the one of the table and the other fields. The collation I've chosen is `utf8_general_ci` but this field has a `utf8mb4_bin` collation

### Environment

- Sequelize version: 6.18.0
- Node.js version: 16.14.2
- Database & Version: MariaDB v10.4.22
- Connector library & Version: mariadb v3.0.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
From the [MariaDB Knowledge Base](https://mariadb.com/kb/en/json-data-type/);
"JSON is an alias for [LONGTEXT](https://mariadb.com/kb/en/longtext/) introduced for compatibility reasons with MySQL's JSON data type. MariaDB implements this as a LONGTEXT rather, as the JSON data type contradicts the SQL standard, and MariaDB's benchmarks indicate that performance is at least equivalent."

Since sequelize does use this JSON alias I will close this issue.
