### ISSUE TITLE
Unable to connect with odbc

### ISSUE THREAD

**Issue by 2kamrul** [sequelize/sequelize#14361]
## Issue Creation Checklist

[✓ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

I'm trying to access DB2 AS/400 through odbc but getting this error. 

### What are you doing?

```js
const DB = new Sequelize('ODBC_DSN_NAME', 'DB_USER', 'DB_PASS', {
    dialect: 'ibmi',
    dialectOptions: {
        connectionTimeout: 10,
        loginTimeout: 10,
    }
})
DB.authenticate()
    .then(() => console.log('DB CONNECTED'))
    .catch((error) => console.log(error))
```

### What is actually happening?
```
ConnectionRefusedError [SequelizeConnectionRefusedError]: [odbc] Error connecting to the database
    at ConnectionManager.connect (D:\Personal\As400\node_modules\@sequelize\core\lib\dialects\ibmi\connection-manager.js:47:21)
    at async ConnectionManager._connect (D:\Personal\As400\node_modules\@sequelize\core\lib\dialects\abstract\connection-manager.js:219:24)
    at async D:\Personal\As400\node_modules\@sequelize\core\lib\dialects\abstract\connection-manager.js:176:32
    at async ConnectionManager.getConnection (D:\Personal\As400\node_modules\@sequelize\core\lib\dialects\abstract\connection-manager.js:199:7)
    at async D:\Personal\As400\node_modules\@sequelize\core\lib\sequelize.js:310:26
    at async Sequelize.authenticate (D:\Personal\As400\node_modules\@sequelize\core\lib\sequelize.js:423:5) {
  parent: [Error: [odbc] Error connecting to the database] {
    odbcErrors: [ [Object] ]
  },
  original: [Error: [odbc] Error connecting to the database] {
    odbcErrors: [ [Object] ]
  }
}
```

### Additional context

Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole
- [✓] Yes. This issue only applies to the following dialect(s): ibmi
- [ ] I don't know.

### Environment
Sequelize version: 7.0.0-alpha.10
Node.js version: 14.16.1

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [✓] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
Can you log the odbcErrors object? And can you add which version of odbc you have installed?

**Comment by 2kamrul** [comment]
### iSeries Access ODBC Driver (v11.64)
```js
[Error: [odbc] Error connecting to the database] {
  odbcErrors: [
    {
      state: 'IM002',
      code: 0,
      message: '[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified'
    }
  ]
}
```

**Comment by kadler** [comment]
@WikiRik The current driver identifies itself as `System i Access ODBC Driver` in the ODBC error mesages. If the error is coming from the database, it will also add `DB2 for i5/OS` (For more info, refer to ODBC Diagnostic Message format [here](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/diagnostic-messages?view=sql-server-ver15)).

@2kamrul I'm assuming the 11.64 driver version is the DLL version (which is different than the driver/product version), I _think_ this is theV5R4 version of the driver which is about a decade out of date and not supported. Please update to the latest version from https://ibm.biz/ibmi-odbc-download and try again (current DLL version should be 13.x.x.x).

Though, from the error message it could be that you have a firewall blocking you, since that error message is for "connection refused".

**Comment by 2kamrul** [comment]
I have installed latest driver version 13.64.25, now getting below message.
```js
[Error: [odbc] Error connecting to the database] {
  odbcErrors: [
    {
      state: '08004',
      code: 10061,
      message: '[IBM][System i Access ODBC Driver]Communication link failure. comm rc=10061 - CWBCO1049 - The IBM i server application  is not started, or the connection was blocked by a firewall'
    }
  ]
}
```

**Comment by 2kamrul** [comment]
This is for your information. Everything working fine with [odbc](https://www.npmjs.com/package/odbc) package that Sequelize also used for established connection. I have tested with both odbc driver version 11.64 and 13.64.25 all working fine.
Here is my code -
```
const connectionConfig = {
        connectionString: "DSN=XXX;uid=XXX;pwd=XXX;",
        connectionTimeout: 10,
        loginTimeout: 10,
    }

    try {
        const pool = await odbc.pool(connectionConfig);

        const connection = await pool.connect()

        const result = await connection.query(`SELECT * FROM db.table fetch first 2 rows only`)

        return res.json({ data: result }).end()
    } catch (error) {
        return res.json({ error }).end()
    }
```
