### ISSUE TITLE
Is `update()` failing silently with JSONB?

### ISSUE THREAD

**Issue by muhammad-bin-zafar** [sequelize/sequelize#14371]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Is it possible for `Model.update()` to fail silently on _anything_ and not update?

### SSCCE

```js
// file: model.js
class User extends Model {}
User.init(
  {
    data: {
        type: DataTypes.JSONB,
        allowNull:false,
        defaultValue: {one: true, two:false, three:true}
  },
  { sequelize, modelName: "user" }
);

// file: controller.js
const list = await User.findAll()
for (const user of list) {
    const {data} = user
    data.two = true
    await user.update({data})
}
```

### What do you expect to happen?

I wanted `data` to be updated. When enabled `logging`, I expected to see the log for UPDATE query.

### What is actually happening?

`data` did not get updated. When enabled `logging`, I only found the SELECT query for findAll.

### Additional context

```js
...
for (const user of list) {
    ...
    // case 1
    const _user = await User.findOne({id:user.id})
    await _user.update({data}) // works
    
    // case 2
    User.update({data}, {where: {id: user.id}}) // works
}
...
```

### Environment

- Sequelize version: 6.17.0
- Node.js version: v14.19.1
- If TypeScript related: TypeScript version:
- Database & Version: PostgreSQL 13.6
- Connector library & Version: `pg` 8.7.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Sequelize checks whether something must be persisted by comparing the new value to the old value.

You're mutating the value that was already in the model, so when sequelize does `old === new`, the result is still true.

You need to pass a new object:

```
 await user.update({ data: { ...data } })
```

Closing in favor of https://github.com/sequelize/sequelize/issues/13006

**Comment by muhammad-bin-zafar** [comment]
Thanks for the quick reply. I wonder, couldn't sequelize use any deep object property equality comparison to achieve that? Why `===` specifically? Please let me know.

**Comment by ephys** [comment]
well if `===` returns true, any deep equal function is also going to return true since the object stored internally and the one being mutated are still the same.

Being able to deep compare would require creating a deep clone of all attributes before you can mutate one of them, which would have a performance impact (+ the performance impact of using `deepEqual` on every attribute when using `save` or `update`).

A few years ago I would have said the cost is worth the benefit, but with the rise in popularity of immutability in JavaScript, I wonder if it wouldn't be better to deep freeze these objects instead (so attempting to mutate them would throw) & a good update to the documentation.

**Comment by muhammad-bin-zafar** [comment]
> A few years ago I would have said the cost is worth the benefit, but with the rise in popularity of immutability in JavaScript, I wonder if it wouldn't be better to **deep freeze these objects instead** (so attempting to mutate them would throw) & a good update to the documentation.

Sounds like a lot of work ahead.

**Comment by perki** [comment]
Hello, 

I confirm that there is an issue on updating JSON fields with sequelize `6.37.3`.
Even a deepClone has no effect. (It was a change nested at 3rd level).

I went in the sequelize code, but would be pleased to have some guidance to see where the "change check" is done to propose a fix. 
 
For now I'm just updating a `touchDate` at first level of object to force to update() to be done.
