### ISSUE TITLE
Add optional `noPrimaryKey` to prevent creating a default PK attribute

### ISSUE THREAD

**Issue by fzn0x** [sequelize/sequelize#14385]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Is your feature request related to a problem? Please describe.

Yes, use new option called `noPrimaryKey` similar to `timestamps` instead of manually remove it using `removeAttribute`.
The reference code to work with: https://github.com/sequelize/sequelize/blob/e59b3ff23d9c768994c502ee5be60279cb46a7e5/lib/model.js#L224 

### Describe the solution you'd like

A clear and concise description of what you want to happen. How can the requested feature be used to approach the problem it's supposed to solve?

```js
Model.init({}. { noPrimaryKey: true });
```

### Describe alternatives/workarounds you've considered

Add the` noPrimaryKey` option, if false and no primary key in the definitions, add the primary key `id` field automatically,

## Feature Request Checklist

- [x] Add the` noPrimaryKey` option, if false and no primary key in the definitions, add the primary key `id` field automatically,

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.

### Would you be willing to implement this feature by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.

**Comment by ephys** [comment]
I'll close in favor of https://github.com/sequelize/sequelize/issues/3142 as it's older but the PR is of course still valid and imo a good addition
