### ISSUE TITLE
FastifyDeprecation: You are accessing the deprecated "request.connection" property. Use "request.socket" instead.

### ISSUE THREAD

**Issue by masthanplumb5** [sequelize/sequelize#14382]
Hi Team
I am getting this below error while retrieving data using fastify framework and accessing database mssql

**FastifyDeprecation: You are accessing the deprecated "request.connection" property. Use "request.socket" instead.**

query I am trying to retrieving data'
sequelize.query(`EXEC User_Details @Action='GET'`,{ type: QueryTypes.SELECT });

versions I am using

"sequelize": "^6.18.0",
"fastify": "^3.27.4",
"tedious": "^14.4.0",

Hi Team kindly check.

**Comment by ephys** [comment]
Hi,
I think you're in the wrong repository. That error message is logged by [Fastify](https://github.com/fastify/fastify) and is unrelated to Sequelize
