### ISSUE TITLE
Support for Row Locking

### ISSUE THREAD

**Issue by jarruda** [sequelize/sequelize#1442]
I apologize if this feature exists, for I have not found anything in the documentation.

It seems Sequelize lacks support for row locking via SELECT FOR UPDATE / FOR SHARE.  I imagine this would be easy to tack onto the options object during finds.

**Comment by Farcek** [comment]
+1

**Comment by mickhansen** [comment]
@Farcek Why necro an old issue with a +1? This exists, as evident from the references PR.
