### ISSUE TITLE
Lacking of records when query with separate = true

### ISSUE THREAD

**Issue by onknight05** [sequelize/sequelize#14421]
## Issue Creation Checklist

- [ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
Lacking of records when query with separate = true.
### SSCCE
I have 3 models, items model, fields model and fieldCells model - items, fields hasMany fieldCells.
The fieldCells model has a primary key is itemID + fieldID.
When I get some items include fieldCells with separate = true. I found that it returns the wrong results with lacking some fields.
##### Example: 
itemID = 1, fieldID = 12 and itemID =  11, fieldID = 2.
Now get 2 items include fields with separate = true, the result is 1 field only.
##### Maybe bug on 
```js
// lib/dialects/abstract/query.js.
...
topHash += stringify(row[includeOptions.model.primaryKeyAttributes[$i]]);
...
```

https://doc.esdoc.org/github.com/sequelize/sequelize/file/lib/dialects/abstract/query.js.html#:~:text=topHash%20%2B%3D%20stringify(row%5BincludeOptions.model.primaryKeyAttributes%5B%24i%5D%5D)%3B

### What do you expect to happen?

I shoud return with all fields

### What is actually happening?

Lack of some records.
### Additional context

Add any other context and details here.

### Environment

- Sequelize version: 5.21.9
- Node.js version: v13.14.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by onknight05** [comment]
@ephys i already solve my issues on sequelize 5. This issues is just a note, so it is okay if it not maintained anymore.
Anyway, thank for you reply.

**Comment by WikiRik** [comment]
Then I'll close this issue. Thanks for the quick response!
