### ISSUE TITLE
https://sequelize.org unreachable - DNS Issues

### ISSUE THREAD

**Issue by phuze** [sequelize/sequelize#14420]
https://sequelize.org is unreachable, citing a DNS misconfiguration.

![image](https://user-images.githubusercontent.com/9218035/164370184-98c8fa7d-00fc-42f3-ac9b-9d6ea4cb49b3.png)

Here's what's currently being reported for the domain:

![image](https://user-images.githubusercontent.com/9218035/164370629-d9cc4f29-8f01-43da-a71f-54232a93f144.png)

It looks like the sequelize.org [website](https://github.com/sequelize/website) is hosted on GitHub pages, which means your DNS A records should be pointing to:

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

You can read more about how to configure the website on the [GitHub documentation](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site).

**Comment by vuletiki** [comment]
Does we have another docs ?

**Comment by phuze** [comment]
> Does we have another docs ?

For anyone who might need or want immediate access to the documentation while the Sequelize team resolves the issue, just add this entry to the bottom of your hosts file (assuming you're using Windows):

```
185.199.108.153 sequelize.org
```

You'll find the hosts file here: `C:\Windows\System32\drivers\etc\hosts`.

Then flush your local DNS resolver cache via powershell or command prompt:

```
ipconfig /flushdns
```

after which you should be able to access the website at http://sequelize.org/

Be sure to remove this entry from your hosts file once it's been properly addressed by the Sequelize team.

**Comment by WikiRik** [comment]
https://sequelize.org/ is online again so I'm closing this issue. I'll refer further comments to https://github.com/sequelize/website/issues/121
