### ISSUE TITLE
Error detail message is missing

### ISSUE THREAD

**Issue by leonkong** [sequelize/sequelize#14430]
## Issue Creation Checklist

- [ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
Updated sequelize from 6.9.0 to 6.19.0, I found error message in console is missing for the same error.

### SSCCE

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
const { createSequelizeInstance } = require("./dev/sscce-helpers");
const { Model, DataTypes } = require(".");

const sequelize = createSequelizeInstance({ benchmark: true });

class User extends Model {}
User.init(
  {
    username: DataTypes.STRING,
    birthday: DataTypes.DATE,
  },
  { sequelize, modelName: "user" }
);

(async () => {
  await sequelize.sync({ force: true });

  const jane = await User.create({
    username: "janedoe",
    birthday: new Date(1980, 6, 20),
  });

  console.log("\nJane:", jane.toJSON());

  await sequelize.close();
})();
```

### What do you expect to happen?
SequelizeDatabaseError: Unknown column 'DeliveryRoute.updated_at' in 'order clause'
      at Query.formatError (/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)
      at Query.run (/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

_I wanted Foo!_

### What is actually happening?
Error
      at Query.run (/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
      at /node_modules/sequelize/lib/sequelize.js:313:28
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async MySQLQueryInterface.select (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:396:12)
      at async Function.findAll (/node_modules/sequelize/lib/model.js:1126:21)
      at async Promise.all (index 1)
      at async Function.findAndCountAll (/node_modules/sequelize/lib/model.js:1296:27)

_The output was Bar!_

```
Output here
```

### Additional context

Add any other context and details here.

### Environment
VSCode
Version: 1.66.2 (Universal)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 20.6.0

- Sequelize version:
- Node.js version:
- If TypeScript related: TypeScript version:
- Database & Version:
- Connector library & Version:

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Can you create a minimal reproducible example that causes this error?

We also need these informations filled in:

- Database & Version:
- Connector library & Version:

**Comment by leonkong** [comment]
> Can you create a [minimal reproducible example](https://github.com/sequelize/sequelize-sscce) that causes this error?
> 
> We also need these information filled in:
> 
> * Database & Version:
> * Connector library & Version:

Any sequelize error will reproduce this problem. In other words, seqeulize 6.19.0 will give different error message with  seqeulize 6.9.0 in same error.

**Comment by ephys** [comment]
It looks like this error is the same as https://github.com/sequelize/sequelize/issues/14408
