### ISSUE TITLE
AWS RDS Proxy timeout issues

### ISSUE THREAD

**Issue by amitvishw** [sequelize/sequelize#14433]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description
Sequelize config:
```
new Sequelize({
  host: DB_HOST,
  database: DB_SCHEMA,
  username: DB_USER,
  dialect: "mysql",
  ssl: true,
  dialectOptions: {
      ssl: "Amazon RDS",
      connectTimeout: 4000,
      authPlugins: {
          mysql_clear_password: () => () => Buffer.from(<token>)
      }
  },
  hooks: {
      beforeConnect: async config => {
         //get token
      }
  },
  pool: {
      max: 1,
      evict: 3000,
      acquire: 4000
  }
  });
```

Notice the acquire timeout is set to 4 sec but it does not throw an error after acquire time is elapsed. Seems to wait for longer before throwing `SequelizeConnectionError: Timed-out waiting to acquire database connection`. 
In my observation Sequelize waits for the amount of time that is set as borrow timeout for AWS proxy. If I set borrow timeout to 60 sec then the time difference between `beforeConnect` hook completion and the first error thrown is also 60 sec. 

### Additional context

This issue happens when RDS is down and trying to get db connection via proxy.

### Environment
Sequelize version: 6.9.0
Node.js version: 14.x
If TypeScript related: TypeScript version: 4.4.4
Database & Version: 5.7.mysql_aurora.2.10.0
Connector library & Version: mysql2@2.3.3

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by soryy708** [comment]
So you're trying to connect to a RDS database through a proxy?
I hypothesize that the reason an error isn't thrown after 4 seconds (as set by `connectTimeout`) is because the connecting is actually successful to the proxy, but not to RDS.

**Comment by amitvishw** [comment]
Yes, connecting to RDS database through a proxy

**Comment by agustinparamio** [comment]
@amitvishw any solution to your problem? I have a similar issue.

I get SequelizeConnectionTimeoutError from time to time and cannot figure out why. We tested closing the connections like sequelize.org suggest but that approach is for non Proxy users.
