### ISSUE TITLE
PostGIS support

### ISSUE THREAD

**Issue by emadd** [sequelize/sequelize#1445]
I couldn't find any official mention of this, so I thought I'd come out and ask if this is being considered.

**Comment by mtfranchetto** [comment]
+1

**Comment by kevbradwick** [comment]
+1

**Comment by Ghirro** [comment]
+1

**Comment by Toub** [comment]
+1

**Comment by sharathm** [comment]
+1

**Comment by rafaelveloso** [comment]
+1

**Comment by golovanov** [comment]
+1

**Comment by leoromanovsky** [comment]
+1.. if that helps :-)

**Comment by warrieka** [comment]
+1

**Comment by albertkeba** [comment]
+1

**Comment by lipemorais** [comment]
+1

**Comment by thecaddy** [comment]
+1

**Comment by hal-gh** [comment]
+1

**Comment by gordlea** [comment]
Looks like this was just merged into master: #4013

**Comment by janmeier** [comment]
@gordlea Indeed, but only with postgres support for now. I'll close this one once @mikeingrose has added support for other dialecst as well

**Comment by mshahriarinia** [comment]
+1

**Comment by janmeier** [comment]
Closing this, since postgis support has landed. https://github.com/sequelize/sequelize/issues/2839 will be used to track general gis / geometry support
