### ISSUE TITLE
Response fields order if I use include

### ISSUE THREAD

**Issue by yellowduckbear** [sequelize/sequelize#14464]
I have two tables Orders and Order_address. In Orders there are two fields delivery_address_id and billing_address_id which are linked to Orders_address id.

In the db.js used this
db.orders_addresses = require("./order_addresses.model.js")(sequelize, Sequelize);
db.orders = require("./orders.model.js")(sequelize, Sequelize);
db.orders.belongsTo(db.orders_addresses, { modelName: 'delivery', as: 'deliveryAddress', foreignKey: 'delivery_address_id' });
db.orders.belongsTo(db.orders_addresses, { modelName: 'billing', as: 'billingAddress', foreignKey: 'billing_address_id' });

In the orders.controller.js
exports.findAll = (req, res) => {
  Order.findAll({
    limit: req.query.size,
    offset: 0 + (req.query.page -1) * req.query.size,
    attributes:["id", "payment", "delivery_type", "first_name", "last_name", "order_date"],
    include: ["deliveryAddress", "billingAddress"],
    where: {}, 
  })
  .then(data => {
    if (data) {
      res.send(data);
    } else {
      res.status(404).send({
        message: `Cannot find any Orders.`
      });
    }
  })
}

response:
[
    {
        "id": 1,
        "payment": "CASH",
        "delivery_type": "PERSONAL",
        "first_name": "unknown01",
        "last_name": "unknown01",
        "order_date": "2021-05-09T22:00:00.000Z",
        "deliveryAddress": {
            "id": 1,
            "country": "hun",
            "zip": "8200",
            "settlement": "22213",
            "address": "Egry"
        },
        "billingAddress": {
            "id": 2,
            "country": "eng",
            "zip": "3210",
            "settlement": "323",
            "address": "Wellington"
        }
    }
]

BUT: I would like to see deliveryAddress and biillingAddress between delivery_types and first_name. Is it possible to change response fields order?

BR
Tamás

**Comment by ephys** [comment]
There is no way to control the order of the properties of the object sequelize will create. There also isn't much of a point to implement that in Sequelize itself. If you really need your properties to follow a specific order, you'll need to create a new object yourself

**Comment by yellowduckbear** [comment]
Thanks for your answer. I found this solution:

Order.findAll({
      include: ["deliveryAddress", "billingAddress", "items"],
      where: { id: orderId }
    })
    .then(data => {
      if (data){
        res.status(200).json({
          id: data[0].id,
          payment: data[0].payment,
          deliveryType: data[0].delivery_type,
          deliveryAddress: data[0].deliveryAddress,
          billingAddress: data[0].billingAddress,
          firstName: data[0].first_name,
          lastName: data[0].last_name,
          orderDate: data[0].order_date,
          orderSum: data[0].order_amount,
          items: data[0].items
        })
      } else {
        res.status(404).send({
          message: `Cannot find Order with.`
        });
      }
    })

**Comment by ephys** [comment]
Yep! That is the solution I meant :)
