### ISSUE TITLE
WhereAttributeHashValue should allow WhereOptions as possible value

### ISSUE THREAD

**Issue by adrienboulle** [sequelize/sequelize#14478]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE
`WhereAttributeHashValue` typing does not allow `Where` type where it is actually a legit value
 
```ts
class User extends Model {}

await User.findOne({
  {
    username: Sequelize.where(...),
  },
);
```

### What do you expect to happen?

_I wanted this to compile_

### What is actually happening?

_Typescript does not allow this_

### Environment

- Sequelize version: latest (v6.19.0)
- Node.js version: 16
- If TypeScript related: TypeScript version: 4.6
- Database & Version: N/A
- Connector library & Version: N/A

## Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by intellix** [comment]
We're getting this same error actually when trying to use it against createdAt:

```ts
where: {
  createdAt: Sequelize.where(Sequelize.fn('date_trunc', 'day', Sequelize.col('createdAt')), '=', Sequelize.literal('CURRENT_DATE')),
}
```

The error is:
```
Types of property 'createdAt' are incompatible.
    Type 'Where' is not assignable to type 'WhereAttributeHashValue<Date>'.ts(2769)
```

**Comment by ephys** [comment]
`where` generates an expression that will produce a boolean, I don't think you want to check that `createdAt` is true / false

```ts
where: {
  createdAt: where(fn('date_trunc', 'day', col('createdAt')), '=', literal('CURRENT_DATE')),
}
```

would produce (roughly):

```sql
WHERE "createdAt" = (date_trunc('day', "createdAt") = CURRENT_DATE)
```

What you want is just

```ts
where: where(fn('date_trunc', 'day', col('createdAt')), '=', literal('CURRENT_DATE'))
```

**Comment by intellix** [comment]
just tested this locally with 6.29.0 and actually, it didn't produce like mentioned.

Passing as where: 
```ts
await User.findAll({
  where: getWhereConditionForToday('createdAt'),
});
```
gave:
```sql
WHERE date_trunc('day', "createdAt") = CURRENT_DATE;
```

Passing as property:
```ts
await User.findAll({
  where: {
    createdAt: getWhereConditionForToday('createdAt'),
  },
});
```
gave:
```
WHERE date_trunc('day', "createdAt") = CURRENT_DATE;
```

and adding an extra property:

```ts
await User.findAll({
  where: {
    createdAt: getWhereConditionForToday('createdAt'),
    id: 1,
  },
});
```
gave:
```sql
WHERE date_trunc('day', "createdAt") = CURRENT_DATE AND "User"."id" = 1;
```

I think it makes sense what you're saying but just from testing it didn't seem to work like that

**Comment by ephys** [comment]
No that's because Sequelize has two very different codepaths for handling the "plain object" syntax (`{ id: 1 }`) and the `where()` syntax (`where(col('id'), '=', 1)`), and that second one is riddled with bugs (fixing it is one of the main reasons I joined in the first place #13602)

PR #15598 fixes that completely (I hope), but will only land in v7

If you want to combine `where()` with another condition, you can use `and()`:

```ts
await User.findAll({
  where: and(
    getWhereConditionForToday('createdAt'),
    { id: 1 },
  ),
});
```
