### ISSUE TITLE
Empty Database

### ISSUE THREAD

**Issue by heartforit** [sequelize/sequelize#1447]
hi, 

everytime i try to use the code below, my sqlite database is still empty

``` js
var Sequelize = require("sequelize");
var sequelize = new Sequelize('mydb', '', '', {
  // sqlite! now!
  dialect: 'sqlite',

  // the storage engine for sqlite
  // - default ':memory:'
  storage: 'mydb.sqlite'
  //storage: ':memory:'
});
```

I don't know what am doing wrong.
I use the latest version of sequelize, nodejs and npm on windows.

**edit by janmeier: code formatting, for sanity**

**Comment by saurabhghewari** [comment]
how to override the default storage. I am using hapi-sequelize pluign to connect to database. All works properly, but .sqlite file in not created. All data is stored in memory, which is default engine. I sync all the models on server start, no file is created.

below is the config for sqlite db:-

                name: "xyz",
                dialect: "sqlite",
                models: "path/to/models",
                storage: "demo.sqlite",
                sequelize: {
                    define: {
                        logging: false,
                        underscoredAll: true,
                        timestamps: true,
                    }
                }
where I am going Wrong? or Missing docs to read about sqlite and sequelize.

**Comment by janmeier** [comment]
Are you sure you are looking in the right place, and that the node process has access to write to that location? I just tested with `storage: '/tmp/test.sqlite'` and it works fine

**Comment by saurabhghewari** [comment]
Yes, storage path given in code means it should create ".sqlite" file in current directory, right? but not getting why it does not create the file.

**Comment by janmeier** [comment]
Can you create a ![SSCCE](HTTP://SSCCE.ORG/)?  - I cannot replicate the issue

**Comment by saurabhghewari** [comment]
checkout this repo https://github.com/psahindrakar/hapi-typescript-todo

This is spike project we have done with sqlite as storage. but does not create file.

**Comment by janmeier** [comment]
I'd rather not have to install typescript and whatnot - Just a simple copy-pasteable test case please :)

Also, sqlite should be throwing an error if it cannot write - it the query succeeds, something must have been written

**Comment by saurabhghewari** [comment]
'use strict';

        const Hapi = require('hapi');

        // Create a server with a host and port
        const server = new Hapi.Server();
        server.connection({ 
            host: 'localhost', 
            port: 8000 
        });

        server.register(
            [
                {
                    register: require('hapi-sequelized'),
                    options: {
                dialect: 'sqlite',
                storage: 'test.sqlite',
                        models: 'models/*.js',
                        sequelize: {
                            define: {
                                underscoredAll: true
                            }
                        }
                    }
                },
            ], function(err) {
                if (err) {
                    console.error('failed to load plugin');
                }
            }
        );

        // Add the route
        server.route({
            method: 'GET',
            path:'/hello', 
            handler: function (request, reply) {

                return reply('hello world');
            }
        });

        // Start the server
        server.start((err) => {

            if (err) {
                throw err;
            }
            console.log('Server running at:', server.info.uri);
        });


        //Models dir Company.model.js

        'use strict' 

        module.exports = function(sequelize, DataTypes) {
                var Company = sequelize.define('company', {
                company_id: {
                    type: DataTypes.INTEGER,
                    primaryKey: true,
                    autoIncrement: true
                },
                name: {
                    type: DataTypes.STRING
                },
                email: {
                    type: DataTypes.STRING
                },
                contact: {
                    type: DataTypes.STRING
                },
                logo: {
                    type: DataTypes.STRING
                },
                is_deleted: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false }
            });

            Company.sync();

            return Company;
        }

**Comment by janmeier** [comment]
Have you tested it with plain sequelize, without hapi? Have you checked that any queries are being run, otherwise the database file won't be created

**Comment by saurabhghewari** [comment]
I will check with plain sequelize and let you know?

**Comment by sushantdhiman** [comment]
Yes, it will prove thats indeed sequelize issue not misconfiguration or hapi related bug. Pleas submit a [SSCCE](http://sscce.org).

**Comment by saurabhghewari** [comment]
ok, sqlite file is created when done with bare sequelize code. Its the bug in hapi-sequelized hapi plugin.
Thanks for the instant reply and support.

**Comment by saurabhghewari** [comment]
var Sequelize = require('sequelize');

var sequelize = new Sequelize({
  dialect: 'sqlite',

  // SQLite only
  storage: 'test.sqlite'
});

sequelize
  .authenticate()
  .then(function(err) {
    console.log('Connection has been established successfully.');
  })
  .catch(function (err) {
    console.log('Unable to connect to the database:', err);
  });

var User = sequelize.define('user', {
  firstName: {
    type: Sequelize.STRING,
    field: 'first_name' // Will result in an attribute that is firstName when user facing but first_name in the database
  },
  lastName: {
    type: Sequelize.STRING
  }
}, {
  freezeTableName: true // Model tableName will be the same as the model name
});

User.sync({force: true}).then(function () {
  // Table created
  return User.create({
    firstName: 'John',
    lastName: 'Hancock'
  });
});
