### ISSUE TITLE
Unable to set a Default Value to a JSON DataType

### ISSUE THREAD

**Issue by M1O0O** [sequelize/sequelize#14488]
```ts
 commands: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: '[]',
    get() {
        return JSON.parse(this.getDataValue('commands'));
    }
}
```
![dbeaver_TiwJyXLuAF](https://user-images.githubusercontent.com/50182658/167284639-43473aa9-138f-4439-b44a-306cda5fc136.png)

--- 

I can define an Object or Array when it's a string, the problem is that when I retrieve the entire contents of my table, the values ​​don't parse automatically to JSON.

```ts
commands: {
    type: DataTypes.STRING,
    allowNull: false,
    defaultValue: '[]',
    get() {
        return JSON.parse(this.getDataValue('commands'));
    }
}
```
Fetch All
```ts
Roles.findAll().then(roles => {
    console.log(roles.shift());
});
```
Output
![](https://files.m1000.fr/Code_zvsCOdEsS8.png)

When i fetch only `commands`
```ts
Roles.findAll().then(roles => {
    console.log(roles.shift().commands);
})
```

Output
![](https://files.m1000.fr/Code_oWHd3hRetc.png)
The result is parsed.

**How could I either assign a default value to a JSON DataType or parse automatically when it's a String DataType ?**

**Comment by ephys** [comment]
I need you to provide the information mentioned here to be able to help you with this https://github.com/sequelize/sequelize/blob/main/.github/ISSUE_TEMPLATE/bug_report.md#additional-context
