### ISSUE TITLE
A SubClass extend from Model will not serialize data correctly if calling super on subclass

### ISSUE THREAD

**Issue by FeiBam** [sequelize/sequelize#14508]
## Issue Creation Checklist

[x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description
A class inheriting from Model will not serialize data correctly if calling super

### Additional context

I created a new class called User which extend Model
I called super inside the constructor of the User class
Then the data will not be serialized correctly
it is bug?

Model/User.js: 
class User extends Model{
    constructor(){
        super()
    }
}

User.init({
    id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true
    },
    user_id:{
        type:DataTypes.STRING
    },
    user_name:{
        type:DataTypes.STRING
    },
    user_email:{
        type:DataTypes.STRING
    },
    user_type:{
        type:DataTypes.INTEGER
    },
    active:{
        type:DataTypes.BOOLEAN
    },
    avatar:{
        type:DataTypes.STRING
    },
    discriminator:{
        type:DataTypes.STRING
    }
},{
    sequelize:db,
})

export { User }

service/User.js

import {User as UserModel } from '../db/Model/User.js'
import {Op} from 'sequelize'

const user = UserModel.findOne()

console.log(user)

User {
  dataValues: { id: null },
  _previousDataValues: {},
  uniqno: 1,
  _changed: Set(0) {},
  _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
  isNewRecord: true
}

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [x] Yes. This issue only applies to the following dialect(s):sqlite
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by FeiBam** [comment]
> ## Issue Creation Checklist
> [x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)
> 
> ## Issue Description
> A class inheriting from Model will not serialize data correctly if calling super
> 
> ### Additional context
> I created a new class called User which extend Model I called super inside the constructor of the User class Then the data will not be serialized correctly it is bug?
> 
> Model/User.js: 
``` javascript
 class User extends Model{ constructor(){ super() } }
> 
> User.init({ id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true }, user_id:{ type:DataTypes.STRING }, user_name:{ type:DataTypes.STRING }, user_email:{ type:DataTypes.STRING }, user_type:{ type:DataTypes.INTEGER }, active:{ type:DataTypes.BOOLEAN }, avatar:{ type:DataTypes.STRING }, discriminator:{ type:DataTypes.STRING } },{ sequelize:db, })
> 
> export { User }
> ```
> service/User.js
> 
> import {User as UserModel } from '../db/Model/User.js' import {Op} from 'sequelize'
> 
> const user = UserModel.findOne()
> 
> console.log(user)
> 
> User { dataValues: { id: null }, _previousDataValues: {}, uniqno: 1, _changed: Set(0) {}, _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' }, isNewRecord: true }
> 
> ## Issue Template Checklist
> ### Is this issue dialect-specific?
> * [ ]  No. This issue is relevant to Sequelize as a whole.
> * [x]  Yes. This issue only applies to the following dialect(s):sqlite
> * [ ]  I don't know.
> 
> ### Would you be willing to resolve this issue by submitting a Pull Request?
> * [ ]  Yes, I have the time and I know how to start.
> * [ ]  Yes, I have the time but I don't know how to start, I would need guidance.
> * [ ]  No, I don't have the time, although I believe I could do it if I had the time...
> * [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by FeiBam** [comment]
> ## Issue Creation Checklist
> [x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)
> 
> ## Issue Description
> A class inheriting from Model will not serialize data correctly if calling super
> 
> ### Additional context
> I created a new class called User which extend Model I called super inside the constructor of the User class Then the data will not be serialized correctly it is bug?
> 
> Model/User.js: 
``` javascript
class User extends Model{ constructor(){ super() } }
> 
> User.init({ id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true }, user_id:{ type:DataTypes.STRING }, user_name:{ type:DataTypes.STRING }, user_email:{ type:DataTypes.STRING }, user_type:{ type:DataTypes.INTEGER }, active:{ type:DataTypes.BOOLEAN }, avatar:{ type:DataTypes.STRING }, discriminator:{ type:DataTypes.STRING } },{ sequelize:db, })
> 
> export { User }
```
> service/User.js

``` javascript
> import {User as UserModel } from '../db/Model/User.js' import {Op} from 'sequelize'
> 
> const user = UserModel.findOne()
> 
> console.log(user)
```
> User { dataValues: { id: null }, _previousDataValues: {}, uniqno: 1, _changed: Set(0) {}, _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' }, isNewRecord: true }
> 
> ## Issue Template Checklist
> ### Is this issue dialect-specific?
> * [ ]  No. This issue is relevant to Sequelize as a whole.
> * [x]  Yes. This issue only applies to the following dialect(s):sqlite
> * [ ]  I don't know.
> 
> ### Would you be willing to resolve this issue by submitting a Pull Request?
> * [ ]  Yes, I have the time and I know how to start.
> * [ ]  Yes, I have the time but I don't know how to start, I would need guidance.
> * [ ]  No, I don't have the time, although I believe I could do it if I had the time...
> * [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by FeiBam** [comment]
i am sure the database haved data

**Comment by ephys** [comment]
You most likely need to pass the data up from the constructor:

```
 constructor(...args){
    super(...args)
   } 
```

**Comment by FeiBam** [comment]
So actually sequelize internally returns a new instantiated UserModel

now i understand why the data not be correctly sequelize  
Thank you
