### ISSUE TITLE
Mode.validate function return Promise<void> Type

### ISSUE THREAD

**Issue by leungtinyau27m5** [sequelize/sequelize#14515]
I am using Sequelize with TypeScript, and I encounter and TypeError that **validate() funciton in Model** is marked as return **Promise\<void\>** which is not align with the actual runtime result and the comments in doc.

**Comment by ephys** [comment]
Checking its implementation, it does return `Promise<void>`, what return value are you getting? Which Sequelize version are you using?

**Comment by leungtinyau27m5** [comment]
> Checking its implementation, it does return `Promise<void>`, what return value are you getting? Which Sequelize version are you using?

^6.19.1 , oh i find out that the error message is returned with .catch. thanks, i made i stupid mistake
