### ISSUE TITLE
[v6] raw query replacements - semicolon terminated fields not being replaced

### ISSUE THREAD

**Issue by Azerothian** [sequelize/sequelize#14517]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** [LINK-HERE](https://github.com/Azerothian/replacements-bug)

### What do you expect to happen?

if the replacement variable is at the end of a SQL statement and it is directly terminated with a semicolon it should still replace the variable. (works in 6.19.0 and below)

```
  await sequelize.query(`UPDATE "foo" SET "name" = :newName;`, {
    replacements: {
      newName: "Working"
    }
  });
[Sequelize] Executed (default): UPDATE "foo" SET "name" = 'Working'; [Elapsed time: 0 ms] 
```

### What is actually happening?

It ignores the field and attempts to run the query and crashes out

```
  await sequelize.query(`UPDATE "foo" SET "name" = :newName;`, {
    replacements: {
      newName: "Working"
    }
  });
[Sequelize] Executed (default): UPDATE "foo" SET "name" = :newName; [Elapsed time: 0 ms] 
```

### Environment
- Sequelize version: 6.19.1
- Node.js version: v16.13.2
- Database & Version: postgres 13

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Azerothian** [comment]
Seems to be introduced with this pull request https://github.com/sequelize/sequelize/pull/14472

**Comment by ephys** [comment]
On it :)

**Comment by ephys** [comment]
PR: https://github.com/sequelize/sequelize/pull/14518

**Comment by ephys** [comment]
Fix released
