### ISSUE TITLE
`findOne` logic for adding `limit: 1` led to severe performance degredation.

### ISSUE THREAD

**Issue by rharriso** [sequelize/sequelize#14548]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Misuse of `@Unique` annotation in `seqsequelize-typescript` triggered a condition in `findOne` that lead to ALL rows being queried, rather than halting after a single row was retrieved. The invalid "uniqueness" of the column caused the `findOne` method to omit the `LIMIT 1` clause causing ALL of the matching rows to be queried.

Foreign keys should be used to ensure data integrity, and should not impact query performance. It's unclear how omitting `LIMIT 1` benefits any query that should return a single result.

### SSCCE

```ts
export class APITransaction extends Model<IAPITransactionAttributes> {
  @ForeignKey(() => APIUser)
  @Unique // should not be here, foreign key is not actually unique
  @AllowNull(false)
  @NotEmpty
  @Column({
    type: DataType.STRING,
  })
  apiUserId: string;
}

// selects and sorts 50k results just to get a single value.
const apiTx = await APITransaction.findOne({
    where: { apiUserId: apiUser.slug },
    order: [['createdAt', 'DESC']]
});
```

### What do you expect to happen?

`findOne` should **always** select a single row from the database

### What is actually happening?

In the case outlined above, `findOne` would query for **every** row matching the where clause, then return the first.
This led to rapidly degrading query performance and cascading problems as application servers failed over. The databases because saturated with abandoned connections. Application servers thrashed. Database and Application servers failed over under modest load.

### Additional context

This issue was eventually resolved after reviewing the slow query log, and replacing all uses of `findOne` with `findAll({ limit: 1})`. It was not detectable until the row count that matched the where clause reached > 10k. 

We also resolved the misuse of `@Unique` in our own code base.

### Environment

- Sequelize version: 6.8
- Node.js version: 16
- If TypeScript related: TypeScript version: 
- Database & Version: PSQL 13
- Connector library & Version: 

## Would you be willing to resolve this issue by submitting a Pull Request?

Yes, coming shortly.

**Comment by WikiRik** [comment]
No worries, let us know in the PR if there's something we can help you with

**Comment by WikiRik** [comment]
Yeah, we updated some files in the dev folder. Merging main into your branch should work

**Comment by rharriso** [comment]
🥳

**Comment by WikiRik** [comment]
The PR has been merged so I'll close this issue
