### ISSUE TITLE
Running raw complicated queries with sequelize

### ISSUE THREAD

**Issue by monishgithub** [sequelize/sequelize#14559]
I have a peculiar problem. I have a joined query due to the distribution of data in various table. I want to run this as raw sql query using node module for sequelize as alot existing code is associated using sequelize orm. I do not want to use orm here but just a plain raw query. The packages are     "sequelize": "^4.44.4",
    "sequelize-auto": "^0.4.29",
    "sequelize-cli": "^4.1.1",

    SELECT testmodel.bacode, testmodel2.paopkey from (SELECT ptr.paopkey as paopkey, psgkey.pskey from (SELECT * FROM	pts where paopkey = 4 and ptr_active = 1) ptr,
    pt_sg psgkey where ptr.pkey = psgkey.pkey) testmodel2,
    pt_act testmodel where testmodel.pskey =  testmodel2.pskey;

Any advise if the above query can be run as raw query and the data can be captured as result.
Also when I run the below code with below sequelize code, I get 
the error **"_sequelize.default.query is not a function"**. I have also created a connection with sequelize the db and it still shows the same error.  "**_datasource.default.getDBClient.query is not a function**"

    import Sequelize from 'sequelize';
    async function getTestDataList(opcoKey) {
      const testdata = await Sequelize.query(`SELECT testmodel.bacode, testmodel2.paopkey from (SELECT ptr.paopkey as paopkey, psgkey.pskey from (SELECT * FROM	pts where paopkey = 4 and ptr_active = 1) ptr,
      pt_sg psgkey where ptr.pkey = psgkey.pkey) testmodel2,
      pt_act testmodel where testmodel.pskey =  testmodel2.pskey;`, 
      { type: Sequelize.QueryTypes.SELECT }).then(function (results) {
         // SELECT query - use then
      })
      return toPlain(testdata);
    }

**Comment by ephys** [comment]
You're using the Sequelize class. [`query`](https://sequelize.org/api/v7/classes/sequelize#query) is a method on Sequelize instances

**Comment by monishgithub** [comment]
I know that, I even tried it with instance and it still gave it. Pls dont close the ticket without answering the questions
