### ISSUE TITLE
Postgres HSTORE querying

### ISSUE THREAD

**Issue by tomchentw** [sequelize/sequelize#1456]
As describe in [doc](http://www.postgresql.org/docs/9.1/static/hstore.html).
It seems that `sequelize` doesn't provide a query interface for HSTORE. 

I'm using stable `1.7.0`, and the following code won't work:
```livescript
  User.findOrCreate github: profile{id}, do
    username:     profile.username
    displayName:  profile.displayName
    email:        profile.emails.0.value
    github: do
      id:           profile.id
  .then done
```
Will result in: 
```
Executing (default): SELECT * FROM "Users" WHERE "Users"."github"  922234 LIMIT 1;
Possibly unhandled error: syntax error at or near "922234"
```

**Comment by BridgeAR** [comment]
I guess this should be closed. There is [pg-hstore] (https://github.com/scarney81/pg-hstore) if anyone wants to parse hstores by himself. Everything in sequelize handles hstores properly, so the use case is probably obsolete?

**Comment by janmeier** [comment]
Just tested this, and HSTORE querying works fine

**Comment by tomchentw** [comment]
Cool! :+1:
