### ISSUE TITLE
Replacement issue with 6.20.0

### ISSUE THREAD

**Issue by jiqiang90** [sequelize/sequelize#14568]
Hi,

When i'm trying to create a query like this 

`COMMENT ON TYPE "query-registry-subquery-project_enum_167d3578e1" IS E'@enum\n@enumName Status'`

And we are trying to use the replace the question mark here to `comment`

```
  const comment = `@enum\\n@enumName ${e.name}${
    e.description ? `\\n ${e.description}` : ''
  }`;

  await this.sequelize.query(`COMMENT ON TYPE "${enumTypeName}" IS E?`, {
    replacements: [comment],
  });
```

In the version 6.19.0 it was working fine, but in 6.20.0 if will query `COMMENT ON TYPE “${enumTypeName}” IS E?`, appears the replacement failed. 

Just need to confirm this is due to the replacement update in new release? or it should be written in another way, please advice. Thanks

**Comment by ephys** [comment]
Are you using an E-prefixed string for `\n`?

I would recommend removing the E prefix as SQL strings can contain a new line

Simplified example:

```typescript
const comment = `@enum\n@enumName ${e.name}`;

await this.sequelize.query(`COMMENT ON TYPE "${enumTypeName}" IS ?`, {
  replacements: [comment],
});
```

should result in 

```sql
COMMENT ON TYPE "myEnumType" IS '@enum
@enumName theName'
```

Unless there is a bug, which we can fix

**Comment by jiqiang90** [comment]
Thank you @ephys , yes we are trying to have the E-prefixed string for Escape. Does sequelize query will escape string by default? If yes we can remove the prefixed string.

**Comment by ephys** [comment]
Replacements are escaped by sequelize. In fact, it's likely that using an E prefix in front of the string generated by Sequelize could have lead to an SQL injection because sequelize would not have escaped `\'` correctly (as it assumes standard strings)

Let me know if you're encountering an issue if you remove the E prefix. Don't forget to remove the escape in `\\n` too :)

**Comment by ephys** [comment]
I'll close as this is actually working as intended
