### ISSUE TITLE
Different amount of rows returned with generated raw query

### ISSUE THREAD

**Issue by maduq1** [sequelize/sequelize#14588]
Hi, I am experiencing a weird issue, maybe I am forgetting a setting, but so far sequelize worked great with the rest of models we have.

We are using Sequelize `6.19.0`, by the way in a `node 16.13.0` environment.

The thing is, we are running the following command:
```
const unitRetentions = await Retention.findAll({
    include: [
      {
        model: Admin,
        as: 'Admin',
        required: false, // left join
        attributes: [],
      },
    ],
    attributes: {
      include: [
        [sequelize.col("Admin.unit"), 'unit'],
        [sequelize.col("Retention.profile_time"), 'profile_time'],
        [sequelize.col("Retention.profile_type"), 'profile_type'],
        [sequelize.col("Retention.transaction_time"), 'transaction_time'],
        [sequelize.col("Retention.transaction_type"), 'transaction_type'],
        [sequelize.col("Retention.countrycode"), 'countrycode']
      ]
    }
  })
```

The relations between the two models are defined like this:

```
Admin.hasOne(Retention, {
  foreignKey: 'countrycode',
  sourceKey: 'countrycode',
  onDelete: 'NO ACTION',
  onUpdate: 'NO ACTION'
})

Retention.hasMany(Admin, {
  as: 'Admin',
  foreignKey: 'countrycode',
  sourceKey: 'countrycode',
  onDelete: 'NO ACTION',
  onUpdate: 'NO ACTION'
})
```

The sequelize command generates the following query: `SELECT "Retention"."countrycode", "Retention"."updated_at", "Retention"."updated_by", "Retention"."image_transaction", "Retention"."image_time", "Retention"."image_type", "Retention"."profile_time", "Retention"."profile_type", "Retention"."transaction_time", "Retention"."transaction_type", "Admin"."unit" AS "unit", "Retention"."profile_time" AS "profile_time", "Retention"."profile_type" AS "profile_type", "Retention"."transaction_time" AS "transaction_time", "Retention"."transaction_type" AS "transaction_type", "Retention"."countrycode" AS "countrycode" FROM "retention" AS "Retention" LEFT OUTER JOIN "admin" AS "Admin" ON "Retention"."countrycode" = "Admin"."countrycode";`

When checking the logs, it's returning less rows than expected. The funny thing is that if I copy the generated SQL query above and run it against the same server, I get more rows.

This the expected result (the one we get when running the raw query):

```
[
  {
    countrycode: 'ZE',
    unit: null,
    profile_time: 3,
    profile_type: 'years',
    transaction_time: 1,
    transaction_type: 'years'
  },
  {
    countrycode: 'SE',
    unit: 'STO.719',
    profile_time: 30,
    profile_type: 'days',
    transaction_time: 30,
    transaction_type: 'days'
  },
  {
    countrycode: 'SE',
    unit: 'STO.888',
    profile_time: 30,
    profile_type: 'days',
    transaction_time: 30,
    transaction_type: 'days'
  },
  {
    countrycode: 'SE',
    unit: 'STO.720',
    profile_time: 30,
    profile_type: 'days',
    transaction_time: 30,
    transaction_type: 'days'
  }
]
```

And this is the one we get when using the Sequelize command stated above:

```
[{
  countrycode: 'ZE',
  profile_time: 3,
  profile_type: 'years',
  transaction_time: 1,
  transaction_type: 'years',
  unit: null
},
{
  countrycode: 'SE',
  profile_time: 30,
  profile_type: 'days',
  transaction_time: 30,
  transaction_type: 'days',
  unit: 'STO.719'
}]
```

What strikes me interesting is that the "wrong" result returns one row per "countrycode"; but we are expecting to receive one row for 'ZE' and three rows for 'SE'.

Is there some option I am missing when running the sequelize command?

Thank you very much in advance!

**Comment by Jopchumba** [comment]
@maduq1 sounds interesting with the include can you run with the option findall having required set to true.
Also, read about the idea of nesting.
`   model: Admin,
        as: 'Admin',
        required: false, // left join
        attributes: [],`
