### ISSUE TITLE
Patch dependency with CVSS High Vulnerability older than 30 days on v6

### ISSUE THREAD

**Issue by joseph-lorenzo** [sequelize/sequelize#14606]
## Issue Creation Checklist

[X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

The PR https://github.com/sequelize/sequelize/pull/14351 updates a dependency (moment 2.29.1 -> 2.29.2, moment 2.29.3 is available) that has a CVSS High vulnerability on v7.

It's been more than 30 days since discovery and proper patching on moment, which is the consensus remediation timeline to fix CVSS >= 7 issues, and it seems v7 won't be around for a while. We already had two minors and two patch versions since then, can we patch this same PR or another one with the newer moment into v6?

Thank you

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
Feel free to make a new PR but since `moment` is not pinned you should get the latest patch version when you are updating your dependencies.

**Comment by joseph-lorenzo** [comment]
> Feel free to make a new PR but since `moment` is not pinned you should get the latest patch version when you are updating your dependencies.

I'm taking some more time reading the pros and cons of having .lock versioned, from what I understand for the sequelize community it is indifferent :)

Thank you for the info!
