### ISSUE TITLE
Query gets mangled when using function inside where

### ISSUE THREAD

**Issue by alecrobertson1** [sequelize/sequelize#14600]
## Issue Creation Checklist

- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When using sequelize.fn inside sequelize.where, the output query gets mangled.

### SSCCE

**Here is the link to the SSCCE for this issue:** N/A

### What do you expect to happen?

The query to be output normally and work correctly.

### What is actually happening?

The query is mangled and fails because it refers to columns which don't exist.

```
sql: `SELECT "TABLE_ID" AS "Id" FROM "SNOWFLAKE" AS "table" WHERE "table"."attribute" = ST_DWITHIN(ST_MAKEPOINT(0, 0), ST_MAKEPOINT(1,0), 150000) AND "table"."comparator" = '=' AND "table"."logic" = 'true';`
```

### Additional context

If you use [Op.and] the issue goes away. I believe this issue is identical to this one which was fixed - https://github.com/sequelize/sequelize/issues/6440 - but the issue has returned.

If you use [Op.and], the query works and looks as follows:

```
sql: `SELECT "TABLE_ID" AS "Id" FROM "SNOWFLAKE" AS "table" WHERE ST_DWITHIN(ST_MAKEPOINT(0, 0), ST_MAKEPOINT(1,0), 150000) = 'true';`
```

Broken code:

```js
sequelize.where(
          sequelize.fn(
            'ST_DWithin',
            sequelize.literal('ST_Point(0, 0)'),
            sequelize.literal(
              `ST_Point(1,0)`
            ),
            150000
          ),
          'true'
        )
```

Working code:

```js
[Op.and]: sequelize.where(
          sequelize.fn(
            'ST_DWithin',
            sequelize.literal('ST_Point(0, 0)'),
            sequelize.literal(
              `ST_Point(1,0)`
            ),
            150000
          ),
          'true'
        )
```

### Environment

- Sequelize version: 6.20.1
- Node.js version: 14.19.3
- If TypeScript related: TypeScript version: 4.6.4
- Database & Version: Snowflake Data Cloud
- Connector library & Version: N/A

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Hi! Could you show the rest of your query, we need to see where `where()` is being used

**Comment by alecrobertson1** [comment]
@ephys, what I am trying to do is build up three filters that can be used all together, just one, just two etc.

So I construct the filters as follows:

**Comment by ephys** [comment]
I should have been clearer about what I meant, we need a full example that uses the minimal amount of code necessary.

Replicating the issue with the minimum necessary amount of code using https://github.com/sequelize/sequelize-sscce is the best way to ensure we can take the time to review it.
