### ISSUE TITLE
Attribute scoping proposal

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#1462]
*Taking naming suggestions, 'scope' might confuse with Model.scope*

Allow users to scope attributes for retrieval when using get() & toJSON().

**Defining 'scopes' on attributes:**

 ```
sequelize.define('User', {
  email: {
    type: DataTypes.STRING,
    scopes: ['self'],
  },
  name: {
    type: DataTypes.STRING,
    scopes: ['self', 'public']
  },
  title: {
    type: DataTypes.STRING // No scopes is default all scopes
  },
  parent_id: {
    type: DataTypes.INTEGER,
    scopes: false||[] // Don't EVER include
  }
});
```

**Defining attributes in scope:**
```js
// found some user
var values = user.get({scope: 'public'}); // {name: someValue, title: someValue}
var values = user.get({scope: 'self'}); // {email: someValue, email: someValue, title: someValue}
```

*WIP*

**Comment by mickhansen** [comment]
This is easily implemented as a plugin so we have decided not to implement it in core.
I personally need this so i'm developing an implementation here: https://github.com/mickhansen/ssacl-attribute-roles (as of writing, only `.get()` support - since that's where most of my usecases live, .set() to follow soon).

**Comment by diosney** [comment]
+1

@mickhansen This is a so needed feature in almost all systems, that I think it should be in the core, or at least a plugin with a strong support by the core sequelize developers.

Something as the mongoose [`.select()`](http://mongoosejs.com/docs/api.html#query_Query-select ) method would be awesome, since there are occasions when an attribute filtering needs to be made without having to specify it at the Model definition level, but for specific queries.

**Comment by mickhansen** [comment]
@diosney core sequelize developers = 2 people, one of them is me, so you could say it has strong support ;)

**Comment by diosney** [comment]
@mickhansen haha! good point :smile: 

I will give it a try then.

**Comment by diosney** [comment]
@mickhansen Thanks, it worked like a charm :)

**Comment by pbrain19** [comment]
an ORM that does not allow you exclude fields at its core?

**Comment by mickhansen** [comment]
@pbrain19 It's supported by `attributes`.

**Comment by pbrain19** [comment]
Can you show me where this is documented? Can't seem to find it... do i just put the "-" if i want to exclude?

**Comment by mickhansen** [comment]
@pbrain19 `Model.findAll({attributes: ['...']})` - it simply takes a list of attribute names, use lodash with `Object.keys(Model.rawAttributes)` to do an exclude.

It's not so magic but it can be accomplished in one line of code :)

**Comment by pbrain19** [comment]
@mickhansen so Model.findAll({attributes: ['_DoNotInclude']}) will include all attributes but the DONotInclude?

**Comment by mickhansen** [comment]
@pbrain19 No. `attributes` defines exactly what attributes to load, like my previous comment should have suggested.

**Comment by pbrain19** [comment]
The only way to exclude is to include all the ones you want without the ones you don't? So in essence there is no exclude functionality?

**Comment by pbrain19** [comment]
I only ask because I have very large objects.

**Comment by mickhansen** [comment]
No native exclude at the moment, but it is something we'd like to improve on: https://github.com/sequelize/sequelize/issues/4074
However it can be implemented with three lines of code using the list of existing attributes `Object.keys(Model.rawAttributes)` and a filter (perhaps using lodash) + a find hook.

**Comment by pbrain19** [comment]
I see. thanks

**Comment by Neefay** [comment]
So, any progress with this? I love Sequelize so far, but not being able to filter eager loads or exposing fields is really busting my behind.

**Comment by mickhansen** [comment]
@Neefay It's been decided that it's better off left as a plugin, you can give mine a try.

**Comment by Neefay** [comment]
@mickhansen I'm assuming you refer to [this](https://github.com/mickhansen/ssacl-attribute-roles)? I read the example and it made my head spin for a bit, but I'll take your word for it and dive in deeper. Thank you for your excellent work with Sequelize.

**Comment by mickhansen** [comment]
@Neefay That's the one :)

**Comment by OlivierCuyp** [comment]
For the people that were reading this thread looking for a full exemple (based on [express-exemple](https://github.com/sequelize/express-example)) on how to hide attributes redefining the `toJSON` method:

```js
var _ = require ('lodash');

module.exports = function (sequelize, DataTypes) {
  var schema = {
    name: {
      type: DataTypes.STRING(255),
      allowNull: false
    },
    email: {
      type: DataTypes.STRING(255),
      allowNull: false,
      unique: true
    },
    password: DataTypes.STRING(20)
  };

  var User = sequelize.define('user', schema, {
    instanceMethods: {
      toJSON: function () {
        var privateAttributes = [ 'password' ];

        return _.omit(this.dataValues, privateAttributes);
      }
    }
  });

  return User;
}
```

**Comment by carragom** [comment]
I know it's a bit late but I have a proposal that after reading the Sequelize documentation for the first time it just made sense to me. Actually I went ahead and coded my model first just to find out it did not work :P.

This leaves the matter of access control for another day as suggested many times on this thread and focus only on the possibility to show/hide a column based on scopes. As documented [here](http://docs.sequelizejs.com/en/latest/docs/scopes/) Sequelize already have scopes. So why not enrich that same facility to filter out columns as well as rows?

```javascript
var User = sequelize.define('User', {
  id: DataTypes.INTEGER,
  name: DataTypes.STRING,
  email: DataTypes.STRING,
  active: DataTypes.BOOLEAN,
  password: DataTypes.STRING
}, {
  defaultScope: {
    where: { active: true },
    attributes: ['id', 'name']
  },
  restrictedScope: {
    attributes: {exclude: ['password', 'email']}
  },
  complexScope: {
    attributes: {exclude: ['password'], include: ['name', 'email']}
  }
})
```

This new `attributes` property, if it's an array, it would behave the same as the `attributes` property we already use to filter columns in the query methods [here](http://docs.sequelizejs.com/en/latest/docs/querying/). With the extra functionality of having `include` and `exclude` arrays when it's an object.

This way we can use model scopes not only to filter out rows but columns as well and don't have to repeat those filters on every query method.

**Comment by mickhansen** [comment]
@carragom We've discussed merging exclude/include into attributes with scopes but skipped in the first round since we're not exactly sure what should take precedence (what if a scope applied after another includes something that was excluded etc).

**Comment by carragom** [comment]
Well in that case one of the two should take precedence (i think exclude should) and the behavior should be documented.

But I don't consider this an issue since the same thing can already happen when mixing multiple scopes with conflicting filters, something like this:

```javascript
active: {
  where: {active: true}
},
inactive: {
  where: {active: false}
}
```

In the end it looks like mixing multiple scopes is not a good idea and should be avoided on a general basis.

**Comment by mickhansen** [comment]
@carragom you have to be careful about mixing scopes atleast :)

**Comment by smassin** [comment]
I may be missing something but this doesn't appear to cover the case where you have eager loaded an association for use with processing but don't want it to be returned to the user. However, @OlivierCuyp method does allow you to cover this case.

**Comment by nadapeter** [comment]
@smassin 
There's still a potential loop hole with that implementation if you have nested models.
When you call toJSON() on the original object, the nested models will be returned in plain objects.
Those plain objects may have had their own toJSON() method when it was an instance but now it will be never called.

**Comment by leodutra** [comment]
So, what is the conclusion?
I'm already using the v4 form of `toJSON`:
```js
// ... v4 Model definition
User.prototype.toJSON = function() {
  return _.omit(this.dataValues, 'password');
}
```

Will scopes be usable in attributes or just on model?

**Comment by drunkhacker** [comment]
is still WIP? This would be really useful!

**Comment by nonamez** [comment]
Guys, are you serious?  2 years of discussion on how to hide attributes in model in still no method simply to list attributes in array?

**Comment by mickhansen** [comment]
@nonamez there are plenty of solutions, it's a trivial problem to solve in userland, and there are plugins too.

Most people solve this in their API layer, and that makes a lot more sense too in my opinion.

Please consider your attitude and tone when posting on open source issue trackers.

**Comment by mickhansen** [comment]
https://github.com/mickhansen/ssacl-attribute-roles is an unmaintaned plugin that somewhat does what you need.

I never found a use for it, hence the status of being unmaintained, i believe it's a lot more appropriate to keep presentation logic in your presentational layer (be that a REST API or whatever).

**Comment by nonamez** [comment]
@mickhansen my attitude and tone is ok, just little surprised as such a simple feature need so much work...

My situation is quite simple: I have user model in which I overwrite `toJSON` as suggested above and was surprised when I tried to get all messages from other model and included in it `user` and all my passwords are seen...

So basically I need to add double check in each model that is associated with user model to hide `password` attribute.

**Comment by mickhansen** [comment]
@nonamez I disagree.

Plenty of solutions have been proposed, take your pick.
If i were to make a personal suggestion i'd take a step back and consider why model instances are being piped directly to end users.

**Comment by nonamez** [comment]
@mickhansen Well, as for me, one of the main tasks of ORM is in reducing development time by solving routine tasks. 

For example one of those task is data validation/escape before saving - roughly speaking "data input".

On the "data output" in most cases we just need to return some data adding few `where` statements.

For example users private messages, or users comments, or users posts. And each time when we simply want to get comments for the post we need not forget to do some extra manipulations (which are the same for messages, comments, posts) to exclude sensitive user data.

Why we simple cant define property `hidden: ['password', 'auth_token']` and exclude those items each time when model is called for serialization ?

Why we need to search for some sort of second-hand solutions ? Can we even trust those second-hand solutions?

**Comment by mickhansen** [comment]
@nonamez When asking why a feature doesn't exist you can usually assume the answer is "bloat" or "no one has implemented it".

I've given my personal reasons for why i think such a feature doesn't need to exist, i don't believe more can be added to the discussion.

I'm no longer an active maintainer, but PRs are always given appropriate attention i'm sure. Just remember the one true rule of OSS; "No is temporary, yes is forever".
