### ISSUE TITLE
specifying column names via attributes never excludes primary key

### ISSUE THREAD

**Issue by eshell** [sequelize/sequelize#1468]
I'm running a query...

``` JavaScript
User.findAll({attributes:['name']})...
// i get
// Executing (default): SELECT `username` FROM `Users`;
```

and in my data, i get the primary key field `id` with a value of `null`. 

If I do this same query with a related model and selecting only one attribute for the related model, it always shows the primary key and value for the related model.

So not selecting primary key in `{attributes:[columns]}`, always results in `id` being returned for related models, and an `id` with `null` value for primary model. Is there a way to keep `id` from being returned with data if I don't need/want them? ( I don't believe you need to `select` the primary key to perform a join ). 

[addition] it seems all keys are always shown regardless of `attributes`. I'd definitely prefer not to have this unnecessary data clouding up my json.

ps: i can't find in the docs how to automatically keep attributes from being selected when performing a basic `select *` query. How would I do this?

pss: Keep up the good work on this orm =)

**Comment by tinganho** [comment]
I think I'm still seeing this issue in my include statements:
```typescript
{
     model: User,
     attributes: ['username', 'name'],
}
```

and the `id` field for the user is included.

**Comment by mickhansen** [comment]
@tinganho Yes we to select it for deduplication of the cartesian product. However it should not show up in the final product if you're using `.get()`

**Comment by nicolabortignon** [comment]
How would I remove the Joined table in case of this query?
```

model.Collection.findAll({
      include:  [{
        model: model.Product,
        attributes: ['id','ImageId'],
      },
      {
        model: model.Post,
        attributes: ['id','ImageId'],
      }],
      where: {
       UserId: userId,
      }

```

I basically get this:

`[{"id":6,"displayName":"New Collection 232323","createdAt":"2017-03-08T17:34:56.000Z","updatedAt":"2017-03-08T17:34:56.000Z","UserId":1,"Products":[],"Posts":[{"id":58,"ImageId":14194,"CollectionPost":{"createdAt":"2017-03-08T17:34:57.000Z","updatedAt":"2017-03-08T17:34:57.000Z","CollectionId":6,"PostId":58}}]`

and I just need 

`[{"id":6,"displayName":"New Collection 232323","createdAt":"2017-03-08T17:34:56.000Z","updatedAt":"2017-03-08T17:34:56.000Z","UserId":1,"Products":[],"Posts":[{"id":58,"ImageId":14194}]`

**Comment by mattfysh** [comment]
This also causes issues if trying to use `group` and `separate` on the related model

**Comment by Snelius30** [comment]
> This also causes issues if trying to use `group` and `separate` on the related model

Yes and did not resolved yet.
