### ISSUE TITLE
Model.create() sets auto increment to null

### ISSUE THREAD

**Issue by bennom** [sequelize/sequelize#14706]
## Bug Description

**Attention**: I "migrated" to Sequelize on top of an existing database. I did not create tables with Sequelize nor did I use the migration tools. Additionally, I'm using the TypeScript version for my API (Serverless Framework).

I've got a `Customer` model (see below) that holds simple information. Whenever I'm trying to create a new customer now, I'm getting an error:
```null value in column "id" of relation "customer" violates not-null constraint```

#### The `customer` table in the database
```
CREATE TABLE customer (
  id          SERIAL NOT NULL CONSTRAINT customer_pkey PRIMARY KEY,
  email       VARCHAR(512) NOT NULL CONSTRAINT customer_email_key UNIQUE,
  first_name  VARCHAR(512) NOT NULL,
  last_name   VARCHAR(512) NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

#### The model `Customer.ts`
```
import { DataTypes, InferAttributes, InferCreationAttributes, Model, Sequelize } from 'sequelize'

export class Customer extends Model<InferAttributes<Customer>, InferCreationAttributes<Customer>> {
  declare id: number
  declare email: string
  declare first_name: string
  declare last_name: string
}

export const initCustomer = (sequelize: Sequelize) => {
  Customer.init(
    {
      id: {
        primaryKey: true,
        type: DataTypes.INTEGER,
        autoIncrement: true,
      },

      email: {
        type: DataTypes.STRING(512),
      },

      first_name: {
        type: DataTypes.STRING(512),
      },

      last_name: {
        type: DataTypes.STRING(512),
      },
    },

    {
      tableName: 'customer',
      sequelize,
      underscored: true,
    }
  )
}
```

The `initCustomer()` is getting called after Sequelize and the database is getting initiated with all the credentials etc.

#### In the API endpoint when creating a customer
```
await Customer.create(
  {
    email: 'foo@bar.net',
    first_name: 'foo',
    last_name: 'bar',
  }
)
```

### What do you expect to happen?

Customer is getting created in the database.

### What is actually happening?

When I log the SQL, the following SQL statement is getting generated:
```
sql: INSERT INTO "customer" ("id","email","first_name","last_name","created_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "id","email","first_name","last_name","created_at","updated_at","id";

parameters: [null, "foo@bar.net", "foo", "bar", "2022-07-01 10:00:00.000 +00:00", "2022-07-01 10:00:00.000 +00:00"]
```
... with the Error message `null value in column "id" of relation "customer" violates not-null constrain`.

Interestingly, with a Project model I have it works perfectly fine. It's the same model definition with just `name` as an attribute (and the same `id` column definition of course).

Any ideas? Thanks in advanced, lovely people :)

### Environment

- Sequelize version: 6.21.2
- Node.js version: 14.19.0
- If TypeScript related: TypeScript version:
- @serverless/typescript: 3.0.0
- Database & Version: PostgreSQL 13.4
- Connector library & Version: pg@8.7.3 /  pg-native@3.0.0
---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
I ran the following code and could not reproduce:

```ts
class Customer extends Model<InferAttributes<Customer>, InferCreationAttributes<Customer>> {
  declare id: CreationOptional<number>;
  declare email: string;
  declare first_name: string;
  declare last_name: string;
}

Customer.init(
  {
    id: {
      primaryKey: true,
      type: DataTypes.INTEGER,
      autoIncrement: true,
    },

    email: {
      type: DataTypes.STRING(512),
    },

    first_name: {
      type: DataTypes.STRING(512),
    },

    last_name: {
      type: DataTypes.STRING(512),
    },
  },

  {
    tableName: 'customer',
    sequelize,
    underscored: true,
  },
);

await Customer.sync({ force: true });

await Customer.create({
  email: 'foo@bar.net',
  first_name: 'foo',
  last_name: 'bar',
});
```

`create` logged the following query:

```sql
INSERT INTO "customer" ("id","email","first_name","last_name") VALUES (DEFAULT,$1,$2,$3) RETURNING "id","email","first_name","last_name"; 

-- data: "foo@bar.net", "foo", "bar"
```

The fact that your create set `id` to null instead of `DEFAULT` indicates that there is something wrong with how the model is declared. But the issue isn't present in the code you provided

**Comment by dj0024javia** [comment]
This is happening with me as well. I have a field like this below.
fleet_req_Id: {
          autoIncrement: true,
          type: DataTypes.INTEGER,
          allowNull: false,
          primaryKey: true,
        },

And when i create a record using .create it executes below SQL Query.

Executing (5c4626a2-d38a-41cf-af62-d0eb7519539a): START TRANSACTION;
Executing (default): INSERT INTO `table` (`fleet_req_Id`,...) VALUES (DEFAULT,...);
Executing (5c4626a2-d38a-41cf-af62-d0eb7519539a): COMMIT;

And this is the response i get after insert from sequelize create

data -> {..., "fleet_req_Id": null}

**Comment by ephys** [comment]
I won't be able to help if I can't reproduce this issue

If you can manage to reproduce it using [this SSCCE repository](https://github.com/sequelize/sequelize-sscce), consider opening a new bug report with a link to your SSCCE

**Comment by dj0024javia** [comment]
Sure, will do that. Thanks @ephys

**Comment by Ruumaa** [comment]
I have a similiar problem, so I already set tbe models of the id to autoincrement and primarykey true, and this is the log 
`Executing (default): INSERT INTO "users" ("id","email","gender","password","role") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING "id","email","gender","password","role";
users {
  dataValues: {
    id: null,
    email: 'test@email.com',
    gender: 'unicorn',
    password: 'admin',
    role: 'admin'
  },`
  as you can see, the id set to default but the output is null. Its weird because I did the same thing for another table and its works fine
  this is my code
  controllers file
  `controllers.create = (req, res, next) => {
  const { email, gender, password, role } = req.body;
  if (!email || !gender || !password || !role) {
    res
      .status(400)
      .json({ message: "Email, gender, password, and role are required!" });
  }
  UserService.create(req.body)
    .then((result) => {
      res.status(200).json(result);
    })
    .catch((err) => {
      next(err);
    });
};`
UserService file
`userService.create = async (params) => {
  try {
    const { email, gender, password, role } = params;
    let payload = {
      email,
      gender,
      password,
      role,
    };

    const user = await userRepository.create(payload);
    return user;
  } catch (err) {
    throw err;
  }
};`
repo file
`userRepository.create = async (payload) => {
  try {
    const user = await models.Users.create(payload);
    console.log(user)
    return user;
  } catch (err) {
    throw err;
  }
};`

**Comment by reke592** [comment]
It's possible that the payload you pass in the `create` method has an id parameter. I ran into same problem in my case when the frontend passed a `'null'` string.

**Comment by MiguelG97** [comment]
Same happened to me
![image](https://github.com/sequelize/sequelize/assets/78984964/94da4c89-4b4b-42fb-a89e-763899f9a60e)

![image](https://github.com/sequelize/sequelize/assets/78984964/752f3857-c09d-44d3-a734-7a62798ec36d)

**Comment by MiguelG97** [comment]
somehow it was fixed by adding {force:true} to the sequelize synchronization

also tried re installing the pg and ph-hstore libraries

**Comment by Virgilio-Flores** [comment]
try checking the sequelize model. make sure the autoincrement is set to true:

```typescript
import { DataTypes, Model } from "sequelize";
import { db } from "../config/database";

class Subject extends Model {
  declare subjectId: string;

...

  static associate(models: any) {
    // define association here
    this.hasMany(models.Question, {
      foreignKey: "questionId",
      as: "question",
      onDelete: "cascade",
    });
  }
}

Subject.init(
  {
    subjectId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true, 
      autoIncrement: true, // SET TO TRUE
    },
   ...
  {
    tableName: "Subjects",
    sequelize: db,
  }
);

export default Subject;
```

**Comment by JuniorC07** [comment]
It seems that in my case, I had a User model that previously contained foreign keys. However, these foreign keys were removed, while the associations in other tables were still maintained. This was likely causing the issue I was experiencing. Once I removed the belongsTo and belongsToMany relationships related to the removed foreign keys, everything started functioning correctly again.



### Example

Here's a simplified example using Sequelize:

#### Before Changes

```javascript
// User.js (Model)
const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/database');

class User extends Model {}

User.init({
  // Define attributes
  name: {
    type: DataTypes.STRING,
    allowNull: false
  }
}, { sequelize, modelName: 'user' });

// Post.js (Model)
class Post extends Model {}

Post.init({
  // Define attributes
  title: {
    type: DataTypes.STRING,
    allowNull: false
  },
  userId: {
    type: DataTypes.INTEGER,
    references: {
      model: User,
      key: 'id'
    }
  }
}, { sequelize, modelName: 'post' });

// Associations
User.hasMany(Post, { foreignKey: 'userId' });
Post.belongsTo(User, { foreignKey: 'userId' });
```

#### Issue

After removing the foreign key from the `users` table (e.g., `userId`), the association in the `Post` model still existed, leading to errors.

#### After Changes

```javascript
// User.js (Model)
const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/database');

class User extends Model {}

User.init({
  // Define attributes
  name: {
    type: DataTypes.STRING,
    allowNull: false
  }
}, { sequelize, modelName: 'user' });

// Post.js (Model)
class Post extends Model {}

Post.init({
  // Define attributes
  title: {
    type: DataTypes.STRING,
    allowNull: false
  }
  // Removed the userId field
}, { sequelize, modelName: 'post' });

// Associations
User.hasMany(Post, { foreignKey: 'userId' });
// Removed Post.belongsTo(User);
```

By removing the outdated `belongsTo` association in the `Post` model and the related foreign key, the application began to work correctly again.
