### ISSUE TITLE
I am getting the same error, please help me out.

### ISSUE THREAD

**Issue by Ravi1717** [sequelize/sequelize#14722]
I am getting the same error, please help me out.

exports.registerSubAdmin = async (req, res) => {
  const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).send({ errors: errors.array() });
    }
    try {
  const result = await db.sequelize.transaction(async (transact) => {
  const { token } = req.params;
  const { email, name, newPassword,confirmPassword, phone, profile_photo, } = req.body;

  jwt.verify(token, config.secret, async(err, verifiedJwt) => {
    if(err)
     return res.status(400).send({
        status:{
          "msg": "Token in Invalid! Please resend the link.",
          "action_status": false
      }
      });

      let user = await db.User.findOne({ where: { email } },{transaction: transact});
       if (user) {
        return res.status(400).send({
          status:{
            "msg": "Email already registered. Please use different email.",
            "action_status": false
        }
        });
     }

      if (newPassword !== confirmPassword) {
       return res.status(400).send({
          status:{
            "msg": "Password does not match.",
            "action_status": false
        }
        });
      }
      let newPasswordHash = await bcrypt.hash(newPassword, 10);
      let result =  await db.User.create({ 
        name: name,
        email:email,
        password: newPasswordHash, 
        phone: phone,
        role:"sub admin",
        profile_photo:profile_photo 
      }, {transaction: transact});
      if (result) {
        return res.status(200).send({
          status:{
            "msg": "Sub Admin registration successfull!",
            "action_status": true
        },
        });
      }
  });
});
    } catch (error) {
      res.status(500).send({
      status: 'Failed',
      message: error.message,
      data: null,
      description: error,
    });
    }
};

_Originally posted by @Ravi1717 in https://github.com/sequelize/sequelize/issues/7525#issuecomment-1176243432_

**Comment by ephys** [comment]
Closing as the content is invalid (please use our issue templates) and resolved as per https://github.com/sequelize/sequelize/issues/7525#issuecomment-1177650892
