### ISSUE TITLE
The = sign was not checked in the first parameter when selecting date intervals

### ISSUE THREAD

**Issue by Nef007** [sequelize/sequelize#14730]
The = sign was not checked in the first parameter when selecting date intervals

`    const  divisionDoc = await dbSeq.sequelize.query('SELECT * FROM "files_doc" AS "files_doc" 
      WHERE (date("files_doc"."createdAt") >= '2022-01-10' AND date("files_doc"."createdAt") <= '2022-07-05') ;',
                {
                    type: QueryTypes.SELECT,
                    logging: console.log
                }
            );`

 Executing (default): SELECT * FROM "files_doc" AS "files_doc" WHERE (date("files_doc"."createdAt") >= '2022-01-10' AND date("files_doc"."createdAt") <= '2022-07-05') ;

i am getting different data when doing query through PgAdmin and Sequalize

DataBase: PostgreSQL v14
Server: Node js v16.15.0
sequelize: "^6.6.2"

**Comment by ephys** [comment]
Hi! We get a lot of issues which takes a very long time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

You can edit this issue and ping us, and we will re-review.

If this is not about a bug report or a feature request, prefer instead:

- StackOverflow: https://stackoverflow.com/questions/tagged/sequelize.js
- GitHub discussions: https://github.com/sequelize/sequelize/discussions
- Slack: https://sequelize-slack.herokuapp.com/
