### ISSUE TITLE
Not covered QueryInterface.select() description in v6 Api docs

### ISSUE THREAD

**Issue by koenigstag** [sequelize/sequelize#14761]
## Issue Creation Checklist

- [x]  I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

Not covered QueryInterface.select() description in v6 Api docs

#### Table
public
async select(model: [Model](https://sequelize.org/api/v6/class/src/model.js~Model.html) | [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Null), tableName: [string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), options: [object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)): [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

Returns selected rows

#### Params:
Name model
Type [Model](https://sequelize.org/api/v6/class/src/model.js~Model.html) | [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Null)
Attribute 
Description model class

Name tableName
Type [string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)
Attribute
Description Name of table to select

Name options
Type [object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)
Attribute optional
Description query options with where

#### Example:
```js
queryInterface.select(null, 'Users', {
  attributes: ['name', 'age', 'address'],
  where: {
    age: {
      [Sequelize.Op.gt]: 18,
    },
  },
});
```

**Comment by ephys** [comment]
`QueryInterface.select` is not a public API yet, which is why it was never documented. We're working on making all available methods of that class public in v7, but this one isn't one of them yet
