### ISSUE TITLE
moment:2.29.2 vulnerability please patch to 2.29.4

### ISSUE THREAD

**Issue by n8ores** [sequelize/sequelize#14768]
moment:2.29.2 contains a vulnerability that will cause most security scanners to flag (as it's high).

**Details here:** https://github.com/advisories/GHSA-wc69-rhjr-hc9g

Sequelize should patch momentjs to version 2.29.4 as soon as possible.

**Comment by WikiRik** [comment]
I've made a PR for renovate to also check the v6 branch, but since we have not pinned `moment` in our dependencies you will get 2.29.4 when re-installing the dependencies. Therefore I will close this issue.
