### ISSUE TITLE
Add option to retry transaction

### ISSUE THREAD

**Issue by jValdron** [sequelize/sequelize#1478]
Hey guys,

I received an automated error from my staging server the other day with a ER_LOCK_DEADLOCK error.

That server is running MySQL on Amazon RDS. Here's the full error log:

``` json
{"date":"Thu Feb 27 2014 18:15:56 GMT+0000 (UTC)","process":{"pid":5629,"uid":0,"gid":0,"cwd":"/srv/www/di_api/releases/20140226211654","execPath":"/usr/local/bin/node","version":"v0.10.25","argv":["/usr/local/bin/node","/srv/www/di_api/current/server.js"],"memoryUsage":{"rss":323936256,"heapTotal":262785344,"heapUsed":179888024}},"os":{"loadavg":[0.1748046875,0.06005859375,0.05859375],"uptime":679004.790621176},"trace":[{"column":14,"file":"/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/sequences/Sequence.js","function":"Query.Sequence._packetToError","line":30,"method":"Sequence._packetToError","native":false},{"column":18,"file":"/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/sequences/Query.js","function":"Query.ErrorPacket","line":82,"method":"ErrorPacket","native":false},{"column":24,"file":"/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Protocol.js","function":"Protocol._parsePacket","line":197,"method":"_parsePacket","native":false},{"column":12,"file":"/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Parser.js","function":"Parser.write","line":62,"method":"write","native":false},{"column":16,"file":"/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Protocol.js","function":"Protocol.write","line":37,"method":"write","native":false},{"column":26,"file":"stream.js","function":"Socket.ondata","line":51,"method":"ondata","native":false},{"column":20,"file":"events.js","function":"Socket.EventEmitter.emit","line":117,"method":"EventEmitter.emit","native":false},{"column":14,"file":"_stream_readable.js","function":"","line":746,"method":null,"native":false},{"column":17,"file":"events.js","function":"Socket.EventEmitter.emit","line":92,"method":"EventEmitter.emit","native":false},{"column":10,"file":"_stream_readable.js","function":"emitReadable_","line":408,"method":null,"native":false},{"column":null,"file":"    --------------------","function":null,"line":null,"method":null,"native":null},{"column":26,"file":"/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Protocol.js","function":"Protocol._enqueue","line":110,"method":"_enqueue","native":false},{"column":25,"file":"/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/Connection.js","function":"Connection.query","line":148,"method":"query","native":false},{"column":34,"file":"/srv/www/di_api/releases/20140226211654/node_modules/newrelic/lib/instrumentation/mysql.js","function":"","line":61,"method":null,"native":false},{"column":17,"file":"/srv/www/di_api/releases/20140226211654/node_modules/newrelic/node_modules/continuation-local-storage/context.js","function":"","line":62,"method":null,"native":false},{"column":63,"file":"/srv/www/di_api/releases/20140226211654/node_modules/newrelic/lib/transaction/tracer.js","function":"Connection.wrapSegmentInvocation [as query]","line":178,"method":"wrapSegmentInvocation [as query]","native":false},{"column":17,"file":"/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/dialects/mysql/query.js","function":"module.exports.Query.run","line":26,"method":"exports.Query.run","native":false},{"column":23,"file":"/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/dialects/mysql/connector-manager.js","function":"","line":410,"method":null,"native":false},{"column":15,"file":"/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/emitters/custom-event-emitter.js","function":"","line":105,"method":null,"native":false},{"column":17,"file":"events.js","function":"EventEmitter.emit","line":95,"method":"emit","native":false},{"column":33,"file":"/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/emitters/custom-event-emitter.js","function":"module.exports.CustomEventEmitter.emit","line":61,"method":"exports.CustomEventEmitter.emit","native":false}],"stack":["Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction","    at Query.Sequence._packetToError (/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14)","    at Query.ErrorPacket (/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)","    at Protocol._parsePacket (/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Protocol.js:197:24)","    at Parser.write (/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Parser.js:62:12)","    at Protocol.write (/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Protocol.js:37:16)","    at Socket.ondata (stream.js:51:26)","    at Socket.EventEmitter.emit (events.js:117:20)","    at Socket.<anonymous> (_stream_readable.js:746:14)","    at Socket.EventEmitter.emit (events.js:92:17)","    at emitReadable_ (_stream_readable.js:408:10)","    --------------------","    at Protocol._enqueue (/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/protocol/Protocol.js:110:26)","    at Connection.query (/srv/www/di_api/releases/20140226211654/node_modules/mysql/lib/Connection.js:148:25)","    at Connection.<anonymous> (/srv/www/di_api/releases/20140226211654/node_modules/newrelic/lib/instrumentation/mysql.js:61:34)","    at Connection.<anonymous> (/srv/www/di_api/releases/20140226211654/node_modules/newrelic/node_modules/continuation-local-storage/context.js:62:17)","    at Connection.wrapSegmentInvocation [as query] (/srv/www/di_api/releases/20140226211654/node_modules/newrelic/lib/transaction/tracer.js:178:63)","    at module.exports.Query.run (/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/dialects/mysql/query.js:26:17)","    at Function.<anonymous> (/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:410:23)","    at null.<anonymous> (/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/emitters/custom-event-emitter.js:105:15)","    at EventEmitter.emit (events.js:95:17)","    at module.exports.CustomEventEmitter.emit (/srv/www/di_api/releases/20140226211654/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)"]}
```

No user actually reported an error, but I got this exception. It's obviously due to transactions or something, but I'm not using transactions explicitly. Anyone has a clue about why this would happen?

**Comment by lloydw** [comment]
According to Mysql docs deadlocks are expected:
> Deadlocks are a classic problem in transactional databases, but they are not dangerous unless they are so frequent that you cannot run certain transactions at all. Normally, you must write your applications so that they are always prepared to re-issue a transaction if it gets rolled back because of a deadlock.

From: https://dev.mysql.com/doc/refman/5.6/en/innodb-deadlocks.html

I've modified the mysql query class to cope with deadlock errors and retry them if you're interested in pulling it into sequelize I'm happy to write a unit test and create a pull request.

The change is here: https://github.com/lloydw/sequelize/commit/f16c7133adb84dcf28e8ad2e510ccfb475a79b7f

**Comment by mickhansen** [comment]
@lloydw That might be interesting to implement across all dialects, probably with a `retries` flag for each query or similar.

**Comment by janmeier** [comment]
According to the quote you posted, the transaction, and not just the query that caused the deadlock, must be retried

**Comment by lloydw** [comment]
That's true, I haven't needed to do that as I'm not currently requiring transactions.

I guess that makes it a lot more tricky to solve in a general way

**Comment by janmeier** [comment]
I guess we could save a history of queries executed on each transaction object - its not very pretty, but I don't think we can do better. 

For autocallback only could argue that we can rerun the callback function, but I don't believe this will be viable, because that function might not be free of side-effects

**Comment by mdarveau** [comment]
"I guess we could save a history of queries executed on each transaction object - its not very pretty, but I don't think we can do better.": I doubt you can do what since there are some business logic involved between each query. That business logic depends on the result of a previous query thus could change what is executed next.

"For autocallback only could argue that we can rerun the callback function, but I don't believe this will be viable, because that function might not be free of side-effects": Do you mean automatically calling the transaction callback when there is a deadlock? If so, I have done that in other projects with some success. The only thing is that the callback need to know if it is a retry so it can sometimes reset some states. Passing that information to the callback should not be hard though. The retry count would need to be an option.

**Comment by janmeier** [comment]
> "I guess we could save a history of queries executed on each transaction object - its not very pretty, but I don't think we can do better.": I doubt you can do what since there are some business logic involved between each query. That business logic depends on the result of a previous query thus could change what is executed next.

That is true

> "For autocallback only could argue that we can rerun the callback function, but I don't believe this will be viable, because that function might not be free of side-effects": Do you mean automatically calling the transaction callback when there is a deadlock? If so, I have done that in other projects with some success. The only thing is that the callback need to know if it is a retry so it can sometimes reset some states. Passing that information to the callback should not be hard though. The retry count would need to be an option.

Yes, that is what I meant - Perhaps we could do it so if the user passes `retries: x` we will retry that x times and the user will then be aware that their function might be called again. But this will still only work with autocallback (`sequelize.transaction(function)`, not with `sequelize.transaction().then(function)`

**Comment by mickhansen** [comment]
@janmeier if we make retrying explicit by an option/flag people can probably realize it needs to be pure/side-effect free.

Generally we recommend auto callback style so it's fine that's the only feature to support that, imo.

**Comment by DanMMX** [comment]
Is this feature implemented yet?

**Comment by janmeier** [comment]
@DanMMX Since the issue is still open, that'd be a no

**Comment by DanMMX** [comment]
Thanks @janmeier , I'm having that only on my unit tests, just wondering if you think of a good way of preventing testing to break

<img width="1014" alt="captura de pantalla 2015-08-17 a las 14 37 30" src="https://cloud.githubusercontent.com/assets/1919322/9314282/849446be-44ed-11e5-9a9a-18dbd60b7b38.png">

**Comment by mickhansen** [comment]
This feature can easily be implemented by the end-user with https://github.com/mickhansen/retry-as-promised.

(and probably what i would use to implement the feature internally).

**Comment by janmeier** [comment]
@DanMMX I have no idea what your test does, so I can't think of a good way with the information you've given me :D

**Comment by DanMMX** [comment]
Probably that could work @mickhansen 

It's just addition and deletion of rows in unit tests, creating/deleting around 1,200 different rows in the same table @janmeier

**Comment by mickhansen** [comment]
@DanMMX It might just be taking longer than 5seconds? Try increasing the timeout for the test.

**Comment by connor4312** [comment]
Our site is growing and deadlocks are becoming a less-rare error. I'm going to create a PR to add support for this either today or tomorrow.

**Comment by lloydw** [comment]
@connor4312 sequelize 3.0 supports this, just add the dead lock to your retry policy:

`database: {
	dialectOptions: {
		supportBigNumbers: true,
		bigNumberStrings: true,
		charset: 'utf8mb4',
	},
	pool: {
		min: 2,
		max: 8,
		idle: 600000 // Timeout after 10 minutes
	},
	retry: {
		match: 'ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction',
		max: 3
	}
}`

**Comment by connor4312** [comment]
Ah, great, I assumed since this was open it wasn't implemented.  Should this issue be closed then?

**Comment by mickhansen** [comment]
Retry is currently at a query level. For postgres you want transaction level retries on certain types of errors.

**Comment by jacob-israel-turner** [comment]
@mickhansen Apologies for bringing up an old issue.  I'm coming across a similar issue, with transactions in Postgres.  I see that retries are implemented on a query-level.  For transaction-level retries, would you recommend handling that in application code?  Or has there since been a transaction retry API introduced that I'm not aware of?

**Comment by proftom** [comment]
so 4 years on... is there a 'nice' way to retry transactions. or do we need to wrap our entire transaction code in some kind of control loop which retries on transaction failure?

**Comment by cirosantilli** [comment]
My PostgreSQL workaround, please send suggestion if anyone finds a problem with it or generalizes to other DBs: https://stackoverflow.com/questions/68427796/sequelize-transaction-retry-doenst-work-as-expected/70204395#70204395

```
async function transactionWithRetry(sequelize, transactionArgs, cb) {
  let done = false
  while (!done) {
    try {
      await sequelize.transaction(transactionArgs, cb)
      done = true
    } catch (e) {
      if (
        sequelize.options.dialect === 'postgres' &&
        e.original.code === '40001'
      ) {
        await sequelize.query(`ROLLBACK`)
      } else {
        // Error that we don't know how to handle.
        throw e;
      }
    }
  }
}
```

Sample usage:

```
const { Transaction } = require('sequelize');

await transactionWithRetry(sequelize,
  { isolationLevel: Transaction.ISOLATION_LEVELS.SERIALIZABLE },
  async t => {
    const rows = await sequelize.models.MyInt.findAll({ transaction: t })
    await sequelize.models.MyInt.update({ i: newI }, { where: {}, transaction: t })
  }
)
