### ISSUE TITLE
Simplify the sequelize migration flow and sum up all the existing practices

### ISSUE THREAD

**Issue by fzn0x** [sequelize/sequelize#14797]
Currently everyone using the Sequelize migration having different practices to achieve their targets, some differences is happen because our existing Sequelize migration still have manual touches on it. 

## The migrate:undo dilemma

The `migrate:undo` of sequelize-cli is a command to run down() function which has instruction to undo changes whenever we want to undo the changes we made on up() function, but this is not efficient since we need to write things up which is the reverse code of the up() function. It's not efficient since we can make it automatic from the core syntax.

## The model:generate dilemma

The `model:generate` of sequelize-cli is a command to generate a skeleton of DDL script **but** the further complexity like relations and details of the schema is not automically created. Even though this way actually solve the famous migration sync issue on `SequelizeMeta` for pending migrations and not using the `sync` method because this way will overwrite the current database schema on demand.

## Using raw query for migration dilemma (To avoid sync())

We can use raw query to do migration to avoid using the sync() method, in other words, we can use `sync()` first until we are confident with our models schema then grab the SQL output to copy it on sql variable below.

```js
module.exports = {
  up: function (queryInterface, Sequelize) {
    var sql = ``;

    return queryInterface.sequelize.query(sql, {
      type: Sequelize.QueryTypes.RAW
    });
  },

  down: function (queryInterface, Sequelize) {
    var sql = ``;

    return queryInterface.sequelize.query(sql, {
      type: Sequelize.QueryTypes.RAW
    });
  }
};
```

This is good way to avoid sync with running the migrations scripts and commands only but we have to did write the raw query manually which is pain for few developers (I believe it).

## Sync method dilemma

Most conclusions for synchronization methods only create a lot of dilemmas among developers, because the sync method is kind of destructive solution and Sequelize will recommend to use the `sequelize-cli` migrations to solve it, it's just like the sync method is likely to be useful for development purposes so we need to change the code for production use with using the `sequelize-cli` migrations which adds the conclusion again for "so why not to deprecate it from the start and optimize the sequelize-cli migration flow?"

As the docs said:

> - User.sync() - This creates the table if it doesn't exist (and does nothing if it already exists)
> - User.sync({ force: true }) - This creates the table, dropping it first if it already existed
> - User.sync({ alter: true }) - This checks what is the current state of the table in the database (which columns it has, what are their data types, etc), and then performs the necessary changes in the table to make it match the model.

### User.sync()

The facts is `User.sync()` actually does nothing when the migration already registered inside `SequelizeMeta` table, so if you delete the migration file and create a new one, it will not work if you didn't delete the record inside `SequelizeMeta` table.

### User.sync({ force: true })

This is likely to be for `development` purpose only, because it will works for most of the cases on migration but you need to drop your table first (unsafe for production).

### User.sync({ alter: true })

This is likely to be for `development` purpose only, this is not work for most of the cases because I think it's still unstable, I don't see this method is well applied the necessary changes for the database models.

## My proposed solution

My proposed solution is to deprecate the `sync` method and `SequelizeMeta` for our existing Sequelize migration flow on a major version, and use an well behaved logic to detect changes on fields from the `sequelize-cli`. Also we need to restructure the migration scripts, we can't keep the same `up()` and `down()` mindset because most of the `down()` cases like dropping tables are able to do it manually from the database, all we need to provide is easy way to update the database model with just modify the migration scripts and this is wanted from the past and caused many dilemma practices which is have their own cons.

**Comment by WikiRik** [comment]
@fzn0x any specific reason you closed this?

**Comment by fzn0x** [comment]
> @fzn0x any specific reason you closed this?

Looking the oldest issues, seems I'm not really confident to came up with a solution
