### ISSUE TITLE
how to add/set Association with only id?

### ISSUE THREAD

**Issue by starwing** [sequelize/sequelize#1479]
can I add a association with only given a id? now I only can find the id, and get object. is possible to set association only with id? e.g.

user.addTask(req.query.task_id);

now I can only:

models.task.find(req.query.task_id)
  .success(function(task) {
      user.addTask(task);
  });

**Comment by DaAwesomeP** [comment]
Is it possible to do this now with many to many associations? My join table only contains IDs of the two tables, so it would be inefficient have to first find the row in one table to associate it when I already have the ID.

**Comment by DaAwesomeP** [comment]
Nevermind! I just figured it out.
```js
project.setTags([tag.id])
```

**Comment by MohamedLamineAllal** [comment]
What about not event construct the first object. As when all we need is to set the association. And so we don't need to use Project.findById() to get a model isntance. Something like Project.setTag(projectId, [...tagsIds])  will be great and more efficient.
