### ISSUE TITLE
How to remove table prefix in nested includes

### ISSUE THREAD

**Issue by bruck93** [sequelize/sequelize#14806]
## Issue Creation Checklist

[X ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

Hello, I've 3 tables nested with which I do the following
`await DB.evtSwap.findAndCountAll({
      attributes: [
        "evmNetworkId",
        "swapId",
        "addressMaker",
        "valueMakerNative",
        "addressTaker",
        "addressTaker",
        "valueTakerNative",
        "gifUrl",
        "gifUid",
      ],
      include: [
        {
          model: DB.dtlSwap,
          attributes: [
            "collectionAddress",
            "tokenId",
            "creator",
            "type",
            "blcNative",
            "royNative",
            "mediaUrl",
            "isImg",
            [sequelize.col("asset.name"), "name"],
            [sequelize.col("asset.codeName"), "codeName"],
            [sequelize.col("asset.symbol"), "symbol"],
          ],
          raw: true,
          include: [{ model: DB.assets, attributes: [] }],
        },
      ],
      where: {
        evmNetworkId: value.networkId,
        swapId: { [Op.in]: swapArr },
      },
    })`

When the query is executed, it seems that in the last nesting, the attributes have a table prefix and they look like this:
`'dtlSwaps.asset.name'` and they can't be mapped.

### Additional context

Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [X ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by laurelgr** [comment]
> When the query is executed, it seems that in the last nesting, the attributes have a table prefix and they look like this:
'dtlSwaps.asset.name' and they can't be mapped.

This prefix is important because you need to know if the 'id' you need belongs to your root table `evtSwap` (no prefix), to your nested include `dtlSwaps`, or to the doubly nested `asset` of `dtlSwaps`, thus `dtlSwaps.asset`.

Could you maybe explain what you want to do that does not work exactly? Without the context of *why* removing prefixes would fix your issue or what issue the prefixes are causing, it's not exactly easy to help you.
