### ISSUE TITLE
How to handle Promises in CRUD operations in a large batch operation?

### ISSUE THREAD

**Issue by DewangS** [sequelize/sequelize#14818]
## Issue Creation Checklist

[X ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

In my web app we allow user to upload a tab delimited file with records which gets processed by a backend API written in ExpressJs (NodeJS). I use Sequlize to perform CRUD operations. I am noticing a very high connection usage by Sequlize esp when I get a file with 200+ records. This results in SequelizeConnectionAcquireTimeoutError where DB operations fails as it can't acquire DB connection.

In my API layer I simply loop through the supplied records (hundreds) and fire off INSERT and UPDATE operations for each record. As Sequlize CRUD operations are Javascript promises and Node being a single threaded architecture, I believe these requests gets queued up and first few hundred requests gets hold of the DB connections while the remaining requests times out (acquire time settings in the connection pool). Is there any way you can address this other than using a queue mechanism or some sort of throttling within the loop?

### Is this issue dialect-specific?

- [ X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ X] No, I don't have the time and I wouldn't even know how to start.

**Comment by tareq-alsayed** [comment]
actually as I think, it is not efficent at all to loop through your insert query, 
you should try **bulkCreate** instead.
so you would get your records in an array, then bulkCreate them

**Comment by DewangS** [comment]
Thanks @tareq-alsayed  though the loop has it's own logic to upsert records i.e. it's a conditional insert\update in to 2 different tables.
