### ISSUE TITLE
Is it possible to have the updatedAt column be updated when another model that belongsTo the first model gets updateed?

### ISSUE THREAD

**Issue by devluked** [sequelize/sequelize#14814]
## Issue Creation Checklist

[X ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

Is it possible to have the updatedAt column be updated when another model that belongsTo the first model gets updateed?

### Additional context

Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ X ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ X ] No, I don't have the time and I wouldn't even know how to start.

**Comment by tareq-alsayed** [comment]
As I think, updateAt & createdAt are related only to the model it self, so you may do it by your self.
for example you could override afterUpdate hook on your model, and update its "children" in the other tables.
