### ISSUE TITLE
Missing API reference for operators?

### ISSUE THREAD

**Issue by mjunix** [sequelize/sequelize#14849]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

The [API reference](https://sequelize.org/api/v6/) doesn't seem to have a reference on [Operators](https://github.com/sequelize/sequelize/blob/main/src/operators.ts). Is this intentional?

### If possible: Provide some suggestion on how we can enhance the docs

Reference documentation for operators.

### Additional context

Add any other context or screenshots about the issue here.

**Comment by WikiRik** [comment]
Just to spare the people looking into this a click; this relates to the v6 API reference which is still built with esdoc.

**Comment by fzn0x** [comment]
The alternative for this is by looking the documentation [here[(https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#operators)

**Comment by fzn0x** [comment]
The alternative for this is by looking the documentation [here](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#operators)

**Comment by WikiRik** [comment]
I looked a bit into this and this is probably because the file was already migrated to TypeScript in v6 and therefore not picked up by esdoc. We're tracking this issue further in https://github.com/sequelize/website/issues/43
