### ISSUE TITLE
Support composite indexes (also primary) and foreign key associations

### ISSUE THREAD

**Issue by ruifortes** [sequelize/sequelize#1485]
Not trivial to implement but surely one feature that would make sequelize greater and one big step closer to ~~"production ready"~~ "de facto ORM for Node" :)

Column order is important so defining it in table and not columns definition seams reasonable.
Starting by the end how about a "indexes" property in sequelize.define "option" argument. Something like:

```
indexes:[
    {
        type:"primary" // or "key", "unique", "fulltext",etc
        columns:["userId","classId"]
        name:"mypk" //optional, could default to generated name
    }
]
```

Of course...defining indexes in columns should also remain possible for single column indexes.

**Comment by dianaflorez** [comment]
I did this and working for me... for postgres 
(I declared id_pais and codigo_pais how primaryKey: true) 

"use strict";

module.exports = function(sequelize, DataTypes) {
  
    var Pais = sequelize.define('pais', {
        id_pais:{
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        codigo_pais: {
            type: DataTypes.STRING(3),
            primaryKey: true
        },
        nombre: {
            type: DataTypes.STRING(50),
            allowNull : false
        },
       "createdAt":{
			type: DataTypes.DATE,
			defaultValue : sequelize.fn('now') 
		},
		"updatedAt":{
			type: DataTypes.DATE,
			defaultValue : sequelize.fn('now') 
		}
    });
  return Pais;
};

//**********************************************
The result in postgres was

-- Table: pais

-- DROP TABLE pais;

CREATE TABLE pais
(
  id_pais serial NOT NULL,
  codigo_pais character varying(3) NOT NULL,
  nombre character varying(50) NOT NULL,
  "createdAt" timestamp with time zone DEFAULT now(),
  "updatedAt" timestamp with time zone DEFAULT now(),
  CONSTRAINT pais_pkey PRIMARY KEY (id_pais, codigo_pais)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE pais
  OWNER TO diana;
