### ISSUE TITLE
How to update associates 

### ISSUE THREAD

**Issue by TannerS** [sequelize/sequelize#14868]
Hello, I am wondering how to correctly update a model and all its associated models that will keep the proper foreign key constraints? 

Right now we are trying to implement a endpoint/method to update models and some of there associated models but we want to avoid the possibly of someone entering a id of a entry that doesn't belong to that specific parent entry

so for example

// parent model / payload to pass into something to update with child association 
```
{
  id: 5, 
  child: {
   parentId: 5 <===we want  to avoid someone entering something other then the proper parentId that belongs to that entry 
  }
 // ...
}
```

**Comment by fzn0x** [comment]
You can create the model with [Sequelize Associations](https://sequelize.org/docs/v6/core-concepts/assocs/) also read about the [Constraints](https://sequelize.org/docs/v6/other-topics/constraints-and-circularities/) if you have any problems with model order.

Using Associations will help you to only using the correct primary key reference.

**Comment by TannerS** [comment]
Hello. I understand creating but I'm wondering about updating. like I can pass a Json payload, to create a bunch of embedded/child objects/models but not with creating so I wonder what is the best approach to this issue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mschipperheyn** [comment]
You would expect an ORM to intelligently update associations on update, such as Hibernate does. However, Sequelize doesn't do this. I suggest you write a generic `updateAssociation` method to execute the update for any kind of association using some options depending on your needs.

**Comment by TannerS** [comment]
I find it so crazy this is not a feature. I did attempt the create my own update method but for so many different models and associates, I was hoping there was a way to write a generic function that could know all of it's associates and child's recursively, then ran into the issue of the foreign key relationships not holding since u could override those .

All in all It may be possible to do this, but having to make it not overwrite foreign key ids and keep the relationship, (knowing this object is a associates of this record ) is a pain

But I'm not sure how to get all associates from a single model/instance/roe/what ever

I wish this was a feature. I don't see why it isn't

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TannerS** [comment]
@mschipperheyn  have you written such a type of method before?
