### ISSUE TITLE
Default timezone wrongly detected / not recognized on Ubuntu Linux

### ISSUE THREAD

**Issue by BodoMinea** [sequelize/sequelize#14872]
## Bug Description

Datetime type fields are treated as having no timezone or the wrong timezone with a mysql database under Ubuntu 20.04.4 LTS.

### What do you expect to happen?

Having the timezone of the system set during installation and the correct date and time shown when I run the `date` command in the terminal or in other programming languages / interpreters (PHP, Python, NodeJS outside Sequelize), I expect the createdAt and updatedAt fields of sequelize objects saved to database to reflect the current time. The timezone should be detected by Sequelize from the default system setting.

### What is actually happening?

The createdAt and updatedAt are saved with the time of 3 hours (my timezone offset) before the current moment, therefore being wrongly interpreted by other apps, etc.

### Checks and fixes

I have tried setting the timezone again with dpkg-reconfigure tzdata, restarting the mysql service and NodeJS app, rebooting the server and checking `date +"%Z %z"`, `timedatectl | grep "Time zone"` and `cat /etc/timezone`. These all show the correct value (`EEST +0300`, `Time zone: Europe/Bucharest (EEST, +0300)`, `Europe/Bucharest`), however the dates are still being saved as 3 hours prior to actual current local time by Sequelize.

The only way to solve this problem, after some trial and error, was to set the `timezone: 'Europe/Bucharest'` parameter directly on the Sequelize connection object.

- Sequelize version: 6.19.2
- Node.js version: 16.15.0
- Database & Version: MariaDB 10.3.34
- Connector library & Version: mysql2 2.3.3

I am not sure if there is something wrong with my setup that makes it impossible to properly detect the local settings. I have this same app and others (albeit on another Sequelize version - 6.6.5) on other Ubuntu 20.04.4 LTS servers on this same and other timezones and they didn't have to be set on a per app basis in order to infer the server timezone.

Are there any supplemental checks that I can run or can you point me to where in the Sequelize code could I look to diagnose this issue?

Thank you so much in advance.

**Comment by WikiRik** [comment]
I did a quick look through the source code and found the following.

Default timezone is `+00:00` as per the [API reference](https://sequelize.org/api/v7/interfaces/options#timezone) and looking at the [connection-manager for MariaDB](https://github.com/sequelize/sequelize/blob/main/src/dialects/mariadb/connection-manager.js#L54-L87) it seems that that's also the one used. This seems unchanged since 6.6.5.

So from my initial findings it should use `+00:00` unless you have specified a custom timezone.
