### ISSUE TITLE
SQLITE_BUSY: database is locked for postgresql db

### ISSUE THREAD

**Issue by dar6k6night** [sequelize/sequelize#14889]
PG module version --- ^8.4.0
sequelize: ^6.3.5

Hi, I'm getting a SQLITE_BUSY error even though I'm using a postgresql database. Also when an error occurs, all credentials are written into the log, including the database password. When I connect to the database from the console all operations work fine.
A similar problem was found here - https://github.com/sequelize/sequelize/issues/13386

**Comment by WikiRik** [comment]
It seems that `SQLITE_BUSY: database is locked` is the default value for `options.retry.match` in the Sequelize constructor (linked below is from 6.3.5, but the same code holds for the latest v6 release). Apart from that `SQLITE_BUSY` is only used in sqlite specific code. When does this error occur? (i.e. is it during connecting, when executing commands) Can you share the exact error (without the database credentials)?

https://github.com/sequelize/sequelize/blob/933b3f62640e218587d34ec141029b2416ff7845/lib/sequelize.js#L164

https://github.com/sequelize/sequelize/blob/933b3f62640e218587d34ec141029b2416ff7845/lib/sequelize.js#L243-L278
