### ISSUE TITLE
Find hooks are not documented

### ISSUE THREAD

**Issue by PierreTurnbull** [sequelize/sequelize#14887]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

Find hooks (beforeFind, beforeFindAfterExpandIncludeAll, beforeFindAfterOptions, afterFind) are not documented, both on [the documentation](https://sequelize.org/docs/v6/other-topics/hooks/) and [the API reference](https://sequelize.org/api/v6/class/src/model.js~model).

### If possible: Provide some suggestion on how we can enhance the docs

Documentation should be added for these hooks

**Comment by WikiRik** [comment]
This should be part of https://github.com/sequelize/website/issues/43
