### ISSUE TITLE
Do model association methods allow passing in transactions? 

### ISSUE THREAD

**Issue by TannerS** [sequelize/sequelize#14893]
I was looking at these examples to set/update associated models 

![image](https://user-images.githubusercontent.com/8866319/184983124-0c3bb9ba-7aa4-4789-8466-25ba1a6427a5.png)

but i dont see any docs on if these accepts transactions,  do they allow it?

**Comment by ephys** [comment]
Yes, all of them accept an option bag which accept a `transaction` option: https://sequelize.org/api/v7/index.html#HasOneGetAssociationMixin

**Comment by ephys** [comment]
It is
You can check which transaction the query uses using the `logging` option. The message printed to the console includes the UUID of the transaction

```
const jobPlace = await JobPlace.create(..., { transaction, logging: console.log })
jobPlace.setCities(..., { transaction, logging: console.log });
```
