### ISSUE TITLE
Anyway to fetch associated methods?

### ISSUE THREAD

**Issue by TannerS** [sequelize/sequelize#14891]
Short of hard coding all associated models per model, is there a generic way to get all associated models for any model?

I wanna try to write a recursive update method to update a model and all its associatesd models, however i dont now a way to get all models associated with a model without explicit filling them in. And for a recursive method that would be a lot of filling in everything for every parent model to every child model and so on

**Comment by ephys** [comment]
There is the `{ include: [{ all: true }] }` option, which may cover your needs
