### ISSUE TITLE
How to search the documentation at netifly?

### ISSUE THREAD

**Issue by lucasgcbkhomp** [sequelize/sequelize#14932]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

Cannot find documentation search. I cannot tell if this is missing or if it just expertly hidden in the design.

### What was unclear/insufficient/not covered in the documentation

I'm unable to find my way through the documentation at the netifly host: https://sequelize.org/docs/v6/

I have to rely on Google index results and extra stale StackOverflow posts to figure out how to use this library.

### If possible: Provide some suggestion on how we can enhance the docs

Remove all the dark mode/clutter/socials buttons on the header and add the magnifying glass somewhere like the [API docs](https://sequelize.org/api/v6/identifiers) does. If this actually is not hidden and simply does not exist, let's work towards adding it.

### Additional context

I have sat down with multiple engineers of varying experience and age groups; we were all unable to find the option to search the documentation. It is nigh unusable as result. I will spare the comments I received while doing so.

**Comment by WikiRik** [comment]
Searching the docs is not yet added, we're tracking this in https://github.com/sequelize/website/issues/57
