### ISSUE TITLE
validationFailed hook is missing in type definitions

### ISSUE THREAD

**Issue by nathanlepori** [sequelize/sequelize#14955]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

The TS type definition for the `validationFailed` hook is missing.

### Additional context

The signature should be added to `ModelHooks` interface (allowing to add it with `addHook()` as  well). There might be other places but this is the one I could find.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by fzn0x** [comment]
PR welcome, also nice for first contribution :)

**Comment by ravihidayat** [comment]
Looks interesting, although I might need some guidance on how to approach this before I start.
