### ISSUE TITLE
_previousDataValues replaced by dataValues in save Method

### ISSUE THREAD

**Issue by FauziFadhi** [sequelize/sequelize#14969]
## Bug Description

i was tried to get previous data after update my data. i tried to use `.previous()` function but always get updated data not previous data before i updated the data. i tried to debug inside sequelize class (model.js) and found these lines.
![bug data previous](https://user-images.githubusercontent.com/22959762/189261608-96c6402f-a637-4e21-8f0f-d08e4fd78158.png)

tried to delete these lines and it works on my local machine.
### Reproducible Example

1. get data with findOne from database.
2. update some column with new value.
3. log `instance.previous()`

![image](https://user-images.githubusercontent.com/22959762/189264129-be501be3-2f11-40d2-9d40-fedb7433af50.png)

### What do you expect to happen?

 i can get old data after i updated the row with `instance.previous()` function outside hook.

### What is actually happening?

i get new data with `instance.previous()` function

### Environment

sequelize: ^6.21.4
nodeJs: 16.17.0
PostgreSQL: ^14

- Sequelize version: 6.21.4
- Node.js version: 16.17.0
- If TypeScript related: TypeScript version: 4.7.x
- Database & Version: Postgres 14
- Connector library & Version: pg@8.8.0

## Would you be willing to resolve this issue by submitting a Pull Request?
I can, but I dont what is the reason those line come from.

- [ ] Yes, I have the time and I know how to start.
- [ x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by fzn0x** [comment]
The reason is because you already update your values, and your database is already updated.

You can try this (lets assume the `payload.count` here is the data you want to update):
```js
console.log(payload.count)); // 1

payload.count= 2;

console.log(payload.count)); // 2
console.log(payload.previous('count')); // 1 (you can store this to a new variable)
```

**Comment by fzn0x** [comment]
The reason is because you already update your values, and your database is already updated.

You can try this (lets assume the `payload.count` here is the data you want to update):
```js
console.log(payload.count)); // 1

payload.count = 2;

console.log(payload.count)); // 2
console.log(payload.previous('count')); // 1 (you can store this to a new variable)
```

**Comment by fzn0x** [comment]
The reason is because you already update your values, and your database is already updated.

You can try this (lets assume the `payload.count` here is the data you want to update):
```js
console.log(payload.count)); // 1

payload.count = 2;

console.log(payload.count)); // 2
console.log(payload.previous('count')); // 1 (you can store this to a new variable)

// do the above things before calling `update` or `save` 
```

**Comment by FauziFadhi** [comment]
> The reason is because you already update your values, and your database is already updated.
> 
> You can try this (lets assume the `payload.count` here is the data you want to update):
> 
> ```js
> console.log(payload.count)); // 1
> 
> payload.count = 2;
> 
> console.log(payload.count)); // 2
> console.log(payload.previous('count')); // 1 (you can store this to a new variable)
> 
> // do the above things before calling `update` or `save` 
> ```

but it is works in afterUpdate Hooks. the instance give old data from _previousDataValues.

as you can see in this code 
![image](https://user-images.githubusercontent.com/22959762/189285855-ef42ecd3-6118-49c1-80dd-3b577f69d4af.png)

this method send the instance to hook, before replacing the _previousDataValues with dataValues.

**Comment by fzn0x** [comment]
> > The reason is because you already update your values, and your database is already updated.
> > You can try this (lets assume the `payload.count` here is the data you want to update):
> > ```js
> > console.log(payload.count)); // 1
> > 
> > payload.count = 2;
> > 
> > console.log(payload.count)); // 2
> > console.log(payload.previous('count')); // 1 (you can store this to a new variable)
> > 
> > // do the above things before calling `update` or `save` 
> > ```
> 
> but it is works in afterUpdate Hooks. the instance give old data from _previousDataValues.
> 
> as you can see in this code ![image](https://user-images.githubusercontent.com/22959762/189285855-ef42ecd3-6118-49c1-80dd-3b577f69d4af.png)
> 
> this method send the instance to hook, before replacing the _previousDataValues with dataValues.

Yes it's because the `afterUpdate` are put before Sequelize updating the `_previousDataValues`, the reason Sequelize update the `_previousDataValues` is to keep the previous data values is always updating for next update too as we won't to always keep the first original data.

**Comment by FauziFadhi** [comment]
shouldn't it would be more make sense, if those line move before updating data to database?

something like,

```
this._previousDataValues = this.dataValues;

// update query to DB
const result = {result query after update}

this.dataValues = result.dataValues
```

if like that,
i think we can always get 1 step previous data with `previousDataValues` and current data with `dataValues`

**Comment by fzn0x** [comment]
> shouldn't it would be more make sense, if those line move before updating data to database?
> 
> something like,
> 
> ```
> this._previousDataValues = this.dataValues;
> 
> // update query to DB
> const result = {result query after update}
> 
> this.dataValues = result.dataValues
> ```
> 
> if like that, i think we can always get 1 step previous data with `previousDataValues` and current data with `dataValues`

Theoretically, yes, but if you looking from our current codebase, is it possibile? if you think it's possible, PR welcome 😃

**Comment by ephys** [comment]
`_previousDataValues` is meant to represent the state of the DB, without the currently unsaved changes. `dataValues` is meant to include the unsaved changes.
For that reason, `_previousDataValues` & `dataValues` will be equal just after a save or a select.

We won't be changing this behavior (though we could find a better name than previous). If you need to keep what the values looked like before persisting them, you need to store them separately (e.g. on a non-attribute property of your model). You could do that automatically with our hooks
