### ISSUE TITLE
support for DataTypes.ARRAY(DataTypes.ENUM('value 1', 'value 2')) in postgres

### ISSUE THREAD

**Issue by cjroth** [sequelize/sequelize#1498]
it would be great if this worked:

```
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Role', {
    // ...
    'my_column': {
      type: DataTypes.ARRAY(DataTypes.ENUM('value 1', 'value 2')),
      // values: ['value 1', 'value 2'], <- and this would be awesome as well!
    },
  }, {
    tableName: 'my_table',
  });
};
```

as of 1.7.0 it causes sequelize to throw `error: type "enum[]" does not exist`.

probably low priority because it can be emulated with the isIn validator and DataTypes.STRING

**Comment by wavded** [comment]
any plans for this?

**Comment by Hoverbear** [comment]
+1 This is important to me as well.

**Comment by tiblu** [comment]
+1 - would be nice to have.

**Comment by zoltan-tamasi** [comment]
I have the same problem.
I have enum types in postgres and some table columns with arrays of those enums like:

```
CREATE TYPE enum_type AS ENUM ('value1', 'value2');
CREATE TABLE table ( enum_array_type enum_type[] );

```
And what I wanted to do is to define a sequelize model like this:
```

sequlize.define('model', {
  'enum_array_type' : 'enum_type[]'
});
```
In this case it throws an error: "field.type.toSql is not a function" when I want to insert a new row...

**Comment by aliatsis** [comment]
+1

**Comment by rajat246** [comment]
+1. I also need this feature.

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by gabybrow** [comment]
Any new about this issue ? It's sad that we still don't have an answer :(

**Comment by HarleyKwyn** [comment]
I just ran into this as well. Can we get support for this?

**Comment by jameskennethrobinson** [comment]
Ditto for support.

**Comment by xiaomingplus** [comment]
Ditto for support.

**Comment by wavded** [comment]
It would be very helpful to have this.  I started a pull request.
