### ISSUE TITLE
List of possible attributes for queryInterface.createTable nowhere to be found

### ISSUE THREAD

**Issue by jwad96** [sequelize/sequelize#14988]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What was unclear/insufficient/not covered in the documentation

List of possible key/value pairs for attributes object in queryInterface.createTable

### If possible: Provide some suggestion on how we can enhance the docs

Provide missing documentation

### Additional context

Add any other context or screenshots about the issue here.

**Comment by ephys** [comment]
They are here https://sequelize.org/api/v7/classes/queryinterface#createTable

**Comment by jwad96** [comment]
Ah yeah, I mistyped. I meant a list of options for the attributes object, not the options object. I see that the possible options for the options object are listed here: https://sequelize.org/api/v7/interfaces/queryinterfacecreatetableoptions

**Comment by ephys** [comment]
The type of attributes in createTable is `ModelAttributes<M, CreationAttributes<M>>`, which is an object where the key is the name of the attribute & the value is either a [`DataType`](https://sequelize.org/docs/v7/other-topics/other-data-types/) or this type https://sequelize.org/api/v7/interfaces/modelattributecolumnoptions

**Comment by jwad96** [comment]
That looks good, thanks!
