### ISSUE TITLE
customizable allowNull error messages

### ISSUE THREAD

**Issue by cjroth** [sequelize/sequelize#1500]
something like this:

```
  var User = sequelize.define('User', {
    'email': {
      type: DataTypes.STRING,
      unique: true,
      allowNull: { args: false, msg: 'Email is required.' },
      validate: { isEmail: { msg: 'Invalid email.' } },
    },
```

**Comment by epsyan** [comment]
+1

**Comment by streetkid** [comment]
+1

**Comment by cithukyaw** [comment]
What is the solution for this? `notEmpty` or `notNull` did not work.

	travelTime: {
		type: Sequelize.INTEGER,
		allowNull: false,
		validate: {
			notNull: { msg: "Travel time is required" },
			isNumeric: true
		}
	}

or 

	travelTime: {
		type: Sequelize.INTEGER,
		allowNull: false,
		validate: {
			notEmpty: { msg: "Travel time is required" },
			isNumeric: true
		}
	}

My sequelize version is 2.0.2.

**Comment by epsyan** [comment]
@cithukyaw,

<pre>hooks: {
			beforeValidate: function (model, options, cb) {
				model.travelTime = model.travelTime || '';
				cb(null, model);
			}
		}</pre>

**Comment by cithukyaw** [comment]
@epsyan Thanks. I have seen that workaround. I expect the Sequelize to be fixed internally, otherwise I would have to use the hook in every schema that is not efficient.

**Comment by mickhansen** [comment]
Issue is still open so it's not solved yet.

@thanpolas you initially refactored `allowNull` to be a schema valdiator, what is your opinion about customizable error messages and allow null?

**Comment by cithukyaw** [comment]
@mickhansen [Your link in the comment](https://github.com/sequelize/sequelize/issues/1500#issuecomment-39193812) is broken.

**Comment by mickhansen** [comment]
@cithukyaw was renamed to https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js a while back.

**Comment by cithukyaw** [comment]
@mickhansen Yes, thanks. I in fact don't like all of the validation error messages of Sequelize as they all are not user-friendly. If we could re-define custom messages for all validators in one place, it will be great.

**Comment by epsyan** [comment]
@mickhansen, +1

**Comment by mickhansen** [comment]
@cithukyaw proposals and PR's always welcome :)

**Comment by cithukyaw** [comment]
@mickhansen difficult to find a spare time to contribute this. wonder why those messages were initially implemented like system errors.

**Comment by mickhansen** [comment]
@cithukyaw we all have limited spare time. If you read the entire issue and the original PR change you can find the reasons, mostly it's to distinguish between schema validation and user validation.

**Comment by janmeier** [comment]
@cithukyaw The error messages are directed at the programmer, not necesarily at the end user

**Comment by cithukyaw** [comment]
@janmeier Those messages are related to the user inputs, so they are directly related to the end user. So, why we need to re-define all of them as user messages.

**Comment by mickhansen** [comment]
@cithukyaw `The field is numeric` would be bad for user experience aswell. Not sure it's possible to implement something as domain driven and specific to UX as valdiations as generic error messages.

**Comment by mickhansen** [comment]
@cithukyaw You seem to have very strong feelings about what "should be done for you", so it's really an oppurtune time for you to come up with tangible proposal and changes :)

The Sequelize team has limited resources, and we currently have higher priorities. We will get to this eventually but it can easily be solved in the implementation layer and there's a difference of opinion whether or not stuff like this should be communicated directly to the end-user (i wouldn't). And i don't think generic error messages would ever satisfy the end user in terms of good UX.

**Comment by cithukyaw** [comment]
@mickhansen 

> The field is numeric would be bad for user experience aswell. Not sure it's possible to implement something as domain driven and specific to UX as valdiations as generic error messages.

Yes, it is just for example. Such `Validation isNumeric failed` message is not ideal for the end user I think.

**Comment by janmeier** [comment]
And that's exactly what the validations are - sub-types of `Error` ;)

I see your point, that it would be nice, but look at it this way. Right now we have one message for all errors: name of validator + 'failed'. If we were to do something like you said it would required a tailored error message for each validtor - someone would have to write and maintain those and they would bloat the core code. And as mick mentioned, most developers would override them anyways, to get validator error messages closer to their domain

**Comment by cithukyaw** [comment]
Just a possibility by defining `label` in schema that is what I usually do in PHP:

	travelTime: {
		type: Sequelize.INTEGER,
		label: "Travel Time",
		allowNull: false,
		validate: {
			isNumeric: true
		}
	}


or 

	travelTime: {
		type: Sequelize.INTEGER,
		label: "Travel Time",
		allowNull: false,
		validate: {
			isNumeric: { msg: "%s must be number." }
		}
	}

This could return "**Travel time must be number**". If `label` is not defined, just return "**travelTime** must be number", however, camelCase could be converted to words. Does it make sense and is it possible?

**Comment by mickhansen** [comment]
@cithukyaw yeah that makes a lot of sense, likely possible, although a formalized API should probably be discussed. And then the work still needs to be done :)

**Comment by cithukyaw** [comment]
Since [the workaround](https://github.com/sequelize/sequelize/issues/2870#issuecomment-69260235) is not working in 2.0.2, the following is my temporary workaround:

Use `notEmpty: { msg: "xxxxx is missing" }` in schema and set empty if `null`.

	params.travelTime = params.travelTime || "";
	params.travelCost = params.travelCost || "";
	
	Model.create(params).then(function() {
	});

However, validation failed for the input `0`. If you want to by-pass `0`, you may check it explicitly or use the other validator such as `is`.

**Comment by mickhansen** [comment]
@cithukyaw i wasn't aware that that was *the workaround* ;)
Have you tried using hooks?

**Comment by cithukyaw** [comment]
@mickhansen https://github.com/sequelize/sequelize/issues/1500#issuecomment-74485080

**Comment by alexcheuk** [comment]
My workaround right now is
```
        lastname: {
            type: DataTypes.STRING,
            defaultValue: '',
            validate: {
                notEmpty: { msg: 'Last Name is required' }
            }
        }
```

**Comment by mshahriarinia** [comment]
So what's the right way to provide a message for `allowNull:false`?

**Comment by mickhansen** [comment]
@mshahriarinia It's not possible to change the messages for schema validations, you'll have to use a custom validator at the moment i'm afraid.

**Comment by fjcero** [comment]
@alexcheuk nice! thanks for the idea :)

**Comment by kog13** [comment]
@alexcheuk seconded, thanks for pointing out this option.

**Comment by nikko-xepler** [comment]
@alexcheuk Also using this, thanks

**Comment by sushantdhiman** [comment]
Proper way to set `allowNull` messages

```js
{
  email: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      notNull: {
        msg: 'Please enter your e-mail',
      }
    },
  },
}
```

Fixed in https://github.com/sequelize/sequelize/pull/6943 (v4)

**Comment by diego-oliveira** [comment]
@sushantdhiman I think we have a problem with this. The `notNull` validator was depreciate. So, when I try configure the code in the way you did, I get this error: 

`'Warning "notNull" validation has been deprecated in favor of Schema based "allowNull"'` 

make sense?

**Comment by sushantdhiman** [comment]
With master @diego-oliveria ?

**Comment by diego-oliveira** [comment]
No @samkelleher, it was on a stable version. I just tested in the master branch and it is working. My bad. 👍

**Comment by diego-oliveira** [comment]
@samkelleher I just realize that even in master this message shows up. Just need send the field with value and the message appears. I saw that in master, file `validator-extras.js`, that we have this piece of code: 
`
// Deprecate this.
validator.notNull = function() {
  throw new Error('Warning "notNull" validation has been deprecated in favor of Schema based "allowNull"');
};

In some situations this function is been called and cause this. 


`

**Comment by timscott** [comment]
Why was this issue is closed? It's important to be able to customize messages for required fields missing and also handle cases where the attribute can be null but only under certain conditions. 

Currently I'm using this dreadful hack in a few dozen places:

```javascript
changeAt: {
  type: DataTypes.DATE,
  defaultValue: '',
  validate: {
    notEmpty: {
      msg: 'Change At is required.'
    }
  }
}
```

I would expected this to work:

```javascript
changeAt: {
  type: DataTypes.DATE,
  validate: {
    required: function(value, next) {
      if (value) {
        return next();
      }
      return next('Change At is required.');
    },
    otherCustomValidation: ...
  }
}
```

But when the value is null or undefined, validation is entirely skipped, whether or not ```allowNull``` is set to ```true```. Seems wrong. What if I want to allow null but only under some certain other conditions. I guess the only way to do that is using the ugly hack of setting the default value to empty string.

**Comment by Kumagor0** [comment]
Can we reopen this?
As of 4.2.0, @sushantdhiman 's solution does not work.
```
      firstName: {
        type: Sequelize.STRING,
        allowNull: false,
        validate: {
          notNull: { msg: 'null is not valid' },
        },
      },
```

leads to

```
Validation error: Warning "notNull" validation has been deprecated in favor of Schema based "allowNull"
    at Promise.all.then (/.../sequelize/lib/instance-validator.js:77:15)
```

if firstName value is not null.

**Comment by mabdullah353** [comment]
Getting this error

```
{
 "message": 'Warning "notNull" validation has been deprecated in favor of Schema based "allowNull"',
}
```

So what's the proper way to set custom message on notNull ?

**Comment by jackwilsdon** [comment]
It looks like there's isn't a way at the moment, possibly an oversight of deprecating `notNull`?

https://github.com/sequelize/sequelize/blob/2fc43c4cd1efe7f0ba649a7d6572119502fb0a42/lib/instance-validator.js#L325-L327

**Comment by boulosda** [comment]
The fix we are using currently replaces the `notNull` function in [validator-extras](https://github.com/sequelize/sequelize/blob/63978e184a95a8a39595cb0e04d43e663163c9bc/lib/utils/validator-extras.js#L80-L83) with,
`validator.notNull = function(item){
    return !validator.isNull(item);
};`

**Comment by fariasfrancisco** [comment]
Any official update on this? This issue should not be closed.

**Comment by Oxyaction** [comment]
Any solutions? As I see there is no capability to add not null error message now 😞

**Comment by themightychris** [comment]
How does an ORM have a 3+ year old issue for customizing the validation error message when a required field is missing? This shouldn't be labeled as a feature request...

**Comment by themightychris** [comment]
Building off what @boulosda provided above, you can monkeypatch this from the bottom of `models/index.js` :'(

```js
/**
 * Monkey patch issue causing deprecation warning when customizing allowNull validation error
 *
 * See https://github.com/sequelize/sequelize/issues/1500
 */
Sequelize.Validator.notNull = function (item) {
    return !this.isNull(item);
};
```

**Comment by brunoosilva** [comment]
+1

**Comment by dubharmonic** [comment]
👍

**Comment by DmytroMysak** [comment]
+1

**Comment by brsalviano** [comment]
Thanks @timscott. The workaround worked as expected:
```
    name: {
        type: Sequelize.STRING(50),
        allowNull: false,
        defaultValue: '',
        validate: {
            notEmpty: {
                msg: 'The name is required.'
            }
        }
    }
```

**Comment by tybro0103** [comment]
+1

**Comment by agims7** [comment]
+1

**Comment by acodercat** [comment]
```js
 username: {
      type: STRING(32), allowNull: false, unique: true,
      validate: {
        notNull: { args: true, msg: "用户名不能为空" },
      }
    },
```
{
     "message": "Warning \"notNull\" validation has been deprecated in favor of Schema based \"allowNull\""
}

**Comment by sushantdhiman** [comment]
@acodercat only `5.0.0-beta.9` or above

**Comment by acodercat** [comment]
> @acodercat only `5.0.0-beta.9` or above

How should I modify allowNull validate msg now?

**Comment by sushantdhiman** [comment]
@acodercat Not possible in v4, there are some hacks discussed in this thread though

**Comment by PauloLira** [comment]
+1

**Comment by jackwilsdon** [comment]
@PauloLira this has already been implemented, you need to use `>=5.0.0-beta.9` for the deprecated message to go away.

**Comment by PauloLira** [comment]
@Marcosaurios this solution worked fine for me, pay attention to **allowNull** and inside of the validate I'm calling **notNull**

 field: {
      type: DataTypes.STRING,
      **allowNull**: false,
      validate: {
        **notNull**: { args: true, msg: "Field is required" },
      },
    },

**Comment by KBHE** [comment]
> This work for me "sequelize": "^4.43.0" version

> ```js
>  email: {
>       type: DataTypes.STRING,
 >       unique: true,
>       allowNull: false,
>       validate: {
>        notNull: { msg: 'Email is required.' },
>        isEmail: { msg: 'Invalid email address.' },
>       }
>     },
> ```
>

**Comment by xuxuewen** [comment]
```javascript

var User = sequelize.define('User', {
    email: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: { args: false, msg: 'Email is required.' }, // not work
      validate: { isEmail: { msg: 'Invalid email.' } },
    },

// modify
email:{
  type:Data.Types.STRING,
 unique:true,
 allowNull:false,
 validate:{
   notNull:{
      msg:'this is custom allowNull error message'
   }
 }
}

```

**Comment by mafei-dev** [comment]
@cjroth 
You can use validate with isNull. if value is null, you can throw an error with custom message like bellow.

![Annotation 2020-01-05 013314](https://user-images.githubusercontent.com/58949636/71771082-9ebdf500-2f5b-11ea-8bca-60d7b45c7f42.png)
Then your output will be appear like this . 

![output](https://user-images.githubusercontent.com/58949636/71771104-f8262400-2f5b-11ea-94c6-691df5184e90.png)
