### ISSUE TITLE
How can I rollback all query in nested funtion

### ISSUE THREAD

**Issue by hzjux001** [sequelize/sequelize#15014]
How can I rollback all query in nested funtion
just like

err = sqlxdb.InTransaction(func() (interface{}, error) {
     err =func1(sqlxdb){
           do some query
     }
     if err !=nil{
        return nil,err
     }

     err =func2(sqlxdb){
           do some query
     }
     if err !=nil{
        return nil,err
     }  
     
})

when func2 return err but can't rollback query in func1

**Comment by fzn0x** [comment]
This is not the right place to issue your problem, because it is golang and you are using `reform` inTransaction https://pkg.go.dev/gopkg.in/reform.v1#hdr-Context
