### ISSUE TITLE
update moment-timezone to 0.5.35 because of low and moderate security issues

### ISSUE THREAD

**Issue by sadtrick** [sequelize/sequelize#15021]
## Issue Creation Checklist

[ x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

moment-timezone has two security issues with severity low and moderate that are patched with version 0.5.35:
https://github.com/moment/moment-timezone/security/advisories/GHSA-56x4-j7p9-fcf9
https://github.com/moment/moment-timezone/security/advisories/GHSA-v78c-4p63-2j6c

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by WikiRik** [comment]
moment-timezone is not pinned and will therefore update to the latest version when reinstalling dependencies. But it is wise that the minimum version is a safe one, so we'll update this in the next v6 release.

**Comment by ephys** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/15685
