### ISSUE TITLE
SQLITE_ERROR: no such function: REGEXP

### ISSUE THREAD

**Issue by jouannoj** [sequelize/sequelize#15041]
## Bug Description

` Error: SQLITE_ERROR: no such function: REGEXP`

The request work fine when I try it in sqlite3 cli without loading external lib (like pcre.so)

### Reproducible Example

`sequlize.query('SELECT * FROM myTable WHERE col1 REGEXP 'expr');`

### What do you expect to happen?

The request work like when I write it in sqlite3 cli

### What is actually happening?

` Error: SQLITE_ERROR: no such function: REGEXP`

### Environment

- Sequelize version:  sequelize@6.16.1 
- Node.js version: v14.15.4
- If TypeScript related: TypeScript version:  typescript@4.5.5
- Database & Version: sqlite3
- Connector library & Version:  sqlite

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [X] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by fzn0x** [comment]
Looks like it is your query error (`SQLITE_ERROR`) not Sequelize.

**Comment by WikiRik** [comment]
Yeah, when I run the query within [node-sqlite3](https://github.com/TryGhost/node-sqlite3) (without using sequelize) I get the same error (with the fixed example).

**Comment by ephys** [comment]
According to https://github.com/TryGhost/node-sqlite3/wiki/API#databaseloadextensionpath-callback, you can use their loadExtension API.

You need to call that method on the SQLite database instance, which you can retrieve with:

```js
sequelize.connectionManager.getConnection()
```

**Comment by jouannoj** [comment]
Hi all thank you for your replies.

I try to use the load extension with the pcre.o lib like described by TryGhost but nothing work

`
  await sequelize.authenticate()
  const c = await sequelize.connectionManager.getConnection({ type: 'write' })
  await c.loadExtension(`${__dirname}/../pcre.so`, (err) => {
   // When path is incorrect that throw an error but here err is null
    console.log(err) 
  })

`

Can you help me please?
