### ISSUE TITLE
How to where clause in array of string in json data type postgres?

### ISSUE THREAD

**Issue by thoriqadillah** [sequelize/sequelize#15043]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

There is a column that uses json in the database for categories, but the actual data is an array of string. I want to filter it, but how can I do it? I have tried the docs said, but it gave me errors like `"operator does not exist: json @> unknown"`

### Additional context

Suppose the categories column like this 
```js
categories: {
  type: Sequelize.JSONB,
  allowNull: false
},
```
And I would like to query the model and include it it like this
```js
include: [{
  model: Training,
  as:  'training',
  where: {
    // TODO: filter categories
    categories: {
      [Op.contains]: req.categories
    }
  },
}]
```
But it gave me error such as `"operator does not exist: json @> unknown"`
I also tried query it like this
```js
include: [{
  model: Training,
  as:  'training',
  where: {
    // TODO: filter categories
    categories: {
      $contains: req.categories
    }
  },
}]
```
It gave me empty data, just like when the categories does not found, even though I hard coded it from one of categories in database
The req.categories is supposed to be an array such as `['eum', 'quos', 'quis']`
And the categories data in database is supposed to be like this
![Screenshot_20220924_070124](https://user-images.githubusercontent.com/44075782/192070985-b5fc7e93-6447-4ffb-a558-5b6efb37378b.png)

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by fzn0x** [comment]
It's indeed a bug, related to https://github.com/sequelize/sequelize/issues/5173

You can change your script from

```js
where: {
  // TODO: filter categories
  categories: {
    [Op.contains]: req.categories
  }
},
```

to (or other working alternatives):

```js
where: sequelize.fn('JSON_CONTAINS', sequelize.col('categories'), `"${req.categories}"`),
```

**Comment by thoriqadillah** [comment]
@fzn0x I tried the function one and it did not work. I got an error `function json_contains(json, unknown) does not exist`. And by the way, the categories on json result is nested like this.
```js
{
  TrainingClassStudent: {
    classes: {
      training: {
        boo: baz,
        categories: ['foo', 'bar']
      }
    }
  }
}
```
I tried different sequelize.col, like 
TrainingClassStudent.classes.training.categories (same error as first)
classes.training.categories (same error as first)
training.categories (`error: missing FROM-clause entry for table \"training\`)
categories (same error as first)

**Comment by fzn0x** [comment]
is `TrainingClassStudent` a association?

**Comment by fzn0x** [comment]
> the categories on json result

Is it the `req.categories` or the `categories`  field from the table?

**Comment by thoriqadillah** [comment]
@fzn0x TrainingClassStudent belongs to classes, and classes belongs to training. It's training -> training class -> training class student. And the `categories` is the field from the table. The `req.categories` is for filter purpose

**Comment by fzn0x** [comment]
> @fzn0x TrainingClassStudent belongs to classes, and classes belongs to training. It's training -> training class -> training class student. And the `categories` is the field from the table. The `req.categories` is for filter purpose

`the categories on json result` I mean, this comment you mention, where the value is coming from?

**Comment by fzn0x** [comment]
I know if `categories` is the field from the table. The `req.categories` is for filter purpose, but can you ealborate about `the categories on json result`?

**Comment by fzn0x** [comment]
> @fzn0x I tried the function one and it did not work. I got an error `function json_contains(json, unknown) does not exist`. And by the way, the categories on json result is nested like this.
> 
> ```js
> {
>   TrainingClassStudent: {
>     classes: {
>       training: {
>         boo: baz,
>         categories: ['foo', 'bar']
>       }
>     }
>   }
> }
> ```
> 
> I tried different sequelize.col, like TrainingClassStudent.classes.training.categories (same error as first) classes.training.categories (same error as first) training.categories (`error: missing FROM-clause entry for table \"training\`) categories (same error as first)

I just want to know since I don't know what the solution to bring because I think you mention that both value from `req.categories` and the categories from database is array of strings but now you mention that it is a nested object. Which one is the correct one?

**Comment by fzn0x** [comment]
> @fzn0x I tried the function one and it did not work. I got an error `function json_contains(json, unknown) does not exist`. And by the way, the categories on json result is nested like this.
> 
> ```js
> {
>   TrainingClassStudent: {
>     classes: {
>       training: {
>         boo: baz,
>         categories: ['foo', 'bar']
>       }
>     }
>   }
> }
> ```
> 
> I tried different sequelize.col, like TrainingClassStudent.classes.training.categories (same error as first) classes.training.categories (same error as first) training.categories (`error: missing FROM-clause entry for table \"training\`) categories (same error as first)

I just want to know since I don't know what the solution to bring without knowing the actual value you mention because I think you mention that both value from `req.categories` and the categories from database is array of strings but now you mention that it is a nested object. Which one is the correct one?

**Comment by thoriqadillah** [comment]
@fzn0x oh right, I'm sorry for not looking at the quote block. 
> the categories on json result

What I mean by that is, the result from the query I did is looking like the json code I provided. 
```js
{
  TrainingClassStudent: {
    classes: {
      ...somefield
      training: {
        ...somefield
        categories: ['foo', 'bar']
      }
    }
  }
}
```

**Comment by thoriqadillah** [comment]
@fzn0x 
> I just want to know since I don't know what the solution to bring without knowing the actual value you mention because I think you mention that both value from req.categories and the categories from database is array of strings but now you mention that it is a nested object. Which one is the correct one?

I'm sorry that it's confusing you. But let me iterate it better
The `categories` and `req.categories` is an supposed to be array. But, the `categories` field in database has json data type, and so does the sequelize definition. The nested object I mentioned earlier is the result of the query I did, and that is to be consumed by the frontend. And the `categories` is in `training` field. The task I'm currently doing is to fetch training and class data based on student id. And the result of the query is looking like the reply above. Are we clear enough?

**Comment by fzn0x** [comment]
> 

Yup it is better explanation from you but honestly I don't want to give this solution since this is the only thing that gonna work AFAIK, you need to cast the value to `jsonb` first, you might get performance issue by doing type casting on large json. But it is inevitable to get the result you want for now by doing that. 

You need to cast the `json` to `jsonb` to allow the @> operator. The value you want to find is recognized as `json` there, so you need to cast it to `jsonb`, for example:

```js
include: [{
  model: Training,
  as:  'training',
  where: {
    // TODO: filter categories
    categories: {
      $contains: req.categories
    }
  },
}]
```

change it to 

```js
include: [{
  model: Training,
  as:  'training',
  where: {
    'categories::jsonb': { // just make sure this is always an "ARRAY" of strings.
      $contains: req.categories // just make sure this is always an "ARRAY" string. e.g '["exampleA"]'
    }
  },
}]
```

**Comment by fzn0x** [comment]
> ```js
> include: [{
>   model: Training,
>   as:  'training',
>   where: {
>     'categories::jsonb': { // just make sure this is always an "ARRAY" of strings.
>       $contains: req.categories // just make sure this is always an "ARRAY" string. e.g '["exampleA"]'
>     }
>   },
> }]
> ```

This will work if

- the data from the database is array of strings
- and the value you provide for `$contains` property is array string, e.g '["exampleA"]'

**Comment by thoriqadillah** [comment]
I'm sorry if this is rather annoying, but it still give me error: `  "message": "Invalid value { '$contains': [ 'eum', 'quos' ] }`
Because the `req.categories` is from `query param`, so I make it string, but seperated with comma, e.g 'eum,quos', and splitted afterward to parse it to array. Maybe that is something you need to know. Any idea?

**Comment by fzn0x** [comment]
> I'm sorry if this is rather annoying, but it still give me error: ` "message": "Invalid value { '$contains': [ 'eum', 'quos' ] }` Because the `req.categories` is from `query param`, so I make it string, but seperated with comma, e.g 'eum,quos', and splitted afterward to parse it to array. Maybe that is something you need to know. Any idea?

It's seems the operator is working now! just the `req.categories` value is wrong.

After you parse it to array, can you stringify the array so it's become a string, like this `JSON.stringify(req.categories)`.

**Comment by thoriqadillah** [comment]
still gives the same error

**Comment by fzn0x** [comment]
If it is the same invalid value error, you need to enclose the values with double quotes for the values inside the array string.

```js
var yourQueryParamsArray= [ 'eum', 'quos' ];
const wrappedInQuotes = yourQueryParamsArray.map(date => `"${date}"`);
const withCommasInBetween = yourQueryParamsArray.join(',')
console.log(`[${withCommasInBetween}]`);
```

**Comment by fzn0x** [comment]
If it is the same invalid value error, you need to enclose the values with double quotes for the values inside the array string.

```js
var yourQueryParamsArray= [ 'eum', 'quos' ];
const wrappedInQuotes = yourQueryParamsArray.map(value => `"${value}"`);
const withCommasInBetween = wrappedInQuotes.join(',')
console.log(`[${withCommasInBetween}]`);
```

**Comment by fzn0x** [comment]
If it is the same invalid value error, you need to enclose the values with double quotes for the values inside the array string.

```js
const yourQueryParamsArray = [ 'eum', 'quos' ];
const wrappedInQuotes = yourQueryParamsArray.map(value => `"${value}"`);
const withCommasInBetween = wrappedInQuotes.join(',');
console.log(`[${withCommasInBetween}]`);
```

**Comment by fzn0x** [comment]
> still gives the same error

If it is the same invalid value error, you need to enclose the values with double quotes for the values inside the array string.

```js
const yourQueryParamsArray = [ 'eum', 'quos' ];
const wrappedInQuotes = yourQueryParamsArray.map(value => `"${value}"`);
const withCommasInBetween = wrappedInQuotes.join(',');
console.log(`[${withCommasInBetween}]`);
```

**Comment by thoriqadillah** [comment]
wait what
So, if I was gonna make it one liner:
```js
const queryParam = 'eum,quos'
const categories = queryParam.split(',').map(value => `"${value}"`).join(',')
```
so that will not make it array of string with length of 2, is it?

**Comment by thoriqadillah** [comment]
oh sorry, I thought ```[`${categories}`]``` instead of  ``` `[${categories}]` ```
But it's still gives me the same error as JSON.stringify(categories)
`"Invalid value { '$contains': '[\"eum\",\"quos\"]' }"`

**Comment by thoriqadillah** [comment]
The strange thing about this, fyi I turned on the logging. Sometimes the error show the query log, some time doesn't. Is that normal?

**Comment by fzn0x** [comment]
> "Invalid value { '$contains': '[\"eum\",\"quos\"]' }"

{ '$contains': '[\"eum\",\"quos\"]' }" <-  I think this error already give you a hint what you need to remove, which is the slash `\`

**Comment by fzn0x** [comment]
> wait what So, if I was gonna make it one liner:
> 
> ```js
> const queryParam = 'eum,quos'
> const categories = queryParam.split(',').map(value => `"${value}"`).join(',')
> ```
> 
> so that will not make it array of string with length of 2 when I parse it again to `` [`${categories}`] ``, is it?

You can also make it one-liner, my solution just for the double quotes flow.

**Comment by fzn0x** [comment]
Just for test, maybe you can just hard coded it, if it's works you can try to figure out yourself how to fix the value for `$contains` property.

**Comment by thoriqadillah** [comment]
> "Invalid value { '$contains': '[\"eum\",\"quos\"]' }" <- I think this error already give you a hint what you need to remove, which is the slash \

I think the slash is autogenerated by the sequelize or something, because when I `console.log` it, the slash did not appear. Beside, isn't the slash for escaping the double quotes? Because it has single quotes on the outside

**Comment by fzn0x** [comment]
> '[\"eum\",\"quos\"]'

![Screenshot 2022-09-24 190302](https://user-images.githubusercontent.com/50759463/192096946-0ea3b0a1-4ef3-43b0-97fd-98f3b276d83c.jpg)

It is console.log behaviour that removes the slash, i think you need to replace the slash to empty string

**Comment by thoriqadillah** [comment]
I'll let you know when I try it out. Need to work on something else

**Comment by thoriqadillah** [comment]
it turns out.... still doesnt work
```js
const categories = req.categories.split(',').map(el => `"${el}"`).join(',')

include: [{
  model: Training,
  as: 'training',
  where: {
    "categories::jsonb": {
       $contains: `[${categories}]`.replace(/\\"/g, '"')
    }
  },
}]
```
```
"message": "Invalid value { '$contains': '[\"eum\",\"quos\"]' }",
```

**Comment by ephys** [comment]
I don't think the `::jsonb` cast syntax is available everywhere yet. It's on my backlog to support it everywhere

I also don't know whether `$contains` still works in v6. It's been deprecated for a while and I wouldn't be surprised if it were removed already. Instead you need to use `Op.contains`

Finally, use the "logging" option to see what SQL is produced by your query, that'll be a big help for us

Anyway, I haven't tested this but I think this should work: You need to cast the value, not the column. The column is already JSONB and the `@>` operator requires the right operand to also be JSONB (without the cast, its sql type will be `text`):

```ts
import { where, Op } from 'sequelize';

YourModel.findAll({
  // ...
  include: [{
    // ...
    where: { 
      categories: {
        [Op.contains]: cast(req.categories.split(','), 'jsonb'),
      },
    },
  }],
});
```

I'll test in a proper environment if this doesn't work. If it doesn't work, use the logging option to show us what the generated SQL looks like

**Comment by fzn0x** [comment]
Thanks @ephys for the suggestion ! We tried everything and none seems working for him. Logging option is clever way to see what's wrong, can you tried again with her suggestion and solution @thoriqadillah ?

**Comment by thoriqadillah** [comment]
I tried @ephys with the following code
```js
const categories = req.categories.split(',')

include: [{
  model: Training,
  as: 'training',
  where: {
    "categories::jsonb": {
       [Op.contains]: cast(JSON.stringify(categories), 'json')
    }
  },
}]
```
First of all, I tried the exact @ephys suggestion with `[Op.contains]: cast(categories, 'jsonb')`, but it gives me error `"cannot cast type text[] to json"`, so I stringify it, but still gives me error `operator does not exist: json @> jsonb`. Since my actual field type is `json` instead of `jsonb`, so I change it to cast to json. But still, yet another error `operator does not exist: json @> json`. The logged query of the code above as follows :
```
Executing (default): SELECT count("TrainingClassStudent"."id") AS "count" FROM "public"."training_class_students" AS "TrainingClassStudent" INNER JOIN "public"."training_classes" AS "classes" ON "TrainingClassStudent"."training_class_id" = "classes"."id" AND ("classes"."deleted_at" IS NULL AND "classes"."id" = "TrainingClassStudent"."training_class_id") INNER JOIN "public"."trainings" AS "classes->training" ON "classes"."training_id" = "classes->training"."id" AND ("classes->training"."deleted_at" IS NULL AND "classes->training"."categories" @> CAST('["eum","quos"]' AS JSON)) LEFT OUTER JOIN "public"."training_class_subjects" AS "classes->subjects" ON "classes"."id" = "classes->subjects"."training_class_id" AND ("classes->subjects"."deleted_at" IS NULL) WHERE ("TrainingClassStudent"."deleted_at" IS NULL AND "TrainingClassStudent"."student_id" = 2);
Executing (default): SELECT "TrainingClassStudent".*, "classes->subjects"."id" AS "classes.subjects.id", "classes->subjects"."trainer_id" AS "classes.subjects.trainer_id" FROM (SELECT "TrainingClassStudent"."id", "classes"."id" AS "classes.id", "classes"."training_id" AS "classes.training_id", "classes"."slug" AS "classes.slug", "classes"."name" AS "classes.name", "classes"."description" AS "classes.description", "classes"."type" AS "classes.type", "classes"."start_register" AS "classes.start_register", "classes"."end_register" AS "classes.end_register", "classes"."start_class" AS "classes.start_class", "classes"."end_class" AS "classes.end_class", "classes"."price" AS "classes.price", "classes"."discount" AS "classes.discount", "classes"."created_at" AS "classes.createdAt", "classes"."updated_at" AS "classes.updatedAt", "classes"."deleted_at" AS "classes.deletedAt", "classes->training"."id" AS "classes.training.id", "classes->training"."owner_id" AS "classes.training.owner_id", "classes->training"."name" AS "classes.training.name", "classes->training"."categories" AS "classes.training.categories" FROM "public"."training_class_students" AS "TrainingClassStudent" INNER JOIN "public"."training_classes" AS "classes" ON "TrainingClassStudent"."training_class_id" = "classes"."id" AND ("classes"."deleted_at" IS NULL AND "classes"."id" = "TrainingClassStudent"."training_class_id") INNER JOIN "public"."trainings" AS "classes->training" ON "classes"."training_id" = "classes->training"."id" AND ("classes->training"."deleted_at" IS NULL AND "classes->training"."categories" @> CAST('["eum","quos"]' AS JSON)) WHERE ("TrainingClassStudent"."deleted_at" IS NULL AND "TrainingClassStudent"."student_id" = 2) ORDER BY "TrainingClassStudent"."id" ASC LIMIT 10 OFFSET 0) AS "TrainingClassStudent" LEFT OUTER JOIN "public"."training_class_subjects" AS "classes->subjects" ON "classes.id" = "classes->subjects"."training_class_id" AND ("classes->subjects"."deleted_at" IS NULL) ORDER BY "TrainingClassStudent"."id" ASC;
```
PS: changing model definition data type on `categories` doesn't change anything, weather it's `DataTypes.JSON` or `Sequelize.JSONB`

**Comment by ephys** [comment]
> Since my actual field type is json instead of jsonb

That's the thing I was missing :)

You need to cast the column to JSONB but the syntax `categories::jsonb` isn't supported everywhere yet (it's on my backlog) so it's ignored. You can use our `cast()` function instead:

```
const categories = req.categories.split(',')

include: [{
  model: Training,
  as: 'training',
  where: where(
    cast(col('categories'), 'jsonb'),
    Op.contains,
    cast(JSON.stringify(categories), 'json')
  ),
}],
```

Hopefully `where` is not bugged 🤞

**Comment by thoriqadillah** [comment]
Man, I hope I can provide you with better news, but I'm afraid not lol
```js
const { Op, where, cast, col } = require('sequelize');

const categories = req.categories.split(',')

include: [{
  model: Training,
  as: 'training',
  where: where(
    cast(col('categories'), 'jsonb'),
    Op.contains,
    cast(JSON.stringify(categories), 'json')
  ),
}]
```
produces error `operator does not exist: jsonb @> json` with logged query:
```
Executing (default): SELECT count("TrainingClassStudent"."id") AS "count" FROM "public"."training_class_students" AS "TrainingClassStudent" INNER JOIN "public"."training_classes" AS "classes" ON "TrainingClassStudent"."training_class_id" = "classes"."id" AND ("classes"."deleted_at" IS NULL AND "classes"."id" = "TrainingClassStudent"."training_class_id") INNER JOIN "public"."trainings" AS "classes->training" ON "classes"."training_id" = "classes->training"."id" AND ("classes->training"."deleted_at" IS NULL AND CAST("categories" AS JSONB) @> CAST('["eum","quos"]' AS JSON)) LEFT OUTER JOIN "public"."training_class_subjects" AS "classes->subjects" ON "classes"."id" = "classes->subjects"."training_class_id" AND ("classes->subjects"."deleted_at" IS NULL) WHERE ("TrainingClassStudent"."deleted_at" IS NULL AND "TrainingClassStudent"."student_id" = 2);
Executing (default): SELECT "TrainingClassStudent".*, "classes->subjects"."id" AS "classes.subjects.id", "classes->subjects"."trainer_id" AS "classes.subjects.trainer_id" FROM (SELECT "TrainingClassStudent"."id", "classes"."id" AS "classes.id", "classes"."training_id" AS "classes.training_id", "classes"."slug" AS "classes.slug", "classes"."name" AS "classes.name", "classes"."description" AS "classes.description", "classes"."type" AS "classes.type", "classes"."start_register" AS "classes.start_register", "classes"."end_register" AS "classes.end_register", "classes"."start_class" AS "classes.start_class", "classes"."end_class" AS "classes.end_class", "classes"."price" AS "classes.price", "classes"."discount" AS "classes.discount", "classes"."created_at" AS "classes.createdAt", "classes"."updated_at" AS "classes.updatedAt", "classes"."deleted_at" AS "classes.deletedAt", "classes->training"."id" AS "classes.training.id", "classes->training"."owner_id" AS "classes.training.owner_id", "classes->training"."name" AS "classes.training.name", "classes->training"."categories" AS "classes.training.categories" FROM "public"."training_class_students" AS "TrainingClassStudent" INNER JOIN "public"."training_classes" AS "classes" ON "TrainingClassStudent"."training_class_id" = "classes"."id" AND ("classes"."deleted_at" IS NULL AND "classes"."id" = "TrainingClassStudent"."training_class_id") INNER JOIN "public"."trainings" AS "classes->training" ON "classes"."training_id" = "classes->training"."id" AND ("classes->training"."deleted_at" IS NULL AND CAST("categories" AS JSONB) @> CAST('["eum","quos"]' AS JSON)) WHERE ("TrainingClassStudent"."deleted_at" IS NULL AND "TrainingClassStudent"."student_id" = 2) ORDER BY "TrainingClassStudent"."id" ASC LIMIT 10 OFFSET 0) AS "TrainingClassStudent" LEFT OUTER JOIN "public"."training_class_subjects" AS "classes->subjects" ON "classes.id" = "classes->subjects"."training_class_id" AND ("classes->subjects"."deleted_at" IS NULL) ORDER BY "TrainingClassStudent"."id" ASC;
```

**Comment by ephys** [comment]
Woops, my bad, the second cast must be JSONB too, not json

**Comment by thoriqadillah** [comment]
wait, actually when I change the casting `cast(JSON.stringify(categories), 'json')` from `json` to `jsonb`, it works. But somehow it gave me zero data, even though there are categories with `eum` and `quos` 
Maybe I will debug this later after finishing something I'm gonna do

**Comment by thoriqadillah** [comment]
Maybe this is the last question, what `Op.contains` do? Is it just like `and` or `or`? I assume it's `and` right? So what is the `or` here? Because it's actually work if I filter it with `eum` only instead `eum,quos`. I'm so happy now

**Comment by ephys** [comment]
It is AND. The OR version would be the overlap operator but overlap (Op.overlap) doesn't exist with JSON, you need to cast to a string array instead (or better: make the column a string array instead of JSON)

**Comment by thoriqadillah** [comment]
how to cast json to array? I tried 
```js
where(
  cast(col('categories'), 'text[]'),
  Op.overlap,
  categories
)
```
and get error `cannot cast type json to text[]`

**Comment by ephys** [comment]
You can use `json_array_elements_text`

```js
where(
  fn('json_array_elements_text', col('categories')),
  Op.overlap,
  categories
)
```

**Comment by thoriqadillah** [comment]
I'm sorry if this is bothering you, but I get an error `set-returning functions are not allowed in JOIN conditions`

**Comment by ephys** [comment]
Well looks like there is a way to do overlap with JSONB: The `jsonb ?| text[]` operator. The problem is we don't support that operator yet :/

The following *may* work, but will break in v7:

```js
where(
  cast(col('categories'), 'jsonb'),
  '?|',
  categories
)
```

The following should also work (in v6 and v7, and is the way I'd recommend):

```js
const categories = req.categories.split(',');

findAll({
  include: [{
    model: Training,
    as: 'training',
    where: literal('categories ?| :categories'),
  }],
  replacements: { categories },
}),
```

> I'm sorry if this is bothering you

not at all :)

**Comment by thoriqadillah** [comment]
Currently my query looking like this, 
```js
return Model.findAndCountAll({
      //...
      include: [{
        //...
        include: [
          {
            model: Training,
            as: 'training',
            where: literal('categories::jsonb ?| :categories'),
          },
        ],
      }],
      replacements: { categories }, 
    })
```
And is still give me error `syntax error at or near \")\""`. And when I chane the position of the `replacement` more inside, the error turns to `syntax error at or near \":\""`

But I wonder if I change `categories` data type to `text[]` in the db, is the query would be just 
```js
where: {
  categories: {
    [Op.overlap]: req.categories.split(',') 
  }
}
```
I have tried it but it gave me zero data even though the db has it, e.g i the categories i query is `quis,est`, and the categories field has` ['quis', 'enim', ..]` and `['est', ... ]` but gave me zero data on query results

**Comment by thoriqadillah** [comment]
Update: I mistakenly querying `quis,est`, but the thing is, the query I did is for certain user id. And the query I did produces result that has no `quis` or `est` on the categories, so that is why I got zero result
