### ISSUE TITLE
Contribution guidelines contain outdated instructions for databases

### ISSUE THREAD

**Issue by friendofdog** [sequelize/sequelize#15078]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

The contribution guidelines contain [instructions on setting up databases with Docker](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#31-with-docker-recommended) which predate [a recent PR](https://github.com/sequelize/sequelize/pull/14737) which make these instructions obsolete.

### What was unclear/insufficient/not covered in the documentation

For example, contribution guidelines state that Postgres can be set up in Docker by running `yarn start-postgres`. With the oldest/latest naming scheme in place, this becomes either `start-postgres-oldest` or `start-postgres-latest`. This applies to all other databases covered in the guidelines.

### If possible: Provide some suggestion on how we can enhance the docs

Replace the old command with the new ones, explaining the difference between the two.

### Additional context

Related to #14737

**Comment by WikiRik** [comment]
True, thanks for creating the issue! As @fzn0x added, this would be a nice one to tackle for hacktoberfest. Feel free to open a PR yourself if you want

**Comment by friendofdog** [comment]
I'm on it
