### ISSUE TITLE
precompile in sequelize update

### ISSUE THREAD

**Issue by shinku** [sequelize/sequelize#15105]
### Describe the feature you'd like to see implemented

when i use Model.update 
such as 
```
await Table.update({name:"shingu"},{where:{
   id:{
     [Op.gt]: 100
   }
}})
```
which precompile  sql shuld be 
```sql
update table set name = ? where id > ? , 'shingu', 100
```
but 
```sql
update table set name = ? where id > 100 , 'shingu'
```
it will make precompile cache to the max in some conditions.
according to related code
function `whereParseSingleValueObject` in `QueryGenerator` , when prop is in Op.lt,Op.gt,Op.eq ....nothing is done here,
so,could you update this function in the future feature to make my description to be done?

**Comment by ephys** [comment]
This is the same issue as #13972, this is something we'd like to do at some point

**Comment by shinku** [comment]
thanks bro~

**Comment by shinku** [comment]
> This is the same issue as #13972, this is something we'd like to do at some point

thanks~bro
