### ISSUE TITLE
Sleeping Connections

### ISSUE THREAD

**Issue by scriptsure** [sequelize/sequelize#15116]
### Reproducible Example
Right now the way i load my models is by using an index.js file that creates the connection and loads all the models into sequelize. It looks like below:

```javascript
'use strict';

var fs = require('fs');
var path = require('path');
var Sequelize = require('sequelize');
var basename = path.basename(module.filename);
var config = require('config').db;
var sequelize = new Sequelize(config.database, config.username, config.password, config);
var db = {};

fs
    .readdirSync(__dirname)
    .filter(function (file) {
        return (file.indexOf('.') !== 0) && (file !== basename);
    })
    .forEach(function (file) {
        var model = sequelize['import'](path.join(__dirname, file));
        db[model.name] = model;
    });

Object.keys(db).forEach(function (modelName) {
    if ('associate' in db[modelName]) {
        db[modelName].associate(db);
    }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

I thought that having a pool setup in my configuration that the connections would be managed by sequelize, but it seems to be ignoring those settings. I know others have opened cases like this but I am unable to find a good solution. ALSO, we are in the middle of upgrade to hopefully 7, but it will not be done for another 5 months. 

Here is my config that indicates my pool settings:
```javascript
"db": {
  "host": “***”,
  "username": “***”,
  "password": “***”,
  "database": “db”,
  "dialect": "mysql",
  "logging": false,
  "dialectOptions": {
    "ssl": "Amazon RDS"
  },
  "pool": {
    "max": 5,
    "min": 0,
    "acquire": 30000,
    "idle": 10000
  }
},
```

As described in the config we are using RDS MySql. I believe that the connections are causing erratic behavior with the application, slowness and impacting hardware. 

### What do you expect to happen?

I expected based on my pool settings that there would not be so many connections open, and that if left idle they would close after a certain duration of time. 

If the pool has some issues in v3, how would you recommend manually closing connections?
Is the index.js file the appropriate approach? 

### What is actually happening?

Connections are left open sleeping on MySql. They are utilizing RAM and causing slowness. There are 127 open at the moment:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/798281/195152277-1b75420f-d9b5-478b-8960-c5eb69807c85.png">

### Environment
- Sequelize version: 3.30.4
- Node.js version: 8.9.4
- If TypeScript related: TypeScript version: 2.7.1
- Database & Version: 5.7
- Connector library & Version: mysql 2.17.1

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
We do not support sequelize v3 anymore.

**Comment by ephys** [comment]
Yes unfortunately we can't be of much help because most of the team has arrived years after v3 was still maintained. We basically know just as much about the v3 codebase as you do :(

It's very possible that the pool is completely bugged in v3. I haven't seen such issues for v6
