### ISSUE TITLE
SQL Server - Create Index donot have support for "Include"

### ISSUE THREAD

**Issue by vsinghal3392222** [sequelize/sequelize#15124]
Below is the basic command for creating index in SQL Server. The below command also has "INCLUDE" key which sequelize donot support while creating indexing

/*
USE [cube-qa]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[has_roles] ([resourceType])
INCLUDE ([resourceType],[resourceId])
GO
*/

**Comment by lohart13** [comment]
I've created a PR for this, see #14900
