### ISSUE TITLE
Facilitation of the implementation of JOINS

### ISSUE THREAD

**Issue by rafaelmoraes003** [sequelize/sequelize#15136]
## FEATURE

One issue that I personally find complicated when using sequelize (both in functional and OOP form) is the way to create and structure SQL `JOINS`.

One suggestion I would like to propose is how to organize and facilitate this implementation even more

## CURRENT CASE

Let's suppose I need to create a JOIN between two tables to arrange information. The relationship of these tables is 1:N, so it would look like this:

```
class Match extends Model { ... }

Match.init({ ... },
}, {
  sequelize: db,
  modelName: 'some_model',
  underscored: true,
  timestamps: false,
});

  Match.belongsTo(Team, {
  foreignKey: 'homeTeam', as: 'teamHome',
});

Match.belongsTo(Team, {
  foreignKey: 'awayTeam', as: 'teamAway',
});
```

### The query implementation would be something like this:

```
const getMatches = async () => {
  const matches = await Match.findAll({
    include: [
      {
        model: Team,
        as: 'teamHome',
        attributes: { exclude: ['id'] },
      },
      {
        model: Team,
        as: 'teamAway',
        attributes: { exclude: ['id'] },
      },
    ],
  });

  return matches;
};
```
###

`The context of this query is that I want to show the result of soccer matches and, in each match, I show the ID of the home and away team. To be user-friendly, two properties are available (teamHome and teamAway) that show the names of teams based on their IDs (that's where JOIN comes from).`

## FEATURE IMPLEMENTATION

The point of facilitating the implementation is that, in the current case, it is necessary to prepare the JOIN both in the Model of the table and in the implementation of the Sequelize query. My facilitation proposal would look like this:

```
const getMatches = async () => {
  const matches = await Match.findAll({
    includes: [
        {
            model: Team,
            as: 'teamHome',
            joinType: 'inner',
            on: {
                '__currModel.id':  'model.teamName',
            },
        },
        {
            model: Team,
            as: 'teamAway',
            joinType: 'inner',
            on: {
               '__currModel.id':  'model.teamName'
            },
        }
    ]
  });

  return matches;
};
```

`In this scenario, it would no longer be implementing the JOIN in the Model of the table, everything would be done in the query itself.` 

In this query, the JOIN would be delimited by the includes property (which can be either an array or an object). It receives one or more objects with the following properties:

```
model: the reference model for performing the JOIN,
as: How the property should be called in the data arrangement,
joinType: The type of JOIN to be made (inner, left or right)
on: Condition for the JOIN to be performed, receiving an key-value object with the condition.

```

## CONCLUSION

This is just a feature suggestion that would make the developer experience even easier. I hope you kindly review it.

**Comment by ephys** [comment]
We're working on providing a way to do arbitrary joins. We don't have an ETA, we're still figuring out what the API would look like ([current draft](https://6341ba52a568737283945fd0--sequelize-site.netlify.app/docs/v7/core-concepts/querying/))

However writing something like this would not be possible. The code in parentheses would end up being a boolean in JS instead of an SQL condition

```
on: (__currModel.id === model.teamName),
```

**Comment by rafaelmoraes003** [comment]
Thank you for the advice. I think a better way then would be like:

```
on: {
     '__currModel.id': 'model.teamNamr'
}
```

**Comment by ephys** [comment]
This is already almost how `on` works, but not quite:

```
on: {
     '__currModel.id': 'model.teamName'
}
```

- You don't need to specify `__currModel`, `on` already knows which model it's assigned to. It's just `id`
- `'model.teamName'` would match the string `model.teamName`, not the column. Columns can be referenced using `col`

```ts
User.findAll({
  include: {
    project: {
      on: { id: col('user.teamName') },
    },
  },
});
```

Right now it's difficult to determine what `User` will be called in the query (user? User? users?). I'd like to add an alias option in https://github.com/sequelize/sequelize/issues/15260 to make that deterministic.

I'll close this issue in favor of https://github.com/sequelize/sequelize/issues/15260
