### ISSUE TITLE
Nested include is returning first initials of attributes name

### ISSUE THREAD

**Issue by rishat5081** [sequelize/sequelize#15198]
This is weird that I am using multi include but in patientAnswers model, it gives me the first alphabet of the column.

if i see the query it is selecting the first initials of the table

`  {
    "id": 2,
    "name": "Collateral History",
    "subSections": [
      {
        "id": 4,
        "name": "Questionnaire",
        "questions": [
          {
            "id": 1,
            "question": "primary school report cards comments included: (select all that apply)",
            "answers": [
              {
                "id": 1,
                "answer": "Easily distracted",
                "preConsultations": [
                  {
                    "id": 1,
                    "patientAnswers": {
                      "s": null,
                      "i": null,
                      "q": 1,
                      "a": 1,
                      "p": 1,
                      "d": null,
                      "c": "2022-10-28T12:43:09.348Z",
                      "u": "2022-10-28T12:43:09.348Z"
                    }
                  }
                ]
              },`

**### here is the log query** 

` SELECT "questionsection"."id", "questionsection"."name", "subSections"."id" AS "subSections.id", "subSections"."name" AS "subSections.name", "subSections->questions"."id" AS "subSections.questions.id", "subSections->questions"."question" AS "subSections.questions.question", "subSections->questions->answers"."id" AS "subSections.questions.answers.id", "subSections->questions->answers"."answer" AS "subSections.questions.answers.answer", "subSections->questions->answers->preConsultations"."id" AS "subSections.questions.answers.preConsultations.id", "subSections->questions->answers->preConsultations->patientAnswers"."selected" AS "subSections.questions.answers.preConsultations.patientAnswers.selected", "subSections->questions->answers->preConsultations->patientAnswers"."isDeleted" AS "subSections.questions.answers.preConsultations.patientAnswers.isDeleted", "subSections->questions->answers->preConsultations->patientAnswers"."sectionId" AS "subSections.questions.answers.preConsultations.patientAnswers.sectionId", "subSections->questions->answers->preConsultations->patientAnswers"."subSectionId" AS "subSections.questions.answers.preConsultations.patientAnswers.subSectionId", "subSections->questions->answers->preConsultations->patientAnswers"."questionId" AS "subSections.questions.answers.preConsultations.patientAnswers.questionId", "subSections->questions->answers->preConsultations->patientAnswers"."answerId" AS "subSections.questions.answers.preConsultations.patientAnswers.answerId", "subSections->questions->answers->preConsultations->patientAnswers"."patientId" AS "subSections.questions.answers.preConsultations.patientAnswers.patientId", "subSections->questions->answers->preConsultations->patientAnswers"."preConsultationId" AS "subSections.questions.answers.preConsultations.patientAnswers.preConsultationId", "subSections->questions->answers->preConsultations->patientAnswers"."status" AS "subSections.questions.answers.preConsultations.patientAnswers.status", "subSections->questions->answers->preConsultations->patientAnswers"."deletedAt" AS "subSections.questions.answers.preConsultations.patientAnswers.deletedAt", "subSections->questions->answers->preConsultations->patientAnswers"."createdAt" AS "subSections.questions.answers.preConsultations.patientAnswers.createdAt", "subSections->questions->answers->preConsultations->patientAnswers"."updatedAt" AS "subSections.questions.answers.preConsultations.patientAnswers.updatedAt" FROM "questionsections" AS "questionsection" INNER JOIN "subsections" AS "subSections" ON "questionsection"."id" = "subSections"."sectionId" INNER JOIN "questions" AS "subSections->questions" ON "subSections"."id" = "subSections->questions"."subSectionId" INNER JOIN "answers" AS "subSections->questions->answers" ON "subSections->questions"."id" = "subSections->questions->answers"."questionId" INNER JOIN ( "patientAnswers" AS "subSections->questions->answers->preConsultations->patientAnswers" INNER JOIN "preConsultations" AS "subSections->questions->answers->preConsultations" ON "subSections->questions->answers->preConsultations"."id" = "subSections->questions->answers->preConsultations->patientAnswers"."preConsultationId") ON "subSections->questions->answers"."id" = "subSections->questions->answers->preConsultations->patientAnswers"."answerId" AND "subSections->questions->answers->preConsultations"."patientId" = 12;`

**Comment by manojmula** [comment]
Hi @rishat5081 can you also share sequilize query?

**Comment by ephys** [comment]
This is because the identifiers generated by sequelize are becoming too long.

You can solve that by one of three ways:

- use the "minifyAliases" option. Unfortunately that options goes on the Sequelize constructor, not on individual queries. In a future update I'd live to make that option available on individual queries (and print an error when sequelize generates identifiers that are too long)
- split your query, reduce the number of includes and load them after your query
- use a raw query using sequelize.query, but you'd need to write raw sql

**Comment by manojmula** [comment]
I use kind of complex quires throughout the project , never faced this kind of issue.
I believe there might be some syntactical error which JS might not catch while compiling. but @rishat5081 sharing sequelize query will really help us in debugging.

**Comment by ephys** [comment]
Identifiers are truncated at around 63 characters (depends on the dialect), `subSections.questions.answers.preConsultations.patientAnswers.selected` is 70 characters. Truncated to 63, it results in `subSections.questions.answers.preConsultations.patientAnswers.s`. Sequelize parses that and creates a property called `s`. 
It's a known issue with https://github.com/sequelize/sequelize/issues/15198#issuecomment-1312684973 being the only solution

I'll close this issue but have opened https://github.com/sequelize/sequelize/issues/15362 and https://github.com/sequelize/sequelize/issues/15361
