### ISSUE TITLE
Can you update a value that is from an enum?

### ISSUE THREAD

**Issue by TannerS** [sequelize/sequelize#15194]
I currently created a column in a table thats an enum

```
 max: {
          type: DataTypes.ENUM('2', '5'),
          allowNull: false,
        },
```

and so I can create values in this table with either 2 or 5, but when I try to update it, i get this error 

```
ERROR:  column "max" is of type enum_expression_max but expression is of type integer

```

when trying to update (i hardcoded it to test)

```
 await model.update({
      max: 3
    }, { transaction: t });
    ```

is this not allowed?

**Comment by fzn0x** [comment]
It is not allowed by design, you can only update it to whether 2 or 5, if you tried to update it to other values, SQL will throws error.

You need to use `changeColumn` and change your enum to accept `3` instead.

**Comment by fzn0x** [comment]
https://sequelize.org/docs/v6/other-topics/other-data-types/#enums

> The ENUM is a data type that accepts only a few values, specified as a list.
