### ISSUE TITLE
default value cannot be updated

### ISSUE THREAD

**Issue by chengpengjava** [sequelize/sequelize#15192]
Hello,team.
I found that a model field has a default value, I cannot modify the value in its database.The detailed steps are as follows:
1.I created a table in the database:
![image](https://user-images.githubusercontent.com/33616855/198274639-bdde3ee8-994e-42d9-a02c-fa8168785f00.png)
Among them, I have set the default value ‘0’ for the status field,and then I added a data:
![image](https://user-images.githubusercontent.com/33616855/198274926-a3b83e3a-487e-44a4-ab4a-ea84f20bb862.png)
2.I created sequelize model for it:
![image](https://user-images.githubusercontent.com/33616855/198275071-fa2dc8bf-8ba8-42f7-ad83-bd716b4299df.png)
3.I tried to modify status field but failed:
![image](https://user-images.githubusercontent.com/33616855/198275454-add06842-5cab-48b3-9458-7c067ef7abd7.png)
![image](https://user-images.githubusercontent.com/33616855/198275490-fb552c17-fbfb-4ef7-8889-b676913d8c66.png)
I have tried to modify other fields successfully,I can't find any explanation about this problem in the official document,so what should I do?

sequelize version:@6.25.3
node version:v16.15.1
database:mysql.
database version:mysql2@2.3.3

Thanks!

**Comment by fzn0x** [comment]
Questions:
- Are you already check your database?
- Is the `id` you set is really exists?
- Do we recommend checking the updated values using `console.log('---1.1---', num)`?

This shouldn't happen that's why we don't document it, to avoid such questions, if it's bug can you please recreate the reproduction using SSCCE?

**Comment by chengpengjava** [comment]
> Questions:
> 
> * Are you already check your database?
> * Is the `id` you set is really exists?
> * Do we recommend checking the updated values using `console.log('---1.1---', num)`?
> 
> This shouldn't happen that's why we don't document it, to avoid such questions, if it's bug can you please recreate the reproduction using SSCCE?

Yeah,I checked the database,the current data is as follows:
![image](https://user-images.githubusercontent.com/33616855/198473619-6f376bca-6aa1-4e5a-a495-2fa3876808b6.png)
Now,I ran following and result:
![image](https://user-images.githubusercontent.com/33616855/198474100-9d7f96cf-b9cd-4742-825f-9f2db4d80ab7.png)
let me see database:
![image](https://user-images.githubusercontent.com/33616855/198474472-f507c586-38f6-4eb6-8223-0aafa8daad80.png)
I don't know why.The only thing I can guess is that this may have something to do with the field `status` have default value in model.
I'd like to put this question down in SSCCE,but I don't know what it is.Maybe I'll spend some time studying it. I'll finish these things in my free time.
Thank you.

**Comment by chengpengjava** [comment]
I found that it was not the default value,because I canceled the default value of this field:
![image](https://user-images.githubusercontent.com/33616855/198489554-d10548e0-9b94-4bd9-bf32-9bb5cd28bc92.png)
Now the data is following:
![image](https://user-images.githubusercontent.com/33616855/198489760-66aca910-c51e-4e8a-b47c-54e2bba69dd7.png)
I ran following and result:
![image](https://user-images.githubusercontent.com/33616855/198490422-0eaa33fd-4b57-4eab-8c03-79fa05c5afd8.png)
I don't know what the problem is...

**Comment by chengpengjava** [comment]
Oh my god,I know what the problem is,I replaced `status: 1` with `status: '1'`and the result:
![image](https://user-images.githubusercontent.com/33616855/198497419-737060ef-30a8-4139-923b-09dc38fa53e7.png)
Therefore, sequelize cannot recognize the data of `Number` must be replaced with a `string` when executing the `update` method,is that so?
I think it is better to explain this in the document, otherwise it is difficult for people to think of this. After all, the model field is integer and people will subconsciously pass an `Number`
