### ISSUE TITLE
How to connect to custom logging?

### ISSUE THREAD

**Issue by kenperkins** [sequelize/sequelize#152]
All of my node applications use [Winston](https://github.com/flatiron/winston) for logging and I'd love to be able to connect Sequelize to use an existing logging framework. How or can this be done?

If not, is it something I could prototype and create a pull request (to start the dialog about how this would be done)

Thanks!

**Comment by gzurbach** [comment]
I ran into the same question today and ended up doing this:

```
var winston = require('winston');
var sequelize = new Sequelize(config.mysql.database, config.mysql.user, config.mysql.password, {
    host: config.mysql.host,
    port: config.mysql.port,
    logging: winston.info
});
```

Seems to work like a charm. Hope it helps someone :)

**Comment by OsoianMarcel** [comment]
In my case, this works: 
```js
{
    logging: logger.debug.bind(logger)
}
```
