### ISSUE TITLE
How to catch mysql signal messages

### ISSUE THREAD

**Issue by kerog** [sequelize/sequelize#1522]
Hi I write a software using node.js + mysql + sequelize, In mysql triggers I have SIGNAL statement with message text. How to get message text in sequelize? Simple example is on http://stackoverflow.com/a/7189396.
Regards

**Comment by 9662** [comment]
@janmeier : I am not @kerog, but I am guessing that what he's after is a way of capturing the [`SIGNAL`](https://dev.mysql.com/doc/refman/5.6/en/signal.html)'s [`MESSAGE_TEXT`](https://dev.mysql.com/doc/refman/5.6/en/signal.html#signal-condition-information-items)` information item.

As he points out, that seems to be passed on to Node, as it appears in the error's message (see the stack trace in his [example above](#issuecomment-38061185)).

This is possibly more of a [node-mysql](/felixge/node-mysql) question as has already been pointed out, but it would appear to me that, as the returned error is an [`Error` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error), one could access the value of `MESSAGE_TEXT` via [`Error.prototype.message`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message). Perhaps @felixge can confirm?

So, to take the code above as an example:

```javascript
//var mysql      = require('mysql');
var Sequelize = require("sequelize");
//var connection = mysql.createConnection({
//  host     : '192.168.1.25',
//  user     : 'interCT',
//  password : 'InterCTS$M',
//  database : 'ec_dev_v0_8_1'
//});
var seq = new Sequelize('ec_dev_v0_8_1','interCT','InterCTS$M',{
    host: '192.168.1.25',
    dialect: 'mysql'
});
seq.query('insert into _test values (-1)',null,{
    raw: false
})
    .success(function(data){
        console.log(data);
    })
        .error(function(error){
            var errorParts = error.message.split(':');
            if (errorParts[0] == 'ER_SIGNAL_EXCEPTION' && errorParts[1] == 'MyTriggerError') {
                console.log("You tried to insert the negative value " + errorParts[3] + ", which the database doesn't want you to do. Please be more positive next time.");
            } else {
                console.log(error);
            }
        })

//connection.connect();
//
//connection.query('insert into _test values (-1)', function(err, rows, fields) {
//  console.log(err);
//  console.log(rows);
//  console.log(fields);
//  if (err) throw err;
//
//});
//
//connection.end();
```

I am just taking a guess here as to what @kerog might be describing. Apologies if I got this wrong.

**Comment by janmeier** [comment]
We inherit the message from the error thrown from node-mysql https://github.com/sequelize/sequelize/blob/e6c6ac35e2e00ed1fd95996af4364842987be287/lib/errors.js#L84, so it should be available
