### ISSUE TITLE
Current MySQL/MariaDB/postgres nested JSON operations make it impossible to distinguish between the JSON `null`/`true` and a JSON string containing `"null"`/`"true"`

### ISSUE THREAD

**Issue by ephys** [sequelize/sequelize#15238]
## Bug Description

Take the following example:

```ts
const Test = sequelize.define('Test', {
  json: DataTypes.JSON,
});

await sequelize.sync({ force: true });

await Test.create({
  json: { name: 'null' },
});

const results = await Test.findAll({
  where: {
    json: {
      name: null,
    },
  },
});

expect(results).to.have.lengthOf(0);
```

It's trying to find all users who don't have a last name set. The last name is stored in a JSON field. Unfortunately it's returning all users whose last name is `"null"`.

This is the query it's using:

```sql
SELECT `id`, `json` FROM `Tests` AS `Test`
WHERE json_unquote(json_extract(`Test`.`json`,'$.\"name\"')) = 'null'
```

The root of the problem is `json_unquote`. Because of `json_unquote`, it's impossible to distinguish between `null` an `"null"`, because they both become `null` when passed to `json_unquote`.

This is crazy because it's exactly what MySQL recommends. They even added the [`->>`](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-inline-path) operator as a shorthand for `JSON_UNQUOTE(JSON_EXTRACT)`, but it's completely broken.

We have the same issue with `true` and `"true"`, `1` and `"1"`, etc.

This `json_unquote` must go away. Instead we must call `JSON.stringify` on the value provided by the user.

If we take a query like this:

```ts
const results = await Test.findAll({
  where: {
    json: {
      name: "john",
    },
  },
});
```

Instead of producing this query:

```sql
SELECT `id`, `json` FROM `Tests` AS `Test`
WHERE json_unquote(json_extract(`Test`.`json`,'$.\"name\"')) = 'john'
```

It must produce this query:

```sql
SELECT `id`, `json` FROM `Tests` AS `Test`
WHERE json_extract(`Test`.`json`,'$.\"name\"') = '"John"' -- <- notice the quotes around the string
```

---

This would be a breaking change because literals are going to be affected. replacements and bind parameters would also break, which is a huge caveat that will need to be documented :/ (the user will need to call `JSON.stringify` on these values)

### Environment

- Sequelize version: 6.25.1, ^7.0.0-alpha.16
- Node.js version: 16.17.1
- If TypeScript related: TypeScript version: N/A
- Database & Version: MySQL 8.0.32
- Connector library & Version: mysql2 - 2.3.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by frostzt** [comment]
Hey @ephys can I pick this up?

**Comment by WikiRik** [comment]
Maybe we should put this behaviour as an option so it's not enabled by default? I think that replacements and bind parameters should work in the most cases possible

**Comment by ephys** [comment]
I don't think we should put it behind an option. If we do, no one is going to realize the issue during development and won't realize their code has bugs until it crashes in production :/

If we look at the possible scenarios, only one is impacted, the first one:

## Scenario 1: Bind params or replacements in Model methods

This is the only scenario where the user would have do something differently from what they do today: If they try to use a bind parameter of replacement with a model method (such as `findAll`), we're currently unable to know what the type of the replacement is, and we won't be able to call `JSON.stringify` on it:

```ts
Test.findAll({
  where: {
    json: {
      name: literal('$name'),
    },
  },
  replacements: {
    name: 'John',
  },
})
```

would produce


```sql
SELECT `id`, `json` FROM `Tests` AS `Test`
WHERE json_extract(`Test`.`json`,'$.\"name\"') = 'John'
```

That condition will always be false, making it very likely that the developer will notice the issue during development, and be able to fix it.

The fix is also very simple since the user can simply JSON stringify the parameter:

```ts
Test.findAll({
  where: {
    json: {
      name: literal('$name'),
    },
  },
  replacements: {
    name: JSON.stringify('John'),
  },
})
```

Or, once we support https://github.com/sequelize/sequelize/issues/14410, by specifying the type of their replacement:

```ts
Test.findAll({
  where: {
    json: {
      name: literal('$name'),
    },
  },
  replacements: {
    name: 'John',
  },
  // really not set on how to specify them
  replacementTypes: {
    name: DataTypes.JSON,
  },
})
```

both of which would produce

```sql
SELECT `id`, `json` FROM `Tests` AS `Test`
WHERE json_extract(`Test`.`json`,'$.\"name\"') = '"John"' -- <- notice the quotes around the string
```

## Scenario 2: Raw Queries

The query is already raw so it's already up to the user whether they use `json_unquote` or not. No changes there.

## Scenario 3: Typical model method calls (replacements)

Say the user writes the following:

```ts
Test.findAll({
  where: {
    json: {
      name: 'John',
    },
  },
})
```

We know `json` is a `JSON` DataType, so we can stringify the value accordingly. No change for the user. We'll transparently produce the following query

```sql
SELECT `id`, `json` FROM `Tests` AS `Test`
WHERE json_extract(`Test`.`json`,'$.\"name\"') = '"John"'
```

Instead of this broken one:

```sql
SELECT `id`, `json` FROM `Tests` AS `Test`
WHERE json_unquote(json_extract(`Test`.`json`,'$.\"name\"')) = 'John'
```

## Scenario 4: Typical model method calls (bind params)

Some methods, like `Model.update` use bind parameters instead of replacements. But the same concept applies. We're responsible for generating these bind parameters so we can stringify them ourselves.

```ts
Test.update({ password: null }, {
  where: {
    json: {
      name: 'John',
    },
  },
})
```

will produce this:

```sql
UPDATE `Tests` SET `password` = ?
WHERE json_unquote(json_extract(`Test`.`json`,'$.\"name\"')) = ?
```

with bind parameters

```ts
// note how the second bind parameter has been JSON.stringify-ed by Sequelize
[null, '"John"']
```

**Comment by ephys** [comment]
> Hey @ephys can I pick this up? Would love to have your advice on how to go about it.

For sure! I'll edit this post with all the information I have

**Comment by WikiRik** [comment]
If we're updating `jsonPathExtractionQuery` it might be nice to merge this PR first; https://github.com/sequelize/sequelize/pull/15236

**Comment by ephys** [comment]
I'll go took a look at it :)

**Comment by ephys** [comment]
We have the same issue in postgres with boolean & numeric keys, here is a failing test:

```ts
await User.create({
  json: {
    name: 'true',
  }
})

const data = await User.findAll({
  where: {
    json: {
      name: true,
    }
  }
});
  
expect(data).to.have.length(0);
```

**Comment by WikiRik** [comment]
On the postgres topic; we have https://github.com/sequelize/sequelize/issues/14066 and associated PR https://github.com/sequelize/sequelize/issues/14099 to keep in mind as well

**Comment by frostzt** [comment]
Hey @ephys yeah seems like this is gonna be a hard one, but someday will have to start on hard ones right :p do you think I would be able to take this on? Like maybe you and Rik can also guide me (ofc only when you have time) and I will also keep working on it post work?

**Comment by ephys** [comment]
@WikiRik good opportunity to handle it at the same time. The same logic applies too, we should use `->` and not `->>`

@frostzt I honestly don't know. You can give it a try but it's definitely a complicated one

If you want to work on it I'd propose to do it in two steps: first write/update the unit tests, then we can look into implementing the code

We already have unit tests for JSON operations here:
https://github.com/sequelize/sequelize/blob/main/test/unit/sql/where.test.ts#L2134
https://github.com/sequelize/sequelize/blob/main/test/unit/sql/json.test.js#L98
https://github.com/sequelize/sequelize/blob/main/test/unit/sql/json.test.js#L167

They'll need to be updated. They can be regrouped in the same test file (such as `json.test.ts` (note the ts extension)). Then for each one possible value we need to decide what the behavior should be.

But again just for one dialect this is going to be a lot of work. This long post is just about postgres

There are multiple things to test such as:

## how the json path is generated:

```ts
testSql({
  jsonAttr: 'myString',
});
```

produces:

```
"jsonAttr" = '"myString"'
```

---

```ts
testSql({
  'jsonAttr.nested': 'myString',
});
```

or

```ts
testSql({
  'jsonAttr': {
    nested: 'myString',
  },
});
```

produce

```
"jsonAttr"->'nested' = '"myString"'
```

---

```ts
testSql({
  'jsonAttr.0': 'myString',
});
```

or

```ts
testSql({
  'jsonAttr': {
    0: 'myString',
  },
});
```

produces

```
"jsonAttr"->0 = '"myString"'
```

---

```ts
testSql({
  'jsonAttr.nested.twice': 'myString',
});
```

or

```ts
testSql({
  'jsonAttr': {
    nested: {
      twice: 'myString',
    }
  },
});
```

produces

```
("jsonAttr"#>ARRAY['nested', 'twice']) = '"myString"'
```

## how each JSON type is compared:

### string

```ts
testSql({
  jsonAttr: 'myString',
});
```

produces:

```
"jsonAttr" = '"myString"'
```

### number

```ts
testSql({
  jsonAttr: 12,
});
```

produces:

```
("jsonAttr")::text::decimal = 12
```

⚠️ but even this needs more research: casting text to boolean will fail if the value is not a number. When comparing we don't want it to fail. So maybe when the `=` or `<>` operator is used, we do this instead:

```
("jsonAttr")::text = '12'
```

and if another operator is used:

```ts
testSql({
  jsonAttr: { [Op.gt]: 12 },
});
```

then we do this:

```
("jsonAttr")::text::decimal > 12
```

### boolean

```ts
testSql({
  jsonAttr: true,
});
```

produces:

```
("jsonAttr")::text = 'true'
```

### null

```ts
testSql({
  jsonAttr: null,
});
```

produces:

```
("jsonAttr") IS null
```

---

```ts
testSql({
  'jsonAttr.nested': null,
});
```

produces:

```
("jsonAttr"->>'nested') IS null
```

⚠️ notice how this time I used `->>` instead of `->` so both JSON null and postgres null are normalized to a postgres null, which can then be compared using `IS`

### array and objects

Unsure how to handle these. I'd say JSON.stringify. But that means any spacing difference makes it fail:

```ts
testSql({
  jsonAttr: [1,2,3],
});
```

produces?:

```
("jsonAttr")::text = '[1, 2, 3]'
```

Then there are the JSON operators, such as `@>`:

```ts
testSql({
  jsonAttr: { [Op.contains]: [1,2,3] },
});
```

which must produce:

```
("jsonAttr") @> '[1, 2, 3]'::jsonb
```

## Alternative

ℹ️ this would IMO be the better solution, but we'd need to create that function at some point.

That's one approach, but we can also do it the other way around:

Sequelize could add a postgres function to the database `sequelize_json_to_native` or something. That method would use the built-in method `json_typeof`.

It would convert the json input based on the return value of `json_typeof`:

- number: cast to decimal
- boolean: cast to boolean
- null: return native null
- text: parse as JSON so we get the unquoted text
- array & object: throw an error

Methods would then do this:

```ts
testSql({
  jsonAttr: null,
});
```

produces:

```ts
sequelize_json_to_native("jsonAttr") IS null
```

---

```ts
testSql({
  jsonAttr: { [Op.gt]: 10 },
});
```

produces:

```ts
sequelize_json_to_native("jsonAttr") > 10
```

JSON operators would continue to not do any casting:

```ts
testSql({
  jsonAttr: { [Op.contains]: [1,2,3] },
});
```

produces:

```
("jsonAttr") @> '[1, 2, 3]'::jsonb
```

and users could also do explicit casting to bypass the issue with arrays & objects not being strictly comparable:

```ts
testSql(where(cast(col("jsonAttr"), 'integer') Op.eq, 10))
```

produces:

```ts
("jsonAttr")::integer = 10
-- sequelize_json_to_native is not used because the value is already cast? Could be difficult 
```

---

```ts
testSql(where(cast(col("jsonAttr"), 'text') Op.eq, JSON.stringify([1,2,3]))
```

produces:

```ts
("jsonAttr")::text = '[1, 2, 3]'
-- sequelize_json_to_native is not used because the value is already cast? Could be difficult 
```

I think that's about it, but this is just postgres 😅

**Comment by frostzt** [comment]
damn thanks a lot @ephys I'll give it a shot!
