### ISSUE TITLE
Cannot get DataTypes.VIRTUAL field in .findAll({raw:true})

### ISSUE THREAD

**Issue by lumpov** [sequelize/sequelize#15248]
## Bug Description

Cannot get VIRTUAL field in results with `raw:true`.

The docs for the `raw` option or `VIRTUAL` fields  say nothing about not allowing virtual fields to work with `raw:true`, except that `raw:true` don't build an instance of a model from the result.

If this case is ok, what the best way to get in result virtual fields in like raw?

### Reproducible Example

``` javascript
'use strict';

const { Sequelize, DataTypes } = require('sequelize');

(async () => {
	const sequelize = new Sequelize('admin', 'admin', '***', {
		host: 'localhost',
		dialect: 'mysql',
		define: {
			charset: 'utf8mb4',
			freezeTableName: true,
			createdAt: 'created_at',
			updatedAt: 'updated_at',
			deletedAt: 'deleted_at',
			timestamps: true,
			underscored: true,
			paranoid: true,
		},
		logging: (...msg) => console.log(msg),
	});

	const sites = await sequelize.define('sites', {
		id: {
			type: 'BIGINT UNSIGNED',
			allowNull: false,
			defaultValue: null,
			primaryKey: true,
			autoIncrement: true,
			comment: null,
		},
		label: {
			type: 'VARCHAR(250)',
			allowNull: false,
			defaultValue: '',
			primaryKey: false,
			autoIncrement: false,
			comment: null,
		},
		created_at: {
			type: 'DATETIME',
			allowNull: false,
			defaultValue: null,
			primaryKey: false,
			autoIncrement: false,
			comment: null,
		},
		updated_at: {
			type: 'DATETIME',
			allowNull: false,
			defaultValue: null,
			primaryKey: false,
			autoIncrement: false,
			comment: null,
		},
		deleted_at: {
			type: 'DATETIME',
			allowNull: true,
			defaultValue: null,
			primaryKey: false,
			autoIncrement: false,
			comment: null,
		},
		repr: {
			type: DataTypes.VIRTUAL(DataTypes.STRING, ['label', 'id']),
			get() {
				console.log('get()!');
				return 'get';
			},
		},
	});

	const sitesResponse = await sites.findAll({
		raw: true,
		attributes: ['repr'],
	});

	console.log('sites:', {sitesResponse});
})();
```

### What do you expect to happen?

I expect see console.log message `get()!` and in results of findAll() `repr` field with value of `get`.

### What is actually happening?

console:

```
[
  'Executing (default): SELECT `label`, `id` FROM `sites` AS `sites` WHERE (`sites`.`deleted_at` IS NULL);',
  {
    plain: false,
    raw: true,
    logging: [Function: logging],
    showWarnings: false,
    attributes: [ 'label', 'id' ],
    hooks: true,
    rejectOnEmpty: false,
    originalAttributes: [ 'repr', 'label', 'id' ],
    where: '(`sites`.`deleted_at` IS NULL)',
    tableNames: [ 'sites' ],
    type: 'SELECT',
    model: sites
  }
]
sites: {
  sitesResponse: [
    { label: 'root', id: 1 },
    { label: 'adm', id: 2 }
  ]
}
```

### Environment

- Sequelize version: sequelize@6.25.4, @sequelize/core@7.0.0-alpha.10
- Node.js version: v16.15.1
- If TypeScript related: TypeScript version: N/A
- Database & Version: MySQL v16.15.1
- Connector library & Version: mysql2@2.3.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by fzn0x** [comment]
> ### Environment
> * Sequelize version: sequelize@6.25.4, @sequelize/core@7.0.0-alpha.10


From what I read in your issue environment, is it happen in both version?

**Comment by lumpov** [comment]
both versions.

I'm understand that the `raw:true` don't render any fields by model.

What is the best way to get all fields rendered? Loop full response and `.get()` or `.toJSON()` every record to get rendered all fields?

Or stop using VIRTUAL fields and create virtual fields based on raw-response?

**Comment by ephys** [comment]
Virtual fields are computed when they are accessed on a model instance. We can't compute virtual fields if we don't have an instance, and no instance is created when `raw` is true (by design, to improve performances)

If you want to access virtual fields, you cannot use `raw`. Alternatively you can compute the virtual field yourself

**Comment by FauziFadhi** [comment]
i think you can use JSON.parse(JSON.stringify(model)
