### ISSUE TITLE
findOrCreate fails concurrently when unique attribute contains '/' in value

### ISSUE THREAD

**Issue by shruti-shukla** [sequelize/sequelize#15259]
## Bug Description

Similar to issue described in https://github.com/sequelize/sequelize/issues/7941 and as mentioned [here](https://github.com/sequelize/sequelize/issues/7941#issuecomment-1139640984)
This issue is occurring for MySQL, with / present for in the value for an attribute with unique constraint.
In my case, it seems to be doing something different.

For example if I were to pass following values to findOrCreate:
```

where: {
    uniqueStringParameter: '12345/1234567/text/123',
    uniqueIntegerParameter: 789
  },
  defaults: { jsonData: {} }
```
I would get the error:

`Error: ModelName#findOrCreate: value used for uniqueStringParameter was not equal for both the find and the create calls, '12345/1234567/text/123' vs '789'`

(Note that it is comparing the values passed for uniqueStringParameter and uniqueIntegerParameter)

This is also difficult to reproduce since it only happens when findOrCreate runs concurrently.

### What do you expect to happen?

Concurrent operations to complete successfully without this exception.

### What is actually happening?

Like mentioned above - this error is received in case of concurrent operations

`Error: ModelName#findOrCreate: value used for uniqueStringParameter was not equal for both the find and the create calls, '12345/1234567/text/123' vs '789'`

### Environment

- Sequelize version: "^6.12.5"
- Node.js version: v14.17.6
- If TypeScript related: TypeScript version: 6.14.17
- Database & Version: MySQL
- Connector library & Version:

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
I've added the `dialect: mysql` label to the other issue to indicate that it's not postgres specific. Since they seem to be the same issue I'll close this one so we can keep the discussion in one issue.
