### ISSUE TITLE
Float Values Greater than 9007199254740991 Fails for MSSQL

### ISSUE THREAD

**Issue by npandey5** [sequelize/sequelize#15278]
## Bug Description

Issue occurs when working with FLOAT Types on MSSQL Database. 
If we provide a value > 9007199254740991 or a decimal with Precision of more than 15 decimal places, we get this error:

**Validation failed for parameter '0'. Value must be between -9007199254740991 and 9007199254740991, inclusive.  For smaller or bigger numbers, use VarChar type.**

We have debug the library and the issue seems to be with the getSQLTypeFromJsType function in src/dialects/mssql/query.js
Related PR - https://github.com/sequelize/sequelize/pull/15277

Just this code change does not resolve our issue as the values are still not updated correctly in the DB (Last extra digits are replaced with Zeros). E.g -> 900719925474098**1123** is saved as 900719925474098**1000**

### What do you expect to happen?

The library should successfully be able to save the large float value or handle large decimal places into MSSQL

### What is actually happening?

Error Stacktrace:
2022-11-13T11:39:15.196Z | error | controller | patchValue | null | patch value error | GeneralError: Validation failed for parameter '0'. Value must be between -9007199254740991 and 9007199254740991, inclusive.  For smaller or bigger numbers, use VarChar type.
    at new BaseError (C:\Source\<reponame>\exceptions\exceptions.js:20:15)
    at new GeneralError (C:\Source\<reponame>\exceptions\exceptions.js:65:9)
    at updateKPIPlanValueDAO (C:\Source\<reponame>\database\dao\kpiPlanValueDAO.js:226:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Validation failed for parameter '0'. Value must be between -9007199254740991 and 9007199254740991, inclusive.  For smaller or bigger numbers, use VarChar type.

### Environment

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
The error mentions that the `VarChar` type is recommended for this. This is because the number is outside the safe range for BigInt. Is there a reason that `VarChar` is not wanted in this scenario?

**Comment by npandey5** [comment]
> The error mentions that the `VarChar` type is recommended for this. This is because the number is outside the safe range for BigInt. Is there a reason that `VarChar` is not wanted in this scenario?

The underlying SQL database has the field as FLOAT which if directly updated accepts these numbers. Reads requests with the high values works fine as well using Sequelize but Insert and Update do not.

**Comment by ephys** [comment]
Are you passing the value you're trying to store as a JavaScript number? Because 9007199254740991 is MAX_SAFE_INTEGER: JavaScript's number type is unable to safely represent values bigger than that, smaller than -9007199254740991, or with more than 15 (16?) digits. You will lose precision if you try to use it with such values. You need to use a string instead

On top of the above, mssql's double type has the same size restrictions as the JavaScript number type. If you want a bigger value there you will need to use the Decimal or BigInt data types

**Comment by npandey5** [comment]
Thanks for inputs @ephys. I think it is a Javascript number issue in addition. Coz the digits are set to 0 for large values at the application entrypoint from the Swagger itself.
For Sequelize, the error is very real as it is failing when we put the large numbers(Last stable NPM version)
I forked from Main Branch code, It has two type of blocks (number and bigint). Where as the latest stable version has just number(6.25.5) which I had debug and modified, I will try to run with the latest code and maybe we can release a new version soon if that works.

![image](https://user-images.githubusercontent.com/118109399/201535957-bce5fa84-cbe0-401a-a60a-d2015db928fd.png)

**Comment by npandey5** [comment]
Doesn't work guys, It never reaches the condition (typeof value === 'bigint'). Any value it is always a number.
If done forcefully, The current code of assigning as varchar is failing the Run Query function with error - 
GeneralError: Validation failed for parameter '0'. Invalid string 

This code change helps us process the data but yes loosing some precision of the value.
![image](https://user-images.githubusercontent.com/118109399/201538852-7aa0b874-74a5-4c34-af6a-49a8621632f8.png)

**Comment by ephys** [comment]
If you're using the JavaScript [number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) type, the bigint block won't run since you're not using a [bigint](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). The type doesn't depend on the size of the value, `2n` is a bigint, `2` is a number, `'2'` is a string. No matter what you change in Sequelize, you won't be able to pass values bigger than 9007199254740991 using the number type - you must use string or bigint

**Comment by npandey5** [comment]
Hi @ephys and @WikiRik - We made an agreement with business to capture the large data points in a higher unit (millions) which solves the problem for now.
We can probably close the issue but raising one concern on the earlier analysis. Node JS I agree does not support numbers > MaxSafeInt. It is clearing some last digits but not failing the program. Whereas Sequelize for MSSQL is failing the operation in the code. i.e Node is passing 900719925474098**1000** and SQL Float supports that. It shouldn't be the Sequelize library that makes a decision on the number value that can or cannot be inserted into the SQL Server DB. And in addition the READ operations on these large numbers work seamlessly, both in Sequelize and in the Node App. Bummer!!!!

**Comment by ephys** [comment]
You can insert any value you want, you just have to pass them as strings:

```ts
class ModelA extends Model {}
ModelA.init({
  double: DataTypes.DOUBLE,
}, { sequelize });

await ModelA.create({
  // KO! 9007199254741000 is above max int. 
  // Tedious's safeguards prevent this.
  // Sequelize 7 also prevents this, 
  // but your current issue isn't actually caused by us in v6.
  double: 9007199254741001
});

await ModelA.create({
  // OK! This is safely represented in JS so we'll send it as-is.
  // it's still going to lose precision once it arrives in your database 
  //  if your column is a double - so you'll have 9007199254741000 in your row instead.
  double: '9007199254741001'
});

await ModelA.create({
  // OK in v7 (not v6) - same as string version (we literally just convert it to string)
  double: 9007199254741001n
});
```

The vast majority of users don't want to lose precision. IMO playing with out-of-range floating point numbers is playing with fire, so we won't remove our safeguards, but you're still free to bypass them by using strings or bigints
