### ISSUE TITLE
Nested query wont work

### ISSUE THREAD

**Issue by allestaire** [sequelize/sequelize#15287]
Seems like the documentation and result wont match hope you check this.
https://sequelize.org/docs/v6/advanced-association-concepts/eager-loading/

This is the example where clause for nested query but it does not work.
```json
[Op.or]: [
          {
            customerEmail: {
              [Op.like]: `%${search}%`
            }
          },
          {
            '$orderItems.name$': {
              [Op.like]: `%${search}%`
            }
          },
          {
            '$orderItems.description$': {
              [Op.like]: `%${search}%`
            }
          }
        ]
```

When queries this is the result:

**Unknown column 'orderItems.name'**

**Comment by ephys** [comment]
Please provide your complete query & your models (as the issue requested). You can try to replicate your issue using this repository https://github.com/sequelize/sequelize-sscce. Unfortunately we can't help you with just a subset

**Comment by allestaire** [comment]
Sorry for the rant, and thanks for the kind response 😄 
This was already been resolve,
The result I want is only check if there are sub query exists and parent should be return including its sub model (not filtered on checked that specific item exists).
