### ISSUE TITLE
Add posibility to write Case insensitive SQL SELECT query 

### ISSUE THREAD

**Issue by Gedzis** [sequelize/sequelize#1529]
Hi,

today i have faced problem that in where queries we can not write Case insensitive queries. 

We need to add iLike for postgress, or just add possibility to write 

select \* from users where lower(first_name) =lower( 'fred');

**Comment by bradisbell** [comment]
The `ilike` criteria should be documented.

**Comment by mickhansen** [comment]
@bradisbell you are very right :) we are working on making the docs way more comprehensive. PR and suggestions welcome

**Comment by basco-johnkevin** [comment]
I'm currently using ILIKE as a workaround, but I read that using ILIKE for case-insensitive search might cause issues when the strings has an underscore - http://stackoverflow.com/questions/16311289/postgresql-case-insensitive-select-on-array . Not sure if it only applies on Postgresql's array data type. Thoughts?

**Comment by janmeier** [comment]
@basco-johnkevin This seems more like a postgres concern than a sequelize concern. Also, do you have some more information about why ilike gives problems with arrays, other than a comment on SO :)?

**Comment by corbanb** [comment]
@janmeier I am trying out your psql solution here for lower seen here:

```
Model.findAll({ where: { 
    name: Sequelize.fn('lower', Sequelize.col('name') 
});
```

What do I need to do for a findOne and have a param passed for the username? Such as...

```
Model.findOne({ where: { 
    username: {
        arg: "Admin"
        fn:  Sequelize.fn('lower', Sequelize.col('name') 
    }
});
```

Is this possible?

**Comment by janmeier** [comment]
```js
return User.findOne({
  where: Sequelize.where(Sequelize.fn('lower', Sequelize.col('username')), sequelize.fn('lower', username))
});
```

Ideally, I'd like a bit lighter syntax, something like 
```js
return User.findOne({
  where: {
     $key: sequelize.fn('lower', Sequelize.col('username'))
     $val: sequelize.fn('lower', username))
  }
});
```
But the first example i posted should work :). You can combine it with other queries using `$or` and `$and`

**Comment by corbanb** [comment]
@janmeier thanks sir! I agree there should be a better way but its not bad for now.

**Comment by corbanb** [comment]
@janmeier can you explain `You can combine it with other queries using $or and $and` further? 

I haven't been able to get this working.

**Comment by janmeier** [comment]
@corbanb, give me an example of what you want to write, and I'll try to formulate it in sequelize

**Comment by corbanb** [comment]
Thanks @janmeier, I am just trying to add other attributes to the query. Should be pretty straight forward. I just want to be able to query on more attributes with AND clause. 


```
User.findOne({
  where: Sequelize.where(Sequelize.fn('lower', Sequelize.col('username')), sequelize.fn('lower', username),
$and: attr: 'foo'
)
});
```

**Comment by janmeier** [comment]
```js
User.findOne({
  where: {
    $and: [
      { attr: 'foo' },
      Sequelize.where(Sequelize.fn('lower', Sequelize.col('username')), sequelize.fn('lower', username))
    ]
  }
});
```

Not the pretties syntax in the world, but it should work ;)

Sequelize.where is quite a speciale case, since its both key and value in one - stemming from the fact that an object cannot be used as a key in js object.

What I'd like more is something like this 

```js
User.findOne({
  where: {
    $and: [
      { attr: 'foo' },
      {
        $key: Sequelize.fn('lower', Sequelize.col('username')), 
        $value: sequelize.fn('lower', username) 
      }
    ]
  }
});
```
At least, less use of functions is more pleasing to my eye. Hopefully I'll get around to implemnenting it at some point

**Comment by corbanb** [comment]
@janmeier this is perfect for now though. I'd toss this in the docs for sure. Good stuff!

**Comment by janmeier** [comment]
@corbanb pull request for the docs are always welcome :) The querying section could use some looove http://docs.sequelizejs.com/en/latest/docs/querying/#combinations

**Comment by davidsansay** [comment]
I would not recommend to use ilike because pg cannot use the BTree index if you search with ilike.

> It is also possible to use B-tree indexes for ILIKE and ~*, but only if the pattern starts with non-alphabetic characters, i.e., characters that are not affected by upper/lower case conversion.
source: http://www.postgresql.org/docs/9.4/static/indexes-types.html

**Comment by vipingupta559** [comment]
User.findOne({
  where: {
    $or: [    
                                                sequelize.where(sequelize.fn('lower',  sequelize.col('excel_uploads.file_name')),
                                                                {$like : sequelize.fn('lower', 'searchString')}),
                                                sequelize.where(sequelize.fn('lower', sequelize.col('employer.profile')),
                                                                {$like : sequelize.fn('lower',  'searchString')}),
                                                sequelize.where(sequelize.fn('lower', sequelize.col('user.first_name')),
                                                                {$like : sequelize.fn('lower', 'searchString')}),
                                                sequelize.where(sequelize.fn('lower', sequelize.col('user.last_name')),
                                                                {$like : sequelize.fn('lower', 'searchString')}),
                                                sequelize.where(sequelize.fn('lower', sequelize.col('excel_uploads_bad_record.file_name')),
                                                                {$like : sequelize.fn('lower', 'searchString')})
                                            ]

  }
});

**Comment by alenteria** [comment]
here's what worked for me
`
.findOne({
    where: {
      $and: Sequelize.where(Sequelize.fn('lower', Sequelize.col('short_name')), Sequelize.fn('lower', short_name))
    }
  })`
