### ISSUE TITLE
Duplicate Foreign Keys on Latest Version

### ISSUE THREAD

**Issue by 1Map** [sequelize/sequelize#15308]
I am using the latest version (6.25.7) and connect to PostgreSQL.

Every time I run a sync all the Constraints (All - Foreign Keys, Unique's, etc. except the Primary Key) are getting duplicated.  I know this might be a duplicate issue.  But I read through all the other issues and thought this was fixed, but definitely not.

I can just note that I am not using the default PostgreSQL schema (public), but in my case a custom schema (auth).

```
  schema: 'auth',
  host: process.env.DEV_DB_HOST || 'localhost',
  port: 5432,
  dialect: 'postgres',
```

<img width="672" alt="image" src="https://user-images.githubusercontent.com/1152458/202868028-15f3ab7e-b007-4bb4-a043-46375c48ef43.png">

**Comment by ephys** [comment]
This looks like the same issue as https://github.com/sequelize/sequelize/pull/14619. It was fixed in v7, no fix in v6 as of yet

**Comment by 1Map** [comment]
Nope, just upgraded and still creating duplicates.

**Comment by ephys** [comment]
Can you try to replicate your issue using this repo? https://github.com/sequelize/sequelize-sscce

**Comment by 1Map** [comment]
No, problem.  I got it working.  My problem was that by installing v7 via:
`**npm install @sequelize/core**`

installed version `**^7.0.0-alpha.10**` which still had the problem.  After I forced a install on `**^7.0.0-alpha.19**` all works 100%

**Comment by WikiRik** [comment]
Yeah, it was fixed in alpha14. Thanks for confirming!

**Comment by 1Map** [comment]
I want to reopen this as I get an error when changing my ENUM type and doing a sync.  Seems that ENUM types are not synced in Postgresql, but rather a CREATE.  An ENUM Type should be also be correctly synced, like foreign keys, indexes, etc, etc.  This causes an error saying the the ENUM type already exists, for example in the sync the following is causing the error:

**`CREATE TYPE "auth"."enum_users_state_code" AS ENUM('STATE1', 'STATE2', 'STATE3');`**

PostgreSQL error: **`type "enum_users_state_code" already exists`**

This is a tricky one, as one cannot just drop the ENUM type and then re-create it, as other tables might also be using the same ENUM type.  Any idea on how to get past this bug?

**Comment by 1Map** [comment]
I can just add to the issue on top.  What I see is that ENUM types are created unique for each table.  The way I see it.  In that case, in the same transaction,

1) The column should get a STRING type
2) the existing ENUM should be dropped
3) the new ENUM should be created <-- This is where the error happens
4) lastly, the new ENUM type should be hooked to column

This is all in theory, not sure how you guys handle this.

**Comment by 1Map** [comment]
Currently you are doing in one transaction as follow (Which breaks on the 3rd query):

```
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" SET NOT NULL;
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" SET DEFAULT 'STATE1';
CREATE TYPE "auth"."enum_bf_users_state_code" AS ENUM('STATE1', 'STATE2', 'STATE3');
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" TYPE "auth"."enum_bf_users_state_code" USING ("state_code"::"auth"."enum_bf_users_state_code");
```

What I found is that all will work 100% if you do it as (Compare to the existing one above):

```
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" SET NOT NULL;
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" TYPE character varying;
DROP TYPE "auth"."enum_bf_users_state_code" CASCADE;
CREATE TYPE "auth"."enum_bf_users_state_code" AS ENUM('STATE1', 'STATE2', 'STATE3');
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" DROP DEFAULT;
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" TYPE "auth"."enum_bf_users_state_code" USING ("state_code"::"auth"."enum_bf_users_state_code");
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" SET DEFAULT 'STATE1';
```

**Comment by 1Map** [comment]
So, to recap.  To re-create the enum type in one transaction without breaking anything can be done in this single transaction (Of course, here the order is important):

```
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" DROP DEFAULT;
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" TYPE character varying;
DROP TYPE "auth"."enum_bf_users_state_code" CASCADE;
CREATE TYPE "auth"."enum_bf_users_state_code" AS ENUM('STATE1', 'STATE2', 'STATE3');
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" TYPE "auth"."enum_bf_users_state_code" USING ("state_code"::"auth"."enum_bf_users_state_code");
ALTER TABLE "auth"."bf_users" ALTER COLUMN "state_code" SET DEFAULT 'STATE1';
```

**Comment by ephys** [comment]
We already have an issue about sync trying to recreate existing enums https://github.com/sequelize/sequelize/issues/7649

**Comment by ephys** [comment]
I'll close this issue in favor of https://github.com/sequelize/sequelize/issues/7649
