### ISSUE TITLE
Unknown column 'orderFiles.tempOrderId' in 'on clause

### ISSUE THREAD

**Issue by nekl3103** [sequelize/sequelize#15331]
У меня есть таблица заказов. К таблице заказов я создал еще 1 таблицу где сохраняю файлы для заказов.
У меня часто выходит вот такая ошибка 

[https://disk.yandex.ru/d/si40mc6sDC5B0A](https://disk.yandex.ru/d/si40mc6sDC5B0A)
[https://disk.yandex.ru/d/RNVCrydc_f-Q7g](https://disk.yandex.ru/d/RNVCrydc_f-Q7g)

Это я уже использовал. Плагин может создать а потом опять через какое то время снова удалить.
await sequelize.sync({ force: false, alter: true });

- Sequelize version: 6.25.6
- Node.js version: 14.20.0
- Database & Version: 10.3.31-MariaDB-0+deb10u1

**Comment by WikiRik** [comment]
Please use one of the [issue templates](https://github.com/sequelize/sequelize/issues/new/choose) in English so we have the required information to help you with. You can make a new issue, or you can update this one. I can reopen once that has been done.
