### ISSUE TITLE
Transaction commit success gets called but data not committed

### ISSUE THREAD

**Issue by fsosa** [sequelize/sequelize#1533]
I have a set of queries that I run within a transaction. The success callback of t.commit gets called but my data does not get saved to the database. Occasionally it does commit the queries, but very rarely. I'm on MySQL. 

Additionally, are there issues with running a chainer inside of a transaction?

**Comment by yuriscom** [comment]
Hello from 2017. Having the same issue here. It's very inconsistent. Most of the time it works, but from time to time it does NOT commit. Using the sequelize version 3.30.2

**Comment by GauravMisraSE** [comment]
Having the same issue, there are no errors, but the data is not committed to the database.

**Comment by GauravMisraSE** [comment]
Solved it, please do use only sessions, I was using a non orm transaction before adding object to my session, when I removed it, the code worked fine

**Comment by poorprogrammer** [comment]
@GauravMisraSE Could you please explain more about your issue and solution. I am facing this issue too. Thank you in advance.

**Comment by yuriscom** [comment]
I solved it by using autocommit:true. the issue reproduces only with autocommit:false & manual committing.

**Comment by emanuelecasadio** [comment]
Same issue here, using `sequelize-typescript` for most of the codebase and a little bit of `sequelize` for extra things (like, manual transactions).

**Comment by dougmaitelli** [comment]
Is this still happening? I suspect I am facing the same issue. Am using sequelize-typescript, and without the transaction the changes do go to the database without any problems, using transactions the commit is executed fine according to the logs but no data is actually saved.

**Comment by papb** [comment]
@dougmaitelli If you are still having problems, please open a new issue. Also, try to reproduce the problem without `sequelize-typescript`, otherwise you should open your issue there instead.

**Comment by Jeff-Tian** [comment]
Same issue on plain sequelize@5.18.4.

**Comment by papb** [comment]
@Jeff-Tian Can you please open a new issue, filling the template, reporting this bug?

**Comment by vajnorcan** [comment]
Apparently this is still a problem unfortunately.  Any workarounds in the meantime ? I need to be able to edit multiple tables in one transaction and without this working my whole back end is pretty much unusable..

sequelize@5.21.5
SQLServer 2017

**Comment by vajnorcan** [comment]
> Same issue on plain sequelize@5.18.4. (I am not using `sequelize-typescript`)
> 
> MySQL, reproduces every time.

Hi, have you managed to workaround this issue ?

**Comment by Jeff-Tian** [comment]
> @Jeff-Tian Can you please open a new issue, filling the template, reporting this bug?

Sorry, finally I found it's not the sequelize bug:

I met the issue during my automation testing code, and in the end I figured it out that my testing tear down code will truncate all the data committed during testing, which made me think that the committing was not successful.
