### ISSUE TITLE
Rethink hook ordering

### ISSUE THREAD

**Issue by theoephraim** [sequelize/sequelize#1536]
Im trying to use beforeCreate and beforeUpdate to implement some default value functionality on a model (automatically filling one column based on the value of another before saving).

The column I am filling is `notNull: true` and because of this, the model fails the validation step due to the column being empty so my hooks (which would fill these columns) are never called.

So either changing the order of the hooks, or some way of specifying when or if to run the validation would be helpful.

**Comment by sushantdhiman** [comment]
Agreed to change order so `beforeValidate` called after `before Create/Update/Save`? @mickhansen @janmeier

**Comment by durango** [comment]
@mickhansen just trying to get a better understanding of this:

`...they [beforeAction] would be the ideal place to do conditional default values`

Why would `beforeAction` be a better place than `beforeValidate` on conditional default values?

Couldn't we just use `instance.isNewRecord` and a mixture of "type safe" throughout the hook itself? Is that not the proper way of handling this specific scenario?

**Comment by durango** [comment]
The above mentioned "proper way" is a bit limiting as a solution. There might be a way to add this functionality without breaking changes. Proposal:

```js
// current behavior
beforeValidate(<instance, options, fn>Func);
// proposed solution
// beforeValidate(<action>String, <instance, options, fn>Func);
beforeValidate('create', (instance, options, fn) => { ... });
```

**Comment by mickhansen** [comment]
woah, @durango, haven't seen you in ages :)

Well, defining a method beforeValidate operates on wouldn't really effect hook ordering would it?

**Comment by durango** [comment]
Unless we do type checking within the initialization process, internally we would have to manage an actual `beforeValidateOnCreate` hook "state" which will run prior to beforeValidate [or just split the functionalities into two and allow either `beforeValidate` or `beforeOnActions`]) but the surface of sequelize shouldn't be an issue.. although @mickhansen as you said it's been ages :) 

Either way, just a thought, there's still the `instance.isNewRecord` trick of course, the BC path, etc.

The original logic came from http://guides.rubyonrails.org/active_record_callbacks.html (`around_save` and some of these other ones were not there at the time) but that doesn't mean it has to be set in stone of course.

**Comment by sushantdhiman** [comment]
@durango never thought I will be getting replies from you :)

What you just suggested is more like scenarios as discussed in https://github.com/sequelize/sequelize/issues/1768 ? If we implement them we could control various hooks based on scenarios and it can solve @theoephraim problem too.

What do you think about it @mickhansen @janmeier

**Comment by durango** [comment]
@sushantdhiman ty for the hard work in maintaining Sequelize :wave: it's been moving so fast a bit hard to keep up hah.

As for #1768 I wasn't aware of this ticket, but it seems like a reasonable/good solution for this issue :+1:
