### ISSUE TITLE
Allow custom dialect

### ISSUE THREAD

**Issue by geofmigliacci** [sequelize/sequelize#15402]
## Feature Description
Currently inside Sequelize there is a default case for unknown dialects (https://github.com/sequelize/sequelize/blob/main/src/sequelize.js#L326) that throws an error. 

The feature would be to implement a "custom" case where the user could develop a custom dialect implementing the availables interfaces inside the dialect folder & using it.

### Describe the feature you'd like to see implemented
Adding a case "custom" to avoid removing throwing error. 
Keeping the error to avoid users not understanding why sequelize doesn't works (typo inside the dialect name).

```js
case 'custom': // Or another custom case
  // Or another option name?
  Dialect = require(this.options.customDialectPath)[this.options.customDialectName];
  break;

```

### Describe why you would like this feature to be added to Sequelize

I would like to use sequelize on a project but I have a very old database that is not supported by sequelize.

Moreover, this could open sequelize to more dialects or "old" SQL databases as well as not having it in the main sequelize project, thus mitigating the creation of issues related to custom dialects.

### Is this feature dialect-specific?

- [X] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
This is already planned :)

See https://github.com/sequelize/sequelize/issues/13003, as well as https://github.com/sequelize/sequelize/issues/13894

We wanted to do this for Sequelize 7, but had to rescope and it is now part of Sequelize 8
