### ISSUE TITLE
when in Sequelize I am trying to select columns for both inner joined table some of the joined table columns are nested in alias

### ISSUE THREAD

**Issue by HMhamedminaee** [sequelize/sequelize#15489]
I am still new to Sequelize and I am trying to select specific columns from both table in inner join using sequelize. Here is what I have

            const paramPostgres: QueryBuilder = {
            raw: false,
            nest: true,
            include: [{
                model: UserAccountDeRepository.getInstance().model, as: "userAccountTableAlias",
                attributes: ["account"],
                required: true
            }],
            attributes: ["is_archived", "status", "udiId"],
            where: {
            '$userAccountTableAlias.user$': usernames
            }
        }

as you can see attributes: ["is_archived", "status", "udiId"] gives me the columns I want from main table while attributes: ["account"] gives me the column name I want from joined table. My problem is the following response format:

    [{"is_archived":false,"status":"COMPLETED","udiId":"9e8350f1-fab0-4861-96ae-1268118c49a3","userAccountTableAlias":{"account":"133b5f93-916b-46c1-b429-6c071c752097"}}]

as you can see all columns are back but account from joined model is buried in userAccountTableAlias

what I want to get is the following

   

        [{"is_archived":false,"status":"COMPLETED","udiId":"9e8350f1-fab0-4861-96ae-1268118c49a3","account":"133b5f93-916b-46c1-b429-6c071c752097"}]
 

but not sure how to achieve that. I appreciate any help

**Comment by harikrishna2208** [comment]
If you need everything in a single object of key and value, try passing all the required fields in the parent attribute itself.Make the included (children) attribute empty, which removes nested data.

```typescript
const paramPostgres:QueryBuilder = {
  raw: false,
  nest: true,
  attributes: [
    'is_archived',
    'status',
    'udiId',
    [sequelize.col('userAccountTableAlias.account'), 'account'], // -> pass here [child attributes using alias.]
  ],
  include: [
    {
      model: UserAccountDeRepository.getInstance().model,
      as: 'userAccountTableAlias',
      attributes: [], // => to avoid nested object from include
      required: true,
    },
  ],
  where: {
    '$userAccountTableAlias.user$': usernames,
  },
};

**Comment by HMhamedminaee** [comment]
@harikrishna2208 thanks but when I try 

`const paramPostgres:QueryBuilder = {
  raw: false,
  nest: true,
  attributes: [
    'is_archived',
    'status',
    'udiId',
    ['userAccountTableAlias.account', 'account'], 
  ],
  include: [
    {
      model: UserAccountDeRepository.getInstance().model,
      as: 'userAccountTableAlias',
      attributes: [], // => to avoid nested object from include
      required: true,
    },
  ],
  where: {
    '$userAccountTableAlias.user$': usernames,
  },
};`

I get the following error
`Executing (default): SELECT "hamed-test"."search_id" AS "searchId", "hamed-test"."is_archived", "hamed-test"."status", "hamed-test"."udi_id" AS "udiId", "hamed-test"."creation_time", "userAccountTableAlias.account" AS "account" FROM "hamed-test" AS "hamed-test" INNER JOIN "user-account-de" AS "userAccountTableAlias" ON "hamed-test"."user_account_de_hamed" = "userAccountTableAlias"."id" WHERE "userAccountTableAlias"."user" IN ('test');
{"name":"SequelizeDatabaseError","parent":{"length":130,"name":"error","severity":"ERROR","code":"42703","position":"163","file":"parse_relation.c","line":"3403","routine":"errorMissingColumn","sql":"SELECT \"hamed-test\".\"search_id\" AS \"searchId\", \"hamed-test\".\"is_archived\", \"hamed-test\".\"status\", \"hamed-test\".\"udi_id\" AS \"udiId\", \"hamed-test\".\"creation_time\", \"userAccountTableAlias.account\" AS \"account\" FROM \"hamed-test\" AS \"hamed-test\" INNER JOIN \"user-account-de\" AS \"userAccountTableAlias\" ON \"hamed-test\".\"user_account_de_hamed\" = \"userAccountTableAlias\".\"id\" WHERE \"userAccountTableAlias\".\"user\" IN ('test');"},"original":{"length":130,"name":"error","severity":"ERROR","code":"42703","position":"163","file":"parse_relation.c","line":"3403","routine":"errorMissingColumn","sql":"SELECT \"hamed-test\".\"search_id\" AS \"searchId\", \"hamed-test\".\"is_archived\", \"hamed-test\".\"status\", \"hamed-test\".\"udi_id\" AS \"udiId\", \"hamed-test\".\"creation_time\", \"userAccountTableAlias.account\" AS \"account\" FROM \"hamed-test\" AS \"hamed-test\" INNER JOIN \"user-account-de\" AS \"userAccountTableAlias\" ON \"hamed-test\".\"user_account_de_hamed\" = \"userAccountTableAlias\".\"id\" WHERE \"userAccountTableAlias\".\"user\" IN ('isc-demo', 'isc-test');"},"sql":"SELECT \"hamed-test\".\"search_id\" AS \"searchId\", \"hamed-test\".\"is_archived\", \"hamed-test\".\"status\", \"hamed-test\".\"udi_id\" AS \"udiId\", \"hamed-test\".\"creation_time\", \"userAccountTableAlias.account\" AS \"account\" FROM \"hamed-test\" AS \"hamed-test\" INNER JOIN \"user-account-de\" AS \"userAccountTableAlias\" ON \"hamed-test\".\"user_account_de_hamed\" = \"userAccountTableAlias\".\"id\" WHERE \"userAccountTableAlias\".\"user\" IN ('test');","parameters":{}}`

**Comment by HMhamedminaee** [comment]
Thanks that works
