### ISSUE TITLE
allowNull for hasMany associations?

### ISSUE THREAD

**Issue by jrvidotti** [sequelize/sequelize#1554]
When defining associations, I'm trying to make a foreign key NOT NULL. `allowNull` isn't working for it: my `countryId` continues as NULL.

```
Country.hasMany(models.States, {
  as: 'States', 
  foreignKey: 'countryId', 
  onDelete: 'restrict', 
  foreignKeyConstraint: true,
  allowNull: false
});
```

**Comment by kartik115** [comment]
@janmeier is it possible now to add not null field as Foreign key.
