### ISSUE TITLE
isEmail validator Failed

### ISSUE THREAD

**Issue by DivyachandrapandiHomeIntel** [sequelize/sequelize#15592]
I cannot validate email using email validator in sequelize

Code:
 `email: {
      type: DataTypes.STRING,
      allowNull:false,
validate: {
isEmail:true,  //not working
},
      unique: {
        args: true,
        msg: "Email address already in use!",
      },
    },`

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
Please follow the issue template, this is not enough for us to replicate the problem
