### ISSUE TITLE
It seems like that the {alter: true} doesn't work when I'm trying reboot my script

### ISSUE THREAD

**Issue by talonshi** [sequelize/sequelize#15630]
### What do you expect to happen?

use sync({alter: true}) in order to update the columns of mysql table

### What is actually happening?
I added a column named 'authorization', wanna update the columns of my table but it won't.

<img width="341" alt="code" src="https://user-images.githubusercontent.com/101341990/215694420-fd031d57-fcea-4d6e-aee1-811ba4fcca46.png">

<img width="273" alt="企业微信截图_16751507395559" src="https://user-images.githubusercontent.com/101341990/215696475-f4e169a5-e743-422a-adfb-61380ee78db8.png">

when I reboot the script, the terminal print CREATE sql rather than UPDATE sql
<img width="556" alt="企业微信截图_16751502712265" src="https://user-images.githubusercontent.com/101341990/215694859-ba862f18-57c3-4883-a4b3-1854d9b11e4a.png">

It seems like that the {alter: true} doesn't work
### Environment

- Sequelize version: 6.28.0
- Node.js version: 14.17.3
- Database & Version: mysql2: "^2.3.3",
- Connector library & Version: mysql2: "^2.3.3",

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
I looked into this and I can't reproduce your problem. Unfortunately without an SSCCE I'm not going to be able to help you with this.

You can create one at https://github.com/sequelize/sequelize-sscce

That being said I typically would not recommend using the `alter` option
