### ISSUE TITLE
Unknown column order clause with multi models in include

### ISSUE THREAD

**Issue by OsamaaNK** [sequelize/sequelize#15635]
## Bug Description

whenever i try to create a order on children with include and the include has multiple objects, it does not work, it only works if i have one object inside the include statement 

### Reproducible Example

const data = MainModel.findAll({
order: [[ModelOne, 'order', 'DESC']],
include: [
{model: ModelOne},
{model: ModelTwo},
{model: ModelThree},
]
})

notes:
- the relation between MainModel and ModelOne is One-To-One
- the relation between MainModel and ModelTwo is One-To-Many
- the relation between MainModel and ModelThree is One-To-Many

### What do you expect to happen?
sort item of MainModel depend on ModelOne.order

### What is actually happening?

  original: Error: Unknown column 'ModelOne.order' in 'order clause'

### Environment
Local - Mac

- Sequelize version: ^6.16.1
- Node.js version: v14.17.0
- Database & Version: mysql  Ver 8.0.30 for macos12.4 on arm64 (Homebrew)

## Would you be willing to resolve this issue by submitting a Pull Request?

- [] Yes, I have the time and I know how to start.
- [] Yes, I have the time but I will need guidance.
- [] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
We won't be able to help you with this without a reproducible example. You can create one with https://github.com/sequelize/sequelize-sscce
