### ISSUE TITLE
_loadDialectModule hides original MODULE_NOT_FOUND exception which makes debugging very difficult

### ISSUE THREAD

**Issue by fedulovivan** [sequelize/sequelize#15657]
There are a lot of issues here, with text like **Please install sqlite3 package manually** or **Unable to find dialect at sqlite3** (**sqlite3** may be replaced with **pg** or any other, this does not matter, actually).

So this was also my case, I have faced with weird error, saying "sqlite3" package is missing. I have ensured it is in package.json, then checked node_modules/sqlite3 - all ok, but issue still present.
Almost all items in this repo contain advises with some magical steps like using `npm rebuild`, or steps leading to package reinstall. This obviously looks weird..

So, after several hours of debugging I have found a real RCA for the problem in my particular case. Instruction require("sqlite3") throwed an exception `Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-arm64/node_sqlite3.node'` (that was caused by wrong Dockerfile on my side, and using different distributive to compile and run application). But the problem is, [_loadDialectModule](https://github.com/sequelize/sequelize/blob/main/packages/core/src/dialects/abstract/connection-manager.ts#L118) hides an original exception thrown by node.js runtime.

So, please consider using following exception text: "**Unable to load sqlite3 package due to error: Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v6-linux-musl-arm64/node_sqlite3.node'**", and do not hide original exception, which may not be caused by simple absence of node_modules/sqlite3.

**Comment by geeksesi** [comment]
please, could you explain about "that was caused by wrong Dockerfile on my side, and using different distributive to compile and run application".

**Comment by fedulovivan** [comment]
@geeksesi please check [this](https://github.com/TryGhost/node-sqlite3/issues/1677#issuecomment-1422315954) comment

**Comment by ephys** [comment]
`_loadDialectModule` is no longer used following the extraction of dialects to their own packages https://github.com/sequelize/sequelize/issues/13722
