### ISSUE TITLE
Sequelize does't update updated_at attribute

### ISSUE THREAD

**Issue by gorcer** [sequelize/sequelize#15697]
v6.21.4

When i try to update only updatedAt field it doesn't update it.

It does't works:
```
models.User.update(
{ updatedAt: '2022-01-01' }, 
{ where: {id:1} }
)
```

It works:
```
models.User.update(
{ updatedAt: '2022-01-01', name: 'Egor' }, 
{ where: {id:1} }
)
```

I thing the problem in model setter, look at this:

```
console.log(user.updatedAt);
// 2023-02-20 21:00:00

user.updatedAt = '2022-01-01';
console.log(user.updatedAt);
// 2023-02-20 21:00:00
```

I'm try all of this and it's all doesn't works:
```
// value in dataValues still have the old value
user.set('updatedAt', new Date()); 
user.updatedAt = '2022-01-01';
user.changed('updatedAt', true) 
user.updatedAt = '2022-01-01';

// doesn't update
user.update({ updatedAt }, { where: { id: instance.id }, silent: true }); 


```

My model:
```

module.exports = (sequelize, DataTypes) => {
    const User = sequelize.define('User', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        name: DataTypes.STRING,
        email: DataTypes.STRING,
        password: DataTypes.STRING,
        remember_token: DataTypes.STRING,
    }, {
        tableName: 'users',
        timestamps: true,
        underscored: true,       
    });

    return User;
};
```

I try to add updatedAt definition in model, but it doesn't help for me.

Why updatedAt doesn't update?

**Comment by ephys** [comment]
Hi! We get a lot of issues which takes a very long time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

You can edit this issue and ping us, and we will re-review.
As indicated in the issue template, issues that do not follow the template may be closed.

---

If this is not about a bug report or a feature request, prefer instead:

- StackOverflow: https://stackoverflow.com/questions/tagged/sequelize.js
- GitHub discussions: https://github.com/sequelize/sequelize/discussions (let us know and we'll convert this issue into a discussion)
