### ISSUE TITLE
Error: SequelizeDatabaseError: column "receiving_product.id" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by sumonskys** [sequelize/sequelize#15690]
const singleRP = await db.receiving_product.findOne({
        include: [
          {
            model: db.purchase_order,
            as: "purchase_order",
            include: [
              { model: db.vendor, as: "vendor" },
              {
                model: db.po_productlist,
                as: "product_items",
                attributes: [
                  "id",
                  "purchase_order_id",
                  "product_id",
                  "quantity",
                  "price",
                  "totalPrice",
                  "created_by",
                  "updated_by",
                  "tenant_id",
                  "createdAt",
                  "updatedAt",
                  [
                    db.sequelize.fn(
                      "SUM",
                      db.sequelize.col("purchase_order.product_items.receivinghistory.received_quantity")
                    ),
                    "received_quantity",
                  ],
                ],

                include: [
                  { model: db.product, as: "product" },
                  {
                    model: db.received_product,
                    as: "receivinghistory",
                    attributes: [
                      [
                        db.sequelize.fn(
                          "SUM",
                          db.sequelize.col("purchase_order.product_items.receivinghistory.received_quantity")
                        ),
                        "received_quantity",
                      ],
                    ],
                    include: {
                      model: db.user,
                      as: "received_by",
                    },
                  },
                  {
                    model: db.product_serial,
                    as: "serials",
                    required: false,
                    where: {
                      rec_prod_id: id,
                    },
                  },
                ],
              },
            ],
          },
          {
            model: db.user,
            as: "added_by",
            include: {
              model: db.role,
              as: "roles",
            },
          },
        ],
        where: {
          [Op.and]: [
            {
              id,
              tenant_id: TENANTID,
            },
          ],
        },
        group: ['receiving_product.id']
      });

**Comment by ephys** [comment]
Hi! We get a lot of issues which takes a very long time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

You can edit this issue and ping us, and we will re-review.
As indicated in the issue template, issues that do not follow the template may be closed.

---

If this is not about a bug report or a feature request, prefer instead:

- StackOverflow: https://stackoverflow.com/questions/tagged/sequelize.js
- GitHub discussions: https://github.com/sequelize/sequelize/discussions (let us know and we'll convert this issue into a discussion)
