### ISSUE TITLE
NPM Audit for SequeizeImproper Filtering of Special Elements

### ISSUE THREAD

**Issue by anjanaNewput** [sequelize/sequelize#15706]
## Bug Description

 I am using sequelize node module in my node js aaplication and while doing audit for security vulnerability. Audit command gives critical warning for sequelize with no patch version available 

Here I am attaching the screenshot 
<img width="719" alt="Screenshot 2023-02-23 at 12 13 43 PM" src="https://user-images.githubusercontent.com/17215354/220857984-86f459a6-27be-448a-81be-9761c41538b9.png">

### Reproducible Example

1. Run `npm audit ` in your node js application
2. Gives above issue for sequelize dependency with no patch available to fix it.

I want to know how we can fix it if any hack is there or when it get fixed by the team sequelize.

- Sequelize version: 6.28.2
- Node.js version: 14.17.5

Since it is blocking our release and code merge. Quick help is really appreciated. Thanks in advance!

**Comment by ephys** [comment]
Please see https://github.com/sequelize/sequelize/discussions/15694
