### ISSUE TITLE
support [] parameter for mysql query for " where aaa in $1"

### ISSUE THREAD

**Issue by isee15** [sequelize/sequelize#15707]
### Describe the feature you'd like to see implemented

in mysql dialect, the implementation of query.js
```
async run(sql, parameters)
...
try {
      if (parameters && parameters.length > 0) {
        results = await new Promise((resolve, reject) => {
          connection
            .execute(sql, parameters, (error, result) => (error ? reject(error) : resolve(result)))
            .setMaxListeners(100);
        });
      } else {
        results = await new Promise((resolve, reject) => {
          connection
            .query({ sql }, (error, result) => (error ? reject(error) : resolve(result)))
            .setMaxListeners(100);
        });
      }
    } 
...

```
when query a sql like "select name, emaill from user where name in $1" with parameters ["john","jobs"], connection.query support well.
But connection.execute will throw exception。
So hope the sequelize can support array parameters[] for param bind.
maybe like this
```
if (parameters && parameters.length) {
        if (options.type === 'SELECT') {
            results = await new Promise((resolve, reject) => {
              connection.query(sql, parameters, (error, result) => error ? reject(error) : resolve(result)).setMaxListeners(100);
            });
          } else {
          results = await new Promise((resolve, reject) => {
            connection.execute(sql, parameters, (error, result) => error ? reject(error) : resolve(result)).setMaxListeners(100);
          });
        }
      } else {
        results = await new Promise((resolve, reject) => {
          connection.query({ sql }, (error, result) => error ? reject(error) : resolve(result)).setMaxListeners(100);
        });
      }
```

### Describe why you would like this feature to be added to Sequelize

In our system， query with "in" param bind is usual, if use  Sequelize, we have to bind with "replacements", it can not to use query plan optimize

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [✓] Yes. This feature only applies to the following dialect(s): mysql-dialect

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ✓] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
As far as I'm aware this is not possible. `IN` requires a parameter for each value. You can't have a single bind parameter for all values you wish to pass to `IN`. You need to use replacements, or use something other than `IN`, such as `FIND_IN_SET`.

In postgres, `= ANY($param)` can be used, since they support arrays

**Comment by isee15** [comment]
use **?** mode
```
const prepareSql = 'select name, email from user where name in (?) and email=?'
const params = [['john','smith'], 'ccc@gmail.com']
conn.query(prepareSql, params,
```
I tried and it's ok.

**Comment by ephys** [comment]
That's still a replacement. mysql2[^1]'s `query` does not support bind parameters, they use replacements. Only `execute` supports bind parameters

This is a limitation of mysql[^1] itself, there is nothing we (nor mysql2[^1]) can do about it.

[^1]: mysql refers to the database, mysql2 to the npm library
