### ISSUE TITLE
How to use postgis with sequelize

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1577]
I know that sequelize does not support geo data type like postgis, but I would like to hack it to be able to insert geo data (lon and lat) and query by them to find nearest points.

Is it possible to somehow modify postgres query on the fly or maybe there is better method to do this? Could you give me some beta?

Are you planning to add support for PostGis in the future?

**Comment by yalva** [comment]
> 1 . Creating table
> 
> ```
> create table places(
>     lat_lng geography(Point,4326),
>     place_name varchar(50)
> );
> ```
> 
> 2 . Inset value into table (2 possible synatexes)
> 
> ```
> insert into places values (ST_MakePoint(-126.4, 45.32), 'Food Bar1');
> insert into places values ('POINT(-126.4 45.32)', 'Food Bar2');
> ```
> 
> 3 . Query - nearest within 1000m
> 
> ```
> select *, ST_Distance(lat_lng, ST_MakePoint(-126.4, 45.32)::geography)
> from places
> where ST_DWithin(lat_lng, ST_MakePoint(-126.4, 45.32)::geography, 1000)
> order by ST_Distance(lat_lng, ST_MakePoint(-126.4, 45.32)::geography);
> ```
> 
> Forgot about spatial index:
> 
> ```
> create index places_lat_lng_idx on places using gist(lat_lng);
> ```

How to retrieve lat, long with find?
