### ISSUE TITLE
"order by" appeared twice in generated sql which cause side effect - " Unknown column 'Model.createdAt' in 'order clause'"

### ISSUE THREAD

**Issue by theromie** [sequelize/sequelize#15776]
```
await Recipients.findAll({include: [
        {
          model: RecipientTagMaps,
          attributes: ["id"],
          include: [{ model: Tags }],
        },
      ],
      limit: limit,
      offset: offset,
      order:[['createdAt','DESC']],
      });
```
// models details are as below
`Recipient.hasMany(models.RecipientTagMaps, { foreignKey: "recipientId" });`
`RecipientTagMap.belongsTo(models.Recipients, { foreignKey: "recipientId" });`

I came across an exception: "SequelizeDatabaseError: Unknown column 'Recipients.createdAt' in 'order clause'".

Seems the 'Order by' was applied twice.

Dialect: mysql / postgres / sqlite / mssql / any
Dialect version: mysql
Database version:
Sequelize version: ^6.28.0

**Comment by ephys** [comment]
Hi! We get a lot of issues which takes a very long time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

As indicated in the issue template, issues that do not follow the template may be closed.
You can edit this issue and ping us, and we will re-review and re-open this issue (there is no need to create a new issue).

---

If this is not about a bug report or a feature request, prefer instead:

- StackOverflow: https://stackoverflow.com/questions/tagged/sequelize.js
- GitHub discussions: https://github.com/sequelize/sequelize/discussions (let us know and we'll convert this issue into a discussion)
