### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by Predrag** [sequelize/sequelize#15781]
Hello, 

is it possible to run Sequelize on Raspberry pi 4B ARM v 8 (Ubuntu 22.10 64 bit)? I have compiled node-oracledb, installed oracle instant client for ARM but when I run some query I am getting this error: " TypeError: connection.isHealthy is not a function". On x86_64 system I am not getting this error.

**Comment by WikiRik** [comment]
Upon a quick look it seems that this issue probably lies within the node-oracledb project. Check if you follow the installation instructions correctly; https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html#node-oracledb-installation-instructions and if so, open an issue at https://github.com/oracle/node-oracledb
