### ISSUE TITLE
Always include association

### ISSUE THREAD

**Issue by yuri0** [sequelize/sequelize#1582]
Is it possible / can it be made possible to have a model ALWAYS eager-load a particular association (without having to specify it)? This came about from refactoring several columns in table A into rows in table B, with A `hasMany` B and each B `belongsTo` (/ `hasOne`) A.

**Comment by Kuzmin** [comment]
How is progress with extending defaultScope? Would be a nice feature to have.

**Comment by janmeier** [comment]
@Kuzmin Not much progress have been made yet - We'll probably need to write up a proper spec for the things that need to be rewritten

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
