### ISSUE TITLE
Nodejs Crash when added to Angular/Universal

### ISSUE THREAD

**Issue by cyberiums** [sequelize/sequelize#15853]
I have researched this issue at SO.

This is basically a new type. I am trying to add Sequelize backend in Angular Universal. In pure backend only, I know this.

When you add the statement "const sequelize = new Sequelize();" in server.ts, node crashes.

### Reproducible Example
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.11
@angular-devkit/build-angular   14.2.11
@angular-devkit/core            14.2.11
@angular-devkit/schematics      14.2.11
@angular/cdk                    14.2.7
@angular/cli                    14.2.11
@angular/material               14.2.7
@nguniversal/builders           14.2.3
@nguniversal/express-engine     14.2.3
@schematics/angular             14.2.11
rxjs                            6.5.5
typescript                      4.8.4
webpack                         5.76.3

{

  npm: '8.19.2',
  node: '16.17.0',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

"sequelize": "^6.30.0",

## Would you be willing to resolve this issue by submitting a Pull Request? I will try.

- [ ] Yes, I have the time and I know how to start.
- [Y ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

I am willing to fix this.

**Comment by ephys** [comment]
What sort of error are you getting?
