### ISSUE TITLE
Extend #759 Bug fix - Make the getters on associations also run under a .toJSON() call.

### ISSUE THREAD

**Issue by redevill** [sequelize/sequelize#15878]
## Feature Description
When calling the .toJSON() method on a Sequelize object, I would expect that the getters are run on all the fields specified in the model.

My "Form" model has an association (Form object has multiple fields)
The standard return format for this association is an array of objects - a Record<string, Field> is needed for speedy keyed access.
Included in the model is a getter to transform this Array => Record transform.

When returning the object from the server - I would be good to be able to correctly serialize the model without resorting to individual hacks on association type fields.

As stated above - .toJSON() should invoke all existing getters on the model.

Because it is a Sequelize model, and sequelize should be responsible for it's serialization under the existing sequelize interface aka .toJSON()

### Is this feature dialect-specific?
No

### Would you be willing to resolve this issue by submitting a Pull Request?
With some help - Yes. Point me to the serialization section, and I will try and put something together.

- [x ] Yes, I have little time,  and will need some guidance.

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
I don't think that would be a good idea. We don't know what these getters depend on and doing this will cause more breakage than is worth

I recommend you override your toJSON method to customize its output instead

**Comment by redevill** [comment]
@ephys - Not sure you understood the request. 
The Getters NOT firing was considered a BUG in Fix #759 - they are still not all firing.

"your toJSON" - it is not "MY" method - it is Sequelize's Model toJSON method - and in what world is it, that you would not be consistent in calling all getters during a serialization request ?!?! 

Granted - if a developer has put something "nasty" in a getter or setter (Sequelize should not compromise the serialization standard for this) perhaps a decorator can be added to opt out for that getter during serialization.

**Comment by ephys** [comment]
I would recommend writing a json serialization library like that. It would be very useful to be able to control how an object serializes based on decorators.

I don't think it's the role of an ORM and tightly coupling it to an ORM would not do it justice. This is the sort of thing that should work with any class, not just our models.

We're designing a plugin API, which will first be used to support any validation API instead of limiting users to our built-in validators. If a serialization library needs to hook into a model, the plugin API could cover this
