### ISSUE TITLE
Postgres Eager loading SQL syntax error.

### ISSUE THREAD

**Issue by vjames19** [sequelize/sequelize#1589]
When I execute `db.GoesVariable.findAll({include: [db.GoesMap]});`

This is what I get:

```
Executing (default): SELECT GoesVariables.*, GoesMaps.variableName AS GoesMaps.variableName, GoesMaps.imagePath AS GoesMaps.imagePath, GoesMaps.dataDate AS GoesMaps.dataDate, GoesMaps.createdAt AS GoesMaps.createdAt, GoesMaps.updatedAt AS GoesMaps.updatedAt FROM GoesVariables LEFT OUTER JOIN GoesMaps AS GoesMaps ON GoesVariables.variableName = GoesMaps.variableName;
{ [error: syntax error at or near "."]
  name: 'error',
  length: 83,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '58',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'scan.l',
  line: '1053',
  routine: 'scanner_yyerror',
```

Is there a way to fix this?

The following has my model definitions
Model: GoesVariable

``` js
'use strict';

module.exports = function(sequelize, DataTypes) {

  var GoesVariable = sequelize.define('GoesVariable', {
    variableName: {
      type: DataTypes.STRING,
      primaryKey: true
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
      validate: {
        notEmpty: true
      }
    }
  }, {
    classMethods: {
      associate: function(models) {
        GoesVariable.hasMany(models.GoesMap, {foreignKey: 'variableName'});
        GoesVariable.hasMany(models.GoesData, {foreignKey: 'variableName'});
      }
    }
  });

  return GoesVariable;
};
```

Model: GoesMap

``` js
'use strict';

module.exports = function(sequelize, DataTypes) {
  var GoesMap = sequelize.define('GoesMap', {
    variableName: {
      type: DataTypes.STRING,
      references: 'GoesVariables',
      referencesKey: 'variableName',
      primaryKey: true
    },
    imagePath: {
      type: DataTypes.STRING,
      primaryKey: true,
      validate: {
        notEmpty: true
      }
    },
    dataDate: {
      type: DataTypes.DATE,
      primaryKey: true
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
      primaryKey: true
    },
  }, {
    classMethods: {
      associate: function(models) {
        GoesMap.belongsTo(models.GoesVariable, {foreignKey: 'variableName'});
      },
      getLatest: function(variableName) {
        return GoesMap.find({
          where: {
            variableName: variableName
          },
          order: 'dataDate desc'
        });
      },
      getMapsBetween: function(variableName,startDate, endDate) {
        return GoesMap.findAll({
          where: {
            variableName: variableName,
            dataDate: {
              between: [startDate, endDate]
            }
          }
        });
      }
    }
  });

  return GoesMap;
};

```

**Comment by idris** [comment]
@mickhansen I'm having this same issue.  Was this ever fixed?

**Comment by mickhansen** [comment]
@idris A case was never provided

**Comment by idris** [comment]
I couldn't figure out how to write a unit test for this, but I fixed the problem (at least it fixed my use case)
https://github.com/sequelize/sequelize/pull/3780

**Comment by ra50** [comment]
This bug is marked as fixed in release 3.1.1 but the fix is incomplete.  When doing a many-to-many join through a junction table, the alias name ends up being two "levels" deep, for instance Table2.joinTable, and this alias is not quoted.  Other aliases are.  The quoting needs applied to these aliases as well.  In addition, the quoting needs to be used when the alias is used elsewhere to reference a column, for instance in the ON clause of the join.

This entire issue could also be avoided by not using "." in aliases in the first place.  If it just used underscores instead, no quotes would be necessary and the SQL would be valid.  Considering the aliases don't really matter, this could be an easier solution than inserting quotes even when quoteIdentifiers is set to false.

**Comment by mickhansen** [comment]
@ra50 underscores don't work since they can be a part of a legal field identifier (ex: `first_name`)

**Comment by ra50** [comment]
I see how that could be an issue if the alias ended up matching an actual column somewhere.  Either way, this bug should not be marked closed as the included fix is incomplete.  Junction table aliases, and the reference of those aliases, need quoted as well.

**Comment by aray12** [comment]
Is this being discussed any further? +1 for fix

**Comment by yjx3097890** [comment]
+1 for fix
