### ISSUE TITLE
findAndCountAll return count is not correct

### ISSUE THREAD

**Issue by xtieume** [sequelize/sequelize#15943]
> const orders = await models.orders.findAndCountAll({
      include: [
        {
          model: models.carts,
          where: { orderId: sequelize.col('orders.orderId') },
          include: [
            {
              model: models.products,
              required: false,
            }
          ],
          required: false,
        },
       ............
        },
      ],
      where,
      order: orderCriteria,
      offset,
      limit,
    });

The count result is 182, but my database just have 177 record, The problem here is join condition, Its return many duplicate row => the counting is not correct (182), when I get orders.rows.length it is 177

**Comment by frostzt** [comment]
I believe this was something I had seen #15092

**Comment by ephys** [comment]
Closing due to not following the issue template
This is likely the same issue as https://github.com/sequelize/sequelize/issues/10557
