### ISSUE TITLE
Add Github Sponsoring

### ISSUE THREAD

**Issue by hughcrt** [sequelize/sequelize#15952]
### Describe the feature you'd like to see implemented
Please consider adding Github Sponsoring for the organization to receive donation directly on Github.

### Describe why you would like this feature to be added to Sequelize
There's less friction to sponsor directly via Github compared to using other services. I would be glad to sponsor Sequelize if it was available on Github, and I guess I'm not the only one that would do so.

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
You can donate to us through OpenCollective already; https://opencollective.com/sequelize

But we can look into GitHub Sponsorships as well, I'll forward this to an internal discussion with the team. Thanks for the suggestion!

**Comment by ephys** [comment]
[Github Sponsoring](https://github.com/sponsors/sequelize) was added :)
