### ISSUE TITLE
cannot install pre released version of sequelize

### ISSUE THREAD

**Issue by HMhamedminaee** [sequelize/sequelize#15974]
when I try to install alpha version as follows 

` npm i sequelize@7.0.0-alpha.26  --save`

I get 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for sequelize@7.0.0-alpha.26.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

is the pre released not published yet?

**Comment by WikiRik** [comment]
Starting with v7, we're releasing on `@sequelize/core` while we prepare to release dialect-specific packages in future major releases. You can find it here; https://www.npmjs.com/package/@sequelize/core
