### ISSUE TITLE
findOrCreate is not atomic

### ISSUE THREAD

**Issue by vincentbernat** [sequelize/sequelize#1599]
Hi!

I would expect `findOrCreate()` method to be atomic. However, it just calls `find()` and if  unsuccessful, it will call `create()`. If I run two of them in parallel, I get a constraint error, assuming a unique constraint on `name`:

``` js
Promise.all([User.findOrCreate({name: "John"}, {age: 47}),
             User.findOrCreate({name: "John"}, {age: 49})])
  .spread(function(john1, john2) {
    console.log("All done!")
  }), function(err)  {
    console.log(err);
  });
```

I would have expected that something like `INSERT ...  ON DUPLICATE KEY IGNORE` would be used.

**Comment by soryy708** [comment]
So was this fixed or not? Is `findOrCreate` atomic in Sequelize v6?

**Comment by ephys** [comment]
It's executed in a transaction (or a savepoint if a transaction is already active)

**Comment by soryy708** [comment]
So it should be atomic. How are these 2 paths tested?
