### ISSUE TITLE
Query `sqlite_master`

### ISSUE THREAD

**Issue by vincentbernat** [sequelize/sequelize#1612]
Hi!

I would like to test if I get the same tables when running `.sync({force: true})` and when using the migration process. I am using in-memory SQLite tables for that. I thought that I would be able to query `sqlite_master` special table and compare the `sql` column. However, since this table is schema-less, it seems that there is a bit of magic behind it.

`SELECT * FROM sqlite_master` will return names. `SELECT sql FROM sqlite_master` will return `undefined` for each row. `SELECT 1 FROM sqlite_master` will also return `undefined` for each row.

How should this table be queried?

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
