### ISSUE TITLE
Our vulnerability detection tool lists sequelize as vulnerable for semver library

### ISSUE THREAD

**Issue by HMhamedminaee** [sequelize/sequelize#16180]
Our vulnerability detection tool lists sequelize as vulnerable for semver library

npm ls semver --production 

└─┬ sequelize@6.32.0
  └── semver@7.5.1

Can you please shed light?

**Comment by WikiRik** [comment]
`npm audit fix` can fix this as semver is not pinned. Otherwise removal of node_modules folder and lockfile and reinstalling dependencies also works

**Comment by ephys** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/16265
