### ISSUE TITLE
Can't run migration script

### ISSUE THREAD

**Issue by takempf** [sequelize/sequelize#162]
note: I'm running Windows 7 64 bit

I've been hitting my head against my desk for the past few days attempting to get migrations working, but nothing I attempt to do seems to work. I'd like to know if I'm doing something wrong, or if there is a problem...

My folder is set up like so:
/config (with /config.json within)
/migrations (with /1.js within)
/node_modules (with /sequelize within)
/server.js

I've been trying to run my migration with the following two commands:

`node_modules\.bin\sequelize -m` and `node_modules/sequelize/bin/sequelize -m`

Each time I get the same error:

```
timers.js:96 if (!process.listeners('uncaughtException').length) throw e;
TypeError: Cannot read property '1' of null
at new <anonymous> (node_modules\sequelize\lib\migration.js:13:66)
at (node_modules\sequelize\lib\migrator.js:89:14)
```

My migration file `1.js` is as follows:

``` javascript
module.exports = {

    up: function( migration, DataTypes ){

        migration.createTable( 'projects', {
            title:          DataTypes.STRING,
            description:    DataTypes.TEXT
        });

        migration.createTable( 'tasks', {
            title:          DataTypes.STRING,
            description:    DataTypes.TEXT,
            deadline:       DataTypes.DATE
        });

    },

    down: function( migration, DataTypes ){

        migration.dropTable('projects');
        migration.dropTable('tasks');

    }

};
```

**Comment by michaelgarde** [comment]
I know this is really old but since it popped up in a google search i thought i might as well add, that you can use sequelize to generate the scripts:
`sequelize migration:generate --migrations-path migrations --name{{NAME-OF-MIGRATION}}`
