### ISSUE TITLE
Is `validator` really "exposed"?

### ISSUE THREAD

**Issue by catamphetamine** [sequelize/sequelize#16223]
Following the discussion in https://github.com/sequelize/sequelize/pull/16222#issuecomment-1615975113

I've looked that the code in `src\model.js` and seems like Sequelize models have an instance method called `async validate(options)`:

```js
const { InstanceValidator } = require('./instance-validator');

export class Model extends ModelTypeScript {
  /**
   * Validate the attribute of this instance according to validation rules set in the model definition.
   *
   * Emits null if and only if validation successful; otherwise an Error instance containing
   * { field name : [error msgs] } entries.
  *
  * @param {object} [options] Options that are passed to the validator
  * @returns {Promise}
  */
  async validate(options) {
    return new InstanceValidator(this, options).validate();
  }
}
```

`InstanceValidator` doesn't seem to be imported anywhere else.
So what's `InstanceValidator`?

From the code in `src/instance-validator.ts`:

```js
/**
 * Instance Validator.
 *
 * @param {Instance} modelInstance The model instance.
 * @param {object} options A dictionary with options.
 *
 * @private
 */
export class InstanceValidator {
    /**
     * Exposes a reference to validator.js. This allows you to add custom validations using `validator.extend`
     *
     * @name validator
     * @private
     */
    this.validator = validator;
}
```

So it assigns `this.validator` variable but doesn't ever use it.

Which raises the question: Is the reference to validator.js really "exposed"?
If the end user can't access `InstanceValidator` directly — only the `.validate(options)` method of it — then looks like the validator.js reference is not exposed?

If it's not exposed then that comment could be corrected and then there'd be no need to import the `validator` as a whole, only the few used functions of it.

What are your thoughts?
Would you accept a pull request that introduces that type of change?

**Comment by ephys** [comment]
Everything related to the `validator` library is going to be moved to its own package in a future major release, see https://github.com/sequelize/sequelize/issues/15497 

Until then, we have no choice but to import all of it due to how the individual validators are declared and invoked: https://github.com/sequelize/sequelize/blob/7022c48214901aadceca87709835ee1f5bb36bfc/packages/core/src/instance-validator.js#L317-L330

**Comment by catamphetamine** [comment]
@ephys Oh, I see, it does get exposed in the `_invokeBuiltinValidator()` method of `InstanceValidator`. Seems like a developer could supply a name of a certain `isXxx` function and then it gets called on the `validator` package. Ok then, closing.
