### ISSUE TITLE
Sequelize Grant privileges to user for all tables, executed correctly, but not working

### ISSUE THREAD

**Issue by NikolayChankov90** [sequelize/sequelize#16243]
When i am creating a spefic tenant database , i create the database with the sequelize connection established , which manipulates the Master database. 

    masterDBsequelize.query(`CREATE DATABASE ${createdTenant.databaseName}`);

And after the creation of the database using the `createdTenant` record *(which is a record saved in the master database)* I connect to that specific databaase with:

    const dbOptions = {
        host: DATABASE_HOST,
        port: DATABASE_PORT,
        database: createdTenant.databaseName,
        username: MASTER_DATABASE_USER_NAME,
        password: MASTER_DATABASE_PASSWORD,
        dialect: 'postgres'
      };

      const tenantSequelize: Sequelize = new Sequelize(dbOptions);

It is important to mention that i use `sequelize-typescript` library.

After that i create user with the master database connection: 

    const username = `user_123}`;
    const password = `userPassword_123`;
    const createUserQuery = `CREATE USER ${username} WITH PASSWORD '${password}'`;

    await masterDbSequelize.sequelize.query(createUserQuery, { transaction });

After that grant privilages with tenant specific database connection: 

    const grantPrivilegesQuery = `
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${username}; 
    GRANT ALL PRIVILEGES ON TABLE "Device" TO ${username};`;

    await tenantSequelize.query(grantPrivilegesQuery, { transaction });

In the console i receive the whole string which confirms the creation of the database the granting of the privalages. When that happens i diconnect from the database.

And when i execute http request to connect to the Tenant database with the needed credentials it established the conneciton succesfullt using the `authenticate()` method of Sequelize the promise returned is successfull . And when i try to create a record in Device table i receive an error: 

    Error on executing createDevice SequelizeDatabaseError: permission denied for table Device 

When i check in PGAdmin  the created users and their privileges on the created user `user_123}` it shows that it has `canLogin`  & `inherit rights from parent roles` .

**Comment by WikiRik** [comment]
This is not an issue with sequelize, but a general postgres one. Check if the user is created properly on the tenant database and got the correct privileges.
