### ISSUE TITLE
afterValidate hook is not called when validation fails

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1626]
When validation errors occur (for example during `Model.create(...)` then `afterValidate` hook is not called. It would be a good feature to be able to catch validation errors in a hook - is it possible?

If not maybe you could implement this functionality in new version?
For example like this:
```
hooks: { afterValidate: function(model, done) { console.error(model.validationErrors)... } }
```
or
```
hooks: { afterValidationFailed: function(err, model, done) { ... } }
```
or something like this.

**Comment by ptusch** [comment]
*Push*

It would be nice to work with failed validation.

**Comment by janmeier** [comment]
Added in https://github.com/sequelize/sequelize/issues/5196
