### ISSUE TITLE
continuation-local storage support w/ bluebird

### ISSUE THREAD

**Issue by devcommunity** [sequelize/sequelize#1627]
It seems that Sequelize and CLS + Bluebird aren't friends, i'm trying to use CLS to maintain state for logging and other things, CLS works quite well with the cls-bluebird patch, but the CLS context / state is lost immediately after all Sequelize calls.

The state is maintained through a quite deep promise chain (so the bluebird CLS patch is working), but once it hits a Sequelize query() promise the context is lost from the query result promise onwards.

I realise CLS is quite new, but thought it might be a simple solution, or i'm missing something!

**Comment by yzia2000** [comment]
Hi @janmeier does https://github.com/sequelize/sequelize/pull/2810 solve this issue? Or are we expected to patch bluebird in our code?

**Comment by WikiRik** [comment]
Hi @yzia2000
This issue is 8 years old and will probably not apply to the current versions of sequelize anymore. As far as I know bluebird is not used anymore with sequelize

**Comment by yzia2000** [comment]
> Hi @yzia2000
> This issue is 8 years old and will probably not apply to the current versions of sequelize anymore. As far as I know bluebird is not used anymore with sequelize

Thanks @WikiRik for the reply. Any knowledge on the current state of cls sequelize and bluebird? Is it recommended that we migrate away from bluebird to native promises rn?

**Comment by WikiRik** [comment]
@yzia2000 yes, I believe so
