### ISSUE TITLE
Query on postgreSQL is not consistent on code Sequelize

### ISSUE THREAD

**Issue by EmmanDizon** [sequelize/sequelize#16279]
I have a query wherein i want only to select dates without no timestamp on it.
Since on this column, i have some dates with timestamp and without timestamp.

example:
without timestamp -> 2023-04-21 00:00:00+08
with timestamp -> 2023-02-01 18:45:54+08

to achieve selecting only dates without timestamp, i have this sequelize code:

` const tdInfos = await TdInfos.findAll({
    where: Sequelize.where(Sequelize.fn('date_trunc', 'day', Sequelize.col('maturityDate')), Sequelize.col('maturityDate')),
  });
  
  console.log(tdInfos); // no result, just empty []
`
Unfortunately, i got no result.

after that I check terminal logs and saw like this:

`SELECT * 
FROM "tdInfos"
WHERE date_trunc('day', "maturityDate") = "maturityDate";`

Then i copy it and paste this query on pg admin.

and look, i got my expected result.

Thus, above explanation, im reporting this one, its not consistent.  how come its not, im using same postgres.
Is there a difference on actual query on postgres vs on code sequelize?

Im using sequelize version:  "sequelize": "^6.32.1",
and "pg": "^8.11.1",
and the dialect is "postgres"

**NOTE:**
I'm using the right database credentials for this one. I'm using the right database.
Whenever Im querying SELECT * FROM WHERE Id = ?, just to test if im on the same page of database, yes.

the result is right and on the PG admin when i query.

Now, my concern only lies on this specific scenario wherein im trying to select dates without timestamp using literal "provided screenshot below" or using query sequelize above mentioned which is: `const tdInfos = await TdInfos.findAll({
where: Sequelize.where(Sequelize.fn('date_trunc', 'day', Sequelize.col('maturityDate')), Sequelize.col('maturityDate')),
});`

**Comment by EmmanDizon** [comment]
this is what im talking about exactly

![image](https://github.com/sequelize/sequelize/assets/93915230/8ce059d0-49e7-4cea-95c7-68159e880006)
![image](https://github.com/sequelize/sequelize/assets/93915230/39f8b2ad-36fd-4aa3-81d3-f33119309f64)

**Comment by EmmanDizon** [comment]
@ephys help me please

**Comment by ephys** [comment]
Unfortunately without a reproducible example we can't help with this :(
