### ISSUE TITLE
renameColumn on auto-inc PK fails

### ISSUE THREAD

**Issue by bblack** [sequelize/sequelize#1629]
I have a mysql table with a primary key of type INT(11), not null, auto_increment. Running a migration to renameColumn(), I get a failure because this query is executed:

```
ALTER TABLE `fruits` CHANGE `fruitId` `fruit_id` INT(11) NOT NULL DEFAULT NULL;
```

```
Error: ER_INVALID_DEFAULT: Invalid default value for 'fruit_id'
```

**Comment by Bulforce** [comment]
Rename column is not working for columns that are primary key.
