### ISSUE TITLE
`attributeSelector` arg for getQueryInterface().rawSelect() does not process an array of strings

### ISSUE THREAD

**Issue by joseph-hailu-dd** [sequelize/sequelize#16424]
I took a peak at the source for v6 and the typedef for the `attributeSelector` is a [string or an array of strings ](https://github.com/sequelize/sequelize/blob/v6/src/dialects/abstract/query-interface.d.ts#L579)
```typescript
  /**
   * Selects raw without parsing the string into an object
   */
  public rawSelect(
    tableName: TableName,
    options: QueryOptionsWithWhere,
    attributeSelector: string | string[], // i am passing array of strings
    model?: ModelType
  ): Promise<string[]>;
```

but it seems the method does not account for [an array of strings being passed  for `attributeSelector`](https://github.com/sequelize/sequelize/blob/v6/src/dialects/abstract/query-interface.js#L1048)

```typescript
const result = data ? data[attributeSelector] : null;
```

this means the query below returns undefined
```typescript
const r = await sequelize
        .getQueryInterface()
        .rawSelect(
           'tableName',
           { plain: true, raw: true, where: { [primaryKeyColumn]: id } },
           [ "id", "col1", "col2"],
        );
 console.log({ r });
```

_Originally posted by @joseph-hailu-dd in https://github.com/sequelize/sequelize/discussions/16112#discussioncomment-6137960_

**Comment by ephys** [comment]
`QueryInterface.rawSelect` is not a public API yet, which is why it has strange behaviors. We're working on making all available methods of that class public in v7, but this one isn't one of them yet
