### ISSUE TITLE
order: ['updatedAt', 'DESC']: column "DESC" doesn't exist

### ISSUE THREAD

**Issue by golergka** [sequelize/sequelize#1643]
I have code that looks like this:

```
SomeModel.find({ // ... there was some irrelevant where block
    order: ['updatedAt', 'DESC']
});
```

According to the example at http://sequelizejs.com/docs/latest/models#finders this should work, but I get this instead:

```
Executing (default): SELECT * FROM "SomeModel" WHERE ... ORDER BY "updatedAt", "DESC" LIMIT 1;
error: column "DESC" does not exist
```

**Comment by stevemarksd** [comment]
they should add typescript...

**Comment by mickhansen** [comment]
@stevemarksd https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sequelize

**Comment by papb** [comment]
@stevemarksd @mickhansen Actually since v5 we ship our own typescript types now, so @stevemarksd if you encounter any issue involving typescript on Sequelize please open a detailed issue about it for us to look at! Thanks!
