### ISSUE TITLE
NOT Operator does not work properly in deep "WHERE" conditions in version 7

### ISSUE THREAD

**Issue by amoqaddam** [sequelize/sequelize#16437]
Hello
I found an strange bug in version 7.0.0-alpha.27

when i use deep objects in "WHERE" option, the "[Op.not]" Operator does not work properly
but the same condition works propely in version 6

for example this conditions does not work in version 7
-------------
```
where: {
    [Op.not]: {
        [Op.or]: {
            [Op.and]: {
                id: {
                    [Op.gt]: 4,
                },
                password: {
                    [Op.like]: "%a%",
                },
            },
            [Op.or]: {
                id: {
                    [Op.gt]: 7,
                },
                password: {
                    [Op.like]: "%c%",
                },
            },
        },
    },
}
```
-------------

but it works properly in version 6

actually generated SQL Query has not proper parentheses (in version 7)

**Comment by WikiRik** [comment]
Can you share an example including the generated SQL for version 6 and the v7 alphas?

**Comment by amoqaddam** [comment]
> Can you share an example including the generated SQL for version 6 and the v7 alphas?

Yes
This is generated SQL in version 7
----------------
`SELECT `id`, `username`, `password` FROM `Users` AS `User` WHERE NOT (`User`.`id` > 4 AND `User`.`password` LIKE '%a%') OR (`User`.`id` > 7 OR `User`.`password` LIKE '%c%')`
----------------

and this is generated SQL in version 6
---------------
`SELECT `id`, `username`, `password` FROM `Users` AS `User` WHERE NOT (((`User`.`id` > 4 AND `User`.`password` LIKE '%a%') OR (`User`.`id` > 7 OR `User`.`password` LIKE '%c%')))`
---------------

**Comment by jmjuanico** [comment]
indeed its not working. the Op.or on this example is completely ignored on version 7. was working on version 6. {
      where: {
        branchId,
        objType: 'column',
        [Op.or]: [
          { '$draftColumn.merge_id$': { [Op.not]: null } },
          { '$draftColumn.id$': null },
        ],
      },
      size: chunkSize,
      include: [
        {
          model: DraftColumn,
          as: 'draftColumn',
          required: false,
          duplicating: false,
          where: { branchId },
        },
      ],
    }

**Comment by WikiRik** [comment]
I've adapted your example into the following test, which passes on the current `main`.

```
      testSql({
        [Op.not]: {
          [Op.or]: {
            [Op.and]: {
              intAttr1: {
                [Op.gt]: 4,
              },
              stringAttr: {
                [Op.like]: '%a%',
              },
            },
            [Op.or]: {
              intAttr1: {
                [Op.gt]: 7,
              },
              stringAttr: {
                [Op.like]: '%c%',
              },
            },
          },
        },
      }, {
        default: 'NOT ((`intAttr1` > 4 AND `stringAttr` LIKE \'%a%\') OR (`intAttr1` > 7 OR `stringAttr` LIKE \'%c%\'))',
      });
```

So based on that I think the current behaviour is correct. @amoqaddam can you confirm that this is also the behaviour you would expect?

See also similar tests that we already have;
https://github.com/sequelize/sequelize/blob/651f0b08a50c6b8ce2b9bde4e6b00a3c11953acf/packages/core/test/unit/sql/where.test.ts#L2650-L2718
