### ISSUE TITLE
Need for enchanced validation error reporting

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1649]
In `1.7.0` validation error is returned as object - for example:

```
{
    "email": [
      "Validation isEmail failed: email"
    ],
    "password": [
      "Validation len failed: password"
    ],
    "firstName": [
      "Validation len failed: firstName",
      "Validation isAlpha failed: firstName"
    ],
    "lastName": [
      "Validation len failed: lastName",
      "Validation isAlpha failed: lastName"
    ],
    "gender": [
      "Validation isIn failed: gender"
    ],
}
```

I know that in `2.x.x` validation error will be `Error` instance.
It would be nice if error for each field contained some extra information along with validation error message. For example:

```
{
    "email": [
      { msg: "Validation isEmail failed: email", rule: "isEmail", value: "bademail@" }
    ],
    "firstName": [
       { msg: "Validation len failed: firstName", rule: "len", value: "toolongname" },
       { msg: "Validation isAlpha failed: firstName", rule: "isAlpha", value: "_!@#$ ABC" }
    ],
}
```

This would be very useful when someone wants to return list of validation errors from the REST api for example. For now I am parsing error message to capture `ruleName`...

**Comment by Joanne16** [comment]
Has this been added to the latest release of sequelize ? (i.e. have additional information such as "rule" in the error object)

Thanks

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/commit/8be24f37d819245dcc61ad12f459388089eac34f now Error object support `message`, `type`, `path` and `value`
