### ISSUE TITLE
Can't resolve 'pg-hstore'

### ISSUE THREAD

**Issue by IDrumsey** [sequelize/sequelize#16506]
Using Sequelize with Nextjs 13 seems to have a bug where it can't find a module.

```
- error ./node_modules/sequelize/lib/dialects/postgres/hstore.js:2:15
Module not found: Can't resolve 'pg-hstore'
```

I'm simply trying to establish a connection to my mssql database

```
import { Sequelize} from "sequelize"

export function getSQLConnector(): Sequelize {
  const sequelize = new Sequelize({
    host: process.env.SERVER_NAME,
    database: process.env.DB_NAME,
    username: process.env.USERNAME,
    password: process.env.PASSWORD,
    dialect: "mssql",

      options: {
        encrypt: true,
        trustServerCertificate: false,
      },
    },
  })

  return sequelize
}
```

also happening for this guy - https://stackoverflow.com/questions/76496664/module-not-found-cant-resolve-pg-hstore-sequelize-and-nextjs13

Other projects using Next.js 12 are working, so it's a Next.js 13 thing.

**Comment by WikiRik** [comment]
Looking at the [Next.js 13 update blog post](https://nextjs.org/blog/next-13#breaking-changes) I do see the following breaking change;

> The swcMinify configuration property was changed from false to true. See Next.js Compiler for more info.


That might be the cause of this. Can you try to disable that property and see if that works?

**Comment by lohart13** [comment]
In v7, `pg-hstore` has been added as a dependency as per #15914.

Try adding `pg-hstore` to your dependencies and seeing if this resolves your issue.

**Comment by ephys** [comment]
Yes this is due to Next attempting to bundle. You need to either install the dependency or tell Next to not bundle Sequelize or pg-hstore
