### ISSUE TITLE
Error: Please install mysql2 package manually

### ISSUE THREAD

**Issue by wildy13** [sequelize/sequelize#16548]
```
require('dotenv').config();

const Sequelize = require('sequelize');
const mysql2 = require('mysql2')
const sequelize = new Sequelize(
    process.env.DB_NAME,
    process.env.DB_USERNAME,
    process.env.DB_PASSWORD,
    {
        host : 'localhost',
        dialect : process.env.DB_DIALECT,
        dialectModule: mysql2,
        dialectOptions: {
            dateStrings: true,
            typeCast: true,
        },
        pool: {
            max: 10,
            min: 0,
            idle: 10000,
        },
          
    }
)

const config = {
    host : process.env.BACKEND_HOST,
    port : process.env.BACKEND_PORT,
    secret: { session: process.env.SESSION_KEY },
}

module.exports = { sequelize, config }
```

but I'm still error, even though ive dialectModule
>Error: Please install mysql2 package manually

**Comment by ephys** [comment]
Based on the source code, it does try to use `dialectModule` if that is provided: https://github.com/sequelize/sequelize/blob/7c8972fa183e064d7f801446c286ded5514f89e9/src/dialects/abstract/connection-manager.js#L71-L73

If you're still getting that error, maybe the value used for `dialectModule` is falsy. If you `console.log` it you should get more information

I'm going to close the issue as I assume you found a solution by now, if that's not the case, please provide the information requested in the issue template so we can help you further: https://github.com/sequelize/sequelize/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1
