### ISSUE TITLE
Why does the Oracle dialect declare no support for locking?

### ISSUE THREAD

**Issue by Irfy** [sequelize/sequelize#16606]
The Oracle dialect declares no support for locking:

https://github.com/sequelize/sequelize/blob/367caf3fea02c5f66e6c57db0ecf67592a45e9e5/src/dialects/oracle/index.js#L31

This is unchanged from the PR for Oracle support by @sudarshan12s from about a year ago:

https://github.com/sequelize/sequelize/pull/14638/files#diff-370560d16016cf3a69bb97cc3299a7347f9ff170857f0b4c7cac861ca1b9a4c4R31

Is it intentional, i.e. is there an issue with using locking with oracle?

Is it an oversight?

I've tried monkey-patching the `lock` property to `true` and select statements then generated with `FOR UPDATE` as expected.

---

MSSQL dialect seems to suffer from the same issue: https://github.com/sequelize/sequelize/blob/v6.33.0/src/dialects/mssql/index.js#L34

v7-alphas do not mention oracle in their dialects: https://github.com/sequelize/sequelize/tree/v7.0.0-alpha.32/packages/core/src/dialects -- is oracle support being dropped?

**Comment by WikiRik** [comment]
I can't answer on using locking for Oracle at this moment, but I do know that Oracle support for v7 will be added later. The team from Oracle started with v6 support and will work on v7 support soon

**Comment by sudarshan12s** [comment]
Yes row/table level locks are supported in Oracle dialect. I will investigate on this.

**Comment by Irfy** [comment]
Thanks for your feedback. We will continue `npx patch-package`-patching it until it lands in a release.

**Comment by sudarshan12s** [comment]
> Thanks for your feedback. We will continue `npx patch-package`-patching it until it lands in a release.

I have raised [PR](https://github.com/sequelize/sequelize/pull/16643) for the same. Can you please see. (The checks failure seems to be some setup issue (node-gyp,..))
