### ISSUE TITLE
How to get all models and all their associated models where at least one associated model satisfies given requirements

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1661]
```
User.hasMany(Role);
Role.hasMany(User);

User.findAll({
   where: {/* some query */},
   include: [{ model: Role, attributes: ['name'], where: { name: ['member'] } }]
}).done(...)
```

This code returns all `users` that are associated with `role.name = 'member'`. But along with each user it returns ONLY one role that matches required name ('member').

What I want is to return ALL `roles` associated with each user, and filter users just to those that have at least one `Role` that match requirements.

Is it possible using Sequelize?

**Comment by arcanis** [comment]
I would also be interested if Sequelize supported this use case at some point.

**Comment by JemarJones** [comment]
@mickhansen Is this still the only solution with the most current version of sequelize?

**Comment by dsbert** [comment]
Is there any new functionality since this issue was closed to allow an existence check using an association?
