### ISSUE TITLE
ECONNABORTED error occurring when using bulkCreate 20,000 records.

### ISSUE THREAD

**Issue by iruthaya** [sequelize/sequelize#16710]
I'm trying to insert bulk (20,000) records using bulkCreate method its working fine in local machine but in windows server 2012 getting the following error 

{
	"response": {
		"code": "write ECONNABORTED",
		"message": "write ECONNABORTED",
		"name": "SequelizeDatabaseError",
		"stack": "Error: \n    at Query.run (E:\\Projects\\Aggregate_Report\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at E:\\Projects\\Aggregate_Report\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at MySQLQueryInterface.bulkInsert (E:\\Projects\\Aggregate_Report\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:881:21)\n    at recursiveBulkCreate (E:\\Projects\\Aggregate_Report\\node_modules\\sequelize\\src\\model.js:2850:25)\n    at Function.bulkCreate (E:\\Projects\\Aggregate_Report\\node_modules\\sequelize\\src\\model.js:2976:12)\n    at Object.createData (E:\\Projects\\Aggregate_Report\\src\\db\\dal\\caselist.ts:254:49)\n    at Object.createData (E:\\Projects\\Aggregate_Report\\src\\components\\caseListingLog\\caseListlog.service.ts:46:28)\n    at CaseListController.caseListUpload (E:\\Projects\\Aggregate_Report\\src\\components\\caseListingLog\\caselistingcontroller.ts:96:37)"
	}
}

connection config:
pool: {
        acquire: 50000
}

**Comment by ephys** [comment]
The query is likely too big and something in the network or on the remote server caused the query to be aborted.

We recommend chunking your insert into multiple inserts in a transaction
