### ISSUE TITLE
NEO4J - support of graphDB with Sequelize

### ISSUE THREAD

**Issue by yboujraf** [sequelize/sequelize#16718]
### Describe the feature you'd like to see implemented

- graphDB : to create / delete
- EDGE : CRUD
- NODE : CRUD

### Describe why you would like this feature to be added to Sequelize

Today, the relational databases is taking place in a complex data architecture.

**Comment by ephys** [comment]
Our current focus with this ORM is exclusively on SQL databases. This may change one day, but we currently have too many things we would like to do to be able to able to dedicate the resources to support a dialect that doesn't provide an SQL interface

We are moving dialects to their own individual packages. Once that is done, it should be possible for a third-party package to implement their own support for this dialect
