### ISSUE TITLE
Need for Postgres table inheritance

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1679]
It would be nice if Sequelize supported Postgres table inheritance.
It looks like this on SQL side (found this example in google):

```
CREATE TABLE post (id integer, title varchar(100), content text);
CREATE TABLE post_without_tags () INHERITS (post);
CREATE TABLE post_with_tags (tags text[]) INHERITS (post);
```

So it is as simple as adding `INHERITS (tableName)` after `CREATE TABLE` statement.
On Sequelize side to could look like this:

```
...
PostWithTags.inherits(Post)
PostWithoutTags.inherits(Post)
...
```

This functionality could be even emulated for other dialects/databases - `inherit` method could just copy attributes from `parent` to `child` model.

Here is documentation on Postgres table inheritance:
http://www.postgresql.org/docs/9.3/static/ddl-inherit.html

**Comment by thecaddy** [comment]
I have started using inherited tables and I took some time to write a plugin to create models easily assuming you have already set up your inherited tables and you want your models to inherit.

Below is a snip-it of the syntax I came up with, you can view the plugin and example gist here:
https://gist.github.com/thecaddy/b72a062b62b835fa06a8

```
export default function(sequelize, DataTypes) {
  const ChildModel = inheritFrom(sequelize, DataTypes)('childModel', inherittedModel, {
    // define child model specific properties here
      id: Sequelize.INTEGER,
      some_model_id: Sequelize.INTEGER
  }, {
    hooks: {
      beforeDestroy(instance, options) {
        return instance.sequelize.models.someModel({
          where: {
            id: instance.some_model_id
          }
        })
    },
    classMethods: {
      associate: function (models) {
        const {someModel} = models;
        this.belongsTo(someModel)
      }
    },

    instanceMethods: {
      anInstanceMethod(){}
    },
  });
  return ChildModel;
};
```

**Comment by felixfbecker** [comment]
If Instances will be instances of Models in the future it would make sense to check the prototype chain in of the Model in Model.init() for other Models and for Model.inherits() to set up prototype inheritance.
