### ISSUE TITLE
BigInteger corruption on MySQL

### ISSUE THREAD

**Issue by baliw** [sequelize/sequelize#1681]
I'm using MySQL and Sequelize 2.0.0-dev11.

I have a value in a table '276436166916084264' but when I pull the record in sequelize I get the value '276436166916084260'.

Seems like the last digit is getting zero'd out.

In my case, I'm using 64 bit integers for my primary key and this is causing major issues with associations for me.

Is there a solution to this available?

**Comment by hokkoo** [comment]
@baliw thank you .I got it.
