### ISSUE TITLE
column value is provided but it is giving a null error

### ISSUE THREAD

**Issue by dibyank-aither** [sequelize/sequelize#16828]
name: 'SequelizeDatabaseError',  parent: Error: Column 'status' cannot be null      at Packet.asError (/opt/node_modules/mysql2/lib/packets/packet.js:728:17)      at Query.execute (/opt/node_modules/mysql2/lib/commands/command.js:29:26)      at Connection.handlePacket (/opt/node_modules/mysql2/lib/connection.js:456:32)      at PacketParser.onPacket (/opt/node_modules/mysql2/lib/connection.js:85:12)      at PacketParser.executeStart (/opt/node_modules/mysql2/lib/packet_parser.js:75:16)      at Socket.<anonymous> (/opt/node_modules/mysql2/lib/connection.js:92:25)      at Socket.emit (node:events:517:28)      at addChunk (node:internal/streams/readable:335:12)      at readableAddChunk (node:internal/streams/readable:308:9)      at Readable.push (node:internal/streams/readable:245:10) {    code: 'ER_BAD_NULL_ERROR',    errno: 1048,    sqlState: '23000',    sqlMessage: "Column 'status' cannot be null",    sql: "update messages set status = CAST('delivered' as CHAR(255)), delivered_at = '2023-12-01 07:33:33' where id in (223637347,223754067,223751644,222479843,223082937,222894600);",    parameters: undefined  },  original: Error: Column 'status' cannot be null      at Packet.asError (/opt/node_modules/mysql2/lib/packets/packet.js:728:17)      at Query.execute (/opt/node_modules/mysql2/lib/commands/command.js:29:26)      at Connection.handlePacket (/opt/node_modules/mysql2/lib/connection.js:456:32)      at PacketParser.onPacket (/opt/node_modules/mysql2/lib/connection.js:85:12)      at PacketParser.executeStart (/opt/node_modules/mysql2/lib/packet_parser.js:75:16)      at Socket.<anonymous> (/opt/node_modules/mysql2/lib/connection.js:92:25)      at Socket.emit (node:events:517:28)      at addChunk (node:internal/streams/readable:335:12)      at readableAddChunk (node:internal/streams/readable:308:9)      at Readable.push (node:internal/streams/readable:245:10) {    code: 'ER_BAD_NULL_ERROR',    errno: 1048,    sqlState: '23000',    sqlMessage: "Column 'status' cannot be null",    sql: "update messages set status = CAST('delivered' as CHAR(255)), delivered_at = '2023-12-01 07:33:33' where id in (223637347,223754067,223751644,222479843,223082937,222894600);",    parameters: undefined  },  sql: "update messages set status = CAST('delivered' as CHAR(255)), delivered_at = '2023-12-01 07:33:33' where id in (223637347,223754067,223751644,222479843,223082937,222894600);",  parameters: undefined} | 2023-12-01T07:33:33.664Z e8a2168c-e822-56ee-9b8d-4b6f66240140 INFO Error at Query.run (/opt/node_modules/sequelize/lib/dialects/mysql/query.js:46:25) at /opt/node_modules/sequelize/lib/sequelize.js:626:28 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Runtime.handler (file:///var/task/index.mjs:280:17) { name: 'SequelizeDatabaseError', parent: Error: Column 'status' cannot be null at Packet.asError (/opt/node_modules/mysql2/lib/packets/packet.js:728:17) at Query.execute (/opt/node_modules/mysql2/lib/commands/command.js:29:26) at Connection.handlePacket (/opt/node_modules/mysql2/lib/connection.js:456:32) at PacketParser.onPacket (/opt/node_modules/mysql2/lib/connection.js:85:12) at PacketParser.executeStart (/opt/node_modules/mysql2/lib/packet_parser.js:75:16) at Socket.<anonymous> (/opt/node_modules/mysql2/lib/connection.js:92:25) at Socket.emit (node:events:517:28) at addChunk (node:internal/streams/readable:335:12) at readableAddChunk (node:internal/streams/readable:308:9) at Readable.push (node:internal/streams/readable:245:10) { code: 'ER_BAD_NULL_ERROR', errno: 1048, sqlState: '23000', sqlMessage: "Column 'status' cannot be null", sql: "update messages set status = CAST('delivered' as CHAR(255)), delivered_at = '2023-12-01 07:33:33' where id in (223637347,223754067,223751644,222479843,223082937,222894600);", parameters: undefined }, original: Error: Column 'status' cannot be null at Packet.asError (/opt/node_modules/mysql2/lib/packets/packet.js:728:17) at Query.execute (/opt/node_modules/mysql2/lib/commands/command.js:29:26) at Connection.handlePacket (/opt/node_modules/mysql2/lib/connection.js:456:32) at PacketParser.onPacket (/opt/node_modules/mysql2/lib/connection.js:85:12) at PacketParser.executeStart (/opt/node_modules/mysql2/lib/packet_parser.js:75:16) at Socket.<anonymous> (/opt/node_modules/mysql2/lib/connection.js:92:25) at Socket.emit (node:events:517:28) at addChunk (node:internal/streams/readable:335:12) at readableAddChunk (node:internal/streams/readable:308:9) at Readable.push (node:internal/streams/readable:245:10) { code: 'ER_BAD_NULL_ERROR', errno: 1048, sqlState: '23000', sqlMessage: "Column 'status' cannot be null", sql: "update messages set status = CAST('delivered' as CHAR(255)), delivered_at = '2023-12-01 07:33:33' where id in (223637347,223754067,223751644,222479843,223082937,222894600);", parameters: undefined }, sql: "update messages set status = CAST('delivered' as CHAR(255)), delivered_at = '2023-12-01 07:33:33' where id in (223637347,223754067,223751644,222479843,223082937,222894600);", parameters: undefined }
-- | --

This doesn't happen everytime but I will 30% for time I get this error. I need some help resolving this on mysql

**Comment by ephys** [comment]
Closing as this is not readable, does not follow the template, and does not provide the requested information

**Comment by j3rryl** [comment]
Did you find a solution? Experience the same as well. Sometimes it works, sometimes not despite all the values being present.

**Comment by thelaughinglama** [comment]
> For me this turned out to be a lock issue. When you have triggers on your table for on update or on insert
I am facing the same issue. How did you resolve it?

**Comment by thelaughinglama** [comment]
> For me this turned out to be a lock issue. When you have triggers on your table for on update or on insert

I am facing the same issue. How did you resolve this?
