### ISSUE TITLE
使用 Model.update 中  returning: true, 数据库数据真实被改变，但是没有正确返回对应的数据。并且，使用全局hook 监听不到更新事件。

### ISSUE THREAD

**Issue by Gf199811** [sequelize/sequelize#16840]
### 代码如下
`异步更新（id：编号，项目：ProjectEntity）：Promise<ProjectEntity> {
const timestamp = Date.now().toString(16);
const secretKey = generateSignature（时间戳，项目）；
const secretId = uuidv4().replace(/-/g, '');
const updatedProject = { projectName: projectDesc: projectDesc,secretKey: secretKey, secretId }
const transaction = await this.sequelize.transaction();
尝试{
const [rowsAffected, updatedProjects] = await ProjectEntity.updatedProject, { where: { id },returning: true, });
返回更新的项目[0];
} catch (err) { console.log(err) await transaction.rollback() }`
##全局钩子
`sequelize.addHook('afterUpdate', async (instance, options) => {
                await handleHook(instance, options, 'update', redisService);
            });`

**Comment by WikiRik** [comment]
Please ask your questions in English and use the issue template we provide. We can reopen once you have updated your message
