### ISSUE TITLE
eager loading error when calling getAll() function

### ISSUE THREAD

**Issue by Kendyelisca** [sequelize/sequelize#16879]
I have already established all the relationship logic but I am getting this error:

Error fetching stories: EagerLoadingError [SequelizeEagerLoadingError]: comment is not associated to story!
    at story._getIncludedAssociation (C:\Users\kendy\Daily-personal-projects\newsFlow-backend\node_modules\sequelize\lib\model.js:565:13)
     
but I have already take the necessary steps to established the relationship like follows:

const Comment = require("./Comment");
const Save = require("./Save");
const Story = require("./Story");
const User = require("./User");

User.hasMany(Save);
Save.belongsTo(User);

User.hasMany(Story);
Story.belongsTo(User);

User.hasMany(Comment);
Comment.belongsTo(User);

Comment.belongsTo(Story, { foreignKey: "commentId" });
Story.hasMany(Comment, { foreignKey: "storyId" });

I wonder if the error occurs because the comment belongs to both the User and the Story or a problem with sequelize not supporting the relationship how I have defined it! Well I would really appreciate your help on this. Thanks!

**Comment by ephys** [comment]
I'm closing as we don't have a reproducible example and the issue template was not followed, but the likely reason is that your association code is not being run by the time you run the query
