### ISSUE TITLE
Incorrect types for default in findOrCreate and findOrBuild

### ISSUE THREAD

**Issue by MaksymAleieiv** [sequelize/sequelize#16947]
## Bug Description

Model.findOrCreate and Model.findOrBuild incorrectly has the type `TCreationAttributes` when it should be `Partial<TCreationAttributes>` this results in a type error when not passing all fields defined in model (id, createdAt or any other field).

### Reproducible Example

![image](https://github.com/sequelize/sequelize/assets/89811231/099c0e62-5851-478d-8f9c-5085dcaaca7c)

![image](https://github.com/sequelize/sequelize/assets/89811231/fe0468b7-3b16-4399-9835-a1b7c0122872)

### What do you expect to happen?

Do not require all fields to be present in `defaults` object, especially those auto-generated by sequalize (id, createdAt, etc).

### What is actually happening?

It requires all fields to be present in `defaults` object, even those auto-generated by sequalize (id, createdAt, etc).

### Environment

- Sequelize version: 6.35.2
- Node.js version: 20.10.0
- If TypeScript related: TypeScript version: 5.3.2
- Database & Version:  Postgresql 16
- Connector library & Version: pg 8.11.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
I can't reproduce a bug here. `findOrBuild`'s default requires all mandatory fields. The following code does not emit an error:

```ts
export class User extends Model<
  InferAttributes<User>,
  InferCreationAttributes<User>
> {
  declare firstName: string;
  declare lastName: CreationOptional<string | null>;
}

User.findOrBuild({
  defaults: {
    firstName: 'Smith',
  },
});
```

While this one does, because it's missing `firstName` which is mandatory

```ts
User.findOrBuild({
  defaults: {
    lastName: 'Smith',
  },
});
```

You may have an error in your creation attribute declaration

**Comment by MaksymAleieiv** [comment]
Yeah I ~~might be retarted~~ have an error in my types, didn't know about `CreationOptional` existence (:
Sorry for wasting your time and thank you for your help!
