### ISSUE TITLE
Centralize Error Handling In Sequelize

### ISSUE THREAD

**Issue by waqas1991** [sequelize/sequelize#1707]
Hi,
I have develop complete website by using sequelize. The only issue I am facing is Error Handling.
Currently I am handling error by defining .error on each query and its working fine, later I realize that I should email those error to my self instead of just printing in log and there are almost 200+ sequalize queries.
One thing I can do is to call my email method inside each error  block of my query or if there is anyway to handle sequalize error globally so it can reduce my efforts.
Any help would be appreciated

Waqas Ahmed

**Comment by danpaz** [comment]
I don't know how or if this can be accomplished within the sequelize library, but I would like to +1 this because having a central place to catch and log database errors would be just primo. For example, I want to log every time there is a db connection error, without having to explicitly `catch` on every promise. For instance, maybe could hook into the [connection](https://github.com/sequelize/sequelize/blob/2c4a9f3cf9887fb33c31e397e758dd4aa3374d01/lib/dialects/mysql/connection-manager.js#L46), listen to 'error' events on that connection, and bubble them up to a error logging function on the sequelize instance.

Handling uncaught exceptions globally doesn't work here because these rejections *are* being handled, but they seem to just be logged to stderr. 

Any suggestions or guidance on this would be great, thanks!

**Comment by janmeier** [comment]
@danpaz 

`sequelize.query` is used by all queries in sequelize, so perhaps you could overwrite that and attach an error handler: 

 ```js
Sequelize.prototype.query = function () {
  return originalQuery.apply(this, arguments).catch(function (err) {
    // log the error 

    throw err;
  });
};

**Comment by danpaz** [comment]
:+1: This worked great!

**Comment by DanMMX** [comment]
Awesome one @janmeier :+1: was looking for something like this a few hrs ago

**Comment by chickenwing** [comment]
If I put this in my app.js, where does the originalQuery come from?

**Comment by mickhansen** [comment]
@chickenwing That would be the original `sequelize.query`

**Comment by boertel** [comment]
I found that relying on [bluebird global rejection events](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events) caught more exceptions. Monkey patching ```query``` method doesn't catch error like this one: https://github.com/sequelize/sequelize/issues/3273

**Comment by cusspvz** [comment]
In case anyone just wants to copy/paste it:

```js
sequelize.query = async function () {
  try {
    // proxy this call
    return Sequelize.prototype.query.apply(this, arguments)
  } catch ( err ) {
    // handle it with sentry
    sentry(err)

    // rethrow error
    throw err
  }
}
```

**Comment by cusspvz** [comment]
Also, you guys can turn it into a sequelize option, such as `queryErrorHandler`. 😄

**Comment by iamjoyce** [comment]
@cusspvz Thanks! Just to refine,

```
sequelize.query = async function () {
    // proxy this call
    // since `query` is a promise, we can just use promise functions instead of try-catch
    return Sequelize.prototype.query.apply(this, arguments).catch(function (err) {
        // handle it with sentry
        sentry(err);

        // rethrow error
        throw err;
    });
};
```

**Comment by rickyk586** [comment]
```
const orgFindAll = SequelizeModel.findAll;
SequelizeModel.findAll = function(){
	const e = Error('sequelize error');
	return orgFindAll.apply(this, arguments).catch(err => {
		e.sequelizeError = err;
		throw e;
	});
};
const orgCreate = SequelizeModel.create;
SequelizeModel.create = function(){
	const e = Error('sequelize error');
	return orgCreate.apply(this, arguments).catch(err => {
		e.sequelizeError = err;
		throw e;
	});
};
const sequelize = new Sequelize(...);
this.sequelize.query = function(){
	const e = Error('sequelize error');
	return Sequelize.prototype.query.apply(this, arguments).catch(err => {
		e.sequelizeError = err;
		throw e;
	});
};
```

note: creating an Error object each time adds overhead

**Comment by kozakvoj** [comment]
When I override the query function I get an error while creating new persistant instance.

Schema.create({..}) causes:

`TypeError: this.constructor.QueryInterface[query](...).then(...).tap is not a function`

Any ideas?

**Comment by rickyk586** [comment]
@kozakvoj 'tap()' is not a method on native promises which is what gets created when you use 'async'. It should work if you just remove 'async' since the new method returns a Bluebird promise.

**Comment by knoxcard** [comment]
@rickyk586 - thank you so much! I can't believe I finally have this working now, thanks for sharing that code. I ended up with this to fit my platform...

app.js
------------
console.time('Database')
require('./model').connect(app, (db, sequelize) => {
  app.set('model', db)
  app.set('sequelize', sequelize)
  console.timeEnd('Database')
  // continue app logic
})


model.js
```
var exports = {}
exports.connect = (app, cb) => {
  function formatJsonColumns(model) {
    for(let json_key in model.rawAttributes) {
      if(model.rawAttributes[json_key].type.key.toUpperCase() == 'JSON') {
        var obj = app.get('functions').objEscapeDblQuotes(model[json_key]),
          json_val = JSON.stringify(obj, null, app.get('json spaces'))
        json_val = json_val.replace(/\\([\s\S])|(")/g, "\\$1$2")
        json_val = json_val.replace(/'/g, "\\'")
        var raw_sql_string = "UPDATE `" + model.constructor.name + "` SET `" + json_key + "` = \'" + json_val + "\' WHERE id = " + model.id
        app.get('sequelize').query(raw_sql_string).then(([results, metadata]) => {
        })
        // console.log(json_val)
        // console.log('raw sql string: ' + raw_sql_string)
      }
    }
  }
  var Sequelize = require('sequelize'),
    sequelize = new Sequelize(process.env.db_name, process.env.db_user, process.env.db_pass, {
      dialect: 'mariadb',
      dialectOptions: {
        timezone: process.env.db_timezone
      },
      port: process.env.db_port,
      pool: {
        min: 0,
        max: 2,
        idle: 10000
      },
      define: {
        charset: 'utf8mb4',
        timestamps: false,
        hooks: {
          afterCreate: (model, fn) => {
            formatJsonColumns(model)
          },
          afterUpdate: (model, fn) => {
            formatJsonColumns(model)
          }
        }
      },
      benchmark: false,
      logging: false
    })
  function dbError(err) {
      console.log('sequelize err...')
      process.exit(0)
  }
  const SequelizeModel = require('sequelize/lib/model'),
    orgFindAll = SequelizeModel.findAll
  SequelizeModel.findAll = function() {
    return orgFindAll.apply(this, arguments).catch(err => {
      dbError(err)
    })
  }
  const orgCreate = SequelizeModel.create
  SequelizeModel.create = function() {
    return orgCreate.apply(this, arguments).catch(err => {
      dbError(err)
    })
  }
  sequelize.query = function() {
    return Sequelize.prototype.query.apply(this, arguments).catch(err => {
      dbError(err)
    })
  }
  sequelize.authenticate().then(() => {
    var db = {}
    require('fs').readdirSync('./models').filter(model => {
      return model.slice(-3) === '.js'
    }).forEach(model => {
      var model = require('./models/' + model)(sequelize, Sequelize, app)
      db[model.name] = model
      if(db[model.name].associate)
        db[model.name].associate(db)
    })
    sequelize.sync().then(() => {
      db.cities.preload(() => {
        cb(db, sequelize)
      })
    })
  }).catch(err => {
    console.error('Unable to connect to the database:', err)
  })
}
module.exports = exports

```

**Comment by axusmark** [comment]
https://medium.com/@vapurrmaid/separating-concerns-by-using-errorr-handling-a-case-study-with-sequelize-transactions-64434ef98b3a

**Comment by datis-01** [comment]
I'm trying to intercept SequelizeValidationError messages to send "lighter" errors to client, but nothing in the 

> Sequelize.prototype.query.apply

 runs : 

`sequelize.query = function () {
  return Sequelize.prototype.query.apply(this, arguments).catch(err => {
    var messages = [];
    if (err instanceof ValidationError) {
      err.errors.forEach((error) => {
        var message;
        switch (error.validatorKey) {
          case 'isEmail':
            message = error.path + ': please enter a valid email';
            break;
          case 'is_null':
            message = error.path + ': this field is required';
            break;
          // ...
        }
        messages.push(message);
      });
      err = messages;
    }
  })
}`

**Comment by hwkim94** [comment]
How could I do this in Typescript? When I try to above solutions, I faced below error

```typescript
import { Sequelize, QueryOptions, QueryOptionsWithType, QueryTypes } from 'sequelize';
import config from '../config';
import { MysqlFailedError } from '../lib/error';

const createSequelize = (database: string): Sequelize => {
  const sequelize = new Sequelize(database, config.db.user, config.db.password, {
    host: config.db.host,
    port: config.db.port,
    dialect: 'mysql',
    typeValidation: true,
    timezone: '+09:00',
    logging: false,
    define: {
      freezeTableName: true,
      timestamps: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
    pool: {
      max: config.db.pool,
      min: 5,
      acquire: 30000,
    },
    retry: {
      max: 0,
    },
  });

  sequelize.query = async (
    sql: string | { query: string; values: unknown[] },
    options?: QueryOptions | QueryOptionsWithType<QueryTypes.RAW> | undefined,
  ) => {
    try {
      return Sequelize.prototype.query.apply(this, [sql, options]);
    } catch (err: any) {
      throw new MysqlFailedError(err);
    }
  };

  return sequelize;
};
```

```
Type '(sql: string | {    query: string;    values: unknown[];}, options?: QueryOptions | QueryOptionsWithType<QueryTypes.RAW> | undefined) => Promise<[unknown[], unknown]>' is not assignable to type '{ (sql: string | { query: string; values: unknown[]; }, options: QueryOptionsWithType<QueryTypes.UPDATE>): Promise<[undefined, number]>; (sql: string | { ...; }, options: QueryOptionsWithType<...>): Promise<...>; (sql: string | { ...; }, options: QueryOptionsWithType<...>): Promise<...>; (sql: string | { ...; }, opt...'.
  Type 'Promise<[unknown[], unknown]>' is not assignable to type 'Promise<[undefined, number]>'.
    Type '[unknown[], unknown]' is not assignable to type '[undefined, number]'.
      Type at position 0 in source is not compatible with type at position 0 in target.
        Type 'unknown[]' is not assignable to type 'undefined'.ts(2322)
```


![image](https://user-images.githubusercontent.com/33803262/128612489-03249294-92d9-43b4-9b08-66cec9a0f7d1.png)
