### ISSUE TITLE
Problems referencing associated query conditions that are not primary key fields | BUG!

### ISSUE THREAD

**Issue by JeffreyCheungGit** [sequelize/sequelize#17125]
### Problems referencing associated query conditions that are not primary key fields | BUG!
引用非主键字段的关联查询条件时出现问题！

e.g：
`
   // 账号表模型
  const Account = sequelize.define('account', {
        pk: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
            comment: '主键'
        },
        userId: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            comment: '用户ID'
        }
     }, {
       indexes: [{
            unique: true,
            fields: ['userId']
        }]
    })

  // 角色表模型
  const Role = sequelize.define('account', {
        pk: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
            comment: '主键'
        },
        roleId: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            comment: '角色ID'
        }
     }, {
       indexes: [{
            unique: true,
            fields: ['roleId']
        }]
    })

   // 账号与角色的关联表
  const RoleConfig = sequelize.define('account', {
        pk: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
            comment: '主键'
        },
        roleId: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            comment: '角色ID'
        },
        userId: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            comment: '用户ID'
        }
     })

     // 角色表与账号表用联结表关联
    RoleConfig.associate = function () {
        Account.belongsToMany(Role, {
            through: RoleConfig,
            sourceKey: 'userId',
            targetKey: 'roleId',
            foreignKey: 'userId'
        })
        Role.belongsToMany(Account, {
            through: RoleConfig,
            sourceKey: 'roleId',
            targetKey: 'userId',
            foreignKey: 'roleId'
        })
   }
        

// 查询账号表并查询关联角色数据，根据角色ID查询条件有效过滤  required: true
const result = await Account.findAndCountAll({
   include: [
      {
            model: Role,
            required: true,
            through: {
                where: {
                    roleId: 1
               }
           }
      }
   ]
})
`
role表中roleId=1数据存在，并在关联表中有与账号的关联关系

// 或者  where: {}  条件查不出数据

//查询结果：
{count: 4, rows: Array(0)}

无法查询出数据，但是统计数是对的。

检查SQL语句，出现以下条件导致查询不出数据：
 AND ( SELECT `roleConfig`.`pk` FROM `roleConfig` AS `roleConfig` INNER JOIN `role` AS `role` ON `roleConfig`.`roleId` = `role`.`pk` WHERE (`account`.`pk` = `roleConfig`.`userId`) LIMIT 1 )

这个好像没有问题：
 INNER JOIN ( `roleConfig` AS `roles->roleConfig` INNER JOIN `role` AS `roles` ON `roles`.`roleId` = `roles->roleConfig`.`roleId`) ON `account`.`userId` = `roles->roleConfig`.`userId`

以下是全部的SQL语句：
SELECT `account`.*, `company`.`pk` AS `company.pk`, `company`.`companyId` AS `company.companyId`, `company`.`companyName` AS `company.companyName`, `company`.`unifiedSocialCreditID` AS `company.unifiedSocialCreditID`, `company`.`enterpriseAddress` AS `company.enterpriseAddress`, `company`.`account` AS `company.account`, `company`.`password` AS `company.password`, `company`.`landlineNumber` AS `company.landlineNumber`, `company`.`menuStrictly` AS `company.menuStrictly`, `company`.`locale` AS `company.locale`, `company`.`expireDate` AS `company.expireDate`, `company`.`status` AS `company.status`, `company`.`remark` AS `company.remark`, `company`.`createdAt` AS `company.createdAt`, `company`.`updatedAt` AS `company.updatedAt`, `roles`.`pk` AS `roles.pk`, `roles`.`companyId` AS `roles.companyId`, `roles`.`roleId` AS `roles.roleId`, `roles`.`roleName` AS `roles.roleName`, `roles`.`authScope` AS `roles.authScope`, `roles`.`menuStrictly` AS `roles.menuStrictly`, `roles`.`orgStrictly` AS `roles.orgStrictly`, `roles`.`status` AS `roles.status`, `roles`.`remark` AS `roles.remark`, `roles`.`createdAt` AS `roles.createdAt`, `roles`.`updatedAt` AS `roles.updatedAt`, `roles->roleConfig`.`pk` AS `roles.roleConfig.pk`, `roles->roleConfig`.`companyId` AS `roles.roleConfig.companyId`, `roles->roleConfig`.`roleId` AS `roles.roleConfig.roleId`, `roles->roleConfig`.`userId` AS `roles.roleConfig.userId`, `roles->roleConfig`.`createdAt` AS `roles.roleConfig.createdAt`, `roles->roleConfig`.`updatedAt` AS `roles.roleConfig.updatedAt` FROM (SELECT `account`.`pk`, `account`.`companyId`, `account`.`organizationalId`, `account`.`userId`, `account`.`account`, `account`.`password`, `account`.`userName`, `account`.`mobilePhone`, `account`.`email`, `account`.`locale`, `account`.`status`, `account`.`remark`, `account`.`createdAt`, `account`.`updatedAt`, `organizational`.`pk` AS `organizational.pk`, `organizational`.`companyId` AS `organizational.companyId`, `organizational`.`parentId` AS `organizational.parentId`, `organizational`.`organizationalId` AS `organizational.organizationalId`, `organizational`.`organizationalName` AS `organizational.organizationalName`, `organizational`.`organizationalType` AS `organizational.organizationalType`, `organizational`.`remark` AS `organizational.remark`, `organizational`.`createdAt` AS `organizational.createdAt`, `organizational`.`updatedAt` AS `organizational.updatedAt` FROM `account` AS `account` INNER JOIN `organizational` AS `organizational` ON `account`.`organizationalId` = `organizational`.`organizationalId` WHERE `account`.`companyId` = 1 AND ( SELECT `roleConfig`.`pk` FROM `roleConfig` AS `roleConfig` INNER JOIN `role` AS `role` ON `roleConfig`.`roleId` = `role`.`pk` WHERE (`account`.`pk` = `roleConfig`.`userId`) LIMIT 1 ) IS NOT NULL ORDER BY `account`.`updatedAt` DESC LIMIT 0, 50) AS `account` LEFT OUTER JOIN `company` AS `company` ON `account`.`companyId` = `company`.`companyId` INNER JOIN ( `roleConfig` AS `roles->roleConfig` INNER JOIN `role` AS `roles` ON `roles`.`roleId` = `roles->roleConfig`.`roleId`) ON `account`.`userId` = `roles->roleConfig`.`userId` ORDER BY `account`.`updatedAt` DESC;

自动添加了账号表的pk等于关联表的userId进行约束，这是为什么？
就算加了constraints: false取消约束，这个条件也会存在

这是BUG？

还是我的书写方式有问题？

有没有大神遇到相同问题已解决的？可以通过关联表的另一个模型进行过滤主表数据

谢谢！

**Comment by JeffreyCheungGit** [comment]
联表查询添加以下参数使用右查询，可以查出数据，但是会导致查询的数据与统计数对不上，有些记录的字段值都是null
`include = [
     model: Role,
    required: false,
   right: true,
   where: {}
]`

**Comment by ephys** [comment]
Sorry but the issue you opened is not readable. Please follow the issue template when opening a bug report, use markdown to format it properly, and use https://github.com/sequelize/sequelize/discussions if you're looking for help for something that is not a bug

If you're at ease with it, prefer posting your comments in English. If not, please include a machine translation into English next to the original text

You can ping us once the issues are resolved to re-open the issue
