### ISSUE TITLE
Cyclic dependency checker should consider different 'as' parameter

### ISSUE THREAD

**Issue by mlegenhausen** [sequelize/sequelize#1717]
I have following example:

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('sequelize-test', 'root', '');
var Content = sequelize.define('Content', {});
var Version = sequelize.define('Version', {});

Content.hasMany(Version);
Version.belongsTo(Content);

Content.belongsTo(Version, {
    as: 'ReleaseVersion',
    foreignKey: 'ReleaseVersionId'
});

Version.hasOne(Content, {
    as: 'ReleaseVersion',
    foreignKey: 'ReleaseVersionId'
});

sequelize.sync({ force: true });
```

Which produces following error:

```
Error: Cyclic dependency found. 'Contents' is dependent of itself.
Dependency Chain: Contents -> Versions => Contents
```

I want to associate the active release of a content by the `Content` model, for this I added a new association that links directly to my `Version` model. The key for this id (ReleaseVersionId) should be in the `Content` Table. This key can be null if no version was released. Since Version 2.0.0-dev11 I get an error when constructing something like this. Do I miss something or can I model something like this in a sequelize way?

**Comment by asimsohail** [comment]
@janmeier.. can you show how to manually add the keys after `.sync` is complete?

**Comment by janmeier** [comment]
@asimsohail Add them manually either using phpmyadmin/pgadmin whatever or by writing the query

**Comment by bottleofwater** [comment]
@janmeier Couldn't Sequelize first create the tables without the foreign keys, then add all the foreign keys right after?

**Comment by mickhansen** [comment]
@bottleofwater that could work

**Comment by Znarkus** [comment]
Is `constraints: false` and adding keys after `.sync` the canonical way of doing cyclic database structures?

Table structure:

```
template
- id
- category_id

category
- id
- default_template_id
```

**Comment by ralusek** [comment]
@mickhansen Is this currently in development?

**Comment by marc-ferrer** [comment]
I know this is an old issue, but why does not `allowNull: true` on the foreign key parameter make this work?

**Comment by jasonbodily** [comment]
Yes old issue, but it doesn't appear to work. With above, is this currently available?

**Comment by gzurbach** [comment]
@jasonbodily it's `constraints: false` (with an `s`)... spent a few minutes figuring that out :)

**Comment by jasonbodily** [comment]
@gzurbach - Sorry about that! Updated my answer!

**Comment by mentos1386** [comment]
@jasonbodily You have a typo, `constrainst: false` should be `constraints: false` (`ts` at the end`)

**Comment by petersg83** [comment]
Same problem here.
More than 2 years this issue has been opened :)
I'll add `contraints: false` but it hurts my heart :'(

**Comment by JQuezada0** [comment]
Was this ever resolved?

**Comment by xaiyeon** [comment]
Aw man and here I thought this was solved... Just ran into this issue, but I have over 15 tables with hasMany relationships :( I will try them without and query right after migration then, but how do I call a migration file to be executed after .sync().then((function{}))?

**Comment by semy** [comment]
Any news on this? :-(

**Comment by contra** [comment]
Can we get this issue reopened so somebody can potentially send a PR for this?

**Comment by contra** [comment]
@sushantdhiman 	Thanks!

**Comment by petrovi4** [comment]
@sushantdhiman Is this in development now?

**Comment by LFabre** [comment]
Any news?

**Comment by papb** [comment]
@LFabre and others - none that I know of. PR is welcome.

**Comment by esyeng** [comment]
Any news? :-(

**Comment by ephys** [comment]
I'll close. Starting with Sequelize 6.20.0, if there is a cyclic foreign key, `sync` will first create the tables without foreign key constrants, then add them.
This change should resolve this issue.
