### ISSUE TITLE
The Lengthy Integer is getting converted to decimal even when DataTypes.STRING is Specified

### ISSUE THREAD

**Issue by Veekshak** [sequelize/sequelize#17185]
I am Passing these arguments 
{
      "id": 132,
      "name": "Rajesh Dinesh",
      "address": "Bengaluru",
      "phone_number": 9843894787,
      "date":"14/03/2012",
      "father_name": "Meow Billa",
      "cur_state": "member",
      "dir": "Praveen"
}
to the` const member = await Members.create(data)` function

The Output of phone_number will automatically have a decimal 

[{
        "id": 132,
        "name": "Rajesh Dinesh",
        "address": "Bengaluru",
        "phone_number": "9843894787.0",
        "father_name": "Meow Billa",
        "date": "14/03/2012",
        "cur_state": "member",
        "dir": "Praveen",
        "createdAt": "2024-03-20T13:36:56.675Z",
        "updatedAt": "2024-03-20T13:36:56.675Z"
    }]

**Here is the model**
const Members = sequelize.define("Members", {
  id: {
    type: DataTypes.INTEGER,
    allowNull: false,
    primaryKey: true,
    unique: true,
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  address: {
    type: DataTypes.STRING,
  },
  phone_number: {
    type: DataTypes.STRING,
    allowNull:false
  },
  father_name: {
    type: DataTypes.STRING,
  },
  date: {
    type: DataTypes.STRING,
  },
  cur_state: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  dir: {
    type: DataTypes.STRING,
  },
});

**Comment by ephys** [comment]
Hi! We get a lot of issues, which takes a lot of time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

As indicated in the issue template, issues that do not follow the template may be closed.
You can edit this issue and ping us, and we will re-review and re-open this issue (there is no need to create a new issue, editing this one is enough).
