### ISSUE TITLE
sql.trim() fatal error

### ISSUE THREAD

**Issue by redechidna** [sequelize/sequelize#17232]
## Bug Description

```shell
/project/node_modules/sequelize/lib/sequelize.js:583
sql = sql.trim();
          ^
TypeError: Cannot read properties of undefined (reading 'trim')
``` 
Sometimes our server crashes with this error. And this project doesn't use "sequelize.query" to execute SQL from string

### What do you expect to happen?

Something like this. If "sql" value is not valid - just stop further execution without any messages
```javascript
try {
    sql = sql.trim();
} catch () {
    return
}
``` 

### What is actually happening?

I repeated all users actions from SQL log history. Everything works as it should without crashes. The issue happens suddenly. Each time users do different actions. And at some moment the server crashes with this error.

### Environment

- Sequelize version: 6.11.0
- Node.js version: 16.16.0
- If TypeScript related: TypeScript version: 4.5.2
- Database & Version: mysql 5.7
- Connector library & Version:

## Would you be willing to resolve this issue by submitting a Pull Request?

Yes, I have the time and I know how to start.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by WikiRik** [comment]
See my comment on the PR.

**Comment by redechidna** [comment]
Can't reproduce for now. This is the only piece of stacktrace I have. Old docker data were removed to clear space so we could restart the server again. Will reopen if I get the error again. Will try to update all packages
