### ISSUE TITLE
Can't make table queries. TypeError: _.includes is not a function

### ISSUE THREAD

**Issue by s1nistr4** [sequelize/sequelize#17282]
As of now, you can't run a query in Sequelize because of the following error:

```
TypeError: _.includes is not a function
```

The code used: 
```
        const PassportQuery = await Passport.findOne({
            where: {
                Email: Body.Email, // email string from a fastify request body, like "myemail@gmail.com",
            },
        })

```

**Comment by ephys** [comment]
Hi! We get a lot of issues, which takes a lot of time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

As indicated in the issue template, issues that do not follow the template may be closed.
You can edit this issue and ping us, and we will re-review and re-open this issue (there is no need to create a new issue, editing this one is enough).
