### ISSUE TITLE
使用webpack5 打包 后报错 TypeError: i is not a function

### ISSUE THREAD

**Issue by guanzhongxu** [sequelize/sequelize#17311]
使用webpack5 打包node 项目， 
sequelize配置如下
import { Sequelize } from "sequelize";
import mysql from "mysql2";
const db = new Sequelize("fuwujia", "root", "xxxxxx", {
	host: "localhost",
	dialect: "mysql",
	dialectModule: mysql,
	logging: false,
	define: {
		createdAt: true,
		updatedAt: true,
		paranoid: true,
		freezeTableName: true,
		timestamps: true
	}
});
export default db;
打包完成以后，，将把包之后的js 放在一个空白的文件夹中 运行 后报错TypeError: i is not a function
webpack配置文件如下：
import { join } from "path";
import * as webpack from "webpack";
import Dotenv from "dotenv-webpack";

const config: webpack.Configuration = {
	mode: "production",
	entry: join(__dirname, "src", "index.ts"),
	output: {
		path: join(__dirname, "dist"),
		filename: "index.js"
	},
	target: "node",
	node: {
		global: true,
		__filename: true,
		__dirname: true
	},
	// devtool: "source-map",
	resolve: {
		extensions: [".tsx", ".ts", ".js"],
		alias: {
			".js": [".js", ".ts"],
			".cjs": [".cjs", ".cts"],
			".mjs": [".mjs", ".mts"],
			mysql2: require.resolve("mysql2")
		}
	},
	module: {
		rules: [
			{
				test: /\.([cm]?ts|tsx)$/,
				loader: "ts-loader",
				exclude: "/node_modules/"
			}
		]
	},
	plugins: [new Dotenv()],
	stats: {
		errorDetails: true
	}
};
export default config;

**Comment by buaayoung** [comment]
plugins: [
    new webpack.ProvidePlugin({
      Sequelize: 'sequelize',
    }),
  ],
  optimization: {
    minimize: true,
    minimizer: [new TerserPlugin({
      terserOptions: {
        keep_fnames: true,
      },
    })],
    usedExports: false,
  }

try it!

**Comment by guanzhongxu** [comment]
依然报错。
报错信息如下：
Error: Please install mysql2 package manually

**Comment by ephys** [comment]
Hi! We get a lot of issues, which takes a lot of time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

As indicated in the issue template, issues that do not follow the template may be closed.
You can edit this issue and ping us, and we will re-review and re-open this issue (there is no need to create a new issue, editing this one is enough).

---

If this is not about a bug report or a feature request, prefer instead:

- StackOverflow: https://stackoverflow.com/questions/tagged/sequelize.js
- GitHub discussions: https://github.com/sequelize/sequelize/discussions (let us know and we'll convert this issue into a discussion)
- Slack: https://sequelize-slack.herokuapp.com/
