### ISSUE TITLE
underscored doesn't also apply to table names

### ISSUE THREAD

**Issue by wbyoung** [sequelize/sequelize#1733]
I was a little surprised to find that `underscored` didn't apply to table names as well.

This is especially annoying on PostgreSQL where it [converts unquoted identifiers to lowercase](http://stackoverflow.com/a/7910264/98069) making you have to quote table names.

Any chance of chaining this (or adding another option to handle it)?

**Comment by Harulla** [comment]
> Applying `underscored` to model names to generate tablenames at this point would probably break loads.
> 
> What you can do is:
> 
> ```js
> sequelize.define('modelName', {
>   // attributes
> }, {
>   // options
>   tableName: 'my_underscored_table'
> })
> ```

Merci chef.
