### ISSUE TITLE
HSTORE columns not parsed in associated models when retrieved via include

### ISSUE THREAD

**Issue by jseppi** [sequelize/sequelize#1737]
Example: 

For models Photo and Tag, which are related Many-to-Many, and where Photo has an HSTORE field, a query like:
```js
Tag.find({where: {id: tagId}, include: [Photo]}).success(function(tag) {
  //tag.photos will not have their HSTORE fields parsed
});
```
will not properly deserialize the HSTORE field in the associated Photos.

Getting the associated Photos in a separate query will have the HSTORE fields parsed:
```js
Tag.find(tagId).success(function(tag) {
  tag.getPhotos().success(function(photos) {
    //photos will have their HSTORE fields parsed
  });
});
```

**Comment by BridgeAR** [comment]
This is already fixed and there is a test for this existent.
Ping @mickhansen @janmeier

**Comment by janmeier** [comment]
Sweet, closing immediately then - thanks @BridgeAR  :)
