### ISSUE TITLE
Migration logic for deploying everywhere

### ISSUE THREAD

**Issue by golergka** [sequelize/sequelize#1748]
I want to be able to easily deploy my app both to server where it resides for a long time already, or to a completely new server — for example, for unit tests. Or, since I want to create unit tests to test the mgirations themselves too, to a server in a state before certain migration.

Right now in my app all migrations are automatically run on startup, which is perfect for deploying to production, but it creates problems with deploying to an empty database.

Since all migrations are marked with timestamps, may be Sequelize could somehow remember when particular database was created and automatically run only migrations that were created after that date?

**Comment by janmeier** [comment]
Migration issues belong is sequelize/cli and sequelize/umzug
