### ISSUE TITLE
Unable to Connect to Supabase PostgreSQL via Sequelize: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing

### ISSUE THREAD

**Issue by ryzxxn** [sequelize/sequelize#17492]
I’m using Sequelize to connect to various PostgreSQL databases. The connection works for some instances but fails when trying to connect to Supabase with the following connection string:

```postgresql://postgres.zzoqmftgxxbtuztxklxi:[PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
```

I receive the following error:
```
Unable to connect to the database: SequelizeConnectionError: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
```

Steps to Reproduce:
Code: Here is the Sequelize instance creation code I'm using:
```
const { Sequelize } = require('sequelize');

function createSequelizeInstance(connectionURI) {
  return new Sequelize(connectionURI, {
    dialect: 'postgres',
    dialectOptions: {
      ssl: {
        require: true,
        rejectUnauthorized: false,  // Tried both true and false here
      },
    },
  });
}
```
Working connectionUri:
```
postgresql://vmkathe:[PASSWORD]@ep-damp-sun-a1vvdcup-pooler.ap-southeast-1.aws.neon.tech/anyname?sslmode=require
```
this db  is provided by NeonDb

Expected Behavior:
Sequelize should successfully authenticate with Supabase PostgreSQL using the provided connection string.

Actual Behavior:
Authentication fails with the error SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing.

Questions:
Is there any specific configuration required to authenticate with Supabase PostgreSQL when using Sequelize?
Is this error related to Supabase’s authentication mechanism, or is it a bug/limitation in Sequelize’s handling of SASL/SCRAM authentication?

Any guidance on how to resolve this issue would be greatly appreciated.

**Comment by olnov** [comment]
I was able to connect successfully to both services - NeonDB (PG 16) and Supabase (PG 15.6) using this:

const sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_USER, process.env.DB_PASSWORD, {
  host: process.env.DB_HOST,
  port: process.env.DB_PORT,
  dialect: process.env.DB_DIALECT,
  dialectOptions: {
    ssl: {
      require: true,
      rejectUnauthorized: false
    }
  },
  logging: false
});

Packages:
pg-hstore@2.3.4
pg@8.12.0
sequelize@6.37.3

**Comment by ephys** [comment]
I'll close as it seems the problem has been resolved in https://github.com/supabase/supabase/issues/29257
