### ISSUE TITLE
Feature request: Support for hierarchies

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#1751]
I would like to propose an addition to the API.

At present, if you have a tree structure of nested folders, you can represent that:

```
Folder.hasMany( Folder, { as: 'Childs', foreignKey: 'parentId' } )
Folder.belongsTo( Folder, { as: 'Parent', foreignKey: 'parentId' } )
```

However, to retrieve an entire nested hierarchy requires multiple queries to traverse each folder and iteratively fetch their children. It would be useful if you could do this in a single query.

How about this?

```
Folder.hasMany( Folder, { as: 'Childs', foreignKey: 'parentId', hierarchy: true } )
Folder.belongsTo( Folder, { as: 'Parent', foreignKey: 'parentId', hierarchy: true } )
```

Setting `hierarchy` to `true` would do the following:
- Add a field `hierarchyLevel` to the Folder model indicating how deeply nested in the tree the item is
- Create a many-to-many association between Folder and Folder via a through table `FolderHierarchy` representing a Folder's link to all it's ancestors and descendents
- Add methods on Folder instances `getChildDescendents` and `getParentAncestors`
- Allow `Folder.findAll( { include: [ { model: Folder, as: 'ChildDescendents' } ] } )` and `Folder.findAll( { include: [ { model: Folder, as: 'ParentAncestors' } ] } )` to retrieve all parents/parent's parents/parent's parent's parents or children/children's children/ children's children's children - all in one go
- For `findAll( ... ChildDescendents )`, would present the returned Descendents in a nested tree structure
- Update Folder.hierarchyLevel and records in FolderHierarchy automatically whenever a Folder is created, deleted or updated

This would allow retrieval of an entire hierarchy in a single query, and for the tree structure to be transparently maintained without any further user code.

The obvious use cases are:
- displaying a tree structure such as nested folders
- a nested tagging system where you want to say to Sequelize "give me all the articles about sport, including all the articles in sub-categories of sport and their sub-categories"

NB: the names of the FolderHierarchy table, hierarchyLevel attribute, and all the accessors etc would be customisable - by providing `hierarchy: { ... }` options instead of `hierarchy: true` in the `hasMany()` call that initialises the hierarchy.

An example:

```
// set up table
var Folder = sequelize.define( 'Folder', { name: Sequelize.STRING } )

// set up association
Folder.hasMany( Folder, { as: 'Childs', foreignKey: 'parentId', hierarchy: true } )
Folder.belongsTo( Folder, { as: 'Parent', foreignKey: 'parentId', hierarchy: true } )

// sync
sequelize.sync(). ...

// create folders
Folder.create( { name: 'root', parentId: null } ). ... // id: 1
Folder.create( { name: 'root.a', parentId: 1 } ). ... // id: 2
Folder.create( { name: 'root.b', parentId: 1 } ). ... // id: 3
Folder.create( { name: 'root.b.c', parentId: 3 } ). ... // id: 4

// query data
Folder.findAll( { where: { id: 4 }, include: [ { model: Folder, as: 'ParentAncestors' } ] } ). ...
/* returns {
  id: 4,
  name: 'root.b.c',
  hierarchyLevel: 4,
  parentAncestors: [
    { id: 2, name: 'root.b', hierarchyLevel: 2 },
    { id: 1, name: 'root', hierarchyLevel: 1 }
  ]
} */

Folder.findAll( { where: { id: 1 }, include: [ { model: Folder, as: 'ChildDescendents', hierarchy: true } ] } ). ...
/* returns {
  id: 1,
  name: 'root',
  hierarchyLevel: 1,
  childDescendents: [
    { id: 2, name: 'root.a', hierarchyLevel: 2 },
    { id: 3, name: 'root.b', hierarchyLevel: 2, childDescendents: [
      { id: 4, name: 'root.b.c', hierarchyLevel: 3 }
    ] }
  ]
} */
```

The data created in the tables by the example above would be:

Folder:

id | name | parentId | hierarchyLevel
-- | ---- | -------- | --------------
1 | root | null | 1
2 | root.a | 1 | 2
3 | root.b | 1 | 2
4 | root.b.c | 3 | 3

FolderHierarchy:

folderId | ancestorId
2 | 1
3 | 1
4 | 1
4 | 3

So, what do you think?

I need this for a project I'm working on, so happy to write the code. Just want to make sure it'd be welcome in Sequelize before I proceed.

**Comment by diosney** [comment]
+1 Very useful. It would be nice to have nested hierarchies in the core, I agree too that is a common pattern out there.

**Comment by overlookmotel** [comment]
@diosney You can use my sequelize plugin for this https://www.npmjs.com/package/sequelize-hierarchy

**Comment by diosney** [comment]
@overlookmotel Yeah sure, I'm testing it right now and so far so good :smile: Thanks!
