### ISSUE TITLE
Sequelize timeout error

### ISSUE THREAD

**Issue by arunkumarbm408** [sequelize/sequelize#17573]
I am trying to connect the nodejs to sequelize but in development after inserting some data into multiple child tables i am getting like this and also the error message is "too many connections" can you help me out this.

**Comment by ephys** [comment]
Hi! We get a lot of issues, which takes a lot of time to process.
For this reason, we have to ask you to fill-in the [issue template](https://raw.githubusercontent.com/sequelize/sequelize/main/.github/ISSUE_TEMPLATE/bug_report.md). The most important part being to provide a [SSCCE](https://github.com/sequelize/sequelize-sscce) that replicates your issue.

As indicated in the issue template, issues that do not follow the template may be closed.
You can edit this issue and ping us, and we will re-review and re-open this issue (there is no need to create a new issue, editing this one is enough).

---

If this is not about a bug report or a feature request, prefer instead:

- StackOverflow: https://stackoverflow.com/questions/tagged/sequelize.js
- GitHub discussions: https://github.com/sequelize/sequelize/discussions (let us know and we'll convert this issue into a discussion)
- Slack: https://sequelize-slack.herokuapp.com/
