### ISSUE TITLE
MS SQL showIndex for non-dbo schema failure patch.

### ISSUE THREAD

**Issue by tisdadd** [sequelize/sequelize#17571]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `sequelize@6.37.4` for the project I'm working on.

Basically, `sequelize.getQueryInterface().showIndex('nonDbo.tableName')` was failing. I am testing against the [World Wide Importers sample database](https://learn.microsoft.com/en-us/sql/samples/wide-world-importers-what-is?view=sql-server-ver16) and was using the table `Sales.Customers`.  Both `describeTable` and `getForeignKeyReferencesForTable` work with the `schema` option passed in, and do similar types of things.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/sequelize/lib/dialects/mssql/query-generator.js b/node_modules/sequelize/lib/dialects/mssql/query-generator.js
index 5dbf624..e384a63 100644
--- a/node_modules/sequelize/lib/dialects/mssql/query-generator.js
+++ b/node_modules/sequelize/lib/dialects/mssql/query-generator.js
@@ -467,7 +467,13 @@ class MSSQLQueryGenerator extends AbstractQueryGenerator {
     ]);
   }
   showIndexesQuery(tableName) {    
-    return `EXEC sys.sp_helpindex @objname = N'${this.quoteTable(tableName)}';`;
+    const splitTableName = tableName.split('.');
+    for(let i = 0; i < splitTableName.length; i++)
+    {
+      splitTableName[i] = this.quoteTable(splitTableName[i]);
+    }
+    
+    return `EXEC sys.sp_helpindex @objname = N'${splitTableName.join('.')}';`;
   }
   showConstraintsQuery(tableName) {
     return `EXEC sp_helpconstraint @objname = ${this.escape(this.quoteTable(tableName))};`;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Thanks so much for your time and effort here. I did see the v6 was pushed through after disabling MS SQL tests it looked like, so figured I can hopefully help with one of the bugs.

**Comment by WikiRik** [comment]
I believe this issue has been fixed on the v7 alphas a while back already. I also believe we've considered this a breaking change since people might have added workarounds for this, so I don't think we'll backport this to v6.
If this is still an issue on the [latest v7 alpha](https://www.npmjs.com/package/@sequelize/core) (alpha 43 at the time of writing), we would for sure be open to fixing this.

---

> Thanks so much for your time and effort here. I did see the v6 was pushed through after disabling MS SQL tests it looked like, so figured I can hopefully help with one of the bugs.

That's partially true. It's only the MSSQL 2019 tests that are disabled on v6 due to a CI issue. We are still running the tests that we have.

**Comment by tisdadd** [comment]
Thanks much, just had read the comments. I will close this out then, leaving it just for reference for others in v6.
