### ISSUE TITLE
BIGINT is returned as String

### ISSUE THREAD

**Issue by bluecenter** [sequelize/sequelize#1774]
a column type is set to BIGINT, however the type of attribute is string after retrieved from DB. If the column type is integer/float, the type of attribute is number which is correct.

**Comment by Gerhardk** [comment]
Sorry to necro-post, but I just had the same problem and adding the above line of code _before_ initializing sequelize and it solved the problem.

Like this:
```coffeescript
require('pg').defaults.parseInt8 = true # before the following are called
# ...
Sequelize = require 'sequelize'
sequelize = new Sequelize config.database, config.username, config.password, config
```

**Comment by ErikvdVen** [comment]
Worked for me as well :)

**Comment by denisazevedo** [comment]
Please feel free to accept it or change as desired. Thanks

**Comment by mickhansen** [comment]
@denisazevedo You've opened a pull request to your own fork, not to the main master.

**Comment by denisazevedo** [comment]
Ops, sorry about that @mickhansen.
The correct one is right [above](https://github.com/sequelize/sequelize/issues/5796).
Thank you

**Comment by ElTeixe** [comment]
> Sorry to necro-post, but I just had the same problem and adding the above line of code _before_ initializing sequelize and it solved the problem.
> 
> Like this:
> 
> require('pg').defaults.parseInt8 = true # before the following are called
> # ...
> Sequelize = require 'sequelize'
> sequelize = new Sequelize config.database, config.username, config.password, config

I've tried that but instead of returning a string now returns a number, which isn't intended either due the precission is lose.

In database field BIGINT: 1180583994472009799

Returned as:

1180583994472009700 (Type: number) 

What we need is a bigint and I've found a workaround at least working in my case:

```
require('pg').defaults.parseInt8 = true;
require('pg').types.setTypeParser(20, (val) => BigInt(val));

const Sequelize = require('sequelize');

const sequelize = new Sequelize('db', 'user', 'pass', {
	host: 'localhost',
	dialect: 'postgres',
	logging: console.log
});

etc...
```

Returned as:

1180583994472009799 (Type: bigint)
