### ISSUE TITLE
How to perform dynamic eager loading using custom join conditions?

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1776]
I have 2 models: `User` and `Module`. They are not referencing each other by any constraints/foreign keys. What I want is to get one `User` and all `Module` where `Module.type = "type1"` in  a single query. In normal SQL it would look like this:

```
SELECT Users.*, Modules.*
FROM Users
WHERE Users.id = 1
LEFT JOIN Modules
ON Modules.type = "type1"
```

What I would like to receive is:

```
{
   id: 1
   name: 'username'
   modules: [{ /*module1 data*/ },{ /* module2 data */ }]
}
```

Is it possible to accomplish this using Sequelize 1.7.x?

**Comment by adamlawson** [comment]
Hi, is there any progress on this feature request? I have a similar issue to the original post.

Thanks

**Comment by adamlawson** [comment]
Sorry, just found the same issue here https://github.com/sequelize/sequelize/issues/5385 I'll give it a test tomorrow.
