### ISSUE TITLE
Problem with Heroku Connection Strings

### ISSUE THREAD

**Issue by danielschwartz** [sequelize/sequelize#178]
Having difficulties connecting to a Heroku shared Postgres database using the standard shared database addon. Heroku gives me a connection string in a environment variable. I parse that string into the different parts (host, user, pass, db name, etc.) and they are definitely correct (i outputted the db object to the console on Heroku). 

The only difference I can tell is this: The Heroku connection string begins with a postgres:// while the postgres dialect internally hardcodes tcp;//. I am definitely not an expert in this so I have no idea if this is actually the problem or not, it's just the only difference i've been able to find.

If this is the issue, can we get an option to specificy the protocol as well? 

Here is Heroku's example using the PG library (same one used in the postgres dialect): https://devcenter.heroku.com/articles/nodejs#using_a_postgres_database

Any help woud be appreciated!

**Comment by jbarros35** [comment]
ReferenceError: dbOptions is not defined

I need some help more consistent on how to use the sample provided here.

**Comment by janmeier** [comment]
@jbarros35 Well, you haven't defined the variable `dbOptions` then ...

**Comment by jbarros35** [comment]
it doesnt works I'm asking myself if it project is mature enough.

**Comment by janmeier** [comment]
@jbarros35 you'll have to be more specific than doesn't work for us to be able to help you. Show the actual code, and the error message you are getting. And preferably in a new issue instead of one that is more than two years old ;-)
