### ISSUE TITLE
Built-in fixtures

### ISSUE THREAD

**Issue by kytwb** [sequelize/sequelize#1793]
Here's how I'm handling my fixtures for now:
                                                                                                                                                              
    var casual = require("casual");                                                                                                                          
    module.exports = function(sequelize, DataTypes) {
      return sequelize.define("Prospect", {
        firstname: DataTypes.STRING,
        lastname: DataTypes.STRING,
        email: DataTypes.STRING,
        phone: DataTypes.STRING,
        address: DataTypes.STRING,
        city: DataTypes.STRING,
        zipcode: DataTypes.STRING,
        country: DataTypes.STRING
      }, {                                                                                                                                                                    
        classMethods: {                                                                                                                                                       
          fixture: function() {                                                                                                                                               
            return {                                                                                                                                                          
              firstname: casual.first_name,                                                                                                                                   
              lastname: casual.last_name,                                                                                                                                     
              email: casual.email,                                                                                                                                            
              phone: casual.phone,                                                                                                                                            
              address: casual.address,                                                                                                                                        
              city: casual.city,                                                                                                                                              
              zipcode: casual.zip,                                                                                                                                            
              country: casual.country                                                                                                                                         
            };                                                                                                                                                                
          }                                                                                                                                                                   
        }                                                                                                                                                                     
      });
    };

I suggest:
                                                                                                                                                        
    var casual = require("casual");                                                                                                                            
    module.exports = function(sequelize, DataTypes) {
      return sequelize.define("Prospect", {
        firstname: {type: DataTypes.STRING, fixture: casual.first_name},
        lastname: {type: DataTypes.STRING, fixture: casual.last_name},
        email: {type: DataTypes.STRING, fixture: casual.email},
        phone: {type: DataTypes.STRING, fixture: casual.phone},
        address: {type: DataTypes.STRING, fixture: casual.address},
        city: {type: DataTypes.STRING, fixture: casual.city},
        zipcode: {type: DataTypes.STRING, fixture: casual.zip},
        country: {type: DataTypes.STRING, fixture: casual.country}
      });
    };

With the classMethod `fixture()` being built-in.
Any feedback? If it sounds like a good suggestion, I'll go for a pull request.
NB: DataTypes in the previous snippets might not be appropriate, but that was not the point.

**Comment by sushantdhiman** [comment]
[Sequelize-CLI](https://github.com/sequelize/cli) has seeder for this purpose https://github.com/sequelize/cli/pull/176 now. Please use them.
