### ISSUE TITLE
How to set transaction isolation level?

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1798]
```
sequelize.transaction(function(t){
   ....
});
```

How I can set transaction isolation level and from which sequelize version it is possible?

**Comment by calvintwr** [comment]
@mickhansen if you don't mind can you open this? I wanna update the documentation for this one.

**Comment by calvintwr** [comment]
https://github.com/sequelize/sequelize/pull/3684

**Comment by BridgeAR** [comment]
Solved. Should be closed.

**Comment by jbarros35** [comment]
this is not alchemy, its very hard to understand in your documentation what does means all of those isolation levels.

**Comment by mickhansen** [comment]
@jbarros35 Isolation levels differ wildly from database implementation to database implementation, so if the user isn't just using the default they should really look up the specific implementation details.
