### ISSUE TITLE
How to avoid table aliases?

### ISSUE THREAD

**Issue by JasonTheAdams** [sequelize/sequelize#1808]
I have a model:

``` js
var name = "churches";

exports['definition'] = function(sequelize, Datatypes) {
    return sequelize.define(name, {
        name:       {type: Datatypes.TEXT, allowNull: false, validate: { len: [2,50] } },
        address:    {type: Datatypes.TEXT, allowNull: true},
        colors: {type: Datatypes.TEXT, allowNull: true,  validate: { 'isJson': textIsJson } },
        baseUrl:    {type: Datatypes.TEXT, allowNull: true,  validate: { isUrl: true } },
        logo:       {type: Datatypes.TEXT, allowNull: true},
        phone:  {type: Datatypes.TEXT, allowNull: true, validate: { len: [7] } },
        email:  {type: Datatypes.TEXT, allowNull: true, validate: { isEmail: true } }
    }, {
        freezeTableName: true,
        tableName: name,
        updatedAt: 'modified',
        createdAt: 'created'
    });
}
```

I need the word table "churches" to be exactly that, always. The problem I'm running happens when I do this (Churches hasMany Forms):

``` js
    Forms
      .find({
        where: {
          id: request.params.id
        },
        include: [Churches]
      })
```

Strangely, the SQL it produces renames "churches" to "church". I tried adding the freezeTableName property to the churches config and synced, but no dice. Why is it applying an alias? And where is it even getting it from?

**Comment by DelvarWorld** [comment]
Please stop randomly aliasing my tables! My tables get randomly capitalized, quoted, and pluralized. It makes debugging queries confusing and feels like bad magic.

**Comment by janmeier** [comment]
@DelvarWorld You'll have to be more specific than that - we have options to control most of these things - what specifically do you want?

Plural table names - yes by default the name of the table is the plural of the model - use `freezeTableName` either on the model or in the sequelize constructor to use the model name verbatim. Or use `tableName` in the model definition

Capitalized - No they don't  - if your model has a capitalized name, then yes your table will be so too

Quoted - yes, unless you set `quoteIdentifiers` to false. But as you found out, that probably breaks some other scenarios

**Comment by brianchristophermendozahuey** [comment]
When Sequelize is executing SQL statements, it's for some reason capitalizing my foreignkey col names...so, from 'chatId' to 'ChatId' thus causing an error.

What's a possible reason this is happening? And any solution?

**Comment by janmeier** [comment]
@brianchristophermendozahuey Very hard to say without any code - But if your model or association alias is capitaled (`sequelize.define('Chat') || { as: 'Chat' }`), so will the foreign key be

**Comment by brianchristophermendozahuey** [comment]
Ok, it might be that the model is Capitalized. BUT, I thought by adding 'field: 'chatId' in the Message model, it should override it.

Code below is in the Message model:

`chatId: {
      type: DataTypes.INTEGER,
      references: {
        model: "Chats",
        key: "id"
      },
      field: "chatId"
    }`

**Comment by VikR0001** [comment]
Why does Sequelize change table names and aliases **at all**?  It causes an enormous number of anomalies -- especially when it happens despite freezetablenames being set to true. I just lost a day dealing with this. I love Sequelize, but will you please **turn this behavior off?**

**Comment by webmobiles** [comment]
i'm starting with sequelize, and i'm lost a lof of time with sequelize changing names... there are plan to turn off this function ?

**Comment by kmannislands** [comment]
This 'feature' must have cost developers collective lifetimes in wasted debugging. Honestly astounding that this is _intentional_.

**Comment by smithaitufe** [comment]
Please I have a challenge. How do I stop sequelize from using this `->` in table aliases?

For example, I don't want this `UserRoyaltyPurchase->UserRoyaltyPurchaseLineItem`. I want only `UserRoyaltyPurchaseLineItem`

How can I get this?

**Comment by fsevenm** [comment]
Is there any progress to this issue?

**Comment by jorgeLopezClikalia** [comment]
> Please I have a challenge. How do I stop sequelize from using this `->` in table aliases?
> 
> For example, I don't want this `UserRoyaltyPurchase->UserRoyaltyPurchaseLineItem`. I want only `UserRoyaltyPurchaseLineItem`
> 
> How can I get this?

and now?
