### ISSUE TITLE
Get previous value

### ISSUE THREAD

**Issue by pola88** [sequelize/sequelize#1814]
Hi,

I want to know if there is a way to get the previous value from _previousDataValues after save or update the model.

Thanks in advance,
PoLa.

**Comment by lekhnath** [comment]
Not working for me. I am always getting the new value.
```
particular = await particular.updateAttributes({qty: 10});
console.log(particular.previous('qty')); // 10
```
I logged `_previousDataValues` to conform and the resulting object also contains newest value provided.

**Sequelize v3.30.2**
**dialect sqlite3**
**sqlite3 v3.1.8**

**Comment by iserdmi** [comment]
That's because you already update your value. Here is an example where you can get previous value:
```
console.log(particular.qty)); // 5
particular.qty = 10;
console.log(particular.qty)); // 10
console.log(particular.previous('qty')); // 5
```

**Comment by JohnSmall** [comment]
I'll make a guess that updateAttributes() doesn't save the previous values in `previous`.

But setting the attribute directly does save the previous values in `previous`
