### ISSUE TITLE
Support async getters and setters

### ISSUE THREAD

**Issue by pensierinmusica** [sequelize/sequelize#1821]
It would be great if Sequelize could add support for async [getters and setters](http://sequelizejs.com/docs/latest/models#getters---setters).

Currently we have to use sync processes, thus blocking other incoming requests. Let's see an example of a simple user model, that has a "password" field hashed using [Bcrypt](https://github.com/ncb000gt/node.bcrypt.js).

```
var User = sequelize.define('User', {
  email: {type: DataTypes.STRING, unique: true},
  hashedPassword: {
    type: DataTypes.STRING,
    set: function (password) {
      var salt = bcrypt.genSaltSync(10);
      return bcrypt.hashSync(password, salt);
    }
  }
});
```

If Sequelize supported async getters and setters, we could instead be able to do this:

```
var User = sequelize.define('User', {
  email: {type: DataTypes.STRING, unique: true},
  hashedPassword: {
    type: DataTypes.STRING,
    set: function (password) {
      bcrypt.hash(password, 10, function (err, hash) {
        sequelizeSetterCallback(err, hash);
      });
    }
  }
});
```

This second scenario would lead to non-blocking, more efficient execution. What do you think about it?

Cheers!

**Comment by krisbarrett** [comment]
@mickhansen your example above doesn't seem to work. Upon closer inspection, done is an object, not a function.  Where can I find the documentation on what arguments get passed to the hook.

**Comment by janmeier** [comment]
@krisbarrett http://docs.sequelizejs.com/en/latest/api/hooks/

**Comment by faceleg** [comment]
@janmeier thanks but this doesn't really answer the question - how do we indicate that an async hook has completed?

**Comment by janmeier** [comment]
@faceleg return a promise from the hook

**Comment by faceleg** [comment]
@janmeier thanks!

**Comment by faceleg** [comment]
Should the promise be resolved with the `instance` as the resolve arg?

**Comment by michrome** [comment]
```javascript
var bcrypt = require('bcryptjs')

module.exports = function (sequelize, DataTypes) {
  var Person = sequelize.define('Person', {
    name: DataTypes.STRING,
    email: DataTypes.STRING,
    password: DataTypes.TEXT
  })
  Person.beforeCreate(hashPassword)
  Person.beforeUpdate(hashPassword)
  return Person
}

var hashPassword = function (person, options) {
  if (!person.changed('password')) return
  return new Promise(function (resolve, reject) {
    bcrypt.hash(person.password, 10, function (err, hashedPassword) {
      if (err) reject(err)
      else resolve(hashedPassword)
    })
  }).then(function (hashedPassword) {
    person.password = hashedPassword
  })
}
```

**Comment by ahmadnassri** [comment]
leaving this here for future visitors and in reference to @michrome code snippet:

- use [`bcrypt`](https://github.com/kelektiv/node.bcrypt.js) over [`bcryptjs`](https://github.com/dcodeIO/bcrypt.js) _(where possible)_
  - _see author's [note on security & performance](https://github.com/dcodeIO/bcrypt.js#security-considerations)_
- both `bcrypt` _(as of `v1.0.0`)_ & `bcryptjs` _(as of `v2.4.0`)_ offer Promises natively, making the following code a lot cleaner:

```js
var bcrypt = require('bcrypt')

module.exports = function (sequelize, DataTypes) {
  var Person = sequelize.define('Person', {
    name: DataTypes.STRING,
    email: DataTypes.STRING,
    password: DataTypes.TEXT
  })
  Person.beforeCreate(hashPassword)
  Person.beforeUpdate(hashPassword)
  return Person
}

var hashPassword = function (person, options) {
  if (!person.changed('password')) return
  return bcrypt
    .hash(person.password, 10)
    .then(hash => (person.password = hash))
}
```

**Comment by danmandle** [comment]
@ahmadnassri That's a great example, however, the Sequelize docs state the following:

> It is important to stick to using the setDataValue() and getDataValue() functions (as opposed to accessing the underlying "data values" property directly) - doing so protects your custom getters and setters from changes in the underlying model implementations.

So instead of setting `person.password = hash`, it should be `person.setDataValue('password', hash)`

**Comment by ahmadnassri** [comment]
@danmandle thanks for the feedback! if I recall correctly, I had tried that and for some reason it did not work ... I'll have to validate and post here again 😋

**Comment by leodutra** [comment]
Using the ES6 format...
```js
async function hashPasswordHook (usuario, options) {
  if (!usuario.changed('password')) return;
  usuario.password = await utils.hashPassword(usuario.password);
}
```

**Comment by aichholzer** [comment]
@pensierinmusica I was just thinking the same as @leodutra -Using your own code example:

```
var User = sequelize.define('User', {
  email: {type: DataTypes.STRING, unique: true},
  hashedPassword: {
    type: DataTypes.STRING,
    set: async (password) => {
      const salt = await bcrypt.genSalt(10);
      return bcrypt.hashSync(password, salt);
    }
  }
});
```

No need to explicitly `await` on that last return as `.hashSync()` is implicitly awaited for.

**Comment by pensierinmusica** [comment]
@aichholzer and @leodutra thanks for your contributions! When I created this issue in 2014 the only way to do async in JS was through callbacks. Now instead with async / await there is a perfect pattern for this use case. Cheers!

**Comment by mkondel** [comment]
@aichholzer What should happen when I return a value from the set() method? Is it supposed to set the model instance field 'hashedPassword' to this value? In my testing, when using setters with arrow functions, nothing happens, instance gets NULL in that field.

**Comment by leodutra** [comment]
BTW, I recommend **12** bcrypt salt rounds. I've seen a table a little time ago, and the time cost for it is very near 10 rounds, while breaking it is way more slow.

**Comment by vladimirpetuhov** [comment]
@aichholzer For me your feature doesn't work at all.
Here an example: 
```
is_editable: {
      type: Sequelize.VIRTUAL,
      defaultValue: false,
      async get() {
        return Promise.resolve(true);
      }
    }
```

And what i see in response: 
```
"is_editable": {},
```

**Comment by AntonNarkevich** [comment]
@vladimirpetuhov There is no way to make it work. `get` and `set` methods do not support any asynchrony. Nothing (callbacks/promises/async functions/generators) is gonna work.

And as it's said at the top of the thread it's not gonna be implemented.

**Comment by frlinw** [comment]
> Password hashing it probably the only good case and that can be done with hooks just fine.

Receive a base64, save it on an third party storage service and set the url as value can be an other use case.

It does not make sense to use a hook for all "async set" just because they are async, it's a workaround, not a logic way to do it

**Comment by watch-janick** [comment]
@frlinw +1

**Comment by crrobinson14** [comment]
If this isn't going to be done, can you at least update the docs at http://docs.sequelizejs.com/class/lib/data-types.js~VIRTUAL.html to change the example provided? There are two problems here:

1. The example is actually an incredibly poor one security-wise. It suggests that what is being done is "hashing" but actually it is simply prefixing the un-hashed string with a salt (whose definition is not discussed). An inexperienced developer attempting to follow this model would end up storing un-hashed passwords in the database, leaving them vulnerable to theft if the database was compromised.

2. Since "good" (per their authors) hashing methods (e.g. bcrypt, node crypto, etc) are async to avoid blocking the main event loop, if async can't be suported, password hashing itself is probably a bad example of the purpose of a virtual field + setter in the first place. Why not just go with the simpler `fullName` example that concatenates first/last? That one is easy and safe...

**Comment by lmbell89** [comment]
Perhaps the documentation for setters could contain a reference to hooks, which seems to be the better way to handle async password hashing

**Comment by arthurwolf** [comment]
For anyone looking for a solution to this, here's how I do the async getters for sequelize:

```
// Initialize the model.
SceneNodeOutput.init({

    image: {
        type: DataTypes.TEXT,

        // Define an asynchronous getter function for 'image_original'.
        async get(): Promise<Jimp | null> {

            // Get the buffer.
            const buffer : Buffer|null = await minio.retrieve(this.getDataValue('image'));

            // If the buffer is null, return null.
            if(buffer === null) return null;
        
            // Return the image.
            return (await buffer_to_jimp(buffer));

        },

        // Define a setter function that throws an error to prevent direct setting of this property.
        set() { throw new Error("Error: do not use the setter, use set_image") }

    },

}, {
    sequelize,
    modelName: 'scene_node_output'
});
```

This lets me do:

```
let image : Jimp = await scene_node_output.image;
```

For the setter I couldn't find a solution though.

Really interested in any comments or alternative solutions.

**Comment by BuistvoPloti** [comment]
though it is closed i'm leaving my answer on the opened issue 
https://github.com/aws/aws-sdk-js-v3/issues/5509#issuecomment-1992184090
