### ISSUE TITLE
Migrations - how to use environment variables in config.json

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1822]
I want to use migrations, but I don't want to store db credentials in config.json -> instead I would like to be able to load db credentials from environment variables.
Is it possible to somehow overcome this?

I tried to use config.js instead of config.json but sequelize throws error...
Using Sequelize 1.7.5

**Comment by ryanwalters** [comment]
Yes, automatically detecting the values of `.env` would be very useful.

**Comment by Jakobud** [comment]
Can someone explain this? Can you use .env files or not?

**Comment by mickhansen** [comment]
@Jakobud Please ask CLI related questions on the CLI repository.
