### ISSUE TITLE
Create with includes

### ISSUE THREAD

**Issue by bluecenter** [sequelize/sequelize#1838]
two objects A, B, one-on-one relationship. create A first and create B right after with include  as options to reload A in B, however it does not work. Have to use find to populate the relationship.

**Comment by dcohenb** [comment]
+1 on this

**Comment by janmeier** [comment]
@mickhansen This can be closed now, right?

**Comment by mickhansen** [comment]
Yes I think so.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/3386
