### ISSUE TITLE
DATE type gets truncated to seconds

### ISSUE THREAD

**Issue by jylin** [sequelize/sequelize#1843]
I'm using a Sqlite (and memory backend for tests), and it seems like DATE types get truncated to seconds even though you saved a `new Date()` which should be milliseconds. Hence tests that compare dates fail because the last 3 digits are always 0 when read from Sequelize.

**Comment by aiwb** [comment]
how can i turn the default createdAt and updatedAt field type from DATE to INT or BIGINT in mysql
