### ISSUE TITLE
Database connection error handling

### ISSUE THREAD

**Issue by shadone** [sequelize/sequelize#1854]
Hi there,

I've started using Sequelize just recently and one of the things missing for me is a way to detect database connection errors. I can see there is authenticate() function for establishing the initial connection to the db, however I cannot find any events / callbacks for handling errors afterwards - e.g. if the database (postgresql) is restarted my nodejs app simply crashes with the following exception:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
error: terminating connection due to administrator command
    at Connection.parseE (/Users/denis/dev/.../node_modules/pg/lib/connection.js:526:11)
    at Connection.parseMessage (/Users/denis/dev/.../node_modules/pg/lib/connection.js:356:17)
    at Socket.<anonymous> (/Users/denis/dev/.../node_modules/pg/lib/connection.js:105:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

Is there a workaround for this?

**Comment by aray12** [comment]
Is there any further discussion concerning this? I guess you could argue the entire app probably should crash if the DB connection is lost. But I am trying to kill my DB during unit testing and it is throwing an Error in my mocha hook. I'd like a way to handle the gracefully so my tests don't fail.

**Comment by lukechilds** [comment]
I've been reading the docs looking for a way to listen for connection errors and I was pretty surprised that there's really no way to do this.

Seems like this should exist:

```js
const sequelize = new Sequelize('postgres://user:pass@example.com:5432/dbname');
sequelize.on('error', handleConnectionError);
```

Would you accept a PR for this?

**Comment by Oxyaction** [comment]
any suggestions on this? really difficult to make correct connection error handling without the capability to track it on `sequelize` object. Handling such errors on query level is very inconvenient.

**Comment by lukechilds** [comment]
For anyone who needs this, I wrote Keyv which has proper error handling.

It's only suitable for key-value or cache though, more complex schema needs sequelize or similar.

**Comment by sharmiguna** [comment]
Is there update on this? is there a way to catch connection error in sequelize and not crash the node app ?

**Comment by knoxcard** [comment]
helloooo is anyone out there?

**Comment by knoxcard** [comment]
I heard you can do this...

        sequelize.sync().then(() => {
            console.log('[PASS]'.green + ' Models Loaded')
            return cb(db)
        }, err => {
            throw err
            process.exit()
        })

**Comment by knoxcard** [comment]
@sushantdhiman - i think this vital. I need Sequelize to emit an error connection problem the second it happens, any time during the program lifecycle.

```
const sequelize = new Sequelize()
sequelize.on('error', () => {
   console.log('DB failed')
   process.exit(0)
})
```

**Comment by riteshdoomra88** [comment]
Is the sequelize.on has been added for error handling, or any other way to handle sequelize error, not crash the node app ?

**Comment by sdemontfort** [comment]
@riteshdoomra88, here's what we're doing which seems to work. We're on `"sequelize": "^4.43.0"`. We use a wrapper to create one-time connections and let PgBouncer handle pooling instead of Sequelize. This allows us to catch the specific connection error and do what we want with it:

```
class SequelizeWrapper extends Sequelize {
  constructor(opts) {
    super(opts);

    // Disable Sequelize pool as we'll manage the pool externally.
    // Taken from here: https://github.com/sequelize/sequelize/issues/8468#issuecomment-430821770
    this.options.handleDisconnects = false;
    this.connectionManager.pool.clear();
    this.connectionManager.pool = null;
    this.connectionManager.getConnection = function getConnection() {
      return this._connect(this.config).catch(err => {
        // NOTE: This is an override for lack of a better solution
        if (err instanceof Sequelize.ConnectionError) {
          console.log('access to the connection error!', err);
        }
        return err;
      });
    };
    this.connectionManager.releaseConnection = function releaseConnection(
      connection
    ) {
      return this._disconnect(connection);
    };
    // HACK: Sequelize calls _refreshDynamicOIDs every time it opens a connection which is normally fine,
    // but we have a large pg_type table that keeps growing due to our use case, so turning this off results in
    // some performance benefits.
    this.connectionManager._refreshDynamicOIDs = () => Promise.resolve();
  }
}

export default SequelizeWrapper;
 ```

**Comment by naderghanbari** [comment]
Should this be reopened? Still happening on version `5.22.x`.

**Comment by joepuzzo** [comment]
Using `5.22.x` as well with mysql. I think the same problem exists for the `mysql` dialect. I am personally getting intermittent DNS issues. When the DNS issue occurs, a connection cannot be established with the sql DB. This causes the whole node.js app to crash. Are there any workarounds for this?

**Comment by perrosnk** [comment]
This should be re-opened. Any updates on this?

**Comment by siyb** [comment]
@janmeier first off, sorry for mentioning you directly. I just wanted to know if there is a way to catch connection errors now. I could not find anything in the documentation and the issue persists in Sequelize 6.8.x.
