### ISSUE TITLE
support for model scope in included (association) model?

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1873]
I would like to include some model in another and use scope for it. Currently is does not work because Sequelize does not recognize `Model.scope('scopeName')` as associated model. Here is the code (tested on MASTER):

```
var Sequelize = require('sequelize')

var sequelize = new Sequelize()

var Post = sequelize.define('Post',{})
var Comment = sequelize.define(
	'Comment',
	{ language: Sequelize.TEXT },
	{ scopes:
		{ customScope: { where: { language: 'en-us' } }
	}
})

Post.hasMany(Comment)
Comment.belongsTo(Post)

Post.findAll({ include: [{ model: Comment.scope('customScope') }] })
```
Code above throws following error:
```
Error: Comment is not associated to Post!
```
Do you plan to support such scenario? It would be very handy for example where you want to include single model in many other models and you want to "scope" it... I know I could write whole scope directly in `Post` scope but then I would have to rewrite it per every model that includes Comment.
If you agree, when you think this can be implemented on master?

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
