### ISSUE TITLE
Error translation

### ISSUE THREAD

**Issue by joerx** [sequelize/sequelize#1874]
Currently any errors thrown by the underlying database driver are simply sent straight through the call chain. This leads to different error types, messages, codes depending on the database system used. E.g. violating a unique key constraint leads to the following with MySQL:

```json
{
  "code":"ER_DUP_ENTRY",
  "errno":1062,
  "sqlState":"23000",
  "index":0,
  "sql":"...omitted..."
}
```

And using SQLite:

```json
{
	"errno":19,
	"code":"SQLITE_CONSTRAINT",
	"message": "SQLITE_CONSTRAINT: UNIQUE constraint failed: ",
	"sql":"...omitted..."
}
```

Sometimes I need to be able to respond differently based on the concrete error, e.g. in the above scenario I might want to send a "409 Conflict" response to a REST client, for other types of errors it might be 404, etc.

The requested feature would introduce a hierarchy of higher-level error types and map database errors to these error types depending on the SQL dialect used. As a result, I could do something like this:

```js
User.create(userData).then(function(user) {
   // do something nice on success
})
.catch(function(err) {
  if(err instanceof sequelize.ConstraintViolationError) {
     res.code(409); // Conflict
  }
});
```

What do you think? With some guidance, I might be able to work on a patch for this.

**Comment by janmeier** [comment]
`UniqueConstraintError` and `ForeignKeyConstraintError` have been implemented
