### ISSUE TITLE
Documentation is missing an example how to run createSchema()

### ISSUE THREAD

**Issue by lobodpav** [sequelize/sequelize#1908]
I'd like Sequelize to create DB schema for me. In the doc, there is createSchema() function mentioned. However, there is no example how to get it working.

Typically, I connect to the DB this way:

``` js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('schema_name', 'root', 'password');

sequelize.createSchema('schema_name').complete(...);
```

However the DB schema does not exist which results into `Error: ER_BAD_DB_ERROR: Unknown database`.

What is the correct way do do this job?

**Comment by rishirajrandive** [comment]
I was also trying to find a way to auto create database in MySQL with Sequilize if not present. But from the comments, it seems like we cannot do that. Is there a way I can do it?

**Comment by rishirajrandive** [comment]
@lobodpav Apology if this is the right way to ask a question. I am trying to create MySQL database using Sequelize if it's not present. The comments above say that it cannot be done. Was wondering if there is any way I can do that.
