### ISSUE TITLE
Question; usage of migration

### ISSUE THREAD

**Issue by ubaltaci** [sequelize/sequelize#1909]
Hi,

I'm new in sql development, I cant handle migration cases in collaborative development.

For example;

Our initial db consists of two table; Customers and Projects, then a teammate decide to change column name ( CustomerName) in Customer table, so it created one migration file.

After, he realised that he does not need to Customers table and he created another migration file to drop Customers table as well as customer model file.

In that point, when I clone project from scratch which consists a code part like below; since it tries to change column name which isn't exist [ customer model had been deleted from project ] It throws an error. 

````
var migrator = sequelize.getMigrator({
            path: process.cwd() + '/plugins/database/migrations'
        });

migrator.migrate({ method: 'up' })...success...error;
````

* What can I do handle these cases when I start from scratch? 

* Why migrator get all migration files and writes into db as it were already processed if db is empty ( or maybe SequelizeMeta table not exist ? ).
 
* In sql world, is this kind of migration behaviour accepted as standard ?

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
