### ISSUE TITLE
Model property to protect against mass assignment 

### ISSUE THREAD

**Issue by clouddueling** [sequelize/sequelize#1925]
I've been google through the docs but I can't find a property that stops mass assignment when I want to pass `req.body` into the model.

Kind of like: http://laravel.com/docs/eloquent#mass-assignment

But I saw there is something out there for it: https://github.com/sequelize/sequelize/blob/master/changelog.md#v150

Is this something sequelize has?

**Comment by tonetlds** [comment]
New reference:
http://docs.sequelizejs.com/en/latest/docs/instances/#working-in-bulk-creating-updating-and-destroying-multiple-rows-at-once
