### ISSUE TITLE
JOIN against function call

### ISSUE THREAD

**Issue by yuri0** [sequelize/sequelize#1940]
My query looks something like this:

````Postgres
SELECT u.*, ct.depth, ct.path, ct.cycle
FROM "Units" u, downwardsClosure(:ancestorId, 'parent') ct
WHERE u.id = ct.id;
````
or
````Postgres
SELECT u.*, ct.depth, ct.path, ct.cycle
FROM "Units" u JOIN downwardsClosure(:ancestorId, 'parent') ct ON u.id = ct.id;
````
(for what it's worth, `downwardsClosure` is essentially the second last `search_graph` example at http://www.postgresql.org/docs/current/static/queries-with.html#QUERIES-WITH-SELECT)

Is Sequelize's QueryGenerator currently capable of generating something like this?

**Comment by janmeier** [comment]
Closing in favor of https://github.com/sequelize/sequelize/issues/6718
