### ISSUE TITLE
Composite index name too long

### ISSUE THREAD

**Issue by baliw** [sequelize/sequelize#1944]
So I was creating a table tonight with 6 fields put into a compound index per the docs.

```
field: {type:Sequelize.STRING(34), unique:'main'},
another_field: {type:Sequelize.STRING(34), unique:'main'},
a_date_field: {type:Sequelize.STRING(34), unique:'main'},
yet_another_field: {type:Sequelize.STRING(34), unique:'main'},
almost_done_field: {type:Sequelize.STRING(34), unique:'main'},
last_field: {type:Sequelize.STRING(34), unique:'main'}
```

I'm getting an error from MySQL.  ER_TOO_LONG_IDENT  "Identifier name is too long".

Sequelize is combining my field names to create an index name rather than using the 'main' string I'm providing.

Is there a way to provide the index name to avoid this issue?

**Comment by thatisuday** [comment]
@mickhansen Yes, I happened to have the same problem. Composite index string is now being used for belongsToMany composition.

**Comment by nawlbergs** [comment]
Same... i have 3 tables.
rm_roadmaps
rm_userbizchallenges
and the through table: rm_userbizchallengeroadmaps

Error: ER_TOO_LONG_IDENT: Identifier name 'rm_userbizchallengeroadmaps_userBizChallenge_id_roadmap_id_unique' is too long

I cannot get it to generate...

**Comment by kareljuricka** [comment]
@nawlbergs 

For M:M relations I found how to go around this problem. Create model for rm_userbizchallengeroadmaps and add keys (that will be foreign keys for connected tables):

```
roadmap_id: {
                type: Sequelize.INTEGER,
                unique: 'roadmap_id_userbizchallenge_id'
            }, 
userbizchallenge_id: {
                type: Sequelize.INTEGER,
                unique: 'roadmap_id_userbizchallenge_id'
            }, 
```

That unique key is a solution to use own key instead of generating one. Then, in settings through options in both connected models, set parmetr unique: false : 

```
 FirstModel.belongsToMany(SecondModel, {
            through: {
                model: MiddleModel,
                unique: false
            }
        });
```

For me, this works. I only found a problem when I use parameter alter: true in sync option and then I have 1 : M relations. Same error with long identifier appears but I didn't find way how to fix it except not enable ALTER parameter.

**Comment by natesilva** [comment]
Please reopen this. This is a bug in `lib/associations/belongs-to-many.js`, `injectAttributes()`.

https://github.com/sequelize/sequelize/blob/f36db54dd5b031427fd8c52296c614c56421e4ba/lib/associations/belongs-to-many.js#L262

This line creates an index name for a BelongsToMany table, and if the name is longer than 64 characters it will fail on MySQL. On PostgreSQL I believe the name will be truncated to 63 chars, which also is not desirable.

Ideally I’d have the option to specify the index name myself.

**Comment by BartusZak** [comment]
During running sequelize migration I got

`ERROR: Identifier name 'manufactured_products_downstream_manufacturing_value_id_foreign_idx' is too long`

![image](https://user-images.githubusercontent.com/16143176/61694767-771efb80-ad32-11e9-8173-3712a1035140.png)

Is there any possibility to exceed that limitation?

`migration.js`

![image](https://user-images.githubusercontent.com/16143176/61694966-dda41980-ad32-11e9-88f2-0a558b8f7a3c.png)

**Comment by sushantdhiman** [comment]
`uniqueKey` name can be overridden now https://github.com/sequelize/sequelize/pull/9914

**Comment by khanisak** [comment]
> > During running sequelize migration I got
> > `ERROR: Identifier name 'manufactured_products_downstream_manufacturing_value_id_foreign_idx' is too long`
> > ![image](https://user-images.githubusercontent.com/16143176/61694767-771efb80-ad32-11e9-8173-3712a1035140.png)
> > Is there any possibility to exceed that limitation?
> > `migration.js`
> > ![image](https://user-images.githubusercontent.com/16143176/61694966-dda41980-ad32-11e9-88f2-0a558b8f7a3c.png)
> 
> Hello，I also encountered the same problem as you when performing the migration. UniqueKey did not work. Do you have a solution?

DId you find out solution for this issue?

**Comment by Fantast416** [comment]
> > > During running sequelize migration I got
> > > `ERROR: Identifier name 'manufactured_products_downstream_manufacturing_value_id_foreign_idx' is too long`
> > > ![image](https://user-images.githubusercontent.com/16143176/61694767-771efb80-ad32-11e9-8173-3712a1035140.png)
> > > Is there any possibility to exceed that limitation?
> > > `migration.js`
> > > ![image](https://user-images.githubusercontent.com/16143176/61694966-dda41980-ad32-11e9-88f2-0a558b8f7a3c.png)
> > 
> > 
> > Hello，I also encountered the same problem as you when performing the migration. UniqueKey did not work. Do you have a solution?
> 
> DId you find out solution for this issue?

I havn't find any solution since, my solution is to reduce the character number of the field name.

**Comment by khanisak** [comment]
`'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.addColumn("invoice_service_administration", "id_service_administration", {
      type: Sequelize.INTEGER,
      allowNull: false,
      after: "id_subscription"
    });
    await queryInterface.addConstraint("invoice_service_administration", {
      type: "FOREIGN KEY",
      name: "invoice_id_service_administration_foreign_fk",
      fields: ["id_service_administration"],
      references: {
        table: "service_administration",
        field: "id"
      }
    });
    return Promise.resolve();
  }
};`

For now my workaround is to create new column and foreign key constraint in separate line. As we can override constraint name in **addConstraint** method and not in **addColumn** method. 

I think it should be an option in **addColumn** to override foreign key constraint name instead doing two separate line code like I do.

**Comment by chongma** [comment]
Is there a solution?

**Comment by Ocresort** [comment]
¿Hay alguna solución?

**Comment by chongma** [comment]
@Ocresort My solution was to stop using sequelize.  There are a lot of open issues on this project that look like they will never get fixed.  Learning to use SQL is a better skill than trying to figure out how an ORM is working.  The best use case for an ORM is if you want to switch your database type every week (e.g. MariaDb to Oracle)
