### ISSUE TITLE
Empty array as defaultValue causes errors

### ISSUE THREAD

**Issue by RangerMauve** [sequelize/sequelize#1956]
Hello, I'm trying to get an empty array as the default value of a column for an array of integers in PostgreSQL.

My first attempt looked something like this:
``` javascript
var User = sequelize.define("User", {
        contacts: {
                type: Sequelize.ARRAY(Sequelize.INTEGER),
                defaultValue: []
        }
});
```

However, this caused an error because the default for the contacts column was being set to `ARRAY[]`. The error gave a hint saying to use `ARRAY[]::integer[]` instead.

I then tried to use the syntax for declaring the type as the default value in hopes that it'd create the correct value.
``` javascript
var User = sequelize.define("User", {
        contacts: {
                type: Sequelize.ARRAY(Sequelize.INTEGER),
                defaultValue: Sequelize.ARRAY(Sequelize.INTEGER)
        }
});
```
This made Postgres complain again because the outputted default value was `\'INTEGER[]\'` (with the escaped characters). This time the error said `error: array value must start with "{" or dimension information` which makes me think that `{}` would be a valid default.

Personally, I think that the library should handle setting the default from empty arrays.
This initially looked like it was related to #714.

**Comment by BridgeAR** [comment]
I guess this is already fixed? I know it's working fine for ARRAY(HSTORE). I'll write a couple unit test to check the types thought.
Ping @mickhansen

**Comment by mickhansen** [comment]
@BridgeAR [] is working as a default value for you?

**Comment by BridgeAR** [comment]
This should be closed

**Comment by kevincolten** [comment]
You have to type the default array for postgres:

```
    skills: {
      type: DataTypes.ARRAY(),
      defaultValue: [DataTypes.STRING]
    },
```

with enums
```
    skills: {
      type: DataTypes.ARRAY(DataTypes.ENUM(selectors.skills)),
      defaultValue: [DataTypes.STRING]
    },
```

**Comment by wambugucoder** [comment]
[] this should work dont space them while defining defaultvalue

**Comment by sane5ek** [comment]
Hello everyone! I faced exactly the same problem. I wrote like this:

```js
email: {
      type: Sequelize.ARRAY(Sequelize.TEXT),
      allowNull: false,
      defaultValue: []
},
```

Then `sequelize-auto-migrations` generated a migration of the following type for me:

```js
var migrationCommands = function(transaction) {
    return [{
        fn: "addColumn",
        params: [
            "Gallery",
            "email",
            {
                "type": Sequelize.ARRAY(Sequelize.STRING),
                "field": "email",
                "defaultValue": Sequelize.Array,
                "allowNull": false
            },
            {
                transaction: transaction
            }
        ]
    }];
};
```

And I was getting an error from Postgres that the field cannot contain null values in existing records. All that is required for postgres to see the default values for this field is to replace 

```js
"defaultValue": Sequelize.Array,
```

with

```js
"defaultValue": [],
```

 in the migration file.
