### ISSUE TITLE
Method for specifying unique keys different in define vs migrations

### ISSUE THREAD

**Issue by ysulyma** [sequelize/sequelize#1966]
To specify a unique key in a model definition, I do something like

``` Javascript
sqlz.define(
  'Example',
  {
    fieldA: {
      type: INTEGER,
      allowNull: false,
      unique: 'uniqueAB'
    },
    fieldB: {
      type: INTEGER,
      allowNull: false,
      unique: 'uniqueAB'
    },
    fieldC: {
      type: INTEGER,
      allowNull: false,
      unique: true
    },
  }
)
```

However, to do it in a migration, I need to do use a `uniqueKeys` option:

```
migration.createTable(
  'Example',
  {
    fieldA: {
      type: INTEGER,
      allowNull: false
    },
    fieldB: {
      type: INTEGER,
      allowNull: false
    },
    fieldC: {
      type: INTEGER,
      allowNull: false
    },
  },
  {
    uniqueKeys: [
      {fields: ['fieldA', 'fieldB']},
      {fields: ['fieldC']}
    ]
  }
)
```

This is very unintuitive (and undocumented). I expect to generally be able to copy the model definition into a migration file / vice versa. In fact I thought it used to work that way.

Sequelize 1.7.8

**Comment by tylerFowler** [comment]
I don't know how much this has changed (I'm using version 2.0.6) but the `uniqueKeys` option didn't even work for me. I had to use `migration.addIndex` in order to do a composite unique key at all.

+1 on the define syntax being used for migrations though.

**Comment by hourliert** [comment]
Thanks @yuri0. You save my day...
