### ISSUE TITLE
n:m through does not support multiple same associated models. Unwanted unique key.

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#1997]
```
var Post = sequelize.define('Post',{});
var AssociatedPost = sequelize.define('AssociatedPost',{
  language: { type: Sequelize.TEXT, primaryKey: true },
  PostId: { type: Sequelize.INTEGER, references: "Posts", referencesKey: "id" primaryKey: true },
  AssociatedPostId: { type: Sequelize.INTEGER, references: "Posts", referencesKey: "id", primaryKey: true },
});
Post.hasMany(Post, { through:AssociatedPost, as: 'AssociatedPosts' }) 
```
1. Code above despite primaryKey on three columns adds `uniqueKey` on `PostId, AssociatedPostId`.
2. When querying posts like this:

```
Post.find({ include: [{ model: Post, as: 'AssociatedPosts' }] })
```

It does not return "duplicate" associated posts - if I remove unwanted unique key (using migration) then I can associate same post twice with different language:

```
{ PostId: 1, AssociatedPost: 2, language: 'en-us' }
{ PostId: 1, AssociatedPost: 2, language: 'zh-cn' }
```

Query should return post 2 twice (same post), however it is returning it just once. I checked SQL and it is correct, post 2 id joined twice - it seems that sequelize parser assumes that unique key is `PostId, AssociatedPostId` and groups by this key omitting "duplicate" model....

**Comment by sushantdhiman** [comment]
Fixed, Please check https://github.com/sequelize/sequelize/issues/2459
