### ISSUE TITLE
Count using distinct?

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#2002]
How I can count by distinct id of model?
Use case: I want to find all Posts that have at least one PostTranslation according to some condition.

```
Post.count({ include: [{ model: PostTranslation, where: { language: 'en-us' }, required: true }] }
```

This query uses inner join, however it will count twice if there will be two pos translations for one post.

**Comment by stephenjesus** [comment]
https://onlinedevtools.in

its useful for developers
