### ISSUE TITLE
Need for support of Sequelize.literal() in query.order

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#2005]
```
Post.findAll({ order: [ Sequelize.literal('CASE WHEN "Post"."id" = 1 THEN 2 WHEN "Post"."id" = 2 THEN 1') ] })
```

It does not work for now, I will prepare PR with test for it.

**Comment by mtfranchetto** [comment]
Broken in 2.0.0-rc6, the ORDER BY produced is: 

`ORDER BY [object Object]`

**Comment by NimilaJ** [comment]
db[modelName].findAll({
    where: whereC,
    order: [
      [sequelize.literal(`CASE ${modelName}.is_archived WHEN 0 THEN ${modelName}.last_updated_time ELSE -1 END`), 'DESC'],
    ],
    limit,
    offset: page * limit,
  });
