### ISSUE TITLE
PostgreSQL dialect issue with scale, maybe set default SQL dataType to numeric from datatypes.FLOAT ? 

### ISSUE THREAD

**Issue by josdewitte** [sequelize/sequelize#2014]
PostgreSQL does not support scale for native FLOAT datatype; furthermore the default floating-point type seems to be numeric in those cases?

FLOAT(10,2) is not supported (FLOAT(10) or numeric(10,2) is).

**Comment by BridgeAR** [comment]
@josdewitte @janmeier @mickhansen There is no [float] (http://www.postgresql.org/docs/9.4/static/datatype-numeric.html) in postgres. So if someone uses the DataType.FLOAT in postgres, it's just inherently wrong.

**Comment by mickhansen** [comment]
@BridgeAR Right, people should just use NUMERIC directly. Although we could consider doing the mapping.
