### ISSUE TITLE
SQL injections

### ISSUE THREAD

**Issue by rcorral** [sequelize/sequelize#2028]
I'm curious if sequelize takes care of sanitizing input to mitigate sql injections?

Thanks.

**Comment by DG-Wangtao** [comment]
But, why follow code can excute?
```
Table.findAll({
      attributes:
      [
        'id',
        ['sum("col1")', 'sum']
      ],
      group: ['id'],
    });
```

As I can us `sum` function in atttribute,is there any risk of  sql injection?

**Comment by mickhansen** [comment]
@DG-Wangtao If you were to accept user input into the first argument of the array used in the attributes array, then yes you might be exposed

**Comment by DG-Wangtao** [comment]
> @DG-Wangtao If you were to accept user input into the first argument of the array used in the attributes array, then yes you might be exposed

Thanks !
Because I meet erro `attr[0].indexOf is not a function` when I use Sequelize.fn like this:
```
Table.findAll({
      attributes:
      [
        'id',
       [Sequelize.fn('sum', Sequelize.col('col1')), 'sum']
      ],
      group: ['id'],
    });
```

The error was here 
```
egg-sequelize/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1243:28)

else if (attr[0].indexOf('(') === -1 && attr[0].indexOf(')') === -1) {
```
So I try to use `sum` function as this.
