### ISSUE TITLE
Change column in SQLite loses indices

### ISSUE THREAD

**Issue by joerx** [sequelize/sequelize#2033]
Seems when using a 'changeColumn' query with SQLite in a migration causes any indices on that table to be lost. That's caused by the fact that the affected table will be dropped and re-created. When recreating the table, the associated indices are 'forgotten'.

The MySQL dialect does not have this issue.

**Comment by sushantdhiman** [comment]
Move to https://github.com/sequelize/sequelize/issues/7078
