### ISSUE TITLE
How to specify Model on scopes?

### ISSUE THREAD

**Issue by santialbo** [sequelize/sequelize#2037]
I have a couple of related Models on an existing database with an `archived` field so I defined the `defaultScope` for both as:

    defaultScope: {
      where: { archived: false }
    }

The problem is that when I join tables the `archived` property is not scoped to the model and then I get an ambiguous field error since the two tables have said field. Is there any way of specifying that the `archived` field belongs to the model being defined?

Thanks

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
