### ISSUE TITLE
Is unsigned decimal type supported?

### ISSUE THREAD

**Issue by yoyek** [sequelize/sequelize#2038]
I got "Unrecognized data type for field price" exception with this schema definition:

```
var Order = db.define('order', {
    price: Sequelize.DECIMAL.UNSIGNED
});
```

INTEGER.UNSIGNED works as expected.

**Comment by BridgeAR** [comment]
Since the data types got refactored it should be possible to use unsigned when ever the dialect supports that. @mickhansen @janmeier 
I'll write a couple of unit tests for this.
