### ISSUE TITLE
Data-type UP / DOWN system

### ISSUE THREAD

**Issue by janmeier** [sequelize/sequelize#2042]
Supersedes #1690 

What we want is some kind of system, which allows a more or less dialect-independent way of converting data types between their javascript at DB representations. This system should also be extendable by the user

**Comment by florian-rossiaud** [comment]
Hi,

Do you know for when this feature will be implement ? May I can help ?

**Comment by mickhansen** [comment]
@florian-rossiaud No estimate. When we get to it is all we can say i'm afraid.

**Comment by janmeier** [comment]
... But pull requests are always welcome :-). 

For this feature we'd probably need a bit of api discussion first - feel free to provide a suggestion, or more details into the use case you'd like this to support

**Comment by florian-rossiaud** [comment]
I think the DataType should know how to escape his value. We could have a function inside DataType `escape` who espace the value on the query.

For now escape is like that :
      
    escape: function(value, field) {
      if (value && value._isSequelizeMethod) {
        return this.handleSequelizeMethod(value);
      }

      if (Utils._.isObject(value) && field && (field.type instanceof DataTypes.HSTORE || DataTypes.ARRAY.is(field.type, DataTypes.HSTORE))) {
        if (field.type instanceof DataTypes.HSTORE){
          return "'"  + hstore.stringify(value) + "'";
        } else if (DataTypes.ARRAY.is(field.type, DataTypes.HSTORE)) {
          return "ARRAY[" + Utils._.map(value, function(v){return "'" + hstore.stringify(v) + "'::hstore";}).join(",") + "]::HSTORE[]";
        }
      } else if(Utils._.isArray(value) && field && (field.type instanceof DataTypes.RANGE || DataTypes.ARRAY.is(field.type, DataTypes.RANGE))) {
        if(field.type instanceof DataTypes.RANGE) { // escape single value
          return "'"  + range.stringify(value) + "'";
        }
        else if (DataTypes.ARRAY.is(field.type, DataTypes.RANGE)) { // escape array of ranges
          return "ARRAY[" + Utils._.map(value, function(v){return "'" + range.stringify(v) + "'";}).join(",") + "]::" + field.type.toString();
        }
      } else if (field && (field.type instanceof DataTypes.JSON || field.type instanceof DataTypes.JSONB)) {
        value = JSON.stringify(value);
      } else if (Array.isArray(value) && field && DataTypes.ARRAY.is(field.type, DataTypes.JSON)) {
        return "ARRAY[" + value.map(function (v) {
          return SqlString.escape(JSON.stringify(v), false, this.options.timezone, this.dialect, field);
        }, this).join(",") + "]::JSON[]";
      }

      return SqlString.escape(value, false, this.options.timezone, this.dialect, field);
    },

So for each DataType in each dialect you return an formatted string in function of what you need. You could use a things like this :

    /**
     * A GEOMETRY column. Only available in postgis.
     * @property GEOMETRY
     */
    var GEOMETRY = function () {
        if (!(this instanceof GEOMETRY)) return new GEOMETRY();
        Sequelize.ABSTRACT.apply(this, arguments);
        this._getter = 'ST_AsGeoJSON';
        this._setter = 'ST_GeomFromGeoJSON';
    };
    util.inherits(GEOMETRY, Sequelize.ABSTRACT);

    GEOMETRY.prototype.key = GEOMETRY.key = 'GEOMETRY';
    GEOMETRY.prototype.setter = GEOMETRY.setter = function(value) {
        return 'ST_AsGeoJSON(' + JSON.stringify(value) + ')';
    }
    GEOMETRY.prototype.getter = GEOMETRY.getter = function(field) {
        return 'ST_AsGeoJSON(' + field + ')';
    }

Or a thing like that. All your logic will be in your dataType.

**Comment by mickhansen** [comment]
@florian-rossiaud we would agree with that, hence the proposal for an UP/DOWN system that would take all the current escaping/parsing logic and place it with the data types.

**Comment by janmeier** [comment]
In your example both `ST_GeomFromGeoJSON` and `ST_AsGeoJSON` are DB methods right?

In my mind, one method takes a JS representation and converts in to DB representation ready for  insert, the other takes a DB representation and converts in to JS. An example for DATE would be

```js
up: function (dateObj) {
  return dateObj.format('YY-M-D h:m:d Y');
},
down: function (dateString) {
  return new Date(dateString);
}
```

**Comment by florian-rossiaud** [comment]
We can already do that with `get` and `set` method in the model. But we can do a `up` and `down` method for the DataType and a `get` and `set` method for have both functionality.

**Comment by janmeier** [comment]
I know something like that is already possible, but my idea was to move the code up one level of abstraction so to speak - so that it is applied to all field instances of that type:

**Comment by florian-rossiaud** [comment]
True that.

I don't have so much time to implement this pm but if I found some time in the next week ill give a try (to implement up / down and set / get)
