### ISSUE TITLE
Migrations: How to add data to a new column

### ISSUE THREAD

**Issue by nichdiekuh** [sequelize/sequelize#2050]
Hello,

I have a simple migration and want to add a UUIDv4 column to an existing table.

I already have migration script set up which adds the new column:

```
module.exports = {
  up: function(migration, DataTypes, done) {
    // add altering commands here, calling 'done' when finished

    migration.addColumn(
        'Graphs',
        'uuid',
        { type: DataTypes.UUID, allowNull: false, defaultValue:DataTypes.UUIDV4}
    )
    done();
  },
  down: function(migration, DataTypes, done) {
    // add reverting commands here, calling 'done' when finished
    done();
  }
}
```

Now the tricky part: After adding the new column I'd like to set UUIDs for all rows automatically. Is that possible?

**Comment by TannerS** [comment]
hello! is there a way to do this but the v6 of sequelize?
