### ISSUE TITLE
Can't add unique columns with SQLite

### ISSUE THREAD

**Issue by santialbo** [sequelize/sequelize#2051]
When trying to add a unique column on a migration for a SQLite database the following error is thrown:

```
Possibly unhandled Error: SQLITE_ERROR: Cannot add a UNIQUE column.
```

Checking the code I saw that the SQLite dialect is relying on the Mysql one for the addColumn function. Aparently the way to do it in SQLite is to add the column and then create a unique index. I could overcome this problem by running the migration like this:

```
migration.addColumn('products', 'key', {
  type: DataTypes.STRING(191),
}).then(function() {
  return migration.addIndex('products', ['key'], {
    indicesType: 'UNIQUE'
  })
}).then(done);
```

but it would be nice if I could still do the `unique` option inside the addColumn.

**Comment by Wtower** [comment]
+1

**Comment by julienvincent** [comment]
Whats the status of this issue? I am getting the following on the latest version of Sequelize:

```js
{ SequelizeDatabaseError: SQLITE_ERROR: Cannot add a UNIQUE column
      name: 'SequelizeDatabaseError',
      parent:
       { Error: SQLITE_ERROR: Cannot add a UNIQUE column
         errno: 1,
         code: 'SQLITE_ERROR',
         sql: 'ALTER TABLE `x` ADD `link_id` UUID UNIQUE;' },
      original:
       { Error: SQLITE_ERROR: Cannot add a UNIQUE column
         errno: 1,
         code: 'SQLITE_ERROR',
         sql: 'ALTER TABLE `x` ADD `link_id` UUID UNIQUE;' },
      sql: 'ALTER TABLE `x` ADD `link_id` UUID UNIQUE;' }
```

My migration looks like:

```js
await queryInterface.addColumn("x", "link_id", {
  type: sequelize.UUID,
  defaultValue: sequelize.UUIDV4,
  allowNull: false,
  unique: true
})
```

**Comment by harrisonhoward** [comment]
Still an issue to this day unfortunately..
```ts
queryInterface.addIndex("users", "email", {
	type: "UNIQUE",
});
```
This is the current solution I'm using.

**Comment by harrisonhoward** [comment]
Despite the fact this issue is closed, this issue still exists. I managed to around it by just adding `UNIQUE` to the type on the column.
```ts
await queryInterface.addColumn("x", "y", {
  type: `${Sequelize.DataTypes.STRING} UNIQUE`
})
```
Like so, I checked if it worked and it does create the unique index in SQLite.

**Comment by verveguy** [comment]
This is still a bug in latest sequelize.

SQLITE_ERROR: Cannot add a UNIQUE column

```javascript
await queryInterface.addColumn("atlases", "urlId", {
  type: Sequelize.STRING,
  unique: true,
});
```
