### ISSUE TITLE
[] in query resolves to NULL in mySQL

### ISSUE THREAD

**Issue by andrewaustin** [sequelize/sequelize#2052]
I've got the following code:

```
DbModel.destroy([{id: {not: updatedIDs}}, {score_id: sectionID }])
```

This generates the following query if updatedIDs is non empty (in mySQL):

```
DELETE FROM `questions` WHERE (`id` NOT IN (8084) AND `score_id`=135040)
```

However, if updatedIDs = [], I get the following:

```
DELETE FROM `questions` WHERE (`id` NOT IN (NULL) AND `score_id`=135041)
```

This seems like a bug because it **deletes nothing**. I would expect sequelize to generate a query logically equivalent to something like:

```
DELETE FROM `questions` WHERE score_id`=135041
```

**Comment by BridgeAR** [comment]
As @mshiltonj pointed out this would be quite dangerous. If someone wants to delete all datasets of a table it should always be explicit, not implicit as suggested. The scope is always what the user provides. If he provided an empty array, so let it be and return/delete nothing. I'd go so far and say the best way to handle this is not fireing a query at all if an empty array is passed and resolve immediatly, if there's no $or in the where clause. No matter if it's IN [] or NOT IN [].

That way nothing bad or unintented can happen. If anyone wants to handle empty arrays differently, that person can write his code in a way to remove the array explicitly from the where clause.

**Comment by sushantdhiman** [comment]
I think it would be pretty dangerous to remove `IN []` or `NOT IN []` which can leads to unexpected queries. User must handle empty cases explicitly, ORM should not be doing this.

It should be closed @mickhansen @janmeier

**Comment by sushantdhiman** [comment]
I honestly think we will not support these automagical transformation that can make your whole table disappear.

Please remove the empty `[ ]` from `where` conditions explicitly if your business logic demands it. But Sequelize will still keep `[ ] => IN (NULL)` for safety purpose at least.
