### ISSUE TITLE
Casting a field in a where condition?

### ISSUE THREAD

**Issue by jValdron** [sequelize/sequelize#2063]
I used to be able to use `keysEscaped` to cast my fields in my where conditions, but can't seem to be able to do this anymore:

```
Vehicle.findAll({
  where: sequelize.and(
    { '"vin_id"': values.vin_id },
    { "odometer"::integer': { gt: parseInt(values.odometer, 10) || 0 } }
  ),
  keysEscaped: true
});
```

Is there any way to properly cast my field to an integer?

Btw, sorry for all the issues, just trying to make everything look clean ;)

**Comment by fabianrios** [comment]
just want to add that if you use 'vehicle.odometer' instead of sequelize.col('vehicle.odometer') it can cause problems so it's better to use it.

**Comment by sfali16** [comment]
Does `sequelize.where` still not support calling functions (like cast or date_trunc) on the table columns as the operand for the conditional. 
I want to do something like 
`"message_result"."timestamp_column" IS NOT NULL
   AND date_trunc('seconds', "message_result"."timestamp_column") > '2019-01-04 20:50:50.996 +00:00'
   AND date_trunc('seconds', "message_result"."timestamp_column") <= '2019-01-04 21:00:56.997 +00:00'`

and using Sequelize.literal or Sequelize.fn doesn't seem to work with it.

**Comment by rahulsps** [comment]
This worked for me:

```
Notification.findOne({ where: {
  [Op.and]: [
    sequelize.literal("cast(notify_data as CHAR) = "+game_id),
    {user: players[i].user, notify_type: type.id}
  ]
}});
```

Basically, _sequelize.literal_ returns a string rather than a key-value pair, so I did a work around using Op.and which can take both strings and objects in its array
