### ISSUE TITLE
Method to catch all errors?

### ISSUE THREAD

**Issue by takempf** [sequelize/sequelize#208]
Is there any way to catch all uncaught errors generated by Sequelize? I use an error reporting system, and I'd like to be able to globally report any uncaught Sequelize errors I have back to my error reporter.

**Comment by up9cloud** [comment]
Memo for catch all Sequelize errors:

https://github.com/sequelize/sequelize/blob/2a4e1113a3bea957998ea7967eef66718e4e5eb4/lib/sequelize.js#L1271

```js
const sequelize = require('sequelize')
try {
  sequelize.query("__INVALID__;")
} catch (e) {
  if (e instanceof sequelize.Error) {
    // it is
  } else {
    // others
  }
}
```
