### ISSUE TITLE
Raw Query Replacement is broken

### ISSUE THREAD

**Issue by billxinli** [sequelize/sequelize#2085]
Assume:
```
sequelize.query('SELECT * FROM people WHERE properties::text = :blob', Person, {}, {blob: '{"NAME":"PERSON1"}'})
.then(function (person) {})
```

Raises: `Error: Named parameter ":text" has no value in the given object.`

Latest stable version

**Comment by janmeier** [comment]
Appears to be fixed https://github.com/sequelize/sequelize/blob/master/lib/sql-string.js#L157-L159

**Comment by tinganho** [comment]
I think I still experience this problem:
```
let foundUsers =  await DbContext.query(`
        SELECT id, name, username, email, "createdAt", "updatedAt"
        FROM users
        WHERE "passwordHash" = crypt(:password, salt)
        AND (LOWER(email) = LOWER(:email) OR LOWER(username) = LOWER(:username))
    `, {
        replacements: {
            email: email,
            username: username,
            password: password,
        },
        model: User
    }
);
```

```
Error: Named parameter ":username" has no value in the given object.
```

**Comment by Nainesh86** [comment]
I am also getting this error.
please solve this error guys.
`var queries = "SELECT " +
                columns.join(", ")+ " " +
                "FROM wines " +
                "INNER JOIN wines ON wines.wine = wines.id " +
                "WHERE wines.id IN (:wine_ids) " +
                "ORDER BY wines.id ";

            models.sequelize.query(queries,{
                replacements:{
                    wine_id:request.body.wine_ids
            },
                type: models.Sequelize.QueryTypes.SELECT,
                raw:true
            })`

**Comment by janmeier** [comment]
@Nainesh86 You are missing an `s` on `wind_id` .......

**Comment by Nainesh86** [comment]
actually I try both. you are right @janmeier but after do it. he same error will returned.. it will not fetch the wine_id. i can't understand the error.

**Comment by janmeier** [comment]
Have a look at https://stackoverflow.com/questions/920353/can-i-bind-an-array-to-an-in-condition - You cannot use an array in a bind parameter like that. You will either need to insert a number of replacements corresponding to the number of elements of the array, or use something like `wine.id = ANY(:wine_ids::INTEGER[])` (postgres syntax, probably different for mysql if it even exists)

**Comment by Nainesh86** [comment]
thanks sir. actually i try all the possibility but it will still giving an same error. @janmeier
