### ISSUE TITLE
How to force to NOT query for ANY of the attributes of association?

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#2086]
I tried `include: [{ model: Post, attributes: [] }]` but it does not work. I found in code that even if no attributes are specified Sequelize will always query for PK attribute. This is not always desired behaviour. Right now I am including model `Post` just to group it and aggregate (COUNT) on them. The problem is that when I am using COUNT in my query I have to put "Post.id" into group statement, but then it does not count properly. Consider this (I want to list all categories, each with number of posts in this category):

```
var Post = sequelize.define(...)
var Category = sequelize.define(...)
Post.belongsTo(Category)

query = {
   include: [{ model: Post, attributes: [] }],
   attributes: ['id','index',Sequelize.literal('COUNT("Category"."id") AS "postsCount"')],
   group: ['Category.id']
}

Category.findAll(query).done(function(err,categories){
});
```

Code above will generate following query:

```
SELECT "Category"."id"
    ,"Category"."index"
    ,COUNT("Category"."id") AS "postsCount"
    ,"Posts"."id" AS "Posts.id"
FROM "Categories" AS "Category"
LEFT JOIN "Posts" AS "Posts" ON "Category"."id" = "Posts"."CategoryId"
GROUP BY "Category"."id"
ORDER BY "index" ASC;
```

and error

```
"column \"Posts.id\" must appear in the GROUP BY clause or be used in an aggregate function"
```

If I add `Post.id` to group like this: `group: ['Category.id',[{ model: Post },'id']]` then there wont be error however results will be incorrect (each postCount will be equal 1). The only way to make it work for me is to manually change SQL query NOT to include Post.id. Then I get correct results:

```
id;index;postsCount
1;1;46
2;2;42
3;3;46
4;4;28
5;5;38
```

So what I have to do i just force not to include any of attributes of Post model - is it possible? Is there any workaround?

**Comment by syldor** [comment]
Instead of this idea of forcing not to query, is there a workaround to do that kind of aggregation + join ? 
(I have the same issue with SUM: http://stackoverflow.com/questions/28206680/using-group-by-and-joins-in-sequelize).
