### ISSUE TITLE
Overriding DAO.prototype methods

### ISSUE THREAD

**Issue by noah-goodrich** [sequelize/sequelize#2091]
I need to override the `DAO.prototype.save` method for a specific model. In PHP I could do this:

```
class Parent {
     public function save($arg1,$arg2) {
           echo 'parent';
    }
}

class Child extends Parent {
     public function save($arg1,$arg2) {
           echo 'child';

           parent::save($arg1,$arg2);
    }
}
```

I have tried iimplementing `save` in `instanceMethods` but can't seem to find a way to call the original  `save` method from the DAO prototype.

How can I best accomplish this in Sequelize?

**Comment by BernhardBezdek** [comment]
+1 Thanks for the mention helped me a lot!
