### ISSUE TITLE
dropTable: problems when forcing the table drop

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2100]
`force: true` and `cascade: false` doesn't force the table drop.

``` js
    migration.dropTable( 'Model', {

        force: true,
        cascade: false,

    }).done( done );
```

We need to disable `foreign_key_checks` on mysql before attempt to drop it, i think sequelize isn't doing it.

**Comment by u-can-miracle** [comment]
Look at the solution in [source code](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L250)
