### ISSUE TITLE
Problem with hooks

### ISSUE THREAD

**Issue by Bondifrench** [sequelize/sequelize#2105]
My model is defined as follows

```
var User = sequelize.define('user',{
        email: {
            type: Sequelize.STRING(25), unique: true, allowNull:false, validate: {isEmail: true}
        },
        password: {
            type: Sequelize.STRING, allowNull: false
        }
    },{
        instanceMethods:{
            generateHash : function (password, done) {
                bcrypt.genSalt(10, function (err, salt) {
                    bcrypt.hash(password, salt, null, done); 
                });
            },
            validPassword : function (password, next) {
                bcrypt.compare(password, this.password, next)
                }
        }
    })
```

When I create a hook outside my model like this:

```
User.beforeCreate(function (model, done) {
    bcrypt.genSalt(10, function (err, salt) {
        bcrypt.hash(model.password, salt, null, function (err, encrypted) {
            console.log('Using beforeCreate to generate encrypted password');
            if (err) return done(err);
            model.password = encrypted;
            done();
        });     
    })
})
```

It works, my password is salted and hashed, however when I try to redefine my model to put the hook inside the model definition like this:

```
var User = sequelize.define('user',{
        email: {
            type: Sequelize.STRING(25), unique: true, allowNull:false, validate: {isEmail: true}
        },
        password: {
            type: Sequelize.STRING, allowNull: false
        }
    },{
        instanceMethods:{
            generateHash : function (password, done) {
                bcrypt.genSalt(10, function (err, salt) {
                    bcrypt.hash(password, salt, null, done); 
                });
            },
            validPassword : function (password, next) {
                bcrypt.compare(password, this.password, next)
                }
        }
    }
,{
hooks: {
            beforeCreate: function (model, done) {
                bcrypt.genSalt(10, function (err, salt) {
                    bcrypt.hash(model.password, salt, null, function (err, encrypted) {
                        if (err) return done(err);
                        model.password = encrypted;
                        done();
                    });
                })
            }
        }}
)
```

It doesn't work, when User.create() my password is not going through the hook, it's not being encrypted, any clues?

Second question:
As you can see I created instanceMethod `generateHash`, when defining multiple hooks inside the model, is there anyway to reference the before defined instanceMethods? Having something like

```
hooks: {
         beforeCreate: function (password, done) {
                User.generateHash(password, function (err, encrypted){
                       if (err) return done(err);
                       User.password = encrypted;
                       done();
}}
```

Obviously I tried and it didn't work either.
I am still a beginner in using Sequelize and NodeJs in general, help appreciated.

**Comment by callen5914** [comment]
`var bcrypt = require('bcrypt-nodejs');

'use strict';
module.exports = function(sequelize, DataTypes) {
  var Team = sequelize.define('Team', {
    teamName: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    teamEmail: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isEmail: true
      }
    },
    teamPassword: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        len: [6, 64]
      }
    },
    teamActive: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true
    }
  }, {
    classMethods: {
      generateHash : function (password, next) {
        bcrypt.genSalt(10, function (err, salt) {
          bcrypt.hash(password, salt, null, next); 
        });
      },
      associate: function(models) {
        Team.hasMany(models.Member);
      }
    },
    instanceMethods: {
      validPassword : function (password, next) {
        bcrypt.compare(password, this.password, next)
      }
    },
    hooks: {
      beforeCreate: function(team, next){
        Team.generateHash(team.teamPassword, function(err, encrypted){
          if (err) return next(err);
          team.teamPassword = encrypted;
          next();
        });
      }
    }
  });
return Team;
};`

So why is this broke? I am so confused right now the error I get is that next is not a function.

**Comment by felixfbecker** [comment]
@callen5914 Because there is no `next` parameter to hooks. Please don't resurrect old issues.
