### ISSUE TITLE
POJO only one level deep with instance.dataValues.subinstance

### ISSUE THREAD

**Issue by sixlettervariables** [sequelize/sequelize#2119]
I'm working with kraken+dust and I've been bit by the recent change to dust (2.4.X) where only POJO's can be passed to the template as a rendering context (they no longer walk the prototype chain due to some odd corner cases). It appears users of Mongoose have a similar issue linkedin/dustjs#487. 

I've worked around it using a small wrapper class like so (perhaps not the best approach, but the simplest one I've found so far):

``` javascript
function ViewModel(instance) {
  // extract POJO version for Dust template
  _.assign(this, instance.dataValues);
}
```

Which works for all single level sequelize instances.

However, if I've got something like:

``` javascript
db.Hello
  .find({ where: { foo: bar }, include: [ db.World ] })
  .success(function (hello) {
    res.render('hello', { hello: new ViewModel(hello) });
  })
  .error(next);
```

It seems the second level members under `dataValues`, such as `hello.worlds`, are not POJO's. I can get around this with `JSON.parse(JSON.stringify(...))`, but that seems a bit much.

Is there a simpler way to get a the raw data values from nested instances?

**Comment by mountHouli** [comment]
I just started using/learning Sequelize.  This is great, thanks!!!
