### ISSUE TITLE
Add a way to hide certain properties before or when calling toJSON

### ISSUE THREAD

**Issue by oleduc** [sequelize/sequelize#2132]
Hi,
This is a feature request to add a way to hide certain properties when sending a query result as a response.

Right now, it is necessary to manually clean up the response data before sending it to client. Which means it is necessary to track usage of associations and clean them appropriately.
## Problematic situation example:

If we have a user model with a password that should never be sent to the front-end, and this user is associated with another model.
### User model

``` javascript
var User= sequelize.define("User", {
        id: {type:DataTypes.INTEGER,primaryKey: true,autoIncrement: true},
        name: DataTypes.STRING,
        password: DataTypes.STRING
    }, {
        classMethods: {
            associate: function(models){
                User.hasMany(models.Conversation);
            }
        }
    });
```
### Associated model

``` javascript
var Associated =  sequelize.define("Associated ", {
        id : {type: DataTypes.INTEGER,primaryKey: true,autoIncrement: true},
        someProperty: DataTypes.STRING
    },{
        classMethods:{
            associate: function(models) {
                Associated .hasMany(models.User);
            }
        }
    });
```
### Controller

``` javascript
var User= require('user');
var Associated = require('associated');

function getUser(req,res){
    User.find({where:{id:req.body.id}}).success(function(user){
         //Must remove password field before returning and cannot use setters if setter hashes passwords
         delete user.dataValues.password;
         res.json(200,user);
    });
}

function getAssociated (req,res){
    Associated.find({where:{id:req.body.id},include[User]}).success(function(associated){
         //Cleanup associated users before responding
        associated.users.forEach(function(user){
             delete user.dataValues.user;
        });
        res.json(200,associated);
    });
}
```

As you can see, this isn't a very elegant solution, and having to rely on utility functions is not better.
## Proposed solutions

A way to specify secret properties.

``` javascript
var User= sequelize.define("User", {
        id: {type:DataTypes.INTEGER,primaryKey: true,autoIncrement: true},
        name: DataTypes.STRING,
        password: DataTypes.STRING
    }, {
        classMethods: {
            associate: function(models){
                User.hasMany(models.Conversation);
            }
        },
        privateColumns:['password']
    });
```

A way to hook into or override toJson for this specific model.

``` javascript
var User= sequelize.define("User", {
        id: {type:DataTypes.INTEGER,primaryKey: true,autoIncrement: true},
        name: DataTypes.STRING,
        password: DataTypes.STRING
    }, {
        classMethods: {
            associate: function(models){
                User.hasMany(models.Conversation);
            }
        },
        instanceMethods: {
             toJson: {
                 delete this.dataValues.password;
                 return JSON.stringify(this.dataValues);
            }
        }
    });
```

I will gladly add it myself if the proposition if accepted.

Thank you!

**Comment by vhmth** [comment]
@oleduc this method of overriding the `toJSON` instance method is great if you are able to throw away that instance quickly after calling this method, but it's bad if you need to reuse it. If you `delete` on a value in `dataValues` like this:

```
toJSON: function () {
  var repr = this.dataValues;
  repr.derived_prop = { hello: 'world' };
  delete repr.password;
  return repr;
}
```

You have now added `derived_prop` to the model instance object and deleted `password` from it. So if you reuse that instance, you have to be careful to not shoot yourself in the foot (doing an `update` or other derived instance methods from then on).

A good workaround is to use Underscore's [clone](http://underscorejs.org/#clone) method.

**Comment by mauris** [comment]
While this is an amazing solution, it doesn't work for models that were `include`-d.

**Comment by leodutra** [comment]
Solved this by using password getter to return '...' and am using a raw query to get user password... taking care with injection.

*Please notify me, whenever a consistent solution is found.*

**Comment by leodutra** [comment]
@mauris is there a way to define  a default scope hiding password?

**Comment by mauris** [comment]
yes. default scope is defined on the documentation: http://docs.sequelizejs.com/manual/tutorial/scopes.html

rather than hiding certain attributes, you need to specify which scopes you want to retrieve.

**Comment by leodutra** [comment]
@mauris omg... I saw that a while ago. Bad memory. I think this is a great
approach. A last resort would be create a hasOne password table...

Any other method?

**Comment by leodutra** [comment]
@mauris for the scope alternative, are you using a hasOne relationship with a password table? I could not define an attribute for just one scope.

**Comment by leodutra** [comment]
Found another solution:
```
     get() {
        return () => this.getDataValue('password');
      }
```
Returning a function and not a value from `user.password`.

The **pro** part of it is the explicit need for `password()` call.
The **con** is not known.

**Comment by arivia** [comment]
I wanted to hide certain attributes only when the data was sent back to the client while having access to the attributes on the instance of the model.

The code below worked for me.

**user.model.js**
```
const Sequelize = require('sequelize')
const Model = Sequelize.Model

const PROTECTED_ATTRIBUTES = ['password', 'token']

class User extends Model {
  toJSON () {
    // hide protected fields
    let attributes = Object.assign({}, this.get())
    for (let a of PROTECTED_ATTRIBUTES) {
      delete attributes[a]
    }
    return attributes
  }
}

User.init({
  email: Sequelize.STRING,
  firstName: Sequelize.STRING,
  lastName: Sequelize.STRING,
  password: Sequelize.STRING,
  token: Sequelize.STRING
},
{
  sequelize,
  modelName: 'user',
})

module.exports = User
```

**Comment by arivia** [comment]
The code below worked for me. We wanted access to the instance attributes at runtime but remove them before sending the data to the client.

**user.model.js**
```
const Sequelize = require('sequelize')

const PROTECTED_ATTRIBUTES = ['password', 'token']

const Model = Sequelize.Model

class User extends Model {
  toJSON () {
    // hide protected fields
    let attributes = Object.assign({}, this.get())
    for (let a of PROTECTED_ATTRIBUTES) {
      delete attributes[a]
    }
    return attributes
  }
}

User.init({
  email: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    validate: {
      isEmail: true
    }
  },
  password: {
    type: Sequelize.STRING,
    allowNull: false
  },
  token: {
    type: Sequelize.STRING(16),
    unique: true,
    allowNull: false
  },
},
{
  sequelize,
  modelName: 'user'
})

module.exports = User
```
