### ISSUE TITLE
Find Response With Include Contains Join Table

### ISSUE THREAD

**Issue by lsiv568** [sequelize/sequelize#2143]
I am using the latest version, `v2.0.0-dev12`, and when I perform a `find` with an include the returned JSON contains the join table.  Based on #1468 I was under the impression that this was no longer the default behavior.  I have a comment at the bottom of issue #1468 which includes more detailed information.  Any idea why this is happening?

**Comment by Anaphase** [comment]
Thank you jesus. Is this documented anywhere in the documentation? It took me forever to track this down!

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/en/latest/docs/associations/#belongs-to-many-associations

> With Belongs-To-Many you can query based on through relation and select specific attributes. For example using findAll with through

```
User.findAll({
  include: [{
    model: Project,
    through: {
      attributes: ['createdAt', 'startedAt', 'finishedAt'],
      where: {completed: true}
    }
  }]
});
```

**Comment by agchou** [comment]
How would this work in N:M (2x belongsToMany) associations? Include does not work but I'm guessing you could pass something similar into user.getProjects({ through: { attributes: ['something'] } })?

**Comment by kevinvugts** [comment]
@agchou I totally agree with you. I am currently in the same situation where I use the provided getters and setters from Sequelize but its returning the containing join table as well.

**Comment by abhi5658** [comment]
@kevinvugts I think you are placing the attributes at wrong place and also making the wrong updates in code as required by the solution.
You need to resepecify the attributes at the model level and then make the table attributes as none
````
User.findAll({
  include: [{
    model: Project,

    through: 'JoinTableAlias' /// only if exist
    as: 'associationAlias' // only if exist
    
    // attributes needed from Project table
    attributes: ['createdAt', 'startedAt', 'finishedAt'],
    
    through: { // through again doesn't create any issue
      attributes: [], // this helps removing the join table in returned data
      where: {completed: true}
    }
  }]
});
```

**Comment by GhettoBurger996** [comment]
hey @abhi5658  having similar issues with user, group and user_group relation Code below returns a pretty the join table object, as well, nothing in the documentation as far as I'm aware that addresses this issue, so followed your code example.
      
```
const usersInGroups = await user.findAll({
        where: { uuid },
        attributes: ["uuid", "username", "fullName", "phoneNumber"],
        include: [
          {
            model: group,
            attributes: ["uuid", "title"],

            // remove join table from object
            through: "user_group",
            through: {
              attributes: [],
              where: { completed: true },
            },
          },
        ],
        required: true,
      });
```
The results still return the join table, the result I'd like is for the final object user_group to not be returned. Any updated regarding the issue ?
```
"uuid": "1bd93d74-b204-4098-a314-dbab621b5621",
        "username": "joey_ctr",
        "fullName": "Joey",
        "phoneNumber": "09456897825",
        "groups": [
            {
                "uuid": "13f05c257-fe42-4c4a-9570-a35a228b3200001",
                "title": "admin",
                "user_group": {
                    "uuid": "323af060-ada4-4323-a112-e60d10761545",
                    "userUuid": "1bd93d74-b204-4098-a314-dbab621b5621",
                    "groupUuid": "13f05c257-fe42-4c4a-9570-a35a228b3200001",
                    "author": "ctr",
                    "createdAt": "2021-04-19T12:01:40.470Z",
                    "updatedAt": "2021-04-19T12:01:40.470Z"
                }
```
