### ISSUE TITLE
How to do MATCH(col1, col2) AGAINST('query')?

### ISSUE THREAD

**Issue by santialbo** [sequelize/sequelize#2146]
I would like to translate the following query 

``` SQL
SELECT * FROM assets WHERE companyId = XXX AND MATCH(filename) AGAINST('YYY')
```

into a `Model.findAll` query object but I haven't found the way of putting the `MATCH(filename) AGAINST('YYY')` part inside the `where` object:

``` js
Asset.findAll({
  where: sequelize.and({
    companyId: XXX
  }, ???)
})
```

For this particular case it needs to be inside the `where` object (it's part of a larger library that builds the queryOptions incrementally). Any hints?

Thanks

**Comment by tejalshah84** [comment]
Hi guys,

Working on a school project, trying to implement a text search function but am stuck. Not sure how MATCH AGAINST works in sequelize.

Two questions fundamentally:

1) How do you do case insensitive string matching? So if i want findAll to return a column that contains either %hello% or %HELLO%, how does sequelize support this?

2) How do I write a where clause that has multiple $Like statements but the number of $like statements is dependent on how long the search text is. For example: if I search "How are you",
I would like to return rows that have text $like %How% OR $like %are% OR $like %you%. So basically its a combination of $like and $in (inclusive OR).

Not clear from above explanation how MATCH AGAINST works in sequelize. Would it be:

searchtxt = ['%HOw%','%Are%','%you%'];

return X.findAll({
    where: {
       ['MATCH(column_name) AGAINST(?)', searchtxt ]
  })

Can searchtxt be an array of the individual words in the search text?


Thanks for your help.

**Comment by santialbo** [comment]
@tejalshah84 the search text should be the query itself i.e. 'how are you'. That's the nice thing about full text search, that you don't need to do any of that.

If, on the other hand you really want to do the combination of `$like` you can also do the following (from the [docs](http://docs.sequelizejs.com/en/latest/docs/querying/#operators))

```
$iLike: { $any: ['how', 'are', 'you']}
```

**Comment by tejalshah84** [comment]
@santialbo Thank you for the help. I did exactly the same but its not working. Its giving me a 500 error

where: {
     chatmessage: {
	$iLike: { $any: arrayOfStrings }
      },
      $or: [{chatauthor: currUser}, 
	      {chattarget: currUser}
}

**Comment by lsycxyj** [comment]
@santialbo How can I order by the relevance of "match... against " with Sequelize?

**Comment by heisenme** [comment]
@tejalshah84 I have the same question, did you fixed? can you tell me your resolve

**Comment by jgentes** [comment]
This solution unfortunately no longer works: `Unhandled rejection Error: Support for literal replacements in the `where` object has been removed.`

**Comment by knoxcard** [comment]
I am working with a table of 12,000+ stores and searching columns such as name, city, state, and zip and the search is taking 4 to 10 second using LIKE with an index.  I am guess that match will be in the millisecond range?  Seconds are too long!! lol

**Comment by knoxcard2** [comment]
```
ar whereAnd = []
			// console.log('params: ' + params)
			whereAnd.push(
				type.literal('MATCH(' + 'city, state' + ') AGAINST(:search_query)')
			)
			whereAnd.push({
				menu_enabled: 'Y'
			})
			// console.log(JSON.stringify(whereAnd, null, 4))
			var search_params = {	
				where: whereAnd,
				replacements: {
					search_query: '+' + res_query + '*',
					search_params: 'city, state',
					type: type.QueryTypes.SELECT
				},
				attributes: [
					'id',
					'name',
					'url_slug',
					'city', 
					'state',
					'zip',
					'blob'
				],
				offset: start,
				limit: limit,
				raw: true
				// order: [
				// 	type.literal('exact_like_match DESC')
				// ]
			}
			// console.log(JSON.stringify(search_params, null, 4))
			// if(query.includes('-') && lat && lng) {
			// search_params['order'] = [
			// 	type.literal('exact_like_match DESC, distance ASC')
			// ]
			// }
			dispensary.findAndCountAll(search_params).then(disp_rx => {
				disp_rx.rows.forEach((disp_rec, index) => {
					delete disp_rx.rows[index].menu_categories
					delete disp_rx.rows[index].menu_items
					delete disp_rx.rows[index].blob
					/*if(disp_rec.blob.src_logo_url)
						disp_rx.rows[index].logo = disp_rec.blob.src_logo_url */
					disp_rx.rows[index].url_path = disp_rec.city.toLowerCase().replace(/\s/g, '-').replace(/\//g,'-').replace(/\\/g, '-') + '/' + disp_rec.url_slug
					disp_rx.rows[index].country = disp_rec.country
				})
				disp_rx.query = res_query
				app.get('functions').stringify(disp_rx)
				cb(disp_rx)
			})
```

**Comment by alirizwan** [comment]
> This will work...
> 
> ```
> var whereAnd = [],
>   columns = 'city, state'
> whereAnd.push(
> 	type.literal('MATCH(' + columns + ') AGAINST(:search_query)')
> )
> whereAnd.push({
> 	menu_enabled: 'Y'
> })
> var search_params = {	
> 	where: whereAnd,
> 	replacements: {
> 		search_query: '+' + res_query + '*',
> 		type: type.QueryTypes.SELECT
> 	},
> 	offset: start,
> 	limit: limit,
> 	raw: true
> }
> model.findAndCountAll(search_params).then(disp_rx => {
> 	cb(disp_rx)
> })
> ```

This won't work if you have your field names in the db are different from model names. i.e. if a column name is first_name in db but in model it's firstName, it won't work.

**Comment by alirizwan** [comment]
Following is a safe and slightly better way to do this.


```
var whereAnd = { menu_enabled: 'Y', [Op.and]: [type.literal('MATCH(' + columns + ') AGAINST(:search_query)')] },
  columns = 'city, state'

var search_params = {	
	where: whereAnd,
	replacements: {
		search_query: '+' + res_query + '*',
		type: type.QueryTypes.SELECT
	},
	offset: start,
	limit: limit,
	raw: true
}
model.findAndCountAll(search_params).then(disp_rx => {
	cb(disp_rx)
})
```
