### ISSUE TITLE
Query "attributes" options still selects associations fields when used with include.

### ISSUE THREAD

**Issue by oleduc** [sequelize/sequelize#2147]
Hello,

I'm not sure if this is an intended behavior, but when I specify attributes to be selected in conjunction with the include options for associates, the query still pulls all the fields for a given association, which in turn prevents me from using aggregation to count associations without getting them.

This is critical for performance.

This code:

``` javascript
User.findAll({
    attributes: ['Users.id','QuestionAnswers.id'],
    include:[ QuestionAnswers]}).success(function(userArray) {
        console.log(userArray);
});
```

Is currently producing this query:

``` SQL
SELECT "Users"."id", "QuestionAnswers"."id", "QuestionAnswers"."id" AS "QuestionAnswers.id", "QuestionAnswers"."content" AS "QuestionAnswers.content", "QuestionAnswers"."createdAt" AS "QuestionAnswers.createdAt", "QuestionAnswers"."updatedAt" AS "QuestionAnswers.updatedAt", "QuestionAnswers"."QuestionId" AS "QuestionAnswers.QuestionId", "QuestionAnswers"."QuestionOptionId" AS "QuestionAnswers.QuestionOptionId", "QuestionAnswers"."UserId" AS "QuestionAnswers.UserId" 
FROM "Users" 
LEFT OUTER JOIN "QuestionAnswers" AS "QuestionAnswers" ON "Users"."id" = "QuestionAnswers"."UserId";
```

But in reality, it should produce that query:

``` SQL
SELECT "Users"."id", "QuestionAnswers"."id" 
FROM "Users" 
LEFT OUTER JOIN "QuestionAnswers" AS "QuestionAnswers" ON "Users"."id" = "QuestionAnswers"."UserId";
```

This seems like a pretty major bug to me.
Thanks you!

**Comment by capiot-shobhit** [comment]
I have used Alias-
`User.hasMany(Address, { as: 'address' });`
but when i do `User.findOne({ where: {id: 1}, include: [ {model:Address , attributes:['city']}]})`.
I get an error "address is associated to user using an alias. You must use the 'as' keyword to specify the alias within your include statement." . When I use `User.findOne({ where: {id: 1}, include: [ {as:'address' , attributes:['city']}]}) `
I get an error: Cannot read property 'getTableName' of undefined
