### ISSUE TITLE
Can I set protected columns?

### ISSUE THREAD

**Issue by VictorQueiroz** [sequelize/sequelize#2156]
That's what I used in my model to protect this field. There is some better way for unlisting password and setting some protected columns?

http://pastebin.com/EVMeVuu8

**Comment by arivia** [comment]
I wanted to hide certain attributes only when the data was sent back to the client while having access to the attributes on the instance of the model.

The code below worked for me.

**user.model.js**
```
const Sequelize = require('sequelize')
const Model = Sequelize.Model

const PROTECTED_ATTRIBUTES = ['password', 'token']

class User extends Model {
  toJSON () {
    // hide protected fields
    let attributes = Object.assign({}, this.get())
    for (let a of PROTECTED_ATTRIBUTES) {
      delete attributes[a]
    }
    return attributes
  }
}

User.init({
  email: Sequelize.STRING,
  firstName: Sequelize.STRING,
  lastName: Sequelize.STRING,
  password: Sequelize.STRING,
  token: Sequelize.STRING
},
{
  sequelize,
  modelName: 'user',
})

module.exports = User
```

**Comment by arivia** [comment]
I wanted access to the instance attributes at runtime but remove them before sending the data to the client. Check out this issue for the solution.
https://github.com/sequelize/sequelize/issues/2132
