### ISSUE TITLE
Including pattern convert exception

### ISSUE THREAD

**Issue by bitliner** [sequelize/sequelize#217]
It seems that Sequelize doesn't do pattern convert exception.
For example: 
- i have a User model that have a primaryKey attribute (for example email)
- if i try to save an instance with duplicate value of the primaryKey attribute i get the error "Duplicate entry 'poi' for key 'PRIMARY'"
- may be a message as "User with this email already exist" better?

With pattern convert exception i refer to throw error message that is adapt to upper layer than sql layer.
I think that it let to write less code to handle error message. I will try to update the code of Sequelize on this way.

What do you think about it?

**Comment by BridgeAR** [comment]
I guess this is a bit outdated and should be closed @mickhansen @janmeier
