### ISSUE TITLE
Provide a way to default `id` to INTEGER UNSIGNED

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#2179]
There's no reason for the id primary key to be signed. I understand that supports this now by explicitly adding the id attribute with a type and sequelize defaults to signed integers for backwards compatibility.

But one shouldn't have to explicitly go and add a custom id attribute to every single model in a new project just to coax a sane database schema out of sequelize.

Could we have a global setting in Sequelize() like the `define.timestamps` option that makes all model ids default to unsigned. This can be used in new projects and projects that feel like instead tweaking old models and migrations that haven't been switched to unsigned yet as signed.

**Comment by wmulligan** [comment]
+1

**Comment by ataulmustafa** [comment]
+1

**Comment by doublesharp** [comment]
@mickhansen Is this still on the roadmap?

**Comment by felixfbecker** [comment]
@doublesharp If it is not assigned a milestone, it is not on the roadmap and will be implemented if someone picks it up and does a PR

**Comment by doublesharp** [comment]
@felixfbecker Do you have an opinion on how it should be implemented? I just ran a quick hack and got it to work pretty quickly by adding the following option to `sequelize.define()`.

```
module.exports = function Model(sequelize, DataTypes) {
  const User = sequelize.define(
    'user',
    { name: { type: DataTypes.STRING } },
    {
      idType: DataTypes.INTEGER.UNSIGNED,
    }
  );
  return User;
}
```

In the Model I added the option to the defaults:

```
 idType: DataTypes.INTEGER,
```

And in `addDefaultAttributes()`:

```
    head = {
      id: {
        type: this.options.idType,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: true
      }
    };
```

**Comment by doublesharp** [comment]
I was also about to use `DataTypes.BIGINT.UNSIGNED` on MariaDB. Setting the `type` in the Model options seemed to be the most flexible.

**Comment by felixfbecker** [comment]
Imo an option on the model is quite useless because then you could just specify the id attribute yourself?

**Comment by doublesharp** [comment]
This would provide a shorthand way to do it, similar to how you can specify all the column names with underscores or use `options.underscored`. It's longer because you have to define it as the `primaryKey` with `autoIncrement`. Definitely not a huge deal, but this these are equivalent definitions:
 
```
module.exports = function Model(sequelize, DataTypes) {
  const User = sequelize.define(
    'user',
    {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
    },
    name: { type: DataTypes.STRING },
    {}
  );
  return User;
}
``` 

vs

```
module.exports = function Model(sequelize, DataTypes) {
  const User = sequelize.define(
    'user',
    { name: { type: DataTypes.STRING },
    { idType: DataTypes.INTEGER.UNSIGNED, }
  );
  return User;
}
```

I did find another hack-y way to do this using the existing codebase as well that adds a single line:

```
module.exports = function Model(sequelize, DataTypes) {
  const User = sequelize.define(
    'user',
    { name: { type: DataTypes.STRING },
    {}
  );
  // change id type here
  User.attributes.id.type = DataTypes.INTEGER.UNSIGNED;
  return User;
}
```

I don't actually need this functionality so I'll just leave this here in case anyone finds it useful.
