### ISSUE TITLE
Many-to-many problem

### ISSUE THREAD

**Issue by eveiga** [sequelize/sequelize#218]
Hello, I'm getting a strange problem, defining a many-to-many relation between to models (the backend is sqlite3).

This is my code:

https://gist.github.com/3150943

And I'm receiving this error:

Error: Invalid DAO definition. Only one autoincrement field allowed.

Can you please advise me on this one?

Best regards

**Comment by TangMonk** [comment]
still problem 

sequelize@2.0.0-rc7

sqlite3@3.0.4
