### ISSUE TITLE
Method to count associations?

### ISSUE THREAD

**Issue by takempf** [sequelize/sequelize#222]
Is there currently any way to use `.count()` with associations? I'm constructing an API endpoint and I'd like to be able to return a total items count while doing a `.getAssociations()` call with a limit.

**Comment by dmbrowne** [comment]
this  doesn't seem to work for me
```
models.Post
		.findAll({
			attributes: [
				models.sequelize.col('Post.*'), 
				[models.sequelize.fn('COUNT', models.sequelize.col('PostComment.id')), 'PostCount']
			],
			include: [models.PostComment]
		})
```

I get the error:
`missing FROM-clause entry for table "PostComment"`

what am i doing wrong?

**Comment by corbanb** [comment]
Just stumbled on this thread and when trying to do this in 2.0.5

```javascript
		var query = {
				where: { 
					region: region,
					createdAt: { between: [start, end] }
				},
				include: [
            		{ model: abe.db.Vote }
				],
				attributes: ['Item.*', 'Vote.*', [abe.db.sequelize.fn('COUNT', abe.db.sequelize.col('Vote.id')), 'VoteCount']],

			};

		abe.db.Item.findAll(query)
```

I get the error:

```
SequelizeDatabaseError: ERROR:  missing FROM-clause entry for table "Vote"
LINE 1: SELECT "Item"."id", "Item".*, "Vote".*, COUNT("Vote"."id")...
```

Did something change?

**Comment by mickhansen** [comment]
@corbanb Can you post the full SQL?

**Comment by corbanb** [comment]
@mickhansen this is what i got from the logs.

```
SELECT "Item"."id", "Item".*, "Vote".*, COUNT("Vote"."id") AS "VoteCount", "Votes"."id" AS "Votes.id", "Votes"."type" AS "Votes.type", "Votes"."scope" AS "Votes.scope", "Votes"."region" AS "Votes.region", "Votes"."createdAt" AS "Votes.createdAt", "Votes"."updatedAt" AS "Votes.updatedAt", "Votes"."ItemId" AS "Votes.ItemId", "Votes"."UserId" AS "Votes.UserId", "Votes"."CompetitorId" AS "Votes.CompetitorId" FROM "Items" AS "Item" LEFT OUTER JOIN "Votes" AS "Votes" ON "Item"."id" = "Votes"."ItemId" WHERE "Item"."region" = 'east' AND "Item"."createdAt" BETWEEN '2015-05-27T15:30:00+00:00' AND '2015-05-27T18:00:00+00:00';
```

**Comment by corbanb** [comment]
@mickhansen did you have any thoughts on this. sorry to bother. I am just not sure how this would not be generating the correct SQL based on the examples.

**Comment by mickhansen** [comment]
You don't need `'Vote.*'` i think, you should use `attributes` on the `include` instead if you need to filter.

**Comment by corbanb** [comment]
Thanks @mickhansen that is an interesting way to achieve this goal.

I have tried this a few ways now such as:

```javascript

var query = {
                where: { 
                    region: region,
                    createdAt: { between: [start, end] }
                },
                include: [
                    { 
                    	model: abe.db.Vote, 
                    	attributes: [[abe.db.sequelize.fn('COUNT', abe.db.sequelize.col('Votes.id')), 'VoteCount']]  
                    }
                ]

            };

abe.db.Item.findAll(query)

```

with the error of: 

```
SequelizeDatabaseError: ERROR:  column "Item.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "Item"."id", "Item"."region", "Item"."timezone", "...
```

And by trying:

```javascript

var query = {
                where: { 
                    region: region,
                    createdAt: { between: [start, end] }
                },
                include: [
                    { model: abe.db.Vote  }
                ],
                attributes: ['Item.*', [abe.db.sequelize.fn('COUNT', abe.db.sequelize.col('Votes.id')), 'VoteCount']],

            };
abe.db.Item.findAll(query)

```

with the error of:

```
SequelizeDatabaseError: ERROR:  column "Item.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "Item"."id", "Item"."id", COUNT("Votes"."id") AS "V...
```

Is this how you are suggesting this kind of thing be done?

**Comment by mickhansen** [comment]
`Item.*` might not work either, but you're doing an aggregate so you have to abide by the PG aggregate rules :)

**Comment by corbanb** [comment]
Hi mick, Thanks again. I am very unsure as to what you are referring to here. Is there anymore info you can provide?

**Comment by corbanb** [comment]
I was able to get a little closer I believe with:

```javascript
var query = {
                where: { 
                    region: region,
                    createdAt: { between: [start, end] }
                },
                include: [
                    { model: abe.db.Vote }
                ],
                logging: abe.logs.info,
                attributes: [
                				'Item.*',
                    			[abe.db.sequelize.fn('COUNT', abe.db.sequelize.col('ItemId')), 'VoteCount']
                    		],
                 group: 'Item.id'
            };
abe.db.Item.findAll(query)
```

```sql

SELECT "Item"."id", "Item".*, COUNT("ItemId") AS "VoteCount", "Votes"."id" AS "Votes.id", "Votes"."type" AS "Votes.type", "Votes"."scope" AS "Votes.scope", "Votes"."region" AS "Votes.region", "Votes"."createdAt" AS "Votes.createdAt", "Votes"."updatedAt" AS "Votes.updatedAt", "Votes"."ItemId" AS "Votes.ItemId", "Votes"."UserId" AS "Votes.UserId", "Votes"."CompetitorId" AS "Votes.CompetitorId" 
FROM "Items" AS "Item" 
LEFT OUTER JOIN "Votes" AS "Votes" ON "Item"."id" = "Votes"."ItemId" 
WHERE "Item"."region" = 'east' 
AND "Item"."createdAt" BETWEEN '2015-06-02T15:30:00+00:00' AND '2015-06-02T18:00:00+00:00' GROUP BY Item.id;

```

But still can't get around the error of:

```
SequelizeDatabaseError: ERROR:  missing FROM-clause entry for table "item"
LINE 1: ...00+00:00' AND '2015-06-02T18:00:00+00:00' GROUP BY Item.id;
```

**Comment by mickhansen** [comment]
You'll want `group: '"Item"."id"'` since you have cased tables. You can probably just do `group: ['id']` though.

**Comment by corbanb** [comment]
Awesome @mickhansen . That got things close but its not actually counting the votes. Its just counting the single vote as seen here:

```javascript

var query = {
                where: { 
                    region: region,
                    createdAt: { between: [start, end] }
                },
                include: [
                    { 
                    	model: abe.db.Vote,
                    	attributes: [
                    			[abe.db.sequelize.fn('COUNT',  abe.db.sequelize.col('Votes.ItemId')), 'VoteCount']
                    		],
                    }
                ],
                group: ['"Item"."id"', '"Votes"."id"', '"Votes"."ItemId"'],
                logging: abe.logs.info
            };
abe.db.Item.findAll(query)
```


Output:

```
"Votes": [
   {
      "VoteCount": "1"
   },
   {
      "VoteCount": "1"
   },
   {
      "VoteCount": "1"
   }
]
},
```

I moved it out to the main attributes also but it still only gets a single vote and shows 3 objects under it.

**Comment by mickhansen** [comment]
@corbanb You need to work with your group statement then, you are grouping on Votes.id atm, that won't work, you need to group on a common factor, likely Item.id or Votes.ItemId

**Comment by osteenbergen** [comment]
@mickhansen I have tried the solution from @corbanb but the grouping isn't possible in at least Postgres as sequelize always adds the primary column from the included model resulting in an error. 

Something like:
```sql
SELECT "Run"."id", "messages"."id", COUNT("messages"."id") AS "count" 
FROM "Runs" AS "Run" 
  LEFT OUTER JOIN "RunMessages" AS "messages" ON "Run"."id" = "messages"."runid"
WHERE "Run"."id" = '27ab0639-272e-4e7e-8b3e-b4650cf17d98' 
GROUP BY "Run"."id";
```
I managed to get a __solution__ working when setting ```include.attributes``` to ```[]```
```javascript
return this.db.model("Run").findAll({
  "where" : {
    "id":req.params.runid
  },
  "attributes": 
    Object.keys(this.db.model("Run").attributes).concat([
      [sequelize.fn('COUNT',sequelize.col('messages.id')),"count"]
    ]
  ),
  "include":[
      {
        "model": this.db.model("RunMessage"),
        "as" : "messages",
        "attributes":[]
      }
  ],
  "group":['"Run.id"'],
  "logging": console.log
});
```

I would like to have ```attributes``` simpler
```javascript
['Run.*', [sequelize.fn('COUNT',sequelize.col('messages.id')),"count"]]
```
but this doesn't work but it does generate the correct query:
```sql
SELECT "Run"."id", "Run".*, COUNT("messages"."id") AS "count" 
FROM "Runs" AS "Run" 
   LEFT OUTER JOIN "RunMessages" AS "messages" ON "Run"."id" = "messages"."runid" 
WHERE "Run"."id" = '27ab0639-272e-4e7e-8b3e-b4650cf17d98' 
GROUP BY "Run"."id";
```
The result is just the ```count``` column
```json
[{"count":4}]
```

**Comment by mickhansen** [comment]
You can try adding `raw: true` @osteenbergen

**Comment by diosney** [comment]
Maybe can be added a new association method like `.countAssociation?`.

That way the overall style is maintained while providing an easy way to get the count without fetching the items.

**Comment by mickhansen** [comment]
`countAssociations` exists for `hasMany`. Not sure if it exists for `belongsToMany` yet

**Comment by diosney** [comment]
@mickhansen Good to know!!! I didn't!!!

It seems that it need to be added to http://docs.sequelizejs.com/en/latest/api/associations/has-many

Coincidentally, `countAssociations` in `hasMany` was exactly what I needed, ha!

And what do you think about the second option? That will need to be done on a major version since will change the current API. 

Thanks

**Comment by mickhansen** [comment]
Personally not a huge fan of chaining-style APIs

**Comment by chiefGui** [comment]
I still couldn't get the count of associated model, even reading everything in here. Probably I am missing something.

This is my code:

```js
Post.findAll({
  where: {slug: postSlug},
  group: ['post.id', 'posts_votes.id'],
  attributes: [
    'id',
    [
      sequelize.fn('COUNT', sequelize.col('posts_votes.postId')), 'votes'
    ]
  ],
  include: [{
    model: PostsVotes,
    attributes: []
  }]
})
```

And the output of `votes` is `1`:

![image](https://cloud.githubusercontent.com/assets/1330257/12996996/4b0b92c4-d11c-11e5-936b-a8be4ec082a8.png)


and for that `postId` I have three records instead of `1`:

![image](https://cloud.githubusercontent.com/assets/1330257/12996949/dc3eff98-d11b-11e5-8276-eafcc3996f77.png)

The query is:

```sql
SELECT "post"."id", COUNT("posts_votes"."postId") AS "votes"
FROM "posts" AS "post"
LEFT OUTER JOIN "posts_votes" AS "posts_votes"
ON "post"."id" = "posts_votes"."postId"
WHERE "post"."slug" = 'testing-post'
GROUP BY "post"."id", "posts_votes"."id";
```

What am I missing here?

**Comment by janmeier** [comment]
@chiefGui You shouldn't group by post_votes.id - that in effect creates three groups:

| post_votes.id | postid | count |
| 1 | 1 | 1 |
| 2 | 1 | 1 |
| 3 | 1 | 1 |

Since you are not selecting post_votes.id, you only get the first row

**Comment by chiefGui** [comment]
Probably because it was late, but yesterday without `posts_votes.id` in the `group` property was throwing me an error. For sure I was doing something wrong and can't remember what.

Thanks anyway, @janmeier—it worked!

**Comment by janmeier** [comment]
@chiefGui - maybe you hint the famous postgres "column must appear in a group by or be used in an aggregate" error :)?

**Comment by chiefGui** [comment]
Exactly, @janmeier. What's that?

**Comment by janmeier** [comment]
See http://stackoverflow.com/questions/18061285/postgresql-must-appear-in-the-group-by-clause-or-be-used-in-an-aggregate-functi and other s


Basically, when you start grouping, any attribute you select must either be part of the group or have an aggregate function of applied to it. When you group by post.id, you will get several different values for post_votes.id - but since you are grouping, only one value can be returned. Therefore you med to either tell postgres to group by that attribute (which would be wrong), aggregate om it, or remove it as in your case. 
Mysql simply ignores this problem by just returning the first value, while postgres actually makes you aware of the potential error

**Comment by chiefGui** [comment]
Oh, I feel more confident now that I know Postgres do cares about errors, at least more than MySQL, lol.

Thank you for the explanations, @janmeier—it was very helpful!

**Comment by juhaelee** [comment]
I'm trying to execute similar code to @chiefGui using the following query:
```javascript
Comment.findAll({
  where: {slug: postSlug},
  group: ['Comment.id'],
  attributes: [
    'id',
    [
      sequelize.fn('COUNT', sequelize.col('votes.CommentId')), 'votes'
    ]
  ],
  include: [{
    model: Vote,
    attributes: []
  }],
   limit 100,
   raw: true
});
```

This is the query I'm getting, however:
```sql
SELECT "Comment".* FROM (
   SELECT "Comment"."id", COUNT("votes"."CommentId"), "Comment"."count" FROM "Comments" AS "Comment" 
   WHERE ("Comment"."deletedAt" IS NULL AND ("Comment"."createdAt" >= '1970-01-01 00:00:00.000 +00:00')) 
   GROUP BY "Comment"."id" 
   ORDER BY "Comment"."createdAt" DESC LIMIT 100
) AS "Comment"
LEFT OUTER JOIN "Votes" AS "Votes" ON "Comment"."id" = "Votes"."CommentId" 
ORDER BY "Comment"."createdAt" DESC;
```

As you can see, the `GROUP BY` clause as well as the `COUNT` are in the inner `SELECT` when they should be on the outer since `include.attributes = []`. I'm on sequelize 3.23.2 and postgres 9.4.5.

@mickhansen is there a known bug in sequelize or am I doing something wrong here?

**Comment by mickhansen** [comment]
@juhaelee You can try adding `duplicating: false` on the include since it won't generate any rows (we don't currently infer this)

**Comment by juhaelee** [comment]
awesome it worked! thanks @mickhansen

**Comment by AlexNasonov** [comment]
Still have some problems with my code:
```javascript
User.belongsToMany(Role, {through: 'user_roles'});
Role.belongsToMany(User, {through: 'user_roles'});

models.Role.findAll({
                attributes:['name',
                   [models.sequelize.fn('COUNT', models.sequelize.col('users.email')), 'users']
                ],
                include: [{
                    model: models.User,
                    attributes: ['email'],
                    through: {
                        attributes: []
                    },
                    duplicating: false

                }],
                group: ['role.name']
```
I have Postgres and ManyToMany relation. I can't remove `email` attribute, because if i remove it, i get an error from through model: `Unhandled rejection TypeError: Cannot set property 'user_roles' of undefined`.

Without `group: ['role.name']` I get `Unhandled rejection SequelizeDatabaseError: column "role.name" must appear in the GROUP BY...`

If I let it be, it says `column "users.email" must appear in the GROUP BY...`))

If I add "users.email" to group it hits with `Unhandled rejection SequelizeDatabaseError: column "users.user_roles.createdAt"`

**Comment by OKNoah** [comment]
Is this documented anywhere? Really struggling to adapt people's examples from this thread into my own project.

**Comment by felixfbecker** [comment]
There are  `countAssociations()`  methods, see the associations API docs

**Comment by OKNoah** [comment]
@felixfbecker Sorry, I mean is there documentation for the `fn('count')` and `group`, etc.

**Comment by felixfbecker** [comment]
`Sequelize.fn()` is documented. Not sure what you mean by `group`.

**Comment by laurenskling** [comment]
I would love to see a `getAndCountAssociations` as there is `findAndCountAll`
http://docs.sequelizejs.com/en/latest/docs/models-usage/#findandcountall-search-for-multiple-elements-in-the-database-returns-both-data-and-total-count

**Comment by felixfbecker** [comment]
@laurenskling please open a new issue.

**Comment by laurenskling** [comment]
@felixfbecker , will do. To me it seemed the original question was the same as mine.

**Comment by OKNoah** [comment]
@laurenskling Can you link to it?

**Comment by OKNoah** [comment]
@felixfbecker See the comments above where people are discussing group. I don't understand it either which is why I'd like documentation.

**Comment by laurenskling** [comment]
@OKNoah https://github.com/sequelize/sequelize/issues/7045

**Comment by paffare** [comment]
Hi!

I'm having trouble with this counting solution. The code:
```
models.Comment.findAll({
  where: whereOptions,
  attributes: ['id', 'text', [Sequelize.fn('COUNT',` Sequelize.col('votes.up')), [Sequelize.fn('COUNT', Sequelize.col('votes.down')), 'downVotes']],
}).then(() => {
  console.log(comments);
});
```
Works just find, but in my case i include some more models not related to the counting, I'm just receiving one object instead of all of them. Like this:

```
models.Comment.findAll({
  where: whereOptions,
  attributes: ['id', 'text', [Sequelize.fn('COUNT',` Sequelize.col('votes.up'))], [Sequelize.fn('COUNT', Sequelize.col('votes.down')), 'downVotes']],
  include: [Report]
}).then(() => {
  console.log(comments);
});
```
I'll only get the first Report entry even though there are several associated with the Comment. If I remove the counting attributes, all my Report entries are included.

Does anyone recognize this behavior? I can't see what is causing this.

**Comment by juliocanares** [comment]
@paffare you need group by comment id add to your findAll query the following `group: ['id']`

**Comment by mytharcher** [comment]
After read the whole thread and tried many times, my query as below works:

~~~javascript
TagModel.getAll({
  visible: true
}, {
  attributes: {
    include: [
      [fn('COUNT', 'Product.id'), 'number']
    ]
  },
  include: [
    // can't add the where condition below:
    // SequelizeDatabaseError: missing FROM-clause entry for table 'Product';
    // {
    //   association: 'products',
    //   attributes: [],
    //   where: {
    //     enabled: true
    //   }
    // },
    'icon'
  ],
  // when using associated model count,
  // must use group by clause together.
  // when using include for more association,
  // also must use specific model key for
  // grouping.
  group: ['ProductTag.id',/* 'Product.id',*/ 'icon.id']
})
~~~

But still not sure how to add deep where conditions for count.

**Comment by AlekseyPanch** [comment]
Tried to count associations with following code:

**Comment by sasajib** [comment]
I am new to sequelize, found a solution from
[Stackoverflow Post](https://stackoverflow.com/a/36852571/1086183)
`User.findAll({
    attributes: [
        'User.username',
        [sequelize.literal('(SELECT COUNT(*) FROM Posts WHERE Posts.userId = User.id)'), 'PostCount']
    ],
    order: [[sequelize.literal('PostCount'), 'DESC']]
});`

**Comment by AlikRakhmonov** [comment]
model.findAll({
    attributes: {
        include: [[sequelize.fn('COUNT', sequelize.col('comments.postId')), 'commentsCount']]
    },
    include: [{
        model: CommentModel,
        attributes: []
    }],
    group: 'post.id'
});

**Comment by AlikRakhmonov** [comment]
`model.findAll({
    attributes: {
        include: [[sequelize.fn('COUNT', sequelize.col('comments.postId')), 'commentsCount']]
    },
    include: [{
        model: CommentModel,
        attributes: []
    }],
    group: 'post.id'
});`

**Comment by AlikRakhmonov** [comment]
`
model.findAll({
    attributes: {
        include: [[sequelize.fn('COUNT', sequelize.col('comments.postId')), 'commentsCount']]
    },
    include: [{
        model: CommentModel,
        attributes: []
    }],
    group: 'post.id'
});
`

**Comment by lpedromachado** [comment]
> I'd also like to point out that Mick's solution will not do exactly what you expect.
> 
> ```js
> User.findAll({
>   attributes: ['User.*', 'Post.*', [sequelize.fn('COUNT', 'Post.id'), 'PostCount']],
>   include: [Post]
> }
> ```
> 
> Will be escaped incorrectly to `COUNT('Post.id')`, instead of `COUNT(`Post`.`id`)` (making it count the User row as well as NULL values of the Post table).
> 
> The correct query is:
> 
> ```js
> User.findAll({
>   attributes: ['User.*', 'Post.*', [sequelize.fn('COUNT', sequelize.col('Post.id')), 'PostCount']],
>   include: [Post]
> }
> ```

What if I already have a `User` model instance and want to get the number of its associated posts? What is the best way? Do I have to `find` the instance again by its primary key in order to aggregate and count its posts?

**Comment by harpcio** [comment]
I have a lot of problems with PostreSQL vs MySQL compatibility.
This is working for both. Maybe will help someone.

```
let ordersCountSQL = sequelize.dialect.QueryGenerator.selectQuery('orders', {
    attributes: [
        [sequelize.fn('COUNT', sequelize.col('orders.id')), 'orders_count']
    ],
    where: {
        customer_id: {
            [Op.eq]: sequelize.col('Customer.id')
        }
    }
}).slice(0, -1);

let totalPurchaseSQL = sequelize.dialect.QueryGenerator.selectQuery('orders', {
    attributes: [
        [sequelize.fn('SUM', sequelize.col('orders.total')), 'total_purchase']
    ],
    where: {
        customer_id: {
            [Op.eq]: sequelize.col('Customer.id')
        }
    }
}).slice(0, -1);

const customers = await Customer.findAndCountAll({
    attributes: {
        include: [
            [sequelize.literal('(' + ordersCountSQL + ')'), 'orders_count'],
            [sequelize.literal('(' + totalPurchaseSQL + ')'), 'total_purchase'],
        ],
    },
    include: [
        {
            association: 'orders',
            model: Order,
            attributes: [],
        },
    ],
    subQuery: false,
    group: ['Customer.id']
});
```

**Comment by mfauzaan** [comment]
Somehow many of the options does not work for me

Here is my solution which works on sequelize v5.18.4 (postgres)

```
const item = await Item.findAll({
      attributes: ['id','title', [Item.literal('(SELECT COUNT(*) FROM item_requests WHERE item_requests.item_id = "Item"."id")'), 'requestsCount']],
        order: [['id', 'ASC']]
      })
```

Note: issue caused by string quote.

**Comment by Vanguardo66** [comment]
Hi guys.
I want to get all categories and count of the associated posts using below code:

`const categories = await Category.findAll({
        attributes:[[sequelize.fn('COUNT', 'Post.id'), 'PostCount'], 'Category.name','Category.slug','Category.id'],
        include:[Post],
        group: ['Category.name','Category.slug','Category.id']
    });`

This in throwing this:

> Executing (default): SELECT `Category`.`id`, COUNT('Post.id') AS `PostCount`, `Category`.`name`, `Category`.`slug`, `Posts`.`id` AS `Posts.id`, `Posts`.`title` AS `Posts.title`, `Posts`.`slug` AS `Posts.slug`, `Posts`.`introImage` AS `Posts.introImage`, `Posts`.`content` AS `Posts.content`, `Posts`.`categoryId` AS `Posts.categoryId`, `Posts`.`createdAt` AS `Posts.createdAt`, `Posts`.`updatedAt` AS `Posts.updatedAt`, `Posts`.`CategoryId` AS `Posts.CategoryId` FROM `Categories` AS `Category` LEFT OUTER JOIN `Posts` AS `Posts` ON `Category`.`id` = `Posts`.`CategoryId` GROUP BY `Category`.`name`, `Category`.`slug`, `Category`.`id`;
(node:31164) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'nini_db.Posts.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

1- Why it is including every attribute in both tables?
2- How to get it done?

**Comment by manoellribeiro** [comment]
> Somehow many of the options does not work for me
> 
> Here is my solution which works on sequelize v5.18.4 (postgres)
> 
> ```
> const item = await Item.findAll({
>       attributes: ['id','title', [Item.literal('(SELECT COUNT(*) FROM item_requests WHERE item_requests.item_id = "Item"."id")'), 'requestsCount']],
>         order: [['id', 'ASC']]
>       })
> ```
> 
> Note: issue caused by string quote

None of the solutions related here work for me, but this one helped me and I achieved what I wanted. Thank You @mfauzaan

**Comment by Letale-vc** [comment]
Maybe a lot of people are making a request wrong. I hope this helps someone
`const anyNameItem = await model.findAll({
  attributes: [
    'id',
    'Name',
    [model.sequelize.fn('COUNT',model.sequelize.col('ASSOCIATION_MODEL.NAME_COL')),'ANY_NAME_']
  ], // add any attributes if u need and make a subquery
  include: ['ASSOCIATION_MODEL'], // just adding an association
  group: ['model.id', 'association.id'], // add group_by model id and any association id
});`

**Comment by rahathossain690** [comment]
> attributes: [
>         'User.username',
>         [sequelize.literal('(SELECT COUNT(*) FROM Posts WHERE Posts.userId = User.id)'), 'PostCount']
>     ],
For me this worked instead, just a little tweak
```
attributes: [
'User.username',
[sequelize.literal('(SELECT COUNT(*) FROM "Posts" WHERE "Posts"."userId" = User.id)'), 'PostCount']
]
```
