### ISSUE TITLE
createOrFind[AS]?

### ISSUE THREAD

**Issue by Jon889** [sequelize/sequelize#2223]
Is there a better way of adding an association and if it doesn't exist, create it?

Currently I am having to do:

```
 Artist.findOrCreate(artistData, artistData)
.complete(function (err, artist) {
    Album.findOrCreate({'title' : albumName}, albumData)
    .complete(function(err, album) {
        album.setArtist(artist);
    });
});
```

(That's 3 queries to the database)

It would perform one less SQL queries if you could do:

```
Artist.findOrCreate(artistData, artistData)
.complete(function (err, artist) {
    artist.findOrCreateAlbum({'title' : albumName}, albumData)
    .complete(function(err, album) {
         //...
    });
});
```

**Comment by BridgeAR** [comment]
@mickhansen @janmeier is this really something you'd like to support? There are so many open tickets that it's difficult to get a overview and there's still a lot of work for really important things. So I'd recommend closing this and add the label "backlog" or something like that?

**Comment by mickhansen** [comment]
@BridgeAR Perhaps. Hence why it's labeled as a feature request :) I agree there's a lot of open issues, we label as many as possible to make it easy to search for bugs or high priority items.
