### ISSUE TITLE
defaultValue: Sequelize.UUIDV4 not working?

### ISSUE THREAD

**Issue by Pomax** [sequelize/sequelize#2225]
I'm using the following model with a sqlite3 backing:

```
var models = {
    Ink: sequelize.define("Ink", {
      id: { type: Sequelize.UUID, defaultValue: Sequelize.UUIDV4 },
      company: Sequelize.TEXT,
      inkname: Sequelize.TEXT,
      profiles: Sequelize.ARRAY(Sequelize.UUID),
      notes: Sequelize.ARRAY(Sequelize.UUID)
    }),
   ...
};
```

but the following code leads to a record without an autogenerated id:

```
var ink = models.Ink.build({
  company: "a",
  inkname: "b"
});

ink.save().complete(function() {
  console.log(ink.company, ink.inkname, ink.id);
});
```

The console log shows `a b null` instead.

It gets even more fun when I try `id: { type: Sequelize.UUID, allowNull: false, defaultValue: Sequelize.UUIDV4 }` because it ends up `null` anyway.

**Comment by JSteunou** [comment]
I'm sorry but the bug appears to be present in 2.0.0-rc6.

I have a model user like

```
module.exports = function(sequelize, DataTypes) {
    return sequelize.define('user', {
        email: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        firstname: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        lastname: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        uuid: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDv4
        },

    });

};
```

and if I do this

```
user.build({email: 'jean.dupont@gmail.com', firstname: 'Jean', lastname: 'Dupont'});
user.toJSON();
```

I got this

```
{ uuid: undefined,
  id: null,
  email: 'jean.dupont@gmail.com',
  firstname: 'Jean',
  lastname: 'Dupont' }
```

And yes I'm using both id (for the mysql db) and uuid (for another purpose)

**Comment by mickhansen** [comment]
@JSteunou that specific default value might not happen untill save, try calling save and checking whether the value is available after that.

**Comment by JSteunou** [comment]
I tried with a `findOrCreate` that does create (build & save) if I understand well, and I found the same issue. But I tested so many things... I will test again tomorrow and keep you updated.

**Comment by mickhansen** [comment]
@JSteunou okay, please open a seperate issue if your problem persists

**Comment by JSteunou** [comment]
ok, done #2858

**Comment by JSteunou** [comment]
Ho my... I'm so sorry, I wrote "v4" with a lower "v". That's why it does not work. Good night of sleep helped.
