### ISSUE TITLE
[dev12] Construct LEFT JOIN query

### ISSUE THREAD

**Issue by shadeglare** [sequelize/sequelize#2260]
How could I construct a LEFT JOIN query with IS NULL using sequelize.js without raw SQL?

``` sql
SELECT T1.id FROM Table1 as T1
LEFT JOIN Table2 AS T2
ON T1.id = T2.id
WHERE T2.id IS NULL
```

**Comment by markdboyd** [comment]
I'm having the same issue, but the recommendation above does not work. if I try the above solution, it prepends the main table to my join table, creating the where condition as `T1.Table2.id IS NULL`, which is incorrect and causes the query to fail.

I can get around this by using `Sequelize.literal('"Table2"."id" IS NULL')`, but is that the only way to achieve what I want? Or am I missing something?

**Comment by mickhansen** [comment]
New syntax `{'$Table2.id$: null}` could work for you.

On Mon, Nov 2, 2015 at 6:22 PM, Mark Boyd <notifications@github.com> wrote:

> I'm having the same issue, but the recommendation above does not work. if
> I try the above solution, it prepends the main table to my join table,
> creating the where condition as T1.Table2.id IS NULL, which is incorrect
> and causes the query to fail.
>
> I can get around this by using Sequelize.literal('"Table2"."id" IS NULL'),
> but is that the only way to achieve what I want? Or am I missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/2260#issuecomment-153089546>
> .
>



-- 
Mick Hansen
@mhansendev
mhansen.io

**Comment by markdboyd** [comment]
That works. Thanks!
