### ISSUE TITLE
Migrations: add new UUID column and populate with default value

### ISSUE THREAD

**Issue by kytwb** [sequelize/sequelize#2263]
As I was reading reddit, I found [that guy asking for that exact same question](http://www.reddit.com/r/node/comments/2g1dq7/migrations_with_sequelizejs_how_can_i_add_a_new/) and I remember I met that issue earlier this month: how do you do with migrations to add a new column (that doesn't allowNull) and populate it with its default value (UUID for instance)?

**Comment by Americas** [comment]
The problem is in the ALTER TABLE SQL, it is not defining that column to have a default value..

**Comment by mindo** [comment]
+1

**Comment by mickhansen** [comment]
@Americas Are you using postgres? That's really the only dialect that supports built-in UUIDV4 afair.

**Comment by Americas** [comment]
In my case yes. It would solve some problems I'm having with sequelize not passing uuid primary keys, plus the logic would stay in the database, which is a huge boon

**Comment by DropsOfSerenity** [comment]
This is happening to me too, using postgres with existing tables that i'm adding a column to.

**Comment by Leventhan** [comment]
Default UUID values in the migrations not working for me either. This is what I had to do:

> 20151209115923-create-user.js (migration)

```
id: {
        allowNull: false,
        primaryKey: true,
        type: Sequelize.UUID
}

```

> user.js (model)

```
  var User = sequelize.define('User', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4
    }
);
```

**Comment by kennethklee** [comment]
my problem was with dates. I had to do this for postgres:

`defaultValue: DataTypes.literal('CURRENT_TIMESTAMP'),`

will produce something that looks like this:
`ALTER TABLE "public"."Users" ADD COLUMN "billingPlanUpdatedAt" TIMESTAMP WITH TIME ZONE NOT NULL CURRENT_TIMESTAMP;`

equivalently for uuid, you may have to do this:

`defaultValue: DataTypes.literal('uuid_generate_v4()'),`

**Comment by fcanela** [comment]
I seem to be facing the same problem but directly when creating the table.

```
  up: function (queryInterface, DataTypes) {
    return queryInterface.createTable('activities', {
      id: {
        primaryKey: true,
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV1
      },
```

And I face "Seed file failed with error: null value in column "id" violates not-null constrain" when trying to populate with some seeders.

**Comment by otusweb** [comment]
For other coming to this page, i found a solution at: http://stackoverflow.com/questions/12505158/generating-a-uuid-in-postgres-for-insert-statement

set the default value to: 
`md5(random()::text || clock_timestamp()::text)::uuid`

**Comment by felixfbecker** [comment]
@otusweb that is a bad way to generate a UUID.

**Comment by ajmueller** [comment]
@kennethklee that solution worked for me with Postgres, however you need to make sure you have the uuid-ossp extension installed.  In order to do that in a migration, you have to execute a raw query.  So here is my migration:

```javascript
'use strict';

module.exports = {
	up: function (queryInterface, Sequelize) {
		return queryInterface.sequelize.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";').then(function() {
			return queryInterface.addColumn(
				'TableName',
				'uuidColumnName',
				{
					type: Sequelize.UUID,
					defaultValue: Sequelize.literal('uuid_generate_v4()'),
					allowNull: false
				}
			);
		});
	},

	down: function (queryInterface, Sequelize) {
		return queryInterface.removeColumn('TableName', 'uuidColumnName');
	}
};
```

Hopefully this helps someone else in a similar situation with Postgres.

**Comment by TimFerrell** [comment]
When researching Postgres' documentation on the `"uuid-ossp"` extension, it states: 

> Historically this module depended on the OSSP UUID library, which accounts for the module's name. While the OSSP UUID library can still be found at http://www.ossp.org/pkg/lib/uuid/, it is not well maintained, and is becoming increasingly difficult to port to newer platforms.

> If you only need randomly-generated (version 4) UUIDs, consider using the gen_random_uuid() function from the pgcrypto module instead.

https://www.postgresql.org/docs/devel/static/uuid-ossp.html

Should you choose to use `pgcrypto` instead of `uuid-ossp` you can do so by:

```
    queryInterface.sequelize
      .query('CREATE EXTENSION IF NOT EXISTS pgcrypto;')
      .then(() =>
        queryInterface.addColumn('your_table', 'uuid', {
          type: Sequelize.UUID,
          allowNull: false,
          defaultValue: Sequelize.literal('gen_random_uuid()')
        })
      )
```

**Comment by tonestrike** [comment]
> For other coming to this page, i found a solution at: http://stackoverflow.com/questions/12505158/generating-a-uuid-in-postgres-for-insert-statement
> 
> set the default value to:
> `md5(random()::text || clock_timestamp()::text)::uuid`

This is the full implementation mentioned by @otusweb and this worked for me.
```
'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.addColumn('table', 'uuid', {
      type: Sequelize.UUID,
      defaultValue: Sequelize.literal('uuid_in((md5((random())::text))::cstring)'),
      allowNull: false,
      unique: true
    })
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.removeColumn('table', 'uuid')
  }
};

```
