### ISSUE TITLE
Multilingual Database Design with Sequelize

### ISSUE THREAD

**Issue by burakkilic** [sequelize/sequelize#2284]
Hi;

I want to save multilingual data to my database and I want to retrieve it easily.

Therefore I made a research and found a post about approaches for multilingual database design.

http://www.apphp.com/tutorials/index.php?page=multilanguage-database-design-in-mysql

As the author advices, I chose the 4th approach. So for each table, I created a translation table. 

But in SequelizeJS, I am having trouble with retrieving and saving data to my database. For instance:

```js
module.exports = function(sequelize, DataTypes) {

    var Item = sequelize.define('Item', {

    }, {
        associate: function(models) {
            Item.belongsTo(models.Account);
        },
        tableName: 'items'
    });
    return Item;
};

and

module.exports = function(sequelize, DataTypes) {
	var ItemTranslation = sequelize.define('ItemTranslation', {
			name: DataTypes.STRING,
			description: DataTypes.STRING
	},{
		tableName: 'item_translations',
		timestamps: false,
		associate: function(models){ 
			ItemTranslation.belongsTo(models.Item);
			ItemTranslation.belongsTo(models.Language);
		}
	});
	return ItemTranslation;
};
```

When I want to retrieve data from front end, I should use:

    item.itemTranslations[0].name = "BlaBla";

But what I need is, 
    
    item.itemTranslations[language].name = "BlaBla";

So what can I do about it? What is the best way to deal with multilingual data?

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by asaf050** [comment]
+1

**Comment by Diminished-librarian** [comment]
> I changed it to
> 
> ```
> var itemTranslationsArray = item.itemTranslations;
> ```
> 
> and the error is:
> 
> ```
> TypeError: Cannot call method 'each' of undefined
> ```





https://stackdev.space/questions/question-about-designing-databases-in-mysql-with-cakephp
