### ISSUE TITLE
Change the migration table name

### ISSUE THREAD

**Issue by tgthies** [sequelize/sequelize#2294]
Our use case is that we are refactoring a huge system into a multiple smaller systems, all of them with separated migrations but using the same DB (it will be separated later).

We'd like to be able to specify the name of migration table, so it won't conflict. I think it will be valuable to others use cases.

We thought it could be a key in the config file ex: "production": { "dialect": ..., "username": ..., "migrationTable": "migration_XYZ" }

If it makes sense we could do a pull request with the necessary changes.

Tks

**Comment by janmeier** [comment]
I believe this has already been implented in sequelize/umzug
