### ISSUE TITLE
Sequelize hooks do not work with libraries like co anymore

### ISSUE THREAD

**Issue by mlegenhausen** [sequelize/sequelize#2313]
Example:

``` js
var co = require('co');
var Sequelize = require('sequelize');

var sequelize = new Sequelize('sequelize-test', 'root', '');

var A = sequelize.define('A', {});

A.beforeCreate(co(function* (model, options) {
    yield function (done) {
        setTimeout(done, 1000);
    }
    console.log('before');
}));

co(function* () {
    yield sequelize.sync({
        force: true
    });

    var a = yield A.create();
    console.log('after');
})();
```

Result:

```
after
before
```

Expected the opposit. The problem is that sequelize expected a function with more than 2 parameters. But co returns a function with only 1, the callback. So sequelize is incompatible with all libraries which have dynamic parameter length. Is this the wanted behaviour? Removing the hook parameter length check let it work again with co.

**Comment by mattisx** [comment]
`co` is using promises since a while back. Personally I can't wait until `await/async`.
