### ISSUE TITLE
question: how to try/test sequelize in console

### ISSUE THREAD

**Issue by apneadiving** [sequelize/sequelize#2322]
Hi,

Coming from the Rails' world, I find it very convenient to go in my console and check my queries to ensure they return what I want.

I'm not sure how to do this using Express and Sequelize. Using the `node-inspector`, I set a debugger then once here, write:

```
User.findAll().success(function(users){ debugger; })
```

I hit enter, I resume the process but it fails to stop on the new introduced breakpoint.

Could you explain me how you do proceed to test queries? Do I really have to reload the page each time?

Thanks,

Benjamin

**Comment by bradens** [comment]
This is something I would love as well.  Sequelize is doing good things for a node ORM, but it needs a rails console equivalent :|

**Comment by janmeier** [comment]
What exactly do you want @bradens ? You can definitely spin up a node console, require sequelize and work away :)

**Comment by caioflores** [comment]
@janmeier I think he wants something like rails console for manipulating DB. For example, in rails you can run "rails c" in your console and it starts a command interface to manipulate your database using model functions. For example, you can run "User.all" and it returns all the users, you can run "User.first.name = 'other name'" and change a user name. Things like that, there's any easy way to to it with sequelize?

**Comment by felixfbecker** [comment]
@caioflores Just use the Node REPL.

**Comment by janmeier** [comment]
There is no automated way, but assuming you have exported all your models in a file you could do something like this to see all users:

```bash
node
> var models = require('./models.js');
> models.User.findAll().then(console.log);
```

One problem is that everything is async in node, so there is no easy way to write a command in the console and wait for it to complete - You have to attach a promise handler.

As for updating etc - No, I don't think that would be plausible to do in the console

**Comment by caioflores** [comment]
@janmeier I got it! Thanks for the help

**Comment by felixfbecker** [comment]
In Node 7 we can run the REPL with a flag to enable async/awai

**Comment by gavinbelson** [comment]
As @felixfbecker suggested using the async flag works well in this situation.

`node --experimental-repl-await`
`> models = require('./models'); 
> User = models.User; 
> await User.findAll(); `
