### ISSUE TITLE
[standard proposal] Model definitions and file placement should be standard?

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2323]
Implementation of sequelize on various framework environments (such as `express`) are different on some ways.

If sequelize had a standard on models placement, it would be extremely easy to implement nice features such as:
* Migrations access to models (its a pain on the *ss to create a table with migration and do manually all constraints, relationships and some important data)
* Sequelize models autoload (instead of having each one creating one)
* And way more...

What do you guys think about this?

**Comment by janmeier** [comment]
We shouldn't enforce any practice, so I'm closing this issue. If you feel like it you are welcome to provide a docs PR to provide best practice examples @cusspvz
