### ISSUE TITLE
Retrieve all record that are not related 

### ISSUE THREAD

**Issue by BlaShadow** [sequelize/sequelize#2326]
I got this

```
 models.Entity1.findAll({
        where:{ 'entity.id':[1,2] },include:[{model:models.Entity2,as:'entity'}]
  })
```

I want to retrieve all **Entity1** that are not related to **Entity2** but not figure out how to do it.

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
