### ISSUE TITLE
Feature: Associations remove[AS][plural]

### ISSUE THREAD

**Issue by ggarek** [sequelize/sequelize#2338]
> Sequelize version: 2.0.0-rc1

What about providing a method to remove associations, when array of association ids is given?

**Models given:**
```javascript
...
User.hasMany(Project)
Project.hasMany(User)
...
```

**What i want to do on a hunch:**
```javascript
var user = ... 

var toRemove = [1,2,3];  // e.g. got from http request 
user.removeProjects(toRemove).complete(...);
```

**But, the only option i have:**
```javascript
var user = ... 

var allUserProjectIds = [1,2,3,4,5]; //  ! excess db query
var toRemove = [1,2,3];  // e.g. got from http request 
var updatedUserProjecIds = difference(allUserProjectIds, toRemove); // [4,5]

user.setProjects(updatedUserProjecIds).complete(...);
```

If i am not mistaken currently i can remove associations this way:
* user.setProjects([]) - **Remove all associations**
* user.removeProject(project) ** - **Remove single association**

But i really need to remove a range of associations!

Thank you!

**Comment by janmeier** [comment]
Pr merged, closing
