### ISSUE TITLE
Where should not be required in `Model#update()`

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#2340]
I just noticed that providing a `where` parameter in the options passed to `Model#update()` is required. The following throws an error:

```
Folder.update({name: 'bob'})
```

This doesn't allow you to update all rows in a table simultaneously, which sometimes you might want to do. Should this be the case?

**Comment by feroc1ty** [comment]
why then throw a new Error?

https://github.com/sequelize/sequelize/blob/5be311997d5a07030ba62d9df1ab77ec52be415f/lib/model.js#L1584
options = options || {};
options.where = options.where || {};

I can create a pull request if you want?

**Comment by feroc1ty** [comment]
btw this

```Folder.update({name: 'bob'}, {where: {}})```

does not work for me
stacktrace - https://gist.github.com/feroc1ty/13551b351acde30a05d1

**Comment by janmeier** [comment]
The where is required to make sure the user actually wants to update all rows

**Comment by feroc1ty** [comment]
query

> postgres Executing (default): UPDATE "Users" SET "something"=0,"updatedAt"='2015-02-11 11:54:48.880 +00:00' WHERE

**Comment by mickhansen** [comment]
@feroc1ty seems there's an error in the query generator :)
Please open a new issue.
