### ISSUE TITLE
VIRTUAL Datatype validations

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2367]
I'm not completely aware if there was a discussion with validation options related with VIRTUAL Datatype.

I was thinking about this until I've realized that if VIRTUAL could have validations, they should run before set. It would be a bad approach to validate inside setter method.

**Comment by corbanb** [comment]
@mickhansen is this still an issue? The docs show we can validate on VIRTUAL but I am still seeing issues. Thoughts?

http://docs.sequelizejs.com/en/latest/api/datatypes/#virtual

**Comment by kengoldfarb** [comment]
@corbanb @mickhansen Seeing the same thing on **v3.19.3**.  Validations don't seem to run even though the docs suggest they should.

In the example below, I can set the password value to a single character without any errors.

```
password: {
	type: this.DataTypes.VIRTUAL,
	comment: 'This is a virtual attribute that is used to hash and set the actual password.',
	validate: {
		min: {
			args: 6,
			msg: 'Password must be at least 6 characters.'
		},
		max: {
			args: 50,
			msg: 'Password must be less than 50 characters.'
		},
	},
	set(val) {
		var salt = bcrypt.genSaltSync(10);
		var hash = bcrypt.hashSync(val, salt);
		this.setDataValue('password_encrypted', hash);
	}
}
```

**Comment by mickhansen** [comment]
@corbanb I'm actually not sure. I'd love for someone to verify.

**Comment by corbanb** [comment]
This all might be as simple as the @arcanis example missing one line after all: `this.setDataValue( 'password', value );` 

```
export var User = defineModel( 'user', {

    uid          : { type : UUID, defaultValue : UUIDV4, primaryKey : true },

    username     : { type : STRING, allowNull : false },
    email        : { type : STRING, allowNull : false },
    passwordHash : { type : STRING, allowNull : false },

    password : {

        type : VIRTUAL,

        set : function ( value ) {
            this.setDataValue( 'passwordHash', md5Buffer( value ) );
            this.setDataValue( 'password', value );
            return value;
        },

        validate : {
            len : [ 1, +Infinity ]
        }

    }

} );

```

**Comment by mickhansen** [comment]
Ah yeah, that's actually probably it. If you overwrite `set` we don't set to internal values, that's up to the user.
