### ISSUE TITLE
(Aliased) Count in raw query returns string instead of integer for the count column

### ISSUE THREAD

**Issue by Roam-Cooper** [sequelize/sequelize#2383]
When not binding the results to an orm model and therefore using raw: true,

A SELECT count(id) AS "countName" FROM "TABLE_NAME";
Results in the count being returned as a string, rather than an integer in Sequelize 1.7.9

**Comment by kikar** [comment]
Same thing is happening to me with Mysql/MariaDB, how to fix this?

**Comment by kikar** [comment]
I've tried dialectOptions: 
```javascript
new Sequelize(connectionString, { dialectOptions: { supportBigNumbers: true }})
```

Following [Sequelize docs](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor) and [mysql docs](https://github.com/mysqljs/mysql#connection-options), but still now working.

**Comment by rodrigoclp** [comment]
Add ::integer
SELECT count(id)::integer AS "countName" FROM "TABLE_NAME"
