### ISSUE TITLE
[2.0.0-rc1] instance.set doesn't override deleted_at

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2384]
Sequelize doesn't allow me to override `deleted_at` to `null` again. (Paranoid mode)

``` js
// Neither this works
instance.deleted_at = null;
instance.set( 'deleted_at', null );

// Only directly
instance.dataValues.deleted_at = null;

// I didn't tried setDataValue, but it should work.
```

**Comment by BeleteYaregal** [comment]
Use row queries like ....
sequelize.query("UPDATE users SET y = 42 WHERE x = 12").spread((results, metadata) => {
  // Results will be an empty array and metadata will contain the number of affected rows.
})
