### ISSUE TITLE
Question: proper way to set created_at/updated_at defaultValue on migration?

### ISSUE THREAD

**Issue by mchavarriagam** [sequelize/sequelize#2394]
Hello,

Running Sequelize on Express [Node: 0.10.25, CLI: 0.3.1, ORM: 2.0.0-rc1, Express: 4.9.0] using PostgreSQL and generated a migration to create a new table, like so:

```
module.exports = {
  up: function(migration, DataTypes, done) {
    // add altering commands here, calling 'done' when finished
    migration.createTable(
      'mytable',
      {
        id: {
          type: DataTypes.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        /** some more fields in here, not really relevant **/
        created_at: {
          type: DataTypes.DATE,
          defaultValue: DataTypes.NOW,
          allowNull: false
        },
        updated_at: {
          type: DataTypes.DATE,
          defaultValue: DataTypes.NOW,
          allowNull: false
        }
      }
    );

    done();
  },

  down: function(migration, DataTypes, done) {
    // add reverting commands here, calling 'done' when finished
    migration.dropTable('mytable');
    done();
  }
};
```

When I run the migration I get no errors but when I look at my table structure, this is what I see (SQL):

```
CREATE TABLE mytable
(
  id serial NOT NULL,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT mytable_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
```

There's no default value for created_at/updated_at. I tried running `INSERT INTO...` on psql (without passing created_at/updated_at data) and sure enough Pg complained about null values for those fields.

Any pointers would be appreciated. Thanks.

**Comment by tylerFowler** [comment]
+1 on this, I'm seeing the same thing with migrations for those two fields as well as a custom Date field. No errors reported but no default values applied in the schema (for Postgres in my case).

**Comment by BridgeAR** [comment]
This is indeed not intuitive but the solution to this is to use this in migrations:
```javascript
defaultValue: sequelize.fn('NOW')
```
The default value `DataTypes.NOW` will only work with the models and this won't set a default value as far as I remember. So the date is set by sequelize by the model instead of the database.

Until this is fixed it might be good to document this. @mickhansen @janmeier

**Comment by mchavarriagam** [comment]
Thanks for the update guys.

**Comment by paulxtiseo** [comment]
+1 on fixing this. Just got hit by it after having setup many tables.
