### ISSUE TITLE
Paranoid selects don't work with scopes

### ISSUE THREAD

**Issue by darren-clark** [sequelize/sequelize#2407]
If you use scopes, and have paranoid true in table options and call find with a primary key, the query constructed is invalid.

The reason is that in paranoidClause it calls sequelize.and, which replaces the single id attribute with an attribute called args. Then when the scope is merged in, it transforms that into an in clause e,g, args in (?,?). Which breaks all sorts of things.

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
