### ISSUE TITLE
Query BIGINT lose precision

### ISSUE THREAD

**Issue by aguegu** [sequelize/sequelize#2420]
parseInt is applied to parse BIGINT in the code:

https://github.com/sequelize/sequelize/blob/master/lib/dialects/mariadb/query.js#L57

parseInt would not keep the precision of bigint 

> parseInt('1481101092915232636')
> 1481101092915232500

It needs additional package like bignum, https://www.npmjs.org/package/bignum , to work

returning a wrong result is even worse than returning the raw string.

**Comment by BridgeAR** [comment]
This should be fixed since the data types got refactored, right? @mickhansen @janmeier

**Comment by mickhansen** [comment]
@BridgeAR I doubt it, but it's a driver issue rather than a sequelize issue.
