### ISSUE TITLE
Data migrations

### ISSUE THREAD

**Issue by patrykziem** [sequelize/sequelize#2435]
Possible duplicate, but it would be awesome to be able to create data migrations, which allow one to not only run DDL but also DML via ORM. I know that I can run raw SQL by `migration.migrator.sequelize.query()`, but that makes migrations dependant on particular DB dialect.

**Comment by hfar** [comment]
+1

**Comment by sushantdhiman** [comment]
Can't we use https://github.com/sequelize/cli `seeder` for this ? @janmeier

**Comment by janmeier** [comment]
Probably, in any case this is a CLI / umzug issue, not core sequelize
