### ISSUE TITLE
findOrCreate syntax in guide

### ISSUE THREAD

**Issue by calvintwr** [sequelize/sequelize#2443]
http://sequelizejs.com/docs/latest/models#block-26-line-1

should be 
    .findOrCreate({ username: 'sdepold',  job: 'Technical Lead JavaScript' })

**Comment by shotu** [comment]
I want to do something like : models.somemodel.findOrCreate({where:{
      id:payload.idd
    }, 
defaults:{ somemodel :payload }} 
)
.then(function (somemodelName) {
})
it is not working, i want to save complete payload if not exists already.

**Comment by janmeier** [comment]
@shotu `defaults: payload`

**Comment by shotu** [comment]
@janmeier thanks, it worked :)

**Comment by niktechnopro** [comment]
thank you that was very helpful

**Comment by RyanLandDev** [comment]
My log tells me the where attribute is missing, while it is clearly there. Anyone that could help me with this? https://ryan.is-inside.me/1HmV95xo.png
