### ISSUE TITLE
Multi-Level Includes and Aggregate Functions

### ISSUE THREAD

**Issue by DavidTPate** [sequelize/sequelize#2460]
Trying to do a little more advanced queries with what I have setup and I'm running into a few issues. Looking for a nudge in the right direction. I have a model which contains three major objects `user`, `action`, and `actionValue`. The idea is that a user can take multiple actions multiple times and each of those actions are worth some amount of points.

I'm trying to model the calculations for total points inside of a find statement to be used on a dashboard of sorts but I'm having troubles figuring out how to do all of this in Sequelize without using a custom query.

Here's my data model.
### User
- id (int) - Auto-generated
- username (string) - user input
### Action
- id (int) - Auto-generated
- actionTypeId (int) - The ID for the corresponding action in the `actionType` model.
- count (int) - Number of times the action has been done
## Action Type
- id (int) - Auto-generated
- name (string) - Name of the action
- value (int) - Number of points the action is worth.

What I'm trying to do is retrieve a summary of the points for the user based on the type of action. To do this my `find()` statement looks like the following:

``` js
model.user.find(
    {
        where: {
            username: 'bob'
        },
        include: [
            {
                model: model.action,
                include: [ model.actionType ]
            }
        ]
    }
)
```

This will retrieve for me the row on `user` that has a `username` of 'bob' and then retrieve all of their rows on the `action` table and the associated `actionType` record for each, sample below (represented as a JSON array of objects since it is too many fields for a table).

``` js
[
  {
   "id": 0
   "username": "bob",
   "action.id": 0,
   "action.actionTypeId": 0,
   "action.count": 5,
   "action.actionType.id": 0,
   "action.actionType.name": "Lost Game",
   "action.actionType.value": 2
  },
  {
   "id": 0
   "username": "bob"
   "action.id": 1
   "action.actionTypeId": 1
   "action.count": 3
   "action.actionType.id": 0
   "action.actionType.name": "Won Game",
   "action.actionType.value": 10
  }
]
```

I could then parse through that data and I would come out with composite values by multiplying the number of times an action was taken with the value it holds. So for the data above I would see that the user `bob` got 10 points (5 \* 2) for losing a total of 5 games, and then he got 30 points (3 \* 10) for winning a total of 3 games giving `bob` a grand total of 40 points.

Since I want to be able to utilize the ordering and other capabilities of the database I want to be able to calculate what I ran through above in my query instead of having to do it on the application server.

Ideally I'm looking for output containing the following (again a JSON object because it is too large for a table):

``` js
{
  "id": 0,
  "username": "bob",
  "score": 40 // This would be the `sum(action.count * action.actionType.value)`
}
```

Any help on if this is feasible right now or not through the model would be much appreciated. Thanks!

**Comment by QwertyZW** [comment]
@mickhansen missing a `)` after 'score'.

It's `attributes: [[sequelize.literal('SUM()', 'score')]]` for the copypasta squad

**Comment by mickhansen** [comment]
@QwertyZW Thanks, fixed :)

**Comment by QwertyZW** [comment]
Btw is there a way to do what the OP is trying to do in 2017? trying out various methods but with no luck. I'm a bit of a newbie with sequelize 

This code
```
  // find the provider, nest all the components and nest their timestamps within them

//  models.sequelize.query('SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,\'ONLY_FULL_GROUP_BY\',\'\'));')
  provider.find({
 //   attributes: { exclude: ['*'] },
  //  group: 'Components.TimestampStatuses.ComponentId',
   // attributes: [[sequelize.fn('MAX', sequelize.col('Components.TimestampStatuses.createdAt')), 'no_hats']],
    
    where:{
      name: name
    },
    include: [ 
      { 
      //  attributes: { exclude: ['*'] },
        model: models.Component,   
      //  group: 'id',
        include: [
          {
            model: models.TimestampStatus,
           // limit: 1,
            group: 'Components.id',
            attributes: [[sequelize.fn('MAX', sequelize.col('Components.TimestampStatuses.createdAt')), 'no_hats']]
          } 
        ] 
      } 
    ]
  })
```

generates this SQL 

```
SELECT `Provider`.*, `Components`.`id` AS `Components.id`, `Components`.`name` AS `Components.name`, `Components`.`description` AS `Components.description`, `Components`.`createdAt` AS `Components.createdAt`, `Components`.`updatedAt` AS `Components.updatedAt`, `Components`.`ProviderId` AS `Components.ProviderId`, `Components.TimestampStatuses`.`id` AS `Components.TimestampStatuses.id`, `Components.TimestampStatuses`.`status` AS `Components.TimestampStatuses.status`, `Components.TimestampStatuses`.`createdAt` AS `Components.TimestampStatuses.createdAt`, `Components.TimestampStatuses`.`updatedAt` AS `Components.TimestampStatuses.updatedAt`, `Components.TimestampStatuses`.`ComponentId` AS `Components.TimestampStatuses.ComponentId`, `Components.TimestampStatuses`.`ScanId` AS `Components.TimestampStatuses.ScanId` FROM (SELECT `Provider`.`id`, `Provider`.`statusUrl`, `Provider`.`parser`, `Provider`.`name`, `Provider`.`createdAt`, `Provider`.`updatedAt` FROM `Providers` AS `Provider` WHERE `Provider`.`name` = 'Atlassian' LIMIT 1) AS `Provider` LEFT OUTER JOIN `Components` AS `Components` ON `Provider`.`id` = `Components`.`ProviderId` LEFT OUTER JOIN `TimestampStatuses` AS `Components.TimestampStatuses` ON `Components`.`id` = `Components.TimestampStatuses`.`ComponentId`;
```

All I wanna do is add a MAX(...) to the SELECT and append a GROUP BY at the end to get this sql:

```
SELECT MAX(`Components.TimestampStatuses`.`createdAt`), `Provider`.*, `Components`.`id` AS `Components.id`, `Components`.`name` AS `Components.name`, `Components`.`description` AS `Components.description`, `Components`.`createdAt` AS `Components.createdAt`, `Components`.`updatedAt` AS `Components.updatedAt`, `Components`.`ProviderId` AS `Components.ProviderId`, `Components.TimestampStatuses`.`id` AS `Components.TimestampStatuses.id`, `Components.TimestampStatuses`.`status` AS `Components.TimestampStatuses.status`, `Components.TimestampStatuses`.`createdAt` AS `Components.TimestampStatuses.createdAt`, `Components.TimestampStatuses`.`updatedAt` AS `Components.TimestampStatuses.updatedAt`, `Components.TimestampStatuses`.`ComponentId` AS `Components.TimestampStatuses.ComponentId`, `Components.TimestampStatuses`.`ScanId` AS `Components.TimestampStatuses.ScanId` FROM (SELECT `Provider`.`id`, `Provider`.`statusUrl`, `Provider`.`parser`, `Provider`.`name`, `Provider`.`createdAt`, `Provider`.`updatedAt` FROM `Providers` AS `Provider` WHERE `Provider`.`name` = 'Atlassian' LIMIT 1) AS `Provider` LEFT OUTER JOIN `Components` AS `Components` ON `Provider`.`id` = `Components`.`ProviderId` LEFT OUTER JOIN `TimestampStatuses` AS `Components.TimestampStatuses` ON `Components`.`id` = `Components.TimestampStatuses`.`ComponentId` GROUP BY `Components` . `id`;
```

I've tried a mixture of things including everything in this thread but with no luck.

**Comment by KhizarSH** [comment]
how we can convert this query to sequelized one
SELECT 
    createdAt,
    COUNT(*) AS TOTAL, 
    sum(DATE_FORMAT(createdAt,'%Y%c%d')=DATE_FORMAT(current_date(),'%Y%c%d')) tcount,
    sum(DATE_FORMAT(createdAt,'%Y%c%d')=DATE_FORMAT(current_date()-1,'%Y%c%d')) ycount,
    sum(DATE_FORMAT(createdAt,'%Y%c%d')=DATE_FORMAT(current_date()-2,'%Y%c%d')) threecount,
    sum(DATE_FORMAT(createdAt,'%Y%c%d')=DATE_FORMAT(current_date()-3,'%Y%c%d')) fourcount,
    sum(DATE_FORMAT(createdAt,'%Y%c%d')=DATE_FORMAT(current_date()-4,'%Y%c%d')) fifthcount
FROM r5.users;
