### ISSUE TITLE
Conventions for plugins

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#2462]
I've written another Sequelize plugin (https://github.com/overlookmotel/sequelize-definer). This one is to make it easy to define a whole set of models. I also published a plugin to handle hierarchies a while back (https://github.com/overlookmotel/sequelize-hierarchy).

If the aim is to encourage people to write plugins for Sequelize, it seems to me that it'd be good to agree a convention for how plugins should be loaded and work.

Here are the issues I think it would useful to agree a convention on:
### How to load the plugin?

I can see 3 possible solutions:
#### 1. Pass Sequelize to plugin module

```
var Sequelize = require('sequelize');
require('sequelize-plugin1')(Sequelize);
require('sequelize-plugin2')(Sequelize);
```

At present this is how my two plugins work, but it's a bit of a pain.
#### 2. Rely on `require` caching

```
var Sequelize = require('sequelize');
require('sequelize-plugin1');
require('sequelize-plugin2');
```

The plugins would call `var Sequelize = require('sequelize')` internally and then alter the Sequelize object. It relies on `require` caching the result of `require('sequelize')`.

If plugins return `Sequelize` then it'd also be possible for a user who is only using a single plugin to load both Sequelize and the plugin with:

```
var Sequelize = require('sequelize-plugin1');
```

This option would be easier to code and use, but I'm not sure if it is reliable or not to expect `require` to cache or not.
#### 3. A Sequelize method

Something like:

```
var Sequelize = require('sequelize');
Sequelize.plugin(require('sequelize-plugin1'));
```

Personally, I'm not so sure about this one.
### How to register plugins?

It would be good if there was a register of plugins in Sequelize, so that one plugin can check if another plugin is also loaded, to manage any conflicts etc.

Something like an object `Sequelize.plugins` which is initially empty, and each plugin should on loading run:

```
Sequelize.plugins.<name of plugin> = true;
```

`.plugins` could also be a space for plugins to store options, or other persistent state data without cluttering up the Sequelize object elsewhere. e.g.:

```
Sequelize.plugins.<name of plugin> = { options: { option1: true, option2: false } };
```
### Rules

I would also suggest setting some "rules" for plugin developers. I would propose:
1. Your plugin module should return `Sequelize`
2. Your plugin should register itself in `Sequelize.plugins`
3. Your plugin should store any persistent data only inside `Sequelize.plugins`
4. Your plugin should not alter the behaviour of Sequelize's native methods, unless the user calls a method or sets an option to specifically ask it to
5. `package.json` should contain the keywords `'sequelize'` and `'sequelize-plugin'` to allow easy npm searching
### Other things

It would be nice to have a short list of existing Sequelize plugins in the docs to act as examples to other plugin developers.

Any thoughts?

**Comment by BridgeAR** [comment]
Reference #895
