### ISSUE TITLE
self-referencing hasMany with through:null conform manual does not work anymore in 2.0.0rc2 

### ISSUE THREAD

**Issue by josdewitte** [sequelize/sequelize#2463]
According to the manual, this should be the way to define self-referencing toMany relations:

Item.hasMany(models.Item, { as:'children', foreignKey : 'parent_id' , through: null});

However when calling the associate function:

TypeError: Cannot read property 'model' of null
    at new module.exports.HasMany (/node_modules/sequelize/lib/associations/has-many.js:133:28)

Probably it tries to get the model of the "through" property before checking if it is == null..

This used to work around dev12

**Comment by BridgeAR** [comment]
This is fixed. Should be closed.
