### ISSUE TITLE
missing schema name in generated SQL for foreign keys

### ISSUE THREAD

**Issue by codename-** [sequelize/sequelize#2464]
**Notice: I'm using PostgreSQL with schemas, and sequelizer 2.0-rc2**

I've got a small problem trying sequelize do all magic with my relations.
I want to create relationship **n:m**, but I also want that transition table to have few additional fields.
I've defined model with explicit foreign keys (where _references_ are pointing to model instance) - something like this:

``` javascript

// db = new Sequelize(...);

db.define('company_view', {

  sort_order   : { type : Sequelize.INTEGER },

  company_code : {
    type          : Sequelize.STRING,
    primaryKey    : true,
    references    : db.models.company,
    referencesKey : "code"
  }, 

  view_code : {
    type          : Sequelize.STRING,
    primaryKey    : true,
    references    : db.models.view,
    referencesKey : "code",
  } 

}, { schema : 'configuration' })
```

But when I try to create schema I've got this SQL - which do not have schema names in references bits:

``` SQL
CREATE TABLE IF NOT EXISTS "configuration"."company_views" (
  "sort_order" INTEGER, 
  "company_code" VARCHAR(255)  REFERENCES "companies" ("code"),  -- look ma' - no schema
  "view_code" VARCHAR(255)  REFERENCES "views" ("code"),         -- look ma' - no schema
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, 
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, 
  PRIMARY KEY ("company_code","view_code")
);
```

Changing definition to something like this also doesn't work:

``` javascript
  // ...
  view_code : {
    type          : Sequelize.STRING,
    primaryKey    : true,
    references    : '"configuration"."views"',
    referencesKey : "code",
  } 
  // ...
```

Any ideas for workaround until it's fixed?

**Comment by iamjoyce** [comment]
This issue also exists for MSSQL. The fix suggested by codename- does solve the problem.

**Comment by felixfbecker** [comment]
@iamjoyce PR welcome!

**Comment by iamjoyce** [comment]
@felixfbecker Can I clarify something? - Currently the master branch is for Sequelize v4, but I've gotten that error in v3. Should I still do the PR for master branch?
