### ISSUE TITLE
Instance method with conflicting names break stuff

### ISSUE THREAD

**Issue by amikhalev** [sequelize/sequelize#2466]
If you have an instance method that has the same name as an interal method on the `Instance` class, it breaks stuff (eg. `set`). Code Example:
```js
var Sequelize = require("sequelize");
var sequelize = new Sequelize('db', 'user', 'pass', {
  dialect: 'sqlite',
  storage: 'test.sqlite'
});

var Model = sequelize.define('Model',
  {
    name: {
      type: Sequelize.STRING,
      allowNull: false
    }
  },
  {
    instanceMethods: {
      set: function (){} // breaks stuff
    }
  });

Model.create({name: ""})
  .catch(function (err) {
    console.error(err); // SequelizeValidationError
  });
```
Sequelize shouldn't allow you to declare methods that conflict with others. I am using `sequelize:2.0.0-rc2`

**Comment by sushantdhiman** [comment]
`instanceMethods / classMethods` have been removed https://github.com/sequelize/sequelize/pull/6180
