### ISSUE TITLE
Access selected values that are not model attributes (eg from a join)

### ISSUE THREAD

**Issue by cjroth** [sequelize/sequelize#2469]
Related to #1460 and #1830. I'm using rc2.

I am using a raw query to join two tables, creating additional "virtual" attributes on my model instances.  How can I make these additional attributes accessible from my models? I had previously been using the selectedValues property but now that it's gone I need to find another way. Here is an example (I'm using squel to write the queries):

```
var query = squel.select()
    .field('users.*')
    .field('count(signs.*)', 'sign_count')
    .from('users')
    .left_join('signs', null, 'signs.created_by = users.id')
    .where('users.deleted_at is null')
    .where('signs.deleted_at is null')
    .group('users.id')
    .order('users.created_at', false);

  sequelize
    .query(query.toString())
    .error(next)
    .success(function(users) {
      // ...
    });
```

So I am joining the signs table to get a count of signs for each user. This is not very complicated and could maybe be done with the sequelize's count functionality, but there are a number of places where I'm doing more complex joins, like here where I am joining three tables and using an attribute from the third table and attaching it to rows on the first:

```
  var query = squel.select()
    .field('signs.*')
    .field('sponsors.image_url', 'sponsor_logo_url')
    .from('signs')
    .left_join('campaigns', null, 'campaigns.id = signs.campaign_id')
    .left_join('sponsors', null, 'sponsors.id = campaigns.sponsor_id')
    .where('signs.deleted_at is null')
    .order('signs.created_at', false);
```

**Comment by LaurentVB** [comment]
Hi,
I know this is a veeeeeeery old question, but I found it while searching for the same information so answering here might help others (and future me).
I'm using Sequelize v3 and I can access my additionally selected column (a COUNT from a JOIN, not part of the defined model, even as a VIRTUAL field) by simply doing: 

```
model.get('additional_column_name')
```

In the above question's first example, you would access the count with:

```
user.get('sign_count')
```

Hope this helps.

**Comment by BartusZak** [comment]
@LaurentVB works within model fields, but what about associated fields?

I see that constructor of the model contains those values. Is there a way to get them in a more 'gentle' way?
