### ISSUE TITLE
Casting datatypes when migrating

### ISSUE THREAD

**Issue by mateeyow** [sequelize/sequelize#2471]
I am trying to migrate data types from **boolean** to **integer** using this query on a postgre database: 

``` javascript
seq.getMigrator().queryInterface.changeColumn('tableName', 'columnName', {type: Sequelize.INTEGER});
```

And I get the following error:

> Possibly unhandled SequelizeDatabaseError: error: column "columnNew" cannot be cast to type 
> integer

And I understand that I have to cast the data type, but is there a way to cast it while using the above migration code? 
`I am using the current version of sequelize`

**Comment by ee99ee** [comment]
+1 for this... ran into the same problem

**Comment by andrest** [comment]
+1, also interested in this

**Comment by bumpmann** [comment]
+1

Using postgres, you have to use ALTER TABLE ... USING like

`ALTER TABLE the_table ALTER COLUMN col_name TYPE integer USING (col_name::integer);`

according http://stackoverflow.com/questions/13170570/change-type-of-varchar-field-to-integer-cannot-be-cast-automatically-to-type-i which does not look like to be possible in query-generator.js

**Comment by Hinton** [comment]
As a temporary work-around it's possible to use:
```js
queryInterface.changeColumn('table', 'column', {
        type: 'INTEGER USING CAST("column" as integer)'
});
```
**Warning**, I've only tested the query in postgresql.

**Comment by wikiziner** [comment]
@Hinton Thanks!, Worked for me too.

**Comment by NgSculptor** [comment]
For someone like me who wants to change string to JSONB

return queryInterface.changeColumn('table', 'details', {
			type: Sequelize.ARRAY(Sequelize.JSONB) + 'USING CAST("details" as ' + Sequelize.ARRAY(Sequelize.JSONB) + ')'
		});

**Comment by arhka-win** [comment]
@bumpmann I still have this bug with Postgres. Works only with this 'INTEGER USING CAST("column" as INTEGER)', what is not the same as written in documentation. Could you tell me, when this bug is going to be fixed, please?

**Comment by samathan** [comment]
Hi 

> return queryInterface.changeColumn('table', 'details', { type: Sequelize.ARRAY(Sequelize.JSONB) + 'USING CAST("details" as ' + Sequelize.ARRAY(Sequelize.JSONB) + ')' });

Hi,

When I use the above way to migrate JSON column into JSONB it is throwing below error
ERROR: cannot cast type json to jsonb[]

Can you please help me with this.

Thank You

**Comment by Ethaan** [comment]
should this do the trick?

```
    await queryInterface.changeColumn('tribes', 'cover_image_url', {
      type: 'JSONB USING CAST("cover_image_url" as JSONB)',
      defaultValue: '{}',
    });
```

becuase this thorow, `ERROR: default for column "cover_image_url" cannot be cast automatically to type jsonb`, i did already try to `defaultValue: {}` and that throw `ERROR: Invalid value {}`

**Comment by jeancabral** [comment]
> As a temporary workaround it's possible to use:
> 
> ```js
> queryInterface.changeColumn('table', 'column', {
>         type: 'INTEGER USING CAST("column" as INTEGER)'
> });
> ```
> 
> **Warning**, I've only tested the query in postgresql.

save my day

**Comment by drilonibrahimi** [comment]
> As a temporary workaround it's possible to use:
> 
> ```js
> queryInterface.changeColumn('table', 'column', {
>         type: 'INTEGER USING CAST("column" as INTEGER)'
> });
> ```
> 
> **Warning**, I've only tested the query in postgresql.

This worked for me. Thanks a lot!

**Comment by Xkill119966** [comment]
I just want to change my string data type to array enum value, but i got type cast error
