### ISSUE TITLE
where.$and/$or support

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2489]
To allow and/or combinations without forcing people to use `sequelize.and/or`.

**Comment by davidsansay** [comment]
This is already documented, http://sequelize.readthedocs.org/en/latest/docs/models/#data-retrieval-finders, in the "Complex filtering / OR queries" section, but not implemented yet on sequelize@2.0.0-rc8

I wonder if the docs should describe what is already done

**Comment by mickhansen** [comment]
@davidsansay those docs refer to `sequelize.or()` which has been implemented for a while. `$or`/`$and` is a never thing we've implemented that actually needs to be documented still.
