### ISSUE TITLE
Trick for automatically serializing eagerly loaded associations?

### ISSUE THREAD

**Issue by dkushner** [sequelize/sequelize#2493]
Just a minor issue that I'm struggling with at the moment. It appears that the default instance implementation of toJSON detects and automatically serializes any eagerly loaded associations on the model. However, the name that the associations are loaded under is the capitalized and pluralized name of the association. So if I have a 'Topic' model with a 'Category' association such that `Topic.belongsTo(Category)`, if I eagerly load the category with the topic, I get `topic.Category`. Obviously this is a trivial example but I'm wondering if there is some way to access a list of eagerly loaded associations from within the toJSON() instance method so that I can programmatically rename and serialize all of the eagerly loaded associations?

**Comment by memelet** [comment]
Where would instance.options.include be used?

**Comment by mickhansen** [comment]
@memelet depends on what you want to do
