### ISSUE TITLE
order with camelcase column name gives an error

### ISSUE THREAD

**Issue by sayanee** [sequelize/sequelize#2495]
with sequelize version `2.0.0-rc2`, my simple sorting, where the db column in postgres is `updatedAt`, is as follows:

```
db.MachineRequest.findAll({
      where: { approved: true },
      order: 'updatedAt'
})
```

It gives me this error - seems like it is always lowercasing it:

```
Cannot display approved machine requests: SequelizeDatabaseError: error: column "updatedat" does not exist
```

I have tried putting backtick symbol around `updatedAt` and it gives the same error:

Any idea how to order by a column name that has camel case? Thanks!

**Comment by rutaihwa** [comment]
I know the issue has been closed but, what is is the solution? Because, I still get this error

`Possibly unhandled SequelizeDatabaseError: column "createdat" does not exist`

when perfoming `...., order: 'createdAt'

**Comment by manmar92** [comment]
You have to write it like this: 
```
findAll({ order: '"createdAt" DESC' })
```

**Comment by bschmaltz** [comment]
:+1: @manmar92

**Comment by mattroberts297** [comment]
:+1: @manmar92

**Comment by chouchou900822** [comment]
thx @manmar92

**Comment by sagnol** [comment]
thanks!! @manmar92

**Comment by felixfbecker** [comment]
Using a string directly for `order` is not recommended and will likely go away in the future. Use `[['updatedAt', 'DESC']]`.

**Comment by maxmumford** [comment]
Note: if using the list syntax like so:

`[['updatedAt', 'DESC']]`

You don't have you quote the column names
