### ISSUE TITLE
find should error on incorrect inputs

### ISSUE THREAD

**Issue by jsha** [sequelize/sequelize#2497]
It's easy to make mistakes with option parameters. For instance, the difference between these two statements is crucial:

```
Subscription.find({
  author_uid: btUser.uid,
  subscriber_uid: req.user.uid
});
```

```
Subscription.find({
  where: {
    author_uid: btUser.uid,
    subscriber_uid: req.user.uid
  }
});
```

It should be possible to detect this type of error at runtime by looking for keys that are not valid inputs to find().

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/5322
