### ISSUE TITLE
How do bind a binary in where clause?

### ISSUE THREAD

**Issue by tslater** [sequelize/sequelize#2499]
I currently have a hexadecimal string. I tried putting it directly in there where clause but that doesn't work. Is there someway to unhex it?

**Comment by ReklatsMasters** [comment]
@tslater try use 
```js
var c = "a1b2c3d4";
Model.update({a:1}, {where:{ b: sequelize.literal(`unhex('${ c }')`) }})
```

**Comment by samvv** [comment]
Any updates on this for the case of inserting a value? I also need it.
