### ISSUE TITLE
Can't get the raw result for raw query "INSERT ... ON DUPLICATE KEY ..."

### ISSUE THREAD

**Issue by warmsea** [sequelize/sequelize#2505]
I'm using v2.0.0-rc2.
I can't get the raw result no matter how I set `raw` and `type` for a `INSERT ... ON DUPLICATE KEY ...` query.
And the raw result seems wrong.
Here's my code:

```javascript
var Sequelize = require('sequelize');
var sequelize = new Sequelize('testa', 'testa', 'testa', { dialect: 'mysql' });

sequelize.define('Test', {
  a: Sequelize.INTEGER,
  b: Sequelize.INTEGER,
  del: Sequelize.BOOLEAN
}, {
  indexes: [{ unique: true, fields: ['a', 'b'] }]
});

sequelize.sync().complete(function(err) {
  if (err) {
    console.log('ERROR 1');
  } else {
    var sql = 'INSERT INTO `Tests` (`a`, `b`, `del`) VALUES (1, 2, 0) ' +
      'ON DUPLICATE KEY UPDATE `del`=0';
    sequelize.query(sql, null, { raw: true, type: 'INSERT' }).complete(
      function(err, result) {
        console.log(arguments);
      }
    );
  }
});
```

I want to know how many rows are inserted or changed. 

There's already a (1, 2, 0) in the table. Here's my tests:

callee | raw | type | results
---------|------|-------|---------
null | * | SELECT | ERROR
null | * | INSERT | null
null | * | BULKUPDATE or BULKDELETE | 1 (I want a zero)
Test | * | * | ERROR

I noticed in the file `sequelize/lib/dialects/mysql/query.js`, in line 43, the `results` BEFORE `.formatResults()`, there are `affectedRows` and `changedRows` in it. But I don't know how to get that value without formatting. And the `changedRows` seems wrong too.

I ran the same SQL in my MySQL CLI, it tells `0 row affected` or `1 row affected`. This value is what I expected.

Will you please let me know how many rows are changed?

Thank you!

**Comment by warmsea** [comment]
Thank you janmeier! I tested it again and found it's felixge/node-mysql didn't return the values I expected. Sequelize's bug is fixed.

**Comment by warmsea** [comment]
For those who meet the same issue. Setting `flags` for `felixge/node-mysql` works as I expected.

See [the docs of node-mysql](https://github.com/felixge/node-mysql#connection-flags).

```javascript
var sequelize = new Sequelize('testa', 'testa', 'testa', {
  dialect: 'mysql',
  dialectOptions: {
    flags: '-FOUND_ROWS'
  }
});
```

**Comment by yft** [comment]
Sqlite also has the same problem
