### ISSUE TITLE
How is constraints handling working on paranoid?

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2506]
I think i may found a bug, i'm using paranoid on all my tables (except N:M ones, that uses no paranoid by default).

Deleting an instance doesn't delete N:M associations...

I've made that question to understand how it is working behind the hood to gather  a solutions for some problemas i've found:
- If N:M throughTable isn't paranoid and instance related is, it should trigger a relation deletion whenever an instance is deleted.
- `Model.delete` ( and maybe `Model.bulkCreate` ) is not turning `instanceHooks` on by default, which will create a lot of problems with constraints handling in the future for developers who are using `paranoid`.

**Comment by sushantdhiman** [comment]
**SSCCE Test**

```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

var
    M = sequelize.define('M', {}, { paranoid: true })
  , N = sequelize.define('N', {}, { paranoid: true })
  , MN = sequelize.define('MN');

M.belongsToMany(N, { through: MN, onUpdate: 'CASCADE', onDelete: 'CASCADE' });

sequelize.sync({ force: true })
.then(() => sequelize.Promise.join(
  M.create({}), N.create({})
))
.spread((m, n) => (
  m.setNs(n).then(() => m.destroy())
))
.then(() => ( MN.findAll({ raw: true }) ))
.then(console.log)
.catch(console.error);
```

**Output**
```bash
Using database:  sequelize-test-91
[ { createdAt: 2016-07-02T08:07:23.244Z,
    updatedAt: 2016-07-02T08:07:23.244Z,
    MId: 1,
    NId: 1 } ]
```

**Thoughts**

As we can see the paranoid instance will not delete their junction table links because they are actually not deleted, just `deletedAt` is set.

I think this is the desired behavior, If the deleted instance is ever restored back the link should be present. If user really want to remove the link they can 'unset' the link between two tables before deleting the record.

What do you think @mickhansen @janmeier ?

**Comment by cusspvz** [comment]
@sushantdhiman thank you for the provided test case.

When you don't set `paranoid` on models that have a relation, you have the **cascade deletion** by default, am I right? Unless you change the desired behavior.

But when you have `paranoid` on both of them, you might want the **cascade deletion** effect to happen but not the **real deletion**, just the cascade set of **deletedAt** attribute, or a **paranoid cascade**.

The way I did work around at the time was to attach hooks on models children to apply the **deletedAt** whenever a parent was deleted to obtain the desired **paranoid cascade**.

This seems quite simple to solve, but there should be a note on the docs regarding **unwanted loss of data**.

At first glance it seems to be easy as, on both destruction (instance.destroy and Model.destroy), if model is paranoid, check associations and trigger a `Model.destroy` call filtering by the affected rows's primary keys. That would work flawless if every models are set as `paranoid`. But if you have one of them as non-paranoid, it won't only delete the data, but also delete the *children* related even if they are set as `paranoid` because of the mysql's CASCADE effect. In fact, I think that already happens.

@janmeier @mickhansen @sushantdhiman What suggestions do you have to cover what I've mentioned?

**Comment by sushantdhiman** [comment]
Users can set the hooks but we can't rely on hooks for this critical behavior (hooks can be disabled).

I would only soft delete child models in any situation. So if we want to delete related records, we should only do if the target model is paranoid (to prevent unexpected data loss)

In non paranoid cases deletion of related records is handled by database constraints thus its an atomic operation. So we might need to run destroy in transaction (if we want to destroy related records by sequelize)

Personally I would never like `destroy` to work like this. Related records may be used by other tables in many cases. Sequelize should not delete the records behind the scenes. Deletion should be explicit and defined.

I would like to know @mickhansen @janmeier opinion too.

**Comment by mickhansen** [comment]
Soft delete cascation for two models being paranoid with an explicit onDelete: CASCADE might make sense.

**Comment by mickhansen** [comment]
As for hooks, in the future users should rely on missing a lot of functionality if they disable hooks.

**Comment by janmeier** [comment]
Yeah, I think cascading the deletion is the most intuitive - But it should be mentioned in the doc

**Comment by janmeier** [comment]
And I agree, if users disable hooks, they may have a bad time, mkay!

**Comment by cusspvz** [comment]
I've relied on hooks before because I had to move faster, that doesn't mean this has to be applied with hooks. If you all agree to CASCADE in case it is the default configured behavior, a simple `for` logic could be added into the `.destroy` method. :)

**Comment by felixfbecker** [comment]
I also agree that not deleting the relation rows is the expected behaviour. We use paranoid in pretty much every model in our company and need to be able to 100% restore any record, including relations. But we never query our relation (through) models directly, other users might do that. And in that case the relation table should have a deletedAt too. This of course needs to happen on application layer in sequelize, in a transaction. This of course should also be done for 1:n and 1:1 relations, is this already implemented?
