### ISSUE TITLE
Memory leak when using a "connectPromise" variable?

### ISSUE THREAD

**Issue by Madd0g** [sequelize/sequelize#2513]
Hi, please take a look at this question on StackOveflow - http://stackoverflow.com/questions/26683871/node-memory-leak-v8-snapshot-is-it-bad-practice-to-use-a-connection-promise

I store a reference to the first promise from the connection and reuse that in all method calls.
It looks like all the memory in my v8 heap snapshot is always retained by the same storage sequence - `Array -> 'sql' > _events > connectPromise`. 

Is having a global long-lived "connect promise" object is what causing my memory leak? What's the alternative?

Thanks

**Comment by mickhansen** [comment]
The event emitter patch and storage of SQL events will be killed in `2.1.0`, we just need to rewrite all tests to promises first, zzz.

**Comment by janmeier** [comment]
Closing this as a bug in a the trycatch module.

The effects should be completely alleviated once eventemitter goes away
