### ISSUE TITLE
Error: Unknown column 

### ISSUE THREAD

**Issue by nicholasf** [sequelize/sequelize#253]
Hi,

Instead of throwing an error if create is called with a property and value that doesn't correspond to the table definition, the value should be ignored and copied onto the produced model instance as a virtual attribute (this would mimic ActiveRecord and seems like a safe practice to pursue).

```
Executing: INSERT INTO `health_quotes_request_details` (`member_request`,`cover_type`,`cover_for`,`cover_level`,`excess_level`,`age_oldest_person`,`current_provider`,`current_paying`,`frequency`,`shortlist_1`,`shortlist_2`,`shortlist_3`,`shortlist_4`,`id`,`created_at`,`updated_at`,`quotes_request_id`) VALUES ('member request data','cover type','family cover data','cover level','full','30-50','BUPA',350,'monthly','Medibank Private','AHF','BUPA','NIB',NULL,'2012-08-20 12:10:02','2012-08-20 12:10:02',NULL);

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: Unknown column 'member_request' in 'field list'
```

**Comment by ahmedbouhmid** [comment]
hey i have the same probleme
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'
Or i dind't have the clumn 'createdAt' in my table in the database , any help ?

**Comment by janmeier** [comment]
@ahmedbouhmid Have you disabled timestamps in your model definition? By default sequelize thinks you have timestamps http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration
