### ISSUE TITLE
Getting [SyntaxError: Unexpected token u] from what seems a valid query statement

### ISSUE THREAD

**Issue by attheodo** [sequelize/sequelize#2534]
I am getting "[SyntaxError: Unexpected token u]" when running this code for no apparent reason. Removing the specific attributes from the include statement works fine. Any clues?

Edit: Using Postgres dialect

module.exports.getUserChats = function getUserChats(req,res,next){

```
var userId = req.user.id

models.ChatChannel.findAll({
    attributes: ['id','name','hasSessionEnded','createdAt','updatedAt'],
    where: {UserId: userId},
    include: [
        { model: models.Place, attributes: ['id','name'] }
    ]

})
.then(function(chatChannels){
    res.status(200).json({response: {ChatChannels: chatChannels}})
})
.catch( function(err){ return hlprs.sendResWithErr(res,err,500,true,'Error while querying database to get chat channels'); });
```

}

**Comment by CenaSurya** [comment]
Hai Am Sooriyan,
I have using sequelize in date format
but , caught in error "unexcepted token"
what will doo,,,
coding here is

const timezone ='Europe/vilius'

const moment = require( 'moment').tz.setDefault(timezone)

let sequelize = new sequelize ('sooriyan' , 'root' , 'password',{
timezone: timezone
})
CreateDate: {
    type: DataTypes.DATEONLY,
    get: function() {
        return moment.utc(this.getDataValue('CreateDate')).format('YYYY-MM-DD')
    }
},
CreateTime: {
    type: DataTypes.TIME,
    get: function() {
        let time = this.getDataValue('CreateTime')

        if (moment(time, moment.ISO_8601, true).isValid()) {
            return moment(this.getDataValue('CreateTime')).format('HH:mm:ss')
        } else {
            return time
        }
    }
} 

DB.moment.create({
    CreateDate: now,
    CreateTime: now
}).then(function(created) {
    console.log(created.CreateDate);
    console.log(created.CreateTime); 
})


erroe is ,,,,

SyntaxError: Unexpected token :
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
