### ISSUE TITLE
Cannot query createdAt column in Postgre

### ISSUE THREAD

**Issue by mateeyow** [sequelize/sequelize#2543]
Is there a way to query createdAt or updatedAt column in postgre database, because everytime I try to create a query with order for createdAt, I always get an error stating the the createdAt column does not exists. Also, I practice camelcase for column names, so this is a big issue for me as I cannot query my camelCased column.

**Comment by Shrikanta9** [comment]
in model "createdAt" is camelCase but in migration it is "createdat". I given the field in model still it is giving below error "column "createdAt" does not exist stack in relation 'admin'"

**Comment by Shrikanta9** [comment]
I am upserting data in relation 'admin'

**Comment by Shrikanta9** [comment]
i did it with 
{
timestamps:false
}
in model
