### ISSUE TITLE
smartWhere error when generating where statement

### ISSUE THREAD

**Issue by tomwang1013** [sequelize/sequelize#2589]
https://github.com/sequelize/sequelize/blob/v1.7.10/lib/utils.js#L146:
 `_where._ = where._ || {queries: [], bindings: []}`
It should be:
 `_where._ = _where._ || {queries: [], bindings: []}`

Otherwise, `_where._.queries` will always contains only one condition

**Comment by BridgeAR** [comment]
Do we still fix bugs in 1.7? SmartWhere was removed in 2.x.x

**Comment by mickhansen** [comment]
We don't no.

**Comment by janmeier** [comment]
:fire:
