### ISSUE TITLE
Prefixed tables names

### ISSUE THREAD

**Issue by typeofweb** [sequelize/sequelize#259]
Does Sequelize support prefixed tables names when using Sequelize.js ?

The only way now is to use `sequelize.define(prefix + 'name' ...)` but this is quite problematic. Moreover such approach will generate strangely named tables for many-to-many relations (`prefix_xxprefix_yy` instead of more natural `prefix_xxyy`).

A function similar to `sequelize.setPrefix` would be nice.

**Comment by manixx** [comment]
Thank you for this feature!

Is there a way to define the schema globally? So every model automatically uses a certain schema?

**Comment by willin** [comment]
same question. global tables prefix

like:

- a_categories
- a_user
_ a_xxxxxx

@durango  how to use?

**Comment by igordeoliveirasa** [comment]
+1
