### ISSUE TITLE
bulkCreate "INSERT OR IGNORE" capability

### ISSUE THREAD

**Issue by danb235** [sequelize/sequelize#2626]
Is it possible to use `bulkCreate` to insert multiple rows and ignore if the key is unique and exists?  Currently when I update a table I get an error with the following:

```
{ [SequelizeUniqueConstraintError]
  name: 'SequelizeUniqueConstraintError',
  message: undefined,
  parent:
   { [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: Files.path]
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
     sql: 'INSERT INTO `Files` (`id`,`path`,`status`,`filename`,`filtered_filename`,`width`,`height`,`size`,`duration`,`createdAt`,`updatedAt`) VALUES ...
```

**Comment by cirosantilli** [comment]
Worth noting that it might not return generated IDs on the JavaScript objects currently: https://github.com/sequelize/sequelize/issues/11223
