### ISSUE TITLE
Consistent formatting across dialects for DATE fields

### ISSUE THREAD

**Issue by yonjah** [sequelize/sequelize#2627]
if you have a column type DATE in your DB it will not be fetched properly since the MariaDB dialect tries to add TZ parameter to it before parsing it.

*I created a pull request to fix this issue #2614 

Also this parsing is happening when I send the custom query with `raw` sets to true.
If I'm understanding the function of `raw` this should not happen -
_If true, sequelize will not try to format the results of the query, or build an instance of a model from the result_

**Comment by janmeier** [comment]
MariaDB uses the same formatting as mysql, so this isssue is now fixed.

With regards to the original question - there is no way to circumvent the date parsing, short of disabling it completely for all queries. `raw` only avoids creating instances and formatting the data from join queries
