### ISSUE TITLE
ID required in Junction table? :(

### ISSUE THREAD

**Issue by ErikvdVen** [sequelize/sequelize#2629]
Hello all,

We have a junction table which does not contain a primary key... It has a unique index on two columns (user_id, profile_id) and those are both foreign keys. How do I tell Sequelize JS to not use any primary key in that model?

So far we know this is not possible.... Cause if we do this, it creates a primary key itself (called ID):
```
    var definition = {
        user_id: {
            type: DataTypes.INTEGER,
            allowNull: false
          //  references: "users", // notice the plural, it's the name of the table
        },
        profile_id: {
            type: DataTypes.INTEGER,
            allowNull: false
          //  references: "profiles", // notice the plural, it's the name of the table
        }
    };
```

**Comment by janmeier** [comment]
Closed in favor of https://github.com/sequelize/sequelize/issues/311
