### ISSUE TITLE
Sequelize + Postgres: 100% CPU usage, memory sky rocketing

### ISSUE THREAD

**Issue by kytwb** [sequelize/sequelize#2632]
Just a quick report on something I experienced many times. Using `includes` to fetch associations, my nodejs process goes wild, taking 100% of CPU and using all the memory available. It's hard to reproduce in local as it has something to deal with my database set state on my staging server.
I'll be back in a bit with more info. I hope. Meanwhile, here the piece of code leading to the issue. Everything's fine before the `return`'s line, then the bug happens and promise never resolves anything (server crashes). It had happened by the past on other sequelize queries.

```javascript
return api.models.prospect.findAll({
    where: {
        merchantId: '1'
    }, includes: {
        all: true,
        nested: false
    }
}).then(function (result) {
    connection.response = result;
});
```

Nobody every experienced / reported anything like this?

**Comment by mickhansen** [comment]
@kytwb would still be nice if you could test selecting the raw BLOB's through raw PG to see if Sequelize is the issue here, but closing this for now.

**Comment by kytwb** [comment]
I've finally been able to reproduce this issue (catched a query leading to the bug and made a backup of my database at this state). It's a postgres issue, currently investigating. Not BLOB-related.

**Comment by mickhansen** [comment]
@kytwb manually run queries are slow too?

**Comment by kytwb** [comment]
@mickhansen not slow, just indefinitly hanging (been waiting for 20/30mn, dataset isn't big at all).
