### ISSUE TITLE
[QUESTION] How to alter table without dropping it?

### ISSUE THREAD

**Issue by NathanFlurry** [sequelize/sequelize#2634]
Hello,

I feel like this may be a moderately simple questions an I'm missing something, but as far as I can tell, when syncing a database, you need to turn on `forced` to add new columns to a table. However, that seems to erase my database, which I don't want.

In MySQL, you can use `ALTER` to do this, but I'm not sure how to do this with SequelizeJS.

Right now, when I alter my `User` object with a new object, whenever I try and access it, it comes back with an error.

Any help would be great.

Thanks!

**Comment by loukmane-issa** [comment]
Hello,
Sorry to ask on this old thread, but did you find out how to alter table with migration?
