### ISSUE TITLE
Why is `unique` not a validator?

### ISSUE THREAD

**Issue by NathanFlurry** [sequelize/sequelize#2640]
Hello,

In my opinion, the `unique` property should be a validator. However, I do understand it's not quite a "validator", since it isn't part of the library. However, it would make mine (and I assume other developer's) life easier, since all the error messages would then be in one, uniform-formated response. The user should be able to know if the username is taken, along with other things wrong with it like length (but it wouldn't be taken in the first but, but you see my point).

If you could consider changing this, that'd be great.

Thanks again!

**Comment by yourcelf** [comment]
I've done this myself by defining an ``isUnique`` validator function, which I can reuse across different models that need unique fields:

    isUnique = function(modelName, field) {
      return function(value, next) {
        var Model = require("../models")[modelName];
        var query = {};
        query[field] = value;
        Model.find({where: query, attributes: ["id"]}).then(function(obj) {
          if (obj) {
            next(field + ' "' + value + '" is already in use');
          } else {
            next();
          }
        });
      };
    }

In the model definition:

    validate: {
      isUnique: isUnique("User", "username")
    }

**Comment by janmeier** [comment]
@yourcelf You are welcome to provide a pullrequest with that functionality. If we include the functionality in sequelize you wouldn't need to pass the table and column name either, since internal validators already have access to that.

+1 If you can make it support composite unique keys as well! :)

**Comment by danpaz** [comment]
+1 I'm having a possibly related problem with the differing implementation between UniqueConstraintError and ValidationError. In particular, since https://github.com/sequelize/sequelize/pull/1024 it is possible to customize the unique constraint error message, but that message doesn't propagate down to the error item. 

```js
{ [SequelizeUniqueConstraintError: That email is already registered.]
  name: 'SequelizeUniqueConstraintError',
  message: 'That email is already registered.',  // <-- my custom message
  errors:
   [ { message: 'email must be unique', // <-- sequelize's default message that didn't get overwritten
       type: 'unique violation',
       path: 'email',
       value: 'me@example.com' } ],
  fields: { email: 'me@example.com' } }
```

This means that in my route I need to catch UniqueConstraintErrors and modify them to use the custom message. 

```js
...
.catch(sequelize.UniqueConstraintError, function(err) {
          err.errors.map(function (errItem) {
            errItem.message = err.message;
          });

          res.status(400).send(err);
```

I wonder if this is more likely a bug or a consequence of database errors not being treated as validation errors?

I would tend to agree with @janmeier that whether to validate uniqueness before hitting the db depends on how frequently you expect that unique constraint to be violated. For my use case, it makes sense to let the db handle unique violations because it happens so infrequently and avoids making an additional db request.

**Comment by vanwalj** [comment]
This may become problematic if you use transactions for example, and definitely not performance friendly :)

**Comment by BridgeAR** [comment]
It's one query more than you need, thus slowing the average use case. As @janmeier mentioned, it would only be a good consideration to use something like that if your application relies on a lot of unique duplicates. In most applications this is probably not the case.
Besides that I'm always wondering if I'm the only one who'd never send out all model errors to the frontend as they occur... Those expose information that in most cases no one can handle in the frontend, provide information that the user should often not have and they are language specific so rewriting the application to support multiple languages will be... fun. Instead you could handle all errors in one place and decide what parts you really want to send to the frontend and how.

To conclude: I'd not recommend implementing this into core. This might be a good choice for a plugin.

**Comment by angelxmoreno** [comment]
I will attempt to make a plugin for the use case mentioned by @janmeier

**Comment by angelxmoreno** [comment]
I started something (sequelize-isunique-validator)[https://github.com/angelxmoreno/sequelize-isunique-validator]

**Comment by linxixuan** [comment]
@yourcelf your code is work in add a new record. But it also stops record updating.
So I add change your code like this:
```javascript
isUnique = function(modelName, field) {
  return function(value, next) {
    var Model = require("../models")[modelName];
    var query = {};
    query[field] = value;
    Model.find({where: query, attributes: ["id"]}).then(function(obj) {
      if (obj && obj.isNewRecord) {
        next(field + ' "' + value + '" is already in use');
      } else {
        next();
      }
    });
  };
}
```

**Comment by fadec** [comment]
Using a select before an insert isn't always going to work with concurrent connections. Perhaps just try to insert or update and then check the connection for the error code.

I'm using postgress (npm "pg") and a unique violation error looks like this...

```
{ error: duplicate key value violates unique constraint "category_name_idx"
    at Connection.parseE (/home/sam/ykcorner/server/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/sam/ykcorner/server/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/home/sam/ykcorner/server/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 203,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (name)=(Dogs) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'catalog',
  table: 'category',
  column: undefined,
  dataType: undefined,
  constraint: 'category_name_idx',
  file: 'nbtinsert.c',
  line: '433',
  routine: '_bt_check_unique' }
```

DB error codes are the most correct and performant way to go. Look up SQLSTATE code 23505 (unique violation) in the following different docs and you'll see there is some level of standardization. Unfortunately, each product will probably need its own shim to generate nice error messages.

https://www.postgresql.org/docs/current/static/errcodes-appendix.html
http://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzala/rzalaccl.htm
http://docs.oracle.com/javadb/10.6.2.1/ref/rrefexcept71493.html

**Comment by corysimmons** [comment]
Didn't read over the entire thread so not sure if this has been addressed, but I think that **all** Sequelize validations should live in the `validate` object.

My use-case is wanting to add a unique msg to the `unique` validator.

I see there is a plugin, but it just seems like bad practice to separate the functionality of validators. I think most people, including your "average user", would prefer this approach as you wouldn't have to memorize that "_some_ validators go here, _some_ go there".

**Comment by vodniciarv** [comment]
Example of isUnique validator:
```
phone: {
      type: Sequelize.STRING(18),
      validate: {
        isUnique(value, next) {
          user.find({
            where: { phone: value },
            attributes: ['id']
          }).done((user) => {
            if (user)
              return next('errors.phone.unique');

            next();
          });
        }
      }
```

**Comment by papb** [comment]
> I think most people, including your "average user", would prefer this approach as you wouldn't have to memorize that "some validators go here, some go there".

This is a fair point, but I'd say this is a matter of documentation. There is a reason for the UNIQUE constraint to be in a different place than the other usual validators. The reason is that the UNIQUE constraint is enforced at the database level, i.e., the SQL itself contains this validator; the other usual validators are just javascript checks performed by sequelize.
