### ISSUE TITLE
[feature] basic node-webkit support

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2645]

**Comment by ua2004** [comment]
I can add that migrations don't work after sqlite3 has been compiled for node-webkit. As mentioned [here](https://www.npmjs.com/package/sqlite3#building-for-sqlcipher),

> After the sqlite3 package is built for node-webkit it cannot run in the vanilla Node.js (and vice versa).

Migrations run in CLI using vanilla Node.js mode and therefore are useless when sqlite3 package is compiled for node-webkit.
