### ISSUE TITLE
Sequelize.sync({ force: true }) is too dangerous to live.

### ISSUE THREAD

**Issue by dkushner** [sequelize/sequelize#2670]
While useful for testing purposes, `Sequelize.sync({ force: true })` makes a number of dangerous assumptions about the relationship between ORM and the backing data store. Most concerning is that it assumes that the model definitions represent the entirety of the underlying table's schema. This is a dangerous claim for a few reasons:

1. In order to ensure a 1:1 parity between ORM model definitions and the underlying schema, the user must clutter their model definitions with attribute hints to help the ORM understand how to build the schema. This is a task for a migrator, not an ORM. If we look at ActiveRecord or Knex/Bookshelf, we see  an entirely separate system at play for schema-building and model-building. 

2. This may be opinion rather than principle, but I believe the ORM should refrain as much as possible from altering the _structure_ of the underlying schema while providing a layer of abstraction for manipulating the _data_ within that schema. With the excellent work @sdepold is doing, hopefully we will have a migration system robust enough to allow for this separation of concerns.

3. The user may be leveraging database features that are transparent to the ORM that would be disrupted by the indiscriminate modification of the schema. Examples include FDWs and polymorphic tables for Postgres.

I propose that the behavior of `Sequelize.sync({ force: true })` be altered such that it merely deletes the _contents_ of the table without touching the schema. Alternatively (and avoiding breaking changes), a separate { truncate: true } option could be provided to the sync method.

**Comment by zeeshanjan82** [comment]
I have few questions around the sync functinality using sequelize. As I understand sequelize-cli uses Umzug internally for doing all the migrations.What is the procedure for Alter Table, suppose I would like to alter the model in sequelize and let sequelize cli create the migration script for me , how can sequelize cli create the migration script by going through all the model changes or do I have to create the migration scripts myself.

**Comment by sushantdhiman** [comment]
It appears we will support `force: true` option. This discussion can be close then @janmeier @mickhansen ?

**Comment by mickhansen** [comment]
Yeah, we still want `diff` some day, but for now `force: true` has it's uses.

**Comment by Ninja-Coding-Git** [comment]
is there a way to prompt in console if we wish to proceed with sync force true? something like a confirmation? justs asking.

**Comment by spitWind** [comment]
> 如果我们希望继续使用sync force true，有没有办法在控制台中提示？像确认一样的东西？只是问。

手动敲命令吧~.~ 别在后端实例运行了

**Comment by aaronarul** [comment]
> maybe protect production environment by checking NODE_ENV
> 
> ```js
> if (process.env.NODE_ENV == "production") {
>   throw new Error("Forced sync is disabled in production");
> }
> ```

How would i change the development mode into production mode?

**Comment by T0TProduction** [comment]
> > maybe protect production environment by checking NODE_ENV
> > ```js
> > if (process.env.NODE_ENV == "production") {
> >   throw new Error("Forced sync is disabled in production");
> > }
> > ```
> 
> How would i change the development mode into production mode?

You set environment variables inside the environment. So change its value inside your production environment to production, and you're good to go.
[This article](https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa) might help you understand environment variables a bit more.
