### ISSUE TITLE
How can I find out if a model is an instanceof a Model?

### ISSUE THREAD

**Issue by simonexmachina** [sequelize/sequelize#2672]
`Model.build() instanceof Model` throws an Exception, how should I be doing this?

**Comment by hendrul** [comment]
Not working for me, here how to reproduce:
```javascript
let Sequelize = require('sequelize'); 
let sequelize = new Sequelize(null,null,null,{dialect: 'sqlite'}); 
let Model = sequelize.define('Model',{},{sequelize}); 
User instanceof Sequelize.Model  //<-- FALSE!
```

**Comment by aexmachina** [comment]
@hendrul `instanceof` checks whether an _instance_ has a given class in its prototype change. You're passing _a class_, not an instance.

**Comment by hendrul** [comment]
@aexmachina oh god! you're right

**Comment by nikksan** [comment]
`Instance` no longer exists on `Model` entities

**Comment by mickhansen** [comment]
@nikksan `instanceof Model` should work now

**Comment by nikksan** [comment]
@mickhansen Great!

**Comment by rsshilli** [comment]
If using `instanceof` gives you the creeps or doesn't work, this might be a better answer: https://stackoverflow.com/a/42166942/491553
