### ISSUE TITLE
Migration with schema support

### ISSUE THREAD

**Issue by bluecenter** [sequelize/sequelize#2677]
We may have one or more databases with many schemas with name following the the pattern for example, database 0 has schema TEST_0, TEST_1, TEST_2...., database 1 has schema TEST_0, TEST_1, TEST_2...., database 3...... 
We want to migrate all the schemas in all the databases with one migration file like CREATE TABLE, ADD COLUMNS, DROP COLUMNS, CREATE FUNCTIONS, TRIGGERS and so on.
There are two options for us, one is to use sql script, another one is to call sequelize migration function. In sql script, we can manually replace all the schema name in the template migration files. Something like this in sql script CREATE TABLE schema.people. we replace schema.people to database_0.test_0.people. In migration files, we can pass schema name. 
So if Sequelize can take the schema name pattern or schema list, and migrate all the schemas in the database, that would be awesome.  

Please let me know if you have any questions.

**Comment by adeelhussain** [comment]
On which version this option passing is support?
