### ISSUE TITLE
Validate function fails on object literals in node-webkit

### ISSUE THREAD

**Issue by sarme** [sequelize/sequelize#2685]
I am getting "The parameter (value: [object Object]) is no Object" in my node-webkit application from the validate function in utils/parameter-validator.js.  The validate function looks like this:

```javascript
var validate = function(value, expectation, options) {
  if (value instanceof expectation) {
    return true;
  }

  throw new Error(util.format('The parameter (value: %s) is no %s.', value, expectation.name));
};
```

Here's a simple example of a node-webkit app that generates this issue:

```javascript
<!DOCTYPE html>
<html>
<head>
    <title>Object Literal Example</title>
</head>
<body>
 	<script type="text/javascript">
		var Sequelize = require("sequelize");

		var sequelize = new Sequelize('database', 'username', 'password', {
		  dialect: 'sqlite',
		   storage: 'test.db',
		  omitNull: true,
		  sync: { force: true },
		  syncOnAssociation: true
		});

		var User = sequelize.define('User', {
		  username: Sequelize.STRING,
		  birthday: Sequelize.DATE
		});

		sequelize.sync().success(function() {
		    var param = {
		        username: 'sdepold',
			    birthday: new Date(1986, 06, 28)
		    };

		  User.create(param).success(function(sdepold) {
		    console.log(sdepold.values)
		  })
		  .error(function(err){
		  	console.error(err);
		  });
		});
 	</script>
</body>
</html>
```

The error occurs on the "User.create" call.

I'm using node-webkit 0.8.6 with sequelize&#64;2.0.0-rc3.  I cannot reproduce this in straight Node.js, so I suspect it's something specific to node-webkit.  

My environment was installed using the following:
```
npm install nodewebkit@0.8.6 -g
npm install nw-gyp -g
npm install sequelize
npm install sequelize-sqlite
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target="0.8.6"
```

Here's what it looks like when I break in the function:
![image](https://cloud.githubusercontent.com/assets/1462568/5329553/8d91b95e-7d79-11e4-8b32-0ce6f0c8ef15.png)

Notice how expectation looks like a constructor.  Its type at this point is "function", so it makes sense that it would fail when we actually are expecting an Object.  

Changing the function to the following makes it work for me:

```Javascript
var validate = function(value, expectation, options) {
  if (value instanceof expectation || typeof(value) === typeof(new expectation())) {
    return true;
  }

  throw new Error(util.format('The parameter (value: %s) is no %s.', value, expectation.name));
};
```

I'm just not sure that's the best way to handle this.  I'd be happy to submit a pull request if this looks like a viable solution and I'd be happy to hear a better suggestion.

**Comment by zoff** [comment]
Any updates on this issue?
Is it still impossible to use Sequelize with literal objects in node-webkit?

**Comment by janmeier** [comment]
@zoff I think this was fixed in  #2691

**Comment by zoff** [comment]
@janmeier  PR was reverted #2694

**Comment by janmeier** [comment]
Woops, in that case reopening this :)

**Comment by janmeier** [comment]
In that case, this is still a bug - PR welcome

**Comment by BridgeAR** [comment]
To fix the outstanding issue a stricter comparison might fix the problem without triggering wrong deprecation messages:
```javascript
value instanceof options.deprecated || 
Object.prototype.toString.call(value) === Object.prototype.toString.call(options.deprecated.call();
```
@janmeier @mickhansen what do you think?

**Comment by mickhansen** [comment]
@BridgeAR That could work

**Comment by janmeier** [comment]
Yep, sounds like the cleanest solution

**Comment by jlescot** [comment]
Hi,

I got the same issue, but in my case, I could not get the error message displayed. This is because the `util.format('The parameter (value: %s) is no %s.', value, expectation.name)` expression is raising an Exception because the `value` variable is considered as an Object and it can't be converted into a String. Here is the exception which is raised:

```
error: TypeError: Cannot convert object to primitive value
    at String (native)
    at util.js:39:36
    at String.replace (native)
    at Object.exports.format (util.js:35:23)
    at validate (D:\dev\github\AirVantage\node-tech-db\node_modules\sequelize\lib\utils\parameter-validator.js:26:35)
```

I guess that fixing this following @BridgeAR proposal should fix in the same time the unexpected exception in the `util.format()` call.
