### ISSUE TITLE
table schema vs database (postgres) schema

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2688]
I'm thinking of placing all the current migrator/queryinterface code under something like `sequelize.schema` to make changing schemas more of a first class citizen of the project.

However we need a way to distinguish, both in code and in tests between a table schema and a database schema.

Any ideas?

**Comment by mickhansen** [comment]
What about just `sequelize.table.*`?

**Comment by mickhansen** [comment]
`sequelize.table.create`

**Comment by mbroadst** [comment]
:+1: that looks clean

**Comment by sdepold** [comment]
sounds good.

**Comment by overlookmotel** [comment]
Just a thought on naming... how about calling a schema in the Postgres sense "schema" and a schema in the database sense "database"?

Seems the simplest. Or have I got mixed up what schema means?

**Comment by mickhansen** [comment]
@overlookmotel in this sense we're talking about table schemas :)

**Comment by BridgeAR** [comment]
Sounds like you found a conclusion with `sequelize.table.*`.
