### ISSUE TITLE
test structuring

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2689]
should we structure tests by feature -> method or method -> feature?

For example: `increment` schema support, do we create a test/schemas/increment test or a test/increment/schema test?

Another example: hasMany include support

I think it would be great to have a discussion about this and atleast decide on one way of doing things.
Personally i'm not quite sure which way i'm leaning.

**Comment by BridgeAR** [comment]
@mickhansen Is this still open for discussion or did you decide how to handle it? (In my opinion it's not all that important as long as it's handled the same way all the time). So this is maybe ready for closing?

**Comment by mickhansen** [comment]
No real guideline
