### ISSUE TITLE
unit testing sql generation

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2690]
Currently we do a small bit of sql generation testing but we keep removing some of it since it keeps breaking when implementation changes.

I must admit i prefer integration tests. But i also realize that we should start providing a lot better support for schema changes and that might be easier (and faster) to do by unit testing vs generated SQL since integration testing a schema/column change might be tricky.

Opening up the floor for discussion.

**Comment by BridgeAR** [comment]
I guess here's no discussion left. To conclude: everyone wants to use more unit tests. How exactly might still be open but that's probably not really an issue. So I'd close this.
