### ISSUE TITLE
Regression: Postgres arrays are not saved/updated anymore

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#2700]
Hey, about two days ago I realized that something is not saved anymore so I had a look at it today and I found that the commit 5c5cb18a33ec8df10f694dd2dc59b5e862d2d128 changed the update behavior for Postgres arrays. The object is indeed updated but one of the elements updated is an array and that one is skipped.

My Model is:

column: {
    type: DataTypes.ARRAY(DataTypes.ARRAY(DataTypes.STRING)),
    defaultValue: []
},

**Comment by BridgeAR** [comment]
Hey, sorry I forgot to anwser here. Your suggestion worked :)

But I think it's quite unintuitive that the original way is not working and other people might get into trouble because of this, without noticing anything.

I ran into a similar problem with this code:
```javascript
var misc = user.get('misc');
if (misc) {
    misc.lastLogin = (new Date(Date.now())).toString();
} else {
    misc = {
        lastLogin: (new Date(Date.now())).toString()
    };
}
// sequelize does not recognize that misc has changed properly
// setting it to null first avoids that problem
user.set('misc', null);
user.set('misc', misc);
return user.save({
    transaction: t
});
```
where misc is an HSTORE

**Comment by mickhansen** [comment]
Hmm yes it's probably do `===` internally hence why the same object is not triggering.

**Comment by BridgeAR** [comment]
At least the last part should work without setting it to null. Do you want me to open a new ticket for it?

And I also think that my original case:
```javascript
object.columnOne = 'something';
object.columnTwo.push(['', '', '']);
return object.save({
    transaction: transaction
});
```
should work without using your solution. Otherwise it's just not intuitive to use. It should be easy to accomplish this by using lodashes _.isEqual and do a deep compare. It's of course a question how fast that is, so it might be good to introduce a flag to deactivate the deep equality check. But this is only important to people who save big objects in JSON / JSONB or use big Arrays.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/2863
https://github.com/sequelize/sequelize/issues/2862

**Comment by BridgeAR** [comment]
<3
