### ISSUE TITLE
Add `(before/after)Save` hook

### ISSUE THREAD

**Issue by luin** [sequelize/sequelize#2702]
I'm using 2.0.0-rc3 and finding out that there are `beforeCreate` and `beforeUpdate` but no `beforeSave`.

The reason `beforeSave` is useful is that I want to hash users' password before saving. If there's no `beforeSave`, I have to write the logic of hashing password in two place(both `beforeCreate` and `beforeUpdate`), otherwise, I can just write:

```javascript
beforeSave: function(instance, options) {
  if (instance.isModified('password')) {
    return hash(instance.password).then(function(hashedPassword) {
      instance.password = hashedPassword;
    });
  }
}
```

btw, I also wonder whether there's a `isModified` method to check if a field has been modified(or created).

Related file:
https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L581

Related question:
http://stackoverflow.com/questions/21411848/pre-save-hook-and-instance-methods-in-sequelize

**Comment by xpepermint** [comment]
+1

**Comment by ashlinchak** [comment]
+ 1
I don't see any performance issues for adding synthetic sugar for two hooks.
