### ISSUE TITLE
Use transaction in the hooks

### ISSUE THREAD

**Issue by luin** [sequelize/sequelize#2704]
I'm using 2.0.0-rc3. I want to use transaction in the `beforeCreate` hook. My scenario is that when a user instance is created, the `beforeCreate` will increase the `userCount` field in another model. If it's failed to create the user or is failed to incr the `userCount`, I want a rollback. My code is like this:

``` javascript
// user model hook
beforeCreate: function(user, options) {
  return sequelize.transaction().then(function(t) {
    options.transaction = t;
    return Stat.incr(1, { transaction: t }).catch(function(err) {
      t.rollback();
      throw err;
    });
  });
},
afterCreate: function(user, options) {
  // commit the transaction when success
  options.transaction.commit();
}
```

In the code, transaction will rollback if `Stat.incr` is failed, but there's no chance to rollback if the `user.create` is failed.

I know that I can create an transaction outside the model and reuse it in the `beforeCreate` hook like:

``` javascript
// outside the model
sequelize.transaction().then(function(t) {
  User.create({...}, { transaction: t }).then(function() {
    t.commit();
  }).catch(function() {
    t.rollback();
  });
)};

...
// user model hook
beforeCreate: function(user, options) {
  return Stat.incr(1, { transaction: options.transaction });
}
```

But it looks strange because if people don't look into the model definition, it'll seem the transaction is useless as it's only used in one query.

**Comment by BridgeAR** [comment]
I guess here's nothing more we can do right now. Btw: CLS might be a good option for hooks too. That way every query called in the hook will use the transaction automatical.

**Comment by yelvert** [comment]
What's the status on this? There really needs to be a way to access the transaction that will be used for the save in any of the hooks. That way you could do something like

```ruby
Parent.beforeUpdate( async (parent, options, transaction) => {
  if (options.include && options.include.indexOf(Child) > -1 && parent.child) {
    await parent.child.save({ transaction })
  }
});
```

This way associations can automatically updated and rolled back, rather than having to manually manage the transactions every time you need to update associations. This gets especially painful when handling multiple top level associations or deep nested associations.

**Comment by felixfbecker** [comment]
@yelvert What is wrong with `options.transaction`?http://docs.sequelizejs.com/en/v3/docs/hooks/#a-note-about-transactions

**Comment by yelvert** [comment]
Just what I said before, that requires manually wrapping the create in a transaction, rather than just making save/create/update make a new transaction if one is not originally passed, and make that transaction available to the hooks. Or may maybe, make save/create/update take a 'transaction: true' option that would trigger the previously stated functionality.

**Comment by felixfbecker** [comment]
Implicit transaction sounds a bit to magic for me, and controlling it from the outside doesn't make much sense if the hook always depends on the behavior.

For now you have to write some boilerplate, but it is possible.
```js
beforeCreate(async (user, options) => {
  if (!options.transaction) {
    options.transaction = await sequelize.transaction()
  }
  try {
    await whatever
  } catch (e) {
    options.transaction.rollback()
    throw e
  }
})
afterCreate((user, options) => options.transaction.commit())
```

**Comment by marklai1998** [comment]
Hi, I'm having the same issue, my problem is with postgres row level security, which needs to run other sql to set user identity in the same sql

Prisma solved it with [extension](https://www.prisma.io/blog/client-extensions-preview-8t3w27xkrxxn#example-row-level-security), where you can create transaction in the middleware phase

But there is no simple way to achieve it with sequelize

My team came up with this solution, its kinda hacky
```ts
export const beforeQueryHook = (
  sequelize: Sequelize
) => {
  return async (options: any, query: any) => {
    if (!options.transaction) {
      await query.sequelize.connectionManager.releaseConnection(
        query.connection
      );
      const t: any = await sequelize.transaction();
      options.transaction = t;
      query.connection = t.connection;

      const sql = getRlsQuery();
      await sequelize.query(sql, {
        transaction: t,
      } as any);
      options.customTransaction = true;
    } else {
       await sequelize.query(sql, {
        transaction: options.transaction,
        } as any);
     }
  };
};

export const afterQueryHook = () => {
  return async (options) => {
    if (options.customTransaction === true) {
      await options.transaction?.commit();
    }
  };
};
```

I hope there is some official way to achieve this
I do agree with @felixfbecker said "Implicit transaction" is not a good thing, but its a real world use case that a lot of ppl uses
