### ISSUE TITLE
Watching a database for change

### ISSUE THREAD

**Issue by khwerhahn** [sequelize/sequelize#2708]
Is it possible to watch a (remote) database for change and when a change is detected fire an event? Something like object.observe()? 

Would be really neat if you could define a local table and a remote table to watch. When for example certain fields are different or the amount of rows changed to fire an event maybe even return the ids of the changed remote rows. 

I would really like this functionality for advanced syncing of remote databases.

**Comment by amanmahalgavan** [comment]
is there any update on this? Is there a way now to observe for changes in tables in a remote database?

**Comment by eseliger** [comment]
There are no plans on adding this, it can be built using APIs sequelize offers though. But it is not a very generic use-case for an ORM and hence would not need to make the main codebase more complex. If you want you could publish it as a plug-in though :)

**Comment by amanmahalgavan** [comment]
I see. Thanks for the quick response :)
