### ISSUE TITLE
Missing operator is / is not 

### ISSUE THREAD

**Issue by juansev** [sequelize/sequelize#2710]
Although IS NULL AND IS NOT NULL is covered by 
{where:{ field: null }} and {where:{ field: {ne: null }}}
the operators IS TRUE / IS FALSE / IS NOT TRUE / IS NOT FALSE are needed to be able to easily extract the rows that has "deleted" columns and can be 0 / 1 or NULL. I usually get the rows with

SELECT * FROM table WHERE conditions AND DELETED IS NOT TRUE

This behavior can be achieve only using an OR  clause that that is not elegant enough. I would like to use the IS / IS NOT operators. File utils.js should be modified to achieve this.

**Comment by juansev** [comment]
I have made  the modification and a branch has been created. Is there anything else that i have to do? The branch is patch-1

**Comment by janmeier** [comment]
If you go to the main repo page (github.com/sequelize/sequelize) you should see a button that says something like open pull request. 

Remember to add unit test

**Comment by juansev** [comment]
I have noticed that the $not operator makes a similar effect. I think this feature is covered by that operator. How can i remove my branch?

**Comment by janmeier** [comment]
http://gitready.com/beginner/2009/02/02/push-and-delete-branches.html
