### ISSUE TITLE
Does sequelize have tools for tracking history of tables and  storing/retrieving files?

### ISSUE THREAD

**Issue by lvarayut** [sequelize/sequelize#2711]
I have some following basic questions, I have searched about them but didn't find any documentation. 
1. I wanted to keep history of tables. Let's say I have an application form. A user submits the form once a year, I would like to track history of this user against the submitted form version. For example, I could see the application information of the last two years filled by this user. Does sequelize provides some tools for managing history?
2. I wanted to store files as BLOB. I would like to divide a file into chunks and store them, and then, retrieve it as object. Does sequelize have some tools for handling files?

**Comment by asaf050** [comment]
Hey,

I know this is old issue but it came first result in Google so I suggest using this package
https://github.com/bonaval/sequelize-temporal
