### ISSUE TITLE
Requiring sequelize screws up modules

### ISSUE THREAD

**Issue by JoshWillik** [sequelize/sequelize#2730]
So I have this project which relies on Sequelize to work properly; we'll call this project X.
X also uses a module of my own creation, Librarian.

The problem is, they don't seem to co-exist peacefully in the dependency list.

If  I list Sequelize in the dependencies of X, a module under librarian becomes unable to access the sqlite3 module and breaks. If I remove Sequelize, everything works as it should.

Just to get this out of the way, I've tried clearing the npm cache, I'm running the latest version of npm, I've found this issue on more than one machine, (Arch Linux & Ubuntu 14.04).

Here's a [test-project](https://github.com/JoshWillik/sequelize-issue) with both working and non-working package.json's. The only difference is the sequelize dependency.
It also has an `index.js` to test whether it's working.

**Comment by janmeier** [comment]
Closing this as an npm edge-case bug. The idea of separate stores is still interesting, but not something that will be implemneted anytime soon :)
