### ISSUE TITLE
Host<-> Client data binding

### ISSUE THREAD

**Issue by Domiii** [sequelize/sequelize#2733]
Currently, the biggest issue with Sequelize for me is the fact that while on the server, I get some nicely decorated instances to work with, sadly, in order for the client to work with it, I need to separate the data from the decorations, serialize it, send it to the client, and then re-decorate it, using my own decoration method (since Sequelize does not run on any other JS run-time but Node).

Data binding is the holy grail of distributed applications, be it p2p or plain old Client<->Server architecture. However, current solutions, like [meteor](https://www.meteor.com/) are heavily [opinionated](http://programmers.stackexchange.com/questions/12182/what-does-opinionated-software-really-mean), and they try to do much more than just network-striding data binding.

I was hoping that Sequelize could fix that by providing:
1. a simple way of accessing the Sequelize "DB interface language" (i.e. all the arguments to database query methods, such as `find`, `create`, `destroy` etc.) from the client as well,
2. the ability to easily exchange Sequelize instances between client and server

Of course, it would require an additional layer of customizable access management, and I understand that the whole idea would significantly enlarge Sequelize's scope, but is this not a worthy path to be on? :)

**Comment by cvsguimaraes** [comment]
+1
@mickhansen in the meantime has anything been done in this matter?!
Is sequelize more browserify-friendly now?!

**Comment by mickhansen** [comment]
I believe it's browserify/webpack friendly now, but that's probably the extent of it.

**Comment by cvsguimaraes** [comment]
@mickhansen so I can it is somewhat doable even by regular developer (i.e nodejs newcomer)?!

I think it's very important to have the ability to use our class models as data contracts on client-side, getting validations to work on the browser also would be a huge plus. 
In the other hand, anything else should strictly be done though your own API IMHO.

So basically I'm gonna try to rip off any unwanted stuff then browserify the rest, probably going to be a separate project to reduce complexity. I update here if this ever come to existence :)

Any heads up towards this are welcome :sweat_smile:

**Comment by mickhansen** [comment]
That would definitely be a plus, but not a specific goal for the maintainers at this point.
