### ISSUE TITLE
Incorrect JOIN presidence in complex `include` scenario

### ISSUE THREAD

**Issue by Domiii** [sequelize/sequelize#2734]
**UPDATE**

This issue has shifted a bit. The exact explanation of this issue, including pseudo code can be found [below](https://github.com/sequelize/sequelize/issues/2734#issuecomment-97330031).

**Original report**

In my current scenario, I have three tables: `Problem`, `Rating`, `RatingCategory`, with the following associations:

```
`Problem` hasMany `Rating`
`Rating` belongsTo `RatingCategory`
```

When fetching from `Problem`, this is a possible `include`:

```
[{
    model: Rating,
    as: 'ratings',
    include: [{
        model: RatingCategory,
        as: 'category',
        where: {
            typeId: typeId,
            isPublic: true
        }
    }]
}]
```

Obviously, I only want to get `Rating`s whose `RatingCategory` matches the given `where`, so the nested `include` must be required. However, now, if a problem has no ratings, I don't get anything at all. That is due to incorrect [JOIN presidence, as explained here](http://stackoverflow.com/a/6391224/2228771).

Sequelize simply takes the given `include` hierarchy and flattens it:

```
SELECT * FROM 
    Problem
    LEFT JOIN Rating ON (C1)
    INNER JOIN RatingCategory ON (C2)
```

but because the JOIN operators are [left associative](http://en.wikipedia.org/wiki/Operator_associativity), its the same as:

```
SELECT * FROM 
    (
        Problem
        LEFT JOIN Rating ON (C1)
    )
    INNER JOIN RatingCategory ON (C2)
```

While I actually need:

```
SELECT * FROM 
    Problem
    LEFT JOIN (
        Rating
        INNER JOIN RatingCategory ON (C2)
    ) ON (C1)
```

From looking at [dialect/abstract/query-generator](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L878), it appears, I can only control whether an include is required or not, but not change presidence.

Any short-term solutions?

**Comment by BridgeAR** [comment]
@Domiii Would you be so kind and provide a testcase, or is the issue maybe already fixed?

**Comment by Domiii** [comment]
Hi! Sorry for totally slacking off here, and thanks for reminding me!

Turns out it (at least my current test case) works just fine! Not sure, if its different from what I originally planned or if my original code had bugs or if you simply fixed it in the meantime!

Anyway, this is the (working!) test case (code below).

The gist of the structure:

    Item.hasMany(Comment);
    Comment.belongsTo(Item);

    Comment.hasMany(Rating);
    Rating.belongsTo(Comment);

My query:

	// get all items with all comments which have at least one rating with value = 1
    	return Item.findAll({
    		include: [{
				model: Comment,
				include: [{
					model: Rating,
					where: {
						value: 1
					}
				}]
			}];
    	});

Works!


Code:

	"use strict";

	var Sequelize = require('sequelize');
	var sequelize = new Sequelize('test', 'root', 'r00t');

	// make Promise global
	GLOBAL.Promise = Sequelize.Promise;


	// Item
	var Item = sequelize.define('Item', {
	    id: {type: Sequelize.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true},
	    name: Sequelize.TEXT
	});

	// one Item has many Comments
	var Comment = sequelize.define('Comment', {
	    id: {type: Sequelize.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true},
	    content: Sequelize.TEXT
	});

	Item.hasMany(Comment);
	Comment.belongsTo(Item);

	var Rating = sequelize.define('Rating', {
	    id: {type: Sequelize.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true},
	    value: Sequelize.INTEGER
	});

	Comment.hasMany(Rating);
	Rating.belongsTo(Comment);

	// (re-)create tables
	return sequelize.sync({force: true})
	.then(function() {
		// create test data
	    return Promise.join(
		  	Item.create({
		  		name: 'item1'
			}),
		  	Item.create({
		  		name: 'item2'
			})
	    )
	    .spread(function(item1, item2) {
	    	return Promise.join(
	    		Comment.create({
	    			content: "comment1a",
	    			ItemId: item1.id
	    		}),
	    		Comment.create({
	    			content: "comment1b",
	    			ItemId: item1.id
	    		})
			)
			.spread(function(comment1a, comment1b) {
				return Promise.join(
					Rating.create({
						value: 1,
						CommentId: comment1a.id
					}),
					Rating.create({
						value: 1,
						CommentId: comment1a.id
					}),
					Rating.create({
						value: 2,
						CommentId: comment1a.id
					}),
					Rating.create({
						value: 3,
						CommentId: comment1b.id
					})
				);
			});
	    })
	    .then(function() {
			// get all items with all comments which have at least one rating with value = 1
	    	return Item.findAll({
	    		include: [{
					model: Comment,
					include: [{
						model: Rating,
						where: {
							value: 1
						}
					}]
				}]
	    	});
	    })
		.then(function(itemsWithAssociations) {
			// check results
			console.assert(itemsWithAssociations.length == 1, 'Incorrect amount of items = ' + itemsWithAssociations.length);
			console.assert(itemsWithAssociations[0].Comments.length == 1, 'Incorrect amount of comments = ' + itemsWithAssociations[0].Comments.length);
			console.assert(itemsWithAssociations[0].Comments[0].Ratings.length == 2, 'Incorrect amount of ratings = ' + 
					itemsWithAssociations[0].Comments[0].Ratings.length);
			console.assert(itemsWithAssociations[0].Comments[0].Ratings[0].value == 1, 'Incorrect rating value!');

			console.log('All tests passed!');
		});
	});
