### ISSUE TITLE
how to associate the model which has two primary keys

### ISSUE THREAD

**Issue by ryanking8215** [sequelize/sequelize#2737]
I have two models `A` and `B`.
A has one primary key `id`, `B` has two primary keys `bid1,bid2`
The association of `A` and `B` is many-to-many, So the third join table is needed. 

how to define the association?

I tried `foreignKey:['bid1','bid2']` using `hasMany`, but it didn't  work.

**Comment by janmeier** [comment]
Closed in favor of https://github.com/sequelize/sequelize/issues/311
