### ISSUE TITLE
Scoped model is not reusable.

### ISSUE THREAD

**Issue by darren-clark** [sequelize/sequelize#2738]
Model.scope returns a Model. My reading is that this is a model that limited to results as defined by the scope. e.g. Only since <b>date</b>, owned by <b>user</b> etc. This would be useful to hold onto and pass around or reuse.

However, any query that is executed against this model retains the query as part of the models scopeObj, reusing parameters on subsequent queries.

Example:

```javascript
var Sequelize = require('sequelize')
    , sequelize = new Sequelize('test', 'root', '', {
        dialect: 'mysql',
        logging: console.log
    });

var model = sequelize.define('test', { name: Sequelize.STRING }, {
  defaultScope: { where: {} },
    scopes: {
        test: { where: {name:'foo'} }
    }
})
var scoped = model.scope('test');
scoped.find(1).then(function(obj){
    var whee = obj;
})
//        scoped = model.scope('test')
scoped.find({where: { name: 'bar'}}).then(function(obj){
    var whee = obj;
})
```
Results in the following queries:
```
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `tests` AS `test` WHERE `name` = 'foo' AND `id` = 1;
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `tests` AS `test` WHERE `id` = 1 AND `name` = 'bar' LIMIT 1;
```

Note that I also have no idea where the LIMIT is coming from on the second query.

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
