### ISSUE TITLE
Postgres Inet type support

### ISSUE THREAD

**Issue by deepcover96** [sequelize/sequelize#2745]
I will be creating a model that is required to have IPv4, IPv6, and MAC address fields.  I am using PostgreSQL as the database.  Instead of having these attributes only as strings, I would like to use the Inet type in Postgres so I can sort these values properly.  Is there a way to do this through the ORM?  If not, is it recommended to have columns of these types in tables that Sequelize will query, in the event I was to use raw SQL to use the Inet columns?  Thank you in advance.

**Comment by fundon** [comment]
Hi @mickhansen How to define?

Which's this?
```js
ip_address: {
  type: 'inet'
}
```

**Comment by janmeier** [comment]
@fundon The exact code that you showed should work fine

**Comment by fundon** [comment]
@janmeier It works.
I checked the table schema, it's there.
```
│
 company       │ character varying(255)   │                                                    │ extended │              │
 ip_address    │ inet                     │                                                    │ main     │              │
 created_at    │ timestamp with time zone │ not null                                           │ plain    │              │
```

**Comment by gabegorelick** [comment]
This was added to Sequelize in v4.38.0. See https://github.com/sequelize/sequelize/pull/9571.
