### ISSUE TITLE
Update associated object generates "where `id` IS NULL"

### ISSUE THREAD

**Issue by buehler** [sequelize/sequelize#2748]
Good morning everyone

I'm experiencing a weird issue:
I have a model "post" which has an associated model "gallery". When I want to update those models, only the parent gets updated not the associated one.

Even if I update them explicitly, the generated query is wrong.

Example:
new sequelize.Utils.QueryChainer()
            .add(post.updateAttributes(req.body))
            .add(post.Gallery.updateAttributes(req.body.Gallery))
            .run()
...
generates the correct updatequery for "post". But for the gallery it generates:
UPDATE `Galleries` SET ... WHERE `id` IS NULL

**Comment by buehler** [comment]
Not yet :)

**Comment by mickhansen** [comment]
Closing, please test against master and re-open if issue persists.
