### ISSUE TITLE
user sequelize.query function but want to build associated models defined in sequelize

### ISSUE THREAD

**Issue by mike442144** [sequelize/sequelize#2767]
Here I have a question, if I exec sequelize.query function which return many rows, I need all the raw results to be built as models defined in sequelize. I read the doc, and find I can put in a second param to this function, but seems that I can't do the associated models, any idea?

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
