### ISSUE TITLE
Why does 'sequelize migration:create' require the config.json?

### ISSUE THREAD

**Issue by memelet** [sequelize/sequelize#2768]
It does not seem to be used. And in our case, we configure our app similar to 12-factor where all db parameters are set via environment variables. Hence we don't have a static config.json.

I have created a dummy config.json with bogus values just to be able to create migrations. (Of course I don't really need the migration:create, but its handy.)

**Comment by mickhansen** [comment]
Closing this, please continue discussion in the CLI repo.
