### ISSUE TITLE
Reusing objects as attribute definitions is not possible

### ISSUE THREAD

**Issue by hg77** [sequelize/sequelize#2771]
The following code used to work with sequelize _2.0.0-rc2_ but breaks with _2.0.0-rc4_. 
food and drinks have the same value in the assertion.

The problem is the use of the variable _ranktype_. If I repeat the definition twice instead of using ranktype everything works fine.
What's wrong with using a variable in the definition?

Thank you,

 Henryk

``` javascript```
var Sequelize = require('sequelize');
var sequelize = new Sequelize("some-db", "notNeeded", "notNeeded",
                              {"dialect" : "sqlite", "storage" : "some-db.sqlite"} );
var assert = require('assert');

var Review = (function (sequelize, DataTypes) {
  var ranktype = {
           type: DataTypes.INTEGER,
           is:["^[1-5]$|^$"],
          };

  var Review = sequelize.define("Review", {
    Text: DataTypes.TEXT,
    food: ranktype,
    drinks: ranktype,
  }, {
  });

  return Review;
})(sequelize, Sequelize);

var myrev = {
    Text: 'The food was very bad.',
    food: 1,
    drinks: 2,
}

sequelize.sync()
.success(create_review);

function create_review() {
   Review.create(myrev)
   .then(load_reviews);
}
function load_reviews() {
   Review.findAll()
   .then(display_reviews)
}

function display_reviews(reviews) {
  for (var i=0; i <reviews.length; i++) {
     assert.equal(myrev.food, reviews[i].food);
     assert.equal(myrev.drinks, reviews[i].drinks); // This line fails because reviews[i].drinks==1
  }
```

**Comment by mickhansen** [comment]
#2851 is a duplicate

**Comment by sushantdhiman** [comment]
Somehow `_.cloneDeep` not works for this :(

Here is a SSCCE test case for anyone trying to solve it in future

```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();
var assert = require('assert');

var ranktype = { type: Sequelize.INTEGER };
var myrev = { text: 'The food was very bad.', food: 1, drinks: 2 };

console.log("**Before Define**");
console.log(ranktype);

var Review = sequelize.define("Review", {
  text: Sequelize.TEXT,
  food: ranktype,
  drinks: ranktype
});

console.log("**After Define**");
console.log(ranktype);

sequelize.sync({ force: true })
.then(() => Review.create(myrev))
.then(() => Review.findAll())
.then((reviews) => {
  assert.equal(myrev.food, reviews[0].food);
  assert.equal(myrev.drinks, reviews[0].drinks);
});
```

**Output**

```js
Using database:  sequelize-test-72

**Before Define**
{ type: 
   { [Function: INTEGER]
     super_: { [Function: ABSTRACT] warn: [Function: warn], types: {} },
     warn: [Function: warn],
     key: 'INTEGER',
     types: 
      { postgres: [Object],
        mysql: [Object],
        sqlite: [Object],
        mssql: [Object] } } }

**After Define**
{ type: 
   INTEGER {
     options: { length: undefined },
     _length: undefined,
     _zerofill: undefined,
     _decimals: undefined,
     _precision: undefined,
     _scale: undefined,
     _unsigned: undefined },
  Model: Review,
  fieldName: 'drinks',
  _modelAttribute: true,
  field: 'food' }

An unhandled rejection occured:
An unhandled exception occured:

/var/www/sequelize/test/support.js:23
  throw e;
  ^
AssertionError: 1 == 2
    at sequelize.sync.then.then.then (/var/www/sequelize/sscce_template.js:30:10)
```

**Notes**

- `cloneDeep` don't work
- `extend` don't work
- `attributes` are mutated in `Model.init()`
- cloning wont work even if `options` and `attributes` are cloned in `Model.init`
