### ISSUE TITLE
JSON support for MySQL

### ISSUE THREAD

**Issue by jackiesun8** [sequelize/sequelize#2774]
How to store a json field in mysql?

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by wzup** [comment]
@mickhansen, How about [this](https://dev.mysql.com/doc/refman/5.7/en/json.html)? 

> As of MySQL 5.7.8, MySQL supports a native JSON data type that enables efficient access to data in JSON (JavaScript Object Notation) documents. The JSON data type provides these advantages over storing JSON-format strings in a string column:

**Comment by mickhansen** [comment]
@wzup See other issues regarding this, IIRC Travis is lacking support still.

**Comment by janmeier** [comment]
Which is why @toddbluhm is working on switching our travis setup over to docker so we can run 5.7 ;) https://github.com/sequelize/sequelize/pull/6443

**Comment by cheapsteak** [comment]
Should this be reopened? It's been a few months since mysql's supported json

**Comment by sushantdhiman** [comment]
Discussion moved to https://github.com/sequelize/sequelize/issues/4727
