### ISSUE TITLE
upsert generating non-sequential IDs

### ISSUE THREAD

**Issue by jpmonette** [sequelize/sequelize#2777]
After using the new `upsert` function with PostgreSQL, I noticed that the IDs generated are non-sequential when Sequelize is making an update.

For example, if we add 3 values: `['test', 'test', 'test2']`, the first and second one will generate one record with id `1`, while the third one will generate a second record with an id `3`.

I think this has something to do with the fact that the upsert SQL query is executed in one line. Is it possible?

**Comment by janmeier** [comment]
Closing, no response
