### ISSUE TITLE
A new Dialect for Indexeddb and new Dialects in general.

### ISSUE THREAD

**Issue by gaurav21r** [sequelize/sequelize#2779]
I'm a newbie to this project but it seems very interesting and the team and I plan to use it for a HUGE Enterprise Application software where many SQL queries have to be automated.

One of our goals is heavy use of offline databases and then syncing it back to a MySQL backend. I was wondering that is there any work for an IndexedDb Adapter (Dialect) in sequelize in the works?

Incase my team plans to create one will it be accepted by this project through several pull requests? As it will be something client side, how do we go about not breaking the current architecture of the project? Any resources for this?

Also, can the project lead / someone else shed some light into the willingness of the project core members to accept new dialects from the community. Say we want to create a new dialect for MongoDB / CouchDB etc?

I believe that when we add noSQL capabilities to sequelize, people can start using it for making one database to another.

**Comment by janmeier** [comment]
Closing this issue

To anyone stumbling across this, we would definitely be interested in adding indexdb support, if someone pledges to implement and provide support for it.

We'd also need some way to test oracle on travis.

If someone is open for the challenge, please open a new issue if you have specific questions, or post them on IRC
