### ISSUE TITLE
PostgreSQL ENUM type naming is inconsistent

### ISSUE THREAD

**Issue by twodave** [sequelize/sequelize#2785]
When I attempt to sync a model using an `ENUM` type to my postrgresql database with it doesn't calculate the `ENUM` type's name based on the property's `field` option in all cases, thus causing the model to fail to create.

Specifically, when the `ENUM` type is created, the `field` option is not observed on the column name part of the `ENUM`, but when building the query segment for the column using the type, it is. For one-word column names, this is actually not a problem. I could probably track this down in the query builder somewhere, but I figure it's easy to find. More than likely there's just some duplicated-then-slightly-altered code that needs to be refactored to be more DRY. 

An example of a broken setup:
```javascript
var Form = db.define('Form', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    field: 'id',
    primaryKey: true,
    allowNull: false
  },
  formStatus: {
    type: Sequelize.ENUM('preparing','prepared','sending','sent','signing','signed','sealed'),
    defaultValue: 'preparing',
    field: 'form_status',
    allowNull: false
  }
}, {
  paranoid: true,
  freezeTableName: true,
  tableName: 'form',
  underscored: true
});
```
So, in the above case, it creates an `ENUM` named `"enum_form_formStatus"`, but when assigning the type to the table column, it uses `"enum_form_form_status"`, which results in a "No such type" error. To be safe it's probably not a bad idea to make sure the table name is properly being observed consistently vs the model name as well.

The obvious work-around right now is just naming the property and column the same for `ENUM` columns (which results in underscores in my javascript properties, *shudder*).

**Comment by kenkouot** [comment]
Just encountered this with a custom field different than the key defined in the model definition. Fell back to using a STRING type instead of ENUM for that column–any update on this issue?

**Comment by vascofg** [comment]
+1
In my case:
```
Executing (default): DROP TYPE IF EXISTS "enum_test_dev_Users_role"; CREATE TYPE "enum_test_dev_Users_role" AS ENUM('visitor', 'organizer', 'brand', 'administrator');
Executing (default): CREATE TABLE IF NOT EXISTS "test_dev"."Users" ("id"   SERIAL , "email" VARCHAR(255) UNIQUE, "password" VARCHAR(64), "role" "enum_test_dev.Users_role", PRIMARY
 KEY ("id"));
Possibly unhandled SequelizeDatabaseError: type "enum_test_dev.Users_role" does not exist
```

**Comment by janmeier** [comment]
Should be fixed by https://github.com/sequelize/sequelize/commit/00ec6d3b9f09f7a89b37a063ab26bf20c7cd1c4b
