### ISSUE TITLE
Using Semver for real - And not being afraid of bumping major

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2786]
We have been making a lot of BC breaks lately, and we will likely continue to do so.
We can either go down the path of mxing BC breaks into regular releases (like we have been doing) or we can go the more semantic way of bumping major every time.

Personally i've always been a bit against bumping major since major versions seem like a major milestone to me. (2.0 -> 3.0 without any important features?). However it would certainly provide assurances for anyone depending on Sequelize.

If we do decide to use Semver for real (bump major on each BC break) we can't be afraid to bump master (we'll hit large versions numbers soon) however it would also allow us to break BC more freely and timely (instead of having a huge number of breaks between 1.7 and 2.0 for instance).

Thoughts all?

@sdepold @janmeier @mbroadst @overlookmotel @cusspvz @durango @thanpolas

**Comment by nchase** [comment]
Looks like this particular conversation has been dormant for a while, but I wanted to give my two cents on versioning and this looks like the best place for it. Here are a couple of quotes from the conversation above that I wanted to address:

> Personally i've always been a bit against bumping major since major versions seem like a major milestone to me. (2.0 -> 3.0 without any important features?). However it would certainly provide assurances for anyone depending on Sequelize.

<br/>

> a major release should be a big thing, not small changes. A major release is as much a "marketing" milestone as a code one.

If that's what you believe and that's the philosophy you want to use going forward, that's totally OK IMO. Plenty of people do that, some people don't follow the semver spec for similar [and totally valid] reasons. Others, on the other hand (e.g. [`browserify`](https://github.com/substack/node-browserify/blob/master/changelog.markdown), which recently hit 10.0.0) follow it closely, and cut "major" releases without concern for version number, just thinking of it as the semver signifier.

The big thing to point out here is that people are using npm to get `sequelize` as a dependency, and npm uses/expects packages to use semver, and people are increasingly [, or so I think] comfortable with semantic versioning and have a certain expectation [again, just my perception] that the dependencies that they declare will follow it.

The thing that makes this worse is that some people have conditioned themselves to run `npm install --save {packagename}` to fetch dependencies, which currently (in npm 2.6.0, anyway) defaults to the "caret" dependency range e.g. `"sequelize": "^2.1.0"`, so if you continue with the scheme of introducing breaking changes in what semver considers "minor" releases, Sequelize will break for those people, and I think there are potentially a lot of those people. In fact, I just discovered that [your documentation](http://docs.sequelizejs.com/en/latest/docs/getting-started/) suggests that people install Sequelize this way.

I wanted to call out one more thing:
> Yeah, I don't think you guys have enough of a user base to really warrant concern about BC breaks in minor changes.

Sequelize has 73K downloads per week through NPM. Isn't that a pretty big userbase? @mbroadst 

If you're going to deviate from the semver expectation (even if you have plans to follow semver later or in the near future), I think a community-friendly approach could be:

1. do what @overlookmotel called out: state clearly [and maybe even loudly :smile_cat:] in the repo's README that the package doesn't follow semantic versioning, and that caret dependency ranges such as those produced by `npm install --save` should be considered dangerous at this current point in time.
2. given that the project doesn't follow semantic versioning, in the README, also give people some idea of which version ranges will not introduce breaking changes. i.e. if "patch" versions will never introduce breaking changes, but "major" certainly will, and "minor" will sometimes-or-often introduce breaking changes, state that clearly and follow it.
3. in the changelog, call out "backward compatibility changes" as what they are to the users: **breaking changes**, and [if possible] suggest an upgrade path. I [added a bit of text to the changelog notes for the 2.1.0 release](https://github.com/sequelize/sequelize/commit/11d63dcde93b361e19a93115a672faa0bc7c6d07) to help with that, it would be great if when breaking changes were introduced there was always a hint or some kind of note of consideration for people who have upgraded.

If this is how it will be, you might also want to update the documentation and suggest that people use `npm install --save-exact` to prevent this kind of pain.

**Comment by mickhansen** [comment]
"major version = major release" is mostly a psychological barrier that the core team needs to get over i think.
We've been slowed down earlier by having to put of major BC breaks, and then slipping smaller ones into minor releases.

I might be inclined to say that we should start following SEMVER liberally, still missing @janmeier's thoughts on this though.

**Comment by mickhansen** [comment]
The fact that NPM changes the default from `~` to `^` is probably the best argument for starting to follow semver.

**Comment by nchase** [comment]
:thumbsup: :thumbsup: – yeah, I agree the "major version = major release" thing is a psychological barrier...and it _can_ be difficult to get over :)

The thing that I've been telling people is "in semver, versions are cheap" and that seems to help.

**Comment by overlookmotel** [comment]
Although I originally argued that "major version = major release", I'm also tending to change my mind now!

Either way, I think there's a few important points:
1. Make the policy clear in the README (as @nchase says)
2. Plan out changes so that major releases don't come out too often, and when you upgrade you can deal with the pain of a load of breaking changes in one go, rather than having it every month or so
3. Print deprecation warnings on API changes well in advance
4. Where possible, a period of "compatibility mode" where both the new API and old API both work so people have time to switch over, which still enjoying new features

**Comment by overlookmotel** [comment]
PS Sequelize is now getting pretty mature. From what I can see from conversations on Github, most development now seems to be in adding new features, so hopefully breaking changes shouldn't be too common and the extra work of maintaining BC should not be too demanding.

**Comment by janmeier** [comment]
Default `^` is the tipping point for me - bump all around 

![image](https://cloud.githubusercontent.com/assets/1210224/7501070/ec1cd2cc-f431-11e4-94a3-fdd75c64db5f.png)

**Comment by cusspvz** [comment]
@janmeier thumbs up for the meme :laughing:

**Comment by mickhansen** [comment]
Alright, so it's agreed. Sequelize will follow semver from now, all BC breaks will bump major.
However we'll still try to schedule BC breaks and make sure to put in deprecation notices a few versions in advance.

**Comment by overlookmotel** [comment]
Is there a branch for v3 which breaking changes should be PR-ed against?

**Comment by mickhansen** [comment]
@overlookmotel No, i'd really like not to have to maintain seperate branches of development.
If something majorly furthers the development of the project we should just release everything we have at that time and then prepare a major bump with as much sane BC break as we can come up with :D

**Comment by overlookmotel** [comment]
Hmm... here's a question: how often do you envisage major versions will be released?

Problem with not maintaining 2 branches is that if people want to update to get big fixes, they have to take the breaking changes too. I'd imagine this could be frustrating if your code is running into a bug which you need to upgrade to fix urgently, but you don't have the time to deal with breaking changes at that moment.

For example, a while ago, I proposed changing all references to table names in the API to use model names etc (https://github.com/sequelize/sequelize/pull/2429). This would be a breaking change so should be in a major release, but it's not urgent - it could wait a while before being released. Of course, I should have got this done before v2.0.0, but I didn't have time.

I have no experience in this area. How much extra work is it to maintain 2 branches? Presumably every bug fix patch has to be applied to both branches. There's a possibility of merge conflicts on the next version branch which would be time-consuming to resolve, but I don't know how common that would be.

Of course I understand your time is limited, and there's a balance to be struck between having time to develop new features and time to maintain two branches. But I just wanted to continue the conversation about what's of greatest value to sequelize overall...

**Comment by mickhansen** [comment]
@overlookmotel It ended up being a ton of work (ton being relative to the amount of time we have) maintaing both the 2.0 development and the 1.7 stable branch. Endless merge conflicts you have to resolve each time you try to keep the branches in sync, eventually we just abandoned 1.7 because it was too much hassle.

**Comment by overlookmotel** [comment]
Yes, I can understand that. Well I guess it depends how often major releases come out. As I gather, it was a long time between 1.7 and 2.0. Maybe, in retrospect (and I say this knowing very little of the project's history), 2.0 should have been released much earlier and what is now 2.0 might have ended up being more like 4.0?

But that leads me back to my first question: how often do you envisage major versions will be released?

I hope you don't mind me bringing this up as a topic of conversation. I'm not telling you what to do!

**Comment by mickhansen** [comment]
More than a year between 1.7 and 2.0, which was horrible for everyone involved heh.

I'm not sure we can estimate that, there's not that many things that needs to be broken immediately - There's stuff i'd like to change but don't have to remove completely. So i'd still think 3.0 is some ways off, but then again the scopes refactor @janmeier just did would technically be a semver major bump, so it might be sooner :)

**Comment by mickhansen** [comment]
@overlookmotel And i never mind conversation with you, have missed you! :)

**Comment by overlookmotel** [comment]
Thanks @mickhansen :). I've been busy as hell so had to put all this stuff to one side for a while. Now have bits and pieces of time, so will be working on stuff sporadically over next couple of months.

I'd be interested in what @janmeier and other core contributors think about this (can't remember how you reference @sequelize/owners). My opinion is that it would be preferable to maintain 2 branches, and I wonder if it would be as much work as it was for 1.7 & 2.0 if 3.0 is not so long in coming, so the branches won't diverge as far and there'd be less merge conflicts. But this is easy for me to say - I won't be maintaining the two branches!

**Comment by sdepold** [comment]
I totally didn't read the whole discussion but imho there is nothing wrong with major bumps if the migration path is clearly documented and if we don't bump the major version every 2 weeks. Having a major bump every 3 to 6 months on the hand is totally ok in my opinion if we break BC for sensible reasons.

**Comment by mickhansen** [comment]
@sdepold We'll bump when there's BC to break, but it will likely be less often than every 2 weeks.
Not sure we'll document migration path more than documenting the changes in the changelog (and the recommend new use), but that should be sufficient for most, if they care to read the changelog.
