### ISSUE TITLE
Transaction giving mea http 500 error

### ISSUE THREAD

**Issue by kahwooi** [sequelize/sequelize#2792]
I am trying to use the transaction feature in my service class:

```
var sequelize = require("sequelize");
var models  = require("../models");

var user= {
    new: function(data, callback) {
        return sequelize.transaction(function (t) {
            return models.User.create({
            ...
            ...
        }).then(function(result){
            callback(null, result);
        }).catch(function(err){
            callback(err, null);
        });
```

The debugging breakpoint stop at return sequelize.transaction(function (t) {, and http request give me 500 server error.

I have no idea why the code stop at return sequelize.transaction(function (t) { and does not catch the error.

**Comment by janmeier** [comment]
No response, closing
