### ISSUE TITLE
How can I create a LONGTEXT MySQL field ?

### ISSUE THREAD

**Issue by iwazaru** [sequelize/sequelize#2793]
I have an app that needs to store very long texts, both in MySQL and Postgresql. With MySQL, I would use LONGTEXT, in Postgresql TEXT, that has unlimited length, so that's cool. However in Sequelize 2.0.0-rc4, if i do this :

    var Book = sequelize.define('Book', {
        title: Sequelize.STRING,
        content: Sequelize.TEXT,
    });

when syncing with Postgresql I would get unlimited lengh TEXT which is okay, but in MySQL I would get a 64 KB long TEXT field which is not enough for my needs.

Maybe consider creating a LONGTEXT DataType that whoud create a LONGTEXT for MySQL and fallback to TEXT field on others DBMS ?

**Comment by OtaK** [comment]
@mickhansen Did you start taking care of it or do you mind if I give it a shot?

**Comment by mickhansen** [comment]
@OtaK give it a shot :) the data type system is not the best internally right now though

**Comment by OtaK** [comment]
@mickhansen Is it normal that the mysql dialect's files are included whatever the current test dialect is?

Feature and tests so far are written, but something strange happens; the specific data-types.js I wrote in the mysql dialect is always included, thus overwriting toString prototype with TINY/MEDIUM/LONGTEXT logic where it's not necessary at all.

Can you check this if you have some time please? https://github.com/OtaK/sequelize/commit/3a3c3b52f12a25a311d2f84b811f53486b58f177

**Comment by mickhansen** [comment]
@OtaK not quite sure what you mean? They should ideally only be included in mysql and mariadb, but sqlite might also depend on the mysql query generator slightly.

That's what i meant by the data type is not the best internally yet, you can't modify the DataTypes object since it's an object used by all dialects.

We need to have some sort of mechanism where it will replace the functionality in runtime but without touching the original object - Ideally it has to be when a query comes in.

**Comment by OtaK** [comment]
@mickhansen I mean that I had weird behaviors going on, I put a console.log('wtf'); on top of mysql dialect's data-types.js and it was displayed on all dialects (postgres, sqlite and so on). It looks like some piece of code tries to warm-up the require() cache by requiring all files beforehand.

**Comment by mickhansen** [comment]
@OtaK perhaps so, but in any case modifying `lib/data-types` is NOT the way to go since it also interfers with multiple instances of sequelize.

**Comment by OtaK** [comment]
@mickhansen It is, if you want to make so that the TEXT datatype behaves like BLOB: BLOB('tiny') as described in the MySQL/MariaDB spec. That would allow developers to use TEXT('tiny') in definitions and get TEXT as a result on all platforms except MySQL-based ones, where it would output TINYTEXT.

What's your insight on this approach?

**Comment by mickhansen** [comment]
@OtaK `lib/data-types` is shared between all dialects and all instance of sequelize, therefor should not be modified. I'm not saying that your general idea is wrong, i'm saying the approach with modifying the global DataTypes object is wrong :)

We need a way where we can either create a local copy for that sequelize instance or do a replace when doing queries. The problem with doing a local copy is that people use the object/Sequelize directly and not the sequelize instance when using DataTypes in model definitions.

**Comment by florian-rossiaud** [comment]
Any update on this topic ?

**Comment by mickhansen** [comment]
@florian-rossiaud data types has been refactored so it's possible to create dialect specific data types now.

**Comment by dorrotman** [comment]
+1 on this feature request.

**Comment by OtaK** [comment]
Might give it a shot again since 2.0/3.0 have been released and DataTypes' implementation seems more flexible to fiddle with. :)

**Comment by dorrotman** [comment]
That would be great :smiley:

**Comment by ghostfreak3000** [comment]
I just ran this

var sql = "ALTER TABLE tablename MODIFY columnname LONGTEXT;";
sequelize.query(sql,{ raw: true }) 

after checking that the table exists.
hope it helps.

**Comment by sushantdhiman** [comment]
Implemented in https://github.com/sequelize/sequelize/pull/3836

**Comment by Piotr23** [comment]
Sequelize.TEXT('long')

http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes
