### ISSUE TITLE
Options not passed to getTableName function

### ISSUE THREAD

**Issue by quiddle** [sequelize/sequelize#2794]
Back in June, this pull request I submitted was merged: https://github.com/sequelize/sequelize/pull/1952

In September, another change was merged, which reversed all of those changes, except for the inline documentation: https://github.com/sequelize/sequelize/commit/bea6549048b3bc164f0cb979696154110c119129

We recently updated our sequelize instance and found this problem. What would be most useful? I can issue a new pull request if need be.

**Comment by janmeier** [comment]
Looks like this has been un-reverted, if not please reopen
