### ISSUE TITLE
Way to extend Model objects as scopes are doing

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2799]
This issue is a proposal to include the method `.extend` on `Model` 's prototype with the propose to create contexts from same Model for different processes.

A nice example could be connecting models into each request:

```js
// model.js
Model.prototype.extend = function ( object ) {
    return object ? Utils._.extend( Object.create( this ), object ) : Object.create( this );
};
```

I think this is a must for plugins. I don't have sure what do you think about this, but maybe it isn't a bad idea to add it into `Sequelize` class and prototype for `sequelize` instances. Would cover also the need of @overlookmotel to manipulate DataTypes.

@overlookmotel @mickhansen @janmeier 

### Pros
* Hooks would run on extended object, which means that we could easily create plugins that interact with other platforms/modules since they could mixin whatever they want.

### Cons
*

**Comment by sushantdhiman** [comment]
As `Model` is now a ES6 class, I think it can be extended without any issues
