### ISSUE TITLE
Should sequelize core have direct compatibility with connect/express as middleware?

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2800]
I had think about creating a module that extends Models ( related #2799 ) and place them into each `req` on `req.models`, but since most of us would need it ( for me its better to contextualize them than saving and using models / database into a global variable ) should it be part of core?

### Implementation

```js
// sequelize.js

Sequelize.prototype.handle = function ( req, res, next ) {
    req.db = this;
    req.models = this.models.map(function ( Model ) {
        return Model.extend({
            req: req,
            res: res
        });
    });
    next();
};

```

### Usage

```js
// database.js
var Sequelize = require( 'sequelize' );

var database = module.exports = new Sequelize(/* ... */);
```

```js
// app.js
var express = require( 'express' );
var database = require( './database' );

var app = module.exports = express();

app.use( database );

// Gathering models should be easier

// Example:
app.use(function ( req, res ) {
    return req.models.User.find( req.session.me )
        .then(function ( me ) { req.me = user })
        .finally( next );
});
```

### Pros
* 

### Cons
*

**Comment by danamajid** [comment]
@cusspvz Currently facing exactly what you've described here. How does your current solution look like and would you recommend it?

**Comment by cusspvz** [comment]
@danamajid sorry for my late response.

If you read carefully my post you could see that:
* We need a `handle` method so express can recognize that `[Object]` as an handler
* For better structure proposes, we configure our *Sequelize* instance on a file that exports that object

Since this didn't had progress, you could workaround it by defining `handle` on your object instead.

Example:

`database.js`

```js
import Sequelize from 'sequelize'

const database = new Sequelize(/* ... */)

// Inject request handler
database.handle = ( req, res, next ) => {
    req.db = database
    req.models = database.models.map(( Model ) => {
        return Model.extend({ req: req, res: res })
    })
    next()
}

export default database
```

`app.js`
```js
import Express from 'express'
import database from './database'

const app = new Express()

app.use( database )
```

This will allow you to call models from within your route handlers:
```
app.get( '/user/:user', ( req, res ) => {
  return req.models.User.find( req.param( 'user' ) )
  .then(( user ) => {
    res.render( 'user/profile', { user })
  })
})
```

**Comment by mickhansen** [comment]
Closing this. Interop with a middleware lib will likely not go in core, easy to write a plugin for.
