### ISSUE TITLE
SphinxSearch dialect

### ISSUE THREAD

**Issue by djmadcat** [sequelize/sequelize#2804]
[Sphinx](http://sphinxsearch.com/about/sphinx/) is an open source full text search server, designed from the ground up with performance, relevance (aka search quality), and integration simplicity in mind.

Rich database-like querying features. Sphinx does not limit you to just keyword searching. On top of full-text search result set, you can compute arbitrary arithmetic expressions, add WHERE conditions, do ORDER BY, GROUP BY, use MIN/MAX/AVG/SUM, aggregates etc. Essentially, full-blown SQL [SELECT](http://sphinxsearch.com/docs/current.html#sphinxql-select) is supported. 

[SphinxQL](http://sphinxsearch.com/docs/current.html#sphinxql-reference) lets the application query Sphinx using standard MySQL client library and query syntax.

It also partially supports [ALTER statement](http://sphinxsearch.com/docs/current.html#sphinxql-attach) as DDL feature.

**Comment by janmeier** [comment]
Closing this issue

To anyone stumbling across this, we would definitely be interested in adding sphinx support, if someone pledges to implement and provide support for it.

We'd also need some way to test oracle on travis.

If someone is open for the challenge, please open a new issue if you have specific questions, or post them on IRC

**Comment by ddeshmane** [comment]
As native MySQl Full Text Search does not support synonyms, plurals etc, I decided to go with Sphinx. I am using the Sequelize as my ORM, Now I am stuck and don't know if sequelize supports Sphinx or not ? Can any one please let if know if this is supported ? and guide me to it's documentation so that I can integrate Sphinx with Sequelize . Thanks !

**Comment by janmeier** [comment]
@ddeshmane It is not supported

**Comment by ddeshmane** [comment]
@janmeier  Thanks for letting me know.
