### ISSUE TITLE
hook: afterCommit?

### ISSUE THREAD

**Issue by nestorneto** [sequelize/sequelize#2805]
Using the hooks to emit real-time events, how to ensure that this transaction was not rollbacked? Assuming that the trigger is activated even if the transaction is not completed.

My current strategy is creating a timeout in the hook that will check within period of time if that event was created (in the case of afterCreate) going in the database and making sure that the record exists.

I wonder if there is no possibility to do this without go to the database everytime, if somehow I could have the object of the transaction and it keep track of her situation?

**Comment by nestorneto** [comment]
which way i could check the transaction status outside of hooks?

**Comment by mickhansen** [comment]
@nestorneto well like i wrote, i'm not sure you can right now.

**Comment by nestorneto** [comment]
you wrote that i can't inside. but how i do outside?

**Comment by nestorneto** [comment]
A simple hack maybe me allow to check this.

QueryInterface.prototype.rollbackTransaction = function(transaction, options) {
    if (!transaction || !(transaction instanceof Transaction)) {
      throw new Error('Unable to rollback a transaction without transaction object!');
    }
    transaction.status = 'not_committed';
    options = Utils._.extend({
      transaction: transaction,
      parent: options.transaction
    }, options || {});

    var sql = this.QueryGenerator.rollbackTransactionQuery(transaction, options);
    return this.sequelize.query(sql, null, options);
  };

the problem is about autocommit.

**Comment by mickhansen** [comment]
Ah my bad - Well `.transaction()` returns a promise so you just use `.then()` or `.catch()`

**Comment by cusspvz** [comment]
@mickhansen I'm not sure, but i think that @nestorneto can be experiencing some flow control fault on hooks or bad app structure (since post-transaction code should be where the transaction is being started).

Inspite that, what do you think about `transaction` hooks? I can't image a usage case example, unless we give namespaces into transactions, but i don't see the point.

**Comment by mickhansen** [comment]
@cusspvz we'd have to find a usecase.

But perhaps we could expose a promise property from the transaction object so you could do something like:

```js
Notification.afterCreate(function (notification, options) {
  options.transaction.promise.then(function () {
   // send email
  });
});
```

Obviously you could not return the transaction promise to the hook since it would never finish, but it could work for side effect hooks that don't touch sequelize.

**Comment by nestorneto** [comment]
If every time I create a task, I have to emit a realtime event, it makes no sense to worry about it in each code that performs this action. This is why I am trying to emit by hooks. In cases that do not have transaction works perfectly.

**Comment by mickhansen** [comment]
@nestorneto yeah i understand your problem completely, and it's one i'd like to adress, just not sure how to do it perfectly.

**Comment by cusspvz** [comment]
> @nestorneto 
> If every time I create a task I have to emit a realtime event, it makes no sense to worry about it in each code that performs this action.

Does the event triggers some sort of data loading mechanism?

**Comment by neekey** [comment]
+1 for this, I'm implementing a web-hook service, and one of my hook types is "after-create", so what I did is querying the new item just created associated with related datas in the "afterCreate" hook, and the result end up with the id I provided can't be found at that time.

```js
models.schema.hook( 'afterCreate', function( schema, options, next ){
        hookHandle( "SCHEMA_CREATE", schema.id );
});

function hookHandle( type, schemaId ){
    
    Promise.join(
    SchemaProxy.findOneWIthAll( schemaId ),
    SchemaProxy.getHooks( schemaId ), function( schema, hooks ){
        // handle the hooks and datas
    }
}
```

**Comment by mickhansen** [comment]
@neekey It would be findable if you used the transaction in the hook aswell - But obviously that won't solve the rollback issue.

**Comment by cusspvz** [comment]
@mickhansen is there any sense in rerun hooks triggered inside a `transaction` when it is commited? Or even run transaction hooks, don't know.

Example:
* transaction
* build
* save
* update
* save
* transaction commit

would trigger hooks:
* sequelize.afterTransaction
* model.afterBuildOnTransaction
* model.afterCreateOnTransaction
* model.afterUpdateOnTransaction
* sequelize.afterTransactionCommit
* model.afterBuild
* model.afterCreate
* model.afterUpdate

**Comment by mickhansen** [comment]
@cusspvz That would be a lot to maintain, the transaction might span 50 calls that each have to track when the transaction is committed to fire and extra hook.

How do other ORMs deal with this issue?

**Comment by mdarveau** [comment]
@cusspvz @nestorneto You could use the instance hook to queue pending (uncommited) changes into some singleton "real-time event manager" that would map the current transaction to a list of created/updated/deleted records. You can then systematically add a post transaction hook that would call the real-time event manager and make it dequeue whatever it stored.

This assume you can get a reference to the current transaction in the hook but it should be the case if you use CLS and if not, the transaction might be in the options passed to the hook.

It's a little error prone to have to put a post transaction handler so maybe there could be some kind of global post transaction hook implemented in sequelize?

This design could be built-in sequelize but it could have negative performance/memory impact. I believe it could also be done as a plugin that would add generic hooks on your model and provide the singleton manager that track changes.

**Comment by cusspvz** [comment]
@mickhansen in case of `CakePHP` all sort of `transaction` things were made under `dataSource` hood, so developers don't have to worry with nothing.

-------

> You can then systematically add a post-transaction hook that would call the real-time event manager and make it dequeue whatever it stored.

@mdarveau Isn't the first time that occurs to me the idea to place hooks on `Transaction`, or `Instance <-> Transaction` and sort of that kind but then i realize that probably its a huge mistake because of its context, structure and data delivering.

> This assumes you can get a reference to the current transaction in the hook

The most important part of logic repetition is covered ATM with an `options.transaction` exposure on each `hook` run if its `method` supports it.

**Comment by cusspvz** [comment]
Well, today i was cached with a similar scenario.
We were using a transaction while using `save` method  for creating for the first time an image on our DB, and that calls for `afterCreate` hook. Happens that we only save a pointer for the original image, we send to our task manager service image's id so it can render up thumbnails and sort of but it can happen that transaction could be rollbacked, so `afterCreate` doesn't quite works.

@mickhansen I've liked your idea to expose a promise on `transaction` to handle its final state, that would complement `options.transaction` exposure solution!

I could implement it easily, but before that i have to ask: Is interesting for sequelize if Transaction inherits properties of a Promise?

**Comment by cusspvz** [comment]
That would allow things such as:

```js

// Creation of an unmanaged transaction
var transaction = sequelize.transaction();

// Some async workflow with unmanaged transaction 

return transaction;
```

**Comment by mickhansen** [comment]
@cusspvz transaction already returns a promise which is resolved/rejected based on the callback pattern resolution.

**Comment by cusspvz** [comment]
`sequelize.transaction` returns a promise that fulfills last promise with a `transaction` instance, my suggestion was to inherit properties from `Promise` into `Transaction`, that would turn `Transaction` instances promisables.

**Comment by mickhansen** [comment]
@cusspvz ah right

**Comment by cusspvz** [comment]
Is that interesting? Or do you prefer your first approach? (`transaction.promise`)

**Comment by mickhansen** [comment]
Perhaps `transaction.promise` with `transaction.then|catch` sugar.

**Comment by cusspvz** [comment]
Nice, one more question. When `transaction` is set with `autocommit`, does `Transaction.prototype.commit` method gets called?

**Comment by mickhansen** [comment]
No, autocommit refers to the sql statement auto commit.

**Comment by cusspvz** [comment]
Do you have some suggestions on how i would I detect `transaction` final status on those cases?

**Comment by mickhansen** [comment]
@cusspvz I think you're confusing something, autocommit does not mean a transaction is automatically committed.

**Comment by cusspvz** [comment]
Oh, my bad. ASAP today I will PR this.

**Comment by EToreo** [comment]
@mickhansen Any movement on this?  I am running into very similar issues with `findOrCreate` "afterCreate" hooks.  The only solution I have found is putting in setTimeout hacks in my hook code.  Nasty!

**Comment by mickhansen** [comment]
@EToreo Not yet i'm afraid, no one is expected to work on it soon either so i suggest you look at providing a PR.

https://github.com/sequelize/sequelize/blob/master/lib/transaction.js
https://github.com/sequelize/sequelize/blob/master/lib/hooks.js
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2617

Will probably want to create a seperate mixin function so transaction only gets before/afterCommit though.

**Comment by cusspvz** [comment]
@mickhansen @EToreo I've been a little bit busy since a while with other tasks rather than sequelize related. I predict I will touch this again at the end of this month.

@brunocasanova is the person that is directly working with sequelize at the time. 
Until then, if someone is available for getting the job done, feel free to see what I did on my PR #3449

@brunocasanova remember the problem related with transactions and hooks you had discussed with me? Was it related with this issue?

**Comment by EToreo** [comment]
It turns out that in my case I was able to just pass the transaction along to the rest of the find commands I was doing in the hook.  I'm not sure why that wasn't my first instinct...  At any rate, my problem was solved because the transaction was already exposed.  I'm am still interested in this issue, though.

**Comment by mickhansen** [comment]
@EToreo right that works for most cases, the general issue here is if you need to do a non-sequelize command after you know an entire sequence has succeeded.

**Comment by EToreo** [comment]
It turns out that I am in need of an after commit hook.  I need to distribute the changes made to the database when a transaction is done.  But I can't use afterCreate/afterModify on the models because the transaction might fail later and those mutations to the database would be rolled back (but the mutation distribution would have already happened).

@cusspvz Did you ever get to this?  If not, my team can take a look.

**Comment by cusspvz** [comment]
@EToreo This is quite old, I think it was everything working but you might have to check if tests are ok.
I've been on a rush for the last months, being unable to get my hands on most of open-source projects we use.

**Comment by krisr** [comment]
For anyone currently dealing with this, I worked around it with a wrapper function like this:

```
	/**
	 * This is our version of Sequelize.transaction. It augments the transaction
	 * object with a hook that is run after the transaction commits successfully.
	 *
	 * @see sequelize.transaction for usage.
	 */
	transaction: function(options, autoCallback) {
		if (typeof options === 'function') {
			autoCallback = options;
			options = undefined;
		}
		var afterCommitHooks = [];
		return sequelize.transaction(options, function(t) {
			// Ensure sequelize didn't add this functionality themselves already:
			assert(t.afterCommit === undefined, 'Sequelize already has a afterCommit hook on transactions');
			t.afterCommit = function(callback) {
				afterCommitHooks.push(callback);
			};
			return autoCallback(t);
		}).then(function(result) {
			return BPromise.map(afterCommitHooks, function(callback) {
				return callback();
			}, {concurrency: 1}).return(result);
		});
	},

```

Creating a promise on transaction as this PR does (https://github.com/sequelize/sequelize/pull/3449) seemed like a more roundabout way of accomplishing the same thing.

**Comment by novrain** [comment]
excuse me , does this issue has been fixed or fulfilled?

**Comment by janmeier** [comment]
@novrain It's still open, so no

**Comment by JoshuaWise** [comment]
two years later and people still need this feature. What's going on?

**Comment by drunkhacker** [comment]
For who wants use this function, I added this workaround. I used [shimmer](https://www.npmjs.com/package/shimmer) library for doing monkey patch.

```
const Sequelize = require('sequelize');

// monkey patch for transaction after hook
Sequelize.Transaction.prototype.afterCommit = function(cb) {
  if (!this.afterCommitHooks) {
    this.afterCommitHooks = [];
  }
  this.afterCommitHooks.push(cb);
};
shimmer.wrap(Sequelize.Transaction.prototype, 'commit', original => {
  return function() {
    if (this.afterCommitHooks) {
      return original.apply(this, arguments).then((result) => Promise.map(this.afterCommitHooks, (cb) => cb(), {concurrency: 1}).return(result));
    } else {
      return original.apply(this, arguments);
    }
  }
});
```

usages:

```
db.sequelize.transaction((tx) => {
  tx.afterCommit(() => db.User.find({where: {id: 3}}).then((user) => console.log(user.name)));
  // other db jobs
});
```

**Comment by EToreo** [comment]
I think this is still needed.

**Comment by iamjochem** [comment]
I offer an alternative work-around that you can implement in your own code (check the 2nd comment in #8115) - the difference between my work-around and that offered by @drunkhacker is that mine applies at the point a "std" sequelize hook is defined rather than in the place where a transaction is used (this might be useful for users who already have a pile of hook functions defined)

**Comment by zekenie** [comment]
Having a transaction commit hook would be extremely helpful for me. Like everyone above has mentioned when you need to do something like fire off a websocket event after an instance has been created, but want to wait to make sure the instance isn't rolled back, there's no great way to do that. That means if there's something else on the transaction that causes a rollback, my frontend might be notified of something that never actually committed.

**Comment by bradley** [comment]
Not sure why I had such a hard time finding this but maybe it will help someone else: there is an [afterCommit hook](https://github.com/sequelize/sequelize/blob/master/docs/manual/other-topics/transactions.md#the-aftercommit-hook) that you can hook into on the `transaction` object itself. 

Knowing this isn't directly related to _model_ hooks, the usefulness will be dependent on use case.

**Comment by papb** [comment]
Hi @bradley, thanks for your comment, can you please open a new docs issue requesting this to be made explicit somehow at the docs? You can link to your comment here. Thanks.

**Comment by marcin-wlodarczyk** [comment]
I had a similar problem and couldn't find explicit documentation about [afterCommit hook](https://github.com/sequelize/sequelize/blob/master/docs/manual/other-topics/transactions.md#the-aftercommit-hook).

I rely on global model hooks to dispatch events from the queue. The problem consisted of events dispatched even after transaction failure.

My solution:

```typescript
// Global Hook
model.afterCreate((model, options) => {
    if (options.transaction) {
        // Wait until transaction is committed
        options.transaction.afterCommit(() => {
            // Dispatch events (model is persisted in database)
        });
    } else {
        // Optionally dispatch events outside of transaction
    }
});
```
