### ISSUE TITLE
Syntax error on token "catch", Identifier expected

### ISSUE THREAD

**Issue by ht10vn** [sequelize/sequelize#2812]
Hi,

I have used model destroy with catch() as code below,
<pre>
View.destroy({
			where: {
				id: viewid
			}
		}).then(function(){
			console.log('success');			
		}).catch(function(error) {
			  console.log('fail');
		});	
</pre>
Has error in eclipse at row 
}).catch(function(error) {
is 
Syntax error on token "catch", Identifier expected

Please help me resolve this error,
Thanks,

**Comment by mickhansen** [comment]
@ht10vn well Eclipse is wrong, not really much we can do about that :)
Alternatively to catch you can use `.then(onSuccess, onError)` rather than just `.catch(onError)` although that catch is the better alternative imo.

You can also do `["catch"]()`
