### ISSUE TITLE
Transaction does not get committed

### ISSUE THREAD

**Issue by igittGit** [sequelize/sequelize#2814]
Hi,

I want to build a simple webform where you can enter a user's username, firstname, lastname and select multiple groups for this user (but one for now). 

Because creating the user and assigning it into a group should be handled atomically in one step I decided to use a transaction, as shown in the docs here: http://sequelize.readthedocs.org/en/latest/docs/transactions/#using-transactions-with-other-sequelize-methods

My models:
```javascript

var Sequelize = require("sequelize");
var sequelize = new Sequelize('test', 'root', 'xxxx' , 
    {
        "host": "127.0.0.1",
        "dialect": "mariadb",
        "define": {
          "timestamps": false
        }
    });

var Group = sequelize.define("Group", {
    name: {
        type: Sequelize.STRING,
        allowNull: false
    }
})

var User = sequelize.define("User", {
    username: {
        type: Sequelize.STRING,
        allowNull: false
    },
    firstName: {
        type: Sequelize.STRING,
        allowNull: false
    },
    lastName: {
      type: Sequelize.STRING,
      allowNull: false
    }
});


User.belongsToMany(Group, {as: 'Groups'});
Group.belongsToMany(User, {as: 'User'});
```
So I've a many-to-many relationship.

My transaction:
```javascript

sequelize.sync()
.then(function(){
    

    var newUser = {
        username: 'hf',
        firstName: 'Hans',
        lastName: 'Fischer'
    };
    var id = 2;   // group

    return sequelize.transaction(function (t) {
        return User.create(newUser, {transaction: t}).then(function (user) {
            return Group.find(id, {transction: t}).then(function(group){
                if (!group) throw Error("Group not found for id: " + id);
                return user.setGroups( [group], {transction: t});
            })              

        });
    }).then(function (result) {
        // Transaction has been committed
        console.log(result);
    }).catch(function (err) {
        // Transaction has been rolled back
        console.error(err);
    });        




})
```

But for some reason neither function (result) {.. for success nor the function in catch gets called. However, the complete SQL queries of the transaction were generated except COMMIT, so nothing was inserted into the db.

If I put it like this  
```javascript
return user.setGroups( [], {transction: t}); 
```
the transactions succeeds, but with no inserts into GroupsUsers of course.

I'm using sequelize@2.0.0-rc4 with mariadb dialect.

**Comment by mickhansen** [comment]
You have mispelled transaction twice, 'transction' should be 'transaction'.
Also `Group.find(id, {transaction: t})` might have to be `Group.find({where: {id: id},  transaction: t})`

**Comment by igittGit** [comment]
that fixed the problem!

Thank you and sorry;)
