### ISSUE TITLE
Deprecation notice for chaining with .error, even though it is supported in Bluebird

### ISSUE THREAD

**Issue by aaronbean** [sequelize/sequelize#2815]
In Sequelize 2.0.0-rc4, I get a deprecation notice (EventEmitter#failure|fail|error is deprecated, please use promise-style instead.) when I try to chain off a promise with .error, which I use all the time with Bluebird.  It seems this shouldn't be deprecated, as Bluebird officially supports it.

**Comment by mickhansen** [comment]
'error' is a method on the old event emitter aswell that we are maintaining BC for. So when you are using `.error` you are using the event emitter and not the promise.

It's too huge of a break to remove the eventemitter completely, but i suppose we could have some kind of flag to turn it off perhaps.

**Comment by mickhansen** [comment]
The event emitter patch and storage of SQL events will be killed in `2.1.0`, we just need to rewrite all tests to promises first, which will take a bit of work.
