### ISSUE TITLE
Confused about M:M hasMany

### ISSUE THREAD

**Issue by memelet** [sequelize/sequelize#2816]
I have had a m:m working as:
```
  Roles.hasMany(models.Users)
  Users.hasMany(models.Roles)
```

Since I want to grab the user's roles I wanted an alias so first I tried:
```
  Roles.hasMany(models.Users, {as: "users"})
  Users.hasMany(models.Roles, {as: "roles""})
```
But this yielded:
```
Error: Cyclic dependency found. 'Roles' is dependent of itself.
Dependency Chain: Roles -> Users => Roles
    at visit (/Users/bkaplan/si/vi-security-users/node_modules/sequelize-extra/node_modules/sequelize/node_modules/toposort-class/toposort.js:74:27)
    at /Users/bkaplan/si/vi-security-users/node_modules/sequelize-extra/node_modules/sequelize/node_modules/toposort-class/toposort.js:96:25
```

After reading the docs closer I see that through is required when using an alias. But still this error message is a bit opaque. 

So I next tried:
```
  Roles.hasMany(models.Users, {as: "users", through: "Roles_Users"})
  Users.hasMany(models.Roles, {as: "roles", through: "Roles_Users"})
```
But this yielded:
```
Uncaught exception: [RangeError: Maximum call stack size exceeded]
```
With no other stack trace.

Is there something basic I am missing? (Assuming this is enough context)

**Comment by mickhansen** [comment]
It all looks correct with the through defined.
I haven't seen a stack size error before. Is there a stack for the range error?

**Comment by memelet** [comment]
No, just the error. Also I just hacked sequelize-hierarchy to depend on sequelize#master and it too generates this error when using belongsToMany. eg, from modelExtends.js

```
                this.belongsToMany(this, {
			as: options.ancestorsAs,
			foreignKey: options.throughKey,
			through: options.through
		});
```

**Comment by mickhansen** [comment]
@memelet well the hierachy code uses a self referential association. Your original association is not self referential.

**Comment by memelet** [comment]
Yes, the the common part is the use of 'as' and 'through' for a hasMany (actually belongsToMany since I upgraded to master to test this).

**Comment by janmeier** [comment]
@memelet Can you post the model definitions for user and role? 

The issue might be that one of the models already have an attribute with the same name as the relation. e.g. User might already have a `role` attribute?

**Comment by BridgeAR** [comment]
Ping @memelet

**Comment by memelet** [comment]
Sorry, I have removed sequelize-hierarchy from the project. Could  you close this for now? And if I get back to it I will open a new issues with more details.
