### ISSUE TITLE
Error: table name specified more than once

### ISSUE THREAD

**Issue by mtfranchetto** [sequelize/sequelize#2819]
Hi, I have defined a db with User, Announcement and Image schemas. I run into an error with eager loading that i cannot solve. All these entities are related in some ways, and when i do the following:

`user.getAnnouncements({ include: [ model: Image]})`

to get the announcements associated to a user with the images, i get this error:

`
{ [SequelizeDatabaseError: error: table name "UsersAnnouncement" specified more than once]
  name: 'SequelizeDatabaseError',
  message: 'error: table name "UsersAnnouncement" specified more than once',
  parent: 
   { [error: table name "UsersAnnouncement" specified more than once]
     name: 'error',
     length: 124,
     severity: 'ERROR',
     code: '42712',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     file: 'parse_relation.c',
     line: '396',
     routine: 'checkNameSpaceConflicts'
}}
`

What am I doing wrong?

Thanks

**Comment by mickhansen** [comment]
Looks like a bug. What version are you using and what does the SQL look like?

**Comment by mtfranchetto** [comment]
I am using sequelize 2.0.0-rc2.
Here's the query produced:

`
SELECT "Announcement"."id", "Announcement"."title", "Announcement"."message", "Announcement"."recipientId", "Images"."id" AS "Images.id", "Images"."sslUrl" AS "Images.sslUrl", "UsersAnnouncement"."removeAt" AS "UsersAnnouncement.removeAt", "UsersAnnouncement"."createdAt" AS "UsersAnnouncement.createdAt", "UsersAnnouncement"."updatedAt" AS "UsersAnnouncement.updatedAt", "UsersAnnouncement"."UserId" AS "UsersAnnouncement.UserId", "UsersAnnouncement"."AnnouncementId" AS "UsersAnnouncement.AnnouncementId", "UsersAnnouncement"."removeAt" AS "UsersAnnouncement.removeAt", "UsersAnnouncement"."createdAt" AS "UsersAnnouncement.createdAt", "UsersAnnouncement"."updatedAt" AS "UsersAnnouncement.updatedAt", "UsersAnnouncement"."UserId" AS "UsersAnnouncement.UserId", "UsersAnnouncement"."AnnouncementId" AS "UsersAnnouncement.AnnouncementId", "UsersAnnouncement"."removeAt" AS "UsersAnnouncement.removeAt", "UsersAnnouncement"."createdAt" AS "UsersAnnouncement.createdAt", "UsersAnnouncement"."updatedAt" AS "UsersAnnouncement.updatedAt", "UsersAnnouncement"."UserId" AS "UsersAnnouncement.UserId", "UsersAnnouncement"."AnnouncementId" AS "UsersAnnouncement.AnnouncementId" FROM "Announcements" AS "Announcement" LEFT OUTER JOIN "Images" AS "Images" ON "Announcement"."id" = "Images"."AnnouncementId" INNER JOIN "UsersAnnouncements" AS "UsersAnnouncement" ON "Announcement"."id" = "UsersAnnouncement"."AnnouncementId" AND "UsersAnnouncement"."UserId"=1 INNER JOIN "UsersAnnouncements" AS "UsersAnnouncement" ON "Announcement"."id" = "UsersAnnouncement"."AnnouncementId" AND "UsersAnnouncement"."UserId"=1 INNER JOIN "UsersAnnouncements" AS "UsersAnnouncement" ON "Announcement"."id" = "UsersAnnouncement"."AnnouncementId" AND "UsersAnnouncement"."UserId"=1 WHERE ((1=1));
`

**Comment by mickhansen** [comment]
`getNM` was changed in regards to includes in later versions, please try upgrading.

**Comment by mtfranchetto** [comment]
Ok, seems okay after upgrading, i'll let you know if the problem come back.
Thanks for the incredibly fast support!

**Comment by mickhansen** [comment]
Great @mtfranchetto - reopen if issue persists
