### ISSUE TITLE
Attributes set during before* hooks do not appear on the created model instance.

### ISSUE THREAD

**Issue by dkushner** [sequelize/sequelize#2822]
With this model definition:

```
  var Invitation = orm.define('Invitation', {
    first_name: DataTypes.STRING,
    last_name: DataTypes.STRING,
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    status: {
      type: DataTypes.ENUM,
      values: ['requested', 'approved', 'invited', 'activated'],
      defaultValue: 'requested'
    },
    token: {
      type: DataTypes.STRING
    }
  }, {
    instanceMethods: {
      toJSON: function() {
        var values = this.values;
        delete values.token;
        return values;
      }
    }
  });

  Invitation.hook('beforeCreate', function(invite, options) {
    if (_.contains(['invited', 'approved'], invite.status)) { 
      return new Promise(function(resolve, reject) {
        crypto.randomBytes(16, function(err, buf) {
          if (err) {
            reject(err);
          } else {
            invite.token = buf.toString('hex');
            resolve(invite);
          }
        });
      });
    }
  });
```

Creating an instance of this model gives the following behavior: 

```
  return Invitation.create({
        first_name: profile.first_name,
        last_name: profile.last_name,
        email: profile.email,
        status: 'approved'
  }).then(function(invitation) {
    console.log(invitation);
  });
```

```
{ dataValues: 
   { id: 261,
     first_name: 'Rad',
     last_name: 'Awesome',
     email: 'rad@test.com',
     status: 'approved',
     updated_at: Fri Jan 02 2015 13:45:41 GMT-0800 (PST),
     created_at: Fri Jan 02 2015 13:45:41 GMT-0800 (PST),
     user_id: null },
  _previousDataValues: 
   { id: 261,
     first_name: 'Rad',
     last_name: 'Awesome',
     email: 'rad@test.com',
     status: 'approved',
     updated_at: Fri Jan 02 2015 13:45:41 GMT-0800 (PST),
     created_at: Fri Jan 02 2015 13:45:41 GMT-0800 (PST),
     token: 'ad4d7213098cd6bd6388a84e4cbc12e6',
     user_id: null },
```

**Comment by dkushner** [comment]
Note that changing the hook to be synchronous has no effect on the output. Same issue.

**Comment by dkushner** [comment]
Just tested, and even using an earlier hook like `beforeValidate` displays this same behavior. Surely this didn't just slip by the test suite?

**Comment by dkushner** [comment]
Here are the results of some further testing:

* No permutation of hook definition style and async/sync hooks improves the issue.
* The value IS being set in the `beforeCreate` hook just fine, and the value is being inserted into the database, but the change is never reflected in the instance returned from the call to `Invitation.create`.
* Checking the value in an `afterCreate` call shows that `dataValues.token` is set correctly.

**Comment by mickhansen** [comment]
I'm unable to reproduce this. `token` is available in `instance.dataValues` for me.
Can you provide more information? Perhaps a copy-pasteable test or a pull request with a failing unit test?

**Comment by dkushner** [comment]
@mickhansen, I figured this was way too big to sneak through the test suite but I could find no ulterior cause. Let me give you the full model definition, just in case some of the other hooks are interfering with the process?

```
exports = module.exports = function(orm, queue) {
  var Invitation = orm.define('Invitation', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    first_name: DataTypes.STRING,
    last_name: DataTypes.STRING,
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isEmail: "Not a valid email.",
        isNotUsed: function(value, done) {
          orm.models.User.count({
            where: {
              email: value
            }
          })
          .then(function(exists) {
            if (!!exists) {
              done("Email must not be in use.");
            } else {
              done();
            }
          })
          .catch(function(err) {
            done(err.message);
          });
        }
      }
    },
    token: DataTypes.STRING,
    status: {
      type: DataTypes.ENUM,
      values: ['requested', 'approved', 'invited', 'activated'],
      defaultValue: 'requested'
    },
  }, {
    instanceMethods: {
      toJSON: function() {
        var values = this.values;
        delete values.token;
        return values;
      }
    }
  });

  Invitation.hook('beforeCreate', function(invite, options) {
    if (_.contains(['invited', 'approved'], invite.status)) {
      invite.token = crypto.randomBytes(16).toString('hex');
    }
    return invite;
  });

  // Send mailer corresponding to the newly created invitation status.
  Invitation.hook('afterCreate', function(invite, options) {
    return new Promise(function(resolve, reject) {
      queue.create('invite.' + invite.status, invite).save(function(err) {
        if (err) {
          return reject(err);
        }
        return resolve(invite);
      });
    });
  });

  Invitation.hook('afterUpdate', function(invite, options) {
    if (!invite.changed('status')) {
      return Promise.resolve(invite);
    }

    return new Promise(function(resolve, reject) {
      queue.create('invite.' + invite.status, invite).save(function(err) {
        if (err) {
          return reject(err);
        }
        return resolve(invite);
      });
    });
  });
```

**Comment by dkushner** [comment]
I've discovered the issue has something to do with the way hooks are being executed. On [this line](https://github.com/sequelize/sequelize/blob/v2.0.0-rc4/lib/instance.js#L648) a debug statement shows the token as missing while a debug statement in the preceding tap or in the afterX hook clearly shows the token as still being set. This makes no sense whatsoever. Nothing in the _afterX_ hook is being done to modify the value of the token.

**Comment by dkushner** [comment]
I've found the (sort of) solution to this problem. Something about the afterCreate/afterUpdate hooks was interfering. I have since changed both hooks to use a synchronous form of the same operation and the issue has disappeared. I think this still warrants some investigation. I don't believe anything in the example case violates expected behavior according to the documentation.

**Comment by mickhansen** [comment]
I'm thinking that https://github.com/sequelize/sequelize/blob/v2.0.0-rc4/lib/instance.js#L629 should be a `then` with a return result since it's actually modifying the result.

**Comment by dkushner** [comment]
@mickhansen, this would break with what the docs have indicated with regards to the return value of a hook not mattering. There seems to be some other sort of issue here, I've not made any changes to the model since I found that previous solution and now I'm encountering the exact same behavior.

**Comment by dkushner** [comment]
[_Not sure whether the appropriate etiquette is to combine comments here, I fill as if I'm spamming._]

Some additional information, just to add to the weirdness:

```javascript
Invitation.create(invitation).then(function(invitation) {
  console.log(invitation.token); // correctly prints out the token  
  return User.create(profile).then(function(user) {
    console.log(invitation.token); // undefined
  });
});
```

**Comment by mickhansen** [comment]
@dkushner we would keep the afterCreate hook as tap, but change the transfer of values to result as a then - That might work, although your case is highly strange.

**Comment by mickhansen** [comment]
@dkushner do you have a fully copy pasteable test case that shows the issue? I would like to take a look at a fix this evening.

**Comment by mickhansen** [comment]
@dkushner okay this might have to do with your toJSON, try commenting out `delete values.token`

**Comment by mickhansen** [comment]
Yeah it's the `toJSON`. For performance reasons `.get()` doesn't clone the values unless it absolutely has to (in cases of custom getters or includes) so when doing `delete` you are in fact modifying the values object.

**Comment by mickhansen** [comment]
`queue.create('invite.' + invite.status, invite)` might be caling `toJSON` on `invite` is my guess

**Comment by mickhansen** [comment]
@dkushner
