### ISSUE TITLE
Relationship between two tables

### ISSUE THREAD

**Issue by VictorQueiroz** [sequelize/sequelize#2823]
I have `characters` and I have `character_inventory`, the `character` table have a primary key which is `guid` as do `character_inventory`, what I need to do is when I through:
```
Character.findOne({
  where: { guid: 1 },
  include: [models.CharacterInventory]
})
```

The Sequelize go inside the `character_inventory` get all the respective `character_inventory` and bring me this too. How can I do that?

**Comment by dkushner** [comment]
I believe the `Model.findOne()` call applies an implicit `LIMIT 1` to the query result, meaning the query can never return more than one row meaning it cannot perform the join and group you're looking for. You need to use `Character.findAll({ where: { guid: 1 }, include: [models.CharacterInventory] })`.

**Comment by mickhansen** [comment]
The findOne will still work with includes, especially when querying on a primary key, you'll have to provide more information @VictorQueiroz. It's not very clear what your issue is with the include.

**Comment by mickhansen** [comment]
Or are you specifically asking to get only characters with guid 1 and only characterinventory with guid 1?
In that case you could do:

```js
Character.findOne({
  where: { guid: 1 },
  include: [{model: models.CharacterInventory, where: {guid: 1}}]
})
```

**Comment by janmeier** [comment]
Closing, no response
