### ISSUE TITLE
TypeError: Object has no method add %Model%

### ISSUE THREAD

**Issue by KoalaOnAStick** [sequelize/sequelize#2826]
Hi,

I seem to be faced with a reccurent problem with the last (2.0.0 rc4) version of sequelize.

**Firstly, I create my model** 
(I'm using "sequelizecon" instead of "sequelize" for legacy reasons):

    var Interest = sequelizecon.define('Interest', {
    userid: sequelize.INTEGER,
    interest: sequelize.TEXT,
    });
    var Listofinterest = sequelizecon.define('listofinterest', {
    overview: sequelize.TEXT,
    });

**Secondly, I define my Associations:**

    Listofinterest.hasMany(Interest);
    Interest.hasOne(Listofinterest);

**Thirdly, I sync my model:**
	Listofinterest.sync();
	Interest.sync();

**Finally, I attempt to create an item in my two models**
	Listofinterest.addInterests(Interest, {overview: "House of Cards"}).then(function() {});

Sadly, this gives me the following error:
	TypeError: Object [object SequelizeModel] has no method 'addInterests'

Is this a bug or am I just not understanding how these associations work?

Thanks in advance for the help - I've been stuck on this for days now :(

**Comment by mickhansen** [comment]
Associations work on instances, not on models.
A model is a definition on how an instance works - You need to fetch or create an instance to be able to interact with its association methods.

**Comment by KoalaOnAStick** [comment]
Hi Mick, 

Thanks for the super quick answer, and understood! 

Love sequelize - keep up with the great work!

**Comment by mickhansen** [comment]
Great, let us know if you have anymore questions @KoalaOnAStick

**Comment by KoalaOnAStick** [comment]
Hi Mick,

I tried working on it based on your answer, but I still cannot seem to make it work, even going through the documentation multiple times.

I was hoping you could give me a rough outline of how to make this work:

1. I have a table which holds a unique set of interests named **Listofinterests** (*for example: interest: "House of cards", interest: "Biking", interest: "Travelling", ...*)
2. I have a second table which holds users named **Users** (*for example: user: "Mike", user: "Beatrice", user: "John"*)
3. I have a third table which holds the link between users and interests named **Interests**(*for example: "Mike" is interested in "House of Cards", "Mike" is interested in "Biking", "Beatrice" is interested in "Travelling"*)

This third table, Interests, can have the same user having multiple interests. At the same time, an interest can have multiple users.

I'm unclear how to code this. For example, if I would want {User: Mike} to add the {interest: House of Cards} (assuming Mike logged in and I have his id), my intuition would be to do something like this:

	Listofinterests.findOrCreate({
		where: {interest: "House of Cards"}
	})
	.then(function(Listofinterests, created){
		if 
		//the interest is created
		//create a new record in Interests, with the id of user: "Mike", and the id (passed through) of interest: "House of Cards"
		else 
		//the interest is not created
		///find the interest in the interestoverview
		///create a new record in Interest, with the id of user: "Mike", and the id (I just found) of interest "House of Cards"
	});


But from what I understand from associations, I can do this with associations and setXXX and getXXX methods.
		
	//create my associations
	Listofinterests.hasMany(Interests);
	Interests.hasMany(ListofInterests);
	Listofinterests.belongsToMany(Interests);
	Interests.belongsToMany(ListofInterests);
	//**How can I create a new record for user: "Mike", with the interest: "House of Cards"**

Do you have any examples or pseudocode that could direct me in the right way?

Thanks in advance for your help, and sorry for what seems to be really simple questions...

**Comment by mickhansen** [comment]
@KoalaOnAStick i'm not quite sure i understand your case, please provide more code of what you are trying right now.

But generally you just need to create the instances you need and then use `set[relation]` or `add[relation]`
