### ISSUE TITLE
One-To-Many association with alias,but getTarget() can not get result

### ISSUE THREAD

**Issue by catalsdevelop** [sequelize/sequelize#2827]
Hi, @vpontis @mickhansen. I have meet the **same problem** with #2392 .
Models like that:

    Person hasMany Pets,
    Pet belongsTo  One Person.

If I use the default setting, everything works fine. But when an **alias** has set, for example:

```javascript
Person.hasMany(Pet, {as:'Pets'});
Pet.belongsTo(Person, {as:'Owner'});

var person = Person.build{...};
var pet1 = Pet.build{...};
var pet2 = Pet.build{...};
//....
//Save them and run the following case

//case1:
person.setPets([pet1, pet2])
.then(function() {
	return pet1.getOwner();
	//sql log====> Executing (default): SELECT `id`, `name`, `surname`, `age` FROM `Person` AS `Person` WHERE (`Person`.`id` IS NULL);
})
.then(function(owner) {
	console.log(owner.name);//An error occurred
});


//case2:
pet1.setOwner(person)
.then(function() {
	return pet1.getOwner();
})
.then(function(owner) {
	console.log(owner.name);//retrieve the right data
});
```

In case1, the 'getOwner' function didn't get a correct foreign key.
So how can I solve this problem?
Thanks

**Comment by mickhansen** [comment]
You'll need to persist the instances first (call save()) before you can use them in associations.
Generally an instance won't be able to work without having a primary key which they don't if you're only using `.build()`

**Comment by catalsdevelop** [comment]
yes, @mickhansen. I have save them before use in associations, but not shown in the above codes. In the sql log, all person/pet1/pet2 have been added into database.

**Comment by mickhansen** [comment]
Ah yeah that confused me.
The problem is that `person.setPets([pet1, pet2])` is supposed to set the foreign key on the targets and then save but the foreign key must not be set correctly in this case.

**Comment by catalsdevelop** [comment]
hi, @mickhansen, the following code is a complete test. you can comment/uncomment to see the different logs.

````javascript
var Promise = require('bluebird');
var Sequelize = require('sequelize');

var sequelize = new Sequelize('sqlite:', {
	logging:true
});
var Person = sequelize.define('Person',{
		id:{type:Sequelize.INTEGER, primaryKey:true, autoIncrement:true},
		name:{type:Sequelize.STRING, defaultValue:null},
		surname:{type:Sequelize.STRING, defaultValue:null},
		age:{type:Sequelize.INTEGER, allowNull:false},
	},{
		timestamps:false,
		freezeTableName:true,
	}
);

var Pet = sequelize.define('Pet', {
		id:{type:Sequelize.INTEGER, primaryKey:true, autoIncrement:true},
		name:{type:Sequelize.STRING(30), allowNull:false}
	},{
		timestamps:false,
		freezeTableName:true,
	}
);

Person.hasMany(Pet);
// Pet.belongsTo(Person);
Pet.belongsTo(Person, {as:'Owner'});

sequelize.sync().then(function () {
	var p = Person.build({
		name:'jack',
		age:30
	});

	var pet1 = Pet.build({
		name:'pet1',
	});
	var pet2 = Pet.build({
		name:'pet2',
	});
	Promise.join(p.save(), pet1.save(), pet2.save()).then(function () {
		return p.setPets([pet1, pet2]);
	}).then(function(){
		return pet1.getOwner();
		// return pet1.getPerson();
	}).then(function(p){
		console.log(p);
	});
});
````

**Comment by janmeier** [comment]
`Pet.belongsTo(Person);` will make the foreign key `person_id`, while `Pet.belongsTo(Person, {as:'Owner'});` will make the foreign key `owner_id`. If you want to override the foreign key you case use `foreignKey`, for example: `Pet.belongsTo(Person, {as:'Owner', foreignKey: 'person_id' });`

**Comment by catalsdevelop** [comment]
@janmeier, I just want to get the target when alias used , not to override the foreign key.

**Comment by mickhansen** [comment]
@catalsdevelop as jan said, `as` will change the foreign key, you either override that or you use the changed foreign key.

In any case for a relation like yours:

```js
Person.hasMany(Pet);
Pet.belongsTo(Person, {as:'Owner'});
```

You need to specify the foreign key if you want those kinds of semantics, (and really, you likely want `owner_id` here for sane database design)

**Comment by catalsdevelop** [comment]
@mickhansen ,what confused me is not the foreign key, It is that an instance of Pet can not use getOwner() function to get the related people target when an alias used as 'Owner', whether or not set the 'foreignKey' property.And when I didn't use 'as', getPeople() function can work fine.

**Comment by mickhansen** [comment]
@catalsdevelop I'm not sure what you mean, you can ONLY use `getOwner` if you have `as: 'Owner'`.

**Comment by mickhansen** [comment]
If you want to use `getOwner` and still use `person_id` you need to do:

```js
Person.hasMany(Pet, {foreignKey: 'person_id'});
Pet.belongsTo(Person, {as:'Owner', foreignKey: 'person_id'});
```

If you think that is horrible we welcome an API discussion in a new issue
