### ISSUE TITLE
1:1 Relation problem

### ISSUE THREAD

**Issue by lvarayut** [sequelize/sequelize#2828]
I created 1:1 relation between Budget table and SubBudget table:

```js
/**
 * Budget Model
 */

module.exports = function(sequelize, DataTypes) {

    var Budget = sequelize.define('Budget', {
        name: DataTypes.STRING,
        description: DataTypes.STRING
    }, {
        associate: function(models) {
            Budget.hasOne(models.SubBudget);
        }
    });

    return Budget;
};


/**
 * SubBudget Model
 */

module.exports = function(sequelize, DataTypes) {

    var SubBudget = sequelize.define('SubBudget', {
        name: DataTypes.STRING,
        description: DataTypes.STRING
    }, {
        associate: function(models) {
        	SubBudget.belongsTo(models.Budget);
        }
    });

    return SubBudget;
};
```

However, what I got from MySQLWorkbench is look like 1:M relation:

![screen shot 2558-01-04 at 5 10 09 pm](https://cloud.githubusercontent.com/assets/4281887/5605567/09dbcfe6-9435-11e4-8f77-08705252b265.png)

What did I do wrong? 

Thanks in advance for your help.

**Comment by janmeier** [comment]
You did nothing wrong, but the `BudgetId` column can be interpreted in several ways, and mysql workbench seems to be interpreting it differently than sequelize. Even though your application enforces that each budget can have only one subbudget, the database structure allows for several.

You could add a unique to the `BudgetId` column, at least in 2.0-rc4: `SubBudget.belongsTo(models.Budget, { foreignKey: { unique: true }});

**Comment by lvarayut** [comment]
Got it. Thanks so much.
