### ISSUE TITLE
How to save an object with multiple has many connections

### ISSUE THREAD

**Issue by nicolabortignon** [sequelize/sequelize#2829]
Hi, 
I just pulled an object with a find, including lot of has many association:

release.find({where: {id:releaseId},
     include: [
      {model: dbProxy.Track, include: [
        {model: dbProxy.Artist, as: 'Remixer'},
        {model: dbProxy.Artist, as: 'Producer'}
      ]},{model: dbProxy.Label}
    ]
    }).then(function(release) {
       // HERE RELEASE IS A COMPLEX JSON OBJECT
  });

Now, I pass the object around my application, and I'm changing things around the object. I'm removing object from the Remixer array, I'm adding something on the Producer array. I may change some field values here and there.

Now, I'd love to save back the object in the easiest way. I can write the logic by hand, and parse the object and update every single subobject and relations accorderly. It would be great if there is an easier way to do that. Just giving back the big json object and sequelize does the rest.

Is such a thing possible? 

Thank you

**Comment by mickhansen** [comment]
Nested creation/updates is not possible. It's a feature request we got once in a while but no one has really had the time to write it yet.
