### ISSUE TITLE
Can't overwrite `updatedAt`, only `createdAt`

### ISSUE THREAD

**Issue by garrett-gottlieb** [sequelize/sequelize#2833]
Firstly, amazing library.

I am importing data from a Parse app. Each object also has the `updatedAt` and `createdAt` set, so I must overwrite the ones generated by Sequelize.

Setting `options = {raw:true}` seemed to do the trick for `createdAt`, but not `updatedAt` when inserting.

I found the option `{silent:true}` in `instance.save`, but it always unsets `updatedAt` instead of simply not setting it.

https://github.com/sequelize/sequelize/blob/cdd8c3be7961c58c1446cb4893939a2986db9876/lib/instance.js#L447

**Comment by garrett-gottlieb** [comment]
Very sneaky. I fucking love this library, although it looks like the generated docs are out of date. Beautiful code. I actually enjoy reading it.

For all the others wondering, use the `{silent:true}` option in `instance.save`.

https://github.com/sequelize/sequelize/blob/cdd8c3be7961c58c1446cb4893939a2986db9876/lib/instance.js#L447

**Comment by mickhansen** [comment]
Can you verify that `updatedAt` is not getting set with `.set(values, {raw: true})` by checking the return with `.get()` or is just not being saved?

**Comment by garrett-gottlieb** [comment]
It's just getting overwritten. I think I fixed it, I'll submit a PR :).

**Comment by mickhansen** [comment]
Right, so a change to how `silent` works might be all that is needed :)

**Comment by garrett-gottlieb** [comment]
You might want to check that one over, I just started using this tonight and it's pretty late... but it fixed the problem for me.

**Comment by garrett-gottlieb** [comment]
@mickhansen this must also work with `bulkCreate`.

```js
User.bulkCreate(records, {silent:true})
// doesn't overwrite `updatedAt` or `createdAt` if already set
```

**Comment by mickhansen** [comment]
@garrett-gottlieb `bulkBuild` is to easily reuse the same options object in case where an object literal is used, it's a very tiny optimization.

`bulkCreate` cant use `bulkBuild`, or it could but it would slow it down since it couldn't use a single INSERT statement for everything.

**Comment by mickhansen** [comment]
@garrett-gottlieb i'll take a look at it as soon as i can - Only so much freetime though :)

**Comment by garrett-gottlieb** [comment]
@mickhansen not available in `upsert` yet, as well.

**Comment by garrett-gottlieb** [comment]
and `findOrCreate` and `findOrBuild`

**Comment by mickhansen** [comment]
@garrett-gottlieb hmm findOrCreate and findOrBuild should work implicitely. upsert might not.
