### ISSUE TITLE
findOrCreate does not seem to work with paranoid: true

### ISSUE THREAD

**Issue by Kuzmin** [sequelize/sequelize#2835]
When running findOrCreate, it doesn't create a new entry if there already is one fulfilling the criteria, but has been "deleted" (`deletedAt != null`)

**Comment by mickhansen** [comment]
@Kuzmin What do you expect to happen here exactly? It won't be able to insert since there'll be a unique constraint.

**Comment by mickhansen** [comment]
You might want to extend your unique index to include the `deletedAt` column

**Comment by BridgeAR** [comment]
As @mickhansen has already mentioned the best solution to this is probably to extend the unique index. The only other solution I can think of is to implement a new parameter that would update the deleted entry to remove the deletedAt. 
@Kuzmin would that be something you wanted? Other than that there's probably nothing we could change.

**Comment by janmeier** [comment]
Closing, no response

**Comment by Kuzmin** [comment]
Sorry for not replying. I understand if you do not want to do anything, but I think that a good "fix" would be to output warnings to the user if he/she attempts to run findOrCreate where it won't work. Otherwise there are countless hours spent in debugging this very strange bug where you do `findOrCreate` and it magically revives deleted records with all their properties :)
