### ISSUE TITLE
Rewrite set / remove functions for associations

### ISSUE THREAD

**Issue by janmeier** [sequelize/sequelize#2836]
Thoughts sparked by this issue #2832.

It is clear from the issue that it would probably make sense to rewrite the two remove functions (https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L649-L705) (removePlural and removeSingular) into a single function, which accepts both arrays and a single instance.

While looking over the code, I wondered if it might make sense to rewrite the code to directly call delete, instead of calling getAssociated + setAssociated (set will then again call getAssociated to make things even more complicated :) )

Couldn't all that just be replaced with a `Model.destroy`? I think the code stems back from before `destroy` with where conditions was implemented, hence the get-set-get-delete dance

**Comment by mickhansen** [comment]
Hooks might be a reason why it's using set but i'm not sure.
Since BTM operates on a join table we should generally be able to just use `destroy`

**Comment by BridgeAR** [comment]
removePlural and removeSingular was rewritten to a single function with a single get call. So this might be closed.

**Comment by janmeier** [comment]
Yep closing this one - I have a PR coming up which refactors some of the BTM logic as well
