### ISSUE TITLE
ORDER By and .literal()

### ISSUE THREAD

**Issue by mtfranchetto** [sequelize/sequelize#2838]
I'm using sequelize 2.0.0-rc6 trying to order a table with postgis.

This code:

`[sequelize.literal(orderClause)]``

gives me the following order by in the query:

`ORDER BY [object Object]`

I read about a breaking change of ORDER BY in sequelize 2.0.0-rc3... What am i doing wrong?

**Comment by mickhansen** [comment]
@mtfranchetto did this work before upgrading? It should still work but it might have broken.
Have you tried any variations:

```js
orderBy: sequelize.literal()
orderBy: [
  [sequelize.literal()]
]
```

**Comment by mtfranchetto** [comment]
I tried with orderBy but it does not append the ORDER BY keyword, so it's not working.

**Comment by mickhansen** [comment]
Ah the key is still `order`, not sure why i wrote `orderBy`

**Comment by mickhansen** [comment]
Confirmed bug with `order: sequelize.literal()`, works for me with `[sequelize.literal()]` though

**Comment by mickhansen** [comment]
I was unable to reproduce with anything other than `order: sequelize.literal()`.

**Comment by mtfranchetto** [comment]
I tested again with [sequelize.literal()] and now works IF i remove the include statement. Strange behaviour. If i keep the include the include this is the error i get:

`TypeError: Cannot read property 'model' of undefined
    at Object.<anonymous> (/Users/mfranchetto/Development/mattia/test/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1228:63)
`

Any idea?

**Comment by mickhansen** [comment]
@mtfranchetto well you didn't mention that at first. Can you show the relevant models, associations and findAll call?

**Comment by mickhansen** [comment]
Hmm that error should really only occur if you are doing something `[[]]`

**Comment by mtfranchetto** [comment]
Sorry, i thought the problem was only caused by the order by.

I dug into the problem a bit more by testing all the possible combination of the query i need to run.

It works like this:

`findAll({
        where: sequelize.literal(whereClause),
        offset: 0,
        order: [sequelize.literal(orderClause)],
        include: [Image, User]
    });`

but it stops working if add the limit (which i need):

`findAll({
        where: sequelize.literal(whereClause),
        offset: 0,
        limit: 20,
        order: [sequelize.literal(orderClause)],
        include: [Image, User]
    });`

**Comment by mickhansen** [comment]
@mtfranchetto is it still failing because of `[object Object]` or something different now? What does `orderClause` look like?

**Comment by mtfranchetto** [comment]
It's still failing for 

`TypeError: Cannot read property 'model' of undefined at Object.<anonymous> (/Users/mfranchetto/Development/mattia/test/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1228:63)`

The ORDER BY looks like this:

`ST_Distance("TableTest"."geo", ST_MakePoint(45,45)::geography)`

**Comment by mickhansen** [comment]
Does `findAll({ where: sequelize.literal(whereClause), offset: 0, limit: 20, order: sequelize.literal(orderClause), include: [Image, User] });` work? (i removed the `[]`).

It's throwing a bug at a strange place.

**Comment by jamesone** [comment]
ordering with a custom query works for me, here is what I've done:

```
order: [
     [sequelize.literal('no_likes DESC')]
]

```
Above I have ordered my records by `no_likes`, which is a custom attribute literal I created.

**Comment by adam4813** [comment]
noice

**Comment by elchinzadeh** [comment]
It worked for me:

```
order: [
     [sequelize.literal('`column_name` DESC')]
]
```
