### ISSUE TITLE
updateAttributes fails to update attributes set in beforeUpdate hooks

### ISSUE THREAD

**Issue by marcus** [sequelize/sequelize#2842]
I have an order model. If I do `order.updateAttributes({sales: 1, shipping: 2})`, with a `beforeUpdate` that does `order.setDataValue('total', order.sales + order.shipping)` the total gets set correctly in memory, but only sales and shipping are updated in the postgres database. I've also tried using `order.set(...)` and using `order.total = 3` with the same results.

The only way I can get this to work is by doing `order.updateAttributes({sales: 1, shipping: 2}, {fields: ['sales', 'shipping', 'total'])`. I don't think I should have to explicitly pass in column names to update all dirty columns.

Sequelize 2 rc 6

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/2655
We are aware of this and will likely land a change/fix before 2.0 final

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/commit/222fb13cffe2707e6ee50dde956c3f0c0d5cf54e

**Comment by marcus** [comment]
Thanks! Can't wait to give it a try!

**Comment by mickhansen** [comment]
Mind you this doesn't run validation for the changes values yet (that's upcomming, see #2655 for progress).
