### ISSUE TITLE
Change all examples to use lowercase model names

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2846]

**Comment by psayre23** [comment]
What is the purpose of this change? I'm looking at reporting a big with capitalization, and was researching before I did. Is this a standard the library has chosen to follow?

**Comment by mickhansen** [comment]
@psayre23 lowercase naming results in saner naming throughout in my opinion, atleast when building REST API's

**Comment by psayre23** [comment]
Here's the specific bug I was mentioning.

https://github.com/sequelize/sequelize/issues/3598
