### ISSUE TITLE
Model.destroy() clears table if no where clause is given

### ISSUE THREAD

**Issue by ekmartin** [sequelize/sequelize#2847]
Omitting the where clause in `Model.destroy()` will result in a `DELETE FROM ... WHERE 1=1` query, and thus clearing the table. `.destroy()`'s syntax changes towards v2.0.0 also makes this a bit more problematic, since accidentally using the old syntax will do the same as no where clause at all.

One solution could be to at least require the where-option to be given as an empty object for it to clear all, i.e. `Model.destroy({ where: {} })`;

**Comment by janmeier** [comment]
Agreed

**Comment by mickhansen** [comment]
PR merged, closing.
