### ISSUE TITLE
[BUG]When retriving data with the WHERE clause of an empty Array, it throws an obscure error

### ISSUE THREAD

**Issue by ppoo24** [sequelize/sequelize#2849]
Hi, during my working, i found pieces of code below not working properly:
```js
return User.findAll({
	where: [] //remove this OR change to where:['1=1'] is ok
});
```
as test upon, when remove the __where__ option or push one element into it, that's ok, or it will throw:
```log
TypeError: Cannot call method 'replace' of undefined
    at Object.SqlString.format (e:\webroot\zx250\node_modules\sequelize\lib\sql-
string.js:145:14)
    at Object.module.exports.format (e:\webroot\zx250\node_modules\sequelize\lib
\utils.js:84:22)
    at Object.module.exports.QueryGenerator.getWhereConditions (e:\webroot\zx250
\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1488:26)
    at Object.module.exports.QueryGenerator.selectQuery (e:\webroot\zx250\node_m
odules\sequelize\lib\dialects\abstract\query-generator.js:1176:30)
    at module.exports.QueryInterface.select (e:\webroot\zx250\node_modules\seque
lize\lib\query-interface.js:662:35)
    at null.<anonymous> (e:\webroot\zx250\node_modules\sequelize\lib\model.js:72
6:34)
From previous event: [TypeError: Cannot call method 'replace' of undefined]
```
need to be fixed.

**Comment by janmeier** [comment]
Not sure if this "needs" to be fixed. As far as I know passing an empty as a where condition has never been correct syntax

**Comment by ppoo24** [comment]
I'm glad to see Sequelize will automatically ignore the empty where condition, if the it's not necessary, i think that throwing an humanable exception like "The where condition can't be an empty array" instead of "Cannot call method 'replace' of undefined" will locate to the code more accurately.
tks for your time :)

**Comment by mickhansen** [comment]
@janmeier we actually support `{}` to be turned into `1=1` but yeah it's not exactly official or correct syntax.

I do actually think we should probably handle this case with an empty where condition as an [].
Either as empty query or as an error like @ppoo24  suggests.

In any case more sensible errors will always be the ideal.

**Comment by ppoo24** [comment]
It seem the __order__ option has the same problem: `Cannot read property 'length' of undefined` while non-child array

**Comment by mickhansen** [comment]
@ppoo24 Hmm i was pretty sure that `include: []` was possible actually.

**Comment by ppoo24** [comment]
@mickhansen Sorry about my rash suggestion, it may caused by another way

**Comment by GuilhermeReda** [comment]
```include: []``` throws me an error

**Comment by mickhansen** [comment]
@GuilhermeReda hmm alright, i'll take a look at it.

**Comment by GuilhermeReda** [comment]
I think that it should work like this.

````javascript
User
    .findAll({
		attributes: []
	})
    .then(function(result) {
      console.log('Users found', result);
    })
/*This should produce SELECT * FROM "Users" AS "User"*/
 
//and this
User
    .findAll({
		attributes: [],
		include      : [{
            model        : models.Upload,
            attributes   : ['id', 'name']
        }]
	})
    .then(function(result) {
      console.log('Files found', result);
    })

```
This should produce 

```sql 
SELECT 
    "Uploads"."id" as "Uploads.id", 
    "Uploads"."name" as "Uploads.name" 

FROM "Users" AS "User"

LEFT OUTER JOIN "Uploads" on "Uploads"."UserId" = "Users"."id" 

```

**Comment by mickhansen** [comment]
An empty `attributes` array will result in no attributes whenever possible.

**Comment by mickhansen** [comment]
`include: []` does not crash for me.
