### ISSUE TITLE
Query was empty error

### ISSUE THREAD

**Issue by burakkilic** [sequelize/sequelize#2850]
Hi;

I am getting 

    {"error":{"name":"SequelizeDatabaseError","message":"ER_EMPTY_QUERY: Query was empty","parent":    {"code":"ER_EMPTY_QUERY","errno":1065,"sqlState":"42000","index":0,"sql":""},"original":    {"code":"ER_EMPTY_QUERY","errno":1065,"sqlState":"42000","index":0,"sql":""},"sql":""}}

when I make a put request from AngularJS code if the data is the same in the database. 

For example, if I have item data 

    {
          id: 1,
          name: item1,
          desc: desc1
    }

   and the same data in the db, put request is giving me the error above.

**Comment by mickhansen** [comment]
@burakkilic you have to atleast show the call you are making that triggers that error.

**Comment by burakkilic** [comment]
Sorry @mickhansen , let me explain.

My MenuTranslation model is:

    module.exports = function(sequelize, DataTypes) {
	var MenuTranslation = sequelize.define('MenuTranslation', {
			name: DataTypes.STRING,
			description: DataTypes.STRING
	},{
		tableName: 'menu_translations',
		timestamps: false,
		associate: function(models){ 
		  MenuTranslation.belongsTo(models.Menu, { onDelete: 'cascade' });
		  MenuTranslation.belongsTo(models.Language);
		}
	});

	return MenuTranslation;
    };

I am trying to edit with this data:

    {"id":87,"name":"menuName1","description":"description1","MenuId":63}

If I send this data like "form-data" in Postman, it is successfull.

If I send raw json data, the error is:

    {
    "error": {
    "name": "SequelizeDatabaseError",
    "message": "ER_EMPTY_QUERY: Query was empty",
    "parent": {
    "code": "ER_EMPTY_QUERY",
    "errno": 1065,
    "sqlState": "42000",
    "index": 0,
    "sql": ""
    },
    "original": {
    "code": "ER_EMPTY_QUERY",
    "errno": 1065,
    "sqlState": "42000",
    "index": 0,
    "sql": ""
    },
    "sql": ""
    }
    }

I am using Epilogue for RESTful service.

    var menuTranslations = rest.resource({
    model: db.MenuTranslation,
    include: [db.Language],
    endpoints: ['/menuTranslations', '/menuTranslations/:id']
    });

Hope this helps more.

**Comment by mickhansen** [comment]
@burakkilic i don't know how epilogue works, so it might be a bug with them. You'll need to dig up the actual sequelize call for us to be able to help you i'm afraid.

**Comment by burakkilic** [comment]
ok, I will tell @mbroadst about that. As you say, it can be related to epilogue. Thank you.
