### ISSUE TITLE
DEBUG support

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2852]
More verbose debugging support.

Everything from hooks being called to calls.

**Comment by cusspvz** [comment]
Are you thinking on applying [debug](https://github.com/visionmedia/debug) on each **sequelize** file or transporting it into **logging**

**Comment by mickhansen** [comment]
I'm talking about the debug module.

**Comment by AJamesPhillips** [comment]
What's the best way to help with this?  I have come across an error running migrations in production so would love to specify a `sequelize db:migrate --verbose`  or `--debug` if possible.

**Comment by mickhansen** [comment]
@AJamesPhillips To open PR with appropriate calls to https://www.npmjs.com/package/debug
