### ISSUE TITLE
How do you add an association to an existing table without losing data?

### ISSUE THREAD

**Issue by countrdd** [sequelize/sequelize#2853]
I have a user table, and need to add an association to the transactionitem table. All the tables exist an there is a ton of data I cannot lose. what is the best way to add the assocation?

**Comment by mickhansen** [comment]
You can add the code part of the association without any issues.
You'll need to use a migration to add the relevant foreign key though.

Take a look at: https://github.com/sequelize/umzug

**Comment by mickhansen** [comment]
Or if you're up to it you can just run a raw query to add the foreign key.
Can you show the association you would like to add?

**Comment by countrdd** [comment]
my transaction item table already has an association to Users based on a field called user_id.
my transaction item table already has a field (and populated) called provider. What i need to do is associate the provider as well as the user back to the users table.

Sample Transacionitem record:
 user_id on transactionitem is set to 1 for a user name LEILLC.NET
 provider on transcationtem is set to 12 for a provider of Hagen.

Note: all the fields already existed 

so I changed the model for transcationitem to this.

associate: function (models) {

                Transactionitem.belongsTo(models.User)
                Transactionitem.belongsTo(models.User,{as: 'provider',foreignKey:'id'})
                Transactionitem.belongsTo(models.Product,{foreignKey:'upc'})
                Transactionitem.belongsTo(models.Transaction)'
but it does not grab the provider information from the user table.

**Comment by mickhansen** [comment]
If the fields already exist you just need to add the correct code.
`Transactionitem.belongsTo(models.User,{as: 'provider',foreignKey:'provider'})` perhaps?

**Comment by mickhansen** [comment]
foreignKey should almost never be `id` or any other primary key, it should point at the attribute that points back at the model.
