### ISSUE TITLE
Use `depd` for deprecated messages

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2857]
This issue is a proposal to replace [sequelize's custom fn](https://github.com/sequelize/sequelize/blob/c3f2603048ac9ffaea0886fd6c135d21bf094428/lib/promise.js#L8) by [depd](https://www.npmjs.com/package/depd) for showing deprecated messages.

Advantages:
* Warns developer in which file and line it is being called.
* It has the same appearance that `debug` module.

![captura de ecra 2015-01-8 as 02 14 09](https://cloud.githubusercontent.com/assets/3604053/5656917/13b01eec-96dc-11e4-9996-8063268dc3dc.png)

**Comment by mickhansen** [comment]
Of course something like that exists. Yeah that sounds like a good idea.
+1

**Comment by BridgeAR** [comment]
This is already in use. So the ticket should be closed.
