### ISSUE TITLE
Incorrect foreign key name in belongsToMany association

### ISSUE THREAD

**Issue by mrpotato3** [sequelize/sequelize#2861]
Hi,

I'm trying to o specify foreign key name in N:M relations using beongsToMany + belongsToMany in Sequelize 2.0.0 rc6.

Code I'm using:

```javascript
ServiceX.belongsToMany(ServiceY, {as: 'y', foreignKey: 'service_x_id'});
ServiceY.belongsToMany(ServiceX, {as: 'x', foreignKey: 'service_y_id'});
```

Result in database (join table):

ServiceXServiceY_service_x_id_fkey ---> ServiceX (CORRECT)
ServiceXServiceY_ServiceYId_fkey ---> ServiceX (INCORRECT)

I don't know why is working properly with first expression but not with second. Can you help me?

Many thanks!

**Comment by mickhansen** [comment]
There's a bug in the implementation that, you'll need to do this as a workaround:

```js
ServiceX.belongsToMany(ServiceY, {as: 'y', foreignKey: 'service_x_id', otherKey: 'service_y_id'});
ServiceY.belongsToMany(ServiceX, {as: 'x', foreignKey: 'service_y_id', otherKey: 'service_x_id'});
```

**Comment by mrpotato3** [comment]
Perfect!

Problem solved. Thanks for your fast reply.

This bug will be solved in final release, no?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/2845
Yeah it's slated for 2.0
