### ISSUE TITLE
MSSQL dialect no longer formats geo types

### ISSUE THREAD

**Issue by thecaddy** [sequelize/sequelize#2866]
Originally sequelize used the node-mssql, https://github.com/patriksimek/node-mssql, and switched to using the tedious driver.  This provided formatting of Geography and Geometry types:
https://github.com/patriksimek/node-mssql#geography

Commit where switched to tedious:
https://github.com/sequelize/sequelize/commit/99abdc3f3f338874cc7416700a3058c5af72d15e

Suggest either switching back to mssql or somehow incorporating the logic located in mssql to format geo: https://github.com/patriksimek/node-mssql/blob/master/src/udt.coffee

**Comment by mickhansen** [comment]
@mbroadst

**Comment by mbroadst** [comment]
okay yeah we can incorporate that, I didn't think it was relevant atm (though thinking about it, you guys are probably using it). Switching back to node-mssql is a no go since they try to take over connection pooling. I'll take a look at this as soon as I'm back from vacation.

**Comment by theverything** [comment]
I turned the geoparser into an npm module https://www.npmjs.com/package/mssql-geoparser

**Comment by mbroadst** [comment]
@theverything fantastic, much appreciated. I'll incorporate this asap unless someone else does :smile:

**Comment by joewood** [comment]
Was this incorporated?

**Comment by mickhansen** [comment]
Don't believe so @joewood

**Comment by renatoargh** [comment]
Sorry for re-asking but... was this incorporated?
