### ISSUE TITLE
MSSQL dialect no longer returns updated object after insert/update query

### ISSUE THREAD

**Issue by thecaddy** [sequelize/sequelize#2871]
Sequelize objects after inserting, updating, or saving would return the object with the respective values updated.  This was removed and in its current state will only return to you the limited fields you may of submitted for insertion or updating leaving you without id's or various other generated fields associated with the object.

The code below, "its not great by any means", but it added the "OUTPUT" keyword and "INSERTED." to return the values to populate the sequelize object:

```
insertSql: function(tableName, valueHash, modelAttributeMap, options) {		
    var query		
      , valueQuery = 'INSERT INTO <%= tableName %> (<%= attributes %>)'		
      , emptyQuery = 'INSERT INTO <%= tableName %>';		
		
    valueQuery += ' OUTPUT <%= selFields %>  VALUES (<%= values %>)';		
    if(modelAttributeMap){		
      emptyQuery += ' OUTPUT <%= selFields %>';		
    }		
    emptyQuery += ' DEFAULT VALUES';
...
```
```
 updateSql: function(tableName, valueHash, where, options, attributes){		
    options = options || {};		
		
    valueHash = Utils.removeNullValuesFromHash(valueHash, this.options.omitNull, options);		
		
    var query		
      , selFields = []		
      , values = [];		
		
    query = 'UPDATE <%= tableName %> SET <%= values %> OUTPUT <%= selFields %>';		
		
    var parsedValues = valuesToSql(valueHash, attributes, true);		
    for (var key in valueHash) {		
      var value = valueHash[key];		
      selFields.push('INSERTED.' + quoteIdentifier(key));		
    }
...
```

Related commit:
https://github.com/sequelize/sequelize/commit/2a2cd48a041d406dd1aa3781d40ba7014a1148bc

**Comment by mickhansen** [comment]
@mbroadst

**Comment by mbroadst** [comment]
It seems crazy to me that we don't have coverage for this feature. @thecaddy to be specific, mssql DOES return some changed fields, but you want all fields returned, right?

**Comment by mbroadst** [comment]
@thecaddy can you actually provide more of a concise example here? We need to start with a failing test case here, because looking at the tests it seems that this functionality IS tested and passes for mssql.

**Comment by thecaddy** [comment]
@mbroadst We have an auto increment id in our table and need the id returned to use on insert.  It seemed wild to me that this wouldn't be covered by the hundreds of tests in sequelize.  I'll grab the code when I get in today that is performing our insert query.

**Comment by mbroadst** [comment]
@thecaddy are you by any chance having this issue with bulkCreate? I've been making headway in making sure this is indeed tested with mssql, and can confirm that it's broken for bulkCreate but not for create (I haven't yet tested updates)

**Comment by thecaddy** [comment]
It looks like we failed to pass in field and because the old code had sort of a shotgun for mapping the field names it was passed still mapped.

The relevant test in /test/model/create.test#L755

**Comment by mbroadst** [comment]
@thecaddy glad you figured it out, I ended up fixing some bugs with return values anyway :smile:
