### ISSUE TITLE
Model.validate(field, value) and Instance.validate(field)

### ISSUE THREAD

**Issue by garrett-gottlieb** [sequelize/sequelize#2875]
A function that returns the validation result for a single field without actually setting it.

eg.

``` js
User = sequelize.define('User', {
  email: {
    type: Sequelize.STRING,
    validate: {
      isEmail: true
    }
  }
})
User.validate('email', 'asdf@fdas.com') // true
User.validate('email', 'notanemail') // false
```

It would also be nice to have the `instance.validate(field)` to call validate on a single field (or array of fields).

**Comment by mickhansen** [comment]
It would have to return a promise since validations **can** be asynchronous.

**Comment by mickhansen** [comment]
I suppose we could create a `validateSync` function that only works with sync validations and warns if there's an async one.

**Comment by akaNightmare** [comment]
+1

**Comment by Paul-DS** [comment]
Is this functionality is planned to be implemented ? It would be very useful !

**Comment by loogle18** [comment]
For those who're looking for it, here's workaround:
```
// for single attribute
Model.build({ email: 'example@gmail.com' }).validate({ skip: allAttrsExceptEmail });

// or for multiple attributes
let attrsToSkip = Object.keys(Model.attributes).filter(x => !Object.keys(data).includes(x));
Model.build(data).validate({ skip: attrsToSkip });
```

---

But anyway, how about to re-open this?
