### ISSUE TITLE
Deprecated message for belongsToMany

### ISSUE THREAD

**Issue by PierrickP** [sequelize/sequelize#2876]
I get this warning when using **belongsToMany**

> belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model

``` JavaScript
Schedules.belongsToMany(Dish, {through: ScheduleDishes});
Dishes.belongsToMany(Schedule, {through: ScheduleDishes});
```

I'm not an expert of JS but this part of code seem to be a bit weird
https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L41-L47
In my case, _this.throught_ will be setted with my model object. But the deprecated condition are **true** ( `({}) ? console.log('pass') : console.log('fail')` )

``` JavaScript
this.through = {}; // my model

if (this.through) {
      deprecated('belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model');
}
```

I'm a bit lost with my associations .. and documentation & test are still outadated with 2.0.0-rc7

**Comment by chuks** [comment]
I'm still seeing this deprecation warning on  
Schedules.belongsToMany(Dish, {through: ScheduleDishes});
Dishes.belongsToMany(Schedule, {through: ScheduleDishes});

belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model

**Comment by mickhansen** [comment]
@chuks are you on 2.0.4?

**Comment by chuks** [comment]
Yes, I am. When I specify through as a string, it doesn't give the warning. However, I am using custom attributes on the through model, hence I need to use the model, and not a string.

**Comment by mickhansen** [comment]
Should really not be giving you the warning then, there was a minor bug on a version before 2.0.4 that the warning was there by mistake.

**Comment by chuks** [comment]
Yeah. I saw the notes you mad, but I am still getting the warning. After living the issues from yesterday's associate not being called, I left the logging in the associate method of my models, so I can see that it warns immediately I enter associate. See logs:

Happening - I am in associate. Happening.Instance.prototype: [object SequelizeInstance]
Passwordreset - I am in associate. Passwordreset.Instance.prototype: [object SequelizeInstance]
User - I am in associate. User.Instance.prototype: [object SequelizeInstance]
belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model
