### ISSUE TITLE
Question: is there a way to have camelCase *and* underscored

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#2877]
Is it possible to have `createdAt` in JavaScript but `created_at` in DB?

**Comment by JSteunou** [comment]
Ho, I hoped for a magical option like `underscored` but only for columns :innocent:

**Comment by mickhansen** [comment]
@JSteunou not currently i'm afraid.

**Comment by JSteunou** [comment]
ok in that case I have an issue.

If I do as you wrote above I have this in my object when I inspect or do .get()

```
updatedAt: Fri Jan 09 2015 14:06:36 GMT+0100 (CET),
createdAt: Fri Jan 09 2015 14:06:36 GMT+0100 (CET),
deleted_at: undefined
```

it seems like when NULL in db, column arent translate to object property.

**Comment by mickhansen** [comment]
@JSteunou hmm strange, it should just be null in that instance.

**Comment by miguelcobain** [comment]
A global default configuration for this would be great.

**Comment by mendenhallmagic** [comment]
Is the `underscored` option supposed to accomplish this? I only see `underscoredAll` mapping tableNames...am I missing something?

**Comment by mickhansen** [comment]
@mendenhallmagic accomplish what exactly? `underscored` generally things as underscored, that includes timestamps.

**Comment by mendenhallmagic** [comment]
Just want to make sure I understand correctly. I have the following sequelize instance:
```js
var sequelize = new Sequelize('sqlite:chat-test.db', {
  define: {
    freezeTableName: true,
    timestamps: false,
    underscored: true,
  },
  logging: false,
})

```
and the following model:
```js
module.exports = function (sequelize, DataTypes) {
  return sequelize.define('chat', {
    id: rowId,
    chatId: {
      field: 'chat_identifier',
      type: DataTypes.STRING,
    },
    displayName: DataTypes.STRING,
    roomName: DataTypes.STRING,
  })
}
```
Should all columns be snake_case in the db? I just ran a `sequelize.sync()` on a new sqlite file with 2.0.3, and the fields in the resulting db are camelCased. I do have a PR on query-generator...

**Comment by mendenhallmagic** [comment]
Forgot to include my rowId module:
```js
module.exports = {
  field: 'ROWID',
  type: 'INTEGER',

  autoIncrement: true,
  primaryKey: true,
}
```
I'm not a sqlite or sequelize expert, but this shouldn't cause any related issues as far as I can tell.

**Comment by mickhansen** [comment]
@mendenhallmagic Ah like that, no in this case underscored refers primarily to table names, the autogenerated timestamp columns and a few other bits, not genering attribute naming.

**Comment by JSteunou** [comment]
I'm closing this since the question was answered and covered
