### ISSUE TITLE
unable to set `setDataValue` of any other data value in custom setter

### ISSUE THREAD

**Issue by blakmatrix** [sequelize/sequelize#2884]
I am attempting to do something like this, I haven't seen anything that says I can't, nor anything on this:

```javascript
var Foo = sequelize.define('Foo', {
    baz: {...},
    flag: {...},
    bar: {
      type: DataTypes.STRING,
      defaultValue: null,
      set: function setFooBar(value) {
        if (null === value || undefined === value) {
          value = null;
        } else {
          if (null === this.getDataValue('baz')) {
            this.setDataValue('baz', DataTypes.NOW); // set baz on bar update if there is not a current saved date in it
          }
          this.setDataValue('flag', true); // set bar's flag once created
        }
        this.setDataValue('bar', value);
      }
    }
...
```

`bar` will get set but `flag` and `baz` won't (If I do a `this.getDataValue('baz')`after setting, it'll contain the set value, but it doesn't propagate to the update statement). Any Ideas of what is happening here?

**Comment by mickhansen** [comment]
You have verified that the setter is called i assume?
It should work as intended, mind you you're not actually setting `baz` anywhere in that code. (But i assume that might be a typo with `bar_created_at`?

**Comment by blakmatrix** [comment]
@mickhansen Yes, the setter is being called, if I was to dynamically append a string to the value in the setter it gets set as expected and is in the sequelize (postgres) statement, baz and flag don't make it into the statement. I haven't upgraded yet but am on `1.7x` -- I don't know if that matters.

**Comment by mickhansen** [comment]
What does your save statement look like? Are you setting `fields`?

**Comment by blakmatrix** [comment]
We actually don't use save, so the way we call this is like such
```javascript
function updateFoo(fooId, fooObj, callback) {
  var Foo = models.Foo;
  Foo.update(fooObj, {id: fooId})
    .success(function() {
      Foo.find({id: fooId})
          .success(function(result) {
            callback(null, result.values); // return the updated record
          });
    })
    .error(function(err) {
      log(['error'], err);
      callback(err);
    });
}
```

We've been thinking of moving to using promises on the latest but that will take us at least a weeks worth of work to convert our entire app and a clear understanding of whats the best way to convert everything.

**Comment by mickhansen** [comment]
Ah you are just bulk update, i do believe it should be using the setters internally when running through the hooks but.

What does `fooObj.toJSON()` give you right before the update call?
Is `fooObj` even an instance or a POJO? And do you know if your setters are called before .update() or "during"?

**Comment by blakmatrix** [comment]
Its a POJO, the setter is called sometime between calling update (sorry `models` in my example is the object which to access sequelize models) and the find statement.

**Comment by mickhansen** [comment]
Strange, it's likely an issue with using bulk update together with setters.

**Comment by BridgeAR** [comment]
@blakmatrix did you upgrade to newer versions by now and those this issue persist?

**Comment by blakmatrix** [comment]
I've Upgraded, the issue is gone thanks!
