### ISSUE TITLE
afterCreate() hook does not set Model field

### ISSUE THREAD

**Issue by muuuub** [sequelize/sequelize#2885]
The hook runs after a user is created, but it doesn't actually set the slug field.

    module.exports = function(sequelize, DataTypes) {
        var User = sequelize.define('User', {
            username: DataTypes.STRING,
            slug: DataTypes.STRING
        }

        User.afterCreate(function(user, options, fn) {
            var slugify = require('slug');
            user.slug = slugify(user.username);
            fn(null, user);
        });  
        return User;
    };

Creating a user:

    models.User.create( { username: "bob 1234" });

**Comment by muuuub** [comment]
This works though:

    User.afterCreate(function(user, options, fn) {
        var slugify = require('slug');
        var s = slugify(user.username);
        user.updateAttributes({ slug: s });
        fn(null, user);
    });

**Comment by mickhansen** [comment]
@muuuub what are you expecting? That the value would be in the database or that it would be on the instance?

It should definitely be on the instance with an afterCreate, but it won't be in the database, as expected, since afterCreate runs AFTER the insert statement.

**Comment by mickhansen** [comment]
What you likely want is to move your original hook to `beforeCreate`
