### ISSUE TITLE
Question: passing data from create to bulkcreate

### ISSUE THREAD

**Issue by KoalaOnAStick** [sequelize/sequelize#2892]
Hi guys,

I'm having some trouble with passing data from create to bulkcreate.

My code looks like this:

	Table.create({
		userid: req.user.id,
		tabletype:	req.body.tabletype,
	})
	.then(function(table){
		Othertable.bulkCreate(req.body.othertabledata, {tableid: table.id});
	});

I would expect this code to: 
1. first create a single instance of table, 
2. then pass through the data of this instance to bulkcreate, and 
3. add the "tableid" to each of my records created by bulkcreate.

However, the data being inserted in my tableid column ends up being "null".

I've tried changing my code to represent an array rather than an object (as indicated in the API), but then sequelize gives me an error code.

Any idea where I'm going wrong?

Thanks in advance!

**Comment by mickhansen** [comment]
The 2nd argument to `bulkCreate` is `options`, not default values.
You'll need to do something like:

```js
bulkCreate(req.body.othertabledata.map(function (values) {
  return _.extend(values, {tableid: table.id});
});
```

**Comment by KoalaOnAStick** [comment]
Thanks @mickhansen Mick, that worked perfectly.

For those that look this up, @mickhansen's solution requires underscore.js:
In your terminal:

    npm install underscore --save

In your app:

    var _ = require('underscore');

**Comment by mickhansen** [comment]
Or lodash ;)
