### ISSUE TITLE
Associations set on a POST request seem to not be active on next GET request

### ISSUE THREAD

**Issue by MarkTraceur** [sequelize/sequelize#2898]
I have a system that does this:

* POST to create a new object in the database and associate that object with several others that already exist
* Return a JSON object with an href to the new object (not its actual body)
* GET to get a list of objects of the same type, because we just created one and it's wise to update the list to see the new one - the server does a findAll with a proper include array to include the associated objects and returns the results

Expected result: GET request should have a list of objects including the new object, which should also include the new associations

Actual: The new object exists, but has no associations.

I thought this might be a race condition, but if that's the case, the association promises that I use in the POST request shouldn't have fired yet. I tried looking at just the associations, and for some reason request.getSong() works fine and gets the associated song, but request.Song doesn't (despite include: { model: models.Song} in the request.findAll call).

Advice, or thoughts, or a bugfix...I don't really care which, but I'd like this to start working! :)

**Comment by MarkTraceur** [comment]
GET request code: https://gitorious.org/minstrel/minstrel/source/0d8dab99fd885e599c7686e788448b40f784669f:routes/requests.js#L21-50

POST request code: https://gitorious.org/minstrel/minstrel/source/0d8dab99fd885e599c7686e788448b40f784669f:routes/requests.js#L106-129

Request model: https://gitorious.org/minstrel/minstrel/source/0d8dab99fd885e599c7686e788448b40f784669f:models/request.js

Song model: https://gitorious.org/minstrel/minstrel/source/0d8dab99fd885e599c7686e788448b40f784669f:models/song.js

**Comment by mickhansen** [comment]
If you manually look at `/requests/:id` after a post does it then have the correct data?

**Comment by MarkTraceur** [comment]
Yup!

That makes sense, because refreshing the main list also works fine.

So it must be a race condition, and the promise callbacks for request.setSong must be firing too soon?

**Comment by MarkTraceur** [comment]
As confirmed on IRC, I'm an asshole.

I needed to wait for my Angular save() function to callback before trying to update the list. OF COURSE.

Thanks so much for the debugging help, @mickhansen
