### ISSUE TITLE
There are a number of typos in the Getting Started article

### ISSUE THREAD

**Issue by ClimbsRocks** [sequelize/sequelize#2899]
I'm happy to go through and fix all the ones I've found. Let me know if you have any preferences on style that aren't mentioned in your Contrib file.

**Comment by mickhansen** [comment]
No real preferences for the docs, just that they be clear, succinct (as in to the point) and good :D

**Comment by mickhansen** [comment]
Thanks a bunch for this @ClimbsRocks, please keep em coming - We would like the docs to be much better.

**Comment by janmeier** [comment]
Closing this issue, but further PRs are very welcome @ClimbsRocks  :)
