### ISSUE TITLE
sql injection risk  when when using order.

### ISSUE THREAD

**Issue by levansuper** [sequelize/sequelize#2906]
Test.findAndCountAll({
where: { id :1 },
order : [['id', 'DESC; delete from test;']]
})

when the client sends parameters of which columns should be ordered with there is a risk of sql injection.
this works with PostgreSQL. I haven't tested with other databases though.

**Comment by mickhansen** [comment]
It's likely safe to assume that the second argument of an order statement could only ever be `ASC` or `DESC`

**Comment by Zolmeister** [comment]
Please update npm

**Comment by mickhansen** [comment]
@Zolmeister We will. Can always use a git reference in the meantime.

**Comment by mickhansen** [comment]
I will likely push a new NPM version after i fix #2969 tonight.
