### ISSUE TITLE
bulkCreate id is null

### ISSUE THREAD

**Issue by YouriT** [sequelize/sequelize#2908]
Hi guys,

When doing a 
```javascript
User.bulkCreate([user1,user2,...]).success(function(users) {
	users.forEach(function(user) {
		console.log(user.id); // Always null
	});
);
```

So this example produces a long list of ```null``` values, I've to do a find() to have the proper value in the instance. But, if I go with the classic : ```.build()``` & ```.save()``` methods or the ```.create()``` one, it works well. Any thoughts ?

Thanks !

**Comment by mickhansen** [comment]
Only works on postgres. MySQL etc doesn't support returning auto incremented values for a multi insert.
If you absolutely need the primary keys you have to either do a find again or do a looping create.

**Comment by YouriT** [comment]
@mickhansen I'm using Postgres in fact...

**Comment by mickhansen** [comment]
Alright, then you're missing the returning option (which is understandable):
`User.bulkCreate([user1,user2,...], {returning: true})`

**Comment by YouriT** [comment]
Well, I've the following code and it still writes me ```null``` in the console.

```javascript
fct
	.createUsers()
	.success(function(users) {
		users.forEach(function(user) {
			console.log(user.id);
		});
        });
fct.createUsers = function() {
	var users = [];
	for (var i = 0; i < 100; i++) {
		users.push({
			firstName: 'Firstname ' + i,
			lastName: 'Lastname ' + i,
			email: 'me' + i + '@me.com',
			phone: '+471234567',
			password: Math.random() * 1000,
			verified: true,
			validationCode: Math.random() * 10000,
			birthDate: new Date(1990 - i, 12, 1)
		});
	}
	return app.db.User.bulkCreate(users, {
		returning: true
	});
};
```

**Comment by mickhansen** [comment]
What version are you using?

**Comment by YouriT** [comment]
2.0.0-rc6

**Comment by mickhansen** [comment]
Was fixed in rc6: https://github.com/sequelize/sequelize/blob/master/changelog.md

**Comment by YouriT** [comment]
Just updated and it works now thanks @mickhansen ! :)

**Comment by hasanraza-axovel** [comment]
I'm inserting multiple rows with bulkCreate, my id(auto increamented) is returning null

**Comment by michaelunltd** [comment]
I encounter the same, using bulkCreate to create many Models at once and the return of promise then has null id

**Comment by nsonankar** [comment]
Try : individualHooks: true
like 
User.bulkCreate([user1,user2,...], {individualHooks: true})

**Comment by ex3ndr** [comment]
Doesn't work for me too on PSQL

**Comment by Stradivario** [comment]
@nsonankar Great job thank you!

**Comment by cherishh** [comment]
tried what @nsonankar said, it works. I'm using mssql
