### ISSUE TITLE
instance updateAttributes does not Update manually set values

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#2910]
found in rc7

I have a use case with `DataTypes.VIRTUAL` like in the [doc](http://sequelize.readthedocs.org/en/latest/api/datatypes/#virtual)

But if I do this on existing user instance

```
user.updateAttributes({password: 'newOne'}).then(function(updatedUser) {
  // updatedUser.password_hash is ok
  return db.User.findOne({where: {id: updateUser.id}});
}).then(function(foundUser) {
  // foundUser.password_hash still undef or not changed
});
```
and the request was

```
Executing (default): UPDATE `user` SET `updated_at`='2015-01-12 11:05:55' WHERE `id`=1
```

quite empty

**Comment by JSteunou** [comment]
Found why: usage of [intersection](https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L715) instead of `union`

**Comment by mickhansen** [comment]
Works with set & save?
Using `union` would be bad, it's explicitely supposed to only update the intersection of value key and changed key.

I do see your usecase but it could probably be saved by using a seperate set and save.

**Comment by JSteunou** [comment]
I think I see what you mean. Are you using intersection to find the wanted to be update fields that pass validation?

**Comment by JSteunou** [comment]
I works with set + save. Why?

**Comment by mickhansen** [comment]
@JSteunou cause `save` has differente semantics. `update` is supposed to only save what is passed to it.

I use intersection so that the query wont break on bad fields and will update atomically.

**Comment by JSteunou** [comment]
Ok. That seems not natural, especially with documentation saying update = set + save.

**Comment by mickhansen** [comment]
Depends on how you look at it, it makes `update` a way more safe and atomic operation.
But yes the docs might need to be updated.

**Comment by JSteunou** [comment]
See your point.
Thank you for your very responsive help @mickhansen

**Comment by mickhansen** [comment]
@JSteunou unfortuneatly we can't cater to all use cases always. Glad to help :)

**Comment by arcanis** [comment]
@mickhansen I think that update should have some way follow the `setDataValue` calls and add them the updated properties to what will be called. The current behavior (ignoring setters in the persisted data) seems to have a lot of drawbacks for a use case (persisting properties changes without persisting what these properties setters have set) that isn't very intuitive.

**Comment by mickhansen** [comment]
`update` has very specific security semantics currently. It's always possible to just use `.set().save()`
I'm open for discussion about it though.

**Comment by arcanis** [comment]
And how would you feel about giving `updateAttributes` a different semantic than `update` ?

**Comment by mickhansen** [comment]
Well they are currently the same method. I'm not against it but i'm not sure how we could distinguish them enough.

**Comment by arcanis** [comment]
Hm I feel like making one of them apply setters and the other not would be an important distinction :

```js
var User = sequelize.define( 'user', { passwordStr : STRING, passwordLen : INTEGER, password : {
    type : VIRTUAL,
    get( ) { return this.getDataValue( 'passwordStr' ) },
    set( value ) { this.setDataValue( 'passwordStr', value ); this.setDataValue( 'passwordLen', value.length )
} } );

var user = User.find( ... );

user.updateAttributes( { password : 'test' } );
// vs
user.update( { passwordStr : 'test', passwordLen : 4 } );
```
