### ISSUE TITLE
belongsToMany depreciation notice

### ISSUE THREAD

**Issue by ozum** [sequelize/sequelize#2913]
Hello,

Even I provided "through" option as string for belongsToMany, I get the warning below:

belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model.

My definition is as below:

    public.cart.belongsToMany(public.product, { as: 'cartLineItemProducts',
         foreignKey: 'cart_id',
         otherKey: 'product_id',
         through: 'cart_line_item',
         onDelete: 'RESTRICT',
         onUpdate: 'CASCADE'
    });

I guess lib/associations/belongs-to-many line 45 should is the reason.

    if (this.through) {
      deprecated('belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model';
    }

I inspected if my code does not send string as below:

    if (this.through) {
      deprecated('belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model' + require('util').inspect(this.through));
    }

**Comment by mickhansen** [comment]
You are right - and it was already fixed a few days ago in https://github.com/sequelize/sequelize/commit/52e381733571bd58d92e2f8c0fa85fe04d87ab1e :) 

Small blunder on my part.
