### ISSUE TITLE
Include doesn't no work with find(sequelize-2.0.0rc7)

### ISSUE THREAD

**Issue by pola88** [sequelize/sequelize#2914]
Hi guys,

I have a problem with the following code:

```
User.find( { where: { id: id } }, { include:  [Location ] });
```

If I remove the include option, it works properly, but If I use ```include``` , it doesn't work.
I tried using ```findAll``` instead of ```find``` and it works.
I don't get an error for this, the app is frozen and I have to force the close.

Did you remove the include for find?
Thanks,

**Comment by mickhansen** [comment]
You are putting the include parameter in the wrong place.
Should be `User.find( { where: { id: id },  include:  [Location ] });`

**Comment by pola88** [comment]
@mickhansen My mistake when I describe the issue, I am doing what you say.
I will try to create a test for this.

**Comment by mickhansen** [comment]
Are you sure you're not getting an error? Do you have a catch handler on it?
Is the SQL logged?
It should still work, there's a bunch for finds and includes.

**Comment by pola88** [comment]
@mickhansen I'm sorry....
My mistake, it's working now!:)

Thanks for your answer!
