### ISSUE TITLE
Adding a option 'length' to specify columnlength more specifically in model definition

### ISSUE THREAD

**Issue by SirUli** [sequelize/sequelize#292]
Hello,

i have an application where i am using sequelize to connect to the database. To optimize my database i have changed the columns in the database "a little", e.g. changed some colums from INT(11) to INT(4). Would it be possible to add an option "length" to the column-definition which would be used by databases which are able to use it and ignored by those who have a fixed length?

This could look like this (File for Import im sequelize.import):

``` javascript
module.exports = function(sequelize, DataTypes) {
    var Table = sequelize.define("mycooltable"
        , {
            id: {
                type: DataTypes.INTEGER
                , primaryKey: true
                , autoIncrement: true
            }
            , lfs:  {
                type: DataTypes.INTEGER
                , length: 4
            }
            , sid:          DataTypes.INTEGER
        }
        , {
            paranoid: false
            , timestamps: false
        }
    );

    return Table;
}
```

What do you think?

Best Regards,
Uli

Edit: Of course it would be even better to use an appropriate datatypes like "TINYINT" or "SMALLINT" and so on, but this then needs much more codework to be independent to the different databases.

**Comment by josser** [comment]
This will work for INT but not for CHAR. 
I know, to specify length for CHAR/VARCHAR I have to call them like a function: 
  isbn13: {
    type: DataTypes.CHAR(12),
    primaryKey: true,
  },
But this force me to go against coding standard. i.e airbnb has rule new-cap: 
A function with a name starting with an uppercase letter should only be used as a constructor
http://eslint.org/docs/rules/new-cap

**Comment by janmeier** [comment]
You can use `new` in data types (but its not required)

**Comment by felixfbecker** [comment]
@josser new-cap also has options you might be interested in:
> 
> "capIsNewExceptions" allows specified uppercase-started function names to be called without the new operator.
> "capIsNewExceptionPattern" allows any uppercase-started function names that match the specified regex pattern to be called without the new operator.

> "properties": false disables checks on object properties

**Comment by josser** [comment]
@felixfbecker that's true but I think we are using presets because don't want to manually invent set of rules. 
Anyway, using new is acceptable. 

Thank you, and sorry for bad English!
