### ISSUE TITLE
Seqeulize $not comparator broken. To also add support for $not: { $contains }.

### ISSUE THREAD

**Issue by calvintwr** [sequelize/sequelize#2923]
From: http://sequelize.readthedocs.org/en/latest/api/model/
The possible comparators for the where criterias: 

    gt, gte, lt, lte, ne, between/.., nbetween/notbetween/!.., in, not, like, nlike/notlike

There is a a "not" comparator but it when used it produces the sql:

    // sequelize where
    where: { someField: { not: true }} 

    // generated query
    "someField" NOT IN (true);

This doesn't allow fields that are NULL to be selected. Suppose the `NOT` comparater is used, it would pick up rows that have `someField` with `NULL` values.

In order to maintain BC, I propose `nt` as `NOT`. In order to avoid confusion, we should deprecated `not` and use `notIn`.

**Comment by mickhansen** [comment]
`ne` should do what you need in terms of `NOT NULL` and `!= true`

**Comment by calvintwr** [comment]
`!= true` cannot pick up NULL rows.

**Comment by mickhansen** [comment]
@calvintwr ah, was not aware, alright :)

**Comment by mickhansen** [comment]
> In order to maintain BC, I propose nt as NOT. In order to avoid confusion, we should deprecated not and use notIn.

Makes sense.

**Comment by mickhansen** [comment]
This could perhaps be fixed without breaking BC by just looking at whether or not the value passed to `not` is an array, should only use list logic for arrays really.

**Comment by mickhansen** [comment]
#2976

**Comment by calvintwr** [comment]
ahh that's a great idea....

**Comment by calvintwr** [comment]
`AND "post"."softDeleted" NOT true` is causing errors.

I believe it should be `IS NOT true`?

**Comment by calvintwr** [comment]
I think there is more to it. The implementation logic should be:

1) Is `not` an array?
2) If `not` is not array, check if it is boolean or null types.
3) If boolean or null types, operator is 'IS NOT'
4) If not boolean or null types, proceed to parse it as a tuple.

**Comment by mickhansen** [comment]
@calvintwr yeah there's a case or two missing it seems.
PR welcome, it's rather easy to push a test and a fix with the new sql unit tests :)

**Comment by calvintwr** [comment]
I will when I can. Some hints on where I should be looking?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/test/unit/sql/where.test.js#L120

**Comment by mickhansen** [comment]
Hmm we actually have a test for `$not: true`: https://github.com/sequelize/sequelize/blob/master/test/unit/sql/where.test.js#L124

Not sure why i thought why that was correct, must've read it somewhere.

**Comment by calvintwr** [comment]
Thanks man I'll check it out real soon.

**Comment by calvintwr** [comment]
@mickhansen 
I just went through the various sql documentation.

mysql apparently uses the `NOT` operator without `IS`, like `SELECT NOT 10`. I would assume mariaDB does the same.

I can't find anything for sqlite.

Postgres definitely can't use the `NOT` operator like MySQL does it.

Question being... I just checked travis, why does the test pass? I have no experience in unit testing.

**Comment by calvintwr** [comment]
I'm just thinking, if you are passing values that are not boolean or null type to `$not`, it should go to `$ne` instead. 

Can you confirm my changes are good? If yes I will go on to make the changes to the unit tests.
https://github.com/calvintwr/sequelize/commit/4eca34759f00b10615fe41f9f0b066c5fadc0b35

**Comment by mickhansen** [comment]
@calvintwr Well it's a unit test, so it doesn't hit the database so we don't get an error, but there's an error in the unit test for postgres obviously then :)

I don't think that non boolean or null should go to $ne when explicitely using $not since $not has different NULL semantics.

**Comment by calvintwr** [comment]
@mickhansen I just tried the following queries on MySQL and Postgres. They are not working:

`SELECT * FROM [table] WHERE [value] NOT TRUE`
`SELECT * FROM [table] WHERE [value] NOT 1`
`SELECT * FROM [table] WHERE [value] IS NOT 1`

The first query confirms that `NOT` when used alone as a comparator must be used with `IS`, like in `IS NOT'.

The second query confirms that non boolean and non-null values cannot be used with `IS NOT` or `NOT` (in `NOT`, most likely its the syntax error that is overriding.).

If that is true that indeed we should pass $not to $ne. In fact, it would be incorrect to use $not for non-bool, non-null values.

**Comment by mickhansen** [comment]
http://www.postgresql.org/docs/9.1/static/functions-comparison.html hmm yeah seems like postgres only supports the NOT construct for boolean and null types.

MySQL doesn't have boolean types so we should only support NULL in that case.

**Comment by calvintwr** [comment]
alright so... i guess the safest option is to pass $not to $ne when it is of the "unsupported" types, depending on dialect?

or would you prefer to throw an exception? 

also, the documentation..... shows that you are able to do `$not: 3`. can i change it to boolean/null?
http://sequelize.readthedocs.org/en/latest/docs/models/#findall-search-for-multiple-elements-in-the-database

**Comment by mickhansen** [comment]
`$not` also still might be usefull for nested `$not: {$any: []}`

**Comment by calvintwr** [comment]
i didn't know about `$any`. where is the documentation for it so that I can read?

**Comment by mickhansen** [comment]
Not sure there is any other than the unit tests :D
But yeah we definitely need to redirect to $ne for strings and integers i suppose.

**Comment by calvintwr** [comment]
https://github.com/sequelize/sequelize/pull/3271

We should leave `$not: { $any: {}}` out of this. Make a `$notAny` like how `$notIn` and `$notBetween`.

My opinion is that `$not` is a comparator here. Using it like `$not:{ $any: {}}` confuses me because it becomes a logical operator. It will open cans of worms of people who will use if for `$not: { [a very very long condition but I want to NOT it. ]}`, which I think can always be written in less confusing ways.

**Comment by calvintwr** [comment]
oh btw, `IS NOT [boolean_value]` is available for MySQL. so there wasn't a need to add to the default.

http://dev.mysql.com/doc/refman/5.0/en/comparison-operators.html#operator_is-not

**Comment by mickhansen** [comment]
@calvintwr i disagree, in some cases `$not: {$any}` makes a lot more sense than `$notAny` to me, generally i favor nesting over overly dense operators.

**Comment by calvintwr** [comment]
alright. while we let this discussion run a bit more, shall we merge the current PR which fixes some of the use cases?

**Comment by mickhansen** [comment]
Haven't had time to review it properly yet.

**Comment by calvintwr** [comment]
https://github.com/sequelize/sequelize/pull/3271

**Comment by calvintwr** [comment]
shouldn't we leave this open for `$not: {any}`?

**Comment by mickhansen** [comment]
Ah right @calvintwr

**Comment by calvintwr** [comment]
There doesn't seem to be any difference between:

    WHERE NOT ANY ( [value] ANY([arrayField])

vs

    WHERE NOT [arrayField] @> '{[arrayOfValues]}'

Can we confirm this?

If that is the case I should write only for {$not : { $contains } }

**Comment by calvintwr** [comment]
@mickhansen btw, I'm get mind-blocked. Whats the purpose of $contained `<@`

**Comment by mickhansen** [comment]
@calvintwr VALUES performs differently than ARRAY in a few cases (https://www.datadoghq.com/2013/08/100x-faster-postgres-performance-by-changing-1-line/)

$contained: http://www.postgresql.org/docs/9.1/static/functions-array.html

**Comment by calvintwr** [comment]
where is the $contains query being generated. Its not in query-generator.js. Can't find it.

**Comment by calvintwr** [comment]
I gather the following conclusion:

1) No use case for `ANY(ARRAY[])`. `$any: [array]` should just output `ANY(VALUES())`. I think this is being done.

2) No use case for `arrayField: {$any: [array]}`. In fact I might be correct to say that's wrong syntax, cause ANY can only be used to check a single value against an array field.

3) Hence `$not: {$any}` is just $notIn.

Curious question: why do we have $notIn, $notLike etc, but you want $not: {$any} instead of $notAny.

4) Lastly we need to write the support for $notCotains and possibly $notContained

**Comment by mickhansen** [comment]
@calvintwr $contains is not tested but works as a simple comparator.

There is a difference between `$not: $any: $values` and `$notIn`. `NOT IN` will use a different matcher and can be a different performance implementation.

`$notContains` is not really a postgres construct though, that would be a NOT negator + contains.

**Comment by mickhansen** [comment]
I believe you are right about 2), no reason to use an array attribute in an ANY expression (that would be for comparing a single-value attribute to an array input).

**Comment by calvintwr** [comment]
https://github.com/sequelize/sequelize/pull/3351

Generally it will at `NOT` operator in front of the generated query string.

It is definitely subjected to limitations of what the comparators can do. I.e. meaning `$not: [ {$contains: [value] } ]` will definitely not pick up `NULL` fields... as per our initial reason why we needed the $not boolean/null fix.

Also I don't think nested `$not`'s can be supported. And I don't think we should support it anyway.

**Comment by calvintwr** [comment]
merged https://github.com/sequelize/sequelize/issues/2923 and closed.

**Comment by calvintwr** [comment]
oh wait the doc....

**Comment by calvintwr** [comment]
https://github.com/sequelize/sequelize/pull/3380

**Comment by calvintwr** [comment]
docs pr: https://github.com/sequelize/sequelize/pull/3380#issuecomment-83939827
