### ISSUE TITLE
Migrations vs define model names

### ISSUE THREAD

**Issue by nathasm** [sequelize/sequelize#2924]
From reading the documents and issues on Github, it appears that a typical development life-cycle is to use `sequelize.define('Model', function() { ... });` and then move to migrations for production.

The problem that I am noticing is that when I use `define` for `Model` it converts it to `Models` in the database, but to reference it, I use the non-plural form: `sequelize.models.Model`;

However, when I move over to migrations, I must make sure to create a pluralized form of the model, set the modelName to the non-pluralized form, and make sure to define the ID/created_at/updated_at columns myself.

Does this sound right? There was little documentation describing the differences between going from `define` to `createTable` and want to make sure there weren't any other differences that I might have missed.

To make this an actual Issue, I like to suggest making this more clear in the documentation.

**Comment by mickhansen** [comment]
Sequelize by default pluralizes table names from the model name, it can be turned off with `freezeTableName: true`.

It's not a default i'm happy with but it's one that's hard to change without affecting a lot of users.
