### ISSUE TITLE
Where condition puts AND after LEFT JOIN

### ISSUE THREAD

**Issue by ErikvdVen** [sequelize/sequelize#2930]
I need a WHERE condition at the end of my query to get the right results from the database but I can't get it done. The strange part is, if I add a "where" condition to the json query, sequelize places this condition with an AND after a LEFT JOIN (see json below), which returns different (and the wrong) results, in contrast to a SQL query with the WHERE condition at the end (after a WHERE keyword). See below.

This query:

```
query = {
                    offset: offset,
                    limit: limit,
                    order: [
                        ['id', 'DESC']
                    ],

                    attributes: ['id', 'name', 'supplier_id', 'created_at', 'url'],
                    include: [
                        models.image,
                        models.supplier, {
                            model: models.offer,
                            attributes: ['valid_to', 'id', 'price', 'price_old']
                        }, {
                            required: false,

                            where: ['"termTaxonomies.termRelationships"."product_id" is NULL'],
                            model: models.termTaxonomies,
                            include: [{
                                model: models.term
                            }, {
                                required: false,
                                model: models.taxonomy,
                                attributes: ['id']
                            }],

                        }
                    ],
                };
```

creates this SQL (returns 70 rows):

```
SELECT "product".*
    ,"images"."id" AS "images.id"
    ,"images"."deal_id" AS "images.deal_id"
    ,"images"."image" AS "images.image"
    ,"supplier"."id" AS "supplier.id"
    ,"supplier"."name" AS "supplier.name"
    ,"supplier"."url" AS "supplier.url"
    ,"supplier"."logo" AS "supplier.logo"
    ,"supplier"."clicks" AS "supplier.clicks"
    ,"supplier"."order" AS "supplier.order"
    ,"offers"."valid_to" AS "offers.valid_to"
    ,"offers"."id" AS "offers.id"
    ,"offers"."price" AS "offers.price"
    ,"offers"."price_old" AS "offers.price_old"
    ,"termTaxonomies"."id" AS "termTaxonomies.id"
    ,"termTaxonomies"."taxonomy_id" AS "termTaxonomies.taxonomy_id"
    ,"termTaxonomies"."term_id" AS "termTaxonomies.term_id"
    ,"termTaxonomies"."parentId" AS "termTaxonomies.parentId"
    ,"termTaxonomies"."hierarchyLevel" AS "termTaxonomies.hierarchyLevel"
    ,"termTaxonomies"."distance" AS "termTaxonomies.distance"
    ,"termTaxonomies.termRelationships"."product_id" AS "termTaxonomies.termRelationships.product_id"
    ,"termTaxonomies.termRelationships"."term_taxonomy_id" AS "termTaxonomies.termRelationships.term_taxonomy_id"
    ,"termTaxonomies.termRelationships"."verified" AS "termTaxonomies.termRelationships.verified"
    ,"termTaxonomies.term"."id" AS "termTaxonomies.term.id"
    ,"termTaxonomies.term"."name" AS "termTaxonomies.term.name"
    ,"termTaxonomies.term"."plural" AS "termTaxonomies.term.plural"
    ,"termTaxonomies.term"."sin_article" AS "termTaxonomies.term.sin_article"
    ,"termTaxonomies.term"."plu_article" AS "termTaxonomies.term.plu_article"
    ,"termTaxonomies.taxonomy"."id" AS "termTaxonomies.taxonomy.id"
FROM (
    SELECT "product"."id"
        ,"product"."name"
        ,"product"."supplier_id"
        ,"product"."created_at"
        ,"product"."url"
    FROM "products" AS "product"
    ORDER BY "product"."id" DESC LIMIT 10
    ) AS "product"
LEFT JOIN "images" AS "images" ON "product"."id" = "images"."deal_id"
LEFT JOIN "suppliers" AS "supplier" ON "product"."supplier_id" = "supplier"."id"
LEFT JOIN "offers" AS "offers" ON "product"."id" = "offers"."product_id"
LEFT JOIN (
    "term_relationships" AS "termTaxonomies.termRelationships" LEFT JOIN "term_taxonomies" AS "termTaxonomies" ON "termTaxonomies"."id" = "termTaxonomies.termRelationships"."term_taxonomy_id"
    ) ON "product"."id" = "termTaxonomies.termRelationships"."product_id"
    AND "termTaxonomies.termRelationships"."product_id" IS NULL -- this is wrong
LEFT JOIN "terms" AS "termTaxonomies.term" ON "termTaxonomies"."term_id" = "termTaxonomies.term"."id"
LEFT JOIN "taxonomies" AS "termTaxonomies.taxonomy" ON "termTaxonomies"."taxonomy_id" = "termTaxonomies.taxonomy"."id"
ORDER BY "product"."id" DESC
```

Check the 4th line from below, in above mentioned query.

But I need this query to get it work (returns 63 rows, check the 2nd line from below, in below mentioned query.):

```
SELECT "product".*
    ,"images"."id" AS "images.id"
    ,"images"."deal_id" AS "images.deal_id"
    ,"images"."image" AS "images.image"
    ,"supplier"."id" AS "supplier.id"
    ,"supplier"."name" AS "supplier.name"
    ,"supplier"."url" AS "supplier.url"
    ,"supplier"."logo" AS "supplier.logo"
    ,"supplier"."clicks" AS "supplier.clicks"
    ,"supplier"."order" AS "supplier.order"
    ,"offers"."valid_to" AS "offers.valid_to"
    ,"offers"."id" AS "offers.id"
    ,"offers"."price" AS "offers.price"
    ,"offers"."price_old" AS "offers.price_old"
    ,"termTaxonomies"."id" AS "termTaxonomies.id"
    ,"termTaxonomies"."taxonomy_id" AS "termTaxonomies.taxonomy_id"
    ,"termTaxonomies"."term_id" AS "termTaxonomies.term_id"
    ,"termTaxonomies"."parentId" AS "termTaxonomies.parentId"
    ,"termTaxonomies"."hierarchyLevel" AS "termTaxonomies.hierarchyLevel"
    ,"termTaxonomies"."distance" AS "termTaxonomies.distance"
    ,"termTaxonomies.termRelationships"."product_id" AS "termTaxonomies.termRelationships.product_id"
    ,"termTaxonomies.termRelationships"."term_taxonomy_id" AS "termTaxonomies.termRelationships.term_taxonomy_id"
    ,"termTaxonomies.termRelationships"."verified" AS "termTaxonomies.termRelationships.verified"
    ,"termTaxonomies.term"."id" AS "termTaxonomies.term.id"
    ,"termTaxonomies.term"."name" AS "termTaxonomies.term.name"
    ,"termTaxonomies.term"."plural" AS "termTaxonomies.term.plural"
    ,"termTaxonomies.term"."sin_article" AS "termTaxonomies.term.sin_article"
    ,"termTaxonomies.term"."plu_article" AS "termTaxonomies.term.plu_article"
    ,"termTaxonomies.taxonomy"."id" AS "termTaxonomies.taxonomy.id"
FROM (
    SELECT "product"."id"
        ,"product"."name"
        ,"product"."supplier_id"
        ,"product"."created_at"
        ,"product"."url"
    FROM "products" AS "product"
    ORDER BY "product"."id" DESC LIMIT 10
    ) AS "product"
LEFT JOIN "images" AS "images" ON "product"."id" = "images"."deal_id"
LEFT JOIN "suppliers" AS "supplier" ON "product"."supplier_id" = "supplier"."id"
LEFT JOIN "offers" AS "offers" ON "product"."id" = "offers"."product_id"
LEFT JOIN (
    "term_relationships" AS "termTaxonomies.termRelationships" LEFT JOIN "term_taxonomies" AS "termTaxonomies" ON "termTaxonomies"."id" = "termTaxonomies.termRelationships"."term_taxonomy_id"
    ) ON "product"."id" = "termTaxonomies.termRelationships"."product_id"

LEFT JOIN "terms" AS "termTaxonomies.term" ON "termTaxonomies"."term_id" = "termTaxonomies.term"."id"
LEFT JOIN "taxonomies" AS "termTaxonomies.taxonomy" ON "termTaxonomies"."taxonomy_id" = "termTaxonomies.taxonomy"."id"
WHERE "termTaxonomies.termRelationships"."product_id" IS NULL -- this is good
ORDER BY "product"."id" DESC
```

**Comment by mickhansen** [comment]
`include.where` scopes the join, so using `AND` on the join is correct (joins support multiple ON conditions).
`where: ['"termTaxonomies.termRelationships"."product_id" is NULL'],` on an `include` is not exactly supported syntax, you should move it to the general find where.

**Comment by mickhansen** [comment]
Or create a proper `{where: {product_id: null}}` on the `termRelationships` include instead.

**Comment by ErikvdVen** [comment]
move where: ```['"termTaxonomies.termRelationships"."product_id" is NULL']``` to the general find where is not an option, because then it adds the row to the query inside the FROM(). And then I got an error it can't find the table termRelationships.

And we don't include the termRelationships inside the json query, because it's a join table, so changing the current where with ```{where: {product_id: null}}``` adds the condition on the termTaxonomies table...

Guess the only option is to include termRelationships manually as well, anyway?

**Comment by mickhansen** [comment]
@ErikvdVen Have you tried adding the where to the correct include/join table?

**Comment by ErikvdVen** [comment]
Like I said, we suppose to add the where condition to the termRelationships include, but because it's a join table we cannot include termRelationships. If we try to include it, sequelize gives us an error.

**Comment by mickhansen** [comment]
@ErikvdVen you are not giving me a lot to work with, did you try `through: {where: {}}` or have you tried setting up a relation to the join table and including that?

**Comment by ErikvdVen** [comment]
Sorry,
Uhm I did tried this:
```
query = {
                    offset: offset,
                    limit: limit,
                    order: [
                        ['id', 'DESC']
                    ],

                    attributes: ['id', 'name', 'supplier_id', 'created_at', 'url'],
                    include: [
                        models.image,
                        models.supplier, {
                            model: models.offer,
                            attributes: ['valid_to', 'id', 'price', 'price_old']
                        }, {
                            required: false,
                            model: models.termTaxonomies,
                            include: [{
                                model: models.term
                            }, {
                                required: false,
                                model: models.taxonomy,
                                attributes: ['id'],
                                where:{
                                    id: 1
                                },
                            }],

                        }
                    ]
                };

                query.include.through = {
                    where: { product_id: null }
                };```

But it gave the same result, an AND statement after the JOIN. The same query as the first example in my first post.


And this did changed the query big time, but I had to unset the limit because of a SQL error:
```
query = {
                    offset: offset,
                    //limit: limit,
                    order: [
                        ['id', 'DESC']
                    ],

                    attributes: ['id', 'name', 'supplier_id', 'created_at', 'url'],
                    include: [
                        models.image,
                        models.supplier, {
                            model: models.offer,
                            attributes: ['valid_to', 'id', 'price', 'price_old']
                        }, {
                            required: false,
                            model: models.termTaxonomies,
                            through : {
                                where: { product_id: null }
                            },
                            include: [{
                                model: models.term
                            }, {
                                required: false,
                                model: models.taxonomy,
                                attributes: ['id'],
                                where:{
                                    id: 1
                                },
                            }],

                        }
                    ]
                };
```
With this json I got this SQL:
```
SELECT "product"."id"
	,"product"."name"
	,"product"."subtitle"
	,"product"."url"
	,"product"."prod_specs"
	,"product"."prod_desc"
	,"product"."supplier_id"
	,"product"."created_at"
	,"product"."updated_at"
	,"product"."active"
	,"images"."id" AS "images.id"
	,"images"."deal_id" AS "images.deal_id"
	,"images"."image" AS "images.image"
	,"supplier"."id" AS "supplier.id"
	,"supplier"."name" AS "supplier.name"
	,"supplier"."url" AS "supplier.url"
	,"supplier"."logo" AS "supplier.logo"
	,"supplier"."clicks" AS "supplier.clicks"
	,"supplier"."order" AS "supplier.order"
	,"offers"."id" AS "offers.id"
	,"offers"."product_id" AS "offers.product_id"
	,"offers"."price_old" AS "offers.price_old"
	,"offers"."price" AS "offers.price"
	,"offers"."price_alt" AS "offers.price_alt"
	,"offers"."valid_from" AS "offers.valid_from"
	,"offers"."valid_to" AS "offers.valid_to"
	,"offers"."created_at" AS "offers.created_at"
	,"offers"."updated_at" AS "offers.updated_at"
	,"offers"."sold_out" AS "offers.sold_out"
	,"termTaxonomies"."id" AS "termTaxonomies.id"
	,"termTaxonomies"."taxonomy_id" AS "termTaxonomies.taxonomy_id"
	,"termTaxonomies"."term_id" AS "termTaxonomies.term_id"
	,"termTaxonomies"."parentId" AS "termTaxonomies.parentId"
	,"termTaxonomies"."hierarchyLevel" AS "termTaxonomies.hierarchyLevel"
	,"termTaxonomies"."distance" AS "termTaxonomies.distance"
	,"termTaxonomies.termRelationships"."product_id" AS "termTaxonomies.termRelationships.product_id"
	,"termTaxonomies.termRelationships"."term_taxonomy_id" AS "termTaxonomies.termRelationships.term_taxonomy_id"
	,"termTaxonomies.termRelationships"."verified" AS "termTaxonomies.termRelationships.verified"
	,"termTaxonomies.term"."id" AS "termTaxonomies.term.id"
	,"termTaxonomies.term"."name" AS "termTaxonomies.term.name"
	,"termTaxonomies.term"."plural" AS "termTaxonomies.term.plural"
	,"termTaxonomies.term"."sin_article" AS "termTaxonomies.term.sin_article"
	,"termTaxonomies.term"."plu_article" AS "termTaxonomies.term.plu_article"
	,"termTaxonomies.taxonomy"."id" AS "termTaxonomies.taxonomy.id"
	,"termTaxonomies.taxonomy"."taxonomy" AS "termTaxonomies.taxonomy.taxonomy"
	,"termTaxonomies.taxonomy"."description" AS "termTaxonomies.taxonomy.description"
FROM "products" AS "product"
LEFT JOIN "images" AS "images" ON "product"."id" = "images"."deal_id"
LEFT JOIN "suppliers" AS "supplier" ON "product"."supplier_id" = "supplier"."id"
INNER JOIN "offers" AS "offers" ON "product"."id" = "offers"."product_id"
	AND 1 = 1
LEFT JOIN (
	"term_relationships" AS "termTaxonomies.termRelationships" LEFT JOIN "term_taxonomies" AS "termTaxonomies" ON "termTaxonomies"."id" = "termTaxonomies.termRelationships"."term_taxonomy_id"
	) ON "product"."id" = "termTaxonomies.termRelationships"."product_id"
LEFT JOIN "terms" AS "termTaxonomies.term" ON "termTaxonomies"."term_id" = "termTaxonomies.term"."id"
LEFT JOIN "taxonomies" AS "termTaxonomies.taxonomy" ON "termTaxonomies"."taxonomy_id" = "termTaxonomies.taxonomy"."id"
ORDER BY "product"."id" DESC;
```

**Comment by mickhansen** [comment]
2nd way is the way i meant, add it to the relevant include object, not the overall include array :)
What was the error?

**Comment by mickhansen** [comment]
Doesn't look like it actually added the product_id: null query, but hard to tell with all that text.
Can you reproduce the issue in a smaller piece of code? (`through: {where: {}}` should work).

**Comment by ErikvdVen** [comment]
Nope, through doesn't seem to work. ```TypeError: Cannot set property 'limit' of undefined at Object.methods.all ``` is the error we received after setting a limit on below json (I decreased the amount of includes so the SQL query becomes smaller and easier to read, like you asked ;)):
```
query = {
                    offset: offset,
                    limit: limit,
                    order: [
                        ['id', 'DESC']
                    ],

                    attributes: ['id', 'name', 'supplier_id', 'created_at', 'url'],
                    include: [
                        {
                            required: false,
                            model: models.termTaxonomies,
                            through : {
                                where: ['"termTaxonomies.termRelationships"."verified" IS NULL']
                            }
                        }
                    ]
                };
```

But it still creates a very big query, so I removed all columns in the first select from the below query (not that important anyway) and replaced it with some dots:
```
SELECT ...........
FROM "products" AS "product"
LEFT JOIN "images" AS "images" ON "product"."id" = "images"."deal_id"
LEFT JOIN "suppliers" AS "supplier" ON "product"."supplier_id" = "supplier"."id"
INNER JOIN "offers" AS "offers" ON "product"."id" = "offers"."product_id"
	AND 1 = 1
LEFT JOIN (
	"term_relationships" AS "termTaxonomies.termRelationships" LEFT JOIN "term_taxonomies" AS "termTaxonomies" ON "termTaxonomies"."id" = "termTaxonomies.termRelationships"."term_taxonomy_id"
	) ON "product"."id" = "termTaxonomies.termRelationships"."product_id"
LEFT JOIN "terms" AS "termTaxonomies.term" ON "termTaxonomies"."term_id" = "termTaxonomies.term"."id"
LEFT JOIN "taxonomies" AS "termTaxonomies.taxonomy" ON "termTaxonomies"."taxonomy_id" = "termTaxonomies.taxonomy"."id"
ORDER BY "product"."id" DESC
```
The version we're using: 2.0.0-rc7

**Comment by mickhansen** [comment]
Your query looks weird, the nested join should be an INNER i think.
Looks like there's a bug in your case.

**Comment by ErikvdVen** [comment]
I think it's also quite weird it adds an AND 1=1 after the INNER JOIN instead of WHERE 1=1 at the end of the query (before ORDER) followed by the where condition I added.

**Comment by mickhansen** [comment]
`1=1` usually occurs when you have an empty `where` object.

**Comment by mickhansen** [comment]
@ErikvdVen ill take a look at this as soon as possible, if you want to help out please open a PR with a comprehensive/complex unit test (as close to your original case as possible) with data and the works.

**Comment by ErikvdVen** [comment]
> 1=1 usually occurs when you have an empty where object.
I know ;) That's the reason I thought it's strange it contains ```AND 1=1``` instead of ```WHERE 1=1```
> ill take a look at this as soon as possible, 
Thanks!
> if you want to help out please open a PR with a comprehensive/complex unit test (as close to your original case as possible) with data and the works.
I'll take a look at the code! Don't know I'm really able to help, because I'm not that familiar with the source code, but I'll try ;)

**Comment by mickhansen** [comment]
@ErikvdVen you don't need to know the source code, you just need to provide me with a failing test case, that helps us out more than you know :)

**Comment by mickhansen** [comment]
like this: https://github.com/sequelize/sequelize/blob/master/test/include/findAll.test.js#L2082

**Comment by ErikvdVen** [comment]
Ooow okay. I'll take a look at it!

**Comment by ErikvdVen** [comment]
Tried my best to create a test and created a pull request.

**Comment by micksatana** [comment]
When using this condition, i'll get AND condition instead of OR
```
include: [{
    model: MyModel
    required: false,
    where: {
        $or: [ { myKey: null } ]
    }
}]
```

Expectation:
`LEFT JOIN MyModel ON myId = 1 OR myKey IS NULL`

Wrong result:
`LEFT JOIN MyModel ON myId = 1 AND (myKey IS NULL)`

My understanding is current code always appends AND before the include[].where
Anyhow I can workaround?

**Comment by aprilmintacpineda** [comment]
see my comment @ https://github.com/sequelize/sequelize/issues/3095#issuecomment-367907718
