### ISSUE TITLE
Refactor hooks and use stack-queue instead

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2932]
This is a proposal to refactor hooks to use [stack-queue](https://github.com/findhit/stack-queue) as hooks run engine.

**Comment by mickhansen** [comment]
You haven't really included in any arguments in your proposal :)

**Comment by cusspvz** [comment]
Sorry.

**stack-queue** code came public from the our internal repos, while refactoring our router to **emvici-router**.

It was initially created to hold queue stacks such the ones you see at **express** and **connect** middleware handlers.

This proposal pretends to:
* Discard [hookTypes](https://github.com/sequelize/sequelize/blob/master/lib/hooks.js#L38-L61) - Currently all Constructors that are hookable have all hooks on it, i would remove `hookTypes` and create a generator that would create generate hook methods for each Constructor, something like: `Hooks.bind( Constructor /* Ex: Model */, [ 'find', 'bulkFind' /*, ... Aliased hooks could be provided with another array Ex: [ 'destroy', 'delete' ]*/])`
* IMHO is bad to save and use hooks directly from options, so i would propose to define a `_hooks` object, not enumerable and not writable which would contain a stack for each hook, and aliased stacks could be binded easily within `.bind`.
* **stack-queue** provides a method for dispatching arguments on stack called `stack.dispatch( arg1, arg2 ), with that we won't need to enumerate params and check if we should transport a callback or not, it does it already.`

Advantages:
* We are using it on `emvici-router` and it has better [performance](https://cloud.githubusercontent.com/assets/3604053/5664543/f96dc382-9748-11e4-8458-9c860f5e2fe7.png) than `express.Router`.
* **stack-queue** is already able to short-circuit/break the stack flow.
* **stack-queue** works on top of promises (bluebird) also.

**Comment by cusspvz** [comment]
I would like to know also the opinion of @overlookmotel @janmeier @RichAyotte @mlegenhausen

**Comment by mickhansen** [comment]
Is it backwards compatible with our codebase?
How does it short-circuit the stack flow?

**Comment by cusspvz** [comment]
> Is it backwards compatible with our codebase?

Yes, implementation should be easy.

> How does it short-circuit the stack flow?

It breaks stack queue execution on all errors and rejects the returned promise.
By default, it also breaks on `strings` but we could optionally give a method to decide when it should break (I was working on that minutes ago, coincidence!!).

Example - break on arrays:
```js

var Stack = require( 'stack-queue' );

var stack = new Stack({
  breakOn: function ( value ) {
    return value instanceof Array;
  },
});

stack.queue([
  function ( options ) { return 'a'; },
  function ( options ) { return []; },
  function ( options ) { throw new Error(); },
]);

stack.dispatch( {} ); // Should return a promise which will be resolved with `[]` from the second queue method.

```

**Comment by cusspvz** [comment]
@mickhansen I'm currently trying to complete the proposal PR.
Just to mention that `.hook` | `.addHook` will also accept an array of functions, since `stack.queue` deeps into arrays / arguments.

**Comment by sushantdhiman** [comment]
Looking at [_Stack Queue_](https://github.com/findhit/stack-queue) after about 1 year, It doesn't seems to be very active.

Is it worth to invest on such option @mickhansen @janmeier ? Keeping in mind we might run into issues that are actually dependent on stack-queue and may not be solved fast enough.

**Comment by mickhansen** [comment]
No, let's close - Current hooks work just fine.
