### ISSUE TITLE
Default username and password when db connection string is passed

### ISSUE THREAD

**Issue by ksmithut** [sequelize/sequelize#2935]
I am attempting to connect to a postgres database with no username and password, and pass in options

```javascript
var sequelize = new Sequelize('postgres://127.0.0.1/db', {
  logging: console.log
});
```

It throws an error `Argument must be a string` because it's using the options object as the username.

I expect it to use the defaults `null` and `null` for username and password respectively. 

I'm using version 2.0.0-rc7 of sequelize.

I believe the issue is somewhere around [here](https://github.com/sequelize/sequelize/blob/cdd8c3be7961c58c1446cb4893939a2986db9876/lib/sequelize.js#L120-L123)

```javascript
if (urlParts.auth) {
  username = urlParts.auth.split(':')[0];
  password = urlParts.auth.split(':')[1];
}
```

If before that, you were to set `username` and `password` to `null`, then it should default to null username and password.

I'm happy to work in a PR with tests if needed.

**Comment by mickhansen** [comment]
@ksmithut What's the difference between `null` and `undefined` in this case?
A PR is always welcome - Tests might be hard in this instance but also very welcome.

**Comment by ksmithut** [comment]
@mickhansen not really too much of a difference, the problem is that because `username` is the second parameter, and gets carried over to the configuration.

I forgot to mention that it was throwing an error `Argument must be a string` because it's trying to pass the username as the options object that gets passed through. I'll update the issue with the error that was thrown.

**Comment by ksmithut** [comment]
@mickhansen I've created a PR (#2938) that adds a test case and a fix. Pretty easy fix. The build should finish up here pretty soon, but looks like everything is passing.

**Comment by mickhansen** [comment]
Merged, thank you @ksmithut

**Comment by ksmithut** [comment]
@mickhansen Thank you! That was very quick and painless. I appreciate your attention to the issue.
