### ISSUE TITLE
One-to-many doesn't give functionality on the childObjects

### ISSUE THREAD

**Issue by saelfaer** [sequelize/sequelize#2940]
trying something like this

```
var User = sequelize.define('user', {...}, {});
var Asset = sequelize.define('asset', {...}, {});
```

Adding `User.hasMany(Asset);` gives the User many extra methods like `.addAsset`, `.removeAsset` ...
but I also want the other way around,  `asset.addOwner` or alike...

so i try to add: `Asset.belongsTo(User);`
however this does not give me `.addUser`.... 

so I tried more specific `Asset.belongsTo(User, { as: 'owner' });`
however still no `.addOwner`.... 

how should I add a ONE-TO-MANY where both sides can manipulate the others?
or is this simply not possible and thus a featurerequest?

**Comment by janmeier** [comment]
Since each asset has one user, the method is called 'setUser'

**Comment by saelfaer** [comment]
Of course, `add` and `remove` are for many relations. If there is only one you have to `set` it.
thanks for clearing that up. nothing wrong in sequelize, just my knowledge of it.
