### ISSUE TITLE
Consider smaller key length in SequelIzeMeta

### ISSUE THREAD

**Issue by Willyham** [sequelize/sequelize#2941]
InnoDB databases with a 'utf8mb4' charset are unable to run migrations as the key for 'SequelizeMeta' is a VARCHAR(255). This takes 1020 bytes and the max is 767.

Is it possible to allow the user to override the charset in 'findOrCreateSequelizeMetaDAO' so we can force the charset of this table to be utf8, regardless of database defaults?

**Comment by mickhansen** [comment]
@sdepold will be the guy to ask about this.

Generally the migration logic in Sequelize core is deprecated in favor of https://github.com/sequelize/umzug

**Comment by sdepold** [comment]
So this is line that causes the trouble as far as I can see? https://github.com/sequelize/umzug/blob/master/lib/storages/sequelize.js#L62

**Comment by Willyham** [comment]
Yeah, I believe that is the case. Let me open a PR against umzug. Is umzug in a production ready state? Is there anything still in Sequelize which is stopping it from being removed? I couldn't find a reference to umzug anywhere in the Sequelize docs.

**Comment by sdepold** [comment]
migration logic is only kept for bc reasons.

**Comment by sdepold** [comment]
also: here is a summary of how things are combined: https://github.com/sequelize/cli/issues/75#issuecomment-68154955
