### ISSUE TITLE
belongsToMany always creates deprecated warning

### ISSUE THREAD

**Issue by Pasukaru** [sequelize/sequelize#2942]
**Used dialect:** mysql
**Used sequelize version:** 2.0.0.rc7

**What I did:** 

Create a manyToMany relationship like so:

    module.exports = function(sequelize, DataTypes){
		var ModelA = sequelize.define('ModelA', {
			name: {type: DataTypes.STRING, allowNull: false}
		},{
	        underscored: true,
	        timestamps: true,
	        classMethods: {
	            associate: function(models){
	                ModelA.belongsToMany(models.Dataset, {
	                    through: 'ModelA',
	                    foreignKey: 'ModelA_id',
	                    otherKey: 'ModelB_id',
	                    constraints: true,
	                    onDelete: 'restrict',
	                    onUpdate: 'restrict'
	                });
	            }
	        }
	    });
		return ModelA;
    };

ModelB, for reference:

	module.exports = function(sequelize, DataTypes){
		var ModelB = sequelize.define('ModelB', {
			name: {type: DataTypes.STRING, allowNull: false}
		});
		return ModelB;
	};

**What I expect:**
It should not print the deprecated warning, since 'through' was provided a string.

**What actually happened:**
Deprecated warning is print to the console: 
"*belongsToMany: not defining through or defining through as true has been deprecated, please provide a string or a model*"

**Note**
In my tests, no matter what I pass as through, the deprecation warning is always displayed when using belongsToMany. Except when passing *null*, which results in an error.
Also, it does not matter if any of the other options is passed or not (foreignKey, otherKey, contraints, etc)

**Comment by mickhansen** [comment]
This is already fixed, was a typo on my part - Will be fixed in next release (and already fixed on master).

**Comment by chuks** [comment]
Still seeing this warning.
