### ISSUE TITLE
Document `indexes` option in model

### ISSUE THREAD

**Issue by jfinkhaeuser** [sequelize/sequelize#2944]
This should be possible:

```javascript
some_field: {
  type: DataTypes.STRING,
  unique: [ 'constraint1', 'constraint2'],
}
```

Because this is possible:
```sql
ALTER TABLE foo ADD CONSTRAINT `constraint1` UNIQUE(`some_field`, ...);
ALTER TABLE foo ADD CONSTRAINT `constraint2` UNIQUE(`some_field`, ...);
```

The same logic applies to all kinds of constraints, except primary keys. There was an issue about non-PK, non-unique indexes supported (can't find it now), which probably wants the same treatment.

As an observation, I find the whole in-line declaration of multi column constraints non-intuitive to read. So (alternatively) constraints outside of the field declarations make more sense to me.

_edit by janmeier:_ Remember to also document that you can use sequelize.fn etc in the index

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/2057

**Comment by janmeier** [comment]
Already possible, but needs documentation :)

**Comment by jfinkhaeuser** [comment]
Please note that constraints and indexes are two different things. That is, the following two statements yield different results:

```SQL
ALTER TABLE foo ADD CONSTRAINT `constraint1` UNIQUE(`some_field`, ...);
ALTER TABLE foo ADD INDEX `index1` (`some_field`, ...);
```

I'm essentially asking for both to work similarly; if that's already implemented and just not documented, great! But the topic change makes me think you might think of something very similar but slightly different.

**Comment by janmeier** [comment]
@jfinkhaeuser Do you have any documentation on this? 

`ALTER TABLE foo ADD CONSTRAINT `constraint1` UNIQUE(`some_field`, ...);` followed by `SHOW INDEX` shows that a unique index is created. Similarly, the output from `SHOW CREATE TABLE` are identical. (with the exception that I changed line two to `ADD UNIQUE INDEX`)

Mind you this is only tested on mysql so it might not be the case for other DBs - Google seems to suggest that the two are identical for mssql too however. They might not be for postgres, in particular for partial indexes (which I'm not sure we even support)

**Comment by jfinkhaeuser** [comment]
Well, http://dev.mysql.com/doc/refman/5.1/en/alter-table.html of course, but it's not like I've read the page to verify it covers it ;)

Essentially:
- `ADD INDEX` creates an index, meaning queries on those field(s) no longer require full table searches.
- `ADD CONSTRAINT ... UNIQUE` also creates an index, but additionally requires the field(s) to be unique (in combination).

You may have a need to accelerate searches on some fields without requiring their tuples to be unique.

The stereotypical example might be user names vs. user emails:
- Emails need to be unique, and you might search for them as part of the login process, so the index is also useful.
- User names (real names, not handles) are rarely unique, but you might search for them as part of an alphabetical user listing.

**Comment by janmeier** [comment]
Agree - but `CREATE UNIQUE INDEX` also creates a constraint that enforces the fields to be unique.

The `indexes` option supports both:
```js
indexes: [
    { fields: ['a', 'b'], method: 'BTREE'}
  ]
```
```sql
CREATE INDEX `users_a_b` USING BTREE ON `users` (`a`, `b`)
```
Creates an unique, but no constraint

```js
indexes: [
    { fields: ['a', 'b'], unique: true}
  ]
```
```sql
CREATE UNIQUE INDEX `users_a_b` ON `users` (`a`, `b`)
```
Creates a unique index, and enforces a unique constrainy

**Comment by mickhansen** [comment]
> Creates an unique, but no constraint
Should be "creates an index"?

**Comment by jfinkhaeuser** [comment]
Ah, yeah. I'm with you on that.

Sorry, commenting while discussing stuff with other people will result in some loss of clarity ;)

**Comment by sushantdhiman** [comment]
@mickhansen Its already being documented https://github.com/sequelize/sequelize/commit/111de38b04a105fe6f1ecf6faea66da388eee503 , Please close this issue.
