### ISSUE TITLE
Upsert not honoring renamed fields?

### ISSUE THREAD

**Issue by stnever** [sequelize/sequelize#2946]
Hi! I'm using sequelize-2.0.0-rc7 now. I couldn't find out if this is already fixed, if so please disregard this issue.

I have a model with a few renamed fields (my database is underscored):

```javascript
sequelize.define('ClientInfo', {
    customerName    : { type: Sequelize.STRING, field: 'customer_name'
  , currentFirmwareVersion : { type: Sequelize.INTEGER, field: 'current_firmware_version' }
  ...
});
```

Queries and inserts seem to be working as expected. This is a `findOne()` log excerpt. Note that the columns have underscores and Sequelize aliased them correctly:

```
2015-01-15T20:48:47-02:00 - debug: Executing (default): SELECT `id`, `customer_name` AS `customerName`, `current_firmware_version` AS `currentFirmwareVersion`, `last_pointer` AS `lastPointer`, `status` FROM `client_infos` AS `ClientInfo` WHERE `ClientInfo`.`id`=12345;
```

But when I call `ClientInfo.upsert({customerName: 'abc', currentFirmwareVersion: 123})`, the columns are no longer underscored, the query lists them as camelCase and the db obviously complains:

```
2015-01-15T20:48:47-02:00 - debug: Executing (default): INSERT OR IGNORE INTO `client_infos` (`id`,`customerName`,`currentFirmwareVersion`,`lastPointer`,`status`) VALUES (12345,'unknown-customer',NULL,116,'active'); UPDATE `client_infos` SET `id`=12345,`customerName`='unknown-customer',`currentFirmwareVersion`=NULL,`lastPointer`=116,`status`='active' WHERE (`id`=12345)

2015-01-15T20:48:47-02:00 - error:
{ name: 'SequelizeDatabaseError',
  message: 'SQLITE_ERROR: table client_infos has no column named customerName',
...
```

I'm calling the `upsert` method passing a simple object, not a Sequelize instance, should I use the instance? [The docs](http://sequelize.readthedocs.org/en/latest/api/model/#upsertvalues-options-promisecreated) aren't clear to me in this regard...

**Comment by mickhansen** [comment]
A simple POJO should definitely work.

@janmeier

**Comment by janmeier** [comment]
Hmm... is there any way to get a POJO of values with field names @mickhansen ? Similar to `get` but with the actual field names in the db?

**Comment by mickhansen** [comment]
@janmeier `get` doesnt return field names, need to loop through the POJO and replace.

**Comment by janmeier** [comment]
Yeah that's what I though, I just hoped there was a utility method for it ;). Time to make one then1

**Comment by mickhansen** [comment]
@janmeier shouldn't really use `get` for retrieving database insertion values since it runs getters.

**Comment by mickhansen** [comment]
`get` is really for user facing stuff, not database facing stuff :)

**Comment by mickhansen** [comment]
@janmeier suppose we could do `.get({raw: true, fields: true})` but again, `get` is really meant to be user facing :D

**Comment by janmeier** [comment]
Details!! But alright, I'll think up something smarter...
