### ISSUE TITLE
Add QueryTypes.RAW

### ISSUE THREAD

**Issue by janmeier** [sequelize/sequelize#2947]
By default, all calls to `sequelize.query` will use `QueryTypes.RAW`, meaning that everything returned by the dialect is returned as-is - preferrably also the metadata object, which contains data about affected rows etc.

This should hopefully fix a lot of cases where complex raw queries do not return anything.

Users can still override the querytype if they want sequelize handling (e.g. for a simple select query you could pass `QueryTypes.SELECT`)

Not sure about what we should do if callee is passed in - default to `QueryTypes.SELECT`, or enforce that the user specifies the query type?

**Comment by mickhansen** [comment]
@janmeier well `callee` can also be INSERT and UPDATE.

**Comment by janmeier** [comment]
Yeah that's why I thought forcing the user to specify might be a good idea

**Comment by janmeier** [comment]
We also need to think about the `raw` parameter - it might be a tiny bit confusing to have both `options.raw` and `QueryTypes.RAW`...

**Comment by mickhansen** [comment]
Well we might not need `QueryTypes.RAW` at all since it's just the default when there's no other query type defined.

**Comment by janmeier** [comment]
True dat - but then we need to make sure that everywhere else passes a query type (on that right now :) )
