### ISSUE TITLE
Error from master: dialect postgres is not supported

### ISSUE THREAD

**Issue by Bondifrench** [sequelize/sequelize#2949]
I have recently upgraded sequelize with the master version after @mbroadst upgraded the MSSQL driver so it can work with table schemas using 
````
"sequelize": "git://github.com/sequelize/sequelize#master"
````
this worked fine with MSSQL however in the same project I connect to a Postgres db (using pg.js) that used to work before my upgrade, @mickhansen did you recently change something to the postgres dialect?
I get the following error:
````
c:\Users\London\Apps\FinviewsApp\node_modules\Sequelize\lib\sequelize.js:191
      throw new Error('The dialect ' + this.getDialect() + ' is not supported.
            ^
Error: The dialect postgres is not supported. (Error: Cannot find module 'pg-hstore')
    at new module.exports.Sequelize (c:\Users\London\Apps\FinviewsApp\node_modules\Sequelize\lib\sequelize.js:191:13)
    at Object.<anonymous> (c:\Users\London\Apps\FinviewsApp\models\index.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\London\Apps\FinviewsApp\routes\api.js:1:72)
    at Module._compile (module.js:456:26)
````

Note, reversing to 2.0.0-rc7 doesn't work, but to version 2.0.0-rc6 does.

**Comment by mickhansen** [comment]
@Bondifrench you need to install `pg-hstore` aswell. We removed it from dependencies.
As evident from `(Error: Cannot find module 'pg-hstore')`

**Comment by mickhansen** [comment]
The error message could really be more clear than that though.

**Comment by Bondifrench** [comment]
Just to be clear, on top of pg.js I need to install pg-hstore?
Oh I see you have changed the docs.
Seems to have resolved the ssue, thanks

**Comment by mickhansen** [comment]
Yep pg + pg-hstore to remove the pg-hstore install from mysql/sqlite/mssql ;p

**Comment by novemberalpha** [comment]
Adding pg-hstore fixed my crashing as well. I got distracted by a post on Stackoverflow that suggested install pg-native to remedy the situation. Installing pg-native gives the following error and down the wrong rabbit hole we go: 

```bash
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.33"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/api/node_modules/pg-native/node_modules/libpq/.node-gyp"
/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.14.27-25.47.amzn1.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/api/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.14.27-25.47.amzn1.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "pg-native"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.7
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.5.1 install script.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/api/npm-debug.log
```

http://stackoverflow.com/questions/22083223/postgres-dialect-not-working-in-sequelize-m

**Comment by mickhansen** [comment]
To install `pg-native` you need to have `libpq` and possible `libpq-dev` installed aswell.
But no just `pg-hstore` in this instance :)

**Comment by anneb** [comment]
I kept on getting this message (Error: Cannot find module 'pg-hstore'), even after installing pg-hstore
<blockquote>npm install pg-hstore</blockquote>
The problem was in the way node looks for modules. Node searches for directories 'node_modules' in the current directory and all parent directories. If sequelize is installed somewhere in the parent directories, then sequelize cannot find 'pg-hstore' installed in a subdirectory. So, make sure that modules sequelize, pg and pg-hstore are all installed in the same directory.

**Comment by curiousdannii** [comment]
I too am getting this error. I've tried running globally installed copies of sequelize-cli/pg/pg-hstore and locally installed copies with no difference, it still says I need to install pg.

Sequelize [Node: 0.12.7, CLI: 1.7.2, ORM: 3.4.1]

**Comment by janmeier** [comment]
@curiousdannii Yes, in that case you need to install pg-native :)

**Comment by curiousdannii** [comment]
@janmeier Just pointing out that the error message is still misleading. If it's going to tell me to install a package manually, then it should tell me what I actually need to install, or else just say "Install the required packages"

**Comment by bjones6** [comment]
Just wanted to point out I ran into this issue while configuring unit tests for Circle CI. Circle CI uses a test database with the role "ubuntu" and no password. Passing a configuration object to Sequelize with no password yields:

```
 "Error: The dialect postgres is not supported. (Error: Please install 'pg' module manually)"
```

And after added pg-native the error becomes:

```
Unhandled rejection Error: expected [SequelizeConnectionError: fe_sendauth: no password supplied
] to sort of equal null
```

will post back when I find the solution.

**Comment by bjones6** [comment]
Ok I'm back. It appears I misinterpreted what native: true did. However I did find what I believe to be the bug.

```javascript
// This will properly connect to a database with a user that does not have a password
var s = new Sequelize("db_name", "user", null, {...})
```

and 

```javascript
// This will NOT properly connect to a database with a user that does not have a password
var s = new Sequelize({
    username: "user",
    database: "db_name",
    password: null, // or password: "" (empty string) for that matter
});
```

After I fix the problem in my codebase i'll post it under a new issue with some code examples.

**Comment by tadman** [comment]
I just want to add if you're getting the `Cannot find module 'pg-hstore'` type message and you're using a globally-installed `sequelize` you need to be sure you've installed the `pg-hstore` module globally as well. The local packages defined in `package.json` in your project are not used by that command.

Hopefully this helps anyone who's installed it into their project and things still aren't working. Install it globally if you're using the global command.

**Comment by chandankrishnan** [comment]
/home/bridgelabz1/Documents/backend/node_modules/sequelize/lib/sequelize.js:187
      throw new Error('The dialect ' + this.getDialect() + ' is not supported. ('+err+')');
      ^

Error: The dialect mongodb is not supported. (Error: Cannot find module './dialects/mongodb')
    at new module.exports.Sequelize (/home/bridgelabz1/Documents/backend/node_modules/sequelize/lib/sequelize.js:187:13)
    at Object.<anonymous> (/home/bridgelabz1/Documents/backend/app.js:11:15)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
 
got this error but not resolve by npm install pg-hstore --save

**Comment by Bondifrench** [comment]
@chandankrishnan  Your error seems to suggest you were looking for the `mongodb` dialect, not `Postgres`, are you sure you indicated your `dialect` correctly?

**Comment by chandankrishnan** [comment]
now i change dialect as 'mongodb' but not working...give a same error

**Comment by Bondifrench** [comment]
@chandankrishnan sequelize does NOT work with MongoDB.
MongoDB is a Nosql database, Sequelize works for all relational databases (ie that use SQL).
