### ISSUE TITLE
ORM to increment a value

### ISSUE THREAD

**Issue by dmbrowne** [sequelize/sequelize#2956]
Is they a way to increment a integer by 1 using the the ORM? 
e.g.
```
UPDATE posts 
   SET likes = likes + 1
WHERE id = 32435;
```
This is a simple enough raw query so writing it raw isn't that big of a issue, but I always prefer an ORM method as it makes updating in the future easier.

**Comment by mickhansen** [comment]
We have increment on instances: http://sequelize.readthedocs.org/en/latest/api/instance/#incrementfields-options-promise

It requires you to load the instance first (or hack around it with something like `Model.build({id: 32435}, {isNewRecord: false}).increment('likes')`

**Comment by dmbrowne** [comment]
Thanks, looks like I missed that in the docs.
