### ISSUE TITLE
generic-pool maxConnections likes multiple used in mysql with node v.11.x

### ISSUE THREAD

**Issue by gse7en2012** [sequelize/sequelize#2958]
hi. Recently I found a problem.
I am using pm2 V0.12.3 and node v0.11.12. I found out that when using cluster mode in pm2 , generic-pool database connections=node instances* pool.maxConnections. 
But in fork mode, generic-pool maxConnections works well .
For example,  my pool config setting maxConnections=10,then i run  "pm2 start index.js -i 10" that i find the mysql conncetions=10*10. And run likes  "pm2 start index.js" , mysql connctions=10.
When using v0.10.28 and pm2 0.8.3 do not have this problem before. all the node instances share the pool maxConnections . 
So I'm confused， is that node v0.11.x's new cluster module cause the problem?

**Comment by mickhansen** [comment]
You probably want to open this issue against generic pool.
But i would assume that with any kind of multi process handler for node.js you'll end up with multiple sequelize instances and therefor multiple connection pools.
