### ISSUE TITLE
UpdateAttributes not working with null attributes

### ISSUE THREAD

**Issue by mchicote** [sequelize/sequelize#2960]
Hi
The following is not working for me:
```javascript
var changedAttributes = {}
changedAttributes.stock = null

product.updateAttributes(changedAttributes)
```

`product stock` is not being update. The `UPDATE` does not include the stock value.
Is this a bug or am I understanding something incorrectly? 

Thanks!

**Comment by mickhansen** [comment]
What is `product.stock` before the update?
If you are working off the latest version `update` will ignore attributes that haven't been changed.

**Comment by mchicote** [comment]
Sorry, I made a mistake on my first post. I have already updated it.

Before update the value is 0. 
I'm working on the latest versión

**Comment by mickhansen** [comment]
Changing it from `0` to `null` should result in an update, if it doesn't that's certainly a bug.

**Comment by mchicote** [comment]
ok, let me see if I can build a minimal example of this and I'll post back.

**Comment by mchicote** [comment]
My bad. Sorry for the inconvenience. Thanks for the help.

**Comment by magistrula** [comment]
I'm having this issue as well. @mchicote, how did you solve your problem?

**Comment by haikyuu** [comment]
It's actually working (in sequelize 3). I came across this issue because i was using undefined instead of null.
`
db.SomeModel.update({ name: null}, {
        where: {
          id: 3
        }
      })
`

**Comment by magistrula** [comment]
@haikyuu, hmm...I'm definitely using null. I tried both using Model.update and instance.updateAttributes, no luck either way.

**Comment by janmeier** [comment]
@magistrula If you can create a self contained test case, its easier for us to help debug :)

**Comment by nawlbergs** [comment]
Check your getters/setters on your model..  I had this issue too... but then realized my setter was modifying it to a string on save.
