### ISSUE TITLE
Mocking Dialect

### ISSUE THREAD

**Issue by mchicote** [sequelize/sequelize#2961]
As mentioned in #1902, a Mocking dialect would be great. As suggested by @janmeier, I'm opening a Feature Request.

**Comment by mickhansen** [comment]
So obviously any kind of create/update could likely be put into somekind of POJO memory store.
The problem would be querying those values with everything we support in find calls etc.

**Comment by mickhansen** [comment]
Really the mock dialect would probably have to pass the entire integration test suite, which would not be trivial.

**Comment by mchicote** [comment]
Would that be the same as having a sqlite on memory? Without taking into consideration the obvious difference of not including an external dependency. It would also be necessary to drop everything between tests.

In my ideal world I would like to mock what a query returns before each test. Similar to what I do using [rewire](https://github.com/jhnns/rewire). I would, of course, need to specify different results in case a query method is called more than once.

**Comment by gustavohenke** [comment]
:+1: for such feature, even though the suggestion of using SQLite on memory seems a good choice to me right now.

**Comment by mickhansen** [comment]
A mocking dialect is not practical since it would require us having to write our own SQL parser that could work with in-memory JSON.

However we'd love to look into helping users stub our relevant methods: #5645
