### ISSUE TITLE
Possibly unhandled TypeError: Object [object Object] has no method 'filter'

### ISSUE THREAD

**Issue by markforster** [sequelize/sequelize#2963]
What you are doing?

Running a query against a simple object using the db instance generated through the index.js (the module file generated to bring together the DB instance, sequelize and model files)

Post a minimal code sample that reproduces the issue, including models and associations

(Might be best to attach as file)

What do you expect to happen?

I expected to be able to still run a find query against the model 

What is actually happening?

An unhandled type error was thrown notifying me that object has no method 'filter'

Which dialect you are using?

not sure what that means :(.. mySQL?
Which sequelize version you are using?

2.0.0-rc7 when it failed and 2.0.0-rc4 when it worked

first line of error >>>> at Object.module.exports.QueryGenerator.handleSequelizeMethod (/Users/markforster/Workspace/hedgehoglab/LabProjects/labprojects_lib/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1382:28) (I'll attach full og shortly)

found in 2.0.0-rc7.. works in 2.0.0-rc4. havent stepped through each RC

Found when models etc.. were moved into a shared npm module and npm install was run on new package with version numbers set "^2.0.0-rc7".. put back to 2.0.0-rc4 and worked as expected.

Reverting back to 2.0.0-rc4 fixed the problem.. just thought i'd raise for reference.

**Comment by markforster** [comment]
Code snippet 

var query = {
				where: context.db.sequelize.or({ "email": username }),
				include:[
					{
						model:context.db.AccountUser,
						where:{"AccountId":account.id}
						}
				]
			};

			//	Get projects where Account ID Matches!!
			
			// console.log(">>>> ",context.db.User);
			context.db.User.find(query).success(function(user)
			{
				//	Do the passwords match!!!
				if(user)
				{
					console.log("The User Exists!!!",">"+password+"<");
					if(passwordHash.verify(password, user.password))
					{
						callback(true,user);
					}
					else
					{
						callback(false,null);
					}
				}
				else
				{
					callback(false,null);
				}
			});

**Comment by mickhansen** [comment]
Looks like its failing on https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1438 which is strange.

Can you try logging `query.where`?

**Comment by cusspvz** [comment]
Also happening here with `rc-7`.

**Comment by markforster** [comment]
yup @mickhansen was going to attach log but forgot.. I'll log query.where a soon as I'm back to some dev.

**Comment by markforster** [comment]
ok, I've logged query:

'''
{ args: [ { email: 'mark.forster@hedgehoglab.com' } ] }
'''

where was setup to run a single seuqlize.or as originally I was checking both username and password in with a combined "or" AND "and" during early dev which I reworked when I refactored to perform password checking after the query using passwordHash.. and didnt bother to refactor out the single argument or as it continued to work.

Short term fix was to remove the sequelize.or so my query went from: 

'''
var query = {
				where: context.db.sequelize.or({ "email": username }),
				include:[
					{
						model:context.db.AccountUser
						,include:[
							{model:context.db.Account}
						]
					}
				]
			};
'''

to 

'''
var query = {
				where: { "email": username },
				include:[
					{
						model:context.db.AccountUser
						,include:[
							{model:context.db.Account}
						]
					}
				]
			};
'''

so again, short term fix..maybe sequelize.or was expecting more than 1 set of query arguments..

havent tested this with more than one set but guessing an or with single argument should still be expected to work?

**Comment by mickhansen** [comment]
`args` is an array so it shouldn't be failing.
Seems like a bug,

**Comment by BridgeAR** [comment]
@markforster Is this still an issue? I run a couple of different querys looking like yours and everything passed.

**Comment by markforster** [comment]
Haven't had a chance to test this.. went with simply reverting back and havent had time to work on my app. I'm sure you guys have sorted this but next time I get a chance I'll update to latest and test.

Again, no doubt you guys have this nailed ;) cheers
