### ISSUE TITLE
#2919 expansion: NULLS LAST and literals

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#2969]
Need to expand #2919 to cover DESC NULLS LAST, ASC NULLS LAST and support for .literal().
Publish to NPM after fix.

**Comment by masad-frost** [comment]
Is this ditched?

**Comment by mickhansen** [comment]
No it was implemented @masad-frost

**Comment by masad-frost** [comment]
Oh yeah, it works. I don't know why I got this error `Order must be 'ASC' or 'DESC', 'DESC ' given` earlier, unfortunately I don't have a diff with the wrong code, probably a typo though. Thanks!

**Comment by mickhansen** [comment]
@masad-frost looks like you have `DESC `, that is DESC with a space after it.
