### ISSUE TITLE
[BUG]findOrCreate will not work properly while using complex where clause

### ISSUE THREAD

**Issue by wilsoncook** [sequelize/sequelize#2970]
pieces of code below:

``` js
return SyncQueue.findOrCreate({
    where: {
        'UserId': self.userId,
        'status': { ne: 2 }
    },
    defaults: defaults
}).spread(function ($tmp, created) { $gQueue = $tmp; });
```

When these is no records match the searching, Sequelize is willing to insert an new record, but, it generate an wrong SQL below:

``` sql
INSERT INTO `zx_sync_queue` (`id`,`status`,`createdAt`,`updatedAt`,`UserId`) VALUES (DEFAULT,`ne` = 2,\'2015-01-20 09:06:39\',\'2015-01-20 09:06:39\',1);
```

so, an exception throws:

``` sql
SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'ne' in 'field list'
```

if i set the **defaults** options to be `{'status': 0}` to override the attribute in **where**, it will be ok.

**Comment by mickhansen** [comment]
Should it ignore the entire `where` statement if any of the fields is not a plain value or only ignore the specific fields?

@janmeier
