### ISSUE TITLE
validate isIP fail unexpected when Model.create

### ISSUE THREAD

**Issue by iammapping** [sequelize/sequelize#2972]
The `isIP` validator failed when I give a right ip, sequelize version `2.0.0-rc7`.
I'm looking for the reason, maybe the `ture` value of `isIP` conflicting with the second parameter of `validator.isIP`, it expect 4 or 6 or empty.
But I don't know why the `Model.build` executes success, the test code is below:

Model
```javascript
module.exports = function(sequelize, DataTypes) {
    var Test = sequelize.define('Test', {
        ip: {
            type: DataTypes.STRING,
            allowNull: false,
            validate: {
                isIP: true
            }
        }
    });

    return Test;
};
```
call create and build
```javascript
var Models = require('../models');
var Test = Models.Test;

// throw error
Test.create({
    ip: '127.0.0.1'
}).catch(function(e) {
    console.log(e);
    // { [SequelizeValidationError: Validation error]
    //   name: 'SequelizeValidationError',
    //   message: 'Validation error',
    //   errors:
    //    [ { message: 'Validation isIP failed',
    //        type: 'Validation error',
    //        path: 'ip',
    //        value: 'Validation isIP failed',
    //        __raw: 'Validation isIP failed' } ] }
});

// success
Test.build({ip: '127.0.0.1'});
```

**Comment by mickhansen** [comment]
`build` just creates an instance, it doesn't actually validate untill you either save or call validate.
Unsure why the validation is failing though, does it fail with `isIPv4: true` too?

**Comment by iammapping** [comment]
`isIPv4: true` is ok, it has extended `validator.isIP`  with second parameter as 4
```javascript
Validator.extend('isIPv4', function(str) {
  return this.isIP(str, 4);
});
```

**Comment by mlegenhausen** [comment]
+1 the problem is that `isIP` is called with 3 parameters by sequelize e.g. `[ '192.168.0.1', true, 'ip' ]` and the seconds argument is interpreted as the version. Cause `true` is no valid version the validator fails when using `isIP` adding a new extend that makes sure `isIP` is called with only one parameter should fix the problem.

```js
Validator.extend('isIP', function(str) {
  return this.isIP(str);
});
```

**Comment by mlegenhausen** [comment]
Workaround for now:

```js
ip: {
  type: DataTypes.STRING,
  allowNull: false,
  validate: {
    isIP: '' // validator.js interpretes this as false so both versions are checked
  }
}
```

**Comment by janmeier** [comment]
@mlegenhausen You should be able to pass `isIP: false` as well. At first glance it might not make 100% sense to but false next to the validator, but one 'just' has to remember that its the argument to the validator, not an enable / disable switch.


We might want to make this clear in the docs as well

**Comment by mlegenhausen** [comment]
@jammeier I tried this it is not working cause of the `validator.toString()` method from `validation.js` which would translate the boolean value into a string. `''` is working cause it is a string and is also false, so it is handled as if there is no version parameter.
