### ISSUE TITLE
Include property used for eager loading does not throw an error when supplied with String name

### ISSUE THREAD

**Issue by MirzaSikander** [sequelize/sequelize#2978]
Instead of:
```
 db.Category.find({
        where: {id: categoryId},
        include: [{
            model: db.Product,
            include: [{model: db.Diagram}]
        }]
    }).then(function (Category) {})
```
I wrote:
```
 db.Category.find({
        where: {id: categoryId},
        include: [{
            model: "Product",
            include: [{model: "Diagram"}]
        }]
    }).then(function (Category) {})
```

The application did not return any callback, not even the error one, and continued on as if nothing had happened. 
Although it is not a big deal, but an error message would be nice.

**Comment by Bondifrench** [comment]
I believe you can use both references:
- a string representing the table name: "Diagram"
- or a reference to a mode: db.Diagram
It is mentioned partly here:
http://sequelize.readthedocs.org/en/latest/docs/associations/
see in the last example for Video, references for series_id

**Comment by janmeier** [comment]
Passing a string is definitely not supported in the latest version, and hasn't been for some releases. 

Which version are you on? 

If sounds like the error might have been swallowed in a promise chain

**Comment by mickhansen** [comment]
Are you sure you have attached a catch listener to your promise?

@janmeier i've actually considered whether or not we should introduce string references for models and associations.

**Comment by MirzaSikander** [comment]
Yes I did. Its not showed in the code above but I did.

**Comment by mickhansen** [comment]
@MirzaSikander i find that highly unlikely that an error wouldn't be propagated somewhere, but i will have to test it locally.

**Comment by janmeier** [comment]
Just tested this locally and I get an error. Please comment with node version, sequelize version and model definitions + associations if you still have issues @MirzaSikander 

@mickhansen But we had so many issues with string includes! :(
