### ISSUE TITLE
FULLTEXT indexes throw a parse error on sync()

### ISSUE THREAD

**Issue by nullivex** [sequelize/sequelize#2979]
Hi,

I know that the indexes code is relatively new so this bug probably hasnt affected most people yet.

However I have a model with this in the field definition:

```
{
        name: 'ft_search_index',
        method: 'FULLTEXT',
        fields: ['title','altTitles']
      }
```

When I try to do a `sync()` I get a parse error.

I have to get my lab set back up to produce  the parse error. However this should be easily reproducible.

**EDIT** here is the error.

```
{ [SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FULLTEXT ON `Shows` (`title`, `altTitles`)' at line 1]
  name: 'SequelizeDatabaseError',
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'FULLTEXT ON `Shows` (`title`, `altTitles`)\' at line 1',
  parent:
   { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FULLTEXT ON `Shows` (`title`, `altTitles`)' at line 1]
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'CREATE INDEX `ft_search_index` USING FULLTEXT ON `Shows` (`title`, `altTitles`)' },
  original:
   { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FULLTEXT ON `Shows` (`title`, `altTitles`)' at line 1]
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'CREATE INDEX `ft_search_index` USING FULLTEXT ON `Shows` (`title`, `altTitles`)' },
  sql: 'CREATE INDEX `ft_search_index` USING FULLTEXT ON `Shows` (`title`, `altTitles`)' }
```

Version

```
e132 drama # npm ls | grep seq
├─┬ sequelize@2.0.0-rc8
```

**Comment by nullivex** [comment]
As an added note.

I was able to work around this by commenting out the index, syncing then manually adding the index, then uncommenting the index definition.

**Comment by janmeier** [comment]
You should use `type: 'FULLTEXT'` instead of method

http://sequelize.readthedocs.org/en/latest/api/sequelize/#definemodelname-attributes-options-model

**Comment by janmeier** [comment]
You should use `type: 'FULLTEXT'` instead of method

http://sequelize.readthedocs.org/en/latest/api/sequelize/#definemodelname-attributes-options-model

**Comment by ddeshmane** [comment]
I don't see any documentation on how to configure MySQl DB and Sequelize to implemented Full Text Search. My MySQL version is 5.5.14 and Sequelize version is 3.23.4.
Please guide me to links/code-snippets where I can read on how to configure DB and Sequelize JS for FTS and how to perform FTS Query ?

I am really stuck on this.

**Comment by felixfbecker** [comment]
@ddeshmane you probably will get more help on StackOverflow

**Comment by ddeshmane** [comment]
I have already posted a question on stackoverflow but got not response.
Stackoverfow Question: http://stackoverflow.com/questions/39123631/mysql-fulltext-search-with-sequelize

**Comment by graforlock** [comment]
Any update on how am I supposed to do this now? 

I get `Unhandled rejection Error: Support for literal replacements in the `where` object has been removed.`

So, from stackoverflow example:

```const against = 'more or less';

models.Book.find({
  where: ['isActive = 1 AND MATCH (description) AGAINST(?)', [against]]
}).then((result) => {
  console.log(result.title);
});```

isnt possible anymore.
