### ISSUE TITLE
2.0.0-rc8 missing pg-hstore

### ISSUE THREAD

**Issue by diversemix** [sequelize/sequelize#2980]
Building with the above release does not install the module pg-hstore. (see below)
sequelize@2.0.0-rc8 node_modules/sequelize
├── dottie@0.2.4
├── toposort-class@0.3.1
├── inflection@1.5.3
├── node-uuid@1.4.2
├── validator@3.22.2
├── generic-pool@2.1.1
├── bluebird@2.4.2
├── lodash@2.4.1
└── moment@2.8.4

I get the following error:

      throw new Error('The dialect ' + this.getDialect() + ' is not supported.
            ^
Error: The dialect postgres is not supported. (Error: Cannot find module 'pg-hstore')

**Comment by mickhansen** [comment]
It was removed since it's a PG only dependency, please install it manually. 
http://sequelize.readthedocs.org/en/latest/docs/getting-started/
https://github.com/sequelize/sequelize/pull/2889
