### ISSUE TITLE
Add methods for calling associated models without knowing the name

### ISSUE THREAD

**Issue by mlegenhausen** [sequelize/sequelize#2981]
Generating methods for accessing and modifing the assoications is nice for programmer that writes static code. I am currently writing utitliy methods for generell operations like modifing nested data. Writing these methods in a generell way is a little bit tricky cause I would need to know how the name of the generated methods is.

It would be nice to have a more generell association interface like the following:

``` js
var A = sequelize.define({});
var B = sequelize.define({});

A.hasMany(B);
B.belongsTo(A);

var a = A.create();
var b = B.create();

a.get(B);
a.set(B, b);
a.create(B);
a.removes(B, [...])
a.remove(B, b);
a.has(B, b);

// and so on
```

This of course for one-to-one relationships too.

**Comment by mickhansen** [comment]
Interesting idea. However `get` and `set` would immediately clash.
In general the names might be a bit too generic, but i do like the general idea.

**Comment by mlegenhausen** [comment]
Then maybe `getAssociation(B)` and so on.

Is there any documentation about how the association classes are modeled? Would some more insights for some features I have in my application.

**Comment by mickhansen** [comment]
Yeah i was thinking the same thing, that `getAssociation` might be a way to go :)
No there is not per say, but happy to answer any questions.

**Comment by mickhansen** [comment]
The first parameter would likely have to follow the same syntax as includes, so either a Model, a model/as pair or a Association reference.
