### ISSUE TITLE
Question about .set usage

### ISSUE THREAD

**Issue by radoslavpetranov** [sequelize/sequelize#2982]
I know regular question don't exactly fit the 'Issues' section so please let me know if there's a better place to post these.

I spent a few days working on some code that performs deep updates on any sequelize model instances and I just realized this stuff is actually all supported by the .set method. I went through the docs and it's still a little unclear to me how that method should work.

So say we have 3 models: A, B and C

And we have the following associations (A --> Collection < B >, B --> C):

A HasMany B as bVals
B BelongsTo C as cVal

Now say we have these instances in the DB:

a = { id : 1, aText : 'This is A instance' 
       bVals : [ {   id : 1,
                         bText : 'This is B instance',
                         cVal : { id : 1,
                                      cText : 'This is a C instance'
                          }
                     },{   id : 2,
                         bText : 'This is another B instance',
                     }
        ]
};

and we then want to use a.set() with the following update data

updateData = {
         bVals : [ { id : 1 
                       }, {
                         id : 2,
                         cVal : {
                             cText : 'This is a new C instance'
                          }
                       }
          ]
};

Now here are my questions/understanding of things:

1. the right way to run .set with an object and options would be ---> a.set(updateData, undfined, { /* options here */ } );

2. if I only run a.set(updateData) then options.reset will be false and there will be no options.include models either so nothing would/should really happen because there's nothing to tell the code to update the bVal association and aText will not get reset either because the option reset is false.

3. if I run a.set(updateData, undefined, { reset = true }) then a.aText will end up being null because we haven't provided a value in updateData but again the associations won't be updated because we have no includes.

4. How do I tell the .set method that I want it to update both bVals and cVal (which in turn is internal to bVal instances). Like do I need to pass the include param in a flat list like { include : [B, C]} and expect the code to take care of everything or do I have to create some type of hierarchy like { include : [ { model : B, include : [C] } ]

5. Is there a way to tell the .set method to run reset = false on the A instance and reset = true on the B instance so that if I run a.set(updateData,...) I will end up preserving the aText but losing/resetting the cVal for bVals[0]?

Sorry for the long post but I just wanna know how this stuff is supposed to work and what's supported and what isn't. I think other people will find this information useful as well.

Thanks in advance and cheers!

**Comment by mickhansen** [comment]
`set` with includes only really supports setting the initial values, we don't have any tests or expectations that it will work on existing values currently.

**Comment by mickhansen** [comment]
It's something we'll eventually like to support with nested creates and possible updates, but it is not currently supported.

`set` supports includes so that it's possible to build from a cache or from the database and receive the same instances in the end.

**Comment by radoslavpetranov** [comment]
O ok - at least all the head banging against that wall moments I've had in the last few days with some SQL errors and update/create/delete promises flying here and there wasn't a waste :) Thanks for the quick reply!

**Comment by radoslavpetranov** [comment]
Oh and a last unrelated question:

Do the sequelize getter methods (ex: a.getBVal()) always retrieve the data from the DB? For example if I run a.getBVal() and the data is now loaded will running a.getBVal() again call the DB again or would it just return the already loaded (and potentially not up to date anymore) object?

**Comment by mickhansen** [comment]
All relation getters/setters hit the database yes. Except for `belongsTo` relations which optinally take a `save: false` option on its setter where it will not save but merely set the foreign key on the instance.

**Comment by radoslavpetranov** [comment]
Gotcha - thanks heaps for the help/info Mick. Cheers
