### ISSUE TITLE
belongsToMany & foreignKey

### ISSUE THREAD

**Issue by cuva** [sequelize/sequelize#2991]
Hey,

I'm using the master branch of sequelize. I'm trying to migrate my N:M model to the version 2 as I was receiving the deprecation warning.

        Vessel.belongsToMany(User, {
          through: models.UserVessel,
          foreignKey: 'vesselId'
        })

        User.belongsToMany(Vessel, {
          through: models.UserVessel,
          foreignKey: 'userId'
        })

But sequelizejs seems to create the following join table:

    CREATE TABLE IF NOT EXISTS `UserVessels` (`uuid` CHAR(36) BINARY NOT NULL , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `vesselId` CHAR(36) BINARY, `UserUuid` CHAR(36) BINARY, `userId` CHAR(36) BINARY, UNIQUE `UserVessels_userId_vesselId_unique` (`vesselId`, `userId`), UNIQUE `UserVessels_vesselId_UserUuid_unique` (`UserUuid`), PRIMARY KEY (`uuid`), FOREIGN KEY (`vesselId`) REFERENCES `Vessels` (`uuid`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`UserUuid`) REFERENCES `Users` (`uuid`), FOREIGN KEY (`userId`) REFERENCES `Users` (`uuid`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

As you can see, it created both `vesselId` / `userId` foreign keys, but it also created a UserUuid additional foreign key.

Is this a bug?
Many thanks.

**Comment by mickhansen** [comment]
That sounds like a bug, although i was sure i fixed that previously:

https://github.com/sequelize/sequelize/blob/master/test/integration/associations/belongs-to-many.test.js#L814

But this doesn't test that an extra key is not generated i suppose.

**Comment by cuva** [comment]
Hi Mike,

Thanks for your answer. I've been through the tests, and it looks like the one you've referenced + the next one define these:

      var User = this.sequelize.define('User', {});
      var Place = this.sequelize.define('User', {});

instead of this I guess.

      var User = this.sequelize.define('User', {});
      var Place = this.sequelize.define('Place', {});

Not that it changes much though. Not sure just this is worth a PR.

**Comment by mickhansen** [comment]
@cuva oh lol you're right, there's definitely a typo in that test.

**Comment by cuva** [comment]
I resolved it by setting the attribute `otherKey` on the `options` object. Not sure if that's the expected behaviour but it works fine now:

    CREATE TABLE IF NOT EXISTS `UserVessels` (`uuid` CHAR(36) BINARY NOT NULL , `role` ENUM('vesseladmin', 'crewmate') NOT NULL DEFAULT 'crewmate', `enabled` TINYINT(1) DEFAULT true, `push` TINYINT(1) DEFAULT false, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `vesselId` CHAR(36) BINARY, `userId` CHAR(36) BINARY, UNIQUE `UserVessels_userId_vesselId_unique` (`vesselId`, `userId`), PRIMARY KEY (`uuid`), FOREIGN KEY (`vesselId`) REFERENCES `Vessels` (`uuid`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`userId`) REFERENCES `Users` (`uuid`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

I'll let you close the issue if there's no need for intervention. :)

**Comment by mickhansen** [comment]
It should work without `otherKey` too so keeping it open for now.

**Comment by mickhansen** [comment]
Fixed in `sequelize@2.0.3`

**Comment by peponerock** [comment]
Hey guys. I'm having the same problem here (sequelize@3.12.2)
This is my association table:
```javascript
sequelize.define('category_product',{
    category_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    product_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    }
  });
```
The relations I'm making:
```javascript
db.product.belongsToMany(db.category,{through:db.category_product,foreignKey:'product_id'});
			db.category.belongsToMany(db.product,{through:db.category_product,foreignKey:'category_id'});
```
And this is the output I'm getting: 
```javascript
CREATE TABLE category_product (
    category_id INTEGER  NOT NULL
                         REFERENCES category (id) ON DELETE CASCADE
                                                  ON UPDATE CASCADE,
    product_id  INTEGER  PRIMARY KEY,
    created     DATETIME NOT NULL,
    updated     DATETIME NOT NULL,
    UNIQUE (
        category_id,
        product_id
    )
);
```
Note that foreign key names in category_product table should stay named like that, since that model is autogenerated from a legacy DB.
¿Am I doing something wrong here?

Thank you!

**Comment by janmeier** [comment]
@peponerock I'm not sure what the issue is? product id being marked a primary key?

**Comment by peponerock** [comment]
product_id is not referencing product table, and also both foreign keys should be  a combined primary key (not that important). I was expecting something like this:

```javascript
CREATE TABLE category_product (
    category_id INTEGER  PRIMARY KEY NOT NULL
                         REFERENCES category (id) ON DELETE CASCADE
                                                  ON UPDATE CASCADE,
    product_id  INTEGER  PRIMARY KEY NOT NULL
                         REFERENCES product (id) ON DELETE CASCADE
                                                  ON UPDATE CASCADE,
    created     DATETIME NOT NULL,
    updated     DATETIME NOT NULL,
    UNIQUE (
        category_id,
        product_id
    )
);
```

**Comment by peponerock** [comment]
Please, read the comment above. Thanks

**Comment by janmeier** [comment]
I've read it, please give me time to respond ;)

```js
var CategoryProduct = sequelize.define('category_product',{
  category_id: {
    type: DataTypes.INTEGER,
    allowNull: false,
    primaryKey: true
  },
  product_id: {
    type: DataTypes.INTEGER,
    allowNull: false,
    primaryKey: true
  }
});
```
```sql
CREATE TABLE IF NOT EXISTS `category_products` (`category_id` INTEGER NOT NULL NOT NULL REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `product_id` INTEGER NOT NULL NOT NULL REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, UNIQUE (category_id, product_id), PRIMARY KEY (`category_id`, `product_id`));
```

**Comment by peponerock** [comment]
Thanks a lot! (I'm still learning btw)

**Comment by tyler-canton** [comment]
@jose-nunez How are you getting the output. I'm trying to migrate two models with 'belongsToMany' relationship, this work, however, I'm not seeing the through table within the database. Or does this create the model in sequelize?

**Comment by jose-nunez** [comment]
Sorry mate, I'm out on holidays. I'll be back in April. It's impossible for
me to check it now. Good luck.
