### ISSUE TITLE
postgres upsert does not work for blobs

### ISSUE THREAD

**Issue by alubbe** [sequelize/sequelize#2993]
Code below is very similar to the test https://github.com/sequelize/sequelize/blob/master/test/integration/model.test.js#L2277, where ```.create()``` is replaced with ```.upsert()```.

Using upsert on a model with a  string ```name``` and a blob ```data```
```js
BlobUser.upsert({
    name: "test",
    data: new Buffer('Sequelize')
})
```
builds the following broken sql - note ```data``` in the update statement.
```sql
CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $$ BEGIN

INSERT INTO "users" ("name","data","createdAt","updatedAt") 
VALUES ('test',E'\\x74657374','2015-01-23 13:53:06.796 +00:00','2015-01-23 13:53:06.796 +00:00'); 
RETURN 1;

EXCEPTION WHEN unique_violation THEN 
UPDATE "users" 
SET "name"='2',

"data"=`0` = 116, `1` = 101, `2` = 115, `3` = 116, `length` = 4, `parent` = '[object Object]',

"updatedAt"='2015-01-23 13:53:06.796 +00:00' 
WHERE ("name"='2'); 
RETURN 2; 

END; $$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
```
On their own, both ```.create()``` and ```.update()``` work fine, so I suspect there is something wrong with the way that the ```.upsert()``` method creates the update sql.

If you'd like, I can create a PR with a failing test reproducing this.

**Comment by janmeier** [comment]
This was an issue with lodash.cloneDeep (used in the upsert code) which does not preserve Buffer.isBuffer
