### ISSUE TITLE
Inserting the same record with Promise.settle or promise.all fails to find existing orders

### ISSUE THREAD

**Issue by marcus** [sequelize/sequelize#2994]
I have a model with a unique constraint on a field (order_id). I want to save a bunch of orders, some might be duplicated like this:
```
[{order_id: 123, ...}, {order_id: 345, ...}, {order_id: 123, ...}]
```
I have a writeOrder function that returns a promise that writes the order. If the order doesn't exist, it writes a new one, otherwise it should find and update the existing order.

The problem is that it using writeOrder within promise.settle or promise.all never finds an existing order. It always only tries to write new orders, causing validation errors because of the unique constraint. I've tried switching between creating and upserting, but it never finds the existing order.

It seems like somewhere I should be able to tell sequelize to actually hit the database to find the existing order before trying to write it.

If this isn't clear, let me know and I can post more code.

**Comment by marcus** [comment]
I noticed that the actual queries are 3 selects to find each order, then 3 writes. I would have expected a series of 3 "select, write/update" operations.

I'm not sure the best way to avoid this, but for now I've gotten around it by filtering the records in memory before hand. I'm very interested to know if there's a better way. It seems like this could just be something I am doing wrong.

**Comment by mickhansen** [comment]
Are you using findOrCreate?
It should actually be optimized for concurrency cases on unique keys.

**Comment by janmeier** [comment]
Please show some actual code (model definition, test case and find call(s))

As mick mentioned, this could probably be handled using findOrCreate
