### ISSUE TITLE
Transactions extremely slow when inserting 1000s of records using findOrCreate

### ISSUE THREAD

**Issue by ameensol** [sequelize/sequelize#2995]
Hello,

Great work on the library! It's been a lifesaver so far and I've been able to figure everything out through the docs. I'm learning my way around transactions and it's been a bit of a mind-opener. I recently hit a strange problem though and would appreciate any help. 

I'm trying to load several thousand twitter accounts into the database simultaneously. I wrapped the operation in a transaction, and my application started to slow to a crawl. Below is the relevant code:

``` js
        return sequelize.transaction(function (t) {
          console.log('Started transaction for list' + count)
          return sequelize.Promise.map(members, function (member) {
            return Tweeter.findOrCreate({where: {id: member.id}, defaults: member}, {transaction: t})
            // return Tweeter.upsert(member)
          })
        })
```

In my application, without the transaction, inserting the several thousand accounts only took ~30 seconds. However, once I wrapped it in the transaction it took up to 5-10 minutes. I prepared a [test repo](https://github.com/ameensol/sqlizeTransaction) (instructions below) which only performs this operation. In this isolated environment, I found that without the transaction, the operation would finish in 8-9s, but with a transaction it would take 30-40s.

There are several things I'm confused about:
1. Why would this operation take my application several _minutes_? For only several thousand rows, amounting to ~6MB of data, it seems ridiculous that it would take so long.
2. Why the great discrepancy between the isolated test case and the application results? In the application, I'm saving 16 arrays totaling ~3000 accounts, with the last 2 being length ~1000 each, and the first 14 in total being length ~1000. These first 14 arrays save in ~35s, and then as I mentioned I'm stuck waiting 5-10m for the last 2. The test case saves just those 2 arrays of accounts and takes 30s.
3. Is it normal for transactions around findOrCreate to take 3x longer? 
4. Something I noticed was that I sometimes hit the memory limit on my computer during these operations. Could this cause the transaction to fail? Could I be filling up some kind of buffer of operations? Since I have a transaction I can't commit until I can commit all 1000 operations, right? So maybe the Postgres is attempting to hold all the locks from each operation in memory but then continuously failing until the system idles some other processes? Any ideas on how I might be able to test this?

For the test case repo, all you need to to run it is to create a file called `config.json` and add your database URI:

``` json
{
  "db": "postgres://pass@host:port/db"
}
```

By default, the code will attempt to do the transaction, but you'll find that on line 35 of index.js you can change `transaction()` to `noTransaction()` which will test the other case.

**Comment by ameensol** [comment]
I looked at the Postgres implementations for findOrCreate and upsert, and it looks like both use the pattern of attempting the create operation but then doing the select or update when there is an exception. The Postgres docs indicate that exception handling is slower -- could the combination of exception handling in a transaction cause the slowdowns I was seeing?

**Comment by mickhansen** [comment]
Exception handling is likely slower, but is something we need to support concurrent findOrCreate's inside a transaction.

Transactions probably generally have a performance overhead since they force your queries to be sequential within the transaction - and it also limits you to one connection per transaction. So if you previously had a pool of say max 10 connections it would be using all those 10 connections to run all your queries, if you are using a **single** transaction for **all** of your calls it will only use a single connection and all those queries happen sequentially (rather than with a parallelity of 10)

**Comment by mickhansen** [comment]
For ETL stuff you might want to stay away from transactions, transactions are great for ensuring data integrity which might not be needed if you run an ETL (where you can start from scratch everytime possibly).

**Comment by ameensol** [comment]
Thanks for the quick reply!

Okay. When I looked at the Postgres findOrCreate implementation, I saw that it has two behaviors: The first is to use an internal transaction when findOrCreate isn't inside a transaction, and savepoints when it is. Is the exception handling necessary for both cases to properly work? When findOrCreate isn't inside a transaction and savepoints are used, could it also query without using exception handling? I'm a bit naive to how sequelize works under the hood, so mostly I'm just curious. Although if this is the case and it isn't incredibly difficult to implement it might be a cool optimization I could potentially help contribute down the road.

Thanks for explaining the enforced sequential behavior of transactions -- that makes a lot of sense. I was using 100 connections but was doing all 1000 of my calls in a single transaction. 

This is a weird ETL edge case. I have a lot of data to load upfront, but then also need to continuously load additional data as I receive it over the next several months/years. As a workaround to this transaction delay, I was planning on implementing a sort of persisted WAL, so I could make a single record of all the members I was planning on updating, then attempting the several thousand inserts, and then if they were all successful deleting the log entry. I'd rather not start from scratch everytime, and this would allow me pickup roughly where I left off and only have to try the pending insert operations in case of a failure. 

Thanks again for the help!

**Comment by mickhansen** [comment]
The exception handling is required for postgres because in postgres unlike other sql dialects a constraint will disallow any further calls on that transaction. The exception handling is really to support concurrent findOrCreates where two parallel finds will be done, both will result in no result being found and they will both insert, however one of the inserts will then hit a unique constraint, we then catch that and find the new inserted instance (from the sister parallel call).

Does your ETL need to update data aswell or just create it if it's missing?
If it was a dialect like mysql i would suggest using INSERT IGNORE but unfortuneatly PG does not support this.

**Comment by ameensol** [comment]
Thanks for the explanation. My ETL does need to update data, probably not initially, but in the long run as I get new information I will need to make sure its updated. So far I've been developing the code to run initially, so I've been using findOrCreate. When I want to update data when its already there I think I'll need to use an upsert, right?

**Comment by mickhansen** [comment]
It does not use exactly the same, but yes it uses exception handling too, unfortuneatly that's a requirement for postgres. PG is also the only dialect where you can't deal with exceptions on the app side and just let the transaction keep going unfortuneatly.

**Comment by ameensol** [comment]
I'm still getting abysmal results. Below is a sample of some analytics for one type of database operation I'm doing. 

```
info: Stats for friend.findOrCreate
info: {
	"count": 10458,
	"mean": 106657,
	"min": 37529,
	"max": 178720,
	"median": 104751,
	"stddev": 37933
}
```
I can't imagine why these operations should be taking so long. I've been trying to debug but I feel a bit like an 18th century doctor—lobotimize! leech!—I have no idea what I'm doing. I've tried changing the number of connections, but it doesn't help. I stopped using transactions but it isn't enough. I have a hunch that the problem might have something to do with available memory, but I haven't been able to figure out a way of testing it yet. 

I guess what I'm asking is: Is there a Postgres textbook I should read before moving on? Is there any chance I'm using sequelize wrong? I've read the sequelize docs many times now, so I don't think I'm doing anything wrong, but is there a good way to get started learning about how sequelize and postgres work together? Should I just read the code?

**Comment by mickhansen** [comment]
@ameensol you are not hitting the original speeds you had without using transactions?
findOrCreate in PG is a complicated beast to support concurrency so it probably is not the most performant.

Are you ever running your ETL in parrallel? i.e. two instancesof the same ETL script, if not you could forego the sugar of findOrCreate for higher performance by first feting all the instances by the unique identifiers and then doing update/create based on that.

**Comment by frogcjn** [comment]
Very Slow. 10 records need 3 seconds!!

**Comment by janmeier** [comment]
@frogcjn [SSCCE](HTTP://SSCCE.ORG/) please?

**Comment by sushantdhiman** [comment]
Inserting 10 record stake 10 s ?

**Comment by janmeier** [comment]
Sounds like you may have some transactions blocking each other - But its hard to say without seeing some actual code ;)

**Comment by frogcjn** [comment]
@sushantdhiman 100 records need 3 seconds!!

**Comment by sushantdhiman** [comment]
@frogcjn Let me add transaction suite to our benchmarks and let see the actual numbers :)

**Comment by sushantdhiman** [comment]
@frogcjn You are inserting one record per transaction or 100 records in single transaction (bulkCreate)

**Comment by frogcjn** [comment]
I'll try to use transaction.

**Comment by sushantdhiman** [comment]
You are not using transactions and inserting 100 records take 3s ? @frogcjn

**Comment by frogcjn** [comment]
@sushantdhiman yes
 const [content/*, created*/] = await Book.findOrCreate({
        where: { A, B, C },
        defaults: {
               ...
        }
    })

A, B, C is unique indexed. In PostgreSQL

since PostgreSQL does not support ignoreDuplicates or updateOnDuplicate, I cannot use BulkCreate to deal with duplicate situation.

**Comment by mickhansen** [comment]
`findOrCreate` uses a transaction internally, try `findCreateFind` if you're not using an outer transaction.

**Comment by sushantdhiman** [comment]
Have a look at https://github.com/sushantdhiman/sequelize-benchmark , There is a test for creating 100,000 records and it take `5s`, for creating 1500 records it take just `0.07s` (sqlite)

**Comment by frogcjn** [comment]
So how to deal with bulk create with unique index in Postgres? inserting rows may have unique conflict with data in database.
findCreateFind needs 2 seconds for 100 rows with 3 rows unique index.

**Comment by sushantdhiman** [comment]
I just want to point point bare inserting 1000 records take milliseconds.

Your case can be solved with transactions, but we dont have any numbers for that cases. ( I'll try to add one soon)

**Comment by frogcjn** [comment]
@sushantdhiman , The point is 
This problem is not about pure inserting. It is about unique required inserting.

**Comment by frogcjn** [comment]
findOrCreate with transaction
100 records
3646ms

**Comment by frogcjn** [comment]
This issue may related to https://github.com/sequelize/sequelize/pull/6325
https://github.com/sequelize/sequelize/issues/4132

**Comment by frogcjn** [comment]
bulkCreate with the same 100 records only 201 ms
So I believe this is a PostgreSQL problem pre 9.5. It will be easier in MySQL.

**Comment by sushantdhiman** [comment]
@frogcjn There are known performance issues around transactions and build.

I will try to get exact numbers recorded via sequelize-benchmark. Hopefully after that I will be able to pinpoint major bottlenecks and later on improve them :)

**Comment by frogcjn** [comment]
PostgreSQL 9.5, modified sequelize
`bulkCreate` and 'ON CONFLICT DO NOTHING'

479ms

**Comment by vitaly-t** [comment]
Below are pessimistic performance figures for inserting multiple records:

|   records    |    10    |   100   |    1k   |    10k   |   100k   |   1m   |   10m  |   100m  |
|:------------:|:--------:|:-------:|:-------:|:--------:|:--------:|:------:|:------:|:-------:|
|    time      |    <1ms  |    4ms  |   15ms  |   110ms  |  1040ms  |  10.5s |  105s  | 17.4m   |

They are pessimistic, because they were based of `pg-promise` library, which is high-level promise library on top of the same `node-postgres` library. So if you you were to use that driver directly, you could get even better performance figures, in theory.

This is just as a perspective on on the performance figures that were quoted here above by a few developers.

**Comment by papb** [comment]
Is this still happening? Does this depend on the dialect? Can someone please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))?
