### ISSUE TITLE
How to find distinct rows in a table?

### ISSUE THREAD

**Issue by lvarayut** [sequelize/sequelize#2996]
I'm trying to find distinct rows in a table. I currently have the following query:

```javascript
    db.User.findAll({
        distinct: 'UserId'
    })
```

I found a thread on [Stackoverflow](http://stackoverflow.com/questions/12156206/sequelize-select-distinct-rows), asked in 2012. It's written that It's not possible and we have to  create a raw SQL. Is it possible right now?

**Comment by mickhansen** [comment]
No it's still not supported as far as I know

**Comment by lvarayut** [comment]
Alright. Thanks for your response.

**Comment by bluepeter** [comment]
@Ivarayut why can't you use https://github.com/sequelize/sequelize/blob/5be311997d5a07030ba62d9df1ab77ec52be415f/lib/model.js#L794 to get distinct rows?

**Comment by swordofpain** [comment]
You can do the following to get a list of distinct values for a field:

```javascript
MyModel.aggregate('teh_field', 'DISTINCT', { plain: false }).then(...)
// Resolves to: [ { DISTINCT: value1 }, { DISTINCT: value2 }, ... ]
```

**Comment by DemarsM** [comment]
@swordofpain very nice!

Going a little further is it possible to sum values of a field using distinct. 
For instance:

          id  | group   | people
         -----+---------+--------
           1  | A       |  1
           2  | B       |  6
           3  | B       |  2
           5  | B       |  4
           6  | B       |  8
           7  | A       |  3

    Result:
           group| people*sum
          ------+------------     
             A  | 8
             B  | 20

**Comment by swordofpain** [comment]
Judging by the code, you should be able to do something like:

```javascript
MyModel.aggregate('people', 'SUM', { plain: false, group: [ 'group' ] })
```

**Comment by DemarsM** [comment]
@swordofpain thanks! Except this query do not return group value, its perfect!

**Comment by swordofpain** [comment]
Add `attributes: [ 'group' ]` to the third param. It should do the trick

**Comment by DemarsM** [comment]
@swordofpain Thank you for this little lesson, its really appreciated!

**Comment by aaronwilliams97** [comment]
This could also have been achieved using sequelize.fn, but the model.aggregate works fine, too.

myModel.findAll({
     attributes: [[sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']],
     /*group: ['col_name'] <-- only necessary if you were doing like a 'COUNT', etc...*/
     /*just added it to be thorough, in-case you were using for multi-purpose*/
}).then....blah blah blah, nothing new here

Again, the above solution works fine, just a manner of preference.

**Comment by bhagyalakshmikk** [comment]
Hi

IS there any method to rearrange the select statement arguments in query using sequelize. ??
I got the generated query as 
SELECT "npi".*, "cms"."_id" AS "cms.id", DISTINCT("provider_type") AS "cms.specialty" FROM (SELECT "npi"."NPI".............

Bt I need the query as, 

SELECT  DISTINCT("provider_type") AS "cms.specialty", "npi".*, "cms"."_id" AS "cms.id"  FROM (SELECT "npi"."NPI".............

**Comment by sagarora77** [comment]
Model.findAll({Attributes: ['col_name'], group: ['col_name']});
It worked fine on Sequelize version 3.6

**Comment by UmerIftikhar** [comment]
myModel.findAll({
attributes: [[sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']],
}).then

Does not seem to be working on MSSQL Server.
Does it have the support?

**Comment by Milad** [comment]
This worked for me: https://stackoverflow.com/a/30070249/2072132

**Comment by AnechaS** [comment]
try this 

```ts
myModel.findAll({
     attributes: [[sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']],
     'id'
})
```

**Comment by alvaroaac** [comment]
> try this
> 
> ```ts
> myModel.findAll({
>      attributes: [[sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']],
>      'id'
> })
> ```

This is invalid syntax. What would be the purpose of 'id' ?

**Comment by serlapteff** [comment]
> > try this
> > ```ts
> > myModel.findAll({
> >      attributes: [[sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']],
> >      'id'
> > })
> > ```
> 
> This is invalid syntax. What would be the purpose of 'id' ?

```js
myModel.findAll({
    attributes: [
         'id',
         [sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']
    ]
})
```
This worked for me.

**Comment by uzair004** [comment]
the 'alias_name' doesn't work for me when its different then 'col_name'

**Comment by AnechaS** [comment]
> > > try this
> > > ```ts
> > > myModel.findAll({
> > >      attributes: [[sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']],
> > >      'id'
> > > })
> > > ```
> > 
> > 
> > This is invalid syntax. What would be the purpose of 'id' ?
> 
> ```js
> myModel.findAll({
>     attributes: [
>          'id',
>          [sequelize.fn('DISTINCT', sequelize.col('col_name')), 'alias_name']
>     ]
> })
> ```
> 
> This worked for me.

@serlapteff correct. I forget to move the field "id" into the attributes

**Comment by chornbeRecurve** [comment]
If you know the fields - clearly you do - just bang a raw query to get the minimal information you need; it's far more efficient and you don't have to use any of this wonky syntax listed above.
