### ISSUE TITLE
Error: Invalid Instance definition. Only one autoincrement field allowed.

### ISSUE THREAD

**Issue by TangMonk** [sequelize/sequelize#2999]
```coffeescript
module.exports = (sequelize, DataTypes) ->

  List = sequelize.define 'List',
    order:
      type: DataTypes.INTEGER
      autoIncrement: true
```

this above alert me error:

```
Error: Invalid Instance definition. Only one autoincrement field allowed.
```

**Comment by mickhansen** [comment]
You have not defined a primaryKey by the looks of it. Sequelize will then add the default AI PK `id` and that is throwing the double AI error.

If you want a field that is AI but not the PK you need to define your own PK using a UUID type.
If order is meant to be the primary key, please add `primaryKey: true`

**Comment by TangMonk** [comment]
@mickhansen thanks , i am sorry for my stupid :(

**Comment by Americas** [comment]
@mickhansen What if my primary key is a foreign key added by association? I cannot make a field AI because it throws this error.

**Comment by janmeier** [comment]
@Americas please provide some more detail. How does the association add a primary key?

**Comment by Americas** [comment]
Well, the model can't, but the database can, and the validation can be done on the DB.

Maybe I should ask how to make a field AI in a model with no PK.

**Comment by eugeneshemonaev** [comment]
What if need to have two auto increment fields - `id` is primary key which starts from 1 and `orderNumber` which starts from 1000 and its not primary?

**Comment by Khuzha** [comment]
@mickhansen, @janmeier, hey guys! But what if we really need two AI in integer? E.g. Postgres allows that, but I'm not able to use it right now with Sequelize, even if I specify id as primarykey and add other field, that needs to be an integer and to have AI
