### ISSUE TITLE
scopes does not work

### ISSUE THREAD

**Issue by khaldoun1** [sequelize/sequelize#3001]
Im trying v2.0.0 rc8, and I found that scopes does not work unless a default scope is defined in the model definition, which in my case is not needed, here is what I'm doing.

```javascript
.
.
defaultScope: { where: {} },
scopes: {
    isSomething: {where: someKey: 'blablabla'}
}
.
.
```
the problem occurs when I try to get the data of this model through another one which has a realtion with, then the defualt scope is applied but with an incorrect query criteria, somethimg like this
```sql
.... WHERE (`args` IN {} )
```
any help is highly appreciated

**Comment by rbudiharso** [comment]
+1, also having this problem, in my case defining defaultScope in the model produce this bug

**Comment by marcus** [comment]
I'm not sure why a default scope is required:

https://github.com/sequelize/sequelize/blob/5be311997d5a07030ba62d9df1ab77ec52be415f/lib/query-interface.js#L674

There may be more to this, but it seems like checking for a defaultScope could be avoided altogether. If there's not a reason to require defaultScope, I can create a PR to change this.

**Comment by nkt** [comment]
Scopes still doesn't works at all.

**Comment by marcus** [comment]
@nkt it works, just make sure you have a default scope.

**Comment by Belciu** [comment]
Scopes still doesn't work if you use Sequelize.and or findOne even with the defaultScope, for example:
If we define 
```javascript
var Session = sequelize.define('sessions', {
        id: DataTypes.STRING(255),
        payload: DataTypes.TEXT,
        last_activity: DataTypes.INTEGER(11).UNSIGNED
    }, {
        timestamps: false,
        defaultScope: { limit: 1},
        scopes: {
            getPayload: function(sid, session_lifetime) {
                return {
                    attributes: ['payload'],
                    where: Sequelize.and([id: sid], ['UNIX_TIMESTAMP(now())-last_activity < ?*60', session_lifetime]),
                    limit: 1
                }
            }
        }
    });
```
if we try to run it 
```javascript
Session.scope({ method: ['getPayload', 1, 120]}).findOne()
                .then(function(res){
                       console.log('Result: ' + res);
                 }
```
there will be no debug from Sequelize and res will be null, but if we will use findAll 

limit 1 will be ommited and 
```javascript
.... WHERE (`args` IN {?,?} ) 
````
will appear in the query

**Comment by mickhansen** [comment]
There's a bug with defaultScope and `.and()` it seems.

**Comment by Belciu** [comment]
With enabled 'logging: console.log', the .findOne() method used on a scope, it do not push any query debug to the console and it also returns null every time.

**Comment by klaemo** [comment]
Scopes don't work at all for me with v2.0.4. Not even with defaultScope.

**Comment by janmeier** [comment]
@claemo please show some actual code that is not working and tell us how it fails. Does it not apply the scope at all / correctly, is the query wrong etc

**Comment by klaemo** [comment]
sorry, it might have just been a misunderstanding on my part about how scopes work. nevermind!

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
