### ISSUE TITLE
findOrCreate with lock

### ISSUE THREAD

**Issue by chris-rock** [sequelize/sequelize#3002]
As far as I read the code correctly, findOrCreate does not support db locks. Is that correct?

**Comment by janmeier** [comment]
Hmm no it seems that query options are only passed to the create call, not the find.

**Comment by hacker112** [comment]
+1 I am also affected by this.

**Comment by BridgeAR** [comment]
At least 3.0 supports locks. So this issue is resolved. It's just not documented yet and it would also be good to have some internal tests for it.
