### ISSUE TITLE
Increment column in many-to-many junction table

### ISSUE THREAD

**Issue by paolodm** [sequelize/sequelize#3003]
In one of my junction tables, I have a column called `ordinal`. It represents the order of the relationship between the two tables. 

![screen shot 2015-01-25 at 8 04 53 pm](https://cloud.githubusercontent.com/assets/247525/5894222/fbcf368c-a4cd-11e4-89f5-fc616afec55a.png)

This column should start from 1 to n, where n is the number of relations. 

This is how I set up the many-to-many relationship in my model:

```js
Survey.hasMany(Section, {through: SectionSurvey, foreignKey: 'survey_id' });
Section.hasMany(Survey, {through: SectionSurvey, foreignKey: 'section_id'});
```

Of course, by default, this column is defaulting to null. Is there a setting in the model that will allow me to auto-increment this table?

**Comment by mickhansen** [comment]
Not by default no.
You could probably set on a `beforeCreate` hook on `SectionSurvey` and fetch the latest num and use that.

**Comment by BridgeAR** [comment]
You've already defined your through model. It should be enough to add the [auto-increment] (http://sequelize.readthedocs.org/en/latest/api/sequelize/#definemodelname-attributes-options-model) flag in your definition, or I'm missing the point here.

**Comment by janmeier** [comment]
@BridgeAR as I recall it is only possible to have a single auto increment column, at least in mysql. But @paolodm How about marking the ordinal column as primary key and adding auto-increment to it?

**Comment by BridgeAR** [comment]
@janmeier Well it seems to me that there's only one field auto-incremented. The other two are UUIDs :D

**Comment by janmeier** [comment]
No response from @paolodm. Closing
