### ISSUE TITLE
Spurious args added to query string when defaultScope exists in related models.

### ISSUE THREAD

**Issue by Spudley** [sequelize/sequelize#3005]
Using the latest Sequelize (2.0.0-rc8), I have two sequelize models that are linked using `hasMany` -- ie `User.hasMany(models.UserToken)`

So I can get the user tokens like this:

    user.getUserTokens().then(function(tokens) {
        ....
    }

This arrangement works perfectly, until I try to add a `defaultScope` to the related model (ie `UserToken`).

When I add the following to the `UserToken` model:

    defaultScope: {
        where: {
            active: 1
        }
    },

I get the following broken query in the log when I run the same `user.getUserTokens()` method:

    Executing (default): SELECT `id`, `token`, `valid_from`, `valid_to`, `active`, `createdAt`,
    `updatedAt`, `UserId` FROM `UserTokens` AS `UserToken` WHERE `active` = 1
     AND `args` IN (`attribute`= '[object Object]', `comparator` = '=', `logic` = 5, `_isSequelizeMethod` = true,?,?);

I've split it onto three lines for readability; the code on the third line should not be there.

I can work around it by specifying a `where` clause as an argument to the `user.getUserTokens()` call instead, but I was hoping to use `defaultScope` I to avoid repeating myself.

**Comment by mickhansen** [comment]
Looks like a bug. scopes in general need a loving hand.

**Comment by danamajid** [comment]
+1

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
