### ISSUE TITLE
A way to incapsulate the constants in the class object

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#3006]
Hi,

I want to have a set of constants on the class level.
To be able to use them like this:

~~~javascript
var Model = sequelize.define(modelName, modelConfig.attributes, modelConfig.options);
console.log(Model.StatusCodes.SUBMITTED);
~~~

Is there an elegant way to do that?

In the documentation there is a chapter about getters and setters, but, as I understand they are active on the "instance" level. And I want to use them on the class level.

For now I've ended up with the next solution:
~~~javascript
    'options'   : {
        classMethods   : {
            /* it could be that there is a better way to hold the constants inside the class */
            StatusCodes: {
                SUBMITTED: 10
            }
        },
        instanceMethods: {},
        timestamps     : false,
        tableName      : 'statuschange',
        freezeTableName: true,
        thrift         : 'Statuschange'

    }
~~~

The thing which confuses me is, that the section is called *classMethods*.

Any thoughts?

Regards,

**Comment by mickhansen** [comment]
`classMethods` is kind of an outdated construct in my opinion. It merely adds the properties to the Model.
You could just as well do `Model.StatusCodes = {}`.

**Comment by PavelPolyakov** [comment]
The thing is that I have a unified models initiator. Which grabs the options and configs and then instantiates the models. So for me it would be better if there is some configuration inside the options object.

But thanks for the opinion.

**Comment by mickhansen** [comment]
Well there's `classMethods` if you want to do it that way.

**Comment by lekhnath** [comment]
In es6 I use the following:

{
    classMethods: {
        get SELECTABLES() {
            return 'some value';
        }
    }
}

should I avoid this ?
