### ISSUE TITLE
Eager loading with where clause returns null when nothing is found

### ISSUE THREAD

**Issue by MtDalPizzol** [sequelize/sequelize#3008]
In my app, a user can have more than one email address, but only one of those is set as the main email. When I try to get the user including only the email which are not the main email and the user has only the main email registered in the database, I was expecting to get the user data and no emails at all. Instead, I'm getting no data at all. I think this is a bug because when I set the where clause to ``` { main: true } ``` it works like expected. I'm using Postgres.

```javascript
User.find({
    where: {
        id: req.params.userId
    },
    include: [{
        model: Email,
        where: {
            main: false
        }
    }]
}).then(function(user) {
    console.log(user); // null
});
```

**Comment by mickhansen** [comment]
`where` automatically sets it to an INNER JOIN, use `required: false` to have it be a left join again.

**Comment by MtDalPizzol** [comment]
Thank you! It worked! I'm closing this. Is this documented somewhere? I looked up the docs again and I can't find this...

**Comment by mickhansen** [comment]
@MtDalPizzol in the api reference, probably not in the main docs yet.
