### ISSUE TITLE
DBERROR : Schema "Table" not found when using RC7+ of sequelize using postgreSQL, postgreSQL schemas,  and "include" feature on findAll 

### ISSUE THREAD

**Issue by josdewitte** [sequelize/sequelize#3011]
Using findAll on a model with postgres schema name and underscored table name, and using the "include" feature on this findAll statement results in incorrect SQL, since the "AS [modelInstanceName]" cannot be used in the SELECT query at the same time.

**Comment by josdewitte** [comment]
For model.A.findAll({where: { 'x': 2 }, include: [{ model: model.B, as:'bAlias'}]})

The SQL returned is

SELECT A.a, A.b, A.c FROM schemaname.table_name WHERE A.x=2 AS A LEFT OUTER JOIN B AS bAlias ON A.id=B.Aid;

You cannot use A inside the same statement; you should use (SELECT a,b,c  FROM schemaname.table_name WHERE x=2) AS A LEFT OUTER JOIN .....

**Comment by mickhansen** [comment]
Generally table aliases are available to the rest of the select query. Is it different when using schemas?

**Comment by mickhansen** [comment]
Although `FROM schemaname.table_name WHERE A.x=2 AS A` does not look like sequelize SQL, there's no code that should generate a WHERE before any of the joins or aliases.

**Comment by josdewitte** [comment]
You are correct. I simply cleaned up a complex existing query for brevity, indeed the where is behind the LEFT OUTER JOIN

**Comment by josdewitte** [comment]
Removing the aliases  A and B results in a working query.

**Comment by mickhansen** [comment]
Very strange that table aliases don't work the same way when using schemas, do you have any resources on this?

**Comment by josdewitte** [comment]
I have found the culprit. I is not the aliasing but the ORDER BY clause that uses ORDER BY "A.B.index". Sequelize first creates the A.B alias, then tries to use "A.B.Index" in the ORDER BY. This conflicts with PostgreSQL which thinks it is a schema.

**Comment by josdewitte** [comment]
In pre-RC7, i could include for example many-to-one B and order by "B.index"; 

actual code:

 self.model.Route.findAll({where:{id > 0}, include: [{ model: self.model.Sector, as:'sector'}], order: [['sector.index','ASC'],['number','ASC']] });

However the "Route" table alias in the SQL query now creates "Route"."sector"."index"

**Comment by josdewitte** [comment]
SELECT * FROM "geography"."tbl_routes" AS "Route" LEFT OUTER JOIN "geography"."tbl_sectors" AS "sector" ON "Route"."sector_id" = "sector"."id" AND "sector"."deleted_at" IS NULL WHERE ("Route"."deleted_at" IS NULL AND "Route"."id">0) ORDER BY "Route"."sector"."index" ASC, "Route"."number" ASC;

**Comment by josdewitte** [comment]
The "Route"."sector"."index" is not supported by postgreSQL that thinks it is a schema. How should I adapt the order clause in the findAll statement?

**Comment by mickhansen** [comment]
```
order: [
  [{ model: self.model.Sector, as:'sector'}, 'index', 'ASC']
]
```

**Comment by josdewitte** [comment]
WOW. That is some pretty advanced order syntax, and, indeed, it works.
Is this in the docs?

**Comment by mickhansen** [comment]
http://sequelize.readthedocs.org/en/latest/docs/models/#ordering-eager-loaded-associations

Yeah it's a bit tricky. But it's to provide the right naming across schemas and everythingwhen using includes :)

If you hadn't aliased the relation you could simply use `[self.model.Sector, 'index', 'ASC']`

**Comment by josdewitte** [comment]
Thx anyway!. I'll close this then.

**Comment by josdewitte** [comment]
One last question: If I remove aliasing it fails with "Sector is not associated to Route!"

Definition in Route:

Route.belongsTo(models.Sector, { as:'sector', foreignKey : 'sector_id'});

In Sector:

Sector.hasMany(models.Route, { as:'routes', foreignKey : 'sector_id'});

Is the error correct? I can just add the aliasing again and everything works, but just for your consideration..

**Comment by mickhansen** [comment]
It's intended yes. If you use an alias on the association you have to use it on the include and the order aswell.
It's to distinguish multiple relations between the same models.

**Comment by josdewitte** [comment]
Ok! Thx!
