### ISSUE TITLE
Any plans on supporting Oracle? [Question]

### ISSUE THREAD

**Issue by renatoargh** [sequelize/sequelize#3013]
After reading this; https://strongloop.com/strongblog/official-node-js-connector-oracle-database/ I wonder if you guys have any plans on supporting oracle!?

**Comment by mickhansen** [comment]
We'd like to support it, but it's not our highest priority currently.
Ideally someone outside the core team could take the first steps to integrating it.

**Comment by jclohmann** [comment]
I'm also interested in this. Any news about #1836?

**Comment by janmeier** [comment]
Haven't heard more about #1836 - ping @timezra

**Comment by grabbou** [comment]
If anyone with Oracle experience is willing to implement a driver for it - let me know, we can fork the master branch and start together.

**Comment by lebretr** [comment]
Hi,

I have developped a little Oracle support on sequelize 1.7.x (https://github.com/lebretr/sequelize-oracle/tree/1.7.0-Oracle-dev) with node-oracle driver (https://github.com/joeferner/node-oracle). The official Oracle driver not existed yet.

In my fork, only DML work but without bulk and transaction.
This support is not perfect and not complete but it is suits our needs. 

Maybe this (https://github.com/lebretr/sequelize-oracle/pull/1/files) can help you for integrate Oracle.

**Comment by kozervar** [comment]
Actually Oracle released official driver for their DB. (https://github.com/oracle/node-oracledb) Downside is that they support NodeJS in v. <= 10.x. (Issue: https://github.com/oracle/node-oracledb/issues/2)
node-oracle (https://github.com/joeferner/node-oracle) is deprecated.

**Comment by advancedits** [comment]
@lebretr any chance you modify your fork to use node-oracledb instead of node-oracle?

**Comment by janmeier** [comment]
Closing this issue

To anyone stumbling across this, we would definitely be interested in adding oracle support, if someone pledges to implement and provide support for it.

We'd also need some way to test oracle on travis.

If someone is open for the challenge, please open a new issue if you have specific questions, or post them on IRC
