### ISSUE TITLE
ORDER BY applied incorrectly with nested includes

### ISSUE THREAD

**Issue by marcus** [sequelize/sequelize#3015]
I'm trying to get the last few files like this:
```
db.files.findAll(
      {
        where: {
          id: id,
          company_id: company_id,
        },
        include: [
          {model: db.datasource, include: [db.job]}
        ],
        limit: 4,
        order: 'created_at DESC'
      }
    )
```
It generates a query like this:
```
SELECT "filesToMap".*, [... AS ...]
FROM (SELECT "files"."id", [...COLUMNS... ]
      FROM "files" AS "files" WHERE "files"."company_id"='1659' LIMIT 4) 
  AS "files" LEFT OUTER JOIN "datasources" AS "datasource" ON "files"."datasource_id" = "datasource"."id" 
  LEFT OUTER JOIN "jobs" AS "datasource.jobs" ON "datasource"."id" = "datasource.jobs"."datasource_id" 
ORDER BY created_at DESC;
```
Notice the created_at is at the end, it should be after the LIMIT 4. I end up getting the first files rather than the last.

**Comment by mickhansen** [comment]
Hi @marcus 

This might be a bit confusing but the syntax you're using is for raw orders so we don't know where to place it.

If you use:

```js
order: [
  ['created_at', 'DESC']
]
```

We know that you mean `created_at` on the main table and it will be inside the subquery.

**Comment by marcus** [comment]
Huh. Yes, that is confusing but it works! Thank you very much for answering!

**Comment by mickhansen** [comment]
Yes but thats because `order: string` is use literally.
