### ISSUE TITLE
Relative import is broken

### ISSUE THREAD

**Issue by natevw** [sequelize/sequelize#3016]
The relative import code at https://github.com/sequelize/sequelize/blob/4294b4c83603a15d3b633a1ad9187a53e8b14dba/lib/sequelize.js#L606 relies on a stacktrace containing its caller as item `[1]`.

This was broken by https://github.com/sequelize/sequelize/commit/29a7954954756ac049a3f1a8f8fada685b1c3daf#diff-50e3aa130a4f97a42ee2cf111c7b1d9dL474 and then further confused by https://github.com/sequelize/sequelize/commit/d09e876410781eaa89c8af1aef9580f14dbf314d#diff-50e3aa130a4f97a42ee2cf111c7b1d9dL476 — because the `Error.captureStackTrace` is no longer getting passed the stack grabbing function as its second argument, the grab function does not get filtered out and so the whole stack is shifted from where the import code (and any other use) expects it.

The fix in util.js looks something like:

```
  stack: function _stackGrabber() {
    var orig = Error.prepareStackTrace;
    Error.prepareStackTrace = function(_, stack) { return stack; };
    var err = new Error();
    Error.captureStackTrace(err, _stackGrabber);
    var errStack = err.stack;
    Error.prepareStackTrace = orig;
    return errStack;
  },
```

…but any fix should also include a test, seemingly.

**Comment by mickhansen** [comment]
@natevw most fixes should include a test to make sure we don't have regressions.
However we don't have any tests for import currently, as it is hard to test for.

I would welcome a PR and we can manually try out a few cases to make sure it works.

**Comment by briandamaged** [comment]
Seems like it will only be necessary to unit test the 'stack' function to verify this fix.

In terms of testing the 'import' function: do you mind if we simply expose the DataTypes object from the Sequelize class?  This way, the unit tests will be able to access the DataTypes object, which will make it easier to verify the behavior of the 'import' function.  Thoughts?

**Comment by mickhansen** [comment]
@briandamaged data types are already exposed on the Sequelize object.

**Comment by natevw** [comment]
Right, I was referring to a unit test for the stack function as being easier. Sorry if that was unclear.

**Comment by briandamaged** [comment]
@natevw : Gotcha.  Well, good news, then: I just added a unit test for Util.stack()

@mickhansen : Ah -- I didn't notice that the DataTypes object was available through sequelize_instance.dialect.DataTypes.  (Basically, I was looking for an object that housed the DataTypes definitions without any extra clutter)
