### ISSUE TITLE
IDs coming back as null in promise objects after recent creation of new instances

### ISSUE THREAD

**Issue by erikreppen** [sequelize/sequelize#3017]
I've been having a lot of problems with (I thought `bulkCreate` specifically) where after creating new instances, all the IDs come back null in the .then callback's first parameter. When I check the DB they're populated. I thought maybe it was strictly `bulkCreate` but just recently I'm creating a new instance:

<pre><code>
		models.User.findOne(id)
		.then( function(user){
			models.Classregistration.create( { SectionId:section.id,UserId:user.id, completion_status:'active' } );
			res.redirect('/courses/active_courses/');
		} );
</code></pre>

Then we get to active courses and I query for all registered classes. I thought I would have to bounce through a long chain of 1 to many relationships via foreing keys to get to get from one table to the next to get to the actual course information I needed but then I noticed they were all included automatically when I logged just the course_registration results, so I did this:

<pre><code>
router.get('/courses/active_courses', checkAuth, function(req, res) {

	models.Classregistration.findAll({ where:{ UserId:req.session.user.id, completion_status:'active' } })
	.then(function(regItems){
		console.log(regItems);
		var courses = regItems.map( function(el){
			var now = new Date();
			if(true){//( (el.section.start < now) && (now < el.section.end) ){
				return el.course;
			}
		} );
		res.render('courses/active_courses', { classes:courses } );
	} );

} );
<code></pre>

This duplicates quite some time after registering the class and server launch. PG admin shows IDs populated. That `console.log` of regItems shows a bunch of associated IDs with the course table data but the Courseregistration IDs are all null.

<pre>
[ { dataValues:
     { id: 1,
       completion_status: 'active',
       createdAt: Tue Jan 27 2015 18:19:18 GMT-0600 (Central Standard Time),
       updatedAt: Tue Jan 27 2015 18:19:18 GMT-0600 (Central Standard Time),
       UserId: 4,
       ClassregistrationId: null,
       SectionId: 1 },
...
</pre>

Some things worth noting:

* I've only tested in postgres
* pg admin seems awfully crappy/slow. I always have to refresh to see the current state of data. If that's not normal, there may be an issue with my config or something, but I've seen people say unkind things about pgAdmin so this seemed normal. Still not sure why my callbacks come back with unpopulated IDs though.
* My issues with bulk create were happening just after syncing, before the webserver launched. This new one is not though.
* It's a somewhat complex DB but there's almost no data in it at this time. The chain of foreignKeys I mentioned is through like 6 tables.
* I've tried a lot of the stuff that comes up on a casual google that seems vaguely relevant but mostly over a year old.
* I updated recently but not sure that means the latest version is in use based on returns from a version check which was way TMI by the way

**Comment by mickhansen** [comment]
Can you provide a piece of isolated code with models etc that shows the issue?

For `bulkCreate` to return ids with postgres you need to use the `returning: true` option.

**Comment by janmeier** [comment]
Please comment with your model definitions and a piece of bulkCreate code showing the issue. And as commented, remember to check that `returning` is true
