### ISSUE TITLE
Model.count returning NaN because Mysql returns an empty string

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#3019]
### Problem

`Model.count` is returning `NaN` because Mysql returns an empty string when grouping.

```MySQL
SELECT count(*) AS `count` FROM `Model` AS `Model` WHERE (`Model`.`deleted_at` IS NULL AND `Model`.`a_model`='Post' AND `Model`.`a_foreign_key`=186);
# count: 0
```

```MySQL
SELECT count(*) AS `count` FROM `Model` AS `Model` WHERE (`Model`.`deleted_at` IS NULL AND `Model`.`a_model`='Post' AND `Model`.`a_foreign_key`=186) GROUP BY `Model`.`user_id`;
# count: ''
```

If there are values to group up, everything works as expected, but if not, MySQL returns an empty string instead of a `0` (zero).

### Solution

Return parsed Int, or `0` at [queryInterface](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L734);

**Comment by BridgeAR** [comment]
Would you be so kind and check if your issue still persists and if, if my linked fix fixes the issue?

**Comment by janmeier** [comment]
@cusspvz What result do you expect - a count for each group, or the number of groups?

Asuming:

| user_id |
| --- |
| 1 |
| 1 |
| 1 |
| 2 |
| 2 |

Do you want
```js
[{ user_id: 1, count: 3 }, { user_id: 2, count: 2}]
```

Or 2, the number of groups (which is guess is equal to `COUNT DISTINCT user_id`)

**Comment by cusspvz** [comment]
@BridgeAR 
> @cusspvz Would you be so kind and check if your issue still persists and if, if my linked fix fixes the issue?

Think your PR fixes this issue.

@janmeier
> @cusspvz What result do you expect - a count for each group, or the number of groups?

Honestly i din't quite remember, but after checking our internal issue related with this and the image it had, i think it is the number of users with entries with the polymorphed model.

![captura de ecra 2015-03-4 as 17 56 37](https://cloud.githubusercontent.com/assets/3604053/6489646/e8b3d656-c297-11e4-809d-d6d5ce6d85da.png)

Problem was on `mysql` returning an empty string instead of zero, you can check that behavior with `mysql-client`.
