### ISSUE TITLE
[Question]: db:migrate doesn't work second time after resynchronizing db to old schema (not via undo)

### ISSUE THREAD

**Issue by bitwit** [sequelize/sequelize#3020]
I don't believe my issue to be a bug necessarily, but I'm wondering if something in my understanding is missing or the documentation could be improved to clarify:

- If I create a new migration file and then run `db:migrate` via the cli, I see the change made to my db (in this case it is removing a column)
- Next, I run a handy 'syncdb' command which is a sequlize.sync({force:true}) operation followed by using sequelize-fixtures to repopulate the tables
- If I run `db:migrate` a second time now, the column isn't removed. However, if I change the name of the migration file (i.e. adjust the date stamp in any random way; I tried an earlier date) it appears to run and remove the column again.

So I'm wondering is there some information stored somewhere that is saying a particular migration has already run?

I'm having trouble understanding how sequelize knows where any given database stands in the current history of schema changes.

We are using v2.0-RC2 at the moment should any of this be unexpected behaviour.

Thank you

**Comment by mickhansen** [comment]
Hi @bitwit 

Generally once you move to migrations you stop using sync.
But yes, the sequelize migrator stores what migrations it has run in a sequelize_meta table.
So if you run migrations, force sync and want to run migrations again you need to clear the entries from the migrator.

**Comment by bitwit** [comment]
@mickhansen Awesome, this is exactly what I was missing.

Yeah, the sync was just a dev-side testing measure to try and understand what was happening under to hood.

Is there somewhere I can make a pull request to this documentation?
http://sequelize.readthedocs.org/en/latest/docs/migrations/

I think a mention of the SequelizeMeta table would be useful for others in the future who might wonder the same. I tried the links at the bottom of the page but they go to a 404 on Github.

**Comment by mickhansen** [comment]
The migration logic inside Sequelize is deprecated - We officially recommend https://github.com/sequelize/umzug now :)

As for documentation you can do pull requests against the `docs/docs/*` files
