### ISSUE TITLE
how to disable raw sql log?

### ISSUE THREAD

**Issue by TangMonk** [sequelize/sequelize#3022]
log is too much when I run batch tests

**Comment by mickhansen** [comment]
Not an appropriate issue for github.
The information is readily available in the docs.

All you have to do is pass `logging: false` to the options when you init
sequelize

**Comment by TangMonk** [comment]
@mickhansen thanks, I have little confuse of doc

I have read the doc, but the doc said:

http://sequelize.readthedocs.org/en/latest/api/sequelize/index.html?highlight=log

```
[options.logging=console.log]  Type is Function
```

So I am tried to google ,but nothing appeared.

thanks :D
