### ISSUE TITLE
possible to use WITH() ?

### ISSUE THREAD

**Issue by ErikvdVen** [sequelize/sequelize#3025]
This is not an issue, but I'm just curious. I would like to execute such query with sequelize js (So use the postgresql ```WITH``` functionality and select on those results):

```
WITH p AS
( SELECT *, ROW_NUMBER() OVER (PARTITION BY supplier_id ORDER BY id)-1 AS rn
  FROM products
)
SELECT * 
FROM p
ORDER BY rn/2, supplier_id, rn ;
```

Can you tell me this is possible or not? Else I have to execute a raw query, but the current query is already quite big where I would like to add this ```WITH``` to.

**Comment by mickhansen** [comment]
Not supported by Sequelize - You have to use a raw query.

**Comment by ErikvdVen** [comment]
Alright then! Thanks for the info
