### ISSUE TITLE
Associations

### ISSUE THREAD

**Issue by MarcelLZ** [sequelize/sequelize#3028]
I'm creating an association between two tables using hasMany and belongsTo, specifying a name to the foreign key. The resulting target table has two constraints, one of them is the FK I want and the other is being generated automatically by Sequelize.

Example:
var State  = sequelize.define("State", { ... });
var City = sequelize.define("City", { ... });

State.hasMany(City, { foreignKey: 'fk_id_state' });
City.belongsTo(State);

And this implementation's results was:
CREATE TABLE IF NOT EXISTS "city" (
    "id_city"  SERIAL , 
    "nm_city" VARCHAR(255) NOT NULL, 
    "StateIdState" INTEGER REFERENCES "state" ("id_state") 
        ON DELETE SET NULL ON UPDATE CASCADE, 
    "fk_id_state" INTEGER REFERENCES "state" ("id_state") 
        ON DELETE SET NULL ON UPDATE CASCADE, 
    PRIMARY KEY ("id_city")
);

What to do?

**Comment by mickhansen** [comment]
```js
State.hasMany(City, { foreignKey: 'fk_id_state' });
City.belongsTo(State, { foreignKey: 'fk_id_state' });
```

**Comment by Inventti-Marcel** [comment]
Thanks! it work's.
