### ISSUE TITLE
Sequelize 2.0.0-RC8 Crash on insert : Cannot call method '_fulfill' of undefined

### ISSUE THREAD

**Issue by mathieuyocto** [sequelize/sequelize#3030]
We give this error when we try to insert data on DB.

On Seq 2.0.0 RC-7 it's ok.

<pre>

uncaughtException: Cannot call method '_fulfill' of undefined date=Fri Jan 30 2015 07:42:42 GMT+0100 (CET), 
pid=609, uid=1000, gid=1000, cwd=/var/www/clients/bazarmaurice/bazarmaurice.mu, 
execPath=/usr/bin/nodejs, version=v0.10.35, argv=[node, /www/seq-test-project/app.js], rss=117014528, heapTotal=95289344, 
heapUsed=68592136, loadavg=[0.0498046875, 0.0556640625, 0.09033203125], uptime=1704498.771336448, trace=[column=38, 
file=/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js, 
function=Promise._settlePromiseAt, line=742, method=_settlePromiseAt, native=false, column=18, 
file=/www/seq-test-project/node_modules/sequelize/lib/promise.js, 
function=Promise._settlePromiseAt, line=76, method=_settlePromiseAt, native=false, column=10, 
file=/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js, 
function=Promise._settlePromiseAtPostResolution, line=335, method=_settlePromiseAtPostResolution, native=false, column=12, 
file=/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/async.js, function=Async._consumeFunctionBuffer, 
line=85, method=_consumeFunctionBuffer, native=false, column=14, file=/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/async.js, 
function=Async.consumeFunctionBuffer, line=40, method=consumeFunctionBuffer, 
native=false, column=13, file=node.js, function=process._tickCallback, line=442, 
method=_tickCallback, native=false], stack=[TypeError: Cannot call method '_fulfill' of undefined,     
at Promise._settlePromiseAt (/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:742:38),     
at Promise._settlePromiseAt (/www/seq-test-project/node_modules/sequelize/lib/promise.js:76:18),     
at Promise._settlePromiseAtPostResolution (/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:335:10),     
at Async._consumeFunctionBuffer (/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12),     
at Async.consumeFunctionBuffer (/www/seq-test-project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14),     
at process._tickCallback (node.js:442:13)]

</pre>

**Comment by mickhansen** [comment]
We'll need a bit more information to help you debug this issue.
But i appears to be an issue with promises.

**Comment by janmeier** [comment]
Closing, please comment with a piece of code showing the issue so we can debug further
