### ISSUE TITLE
Sequelize 1.7.9 calling save() problem

### ISSUE THREAD

**Issue by nomadster** [sequelize/sequelize#3032]
Hi guys, I know 1.7.* isn't the bleeding edge version, but i have this in production (we are planning to upgrade to 2.0.0 when it's ready) and have a bug to fix  :)

The following code

```JavaScript
function modifyUser(usr){
   usr.one_field = 42;
   return usr.save(); 
}

User.build(....)
  .then(function(user){
    return modifyUser(user);
  }).then(function(){
     console.log('Exit from ehere');
  });
```

produces ad UPDATE query, which fails:
```
UPDATE `users_tbl` SET `user_type`='person', ... ,`user_FK_company_id`=1 WHERE `user_id` IS NULL
```
since there is no entry with user_id=NULL on the db.

Should build() create an object that, once we call save() on it, will produce an INSERT??

Am I missing something?
We are using MySQL.

**Comment by mickhansen** [comment]
`build` will by default result in an insert yes. However you can use `Model.build(values, {isNewRecord: false})` to have it trigger an update instead.

**Comment by mickhansen** [comment]
By the way, `build` does not return a promise, so your current code must not be straight from your app, or you would be getting a undefined method then error.

**Comment by nomadster** [comment]
> build will by default result in an insert yes. However you can use Model.build(values, {isNewRecord: false}) 
> to have it trigger an update instead.
...
> By the way, build does not return a promise, so your current code must not be straight from your app

Yep, this in not exactly the code i run :)

I'm doing something like

```JavaScript
sequelize.transaction(function (t) {

Promise.props({
   company: Company.find(id, {transaction:t}),
   user: User.build(fields_but_not_user_id, {transaction: t})
}).then(function(props_Obj){
    return props_Obj.company.customAddUser(props_Obj.user, {transaction:t});
}).then(commitTransaction).catch(revertTransaction);

t.done(DoThingsHere);
}
```
where `props_Obj.company.customAddUser` is an instance method defined in the Company model that does something like

```JavaScript
instanceMethods: {
            customAddUser: function (userInstance, trans) {
                    return Promise.all([
                        retrieveThingUsingPromise....NotSequelizerelated
                     ]).then(function (result) {
                         userInstance.user_graphdb_id = result[0]._id;
                         userInstance.user_FK_company_id = company.company_id;
                         return Promise.all([
                             userInstace.save({transaction: trans}),
                             ...otherThings]);
                      }).then(){
                          ....
                          return Promise.resolve('Hurray!');
                       }).catch(DoSomeThingWithErrors);
              } ...
```


However I'm never getting an INSERT (as I would expect from a `build()`, since it would create a non persisting instance) but am getting the UPDATE, as you can see from MySQL logs

```
794 Connect	xxxxxxxxxxxx
794 Query	SET time_zone = '+0:00'
794 Query	START TRANSACTION
794 Query	SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
794 Query	SET autocommit = 1
795 Connect	xxxxxxxxxxxx
795 Query	SET time_zone = '+0:00'
795 Query	SELECT * FROM `companies_tbl` WHERE `companies_tbl`.`company_id`=1 LIMIT 1
795 Query	UPDATE `users_tbl` SET `user_type`='person', !!!!!user_data_here!!!!!, `user_FK_company_id`=1 WHERE `user_id` IS NULL
794 Query	COMMIT
794 Quit
795 Quit	
```

Any idea?

**Comment by janmeier** [comment]
Build followed by save inserts fine for me. You'll need to provide at more isolated test case for us to debug further

**Comment by nomadster** [comment]
@janmeier are you using 1.7.9 ?

**Comment by janmeier** [comment]
Yes

**Comment by nomadster** [comment]
I think it would be easier if you tell me what do I have to look for, since extracting a coherent isolated test case would be a huge work right now (is not all in one file, is more like a controller which calls a service which spawn a promise chain, which `build()` an User instance and `find()` a Company instance so that later in the chain I'll be able to call the `customAddUser` instance method of that Company)

**Comment by janmeier** [comment]
You have to look for the smallest possible pieces of code that can reproduce the issue. Start from a new file where you load your model, call build and then call save. Does that show them problem? If yes try to strip away as many irrelevant things (instance and class methods, extra attributes etc) until you reach the smallest possible case. 

If it doesn't show the issue you'll need to go bigger, maybe take a small snippet of code from your application and try to reproduce with that

**Comment by nomadster** [comment]
If it's ok, since as far as I understand you are all working to complete 2.0.0, I'll post the snippet as soon as I have enough time :)

**Comment by janmeier** [comment]
Closing this, but feel free to comment if you come up with a testcase @nomadster 

However, we are unlikely to have time to do a lot of work on 1.7

**Comment by nomadster** [comment]
Oh, sorry guys, haven't find enough time to extract a valid snippet of code. By the way we are migrating to 2.0
Thanks for your help, and keep up the good work! :)
