### ISSUE TITLE
Sequelize duplicates column name

### ISSUE THREAD

**Issue by crocodile** [sequelize/sequelize#3035]
I decided to make all my column names lower-case in my MySql table. As I understand there is [no specific standard to follow][1] regarding this, it's just any chosen approach should be kept consistent across the project.

With the following code, the foreign key column sequelize.js (2.0.0-rc2) creates always starts with an upper-case character: 

    Tab.hasMany(Column);  // This creates a "TabId" column as a foreign key

In order to convert this foreign key to lower-case I tried to specify the foreign key manually, as show below. Unfortunately, I ended up with an SQL operation trying to create **two columns with the same name**, which is undesired and fails anyway.

    Tab.hasMany(Column, {foreignKey: 'tabId'});   
    //This creates two columns: 'tabId' and 'TabId'

  [1]: http://stackoverflow.com/questions/5325520/mysql-column-name-standards-conventions

If I specify a foreign key with a different name, the conflict is gone, but I still end up with **two columns**, which means I will have a column I never use:

     Tab.hasMany(Column, {foreignKey: 'tabForeignId'});   
    //This creates two columns: 'tabForeignId' and 'TabId'

**How can I create a lower-case foreign key without such duplications and  conflicts?**

**Comment by mickhansen** [comment]
When defining a foreignKey you also need to define it on the revers relationship assuming you have defined on.

I.e. if you have `Column.belongsTo(Tab);` you need to add `foreignKey: `tabId` to that.

**Comment by janmeier** [comment]
Closing, please comment if you still have issues  after adding the foreign key to both sides of the association

**Comment by peterwiebe** [comment]
if it wasn't already clear, an example for the given code that should work would be:
```
Tab.hasMany(Column, { foreignKey: 'tabId' }
Column.belongsTo(Tab, { foreignKey: 'tabId' }
```
This also cleared up the duplicate column names for me.
