### ISSUE TITLE
Expressjs docs needs update for Sequelize 2.0

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3037]
I was following this expressjs tutorial:
http://sequelizejs.com/articles/express

However, I think that was written before Sequelize changed their inflection library. With Sequelize 2.0, the migration doc say to change all model names to lowercase:
https://github.com/sequelize/sequelize/wiki/Upgrading-to-2.0

**models/user.js**
```
"use strict";

module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define("user", {
    username: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        User.hasMany(models.task)
      }
    }
  });

  return User;
};
```
**models/task.js**
```
"use strict";

module.exports = function(sequelize, DataTypes) {
  var Task = sequelize.define("task", {
    title: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        Task.belongsTo(models.user);
      }
    }
  });

  return Task;
};
```

**routes/index.js**
```
var models  = require('../models');
var express = require('express');
var router  = express.Router();

router.get('/', function(req, res) {
  models.user.findAll({
    include: [ models.task ]
  }).then(function(users) {
    res.render('index', {
      title: 'Express',
      users: users
    });
  });
});

module.exports = router;
```

**Comment by maplesap** [comment]
As a side question, if I have a model with an underscore:

    var doIt = sequelize.define("do_it",{...});

Would I refer to that model as `models.do_it` instead of `models.doIt`?

ie, `User.hasMany(models.do_it);`

**Comment by BridgeAR** [comment]
The outdated examples were removed, so this should probably be closed.
