### ISSUE TITLE
best practice for associating models from POST data?

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3038]
Here's what I'm trying to do. I have the following simple models:

    Name
        name: {type: DataTypes.String, unique: true}
        belongsTo(Person)
    
    
    Person
        hasMany(Name)

A list of names is POSTed to the server, and I want to either query the name or create it if it doesn't exist. Then I need to associate each name with a certain person if the association doesn't already exist.

I came up with this, but it feels naive and I'm not sure how to check if an association exists:

    var names = ["bob", "alice", "sam"];  // Posted to server;
    var person = 1; // Posted to server;

    for (var i = 0; i < names.length; i++) {
        models.Name.findOrCreate({where: {name: names[i] }}).then(function(instance, created) {
            if (instance)
               models.Person.find(id).then(function(person) {
                   // How do I check if name already exists in this person? If it doesn't exist,
                   // person.addName(instance);
               }
        });
    }

Is there a good way to do this in sequelize?

**Comment by mickhansen** [comment]
You should be able to do `person.hasName(instance)`.
But since you're finding the instances directly you could also just check the foreignKey on the names.

**Comment by maplesap** [comment]
Is there a more efficient way of doing what I'm doing in sequelize? Isn't this going to INSERT multiple times if all the names don't exist on the person yet?
    
Also,  can I pass in a list and get rows back? Something like:

```
var names = ["bob", "alice", "sam"];
    models.Names.findAll({where: { names: names }}).then(function(rows) {
            // rows would contain all 
    });
```
