### ISSUE TITLE
SequelizeDatabaseError: ER_EMPTY_QUERY: Query was empty on .save() when no fields changed

### ISSUE THREAD

**Issue by MrVoltz** [sequelize/sequelize#3039]
I have page for editing posts and when user doesn't change anything, Sequelize throws ER_EMPTY_QUERY,
I don't have timestamps enabled.

I think, there should be check in save() method if the data changed, otherwise just return.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L569

Already fixed on master.

**Comment by MrVoltz** [comment]
Still throws ER_EMPTY_QUERY when changing some field to undefined. .changed() returns the modified field, but .save() throws error.

**Comment by mickhansen** [comment]
@MrVoltz Hm alright. In what case are you changing values to be undefined?

**Comment by MrVoltz** [comment]
It was accidentally assigning bad variable, but it is still bug in Sequelize.

**Comment by sushantdhiman** [comment]
**SSCCE Test** 
```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();


var M = sequelize.define('M', {
  name: Sequelize.STRING
}, { timestamps: false });

var l = console.log.bind(console);

sequelize.sync({ force: true })
.then(() => M.create({ name: '7 Eleven' }))
.then((m) => {
  m.name = undefined;
  l(m.changed());
  return m.save({ logging: l});
})
.then((m) => { l(m.toJSON())})
.catch(l);
```

**Output**
```bash
Using database:  sequelize-test-5
[ 'name' ]
Executing (default): 
{ id: 1, name: undefined }
```

**Comment by arjun8624** [comment]
this will happen, when you save model without any changes.
