### ISSUE TITLE
'Application wide model options' through Sequelize constructor not working

### ISSUE THREAD

**Issue by luciano-junior** [sequelize/sequelize#3046]
Hi, 

I was reading the Getting Started documentation [here](http://sequelize.readthedocs.org/en/latest/docs/getting-started/) and I could not reproduce the feature described in the section **Application wide model options**

I wanted to define the option **timestamps** as false through Sequelize constructor. So, that option would be used as default option to all defined models. Finally, I coded this simple Hello world app to try this feature as follows:

```
var Sequelize = require('sequelize');

var sequelize = new Sequelize('postgres', 'postgres', '', {
  host: 'localhost',
  dialect: "postgres",
  port: 5432,
  timestamps: false
});

/*
This way also does not work:

var sequelize = new Sequelize('postgres://postgres:postgres@localhost:5432/postgres', {
    timestamps: false
  });
*/

sequelize
  .authenticate()
  .complete(function(err) {
    if (!!err) {
      console.log('Unable to connect to the database:', err)
    } else {
      console.log('Connection has been established successfully.')
    }
  });

var User = sequelize.define('user', {
  firstName: {
    type: Sequelize.STRING
  },
  lastName: {
    type: Sequelize.STRING
  }
});


User.sync({
  force: true
});
```

After running this code, the tool pgAdmin3  tells me that the table 'users' has been created with the following columns:

```
-- Table: users

-- DROP TABLE users;

CREATE TABLE users
(
  id serial NOT NULL,
  "firstName" character varying(255),
  "lastName" character varying(255),
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE users
  OWNER TO postgres;
```

Here are the versions of my node.js dependencies:

```
"dependencies": {   
    "pg": "^4.2.0",
    "pg-hstore": "^2.3.1",
    "sequelize": "^2.0.0-rc8"
  }
```
I am using Postgresql 9.4.

**Questions**

1 - What am I doing wrong?
2 - Is this a bug?

Thanks!

**Comment by janmeier** [comment]
All default model options should be wrapped in define: `define: { timestamps: false} `

**Comment by janmeier** [comment]
The text in the docs are correct, but the example is wrong, so I see your confusion though
