### ISSUE TITLE
sequelize.query with replacements does not work properly

### ISSUE THREAD

**Issue by kirill-zhirnov** [sequelize/sequelize#3047]
``` js
db.query("select * from auth_resource where parent_id = ?", null, null, [1])
.then(function(rows) {
	console.log(rows);
})
.done();
```

TypeError: Cannot call method 'bulkBuild' of null at [object Object].module.exports.AbstractQuery.handleSelectQuery (./node_modules/sequelize/lib/dialects/abstract/query.js:216:28)

The only way to fix it without patching source codes:
``` js
db.query("select * from auth_resource where parent_id = ?", null, {raw:true}, [1])
.then(function(rows) {
	console.log(rows);
})
.done();
```

Thank you!

**Comment by janmeier** [comment]
This should  be fixed by https://github.com/sequelize/sequelize/pull/2990
