### ISSUE TITLE
Crash when setting boolean values with Sqlite dialect

### ISSUE THREAD

**Issue by hrudham** [sequelize/sequelize#3048]
If I have the following mode defined:

    var Sequelize = require("sequelize");

    module.exports = function(sequelize, DataTypes)
    {
        var Thing = sequelize.define(
            "Thing",
            {
                MyName: DataTypes.STRING,
                MyBoolean: DataTypes.BOOLEAN
            });

        return Thing;
    };

... and then I run the following code elsewhere in my application:

	models.Thing
	    .findOrCreate(
			{
				where: { MyName: 'MyName' },
				defaults: { MyName: 'MyName', MyBoolean: false }
			});

... my application crashes with the following error:

	Possibly unhandled TypeError: Object 0 has no method 'replace'
		at Object.module.exports.QueryGenerator.insertQuery (...\query-generator.js:244:29)

This seems to be directly related to setting the boolean to a specific value; if I take "MyBoolean: false" out of the above code, it doesn't crash (but obviously doesn't do what I need it to either).

**Comment by hrudham** [comment]
Seems to be related to the following lines in `lib/dialects/abstract/query-generator.js`

	if (options.exception) 
	{
		// $ inside value strings are illegal when using $$ as literal strings/delimiters for function bodys
		value = value.replace(/\$/g, '\\$');
	}

According to node-inspector, `value` in this case is actually an integer, hence why it dies.

**Comment by janmeier** [comment]
Cannot reproduce this in latest master. Please open a pull request with a failing test if you still have issues after upgrading

**Comment by janmeier** [comment]
Woops, tested on mysql - bug confirmed

**Comment by janmeier** [comment]
Quick fix - thanks for pointing me at the correct location :)
