### ISSUE TITLE
JSON-like strings in columns of postgres type json

### ISSUE THREAD

**Issue by aslakhellesoy** [sequelize/sequelize#305]
This might be related to #137.

I have a table with a column named `data` and type `json`. I believe the error I'm getting would be similar if the type was `text`.

If I try to `mymodel.update({data: JSON.stringify({info: "Look ma a \" quote"})})`

It ends up double-escaping the string:

```
UPDATE "my_table" SET "data"='{"info":"Look ma a \\" quote"}' WHERE "id"=2
```

This causes a parse exception in the database:

```
ERROR:  invalid input syntax for type json
DETAIL:  Token "quote" is invalid.
```

The correct SQL would have been:

```
UPDATE "my_table" SET "data"='{"info":"Look ma a \" quote"}' WHERE "id"=2
```

I have also seen dots `.` converted to quoted dots. So `http://foo.com` becomes `http://foo'.'com`.

There is something funny going on in some escaping functions, but I'm a little lost about where to start. It would help if there were some low level tests that take a value object as inputs and compares a generated SQL whith an expected one.

Most of the tests are high level end to end ones (good!), but they're a little coarse grained for fixing bugs like this one.

**Comment by haikyuu** [comment]
You can handle JSON types using `'{ "latitude": 65.96669666666666, "longitude": -18.5333 }'`
