### ISSUE TITLE
Eager loading a paranoid model with 'where' clause returns deleted items (2.0rc8)

### ISSUE THREAD

**Issue by ruddct** [sequelize/sequelize#3050]
Eager loading a paranoid model sometimes returns deleted items. Example:
```
this.User = this.sequelize.define('User', { username: DataTypes.STRING }, {timestamps: false});
      this.Task = this.sequelize.define('Task', { title: DataTypes.STRING }, {timestamps: false, paranoid: true});

this.User.hasMany(this.Task);
this.Task.belongsTo(this.User);

// Create and associate some users and tasks, then delete a task

this.User.findOne(
          { where: { id: user.id }}, // Note that this is required for this bug to surface
          { include: [{ model: self.Task, where: { UserId: user.id }}] }
        )
// The above returns deleted tasks
```

This appears to happen when the following conditions are met:
* A where clause is defined for the model being queried (in the above case, User)
* A where clause is included for the eager loaded model (in the above case, Task)

This is happening for me in Postgres, in 2.0rc8.

**Comment by ruddct** [comment]
note for those hitting this issue: A possible mitigation is including deletedAt in your nested where clause:

e.g.
```
this.User.findOne(
          { where: { id: user.id }}, // Note that this is required for this bug to surface
          { include: [{ model: self.Task, where: { UserId: user.id, deletedAt: null }}] }
        )
```

**Comment by janmeier** [comment]
Hmm it seems I can reproduce this even without the where clauses. I think the problem is that the User model is not paranoid: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1797
