### ISSUE TITLE
bulkCreate first item not has createdAt value

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3052]
This is my User Model

```javascript

"use strict";

module.exports = function (sequelize, DataTypes) {
    var User = sequelize.define("User", {
            email: DataTypes.STRING,
            password: DataTypes.STRING
        }, {
            classMethods: {
                associate: function (models) {
                    User.hasMany(models.Purchase);
                    User.hasMany(models.Evaluation);
                    User.hasMany(models.Note);
                    User.belongsToMany(models.Question, {through: models.UserQuestion});
                }
            }
        }
    );
    return User;
};
```

and this is the bulkCreate execute

```javascript

var usersData = [
            {email: 'julio@gmatdudes.com', password: '123'},
            {email: 'christian@gmatdudes.com', password: '123'}
        ];
 models.User.bulkCreate(usersData).then(function () {
           
        });
```

this is after insert the data

![Image of User table](http://i.imgur.com/OhK8L2U.png)

any solution for this issue ?

**Comment by janmeier** [comment]
This seems to work fine for me on mysql on latest master. Which version are you using and which dialect?

**Comment by juliocanares** [comment]
@janmeier  I'm using  "mysql": "^2.5.4"  in my package.json

**Comment by janmeier** [comment]
What sequelize version?

**Comment by juliocanares** [comment]
this is my package.json 

![Image of package json](http://i.imgur.com/BrkgtwK.png)

**Comment by janmeier** [comment]
You might try to update to latest master, but I don't think anything has changed in regard to bulk create since rc8.

Can you provide a PR with a failing test, since I can't replicate the issue with the code you posted?

**Comment by mickhansen** [comment]
No response, closing.
