### ISSUE TITLE
NoSQL Support Possible?

### ISSUE THREAD

**Issue by breandr** [sequelize/sequelize#3053]
I haven't looked into the source (or even started using Sequelize yet for that matter), but I'm wondering if it's possible to make a mapper to NoSQL DB. I'm playing around with AWS and thought it would be really cool if I could just change "postgres" to "dynamo"; let Sequelize do it's thing; and run some benchmarks on the two.

I'm not asking anyone to implement this btw, I"m just asking if it's possible.

**Comment by breandr** [comment]
Nevermind, found #2779.

**Comment by janmeier** [comment]
Nosql support has been discussed before, and we'd really _like_ to support it but realistically no-one from the core team is going to have time to do it. We have plenty of work on our hands supporting the current dialects.


This is not to say we wouldn't accept community contributions, but that person would have to commit to maintaining support going forward
