### ISSUE TITLE
Question about .add .set and transactions

### ISSUE THREAD

**Issue by radoslavpetranov** [sequelize/sequelize#3055]
So say I have a hasMany relationship between ModelA and ModelB. So now I can do like 

```
modelA.addModelB(modelB);
```

My question is whether these methods support passing transactions? So is something like this valid

```
modelA.addModelB(modelB, { transaction : t });
modelA.setModelB([modelB2, modelB3], { transaction : t });
```

The reason I'm asking is that right now I reach a point where I try doing 

```
modelA.addModelB(modelB, { transaction : t });
```

and after waiting a few second I end up hitting 

```
SequelizeDatabaseError: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
```
so I'm not sure if this is a problem where my modelA instance (which was created using ModelA.create({ myData }, { transaction : t }) ) is locking out the addModelB method because it doesn't support transactions and the transaction is not committed yet or I'm doing something else that I'm not aware of.

So yeah - just wondering if the .set and .add build-in methods support transactions or not.

Cheers and thanks!

**Comment by janmeier** [comment]
Just tested on latest master and both set and add seem to work fine with transactions. You'll need to open a pr with a failing test case or provide more detail for us to debug further

**Comment by janmeier** [comment]
No response, closing. Please comment here or open a PR with more info
