### ISSUE TITLE
autoFetch eager associations

### ISSUE THREAD

**Issue by eclipse1985** [sequelize/sequelize#3056]
Hi,

there is a way that I can use for defining the prefetch of associations (for example, directly in the model) instead of specifying "includes" in the find/findAll methods?

For example, in node-orm2 I can do something like this:

```javascript
    autoFetch: true,
    autoFetchLimit: 3
```

in model definition.

**Comment by janmeier** [comment]
Sounds like a good idea to me. This could probably be achieved by extending scopes to cover includes.

Perhaps we need a new issue tracking all the changes needed to scopes so we can do a rewrite @mickhansen ?

**Comment by mickhansen** [comment]
@janmeier scopes definitely need a major overhaul

**Comment by eclipse1985** [comment]
For now, i use this solution:

```javascript
var MyItem = db.define('MyItem', {
			example_property: DataTypes.STRING
		}, {
			classMethods: {
				getIncludes: function() {
					return {
						model: MyOtherModel,
						include: [MyNestedModel]
					};
				},
				findAllNested: function(){
					return this.findAll({include: [ this.getIncludes()]})
				}
			}
		});
```

and outside I call can:
```javascript
Item.findAllNested().then(function(items) {
...
}
```
in this way I can define autofetched relationships once in the model

**Comment by neekey** [comment]
+1

**Comment by neekey** [comment]
For now, I wonder if defaultScope can achieve this feature? Or as the document says scope just affects `findAll` ? 

In my point of view, the main difference between `autoFetch` and `include` is that `autoFetch` will affect every model instance no matter how it is generated ( through `findX` methods, `create`, association methods `getModels` )

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
