### ISSUE TITLE
Association Validation

### ISSUE THREAD

**Issue by randdusing** [sequelize/sequelize#3058]
Apologies if I overlooked something really basic. How do I require an object to have an associated object? For example when creating a new post, it must belong to a specific user. Currently when I create a new Post without a user, no validation messages are thrown and the UserId field is set to null. Is it possible to enforce validations on the association fields?

```javascript
User.hasMany(models.Post, {onDelete: "cascade"});
Post.belongsTo(models.User, {onDelete: "cascade"});
```

**Comment by janmeier** [comment]
Add `foreignKey: { allowNull: false}` to the associations

```js
User.hasMany(Post, {onDelete: "cascade", foreignKey: { allowNull: false}});
Post.belongsTo(User, {onDelete: "cascade", foreignKey: { allowNull: false}});
```

**Comment by randdusing** [comment]
Thanks!

**Comment by DiegoRBaquero** [comment]
Thank you @janmeier . This should be somewhere in the docs
