### ISSUE TITLE
bulkCreate doesn't run individual hooks when passing individualHooks: true

### ISSUE THREAD

**Issue by dmur** [sequelize/sequelize#3060]
When running bulkCreate and passing individualHooks: true as an option, I expected my beforeCreate/beforeValidate hooks to be run.  But that does not seem to be the case.  

I saw in the documentation examples of passing individualHooks: true to update/destroy, but not one for bulkCreate, so I'm not sure if this is expected behavior or a bug.  If expected, it would be good to clarify this in the docs.

Example: 
```
var Event = sequelize.define("Event", {
    [...]
  }, {
    classMethods: {
      associate: function(models) {
        [...]
      },
    },
    hooks: {
      beforeValidate: function(e, fn) {
        console.log("This never outputs");
      },
      beforeCreate: function(e, fn) {
        console.log("This never outputs either");
      }
    }
});
```  
```
  Event.bulkCreate(eventParams, { individualHooks: true })
    .then(function(events) {
      // Do something after bulkCreate
    });
```

using 2.0.0-rc8

Thanks for your help!

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1353

Should work so likely a bug.

**Comment by leonprou** [comment]
I had the same issue, 
checking piece of code you linked I've found in https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1278

```javascript
Model.prototype.bulkCreate = function(records, fieldsOrOptions, options) {

...
    options = Utils._.extend({
      validate: false,
      hooks: true,
      individualHooks: false,
      ignoreDuplicates: false
    }, options || {});
...
if (options.individualHooks) { 
  //run individual hooks
}
```

So if `individualHooks:true` doesn't specified in `options`, bulkCreate will not run the individual hooks.

I assume, from the docs that the default of  `individualHooks` should be true

**Comment by BridgeAR** [comment]
This is fixed in newer versions. @dmur please use sequelize 3.0. And as a hint: beforeValidate won't be called if you do not pass the option `validate: true` ;-)
