### ISSUE TITLE
 Sequelize, Raw Query by Date Range

### ISSUE THREAD

**Issue by juvasquezg** [sequelize/sequelize#3061]
I use "sequelize": "^2.0.0-rc3" with pg (postgresql), in this moment i am trying to do a raw query with date range but sequelize don't return data.

When I run the same query in postgresql db I get correct results. Please Help Me.

In sequilize:

```bash
// Init main query
  var query = "SELECT * FROM" + '"Calls"' +
              " WHERE "  + '"EquipmentId"' + " = 1" +
              " AND " + '"initDate"' + " >= " + "'2015-02-05 14:40' " +
              " AND " + '"endDate"' + " <= " + " '2015-02-05 15:00' ";

  global.db.sequelize.query(query)
  .then(function(calls) {
    console.log(calls);
  })
  .error(function (err) {
    console.log(err);
  });
```

In console of node server I get, squelize say:
```bash
Executing (default): SELECT * FROM "Calls" WHERE "EquipmentId" = 1 AND "initDate" >= '2015-02-05 14:40'  AND "endDate" <=  '2015-02-05 15:00'
```

The query in postgres is:
 ```bash
SELECT * FROM "Calls" 
WHERE "EquipmentId" = 1 
AND "initDate" >= '2015-02-05 14:40'
AND "endDate" <= '2015-02-05 15:00'
```

and i get correct results.

Thank you!

**Comment by juvasquezg** [comment]
The problem is that  sequelize doesn't have the time part. How to do this.

**Comment by janmeier** [comment]
Could you try with latest master, I've done some fixed to raw queries.

You should also be able to write that query in sequelize:
```js
Calls.findAll({
  where: {
    EquipmentId: 1,
    initDate: { gt: Date.UTC(2015, 01, 05, 14, 40) },
    endDate: { lt: Date.UTC(2015, 01, 05, 15, 00) }
  }
});
```

**Comment by janmeier** [comment]
No response

**Comment by juvasquezg** [comment]
Excuse me Please!! 

 This response in Stackoverflow helped me  http://goo.gl/znrK3K 

Thak you so much.
