### ISSUE TITLE
underscored not working for many-to-many self-associations

### ISSUE THREAD

**Issue by eventhough** [sequelize/sequelize#3062]
I am creating a many-to-many self association. I would like to use camel_case for all fields in the database. In my example I am using a simple case where we have a table for people and a join table for friendships. (dialect: postgres)
**person.js:**

``` javascript
exports = module.exports = function(sequelize, DataTypes) {
  var Person = sequelize.define('Person', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    }
  }, {
    underscored: true,
    tableName: 'person',
    classMethods: {
      associate: function(models) {
        Person.hasMany(models.Person, { as: 'newFriend', through: models.Friendship });
      }
    }
  });

  return Person;
};
```

**friendship.js:**

``` javascript
exports = module.exports = function(sequelize, DataTypes) {
  var Friendship = sequelize.define('Friendship', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    sharedHobby: {
      type: DataTypes.STRING,
      field: 'shared_hobby'
    }
  }, {
    underscored: true,
    tableName: 'friendship'
  });

  return Friendship;
};
```

I am expecting a column to be created on friendship called `new_friend_id` since I have underscored turned on. Instead I get this:

| Column | Type | Modifiers |
| --- | --- | --- |
| id | integer | not null default nextval('friendship_id_seq'::regclass) |
| shared_hobby | character varying(255) |  |
| created_at | timestamp with time zone | not null |
| updated_at | timestamp with time zone | not null |
| person_id | integer |  |
| newFriend_id | integer |  |

```
Indexes:
    "friendship_pkey" PRIMARY KEY, btree (id)
    "friendship_person_id_newFriend_id_key" UNIQUE CONSTRAINT, btree (person_id, "newFriend_id")
Foreign-key constraints:
    "friendship_newFriend_id_fkey" FOREIGN KEY ("newFriend_id") REFERENCES person(id) ON UPDATE CASCADE ON DELETE CASCADE
    "friendship_person_id_fkey" FOREIGN KEY (person_id) REFERENCES person(id) ON UPDATE CASCADE ON DELETE CASCADE
```

As you can see, newFriend_id was not camel_cased. Is this a bug?

**Comment by mickhansen** [comment]
Not exactly a bug since you are using alias, the generated foreign key is obviously not ideal but i'm not sure Sequelize could make an accurate guess here. You might want to use `foreignKey: 'new_friend_id'.

**Comment by janmeier** [comment]
Agreed - we recently changed to handling of `as` to be less guesswork, and more 'do what the user told us' . I think it would be too hard to come up with a consistent way of handling undercored and sequelize generated foregin keys. I would suggesting using `foreignKey` as mick mentioned
