### ISSUE TITLE
Question: are hooks can be declared using 2 method at once?

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#3063]
Can I add hooks on a model using 

```javascript
db.User.hook('beforeUpdate', function() { ... }) 
```

with 

```javascript
// Method 1 via the .define() method
var User = sequelize.define('User', {
  username: DataTypes.STRING,
  mood: {
    type: DataTypes.ENUM,
    values: ['happy', 'sad', 'neutral']
  }
}, {
  hooks: {
    beforeValidate: function(user, options, fn) {
      user.mood = 'happy'
      fn(null, user)
    },
    afterValidate: function(user, options, fn) {
      user.username = 'Toni'
      fn(null, user)
    }
  }
})
```

I tested and it does seem to work, but I do not know if it's on purpose or if it's a bug.

**Comment by mickhansen** [comment]
That should definitely be on purpose.
Can you show your actual code?

**Comment by JSteunou** [comment]
Sorry I cannot, but maybe I did something wrong. I'm kind in a rush, I will continue the old way and come back to you later testing the new way I tried.

**Comment by mickhansen** [comment]
Well kind of hard to help you when you don't show actual code.
Hard to say what changed between your actual code that is failing and the contrived example given here :)

**Comment by JSteunou** [comment]
My code does just the same I paste above and I can show actual code because I'm in a company where I'm not allowed to do such things.

**Comment by JSteunou** [comment]
But you said it does not work on purpose so this is not an issue right?

**Comment by mickhansen** [comment]
Actual code is easier to debug. When people show contrived code there's almost always human error.
No it's supposed to work both ways, and pretty sure it does per unit tests :)

It would be helpfull if you were more detailed about exacttly what didn't work, what hook isn't getting called, what's the contents of the Model, etc.

**Comment by mickhansen** [comment]
If you can't show actual production code, atleast show actual code that you have tested and know not to work - It makes it easier for everybody since we can work off the assumption that there wasn't an error in translation.

**Comment by JSteunou** [comment]
Ok I'l tried to provide some.

**Comment by JSteunou** [comment]
Time to show some code (but not too much :p)


### hook like this works very well (got a lot of tests)

*models/index.js* is like the generated one

```javascript
// require stuff
// init sequelize

var db = {};

fs.readdirSync(__dirname)
    .filter(function(file) {
        return (file.indexOf('.') !== 0) && (file.indexOf('_') !== 0) && (file !== basename);
    })
    .forEach(function(file) {
        var model = sequelize['import'](path.join(__dirname, file));
        // register user as User
        db[model.name[0].toUpperCase() + model.name.substring(1)] = model;
    })
;

Object.keys(db).forEach(function(modelName) {
    if ('associate' in db[modelName]) {
        db[modelName].associate(db);
    }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

*models/user.js*

```javascript
module.exports = function(sequelize, DataTypes) {

    var User = sequelize.define('user', {
        email: {},
        firstname: {},
       // classic stuff
    }, {
        timestamps: true,
        classMethods: {
            asyncStuff: function() {
                // return a Promise
            }
        },
        instanceMethods: {},
        hooks: {
            beforeUpdate: function(user, options) {
                // some sync stuff
                user.beforeSavePassword(options);
                // ..

                // + one async stuff that return a promise
                return User.asyncStuff(user, options);
            }
        }
    });

    return User;

};
```

### separated hooks like this fail

And I tried to put the `asyncStuff` away because it can be common to several models. So I tried to do this

*models/_asyncstuff.js*
```javascript

var asyncStuff = function() {
    // return a Promise
};

module.exports = function(db) {

    db.User.hook('beforeUpdate', function(user, options) {
        console.log('====== BEFOREUPDATE');
        return asyncStuff(user, options);
    });

};

```


With the module loaded like this, at the end of *models/index.js*

```javascript

// lot of unchanged stuff

db.sequelize = sequelize;
db.Sequelize = Sequelize;

// load bunch of hooks
require('./_asyncstuff')(db);


module.exports = db;

```

And of course remove the old call in the user hook

```javascript

// lot of unchanged stuff

        hooks: {
            beforeUpdate: function(user, options) {
                // some sync stuff
                user.beforeSavePassword(options);
                // ..

                // + one async stuff that return a promise
                // return User.asyncStuff(user, options);
            }
        }
    });

    return User;

};
```

I'm sorry I had to clean it up a lot and rename things. But that's real code & real bug.

**Comment by mickhansen** [comment]
Does it work with the `db.User.beforeUpdate(function(user, options) {})` syntax?
Whats the contents of db.User.hooks?

**Comment by JSteunou** [comment]
Same issue with the `db.User.beforeUpdate(function(user, options) {})` syntax?

`db.User.hooks` is undefined

Did I call my module at the wrong place / time?

**Comment by mickhansen** [comment]
Sorry try looking in `db.User.options.hooks`

**Comment by JSteunou** [comment]
====== BEFORE { beforeCreate: [Function],
  beforeUpdate: [Function],
  beforeBulkDestroy: [Function] }

====== AFTER { beforeCreate: [Function],
  beforeUpdate: { [Function] '2': [Function] },
  beforeBulkDestroy: [Function] }

**Comment by mickhansen** [comment]
Looks like the hooks are getting adding, they should be called too unless your a short circuiting or similar.

**Comment by JSteunou** [comment]
I just do a user instance update and my test have a chai spy on the asyncStuff function.
