### ISSUE TITLE
Two unique associations

### ISSUE THREAD

**Issue by neoziro** [sequelize/sequelize#3064]
I have two associations on a table and I would like to add a unique index for these two associations. Is it possible? How to do it?

```js
var Click = sequelize.define('Click', {}, {
    classMethods: {
      associate: function (models) {
        Click.belongsTo(models.Notification);
        Click.belongsTo(models.User);
      }
    }
  });
```

I want the couple notification / user to be unique.

**Comment by janmeier** [comment]
Ideally you would be able to do this:
```js
Click.belongsTo(Notification, { foreignKey: { unique: 'user_and_notification'}});
Click.belongsTo(User, { foreignKey: { unique: 'user_and_notification'}});
```
However, unique indexes are only created on model init, not when new attributes are added (__technical detail:__ they are added on model.init, not on model.refreshattributes)

You can define the foreign keys on the Click model however:

```js
var Click = sequelize.define('Click', {
  notificationId: {
    type: Sequelize.INTEGER,
    unique: 'user_and_notification'
  },
  userId: {
    type: Sequelize.INTEGER,
   unique: 'user_and_notification'
  }
});
```

@mickhansen Perhaps this https://github.com/sequelize/sequelize/blob/master/lib/model.js#L153-L181 should be moved from init to refresh?

**Comment by janmeier** [comment]
Ideally you would be able to do this:
```js
Click.belongsTo(Notification, { foreignKey: { unique: 'user_and_notification'}});
Click.belongsTo(User, { foreignKey: { unique: 'user_and_notification'}});
```
However, unique indexes are only created on model init, not when new attributes are added (__technical detail:__ they are added on model.init, not on model.refreshattributes)

You can define the foreign keys on the Click model however:

```js
var Click = sequelize.define('Click', {
  notificationId: {
    type: Sequelize.INTEGER,
    unique: 'user_and_notification'
  },
  userId: {
    type: Sequelize.INTEGER,
   unique: 'user_and_notification'
  }
});
```

@mickhansen Perhaps this https://github.com/sequelize/sequelize/blob/master/lib/model.js#L153-L181 should be moved from init to refresh?

**Comment by mickhansen** [comment]
@janmeier yeah that could probably be doable, have to reset unique and primary key holders too tho.

**Comment by neoziro** [comment]
I do that, is it OK?

```js
var Click = sequelize.define('Click', {}, {
    classMethods: {
      associate: function (models) {
        Click.belongsTo(models.Notification);
        Click.belongsTo(models.User);
      }
    },
    indexes: [
      {fields: ['NotificationId', 'UserId'], unique: true}
    ]
  });
```

**Comment by janmeier** [comment]
Yep, that should be fine as well

**Comment by neoziro** [comment]
OK
