### ISSUE TITLE
Using Lodash 3.x _.matches() cannot filter/find/findIndex to the result Array.

### ISSUE THREAD

**Issue by jchbh-duplicate** [sequelize/sequelize#3068]
I use the 2.0.0-rc3. And when I upgrade by Lodash module to 3.1.0, I find the functions that using _.matches as the filter function will be failed.
Check ChangeLog and Code of Lodash, I find it is because the _.matches() will check hasOwnProperty() of object in array, and when using on the DAO object, which using get() to translate dataValues to direct property access, hasOwnProperty(DAO, datakey) will return false, that cause the function fail to get the result.
Currently I have to hack the Lodash code to remove the hasOwnProperty check for object. But it looks unsafe. Can Sequelizejs change the implements to fit the Lodash 3.x?

**Comment by janmeier** [comment]
Over time we would like to move all access to `get()`, so placing the values directly on the DAO is unfortunately not a possibility. I'd suggest adding a predicate function to your filter that returns `get()`.

I realize this might not be ideal... If you show some of your code we might be able to give suggestions as to how to rework it

**Comment by jchbh-duplicate** [comment]
The workable way is using the long-style match function to done the .matches short-cut actions,
for example: 

In lodash 2.4.x: 

oneModel.findAll({where:{...}).then(function(instances){
   var targetInstance =  _.find(instances, {group: 1}); // it will call .matches() to generate match function. 
})

it is really OK and elegant.

But in lodash 3.1.0, workable version should be 

oneModel.findAll({where:{...}).then(function(instances){
   var targetInstance =  _.find(instances, function(instance){return instance.group === 1});
})

It can work but not elegant.

Looking into the code of Lodash, you can find this is because Lodash 3.x restrict the comparable properties should only belong to the object (by check hasOwnProperty).
 
I also know you concern about the get(). so do I. I am also using the Hook function to add some helper attributes to the instanceObject by the magic of get(). 
Currently I can fork an Lodash and close the check code. But I think it is really a problem if Lodash does not want to change the check logic of _.matches in future versions.

**Comment by janmeier** [comment]
I see your issue, but I also see lodash's desire to only use own properties... Not sure we have a good solution here.

@mickhansen ?

**Comment by janmeier** [comment]
This is not something we are going to change in sequelize, and likely not something that will change in lodash either.
You'll just have to go for the slightly longer version
