### ISSUE TITLE
can i use VIEW with sequelize ?

### ISSUE THREAD

**Issue by neekey** [sequelize/sequelize#3078]
Hi, I'm implementing a simple version system, and I have designed a draft EER diagram（part of it）:

![image](https://cloud.githubusercontent.com/assets/499870/6103478/c04f2140-b07f-11e4-830d-1240046e88bf.png)

As this diagram tells, besides `schema_core`, there are also `schema_content` and `schema_mock` attached to `schema_core`, and each of them need to have a version whenever updated. `schema_version` is just a set of references to `schema_content` and `schema_mock`, and combine two versions into one "schema version".

Now I want to use VIEW to get me the latest "schema version" and combine with `schema_core`.

**Comment by janmeier** [comment]
There is no way to create views on sequelize, but you can create the view manually and query it like a regular sequelize model. 

So you use a raw query to create the view, and query the table using a regular sequelize model:

```js
sequelize.define('schema_content', {
  ...
});
```

Just remember not to `.sync` the schema_content model

**Comment by neekey** [comment]
@janmeier Thank you for sharing your idea. But since I generally use `sequelize.sync() ` to sync all the models, it's a little risky. And what came to my mind suddenly is that there seems lots of restrictions when you try to update a view. So event if I imply your idea, I guess it will not be easy to just use `SchemaContent.create( { .. } );` and then do something like updating attributes and saving it.

**Comment by janmeier** [comment]
I'm not at all familiar with updating a parent table through a view, so can't help you there.

**Comment by neekey** [comment]
So may be the easiest way to do this is just add a `version` column to `schema_core`, and update it whenever `schema_version` updates ? Any better idea?

**Comment by neekey** [comment]
@janmeier Thank you for your sharing : )

**Comment by janmeier** [comment]
@neekey That sounds reasonable, I dont have any better ideas

**Comment by drkstr101** [comment]
`const MyView = sequelize.define('my_view', {});`

>  Error: Table 'mydb.my_view' doesn't exist

Attempting to define a model from an existing view throws the above error. Sequelize 4.24.0 & Maria DB 10.2.10

**Comment by abelosorio** [comment]
See https://github.com/sequelize/sequelize/issues/7197#issuecomment-409277244

**Comment by mariusa** [comment]
Hi, with one model, would it be possible to READ from a view, and have write operations to the table, as usual?

**Comment by soonsam123** [comment]
> 
> 
> Hi, with one model, would it be possible to READ from a view, and have write operations to the table, as usual?

In my case I need to set the name of the database at runtime and also I need to write to the table and read from the view. For that I changed my model to get those fields at runtime.

`models/liberacoes.js`
```
module.exports = (sequelize, DataTypes, nomeTable = "liberacoes") => {
  class Liberacoes extends Model {}
  Liberacoes.init(
    {
      horario: DataTypes.DATEONLY,
      ....
    },
    {
      sequelize,
      modelName: nomeTable,
      timestamps: false,
    }
  );
  return Liberacoes;
};

```

When reading data I pass the **name of the view** as a parameter

```
      const liberacoes = await Liberacoes(
        sequelize,
        Sequelize.DataTypes,
        'view_liberacao'
      ).findAll();
```

When writing data I just leave the default, which is the **name of the table**

```
      const liberacao = await Liberacoes(sequelize, Sequelize.DataTypes).create(...);
```

**Comment by KeyOnTech** [comment]
Hi saw this thread and figured it out if this is still an issue for anybody...
going to try and explain best i can
first create a model file with the fields you need from your view, in this model there has to be a primary index...

sequelize/model/view_model_vwloginslist.js

const Sequelize = require('sequelize');
const sequelize = require('../database/connection');
module.exports = sequelize.define("vwloginslist",
    {
        loginid: {
            field: 'id',
            type: Sequelize.INTEGER,
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
        },
        name: {
            type: Sequelize.STRING(255),
        },
        login: {
            type: Sequelize.STRING(255),
        },
        roledescription: {
            type: Sequelize.STRING(255),
        },
    },
    {
        timestamps: false,
    }
);

**Comment by KeyOnTech** [comment]
next make a migration file, the special thing about this file is you will delete the table model auto created by sequelize then create or replace the view with the same name.  Once this is done you will be able to do a findAll against the model because it will call the view

20200102010201-vwloginslists_create_view_delete_model_table.js


/*
  * create new migration file and name
npx sequelize migration:create --name create_view_vwloginslist

  * run all 
npx sequelize db:migrate

  * run single - from here to there in files list
npx sequelize-cli db:migrate --from 20170316142544-create-an-index.js --to 20170421112638-do-some-refactor.js

  * undo single
npx sequelize db:migrate:undo

  * undo all
npx sequelize db:migrate:undo

*/
'use strict';
const sequelize = require("../database/connection");
/*** 
if you are using views make sure you add the s to the end of the name below in proper grammer format and this way you will
auto delete the model on sync

migrations file no mvw just vw name, add the s to the end for proper grammar
  vwLoginsLists
      ex:
      20200102010201-vwloginslists_create_view_delete_model_table.js
      const view_name = 'vwloginslists';


models file no s, s will automatically be added 
  vwLoginsList
  s will automatically be added 
    ex:
      vwloginslist.js
      module.exports = sequelize.define("vwloginslist",
      vwloginslist.js

now on your routes you can use the vw model file to do a findAll
    ex:
      loginsroles-routes.js
      const vwLoginsList = require('../sequelize/models/vwloginslist');
      await vwLoginsList.count()
      return vwLoginsList.findAll(
        whereCondition
      )

 */
/*** this is only used for views if this is not related to a view delete these sections --- start */
const auto_created_model_table_name = 'vwloginslists';
/*** this is only used for views if this is not related to a view delete these sections --- end */
const view_name = 'vwloginslists';
const original_query = "SELECT "
  + " logins.id, logins.name, logins.login, logins.loginenabled, logins.role,  "
  + " CASE "
  + " WHEN logins.loginenabled = 0 THEN 'DISABLED' "
  + " WHEN logins.loginenabled = 1 THEN 'ENABLED' "
  + " END AS loginenableddescription, "
  + " loginroles.description AS roledescription  "
  + " FROM logins "
  + " LEFT JOIN loginroles "
  + " ON loginroles.id = logins.role "

const new_query = "SELECT "
  + " logins.id, logins.name, logins.login, logins.loginenabled, logins.role,  "
  + " CASE "
  + " WHEN logins.loginenabled = 0 THEN 'DISABLED' "
  + " WHEN logins.loginenabled = 1 THEN 'ENABLED' "
  + " END AS loginenableddescription, "
  + " loginroles.description AS roledescription  "
  + " FROM logins "
  + " LEFT JOIN loginroles "
  + " ON loginroles.id = logins.role "

module.exports = {
  up: function (database, Sequelize) {
    return Promise.all([
      /*** this is only used for views if this is not related to a view delete these sections --- start */
      sequelize.query(`DROP TABLE IF EXISTS ${auto_created_model_table_name}`)
        .then(result => {
      /*** this is only used for views if this is not related to a view delete these sections --- end */
          sequelize.query(`CREATE OR REPLACE VIEW ${view_name} AS ${new_query}`)
            .then(result => {
                return result
            })
      /*** this is only used for views if this is not related to a view delete these sections --- start */
        })
      /*** this is only used for views if this is not related to a view delete these sections --- end */

    ]);
  },
  down: function (database, Sequelize) {
    return Promise.all([
      sequelize.query(`DROP TABLE IF EXISTS ${auto_created_model_table_name}`)
        .then(result => {
          sequelize.query(`CREATE OR REPLACE VIEW ${view_name} AS ${new_query}`)
            .then(result => {
                return result
            })
        })
    ]);
  }
};

**Comment by KeyOnTech** [comment]
last step go to your route file and here's is how you can now findAll

const vwLoginsList = require('../sequelize/models/view_model_vwloginslist');
                await vwLoginsList.count(
                    whereConditionCount
                )

or
                    return vwLoginsList.findAll(
                        whereCondition
                    )

or etc...

**Comment by KeyOnTech** [comment]
next npm run start to auto create all the models and tables
stop the node server
next run sequelize migration to clean up the auto created tables and create your view for you
npx sequelize db:migrate

now start your server again npm run start and your findAll should work great

hope this helps the next person or myself in the future

Note to future self... your awesome and its all gonna be worth it one day :)

**Comment by RomanShabanov** [comment]
To whomever is struggling to read @KeyOnTech's tutorials:

1. Create a model file with the fields you need from your view, in this model there has to be a primary index.

```JavaScript
// sequelize/model/view_model_vwloginslist.js;

const Sequelize = require("sequelize");
const sequelize = require("../database/connection");
module.exports = sequelize.define(
  "vwloginslist",
  {
    loginid: {
      field: "id",
      type: Sequelize.INTEGER,
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: Sequelize.STRING(255),
    },
    login: {
      type: Sequelize.STRING(255),
    },
    roledescription: {
      type: Sequelize.STRING(255),
    },
  },
  {
    timestamps: false,
  }
);
```

2. Next make a migration file. The special thing about this file is you will delete the table model auto created by sequelize then create or replace the view with the same name. Once this is done you will be able to do a findAll against the model because it will call the view.

```JavaScript
// 20200102010201-vwloginslists_create_view_delete_model_table.js

"use strict";
const sequelize = require("../database/connection");
/***
if you are using views make sure you add the s to the end of the name below in proper grammer format and this way you will
auto delete the model on sync

migrations file no mvw just vw name, add the s to the end for proper grammar
vwLoginsLists
ex:
20200102010201-vwloginslists_create_view_delete_model_table.js
const view_name = 'vwloginslists';

models file no s, s will automatically be added
vwLoginsList
s will automatically be added
ex:
vwloginslist.js
module.exports = sequelize.define("vwloginslist",
vwloginslist.js

now on your routes you can use the vw model file to do a findAll
ex:
loginsroles-routes.js
const vwLoginsList = require('../sequelize/models/vwloginslist');
await vwLoginsList.count()
return vwLoginsList.findAll(
whereCondition
)

/
/** this is only used for views if this is not related to a view delete these sections --- start /
const auto_created_model_table_name = 'vwloginslists';
/** this is only used for views if this is not related to a view delete these sections --- end */

const view_name = "vwloginslists";
const original_query = [
  "SELECT ",
  " logins.id, logins.name, logins.login, logins.loginenabled, logins.role, ",
  " CASE ",
  " WHEN logins.loginenabled = 0 THEN 'DISABLED' ",
  " WHEN logins.loginenabled = 1 THEN 'ENABLED' ",
  " END AS loginenableddescription, ",
  " loginroles.description AS roledescription ",
  " FROM logins ",
  " LEFT JOIN loginroles ",
  " ON loginroles.id = logins.role ",
].join("");

const new_query = [
  "SELECT ",
  " logins.id, logins.name, logins.login, logins.loginenabled, logins.role, ",
  " CASE ",
  " WHEN logins.loginenabled = 0 THEN 'DISABLED' ",
  " WHEN logins.loginenabled = 1 THEN 'ENABLED' ",
  " END AS loginenableddescription, ",
  " loginroles.description AS roledescription ",
  " FROM logins ",
  " LEFT JOIN loginroles ",
  " ON loginroles.id = logins.role ",
].join("");

module.exports = {
  up: function(database, Sequelize) {
    return Promise.all([]);
  },
  down: function(database, Sequelize) {
    return Promise.all([
      sequelize.query(`DROP TABLE IF EXISTS ${auto_created_model_table_name}`).then(result => {
        sequelize.query(`CREATE OR REPLACE VIEW ${view_name} AS ${new_query}`).then(result => {
          return result;
        });
      }),
    ]);
  },
};
```

3. Go to your route file and here's is how you can now findAll

```JavaScript
const vwLoginsList = require("../sequelize/models/view_model_vwloginslist");
await vwLoginsList.count(whereConditionCount);

// or;
return vwLoginsList.findAll(whereCondition);
```

- next `npm run start` to auto create all the models and tables
- stop the node server
- next run sequelize migration to clean up the auto created tables and create your view for you `npx sequelize db:migrate`

now start your server again npm run start and your findAll should work great

hope this helps the next person or myself in the future

**Note to future self... your awesome and its all gonna be worth it one day :)**

**Comment by KeyOnTech** [comment]
Thank you for rewriting this I had so much trouble posting it wouldn't format right for me and I was super tired after figuring it all out I just wanted to go to bed

I just wanted to get the message out that it can work 

you showed it like I was trying LoL and great explanation of the steps. Thanks

**Comment by it-nalon** [comment]
For those using `sequelize-typescript` I resolved like this:

1. create your model as usual, add a `primaryKey` column and disable `createdAt` and `updatedAt` columns:
```ts
import { Column, Model, Table } from 'sequelize-typescript'
import { Sequelize, SyncOptions } from 'sequelize'
import { Field, Int, ObjectType } from 'type-graphql'

@ObjectType()
@Table({ createdAt: false, updatedAt: false })
export class MyView extends Model<MyView> {
  @Field(() => ID)
  @Column({ primaryKey: true, autoIncrement: true })
  id!: number

  @Field(() => Int)
  @Column({ allowNull: false })
  myViewColumn!: number

  @Field()
  @Column({ allowNull: false })
  mySecondViewColumn!: string
}
```

2. add the `sync()` function implementation in your model, so when you `sync()` Sequelize during the initialization it will skip the table creation:
```ts
@ObjectType()
@Table({ createdAt: false, updatedAt: false })
export class ProductStock extends Model<ProductStock> {
  @Field(() => ID)
  @Column({ primaryKey: true, autoIncrement: true })
  id!: number

  @Field(() => Int)
  @Column({ allowNull: false })
  myViewColumn!: number

  @Field()
  @Column({ allowNull: false })
  mySecondViewColumn!: string

  static async sync(options: SyncOptions): Promise<any> {
    if (options.force) {
      await this.sequelize?.query(`DROP VIEW IF EXISTS "${this.tableName}"`)
    }
  }
}
```

3. Create the view in your entry point code after the Sequelize initialization:
```ts

 ... rest of your entry point

  const sequelize = await createSequelizeInstance(configuration)

  try {
    await sequelize.authenticate()
    console.log('Connection has been established successfully.')
  } catch (error) {
    console.error('Unable to connect to the database:', error)
    process.exit(-1)
  }

  await sequelize.query(getMyViewCreateQuery(MyView.tableName))

... rest of your entry point
```

4. Query your view:
```ts
MyView.findAll({where: { myViewColumn: 1 }})
```

**Comment by slidenerd** [comment]
> For those using `sequelize-typescript` I resolved like this:
> 
>     1. create your model as usual, add a `primaryKey` column and disable `createdAt` and `updatedAt` columns:
> 
> 
> ```ts
> import { Column, Model, Table } from 'sequelize-typescript'
> 
> @Table({ createdAt: false, updatedAt: false })
> export class MyView extends Model<MyView> {
>   @Column({ primaryKey: true, autoIncrement: true })
>   id!: number
> 
>   @Column({ allowNull: false })
>   myViewColumn!: number
> 
>   @Column({ allowNull: false })
>   mySecondViewColumn!: string
> }
> ```
> 
>     2. add the `sync()` function implementation in your model, doing so will skip the table creation when you run `sequelize.sync()` during the initialization:
> 
> 
> ```ts
> import { Column, Model, Table } from 'sequelize-typescript'
> import { SyncOptions } from 'sequelize' // <- import SyncOptions
> 
> @Table({ createdAt: false, updatedAt: false })
> export class MyView extends Model<MyView> {
>   @Column({ primaryKey: true, autoIncrement: true })
>   id!: number
> 
>   @Column({ allowNull: false })
>   myViewColumn!: number
> 
>   @Column({ allowNull: false })
>   mySecondViewColumn!: string
> 
>   static async sync(options: SyncOptions): Promise<any> {
>     if (options.force) {
>       await this.sequelize?.query(`DROP VIEW IF EXISTS "${this.tableName}"`)
>     }
>   }
> }
> ```
> 
>     3. Create the view in your entry point code after the Sequelize initialization:
> 
> 
> ```ts
>  ... rest of your entry point
> 
>   const sequelize = await createSequelizeInstance(configuration)
> 
>   try {
>     await sequelize.authenticate()
>     console.log('Connection has been established successfully.')
>   } catch (error) {
>     console.error('Unable to connect to the database:', error)
>     process.exit(-1)
>   }
> 
>   await sequelize.query(getMyViewCreateQuery(MyView.tableName))
> 
> ... rest of your entry point
> ```
> 
>     4. Query your view:
> 
> 
> ```ts
> MyView.findAll({where: { myViewColumn: 1 }})
> ```

The first time you run this it has no problems

The second time or any subsequent time you run this and the tables already exist, it immediately throws an error
```

  original: error: "feed_item_likes_dislikes_aggregates" is not a table
      at Parser.parseErrorMessage (/Users/vr/Desktop/code/ch/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/vr/Desktop/code/ch/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/vr/Desktop/code/ch/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/vr/Desktop/code/ch/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 182,
    severity: 'ERROR',
    code: '42809',
    detail: undefined,
    hint: 'Use DROP MATERIALIZED VIEW to remove a materialized view.',
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'tablecmds.c',
    line: '1304',
    routine: 'DropErrorMsgWrongType',
    sql: 'DROP TABLE IF EXISTS "feed_item_likes_dislikes_aggregates" CASCADE;',
    parameters: undefined
  },
  sql: 'DROP TABLE IF EXISTS "feed_item_likes_dislikes_aggregates" CASCADE;',
  parameters: {}
}
```
This is what the code for the entry point looks like

```

async function setupDatabase() {
  try {
    await sequelize.sync({ force: true });
    await createMaterializedBullishBearishAggregate();
    await createMaterializedLikesDislikesAggregate();
  } catch (error) {
    console.error(error);
  }
}

```
