### ISSUE TITLE
MySQL INIT Command (or how to SET time_zone in MySQL)

### ISSUE THREAD

**Issue by noah-goodrich** [sequelize/sequelize#3079]
Google has revealed that timezone can be set directly in the options object in 2.0 when constructing a new Sequelize instance. However, we are still using the 1.7 branch in production. 

The PDO library in PHP allows for an INIT COMMAND option to be passed to the driver for custom commands that need to be executed upon connection each time. Is there something similar in Sequelize 1.7?

Otherwise, what is the prescribed method in 1.7 for setting the MySQL time_zone?

**Comment by janmeier** [comment]
There is no prescribed way of doing what you want in 1.7 (and not really in 2.0 either - theres an option for timezone, but for anything else no)

Your best bet would probably be to wrap the getConnection https://github.com/sequelize/sequelize/blob/1.7.0/lib/dialects/mysql/connector-manager.js#L212 function and SET the timezone there

**Comment by janmeier** [comment]
No response, closing
