### ISSUE TITLE
document link "sequelize#query" is broken

### ISSUE THREAD

**Issue by neekey** [sequelize/sequelize#3085]
In this section, [findAll](http://sequelize.readthedocs.org/en/latest/api/model/#findalloptions-queryoptions-promisearrayinstance), link [Sequelize#query](http://sequelize.readthedocs.org/en/latest/sequelize#query) is broken.

**Comment by janmeier** [comment]
Fixed in https://github.com/sequelize/sequelize/commit/1e990afddb70e5c4bcfef5502b6a8f111d42e079
