### ISSUE TITLE
[Question] Can we use sql.js library instead of sqlite3 ?

### ISSUE THREAD

**Issue by florian-rossiaud** [sequelize/sequelize#3086]
Hi,

I tried to use an other library than sqlite3 (compiled on server and not feet all my needs) by the [sql.js](https://github.com/kripken/sql.js) node module but with no success.

Is it possible to do that or I'm a fool with to much hope ?

**Comment by janmeier** [comment]
It should be possible with `dialectModulePath`

```js
new Sequelize(..., {
  dialect: 'sqlite',
  dialectModulePath: 'sql.js'
});

**Comment by mickhansen** [comment]
That's assuming the API's are the same though.

**Comment by florian-rossiaud** [comment]
I tried that and the api seems to not like this module..

**Comment by janmeier** [comment]
Hmm yeah I was perhaps a bit too fast there - I though it was port of sqlite3, and not just sqlite..

**Comment by florian-rossiaud** [comment]
Do we have some other modules to be link with sequelize/sqlite3 but with no server compilation during the installation ?

**Comment by mickhansen** [comment]
@florian-rossiaud no the implementation and the lib used is coupled.

**Comment by janmeier** [comment]
But sqlite3 should have precompiled binaries that it will use. It shouldnt need to be compiled unless you specifically choose to, or if there is no binary for your platform

**Comment by florian-rossiaud** [comment]
@mickhansen  @janmeier  : Thank you for your fast answers ! :)

**Comment by iPotaje** [comment]
Possible solution:

https://github.com/kripken/sql.js/issues/91#issuecomment-211921170

**Comment by catamphetamine** [comment]
Hi. I've made an npm package that could be used to make `sql.js` work with Sequelize by mimicking `sqlite3`'s interface (based on @iPotaje 's comment):
https://www.npmjs.com/package/sql.js-as-sqlite3

Usage:

```js
import Sequelize from 'sequelize'
import sqlJsAsSqlite3 from 'sql.js-as-sqlite3'

const sequelize = new Sequelize('sqlite://dbname', {
  dialectModule: sqlJsAsSqlite3
})
```
