### ISSUE TITLE
query-interface.js:634:33:  Object [object Promise] has no method 'error'

### ISSUE THREAD

**Issue by bluecenter** [sequelize/sequelize#3094]
onDelete: 'cascade', if the row had been deleted, an error is thrown out.

   at /node_modules/sequelize/lib/query-interface.js:634:33)

**Comment by janmeier** [comment]
Can you give some more information please? Which version are you on? Which dialect are you using? Can you show some code that reproduces the error?=

**Comment by bluecenter** [comment]
The version is rc8, postgres. The code is simple, for example A, B, you call B.destroy(), then A is deleted as well, however if you call A.destroy(), the error is raised up. I think maybe I override the destroy() method on instance, now it returns a promise.

**Comment by cusspvz** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L665

@janmeier should this issue be a reminder to refactor that function into Promise methods? Since `.success` and `.error` are deprecated.

**Comment by janmeier** [comment]
@bluecenter Well, if the code is simple, then please show it :) Reproducable code snippets makes it _so_ much easier for us to fix bugs!

@cusspvz probably, but I don't see why this error arises, the promise has an error method

**Comment by cusspvz** [comment]
> I think maybe I override the destroy() method on instance, now it returns a promise.

@janmeier i've supposed that he placed a method called `destroy` on `instanceMethods`, but i didn't mentioned nothing about the subject since it is a supposition.

**Comment by janmeier** [comment]
No response, closing
