### ISSUE TITLE
Connecting to a named instance of MS SQL.

### ISSUE THREAD

**Issue by XemsDoom** [sequelize/sequelize#3097]
Hey,
is there currently any support for named instances with MS SQL? I have a dev environment with a SQLExpress Installation but I can't get sequelize to connect to the database. However, other modules like 'node-mssql' can connect without problems but that module lets me define a named instance to connect to.

node-mssql connection code
```
function connectMSSQL(callback){
    var sqlConfig = {
        user: 'sa',
        password: 'sasasa',
        port: '',
        server: 'localhost',
        database: 'dms2',
        driver: 'tedious',
        options : {
            instanceName: 'SQLEXPRESS'
        }
    };

    sql.connect(sqlConfig, function(err){
        if(err){
            console.log('cant connect to MS SQL server.');
            callback(err, false);
        }
        console.log('successfully connected to MS SQL server @' + config.database.host + '.');
        callback(null, true);
    });
}
```
sequelize code:
```
function connectSequelize(callback){
    sequelize = new Sequelize('dms2', 'sa', 'sasasa', {
        dialect: 'mssql',
        host: 'localhost'
    });
    sequelize.authenticate().complete(function(err){
        if(err){
            callback('sequelize couldnt connect to database:' + err, false);
        }else{
            console.log('sequelize successfully connected to database.');
            callback(null, true);
        }
    });
}
```
The error always gets triggered. I tried explicitly setting the port in the Sequelize object, but nothing works.

Since both modules use tedious, there should be some way to let Sequelize work with named instances, right?

Am I doing something wrong or is there currently just no support?

**Comment by XemsDoom** [comment]
Alright got it to work with a hack. Basically, your connection-manager.js for MS SQL needs to also serve an option called 'instanceName' to tedious. This would mean, that the port property of the passed config object must be removed when using named MS SQL instances.

**Comment by XemsDoom** [comment]
https://github.com/sequelize/sequelize/pull/3098

**Comment by L3V147H4N** [comment]
Im trying to connect to a remote mssql server but I got an error saying 'Failed to connect to xxx.xx.xx.xx:undefined .. I've already connect successfully using the node-mssql package, could you post an example?

**Comment by janmeier** [comment]
@L4V147H4N please show the code you tried. Have you set the instance name as shown in the linked PR?

**Comment by L3V147H4N** [comment]
Nevermind, later I tried connecting the other way and turns out that the IP was unreachable. I tried it locally and it worked

**Comment by mgrivera** [comment]
Hi, you can also make the sql server instance the *default* instance. That way, it serves itself through default port, which is 1433. In short, you should set 1433 the default port for your sql server instance. Please follow this link in SO which explains just to do that:
 
http://stackoverflow.com/questions/35026/sql-server-convert-a-named-instance-to-default-instance

If you can make your sql server instance the 'default' instance, following code should allow sequelize to connect (as you don't have to state the instance name): 
```javascript
        var sql = new Sequelize('yourDBName', 'user', 'pwd', {
            host: 'localhost',
            dialect: 'mssql',
            pool: {
              max: 5,
              min: 0,
              idle: 10000
          }
        });
```

**Comment by pablocarreraest** [comment]
guy I need some guide my code is like that:

`"development": {
        "database": "dbname",
        "username": "username",
        "password": "password",
        "dboptions":{
            "host": "192.168.0.117",
            "port": 1433,
            "dialect": "mssql",
            "dialectOptions": {
                "instanceName": "serverName"
            },
            "pool": {
                "max": 5,
                "min": 0,
                "idle": 15000
            }
        }
    }`

**Comment by pablocarreraest** [comment]
guy I need some guide my code is like that:

```
"development": {
        "database": "dbname",
        "username": "user",
        "password": "pass",
        "dboptions":{
            "host": "192.168.0.117",
            "port": 1433,
            "dialect": "mssql",
            "dialectOptions": {
                "instanceName": "svrname"
            },
            "pool": {
                "max": 5,
                "min": 0,
                "idle": 15000
            }
        }
    }
```

**Comment by aristot** [comment]
Dear Pablo,
we have the same error...
have you found a solution?

**Comment by janmeier** [comment]
Did you try https://github.com/sequelize/sequelize/pull/3098?

**Comment by aristot** [comment]
I am not sure we are in same config.
Our config:
sqlserver: {
    dialect: 'mssql',
    user: 'sa',
    password: 'torken2016!', //Tkn2016
    database: 'hise_dev',
  options: {
      dialect: 'mssql',
      host   : '127.0.0.1', 
      port   : 1433, 
      logging: true
    }

**Comment by blueorbitz** [comment]
I was puzzle as well initially searching for a solution.

I would like to share the finding in case anyone hit this issue don't have to go through so much digging.

The default way of setting up is as follow:
```
{
  "production": {
    "dialect": "mssql",
    "host": "localhost",
    "username":"xxxx",
    "password":"xxxx",
    "database":"databaseName",
    "dialectOptions":{
      "instanceName": "xxxxxxx"
    }
  }
}
```

In case, where the database is setup on a separate server, the `port` itself is already connected to the `instanceName` and therefore only the `port` is required.
```
{
  "production": {
    "dialect": "mssql",
    "host": "192.168.0.123",
    "username":"xxxx",
    "password":"xxxx",
    "database":"databaseName",
    "dialectOptions":{
      "port": 1433
    }
  }
}
```

Here are the reference to the [tedius API](http://tediousjs.github.io/tedious/api-connection.html)

**Comment by newbienewbie** [comment]
@blueorbitz Thanks a lot ! It woks!

**Comment by mytharcher** [comment]
Thanks @blueorbitz ! I also made my remote access work by changing `instansName: 'sqlexpress'` into `port: 1433`!

**Comment by sriharshachdalawadada** [comment]
i want to use trusted connection instead of specifying username and password, any body got workaround for this?

let db = new Sequelize({
  dialect: 'mssql',
  dialectModulePath: 'sequelize-msnodesqlv8',
  dialectOptions: {
    driver: 'SQL Server Native Client 10.0',
    instanceName: 'SQLEXPRESS',
    trustedConnection: true
  },
  host: 'localhost',
  database: 'finances'
});

this example doesnt work !!!

any ideas...

**Comment by mittaus** [comment]
Work for me: dialectOptions -> options -> instanceName

```
{
    development: {
        username: process.env.DB_USERNAME,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_NAME,
        host: process.env.DB_HOSTNAME,
        dialect: 'mssql',
        port: 1433,
        dialectOptions: {
            "options": {
                "instanceName": "spsaqa",
            }
        }
    }
};
```
