### ISSUE TITLE
Sequelize option native=false does not disable pg-native binding for model.findOne()

### ISSUE THREAD

**Issue by ccairns-hae** [sequelize/sequelize#3101]
In version 2.0.0, with option native set explicitly to false, sequelize still tries to load pg-native (which is not available or installed in our Windows environment).   Though after throwing an error once, subsequent calls to the same query go through in the non pg-native function.

## sequelize init
```javascript
var sequelize = new Sequelize(config.get("db.url"), {
    dialect: 'postgres',
    native: false,
    logging: console.log,
    define: {
        timestamps: true,
        underscored: true,
        underscoredAll: true
    }});
```
This findOne search triggers the native call.  
```javascript
    logger.debug("selector",selector);
    req.app.models.Organization.findOne(selector)
        .then(function(orgs) {
            res.json(orgs).end();
        })
        .catch(function(err) {
            logger.error("Failed to get organization", err);
            res.status(500).send(errors.OPERATION_FAILED).end();
        });
```

## logfile
```
[21:48:38] Development server listening. (PID:25504)
sequelize.options:{"dialect":"postgres","dialectModulePath":null,"host":"localhost","protocol":"tcp","define":{"timestamps":true,"underscored":true,"underscoredAll":true},"query":{},"sync":{},"timezone":"+00:00","omitNull":false,"native":false,"replication":false,"pool":{},"quoteIdentifiers":true,"hooks":{},"port":"5432"}
...
Error: Cannot find module 'pg-native'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\svn\swhub\node_modules\pg\lib\native\index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

## installed npm dependencies:
    "pg": "4.2.0",
    "pg-hstore": "^2.3.1",
    "sequelize": "2.0.0",

## environment
- Windows 7x64
- Node v10.28

**Comment by ccairns-hae** [comment]
Issue resolved.  Actual cause of the issue was the logger attempting to log the selector and the models it contained.   Assumption is that parsing these models triggers the call-out to pg-native.

**Comment by janmeier** [comment]
@mickhansen This seems to be the same issue as was discussed on IRC yesterday. I seem to remember having the same issue when I was on windows.

As already mentioned, the issue is that something is trying to clone the pg module, invoking the native property... Perhaps the solution would be to delete pg.native if native == false. But I'm not sure we can do that if it's a lazily initialized property
