### ISSUE TITLE
New datatype - comma list

### ISSUE THREAD

**Issue by grabbou** [sequelize/sequelize#3102]
Hi,

Been thinking about implementing a new data type "LIST", which can accept an array and join it by special delimiter (that can be specified, it's "," by default). 

Currently in my project I am using custom get / set, but AFAIK might be light & useful addition to already powerful data types collection.

What you think?

**Comment by janmeier** [comment]
We already have native array support in postgres, so it might make sense to extend that to just be a comma separated string in other dialects.

With the very recent data types refactor we are already at step one, where you can easily extend the array type to just be a string column in the DB.
However, we still need to up/down system, which would allow you to easily define a method for converting to / from an array

**Comment by grabbou** [comment]
That's great, I remember the discussion about native JSON file in Postgress as well and porting that to SQL. 

I can try to submit a PR request for that specific feature along with appropriate unit tests if you do see a point of having such a port.
