### ISSUE TITLE
Error Message property

### ISSUE THREAD

**Issue by mehmetavsar** [sequelize/sequelize#3104]
Hi,

I noticed that, after seeing that message property of error remains undefined, in errors.js line 139, `message` property belongs to `options.parent`, not `options`.

**Comment by janmeier** [comment]
Pr with test welcome :)

**Comment by BridgeAR** [comment]
@mehmetavsar Would you be so kind and try my fix? And it would be great if you'd have a test for me :)

**Comment by mehmetavsar** [comment]
@BridgeAR  : Pass

I had solved the issue with different approach. I wrote a util function that recursively search for a string message property in parent object hierarchy. The motivation behind choosing this was aiming to standardize responding error message to AJAX POST responses. And Sequelize is just one source of errors.
