### ISSUE TITLE
New DataTypes do not allow postgres character varying(n)[]

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3106]
A few days ago it was still possible to use DataTypes.ARRAY(DataTypes.STRING(n)). This is not possible with the refactored DataTypes and throws the following error:

/node_modules/sequelize/lib/sequelize.js:1175
    if (type instanceof DataTypes.ARRAY && dialectTypes[type.type.key]) {
                                                                 ^
TypeError: Cannot read property 'key' of undefined

It's not really a big issue to change that to DataTypes.ARRAY(DataTypes.STRING) but it would be nice to have the old functionality.

**Comment by mickhansen** [comment]
Ah, that's a regression i'll get fixed.
What's the expected SQL for a VARCHAR ARRAY with length?

**Comment by BridgeAR** [comment]
"columnName" VARCHAR(n)[]

**Comment by mickhansen** [comment]
@BridgeAR roger

**Comment by mickhansen** [comment]
Fixed in `sequelize@2.0.2`
