### ISSUE TITLE
Feature request: Using functions with unique indexes

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3108]
I'd like to create a index with a sequelize function. 

So instead of writing:
`someUnique: {type: Sequelize.STRING, unique: true}`
I'd like to do:
`someUnique: {type: Sequelize.STRING, unique: Sequelize.fn('upper')}`

In SQL-Syntax:
`CREATE UNIQUE INDEX my_unique_index ON sample_table(UPPER(my_column));`

I have a lot to do atm, so I do not have the time to make a pull request, but you'd get a lot of <3 from me by implementing it ;)

**Comment by janmeier** [comment]
```js
sequelize.define(..., {
  ... 
}, {
  indexes: [
    { fields: [ sequelize.fn('upper', sequelize.col('my_column')) ]}
]});
```

**Comment by BridgeAR** [comment]
Hey, thanks a lot for your effort :+1:
