### ISSUE TITLE
Raw query returns array of arrays with records 

### ISSUE THREAD

**Issue by jeffdupont** [sequelize/sequelize#3111]
I have a RAW query within my Domain model
```
classMethods: {
    findByWebsiteId: function(website_id) {
        var query = "SELECT w.id as website_id, d.id as domain_id, domain, d.created_at as created_at FROM domains d JOIN websites w ON d.id = w.domain_id WHERE w.id = :website_id";

        return db.query(
            query,
           { replacements: { website_id: website_id, type: db.QueryTypes.SELECT } }
        );
    }
}
```

There is only 1 record in the database, but I'm getting this
```
	Domain.findByWebsiteId(website_id)
		.then(function(domain) {
			callback(null, domain[0]);
		}, function(err) {
			callback(err, null);
		});
```

Results in:
```
[ [ { website_id: 104,
      domain_id: 32,
      domain: 'blog.example.net',
      created_at: 1422908489 } ],
  [ { website_id: 104,
      domain_id: 32,
      domain: 'blog.example.net',
      created_at: 1422908489 } ] ]
```

What am I doing wrong? I've updated the code according to the new RAW queries in the documentation. I'm expecting to see just ONE of the arrays in the results, not two.

**Comment by mickhansen** [comment]
What dialect? Afaik one of the dialects didn't have metadata so it returns the results twice.
Use `.spread()` to counter this.
Or define `type` correctly, currently you are nesting it in replacements, try this instead:

```
{
  replacements: { website_id: website_id },
  type: db.QueryTypes.SELECT
}
```

**Comment by jeffdupont** [comment]
It’s in MySQL dialect. The RAW type is what is suppose to use the spread. RAW is assumed if you do not pass the type value, or if you pass db.QueryTypes.RAW. So in this case, the SELECT type is not properly passing down just the results.


—

**Comment by mickhansen** [comment]
Because you supplied the query type in the wrong way, look at your code then at mine, you have it under the replacements option which is wrong.

**Comment by jeffdupont** [comment]
You’re right I missed that. It seems the documentation is off then?




http://sequelize.readthedocs.org/en/latest/docs/raw-queries/





The section on replacements shows this:




```

sequelize.query('SELECT * FROM projects WHERE status = :status ', 
  { replacements: { status: 'active', type: sequelize.QueryTypes.SELECT }}
).then(function(projects) {
  console.log(projects)
})

```




You can see there that the Type property is within the replacements object. Might need to adjust that.




Thanks for the help!


—

**Comment by mickhansen** [comment]
Right you are - Error in the docs :) Ill get that fixed.
