### ISSUE TITLE
Query Generator should ignore empty where object 

### ISSUE THREAD

**Issue by feroc1ty** [sequelize/sequelize#3113]
```
User.update({name: 'bob'}, {where: {}});
```
Produce query like this

> UPDATE "Users" SET "name"="bob","updatedAt"='2015-02-11 11:54:48.880 +00:00' WHERE

#2340

**Comment by feroc1ty** [comment]
Thanks :smile:

**Comment by mickhansen** [comment]
Fixed in `sequelize@2.0.2`
