### ISSUE TITLE
Foreign Key Naming

### ISSUE THREAD

**Issue by toaster33** [sequelize/sequelize#3116]
Curious how the foreign keys order is determined when Sequelize creates the table?  I thought the order is alphabetical but during testing it does not appear this way but at least the order is consistent.  Guessing the order comes from Models.js rawAttributes.

Is it possible to add an attribute to foreignKey that lets us define the foreign key constraint name (i.e. fk_PerOrders)?  This will help when using Sequelize migrations.

```
ALTER TABLE Orders
ADD CONSTRAINT fk_PerOrders
FOREIGN KEY (P_Id)
REFERENCES Persons(P_Id)
```

**Comment by apsavin** [comment]
+1

**Comment by mjurincic** [comment]
+1

**Comment by antonsamper** [comment]
👍

**Comment by KarboniteKream** [comment]
I also think this would be a nice feature.

**Comment by fabiotadashi** [comment]
That would be nice.

But I also have a problem that I think it's related to this issue (Foreign Key Naming). During the migration, "add column" uses the property name to create the foreign key name, which could generate a problem (duplicate foreign key names).
