### ISSUE TITLE
Get getterMethods via attributes property on findAll

### ISSUE THREAD

**Issue by MtDalPizzol** [sequelize/sequelize#3121]
Hey guys! Sorry if somebody else already asked for this. I need to get only the fullName of the User when I query the  db, so I'm trying this via a getterMethod, since I store the firstName and the lastName in different fields on the db, but it isn't working:

```javascript
module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define("User", {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    first_name: {
      type: DataTypes.STRING(100),
      allowNull: false,
      validate: {
        notEmpty: true
      }
    },
    last_name: {
      type: DataTypes.STRING(100),
      allowNull: false,
      validate: {
        notEmpty: true
      }      
    }
  }, {
    getterMethods: {
      fullName: function(){
        return this.first_name.concat(' ', this.last_name);  
      }
    }
  });
  return User;
};
           
User.findAll({
    attributes: ['fullName']
}).then(function (users) {
    fn(null, users);
});
```

When I remove the ```attributes: ['fullName']``` , it works fine. Is it possible or getterMethods only work when I call something like ```instance.fullName```? If not, is there some npm module that can help me to achieve this?

I'm getting the following error:

```
Possibly unhandled TypeError: Cannot read property 'field' of undefined
    at /home/ubuntu/workspace/app/node_modules/sequelize/lib/model.js:1727:47
    at Array.map (native)
    at module.exports.mapFieldNames (/home/ubuntu/workspace/app/node_modules/sequelize/lib/model.js:1723:47)
    at Promise.bind.then.then.then.then.QueryInterface.select.Utils._.defaults.type (/home/ubuntu/workspace/app/node_modules/sequelize/lib/model.js:720:21)
    at Promise._settlePromiseAt (/home/ubuntu/workspace/app/node_modules/sequelize/lib/promise.js:66:18)
```

**Comment by mickhansen** [comment]
`getterMethods` are not available in `attributes` as you surmised. You'll have to use your first and last name fields and then call the getter function after the instances have been found.

**Comment by MtDalPizzol** [comment]
Alright then... Thanks anyway!
I'm closing this, but, just out of curiosity: Is there any chance for this to be implemented in the future?

**Comment by grahamb** [comment]
+1 for supporting getters in attributes. This bit me tonight as well.

**Comment by mickhansen** [comment]
There's no way in your code to extrapolate that the fullName getter needs those two fields.
I'll have to see some more use cases and examples to determine whether or not this is something we can do :)

**Comment by cnaut** [comment]
I am some how able to get this to work. I have a fullName column in my db but it is null and the getterMethod is working to return the actual fullName

**Comment by janmeier** [comment]
@cnaut That comment makes no sense to me at all. Please open a new issue and show some actual code :)

**Comment by cnaut** [comment]
Sorry that was unclear and posted before understanding it a little better. I was able to get this to work by including first_name and last_name in attributes: 

```
User.findAll({
    attributes: ['first_name', 'last_name', 'fullName']
}).then(function (users) {
    fn(null, users);
});
```

**Comment by quanglam2807** [comment]
+1

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by pe77** [comment]
+1
