### ISSUE TITLE
Model.scope ambiguous columns

### ISSUE THREAD

**Issue by ackerdev** [sequelize/sequelize#3123]
When a model has a scope that contains a `where`, it will cause all columns referencing that model in the SQL's `where` clause to be referenced without being prefixed by their table reference. If including an association that also has a column with the name referenced in the `where` clause, and the query does not subquery for the source model, the query will error due to ambiguous column names.

### Example

Here's an example model definition.

```js
var Foo = sequelize.define('Foo', {
  status: DataTypes.STRING
}, {
  defaultScope: { where: { status: 'active' } }
});

var Bar = sequelize.define('Bar');

Foo.hasMany(Bar);
Bar.belongsTo(Foo);
```

Here, we query for a specific Foo instance by id, which will cause Sequelize to generate a query that does not use a subquery to retrieve Foo, allowing the where conditions to break out into the main query.

```js
Foo.find({
  where: { id: 1 } // This causes the source model (Foo) to not be retrieved via subquery
  include: Bar
});
```

The generated SQL's FROM will be Foo, it will JOIN Bar, and then the where clause will look something like

```SQL
WHERE `id` = 1 AND `status` = 'active'
```

And this will result in the error `Ambiguous column name 'id'`.

**Comment by janmeier** [comment]
All scope related issues have been aggregated into https://github.com/sequelize/sequelize/issues/3486 so I'm going to close this one
