### ISSUE TITLE
Facing problem in Find query on objects with Many to many relation

### ISSUE THREAD

**Issue by sahilgarg25** [sequelize/sequelize#3125]
I have below 3 models
```javascript
module.exports = function(sequelize, DataTypes) {
    var CATEGORY = 'category';
    var termTaxonomy = sequelize.define("termTaxonomy", {
        termTaxonomyId: {
            type: DataTypes.BIGINT,
            field: 'term_taxonomy_id',
            primaryKey: true
        },
        taxonomy: DataTypes.STRING,
        description: DataTypes.TEXT,
        parent: DataTypes.BIGINT,
        count: DataTypes.BIGINT
    }, {
        tableName: 'wp_term_taxonomy',
        timestamps: false,
        classMethods: {
            associate: function(models) {
                termTaxonomy.belongsTo(models.term, {
                    foreignKey: 'term_id'
                });
                termTaxonomy.hasMany(models.post, {
                    through: 'wp_term_relationships',
                    foreignKey: 'term_taxonomy_id'
                });
                models.post.hasMany(models.termTaxonomy, {
                    through: 'wp_term_relationships',
                    foreignKey: 'object_id'
                });
            },
            getCategoryPostsById: function(models, id) {
                return termTaxonomy.find({
                    include: [models.term, models.post],
                    where: {
                        termTaxonomyId: id,
                        taxonomy: CATEGORY
                    }
                });
            }
        }
    });
    return termTaxonomy;
};

module.exports = function(sequelize, DataTypes) {
    var termRelationship = sequelize.define("termRelationship", {
        objectId: {
            type: DataTypes.BIGINT,
            field: 'object_id',
            primaryKey: true
        },
        termTaxonomyId: {
            type: DataTypes.BIGINT,
            field: 'term_taxonomy_id',
            primaryKey: true
        },
        termOrder: {
            type: DataTypes.INTEGER,
            field: 'term_order'
        }
    }, {
        tableName: 'wp_term_relationships',
        timestamps: false
    });
    return termRelationship;
};

module.exports = function(sequelize, DataTypes) {
    var post = sequelize.define("post", {
        id: {
            type: DataTypes.BIGINT,
            field: 'ID',
            primaryKey: true
        },
        author: {
            type: DataTypes.BIGINT,
            field: 'post_author'
        },
        date: {
            type: DataTypes.DATE,
            field: 'post_date'
        },
        dateGMT: {
            type: DataTypes.DATE,
            field: 'post_date_gmt'
        },
        content: {
            type: DataTypes.TEXT,
            field: 'post_content'
        },
        title: {
            type: DataTypes.TEXT,
            field: 'post_title'
        },
        excerpt: {
            type: DataTypes.TEXT,
            field: 'post_excerpt'
        },
        status: {
            type: DataTypes.STRING,
            field: 'post_status'
        },
        commentStatus: {
            type: DataTypes.STRING,
            field: 'comment_status'
        },
        pingStatus: {
            type: DataTypes.STRING,
            field: 'ping_status'
        },
        password: {
            type: DataTypes.STRING,
            field: 'post_password'
        },
        name: {
            type: DataTypes.STRING,
            field: 'post_name'
        },
        toPing: {
            type: DataTypes.TEXT,
            field: 'to_ping'
        },
        pinged: {
            type: DataTypes.TEXT,
            field: 'pinged'
        },
        modified: {
            type: DataTypes.DATE,
            field: 'post_modified'
        },
        modifiedGMT: {
            type: DataTypes.DATE,
            field: 'post_modified_gmt'
        },
        contentFiltered: {
            type: DataTypes.TEXT,
            field: 'post_content_filtered'
        },
        parent: {
            type: DataTypes.BIGINT,
            field: 'post_parent'
        },
        guid: {
            type: DataTypes.STRING,
            field: 'guid'
        },
        menuOrder: {
            type: DataTypes.INTEGER,
            field: 'menu_order'
        },
        type: {
            type: DataTypes.STRING,
            field: 'post_type'
        },
        mimeType: {
            type: DataTypes.STRING,
            field: 'post_mime_type'
        },
        commentCount: {
            type: DataTypes.BIGINT,
            field: 'comment_count'
        }
    }, {
        tableName: 'wp_posts',
        timestamps: false
    });
    return post;
};
```

Now if I call the function 
models.termTaxonomy.getCategoryPostsById(models, 16);

Below Query gets executed:
SELECT 
`termTaxonomy`.`term_taxonomy_id` AS `termTaxonomyId`, 
`termTaxonomy`.`taxonomy`, 
`termTaxonomy`.`description`, 
`termTaxonomy`.`parent`, 
`termTaxonomy`.`count`, 
`termTaxonomy`.`term_id`, 
`term`.`term_id` AS `term.termId`, 
`term`.`name` AS `term.name`, 
`term`.`slug` AS `term.slug`, 
`term`.`term_group` AS `term.termGroup`,
`posts`.`ID` AS `posts.id`, 
`posts`.`post_author` AS `posts.author`, 
`posts`.`post_date` AS `posts.date`, 
`posts`.`post_date_gmt` AS `posts.dateGMT`, 
`posts`.`post_content` AS `posts.content`, 
`posts`.`post_title` AS `posts.title`, 
`posts`.`post_excerpt` AS `posts.excerpt`, 
`posts`.`post_status` AS `posts.status`, 
`posts`.`comment_status` AS `posts.commentStatus`, 
`posts`.`ping_status` AS `posts.pingStatus`, 
`posts`.`post_password` AS `posts.password`, 
`posts`.`post_name` AS `posts.name`, 
`posts`.`to_ping` AS `posts.toPing`, 
`posts`.`pinged` AS `posts.pinged`, 
`posts`.`post_modified` AS `posts.modified`, 
`posts`.`post_modified_gmt` AS `posts.modifiedGMT`, 
`posts`.`post_content_filtered` AS `posts.contentFiltered`, 
`posts`.`post_parent` AS `posts.parent`, 
`posts`.`guid` AS `posts.guid`, 
`posts`.`menu_order` AS `posts.menuOrder`, 
`posts`.`post_type` AS `posts.type`, 
`posts`.`post_mime_type` AS `posts.mimeType`, 
`posts`.`comment_count` AS `posts.commentCount`, 
`posts.wp_term_relationship`.`object_id` AS `posts.wp_term_relationship.object_id`, 
`posts.wp_term_relationship`.`term_taxonomy_id` AS `posts.wp_term_relationship.term_taxonomy_id` 
FROM `wp_term_taxonomy` AS `termTaxonomy` 
LEFT OUTER JOIN `wp_terms` AS `term` 
	ON `term`.`term_id` = `termTaxonomy`.`term_id`
LEFT OUTER JOIN (`wp_term_relationships` AS `posts.wp_term_relationship` 
					LEFT OUTER JOIN `wp_posts` AS `posts` 
						ON `posts`.`id` = `posts.wp_term_relationship`.`object_id`) 
	ON `termTaxonomy`.`termTaxonomyId` = `posts.wp_term_relationship`.`term_taxonomy_id` 
WHERE `termTaxonomy`.`taxonomy`='category' AND `termTaxonomy`.`term_taxonomy_id`='16';

This query throws an error:
Error Code: 1054. Unknown column 'termTaxonomy.termTaxonomyId' in 'on clause'

How ever if i change the query this column name to 
'termTaxonomy.term_taxonomy_id'
The query runs successfully.

What changes do i need to make in the models so that the correct query is generated automatically.

**Comment by mickhansen** [comment]
Please remember to format the code so it's readable :)
Looks like a possible bug though, what version are you using?

**Comment by sahilgarg25** [comment]
I am sorry but the editor provided here on git automatically removed the indentation of my code.
I am using the below versions
"sequelize": "^2.0.0-rc1",
"sequelize-cli": "^1.1.0",

**Comment by mickhansen** [comment]
What is the actually installed version? (Not necessarily the one listed in package.json when using caret).
GitHub uses GitHub Flavored Markdown which has support for marking up code.

**Comment by sahilgarg25** [comment]
Same versions are installed.
"sequelize": "2.0.0-rc1",
"sequelize-cli": "1.1.0",

**Comment by mickhansen** [comment]
Well the issue you're facing might already be fixed then :)
You should give a newer version a go.

**Comment by sahilgarg25** [comment]
Thanks Mickhansen. Problem got resolved after upgrading the package.
