### ISSUE TITLE
How to execute custom SQL in migration?

### ISSUE THREAD

**Issue by wuyuntao** [sequelize/sequelize#313]
`ALT TABLE` for example.

**Comment by ebrian** [comment]
And in 2.0.x?

**Comment by bakavic** [comment]
@ebrian The `migration` being passed in when using `sequelize-cli` is `sequelize.getQueryInterface()`. So you can get access back to sequelize with:

```javascript
module.exports = {
  up: function (migration, DataTypes) {
    migration.sequelize.query('ALTER TABLE my_table ADD PRIMARY KEY(id)');
  }
}
```

**Comment by ebrian** [comment]
@bakavic For whatever reason that didn't work for me. However, `var sequelize = require('./sequelize-bootstrap');` worked fine.

**Comment by bakavic** [comment]
@ebrian I can't seem to find `sequelize-bootstrap`? Trying to require it in my migration file leads to an error complaining that it can't be found. Googling doesn't seem to bring up anything as well.

Just realised that the [`sequelize-cli` readme](https://github.com/sequelize/cli#the-migration-schema) seems to recommend getting `sequelize` from the `queryInterface` passed in as the first arg to the migration function, guess this should be the way forward?

**Comment by ebrian** [comment]
It may not be called sequelize-bootstrap, but, whatever file has your bootstrapping logic.

![image](https://cloud.githubusercontent.com/assets/4989650/7623764/af9bc8e6-f9ac-11e4-9cf6-9c27ffec3050.png)

**Comment by pittersnider** [comment]
i needed to find a github issue to be able to execute a custom query in migrations and I know many other people that needed as well. bad documentation.

**Comment by tunatoksoz** [comment]
send a pull request instead?

**Comment by tunatoksoz** [comment]
> i needed to find a github issue to be able to execute a custom query in migrations and I know many other people that needed as well. bad documentation.

send a pull request instead of complaining?
