### ISSUE TITLE
Can't call Model.destroy() or Model.update() without `where`

### ISSUE THREAD

**Issue by adamhooper** [sequelize/sequelize#3131]
When I call `MyModel.destroy()`, Sequelize throws an error: "Missing where or truncate attribute in the options parameter passed to destroy."

This removes functionality. WHERE-free DELETE is different from TRUNCATE (it runs triggers, works with views, and cascades deletes to foreign tables, among other things). And WHERE-free UPDATE has obvious uses.

I understand the desire to idiot-proof SQL. But is this really the place? I expect these methods to mimic SQL, and they don't.

ActiveRecord idiot-proofs by making the method name more alarming: `destroy(id)` destroys one; `destroy_all(options)` destroys many. http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-delete

Workaround: `where: '1=1'`

**Comment by mickhansen** [comment]
It's mostly implemented to safeguard people who are upgrading from 1.7 where we changed the syntax, don't want people blowing up stuff in production.

So for now `{where: {}}` is the workaround till we got "everyone" on the new version.
I have considered however that `destroy()` with no options at all should still allow destroy (as compared to an options object with no where property which is what we're guarding against really).

**Comment by adamhooper** [comment]
What about deprecating `destroy()` in favor of `destroyAll()` or a similarly-named method? That would be a more intuitive name -- `Model#destroy` and `Instance#destroy` wouldn't have the same method name, which would be nice because they're very different.

Otherwise, I wonder how many years I'll need to type `where: '1=1'` every time I run bulk updates and deletes? Or even worse, remember to add a `really: true` parameter? When should Sequelize stop "supporting" upgrades from 1.7 to >=2.0?

**Comment by mickhansen** [comment]
Well that could be an option aswell, although `all` is misleading with a filter i suppose ... then again it's called findAll heh.

Well like i suggested we could also fix this by not checking for the presense of `where` if `options === undefined` since this is to protect against: `.destroy({key: value})` which was the syntax for 1.7 but will whipe you out in 2.0 (without it being immediately obvious).

**Comment by rainabba** [comment]
If I'm following, this is counter-intuitive to OOP (and this is an ORM), but maybe my situation is different. I'm trying to figure out how to effectively delete an entity. After calling .findAll() then looping the resulting array, I expect to be able to call .destroy() (was looking for .delete() initially) on any object to delete it, but it seems that the old behavior there would have been to delete all records (1=1) and now I have to specify parameters when I already have a reference to the object that contains the primarykey.

Am I misunderstanding or just missing something? Do I have to call Model.destroy() with a where parameter every time?

**Comment by mickhansen** [comment]
@rainabba The reason why we're requiring `where` is because we changed the signature recently, so for people upgrading not to blow up there databases we're throwing rather than silently deleting everything.

It will be that way for a while untill we're confident most of our userbase has upgraded (although there's really now way to tell - i know of companies still running 1.7.x in production).

**Comment by janmeier** [comment]
In think its a good idea in general to require more confirmation from the user before deleting or updating everytning. You can still just pass an empty where object to both methods if you really mean it. Do we really need a specific method for destroying everything?

@rainabba you can still call `destroy` on the instance to destroy that instance directly

**Comment by rainabba** [comment]
@janmeier Below is the code I'm trying. The users[0].destory() call fails with "undefined is not a function". If users is an array of instances with a length > 0, I'd expect to be able to then call .destory() on users[0] so I'm making a bad assumption somewhere. Where is it?

Thanks

```
User.findAll()
	.then(function(users) {
		console.log('Found users. Count=', users.length); // 'Found users. Count=1'
		console.log(users[0]); // { dataValues: { uid: '67391560-b082-4168-91ba-eb52315f40b5' ...
		users[0].destory() // Unhandled rejection TypeError: undefined is not a function
			.then(function(res) {
				console.log(res);
			});

	});
});
```

**Comment by janmeier** [comment]
Destory -> destroy :-)

**Comment by rainabba** [comment]
Ha! But 'destory' is more interesting that way. Sorry for all the needless noise due to my lack of *speeling* skills. :P

**Comment by janmeier** [comment]
@mickhansen Do you think we need to do more here? I think its fine to just require users to pass an empty where object if they really want to remove everythnig

**Comment by rainabba** [comment]
Could have sworn I left some witty reply yesterday to say thank you, but I'm not seeing it now so thanks  :)
