### ISSUE TITLE
Array of BLOBs in postgres returning string instead of array of buffers

### ISSUE THREAD

**Issue by imathews** [sequelize/sequelize#3135]
I'm running Sequelize 2.0.2, pg 4.2.0, and postgres 9.3. I'm attempting to store an array of binary data, but can't make any sense of the issue I'm running into.

I have the serieArrays field defined in my Collections model as such:

```
sequelize.define('Collection', {
    serieArrays: {
        type: DataTypes.ARRAY(DataTypes.BLOB),
        defaultValue: [new Buffer(0)]
    }
```

When I update the Collection, all seems good in the server logs:

```
Executing (default): UPDATE "Collections" SET "serieArrays"=ARRAY[E'\\x00000000',E'\\x00000001']::BYTEA[] WHERE "id" = 6
```

However, when I access serieArrays from a the Collection instance, I'm returned a string:
`serieArrays: '{"\\\\x00000000","\\\\x00000001"}'`

I would expect an array of Buffers here; parsing this string kind of defeats the purpose of using binary data. Not sure if this is a bug or due to gaps in my understanding, but would greatly appreciate any help/advice.

Thanks!

**Comment by mickhansen** [comment]
@imathews appears to be a parsing bug.

**Comment by imathews** [comment]
Got it, thanks. Any sense of how long it might take to patch this? It's fairly substantially limiting our workflow...

**Comment by mickhansen** [comment]
@imathews No clue, need to find out if it's a bug in sequelize or the pg library. In any case the work needs to be done - but we have limited resources.

**Comment by imathews** [comment]
@mickhansen Of course, and thanks - let me know if there's anything I can do to help.

**Comment by mickhansen** [comment]
@imathews did you every verify whether the result was faulty with a pure node-postgres query?

**Comment by imathews** [comment]
@mickhansen No, though I'm happy to take a look this afternoon. I'm not too familiar with node-postgres, if you have any pointers...

**Comment by mickhansen** [comment]
@iamjochem Load up the node-postgres library with your connection settings and just run a raw SELECT.

**Comment by imathews** [comment]
@mickhansen - Got a chance to fire up node-postgres, see below for the output. Unless I'm mistaken, looks like our issue is in the pg module.

````
{ command: 'SELECT',
  rowCount: 1,
  oid: NaN,
  rows: 
   [ { id: 6,
       serieArrays: '{"\\\\x00000000"}',
       timepointArrays: '{"\\\\x00000000"}' } ],
  fields: 
   [ { name: 'id',
       tableID: 246563,
       columnID: 1,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'serieArrays',
       tableID: 246563,
       columnID: 15,
       dataTypeID: 1001,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'timepointArrays',
       tableID: 246563,
       columnID: 18,
       dataTypeID: 1001,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function], [Function], [Function] ],
  RowCtor: [Function],
  rowAsArray: false,
  _getTypeParser: [Function] }

````

**Comment by mickhansen** [comment]
@imathews Thank you, good to know. Now the question is whether or not this is an oversight in the pg library or if it's as intended.

**Comment by imathews** [comment]
@mickhansen Just filed an issue over at node-postgres. I feel like returning a string completely defeats the purpose of binary data...

**Comment by tiagowippel** [comment]
@imathews have you found the solution ? It is 2019 and I am facing this very same issue...
