### ISSUE TITLE
ER_PARSE_ERROR on MySQL enum

### ISSUE THREAD

**Issue by smill01** [sequelize/sequelize#3136]
Was working OK in 2.0.0-rc8.

```
   this.MetricDefinitions = sql.define("MetricDefinitions", {
        name: {type: Sequelize.STRING, primaryKey: true, comment: "Definition name"},
        metricName: {type: Sequelize.STRING, allowNull: false, comment: "Metrics.Name this definition applies to"},
        description: {type: Sequelize.STRING, comment: "Description"},
        values: {type: Sequelize.STRING, comment: "optional set of allowed values; comma-delimited floats"},
        valueMap: {type: Sequelize.STRING, comment: "optional set of descriptive labels suitable for use in the UI; comma-delimited"},
        metricType: {type: Sequelize.ENUM, values: ['gauge', 'counter', 'histogram'], comment: "Metric type"},
        // ‘gauge’ – default – an instantaneous value – only the last instance of the metric is kept
        // ‘counter’ –  the metric value is added to or subtracted from the running total – only one instance of the metric is kept
        // ‘histogram – an instantaneous value; saved as a series
        retentionType: {type: Sequelize.ENUM, values: ['max_count', 'hours'], comment: "RetentionType – ‘max_count’ or ‘hours’ – optional – histogram only"},
        retention: {type: Sequelize.INTEGER, defaultValue: 1, comment: "Retention - int – optional – histograms only"}
    });
```
2015-02-13 23:10:35.41 <error> { name: 'SequelizeDatabaseError',
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \' `retentionType` ENUM, `retention` INTEGER DEFAULT 1, `createdAt` DATETIME NOT N\' at line 1',
  parent: 
   { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `retentionType` ENUM, `retention` INTEGER DEFAULT 1, `createdAt` DATETIME NOT N' at line 1]
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'CREATE TABLE IF NOT EXISTS `MetricDefinitions` (`name` VARCHAR(255) , `metricName` VARCHAR(255) NOT NULL, `description` VARCHAR(255), `values` VARCHAR(255), `valueMap` VARCHAR(255), `metricType` ENUM, `retentionType` ENUM, `retention` INTEGER DEFAULT 1, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`name`)) ENGINE=InnoDB;' },
  original: 
   { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `retentionType` ENUM, `retention` INTEGER DEFAULT 1, `createdAt` DATETIME NOT N' at line 1]
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     index: 0,
     sql: 'CREATE TABLE IF NOT EXISTS `MetricDefinitions` (`name` VARCHAR(255) , `metricName` VARCHAR(255) NOT NULL, `description` VARCHAR(255), `values` VARCHAR(255), `valueMap` VARCHAR(255), `metricType` ENUM, `retentionType` ENUM, `retention` INTEGER DEFAULT 1, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`name`)) ENGINE=InnoDB;' },
  sql: 'CREATE TABLE IF NOT EXISTS `MetricDefinitions` (`name` VARCHAR(255) , `metricName` VARCHAR(255) NOT NULL, `description` VARCHAR(255), `values` VARCHAR(255), `valueMap` VARCHAR(255), `metricType` ENUM, `retentionType` ENUM, `retention` INTEGER DEFAULT 1, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`name`)) ENGINE=InnoDB;' } [Service._syncDB (service.js:1110)]

Output in rc8:
2015-02-13 23:19:14.78 <info> Executing (default): CREATE TABLE IF NOT EXISTS `MetricDefinitions` (`name` VARCHAR(255) , `metricName` VARCHAR(255) NOT NULL, `description` VARCHAR(255), `values` VARCHAR(255), `valueMap` VARCHAR(255), `metricType` ENUM('gauge', 'counter', 'histogram'), `retentionType` ENUM('max_count', 'hours'), `retention` INTEGER DEFAULT 1, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`name`)) ENGINE=InnoDB; [module.exports.Sequelize.log (sequelize.js:1111)]

**Comment by mickhansen** [comment]
Please make an effort to properly format the code and sql output, makes it easier for everyone to read :)

**Comment by janmeier** [comment]
Works fine for me on master
