### ISSUE TITLE
findOrCreate crashes the process with Out of Memory

### ISSUE THREAD

**Issue by arcanis** [sequelize/sequelize#3137]
Here is a showcase. If you set the `TESTED` function to `works`, it ... works. And doesn't work anymore with `doesNotWork` (the process goes out of memory).

I suggest executing `ulimit -m 2048000` (or lower) before trying the `doesNotWork` branch. I haven't used it the first time I launched the script, and my laptop crashed horribly.

Note that if sequelize has to create an element each time (if we use random ids in the where clause), the `works` branch crashes too. That may be another issue, I would expect everything to be garbage collectable if Node needs to free some space during the execution. Even forcing the garbage collection doesn't work.

``` js
var Sequelize = require( 'sequelize' );
var sequelize = new Sequelize( 'database', 'user', 'pass', { dialect : 'postgres', logging : false } );

var buffer = new Buffer( 5 * 1024 * 1024 );

var works = function ( Model, where, defaults ) {

    return Model.find( { where : where } ).then( function ( model ) {
        return model ? model : Model.create( require( 'lodash' ).merge( { }, where, defaults ) );
    } );

};

var doesNotWorks = function ( Model, where, defaults ) {

    return Model.findOrCreate( { where : where, defaults : defaults } );

};

var Foo = sequelize.define( 'Foo', {
    id : { type : Sequelize.INTEGER, primary : true },
    data : { type : Sequelize.BLOB }
} );

var promise = sequelize.sync( { force : true } );

var TESTED = works;//doesNotWorks;                                                                                                                                                                                 

for ( var t = 0; t < 1000; ++ t ) {
    promise = promise.then( function ( ) { return TESTED( Foo,
        { id : 0 }, { data : buffer }
    ); } );
}

promise.catch( function ( error ) {
    console.log( error.stack || error );
} );
```

**Comment by BridgeAR** [comment]
@arcanis the way how you test this is inherently wrong and your crashes have nothing to do with sequelize. It's the way how javascript works that is the issue. Each call created a buffer in a closure that can't be freed until the end of the promise chain, since the chain itself is a closure.
If you want to create huge amounts of parallel buffer calls (this won't work for any database btw - you have a limited amount of possible open transactions per database and sequelize has a default pool of five) you'd have to call them without the chain. That way javascript can free the memory as soon as the call is finishes.

@mickhansen please close this

**Comment by arcanis** [comment]
@BridgeAR I don't create any buffer except the initial one :)

If a buffer is created without being released, it can't come from this program and must come from either sequelize or pg. You can test this fairly easily by replacing the findOrCreate call by a setTimeout-based promise.

**Comment by BridgeAR** [comment]
Yepp, you only create one buffer. But it's not about the buffer - every call uses memory and stays in the memory as long as it was not collected. And yes, sequelize could try free it's memory after each call by setting the used objects to null after each usage. This would be a lot of work to do though and I'd say it's just not a use case that would normally happen.
So the memory won't be freed by garbage collector as long as we are in the chain and don't do it on our own.

**Comment by arcanis** [comment]
> And yes, sequelize could try free it's memory after each call by setting the used objects to null after each usage. This would be a lot of work to do though and I'd say it's just not a use case that would normally happen.

It *has* to do it. Otherwise it's a memory leak, and it may be really dangerous (think about a server that crash randomly every once in a while because it exausted the available memory - not acceptable).

**Comment by BridgeAR** [comment]
The memory will be freed after the chain ends.

**Comment by mickhansen** [comment]
@BridgeAR It's a leak if the buffer is coped internally and never cleaned.

**Comment by BridgeAR** [comment]
I'm quite certain that it's not leaking and freed at the chain end. Anyhow, I'll check later on if that's the case

**Comment by mickhansen** [comment]
@BridgeAR Ideally it should be a able to free before the chain end. That or the memory shouldn't grow per call ;p

**Comment by loulin** [comment]
+1. Whether I use `findOrCreate` or `create` with Promise serial loops, the memory usage rises quickly. I have to stop node to reduce memory, otherwise the usage will stay high even when the chain ends.

**Comment by mickhansen** [comment]
@loulin `create` does not do any magic

**Comment by contra** [comment]
I'm also getting out of memory when inserting 33K records (they're pretty big geojson blocks, some are 1MB each) asynchronously using `bulkCreate`, or if I do an individual `create` for each one.

Workaround is to batch them, but this has a huge perf hit.

**Comment by contra** [comment]
This should be reopened, it is still a bug.
