### ISSUE TITLE
query to get random rows

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3139]
Can there be something like:

```
models.user.findAll({ random: true, limit: 10, offset: 20 });
```

To get a random list of 10 users after the first 20 users?

**Comment by mickhansen** [comment]
I suppose, but it could probably trivially be solved with:

```js
order: [
  [sequelize.fn('RAND', '')]
]
```

Or similar.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/3159 does pose an issue about differences between MySQL and PG in terms of `ORDER BY [random]` so perhaps an abstraction could actually be a valid thing.

**Comment by akohout** [comment]
+1

**Comment by sean-madhavan** [comment]
:+1:

**Comment by DigitalSkyline** [comment]
+1  ... unfortunately needed this like tomorrow.

**Comment by janmeier** [comment]
@DigitalSkyline Then you need to provide a PR, like tomorrow :)

Everyone here works on the project in their free time, so you can't really expect something to be done within a certain timeframe - [scratch your own itch](http://www.catb.org/~esr/writings/cathedral-bazaar/)

**Comment by DigitalSkyline** [comment]
i appreciate that. If I ever get a free moment I would absolutely love to contribute.

**Comment by luongvo** [comment]
👍

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)
