### ISSUE TITLE
Problems with raw query

### ISSUE THREAD

**Issue by artiee** [sequelize/sequelize#314]
var sql = 'SELECT COUNT(*) FROM mytable WHERE 1';
sequelize.query(sql, null, { raw: true }).success(function(result){   });

This returns the correct result

Versus

var sql = '(SELECT COUNT(*) FROM mytable WHERE 1)';
sequelize.query(sql, null, { raw: true }).success(function(result){   });

This returns null.

Also

var sql = '  SELECT COUNT(*) FROM mytable WHERE 1';
sequelize.query(sql, null, { raw: true }).success(function(result){   });

returns null

**Comment by pda2564** [comment]
Is that config ..."type" : "sequelize.QueryTypes.SELECT" the same as "type": "SELECT"?
I tried these 2 ways and got the same results format.
So is that ok if using only "SELECT"?
