### ISSUE TITLE
Sync docs broken link

### ISSUE THREAD

**Issue by blairvanderhoof** [sequelize/sequelize#3140]
http://sequelize.readthedocs.org/en/latest/sequelize#sync leads to a 404.

**Comment by mickhansen** [comment]
Thank you @blairvanderhoof, where are you seeing that link so we can fix it?

**Comment by blairvanderhoof** [comment]
It's on this page under Sync http://sequelize.readthedocs.org/en/latest/api/model/index.html?highlight=Sync

**Comment by janmeier** [comment]
Duplicate of https://github.com/sequelize/sequelize/issues/3085
