### ISSUE TITLE
"on() is deprecated" query error message

### ISSUE THREAD

**Issue by pensierinmusica** [sequelize/sequelize#3141]
Hi,

Every time I run a query with Sequelize (v2.0.0), using NodeJS and PostgreSQL, I get a weird error message logged before any output:

"on() is deprecated and will be removed in 2.1, please use promise-style instead or use logging: fn in method options for method"

I am using promises though. This is the code:

```javascript
Project.find({where: {title: 'test'}})
  .then(function (project) {
  // ... some stuff
}, function (err) {
  console.error(err);
});
```

Any idea why this happens?

Thanks!

**Comment by mickhansen** [comment]
Ah yeah i believe i made an error.
I added the deprecation notice to on, but promises still ues them internally, i'll make sure to fix it :)

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/commit/b8e3ed598e892431ba32f4f02a00039809c3c125

**Comment by pensierinmusica** [comment]
Thanks!  :)
