### ISSUE TITLE
Avoid "id" field creation

### ISSUE THREAD

**Issue by pensierinmusica** [sequelize/sequelize#3142]
Sequelize automatically adds the "id" field to any model.

Is there a way to avoid this? I mean, simply not having the "id" field at all.

So far I've been able to do it through `model.removeAttribute('id')`. There should be an option for it though somewhere in the [model configuration](http://sequelize.readthedocs.org/en/latest/docs/models/#configuration), that doesn't require invoking this method every time.

I'm thinking about something similar to `timestamps: false`, but relative to the "id".

Could you please show me how to do it, or point me in the right direction on the docs?

Thanks!

**Comment by mickhansen** [comment]
Currently the only way is to define your own primary key or use `removeAttribute`.

Nothing like it exists, but i suppose an option named `defaultPrimaryKey: false` similar to `timestamps: false` could do the trick.

**Comment by pensierinmusica** [comment]
@mickhansen, that would be nice to have! I guess it shouldn't take too long to implement either  ;)

I imagine this doesn't have high priority, but any chances we could see it in v2.0.3?

Cheers!

**Comment by mickhansen** [comment]
@pensierinmusica likely not i'm afraid.

**Comment by golovashevich** [comment]
Yes, it's still an issue. Very, very surprising behavior, specifically taking into account impossibility to turn it off via options (configuration). 

Thank you.

**Comment by william0bra** [comment]
Yeah, that would be very helpful for several designs.

**Comment by JoshNewbury** [comment]
Any movement here?

**Comment by damusix** [comment]
+1

**Comment by AykutBurak** [comment]
Waiting for updates.

**Comment by Cuxs** [comment]
+1

**Comment by evangow** [comment]
+1

**Comment by vyolla** [comment]
+1

**Comment by dantaub** [comment]
+1

**Comment by Ricardonacif** [comment]
+1

**Comment by Gennadiii** [comment]
+1 I have different primary key and at the same time "id" as regular key. So I have to removeAttribute("id") but then I can't use "id" which is just a regular key. It's actually surprising that a column is added implicitly and there's no chance to undo that.

**Comment by JoshNewbury** [comment]
Great fix guys.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tawfiknasser** [comment]
https://github.com/sequelize/sequelize/blob/e59b3ff23d9c768994c502ee5be60279cb46a7e5/lib/model.js#L220

adds id field if no primary key is provided.
