### ISSUE TITLE
Model.update not returning the instance 

### ISSUE THREAD

**Issue by Caligone** [sequelize/sequelize#3144]
I'm using Sequelize v2.0.2 with PostgreSQL and when I'm trying to update a field with `option.returning = true`, the promise does not return the updated instance.

```javascript
Model.update({ name: 'Test' }, {
    where: {
        id_model: id
    },
    returning: true
})
.then(function (rowCount, model) {
    console.log(rowCount); // 1
    console.log(model); // undefined
})
.catch(function (err) {
    throw err;
});
```

The SQL seems ok : 
```SQL
UPDATE "Model" SET "name"='Test' WHERE "id_model" = 'f9008dc4-c6d3-4d90-ba0d-2d9e552818e3' RETURNING *
```

[Related documentation](http://sequelize.readthedocs.org/en/latest/api/model/#updatevalues-options-promisearrayaffectedcountaffectedrows)

**Comment by mickhansen** [comment]
`then` will always return a single argument, have you tried using `spread`?

**Comment by Caligone** [comment]
Oh my bad ! I learnt something new then :)
Thank you
