### ISSUE TITLE
Could we have validators be pushed to the backend as well?

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [sequelize/sequelize#3145]
I'm not entirely sure that my node app is the only application that will access the database directly (at the very least I may want to bulk load data into it from time to time).

It would be prudent, I think, to have the validators also pushed to the backend as check constraints at table creation time.

I know that Postgres supports robust constraints, and though I haven't paid attention, Mysql also supports them to some extent or another.

It looks like such a modification would be limited to the query-generator.js (one each for the supported db engines). I have prototype code here:

https://github.com/NoMoreNicksLeft/sequelize

It's unfinished (I have some concerns over the isIP validators, a few others), but I intend to finish it and use it myself. Would it be suitable for inclusion in the main Sequelize repo once finished? If it's unsuitable, what is the reasoning behind that?

**Comment by mickhansen** [comment]
Well first there's a question of whether or not it's doable in a sane way for all dialects. If not i would probably suggest we keep it application side since it's solved pretty well there (as opposed to DB specific things like JSONB which have to be dialect specific). 

Ideally we provide features for all dialects, except in cases where there's overwhelming reason to implement database specific stuff like JSONB etc.

There's also the question of maintenance, adding more to core means more maintenance, we don't want to add something that we can't keep up to date (which has unfortuneatly been a problem with other parts of the codebase).

**Comment by NoMoreNicksLeft** [comment]
Postgres's constraint syntax might as well be written in stone. They'll never change it in a way that impacts this. I do think it can be handled in a sane way for other dialects. The code will be similar (and go in the query-generator), though not identical between dialects. It looks as if even sqlite has some support of check constraints... should be possible to do it for all of them.

I do not believe it would be an ongoing maintenance issue. If new validators were added, you'd want to implement those as well, but other than that it should be the sort of thing that can just be left alone.

I'm willing to write the implementation for the various dialects, not just postgres.

**Comment by mickhansen** [comment]
@NoMoreNicksLeft Right i was mostly considering when we changed something on the Sequelize side the change would have to be implemented in two places, hence more maintenance.

I'll give it some thought, and would like @janmeier's input on this.
The more i begin to learn about Postgres the more i'm in favor of having stuff DB side (the only argument against it is cross-dialect issues), i'm originally from the MySQL world where everything was to be built application side :D

**Comment by NoMoreNicksLeft** [comment]
I'll continue to work on the code for this. Some of the validators seem difficult (doing a Luhn check without a subquery or custom function... ugh), but the rest I'm trying to match against validator.js directly so that they'll either be identical or provably equivalent. If I can swing some access to an mssql db, I'll start working on those too.

**Comment by kenydub** [comment]
+1 to the idea having validators pushed back to the db as check constraints
