### ISSUE TITLE
Preventing unauthorized access to associations?

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3146]
Say we have

```
User
    id
    email
    hasMany Item
    
Item
    id
    belongsTo User
```

When a user updates an Item, I would like to ensure the user is only updating items that belong to that user.

    current_user = 1;    // id of authenticated user

    models.item.find(....).then(function(item) {
        if ( item.user.id == current_user)   // Ensure item belongs to user
            item.updateAttributes(....);    
    });

This is a cumbersome solution, because it has to be written everywhere that requires an authorized action (across different models, different controllers, etc). Instead of doing that `if` check everywhere, can it be placed inside hooks in the models?

ie, as a hook in `models/item.js`:

```
module.exports = function(sequelize, DataTypes) {
    var Item = sequelize.define('item', { ..... });
 
     // hooks
     Item.beforeUpdate(function(item, options, fn) {
          // Somehow get current_user and check id against item.user.id
     });

     Item.beforeDestroy(.....) {
          // Somehow get current_user and check id against item.user.id
     });
};
```
    
But how would I pass my `current_user` to the hooks, and how would I check it against `item.user.id` (I would have to eager load `User` to do this too?). Or is there some other recommended way of checking authorizations?

**Comment by janmeier** [comment]
This would be a good case for CLS I think. We use it internally for providing the feature that automatically passes the transaction to all call within a transaction callback. As an example:

```js
var cls = require('continuation-local-storage')
  , ns = cls.createNamespace('mynamespace');

Sequelize.cls = ns;

ns.set('current_user');
ns.run(function () {
  // Do whatever your controller does 
});
```

Inside the callback to `ns.run` your hooks will be able to use `cls.getNamespace('mynamespace').get('current_user');`

If you use express / connect you can use this middleware https://github.com/othiym23/cls-middleware, set the current_user variable on the namespace in the authentication handler which will then be available to all other handlers

**Comment by janmeier** [comment]
No response, closing
