### ISSUE TITLE
Relations documentation on .get{AS}, .set{AS}, and .add{AS} is hard to find

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3147]
Both the docs and API link are pointing to a new readthedocs site.

Besides being messy to navigate (left side doesn't scroll at least in Firefox so when a page is open I can't access the links to the latter sessions on the page or pages after it) it looks like a lot of information has been lost as there is no longer a complete set of API docs.

- findOrCreate is mentioned, but not others like findOrBuild
- Things like instance.get{FooBarAssoc} have barely any explanation on how they work and what arguments they accept.

**Comment by janmeier** [comment]
findOrbuild is mentioned as findOrInitialize http://sequelize.readthedocs.org/en/latest/api/model/#findorinitialize

Regarding the scrolling, yes it seems to have broken - I has definitely worked before ..

`instance.get{FooBarAssoc}` this is mentioned in both API and regular docs - which do you find confusing. I agree it is not very well explained in the API docs

**Comment by mickhansen** [comment]
@dantman the API docs are the exact same as before.

**Comment by mickhansen** [comment]
And we've added more documentation since the RTD move since it's easier. But yes the scrolling is broken for some reason right now.

**Comment by dantman** [comment]
Ok, get{...} "is" mentioned in docs under a "Naming strategy" section, with just a few examples on use.

And API "does" mention get{AS} inside and say that the argument works like/is passed to the find methods.

Though this is in a page who's section headers are hasOne, belongsTo, hasMany, and belongsToMany. Giving the documentation skimmer trying to solve an immediate bug the impression that the page is about defining relations rather than using them from an instance.

**Comment by janmeier** [comment]
Agreed, the relations page of the docs could be rewritten to be more clear. Unfortunately we only have so much time, but well keep this issue open and hopefully find the time :)

**Comment by dantman** [comment]
Ok, I'll update the subject to fit that goal then.

**Comment by janmeier** [comment]
:+1:

**Comment by mickhansen** [comment]
@dantman the naming strategy of get{} should definitely be explained under the associations section in each section!

**Comment by sankethkatta** [comment]
On a related note, is there any way to inspect the get/set/add methods on the models? It doesn't seem to be as simple as looking at an instance object's keys.

**Comment by janmeier** [comment]
@sankethkatta Try to inspect the keys of `instance.prototype` instead

**Comment by sankethkatta** [comment]
@janmeier Thanks! However, `instance.prototype` was `undefined`. I was able to list the prototype's keys using either `instance.__proto__` or `instance.constructor.prototype`.

**Comment by mickhansen** [comment]
@sankethkatta Can also use: `Model.Instance.prototype`

**Comment by janmeier** [comment]
Association functions are not documented for each type of assocation http://docs.sequelizejs.com/en/latest/api/associations/belongs-to-many/
