### ISSUE TITLE
Add a singular get{AS} for hasMany relations.

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3148]
Currently hasOne relations gets a `.getFooBar` method and hasMany relations get a `.getFooBars` relation.

These work like Model.find and Model.findAll respectively.

I'd like to propose that hasMany relations also get a `.getFooBar` function. Because even though you would never need `.getFooBar()` without args there are still uses for it. Just as there are uses for Model.find even though it is always working with tables that have multiple rows.

Two examples:

```
user.getEmail({ where: { primary: true } })
```

The system makes an effort to ensure that only one row per user gets primary set to true, it's supposed to be unique, so picking the first one that matches is fine even if somehow there are more.

```
user.getEmail({ where: { email: 'foo.bar@example.com' } })
```

This one is more reasonable. The uniqness of email is guaranteed because it has a `{ unique: true }` index. This query will **never** return more than one instance so there's no point in using `user.getEmails` to return a list of instances.

**Comment by janmeier** [comment]
Not a bad idea :)
