### ISSUE TITLE
belongsToMany creates extra foreign

### ISSUE THREAD

**Issue by calvintwr** [sequelize/sequelize#3150]
https://github.com/sequelize/sequelize/issues/2991
Understand that there was a fix applied to this but I think I am still experiencing some problems.

This is my code:

    Customers.belongsToMany(models.Stores, {foreignKey: 'CustomerId', through: 'StoresCustomers'});
    Stores.hasMany(models.Customers, {foreignKey: 'StoreId', through: 'StoresCustomers'});

And it created these tables:
![screen shot 2015-02-17 at 1 25 33](https://cloud.githubusercontent.com/assets/6825277/6216341/43da7612-b644-11e4-99be-835c767e1702.png)

**Comment by mickhansen** [comment]
@calvintwr are you using master?

**Comment by mickhansen** [comment]
You can't mix belongsToMany and hasMany like that. Both associations should be belongsToMany.

**Comment by calvintwr** [comment]
Ahh... I was under the impression that it is used that way. Updated my stackoverflow answer too. Thanks mick.

Anyway 2xbelongsToMany had a bug that threw error when specifying `through: [string]`. Was about to make a pr for it but saw it was fixed.
