### ISSUE TITLE
documentation: Main docs say "greater than" is "$gt" but Sequelize understands "gt"

### ISSUE THREAD

**Issue by stnever** [sequelize/sequelize#3151]
Hi! The main documentation [here](http://sequelize.readthedocs.org/en/latest/docs/models/#findall-search-for-multiple-elements-in-the-database) has a section on operators that says:

    id: {
      $gt: 6,                // id > 6
      $gte: 6,               // id >= 6
      $lt: 10,               // id < 10
      $lte: 10,              // id

But this is wrong, seems the dollar signs shouldn't be there. The API docs [here](
http://sequelize.readthedocs.org/en/latest/api/model/#findalloptions-queryoptions-promisearrayinstance) are correct:

    Possible options are: gt, gte, lt, lte, ne, between/.., 
    nbetween/notbetween/!.., in, not, like, nlike/notlike

Also, in 2.0.0-rc8, using an unknown operator (I was trying `$gte`) will cause a bad SQL query like this:

     ... WHERE `Trip`.`startTimestamp`  '2015-02-02 02:00:00.000 +00:00'...
                                       ^-- nothing here
Perhaps we could throw a more user-friendly error, maybe pointing to the API documentation on operators?

**Comment by mickhansen** [comment]
`$gt` and the like was added in `2.0.0`, for older versions you can use `gt`.

**Comment by stnever** [comment]
Oops, thanks! I didn't see that on the changelog.
