### ISSUE TITLE
Closing sequelize connection.

### ISSUE THREAD

**Issue by juanjoLenero** [sequelize/sequelize#3152]
I might be missing something, but is there a way to close a database connection?
```javascript
var sequelize = new Sequelize(
    config.name,
    config.username,
    config.password,
    config.options
);
```

**Comment by mickhansen** [comment]
`sequelize.close()`

**Comment by janmeier** [comment]
As mickhansen said, simple as that - `issue.close()`

**Comment by MJafarMashhadi** [comment]
Is it syncron or returns a promise?

**Comment by mickhansen** [comment]
Method does not currently return a promise, but not exactly a synchronous action either.

**Comment by bkw** [comment]
> Method does not currently return a promise, but not exactly a synchronous action either.

I think a promise would be nice. Any chance of adding this?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/pull/5776

**Comment by bkw** [comment]
thanks, @janmeier !
