### ISSUE TITLE
Get random item from model

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3156]
Hi guys , its possible get item random from model ?

**Comment by cusspvz** [comment]
```js

Model.find({
  order: Sequelize.fn( 'RAND' ),
});

```

**Comment by juliocanares** [comment]
thanks :D

**Comment by paulomcnally** [comment]
How to import "Sequelize" to a controller?

    const models = require('../../models');

    models.foo.find({
      order: [
        Sequelize.fn( 'RAND' ),
      ]
    });

**Comment by mickhansen** [comment]
@paulomcnally The method is available on both the Sequelize constructor and the sequelize instance, entirely up to your own javascript/architecture prowess to figure out how to best pass that around.

In projects where i only need a single instance (99%) i simply have a file containing my sequelize instance that imports model, node.js caches requires so it's generally a singleton.

**Comment by paulomcnally** [comment]
Thanks @mickhansen. Solved with:

    const sequelize = require('../../../models').sequelize;

**Comment by dsullivan7** [comment]
It needs to be `Sequelize.fn( 'RANDOM' )` for Postgres
