### ISSUE TITLE
How to do an upsert() and can create() run validations?

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3157]
with this model:

```
var Item = sequelize.define('item', {
    slug: type: DataTypes.STRING,
    amount: {type: DataTypes.INTEGER, validate: { [0, 1000] }}
});
```

I've two questions:

(1) How do I do an upsert() based on a the `slug` field? The slug itself shouldn't be updated, but the amount should.

(2) How can I do an insert and ensure all fields obey validations? `create()` api doesn't have`[options.validate=true]`.

**Comment by mickhansen** [comment]
`upsert` is based on unique keys, so if `slug` is unique it will upsert based on that.

`create` maps to `save` so you can use all the options for `save`, `validate` is `true` by default.

**Comment by maplesap** [comment]
I think I might be doing upserts incorrectly. It doesn't seem to run any hooks or validations, and it never updates. It always does an insert.

```
var Item = sequelize.define('item', {
    slug: type: {type: DataTypes.STRING, unique: true},
    amount: {type: DataTypes.INTEGER, validate: { [0, 1000] }}
});

Item.afterCreate(function(item,options, fn) {
    var slug = createSlug();
    item.updateAtributes({slug:slug});
});
```

My upsert:

    models.item.upsert( { slug: slug, amount: 9999999 }, { fields: ['amount'] });

**Comment by mickhansen** [comment]
UPSERT does not support hooks currently (since it doesn't know at execution time whether it's going to be a create or update so no way to know what hooks to run)
Also you definitely shouldn't scope your upsert to `amount` of `slug` is the unique key.

**Comment by janmeier** [comment]
Closed, no response
