### ISSUE TITLE
Heroku Sequelize

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3159]
Hi guys , I'm deploying app to heroku using postgres and in local development mysql like dialect , but when I'm consulting the db in the app heroku , falls the page , any features of mysql than not work in postgres ?

**Comment by mickhansen** [comment]
It's usually the other way around, PG has features that MySQL doesn't.
We'll need a bit more information about what actually fails.

**Comment by juliocanares** [comment]
this occurs when consulting db and execute , check this link is the log 

https://gist.github.com/juliocanares/6445c67b68ec4d91f827#file-heroku-js

after execute this message is showed
```javascript
heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/pay/trial" host=mysterious-crag-5912.herokuapp.com request_id=917b1d8a-7da6-4f0b-9e30-0c16404679d0 fwd="190.232.1.128" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0
```

**Comment by juliocanares** [comment]
also I'm using 
```javascript
 order: sequelize.fn('RAND')
```
and the log show this

```javascript
Possibly unhandled SequelizeDatabaseError: function rand() does not exist
```

**Comment by mickhansen** [comment]
Well that should tell you most of what you need to know.

Google: https://www.google.dk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=postgres%20rand()
Leads you to: http://www.postgresql.org/message-id/Pine.LNX.4.21.0007182150230.1545-100000@localhost.localdomain
Which tells you that it's called: `random()` in PG, not `rand()` like in MySQL.

You are using a SQL function when using `sequelize.fn`, we don't provide an abstraction for that unfortuneatly.

**Comment by mickhansen** [comment]
You'll have to run pg locally aswell or introduce some dialect specific branching in your code.

Closing this since we know this issue, there's a feature request for abstraction here: https://github.com/sequelize/sequelize/issues/3139

**Comment by luongvo** [comment]
@juliocanares 
```
order: [
            [sequelize.fn('RANDOM')]
          ]
```
will solve this issue
