### ISSUE TITLE
File structure based on features instead of types

### ISSUE THREAD

**Issue by lvarayut** [sequelize/sequelize#3161]
I presently keep all of my model files in the model folder as suggested in the [Sequelize Guide](http://sequelizejs.com/articles/express#the-application). So, it allows me to easily load all of my models. My application structure is currently as following:

```
app/
----controllers/
--------user.js
--------article.js
----models/
--------user.js
--------article.js
----views/
--------user.jade
--------article.js
```

Recently, I wants to restructure my project based on features instead of types as following:

```
app/
----packages/
--------users/
------------model.js
------------controller.js
------------view.jade
--------articles/
------------model.js
------------controller.js
------------view.jade
```

Is there any easy way to load all of these models? Any suggestion would be appreciated.

**Comment by mickhansen** [comment]
@lvarayut more of a general node.js question than sequelize. But you should just be able to recursively iterate over folders and look for model.js files inside though.

**Comment by lvarayut** [comment]
Thanks for your answer. I'll try it soon.
