### ISSUE TITLE
How to associate model to another model by two foreignKeys ?

### ISSUE THREAD

**Issue by ondrasak** [sequelize/sequelize#3162]
Let's imagine situation

You have two models:
**event_user** with attributes: _id_
**event_user_message** with attributes: _user_from_id, user_to_id_

**You want to get _20_ event_users that were in contact (by message/s) with user X**

**definition of associations**

```
EventUser.hasMany(eventUserMessages, as: "from", foreignKey: "user_from_id")
EventUser.hasMany(eventUserMessages, as: "to", foreignKey: "user_to_id")

EventUserMessages.belongsTo(eventUser, as: "from", foreignKey: "user_from_id")
EventUserMessages.belongsTo(eventUser, as: "to", foreignKey: "user_to_id")
```

**Solution 1**
_problem_: _in this case I get only users that had two ways conversation_

```
var include, limit, where;
limit = parameters.limit ? parameters.limit : 20;

include.push({
  model: models.eventUserMessages,
  as: "to",
  where: {user_from_id: parameters.inConnectionWith}
  attributes: []
});
include.push({
  model: models.eventUserMessages,
  as: "from",
  where: {user_to_id: parameters.inConnectionWith}
  attributes: []
});

eventUserModel.findAll({
  include: include,
  where: where
})
```

**Solution 2**
In this solution you get all expected result
_problem_: _in this solutions is you can not use Limit (does not work)_

```
include.push({
  model: models.eventUserMessages,
  as: "to",
  required: false,
  attributes: []
});
include.push({
  model: models.eventUserMessages,
  as: "from",
  required: false,
  attributes: []
});

where = Sequelize.and(where, Sequelize.or({
  "to.user_from_id": parameters.inConnectionWith
}, {
  "from.user_to_id": parameters.inConnectionWith
}));

eventUserModel.findAll({
  include: include,
  where: where
})
```

will appreciate if you provide some suggestions about how to achieve this
thanks in Advance

**Comment by mickhansen** [comment]
I'm not sure there are any other ways, we don't currently support overwriting the JOIN condition for an include, but i suppose that would be the real solution `JOIN table ON from_id = ? OR to_id ?`
