### ISSUE TITLE
How to add index on two fields which are both foreignKeys

### ISSUE THREAD

**Issue by saelfaer** [sequelize/sequelize#3163]
hey, i'm trying to relate a `User` with `Skill` over a `UserSkill` table.

**user**

```
  var User = sequelize.define("User", {
    uuid: {type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true},
    firstName: {type: DataTypes.STRING, allowNull: false},
    lastName: {type: DataTypes.STRING, allowNull: false}
    /* removed irrelevant properties for this demo */
  }, {
    timestamps: true,
    paranoid: true,
    classMethods: {
      associate: function(models) {
        User.belongsToMany(models.Skill, {through: models.UserSkill});
      }
    }
  });
```

**skill**

```
  var Skill = sequelize.define("Skill", {
    uuid: {type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true},
    name: {type: DataTypes.STRING, allowNull: false, unique: 'skill_name_organisation'}
    /* removed irrelevant properties for this demo */
  }, {
    timestamps: true,
    paranoid: true,
    classMethods: {
      associate: function(models) {
        Skill.belongsToMany(models.User, {through: models.UserSkill});
      }
    }
  });
```

**userSkill**

```
  var UserSkill = sequelize.define("UserSkill", {
    uuid: {type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true}
    /* i have extra properties here like score, description, ...*/
  }, {
    timestamps: true,
    paranoid: true
  });
```

Now, in order for this relation between 1 user and 1 skill to be unique, I would need to be able to add a unique key. but as soon as I create the following fields within the `UserSkill` model it throws `duplicate field` errors on them.

```
    skillUuid: { type: DataTypes.UUID, unique: 'user_skill', allowNull: false, references: 'Skills', referencesKey: 'uuid'},
    userUuid: { type: DataTypes.UUID, unique: 'user_skill', allowNull: false, references: 'Users', referencesKey: 'uuid'}
```

Even when I add   `{ foreignKey: 'skillUuid' }` and `{ foreignKey: 'userUuid' }` to the 2 relations...

I'm kind of clueless at this point.

**Comment by mickhansen** [comment]
Can you show the SQL for the create table statements?
What you're doing should definitely be possible, can you show the relations and through model as you use them with unique keys and foreignKey option added?

**Comment by saelfaer** [comment]
Odd, while i'm drafting up the example you ask, I created a new project
added only the user - skill and userskill models and the setup works as expected.

but copying over those exact models into my other project results in duplicate columns...

so I'm now copying over my other models 1 by one to single out the one that causes the error but I'm kind of surprised by this.  

I will update this ticket with my findings soon

**Comment by mickhansen** [comment]
@saelfaer have to respect a man who knows his oldschool debugging atleast ;)

**Comment by saelfaer** [comment]
Well I'm sorry to have wasted your and my time... other debugging methods might have given me better results. I am even ashamed to admit my issue was just the fact that due to the many fiddling with these 3 models, my database was way out of sync. 

still struggling with the 'migrations' and 'sync' concepts. after fiddling with models and properties I often have to delete my database and let the sync recreate everything just to see it work.

**Comment by mickhansen** [comment]
@saelfaer i personally still use oldschool log & debug, haven't moved to more advanced debugging yet :)

Generally you should only be using `sync` while you are agressively prototyping, as soon as you have an app with production data you should be using migrations.

**Comment by saelfaer** [comment]
that I understand, however i'd love it if sequelize cli or the spin off sequelice-cmd have some auto migration generation :)

writing these migrations is ok for a small to medium project but as soon as you have more than 10 models it starts getting tedious to write new migrations for every small change. 

this migration generation was working pre-2.0 with sequelize-cmd but since the API changed that much and the entire migration system moved to umzug i'm hoping for a solution.

in the mean time i'll be writing them myself :)

**Comment by mickhansen** [comment]
@saelfaer i'm not too familiar with the CLI or umzug so you might want to open an issue on the CLI :)
