### ISSUE TITLE
Truncate table in postgres (pg)

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3168]
Hi guys i want truncate a table I'm using 
```javascript
         global.db.sequelize
         .query('SET FOREIGN_KEY_CHECKS = 0')
         .then(function () {
               return sequelize.query('truncate table Meals')
         })
         .then(function () {
               return sequelize.query('SET FOREIGN_KEY_CHECKS = 1')
         })
         .then(function () {
               //after truncate
         });
         });
```

this works fine with mysql but crash in postgres , what is the equivalent for postgres ? thanks :]

**Comment by mickhansen** [comment]
@juliocanares please don't post basic SQL questions here, google is way better for that :)
Figure out what query is failing specifically and then google the replacements for it.

However, we already have truncate support with `Model.destroy({truncate: true})`, however it might not turn off foreign keys.
