### ISSUE TITLE
code analysis failed, assignment actually looks pointless

### ISSUE THREAD

**Issue by cepharum** [sequelize/sequelize#3170]
When opening sequelize as part of my project PhpStorm started to mark initial line of normalizeDataType() in lib/sequelize.js to be malformed.

```javascript
  Sequelize.prototype.normalizeDataType = function(Type) {
    var type = typeof Type === "function" ? type = new Type() : Type
      , dialectTypes = this.dialect.DataTypes || {};

    [..]
  };
```

Actually, this late assignment in scope of ternary operator looks weird. Is it good for something special? I confirm with my IDE in that it might be more simply like this:

```javascript
  Sequelize.prototype.normalizeDataType = function(Type) {
    var type = typeof Type === "function" ? new Type() : Type
      , dialectTypes = this.dialect.DataTypes || {};

    [..]
  };
```

**Comment by mickhansen** [comment]
That definitely looks wrong, strange that jshint wouldn't have caught that.

**Comment by mickhansen** [comment]
Fixed, thank you :)
