### ISSUE TITLE
How to set custom validation messages, and catching validation errors in one catch() block?

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3172]
Two oddities I noticed:

(1) Custom validation message doesn't seem to work. Documentation says: 

"To use a custom error message instead of that provided by node-validator, use an object instead of the plain value or array of arguments"
https://sequelize.readthedocs.org/en/latest/docs/models/

But I get `Invalid validator function: args` and `Invalid validator function: msg`:

```
// model
var Item = sequelize.define('item', {
    slug: type: DataTypes.STRING,
    amount: {type: DataTypes.INTEGER, validate: { 
        args: {
                   max: 100,
                   min: 1 
         }, msg: "Please pick between 1-100" }
    }
});
```

(2) Why does the outside `catch()` not catch any `ValidationError`? ie,

This works:

    models.item.find(...).then(function(item) {
        // test max validation
        item.updateAttributes({ amount: 100000}).catch( function (msg) {
            console.log(msg);    // prints out fine, validation error caught!
        });
    });

This does not work:

    models.item.find(...).then(function(item) {
        // test max validation
        item.updateAttributes({amount:100000});
    }).catch(function(msg) {    // doesn't catch anything
        console.log(msg); 
    });

Nothing is caught; instead sequelize just throws the error:

`Possibly unhandled SequelizeValidationError: Validation error`

I was thinking I would catch all validations on outer most block, so that I could reduce the number of `catch()` statements and maintain some readability. Is this possible?

**Comment by mickhansen** [comment]
(2) You are not returning the promise inside find.

**Comment by maplesap** [comment]
Oh yes, I forgot about the promise for (2). That is fine.

Is there a problem with the way I'm doing my custom validate message in (1), or is it a bug?

**Comment by maplesap** [comment]
Okay, so it's supposed to be:

```
validate: {
    min: { args: 1, msg: "Pick 0-100 please"},
    max: { args: 100, msg: "Pick 0-100 please"},
}
```

**Comment by radishlau** [comment]
if the above didnt work, try
validate: {
    min: { args: [1], msg: "Pick 0-100 please"},
    max: { args: [100], msg: "Pick 0-100 please"},
}

**Comment by joaocg** [comment]
**jjhjhkjhkjhkjhkhk** lklkkljlkjljl ### jhjhkhkjhhjkhkjhkj
