### ISSUE TITLE
Don't validate in findOrInitialize

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3175]
findOrInitialize appears to be running validation hooks before resolving.

This behavior is unexpected (not in the API docs) and actually breaks the one use case I can think of (and would like to use) findOrInitialize for.

```js
FooBar.findOrInitialize({ where: { name: 'Foo' }, defaults: { name: 'Foo' } })
  .spread(function(fooBar, initialize) {
    fooBar.baz = 'baz';
    return fooBar.save();
  });
```

This should (from looking at it and following the docs) be a simple way to:
1. Find the `name: Foo` instance or build a `name: Foo` instance if one doesn't exist.
2. Set some properties on an instance whether it's new or existing.
3. `INSERT` the instance if it's new or `UPDATE` it if it already exists.

However if `.baz` is `allowNull: false` when creating this will result in a validation error because findOrInitialize runs validation before `.baz` has even been set.

This is an extremely handy pattern while building scripts/cron jobs that build and update data in bulk.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1108
It is indeed validating, and that does seem wrong to me.
@janmeier ?

**Comment by janmeier** [comment]
Yep, that shouldnt happen :)
