### ISSUE TITLE
addHook doesn't add hook if hook of same type already added as part of Model definition

### ISSUE THREAD

**Issue by shaunerikson** [sequelize/sequelize#3179]
Using version 2.0.0-rc8

```javascript
describe('#addHook', function() {

	describe('hook of same type already added as part of Model definition', function() {

		it('should add additinoal hook (BUT DOES NOT - BUG?)', function(done) {
			var hook1 = sinon.spy();
			var hook2 = sinon.spy();
			var Model = sequelize.define('Model', { 
				name: Sequelize.STRING 
			}, {
				hooks: { beforeCreate: hook1 }
			});
			Model.addHook('beforeCreate', hook2);
			Model.sync({ force: true })
				.then(function() { return Model.create({ name: 'bob' }); })
				.then(function() {
					hook1.should.have.been.calledOnce;
					// This assertion fails
					hook2.should.have.been.calledOnce;
					done(); 
				})
				.catch(done);
		})
	});
});
```

**Comment by mickhansen** [comment]
That's definitely a bug, thank you for the report.

**Comment by mickhansen** [comment]
Appears it's because the syntax is actually `beforeCreate: [hook1]`, where did you find the syntax you are using?

**Comment by serikson** [comment]
The docs [here] (http://sequelize.readthedocs.org/en/latest/docs/hooks/) in the section on "Declaring Hooks" make it seem that an array isn't required.

**Comment by mickhansen** [comment]
@serikson right you are :) either the docs were wrong initially or something changed the code and broke. It any case it is supposed now :)

**Comment by shaunerikson** [comment]
Thanks for fixing all those bugs so fast!

On Tue, Feb 24, 2015 at 10:00 AM, Mick Hansen <notifications@github.com>
wrote:

> @serikson <https://github.com/serikson> right you are :) either the docs
> were wrong initially or something changed the code and broke. It any case
> it is supposed now :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/3179#issuecomment-75810031>
> .
>



-- 
Shaun
