### ISSUE TITLE
Improve min, max and aggregate for multiple fields

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3187]
I'd like to run the following query in Postgres:

SELECT MAX("field1"), MAX("field2"), MAX("field3") FROM "tableName" WHERE "validTo" IS NULL;

This is not possible atm with the specified functions in sequelize and I have to use a raw query. As far as I can see it the only thing that has to be changed to make this work is to allow an array for fields instead of a string for one field.

Or is there any other way to solve this?

**Comment by mickhansen** [comment]
That query should be possible with:

```js
Model.findAll({
  attributes: [
    sequelize.fn('MAX', sequelize.col('field2'))
    // etc
  ],
  where: {
    validTo: null
  }
});
```

**Comment by BridgeAR** [comment]
The query generation works like a charm. The only problem is it won't return any data.

**Comment by BridgeAR** [comment]
Scratch that. This will work just fine:

```javascript
model.findOne({
    where: {
        validTo: null
    },
    attributes: [
        [sequelize.fn('max', sequelize.col('col1')), 'col1'],
        [sequelize.fn('max', sequelize.col('col2')), 'col2'],
        [sequelize.fn('max', sequelize.col('col3')), 'col3']
    ]
})
```

**Comment by winseros** [comment]
hm.. but if i wanna run the following query:

```sql
SELECT min(someField) as minValue, max(someField) as maxValue from someTable
```

And I use the following code:

```javascript
MyModel.find({
	attributes: [
		[sequelize.fn('min', sequelize.col('someField')), 'minValue'],
		[sequelize.fn('max', sequelize.col('someField')), 'maxValue']
	]
}).then(function(result) {
	console.log(result.minValue + ' ' + result.minValue);
});
```

i receive both values *undefined*
Is there a way to make it work?

**Comment by mickhansen** [comment]
@winseros you'll need to define VIRTUAL attributes for the targets of the aggregates.

**Comment by janmeier** [comment]
You should also be able to use a raw query:
```js
MyModel.find({
    attributes: [
        [sequelize.fn('min', sequelize.col('someField')), 'minValue'],
        [sequelize.fn('max', sequelize.col('someField')), 'maxValue']
    ]
}, {
  raw: true
});
```
Since you are not actually loading row data but aggregate data there is no need to put in into an instance

**Comment by winseros** [comment]
Thanks! That really does the trick!

Would be nice to see this potion in the api docs:
http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-queryoptions-promisearrayinstance

**Comment by janmeier** [comment]
It's sorta mentioned in the `See sequelize.query for options` part, but it might not be totally clear - however i still think it's better than having to repeat the same option for all methods :)

**Comment by qqqzhch** [comment]
.max('pagenum', {
            where: {
                language: language
            }
        })

is good

**Comment by justin-calleja** [comment]
What if you want all columns not just the max 'pagenum'? i.e. get the max 'pagenum' and all other columns (all in one query without having to look for that max first).
