### ISSUE TITLE
Sequelize has issues being used across contexts

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3188]
I was testing something in a custom REPL for my app and had an issue with Sequelize.
(The custom repl basically loads up the same environment with database config, etc... as my normal executable, preload some modules like ./models, Q, lodash, etc..., then start a node repl wrapped with repl-promised)

When trying to do a simple `models.MyModel.create({ ... })` I ended up with this error:

```
Error: The parameter (value: [object Object]) is no Object.
```

I spent awhile debugging thinking there was a validation error in my data or the `.create()` method's arguments changed and I was supposed to do something like `.create({ values: { ... } })`.

After awhile I dug into the code and looked up exactly where the error was. After a little test I realized that `Object` to Sequelize did not equal `Object` to my REPL.

This is because I did a `global.models = require('../models');` in my REPL's setup and apparently I needed to add `useGlobal: true` to `repl.start` to make them use the same context.

---

Not using `useGlobal: true` is sort of my fault and is an easy fix. Though I do think it's good practice to aim to behave normally across multiple contexts.

This could probably be done by replacing the `instanceof expectation` at [parameter-validator.js#L23](https://github.com/sequelize/sequelize/blob/56b47a6bdd60a9a1c5e43a35409dffa9ed5a4d93/lib/utils/parameter-validator.js#L23) with use of expectation functions and using lodash's _.is\* methods as expectations.

So instead of this:

``` js
Utils.validateParameter(values, Object, { optional: true });
```

You'd start writing this in your methods:

``` js
Utils.validateParameter(values, _.isObject, { optional: true });
```

**Comment by mickhansen** [comment]
`instanceof` does indeed have some caveats across different contexts, but we use that quite a lot, especially with the new data types, so if you're mixing sequelize contexts you might have a bad time regardless.

Not sure the parameter valiation fix will suffice.
You are probably best suited to propose a fix in a PR for this, if you can get a working state without crippling the codebase too much :)
