### ISSUE TITLE
Model findAll "include[].associations" 

### ISSUE THREAD

**Issue by ColCh** [sequelize/sequelize#3189]
[From documentation](http://sequelize.readthedocs.org/en/latest/api/model/#findalloptions-queryoptions-promisearrayinstance):
```
[options.include[].association] 	Association 	The association you want to eagerly load. (This can be used instead of providing a model/as pair)
```
I tried to [look some tests](https://github.com/sequelize/sequelize/blob/f5f58ec76f58c5c6fda1b9601e35396fd61ce59f/test/integration/model/findAll.test.js) on it... can't find documentation or any test as well

It's really untested or I can't find it?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/5d0f9be21a353d5ae42a61ea6706ffe4f0aafcee/test/integration/include.test.js#L56

Are a few here.
It's tested, not as heavily as the regular way but tested :)

**Comment by ColCh** [comment]
Oh thanks ... I've just looking for examples
