### ISSUE TITLE
Changing database credentials after sequelize init

### ISSUE THREAD

**Issue by ssh-pw** [sequelize/sequelize#3190]
Hello,
in the Sequelize Version 2.0.3 I can not change the database credentials (dialect: mysql) after the first init without credentials.

Code:

```javascript
// first init
var db = new Sequelize('foo', 'foo', 'foo', {
        host : 'localhost',
        dialect : 'mysql'
    });

// set credentials
db.config.password = 'secret';
db.config.username = 'bar';
db.config.database = 'foo';
```
console.log tells me that the credentials set in the sequelize instance, but the queries results in an SequelizeAccessDeniedError.

In older versions this was possible. Is there any other way to set the credentials after the first initialization?

Thanks and regards,
patric

**Comment by mickhansen** [comment]
Changing https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L169 should work, but it's not supported API so expect your code to break when we refactor internals.

**Comment by ssh-pw** [comment]
Hi,
the problem is that on every request to my node server instance the database credentials of the sequelize instance could be changed. Is there a possibility that I can rewrite the credentials (user, pass and database name) without a new init of the Sequelize-Class (with model-import-payload)?
thanks

**Comment by mickhansen** [comment]
@ssh-pw well you'd have to interface with the options, it's not really something we support.
You'll have to change the internal options and see if that works.

**Comment by marcusbalbi** [comment]
I don't know if it could be risky but every time I change my connection i run this code to setup the new credentials:

```javascript
sequelize.connectionManager.config.database = pClient.base
  sequelize.connectionManager.config.username = pClient.login
  sequelize.connectionManager.config.password = pClient.password
  sequelize.connectionManager.config.host = pClient.host
  sequelize.connectionManager.pool.clear()
```

**Comment by marcusbalbi** [comment]
Hello @ShepelievD I'm sorry for the delay, it's working well but I don't know if this is dangerous or not, I've tested a lot using the apache benchamark to force the application change the connection every time and it works fine!

**Comment by mickhansen** [comment]
`beforeConnect` is also an option now.

**Comment by rsshilli** [comment]
@mickhansen You da man. Here's the code that seems to work for me:
```
// Increase the connect timeout to 5 mins for test case connections, because sometimes an Aurora Serverless DB takes a while to cold start.
sequelize.beforeConnect(async (config) => {
  config.dialectOptions.connectTimeout = 5 * 60 * 1000;
});
```
