### ISSUE TITLE
Support `Model.find({ ..., include: [ { as: 'fooBar' } ] })` and `Model.find({ ..., include: [ 'fooBar' ] })`

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3193]
`include` on model queries is fairly verbose in its current state.

``` js
Model.find({ ..., include: [ { model: FooModel, as: 'fooBar' } ] });
Model.find({ ..., include: [ { association: Model.associations.fooBar } ] });
```

All of my models use `as`, because I have things like `UserEmail` as `user.emails`/`user.getEmails`, `UserPreference` as `user.preferencePairs`/`user.getPreferencePairs`, `UserAvatar` as `user.avatar`/`user.getAvatar`, etc. So using include is very verbose for me.

From what I understand models already contain all the information they need about their associations. You can't associate multiple models to the same `as` name or property (`{ model: Bar, as: 'foo' }` and `{ model: Baz, as: 'foo' }` should be impossible on one model). And using an association from a different model has no meaning and just breaks the query.

So it doesn't sound like both `modal` and `as` or a whole `association` object is needed to do an include.

So I'd like to suggest we also support these formats for doing an include:

``` js
Model.find({ ..., include: [ { as: 'fooBar' } ] });
Model.find({ ..., include: [ 'fooBar' ] });
```

I think this actually makes a lot of sense.

Implementation wise `Model` already knows that an association to the `fooBar` property exists and that the model for it is `FooModel`.

User expectation wise. The `as: 'fooBar'` association maps to the `fooBar` property. And so when you're writing `Model.find({ ..., include: [ 'fooBar' ] })` and then using `model.fooBar` it reads perfectly as `Find a Model instance and include the value of the 'fooBar' property from the associated model`.

**Comment by mickhansen** [comment]
We had this feature previously but it was very error prone.
I would be very open to supporting it, but only for relations that explicitely use "as" (since we respect "as" as-is and don't transform it).

**Comment by irond13** [comment]
I also think this is a good idea. I've submitted a pull request containing both of the above feature rests. @mickhansen why would this be very error prone?

**Comment by mickhansen** [comment]
@irond13 we used to have quite a big of magic around naming that confused a ton of users, this has mostly been removed now so it could be worth revisiting.
