### ISSUE TITLE
Accept database/username/password through `new Sequelize(config)` object args

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3194]
Database config as an options object is extremely common. JSON config files, parsed cli argument objects, and even sequelize-cli's own config files.

As a result this development pattern seems to be extremely common.

``` js
new Sequelize(config.database, config.username, config.password, config);
```

Maybe we should just go and allow `new Sequelize(config)` to be used. Accept an options object as the first arg, accept `.database`, `.username`, and `.password` from options, set them on options if they're provided in the args.

**Comment by mickhansen** [comment]
Makes sense, shouldn't be too hard to accomplish either.
