### ISSUE TITLE
model.findAll(where:{}) where clause produced is incorrect

### ISSUE THREAD

**Issue by danny-d** [sequelize/sequelize#3197]
var find = {
       where: {
          "createdBy": 1,
          "project.name": {ilike: '%singl%'},
        },
        include: [db.context, db.project, db.listItem]
      };
      db.item.findAll(find);

The where clause produced should be:

WHERE "item"."createdBy" = 1 AND "project.name" ILIKE '%singl%';

The where clause produced is:
WHERE "item"."createdBy" = 1 AND "item"."project.name" ILIKE '%singl%';

The entity "item" has been inserted in front of "project.name".

Dialect: postgresql
Sequelize version where bug occurs: v2.0.0 and upwards
This code worked on versions 2.0.0-rc3, 2.0.0-rc5, 2.0.0-rc7, 2.0.0-rc8.

**Comment by janmeier** [comment]
Try placing the where clause on the include: `include: [{ model: project, where: {...}}]

**Comment by danny-d** [comment]
Thank you very much. This solved my issue.
