### ISSUE TITLE
Add support for options.through.where in association getters

### ISSUE THREAD

**Issue by janmeier** [sequelize/sequelize#3198]
To allow querying the join table. Would probably fit right around here: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L327

**Comment by elliotstokes** [comment]
is there a work around for this at all? Im currently stuck not being able to query the join table.

**Comment by janmeier** [comment]
Unfortunately not. However, the fix shouldn't be too hard. Should be as easy as addding `options.through.where` somewhere around these lines https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L317-L329

(and the corresponding lines in has-many double linked)

**Comment by elliotstokes** [comment]
ok ill roll back to the previous version for the time being then.

**Comment by janmeier** [comment]
You're welcome to provide a PR - should only be a couple of lines of code + test (which you already more or less have given that your own code uses the feature :) )

**Comment by mickhansen** [comment]
@elliotstokes No workaround for BTM specifically however all BTM relations can be emulated with intermediate associations.

**Comment by elliotstokes** [comment]
ill take a look tonight. Thanks. Im also getting some other weird issues with the latest version as well but completely unrelated to this.

**Comment by contra** [comment]
Can this be reopened? This is a pretty major missing feature for the associations

**Comment by sushantdhiman** [comment]
Yea I need this one too :D, hopefully will send a PR really soon

**Comment by jsyvino** [comment]
agree!  would love this

**Comment by tresdev** [comment]
still not done?

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/5479
