### ISSUE TITLE
Running validations on a custom set()?

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3203]
When a user enters a password to be saved, I hash the plaintext password and the store it:

```
// models.user:

  password: { 
    type: DataTypes.STRING,
    validate: { 
      len: [10,20]
    },
    set : function(plain_password) {
      var hash = bcrypt.hash(plain_password, ...);
      this.setDataValue("password", hash);
    }
  }
```

But `set()` ignores any validations I have on `password`, because I think it is checking the hash length  and not the plaintext password length.

So I tried to throw an error in `set()`:

```
  set: function(password) {
    if (password.length < 10)
      new Error('password must be at least 10 characters');

    var hash = .....
  }
```

Which works, but it's not a `SequelizeValidationError` that gets passed back along with any other validation errors. All I see is:

    [Error: password requires 10-20 characters]

How would I get validations to run properly in my custom `set()`?

**Comment by janmeier** [comment]
I'd save the plain password in a virtual attribute, something like: https://github.com/sequelize/sequelize/blob/6a0912ad82915fd7bf20bd71ad7707abd473a137/test/integration/instance.validations.test.js#L917

**Comment by maplesap** [comment]
Ah, I didn't know about virtual datatypes. Yes, this works. Thanks!
