### ISSUE TITLE
options.indexes in define() throws error when the model has a schema

### ISSUE THREAD

**Issue by JMTyler** [sequelize/sequelize#3204]
(I am using dialect postgres, on sequelize version 2.0.3)

Included the following in my model options definition:

```json
{
    "indexes": [
        {
            "unique": true,
            "fields": ["myField"]
        }
    ]
}
```

Upon `sequelize.sync()`, I received the following error:

```
Possibly unhandled TypeError: Object "MySchema"."MyTable" has no method 'indexOf'
    at Object.module.exports.QueryGenerator.quoteIdentifiers (...MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:749:23)
    at Object.module.exports.QueryGenerator.addIndexQuery (...MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:519:20)
    at module.exports.QueryInterface.addIndex (...MyProject\node_modules\sequelize\lib\query-interface.js:443:35)
    at ...MyProject\node_modules\sequelize\lib\model.js:418:36
    ...
```

In lib/model.js at line 418, I found the following code:

```node
self.QueryInterface.addIndex(self.getTableName(options), index.fields, index, self.tableName);
```

The problem appears to be that the first argument to `addIndex()` is `self.getTableName(options)`, which returns an **object** of table name data (including a `toString()` method), instead of the actual **string** table name that the `addIndex()` method expects.  If I modify this code to pass the first argument as `self.getTableName(options).toString()`, it creates the index and does not produce an error.

Is this truly a bug, or am I somehow doing this wrong?

**Comment by janmeier** [comment]
Yep, seems to be a bug when the table has a schema. PR welcome
