### ISSUE TITLE
Table inheritance

### ISSUE THREAD

**Issue by skvsree** [sequelize/sequelize#3207]
Sequelize should support table inheritance feature reducing the code overhead.

eg;
``` 
var basetable = sequelize.define('base', {
  createdby: Sequelize.STRING,
  updatedby: Sequelize.STRING
});

var user= sequelize.define('User', {
  username: Sequelize.STRING,
  dob: Sequelize.DATE
},basetable);

user.createdby = user.name;

```
this will be excellent feature to have.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/1679 and https://github.com/sequelize/sequelize/issues/1243
