### ISSUE TITLE
Validation of array input to array field failed for PostgreSQL

### ISSUE THREAD

**Issue by cithukyaw** [sequelize/sequelize#3208]
I'm using [Node.js](http://nodejs.org) + [PostgreSQL](http://www.postgresql.org/) + [Sequelize.js 2.0.2](http://sequelizejs.com/). I have the following schema definition for the phone field which could be array of strings, but only number is allowed:

```
var User = sequelize.define("User", {
    ....
    ....
    /** Phone number
     * Multiple numbers should be registered due to
     */
    phone: {
        type: Sequelize.ARRAY(Sequelize.STRING),
        allowNull: false,
        unique: true,
        validate: {
            isNumeric: true
        }
    },
    ....
    ....
});
```

The array of numeric phone numbers is not passed for validation.

**Input**: `[ '9252522525', '9252525555' ]`  

**Error**:

```
{ [SequelizeValidationError: Validation error]
  name: 'SequelizeValidationError',
  message: 'Validation error',
  errors: 
   [ { message: 'Validation isNumeric failed',
       type: 'Validation error',
       path: 'phone',
       value: 'Validation isNumeric failed',
       __raw: 'Validation isNumeric failed' } ] }
```

However, the single-value array input `[ '9252522525' ]` is successful. Is it Sequelize's bug or what am I wrong?

I changed the validator to `is`, but no success.

```
validate: {
    is: ["^[0-9]+$", "i"]
}
```

I got the following error.

```
{ [SequelizeValidationError: Validation error]
  name: 'SequelizeValidationError',
  message: 'Validation error',
  errors: 
   [ { message: 'Validation is failed',
       type: 'Validation error',
       path: 'phone',
       value: 'Validation is failed',
       __raw: 'Validation is failed' } ] }
```

**Expected:** Applying the validator to each item of the array.

**Comment by janmeier** [comment]
Hmm, in most cases it might make sense to apply the validation to array elements, but then what about length and contains validations which could apply to both? I think it might be a bit too magic if some validations apply to elements and some apply to the array. 

I think you'll have to resort to a custom validator here. @mickhansen ?

**Comment by cithukyaw** [comment]
@janmeier I'm not sure why the single-value array `[ '9252522525' ]` is working. Along with the data type `Sequelize.ARRAY(Sequelize.STRING)`, my opinion is that the validator could be enough to apply to each array element for `Sequelize.STRING` because the array `Sequelize.ARRAY` itself can be validated using `Array.isArray()` and no validator is explicitly needed.

What do you mean "a bit too magic if some validations apply to elements and some apply to the array"?

**Comment by janmeier** [comment]
By too magic i mean 
```js
    phone: {
        type: Sequelize.ARRAY(Sequelize.STRING),
        validate: {
            isLength: [2, 4]
        }
```

Should that validate the length of the array or the length of the contained strings?

The reason that a single array is work is probably something to do with our usage of call / apply

**Comment by cithukyaw** [comment]
Oh I see. According to my expectation and suggestion, it could apply to the length of the contained strings. To validate the length of the array for `Sequelize.ARRAY`, a new special validator can probably be implemented, for example, `arrayLength`. Since `ARRAY` data type is only allowed for PostgreSQL, `Sequelize.ARRAY` and the `arrayLength` validator shall only be used by PostgreSQL users. This could not affect to the other database engine users.

**Comment by cithukyaw** [comment]
@janmeier [According to the documentation about validation](http://sequelize.readthedocs.org/en/latest/docs/models/#validations), `len` is probably what you said of `isLength` and `isArray` may be what I said about checking with `Array.isArray()`.

      is: ["^[a-z]+$",'i'],     // will only allow letters
      is: /^[a-z]+$/i,          // same as the previous example using real RegExp
      not: ["[a-z]",'i'],       // will not allow letters
      isEmail: true,            // checks for email format (foo@bar.com)
      isUrl: true,              // checks for url format (http://foo.com)
      isIP: true,               // checks for IPv4 (129.89.23.1) or IPv6 format
      isIPv4: true,             // checks for IPv4 (129.89.23.1)
      isIPv6: true,             // checks for IPv6 format
      isAlpha: true,            // will only allow letters
      isAlphanumeric: true      // will only allow alphanumeric characters, so "_abc" will fail
      isNumeric: true           // will only allow numbers
      isInt: true,              // checks for valid integers
      isFloat: true,            // checks for valid floating point numbers
      isDecimal: true,          // checks for any numbers
      isLowercase: true,        // checks for lowercase
      isUppercase: true,        // checks for uppercase
      notNull: true,            // won't allow null
      isNull: true,             // only allows null
      notEmpty: true,           // don't allow empty strings
      equals: 'specific value', // only allow a specific value
      contains: 'foo',          // force specific substrings
      notIn: [['foo', 'bar']],  // check the value is not one of these
      isIn: [['foo', 'bar']],   // check the value is one of these
      notContains: 'bar',       // don't allow specific substrings
      len: [2,10],              // only allow values with length between 2 and 10
      isUUID: 4,                // only allow uuids
      isDate: true,             // only allow date strings
      isAfter: "2011-11-05",    // only allow date strings after a specific date
      isBefore: "2011-11-05",   // only allow date strings before a specific date
      max: 23,                  // only allow values
      min: 23,                  // only allow values >= 23
      isArray: true,            // only allow arrays
      isCreditCard: true,       // check for valid credit card numbers

So, I see only `notNull`, `isNull` and `isArray` applicable to the ARRAY. Most of the validator would be applicable to each single piece of item value, otherwise I guess all of them could fail for array.

In fact, `isArray` might not be needed and it could be checked `Array.isArray()` internally when `Sequelize.ARRAY` data type is used. I can't imagine the situation to use `isArray: true` when `Sequelize.ARRAY` is not used. The new possible validator `arrayLength` what I said is to apart the array length validation from the length the contained strings by `len`.

**Comment by mickhansen** [comment]
@cithukyaw it makes sense but it does not adress the question that it would be overly ambigious as to which element the validator would apply.

**Comment by cithukyaw** [comment]
@mickhansen overly ambigious? I'm sometimes a over-thinking person. Sorry :) 

I'm not sure if it addresses the question or not. The custom validator could be a solution to this issue, however, I think that most of the validator would fail for array seems problem.

**Comment by mickhansen** [comment]
@cithukyaw What i mean is that we as designers of the API can reason about that users should use a special length validator for arrays, but it would likely not be clear to the end user who would just grab for the first length validator they see (cause that sort of make sense right?).

Validation of array input is likely a good idea, just not sure what would be good design :)
A custom validator is probably your fastest bet in terms of productivity right now.

**Comment by cithukyaw** [comment]
@mickhansen 
> A custom validator is probably your fastest bet in terms of productivity right now.

Yes, of course.

> about that users should use a special length validator for arrays, but it would likely not be clear to the end user who would just grab for the first length validator they see

`charLen` instead of `len` is more proper name I think.

**Comment by wavded** [comment]
Chiming in here late but is there a way to validate array elements?  Or no?  I'm not having any luck.

**Comment by janmeier** [comment]
@wavded By adding a custom validator function, yes :)

**Comment by wavded** [comment]
ahh ok, I'll do that :) wonder if i was missing some piece of configuration.

**Comment by BridgeAR** [comment]
A solution might be to implement something to do the following:

```js
validate: {
    elements: {
        len: [5,10] // each element has to be at least five and max ten chars length
    },
    len: [3, 99] // the array has to be at least three and max 99 elements long
}
```

The name elements might not be the best though. 
@janmeier would do you think about that?

**Comment by vhmth** [comment]
@BridgeAR I like that distinction. If the user wants to validate nested structures within the elements, they will need to implement custom validators.

**Comment by Tyler-Murphy** [comment]
How about a new syntax where the argument to `ARRAY` is another type/validation definition?

For example, this defines a type that's a list of 1 to 10 email addresses:

```javascript
emailListDefinition = {
    type: Sequelize.ARRAY({
        type: Sequelize.STRING,
        validate: {
            isEmail: true
        }
    }),
    validate: {
        len: [1, 10]
    }
}
```

**Comment by janmeier** [comment]
I think I like the `elements` way better than adding to the array constructor.

However, we are also considering removing validations completely from core and making them a plugin instead https://github.com/sequelize/sequelize/issues/5604

**Comment by hashinclude72** [comment]
Is there a good solution to this?
