### ISSUE TITLE
How to populate a table through migrations?

### ISSUE THREAD

**Issue by sandokanelcojo** [sequelize/sequelize#3210]
Hi there:

I've set up a project with it's Models and the tables are created automatically by sequelize.
I've also set up umzug to run the pending migrations automatically.

So far so good. Is there a simple way to populate a table through a migration?
Having a table 'Country' and a SQL to populate it how would my 'up' section look like?
Is there a doc page where I can look for the right params to use use `QueryInterface.insert()`? 

Thanks in advance for the help.

EDIT: Using Sequelize 2.0.3

**Comment by mickhansen** [comment]
You shouldn't interface with `QueryInterface` directly.
Use `sequelize.query` or `Model.bulkCreate`.

**Comment by sandokanelcojo** [comment]
Thanks a lot.
I went with `Model.bulkCreate`.
Here I leave a snippet in case it helps someone:

    var countries = [
       {code: 'ZMB', name: 'Zambia'},
       {code: 'ZWE', name: 'Zimbabwe'},
     ];

    sequelize.models.Country.bulkCreate(countries, null)
      .then(function (models) {
        console.log(models);
      });

Regards.

**Comment by barmatz** [comment]
+1

I was looking for a workaround for a while.
This is my solution when the model is not available yet.

```js
module.exports = {
  up: function(migration, DataTypes, done) {
    migration.createTable('Currencies', {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      createdAt: {
        type: DataTypes.DATE
      },
      updatedAt: {
        type: DataTypes.DATE
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false
      },
      code: {
        type: DataTypes.STRING,
        allowNull: false
      },
      entity: DataTypes.STRING
    }).complete(function () {
      migration.sequelize.query(migration.QueryGenerator.bulkInsertQuery('Currencies', [{
        name: 'United States dollar',
        code: 'USD',
        entity: '&#36;'
      }, {
        name: 'Euro',
        code: 'EUR',
        entity: '&#8364;'
      }])).complete(done);
    });
  },
  down: function(migration, DataTypes, done) {
    migration.dropTable('Currencies').complete(done);
  }
};

```

**Comment by AlexisNo** [comment]
> you shouldn't interface with QueryInterface directly.

@mickhansen What is wrong about that? This is an example of the solution I use: 

```javascript
'use strict';
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('roles', [{
      label: 'user',
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      label: 'admin',
      createdAt: new Date(),
      updatedAt: new Date()
    }]);
  },
  down: function(queryInterface, Sequelize) {
    return queryInterface.sequelize.query('DELETE FROM roles');
  }
};
```
Is there something wrong about it? I usually do not insert data in migration files and use seeders, but in some cases, it can be relevant.

About using `Model.bulkCreate()`, wouldn't it be susceptible to break the migration suite one day? Migration files should be immutable while a model definition can evolve. When a model evolves, I create a new migration file but do not alter the previous one so that new deployments do not require to rebuild the database completely. If a migration file references a model, an update of this model could break the migration suite.

**Comment by felixfbecker** [comment]
We moved more towards making QueryInterface public API, so no problem with that.

**Comment by darkotuning** [comment]
Is it possible that the seed is full of data at one time? I would like to have a lot of data in tables using the faker but not to run the anchor command many times but to do it all at once? Thank you
