### ISSUE TITLE
Prevent string escaping

### ISSUE THREAD

**Issue by BernhardBezdek** [sequelize/sequelize#3212]
I've a column which is Datatype Binary (16) and I store MD5 Hashes in it.
That's working after some effort but now I'm failing to query for this column.

The Reason for the failing query is sequelizes internal string masking.

My sequlize generated query looks like this example:

```
    SELECT 
        `account`
    FROM
        `Accounts` AS `Accounts`
    WHERE
        `Accounts`.`account` = '0x58bf948d865d11a05daa8546d832327a';
```

And it hasn't a result.

I want to remove the ' in where clause.

```
    SELECT 
        `account`
    FROM
        `Accounts` AS `Accounts`
    WHERE
        // Here quotes are remove which results with a successful mysql result
        `Accounts`.`account` = 0x58bf948d865d11a05daa8546d832327a;
```

Is it possible to particularly disable masking properties using my model class?

Thanks in advance

**Comment by janmeier** [comment]
Can you show the javascript code used to generated that query, and the model definition? 

Do you have the account field marked as BLOB in your model? and are you passing the data as a buffer?

**Comment by BernhardBezdek** [comment]
It's a BINARY(16)...

```  
var Accounts = sequelize.define("Accounts", {
            account: {
                type: "BINARY(16)",
                allowNull: false,
                primaryKey: true
            },

            [...]

```

**Comment by janmeier** [comment]
Just did some local testing, you should pass in a buffer:

```
Account.find({
  where: {
    account: new Buffer('58bf948d865d11a05daa8546d832327a', 'hex')
  }
});
```

**Comment by BernhardBezdek** [comment]
Hey thanks for your fast reply. 
Will give it a try later and give you a response.

**Comment by BernhardBezdek** [comment]
Hey @janmeier implemented it and it works perfect. Thank you so much.
