### ISSUE TITLE
Structured JSON columns with postgres dialect

### ISSUE THREAD

**Issue by kytwb** [sequelize/sequelize#3214]
Just opening the discussion. What do you guys think about implementing nested models for JSON type column when using postgres dialect? I'll be done to work on it.

**Comment by mickhansen** [comment]
@kytwb you mean with nested validation etc? Sort of building an ORM layer for the JSON/JSONB column type?

**Comment by kytwb** [comment]
@mickhansen yes sir'

**Comment by mickhansen** [comment]
@kytwb I don't really have an opinion, it's not likely something we'll want to maintain in core though.

**Comment by kytwb** [comment]
Alright, I'll make it a third tier module then, like `sequelize-fixtures`.
