### ISSUE TITLE
Remove auto transaction deprecation warning

### ISSUE THREAD

**Issue by bleupen** [sequelize/sequelize#3215]
Are auto managed transaction callback functions deprecated? If not, please remove the deprecation note as its cluttering stdout on unit tests.

**Comment by mickhansen** [comment]
@bleupen you are misunderstanding the deprecation notice, it's a deprecation notice for 1.7 syntax. In any case it will be removed soon.

**Comment by bleupen** [comment]
Thanks, what is the preferred 2.x syntax to avoid the message?

**Comment by mickhansen** [comment]
@bleupen you cant avoid it, or well you can now cause i just committed a change.
