### ISSUE TITLE
Improve .values

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3218]
In my code I have to copy sequelize objects quite often since .values only returns the stripped values of the instance itself without stripping included values.

That's not very intuitive and I'd recommend that .values should always strip the included data too.

**Comment by mickhansen** [comment]
`.values` has been deprecated for some time.
Use `.get()` or `.get({plain: true})` (plain gives you stripped values)

**Comment by BridgeAR** [comment]
Well, there is no deprecation notice when calling .values and it is still recommended in the docs (http://sequelize.readthedocs.org/en/latest/docs/instances/#values-of-an-instance). I'm going to make a pull request in the next couple of days to fix the docs and insert a deprecation warning.

Besides that, I'd still have a wish how to improve get(). If we'll call findAll().then(function(result){}) the return value is a plain array with sequelize objects. It would be great to use result.get() instead of iterating every element.

**Comment by janmeier** [comment]
A PR would be very welcome - we are aware that the documentation is lacking is some places, and all help is appreciated!

I see your point about `result.get` but that is not going to happen unfortunately. We return native arrays of results, and we don't want to be the kind of library that modifies `Array.prototype` ;)

**Comment by BridgeAR** [comment]
True point. Maybe it would be a good alternative, to add a option to return a plain object instead of a sequelize Object. 

Btw: using options.plain with different meanings in get and query is maybe not the best thing to do. Otherwise I would have recommended to insert plain in find* and query to resolve plain objects.

**Comment by mickhansen** [comment]
@BridgeAR are you looking to skip instances entirely or still run getters and get POJO data?

**Comment by BridgeAR** [comment]
I'd skip the instance entirely. I guess it's quite a common use case to only use the plain object and not the sequelize object.

**Comment by mickhansen** [comment]
@BridgeAR well we actually have something like that on the roadmap, full support for findAll with includes and `raw: true, better performance and pojos with the query generation still, you lose all model magic (getters, etc) though.
