### ISSUE TITLE
Bug in "where" with condition "$and"

### ISSUE THREAD

**Issue by bodyaka** [sequelize/sequelize#3219]
I've have a next condition:

	{
		where: {
			someField: {
				$and: [ {
					like : '%someValue1%'
				}, {
					like : '%someValue2%'
				} ]
			}
		}
	}

With this condition Sequelize go down with error "Cannot call method 'map' of undefined"

But, if instead of $and use $or - everything is fine.

Sequelize ver 2.0.3
I find bug here:
/sequelize/lib/dialects/abstract/query-generator.js:1681

      if (value) {
        if (value.$or || value.$and) {
          binding = value.$or ? ' OR ' : ' AND ';

          value = value.$or.map(function (_value) {
            return self.whereItemQuery(key, _value, options);
          }).filter(function (item) {
            return item && item.length;
          });

          return value.length ? '('+value.join(binding)+')' : undefined;
        }
      }
	
``  value = value.$or.map ``
but, if we have $and - exception

**Comment by mickhansen** [comment]
How the f.. - Well that's my bad, i'll fix it later today.
