### ISSUE TITLE
set() for Virtual datatype does not work when doing updateAttributes()

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3221]
password_hash: DataTypes.STRING,
    password: { type: DataTypes.VIRTUAL,
        validate: {
            len: {args: [10, 20], msg:"password must be 10-20 characters" }
        },

        set: function(password) {
            var password_hash = bcrypt.hash(password, ...);
            this.setDataValue('password', password);
            this.setDataValue('password_hash', password_hash);
        }
    }

I try to update password:

    user.updateAttributes({ name: 'test', password: "password1" }).then(function(user)) {
        console.log(user);
    });

Which prints out:

```
{ id: 1,
  name: 'test',
  password_hash: '$2a$10$rdNZ4WqG8kLeH.cT2c2N8ONkXAMy5qAPV7cPrsqOgVg.uMncl53CW',
  password: 'password1' }
```

It looks like everything was updated. But actually, the new password hash is never set. It still holds the old password hash when `create()` was called to create the user for the first time. However, the name updates fine.

The SQL output is:

    Executing (default): UPDATE "Users" SET "name"='test', WHERE "id"=1

----
using postgres, sequelize 2.0.0-rc8.

**Comment by mickhansen** [comment]
`update` only updates exactly what is passed to it, which unfortuneatly does not work with VIRTUALS at the moment.

**Comment by billxinli** [comment]
Are there any plans on supporting this feature in the future?

**Comment by mickhansen** [comment]
@billxinli Not sure yet, have to discuss it - But i think so.
