### ISSUE TITLE
defaultValue: DataTypes.NOW generates bad SQL after 2.0.0-rc8

### ISSUE THREAD

**Issue by johnpwrs** [sequelize/sequelize#3226]
When using the property `defaultValue: DataTypes.NOW` in a model, the SQL generated when updating or inserting looks like this:

UPDATE \`table\` SET \`updated_at\`=\`key\` = 'NOW' WHERE \`id\` = 1

Example:

`module.exports = function(sequelize, DataTypes) {
var part = sequelize.define('part', {
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW
    }
})
}`

This seems to be happening on all versions after 2.0.0-rc8

**Comment by janmeier** [comment]
Works fine for me on master
