### ISSUE TITLE
Increment function has wrong documentation!

### ISSUE THREAD

**Issue by fourpixels** [sequelize/sequelize#3228]
Check this link: http://sequelize.readthedocs.org/en/latest/docs/instances/#incrementing-certain-values-of-an-instance

It's stated:
```js
User.find(1).then(function(user) {
  user.increment('my-integer-field', 2).then(/* ... */)
})
```

This actually creates an error:
```js
[Error: The parameter (value: 2) is no Object.]
```

I had to search in the code to find out that:
```js
instance.increment('number') // increment number by 1
instance.increment(['number', 'count'], { by: 2 }) // increment number and count by 2
instance.increment({ answer: 42, tries: 1}, { by: 2 }) // increment answer by 42, and tries by 1.
                                                       // `by` is ignored, since each column has its own value
```

Shouldn't be that hard to fix :)

**Comment by mickhansen** [comment]
Hmm i actually thought that old syntax still worked, @janmeier?

**Comment by fourpixels** [comment]
Yeah well it seems like there is code for this

```js
if (countOrOptions === undefined) {
  countOrOptions = { by: 1 };
} else if (typeof countOrOptions === 'number') {
  countOrOptions = { by: countOrOptions };
}

countOrOptions = Utils._.extend({
  by: 1,
  attributes: {},
  where: {}
}, countOrOptions);
```

but on the very first line a validation check is done and an error is thrown, so.. uhm, it's not working :)

**Comment by janmeier** [comment]
Hmm, my guess would be that we can just remove that validator.. I think that all the syntaxes are equally valid
