### ISSUE TITLE
Question: timezones sequelize JS

### ISSUE THREAD

**Issue by ErikvdVen** [sequelize/sequelize#3235]
We just found out that Sequelize sends the current timestamp to our database from a server in England (were we run some cronjobs every couple hours), and PostgreSQL adds a Dutch timezone to the timestamp... So the the times are wrong. Now the same problem might occur when users load our website from different countries (as soon as we make a decision to go live in different countries)...
I just found out that Sequelize has the ability to add timezones to the timestamps:
https://sequelize.readthedocs.org/en/latest/api/sequelize/

But do I need to add a JavaScript function who adds the right current timezone (of the user) to the options object? Or are there other possibilities?

**Comment by mickhansen** [comment]
@janmeier might have some insight here

As far as i remember we save dates with timezones for postgres, so there really shouldnt be any issue accross timezones for postgres.

**Comment by calvintwr** [comment]
I don't get this. The "time" which you recorded, regardless of where your user are located geographically, would represent an exact moment in time. They can't be wrong.

You should use a client-side library to convert the timestamptz, which would present to the use correctly the time in his/her timezone.

Also, you might want to set UTC as the default for your database. 

For more info:
http://justatheory.com/computers/databases/postgresql/use-timestamptz.html

**Comment by janmeier** [comment]
How are your timestamps created? By sequelize (timestamp with time zone) or something else?

In pg sequelize will send the timestamp with timezone information, which will be saved by pg (eg `2015-03-02 18:01:38.816 +02:00`) .When that value is converted to a JS date object, it will represent the same point in time. The `+XX:XX` part is set by `options.timezone`.

Perhaps you could post a couple of examples of which queries your happening and where you think something is wrong.

I can't determine from your issue if anything is actually wrong, or if it is just a question. If it is a question, then yes, sequelize handles timezones properly. The only exception are timestamp columns without timezone in postgres (see #3000)

**Comment by mickhansen** [comment]
@janmeier `options.timezone` is not needed with `new Date()` i assume?

**Comment by janmeier** [comment]
@mickhansen In the case of postgres, `options.timezone` controls the timezone of the date at the time of insertion, so it is not used when doing `new Date`, no

**Comment by janmeier** [comment]
Closing, no response
