### ISSUE TITLE
Execution of customized query return the resulting array TWICE

### ISSUE THREAD

**Issue by kkcheungus** [sequelize/sequelize#3236]
Execution of customized query return the resulting array TWICE.

A customized query  "userProjectsQueryString" is executed and result return as 
"projectRows"  
                  portalAdminModels.sequelize.query(userProjectsQueryString,
                                                      portalAdminModels.projects,
                                                      { raw:true }).then(function(projectRows)

When viewing the projectRows as JSON string using 
                     console.log(JSON.stringify({"projectRows": projectRows}));

Version 2.0.0-rc8   correct result where projectRows is an array of "projects"
{
"projectRows":
[
{"projectId":1,"projectName":"13002","dbName":"proj_cancer_13002"},
{"projectId":2,"projectName":"13006","dbName":"proj_cancer_13006"},
{"projectId":3,"projectName":"13007","dbName":"proj_cancer_13007"},
{"projectId":4,"projectName":"13008","dbName":"proj_cancer_13008"},
{"projectId":5,"projectName":"13010","dbName":"proj_cancer_13010"},
{"projectId":6,"projectName":"13015","dbName":"proj_cancer_13015"}
]

}

Version 2.0.3
{
"projectRows":
[

[
{"projectId":1,"projectName":"13002","dbName":"proj_cancer_13002"},
{"projectId":2,"projectName":"13006","dbName":"proj_cancer_13006"},
{"projectId":3,"projectName":"13007","dbName":"proj_cancer_13007"},
{"projectId":4,"projectName":"13008","dbName":"proj_cancer_13008"},
{"projectId":5,"projectName":"13010","dbName":"proj_cancer_13010"},
{"projectId":6,"projectName":"13015","dbName":"proj_cancer_13015"}
],

[
{"projectId":1,"projectName":"13002","dbName":"proj_cancer_13002"},
{"projectId":2,"projectName":"13006","dbName":"proj_cancer_13006"},
{"projectId":3,"projectName":"13007","dbName":"proj_cancer_13007"},
{"projectId":4,"projectName":"13008","dbName":"proj_cancer_13008"},
{"projectId":5,"projectName":"13010","dbName":"proj_cancer_13010"},
{"projectId":6,"projectName":"13015","dbName":"proj_cancer_13015"}
]

]

}

Actual code:

exports.findUserByUserId = function(userId, callbackFunction) {
    //console.log("PortalAdminDatabase = " + portalAdminDatabase);
    //portalAdminModels.sequelize.query("USE " + portalAdminDatabase).then(function() {
    //models.users.schema(portalAdminDatabase);
    portalAdminModels.users.find(
        {   where:   {userId: userId},
        }).then(function(loginUser) {
            var userProjectsQueryString = 
                    "select distinct " +
                    "p.projectId, p.projectName, p.dbName " +
                    "from " + portalAdminDatabase + ".users u " +
                    "join " + portalAdminDatabase + ".usersGroups  ug " +
                    "on u.userId = ug.userId " +
                    "join " + portalAdminDatabase + ".groups g " +
                    "on ug.groupId = g.groupId " + 
                    "join " + portalAdminDatabase + ".groupsProjects gp " +
                    "on g.groupId = gp.groupId " +
                    "join " + portalAdminDatabase + ".projects p " +
                    "on gp.projectId = p.projectId " +
                    "where u.userId =  " + userId +
                    " order by p.projectName" ;

                    //console.log("CUSTOMIZED SQL TO FIND PROJECTS for UserId " + userId); 
                    //console.log(userProjectsQueryString);
                    portalAdminModels.sequelize.query(userProjectsQueryString,
                                                      portalAdminModels.projects,
                                                      { raw:true }).then(function(projectRows) { 
                     loginUser.projects = projectRows;
                     console.log(JSON.stringify({"projectRows": projectRows}));
                     console.log(loginUser);
                     callbackFunction(loginUser);
                    });
            });
    //});
};

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/wiki/Upgrading-to-2.0#changes-to-raw-query
`sequelize.query('SELECT ...', { type: Sequelize.QueryTypes.SELECT})`

**Comment by streetkid** [comment]
I've also noticed that when doing raw Queries, the resulting array is 
[ [ { object } ] ] in 2.0.4
 where in 2.0.0 I get [ {object} ] 

Is this caused by the same reason?

**Comment by janmeier** [comment]
@streetkid yes
