### ISSUE TITLE
Create indexes adding a where clause (Conditional/Partial index)

### ISSUE THREAD

**Issue by lao** [sequelize/sequelize#3238]
I am using sequelize for a postgresql database with paranoid.

I have the current Table:

Table_A:
idB,
idC,
idD,
deletedAt

I want to create an unique index like for the following columns: (idB, idC, idD).

I created the index using migration.addIndex. And it created a problem because of paranoid.

Lets say we create an instance {idB:1, idC:2, idD:3}, and delete it. After, if we want to create another instance like {idB:1, idC:2, idD:3} we cant, because of the unique index, even though we "deleted" the previous one.

So I was forced to create the index like this:  (idB, idC, idD, deletedAt).

But there is a problem with index for NULL values. Postgres doesn't throw unique constraint if we try to add the following instance twice {idB:1, idC:2, idD:3, deletedAt:null}.

You can see this issue on the following stackoverflow post: http://stackoverflow.com/questions/8289100/create-unique-constraint-with-null-columns

So, to do something to solve the problem I have to create two indices. Like this:

CREATE UNIQUE INDEX "Table_A_unique_index_with_deletedAt"
  ON "Table_A"
  USING btree
  ("idB", "idC", "idD", "deletedAt")
 WHERE "deletedAt" IS NOT NULL

CREATE UNIQUE INDEX "Table_A_unique_index_without_deletedAt"
  ON "Table_A"
  USING btree
  ("idB", "idC", "idD")
 WHERE "deletedAt" IS NULL

The problem is that currently sequelize wont let me create an index with a where clause and I believe that sequelize should have this feature.

And whe using the sync option sequelize should automatically create these 2 indices for paranoid tables, dont you think?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/2696 some work was done here but is not ocmplete.

**Comment by mickhansen** [comment]
Implemented per https://github.com/sequelize/sequelize/commit/1d22f4043c01d91b4470dc5600ec39678d6d2cc3

**Comment by lschnoller** [comment]
Is this still an issue? couldn't find the solution anywhere else.

**Comment by Greg-Hamel** [comment]
There seems to be an undocumented behaviour when using indices, where an index can have a `where` clause.

This is as per the information provided by @mickhansen above and how it is implemented within the codebase.
This works under v6, haven't taken the time to check with v7, and using Postgres 11+.

### Example

Imagine a table which contains a vast amount of events, with a boolean field representing their "acknowledgement" or "processing". If looking for all "unacknowledged" events and the vast majority are `acknowledged = True` an index with a condition of `asked = false` is much faster to get the results.

```js
sequelize.define(
  events,
  {
    created: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    device: {
      type: DataTypes.STRING(16),
    },
    data: {
      type: DataTypes.JSONB,
    },
    acknowledged: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
  },
  {
    timestamps: false,
    indexes: [
      {
        name: 'unacknowledged_false',
        using: 'BTREE',
        fields: ['acknowledged'],
        where: { acknowledged: { [Op.eq]: false } }, // Undocumented feature
      },
    ],
  }
);

Hope this helps others! 

Cheers
