### ISSUE TITLE
Can we do this?

### ISSUE THREAD

**Issue by cfltdf** [sequelize/sequelize#3242]
I just want to import model(s) from an existing database or SQL script.
That means when I already have a database built by MySQL Workbench, and I want to use it in sequelize. But coding with the model is not a happy job. So is there an easy way to do this just like what LINQ does?

**Comment by mickhansen** [comment]
Please provide titles that give a clue to the contents of the issue, so they are searchable etc.
Sequelize only natively supports defining models the way the documentation describes it, but it should be trivial for you to write a script that transforms your dump into sequelize models.
