### ISSUE TITLE
ForeignKey not working for belongsToMany relations

### ISSUE THREAD

**Issue by Sharian** [sequelize/sequelize#3248]
Hi, 

The created SELECT statement to fetch mn-related data is using the default id instead of the given foreign keys. 

i define my relations like this: 
```js
User.belongsToMany(models.Request,
                    {
                        through: "User_has_Request",
                        foreignKey: "User_ID"
                    });

Request.belongsToMany(models.User, 
                    {
                        foreignKey: 'Request_ID', 
                        through: 'User_has_Request'
                    }
```

later I try to find Requests like this: 
```
return db.Request.findAll({include: [
                {
                    model: db.User
                }
            ]});
```

Did I miss something in specifying the models  or is this actually a bug. 

Thanks in advance, 
Marco

**Comment by janmeier** [comment]
Please show the generated SQL, and where you believe there is an error.

The relations you have shown should create a junction table with the keys `User_ID` and `Request_ID`

**Comment by Sharian** [comment]
Ohh the actual SELECT is quiet long, is the error message enough information:

Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'Users.User_has_Request.UserId' in 'on clause'.

I'm currently not using sequalize to create my mysql schemas, as I'm using mysqlworkbench. That's why I specify foreignKeys on my own :)

**Comment by mickhansen** [comment]
What version are you using? We recently fixed some bugs with otherKey inferring and 2 x belongsToMany.

**Comment by Sharian** [comment]
Ohh I'm sorry: It should be the current version as I ran npm update --save some minutes ago.

The JOIN-sections of the SQL Statement: 

```LEFT OUTER JOIN (`User_has_Request` AS `Users.User_has_Request` 
INNER JOIN `Users` AS `Users` ON `Users`.`id` = `Users.User_has_Request`.`UserId`) 
ON `Request`.`id` = `Users.User_has_Request`.`Request_ID`;
```

**Comment by mickhansen** [comment]
Could you please try against master? Fixed something recently.

**Comment by Sharian** [comment]
It works :)

**Comment by mickhansen** [comment]
Great :)
