### ISSUE TITLE
Instance methods not attach to found/created object

### ISSUE THREAD

**Issue by nkt** [sequelize/sequelize#3249]
I've separate small piece of code:
```js
const bcrypt = require('bcrypt');
const hash = sequelize.Promise.promisify(bcrypt.hash);
const compare = sequelize.Promise.promisify(bcrypt.compare);

var User = sequelize.define('User', {
    username: DataTypes.STRING(255),
    password: DataTypes.STRING(60)
}, {
    instanceMethods: {
        checkPassword(password) {
            return compare(password, this.get('password'));
        }
    },
    hooks: {
        beforeCreate(user, options, next) {
            return hash(user.get('password'), 8).then(hash => {
                user.set('password', hash);
                return user;
            }).complete(next);
        }
    }
});

User.create({
    username: 'nkt',
    password: '123'
}).then((user) => {
    return user.checkPassword('123');
}).then((correct) => {
    console.log({correct});
}).catch((error) => {
    console.error({error});
});
```
This code produce:
```
[TypeError: Object [object SequelizeInstance] has no method 'checkPassword']
```

**Comment by janmeier** [comment]
Seems to work fine for me (albeit I had to convert the code to ES5 :) )

I did have to remove the beforeCreate hook since I don't have bcrypt installed. Can you try removing that, and see if the issue persists?

**Comment by nkt** [comment]
@janmeier actually this is not sequelize problem. I'm using vagrant, and firstly made mistake in method name `sheckPassword`, but this file wasn't updated correctly.
Anyway, thanks for help!

Actually I have another question - is there simple way to update password on `create` and `update`, instead of just `create`, without creating second listener?

**Comment by mickhansen** [comment]
@nkt no you need both a beforeCreate and beforeUpdate currently.
