### ISSUE TITLE
Include associations on an association model

### ISSUE THREAD

**Issue by saelfaer** [sequelize/sequelize#3250]
Is it possible to include a relation to the original item when querying on an association model itself?

example:

if you have `User` and `Task` these two can be indirectly related via a `UserTask` (which would be needed because there are extra properties on the UserTask relation.

so 

`User.belongsToMany(Task, {through: UserTask, foreignKey: 'userUuid' });`
`Task.belongsToMany(User, {through: UserTask, foreignKey: 'taskUuid' });`

now,  can i do something like this?:

```
UserTask
    .all({
        include: [
            { model: User },
            { model: Task }
        ]
    })
    .then(function(){ /* handle stuff */ });
```

**Comment by janmeier** [comment]
In order to do that you would need to manually set up the relation between UserTask and User etc: `UserTask.belongsTo(User, ...)`

**Comment by saelfaer** [comment]
hm, let me try that tomorrow morning... will that play nice with the existing relations that go over that join table?

**Comment by janmeier** [comment]
No response, closing
