### ISSUE TITLE
Improve indexes with operator classes

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3251]
Hey,

I really appreciate that you inserted sequelize functions on indexes but what's still missing is the operator class in Postgres (http://www.postgresql.org/docs/9.4/static/indexes-opclass.html).

This feature is really nice to speed up fuzzy search querys.

**Comment by mickhansen** [comment]
Will definitely be needed for JSONB indexes for defining GIN and path indexing.

**Comment by mickhansen** [comment]
`operator` will be implemented in https://github.com/sequelize/sequelize/issues/3471
