### ISSUE TITLE
Model.save() does not return instance

### ISSUE THREAD

**Issue by sjlu** [sequelize/sequelize#3254]
Not sure if this is intentional or not, I'll close if it is.

In previous versions, when you did `.save()` on an instance, it would return a reference of that instance. 

For example:
```
exampleModel.save().then(function(returnedExampleModel) {
    console.log(returnedExampleModel);
});
```

In the past, `returnedExampleModel` would have the model. From 2.0.3, this is now undefined, is this intentional?

**Comment by sjlu** [comment]
This test says otherwise too:

https://github.com/sequelize/sequelize/blob/master/test/integration/instance.test.js#L83

**Comment by mickhansen** [comment]
@sjlu that test is for isNewRecord though.

**Comment by mickhansen** [comment]
`save` should very much so return an instance, a lot of tests depend on it. Something in your code must be off.

**Comment by sjlu** [comment]
It definitely could be wrong on my end, let me get back to you.

**Comment by sjlu** [comment]
Yes, something wrong on my end :), closing.
