### ISSUE TITLE
Migrations don't work

### ISSUE THREAD

**Issue by rootStar-lock** [sequelize/sequelize#3259]
I found that migration *down* event don't clean **SequelizeMeta** while migrations is reversed. Original code is here https://github.com/sequelize/sequelize/blob/master/lib/migrator.js#L38. Without that line code work well in postgress.

**Comment by mickhansen** [comment]
Migrations in Sequelize core are indeed severely broken.
@sdepold have moved the project out of core and is working on a migrations/tasks project here: github.com/sequelize/umzug

**Comment by rootStar-lock** [comment]
Thank you Mike.

**Comment by sdepold** [comment]
Please note that the actual migration execution (in terms of the command to run the migrations) is over at the CLI: https://github.com/sequelize/cli
