### ISSUE TITLE
Document how to use migrations programmatically

### ISSUE THREAD

**Issue by evantahler** [sequelize/sequelize#326]
Hi! 

I use sequelize migrations programmatically rather than the binary, and I wanted to share how I was able to get it to work.  Perhaps this will help others:

``` javascript
var configData = configData || {};

configData.mySQL = {
  database: 'myDB',
  username: 'root',
  password: null,
  host: '127.0.0.1',
  port: 3306,
}

var SequelizeBase = require("sequelize");
var sequelize = new SequelizeBase( configData.mySQL.database,  configData.mySQL.username,  configData.mySQL.password, {
  host:  configData.mySQL.host,
  port:  configData.mySQL.port,
  logging: false,
  dialect: 'mysql',
});

var migrator = sequelize.getMigrator({path: process.cwd() + "/migrations" }, true)
migrator.migrate().success(function(){
  console.log("migrations complete");
}).error(function(err){
  console.log("error migrating DB: ");
  throw err;
  process.exit();
});
```

**Comment by rafis** [comment]
How to run migrator programmatically after it has been divided in separate project `sequelize-cli` and `umzug`? Need for tests.

**Comment by mickhansen** [comment]
@rafis please open issues about umzug on the umzug repo.

**Comment by iDVB** [comment]
This is helpful, thanks @evantahler 
I trying to read up as much as I can about migrations, but what does the above code look like in the greater context of, say a CI/CD pipeline... how does it know which of the migrations have already been run or not. Does that mean that the `/migrations` dir will contain EVERY migration ever applied to that DB forever. (that could grow rather fast, no?)

**Comment by evantahler** [comment]
@iDVB that's built in.  Sequelize creates a table in your DB which tracks which migrations have run already.  It's safe to run this often, on every deployment and every CI run.

**Comment by iDVB** [comment]
Great! Thanks @evantahler I'm deep into setting it up now. Seems to be working pretty good. However, its the initial schema push that I'm stumped on. Out of the box my application uses Sequelize to inject the empty schema/tables into the db (if db empty) on first init. 

However, if I want to use migrations and seeding that currently would require 
```
1) run the app (which creates the schema tables)
2) stop the app in order to CI the rest of the commands
3) run the migrations
4) run the seeder
5) run the app
```

that because I can't seem to find a way to repurpose the "app Models" to create migrations that could do the same without needing to start the app. Cut and pasting each of the models doesnt quite sit well with me. What really seems to be missing is an automated tool to [generate these init migrations](https://github.com/sequelize/cli/issues/388) 

Open to any ideas how to ease this process.

**Comment by andrew-aladev** [comment]
Hello. Today it is enought to run this code:

```ruby
const sequelize = new Sequelize(config);
const umzug     = new Umzug({
  storage: "sequelize",

  storageOptions: {
    sequelize: sequelize
  },

  migrations: {
    params: [
      sequelize.getQueryInterface(),
      Sequelize
    ],
    path: MIGRATIONS_PATH
  }
});

return umzug.up();
```

All your migrations will be applied and that's it.

**Comment by hackhat** [comment]
My code is in typescript, therefore migrations are in typescript as well. Is there anyway to pass the migrations as an object instead of providing the folder for umzug to lookup?

**Comment by A-Atrash** [comment]
Without any library and with only child_process and basic CLI command:
`const execSync = require('child_process').execSync;

const createDb = () => {
  return new Promise((resolve, reject) => {
    try {
      execSync('node_modules/.bin/sequelize db:create', { stdio: 'inherit' });
      resolve('OK');
    } catch (e) {
      reject(e);
    }
  });
};

const migrate = () => {
  return new Promise((resolve, reject) => {
    try {
      execSync('node_modules/.bin/sequelize db:migrate', { stdio: 'inherit' });
      resolve('OK');
    } catch (e) {
      reject(e);
    }
  });
};

createDb().then(() => migrate());`

If you are using any server that runs a 'build' before deploying (like Heroku) you can add your migration module before the rest of your "build" script:
`"build": "node ./migrate.js && ....."`

**Comment by rootguigui** [comment]
Thank @A-Atrash it`s work. I add these function in my code and its work. Only modifies that I did are.

const execSync = require('child_process').execSync;

function createDb() {
  return new Promise((resolve, reject) => {
    try {
      execSync(__dirname + '../../node_modules/.bin/sequelize db:create', { stdio: 'inherit' })
      resolve('db create')
    } catch(e) { reject(e) }
  })
}

function migrate() {
  return new Promise((resolve, reject) => {
    try {
      execSync(__dirname + '../../node_modules/.bin/sequelize db:migrate', { stdio: 'inherit' })
      resolve('do all migrate')
    } catch (e) {
      reject(e)
    }
  })
}

module.exports.createDb = createDb
module.exports.migrate = migrate

**Comment by rootguigui** [comment]
I added __dirname in path

**Comment by vafrcor** [comment]
Thanks to @A-Atrash and  @rootguigui code , I have create simple node module to run migrator programmatically.

> Note: This script only used for TESTING environment only. Use at PRODUCTION at your own risk.

Source code: https://gist.github.com/vafrcor/db503cc0cf568ff13159abfdee5cb5b8

Dependency Packages:
- child_process (required)
- [lodash](https://www.npmjs.com/package/lodash) (required)
- [async](https://www.npmjs.com/package/async) (required)
- [app-root-path](https://www.npmjs.com/package/app-root-path) (optional)

How to use:
```node
const approot = require('app-root-path');
let migrator = require(approot + '/database/sequelize-migrator.js')({
  debug: true,
  drop_existing_db: false,
  drop_tables: true,
  migration: true,
  seed: true
});

migrator.exec();
```
