### ISSUE TITLE
Error when trying to decrement an UNSIGNED integer attribute

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#3262]
`SequelizeDatabaseError: ER_DATA_OUT_OF_RANGE: BIGINT UNSIGNED value is out of range in ...`

If we try to decrement an `UNSIGNED` attribute which is already `0`, an error is thrown by database.

My question is: should we throw an error or maintain `0` value?

**Comment by mickhansen** [comment]
Well an error is already thrown by the looks of it :)
increment & decrement are supposed to be atomic, checking the "final" value beforehand would conteract that.

**Comment by cusspvz** [comment]
We fixed this already internally by applying a condition statement.

I will rephrase my question :+1: .
Its better to keep things as they are (keeping mysql, in this case, to throw an out of range error) or apply a mysql formula to don't allow negative numbers decrementing when unsigned?

**Comment by mickhansen** [comment]
What would that mysql formula look like?
I don't think we should do anything here, can't always protect users against getting their application into a bad state - Actually i think an explicit error is better than a silent fail here (somebody did something wrong for the data to get into that state).

**Comment by cusspvz** [comment]
> What would that mysql formula look like?

Conditional `IF`

> ... can't always protect users against getting their application into a bad state

But you're right, I was kind of divided but I wasn't seeing the bad state part.

Before closing this issue, should we add an alert on docs to warn developers about decrementing whenever they increment with conditional statements?

**Comment by mickhansen** [comment]
@cusspvz Well if they are incrementing with conditionals they should certainly decrement with conditions aswell i'd say :)

Sure, a docs addition would be welcome. Closing this issue.

**Comment by cusspvz** [comment]
Thanks!

I will try to add something to docs later.
