### ISSUE TITLE
Removing timestamp columns from many-to-many junction table

### ISSUE THREAD

**Issue by thebinarypenguin** [sequelize/sequelize#3266]
I'm having an issue with timestamp columns (created_at and updated_at) showing up in my junction tables

Example:
```js
var Sequelize = require('sequelize');

// Create a connection instance
var sequelize = new Sequelize(null, null,  null, {
  dialect: 'sqlite',
  storage: './test-timestamps.sqlite3',
  define: {
    timestamps: false  // I don't want timestamp fields by default
  },
});

// Define Note model
var Note = sequelize.define('note', {
  body: { type: Sequelize.TEXT },
}, {
  timestamps: true,  // I do want timestamps here
});

// Define Tag model
var Tag = sequelize.define('tag', {
  name: { type: Sequelize.STRING(100), unique: true, allowNull: false },
});

// Define n:m relationship between Notes and Tags
Note.belongsToMany(Tag, {through: 'notes_tags'});
Tag.belongsToMany(Note, {through: 'notes_tags'});

// Write schema to database
sequelize.sync({force: true});
```

**Problem:** The `notes_tags` table contains the `created_at` and `updated_at` timestamp columns (and I don't want it to)

I figured setting `timestamps: false` in the global options would fix this, but no such luck. This also appears to be related to issue #739

**Comment by janmeier** [comment]
Hmm, I thought we had actually removed timestamps for through tables completely @mickhansen ?

@thebinarypenguin For now you can do
```js
var NotesTags = sequelize.define('notes_tags', {

}, {
  timestamps: false
})

Note.belongsToMany(Tag, {through: NotesTags});
Tag.belongsToMany(Note, {through: NotesTags});
```

**Comment by mickhansen** [comment]
@janmeier only paranoid AFAIR

**Comment by janmeier** [comment]
Ah right :)

In that case, the correct solution is posted above @thebinarypenguin

**Comment by thebinarypenguin** [comment]
@mickhansen , @janmeier Is there any chance of getting these through/junction tables to respect the global `timestamps: false` setting?

**Comment by mickhansen** [comment]
@thebinarypenguin yeah tagging as a bug, it's not intended.

**Comment by janmeier** [comment]
The issue is that it is taking the timestamps option from the Note model. Perhaps being able to pass `{through: 'notes_tags', timestamps: false });` would be sufficient?

**Comment by mickhansen** [comment]
@janmeier ah right, it will do what it's source does.

**Comment by chrisbjr** [comment]
I agree with @janmeier. That's what I instinctively tried to do when I found myself in this situation.

**Comment by EliasChampi** [comment]
Thank

> The issue is that it is taking the timestamps option from the Note model. Perhaps being able to pass `{through: 'notes_tags', timestamps: false });` would be sufficient?

**Comment by william-deckard** [comment]
Is this documented anywhere? This was such a pain to find *tears*...
