### ISSUE TITLE
No array overlap in where of eager load in 1.7.9 (PG)

### ISSUE THREAD

**Issue by Roam-Cooper** [sequelize/sequelize#3268]
We are still on 1.7.9 and running PG (believe me, I am pushing at work for the time to move to your most recent version...)

And I noticed that if I have a column whose type is array of text, in the models where I can check against an array and Sequelize will produce the SQL: "&& ARRAY['value']::TEXT[]" (this is what I want, array overlap)

But in the where statements in includes (and in nested includes) when I check against an array Sequelize produces the SQL: "IN ('value')" which results in PG erroring with "array value must start with "{" or dimension information"

I know this is an old version, so I don't expect any sort of solution, but I thought I'd create the issue just to see if anybody else experienced this problem and to learn if/how they managed to fix it. I've checked that the column in question in every table is array of text and I can't think of anything else, Sequelize just seems to be changing the array statement it generates depending on whether it is for an include or not.

Are array overlaps supported in includes and why do the current includes generate invalid SQL?

EDIT: the issue also occurs in 1.7.10, which seems to be the best version before I'd have to switch to >=2.0.0 incompatible

**Comment by Roam-Cooper** [comment]
For posterity, each of our models include a column like so:
```javascript
foo: {
        type: DataTypes.ARRAY(DataTypes.TEXT)
}
```

And the operation in question is something like:

```javascript
someModel.findAll({
            where: {
                someColumn: ['value']
            },
            include: {
                model: associatedModel,
                required: true,
                where: {
                    someColumn: ['value']
                }
            }
        }).success().failure();
```

What happens (as I mentioned initially) is that Sequelize generates the query correctly for the where statement and uses the array overlap operator ("&&") along with ARRAY[] syntax, but for where statements in any includes (including nested includes) Sequelize generates SQL that uses the "IN" operator and uses "('value')" syntax for the array data to compare to.

Hopefully this is enough information to get some sort of lead going. :)

**Comment by janmeier** [comment]
Thanks for the well explained bug report!

Unfortunately I doubt any of the core contributors will have time to look at your issue - we have plenty of 2.0 issues. 

You are very welcome to investigate and provide a PR yourself and I will gladly review it but I doubt there is much more we can do

**Comment by mickhansen** [comment]
Strange that overlap actually worked with you like that, pretty sure it should be defaulting to something else.
In any case 2.0 has specific `&&/$overlap` operators for where conditions.

**Comment by janmeier** [comment]
Closing this. `$overlap` is supported by 2.0 but unlikely to be ported to 1.7
