### ISSUE TITLE
inject model values when using defaultValue as a function

### ISSUE THREAD

**Issue by neekey** [sequelize/sequelize#3272]
Hi, I want to generator a string primary key based on the model values (  like creating a hash ) by providing the `defaultValue` option as a function, now the only problem is inside the function I have no way to get the values.

Here is what in my mind:

``` js
sequelize.define("record", {
        version: {
            type: DataTypes.STRING,
            primaryKey: true,
            unique: true,
            defaultValue: function( values ){
                return createHash( values.data ); // something like this, unique will be assured
            }
        },
        data: DataTypes.STRING,
        date: DataTypes.DATE,
        message: DataTypes.TEXT,
        committer_id: DataTypes.INTEGER
    }
```

**Comment by mickhansen** [comment]
Interesting idea, i see the merit.
You could achieve it with hooks for the time being.

**Comment by janmeier** [comment]
I see the merit, and it could be pretty easily solved by changing `defaultFunc()` to `defaultFunc.call(values)`.

However, what happens if we have to default functions - which one should be invoked first, and be able to access the values the other function created?
I think the best and most complete solution is to use hooks

**Comment by neekey** [comment]
@mickhansen That's how I implement this right now ~

**Comment by ianjuma** [comment]
+1

**Comment by ianjuma** [comment]
There's  just one problem, using the beforeCreate hook with allowNull set as false on an attribute. It fails to save. Is there a different hook, or a custom one to run earlier... 

...
```javascript
{
        hooks: {
            beforeCreate: function(vehicle, options, fn) {
              vehicle.front_image_url = vehicle.license_plate + '-front';
              vehicle.interior_image_url = vehicle.license_plate + '-interior';
              vehicle.back_image_url = vehicle.license_plate + '-back';

              fn(null, vehicle);
            }
        },
        underscored: true,
        classMethods: {
            underscored: true,
            associate: function(models) {
                Vehicle.hasOne(models.Listing);
            }
        }
    });
```
```javascript
{
"error": {
"name": "SequelizeValidationError",
"message": "notNull Violation: front_image_url cannot be null,\ notNull Violation: interior_image_url cannot be null,\ notNull Violation: back_image_url cannot be null",
"errors": [
{
"message": "front_image_url cannot be null",
"type": "notNull Violation",
"path": "front_image_url",
"value": null
}
]
}
}
```
right now, allowNull is true

**Comment by mickhansen** [comment]
@ianjuma The `beforeValidate` runs before validations take place, `beforeUpdate` takes place after validations and just before saving.

**Comment by ianjuma** [comment]
aha! so the earliest possible hook, it works fine. hooks are just as clean. Thanks!
