### ISSUE TITLE
Transaction error in destroy()

### ISSUE THREAD

**Issue by mrpotato3** [sequelize/sequelize#3276]
Hi!

I have a problem when I try to do a rollback() after error in destroy function with paranoid enabled (it's a update in fact).

This problem seems to be occurred by a bad transaction id when sequelize makes the update (I attach log output).

```javascript
sequelize.transaction().then(function (t)
{
    ModelA.destroy({where: {uuid: arrayOfIds}}, {transaction: t}).then(function (affectedRows)
    {
        if (affectedRows !== arrayOfIds.length)
        {
            t.rollback();
            return;
        }

        // (...)
}).catch(function (DatabaseError)
{
    t.rollback();   // <-- Crashes here
});
```

* Executing (820e04de-e898-4bd6-b61a-2ae382b24676): START TRANSACTION;
* Executing (820e04de-e898-4bd6-b61a-2ae382b24676): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
* Executing (820e04de-e898-4bd6-b61a-2ae382b24676): SET autocommit = 1;
* Executing (default): UPDATE "ModelA" SET "deletedAt"='time' WHERE "id" IN (1)    // <-- Problem is here, sequelize picks a default transaction not assigned transaction (820e04de-e898-4bd6-b61a-2ae382b24676)
* Executing (820e04de-e898-4bd6-b61a-2ae382b24676): ROLLBACK;

Many thanks!

**Comment by janmeier** [comment]
`destroy` takes only a single argument http://docs.sequelizejs.com/en/latest/api/model/#destroyoptions-promiseundefined

`ModelA.destroy({where: {uuid: arrayOfIds}, transaction: t})`

**Comment by mrpotato3** [comment]
oookei... thanks. :X

**Comment by amsingh-qasource** [comment]
stuck with the same issue. Thanks @janmeier

**Comment by cjancsar** [comment]
This is no longer the case (2019)

**Comment by petr-hybler** [comment]
thx @janmeier  .... weird that all others have two args but this one has only one .. anyway,worked for me :)
