### ISSUE TITLE
Is there any option for create bulk asociations?

### ISSUE THREAD

**Issue by mrpotato3** [sequelize/sequelize#3277]
I need to create bulk instances with associated options (n:m relation) and I want to insert this options in bulk too.

There's any option to avoid single insert?
There's any option to query directly the join table?

Thanks.

**Comment by janmeier** [comment]
createMultiple on associations is not supported currently.

If you define the join table manually, you can query it directly: 

```js
var Through = sequelize.define('through', ...);

X.belongsToMany(Y, { through: through });
Y.belongsToMany(X, { through: through });
```

**Comment by mrpotato3** [comment]
okei. I'll try with join table. thanks! :)

**Comment by johnnyPescarul** [comment]
+1 I think the bulk create with associations would be a useful feature. Any plans to implement it? Right now If I have a Parent Child relation and I populate the children array on the parent, bulkCreate does not save the children.

**Comment by bigopon** [comment]
I managed to make sequelize save the children, but even when saved successfully, an error will be thrown

**Comment by wzup** [comment]
@bigopon Why didn't you include the code?

**Comment by wzup** [comment]
@janmeier Is there any progress with `bulkCreate` with associations since Mar 4, 2015?

**Comment by felixfbecker** [comment]
@wzup not afaik. feel free to implement it

**Comment by toddsby** [comment]
@felixfbecker 🙈 😂 👍

**Comment by bigopon** [comment]
@wzup sorry it didn't really work the expected way, I created a bunch of promises, each was a single create

**Comment by raxod502** [comment]
> If this is still an issue, just leave a comment 🙂

This is definitely still an issue, as far as I can tell. Unless support for bulk creating objects with associations has been added, and the documentation was not updated?

I don't really think feature requests should be closed automatically due to lack of activity. It's not like the features are going to magically appear if nobody is talking about them :)

**Comment by adkl** [comment]
Yeah, this definitely is an issue. It's too complicated to achieve write queries now

**Comment by raxod502** [comment]
Is there a workaround? I'm fine with doing things in an awkward way if I have to, but creating objects one at a time is not an option. I can bulk create the parent and child objects separately, but this doesn't establish the relation between them correctly AFAICT.

**Comment by SirWojtek** [comment]
@raxod502 You can try creating parent + child + associate using `Transaction` object. This approach gives you atomic bulk create with associations. Although, for many records, this probably will be very slow.
Are there any technical issues to implement `bulkCreate` with associations?

**Comment by raxod502** [comment]
@SirWojtek Well sure, if I do it that way it'll work, but then I'm creating objects one at a time so I'm not using bulkCreate in the first place—and the reason I need bulkCreate is because I'm adding thousands of records. (Unless I misunderstand your suggestion.)

I'd be curious about the technical challenges, as well.

**Comment by corysimmons** [comment]
Might be possible to stash each part of your request in different objects and run `bulkCreate` on each individually.

**Comment by SirWojtek** [comment]
Something like that:
1. Make some non-persistent instances with `build`
2. Run `bulkSave` <-- this is not implemented

**Comment by AzureusSme** [comment]
+1

**Comment by jenniferneale** [comment]
+1

**Comment by zsh1313** [comment]
+1

**Comment by eth0izzle** [comment]
+1

**Comment by TdevM** [comment]
+1

**Comment by nickgeorgiou** [comment]
+1

I was able to insert bulk associations in a single separate query by creating a separate model for the N:M association. So I have my PostTags model and then I have PostId and TagId and can do 

`PostTags.bulkCreate([{postId: 1, tagId: 1}, {postId: 2, tagId: 1}])`

**Comment by giga8man** [comment]
+1

**Comment by lmshaffe** [comment]
+1

**Comment by francessco410** [comment]
+1

**Comment by daviseford** [comment]
+1

**Comment by fedealconada** [comment]
+1

**Comment by jameskennethrobinson** [comment]
+1

**Comment by botaniQQQ** [comment]
4 years =)

Maybe in 5 version add?

**Comment by lpedromachado** [comment]
+1

**Comment by DenisRupp** [comment]
+1

**Comment by dan-cummings1** [comment]
I'm seeing a lot of references back to this. Has there been any progress on how to handle these situations?

**Comment by ioanmeri** [comment]
Was facing the same issue..
For
Canvas.hasOne(models.CanvasDetail,{
      foreignKey: 'canvas_id',
      as: 'canvasDetail',
})
I tried this:
// separate incoming data into the 2 tables: sqlCanvases, sqlCanvasDetails
// bulk create sqlCanvases
// then for each saved canvas, set the foreignKey in canvasDetails table
//   & bulk create sqlCanvasDetails

var canvas = req.body.data;
var sqlCanvases = [];
var sqlCanvasDetails = [];

if(canvas.enter.length){
    canvas.enter.forEach(function(element) {
        sqlCanvasData = {
           title: "test canvas",
           UserId: req.user.id
        }
        sqlCanvases.push(sqlCanvasData);

        sqlCanvasDetailsData = {
          scale: element.data.props.scale,
          zoom: element.data.props.zoom,
          width:  element.data.width,
          height: element.data.height
        }
        sqlCanvasDetails.push(sqlCanvasDetailsData);
    })

    db.Canvas.bulkCreate(sqlCanvases)
    .then(function(data) {
         data.forEach(function(el, i){
            sqlCanvasDetails[i].canvas_id = el.id;
        })

        db.CanvasDetail.bulkCreate(sqlCanvasDetails)
        .then(function(data){
            res.send('okkk');
        })
    })
}
seems to be in order at localhost for 30 entries
no catches yet

**Comment by luismramirezr** [comment]
> +1
> 
> I was able to insert bulk associations in a single separate query by creating a separate model for the N:M association. So I have my PostTags model and then I have PostId and TagId and can do
> 
> `PostTags.bulkCreate([{postId: 1, tagId: 1}, {postId: 2, tagId: 1}])`

This helped me a lot!

Does this still the only/prefered method? 

Thanks!

**Comment by hexerei** [comment]
well, so now it is implemented since version 5.14.0 by allowing the include attribute in the bulk insert, but is there in fact a documentation for this?

**Comment by hexerei** [comment]
actually found it in documentation now and works fine for hasMany relations, but there are some things missing for belongsToMany.
i.e. looking at Game, Team, Player sample, i tried simulating this with bulk inserts:

```
  await Game.bulkCreate([
    { name: 'The Big Clash', Teams: [{ id: 1, name: 'The Martians' }, { id: 2, name: 'The Earthlings' }] },
    { name: 'Winter Showdown', Teams: [{ id: 1, name: 'The Martians' }, { id: 3, name: 'The Plutonians' }] },
    { name: 'Summer Beatdown', Teams: [{ id: 2, name: 'The Earthlings' }, { id: 3, name: 'The Plutonians' }] }
  ], { include: [ Team ] });

  await Player.bulkCreate([
    { username: 's0me0ne', Teams: [{ id: 1, name: 'The Martians' }] },
    { username: 'empty' },
    { username: 'greenhead', Teams: [{ id: 1, name: 'The Martians' }] },
    { username: 'not_spock', Teams: [{ id: 3, name: 'The Plutonians' }] },
    { username: 'bowl_of_petunias', Teams: [{ id: 3, name: 'The Plutonians' }] }
  ], { include: [ Team ] });

```

now this leads into an error, since sequelize is trying to insert teams that already exist. I have seen there is something like an **updateOnDuplicate** option, but is there actually also an **ignoreOnDuplicate**?

**Comment by hexerei** [comment]
Tried implementing the above sample by including the `updateOnDuplicate` option, which works fine for the main model object table, and the associated table, but it does not work for the association table itself, as then `ON DUPLICATE KEY UPDATE` is added there without parameters, which throws an error:

```Javascript
  await Game.bulkCreate([
    { name: 'The Big Clash', Teams: [{ id: 1, name: 'The Martians' }, { id: 2, name: 'The Earthlings' }] },
    { name: 'Winter Showdown', Teams: [{ id: 1, name: 'The Martians' }, { id: 3, name: 'The Plutonians' }] },
    { name: 'Summer Beatdown', Teams: [{ id: 2, name: 'The Earthlings' }, { id: 3, name: 'The Plutonians' }] }
  ], { include: [{ model: Team, updateOnDuplicate: ['name'] }] });
```

The SQL sequelize creates looks like this then:

```SQL
INSERT INTO `Games` (`id`,`name`,`createdAt`,`updatedAt`) VALUES
  (NULL,'The Big Clash','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (NULL,'Winter Showdown','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (NULL,'Summer Beatdown','2021-04-09 12:33:20','2021-04-09 12:33:20');
INSERT INTO `Teams` (`id`,`name`,`createdAt`,`updatedAt`) VALUES
  (1,'The Martians','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (2,'The Earthlings','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (1,'The Martians','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (3,'The Plutonians','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (2,'The Earthlings','2021-04-09 12:33:20','2021-04-09 12:33:20'),
  (3,'The Plutonians','2021-04-09 12:33:20','2021-04-09 12:33:20')
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `GameTeam` (`createdAt`,`updatedAt`,`TeamId`,`GameId`) VALUES
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',1,1),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',2,1),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',1,2),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',3,2),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',2,3),
  ('2021-04-09 12:33:20','2021-04-09 12:33:20',3,3)
  ON DUPLICATE KEY UPDATE;

```

So it works fine for the Games and Teams tables, but the `GameTeam` insert query throws an error because of the `ON DUPLICATE KEY UPDATE` without parameters.

Tried overcoming this by creating models for the `GameTeam` table, so I could add this to the includes and state the update fields:

```Javascript
  await Game.bulkCreate([
    { name: 'The Big Clash', Teams: [{ id: 1, name: 'The Martians' }, { id: 2, name: 'The Earthlings' }] },
    { name: 'Winter Showdown', Teams: [{ id: 1, name: 'The Martians' }, { id: 3, name: 'The Plutonians' }] },
    { name: 'Summer Beatdown', Teams: [{ id: 2, name: 'The Earthlings' }, { id: 3, name: 'The Plutonians' }] }
  ], { include: [{ model: Team, updateOnDuplicate: ['name'] }, { model: GameTeam, updateOnDuplicate: ['GameID','TeamId']}] });

```

This gave another error, stating that `GameTeam` is not related to `Game`. So simply defining my models association with:

```Javascript
Team.belongsToMany(Game, { through: GameTeam });
Game.belongsToMany(Team, { through: GameTeam });
```

was not enough, I had to do the full many-to-many-to-many definition:

```Javascript
Team.belongsToMany(Game, { through: GameTeam });
Game.belongsToMany(Team, { through: GameTeam });
GameTeam.belongsTo(Game);
GameTeam.belongsTo(Team);
Game.hasMany(GameTeam);
Team.hasMany(GameTeam);
```

Now `GameTeam` was allowed in the includes, but the `updateOnDuplicate` for `GameTeam` was still ignored, and the resulting 
SQL still had the `ON DUPLICATE KEY UPDATE` for the `GameTeam` table without parameters, hence still throwing an error.
