### ISSUE TITLE
Query Paranoid not working as expected

### ISSUE THREAD

**Issue by benjsicam** [sequelize/sequelize#3278]
Tried to do a query like this:
```
myModel.findAll({
    paranoid: false
})
.then(function (myModels) {
    console.log(myModels);
});
```
The returned result set is the same as querying like this:
```
myModel.findAll({
    paranoid: true
})
.then(function (myModels) {
    console.log(myModels);
});
```
The models have paranoid = true and timestamps = true on the options.

**Comment by janmeier** [comment]
Please use github flavored markdown to format code https://help.github.com/articles/github-flavored-markdown/

The paranoid option works fine for me, disabling / enabling the `deletedAt IS NULL` part as needed. 

Which version are you on? Do the queries look correct

**Comment by benjsicam** [comment]
I am using v2.0.3. Tried it again and it still doesn't work on mine. The SQL query being generated are:

Paranoid = false
```
SELECT `id`, `name`, `createddate`, `lastmodifieddate`, `deleteddate` FROM `users` AS `User` ORDER BY name ASC;
```
Paranoid = true
```
SELECT `id`, `name`, `createddate`, `lastmodifieddate`, `deleteddate` FROM `users` AS `User` WHERE `User`.`deleteddate` IS NULL ORDER BY name ASC;
```

**Comment by janmeier** [comment]
> If false, will include columns which have a non-null deletedAt column.

So true means return stuff which is not deleted, and false means delete everything

**Comment by benjsicam** [comment]
Yes, that is correct. If Paranoid = false, will include columns which have a non-null deletedAt column. So it should be using this query:

```SELECT `id`, `name`, `createddate`, `lastmodifieddate`, `deleteddate` FROM `users` AS `User` WHERE `User`.`deleteddate` IS NOT NULL;

**Comment by mickhansen** [comment]
@benjsicam No, that is the expected query for paranoid: true, paranoid: false will return everything.

**Comment by janmeier** [comment]
Clarified in https://github.com/sequelize/sequelize/commit/3c2071aa617613191d89a364e88773cc9c50abf3
