### ISSUE TITLE
How do I create a migration with index?

### ISSUE THREAD

**Issue by skwee357** [sequelize/sequelize#3281]
I know how to create migration for table creation (`migration.createTable('name', {..})`).
I know how to create migration that adds index (`migration.addIndex('name', ['column'])`);
I dont know how to combine those two into one migration file. Promise.all dosent work because it does not provide order in which the promises are run. And I dont want to split my table creation into two different migration files: one for the table itself, the second one for the indexes.

Thanks!

**Comment by skwee357** [comment]
Ok, I've finally had some time to work with sequelize again, so in case of anyone have the same issue, the answer is very simple:
```javascript
migration
  .createTable('table_name', {...})
  .then(function() {
    return migration.addIndex('table_name', ['column'], ...);
  })
  ..more then to add more indecies
  .complete(done);
```
Works fine!

**Comment by mickhansen** [comment]
Generally you'll just want to return the promise and then use then() to chain commands.
