### ISSUE TITLE
MSSQL insert/update/delete issues when triggers are enabled

### ISSUE THREAD

**Issue by shakdoesgithub** [sequelize/sequelize#3284]
When there is a trigger enabled on a table, the query that is generated is not correct.

For example:

we have a table contactNotes and a trigger on it, when doing an update the query is generated as 

`INSERT INTO [contactnotes] ([CreateDate],[DeleteDate],[LastUpdated],[ContactID],[Notes]) OUTPUT INSERTED.* VALUES ('2012-09-09T23:15:00.000Z','2012-09-09T23:15:00.000Z','2012-09-09T23:15:00.000Z','3097674','test notes');
`

The error that comes back is:
The target table 'contactnotes' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

The link: http://blogs.msdn.com/b/sqlprogrammability/archive/2008/07/11/update-with-output-clause-triggers-and-sqlmoreresults.aspx says we need to have the output into a table parameter

One work around was to set the output:false of returnvalues in the dialects file for mssql, but this broke the insert capability.

I think the only way to fix it is by adding the correct syntax that is mentioned in the link above

**Comment by mickhansen** [comment]
@mbroadst

**Comment by mbroadst** [comment]
@shakdoesgithub what version of mssql are you running?

**Comment by shakdoesgithub** [comment]
@mbroadst we are using msSQL 2012

**Comment by shakdoesgithub** [comment]
@mbroadst, I was able to hack a fix together for two queries: Insert and Update.

The queries are modified to include a variable table based on the model.  This only happens if the dialect has output for returnvalues.  The fix checks the column types and ignores virtual types.  It converts NVARCHAR columns to NVARCHAR(MAX), this is a hack for our project.  

Here's the gist file: https://gist.github.com/shakdoesgithub/8942e635f50bed09a3e4



Changes insert query:
https://gist.github.com/shakdoesgithub/8942e635f50bed09a3e4#file-query-generator-js-L172-L186
https://gist.github.com/shakdoesgithub/8942e635f50bed09a3e4#file-query-generator-js-L208-L238
https://gist.github.com/shakdoesgithub/8942e635f50bed09a3e4#file-query-generator-js-L289-L297

Changes for update query:
https://gist.github.com/shakdoesgithub/8942e635f50bed09a3e4#file-query-generator-js-L289-L297
https://gist.github.com/shakdoesgithub/8942e635f50bed09a3e4#file-query-generator-js-L357-L386
https://gist.github.com/shakdoesgithub/8942e635f50bed09a3e4#file-query-generator-js-L357-L386

**Comment by janmeier** [comment]
@shakdoesgithub Opening a PR would make it a lot easier to review your changes. PRs don't need to be finished pieces of code ready for integration, they can just as well serve as the grounds for discussion :)
