### ISSUE TITLE
How to get last inserted id for raw queries?

### ISSUE THREAD

**Issue by kirill-zhirnov** [sequelize/sequelize#3287]
Hi,
Db: postgresql

I tried to pass callee, but it has no effect - field with primary key is always null.
Is it possible to get last inserted id without passing callee?

Regards, Kirill.

**Comment by mickhansen** [comment]
Can you show the actual query you're running?
For postgres you might need to use RETURNING id; to get the id.

**Comment by kirill-zhirnov** [comment]
Great! Thanks! It works!
