### ISSUE TITLE
Sequelize time comparison failed after database replacement to postgreSQL

### ISSUE THREAD

**Issue by makromat** [sequelize/sequelize#3289]
I've replaced MySQL database instead PostgreSQL and now I have issue when I'm trying find user through :

```js
.find({ where: { 
  resetPasswordToken: req.params.token, 
  resetPasswordExpires: { gt: Date.now() } 
} })
.then(function(user){
  if (!user) {
    req.flash('errors', { msg: 'Password reset token is invalid or has expired.' });
    return res.redirect('/forgot');
  }
 res.render('account/reset', {
    title: 'Password Reset'
  });
})
.catch(function(err){
  return next(err);
});
```

**This code was working before now I've message:**

`SequelizeDatabaseError: operator does not exist: timestamp with time zone > bigint`

Date inside database is stored like: 2015-03-05 08:09:40.152+01

I will be very grateful because I don't know if my issue is caused by database migration or some type in my code. Thanks a lot!

**Comment by janmeier** [comment]
Try with `new Date(Date.now())`. Date.now returns an integer timestamp

**Comment by janmeier** [comment]
Closing, no response
