### ISSUE TITLE
Add function in the select / update-create query

### ISSUE THREAD

**Issue by florian-rossiaud** [sequelize/sequelize#3290]
Hi,

Is there a way to add a function at the select when i created a custom type and another one for the create / update query ?

Exemple:

    sequelize.define('MyModel', {
        myDate: CustomType.MYDATE
    });

    MyModel.find(); => SELECT DATE_FORMAT(myDate,'%b %d %Y %h:%i %p') FROM ....

    MyModel.create({..}) => INSERT INTO MyModel (myDate) VALUES (STR_TO_DATE(myDate, '%b %d %Y %h:%i %p'))

The use of `DATE_FORMAT` and `STR_TO_DATE` is an example, I know I could use a getter in this case but i'd like to use it for all my `CustomType.MYDATE`.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/2042
