### ISSUE TITLE
Do not forget to synchronize your models for each process!

### ISSUE THREAD

**Issue by martinoppitz** [sequelize/sequelize#3291]
### Description
As of today (2015-03-05), the deletion of a instance does not work anymore. The SQL snippet looks wrong.

#### Model
```javascript
var Constraint = sequelize.define( 'Constraint', {
  'id': {
    'field': 'constraint_id',
    'type': DataTypes.BIGINT,
    'primaryKey': true,
    'autoIncrement': true
  },
  'identifier': {
    'field': 'constraint_identifier',
    'type': DataTypes.STRING( 32 ),
    'unique': true,
    'allowNull': false
  },
  'formula': {
    'field': 'constraint_formula',
    'type': DataTypes.TEXT,
    'allowNull': false
  },
  'comment': {
    'field': 'constraint_comment',
    'type': DataTypes.STRING( 128 ),
    'allowNull': true,
    'defaultValue': null
  }
}, {
  'tableName': 'constraints'
} );
```

#### Controller
```javascript
Constraint.find( {
    where: {
      id: 1
    }
  } )
    .then( function ( constraint ) {
      constraint.destroy()
        .then( function () {} )
        .catch ( function ( error ) {} );
    } )
    .catch ( function ( error ) {} );
};
```

### Log
- [x] Select item by id works
- [ ] Delete item by instance does not work **`Error log: Column „id“ not exists`**
```
Executing (default): SELECT "constraint_id" AS "id", "constraint_identifier" AS "identifier", "constraint_formula" AS "formula", "constraint_comment" AS "comment", "created_at", "updated_at" FROM "constraints" AS "Constraint" WHERE "Constraint"."constraint_id" = 1;
Executing (default): DELETE FROM "constraints" WHERE "id" IN (SELECT "id" FROM "constraints" WHERE "constraint_id" = '1' LIMIT 1)
```

**Comment by mickhansen** [comment]
As of today? It would be more helpfull to know form what and to what version you upraded :)
But yes there does appear to be a bug.

**Comment by deleonio** [comment]
Current version: **2.0.3** (Updated at 2015-03-03)
Last version: **2.0.2**

**Comment by martinoppitz** [comment]
### A little test

1. I removed sequelize
2. I install sequelize by `npm install sequelize@2.0.2`
3. Restart my application

Result: **Same issue**

Conclusion: **I believe, the issue based on sequelize dependencies.** Because the current versions of the dependencies modules installed have been installed.

**Comment by martinoppitz** [comment]
#### Interestingly Note

**`The problem occurs since I use  js workers.`** I insert the exact same code in the Master and executed my application. Everythinks works fine. **`Executing (default): DELETE FROM "properties" WHERE "property_id" IN (SELECT "property_id" FROM "properties" WHERE "property_id" = '5' LIMIT 1)`**

After that, I retry the same code by using a Worker. **`Executing (default): DELETE FROM "properties" WHERE "id" IN (SELECT "id" FROM "properties" WHERE "property_id" = '5' LIMIT 1)`**

##### App index.js
```javascript
var cluster = require( 'cluster' );
var models = require( '../common/models' );
var config = require( './config' );

if ( cluster.isMaster ) {
    var Master = require( './ctrls/Master' );
    models.sequelize.sync( {
      'force': config.reset
    } ).then( function () {
        new Master( config.url.port, models );
    } );
  } else if ( cluster.isWorker ) {
    var Worker = require( './ctrls/Worker' );
    new Worker( config.url.port, models );
  }
} )();
```

**Comment by martinoppitz** [comment]
#### Little changes
```javascript
var cluster = require( 'cluster' );
var models = require( '../common/models' );
var config = require( './config' );

if ( cluster.isMaster ) {
  models.sequelize.sync( {
    'force': config.reset
  } ).then( function () {
    var Master = require( './ctrls/Master' );
    new Master( config.url.port, models );
  } );
} else if ( cluster.isWorker ) {
  models.sequelize.sync( {
    'force': false
  } ).then( function () {
      var Worker = require( './ctrls/Worker' );
      new Worker( config.url.port, models );
    } );
}
```

**Comment by martinoppitz** [comment]
### `@everyone`
### Do not forget to synchronize your models for each process!

#### I am sorry! My mistake.

Because I thought that the models were already synchronized via the master. But that was a mistake.

**Comment by mickhansen** [comment]
@martinoppitz Hmm, sync() shouldn't be required for it to work, that's still a bug.

**Comment by martinoppitz** [comment]
@mickhansen I think, in my case it is required. Because my `foreigenKey`-columns differ from `id`.

**Comment by mickhansen** [comment]
@martinoppitz Shouldn't matter and should still work :) I'm reopening so i can make sure to fix it. Using sync is NOT required for an application to work, or it should not be.

**Comment by martinoppitz** [comment]
@mickhansen Ok. I follow you ... interesting.

**Comment by janmeier** [comment]
Tested, works fine on 3.17.3
