### ISSUE TITLE
The same password but generate different hash 

### ISSUE THREAD

**Issue by uchsarath** [sequelize/sequelize#3293]
I've tried with these code, but finally still generate different hash code within the same password. Is there is solution to solve this problem. I think it is not caused from BCRYPT, but that should be Sequelize problem

Here is the code:

    bcrypt.genSalt(SALT_WORK_FACTOR, function (err, salt) {
        if (err) return next(err, user);

        log.debug("After Salted : " + salt);

        bcrypt.hash(user.password, salt, function (err, hash) {
            if (err) return next(err, user);
            user.password = hash;
            console.log("user name: " + user.nickname);
            console.log("password:  " + user.password);
            bcrypt.hash(user.password, salt, function(err, hash) {
                console.log("======================= \n");
                console.log("Re-hash username: " + user.nickname);
                console.log("Re-hash password: " + hash);
![screenshot from 2015-03-06 15 04 16](https://cloud.githubusercontent.com/assets/1330852/6522080/81effcde-c412-11e4-9d27-0a2afad57974.png)

            });

            next(null, user);
        });
    });

**Comment by mickhansen** [comment]
If you generate a new salt each time the password hash will be different each time.
Also why are you hashing an already hashed password?

**Comment by mickhansen** [comment]
If you are expecting `re-hash password` to be the same as `hashed password` you'd be mistaken and you should read up on how hashing works, highly doubt this is a Sequelize issue.
