### ISSUE TITLE
Mysql connection - performance

### ISSUE THREAD

**Issue by streetkid** [sequelize/sequelize#3294]
I'm load testing my Amazon m3.medium servers running express connecting to sequelize mysql. I've put a connection pool of 1 - 100 max. The sequelize only ever create 5 concurrent connections, even if I hit it with 100 requests per second. 

I'd like to consider alternatives to increase performance, because at the moment with 100 requests within 3 seconds, it can take up to 15 seconds for the query to come back. Very simple query to get username password for authentication, no joins. I've put indexes in and it doesn't matter.

**Comment by janmeier** [comment]
Please show some actual code - how have you set the max number of connections ?

**Comment by streetkid** [comment]
var config = {     
       "username": "",
        "password": "",
        "database": "",
        "host": "",
        "port": 3306,
        "dialect": "mysql",
        "logging": true,
        "sync": false,
        "pool.maxConnections" : 100,
        "pool.minConnections" : 1,
       "pool.maxIdleTime": 3600000
    }
    var sequelize = new Sequelize(config.database, config.username, config.password, config);

Test using Jmeter number of threads: 100
Ramp up period (in seconds) : 3

**Comment by janmeier** [comment]
Pool is an object

```js
var config = {     
   "username": "",
    "password": "",
    "database": "",
    "host": "",
    "port": 3306,
    "dialect": "mysql",
    "logging": true,
    "sync": false,
    pool: {
        maxConnections : 100,
        minConnections : 1,
        maxIdleTime: 3600000
    }
}
```

**Comment by streetkid** [comment]
Apologies for the mistake there!  it's pooling with more now, however is there any way to make it persistent? Currently once the request is done it disappears after the maxIdleTime.

**Comment by janmeier** [comment]
Connection pooling as handled by [generic pool](https://github.com/coopernurse/node-pool). As far as i know there is no way to make it persist, other than setting a very high idle timeout

**Comment by mickhansen** [comment]
@streetkid bump up idle time or min connections
