### ISSUE TITLE
One-to-many create / get accessors do not take / include recursive associations?

### ISSUE THREAD

**Issue by josdewitte** [sequelize/sequelize#3297]
1: When using the "create" injected accessor on a one-to-many relation,

how does one set the sub-associations without have to know the foreign key ?

Project.createUser({ userAssociation: userAssociationInstance }) does not work;

2: When using Project.getUsers({ where : { status : 4} , include: [{model : userAssociationModel, as 'assoc']}) the association is undefined on the returned users..

Am I missing something?

3: Furthermore, on a side note, if I use find / findAll, and suppose I have an attribute portalId with db field portal_id, why do I have to use the DB field name in a where clause? Shouldn't Sequelize convert it for me as other ORMs do?

Thanks!

**Comment by mickhansen** [comment]
1:
`Project.createUser({ userAssociation: userAssociationInstance })` is not supported.
You can have a look at https://github.com/sequelize/sequelize/pull/3169 though.

2:
You're giving us next to no information, impossible to answer :)

3:
You don't, you can use the attribute name if the attriibute has a field property.

**Comment by josdewitte** [comment]
Hmm. Is there a way to declare a hook on all models in sequelize so I can implement this feature?
beforeUpdate seems a likely candidate, but I have 200+ class models,,

**Comment by mickhansen** [comment]
@josdewitte You can use `afterDefine` as a global hook mechanism:

```js
sequelize.afterDefine(function (model) {
  model.beforeUpdate(function (instance) {

  });
});
```

**Comment by josdewitte** [comment]
Thanks! I'll get on that!
