### ISSUE TITLE
Adds { force: true } option to .removeTarget and .removeTargets instance methods.

### ISSUE THREAD

**Issue by MtDalPizzol** [sequelize/sequelize#3298]
As discussed in #1761 , it'll be nice to have an option to force the deletion of the target records, not simply disassociating them from the source, when using .removeTarget and .removeTargets instance methods. Something like:

``` javascript
User.removeAddresses(addressesToDelete, {force: true});
```

**Comment by mickhansen** [comment]
I would probably suggest naming the option `destroy: true`, and perhaps having it enabled directly on the association somehow aswell.

`Adress.belongsTo(User, {required: true})` or something

**Comment by MtDalPizzol** [comment]
Hmm... ```{ destroy: true }``` in fact sounds better. But how about this:
```javascript
Address.belongsTo(User, { onRemove: 'destroy' });
```
I think ``` { required: true } ``` dosn't say a lot about the matter of this issue...

**Comment by janmeier** [comment]
But `onRemove` is easy to confuse with `onDelete` (which creates a DB constraint). 

I'm thinking that something very close to this could be achieved by setting to foreign key column to `allowNull: false`. The constraint enforces that adresses can only reference a valid user id, and allow null false enforces that adresses must reference a user id.

I'm not sure why it should be the responsibility of the related model to delete the adresses. Would this not be more clear?

```js
var addressIds = adressesToDelete.map(function (a) { return a.id });
Address.destroy({ where: { id: addressIds }});
```

**Comment by MtDalPizzol** [comment]
@janmeier , thanx for your help too. I have tried enforcing constraints by setting ```{ allowNull: false }``` to the ```foreignKey```, but then it thows an error because when I try to ```.removeAddresses()``` it tries to set ```user_id``` to ```NULL``` anyway.

```
{ [SequelizeValidationError: Validation error]
  name: 'SequelizeValidationError',
  message: 'Validation error',
  errors: 
   [ { message: 'user_id cannot be null',
       type: 'notNull Violation',
       path: 'user_id',
       value: null } ] }
```

I know I could remove addresses directly as you suggested. I just think it'll be cool having this awesome and semantic feature of ```User.removeAddresses()``` allowing us to avoid having to ```.map()``` instances every time we need to delete eager loaded records, for example...

**Comment by emanuelscariot** [comment]
Is there any perspective to implement this? It'll be very helpful indeed and prevent a lot of unecessary code. =/

**Comment by janmeier** [comment]
@emanuelscariot it will probably be implemented eventually, but no promises. The problem is easy to work around, so not really a priority for the core team. 

If you feel like providing a PR, this should be an excellent way to get acquainted with the sequelize codebase :-)

**Comment by jerilamy** [comment]
+1 for this feature.  I'll take a look in my spare time at getting a PR for this.

**Comment by janmeier** [comment]
@jerilamy Awesome! Don't hesitate to ask if you encounter any problems! :)
