### ISSUE TITLE
Errors with non lower case letters in table name (Postgres)

### ISSUE THREAD

**Issue by gmuresan** [sequelize/sequelize#3299]
If you define a model with an underscore or a capital letter in the name there are a few errors. The biggest error is relations/associations don't get created.

**Comment by mickhansen** [comment]
I personally use model names with underscores so i highly doubt that they are fundamentally broken.
Please show your actual code and expectations, you can't expect people to just guess if you wan't help :)

**Comment by BridgeAR** [comment]
Ping @gmuresan

**Comment by theptrk** [comment]
You can explicitly flag then change the names described here https://github.com/sequelize/sequelize/issues/94

**Comment by theptrk** [comment]
Is this still an open issue?

**Comment by janmeier** [comment]
@theptrk no idea, since we've never seen any code to show the issue. I highly doubt there is anything wrong though. 

Please open a new issue if you have problems :-)
