### ISSUE TITLE
Connecting to the database takes a long time

### ISSUE THREAD

**Issue by ilanbiala** [sequelize/sequelize#3300]
Connecting to the database seems to always take >4s and sometimes up to 10s.

**Comment by mickhansen** [comment]
@ilanbiala You have instrumented some tracing in the sequelize codebase?

**Comment by ilanbiala** [comment]
How would I do that?

**Comment by mickhansen** [comment]
I'm asking how you're currently measuring the database connection time.

**Comment by ilanbiala** [comment]
Just running a stopwatch from 1 console.log before to 1 console.log after.

**Comment by mickhansen** [comment]
before and after what exactly?
If it's around a find call you're measuring a lot more than just the connection.

**Comment by ilanbiala** [comment]
No just
```
connection = new Sequelize(config.db.opts.database, config.db.opts.user, config.db.opts.password, {
      host: config.db.opts.host,
      port: config.db.opts.port,
      dialect: 'mysql',
      logging: false,
      pool: {
        max: 8,
        min: 0,
        idle: 10000
      }
    });
```

**Comment by mickhansen** [comment]
I don't understand, that call doesn't do any connections, that just sets up the sequelize instance.
Are you saying you placed `console.log`s around new Sequelize and that takes 4-10 seconds?
I find that almost impossible to believe.

**Comment by ilanbiala** [comment]
http://sequelize.readthedocs.org/en/latest/docs/getting-started/#setting-up-a-connection

This doesn't create a connection? Then what does......?

**Comment by mickhansen** [comment]
Connections are created when you execute queries. We're using standard pooling techniques - So unless you have have min connections set it won't start a connection untill you do a query.

**Comment by janmeier** [comment]
Please provide a more detailed test case if you still believe this is an issue
