### ISSUE TITLE
Running migrate with `method: "down"` actually undoes ALL migrations

### ISSUE THREAD

**Issue by submitteddenied** [sequelize/sequelize#3301]
The default behaviour when running `migrate({method: "down"})` is to execute the down() for all migrations. [These docs](https://sequelize.readthedocs.org/en/latest/docs/migrations/) seem to suggest that migrating down should only revert the most recently run migration, so I suspect this is an error in the implementation of `lib/migrator.js` around [line 38](https://github.com/sequelize/sequelize/blob/master/lib/migrator.js#L38).

I intend to submit a PR that adds a `limit` option to the `migrator.migrate()` function options, but I thought I'd raise visibility here first.

**Comment by mickhansen** [comment]
The Sequelize core migrator is severely broken and has been rewritten in https://github.com/sequelize/umzug

**Comment by submitteddenied** [comment]
In that case, can we remove the core migrator from Sequelize or document somewhere that users should be using umzug?

**Comment by mickhansen** [comment]
I believe the CLI ships with Umzug by default now, @sdepold would know.
We'll remove the migrator completely from Sequelize in a version or two.

**Comment by sdepold** [comment]
CLI uses Umzug. The core should actually show you deprecation warnings when you use them.
