### ISSUE TITLE
Problem with N:M self assocciation

### ISSUE THREAD

**Issue by cfltdf** [sequelize/sequelize#3303]
I've created the two tables like this:

---Code Begin---
Class = db.define('Class');
ClassClassify = db.define('ClassClassify');
ClassClassify.belongsTo(Class, {
  as: 'subClass',
  foreignKey: 'subClassId'
});
ClassClassify.belongsTo(Class, {
  as: 'superClass',
  foreignKey: 'superClassId'
});
subClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'subClassId',
  through: ClassClassify
});
superClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'superClassId',
  through: ClassClassify
});
---Code End---

It works well... That's quite good.
But when I'm putting a Class with its subClasses and superClasses together, like this:

---Code Begin---
Class.findAll({
  include: [
    {
      association: subClass
    }, {
      association: superClass
    }
  ]
})
---Code End---

An error occurs:

---Error Message Begin---
Possibly unhandled SequelizeDatabaseError: SQLITE_ERROR: ambiguous column name: subClass.id
---Error Message End---

And the sql form it generates is like this:

---SQL Begin---
Executing (default): SELECT `Class`.`id`, `subClass`.`id` AS `subClass.id`, `subClass.ClassClassify`.`id` AS `subClass.ClassClassify.id`, `subClass.ClassClassify`.`superClassId` AS `subClass.ClassClassify.superClassId`, `subClass.ClassClassify`.`subClassId` AS `subClass.ClassClassify.subClassId`, `subClass`.`id` AS `subClass.id`, `subClass.ClassClassify`.`id` AS `subClass.ClassClassify.id`, `subClass.ClassClassify`.`superClassId` AS `subClass.ClassClassify.superClassId`, `subClass.ClassClassify`.`subClassId` AS `subClass.ClassClassify.subClassId` FROM `Classes` AS `Class` LEFT OUTER JOIN `ClassClassifies` AS `subClass.ClassClassify` ON `Class`.`id` = `subClass.ClassClassify`.`subClassId` LEFT OUTER JOIN `Classes` AS `subClass` ON `subClass`.`id` = `subClass.ClassClassify`.`subClassId` LEFT OUTER JOIN `ClassClassifies` AS `subClass.ClassClassify` ON `Class`.`id` = `subClass.ClassClassify`.`superClassId` LEFT OUTER JOIN `Classes` AS `subClass` ON `subClass`.`id` = `subClass.ClassClassify`.`subClassId`;
---SQL End---

Now I wonder if there is some tips for me with this problem.

Thanks.

**Comment by mickhansen** [comment]
Please make the effort to properly format your issue with GitHub markdown.
It looks like you have two associations with the same alias. You likely want one side of your N:M to have a different descriptive alias.

(I think the first N:M should probably have the alias 'superClass' rather than 'subClass')

**Comment by cfltdf** [comment]
My mean is that I have many classes, while each class have several subclasses and several superclasses.
Look at two classes A and B, if class A is a subclass of class B, then class B is a superclass of class A as well.
It can also be discribed as that superclass is the reverse association of subclass.
The program works well while I just take out subclass only or superclass only for a class, but gets wrong if I am taking both.



super.flyingfreely@gmail.com
 
From: Mick Hansen
Date: 2015-03-07 16:30
To: sequelize/sequelize
CC: cfltdf
Subject: Re: [sequelize] Problem with N:M self assocciation (#3303)
Please make the effort to properly format your issue with GitHub markdown.
It looks like you have two associations with the same alias. You likely want one side of your N:M to have a different descriptive alias.
(I think the first N:M should probably have the alias 'superClass' rather than 'subClass')

**Comment by mickhansen** [comment]
Look at your code like i told you, both your superClass and subClass is aliased as subClass, hence the error.

**Comment by mickhansen** [comment]
```
subClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'subClassId',
  through: ClassClassify
});
superClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'superClassId',
  through: ClassClassify
});
```

Should by most logical reasoning be:

```
subClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'subClassId',
  through: ClassClassify
});
superClass = Class.belongsToMany(Class, {
  as: 'superClass',
  foreignKey: 'superClassId',
  through: ClassClassify
});
```

**Comment by cfltdf** [comment]
It works now, thank you!

Sorry that I've made a mistake.

BTW, there should add 'otherKey' to make sure the two association be reverse.



super.flyingfreely@gmail.com
 
From: Mick Hansen
Date: 2015-03-07 16:53
To: sequelize/sequelize
CC: cfltdf
Subject: Re: [sequelize] Problem with N:M self assocciation (#3303)
subClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'subClassId',
  through: ClassClassify
});
superClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'superClassId',
  through: ClassClassify
});

Should by most logical reasoning be:
subClass = Class.belongsToMany(Class, {
  as: 'subClass',
  foreignKey: 'subClassId',
  through: ClassClassify
});
superClass = Class.belongsToMany(Class, {
  as: 'superClass',
  foreignKey: 'superClassId',
  through: ClassClassify
});

**Comment by mickhansen** [comment]
Yes for self referential associations you might want to use otherKey :)
