### ISSUE TITLE
It looks  like v2.0.0-dev12 is the last release

### ISSUE THREAD

**Issue by harianus** [sequelize/sequelize#3305]
When you go to [the releases tab](https://github.com/sequelize/sequelize/releases) and try to know which release is the last one it shows the `v2.0.0-dev12` very large.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1079135/6542116/a7ff7c28-c4ef-11e4-80f2-633342837c6e.png)

Maybe change v2.0.4 to latest release?

**Comment by mickhansen** [comment]
We haven't actually used that release list it seems.
I just added a new release in any case.
