### ISSUE TITLE
In Model.update(values, options), options should support order

### ISSUE THREAD

**Issue by gjuchault** [sequelize/sequelize#3307]
In MySQL documentation, `UPDATE` can support `ORDER BY`.
Example query :

``` sql
UPDATE Projects SET foo="bar" WHERE user_id=1 ORDER BY date DESC LIMIT 1
```

To set foo=bar on the last project of user 1

**Comment by jwt1143** [comment]
Any hope of getting this implemented? This is a hard requirement for the app I'm modifying/building. Without this, I will have no choice but to use raw SQL :/
