### ISSUE TITLE
Strange behavior running Gulp + Mocha tests

### ISSUE THREAD

**Issue by filipedeschamps** [sequelize/sequelize#3308]
Hi guys! How are you?

I use Gulp to keep re-running my Mocha tests. But I'm suffering a strange behavior: **the first run works, but the second doesn't**

After the second run, I'm receiving this error message:

 > **The dialect sqlite is not supported. (Error: Please install sqlite3 package manually)**

## First run
![image](https://cloud.githubusercontent.com/assets/4248081/6548362/9f3e9296-c5d4-11e4-8b58-444f1f94ccb7.png)

## Second run
![image](https://cloud.githubusercontent.com/assets/4248081/6548366/b5db2550-c5d4-11e4-9e66-a16bc6f5c4c2.png)

After digging the problem, looks like it's happening when it runs for the second time the `new Sequelize` command:

![image](https://cloud.githubusercontent.com/assets/4248081/6548397/eb8df604-c5d5-11e4-9259-1da74cf2c5a4.png)

Funny fact is, in the first run, everything is ok even if I duplicate the `new Sequelize` line.

What I'm missing? :)

Best regards.

**Comment by filipedeschamps** [comment]
Looks like the error is happening in this block of code:

`sequelize/lib/dialects/sqlite/connection-manager.js:22:11`
```javascript
  try {
    this.lib = require(sequelize.config.dialectModulePath || 'sqlite3').verbose();
  } catch (err) {
    throw new Error('Please install sqlite3 package manually');
  }
```

And the error message in the catch is this:

 > **[Error: Module did not self-register.]**

**Comment by filipedeschamps** [comment]
Searching for this `Module did not self-register`, I found things related to Node **0.12**.

Downgraded to Node **0.10.36** and now everything is ok.

**Comment by mickhansen** [comment]
Similiar issue to https://github.com/sequelize/sequelize/issues/3302 it seems.

**Comment by cusspvz** [comment]
@filipedeschamps have you deleted `node_modules` folder before changing to `0.12` and installed everything with `npm install`?

**Comment by filipedeschamps** [comment]
@cusspvz tried this now, but still the same error.

**Comment by cusspvz** [comment]
I had `Module did not self-register` being thrown up after node update, but as soon as I deleted `node_modules` and installed them again, it vanished.

> @cusspvz tried this now, but still the same error.

So i guess there is another reason for this to happen.

**Comment by janmeier** [comment]
Do you have gulp / any other module installed globally? You might need to reinstall that as well.

Anyways, this is pretty clearly not a sequelize issue so I'm closing this one

**Comment by filipedeschamps** [comment]
@janmeier ok, no problem.

Anyway, all modules are local, the only global modules are node, npm and nvm.

**Comment by janmeier** [comment]
Hmm, weird - some googling seems to suggest that a lot of other modules are also experiencing something similar ...

**Comment by cusspvz** [comment]
@filipedeschamps i would suggest you to upgrade modules you're using on your app, if you found any module that doesn't have support for `0.12` ATM, keep at `0.10` or `0.11` for a while.

**Comment by filipedeschamps** [comment]
@cusspvz thanks for your tips. I've updated everything, but no success. Still the same behavior.

**Comment by elamperti** [comment]
@filipedeschamps do you by any chance have symlinked your node_modules folder? I have the same problem only in that case.

**Comment by filipedeschamps** [comment]
@elamperti no symlinks at all
