### ISSUE TITLE
MSSql ETIMEOUT intermittent error

### ISSUE THREAD

**Issue by Bondifrench** [sequelize/sequelize#3311]
Hi,

I have the following model:
````
var configDB = require('../config/configMs');
var Sequelize = require('sequelize');
var sequelize = new Sequelize(configDB.dbname, configDB.user, configDB.password, {
	host: 'xxxx.xxxx.net',
	dialect: "mssql",
	pool: {
		maxConnections: 5,
		maxIdleTime: 30000
	}
});
var dimEntity = sequelize.define('dimEntity', {
	Id: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		allowNull: false
	},
	Cik: Sequelize.INTEGER,
	Name: Sequelize.STRING,
	IndustryTypeId: {
		type: Sequelize.INTEGER,
		field: 'IndustryTypeId',
		referencesKey: 'id'
	},
	IsFund: Sequelize.BOOLEAN,
	IsCompany: Sequelize.BOOLEAN,
	FiscalYearEnds: Sequelize.STRING,
	CreatedOn: Sequelize.DATE,
	UpdatedOn: Sequelize.DATE,
	AddressId: Sequelize.INTEGER,
	CompanyName: Sequelize.STRING,
	CompNm_1: Sequelize.STRING,
	hasXBRL: Sequelize.BOOLEAN,
	sicExtern: Sequelize.BOOLEAN,
	aliasName: Sequelize.STRING,
	StateId: {
		type: Sequelize.INTEGER,
		field: 'StateId',
		referencesKey: 'id'
	}
}, {
	schema: 'Domain',
	tableName: 'DimEntity',
	freezeTableName: true,
	timestamps: false
});
// return dimEntity;
// }
sequelize
	.sync()
	.then(function() {
		return dimEntity.findAll()
			.then(function(content) {
				for (var i = 0; i < content.length; i++) {
					console.log(content[i].dataValues);
				}
			});
	})
	.catch(function(error) {
		console.log('Problem trying to retrieve data: ', error);
	});
````
I get the following error from time to time:
````
Executing (default): IF OBJECT_ID('[Domain].[DimEntity]', 'U') IS NULL CREATE TABLE [Domain].[DimEntity] ([Id] INTEGER NOT NULL , [Cik] INTEGER NULL, [Name] NVARCHAR(255) NULL, [IndustryTypeId] INTEGER NULL, [IsFund] BIT NULL, [IsCompany] BIT NULL, [FiscalYearEnds] NVARCHAR(255) NULL, [CreatedOn] DATETIME2 NULL, [UpdatedOn] DATETIME2 NULL, [AddressId] INTEGER NULL, [CompanyName] NVARCHAR(255) NULL, [CompNm_1] NVARCHAR(255) NULL, [hasXBRL] BIT NULL, [sicExtern] BIT NULL, [aliasName] NVARCHAR(255) NULL, [StateId] INTEGER NULL, PRIMARY KEY ([Id]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[Domain].[DimEntity]';
Executing (default): SELECT [Id], [Cik], [Name], [IndustryTypeId], [IsFund], [IsCompany], [FiscalYearEnds], [CreatedOn], [UpdatedOn], [AddressId], [CompanyName], [CompNm_1], [hasXBRL], [sicExtern], [aliasName], [StateId] FROM [Domain].[DimEntity] AS [dimEntity];
Problem trying to retrieve data:  { [SequelizeDatabaseError: Timeout: Request failed to complete in 15000ms]
  name: 'SequelizeDatabaseError',
  message: 'Timeout: Request failed to complete in 15000ms',
  parent:
   { [RequestError: Timeout: Request failed to complete in 15000ms]
     name: 'RequestError',
     message: 'Timeout: Request failed to complete in 15000ms',
     code: 'ETIMEOUT',
     sql: 'SELECT [Id], [Cik], [Name], [IndustryTypeId], [IsFund], [IsCompany], [FiscalYearEnds], [CreatedOn], [UpdatedOn], [AddressId], [CompanyName], [CompNm_1], [hasXBRL], [sicExtern], [aliasName], [StateId] FROM [Domain].[DimEntity] AS [dimEntity];' },
  original:
   { [RequestError: Timeout: Request failed to complete in 15000ms]
     name: 'RequestError',
     message: 'Timeout: Request failed to complete in 15000ms',
     code: 'ETIMEOUT',
     sql: 'SELECT [Id], [Cik], [Name], [IndustryTypeId], [IsFund], [IsCompany], [FiscalYearEnds], [CreatedOn], [UpdatedOn], [AddressId], [CompanyName], [CompNm_1], [hasXBRL], [sicExtern], [aliasName], [StateId] FROM [Domain].[DimEntity] AS [dimEntity];' },
  sql: 'SELECT [Id], [Cik], [Name], [IndustryTypeId], [IsFund], [IsCompany], [FiscalYearEnds], [CreatedOn], [UpdatedOn], [AddressId], [CompanyName], [CompNm_1], [hasXBRL], [sicExtern], [aliasName], [StateId] FROM [Domain].[DimEntity] AS [dimEntity];' }
````
I don't always have this error, but I get it 3 out of 4 times. The result is > 18000 rows.
I thought modifying `maxIdleTime` would help, but as you can see in the error It doesn't go beyond 15000ms.
@mbroadst I think you were saying that for MSSql we don't have a connection pool, is it still possi ble to modify the idle time?
@mickhansen One of the columns has an index, so I was wondering if I should modify my model to add one?

I am using sequelize 2.0.4

Thx

**Comment by janmeier** [comment]
This is not related to pooling, but to the actual underlying connection timing out. `maxIdle` is the time a connection is kept open with no queries running, so not related here.

Try settings [`requestTimeout`](http://pekim.github.io/tedious/api-connection.html):

```js
new Sequelize(..., {
  dialectOptions: {
    requestTimeout: something higher than 15000
  }
});
```

**Comment by janmeier** [comment]
Btw, an index is not going to do any difference here if you are doing a full table scan anyways

**Comment by Bondifrench** [comment]
@janmeier Thanks for the info
requestTimeout did help me going over 15000, but I still get the ETimeout problem with 30000.
Is that normal with 18000 rows and the table defined above?

**Comment by janmeier** [comment]
No idea - the timeout is happening while streaming the rows from the DB to your application. 

So perhaps the connection is slow, the db server is slow, your application server is slow?

**Comment by mbroadst** [comment]
@Bondifrench I actually merged a fix for connection closing [here](421dd28a0511238ecdc080e67fad45a3bc267320) a week ago. Maybe you can try out the latest sequelize version and see if you still experience this error? We weren't properly cleaning up connections previously, but we do now.

**Comment by Bondifrench** [comment]
@mbroadst I have sequelize version 2.0.4, is it in there or in master?

**Comment by mbroadst** [comment]
@Bondifrench its in master, so will be in the 2.0.5 release

**Comment by govi2010** [comment]
@mbroadst  I am getting same error. 
My database is on local machine.
My system is good enough 

but i am getting 
Timeout: Request failed to complete in  in 40000ms

 for just on select query.

**Comment by janmeier** [comment]
@govi2010 Its impossible for us to say anything about the problem with so little information. Have you tried to connect to the database directly using tedious? We can't debug a problem if we can't replicate it ....

**Comment by govi2010** [comment]
Sorry my mistake. 

Actully i had a transaction, 
in which i was inserting product. and after that with in that promise i was returning the product by finding by it. in which i did not pass transaction object. 


Thank you for you help.
