### ISSUE TITLE
SequelizeDatabaseError: syntax error at or near ","

### ISSUE THREAD

**Issue by gtomitsuka** [sequelize/sequelize#3312]
Hello,

I'm working with Sequelize and received a quite weird error:

    Possibly unhandled SequelizeDatabaseError: syntax error at or near ","
        at module.exports.Query.formatError (/home/ubuntu/swap-and-sell/src/node_modules/sequelize/lib/dialects/postgres/query.js:415:16)
        at null.<anonymous> (/home/ubuntu/swap-and-sell/src/node_modules/sequelize/lib/dialects/postgres/query.js:110:21)
        at emit (events.js:107:17)
        at Query.handleError (/home/ubuntu/swap-and-sell/node_modules/pg/lib/query.js:99:8)
        at null.<anonymous> (/home/ubuntu/swap-and-sell/node_modules/pg/lib/client.js:166:26)
        at emit (events.js:107:17)
       at TLSSocket.<anonymous> (/home/ubuntu/swap-and-sell/node_modules/pg/lib/connection.js:109:12)
        at TLSSocket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)
        at TLSSocket.Readable.push (_stream_readable.js:126:10)
    { [SequelizeDatabaseError: syntax error at or near ","]
      name: 'SequelizeDatabaseError',
      message: 'syntax error at or near ","',
      parent: 
       { [error: syntax error at or near ","]
         name: 'error',
         length: 84,
         severity: 'ERROR',
         code: '42601',
         detail: undefined,
         hint: undefined,
         position: '477',
         internalPosition: undefined,
         internalQuery: undefined,
         where: undefined,
         schema: undefined,
         table: undefined,
         column: undefined,
         dataType: undefined,
         constraint: undefined,
         file: 'scan.l',
         line: '1053',
         routine: 'scanner_yyerror',
         sql: 'INSERT INTO "Offers" ("id","title","description","featured","price","originallyBought","createdAt","updatedAt","UserId") VALUES (DEFAULT,\'Ford Ecosport Car\',\'Brand new\',false,9.9,\'2011-04-21 00:00:00.000 +00:00\',\'2015-03-09 15:49:01.034 +00:00\',\'2015-03-09 15:49:01.040 +00:00\',`dataValues` = \'[object Object]\', `_previousDataValues` = \'[object Object]\', `__options` = \'[object Object]\', `options` = \'[object Object]\', `hasPrimaryKeys` = true, `__eagerlyLoadedAssociations` = , `isNewRecord` = false, `_customGetters` = \'[object Object]\', `_customSetters` = \'[object Object]\', `validators` = \'[object Object]\', `_hasCustomGetters` = 0, `_hasCustomSetters` = 0, `rawAttributes` = \'[object Object]\', `attributes` = \'id\', \'title\', \'description\', \'createdAt\', \'updatedAt\', `Model` = \'[object SequelizeModel]\', `$Model` =  \'[object SequelizeModel]\') RETURNING *;' },

My code is:

    var createOffer = function(object, category, user){
      return new Promise(function (resolve, decline){
        var offerInstance = Offer.build({
          title: object.title,
          description: object.description,
          featured: object.featured,
          price: object.price,
          originallyBought: object.originallyBought
        });
        offerInstance.setUser(user);
        offerInstance.save()
        .then(function(){
          return category.addOffer(offerInstance).save();
        }).then(function(){
          resolve();
        }).catch(function(error){
          decline(error);
        });
      });
    }

The user is sent via the REST API. I'm totally sure that it's got nothing to do with the REST API, but with Sequelize, PostgreSQL or my schemas. Thanks anticipated!

**Comment by gtomitsuka** [comment]
Uh oh sorry for the inconvenience I sent the user as the category and the category as the user and this screwed up everything.

**Comment by mentesnot-2** [comment]
I getting this error and unable to resolve it
:SequelizeDatabaseError: syntax error at or near "["

**Comment by ephys** [comment]
Please open a new bug report with a complete description & reproducible example
