### ISSUE TITLE
Sync error - cascading on delete causes 

### ISSUE THREAD

**Issue by EToreo** [sequelize/sequelize#3316]
Back end: MySql
The sync function on models generates `ON DELETE SET NULL ON UPDATE CASCADE` for associated keys when `NULL` is not allowed.

It is generating the cascade statement even when I had `allowNull` set to `false` on the attribute.  OnnoDB was failing to create the table because it can not `SET NULL ON UPDATE` when `NULL` is not allowed on the attribute.

Removing the cascade when `allowNull` is `false` on attributes would fix this bug bug.
Giving the option on including the cascade would be nice for situations where nulls are allowed but you still don't want to cascade on delete (I know, should be rare).

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/2831
We are aware of this issue, although i'm proposing we default you DELETE, it'd be great if you could drop your $.02 on that issue @EToreo
