### ISSUE TITLE
setting field to undefined then saving it causes ER_EMPTY_QUERY

### ISSUE THREAD

**Issue by sjlu** [sequelize/sequelize#3317]
Using Sequelize 2.0.4

At the moment, when I change a field by *nulling* it out, it will clear out that field appropriately. An example of this is:
```
User.find(id).then(function(user) {
  user.firstname = null;
  return user.save();
});
```

On the other hand, when I *undefine* it, for example:
```
user.firstname = undefined;
user.save()
```
It will throw me `SequelizeDatabaseError: ER_EMPTY_QUERY: Query was empty` since it is the only field that has changed. Note that on my model I have `timestamps: false`.
```
Executing (default): 
{ [SequelizeDatabaseError: ER_EMPTY_QUERY: Query was empty]
  name: 'SequelizeDatabaseError',
  message: 'ER_EMPTY_QUERY: Query was empty',
  parent: 
   { [Error: ER_EMPTY_QUERY: Query was empty]
     code: 'ER_EMPTY_QUERY',
     errno: 1065,
     sqlState: '42000',
     index: 0,
     sql: '' },
  original: 
   { [Error: ER_EMPTY_QUERY: Query was empty]
     code: 'ER_EMPTY_QUERY',
     errno: 1065,
     sqlState: '42000',
     index: 0,
     sql: '' },
  sql: '' }
```

Now when diving into the code a little bit more, I see that it is picking up that the field has changed when logging `options` on https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L581

But when it hits `Utils.mapValueFieldNames`, the value has disappeared due to it interpreting the value as undefined and therefore not picking it up on https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L230

I can understand that *null* has a philosophically different meaning than *undefined* where *undefined* in Sequelize means "don't touch this value", should it be treated as *null* in this case? I know that it kind of duplicates specifying which fields to save https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L541

If yes, should the call end early by adding
```
if (!_.keys(values).length) return this;
```

Or no and should it interpret *undefined* as *null*?

**Comment by BridgeAR** [comment]
This is just as it should be. Setting something to undefined in javascript has a different meaning than setting it to null. If sequelize would check for undefined, it would have to include all fields that are not defined and insert null. That's not a desired behaviour. Escmascript 6 is going to implement defaults too and that would be even more confusing with setting something to null if the value is actually undefined ([Example] (https://github.com/nodejs/io.js/pull/635#issuecomment-71790592)).

@mickhansen @janmeier please close this.

**Comment by sfakir** [comment]
Is there any way, how to catch setting a value to undefined on the model?
It is really hard to debug, without even knowing which model is the reason for the error.

**Comment by jayfresh** [comment]
Just a note on this that calling `changed()` on a model instance that has had a field to set `undefined` does return the field that was cleared. I feel it's a bit unexpected that that identified change does not go on to be saved
