### ISSUE TITLE
User not associated to project?

### ISSUE THREAD

**Issue by PaulBGD** [sequelize/sequelize#3320]
I'm attempting to find a project, then include the user that's associated with the project in the query as well. I define the association as such:

```
this.User.hasMany(this.Project);
```
Then my query looks like:
```
server.database.Project.findOne({
    where: {
        id: id,
        name: project
    },
    include: [
        server.database.User
    ]
})
```

However, it says that my user is not associated with the project? Inside the database it has my userId set inside the project row.

**Comment by mickhansen** [comment]
`hasMany` does not setup a reverse association automatically i'm afraid, you'l need to add `this.Project.belongsTo(this.User)` aswell.

**Comment by PaulBGD** [comment]
Alright thanks. I thought there should've been some built in way, but that works too.
