### ISSUE TITLE
model association onDelete to "CASATE" has a indefinite result

### ISSUE THREAD

**Issue by neekey** [sequelize/sequelize#3322]
I did a little test, and seems like the result ( by checking the foreign key generated ) is indefinite 

Define two model:

``` js
var a = sequelize.define("a", {
    name: Sequelize.STRING
});
var b = sequelize.define("b", {
    name: Sequelize.STRING
});
```

and different results below:

only `hasMany` works:

```
a.hasMany( b, { as: 'bs', foreignKey: 'a_id', onDelete: 'CASCADE' } );
```

only `belongsTo` also works:

```
a.hasMany( b, { as: 'bs', foreignKey: 'a_id', onDelete: 'CASCADE' } );
```

all works too:

``` js
b.belongsTo( a, { as: 'a', foreignKey: 'a_id', onDelete: 'CASCADE' } );
a.hasMany( b, { as: 'bs', foreignKey: 'a_id', onDelete: 'CASCADE' } );

a.hasMany( b, { as: 'bs', foreignKey: 'a_id', onDelete: 'CASCADE' } );
b.belongsTo( a, { as: 'a', foreignKey: 'a_id' } );

b.belongsTo( a, { as: 'a', foreignKey: 'a_id', onDelete: 'CASCADE' } );
a.hasMany( b, { as: 'bs', foreignKey: 'a_id' } );
```

and fail and end up with onDelete SET NULL:

``` js
b.belongsTo( a, { as: 'a', foreignKey: 'a_id' } );
a.hasMany( b, { as: 'bs', foreignKey: 'a_id', onDelete: 'CASCADE' } );

a.hasMany( b, { as: 'bs', foreignKey: 'a_id' } );
b.belongsTo( a, { as: 'a', foreignKey: 'a_id', onDelete: 'CASCADE' } );
```

So, I guess once the association is defined, the next opposite call will not change the hook.

I don't know if this can be considered as a bug, but the way to set association hook is ambiguous and the document didn't tell us to set hooks on both side.

**Comment by janmeier** [comment]
Which version is this on? I believe I've fixed something like this pretty recently

**Comment by neekey** [comment]
@janmeier Sequelize 2.0.1
