### ISSUE TITLE
how can I create a Model to support GeoData in Sequelize?

### ISSUE THREAD

**Issue by uchsarath** [sequelize/sequelize#3323]
I have problem in Model. I don't know which data should use to store GeoData - POINT(12312312,234234)

Anyway, how to insert long & lat into the Sequelize?

**Comment by janmeier** [comment]
Geometry types are not currently supported in sequelize. You can define the column as a string with `col: 'POINT'` 

Dupe of https://github.com/sequelize/sequelize/issues/2839

**Comment by emil-alexandrescu** [comment]
saved me bunch of time. Thanks!
