### ISSUE TITLE
Model fields with 'field' parameter, problems.

### ISSUE THREAD

**Issue by sergenikitin** [sequelize/sequelize#3326]
Hello,

I have a table with ```created_at```field, that's described with default value NOW():
```
created_at | timestamp with time zone | not null default now()
```

When I have model with this syntax: 
```
created_at: DataTypes.TIME`
```
, everything works good. When I create a record without specify ```created_at```, it's generated with default value NOW().

But if i use this syntax for model: 

```
createdAt: {
      field: 'created_at',
      type:DataTypes.TIME,
      'default': new Date()
    },
````
, it's error happens, because sequelize try insert ```created_at``` like NULL.

Here a log:
```
Executing (default): INSERT INTO "*****" ("id","name","created_at","account","error","params","response") VALUES (DEFAULT,'GET_SPORTS',NULL,'*****',0,ARRAY[]::VARCHAR[],'<?xml version="1.0"?>')
```

So, if describe model with ```field``` attribute, sequelize starts insert NULL for column that have default value.

P.S.
versions: iojs.1.5.0, sequelize: 2.0.3, postgresql

Thanks!

**Comment by janmeier** [comment]
It should be `defaultValue`,  not default http://docs.sequelizejs.com/en/latest/api/sequelize/#definemodelname-attributes-options-model

**Comment by sergenikitin** [comment]
@janmeier thanks for ```defaultValue```, it's work.

But anyway, after refactoring I have some problems.

Refactoring was to change in sequelizes models all field names to camelCaseStyle.

After I changed fields from 
```
created_at: DataTypes.DATE
```
, to
```
createdAt: {
      field: 'created_at',
      type: DataTypes.DATE,
      defaultValue: new Date()
    },
```

I have some problems:

* Now I must specify defaultValue for a field. But before PostgreSQL gives DEFAULT value, that was defined in PostgreSQL Schema. 

* Now I have problem with ordering.  Before that code
```
      let result = yield models.Bet.findAndCountAll(
        {
          where: _b.createObjectWithNotEmptyValues({
            id: betId, tipId, playerId, placeStatus, result: betResult
          }),
          order: 'created_at DESC',
          include: [models.Player, models.Tip],
          limit: pageLimit,
          offset: (page - 1) * pageLimit
        });

```
, worked good. But after refactoring ```created_at``` -> ```createdAt: {field: 'created_at'}``` it falls with error
```
SequelizeDatabaseError: column reference "created_at" is ambiguous
```

And now it works only like this:
```
let result = yield models.Bet.findAndCountAll(
        {
          where: _b.createObjectWithNotEmptyValues({
            id: betId, tipId, playerId, placeStatus, result: betResult
          }),
          order: '"Bet"."created_at" DESC',
          //order: 'created_at DESC',
          include: [models.Player, models.Tip],
          limit: pageLimit,
          offset: (page - 1) * pageLimit
        });
```
(model Tip has created_at field too. But before refactoring it was working).

It's a pity that can not use ```order: 'createdAt DESC'``` - using sequelize model field name createdAt, not database table column.

P.S. Sorry for bad English.

**Comment by sergenikitin** [comment]
One more problem:

This code do not work:
```
result.betAmount = yield models.Bet.sum('bet_amount', {where: {createdAt: {between: [fromDate, toDate]}}});
```
, it falls with error:

```
SequelizeDatabaseError: column Bet.createdAt does not exist
```

I need code like this, it works: 
```
result.betAmount = yield models.Bet.sum('bet_amount', {where: {'created_at': {between: [fromDate, toDate]}}});
```

**Comment by janmeier** [comment]
Hmm, yeah i guess `order` should default to prefixing the table name on the column.

And `aggregate` needs to map field names it seems

**Comment by mickhansen** [comment]
`order: 'created_at DESC'` means literal order.
Need to use `order: [['created_at', 'DESC']]`

**Comment by janmeier** [comment]
Closing, no response
