### ISSUE TITLE
search where attribute in included model without having to specify where in includes

### ISSUE THREAD

**Issue by mbroadst** [sequelize/sequelize#3328]
It would be ideal if sequelize could just figure out what to do if you wanted to find all database entries with a where condition that refers to an attribute on an included model (rather than having to specify the where condition in the options.include). Here's a test case for this behavior:

```
var Sequelize = require('sequelize'),
    DataTypes = Sequelize,
    sequelize = new Sequelize('groups_test', 'root', 'password');

var Device = sequelize.define('Device', {
  name: DataTypes.STRING
}, {
  underscored: true,
  timestamps: false
});

var Group = sequelize.define('Group', {
  name: DataTypes.STRING
}, {
  underscored: true,
  timestamps: false
});

Device.hasMany(Group);

sequelize.sync({force: true})
  .then(function() {
    return Promise.all([
      Device.create({ name: 'device1' }),
      Device.create({ name: 'device2' }),
      Group.create({ name: 'group1' }),
      Group.create({ name: 'group2' }),
      Group.create({ name: 'group3' })
    ]);
  })
  .spread(function(device1, device2, group1, group2, group3) {
    return Promise.all([
      device1.setGroups([group1, group2, group3]),
      device2.setGroups([group3])
    ]);
  })
  .then(function() {
    return Device.find({
      where: {
        group: {
          name: 'somename'
        }
      }
    }, {
      include: [ Group ]
    });
  })
  .then(function(devices) {
    console.log(devices);
  });
```

**Comment by mickhansen** [comment]
I think this should add the condition to the main where and not the join though.

**Comment by mbroadst** [comment]
@mickhansen wouldn't that be less performant than adding it to the where of the join clause? When I specify the where on the top level there it is, in effect, an alias to the "include where". I'm probably missing something, but I'm not sure I see the benefit of having this in the top level where.

**Comment by mickhansen** [comment]
@mbroadst probably, but we need to support top level wheres on joined tables as well (for complex or's), not sure how we would differ between the alias and the actual top level where?

**Comment by mbroadst** [comment]
@mickhansen maybe it's better to discuss it in terms of code examples. This change would mostly help out big time in epilogue since we could programmatically build up the findAll without having to specialize for include cases, so something like this https://github.com/sequelize/sequelize/pull/3344 seems like it would have solved that for me. Can you post an example of what you're talking about in comparison, so we can think about the implications of each approach?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/3095

The problem is when you need to do matching on two seperate included tables in the same expression (for OR queries primarily, can't be added to the JOIN)
