### ISSUE TITLE
query() returning duplicate data

### ISSUE THREAD

**Issue by CGavrila** [sequelize/sequelize#3333]
I have a Node application running on two separate machines. Both use Sequelize 2.0.4.

**Machine #1:**
```
Ubuntu 14.04
mysql  Ver 14.14 Distrib 5.5.37, for debian-linux-gnu (i686) using readline 6.3
```
**Machine #2:**
```
Ubuntu 14.04
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3
```

They both access the same sort of data, just in different databases, with the query being a simple SELECT statement (no JOINS or anything too fancy).

When I run it on Machine #1 I get:
```
[ { id: 1, title: 'Title 1', language_id: 1 },
  { id: 2, title: 'Title 2', language_id: 1 },
  { id: 3, title: 'Title 3', language_id: 1 } ]
```

When I run on Machine #2 I get:
```
[[ { id: 1, title: 'Title 1', language_id: 1 },
   { id: 2, title: 'Title 2', language_id: 1 },
   { id: 3, title: 'Title 3', language_id: 1 } ],
[  { id: 1, title: 'Title 1', language_id: 1 },
   { id: 2, title: 'Title 2', language_id: 1 },
   { id: 3, title: 'Title 3', language_id: 1 } ] ]
```

Basically the same data, but duplicated within the result. I don't know what else to include other than Sequelize version, OS version and MySQL version that might be of any relevance.

Is there anyone that has an idea as to what this might be caused by? The only difference among what I have provided is the mysql version.

**Comment by CGavrila** [comment]
I have also tried running the query manually in the database, I only get one set of the results.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/wiki/Upgrading-to-2.0#changes-to-raw-query

**Comment by CGavrila** [comment]
I can't really see how that might have happened, but you are most likely right. I'll check and comment here if it's still persisting.

Thank you very much for the help, @mickhansen!

**Comment by ayushmaanbhav** [comment]
I got the same error of duplicate responses:
OS: windows 8.1 64 bit
Sequelize: [Node: 0.12.2, CLI: 1.7.0, ORM: 2.1.2]
MySQL: 5.5.8
Code: 
Models.sequelize.query('SELECT users.messaging_id FROM users INNER JOIN (SELECT * FROM user_vehicle WHERE vehicle_id = '2') AS user_vehicle ON users.user_id = user_vehicle.user_id;');

**Comment by janmeier** [comment]
@ayushmaanbhav And the fix is the same - the raw query api has been slightly refactored, look at the link mick posted above

**Comment by ayushmaanbhav** [comment]
i am srry, didnt notice. thnx.
