### ISSUE TITLE
Associations property with wrong case on eager loading

### ISSUE THREAD

**Issue by falmp** [sequelize/sequelize#3335]
On the eager loading documentation, it's clearly stated that a `User` model will be created as an `user` property, including the examples provided.

http://docs.sequelizejs.com/en/latest/docs/models/#eager-loading

That does not happen as expected. Currently, the association property will have the same case as the defined model (i.e. `User`).

**Comment by mickhansen** [comment]
Docs appear to be a bit outdated. We had a lot of naming issues when trying to automatically camelcase stuff (would break in a lot of edge cases) so we now use model name/association as literally.

You can rename the model name to lowercase for a easy fix that shouldn't break anything (if you don't rely on table name generation)

**Comment by falmp** [comment]
Ok, thank you for the clarification. :+1:
