### ISSUE TITLE
include option on eager loading not working when using find(id, { include: [ Model ] })

### ISSUE THREAD

**Issue by falmp** [sequelize/sequelize#3337]
I'm actually not sure if this is supposed to work like this or if it's a bug, but the `include` option on the `find()` method, if called as `find(id, { include: [ Model ] })`, is ignored.

For instance, this works:

```javascript
database.SearchProcess.find({ where: { id: id }, include: [ database.User ]})
```

But this doesn't work:

```javascript
database.SearchProcess.find(id, { include: [ database.User ] })
```

**Comment by mickhansen** [comment]
That's working as intended.
`include` is only supported on the options object which is the first parameter to `find`.
Passing a single number is simply convenience mapping to `{where: {id: val}}` but it does not work with includes unfortuneatly.

**Comment by falmp** [comment]
Ok, cool. Thanks for the clarification. :+1:
