### ISSUE TITLE
Set constraints on the model level

### ISSUE THREAD

**Issue by omarfouad** [sequelize/sequelize#3343]
My tables have been created with sequelize-migrations (i'm not using `model.sync()`).

I'm wondering if it's possible to set a constraint like `onDelete: 'SET NULL'` on the model without having physical constraints in the database itself like in ActiveRecord. this:

```js
//models/post.js

//definition... 
categoryId: {
   type: DataTypes.UUID, 
   references: 'Categories',
   referencesKey: 'id',
   onDelete: 'SET NULL',
   onUpdate: 'CASCADE'
}
```
So that when I delete a Category it nullifies the categoryId in the post records. 

Thanks.

**Comment by mbroadst** [comment]
+1 I think this would be fantastic, especially since some databases (like mssql) have incredibly strict rules about cascading rules

**Comment by sushantdhiman** [comment]
Its [now possible](http://docs.sequelizejs.com/en/latest/docs/associations/?highlight=references#foreign-keys_1) to set `onUpdate` and `onDelete` constraints like

```js
references: {
    model: "trainers",
    key: "id",
    onUpdate: 'RESTRICT',
    onDelete: 'CASCADE'
}
```
