### ISSUE TITLE
Hook not receiving options when adding associated object

### ISSUE THREAD

**Issue by eventhough** [sequelize/sequelize#3346]
I am using hooks to do some security related actions. For example, I use the beforeFind hook to add an additional check to my where clause to make sure users can only select rows that belong to them.

I do this by adding some credentials to options before I call find. For example:

``` javascript
Thneeds.findAll({
  where: { color: 'purple' },
  credentials: userCredentials
})
```

In my beforeFind hook I can access options.credentials and modify the where clause to include an additional check.

The problem is when I use an association method such as `person.addThneed(thneed, options)` the beforeFind hook no longer contains `options.credentials`, or anything else I add to it.

The interesting thing is when I have an association with a through object the hooks work because in a through object scenario my options are preserved. I basically add them as part of the defaultAttributes and they go through.

Here are the docs for add[AS]:

add[AS] - for example addPicture(instance, defaultAttributes|options). Add another associated object. add[AS] [plural] - for example addPictures([instance1, instance2], defaultAttributes|options). Add some more associated objects.

Is there some way to make sure options are preserved when using add[AS] **without** a through object?

**Comment by mickhansen** [comment]
Sounds like the options aren't passed along to the internal calls correctly.

**Comment by eventhough** [comment]
I'd like to help locate where this issue is happening. I'm looking at the hasMany scenario:

https://github.com/sequelize/sequelize/blob/master/lib/associations/has-many.js#L434

Is this the `.find` call that is causing the hook to fire without options propagated?

https://github.com/sequelize/sequelize/blob/master/lib/associations/has-many.js#L472

**Comment by eventhough** [comment]
@mickhansen Scratch that, I'm not getting options passed to hooks for any of my add[AS] methods with or without a through object.

When I use add[AS] it uses `find` which then fires `beforeFind` hooks where I am expecting something to be in options. I am on sequelize v2.0.3.

**Comment by mickhansen** [comment]
@eventhough yeah there is definitely some code that is not propagating the options object around properly.

**Comment by eventhough** [comment]
@mickhansen Just did some more testing. I am seeing the same problem for **remove[AS]**. Good news is has[AS] is working fine.
