### ISSUE TITLE
Expose Model associations

### ISSUE THREAD

**Issue by mdarveau** [sequelize/sequelize#3347]
Hi,

I often have to do eager fetching of the same associations and I have to type the `{ model: User, as: 'Manager'}` multiple times as in:

```
League.findAll(
      include: [
        { model: User, as: 'Manager'}
      ]
    )
```

I found out that I could pass the return of `League.belongsTo User, {as: 'Manager', foreignKey: { allowNull: false }}` to the include and that would be accepted and processed correctly by sequelize. I'm not even sure this is truly supported so stop me if it's not.

Assuming this is supported, it would be nice if this relation definition could be exposed in the model definition. I know I can always keep a reference to what was returned by the `belongsTo` call, but I found out that it's already in the model definition's `associations` property. However, it's not always in a key that matches the "as" parameter.

What do you think if we added a `getAssociation(asName)` to `Model` so one could do:

```
League.findAll(
      include: [
        League.getAssociation('Manager')
      ]
    )
```

Or even better, something like the following:

```
League.findAll(
      include: [
        League.Manager
      ]
    )
```

... but I'm not sure of the possible conflicts

What do you think? I could attempt a PR if you think this is a good idea.

P.S.: All code are in coffeescript

**Comment by mickhansen** [comment]
`League.Manager = League.belongsTo(User, {as: 'Manager'})` should achieve what you need.
We allow include by association references (all association calls, belongsTo, hasMany etc, return an association reference).

**Comment by mdarveau** [comment]
Yes, this is what I did and it works fine.

However, I think it would be uber cool (and sugary!) if it was done automatically and then we could issue query like:
```
League.findAll( 'Manager' )
```
And maybe even nestes includes like:
```
League.findAll( [ 'Manager', 'Manager.SomeOtherNestedRelation'] )
```

And if I push my luck a little but further, simply the where clauses too. Something like:
```
Game.findAll(
      where:
        Sequelize.or(
          Sequelize.where( Sequelize.col( 'HomeTeam.id' ), '=', team.id ),
          Sequelize.where( Sequelize.col( 'AwayTeam.id' ), '=', team.id )
        )
      include: [
        Game.HomeTeam
        Game.AwayTeam
        Game.Location
      ]
    )
```
Could become:
```
Game.findAll(
      where: Sequelize.or( { 'HomeTeam.id': team.id }, { 'AwayTeam.id': team.id } )
      include: [ 'HomeTeam', 'AwayTeam', 'Location' ]
    )
```

Seems like a huge improvement to the query syntax without too much modifications to the core engine.

**Comment by janmeier** [comment]
Hmm, I think the keys in the `associations` should always match the `as` key. Could you show as case where this is not the case?
```js
var Game = sequelize.define('game', {})
var Team = sequelize.define('team', {})

Game.belongsTo(Team, { as: 'HomeTeam'})
Game.belongsTo(Team, { as: 'AwayTeam'})

return Game.findAll({   
      include: [ Game.associations.HomeTeam, Game.associations.AwayTeam ]
});
```

The where part is being worked on here https://github.com/sequelize/sequelize/issues/3328

**Comment by janmeier** [comment]
@mickhansen I just realized I like using Model.associations much more than passing the related model :). I know we've supported it for quite some time but I just haven't really tried it before ..

**Comment by mdarveau** [comment]
@janmeier here is an example (in CoffeeScript):

    League.Manager = League.belongsTo User, {as: 'Manager', foreignKey: { allowNull: false }}

    League.Substitutes = League.belongsToMany User, {as: 'Substitutes', through: 'LeagueSubstitutes'}
    
    League.Location = League.hasMany Location
    
    League.Team = League.hasMany Team
    
    console.log "League associations:"
    for key, value of League.associations
      console.log "#{key}"

output is

```
League associations:
League.associations.Manager.as=Manager
League.associations.Substitutes.as=Substitutes
League.associations.LeagueLocation.as=Locations
League.associations.LeagueTeam.as=Teams
```

It looks like for `hasMany` associations, the key is different from the as.

**Comment by janmeier** [comment]
@mdarveau Right you are! :)

Not sure if this is something we should fix or we just let the users assign the association to whatever property they want @mickhansen ?

**Comment by mickhansen** [comment]
I think we should fix it :)

**Comment by janmeier** [comment]
Right now associations are assigned via `associationAccessor` https://github.com/sequelize/sequelize/blob/master/lib/associations/mixin.js#L113. We can't change that, but it should be as easy as changing that line to `as` instead

**Comment by mickhansen** [comment]
We can't change it?

**Comment by janmeier** [comment]
I meant we can't change the value of `associationAccessor` to match `as` instead of the trhough table name. Not sure what its used for ;)

**Comment by mickhansen** [comment]
@janmeier Why can't we? I think we can :)

**Comment by arcanis** [comment]
How would it work for additional options (include, where, attribute, etc)?

**Comment by mickhansen** [comment]
@arcanis currently it's `{association: Association, where: {}}`
