### ISSUE TITLE
"otherKey" for belongsToMany is undocumented in associations documentation

### ISSUE THREAD

**Issue by aaronshaf** [sequelize/sequelize#3348]
See: http://docs.sequelizejs.com/en/latest/docs/associations/

And: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L90

Example:

```javascript
Product.belongsToMany(Category, {
  through: ProductCategory,
  foreignKey: 'product_id',
  otherKey: 'category_id'
})
```

**Comment by sddhhanover** [comment]
This is crucial for those upgrading from hasMany to belongsToMany

**Comment by mickhansen** [comment]
@sddhhanover if you are upgrading you should likely still have 2 calls and otherKey should then be inferred, are you experiencing that it isn't?

**Comment by sddhhanover** [comment]
Correct. I am defining `foreignKey` in both calls, yet for some reason the `foreignKey` of one call is not being captured as the `otherKey` of the other. Strange...

**Comment by mickhansen** [comment]
@sddhhanover and this is on 2.0.4+?
