### ISSUE TITLE
Associations cannot be created when model schema is specified using sync.schema

### ISSUE THREAD

**Issue by raffishquartan** [sequelize/sequelize#3349]
This issue occurs in Sequelize 2.0.4 and possibly other version.

When I create my `Sequelize` object as follows:

``` javascript
var sq = new Sequelize(dbname, user, password, {
  /* ... */
  sync: {
    schema: 'foo'
  },
  /* ... */
});
```

Then the database tables which back each model are correctly created in the foo schema. However, the schema is not specified in calls which create relations, which then fail because the SQL is incorrect:

```
2015-03-14 20:58:41.069 DEBUG [app/util/pr/index] sq:sync -- Executing (default): CREATE TABLE IF NOT EXISTS "pfsq"."entry_tag" ("sq_created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "sq_updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "entry_id" UUID  REFERENCES "entry" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "tag_id" UUID  REFERENCES "tag" ("id"), PRIMARY KEY ("entry_id","tag_id"));
Possibly unhandled SequelizeDatabaseError: relation "entry" does not exist
```

When the schema is defined either in an option to the `define` calls or in `options.define.schema` in the call to the Sequelize constructor then the SQL is generated correctly. Additionally, if the option is specified in `options.sync.schema` in the Sequelize constructor call and _then_ I also call `schema('foo')` on each of the models to set its schema manually the associations are created correctly. Based on all of this there seems to be a bug in how the option to sync is handled.

**Comment by janmeier** [comment]
I didn't even know you could set `options.sync.schema` .. I think schema should be set on the model, not when synching.. What do you think @mickhansen

**Comment by mickhansen** [comment]
I wasn't aware that option existed either, but i suppose either we fully support it or we don't support it at all, and i'm mostly leaning towards the latter.

**Comment by marquinhoalm** [comment]
Any news on this? I'm having the same problem.

**Comment by janmeier** [comment]
@marquinhoalm We are planning on removing that option - the schema should be set on the model instead. Do you experience issues when doing that?
