### ISSUE TITLE
when I use migration.removeColumn with  sqlite3 but drop table and not create table

### ISSUE THREAD

**Issue by elover** [sequelize/sequelize#3350]
version 

![image](https://cloud.githubusercontent.com/assets/4330913/6654805/a4aab50a-cb17-11e4-9ed1-94f961d02187.png)

**Comment by mickhansen** [comment]
Are you saying that it's dropping the table but not recreating it?
Can you show your model definition, the actual removeColumn call and the SQL log?

**Comment by elover** [comment]
yes
model definition:
![image](https://cloud.githubusercontent.com/assets/4330913/6654911/930d18e0-cb1e-11e4-81b6-a72b7a5324eb.png)
and logs:
![4d4dfdf1-da39-469c-b267-7fa6fca04b47](https://cloud.githubusercontent.com/assets/4330913/6654924/28fd1e68-cb1f-11e4-9e32-8e8d6324e844.png)

**Comment by elover** [comment]
the log is ok,but the table nameOfTheNewTable is not created

**Comment by mickhansen** [comment]
What do you mean it's not creating?
I'm seeing a create table statement in the log.

**Comment by mickhansen** [comment]
Please post code rather than images :) And please show the removeColumn migration call in it's entirety.

**Comment by elover** [comment]
model definition:

```
"use strict";
 module.exports = {
    up: function(migration, DataTypes, done) {
        migration.createTable(
            'nameOfTheNewTable',
            {
                id: {
                    type: DataTypes.INTEGER,
                    primaryKey: true,
                    autoIncrement: true
                },
                createdAt: {
                    type: DataTypes.DATE
                },
                updatedAt: {
                    type: DataTypes.DATE
                },
                attr1: DataTypes.STRING,
                attr2: DataTypes.INTEGER,
                attr3: {
                    type: DataTypes.BOOLEAN,
                    defaultValue: false,
                    allowNull: false
                }
            });


        done();
    },

    down: function(migration, DataTypes, done) {
        // add reverting commands here, calling 'done' when finished
        done();
    }
};
```

removeColumn migration：

```
"use strict";
module.exports = {
    up: function(migration, DataTypes, done) {
        // add altering commands here, calling 'done' when finished
        migration.removeColumn('nameOfTheNewTable', 'attr2');
        done();
    },

    down: function(migration, DataTypes, done) {
        // add reverting commands here, calling 'done' when finished
        done();
    }
};
```
 I run  sequelize db:migrate  , but the table "nameOfTheNewTable" is not created.
if I do not run removeColumn migration,the table "nameOfTheNewTable" is created,
you can try it ,thank you

**Comment by mickhansen** [comment]
The last paragraph did not make a lot of sense.
But the issue appears to be that you are calling done() before the migration is actually done, hence the table will not be created when the removeColumn migration is being run.

**Comment by elover** [comment]
I have be synchronized but  nameOfTheNewTable is not here
![image](https://cloud.githubusercontent.com/assets/4330913/6655062/46b79c1e-cb27-11e4-9076-7b40d9718b89.png)

**Comment by elover** [comment]
I have created the table before run  removeColumn migration.
the table is droped after I run removeColumn migration.

**Comment by elover** [comment]
```
"use strict";
module.exports = {
    up: function(migration, DataTypes, done) {
        // add altering commands here, calling 'done' when finished
        migration.removeColumn('Users', 'username');
        done();
    },

    down: function(migration, DataTypes, done) {
        // add reverting commands here, calling 'done' when finished
        done();
    }
};

```
run this
the User table is droped too.

**Comment by mickhansen** [comment]
You have synchronized? Not sure what that means.
SQLite doesn't actually support remove/add column so we drop and recreate tables.
I think your primary issue is that you're calling done() before the migration is finished, sequelize is async.

**Comment by mickhansen** [comment]
And i'm clearly seeing a create table statement in the log so, are you logging errors from migrations? Doesn't look like it.

**Comment by elover** [comment]
I  get it , thank you , I should do like this
```
migration.removeColumn('nameOfTheNewTable', 'attr1',function(){
     done();
});
```

**Comment by mickhansen** [comment]
Sequelize doesn't support callbacks, probably more something like `migration.removeColumn('table', 'attr').nodeify(done)`, or just return the promise if using the umzug migrator.

**Comment by mickhansen** [comment]
The code you propose still wont propagate errors, so you have no idea of knowing if a migration failed, that's an important part of the process :)

**Comment by elover** [comment]
thank you , Sequelize is great.

**Comment by elover** [comment]
I use CLI and callbacks is worked

**Comment by mickhansen** [comment]
Super :) i'm glad.
