### ISSUE TITLE
Sequelize transaction Not doing rollback when error throws

### ISSUE THREAD

**Issue by hfar** [sequelize/sequelize#3355]
Hello,

I am using sequelize transaction (managed) and when error throws full rollback is not really happening, maybe i am doing something wrong here ?

my test case : when code block 2 throws an error the things done in code block 1 are not rolled back, i can see `Executing (b87ac7be-fee5-4d01-af7e-c86d1f68130d): ROLLBACK;` in the console but the rollback is not happening in my sql DB.

many thanks for the help.

//My models 

```
var Tag = sequelize.define('Tag', {
            tagId: {
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
            ...
        },
        {
            ...
            freezeTableName: true,
            associate: function (models) {
                Tag.belongsToMany(models.Venue, {through: models.VenueTag,foreignKey: 'tagId'});
            }
        }
    );
	

    var VenueTag = sequelize.define('VenueTag', {
            venueTagCreatedBy: {type: DataTypes.UUID, allowNull: true},
            venueTagUpdatedBy: {type: DataTypes.UUID, allowNull: true},
            venueTagDeletedBy: {type: DataTypes.UUID, allowNull: true}
        },
        {
            ...
            freezeTableName: true
        }
    );
	
    var Venue = sequelize.define('Venue', {
            venueId: {
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
           ...
        },
        {
            ...
            associate: function (models) {
                Venue.belongsToMany(models.Tag, {through: models.VenueTag,foreignKey: 'venueId'});
            }
        }
    );
```

//My Transaction
```
return sequelize.transaction(function (t) {
        return db.VenueTag.destroy({where: {venueId: venue.venueId}}, {transaction: t}).then(function () {
        }, {transaction: t}).then(function () {
        //block 1
            return db.VenueTag.upsert({
            ...
            });
        }, {transaction: t}).then(function () {
        //block 2
            //update venue details
            return venue.updateAttributes({
                ...
            },{ transaction: t});
        });
    }).then(function (result) {
        // Transaction has been committed
        // result is whatever the result of the promise chain returned to the transaction callback
        return res.status(200).json(result);
    }).catch(function (err) {
        // Transaction has been rolled back
        // err is whatever rejected the promise chain returned to the transaction callback
        return res.status(500).send({
            message: errorHandler.getErrorMessage(err)
        });
    });
```

**Comment by janmeier** [comment]
Could you please provide a more complete example? Why is the code you posted throwing an error?
We'd like some code that we can just copy/paste to replicate your example.

Is the catch callback called?

**Comment by mickhansen** [comment]
`upsert` isn't getting a transaction in that piece of code, you are giving it to the error portion of the then callbacks instead, which obviously won't work.

A more clean indentation scheme might help with that.

**Comment by hfar** [comment]
Very sorry about this ,below is smaller test case hope it helps:

transaction details:

- Destroy all records in `VenueTag` (deleted At).
- Then update/insert tags using `upsert()`.
- The exception i am making is sending `null` value for the primary key `venueId` while doing `upsert()`
- `catch` call back is called and it's returning : `ER_BAD_NULL_ERROR: Column 'venueId' cannot be null` ,while i can see that all existing records are still have `deletedAt` and that mean `destroy` action is not rolled back.
```
function createOrUpdateVenueTag(tag)
    {
        return db.VenueTag.upsert({
            venueId: null,
            tagId: tag.tagId,
            venueTagDeletedAt: null
        });
    }
```

```
 return sequelize.transaction(function (t) {
        return db.VenueTag.destroy({where: {venueId: venue.venueId}}, {transaction: t}).then(function () {
            //update insert venue tags such as venueType,DressCode
            return sequelize.Promise.map(req.body.Tags, createOrUpdateVenueTag);
        }, {transaction: t});
}).then(function (result) {
    // Transaction has been committed
    // result is whatever the result of the promise chain returned to the transaction callback
    return res.status(200).json(result);
}).catch(function (err) {
    // Transaction has been rolled back
    // err is whatever rejected the promise chain returned to the transaction callback
    return res.status(500).send({
        message: errorHandler.getErrorMessage(err)
    });
});
```

**Comment by janmeier** [comment]
Destroy takes a single options object http://docs.sequelizejs.com/en/latest/api/model/#destroyoptions-promiseundefined so it should be

```js
return db.VenueTag.destroy({where: {venueId: venue.venueId}, transaction: t})
```

**Comment by hfar** [comment]
thanks Jan ,but i get another error now after updating this 

`ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction`

This error happens on `upsert()` ,can you please advise.

**Comment by hfar** [comment]
look like it worked for me ,i just replaced the code below
``` 
function createOrUpdateVenueTag(tag)
    {
        return db.VenueTag.upsert({
            venueId: null,
            tagId: tag.tagId,
            venueTagDeletedAt: null
        });
    }

return sequelize.Promise.map(req.body.Tags, createOrUpdateVenueTag);
```

with new code
return sequelize.Promise.map(req.body.Tags, function (tag) {
                return db.VenueTag.upsert({
                    venueId: venue.venueId,
                    tagId: tag.tagId,
                    venueTagDeletedAt: null
                }, {transaction: t});
            });

i only see one difference that i am putting the `{transaction: t}` as an option in `upsert()` .. is that it?

**Comment by mickhansen** [comment]
@hfar well the first code doesn't even have a transaction passed to it so.

**Comment by hfar** [comment]
thanks so much :) everything works as expected right now.
