### ISSUE TITLE
bulkCreate validate and individualHooks malfunction

### ISSUE THREAD

**Issue by manmar92** [sequelize/sequelize#3356]
Using the latest version of sequelize and postgreSQL
```
models.User.bulkCreate(mtxes, {
	validate: true,
	individualHooks: true
})
.then(function() {          
	res.redirect('/users');
})
.catch(function(errors) {
	console.log(errors);
})
```
If the validation fails, console.log(errors) is like: 

```
{ [SequelizeValidationError: Validation error]
	  name: 'SequelizeValidationError',
	  message: 'Validation error',
	  errors: [Object] }
```
Instead of the expected:

```
[
    { record: 
    ... 
    errors: 
      { name: 'SequelizeValidationError',
        message: 'Validation error',
        errors: [Object] } },
    { record: 
      ...
      errors: 
        { name: 'SequelizeValidationError',
        message: 'Validation error',
        errors: [Object] } } 
  ]  
```
After looking into the code, I think the error is located in https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1354 and the way it handles validation hooks.

**Comment by manmar92** [comment]
I've tried changing the code and it seems that there is only one change needed:
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1354
```
return instance.hookValidate(options);
```
to:
```
return instance.hookValidate(options).catch(function(err){
  if(err){
    errors.push({record:instance, errors: err});
  }
});
```

**Comment by janmeier** [comment]
Looks good, PR welcome @manmar92 - remember to add test :)

**Comment by mickhansen** [comment]
@janmeier might want @thanpolas to weigh in here, afaik there should only be a single error object containing multiple errors as properties.

**Comment by janmeier** [comment]
@mickhansen The proposed fix just emultes the behaviour when individual hooks is false https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1358

**Comment by mickhansen** [comment]
@janmeier ah yeah of course

**Comment by thanpolas** [comment]
Yes for bulkcreate we'd need an Array of errors +1 for this
