### ISSUE TITLE
Incorrect WHERE formatting on associated tables

### ISSUE THREAD

**Issue by EToreo** [sequelize/sequelize#3360]
**2.0.0-rc8 gives this MySQL output and returns desired results:**

SELECT `Employee`.`Id`, `Employee`.`CompanyId`, `Employee`.`QbRefNum`, `Employee`.`Name`, `Employee`.`Icon`, `Employee`.`QbExportName`, `Employee`.`QbExportNameOverride`, `Employee`.`QbFirstName`, `Employee`.`QbLastName`, `Employee`.`VendorType`, `Employee`.`QbHidden`, `Employee`.`Updated`, `Employee`.`Created`, `usertoemployeemaps`.`Id` AS `usertoemployeemaps.Id`, `usertoemployeemaps`.`UserId` AS `usertoemployeemaps.UserId`, `usertoemployeemaps`.`EmployeeId` AS `usertoemployeemaps.EmployeeId`, `usertoemployeemaps`.`userId` AS `usertoemployeemaps.userId`, `usertoemployeemaps`.`employeeId` AS `usertoemployeemaps.employeeId` FROM `employee` AS `Employee` LEFT OUTER JOIN `usertoemployeemap` AS `usertoemployeemaps` ON `Employee`.`Id` = `usertoemployeemaps`.`EmployeeId` WHERE `Employee`.`CompanyId`='00000000000000000002' AND `Employee`.`QbHidden`=false AND `Employee`.`QbExportName` LIKE '%' AND `usertoemployeemaps`.`UserId`='00000000000000000008' ORDER BY `QbExportName`;

**2.0.4 throws an error:**  (Notice the way usertoemployeemaps.UserId is referenced in the WHERE clause)

SELECT `Employee`.`Id`, `Employee`.`CompanyId`, `Employee`.`QbRefNum`, `Employee`.`Name`, `Employee`.`Icon`, `Employee`.`QbExportName`, `Employee`.`QbExportNameOverride`, `Employee`.`QbFirstName`, `Employee`.`QbLastName`, `Employee`.`VendorType`, `Employee`.`QbHidden`, `Employee`.`Updated`, `Employee`.`Created`, `usertoemployeemaps`.`Id` AS `usertoemployeemaps.Id`, `usertoemployeemaps`.`UserId` AS `usertoemployeemaps.UserId`, `usertoemployeemaps`.`EmployeeId` AS `usertoemployeemaps.EmployeeId`, `usertoemployeemaps`.`userId` AS `usertoemployeemaps.userId`, `usertoemployeemaps`.`employeeId` AS `usertoemployeemaps.employeeId` FROM `employee` AS `Employee` LEFT OUTER JOIN `usertoemployeemap` AS `usertoemployeemaps` ON `Employee`.`Id` = `usertoemployeemaps`.`EmployeeId` WHERE `Employee`.`CompanyId` = '00000000000000000002' AND `Employee`.`QbHidden` = false AND `Employee`.`QbExportName` LIKE '%' AND `Employee`.`usertoemployeemaps.UserId` = '00000000000000000008' ORDER BY `QbExportName`;

SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'Employee.usertoemployeemaps.UserId' in 'where clause'

**Comment by janmeier** [comment]
Please show the sequelize code (model defintions, associations and actual find call) that is generating this error

**Comment by EToreo** [comment]
Here is a simple reproduction by modifying examples/Associations/app.js
```javascript
var Sequelize = require("sequelize");
var sequelize = new Sequelize(config.database, config.username, config.password, {logging: false});
var Person    = sequelize.define('Person', { name: Sequelize.STRING });
var Pet       = sequelize.define('Pet',    { name: Sequelize.STRING });

Person.hasMany(Person, {as: 'Brothers'});
Person.hasMany(Person, {as: 'Sisters'});
Person.hasOne(Person, {as: 'Father', foreignKey: 'FatherId'});
Person.hasOne(Person, {as: 'Mother', foreignKey: 'MotherId'});
Person.hasMany(Pet, {as: 'pets'});

sequelize.sync({force:true}).then(function()
{
   console.log('Synced');
   Person.find({where: {'pets.name': 'Rocky'}, include: [{model: Pet, as: 'pets'}]}).then(function(result)
   {
      console.log(result)
   }, function(err)
   {
      console.log(err);
   });
});
```

**Comment by mickhansen** [comment]
@EToreo that syntax is currently not supported. We're working on a new implementation

**Comment by EToreo** [comment]
So... is there not way to do this currently?

**Comment by mickhansen** [comment]
`include: [{model: Pet, as: 'pets', where: {name: 'Rocky'}]` if your usecase can handle it as a join condition.

**Comment by EToreo** [comment]
Thank you, I should have thought about that.  But in cases where that is not practical, a new syntax is being worked on to support the original Person/Pet example?

**Comment by mickhansen** [comment]
Yep :) We are working up a proposal for handling complex $or association across multiple joined models.

**Comment by EToreo** [comment]
Very nice.  I'm excited to see how that turns out.
