### ISSUE TITLE
upsert and getterMethods

### ISSUE THREAD

**Issue by icodeforlove** [sequelize/sequelize#3361]
when using upsert on a model with psuedo getter methods it tries to save them even if they arent actual table columns

```javascript
sequelize.define(
	'Foo', 
	{
		foo: DataTypes.STRING
	},
	{
		getterMethods: {
			bar: function () {
			}
		}
	}
);
```
it this example upsert would try to insert a row with the column `bar`

**Comment by janmeier** [comment]
Which version are you experiencing this on? I did some changes to how upsert gets its values pretty recently

**Comment by icodeforlove** [comment]
You're right, Its resolved on the latest version ;)
