### ISSUE TITLE
Model is not associated to another model error

### ISSUE THREAD

**Issue by burakkilic** [sequelize/sequelize#3365]
Hi;

I have following models:
   
    module.exports = function(sequelize, DataTypes) {
    var Menu = sequelize.define('Menu', {
       order: DataTypes.INTEGER,
       published: DataTypes.BOOLEAN,
    }, {
        associate: function(models) {
            Menu.belongsTo(models.Theme, {as: 'Theme', constraints:false});
        },
        tableName: 'menus'
    });
    return Menu;
    };

    module.exports = function(sequelize, DataTypes) {
    var Theme = sequelize.define('Theme', {
        name: DataTypes.STRING,
        description: DataTypes.STRING,
    }, {
        tableName: 'themes'
    });
    return Theme;
    };

I am getting "Theme is not associated to Menu!". Is there something missing?

**Comment by janmeier** [comment]
Surely you are not getting that error simply from the association call? You must be doing something more.

**Comment by burakkilic** [comment]
I' m very sorry. It seems to be the problem of Epilogue. Thank you
