### ISSUE TITLE
sequelize.query() returns duplicate result

### ISSUE THREAD

**Issue by haikyuu** [sequelize/sequelize#3366]
I'm using sequelize 2.0.4 on Ubuntu 12.04
Here is how to reproduce the issue 
``` javascript
db.sequelize.
query("SELECT * FROM Companies WHERE  type =  'transporter' ")
	.then(function(transporter) {
		console.log("transporter:", transporter);
	});
```
result  ---> transporteur: [     [ { id: 2, ...},{id: 3, ...} ]   ,     [ { id: 2, ...},{id: 3, ...} ]  ]

It was reproduced in Mac os.
In Windows it works just fine

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/wiki/Upgrading-to-2.0#changes-to-raw-query

**Comment by haikyuu** [comment]
Thanks, i missed that
