### ISSUE TITLE
models without attributes 

### ISSUE THREAD

**Issue by thetutlage** [sequelize/sequelize#3369]
Why is it so important to add attributes to the model. I understand they help in auto creating tables and adding validation, but what if I do not want to use all these goodies and have small models without attributes and their definitions

**Comment by mickhansen** [comment]
What would you do with your models if they had no attributes?
Attributes are more than just validation and table creation, they provide whitelisting safety, they hold foreign keys etc. No real point in using sequelize without attribute definitions.

**Comment by thetutlage** [comment]
Check out ActiveRecord and Eloquent , if i want i can define relations and also for whitelisting i can guard them. I like sequelize but attributes definition makes them too big

**Comment by mickhansen** [comment]
How would you define relations with whitelisting in AR without defining attributes?

**Comment by thetutlage** [comment]
Can u have a look at eloquent.. Adding attributes is not a big deal but this design change can make models look bit cleaner

**Comment by mickhansen** [comment]
I'd rather you make the effort in showing something that would work :)
Going through eloquent is not my top priority.

**Comment by janmeier** [comment]
Closing, no response
