### ISSUE TITLE
Results Formatting

### ISSUE THREAD

**Issue by jspizziri** [sequelize/sequelize#3371]
I've done some searching around with no success.

I would like to know if there is a way to specify how results are formatted. For instance, rather than returning something like this:

```json
// some set of results
[
    {
        id: 1,
        property: "hello"
    },
    {
        id: 2,
        property: "world"
    }
]
```

To return something like:

```json
// some set of results
{
    1: {
        property: "hello"
    },
    2: {
        property: "world"
    }
}
```

If this is not possible at this time, would you be open to implementing it at some point in the future?

**Comment by mickhansen** [comment]
Could probably be done with an afterFind hook and some reduce code, probably won't need to implement it in sequelize core :)

```js
Model.afterFind(function (results) {
  return results.reduce(function (memo, result) {
    memo[result.get('id')] = result;
    return memo;
  }, {});
});
```

**Comment by janmeier** [comment]
And to apply it to all your models, you could add that code in a `sequelize.afterDefine` hook

**Comment by jspizziri** [comment]
Awesome! Thanks guys! 

I haven't done much work with hooks yet, but this looks exactly like what I want.
