### ISSUE TITLE
Querying by Association Value in v2.0.4

### ISSUE THREAD

**Issue by joesavage** [sequelize/sequelize#3372]
The equivalent of the following code worked great with v1.7.9, but since upgrading to v2.0.4 I get the error `"Unknown column 'User.Pictures.featured' in 'where clause'"`. Is there a new way to accomplish this type of query as of the latest release?

```
db.User.findAll({ where: { 'Pictures.featured': true }, include: { model: db.Picture } })
```

Thanks.

**Comment by mickhansen** [comment]
`db.User.findAll({ include: { model: db.Picture, where: {features: true} } })`

I realize this might not be what you want since this will also scope the actual pictures included and not just the where.
We removed the dot syntax because it was error prone, we are working on a more idiomatic way.

**Comment by janmeier** [comment]
`db.User.findAll({ where: { '$Pictures.featured$': true }, include: { model: db.Picture } })`
