### ISSUE TITLE
Composite index

### ISSUE THREAD

**Issue by medric** [sequelize/sequelize#3373]
Hi, 

I am trying to set up a composite index for two columns within a model. Actually, I have this thing : 

```
 return sequelize.define('Assignment', { 
    date: {
      type: DataTypes.DATE,
      allowNull: false,
      unique: 'main',
    },
    antePostMeridiem: {
      type: 'CHAR(1)',
      allowNull: false,
    },
    validated: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
      unique: 'main',
    },
```

This doesn't seem to work, as I am still able to add objects with the same value for these two fields.
Nevertheless, the "unique" option with a simple boolean value works fine. So, is there something wrong here ? Do I have to force / provide a primary key option for these fields ?

Thanks.

**Comment by janmeier** [comment]
This seems to work fine for me. Do you see the unique index created on your table when you do `sequelize.sync`

**Comment by medric** [comment]
Eventually, I just dropped the database (a test one), and recreated it to see what would happen. It worked. Indeed, I don't see the unique index created on my table when I do sequelize.sync tough I thought it would do the job. Is there something I missed ?

Thanks.

**Comment by janmeier** [comment]
You should see something like
```sql
UNIQUE `main` (`date`, `validated`)
```

**Comment by medric** [comment]
Yes I do see it. But the sequelize_sync does not seem to update these constraints. Recreate my database worked though. Is there any specific parameter to add ?

Here is how my sequelize.sync looks like : 

```
db.sequelize.sync().complete(function() ...) 

```
Actually, we run it on "npm start". 

Thanks.

**Comment by janmeier** [comment]
Indexes defined on the columns are added as part of the create table statement, so yes it requires you to drop the tables first (or specify `force: true` in `sync`). 

you should be able to add the index in indexes though

```js
sequelize.define(name, attributes, {
  indexes: [
    {fields: [] }
  ]
});
```
Since those are created after the table is cretaed

**Comment by medric** [comment]
Okay, understood.

Thank you for your help.
