### ISSUE TITLE
Calling findOrCreate() and save() using CLS for transactions

### ISSUE THREAD

**Issue by meanjoe45** [sequelize/sequelize#3375]
Hi,

I've run into an issue when using the `findOrCreate()` method while having CLS enabled for automagically handling transactions. I have CLS enabled for things elsewhere in my project but have narrowed down the issue to the following code (sorry for the length, more explanation below):

```javascript
// sequelize: 2.0.4
var Sequelize = require('sequelize');
// continuation-local-storage: 3.1.2
var cls = require('continuation-local-storage');
var express = require('express');
var app = express();

Sequelize.cls = cls.createNamespace('sequelize-namespace');

var sequelize = new Sequelize('testDB', 'meanjoe45', null, {
    dialect: 'mysql',
    define: {
        timestamps: true,
        underscored: false,
        freezeTableName: true,
        syncOnAssociation: true,
        engine: 'InnoDB',
        charset: 'utf8',
        collate: 'utf8_general_ci',
    }
});

var Test = sequelize.define('Test', {
    uuid: {
        type: Sequelize.STRING(40),
        allowNull: false
    },
    other: {
        type: Sequelize.INTEGER.UNSIGNED,
        allowNull: false
    }
}, {
    createdAt: false,
    tableName: 'tests'
});

app.get('/test', function(req, res) {
    var other = '1';

    Test.findOrCreate({
            where: {uuid: 'fe908634-b930-446b-8e5a-871ac37e3531'},
            defaults: {other: other}
        })
        .bind({})
        .spread(function(test, created) {
            this.created = created;

            if (!created)
                test.other = other;

            return test.save();
        })
        .then(function(test) {
            res.status((this.created) ? 201:200).send({ 'success': true, 'data': (!!test) ? test.get() : 'undefined' });
        })
        .catch(function(error) {
            res.status(error.status || 500).send({ 'success': false, 'error': error.message || error });
        });
});

sequelize.sync({ force: true })
    .then(function() {
        var http = require('http');
        http.createServer(app).listen('8080', '0.0.0.0', function() {
            console.log('* Listening\n(0.0.0.0:8080)');
        });
    });
```

The call to `findOrCreate()` is in the API route (it was the only way for me to reproduce the error). What I want to do is call `findOrCreate()` and if the record/instance is found, update one or more fields then `save()` the instance back. All of this is in the same Promise chain.

What is happening, is the transaction created inside `findOrCreate()` is used/committed but the CLS is maintaining a copy of the transaction and trying to apply the finished transaction to the `save()` call.

```javascript
{
"success": false,
"error": "commit has been called on this transaction, you can no longer use it"
}
```

Is this a bug? Or am I doing something wrong? If I don't set Sequelize.cls, everything works. If I use `findOrInitialize()` instead of `findOrCreate()`, everything works. I would like to use `findOrCreate()` to avoid the race condition it handles.  I hope I can keep using CLS, but it isn't a necessity.

Thanks for any help or guidance you can provide.

**Comment by mickhansen** [comment]
Sounds like the internal transaction of findOrCreate is being added to the namespace.
@janmeier A general solution might be to remove the transaction from the namepsace (if it's the current transaction) when committed or rolled back.

**Comment by janmeier** [comment]
Hmm weird, somehow it must be attaching to the wrong context or not clearing when it should. But yes, clearing the transaction once its been comitted shoyld fix it
