### ISSUE TITLE
Incorrectly not allowing of editing of a primary key

### ISSUE THREAD

**Issue by trevorlanyon** [sequelize/sequelize#3376]
The following code:

``` javascript
    module.exports = function(sequelize, DataTypes) {

        return sequelize.define('EmailAddress', { 
            userId: {
                primaryKey: true,
                type: DataTypes.UUID,
                field: 'user_id',
            },
            address: {
                primaryKey: true,
                type: DataTypes.STRING,
            },
            isPrimary: {
                type: DataTypes.BOOLEAN,
                field: 'is_primary'
            },........
```

and:

``` javascript

    return req.app.get('models').EmailAddress
    .find( {
        where: {
            address: testEmail,
            userId: testUserId
        }
        }).then(function(emailAddress) {
            console.log(emailAddress.get({plain: true}));
            emailAddress.update({isPrimary: true,
            address: 'changed@home.ca'
        }).then(function(changedEmail) {
            console.log(changedEmail.get({plain: true}));
        });
    });
```

results in the .address element not updating because of:

node_modules/sequelize/lib/instance.js:

``` javascript

    // If attempting to set primary key and primary key is already defined, return
        if (this.Model._hasPrimaryKeys && originalValue && this.Model._isPrimaryKey(key)) {
            return;
        }

```

Is there a reason to not allow for the editing of a primary key if the primary key is not auto generated? Is there a different strategy I should be employing?

**Comment by mickhansen** [comment]
(You might want to make the effort to format your issue if we are to make the effort of writing a reply ;))

It's a half-known issue, the code is meant to protect against writing the auto incremented primary key.
So it should probably be made to check whether or not the key is actually auto increment.

**Comment by trevorlanyon** [comment]
( Humble apologise for the poorly formatted question, I hope the above is more clear )

Thanks for the speedy reply! (and the efforts on a great ORM)

I will write my own fix for now. Would it be reasonable for me to expect that change will be implemented in future releases?

**Comment by mickhansen** [comment]
Yes it's something we'd like to fix :)
