### ISSUE TITLE
Update on duplicate support for Postgres

### ISSUE THREAD

**Issue by omarfouad** [sequelize/sequelize#3379]
I recently got in a situation where I had to bulk insert some records in a Postgres db. However in the docs, I found this in the docs, for the`bulkUpdate` option `updateOnDuplicate`:

`Fields to update if row key already exists (on duplicate key update)? (only supported by mysql & mariadb). By default, all fields are updated`

I see it's only supported by mysql and mariadb and not in Postgres. Is this a limitation by Postgres itself, or by Sequelize? If that's the case do you guys have an idea of a workaround to achieve this?

Thanks in advance.

**Comment by mickhansen** [comment]
@omarfouad It's a limitation of postgres. For a Sequelize emulation you can use `Model.upsert()`, it doesn't provide any bulk support though.

**Comment by omarfouad** [comment]
@mickhansen No workarounds for this?

**Comment by mickhansen** [comment]
@omarfouad not to my knowledge.

**Comment by omarfouad** [comment]
Thanks :+1:

**Comment by jojo97** [comment]
You can make a simple workaround by making postgres BEFORE INSERT trigger which will delete old record when a duplicate one is inserted
