### ISSUE TITLE
Is it possible to specify a table name when i using methods like find & findAll?

### ISSUE THREAD

**Issue by cmingxu** [sequelize/sequelize#338]
I got Sequelize.define in my model files, But in controller i want specify a different table name since we sharding table into multiple tables.

**Comment by tangxinfa** [comment]
Hopes there is a official support for database table sharding, it's commom today for a dataset grow beyound 300 thousands rows, a mysql table will slow down to unacceptable. Many of our new project use database table sharding from the beginning.

**Comment by mickhansen** [comment]
@tangxinfa We don't have native sharding support at the moment, you are welcome to open a new feature request so we can discuss the API Design and implementation details of such a feature.
