### ISSUE TITLE
Still problems with associations, can't call association methods on objects

### ISSUE THREAD

**Issue by chuks** [sequelize/sequelize#3381]
User.js
"use strict";

var definition = require(__dirname + '/./../utils/models/definitions/UserDefs.js').definition;

module.exports = function(sequelize, DataTypes) {
    console.log("user model - definition is: "+definition);

    var User = sequelize.define('User', definition, {
        classMethods: {
            associate: function(models) {
                console.log("User - I am in associate. models.Happening: "+models.Happening);
                console.log("User - I am in associate. models.UserHappening: "+models.UserHappening);

                User.belongsToMany(models.Happening, {
                    foreignKey: 'User_id',
                    through: models.UserHappening,
                    as: 'associatedHappenings'
                });

                User.hasMany(models.Passwordreset, {
                    foreignKey: 'Passwordreset_id',
                    as: 'reset'
                });
            }
        },
        freezeTableName: true,
        tableName: 'users'
    });

  return User;
};

Happening.js
"use strict";

var definition = require(__dirname + '/./../utils/models/definitions/HappeningDefs.js').definition;

module.exports = function(sequelize, DataTypes) {
    console.log("Happening model definition is: "+definition);

    var Happening = sequelize.define('Happening', definition, {
        classMethods: {
            getDefinition: function() {
                return definition;
            },
            associate: function(models) {
                console.log("Happening - I am in associate. models.User: "+models.User);
                console.log("Happening - I am in associate. models.UserHappening: "+models.UserHappening);
                
                Happening.belongsToMany(models.User, {
                    foreignKey: 'User_id',
                    through: models.UserHappening,
                    as: 'associatedUsers'
                });
            }
        },
        freezeTableName: true,
        tableName: 'happenings'
    });

 	return Happening;
};

UserHappening.js
"use strict";

var definition = require(__dirname + '/./../utils/models/definitions/UserHappeningDefs.js').definition;

module.exports = function(sequelize, DataTypes) {
	console.log("UserHappening model - definition is: "+definition);

	var UserHappening = sequelize.define('UserHappening',definition, {
		freezeTableName: true,
        tableName: 'userhappenings'
	});	 	

	return UserHappening;
};	

Passwordreset.js
"use strict";

var definition = require(__dirname + '/./../utils/models/definitions/PasswordresetDefs.js').definition;

module.exports = function(sequelize, DataTypes) {
    console.log("Passwordreset model - definition is: "+definition);

    var Passwordreset = sequelize.define('Passwordreset', definition, {
        classMethods: {
            associate: function(models) {
                console.log("Passwordreset - I am in associate. Passwordreset.Instance.prototype: "+Passwordreset.Instance.prototype);

                Passwordreset.belongsTo(models.User, {
                    foreignKey: 'User_id',
                    as: 'reset'
                });
            }
        },
        freezeTableName: true,
        tableName: 'passwordresets'
    });

  return Passwordreset;
};

===PROBLEM==
In a controller. I try to add a password reset association to a user, but failed. Here is what i tried to do:

User.find({where: whereObj}, {raw: true
        }).then(function(user){
            console.log("userController: createUser - successful db call");

            if (user){
                console.log("userController: createUser - got user...");

                var now           = new Date();
                var expiration  = now.setMinutes(now.getMinutes() + 60);
                expiration        = dateFormat(expiration,'yyyy-mm-dd HH:MM:ss');
                var guid           = require('node-uuid').v4();

                Passwordreset.build({
                    guid:       guid,
                    expiration: expiration
                })
                .save()        <= so this works fine, it created the table in DB
                .then(function(passwordreset) {
                    console.log("userController: createUserPasswordChange - successfully created resetpassword record, creating association with user...");

                    user.addPasswordreset(passwordreset)      <= ERROR here...TypeError: Object #<Object> has no method 'addPasswordreset'

              });

I have also been unsuccessful calling any associative  methods between User and Happening, i.e. happening.getUsers() => fails 
happening.addUser(user) =>  fails
user.getHappenings() => fails
user.addHappening(happening) => fails

In all the above cases, it always says does not have method xxx. I thought I had solved this two days ago, but apparently not. I am using the boilerplate code for Sequelize/express. I have added the console logs in the associate class methods of each model, and they print out just ok, signifying that those methods are being called, and supposedly the associations are being created. However, when I try to invoke any association method, it fails saying the method does not exist for the object. I have perused the documentation over and over, and can't see what I am doing wrong. Please help?

**Comment by janmeier** [comment]
You have to use `addAssociatedHappenings` etc. The `as` part is what the
relation will be 'known as'

**Comment by chuks** [comment]
I have tried this, and it still does not work. For example, i tried:

Hi, thanks for the response. I have just tried your suggestions, but still get the same error.
I tried:

user.addReset(passwordreset)    //since "reset" is the "as" association between User and Passwordreset
user.addResets(password reset)  //I just added a plural, just for trial, still same error

Same goes for user.addAssociatedHappenings(happening) , as you mentioned above, still same error.  has no method xxx

**Comment by mickhansen** [comment]
@chuks Try logging `User.Instance.prototype` it should show you the method names.

**Comment by chuks** [comment]
Could you please tell me how to do that? I can only log to console using console.log(xxx). How do I log User.Instance.prototype? When I log to console, I get User.Instance.prototype: [object SequelizeInstance]

**Comment by chuks** [comment]
Ok, I found a way to print out all the methods in that prototype using this function:

unction getAllMethods(obj) {
  var result = [];
  for (var id in obj) {
    try {
      if (typeof(obj[id]) == "function") {
        result.push(id + ": " + obj[id].toString());
      }
    } catch (err) {
      result.push(id + ": inaccessible");
    }
  }
  return result;
}

I can see addReset for User model. However, when i call it on the user instance, it gives this error: TypeError: Object #<Object> has no method 'addReset'

i.e. nothing changes. If that function is correct, it means addReset is indeed in the instance, but when I call it, it fails.

**Comment by mickhansen** [comment]
@chuks What you are calling is likely not an instance of User then. Can you do `typeof object`?

I just saw this `User.find({where: whereObj}, {raw: true}).then(function(user){` (again, properly formatted code makes it easier for everyone).

You can't use `raw: true` and expect to have instance methods :)

**Comment by chuks** [comment]
Yes! That was it. Thanks much for the support! I didn't really understand what the raw flag was for. Good to know.
