### ISSUE TITLE
ARRAY(HSTORE) parsing error on linebreaks

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3383]
Hey,

if someone uses newlines in hstores and saves that data everything is going to be fine. Reading though is going to fail [here] (https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query.js#L23), since JSON.parse is not able to parse linebreaks.

So they have to be escaped before inserting or otherwise the reading can't be done with JSON.parse / linebreaks have to be escaped before reading with JSON.parse.

Here's a stacktrace with commit 2eadf0c705762d9fe4fa4d763cf26d5d305699c.
The code changes done since then did not fix the issue.

SyntaxError: Unexpected token at Object.parse (native) 
at /app/node_modules/sequelize/lib/dialects/postgres/query.js:21:24 
at forOwn (/app/node_modules/sequelize/node_modules/lodash/dist/lodash.js:2105:15)
at Function.forEach (/app/node_modules/sequelize/node_modules/lodash/dist/lodash.js:3302:9) 
at parseHstoreFields (/app/node_modules/sequelize/lib/dialects/postgres/query.js:15:11) 
at /app/node_modules/sequelize/lib/dialects/postgres/query.js:182:13 
at Array.forEach (native) 
at /app/node_modules/sequelize/lib/dialects/postgres/query.js:181:16 
at Promise._settlePromiseAt (/app/node_modules/sequelize/lib/promise.js:76:18)
From previous event:
at new SequelizePromise (/app/node_modules/sequelize/lib/promise.js:28:17) 
at module.exports.Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:70:19) 
at /app/node_modules/sequelize/lib/sequelize.js:724:20 
at Promise._settlePromiseAt (/app/node_modules/sequelize/lib/promise.js:76:18)
From previous event:
at module.exports.Sequelize.query (/app/node_modules/sequelize/lib/sequelize.js:720:20) 
at module.exports.QueryInterface.select (/app/node_modules/sequelize/lib/query-interface.js:733:27) at null. (/app/node_modules/sequelize/lib/model.js:739:34) 
at Promise._settlePromiseAt (/app/node_modules/sequelize/lib/promise.js:76:18)
From previous event: 
at module.exports.Model.findAll (/app/node_modules/sequelize/lib/model.js:697:20) at ...

**Comment by janmeier** [comment]
Hmm there shouldn't really be any reason to involve json here at all. There hstore file should be able to handle all parsing... 

It seems the code is creating a fake array by concating [] around the value and parsing that. Don't ask me why :-).

PR with test or a test case here in the thread would be welcomed

**Comment by BridgeAR** [comment]
I'll have a closer look at it later on.

**Comment by BridgeAR** [comment]
Well the best fix I could come up with right now is doing the following:

```javascript
    return DataTypes.ARRAY.is(options.dataType, DataTypes.HSTORE) ?
      Utils._.map(JSON.parse('[' +
        value.substring(1, value.length - 1)
          .replace('\n', '\\n')
          .replace('\t', '\\t')
          .replace('\r', '\\r') +
          ']'
        ), function (v) {
          return hstore.parse(v);
        }) : hstore.parse(value);
```
As far as I can see it, @seth-admittedly did the right [thing] (https://github.com/seth-admittedly/sequelize/commit/2f34a7bcfe4ed051bcbb469d152aa67e02cdde5c) by using JSON.parse.

Postgres returns the Array as {"\"type\"=>\"mobile\", "\"type\"=>\"landline\""}, that's the reason why he removes the first and last char and creates the fake array. The problem is, that \n\t etc. are not escaped in HStores and as far as I can see, should not be escaped.

By escaping these values before parsing the Array we bypass that problem.

There might be a nicer solution but I'm to tired to think of any at the moment.

Testwise it's easy to insert a \n or something into https://github.com/sequelize/sequelize/blob/master/test/integration/dialects/postgres/dao.test.js#L543

**Comment by BridgeAR** [comment]
@janmeier would you be so kind and point me to the part where you parse arrays? The search function through my cellphone is limited ;)
I guess the best way to resolve the issue is by using the array parsing already in place and parse the hstore afterwards - depending on the array parsing implementation used right now.

**Comment by janmeier** [comment]
@BridgeAR Array parsing for hstore happens right at the place you already found. And yes, after reviewing this again, it seems your suggestion of escaping the line breaks would be fine

**Comment by BridgeAR** [comment]
@janmeier Well I tried it before posting, so it should work ;)

**Comment by janmeier** [comment]
Thanks for helping in debugging this @BridgeAR :)

**Comment by BridgeAR** [comment]
This does not fix the issue, since I forgot to use the replace global. 
It should be
```javascript
.replace(/\n/g, '\\n')
```
But as we've spoken before I'll check if there's a better solution for this.

**Comment by janmeier** [comment]
I've changed the code to use `pg.types.arrayParser` as we spoke about yesterday - much cleaner now :)
