### ISSUE TITLE
Simple hasMany ( 1:m ) doesn't work as I expected

### ISSUE THREAD

**Issue by shin06** [sequelize/sequelize#3387]
Hello !

I have a trouble with hasMany 1:m relations .. with the results, it's doesn't retrieve me a array of results inside my main object, please look:

Model definition:
  var Event = sequelize.define("Event", { // fields });
  var User = sequelize.define("User", { // fields });

Relation definition:
Event.belongsTo( db.User, { as: 'author', foreignKey: 'user_id' } );
User.hasMany( db.Event, { as: 'events', foreignKey: 'user_id' } );

Then I search:
User.findAll({
    include: [{
      model: Event,
      as: 'events',
      }]
  }, {
    raw: true
  }).then(function(results) {
   console.log(results);
  });

And I get:

[
    {
        "id": 1,
        "name": null,
        "age": null,
        "phone_number": 1134167003,
        "hash": "dasjl891",
        "image": null,
        "description": null,
        "regid": null,
        "sex": null,
        "created_at": "2015-03-21T16:18:24.632Z",
        "updated_at": "2015-03-21T16:18:24.632Z",
        "deleted_at": null,
        "events.id": 1,
        "events.title": "Titulo",
        "events.created_at": null,
        "events.updated_at": null,
        "events.deleted_at": null,
        "events.user_id": 1
    },
    {
        "id": 1,
        "name": null,
        "age": null,
        "phone_number": 1134167003,
        "hash": "dasjl891",
        "image": null,
        "description": null,
        "regid": null,
        "sex": null,
        "created_at": "2015-03-21T16:18:24.632Z",
        "updated_at": "2015-03-21T16:18:24.632Z",
        "deleted_at": null,
        "events.id": 2,
        "events.title": "Celebration of lizard!",
        "events.created_at": null,
        "events.updated_at": null,
        "events.deleted_at": null,
        "events.user_id": 1
    }
]

I wish get all Events related with User inside each User as array .. Like de documentation explain in the "Eager loading" example ( http://docs.sequelizejs.com/en/latest/docs/models/#nested-eager-loading ) ... Example:

[
 {
   user_id: 1,
   events: [
       { event_id: 1 }, { event_id: 2 }, ... 
   ]
 },
  user_id: 2,
  events: []
]

I was searching 2 days without any clue, if you can help me please! And thanks for Sequelize!

**Comment by mickhansen** [comment]
Remove `raw: true` and it should work as expected.
Having `raw: true` behave better with includes is a known issue and on our roadmap :)

**Comment by shin06** [comment]
Thank you ! It works perfectly ! :D
