### ISSUE TITLE
(support) Best practices for migrations.

### ISSUE THREAD

**Issue by ericrini** [sequelize/sequelize#3388]
Hello gentlemen, you have built quite the kickass product here. I am finding that the migrations are useful, but possibly missing some features.

The first question is the initial migration. Basically, how do you setup a database.

```
var db = require('../models');

module.exports = {
	up: function(migration, DataTypes, done) {
		db.sequelize.sync({ 
				logging: console.log,
				force: true 
			})
			.finally(function () {
				done();
			});
	},

	down: function(migration, DataTypes, done) {
		db.sequelize.drop()
			.finally(function () {
				done();
			});
	}
};
```

Theoretically this would save me a lot of time defining all of the tables in the schema. However, I see a problem where there is lets say 3 migrations. Performing this step at any point in time makes the remaining 2 migrations unnecessary (as they would be diffs from previous sequelize.sync() calls that could be used on database instances that had already been sync()ed once before). 

So somehow, this migration should make sure to mark those migrations as having already been run on this database.

Is this possible?

-----

Next issue I am having is tearing down migrations that add data. It seems like I may be using migrations in an unintended way here.

This is useful for static data (for example roles and permission lookup tables) as well as for creating standardized sets of test transactions for other developers.

```
var db = require('../models');

module.exports = {
	up: function(migration, DataTypes, done) {
		var data = generateRandomData();

		async.series([
			function (callback) {
				db.Advisors.bulkCreate(data.advisors).finally(callback);
			},
			function (callback) {
				db.Plans.bulkCreate(data.plans).finally(callback);
			},
			function (callback) {
				db.InvestmentVehicles.bulkCreate(data.investmentVehicles).finally(callback);
			},
			function (callback) {
				db.AdvisorsToPlans.bulkCreate(data.advisorsToPlans).finally(callback);
			}
		], function (error) {
			if (error) {
				console.error(error.stack);
			}
			done();
		});
	},

	down: function(migration, DataTypes, done) {
		async.series([
			function (callback) {
				db.sequelize.query('SET FOREIGN_KEY_CHECKS = 0;').finally(callback);
			},
			function (callback) {
				db.AdvisorsToPlans.destroy({
						truncate: true
					})
					.finally(callback);
			},
			function (callback) {
				db.InvestmentVehicles.destroy({
						truncate: true
					})
					.finally(callback);
			},
			function (callback) {
				db.Plans.destroy({
						truncate: true
					})
					.finally(callback);
			},
			function (callback) {
				db.Advisors.destroy({ 
						truncate: true
					})
					.finally(callback);
			},
			function (callback) {
				db.sequelize.query('SET FOREIGN_KEY_CHECKS = 0;').finally(callback);
			}
		], function (error) {
			if (error) {
				console.error(error.stack);
			}
			done();
		});
	}
};
```

Is there currently a way to avoid the raw SQL query in the teardown for this migration.

**Comment by mickhansen** [comment]
For marking migrations as done when using sync i believe there's an issue open on umzug (the migrator the cli uses) for doing something like that.

I don't think the raw sql can be avoided unless you use `cascade: true` aswell, in which case it will cascade.

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
