### ISSUE TITLE
A question about generating Sequialize model from DB

### ISSUE THREAD

**Issue by ftrotter** [sequelize/sequelize#339]
Hi,
I have a really complex database that I would like to migrate to Sequelize. (thanks for the lovely code of course).

I am planning on writing a php script (not fast enough with JS yet) that looks at my database structure and makes starting sequelize models. A couple of questions before I get started:
- Is there anything like this already written that I should be using for this?
- The type mapping seems tolerant at first blush, and if I add validation (i.e. to account for smaller VARCHAR space, etc) it appears that it will work. Will I run into problems not keeping to exact parameters for field types?
- Any advice generally for this approach?

-ft

**Comment by aireater** [comment]
> sequelize.getQueryInterface().describeTable(tableName).success( … )
// => this will result in the structure of a table with all it's attributes and

> sequelize.getQueryInterface().showAllTables().success( … )
// => this will result in an array with all existing table names

.success has been replaced with .then
