### ISSUE TITLE
Saving an Unchanged Instance Causes Error

### ISSUE THREAD

**Issue by elsbree** [sequelize/sequelize#3394]
This seems to be a pretty major bug. If I attempt to call `instance.save()` on an unchanged instance, an error is thrown.

Here's a line of code that can cause this error (assume a User model with id=1 is defined):
```javascript
models.User.find(1).success(function(user) {
    user.save();
});
```

This error occurs because of [line 491 of lib/instance.js](https://github.com/sequelize/sequelize/blob/ab8ca5308a7e3973529238862c1479df2177169a/lib/instance.js#L491):
`options.fields = _.intersection(this.changed(), Object.keys(this.Model.attributes));`
and `this.changed()` returns `false` instead of an empty array.

I can submit a PR which causes `this.changed()` to return an empty array, I just wanted to make sure that this wouldn't cause any unexpected problems elsewhere.

**Comment by mickhansen** [comment]
Better to change 491 to `this.changed() || []`, `changed()` has public and documented semantics we can't change currently.

But yeah that is a bug, i thought we had tests for no-op updates actually.

**Comment by elsbree** [comment]
I see. I'll work on a PR. Thanks for the quick response!

**Comment by elsbree** [comment]
I was actually incorrect about the cause of this error. It looks like this is due to an [issue](https://github.com/lodash/lodash/issues/643) with lodash's intersect function with large arrays. The issue has been fixed in lodash's latest versions, but I can't seem to get Sequelize's tests to pass when I update to the latest version of lodash.

**Comment by janmeier** [comment]
I'm working on upgrading lodash to the lastest version, hopefully I'll have it ready soon :)

**Comment by janmeier** [comment]
Lodash has been updated, closing this
