### ISSUE TITLE
Get association with condition

### ISSUE THREAD

**Issue by Philmod** [sequelize/sequelize#3395]
Hey,

Is it possible to get the association using a condition on a foreign key.

If I use the example from this [page](http://docs.sequelizejs.com/en/latest/docs/associations/): 
```
User = sequelize.define('User', {})
Project = sequelize.define('Project', {})
UserProjects = sequelize.define('UserProjects', {
    status: DataTypes.STRING
})
 
User.belongsToMany(Project, { through: UserProjects })
Project.belongsToMany(User, { through: UserProjects })

user.addProject(project, { status: 'started' })
```

Is it possible to do something like?
```
project.getUsers({where: ["UserId = ?", user.id] })
```
(I'm getting this error: `[SequelizeDatabaseError: column "userid" does not exist]`)

Or:
```
project.getUsers({where: ["username = ?", user.username] })
```
?

Thanks,
Philmod

**Comment by Philmod** [comment]
Nevermind, it works that way: 
```
project.getUsers({where: ["id = ?", user.id] })
```

**Comment by janmeier** [comment]
Glad you solved your issue, however I would recommend using `{where: { id: user.id }}?`
