### ISSUE TITLE
Performance issues since version 2.0.3

### ISSUE THREAD

**Issue by KTachyon** [sequelize/sequelize#3397]
I have noticed that since version 2.0.3 the performance of Sequelize has been hit a little bit hard for bigger queries. It doesn't seem to be a query de-optimisation issue, since both 2.0.2 and 2.0.3+ generate the same queries.

An example with a very noticeable performance hit:

``` javascript
AModel.findAll({
    where : {
        column1: 'someString',
        column2: [ /* around 300 UUIDs */ ]
    }
}, { transaction : transaction })
```

This query, on 2.0.2, takes around 30ms, while on 2.0.3 through 2.0.5, takes around half a second.

**Comment by mickhansen** [comment]
Hmm, that is strange.

**Comment by janmeier** [comment]
Sounds like a job for git bisect http://git-scm.com/docs/git-bisect - I'll hopefully have time to look into it in the comming days.

If you could provide a self contained test case with model definition, sync call and some example IDs that would be absolutely wonderfull! :)

**Comment by janmeier** [comment]
I'm pretty convinced the decreased in performance lies somewhere in parsing, so some test data would also be very nice

**Comment by KTachyon** [comment]
I believe the problem is not just the size of the query. I was trying to build a self contained test case, but there's no performance hit as is (only about 10ms difference). The issue may be related with some constraint mix. Both the columns have a compound unique constraint and are both foreign keys. The problem is that I can't currently reproduce the problem using the test, so it's kind of useless. I'll keep you posted.

**Comment by KTachyon** [comment]
Ok, I still can't reproduce the lower performance issue in an isolated test case. I decided to follow the code changes and try to find out where time is being spent and I found out that the problem lies in the Utils.mapOptionFieldNames which was changed on version v2.0.3.

The problem seems to happen here:

https://github.com/sequelize/sequelize/blob/9ebfb19fbaf4aeb9f514a348995b7c782bac4732/lib/utils.js#L212

Since the column2 is an array os UUIDs (or strings), each will be sent to the recursive call of Utils.mapOptionFieldNames.

Then, it will check each "attribute" of each string (UUID) for an array, which, in my case, means testing from the attribute 0 through 35 (the size of an UUID) and whatever other attributes it finds in there. Like these:

```
bold
strip
stripColors
trap
zalgo
zebra
rainbow
random
america
reset
dim
italic
underline
inverse
hidden
strikethrough
black
red
green
yellow
blue
magenta
cyan
white
gray
grey
bgBlack
bgRed
bgGreen
bgYellow
bgBlue
bgMagenta
bgCyan
bgWhite
blackBG
redBG
greenBG
yellowBG
blueBG
magentaBG
cyanBG
whiteBG
greyBG
```

I don't really know where those come from, and I cannot reproduce those on a self contained test case, but I don't think that this is the intended behaviour.

If I add these lines:

```
console.log(attribute, Array.isArray(attributes[attribute]));
console.log(attribute, attributes[attribute]);
```

Just before that line, this is what I'm getting back on the console:

![screen shot 2015-03-24 at 16 54 48](https://cloud.githubusercontent.com/assets/1596736/6807528/e3e6f892-d246-11e4-9ff5-ea6b3a2bf9c4.png)


Anyway, I have created a representation of the models and data I'm having trouble with. You can find it here: https://github.com/KTachyon/SequelizeIssue-3397

**Comment by mickhansen** [comment]
Hmm yeah so that recursively maps to make sure the query works.
And then for some reason either the array or the values in the array has weird props that it keeps iterating on ;p

**Comment by janmeier** [comment]
Hmm is winston modifying array.prototype / object.prototype? Maybe it can be solved with a hasOwnProperty check

**Comment by mickhansen** [comment]
That shouldn't matter for .map i'd think, but maybe it's hitting https://github.com/sequelize/sequelize/blob/9ebfb19fbaf4aeb9f514a348995b7c782bac4732/lib/utils.js#L206?

**Comment by KTachyon** [comment]
It's not going inside that if.

But I don't think that even if I remove winston weirdeness, it will still be checking each char individually. So, 282 UUIDs, 36 chars each, it's 10152 cycles (or 282 function calls with 36 cycles each). Do we really have to check the properties of string objects? Filtering strings using lodash's isString function seems to solve the issue. Do you predict that to have an impact on how Sequelize works out the queries?

**Comment by mickhansen** [comment]
@KTachyon its recursing on the array since it could possible be a `$or: []` set, but it shouldn't be recursing another level since it looks for the `where` key.

**Comment by Rleahy22** [comment]
+1
