### ISSUE TITLE
duplicate entry Validation error

### ISSUE THREAD

**Issue by mabumeshref** [sequelize/sequelize#3399]
I am not able to create duplicate entries in my join table (SpaceMenu): as sometimes the space(area) may have the same menu multiple times.

I was reading the issues and tried the workaround (applying belongsTo for join table) but it doesn't work for me I am still getting the following error.

SequelizeUniqueConstraintError: Validation error
PRIMARY must be unique

in Menu model I have the following:
```
Menu.belongsToMany(models.Space, {through: models.SpaceMenu,foreignKey: 'menuId'});
```

in Space table I have the following:
```
Space.belongsToMany(models.Menu, {through: models.SpaceMenu, foreignKey: 'spaceId'});
```

and in UserItem model I have the following:
```
tagId: {type: DataTypes.INTEGER},
..
associate: function (models) {
SpaceMenu.belongsTo(models.Space);
SpaceMenu.belongsTo(models.Menu);
}
```

The insert statements:
```
INSERT INTO `SpaceMenu` (`tagId`,`spaceId`,`menuId`,`spaceMenuUpdatedAt`,`spaceMenuCreatedAt`) VALUES (135,3,1,'2015-03-24 15:47:37','2015-03-24 15:47:37');

INSERT INTO `SpaceMenu` (`tagId`,`spaceId`,`menuId`,`spaceMenuUpdatedAt`,`spaceMenuCreatedAt`) VALUES (136,3,1,'2015-03-24 15:47:37','2015-03-24 15:47:37');
```

am I doing something wrong here?

**Comment by mickhansen** [comment]
`belongsToMany` currently enforces a single entry per relation, and also adds a unique constraint.
There's a feature request somewhere for allowing non-unique N:M but we don't support that currently.

You can however achieve it by simply mapping to SpaceMenu directly.

**Comment by mabumeshref** [comment]
Now I have another table "Tag", so they are 3 tables and I want to create a junction table for those three tables. what shall I do in this case, to make those three keys as primary key to stop throwing duplicate entry validation.

**Comment by mickhansen** [comment]
You need a table that references both Tag, SpaceMenu and Menu? How come?
In any case if you do want that you'll have to maintain a model and the relationships seperately, we don't support 3 model junction tables natively.

**Comment by mabumeshref** [comment]
I want the junction table to reference Space, Menu, and Tag (In my case, Tag number is the unique number and both space and menu ids might be the same in multiple records)

**Comment by janmeier** [comment]
No response, closing
