### ISSUE TITLE
Missing documentation for operators beginning with $

### ISSUE THREAD

**Issue by juansev** [sequelize/sequelize#3405]
Please add to the documentation the meaning of all operators, including the obscure operators starting with $ (that i don't know what is the semantic difference)

**Comment by janmeier** [comment]
$ makes it easier to distinguish between attributes and operators. Most should already be documented here http://docs.sequelizejs.com/en/latest/docs/models/#findall-search-for-multiple-elements-in-the-database and in the next paragrahp

**Comment by juansev** [comment]
I have seen in the unit tests for where.js that there is a test with $not and the field deleted that is adding automatically an "IS" to make "IS NOT". That change in behaviour is not clear at all in the docs.

**Comment by mickhansen** [comment]
@juansev What were you expecting `$not` to do for null values?

**Comment by janmeier** [comment]
Closing, no response
