### ISSUE TITLE
Retrieving data in legacy table postgres

### ISSUE THREAD

**Issue by Bondifrench** [sequelize/sequelize#3408]
I am using `sequelize 2.0.4` with Postgres using pg.js and pg-hstore
I have a non-empty table in Postgres called `Users` with id, email, password, createdAt, updatedAt columns which was created with Sequelize a while ago
I have the following code:
````
var configDB = require('../config/database');
var Sequelize = require('sequelize');
var sequelize = new Sequelize(configDB.dbname, configDB.user, configDB.password, {
	dialectModulePath:"pg.js",
	dialect: "postgres",
	port: 5432
});

var User = sequelize.define('User',{
		email: Sequelize.STRING,
		password: Sequelize.STRING 
	});
````
I manage to authenticate with:
````
sequelize
	.authenticate()
	.then(function () {
			return console.log('Connection has been established successfully');
	})
	.catch(function (error) {
			return console.log('Unable to connect to the database', error);
	})
````
but when I try to retrieve data from the `User` table:
````
sequelize
	.sync()
	.then(function() {
		return User.findAll()
			.then(function(content) {
				console.log('content =', content);
				for (var i = 0; i < content.length; i++) {
					console.log(content[i].dataValues);
				}
			});
	})
	.catch(function(error) {
		console.log('Problem trying to retrieve data: ', error);
	});
````
`content` is empty!!
I manage to retrieve data from other tables in the same db with the same syntax, but this ones shows me nothing.

**Comment by janmeier** [comment]
Are you sure that the query is looking in the right table? Remember that postgres is case and tick sensitive, so it might be that sequelize is creating a new table?

**Comment by Bondifrench** [comment]
In Postgres my table is called Users, what do you mean by tick sensitive? 


Sent on the go with Vodafone

<div>-------- Original message --------</div><div>From: Jan Aagaard Meier <notifications@github.com> </div><div>Date:26/03/2015  7:09 PM  (GMT+10:30) </div><div>To: sequelize/sequelize <sequelize@noreply.github.com> </div><div>Cc: Dominik Dumaine <d_dumaine@yahoo.com> </div><div>Subject: Re: [sequelize] Retrieving data in legacy table postgres (#3408) </div><div>
</div>Are you sure that the query is looking in the right table? Remember that postgres is case and tick sensitive, so it might be that sequelize is creating a new table?

**Comment by janmeier** [comment]
I don't remember the specifics, but if the table was created as `CREATE TABLE Users` it won't be matched by `SELECT FROM "Users"` as I remember it. Can you check if sequelize.sync has created an additional table

**Comment by Bondifrench** [comment]
It did create a new table 'users', I tried with tablefreezename 'Users', didn't work, as it was the new created table...and then I deleted by accident the old table...bummer!

**Comment by janmeier** [comment]
Sorry to hear that! 

Closing this issue, since it is neither a bug report nor a feature request.

In the future, for general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
