### ISSUE TITLE
findOrCreate w/ JSON DataType (PostgreSQL)

### ISSUE THREAD

**Issue by blakmatrix** [sequelize/sequelize#3410]
Hi,
I was trying to use the `findOrCreate` method with postgresql on a coulumn with a JSON datatype, I tried various combinations but could not get it working correctly.

`{where: myObj}` -- would end up spitting out error that column name x (x being a key in the object) didnt exist
`{where: Sequelize.json({data: myObj})}` -- would pass the find query, but ended up completely failing to insert on `data`, yet basically created a blank record (`created_at`, `updated_at`, `id(auto)`)
I tried a few other crazy combinations but no success. Is this a bug or perhaps I'm reading the api wrong?

**Comment by mickhansen** [comment]
That functionality is likely missing, so somewhat of a bug.

**Comment by BridgeAR** [comment]
@mickhansen this should be fixed since 2.1, right?

**Comment by mickhansen** [comment]
@BridgeAR Not sure for findOrCreate actually, but likely yes, haven't tested.

**Comment by BridgeAR** [comment]
This is solved
