### ISSUE TITLE
Simplify running migrations in included packages

### ISSUE THREAD

**Issue by madtrick** [sequelize/sequelize#3412]
Consider the following setup:

```
$ tree -L 2 project-A
├── config
│   └── databases.json
├── gulpfile.js
├── node_modules
│   ├── project-B
├── package.json
```

On this scenario if I'd like to run migrations which are kept inside `project-B` I'd have to do the following:

1. Install `sequelize-cli`, `sequelize`, and other packages in `project-A`
2. Execute the following command from `project-A`: `sequelize db:migrate --config config/databases.json --migrations-path node_modules/project-B/migrations/`

It would be nice to make this easier and less error prone.

**Comment by janmeier** [comment]
It's recommended to install packages globally for migrations - That would solve problem 1. 

Also, migration logic has been removed from the main logic, see https://github.com/sequelize/umzug and https://github.com/sequelize/cli

**Comment by sdepold** [comment]
Hi Jan,

we will take care of this problem in our submodule itself. It's nothing the either the CLI nor the sequelize core can fix.

:+1:

**Comment by madtrick** [comment]
sorry for creating noise here
