### ISSUE TITLE
Secondary indexes not using fieldname mappings

### ISSUE THREAD

**Issue by quiddle** [sequelize/sequelize#3413]
If I define a model like this:

``` javascript
 sequelize.define('campaignRecipient',
    {
      status: {
        field:        'mail_status',
        type:         types.ENUM('pending','sent','cancel'),
        allowNull:    false,
        defaultValue: 'pending'
      }
    },
    {
      indexes: [
        { fields: ['status'] }
      ],
    }
  );
```

and then call `db.models.campaignRecipient.sync()`, I'll get the error `ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'status' doesn't exist in table`. It works fine using `mail_status` in the `indexes` array.

**Comment by janmeier** [comment]
Well since indexes are defined at model definition time I think its a reasonable constraint to only use actual fields names

**Comment by quiddle** [comment]
I follow the logic, but it seems to me that if you're using the `indexes` option, you've already defined how you want your fields to be named. Perhaps you're covering up some ugly legacy naming or trying to gain some consistency in naming. It seems valid to want to use the cleanly defined fieldnames wherever you specify fields.

**Comment by mickhansen** [comment]
I'd agree that it should atleast attempt to match model attribute names.

**Comment by quiddle** [comment]
I originally planned to submit a pull request to fix this, but I couldn't really decide where the change belonged.

The easiest spot to make the change would be in the `model.sync` definition, where indexes are created. However, Sequelize handles `unique` indexes directly in the `createTableQuery` function for each dialect. At least in MySQL, it's possible to specify secondary indexes in the create table statement. Is there a reason sequelize doesn't do it that way?

**Comment by janmeier** [comment]
I think the proper place to do it would be in `model.sync`. Create table on handles unique indexes for single columns
