### ISSUE TITLE
findAll with Multiple items in array large performance degredation

### ISSUE THREAD

**Issue by Rleahy22** [sequelize/sequelize#3414]
Using sequelize to perform a findAll on a table that has an index on the column used in where clause saw a huge performance decrease from 1.7.x to 2.0.x when given an array with multiple values. See code below:

```javascript
Model.findALL({
    where: {
        columnName: ids
    }
});
```

*ids* can either be a single integer or array of integers.  I benchmarked this in 1.7.8, 1.7.10, 2.0.0-dev1, 2.0.0, and 2.0.4.

With 1 id, the 2.0.x branches saw ~5-10% improvement.
With 5 ids the 2.0.x branches saw ~30% decrease in performance
With 150 ids the 2.0.x branches saw ~130% decrease in performance

(using Node@0.10.36 and MySQL@5.6.17)

**Comment by Rleahy22** [comment]
I've created a repo that demonstrates the issue: https://github.com/Rleahy22/sequelize-example

**Comment by andrewaustin** [comment]
We're running into #91 and looking to upgrade to 2.0.x because it has a fix but are now running into this issue.

**Comment by andrewaustin** [comment]
I did some profiling and saw most of the time seemed to be spent in libc, rather than in the JS code. So I ran a bunch of different benchmarks:

| Sequelize Version | Node Version | IDs | Run 1 | Run 2 | Run 3 | Avg |
|--------------------------|--------------------|------|---------|-----------|---------|--------|
| 2.0.5 | 0.10.38 | 1500 | 48,294 ms| 44,896 ms | 48,766 ms | **47,319 ms** |
| 1.7.10| 0.10.38 | 1500 | 37,239 ms| 36,921 ms | 40,841 ms | **38,334 ms** |
| 2.0.5 | 0.12.1 | 1500 | 37,557 ms | 36,902 ms| 40,926 ms | **38,461 ms** |
| 1.7.10| 0.12.1 | 1500 | 38,900 ms | 34,861 ms| 38,546 ms | **37,436 ms** |

There is clearly an issue with 2.0.5 and Node 0.10.x but it seems to go away once you upgrade to 0.12.1.

**Comment by mickhansen** [comment]
@andrewaustin that's interesting, points to a dependency issue perhaps.

**Comment by Rleahy22** [comment]
I tried to replicate Andrew's example and my results were very different and still in line with my what I reported originally (on OSX 10.9.5)

| Sequelize Version | Node Version | Ids | Run 1 | Run 2 | Run 2 | Avg
|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------
| 2.0.5 | 0.10.38 | 1500 | 21,348 ms | 21,230 ms | 21,436 ms | **21,338 ms**
| 1.7.10 | 0.10.38 | 1500 | 17,400 ms | 17,347 ms | 17,465 ms | **17,404 ms**
| 2.0.5 | 0.10.38 | 1500 |  17,781 ms | 17,558 ms | 17,674 ms | **17,671 ms**
| 1.7.10 | 0.10.38 | 1500 | 16,888 ms |  16,269 ms | 16,617 ms | **16,591 ms**

While the regression is not as drastic with Node 0.12.1, it still exists, and is still less performant than even Sequelize 1.7.10 on Node 0.10.38

**Comment by Rleahy22** [comment]
Additionally on Node 0.12.1 150 ids still exhibits a large level of regression (~30%)

| Sequelize Version | Node Version | Ids | Run 1 | Run 2 | Run 2 | Avg
|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------
| 2.0.5 | 0.12.1 | 150 | 5,158 ms | 4,930 ms | 4,852 ms | **4,980 ms**
| 1.7.10 | 0.12.1 | 150 | 3,872 ms | 3,870 ms | 3,911 ms | **3,884 ms**

**Comment by mickhansen** [comment]
@Rleahy22 same connector library (mysql/sqlite/pg) version?

**Comment by mickhansen** [comment]
It's probably an issue with field name mapping traversal which was reported in another issue aswell (although i can't find it atm).

**Comment by Rleahy22** [comment]
Sorry I just saw this. I used the same MySQL version for all tests.

**Comment by mickhansen** [comment]
Regression confirmed. Some of it might be the Promise refactor, hard to say.

**Comment by mickhansen** [comment]
The execution time for a single select in your benchmark has barely changed.

**Comment by mickhansen** [comment]
Okay a bit of testing reveals that this in fact mostly due to the internal rewrite to Promises.
There's also a small hit from a new where query generator but that's very minor.
We'll be able to upgrade to a newer version of bluebird soon-ish and that should help somewhat.
