### ISSUE TITLE
.query(sql, model) method return raw instead of instance.

### ISSUE THREAD

**Issue by jchbh-duplicate** [sequelize/sequelize#3415]
As document said, the method .query(sql, model) should return instances instead of raw data without giving the "type" option to say it is an query action.
but I found in 2.0.5, it still return the raw data.

I fix in local by replace 

sequelize.js line 685
        options = {}
into 
        options = {type:QueryTypes.SELECT};

to fix this problem.

**Comment by mickhansen** [comment]
@jchbh-duplicate That's intended since the raw query changes described in upgrading to 2.0.
@janmeier question is if SELECT should be default with callee?

**Comment by janmeier** [comment]
Callee is also used for insertion, but yeah select might be the most common case

**Comment by mickhansen** [comment]
@janmeier Yeah i know but i suppose one can expect a user to supply the type in that case.

**Comment by janmeier** [comment]
True dat!
