### ISSUE TITLE
Documenting the use of `through` in find with BelongsToMany association

### ISSUE THREAD

**Issue by yonjah** [sequelize/sequelize#3416]
The only mention of this I could find was in -
https://github.com/sequelize/sequelize/issues/3258

I would suggest adding -

When eager loading the through parameter can be used to define the required relations.
The following example will only fetch Projects that have been started -

```javascript
User.findAll({ 
    include: [{
        model: Project,
        through: {
            where: {started: true}
        }
    }]
}).then(...);
```

To http://docs.sequelizejs.com/en/latest/api/associations/#belongstomanytarget-options

This would probably be enough to hint most users about the use of through but you might want to document its full API

**Comment by mickhansen** [comment]
Both `through.where` and `through.attributes` need to be documented definitely.

**Comment by harimohanraj89** [comment]
@mickhansen The documentation for `through.where` and `through.attributes` applies to all associations between models, yes (hasOne, hasMany, belongsTo, belongsToMany)? Would it make sense to add this to all four documentation sections?

**Comment by mickhansen** [comment]
@harimohanraj89 No `through` only exists on belongsToMany.

**Comment by harimohanraj89** [comment]
Ah, my mistake. I was thinking of the `include` option on finder methods. :+1:
