### ISSUE TITLE
How to get changed fields

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3418]
I am trying to create an audit trail of some of my tables. I am currently trying to use `beforeUpdate`, `beforeCreate`, `beforeDestroy` hooks to get old values and then to create a history entry.

I can get the field names that changed, but I'm not sure how to get the old values:

Item.beforeUpdate(function(item, options, fn) {
  changed_fields = item.changed();
 
  // how to get the old values for each changed_fields?
});

**Comment by maplesap** [comment]
Okay, so old data can be accessed through `item._previousDataValues`

**Comment by mickhansen** [comment]
Or through `previous(key)`, although that operates on keys.
`_previousDataValues` is not public API so don't expect stability.
