### ISSUE TITLE
Model-based Identity map

### ISSUE THREAD

**Issue by closealert** [sequelize/sequelize#342]
I propose to implement a model-based identity map to prevent building the same instance multiple times. This would give you the benefit that once an instance has been built by a finder (or by create/save), finding the same object would return a reference to that object. This would allow multiple event loops to work on the same object. (This is actually also really necessary for #340)

Implementing would probably require LRU-caching for the identity map. This is probably a feature for a major release as it significantly alters the behavior of `find`, `findAll` and `create`. Backward compatibilty could be provided through configuration (eg. `indentityMap: bool`)

**Comment by BridgeAR** [comment]
I guess this should be closed? This proposal is best as a plugin with a shared in memory cache like redis And should probably not go into core? @janmeier @mickhansen

**Comment by janmeier** [comment]
Yep, definitely a good fit for a plugin
