### ISSUE TITLE
Missing REGEXP in query generator.

### ISSUE THREAD

**Issue by sdimit** [sequelize/sequelize#3420]
It isn't currently possible to use 

```
where: {
   name: {
      regexp: '*'
   }
}
```

even though MySQL, for example, supports the [regexp operator](http://dev.mysql.com/doc/refman/5.0/en/regexp.html#operator_regexp).

Alternatively, one should be able to write

```
where: {
   name: {
      'REGEXP': '*'
   }
}
```

in order to use keywords not supported by Sequelize.

**Comment by mickhansen** [comment]
Not sure i agree about the second point, we would have to use it literally and that opens people up to injection attacks.

**Comment by Russ93** [comment]
You can make it a prepared statement. That should help with injection problem.

**Comment by Dayjo** [comment]
I really would like this, at the moment I'm struggling how to work out how to do this with multiple LIKES and ORs

**Comment by felixfbecker** [comment]
@Russ93 It would not help with the injection problem at all if `where` comes from client input

**Comment by gavinr** [comment]
Adding this line [here](https://github.com/sequelize/sequelize/compare/master...gavinr:patch-1) allows me to use regex in mysql like @Russ93 is mentioning. It works for me, but I'm guessing is not a complete solution ... interested in @mickhansen's thoughts.

**Comment by Dayjo** [comment]
Definitely keen to know what else needs to happen other than that @gavinr

**Comment by saurabhverma2892** [comment]
A work around for anyone who still needs it:

`where:{
    name = Sequelize.literal(' `name` REGEXP "john|doe" ')
}`

**Comment by jaslocum** [comment]
gavinr, you comment about adding the line is no longer active.  Do you have the example some where else?  What version of sequelize was the modification for.

**Comment by sushantdhiman** [comment]
Now supported

```
[Op.regexp]: '~',
[Op.notRegexp]: '!~',
[Op.iRegexp]: '~*',
[Op.notIRegexp]: '!~*',
```

**Comment by rod-stuchi** [comment]
@saurabhverma2892 you saved my day!
Thank you.
