### ISSUE TITLE
transaction not used in hooks when cascading deletes

### ISSUE THREAD

**Issue by jrmurad** [sequelize/sequelize#3422]
If I destroy({transaction: t}) an instance of a model which hasMany(Other, { onDelete: 'cascade', hooks: true }), then I think options.transaction in Other's hooks should be populated with t? I believe they are not because instance.destroy() in QueryInterface.prototype.delete does not pass the transaction along? Should this be the default behavior (to destroy dependents within the same transaction)?

(note: I was using CLS at first but ran into other issues, in particular with findOrCreate using postgres)
(note2: I first tried to destroy on the the model({where: {id: xyz}, transaction: t, individualHooks: true}) rather than an instance but found that Other's hooks weren't being called at all)

**Comment by mickhansen** [comment]
If that is infact true (which with your effort i believe it is) then it's definitely a serious bug yes.
