### ISSUE TITLE
How to query a model on a joined model’s property without including it?

### ISSUE THREAD

**Issue by huguesdk** [sequelize/sequelize#3428]
With models defined like this:

    Team = sequelize.define 'team',
      name: Sequelize.STRING

    User = sequelize.define 'user',
      name: Sequelize.STRING
      foo: Sequelize.INTEGER

    Team.hasMany User
    User.belongsTo Team

how to get all teams containing users where `foo` is equal to `42`, without including users in the result, and without having the same team multiple times in the result, that is, how to generate exactly the following query?

    SELECT DISTINCT team.id, team.name
    FROM team
    INNER JOIN user ON user.team_id = team.id
    WHERE user.foo = 42

Note: The query should be a raw query, that is, using the `raw` option of `findAll()`.

**Comment by rkmax** [comment]
:+1: I'm interested in querying for a object through his relationships

Example, assuming i have the following objects

House 1:m People
People n:m hobby

Queries:

- I want search all houses that have a least a person with the hobby "Sports" for example
- I want search all houses that have a person that have the hobbies "Sports" and "Watch movies" (both)
- I want able to count/paginate the previous queries, if it's possible without using raw queries?

**Comment by mickhansen** [comment]
@rkmax what have you tried so far? `include.where` covers atleast case 1 & 2.

**Comment by mickhansen** [comment]
We are working on a way to query relations without it being on the join specifically.

**Comment by janmeier** [comment]
```js
return Team.findAll({
    attributes:  [sequelize.literal('DISTINCT team.id'), 'id', 'name'],
    include: User,
    where: {
      '$users.foo$': 42
    }
  });
```

I know its slightly silly to select id after the distinct select, but otherwise sequelize will try to add it as the first attribute, which will make the query fail
