### ISSUE TITLE
Association with through table addProperty

### ISSUE THREAD

**Issue by sebay00** [sequelize/sequelize#3429]
Hi everybody,

This issue is a question, so :
I'm stuck, and I don't understand what I'm doing wrong.

I created a through model, and added a line into it with : 
`attendee.addBooking(booking)`, that's functionnal.

Here's the SQL code : 
```sql
INSERT INTO `Invites` (`id`,`status`,`email`,`bookingId`,`userId`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'PENDING','test',3,1,'2015-03-30 15:53:55','2015-03-30 15:53:55');
```

But when I reverse: `booking.addAttendee(attendee)`,It doesn't work anymore.
I'm wondering why ? 

Here's the SQL code : 
```sql
INSERT INTO `Invites` (`id`,`status`,`email`,`bookingId`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'PENDING','user@gmail.com',1,'2015-03-30 15:25:49','2015-03-30 15:25:49');
```

It's just ignoring my attendee, like it was empty.But I checked and it's not. 
I insist on the fact that I had `attendee.addBooking(booking)` and it was working, and because of the reversion (It should do the same thing, shouldn't it ?), it's not anymore.

My invite (through) model : 
```js
var Invite    = module.exports = orm.define("Invite", {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  status: {
    type: Sequelize.ENUM("PENDING", "ACCEPTED", "DECLINED"),
    defaultValue: "PENDING"
  },
  email: {
    type: Sequelize.CHAR(50)
  }
});

Invite.associate = function(models) {
  Invite.belongsTo(models.User, { as: "user", allowNull: true});
  Invite.belongsTo(models.Booking, { as: "booking" });
};
```

Booking model association : 
```js
  Booking.belongsToMany(models.User, {
    as: "attendees",
    through: {
      model: orm.models.Invite,
      as: "invite"
    },
    foreignKey: "bookingId",
    onDelete: "CASCADE",
    onUpdate: "CASCADE"
  });
```

And User one : 
```js
 User.belongsToMany(models.Booking, {
    through: {
      model: orm.models.Invite,
      as: "invite"
    },
    as: "bookings",
    foreignKey: "userId",
    onDelete: "CASCADE",
    onUpdate: "CASCADE"
  });
``` 
Best regards,

Seb :)

**Comment by janmeier** [comment]
Please show model definitions and associations

**Comment by sebay00** [comment]
@janmeier Updated. Maybe you need more ?

**Comment by janmeier** [comment]
Hmm, maybe its not properly identifying the relation between the two `belongsToMany`s. Try to change both to `through: orm.models.Invite`

**Comment by sebay00** [comment]
@janmeier And problem solved. You're the man !
