### ISSUE TITLE
How works migrations in sequelize ?

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3431]
Hi guys I'm trying understand how work migrations in sequelize,

I have my user model

```javascript
var User = sequelize.define('User', {
            name: DataTypes.STRING,
            email:  DataTypes.STRING,
            hashedPassword: DataTypes.STRING
});
```

and my migration create_users_table

```javascript
module.exports = {
    up: function (migration, DataTypes, done) {
        migration.createTable('users', {
                id: {
                    type: DataTypes.INTEGER,
                    primaryKey: true,
                    autoIncrement: true
                },
                createdAt: {
                    type: DataTypes.DATE
                },
                updatedAt: {
                    type: DataTypes.DATE
                },
                name: DataTypes.STRING,
                email:  DataTypes.STRING,
                hashedPassword: DataTypes.STRING
            },
            {
                charset: 'utf8'
            });
        done();
    },

    down: function (migration, DataTypes, done) {
        migration.dropTable('users');
        done();
    }
};
```

then I'm a little confused ,  when I'm creating a migration this create the table scheme , but the user model too create the table scheme , what is the right way for working with migrations? , the properties are no longer defined in the model? , 

thanks :)

**Comment by KlonD90** [comment]
It's default fields so you can use at any default model.
You cant try something like this for supress:  http://stackoverflow.com/a/20395054/1406632

**Comment by juliocanares** [comment]
don't understand , my model user is creating the table schema and my migration too , with what I work ? , when I running  the server , 

```javascript
global.db.sequelize.sync({force: true})  // this create all tables defined by models
```

but if I creating the tables by migrations  , still I need create tables by models definition ?

**Comment by KlonD90** [comment]
Sorry.
Use sync only for start or empty database ofc. In other way use sequelize db:migrate.

**Comment by mickhansen** [comment]
@juliocanares if creating tables my migrations you need both a full .createTable statement and a full model statement yes - Unfortuneatly those things do need to be decoupled to provide consistency.

**Comment by juliocanares** [comment]
Thanks , I understand better , ¿ and when I pass to production all changes in the tables schema I need use only migrations and the models would equal to the last migration ?, When I need execute a migration what is recommendable by cli or in code ?, finally when I'm syncing the database I need change force to false ?

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
