### ISSUE TITLE
Postgresql full text and geo distance search with sequelize

### ISSUE THREAD

**Issue by chuks** [sequelize/sequelize#3432]
Hi,
Can anyone point me to a sequelize example for implementing full text search AND geo distance search on postgresql? I currently have a postgresql database, and using the express.js boilerplate example for sequelize, on a new project. I have since resolved all the issues I had with first trying out sequelize. Now I need to implement search, and I'd rather not go through the hassle of setting up Elasticsearch or Sphinxsearch. The project in question is not too complex, so I'd rather keep things simple. If anyone could point me to a full setup showing how to get the full text search on postgresql implemented via sequelize, and also important for my application is geo distance search. Thanks, guys!

PS: I am using the latest versions of postgresql, sequelize and express.js, if that matters.

**Comment by chuks** [comment]
Hi, I was wondering if anyone has any info on the above?

**Comment by mickhansen** [comment]
I don't know of any i'm afraid.

**Comment by BridgeAR** [comment]
Geo distance is not yet implemented but there are a couple of pull requests for it and it seems like it'll be implemented sometime "soon". Related #2839
Full text search is not supported yet either. See #1580

So this should be closed.
