### ISSUE TITLE
instance.reload() ignores 'include' option

### ISSUE THREAD

**Issue by matmar10** [sequelize/sequelize#3433]
From the docs: "Options that are passed on to Model.find"

But the following does not work (see gist):

https://gist.github.com/matmar10/d460f0fdfa6071dbb2c1

``` JavaScript

// this works
User.findOne({
  include: [{ as: 'roles', model: UserRole }],
  where: { id: 1 }
}).then(function (user) {
  // has `roles` property OK
  console.log(user);
});

// this does not work
User.findOne({
  where: { id: 1 }
}).then(function (user) {
  user.reload({
    include: [{ as: 'roles', model: UserRole }]
  }).then(function (user) {
    // does NOT have `roles` property
    console.log(user);
  });
});
```

**Comment by grabbou** [comment]
Yeah, does not work. Have exactly the same issue right now in my project.

**Comment by mickhansen** [comment]
@grabbou `reload` attempts to reload with the same options as it was built with (from find, generally).

**Comment by grabbou** [comment]
Maybe worth including in method description? I am pretty sure I've seen somewhere a table/sentence showing that options passed to a finder are these with `where, limit, include` and so on, not these with `raw` etc.

**Comment by matmar10** [comment]
Shouldn't it try to merge the options passed to reload? Something like:

```JavaScript
Instance.prototype.reload = function(options) {
     return this.Model.find({
           where: where,
           limit: 1,
           include: merge(options.include || this.options.include || null)
     }, options).then(function(reload) {
           self.set(reload.dataValues, {raw: true, reset: true});
     }).return(self);
}
```

**Comment by mickhansen** [comment]
@matmar10 That would likely be saner yes :)
PR welcome.

**Comment by matmar10** [comment]
@mickhansen  OK, I'll modify and create a test to validate and submit a PR.

**Comment by mickhansen** [comment]
@matmar10 That would be highly appreciated :)

**Comment by BridgeAR** [comment]
Ping @matmar10

**Comment by grabbou** [comment]
Will send a PR in a couple of days if @matmar10 is still busy :)

**Comment by matmar10** [comment]
Having trouble getting this to work. I don't understand the complex code around merging the options. Here's what I have so far (no effect): 

diff --git a/lib/instance.js b/lib/instance.js
index 5668513..688f286 100644
--- a/lib/instance.js
+++ b/lib/instance.js
@@ -737,6 +737,7 @@ module.exports = (function() {
   *
   * @see {Model#find}
   * @param {Object} [options] Options that are passed on to `Model.find`
+  * @param {Array} [options.include] List of joined models to include. If no include option is provided, uses the include option provided to instance in previous `Model.find`
   * @return {Promise<this>}
   */
   Instance.prototype.reload = function(options) {
@@ -744,12 +745,13 @@ module.exports = (function() {
       , where = [
         this.QueryInterface.quoteTable(this.Model.name) + '.' + this.QueryInterface.quoteIdentifier(this.Model.primaryKeyField) + '=?',
         this.get(this.Model.primaryKeyAttribute, {raw: true})
-      ];
+      ]
+      , include = (options) ? options.include || null : this.options.include || null;
 
     return this.Model.find({
       where: where,
       limit: 1,
-      include: this.options.include || null
+      include: include
     }, options).then(function(reload) {
       self.set(reload.dataValues, {raw: true, reset: true});
     }).return(self);
diff --git a/test/integration/instance.test.js b/test/integration/instance.test.js
index 6c16bb4..8d40730 100644
--- a/test/integration/instance.test.js
+++ b/test/integration/instance.test.js
@@ -597,6 +597,33 @@ describe(Support.getTestDialectTeaser('Instance'), function() {
         });
       });
     });
+
+    it('should honor include options specified during reload', function() {
+      var Book = this.sequelize.define('Book', { title: DataTypes.STRING })
+        , Page = this.sequelize.define('Page', { content: DataTypes.TEXT });
+
+      Book.hasMany(Page);
+      Page.belongsTo(Book);
+
+      return Book.sync({force: true}).then(function() {
+        return Page.sync({force: true}).then(function() {
+          return Book.create({ title: 'A very old book' }).then(function(book) {
+            return Page.create({ content: 'om nom nom' }).then(function(page) {
+              return book.setPages([page]).then(function() {
+                return Book.find({
+                  where: { id: book.id }
+                }).then(function(leBook) {
+                  return leBook.reload({ include: [{ model: Page }] }).then(function(leBook) {
+                    expect(leBook.Pages.length).to.equal(1);
+                    expect(leBook.Pages[0].content).to.equal('om nom nom');
+                  });
+                });
+              });
+            });
+          });
+        });
+      });
+    });
   });
 
   describe('default values', function() {

**Comment by drunkhacker** [comment]
@matmar10 is this done yet? I had a same issue now, and wait your PR. It would be nice update `this.options` with `options` only if `options` have new or updated values.

**Comment by drunkhacker** [comment]
@mickhansen is it okay to overwrite `this.options` with `options`?
I'm planning to use `_.assign` e.g., 
```
Instance.prototype.reload = function(options) {
  ... 
  this.options = _.assign this.options, options
  ...
}
```

**Comment by mickhansen** [comment]
@drunkhacker that's probably too simplistic, includes will probably have to be concated.

**Comment by carlitux** [comment]
this also dows not use attributes to reload

**Comment by BillBrower** [comment]
Is this still an issue?

**Comment by davesag** [comment]
I just tested this and reload with include works fine.  I believe this ticket can be closed.

**Comment by sfrieson-tm** [comment]
I tested as well, using v3.30.4.  Working well for me!

**Comment by matmar10** [comment]
Confirmed this is working fine for me too now. Nice work gang!
