### ISSUE TITLE
CLS transaction not used.

### ISSUE THREAD

**Issue by mehmetavsar** [sequelize/sequelize#3434]
Hi,

> I've asked [this question](http://stackoverflow.com/questions/29351728/sequelize-cls-transaction-not-used) on SO, but not likely to get an answer. 

I'm trying implement a global transaction for all nested sequelize queries, using continuation local-storage support. I believe I've set namespace to Sequelize.cls correctly, because it works in many places as expected.

When migrating data from SQL server to Postgresql (sequelize models bonded), nested calls do not use the transaction. Code below.

    var Steps = function() {
    
    }
    
    Steps.prototype = {
        constructor:Steps,
        IlIlce : function() {
            var connection = this.dataplex;
            var request = new sql.Request(connection);
            return request.execute('Migrasyon_Il').then(function (recordsets) {
                console.log('-=-=-=-=' + recordsets[0].length + ' İL kaydı bulundu');
                return Promise.reduce(recordsets[0], function (total, row) {
                    return app.Sql.models.Il.create({
                        _Isim: row.AD,
                        _Entegrasyon: row.IL
                    });
                }, 0);
            }).then(function (total) {
                return total;
            }).catch(function (cause) {
                throw cause;
            });
        }
        Step2 : function() {},
        Step3 : function() {},
        Step4 : function() {},
    }

I've split migration steps into the the object prototype above. It is called in PostgreSQL/Sequelize transaction as below:

    module.exports = {
        run: function() {
            var steps = new Steps();
            steps.dataplex = new sql.Connection(config);
            ...
       
            return steps.dataplex.connect().then(function() {
                // app.Sql => Sequelize instance.
                return app.Sql.transaction(function () { // <-- wrapper transaction
                    return Promise.delay(1).then(function() {
                        return steps.IlIlce();
                    }).then(function () {
                        return steps.Step2();
                    }).then(function () {
                        return steps.Step3();
                    }).then(function () {
                        return steps.Step4();
                        return true;
                    });
                });
            }).then(function () {
                return true;
            }).catch(function (cause) {
                throw cause;
            }).finally(function() {
                steps.dataplex.close();
            });

None of the Sequelize methods in Steps functions use the wrapper transaction.

I've tried to debug it like:

 - put a console.log() line in
   Transaction.prototype.prepareEnvironment() method, where it sets
   transaction in namespace. it passes.
   
 - defined a beforeCreate() hook in Il model definition, which is used
   in Steps.prototype.IlIlce method. In this method context,
   Sequelize.cls.get('transaction') returns undefined.

**Comment by janmeier** [comment]
Try checking the value of `cls.get` before and after `request.execute` - perhaps that async call is loosing the CLS context somehow

**Comment by mehmetavsar** [comment]
Right guess @janmeier .
Sequelize.cls exists but .get('transaction') returns undefined after that line.
I've tried both promise and callback style of execute method, both clears.

It doesn't make any sense how it manages to clear that. mssql package does not implement cls, and even if it did, namespace is there to protect its domain.

I'm copying it as an mssql issue. Will inform you about the news.

**Comment by janmeier** [comment]
That is indeed weird - especilly since we use CLS with the mssql in sequelize. But perhaps them using a different promise package means that context is not carried properly ...

**Comment by mehmetavsar** [comment]
@janmeier What would you expect in this case, to run the `COMMIT;` statement in or out of transaction?

**Comment by mehmetavsar** [comment]
I've solved it with replacing transaction() and  connect() methods. First open the transaction on Sequelize, then connect thru mssql. Now all nested queries use the transaction.
