### ISSUE TITLE
Has the TEXT datafield really unlimited length?

### ISSUE THREAD

**Issue by moatazelmasry2** [sequelize/sequelize#3435]
Hi all,

I wanted in my sql to create a text field with a large length
The documentation is mentioning that the TEXT field datatype has unlimited length. But in mysql dialect it builds a query with the data type TEXT which has a length of 64kb. 
further I couldn'd figure out how in sequelize can I create  TEXT('medium') or TEXT('long') as I'd do with BLOB object

**Comment by mickhansen** [comment]
That's not supported with data type objects currently i'm afraid.
But you can use a literal string, `"TEXT('medium')"`

**Comment by sushantdhiman** [comment]
Implemented in https://github.com/sequelize/sequelize/pull/3836
