### ISSUE TITLE
Sequelize returns strings instead of a decimal for DataTypes.DECIMAL 

### ISSUE THREAD

**Issue by nodu** [sequelize/sequelize#3437]
I’m running into an issue where Sequelize is returning strings instead of a decimal for DataTypes.DECIMAL when .get() is called to return the values.

Any one have suggestions on how to fix?

**Comment by mickhansen** [comment]
This is something node-postgres does. https://github.com/brianc/node-pg-parse-float https://github.com/brianc/node-postgres/pull/271

**Comment by nodu** [comment]
Thank you Mick, just what I needed.

**Comment by miguelYOGOME** [comment]
I have the same problem with mySql ...

**Comment by miguelYOGOME** [comment]
I have the same problem with mySql ...
any suggestion ??

Thanks ...
