### ISSUE TITLE
using Postgres, on version 2.0.5, cannot create new record

### ISSUE THREAD

**Issue by georgearrowwood** [sequelize/sequelize#3438]
on version 2.0.5 was trying to create new record, using postgres database , 

{ username: 'somename',
      email: "mail@mail.com",
      date_of_birth: '1995-06-13' 
    }; 

db.User.create(user_d);

but failed to do so

this is my model:
```js
var User =  sequelize.define('User', {
    
    username: DataTypes.STRING, 
    date_of_birth: DataTypes.DATE,
    email: DataTypes.STRING,
    password: DataTypes.STRING,

    created_time: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: DataTypes.NOW
    },
    updated_time: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: DataTypes.NOW
    }
  }, {    
      createdAt: 'created_time',
      updatedAt: 'updated_time',
      tableName: 'users',
      underscored: true,
      freezeTableName: true,
      force: false
  });
```

the problem that, sequels generates such query:

```sql
INSERT INTO "users" ("id","username","date_of_birth","email","created_time","updated_time") VALUES (DEFAULT,'somename','1995-06-13 00:00:00.000 +00:00','mail@mail.com','2015-03-31 17:23:39.000 +00:00',`key` = 'NOW') RETURNING *;
```

Problem is obviously in the last value for field "updated_time" is "  `key` = 'NOW' " but should be just " NOW ".

if i downgrade back to version 2.0.0 there is no such issue, its working fine.

**Comment by janmeier** [comment]
A temporary fix for this would probably be to change defaultvalue to `new DateTypes.NOW()`

**Comment by georgearrowwood** [comment]
no it didn't change anything
