### ISSUE TITLE
changed() returns false if nothing has changed

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3447]
The documentation on `changed()` says:

If changed is called with a string it will return a boolean indicating whether the value of that key in dataValues is different from the value in _previousDataValues.

If changed is called without an argument, it will return an array of keys that have changed.

But I noticed that if I call `changed()` with no arguments when no field has changed, Sequelize will return `false` instead of an empty array.

**Comment by mickhansen** [comment]
That is as intended. Guess it needs to be made clearer in the docs.
