### ISSUE TITLE
How to create/update other models from inside a hook?

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3448]
How can I access any other models from inside a hook? The other models may not necessarily be associated with the current model (ie, update a logging table)

ie, in user model:

```
Item.beforeUpdate(function(item, options, fn) {
  models.otherModel.create(name: item.name);   // `models is not defined`
});
```

**Comment by mickhansen** [comment]
That depends on how you've implemented access to your models.
If you've attached them to sequelize just access them through sequelize.
