### ISSUE TITLE
Usage of NEXT in find is not supported SQL server 2008

### ISSUE THREAD

**Issue by kiddkevin00** [sequelize/sequelize#3451]
When I try the find method on a string based column using where clause, I get a result of the following:

```
Executing (default): SELECT [UserID], [UserCreateDate], [UserCreateIP], [UserModifyDate], [UserModifyIP], [UserDeleted], [UserReset], [UserEmail], [UserPassword], [UserName], [UserAdmin], [Participant
ID], [UserIsEmployee] FROM [Users] AS [Users] WHERE [Users].[UserEmail] = 'a' ORDER BY [UserID] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
```

This is the code for my find method: 

```
models.Users.find({
 where:{
  UserEmail: "b"
 },
}).then(function(projects) {
 console.log(projects)
}).catch(function(error){
 console.log(error);
});
```

It looks like it is adding offset, order by, and fetch, but I didn't specify those. For what I know this is not compatible with Microsoft SQL Server  2008, which is what I am using. Correct me when I am wrong.
Any information will be appreciated.

**Comment by SteveyPugs** [comment]
Currently the only way I found with @kiddkevin00 to get around that is to set the limit to null in the find method.

**Comment by janmeier** [comment]
Find is for a single record, thus the limit 1. Use findAll / all for multiple records

**Comment by SteveyPugs** [comment]
We know that, we are using this method to find the one record. The issue is searching on strings in the where clause. If we search by integer all is fine, it never adds the offset, if we search by string thats the result.

**Comment by SteveyPugs** [comment]
Another note. If we search for a string record that's not that there, it shouldn't return null, but it results in the above as well.

**Comment by itsravenous** [comment]
I've written a helper method to make working with this easier - might be useful to some.

```javascript
var Promise = require('bluebird');

function findOne2008(model, options) {
	var p = new Promise(function (resolve, reject) {
		model.findAll(options).then(function (records) {
			if (records.length) {
				resolve(records[0]);
			} else {
				reject();
			}
		}, reject);
	}.bind(this));

	return p;
}
```

**Comment by kiddkevin00** [comment]
@itsravenous Thanks for the suggestion, but it still needs to spend extra IO in Database to grab all the rows, which seems a bit wasted. Any other suggestion? Thanks in advance.

**Comment by itsravenous** [comment]
Correct - it is inefficient. However, all solutions I can find for `LIMIT/FETCH NEXT` for 2008 in general seem to suggest using a sub query which creates a RowNumber parameter using ROW_NUMBER() to select against for limiting/pagination. From [Stackoverflow](http://stackoverflow.com/a/2135449/4887407):

```
WITH Results_CTE AS
(
    SELECT
        Col1, Col2, ...,
        ROW_NUMBER() OVER (ORDER BY SortCol1, SortCol2, ...) AS RowNum
    FROM Table
    WHERE <whatever>
)
SELECT *
FROM Results_CTE
WHERE RowNum >= @Offset
AND RowNum < @Offset + @Limit
```

To me this seems to suggest that there is no efficient way to do limiting/pagination in 2008, but that doesn't sound right and I'm not a SQL expert by any measure :)

**Comment by kiddkevin00** [comment]
@Jenkins thanks for your reply. In the previous response, I am assuming you
suggest using raw query, is that correct and is it the only choice for
using sequelize? Appreciate your help.

**Comment by itsravenous** [comment]
Not quite - what I'm saying is that the workaround function I shared (`findOne2008`) is probably not much less efficient than what is possible (whether using an ORM like Sequelize or using raw queries) because 2008 simply does not support limiting/pagination without first fetching the entire record set. As I said, I'm by no means an expert, and this is just what it looks like to me - I would love someone to prove me wrong as it would make my life easier too :)

**Comment by kiddkevin00** [comment]
@itsravenous Cuz the way we get around this so far is set the `limit` to `null` or `0`. But, do you know why this can work?
