### ISSUE TITLE
Saving with emtpy object bypass validation rule

### ISSUE THREAD

**Issue by digitalysin** [sequelize/sequelize#3453]
say i have this category model

var Category = sequelize.define('categories', {
  name: {
    type: Sequelize.STRING,
    validate: {
      notNull: true,
      notEmpty: true
  }
})

// when i run this code
Category.create().then(function() { console.log('success'))
// or
Category.create({}).then(function() { console.log('success'))

// it still save to database

**Comment by mickhansen** [comment]
You need `allowNull: false` on the schema. The `notNull` validator no longer exists.

**Comment by mickhansen** [comment]
```js
var Category = sequelize.define('categories', {
  name: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      notEmpty: true
    }
})
```

**Comment by digitalysin** [comment]
thanks
