### ISSUE TITLE
changed() for ARRAY type is always true.

### ISSUE THREAD

**Issue by maplesap** [sequelize/sequelize#3454]
I have a field which is `mylist = { type: DataTypes.ARRAY(DataTypes.STRING) }`.

In my `beforeUpdate` hook, `changed()` always returns `['mylist']` even if the values haven't changed.

**Comment by BridgeAR** [comment]
This should be fixed in version 2.1 130cd9a00f2b1c3d7b3a093532e5eb5335e31a23
Ping @mickhansen
