### ISSUE TITLE
unexpected behavior from adding duplicate association

### ISSUE THREAD

**Issue by ryanmeador** [sequelize/sequelize#3455]
I have two models, Staff and Position, that have a bidirectional belongsToMany association through the StaffPosition table (I've also created a model for this table).  If I have instances of these two models, `staff` and `position`, and I call `staff.addPosition(position)`, the first time it returns an instance of StaffPosition.  However, subsequent times I try to add this same exact association, it returns an array consisting of a single element, which looks like this: `[ 1 ]`.  I believe that is because it's updating the existing relationship (as it should) but it's returning the number of rows updated, instead of the StaffPosition object.  This means I need special code in my `then()` to handle the two different cases.  Is this behavior intended, or should it actually return a StaffPosition both times?

**Comment by mickhansen** [comment]
Likely not intended. Although it would be great for adders to also tell you whether or not this was an update or create.

**Comment by mansa-dev** [comment]
I have exact same issue.

This is my association code

`Mo.belongsToMany(db.Me, {through: { model: db.MM, unique: false }, foreignKey: 'mo_id'});`
`Me.belongsToMany(Mo, {through: { model: db.MM, unique: false }, foreignKey: 'me_id', unique: false});`

Intially there are no junction table records so I can add multiple `Mo` <--> `Me` records using this code

`mo`
`.addMes([me_id], MMJson)`
` .then(function(){`
`     console.log(arguments);`
`     deffered.resolve();`
`});`

When I am adding the records for first time, I get junction table `MM` object in `console`. I can link any number record with same `<Me_id, Mo_id>` at that time. I think its depending upon same transaction ?

Now I have some records in `MM` junction for a `<Me_id, Mo_id>` pair. I try to add more record with same  `<Me_id, Mo_id>` pair I get result like `[ [ 2 ] ] `;
