### ISSUE TITLE
[question] Hooks on Sequelize

### ISSUE THREAD

**Issue by sebay00** [sequelize/sequelize#3456]
Hi there,

I'm getting some troubles about Hooks. 
I've tried 2 hooks, afterUpdate and afterValidate.

I have a hook declared on my user model : 
```
  hooks: {
    afterUpdate: someFunction
  }

// Later

function someFunction(user, opts, next)
{
     //Handle new values of user
}
```

The function is never called on `User.update()`, whereas my model is updated.

I tried with afterValidate too, and it seems to work better. At least it's called by the User.update().
But only changed attributes are reachables in the hook function.

**Comment by janmeier** [comment]
Which hook are you talking about? Please show some actual code. 

Also, please add a more descriptive title

**Comment by mickhansen** [comment]
You need to use `individualHooks: true` for bulk update to run individual hooks.

**Comment by sebay00** [comment]
Yeah.

I think there's a little error in the doc.
`Model.update({username: 'Toni'}, { where: {accessLevel: 0}}, {individualHooks: true})`

It should be `Model.update({username: 'Toni'}, { where: {accessLevel: 0} ,individualHooks: true})`.

It works for me. :+1:

**Comment by mickhansen** [comment]
Ah yes then the docs are indeed a bit outdated since we merged the options.
