### ISSUE TITLE
Order in associations

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3461]
Hi guys , I have 2 models Collection and Work in belongsToMany relation with a table associative CollectionWork.

```javascript
    // Collection model
     var Collection = sequelize.define('Collection', {
            name: DataTypes.STRING
        }, {
            classMethods: {
                associate: function (models) {
                    Collection.belongsToMany(models.Work, {through: models.CollectionWork});
                }
            }
        }
    );

    // Work model
    var Work = sequelize.define('Work', {
            name: DataTypes.STRING,
        }, {
            classMethods: {
                associate: function (models) {
                    Work.belongsToMany(models.Collection, {through: models.CollectionWork});
                }
            }
        }
    );

    // CollectionWork model
    var CollectionWork = sequelize.define('CollectionWork', {
            order: {type: DataTypes.INTEGER, defaultValue: 1}
        }
    );

```
Then I need order by order of CollectionWork

I'm trying with this
```javascript
     var query = {
                where: {id: collection.id},
                include: [{
                    model: global.db.Work,
                    through: {order: '`order` DESC'}
                }]
      };

     global.db.Collection.findAll(query).then(function (collection) {
          return res.json(collection);
      });
```

but dont work what is the right way for order in association ?

**Comment by calvintwr** [comment]
Here you go: http://sequelize.readthedocs.org/en/latest/docs/models/#ordering-eager-loaded-associations

Can you try:
     var query = {
                where: {id: collection.id},
                include: [{
                    model: global.db.Work
                }],
                order: [ [ db.Collection, db.CollectionWork, 'order', 'DESC' ] ]
      };

You can change 'DESC' to 'ASC' if that's your intent.

**Comment by calvintwr** [comment]
And you should probably use stackoverflow for such issues in the future. You should receive response there much quicker.

**Comment by juliocanares** [comment]
thanks :dancer:
