### ISSUE TITLE
Unique violation returns path property surrounded by quotes

### ISSUE THREAD

**Issue by falmp** [sequelize/sequelize#3464]
When there's a unique violation, the `ValidationErrorItem` is:

```js
{ message: '"quoteId" must be unique',
     type: 'unique violation',
     path: '"quoteId"',
     value: '24902467' }
```

I suppose that's an error?

**Comment by mickhansen** [comment]
It would make more sense to have it stripped indeed.

**Comment by BridgeAR** [comment]
Do you have a test case for me? The unique validation I used does not escape the path on any dialect...

**Comment by janmeier** [comment]
Closing this one, since @BridgeAR can't reproduce - please comment if you have a test case @falmp

**Comment by mickhansen** [comment]
I'm almost certain i've encountered this a ton of times.

**Comment by falmp** [comment]
I'm currently quite busy with a new born child, but I'll leave this on my TODO list to add a test case when the opportunity kicks in. I'll let you know. :)
