### ISSUE TITLE
renameColumn on SQLite destroys indexes

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3466]
Using renameColumn in a migration appears to resul in all indexes on the table being destroyed.

**Comment by mickhansen** [comment]
@dantman Schema changes in sqlite are done by completely recreating the table, i guess that we don't currently take indexes into account.

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/6205 (with better example)
