### ISSUE TITLE
How do I define a composite unique constraint using a association's foreign key?

### ISSUE THREAD

**Issue by falmp** [sequelize/sequelize#3468]
How do I define a composite unique constraint using a association's foreign key?

From the docs, I have:

```
To get full control over the foreign key column added by sequelize, you can use the foreignKey option. It can either be a string, that specifies the name, or and object type definition,
equivalent to those passed to sequelize.define.
```

My model definition:

```js
module.exports = function(sequelize, DataTypes) {
  var SelectedItem = sequelize.define('SelectedItem', {
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    externalId: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: 'uniqueSelectedItem'
    },
    source: {
      type: DataTypes.ENUM('GOOGLE', 'YAHOO'),
      allowNull: false,
      unique: 'uniqueSelectedItem'
    }
  }, {
    paranoid: true,
    classMethods: {
      associate: function(models) {
        SelectedItem.belongsTo(models.Item, {
          foreignKey: {
            name: 'itemId',
            unique: 'uniqueSelectedItem'
          }
        });
      }
    }
  });

  return SelectedItem;
};
```

From the above definition, I have a composite unique constraint on fields `externalId`, `source` and `itemId` (foreign key for my `SelectedItem.belongsTo(models.Item)` relationship).

But here are the queries executed:

```sql
DROP TABLE IF EXISTS "SelectedItems" CASCADE;
DROP TYPE IF EXISTS "enum_SelectedItems_source";
SELECT t.typname enum_name, array_agg(e.enumlabel) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public'  AND t.typname='enum_SelectedItems_source'  GROUP BY 1
DROP TYPE IF EXISTS "enum_SelectedItems_source"; CREATE TYPE "enum_SelectedItems_source" AS ENUM('GOOGLE', 'YAHOO');
CREATE TABLE IF NOT EXISTS "SelectedItems" ("id"   SERIAL , "name" VARCHAR(255) NOT NULL, "externalId" VARCHAR(255) NOT NULL, "source" "enum_SelectedItems_source" NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE, "itemId" INTEGER REFERENCES "Items" ("id") ON DELETE CASCADE ON UPDATE CASCADE, UNIQUE ("externalId", "source"), PRIMARY KEY ("id"));
```

Am I doing something wrong?

**Comment by janmeier** [comment]
Hmm, yeah we need to re-calculate indices when adding associations it seems

**Comment by janmeier** [comment]
As a temp. solution you could add the itemId could to the model, and in the association do: `SelectedItem.belongsTo(models.Item, { foreignKey: SelectedItem.rawAttributes.itemIt });`

**Comment by mickhansen** [comment]
@janmeier workaround for the time being could be to use `indexes`?

**Comment by janmeier** [comment]
Yep, that'd also work

**Comment by falmp** [comment]
In the end I also needed to add `deletedAt` column to the `UNIQUE` index, so `indexes` worked great. :)

Thanks for the explanation and keep up the great work!

**Comment by thefabulousdev** [comment]
+1

**Comment by janmeier** [comment]
@thefabulousdev Did you try with indexes as mentioned here http://docs.sequelizejs.com/en/latest/docs/models-definition/#indexes?

**Comment by thefabulousdev** [comment]
I did not, thanks @janmeier !

**Comment by janmeier** [comment]
This is also fixed on latest master :)

**Comment by kenjitayama** [comment]
@falmp 
I have the same requirements (composite unique key for foreign keys + deletedAt) and I am wondering if you didn't run into a problem regarding deletedAt.
NULL does not violate unique constraint(at least in MySQL), so something like the following would run multiple times without error.

```
INSERT INTO SelectedItem
(name, externalId, source, deletedAt, itemId) VALUES
('Item1', 'ITEM01', 'GOOGLE', NULL, 1);
```

Or are you using a value other than NULL for non-deleted rows (which I don't know how to accomplish with the paranoid feature) ?

**Comment by mickhansen** [comment]
@kenjitayama `NULL` is technically not any kind of value and thus is unmatchable. You should be able to set the default value for deletedAt to `0`.

**Comment by kenjitayama** [comment]
@mickhansen 
Thanks for your help!

I have `paranoid: true` in my model definition, and `deletedAt` is generated automatically.
How should I set `defaultValue` of `deletedAt` to `0`?

I added the following (in addition to `paranoid: true`), and the created table looked ok (`0` was converted to `0000-00-00 00:00:00`).

```
deletedAt: {
  type: Sequelize.DATE,
  unique: 'compositeUniqueKey',
  defaultValue: 0
},
```

But `find` functions kept running queries with `deletedAt IS NULL`.
Can the `paranoid` feature be used with `deletedAt` column having a default value other than `NULL` ?

**Comment by mickhansen** [comment]
@kenjitayama Hmm yeah that's an issue obviosuly. Unfortuneatly it's not really a public method: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L121. But you could implement a beforeFind hook that sets it to `{$ne: 0}`, then paranoid shouldn't override it AFAIR

**Comment by kenjitayama** [comment]
@mickhansen I made a new issue for this :)

**Comment by OKNoah** [comment]
This bug still seems present in `3.23.3`. I can set a unique composite with the `indexes` option, but not just by using a string as in the docs. At least when using an association and custom foreignKey (not sure if it fails under other conditions or not).

**Comment by janmeier** [comment]
@OKNoah Please provide a [SSCCE](HTTP://SSCCE.ORG/)

**Comment by dianaflorez** [comment]
I did this and working for me... to postgres

"use strict";

module.exports = function(sequelize, DataTypes) {
  
    var Pais = sequelize.define('pais', {
        id_pais:{
            type: DataTypes.INTEGER,
         #    **primaryKey: true,**
            autoIncrement: true
        },
        codigo_pais: {
            type: DataTypes.STRING(3),
            # **primaryKey: true**
        },
        nombre: {
            type: DataTypes.STRING(50),
            allowNull : false
        },
       "createdAt":{
			type: DataTypes.DATE,
			defaultValue : sequelize.fn('now') 
		},
		"updatedAt":{
			type: DataTypes.DATE,
			defaultValue : sequelize.fn('now') 
		}
    });
  return Pais;
};

//**********************************************
The result in postgres was

-- Table: pais

-- DROP TABLE pais;

CREATE TABLE pais
(
  id_pais serial NOT NULL,
  codigo_pais character varying(3) NOT NULL,
  nombre character varying(50) NOT NULL,
  "createdAt" timestamp with time zone DEFAULT now(),
  "updatedAt" timestamp with time zone DEFAULT now(),
  CONSTRAINT pais_pkey PRIMARY KEY (id_pais, codigo_pais)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE pais
  OWNER TO diana;
