### ISSUE TITLE
Its possible create virtual fields and order ?

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3469]
Hi guys , I need calculate popularity of works , this is calculated by number of likes + views ,

Then I have relations like this:

```javascript
User.belongsToMany(models.Work, {as: 'Likes', through: 'Likes'});
User.belongsToMany(models.Work, {as: 'Views', through: 'Views'});
```

I want when I find all works they be order by popularity , the popularity cannot be an column in the table , because this is calculated by time .

I think that this should be a virtual field , but how I can create a virtual field and assign value ?

```javascript
global.db.Work.findAll({order: '`popularity` DESC'}).then(function(works){
    console.log(works);
});
```

**Comment by mickhansen** [comment]
Virtual fields don't exist in the database hence it would be possible to order on them.
Also there's really no way sequelize could detect the semantics of your virtual field and then produce sql based on that.
You'll have to write the calculation in the order statement aswell.
