### ISSUE TITLE
Model.update() fails to handle unique keys

### ISSUE THREAD

**Issue by johngiudici** [sequelize/sequelize#3474]
`caller.__options` isn't defined in the query handler when using `Model.update()`. Fix incoming...

**Comment by amsanket22** [comment]
I think this issue persists. I have a unique constraint added at db level, and when I update the record it gives me an error, raw query at db works fine, but from sequelize it gives me duplicate entry error.

![Screenshot from 2019-05-14 15-01-02](https://user-images.githubusercontent.com/11029171/57690945-8f063f00-7660-11e9-97ab-7b400278cdb1.png)

Attached is the screenshot

**Comment by jy95** [comment]
Still present in the latest version :( 
@papb Can you reopen this issue ? I got the same bug

**Comment by KhizarNaseer** [comment]
This issue still exists, can anyone please solve it.
