### ISSUE TITLE
Add 'scope' to hasOne/belongsTo

### ISSUE THREAD

**Issue by ackerdev** [sequelize/sequelize#3476]
hasMany and belongsToMany both support `scope` in the options object, it would be great to see this feature added to hasOne/belongsTo associations :smile:

Also, only belongsToMany's `scope` seems to be used in retrieving associations, but it'd be great to see this on the other associations as well.

**Comment by danielking** [comment]
+1

**Comment by StyleT** [comment]
+1

**Comment by akaNightmare** [comment]
+1

**Comment by mickhansen** [comment]
What's the usecase exactly here @ackerdev? belongsTo and hasOne is 1:1 so there's not really anything to filter on with `scope`.

**Comment by ackerdev** [comment]
@mickhansen It's been a long time since I encountered this so I don't remember this perfectly, but I believe it's about the options object when creating the association, not when querying, especially in the case of trying to retrieve a specific record of what is actually a hasMany relation (eg. The most recent created date, or the first via a "sortOrder" attribute).

**Comment by mickhansen** [comment]
@ackerdev but these associations work 1:1 on primary keys, so there wouldn't be multiple records.

**Comment by mickhansen** [comment]
Given it some thought, it definitely makes sense for hasOne as sort of pseudo hasMany (will also be needed for poly).

**Comment by danielking** [comment]
How about this case:

A hasOne B (relatedId = ..., relatedType = 'A')
C hasOne B (relatedId = ..., relatedType = 'C')

foreign key 'relatedId' may get same values when using none-global unique ids.

**Comment by mickhansen** [comment]
@danielking Yeah that's the conclusion i came to aswell, it makes sense if it's actually a hasMany relation but you known there will only be one entry per scope column.

**Comment by mickhansen** [comment]
#5113
