### ISSUE TITLE
Complex inner join

### ISSUE THREAD

**Issue by blanchma** [sequelize/sequelize#3479]
I'm having a hard time to make this query:

SELECT "Firmware"."id", "Firmware"."name", "Firmware"."version", "Firmware"."min_version", "Firmware"."snapshot", "Firmware"."ota_key_s3", "Firmware"."spi_key_s3", "Firmware"."release_notes", "Firmware"."android_link", "Firmware"."ios_link", "Firmware"."created_at", "Firmware"."updated_at", "Firmware"."product_id", "product"."id" AS "product.id", "product"."name" AS "product.name", "product"."product_code" AS "product.product_code", "product"."vendor_id" AS "product.vendor_id", "product"."created_at" AS "product.created_at", "product"."updated_at" AS "product.updated_at" FROM "firmwares" AS "Firmware"  INNER JOIN
    (SELECT product_id, MAX(version) AS MaxVersion
    FROM firmwares
    GROUP BY product_id) groupedVersion 
ON "Firmware"."product_id" = groupedVersion.product_id 
AND "Firmware"."version" = groupedVersion.MaxVersion INNER JOIN "products" AS "product" ON "Firmware"."product_id" = "product"."id" AND "product"."vendor_id" IN (1, 2) WHERE "Firmware"."snapshot" = 'false' ORDER BY "Firmware"."version" DESC LIMIT 10;

Work inside this:

          Firmware.findAndCountAll({limit: query.limit, offset: query.offset, where: whereClause,
                                    include: [ { model: allModels.Product, as: 'product', where: {vendor_id: userVendorsId} } ], order: [['version', 'DESC']] }).on("sql",console.log).then(function(result) {

The only missing part in this code is the inner join of "groupedVersion". Is there any way to do this query with rawsql but getting a sequelizeInstance (instead of just an object as sequelize.query returns)?

**Comment by mickhansen** [comment]
You can use the callee option on query to map to a model: http://sequelize.readthedocs.org/en/latest/api/sequelize/#querysql-callee-options-promise
However it likely won't map to nested instances, but start out by trying that.
