### ISSUE TITLE
Eager loading for many to many associations

### ISSUE THREAD

**Issue by chuks** [sequelize/sequelize#3480]
Hi,
I've been trying to wrap my head around eager loading, mostly on many to many associations. Here are two example models:

User.js
var definition = require(__dirname + '/./../utils/models/definitions/UserDefs.js').definition;
module.exports = function(sequelize, DataTypes) {
    console.log("user model - definition is: "+definition);
    var User = sequelize.define('User', definition, {
        classMethods: {
            associate: function(models) {
                console.log("User - I am in associate. models.User: "+models.User);

                User.belongsToMany(models.Recommendation, {
                    foreignKey: 'Recommendation_id',
                    unique:     false,
                    through:    'UserRecommendations',
                    as:         'recommendationsToOthers'
                });

                User.belongsToMany(models.Recommendation, {
                    foreignKey: 'Recommendation_id',
                    unique:     false,
                    through:    'User_Recommendation',
                    as:         'recommendationsFromOthers'
                });
           }
        },
        freezeTableName: true,
        tableName: 'users'
    });

  return User;
};

Recommendation.js
var definition = require(__dirname + '/./../utils/models/definitions/RecommendationDefs.js').definition;

module.exports = function(sequelize, DataTypes) {
    console.log("Recommendation model - definition is: "+definition);

    var Recommendation = sequelize.define('Recommendation', definition, {
        classMethods: {
            associate: function(models) {
                console.log("Recommendation - I am in associate. models.Recommendation: "+models.Recommendation);

                Recommendation.belongsToMany(models.User, {
                    //foreignKey: 'User_id',
                    //unique:     false,
                    through:    'UserRecommendations',
                    as:         'recommendationOwner'
                });

                Recommendation.belongsToMany(models.User, {
                    foreignKey:     'User_id',
                    constraints:    false,
                    through:        'User_Recommendation',
                    unique:         false,
                    as:             'recommendee'
                });

                Recommendation.hasOne(models.Book, {
                    foreignKey: 'Book_id',
                    unique:     false,
                    as:         'recommendedBook'
                });

            }
        },
        freezeTableName: true,
        tableName: 'recommendations'
    });

  return Recommendation;
};

Book.js
var definition = require(__dirname + '/./../utils/models/definitions/BookDefs.js').definition;

module.exports = function(sequelize, DataTypes) {
    console.log("Book model - definition is: "+definition);

    var Book = sequelize.define('Book', definition, {
        classMethods: {
            associate: function(models) {
                console.log("Book - I am in associate. ");

                Book.belongsToMany(models.User, {
                    //foreignKey: 'User_id',
                    through:    'UserBooks',
                    unique:     false,
                    as:         'associatedBookUsers',
                });

                Book.belongsToMany(models.Recommendation, {
                    foreignKey: 'Recommendation_id',
                    unique:     false,
                    through:    'BookRecommendations',
                    as:         'associatedBookRecommendations',
                });

            }
        },
        freezeTableName: true,
        tableName: 'books'
    });

  return Book;
};

..now, in my controller, I do this (this is quite long, I am putting in lots of console logs) --also, inoutObj is just an object of key/values pairs. This works just ok. I can see the correct associations, when I do a Recommendation.findAll(). However, when I try to eager load it from User model, I get empty arrays  on recommendation. Why is this? I try to eager load with the following include, passed to User.find

            { model: Recommendation, as: 'recommendationsToOthers',
                include: [
                    { model: User, as: 'recommendee', attributes: userAttributes},
                    { model: Book, as: 'recommendedBook'},
                ],
                attributes: recommendationAttributes
            },
            { model: Recommendation, as: 'recommendationsFromOthers',
                include: [
                    { model: User, as: 'recommendationOwner', attributes: userAttributes},
                    { model: Book, as: 'recommendedBook'},
                ],
                attributes: recommendationAttributes
            },

, but the above code gives me empty arrays for recommendationsFromOthers and recommendationsToOthers. Can anyone help me with this? The controller that associates the Users to the recommendation models us as below. Again, this works in that when I do a Recommendation.findAll(), I can see all the correct associations with User models. The part not working is trying to eager load the recommendation from the User models. 

----------------------------
Recommendation.create(inputObj).then(function(recommendation){
    	console.log("recommendationController: successfully created recommendation");

        Book.find({where: {id: bookid}}).then(function(book){

            if (book){
                console.log("recommendationController: successfully retrieved book");

                recommendation.setRecommendedBook(book).then(function(recommendedBook){

                    if (recommendedBook){
                        console.log("recommendationController: createRecommendation - successfully added book association");

                        User.find({where: {id: fromid}}).then(function(owner){

                            if (owner){
                                console.log("recommendationController: successfully retrieved fromUser");

                                User.find({where: {id: toid}}).then(function(toUser){

                                    if (toUser){
                                        console.log("recommendationController: successfully retrieved toUser");

                                        recommendation.addRecommendee(toUser).then(function(userRecommendedTo){

                                            if (userRecommendedTo){
                                                console.log("recommendationController: successfully created recommended touser association");

                                                recommendation.addRecommendationOwner(owner).then(function(userRecommendations){
                                                    if (userRecommendations){
                                                        console.log("recommendationController: successfully added recommender association");

                                                        Recommendation.find({where: {id: recommendation.id},

                                                            include: [
                                                                { model: User, as: 'recommendationOwner', attributes: userAttributes},
                                                                { model: User, as: 'recommendee', attributes: userAttributes},
                                                                { model: Book, as: 'recommendedBook'},
                                                            ],
                                                            attributes: recAttributes

                                                        }).then(function(savedRecommedation){
                                                            if (savedRecommedation){
                                                                console.log("recommendationController - successfully retrieved recommendation...");

                                                                var msg  = 'success';
                                                                var data = {msg: msg, data: savedRecommedation};
                                                                sendData(200,data);
                                                            }
                                                            else{
                                                                console.log("recommendationController - problems retrieving recommendation...");

                                                                var msg  = "Error recommending book to user";
                                                                var data = {status: 500, msg: msg, data: null};
                                                                sendData(500,data);
                                                            }

                                                        }).catch(function(error){
                                                            console.log("recommendationController: error is - " + error);
                                                            
                                                            var data = {status: 500, msg: error.message, data: null};
                                                            sendData(500,data);
                                                        });

                                                    }
                                                    else{
                                                        console.log("recommendationController: could not add recommedation");

                                                        var msg  = "Error recommending book to user";
                                                        var data = {status: 500, msg: msg, data: null};
                                                        sendData(500,data);
                                                    }

                                                }).catch(function(error){
                                                    console.log("recommendationController: error is - " + error);
                                                    
                                                    var data = {status: 500, msg: error.message, data: null};
                                                    sendData(500,data);
                                                });
                                            }
                                            else{
                                                console.log("recommendationController: error recommending to user");

                                                var msg  = "Error recommending to user";
                                                var data = {status: 500, msg: msg, data: null};
                                                sendData(500,data);
                                            }

                                        }).catch(function(error){
                                            console.log("recommendationController: error is - " + error);
                                            
                                            var data = {status: 500, msg: error.message, data: null};
                                            sendData(500,data);
                                        });
                                    }
                                    else{
                                        console.log("recommendationController: did not retrieve toUser");

                                        var msg  = "Did not find user to recommend to";
                                        var data = {status: 404, msg: msg, data: null};
                                        sendData(404,data);
                                    }

                                }).catch(function(error){
                                    console.log("recommendationController: error is - " + error);
                                    
                                    var data = {status: 500, msg: error.message, data: null};
                                    sendData(500,data);
                                });
                            }
                            else{
                                console.log("recommendationController: did not retrieve fromUser");

                                var msg  = "User not found";
                                var data = {status: 404, msg: msg, data: null};
                                sendData(404,data);
                            }

                        }).catch(function(error){
                            console.log("recommendationController: error is - " + error);
                            
                            var data = {status: 500, msg: error.message, data: null};
                            sendData(500,data);
                        });

                    }
                    else{
                        console.log("recommendationController: createRecommendation - error adding book association");

                        var msg  = "Error adding recommending book...";
                        var data = {status: 500, msg: msg, data: null};
                        sendData(500,data);
                    }

                }).catch(function(error){
                    console.log("recommendationController: error is - " + error);
                            
                    var data = {status: 500, msg: error.message, data: null};
                    sendData(500,data);
                });

            }
            else{
                console.log("recommendationController: did not find book");

                var msg  = "Did not find book";
                var data = {status: 404, msg: msg, data: null};
                sendData(404,data);
            }

        }).catch(function(error){
            console.log("recommendationController: error is - " + error);
                    
            var data = {status: 500, msg: error.message, data: null};
            sendData(500,data);
        });
        
    }).catch(function(error){
        console.log("recommendationController: error is - " + error);
        
        var data = {status: 500, msg: error.message, data: null};
        sendData(500,data);
    });

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
