### ISSUE TITLE
Sequelize 2.0.5 Included model's toJSON is not getting called.

### ISSUE THREAD

**Issue by billxinli** [sequelize/sequelize#3484]
I have a model Project, and a model User, User has many Projects, and Project belongs_to User.

I have a `toJSON` on my User model to remove the password hash, however when I load User via an association, I see that `toJSON` has not been called, as I still see the password Hash.

**Comment by mickhansen** [comment]
`toJSON()` calls `get({plain: true})` internally which iterates through all includes and calls `get({plain: true})`.

You'll likely have to override toJSON at the top level too achieve the semantics you want, or just use something like https://github.com/mickhansen/ssacl-attribute-roles to hide the password field.
