### ISSUE TITLE
MySql table name capitalization cause problems on linux

### ISSUE THREAD

**Issue by hippich** [sequelize/sequelize#3487]
I have a problem where after sequelize.sync({ force: true }) created tables has original Capitalized case, but when I am trying to store record via record.save() it runs query which uses all lowercase table name.

At the very least, on linux with default configuration this causes problem, since table `Clients` != `clients`. I can manually create tables, but sounds like there should be a better way. Any ideas?

**Comment by janmeier** [comment]
Can you show your model definition + maybe sequelize options. Sounds very weird that the table name in create and in queries should be different

**Comment by hippich** [comment]
Small update/workaround - if I use:

freezeTableName: true,
tableName: 'clients'

This forces same table names during synchronization and in normal usage.

While workaround is fine in my case, this sounds like a bug.

**Comment by hippich** [comment]
One of the models:

```
"use strict";
module.exports = function(sequelize, DataTypes) {
  var Client = sequelize.define("Client", {
    userId       : DataTypes.STRING,
    username     : DataTypes.STRING,
    responses    : DataTypes.BIGINT,
    lastResponse : DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
          Client.hasMany(models.History, { constraints: false });
      }
    }
  });
  return Client;
};
```

config:
```
{
  "development": {
    "dialect"  : "mysql",
    "host"     : "localhost",
    "database" : "client_dev",
    "username" : "root",
    "password" : null
  },
  "test": {
    "dialect": "sqlite",
    "storage": ":memory:"
  },
  "production": {
    "dialect": "sqlite",
    "storage": "db.sqlite3"
  }
}
```

(production is not really used at this time)

**Comment by janmeier** [comment]
Cannot reproduce on latest master. It uses the same table name both on sync and save in my case.

Which version are you on?

Perhaps you can provide a PR with a failing test case?

**Comment by hippich** [comment]
Oh... So silly of me. I was creating some queries manually and these used to work just fine with sqlite... Sorry for a false alarm.  Everything works as it should work! Thank you!
