### ISSUE TITLE
Index name too long in sequelize for PostgreSQL

### ISSUE THREAD

**Issue by hhua** [sequelize/sequelize#3488]
Recently we are trying to create an index with name longer than 63 characters in PostgreSQL with sequelize.

Since the default maximum length for index name in PostgreSQL is 63 characters, the index name will be truncated automatically when you first time creating the database.

The second time you try to sync the database, sequelize will try to create the index name again because the index name expected and previously created index name is different.

Sequelize should check the index name length setting for the targeted database and warn users if their index name is too long.

```
Error! { name: 'SequelizeDatabaseError',
  message: 'relation "xxx" already exists',
  parent:
   { [error: relation "xxx" already exists]
     name: 'error',
     length: 138,
     severity: 'ERROR',
     code: '42P07',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'index.c',
     line: '777',
     routine: 'index_create',
```

**Comment by mickhansen** [comment]
What model definition is creating this index?

**Comment by sushantdhiman** [comment]
Discussion moved to https://github.com/sequelize/sequelize/issues/2084
