### ISSUE TITLE
Order query option with association produces error in mssql dialect

### ISSUE THREAD

**Issue by CommissarXiii** [sequelize/sequelize#3489]
Setting the order option results in an 'Invalid usage of the option NEXT in the FETCH statement' error when including an associated model.

A query such as:
```
models.ModelA.findAndCountAll({
     order: [['createdAt', 'ASC']],
     limit: 25,
     offset: 0,
     include: [
        {model: models.ModelB}
     ]
})
```

Produces two 'Order By' clauses in the the resulting query, similar to ... ORDER BY [ModelA].[createdAt] ASC ORDER BY [id] ...

I've narrowed it down to line 572 of `sequelize/lib/dialects/mssql/query-generator.js`

```
if (!options.order || (options.include && !subQueryOrder.length)) {
          fragment += ' ORDER BY ' + this.quoteIdentifier(model.primaryKeyAttribute);
}
```

I believe this should be something like:

```
if (!options.order || (!options.order && options.include && !subQueryOrder.length)) {
          fragment += ' ORDER BY ' + this.quoteIdentifier(model.primaryKeyAttribute);
}
```

**Comment by alanhoff** [comment]
+1
