### ISSUE TITLE
How do I get back multiple result sets using raw query?

### ISSUE THREAD

**Issue by shakdoesgithub** [sequelize/sequelize#3499]
If I execute a stored proc using the raw query and that returns 3 results sets back, it seems sequelize populates from the first one.

**Comment by janmeier** [comment]
Try upgrading to the latest version - by default .query should return everything.

If that doesn't help, please show some code

**Comment by janmeier** [comment]
Closing, no response

**Comment by aoi-umi** [comment]
i have the save problem
i call like this    
sequelize.query('call proc ....', {

i read the source code
 } else if (this.isCallQuery()) {//match this 
      result = data[0];
...
} else if (this.isRawQuery()) {//but i want to get this
      // MySQL returns row data and metadata (affected rows etc) in a single object - let's standarize it, sorta
      result = [data, data];
    }

**Comment by aoi-umi** [comment]
if i use QueryTypes.SELECT and raw,the result will become a object
for example:
mysql return this:
[ 
  [ TextRow {
      id: 631,...}
  ]
]
and you return this
[ { '0':
     TextRow {
       id: 631,...}
...
]
