### ISSUE TITLE
Change tracking capability for compliance or management requirements.

### ISSUE THREAD

**Issue by Trakkasure** [sequelize/sequelize#35]
Some systems require historical change tracking. When defining, adding a "keepHistory" attribute in the options could automatically create a history table. Additionally, a configurable history length can be used to truncate the history keeping it from going out of control.

When saving an object and it is an update, simply insert into history table (select from current table where id= my object id) then update the existing table with the changed row. This can be done within a transaction to guarantee both actions have been completed.

**Comment by faceleg** [comment]
Hate to resurrect this issue, but was the PR successful?

**Comment by mickhansen** [comment]
@faceleg i don't believe so.

**Comment by janmeier** [comment]
@faceleg The updatedAt column mentioned in the PR still exists, but I've never seen any of the other features mentioned.

However, this should actually be pretty easy to do as a plugin

* Add an afterDefine hook, which defines a `_history` model whenenver a model is defined.
* In the same hook, add an afterCreate / afterUpdate hook to the model, which will insert a new row in the history table, each time a row is updated
* Perhaps also an afterDelete hook?

One problem might be bulk destroy / update. You could fix this by forcing `individualHooks` to true with a `beforeBulkUpdate/Destroy` hook

**Comment by faceleg** [comment]
Thanks @janmeier, I thought about doing that. Although I'd love to create a plugin like this I don't have time at the moment.

I'm going to investigate using this for the time being: https://github.com/2ndQuadrant/audit-trigger

**Comment by faceleg** [comment]
@janmeier would it be appropriate to open an issue "Creation of a revision tracking plugin", that listed requirements and suggested implementation as you have described? 

Anyone looking to get their feet wet in some excellent OSS projects might see this and decide to implemented it. 

Dreams are free

**Comment by janmeier** [comment]
@faceleg Sure, fine by me :)
