### ISSUE TITLE
Limit number of `HasMany` associations?

### ISSUE THREAD

**Issue by Hoverbear** [sequelize/sequelize#3502]
Hello,
I'm seeking to create a `Foo` which may have **up to** 5 associated `Bar`s where `Foo.hasMany(Bar)`. How can I set a limit on number of `Bar`s which `Foo` has?

I've tried:
- A `beforeValidate` hook, which does not run when updating associations.
- Turning `hooks` on via [docs](http://docs.sequelizejs.com/en/latest/api/associations/#hasmanytarget-options), which only applies to `onDelete`.

**Comment by janmeier** [comment]
This is not possible currently.

The best solution would probably be to provide additional hooks and let a plugin handle actually limitng the number of associated

**Comment by Hoverbear** [comment]
How would I create a hook for this though? I see no way to hook into an `foo.addBar()`. I was thinking I could provide an instance method.

**Comment by mickhansen** [comment]
We've talked about adding association hooks but they wouldn't cover cases where people add the foreign key directly vs create/update.

So any foolproof solution would have to use beforeCreate/beforeUpdate (with changed()) in any case.
