### ISSUE TITLE
Docs unclear about mariasql driver for mariadb/mysql dialect

### ISSUE THREAD

**Issue by hnsr** [sequelize/sequelize#3506]
The 'Getting started' part of the docs mention the use of 'mariasql', but I'm not able to get it working. In my project I have installed both the sequelize and mariasql modules, but trying to create a new Sequelize instance using any of mariadb, mysql or mariasql just fails telling me to 'install the mysql package manually'. Is there anything extra I need to do to get mariasql to work? 

The code I (tried) to use is:

```
var Sequelize   = require('sequelize');

//var sequelize = new Sequelize('mariadb://test:foo@localhost/test');
//var sequelize = new Sequelize('mariasql://test:foo@localhost/test');
var sequelize = new Sequelize('mysql://test:foo@localhost/test');
```

**Comment by mickhansen** [comment]
'mariadb' should work. Possibly not with a connection string, try using the parameters + options with dialect: 'mariadb'

**Comment by mickhansen** [comment]
our mariadb support uses the mysql dialect codebase completely so you still need to install the mysql driver, i agree that could be explained way better in the docs.

**Comment by akshay2604** [comment]
I have a mariadb instance on aws. can i use it with sequelize as of now?

**Comment by abdulhannanali** [comment]
@akshay2604 Yes!

**Comment by knoxcard** [comment]
`dialect: mariadb` will be the way to go on the next version release!
