### ISSUE TITLE
Transaction lost somewhere in the promise chain

### ISSUE THREAD

**Issue by mdarveau** [sequelize/sequelize#3509]
Hi,

I have an issue where the transaction (CLS) is "lost" somewhere in the promise chain and I can't figure out why.

Consider the following (CoffeeScript, BTW, is this ok with you or do you want sampled in js?):
```
Promise = require('bluebird')
Sequelize = require('sequelize')
Sequelize.cls = require('continuation-local-storage').createNamespace('sails-sequelize-#{connection.database}')
sequelize = new Sequelize('postgres://postgres:750roger@localhost:5432/test_sequelize', {})
User = sequelize.define('User', firstName: type: Sequelize.STRING)
sequelize.sync(force: true).then ->
  sequelize.transaction (t) ->
    User.create(firstName: 'John').then (user) ->
      someMethod = Promise.method( (param)->
        Promise.try ()->
          if param?
            user.firstName = 'Save #1'
            user.save()
        .then ( res )->
          user.firstName = 'Save #2'
          user.save()
      )
      someMethod("123")
      .then ()->
        user.firstName = 'Save #3'
        user.save()
```

I get the following output:
```
Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("id"   SERIAL , "firstName" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (13a9b770-5338-4ed1-be7a-594d0659107d): START TRANSACTION;
Executing (13a9b770-5338-4ed1-be7a-594d0659107d): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (13a9b770-5338-4ed1-be7a-594d0659107d): SET autocommit = 1;
Executing (13a9b770-5338-4ed1-be7a-594d0659107d): INSERT INTO "Users" ("id","firstName","updatedAt","createdAt") VALUES (DEFAULT,'John','2015-04-10 17:16:48.894 +00:00','2015-04-10 17:16:48.894 +00:00') RETURNING *;
Executing (13a9b770-5338-4ed1-be7a-594d0659107d): UPDATE "Users" SET "firstName"='Save #1',"updatedAt"='2015-04-10 17:16:48.902 +00:00' WHERE "id" = 1
Executing (default): UPDATE "Users" SET "firstName"='Save #2',"updatedAt"='2015-04-10 17:16:48.907 +00:00' WHERE "id" = 1
Executing (default): UPDATE "Users" SET "firstName"='Save #3',"updatedAt"='2015-04-10 17:16:48.916 +00:00' WHERE "id" = 1
Executing (13a9b770-5338-4ed1-be7a-594d0659107d): COMMIT;
```

I don't understand why the second and third update on `User` is made on the `default` transaction instead of `13a9b770-5338-4ed1-be7a-594d0659107d`.

Thank you very much!

**Comment by mdarveau** [comment]
Here is the Javascript version just in case:
```
var Promise, Sequelize, User, sequelize;

Promise = require('bluebird');

Sequelize = require('sequelize');

Sequelize.cls = require('continuation-local-storage').createNamespace('sails-sequelize-#{connection.database}');

sequelize = new Sequelize('postgres://postgres:750roger@localhost:5432/test_sequelize', {});

User = sequelize.define('User', {
  firstName: {
    type: Sequelize.STRING
  }
});

sequelize.sync({
  force: true
}).then(function() {
  return sequelize.transaction(function(t) {
    return User.create({
      firstName: 'John'
    }).then(function(user) {
      var someMethod;
      someMethod = Promise.method(function(param) {
        return Promise["try"](function() {
          if (param != null) {
            user.firstName = 'Save #1';
            return user.save();
          }
        }).then(function(res) {
          user.firstName = 'Save #2';
          return user.save();
        });
      });
      return someMethod("123").then(function() {
        user.firstName = 'Save #3';
        return user.save();
      });
    });
  });
});
```

**Comment by mickhansen** [comment]
Can you try without Promise.method and use Promise.try directly?
Does it work if you cut out Promise.method/try completely? (Would like to know if this is a sequelize or bluebird issue.

**Comment by mdarveau** [comment]
I tried:
```
  sequelize.transaction (t) ->
    User.create(firstName: 'John').then (user) ->
      someMethod = (param)->
        Promise.try ()->
          if param?
            user.firstName = 'Save #1'
            user.save()
        .then ( res )->
          user.firstName = 'Save #2'
          user.save()
      someMethod("123")
      .then ()->
        user.firstName = 'Save #3'
        user.save()
```

And 
```
  sequelize.transaction (t) ->
    User.create(firstName: 'John').then (user) ->
      Promise.try ()->
        user.firstName = 'Save #1'
        user.save()
      .then ( res )->
        user.firstName = 'Save #2'
        user.save()
      .then ()->
        user.firstName = 'Save #3'
        user.save()
```

And even
```
  sequelize.transaction (t) ->
    User.create(firstName: 'John').then (user) ->
      Promise.try ()->
        user.firstName = 'Save #1'
        user.save()
      .then ( res )->
        user.firstName = 'Save #2'
        user.save()
```

And all got the same result. Save 2 and 3 are always on the default transaction.

The simplest repro step I can create is:
```
  sequelize.transaction (t) ->
    User.create(firstName: 'John').then (user) ->
      Promise.try ()->
        return null
      .then ( res )->
        user.firstName = 'Save #2'
        user.save()
```

Output:
```
Executing (1cd6d4a8-c065-4951-9d56-69d238bc1c77): START TRANSACTION;
Executing (1cd6d4a8-c065-4951-9d56-69d238bc1c77): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (1cd6d4a8-c065-4951-9d56-69d238bc1c77): SET autocommit = 1;
Executing (1cd6d4a8-c065-4951-9d56-69d238bc1c77): INSERT INTO "Users" ("id","firstName","updatedAt","createdAt") VALUES (DEFAULT,'John','2015-04-10 19:00:48.938 +00:00','2015-04-10 19:00:48.938 +00:00') RETURNING *;
Executing (default): UPDATE "Users" SET "firstName"='Save #2',"updatedAt"='2015-04-10 19:00:48.947 +00:00' WHERE "id" = 1
Executing (1cd6d4a8-c065-4951-9d56-69d238bc1c77): COMMIT;
```

**Comment by mickhansen** [comment]
Does it work when not using any `Promise` method be it `try`/`method` or otherwise?

**Comment by mickhansen** [comment]
But looks like it might be an issue with `Promise.try` and the CLS implementation we use, @janmeier?

**Comment by mdarveau** [comment]
Yes, 
```
  sequelize.transaction (t) ->
    User.create(firstName: 'John').then (user) ->
      user.firstName = 'Save #1'
      user.save()
      .then ( res )->
        user.firstName = 'Save #2'
        user.save()
```

Works as expected:
```
Executing (0ac6528f-a618-4e70-8889-c3024fc017aa): START TRANSACTION;
Executing (0ac6528f-a618-4e70-8889-c3024fc017aa): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (0ac6528f-a618-4e70-8889-c3024fc017aa): SET autocommit = 1;
Executing (0ac6528f-a618-4e70-8889-c3024fc017aa): INSERT INTO "Users" ("id","firstName","updatedAt","createdAt") VALUES (DEFAULT,'John','2015-04-10 19:36:44.963 +00:00','2015-04-10 19:36:44.963 +00:00') RETURNING *;
Executing (0ac6528f-a618-4e70-8889-c3024fc017aa): UPDATE "Users" SET "firstName"='Save #1',"updatedAt"='2015-04-10 19:36:44.973 +00:00' WHERE "id" = 1
Executing (0ac6528f-a618-4e70-8889-c3024fc017aa): UPDATE "Users" SET "firstName"='Save #2',"updatedAt"='2015-04-10 19:36:44.979 +00:00' WHERE "id" = 1
Executing (0ac6528f-a618-4e70-8889-c3024fc017aa): COMMIT;
```

**Comment by mickhansen** [comment]
@janmeier Our shim is different from https://github.com/TimBeyer/cls-bluebird/blob/master/shim.js - do you know why?

**Comment by janmeier** [comment]
@mickhansen Nope, not sure - `_addCallbacks` is called by `then` so the effect should be the same

**Comment by mickhansen** [comment]
@janmeier But `Promise.try` is the issue here, so patching `then` is likely not enough.

**Comment by janmeier** [comment]
@mickhansen Probably not ...But then we'd probably need to patch all methods on `Promise.prototype` ... 

Perhaps we can look into overriding their [utils.tryCatch](https://github.com/petkaantonov/bluebird/blob/master/src/util.js), which seems to be used for both `try` and `method` - but then again, thats awfully dependent on the bluebird implementation

**Comment by mickhansen** [comment]
Maybe it's worth testing the cls-bluebird shim seperately and then perhaps opening an issue there to see if they have a known fix.

`tryCatch` is used pretty much everywhere indeed.

**Comment by janmeier** [comment]
Yeah, maybe we should test it. The only issue I can see (but it's probably not a big one) is that we'd be patching the global bluebird instance so if a user requires bluebird in their own code that instance is also patched. Probably thats what most users want, but it might give unexpected results for some who are not expecting cls context to be carried over

**Comment by mdarveau** [comment]
"The only issue I can see (but it's probably not a big one) is that we'd be patching the global bluebird instance so if a user requires bluebird in their own code that instance is also patched."

That made me think that maybe I shouldn't be using bluebird directly if I wanted to get transaction propagated. I digged a little bit and realized that Sequelize expose the patched bluebird in "Sequelize.Promise". I tried:

```
Sequelize = require('sequelize')
Sequelize.cls = require('continuation-local-storage').createNamespace('sails-sequelize-#{connection.database}')
sequelize = new Sequelize('postgres://postgres:750roger@localhost:5432/test_sequelize', {})
User = sequelize.define('User', firstName: type: Sequelize.STRING)

sequelize.sync(force: true)
.then ()->
  sequelize.transaction (t) ->
    User.create(firstName: 'John')
    .then (user) ->
      Sequelize.Promise.try ->
        user.firstName = 'Save #1'
        user.save()
      .then ()->
        user.firstName = 'Save #2'
        user.save()
```

And the transaction is not lost anymore:
```
Executing (09f3c7be-6513-4c10-9bbf-57b25844e3f3): START TRANSACTION;
Executing (09f3c7be-6513-4c10-9bbf-57b25844e3f3): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (09f3c7be-6513-4c10-9bbf-57b25844e3f3): SET autocommit = 1;
Executing (09f3c7be-6513-4c10-9bbf-57b25844e3f3): INSERT INTO "Users" ("id","firstName","updatedAt","createdAt") VALUES (DEFAULT,'John','2015-04-13 02:18:37.993 +00:00','2015-04-13 02:18:37.993 +00:00') RETURNING *;
Executing (09f3c7be-6513-4c10-9bbf-57b25844e3f3): UPDATE "Users" SET "firstName"='Save #1',"updatedAt"='2015-04-13 02:18:38.001 +00:00' WHERE "id" = 1
Executing (09f3c7be-6513-4c10-9bbf-57b25844e3f3): UPDATE "Users" SET "firstName"='Save #2',"updatedAt"='2015-04-13 02:18:38.007 +00:00' WHERE "id" = 1
Executing (09f3c7be-6513-4c10-9bbf-57b25844e3f3): COMMIT;
```

"Probably that's what most users want": Well yes! :-)
"but it might give unexpected results for some who are not expecting CLS context to be carried over": Could you simply document that, if CLS is enabled, Sequelize will patch Bluebird using https://github.com/TimBeyer/cls-bluebird? And maybe offer an option to disable this? I don't really see why someone would be surprised to have the CLS context carried over.

What's funny is that I copied the example from http://sequelize.readthedocs.org/en/latest/docs/transactions/:
'''
sequelize.transaction(function (t1) {
  sequelize.transaction(function (t2) {
    // By default queries here will use t2
    return Promise.all([
        User.create({ name: 'Bob' }, { transaction: null });
        User.create({ name: 'Mallory' }, { transaction: t1 });
    ]);
  });
});
'''
And if I add a then after the `Promise.all`, the transaction is also lost. What confused me is that the example uses `Promise` directly so I assume that I needed to require the original `Bluebird` lib directly. If this is not supported (and you don't plan to patch the global bluebird), the example should use `Sequelize.Promise`.

**Comment by janmeier** [comment]
Hmm, appearently I don't understand the bluebird code well enough then :D

I think you are right @mdarveau  that we should simply state clearly that sequelize will patch the global bluebird instance then

**Comment by mickhansen** [comment]
The more surprising case would probably be that it's not carried over to regular bluebird.

**Comment by mickhansen** [comment]
@janmeier Well we only patch our copy of bluebird, there's two in node_modules if differerent versions, if using the exact same version it would probably work out of the box.

**Comment by janmeier** [comment]
Hmm yeah if the user requires a different version of bluebird there is nothing we can do..

**Comment by mdarveau** [comment]
I have opened https://github.com/petkaantonov/bluebird/issues/583 on Bluebird to see if they are open in bundling CLS support directly into the lib.

I the meantime, I used `Sequelize.Promise.try` to workaround the problem.

**Comment by janmeier** [comment]
Thanks for opening that issue @mdarveau - I've subscribed. Even if bluebird doesn't want to patch its not too much work to do it ourselves however :). And once we remove our custom code we can use the cls-bluebird module directly.

I've added on this PR https://github.com/sequelize/sequelize/pull/3265 that we should remember to patch bluebird and mention it in the docs so I'm going to close this issue

**Comment by mdarveau** [comment]
@janmeier, @petkaantonov has a good point. Is there a reason Sequelize uses CLS instead of domains? It seems like it's a perfect fit for transaction handling and it would remove the need for patching.

**Comment by janmeier** [comment]
I was not aware that you could (ab)use `domain.active` in that way :)

I've re-read the original CLS issue https://github.com/joyent/node/pull/5990, and as I see it, there are two main differences between CLS and domains:

1. CLS has namespaces built in - you can still do this with domains, e.g. `domain.active.sequelize.transaction`, but it's not as explicit, and users might override `domain.active.sequelize` unintentionally if they want to store a sequelize instance on the active domain (which would be weird, but it's possible, for example if a multi-tenancy setup where each user has their own DB)
2. There is no way to disable the error handling built into domains:

    > Ie, you can't have a domain that doesn't catch errors, and they shadow one another, so if the user is using domains in their app, it blocks the trace from working
    https://github.com/joyent/node/pull/5990#issuecomment-22143258

    I realize this might be kind of a moot argument since you really should be using domains to catch errors anyway, but still ...
