### ISSUE TITLE
Request: Notification of unique association exists already.

### ISSUE THREAD

**Issue by Hoverbear** [sequelize/sequelize#3511]
Regarding #3510.

There is currently only an undocumented, unofficial way to detect if an association already exists when attempting to add one. Given that this has useful applications it would be good for there to be an official way.

**Comment by mickhansen** [comment]
I propose we add an option to 1:M and N:M association adders that will throw if exists.
Taking naming suggestions, since all i have right now is `throwIfExists` which does not read that well imo.

**Comment by Hoverbear** [comment]
`AssociationExists`

**Comment by mickhansen** [comment]
Yes that could work as an exception name, but we need an option for the method to trigger that exception :)

**Comment by Hoverbear** [comment]
Ah, `throwIfPresent()` or `throwIfExists()`

**Comment by Hoverbear** [comment]
It looks like [this](https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L423-L439) is the relevant code where this would be changed?

**Comment by mickhansen** [comment]
More likely here: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L539

`set` specifically sets an entire set, so wouldn't make sense for that to fail on duplicates.

**Comment by Hoverbear** [comment]
Okay I see. Can you explain the meaning of `isNewRecord` [here](https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L558-L560)?

**Comment by mickhansen** [comment]
It builds a sequelize instance from a primray key and marks it as being an existing instance (rather one for creation on save).

**Comment by thesofakillers** [comment]
Hi @mickhansen, I see that stale bot has closed this feature request. Would it be possible to reopen it?

 I was hoping to throw, catch and handle an error raised by a unique constraint failing when trying to add an association that already exists. 

If I run `foo.addBar(bar)`, the first time sequelize will correctly run an `INSERT` SQL statement, however if i try running `foo.addBar(bar)` again, it just runs a `SELECT` SQL statement. 

Surely it should run the `INSERT` again and throw an error, no? If I wanted to select, I would've called `foo.getBar({id:bar_id})` or something
