### ISSUE TITLE
Best way to enable support for old MSSQL

### ISSUE THREAD

**Issue by oromero** [sequelize/sequelize#3512]
I have been using sequelize with mssql 2012 and things work just fine. However, I need to enable temporary support for using mssql 2005.

I have found 2 issues when using sequelize with mssql 2005:
1) Datetime datatype `toSql` returns DATETIME2, which doesn't seem to be supported in mssql 2005. If changed to DATETIME, it works.
2) Inserts on tables fail because createdAt and UpdatedAt are inserted with wrong format for mssql 2005 DATETIME.

I have found where to fix the datatype:

/dialects/mssql/data-types.js

```
DATE.prototype.toSql = function() {
  return 'DATETIME2';
};
```

Changing DATETIME2 to DATETIME would work for MSSQL 2005. To adjust createdAt and UpdatedAt formats to fit in the DATETIME field, I found some changes on the following file would be required.

/lib/sql-string.js

```
SqlString.dateToString = function(date, timeZone, dialect) {
  date = moment(date).utcOffset(timeZone);

  if (dialect === 'mysql' || dialect === 'mariadb') {
    return date.format('YYYY-MM-DD HH:mm:ss');
  } else {
    // ZZ here means current timezone, _not_ UTC
    return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
  }
};
```

Adding mssql to the first condition fixes the second issue with the dates.

I have been looking on a way to enable this legacy support but not sure how to do it:
1) Changing the DATE prototype and SqlString.dateToString after referencing Sequelize.
2) Try to create a custom dialect. I tried to use `options.dialectModulePath` but doesn't seem to work for this purpose.

Is there any particular way to extend sequelize to enable this?

**Comment by janmeier** [comment]
To change the date you could do something very similar to this https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/data-types.js#L61-L69 to create your own DATE2005 type or similar.

Patching the tostring is not possible currently. We need the data types up/down system first https://github.com/sequelize/sequelize/issues/2042

**Comment by mbroadst** [comment]
@janmeier @mickhansen I think this is actually not so much of a mssql specific question, rather a question about how to "patch" or "extend" sequelize dialects through a plugin perhaps

**Comment by oromero** [comment]
For the first issue I haven't been able to solve it yet as the createdAt and updatedAt datatypes seems to be set by Sequelize at model.js. I could create the fields manually but haven't gone there yet.

For the second issue mentioned, at least from what I have seen so far, it is a bit difficult to extend the toString, as SqlString is handling all dialects.  The up/down system looks like something that would allow dialect-independent conversion, which could make it more extensible.

I don't think it is possible to enable this type of support until now, so I'am looking on avoiding having to support this in the application, but will be following the up/down feature :+1:

**Comment by itsravenous** [comment]
I have the same issue and followed (mostly blindly!) the advice above from @janmeier to create a DATE2005 type in a plugin-ish way. It's working for me so far, although obviously it relies on `data-types.js` staying in the same place in the Sequelize lib :)

orm/custom-data-types.js:
```javascript

var BaseTypes = require('sequelize/lib/data-types'),
	util = require('util');

var DATE2005 = function() {
	if (!(this instanceof DATE2005)) return new DATE2005();
	BaseTypes.DATE2005.apply(this, arguments);
};
util.inherits(DATE2005, BaseTypes.ABSTRACT);

DATE2005.prototype.toSql = function() {
	return 'DATE2005TIME';
};

module.exports = {
	DATE2005: DATE2005
};

if (!DATE2005.key) DATE2005.key = DATE2005;
if (!DATE2005.extend) {
	DATE2005.extend = function(oldType) {
		return new DATE2005(oldType.options);
	};
}
```

models/customer.js:
```javascript
var customDataTypes = require('../orm/data-types');

var Customer = orm.define('tblCustomers', {
	CustomerID: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		autoIncrement: true
	},
	Forename: {
		type: Sequelize.STRING
	},
	Surname: {
		type: Sequelize.STRING
	},
	DOB: {
		type: customDataTypes.DATE2005
	}
});

```

**Comment by oromero** [comment]
@itsravenous, I just made one change to get it running in my case.

Replaced this line:
```
BaseTypes.DATE2005.apply(this, arguments);
```
with this one:
```
BaseTypes.ABSTRACT.apply(this, arguments);
```

**Comment by itsravenous** [comment]
@oromero Apologies - that was a typo on my part! I actually use:

```javascript
BaseTypes.DATE.apply(this, arguments);
```

Have updated my original comment.

**Comment by oromero** [comment]
@itsravenous no problem, it is great to have an example. I was not able to find a way to enable this for the auto-generated fields createdAt and updatedAt, but this works great for user-defined model fields :+1:

**Comment by itsravenous** [comment]
Just a quick note - be careful if you're implementing a custom data type for `VARCHAR` in MSSQL (`Sequelize.STRING` maps to `NVARCHAR`) - you need to implement the `toSql() method`, especially if you're going to be doing updates on tables with triggers. For example:

```javascript
var BaseTypes = require('sequelize/lib/data-types');
var util = require('util');

var VARCHAR = function(length) {
	if (!(this instanceof VARCHAR)) return new VARCHAR(length);
	this.length = length;
	BaseTypes.ABSTRACT.apply(this, arguments);
};
util.inherits(VARCHAR, BaseTypes.ABSTRACT);

VARCHAR.prototype.toSql = function() {
	return 'VARCHAR('+this.length+')';
};
```

**Comment by mubaidr** [comment]
I am having the same issue. Is it possible to enable `datetime` support for timestamps?
