### ISSUE TITLE
raw query result instances don't get the getter attributes

### ISSUE THREAD

**Issue by neekey** [sequelize/sequelize#3515]
I have set some getter for my model like below:

```js
getterMethods: {

            typeName: function(){
                var name = 'other';
                switch( this.type ){
                    case 'data':
                        name = 'data app';
                        break;
                    case 'standard_data':
                        name = 'app with standard data structures';
                        break;
                    case 'app':
                        name = 'app that handles business';
                        break;
                    default:
                        name = 'other';
                        break;
                }

                return name;
            },
            ....
```

For instances from the sequelize `findAll` method, I can access `typeName` via `instance.typeName`, but it fails when trying to access the instances from raw query:

```js
Model.sequelize.query( selectSQL, Model.app ).spread(function( apps ){
    console.log( apps[0].typeName ); // --> undefined 
    return apps;
}),
```

**Comment by mickhansen** [comment]
Is apps a set of instances? If not that would likely be the first issue.

**Comment by neekey** [comment]
@mickhansen as I put the `Model.app` to the second param of `query`, the result apps should be a set of instances of Model.app I guess. I will double check this by trying to access the `apps[0].values`... I will let you know the result.

**Comment by neekey** [comment]
@mickhansen I tried to output the result and the apps turn out to be just plain object. According to the documentation:

> A second, optional, argument is the callee, which is a model. If you pass a model the returned data will be instances of that model.

the result should be a set of instances.

My SQL Query is: `SELECT apps.* from apps, appOwner where appOwner.app_id = apps.id and appOwner.user_id = 1 and apps.type = "data" LIMIT 10`

**Comment by janmeier** [comment]
Try passing ` { type: sequelize.QueryTypes.SELECT } ` as the third parameter.

You can also upgrade to latest master, where type defaults to SELECT when callee is set

**Comment by neekey** [comment]
@janmeier passing this third parameter and change `spread` to `then` fix this problem, thank you.
