### ISSUE TITLE
Multiple model associations to the same target 

### ISSUE THREAD

**Issue by rtorino** [sequelize/sequelize#3516]
In my case, I have two models User and Goal. I want the User model to have multiple association with the Goal model. Refer to the code below:

```javascript
var User = sequelize.define('User', {/* attributes */});
var Goal = sequelize.define('Goal', {/* attributes */});

// associations
Goal.belongsTo(User, {as: 'Owner'});
Goal.hasMany(User, {as: 'Members'});
```

Does sequelize support this where Goal has multiple association with the User? The first association works for me, I can set and get User as Owner of a Goal but the second doesn't work. The setters and getters for the second association (e.g. setMembers) are not available in the Goal prototype.

**Comment by mickhansen** [comment]
It should work like that out of the box, the foreignKey attribute should be derived from `as`.
Are you checking `Goal.prototype` or `Goal.Instance.prototype`?

**Comment by rtorino** [comment]
@mickhansen, I figured it out and it's working fine now. Thanks
