### ISSUE TITLE
Adding a seed.js file with sequelize db:seed

### ISSUE THREAD

**Issue by piyushchauhan2011** [sequelize/sequelize#3517]
It would be nice to have a seed folder with different seed files based on timestamps generated when we run `sequelize init` or `sequelize init:seed` and created using `sequelize db:seed:create`. The command can be extended to different environments e.g.
```
sequelize init --env=development
sequelize init --env=test
sequelize init --env=production
```
On executing `sequelize db:seed --env=<environment>` seed folder should automatically get synced for different environment and default should be development, only newer migrations should run.

**Comment by mickhansen** [comment]
Please open feature requests for the CLI here: https://github.com/sequelize/cli
