### ISSUE TITLE
Adding custom tasks to sequelize-cli

### ISSUE THREAD

**Issue by piyushchauhan2011** [sequelize/sequelize#3518]
It would be nice to have `sequelize create:task` to create new tasks which can then be used by developers to customize sequelize-cli to its fullest. It should appear in `sequelize help` and `sequelize help:create:task`. Though, you have to provide some way to create this help too. A separate tasks folder would suffice.

**Comment by mickhansen** [comment]
Please open feature requests for the CLI here: https://github.com/sequelize/cli
