### ISSUE TITLE
Bug: foreign key not-null-constraint blocks correct insert

### ISSUE THREAD

**Issue by VanHumbeeckA** [sequelize/sequelize#3519]
I have a model 'User' and a model 'Project'. A user can have multiple projects, and a single project ALWAYS belongs to a User (so not null).
I was able to push this constraint with sequelize:
```
sequelize.define('Project', {
...
userId: {
            field: "UserId",
            type: DataTypes.INTEGER,
            references: "User",
            referencesKey: "Id"
        },
...
classMethods: {
            associate: function (models) {
                // http://stackoverflow.com/questions/26835688/how-to-force-1n-association-with-sequelizejs/26839975
                project.belongsTo(models.User, { 
                    foreignKey: { name: "UserId", allowNull: false }, 
                    foreignKeyConstraint: true,
                    onDelete: "CASCADE"
                });
            }
        }
..
```
This works fine: the constraint is visible in the MySQL database.
When i add data like this, everything works and is stored in the mysql db:
```
User.create({
                username: "dummy-user",
                email: "a@b.com"
            }, {logging: false}).then(function(user) {
                Project.bulkCreate([
                    {
                        projectName: "X",
                        userId: user.id
                    },
                    {
                        projectName: "Y",
                        userId: user.id
                    }
                ], { logging: false }).then(function(projects) {
                    // do nothing
                });
            });
```
However, this works fine for `bulkCreate` but _NOT_ for a single `create`:
```
User.create({ // The user is succesfully created
        username: "dummy-user",
        email: "a@b.com"
    }, { logging: console.log }).then(function (user) { 
        Project.create({ // BUILDING the Project does NOT work, I get a 'SequelizeValidationError: notNull Violation: UserId cannot be null
            projectName: "X",
            userId: user.id // << number is OK, i checked
        }).then(function(p) {
            // do nothing
        });
    });
```

Is this a bug? or am I missing something?

**Comment by mickhansen** [comment]
You are using `userId` where it should be `UserId` it appears. `bulkCreate` doesn't do validation by default so it's ignoring `userId` and in `create` its ignoring `userId` and not seeing a value for `UserId`.

Change the attribute names either in the model or in the input to get the desired effect.

**Comment by VanHumbeeckA** [comment]
Ok thanks, that worked for me.
I thought I had that covered by specifying `field` of `userId` explicitly in the `Project` model.
Seems it doesn't work that way. But changing it did the trick.

Thanks for the quick response.

**Comment by mickhansen** [comment]
@VanHumbeeckA `field` specifies how the code interacts with the database, for user-side api it uses the attribute name (the prop key)

**Comment by mickhansen** [comment]
@VanHumbeeckA Hmm actually, you are right, it should just have worked i think.
