### ISSUE TITLE
Instance methods chaining

### ISSUE THREAD

**Issue by mmahalwy** [sequelize/sequelize#3522]
I really like Resql that changing sequelize's function of:
```
    students.find({where: {id: 34235}}).success(function(student) {
        student.getCourses().success(function(courses) {
            console.log(courses);
        });
    });
```
To:
```
    students.one({id: 34235}).courses().then(function(courses) {
        console.log(courses);
    });
```

I am wondering if there is a way to do this now with sequelize?

For example:
```
    models.User.find(1).getProducts()
```
I keep getting error:
```
    TypeError: Object [object Promise] has no method 'getProducts'
```

Rails also does an awesome job of:
```
User.find(1).products
```

Thanks!

**Comment by janmeier** [comment]
Closing, going to answer this on SO http://stackoverflow.com/questions/29550722/sequelize-chaining-methods/29598802#29598802

**Comment by mmahalwy** [comment]
@janmeier thanks!
