### ISSUE TITLE
remove association based on id

### ISSUE THREAD

**Issue by mmahalwy** [sequelize/sequelize#3523]
I'd like to remove the association based on Id without going into callback/promise hell:
```
models.User.find(req.user).then(function(user) {
      console.log(req.params)
      user.removeMyProducts(req.params.id).then(function(product) {
        res.send({message: product})
      });
    });
```

That fails as `req.params.id` is not an instance. How can I bypass this and be using just the id?

**Comment by janmeier** [comment]
In case anyone is wondering about the solution here - `removeAssociation` always takes an array, so `removeProducts([req.params.id])` works

**Comment by mmahalwy** [comment]
My stupidity.... it's `removeMyProduct` not products...

**Comment by mmahalwy** [comment]
@janmeier thanks!
