### ISSUE TITLE
How do I do a $or query against parent and joined tables?

### ISSUE THREAD

**Issue by wavded** [sequelize/sequelize#3527]
This query leaves out data:

```js
Invoice.findAll({
  where: {
    $or: [
      { id: Number(req.query.search) }
    ]
  },
  include: [{
    model: Employee,
    where: {
      $or: [
        { employee_no: Number(req.query.search) },
      ]
  }]
})
```

I figured I should do something like this:

```js
Invoice.findAll({
  where: {
      $or: [
        { id: Number(req.query.search) },
        { 'Employee.employee_no': Number(req.query.search) }
      ]
  },
  include: [Employee]
})
```

But I get the following error:

```
SequelizeDatabaseError: column Invoice.Employee.employee_no does not exist
```

I basically want the entire query in the `WHERE` clause and not in the `AND` one.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/3095

**Comment by mickhansen** [comment]
A possible work around is using `sequelize.where(sequelize.col('Employee.employee.no'), Number())`

**Comment by wavded** [comment]
FYI, this worked for me, a little verbose but works:

```js
where: req.query.search && {
  $or: [
    { id: Number(req.query.search) || 0 },
    sequelize.where(sequelize.col('Employee.employee_no'), Number(req.query.search) || 0),
    sequelize.where(sequelize.col('Employee.first_name'), 'ILIKE', `%${req.query.search}%`),
    sequelize.where(sequelize.col('Employee.last_name'), 'ILIKE', `%${req.query.search}%`)
  ]
},
include: [Employee]
```

**Comment by basco-johnkevin** [comment]
@wavded Hi! What version of SequelizeJS are you using? I tried your code above but it doesn't work. I'm using SequelizeJS version 2.0.4 

I posted a question on Stackoverflow - http://stackoverflow.com/questions/31258158/how-to-implement-search-feature-using-sequelizejs . Maybe you can help me out.
