### ISSUE TITLE
When selecting from users table in postgres, select statement generated tries to use reserved word 'user'

### ISSUE THREAD

**Issue by alexduan** [sequelize/sequelize#3528]
Driver: postgres
Created a user model using: sequelize model:create --name User --attributes email:string

When selecting from the user model with something as simple as:

models.User.findAll({}).then(function(err, users) {
    console.log(users);
});

I get the following stacktrace: 
Executing (default): SELECT id, email, createdAt, updatedAt, deletedAt FROM Users AS User WHERE User.deletedAt IS NULL;
Possibly unhandled SequelizeDatabaseError: syntax error at or near "User"

**Comment by janmeier** [comment]
Do you have quoteIdentifiers set to false? Otherwise User should automatically be quoted.

Which seqeulize version are  you using?

**Comment by alexduan** [comment]
Yes, I have set it to false so that table names are not created with quotes
(which is kind of weird on Postgres...).

On Tue, Apr 14, 2015 at 1:43 AM, Jan Aagaard Meier <notifications@github.com

**Comment by janmeier** [comment]
Well in that case there is really nothing to do - you have told sequelize that you don't want quotes, so you're not getting any :)

`quoteIdentifiers`  should really only be used in legacy situations where the table was created without quotes. When everything is handled by sequelize, quotes is your friend ;)

**Comment by mickhansen** [comment]
@alexduan includes don't work with `quoteIdentifiers: false` so i'd reenable it.

**Comment by alexduan** [comment]
Ah, ok - that makes sense. I'm used to inspecting records via psql and was
weirded out by the quotes. Will re-enable and suck it up. Thanks!

On Tue, Apr 14, 2015 at 9:20 AM, Jan Aagaard Meier <notifications@github.com
