### ISSUE TITLE
Hook not being called from association destroy

### ISSUE THREAD

**Issue by waltonseymour** [sequelize/sequelize#3529]
I'm using the following calls to generate assoications:

```js
models.Post.hasMany(models.Photo, {as: 'photos', foreignKey: 'post_id', onDelete: 'cascade', hooks: true});
models.Photo.belongsTo(models.Post, {as: 'post', foreignKey: 'post_id', onDelete: 'cascade', hooks: true});
```
and I have the following hook set up in the Photo model definition:
```js
return sequelize.define('Photo', {
    id: {
      type: 'UUID',
      primaryKey: true,
      allowNull: false
    },
    post_id: {
      type: 'UUID',
      allowNull: false,
    }
  },
  {
    hooks:{
      afterDestroy: function(photo, options) {
        utils.deletePhotos([photo.id]);
      }
    },
    tableName: 'photos'
  });
```
However when I call:
```js
models.Post.destroy({where: {id: req.params.id}, individualHooks: true});
```
the photo rows are deleted in the database but the hook is not being called.

Any idea why this might be happening?

**Comment by waltonseymour** [comment]
I looked in the source and realized that the cascading effect is only triggered through the instance destroy, not the model destroy.

After switching it, it works. 

The docs might want to be more clear regarding that though.

**Comment by mickhansen** [comment]
Hmm, the question is whether this should actually be supported though.
@janmeier? Bulk actions are generally meant as an optimization thing.

**Comment by janmeier** [comment]
Hmm, mayhaps it should.

**Comment by flexelektro** [comment]
Why is this closed ?
This doesnt work as supposed i think.

I find it quite unconvenient to call findAll first and then iterating through instances to call destroy, so that the hook is called.

Or am i wrong  ?

**Comment by janmeier** [comment]
@flexelektro Please provide a [SSCCE](HTTP://SSCCE.ORG/) :)

**Comment by flexelektro** [comment]
```
var FileUploads = db.define('fileuploads', {
    id: {
        ...
    },
    name: {
       ...
    }
},{
    hooks:{
        afterDestroy: function(instance){
            console.log("IS NOT CALLED !!!!",instance);
        }
    },
});


// Somewhere in the router :

var readytodelete = [1,2,3]
models.fileUploadModel.destroy({
                    where:{
                        id: readytodelete
                    }
});

```

Everything works fine, but the afterdestroy hook is never called.

**Comment by janmeier** [comment]
`individualHooks` http://docs.sequelizejs.com/en/latest/api/model/#destroyoptions-promiseinteger

**Comment by flexelektro** [comment]
oh thanks .. i will have a look !
