### ISSUE TITLE
Sequelize.sync() returns odd Promise

### ISSUE THREAD

**Issue by MichaelJCole** [sequelize/sequelize#3530]
Hi, I'm just getting started with your API.  I'm probably doing it wrong, but noticed this:

[Sequelize.sync()](https://github.com/sequelize/sequelize/blob/5aa77fa291abeaf0498f65724000c75da9ab9028/lib/sequelize.js#L713) is returning a promise that resolves to the last table synced.

Why wouldn't it return a promise to a sync'd version of itself?  Or, all the tables sync'd?  Just a suggestion.  I ended up doing something like this:

```
  var sequelize = new Sequelize(config.getDbUri());
  sequelize.define('user', { ... stuff ... });
  sequelize.define('thing', { ... stuff ... });

  // Promise to Create/update all tables in database
  return sequelize.sync()
  .then(function(lastTable) {
    return sequelize;
  });
```

Not a big deal, the extra .then() just seemed odd.

**Comment by janmeier** [comment]
This happens because sequelize does `Promise.reduce` when synching daos, so the last one is returned. Ending the chain with `return(this)` might make more sense yes :) - PR welcome

**Comment by MichaelJCole** [comment]
Ok, cool!  I'll take a crack at it!

**Comment by BridgeAR** [comment]
This should be closed

**Comment by MichaelJCole** [comment]
Hey, thanks for adding this.  Bummer you asked for a PR, I spent hours trying to put it together, and you then didn't accept it.  PR not welcome. :-(

Anyways, glad Sequalize is better for it :-)  Thanks for a great library!

**Comment by mickhansen** [comment]
@MichaelJCole I'm sorry about that, @BridgeAR's was just mergeable faster :) We still appreciate your effort!

**Comment by MichaelJCole** [comment]
Ok :-)  Glad it worked out!
