### ISSUE TITLE
Bulk update shouldn't default to validating each instance

### ISSUE THREAD

**Issue by garrett-gottlieb** [sequelize/sequelize#3536]
When running `this.update` under `classMethods`, validation should not be called as the instance will not have any properties except the ones being updated. Validation should only occur by default when the entire object is available to be validated.

**Comment by mickhansen** [comment]
Can use `{validate: false}` in the meantime. But you are probably right that it's not ideal.

**Comment by rpavlovs** [comment]
Would be nice to have it disabled unless `bulkValidate()` is defined.
Also, analogous to `Model.update({ individualHooks: ... }`, add `individualValidate` flag.
