### ISSUE TITLE
Index on multiple columns doesn't work with foreign key

### ISSUE THREAD

**Issue by pkeuter** [sequelize/sequelize#3538]
I'm pretty new to sequelize so I might be doing something wrong here. I'm on 2.0.5, using MySQL. Trying to make an index on multiple columns in Recording, 2 columns being in Recording, 1 column being in Station. 
```
  var Recording = sequelize.define("Recording", {
    date: DataTypes.DATE,
    hour: DataTypes.INTEGER,
    filename: DataTypes.STRING,
  }, {
    indexes: [{
      name: 'uni',
      unique: true,
      fields: ['date', 'hour', 'stationId']
    }] },
    {
    classMethods: {
      associate: function(models) {
        Recording.belongsTo(models.Station, {as: 'station'});
      }
    }
  });
  return Recording;
};
```
When I sync this with indexes higher that classMethods, it will complain that the referenced field does not exist. 
```
Possibly unhandled SequelizeDatabaseError: ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'stationId' doesn't exist in table
```
Which is not so strange because the belongsTo didn't get inserted into the database yet?

And when I turn it around (classMethods first and then indexes, I don't get any error, but my indexes aren't being generated at all). Am I doing something wrong? Thanks.

**Comment by janmeier** [comment]
Indexes and class methods should be in the same object, right now they are in separate objects

**Comment by pkeuter** [comment]
Do you mean I'm doing something wrong? Or do you mean this is a problem in sequelize?

**Comment by janmeier** [comment]
I mean you are doing something wrong :-). As I said your code is passing indexes and class methods in separate objects. They should be in the same object. 

Proper indentation and linebreaks will probably help you see the problem

**Comment by pkeuter** [comment]
Lol, I feel pretty stupid now. Thanks! It works :-)
