### ISSUE TITLE
Transaction not rolling back when uncaught exception happens (Sequelize v1.7.10 & MySQL)

### ISSUE THREAD

**Issue by renatoargh** [sequelize/sequelize#3539]
Hey! First; thank you guys for the super awesome work!

This is actually a question: I have the following code;

```javascript
sequelize.transaction(function(transaction) {
    Model.create({
        foo: 'bar'
    }, {
        transaction: transaction
    }).complete(function(err) {
        if(err) {
            throw err;
        }

        throw new Error('Error intentionally thrown!'); 
        // In my real code this error originates from a third party module

        transaction.commit();
    });
});
```

Isn't it expected that when the intentional error is thrown I end up NOT inserting a new record to the database? I tried starting my transaction with `autocommit: false;` but I am still ending up with an unwanted record inserted. 

My problem is that I have lots of consecutive inserts and eventually some third party module may throw an error. In this case I wan't to automatically rollback all the previous successfully inserted rows. Am I missing something? Is this the expected behavior? I always thought that a subtle lost connection (program exiiting due to uncaught exception) to the database would trigger a rollback! 

*I can confirm that the `INSERT` is running within a transaction since sequelize logs output the transaction id (a long guid) along with the insert command*

Thank you again for the amazing job! (:

**Comment by mickhansen** [comment]
For 1.7 you manually have to do rollbacks and commits.
For 2.0 you can used managed transactions: http://sequelize.readthedocs.org/en/latest/docs/transactions/#managed-transaction-auto-callback

**Comment by janmeier** [comment]
Unfortunately 1.7 is no longer officially supported - If you can find and fix the issue yourself you are welcome to provide a PR, but otherwise I'd suggest upgrading to 2.0 / 3.0
