### ISSUE TITLE
truncate all tables

### ISSUE THREAD

**Issue by sdepold** [sequelize/sequelize#354]
function truncateAllTables(callback) {
21:13 <gavri>     db.getQueryInterface().showAllTables().success(function(tableNames) {
21:13 <gavri>         var chainer = new Sequelize.Utils.QueryChainer();
21:13 <gavri>         _.each(tableNames, function(tableName) {
21:13 <gavri>             chainer.add(db.query("truncate " + tableName));
21:13 <gavri>         });
21:13 <gavri>         chainer.run().done(callback);
21:13 <gavri>     });
21:13 <gavri> }

**Comment by pkyeck** [comment]
> I could mostly see it used for testing, and we already have a helper method there

I know this is an old thread but I just stumbled upon it. Where can I find the test helpers? Are they still there?

**Comment by janmeier** [comment]
@pkyeck All tests actually just drop and re-create tables now. But you can use destroy with truncate: true http://docs.sequelizejs.com/en/latest/api/model/#destroyoptions-promiseundefined
