### ISSUE TITLE
Feature: Eager load in mapping definition

### ISSUE THREAD

**Issue by perara** [sequelize/sequelize#3540]
On some project, the database structure are nested pretty deep.
I'm required to eager load this data and send it to an client.

The following include chain i have to write is the following:
```coffeescript
that.Database.Model.User.find(
	where: 
		id: 1
	include:
	[
		{
		  model: that.Database.Model.Identity
		  include:
			[
			  {
				model: that.Database.Model.Network
				include:
				  [
					{
					  model: that.Database.Model.Node
					},
					{
					  model: that.Database.Model.Host
					  include:
						[
						  model: that.Database.Model.Filesystem
						]
					}
				  ]
			  }
			]
		}
	]
).then (user) ->
console.log user.Identities[0].Networks[0].Hosts[0].Filesystem
```

Would it be better to have an option to define such include chains in the mapping definition?
Something like this:
```coffeescript
that.Database.Model.User.find(
	where: id: 1
	eager: true
).then (user) ->
    console.log user.Identities[0].Networks[0].Hosts[0].Filesystem
```

**Comment by janmeier** [comment]
You can use `include: [{ all: true, nested:true}] `

**Comment by perara** [comment]
That would work, but in this case i would end up eager loading most of the database.
Its not a very big issue, but would slow down the application abit.

Could use  all: and nested for now :)

**Comment by janmeier** [comment]
That would be my best bet until default scope supports includes

**Comment by janmeier** [comment]
Default scope now supports includes
