### ISSUE TITLE
belongsToMany with include[].where

### ISSUE THREAD

**Issue by ackerdev** [sequelize/sequelize#3552]
It seems that when including a belongsToMany relation with a where clause, there appear to be a few issues with the resulting query.
1. `field` is not respected, and the query attempts to use the attribute name as the identifier without an alias.
2. `foreignKey` and `otherKey` seem to get mixed up, causing the query to contain `[ThroughModelAlias].[TargetFK] = [TargetModelAlias].[SourceModelId]`

version 2.0.6, MSSQL dialect

**Comment by mickhansen** [comment]
Thanks for the report @ackerdev.
Specific examples always welcome - pull request with failing tests even more so.
