### ISSUE TITLE
Would you please fix read write bug in version 1.7.10 and release version 1.7.11 ?

### ISSUE THREAD

**Issue by starfalling** [sequelize/sequelize#3554]
In file lib/dialects/mysql/connector-manager.js, line 111

connection.queryType should be write, not read

**Comment by mickhansen** [comment]
We don't actively maintain 1.7.x anymore.
If you submit a pull request we'll review and release.

**Comment by starfalling** [comment]
I have submitted a pull request, please take a look

https://github.com/sequelize/sequelize/pull/3557

Thanks~
