### ISSUE TITLE
Postgres sequences

### ISSUE THREAD

**Issue by leonprou** [sequelize/sequelize#3555]
Is there any intentions to implement postgres [sequences](http://www.postgresql.org/docs/8.1/static/sql-createsequence.html)?
 As I see the only option to use them now is with the raw query syntax

**Comment by mickhansen** [comment]
@leonprou Not on the roadmap - You're the first one requesting the functionality. What's your usecase?

**Comment by leonprou** [comment]
@mickhansen 
thank for quick response
I have users table with array of chats in it as a field, I would like to give an increment id for every new chat. 
I could use a separate table for chats, but then I'll have to join two tables. As I understand I can index an array or a JSONB field with Postgres, so this embedded solution (mongoDB style) sounds more suitable for my case.

**Comment by jimmed** [comment]
I'd like to :+1: this issue. My use case is migrating a legacy system which uses a 'global' sequence to generate IDs for multiple tables, as per [this document][1]:

```
CREATE SEQUENCE common_fruit_id_seq;

CREATE TABLE apples (
    id      INT4 DEFAULT nextval('common_fruit_id_seq') NOT NULL,
    price   NUMERIC
);

CREATE TABLE oranges (
    id      INT4 DEFAULT nextval('common_fruit_id_seq') NOT NULL,
    weight  NUMERIC
);
```

[1]: http://www.neilconway.org/docs/sequences/

**Comment by mickhansen** [comment]
@jimmed Well you can manually create the sequences and just have sequelize point at the tables.

**Comment by SerjoPepper** [comment]
+1

**Comment by jtan25** [comment]
@mickhansen  can you elaborate on that? 
I currently have a column who's default value is nextval(' '). I create the object and left the field blank. But the sql query is rejected as it is not being recognized as an integer. 
     
    INSERT INTO client_table (client_id, name) VALUES (\'nextval(\'client_id_gen\')\', Johnny)

**Comment by gstrtoint** [comment]
I have solution for shis:
Alter library sequelize file: squelize/lib/sql-string.js
incluid on line 56 this:

alter 

if (dialect === 'postgres' || dialect === 'sqlite' || dialect === 'mssql') {
    // http://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
    // http://stackoverflow.com/q/603572/130598
    val = val.replace(/'/g, "''");
  } else {
    val = val.replace(/[\0\n\r\b\t\\\'\"\x1a]/g, s => {
      switch (s) {
        case '\0': return '\\0';
        case '\n': return '\\n';
        case '\r': return '\\r';
        case '\b': return '\\b';
        case '\t': return '\\t';
        case '\x1a': return '\\Z';
        default: return '\\' + s;
      }
    });
  }

for

if (dialect === 'postgres' || dialect === 'sqlite' || dialect === 'mssql') {
    // http://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
    // http://stackoverflow.com/q/603572/130598
    if(val.indexOf('nextval(')>-1) {
      return val
    }
    val = val.replace(/'/g, "''");
  } else {
    val = val.replace(/[\0\n\r\b\t\\\'\"\x1a]/g, s => {
      switch (s) {
        case '\0': return '\\0';
        case '\n': return '\\n';
        case '\r': return '\\r';
        case '\b': return '\\b';
        case '\t': return '\\t';
        case '\x1a': return '\\Z';
        default: return '\\' + s;
      }
    });
  }

On your model declare field with defaultValue = "nextval('xxxxxxx')", ex:

...
return sequelize.define('cgm', {
      z01_numcgm: {
        type: DataTypes.INTEGER,
        defaultValue: "nextval('cgm_z01_numcgm_seq')",
        allowNull: false,
        primaryKey: true,
      },
....

**Comment by damianobarbati** [comment]
@jimmed @jtan25 did you manage to solve this?

I need the primary key "id" prefixed with the table name.

But sequelize is autofilling the "id" column (which is given primaryKey=true) with "null" on insert thus I always get:
```
SequelizeDatabaseError: null value in column "id" violates not-null constraint
```

Here what I'm currently doing on my tables:
```
//custom sql after sync({ force: true }) for each model
const sequenceName = model.toLowerCase() + '_omniseq';
await database.query(`drop sequence if exists "${sequenceName}"`);
await database.query(`create sequence "${sequenceName}"`);
await database.query(`alter table "${model}" alter column id drop default`);
await database.query(`alter table "${model}" alter column id drop not null`);
await database.query(`alter table "${model}" alter column id set default '${model.toLowerCase()}'||nextval('${sequenceName}')::text not null`);
await database.query(`alter sequence "${sequenceName}" owned by "${model}".id`);             

//when defining models
definition.id = {
    type: Sequelize.TEXT,
    primaryKey: true,
    unique: true,
};
```

**Comment by brian-human-interest** [comment]
I'd love to see this feature. Was looking for the same thing.

It seems like folks are still asking this question. See [SO](https://stackoverflow.com/a/42502843) answer.

**Comment by yogeshbonzer** [comment]
@gstrtoint Thanks for solution. You saved me!!!!
But when will this code merge in master branch?
I have updated library on following path **\node_modules\sequelize\lib\sql-string.js**.  Line No. 58. When I look there I found something interesting that the following comments are already presents
```
// http://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
// http://stackoverflow.com/q/603572/130598
```

But code is not present. So I put following code there at line no. 61 in **\node_modules\sequelize\lib\sql-string.js**

```
if(val.indexOf('nextval(')>-1) {
     return val
}
```

But it is not good practise to edit direct library file. So I am eager when should this comments will be merge in master? So on production server I don't need to edit manually this file.
 @gstrtoint

**Comment by hikensensei** [comment]
In case there is someone who wants to do this as well read [this answer on StackOverflow](https://stackoverflow.com/a/67524186/5827964)

**Comment by ephys** [comment]
We discussed this issue at our recent meeting. We're not convinced providing an API for this would be clearer than using raw SQL. We recommend doing it like on [the StackOverflow post](https://stackoverflow.com/questions/42501904/custom-postgresql-sequence-nextval-in-sequelizejs/67524186#67524186) @hikensensei posted

## In Models:

Use `literal` to use the sequence

```typescript
import { literal, DataTypes } from 'sequelize';

sequelize.define("model", {
  ...attributes,
  customSequence: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: literal("nextval('custom_sequence')"),
  },
});
```

If you're using `sequelize.sync`, use the beforeSync hook to create the sequence (or create it before calling .sync):

```
sequelize.beforeSync(() => {
  await sequelize.query('CREATE SEQUENCE IF NOT EXISTS custom_sequence');
  await sequelize.query('ALTER SEQUENCE custom_sequence RESTART');
});

await sequelize.sync();
```

## In Migrations

```js
import { literal, DataTypes } from 'sequelize';

module.exports = {
  up: async (queryInterface) => {
    await queryInterface.sequelize.query('CREATE SEQUENCE custom_sequence');

    await queryInterface.addColumn('table', 'customSequence', {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: literal(`nextval('custom_sequence')`),
    });
  },

  down: async (queryInterface) => {
    await queryInterface.removeColumn('table', 'customSequence');
    await queryInterface.sequelize.query('DROP SEQUENCE custom_sequence');
  },
};
```
