### ISSUE TITLE
Add an option for complex ON for joins

### ISSUE THREAD

**Issue by yonjah** [sequelize/sequelize#3561]
I'm trying to add a new type of association to sequelize (#3532)
for nested set if I want to fetch all the children of a record I need to run the query ->

``` sql
SELECT * FROM `table` INNER JOIN `table` as `child` ON (
     `table`.`lft` < `child`.`lft` AND
     `table`.`rgt` > `child`.`rgt`
);
```

unfortunately Sequelize doesn't support multiple fields for ON and only allows eql relationship.
Since ON syntax is similar to where it would be great if we could pass with include a `on` parameter which will define how the relationship attributes should be associated 

``` javascript
{
    on: {
        lft: { $lt: 'lft'},
        rgt: { $gt: 'rgt'}
    }
}
```

if no on was sent Sequelize can fall back to default -

``` javascript
on = {};
on[left.primaryKeyAttributes[0]] = right.primaryKeyAttributes[0];
```

**Comment by mickhansen** [comment]
That's actually a feature we've talked about a few times. I'm sure there must be a feature request for the same tihng elsewhere.
