### ISSUE TITLE
Class methods aren't found by jsdoc

### ISSUE THREAD

**Issue by itsravenous** [sequelize/sequelize#3562]
Looks like it's having trouble linking instance methods to the parent class (e.g. Model) because they're defined separately, i.e:

```
/**
  * Search for a single instance. This applies LIMIT 1, so the listener will always be called with a single instance.
  *
  * @param  {Object|Number}             [options] A hash of options to describe the scope of the search, or a number to search by id.
  * @param  {Transaction}               [options.transaction]
  * @param  {Object}                    [queryOptions]
  *
  * @see {Model#findAll}           for an explanation of options and queryOptions
  * @return {Promise<Instance>}
  * @alias find
  */
Model.prototype.findOne = function () {
[...]
}
```

instead of:

```
Model.prototype = {
    /**
      * Search for a single instance. This applies LIMIT 1, so the listener will always be called with a single instance.
      *
      * @param  {Object|Number}             [options] A hash of options to describe the scope of the search, or a number to search by id.
      * @param  {Transaction}               [options.transaction]
      * @param  {Object}                    [queryOptions]
      *
      * @see {Model#findAll}           for an explanation of options and queryOptions
      * @return {Promise<Instance>}
      * @alias find
      */
    findOne: function () {
        [...]
    }
}
```

JSDoc picks up the methods if a `@memberof Model` tag is added to the method comment. This really seems like more of a JSDoc issue, but I'd be happy to submit a PR when I get time to add in the @memberof tags. It's whether that makes it too much effort when adding new methods :)

**Comment by janmeier** [comment]
It seems to work fine :) http://docs.sequelizejs.com/en/latest/api/model/#findoneoptions-queryoptions-promiseinstance

We are not using jsdoc, just jsdoc style comments. We are using dox and a custom script to generate the docs.

**Comment by itsravenous** [comment]
My apologies - I wasn't clear on why I was using JSDoc! I'm using Sequelize in a project of mine which uses JSDoc for documentation, and was trying to get the Sequelize docs to appear within my own (so I can e.g. `@extend Sequelize.Model` and have inherited methods show on my model classes. But seems like this is really a JSDoc problem - it should be able to pick up the fact that the methods are part of the prototype. I'll file a bug over there. Thanks and sorry for the bother!

**Comment by janmeier** [comment]
No problem - In case your jsdoc bug does not yield any results you are welcome to provide a PR to seqeulize - I just cant guarantee we'll always remember to add the tag for new methods :)

**Comment by itsravenous** [comment]
Lightning response ;) I just found that if I remove the closure function that wraps the Model class definition then JSDoc suddenly picks up all the methods! I'll see if it's a known issue.

**Comment by itsravenous** [comment]
So it is fixable, but it would require assigning names to the closure functions, which is something one is not likely to remember to do when writing new work. I'll resign myself to using the `:external` prefix and using a `@link` to link to the Sequelize Read the Docs site. Thanks for listening!

**Comment by janmeier** [comment]
No problem @itsravenous  :)

Assigning names to closure functions would also sometimes make debugging easier (you get the function name instead of undefined). If you can find a jshint optioon that enforces names to closure functions I think we'd be open to support and enforce iut

**Comment by itsravenous** [comment]
Well now you've piqued my interest! Taking a step back, do you know what the purpose of the closure is? Taking `lib/model.js` as an example I can't see any benefit to:

```javascript
module.exports = (function () {
    // Class definition code here

    return Model
})();
```

versus:

```javascript
// Class definition code here

module.exports = Model; 
```

The two seem equivalent to me, but I may be missing some nuance of closures :)

**Comment by janmeier** [comment]
Hmm, right now the IIFE protects some private model methods, but these do not strictly need to be private I guess - we could just stick them on the model object with a $ in front. 

I think we could just as well remove the clousre in this case

**Comment by itsravenous** [comment]
Aah, you're referring to `paranoidClause`, `addOptionalClassMethods`, etc defined beneath `// private`? These would presumably still be "private" in the sense that they aren't exported via `module.exports` anyway, so removing the closure wouldn't change that. If you're happy for me to do so I could submit a PR with the same logic applied to other class definition files.

**Comment by janmeier** [comment]
I'd like @mickhansen to chime in here, but I'm pretty sure you can safely change it :)

**Comment by mickhansen** [comment]
No reason at all to have IIFE in Node.js, atleast not in terms of not exposing privates inside a file to files including it.

**Comment by axell-brendow** [comment]
I had a similar issue with jsdoc, static Model methods and @template when I created a generic repository, but I got auto complete using something like:

```js
/** @type {typeof import('sequelize').Model} */
const M = null;
```

![image](https://user-images.githubusercontent.com/11397715/122285455-1e781f00-cec5-11eb-9465-2e1df1a84a9c.png)

```js
/**
 * @template {typeof import('sequelize').Model} T
 * @param {T} model
 */
module.exports = model => ({
  /**
   * @param {import('sequelize').FindOptions} options
   */
  list: options => model.findAll(options),

  /**
   * @param {object} values
   * @param {import('sequelize').CreateOptions} options
   */
  create: (values, options) => model.create(values, options),

  /**
   * @param {object[]} values
   * @param {import('sequelize').BulkCreateOptions} options
   */
  bulkCreate: (values, options) => model.bulkCreate(values, options),

  /**
   * @param {object} values
   * @param {import('sequelize').UpdateOptions} options
   */
  update: (values, options) => model.update(values, options),

  /**
   * @param {import('sequelize').DestroyOptions} options
   */
  destroy: options => model.destroy(options),
});
```

**Comment by nanosoftonline** [comment]
```js
@type import("sequelize").ModelCtor<import("sequelize").Model>
```
worked for me

**Comment by bernardo-zuchowski** [comment]
> ```js
> /** @type import("sequelize").ModelCtor<import("sequelize").Model> */
> ```
> 
> worked for me

Perfect!
I used like this:
``` js
module.exports = class GenericRepository {
  /**
   * Base class to create a repository
   * @param {import("sequelize").ModelCtor<import("sequelize").Model>} model
   */
  constructor(model) {
    this.model = model;
  }
```
