### ISSUE TITLE
How implement this query

### ISSUE THREAD

**Issue by MikeBazhenov** [sequelize/sequelize#3565]
```SQL
SELECT "a".* FROM "accounts" a, account_phones p, account_emails e, WHERE 
  (p.phone ilike '%11111111111%' OR  e.email ilike '%11111111111%') 
  AND a.id = p.account_id 
  AND a.id = e.account_id
ORDER BY "id" DESC;
```

I do

```JavaScript
db.Accounts.findAll({
  where: where,
  include: [
    {model: db.AccountEmail, where: whereEmail, required: false },
    {model: db.AccountPhone, where: wherePhone, required: false }
  ]
})
```

and it no worked

**Comment by janmeier** [comment]
Your post is empty :)

**Comment by MikeBazhenov** [comment]
@janmeier ctrl+enter :(

**Comment by janmeier** [comment]
Please define how it does not work - does it throw an error, does the query look wrong, are there no results etc? 

What does your `where` object look like?

From the query you want it looks like you should place the where objct only on the main query, not on the includes

**Comment by MikeBazhenov** [comment]
@janmeier sorry

Request return a 0 rows, thanks will be research for build query..

**Comment by MikeBazhenov** [comment]
@janmeier 

```

**Comment by janmeier** [comment]
Try something like 

```js
where = {
  $or: [
    { first_name: { $ilike: '%' + q  + '%'% }},
    { last_name: { $ilike: '%' + q  + '%'% }}
    ....,
    sequelize.where(sequelize.col('account_emails.email'), { $ilike: '%' + q + '%')
  ]
}

**Comment by abhinav76** [comment]
does it work for integers too?
i have a no say 11112234000000 and i have to check if the number given has 2234 part in it at the position like say 55552234000000. So it should return true. is there any method to do this for numbers?

**Comment by janmeier** [comment]
@abhinav76 you'll probably have to cast the number to a string. You can use `sequelize.fn` and `sequelize.where` similarly to above

**Comment by abhinav76** [comment]
but the field in the database is an integer, so that would be a problem no?

**Comment by janmeier** [comment]
Yes, that's why you have to call the cast function to cast it to a string

**Comment by abhinav76** [comment]
@janmeier do we cast it to string like this?
<code>sequelize.where(sequelize.col('account_emails.email'), { $ilike: '%' + q + '%')</code>

**Comment by janmeier** [comment]
You have to call the sql cast function on the column

**Comment by abhinav76** [comment]
ok i have to use a raw query then?

**Comment by janmeier** [comment]
@abhinav76 No, you have to use .where and .fn like i mentioneed in my first reply

`sequelize.where(sequelize.fn('cast' ...`
or
`sequelize.where(sequelize.cast(sequelize.col( ... `

**Comment by abhinav76** [comment]
<code> birthdayToday:function(){
	  	return Profile.findAll(sequelize.where(sequelize.cast(sequelize.col('member_dob'),{$ilike:'%'+'0811'+'%'})));
	  },</code>
i used this and it gives me error

**Comment by janmeier** [comment]
You forgot `{ where: sequelize.where ... } `. Also, you can't just call cast, you have to tell what to cast to http://www.1keydata.com/sql/sql-cast.html

**Comment by abhinav76** [comment]
thanks for helping me but i just cant figure out a way
i used 
<code>eturn Profile.findAll({where:sequelize.where(sequelize.cast(sequelize.col('profile.member_dob AS INTEGER'),{$ilike:'%'+'0811'+'%'}))});/<code>
and its giving me error

**Comment by janmeier** [comment]
```js
Profile.findAll({
  where: sequelize.where(
    sequelize.cast(sequelize.col('profile.member_dob'), 'INTEGER'),
    {$ilike:'%'+'0811'+'%'}
  )
});
```

**Comment by abhinav76** [comment]
there's a parse error now
the query it is executing is <code>SELECT `member_username`, `member_gender`, `member_dob`, `member_country`, `state`, `city`, `hair_colour`, `hairstyle`, `eye_colour`, `eyesight`, `complexion`, `height`, `body_ENGINE`, `exercise`, `religion`, `religious_beliefs`, `education`, `occupation`, `annual_income`, `ethnicity`, `nationality`, `languages`, `diet`, `smoke`, `drink`, `current_relationship_status`, `preferred_relationship`, `profile_tagline`, `screened`, `photo_status`, `hidden`, `record_date`, `update_date`, `ip`, `member_id`, `time_stamp`, `photo_key` FROM `profile` AS `profile` WHERE CAST(`profile`.`member_dob` AS VARCHAR) ILIKE '%0811%';</code>
I don't think there is ilike in mysql,isn't it just like?

**Comment by abhinav76** [comment]
Thanks for the help
There's no varchar defined as types in cast function

**Comment by janmeier** [comment]
Well, then you probably have to cast it to something else - https://dev.mysql.com/doc/refman/5.0/en/cast-functions.html#function_cast. Please try to seek information on your own - this is a basic sql question, not a sequelize question. Once you know what you want to achieve in sql I might be able to help you convert that to sequelize, but I don't want to write your queries for you ....

And no, there is no ilike in mysql, you'll have to use the 'LOWER` function if you want case insensitive matching

**Comment by abhinav76** [comment]
Yeah I found it .
appreciate your help :+1:
