### ISSUE TITLE
There is validation when using add[AS](), but no validation when using set[AS]()

### ISSUE THREAD

**Issue by loki2302** [sequelize/sequelize#3569]
It looks like the `through` entity is not validated when using `set[AS]()`. Consider an example:
```javascript
Project = sequelize.define('Project', {
  name: Sequelize.STRING
});

Employee = sequelize.define('Employee', {
  name: Sequelize.STRING
});

Participation = sequelize.define('Participation', {
  role: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      len: {
        args: [2, 50],
        msg: 'too bad'
      }
    }
  }
});

Project.belongsToMany(Employee, { as: 'Participants', through: Participation });
Employee.belongsToMany(Project, { as: 'Participations', through: Participation });
...

// TEST #1: associating with add[AS]()
var project = yield Project.create({ name: 'project 1' });
var employee = yield Employee.create({ name: 'employee 1' });
// the next line throws a SequelizeValidationError
yield project.addParticipant(employee, { role: '' });
...

// TEST #2: associating with set[AS]()
var project = yield Project.create({ name: 'project 1' });
var employee = yield Employee.create({ name: 'employee 1' });
employee.Participation = { role: '' };
// the next line DOESN'T throw a SequelizeValidationError
yield project.setParticipants([employee]);
```

**Comment by janmeier** [comment]
Hmm, looks like a bug. Does it work if you do eg `employee.Participation = { role: 'something' };` - will this insert something into the join table, or is it ignored completely?

**Comment by loki2302** [comment]
Hi @janmeier,
Thanks for the quick response! In both cases (`{role: ''}` and `{role: 'something'}`) the new row is inserted successfully.

**Comment by janmeier** [comment]
Definitely looks like a bug then - I just wanted to make sure that it was not ignoring `employee.Participation` comletely for some reason

**Comment by BridgeAR** [comment]
The reason is that you use bulkCreate. BulkCreate does not validate if you do not pass `validate: true` as an option. I actually think it might be good to set it as a default [here] (https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L516) but that's not up to me.
