### ISSUE TITLE
Unable to create migration with Hstore DataType? [Postgres]

### ISSUE THREAD

**Issue by tylerFowler** [sequelize/sequelize#3572]
In one of my migrations I have a column like:

```coffee
files:
        type: DataTypes.HSTORE
        allowNull: false
        unique: true
```

But when I try to run the migration I get the following error:
`Possibly unhandled SequelizeDatabaseError: type "hstore" does not exist` (from `lib/dialects/postgres/query.js` around line 110).

Am I not initializing the HSTORE type incorrectly? Or is this a bug with migrations?

**Comment by janmeier** [comment]
You need to enable hstore: http://www.postgresql.org/docs/9.1/static/sql-createextension.html

**Comment by tylerFowler** [comment]
Interesting, I didn't know you had to do this. Might be worth throwing something into the docs about it. But that did fix the issue, thanks!

**Comment by Hoverbear** [comment]
@janmeier Is there a reason that Sequelize does not do this itself?

**Comment by BridgeAR** [comment]
http://www.postgresql.org/docs/9.4/static/sql-createextension.html

**Comment by janmeier** [comment]
No other reason than 'no-one has taken the time to do it'

**Comment by BridgeAR** [comment]
Well sequelize could try to do this per database but there would be new issues. 

1) Not every database might be run with owner rights and it certainly should not be run with superuser rights. 
2) Depending on the system you're running on, you'll also need to install an additional program that can't be installed by sequelize or any other npm module.

**Comment by Hoverbear** [comment]
@BridgeAR that's good reasoning.
