### ISSUE TITLE
Stubbing Model.findAll for Testing

### ISSUE THREAD

**Issue by aowainati** [sequelize/sequelize#3573]
Hi folks, running into some issues trying to stub a findAll method on my model for unit testing. Here's the controller code I'm trying to test:

    // UsersController#index
    export function index(req, res, next) {
      User.findAll().then((users) => {
        res.send(JSON.stringify(users, undefined, 2) + "\n");
      }).catch((err) => {
        res.status(500).send('Everything exploded!');
      });
    }

I'm now trying to write a test to verify the exception catching behavior specifically, for which I'm using mocha/chai/sinon:

    // Helper function for generating a fake response
    function generateFakeResponse() {
      let fakeResponse = {};
      fakeResponse.send = sinon.stub().returns(fakeResponse);
      fakeResponse.status = sinon.stub().returns(fakeResponse);
      return fakeResponse;
    }
    
    describe('#index', () => {
      it('errors when findAll fails', () => {
        let response = generateFakeResponse();
        let p = Promise.reject(new Error("Promise failed!"));
        let spy = sinon.stub(User, 'findAll').returns(p);
    
        UsersController.index({}, response)
        expect(response.status).to.have.been.calledWith(500);
        expect(spy).to.have.been.calledOnce;
        spy.restore();
      });
    });

The general idea here is to stub User.findAll to return a Sequelize Promise that raises an exception upon resolution (which, Promise.reject should be doing, correct?). However, using some logging statements, it looks like UsersController.index isn't running until after the assertions are made, so that doesn't seem to work. One hack that fixed this was to wrap the expect statements in a setTimeout just to force the next tick, but that feels ugly:

    setTimeout(() => {
      expect(response.status).to.have.been.calledWith(500);
      expect(spy).to.have.been.calledOnce;
      spy.restore();
    }, 0);

I think my approach isn't correct here, what's the proper pattern for this type of test? Thanks!

**Comment by mickhansen** [comment]
Your stub looks correct. I can't really help you more than that since i never stub my sequelize models when running tests.

**Comment by aowainati** [comment]
How would you test the exception-catching logic instead, then?

**Comment by mickhansen** [comment]
I guess i don't, or i just throw somewhere in the chain to trigger the error path.

**Comment by mickhansen** [comment]
@aowainati Bluebird forces asynchronous resolves to ensure that the API is always asynchronous (and never sometimes synchronous in the case of synchronous resolves).
That could be the issue you're seeing here.

What assertion is failing? The response called one? I would assume the stub spy still passes.

**Comment by aowainati** [comment]
You are correct, `expect(response.status).to.have.been.calledWith(500);` is the one that fails.

**Comment by mickhansen** [comment]
Well thats the forced asychronocity of bluebird for you.
You have a few options: 

- use process.nextTick
- return the promise from the controller and use that in he test
- do a endtoend test with supertest or similiar instead.
