### ISSUE TITLE
[question] Hooks not fired?

### ISSUE THREAD

**Issue by finnishprince** [sequelize/sequelize#3574]
Hi, guys,

thank you for building aweseome ORM.

I'm trying to use hooks in Sequelize. According to [docs](http://docs.sequelizejs.com/en/latest/api/hooks/#beforecreatename-fn), I 've defined `beforeCreate` hook:

    module.exports = function(sequelize, DataTypes) {
      var User = sequelize.define("User", {
        email            : DataTypes.STRING,
        hash             : DataTypes.STRING(1024),
        salt             : DataTypes.STRING(512),
        activationKey    : DataTypes.STRING,
        resetPasswordKey : DataTypes.STRING
      }, {
        hooks: {
          beforeFind: function(options) {
            console.log('[ORM]: `beforeFind` hook fired...')
          },
          beforeCreate: function(attributes, options, fn) {
            console.log('[ORM]: `beforeCreate` hook fired...')
            fn();
          },
        },
        classMethods: {
          associate: function(models) {
            // associations can be defined here
            // ...
          }
        }
      });
      return User;
    };

There are no examples on the docs page, so I've grabbed some usage examples from [tests](https://github.com/sequelize/sequelize/blob/18cb700291fe519f2c77dd91d1e3504acae4b233/test/integration/hooks.test.js). Now I'm using `beforeFind` and `beforeCreate` hooks:

    db.sequelize.sync().then(function() {
      console.log('[INFO]: database synced')
      User
        .create({
          email: "helloworld@example.com",
          name: "John Dow"
        })
        .then(function(user) {
          console.log('[INFO]: <User> created')
        })

      User
        .find({
          where: {
            id: 16
          }
        })
        .then(function(user) {
          console.log(JSON.stringify(user));
        })
        .catch(function(err) {
          console.log(err);
        })
    });

Output:

    [INFO]: database synced

    [ORM]: `beforeFind` hook fired...

    Executing (default): SELECT "id", "email", "hash", "salt", "activationKey", "resetPasswordKey", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."id" = 16;
    Executing (default): INSERT INTO "Users" ("id","email","updatedAt","createdAt") VALUES (DEFAULT,'helloworld@example.com','2015-04-21 23:38:13.697 +00:00','2015-04-21 23:38:13.697 +00:00') RETURNING *;

    {"id":16,"email":"helloworld@example.com","hash":null,"salt":null,"activationKey":null,"resetPasswordKey":null,"createdAt":"2015-04-20T21:51:56.089Z","updatedAt":"2015-04-20T21:51:56.089Z"}

    [INFO]: <User> created

**It seems `beforeFind` is fired, but `beforeCreate` — not. What I'm doing wrong?**

I know, there were separate hooks for Model and instance in previous versions of Sequelize, but current docs do not point on any differences. Are docs are actual for current master, or it's better to be guided by tests?

Any help is highly appreciated.

**Comment by finnishprince** [comment]
"pg": "^4.3.0",
    "pg-hstore": "^2.3.2",
    "promise": "^7.0.0",
    "sequelize": "^2.0.6",

**Comment by finnishprince** [comment]
Moving to SO, sorry.

**Comment by santostmd** [comment]
@f1nnix I'm having the same issue. What was the problem?
