### ISSUE TITLE
concurrent transactions result to findAll pending.

### ISSUE THREAD

**Issue by neekey** [sequelize/sequelize#3575]
I encountered a weird situation when trying to create 100 entities in my test case, and within each creation of my entity a `findAll` will be called to ensure something really exist in my database, like:

```js
var batchCreate = [];
_.times( 100, function(){
    batchCreate.push( EntityProxy.createEntity( { ... } ) );
});
Promise.all( batchCreate ).then( function(){
    console.log( 'all entities have been created' );
});
```

but this process just can't finish, the callback pass to `then` never been called. I struggle this for hours and make it work by remove all the transaction from the implementation of `createEntity`.

So I create a simple snap to reproduce this bug:

```js
"use strict";

var Sequelize = require("sequelize");
var _ = require( 'lodash' );

var config = {
    "username": "test",
    "password": "test",
    "database": "test",
    "host": "127.0.0.1",
    "dialect": "mysql",
    "port": 3306
};

var sequelize = new Sequelize(config.database, config.username, config.password, config);

var Test = sequelize.define("test", {
    name: Sequelize.STRING
});

sequelize.sync().then(function(){
    Test.create( { name: 'test' + Math.random() }).then( function( test ){

        var count = 0;
        _.times( 10, function( index ){
            process.nextTick(function(){
                sequelize.transaction( function(){
                    return Test.findAll( { where: { id: test.id } }).then(function( item ){
                        console.log( 'find item', ++count );
                    });
                });
            });
        });
    });
});
``` 

If you run this snap, nothing will be output, the `findAll`s are pending...what even confused me more is if you change the loop time to `4`, the program will just works fine, or you can replace the `nextTick` with `setTimeout` and set a long interval, which will also make it work.

------------

work with sequelize 2.0.6 , MySQL 5.5.33, OSX

**Comment by janmeier** [comment]
This is probably because you are reaching the max number of connections - the default is 5. Each transaction is holding on to its own connection for as long as it runs, so if you are trying to create more transactions than the max number of connections the program will stall - since you are never comitting the transaction

Try with 
```js
config = {
  ...
  pool: {
     max: 20
  }
}
```

As an aside, you are not passing the transaction to the `findAll` call, so it will be executed outside the transaction

**Comment by mickhansen** [comment]
@janmeier he's using managed transactions though should they should be committing and cleaning up on their own.

**Comment by janmeier** [comment]
@mickhansen The findall is not using the transaction, which means it tries to obtain a new connection - but all connections ar ealready in use by the transactions so the findAll stalls, meaning the promise returned to the transaction is never resolved :)

**Comment by mickhansen** [comment]
Ah yeah that's true, @neekey does it work if you use the transaction in the findAll call?

**Comment by neekey** [comment]
@mickhansen Yes, get all the findAll calls involved into the transaction will fix this problem!

**Comment by mickhansen** [comment]
@neekey well then it's working as expected.

**Comment by DenisGorbachev** [comment]
@neekey Could you please post the code that worked for you?
