### ISSUE TITLE
Error while truncating table with schema

### ISSUE THREAD

**Issue by chanakyap** [sequelize/sequelize#3580]
I have set schema(users) to my model(User) like this
sequelize.define('User', /\* attributes*/).schema('users');
when i use sync() , the query was something like 
create table if not exists "users"."users",
but when i do User.destroy({truncate: true}), the query looks like this 
truncate "users.users"
which throws an error 
relation "users.users" does not exist
i am using postgresql and sequelize 2.0.5

**Comment by mickhansen** [comment]
Thanks for the report, appears to be a bug.
Does it work if you use `.define('Name', attributes, {schema: 'users'})`?

**Comment by chanakyap** [comment]
@mickhansen  Initially i tried with the above code, same error.

**Comment by derrickpelletier** [comment]
Just came here to say i'm seeing the same issue :+1:

**Comment by JMTyler** [comment]
On v2.0.3, I fixed this locally by changing dialects/postgres/query-generator.js:404 from
`query = 'TRUNCATE ' + QueryGenerator.quoteIdentifier(tableName);`
to
`query = 'TRUNCATE ' + this.quoteIdentifiers(tableName);`

Not sure if this is the absolute best solution, so I'll leave the PR up to someone more familiar with the codebase, but hopefully this might give you a better starting point.

**Comment by janmeier** [comment]
@JMTyler I think that would be a fine solution I think

**Comment by mickhansen** [comment]
`quoteTable` would probably be the ideal.
