### ISSUE TITLE
toJSON (aka .get({plain: true})) leaves off NULL values

### ISSUE THREAD

**Issue by andrewjmead** [sequelize/sequelize#3583]
I have a due date fields that's defined like this:

```
 dueDate: {
    type: Sequelize.DATE,
    allowNull: true
}
```

When I create the object, I call `toJSON` on the instance. While it does include my other fields, it leaves off my null dueDate field (allowed to be null if there is no due date).

I dug through the documentation, but I was unable to find any example of this. Is there anyway to keep the null fields on the instance without manually checking (trying to keep it DRY).

**Comment by mickhansen** [comment]
`null` values should be included, and they usually are when i use them in projects.
There's no code that should account for them not being included either.

Can you post a full example that shows your issue?

**Comment by andrewjmead** [comment]
@mickhansen It looks like it might be related to the `Sequelize.DATE` type and how Sequelize handles that. Even when I had a valid date value in the database I wasn't getting any field back from `toJSON`. 

I create a `get` override for the `dueDate` field calling `date.getTime()` and returning that value instead. Seems to be working now, I just couldn't find anything in the documentation about how the DATE type works.

**Comment by mickhansen** [comment]
@andrewjmead it should just be returning a `Date` instance which should get converted to a ISO timestamp by `toJSON`.

**Comment by andrewjmead** [comment]
@mickhansen Okay, maybe there is a bug here after all. I'll post a complete code sample.

**Comment by BridgeAR** [comment]
Ping @andrewjmead
