### ISSUE TITLE
Instance.updateAttributes( { ... } ) syntax error

### ISSUE THREAD

**Issue by anselmo** [sequelize/sequelize#3586]
__context__:
db: postgres
transpiler: babel-node

Occurs on updating an instance ... 

Quick stack trace lookup points to a lodash (template?) syntax error.

Wondering if it's related to lodash upgrade:
-  "lodash": "~2.4.0",  
+ "lodash": "~3.5.0",  

*_previous sequelize works perfectly fine_

stack trace ..
```
error +24ms SyntaxError: Unexpected token =
    at Function (<anonymous>)
    at {edited}/node_modules/lodash/index.js:10693:16
    at {edited}/node_modules/lodash/index.js:10966:21
    at {edited}/node_modules/lodash/index.js:8120:31
    at Function.template (node_modules/lodash/index.js:10692:20)
    at Object.module.exports.QueryGenerator.updateQuery {edited}/node_modules/sequelize/lib/dialects/abstract/query-generator.js:349:22)
    at [object Object].module.exports.QueryInterface.update ({edited}/node_modules/sequelize/lib/query-interface.js:585:35)
    at [object Object].<anonymous> ({edited}//node_modules/sequelize/lib/instance.js:651:43)
    at tryCatch1 ({edited}//node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler ({edited}/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
SyntaxError: Unexpected token =
    at Function (<anonymous>)
    at {edited}//node_modules/lodash/index.js:10693:16
    at {edited}//node_modules/lodash/index.js:10966:21
    at {edited}//node_modules/lodash/index.js:8120:31
   ..... 
```

**Comment by mickhansen** [comment]
Can you show the relevant models, values and calls that triger the error?

**Comment by alexduan** [comment]
I am also using Postgres, and I get this error when setting (not creating) an associated object.

For instance, my code:

```
var sessionId = uuid.v4();
var token = uuid.v4();

var session = {
    session_id: sessionId,
    token: token,
    expires: new Date //i know this logic is wrong...
};

var s = yield user.getSession();
if(s) {
    return yield user.setSession(session);
} else {
    return yield user.createSession(session);
}
```
When setting the session, it generates this SQL:

Executing (default): UPDATE "sessions" SET "id"=`session_id` = '21074f1c-0ad8-49e8-9f40-a7319536983f', `token` = '4957f9f0-bbfb-4cb2-afa0-93db070044bc', `expires` = '2015-05-04 18:28:22.558 +00:00',"user_id"=1,"updated_at"='2015-05-04 18:28:22.586 +00:00' WHERE ("id" = `session_id` = '21074f1c-0ad8-49e8-9f40-a7319536983f' AND "id" = `token` = '4957f9f0-bbfb-4cb2-afa0-93db070044bc' AND "id" = `expires` = '2015-05-04 18:28:22.558 +00:00')

  SequelizeDatabaseError: syntax error at or near "=`"

In PostgreSQL 9.4:

UPDATE "sessions" SET "id"=`session_id` = '21074f1c-0ad8-49e8-9f40-a7319536983f', `token` = '4957f9f0-bbfb-4cb2-afa0-93db070044bc', `expires` = '2015-05-04 18:28:22.558 +00:00',"user_id"=1,"updated_at"='2015-05-04 18:28:22.586 +00:00' WHERE ("id" = `session_id` = '21074f1c-0ad8-49e8-9f40-a7319536983f' AND "id" = `token` = '4957f9f0-bbfb-4cb2-afa0-93db070044bc' AND "id" = `expires` = '2015-05-04 18:28:22.558 +00:00');
ERROR:  syntax error at or near "=`"
LINE 1: UPDATE "sessions" SET "id"=`session_id` = '21074f1c-0ad8-49e...

**Comment by janmeier** [comment]
@alexduan setSession expects a built session instance, the session data you are trying to save with setSession does not have an ID and thus the query fails
