### ISSUE TITLE
hasMany's addMultiple association does not fetch already associated items

### ISSUE THREAD

**Issue by simong** [sequelize/sequelize#3592]
Assuming a hasMany associations between `User` and `Task` you should be able to do:
* `user.addTask(taskA);`
* `user.addTask(taskA.id);`
* `user.addTasks([taskA]);`
* `user.addTasks([taskA.id]);`

**even if taskA is already associated with the user**.

Currently, this doesn't seem to be the case for `addTasks`. There's no logic (afaict) that is checking the existing associations and filtering these out. This obviously triggers a `SequelizeUniqueConstraintError` when adding a task that's already associated with the user.

Here's a test case that demonstrates the issue
```
diff --git a/test/integration/associations/belongs-to-many.test.js b/test/integration/associations/belongs-to-many.test.js
index 2b9a0d1..a66236a 100644
--- a/test/integration/associations/belongs-to-many.test.js
+++ b/test/integration/associations/belongs-to-many.test.js
@@ -846,6 +846,20 @@ describe(Support.getTestDialectTeaser('BelongsToMany'), function() {
           return this.task.getUsers();
         }).then(function(users) {
           expect(users).to.have.length(3);
+
+          // Re-add user 0's object, this should be harmless
+          return this.task.addUsers([this.users[0]]);
+        }).then(function() {
+          return this.task.getUsers();
+        }).then(function(users) {
+          expect(users).to.have.length(3);
+
+          // Re-add user 0's id, this should be harmless
+          return this.task.addUsers([this.users[0]]);
+        }).then(function() {
+          return this.task.getUsers();
+        }).then(function(users) {
+          expect(users).to.have.length(3);
         });
       });
     });
```

**Comment by slawo** [comment]
OK, I will post here instead.

Wouldn't it be better to leave the current behaviour on Add[foreign]s() and implement AddMissing[foreign]s() to make sure this behaviour is kept (we might want to fail on Add if some associations are already made) and we might to make sure we are adding only new relations if the association can have the same relations setup multiple times...

**Comment by slawo** [comment]
Will this be fixed soon in the main branch?

**Comment by janmeier** [comment]
@slawo Yes, I'm mostly just waiitng for #3745 to be merged since there are some changes to hasmany in that
