### ISSUE TITLE
MSSQL Query doesn't execute

### ISSUE THREAD

**Issue by Sk1Zy** [sequelize/sequelize#3595]
Might be related to #3114 

I'm trying to execute a raw query against an mssql database. This same query works fine against mysql.

```
    sequelize.query(sequelize.getQueryInterface().QueryGenerator.showTablesQuery(), null, {raw: true})
    .catch(function(err){
      console.log('ERR: ' + err);
    })
    .spread(function(tables){});
```
I have set sequelize to log to the console but nothing gets logged and the process just exits. Nothing comes from the catch or the spread blocks.

**Comment by janmeier** [comment]
Do regular queries work?

Without more information it is hard to for us to debug this further. Perhaps you'll have to dig into the mssql connection code to see exactly where the query is lots

**Comment by mbroadst** [comment]
@Sk1Zy can you provide the full test case you are running (including database setup and connection), and also give us some information on what version of MSSQL you are attempting to test this against?

**Comment by Sk1Zy** [comment]
I'll do some experimenting and report back later this week.

**Comment by Sk1Zy** [comment]
It seems to work correctly in another project I'm working on. Can get data using findAll and query() on that database. 

I am attempting to get sequelize-auto to work with sequelize 2 so you can view the code here: https://github.com/sequelize/sequelize-auto/blob/master/lib/index.js

Querying mysql after upgrading to sequelize 2 works fine its just mssql that's causing the problem it seems. Haven't tested it against any other databases.

**Comment by janmeier** [comment]
Closing, since the author has provided no further feedback
