### ISSUE TITLE
[Question] Atomic transaction for concurrent write

### ISSUE THREAD

**Issue by nicolabortignon** [sequelize/sequelize#3603]
Hi all,
I have n-threads doing the following operation:

- look up a User Table for a specific User.username
   - if the user doesn't exist, create one and get the ID
   - if the user exists, get the ID
  
   - add an association on another NxN table by Product.addUser(user.id).

Now, the problem that i have is that the race condition on the table, is not atomic, and i may have 4 threads that concurrently try to look up the table, don't find the user, and create the user.

How can i avoid this by using sequelize api (i can rewrite the concurrency scheme, but i may loose some parallelism)

**Comment by janmeier** [comment]
Have you looked at findOrCreate ? http://docs.sequelizejs.com/en/latest/docs/models/#findorcreate-search-for-a-specific-element-or-create-it-if-not-available http://docs.sequelizejs.com/en/latest/api/model/#findorcreateoptions-queryoptions-promiseinstancecreated

**Comment by nicolabortignon** [comment]
I completely overlooked that part of the API.
It seams it exactly solve my problem.
Going to give it a try right now!

Thank you for the quick answer

**Comment by nicolabortignon** [comment]
Unfortunately this doesn't solve the problem. 
Do we know if the if findOrCreate is atomic? 

From a bit of loggin, it doesn't seams to me

**Comment by mickhansen** [comment]
@nicolabortignon It's as atomic as can be. They are running in seperate transactions. They will attempt to SELECT, then if not found, INSERT, if insert hits a unique violation do a find again.

Of course this all requires that you are `findOrCreate`'ing on unique keys.
If not you might want to cook up your own solution with aggressive locking.

**Comment by nicolabortignon** [comment]
By 'unique keys' do you mean at a database level, or as a business logic level?
In my case i'm checking on a String column that is not the key.

I'm happy to implement an aggressive locking solution. Any suggestion on the design?  I'd like to maintain the parallelism.

**Comment by mickhansen** [comment]
At the database levels, `findOrCreate` works under concurrency only in the cases that it operates on unique constraints.

I'm honestly not an expert on locking but you want to find something, or get as close to, a locking level that locks the entire table untill the transaction is committed. This likely depends on the database you are using.

**Comment by janmeier** [comment]
The most useful here would probably be to select for update `model.find({ where: where, transaction: t, lock: t.LOCK.UPDATE })`
