### ISSUE TITLE
Getting parent category object with SequelizeJs

### ISSUE THREAD

**Issue by codebased** [sequelize/sequelize#3604]
I have a model defined as:

```js
var Post = sequelize.define("Post", {
        title: DataTypes.STRING,
        description: DataTypes.TEXT
       }, {
        classMethods: {
            associate: function (models) {
                Post.belongsTo(models.Category, {as: 'category', foreignKey:'categoryId'});
            }
        }
    });
```
And then the category model as :

```js
var Category = sequelize.define("Category", {
        code: DataTypes.STRING,
        description: DataTypes.STRING,
        img: DataTypes.STRING,
    }, {
        classMethods: {
            associate: function (models) {
                Category.hasOne(models.Category, {as: 'parent', foreignKey: 'parentId'});
            }
        }
    });
```
As you can see that the post belongs to one category, which can be a parent or a child category.

Each category can have only one parent category.

Now what I want is to get the parent category if it exists. I can go to N number level. However I am happy that if it works only at one level i.e.

Category - Jobs Sub Category - IT

Now when I have a post that belongs to IT then I want to get the category object as IT but at the same time IT Category object must have an another object of Category Job record.

Currently I can only get the sub category as :

```js
app.db.sequelize.models.Post.findAll({
                where: ['"Post".id = ?', postId],
                include: [
                    {model: app.db.sequelize.models.Category, as: 'category'},
                ]
            }).then(function (post) {
                res.send({post: post});
            }) 
```

**Comment by janmeier** [comment]
```js
Post.findAll({
  where: ['"Post".id = ?', postId],
  include: [
    { 
      model: Category, 
      as: 'category', 
      include: [
        { model: Category, as: 'parent' }
      ]
    },
  ]
});
```

Please format your issue properly with github markdown

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
