### ISSUE TITLE
Sequelize join query with condition

### ISSUE THREAD

**Issue by deepak-manwal** [sequelize/sequelize#3609]
I am using following syntax for selecting record:

    models.account.findAll({
        attributes: ['password'],
        include: [{
                model: models.user,
                as : 'user'
        }],
        where: {
            'password': password,
            'user.email': email
            }
    }).then(function(res){
        console.log(res);
    });

Its generating following query:

    SELECT * 
    FROM   `accounts` AS `account` 
           LEFT OUTER JOIN `users` AS `user` 
                        ON `account`.`user_id` = `user`.`id` 
    WHERE  `account`.`password` = 'PASSWORD' 
           AND `account`.`user.email` = 'xyz@gmail.com';
               ^^^^^^^^^^^^^^^^^^^^^^

So its giving me error: `Unknown column 'account.user.email' in 'where clause'`. I want only `user.email`. Expected query is following:

    SELECT * 
        FROM   `accounts` AS `account` 
               LEFT OUTER JOIN `users` AS `user` 
                            ON `account`.`user_id` = `user`.`id` 
        WHERE  `account`.`password` = 'PASSWORD' 
               AND `user`.`email` = 'xyz@gmail.com';

What am i doing wrong???

**Comment by janmeier** [comment]
Add the where clause to the include instead
```js
    include: [{
            model: models.user,
            as : 'user',
            where: { email: email }
    }],
```

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
