### ISSUE TITLE
Custom unique message not set

### ISSUE THREAD

**Issue by xpepermint** [sequelize/sequelize#3610]
Hey. I have a simple model with an email and a custom error message for it.

```js
module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define('User', {
    name: DataTypes.STRING,
    email: { type: DataTypes.STRING, unique: { msg: 'already exists' }}
  });
  return User;
};
```

If I try to create a duplicate I get this:

```json
{"name":"SequelizeUniqueConstraintError","message":"already exists","errors":[{"message":"email must be unique","type":"unique violation","path":"email","value":"test@domain.com"}],"fields":{"email":"test@domain.com"}}
```

Check the `errors[0].message` value. It should be `already exists` instead of `email must be unique`.

**Comment by janmeier** [comment]
Validation error items (which is what is in `.errors`) always have the default message - but `.message` holds your message `,"message":"already exists"`

**Comment by editcue** [comment]
Check out this link , it may be helpful for you .
https://github.com/angelxmoreno/sequelize-isunique-validator
