### ISSUE TITLE
Filter by string length.

### ISSUE THREAD

**Issue by sandokanelcojo** [sequelize/sequelize#3618]
Hi there:

MySQL provides [CHAR_LENGTH()](http://dev.mysql.com/doc/refman/5.0/en/string-functions.html#function_char-length) to filter by string length .

Is there a way to do the same in Sequelize other than using a raw query?

Thanks in advance.

**Comment by janmeier** [comment]
Probably something like 

```js
Model.find({
  where: sequelize.where(sequelize.fn('CHAR_LENGTH', sequelize.col(column)), /* right hand side of the comparison here, eg > 12 */{ $gte: 12 })
});
``` 

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by anuxs** [comment]
this is a usefull feature request

**Comment by viditkothari** [comment]
Isn't $gte deprecated in latest Sequelize (v5) ? How to go about it?

**Comment by bmovement** [comment]
This section in the docs was helpful to me: https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#advanced-queries-with-functions-not-just-columns
