### ISSUE TITLE
What is the 2.1.0 alternative to using "on('sql')" ?

### ISSUE THREAD

**Issue by phtrivier** [sequelize/sequelize#3619]
The 2.1.0 release removed the event handling (apparently to support io.js or newer versions of bluebird ?)

We used 'on(sql)' on Promises to track the various sql queries that could be sent by a single sequelize function call (for performance tuning.)

The way we handled that was by wrapping all db functions that generated a Promise, and listen to the 'sql' elements (so it's in a fairly generic part of our codebase, and the only assumptions was that the wrapped function returned a sequelized-produced Promise.)

Is there still a way to get notified of all sql queries "hidden" behind a single function call ?

Thanks

**Comment by janmeier** [comment]
The way to do this now is to pass a logging function to each call:

```js
Model.findAll({ ...}, { logging: fn })
```

This could be made more abstract with something like https://github.com/sequelize/sequelize/issues/3535

**Comment by phtrivier** [comment]
#3535 is unfortunately not an options since we're still using es5. 

It the 'logging' feature available of all types of query (find, update, etc...) ? Is what the function returns documented somewhere ? 

Thanks !

**Comment by mickhansen** [comment]
@phtrivier CLS works on ES5.
`logging` should be available on all methods yes. It takes a method that receives the same arguments as `on('sql')` did previously.

**Comment by BridgeAR** [comment]
It is avaible for all querys. If you want to use a global function, just pass logging to the sequelize options. That way you can look for individual querys by using somthing like:

```javascript
logging: function(sql) {
   if (sql.indexOf('ALTER') !== -1) { ...}
}
```

**Comment by janmeier** [comment]
I believe the logging function is actually called with 'Executing (conn id) : sql'..
