### ISSUE TITLE
Documentation for include option in call to Instance.set.

### ISSUE THREAD

**Issue by juanjoLenero** [sequelize/sequelize#3622]
I'm trying to create an instance of a model along with an association.

I believe the ```include``` option in ***Model.prototype.build*** which is passed on to ***Instance.prototype.set*** will be of help, but currently there is no documentation about its use that I can find.

I'm trying to do something like this:
```javascript
var User = sequelize.define('User', {
    name: DataTypes.STRING,
});

var Task = sequelize.define('Task', {
    name: DataTypes.STRING,
});

var UserTask = sequelize.define('UserTask', {
    isCompleted: DataTypes.BOOLEAN,
})

User.belongsToMany(Task, {as: 'tasks', through: UserTask});
Task.belongsToMany(User, {as: 'users', through: UserTask});


// On some handler method.
task.build({name: 'Work'}, {
    include: [{
        model: UserTask, values: {isCompleted: true, UserId: req.user.id}
    }]
});

// Creates the task and the association.
task.save();
```

**Comment by mickhansen** [comment]
There's some here: https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L271
It looks like you want nested creation though: https://github.com/sequelize/sequelize/pull/3386

But generally the syntax is:
```js
Task.build({
  name: 'Work',
  user: req.user
}, {
  include: [{model: User, as: 'users'}]
});
```

I don't believe we support setting join table values with nested creation at the moment, but you can test it out.
