### ISSUE TITLE
Adding limit: to findAll() DESTROYS the query

### ISSUE THREAD

**Issue by DelvarWorld** [sequelize/sequelize#3623]
I'm trying to return a group of `Model`s, paginated using `limit` and `offset`, including the grouped count of that model's favorites. A fairly trivial thing to attempt.

Here's my basic query setup with sequelize:

    var perPage = 12;
    var page = 1;

    return Model.findAll({

        group: [ 'model.id', 'favorites.id' ],
        attributes: [
            '*',
            [ Sequelize.fn('count', Sequelize.col('favorites.id')), 'favorites_count' ]
        ],
        include: [
            { attributes: [], model: Favorite },
        ],
        offset: perPage * page

This generates the (fairly) expected query:

    SELECT          "model"."id",
                    "model".*,
                    Count("favorites"."id") AS "favorites_count",
                    "favorites"."id"        AS "favorites.id"
    FROM            "model"                 AS "model"
    LEFT OUTER JOIN "favorite"              AS "favorites"
    ON              "model"."id" = "favorites"."model_id"
    GROUP BY        "model"."id",
                    "favorites"."id" offset 12;

Ignoring the fact that it quotes the tables, and that it selects `favorites.id` (forcing me to add it to the group by clause), and that it has randomly aliased things to their exact name or to a nonsensical name like `"favorites.id"` (all undesired), it seems to have worked. But now let's complete the pagination and add the limit to the query:

    ...
    offset: perPage * page
    limit: perPage

It now generates this query:

    SELECT "model".*,
        "favorites"."id" AS "favorites.id"
    FROM   (SELECT "model"."id",
                "model".*,
                Count("favorites"."id") AS "favorites_count"
            FROM   "model" AS "model"
            GROUP  BY "model"."id",
                    "favorites"."id"
            LIMIT  12 offset 12) AS "model"
        LEFT OUTER JOIN "favorite" AS "favorites"
                        ON "model"."id" = "favorites"."model";

In completely baffling behavior, it has generated an inner query and applied the limit only to that, then aliased that as `"model"`.

As a sanity check I looked in the docs for findAll, but the docs [do not seem to think that command exists](https://readthedocs.org/elasticsearch/?q=findall&type=file&project=sequelize&version=latest).

I suspect I am doing something wrong, but I can't figure out what it is. This behavior is quite bizzarre, and I'm hoping my sleep deprivation is the cause of my confusion. 

I'm using version `2.0.6`

**Comment by janmeier** [comment]
Adding a limit to the outer query would limit the number of joined rows, not the number of `model` rows - thus we first have to select the 12 models rows in an inner query, and then join them up with their related favorites. 

The count ends up in the wrong place, but we need the inner query in order to do limit correctly

**Comment by DelvarWorld** [comment]
I don't understand why the inner query is generated. Adding `limit` to the original query would achieve the desired result. I also don't see why `offset` behaves in a predictable way while `limit` seems to trigger a fundamental change in the logic, even though it's just a simple tack-on to the end of any query.

**Comment by mickhansen** [comment]
> Adding limit to the original query would achieve the desired result
No it wouldnt, not if any of the joins are row-duplicating (which we assume with 1:M or N:M relationships?.

Have you ever tried writing a query manually with a row duplicating join and appending the LIMIT clause? It's effectively worthless (in terms of limiting the main row atleast).

**Comment by mickhansen** [comment]
It dawns on me that you are doing an aggregate and simply ignoring the attributes from the joined table.
And in that case, you are right, the LIMIT could simply be appended, but i'm afraid Sequelize is not smart enough to detect that case at the moment.

We have however had a few discussions about providing a `subQuery: false` flag to the query to turn off the subquery behaviour manually when absolutely needed.

**Comment by janmeier** [comment]
Subquery: false will be covered here https://github.com/sequelize/sequelize/pull/3671

**Comment by krisr** [comment]
As someone who is comfortable with SQL and ORMs, I was surprised by this behavior as well. In my particular case, it actually generated invalid SQL that postgres chocked on. I don't have the time to dig into why at the moment, but I will if the problem persists after your refactor.

**Comment by krisr** [comment]
In my case, the subquery was also generated with incorrect limit semantics.

I had a model setup like

    Parent
        belongsToMany(Child, through ParentChild)
     Child
        belongsToMany(Parent through ParentChild)
        belongsToMany(subChild, through ChildSubChild)
     SubChild
        belongsToMany(Child, through ChildSubChild)

And a query like:

    Parent.getChildren({
        include: {
            model: SubChild,
            where: {id: {$in: [...]}}
        },
        limit: 10
    })

The resulting query came out like:

    SELECT 
        Child.*, SubChild.*
    FROM 
        (SELECT
            Child.*, Parent.* FROM Child.* INNER JOIN ParentChild ...  WHERE  .... LIMIT 30)
    INNER JOIN
         ChildSubChild
         INNER JOIN
             SubChild ... SubChild.id in [....]
    LIMIT 30

So it was limiting the result set before applying the final filter on SubChild - (in my case, SubChild is a form of categorization  / tagging).

**Comment by krisr** [comment]
@mickhansen, you might consider breaking complex queries with joins into two parts. This is how I've done it in some of the ORMs I've co-authored.

For example, the first part would be a query that selects the "distinct" top level ids that you are trying to limit, and only those ids. The "distinct" modifier should result in the proper limit being applied.

You can then select from that query to merge in all the additional fields and associations without any limit.

**Comment by mickhansen** [comment]
@krisr I plan to start working on a `seperate: true` feature for includes soon that would allow a user to split that part of the tree into a seperate query, for performance and fixes.
