### ISSUE TITLE
Cannot define a function as a defaultValue

### ISSUE THREAD

**Issue by fabulouslord** [sequelize/sequelize#3625]
I was wondering if this is possible somehow, my use case is generating a secret key for an application model whenever it's instantiated, however the defaultValue function seems to be evaluated once and not whenever a new instance is created, is there a way to do so?

    module.exports = function(sequelize,DataTypes){
        var Application = sequelize.define('Application',{
            name: {
                type : DataTypes.STRING,
                unique : true,
                validate : {
                    len : [2,32]
                },
                allowNull : false
            },
            secret : {
                unique : true,
                type : DataTypes.STRING,
                allowNull : false,
                defaultValue : function(){
                    // Create new token
                    var tokenContents = {
                        id: this.getDataValue('id'),
                        type : 'app'
                    };
    
                    var token = jwt.sign(tokenContents, cert);
    
                    this.setDataValue('secret',token);
                }
            }
        });
    
        return Application;
    };

**Comment by janmeier** [comment]
Try returning from the function instead of setting the data value - setDataValue is meant for setter functions

**Comment by fabulouslord** [comment]
I tried that first, however seems that the function is evaluated only once at bootstrap runtime meaning that I can't access instances attributes from within as the id,name,etc. 

For completeness, here's the first thing that I tried.

    module.exports = function(sequelize,DataTypes){
        var Application = sequelize.define('Application',{
            name: {
                type : DataTypes.STRING,
                unique : true,
                validate : {
                    len : [2,32]
                },
                allowNull : false
            },
            secret : {
                unique : true,
                type : DataTypes.STRING,
                allowNull : false,
                defaultValue : function(){
                    // Gets evaluated once at bootstrap runtime.
                    
                    // TypeError : Cannot read property 'id' of undefined.
                    var tokenContents = {
                        id: this.id,
                        type : 'app'
                    };
                    return jwt.sign(tokenContents, cert);
                }
            }
        });
    
        return Application;
    };

**Comment by janmeier** [comment]
The default function is run each time you create a new instance - but yes you cannot access other instance attributes, because they are not available yet.

The default value function is run when you call `Model.create`, but the id is not assigned before instance hits the database. 

If you need to create the token based on the id you should create it in an `afterCreate` hook

**Comment by fabulouslord** [comment]
Thanks Jan, that works out. 

Cheers.
