### ISSUE TITLE
destroy() generates incorrect primary key for SQL

### ISSUE THREAD

**Issue by kirill-zhirnov** [sequelize/sequelize#3626]
Model

``` coffeescript
module.exports = (sequelize, DataTypes) ->
    return sequelize.define 'productCategoryRel', {
        category_id:
            type: DataTypes.INTEGER
            primaryKey: true

        product_id:
            type: DataTypes.INTEGER
            primaryKey: true

    }, {
        tableName: 'product_category_rel'
    }
```

``` coffeescript
row.destroy()
```

Generates sql:

``` sql
DELETE 
FROM "product_category_rel" 
WHERE ("category_id","product_id") IN (
SELECT 
    "category_id","product_id" 
FROM 
    "product_category_rel" 
WHERE 
    "category_id" = 26 LIMIT 1
)
```

Here is 2 issues:
1) Sub query should be (since primary key has 2 fields: category_id and product_id):

``` sql
where "category_id" = 26 and "product_id"=5 limit 1
```

2) Is it possible to delete without Sub-query by primary key?

Thank you!

**Comment by mickhansen** [comment]
Sequelize has poor composite primary key support i'm afraid.

**Comment by janmeier** [comment]
For sequrity reasons we delete with limit one when destroying a single row. Postgres does not allow limit on DELETE http://www.postgresql.org/docs/9.0/static/sql-delete.html, so we must first select, then delete

**Comment by mickhansen** [comment]
@janmeier That is true however generally we only apply limit if WHERE does not include a primary key (so normally instance.destroy()) wont use limit, but it doesn't appear to work for composites. (no idea if () IN () is valid syntax actually)

**Comment by janmeier** [comment]
Ah yeah that's right - I believe the IN is correct syntax, but the subquery is wrong :)

**Comment by derrickpelletier** [comment]
I'm getting this same issue, but not with composite primary keys.

when i run the following code, the SQL generated is incorrect.

#### attempted code
```javascript
instance.destroy().nodeify(cb);
```

#### erroring SQL
```
Executing (default): DELETE FROM "derrick"."clients" WHERE "id" IN (SELECT "id" FROM "derrick"."clients" WHERE "client_id" = 60 LIMIT 1)
```

#### definition
```javascript
sequelize.define('client', {
  id: {
    field: 'client_id',
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  name: {
    field: 'client_name',
    type: Sequelize.STRING,
  },
}, {
  schema: 'derrick',
  tableName: 'clients'
});
```

**Comment by mickhansen** [comment]
@derrickpelletier That appears to be an issue with the `field` settings.

**Comment by derrickpelletier** [comment]
as in i've done it incorrectly, or it's a bug?

**Comment by mickhansen** [comment]
bug :)

**Comment by ORESoftware** [comment]
bug :)

**Comment by ORESoftware** [comment]
bug
