### ISSUE TITLE
Timezone Questions

### ISSUE THREAD

**Issue by khwerhahn** [sequelize/sequelize#3627]
Hi,

I'm new to sequelize and I have a question about models and timezones. I use postgres and would like, that every date that is saved to the database is converted to UTC. Is this possible without using hooks?

I understand that I can set the options timezone='+00:00'. I'm not entirely sure, what it will do exactly.

**Comment by janmeier** [comment]
The default value for options.timezone is `'+00:00'` as you noticed = UTC. So by default dates will be inserted as UTC

**Comment by khwerhahn** [comment]
It still adds +2 behind the timestamps (I'm in that timezone). Is this the correct behaviour? I would like, that it converts it into UTC so that the db only works in that timezone.

**Comment by janmeier** [comment]
What version are you on?

Have you checked the data in the DB / looked at the log to see what is inserted? If you just console.log the date it will always be shown in your local timezone

**Comment by khwerhahn** [comment]
Latest.

Lets say I use something like this:

```
var DateStart = moment("2015-03-01 08:03:54.182+01").format();
```

Instead of converting it into utc it stores it as _2015-03-01 08:03:54.182+01_. Is there no way sequelize converts any timezone into utc before saving automatically?

**Comment by janmeier** [comment]
`moment.format()` returns a string - sequelize doesn't do anything to that.

If you pass a JS date object, sequelize will handle it accordingly

**Comment by khwerhahn** [comment]
I have set 

```
timezone: '+00:00',
```
but somehow it still saves the timestamps with +1 or +2... shouldn't sequelize convert them to utc?

Still a bit confused. This timezone stuff is horrible.

**Comment by mickhansen** [comment]
@khwerhahn are you saving native dates? As @janmeier states moment returns strings, not `Date` objects.

If you are saving a string, it's up to your database to interpret that, and the Sequelize timezone won't matter.

**Comment by khwerhahn** [comment]
@mickhansen Thanks for the clarification. So I would save the moment() object?
```
var newrow = {
 somedate: moment(variable)
}
```
Or what would it look like?

**Comment by janmeier** [comment]
You have to pass a javascript date object - you can use `toDate` on the moment object

**Comment by khwerhahn** [comment]
@janmeier thx!
