### ISSUE TITLE
beforeDestroy and afterDestroy hooks not working 

### ISSUE THREAD

**Issue by haikyuu** [sequelize/sequelize#3628]
Here is what i tried : 
```javascript

var User = sequelize.define('user', {
  firstName: Sequelize.STRING,
  lastName: Sequelize.STRING
}, {
  hooks: {
    beforeDestroy: function(instance, options, cb) {
      console.log('before destroy');
      return cb();
    },
    afterDestroy: function(instance, options, cb) {
      console.log('after destroy');
      return cb();
    },
    beforeCreate: function(instance, options, cb) {
      console.log('before Create');
      return cb();
    },
    afterCreate: function(instance, options, cb) {
      console.log('after Create');
      return cb();
    }
  }
});


sequelize.sync({
  force: false
}).
then(function() {
  User.create({
    firstName: 'e',
    lastName: 'e'
  }).then(function(user) {
    return User.destroy({
      where: {
        id: user.id
      }
    });
  });
});
```

In the console : 
before Create
Executing (default): INSERT INTO `users` (`id`,`firstName`,`lastName`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'e','e','2015-04-29 15:41:46','2015-04-29 15:41:46');
after Create
Executing (default): DELETE FROM `users` WHERE `id` = 7

**Comment by janmeier** [comment]
Before and after destroy is invoked when destroying a single instance 

Use before and after bulkDestroy instead or pass individualHooks: true to destroy

**Comment by haikyuu** [comment]
Thanks for the quick reply

**Comment by angelxmoreno** [comment]
I would like to add this since it could be useful:

To set individualHooks to default to true ( so that you don't have to go back and manually add the params on every call to `Model.destroy()` )
```js
beforeBulkDestroy: function(options){
    options.individualHooks = true;
    return options;
}
```

**Comment by Shimon-Technext** [comment]
hi, was looking out for the similar issue, but the typing is a function that returns void/promise that resolves with void value. but you clearly are returning the options object back. is that necessary ? or just modifying `individualHooks` is enough ?

**Comment by doshishreyansh** [comment]
My hook beforeBulkDestroy is not getting called, can anyone help?

Query:
`await BookingDetails.destroy(
					{
						where: { id: detailsDeleteIds },
						userId: req.user.id, //passing to hook
						individualHooks: true,
					},
					{
						transaction: t,
					}
				`);``

Hook inside model:
`hooks: {
				beforeDestroy: async (instance, options) => {
					await instance.update({ updatedBy: options.userId });
				},
				beforeBulkDestroy: async (instance, options) => {
					await instance.update({ updatedBy: options.userId });
				},
			},`
