### ISSUE TITLE
SQLite with many findOrCreate: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by sdimit** [sequelize/sequelize#3629]
It seems that findOrCreate *eventually* hits some SQLite limit resulting in the SQLITE_CANTOPEN error, because of creating a new transaction each time.

**Comment by mickhansen** [comment]
The transactions should be committed and the connection cleaned up though. Are you running a lot in parrallel?

**Comment by sdimit** [comment]
This is actually what's really baffling: those findOrCreates are being run *serially*

**Comment by mickhansen** [comment]
@sdimit Hmm, that's odd, and commit is being called?

**Comment by sdimit** [comment]
yes indeed

**Comment by janmeier** [comment]
ping @sdimit

**Comment by adjoinant** [comment]
Is [this line](https://github.com/sequelize/sequelize/blob/master/lib/transaction.js#L219) the source of the issue?

Would seem that inside the the sqlite dialect of `ConnectionManager.prototype.releaseConnection` method, the `uuid` field needs to truthy for the `connection` to be closed properly. See [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/connection-manager.js#L55)

**Comment by freder** [comment]
*same* problem here.

I'm trying to create/update thousands of rows:

```js
const fs = require('fs');
const path = require('path');
const { connect } = require('../database.js');

// [...]

const { sequelize, Annotation } = connect('../database.db');

sequelize
	.authenticate()
	.then(() => {
		console.log('connection has been established successfully.');
	})
	.catch(err => {
		console.error('unable to connect to the database:', err);
	})
	.then(() => {
		dataFiles.forEach((dataFilePath) => {
			const imgFileName = path.basename(dataFilePath).replace(/\.json$/, '.jpg');

			Annotation.findOrCreate({ where: { fileName: imgFileName } })
				.spread((item, wasCreated) => {
					item.update({
						jsonData: fs.readFileSync(dataFilePath).toString()
					});
				});
		});
	});
```

---

on top of that I'm getting:

```
Unhandled rejection Error: EMFILE: too many open files, open 'path/to/data-file.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.Annotation.findOrCreate.spread
```
