### ISSUE TITLE
Getters/setters are ignored on .get<AssociatedModel>()

### ISSUE THREAD

**Issue by bblack** [sequelize/sequelize#3630]
This is on 1.7 branch. (Have not yet tested on sequelize 2).

For example: I have a `Beer` model that has many `Flavors`, and `Flavor` has a column called `name`, and a `name` getter function that appends a bunch of "!!!" to the end of the `name` column value. I have in my database a Beer record (id: 1, name: 'ipa') and a Flavor record (id: 99, name: 'hoppy', beer_id: 1).

If I do `Flavor.find(99).then(function(f){ return JSON.stringify(f); })`, the flavor name will be 'hoppy!!!'.
If I do `Beer.find(1).then(function(b){ return b.getFlavors(); }).then(function(f){ return JSON.stringify(f); })`, the flavor name will be 'hoppy'.

edit: I failed to specify that this was for json serialization.

**Comment by bblack** [comment]
I'll try to add code to reproduce, but I'll be pretty busy the next couple of days.

**Comment by janmeier** [comment]
Tested this on 2.0 and it works fine. 

You are welcome to provide a PR to the 1.7 branch to fix the issue, but unfortunately no-one from the core time will have time to look into it - we have plenty on our hands with 2.0
