### ISSUE TITLE
instance.updateAttributes executing not based on primaryKey

### ISSUE THREAD

**Issue by rbudiharso** [sequelize/sequelize#3634]
```javascript
db.LoyaltyPoint.find({
        where: {
          distributionId: transaction.distributionId,
        },
        attributes: ['id', 'distributionId', 'point', 'MerchantId', 'CustomerId', 'createdAt', 'updatedAt'],
        include: [ {model: db.Customer} ]
})
```

`loyalty.values` is
```javascript
{ id: 1,
  distributionId: '017610100853086680001001126595',
  point: 0,
  MerchantId: 2,
  CustomerId: 1,
  createdAt: Thu Apr 30 2015 17:41:08 GMT+0700 (WIB),
  updatedAt: Thu Apr 30 2015 17:41:08 GMT+0700 (WIB),
  Customer: { ... }
}
```

the code
```javascript
loyalty.updateAttributes({   
  point: 100
});
```

the query
```javascript
Executing (default): UPDATE "LoyaltyPoints" SET "point"=100,"updatedAt"='2015-04-30 10:41:08.663 +00:00' WHERE "CustomerId" = 1 AND "MerchantId" = 2
```

note that the query WHERE condition doesn't use the `id` but other fields, the result is all record that match that condition gets updated and not just that particular record.

Sequelize version 2.10, node 0.12.2, npm 2.7.4

**Comment by mickhansen** [comment]
What does the model definition for LoyalityPoint look like?

**Comment by rbudiharso** [comment]
The model definition for LoyaltyPoint
```javascript
module.exports = function(sequelize, DataTypes) {
  var LoyaltyPoint = sequelize.define("LoyaltyPoint", {
    distributionId: DataTypes.STRING,
    point: DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function(db) {
        LoyaltyPoint.belongsTo(db.Customer, {constraints: false});
        LoyaltyPoint.belongsTo(db.CardInventory, {constraints: false});
        LoyaltyPoint.belongsTo(db.Merchant, {constraints: false});
        LoyaltyPoint.hasMany(db.LoyaltyPointConversion, {constraints: false});
      }
    }
  });
  return LoyaltyPoint;
};
```

Thanks for the fast feedback :)

**Comment by mickhansen** [comment]
That's very odd. It should use the primary key for the where.

**Comment by rbudiharso** [comment]
That's what I thought, I've been looking in the Sequelize source code but still haven't found the problem.

**Comment by rbudiharso** [comment]
Ok, this is weird..
```javascript
db.LoyaltyPoint.find({
        where: {
          distributionId: transaction.distributionId,
        },
        attributes: ['id', 'distributionId', 'point', 'MerchantId', 'createdAt', 'updatedAt'],
        include: [ {model: db.Customer} ]
})
```
note in the `attributes` option I remove `CustomerId` and when `updateAttributes` is called this is the sql query, the `WHERE` changed to only `MerchantId`
```javascript
Executing (default): UPDATE "LoyaltyPoints" SET "point"=100,"updatedAt"='2015-04-30 11:16:54.121 +00:00' WHERE "MerchantId" = 2
```

and then I remove `MerchantId` from attributes option and running `updateAttributes` result in this sql query
```javascript
Executing (default): UPDATE "LoyaltyPoints" SET "point"=100,"updatedAt"='2015-04-30 11:17:13.043 +00:00'
```
There's no `WHERE` to be found

**Comment by mickhansen** [comment]
Seems like there's an issue with foreign key identification.

**Comment by rbudiharso** [comment]
I'm using postgres if it's any help.

**Comment by rbudiharso** [comment]
I can solve this by doing
```javascript
module.exports = function(sequelize, DataTypes) {
  var LoyaltyPoint = sequelize.define("LoyaltyPoint", {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,  // <= define an id field as primary key
      autoIncrement: true
    },
    distributionId: DataTypes.STRING,
    point: DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function(db) {
        LoyaltyPoint.belongsTo(db.Customer, {constraints: false});
        LoyaltyPoint.belongsTo(db.CardInventory, {constraints: false});
        LoyaltyPoint.belongsTo(db.Merchant, {constraints: false});
        LoyaltyPoint.hasMany(db.LoyaltyPointConversion, {constraints: false});
      }
    }
  });
  return LoyaltyPoint;
};
```
this changes makes sequelize correctly generate SQL query using the id as condition, but from what I understand sequelize will automagically add an id field as primary key if one is not defined, is it true? if it's not then should I add an id attribute on all model definition?

**Comment by mickhansen** [comment]
@rbudiharso The only case where it doesn't do that is in cases where the model is the join/through model for a N:M relation, i'm starting to think you're doing that?

**Comment by rbudiharso** [comment]
yes, that is exactly what the model is for, reading back the documentation I don't know how can I miss that part, my bad :)

**Comment by mickhansen** [comment]
@rbudiharso Alright, for a model like that you will need to specify the id primary key manually to turn off that functionality. (ideally i'd like to move all models to "id" by default but it's a BC break of a magnitude so)
