### ISSUE TITLE
myModel.create().success() throws error undefined is not a function

### ISSUE THREAD

**Issue by JohnCHarrington** [sequelize/sequelize#3636]
I'm using Sequelize 2.1.0 with mysql.

My model file currently looks like this:

```js
module.exports = (function(myModel) { // Injecting the Model
  return {
    // POST /mymodel
    postMyModel: function(req, res) {
      myModel.create({
        someField: 'someValue'
      }).success(function(mymodel) {  // Offending method call here
        res.json(mymodel);
      })
    }
  }
}
```

When I run this I get:
```TypeError: undefined is not a function```

at this point:
 ```
.success(
        ^
```

I was expecting to be able to use the ```success``` method to return data about the added field.

Am I doing something wrong? I have seen many examples doing ```myModel.create().success()``` and cannot work out what is happening to mine. Hopefully you can help?

**EDIT:** Just wanted to add that everything else is working fine and the values are added to the database as expected. Only the success call seems to have any problem.

**Comment by troyastorino** [comment]
Sequelize 2.x.x is based on promises, so you'd want to use `.then` instead of `.success`. I'm guessing you saw examples from Sequelize 1.x.x

Sequelize uses [Bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md) as its promise library.

**Comment by JohnCHarrington** [comment]
Ah, that makes sense. Thanks!

**Comment by mickhansen** [comment]
All events were removed in 2.1, no more success()/complete()/on etc.

**Comment by victorquinn** [comment]
Just noting here that the current live docs still reference .success in a whole bunch of places, [for example](http://sequelize.readthedocs.org/en/rtd/docs/models/#database-synchronization).

**Comment by BridgeAR** [comment]
@victorquinn the docs have to be generated again, true. But it's already [fixed] (https://github.com/sequelize/sequelize/blob/master/docs/docs/models-definition.md)
