### ISSUE TITLE
Sequelize and cls

### ISSUE THREAD

**Issue by haikyuu** [sequelize/sequelize#3644]
This is a continuation of [this.issue](https://github.com/othiym23/node-continuation-local-storage/issues/38) as suggested by @janmeier .
**Context**: i have an express app, and i want to track every request in order to trace its(*the user's*) actions on the database i.e create, update and delete.
[cls](https://github.com/othiym23/node-continuation-local-storage) and [hooks](http://sequelize.readthedocs.org/en/latest/docs/hooks/) to the rescue:
I created a namespace for each request and attached the username to it.Then i access every information related to the request from the hook and store it in the database.

**Issue**: unfortunately, patching the namespace with [cls-bluebird](https://github.com/TimBeyer/cls-bluebird) didn't work.
Here is a repo with a small reproducible test case https://github.com/haikyuu/test-cls-seq

**Comment by janmeier** [comment]
Aah there is one important detail here that was not in the original issue:

Creating a new namespace for each request won't work! If you look at the source for the cls shim you'll notice that it manually binds promise callbacks to a specific namespace https://github.com/TimBeyer/cls-bluebird/blob/master/shim.js#L14-L16

There shouldn't be any reason to create a new namespace for each request though - The exact purpose of CLS is to create 'thread'-local variables for each callback chain - so requests will still be isolated even though you only use a single namespace. Namespaces are meant as an application-level separation, not request level

**Comment by haikyuu** [comment]
> There shouldn't be any reason to create a new namespace for each request though
Ok, let's say i create a namespace for each request's callback chain ?
I modified https://github.com/haikyuu/test-cls-seq and now i `var sequelize = new Sequelize(...)` inside a namespace. The results are different, it works ... sometimes !
I don't know if i used the patcher correctly.
> Namespaces are meant as an application-level separation, not request level
So what i want to do is *impossible mission* ?

**Comment by janmeier** [comment]
> So what i want to do is impossible mission ?

At least with sequelize, probably yes. The patcher can only patch bluebird to work with a single namespace, and only the latest namespace is bound to the promise. This kind of hackery is needed because promises break the callback chain, when the callback is invoked later, once the promise is resolved.

Try with 

```js
var ns = cls.createNamespace...
Sequelize.cls = ns;
// Sequelize constructor, not instance!
```

Before you invoke any routes - it should be executed at application start, not at each request

**Comment by haikyuu** [comment]
Thanks a **LOT** :smile: , it worked.
I guess i didn't understand cls after all. 
In a given namespace: 
> [(...)](http://docs.sequelizejs.com/en/latest/docs/transactions/) variables set within a callback chain are private to that chain.

So there is no need to create multiple namespaces (in a single app).
The following is inspired by [this article about domains](https://medium.com/unexpected-token/node-js-domains-make-my-app-predictably-fixable-a6f30fb153d7) .
Namespaces are contexts that enable you to automagically & distinctly tag functions within every callback chain (in the picture : action consisting of several functions)  
![image](https://cloud.githubusercontent.com/assets/8558836/7458798/2db8cde8-f28f-11e4-9e85-7fa1d144f6cb.png)
Here is a [Repo containing a working sample](https://github.com/haikyuu/test-cls-seq) if somebody ever needs it.

**Comment by janmeier** [comment]
You're welcome, glad you got it solved.

**Comment by janmeier** [comment]
And yes, domains and CLS are very similar concepts - actually CLS could be built on top of domains
