### ISSUE TITLE
Options validation for query methods

### ISSUE THREAD

**Issue by santiagoaguiar** [sequelize/sequelize#3645]
I'm not sure if this has been considered in the past, or if it's there some way to enable these warnings, but it's becoming more of a problem that sequelize doesn't raise any kind of warnings when passing invalid options to some of the methods. 

Since sequelize is a strongly option based API (i.e. at lot of its API is defined inside the option arguments), it would help a lot if at least some cases were validated.

In particular, the following usually creates headaches for my team:

1. `Model.find({ field1: "foo" })`. The right call would have been `Model.find({ where: { field1: "foo" } })`. In the previous case, it not only returns silently, but it also considers it's an empty where, so it returns the first element. We have been bitten a lot of times by this case.
2. `Model.create({ Field1: "foo" })`. In particular for autogenerated columns like foreign keys, more than once the field is mistyped, and there's no warning that the given field does not exist.

On both cases, some checking to see if the passed options make any sense to the method would have helped. For both, we usually need to debug the program carefully to spot the bug, it's not obvious at all, even if it's obvious once spotted ;).

Of course, these are not the only cases.

Any reason not to be stricter and check the options? I'll admit that this is a general issue with option arguments, but given how they are used in sequelize, it seems like a very important issue in this case.

Thanks!

**Comment by janmeier** [comment]
As for find, yes we have considered making the where argument required, I believe there is already an open issue on it 

Validation for attributes in create is more tricky - we can (and do) only validate if the field does not allow nulls. You can define a foreign key without nulls using `x.belongsTo(y, { foreignKey: { allowNull : false}}) `. The same goes for other relations. 

I agree that sometimes options validation might be a good idea, and we are trying to do it for cases where an error might lead to loss of data (bulk delete and update). 
Adding validation to all options for all methods is not likely to happen however.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/2998

**Comment by janmeier** [comment]
Closing this in favor of the issue mentioned above
