### ISSUE TITLE
Overwriting class method

### ISSUE THREAD

**Issue by frnk94** [sequelize/sequelize#3646]
Since there no beforeBuild hook i decided to try overwriting build method then call the parent function but it not defined anywhere `model.DAO.prototype.Model.build` return the overwritten function

**Comment by janmeier** [comment]
Use `this.constructor.prototype.build`

http://docs.sequelizejs.com/en/latest/api/sequelize/#definemodelname-attributes-options-model

**Comment by frnk94** [comment]
Thx a lot !
