### ISSUE TITLE
[MySql] Empty array generates NULL for NOT IN

### ISSUE THREAD

**Issue by razakj** [sequelize/sequelize#3649]
I've came across a possible issue where if you pass an empty array to 
```
...{where:{id: {not:emptyArray}}}...
```
It actually generates SQL query ...NOT IN (NULL)... which then obviously doesn't return any data. For now i just check if array is null and change where clause accordingly but it'd be nice to see some native behavior which would possible exclude clause when no/empty data?

**Comment by BridgeAR** [comment]
Duplicate of #2052
