### ISSUE TITLE
Exception in 'upsert'.

### ISSUE THREAD

**Issue by ziflex** [sequelize/sequelize#3652]
Hi there.

I've got such model:
```js
var Preferences = sequelize.define('Preferences', {
    key: { type: Sequelize.STRING, allowNull: false, unique: true },
    value: { type: Sequelize.STRING }
}, { timestamps: false });

Preferences.removeAttribute('id');
```

and when I try to call 'upsert' method I get this exception:
``` 
Cannot read property 'defaultValue' of undefined
```

Error occurs [here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1252).

Is it a bug or I do something wrong ?

**Comment by mickhansen** [comment]
`upsert` assumes you have a primary key on your model it seems.

**Comment by ziflex** [comment]
@mickhansen maybe, but the value was not provided it's omitted. So, basically it can work without primary key using only unique one.

**Comment by ziflex** [comment]
@mickhansen in any way, there should be a more meaningful error message, to be able detect what the problem is.

**Comment by mickhansen** [comment]
@ziflex Well it's a bug, it should work without a primary key in theory since you have a unique key.

**Comment by janmeier** [comment]
Since this relies on un-supported behaviour  (`Preferences.removeAttribute('id')`) I'm reluctant to add a fix + test for this in the codebase.

As a fix you can set `Preferences.primaryKeyAttribute = false` https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1759

**Comment by mickhansen** [comment]
@janmeier `removeAttribute` is public API, it just doesn't do everything it needs to.

**Comment by janmeier** [comment]
Hmm valid point - I guess what I meant was that removing a primary key is not fully supported :)

But I see your point, removeAttribute should likely reidentify attributes (and also remove the attribute from `dateFields` `jsonFields` etc. if applicable

**Comment by janmeier** [comment]
Nvm. actually most of what I said already happens in refreshAttributes

**Comment by mickhansen** [comment]
@janmeier Yeah i think we've talked about moving all that stuff to `refreshAttributes` and make sure `removeAttribute` calls that.

**Comment by janmeier** [comment]
Yep - on it
