### ISSUE TITLE
Scopes are not applied?

### ISSUE THREAD

**Issue by f1nnix** [sequelize/sequelize#3657]
I'm trying to implement [polymorphic association with scopes](https://sequelize.readthedocs.org/en/latest/docs/associations/#1m). Test case:

#### Schema:

```js
// migrations/20150505212458-create-avatar.js
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('Avatars', {
      ...
      
      // key and scope for polymorphic association => `Bot`
      Avatarable: {
        type: Sequelize.STRING
      },
      AvatarableId: {
        type: Sequelize.INTEGER
      }
    });
  },
  down: function(queryInterface, Sequelize) {
    return queryInterface.dropTable('Avatars');
  }
};
...
```

#### Models

```js
// bot.js
module.exports = function(sequelize, DataTypes) {
	var Bot = sequelize.define('Bot', {
		name: DataTypes.STRING
	}, {
		classMethods: {
			associate: function(models) {
				return Bot.hasOne(models.Avatar, {
					foreignKey: "AvatarableId",
					scope: {
						Avatarable: "Bot"
					}
				});
			}
		},
		hooks: {
			afterCreate: function(bot, options, fn) {
				return bot.createAvatar({
					url: 'http://domain.com/avatar.png'
				}).then(function(avatar) {
					return fn(null, avatar);
				});
			}
		}
	});
	return Bot;
};

// avatar.js
module.exports = function(sequelize, DataTypes) {
  var Avatar = sequelize.define('Avatar', {
    url: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        Avatar.belongsTo(models.Bot, {
          foreignKey: 'AvatarableId',
          as: 'Avatarable'
        })
      }
    }
  });
  return Avatar;
};
```

#### Testing

```js
db.Bot.create({
  name: "John Doe"
})
  .then(function(bot){
    console.log(bot.dataValues)
  })
```
  
##### Produced SQL

```sql
...
Executing (default): INSERT INTO "Avatars" ("id","url","AvatarableId","updatedAt","createdAt") VALUES (DEFAULT,'http://domain.com/avatar.png',4,'2015-05-05 22:37:07.925 +00:00','2015-05-05 22:37:07.925 +00:00') RETURNING *;
```

##### Expected behavior

```sql
...
Executing (default): INSERT INTO "Avatars" ("id","url","AvatarableId", "Avatarable","updatedAt","createdAt") VALUES (DEFAULT,'http://domain.com/avatar.png',4,"Bot",'2015-05-05 22:37:07.925 +00:00','2015-05-05 22:37:07.925 +00:00') RETURNING *;
```

So, the scope value (class name) is not applied for some reason. Is it expected behavior or bug?

```json
{
  "pg": "^4.3.0",
  "pg-hstore": "^2.3.2",
  "sequelize": "^2.1.0",
  "sequelize-cli": "^1.7.0"
}
```
    
As always, thank you for your work, guys. You rock!

**Comment by janmeier** [comment]
Try with latest master - refactored scopes are not published yet :)

Sometimes it might be a bit confusing, but the 'latest' branch of the docs refers to latest master

**Comment by mickhansen** [comment]
Would also be helpful if you posted the part of your code using scopes.

**Comment by f1nnix** [comment]
@janmeier @mickhansen Tried lastest master, still no luck.

Published test case: [https://github.com/f1nnix/scopes_test](https://github.com/f1nnix/scopes_test) Maybe, I'm missing something, docs are confusing a bit about this.

**Comment by mickhansen** [comment]
@f1nnix association scopes only work on association methods (for obvious reasons, we wouldnt know what association you mean otherwise), you'll need to use `avatar.createBot()` in this instance or manually apply the correct field.

**Comment by f1nnix** [comment]
Mick, thank you for response,

1. Avatar is [created](https://github.com/f1nnix/scopes_test/blob/master/models/bot.coffee#L14) by **Provider's** createAvatar() method
2. `Bot.hasOne models.Avatar...` is the **only** association from Bot to Avatar. 

Isn't it sufficient data that points Avatar is associated to Bot scope?

BTW, SELECT gives the same SQL:

> db.Bot.create(name: "John Doe").then (bot) -> bot.getAvatar()
```sql
Executing (default): SELECT "id", "url", "createdAt", "updatedAt", "AvatarableId" FROM "Avatars" AS "Avatar" WHERE ("Avatar"."AvatarableId" = 10);
```

I do hope I'm missing scope definition somewhere.

**Comment by mickhansen** [comment]
In your testing code you only had `Bob.create()`, but yes `bob.createAvatar` should be sufficient.
It appears we don't support scope for hasOne at all, it's only supported for belongsTo, hasMany & belongsToMany.

Please open an issue asking for association scope support for hasOne.

**Comment by f1nnix** [comment]
@mickhansen Sorry, for delayed response. I've cleared example a bit, replaced `Bot` with `User` to be shorter.

> In your testing code you only had Bob.create(), but yes bob.createAvatar should be sufficient.

Nope. I'm doing `bob.createAvatar()` (now — **user**) as you pointed, just in `afterCreate` hook. Please, [take a quick look here](https://github.com/f1nnix/scopes_test/blob/master/models/user.coffee#L16).

> It appears we don't support scope for hasOne at all,

Replaced `hasOne` with `hasMany`, but still no luck. Let me describe the current state:

#### Step 1

```coffeescript
db.User
  .create(name: "John Doe")
```
```sql
Executing (default): INSERT INTO "Users" ("id","name","updatedAt","createdAt") VALUES (DEFAULT,'John Doe','2015-05-10 03:01:25.239 +00:00','2015-05-10 03:01:25.239 +00:00') RETURNING *;
```

#### Step 2

From User model definition
```coffeescript
hooks:
  afterCreate: (user, options, fn) ->
    user.createAvatar
      url: 'http://domain.com/avatar.png'
    .then (avatar) ->
      fn null, avatar
```
```sql
Executing (default): INSERT INTO "Avatars" ("id","url","AvatarableId","updatedAt","createdAt") VALUES (DEFAULT,'http://domain.com/avatar.png',1,'2015-05-10 03:01:25.265 +00:00','2015-05-10 03:01:25.265 +00:00') RETURNING *;
```

**Result:** the scope ` "Avatar"."Avatarable" = 'User'` is NOT applied.

#### Step 3

```coffeescript
.then (user) ->
  user.getAvatars()
```

SQL:

```sql
Executing (default): SELECT "id", "url", "createdAt", "updatedAt", "AvatarableId" FROM "Avatars" AS "Avatar" WHERE ("Avatar"."AvatarableId" = 1 AND "Avatar"."Avatarable" = 'User');
```

**Result:** the scope ` "Avatar"."Avatarable" = 'User'` is applied.

Any ideas why it's not applied while creation, but works while retrieving? Thank you very much.

**Comment by mickhansen** [comment]
There's test for `associationCreator` with `scope`, so you should work.
But there could be a bug i suppose.
