### ISSUE TITLE
Model.update try to update all values

### ISSUE THREAD

**Issue by firatkucuk** [sequelize/sequelize#3659]
on 2.1.0 release model update tries to update all fields.

My current code:

```
    //generate token with length of 10
    var resetCode = utils.generateId(150);

    var newProperties = {
      'resetCode' : resetCode,
      'updatedAt' : new Date()
    };

    return db.models.Customer
      .update(newProperties, {'where': {'email': email}})
      .then(function () {
        return resetCode;
      });
```

and generated SQL is:

```
UPDATE `CUSTOMER` SET `ID`=NULL,`EMAIL`=NULL,`PASSWORD`=NULL,`RESET_CODE`=NULL,`CREATED_AT`=NULL,`UPDATED_AT`='2015-05-06 06:14:27' WHERE `EMAIL` = 'test@example.com'
```

on 2.0.5 release. it updates only given fields. But on 2.06 it does not.

**Comment by janmeier** [comment]
Cannot reproduce with the code you posted. Please post the model definition, and a reproducible test case

**Comment by firatkucuk** [comment]
Hi it's a little bit complicated than i thought. Model fields must define manually. I created a little test scenario here:

https://github.com/firatkucuk/sequelize-update-test

**Comment by mickhansen** [comment]
Bug confirmed, working on a fix.
