### ISSUE TITLE
Testing for generated SQL

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#3662]
What's the suggested best way to write tests to make sure that API calls produce the correct SQL?

In my sequelize modules, I used to use:

```js
Task.find({ where: { name: 'task'} }).on('sql', function(sql) {
	expect(sql).to.be.equal('SELECT ...');
});
```

But since v2.1.0, support for `.on()` has been removed. What's the best way to achieve the same effect please?

**Comment by overlookmotel** [comment]
NB I don't think I can use the query generator, as my module uses hooks, and if the hooks don't run, the SQL won't be correct.

**Comment by janmeier** [comment]
Pass logging: function in the query options

**Comment by overlookmotel** [comment]
Yes, of course! That works great. Thank you.
