### ISSUE TITLE
Can't exclude association's fields from select statement in sequelize

### ISSUE THREAD

**Issue by AndrX** [sequelize/sequelize#3664]
I have the following code (simplified):

    var group = sequelize.define("group", {
        id: {type: DataTypes.INTEGER, autoIncrement: false, primaryKey: true},
        name: type: DataTypes.STRING,
        parentId: DataTypes.INTEGER
    }, { classMethods: {
            associate: function (models) {
                group.belongsToMany(models.item, { as:'items', foreignKey: 'group_id', through: models.group_item_tie });
            }}
    });

    var group_item_tie = sequelize.define("group_item_tie", {}, {freezeTableName: true});

    var item = sequelize.define("item", {
        spn: { type: DataTypes.INTEGER, autoIncrement: false, primaryKey: true },
    }, { classMethods: {
            associate: function (models) {
                item.belongsToMany(models.group, { foreignKey: 'spn', through: models.group_item_tie });
            }}
    });

When I try to return some records with relationships, let's say like this:

	dbcontext.group.findAll({
		where: { id: 6 },
        include: [{
                    model: dbcontext.item,
                    as: 'items',
                    attributes: ['spn']
                }]
        })

I also get in result the fields from a tie table `group_item_tie`:

	[{
        "id": 6,
        "name": "abc",
        "parentId": 5,
        "createdAt": "2015-05-06T15:54:58.000Z",
        "updatedAt": "2015-05-06T15:54:58.000Z",
        "items": [
            {   "spn": 1,
                "group_item_tie": {
                    "createdAt": "2015-05-06 15:54:58.000 +00:00",
                    "updatedAt": "2015-05-06 15:54:58.000 +00:00",
                    "group_id": 6,
                    "spn": 1
                }
            },
            {   "spn": 2,
                "group_item_tie": {
                    "createdAt": "2015-05-06 15:54:58.000 +00:00",
                    "updatedAt": "2015-05-06 15:54:58.000 +00:00",
                    "group_id": 6,
                    "spn": 2
                }
            },

I see it in generated sql query. How to exclude those from select statement? I've tried a few other things but was not successful.

I hope there is something cleaner then just doing:

	delete item.group_item_tie;

**Comment by mickhansen** [comment]
```js
include: [{
  model: dbcontext.item,
  as: 'items',
  attributes: ['spn'],
  through: {
    attributes: []
  }        
}]
```

**Comment by AndrX** [comment]
Thank you! Couldn't find information about this in documentation though

**Comment by janmeier** [comment]
@AndrX its on the todo list :) https://github.com/sequelize/sequelize/issues/2975

**Comment by GayathriMohan** [comment]
Is there any way I can exclude all the attributes in the model 'item' and just include the attributes present in the through model? @mickhansen

**Comment by AntonAL** [comment]
@mickhansen, It does't work for "sequelize": "^4.37.4".
Is there some alternative?

**Comment by mickhansen** [comment]
@AntonAL Define "doesn't work", what happens, what do you expect to happen, etc.
In any case i'm still using v3.

**Comment by AntonAL** [comment]
@mickhansen See series of my last comments here https://github.com/sequelize/sequelize/issues/1897

**Comment by danistefanovic** [comment]
@AntonAL Did you manage to make it work?

---

> Define "doesn't work", what happens, what do you expect to happen, etc.

@mickhansen `through: { attributes: [] }` doesn't remove the join table fields from the SELECT. Tested with v4.37.6.

**Comment by maxbogue** [comment]
This issue should be re-opened, as the provided solution no longer works.

**Comment by dpkshrma** [comment]
@danistefanovic it worked for me in v4.37.10
`through: { attributes: [] }` removed the join table fields from the SELECT

try upgrading to the latest version

**Comment by broox** [comment]
yep! on polymorphic relationships, defining the empty `through: { attributes: [] }` property solves the problem in `v4.38.0`. it's not exactly intuitive... but it it works.

e.g.
```
  MyDude.findOne({
    where: conditions,
    include: [{
      model: MyOtherDude,
      as: 'sub_dudes',
      attributes: ['name', 'slug'],
      through: {
        attributes: []
      }
  }).then((dude) => {
      ...
  });
```

**Comment by ryanburnette** [comment]
This is what I'm using for my use case where I want to exclude a field from the associated record.

```javascript
db.Bar.findOne({
  where: {
    attr: 'foo'
  },
  include: [
    {
      model: db.Foo,
      attributes: {
        exclude: ['xattr']
      }
    }
  ]
})
```

**Comment by wl1711** [comment]
it doesn't work for me, I tried v 4.37.1, 4.38.0 and 4.41
opened another issue #10141

**Comment by mqliutie** [comment]
How do this by `Model.getAssociatedModels()`?

**Comment by MatheusJacob** [comment]
I couldn't make it work on getAssociateMOdels too...

**Comment by jochri3** [comment]
Thank you @mickhansen

**Comment by toxxiczny** [comment]
just use joinTableAttributes attribute

await user.getCars({
    joinTableAttributes: [] 
})

**Comment by santiagoramirez** [comment]
@toxxiczny You're a life saver! This isn't even included in the types of sequelize-typescript, but works with an `as any`.
