### ISSUE TITLE
Eager fetching across many to many associations result in large cross product queries

### ISSUE THREAD

**Issue by Michael-Gannon** [sequelize/sequelize#3665]
Hi, I've got an issue using Sequelize over Postgres ("sequelize": "^2.0.3", "pg": "^4.3.0") and doing eager fetched queries across a db schema with many to many relationships.

We are using a fairly normalized schema (so theres a few tables), not to dwell on that topic, "it is what it is". 

When I issue a query like this:
```js
Listing.find({
  where: { },
  include: [ { all: true, nested: true } ]
});
```
The result is one single large query that fetches all associations with one call, the result is an enormous query that returns a cartesian product and internally it resolved the overlaps and returns the desired result. But it takes plenty of time and under some load I've found it to leak memory like a sieve.

I've dumped the setup (I hope I have it all there)
the db schema [here](https://gist.github.com/Michael-Gannon/f980ec93726f35eb67a1)
the models, relationships and query [here](https://gist.github.com/Michael-Gannon/34f5a8c3aa8ce8fe5262)
and the resulting query [here](https://gist.github.com/Michael-Gannon/79e1909f73a76a033811)

My primary suspicion is that my associations are incorrect and that is causing the problems, and there's no shortage of relationship directions that to raise an eye brow at.

Ideally I'd rather it make sensible queries to return the many to many tables, improving performance and possibly resolving a memory leak that seems to point to lots of resolved overlap values hanging around.

I have hacked a solution to get us moving again and it does this in a bit of a brutish way, unfortunately thats code that I may be able to share in public but if this issue cannot be resolved by modify my setup I can share that with a developer off channel.

Thanks in advance,
Mik.

**Comment by mickhansen** [comment]
Multiple row duplicating association just add a lot of overhead.
`include.seperate` is on the roadmap: https://github.com/sequelize/sequelize/issues/2869

**Comment by mickhansen** [comment]
Although it shouldn't be leaking memory, but the CPU overhead is hard to get around (i've optimized the duplication/overlap reducer a lot but it's still nested loops)

**Comment by Michael-Gannon** [comment]
Thanks for that Mick. 

If I've read that correctly there's nothing I can do today to get multiple queries to execute to return a complete (all:true nested:true) object graph over the current 1 large query.

In my case a medium sized graph has resulted in a query that returns over 400rows for the engine to resolve into the object model.

**Comment by mickhansen** [comment]
Not currently, but we're aware of the issue and the limitations of client side deduplication hence why it's a high priority on the road map :)
