### ISSUE TITLE
Promise returned by model functions doesn't properly support Bluebird .return()

### ISSUE THREAD

**Issue by joshmackey** [sequelize/sequelize#3668]
The following code SHOULD output ````undefined```` due to the empty ````.return()````
````
sequelize.models.User.findAll()
.return()
.then(console.log)
````

However, it continues to output the entities returned from ````findAll()````.

The following outputs ````undefined```` as expected, so something is modifying the promises in sequelize.

````
sequelize.Promise.resolve('test')
.return()
.then(console.log);
````

**Comment by mickhansen** [comment]
We use Bluebird internally - Can it be an issue with multiple `return` calls?

**Comment by joshmackey** [comment]
The two code blocks were ran independently of each other. There is only one return call for each.

Only the one ````.return()```` call from ````.findAll()```` had any problems. The other one using your internal Bluebird instance worked fine. So there is something odd about the promise returned from ````findAll()```` and not Bluebird itself.

**Comment by joshmackey** [comment]
Heres a simple example of the problem:

````
'use strict'
var Sequelize = require('sequelize');
var sequelize = new Sequelize('sqlite://:memory:', {
    logging: null
});

sequelize.define('Table', 
{
  Field: {
      type: Sequelize.STRING
    }
});

sequelize.sync()
.then(function () {
  sequelize.models.Table.findAll()
  .return()
  .then(function (result) {
    console.log('Query Promise should be true: %s', result === undefined);
  });

  sequelize.Promise.resolve('test')
  .return()
  .then(function (result) {
    console.log('Manual Promise should be true: %s', result === undefined);
  });
});
````

Both should be undefined but only the second one is. Also, it appears I was wrong about one thing. I had thought that it returned the entities regardless of the ````.returns()```` but it appears that it returns the model instead.

**Comment by janmeier** [comment]
I have no idea how this can be happening, but hopefully I will have some time to figure out soon

**Comment by janmeier** [comment]
It appears that `return(undefined)` actually returns the last bound value (using `bind`):

```js
return Promise.bind(42)
    .return(undefined)
    .then(function (value) {
      console.log(value); // 42
    });
```

**Comment by janmeier** [comment]
@joshmackey I've closed this issue, since it is an issue with bluebird - see the issue linked above for details
