### ISSUE TITLE
Model.bulkCreate() inserts NULL for undefined values

### ISSUE THREAD

**Issue by bblack** [sequelize/sequelize#3670]
on 2.1.3; postgres

```
var Beer = sequelize.define('Beer', {
    style: Sequelize.STRING,
    size: Sequelize.INTEGER,
});

Beer.bulkCreate([{
    style: 'ipa'
}])
.then(function(){
})
```

> ```
Executing (default): INSERT INTO "Beers" ("id","style","size","createdAt","updatedAt") VALUES (DEFAULT,'ipa',NULL,'2015-05-07 20:32:46.454 +00:00','2015-05-07 20:32:46.454 +00:00');
```

**Comment by mickhansen** [comment]
Mmmm beer.

**Comment by janmeier** [comment]
Whats the expected behaviour here? You are not providing a value for size, and the column does not have a default value - so what should we insert instead?

**Comment by mickhansen** [comment]
@janmeier leave it blank, let the database provide a default value or let it fail. User should explicitely set `defaultValue: null` if they actually want a default value null.

**Comment by bblack** [comment]
The problem is especially apparent when for example you don't specify a value for a column that has both a default value and `not null`, in which case the bulkCreate will fail.
