### ISSUE TITLE
Unhandled rejection TypeError: Object [object Promise] has no method 'complete'

### ISSUE THREAD

**Issue by aowainati** [sequelize/sequelize#3672]
All of your documentation on migrations claims we can use the `.complete` function to chain our commands, yet I just upgraded Sequelize versions from 2.0.6 to 2.1.3 and all my migrations broke because of this error.

Did I miss this in the changelog somewhere? What is the correct way to be writing a migration now?

**Comment by janmeier** [comment]
`complete` is event emitter style - event emitters have been completely removed in 2.1. You can use `then` and return the promise chain from the migration function (no need to use a done callback anymore)

We know many examples still need to be updated - help is welcomed, you'll find the docs in this repo
