### ISSUE TITLE
create()/update() should error with unexpected fields

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#3673]
I'm calling update(new_fields) on an instance and the new_fields includes some that are not contained in the model. For example, I'm adding a field called "whatever".

I expected this to be an error, but it's not. When the promise completes, the instance was saved, although I notice that the "_changed" property includes the unexpected field with a "whatever" of false:

 ```_changed: { whatever: false, updated_at: false },```

Since I can only know after saving is complete that a field was unexpected (from the _changed property above), this doesn't give me a chance to fire an error with unexpected fields, until AFTER I've already saved something.

Am I doing something wrong?

**Comment by GeoffreyPlitt** [comment]
Same behavior with create().

If this is expected, is there a utility function so that I can validate the list of fields before attempting create() or update()?

**Comment by mickhansen** [comment]
It not throwing an error is expected (i actually like being able to trust that i don't have to move extra fields that i might need for other reasons when updating a sequelize instance).
However the undefined field should definitely **NOT** be set in either changed or dataValues.

**Comment by GeoffreyPlitt** [comment]
OK, but let's say I have a business reason to make sure there aren't any surprise fields. Is there a different way to scan the update before saving it, and figure out if there are surprise fields?

**Comment by mickhansen** [comment]
@GeoffreyPlitt Easiest way is to match `Object.keys(values)` with `Object.keys(Model.rawAttributes)`, we do this internally with _.intersection to ensure we only update model.

**Comment by GeoffreyPlitt** [comment]
Gotcha, thanks! may create a little helper function for this and send a PR. Closing this for now.
