### ISSUE TITLE
Include problem for multiple foreign keys of the same model

### ISSUE THREAD

**Issue by pprandee** [sequelize/sequelize#3678]
Hi folks, I just found a problem in the case shown below. I don't know yet, whether it's a wrong behavior or whether I did something wrong. It's basically about the List -> Task table join.

1.) It doesn't matter what include options I take, there is no chance to join both foreign keys. Even something like "include: { all:true }" doesn't work.

2.) The current result looks like:
```json
[{
    "createdAt": "...",
    "updatedAt": "...",
    "dailyTask": 1,
    "weeklyTask": 2,
    "Task": {
        "id": 2,
        "description": "clean your room",
        "createdAt": "...",
        "updatedAt": "..."
    }
}]
```
But is there a chance to get it like, or wouldn't be it actually better to have it like:
```json
[{
    "createdAt": "...",
    "updatedAt": "...",
    "dailyTask": 1,
    "weeklyTask": {
        "id": 2,
        "description": "clean your room",
        "createdAt": "...",
        "updatedAt": "..."
    }
}]
```
And what I'm actually trying to have, should look like:
```json
[{
    "createdAt": "...",
    "updatedAt": "...",
    "dailyTask": {
        "id": 1,
        "description": "brush your teeth",
        "createdAt": "...",
        "updatedAt": "..."
    },
    "weeklyTask": {
        "id": 2,
        "description": "clean your room",
        "createdAt": "...",
        "updatedAt": "..."
    }
}]
```
Any idea, whether it's a bug, or how I could do it?
```javascript
var co = require('co');
var Sequelize = require('sequelize');
var sequelize = new Sequelize('postgres://postgres:postgres@localhost:5432/test', {
    logging: false
});

// Models
var Task = sequelize.define('Task', {
    description: Sequelize.STRING
});

var List = sequelize.define('List');

// Assoziations
Task.hasMany(List, {
    foreignKey: 'dailyTask'
});

Task.hasMany(List, {
    foreignKey: 'weeklyTask'
});

List.belongsTo(Task, {
    foreignKey: 'dailyTask'
});

List.belongsTo(Task, {
    foreignKey: 'weeklyTask'
});

co(function*() {

    var connection = yield sequelize.sync({
        force: true
    });

    var dailyTask = yield Task.create({
        description: 'brush your teeth'
    });

    var weeklyTask = yield Task.create({
        description: 'clean your room'
    });

    var list = yield List.create({
        dailyTask: dailyTask.id,
        weeklyTask: weeklyTask.id
    });

    var result = yield List.findAll({
        include: [Task]
    });

}).catch(function(err) {
    console.log(err);
});

```

**Comment by mickhansen** [comment]
You'll need to add an alias to one or both of those associations, currently they are overwriting eachother.
Something like:

```js
List.belongsTo(Task, {
    as: 'dailyTask',
    foreignKey: 'dailyTask'
});

List.belongsTo(Task, {
    as: 'weeklyTask',
    foreignKey: 'weeklyTask'
});
```

However it's not possible to have an association be named the same as a foreign key, so you need to either rename your foreign keys or set your association aliases to something different.

Closing since a question (although still happy to help)

**Comment by pprandee** [comment]
Awesome, thanks! Got it work! Sorry for wrong bug report.

**Comment by pmhpereira** [comment]
Sorry for hijacking this issue, but I'm having the same problem.
@pprandee, how did you solve it?

**Comment by pprandee** [comment]
Hi @pmhpereira, here the solution related to the example above:
```javascript
List.belongsTo(Task, {
    as: 'weeklyTask',
    foreignKey: 'weeklyTaskFk'
});
```
When you want to join the Task table, simply do the following on the include object:
```javascript
{
    include: [{
            model: Task,
            as: 'weeklyTask'
     }]
}
```
Hope it helps!

**Comment by pmhpereira** [comment]
Thank you very much, that did the trick! :+1:

**Comment by tejalshah84** [comment]
Hey All,

How do you define the association and query it if you have two foreign keys, where both are essential the same primary key in the source table. For example: Each User has many private messages. Each private message belongs to two users: chat author and chat target. I am trying to associate the priv messages and user table twice once through the chat author foreign key and the second time through chat target foreign key. This is unfortunately not working :(

user.hasMany(privatechathistory, {foreignKey: 'chattarget'});
privatechathistory.belongsTo(user, {as: 'usertarget', foreignKey: 'chattarget', targetKey: 'username'});
user.hasMany(privatechathistory, {foreignKey: 'chatauthor'});
privatechathistory.belongsTo(user, {as: 'userauthor', foreignKey: 'chatauthor', targetKey: 'username'});

Query:

privateMessage.findAll({
		attributes: ['id','chatauthor', 'chattarget','chatmessage', 'timestamp', 'createdAt'],
	        where: {
	                 chatmessage: {
				    	$like: searchtxt
	                  },
		         $or: [{chatauthor: currUser}, 
				  {chattarget: currUser}]
			},
		        include: [{model: User, as: 'usertarget', attributes: ['location']}],
		        order:'timestamp DESC',
		        offset: pageCount,
		         limit: 10
		}).then(function (privmessages) {
			res.json(privmessages);
	      });

How do I define multiple foreign keys in an association and then query through one of those joins?

Thank you.

**Comment by mickhansen** [comment]
@tejalshah84 Please format the code.

**Comment by tejalshah84** [comment]
// Model Association Definition for user and chathistory tables
user.hasMany(chathistory, {foreignKey: 'chattarget'});
chathistory.belongsTo(user, {as: 'targetuser', foreignKey: 'chattarget', targetKey: 'username'});
user.hasMany(chathistory, {foreignKey: 'chatauthor'});
chathistory.belongsTo(user, {as: 'authoruser', foreignKey: 'chatauthor', targetKey: 'username'});

// User = user table
// privateMessage = chathistory table


privateMessage.findAll({
         attributes: ['id','chatauthor', 'chattarget','chatmessage', 'timestamp', 'createdAt'],
         where: {
                     chatmessage: {
                              $like: searchtxt
                     },
         $or: [{chatauthor: currUser}, {chattarget: currUser}] },
         include: [{model: User, as: 'targetuser', attributes: ['location']}],
         order: 'timestamp DESC',
         offset: pageCount,
         limit: 10
 }).then(function (privmessages) {
         res.json(privmessages);
});

**Comment by tejalshah84** [comment]
//Defining association. Two foreign keys chattarget and chatauthor, both joining with username

![image](https://cloud.githubusercontent.com/assets/10164619/10853692/9375009c-7ef4-11e5-8c34-6f7c072d2d6c.png)

// Query joining private chathistory and user table 
// using privatechathistory.chattarget = user.username

![image](https://cloud.githubusercontent.com/assets/10164619/10853720/c668c150-7ef4-11e5-836a-9a7633dc446e.png)

**Comment by mickhansen** [comment]
@tejalshah84 Use markdown formatting rather than screenshots, not possible to C/P screenshots into a editor :)

What's the error here exactly? Try to include all relevant details per https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues

**Comment by vhmth** [comment]
@pprandee thank you for your comments! Helped me. :-)

**Comment by jdnichollsc** [comment]
Hi guys, Sequelize support **composite foreign keys**?

**Comment by Giiaga** [comment]
Thank You Mickhansen and whoever asked the question and some other people in the chat

**Comment by Giiaga** [comment]
Thank You Mickhansen and whoever asked the question and some other people in chat like Tejal and jdnichollsc and ppetzold thank you for your solution to someone else's question. thank you pmhpereira

**Comment by rangerisrael** [comment]
add this to your model  fk inside @Column references: {
            model: 'accounts', // Name of the referenced table
            key: 'account_id', // Name of the referenced column
        },
