### ISSUE TITLE
Model#destroy() should take a primary key

### ISSUE THREAD

**Issue by bblack** [sequelize/sequelize#3679]
[feature request]

It is a nice convenience that Model#find() accepts a primary key: ( `Beer.find(1)` rather than `Beer.find({where: {id: 1})` )

It would be nice to have the same feature for Model#destroy.

**Comment by mickhansen** [comment]
@bblack Just to follow up we're actually considering deprecating `.find(1)` since it has some security implications.

**Comment by bblack** [comment]
is there some related discussion i can read?

**Comment by mickhansen** [comment]
It was brought up privately by someone from RedHat.
Cutting a new release tonight mitigating the security issues and then i'll release the details :)

**Comment by janmeier** [comment]
Find is a common enough operation to allow a specialized `findById`, but I don't think we should start providing tailored methods for both update, destroy etc. Also because of the security issues mentioned here (clients might abuse `destroy(id)`, by passing an object as id)
