### ISSUE TITLE
Model#destroy should cascade to "join" tables

### ISSUE THREAD

**Issue by bblack** [sequelize/sequelize#3680]
In the case of a many-to-many association between models A and B (with join table J), it would simplify things greatly if on `A.destroy()`, the corresponding rows in table J were deleted first. (It would be important that they be done first if there were foreign-key constraints placed on table A).

**Comment by mickhansen** [comment]
Hmm i know we support `cascade: true` for destroy (when truncate), for dialects that support that.
We might not be supporting it for destroys with WHERE.
