### ISSUE TITLE
$or gives 'column group.or does not exist'

### ISSUE THREAD

**Issue by canebat** [sequelize/sequelize#3681]
I think I might have misunderstood how to use `$or` and `$like`:
https://github.com/sequelize/sequelize/blob/master/docs/docs/querying.md

I tried to pattern match several fields in my `group` model (w/ postgres):

```
models.group.findAndCountAll({

    where: { 
        $or: [
          { name: { $like: 'abc_' } },
          { detail: { $like: 'abc%' } },
          { other: { $like: '_abc' } },
        ]
    }

})
```

Which errors:

```
  name: 'SequelizeDatabaseError',
  message: 'column group.or does not exist',
```

And the sql statement sees `[object Object]` instead of `like`:

```
Executing (default): SELECT count(*) AS "count" FROM "groups" AS "group" WHERE "group"."or" IN (`name` = '[object Object]',`detail` = '[object Object]',`other` = '[object Object]');
```

**Comment by mickhansen** [comment]
What version are you using?
Does it work with `findAll`?

**Comment by canebat** [comment]
I'm using sequelize 2.0.0-rc8. It also happens for `findAll()`.

However, if I change the where query to this:

    where: { 
        Sequelize.or(
          { name: { like: 'abc_' } },
          { detail: { like: 'abc%' } },
          { other: { like: '_abc' } },
        )
    }

Then it works with `findAll()`. But for `findAndCountAll()` it throws this error:

    name: 'SequelizeDatabaseError',
    message: 'missing FROM-clause entry for table "group"',

**Comment by canebat** [comment]
I did `npm install sequelize --save` and it updated to 2.0.6. The query works now with both `findAll()` and `findAndCountAll()`, but I'm getting problems trying to search through associations:

```
// search group names and user names

where: { 
    Sequelize.or(
      { name: { like: 'abc_' } },
      { 'user.name' { like: 'abc%' } },
    )
}
```

Which complains:
```
error: column group.user.name does not exist
```

**Comment by janmeier** [comment]
@canebat You should add the where clause for user to the include: `include: [{ model: User, where: { name ...`

**Comment by canebat** [comment]
I added this:

   include: [{ model: User, where: { name: { like: 'abc%' } } }]

But it returns empty group row if I search for a user's name. This previously worked in 2.0.0-rc8 with `{ 'user.name':  { like: 'abc%' } }`

**Comment by janmeier** [comment]
That code will only return a group, if it has a user with a matching name. If you want all groups, regardless of whether they have a matching user, use `required: false` on the include

**Comment by canebat** [comment]
I'm trying to get all groups that match either a group name or has a user with that name.

For example,

Group( "bobc") - 3 users
Group( "test") - 3 users, but has a user named "bobcat"

Searching for "bob" should return both Group "test" and Group "bobc" with this:

```
models.group.findAll({ 
    include: [ { model: models.user, where: { name: { like: 'bob%' } }, required: false }], 
    where: { name: { like: 'bob%' } }
});
```

But it's still returning empty rows.

**Comment by janmeier** [comment]
This is not possible currently  - see https://github.com/sequelize/sequelize/issues/3095
