### ISSUE TITLE
Sequelize findAll performance issue

### ISSUE THREAD

**Issue by amirbaer** [sequelize/sequelize#3682]
Hi all,

I encountered some performance issues using the findAll method with includes and I couldn't find any solution in the docs and forums so I was hoping someone here could help me.

##### My schema looks like this -
Move:
 * belongsTo(Package) - M:1
 * belongsToMany(TagValue) - M:N

Package:
 * hasMany(Move) - 1:M

TagValue:
 * belongsToMany(Move) - M:N
 * belongsTo(TagType) - M:1

TagType:
 * hasMany(TagValue) - 1:M

Assuming the heavy part is the M:N join between Move and TagValue, I tried running the query both  with an include and without, to see the time differences.

##### With the include / join
I run this code:
> Move.findAll({ include: [{ model: TagValue, include: [{ model: TagType }] }] })

Which gets translated into this SQL:
> SELECT `Move`.`id`, `Move`.`name`, `Move`.`package`, `Move`.`description`, `Move`.`metadata`, `Move`.`env`, `Move`.`content`, `Move`.`createdAt`, `Move`.`updatedAt`, `Move`.`deletedAt`, `TagValues`.`id` AS `TagValues.id`, `TagValues`.`tagTypeId` AS `TagValues.tagTypeId`, `TagValues`.`tagValueId` AS `TagValues.tagValueId`, `TagValues`.`value` AS `TagValues.value`, `TagValues`.`sort` AS `TagValues.sort`, `TagValues`.`createdAt` AS `TagValues.createdAt`, `TagValues`.`updatedAt` AS `TagValues.updatedAt`, `TagValues`.`deletedAt` AS `TagValues.deletedAt`, `TagValues.movesTags`.`createdAt` AS `TagValues.movesTags.createdAt`, `TagValues.movesTags`.`updatedAt` AS `TagValues.movesTags.updatedAt`, `TagValues.movesTags`.`tagValueInternalId` AS `TagValues.movesTags.tagValueInternalId`, `TagValues.movesTags`.`moveId` AS `TagValues.movesTags.moveId`, `TagValues.TagType`.`id` AS `TagValues.TagType.id`, `TagValues.TagType`.`name` AS `TagValues.TagType.name`, `TagValues.TagType`.`createdAt` AS `TagValues.TagType.createdAt`, `TagValues.TagType`.`updatedAt` AS `TagValues.TagType.updatedAt`, `TagValues.TagType`.`deletedAt` AS `TagValues.TagType.deletedAt` FROM `moves` AS `Move` LEFT OUTER JOIN (`movesTags` AS `TagValues.movesTags` INNER JOIN `tagValues` AS `TagValues` ON `TagValues`.`id` = `TagValues.movesTags`.`tagValueInternalId`) ON `Move`.`id` = `TagValues.movesTags`.`moveId` AND `TagValues`.`deletedAt` IS NULL LEFT OUTER JOIN `tagTypes` AS `TagValues.TagType` ON `TagValues`.`tagTypeId` = `TagValues.TagType`.`id` AND `TagValues.TagType`.`deletedAt` IS NULL WHERE `Move`.`deletedAt` IS NULL;

##### Without the include / join
I run this code:
> Move.findAll({})

Which gets translated into this SQL:
> SELECT `id`, `name`, `package`, `description`, `metadata`, `env`, `content`, `createdAt`, `updatedAt`, `deletedAt` FROM `moves` AS `Move` WHERE `Move`.`deletedAt` IS NULL;

##### Here are some numbers as to the performance:

This was checked with 10,000 Moves and 10,000 Move-TagValue connections in my MYSQL DB.

The query with the includes (Moves+Tags):
* running through Sequelize takes about 2000ms
* running the same SQL code using node-mysql takes around 600ms
* running the same SQL in the mysql client takes around 100ms

The query without the includes (just Moves):
* running through Sequelize takes about 1000ms
* running the same SQL code using node-mysql takes around 180ms
* running the same SQL in the mysql client takes around 25ms

##### Any ideas?

From the numbers it definitely looks like a Sequelize issue. Obviously using an ORM adds an overhead but it seems like this is a lot more than you would expect...

My specs:
Sequelize version: 2.0.6
Node version: tried both 0.10.36 & 0.12.2, 0.12.2 was a bit slower (about %25)

Any help would be greatly appreciated :)
Thanks!
Amir Baer

**Comment by mickhansen** [comment]
JOINS result in a cartesian product which is expected to decrease performance.
How many rows for the query without includes?
We attempt to optimize the code as much as possible, but javascript is not excellent at CPU intensive tasks and serializing database results can be just that.

**Comment by amirbaer** [comment]
Hey, thanks for the quick response.
The query without includes contained 10,000 rows.
What do you mean by serializing database results? Building the objects and relationships from the rows returned by the query?

**Comment by mickhansen** [comment]
@amirbaer Yep that's what i meant :) 10.000 rows are quite a bit to loop through and create instances of.
We haven't done performance improvements in a while, but i'm not sure there's a ton to gain.

**Comment by amirbaer** [comment]
I see... :)
It still seems a bit odd to me that it takes so long because I do some post-processing (remove / alter / add fields) to each of the 10,000 rows after receiving the data from Sequelize and the overhead added is not nearly as long. Is there anyway to get a better understanding of the part that's weighing the process down?

**Comment by mickhansen** [comment]
You can try timing around `bulkBuild` here, for the query without inclues. https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query.js#L212

Be interesting to see if that's most of the overhead. There might be significant overhead alone in `new Instance()` maybe? I'm not an expert on javascript performance i'm afraid.

**Comment by mickhansen** [comment]
Still on my todo to set up a benchmarking suite that can be run on PR's etc to see the effect of code changes.

**Comment by amirbaer** [comment]
Cool, I'll give it a try and see what I find. Thanks!

**Comment by jspeis** [comment]
I've been facing a similar issue where I would like to use Sequelize to work with many rows returned from a join (I'm testing with about 100,000). My query would take about 3 seconds to run in groupJoin -- but around 35 seconds to get results formatted back from bulkBuild.

From my initial checking, it appears like the bottleneck is in performance in bulkBuild specifically seems like the most time is spent in the valueSets.map loop: https://github.com/sequelize/sequelize/blob/02fb3faa5ef45fea510c534184e67b1ce5e6e206/lib/model.js#L1826-1828  

I'm relatively new to Node, so apologies if these suggestions are naive, but would there be any way to either: (a) have the this.build code get inlined inside the map loop (b) parallelize execution of the mapping or (c) provide an option in the API where the user can use the just get back the raw results data (without having to use a raw SQL query)?

**Comment by janmeier** [comment]
@jspeis a): Perhaps, @mickhansen is the best to answer this once he's back from vacation, b) No easy way to do that in node, c) Definitely: `options.raw` (gives you back POJOs)

**Comment by sushantdhiman** [comment]
Current master test results

| findAll  | Include (associations) | queryRun (ms) | overhead (ms) |
| :-----------: | :-----------: | :-----------: | :-----------: |
| 1500  | 1500 | 158 | 16 |
| 1500  | 0 | 74 | 3 |
| 10000  | 10000 | 1204 | 224 |
| 10000  | 0 | 537 | 18 |

It seems sequelize overhead is under acceptable ranges.

But yes it seems `bulkBuild` has some issues. We are tracking it under #4247 and #3852 

We can close this issue @janmeier @mickhansen
