### ISSUE TITLE
Semantic versioning - breaking changes

### ISSUE THREAD

**Issue by timlesallen** [sequelize/sequelize#3685]
Hi guys,

It's naughty to make breaking changes without incrementing the major version number.

See http://semver.org/

Please don't.  Your changes from 2.0.x -> 2.1.x make everything explode.  Bah!

Thanks :)

Tim

**Comment by mickhansen** [comment]
Hi @timlesallen 

It's naughty to post issues without going through the issue history :)
https://github.com/sequelize/sequelize/issues/2786

To sum up, with the npm default to ^ we will begin bumping major for BC.

**Comment by timlesallen** [comment]
@mickhansen Awesome, thanks!
