### ISSUE TITLE
(PostgreSQL) Automanaged transaction with `{isolationLevel: 'SERIALIZABLE'}` throws an error.

### ISSUE THREAD

**Issue by realyze** [sequelize/sequelize#3689]
The error is `Unhandled rejection Error: commit has been called on this transaction(<transactionId>), you can no longer use it.`

Without much investigation, I'd say it looks like that's because `commit` throws an error if I run two concurrent queries and they conflict. The first one commits OK and the other one throws error on `commit` - I assume the transaction manager then catches the error and tries to `rollback`.

**Comment by janmeier** [comment]
There is no way for us to debug this without some code which replicates this error

**Comment by realyze** [comment]
Here's a simple gist: https://gist.github.com/realyze/1aef77ca823fad7e89fe

**Comment by realyze** [comment]
I'm seeing `Unhandled rejection Error: commit has been called on this transaction(bde57e9e-9d79-45e0-a913-b124ed6aac95), you can no longer use it` in the console when I run it (sequelize 2.1.3, I'm on Mac OS X 10.10.2, node 0.12)

**Comment by mickhansen** [comment]
As you say it looks like it happens because there's an error on commit, then it attempts to rollback, which we don't allow.

Question is what's the real way to handle a failed commit, do you rollback or just leave it? I assume leave it.

**Comment by realyze** [comment]
Good question. :-) Wouldn't an unrollbacked failed commit just "hang there" until it times out though?

**Comment by mickhansen** [comment]
I assume the database would kill it if it fails since it's unrecoverable, but i got no idea.
