### ISSUE TITLE
Sqlite on Android

### ISSUE THREAD

**Issue by ziflex** [sequelize/sequelize#3691]
Hi there,
I've faced with a problem caused by some generated queries. It turns out that on some Android devices Sqlite doesn't support multiple queries concatenated with ';'. The most obvious query is which is generated by 'upsert' method.
Is there any options to work around this issue?

**Comment by mickhansen** [comment]
No workaround currently, would have to change how the query is generated.
You'll probably have to bake your own upsert method.

**Comment by janmeier** [comment]
Unfortunately supporting other platforms than node is not a priority for us right now - we simply don't have the time.

We would perhaps be open to accepting a PR that adds support, as long as it is not too much extra code
