### ISSUE TITLE
Creating an index when the model has a schema causes a SequelizeDatabaseError (relation already exists)

### ISSUE THREAD

**Issue by mikrofusion** [sequelize/sequelize#3693]
The following will fail due to having a schema.  Without a schema it works fine.  Note: this is using postgres.

```
sequelize.define('foobar', {
      id: {  ....  },
      foo: { ... },
      bar: { ... },
    }, {
      schema: schemaName,
      indexes: [ { fields: ['foo', 'bar'] } ],
    }
);
```

The failure happens because it tries to create a unique index when the index already exists, which causes an Unhandled rejection SequelizeDatabaseError: relation already exists.

After doing some digging it appears it is attempting to re-create the index because in
```
  Model.prototype.sync = function(options) {
```
when we call
```
      return self.QueryInterface.showIndex(self.getTableName(options), options);
```
we get an empty array [] (even though the model has an index).  When a schema is not provided then showIndex correctly returns an array with the indexes.

So we bottom out with the root cause being (in dialects/postgres/query-generator):

```
    showIndexesQuery: function(tableName) {
      // This is ARCANE!
      var query = 'SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, ' +
        'array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) ' +
        'AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a ' +
        'WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND a.attnum = ANY(ix.indkey) AND '+
        "t.relkind = 'r' and t.relname = '<%= tableName %>' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;";

      return Utils._.template(query)({ tableName: tableName });
    },
```

It appears showIndexesQuery needs to be able to support a tableName when it has a schema (it currently returns incorrect results - an empty set - when there is a schema).

I'd be glad to take a stab at fixing this but appreciate any guidance as to how to fix the showIndexesQuery since the sequelize teams postgres-foo is probably better than mine.

**Comment by mikrofusion** [comment]
Note:  I tried using
```
    if (!Utils._.isString(tableName)) {
      tableName = this.quoteTable(tableName);
    }
```
prior to calling showIndexesQuery but it didn't appear to work.

**Comment by mickhansen** [comment]
`t.relname = '<%= tableName %>'` will likely need to add some lookup for schema aswell? I'm not sure if table names are stored with schemas in that table.
