### ISSUE TITLE
NFR: After find life cycle callback

### ISSUE THREAD

**Issue by ebrian** [sequelize/sequelize#3695]
A row level callback to add virtual meta fields.

Example:
this.full_name = this.first_name + ' ' + this.last_name;

But in such a way where it's part of the returned data as if it were part of the model.

**Comment by mickhansen** [comment]
You should add `full_name` as a virtual field and then simply add a getter to that virtual field. Or `set` the value on the virtual field.

**Comment by janmeier** [comment]
+ We already have an afterFind hook :)

**Comment by ebrian** [comment]
@janmeier No way... Is that an undocumented feature? Most ORMs have it, I was curious why sequelize did not.

**Comment by ebrian** [comment]
On a side note... this is an amazing project. It's excellent just the way it is. But I'm always looking for new ideas to offer up to make it better.

**Comment by janmeier** [comment]
@ebrian Appearently we forgot to document that yes..  - PR welcome https://github.com/sequelize/sequelize/blob/master/docs/docs/hooks.md :)
