### ISSUE TITLE
javascript question about async code and promises?

### ISSUE THREAD

**Issue by canebat** [sequelize/sequelize#3696]
This isn't really about sequelize, but I was wondering if this is a dangerous thing to do given the nature of asynchronous code in javascript:

```
models.group.find({ id: id}).then(function(group) {
    // No group was found
    if (!group) {
        return null;
    }

    if ( ...some other condition... ) {
        return [];
    }

    // group was found
    group.updateAttributes(.....).then(function(group) {
        return [group];
    });
});
```

Would javascript execute the two `if` statements and the `group.updateAttributes` nearly all at once inside the promise? That could lead to problems.

Would forcing it all to be under conditionals be a valid pattern to the problem?

```
if (!group) {
    return null;
} 
else if ( ... some other condition ...) {
    return [];
}
else {
    group.updateAttibutes(....)
}
```

**Comment by mickhansen** [comment]
Javascript evaluates code synchronously, so if all your ifs have returns theres no way the final call will be triggered if the ifs are matched.

Short circuiting code with `if () return` if a pattern we use a lot in the sequelize codebase, so you should be fine.
