### ISSUE TITLE
Validation/Conversion for JSON Type

### ISSUE THREAD

**Issue by dtjohnson** [sequelize/sequelize#3698]
Hi! I've been using Sequelize for a bit now, and I'm incredibly impressed. Extremely easy to use!

I'm migrating from MongoDB (via Mongoose) to PostgreSQL. One of the big features I miss is being able to store encapsulated objects inline as subdocuments. For example:

``` javascript
{
    itemName: "foo",
    properties: {
        height: 5.3
    },
    parts: [{
        name: "bar",
        description: "bars the foo"
    }, {
        name: "baz",
        description: "bazs the foo"
    }]
}
```

I know I can put these subobjects in separate tables and hook them up using associations. However, for truly encapsulated objects this adds a lot of overhead and complexity.

Alternatively, since this is PostgreSQL, I can use the JSON/JSONB type and store these inline. That works great, but I lose the awesome validation and type conversion I get with standard fields. In Mongoose, you could define the schema above like:

``` javascript
{
    itemName: String,
    properties: {
        height: Number
    },
    parts: [{
        name: String,
        description: String
    }]
}
```

Mongoose would take care of validating the subobjects (most of the time). It doesn't seem that Sequelize has support for this out of the box. However, I was wondering if there was a way I could manually use the validation and type conversion built-in to Sequelize using hooks, setters, or custom validation. I'm just not sure how to call these outside of the normal model definition.

For example, how could I convert the property height to a float if it is set as a string? I could check this in a setter, but how can I use Sequelize's type conversion for this?

And how could I validate that height is greater than 0? I could write a custom validation for the field and check that the value is greater than 0, but it would be nice to use the built-in validators like "min".

Any suggestions?

**Comment by mickhansen** [comment]
There's been a little discussion about building mini-orm support for JSONB, but not a lot and no progress.
I don't have any clear suggestion on how you could easily extend that validator to the json fields.

We're looking at adding schema validation to all data types (STRING must be null or string, no integers etc), perhaps we could couple that with something like `schema: {}` and `strict: true|false` for JSON fields.

**Comment by dtjohnson** [comment]
Well, here's hoping this gets implemented at some point. It's really nifty for encapsulation. I ended up doing the schema validation with [revalidator](https://github.com/flatiron/revalidator). It's not as pretty or simple as the Mongoose or Sequelize declarations, but it does the trick. Here's what my example above ends up looking like:

```javascript
var revalidator = require('revalidator');

var schemaValidator = function (schema) {
    return function (value) {
        var results = revalidator.validate(value, schema);
        if (!results.valid) throw new Error(JSON.stringify(results.errors));
    };
};

sequelize.define("Item", {
    itemName: DataTypes.STRING,
    properties: {
        type: DataTypes.JSONB,
        validate: {
            schema: schemaValidator({
                type: "object",
                properties: {
                    height: { type: "number", exclusiveMinimum: 0, required: true }
                }
            })
        }
    },
    parts: {
        type: DataTypes.JSONB,
        validate: {
            schema: schemaValidator({
                type: "array",
                items: {
                    type: "object",
                    properties: {
                        name: { type: "string", required: true },
                        description: { type: "string", required: true }
                    }
                }
            })
        }
    }
});
```

**Comment by nodecode** [comment]
+1 for this feature.

**Comment by gaprl** [comment]
:+1:

**Comment by fredericlefeurmou** [comment]
+1

**Comment by awdogsgo2heaven** [comment]
I agree, JSONB has set up Postgres to be a real contender in document based storage - so this would be a nice feature to have. On the other hand I guess I could see the reluctance to build a large feature built around a feature only found in one database so far. 

Right now I use a JSON Schema validator, along with : https://github.com/chute/json-schema-defaults in order to create default values for my json. I put the schemas in a separate folder from my model and include them to prevent the models from exploding.

**Comment by xpol** [comment]
👍

**Comment by leemalmac** [comment]
Does anyone working on this feature? I can try to implement it.

**Comment by mickhansen** [comment]
@leemalmac Think it would do well as a plugin

**Comment by faceleg** [comment]
Did this proceed any further?

**Comment by BrunoQuaresma** [comment]
Any update?

**Comment by jettangs** [comment]
need this.

**Comment by DiegoRBaquero** [comment]
I'm using `ajv` for this using JSON type:

```js
const Sequelize = require('sequelize')
const Ajv = require('ajv')

const ajv = new Ajv({allErrors: true})

class Schema extends Sequelize.Model {
  static init (sequelize) {
    return super.init({
      params: {
        type: Sequelize.JSON,
        allowNull: false,
        validate: {
          isValid (val) {
            ajv.compile({properties: val, required: Object.keys(val)})
          }
        }
      },
      examples: {
        type: Sequelize.ARRAY(Sequelize.JSON),
        allowNull: false,
        validate: {
          isArray (val) {
            if (!Array.isArray(val)) throw new Error('examples must be an array')
          }
        }
      }
    }, {
      sequelize,
      underscored: true,
      hooks: {
        afterValidate: (schema, options) => {
          const validate = ajv.compile({properties: schema.params, required: Object.keys(schema.params)})
          for (let i = 0; i < schema.examples.length; i++) {
            const example = schema.examples[i]
            const valid = validate(example)
            if (!valid) {
              const err = new Error('Invalid schema examples')
              err.errors = validate.errors.map(e => new Error(`example ${i}${e.dataPath} ${e.message}`))
              throw err
            }
          }
        }
      }
    })
  }
}

module.exports = Schema
```

Hope it helps

**Comment by eharango** [comment]
Example validation using [object-schema-validation](https://www.npmjs.com/package/object-schema-validation)
```js
import Schema from 'object-schema-validation';
const validSchema = new Schema({
  language: String,
  external: Boolean,
  content: {
    type: String,
    required: true
  },
  category: {
    name: {
      type: String,
      required: true
    }
  },
  tags: [{
    name: String,
    slug: String
  }]
});
```
Usign validate method in model
```js
sequelize.define('Post', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      unique: true,
      autoIncrement: true
    },
    data: {
      type: DataTypes.JSONB,
      allowNull: true,
      validate: {
        isEven(value) {
          const validateSchema = validSchema.validate(value);
          if (!validateSchema.valid) {
            throw new Error(validateSchema.error);
          }
        }
      }
    },
  }, {
    tableName: 'post',
  });
```

**Comment by kivervinicius** [comment]
Hello, any another update about this? Or new plugins to help this.

**Comment by kivervinicius** [comment]
https://github.com/kivervinicius/postgres-json-helper

**Comment by sunil-lulla** [comment]
+1 for the above requests. Also, I am looking for something as assigning default values, if the key is missing or non existing, any module or package for reference.
