### ISSUE TITLE
Question: Does get[Association] method always do a query to database?

### ISSUE THREAD

**Issue by fourpixels** [sequelize/sequelize#3707]
Hi guys,
I'm having a bit of struggling with this as I can't find it described in the docs - I have some associations and I get 'magic' methods from them. For example, I get `getUser`. But each time I call it, it makes an SQL query, and doesn't keep a state inside the DAO object.

My question is - is this an expected behavior, and if so - what's the best way to 'fix' it - make my own getters inside the model which keep internal state?

I've posted a question in SO if it's easier for you to answer there and not spam issues here: http://stackoverflow.com/q/30187289/2065080
Thanks in advance!

**Comment by mickhansen** [comment]
`getAssociation`  makes a query every time as you've deduced. We don't attempt to maintain any sort of cache, because then we run into the problem of having to invalidate that cache, and you know what the say about naming and cache invalidation :)

If you want to provide your own cache (with LRU or similar) you should overload the method or provide a custom one.

**Comment by fourpixels** [comment]
Thanks for the answer!

How can I overload the method, as I simply get it overriden by Sequelize? I can remove the association, but this way I will have to create ALL the methods (get, set, create). If I provide an instance method for simply 'get' and have association - mine gets wiped out.

Any ideas?

**Comment by fourpixels** [comment]
Oh, and by the way, I don't understand how to make proper queries with includes if I remove the association, right?
So I guess I end up having to implement custom methods with custom names. Isn't it better to be able to override those methods?

**Comment by mickhansen** [comment]
Something like this **after** already defining associations.

```js
var getUser = Model.Instance.prototype.getUser;
Model.Instance.prototype.getUser = function() {
  // LRU STUFF
  return getUser.apply(this, arguments);
};
```

**Comment by fourpixels** [comment]
I'm using a simple routine to load models from external files, and each one has `associate` class methods, which I call dynamically after all models are defined.

Isn't there some easy way I can change the order that sets those methods? Or at least insert a check if there is already an instanceMethod?!

**Comment by mickhansen** [comment]
You could add an `overload` class method that's called after `associate`.
No there's no real easy way, and if the code checked that it didn't already exist you wouldn't have access to the original method.

https://www.npmjs.com/package/shimmer helps a bit.

**Comment by fourpixels** [comment]
Well, uhm, I would just modify the code a little, like:

```js
HasOne.prototype.injectGetter = function(instancePrototype) {
  var association = this;

  // instancePrototype[this.accessors.get] = function(params) { // old way
  instancePrototype[this.accessors.get] = instancePrototype[this.accessors.get] || function(params) {
```

The only draw-back I see is that I **must** return Promise as well, for consistency. Oh, and a second one - I must do this in all associations :)

I would be more than happy if you think of some kind of a solution, as I don't understand why I have to create another method, instead of a simple check..

Anyways - thanks for the time!

**Comment by mickhansen** [comment]
The problem with that code is that you lose the original method, so you would never be able to call it, making it pretty hard to implement a cache or similar.

The best solution is using shimmer or similar for overloading.

**Comment by fourpixels** [comment]
I don't understand how shimmer would help, as I need to make the code in some specific class method which to be called after association, right? I don't understand how to merge two functions in two different places with shimmer.

This works for me:

    instancePrototype[
        (instancePrototype[this.accessors.get] ? '_'  : '') + this.accessors.get
    ] = function(params) {

So later I can simply use:
    instanceMethods: {
        getResource: function() {
            // some checks, etc.
            return this._getResource();
        }

I know it's a bit hacky, but still, I cannot afford to write bunch of functions in each model (unfortunately I have 22 models so far).

**Comment by mickhansen** [comment]
The shimmer lets you overload a method while having an easy reference to the original method.
Your approach is a way to go, but it's a design i highly dislike.

**Comment by fourpixels** [comment]
If you have some time to spend - I would love to understand how to shimmer it from two different files, I simply don't imagine how :)
And I agree about the latter ;)

**Comment by mickhansen** [comment]
@fourpixels Two different files, i'm not quite sure i understand what you mean by that? :)

**Comment by fourpixels** [comment]
Each of my models is in separate file. Then I loop through all the files and define/associate each of them. I don't understand how to use shimmer with your code or with mine. As far as I can see, I must create new class method, which to be called after `associate` method, in which I must use shimmer with Instance.prototype and wrap the getter/setter. Right?

To be honest - this doesn't sound good for my case, as I must write another method for each of my models (22 now), in which I can use shimmer to wrap Model.Instance.prototype's method. Tons of work for no benefits at all - if I override the method, I know I can use the previously mentioned approach (with underscore).

I am thinking how this can be done in lower level (Sequelize) in such a way that I won't need to write anything additional in each model, nor I will use shimmer each time. All I want is to just use my instance method instead of the injected one (switch override order).

**Comment by mickhansen** [comment]
Ah, then you'll probably want to shimmer at this level: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to.js#L97

We've talked previously about exposing association methods in a different way so they would be easier to use generically (which means they would also be easier to shim).

Something like having Association.getAsssociations(instance, options) and then instance.getAssociations(options) would map to that.

**Comment by fourpixels** [comment]
Sorry, again I don't understand how to shimmer at this level, as I must provide the wrapper function (which cannot be in belongs-to.js). Maybe I'm missing something out.. Anyways - it would be great if you come up with a nice solution to allow nicely overload of instance methods :) Thanks for the attention!

**Comment by mickhansen** [comment]
You'll have to include the file and shim the prototype method, like anything else.
Changing how those methods work are not a priority at the moment, but we'll get to it eventually probably.

**Comment by fourpixels** [comment]
@mickhansen - sorry for opening this up again, but I was just wondering - when creating model instance from association, is there any reason not setting it as a property? For example:

```js
models.Resource.create({ props: 1}).then(function(resource) {
    resource.createKeyword({ text: 'text' }) // this is available through association
    .then(function(keyword) {
        resource.getKeyword; // Promise
        resource.keyword; // undefined, but I have Resource.hasOne(Keyword, { as: 'keyword' })
    });
});
```

I guess that's part of the 'no state because of invalidation' idea, right? If so - the more I think about it, the more I have to wrap the whole ORM in another level of abstraction, as I have connections between models, but I cannot use them properly **without using query with includes**. Is that correct?

**Comment by mickhansen** [comment]
@fourpixels It's just never been developed, discussed a few times.
