### ISSUE TITLE
Bulk Update Bug

### ISSUE THREAD

**Issue by chanakyap** [sequelize/sequelize#3708]
User.update({status: 'deactivated'}, {where: {id: request.params.id}})

The expected result is just the status column should be updated, but the result i got is some other fields (not all) are getting set to null.

**Comment by mickhansen** [comment]
What version are you using?
This was fixed recently.

**Comment by chanakyap** [comment]
Hey, i just saw this in source
* @param  {Array}        [options.fields]                Fields to update (defaults to all fields)

do i need to set fields in options? i am using 2.0.4

**Comment by mickhansen** [comment]
It should really have been fixed here: https://github.com/sequelize/sequelize/commit/3f6f0764edb9d70b08351edeb5640546eb442056

No `fields` is not required.
Please provide a full model and sample.

**Comment by chanakyap** [comment]
Yeah, this is fixed in the recent version, the bug was in my colleague computer, who user older version. 
Closing this.
