### ISSUE TITLE
Problem with where in nested include

### ISSUE THREAD

**Issue by burakkilic** [sequelize/sequelize#3718]
Hi;

I have models Shop,Menu,Categories. Shop has many Menus, Menu have many categories and category has many sub-categories.

Statement is like:

```
db.shop.findOne({
    where: {
        code: req.params.code
    },
    include: [ {
        model: db.menu,
        where: {
            published: false
        },
        include: [ {
            model: db.category,
            where: {
                published: false
            },
            include: [{
                model: db.category,
                as: "SubCategories"
            }]
        }]
    }]
})
```

The first where statement in include (for menu.published: false) is working.

But second one, in the nested include statement, resulting with 

```
ER_BAD_FIELD_ERROR: Unknown column 'menus.id' in 'where clause'
```

**Comment by mickhansen** [comment]
Conditions on nested duplication relations has some issues.
Can you show the entire SQL? Is the inner join important or would it work with a LEFT JOIN? (in which case you can add `required: false` to the bad include).

**Comment by burakkilic** [comment]
The SQL is:

    Executing (default): SELECT `shop`.*, `menus`.`id` AS `menus.id`, `menus`.`order` AS `menus.order`, `menus`.`published` AS `menus.published`, `menus`.`createdAt` AS `menus.createdAt`, `menus`.`updatedAt` AS `menus.updatedAt`, `menus`.`shopId` AS `menus.shopId`, `menus`.`ThemeId` AS `menus.ThemeId`, `menus.categories`.`id` AS `menus.categories.id`, `menus.categories`.`order` AS `menus.categories.order`, `menus.categories`.`isListView` AS `menus.categories.isListView`, `menus.categories`.`published` AS `menus.categories.published`, `menus.categories`.`image` AS `menus.categories.image`, `menus.categories`.`createdAt` AS `menus.categories.createdAt`, `menus.categories`.`updatedAt` AS `menus.categories.updatedAt`, `menus.categories`.`shopId` AS `menus.categories.shopId`, `menus.categories`.`parentId` AS `menus.categories.parentId`, `menus.categories`.`menuId` AS `menus.categories.menuId` FROM (SELECT `shop`.`id`, `shop`.`code`, `shop`.`pincode`, `shop`.`hashedPassword`, `shop`.`salt`, `shop`.`website`, `shop`.`email`, `shop`.`phone`, `shop`.`locale`, `shop`.`twitter`, `shop`.`facebook`, `shop`.`foursquare`, `shop`.`instagram`, `shop`.`logo`, `shop`.`homepage`, `shop`.`background`, `shop`.`address`, `shop`.`city`, `shop`.`state`, `shop`.`zipCode`, `shop`.`country`, `shop`.`latitude`, `shop`.`longitude`, `shop`.`createdAt`, `shop`.`updatedAt`, `shop`.`accountId`, `shop`.`defaultLanguageId` FROM `shops` AS `shop` WHERE `shop`.`code` = 'QJRfundi' AND ( SELECT `shopId` FROM `menus` AS `menus` WHERE `shop`.`id` = `menus`.`shopId` AND `menus`.`published` = false LIMIT 1 ) IS NOT NULL AND ( SELECT `menuId` FROM `categories` AS `menus.categories` WHERE `menus`.`id` = `menus.categories`.`menuId` AND `menus.categories`.`published` = false LIMIT 1 ) IS NOT NULL LIMIT 1) AS `shop` INNER JOIN `menus` AS `menus` ON `shop`.`id` = `menus`.`shopId` AND `menus`.`published` = false INNER JOIN `categories` AS `menus.categories` ON `menus`.`id` = `menus.categories`.`menuId` AND `menus.categories`.`published` = false;

**Comment by mickhansen** [comment]
Hmm right, we don't actually support this since subquery filters dont support being nested atm (requires a join).

**Comment by burakkilic** [comment]
Do you suggest another way?

**Comment by mickhansen** [comment]
Not at the moment.
