### ISSUE TITLE
'@@' comparator for pg full text search

### ISSUE THREAD

**Issue by bleupen** [sequelize/sequelize#3721]
I have mapped an attribute with a raw tsvector type, which i would like to use in object-style where expressions. Is there an easy way to do this? I want to end up with an expression like:

```where terms @@ plainto_tsquery('english', 'my search terms')```

I am currently using a raw string to achieve this, which makes it harder to build larger queries. 

Thanks!

**Comment by BridgeAR** [comment]
Duplicate of #1580
