### ISSUE TITLE
Best way to associate one model to many models

### ISSUE THREAD

**Issue by DanMMX** [sequelize/sequelize#3734]
This belongs to `question` label.

I have several models: `Category`, `Event`, `GiftTable`, `Product` and `Subcategory`.

Each of these can have many Images. `Image` definition is the following:

```
var Image = sequelize.define('Image', {
	imgName: DataTypes.STRING
});
```

My idea about databases is that there should be join tables between `Category` and `Image`, `Event` and `Image`, etc. So I don't end up with one big `Images` table having a `CategoryId`, `EventId`, etc, having `null`.

The associations I have are the following:

```
Image.belongsTo(Product, { through: 'ProductImages', as: 'Product'});
Image.belongsTo(Category, { through: 'CategoryImages', as: 'Category'});
Image.belongsTo(Subcategory, { through: 'SubcategoryImages', as: 'Subcategory'});
Image.belongsTo(GiftTable, { through: 'GiftTableImages', as: 'GiftTable'});
Image.belongsTo(Event, { through: 'EventImages', as: 'Event'});

Category.hasMany(Image, { through: 'CategoryImages' });
GiftTable.hasMany(Image, { through: 'GiftTableImages' });
Product.hasMany(Image, { through: 'ProductImages' });
Subcategory.hasMany(Image, { through: 'SubcategoryImages' });
Event.hasMany(Image, { through: 'EventImages' });
```

But I end up having the undesired `Image` table with many `OtherModelId` columns PLUS the tables defined in the `through` attribute.

Also, when setting another model to the `Image` model with `setProduct`, `setCategory`, etc, the only table affected is the `Images` table adding the required `ModelId` instead of the `ModelImages` table with a new row.

Not sure if I should use `belongsToMany` on one or both associations because that makes no sense when reading because an `Image` only belongs to one of the other models.

Just read about [this](http://docs.sequelizejs.com/en/latest/docs/associations/#1m), but haven't tested, is that the best way?

**Comment by DanMMX** [comment]
I've used scopes for associations the following way

On 1:m

```
var Image = sequelize.define('Image', {
	name: DataTypes.STRING,
	owner: DataTypes.STRING,
	ownerId: DataTypes.INTEGER
}, {
	instanceMethods: {
		getItem: function() {
			return this['get' + this.get('owner').substr(0, 1).toUpperCase() + this.get('owner').substr(1)]();
		}
	}
});

```

and the associations the following way:

```
Category.hasMany(Image, { foreignKey: 'ownerId', scope: {
	owner: 'category'
}});

Event.hasMany(Image, { foreignKey: 'ownerId', scope: {
	owner: 'event'
}});

GiftTable.hasMany(Image, { foreignKey: 'ownerId', scope: {
	owner: 'giftTable'
}});

Product.hasMany(Image, { foreignKey: 'ownerId', scope: {
	owner: 'product'
}});

Subcategory.hasMany(Image, { foreignKey: 'ownerId', scope: {
	owner: 'subcategory'
}});

Image.belongsTo(Category, {
	foreignKey: 'ownerId',
	as: 'category'
});

Image.belongsTo(Event, {
	foreignKey: 'ownerId',
	as: 'event'
});

Image.belongsTo(GiftTable, {
	foreignKey: 'ownerId',
	as: 'giftTable'
});

Image.belongsTo(Product, {
	foreignKey: 'ownerId',
	as: 'product'
});

Image.belongsTo(Subcategory, {
	foreignKey: 'ownerId',
	as: 'subcategory'
});
```

But it ends up referencing the first defined association not allowing me to do `product.createImage({name: 'img.png'});` because the produced error `SequelizeForeignKeyConstraintError`

```
CREATE TABLE IF NOT EXISTS `Images` (
	`id` INTEGER NOT NULL auto_increment ,
	`name` VARCHAR(255),
	`owner` VARCHAR(255),
	`ownerId` INTEGER,
	`createdAt` DATETIME NOT NULL,
	`updatedAt` DATETIME NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`ownerId`) REFERENCES `Categories` (`id`) 
	ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
```

btw… I think the docs are wrong having

```
Image.createComment({
  title: 'Awesome!'
})
```

and should be image (an Image instance)

**Comment by janmeier** [comment]
This is currently the best approach, until https://github.com/sequelize/sequelize/issues/1307
