### ISSUE TITLE
Sequelize 3.0 & Newrelic

### ISSUE THREAD

**Issue by szantner** [sequelize/sequelize#3737]
Hey guys,

Thanks for the amazing work. I just updated my project to sequelize 3.0. Everything went fine except for newrelic integration. After upgrading to sequelize 3.0 when I use newrelic and the program runs on an error, the error object is merged with a lot of newrelic info (which has actually circular references according to node's util.format) and because of the circular references execution hangs and express doesn't get to send the json response.
I know it doesn't really sound like a sequelize error, but before the update I had no problems with that of any kind. 
I use Express, Sequelize, MySql and a lot of other packages. At the time of upgrading to sequelize 3.0 I updated no other npm packages.

**Comment by BridgeAR** [comment]
3.0 contains a conflict right now and is unusable. Please wait until 3.0.1

**Comment by szantner** [comment]
Thx for the quick response. Do you have maybe info on when 3.0.1 will be out?

**Comment by BridgeAR** [comment]
I guess tomorrow morning

**Comment by szantner** [comment]
Super, thank you again.

**Comment by BridgeAR** [comment]
The issue that I thought that would still have been open was resolved and I did not check that properly. I have no clue about newrelic though. Do you have a stacktrace for me to have a look at things?

**Comment by szantner** [comment]
That is not good news for me. So I can't give you a stacktrace, but I try to describe the phenomenon more properly.

So in a Promise chain when I reject a Promise like this:

Promise.resolve()
  .then(function() {
    return new Promise(function(resolve, reject) {
      reject('something went wrong');
    });
  })
  .catch(function (err) {
    console.log(err);
  });

It works fine as before at the catch part of the Promise chain.

On the other hand when I use throw, like this:

Promise.resolve()
  .then(function() {
    throw {error: 'error'};
  })
  .catch(function (err) {
    console.log(err);
  });
 
In this case in the catch part Newrelic attaches a lot of extra info to the err object, that starts like this:
__NR_transaction: {
      "agent": {
        "domain": null,
        "_events": {},
        "_state": "starting",
        "config": {

This even happens when there is no sequelize call of any kind in the Promise chain, so I guess this is something general. Definitely started to experience after updated to sequelize 3.0.0 

I'll continue my investigation. If any new info comes up, I'll let you know.

**Comment by mickhansen** [comment]
What version did you upgrade from?
Might have been the bluebird upgrade.

**Comment by szantner** [comment]
Even worse. I went back to 2.1.3 and I have the same problem there with newrelic, that I didn't have before. Until I can localize the problem better I close the issue.

**Comment by szantner** [comment]
I downgraded bluebird manually and it didn't help.

**Comment by szantner** [comment]
And the upgrade to 3.0.0 was from 2.1.3

**Comment by mickhansen** [comment]
We upgraded bluebird before 2.1.3 so yeah that probably wouldn't be it.

**Comment by szantner** [comment]
That is really strange that getting back to 2.1.3 doesn't solve the problem. I'll post it on Newrelic forums maybe I'll get an answer.
