### ISSUE TITLE
Question: Referencing fields while creating records with include option

### ISSUE THREAD

**Issue by bbird1980** [sequelize/sequelize#3749]
Creating records using include options, example:
```
models.versions.create({version:'1', title:'test create', parent_id:'3', versions_state: {version_id:123}}, {include:[{model:models.versions_states}]})
```

Execution generates two SQL:
```
INSERT INTO "versions" ("id") VALUES (DEFAULT) RETURNING *;
INSERT INTO "versions_states" ("version_id") VALUES (123) RETURNING *;
```

Can i reference versions_state.version_id (instead of test value=123) to versions.id of inserted by first SQL record in this usage case? Of course i can do this by splitting this create by two: models.versions.create().then( models.versions_states.create ) or i can use DB sequence current value, but associated create is nice shorthand.

---

Models definitions:

```
export default function(sequelize, DataTypes) {
    return sequelize.define('versions', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
    },{
        classMethods: {
            associate(models) {
                models.versions.hasOne(models.versions_states, {foreignKey:'version_id'});
            }
        }
    });
};
```
```
export default function(sequelize, DataTypes) {
    return sequelize.define('versions_states', {
        version_id: {
            type: DataTypes.INTEGER,
            primaryKey: true
        }
    });
};
```

**Comment by janmeier** [comment]
Have you tried leaving out the version id completely? Sequelize should set it automagically

**Comment by mickhansen** [comment]
Nested create should automatically set foreign keys.
The issue is more likely that you have your foreign key as your primary key, i'm not totally certain that will work as expected.

**Comment by bbird1980** [comment]
Oops, I missed this simplest solution to don't specify version_id. It works. Thanks a lot!
