### ISSUE TITLE
[Question] GetterMethods & Promises

### ISSUE THREAD

**Issue by sebay00** [sequelize/sequelize#3750]
Hi fellas,

I would like to do some (sequelize) querying in a getterMethods, is there any solution to do that ?
I would like to list the free slots of a room : 
```
var Room      = module.exports = orm.define("Room", {
  name: { type: Sequelize.STRING },
  capacity: { type: Sequelize.INTEGER.UNSIGNED }
}, {
  getterMethods: {
       slots : getAvailableSlots()
  }
});
```

Knowing that `getAvailableSlots()` is a function fetching and returning some data of an Other Model. 

Until now, I succeed to get that : 
```
        "slots": {
            "isFulfilled": false,
            "isRejected": false
        },
```
:+1:

**Comment by mickhansen** [comment]
We don't support asynchronicity in attribute getters.
You should fetch slots async or via includes.
