### ISSUE TITLE
Connect through SSH

### ISSUE THREAD

**Issue by Hyra** [sequelize/sequelize#3753]
Our MySQL servers are only accessible through 127.0.0.1 and require a SSH connection to the server first.

With apps like Sequel Pro this is possible, is it also configurable through the Sequelize connection options?

**Comment by mickhansen** [comment]
We don't support SSH tunneling out of the box, but you can easily use something like the npm package `ssh-tunnel` to set it up before init'ing sequelize.

**Comment by Hyra** [comment]
Ah that actually works perfectly. Thank you kindly sir.

**Comment by hxtruong** [comment]
> Ah that actually works perfectly. Thank you kindly sir.

Can you guide me how to connect DB with SSH tunnel? I tried to do it but it's failed.

**Comment by dahalg** [comment]
This will allow you to securely connect to the RDS instance from your local machine. 
https://repost.aws/questions/QUuRQ-oorMQLahG6egHb4-bg/how-can-i-connect-to-a-private-amazon-rds-instance-from-local-node-js-application-which-was-earlier-using-non-ssh-sequelize-connection

**Comment by Uniphix** [comment]
> This will allow you to securely connect to the RDS instance from your local machine. https://repost.aws/questions/QUuRQ-oorMQLahG6egHb4-bg/how-can-i-connect-to-a-private-amazon-rds-instance-from-local-node-js-application-which-was-earlier-using-non-ssh-sequelize-connection

This helped me thank you!
