### ISSUE TITLE
transaction - 

### ISSUE THREAD

**Issue by ieow** [sequelize/sequelize#3763]
Hi, 

I am wondering how is the flow for the code below:

sequalize.transaction(function ( sqltransaction){
  db.create( {where: opts }, {transaction: sqltransaction} )
  db.create( {where: opts1 }, {transaction: sqltransaction} )
  db.create( {where: opts2 }, {transaction: sqltransaction} )
  db.create( {where: opts3 }, {transaction: sqltransaction} )
  db.create( {where: opts4 }, {transaction: sqltransaction} )
  return db.create( {where: opts5  }, {transaction: sqltransaction} )
}).then( function {

}).catch ();

Does the transaction return promise for all create is done or just the create opts5 is done.
I could run the code but i could not observe the how it  flow.

Please advice.

**Comment by mickhansen** [comment]
This is more a promise question than a sequelize question, please read documentation on how promises work.

You need to return the promise you resolve on, so no the 5 other creates will be ignored.
Use `Promise.all` or `Promise.join` and read https://github.com/petkaantonov/bluebird/blob/master/API.md
