### ISSUE TITLE
seems like timezone doesn't work

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#3768]
Hi,

Just found out, that the values from our PostgreSQL are selected despite the timezone configuration option, which is set by default to '00:00'.

The selected values look like:
```
{ id: '15',
  xxx: 'xxx',
  created_date: Sat May 16 2015 04:00:46 GMT+0200 (CEST),
  due_date: Sat Apr 18 2015 00:00:00 GMT+0200 (CEST),
  xxx: '-xxx',
  xxx: null,
  xxx: 'xxx',
  xxx: 'xxx',
  xxx: null }
```

How to check that ***timezone*** is indeed working?

Regards,

**Comment by mickhansen** [comment]
@PavelPolyakov The output you provided doesn't actually show that the dates are wrong. You are likely logging a javascript date object which will usually display in your local time zone.

You can verify it's indeed working by looking at the raw data instead.

**Comment by PavelPolyakov** [comment]
@mickhansen 
In the postgreSQL the data stored like timestamp

```sql
    created_date TIMESTAMP,
    due_date TIMESTAMP,
```

What I log is:
```javascript
console.log(record.toJSON());
```

Is something wrong with my approach ?

**Comment by mickhansen** [comment]
What's the raw value in postgres? If it's `Sat May 16 2015 06:00:46` then it's correct, if not there's a bug.
@PavelPolyakov You are logging javascript date objects, so you can't expect them to have 00:00 as timezone (they'll use your local timezone), but they should work fine with UTC values, converting them internally.

**Comment by PavelPolyakov** [comment]
@mickhansen 
Here are the database values:
![image](https://cloud.githubusercontent.com/assets/839290/7728191/f106f09c-ff0d-11e4-8be6-693368fcfde5.png)

**Comment by mickhansen** [comment]
Then it does appear to be a bug.
You'll have to share your configuration etc, maybe @janmeier can help.

**Comment by PavelPolyakov** [comment]
My sequelize connection looks the next way:

```javascript
var sequelize = new Sequelize(config.get('database.database'), config.get('database.username'), config.get('database.password'), {
    dialect:  'postgres',
    protocol: 'postgres',
    port:     config.get('database.port'),
    host:     config.get('database.host'),
    logging:  debug, //false

    timezone:'+00:00',

    dialectOptions: {
        ssl: true
    },

    pool: {
        max: 20,
        min: 0,
        idle: 5000
    }
});
```

That's the table DDL:
```sql
CREATE TABLE xxx_xxx
(
    id SERIAL DEFAULT nextval('seq_seq'::regclass) NOT NULL,
    uuu BIGINT,
    created_date TIMESTAMP,
    due_date TIMESTAMP,
    xxx BIGINT,
    yyy VARCHAR(100),
    qqq VARCHAR(100),
    www BIGINT,
    eee BIGINT,
    rrr VARCHAR(255),
    ttt BIGINT
);
```

**Comment by janmeier** [comment]
Sequelize expects timestamp with timezone in postgres

**Comment by PavelPolyakov** [comment]
@janmeier 
So, if there is a timestamp without the timezone, then sequelize would put the current node timezone? 

Could we do something about it? Together with hapijs issue ( https://github.com/hapijs/hapi/issues/2542 ) it makes a time shift, which we doesn't expect to have :)

Any advice?

**Comment by janmeier** [comment]
Technically, sequelize does not, node pg does - since it automatically converts the string from the db to a date object, assuming that the date is in the current timezone of the server. This is an implementation detail of javascript. 

There is another issue relating to this with a fix included. I'll try to find it in a bit

**Comment by PavelPolyakov** [comment]
@janmeier 
Thanks, looking forward for the link.

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/docs/models-definition/#data-types looks for the `setTypeParser` part

I believe I had a discussion with someone about integrating this code into sequelize. There was a reason not to do it, but I can find the issue or remember the reasoning right now :)

**Comment by PavelPolyakov** [comment]
@janmeier 
Thanks!

**Comment by PavelPolyakov** [comment]
btw,

how we've solved it:
```
var postgres = require('pg');

postgres.types.setTypeParser(1114, function(stringValue) {
    return moment(stringValue).format('YYYY-MM-DD HH:mm:ss');
});
```

The one from the link was not working.

**Comment by janmeier** [comment]
But won't that return a string and not a date object?
