### ISSUE TITLE
Raw queries: multiple values in replacement

### ISSUE THREAD

**Issue by kirill-zhirnov** [sequelize/sequelize#3769]
``` coffee
    db.query "
        delete from characteristic where id in (:list)
    ", null, {
        replacements :
            list : [1,2,3]
    }
```

Will execute query:

``` sql
delete from characteristic where id in (ARRAY[1,2,3])
```

Is it possible to quote multiple values?

**Comment by janmeier** [comment]
What do you mean? You can add multiple replacements by adding more parameters to the query if thats wht you mean?

**Comment by kirill-zhirnov** [comment]
I need to put multiple values in "IN ()" condition. I can use more parameters, e.g. "IN (?,?,?)", but in this case I need also to generate SQL query:

```coffeescript
values = ['a', 'b', 'c']

sql = []
for value in values
	sql.push '?'

db.query "
        delete from characteristic where id in (#{sql.join(',')})
    ", null, {
	replacements : values
}
```
It is not really convenient. What would be nice:

```coffeescript
    db.query "
        delete from characteristic where id in (:list)
    ", null, {
        replacements :
            list : [1,2,3]
    }
```

and in the end have SQL:
```coffeescript
delete from characteristic where id in (1,2,3)
```

**Comment by mickhansen** [comment]
I was sure we had fixed this bug but it keeps popping up :p

**Comment by BridgeAR** [comment]
@kirill-zhirnov What version do you use? You're using an older version.

**Comment by majodev** [comment]
Just check the newest version 3.2.0 - same problem.

**Comment by blakmatrix** [comment]
can confirm for `3.2.0`

**Comment by ChaliceG** [comment]
Issue is still present in 3.6.0

**Comment by adonomay** [comment]
+1

**Comment by toddbluhm** [comment]
+1

**Comment by zackexplosion** [comment]
+1

**Comment by leibale** [comment]
+1

**Comment by nazar** [comment]
+eleventy

**Comment by ncwhale** [comment]
Still got this problem, when try to query with `IN ($1::uuid[])`

**Comment by steaks** [comment]
+1

**Comment by felixfbecker** [comment]
This will not work with bound parameters. You can use the ANY operator to accomplish this, it will bind the (single) parameter to the array.

Please do not +1 issues, it clutters the thread and adds no value to the discussion. Use GitHub reactions.

**Comment by amarewgs** [comment]
+1

**Comment by amarewgs** [comment]
this works for me

`
var roleIds = roles.map(role => role.id);
var query = 'select program_id, rating_value,  ((COUNT( * ) / ( SELECT COUNT( * ) FROM rating where program_id = r.program_id group by program_id '
        + ' )) * 100 ) AS percentage, p.title as title from rating r INNER JOIN program p on p.id = r.program_id '
        + whereClause + ' group by program_id, rating_value';

      console.log('query build ' + query);

      return sqldb.sequelize.query(query, {model: Rating, nest: true, replacements: {roleIds: roleIds}, type: 'SELECT'}).then(ratings => {

        console.log('percentage ratings ' + JSON.stringify(ratings));

        return res.json(ratings);
      })
        .catch(err => next(err));
    });`

**Comment by rickyk586** [comment]
From docs (https://github.com/sequelize/sequelize/issues/3769):

> Array replacements will automatically be handled, the following query searches for projects where the status matches an array of values.
> ```sql
> sequelize.query('SELECT * FROM projects WHERE status IN(:status) ',
>   { replacements: { status: ['active', 'inactive'] }, type: sequelize.QueryTypes.SELECT }
> ).then(projects => {
>   console.log(projects)
> })
> ```
