### ISSUE TITLE
isEmail validator does not work (as described in documentation)

### ISSUE THREAD

**Issue by vladh** [sequelize/sequelize#3770]
The documentation states that this should work:

```coffeescript
validate: {
  isEmail: true
}
```

However, this yields:

```
{
  __raw: [TypeError: Cannot assign to read only property 'allow_display_name' of true],
  message: 'Cannot assign to read only property \'allow_display_name\' of true',
  path: 'email',
  type: 'Validation error',
  value: [TypeError: Cannot assign to read only property 'allow_display_name' of true]
},
```

The correct value `validator.js` expects is:
```coffeescript
validate: {
  isEmail: {}
}
```

**Comment by BridgeAR** [comment]
What version do you use? This should have been [fixed] (https://github.com/sequelize/sequelize/commit/04f1e1f01f0196fc3fba6d7ec636ded6c7fc7d6b#diff-6eed5d5a54bdcfa65b0d7f6557362965)

**Comment by vladh** [comment]
I'm on 3.0.1. I do have that code — maybe I'm doing something dumb. Here's what I'm trying:

```coffeescript
    email: {
      type: DataTypes.STRING
      allowNull: false
      validate: {
        isEmail: {args: true, msg: 'phy-simpleUser-email-invalid'}
      }
    }
```

**Comment by BridgeAR** [comment]
It should work if you remove `args: true`.

**Comment by vladh** [comment]
So it does! I was under the impression that that was required.
