### ISSUE TITLE
Sequelize and MySQL Cluster?

### ISSUE THREAD

**Issue by hurricane766** [sequelize/sequelize#3772]
Hi,

I am faced with the production issue of needing redundant (HA) architecture for a MySQL database. Which means not only have master-slave replication, but master-master replication (because if the master goes down the application goes down until a slave can be promoted). I am admittedly new to this kind of solution, so maybe I'm thinking about it the wrong way - but I appreciate your input.

Can Sequelize work with MySQL Cluster? It does look to me like it only allows for singular database connections, not some kind of array of possible connection for it to use something [like this](https://github.com/felixge/node-mysql/#poolcluster).

Thanks

**Comment by mickhansen** [comment]
We don't support master/master replication out of the box.
We do however support master/slave (also known as read replication) where Sequelize will round robin the slaves when reading.

**Comment by shivambarsaley** [comment]
Hi @mickhansen 
I am currently facing a similar problem like @hurricane766 
Does Sequelize support a M-M replication, I am using v4.35 currently

Thanks,
