### ISSUE TITLE
Handling of connection failures (documentation / missing feature / bug?)

### ISSUE THREAD

**Issue by fpauser** [sequelize/sequelize#3779]
I use sequelize in an express-app with the mssql-dialect (tedious). I organized the models according to the [example-app](https://github.com/sequelize/express-example/blob/master/models/index.js), but what is unclear to me is how to catch connection-errors that might come up.

Testing with a misconfigured/unreachable host gives me: 

    Unhandled rejection SequelizeHostNotReachableError: Failed to connect to [..] - connect EHOSTUNREACH

So my question is, what is the standard way of handling connection errors with sequelize?

**Comment by janmeier** [comment]
Normally, the first call that hits the database will try to create a connection. So often `sequelize.sync`, or if you are not syncing, then the first `model.find` etc. To the test connection you can manually tell sequelize to authenticate - so you could do

```js
sequelize.authenticate().catch(function () {
  // Handle misconfigurations here
});
```

However, if you have set your pooling config to always keep x number of open connections, the connections will be create and fail before you can attach a listener. In this case, use [domains](https://nodejs.org/api/domain.html) or [uncaughtException](https://nodejs.org/api/process.html#process_event_uncaughtexception)

Other than that - please refer to https://github.com/sequelize/sequelize/issues/2113 (which we will hopefully soon come around to providing a solution for
