### ISSUE TITLE
AddMissing[foreign]s([]) to add only missing relationships

### ISSUE THREAD

**Issue by slawo** [sequelize/sequelize#3783]
Would it be possible to add an option to add only items which are not yet in the relationship.

For temple if project 2, 3 and 4 are already in the user's backlog  `user.addMissingProjects(projects)` with `projects` containing projects 3, 5, and 7 should not try to add project 3 but still add 5 and 7 to the relationship.

This could save a lot of time in many situations.

**Comment by janmeier** [comment]
That already happens - `add` check if the two instances are already associated, and if not associates them

**Comment by slawo** [comment]
I get errors when I try that (3.0):

	Unhandled rejection SequelizeUniqueConstraintError: Validation error
	    at module.exports.Query.formatError (/Users/slawo/devel/projects/forma-k/foma-c/node_modules/sequelize/lib/dialects/sqlite/query.js:231:16)
	    at Statement.<anonymous> (/Users/slawo/devel/projects/forma-k/foma-c/node_modules/sequelize/lib/dialects/sqlite/query.js:48:31)
	    at Statement.replacement (/Users/slawo/devel/projects/forma-k/foma-c/node_modules/sqlite3/lib/trace.js:20:31)

**Comment by mickhansen** [comment]
@slawo then there might be a bug, it should definitely be supported. Please post your models and relations and code to trigger the error.

**Comment by janmeier** [comment]
Aah, I thought you meant that it would never even try to add those that were missing. In that case we already have a bug [here](https://github.com/sequelize/sequelize/issues/3592) and I'm working on it right now

**Comment by slawo** [comment]
Wouldn't it be better to leave the current behaviour on Add[foreign]s() and implement AddMissing[foreign]s() to make sure this behaviour is kept (we might want to fail on Add is some associations are already made).

**Comment by janmeier** [comment]
That would be a BC break - the behaviour has always been to ignore the missing ones, this is just a bug in BTM

**Comment by janmeier** [comment]
I see the merits, but we've never had the request before - Why would you want to fail if is it already associated?

**Comment by slawo** [comment]
In order to break the promise chain when we are adding relationships that are not supposed to be added.

On the other hand it's possible to check it the entry has just been added or not, so this point is probably moot.

**Comment by mickhansen** [comment]
@slawo I believe we have a feature request somewhere for `failOnExisting` or similar for association adders.
