### ISSUE TITLE
Polymorphic Association with multiple models having error

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3785]
Hi guys , I'm trying implement Polymorphic association with many models , I have a collection that can have many works and products , and the product and work can belong to many collections and this works and products would reorder positions inside the collection then I have the order field in CollectionItem.

Collection

``` javascript
Collection.belongsToMany(models.Work, {
    as: 'work',
    through: {
        model: models.CollectionItem,
        unique: false
    },
    foreignKey: 'collection_id'
});

Collection.belongsToMany(models.Product, {
    as: 'product',
    through: {
        model: models.CollectionItem,
        unique: false
    },
    foreignKey: 'collection_id'
});
```

Work

``` javascript
Work.belongsToMany(models.Collection, {
    through: {
        model: models.CollectionItem,
        unique: false,
        scope: {
            taggable: 'work'
        }
    },
    foreignKey: 'collectable_id',
    constraints: false
});
```

Product

``` javascript
Product.belongsToMany(models.Collection, {
    through: {
        model: models.CollectionItem,
        unique: false,
        scope: {
            taggable: 'product'
        }
    },
    foreignKey: 'collectable_id',
    constraints: false
});
```

CollectionItem

``` javascript
var CollectionItem = sequelize.define('CollectionItem', {
    order: {type: DataTypes.INTEGER, defaultValue: 0},
    collection_id: {
        type: DataTypes.INTEGER,
        unique: 'item_collection_collectable'
    },
    collectable: {
        type: DataTypes.STRING,
        unique: 'item_collection_collectable'
    },
    collectable_id: {
        type: DataTypes.INTEGER,
        unique: 'item_collection_collectable',
        references: null
    }
})
```

Then when I'm adding works or products to the collection , I'm getting this error

``` javascript
   collection.addWork(work);
```

``` javascript
Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at module.exports.Query.formatError (/Users/juliocanares/Sites/work/arte-manifiesto/node_modules/sequelize/lib/dialects/mysql/query.js:131:16)
    at Query._callback (/Users/juliocanares/Sites/work/arte-manifiesto/node_modules/sequelize/lib/dialects/mysql/query.js:35:23)
```

**Comment by janmeier** [comment]
scope `taggable: 'work'` should be collectable, right?

Which columns are being violated by the unique constraint error? Can you show a self-contained example to reproduce the problem?

**Comment by juliocanares** [comment]
Yes I change the taggable for collectable and the error persist 

this is my query 

```javascript
global.db.Collection.findAll({limit: 1}).then(function (collections) {
    var collection = collections[0];
    global.db.Work.create({name: 'New work'}).then(function (work) {
        collection.addWork(work).then(function () {
            return res.json(collection);
        });
    });
});
```
this is the sql generated

```javascript
INSERT INTO `CollectionItems`
(`order`,`collection_id`,`collectable_id`,`updatedAt`,`createdAt`) 
VALUES (0,1,2,'2015-05-21 10:12:35','2015-05-21 10:12:35');
```
I'm using sequelize 2.1.3

**Comment by janmeier** [comment]
You need to add the scope to both sides of the association - its missing in collection -> work and collection -> product. This means that sequelize misses the fact that the relation already exists, and tries to insert a duplicate

**Comment by juliocanares** [comment]
I'm trying adding scopes in collection -> work and collection -> product 

```javascript
Collection.belongsToMany(models.Work, {
    as: 'work',
    through: {
        model: models.CollectionItem,
        unique: false,
        //scope
        scope: {
            collectable: 'work'
        }
    },
    foreignKey: 'collection_id'
});

Collection.belongsToMany(models.Product, {
    as: 'product',
    through: {
        model: models.CollectionItem,
        unique: false,
       //scope
        scope: {
            collectable: 'product'
        }
    },
    foreignKey: 'collection_id'
});
```

but when adding work to collection
```javascript
global.db.Collection.create({name: 'New Collection'}).then(function (collection) {
    global.db.Work.create({name: 'New work'}).then(function (work) {
        collection.addWork(work).then(function () {
            return res.json(collection);
        });
    });
});
```
getting this error

```javascript
Unhandled rejection TypeError: Cannot set property 'collectable' of undefined
    at /Users/juliocanares/Sites/work/arte-manifiesto/node_modules/sequelize/lib/associations/belongs-to-many.js:537:43
```

**Comment by janmeier** [comment]
Hmm, seems to be caused by this line - https://github.com/sequelize/sequelize/blob/v2.1.3/lib/associations/belongs-to-many.js#L537  additionalAttributes is undefined - should be fixable by passing {} as the second argument.

This does not happen on 3.0 because we use _.assign instead which works even if the first argument is undefined ... There is still need for some general cleanup in that part of the code though :)

**Comment by juliocanares** [comment]
I updated to  3.1 and its working :dancers:  , but I have a new error 

When I'm inserting only one work  to the collection work fine , but if I add a product to the collection
this show this error

```javascript
Unhandled rejection SequelizeUniqueConstraintError: Validation error
```

Maybe is because the collection_id not can duplicate , In sequel pro I try add product and work with for same collection and I get this error

![Image of sequelize](http://i.imgur.com/RnCL7f7.png)

**Comment by mickhansen** [comment]
@juliocanares use a single primary key instead

**Comment by juliocanares** [comment]
I need change the foreign key by primary key  , like this ?

```javascript
Collection.belongsToMany(models.Work, {
    as: 'work',
    through: {
        model: models.CollectionItem,
        unique: false,
        scope: {
            collectable: 'work'
        }
    },
    //foreignKey: 'collection_id',
    primaryKey: 'collection_id'
});
```

**Comment by mickhansen** [comment]
@juliocanares No you need to set a primary key on the through model, i suggest using `id` instead of a multi column primary key.

**Comment by juliocanares** [comment]
but where I need add ```id``` field , in my CollectionItem or how is the correct way?

**Comment by janmeier** [comment]
Yes, you should manually add an id field to CollectionItem.

Sequelize automatically adds an id key, but removes it again if the model is used in n:m - because that is often the most sensible :). But in this case, to tell sequelize that you really want an id primary key, you can explicitly add it to the model definition

**Comment by demege** [comment]
Guys,
Thanks a lot!, this solve all my problems :)
Will be good if you can add this Polymorphic Association Example to the Docs. So people can use it.
