### ISSUE TITLE
createdAt/updatedAt doesn't use the millisecond precision with SQLite

### ISSUE THREAD

**Issue by arcanis** [sequelize/sequelize#3793]
As the title say, the createdAt and updatedAt fields have a 0 milliseconds field when persisted on SQLite.

It is due to the following line: [lib/utils.js#L318](https://github.com/sequelize/sequelize/blob/abe7dfbaa427677c5fa2fc8d33e5123e6fd1ea4f/lib/utils.js#L318)

I guess that the condition should be same than [this one](https://github.com/sequelize/sequelize/blob/abe7dfbaa427677c5fa2fc8d33e5123e6fd1ea4f/lib/sql-string.js#L174-L179)

**Comment by janmeier** [comment]
Hmm, yeah I'm not even sure we need to set it to 0, since the milliseconds are never inserted into the DB. But it might be related to testing, not sure.

PR welcome - not even sure we'd require a test for this one if all tests pass simply by removing that line / adding an if :)
