### ISSUE TITLE
Stringify Model Definition

### ISSUE THREAD

**Issue by danilosampaio** [sequelize/sequelize#3794]
Hi,

I'm trying to stringify my model definition, but i get this error:

```TypeError: Converting circular structure to JSON```

this problem is similar to https://github.com/sequelize/sequelize/pull/141

in my case, i need stringify the model definition instead of the object values.

Is there a way to achieve this?

**Comment by mickhansen** [comment]
Not quite similar to #141 since instances have a obvious serialization target.
You'll have to find out where the circular structure appears and then not stringify that part.

One circular atleast would be `Model -> sequelize -> models -> Model`
