### ISSUE TITLE
inconsistent 'returning id' for UPDATE and DELETE (postgres)

### ISSUE THREAD

**Issue by pkoretic** [sequelize/sequelize#3795]
here is an example of a mentioned problem (never mind the es6 parts):
```
'use strict'
var co = require('co')
var Sequelize = require('sequelize')

var db = new Sequelize("postgres://...")

co(function*() {

    try {
        yield db.query("drop table if exists test_table")
        yield db.query("create table test_table(id integer primary key, name text)")

        for (let i = 0; i < 10; i++)
            yield db.query(`insert into test_table values(${i}, 'name${i}' )`) 
    }   
    catch (error) {
        console.log(error)
    }   

    // relevant part
    db.query("update test_table set name = 'test' returning id").spread(function(result, metadata) {
        console.log("update result:", result)
        console.log("update metadata:", metadata)

        db.query("delete from test_table where name = 'test' returning id").spread(function(result, metadata) {
            console.log("delete result:", result)
            console.log("delete metadata:", metadata)
        })  
    })  
})
```
which ends up returning
```
Executing (default): drop table if exists test_table
Executing (default): create table test_table(id integer primary key, name text)
Executing (default): insert into test_table values(0, 'name0' )
Executing (default): insert into test_table values(1, 'name1' )
Executing (default): insert into test_table values(2, 'name2' )
Executing (default): insert into test_table values(3, 'name3' )
Executing (default): insert into test_table values(4, 'name4' )
Executing (default): insert into test_table values(5, 'name5' )
Executing (default): insert into test_table values(6, 'name6' )
Executing (default): insert into test_table values(7, 'name7' )
Executing (default): insert into test_table values(8, 'name8' )
Executing (default): insert into test_table values(9, 'name9' )
Executing (default): update test_table set name = 'test' returning id

// relevant part
update result: { id: 0 }
update metadata: { id: 1 }
Executing (default): delete from test_table where name = 'test' returning id
delete result: [ { id: 0 },
  { id: 1 },
  { id: 2 },
  { id: 3 },
  { id: 4 },
  { id: 5 },
  { id: 6 },
  { id: 7 },
  { id: 8 },
  { id: 9 } ]
delete metadata: { command: 'DELETE',
  rowCount: 10,
  oid: NaN,
  rows: [],
  fields: 
   [ { name: 'id',
       tableID: 181352,
       columnID: 1,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function] ],
  RowCtor: [Function],
  rowAsArray: false,
  _getTypeParser: [Function] }
```

so because of some reason in update statement result is completely different than in delete and not all fields get returned
doing this from postgres console or adminer all id's get returned so it seems that update return from sequelize is wrong?

**Comment by janmeier** [comment]
Hmm, it seems there is still a bit of our 'too-smart-for-its-own-goode' code left for raw queries - this code also checks `.indexOf update` to determine query type https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query.js#L156-L161

Hmm, guess this should be removed @mickhansen . I guess we could say that some people might be  relying on this behaviour right now but then again, we've said that raw is raw, so you should be manually specifying query type ....

**Comment by pkoretic** [comment]
@janmeier
just for completeness since I'm not sure if I understood if there is something for me in your comment :)
 
this is result with { type : Sequelize.QueryTypes.UPDATE } and { type :Sequelize.QueryTypes.DELETE }
```
Executing (default): update test_table set name = 'test' returning id
update result: { id: 0 }
update metadata: { id: 1 }
Executing (default): delete from test_table where name = 'test' returning id
delete result: { id: 0 }
delete metadata: { id: 1 }
```
which is now consistent (but doesn't return all data)

and changing that line you mentioned to: 
```
  AbstractQuery.prototype.isUpdateQuery = function() {
    return (this.options.type === QueryTypes.UPDATE)                                                                                                                                                                                           
  };
```
does solve the problem, didn't understand if that is now wanted or not

**Comment by janmeier** [comment]
@pkoretic My comment was mostly aimed at mick :)

Our intention was that all queries should default to raw and return all data, unless the user specifies otherwise. But it seems we forgot to remove the indexOf check in isUpdate. I'm just not entirely sure we  can remove it now without breaking BC

**Comment by pkoretic** [comment]
@janmeier understood :)
I'll fork if needed for us until it gets resolved
thanks

**Comment by janmeier** [comment]
You're welcome to provide a PR with the changes - then we can continue the discussion there :)

**Comment by mickhansen** [comment]
@janmeier Yeah didn't we pretty much agree on raw when raw and let people set type themselves? Also the type deduction only really matters when you have a callee i guess?
