### ISSUE TITLE
N:M Association naming

### ISSUE THREAD

**Issue by fourpixels** [sequelize/sequelize#3796]
I have different associations and I can't figure out the naming of the fields.. For example:

```js
Answer.belongsToMany(models.Question, {
    through: models.QuestionToAnswer,
    foreignKey: 'answer_id'
});
```

This generates question to answer table, with `question_id` and `answer_id` (I assume because I have both my models underscored with `id` as primary).

If I try to use what's in the docs (http://sequelize.readthedocs.org/en/latest/docs/associations/#naming-strategy) it simply does nothing:

```js
Answer.belongsToMany(models.Question, {
    through: models.QuestionToAnswer,
    foreignKey: 'answer_id', // it doesn't matter if this line is here or not
    as: { singular: 'task', plural: 'tasks' }
});
```

Again I get the very same result. The most important here is that if I try N:M self-referencing association I get an error:

```js
Resource.belongsToMany(Resource, {
    through: models.SubResource,
    foreignKey: 'main_id',
    as: { singular: 'task', plural: 'tasks' }}
});
```

Result:

```js
...\node_modules\sequelize\lib\utils.js:470
    return (tableName1.toLowerCase() < tableName2.toLowerCase()) ? (tableName1
                                                  ^
TypeError: undefined is not a function
    at Object.module.exports.combineTableNames ...\node_modules\sequelize\lib\utils.js:470:51)
    at new module.exports.BelongsToMany (...\node_modules\sequelize\lib\associations\belongs-to-many.js:36:36)
    at Mixin.belongsToMany (...\node_modules\sequelize\lib\associations\mixin.js:354:21)
```

Using
```js
    //as: 'SubResource'
```
works out, I get `addSubResource` (singular) into my model, and it puts `sub_resource_id` into db.

```js
    as: 'sub_id'
```
end up with `sub_id_id` into db, and `getSub_id` method in model.

So, uhm, is the documentation wrong, or I'm missing out something with those naming strategies - I cannot figure out what's the result on different associations..

I guess the best way is to use `as: 'SubResources', so that I can get proper (plural) method in model, and work out property (`sub_resource_id` - **singular**).

A little bit more detailed spec would be great. Something like this: http://stackoverflow.com/questions/22958683/how-to-implement-many-to-many-association-in-sequelize

**Comment by janmeier** [comment]
The undefined is not a function usually means that the model you are passing in is undefined - Have you checked that `models.SubResource` is defined?


As for the naming, i'm not completely sure what you want to do - `as` controls the naming in sequelize (`set[As]`, `get[As]` etc.), while `foreignKey` controls the key in the database - in your case the key pointing to the Answer model. To change the key for question, either use `Question.belongsToMany(Answer)` or `otherKey:` on the relation you already have

`{ singular: 'task', plural: 'tasks' }` is only needed if inflection cannot properly singularize your model - normally `as: 'tasks'` is sufficient

**Comment by fourpixels** [comment]
I just wanted to understand how things work, because I don't understand what to pass as args (docs are not good enough). The Resource model is real-life example. I want to have sub resources via join table.
So I just want each resource to have something like `subResources` / `getSubResources` property/method. But it seems that I have to make it plural, despite that the docs says it will be automatically done (`Project.belongsToMany(User..` - "This will add methods getUsers..")
And I wanted to have some nicer column names in db.

`otherKey` solved the latter - I just couldn't find this **anywhere** in the docs, even with the search. 

About the previous thing - when I do self-referenced association, this is not true: `This will add the functions add/set/get Tasks to user instances.` - it adds `getSubResource`..

**Comment by janmeier** [comment]
Otherkey is mentioned here: http://docs.sequelizejs.com/en/latest/api/associations/#belongstomanytarget-options - I know the search on RTD is not always the best, it seems to be case-sensitive...

> As we've already seen, you can alias models in associations using as. In single associations (has one and belongs to), the alias should be singular, while for many associations (has many) it should be plural. Sequelize then uses the inflection library to convert the alias to its singular form. 

For `hasOne` and `belongsTo` associations, where you only associate a single model the `as` should be singular (`as: resource` = `getResource`). For `hasMany` and `belongsToMany` the alias should be plural `as: resources` = `getResources`) - sequelize will singularize it so you get both `addResource` and `addResources`. So in your case it should be `as: 'Subresources'`

**Comment by fourpixels** [comment]
Well I've tried with `as: 'Subresources'`, and I only get `getSubresources` method (singular is missing).. As far as I can see in the code:

```js
this.accessors = {
      get: 'get' + plural,
      set: 'set' + plural,
      addMultiple: 'add' + plural,
      add: 'add' + singular,
      create: 'create' + singular,
      remove: 'remove' + singular,
      removeMultiple: 'remove' + plural,
      hasSingle: 'has' + singular,
      hasAll: 'has' + plural
    };
```

**Comment by janmeier** [comment]
Hmm, must be because inflection cannot singularize it properly. So in this case singular + plural is needed :)

**Comment by fourpixels** [comment]
Read the updated comment above. And about singular + plural:

`as: { singular: 'subResource', plural: 'subResources' }` results in:
```js
return (tableName1.toLowerCase() < tableName2.toLowerCase()) ? (tableName1

TypeError: undefined is not a function
  at Object.module.exports.combineTableNames
```
See my prev comment with full error stack.

**Comment by janmeier** [comment]
You will get `addSubresources` and `addSubresource`, but only `getSubresource` - which gets all, but allows you to add a `where` filter.

Can you show a complete example that fails for you? The example in the first post uses `task`

Please show the model definitions for resource and subresource so I can easily test it

**Comment by blindsteal** [comment]
I can confirm that using singular/plural in self-referencing belongsToMany relations seems to break things (`combineTableNames` throws `TypeError: undefined is not a function`).
The code I used was similar to OPs code:
```javascript
models.Service.belongsToMany(models.Service, {through: 'Supplements', as: 'supplement', foreignKey: 'supplementsId'})
models.Service.belongsToMany(models.Service, {through: 'Supplements', as: {singular: 'supplemented', plural: 'supplemented'}, foreignKey: 'supplementedById'})
```
