### ISSUE TITLE
hasOwnProperty fails in the formatNamedParameters method.

### ISSUE THREAD

**Issue by hariprasadkulkarni** [sequelize/sequelize#3799]
I'm trying to run a raw SQL query on my db using Sequelize.query method. The dialect is mysql.
In the formatNamedParameters function in sequelize/lib/sql-string.js file, 

```
if (values.hasOwnProperty(key))
```

fails, quoting

```
TypeError: Object object has no method 'hasOwnProperty'
```

I am using an older version of sequelize(2.0.0-rc8). In the latest version of sequelize, I see hasOwnProperty being called in the Sequelize.prototype.query function in sequelize.js. I'm not really sure why this issue is happening, but to be on the safer side, shouldn't it be replaced with the following code?

```
if (Object.prototype.hasOwnProperty.call(values,key))
```

**Comment by janmeier** [comment]
Apperently, using `var data = Object.create(null);` looses `Object.prototype` .... http://stackoverflow.com/questions/16585209/node-js-object-object-has-no-method-hasownproperty

PR welcome :)

**Comment by hariprasadkulkarni** [comment]
@janmeier Yes! This is where I found the solution too. There are 4 occurrences of this function.
In sequelize.js line numbers 661, 662 and 669.
In sql-string.js line number 159.

Are you OK with changing all of these?
Once you reply to this, I'll create a PR asap.

**Comment by janmeier** [comment]
Sure, sounds good
