### ISSUE TITLE
create 

### ISSUE THREAD

**Issue by xuyongtao** [sequelize/sequelize#3801]
can not get the id of a new ModelInstance, i get null, but by record.null

![image](https://cloud.githubusercontent.com/assets/7931332/7807108/2d6bc9a2-03bb-11e5-98c9-4bb17fd7c023.png)

**Comment by janmeier** [comment]
Please show actual code, instead of images

Please show your model definitions. Have you marked the id as `primaryKey: true` and `autoIncrement: true`?

**Comment by xuyongtao** [comment]
thank you your remind, i make a mistake
