### ISSUE TITLE
transactions return extremely slow

### ISSUE THREAD

**Issue by faceair** [sequelize/sequelize#3808]
Maybe this problem is similar to https://github.com/sequelize/sequelize/issues/2995.

This is my code.

    setProvider: (provider) ->
      sequelize.transaction (t) =>
        @getProviders
          provider: provider
        .then ([available_provider]) =>
          unless available_provider
            throw new Error 'provider_unavailable'
          {currency, price} = available_provider
          Order.update
            provider: provider
            currency: currency
            price: price
          ,
            transaction: t
            where:
              id: @id
              provider: null
          .then ([affected_count]) ->
            unless affected_count > 0
              throw new Error 'set_provider_error'
        .then =>
          @setStatus 'unpay',
            transaction: t
            where:
              id: @id
              status: 'created'
        .then =>
          t.commit()
          console.time '1'               #time log
          return @
        .catch (err) ->
          t.rollback()
          throw err
      .then =>
        console.timeEnd '1'              #time log
        @

test result:

![image](https://cloud.githubusercontent.com/assets/3659110/7831557/5631dc94-048a-11e5-992b-3517028b53f0.png)

**Comment by mickhansen** [comment]
How fast is it without the transaction?

**Comment by faceair** [comment]
I noticed something strange.

In the log `setStatus` just take 22ms, when i remove the `setStatus`, this transaction would take 50ms.

And i removed the transaction, this part take more then 1s, and `setStatus` take about 20ms. When i remove the `setStatus`,  this part take about 50ms.

I seem to find the problem ...

**Comment by mickhansen** [comment]
Alright, if you have any specifics we can try to work with, please post them.

**Comment by faceair** [comment]
@mickhansen Thanks.

The problem is in `setStatus` i add a task use `process.nextTick`, it pend a lot of time, and will call before `then`.

**Comment by mickhansen** [comment]
@faceair Ah alright :)
