### ISSUE TITLE
[Question] Eagler Loaded query, list all children

### ISSUE THREAD

**Issue by sebay00** [sequelize/sequelize#3809]
Hi fellas,

I'm trying to query room models that have specific metadata.. 
I succeed to do it, however, Sequelize only returns matched metadata (associated) when I need all the associated metadata linked to my room instance.

Is there a way to do this ?

**Comment by janmeier** [comment]
Put `required: false` on the include - turns it from an inner to an outer join

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by sebay00** [comment]
I thought the required: false was only for listing all the parents ? 
Like said the doc : 

```
This will produce an outer join. However, a where clause on a related model will create an inner join and return only the instances that have matching sub-models. To return all parent instances, you should add required: false.
```

I'll ask on google.

**Comment by janmeier** [comment]
Ah, you are right, required: false is the other way around.

Perhaps add the include twice - once to add the where query, and once to fetch all instances?

**Comment by sebay00** [comment]
What did you mean by "Add the include twice" ? 

Do you have an example ?

**Comment by janmeier** [comment]
What I meant was a query like 
```sql
SELECT "room"."id" ....
FROM "rooms" AS "room"
INNER JOIN "metadata" AS "metadata" ON "room"."id" = "metadata"."roomId"
AND "metadata". { WHERE CLAUSE }
LEFT OUTER JOIN "metadata" AS "metadata" ON "room"."id" = "metadata"."roomId";
```

You can add the include to the array twice, but this fails because the table alias `metadata` is no longer unique. 

Right now your best bet would indeed be to execute two queries

**Comment by sebay00** [comment]
Ah ok. Thx for the hand. I'll do 2 queries so. :(

**Comment by janmeier** [comment]
Perhaps we could make it possible to add a custom alias to an include? @mickhansen , I believe this has been mentioned before?

**Comment by mickhansen** [comment]
@janmeier It has been discussed, haven't found a good syntac for it.
