### ISSUE TITLE
Set Custom DataTypes

### ISSUE THREAD

**Issue by olivercox** [sequelize/sequelize#381]
Hi,

I wonder if anyone knows of a way that the Sequelize DataTypes can be overridden with a local DataTypes file. 

I've tried importing a datatype file calling:

``` javascript
var CustomDataTypes = require('./custom-data-types');
Sequelize.Utils._.map(CustomDataTypes , function(sql, accessor) { Sequelize[accessor] = sql})
```

If I call Sequelize.CustomDataType now the new datatype is there but it doesn't work within the Sequelize module. I am assuming that this is scoping issue that am not understanding.

Any help would be great.

Many Thanks

Oliver

**Comment by thebigredgeek** [comment]
+1.  @mickhansen I'd really like to be able to create custom data types in the same way that I can create custom scalars with GraphQL.  Right now I am resigned to reusing validator functions both in scalar definitions and in sequelize validators, but it would be nice if sequelize could provide pluggable custom types that inherently handle validation.

**Comment by xdamman** [comment]
Same.

Also, I have multiple tables with a "amount" and "currency" column. Would be good to have those types defined in one place instead of copy pasting every time
```
    currency: {
      type: DataTypes.STRING(3),
      defaultValue: 'USD',
      validate: {
        len: [3, 3]
      },
      allowNull: false,
      set(val) {
        if (val && val.toUpperCase) {
          this.setDataValue('currency', val.toUpperCase());
        }
      }
    }
```

**Comment by vmadman** [comment]
@xdamman Not to be a bother, but I am curious why you couldn't just centralize that configuration somewhere, outside of Sequelize?

e.g.

**my-custom-types.js**
```javascript
module.exports = {
    currency: {
      type: DataTypes.STRING(3),
      defaultValue: 'USD',
      validate: {
        len: [3, 3]
      },
      allowNull: false,
      set(val) {
        if (val && val.toUpperCase) {
          this.setDataValue('currency', val.toUpperCase());
        }
      }
    }
}
```

**some-model.js**
```javascript
let customTypes = require("./my-custom-types");
sequelize.define(
	"someModel", {
		currency: customTypes.currency
	}
);
```

**Comment by xdamman** [comment]
@vmadman that's exactly what I'm doing :-) https://github.com/opencollective/opencollective-api/blob/collective/server/models/DataTypes.js

I was just wondering if there was a more elegant way to extend the `DataTypes` when setting up Sequelize. Not a big issue in my case. This one is more blocking at the moment fwiw: https://github.com/sequelize/sequelize/issues/8133

**Comment by marcusbalbi** [comment]
Hello Everyone, I don't know if my solution could get any error later, but I create a set of datatype customized and set on my sequelize connection objetct like so:

connection module :
```javascript
const dataTypes = require('./datatypes')

//...

sequelize.Types = dataTypes

return sequelize
```
datatypes module:
```javascript
const uppercaseString = require('./UppercaseString')

module.exports = {
  UPPERCASE_STRING: uppercaseString
}

```
UppercaseString module:

```javascript
module.exports = () => {
  return {
    stringify: function (val, options) {
      if (val && val.toUpperCase) {
        return val.toUpperCase()
      }
      return val
    }
  }
}

```

thank you!
