### ISSUE TITLE
Inserting data into an array field in Sequelize+Postgres

### ISSUE THREAD

**Issue by manjugit** [sequelize/sequelize#3819]
Hi,

I guess my question is not an issue/bug, and sorry if this is not a place to get clarifications to questions/problems as in a mailing list. 

I have a simple task of inserting data into an array field: Model.create{id_list: [1, 2, 3]}. For some reason id_list is always NULL. 

I also tried ARRAY[1, 2, 3], '{1,2,3}, etc., but Sequelize says 'ARRAY' is undefined, '{' is unexpected, etc. 

The field is defined as follows in its definition:

id_list: {type: DataTypes.ARRAY(DataTypes.INTEGER), defaultValue: null}

Please note that I am able to insert/update all the other non-array fields of the Model without any problem.

Thanks!
Manju

**Comment by mickhansen** [comment]
It should definitely just work like that.

**Comment by ns3777k** [comment]
Strange. works for me. for 2nd (2.1.2) & 3rd (latest) versions.

simple script:

```js
'use strict';

var SEQUELIZE = require('sequelize'),
    sequelize = new SEQUELIZE('...', '...', '...', {
        host: '...',
        dialect: 'postgres'
    });

var testModel = sequelize.define('testModel', {
    title     : SEQUELIZE.TEXT,
    id_list  : { type : SEQUELIZE.ARRAY(SEQUELIZE.INTEGER), defaultValue: null}
}, {
    tableName : 'test',
    createdAt : false,
    updatedAt : false,
    deletedAt : false
});

testModel.create({title : 'testing 2', id_list: [1, 2]});
```

fields in scheme:

```sql
title TEXT,
id_list INTEGER[]
```

packages:

```json
"pg": "^4.4.0",
"pg-hstore": "^2.3.2"
```

query generated:


```
/usr/local/bin/node index.js
Executing (default): INSERT INTO "test" ("id","title","id_list") VALUES (DEFAULT,'testing 2',ARRAY[1,2]::INTEGER[]) RETURNING *;
```

**Comment by janmeier** [comment]
No response from OP so I'm going to close this. Please response with a test case if you still have issues @manjugit

**Comment by idan** [comment]
/cc @janmeier I'm seeing this behavior as well. Here's a minimum reproducible case:

```
var Sequelize = require('sequelize')
var sequelize = new Sequelize(process.env.DATABASE_URL, {dialectOptions: {ssl: true}})

var Dashboard = sequelize.define('dashboard', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true
  },
  owner: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      isEmail: true
    }
  },
  dataclips: Sequelize.ARRAY(Sequelize.TEXT)
}, {timestamps: false})

Dashboard.sync({force: true}).then(function () {
  Dashboard.create({owner: 'foo@bar.com', clips: ['baz', 'bling'] }).then(function () {
    console.log('created')
  })
})
```

using:

```
sequelize@3.3.2
pg@4.4.0
pg-hstore@2.3.2
```

On iojs 2.3.0;

**Comment by janmeier** [comment]
@idan The code you posted gives me `INSERT INTO "dashboards" ("id","owner","dataclips") VALUES ('e3da5414-b17c-4525-9230-f033b91d5d48','foo@bar.com',ARRAY['baz','bling']::TEXT[]) RETURNING *;`

Note that I changed `clips` to  `dataclips` in the create

**Comment by idan** [comment]
@janmeier I'm an idiot, apologies for the typobug.

**Comment by kennetpostigo** [comment]
How to push/pop items into and array from sequelize?

**Comment by PavelPolyakov** [comment]
@kennetpostigo 
here is the solution of the array push:
```js
await YourModel.update({ history: Sequelize.literal(`'${JSON.stringify({ hello: new Date(), random: Math.floor(Math.random() * Math.floor(2)) })}'::jsonb || history`) }, { where: { id: yourModelInstance.id } });
```

(imagine you have a column `history` which is `jsonb`)
