### ISSUE TITLE
error: invalid value for parameter "TimeZone": "UTC"

### ISSUE THREAD

**Issue by micke** [sequelize/sequelize#382]
Hello!

There seems to be a problem with Sequelize's postgres adapter.
When trying to connect to postgres we receive this error:

```
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
error: invalid value for parameter "TimeZone": "UTC"
    at p.parseE (/Users/.../node_modules/pg/lib/connection.js:473:11)
    at p.parseMessage (/Users/.../node_modules/pg/lib/connection.js:348:17)
    at Socket.p.attachListeners (/Users/.../node_modules/pg/lib/connection.js:84:22)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:396:14)
```

But if we change line 63 in dialect/postgres/connector-manager.js from:
`client.query("SET TIME ZONE 'UTC'")` to: `
client.query("SET TIME ZONE 'UTC+0'")`

it works!

**Comment by TangMonk** [comment]
+1 Postgres restart.

**Comment by yehaha9876** [comment]
mkdir /usr/local/xxx/15.5/share/timezone -p
ln -s /usr/share/zoneinfo/Etc /usr/local/xxx/15.5/share/timezone

postgres=# SELECT * FROM pg_timezone_names;
   name    | abbrev | utc_offset | is_dst 
-----------+--------+------------+--------
 GMT+1     | -01    | -01:00:00  | f
 GMT+10    | -10    | -10:00:00  | f
 GMT+11    | -11    | -11:00:00  | f
 GMT+12    | -12    | -12:00:00  | f
