### ISSUE TITLE
Nested creation: data partly saved when validation fails.

### ISSUE THREAD

**Issue by sijmenvos** [sequelize/sequelize#3821]
For instance when a new user has multiple emails in a nested model and one of the emails fails to validate the promise immediately fails. This results in partly saved data; the user gets saved and the emails are saved up until the failed address.

The child models are only saved up until the failed model. I have tried building the instance and validating before saving, but only the 'root'-model gets validated.

Maybe the entire data object should get validated before the models are stored in the database?

**Comment by mickhansen** [comment]
Nested creation is still very early. I would suggest you always use transactions when using nested creation.
But yes validating everything from the start would probably be the sanest.

**Comment by sijmenvos** [comment]
Thanks for the suggestion, that worked out for me.
