### ISSUE TITLE
Return number of deleted rows on model.destroy()?

### ISSUE THREAD

**Issue by FredKSchott** [sequelize/sequelize#3822]
Currently model.destroy() doesn't return/resolve with anything. Could it return the number of deleted rows, similar to how update returns the number of updated rows? Happy to work on the PR if this is something other people want.

```js
// Update: Today
return Item.update(data, {where: {/* ... */}}).spread(function(updateCount) {
// Destroy: Today
return Item.destroy({where: {/* ... */}}).then(function() {
// Destroy: Proposal
return Item.destroy({where: {/* ... */}}).spread(function(deleteCount) {
```

**Comment by janmeier** [comment]
The API docs doesn't mention it, but this is already the case today

**Comment by FredKSchott** [comment]
:+1: :+1: :+1:  Awesome! Thanks for the quick response!
