### ISSUE TITLE
Querying Postgres jsonb column contaning non-text type of fields cause "operator does not exist" exception

### ISSUE THREAD

**Issue by xwk** [sequelize/sequelize#3824]
Suppose model Store has a column called 'jsonb' which has type jsonb. Query like

```
Store.find({
      where: {
        jsonb: {
          enabled: true
        }
      }
```

will cause SequelizeDatabaseError: operator does not exist: text = boolean exception.  

The reason for that is Sequelize will translate the query into following SQL

SELECT "id", "jsonb", "createdAt", "updatedAt" FROM "stores" AS "store" WHERE ("store"."jsonb"**#>>**'{enabled}') = true LIMIT 1.

Notice #>> operator is used, which converts the jsonb type to text. The correct SQL should be 

SELECT "id", "jsonb", "createdAt", "updatedAt" FROM "stores" AS "store" WHERE ("store"."jsonb"**#>**'{enabled}') = **'true'::jsonb** LIMIT 1;

Full sample code as below

```
var Sequelize, Store, configs, sequelize;

Sequelize = require("sequelize");

configs = require("../configs");

sequelize = new Sequelize(configs.DB_NAME, configs.DB_USERNAME, configs.DB_PASSWORD, {
  host: configs.DB_HOSTNAME,
  dialect: 'postgres'
});

Store = sequelize.define('store', {
  jsonb: Sequelize.JSONB
});

Store.sync({
  force: true
}).then(function() {
  return Store.create({
    jsonb: {
      name: 'test store',
      enabled: true,
      grade: 3
    }
  }).then(function() {
    return Store.find({
      where: {
        jsonb: {
          enabled: true
        }
      }
    });
  })
```

**Comment by mickhansen** [comment]
`("store"."jsonb"#>'{enabled}')::boolean = true` might work aswell? That's the technique we use for numbers
