### ISSUE TITLE
bulkUpsert support

### ISSUE THREAD

**Issue by devlato** [sequelize/sequelize#3826]
Hi, 
it would be great if there will be a support of something like bulkUpsert model method, i.e.: 

``` javascript
SomeModel.bulkUpsert([{
  id: 1, 
  key: 'response', 
  value: 'lol'
}, {
  id: 2,
  key: 'quote', 
  value: 'no way'
}], ... );
```

So this method could generate and execute something like this:  

``` sql
INSERT INTO `some_table` (`id`, `key`, `value`) 
VALUES (1, 'response', 'lol'), (2, 'quote', 'no way') 
ON DUPLICATE KEY UPDATE `key` = VALUES(`key`), `value` = VALUES(`value`); 
```

**Comment by mickhansen** [comment]
We've stayed away from implementing this it's currently impossible to do in a cross-dialect way.
