### ISSUE TITLE
SET standard_conforming_strings=on; invalid on Postgres < 8.1

### ISSUE THREAD

**Issue by pmhpereira** [sequelize/sequelize#3829]
I need to query (simple findAll) an old database that is running Postgres 8.0 (can't be upgraded).

Sequelize v3 fails to connect to this database because of [this line](https://github.com/sequelize/sequelize/blob/95a5c0d86dbdd32133a3dcb64659e98f12691b02/lib/dialects/postgres/connection-manager.js#L98).

I was already able to upgrade Sequelize to v3 on all my projects, except the one accessing this database.

Would you accept a PR that solves this issue, like this?
```javascript
...

var query = '';

if (self.sequelize.config.useStandardConformingStrings) {
  query += 'SET standard_conforming_strings=on;';
}

...
```

In this case `useStandardConformingStrings` would be `true` by default.

I'm aware of the fact that other functionalities of Sequelize will still not work with Postgres 8.0 (like `.sync({ force: true }`, but I will not need those.

**Comment by janmeier** [comment]
Sure

**Comment by janmeier** [comment]
Fixed here https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L101
