### ISSUE TITLE
belongsToMany creates unexpected fields

### ISSUE THREAD

**Issue by DuffmanBE** [sequelize/sequelize#3831]
I just upgraded to sequelize 3.1.1 and I am facing a problem I didn't face before. Because I upgraded, I had to change my hasMany-invocations to belongsToMany.

Let's say I have two models: User and JobTitles
User looks like this:

    module.exports = function(sequelize,DataTypes) {
	return User = sequelize.define('User', {
		userId: {
			type: DataTypes.INTEGER,
			primaryKey: true,
			allowNull: false,
			autoIncrement: true,
			unique: true
		},
		firstName: {
			type: DataTypes.STRING,
			allowNull: false
		},
		lastName: {
			type: DataTypes.STRING,
			allowNull: false
		},
		hashedPassword: {
			type: DataTypes.STRING,
			allowNull: false
		},
		email: {
			type: DataTypes.STRING,
			allowNull: false,
			unique: true
		},
		gender: { //Kan misschien wat eleganter
			type: DataTypes.STRING
		},
		jobTitleId: {
			type: DataTypes.INTEGER,
			references: 	'jobtitles',
			referencesKey: 	'jobTitleId'
		},
		hasVisited: {
			type: DataTypes.BOOLEAN,
			defaultValue: false
		},		
		companyId: {
			type: 			DataTypes.INTEGER,
			references: 	'companies',
			referencesKey: 	'companyId',
			onDelete: 		'cascade'
		}
	},
	{
		tableName: 'users'
	})};

JobTitle looks like this:

    module.exports = function(sequelize, DataTypes){
	return JobTitle = sequelize.define('JobTitle', {
		jobTitleId: {
			type: DataTypes.INTEGER,
			primaryKey: true,
			allowNull: false,
			autoIncrement: true,
			unique: true
		},
		name: {
			type: DataTypes.STRING,
			allowNull: false
		},
		companyId: {
			type: 			DataTypes.INTEGER,
			references: 	'companies',
			referencesKey: 	'companyId',
		}
	},
	{
		tableName: 'jobtitles'
	})};

Let's disregard the other tables I'm referring to in the model for now. 

If I just have these models and I create them with 
`models.sequelize.sync().then(function(){ // do stuff });`
everything works fine and the tables are created with the fields I expect.

If I declare following association
    
    db["JobTitle"].belongsToMany(db["User"], {through: db["User"], foreignKey: 'jobTitleId'});
    db["User"].belongsTo(db["JobTitle"], {foreignKey: 'jobTitleId'});

to indicate that a jobTitle can belong to many users but that a user can only have one jobtitle,  unexpected fields are created when I generate the tables by invoking
`models.sequelize.sync().then(function(){ // do stuff });`

The field UserUserId is created in the table users (which corresponds with the model db["User"]. I found out (for other tables as well) that every time I use belongsToMany, a similar field is created in the through-table.

**Comment by janmeier** [comment]
For anyone wondering - belongs to many will always create a join table (n:m). So in this case it should be has many
