### ISSUE TITLE
Saving model after setting a boolean property causes only updatedAt to be saved

### ISSUE THREAD

**Issue by KTachyon** [sequelize/sequelize#3849]
I'm trying to update a boolean property for a model and when I call save(), the only column being updated is the updatedAt column. I can get it to save by explicitly stating that I want that field to be saved:

Code:
```
poi.set('inside', !!value);
return poi.save({ transaction : context.getTransaction() });
```

Resulting query:
```
UPDATE "Pois" SET "updatedAt"='2015-06-01 19:23:32.946 +00:00' WHERE "id" = '90498c3a-e586-45ca-ac0d-752d648d629d'
```

Query with field:
```
poi.set('inside', !!value);
return poi.save({ fields : ['inside'], transaction : context.getTransaction() });
```

Resulting query:
```
UPDATE "Pois" SET "inside"=false,"updatedAt"='2015-06-01 19:25:23.663 +00:00' WHERE "id" = '90498c3a-e586-45ca-ac0d-752d648d629d'
```

EDIT: It happens even if the value of the property is being set to true. The initial value of the property is NULL.

**Comment by janmeier** [comment]
Cannot reproduce this. Please open a PR with a failing test case
