### ISSUE TITLE
Instance#reload not working correctly on { through: Model }

### ISSUE THREAD

**Issue by DanMMX** [sequelize/sequelize#3855]
When having a join model as through table using `belongsToMany` the instance doesn't get reloaded correctly.

Definitions and associations:

```
var GiftTableProducts = sequelize.define('GiftTableProducts', {
    quantity: DataTypes.FLOAT
});

var Product = sequelize.define('Product', {
    // ... attrs ...
});

var GiftTable = sequelize.define('GiftTable', {
    // ... attrs ...
});

GiftTable.belongsToMany(Product, { through: GiftTableProducts});
Product.belongsToMany(GiftTable, { through: GiftTableProducts });
GiftTableProducts.belongsTo(GiftTable, { onDelete: 'CASCADE' });
GiftTableProducts.belongsTo(Product, { onDelete: 'CASCADE' });

```

The `GiftTableProducts` table definition is the following:

![captura de pantalla 2015-06-02 a las 17 15 27](https://cloud.githubusercontent.com/assets/1919322/7948607/04574592-094b-11e5-9091-97cf6f3240cc.png)

When updating some instance, let's say 

```

GiftTableProducts.find({where: { GiftTableId: '2', ProductId: 1}})
.then(function (gift) {
    gift.increment(['quantity'], { by: '10' })
    .then(obj.reload({ GiftTableId: 2, ProductId: 1 }))
    .then(function (obj) { res.send(obj) });
});
```

Produces the following executions:

```
SELECT `quantity`, `createdAt`, `updatedAt`, `ProductId`, `GiftTableId` FROM `GiftTableProducts` AS `GiftTableProducts` WHERE `GiftTableProducts`.`GiftTableId` = '2' AND `GiftTableProducts`.`ProductId` = 1;

UPDATE `GiftTableProducts` SET `quantity`=`quantity` + '10',`updatedAt`='2015-06-02 19:52:11' WHERE `ProductId` = 1 AND `GiftTableId` = 2

SELECT `quantity`, `createdAt`, `updatedAt`, `ProductId`, `GiftTableId` FROM `GiftTableProducts` AS `GiftTableProducts` WHERE `GiftTableProducts`.`ProductId`=1 LIMIT 1;

```

The `WHERE` clause on the reload `SELECT` doesn't include the corresponding `ProductId` which is a primary key even when passing by the `{ GiftTableId: 2, ProductId: 1 }` object to the `.reload` call returning the first gift it founds having the same `GiftTableId` and maybe not being the same one updated.

**Comment by DanMMX** [comment]
I managed to fix that inconsistency mentioning the foreign keys into the model definition :

```
GiftTableProducts = sequelize.define('GiftTableProducts', {
	quantity: DataTypes.FLOAT,
	GiftTableId: {
		type: DataTypes.INTEGER,
		references: {
			model: sequelize.models.GiftTable,
			key: 'id'
		}
	},
	ProductId: {
		type: DataTypes.INTEGER,
		references: {
			model: sequelize.models.Product,
			key: 'id'
		}
	}
});

```

Will leave this opened in case it's a bug

**Comment by DanMMX** [comment]
btw, ├─┬ sequelize@2.1.3
│ ├── dottie@0.3.1
│ ├── generic-pool@2.2.0
│ ├── inflection@1.7.1
│ ├── lodash@3.8.0
│ ├── moment@2.10.3
│ ├── node-uuid@1.4.3
│ ├── toposort-class@0.3.1
│ └── validator@3.39.0

**Comment by mickhansen** [comment]
That does appear to be a bug.

**Comment by ikhos** [comment]
@DanMMX I'm setting the primary keys and through references the way you did but I'm still getting an error, did you set any associations on your GiftTableProducts table as well?

**Comment by DanMMX** [comment]
These are my associations for the already mentioned models:

```
GiftTable.belongsToMany(Product, { through: GiftTableProducts});
Product.belongsToMany(GiftTable, { through: GiftTableProducts });

GiftTableProducts.belongsTo(GiftTable, { onDelete: 'CASCADE' });
GiftTableProducts.belongsTo(Product, { onDelete: 'CASCADE' });
```

so yes, it's a bit different from the starting approach, this should work with the `GiftTableProducts` model definition

**Comment by edrpls** [comment]
Thanks, it's really weird, I changed all of my models and I still get the error. I worked around it by splicing the array after removing one of its relations.

**Comment by sushantdhiman** [comment]
Fixed in master, SSCCE in https://github.com/sequelize/sequelize/issues/3973
