### ISSUE TITLE
Join no primary key column

### ISSUE THREAD

**Issue by Orvacko** [sequelize/sequelize#3857]
Hi,

is there any soultion how to join (set foreign and local key) for ex: TABLE company.company_id on TABLE company_tags.company_company_id, but, both keys are not primary keys? Thank you.

TABLE company | TABLE company_tags
------------ | -------------
id - primary (uniq) | id - primary (uniq)
company_id - no primary (no uniq) | company_company_id - no primary (no uniq)
 | tag_id

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/3854 might be what you want, else open a feature request for your specific use case and associations.
