### ISSUE TITLE
needs a NotIn[relationship]() function

### ISSUE THREAD

**Issue by slawo** [sequelize/sequelize#3858]
I asked a question here: http://stackoverflow.com/q/30598026/171711

> how to retrieve all items not in a relationship?

But apparently there seems to be no easy way to accomplish this in one go using only sequelize functions.

There are 2 ways currently: 
- get the table name used in the relationship and write a custom SQL query to retrieve all items not in the relationship.
- retrieve all the items in the relation ship and do a `not:[<list of ids>]` query which is far from ideal.

Would it be possible to add a `notIn[other]()` function to simplify this type of queries.

**Comment by mickhansen** [comment]
What type of relationship are you looking at here?
If 1:M for instance you can just do a `findAll({where: {foreignKey: null}})` on the 1: side.

**Comment by mickhansen** [comment]
I assume you'd want this on the model? We don't currently add methods to models at all when doing an association, everything gets set on the instance prototype.
