### ISSUE TITLE
Breaking change introduced in 2.1.1: getAssociationByAlias() renamed to getAssociation()

### ISSUE THREAD

**Issue by bleupen** [sequelize/sequelize#3863]
We used this everywhere. Should have been a major release, no? Or are mixins not meant to be public facing?

**Comment by pmhpereira** [comment]
If you read the [API documentation for Associations](http://sequelize.readthedocs.org/en/latest/api/associations/), you will not find the documentation for the `getAssociation()` method.

`getAssociation()` is used [internally](https://github.com/sequelize/sequelize/search?utf8=%E2%9C%93&q=getAssociation) and `getAssociationByAlias()` (also [not documented on the old docs](http://sequelize.readthedocs.org/en/2.0/api/associations/)) was removed becaused it stopped being used.

**Comment by mickhansen** [comment]
`getAssociation` was definitely not meant as public API, i'm sorry this affected you - But there should be no docs and we don't have any tests for it.
