### ISSUE TITLE
Difference Between then(...).catch(...) and spread(...).fail(...)

### ISSUE THREAD

**Issue by aireol** [sequelize/sequelize#3865]
Hi!

I would like to ask what are the difference between `then(...).catch(...)` and `spread(...).fail(...)` methods. Can you give some insights on how and when should I use them?

Also, I am particularly interested on how to handle errors when using the method `.create(...)`. I found posts both in your [documentation](http://docs.sequelizejs.com/en/latest/docs/instances/) and in [stackoverflow](http://stackoverflow.com/questions/19003148/sequelize-get-findorcreate-error) that refers to the `.build()` method and `findOrCreate()` but not for `create()` method. 

Comments are highly appreciated.

Note:
I am using __sequelize v3.1.0__ and __tedious v1.11.0__.

**Comment by janmeier** [comment]
This is a promise question, not a sequelize once. Have a look at https://github.com/petkaantonov/bluebird/blob/master/API.md

Hint: then is for functions returning a single arg, spread is for functions returning multiple, eg findorcreate

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by jnields** [comment]
This is confusing as `Promise.prototype.spread` is not standard, but is just part of the Bluebird promise library.

The only standard methods on the `Promise` prototype are `catch` and `then`. It would be helpful if the docs made this more obvious, and I don't think they should recommend using spread for promises that resolve to an array.

As far as I can tell, the standard way to deal with this is :

ES5
```
Model.findOrCreate(
  { where: { username: 'foo' } }
).then(
  function (result) {
    var instance = result[0], wasCreated = result[1];
    // ...
  }
);
```

ES6 (OK on Node v6):
```
Model.findOrCreate(
  { where: { username: 'foo' } }
).then(
  (result) => {
    const [instance, wasCreated] = result;
    // ...
  }
);
```
or with ES6 & async / await (requires transpiling with Node v6)
```
const [instance, wasCreated] = await Model.findOrCreate({ where: { username: 'foo' } });
```

**Comment by nickangtc** [comment]
Excellent point @jnields. I just wasted 30 minutes wondering why I couldn't get `modelInstance.id` to work until I realised there was a non-standard need to use `.spread()` to destructure the parameters to get to the actual data. 🤦‍♂️

**Comment by jarodsmk** [comment]
I spent a day debugging the possibility of my models being created incorrectly, running it in a sandbox and eventually coming to the conclusion that I hadn't called the .spread() operator after my findOrCreate() call and was calling my instance functions on the returned array instead. 

Bump for updating the documentation on this to make it more prominent.
