### ISSUE TITLE
how to return raw data with hooks(ex:afterUpdate)

### ISSUE THREAD

**Issue by brucewar** [sequelize/sequelize#3867]
I want to return raw data after updating the instance, and i set individualHooks to true.

```js
Shop.update({}, {
  individualHooks: true
});
```
```js
hooks: {
  afterUpdate: function(shop, options, fn){
    shop = shop.dataValues;
    fn(null, shop);
  }
}
```

**Comment by janmeier** [comment]
Sequelize methods will always return instances - you cannot change that in hooks. The values you return will just be put back into an instance :)

If you want to return raw data you'll have to do some processing after the update.

**Comment by rusmichal** [comment]
bump
