### ISSUE TITLE
Using operators on `id` attribute errs out on legacy tables

### ISSUE THREAD

**Issue by redhotvengeance** [sequelize/sequelize#3870]
I've run into an interesting issue while migrating a codebase to Sequelize. When I try to use a comparison operator on the `id` of a `findAll` query, it errs out with:

```js
Unhandled rejection Error: Supplied id is invalid
```

I've tried to isolate the issue by spinning up a separate test project using Sequelize migrations, and I can't replicate it. The simplified test project executes the query without an error.

Here's the query I'm making in both projects:

```js
Post.findAll({logging: console.log, where:{id:{$lt: 2}}}).then(function(posts) {
  console.log(posts);
});
```

The DB is PostgreSQL. Here is the model of the legacy project:

```js
module.exports = function(sequelize, DataTypes) {
  var Post = sequelize.define('post', {
    text: {
      type: DataTypes.TEXT
    },
    date: {
      type: DataTypes.DATE
    },
    deleted: {
      type: DataTypes.DATE
    },
    timeline_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    created_by_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    owner_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    }
  }, {
    timestamps: true,
    underscored: true,
    classMethods: {
      associate: function(models) {
        Post.belongsTo(Timeline);
        Post.belongsTo(User, {as: 'owner'});
        Post.belongsTo(User, {as: 'creator', foreignKey: 'created_by_id'});
        Post.hasMany(Comment)
      }
    },
    defaultScope: {
      where: {
        deleted: null
      },
      order: [
        ['id', 'DESC']
      ]
    },
    scopes: {
      deleted: {
        where: {
          $or: [
            {
              deleted: null
            },
            {
              deleted: {
                $ne: null
              }
            }
          ]
        },
        order: [
          ['id', 'DESC']
        ]
      }
    }
  });

  return Post;
};
```

And here is the model of the simplified project:

```js
module.exports = function(sequelize, DataTypes) {
  var Post = sequelize.define('Post', {
    body: {
      type: DataTypes.TEXT
    }
  }, {
    timestamps: true,
    defaultScope: {
      order: [
        ['id', 'DESC']
      ]
    },
  });

  return Post;
};
```

When examining both DBs with `psql`, the columns are the same in both (with the exception of the capitalization of "posts"):

```sql
 id            | integer                  | not null default nextval('posts_id_seq'::regclass)
```

...as are the indices:

```sql
Indexes:
    "posts_pkey" PRIMARY KEY, btree (id)
```

Can anyone point me in the right direction on how to resolve the invalid id error I'm getting on the legacy table?

**Comment by mickhansen** [comment]
Try running the generated SQL manually, might give you a clue.
Can you show the stack for the error?

**Comment by redhotvengeance** [comment]
@mickhansen Ugh, mark this one invalid. The error was being thrown by an id validator before hook in the project.

GitHub issues needs the equivalent of a "drunk text blocker", except for sleep deprived devs. That way bleary-eyed people like myself don't waste everyone's time. My apologies!
