### ISSUE TITLE
Transactions via CLS do not work in hooks

### ISSUE THREAD

**Issue by ndreas** [sequelize/sequelize#3875]
I discovered that transactions via CLS do not work in hooks, due to `Promise.each` not being shimmed. I created a pull request with a fix in #3874.

**Comment by mdarveau** [comment]
Hi,

That's funny because I create almost the same PR yesterday:
https://github.com/sequelize/sequelize/pull/3868

However, mine covers each, map, reduce and filter.

Manuel

**Comment by ndreas** [comment]
Fixed using #3868 in version 3.2.0. Thanks!
