### ISSUE TITLE
Setting a JSON field to null saves incorrectly as string "null"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#3877]
I am using Node 0.12, PostgreSQL 9.3.7, and Sequelize 3.1.1

I have a field of type JSON and when I set the value to NULL:
```javascript
user.json_field = null
user.save()
```
the SQL generate is wrong, it uses "null" in quotes, i.e. a string with the word "null" instead of a real null:
```sql
 UPDATE "users" SET "json_field"='null', ...
```

How do I set it to a real null? This is a bug, right? Nobody would want NULL to be saved as a string of the word "null".

**Comment by GeoffreyPlitt** [comment]
Same thing happens if I use set() or setDataValue().

**Comment by mickhansen** [comment]
Definitely a bug.

**Comment by GeoffreyPlitt** [comment]
I could try fixing it if someone can point me where to look. I tried some naive fixes in lib/sql-string.js but didn't have any success. I think part of the problem is that JSON fields are represented as strings.

**Comment by curiousdannii** [comment]
null is a valid JSON type, so it makes some sense that it would get stored that way.

**Comment by GeoffreyPlitt** [comment]
Why not store null as null? It stores it as the string "null" right now.

**Comment by mickhansen** [comment]
@curiousdannii That is true, but then you could use 'null', i really think the saner value here is an actual database NULL value.

**Comment by GeoffreyPlitt** [comment]
I've just verified this bug is happening even with JSONB, and JSONB isn't even using string storage.

Does anyone know which developers created the JSON/JSONB features so I can at least ask them what files these bugs are located in?

**Comment by mickhansen** [comment]
No single developer created the feature, but you want to look in `sql-string/escape` likely.
JSONB still uses the same serialization though, and 'null' is valid JSONB aswell (although saved in binary)

**Comment by GeoffreyPlitt** [comment]
Hold on, you guys realize that a null value (not string "null") is valid JSON, right? JSON/JSONB not being able to represent a JSON document of just NULL is broken. Am I the only one who sees that?

**Comment by GeoffreyPlitt** [comment]
Another aspect of this: The default value of a JSON/JSONB field starts off as NULL. I'm just trying to figure out how to revert the value to its default.

**Comment by mickhansen** [comment]
> Hold on, you guys realize that a null value (not string "null") is valid JSON, right?
What are you on about? Seeing as we discussed it previously in this thread, we are aware, and i already told you i agree that it should be `NULL`.

I merely told you the reason it for being in this current state is the fact that `JSON.stringify(null)  === "null"` which is a valid JSON structure in both JSON & JSONB.

**Comment by GeoffreyPlitt** [comment]
Cool, thanks. I may have found the culprit, sending a PR later today.

**Comment by alexcarruthers** [comment]
This also proves to be problematic for constraints. It will accept the null value no problem as valid input JSON but any check constraints checking if that value is null, fail.

**Comment by alexcarruthers** [comment]
@mickhansen @janmeier are there plans on putting this in a release within the next couple days?

**Comment by FernandoLuizNemeChibli** [comment]
I don't know if the issue is back, but this happened with me too. I had to improvise with "if (json.value=="null") json.value=null;" and this annoys me XD

**Comment by tutok** [comment]
workaround
```
up: async (queryInterface, Sequelize) => 
  queryInterface.sequelize.transaction(async transaction => {
     await queryInterface.addColumn(
        'Test',
        'options',
        {
          type: Sequelize.STRING,
          defaultValue: '{}',
          allowNull: false
        },
        { transaction }
      );
      await queryInterface.changeColumn('Test', 'options', Sequelize.JSON);
 }),
```

**Comment by Yihao-G** [comment]
So with the change merged now, how can we insert JSON `null` (not a SQL NULL) with Sequelize now?
