### ISSUE TITLE
"JSONB does not exist"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#3878]
The docs talk about a type called JSONB, I see it in the codebase, and I'm using Postgres.

But when I use the type for a field:
```javascript
field: Sequelize.JSONB
```

I get
```bash
Unhandled rejection SequelizeDatabaseError: type "jsonb" does not exist
```

**Comment by mickhansen** [comment]
What version is your postgres database?

**Comment by GeoffreyPlitt** [comment]
9.3.7

**Comment by KlonD90** [comment]
@GeoffreyPlitt it's 9.4 release.
http://www.postgresql.org/docs/current/static/release-9-4.html
I made upgrade for this feature a few days ago.

**Comment by mickhansen** [comment]
As @KlonD90 mentions only 9.4 supports JSONB
