### ISSUE TITLE
Transaction retry?

### ISSUE THREAD

**Issue by smithb1994** [sequelize/sequelize#3879]
If there are 2 transactions happening concurrently in postgres, postgres will give a 
`ERROR:  could not serialize access due to concurrent update`
Is there a way to make transactions queue up to wait for the previous transaction to finish, rather than giving me back an error?
Is there a SQL, or sequelize solution to this?

Here's my code:
(NOTE: my transaction isolation is set to Serializable)
```javascript
//QUERY
return sql.transaction(function (t1) {
    return sql.query(
        'UPDATE users SET nonce = nonce + 1 WHERE u_id = :u_id',
        {
            replacements: {
                u_id: u_id
            },
            type: sql.QueryTypes.UPDATE,
            transaction: t1
        }
    );
});
```

**Comment by smithb1994** [comment]
I solved my problem, see my solution here 
http://stackoverflow.com/questions/30657118/postgres-wait-for-transaction-to-finish
I had to set my transaction isolation level to "Read commited"

**Comment by mickhansen** [comment]
We have nothing native built in, but you could use a simple promise retry logic or try https://www.npmjs.com/package/retry-as-promised
