### ISSUE TITLE
How to get created model from a transaction?

### ISSUE THREAD

**Issue by canebat** [sequelize/sequelize#3883]
I don't quite understand how to reference a created model after a transaction has successfully committed the operation:

For instance, I create a `user` and their associated `items`:

```
sequelize.transaction(function(t) {
    return models.user.create({ name: name, email: email }).then(function(user) {
        return Promise.map(items, function(item) {
            return models.item.create({ name: item.name }, {transaction: t});
        });
    });
}).then(function(result) {
    console.log(result);         // This is 'undefined'
    console.log( "Created user: ");
    // console.log(  user.name );   <---- How do I get newly created user model here?
});
```

**Comment by mickhansen** [comment]
This is a promise question rather than a sequelize question.
`transaction` will return the result of the returned promise. So in this case it should be an array of created items.
