### ISSUE TITLE
[MSSQL] Inserted id field case-sensitivity

### ISSUE THREAD

**Issue by ackerdev** [sequelize/sequelize#3884]
Assuming we have model Foo like so:

``` js
sequelize.define('Foo', {
  id: {
    type: DataTypes.INTEGER,
    field: 'fooId',
    autoIncrement: true
  }
});
```

Where the actual field in the database is `FooId` (note capital F), when attempting to create/save a new Foo instance, the instance returned in the promise will have an undefined id. This is caused by the fact that the INSERT query uses [`OUTPUT INSERTED *`](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query-generator.js#L215), which means that the column comes back as `FooId`, and when `Query.handleInsertQuery` attempts to find the id via [autoIncrementFieldAlias](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query.js#L274) it will use `fooId` instead of `FooId`, causing the id to be undefined when the instance is returned.

Ideally, it would be nice for the query to change to selecting the columns with aliases as it does with a regular SELECT query (eg. `OUTPUT INSERTED.[fooId] as [id]`) or otherwise work around this case insensitivity.

If nothing else, it might be worth adding some sort of error messaging when the id was not found.

**Comment by kant2002** [comment]
This issue still here.
