### ISSUE TITLE
Database calls in getters

### ISSUE THREAD

**Issue by sn0rcha** [sequelize/sequelize#3886]
Hey There,

I was wondering if it's possible to make a database call to another model inside a getter function. I've been trying all sorts of things with promises eg:

```
currentinvoiceamount:{
             type: DataTypes.VIRTUAL,
             get: function(){
             var deferred = Q.defer();
             db.models.Client.findById(1).then(function(client){
                   //do some stuff
                   deferred.resolve(client.somefield);
               });
           return deferred.promise;
           }
     }
```

I have cases where I want to add external data to a virtual field inside a model. Is there a way to do this. And also, is there a way to specify the default "eager loads" for associations on a model?

Cheers,
Ben

**Comment by mickhansen** [comment]
getters will always be synchronous, we've discussed it a multitude of times.
You'd probably be better off solving this with a include, or a virtual field with a afterFind hook.

**Comment by sn0rcha** [comment]
Many thanks for your reply, I checked the docs but there was no mention of "afterFind" as a hook - http://docs.sequelizejs.com/en/latest/docs/hooks/ - does it exist?

**Comment by mickhansen** [comment]
It does, we just haven't documented it yet apparently.
The syntax is:

```js
Model.afterFind(function (instance|instances, options) {

});
```
