### ISSUE TITLE
Mutilple model files and associations

### ISSUE THREAD

**Issue by sn0rcha** [sequelize/sequelize#3887]
I use the following script to import my models:

```
var fs = require("fs");
var path = require("path");
var db = {};

module.exports = function (dbIntranet, Sequelize) {
    fs.readdirSync(__dirname)
        .filter(function (file) {
            return (file.indexOf(".") !== 0) && (file !== "index.js");
        })
        .forEach(function (file) {
            var model = dbIntranet["import"](path.join(__dirname, file));
            db[model.name] = model;
        });

    Object.keys(db).forEach(function (modelName) {
        if ("associate" in db[modelName]) {
            db[modelName].associate(db);
        }
    });

    //set vars
    db.sequelize = dbIntranet;
    db.Sequelize = Sequelize;

    return db;
};
```

In some of my models, I always want the relations to be included, so I've set the "defaultScope" as follows:

```
classMethods: {
   associate:function(){
       CurrentModel.belongsTo(AnotherModel)
},
   defaultScope:{
       include:[['SomeRelation']]
}}
```

However, it seems if the model file the relation is on is included AFTER the one calling it, it'll error out with "Name undefined" etc... If I do ```CurrentModel.findById(1,{include: [{model:AnotherModel}]}).then()``` it will work with no errors. If I manaully require the model file in the one that has the relation defined, it will also work. Is there something I'm missing or are you not supposed to include relations in the "defaultScope"?

Cheers,
Ben

**Comment by janmeier** [comment]
String based includes are not supported. You'll have to pass a model in the default scope
