### ISSUE TITLE
Date format used for MSSQL dialect appears to be incorrect

### ISSUE THREAD

**Issue by zeiphon** [sequelize/sequelize#3892]
Sequelize translates the `Sequelize.DATE` type into `DATETIME2` for MSSQL, but then proceeds to format dates in this format: `'YYYY-MM-DD HH:mm:ss.SSS Z'`.
MSSQL's formats are as follows:

Data Type | Format
------------ | -------------
`datetime`|`YYYY-MM-DD hh:mm:ss[.nnn]`
`datetime2`|`YYYY-MM-DD hh:mm:ss[.nnnnnnn]`
`datetimeoffset`|`YYYY-MM-DD hh:mm:ss[.nnnnnnn] [+|-]hh:mm`

(from https://msdn.microsoft.com/en-us/library/ms186724.aspx )

Since sequelize is including the offset when it shouldn't be, was a `datetimeoffset` type expected?

**Comment by zeiphon** [comment]
I should mention that unless this is configurable, requiring a `datetimeoffset` date type could be problematic for those wishing to use Sequelize with a pre-existing schema, since `datetime`/`datetime2` are more common.

**Comment by mbroadst** [comment]
@zeiphon that may be the case, however the implementation was based on the existing legacy databases of @thecaddy and me which I imagine were both using DATETIME2. 

This does, however, bring up an interesting point about being able type customizations. I had in fact converted this to use DATETIMEOFFSET previously, but there was no way at the time to accommodate both paths. This may have changed with recent refactorings of the type system, so any contribution would be gladly reviewed and accepted.

**Comment by zeiphon** [comment]
Sequelize currently has this in `sql-string.js`:
```javascript
SqlString.dateToString = function(date, timeZone, dialect) {
  if (moment.tz.zone(timeZone)) {
    date = moment(date).tz(timeZone);
  } else {
    date = moment(date).utcOffset(timeZone);
  }

  if (dialect === 'mysql' || dialect === 'mariadb') {
    return date.format('YYYY-MM-DD HH:mm:ss');
  } else {
    // ZZ here means current timezone, _not_ UTC
    return date.format('YYYY-MM-DD HH:mm:ss.SSS Z'); /// <-- Executed for MSSQL - includes offset
  }
};
```

And this in `dialects/mssql/data-types.js`:
```javascript
DATE.prototype.toSql = function() {
  return 'DATETIME2';
};
```

Perhaps one should be changed to align with the other?

**Comment by seanlindo** [comment]
@zeiphon I haven't run into a datetimeoffset column in a very long time. Being able to configure this based on your dialect would be immensely helpful. I'll probably modify the source for now.

**Comment by seanlindo** [comment]
@zeiphon Simply adding an extra OR to `sql-string.js` was enough for now; however, directly modifying source code isn't the best idea. I'd like to find out if Sequelize exposes a configuration object on the Models we can pass in here.

**Comment by ereami** [comment]
My first test with sequelize, and I had a datetime field on my table, @zeiphon. Including the || dialect === 'mssql' on sql-string.js would be enough? Could you integrate this change?

Cheers.

**Comment by snickell** [comment]
Having trouble with this too... I have an existing schema with a Datetime column, on SQL Server. My model code is like this:
```
sequelize.define('SomeTable', {
  ID: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true        
  },
  Created: {
    type: DataTypes.DATE,
    allowNull: false
  }
}, {
  freezeTableName: true,
  createdAt: false,
  updatedAt: false
})
```

**Comment by snickell** [comment]
As a workaround, I'm monkeypatching sql-string.js/dateToString to behave as mysql:
```
console.warn("Monkeypatching ('sequelize/lib/sql-string').dateToString to work with MSSQL datetime columns (see: https://github.com/sequelize/sequelize/issues/3892)");
var sqlString = require('sequelize/lib/sql-string');
var dateToString = sqlString.dateToString;
sqlString.dateToString = (d, tz, dialect) => dateToString(d, tz, 'mysql');
```

**Comment by ereami** [comment]
Thanks, @snickell 

That's a more elegant solution I guess :)

**Comment by zeeshanjan82** [comment]
I have the date stored in MySql as : 2015-10-29 13:57:00 but when I get it back using sequelize, this is what I get : 2015-10-29T13:57:00.000Z  This is not understood by angularjs as it does not understand T & Z letters in the date. Is there any way to get the date exactly as it is stored in the mysql column?

**Comment by janmeier** [comment]
@zeeshanjan82 Please don't hijack other issues - this is an mssql issue

What you get out of the DB is a javascript date object, and always will be. When its sent over the wire its converted to a string, but when parsing again it should be a date object. Angular should be able to handle those just fine, otherwise you can use `date.format`, or a library like moment.js

**Comment by mickhansen** [comment]
@zeeshanjan82 @janmeier Date is serialized to a JSON date string. Angular does not necessarily work with this out of the box. You need to do `new Date()` after receiving the response.

In no way a sequelize question though @zeeshanjan82

**Comment by janmeier** [comment]
Ah, I thought `JSON.parse(datestring)` would give a date object - appearently not

**Comment by zeeshanjan82** [comment]
Thanks @janmeier @mickhansen I understand but I was hoping that we have any option in sequelize to return date in a particular format like MMM-dd-yy or any other format and it should be some global setting. I would like to return all my dates from mysql in a specific format which then I do not have to format using angularjs.

**Comment by zeeshanjan82** [comment]
something like this: 
````js
  [sequelize.fn('date_format', sequelize.col('date_col'), '%Y-%m-%d'), 'date_col_formed']],

```

**Comment by mickhansen** [comment]
@zeeshanjan82 Sequelize returns a javascript date, you can format that any way you like. But using a custom attribute is an option aswell, that's up to you :)

**Comment by janmeier** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/5274 to use YYYY-MM-DD hh:mm:ss[.nnn]

(Yes, I know that datetime2 theoretically offers 6 digits of ms precision, but javascript doesn't :D)

**Comment by snickell** [comment]
wow, thank you so much @janmeier

**Comment by Aukhan** [comment]
@mickhansen thanks for explicitly mentioning that Sequelize.Date is a Date Object. I'm sure It's in the docs as well. I was trying to save it by assigning a value via `moment.format("mysql datetime format")` and wondering why in the world is Sequelize adding a timezone Offset to my date =[
