### ISSUE TITLE
Refer to table column in where clause

### ISSUE THREAD

**Issue by Roam-Cooper** [sequelize/sequelize#3893]
As an example, being able to do:

``` javascript
{
    where: {
        firstColumn: secondColumn
    }
}
```

Where firstColumn and secondColumn are columns on the same table. Is this possible in 1.7.0? (Or up, 1.7.0 is just what I'm using.)

**Comment by mickhansen** [comment]
Not possible in any version, but it's on our list, not sure there's an existing issue though.
Feature would likely be something like:

```js
field: '$otherfield$'
```

/cc @janmeier

**Comment by janmeier** [comment]
It is possible with sequelize.col but not awfully pretty ;)

```js
{
  where: {
    firstColumn: sequelize.col('secondColumn')
  }
}
```

Mongosql $ syntax would indeed be prettier :)

**Comment by mickhansen** [comment]
@janmeier with wrapping or with a seperate operator?

**Comment by janmeier** [comment]
With wrapping I think

**Comment by juanjoLenero** [comment]
I've been able to do it like this:
```javascript
where: {
    sequelize.where(sequelize.col('table.prop'), '=', sequelize.col('table.otherProp'))
}
```

**Comment by VividVisions** [comment]
+1

**Comment by NHMD** [comment]
+1

**Comment by radhomero** [comment]
+1

It helped me to filter by Id an included table already joined by Id, when the compared table were higher on the join hierarchy.

```
where: {
  id: sequelize.col('otherTable.associatedId')
}
```
Did not work, don't know why.

The @juanjoLenero example worked fine!

**Comment by aasmm7x** [comment]
This problem happens also on `where` option.

 `where?: WhereOptions<T> | where | fn | or | Array<col | and | or | string>;` @ https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/interfaces/IFindOptions.ts

It should support `literal` also on `where`.

**Comment by asgharmusani** [comment]
Is this achievable as of now with a pretty syntax?

**Comment by AllanJeremy** [comment]
> Is this achievable as of now with a pretty syntax?
Actually curious about this as well
