### ISSUE TITLE
raw:true with hasMany

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#3897]
Hi,

Continuing my raw:true questions series.

If it's possible to get not the plain object with raw:true, when we query the entiry + the child entities with the relation oneToMany ?

For example, assuming the clientdata has many locations, how can we query 1 clientdata + all the locations and return everything in raw?

```javascript
 model.find({
                    include : [
                        {
                            model: server.methods.getModel('ClientData'),
                            include: [
                                {
                                    model: server.methods.getModel('Location')
                                }
                            ]
                        }
                    ],
                    where: {id:2308242},
                    raw:true
                }).then(function(application) {
                    console.log(application);
                    return reply(application);
                });
```

Currently the first location object is returned.

Regards,

**Comment by mickhansen** [comment]
Not possible with raw currently, when you use raw you disable our deduplication logic.

**Comment by RoboBurned** [comment]
I think it is very serious issue. For example I have a Feed that has many (1k) Products. I do not want to get the instances for all products. I just need data. Now I can't get the feed with raw products.

**Comment by mickhansen** [comment]
@RoboBurned PRs are always welcome, a setting for query that enables join data grouping although raw is true or similar, shouldn't be too trick.y

**Comment by Relequestual** [comment]
This issue is probably replaced by https://github.com/sequelize/sequelize/issues/5193

**Comment by zanlucathiago** [comment]
You can use raw: false and run JSON.parse(JSON.stringify(data)) on returning model.
