### ISSUE TITLE
Support for schema dump

### ISSUE THREAD

**Issue by dankohn** [sequelize/sequelize#390]
In addition to migrations, it would be fantastic to have schema dump support, to make it easy to create initial migrations and check them into source control.

Here's how Rails does it (with Ruby and SQL flavors), but just supporting a schema.js file (identical to migrations), would be fantastic:
http://guides.rubyonrails.org/migrations.html#schema-dumping-and-you

**Comment by slifty** [comment]
I would love to see something like this, particularly to provide a cleaner (and faster) tool to generate test environments than running all the migrations up and down every time I want to unit test.

Maybe this would done as a schema dump method and a schema load method (taking a path to schema dump) which would be part of the sequelize object methods?

If we can collectively decide on the proper specs for this, I'm happy to spend some time trying to implement it.

**Comment by mickhansen** [comment]
@slifty I personally just do a full sync() in tests, but i suppose running migrations gives a better picture of the world.

We'd like to do schema diffing in the future. And a step to that path is being able to take a database schema and turn it into sequelize semantics, which would support this usecase aswell i believe.

**Comment by milovanderlinden** [comment]
See #120 for a possible solution in the future

**Comment by TanguyP** [comment]
How is this related to issue #120? I see those as two very different requests, and this feature (Rails-like schema dump) is still very much needed IMO.
