### ISSUE TITLE
afterCreate hook runs but the data is not in the database

### ISSUE THREAD

**Issue by curiousdannii** [sequelize/sequelize#3900]
I have an afterUpdate hook that seems to be working perfectly, but my afterCreate hook is not. It is run, but the data has not been inserted into the database yet.

**Comment by mickhansen** [comment]
Are you using a transaction?

**Comment by curiousdannii** [comment]
Not explicitly (I'm not sure how it works under the hood). The rows are being created by Model.findOrCreate().

**Comment by mickhansen** [comment]
findOrCreate uses a transaction interally.
You'll have to use the same transaction in the hook since it's not committed yet at that point.

**Comment by curiousdannii** [comment]
@mickhansen Ah, thanks for the explanation. I've seen a lot of issues saying the docs are out of date, and this is another one.

In the docs if I see [options.transaction] in the options listing, does that mean the function always uses a transaction? (So .save() does too?)

**Comment by mickhansen** [comment]
@curiousdannii No that means it takes a transaction. findOrCreate uses an internal transaction if none is supplied to ensure a concurrenctly safe findOrCreate.

**Comment by mickhansen** [comment]
Yeah the docs could be improved for this tidbit, definitely :)
Generally we probably need some info for hooks that says you should always pass-on options.transaction to your in-hook calls regardless of it being defined or not.
