### ISSUE TITLE
Turn of prefix in where clause, nested where, include where parent

### ISSUE THREAD

**Issue by Orvacko** [sequelize/sequelize#3903]
Hi,

is there any posibility to turn of 'table_prefix' in where clause?

Problem:
```js
...
finder.include = {model: db.Company, attributes: ['id', 'name'], as: 'payer', where: where2};
finder.where = db.Sequelize.and(where, {company_company_id: req.query.company_id});
db.CompanyPayers.findAndCountAll(finder).then(function(result) {
...
```
Output:
```sql
SELECT count(`company_payers`.`id`) AS `count`
FROM `acrm_company_payers` AS `company_payers`
INNER JOIN `acrm_companies` AS `payer` ON `company_payers`.`payer_id` = `payer`.`company_id`
AND (`payer`.`deleted` IS NULL
     AND `payer`.`name` LIKE '%ab%')
WHERE (`company_payers`.`deleted` IS NULL
       AND ((`company_payers`.`id` LIKE '%ab%'
             OR `company_payers`.`created_by` LIKE '%ab%'
             OR `company_payers`.`created` LIKE '%ab%')
            AND `company_payers`.`company_company_id` = '134837'));
```

Is there any posibility to aim this? (different is bold):

 SELECT count(`company_payers`.`id`) AS `count` FROM `acrm_company_payers` AS `company_payers` INNER JOIN `acrm_companies` AS `payer` ON `company_payers`.`payer_id` = `payer`.`company_id` AND (`payer`.`deleted` IS NULL AND `payer`.`name` LIKE '%ab%') WHERE (`company_payers`.`deleted` IS NULL AND ((`company_payers`.`id` LIKE '%ab%' OR `company_payers`.`created_by` LIKE '%ab%' OR `company_payers`.`created` LIKE '%ab%' __OR `payer`.name LIKE '%ab%'__) AND `company_payers`.`company_company_id` = '134837'));

When you use:
```
...
where.name = {$like: '%ab%'};
finder.include = {model: db.Company, attributes: ['id', 'name'], as: 'payer', where: where2};
finder.where = db.Sequelize.and(where, {company_company_id: req.query.company_id});
db.CompanyPayers.findAndCountAll(finder).then(function(result) {
...
```

That where will add `company_payers` prefix so output is this: (different is bold)
SELECT count(`company_payers`.`id`) AS `count` FROM `acrm_company_payers` AS `company_payers` INNER JOIN `acrm_companies` AS `payer` ON `company_payers`.`payer_id` = `payer`.`company_id` AND (`payer`.`deleted` IS NULL AND `payer`.`name` LIKE '%ab%') WHERE (`company_payers`.`deleted` IS NULL AND ((`company_payers`.`id` LIKE '%ab%' OR `company_payers`.`created_by` LIKE '%ab%' OR `company_payers`.`created` LIKE '%ab%' __OR `company_payers`.name LIKE '%ab%'__) AND `company_payers`.`company_company_id` = '134837'));

I have tried everything, nested where (ex.: where.payer = {name: {$like: '%ab%'}}) but it still generate `company_payers`.payer LIKE [Object ..] and throws error

Thank you

**Comment by janmeier** [comment]
No, it is not possible to turn of the prefix. But it should still be possible to do what you want.

Can you show model definitions and assoications?

**Comment by Orvacko** [comment]
I have made simple example:

- lets have this (simplified) definition
```
var Campaign = sequelize.define('campaign', {
   id: {type: DataTypes.INTEGER, primaryKey: true},
   campaign_name: {type: DataTypes.STRING(255), allowNull: false, validate: {notEmpty: true, isAlphanumeric: true}},
   activate_time: {type: DataTypes.DATE, allowNull: false, validate: {notEmpty: true}},
   expire_time: {type: DataTypes.DATE, allowNull: true},
   status: {type: DataTypes.INTEGER, allowNull: false},
   created_by: {type: DataTypes.INTEGER, validate: {isNumeric: true}},
   modified_by: {type: DataTypes.INTEGER, validate: {isNumeric: true}},
   deleted_by: {type: DataTypes.INTEGER, validate: {isNumeric: true}}
}, {
   timestamps: true,
   paranoid: true,
   underscored: true,

   createdAt: 'created',
   updatedAt: 'modified',
   deletedAt: 'deleted',

   classMethods: {
       associate: function (models) {
           Campaign.belongsTo(models.Advertiser, {foreignKey: 'clientid'});
       }
   }
});

var Advertiser = sequelize.define('advertiser', {
   id: { type: DataTypes.INTEGER, primaryKey: true },
   advertiser_name: { type: DataTypes.STRING(255), allowNull: false, validate: { notEmpty: true, isAlphanumeric: true } },
   created_by: { type: DataTypes.INTEGER, validate: { isNumeric: true }},
   modified_by: { type: DataTypes.INTEGER, validate: { isNumeric: true }},
   deleted_by: { type: DataTypes.INTEGER, validate: { isNumeric: true }}
}, {
   timestamps: true,
   paranoid: true,
   underscore: true,

   classMethods: {
       associate: function (models) {
           Advertiser.hasMany(models.Campaign, { foreignKey: 'clientid' });
       }
   }
});
```

- and you execute this
```
db.Campaign.findAll({
   order: 'id DESC',
   limit: 20,
   where: Sequelize.or({'campaign_name' : { $like: '%test%' }}, {'advertiser.advertiser_name': {$like: '%test%'}}),
   attributes: ['id', 'campaign_name'],
   include: [{model: db.Advertiser, as: 'advertiser', attributes: ['advertiser_name'], where:{}}]
}).then(function (result) {

});
```

- what do you expect is something like this (in part of SQL):
```
... WHERE campaign_name LIKE '%test%' OR advertiser.advertiser_name LIKE '%test'% ...
```

- but with prefixes you get
```
... WHERE `campaign`.campaign_name LIKE '%test%' OR `campaign`.advertiser.advertiser_name LIKE '%test'% ...
```
- and off course it end with error because you have not defined column `campaign`.campaign_name or `campaign`.advertiser.advertiser_name
- this is cause of prefixes

Is there any solution/way/hack, that you can do the parent WHERE without prefixes (or if not), create WHERE in our need ?

**Comment by janmeier** [comment]
Ah, I missed the fact that you wanted the where to be outside the join

https://github.com/sequelize/sequelize/issues/3095
