### ISSUE TITLE
"Order by" defaults to id even if there's no id field on a model

### ISSUE THREAD

**Issue by adonomay** [sequelize/sequelize#3904]
Using the MSSQL dialect:
```
var Car = sequelize.define('Car', {
  make: Sequelize.STRING
});
Car.removeAttribute('id'); // don't want an "id" column for this table

Car.findAll().then(function(cars) {
  console.log(cars);
});
```

I get an "invalid column name 'id' " error. The query Sequelize tries to execute includes an `ORDER BY [id]` clause.  I need to specify `{ order: 'make' }` in each of my queries to prevent this. Is there a way to specify "default order-by field if none is given" for the `Car` model?  Will defining some other primary key set that as the default for ORDER BY when no `{ order: 'something' }` is provided?

**Comment by mickhansen** [comment]
Humm, findAll generally doesnt add a default order.
Maybe this is a MSSQL specific implementation detail @mbroadst?

**Comment by mbroadst** [comment]
@mickhansen there shouldn't be any added on just a findAll, @adonomay can you maybe post the generated SQL for your case?

**Comment by adonomay** [comment]
My mistake, I had a `{ limit: 10 }` in my query as well.  Still, I'd assume limit 10 maps to "select top 10", which doesn't require an ORDER BY in MS SQL.

**Comment by mbroadst** [comment]
@adonomay ah yes, there are some complications with expressing the SQL that way which, if solved, would be a welcome addition to the dialect. This is a particular need for supporting MSSQL pre 2010, but as of yet nobody has stepped up to the challenge :smile:
