### ISSUE TITLE
broken link from NPM readme.md

### ISSUE THREAD

**Issue by mikeljames** [sequelize/sequelize#3905]
correct link:http://docs.sequelizejs.com/latest/docs/getting-started/
broken link:http://docs.sequelizejs.com/articles/getting-started

identified the broken link at:
https://www.npmjs.com/package/sequelize

**Comment by janmeier** [comment]
Hmmm, I actually thought the text on npm was the most recent one from the readme .. but apppearently not. I can't find a way to change the text though ....

**Comment by mickhansen** [comment]
@janmeier Hmm it should be pulling from the readme on publish.

**Comment by janmeier** [comment]
Works now :)
