### ISSUE TITLE
Missing column "createdAt" when using "field" param with bulkCreate command

### ISSUE THREAD

**Issue by aysbg** [sequelize/sequelize#3908]
I have this error since upgrading to 3.0: (`"sequelize": "^3.2.0"` to be precise)
```
{ [SequelizeDatabaseError: column "createdAt" of relation "store_table" does not exist]
  name: 'SequelizeDatabaseError',
  message: 'column "createdAt" of relation "store_table" does not exist',
  parent:
   { [error: column "createdAt" of relation "store_table" does not exist]
     name: 'error',
     length: 124,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '59',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_target.c',
     line: '923',
     routine: 'checkInsertTargets',
```

And field is defined:
```
module.exports = function(sequelize) {
  'use strict';

  var DataTypes = require('sequelize');

  return sequelize.define(
    'store_table', {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true
      },

      brandId: {
        type: DataTypes.INTEGER,
        field: 'brand_id',
        references: 'brand',
        referencesKey: 'id'
      },

      name: {
        type: DataTypes.STRING,
        allowNull: true,
        validate: {
          len: [1, 64]
        }
      },

      address: {
        type: DataTypes.TEXT,
        allowNull: true,
        validate: {
          len: [1, 256]
        }
      },

      createdAt: {
        type: DataTypes.DATE,
        field: 'created_at'
      },

      updatedAt: {
        type: DataTypes.DATE,
        field: 'updated_at'
      }

    }, {
      freezeTableName: true
    }
  );
};
```
And present in the DB, obviously under the name of `created_at`.
After reading this issue: https://github.com/sequelize/sequelize/issues/2641 I tried by adding `underscored: true` flag and it does work as before.

The issue is only present on the bulkCreate

**Comment by aysbg** [comment]
Got small addendum for this issue... happens on `create` (insert)

**Comment by simalexan** [comment]
+1 
identical situation

**Comment by aysbg** [comment]
The error is present on every version of Sequelize 3.x.x on bulkCreate command.

**Comment by mickhansen** [comment]
Do you have `timestamps` enabled? I see that you define a custom createdAt.

**Comment by aysbg** [comment]
They are not disabled. I define custom because I need a `field` param. I tried different variations.

I tried with timestamps and underscored and then I tried like this:
```
createdWAt: {
    type: Sequelize.DATE,
    field: 'created_at'
  }
}, {
  createdAt   : 'createdWAt',
  timestamps  : true,
});
```
I'd get an error for missing `createdWat` column.

Just try to map a different name to timestamps and do bulkCreate.

**Comment by aysbg** [comment]
Here is the issue, bulkCreate doesn't read the "field" property for the column definition and its trying to do an insert to a `createdAt` column while I have in the table `created_at`:
```sql
sql: 'INSERT INTO "category" ("id","name","createdAt","updatedAt") VALUES (DEFAULT,\'Arts, crafts, and collectibles\',\'2015-06-12 05:44:12.479 +00:00\',\'2015-06-12 05:44:12.479 +00:00\')
```

**Comment by mickhansen** [comment]
Thank you, just wanted to get all the details about the bug :)

**Comment by huangbin30** [comment]
apply following patch to Model.prototype.bulkCreate will resolve this issue:

    instances.forEach(function(instance) {
      var values = instance.dataValues;

      // set createdAt/updatedAt attributes
      if (createdAtAttr && !values[createdAtAttr]) {
        values[createdAtAttr] = now;
      }
      if (updatedAtAttr && !values[updatedAtAttr]) {
        values[updatedAtAttr] = now;
      }

      instance.dataValues = Utils.mapValueFieldNames(values, options.fields, self);
    });

**Comment by huangbin30** [comment]
Patching following code to Model.prototype.bulkCreate should work.

    instances.forEach(function(instance) {
      var values = instance.dataValues;

      // set createdAt/updatedAt attributes
      if (createdAtAttr && !values[createdAtAttr]) {
        values[createdAtAttr] = now;
      }
      if (updatedAtAttr && !values[updatedAtAttr]) {
        values[updatedAtAttr] = now;
      }

      instance.dataValues = Utils.mapValueFieldNames(values, options.fields, self);
    });

**Comment by smolyakoff** [comment]
Hey, what's the state of this bug?

**Comment by aysbg** [comment]
@mickhansen I tried the patch suggested by @huangbin30 and it works. Can you @huangbin30 create a PR with this fix?

**Comment by aysbg** [comment]
Unfortunately suggested patch breaks several tests regarding bulkCreate.

**Comment by huangbin30** [comment]
Thanks, @aysbg. I will try to make a pull request and finish tests.

**Comment by realalexhomer** [comment]
Hey @aysbg and @huangbin30 what is the state of this? I could try to make a PR if you @huangbin30 doesn't have time.

**Comment by rvnath** [comment]
I too get the same issue with bulkCreate.

**Comment by ro70** [comment]
I'm running sequelize 3.19.3. Still got this issue...

**Comment by edrpls** [comment]
I ran into the same issue with duplicate timestamps (camelCase and snake_case) but with different values, I am not using bulkCreate, just setting the fields timestamps with {field: 'some_name'}.

I am setting updatedAt to certain date, but updated_at has a different one (the result of NOW() instead of my date), am I doing something wrong?

**Comment by galioy** [comment]
I'm still having this problem on `v3.30.4`

**Comment by Kyderman** [comment]
Use the `field:` attribute in the modle property, and ensure `underscored: false` globally, works fine

**Comment by guths** [comment]
> Here is the issue, bulkCreate doesn't read the "field" property for the column definition and its trying to do an insert to a `createdAt` column while I have in the table `created_at`:
> 
> ```sql
> sql: 'INSERT INTO "category" ("id","name","createdAt","updatedAt") VALUES (DEFAULT,\'Arts, crafts, and collectibles\',\'2015-06-12 05:44:12.479 +00:00\',\'2015-06-12 05:44:12.479 +00:00\')
> ```
> 
> This is completely new table that I created just to test the use case. The result is the same, with or without `timestamps: true` attribute.
> 
> If I add `underscored: true`, then the SQL is correct and I see:
> 
> ```sql
> Executing (default): INSERT INTO "category" ("id","name","created_at","updated_at")
> ```
> 
> However, when I do `Category.find`, I see double timestamps, take a look: ![screen shot 2015-06-12 at 07 48 58](https://cloud.githubusercontent.com/assets/2363475/8124177/81df8b80-10d7-11e5-8963-7a87e1aa8aed.png)
> 
> This is the full definition of the Model:
> 
> ```js
> module.exports = function(sequelize) {
>   'use strict';
> 
>   var DataTypes = require('sequelize');
> 
>   return sequelize.define(
>     'category', {
>       id: {
>         type: DataTypes.INTEGER,
>         autoIncrement: true,
>         primaryKey: true
>       },
> 
>       name: {
>         type: DataTypes.STRING,
>         unique: true,
>         allowNull: false,
>         validate: {
>           len: [1, 64]
>         }
>       },
> 
>       createdAt: {
>         type: DataTypes.DATE,
>         field: 'created_at'
>       },
> 
>       updatedAt: {
>         type: DataTypes.DATE,
>         field: 'updated_at'
>       }
> 
>     }, {
>       timestamps: true,
>       underscored: true,
>       freezeTableName: true
>     }
>   );
> };
> ```

thanks a lot, I took a long time to find you aswear.
