### ISSUE TITLE
`Promise#done()` not passing CLS context

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#3909]
`Promise#done()` isn't passing CLS context.

I had a try at fixing it, but couldn't get it working:
https://github.com/overlookmotel/sequelize/commit/c1df7b28c050c25c6268728fc189ba3393a4eee1

The 'done fulfilled' test fails.

And don't know how to test for 'done rejected' properly as it (by design) throws an async error and doesn't return a promise.

**Comment by overlookmotel** [comment]
Any ideas @mdarveau, @ndreas?

**Comment by janmeier** [comment]
Hmm, weird that the fullfilled test fails - it seems to just map to `then`.... 

As I read done rejected, it throws an error, instead of calling the callback, right? In that case there is no way to catch the error?

>  but any unhandled rejection that ends up here will be thrown as an error...

**Comment by overlookmotel** [comment]
Fixed it! Problem was in the construction of the tests, not that context wasn't being passed.

`.done()` doesn't return a promise, so the auto-commit of the transaction was being executed before the `expect(transaction.id)...` statement.

PR https://github.com/sequelize/sequelize/pull/3912
