### ISSUE TITLE
Raw objects in result for findOne.includes

### ISSUE THREAD

**Issue by MikeBazhenov** [sequelize/sequelize#3910]
When i do request with includes models, request return found object with includes keys as raw object...

I want that includes keys will be as `Account Model` objects...

```JavaScript

//Associations
this.belongsTo(db.Account, {foreignKey: 'worker_id', as: 'worker'});
this.belongsTo(db.Company, {foreignKey: 'company_id', as: 'company'});

//Find 
this.findOne({
  where: {
    id: 123
  },
  include: [
    {
      model: internals.db.Account,
      as: 'account'
    },
    {
      model: internals.db.Account,
      as: 'worker'
    }
  ]
}).then(function(result) {
  console.log(result.worker.toObject()); //will be error toObject is not a function
});

```

**Comment by janmeier** [comment]
This works fine for me - can you provide a full testcase (with model and instancemethod definition)

**Comment by MikeBazhenov** [comment]
@janmeier 

Account model
https://gist.github.com/MikeBazhenov/eb2e42643cd728e4b485

Directive model
https://gist.github.com/MikeBazhenov/cc246a9fd1ac4860f627

Method for test `findByHashId` in Directiva model

**Comment by janmeier** [comment]
@MikeBazhenov Those model definitions are enormous, and I get several errors when I try to run them. Please try to create a self-contained example
