### ISSUE TITLE
sequelize.getMigrator is undefined

### ISSUE THREAD

**Issue by Olgagr** [sequelize/sequelize#3916]
I'm trying to get migrator programmatically, but when I do sequelize.getMigrator() I get an Type Error:
```
[TypeError: undefined is not a function]
```

Indeed, when I grep the source code of sequelize (version 3.1.0) I don't see the definition of this function on object Sequelize. I use sequelize-cli to manage my migrations. Is documentation is actual or something changed ?

**Comment by BridgeAR** [comment]
Hey Olga,

the migrations have been removed from Sequelize in Version 3.0. Please use umzug instead.

**Comment by Olgagr** [comment]
@BridgeAR Thanks for answer. Good to know.
