### ISSUE TITLE
AddColumn / ChangeColumn cannot deal with primary keys

### ISSUE THREAD

**Issue by arcanis** [sequelize/sequelize#3918]
Hi,

The following code does not work (at least not with Postgres):

``` js
migration.addColumn('Table', 'column', { type: STRING, primaryKey : true });
migration.changeColumn('Table', 'column', { type: STRING, primaryKey : true });
```

In both case, Sequelize strips the primary key flag [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L838).

Is there a way to change the primary keys without resorting to plain raw queries?

**Comment by dantman** [comment]
This seems to be because the proper way to add a primary key in pg appears to be to create an index and then use `ALTER TABLE ADD CONSTRAINT pkey_name PRIMARY KEY USING INDEX index_name`.

**Comment by jdgreenberger** [comment]
:+1:

**Comment by abimelex** [comment]
This seems still an issue. What would be the best workaround?

**Comment by sushantdhiman** [comment]
in v4 you can use `addConstraint / removeConstraint` https://github.com/sequelize/sequelize/pull/7108
