### ISSUE TITLE
Feature: "map" a table

### ISSUE THREAD

**Issue by arcanis** [sequelize/sequelize#3919]
Hi,

When refactoring a database, I think it's quite common to do things like this:

``` sql
UPDATE FROM "Table" SET "column" = "otherColumn" + 1
```

A real use case will obviously be a bit more complex, but you can see the gist. Unless I'm mistaken, Sequelize doesn't currently provide any builtin way to do this, which requires us to use plain raw queries.

Maybe it could be an interesting tool to add to the migration suite? With an API such as:

``` js
migration.mapTable('Table', {
  column : [ '? + 1', sequelize.col( 'otherColumn' ) ]
})
```

**Comment by janmeier** [comment]
We have [`instance.increment`](http://docs.sequelizejs.com/en/latest/api/instance/#incrementfields-options-promisethis) but it would probably be nice to add `increment` with a where condition to models as well

**Comment by arcanis** [comment]
@janmeier increment was only an example; furthermore, my example isn't exactly like increment. See the difference between `column = otherColumn + 1` and `column = column + 1`
