### ISSUE TITLE
Cannot call method 'then' of undefined

### ISSUE THREAD

**Issue by miguelcrespo** [sequelize/sequelize#3921]
Hi.

I have an issue, I am starting with your ORM and I am following this code to implement it in my express project: https://github.com/sequelize/express-example

This is my user model:
```
module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define("User", {
    username: DataTypes.STRING
  });

  return User;
};
```
And here is where I'm trying to create a new object:
```
var models = require("../api/models");
models.sequelize.sync({force: true}).then(function () {
  models.User.create({
    username: "MiguelCrespo"
  }).then(function() {
    console.log("THEN");
  });
});

```
I get this error:
![screenshot from 2015-06-12 01 19 45](https://cloud.githubusercontent.com/assets/5839623/8124450/2ad7b44c-10a1-11e5-83ac-24fb1562c128.png)

I appreciate your help.

**Comment by janmeier** [comment]
Sounds very weird - something from within sequelize seems to not be returning a promise properly.

However, this is an extremely basic sequelize pattern, so we would know if something was generally wrong with sync + create :)

Can you try to reinstall sequelize, and see that all dependencies (especially bluebird) are installed correctly?

**Comment by miguelcrespo** [comment]
Hi I tried reinstalling sequelize but I still getting the same error, but I noticed that this error is only when I try to save or create a new object in the database (Following the error stream with the method create  thrown the error when that method inside call save method). 

But I can use the method find or findAll and it work fine, I was searching for the line of the error and 
Hi I tried reinstalling sequelize but I still getting the same error, but I noticed that this error is only when I try to save or create a new object in the database (Following the error stream with the method create  raise the error when that method inside call save method). but I can use the method find or findAll and it work fine. 

Thank you for read this issue...

**Comment by janmeier** [comment]
@miguelcrespo there's something weird with your post, the text seems duplicated :)

I don't really have much to go from here since I can't recreate the issue. If you can create a pull request with a failing test that would be great. Otherwise, try to debug in lib/hooks.js and see if you can figure out where the promise disappears

**Comment by janmeier** [comment]
Which version are you using btw?

**Comment by miguelcrespo** [comment]
I am using the version 3.2.0.

Ok I am going to keep watching... Thanks

**Comment by janmeier** [comment]
Closing, no response
