### ISSUE TITLE
[feature] Small dictionary tables represents as enum.

### ISSUE THREAD

**Issue by Smyak** [sequelize/sequelize#3927]
Usually most people don't want to create small dictionary tables to avoid extra coding. As result most databases not in Third-normal form.
How it looks now:
    sequelize.define('Job', {
        name: {type: Sequelize.STRING},
        status:  {type: Sequelize.STRING} // status just string ('Done', 'Progress', 'Fail')
    })

How i see it:
    var Job = sequelize.define('Job', { name: {type: Sequelize.STRING}  })
    var Status =  sequelize.define('Status', {  name: {type: Sequelize.STRING} }).AsEnum();
Job.hasMany(Status);
// Suppose that table 'Status' contains 3 records:
// [{id: 1, name:'Done'}, {id: 2, name:'Progress'}, {id: 3, name:'Fail'}]
// tables 'marked' as AsEnum should be fully loaded on sequelize.sync
var done = Status.Done; // undefined
sequelize.sync().then(function()
{
    done = Status.Done; // some object {id: 1, name: "Done"} or function or something else
    Status.Done = 123; // important: will not change
    Job.create({name:"newJob1", StatusId: Status.Done});
    Job.create({name:"newJob2", StatusId: Status.Progress});
}
It just idea, what do you think about it?

**Comment by janmeier** [comment]
I don't see any benifit of this, over using the [enum datatype](http://docs.sequelizejs.com/en/latest/api/datatypes/#enum)

**Comment by Smyak** [comment]
Thanks, i didn't know about "enum datatype"
