### ISSUE TITLE
[MSSQL] Performing a raw query with model specified doesn't appear to be creating proper model instances

### ISSUE THREAD

**Issue by zeiphon** [sequelize/sequelize#3930]
I have a Product model defined as follows, such that all fields are aliased to the capitalised version present in the database:

``` javascript
this.Product = this.sequelize.define('Product', {
            id: {
                type: Sequelize.INTEGER,
                field: 'Id',
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: Sequelize.STRING,
                field: 'Name'
            },
            //...
        });

// Possibly irrelevant but included for completeness
this.Product.belongsTo(this.Store, { foreignKey: 'StoreId' });
this.Product.hasMany(this.ProductPrice, { foreignKey: 'ProductId' });
```

I am then attempting to retrieve a number of Product instances by using a custom query like so:

``` javascript
        this.sequelize
            .query('SELECT * from dbo.Product WHERE [...]', { model: this.Product, type: 'SELECT' })
            .then(function(products) {
                  //...
              });
```

I was expecting the `products` parameter of the `.then()` promise result to be an array of `Product` instances, and it appears to be, but without the proper fields mapped.
For example, the elements in the `products` return result do not contain a `.name` or even a `.Name` field, though they do have a `.dataValues.Name` field, which means that the instances couldn't have been created properly.

I have attempted to dig through some of the code, but finding the section that handled field mappings eludes me. Is this incorrect behaviour, or am I making a mistake with the `.query()` call?

**Comment by janmeier** [comment]
Definitely sounds like a bug - @mickhansen will probably be the best to answer where we map dataValues to getters - I can't remember :)

There's something else weird as well: 
```js
console.log(res[0].get('name')) // returns undefined
console.log(res[0].get('Name')) // returns the name
```
`get` works for the field name, but not the attribute name

**Comment by mickhansen** [comment]
Sequelize expects the mapping to happen in the SQL query, we don't currently do reverse field to attribute mapping on selects, although there's a different open issue about exactly that.
