### ISSUE TITLE
Document that findOrCreate needs a unique index when there are several concurrent calls

### ISSUE THREAD

**Issue by phanect** [sequelize/sequelize#3931]
I wrote following code:

``` javascript
var User = this.sequelize.define('User', {
  email: {
    type: DataTypes.STRING
  }
});

return Promise.all([
  User.findOrCreate({
    where: { email: 'email@sequelizejs.com' }
  }),
  User.findOrCreate({
    where: { email: 'email@sequelizejs.com' }
  }),
  User.findOrCreate({
    where: { email: 'email@sequelizejs.com' }
  })
])
```

In above code, 3 `findOrCreate` with the same search terms runs asynchronously.
I expected only 1 `User` is created, but actually 3 `User`s are created.

According to the log, SQL seems running with following order:

```
SELECT `email` FROM `User` AS `User` WHERE (`User`.`email` = 'email@sequelizejs.com', ...) LIMIT 1;
# Empty Set
SELECT `email` FROM `User` AS `User` WHERE (`User`.`email` = 'email@sequelizejs.com', ...) LIMIT 1;
# Empty Set
SELECT `email` FROM `User` AS `User` WHERE (`User`.`email` = 'email@sequelizejs.com', ...) LIMIT 1;
# Empty Set
INSERT INTO `User` (`email`, ...) VALUES ('email@sequelizejs.com', ...);
INSERT INTO `User` (`email`, ...) VALUES ('email@sequelizejs.com', ...);
INSERT INTO `User` (`email`, ...) VALUES ('email@sequelizejs.com', ...);
```

(Above log is written manually based on the log of another example)
So `findOrCreate` seems to allow another query during the time between `find` and `create`.

Expected SQL order is:

```
SELECT `email` FROM `User` AS `User` WHERE (`User`.`email` = 'email@sequelizejs.com', ...) LIMIT 1;
# Empty Set
INSERT INTO `User` (`email`, ...) VALUES ('email@sequelizejs.com', ...);
SELECT `email` FROM `User` AS `User` WHERE (`User`.`email` = 'email@sequelizejs.com', ...) LIMIT 1;
# User record returned; No INSERT run
SELECT `email` FROM `User` AS `User` WHERE (`User`.`email` = 'email@sequelizejs.com', ...) LIMIT 1;
# User record returned; No INSERT run
```

**Comment by phanect** [comment]
Above Pull Request #3932 is reproduction test case for this bug.

**Comment by janmeier** [comment]
Adding unique: true to the email field will fix the issue. Tagging this as a documentation issue, findOrCreate can only handle concurrent duplicates when there is a unique index

**Comment by phanect** [comment]
Well, in my use case, I don't want to (cannot?) add `unique`. It is appreciated if `findOrCreate` works asynchronously.

[I tried to implement it using table lock](https://github.com/phanect/sequelize/commit/f8ed79c70b262d0eea8c63986ff8c11436bb17ed), but currently affecting another test case.

**Comment by phanect** [comment]
cf. my use case:
I'm developing order CSV import function for a kind of CRM.
I tried `CallOperator.findOrCreate({ where: { name: csv.operatorName } })` to automatically create associated `CallOperator` who processed the order.
There may be existing `CallOperator` who belongs to another company with the same `name`. The users may want to register another `CallOperator`s with the same name as existing one.

BTW this time I rewrote the structure of the function so that each `findOrCreate`s run synchronously using [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

**Comment by janmeier** [comment]
Locking the table completely just to do a findOrCreate is _not_ a good general solution since it will severly hurt concurrency.

**Comment by phanect** [comment]
Year, table lock is not good idea. I'm starting to give up... :(

**Comment by janmeier** [comment]
What about a composite index of `name, companyName / companyId?

**Comment by phanect** [comment]
Thanks. I will check about composite index.
