### ISSUE TITLE
Attributes query option doesn't take join table into account.

### ISSUE THREAD

**Issue by juanjoLenero** [sequelize/sequelize#3938]
I'm trying to select some attributes on my instances before parsing them into JSON and sending them back to the client. I have a many-to-many relation and I would like to send responses to the clients without the join table.

Here's an example:
```javascript
// MODELS
    var Group = sequelize.define('Group', {
        name: sequelize.Sequelize.STRING
    });

    var Person = sequelize.define('Person', {
        name: sequelize.Sequelize.STRING
    });

    var GroupPerson = sequelize.define('GroupPerson', {
        status: sequelize.Sequelize.STRING
    });

// RELATIONS
    Group.belongsToMany(Person, {through: GroupPerson, as: 'Persons'});
    Person.belongsToMany(Group, {through: GroupPerson, as: 'Groups'});

// EXAMPLE
    Person
        .findAll({
            include: [{
                model: Group,
                as: 'Groups',
                through:{
                    where: {status: 'done'}
                }
                attributes: ['id']
            }]
        });
```
What I'm trying to achieve: 
``` 
[{id: 1}, {id: 2}]
```
What I'm getting right now: 
```
[{id: 1, GroupUser: [Object]}, {id:2, GroupUser: [Object]}]
```
Is there a built-in way to exclude the join table object from the response?

**Comment by mickhansen** [comment]
You can use `through: {attributes: []}` to leave out the join table.

**Comment by kant-bluescape** [comment]
is there a way to exclude just one column from the join table such as say "password" column else I will have a very long list of attributed to include just to exclude this one column.
