### ISSUE TITLE
Model.findOne(): Where clause on unique non-PK column does not return all associated instances

### ISSUE THREAD

**Issue by bomattin** [sequelize/sequelize#3944]
Sequelize Version: 3.2.0
DB Dialect: MySQL

I have a `user` model which has an n:m relationship with `apikey`.
### User.js
```javascript
        id: {
            type: DataTypes.INTEGER,
            field: 'emplid',
            primaryKey: true,
            autoIncrement: false
        },
        firstname: {
            type: DataTypes.STRING,
            field: 'firstname_preferred',
            defaultValue: '',
            allowNull: false
        },
        username: {
            type: DataTypes.STRING,
            field: 'middlename_preferred',
            defaultValue: '',
            allowNull: false,
            unique: true
        } ...
}, {
        
        classMethods: {
            associate: function(models) {
                user.belongsToMany(models.Apikey, {
                    foreignKey: "emplid",
                    through: 'user_keys',
                    onDelete: 'cascade'
                });
            }
        }

```
### Apikey.js
```javascript
      id: {
          type: DataTypes.INTEGER,
          field: 'id',
          primaryKey: true,
          autoIncrement: true
      },
      permissionString: {
          type: DataTypes.STRING,
          field: 'permission_string'
      },
  }, {
      classMethods: {
          associate: function(models) {
              Apikey.belongsToMany(models.User, {
                  foreignKey: 'id',
                  onDelete: 'cascade',
                  through: 'user_keys'
              });
          }
      }
```

If I call `findOne()` with the primary key:
```javascript
User.findOne({
    where: {id: req.user.id},
    include: [{model: Apikey}]
})
```
I get the expected behavior: One User with all of their associated API keys. 

However, if I call `findOne()` with something other than the PK:
```javascript
User.findOne({
    where: {username: req.user.username},
    include: [{model: Apikey}]
})
```
I get one User with an array of API Keys that's forced to length 1, where only the first key is returned. Worse still, if I call `findAll()` on something other than the PK:

```javascript
User.findAll({
    where: {username: req.user.username},
    include: [{model: Apikey}]
})
```

I get the expected results: An array of all matching Users, containing all of their associated API Keys.

Is this intended behavior?

I understand that when using `findOne()` with the PK, Sequelize omits the `LIMIT 1` clause, as it should because PKs are unique. However, when `WHERE`ing with a unique, but non-PK field, Sequelize *keeps* the `LIMIT 1` clause, which prevents multiple rows from returning, which of course prevents all associations from being returned.

### Suggestions:

* modify `lib/model.js` line [1264](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1264) to allow checking for unique constraints as well as PK constraints.

**Comment by janmeier** [comment]
Hmm, I guess the best here would actually be to do a `select where pk in (select where [provided where clause] limit 1)` whenever there is a where clause. That would also support `findOne` on an attribute that is not unique, but where you still want a single row

**Comment by bomattin** [comment]
I like that solution even better. 

I'm running into a weird scenario where I can replicate this on one of my servers but not the other.They all appear to be using Sequelize 3.2.0 and a similar database. Going to do some more digging.

**Comment by janmeier** [comment]
We already have some code for `SELECT WHERE IN (SUBQUERY)` which we might be able to reuse, right @mickhansen ?

**Comment by mickhansen** [comment]
We used that technique for delete's, but didn't work that well.

**Comment by bomattin** [comment]
Scratch it, I found the problem.

In `/lib/dialects/abstract/query-generator.js`, line 854, a fellow developer had modified the conditional from:

```javascript
, subQuery = options.subQuery === undefined ?
                     limit && options.hasMultiAssociation :
                     options.subQuery
```

to

```javascript
, subQuery = options.subQuery === false ?
                     limit && options.hasMultiAssociation :
                     options.subQuery
```

We probably had a legitimate use for it, but I reverted it and I don't believe anything's broken. Yet. I THINK we'd experimented with it because we had something similar to #3718. According to my coworker's comments:

```javascript
 /**
         * The original sequelize code only allowed the 'limit' parameter in the outer scope, thus preventing it
         * from limiting on the final subquery or final filtered set based on included data.
         * For example: Before the change this code would limit on all users,
         * but now the limit affects the complete filtered data where the users have an expertise and the name != null.
         * Below is the path to the js file with the change.
         * On line 854, change 'undefined' to 'false' like so: subQuery = options.subQuery === false ?
         * PATH: ~/api-directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js
         */
```

**Comment by bomattin** [comment]
The tradeoff isn't pretty. Removing this removes my ability to filter on includes. That means if I want to find only Users who have an API Key where `authorized = TRUE`, AND I want to `LIMIT 10`, I can't return all associations on a findOne().

**Comment by mickhansen** [comment]
@bomattin you should still be able to filter and return all associations, it should be doing a subquery.

**Comment by bomattin** [comment]
@mickhansen Unfortunately, that's not the case. With `subQuery = options.subQuery === undefined ?` and a query like so:

```javascript
models.apikey.findOne({
                include: [{model: models.user, where: {id: req.body.emplid}}]
            })
```

I get an `ER_BAD_FIELD_ERROR: Unknown column user.id in on clause.`

Compare this to setting the comparison to `false`, which results in a successful query.

Failed SQL:
```sql
SELECT 
    `apikey`.*,
    `users`.`emplid` AS `users.id`,
    `users`.`firstname_preferred` AS `users.firstname`,
    `users`.`middlename_preferred` AS `users.middlename`,
    `users`.`lastname_preferred` AS `users.lastname`,
    `users`.`firstname_legal` AS `users.legalFirstname`,
    `users`.`middlename_legal` AS `users.legalMiddlename`,
    `users`.`lastname_legal` AS `users.legalLastname`,
    `users`.`username` AS `users.username`,
    `users`.`email` AS `users.email`,
    `users`.`phone` AS `users.phone`,
    `users`.`location` AS `users.location`,
    `users`.`photo_url` AS `users.photo`,
    `users.user_keys`.`emplid` AS `users.user_keys.emplid`,
    `users.user_keys`.`id` AS `users.user_keys.id`
FROM
    (SELECT 
        `apikey`.`id`,
            `apikey`.`jti`,
            `apikey`.`key_string` AS `keyString`,
            `apikey`.`permission_string` AS `permissionString`,
            `apikey`.`authorized`
    FROM
        `apikeys` AS `apikey`
    WHERE
        (SELECT 
                `user_keys`.`emplid`
            FROM
                `user_keys` AS `user_keys`
            INNER JOIN `users` AS `user` ON `user_keys`.`emplid` = `user`.`id`
            WHERE
                (`apikey`.`id` = `user_keys`.`id`)
            LIMIT 1) IS NOT NULL
    LIMIT 1) AS `apikey`
        INNER JOIN
    (`user_keys` AS `users.user_keys`
    INNER JOIN `users` AS `users` ON `users`.`emplid` = `users.user_keys`.`emplid`) ON `apikey`.`id` = `users.user_keys`.`id`
        AND `users`.`emplid` = 'XXX';
```

Successful SQL:

```sql
SELECT 
    `apikey`.`id`,
    `apikey`.`jti`,
    `apikey`.`key_string` AS `keyString`,
    `apikey`.`permission_string` AS `permissionString`,
    `apikey`.`authorized`,
    `users`.`emplid` AS `users.id`,
    `users`.`firstname_preferred` AS `users.firstname`,
    `users`.`middlename_preferred` AS `users.middlename`,
    `users`.`lastname_preferred` AS `users.lastname`,
    `users`.`firstname_legal` AS `users.legalFirstname`,
    `users`.`middlename_legal` AS `users.legalMiddlename`,
    `users`.`lastname_legal` AS `users.legalLastname`,
    `users`.`username` AS `users.username`,
    `users`.`email` AS `users.email`,
    `users`.`phone` AS `users.phone`,
    `users`.`location` AS `users.location`,
    `users`.`photo_url` AS `users.photo`,
    `users.user_keys`.`emplid` AS `users.user_keys.emplid`,
    `users.user_keys`.`id` AS `users.user_keys.id`
FROM
    `apikeys` AS `apikey`
        INNER JOIN
    (`user_keys` AS `users.user_keys`
    INNER JOIN `users` AS `users` ON `users`.`emplid` = `users.user_keys`.`emplid`) ON `apikey`.`id` = `users.user_keys`.`id`
        AND `users`.`emplid` = 'XXX'
LIMIT 1;
```

**Comment by bomattin** [comment]
Closing this. Adding `subquery: true` appears to fix the problem of limits. I was using an earlier sequelize version (My servers were on 3.2.0, my workstation was 2.1.3)

**Comment by Krajiyah** [comment]
I am still having this bug with v4.37.10. When I use: `Model.findOne({where: {name: 'someName'})` does not include the field name in the WHERE clause of the sql command. The only fields that seem to work are primary keys.

**Comment by jpwiddy** [comment]
I am having the above issue as well, still.
```
"sequelize": "5.21.5",
```
