### ISSUE TITLE
findAll including children of a hasMany relationship doesn't return rows

### ISSUE THREAD

**Issue by dmfay** [sequelize/sequelize#3948]
I'm using PostgreSQL 9.4.1, nodejs 0.10.33, pg~4.4.0, pg-hstore~2.3.2, and sequelize~3.2.0.

Here's the code:

``` javascript
'use strict';

var Sequelize = require('sequelize');

var sequelize = new Sequelize('test', 'username', 'password', {host: '127.0.0.1', dialect: 'postgres', 'quoteIdentifiers': false});

var Team = sequelize.define('Team', {
    name: Sequelize.STRING
});

var Person = sequelize.define('Person', {
    name: Sequelize.STRING
});

Team.hasMany(Person);

sequelize.sync({force: true}).then(function() {
    return Team.create({
        name: 'a team'
    }).then(function (team) {
        Person.create({
            name: 'jane doe',
            'TeamId': team.id       // with underscored: 'team_id'; without: 'TeamId' (case sensitive)
        }).then(function() {
            Team.findAll({
                where: {name: 'a team'},
                include: [Person]
            }).then(function (teams) {
                console.log('retrieved ' + teams.length + ' row(s)');
            }).error(function (err) {
                console.log(err);
            });
        });
    });
});
```

Pretty straightforward: a team has many people, we create one team and one member, then go to retrieve all teams along with their members, expecting one result. There's nothing out of the ordinary in the table creation or the insertion, but -- _unless_ Team has the underscored option turned on -- this findAll returns no results whatsoever. The data verifiably exists and the generated query is perfectly valid and returns the expected row if run manually in the psql console, but nothing comes out of the findAll in Sequelize.

It's also possible to break the query even if Team has underscored on: just add a mixed-case column to Team, it doesn't matter if it has a lowercase backing field defined or not. It's weird enough that I had to resort to a truth table to work out the conditions in which it would and wouldn't return (I named my extra column 'thing'):

| underscored? | has 'thing'? | has 'thinG'? | retrieves team+jane? |
| --- | --- | --- | --- |
| y | y | n | y |
| y | n | y | n |
| n | y | n | n |
| n | n | y | n |

**Comment by mickhansen** [comment]
Does it work if yhou remove `quoteIdentifiers: false`?

**Comment by dmfay** [comment]
Yes, it works with all combinations of underscored & extra fields. I'd really prefer not to have to deal with the case sensitivity though.

**Comment by mickhansen** [comment]
Unfortuneatly `quoteIdentifiers: false` does not have full support in Sequelize.

**Comment by dmfay** [comment]
How much *is* it supported? Obviously this is kind of the case in point, but assuming I stick with quoteIdentifiers:false what else could I be looking at running into, or is that not known?

It'd have been nice to have seen a note to this effect in the documentation too -- there is nothing at all in http://docs.sequelizejs.com/en/latest/api/sequelize/#new-sequelizedatabase-usernamenull-passwordnull-options that even hints that the quoteIdentifiers flag is in any way experimental or not fully supported.
