### ISSUE TITLE
PostgreSQL: 'operator does not exist: text = text[]' findOrCreate on JSON data type

### ISSUE THREAD

**Issue by blakmatrix** [sequelize/sequelize#3949]
Hi,

I ran into an issue of Sequelize:postgres erring with `SequelizeDatabaseError: operator does not exist: text = text[]`

code is:
```js
var query = {"search": {"country": ["Africa", "Palestine Territories"], "languages": "English"}}
Searches.findOrCreate({where: query})
```
the query called was of this format:
```sql
SELECT "search_id", "search", "notes", "created_at", "updated_at" 
FROM "searches" AS "Searches" 
WHERE (("Searches"."search"#>>'{country}') = ARRAY['Africa','Palestine Territories'] 
AND ("Searches"."search"#>>'{languages}') = 'English') LIMIT 1;
```

**Comment by janmeier** [comment]
This is the desired behaviour :). We know nothing about the structure of the json in the column, so we asume that country is an array. 

To do an in query you can use `$in`:

```js
where: {
  search: {
    country: { $in: ["Africa", "Palestine Territories"] },
    languages: "English"
  }
}
```
```sql
WHERE (("Searches"."search"#>>'{country}') IN ('Africa', 'Palestine Territories') AND ("Searches"."search"#>>'{languages}') = 'English');

```

**Comment by blakmatrix** [comment]
@janmeier Ah, makes sense, I wouldn't say it's desired from my perspective, but I understand. (For `upsert` there is an apparent assumption though--key/value pairs work quite well, just not when the value is a json array of strings or numbers) I was hopping there was an easy way to convert `{'Africa','Palestine Territories'}` to `['Africa','Palestine Territories']` as that is what postgres seemed to want in this instance. 

Are there any plans to be able to define the structure of a JSON column in Sequelize? That'd be super useful for methods like `upsert` and `findOrCreate` and validations using sequelize.

**Comment by mickhansen** [comment]
@blakmatrix There has been some talks about providing a subschema for json columns yes, no work yet.

**Comment by janmeier** [comment]
Put even if you define a schema, I doubt we would use that schema to make guesses about how to interpret the query.

I understand the sentiment here, but I'd say that for this case you will have to pass the array both to where and to defaults
