### ISSUE TITLE
Need "SET NAMES utf8"

### ISSUE THREAD

**Issue by phplego** [sequelize/sequelize#395]
I use mysql and I need execute "SET NAMES utf8" after connection. How can I do that?

**Comment by treejanitor** [comment]
Gotta note that I wish this were documented a little better.  It's pretty common to need to insert Twitter emoji characters into a MySQL db, and it took me a while to discover this twist.  Ended up being easier to actually trace it through the code.  Anyhoo...  I'd bet the charset option is commonly troublesome.

**Comment by janmeier** [comment]
@treejanitor - Docs PRs always welcome :)

**Comment by jontelm** [comment]
What was the solution to this problem?

**Comment by sushantdhiman** [comment]
[this comment](https://github.com/sequelize/sequelize/issues/395#issuecomment-29132224)

**Comment by jontelm** [comment]
@sushantdhiman Thanks, I don't see the query get executed but "SET NAMES utf8;", but it's maybe the same as setting setting the charset.

**Comment by sushantdhiman** [comment]
You can use `afterConnect` hook on sequelize, so after each connection is connected you can call `SET NAMES utf8`


```js
sequelize.afterConnect(connection => {
   return Promise.fromCallback(callback => connection.query('SET NAMES UTF8', callback);
});
```
