### ISSUE TITLE
You attempted to save an instance with no primary key, this is not allowed since it would result in a global update

### ISSUE THREAD

**Issue by mohammad-rahchamani** [sequelize/sequelize#3953]
Hi
I'm trying to update an instance, but I'm getting this error : 

"You attempted to save an instance with no primary key, this is not allowed since it would result in a global update"

here is my code : 

```javascript
return new promise(function (fullfill, reject) {
                            User.findOne({
                                where: {
                                    id: userId
                                },
                                attributes: ['status']
                            }).then(function (user) {
                                console.log("user.status", user.status);
                                if (user.status === 'Inactive') {
                                    user.updateAttributes({status: 'Active'}, {fields:['status']})
                                        .then(function (result) {
                                            fullfill(result);
                                        }).catch(function (error) {
                                            reject(error);
                                        });
                                } else if (user.status === 'Deactivated') {
                                    reject(new error.DeactivatedUserError());
                                } else {
                                    fullfill(user);
                                }
                            }).catch(function (error) {
                                reject(error);
                            });
```
I appreciate your helps.

**Comment by janmeier** [comment]
We need to be able to actually reproduce the problem - we can't with the code you've given, since we're missing the model definition :). 

The error is throw if the primary key is undefined - have you tried logging `user.id`?

You don't need to wrap sequelize actions in a promise, sequelize already returns a promise. Meaning you can just return the `User.findOne` chain

**Comment by mohammad-rahchamani** [comment]
thank you for your reply.

my problem solved by adding id too attributes of findOne function.

```javascript
...
User.findOne({
                                where: {
                                    id: userId
                                },
                                attributes: ['id', 'status']
...
```

I'm wrapping action in a promise for throwing custom errors.
for example when user is deactivated, throwing an error.

could I do this using scopes? is there any functionality for this?

I have an issue when trying to throw my own error. 
do you have any example for custom errors?
I read the bluebird API and my case is very similar to bluebird examples. but I'm getting "Unhandled rejection DeactivatedUserError" where "DeactivatedUserError" is my custom error and there is a catch function with DeactivatedUserError type and there is another catch function without specific error type.

**Comment by janmeier** [comment]
You should be able to simply throw your error in the then function, and it will be handled further up in the chain. But that is more a promise than a sequelize question

**Comment by mohammad-rahchamani** [comment]
you are right.
thanks for your time again :+1:
