### ISSUE TITLE
Simplify query join results across multiple models

### ISSUE THREAD

**Issue by jonathanwoahn** [sequelize/sequelize#3954]
I'm performing a join query across four different models, and I'm wondering if there is a built in function I'm not aware of that can take a result that looks like this...

```
{
    "id": 1,
    "Department": {
        "id": 1,
        "department_name": "Print/Pack",
        "DepartmentType": {
            "id": 1,
            "product": "OEE"
        }
    },
    "Tenant": {
        "id": 1,
        "tenant_name": "Client Name"
    },
    "PermissionType": {
        "id": 2,
        "permission_type_name": "Manager"
    }
}
 
```
...instead NOT put the object into sub-objects classified by their respective models, and instead look something like this: 

```
{
    "id" :1,
    "department_id": 1,
    "department_name": "Print/Pack",
    "department_type_id": 1,
    "department_type_product": "OEE",
    "tenant_id": 1,
    "tenant_tenant_name": "Client Name",
    "permission_type_id": 2,
    "permission_type_permission_type_name": "Manager"
}
```
I know I could process the results myself and build this pretty simply, but I'd prefer to not have to do this if there is a function already built in to handle flattening the results to something a little more manageable.

Thanks for your help!

**Comment by janmeier** [comment]
There's nothing like that built into sequelize, but you could probably use [`dottie.flatten`](https://github.com/mickhansen/dottie.js/blob/master/test/flatten.test.js)
