### ISSUE TITLE
Postgres Notify

### ISSUE THREAD

**Issue by andrewthornton** [sequelize/sequelize#3956]
I am struggling to find how I might be able to leverage Postgres's [NOTIFY/LISTEN feature](http://www.postgresql.org/docs/9.0/static/sql-notify.html) via sequelize. I know it is [possible](https://github.com/brianc/node-postgres/blob/eb894900ed2ffe317632c7a1fc7217773a660f8c/test/integration/connection/notification-tests.js) using the pg library via the client. I am just struggling trying to find a way to get access to this directly from sequelize.

**Comment by janmeier** [comment]
I'm not sure you could implement this in sequelize in a good way. When you listen you have to keep the same connection open, while sequelize keeps a connection pool, destroying and creating connections as needed.

I'm not sure you could get those two approaches to play well together.

Your best bet would be to use the pg library directly for this I think. If you want, you could use the sequelize connection manager to create a connection for you https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L23

**Comment by andrewthornton** [comment]
OK, thanks. I am using pg directly now. I will just stick with that approach. Thanks!

**Comment by IanGrainger** [comment]
No support for function definition via sequelize, then, to define the trigger? Like how we can define tables? Just out of interest...

**Comment by farzd** [comment]
@andrewthornton can you share your approach please ? Are you not using sequilize to manage your connection then ?

**Comment by jberall** [comment]
I used the https://github.com/voxpelli/node-pg-pubsub
Easy as pie.
const PGPubsub = require('pg-pubsub');

const connectionString = `postgresql://${SeqConfig.username}a:${SeqConfig.password}@${SeqConfig.host}/${SeqConfig.database}`;
const pubsubInstance = new PGPubsub(connectionString);
 The connection only gets triggered on the .addChannel

pubsubInstance.addChannel('testnotify',(payload) => console.log(payload));

Hope this helps.

**Comment by jedwards1211** [comment]
@andrewthornton it's worth noting that `NOTIFY` can be performed perfectly well via `sequelize.query`, and is particularly useful when passing a sequelize transaction, so that you can ensure that the notification is only sent if the transaction commits.

**Comment by tolulope-od** [comment]
@jedwards1211 can you please help with some docs or a little example? Thanks!
