### ISSUE TITLE
before/after upsert hook

### ISSUE THREAD

**Issue by juanjoLenero** [sequelize/sequelize#3965]
I'm using PostgreSQL and noticed that the Update/Create hooks are not being triggered by model upserts.

```javascript
// Example
    var User = sequelize.define('User', {
        name: sequelize.Sequelize.STRING
    });

   User.hook('beforeCreate', function (user, options) {
        console.log('In beforeCreate hook.');
        return Promise.resolve(user);
    });

   User.hook('beforeUpdate', function (user, options) {
        console.log('In beforeUpdate hook.');
        return Promise.resolve(user);
    });

   User.hook('afterCreate', function (user, options) {
        console.log('In afterCreate hook.');
        return Promise.resolve(user);
    });

   User.hook('afterUpdate', function (user, options) {
        console.log('In afterUpdate hook.');
        return Promise.resolve(user);
    });

    User
        .upsert({name: 'Pedro'}) // Insert
        .then(function (created) {
            console.log(created); // true
            return User.upsert({id: 1, name: 'Pablo'}); // Update
        })
        .then(function (created) {
            console.log(created); // false
        });
```
None of the hooks are called. Is there a way around this? This is under sequelize v2.1.3.

SQL for the upsert:
```
// Insert upsert.
Executing (default): CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $$ BEGIN INSERT INTO "Users" ("createdAt","updatedAt") VALUES ('2015-06-18 19:14:13.247 +00:00','2015-06-18 19:14:13.247 +00:00'); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE "Users" SET "updatedAt"='2015-06-18 19:14:13.247 +00:00'; RETURN 2; END; $$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();

// Update upsert.
Executing (default): CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $$ BEGIN INSERT INTO "Users" ("id","createdAt","updatedAt") VALUES (1,'2015-06-18 19:14:13.254 +00:00','2015-06-18 19:14:13.254 +00:00'); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE "Users" SET "id"=1,"updatedAt"='2015-06-18 19:14:13.254 +00:00' WHERE ("id" = 1); RETURN 2; END; $$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
```

**Comment by janmeier** [comment]
There is no way to know before running the query whether it is going to be an insert or an update, so we can't really run a beforeHook. And I don't think it makes sense to run afterHooks, if we haven't run beforeHooks :)

Of course we could do a query first to check if the row exists, but that would require creating a transaction, and make the code more complicated - I quite like the simplicity of it now.

Would a before/after upsert hook work for you? 

We should probably also be more explicit in the docs that create and update hooks aren't run for upserts

**Comment by juanjoLenero** [comment]
Yes, in my specific use case an upsert hook would work.

I have some functions that I need to run whether a model is created or updated, so I already have: 

`Model.hook('afterCreate', myFunction);`
 
`Model.hook('afterUpdate', myFunction);`

But for certain use cases I need to do an `upsert` which means that neither of the above runs, so an `afterUpsert` hook would be neat.

**Comment by shriramshankar** [comment]
Noticed that update and create hooks do not run on upserts. Any plans to introduce after/ before update hooks ?

**Comment by ekristen** [comment]
+1

**Comment by emaniacs** [comment]
I got the same issue about this.
+1

**Comment by ral8** [comment]
+1

**Comment by ippeiukai** [comment]
I know It's late, but shouldn't before/after save be triggered by upsert as well? Kinda unintuitive when a hook for create and update doesn't get triggered by the operation that does either update or insert.

**Comment by ctheller** [comment]
+1

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by thom-nic** [comment]
I just got bit by this - it would be great if documentation for `upsert()` explicitly calls out that hooks do not get run in big bold text.  

In my case, I was upserting a user and did not realize my `beforeCreate` / `beforeUpdate` hooks did not run to hash the password.  As a result, it stored the password in plaintext, and all password validation attempts failed!  

I care more about the docs than the feature even, if I know hooks do not run I can do a `findOrCreate()` at least to work around it..

**Comment by bminer** [comment]
I have been bitten by the snake also.  As @ippeiukai mentioned, at the very least "beforeSave" and "afterSave" triggers should be called by `upsert` calls.  The current behavior is most unexpected, yet this should be an easy issue to fix.

I'd vote for before/after save to "proxy" before/after upsert.  Any thoughts for/against this approach?

**Comment by theRichu** [comment]
I think when use individualHooks: true option at least.

Should be triggered before/after insert/update hook.
I agree current behavior is very unexpected.

**Comment by Gaabe** [comment]
Any updates on this? Got hit hard by a "bug" today, only to realize that the upserts weren't calling the insert and update hooks, this should at least be documented in the function.

**Comment by ethoman** [comment]
Please fix this!

**Comment by clarencedesmarais** [comment]
Any updates on this ?

**Comment by ephys** [comment]
The beforeSave / afterSave part is tracked over https://github.com/sequelize/sequelize/issues/12466
