### ISSUE TITLE
Use of .toJSON() not well documented 

### ISSUE THREAD

**Issue by Murphydbuffalo** [sequelize/sequelize#3966]
Hi,

I ran into an issue in my application that was resolved by use of `.toJSON()`, and which made me think the documentation on that method should be included in the 'Instances' section under 'Documentation', not solely under 'API'.

If you find that it should in fact be included under 'Documentation' I'd be happy to write something up for it :). 

I have `journey` model that `hasMany` processes, and I call `journey.removeProcess(someProcess)` at one point in my application. This deletes the process but if I refer to `journey.processes` it still includes the deleted process. 

So, I wrote an instance method on `Journey` to filter out the deleted process from `journey.processes`, which allows me to return the journey and its updated list of processes without making another call to the database.

```javascript
    instanceMethods: {
      filterDeletedProcess: function(deletedProcess, callback) {
        const journey = this.toJSON();
        const processes = this.processes;

        _.remove(this.processes, (process) => {
          return Number(process.id) === Number(deletedProcess.id);
        });

        journey.processes = processes;

        return callback(journey);
      }
    }
```
Please stop me right there if there is a better way to do that by the way...

The method works fine when I convert the instance of `Journey` to JSON first, and then update `journey` with `journey.processes = processes;`. 

But the way I initially tried to write the method (shown below) doesn't make use of `.toJSON()` because I wasn't aware that it's a bad idea to work with raw Sequelize objects like in the `this.processes = processes` line.

Original attempt:

```javascript
instanceMethods: {
      filterDeletedProcess: function(deletedProcess, callback) {
        const processes = JSON.parse(JSON.stringify(this.processes));

        _.remove(processes, (process) => {
          return Number(process.id) === Number(deletedProcess.id);
        });

        this.processes = processes;

        return callback(this);
      }
    }
```

That resulted in `this.processes` being set correctly (with the deleted process filtered out) initially, *until* I called `res.send(journey)`, which reverted to the original set of processes (which included the deleted process). When `res.send()` converts the instance of `Journey` to JSON does it somehow restore an old version of `journey.processes` from `_previousDataValues`? Is that the desired behavior?  

Thanks in advance, I love the library... thanks for creating such a great resource!

**Comment by janmeier** [comment]
I agree, that toJSON should definitely be mentioned in the regular documentation - PR very welcome.

However, your particular use to toJSON here looks a bit ... weird, to me :). I would recommend against JSON stringifying / parsing anything right up until the point where you are going to send the data to the client, because you loose all the fancy sequelize stuff.


The reason you are still seeing the process entries even though you have removed them from `journey.processes` is that they are saved in `dataValues`. You should call `set` with the updated array:

```js
filterDeletedProcess: function(deletedProcess, callback) {
    const processes = this.processes;
    
    _.remove(this.processes, (process) => {
      return Number(process.id) === Number(deletedProcess.id);
    });

    journey.set('processes', processes)
}
```

You might need to pass a `{ raw: true }` as options parameter

On a broader scale, we have talked about automatically removing eager loaded entries when you call `removeX`, but I can't find the issue right now

**Comment by mickhansen** [comment]
`toJSON` calls `get({plain: true})` internally.

**Comment by Murphydbuffalo** [comment]
Thank you for the help with using `set`!  I'll try to submit a PR this weekend.

**Comment by janmeier** [comment]
@Murphydbuffalo cool - I'll close this issue then :)
