### ISSUE TITLE
MSSQL ENUM VARCHAR(10) default too short

### ISSUE THREAD

**Issue by cdmcnamara** [sequelize/sequelize#3967]
I'm seeing the following error when attempting to persist a record:
`SequelizeDatabaseError: String or binary data would be truncated.`

Upon investigating it would appear as this is related to a column with DataType.ENUM and the translation sync() is making when it actually creates the table:

```
IF OBJECT_ID('[transactions]', 'U') IS NULL
  CREATE TABLE [transactions] (
    [transaction_id] INTEGER IDENTITY (1, 1),
    [type]                  VARCHAR(10)   NULL CHECK (type IN
                                                      ('Payment', 'OfferCreate', 'OfferCancel', 'TrustSet', 'AccountSet', 'SetRegularKey')),
    [result]                NVARCHAR(255) NOT NULL,
    [created_at]            DATETIME2     NOT NULL,
    [updated_at]            DATETIME2     NOT NULL,
    PRIMARY KEY ([transaction_id])
  );
```

The type column is a VARCHAR(10) but the values of the types exceed 10 characters. It looks like the logic that handles the ENUM translation for the sync can be found here: https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query-generator.js#L357

It seems like it would make sense for this to default to the STRING length of 255 or potenially the length of the longest value in the ENUM array.

**Comment by janmeier** [comment]
Yeah, I think setting this to 255 would be a more sane default - PR welcome, shouldn't require to much change :)
