### ISSUE TITLE
Instance Get assumes all custom getter attributes are being loaded

### ISSUE THREAD

**Issue by Thomathan** [sequelize/sequelize#3969]
Line 209 of Instance.

If the model has custom getters, Get assumes those attributes are being retrieved. If you limit the attributes in a Find call that doesn't include a custom getter field it returns the error:
[TypeError: Cannot read property 'length' of undefined]

Current code:
```javascript
if (this._hasCustomGetters) {
    for (_key in this._customGetters) {
      if (this._customGetters.hasOwnProperty(_key)) {
        values[_key] = this.get(_key, options);
      }
    }
}
```

My current hotfix for this:
```javascript
if (this._hasCustomGetters) {
    for (_key in this._customGetters) {
      if (this.dataValues.hasOwnProperty(_key) && this._customGetters.hasOwnProperty(_key)) {
        values[_key] = this.get(_key, options);
      }
    }
  }
```

**Comment by janmeier** [comment]
I think that fix would work fine - PR with test very welcome :)

**Comment by mickhansen** [comment]
customGetters don't operate on attributes, so they wouldn't be in dataValues generally, or am i missing something here?

**Comment by janmeier** [comment]
Hmm that is actually true - the getter itself should check if the attributes it's trying to operate on are defined

**Comment by Thomathan** [comment]
Hmm, I had assumed that the getter was only being called when the relevant attribute was being loaded. 

Looking over my solution now, it would probably break somebody else's getters who don't assume that.

I've added proper validation to my own getters which fixes my issue.
