### ISSUE TITLE
JSONB search by key

### ISSUE THREAD

**Issue by adamwalz** [sequelize/sequelize#3970]
Are the postgres9.4 `?`, `?|`, and `?&` operators implemented in Sequelize? I was not able to find them in the comparator list but wanted to double check. http://www.postgresql.org/docs/9.4/interactive/functions-json.html#FUNCTIONS-JSONB-OP-TABLE

**Comment by mickhansen** [comment]
They are not implemented at the moment. But it might just work with using the operator as a key.

**Comment by adamwalz** [comment]
I wasn't able to get it by using the operator as a key. That might just be because I am new to sequelize though. But of course you have raw queries which worked great for me!
