### ISSUE TITLE
Unique attribute and different field name doesn't generate the right SQL Unique Constraint

### ISSUE THREAD

**Issue by shakdoesgithub** [sequelize/sequelize#3974]
If I have a model that has unique: true and a field name that is different than what is defined, the SQL statement to create the unique constraint will base it off the sequelize field.

For example:

  var User = self.sequelize.define('user', {
            username: {
              type: Sequelize.STRING,
              unique: true,
              field:'user_name'
            }
          },{
            hasTrigger:true
          });

The unique constraint will be off username instead of user_name

**Comment by janmeier** [comment]
Cannot reprodue this - is it mssql specific?

**Comment by janmeier** [comment]
Closing, no response
