### ISSUE TITLE
docs for findById a bit unclear around query options

### ISSUE THREAD

**Issue by defunctzombie** [sequelize/sequelize#3977]
Is it allowed/supported to do

``` js
User.findById('user_id_string', { useMaster: true })
```

Or would I need to use the general case of findOne and specify my own `where` clause and `useMaster` within the options?

**Comment by mickhansen** [comment]
`findById` takes all the same query options as all other calls, so `useMaster`, `transaction`, etc are supported.

**Comment by mickhansen** [comment]
This might not be clear since we don't document all query options seperate for all methods, not sure if we should do this or just refer to query, @janmeier?

**Comment by defunctzombie** [comment]
Right, but it also accepts a string as the first argument. In that case if
I want to useMaster do I have a second options argument?

**Comment by mickhansen** [comment]
Yes the signature for findById is `(param, options)`

**Comment by mrgamer** [comment]
what about `include` ? [In the documentation](http://docs.sequelizejs.com/en/latest/docs/models-usage/#eager-loading) seems to be described only for `find` and `findAll`

**Comment by akotranza** [comment]
Please provide documentation for using findById with id that is not a Number value, i.e. id as a UUID type (which is best practice, see http://blog.codinghorror.com/primary-keys-ids-versus-guids/ etc ad infinitum). Passing the UUID as the param does not work.

**Comment by defunctzombie** [comment]
@akotranza passing the uuid in string form works for me.

**Comment by mickhansen** [comment]
@akotranza https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1400 - What's your issue specifically?

Basically, findById takes a primary key value for a equality lookup as it's first argument, and all other finder options as it's second argument.

**Comment by akotranza** [comment]
Yes, I too have discovered that the uuid as string works. In general this project would benefit greatly from having at least one code example per method in the API. I appreciate the amount of detail in the User Guide section of the documentation, spreading even a 10th of that love over the API section would make using this library much less sticky.

**Comment by mickhansen** [comment]
@akotranza Good suggestion, we might go about that :) Any assistance always welcome.

**Comment by tsheaff** [comment]
@mickhansen I know this is an old issue, but I'm wondering whether it's still the case that `useMaster` option works for non-`.query()` methods. For example `modelInstance.findAll({ where: {...}, useMaster: true })`

**Comment by mickhansen** [comment]
@tsheaff IIRC all options from calls are passed to `query()` so yes it should work, mind you i haven't been involved with development of this project in a while

**Comment by dlarr** [comment]
@mickhansen : 
1- Does this Master/slave feature work for MariaDB ?
2- Is this requiring some special Pool configuration ? Or somthing else ?

Many Thanks.

**Comment by yuriploc** [comment]
> @mickhansen :
> 1- Does this Master/slave feature work for MariaDB ?
> 2- Is this requiring some special Pool configuration ? Or somthing else ?
> 
> Many Thanks.
> 
> EDIT : After own research :
> Answer to 1 : YES
> Answer to 2 : Apparently it would work with like that :
> 
> ```js
> 	sequelize = new Sequelize(config.database, config.username, config.password, {
> 		replication: {
>       			write: {
> 				host: AAA,
> 				port: BBB,
> 				username: CCC,
> 				password: DDD
> 			},
>       			read: [{
> 				host: EEE,
> 				port: FFF,
> 				username: GGG,
> 				password: HHH
> 			}]
> 		},
> 		logging: config.logging,
> 		dialect: config.dialect,
> 		pool: config.pool
> 	});
> ```
> 
> Answer 3 : usage
> 
> ```js
> models.Something.create({
>                 attr1: attr1Value,
>                 attr2: attr2Value
>                 attr3: attr3Value
> }, {useMaster: true});
> 
> // or 
> models.Something.findOne({
>                 where: {
>                     attr1: attr1Value
>                 },
>                 useMaster, true
> });
> ```

When doing something like

```javascript
models.Something.findOne({
                where: {
                    attr1: attr1Value
                },
                useMaster, true
});
```

Do you have to use `reload()`?
