### ISSUE TITLE
Getting 'Unhandled rejection SequelizeDatabaseError: column "value" does not exist"

### ISSUE THREAD

**Issue by rahul1346** [sequelize/sequelize#3978]
I'm trying to use passport.js to authenticate with facebook and am getting this error:

server-0 (out): Executing (a7d2ba28-c1f0-495d-826e-926517c5b671): SELECT "id", "username", "displayName", "email", "password", "created_at", "updated_at" FROM "users" AS "User" WHERE "User"."email" IN (`value` = 'raysharmawashere@gmail.com') AND "User"."displayName" = 'Rahul Sharma' LIMIT 1;
server-0 (out): Executing (a7d2ba28-c1f0-495d-826e-926517c5b671): COMMIT;
server-0 (err): Unhandled rejection SequelizeDatabaseError: column "value" does not exist
server-0 (err):     at module.exports.Query.formatError (/Users/rahulsharma/Desktop/jb/node_modules/sequelize/lib/dialects/postgres/query.js:421:16)
server-0 (err):     at null.<anonymous> (/Users/rahulsharma/Desktop/jb/node_modules/sequelize/lib/dialects/postgres/query.js:105:21)
server-0 (err):     at emit (events.js:107:17)
server-0 (err):     at Query.handleError (/Users/rahulsharma/Desktop/jb/node_modules/pg/lib/query.js:99:8)
server-0 (err):     at null.<anonymous> (/Users/rahulsharma/Desktop/jb/node_modules/pg/lib/client.js:166:26)
server-0 (err):     at emit (events.js:107:17)
server-0 (err):     at Socket.<anonymous> (/Users/rahulsharma/Desktop/jb/node_modules/pg/lib/connection.js:109:12)
server-0 (err):     at Socket.emit (events.js:107:17)
server-0 (err):     at readableAddChunk (_stream_readable.js:163:16)
server-0 (err):     at Socket.Readable.push (_stream_readable.js:126:10)
server-0 (err):     at TCP.onread (net.js:538:20)
server-0 (err): From previous event:
server-0 (err):     at module.exports.Query.run (/Users/rahulsharma/Desktop/jb/node_modules/sequelize/lib/dialects/postgres/query.js:97:19)
server-0 (err):     at /Users/rahulsharma/Desktop/jb/node_modules/sequelize/lib/sequelize.js:744:20
server-0 (err): From previous event:
server-0 (err):     at Promise._then (/Users/rahulsharma/Desktop/jb/node_modules/sequelize/lib/promise.js:14:16)
server-0 (err):     at module.exports.Model.findOrCreate (/Users/rahulsharma/Desktop/jb/node_modules/sequelize/lib/model.js:1157:62)
server-0 (err):     at Strategy._verify (/Users/rahulsharma/Desktop/jb/lib/auth/passport.js:20:12)
server-0 (err):     at /Users/rahulsharma/Desktop/jb/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:195:22
server-0 (err):     at /Users/rahulsharma/Desktop/jb/node_modules/passport-facebook/lib/strategy.js:184:5
server-0 (err):     at passBackControl (/Users/rahulsharma/Desktop/jb/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:125:9)
server-0 (err):     at IncomingMessage.<anonymous> (/Users/rahulsharma/Desktop/jb/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
server-0 (err):     at IncomingMessage.emit (events.js:129:20)
server-0 (err):     at _stream_readable.js:908:16
server-0 (err):     at process._tickCallback (node.js:355:11)

My user mode looks like this:

module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define("User", {
    username: {
      type: DataTypes.STRING,
      allowNull: true,
      validate: {
      }
    },
    displayName: {
      type: DataTypes.STRING,
      allowNull: true,
      validate: {
      }
    },
    email: {
      type: DataTypes.STRING(256),
      allowNull: false,
      validate: {
        isEmail: true,
        len: [5, 256]
      }
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
      }
    }
  }, {
    //  lowercase tableName in Posrgres, if you need.
    tableName: 'users',
    classMethods: {
      associate: function(models) {
        User.hasMany(models.Candidate);
        User.hasMany(models.Employer);
        User.hasMany(models.Topic);
        User.hasMany(models.Reply);
        User.hasMany(models.Notification);
      }
    }
  });

  return User;
};

**Comment by mickhansen** [comment]
You'll need to post the actual call resulting in the error for us to help you.

**Comment by janmeier** [comment]
Please don't post the same question on all channels - you will get an answer eventually :)

http://stackoverflow.com/questions/30961226/sequelizejs-error-when-authenticating-with-passportjsfacebook

**Comment by rahul1346** [comment]
Thanks guys.
