### ISSUE TITLE
Custom Find() function tied to a specific model. 

### ISSUE THREAD

**Issue by mattstrayer** [sequelize/sequelize#3979]
Couldn't find what I wanted in the documentation, so I'm just going to leave this here and hope for some help! 

I have a specific query that I need to run on my user Model with a lot of includes and those includes all have where statements inside of them... 
So, I'd like to unclutter my controller and put this logic 
```javascript 
User.findById(userId, {include: [{
        model: Model1,
        where: { aCondition: false}
    },{
        model: Model2,
        where: { aCondition: false}
    },{
        model: Model3,
        where: { aCondition: false}
    },{
        model: Model4,
        where: { aCondition: false}
    },{
        model: Model5,
        where: { aCondition: false}
    }]}).then()
```

into the Model itself so I'd just be able to call 

```javascript
User.findByIdWithIncludes(userId).then()
```
inside of my controller.

Does this functionality exist and I'm just missing it? 

Any help/advice would be greatly appreciated.

Thanks!

**Comment by janmeier** [comment]
You could add a [`classMethod`](http://docs.sequelizejs.com/en/latest/docs/models-definition/#expansion-of-models) which does a find, including all the includes. You could also add a [`(default)scope`](http://docs.sequelizejs.com/en/latest/docs/scopes/).

One problem is that scopes and methods are defined at the time the model is define - at which point you may not have all your other models / associations set up.

A solution for the scopes problem would be https://github.com/sequelize/sequelize/issues/3963

As for adding a new method, you could simply tack it onto the model object, once all models and associations are loaded: `User.findByIdWithIncludes = ...` 

Closing this in favor of #3963
