### ISSUE TITLE
findOrInitialize() with empty "where" option just returns first object from the DB.

### ISSUE THREAD

**Issue by VasilioRuzanni** [sequelize/sequelize#3981]
Sequelize: **3.2.0**, database: **Postgres**

With any model, the `findOrInitialize` method returns the first row in a database:

```
User.findOrInitialize({
  where: { id: undefined }, // or just where: {}
  defaults: {
    someAttr: 123,
    ...
  }
}).then(function (user) {
  // "user" is now just a first row from the database in Sequelize 3.2.0
  // but it used to be an object initialized with "defaults" attribute in Sequelize 2.1.3
});
```

From one side of the coin that might be justified - no `where` criteria is given so we can consider this case as "no criteria", assume that "everything matches" and return anything that matches first. From the other side, this method is only useful in cases when you need to initialize a new instance based on `defaults` when there is nothing to search for.

Is this expected behavior or is a regression introduced in **3.2.0**?

**Comment by mickhansen** [comment]
`where` should probably be required for both `findOrBuild` and `findOrCreate` if they aren't already.

/cc @janmeier

**Comment by janmeier** [comment]
Definitely!

**Comment by VasilioRuzanni** [comment]
@mickhansen @janmeier The `where` option itself is already required and it makes perfect sense keeping it that way (by "required" I mean that Sequelize checks whether the `where` is defined and throws otherwise).

The question is what to consider the empty `where: {}` param:
- Either as a misuse (should throw?);
- As a "no params to find by are given so nothing to select, just initialize the new one" (Sequelize 2.1.3 behaved this way);
- As a "no params to find by are given and we consider it a valid `SELECT` but without `WHERE`" (Sequelize 3.2.0).

So I'm curious if this `2.3.1 -> 3.2.0` behavior change was intentional and is not a kind of side effect of some refactoring (if it is - should be clarified in the docs probably).

**Comment by mickhansen** [comment]
Definitely not intentional. I'm leaning towards throwing on an empty but defined object.

**Comment by VasilioRuzanni** [comment]
@mickhansen I'm still naturally leaning towards thinking of `findOrInitialize(...)` as **"Well, no criteria is given, so nothing to search by, lets `initialize` right away"** - especially useful when you need to conditionally seed data or update previously seeded object that might or might not have an `id`.

Just a thought, its up to you what behavior Sequelize should have.
