### ISSUE TITLE
dynamic tables names? 

### ISSUE THREAD

**Issue by mikeRead** [sequelize/sequelize#3982]
I am trying to use a single model a for multiple tables and running CRUD  by table name.

For a simplified example a site has multiple users attached to multiple accounts
each table of users has a name like accountID_users

Currently I would build a mysql query like code below to get all users for an account
```javascript
function getUsers(accountId){
var tablename = accountId+"_users";
var query = "select * from `"+tablename+"`" ;
...
```

However I can not find any way of doing this in sequelize is create a model as a normal javascipt object (Users) and define the model for each call
```javascript
function getUsers(accountId){
	var tablename = accountId+"_users"
	var users = sequelize.define(tableName,Users.model,Users.setttings)
	users.findAll(...)
}
```

Is there any way around this? Or running sequelize.define scoped? meaning when getUsers() (in the 2nd code example)  sequelize.define does not store the "dynamic" table in memory for the life of the app, after the function ends? I would like to keep my server memory to a minimum. I cant find any documentation on this as every example is setting a table name on definition

**Comment by janmeier** [comment]
There is no functionality for this built into sequelize, but you should be able to simply change `model.tableName` before the query

**Comment by mikeRead** [comment]
Thank you, I will try it out
I am worried if table name could get overwritten when mutiple calls to the same function get called as the same time. Should I be worried about this?

**Comment by janmeier** [comment]
@mikeRead True, that would probably cause problems, true.

In that case, you could perhaps use CLS to solve the problem


Read [here](http://docs.sequelizejs.com/en/latest/docs/transactions/#automatically-pass-transactions-to-all-queries) for more on CLS + sequelize
```js
Users.prototype.getTableName = function () {
  return Seqeulize.cls.get('tablename');
}

function somethingsomething() {
  Sequelize.cls.set('tablename', accountId+"_users");
  User.find()...
}
```

CLS maintains context across async calls, so you should always have access to the right username when `getTableName` is called
