### ISSUE TITLE
Argument for included model does filter also for parent model

### ISSUE THREAD

**Issue by makromat** [sequelize/sequelize#3983]
Hi 
Is this issue or not even build function? If I'm trying to filter included model sequelize throws me filtered only "parent" model.

    Order.findAll({
        where: { id: 1 },
        include: [
          { model: Item, where: sequelize.and({'active' : true }) }
        ]
    }).then(function(order) {
        callback(null, order);
    });

I'd like to get each Order where id = 1 further Items where active = true, but I'm getting only Orders where  is at least 1 Item with active =true.

**Comment by janmeier** [comment]
Add required: false to the include - turns it from inner to left join http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance
