### ISSUE TITLE
Hooks and promises

### ISSUE THREAD

**Issue by purepear** [sequelize/sequelize#3987]
Hi,
can someone explain to me why this works 
```
beforeValidate: function(record, options) {
  record.slug = record.name
  return Promise.resolve(record)
}
```
and this does not
```
beforeValidate: function(record, options) {
  record.slug = record.name.toLowerCase()
  return Promise.resolve(record)
}
```

this is the essence of my problem.. spending few hours trying to understand what's going on... tried with callbacks without success(i got other promises and async calls ... this is just a simple example)

As soon as you call function and you get "Unhandled rejection Error"
These promises are over complicating everyting

**Comment by janmeier** [comment]
Seems like there is an error in your hook. Try checking that record.name is defined, and that it's a string

**Comment by mickhansen** [comment]
Handling errors makes working with promises quite a bit easier (so you can get a stack trace etc). Otherwise you can add a callback to Bluebird's onUnhandledRejection and throw the error to crash the application.

**Comment by janmeier** [comment]
In this specifci case you actually don't need to return a promise, since you are not doing anything async. You can just return `record`

**Comment by janmeier** [comment]
Closing, no response
