### ISSUE TITLE
Does sequelize support MySQL's timestamp data type?

### ISSUE THREAD

**Issue by axln** [sequelize/sequelize#3989]
I have existing MySQL database which has timestamp columns. How can I work with them?

I know that sequelize always stores UTC time in datatime columns, but I can't find any info on how to work with timestamp data type.

**Comment by itsravenous** [comment]
I would suggest reading #3512 - there's a good example there of adding your own custom data types (I used it to add the old MSSQL DATETIME type to my app, as Sequelize uses DATETIME2 for MSSQL out of the box)

**Comment by axln** [comment]
Great! Thank you very much. Will try it and reports the results.

**Comment by janmeier** [comment]
@axln There has been talk about supporting timestamp before. As you have already seen, it should be pretty easy to add the datatype, and we'd welcome a PR adding a `TIMESTAMP` datatype.

For support to be complete we'd also need a way to change the `createdAt` / `deletedAt` times to use timestamp instead of date

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/963

**Comment by axln** [comment]
I finally implemented the basic TIMESTAMP support using the method suggested by itsravenous.

Here is my code:

lib/sequelize-mysql-timestamp.js:

```javascript
'use strict';

var BaseTypes = require('sequelize/lib/data-types');
var util = require('util');

var TIMESTAMP = function() {
  if (!(this instanceof TIMESTAMP)) {
    return new TIMESTAMP();
  }

  BaseTypes.ABSTRACT.apply(this, arguments);
};

util.inherits(TIMESTAMP, BaseTypes.ABSTRACT);

TIMESTAMP.prototype.key = TIMESTAMP.key = 'TIMESTAMP';

exports.TIMESTAMP = TIMESTAMP;
```

In models we can now use (assumed that modes are located in the models subdirectory):
```javascript
'use strict';

var customDataTypes = require('../lib/sequelize-mysql-timestamp');

module.exports = function(sequelize, DataTypes) {
  var Sample = sequelize.define('Sample', {
    title: DataTypes.STRING,
    created: customDataTypes.TIMESTAMP
  }, {
    tableName: 'sample',
    timestamps: false
  });
  return Sample;
};
```

**Comment by itsravenous** [comment]
Glad it helped :)

**Comment by axln** [comment]
@itsravenous, thank you very much for your help!

**Comment by oaeide** [comment]
Is there any particular reason for this not being included?

**Comment by mickhansen** [comment]
@oaeide No PR was ever submitted as far as i remember, but this was a while back.

**Comment by oaeide** [comment]
Alright. I will try to get around to do it then.

**Comment by abenamer** [comment]
Hi there, 

Just wanted to know if this was ever submitted?

**Comment by janmeier** [comment]
@abenamer Nope, PR welcome

**Comment by natesilva** [comment]
For a project I’m working on we needed robust `TIMESTAMP` support to work with a legacy database. I created a `sequelize-mysql-timestamp` module that is now on NPM. Maybe others will find it useful as well. https://www.npmjs.com/package/sequelize-mysql-timestamp

**Comment by martindavid** [comment]
I wonder, is this suggestion included in any PR?

**Comment by bradleyy1012** [comment]
we live in 2017 and sequelize doesn't support the timestamp data type by default? whyyyyyy D=

**Comment by natesilva** [comment]
@bradleyy1012 As the author of that (we use it where I work), it’s fine, but I’d still recommend going with `DATETIME` over `TIMESTAMP`, unless you need to support a legacy schema.

**Comment by bradleyy1012** [comment]
i would but i need mysql to record the timezone. its more convenient for me to pass in a Date() object and have mysql remember the timezone. then in the getter function for the timestamp i just say: return (new Date(this.getDataValue('endTime'))).toString();

**Comment by yordis** [comment]
@natesilva @janmeier is there any reason why we couldn't include `sequelize-mysql-timestamp` on Sequelize itself?

**Comment by natesilva** [comment]
While I’d like to see the `TIMESTAMP` data type natively supported, `sequelize-mysql-timestamp` is a hack. It works, but I’m sure there are better ways to do it. We still rely on it at my company but we’re migrating our remaining `TIMESTAMP` columns to `DATETIME`.

It’s not only Sequelize, other ORMs we’ve looked at also treat `TIMESTAMP` as a legacy data type. There are pros and cons for both data types, but it’s easier to go with what is widely supported.
