### ISSUE TITLE
How to optionally apply non-association scopes when using injected getters

### ISSUE THREAD

**Issue by itsravenous** [sequelize/sequelize#3990]
If I have a Person model with a convenience scope defined for querying by name:

```javascript
var Person = Sequelize.define('Person', {
	Forename: {
		type: Sequelize.STRING
	},
	Surname: {
		type: Sequelize.STRING
	}
}, {
	tableName: 'tblPeople',
	scopes: {
		name: function (value) {
			return {
				where: {
					$or: [
						{
							Forename: {
								$like: '%'+value+'%'
							}
						},
						{
							Surname: {
								$like: '%'+value+'%'
							}
						}
					]
				}
			};
		}
	}
});
```

I can't think of a way to apply that scope when using `someOtherModelInstance.getPerson()`. I want to be apply to apply it as an option, not by default (as I understand it, association scopes are always applied when using the getter).

The logical solution to me seems to be to add support for something like this:

```javascript
someOtherModelInstance.getPerson({
    scope: { method: ['name', 'Tom'] }
});
```

**Comment by janmeier** [comment]
This is already supported, exactly like you proposed :) 

http://docs.sequelizejs.com/en/latest/docs/scopes/#associations

**Comment by itsravenous** [comment]
You guys are great :) I thought I'd read the docs cover to cover but just wasn't looking in the right place. Thanks!
