### ISSUE TITLE
Update Database 

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/sequelize#3996]
I have used sequelize and I liked the ORM Tool, however one thing which really seems to be incomplete or may be something I am not aware of is how can I update the mysql database once I have defined the models in Sequelize. I would like to either define models in the sequelize and then there should be some way to update the mysql database from those models rather than doing it our own. Or we could have the database updated and the somehow update the models in sequalize without really manually doing it ourselves.

Is there any way to make it work.

**Comment by mickhansen** [comment]
We don't currently support automatically updating the database. It's an often requested feature but no one from the core team is getting around to it soon since we deem it unsafe.

We suggest you take a look at Umzug, the sister migration library.
