### ISSUE TITLE
hasMany setter should set source id on target instances

### ISSUE THREAD

**Issue by irobert91** [sequelize/sequelize#3998]
Hello

I'm not sure if this is a bug or expected behavior, but I have noticed a difference between `3.2.0` and  `3.3.1` when adding or setting associations. Given the following piece of code:

``` js
var User = sequelize.define('user', {});

var Post = sequelize.define('post', {});

User.hasMany(Post);
Post.belongsTo(User);

sequelize.sync({force: true}).then(function() {

  User.create().then(function(user) {
    var post = Post.build();

    console.log(post.userId);

    user.setPosts([post]).then(function() {
      console.log(post.userId);
    });
  });
});
```

`3.2.0` will output `undefined` for the first `console.log` and `1` for the second.
`3.3.1` will output `undefined` for both.

I couldn't find anything related in other issues.

**Comment by mickhansen** [comment]
The setter for hasMany was optimized i believe.
It's not technically breaking since it's not exactly public behaviour, but something that could actually be restored even with the optimizations i belive, @janmeier ?

**Comment by janmeier** [comment]
Yep, should be pretty easy to bring back the old behaviour. Right around [here](https://github.com/sequelize/sequelize/blob/master/lib/associations/has-many.js#L249-L251).

Similarly, the obsolte associations above should probably have their foreign identifier above set to null

**Comment by mickhansen** [comment]
Although i suppose they should only be set if the call succeeds, although that wasn't the behaviour before i suppose.

**Comment by irobert91** [comment]
This broke some of my tests, so I was just wondering what is the right behavior.
Are you suggesting that I shouldn't rely on it?

**Comment by mickhansen** [comment]
@irobert91 Well it definitely hasn't been documented and there were no tests for it, but i agree it's a neat feature so we'll look to reintroduce it :)

**Comment by irobert91** [comment]
Ok, thanks! I will stick to 3.2 until then. Do you think that this could be in the next release?

**Comment by janmeier** [comment]
No idea - but if you provide a PR, then yes ;)

Should only be a couple extra lines of code + tests

**Comment by irobert91** [comment]
@janmeier I will try to look into it.
