### ISSUE TITLE
Limitations on Sequelize 

### ISSUE THREAD

**Issue by jfgomez86** [sequelize/sequelize#40]
I'm trying to store images in a database as base64 encoded strings. It works well with some small (<30kb) images, but on larger images, the string stored is being truncated. 
I've already investigated a lot on the backend side, nodejs, front-end javascript and the only place where the content actually changes is between sequelize and the database. So I'm wondering if there are any limitations on Sequelize's side regarding string sizes to be stored.

**Comment by thomaslc66** [comment]
@sdepold Hello,do you still have the link to this file. might be usefull

**Comment by sdepold** [comment]
Oooph, I don't really recall that anymore. I'm storing images in a Postgres database for a project of mine and it works just fine.

**Comment by WikiRik** [comment]
This link might work; https://github.com/sequelize/sequelize/tree/2.0/examples/image-handling
But be aware that this is from Sequelize v2 and we are now on v6 and a lot has changed since then
