### ISSUE TITLE
validateIncludeElements is not optimized by V8 (event loop blocking)

### ISSUE THREAD

**Issue by emhagman** [sequelize/sequelize#4000]
The validateIncludedElements function is not being optimized by V8. This is causing tick issues that are blocking the event loop which is not a good thing for concurrency.

![V8Profiler](https://www.evernote.com/shard/s108/sh/6499a5c7-1dc7-4443-8556-73975d74474d/7043858c665dd3d2/res/7742a5d4-999a-4921-87df-14aa36e51656/skitch.png)

~ means not optimized.
* means optimized.

Using V8Profiler with IntelliJ.

**Comment by mickhansen** [comment]
Thank you :) And optimization PR always welcome.

**Comment by janmeier** [comment]
Hmm weird, I don't see any code in there that would case the function to go into de-op

**Comment by emhagman** [comment]
I don't either, I am quite baffled.

**Comment by mickhansen** [comment]
V8 won't optimize code unless it's hot, maybe it's just not hot.
