### ISSUE TITLE
Field "options" with type JSONB causes weird behaviour

### ISSUE THREAD

**Issue by skeskinen** [sequelize/sequelize#4005]
If you name one of your fields `options` it conflicts with Sequelize internals.
The nasty part about this is that if you aren't actually using the said field (yet) the problem can manifest in really weird ways, for example eager loading breaks.
There should at least be a warning if you try to use one of the "reserved" variable names in your own code (options, dataValues, hasPrimaryKeys, isNewRecord).

**Comment by mickhansen** [comment]
Agreed, ideally we're looking to prefix all private variables with `$` or similar.
Although we really suggest people use `.get(field)` rather than `[field]`
