### ISSUE TITLE
Documentation issues around migration

### ISSUE THREAD

**Issue by mdarveau** [sequelize/sequelize#4006]
Hi,

In http://sequelize.readthedocs.org/en/latest/api/sequelize/#getqueryinterface-queryinterface, getQueryInterface, the http://sequelize.readthedocs.org/en/latest/api/queryinterface link is broken.

Also, in http://sequelize.readthedocs.org/en/latest/docs/migrations/, Skeleton section, it says:
```The passed migration object can be used to modify the database. The DataTypes object stores the available data types such as STRING or INTEGER. The third parameter is a callback function which needs to be called once everything was executed. The first parameter of the callback function can be used to pass a possible error. In that case, the migration will be marked as failed.```
It mentions a third parameter callback but it's not used in the example. It should say that if a third param is present, it should be called then migration is done, or a promise is returned and the third param is skipped.
Next, the doc says that migration params are `up: function(migration, DataTypes)` but sequelize-cli says `up: function(queryInterface, Sequelize, done)`. The later seems right.

I can do a PR to fix that but I just want to confirm I'm not completely off.

**Comment by mdarveau** [comment]
Ok, looking at the code, I see that `migration == queryInterface` and `DataTypes == Sequelize`.

I assume that the sequelize doc should be updated so the second param is `Sequelize` instead of `DataTypes` and the sequelize-cli doc should be updated to specify that the functions of `queryInterface` are described in http://sequelize.readthedocs.org/en/latest/docs/migrations/.

**Comment by janmeier** [comment]
Both ways of writing migrations are right - if you take a done callback, you should call that, otherwise you can return a promise.
I think we should remove all mention of taking a callback from the migrations docs and only document the promise way :)

It would probably make sense to rename datatypes to sequelize in the examples - but remember to mention, that the datatypes are available on the sequelize object :)

QueryInterface is not public API on purpose (we want to be able to change it without breaking the API). I don't mind having the getQI function in the API docs, but the see part should be removed :)

**Comment by Chaulky** [comment]
If the QueryInterface is not a public API, why is it supposed to be used in the migrations? Do you mean that only part of QueryInterface is meant to be public?

**Comment by janmeier** [comment]
@Chaulky Yes, a more precise statement would be that only parts of the query interface are public API :) 

I guess thats also part of why we call it `migration` in the skeletons - to hide the fact that there are also other methods, which shouldn't be used

**Comment by GregAdSupply** [comment]
It's only called `migration` in docs. When you create a new migration skeleton using the sequelize cli, it calls it `queryInterface`.

**Comment by janmeier** [comment]
Well, my point is invalid then :)

**Comment by sushantdhiman** [comment]
@janmeier Its fixed in #4589

**Comment by janmeier** [comment]
@sushantdhiman Thanks :)
