### ISSUE TITLE
Sequelize doesn't compare dates correctly

### ISSUE THREAD

**Issue by wmulligan** [sequelize/sequelize#4007]
sequelize is using the == comparison to look for changes when using instance.update().  This causes the two identical dates to show as "changed".

The line of code is here
```
if (!options.raw && ((primitives.indexOf(typeof value) === -1 && value !== null) || value !== originalValue)) {
```

This article explains the problem: http://stackoverflow.com/questions/492994/compare-two-dates-with-javascript

I suggest that we need better comparison checks for type DATE and DATEONLY

**Comment by wmulligan** [comment]
Other issue is sequelize is not converting DATEONLY to a Date object, but it does convert the value read from.  So the code ends up comparing a string like 'YYYY-MM-DD' to a date object.

**Comment by janmeier** [comment]
I told you dates would be an issue @mickhansen  ;) https://github.com/sequelize/sequelize/pull/3588

@wmulligan Yeah we need to implement some custom parsing logic for dateonly - currently I think its actually the db driver returning a date object

**Comment by gutobortolozzo** [comment]
I implemented a small code inside ``` instance.set() ``` to prevent the method to identify date attribute has changed when the value is the same, It works as expect and nothing is added to ``` instance._changed```, but that raised a different question, when I call method ``` instance.save() ``` on one model that has nothing changed it generates one SQL updating the field ``` updatedAt ```. From my point of view, when nothing changed even with the value of ``` options.silent=false ``` no SQL should be sent to database. What do you guys think?

**Comment by mickhansen** [comment]
`save` should definitely be a no-op if nothing has changed.

**Comment by gutobortolozzo** [comment]
@mickhansen, Well, I make a PR to fix the date comparison and one other to prevent the ``` save ``` behavior described above. Thanks :)

**Comment by gutobortolozzo** [comment]
@mickhansen, Just make the PR to fix the way dates are compared, about the ```save``` issues, I will make one other PR later.

**Comment by janmeier** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/4116
