### ISSUE TITLE
[Question] How to remove millisecond in datetime (createdAt, updatedAt ... ) Postgres

### ISSUE THREAD

**Issue by kimthangatm** [sequelize/sequelize#4008]
Hi, I use Node JS and PHP Laravel and I don't want millisecond in datetime field.

**Comment by mickhansen** [comment]
I believe this is handled as low level as the pg library, not quite sure how you would change this.
@janmeier might have an idea.

Closing since not a feature or a bug.

**Comment by janmeier** [comment]
On insert it is handled in sql-string.js. But if we don't set milliseconds, they will just be set to .000 in the db. I don't think PG has a datatype without ms precision
