### ISSUE TITLE
id is incremented on failed validation

### ISSUE THREAD

**Issue by elliotfleming** [sequelize/sequelize#4009]
v3.3.0, MySQL

ID auto-increment value is incremented even when validation fails during the creation of a new instance. 

**create()**
1) Instance successfully created, id=1
2) Instance creation fails validation
3) Instance creation fails validation
4) Instance successfully created, id=4

The expectation would be that the auto-increment value only increment on successful creation of an instance, rather than on each call to create().

**Comment by janmeier** [comment]
Cannot reproduce this. We only try to insert when the sequelize validation passes.

If by validation you mean unique / foreign key constraints, then yes it seems that mysql does increment ids before checking constraints. Nothing we can do about that :)

**Comment by elliotfleming** [comment]
Ok, yes... it was the validation of a unique field that was failing. Thank you for clearing that up.

**Comment by alexiskattan** [comment]
@elliotfleming what was the fix for this?  Is the proper thing to check if it is unique before inserting?

**Comment by elliotfleming** [comment]
@alexiskattan it's been long enough that I can't recall specifically, but I do believe that would be the solution when working with MySQL.

**Comment by m4rii0** [comment]
Any ideas how to avoid this behavior?
