### ISSUE TITLE
Current contribution steps don't quite work because of Docker + Node issues

### ISSUE THREAD

**Issue by pimterry** [sequelize/sequelize#4010]
The current contribution setup steps refuse to run the tests when run from a blank checkout on my ubuntu machine. The main problem is that they ask you to run `npm install` locally, and then create a docker instance, and actually you need `npm install` to run inside docker (as it does automatically), and doing it yourself seems to create issues.

There's a couple of specific things that break:
- You need to install the libpq-dev before local `npm install` will work (pg_config won't build without it).
  
  Note that libpq-dev is already installed inside the docker container, just not necessarily on your local machine.
- Sqlite3 won't install the right bindings, unless you're using io.js locally.
  
  The Docker container is built with io.js, not node (see https://github.com/sequelize/sequelize/blob/0a8db194faf400c3c46a5689fb77f35d98c5897a/Dockerfile#L1). In the process of requiring sqlite3 inside the container it tries to load `/sequelize/node_modules/sqlite3/lib/binding/node-v43-linux-x64/node_sqlite3.node`. If you npm installed outside docker though it will install a different binding version. With node 0.10.28 locally though my `npm install` instead only creates `sequelize/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node`.
  
  `npm run test-docker` then fails to start mocha, because require('sqlite3') fails, so you can't run the tests at all.

I'm making an issue rather than just a PR because I'm not sure which way you want to go with this:

One option is to never `npm install` locally at all. If you do that, docker runs happily and can do everything, no problemo. Is that practical? Seems weird, but it does work for me.

Another option is either require people to install libpq-dev and io.js up-front, and to npm install only through io.js. Equivalently, you could move your docker container to a standard node version, and ask people to use that instead, which might be an easier sell.

Finally, you could try to find a way to stop the docker container sharing your local node_modules folder. I'm not sure exactly how this is set up at the moment, but that's definitely the core issue (if I run `npm install` locally after setting up a working docker instance, docker stops working). Fixing that would make the local/docker `npm install`s independent, and solve this quite neatly, but it'd need more investigation.

**Comment by mickhansen** [comment]
`npm install` indeed needs to happen through the docker container for everything to work (that's generally the case for all libs which have bindings).

There's unfortuneatly not anyway to ignore the local node_modules folder when doing volume sharing as far as i can tell.

Ideally people should be able to have npm installed locally aswell so they can run unit tests without going through docker, but not exactly sure how we can do that.
