### ISSUE TITLE
Options object is mutated and cannot be reused when calling model.create

### ISSUE THREAD

**Issue by sclement41** [sequelize/sequelize#4011]
I am calling myModel.create passing in an options object which contains my transaction.

I then try to call mySecondModel.create passing in my options object again, but the first call actually mutated my options object which now contains values for "fields", "instance", "model", "returning", etc.

I was expecting the options object to be cloned before being used internally by Sequelize, so that I can reuse it between calls. The problem code is in Instance.prototype.save, where the code is using the options object without cloning it first.

**Comment by Aukhan** [comment]
@mickhansen sorry to be commenting on a closed issue but I need similar help here.
I can see that the create, update methods are not mutating the options object anymore but I am trying to reuse the same options object in hooks (afterCreate, afterUpdate).
I can see save method here
https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/instance.js#L592
passes the cloned options object into hooks and it contains values for fields, returning etc just like @sclement41  mentions above. When I pass this options object into other getters or query generating functions inside hooks, it causes a field mismatch and throws errors that such and such columns or not part of the table `ER_BAD_FIELD_ERROR: Unknown column 'my_column_name' in 'field list'`

I feel that hooks should also be getting the original options object. Please advice if this is a bad design decision on my end.

Thanks
