### ISSUE TITLE
Executing raw query on tables not defined as models breaks Sequelize 

### ISSUE THREAD

**Issue by ivosabev** [sequelize/sequelize#4012]
An example will be inserting unique id twice. This will break because Sequielize will try to call something like "this.model.uniqueKeys", but this.model is undefined since no model exists.

Could this be changed so we can make raw queries without defining models.

**Comment by janmeier** [comment]
Which dialect and version are you on? As far as I remember all dialects should check for this.model before checking unique keys

**Comment by ivosabev** [comment]
I am using Postgresql, but the error is in the abstract/query.js

```
AbstractQuery.prototype.getUniqueConstraintErrorMessage = function(field) {
  var message = field + ' must be unique';
  var self = this;
  Object.keys(self.model.uniqueKeys).forEach(function(key) {
    if (self.model.uniqueKeys[key].fields.indexOf(field.replace(/"/g, '')) >= 0) {
      if (self.model.uniqueKeys[key].hasOwnProperty('msg')) {
        message = self.model.uniqueKeys[key].msg;
      }
    }
  });
  return message;
};
```

**Comment by janmeier** [comment]
Adding a check for `if self.model` before that should be fine - PR welcome, now that you've already identified the right spot :)

**Comment by janmeier** [comment]
Fixed it myself in connection with another issue - thanks for the report @ivosabev :)
