### ISSUE TITLE
Define scope with includes after definition

### ISSUE THREAD

**Issue by makrolabs** [sequelize/sequelize#4018]
When I have a model as follows:

    var Group = Sequelize.define("Group", {});
    var Member = Sequelize.define("Member", {});
    Member.belongsTo(Group);
    Group.hasMany(Member);

The models depend on each other, thus I can not define the scope when defining the model. How can I do something like this afterwards:

    Member.defineScope("withGroup", {
        include: Group
    });
    Group.defineScope("withMembers", {
        include: Member
    });

**Comment by aarosil** [comment]
@makrolabs how did you solve this?  I face the same issue.

**Comment by makrolabs** [comment]
@aarosil I have no solution. I found that this issue is already open: https://github.com/sequelize/sequelize/issues/3963
