### ISSUE TITLE
include :: where clause + required false

### ISSUE THREAD

**Issue by asimsohail** [sequelize/sequelize#4019]
hi..

im trying to load a model with **some** of its associations through a `where` clause.. the issue is that if no matching associated models are found, the parent model itself fails to load..

```javascript
user.getParent({
  include: [{
    model: Child,
    where: { gender: 'FEMALE' }
  }]
}).then(function(parent) {
  var daughters = parent.children;
});
```

ive tried setting `required : false` as well but looks like it is automatically set to true if a `where` clause is present..

what i need is to be able to specify a `where` clause, and if there are matching `Child` objects, they should be returned.. if not, the `Parent` object should still be loaded with `children = null` or `children = []`..

**Comment by janmeier** [comment]
Setting required to false should be the solution, are you sure you are setting it on the include (as opposed to on the options or where object) 

If it still doesn't work, please post a complete example with models, associations and find call

**Comment by asimsohail** [comment]
@janmeier 

**Javascript Model Definition**
```javascript
var Ancestor = sequelize.define('ancestors', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true
  }
});

var Descendant = sequelize.define('descendants', {
  name: Sequelize.STRING
});

Ancestor.hasMany(Descendant);
Descendant.belongsTo(Ancestor);
```

**SQL Script**
```sql
INSERT INTO ancestors (id) VALUES (1);
INSERT INTO descendants (name, ancestorId) VALUES ('my_name', 1);
```

**Javascript Code**
```javascript
Ancestor.findAll({
  include: [{
    model: Descendant
  }]
}).then(function(ancestors) {
  // ancestors = array[1]
  // ancestors[0].id = 1
  // ancestors[0].descendants = array[1]
  // ancestors[0].descendants[0].name = m'y_name'
});

Ancestor.findAll({
  include: [{
    model: Descendant,
    where: { name: 'not_my_name' }
  }]
}).then(function(ancestors) {
  // ancestors = array[0] !!!

  // what i expect:
  // ancestors = array[1]
  // ancestors[0].id = 1
  // ancestors[0].descendants = array[0]
});
```

**Comment by asimsohail** [comment]
@janmeier.. i posted a complete solution that was a simple representation of my complex problem.. it turned out to be working as expected (required: false giving a blank array).. that led me to suspect that there was an issue with my complex code.. sure enough, the issue was in my code and not sequelize..

i was including nested includes and i had missed a `require: false` clause in one nested include.. setting it made the code work.. :) thanks mate..
