### ISSUE TITLE
`notNull` validation triggered when .save() is called on instance with nothing changed.

### ISSUE THREAD

**Issue by calvintwr** [sequelize/sequelize#4021]
Suppose the following:

```
    var User = sequelize.define('User', {
    userId: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    someNotNullField: {
        type: DataTypes.BIGINT,
        allowNull: false
    },
    someOtherField: {
        type: DataTypes.STRING
    }
```

Then if I only retrieve the `someOtherField` attribute, and subsequently not change anything, it will attempt to also validate fields I have not selected:

```
User.find({
    where: { userId: 1 },
    attributes: [ 'userId', 'someOtherField' ]
}).then(function(user) {
    return user.save();
});
```

This will throw a `SequelizeValidationError` stating that `someNotNullField` cannot be null.

**Comment by mickhansen** [comment]
Hmm, so the question is whether default `fields` should intersect with the `attributes` of the original find statement. That's quite a bit of coupling.

**Comment by calvintwr** [comment]
@mickhansen Don't think that is the issue. Neither should you couple with the original find, because thats kinda being done already. I believe the `_previousDataValues` branch is constructed using the original find statement. Which then works as it is now when you intersection `dataValues` with `_previousDataValues` to find things to trigger `.changed()`.

The weird behaviour is when it tries to intersection itself with everything when nothing has changed. I can't really figure out whats causing it to do that.
