### ISSUE TITLE
Created instance returning null ID (MySQL)

### ISSUE THREAD

**Issue by lucianocn** [sequelize/sequelize#4031]
When I create an instance the callback is returning NULL id, but its saving ok in the MySQL database. What I'm doing wrong?

	var Sequelize = require('sequelize');
	var sequelize = new Sequelize('database', 'root', '', {
	    host: 'localhost'
	    dialect: 'mysql'
	});

	var Line = sequelize.define('Line', {
	    id: { type: Sequelize.INTEGER, primaryKey: true }, // Auto Increment
	    name: Sequelize.STRING
	});

	Line.create({
	    name: 'Test
	}).then(function(line) {
	    console.log(line.get());
	});

Console Output:

    {id: null, name: 'Test' }

Database:

    id: 1
    name: Test

**Comment by janmeier** [comment]
Are you absolutely sure you marked the id column as `autoIncrement: true`?  When I do that everything works fine for me.

Also, as I told you on SO, you don't need to manually add the id column, sequelize will do it for you

**Comment by lucianocn** [comment]
@janmeier Thank you for your support.
As I was using sequelize sync without force, my SQLite wasn't being rebuilt after I added `autoIncrement: true`. My mistake, thank you!

    models.sequelize.sync({force: true}).then(function () {
        server.listen(3000, function() {
            console.log('Listening on port ' + server.address().port);
        });
    });
