### ISSUE TITLE
DateOnly data type not working correctly

### ISSUE THREAD

**Issue by pyephyomaung** [sequelize/sequelize#4035]
Step to reproduce:
1) define a sequelize models with an attribute "date" of dateonly data type
2) Try
```
var instance = models.SomeModel.build({ date: new Date(2012,8,16) });
```
3) instance.date give the wrong date

**Comment by janmeier** [comment]
Did you find a fix @pyephyomaung ? Did you try passing a string instead - generally a date object is going to cause problems because JS dates always have a time (even though you instantiate them with date only)

**Comment by pyephyomaung** [comment]
yeah I made a workaround by adding a custom getter
