### ISSUE TITLE
Raw query with model transformation doesn't take into account the field value.

### ISSUE THREAD

**Issue by ivosabev** [sequelize/sequelize#4036]
Model:
```
module.exports = function(sequelize, DataTypes) {
  var Person = sequelize.define('Person', {
    firstName: {
      type: DataTypes.STRING,
      field: 'first_name'
    }
  });
});
```

Use case:
```
Sequelize.query("SELECT * FROM persons", {
  model: models.Person
}).then(function (persons) {
  persons.forEach(function (person) {
    console.log(person.firstName);
    console.log(person.get());
  });
});
```

Outputs 'undefined'

'person.get()' will output { first_name: 'John' }

...

I understand the problem, it is, because I have to manually select the fields as "first_name AS firstName", but I think the transformation function that builds the model should be smart enough to know if the fields were already converted in the SQL (like you do when find() is used) and when they are not converted as in the case of raw query.

**Comment by mickhansen** [comment]
Will be fixed by https://github.com/sequelize/sequelize/pull/3995

**Comment by ivosabev** [comment]
Great, when could we expect a release?

**Comment by mickhansen** [comment]
PR is not merged yet, so sometime after that.
