### ISSUE TITLE
[Question]: Is it possibly to order an include by it's 'through' association?

### ISSUE THREAD

**Issue by bitwit** [sequelize/sequelize#4038]
I'm having trouble figuring out how to set the order of the nested data on a query.

My model is as follows:

```
Bucket
WalkthroughBucket //defined as 'through' table, but also has it's own 'displayOrder' column
Walkthrough
```

Then I make a query form the bucket...

```
db.Bucket.findAll({
include: [{
  model: db.Walkthrough,
  attributes: ['id'],
  order: [[db.Walkthrough, db.WalkthroughBucket, 'displayOrder', 'DESC']]
}]
})
```

What I'm expecting is that the the first returned result, let's call it `bucketA`, would have a `bucketA.WalkthroughBuckets` array ordered correctly by the associated `displayOrder` but it still comes back out of order.
Is there an obvious issue with my query or is this sort of thing not as I'm expecting? I couldn't actually find `order` used inside of an `include` anywhere in the docs, so I came here to confirm that's even doable.

**Comment by bitwit** [comment]
Pardon me, I meant `bucketA.Walkthrough` is not ordered as expected not `bucketA.WalkthroughBucket`.

**Comment by mickhansen** [comment]
`order` is generally for ordering the main table, although for how SQL works it should *just* work on the include aswell. Can you post the SQL for the call?

**Comment by dongseok0** [comment]
This is quite old but leaving my finds for help someone.

As @mickhansen said, `order` for main table, but there is `separate` option to enable `order` in include. ( http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll )
```
  include: [
     {model: Feedback, as: 'feedbacks', separate: true, order: [['updatedAt', 'DESC']]},
  ]
```

Or, I could just provide `order` on main table query to order associated table.
```
  include: [
     {model: Feedback, as: 'feedbacks'},
  ],
  order: [[Sequelize.col('feedbacks.updatedAt'), 'DESC']]
```
Hope this help!
