### ISSUE TITLE
FindOrCreate with CLS and unmanaged transaction

### ISSUE THREAD

**Issue by gutobortolozzo** [sequelize/sequelize#4039]
Hi. I'm using sequelize with mocha to execute my test specs, so using continuation-local-storage and I'm able to create one transaction before test start, propagate this transaction to all my operations and by the end of test rollback the transaction, my configuration is exposed below.

```javascript
var cls = require('continuation-local-storage');
var namespace = cls.createNamespace('my-namespace');
Sequelize.cls = namespace;
```

```javascript
beforeEach(function(done){
    models.sequelize.transaction().then(function(t){
        models.namespace.set("transaction", t);
        done();
    });
});

afterEach(function(){
    models.namespace.get("transaction").rollback();
});
````

But when I'm using findOrCreate, I always need to explicitly pass my transaction as option parameter, what is not required by other methods. After some changes inside my node_module/sequelize/model.js on method findOrCreate I added this silly snippet of code and the method works as expected.

```javascript
if(this.sequelize.constructor.cls){
    options.transaction = this.sequelize.constructor.cls.get('transaction');
}
```

I did some miss configuration or this is the expected behavior of findOrCreate?

Thanks.

**Comment by janmeier** [comment]
The cls transaction is not added before `sequelize.query`, so I see the issue here.

The fix you posted looks good - add a test and you have yourself a PR :)

**Comment by gutobortolozzo** [comment]
@janmeier I will post the PR late this week.

Thanks :)
