### ISSUE TITLE
Sequelize is incompattible with collections

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#4040]
The [collections](https://github.com/montagejs/collections) package includes an `array.clone` shim.

As a result Sequelize dies if you try certain calls. Namely this happens if you do a find with an includes that includes a Sequelize class.

For example:
`Model.find({include: [{model: User, as: 'user'}]})`

Basically:
- Sequelize tries to deep clone the method `opts` (with a customizer that avoids cloning Sequelize classes)
- Sequelize's Utils.cloneDeep encounters the array under `include:` and tests it for a `.clone` method.
- Upon discovering collections' `array.clone` it calls the shim and `array.clone` begins a deep clone of the array and any objects in it.
- Upon encountering the Sequelize instance under `model:` the shim attempts to clone it.
- The shim fails to clone the model and throws an `Error: Can't clone [object SequelizeModel:User]` error breaking the whole program.

This will happen to anyone who happens to require the `collections` package **anywhere** in their application and makes use of an array with a Sequelize class nested in it as options to a Sequelize method.

I understand that collections shouldn't be shimming array with a clone method. However blindly trusting a mysterious `clone` method on any object without even testing it doesn't seem like a reliable code pattern.

**Comment by mickhansen** [comment]
Not sure how we could differ between `clone` methods to know which ones to trust (it's a nice abstraction for us internally).

The quickfix for this could be to check whether or not it's an array and then just skip if it is.

**Comment by dantman** [comment]
Do you want a 3.3.3 with the `v3.3.2` tag as a base. Or a commit to master?

**Comment by mickhansen** [comment]
PR to master would be best.
