### ISSUE TITLE
Define starting index value in Model

### ISSUE THREAD

**Issue by lfcgomes** [sequelize/sequelize#4043]
Hello guys,

I have a model with an auto generated id as PK. However, I want to force the id to start in 3 instead of 1 (as usual).

There is an easy way so I can do this? What do I need to add to my model?

Thanks! :)

**Comment by janmeier** [comment]
> To start with an AUTO_INCREMENT value other than 1, you can set that value with CREATE TABLE or ALTER TABLE, like this:
     mysql> ALTER TABLE tbl AUTO_INCREMENT = 100;

https://dev.mysql.com/doc/refman/5.0/en/example-auto-increment.html

This can easily be done with a raw query, so this is not functionality that belongs in sequelize core

**Comment by darkguy2008** [comment]
So what's the use of sequelize, if not, to abstract the database layer? I came here from google looking for the same functionality only to find out that the expected path is to use raw SQL anyways, go figure.

**Comment by neilveil** [comment]
This is a very useful feature that should be in the sequelize configurations & models too. Because it's a common practice by many applications when going into production they start their ids of all the tables from 1000, 100000, or maybe a random number, so that the actual count of data can not be determined. Otherwise, just to do this we have to write a separate script that needs to be manually executed on the database server.

**Comment by s1nistr4** [comment]
Ah the good ol issue with no solution, tons of thumbs up, been around for 8+ years

**Comment by ephys** [comment]
There is a solution, as provided by janmeier 8 years ago. You simply need to run a [raw query](https://sequelize.org/docs/v7/querying/raw-queries/). You can do this during the [`AfterSync`](https://sequelize.org/docs/v7/other-topics/hooks/) event:

```ts
import { sql, Model } from '@sequelize/core';
import { AfterSync } from '@sequelize/core/decorators-legacy';

export class MyModel extends Model {
  @AfterSync
  static async _onAfterSync() {
    if (await MyModel.findOne() !== null) {
      return;
    }

    await MyModel.sequelize.query(sql`ALTER TABLE ${sql.identifier(MyModel.table.tableName)} AUTO_INCREMENT = 100;`);
  }
}
```

The actual query depends on the dialect, the one above is for MySQL

It's not realistic to think an ORM can cover every possible feature of all supported dialects. Each feature requires research to unify the quirks of all dialects, and designing an interface that is simpler to use than using SQL directly. Therefore, we cover the highly requested use cases, and those complex enough that we can add value over the plain SQL solution
