### ISSUE TITLE
Documentation/changelog confusion over references

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#4046]
The CHANGELOG states this for `sequelize@3.0.1`.

> - [CHANGED] The `references` property of model attributes has been transformed to an object: `{type: Sequelize.INTEGER, references: { model: SomeModel, key: 'some_key' }}`. The former format (`references` and `referecesKey`) still exists but is deprecated and will be removed in 4.0.

I don't use the "references without foreign key" pattern shown [in the documentation)[https://sequelize.readthedocs.org/en/latest/docs/associations/#enforcing-a-foreign-key-reference-without-constraints].

However I do use `Model.{hasOne,hasMany,belongsTo}` in my Model's associate function and `references` and `referencesKey` in my migrations.

Does this change affect migrations? If so, what is the new format (since you wouldn't use `model: Model` in migrations?

This issue wasn't simple to discover the answer two because I couldn't find any documentation on the `createTable`/`addColumn` migration methods or how references/associations/foreign keys work in migrations.

**Comment by janmeier** [comment]
The change does affect migration, since migrations use sequelize. So a migration that uses `referencesKey` will not be supported by 4.0 when that comes out

**Comment by dantman** [comment]
Then what is the correct signature of a migration that defines a foreign key reference to another table?

**Comment by janmeier** [comment]
`references: { model: 'SomeModel', key: 'some_key' }}` (model can be a string or a model-reference)
