### ISSUE TITLE
Association dependency in include where clause

### ISSUE THREAD

**Issue by Verdier** [sequelize/sequelize#4050]
I've searched the doc for a while, but I couldn't find a solution for the following:
```javascript
User.findAll({
 include: [{
  model: Project

  // My `where` clause is user dependent...
  where: { createdAt: { $gt: 'user.customUserDate' } } 
 }]
});
```
Is there any solution in today sequelize version ?

**Comment by mickhansen** [comment]
If it's user dependent you can just add it to the main where (since that's the user table)?

**Comment by Verdier** [comment]
No, not sure. In my real exemple, I want the following:
```SQL
SELECT users.*
FROM users, operations
WHERE users.id = operations.id
      AND operations."createdAt" >= users."receivedLastOperationNotificationAt";
```
something like that (with an inner join).

**Comment by mickhansen** [comment]
Ah, yeah we don't support that. You want a combination of https://github.com/sequelize/sequelize/issues/3095 and being able to refer to other fields.

**Comment by janmeier** [comment]
What about  `$gt: sequelize.col('user.customUserDate') }` ?

**Comment by Verdier** [comment]
@janmeier thanks, sound's good! I'll try.

**Comment by janmeier** [comment]
It will place the where on the join as opposed to on the outer query (which is what #3095 talks about), but in your case I don't think that's a problem

**Comment by Verdier** [comment]
That works perfectly, thanks!

2015-07-02 15:16 GMT+02:00 Jan Aagaard Meier <notifications@github.com>:
