### ISSUE TITLE
(bleedingly new) postgis GEOMETRY doesn't support srid

### ISSUE THREAD

**Issue by igrayson** [sequelize/sequelize#4054]
Mostly @mikeringrose.

PR https://github.com/sequelize/sequelize/pull/4013 added `GEOMETRY` support, but its srid handling may have some issues.

1. There's a typo in building `ST_GeomFromGeoJSON` sql, when an srid is present in the field def, causing invalid SQL (example: `ST_GeomFromGeoJSON('{"type":"Point","coordinates":[39.807222,-76.984722]}NaN')`. The issue is the second `+` on https://github.com/sequelize/sequelize/blob/56dbddde6739ecdad049881ae0a63e0f955fcf41/lib/dialects/postgres/query-generator.js#L903.

2. PostGIS' implementation of `ST_GeomFromGeoJSON` doesn't seem to support srid input at all. Neither source nor documentation mention accepting a second (srid) argument. Sequelize output is: `SequelizeDatabaseError: function st_geomfromgeojson(unknown, integer) does not exist`. (mysql `ST_GeomFromGeoJSON` does, fwiw).

**Comment by mikeringrose** [comment]
Thanks. I'll take a look. Obviously I'm also missing a test case. 😠

**Comment by mikeringrose** [comment]
Since our representation is geojson, the coordinate reference system is specified by the 'crs' field, like `{ type: 'Point', coordinates: [39.807222,-76.984722], crs:{ type: 'name', properties : { name: 'EPSG:3857'}}};`. I'll remove the srid from the ST_GeomFromGeoJSON call as 1) postgis doesn't support it and 2) postgis expects it to be specified in the geojson object.

**Comment by krisr** [comment]
@mikeringrose, thanks - I agree removing it is best. I first played around with something like this, but I don't know enough about postgis / gis to feel comfortable with this type of change:

    			if (field.type.srid) {
				s = "ST_SetSRID(" + s + "," + field.type.srid + ")";
			}

I agree it is better to leave it up to the user to specify the crs field in the JSON.

**Comment by igrayson** [comment]
Looks good.

Declaring my column type as `type: DataTypes.GEOMETRY('Point')`, and inserting point values as
```
{
      type: 'Point',
      coordinates: [ lat, long ],
      crs: { type: 'name', properties: { name: 'EPSG:4326'} }
    }
```
works as expected.
