### ISSUE TITLE
Strange bug on promise resolve

### ISSUE THREAD

**Issue by theo-ptz** [sequelize/sequelize#4060]
i'm currently on 3.3 version (node@0.10.38)

getting client by email
```
db.models.client.findOne({
    where: {
        email: email
    },
    attributes: ['id', 'email']
}).then(function (user) {
    console.log(user);
    if (!user) {
        return next();
    }

    next(new Error('EMAIL_USED'));
}, function (err) {
    next(err);
});
````

In console i've got global object instead user instance.

```
{
	...
    GLOBAL: [Circular],
    root: [Circular],
	setTimeout: [Function],
	setInterval: [Function],
	clearTimeout: [Function],
	clearInterval: [Function],
	setImmediate: [Function],
	clearImmediate: [Function],
	...
}
```

In log i see correct sql request:
``
Executing (default): SELECT `id`, `email` FROM `client` AS `client` WHERE `client`.`email` = 'test1435952380854@example.com' LIMIT 1;
``

i've added breakpoint in ``lib/dialects/mysql/query.js`` at line 37 (method.run) and have got correct result there.

```
var promise = new Utils.Promise(function(resolve, reject) {
    self.connection.query(self.sql, function(err, results) {
      if (err) {
        err.sql = sql;

        reject(self.formatError(err));
      } else {
      	debugger;
        resolve(self.formatResults(results));
      }
    }).setMaxListeners(100);
  });
```

what can modify and replace this values?

**Comment by janmeier** [comment]
I've never seen anything like this before, and I can't replicate with the code you posted.

Can you provide a full self-contained example (including model defs.), perhaps as a PR?

**Comment by janmeier** [comment]
Closing, no response
