### ISSUE TITLE
Is there a way to use the regex operator?

### ISSUE THREAD

**Issue by bishtawi** [sequelize/sequelize#4061]
Postgres supports the regex operator (~ and ~*). Is there anyway to use it? I need to select some data based off of a regex expression.

Id even be fine with the SIMILAR TO operator. I just know that in postres, the ~ operator is recommended as SIMILAR TO expressions are converted internally to full regex.

**Comment by alexmatveev** [comment]
+1

**Comment by hsubra89** [comment]
+1

**Comment by smolyakoff** [comment]
+1

**Comment by xb1itz** [comment]
+1

**Comment by suricactus** [comment]
+1

**Comment by AlexDar** [comment]
+1

**Comment by robertsonmcclure** [comment]
+1

**Comment by luongvo** [comment]
👍

**Comment by felixfbecker** [comment]
@AlexanderMatveev @hsubra89 @smolyakoff @xb1itz @suricactus @AlexDar @robertsonmcclure @luongvo 
![image](https://cloud.githubusercontent.com/assets/10532611/17959242/68d1e6a6-6a9f-11e6-82b6-b6623c1c8d6a.png)

**Comment by AlexDar** [comment]
Why am I tagged in this @felixfbecker ?

**Comment by felixfbecker** [comment]
Because you were one of the people that posted +1. It clutters the thread, I just cleaned up :)

**Comment by samelliott89** [comment]
+1 please and thank you :)

**Comment by harlentan** [comment]
+1  👍  Thank you :)

**Comment by felixfbecker** [comment]
This was added in https://github.com/sequelize/sequelize/pull/7855

**Comment by sushantdhiman** [comment]
Nice
