### ISSUE TITLE
Scope API usability improvement.

### ISSUE THREAD

**Issue by oracal** [sequelize/sequelize#4067]
I come from a rails background where scopes are just methods on the Model class or on instances of the model, which seems very clean.

Currently when using scopes in sequelize you need to use the `scope` method on the Model class.

Say we use the example from the docs on the Project model:

```
scopes: {
    deleted: {
      where: {
        deleted: true
      }
    }
```

To use this we need to call:

```
Project.scope('deleted').finalAll();
```

Would it be possible to change this so that scopes automatically get added as class methods?

So we can do this: 

```
Project.deleted().finalAll();
```

This would especially be nice when passing in arguments, using another example from the docs:

```
accessLevel: function (value) {
      return {
        where: {
          accessLevel: {
            $gte: value
          }
        }
      }
    }
```

Currently we need to call `Project.scope({ method: ['accessLevel', 19]}).findAll();`

If we added scopes as class methods this could look like `Project.accessLevel(19).finalAll();`

And chaining would just work as it currently does:

```
Project.deleted().accessLevel(19).findAll();
```

Which I find much cleaner than:

```
Project.scope('deleted', { method: ['accessLevel', 19]}).finalAll();
```

The only issue I can think of is method name conflict, but I don't think it is a huge issue.

I was just wondering if there was specific reason this wasn't done? And if not then I might look at creating a PR.

**Comment by janmeier** [comment]
I think that would be a nice addition, and off the top of my head I don't think this would cause any issues. 

A PR would be welcome! :)

**Comment by janmeier** [comment]
If you have the time, this would be a good time to add an `addScope` function as well, which allows you to define scopes after a model has beeen defined

https://github.com/sequelize/sequelize/issues/3963
