### ISSUE TITLE
Question: Trigger at timeout

### ISSUE THREAD

**Issue by brunano21** [sequelize/sequelize#4068]
Hi, 
I wonder if it's possible to create a trigger that triggers once a certain timeout has expired.
This would be useful for me for refreshing a table.
Thanks

**Comment by mickhansen** [comment]
That doesn't sound a lot like a Sequelize question.
You might want to look at bluebird's Promise.delay

**Comment by brunano21** [comment]
Sorry, maybe I was not using the correct words. I meant if it's possibile to trigger a query every time that a timeout expires, not just a one-time query.

**Comment by mickhansen** [comment]
@brunano21 We don't have type of support for what you're looking for. You could just run a script with `setInterval` or setup a cronjob.

**Comment by brunano21** [comment]
Yeah, maybe it's the best option. However, thanks a lot!
