### ISSUE TITLE
Using MySQL date format function

### ISSUE THREAD

**Issue by DjebbZ** [sequelize/sequelize#407]
Hi

When querying a model, I'd like to retrieve the `created_at`/`updated_at` field as a unix timestamp. MySQL supports this through a date function, but how to do that with sequelize ?

**Comment by laratutoteam** [comment]
[✅✅ SOLVED DATE FORMAT ONLY QUERY✅✅](https://laratuto.com/date-format-in-mysql/)

**Comment by laratutoteam** [comment]
Date format in mysql to use when seeing or editing new rows in the database https://laratuto.com/date-format-in-mysql/
