### ISSUE TITLE
Passport deserializeUser() and Instance.set[Model]()

### ISSUE THREAD

**Issue by mtrunt** [sequelize/sequelize#4070]
Hi,

I've picked up Passport and Sequelize recently and I'm having some strange behavior when trying to assign a User to a Place (models).

I have the usual Passport deserializeUser method

    passport.deserializeUser(function(id, done) {
      User.findById(id)
        .then(function(user) {
          done(null, user);
        })
        .catch(function(err) {
          done(err, false);
        });
    });

And a method that assigns a User to a Place (only the relevant parts)

    Place.findOne({
        where: {
          mapPosition: req.body.location
        }
      })
      .then(function(place) {
         if (place) {
           return Promise.reject(new Error('Place already exists'));
         }

         return Place.create({
             'name': req.body.name,
             'mapPosition': req.body.location,
             'address': req.body.address,
             'price': req.body.price,
           })
           .then(function(place) {
             place.setUser(req.user);
           })
         })

But whenever I try to set the User I get this error

    Executing (default): UPDATE "Places" SET "UserId"=`dataValues` = '[object Object]', `_previousDataValues` = '[object Object]', `_changed` = '[object Object]', `__options` = '[object Object]', `options` = '[object Object]', `hasPrimaryKeys` = true, `__eagerlyLoadedAssociations` = , `isNewRecord` = false, `_customGetters` = '[object Object]', `_customSetters` = '[object Object]', `validators` = '[object Object]', `_hasCustomGetters` = 0, `_hasCustomSetters` = 2, `rawAttributes` = '[object Object]', `attributes` = 'id', 'username', 'email', 'password', 'firstname', 'lastname', 'createdAt', 'updatedAt', 'AccountId', `Model` = '[object SequelizeModel:User]', `$Model` = '[object SequelizeModel:User]',"updatedAt"='2015-07-07 03:36:33.494 +00:00' WHERE "id" = 31
    Unhandled rejection SequelizeDatabaseError: syntax error at or near "=`"
    at Query.formatError (c:\projects\adventure-time\node_modules\sequelize\lib\dialects\postgres\query.js:420:14)
    at null.<anonymous> (c:\projects\adventure-time\node_modules\sequelize\lib\dialects\postgres\query.js:104:19)
    at emit (events.js:107:17)
    at Query.handleError (c:\projects\adventure-time\node_modules\pg\lib\query.js:99:8)
    at null.<anonymous> (c:\projects\adventure-time\node_modules\pg\lib\client.js:166:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (c:\projects\adventure-time\node_modules\pg\lib\connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

If I try to set the user as this it works

    Place.findOne({
      where: {
        mapPosition: req.body.location
      }
    })
    .then(function(place) {
      if (place) {
        return Promise.reject(new Error('Place already exists'));
      }
  
      return Place.create({
        'name': req.body.name,
        'mapPosition': req.body.location,
        'address': req.body.address,
        'price': req.body.price,
      })
    })
    .then(function(place) {
      return User.findOne({
        where: {
          id: 2
        }
      })
      .then(function(user) {
        place.setUser(user);
      })
    }

I've also tried `req.user.equals(user)` and it's returning `true`.

Is there anything I'm missing?

Thanks

Edit: Using version 3.3.2

**Comment by mickhansen** [comment]
Can you try `req.user instanceof User.Instance`? Passport might be mucking about with something.

**Comment by mtrunt** [comment]
So it looks like it's a Passport thing as `req.user instanceof User.Instance` returns `false`.
Thanks for the fast reply!

**Comment by janmeier** [comment]
Hmm, weird ...

You can pass the userId directly to `setUser` instead

**Comment by mtrunt** [comment]
I guess I'll use that instead. Thanks for the help!

Closing as it's not Sequelize related.
