### ISSUE TITLE
Create operation for associated models fails when foreignKey is allowNull=false;

### ISSUE THREAD

**Issue by ivanjd** [sequelize/sequelize#4071]
This opperation:

``` javascript
Company.create(companyObject, { include: [addressAssociation]} );
```

Fails with:

```
SequelizeValidationError: notNull Violation: businessAddressId cannot be null
```

companyObject.BusinessAddress is properly set. The SQL queries are perfect. First the address is inserted and then the company with the correct addressId as a foreign key. If the allowNull option is not set to false the call works (and the NOT NULL database constraint is satisfied), otherwise I get a sequelize validation error. 

Here is the association

``` javascript
Company.belongsTo(models.Address, {
                    as: 'BusinessAddress',
                    foreignKey: {
                        name: 'businessAddressId',
                        allowNull: false,
                    }
                });
```

Is there a workaround. I can create the nested models first and then manually set the foreign key, but it is much more convenient if I can do it in a single call.

**Comment by janmeier** [comment]
Please show model definitions and the actual data you are putting into `Company.create`

**Comment by mickhansen** [comment]
@janmeier It's a bug with nested creation, we run validations before we do nested creation so if you have not null on a foreign key nested creation will pretty much always fail.

**Comment by ivanjd** [comment]
Thanks. I have a workaround in the form of a "plugin" which enables an option called allowNullDb=false. It overrides the sync function for the model to manually adds NOT NULL constraints for all foreign keys marked with this option. That way sequelize validation succeeds, and I am still protected by the database constraints:

```javascript

module.exports = function (Sequelize) {
	Sequelize.addHook('afterInit', function (sequelize) {
		sequelize.addHook('afterDefine', function (model) {

			let query = '';
			for(let attribute in model.attributes){
				let attribObject = model.attributes[attribute];
				if(attribObject.allowNullDb===false)
					query+= 'ALTER TABLE "'+model.tableName+'" ALTER COLUMN "'+
						attribObject.fieldName+'" SET NOT NULL; ';
			}

			if(query.length>0)
				model.sync = function () {
					return model.sequelize.Model.prototype.sync.apply(this, arguments)
						.then(function (val) {
							return model.sequelize.query(query);
						});
				}
		});
	});
}
```

Is there a better way to do it, or do you guys know if the bug is being worked on?

**Comment by mickhansen** [comment]
Not being worked out, haven't come up with a good way to solve this yet.

**Comment by jadbox** [comment]
+1 in needing this fixed :/
