### ISSUE TITLE
[Question] Avoid "updatedAt" update?

### ISSUE THREAD

**Issue by tolleiv** [sequelize/sequelize#4073]
Hi,

I do have some meta data fields which are updated by a background process and I'd prefer to not update the "updatedAt" field in some cases where only meta-data is written.
So is there a way / hook to skip that behaviour in some cases?

Cheers

**Comment by mickhansen** [comment]
You should be able to use `{silent: false}` as an option.

**Comment by tolleiv** [comment]
Thank you
