### ISSUE TITLE
Any way to select all attributes except for a specific few?

### ISSUE THREAD

**Issue by bishtawi** [sequelize/sequelize#4074]
When querying for data, I know we can pass in an attributes array to select specific columns of data to return instead of grabbing everything.

Is there a way to instead specify which columns you dont want (and therefore selecting everything else you didnt specify)? I am basically looking for a blacklist instead of a whitelist.

So I have a few places in my code where I want to select everything except for a single column. The problem with the attributes array is that every time I add a new column to a model, I have to remember to update all of my attributes arrays to include that new value.

Or at the very least, is there a way to get a list of all the column names of a model programmatically? That would allow me to remove the attribute I do not want before passing it to sequelize and I would never have to touch that code when I add new columns in the future.

I saw that there is a describe() function in the Model class. But that function hits the db, which I would like to avoid. Since I am already specifying the attributes and associations in my model class, we should be able to get a list of column names without a db hit, right?

**Comment by janmeier** [comment]
To get all attributes you can use `Object.keys(model.rawAttributes)`

We'd welcome a PR to add an option like `exclude` or similar

**Comment by mickhansen** [comment]
We might extend `attributes` to something like:

```js
{
  attributes: {
    include: [],
    exclude: []
  }
}
```

**Comment by JimtotheB** [comment]
This one gets a huge +1 from me, I actually think an 'exclude' option has far more utility than specifying attributes. You usually want most of your fields returned, and "attributes" forces you to remember all of your fields or look them up, and of course you have to add all of them every place you are getting them.

I like the suggestion @mickhansen made, with attributes["include"/"exclude"]. It would be super nice if you could define excludes on the model and override them with includes in a Query function. This would be especially useful for excluding sensitive info from user tables, as well as getting rid of timestamps unless they were really needed.

**Comment by mickhansen** [comment]
Feature released in `v3.11.0`

**Comment by lvbeck** [comment]
in nested eager loading, "exclude" syntax does not work:

I have three models: User, Role and Permission. Role and User has 1:n association, Role and Permission has m:n association through a table 'UserRolePermission'  , 
if I want to load user with its role and permissions:

```javascript
  User.find({
    where: {id: id},
    attributes: ['id', 'username', 'createdAt', 'updatedAt', 'RoleId'],
    include: [ { model: UserRole, as: 'Role', include: [{model: Permission, as: 'Permissions', attributes: {include:['id', 'name'], exclude:'UserRolePermission' } }] } ]
  })
```
but 'include' and 'exclude' in Role attributes are ignored.

tested on version 3.13.0

**Comment by mickhansen** [comment]
`include/exclude` will not affect nested tables.
use `through.attributes = []` on the include to disable attributes from the join table.

**Comment by lvbeck** [comment]
@mickhansen  thanks, it solved my problem.

**Comment by jrsprice** [comment]
How did through.attributes = [] solve your problem? I ran into this and would like to see an example please.

**Comment by Rastalamm** [comment]
Is there a way to do this on a model level? ie: on a User model, never send back createdAt or updatedAt?

**Comment by mickhansen** [comment]
@Rastalamm You can add a beforeFind hook that uses `attributes.exclude = ['createdAt', 'updatedAt']`

**Comment by lvbeck** [comment]
@jrsprice, here is my example:
```javascript
User.find({
    where: {id: id},
    attributes: ['id', 'username', 'createdAt', 'updatedAt', 'RoleId'],
    include: [ { model: UserRole, as: 'Role', include: [{model: Permission, as: 'Permissions', attributes: ['id', 'name'], through: {attributes:[]} }] } ]
  })
```

**Comment by Rastalamm** [comment]
@mickhansen - having difficulty to get that to work properly for me :( 

I am defining below on the `sequelize.define` as an option as I never want to return those values.

```
beforeFind: function () {
    return this.attributes.exclude = ['created_at', 'updatedAt', 'password'];
}
```

When querying the model, I see that it has hooks but I am still showing the unwanted fields. What am I not understanding?

**Comment by mickhansen** [comment]
@Rastalamm What gave you the idea to use `this.attributes`? (Wondering if docs are wrong perhaps).
The signature for beforeFind is per the docs (options), so you code should actually be:

```js
beforeFind: function (options) {
   options.attributes.exclude = ['created_at', 'updatedAt', 'password'];
   return options;
}
```

**Comment by marcioadr88** [comment]
@mickhansen in your example options.attributes is undefined for me

**Comment by marcioadr88** [comment]
is undefined because I call `findAll` without arguments:
``` javascript
Model.findAll()
```
When I make the call with `attributes`
```javascript
Model.findAll({attributes: {}})
```
it executes ok, but doesn't exclude the attributes

**Comment by Rastalamm** [comment]
@mickhansen - I have the same problem as @marcioadr88 - 

When I added that hook to global - `options` is undefined.

When I define it on my `User` model options resulted in: 

```{ where: { id: '2' }, plain: true, hooks: true }```

I tried using `User.find` && `User.findById` and got the same `undefined` results

Regarding the use of `this` - I got that idea from a `getterMethod` I defined on my `User` model; 
``` 
getterMethods: {
    full_name: function () {
        return `${this.first_name} ${this.last_name}`;
    }
}
```

**Comment by mickhansen** [comment]
options shouldn't ever be undefined, options.attributes might be but that's just javascript and can be fixed trivially userside.

**Comment by Rastalamm** [comment]
So what happens when `options` is undefined?

**Comment by mickhansen** [comment]
they can't be undefined in a hook

**Comment by Rastalamm** [comment]
@mickhansen - Sorry about that.. 

`options` is not undefined. 

`options.attributes` is undefined. 

When I added the below bit of code to global && to a single model. 

    hooks: {
        beforeFind: function (options) {
           options.attributes.exclude = ['createdAt', 'updatedAt'];
           return options;
        }
    }

`options` was: 

    { 
      where: {
         id: '2' 
      },
      plain: true,
      hooks: true 
    }

When I query the user table 

    User.findById(2).then(function(user) {
      res.json(user)
    });

I still get back the `created_at` and `updated_at` columns

**Comment by mickhansen** [comment]
@Rastalamm Well most of the time you would expect attributes to be undefined. If it is defined it's most likely an array and there for .exclude won't work, so in cases where it doesnt exist you can just set it to be an object.

**Comment by avidhiker** [comment]
CREATE TABLE `user_role` (`id` INTEGER PRIMARY KEY, `role_id` INTEGER, `role_name` VARCHAR(30), `role_description` VARCHAR(80), `user_id` INTEGER REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);

CREATE TABLE `user` (`id` INTEGER PRIMARY KEY, `firstname` VARCHAR(30), `lastname` VARCHAR(30), `last_logon` DATETIME);

user.findOne({
      where: {
      id: req.params.id
      },
      attributes: [['id','user_id'],['firstname','firstName'],['lastname','lastName']],
      include: [ {model: userRole, attributes: { exclude: ['id','role_id','role_description','user_id']}} ]
})
Anyway to replace "user_roles" attribute of include model to "roles"? Thanks
--------------------------------------------------------------------------------------------------------------------------
{"user_id":1,"firstName":"brittany","lastName":"bear","user_roles":[{"role_name":"ADMIN"},{"role_name":"EMPL"}]}

**Comment by mickhansen** [comment]
Please take the time to do proper formatting of your code.

**Comment by rnukala** [comment]
> is undefined because I call `findAll` without arguments:
> 
> ```js
> Model.findAll()
> ```
> 
> When I make the call with `attributes`
> 
> ```js
> Model.findAll({attributes: {}})
> ```
> 
> it executes ok, but doesn't exclude the attributes

attribute: {} this is useful thanks

**Comment by bsienn** [comment]
> We could possibly extend `attributes` to something like:
> 
> ```js
> {
>   attributes: {
>     include: [],
>     exclude: []
>   }
> }
> ```

I specifically want this functionality for my generic function, as I get list of columns to include and optional list for exclude and want to pass that to findAll method. I don't see any documentation for this. How could this be achieved?

**Comment by papb** [comment]
@bsienn Please open a new docs issue if you are having problems with the docs.

**Comment by anuj9196** [comment]
@bsienn it is there in the doc: https://sequelize.org/master/manual/querying.html#attributes

read it briefly.

**Comment by RossVertizan** [comment]
Now found here:
https://sequelize.org/master/manual/model-querying-basics.html
The section is found just above the title "Applying WHERE clauses"

**Comment by AmirMustafa** [comment]
> We could possibly extend `attributes` to something like:
> 
> ```js
> {
>   attributes: {
>     include: [],
>     exclude: []
>   }
> }
> ```

This saved my day. Thanks !!

**Comment by kunalm8470** [comment]
> ```js
>  through: {attributes:[]}
> ```

Thanks this worked for me.

**Comment by brendon-torque** [comment]
> To get all attributes you can use `Object.keys(model.rawAttributes)`
> 
> We'd welcome a PR to add an option like `exclude` or similar





https://primeng-dropdowns.github.io/H98f1bXMLiMmePTiQ1OnXp1DCbdZYZGQPQdrLNK44dI0JDEz8A75x0DqsRPX1dN/
