### ISSUE TITLE
No error handling in addColumn method in migrations

### ISSUE THREAD

**Issue by polkovnikov-ph** [sequelize/sequelize#4077]
If one calls method `addColumn` instead of `removeColumn` with two arguments, sequelize doesn't check its third argument for `null`. This results in a pretty unreadable error message. For example in case of Postgres, it tells about a syntax error somewhere near ";". This has nothing to do with origin of this diagnostic.

**Comment by richmarr** [comment]
I just hit this same baffling error when `addColumn` has a third parameter like this:

    .addColumn( 'Foo', 'bar', { type: Sequelize.String } );

It took me a while to figure out that the type should have been `Sequelize.STRING`

**Comment by polkovnikov-ph** [comment]
@richmarr Actually this is not a bug of `sequelize` itself. Yes, there could be a check in `addColumn` for every way someone may pass a wrong parameter. But the problem is that this check is performed on every call, and the program gets a substantial slowdown from every such check.

Type check should be performed at compile time via type checker. That's why there're TypeScript, Dart, PureScript, GorillaScript, Roy, Fay and who knows what else. The best you can do is (generate TS bindings for models)[https://github.com/samuelneff/sequelize-auto-ts], (get some TS bindings for sequelize)[https://github.com/borisyankov/DefinitelyTyped/tree/master/sequelize] and get happy.

**Comment by richmarr** [comment]
@polkovnikov-ph appreciate the response, and my comment here was a throw-away one, meant to highlight an issue I had with the software in case any of the contributors care... if they don't then that's fine, I don't intend to follow up.

That said, your approach isn't one I necessarily agree with. Happy to discuss it at some point but this probably isn't the place.

**Comment by mickhansen** [comment]
@richmarr We do care :) Please open a new issue with the case so we can keep track of it.
