### ISSUE TITLE
Selecting attributes from json objects

### ISSUE THREAD

**Issue by marcingasior** [sequelize/sequelize#4078]
Hi Guys, 

I have a question about selecting attributes from json object.
My model looks like :

var Article = sequelize.define("article", {
        id: {
            type: Sequelize.UUID,
            defaultValue: Sequelize.UUIDV4,
            primaryKey: true,
            allowNull: false
        },
        data: { type: Sequelize.JSON }
    });
data contains article metadata and content, so for certain calls, I want to get only subset of data,

sequelize.sync().then(function() {
    return Article.findOne({
        attributes: ["data->'title'"], //Sequelize.json({data: 'title'})
        where: {id : "357df276-1bc6-4d77-a476-347a527524d0"}

    });
}).then(function(dao) {
    console.log(dao.get({
        plain: true
    }))
});

Unfortunately I cannot make it working.
I got following sql 
1)
 SELECT "data->'article_type'" FROM "articles" AS "article" WHERE "article"."id" = '357df276-1bc6-4d77-a476-347a527524d0';

2) commented out 
 SELECT data#>>'{}' = 'title' FROM "articles" AS "article" WHERE "article"."id" = '357df276-1bc6-4d77-a476-347a527524d0';

What I am looking for is
 SELECT data->'article_type' FROM "articles" AS "article" WHERE "article"."id" = '357df276-1bc6-4d77-a476-347a527524d0';

Can you help me with this?

**Comment by mickhansen** [comment]
Please make the effort to format your post so we can read your code properly.
You'll likely have to provide a virtual property for the target values, and you should then be able to use something like:

```
attributes: [
  [sequelize.json('data.title'), 'alias']
]
```

**Comment by janmeier** [comment]
Closing, no response

**Comment by evenfrost** [comment]
How can one select and get specific JSON attributes without aliasing, as is? E.g. running this:
```js
AEntity.findAll({ attributes: [[sequelize.json("aStruct.id"), "aStruct.id"]] });
```
and getting in the result
```js
[{
  aStruct: {
    id: 123
  }
}]
```
instead of
```js
[{
  "aStruct.id": 123
}]
