### ISSUE TITLE
Proposal: move Validator with it's extends to own file

### ISSUE THREAD

**Issue by gustavpursche** [sequelize/sequelize#4085]
Just a short question, before starting a pull request: what do you think about moving all the Validator.extend() related stuff in [instance-validator.js](https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js) to it's own file (validator-extends.js), so it can be imported from the outside world?

**Comment by mickhansen** [comment]
Sure, i see no reason why not.
Probably put it in util/ though.
