### ISSUE TITLE
Differences on addXXXX on v3.2.0 and 3.3.2

### ISSUE THREAD

**Issue by GTTo** [sequelize/sequelize#4090]
V3.2.0
```js
  obj[this.accessors.addMultiple] = obj[this.accessors.add] = function(newInstance, options) {
    // If newInstance is null or undefined, no-op
    if (!newInstance) return Utils.Promise.resolve();

    var instance = this
      , primaryKeyAttribute = association.target.primaryKeyAttribute;

    options = options || {};

    if (Array.isArray(newInstance)) {
      var newInstances = newInstance.map(function(newInstance) {
        if (!(newInstance instanceof association.target.Instance)) {
          var tmpInstance = {};
          tmpInstance[primaryKeyAttribute] = newInstance;
          return association.target.build(tmpInstance, {
            isNewRecord: false
          });
        }
        return newInstance;
      });

      return new HasManySingleLinked(association, this).injectSetter([], newInstances, options);
    } else {
      if (!(newInstance instanceof association.target.Instance)) {
        var values = {};
        values[primaryKeyAttribute] = newInstance;
        newInstance = association.target.build(values, {
          isNewRecord: false
        });
      }

      return instance[association.accessors.get]({
        where: newInstance.where(),
        scope: false,
        transaction: options.transaction,
        logging: options.logging
      }).bind(this).then(function(currentAssociatedObjects) {
        if (currentAssociatedObjects.length === 0) {
          newInstance.set(association.identifier, instance.get(instance.Model.primaryKeyAttribute));

          if (association.scope) {
            Object.keys(association.scope).forEach(function (attribute) {
              newInstance.set(attribute, association.scope[attribute]);
            });
          }

          return newInstance.save(options);
        } else {
          return Utils.Promise.resolve(currentAssociatedObjects[0]);
        }
      });
    }
  };
```

V3.3.2
```js
  obj[this.accessors.addMultiple] = obj[this.accessors.add] = function(newInstances, options) {
    // If newInstance is null or undefined, no-op
    if (!newInstances) return Utils.Promise.resolve();
    options = options || {};

    var instance = this, update = {}, where = {};

    newInstances = association.toInstanceArray(newInstances);

    update[association.identifier] = instance.get(association.source.primaryKeyAttribute);
    _.assign(update, association.scope);

    where[association.target.primaryKeyAttribute] = newInstances.map(function (unassociatedObject) {
      return unassociatedObject.get(association.target.primaryKeyAttribute);
    });

    return association.target.unscoped().update(
      update,
      _.defaults({
        where: where
      }, options)
    ).return(instance);
 };
``` 

When I use de method addXXX over an instance, when the object is not persisted, on the V3.3.2 is sending an UPDATE despite of an INSERT as in the V3.2.0

Thanks

**Comment by janmeier** [comment]
Can you please post some example code that shows the issue, instead of sequelize code :)?

**Comment by mickhansen** [comment]
@GTTo Are you trying to add an unpersisted instance via an association adder? That has never officially been supported.

**Comment by GTTo** [comment]
Hello @janmeier 
I'm trying to add an Object to an a collection in another object who has an 'hasMany' association.
This is the code:

var User = sequelize.define('user', {
		firstName: {
			type: Sequelize.STRING,
			field: 'first_name' // Will result in an attribute that is firstName when user facing but first_name in the database
		},
		lastName: {
			type: Sequelize.STRING
		}
	}, {
			freezeTableName: true // Model tableName will be the same as the model name
		})
	var Project = sequelize.define('project', {
		title: Sequelize.STRING,
		description: Sequelize.STRING
	})

	Project.hasMany(User);
	Project.findById(1).then(function (project) {
		var user = User.build();
		console.log(user);
		project.addUser(
			user
			);
		//User.create({projectId:project.id});

	});

In version V3.2.0 the addUser method send 2 queries:
-SELECT ... FROM user WHERE projectId = ? AND id IS NULL
-INSERT INTO user....

This read is not necessary... because always returns 0 rows.

In version V 3.3.2 the addUser method sends only one query:
 - UPDATE user  SET projectId = ?, .... WHERE id IN <NULL>

The addUser method don't have to send an UPDATE in this case...
Why this "extrange" behaviours?

Thanks

**Comment by mickhansen** [comment]
Like i just commented, `var user = User.build();` has never been officially supported.
The reason it worked previously was because the code used instance.save() rather than a bulk update.

As for your comment that the read is not necessary, there's no way for sequelize to know that ahead of time.

When using addAssociation you need to use a persisted instance or use an id.

**Comment by GTTo** [comment]
I think that this way of make updates/inserts is not appropiated in my point of view.

Thanks

**Comment by mickhansen** [comment]
I'm not sure i understand what you mean.
The bulk update query works both for adding one or more association instances, no difference, just easier to maintain code and better performance.

**Comment by janmeier** [comment]
You can use `Project.createUser`

**Comment by GTTo** [comment]
@janmeier Project.createUser inserts a new register in User table, but don't associate the user to project (the field projectId is inserted null)

**Comment by janmeier** [comment]
@GTTo I doubt that is the case - please show an example?

**Comment by GTTo** [comment]
@mickhansen I try to explain it better.
When I want to add an object to a collection, sequelize is forcing me to:
 - create the foreign key as a nullable
 - Insert the dependent object
 - update the collection via 'addXXX' method
And all of this inside a transacction!

I think it's more efficient to make an insert on the 'addXXX' method in a 'hasMany' association.

**Comment by mickhansen** [comment]
How do we force you to create the foreign key as nullable? I use similar constructs and non of my foreign keys allow null.
If the object you are attempting to add does not exist yet, use `createAssociation` as suggested previously.

**Comment by GTTo** [comment]
@janmeier 
When I  get the project and I createUser 
```js
Project.findById(1).then(function (project) {
	var user = User.build();
	project.createUser(user);
});
```
This sentences are thrown:

Executing (default): SELECT "id", "title", "description", "createdAt", "updatedAt" FROM "projects" AS "project" WHERE "project"."id" = 1 LIMIT 1;
Executing (default): UPDATE "user" SET "projectId"=1,"updatedAt"='2015-07-10 11:56:12.327 +00:00' WHERE "id" IN (NULL)
Executing (default): INSERT INTO "user" ("id","updatedAt","createdAt") VALUES (DEFAULT,'2015-07-10 11:56:12.334 +00:00','2015-07-10 11:56:12.334 +00:00') RETURNING *;

**Comment by janmeier** [comment]
You don't to pass a user object, just pass the raw user data e.g. `project.createUser({ name: 'bob' })`

**Comment by GTTo** [comment]
Ok, this works!
But, I'm a bit confused with the param recived in createUser.
I think this would be the User object instance, not a plain JSON :/
Thanks!!

**Comment by mickhansen** [comment]
@GTTo It's a set of values like you would pass to `Model.create()`.

**Comment by janmeier** [comment]
If you mean the result you get from `.createUser().then(function (user)`, then you will indeed get a user instance in the callback

**Comment by GTTo** [comment]
@mickhansen Ok, I try in this way
Thanks!

**Comment by GTTo** [comment]
@janmeier I'm talking about the object passed to ``.createUser(user)`` method.
Passing a set of values works for me.
Thank you!
