### ISSUE TITLE
Specify non-primary target key in belongsToMany association

### ISSUE THREAD

**Issue by drew-r** [sequelize/sequelize#4092]
Hi & thanks for the lib. 

I am trying to configure a many to many relationship through a joining model. 
I want to use non-primary string key fields on both models referenced by the join model.

I have tried defining the foreign keys manually against each model field... these are created but ignored, the relation creates its own keys referencing the PKs.
I have tried specifying them as the `foreignKey` and `otherKey`, but this results in the fields in the join table being overwritten as integer fields when they should be strings. 
I have also tried specifying a targetKey when calling `belongsToMany()` to no avail.

Is this intended behavior? 
Is what I am trying to achieve possible?

Thanks in advance

**Comment by mickhansen** [comment]
I'm afraid we only support primary keys in this scenario. We only allow defining foreign and other key to define the names of the attributes in the join table.

**Comment by TangMonk** [comment]
+1

**Comment by sirjmkitavi** [comment]
@mickhansen What is the status on specifying non-primary target key in belongsToMany association

**Comment by garrypolley** [comment]
If someone did the work, would it be desired/allowed to make a change so `belongsToMany` would allow non primary key relationships? 

For example I have models that have an `id` and a `uuid`.  We are in progress of updating to use `uuid`s in a lot of places. However, the original `id` is the primary key for now, and likely will stay as the "true" primary key. However, we have new tables that are joining via the `uuid`.  

I want to define a relationship for the `belongsToMany` in the following fashion for example: 

```js
 models.MyModelWithTwoPrimaryKeys.hasMany(models.throughModel, {
    foreignKey: 'twoPrimaryKeysUuuid',
    sourceKey: 'uuid',
    onDelete: 'NO ACTION',
    onUpdate: 'NO ACTION'
});

models.MyModelWithTwoPrimaryKeys.belongsToMany(models.relatedModel, {
    through: models.throughModel,
    foreignKey: 'twoPrimaryKeysUuuid',
    otherKey: 'relatedModelUuid',
    sourceKey: 'uuid', // right now this defaults to 'id' because it cannot be overridden
    onDelete: 'NO ACTION',
    onUpdate: 'NO ACTION'
});
```

https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L249-L256

Ideally I could also specify `targetKey` in the same way, to control the entire querying process.

**Comment by mouhamed** [comment]
Hello,

Fist, thanks for this wonderful lib. This issue is the one I'm now blocked with and it would be very nice if this could be merged in next release. Thanks to @garrypolley for implementation (I started to work on this and you alread did it)

**Comment by FrancescoVaiani** [comment]
Any ETA for integrating the @garrypolley's patch into the project?

**Comment by qpjoy** [comment]
+1

**Comment by nawlbergs** [comment]
I have the exact database scenario as @garrypolley.

I wish it was more like this:
```
// assuming these tables:
// userTable =   { id(primary), uid, ... }
// stuffTable = { id, ... }
// throughTable = { id, user_uid, stuff_id }

models.userTable.belongsToMany(models.stuffTable, {
   // define the fields on the two tables we are joining here:
   foreignKey:  'uid',  // userTable.uid
   otherKey:    'id',   // stuffTable.id
   through:      {
      // define the fields on the through table here:
      model: models.throughTable,
      foreignKey: 'user_uid',   // userTable.uid -> throughTable.user_uid
      otherKey:   'stuff_id'    // stuffTable.id -> throughTable.stuff_id
   }
});
```
I assumed this was possible because .hasOne supports it with the sourceKey.

**Comment by GauravGGTrilyo** [comment]
@garrypolley how to include your library? If I update my sequalize, it may work on local, but when I will push to my server, all the node-modules are reinstalled, and this code will be overwritten by node module from NPM.

**Comment by NaorZakk** [comment]
+1

**Comment by brianalois** [comment]
+1

**Comment by createthis** [comment]
+1 for adding `targetKey` support since #10469 was closed

**Comment by TakanashiOuken** [comment]
Is there any update on this issue? Or are there any walk arounds we can use so far?
