### ISSUE TITLE
Unable to delete model from table where id field renamed

### ISSUE THREAD

**Issue by atorkhov** [sequelize/sequelize#4096]
When I have renamed id field in table and then trying to delete the record from it, like in following script:

```
var Sequelize = require('sequelize');

var db_uri = "postgres://test:test@127.0.0.1/test";

var sequelize = new Sequelize(db_uri, {
    define: {
      underscored: true,
      timestamps: false
    }});

var Task = sequelize.define('Task', {
  id: { type: Sequelize.INTEGER, field: 'task_id', defaultValue: undefined },
  comment: { type: Sequelize.TEXT }
}, {
  tableName: 'tasks'
});

sequelize.query('DROP TABLE IF EXISTS tasks; DROP SEQUENCE IF EXISTS task_id_seq').then(function() {
  return sequelize.sync();
}).then(function() {
  return sequelize.query("CREATE SEQUENCE task_id_seq; ALTER TABLE tasks ALTER COLUMN task_id SET DEFAULT nextval('task_id_seq');");
}).then(function() {
  return Task.create({ comment: 'text' });
}).then(function(m) {
  return m.destroy();
}).then(function() {
  console.log('done');
});
```

I'm getting following error:

```
Executing (default): DELETE FROM "tasks" WHERE "id" IN (SELECT "id" FROM "tasks" WHERE "task_id" = 1 LIMIT 1)
Unhandled rejection SequelizeDatabaseError: column "id" does not exist
```

**Comment by janmeier** [comment]
This is because your id field is not marked as the primary key. When the model already has a field named id, seqeulize will just leave it be, and not do anything to it. 

Adding `primaryKey: true` to the field fixes the issue

**Comment by atorkhov** [comment]
Thanks, it worked with `primaryKey: true`.

**Comment by atorkhov** [comment]
May be sequelize should warn user that it didn't find proper primaryKey when deleting records?

**Comment by janmeier** [comment]
True, in your case that would have beeen nice. However, we have some cases where users explictly remove the primary key - so I'm not sure it could work in the general case.

However, we could argue that if the model has an id field but it is not marked as primaryKey, then we should throw an error - because that is 100% always an error. PR welcome :)
