### ISSUE TITLE
Postgresql updating array column result in ERROR:  missing dimension value

### ISSUE THREAD

**Issue by rbudiharso** [sequelize/sequelize#4100]
I have a column with type definition `Sequelize.ARRAY(Sequelize.STRING)`, when I want to update that column I get this error:

```
ERROR:  missing dimension value
```

the generated sql is (with exact quotes):

```
"UPDATE \"AccessTokens\" SET \"permissions\"='[\"user:create\",\"user:edit\",\"user:delete\",\"merchant:create\",\"merchant:delete\"]',\"updatedAt\"='2015-07-13 06:36:01.243 +00:00' WHERE \"id\" = 2339"
```

if I change to this sql (with exact quotes, single quote for the array value instead of double quotes) :
```
UPDATE "AccessTokens" SET "permissions" = ARRAY['user:create','user:edit','user:delete','merchant:create','merchant:delete'],"updatedAt"='2015-07-13 04:59:06.548 +00:00' WHERE "id" = 2339
```

and run that directly to psql, there is no error. By the way this is the code that triggers the error:

```javascript
instance.update({permissions: newPermissions})
```

where `permissions` is the column with type ARRAY and  `newPermissions` is just an array of strings.

**Comment by janmeier** [comment]
Which version of sequelize are you experiencing this on? Can you show the model definition?

The code you showed works fine for me on the latest version, the array is properly cast to `::VARCHAR[]`

**Comment by rbudiharso** [comment]
Sorry my bad, I change the column type from JSON to ARRAY with migration and forget to update the model definition, everything works now :)
