### ISSUE TITLE
bulkCreate does not understand timestamps renamed fields

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#4103]
Migration from 2.0.x to 3.x I have some issue with `bulkCreate`

> SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'

I have this

```javascript
{
        createdAt: {
            type: DataTypes.DATE,
            field: 'created_at'
        },
        updatedAt: {
            type: DataTypes.DATE,
            field: 'updated_at'
        },
        deletedAt: {
            type: DataTypes.DATE,
            field: 'deleted_at'
        }
}
```

and `timestamp` at `true` in my model definition

**Comment by JSteunou** [comment]
This is specific to timestamp fields. I test with a `fooBar` property in my model, having `foo_bar` in my table, no issue when I add `field: 'foo_bar'` in my model.

**Comment by JSteunou** [comment]
More tests... it's not only bulk operation, I have the issue on `Model#create` too.

**Comment by rfink** [comment]
With the "updateOnDuplicate" clause added, this also fails to recognized aliased fields.

**Comment by JSteunou** [comment]
Any news on this one?

**Comment by JSteunou** [comment]
@janmeier @mickhansen This issue is still present in 3.11, how can I help you to help me on this?
Is there a way around until this is fixed? This bug still prevent me to update from 2.x to 3.x.

**Comment by JSteunou** [comment]
`#create` dont have the issue anymore, so I could get around by doing an `Array#map` to call create multiple time. That does the trick for test case, but I would prefer rely on `bulkCreate` for production code, depending on what SQL optimisation it does underneath

**Comment by janmeier** [comment]
@JSteunou If you can create a pull request with failing tests that would maybe speed up things a bit.

Shouldn't be too much code required to actually do a fix either ;)

**Comment by JSteunou** [comment]
Ok I try to follow the doc and run test against mysql but got this

```
4 errors
Makefile:67: recipe for target 'jshint' failed
make[2]: *** [jshint] Error 2
make[2]: Leaving directory '/home/jerome/Git/sequelize'
Makefile:20: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/jerome/Git/sequelize'
Makefile:74: recipe for target 'mysql' failed
make: *** [mysql] Error 2
```

**Comment by JSteunou** [comment]
ok just found the `make test-unit` command to bypass jshint

**Comment by janmeier** [comment]
jshint checks for syntax / style errors, but it should also output the actual error. Unless it's not installed properly?

**Comment by JSteunou** [comment]
@janmeier my copy / paste was cut, I update my post and PR a unit test.
