### ISSUE TITLE
Timestamps + camelCase / underscored options are broken

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#4104]
Trying to get camelCase timestamps in JS, but underscored in tables.

I tried to solve #4103 at my side, by stopping renaming timestamps fields and using what's said in the documentation 

```javascript
timestamps: true,
underscored: true
```

But that's even worse (or not, depends the pov), all operations return underscored attributes when the operation works.

**Comment by JSteunou** [comment]
I can merge this issue and #4103 if needed, but I found it more relevant to have an issue dedicated to *renamed timestamps properties* and another to `underscored: true` options without timestamps renamed by force.

**Comment by janmeier** [comment]
@JSteunou Sorry for the late reply - not sure what the issue is here? When I test, timestamps are properly converted to underscored, both in the table and model. The `underscored` option cannot give you underscored in db and camel cased in the model

**Comment by JSteunou** [comment]
Ho my bad then, I thought this option was to get camelCase in model but snake_case in table. Then the only issue is #4103
