### ISSUE TITLE
Transactions, Tedious and Connection Pools

### ISSUE THREAD

**Issue by awolden** [sequelize/sequelize#4105]
I have run into an issue making concurrent model calls while in a transaction when using the MSSQL dialect (tedious).

The Error I get: 

    Unhandled rejection SequelizeDatabaseError: Requests can only be made in the LoggedIn state, not the SentClientRequest state
        at Query.formatError (/home/woldena/Desktop/testapp/node_modules/sequelize/lib/dialects/mssql/query.js:215:10)
        at Request.userCallback (/home/woldena/Desktop/testapp/node_modules/sequelize/lib/dialects/mssql/query.js:46:25)
        at Request.callback (/home/woldena/Desktop/testapp/node_modules/tedious/lib/request.js:30:27)
        at Connection.makeRequest (/home/woldena/Desktop/testapp/node_modules/tedious/lib/connection.js:1142:22)
        at Connection.commitTransaction (/home/woldena/Desktop/testapp/node_modules/tedious/lib/connection.js:1048:17)
        at /home/woldena/Desktop/testapp/node_modules/sequelize/lib/dialects/mssql/query.js:44:25
        at tryCatcher (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._resolveFromResolver (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:462:31)
        at new Promise (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:69:37)
        at Query.run (/home/woldena/Desktop/testapp/node_modules/sequelize/lib/dialects/mssql/query.js:33:17)
        at /home/woldena/Desktop/testapp/node_modules/sequelize/lib/sequelize.js:713:18
        at tryCatcher (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:489:31)
        at Promise._settlePromiseAt (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:565:18)
        at Promise._settlePromiseAtPostResolution (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:244:10)
        at Async._drainQueue (/home/woldena/Desktop/testapp/node_modules/sequelize/node_modules/bluebird/js/main/async.js:128:12)

After some research I found out this error occurs when tedious tries to make simultaneous requests on the same connection, so it seems like the transaction isn't utilizing the connection pool.

How I can produce it:

```javascript
'use strict';

const app = require('../../app'),
    Sequelize = require('sequelize'),
    config = require(`${__base}/config`),
    sequelize = new Sequelize(config.db.dbName, config.db.user, config.db.password, config.sequelize),
    _ = require('lodash'),

    //models
    models = require(`${__base}/models`);


    /*-----
    This works
    -------*/
    const promiseQueue = [];

    promiseQueue.push(models.Organization.findAll());
    promiseQueue.push(models.Individual.findAll());

    Promise.all(promiseQueue).then(function(results){
      console.log(results);
    }, function(err){
      console.log(err);
    });


    /*-----
    This Does Not
    -------*/
    sequelize.transaction(function(t){
      const promiseQueue = [];

      promiseQueue.push(models.Organization.findAll({transaction:t}));
      promiseQueue.push(models.Individual.findAll({transaction:t}));

      return Promise.all(promiseQueue).then(function(results){
        console.log(results);
      }, function(err){
        console.log(err);
      });
    });
```

I'm not sure if this is a bug or if transactions do not implicitly support connection pooling.

P.S. Here are my config settings:

```javascript
  sequelize: {
        host: 'localhost',
        dialect: 'mssql',
        dialectOptions: {
            requestTimeout: 60000
        },
        pool:{
          maxConnections:15,
          minConnections:5,
          maxIdleTime:10000
        }
    }
```

**Comment by janmeier** [comment]
Transactions _cannot_ use the connection pool, since a transaction is private per connection. The tedious client only allows a single query at a time per connection, see https://github.com/pekim/tedious/issues/19

Ideally, we should hide this implementation detail in tedious away from the user by doing some kind of query queueing

**Comment by awolden** [comment]
Thanks for the quick response @janmeier . That is what I figured. It would be nice if query queuing was handled under the covers, but for the time being I can write my queries to not run concurrently.

**Comment by mikkelwf** [comment]
Is there any update to this issue..?
And can this module be of any help? https://github.com/pekim/tedious-connection-pool

**Comment by janmeier** [comment]
@mikkelwf no work done yet - The code required on the sequelize side would probably not be substantial , but actualy I'd rather solve this in tedious itself. The other connection libs support queuing out of the box, so I'd like tedious to do so as well - I haven't contacted the author about it yet though, and whether he would be willing to accept a contribution of that sort.

As for tedious-connection-pool, probably not - sequelize already does connection pooling

**Comment by vesters** [comment]
We are very interested in getting this issue fixed (or the original problem on tedious), as we are soon running into problems going to production on a project. But sadly don't possess the skills to fix it ourselves. 

@janmeier Do you think a bounty on this could get things going faster?:-)

**Comment by janmeier** [comment]
@vesters I don't have a lot of time, so no promises, but bounties are always welcome.

In any case, I'll contact @pekim shortly to discuss how this can best be solved

**Comment by vesters** [comment]
@janmeier Thanks for your reply. If @pekim og you opens an issue with the appropriate info on tedious, we would be glad to offer a bounty on it:)

**Comment by janmeier** [comment]
Update - :monkey:patching seems to be the way to go

**Comment by Screeze** [comment]
Any update on this? I also run into this issue and I'm not sure how to avoid it...

**Comment by mickhansen** [comment]
@Screeze No updates since i don't believe anyone is working on this, the person who was initially committed to maintaining the MSSQL dialect no longer has sufficient time to do it.

**Comment by Screeze** [comment]
so there is no workaround right? Then I probably will have to move my whole application to another library, since this is an essential feature for me.. :/

**Comment by mickhansen** [comment]
Simplest workaround would be a transaction wrapper that has a write queue or something (and that would not be that simple=.

**Comment by janmeier** [comment]
@Screeze Depending on the size of the project, adding the feature to sequelize yourself might be less time consuming - and we'd certainly welcome the contribution, and help you along

**Comment by DPM1** [comment]
+1
Would be great to get this working. :-)

**Comment by treythomas123** [comment]
+1

Just hit this. When I used `Promise.all` with transaction queries, I was expecting the queries to be queued, because clearly there's no way to actually run them in parallel within a transaction. After reading through https://github.com/pekim/tedious/issues/318, it still seems to me like Tedious should be handling this, just like the `mysql` and `pg` libraries.

I'll take a look and possibly write a PR for handling this within Sequelize.
