### ISSUE TITLE
Getting a SequelizeUniqueConstraintError when using set[AS] or add[AS] with belongsToMany

### ISSUE THREAD

**Issue by Jake0oo0** [sequelize/sequelize#4106]
So, I have a few models:

```
module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define('User', {
    username: DataTypes.STRING,
    ...
  }, {
    classMethods: {
      associate: function(models) {
        User.belongsToMany(models.Server, {
          through: {
            model: models.ServerModerators,
          },
          as: 'ModeratedServers',
          foreignKey: "userId",
        });
      }
    }
  });
  return User;
};
```

```
module.exports = function(sequelize, DataTypes) {
  var Server = sequelize.define('Server', {
    name: {
      type: DataTypes.STRING,
     },
     ...
  }, {
    classMethods: {
      associate: function(models) {
        Server.belongsToMany(models.User, {
          through: {
            model: models.ServerModerators
          },
          as: 'Moderators',
          foreignKey: "serverId",
        });
      }
    }
  });
  return Server;
};
```

Then I've got my join table:

```
module.exports = function(sequelize, DataTypes) {
  var ServerModerators = sequelize.define('ServerModerators', {
    serverId: {
      allowNull: false,
      type: DataTypes.INTEGER
    },
    userId: {
      allowNull: false,
      type: DataTypes.INTEGER
    }
  }, {
    timestamps: false,
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return ServerModerators;
};
```

Now this is all fine, but when I want to add a moderator to a server ex:

```
m.Server.findOne({where: {id: 1}}).then(function(server) {
 server.setModerators([2]); // 2 == a random user id 
});
```

I ALWAYS get ```SequelizeUniqueConstraintError```, and I'm so confused as to why. I'm not adding duplicates, since I'm setting the moderators, rather than adding them. (even if this was the case, this is the first pair being added)

With this not working, I've had to resort to deleting all the moderators for a server id, then recreating them, which is really inefficient and slow.

Is there something glaringly wrong here? Could this be a bug? I could really use help, and thanks in advance!

**Comment by janmeier** [comment]
Can't reproduce this - it seem to properly select to check if the association already exists before inserting. Can you create a complete example (creating data etc.), perhaps as a pull-request?

**Comment by Jake0oo0** [comment]
Ended up being an issue with my custom migrator, and initializing the collection of models two separate times while migrating.

Thanks for confirming this isn't a sequelize issue! :smile:
