### ISSUE TITLE
Checking if the table already exists when creating

### ISSUE THREAD

**Issue by peterjwest** [sequelize/sequelize#4107]
I'm trying to create a table using the `createTable` method, however the SQL uses the `IF NOT EXISTS` option, which means I have no obvious way to tell if the table has been created or not.

The method yields:
```
[ { fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 2,
    warningCount: 1,
    message: '',
    protocol41: true,
    changedRows: 0 },
  { fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 2,
    warningCount: 1,
    message: '',
    protocol41: true,
    changedRows: 0 } ]
```

Which has `warningCount: 1` when the table already exists. Is this a reliable way to check this?
Also not sure why I get two results back.

**Comment by janmeier** [comment]
I'm pretty sure the warning is a relible way to check if the table already existed. At least as far as I can read from the mysql docs.

When you run a raw query you get `rows, metadata` - but in mysql they are the same object. To standardize the api we always returns two args, thats why you're seeing the same data twice

**Comment by peterjwest** [comment]
Cool thanks!
