### ISSUE TITLE
Inconsistent Error Message Format

### ISSUE THREAD

**Issue by fogle** [sequelize/sequelize#4108]
I have a notEmpty validation with a custom message: "Name is required."
I have a unique index with a custom message: "That name is already taken."

I would like to use these errors for simple user-friendly messages and display just the text I provided.

I get:

``` js
{
    "name": "SequelizeValidationError",
    "message": "Validation error: Name is required.",
    "errors": [{
        "message": "Name is required.",
        "type": "Validation error",
        "path": "name",
        "value": "Name is required.",
        "__raw": "Name is required."
    }]
}
```

or:

``` js
{
    "name": "SequelizeUniqueConstraintError",
    "message": "That name is already taken.",
    "errors": [{
        "message": "name must be unique",
        "type": "unique violation",
        "path": "name",
        "value": "Coke"
    }],
    "fields": {
        "name": "Coke"
    }
}
```

In the first case, I want error.errors[0].message.
In the second case, I want error.message.

Either way is fine with me, but I would prefer if I can use the same way for both cases. Is it possible to make these consistent? If you choose one format, I'd be happy to do the work and send you a pull request.

Thoughts?

**Comment by fogle** [comment]
For backwards compatibility, I'd be happy to add another attribute like customizedMessage if you prefer.

**Comment by janmeier** [comment]
Likely not possible, since a validation error can contain multiple errors, thus it has to be an array

**Comment by fogle** [comment]
I don't see why that prevents consistency at least inside error.errors[0]

**Comment by janmeier** [comment]
@fogle Yeah you're right, didn't see that the messages weren't similarly formatted before.

I think we can change this text without breaking bc - If users are matching on strings its their own fault - since we have both `typeof` and the `type` property

**Comment by fogle** [comment]
Then I'll go ahead and work a pull request this weekend changing errors[0].message to the customized message for SequelizeUniqueConstraintError. Thanks!

**Comment by janmeier** [comment]
@fogle Any update?
