### ISSUE TITLE
Using empty object in query results in sql syntax error

### ISSUE THREAD

**Issue by atorkhov** [sequelize/sequelize#4109]
When using empty object in query like this:

```
    where: {
      field: {}
    }
```

it results in sql like `WHERE "Table"."field" = ;`. I had expected it to either reject query before sending to database or to ignore `field` in where.

**Comment by mickhansen** [comment]
Ignoring `field` would be too dangerous. Rejecting might be an option.

**Comment by sushantdhiman** [comment]
Should throw proper error after https://github.com/sequelize/sequelize/commit/9b73d157b3adfdf05bdefe0da3df6db1526408d2
