### ISSUE TITLE
Using empty query for associations results in changing LEFT OUTER JOIN to INNER JOIN

### ISSUE THREAD

**Issue by atorkhov** [sequelize/sequelize#4110]
When I'm using empty where query for associations like `where: {}` it changes LEFT OUTER JOIN to INNER JOIN. I'd expected it not to change query with empty where.

**Comment by mickhansen** [comment]
We current only check for the presense of a where property, not whether it's empty.

**Comment by atorkhov** [comment]
This is also as issue when using scope.
