### ISSUE TITLE
Set a virtual attribute from a raw query

### ISSUE THREAD

**Issue by festo** [sequelize/sequelize#4115]
I have a raw query in postgresql with a following attributes:

```
postId
title
isSubscibed
...
```

The `isSubscibed` is come from a LEFT JOIN and converted into a bool. It is working very well and give the right data. 

The `isSubscibed` is a virtual type in the model because it is store in a join table, but I don't want to create an association and select the whole record, just a true or false. 
(The task is more complex, but I try to simplify as much as I can...)

If I try to build an instance from it, the `isSubscibed` in never setted. I created a getter and setter method to it, but it didn't help.

I think the problem is in the model `attributes` list: a virtual attribute is missing from it, because the `normalizeAttribute`: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L75

**Comment by festo** [comment]
There is some inconsistence in the instance building process:

Suppose that I have a model (`Foo`) with two "real" attribute: `id`, and `title` and a virtual one `someVirtual`.

If I write a custom SQL query, select every record for the instance, and automatically build the model, the virtual parameter will bi set correctly.
```
sequelize.query(SQLQuery, {
        type: sequelize.QueryTypes.SELECT,
        model: Foo
}).then(function (results) {
// results will contains the good instances with every attribute
}); 
```

If I write the following, the virtual parameter will be undefined:
```
var paramsFromSQL = {
  id: 1,
  title: 'Lorem ipsum',
  someVirtual: 123
};
var foo = Foo.build(paramsFromSQL);
console.log(foo.someVirtual); // undefined
```

**Comment by mickhansen** [comment]
You should definitely be able to target a virtual attribute by adding fields to `attributes`, i do that a lot.
It should work for raw aswell, but not sure it's thoroughly tested.

**Comment by rbudiharso** [comment]
In my case i have a `distance` virtual attribute that should get it value from calculation using `earth_distance`. The raw sql itself is working and the distance is returned, but the `distance` field is missing on the the model instance.
