### ISSUE TITLE
beforeCreate unable to modify model

### ISSUE THREAD

**Issue by lucaschenex** [sequelize/sequelize#4117]
I defined my hook beforeCreate as following:

    module.exports = function (sequelize, DataTypes) {
      var userSchema = sequelize.define('User', {
      // define...
      });
      userSchema.beforeCreate(function (model) {
        debug('Info: ' + 'Storing the password');    
        model.generateHash(model.password, function (err, encrypted) {
          debug('Info: ' + 'getting ' + encrypted);
 
          model.password = encrypted;
          debug('Info: ' + 'password now is: ' + model.password);
          // done;
        });
      });
    };

and when I create a the model

      User.create({
        name:           req.body.name.trim(),
        email:          req.body.email.toLowerCase(),
        password:       req.body.password,
        verifyToken:    verifyToken,
        verified:       verified
      }).then(function (user) {
        debug('Info: ' + 'after, the password is ' + user.password);    
      }).catch(function (err) {
        // catch something
      });

Now what I get from this is 

    Info: Storing the password +6ms
    Info: hashing password 123123 +0ms    // debug info calling generateHash()
    Executing (default): INSERT INTO "Users" ("id","email","password","name","verified","verifyToken","updatedAt","createdAt") VALUES (DEFAULT,'wwx@test.com','123123','wwx',true,NULL,'2015-07-15 09:55:59.537 +00:00','2015-07-15 09:55:59.537 +00:00') RETURNING *;

    Info: getting $2a$10$6jJMvvevCvRDp5E7wK9MNuSRKjFpieGnO2WrETMFBKXm9p4Tz6VC. +0ms
    Info: password now is: $2a$10$6jJMvvevCvRDp5E7wK9MNuSRKjFpieGnO2WrETMFBKXm9p4Tz6VC. +0ms
    Info: after, the password is 123123 +3ms

It seems that every part of the code is working. Creating a user schema will invoke beforeCreate, which properly generates the hash code for the password.... except it didn't write to the database!

I'm certain that I'm missing a very important and OBVIOUS piece of code, but I just can't find where the problem is (aghh). Any help appreciated!

**Comment by mickhansen** [comment]
generateHash is asyncronous i assume? You are using the hook as if its synchronous.
Change your signature to `(model, callback)` and call the callback where you have `// done` atm.

**Comment by lucaschenex** [comment]
That's exactly where the problem is. Hmmm interesting..

**Comment by janmeier** [comment]
@lucaschenex I'm interpreting that as your problem being solved :) ? Closing this, please comment if you still have issues
