### ISSUE TITLE
Can't create an association when saving 

### ISSUE THREAD

**Issue by mitchaep** [sequelize/sequelize#4118]
Hi. I'm pretty new to sequalize and have been trying to create  MySQL database driven app.
I succeed in creating a full database, complete with associations and all, but couldn't save new records and make the associations between them, so I created a smaller test database and one insert function to add 2 test records and associate them, below is the code for the creation and function:

```js
//Create test database
var TestAsset = sequelize.define('TestAsset', {
        description: {type:Sequelize.STRING},
        amount: {type:Sequelize.DOUBLE}});

var TestAssetAddon = sequelize.define('TestAssetAddon', {
        description: {type:Sequelize.STRING},
        amount: {type:Sequelize.DOUBLE}});

TestAsset.hasMany(TestAssetAddon);
TestAssetAddon.belongsTo(TestAsset);

//create testasset
function addTest( desc1, am1, desc2, am2){
    var test = TestAsset.create({description : desc1, amount: am1});
    var testAddon = TestAssetAddon.create({description : desc2, amount: am2});

    test.addTestAssetAddon(testAddon);
}

sequelize.sync();
```

The tables are created and without the " test.addTestAssetAddon(testAddon);" it creates both the testAsset and the testAssetAddon records, so I assume it is causing the problem.

I have checked the docs multiple times for the solution to this problem.  I'm using sequelize 2.7.4.
Is it something I'm missing in the docs or doing wrong? Any and all help will be greatly appreciated

**Comment by janmeier** [comment]
`create` is an async action - you need to wait for it to complete before you can do something with it:

```js
sequelize.Promise.all([
  TestAsset.create({description : desc1, amount: am1}),
  TestAssetAddon.create({description : desc2, amount: am2})
]).spread(function (test, testAddon) {
  return test.addTestAssetAddon(testAddon);
});
```

You can also create both in one go:
```js
TestAsset.create({
  description : desc1, 
  amount: am1,
  TestAssetAddons: [
    {description : desc2, amount: am2}
  ]
}, {
  include: [TestAssetAddon] 
});
```

**Comment by janmeier** [comment]
All async operations (operations that hit the DB) in sequelize, return a promise - perhaps it would help you to read up on promises before trying to understand how they work with sequelize https://www.promisejs.org/

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
