### ISSUE TITLE
Returning option for Model.destroy

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#4122]
`Model.update(...)` already accepts `returning = true` option - any plans to add same option for `Model.destroy(...)` - would be very nice feature.

**Comment by janmeier** [comment]
What does returning return when you are removing something? The ids of the deleted rows?

**Comment by alekbarszczewski** [comment]
It may return whole rows (deleted ones) or specified columns:

```sql
DELETE FROM "Users" RETURNING *; -- will return deleted rows same as select
DELETE FROM "Users" RETURNING id, email; -- will return only id and email columns of deleted rows
```

So it "behaves" same as `RETURNING` in `UPDATE`

This is very handy if you want to delete something and then for example send email based on deleted data - instead of fetching row and then deleting it you can just delete and fetch in one query (one server-database roundtrip less).

**Comment by alekbarszczewski** [comment]
@janmeier The problems I see are:

1. For now `Model.destroy()` "returns" `(rows)`. To make it consistent with `Model.update()` it should "return" `([rows, instances])` (instances only returned if `returning` option has been set) which would break BC.

2. For now `instance.destroy()` "returns" `([])` always. To make it consistent with `instance.update()` it should "return" `(instance)` (instance argument only set when `returning` option has been set). I am not sure if that would break BC because `[]` returned in callback is useless any way, because it never contains any data/info.

**Comment by janmeier** [comment]
@alekbarszczewski If we only return `rows, instances` from `destroy` when `returning` is true, that would not break BC - since its a new option :). Not sure I like the idea of having different return "types" based on options passed though - and it would be inconsistent with `update` as you mentioned ... Hmm, not sure whats the best to do

@2 - lets take that in the other issue :)

**Comment by AllanPinheiroDeLima** [comment]
Well, it would be a very nice feature. 
I'm using the .destroy method and I would use the "returning" option as well. As update has this already, it would make sense to pull this into a next step. 
About backward compatibility, if now return only "rows", into the first parameters, it wouldn't be the same as update to return the deleted instance in the second parameter ?
I mean, I'm new to the library at all, but it didn't make sense for me not putting it into the second parameter as it does not exist second parameter at all

**Comment by iwaduarte** [comment]
[+1]
Nice feature to have

**Comment by hggomez** [comment]
Any plans on this?

**Comment by robihamdani** [comment]
so this is only feature ?

**Comment by theoephraim** [comment]
+1 would like to see this implemented

**Comment by DraftProducts** [comment]
Yea, it will be nice to have this feature 👍
