### ISSUE TITLE
Best way to do finds with many includes?

### ISSUE THREAD

**Issue by ryanpon** [sequelize/sequelize#4125]
I commonly need to do queries that use many includes, for example:
```javascript
User.find({
  where: ...,
  include: [Pet, Car, FavoriteMovie, KitchenSink]
});
```

This becomes expensive quickly since the data set returned is a function of num(Pet) * num(Car) * num(FavoriteMovie) * num(KitchenSink). Other than explicitly doing separate queries by either call find multiple times or doing a lazy load with `get<associationName>`, is there a good way to mitigate this issue?

I have a fix for this locally that automatically splits find calls into multiple queries when there is more than one include and transparently merges the result back together. What do you think about this approach?

**Comment by mickhansen** [comment]
`include.seperate` which would offer you the oppurtunity to split an include into a seperate call to avoid the costly deduplication logic is on the roadmap: https://github.com/sequelize/sequelize/issues/2869

I hope to start on it soon.

**Comment by mickhansen** [comment]
Working on support for hasMany here: https://github.com/sequelize/sequelize/pull/4177
