### ISSUE TITLE
Setting null value when omitnull is true

### ISSUE THREAD

**Issue by radoslavpetranov** [sequelize/sequelize#4131]
Hi there,

I've been trying to figure out if there's a more gracious way to handle the following scenario:

- Sequelize is initialized with omitnull = true
- it works great in 95% of the cases
- every now and then I need to explicitly set a value back to null and I can't do that no matter what I try. If that's the only change I'm doing I'll also end up with this (which is normal)

SequelizeDatabaseError: ER_EMPTY_QUERY: Query was empty

Right now the only workaround I've been able to do is to use sequelize with a pure SQL UPDATE query to update the entries I need. My problem is that this approach is super ugly and I was wondering if there's more gracious way to handle these scenarios. Something like being able to pass { omitNull : true } with the options of instance.save() or instance.set() would be awesome but I don't think that's supported right now. Are there any more sequelize-friendly ways to set a null value?

Cheers and thanks!

**Comment by mickhansen** [comment]
We don't recommend the use of `omitNull` anymore.

**Comment by radoslavpetranov** [comment]
That was fast! So are undefined/null values not overwriting existing values by default, unless { reset : true } is passed as an option?

**Comment by mickhansen** [comment]
Not sure understand? What is your issue exactly?

**Comment by radoslavpetranov** [comment]
Say I have this mapping:

ChildObject.belongsTo(ParentObject, {foreignKey: 'child_id', as: 'child'});

Now say I've assigned a child object instance to a parent and now I want to set that foreign key back to null/undefined so that the Child still remains in the database but the Parent won't point to it any more.

I tried using parent.set('child_id', null/undefined) or parent.setChild(undefined) and then saving and my change is never persisted because the query that gets executed refuses to set that value to null. So to go around this I'm using Sequelize.query() with a raw Update query and I was wondering if there's a way to do what I need to if sequelize is initialized with omitNull = true?

Would the alternative be to set omitNull to false and then run the .set() method with { reset : true }? Is the default sequelize behavior (when omitNull is false) not to overwrite existing values with nulls unless {reset : true} is specified in the setter?

**Comment by mickhansen** [comment]
Using `set('field', null)` or `parent.setChild(null)` should just work.
Can you show a minimal example with all the code needed to reproduce this issue? Sounds very odd.

**Comment by DigitalSkyline** [comment]
I just came across this *feature* and it is currently not working as expected.

I set omitNull : true globally, because for our database, it is generating UUID's for the Primary Key (ID Not Null) ... If I pass Null to ID, I get the error that it's an invalid since it's Null. Without omitNull, ID is automatically inserted into the generated queries.

That being the case, when I attempt to use this with Paranoid:true , I want to be able to set deletedAt : Null on the case a record needs to be undeleted ... well by setting omitNull I am unable to send any Null values at all.

The logical solution is to allow the omitNull to be set on a per model/per command basis. Which is what I expected to be the case, just as you can set Paranoid:t/f ...

**Comment by mickhansen** [comment]
@DigitalSkyline As mentioned, we don't recommend omitNull anymore, it was a dirty hack for another time.

**Comment by DigitalSkyline** [comment]
And the alternative is? As mentioned omitNull is the only way I'm aware of to prevent Sequelize from sending Null/undefined values when the database is handling things such as creating the UUID's for a Primary Key.

**Comment by janmeier** [comment]
@DigitalSkyline marking the column as `autoIncrement: true` should solve that. Sequelize will issue `INSERT ..(uuid) VALUES (DEFAULT)` which means the db handles the value. 

I realize autoIncrement might be a bit confusing, but its the setting thats also used to handle auto-increment columns

**Comment by DigitalSkyline** [comment]
Thanks, that works!

**Comment by DigitalSkyline** [comment]
So by doing this, now if I try to sync, I get an error:
 SequelizeDatabaseError: syntax error at or near "SERIAL"

**Comment by janmeier** [comment]
Hmm, yeah I made a guess that you weren't using sync, but generating your tables manually when you said that the UUID was generated by the DB. 

I don't think there is any good way to fix this now then - we'd need to add a new option `autoGenerated` or similar, to tell sequelize that this is the column that is generated by the db.

**Comment by janmeier** [comment]
@radoslavpetranov Any news on your issues?

**Comment by radoslavpetranov** [comment]
I can't provide you guys with a code snippet because it's all in a big-ass work project with a ton of mappings. I didn't think that's a bug in the sense that what I'm getting (i.e. the empty query and/or the lack of persistence to my updates in that scenario) is an expected result from what I understand. I was just wondering if there's a better workaround than what I'm doing; like a way to tell a particular .save()/.set() command to override the omitNull value and to actually save the null/undefined value that I'm passing it. From my googling around and the responses in here that doesn't seem to be the case so  I think we should just close this thread and I'll stick with my manual sql updates.

I do understand your advice not to use omitNull but that's in the core of our main project and I don't wanna change it because I don't know what calls may rely on it.

So yeah - thanks for the help guys  - this was more of a 'can i do that better' type of thread rather than 'the code is broken' type of thread.

Cheers

**Comment by janmeier** [comment]
@radoslavpetranov You're welcome :)

**Comment by taran-1898** [comment]
I have a similar issue with bulkCreate. Is there a way to stop bulkCreate from changing values (not talking about primary keys here) back to null without using omitNull?

**Comment by vbhakta8** [comment]
I understand `omitNull` was a dirty hack for another time, but we are already using it in production, is there anyway to bypass like we have `paranoid` flag for soft deletes
