### ISSUE TITLE
Postgres UPSERT native support

### ISSUE THREAD

**Issue by lefnire** [sequelize/sequelize#4132]
Looks like Postgres [recently added UPSERT](https://news.ycombinator.com/item?id=9509870) ([9.5alpha is it?](http://www.postgresql.org/about/news/1595/)). Seems Sequelize handles psql upsert fine presently with its workaround, so obviously no rush.

Me personally (and maybe I need re-architecting), my current project's most common SQL operation is UPSERT. That operation seems quite slow; this is the resultant SQL which _looks_ like it would be slow:

`CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $func$ BEGIN INSERT INTO ... VALUES ...; RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE ... SET ... WHERE ...; RETURN 2; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();`

So I'd personally upgrade to Postgres 9.5 if native upsert becomes supported in sequelize

**Comment by mickhansen** [comment]
We still need a proper way to detect features based on the server version, but yeah ideally we'd want to use the built in UPSERT when possible.

**Comment by lefnire** [comment]
Possible sloppy short-term solution: pass version constructor options? Eg: `new Sequelize('database', 'username', 'password', {..., version:'9.5'})`

**Comment by janmeier** [comment]
@mickhansen All the query work regarding version detection is actually already in place - As far as I can see we just need to actually select the verison, and find a good datastructure for storing which features are supported by what versions

**Comment by janmeier** [comment]
One problem though is that pg 9.5 is not supported by travis - and probably won't be before its officially releasesd

**Comment by lorenz** [comment]
+1

**Comment by thynson** [comment]
Well, PostgreSQL 9.5 is released.

**Comment by ncwhale** [comment]
Sometimes, just need update one signal col when insert failed, right now I'll do it like this:

```JavaScript
Models.Somemodel.create().then(_=>{do something here.}).catch(_=>{do something when fail});
```

 but with pg 9.5 , how about add a suger option when insert fail? like this

```JavaScript
Models.Somemodel.create({}, {conflict: { add another sub update/nothing query here}}).then(_=>{do something here.});
```

It most like the upsert on another way, but with other db also can also use it as is.(by add a catch and do the sub query.)

**Comment by tsheaff** [comment]
Any updates on this? Our team is currently looking at how to optimize our upserts, as the native PostgreSQL 9.5 upsert is much faster.  We'd strongly prefer not to re-implement upsert ourselves as a native query.

**Comment by mickhansen** [comment]
@tsheaff No one is working on it, but version detection is in place so it should not be a lot of work (alternative syntax based on version detected). We have support for testing against 9.5 aswell.

**Comment by tsheaff** [comment]
Awesome thanks for quick reply @mickhansen

**Comment by felixfbecker** [comment]
As he said, noone is working on it. PRs welcome :)

**Comment by tsheaff** [comment]
PR is already out @felixfbecker here: https://github.com/sequelize/sequelize/pull/6325

**Comment by tsheaff** [comment]
Seems like #6325 hasn't been worked on in over a month.  Anyone know more around this issue?

**Comment by AlJohri** [comment]
There is also #7174.

**Comment by haijianyang** [comment]
So, this issure when to be resolved?

**Comment by tsheaff** [comment]
This is a really stale issue. Is there any update on this?
