### ISSUE TITLE
Does upsert support transactions?

### ISSUE THREAD

**Issue by arahlf** [sequelize/sequelize#4136]
I'm not sure if this is just a documentation issue or not, but does the upsert method ( http://docs.sequelizejs.com/en/latest/api/model/#upsertvalues-options-promisecreated ) support adding a transaction reference in the options object?

**Comment by mickhansen** [comment]
All calls should support adding a transaction since they pass along their options to `query`

**Comment by arahlf** [comment]
Thanks!
