### ISSUE TITLE
Model definition without primaryKey while overwriting the id property

### ISSUE THREAD

**Issue by sdepold** [sequelize/sequelize#4139]
When you create two models and one does overwrite the id property and didn't set the primaryKey, you are running into interesting problems when association both models.

```
var User = sequelize.define('User', { username: Sequelize.STRING, space_id: Sequelize.STRING }, { tableName: 'users', underscored: true })
var Space = sequelize.define('Space', { id: Sequelize.STRING }, { tableName: 'spaces', underscored: true })
User.belongsTo(Space)

TypeError: Cannot read property 'type' of undefined
    at BelongsTo.injectAttributes (.../node_modules/sequelize/lib/associations/belongs-to.js:119:153)
    at null.belongsTo (.../node_modules/sequelize/lib/associations/mixin.js:106:77)
    at repl:1:7
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1096:12)
    at ReadStream.onData (readline.js:841:14)
    at ReadStream.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:765:14)
    at ReadStream.emit (events.js:92:17)
```

This problem does not occur anymore, when the space's id property is marked as `primaryKey: true`.
So in case a model does not have a primaryKey property and the default primary key property (id) is overwritten, we should print a warning somewhere.

**Comment by vanwalj** [comment]
Got the same bug, which seems to happen from sequelize 3.4.0

**Comment by pmiguel** [comment]
I confirm it as well, starting from ^3.4.0. Setting the primaryKey property does solve the problem.

**Comment by janmeier** [comment]
We should probably also check that the `primaryKey` property is a boolean (see https://github.com/sequelize/sequelize/issues/4249)

**Comment by vikramnet2003** [comment]
Hi,

In mysql we are partitioning a table which may not have a primary key or has composite primary key. This fix might break those model definitions. I have table with id and account_id, which is partitioned by account_id, so my primary key would be (id, account_id), but with this fix the table definition is not possible. In the below table since i could not define a composite primary key i just defined the same as unique index.

Is there some other workaround?

      var Project = sequelize.define('Project', {
        id:{
          type: Sequelize.BIGINT(20),
          allowNull: false,
          autoIncrement: true
        },
        title: Sequelize.STRING,
        description: Sequelize.TEXT,
        account_id: {
          type: Sequelize.BIGINT(20),
          allowNull: false
        }
      },
      {
        indexes: [
          {
            name: 'id_and_account_id',
            type: 'UNIQUE',
            fields: ['id', 'account_id']
          }
        ]
      });

**Comment by VijayChavan001** [comment]
The similar is observed(as mentioned by vikram-chaitanya) for view without primary key and having id as column. So there should be some way to configure that pre-openioned implementation on 'id' column.

**Comment by sfertman** [comment]
This makes now sense. If I have a column named `id`, it doesn't have to be the primary key!
