### ISSUE TITLE
Sequelize 3.4.0 broke data binded to `options.ctx.state` remaining in tact outside of create hooks

### ISSUE THREAD

**Issue by garrett-gottlieb** [sequelize/sequelize#4143]
We use `options` in `afterCreate(inst, options)` to pass the context as `options.ctx`. In certain cases, we modify Koa's `ctx.state`. When upgrading to 3.4.0, the changes made to `ctx.state` vanish as soon as the `afterCreate` completes.

**Comment by janmeier** [comment]
Can you show a small example?

**Comment by garrett-gottlieb** [comment]
```js

    yield db.models.Like.create({
      postId : post.id,
      userId : user.id,
    }, options)

    options.ctx.state.additionalData.workout.id.should.exist
```
That used to pass, and that property *is* set when I log it in `db.afterCreate`, but not in my test once the hook finished running.

**Comment by garrett-gottlieb** [comment]
Also, I ran an equality test of the `options` before and after the `create`, and now they are unequal. I'm guessing there is a deep clone going on somewhere.
```js
var originalOptions = options
yield db.models.Like.create(obj, options)
originalOptions === options // false
```

**Comment by mickhansen** [comment]
We clone the options when calling create so that is to be expected.
It should still be possible to change options in hooks though (but they won't leak out into the options you initially passed, that was considered a bug).

**Comment by garrett-gottlieb** [comment]
Hmm... Then how is it possible to extract some additional data from the hooks?

**Comment by garrett-gottlieb** [comment]
Or, perhaps only a shallow clone can be done?

**Comment by janmeier** [comment]
@garrett-gottlieb Perhaps some kind of callback-local storage like CLS or domains? I don't think a shallow clone is enough - we modify the options object internally, so seeing the main object not modified by the properties of that object may be modified would be confusing.

As mick mentioned, we generally have a lot of requests from users who do not want the options to be modified - so we are beginning to clone the options object in more and more methods. This is the first request we've gotten about _not_ cloning :)

As mentioned, i think cls would fit your case better:

```js
cls.set('ctx', ctx);

model.create();

// In beforeCreate
var ctx = cls.get('ctx');
```

**Comment by garrett-gottlieb** [comment]
Cool. I'll look into CLS when I want to upgrade. Thanks!

On Tue, Jul 21, 2015 at 3:17 PM Jan Aagaard Meier <notifications@github.com>
wrote:

> @garrett-gottlieb <https://github.com/garrett-gottlieb> Perhaps some kind
> of callback-local storage like CLS or domains? I don't think a shallow
> clone is enough - we modify the options object internally, so seeing the
> main object not modified by the properties of that object may be modified
> would be confusing.
>
> As mick mentioned, we generally have a lot of requests from users who do
> not want the options to be modified - so we are beginning to clone the
> options object in more and more methods. This is the first request we've
> gotten about *not* cloning :)
>
> As mentioned, i think cls would fit your case better:
>
> cls.set('ctx', ctx);
>
> model.create();
> // In beforeCreatevar ctx = cls.get('ctx');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/4143#issuecomment-123450804>
> .
>
-- 
Garrett Gottlieb
CEO & Founder, PumpUp
647.622.7867
http://pumpup.com
