### ISSUE TITLE
Model association 'hasOne' doesn't seem to create setters/getters

### ISSUE THREAD

**Issue by CGavrila** [sequelize/sequelize#4144]
I have been struggling for quite some time now with this issue and I don't really get what is happening. 

I am using Sequelize 3.3.2, Node v0.12.5 and MySQL.

Code:

```
House.hasOne(Owner, { as: 'owner', foreignKey: 'owner_id' });
House.hasOne(Price, { as: 'price', foreignKey: 'price_id' });

var house = House.build({
       price: 10000,
       rooms: 3
});

house.setOwner(1); // where the problem is
```

Instead of setting the owner, I get:
```
TypeError: undefined is not a function
```

Is there any reason why that wouldn't work? When placing a `console.log(instancePrototype['setOwner']` in the `has-one.js`file in the Sequelize code, I get `[Function]`, but then I can't call it.

I'm not even sure where I should look. For example:
```
console.log(house.__proto__.Model.associations.owner.accessors);
```
gives me an object with `get: getOwner, set: setOwner` and indeed, it looks like the `injectSetter` and `injectGetter` functions in `has-one.js` are doing their job. I just don't get why this isn't passed down to where I'm trying to access those methods.

**Comment by mickhansen** [comment]
It should just work but looking at your setup i think you want 'BelongsTo` - You want the foreign keys on House i assume?

**Comment by CGavrila** [comment]
Yes, I guess it could go both ways. The issue happens with `Price` as well, though.

`House` has `owner_id` and `price_id` as fields. From the docs I understood that the `foreignKey` field would refer to the fields in `House`, correct?

**Comment by CGavrila** [comment]
I have found the issue after roughly 10 hours spent on the problem. Unfortunately, it would be very difficult to provide a reproducible case here.

However, the explanation is sort of the following: I had the `House`, `Owner` and `Price` models associated like in the first post. Mick was right, `belongsTo()` was the right choice, but that's less important. The problem was that after I have defined those associations, I have defined some other associations related to the same models, but with `belongsToMany( { through: someOtherMode } )` and I think that this caused some clashes in the injected setters and getters.

The above explanation might not be the best, so it basically boils down to this - if you have a problem with the `set` and `get` methods that you should have attached to your model, check if there's some other association that might be interfering.
