### ISSUE TITLE
[2.0.5]belongToMany wrong foreignIdentify relationship when bind multiple times.

### ISSUE THREAD

**Issue by jchbh-duplicate** [sequelize/sequelize#4152]
When bind belongToMany multiple times in relations (in my case I call belongToMany 5 times on same two tablesfor different properties). you will found the foreignIdentify in associations will change when more belongToMany call. 

it is because in belong-to-many.js line 144. 
`if (this.options.through.model === association.options.through.model)`

`this.options.through` might not be an model but a string, and `this.options.through.model` will return `undefined`. and two `undefined` will match the if condition and then `this.paired = association` will set incorrect pair and change the `foreignIdentify` in exists association which set to `this.paired`

Please add test case to find whether this bug exists in new 3.x version or not. because I use too much findAll in 2.x style and hard to change to 3.x, so I cannot test whether this bug exists in current version or not.

**Comment by mickhansen** [comment]
I just fixed this: https://github.com/sequelize/sequelize/pull/4151
