### ISSUE TITLE
Order by json field

### ISSUE THREAD

**Issue by astephenb** [sequelize/sequelize#4155]
Is there a way to order by a postgres json field?

```javascript
Post.findAll({
  order: "json_document->>'json_field' ASC"
})
```

Or something similar. It seems that this is sanitized to the degree that it is not possible, but I could be missing something here.

**Comment by matthewrfindley** [comment]
We were able to make this work by using ```sequelize.json```.

```
Post.findAll({
  order: [sequelize.json("json_document.json_field"), 'ASC']
});
```

I think the problem here is that this feature is not very well documented.  My confusion was around the ability to pass a raw string to order, assuming that the string would be unchanged.  The documentation for order does not indicate how the string is used when a json field is supplied.  

Looking through the specs I was able to find sequelize.json, but didn't not find it in the docs after a brief search.

Can someone clarify if passing a raw string in the order clause for a json field is considered a bug?

**Comment by janmeier** [comment]
Passing a raw string will be used verbatim. What @astephenb posted should work fine. Which error do you get?

http://docs.sequelizejs.com/en/latest/docs/models-usage/#manipulating-the-dataset-with-limit-offset-order-and-group mentions the various syntaxes for order.

**Comment by astephenb** [comment]
When I do an order like: `order: '"createdAt" ASC'` everything works fine. However, `order: ['"createdAt" ASC']` executes as `ORDER BY "createdAt ASC"` and throws `SequelizeDatabaseError: column "createdAt ASC" does not exist`

The first case is not super helpful because we want to order by multiple json fields (lastName, firstName).

**Comment by mickhansen** [comment]
per the docs the syntax is:

```js
order: [
  ['createdAt', 'ASC']
]
```

**Comment by astephenb** [comment]
@mickhansen It is just an example of me not understanding the documentation. [sequelize#Order](http://docs.sequelizejs.com/en/latest/docs/querying/#ordering) makes it seem that a string will not be escaped. `Both the following statements will be treated literally so should be treated with care`.

@janmeier Thanks for that link. That does not seem to be a logical place to go to look at ordering documentation. Would you be open to a PR adding some of that info in the order documentation?

**Comment by mickhansen** [comment]
A string an a single array should not be escaped, a nested array will be. Atleast that was the intention, but there might be an issue there.

**Comment by janmeier** [comment]
@astephenb A string will not be escaped, but anything in an array will.

Perhaps you can pass a `sequelize.literal` to order - or you can concat multiple fields into your string order.

`sequelize.json` also seems to work, as per @matthewrfindleys comment.

Any PR to make the docs better is very welcome :)

**Comment by astephenb** [comment]
Thanks for the help guys!

**Comment by calvintwr** [comment]
this is a gem. should document it down. under querying -> ordering

**Comment by janmeier** [comment]
@calvintwr PR welcome :)

**Comment by calvintwr** [comment]
@janmeier haha i saw that coming. okay i will do it when i'm free.

**Comment by shime** [comment]
I'm getting an error when trying to use 

```js
Post.findAll({
  order: [sequelize.json("json_document.json_field"), 'ASC']
});
```

The error is: `SequelizeDatabaseError: column reference "json_field" is ambiguous`.

Sequelize version: 3.27.0.

**Comment by shime** [comment]
Never mind. Fixed by using `sequelize.literal` instead.
