### ISSUE TITLE
postgres ssl with self signed cert on sequelize v1.7.11

### ISSUE THREAD

**Issue by jaime-ez** [sequelize/sequelize#4159]
Hi, I'm trying to connecto to a postgres DB with a self signed cert. These are my connection options:

![image](https://cloud.githubusercontent.com/assets/4974776/8786902/5a391f30-2f07-11e5-9370-9d74ab98646b.png)

But I keep getting the error:  code=UNABLE_TO_VERIFY_LEAF_SIGNATURE, response=undefined
The only way I've been able to connect is setting 
export NODE_TLS_REJECT_UNAUTHORIZED=0
But this is not recommended...any ideas?
Thanks!

**Comment by janmeier** [comment]
Sequelize doesn't do anything to facilitate ssl connections. Try using node-pg directly, and perhaps opening an issue with them https://github.com/brianc/node-postgres to debug further
