### ISSUE TITLE
belongsToMany relationship removes id field from queries on join table

### ISSUE THREAD

**Issue by seth-admittedly** [sequelize/sequelize#4164]
Using `belongsToMany` with the `through` option is needed to eager load children in n:m relationships. However, we sometimes want to access the join table directly for our REST methods. The former appears to cause `getJoinTableRows` calls to omit the `id`.

```
	models.ContentModuleBundle.hasMany(models.ContentModuleBundleContentModule);
	models.ContentModuleBundle.belongsToMany(models.ContentModule, {through : models.ContentModuleBundleContentModule});
	models.ContentModule.belongsToMany(models.ContentModuleBundle, {through : models.ContentModuleBundleContentModule});
```

should allow both `ContentModuleBundle.findAll({include : ContentModule})` and `contentModuleBundle.getContentModuleBundleContentModules()`, which it does, but the latter omits the `id` field from `ContentModuleBundleContentModule`.

Our current fix is to explicitly specify the attributes for `getContentModuleBundleContentModules` but that's obviously not ideal.

**Comment by seth-admittedly** [comment]
We don't actually specify `id` in the model definition (since it's autocreated along with the date fields) and it looks like the `through` is actually stripping the field from the model definition itself. Explicitly specifying an `id` attribute in the definition of the join table appears to resolve the problem.

**Comment by mickhansen** [comment]
For legacy reasons Sequelize does not define 'id' on a join model automatically.

**Comment by janmeier** [comment]
@seth-admittedly Yes, specifying the id field manually is the correct solution here :)
