### ISSUE TITLE
Order doesn't use fields aliases

### ISSUE THREAD

**Issue by atorkhov** [sequelize/sequelize#4167]
In order directive for queries it doesn't take in account of field aliases.

**Comment by JSteunou** [comment]
might be link to #4103 ?

**Comment by janmeier** [comment]
Not directly, but the root cause is the same, yes :)

**Comment by JSteunou** [comment]
Hey I saw *fields aliases*, I jumped on it :p

**Comment by subjectix** [comment]
Yeah... this bug is annoying -_- 
And I can't find the origin to make a PR. can't track where order in the options end up.

**Comment by faq885** [comment]
Why is this closed? i am having still this issue!

**Comment by mickhansen** [comment]
It was closed via the PR fixing this @faq885
However it is a 3 year old issue, so if you are "still" having the issue then i commend your patience, if it's a recent issue maybe it's a new bug.
