### ISSUE TITLE
Issue with accessors when creating n:m relation

### ISSUE THREAD

**Issue by mrlarssen** [sequelize/sequelize#4168]
I have the following models (minified):

  ```javascript
var Project = sequelize.define('Project', {
    title: {
      type: DataTypes.TEXT,
      allowNull: true,
    },{
  classMethods: {
    associate: function(models){
      Project.belongsToMany(models.User, {through: 'project_user'});
    }}});

  var User = sequelize.define('User', {
    first_name:     { type: DataTypes.STRING },
  {
    classMethods: {
      associate: function(models){
        User.belongsToMany(models.Project, {through: 'project_user'});
      }}});
```

This creates the following functions for Project:

```javascript
getUsers: [Function],
  hasUsers: [Function],
  hasUser: [Function],
  setUsers: [Function],
  addUser: [Function],
  addUsers: [Function],
  removeUser: [Function],
  removeUsers: [Function],
  createUser: [Function]
```

But doesnt generate these methods for User, so when I try to do:

```javascript
User.findById(req.query.userId)
  .then(function(u) {
    u.getProjects().then(function(result){
      return res.json(result);
    });
  });
```

This gives me the error on line u.getProjects()...:
```javascript
Unhandled rejection TypeError: undefined is not a function
```
I am getting this error when trying to access any function through User (and u is not null :) ).
If I log User.Instance.prototype, the functions are not listed, like they are if I log Project.Instance.prototype (or even just User, and Project).

I have also tried to specify the association like this:
```javascript
Project.belongsToMany(models.User, {as: 'users', through: 'project_user',  foreignKey: 'id_project', otherKey: 'id_user'});
User.belongsToMany(models.Project, {as: 'projects', through: 'project_user',  foreignKey: 'id_user', otherKey: 'id_project'});
```
Which gives me the same result.

Does not seem like the functions are added to User, but they are added to Project. Any idea?

Using sequelize version: "3.3.2"

**Comment by janmeier** [comment]
@mrlarssen The code you posted works fine for me. We also rely on this in many of our tests so I would be surprised if it was suddenly broken :)

Perhaps you can create a pull-request with a failing test-case to show your issue? 

Also, I have to ask - Are you absolutely sure both `belongsToMany`s are actucally called :)

**Comment by mrlarssen** [comment]
Thanks for the reply.

No, I am not sure both belongsToMany are being called. This is my index.js file:

```javascript

"use strict";

var fs = require("fs");
var path = require("path");
var config = require('../config/environment');
var Sequelize = require("sequelize");
var sequelize = new Sequelize(config.dbUrl, { define: {underscored: true, timestamps: false}});
var db = {};

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file.indexOf('.spec.') === -1) && (file !== "index.js");
  })
  .forEach(function(file) {
    var model = sequelize["import"](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});

sequelize.sync();

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;

```

If it is not being called, what would the fix be (or force) ?

**Comment by janmeier** [comment]
Well that looks about right. Try to put a console.log in the associate function for each model to see if they are called. That's the only reason I can see for this not working. 


Otherwise, as I said you'll have to create a pull request with a failing test to show the issue

**Comment by mrlarssen** [comment]
You were right. The association for user was never called. I think maybe my classMethods block was in the wrong place 'cause I have som other blocks e.g "instanceMethods", so I moved it before everything and it fixed the problem.

Thanks for the help :)
