### ISSUE TITLE
replace fails in the escape method if the typeof val is function.

### ISSUE THREAD

**Issue by hariprasadkulkarni** [sequelize/sequelize#4169]
I'm trying to run a "find" query on a table(model) in my db schema.

In the SqlString.escape function in sequelize/lib/sql-string.js file,

    val = val.replace(/[\0\n\r\b\t\\\'\"\x1a]/g, function(s)

fails, quoting

    TypeError: Object function (e, u) { pass(i + 1, e, u); } has no method 'replace'

The 'typeof' 'val' being passed is 'function'. This happens around line 89.

I think it should be handled at this line (around 76),

    if (typeof val === 'object' && val !== null)

by changing it to,

    if ( val !== null && (typeof val === 'object' || typeof val === 'function'))

**Comment by janmeier** [comment]
Are you trying to pass a javascript function? Can you show the code that produces this error?

**Comment by hariprasadkulkarni** [comment]
Yes, inadvertently I was passing a function. That was because I had bungled up the order of my parameters. But shouldn't sequelize fail gracefully in case 'function' is not an expected data type?

**Comment by janmeier** [comment]
In the best of all worlds yes - but javascript is a dynamic language, and if we had to add checks that every parameter has the expected type in every public method, the codebase would be twice as large :) 

Generally we add checks in places where not doing so would create errors that are hard to decipher / that you only discover later on. In this case you were able to decipher the error just by looking at the stack trace, and I've never heard of this error before, so I don't think we need that check

**Comment by hariprasadkulkarni** [comment]
Makes sense. Thanks!
