### ISSUE TITLE
Get 'ER_TOO_LONG_KEY error running migrations in the utf8mb4 mysql database

### ISSUE THREAD

**Issue by tiaozi0912** [sequelize/sequelize#4171]
When running migrations, get the ER_TOO_LONG_KEY, probably because the mysql database charset is  utf8mb4.  How to make it work?

Here is the database config:
```
"staging": {
    "username": "USERNAME",
    "password": "PASSWORD",
    "database": "DATABASE",
    "host": "HOST",
    "dialect": "mysql",
    "port": 3306,
    "define": {
      "charset": "utf8mb4",
      "collate": "utf8mb4_general_ci"
    }
  }
```

Here are the logs:
```
Unhandled rejection SequelizeDatabaseError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
    at Query.formatError (/root/www/smartChat-service-staging/node_modules/sequelize/lib/dialects/mysql/query.js:159:14)
    at Query._callback (/root/www/smartChat-service-staging/node_modules/sequelize/lib/dialects/mysql/query.js:35:21)
    at Query.Sequence.end (/root/www/smartChat-service-staging/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/root/www/smartChat-service-staging/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/root/www/smartChat-service-staging/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/root/www/smartChat-service-staging/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/www/smartChat-service-staging/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/www/smartChat-service-staging/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```
Using version 3.4.1

**Comment by janmeier** [comment]
According to this post http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes you are trying to create an index that is too long. You'll have to create the index on parts of the columns or make the columns smaller 

Sequelize doesn't have support for this specific usecase I think so you'll most likely have to resort to a raw query

**Comment by tiaozi0912** [comment]
I didn't create any indices. Did sequelize create any indices by default?
```
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.createTable('users', {
      id: {
        type:Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      openid: Sequelize.STRING,
      nickname: Sequelize.STRING,
      sex: {
        type: Sequelize.INTEGER,
        defaultValue: 1
      },
      headimgurl: Sequelize.STRING,
      createdAt: Sequelize.DATE,
      updatedAt: Sequelize.DATE
    });
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('users');
  }
};
```

**Comment by janmeier** [comment]
That code works fine for me. What does the create table sql look like in the logs? 

This error is related to mysql, not sequelize - if you figure out why mysql is throwing that error we might be able to help you from there

**Comment by tiaozi0912** [comment]
Didn't see the sql in the logs. All the logs are attached above. How could I get that?

**Comment by janmeier** [comment]
Have you disabled logging in the migrator? Not very familiar with how it works so I'm not sure how to get sql logging. But you can use `sequelize.getQueryInterface()` to get access to the qi in code and try to run th equery from there

**Comment by tiaozi0912** [comment]
Managed to get the sql by putting a console.log in the QueryInterface.prototype.createTable:
``
CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE , PRIMARY KEY (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
```
It failed when creating the SequelizeMeta. I guess it is related to the charset. If charset is utf8, it works

**Comment by janmeier** [comment]
Hmm, it seems the migrator needs to explictly define its charset then - Please open an issue with https://github.com/sequelize/umzug instead

**Comment by tiaozi0912** [comment]
Opened. For me `` `name` VARCHAR(255) NOT NULL UNIQUE`` is the issue since if utf8mb4, it up to 4 bytes per character. Reduce to number of character will make it work. 

Is a way to override it?

**Comment by igor-yamshchykov** [comment]
Is there a solution yet ?

**Comment by tomfun** [comment]
Agree with @tiaozi0912 same proble appears when chage charset to utf8mb4

**Comment by tomfun** [comment]
http://wfsovereign.github.io/2016/05/01/nodejs%E9%A1%B9%E7%9B%AEmysql%E4%BD%BF%E7%94%A8sequelize%E6%94%AF%E6%8C%81%E5%AD%98%E5%82%A8emoji/

**Comment by apmcodes** [comment]
Received the same error on a column with unique: true. Adding charset resolved the issue.

    const sequelize = new Sequelize(connectionString, {
        dialect: 'mysql',
        logging: false,
        operatorsAliases: false,
        define: {
            charset: 'utf8',
            collate: 'utf8_general_ci',
        }
    });
