### ISSUE TITLE
`text` fields are occasionally corrupted

### ISSUE THREAD

**Issue by jonlambert** [sequelize/sequelize#4174]
I'm storing JSON in a `text` column in my MySQL database. Occasionally, this JSON is corrupted during the insert, and seems to truncate to only a few characters. This has happened to 4 records out of 576.

Any ideas what might be causing this?

<img width="799" alt="screenshot 2015-07-22 17 16 17" src="https://cloud.githubusercontent.com/assets/856225/8830669/5f21b0b8-3095-11e5-9734-1717989096ca.png">

**Comment by janmeier** [comment]
Perhaps an illegal character / something that is not escaped properly. Without a reproducible test case it's hard to say...

**Comment by jonlambert** [comment]
Yeah maybe that's it. I'll see if I can put together a reproducible example.

**Comment by jonlambert** [comment]
Ah you were right. I tried assigning to a different column, same issue occurred. Seems to be emoticons in utf8mb4 land that are killing the field. Unless Sequelize has a magic way to deal with this, it looks like I'll need to switch to the `blob` datatype (and/or upgrade MySQL). Thanks for pointing me in the right direction, @janmeier.

**Comment by janmeier** [comment]
Hmm, utf8mb4 should be able to store all chars though .. :D

There's no magic way to deal with it now, but hopefully there will be soon, once I get the rewrite of data-types done. That would allow you to create a custom stringify function for text that could convert the text to another encoding befeore inserting.

**Comment by janmeier** [comment]
Perhaps try setting the charset in your connection options, passed to node-mysql

```js
new Sequelize(..., {
  dialectOptions: {
    charset: 'utf8mb4'
  }
});
```
