### ISSUE TITLE
One-to-many relationship error

### ISSUE THREAD

**Issue by leonanluppi** [sequelize/sequelize#4175]
Hello,

I'm trying create a simple association, but I run I got this error: 
/Users/leonanluppi/Documents/_Dev/Projetos/vixmed/node_modules/sequelize/lib/associations/mixin.js:210
    throw new Error(this.name + '.hasMany called with something that\'s not an
          ^
Error: perfil.hasMany called with something that's not an instance of Sequelize.Model

This is my code: http://pastebin.com/5u3rdDQ4

**Comment by mickhansen** [comment]
Did you look at the error message? You're calling hasMany with something that's not a model.
Try to log the arguments you're passing to hasMany.

Looking at the code `models.Usuario` is likely undefined.

Closing since neither bug nor feature.
