### ISSUE TITLE
Decorate association

### ISSUE THREAD

**Issue by DeX3** [sequelize/sequelize#4178]
Hello,

I'm facing the following situation:

I have the following Models: `User`, `Group`, `Membership`, `Role` and `Permission`.

`User`s are members of `Group`s with a specific role. The `Membership`-model represents the relation between `User` and `Group` that contains the user's `Role` in that `Group`. A role is simply a set of `Permission`s.

Now, I want to check if a specific `User` has a specific `Permission` in a `Group`. I know I can get a `User` and their `Group`s with the following:

    return User.find( {
      where: {
        id: steve.id
      },
      include: [
        { model: Group }
      ]
    } );

This will automatically fetch the `User`'s `Group`s through their `Membership`s. It will even give me the role-id for each membership. But now I want to filter not on the role-id, but some other attribute in the Role table. How can I join in the `Role` as well?

**Comment by janmeier** [comment]
Can you show the models and assoications?

**Comment by DeX3** [comment]
Oh of course, sorry - here you go:

    var GroupModel = atlas.sequelize.define( 'Group', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false
      },
      description: Sequelize.STRING
    }, {
      hierarchy: true,
      timestamps: true,
      paranoid: true
    } );

    var RoleModel = atlas.sequelize.define( 'Role', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false
      },
      description: Sequelize.STRING
    }, {
      timestamps: false
    } );

    var MembershipModel = atlas.sequelize.define( 'Membership', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true
      }
    }, {
      timestamps: true,
      paranoid: true
    } );
    
    var UserModel = atlas.sequelize.define( 'User', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true
      },
      email: {
        type: Sequelize.STRING,
        allowNull: false
      }
    }, {
      timestamps: true,
      paranoid: true
      }
    } );

And here's all the relations:
    RoleModel.hasMany( MembershipModel );

    UserModel.belongsToMany( GroupModel, {
      through: {
        model: MembershipModel,
        unique: true
      }
    } );

    GroupModel.belongsToMany( UserModel, {
      through: {
        model: MembershipModel,
        unique: true
      }
    } );

    UserModel.belongsToMany( RoleModel, {
      through: {
        model: MembershipModel,
        unique: true
      }
    } );

    RoleModel.belongsToMany( PermissionModel, {
      through: 'PermissionRole'
    } );

    PermissionModel.belongsToMany( RoleModel, {
      through: 'PermissionRole'
    } );

I've omitted some unnecessary functions and properties.

**Comment by DeX3** [comment]
I was able to join in the `Role` model separately by doing:

    User.find( {
      where: {
        id: steve.id
      },
      include: [
        {
          model: Group,
          include: []
        },
        {
          model: Role
        }
      ]
    } );

But that will give me all the user's roles in all memberships and all the users groups in all memberships, while I want to have the user's role per membership.

**Comment by janmeier** [comment]
I that case you'll have to create an association directly between user and membership, role and membership etc so you can do:

```js
User.find( {
  where: {
    id: steve.id
  },
  include: [
    {
      model: Membership,
      include: [Role, Group]
    }
  ]
} );
```

**Comment by janmeier** [comment]
That means you will have `user.memberships[0].group`

**Comment by DeX3** [comment]
Veeery nice :thumbsup:.

For anyone interested in the future I had to define the following additional relations:

    RoleModel.hasMany( MembershipModel );
    UserModel.hasMany( MembershipModel );
    GroupModel.hasMany( MembershipModel );
    
    MembershipModel.belongsTo( UserModel );
    MembershipModel.belongsTo( GroupModel );
    MembershipModel.belongsTo( RoleModel );

**Comment by DeX3** [comment]
Thanks for the quick help!
