### ISSUE TITLE
BIGINT field is string in getterMethods

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#4181]
I have the next model:
```javascript
var Sequelize = require('sequelize');

module.exports = function () {
    return {
        attributes: {
            uuid            : Sequelize.STRING,
            ccc    : {type: Sequelize.BIGINT, allowNull: false},
            vvv   : Sequelize.BIGINT,
            bbb  : Sequelize.BIGINT
        },
        options: {
            getterMethods: {
                outstandingBalance: function() {
                    var ccc = this.ccc ? this.ccc : 0,
                        vvv = this.vvv ? this.vvv : 0,
                        bbb = this.bbb ? this.bbb : 0;

// the same if I do this.getDataValue('vvv') , I receive string as well

                    console.log(ccc, vvv, bbb);

                    return (ccc + vvv - bbb);
                }
            },
            classMethods: {},
            instanceMethods: {

            },
            tableName: 'xxx_calc'
        }
    };
};
```

Which produces the next to the console:
![image](https://cloud.githubusercontent.com/assets/839290/8851119/a926a124-314d-11e5-9f02-11cb1b9346e5.png)

The values are strings for some reason, however, if I would completely receive the model and print the value from the resolve method, the value of the ```ccc```, ```vvv``` and ```bbb``` would be number.

I mean here:
```javascript
YYY.find({ /* where */
                }).then(function (yyy) {
                    console.log(yyy.uuu.vvv);

                    return reply(yyy);
                });
```

Could you tell me how can I receive the ```number``` values in the ```getterMethods``` as well? Is that normal behaviour?

Regards,

**Comment by janmeier** [comment]
Which dialect is this on? Can you create a self-contained example that I can run?

**Comment by PavelPolyakov** [comment]
@janmeier 
What do you mean by dialect?

On the DB side it's Postgresql, the the xxx_calc is a view.

The wrapper around the model definition is custom, but it doesn't do much, the models are created as they should - afterwards.

So, this issues is unknown, and you expect that in getterMethods I should retrieve the values with their normal datatype?

Regards,

**Comment by janmeier** [comment]
By dialect I meant sql dialect, so you answered my question :-) 

I believe postgres would always return bigints as strings since there is no guarantee the value can be stored in a javascript number 

I don't think I've seen something like this before and how you access the value shouldn't matter. Can you create a self contained example that I can just copy paste and run.

**Comment by PavelPolyakov** [comment]
Here is the code, don't know if you can use it:

```javascript
/* create VIEW "ooo_balance_calc" (
    "id" int8,
    "xxx" int8,
    "yyy" int8,    
    "uuid" varchar(255)  
);
*/

var Sequelize = require('sequelize');
var postgres = require('pg');


var sequelize = new Sequelize('database', 'username', 'password', {
    dialect:  'postgres',
    protocol: 'postgres',
    port:     5832,
    host:     'host',
    logging:  console.log, //false

    dialectOptions: {
        ssl: true
    },

    pool: {
        max: 20,
        min: 0,
        idle: 5000
    }
});


var OOOBalanceCalc = sequelize.define('oooBalanceCalc', {
            uuid            : Sequelize.STRING,
            xxx    : Sequelize.BIGINT,
            yyy   : Sequelize.BIGINT
        }, {
            getterMethods: {
                outstandingBalance: function() {
                    var xxx = this.xxx ? this.xxx : 0,
                        yyy = this.yyy ? this.yyy : 0;

                    console.log(typeof this.xxx, this.getDataValue('xxx'), typeof this.yyy, this.getDataValue('yyy'));

                    return (xxx + yyy);
                }
            },
            classMethods: {
            },
            instanceMethods: {

            },
            tableName: 'ooo_balance_calc',
            timestamps: false
        });


OOOBalanceCalc.find({where: {uuid: 'fg13ub'}}).then(function(ooo) {
    console.log(ooo.toJSON());
});
```

The result of the execution:
![image](https://cloud.githubusercontent.com/assets/839290/8854555/b7465ed0-3160-11e5-9a3a-ed74d289b175.png)

Regards,

**Comment by PavelPolyakov** [comment]
Does this ticket makes sense?

**Comment by janmeier** [comment]
It seems it's strings all around in the example you posted? Which is as it should be, since bigint can't reliably be stored in javascript ints, right? Accessing properties directly or with get also returns strings

**Comment by PavelPolyakov** [comment]
ah, ok, I didn't knew that :) thank you

**Comment by janmeier** [comment]
Look into bignumber support in node myslq in you want numbers: https://github.com/felixge/node-mysql/#connection-options, in connection with `dialectOptions` http://docs.sequelizejs.com/en/latest/api/sequelize/#new-sequelizedatabase-usernamenull-passwordnull-options
