### ISSUE TITLE
Subtype/supertype schema possible?

### ISSUE THREAD

**Issue by jakemmarsh** [sequelize/sequelize#4183]
I'm using this library with PostgreSQL.

I have one type, `User`. The second type is `Group`, which can have any number of users associated with it through a `GroupMemberships` table. `User`s can also own any number of `Group`s. Essentially, User and Group are both subtypes of a supertype which can be thought of as `Party`.

My third type, `Playlist`, can belong to either a `User` OR a `group` (so, any `Party`).

Someone on StackExchange [has helped me](http://dba.stackexchange.com/questions/107919/database-schema-for-entities-with-two-possible-owner-parent-types) come up with [this schema](https://www.dropbox.com/s/34vth8ut1iws2rx/Playlist%20Owners%20Data%20Model%20-%20Option%201.pdf). However, I'm not sure if this is possible to currently implement in Sequelize. I believe this may be a case of polymorphism, and I've read through #1307 to no avail as I don't believe this can be solved through the scope feature. So my question is, is this possible? If so, how?

**Comment by janmeier** [comment]
Perhaps something like proper table inheritance, now that you're using postgres would be better? https://github.com/sequelize/sequelize/issues/1679

No promise when that will be implemented though :)

I'm pretty sure this could be implemented with poly. associations, although probably not exactly like you show.

More likely there will be two separate tables, user and group, and playlist has a `party_id` and a `party_type`, which can be either user or group

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

But feel free to comment further in this issue, since we've already started :)
