### ISSUE TITLE
One-To-Many (hasMany) relationship through a join table - specifying foreign key and target key

### ISSUE THREAD

**Issue by alockwood05** [sequelize/sequelize#4185]
What is the best way to define a HasMany relationship specifying both foreign_key and target key when using a join table. 

Given the models:

- `Person` , 
- `Document`, and 
- `PersonDocumentXref` ( with my_person_fk, my_document_fk)

It works to do a many to many relationship: 
```
Person.belongsToMany( Document, {
  as: 'Documents',
  through: PersonDocumentXref,
  foreignKey: 'my_person_fk',
  otherKey: 'my_document_fk'
});
```

But in my case it can only be a 1:m relationship, even though the schema supports n:m.  How can I do the same with `hasMany`?

This does not work: 
```
Person.hasMany( Document, {
  as: 'Documents',
  through: PersonDocumentXref,
  foreignKey: 'my_person_fk',
  otherKey: 'my_document_fk'
});
```

**Comment by janmeier** [comment]
`otherKey` and `through` are only supported by belongsToMany

**Comment by alockwood05** [comment]
Thanks! 

FYI Documentation Error:  API -> Associations -> Overview -> hasMany lists `options.through` as an optional argument


Found the src, in "lib/associations/has-many.js",  good error message. :)
```
  if (this.options.through) {
    throw new Error('N:M associations are not supported with hasMany. Use belongsToMany instead');
  }
```

**Comment by janmeier** [comment]
Oh, then I understand your confusion - should be corrected in a minute :)
