### ISSUE TITLE
Using jxcore Issue

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/sequelize#4188]
I am using jxcore to compile my nodejs application which uses Sequelize as ORM and I am able to get the .exe file but I get the error defineCall is not a function when I run the .exe file
![error](https://cloud.githubusercontent.com/assets/8342604/8888020/41bab012-32b9-11e5-831c-49b7602a5dd0.png)

**Comment by zeeshanjan82** [comment]
The error is coming in this code in sequelize.js under lib folder in node_modules
  Sequelize.prototype.import = function(path) {
    // is it a relative path?
    if(Path.normalize(path) !== Path.resolve(path)){
      // make path relative to the caller
      var callerFilename = Utils.stack()[1].getFileName()
        , callerPath = Path.dirname(callerFilename);

      path = Path.resolve(callerPath, path);
    }

    if (!this.importCache[path]) {
      var defineCall = (arguments.length > 1 ? arguments[1] : require(path));
      this.importCache[path] = defineCall(this, DataTypes);
    }

    return this.importCache[path];
  };

**Comment by zeeshanjan82** [comment]
Further analyzing the issue. It is coming because I am using following like in my index.js file which is present inside models folder to load all my models.
var model = sequelize['import'](path.join(__dirname, file));

**Comment by zeeshanjan82** [comment]
Further analyzing the issue. It is coming because I am using following like in my index.js file which is present inside models folder to load all my models.
"var model = sequelize['import'](path.join(__dirname, file));"

**Comment by zeeshanjan82** [comment]
Further analyzing the issue. It is coming because I am using following like in my index.js file which is present inside models folder to load all my models.
var model = sequelize['import'](path.join(__dirname, file));

**Comment by janmeier** [comment]
Do you only experience this issue with a jxcore compiled exe, or does it also happen if you urn the program with plain node.

It could seem like the model you are importing does not export a function like this 

```js
module.exports = function (sequelize, datatypes)
```

**Comment by janmeier** [comment]
@zeeshanjan82 Any progress?

**Comment by janmeier** [comment]
Closing, no response

**Comment by zeeshanjan82** [comment]
I really apologize for the late response and will never happen again. Yes the issue was mainly related to sequelize and its settings. It was nothing to do with jxcore. After changing some lines in the above code things started to work.

**Comment by janmeier** [comment]
No worries at all, we can be a bit slow to respond at times as well ;-)

**Comment by pamio** [comment]
@zeeshanjan82 what fixed it. Im having a very similar issue (In fact the same). Its again due to index.js file. Could you tell me what fixe it ?

**Comment by jchristi** [comment]
@pamio I was having the same issue as well. What happened was that I had some incomplete models in the `models` directory (ie. some model files had errors in them). You can either delete the incomplete/erroneous models, correct all errors in all model files or change the filter function to only import your completed models. Hope that helps!

**Comment by pamio** [comment]
@jchristi yes you are right! after after posting this question, I deleted most of my models and keep just two and it started working. Later, I found that there was one model that was causing the issue and fixed it.  Thanks for the help! 
Cheers!

**Comment by lovelstn** [comment]
Hi, I am using electron and am finding the line `Utils.stack()[1].getFileName()` is resolving to `undefined`.

Has anyone else experienced this?
