### ISSUE TITLE
Unmanaged transactions, CLS and tests

### ISSUE THREAD

**Issue by gagoman** [sequelize/sequelize#4189]
Good day. This is a duplication of https://github.com/sequelize/sequelize/issues/3888 with some extended examples.

`version` == `3.4.1`

So, here is basic setup:
1. Application, that uses `sequelize` transactions and create instance of db like:
```
const createDb = (conf, namespaceName='my-super-personal-namespace') => {
  const {uri} = conf;
  const namespace = cls.createNamespace(cls);

  Sequelize.cls = namespace;

  const options = Object.assign({}, conf); // Sequelize doesn't work with frozen

  const sequelize = new Sequelize(uri, options);
  const Thing = sequelize.import('./thing');

  return {
    sequelize,
    Thing,
    _namespace: namespace
  };
};
```

2. And here goes a test:

```
let db;
let transaction;

before(() => {
  db = createDb(config);

  return db.sequelize.sync();
});

beforeEach(() => db.sequelize
    .transaction({autocommit: false})
    .then(t => {
      transaction = t;
    }));

afterEach(() => transaction.rollback());

after(() => db.sequelize.drop());

it('should create instance of Thing', () => {
  return db.Thing.create({
    name: 'foo'
  }, {transaction}).then(thing => {  // FIXME: bad for tests
    expect(thing.id).to.be.a('number');
    expect(thing.name).to.be.eql('foo');
  });
});
```

This code works but it requires manual pass of `transaction`.

I've expected that following code would work, but it fails in `afterEach`:
```
let db;

before(() => {
  db = createDb(config);

  return db.sequelize.sync();
});

beforeEach(() => db.sequelize
  .transaction({autocommit: false})
  .then(t => {
    db._namespace.set('transaction', t);
  }));

afterEach(() => db._namespace.get('transaction').rollback());

after(() => db.sequelize.drop());

it('should create instance of Thing', () => {
  return db.Thing.create({
    name: 'foo'
  }).then(thing => {
    expect(thing.id).to.be.a('number');
    expect(thing.name).to.be.eql('foo');
  });
});
```

Could you advice please what is a best way to solve this issue?

Thank you!

**Comment by janmeier** [comment]
If I read your code correctly, this is never going to work with CLS. The transaction is only available in the `then` callback:

```js
beforeEach(() => db.sequelize
  .transaction({autocommit: false})
  .then(t => {
    db._namespace.set('transaction', t);
    /* ANY FUNCTION CALLED FROM HERE CAN ACCESS t */
  }));
```

But nothing is done in that callback - after it finished, then context is cleared, because that callback / promise chain ends. 

`Thing.create` should be called from inside the callback:
```js
it('should create instance of Thing', () => {
  return db.sequelize.transaction().then(function (t) {
    db._namespace.set('transaction', t);
    return db.Thing.create({
        name: 'foo'
      }).then(thing => {
        expect(thing.id).to.be.a('number');
        expect(thing.name).to.be.eql('foo');
        return t.rollback();
      });
    });
  });
});
```

You can also do it slightly more succinctly, by using a managed transaction
```js
return db.sequelize.transaction(function () {
  // No need to call namespace.set here - sequelize takes care of that
});

**Comment by gagoman** [comment]
I understand that I can use `db.sequelize.transaction().then()` and use `transaction` inside. But this approach isn't test-friendly.

Just assume that you need to test some code that uses transactions but not available for tests. E.g.:

```
const myVeryOwnCreate = user => db.sequelize.transaction(() => { // transaction was created
    /* blah-blah-blah */
    db.User.create(/* ... */);  // transaction is used, everything is ok
});
```

And now I wanna test my code, directly or not.

Basic approach for DB integration tests is:

* create transaction for tests
* run tests inside that transaction (tests can create their own transactions and even commit them)
* rollback it in the end

As far, as I can see, the only way to say to `sequelize` that `transaction` is started is to pass it as an
option. We (I mean application developers, test writers) can not always do this. E.g.

```
it('should ...', () => {  // some pseudocode
    return request(app)
       .post('users/create', {/* definition */})
       .then(() => {
           expect(db.Users.find().length).to.eql(1);
        });
});
```

Code behind `post` uses `sequelize.transaction(t => /* create user */)` and it's works perfectly,
expect one case - it will not use our manually-rollbacked transaction.

It would be commited to DB and it would make our tests slow. DB need to be flushed each time.

Sorry for my bad English, I hope you've got an idea.

**Comment by janmeier** [comment]
Yes, I understand - but CLS does not directly support that usecase, since `beforeEach` and `it` are on different contexts. You could do:

```js
it('should ...', () => {  // some pseudocode
    return 
db.sequelize
  .transaction({autocommit: false})
  .then(t => {
    db._namespace.set('transaction', t);request(app)
       .post('users/create', {/* definition */})
       .then(() => {
           expect(db.Users.find().length).to.eql(1);
        });
});
```

I know this is not very elegant, but that's the only way to do it - This is not related to sequelize, but to how context works with CLS

**Comment by gagoman** [comment]
Update:

My code with `CLS` can be done like this and it would work, but it is not so ideal.

```
let db;
let transaction;

before(() => {
  db = createDb(config);

  return db.sequelize.sync();
});

beforeEach(() => db.sequelize
    .transaction({autocommit: false})
    .then(t => {
      transaction = t;
    }));

afterEach(() => transaction.rollback());

after(() => db.sequelize.drop());

it('should create instance of Thing', () => {
  db._namespace.set('transaction', transaction);

  return db.Thing.create({ // Voila, transaction is binded
    name: 'foo'
  }).then(thing => {
    expect(thing.id).to.be.a('number');
    expect(thing.name).to.be.eql('foo');
  });
});
```

**Comment by gagoman** [comment]
Thanks a lot for clarification about context flush. It's helped me to find a solution, I've posted earlier.

And thanks for a great orm for `node.js`!

**Comment by janmeier** [comment]
@gagoman Yeah that would work too, and looks slightly more elegant :)

Thanks for the praise :D

If you want to read more up on CLS, have a look here https://github.com/othiym23/node-continuation-local-storage

**Comment by puyo** [comment]
This is what I have that seems to work OK for me:

```js
const Runnable = require('mocha/lib/runnable')
const __oldRunnableRun = Runnable.prototype.run
Runnable.prototype.run = function(fn) {
  if (this.type === 'hook') {
    __oldRunnableRun.bind(this)(fn) // as you were
  } else {
    return models.sequelize.transaction().then(transaction => {
      models.Sequelize.cls.set('transaction', transaction)
      __oldRunnableRun.bind(this)(err => {
        transaction.rollback()
        fn(err)
      })
    })
  }
}
```

**Comment by guseinovmg** [comment]
Hi develepers, 
It works but if inside test we create separate transaction, it doesn't roll back.
Do you have any idea how to fix this?

**Comment by janmeier** [comment]
@guseinovmg Please show some code

**Comment by guseinovmg** [comment]
```
describe('API all methods', function () {
    describe('Create order', function () {
        it('should blablabla', function (done) {
            var t;
            db.sequelize.transaction({autocommit: false}, function (_t) {
                t = _t;
                return api.methodForTest().then(function () {
                    return t.rollback();
                });
            }).then(function (res) {
                console.log(res);
                done();
            }).catch(function (err) {
                if (err && err.message&& err.message.match(/rollback/)) {
                    done();
                    return;
                }
                done(err);
            });
        });
    });
```
Inside of  api.methodForTest() there is simple update call, without transaction.
It works fine - this update executes in transaction and successfully roll back.
But if inside  api.methodForTest() there is another transaction, it works independently and not rolled back.

**Comment by guseinovmg** [comment]
Also I notice that {autocommit: false} did not really prevent transaction from commiting. (is it bug?)

**Comment by janmeier** [comment]
Please post a complete, self contained example that we can use to replicate the issue - [SSCCE](HTTP://SSCCE.ORG/)

**Comment by leebenson** [comment]
FWIW, I use the following async transaction wrapper in my test code, which rolls back a transaction regardless of the outcome - but still propagates the error back down to Mocha.

Note: This is using native promises which @overlookmotel has advised can have unintended side-effects with CLS. You can use his `cls-bluebird` wrapper with Bluebird v3 once it's released, for a more solid/tested solution (I've only ever gone 'one level deep' with this):

```javascript
// Wrap promisified function in a transaction block
export function transaction(func) {
  return db.sequelize.transaction().then(async t => {
    Sequelize.cls.set('transaction', t);
    try {
      await func();
    } finally {
      await t.rollback();
    }
  });
}
```

**Comment by overlookmotel** [comment]
@leebenson [cls-bluebird](https://www.npmjs.com/package/cls-bluebird) v2 has been released now and there's a PR pending for Sequelize to use it internally.

Yeah, it's not safe to use with async/await unless the transpiler is converting that code to generators wrapped with `Bluebird.coroutine` with the `cls-bluebird` patch applied to Bluebird. Which it probably isn't!

But @guseinovmg's problem with nested transactions isn't likely related to that. Hard to know without seeing a full example from him.

**Comment by leebenson** [comment]
awesome @overlookmotel, I'll look out for the merge.

The transpiler [I'm currently using](https://babeljs.io/docs/plugins/transform-async-to-generator/) definitely doesn't. But [this does](https://babeljs.io/docs/plugins/transform-async-to-module-method/).

As soon as the PR has merged, I'll defo make the switch.

**Comment by overlookmotel** [comment]
The [transform-async-to-module-method](https://babeljs.io/docs/plugins/transform-async-to-module-method/) babel plugin *does* use `Bluebird.coroutine()` but it *doesn't* apply the [cls-bluebird](https://www.npmjs.com/package/cls-bluebird) patch. So it won't work.

You *could* somewhere else in your code patch the global bluebird instance with:

```js
require('cls-bluebird')( ns, require('bluebird') ) // (ns is the CLS namespace to use)
```

That'll work but isn't ideal. In general, altering globals isn't a good idea - it might in some weird circumstances break something in another module which also does `require('bluebird')` or, worse, some other module might alter the bluebird global and so screw up your code.

Hmm... I get the feeling this is going to be a common problem.

**Comment by overlookmotel** [comment]
@leebenson No need to wait for Sequelize to start using cls-bluebird to make the switch. You can what I suggested above right now and it'll be better than what you have now. Sequelize currently has it's own CLS shim which seems to work almost 100% with most things except coroutines, but it's just not as well-tested as cls-bluebird.
