### ISSUE TITLE
findAndCountAll() and count() pollutes options.includes object

### ISSUE THREAD

**Issue by atorkhov** [sequelize/sequelize#4191]
findAndCountAll() and count() pollutes options.includes object that was passed to the call. This is a problem if I want to store and reuse query options sometime later.

**Comment by mickhansen** [comment]
We need `options = Model.$optClone(options)` about here: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1494

**Comment by harish2704** [comment]
Yes.  I can confirm that at-least Mode.count method pollutes the options .
Because of this bug, A typical pagiante function like this 
```javascript
var store = {};
return model.count(modelOpts)
.bind(store)
  .then(function(count){
    this.count = count;
    var paginationParams = {
      count: count,
      page: paginationOpts.page,
      size: paginationOpts.size,
    };
    var pagination = paginator.paginate( paginationParams );
    this.pagination = pagination;
    modelOpts.offset = pagination.start-1;
    modelOpts.limit = pagination.size;
    return model.findAll( modelOpts );
  });
```
Is not working.
