### ISSUE TITLE
Postgres decimals/numeric handling changed in 3.5.1?

### ISSUE THREAD

**Issue by cwhatley** [sequelize/sequelize#4197]
For numeric/decimal fields, I'm getting numbers instead of strings back in queries and insert/update is failing when strings are provided now.

Is there a setting now for getting one behavior or the other or are numeric/decimals going to be "numbers in/numbers out" now?

**Comment by mickhansen** [comment]
@janmeier we are parsing decimal/numeric? won't there be a precision loss?
@cwhatley we introduced type validators for all types, so strings aren't allowed as allowed as numbers as vice verca, we're considering reverting that since the RDBMS can usually handle number to string and inverse, but not sure yet.

**Comment by janmeier** [comment]
As far as I know there hasn't been anything merged yet to parse stuff yet, only validation :-). I

**Comment by janmeier** [comment]
I believe decimals have always been returned as numbers, but I night be wrong 

I'll make the string and number validations less strict

**Comment by cwhatley** [comment]
FYI, definitely new. My integration tests are expecting string in and returning string out for 3.4.1, but they are expecting number in and returning number out on 3.5.1.

I'm not against this behavior at all. If I recall correctly, it makes postgres and mysql decimal/numeric treatment consistent.

It would be good to know it is a permanent state of affairs, to have the validation, and to have test case coverage.

**Comment by janmeier** [comment]
On master, this returns string in my tests:

```js
var User = sequelize.define('u', {
  test: Sequelize.NUMERIC
})

sequelize.sync({
  force: true
}).bind({}).then(function() {
  return User.create({
    test: 4.2
  })
}).then(function(user) {
  return User.findById(1);
}).then(function(user) {
  console.log(user.test);
  console.log(typeof user.test);
});
```
Same applies for DECIMAL

Which node-pg version are you on? I'm testing in 4.4.0

**Comment by janmeier** [comment]
I don't see any type parser for numeric (1700) in [node-pg-types](https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js) either, so I have no idea whats converting them :D

**Comment by Americas** [comment]
the problem that breaks my tests, and I'm sure is the same as @cwhatley, is here:

```javascript
User.create({
    test: "4.2" -- pass a string instead of a decimal
  })
```

I also want to know if this is a permanent change, or are you going to allow strings once again?

**Comment by janmeier** [comment]
@Americas its a bug, this shouldn't have been a breaking change - I'll make the validations less strict

**Comment by cwhatley** [comment]
@Americas thanks for isolating that. I should have done that initially.

It would be great to still have validations on numerics that check if a string is numeric.

I do like the added validations, but I'm a little afraid to put it into production without a bunch of testing. A option to warn instead of error on validation failure would be welcome.

**Comment by janmeier** [comment]
Merged into https://github.com/sequelize/sequelize/issues/4314

**Comment by kirill-zhirnov** [comment]
Sorry, but I still have the issue in 3.6.0.
Should it be fixed in 3.6.0 or not?

**Comment by mickhansen** [comment]
@kirill-zhirnov Look at the referenced issue.

**Comment by murvinlai** [comment]
yes. still an issue with 3.6.0

**Comment by janmeier** [comment]
@murvinlai Look at the referenced issue

**Comment by jeffprandall** [comment]
I also am having this issue even with 3.10.0 but I do have a magic build running sequelize 3.3.2 and postgres 9.4.1 (9.3.9 and 9.4.4 both fail.)

**Comment by janmeier** [comment]
@jeffprandall Look at the referenced issue (like everyone else should)
