### ISSUE TITLE
validation for fields with UUID type is run against parameters for LIKE queries

### ISSUE THREAD

**Issue by nemophrost** [sequelize/sequelize#4198]
MyModel.findAll({ where: { id: { $like: "12345678%" } } })

results in a validation error: "12345678%" is not a valid uuid

**Comment by BridgeAR** [comment]
This should probably be fixed by #4186

**Comment by janmeier** [comment]
@BridgeAR, how will datatypes refactoring fix this? :-) 

I'm thinking more along the lines of restricting some validations to only run on create, and making it possible to completely disable them

**Comment by janmeier** [comment]
Merged into https://github.com/sequelize/sequelize/issues/4314
