### ISSUE TITLE
options.timezone support with MSSQL

### ISSUE THREAD

**Issue by ace234b** [sequelize/sequelize#4199]
Hello,

It appears that the ability to treat datetime fields as a specific timezone is not implemented with MSSQL. I have set the option in my config.json and the datetime fields are still being treated as UTC. 

I am using Sequelize 3.4.1. with Tedious 1.11.2. I have also confirmed via SQL Profiler that a SET related to timezones is not occurring. 

Is this as expected? If so it would probably be best to document it in the options.timezone notes. 

One way it could be possible to implement this is to rely on the tedious UseUTC option (http://pekim.github.io/tedious/api-connection.html#function_newConnection). But I'm not sure on the implications of to Sequelize's functionality. I have only tested querying data after specifying this option in the connection-manager.

**Comment by janmeier** [comment]
Definitely a bug - bug weird that our regression tests are not catching it... 

I don't think the `useUTC` option will be enough - since the user can specify other timezones, and not just utc or local

Come to think of it, sequelize inserts mssql dates with timestamp info (e.g. `2015-07-28 14:24:34.000 +07:00`) and so the parsing happens automagically - we don't actually have tests for timestamp without timezone. As that what your're seeing?

**Comment by ace234b** [comment]
I'm encountering the problem reading data from a database via a model. I have not tested writing datetimes yet.

I'll try and give a better example to illustrate the problem.

The following is stored in a datetime field, so time zone info is not stored by SQL Server. It is only stored in a datetimeoffset field. 

25/02/2014 1:42:51 AM

Unfortunately, I'm working with an application that stores all its dates in 'localtime' which is always 'Australia/Sydney'.

When I read the data, sequelize assumes that this is a UTC date, so when I call Date.toString(), I end up with an output that's actually 10 hours ahead of what is in the database. I could call Date.toUTCString, which outputs the correct time, albeit with the wrong timezone. But this is a bit too counter intuitive for my liking. 

I was hoping for a way to tell sequelize 'Assume all datetime fields are timezone Australia/Sydney rather than UTC'

**Comment by janmeier** [comment]
Yeah, definitely a bug then - the way you are describing it is the way its supposed to work :)

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/5403
