### ISSUE TITLE
Unable to Connect using the "replication" option

### ISSUE THREAD

**Issue by DubFriend** [sequelize/sequelize#4201]
I get an ECONNREFUSED error if I try to connect to my database this way.

```javascript
new Sequelize('database-name', null, null, {
        dialect: 'mysql',
        port: 3306,
        replication: {
            read: [{
                host: '10.0.33.38',
                username: 'username',
                password: 'password',
                pool: {}
            }],
            write: {
                host: '10.0.33.38',
                username: 'username',
                password: 'password',
                pool: {}
            }
        },
        pool: {
            maxConnections: 20,
            maxIdleTime: 30000
        }
});
```

However I am able to connect using the same database using the normal connection method

```javascript
new Sequelize(
        'database-name',
        'username',
        'password',
        { host: "10.0.33.38", dialect: 'mysql', port: 3306 }
)
```

I am using mysql version 2.6.2 and sequelize version 3.5.1

**Comment by janmeier** [comment]
Hmm, we have tests for this, so there is not much to go on with the information you have given. Try to go into https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js to see if the all parameters are being assigned correctly for the replicas

**Comment by janmeier** [comment]
@DubFriend Any progress?

**Comment by janmeier** [comment]
Closing, no response

**Comment by anibali** [comment]
I'm having the same problem. It looks like getConnection is being called, which uses global config that is not present because we are using replication. Check out `ConnectionManager.prototype.getConnection` from `abstract/connection-manager.js`. I can't see how our replicas are ever used.

**Comment by mickhansen** [comment]
@anibali replication pools are setup here: https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L86

**Comment by mickhansen** [comment]
@anibali But we do have: https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L212 which checks for versions and stuff, that might very well fail in a replication environment!

Please open a new issue.
