### ISSUE TITLE
dropSchema and createSchema allowing SQL injection

### ISSUE THREAD

**Issue by billxinli** [sequelize/sequelize#4202]
```
var reportingSchema = 'report CASCADE; CREATE SCHEMA if not exist foo --'
return sequelize.dropSchema(reportingSchema)
```

Is this the intended behaviour? if so, how can one ensure `reportingSchema` is escaped properly as a literal? 

Currently using: 2.0.5, changelog did not specify any injection fixes for releases after 2.0.5.

**Comment by mickhansen** [comment]
Not sure we've ever considered that as a vector since we hadn't considered using end-user supplied values for creating a schema.

I guess we can escape them as we do tables, if that is allowed, although i have no idea if table names are injection proof.

**Comment by wstallard-gobalto** [comment]
Docs for dropSchema/createSchema should probably reflect their potential as a SQL injection vector...
