### ISSUE TITLE
Rename "include.seperate" to "include.separate"

### ISSUE THREAD

**Issue by SimonDegraeve** [sequelize/sequelize#4204]
Since it is derived from the name "sep**a**ration".

From [wiktionary.org](https://en.wiktionary.org/wiki/seperate):

> seperate [adjective]
Misspelling of separate.

> seperate [verb]
Misspelling of separate.

**Comment by mickhansen** [comment]
Can you point to a place where this is the case?
Pretty sure i did a search/replace after Jan pointed out my mistake.

**Comment by SimonDegraeve** [comment]
[https://github.com/sequelize/sequelize/search?utf8=%E2%9C%93&q=seperate](https://github.com/sequelize/sequelize/search?utf8=%E2%9C%93&q=seperate)

**Comment by mickhansen** [comment]
Ah so an internal method and the changelog, i'll update the changelog now but the other stuff is not too important.
