### ISSUE TITLE
Sequelize ignores milliseconds part of DATETIME in MySQL

### ISSUE THREAD

**Issue by DominikPalo** [sequelize/sequelize#4205]
I'm using MySQL database with some columns of type DATETIME(3) (datetime with precision 3). Also in the entity model I have defined type as DATE(3). But after I set property of instance to time with millisecond part (e.g. entity.openedAt: "2015-08-29T08:39:08.12345Z"), sequelize generates SQL query, that truncates the millisecond part (...`openedAt`='2015-08-29 08:39:08'...).  

> MySQL 5.6.4 and up expands fractional seconds support for TIME, DATETIME, and TIMESTAMP values, with up to microseconds (6 digits) precision.

**Comment by janmeier** [comment]
Dates don't support length at all right now - Actually I didn't even know that dates could have a length in mysql - I'm still on 5.5 :)

Anyhow, this should be pretty easy to do once https://github.com/sequelize/sequelize/pull/4186 has landed. Just change the stringify function for mysql date to check this.length to see if it should add milliseconds

**Comment by mfbx9da4** [comment]
+1 also having this problem using sequelize 3.19.2 when should this be working

**Comment by sobotklp** [comment]
How did you declare the column saved_timeout_time in your model?

**Comment by sobotklp** [comment]
Also, which version of MySQL are you running?

**Comment by mfbx9da4** [comment]
Model declaration:

```js
var scheduled_matches = sequelize.define("scheduled_matches",{
	saved_timeout_time:{type:DataTypes.DATE, allowNull:true}
});
```


Local 
`mysql  Ver 14.14 Distrib 5.6.27, for osx10.11 (x86_64) using  EditLine wrapper`
On server 
`mysql  Ver 14.14 Distrib 5.5.48, for Linux (x86_64) using readline 5.1`

**Comment by sobotklp** [comment]
In order to use millisecond-aware DATETIME columns, you'll have to use
`type: DataTypes.DATE(3)`

**Comment by mfbx9da4** [comment]
Oh right sorry for wasting your time! Where is this documented?

**Comment by sobotklp** [comment]
I don't believe it is documented anywhere, but I will change that tomorrow.

**Comment by sobotklp** [comment]
#5575 adds documentation to the Data Types definitions list.

**Comment by chaoyangnz** [comment]
> In order to use millisecond-aware DATETIME columns, you'll have to use
> `type: DataTypes.DATE(3)`

Does this affect the MySQL column type or just how Sequelize is aware of milliseconds?

**Comment by ephys** [comment]
Normally both
