### ISSUE TITLE
DATE returned as raw string if timezone is set (MySQL)

### ISSUE THREAD

**Issue by balintbako** [sequelize/sequelize#4208]
We are using MySQL and sequelize 3.2.0 (the issue exists in 3.5.2 as well).
The model is the following:
```javascript
module.exports = function(sequelize, DataTypes) {
	var SequelizeTest = sequelize.define('SequelizeTest', {
		id : {
			type : DataTypes.INTEGER,
			primaryKey : true,
			autoIncrement : true
		},
	    testDate: DataTypes.DATE

	}, {
		tableName : 'tgb_sequelize_test',
		timestamps : true
	});
	return SequelizeTest;
};

```
Running the same call with and without a "timezone" setting in data.json give different "testDate". It returns a Date object if "timezone" is not set but it returns a string when it is set.
```javascript
models.SequelizeTest.findAll().then(function(testItemsResp){
	for(var i = 0; i < testItemsResp.length; i++){
		console.log(testItemsResp[i].testDate.getHours());
	}
}).catch(function(err){
	console.log(err);
});	
```

This is the data.json in use (with "timezone"):
```json
"dev": {
	"username": "...",
	"password": "...",
	"database": "...",
	"host": "127.0.0.1",
	"dialect": "mysql",
	"timezone": "Europe/London"
}
```
For some reason the SELECT query seems to be handled as "raw" so the date parsing doesn't take place.

**Comment by janmeier** [comment]
Note to self - fix this in https://github.com/sequelize/sequelize/pull/4186

Right now the date parsing happens in node-mysql which uses native dates, and `new Date('2015-07-29 15:22:52 Europe/London')` gives `Invalid Date`. We should take over this parsing and use moment instead

For now you can fix this by using timezone offset instead

**Comment by balintbako** [comment]
Thank you for the feedback!

Only thing is that timezone offset doesn't handle Daylight Saving Time (BST for London) so we had to change the offset to +01:00 at the beginning to BST and then to +00:00 at the end of it.

**Comment by janmeier** [comment]
I know, and I very much hope to have that PR merged before the new DST change ;). It was merely offered as a temporary fix

**Comment by BridgeAR** [comment]
@janmeier it would also be nice to support the [postgres special values] (http://www.postgresql.org/docs/9.4/static/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-TABLE) :)

**Comment by janmeier** [comment]
@BridgeAR Postgres can keep those in the DB! If someone wants that kind of magic, they can use moment :)

**Comment by ebrian** [comment]
I use the follow config with `System`:
```
{
    "development": {
        "username": "username",
        "password": "password",
        "database": "db",
        "host": "127.0.0.1",
        "dialect": "mysql",
        "logging" : false,
        "timezone" : "System",
        "define" : {
            "underscored" : true,
            "timestamps" : false
        }
    }
}
```

and all of my dates are now "Invalid Date".

This appears to be in >= 3.19.3
