### ISSUE TITLE
Scope applies to find but not create during findOrCreate call

### ISSUE THREAD

**Issue by ktsashes** [sequelize/sequelize#4212]
Right now I've got a scoped Model and am trying to do a `Model#findOrCreate()` on a table with two fields: `name` and `category`. `category` is scoped on the model to always be a specific value for the file I'm in, and I'm trying to do bulk find/creates for several different values.

From looking through the code, it looks like the `findOne` call is getting the scoped values, but the create is not. Values are inserted into the table without the scope values, which means a second `findOrCreate` will create a duplicate entry

Here's a quick example:

``` js
var Model = require('./myModel');
Model.scope('cats').findOrCreate( { where: { name: 'Cheshire' } } ).then(function () {
    // Will create a second instance in the DB
    Model.scope('cats').findOrCreate( { where: { name: 'Cheshire' } } );
});
```

**Comment by janmeier** [comment]
Hmm, yeah I see the issue here, but I'm not sure about the best way to solve it. Normally, scopes are not applied to create, only to the where part of find / update / destroy etc. Do you agree that we should make an exception and let scopes supply default values here @mickhansen ?

**Comment by mickhansen** [comment]
@janmeier I'm unsure, i think that is likely to be the users intent since we copy where to values for create.

**Comment by janmeier** [comment]
I agree, that must be the intent, and the case that @ktsashes describes here is definitely not logical :)

I'll change it and mention this special case in the API docs

**Comment by ktsashes** [comment]
Yeah, sorry, I should have explained it better. I'm doing a `findOrCreate` as part of my server initialization to seed in some values and am getting duplicates when my server restarts. My expectation was that it would copy over values from the `where` in the scope just like it does for the `where` from the search. Or, alternatively, provide a different way to provide defaults in the scope or something. Just basically something where I can prevent these duplicates and do this create as part of my startup.

**Comment by radhomero** [comment]
I also want to `build` or `create` an instance of a Model within a previous defined `scope`.

Example:
 
```js

myModel = sequelize.define('MyModel', {
  registry_status: sequelize.INTEGER,
  detail: sequelize.STRING
}, {
  scopes: {
    open: {
      where: {
        registry_status: 1
      }
    }
  }
});

instance = myModel.scope('open').build({
  detail: 'TEST'
};
>>> { detail: 'TEST', registry_status: undefined }   //actual output

```

I would like the method `build` to consider the scope and auto define the field `registry_status` within the `scope` (i.e.: 1).

**Comment by lbustelo** [comment]
👍

**Comment by mimon** [comment]
Any updates on this bug?

**Comment by border-buddy** [comment]
bump

**Comment by callmekatootie** [comment]
Is there a work around for this? I tried deleting the field (that I did not want to be returned when the record gets created, for example, the password field) in the `afterCreate` hook instead. While the hook does get called, it appears to still send the field back even though I delete the field and then pass it.

Example:
```
hooks: {
          afterCreate: [
              (user, options, cb) => {
                  delete user.password;
                  cb(null, user);
              },
          },
}
```

Here, the password field is still passed. (Note that I am not using `findOrCreate` but just `create`)

**Comment by hank-ehly** [comment]
@callmekatootie 

I'm dealing with this by reloading the instance returned from `findOrCreate`.

```javascript
let [user] = await User.findOrCreate({
    where: {
        email: profile.email
    }
});

user = await user.reload();
```

**Comment by jeffmoss** [comment]
I've been looking and I don't see this reported anywhere else, but I think it may be related to this issue. Let me know and I'll create a new issue.

The problem I have is the scope on my association (a "polymorphic" association) is working when I call parent.addSingular(data), but not when I say Parent.create({ ..., children: [{...}]}, {include:[MyAssociation]}). Here are a couple examples, notice that periodicType is missing from the first example.

First, the association definition looks like this:
```
    Income.PeriodicEvents = Income.hasMany(models.PeriodicEvent, {
        as: name,
        foreignKey: 'periodicUuid',
        constraints: false,
        onDelete: 'cascade',
        hooks: true, // required for onDelete cascade to work
        scope: {
            periodicType: Income.name
        }
    });
```

Then I run this code:
```
            models.Income.create({
                id: 1,
                amount: 100000,
                paychecks: [{
                    date: yesterday
                }]
            }, {
                include: [models.Income.PeriodicEvents]
            });
```

And it yields this:
```
INSERT INTO "PeriodicEvents" ("uuid","periodicUuid","date","createdAt","updatedAt") VALUES (...)
```
It's missing the periodicType scope.

BUT, if I do this:
```
            models.Income.create({
                id: 1,
                amount: 100000
            }).then((_income) => {
                _income.createPaycheck({ date: yesterday });
            });
```

I get this, which is correct:
```
INSERT INTO "PeriodicEvents" ("uuid","periodicType","periodicUuid","date","createdAt","updatedAt") VALUES (...)
```

It would appear that scopes need to be refactored a bit. Something is missing from the "create" functionality when it comes to scopes.
