### ISSUE TITLE
Issue with instance from many to many relationship

### ISSUE THREAD

**Issue by bloodhawk** [sequelize/sequelize#4213]
Here are the associations: 

```js
models.projects.belongsToMany(models.people, { through: models.peopleProjects });
models.people.belongsToMany(models.projects, { through: models.peopleProjects });	
models.peopleProjects.hasMany(models.projectChannels, { foreignKey: 'peopleProjectsId' });
```
Here is the code I'm running:
```js
schemas.sequelize.sync({ force: true, logging: false })
.then(function(){
   return schemas.models.people.create({ name: 'Aaron' });
}).then(function(){
   return schemas.models.project.create({
     name: 'Test',
  });
}).then(function(project){
  return project.addPeople(1, { contractStatus: 'started' });
}).then(function(peopleProject){
  //I expect peopleProject to have a method createProjectChannel on it
  //Instead I get back a nested array.
 //I see peopleProject[0][0] which has a createProjectChannel 
 //I can call that and it creates a record, but it does not fill peopleProjectsId with
 // the instance of peopleProject that I have.
 /* I can do:
  (person is an instance of a person I created earlier)
   person.getProjects().then(function(projects){
     projects[0].dataValues.peopleProjects.createProjectChannel({})
   });
and that works, but it is ugly. 
*/	
```
It seems odd that a returned instance would be nested within two arrays.

**Comment by janmeier** [comment]
That's because we use the same method for adding a single and adding multiple associated people internally. https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L624 

The return value you are seeing is the result of `promise.all` on a bulkCreate + update (we update since an entry may be associated already.

There is no general good solution for this, since `bulkCreate` cannot return the primarykey of the new records. That's also why `peopleProjectsId` is not set. 

I'm afraid the solution you posted in the comment is the post for now (you don't need `.dateValues` though)

**Comment by bloodhawk** [comment]
I'm aware of an option that was mentioned in another issue (https://github.com/sequelize/sequelize/issues/2630) where I can set ```returning: true```. With the latest version of Sequelize when I set returning to true it doesn't give me the primary keys for a bulk create. They are all null. Is there any way we could get the instance method to have ```returning: true``` set and have it work that way. Thanks for your assistance and explanation above.

**Comment by janmeier** [comment]
You should be able to just pass returning in the second object `  return project.addPeople(1, { contractStatus: 'started', returning: true });` (looks kinda weird to mix join table attributes with options, I know...

Mind you that `returning` is only supported by postgres though (mssql supports something similar with output inserted, but I don't know if it works for bulkcreate)

**Comment by bloodhawk** [comment]
Thank you again for your explanations. Marking this as closed. Everything seems to be working as intended.
