### ISSUE TITLE
managed transactions

### ISSUE THREAD

**Issue by xwu20** [sequelize/sequelize#4214]
Hi, 

I am trying to create managed transactions with sequelize 3.5.1 and I have some questions around rolllback.

I have a .catch(error) at the end of my promise chain and I notice the following:
Scenario A) If I don't throw an error in the .catch, the flawed transaction will not roll back
Scenario B) If I do throw an errror in the .catch, the flawed transaction will roll back. 

Wanted to verify that is expected behavior, or if I'm doing something incorrectly. Thanks!

Sample code below: 

```js
exports.postPlugin = function postPlugin(req, res) {
    respond(req, res, sequelize.transaction(function(t) {
        return metadata.create({plugin_id: req.body.plugin_id, git_repo: req.body.git_repo, jenkins_job: req.body.jenkins_job, contacts: req.body.contacts, cdn_url: req.body.cdn_url}, {transaction: t})
            .then(function(){
                return deployments.create({plugin_id: req.body.plugin_id, plugin_version: req.body.plugin_version, qbo_version: req.body.qbo_version, approved_by: req.body.approved_by}, {transaction: t})
            })
            .then(function(){
                return history.create({plugin_id: req.body.plugin_id, plugin_version: req.body.plugin_version, qbo_version: req.body.qbo_version, approved_by: req.body.approved_by, new_deployment: req.body.new_deployment, note: req.body.note}, {transaction: t})
            })
            .then(function(result){
                console.log("success!");
            }).catch(function(error) {
                console.log("error!" + error);
                //throw new Error(error); 
            })
    }))
```

**Comment by mickhansen** [comment]
Please format your code, otherwise it's near impossible to read.

**Comment by xwu20** [comment]
exports.postPlugin = function postPlugin(req, res) {
    respond(req, res, sequelize.transaction(function(t) {
        return metadata.create({plugin_id: req.body.plugin_id, git_repo: req.body.git_repo, jenkins_job: req.body.jenkins_job, contacts: req.body.contacts, cdn_url: req.body.cdn_url}, {transaction: t})
            .then(function(){
                return deployments.create({plugin_id: req.body.plugin_id, plugin_version: req.body.plugin_version, qbo_version: req.body.qbo_version, approved_by: req.body.approved_by}, {transaction: t})
            })
            .then(function(){
                return history.create({plugin_id: req.body.plugin_id, plugin_version: req.body.plugin_version, qbo_version: req.body.qbo_version, approved_by: req.body.approved_by, new_deployment: req.body.new_deployment, note: req.body.note}, {transaction: t})
            })
            .then(function(result){
                console.log("success!");
            }).catch(function(error) {
                console.log("error!" + error);
                throw new Error(error);
            })
    }))
};

**Comment by xwu20** [comment]
welp. github un-formats my code.

**Comment by DanMMX** [comment]
@xwu20 give a look at https://guides.github.com/features/mastering-markdown/

**Comment by janmeier** [comment]
@xwu20 That is definitely expected behaviour. Catch in promises works just like catch in other languages. If you catch an error, you have to rethrow it if you want it to propagate it to other handlers.
