### ISSUE TITLE
accessing renamed attributes

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#4221]
Hi,

It that true, that when I do the next:
```javascript
var application = yield Application.find({where:{uuid:'hbh7yg'},attributes:[['uuid','x']]});
                    console.log(application.x);
```

I only am able to access the renamed attribute through ```.get()``` method, and I am not able to access it directly.

I mean:
```javascript
   console.log(application.x); // undefined
   console.log(application.toJSON().x); // hbh7yg
   console.log(application.get('x')); // hbh7yg
```

Here http://sequelize.readthedocs.org/en/latest/api/model/index.html?highlight=find#findalloptions-promisearrayinstance it says:
> and the second is the name you want the attribute to have in the returned instance

The version of the sequelize is 3.5.1.

Regards,

**Comment by mickhansen** [comment]
`instance.prop` is technically deprecated and only available for model defined attributes.
Define a virtual attribute if you wish to use the alias.

**Comment by PavelPolyakov** [comment]
Thanks
