### ISSUE TITLE
include with required set to false eager load the record even if the include.where clause is not satisfied

### ISSUE THREAD

**Issue by Verdier** [sequelize/sequelize#4223]
The following is broke since the latest version 3.5.x:
```js
Operation.addScope('defaultScope', {
    include: [Transaction]
}, {
    override: true
});

Operation.addScope('actives', {
    include: [{
        model: Transaction,
        required: false,
        where: {
            deleted: false
        }
    }]
});

User.hasMany(Operation.scope('actives'), {
    foreignKey: 'ownerId',
    as: 'activeOperations'
});
```
Getting the `activeOperations` does not include the `transaction`:
```js
let operations = yield user.getActiveOperations();
operations[0].transaction; // this is null.
```
but this works:
```js
let operations = yield user.getOperations();
operations[0].transaction; // this is not null.
```

**Comment by Verdier** [comment]
We use  `co` so the `yield` statement here wait for the promise to resolve, and return the result.

**Comment by Verdier** [comment]
I think that's because of the order of scope declarations, and not a sequelize issue. I confirm in a minute.

**Comment by Verdier** [comment]
No, I confirme the issue.

**Comment by janmeier** [comment]
Both seem to work fine for me. Does the SQL look correct / give the right result if you run it manually?

**Comment by Verdier** [comment]
I just get the real problem, with the following declaration:
```js
Operation.addScope('defaultScope', {
    include: [Transaction]
}, {
    override: true
});

Operation.addScope('actives', {
    include: [{
        model: Transaction,
        required: false,
        where: {
            deleted: false
        }
    }]
});
```
Here is what I do:
```js
let operations = yield Operation.scope('actives').findAll();
```
But compared to the precedent sequelize version, `operations` also contains operation with `deleted` transactions, but for them `operation.transaction` is `null`. In the previous version of sequelize, `operations` only contains operation with non `deleted` transactions.

**Comment by Verdier** [comment]
I need to set `required` to `false` because:
- some `operation` doest not have a transaction => I want them,
- some `operation` have a non deleted transaction => I want them,
- some `operation` have a deleted transaction => I *don't* want them.

**Comment by janmeier** [comment]
When you say them, are you refering to operations or transactions? I.e suppose an operation has a deleted transaction, do you just want to skip the deleted transction, or do you not want the operation at all?

Also, can you show the model definitions and assoications?

**Comment by Verdier** [comment]
@janmeier I don't want the operation at all, and that how sequelize works in version < 3.5.x

here is the associations:
```js
Operation.belongsTo(Transaction);
Transaction.hasOne(Operation);
```

**Comment by Verdier** [comment]
That's not relative to scopes, I've the same problem with the following:
```js
Operation.belongsTo(Transaction);
Transaction.hasOne(Operation);

let operations = yield Operation.findAll({
    include: [{
        model: Transaction,
        required: false,
        where: {
            deleted: false
        }
    }]
});
```

**Comment by janmeier** [comment]
Are you sure that worked on pre 3.5? I doesn't for me. As far as I can figure out, it would need a query on the main where clause:
```sql
SELECT ...
FROM ..
LEFT JOIN on ...
WHERE transaction.deleted = false OR operation.transactionId IS NULL
```

**Comment by Verdier** [comment]
Yep, I'm absolutely sure because of our regression.

**Comment by janmeier** [comment]
Hmm, but what would that join query look like?

**Comment by Verdier** [comment]
Just a minute, I'm fetching an old version of the project.

**Comment by Verdier** [comment]
Mmmm, looks like your are right... that's very very strange. Looks like the issue was older than I was expecting... Do you know a solution to have something like a query on the main where clause ?

**Comment by janmeier** [comment]
An API is being discussed in https://github.com/sequelize/sequelize/issues/3095. Feel free to chime in so we can hopefully soon finalize it :)
