### ISSUE TITLE
Get a .findOne data and directly use that data for a .create

### ISSUE THREAD

**Issue by kasszz** [sequelize/sequelize#4225]
Dear sequelize users,

The title says it all :)

The .findOne has a lot of includes and that changes a lot of times. So I want this to be as dynamic as possible. The problem that I have now is that de id's are defined and maybe that the connections wont be correct.

Hopefully you can help,

Casper

**Comment by janmeier** [comment]
The title doesn't say it all to me unfortunately  :) I'm not sure what you want to do. If you need the raw data from an object you can call `instance.get()`

**Comment by kasszz** [comment]
oh sorry.

But that raw data can't be a create({object}) again because of the id's, right?

**Comment by janmeier** [comment]
So do you want to basically find a row and clone it? You can delete the id from the data before calling `create`

**Comment by kasszz** [comment]
Will that work with an instance with all it's relations ?

**Comment by janmeier** [comment]
There is support for [nested creation](https://github.com/sequelize/sequelize/pull/3386) for belongsto and hasmany - its still experimental, so no guarantees though

**Comment by janmeier** [comment]
!Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
