### ISSUE TITLE
Is there something similar to ActiveModel::SecurePassword in Sequelize?

### ISSUE THREAD

**Issue by rainierwolfcastle** [sequelize/sequelize#423]
I'm trying to achieve something similar to SecurePassword in Sequelize. SecurePassword has a class method, has_secure_password, which encrypts a password when a model is created and an instance method, authenticate, which is called on an instance of a model by a controller to match a password.

I can do something similar to authenticate by attaching an instance function in the model's define function but I'm struggling to work out how I can implement the has_secure_password function. Is there an easy way way I can override the build and create functions in sequelize so I can call a has_secure_password-like function?

**Comment by richmarr** [comment]
There's a module for this:

https://github.com/defunctzombie/sequelize-encrypted
