### ISSUE TITLE
Associations with unsigned PKs on legacy tables

### ISSUE THREAD

**Issue by laholmes** [sequelize/sequelize#4231]
I'm migrating a MySQL database to Sequelize. Generally fine, but there's a problem with keying between new and legacy tables

If I add two new tables A, B as sequelize models, both get unsigned PKs, and I can setup a relationship between them in the standard way:

![screen shot 2015-07-31 at 09 59 53](https://cloud.githubusercontent.com/assets/3737627/9004064/e660114c-376a-11e5-9e8b-5e1aee5b680a.png)

However I can't setup a relationship between A and C in the same way, where C is an existing table with a signed PK (MySQL inserts signed PKs by default). So I have to declare the column on the model for A, like below:

![screen shot 2015-07-31 at 09 55 01](https://cloud.githubusercontent.com/assets/3737627/9003955/39e7202c-376a-11e5-8381-2f475fbda59b.png)

This will work, however now I have my relationship setup in two disparate places on the model, which is unnecessary complexity. I saw a separate issue raised relating to allowing for creation of unsigned PKs on sequelize models, but perhaps it would also be nice to be able to pass config to the relationship itself, setting the type of the foreign key, as otherwise you have no control over how the foreign key is created.

Hopefully the next person who has this issue will find this post, as it took me a while to solve

**Comment by janmeier** [comment]
You can pass an object to the foreignKey definition:

```js
a.belongsTo(C, { foreignKey: { name: 'c_id', type: DataTypes.INTEGER(11).UNSIGNED }})
```

By the way, please post code instead of images in the future. [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown/)

**Comment by laholmes** [comment]
Thanks, and sure. It would be useful if this were documented somewhere
