### ISSUE TITLE
Relations, hasMany - find() analog

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#4233]
Hi,

I have a ```hasMany``` relation, but want to make a query which return only one record.
Do I have this option in some way?

Relations:
```javascrtipt
models.UUU.hasMany(models.ExternalData, {foreignKey: 'uuu_id'});
```

Execution:
```javascrtipt
uuu.getExternalData({
    where: {
        service: 'XXX'
    },
    order: [
        ['updated', 'DESC']
    ],
    raw: true
}).then(function(ed) {
    console.log(ed); // returns array
});
```

Do I have any option to order the single record with such kind of relation (like limit:1, and receive an instance, not array)?
It looks like not, as I read the documentation, but if in any case I can - this would be cool.

Regards,

**Comment by janmeier** [comment]
You can add limit 1 to get only a single instance, but it will still be an array. You can do `uuu.getExternalData().get(0).then(function (` to fetch the first element of the array though

**Comment by PavelPolyakov** [comment]
Thanks!
