### ISSUE TITLE
[bug] belongsToMany generates timestamps in query

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#4235]
I have the next relation:
```
models.User.belongsToMany(models.Role, {through : 'user__role', foreignKey : 'users_id', otherKey : 'roles_id'});
```

Runs ok on 3.4.1, but, on 3.5.1 it fails, because the next SQL query is generater
```sql
SELECT
  "role"."id",
  "role"."name",
  "role"."client",
  "user__role"."createdAt" AS "user__role.createdAt",
  "user__role"."updatedAt" AS "user__role.updatedAt",
  "user__role"."users_id"  AS "user__role.users_id",
  "user__role"."roles_id"  AS "user__role.roles_id"
FROM "role" AS "role" INNER JOIN "user__role" AS "user__role"
    ON "role"."id" = "user__role"."roles_id" AND "user__role"."users_id" = '000';
```

the thing is, that ```createdAt``` and ```updatedAt``` fields are added.
Both ```roles``` and ```user``` tables have ```timestamps     : false``` .

**Comment by janmeier** [comment]
Do you have timestamps set to true globally? In that case we will use that option, instead of the one from the tables https://github.com/sequelize/sequelize/commit/52dbeb3b4e093a09dad3e8e719f329905a9288a1. You can now  also pass `timestamps: false` directly to the association

**Comment by JeasonLaung** [comment]
Oh my god! The bug is exist in 2023 which version is `6.31.0`.
I use `timestamp: false` and it still exist `***->createAt`

**Comment by JeasonLaung** [comment]
It's working when I write like this!😂
`include: [{
    model: RoleModel,
    through: {
      attributes: ['id', 'role_id', 'user_id']
    },
    attributes: ['id', 'name'],
  }],`

**Comment by ephys** [comment]
Please open a separate bug report with a reproducible example instead
