### ISSUE TITLE
Difference when saving for eager/lazy loaded instances?

### ISSUE THREAD

**Issue by ciscoheat** [sequelize/sequelize#4240]
Hi, if I'm including some models when loading an instance, (eager loading), I guess saving the instance won't save the entities loaded in the relation? If not, is there some way to save all the related entities (including creating new ones), or do I have to keep track of that manually?

**Comment by janmeier** [comment]
I haven't tested this, but due to nested creation, you may be able to pass an `include` option to save - try it out

```js
// a has a .bs property, which holds an array of related bs

a.save({
  include: [B]
});
```

**Comment by ciscoheat** [comment]
Yes, that looks promising. Thanks!
