### ISSUE TITLE
Updating the same record multiple times in transaction doesn't work

### ISSUE THREAD

**Issue by lvarayut** [sequelize/sequelize#4241]
I'm trying to update the same record twice in order to update its attribute, named `balance`. Here is a demonstration of my code:

```javascript
for(var i = 10; i <= 20; i+=10) {
    db.Budget.find({
        where: {
            id: 1
        }
    }).success(function(obj) {
            obj.balance = 10+i;
        }
        obj.save({
            transaction: transaction
        }).success(function(obj) {
            callback(null, obj);
        }).error(function(err) {
            console.error(err);
            callback(err);
        });

    }).error(function(err) {
        callback(err);
    });
}
```

The first update was correctly updated with: 

```
UPDATE `Budgets` SET `balance`=205000,`updatedAt`='2015-08-01 16:44:32' WHERE `id`=1`.
```

However, the second one didn't update the balance, the balance wasn't set: 

```
UPDATE `Budgets` SET `updatedAt`='2015-08-01 16:44:32' WHERE `id`=1`.
```

I don't know exactly what's the problem. I'm using `2.0.0-rc3`, I didn't update the newer version because of breaking change. Any help would be appreciated.

**Comment by schester44** [comment]
What is the fix for this? i'm having a similar issue

**Comment by papb** [comment]
@schester44 this issue is too old. If you are experiencing a similar issue, please open a new one (and include a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example))

**Comment by furqanpolani** [comment]
facing same issue
