### ISSUE TITLE
Scope create callback object is not populated

### ISSUE THREAD

**Issue by makrolabs** [sequelize/sequelize#4242]
Simple example:

    Animal.addScope("test", {
        include: Shelter
    }
    
    Animal.scope("test").create({
         name: "Tiger",
         shelterId: 43
    }).then(function (tiger) {
         // tiger.shelter should exist here bud does not
    })

**Comment by janmeier** [comment]
This does not work for normal includes either - the only usecase for include in create is [nested creation](https://github.com/sequelize/sequelize/pull/3386)

Scope is only meant for findAll, and the where parts of update, delete etc

**Comment by makrolabs** [comment]
I think there is a great need for this function, not just for nested creation. A scope is a view of the data and this view usually needs updating after using CREATE and UPDATE. The example in my initial post does not have nested creation, but we still need the joined data when returning the object in a RESTful service.

**Comment by janmeier** [comment]
> this view usually needs updating after using CREATE and UPDATE

What do you mean by this? Scopes also apply to `save` / `update`

To me it doesn't make sense if `create` is also doing select queries to fetch related data. It may be slightly more code to write, but I think its more clear if you add a simultenous find to fetch the related shelters

```js
Promise.all([
  Animal.create({
    name: "Tiger",
    shelterId: 43
  }),
  Shelter.findById(43)
]).spread(function (tiger, shelter) {
  tiger.set('shelter', shelter);
})
```

**Comment by makrolabs** [comment]
By that I mean a client-side view of the data that he obtained through a previous query of the scope. You are right, in the example rewriting the include is not much hassle. A better example would look more like this:

Animal.addScope("test", {
    include: [{ 
        model: Shelter,
        include: [{
            model: Organization,
            include: Country
        }]
   }, {
      model: Picture
   }]
}

In this case, it would make the code very redundant and cluttered to rewrite the scope's includes for every find, create, update statement. This is nescessary because each time we want to return the scoped object so that the client can update its view of the data.

I think if you explicitly use a scope to create the data, it would be logical to that the returned object is scoped as well. Otherwise I could just use the non scoped model for creation.
