### ISSUE TITLE
transaction does not clean up with sqlite

### ISSUE THREAD

**Issue by ssteffl** [sequelize/sequelize#4245]
IDK if this affects other dialects but i am using sqlite3. 

Transactions are not getting removed from the connectionManager because the connection uuid is getting set to undefined before the connection is released. This might lead to long term resource  leaking.

The [old code found here](https://github.com/sequelize/sequelize/blob/f678009d7514b81a6f87e12b86360e9a597e3ca8/lib/transaction.js#L216-L225):

    Transaction.prototype.cleanup = function() {
      var cls = this.sequelize.constructor.cls;

      this.connection.uuid = undefined;

      if (cls) {
        if (cls.get('transaction') === this) {
         cls.set('transaction', null);
        }
      }

What i did to fix it (currently used as an override in my code, no PR, sorry):
    
    Transaction.prototype.cleanup = function() {
		var cls = this.sequelize.constructor.cls;
		if(cls && cls.get('transaction') === this) cls.set('transaction', null);
		
		return this.sequelize.connectionManager.releaseConnection(this.connection);
	};

**Comment by codyrigney92** [comment]
@ssteffl I can confirm this issue.  Applying your fix worked for me.  This is a hugely significant issue for sqlite users because every query opens and leaks a file handle.  Thus memory usage grows continually and you reach the limit of maximum number of file handles.

**Comment by mickhansen** [comment]
@ssteffl would love a pull request :)
