### ISSUE TITLE
instance.increment does not work

### ISSUE THREAD

**Issue by jungseob86** [sequelize/sequelize#4250]
in 3.5.1, instance.increment('columnName') does not work.
```
Model.findOne({where: {id: 1}})
        .then(function(model) {
          return model.increment('version', {by:1});
        })
        .then(function(affectedRows) {
          // affectedRows.version does not increase
          return affectedRows;
        })
        .nodeify(cb)
```

**Comment by janmeier** [comment]
Please define

**Comment by janmeier** [comment]
Ah, didn't see your comment 

The field does not update in the model because we don't know what the value is. Instead of incrementing the value in the model by one we let the db do the increment eg version = version + 1

You'll need to do a reload to get the value
