### ISSUE TITLE
increment and decrement should support RETURNING * in postgres

### ISSUE THREAD

**Issue by jungseob86** [sequelize/sequelize#4253]
```
sequelize.define('Model', { version: Sequelize.INTEGER });
var modelFixture = {version: 1};

Model.create(modelFixture)
  .then(function(model) {
    return model.increment('version');
  })
  .then(function(model) {
    console.log(model.toJSON())
    done();
  })
  .catch(function(err) {
    console.log({err:err});
    done();
  });
```

in 3.0.0 result is
```
{ version: 2 }
```

in 3.5.1 result is
```
{ version: 1 }
```

so, I try to reload instance.
```
Model.create(modelFixture)
  .then(function(model) {
    return model.increment('version');
  })
  .then(function(model) {
    return model.reload();
  })
  .then(function(model) {
    console.log(model.toJSON())
    done();
  })
  .catch(function(err) {
    console.log({err:err});
    done();
  });
```
then, result is
```
{ version: 2 }
```

Oh, thanks! :)

But my question is, why do i need to reload the instance in 3.5.1, when it worked without a reload in the previous version? I can't find any reason in changelog.

**Comment by janmeier** [comment]
Are you using postgres? In that case, try passing `returning: true`, which will return the updated value. 

Otherwise, I really don't know how that worked before. It has always been mentioned in the API docs that you need to do a `reload` to get the new value

**Comment by jungseob86** [comment]
@janmeier Yes, I am using postgres. So I try passing `{returning: true}` option like `instance.increment(['field'], {returning: true})`. But It wasn't return the updated value too. Is that right?

**Comment by janmeier** [comment]
Hmm yeah, the query is correct, but it seems we are not acually handling the returned values and putting them into the model - tagging this as a feature request, but as always it probably gonna be fixed faster if you look into it yourself. I'll be happy to offer guidance, shouldn't be a lot of work required

**Comment by jungseob86** [comment]
@janmeier Thanks! I'll try!

**Comment by jungseob86** [comment]
@janmeier I saw few codes.

**Comment by Bibernull** [comment]
Have been using sequelize for quite a while, and increment/decrement always updated the instances.

not sure when/if this was changed, could be something else recently changed in how it handles RAW queries.

if we look at query-interface.js increment method, it sets the query type to RAW.

https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L684

changing it to UDPATE, successfully updates the instance.

**Comment by janmeier** [comment]
@jungseob86 That is definitely a hack - `reload` issues a new query, so that would get the updated values. However, that's not the idea of `returning`, the idea is that the db should return the values.

@Bibernull raw query handling was changed, but that was in the last major version. 
I can't see any problems with changing it to `types.UPDATE` instead -  PR welcomed! :)
