### ISSUE TITLE
Casting JSON fields in where clause

### ISSUE THREAD

**Issue by tmont** [sequelize/sequelize#4257]
I can't really figure if this is supported or not. I'm basically trying to query by equality on a boolean value inside a JSON object:

```javascript
MyModel.findAll({
  where: {
    someJsonColumn: {
      someProperty: {
        $eq: true
      }
    }
  }
})
```

This throws a n`operator does not exist: text = boolean` error. Basically the query needs a `::boolean` cast at the end of it, and I'm not totally sure if that's even possible in Sequelize.

As a workaround, I can just change `true` to `'true'`, but I'd rather not do that if I don't have to.

**Comment by janmeier** [comment]
I think I talked with @mickhansen about this previously, and we'd really like this to be transparent for the user, so the value is casted automagically.

**Comment by mahnunchik** [comment]
Hi @janmeier  @mickhansen how to cast values in JSON? 

Related: https://github.com/sequelize/sequelize/issues/11998
