### ISSUE TITLE
Would like to make some Oracle.

### ISSUE THREAD

**Issue by gintsgints** [sequelize/sequelize#4261]
Hi,

I am on my way to make oracle dialect aiviable. But here goes some questions:
- what would be best way to push code? Should I do fork and give for you to review?
- autoincrement is only available from latest oracle version. Do you recommend first to make it "oracle way" with sequences so we get bigger audience?

**Comment by janmeier** [comment]
Interresting idea. We have been open to merging user supported dialects before, but generally there are two requirements:

1. Someone (most likely you :)) commits to maintaining the dialect after it has been added. This does not mean you have to fix every issue related to it, but you'd need to help out, since we don't have much exprience with oracle.
2. We need to be able to test it on travis, since oracle is not supported natively https://github.com/travis-ci/travis-ci/issues/689. Our current solution for mssql is to have some instances running on azure that are teoretically open to anyone. It has been working fine so far. Would you / someone you know / your company / a random kind stranger be interested in providing something similar? (I'm assuming you're doing this work for some company?)

As for how to share it - yes, definitely a pull request

As for autoincrement, thats your call - do what you feel like, and if you can do both that's awesome :). I seems knex chose to use sequences exclusively https://github.com/tgriesser/knex/pull/419 - maybe AI was not available at that time?


Cool that you want to make this contribution, and I hope we can work something out! :)

**Comment by janmeier** [comment]
Cross-ref https://github.com/sequelize/sequelize/issues/1836, https://github.com/sequelize/sequelize/issues/3013

**Comment by gintsgints** [comment]
Can you suggest template for new dialect?

**Comment by janmeier** [comment]
Hmm, not really a template, but I think the easiest would be to just look at one of the existing :)

Start out by getting the stuff in connection-manager set up right so you can actually connect. connection-manager.js creates a connection object, while query.js sends the actual query. 

From there start with a blank query-generator that just clones all methods from the abstract one. Then implement the methods that are not implemented in the abstract one. Then start overriding those that are special to oracle. If the difference is small, you can use  `dialect.supports` instead, and add your modification to the abstract query generator.

I know that's not much to go on, but its hard to give a recipe when every dialect is different. Feel free to keep asking questions here or on irc

**Comment by gintsgints** [comment]
Oki. Sounds like this issue could be closed.

And yes.. I would be ready to look after oracle issues.

**Comment by williamgueiros** [comment]
@gintsgints 

i see this projects: https://github.com/lebretr/sequelize-oracle
and relative travis-ci problem: https://github.com/lebretr/test-travis-oracle

I don't know  if @lebretr have idea to putting, dialect on the project sequelize but have a lote of working on that.

@gintsgints do you start this oracle feature ??

**Comment by gintsgints** [comment]
Yes.. I did start work on that at my fork:

https://github.com/gintsgints/sequelize

90% tests are working. But seems like 10% will be hardest ones.

**Comment by williamgueiros** [comment]
@janmeier i saw contribution information and yours worry before, if @gintsgints finish tests , do you thing possible add to project oracle support ?

@gintsgints do you believe, is possible enumerate your problem to help you?

**Comment by janmeier** [comment]
@williamgueiros If my two points above are fulfilled then yes - we need someone comitted to support it (at least once in a while), and a way to test it on travis. Someone has to sponsor some oracle servers. Perhaps @oracle is interested, given their devotion to developing an official node driver?

@gintsgints If you're 90% there on the tests, then I think its time to open your PR and we can start reviewing the code and work out the last tests together

**Comment by mickhansen** [comment]
Oracle has a community edition that might be possible to install on travis.

**Comment by williamgueiros** [comment]
@mickhansen in this project https://github.com/cbandy/travis-oracle , using Oracle Database Express Edition, for me is good, do you have other idea ??

**Comment by mickhansen** [comment]
@williamgueiros yeah that should work.

**Comment by janmeier** [comment]
My only issue with installing oracle ourselves is time - if we have to add 5 minutes to each job to install each time (install.sh takes 280 seconds on travis https://travis-ci.org/cbandy/travis-oracle/builds/64203395) that would be a problem. But perhaps we can use travis' caching features to cache the compiled binaries so we only have to install them?

**Comment by mickhansen** [comment]
@janmeier should only happen for oracle builds, should be doable by looking at the current ENV.

**Comment by janmeier** [comment]
@mickhansen Sure, but ideally I'd like to cache it anyway - but yeah I guess it would be okay :)

**Comment by mickhansen** [comment]
Yeah caching the compiled binary would be ideal :)

**Comment by gintsgints** [comment]
I was thinking I first need to solve travis test stuff, before making PR.

But I created PR for review.
https://github.com/sequelize/sequelize/pull/4586

**Comment by williamgueiros** [comment]
:heart:  \o/

**Comment by williamgueiros** [comment]
@gintsgints do you want to help in your Pr ???

**Comment by gintsgints** [comment]
Go on. Now we have stoped on travis build. @williamgueiros I will assign you rights to commit to my fork.

**Comment by hariprasadkulkarni** [comment]
@gintsgints How can I help you in this?

**Comment by gintsgints** [comment]
You can clone my repo and fix  tests. Then make merge request.

**Comment by hariprasadkulkarni** [comment]
@gintsgints Is there a better way to discuss with you? Your fork of sequelize needs some commits from the main repo for `jshint` issues.

**Comment by gintsgints** [comment]
Merge done. But I could recomend move fork development discussions on my fork.

**Comment by DemersM** [comment]
@gintsgints I have stop following your progress with this few months ago. I see you are still active with this project. Do you need someone to test?

**Comment by gintsgints** [comment]
There is big changes made in sequelize driver part. Lot of job done should be rewritten. But still most important part is how to make automatic build tests to work.
https://travis-ci.org/gintsgints/sequelize

**Comment by williamgueiros** [comment]
@gintsgints I worked on that before, do you what help ?

**Comment by williamgueiros** [comment]
https://github.com/gintsgints/sequelize/pull/2

**Comment by hariprasadkulkarni** [comment]
@gintsgints Are you working on this currently?

**Comment by gintsgints** [comment]
Sadly no. Because first there should be solved problem of Integration Test execution for Travis CI
