### ISSUE TITLE
Is there a way to exclude an attribute? 

### ISSUE THREAD

**Issue by kasszz** [sequelize/sequelize#4262]
Dear Sequelizers,

I'm trying to exclude an attribute from my models.<object>.findAll(). The reason why I really want to exclude the attribute and not include all the other attributes is because the model changes a lot, so the attributes will change all the time.

Hopefully I informed you enough to answer my question.

Casper

**Comment by janmeier** [comment]
Not currently :)

Duplicate of https://github.com/sequelize/sequelize/issues/4074

**Comment by boiawang** [comment]
+1
