### ISSUE TITLE
Add root properties to object instances returned from sequelize

### ISSUE THREAD

**Issue by bkniffler** [sequelize/sequelize#4263]
Hey, 
I've created a library that essentially adds a `context: {}` property to object instances returned from queries, so I can pick the context up in hooks. The context is used to pass individual properties from express requests, for example the user.

Is it save to use that method? I imagine this is kinda hacky.

```
{
   dataValues: {...},
   context: {...},
   _previousDataValues: {...}
}
```

Full code: https://github.com/bkniffler/express-sequelize-user

**Comment by janmeier** [comment]
I don't see any immediate problems with this, but no guarantees ;)

We've never used the word context, so I don't think it will be overridden internally or removed

**Comment by bkniffler** [comment]
Okay, I'll keep it that way for now then, thanks!
