### ISSUE TITLE
BelongsToMany with through model wipes out existing associations on the join table

### ISSUE THREAD

**Issue by sorin** [sequelize/sequelize#4266]
Failing test here: https://github.com/sorin/sequelize/commit/37d2cb6c4d68f761b6bd0b3212d30030de1f0772
First test fails but the second passes

**Comment by janmeier** [comment]
Pull-request, pretty pretty please :)

Also, this would fit better as a unit test, since it doesn't hit the DB. It could also be expressed as `expect(this.UserProjects.Instance.prototype.getUser).to.be.ok`

**Comment by sorin** [comment]
Working on the fix, thanks for the fast reply

**Comment by sorin** [comment]
I thought I had a fix https://github.com/sequelize/sequelize/pull/4267 but it seems to break other things. I'm not familiar enough with the codebase at this point to figure out the proper fix. The problem is that BelongsToMany.injectAttributes is calling model.init and thus wiping out any previously applied associations.

**Comment by janmeier** [comment]
Have you tried with refresgAttributes instead of init?

**Comment by sorin** [comment]
Thanks, that seems to make the Sqlite tests pass but not the others

**Comment by sorin** [comment]
My bad, I had an issue within the tests themselves. Seems like refreshAttributes did the trick, here's the PR: https://github.com/sequelize/sequelize/pull/4268
