### ISSUE TITLE
 New issue targetKey not working as expected 

### ISSUE THREAD

**Issue by peze** [sequelize/sequelize#4269]
i want to use the One-To-One associations like that
```js
serviceType.belongsTo(orderRecord, { targetKey: 'service_id',foreignKey:'service_id',constraints: false });
    orderRecord.hasOne(serviceType, { foreignKey: 'service_id' });
    orderRecord.findAll({
        include: [{
            model: serviceType
        }]
    })
```
as you see ,i have use the targetKey in belongsTo,but it doesn't work ,the OrderRecord still use it's primary key.... im very cofused...how to deal with it?

**Comment by janmeier** [comment]
Merged into https://github.com/sequelize/sequelize/issues/4258
