### ISSUE TITLE
Bulk update

### ISSUE THREAD

**Issue by mikalai-ramashka** [sequelize/sequelize#4270]
Hi,

I would like to update some rows in database with sql multiple statements like below:
`update ... set ... where id=?;
update ... set ... where id=?
.....`

I found that it can be done with options  `multipleStatements: true`. But how can I generate correct sql script for these. I think it can be generated with QueryGenerator class. Could you suggest right way to do this?

**Comment by janmeier** [comment]
Theoretically you could probably use the query generator directly, but since its not public API I'd advice against it .

You can use [model.update](http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows) to run the queries individually

**Comment by mikalai-ramashka** [comment]
I cannot imagine what happens if I start update at least 100 rows with  model.update.

**Comment by janmeier** [comment]
Yes, you would probably need some kind of rate limiting. I was just suggesting an approach that could work if you want to do this in plain sequelize. Otherwise you'll have to generate the sql yourself, or fiddle with the query-generator which, again, isn't public API :)
