### ISSUE TITLE
model wide instanceMethods collection completely overwritten when a model has any delcared instanceMethods

### ISSUE THREAD

**Issue by trevorlanyon** [sequelize/sequelize#4272]
When using sequelize 3.5.1 and declaring instanceMethods at the Sequelize level any instanceMethod declared at model level destroys the Sequelize level declared instanceMethod collection.

Example:

    var sequelize = new Sequelize(settings.dbConnectionString, {
      define: {
        instanceMethods: {
          getInputHTML: function(property, options) {
            return "<input name="' + property + "' value="' + this.get(property) + '">";
          }
        }
      }
    }

    module.exports = function(sequelize, DataTypes) {

      return sequelize.define('User', {
        id: {
           type: DataTypes.UUID,
           defaultValue: DataTypes.UUIDV1,
           primaryKey: true,
           allowNull: false
        }
      },{                                      
        tableName: 'user',                     
         underscored: true,                     
         freezeTableName: true,                 
         instanceMethods: {                     
           touchLastLogin: function() {                       
             this.updateAttributes({lastLoginAt: Date.now()});
           }
        },
      });
    }

Any User will only have 'touchLastLogin' and no 'getInputHTML'.

Is this desired behaviour?

**Comment by janmeier** [comment]
Seems to work fine for me on latest master. Perhaps try to log `console.log(User.Instance.prototype)` and see if both methods are there (they are for me).

If you still see issues, please create a PR with a failing test

**Comment by trevorlanyon** [comment]
Terribly sorry for wasting your time,

I had done a:

    console.log(user.__options.instanceMethods)

which was only showing the instanceMethods declared in User.js however since I did an npm update I now see the addition of the instanceMethods defined during sequelize instantiation. Next time I'll be sure to do an update before spending your time.

Thank you for the quick response,
