### ISSUE TITLE
PostgreSQL window functions support

### ISSUE THREAD

**Issue by josser** [sequelize/sequelize#4273]
Hi! First of all sorry for my bad english. 

is there any way to make such query via findAll/findOne? 
```sql 
SELECT depname, empno, salary, avg(salary) OVER (PARTITION BY depname) 
as avg_salary_by_depname FROM empsalary;
-- example taken from postgresql manual: 
-- http://www.postgresql.org/docs/9.4/static/tutorial-window.html
```
 
For now i'm using .literal but it's a bit hard because I can't modify attributes.
i.e: 
```javascript
models.empsalary.findAll(
 attributes: ['depname', 'empno', 'salary', [Sequelize.literal('avg(salary) OVER (PARTITION BY depname)'),
'avg_salary_by_depname']]
)
```

It's required to enumerate all attributes from empsalary table to get results. 
It's not so hard for one table but if I have several include's it's became harder. 

So, what I want to do is something like: 
```javascript
models.empsalary.findAll(
 appendAttributes: ['depname', 'empno', 'salary', [Sequelize.literal('avg(salary) OVER (PARTITION BY depname)'),
'avg_salary_by_depname']]
)
```

or 
```javascript
models.empsalary.findAll(
 attributes: ['depname', 'empno', 'salary', [Sequelize.literal('avg(salary) OVER (PARTITION BY depname)'),
 'avg_salary_by_depname']],
 append: true, 
)
```

Thank you!

**Comment by adonomay** [comment]
+1!

**Comment by mickhansen** [comment]
Your second example should work, if you don't feel like supplying all keys you can simply use `Object.keys(Model.rawAttributes)` to get a list of all attributes, you can then concat that with your literal attribute.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/4074 is an issue open for providing `attributes.include` and `attributes.exclude` as appenders/detractors rather than overwriting completely.

**Comment by janmeier** [comment]
Closing this in favor of #4074 since it will solve 95% of the trouble with using a window functino
