### ISSUE TITLE
If you include a model with no primaryKey in a findAll query, only one instance is eager loaded

### ISSUE THREAD

**Issue by Americas** [sequelize/sequelize#4274]
Example
```javascript
var CD = sequelize.define("CD", {
    id    : {
        type         : Sequelize.UUID,
        field        : "cd_a",
        defaultValue : Sequelize.UUIDV4,
        primaryKey   : true,
    },
}, {
    tableName    : "test1",
    name         : {
        singular : "parent",
        plural   : "parents",
    },
});

var CQ = sequelize.define("CQ", {
    a : {
        type         : Sequelize.UUID,
        defaultValue : Sequelize.UUIDV4,
        field        : "cq_a",
        allowNull    : false,
        unique       : "uni",
    },
    b : {
        type         : Sequelize.STRING,
        field        : "cq_b",
    },
}, {
    tableName    : "test2",
    name         : {
        singular : "child",
        plural   : "children",
    },
});
CQ.removeAttribute("id");

CD.hasMany(CQ, {foreignKey : "cq_c"});
CQ.belongsTo(CD, { foreignKey : "cq_c", unique : "uni" });

sequelize
.sync({force: true})
.then(function () {
    return CD.create() // Create one CD instance
})
.then(function(result){
    return CQ.create({b : "one", cq_c : result.id }) // Create CQ instace one related to CD
    .then(function(){
        return CQ.create({b : "two", cq_c : result.id }); // Create CQ instace two related to CD
    })
})
.then(function(){

    return CD.findAll({ include : CQ }) // Get CD instance with CQ eager loaded
    .then(function(results){
        console.log(results[0].children.length); // length = 1
    })

})
.then(function () {
    console.log("done");
    process.exit()
}, function (err) {
    console.log(err);
    process.exit()
});
```

**Comment by janmeier** [comment]
I doubt this usecase will ever be supported. Join de-deduplication relies heavily on primary keys, so I'm surprised it even works this far :)

**Comment by janmeier** [comment]
When you have a field thats a UUID, why not mark it as the primarykey of that table?

**Comment by Americas** [comment]
Because one of the columns can be null, and primary keys can't have nulls. In my use case I do not use the "id" attribute, but since it will solve this problem, I will probably add it just to solve this.

If I use the "getAssociationns" function, it returns both children, so I was wondering why the eager load option did not work.

**Comment by janmeier** [comment]
`getAssociation` runs a simple select query, whereas includes use a join query, and have to de-duplicate the data - since it returns multiple rows for each parent row. The code is [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query.js#L58) if you are interested / want to be horrified ;)

I'm not saying that its impossible to write that code to handle your case, but the code is complicated enough already 

You could use [`include.separate`](https://github.com/sequelize/sequelize/pull/4177) to have the include use a `getAssociation` under the hood

**Comment by Americas** [comment]
`include.separate` does indeed break the query into two, but it still only returns one of the associations! That smarts =P

**Comment by janmeier** [comment]
@Americas Is this fixed by the referencing PR?

**Comment by Americas** [comment]
@janmeier the way I changed this behavior was to have the function try to use a unique key if there was no primary key. I guess it could use every field to hash uniqueness between lines as a last resort. It would make this work for all cases, right?

**Comment by janmeier** [comment]
@Americas Yeah thats how I remembered it as well

I don't think trying every field to find something unique is worth the effort! ;)
