### ISSUE TITLE
Explicitly define sequence for autoIncrement

### ISSUE THREAD

**Issue by aray12** [sequelize/sequelize#4279]
dialect: postgres

I defined my primary key with an autoIncrement after the table had already been created once and synced. I was still getting a null constraint error. I realized the sequence was not being created. I then dropped the table and synced again and it worked. It appears to me that autoIncrement only uses SERIAL to create a sequence. SERIAL only works on table creation. 

Shouldn't you define the sequence explicitly to avoid this problem?

http://www.postgresql.org/docs/9.1/static/datatype-numeric.html#DATATYPE-SERIAL

**Comment by janmeier** [comment]
`sequelize.sync` does not support altering the table, only dropping and recreating, so I believe `SERIAL` is fine.
