### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by CGavrila** [sequelize/sequelize#4284]
I keep getting this error when I try to define the associations for my models.

```
turn str.trim().replace(/[-_\s]+(.)?/g, function(match, c){ return c.toUpperCa
                                                                    ^
TypeError: Cannot read property 'toUpperCase' of undefined
    at /home/user/node/project/node_modules/sequelize/lib/utils.js:51:75
```

The line in question is:
```
Project.belongsToMany(Owner, { as: 'Projects', foreignKey: 'project_id', through: 'project_owners' });
```

The problem seems to be the `Owner` model. However, if I do `console.log(Owner.tableName);`, I do get the expected output.

What might be the cause of this?

**Comment by janmeier** [comment]
Does any of your models / key by any chance have a trailing underscore? I think that could cause the replace to fail.

**Comment by CGavrila** [comment]
Interesting thought! Unfortunately, the answer is no. I only have a field called `language_id` in the `Owner` model.

**Comment by janmeier** [comment]
Hmm.. Can you post a reproducible test case? 

Do both target and source have primary keys? And are the marked as such with `primaryKey: true`?

**Comment by CGavrila** [comment]
You nailed it with the `primaryKey: true`. Thank you so much, I was going nuts!

Is there any reason why it behaves this way when a primary key is not provided? Can this be changed to show a warning or something?

**Comment by janmeier** [comment]
Yep, definitely should emit a warning https://github.com/sequelize/sequelize/issues/4139

**Comment by shawninder** [comment]
I have a case where both tables have a primary key and there are no underscores anywhere, yet I still get this error. I also have a repo which reproduces the issue: https://github.com/WaltzApp/sequelize-troubleshooting
