### ISSUE TITLE
Add support for passing connection mode to sqlite3

### ISSUE THREAD

**Issue by ysagal** [sequelize/sequelize#4288]
sqlite3 supports passing of "mode" on new connections:

**new sqlite3.Database(filename, [mode], [callback])**
mode (optional): One or more of sqlite3.OPEN_READONLY, sqlite3.OPEN_READWRITE and sqlite3.OPEN_CREATE. The default value is OPEN_READWRITE | OPEN_CREATE.
https://github.com/mapbox/node-sqlite3/wiki/API

I believe this can be handled by passing `mode` to `dialectOptions` and modifying this line to pass it on to the sqlite3 library:
https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/connection-manager.js#L33

**Comment by janmeier** [comment]
Sure, PR welcome :-)

**Comment by ysagal** [comment]
Okie dokie #4302 :)

**Comment by ysagal** [comment]
Not sure why postgres-native is failing, but sqlite node.js v0.10 is failing because it doesn't yet have `fs.access`. Should I put in a workaround for checking file existence? E.g. `fs.open`?
