### ISSUE TITLE
Using toJSON() with findAll()

### ISSUE THREAD

**Issue by rohanthacker** [sequelize/sequelize#4291]
This command results in a TypeError :  Undefined Not a function. But when using findOne() with an id. I am able to respond with the json.

Is is possible to use toJSON() with findAll()?

**Comment by janmeier** [comment]
An array do not have a toJSON method. You can map the array and call on each element

**Comment by rohanthacker** [comment]
Cheers. I feared that would be my only option.

**Comment by janmeier** [comment]
If you want to you could extend `Array.prototype` :). Or you could do `JSON.parse(JSON.stringify(array))` - but thats not exactly fast ;)

**Comment by rohanthacker** [comment]
:+1:  Thanks will do some more reading on this.
Thank you for the quick reply and solutions.

**Comment by amintado** [comment]
you can use .findAll("raw: true") for Json result

**Comment by leandroluk** [comment]
raw:true not return nested json correctly

**Comment by ubeid** [comment]
> raw:true not return nested json correctly

@leandroluk I'm looking  into another issue currently but just stumbled upon this

```js
MyModel.findAll({ raw: true, nest:true })
```

It should do the job

**Comment by curtisblanchette** [comment]
> you can use .findAll({raw: true}) for Json result

This would result in the loss of any "VIRTUAL" columns since the response is directly returned from the database.
