### ISSUE TITLE
Union Clause on Sequelize.js

### ISSUE THREAD

**Issue by leonanluppi** [sequelize/sequelize#4293]
Good night,

I don't found about union clause on docs. There is some approach using sequelize.js?

**Comment by janmeier** [comment]
Nope, no support currently. Generally we don't have good support for unions, queries with sub queries etc. 

We'd be open to discuss an api, bit perhaps you can elaborate on what kind of unions you want to be able to write. Maybe even a suggestion for the API :-)?

**Comment by leonanluppi** [comment]
@janmeier I solve my problem using other approach :D. However, it's seems very interesting make an API for unions and sub queries. For me, that I work using some data from SAP ERP, will help very much. Sometimes I need cross some data, ex: Customers per City, couting all sales (with sales order) ordering by types and more.

**Comment by janmeier** [comment]
@leonanluppi Do you have some concrete examples of what you want to be able to express in sequelize :)

**Comment by andarilhoz** [comment]
Hello, i was in need of the same thing, and i had to use an raw query instead (since i have a union select and another subquery inside of it), i want to know if there is someway to help develop this api or something like it

sorry bad english by the way.

**Comment by janmeier** [comment]
@andarilhoz Examples of what kind of unions you want to express and API suggesstions are always welcome

**Comment by codeshinobi** [comment]
Hi @janmeier. I think this would be very helpful. In my case I would like to do something like

MailLabels.findAll({ where: { userID : null }, { union: true } }).findAll({where: { userID: 8 }).then(function(returnedLabels){
   response.send({returnedLabels});
});

A query like this would (in my scenario) allow a selection of labels that are pre-defined (null userID), combine them with another set of labels that are created by a specific user.

In pure SQL, it would be something like: 

SELECT * FROM MailLabels where userID IS NULL
UNION
SELECT * FROM MailLabels where userID = @userID

In the UX, this would allow the front-end user to see default (or pre-defined) mail labels like 'Work', 'Private', 'Family', etc and the ones that they have created.

I hope I did not stray too far from the OP's intentions.

Thanks

**Comment by janmeier** [comment]
@codeshinobi `findAll({ where: { userID: { $or: [null, 8] } })` should work

**Comment by codeshinobi** [comment]
How naive could I be...that works. No reason why it shouldn't. I forgot simple SQL logic.

Anyway, is this going to be implemented in the future for more complex operations with large result sets that need to be in a "union".

Thanks for your response.

**Comment by janmeier** [comment]
@codeshinobi Perhaps, but generally we don't have good support for queries with subqueries (unions, withs etc.). So this would probably be part of a larger refactor to support subqueries as well. Personally I don't like the api you suggested, but I don't have any better suggestions right now

**Comment by codeshinobi** [comment]
I understand. I just found myself in a position similar to @andarilhoz and made an example of where a union would work. I just recently started working with Sequelize and probably tried to look for parallels with Linq and Entity Framework.

I can't wait to see Sequelize grow further.

Thanks for your assistance.

**Comment by BruceHem** [comment]
i'm using raw query for union it's so complex.

**Comment by rcpalacio** [comment]
I think this issue  #2325 may be of help in this matter.

I am guessing once we are able to generate different raw queries without actually querying the database, we can easily 
use them to query unions.

Going from there to creating a general purpose union function seems to be an easy step. Something like:

Sequelize.Union(
	Clients.findAll({where:{setOfConditions}}),
    Person.findAll({where:{anotherSetOfConditions}})
)

Does this make any sense to you guys?

**Comment by BruceHem** [comment]
i think it must have attributes field in findAll, cuz a union operation needs both entity to have same fields.

**Comment by xiaoppp** [comment]
@rcpalacio Sequelize.Union is not a function...

**Comment by felixfbecker** [comment]
How about this:
```js
sequelize.union([{
  model: Clients,
  attributes: ...,
  where: ...
}, {
  model: Person,
  attributes: ...,
  where: ...
})
```
Interface:
```ts
interface UnionQuery<M extends typeof Model> extends FindOptions {
  model: M;
}
class Sequelize {
  union<M>(queries: UnionQuery<M>[]): Promise<M[]>;
}
```

**Comment by sqzbx** [comment]
Use UNION ALL to get a single list
```
# Query A: Gets a list of my clients
SELECT
UserRelations.id as inviteId, Users.quickId as quickId, Users.id as userId, Users.firstName, Users.lastName, Users.initials, Users.active, "client" as `type`, UserRelations.status, UserRelations.dateInvited
FROM
Users INNER JOIN UserRelations ON Users.id = UserRelations.clientId ### Join using Client ID to get User Details
WHERE
Users.active = 1 AND UserRelations.coachId = "92663c47-cab6-4e75-9cee-001ce4bc8be0" and UserRelations.status = 1

UNION ALL

# Query B: Gets a list of my coaches
SELECT
UserRelations.id as inviteId, Users.quickId as quickId, Users.id as userId, Users.firstName, Users.lastName, Users.initials, Users.active, "coach" as `type`, UserRelations.status,UserRelations.dateInvited
FROM
Users INNER JOIN UserRelations ON Users.id = UserRelations.coachId ### Join using Coach ID to get User Details
WHERE
Users.active = 1 AND UserRelations.clientId = "92663c47-cab6-4e75-9cee-001ce4bc8be0" and UserRelations.status = 1
```
This is currently my case that I'm looking to make a bit more elegant. Separately I use both the queries to get a based on what I need (client list / coach list) but now I want to have a single list that have both so I just put `UNION ALL` between them... Right now this works as I want it to... I'm just looking for a way if I can have it work in another method of approach... A union API is what I had in mind but I found this issue so I decided to put on case here...

Thanks... :)

**Comment by IbraheemAlSaady** [comment]
I've been doing lots of raw queries (which I don't really like) due to lots of unions and sub queries I have
@janmeier, here is my humble suggestion. For the union I was thinking of doing something like 
```
union([{
  model: ....,
  attributes: ....,
  where: ....
}, {
  model: ....,
  attributes: ....,
  where: ....,
}]);
```
and the same for union all.

for sub queries, maybe something like 
```
where: {
  id: {
    $sub: {
       model: ....,
       attributes: ['id'], 
       where: ....,
       limit: 1
    }
  }
}
```
and that will generate this 
```mySql
select [....] from [tableName] where id = (select top 1 id from [tableName] where [....])
```
or for `in` conditions like 
```
where: {
  id: {
     in: {
        $sub: {
           model: ....,
           attributes: ['id'], 
           where: ....,
       }
     }
  }
}
```
which will generate 
```mySql
select [....] from [tableName] where id in (select id from [tableName] where [....])
```

I also have a use case where the sub query has union as well.
so I guess something like 
```
where: {
  id: {
     in: {
        $sub: {
            union: [
               {
                  model: ....,
                  attributes: ....,
                  where: ....
               }, {
                    model: ....,
                    attributes: ....,
                    where: ....,
               }
           ]
       }
     }
  }
}
```
and that will generate this
```mysql
select [....] from [tableName] where id in 
(
   select [...] from [tableName] where [....]
   union
   select [...] from [tableName] where [....]
)
```
I also have an issue here #7205 

Hopefully that helps somehow.

**Comment by felixfbecker** [comment]
@IbraheemAlSaady That's pretty much what I suggested above, but someone needs to implement it ;)
Sub queries are a different issue, but you can't use `$sub`, that would allow SQL injection if `where` comes from user input.

**Comment by IbraheemAlSaady** [comment]
@felixfbecker it's the same, I just have use cases so I thought I'll share that's all.
as for the `$sub` and where statement, it's just a normal Sequelize where option that is based on the model's properties. not a raw query. Otherwise I might've misunderstood something.

**Comment by mhuggins** [comment]
I am interested in a way to achieve this without having to write a bunch of raw SQL or without having to learn the ins and outs of sequelize internals.

**Comment by nishant-dani** [comment]
I would be interested in Unions as well.  I am building a feed view for a home page that brings in multiple tables only sorted by updatedAt.  I might either do seperate queries and do the sort and merge at the server, or construct a raw sql query.
