### ISSUE TITLE
Filtering on polymorphic association

### ISSUE THREAD

**Issue by DeX3** [sequelize/sequelize#4295]
In my setup, I want to have a `translations` table that stores possible translations of other entities. In this example I have the `Role` entity (users can have roles, etc... but this is not important here). `Role`s have a `name` and a `description`. Each of which may be present in various `Language`s. A single `Translation` has:

* an `id`
* a `model`: For a translation of a `Role`'s `name`, this would be `"Role"`
* an `attribute`: For a translation of a `Role`'s `name`, this would be `"name"`
* a `text`: The actual translated text

furthermore, the translation references other models:

* `targetId`: This is a polymorphic ID. For a translation of a `Role`'s name, it will be the ID of a `Role`
* `languageId`: This points to the language that the translation is in

Because I want to use the `translations` table for multiple entities (not just `Role`s), I do not have a foreign key constraint on the `targetId`.

The setup below gives me the following methods (which work beautifully):

    someRole.getNameTranslations();        // Get all translations of this role's name
    someRole.getDescriptionTranslations(); // Get all translations of this role's description
    Role.findAll( {                        // Get all roles, and load all their translations
      include: [
        {
          model: Translation,
          as: 'nameTranslations',
          include: [ {
            model: Language
          } ]
        },
        {
          model: Translation,
          as: 'descriptionTranslations',
          include: [ {
            model: Language
          } ]
        }
      ]
    } );

However, sequelize will give me an error as soon as I try to add any filter criteria concerning the language:

    Role.findAll( {
      include: [
        {
          model: Translation,
          as: 'nameTranslations',
          include: [ {
            model: Language,
            where: { language: 'en' }
          } ]
        },
        {
          model: Translation,
          as: 'descriptionTranslations',
          include: [ {
            model: Language,
            where: { language: 'en' }
          } ]
        }
      ]
    } );

    //SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'nameTranslations.LanguageId' in 'on clause'
    //    at Query.formatError (.../node_modules/sequelize/lib/dialects/mysql/query.js:159:14)
    //    at Query._callback (.../node_modules/sequelize/lib/dialects/mysql/query.js:35:21)
    //    at Query.Sequence.end (.../node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    //    at Query.ErrorPacket (.../node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    //    at Protocol._parsePacket (.../node_modules/mysql/lib/protocol/Protocol.js:274:23)
    //    at Parser.write (.../node_modules/mysql/lib/protocol/Parser.js:77:12)

Is this a sequelize bug? Or am I doing something wrong here?

I've added my module definitions below:

Language.js:

    var LanguageModel = atlas.sequelize.define( 'Language', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false
      },
      language: {
        // language or language + extlang subtag of a language
        type: Sequelize.STRING,
        allowNull: false
      },
      region: {
        // the region subtag
        type: Sequelize.STRING
      }
    }, {
      timestamps: false
    } );

Translation.js:

    var TranslationModel = atlas.sequelize.define( 'Translation', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false
      },
      model: {
        type: Sequelize.STRING,
        allowNull: false
      },
      attribute: {
        type: Sequelize.STRING,
        allowNull: false
      },
      text: {
        type: Sequelize.TEXT,
        allowNull: false
      }
    }, {
      timestamps: false
    } );

    module.exports = TranslationModel;

Role.js:

    var RoleModel = atlas.sequelize.define( 'Role', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false,
        i18n: true
      },

      description: {
        type: Sequelize.STRING,
        i18n: true
      }
    }, {
      timestamps: false
    } );

    module.exports = RoleModel;

Relations:

    Role.hasMany( Translation, {
      foreignKey: 'targetId',
      as: 'nameTranslation',
      scope: {
        model: 'Role',
        attribute: 'name'
      }
    } );
    Role.hasMany( Translation, {
      foreignKey: 'targetId',
      as: 'descriptionTranslation',
      scope: {
        model: 'Role',
        attribute: 'description'
      }
    } );

    TranslationModel.belongsTo( LanguageModel );
    LanguageModel.hasMany( TranslationModel );

**Comment by janmeier** [comment]
Hmm, the example seems to work fine for me on latest master

```sql
SELECT `Role`.`id`
	,`Role`.`name`
	,`Role`.`description`
	,`nameTranslation`.`id` AS `nameTranslation.id`
	,`nameTranslation`.`model` AS `nameTranslation.model`
	,`nameTranslation`.`attribute` AS `nameTranslation.attribute`
	,`nameTranslation`.`text` AS `nameTranslation.text`
	,`nameTranslation`.`targetId` AS `nameTranslation.targetId`
	,`nameTranslation`.`LanguageId` AS `nameTranslation.LanguageId`
	,`nameTranslation.Language`.`id` AS `nameTranslation.LANGUAGE.id`
	,`nameTranslation.Language`.`language` AS `nameTranslation.LANGUAGE.language`
	,`nameTranslation.Language`.`region` AS `nameTranslation.LANGUAGE.region`
	,`descriptionTranslation`.`id` AS `descriptionTranslation.id`
	,`descriptionTranslation`.`model` AS `descriptionTranslation.model`
	,`descriptionTranslation`.`attribute` AS `descriptionTranslation.attribute`
	,`descriptionTranslation`.`text` AS `descriptionTranslation.text`
	,`descriptionTranslation`.`targetId` AS `descriptionTranslation.targetId`
	,`descriptionTranslation`.`LanguageId` AS `descriptionTranslation.LanguageId`
	,`descriptionTranslation.Language`.`id` AS `descriptionTranslation.LANGUAGE.id`
	,`descriptionTranslation.Language`.`language` AS `descriptionTranslation.LANGUAGE.language`
	,`descriptionTranslation.Language`.`region` AS `descriptionTranslation.LANGUAGE.region`
FROM `roles` AS `Role`
LEFT JOIN `translations` AS `nameTranslation` 
        ON `Role`.`id` = `nameTranslation`.`targetId`
	AND `nameTranslation`.`model` = 'Role'
	AND `nameTranslation`.`attribute` = 'name'
INNER JOIN `languages` AS `nameTranslation.Language` 
        ON `nameTranslation`.`LanguageId` = `nameTranslation.Language`.`id`
	AND `nameTranslation.Language`.`language` = 'en'
LEFT JOIN `translations` AS `descriptionTranslation` 
        ON `Role`.`id` = `descriptionTranslation`.`targetId`
	AND `descriptionTranslation`.`model` = 'Role'
	AND `descriptionTranslation`.`attribute` = 'description'
INNER JOIN `languages` AS `descriptionTranslation.Language` 
        ON `descriptionTranslation`.`LanguageId` = `descriptionTranslation.Language`.`id`
	AND `descriptionTranslation.Language`.`language` = 'en';
```

**Comment by janmeier** [comment]
Can you tests this on latest master, and if it still fails, create a PR with a failing test case?

**Comment by janmeier** [comment]
Closing, no response
