### ISSUE TITLE
Unhandled rejection SequelizeValidationError not work with catch even if validator specified

### ISSUE THREAD

**Issue by Anjmao** [sequelize/sequelize#4304]
I Have table with fields:
name:string;
idUser:integer;

on my model validator I added
...
idUser: { 
		 type: sequelize.INTEGER,
		 validate: {
			 isInt: true, 
			 equals: 7
		 }
	}
...
now if I post data with idUser = 100, I can catch this error with catch function(equals error works and I can send it to UI), but if I pass idUser = "someNotInteger" I get error Unhandled rejection SequelizeValidationError: "someNotIntege" is not a valid integer, but I can't catch it, only see this error in console. From stack trace I see equals validator use tryCatcher, but isInt validator use INTEGER.validate from data-types.js. This is really bad, because nodejs app will be terminated in such situations.

**Comment by janmeier** [comment]
Please show the code you are trying to use to catch the error?
```js
User.create({
  idUser: 100
}).catch(Sequelize.ValidationError, function (err) {

});
```

Works fine for me. Are you trying to catch the error using `try{} catch`? That won't work with async code

**Comment by Anjmao** [comment]
Try inserting idUser:"abc" and you should get this error.
This is my code for creating User.
Model
```javascript
var Player = db.define('Player', {
	 idPlayer: { type: sequelize.INTEGER, primaryKey: true, autoIncrement: true},
	 idFbUser: { 
		 type: sequelize.INTEGER,
		 validate: {
			 isInt: true,           // must  only allow integer
			 equals: 123
		 }
	},
	 name: sequelize.STRING,
	 email: sequelize.STRING
});
```
and creating user logic
```javascript
var newPlayer = {
	idFbUser: "someInvalidNotIntegerData",
	name: 'test name',
	email: 't@gn.coms'
}
Player.create(newPlayer).then(function(player) {	
	defer.resolve(false);
 })
.catch(function(error) {
	defer.reject(error);
});				
		
```

As you see column idFbUser is integer type and I passing string value, so validation runs, but something wrong with catch block

**Comment by janmeier** [comment]
The catch block is invoked fine for me. I'm still not sure what error you are experiencing?

**Comment by Anjmao** [comment]
Finally I found my mistake. I was using find method  like this.
```javascript
Player.find({where: {idFbUser: request.idFbUser}}).then((player) => {
			//create one more
			Player.create({idFbUser: "invalidInteger}).then((player) => {	
				   defer.resolve(false);
			}).catch((error) => {
				defer.reject('catches only equals validator. I don't know why.');
			});
			
}).catch((error) => {
     defer.reject('invalidInteger catch only here, but why?');
});
```

Is this is really the right way of catching errors? I will look at validator code if it possible to fix this strange behavior.

As I see data-types.js doing  throw new sequelizeErrors.ValidationError
but instance-validator.js doing return new sequelizeError.ValidationError(null, self.errors);

**Comment by janmeier** [comment]
@Anjmao Both errors are caught in the innermost catch block:

```js
{ [SequelizeValidationError: Validation error: Validation isInt failed,
Validation error: Validation equals failed]
  name: 'SequelizeValidationError',
  message: 'Validation error: Validation isInt failed,\nValidation error: Validation equals failed',
  errors: 
   [ { message: 'Validation isInt failed',
       type: 'Validation error',
       path: 'idFbUser',
       value: 'Validation isInt failed',
       __raw: 'Validation isInt failed' },
     { message: 'Validation equals failed',
       type: 'Validation error',
       path: 'idFbUser',
       value: 'Validation equals failed',
       __raw: 'Validation equals failed' } ],
  'error@context': {} }
``` 

There might be some slight confusion here. What you're seeing above are the validators that you created, which are run on create, update etc. 

However, there is also a built in validator for types that used always, even when you don't specify a validation, the data you input will still be validated before the query is created - thats why you are seeing `"someNotIntege" is not a valid integer` in the findAll

**Comment by Anjmao** [comment]
Yes, now I understand. Sorry :)
