### ISSUE TITLE
Elegantly handling "Type Tables" when defining models (like Books and Book_Types tables)

### ISSUE THREAD

**Issue by tolgaek** [sequelize/sequelize#4305]
Basically I have lots of tables that can might lead to a 'Type Table' that houses a translation of string to ids. Obviously on the API side, I only want to expose the string for the type but internally save those as references.

Basically if I have a Book model like:
```
{
  name: 'Interesting Book'
  type: 'Hardcover'
}
```

I want to expose an API that way but also when using sequelize still use that same definition, so something like:
```
Book.create({name: 'Interesting Book', type: 'Hardcover'})
```

But internally in SQL, this should create 2 rows in 2 tables, one in `Book` table with `name: 'Interesting Book', type: 1`, and in Book_Types with `name: 'Hardcover'`
In the future that id created for Hardcover should be reused

I think this is a common pattern in databases and I thought there might already be a way to do this elagantly without implementing it all myself. The current project I'm working on have a lot of big-data queries that will be happening directly from database so I wanted to use types to improve query times (string comparison vs integer) and also save on space

**Comment by janmeier** [comment]
I don't think this is functionality that fits into core sequelize, but I'm pretty sure it could be created as a plugin using hooks.

Pseudo-ish code:
```js
Book.beforeCreate(function (values, options) {
  return BookType.findOrCreate({ name: values.type }).then(function (type) {
    values.type = type.id
  });
});
```

And a similar beforeUpdate hook, if books can change type :)

If you want to expose the same API on GET (e.g type name instead of type id), you could add the type as a defaultScope

```js
Book.addScope('defaultScope', {
  include: [BookType]
});
```
And add a `toJSON` instanceMethod on book: 

```js
toJSON: function () {
  var values = this.get();

  values.type = this.get('bookType').get('name');

  return values;
});

**Comment by tolgaek** [comment]
@janmeier These are really good examples. Thank you. I wasn't sure how to do it "elegantly" and this looks good enough for me! Thanks!
