### ISSUE TITLE
[bug][pgsql] truncating table via Model.destroy fails

### ISSUE THREAD

**Issue by machinshin** [sequelize/sequelize#4306]
```javascript
Model.destroy({truncate: true});
```
fails to work, i get the error: 
```text
Unhandled rejection SequelizeDatabaseError: relation "public.model_table" does not exist
```
I dug through the sequelize code to this line: 
https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L382
for some reason quoting the table name for truncate fails to work, when i change my local code from:
`query = 'TRUNCATE ' + QueryGenerator.quoteIdentifier(tableName);`
to:
``query = 'TRUNCATE ' + tableName;`
 works fine. 

I can work on filing a PR if that would be received? 

P.S. names obviously changed to protect the innocent.

**Comment by janmeier** [comment]
Hmm, no idea why we call `quoteTable`, then remove the ticks again....
