### ISSUE TITLE
results of raw query (with include) hard to use, due to table-aliases

### ISSUE THREAD

**Issue by User4martin** [sequelize/sequelize#4311]
Column aliases specified by the user as part of the attributes section(s)  (fooname, barname) are getting prefixed by the table aliases.
This makes it harder to use them. (and requires knowledge what the alias will be like)

```
var S = require('sequelize');

var sequelize = new S('seq_test', 'passwd', '', {
    host: 'localhost',
    dialect: 'postgres',
    pool: { max: 15, min: 0, idle: 10000, },
    define: {  },
});

var User = sequelize.define('User', {
    name: { type: S.STRING(50), allowNull: true},
    pass: { type: S.STRING(50), allowNull: true},
});
var Foo = sequelize.define('Foo', {
    login: { type: S.STRING(50), allowNull: true},
    pass: { type: S.STRING(50), allowNull: true},
});
var Bar = sequelize.define('Bar', {
    login: { type: S.STRING(50), allowNull: true},
    pass: { type: S.STRING(50), allowNull: true},
});

User.belongsTo(Foo, {});
Foo.belongsTo(Bar, {});

sequelize.sync()
.then(function (){
    return User.create({name: 'A'});
})
.then(function (U){
    return Foo.create({login: 'B'})
    .then(function (F){
        return U.setFoo(F)
        .then(function (){
            return F;
        })
    });
})
.then(function (F){
    return Bar.create({login: 'C'})
    .then(function (B){
        return F.setBar(B);
    });
})
.then(function (){
    return User.findAll({
        raw: true,
        attributes: [ 
            [ S.col('name'), 'username' ] 
        ],
        include: [
            {   model: Foo,
                attributes: [ [ S.col('login'), 'fooname' ] ],
                raw: true, // workaruond issue 4308
                include: [
                    {   model: Bar,
                        attributes: [ [ S.col('login'), 'barname' ] ],
                    },
                ],
            },
        ],
    });
})
.then(function (rows){
    console.log(rows);
    rows.forEach(function(r){
        console.log('fooname: ',r['fooname'], 'Foo.fooname: ',r['Foo.fooname'], 'fooname: ',r['barname'], 'Foo.Bar.barname: ',r['Foo.Bar.barname']);
    });
});
```

runs the sql

```
 SELECT 
   "name" AS "username", 
   "Foo"."login" AS "Foo.fooname", 
   "Foo.Bar"."login" AS "Foo.Bar.barname" 
FROM "Users" AS "User" LEFT OUTER JOIN "Foos" AS "Foo" ON "User"."FooId" = "Foo"."id" LEFT OUTER JOIN "Bars" AS "Foo.Bar" ON "Foo"."BarId" = "Foo.Bar"."id";
```

and log to console

```
fooname:  undefined Foo.fooname:  B fooname:  undefined Foo.Bar.barname:  C
```

the results for fooname and  barname are undefined

**Comment by User4martin** [comment]
actually this is related to ##4310

**Comment by janmeier** [comment]
Aliassing of columns is very crucial to how joins and deduplication of joins work in sequelize. I doubt we are going to introduce any way to turn that of.

You could use `nest: true` http://docs.sequelizejs.com/en/latest/api/sequelize/#querysql-options-promise, to get an object like `{Foo: { fooname: B, Bar: { barname C }}`

**Comment by User4martin** [comment]
I am not asking for an option to turn of aliasing. Actually in the example I do specify an alias.for each column.

I am asking for an option to skip adding the join-path to user-specified column aliases.
```
  include: [  {   model: Foo,
                       attributes: [  [ S.col('login'), 'fooname' ]  ],
```
results in 
```
  "Foo"."login" AS "Foo.fooname", 
```
while I would like
```
  "Foo"."login" AS "fooname", 
```

The danger of conflict with user specified aliases exists independent of prefixing them or not..
If I had done
  "Foo"."login" AS "Foo.Bar.barname", 
it would conflict with the attribute in bar. (even though I specified different aliases.

---
Automatically generated column aliases need to be generated in a way so they will all be unique. So I understand why they use pre-fixes. (though see #4315 )

User specified  aliases should be given unique by the user, and should not have the problem.
In fact, if one avoids the dot in user specified aliases then they can never conflict with generated aliases (since all generated issues have table-aliases as prefix)

So removing the pre-fixing of user specified column aliasing is actually an improvement on:
 -  the stability of resulting queries 
 - the usability of the result-row: row['myalias']

The only reason to make it optional (ideally a global option) is backward compatibility, in cases where an existing program uses none unique user specified column aliases assuming the would be prefixed.

**Comment by bjrmatos** [comment]
> Automatically generated column aliases need to be generated in a way so they will all be unique. So I understand why they use pre-fixes. (though see #4315 )
> 
> User specified aliases should be given unique by the user, and should not have the problem.
> In fact, if one avoids the dot in user specified aliases then they can never conflict with generated aliases (since all generated issues have table-aliases as prefix)

this is true, i would love a way to do ` "Foo"."login" AS "fooname"` instead of `"Foo"."login" AS "Foo.fooname"`, rigth now if i want to extract fields of `Foo` i need to do a `.map` an place each property of `Foo` inside my model. 

if this feature can be implemented it would increase the usability of the result-row by a lot!

**Comment by mickhansen** [comment]
An option would be to make sure that `sequelize.literal()` works for table aliases

**Comment by User4martin** [comment]
"not stale".

**Comment by User4martin** [comment]
"a comment"

**Comment by bt404** [comment]
After reading the source, I find the issue still exist. Can I open a PR to add a parameter to prevent adding a prefix of table name to the result column?

**Comment by luisAzcuaga** [comment]
Any news? :(

**Comment by Mohhd-Arif** [comment]
i am still getting the prefix as tablename.
any solution yet?
