### ISSUE TITLE
$any operator is not working with $like

### ISSUE THREAD

**Issue by lbeschastny** [sequelize/sequelize#4313]
[According to sequelize documentation][1], `$any` operator could be combined with `$like` to produce `LIKE ANY` PostgreSQL query:

```js
$like: { $any: ['cat', 'hat']}
```

But it's not working in latest `sequelize@3.5.1`.

Consider the following code example:

```js
var Sequelize = require('sequelize');

var sequelize = new Sequelize('test', 'username', 'password', {
  dialect: 'postgres',
  logging: false
});

var Test = sequelize.define('Test', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true
  },
  str: Sequelize.STRING
});

sequelize.sync().then(function () {
  return Test.findAll({
    where: {
      str: {
        $like: {
          $any: ['foo%', 'bar%']
        }
      }
    }
  });
}).then(function (data) {
  console.log('Success');
}, function (err) {
  console.error(err);
});
```
Though this query looks valid, it throws the following error:

```
{ [SequelizeValidationError: ["foo%","bar%"] is not a valid string]
  name: 'SequelizeValidationError',
  message: '["foo%","bar%"] is not a valid string',
  errors: [] }
```

It looks like sequelize attempts to validate `['foo%', 'bar%']` array against `foo` data type, which is wrong.

  [1]: http://docs.sequelizejs.com/en/latest/docs/querying/#operators

**Comment by janmeier** [comment]
Merged into https://github.com/sequelize/sequelize/issues/4314
