### ISSUE TITLE
Ability to write dialect-independent $like queries

### ISSUE THREAD

**Issue by lbeschastny** [sequelize/sequelize#4317]
Different dialects handle `LIKE` queries in a slightly different way.

For example, `sqlite` doesn't have default escape character, while MySQL and PostgreSQL use `\` symbol as their default escape character.

Consider the following code example:

``` js
var Test = sequelize.define('Test', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true
  },
  str: Sequelize.STRING
})

sequelize.sync().then(function () {
  return Test.create({
    id: 1,
    str: 'foo\\bar'
  })
}).then(function () {
  return Test.findOne({
    where: {
      str: { $like: 'foo\\\\%' }
    }
  })
}).then(function (data) {
  console.log(data ? 'Found: ' + data.get('str') : 'Not found')
}).finally(function () {
  return Test.drop()
})
```

This code works fine with `postgres` and `mysql`, but it can't find anything with `sqlite`.

One possible way to solve this problem is to add `ESCAPE '\'` to all `LIKE` queries with SQLite. But suck radical change could break someones code, so it'll be better to add support for `ESCAPE` clause and allow people to handle this problem by their own.

**Comment by lbeschastny** [comment]
Probably, I should add separate issue about supporting `ESCAPE` clause in `$like` queries. Or, maybe it'll be better to rename this one to reflect general feature proposal, rather than my specific problem.

**Comment by janmeier** [comment]
Hmm, I'm kinda thinking that the issue is the opposite and the mysql and postgres implementations are in the wrong here, not sqlite.

It should not be up to the user to do any escaping :)

We insert `'foo\\bar'`, which the db of course saves a `'foo\bar'` - foo, literal backslash, bar

So I don't understand why `LIKE 'foo\\%'` is not working .. Shouldn't that read as foo, literal backslash, anything?

**Comment by lbeschastny** [comment]
@janmeier, it's not working because postgres treats `\` as an escape character an thus looks for `foo\%` string (with percent symbol). It could be easily fixed by adding `ESCAPE ''`. So `LIKE 'foo\\%' ESCAPE ''` will work exactly like SQLite equivalent.

**Comment by janmeier** [comment]
Oh, I found the culprit ... 

> Because MySQL uses C escape syntax in strings (for example, “\n” to represent a newline character), you must double any “\” that you use in LIKE strings. For example, to search for “\n”, specify it as “\\n”. To search for “\”, specify it as “\\\\”; this is because the backslashes are stripped once by the parser and again when the pattern match is made, leaving a single backslash to be matched against.

> Exception: At the end of the pattern string, backslash can be specified as “\\”. At the end of the string, backslash stands for itself because there is nothing following to escape. Suppose that a table contains the following values:

https://dev.mysql.com/doc/refman/5.0/en/string-comparison-functions.html#operator_like

Now that is funky... So for like queries, we should escape twice, but not for anything else ....

**Comment by lbeschastny** [comment]
@janmeier there is no need to escape things twice, you can simply add `ESCAPE ''` to all `LIKE` queries and it'll turn escaping off.

**Comment by janmeier** [comment]
@lbeschastny We set [standards_conforming_strings](http://www.postgresql.org/docs/8.2/static/runtime-config-compatible.html#GUC-STANDARD-CONFORMING-STRINGS) on for postgres though - so it should be interpreted as a backslash, not an escape character. So `LIKE 'foo\%'` should work for postgres as far as i understand it.

Adding `ESCAPE ''` to mysql and pg will be just as radical as adding `ESCAPE '\'` to sqlite and just as likely to break stuff though..

**Comment by lbeschastny** [comment]
According to mysql docs, you should use [NO_BACKSLASH_ESCAPES][1] mode to disable LIKE queries escaping.

  [1]: https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html#sqlmode_no_backslash_escapes

**Comment by lbeschastny** [comment]
> it should be interpreted as a backslash, not an escape character

@janmeier  well, it's not what I saw. I tested the my code example in postgres and sqlite so I'm pretty sure escaping is still enabled.

**Comment by janmeier** [comment]
@lbeschastny Yeah maybe I'm just reading the postgres docs on escape strings wrong ...At least it seems to be the opposite of what I was expecting

`LIKE E'foo\%';` and `LIKE 'foo\\%';` do the right thing

With standard_conforming_strings off both `LIKE 'foo\%';` and `LIKE E'foo\%';`work

**Comment by lbeschastny** [comment]
@janmeier I think I can explain this results.

`standard_conforming_strings` flag defines how postgres parses SQL strings into internal strings, but it doesn't affect LIKE queries escaping.

Consider the following query (with `standard_conforming_strings` set to `OFF`):

 ```sql
SELECT * FROM "Tests" WHERE "str" LIKE 'foo\\%';
```

First, postgres reads SQL query and transforms it into internal representation, getting `foo\%` string.

Then it converts `foo\%` string to the pattern, treating `\` as an escape character and thus looking for an exact `'foo%'` string.

Now, if `standard_conforming_strings` is set to `ON` it reads SQL string literally, getting `'foo\\%'`, which results in `'foo\%'` pattern after applying `LIKE` internal escaping.

`LIKE 'foo\%'` works with `standard_conforming_strings` set to `off` because it ends up as `'foo%'` (ignoring slash character at all).

**Comment by lbeschastny** [comment]
In other words, you *should* set `standard_conforming_strings` to `on`, but it won't turn `LIKE` queries escaping.

**Comment by lbeschastny** [comment]
With `standard_conforming_strings` set to `off` you'll have to escape each `\` character once more:

```sql
SELECT * FROM "Tests" WHERE "str" LIKE 'foo\\\\%';
```

**Comment by lbeschastny** [comment]
In other words, you **should** set `standard_conforming_strings` to `on` (just as you do), but it won't turn `LIKE` queries escaping off.
