### ISSUE TITLE
findById where clause

### ISSUE THREAD

**Issue by jjacobson93** [sequelize/sequelize#4320]
After some of my queries with `findById()` weren't coming back with the right SQL, I perused the source and found some issues.

Here is a simplified version of what I was doing with findById:
```javascript
var User = sequelize.define('user');
var PrivateProject = sequelize.define('privateProject');
PrivateProject.belongsTo(User);

sequelize.sync({ force: true }).then(function() {
	var user1, user2;

	User.create()
	.then(function(u) {
		return u;
	})
	.then(function(u) {
		user1 = u;
		return User.create();
	})
	.then(function(u) {
		user2 = u;
		return PrivateProject.create({ userId: user1.id });
	})
	.then(function(p) {
		// let's say user2 is our current logged in user
		return PrivateProject.findById(p.id, { where: { userId: user2.id } });
	})
	.then(function(p) {
		console.log(p.dataValues);
	})
	.then(function() {
		process.exit();
	});
});
```
Turns out findById sets `options.where = {}`, so that where clause gets wiped out.
I could query the project by id, then check at the application layer if the user "owns" the project, but why not let the database handle that?

I could also just use a `findOne()`, so maybe that is more applicable and it's silly to use `findById()` here.

**Comment by janmeier** [comment]
Yep, findOne is the way to go here. findById is only meant as a utility method for when you only want to query on the primary key

**Comment by catamphetamine** [comment]
@janmeier Well, you could have at least added a `throw new Error("where clause is not allowed when using findById")`.
