### ISSUE TITLE
Confused about Sync and Migrations

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#4323]
I've just read the documentation of Sync and Migrations and I'm still kind of confused.

I have an existing Sequelize project with a table that has been synced and working fine (Postgres dialect). I added a column and did Sync. I don't see a new column in the database. Isn't that what Sync is supposed to do?

Migrations: Next, I used the CLI to do "migration:create". First time it failed because I didn't have a config file, so I made one, and then noticed it's storing DB passwords in the config file. Wow. So I deleted the config file and I'm using the "--url" method instead, and passed it the DB connection string. So this generated a skeleton/boilerplate migration with only comments stored in the up/down methods. I don't understand, isn't it supposed to look at my model, compare it to the existing database, do a "diff" on the schema, and generate a column-create for me? What's the point of having a "migration:create" command and providing a DB connection string, if it just creates a boilerplate file? I could have done that with copy/paste.

**Comment by janmeier** [comment]
Yes, it would be lovely if sequelize could figure out what changed in your schema / model definition, but unfortunately that's not possible right now :-(. See https://github.com/sequelize/sequelize/issues/537

Indeed you could have just created the migration skeleton by copy paste - do what suits you best :-). Indeed it would be nice if the whole migration was created for you, but as with sync, it's not something that's easy to implement

**Comment by janmeier** [comment]
Regarding passwords in the config file. Where else would you store the password? In my experience storing it in a config file, which of course is not kept in source control, is a pretty common practice

**Comment by GeoffreyPlitt** [comment]
Passwords: gotcha.

Yeah even if it's a lot of work to auto-generate migrations based on schema diffs, we should still have a tool to generate schema diffs.

I use Sequelize so I don't have to write SQL or learn too much about Postgres. As soon as I have to write SQL and learn PostGres specifics, I might as well not be using Sequelize.

It seems like a warning about this should be right on the front page of this Repo. Had I known about this, I might not have wanted to choose Sequelize.

**Comment by janmeier** [comment]
> we should still have a tool to generate schema diffs.

Ideally yes - But no-one has taken the time to write one yet, so we don't. The building blocks are there - we already have [`describeTable`](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L321) which returns a structure that is at least close to the sequelize model definition. But there is still work to do to patch it into a complete tool.

You don't have to write raw sql in your migrations. There are commons for the most common stuff, adding, removing and altering columns http://docs.sequelizejs.com/en/latest/docs/migrations/

> It seems like a warning about this should be right on the front page of this Repo. Had I known about this, I might not have wanted to choose Sequelize.

I'm sorry you feel this way. The repo only ever mentions migrations, not that they can be automagically be generated in some way. I don't know of any other ORMs that can do this either. And I must admit, it feels wrong to try to sell yourself on this you can't do ;)
