### ISSUE TITLE
validationHooks run twice

### ISSUE THREAD

**Issue by giannico** [sequelize/sequelize#4325]
I have a model ```Account```, which represents a user's account in a system. One of the fields is a password, and I have a business scenario where the user's plaintext password should be restricted to 6 - 20 characters. I'm using model validation for this requirement:

```
password: {
    field: 'password',
    type: DataTypes.TEXT,
    allowNull: false,
    validate: {
        len: {
            args: [6, 20],
            msg: 'must be between 6 and 20 characters.'
        }
    }
}
```

I'm using the beforeCreate hook to swap out the plaintext password on the model instance, with a hashed password:

```
beforeCreate: function(account, options, fn) {
    utils.auth.hash(account.password).
        then(function(hashedPassword) {
            account.password = hashedPassword;
            fn(null, account);
        }).catch(function(err) {
            fn(err, null);
        });
}
```

This has worked well for me so far, create works fine. I just implemented the password update feature, however, and I'm finding that model validation is occurring twice, once before the ```beforeUpdate``` hook, and once after it. With the hooks defined as follows:

```
hooks: {
    beforeValidate: function() {
        console.log('before validate');
    },
    afterValidate: function() {
        console.log('after validate');
    },
    beforeUpdate: function(account, options, fn) {
        console.log('before update');
        // hash the password
        // account.password = hashedPassword;
        return fn(null, account);
    }
}
```

Upon saving the model (via the instance ```save()``` method),

My console prints:

```
before validate
after validate
before update
before validate
after validate
```

As a result, the second set of validation is failing, because the hashed password is set at that point, which exceeds the 20 character validation length. This was not the behavior I expected, am I misinterpreting the way the hooks should work in this scenario?

**Comment by janmeier** [comment]
Validation hooks are run again if the `beforeUpdate` hook changes any values.

If you want to skip this, you can set `options.validate = false` in the `beforeUpdate` hook

**Comment by janmeier** [comment]
Closing, no response
