### ISSUE TITLE
Effects of “unique” property in model definition

### ISSUE THREAD

**Issue by pensierinmusica** [sequelize/sequelize#4329]
Hi, I'm using Sequelize v3.5.1 with PostgreSQL v9.4.4 on a NodeJS server project.

In the model definition, it's not entirely clear to me what are the effects of adding the option `unique: true` to a property.

Let's take this code for example:

```js
sequelize.define('User', {
  email: {
    type: Sequelize.STRING,
    unique: true
  },
  password: {
    type: Sequelize.STRING,
    allowNull: false
  }
});
```

Does this mean that PostgreSQL will build a unique index on `email`? So, is it just a shorthand method for this?

```js
sequelize.define('User', {
  email: {
    type: Sequelize.STRING,
  },
  password: {
    type: Sequelize.STRING,
    allowNull: false
  }
}, {
  indexes: [
    {
      unique: true,
      fields: ['email']
    }
  ]
});
```

If so, will such index speed up table queries for email, or just ensure uniqueness?

Thanks!

**Comment by janmeier** [comment]
Yes, those two definitions are equivalent.

As to speed-up thats harder to answer. If the index is [covering](http://stackoverflow.com/questions/609343/what-are-covering-indexes-and-covered-queries-in-sql-server), then yes it will definitely speed up the query. A definition answer is outside the scope of this post, you'll probably have to dig in with [`EXPLAIN`](http://www.postgresql.org/docs/9.1/static/sql-explain.html) or similar

**Comment by pensierinmusica** [comment]
I see, thanks for the clarification! Before asking I actually looked [at the docs](http://docs.sequelizejs.com/en/latest/docs/models-definition/), but there doesn't seem to be  much information about it.

Shall we add more details? (at least about the first part of my initial question)

**Comment by janmeier** [comment]
Sure, the docs could always be more clear - PR welcome :)
