### ISSUE TITLE
Bulk Create or Update

### ISSUE THREAD

**Issue by nicolabortignon** [sequelize/sequelize#4330]
Is there an equivalent bulk method for upsert?

**Comment by janmeier** [comment]
There is the `updateOnDuplicate` option http://docs.sequelizejs.com/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance

However, it only works on mysql currently

The feature is coming in postgres 9.5, see https://github.com/sequelize/sequelize/issues/4324

**Comment by krishangupta** [comment]
@janmeier is the updateOnDuplicate option have the same effect as the (hypothetical) `bulkUpsert`?

In my code I use something like `...bulkCreate(my_object_array, {updateOnDuplicate: true)`. This seems to have the desired effect in that new rows are not created. But maybe that's just because MYSQL won't allow duplicate primary keys.

The docs say that `updateOnDuplicate` is supposed to be an array, but for some reason using it as a boolean works for me. 

Would you mind telling us what you know about updateOnDuplicate and then I can make a suggestion for the docs?

**Comment by ctwhome** [comment]
As far as I see, it doesn't update, just replace all the columns:
```
table.bulkCreate(
      [
        { id: 'foo', name:  'name foo' },
        { id: 'bar', name: 'name bar' },                    
        { id: 'bar', otherColumn: 1234.123 },      <<<< This replace the name to NULL
      ],
      {
        updateOnDuplicate: true,
      },
    )
```

It replaces the name for 'bar' with null

**Comment by knoxcard** [comment]
I ended up creating this code to accomplish creation and updates.


```
              app.model.sequelize.query('ALTER TABLE `dispensaries` AUTO_INCREMENT = 1').spread((ret, metadata) => {
                // console.log(JSON.stringify(disp_recs, null, 4))
                app.model.dispensaries.findAndCountAll().then(res => {
                  var dispensary_count = res.count
                  if(dispensary_count == 0) {
                    return app.model.dispensaries.bulkCreate(disp_recs, {
                      updateOnDuplicate: true
                    }).then(ret => {
                    })
                  }
                  app.model.sequelize.Promise.each(disp_recs, disp_rec => {
                    app.model.dispensaries.findOne({
                      where: {
                        'url_slug': disp_rec.url_slug
                      }
                    }).then(upd_disp_rec => {
                      upd_disp_rec.update(disp_rec).then(ret => {
                        return
                      })
                    })
                  }).then(ret => {
                    app.model.dispensaries.destroy({
                      where: {
                        processed: 'Y'
                      }
                    }).then(ret => {
                      console.log(app.colors.yellow('[Dispensary Upsert - COMPLETE]'))
                    })
                  })
                })
              })
```

**Comment by AlexanderGulakov** [comment]
ProductAttribute.bulkCreate(arrayToUpsert, {updateOnDuplicate: ['id', 'attributeValue'] })
- this will create new instances from arrayToUpsert or update each instance attributeValue if it's already existed in the db

**Comment by BrianMwas** [comment]
There's actually a bulkUpdate option,
`public async bulkUpdate(tableName: string, values: object, identifier: object, options: object, attributes: object): Promise`
It takes the table name so if you want to update the Users tables where the values contain the values you want to update in the format of an object e,g
`{ favorite_dish: 'burger', drink: 'cola'  }` It also returns a promise.
An example would be 
`queryInterface.bulkUpdate('roles', {
    label: 'admin',
  }, {
    userType: 3,
  },
);`
For more info consider [this](https://sequelize.org/master/class/lib/dialects/abstract/query-interface.js~QueryInterface.html#instance-method-bulkUpdate)..
