### ISSUE TITLE
findOrCreate hangs, if only one connection is available

### ISSUE THREAD

**Issue by User4martin** [sequelize/sequelize#4333]
In the example the maximum amount of conections is set to 1.

findOrCreate does not return (or maybe it will at the idle time...)

If "max:2", then it works (giving an exception due to unique violation.

```
var S = require('sequelize');

var sequelize = new S('seq_test', 'passwd', '', {
    host: 'localhost',
    dialect: 'postgres',
    pool: { max: 1, 
            min: 0, idle: 10000, },
    define: {  },
});

var User = sequelize.define('User', {
    name: { type: S.STRING(50), allowNull: true, unique: true},
    pass: { type: S.STRING(50), allowNull: true},
});

sequelize.sync()
.then(function (){
    User.create({ name: 'A', pass: 'A' })
    .then(function (){
        User.findOrCreate({
          defaults: { name: 'A', pass: 'A' },
          where: { name: 'B' }
        })
        .catch(function (e){
            console.log('ERR', e);    
        })
        .then(function (){
            console.log('DONE');
            sequelize.close();
        });
    });
});
```

**Comment by billxinli** [comment]
I am seeing this with 3.5.1

**Comment by janmeier** [comment]
Hmm sounds weird -  `findOrCreate` should only be creating a single transaction (i.e. only need a single connection)

Could you try creating a transaction manually and passing it to `findOrCreate` to see if that hangs as well?

**Comment by User4martin** [comment]
It should be noted that this code has a "where" that "differs" from the default.
- if not exists user "A" then create user "B"
But IMHO that is still a valid use case. (e.g. when there is no registered user, then (attempt to) create a new/dummy user.

---
Works fine, if I create a transaction by hand.

Code: (use definition as in original post)
```
sequelize.sync()
.then(function (){
    User.create({ name: 'A', pass: 'A' })
    .then(function (){
        //  TRANSACTION
        sequelize.transaction(function (t){
            return User.findOrCreate({
              defaults: { name: 'A', pass: 'A' },
              where: { name: 'B' },
              transaction: t,
            })
        })
        .catch(function (e){
            console.log('ERR', e);    
        })
        .then(function (){
            console.log('DONE');
            sequelize.close();
        });
    });
});

```
---
I also re-run the version *without* explicit transaction again. But allowing 2 connections.
I captured the logged SQL.
```
Executing (5d6b8f86-587a-43c8-a8ea-8738eb032a14): START TRANSACTION;
Executing (5d6b8f86-587a-43c8-a8ea-8738eb032a14): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (5d6b8f86-587a-43c8-a8ea-8738eb032a14): SET autocommit = 1;

Executing (5d6b8f86-587a-43c8-a8ea-8738eb032a14): SELECT "id", "name", "pass", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."name" = 'B' LIMIT 1;

Executing (5d6b8f86-587a-43c8-a8ea-8738eb032a14): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "Users", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_c24fad59c8d84cfb8597ac78563b34b3$ BEGIN INSERT INTO "Users" ("id","name","pass","updatedAt","createdAt") VALUES (DEFAULT,'A','A','2015-08-16 11:39:53.083 +00:00','2015-08-16 11:39:53.083 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_c24fad59c8d84cfb8597ac78563b34b3$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();


Executing (default): SELECT "id", "name", "pass", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."name" = 'B' LIMIT 1;

Executing (5d6b8f86-587a-43c8-a8ea-8738eb032a14): COMMIT;
ERR { [SequelizeUniqueConstraintError: Validation error]
```
When the function fails, it searches again for the existing entry. This is not part of the (internal) transaction.

Also in this case it will still not find it.

---
---
Not related to the issue, but the overall SQL seems fairly complex? In postgres one could simply do:
```
  WITH
     SEARCH  AS ( 
          SELECT "id", "name", "pass", "createdAt", "updatedAt" 
          FROM "Users" AS "User" WHERE "User"."name" = 'B' LIMIT 1
     ),
     INS AS (
          INSERT INTO "Users" ("name","pass","updatedAt","createdAt") 
          SELECT  'A','A','2015-08-16 11:39:53.083 +00:00','2015-08-16 11:39:53.083 +00:00'
          WHERE NOT EXISTS (SELECT 1 FROM SEARCH)
          RETURNING *
     )
     SELECT * FROM SEARCH UNION SELECT * FROM INS ;
```

**Comment by janmeier** [comment]
That last select should only be triggered if the create triggers a unique constraint error - meaning that user B already exists - Having different default and where values for the unique key is not really supported. I don't remember why we don't passt the transaction to that last call if it's internal, but there was a reasoning behind it :)

> Also in this case it will still not find it.

No, because it does not know what to find. There is a hard reliance on the unique key being the same in where and defaults. This should probably be more clearly stated in the docs.


Indeed, the SQL is fairly complex. The approach you suggested was my original approach https://github.com/sequelize/sequelize/pull/2518, but it does suffer from race conditions. We are going to rewrite it to use `ON DUPLICATE KEY` once postgres 9.5 is out

**Comment by User4martin** [comment]
> I don't remember why we don't passt the transaction

Well if there is a reason, then maybe the transaction can be closed before the select?

While having only one connection is unlikely, it is very possible that a great many FindOrCreate are running, and they may use all connections for their transaction, blocking each other in the end.

> Having different default and where values for the unique key is not really supported
The issue can happen (as a race condition) if the user is created between the first select and the insert. But it is going to be hard to write a (reliable) example for that.

Also if it is not supported, then why supply params for a "where" instead of creating it from the defaults.
Besides, I do not see why it is not supported: for all I see it works, or suffers only from the same issues that a findOrCreate with equal params also suffers.

**Comment by User4martin** [comment]
> The approach you suggested was my original approach #2518, but it does suffer from race conditions. We are going to rewrite it to use ON DUPLICATE KEY once postgres 9.5 is out

Ok, I read up a bit on this. Since "ON DUPLICATE KEY " is only for postgres 9.5 and up, I assume this is still relevant. I.e. I assume that older postgres will still be supported.

- 1)
Yes the "WITH" has a race condition. But it only means you might get a unique constraint error.
And the current code already issues a further "select" in this case. So the entry will be fetched anyway.

- 2) 
The current approach
```
CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "Users", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_2fd2b475321945a393ec06970192d010$ 
BEGIN 
  INSERT INTO "Users" ("id","name","pass","updatedAt","createdAt") 
    VALUES (DEFAULT,'A','A','2015-08-16 11:38:33.789 +00:00','2015-08-16 11:38:33.789 +00:00') 
    RETURNING * INTO response; 
  EXCEPTION WHEN unique_violation THEN 
      GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_2fd2b475321945a393ec06970192d010$ LANGUAGE plpgsql; 
SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();

// currently outside transaction // only if testfunc failde to insert (duplicate key exception)
SELECT "id", "name", "pass", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."name" = 'B' LIMIT 1;
``` 
suffers a different race.

If I have 2 applications
* app 1: Deletes (not paranoid, so really delete the row from db) the user "A"
* app 2: Find or create the user "A"

The expected result is either (depending which one goes first)
* 1) app2 got the old user (even though it is no longer in the db)
* 2) app2 got a new user.

In either case app2 should have a user.

But if app 1 drops the user after the call to "testfunc", but before the final select, then app 2 ends up with no user at all. That is not expected either.

---
The "WITH" query (if also followed by a further select, in case of an duplicate key error) does not have that issue, because it selects first.

It does however suffers in a different scenario: 
It will also fail to return any user at all, if 
- during the with, another app inserted a user, that was not seen by the select, but that prevented the insert
- and if the other app (or any other app) deleted this inserted user again, before it could be selected by the final select.

--- 
To really avoid any race, I guess a explicit lock will be needed.

**Comment by janmeier** [comment]
Oh right, now I remember why we had to go with a function - when a unique constraint violation is triggered inside a transaction in postgres, the transaction cannot continue - it needs to either commit or rollback, no further queries can be done. [This](http://www.postgresql.org/message-id/CAPNY-2WU76u8-YVJHVgcxc8Mr89GZ0DZEDC2P1NZsQHqyLtb-A@mail.gmail.com) was the best source I could find.

This is of course not acceptable, because the user should be able to do other stuff in the transaction afterwards. You don't expect findOrCreate to throw a unique constraint exception, since that is exactly the case that its meant to handle. So we should handle it and let the users continue with their transaction :)

The only way I've found that enables you to write `EXCEPTION WHEN unique_violation THEN... ` was inside a function.

Explict locking might be an idea here yeah....


Oh, and yes - the internal transaction can definitely be committed before doing the last select - and that will fix your immediate issue :)

**Comment by User4martin** [comment]
Thanks for the detailed feedback / Valuable and interesting info.

Then yes the function is needed., and the on except as well.
Yet it might still be an idea to put the "WITH" into the function, because (IMHO) it has a lower risk of getting a race condition result.

And (but I understand it adds complexity to the code/maintainability) if there is no transaction then skip the internal transaction too, and only use the "WITH" statement. It has the additional advantage of only one statement being sent to postgresql, and the app getting the result much quicker.

**Comment by User4martin** [comment]
"not stale"

**Comment by orajiaku** [comment]
not stale
