### ISSUE TITLE
instance `save()` behavior when nothing has changed

### ISSUE THREAD

**Issue by igrayson** [sequelize/sequelize#4335]
Hello,

How should I expect `instance.save()` to behave when invoked on an instance that has not been modified since load?

From http://docs.sequelizejs.com/en/latest/docs/instances/#updating-saving-persisting-an-instance:

> When you call `save` without changing any attribute, this method will execute nothing;

From http://docs.sequelizejs.com/en/latest/api/instance/#saveoptions-promisethiserrorsvalidationerror:

> Validate this instance, and if the validation passes, persist it to the database.

From nodejs (sequelize 3.3.2):

```
> MyModel.findOne().then(s => s.save());
Executing (default): UPDATE "mymodels" SET "updated_at"='2015-08-15 02:06:57.325 +00:00' WHERE "id" = '3681e9f8-25a5-4863-9015-dd90d3a4a2e2'
```

If the intended behavior of `save` is indeed to not update the timestamp (when no fields have changed), how can I achieve that effect, in a future-proof way?

**Comment by janmeier** [comment]
Yeah, it seems the documentation needs to be cleared up a bit on this point.

It is intentional that nothing is saved if nothing has changed. You can manually mark a column as changed to force a save: `instance.changed('updatedAt', true)`

**Comment by igrayson** [comment]
If that is the intention, this is more than a documentation issue. See block quote in OP.

**Comment by janmeier** [comment]
@igrayson Definitely a documentation issue, that's why I tagged it as such ;)

**Comment by igrayson** [comment]
Okay. It really doesn't seem like a documentation issue when I compare what you said with the observed behavior.

> It is intentional that nothing is saved if nothing has changed.

```
MyModel.findOne().then(s => s.save());
Executing (default): UPDATE "mymodels" SET "updated_at"='2015-08-15 02:06:57.325 +00:00' WHERE "id" = '3681e9f8-25a5-4863-9015-dd90d3a4a2e2'
```
(something is saved)

**Comment by janmeier** [comment]
@igrayson Sorry, I didn't read your first post properly then. I just tested the code you posted though, and no query is executed when I call save (which is the expected behaviour). Can you create a complete example, perhaps as a PR?

**Comment by sushantdhiman** [comment]
@mickhansen This issue has been fixed and documentation is already updated with correct behavior [here](https://github.com/sequelize/sequelize/commit/8df98ded5c3bbd4f62a37a7fd5ed2c8c6a450b9e)

**Comment by mickhansen** [comment]
Thanks for the clean up duty @sushantdhiman
