### ISSUE TITLE
Issue with where clause in associated columns

### ISSUE THREAD

**Issue by tylerjwatson** [sequelize/sequelize#4337]
Hi,

I'm doing a loose search endpoint over `models.Contact` where it optionally `belongsTo` a client or a lender in a 0:1 fashion.  The function should search a few fields in the `Contact` table and the `Name` field inside either of the associations and return results where any name field matches.

I'm having trouble applying the where clause to the outer statement as seen below:

```js
	var searchTerm = req.query.search || "";
	var where = { IsDeleted: false };
	var includeWhere = { IsDeleted: false };
	
	if (searchTerm) {
		searchTerm = utils.searchUtils.normalizeSearchTerm(searchTerm);
		
		where.$or = {
			FirstName: { $like: searchTerm },
			LastName: { $like: searchTerm },
			City: { $like: searchTerm },
			'Client.Name': { $like: searchTerm }, //<--- here
			'Lender.Name': { $like: searchTerm } // <--- here
		};
		

	}
	
	models.Contact.count({ where: where }).then(function(count) {
 		var p = pager(req, res, count, 100);
		var skip = 0;
		var limit = 0;
		
		if (p) {
			skip = p.skip;
			limit = p.limit;
		}
		
		return models.Contact.findAll({
			where: where,
			offset: skip,
			limit: limit,
			include: [
				{ model: models.Client, required: false, where: includeWhere, attributes: ['Name'] },	
				{ model: models.Lender, required: false, where: includeWhere, attributes: ['Name'] }
			]
		});
	})
```

If I add the columns to the `includeWhere` variable it gets placed into the LEFT OUTER JOIN clause along with `IsDeleted` and the result is I still can't search on a lender or client name as the searchTerm for a lender name isn't the same as in in the `Contact` table.

My question is, how do I include associated columns inside an outer `where` clause?

Thanks for your help!

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/3095

Feel free to voice your oppinion regardning API

**Comment by tylerjwatson** [comment]
Thanks for the redirection and let me apologise for adding yet another issue regarding this topic - I'd read a few but not the root issue, will certainly add a +1 to that feature, would be greatly  valued.

Thanks again for your time.

---- Jan Aagaard Meier wrote ----

https://github.com/sequelize/sequelize/issues/3095

Feel free to voice your oppinion regardning API

---

**Comment by janmeier** [comment]
No problem ;)
