### ISSUE TITLE
model not returning anything except query result

### ISSUE THREAD

**Issue by nikhilsamarsingh** [sequelize/sequelize#4340]
Hi, i am new to express js, and was using sequelize for the first time.
I made a function,
uploadPhoto:function(){
       	var profile= Profile.findAll();
    	return profile;
	  }
in the profile model, and it worked fine, but when i tried to return something except the queried result such as,
uploadPhoto:function(){
       	var key=[{'a':'sfv'}];
    	return key;
	  }
It gave an error saying, TypeError: undefined is not a function
Can you please help me @janmeier

**Comment by janmeier** [comment]
You'll have to give some more context - There's nothing calling a function in the second example you showed

Are you calling `uploadPhoto().then()` somewhere? When you return an array, it does not have a `then` function

**Comment by janmeier** [comment]
Closing, no response
