### ISSUE TITLE
QueryInterface.addColumn does not check for existing enum types in Postgres

### ISSUE THREAD

**Issue by sorin** [sequelize/sequelize#4345]
Existing table: 

```
module.exports = function(sequelize, DataTypes) {
    return sequelize.define("ExistingTable", {
        'id': CommonProperties.ID()
    })
}
```

Adding a new ENUM column by changing the model definition:

```
module.exports = function(sequelize, DataTypes) {
    return sequelize.define("ExistingTable", {
        'id': CommonProperties.ID(),

        'status': {
            type: DataTypes.ENUM,
            values: ['good', 'bad]
        },
    })
}
```

& writing a migration script:

```
module.exports = {
    up: function (queryInterface, Sequelize) {
            return queryInterface.addColumn('existing_table', 'status', {
                type: Sequelize.ENUM,
                values: ['good', 'bad']
            })
    }
};
```

& then running sync & migrate fails with:

```
Unhandled rejection SequelizeDatabaseError: type "enum_existing_table_status" already exists
```

I belive this is because sync will create the enum type and then migrate will try to create it again. My guess is the fix should be one of (or both):
- Model.createTable should not try to create the enum type for columns that dont already exist in the physical DB (although they are present in the model definition)
- queryInterface.addColumn checks if the enum type already exists, does not try to create it again

**Comment by sorin** [comment]
Failing test for createTable here
https://github.com/sorin/sequelize/commit/a9c192d0efadf0680fbd0c7619df9d7e8a18df55

**Comment by janmeier** [comment]
@sorin Can you post the test as a pull request instead?

**Comment by sorin** [comment]
Here's the PR: https://github.com/sequelize/sequelize/pull/4348

**Comment by maparent** [comment]
This is indeed still an issue.
