### ISSUE TITLE
findAll never return null

### ISSUE THREAD

**Issue by abhinav76** [sequelize/sequelize#4349]
When i use findAll to retrieve the results, it never return null even if there's no record present in the table.
Due to this I am not able to display "No records found " if table is empty. Is there any other way to do this?

**Comment by janmeier** [comment]
What's wrong with `if results.lenght === 0`?

**Comment by abhinav76** [comment]
yeah already did that.
thanks anyway

**Comment by janmeier** [comment]
Awesome, your issue is solved then :D ?

The reason we always return an array is that you can then always do `results.forEach` - even if there are no results it still works

**Comment by abhinav76** [comment]
yeah ok
thanks a lot
