### ISSUE TITLE
Update attributes silently rejecting validation errors?

### ISSUE THREAD

**Issue by tylerFowler** [sequelize/sequelize#4352]
I've noticed that if I call update attributes on a model instance with some invalid value, it seems that instead of being able to catch the `ValidationError` it will just.. not update that value? I've tried to accomplish this several different ways (including doing on-object changes and manually saving) but to my surprise validation in `.save()` 'passes' somehow. Is there a more specific way of doing this that will actually throw the error? It just keeps the original value instead of updating so it must be not validating, it's just that I don't seem to hear about it.

**Comment by janmeier** [comment]
Can you show some example code?

**Comment by tylerFowler** [comment]
It's simply just a call like:

```js
user.updateAttributes({
  username: req.body.username,
  firstName: req.body.firstName
})
```

But say for username I allow alphanumeric only, if I give it something invalid it will 'pass' and update the First name value but just keep the original value of username. Maybe this is intentional but I think it'd be more helpful to throw an error and be stricter.

**Comment by janmeier** [comment]
Please show the model definition as well

**Comment by tylerFowler** [comment]
I mean it would simply be something like

```js
module.exports = function(Sequelize, DataTypes) {
  User = Sequelize.define('User', {
    username: {
      type: DataTypes.STRING(100),
      validate: { isAlphanumeric: true },
      unique: true
    },

    firstName: {
      type: DataTypes.STRING(100);
      validate: { notEmpty: true }
    }
  });
  return User;
};
```

This isn't my model but it's nothing out of the ordinary. The only thing that's different about the actual model I'm using is that it's a sort of 'blog' post so I use a custom setter on the `title` field to also set the `slug` field (which is never set directly) like so:
```js
set: function(title) {
  if (!title) return;

  var slug = title.toLowerCase().replace(/[^\w ]+/g, '').replace(/\ +/g, '-');
  this.setDataValue('slug', slug);
  this.setDataValue('title', title);
}
```

But even on the other fields with nothing custom and simple validations like the above I get this behavior.

**Comment by janmeier** [comment]
The model and code you posted works for me - it fails with `SequelizeValidationError: Validation error: Validation isAlphanumeric failed`, and nothing is updated. 

Can you create a complete, selfcontained exmaple?

**Comment by tylerFowler** [comment]
Interesting, I haven't isolated anything, I ran into this issue in production code so the issue is far from isolated (though I haven't seen it anywhere else). I'm also using Bluebird's `Promise.all` function and storing the `updateAttributes` promise in a variable in this particular case, though that shouldn't be eating the error.

I'll close this for now and do some experimenting on my end with my models and I'll reopen it if I find that the problem wasn't on my end. Thanks!

**Comment by janmeier** [comment]
Yeah, nothing in that should be swallowing the error - weird ..

**Comment by tylerFowler** [comment]
I even inspected it down the line and the promise was actually getting rejected if I remember correctly, it's just that my code never heard about it.

I also looked at the code for the `updateAttributes` fn and nothing looked suspicious. Though one last thing is that I call `.save()` on the instance after I call update attributes because of the array of promises:

```js
arrayContainingUpdateAttrs.push(doc.updateAttributes(...));

// ... (in between this an action to update an association is called
// conditionally and the promise of the whole operation is pushed to the array)

Promise.all(arrayContainingUpdateAttrs)
.then(function() { doc.save() })
// ...
.catch(Sequelize.ValidationError, function(err) {
  res.status(400).json(_.pluck(err.errors, 'path'));
});
```

But in my findings at the time I didn't see anything that's wrong with this, `.save` even has a validate option and it's defaulted to true.

**Comment by Inqnuam** [comment]
Same issue here with MySQL,
But it is working as excepted (throw error on validation fail) with MariaDB

Example:

With this model
...
{
  birthday: {
    type: BIGINT,
    allowNull: false
    }
}
...

Updating birthday field by anything else than a Number will throw an error when connected to MariaDB, but not with MySQL

With this one
...
{
  birthday: {
    type: BIGINT,
    allowNull: false,
    validate: {
      isNumeric: true
      }
    }
}
...

Sequelize throws a Validation Error with both MariaDB and MySQL
