### ISSUE TITLE
Remove single quote in raw query

### ISSUE THREAD

**Issue by mazzy89** [sequelize/sequelize#4357]
I'm trying to do the following query in sequelize:

```
mysql> SELECT * FROM articles WHERE MATCH (title,body)
    -> AGAINST ('+MySQL -YourSQL' IN BOOLEAN MODE);
```

this is my attempt:

```
var rawQuery = "SELECT * FROM users WHERE MATCH (email) AGAINST ('?*' IN BOOLEAN MODE)";

return sequelize.query(rawQuery, {
    replacements: [text],
    type: sequelize.QueryTypes.SELECT
 }).then(function(user) {
     return user;
});
```
The problem is that I get an error because what I pass a string it contains single quotes and this is the error I got:

```
Executing (default): SELECT * FROM users WHERE MATCH (email) AGAINST (''test'*' IN BOOLEAN MODE)
Unhandled rejection SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'test'*' IN BOOLEAN MODE)' at line 1
```
do you know which is the way to fix it?

**Comment by mickhansen** [comment]
You'll need to remove the quotes in your query string. Replacements are supposed to handle quotes themselves to handle injections etc.

`var rawQuery = "SELECT * FROM users WHERE MATCH (email) AGAINST (? IN BOOLEAN MODE)";`

And then add the `*` app side.

**Comment by mazzy89** [comment]
It worked. Thank you
