### ISSUE TITLE
How got know if the result of query belong to a model

### ISSUE THREAD

**Issue by mazzy89** [sequelize/sequelize#4358]
I have the following query:

```
Promise.join<any>(
    db.User.findAll({
      where: {
        email: {
          $like: '%'+req.query.q+'%'
    }}}),
    db.Investor.findAll({
      where: {
        $or: {
          firstName: { $like: req.query.q+'%' },
          lastName: { $like: req.query.q+'%' }
    }}}),
    (users, investors) => {
      if (!users && !investors) {
        throw new error.NotFoundError('No result match your search criteria!');
      } else {
        return (users ? users : investors);
      }
    }
  ).then((results) => {
   ...
```

how can I know if results is an array of users or investors? does it exist a fast way?

**Comment by janmeier** [comment]
You can use   `results[0] instanceof db.User.Instance` or using `toString`, which should give you something like `[object SequelizeInstance:User]';`

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
