### ISSUE TITLE
How to update the field in database to its increment

### ISSUE THREAD

**Issue by abhinav76** [sequelize/sequelize#4365]
I have a field in my table that counts somethings. so every time user makes a specific call it should update the value. How can i achieve that? Do have to retrieve the field and update it every time?
I don't think arithmetic operations are available in sequelize.

**Comment by janmeier** [comment]
`.increment` http://docs.sequelizejs.com/en/latest/api/instance/#incrementfields-options-promisethis

Notice that you'll have to reload of use `returning: true` in postgres to get the updated value

**Comment by abhinav76** [comment]
I'm using Mysql
can you give me an example query?

**Comment by janmeier** [comment]
`instance.increment('cats', 2)` - increment the cats field by two

**Comment by abhinav76** [comment]
i made this function in my model
<code>
incrementLogin:function(){
			return Member.increment('login_count',1);
		},</code>
what is wrong?

**Comment by janmeier** [comment]
Well you tell me? Whats happening? 

Its seems you are trying to call `increment` on the model - you should call it on an instance

**Comment by abhinav76** [comment]
oh sorry
got it thanks
