### ISSUE TITLE
sync() creates unwanted fKey for polymorphic associations

### ISSUE THREAD

**Issue by f1nnix** [sequelize/sequelize#4367]
### What you are doing?

I'm trying to sync() db with polymorphic associations.

```coffee
db.User.hasMany db.Label,
  foreignKey: 'LabeledId'
  scope:
    Labeled: 'User'
db.Label.belongsTo db.User,
  foreignKey: 'LabeledId'
  as: 'User'

db.Robot.hasMany db.Label,
  foreignKey: 'LabeledId'
  scope:
    Labeled: 'Robot'
db.Label.belongsTo db.Robot,
  foreignKey: 'LabeledId'
  as: 'Robot'
```

When migrating via `sequelize db:migrate`, table `Labels` has no fKeys as expected.

But using `db.sync(force:true)` (usually in tests), a fkey `Labels_LabeledId_fkey` is created **with relation to table `Users`**. So, it throws an error if you try to insert a row with Robot.id if the same User.id doesn't exist. In other words, despite:

```coffee
  'LabeledId': 2
  'Labeled'  : 'Robot'
```
column `LabeledId` tries to relate to table `Users`.

### Which dialect you are using (postgres, mysql etc)?

postgres

### Which sequelize version you are using?

```json
"version": "3.5.1"
```

## Temp workaround

If you are using `sync()` only for tests, the temp solution may be to manually remove unwanted fKey after each `sync()`. Mocha example:

```coffee
describe "Users", ->
  before (done) ->
    db.sequelize.sync(force: true).then ->
      # HACK: fix bug, that violates fKey
      #       for polymorphic associations
      db.sequelize
      .query "ALTER TABLE \"public\".\"Labels\" DROP CONSTRAINT \"Labels_LabeledId_fkey\"",
        type: db.sequelize.QueryTypes.SELECT
      .then (response)->
        done()
```

Thanks.

**Comment by mickhansen** [comment]
For poly relations you need to add `constraints: false` since foreign key constraints obviously won't work in this scenario.
