### ISSUE TITLE
instanceMethods are overwriting by sequelize

### ISSUE THREAD

**Issue by nkt** [sequelize/sequelize#4373]
A little piece of code for demonstration:
```js
const User = sequelize.define('User', {
  ...
}, {
  tableName: 'users',
  classMethods: {
    associate({Invite}) {
      User.hasMany(Invite, {
        as: 'invites',
        foreignKey: 'creator_id'
      });
    }
  },
  instanceMethods: {
    createInvite() {
      ...
    }
  }
});
```

**Comment by mickhansen** [comment]
We can't do much about that, name clashing is to be expected since the association creates a method with the same name.

You'll have to setup your custom method after the associations are done if you wish to overload the association method.
