### ISSUE TITLE
Model.create() returns object without primary key

### ISSUE THREAD

**Issue by kevin-Kno** [sequelize/sequelize#4374]
Just as a reference, this issue is very similar to the one described in #1060, but different enough that I felt it deserved its own issue.

If I define a custom primary key column for the table (instead of the default generated `id` column added when building the model with `sequelize-cli model:create`), the object passed back in the response has a `null` value for the primary key. The real kicker is that the saved object that comes back in the response _does_ come back with the pk, but not on the custom pk column. The value only exists on a property called `null`.

Person model:
```javascript
module.exports = function(sequelize, DataTypes) {
    var Person = sequelize.define('Person', {
        personId: {
            autoincrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER
        },
        firstName: DataTypes.STRING,
        lastName: DataTypes.STRING,
        gender: DataTypes.STRING,
        home: DataTypes.STRING
    });
    return Person;
};
```

Migration file:
```javascript
module.exports = {
    up: function(queryInterface, Sequelize) {
        return queryInterface.createTable('People', {
            personId: {
                autoIncrement: true,
                primaryKey: true,
                type: Sequelize.INTEGER
            },
            firstName: {
                type: Sequelize.STRING
            },
            lastName: {
                type: Sequelize.STRING
            },
            gender: {
                type: Sequelize.STRING
            },
            home: {
                type: Sequelize.STRING
            },
            createdAt: {
                allowNull: false,
                type: Sequelize.DATE
            },
            updatedAt: {
                allowNull: false,
                type: Sequelize.DATE
            }
        });
    },
    down: function(queryInterface, Sequelize) {
        return queryInterface.dropTable('People');
    }
};
```

And the saved Person object
```javascript
{
    dataValues:
        {
            personId: null,
            firstName: 'Wade',
            lastName: 'Wilson',
            gender: '0',
            home: '5555555555',
            updatedAt: Fri Aug 21 2015 15:23:26 GMT-0600 (MDT),
            createdAt: Fri Aug 21 2015 15:23:26 GMT-0600 (MDT)
        },
    // many other properties omitted here for readability's sake
    isNewRecord: false,

    null: 3

}
```

My route:
```javascript
var express = require('express');
var router = express.Router();
var models = require('../../models');
var Sequelize = require('sequelize');
var Person = models.Person;

router.post('/create', function(req, res) {
    Person
        .create(req.body.person)
        .then(function(savedPerson) {
            console.log( savedPerson.null );  ////  <= This line prints out "3".
        });
});
```

**Comment by mickhansen** [comment]
Does it work when you camelcase `autoincrement` as `autoIncrement`? Assuming the definition is a C/P  that's likely your issue.

**Comment by kevin-Kno** [comment]
Well, it would seem you are correct @mickhansen. It seems to work perfectly when the camelcasing is done properly... herpaderp. Thank you kindly.

**Comment by zanemcca** [comment]
Sorry to bring this back up but I feel like this issue should not be closed.
Setting `autoIncrement: true` seems like an irrelevant option that should not affect what is returned. Also, I feel like it is far to easy to forget that `autoIncrement` needs to be set which can result in unexpected side effects. These two factors makes me think that a better solution is definitely needed.

**Comment by cjke** [comment]
Agree with @zanemcca . Why is autoIncrement actually required to return the id?

**Comment by pdxJaxon** [comment]
> Does it work when you camelcase `autoincrement` as `autoIncrement`? Assuming the definition is a C/P that's likely your issue.

Amazing. Same exact issue for me.
Strange that the model doesnt blow up AND that even with incorrect casing, the Identity was being created in the db.
Only Sequelize was confused.....
Thanks for the fix
