### ISSUE TITLE
SUM + GROUP and field disappear.

### ISSUE THREAD

**Issue by nicolabortignon** [sequelize/sequelize#4377]
i'm trying to run this:
```javascript
 Transaction.findAll({
        attributes: ['LabelId', [Sequelize.fn('SUM', Sequelize.col('finalPrice')), 'Price']],
        where: {
          CompanyId: companyId,
          createdAt: {
            $between: [startDate, endDate],
          }
        },
        group: ['Transaction.LabelId']
      })
```

That in the SQL code results in : 

SELECT `LabelId`, SUM(`finalPrice`) as Price FROM `Transactions` AS `Transaction` WHERE `Transaction`.`CompanyId` = '1' AND `Transaction`.`createdAt` BETWEEN '2015-01-01T00:00:00-08:00' AND '2015-08-24T05:54:13+00:00' GROUP BY `Transaction`.`LabelId`;

Unfortunately the Json Object does include LabelId but doesn't included the aggregated field.

If i run the query in sql, it does work as expected.

**Comment by janmeier** [comment]
Works fine for me, both the instance and the result of `.get()` has the `price` property. Which version and database are you seeing this on? Can you create a self-contained example with model(s), assocations and data initialization

**Comment by janmeier** [comment]
Closing, no response
