### ISSUE TITLE
docs: Add new section in Datatypes explaining how check for specific types

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#4380]
I think this may be a common requirement, since this could be very useful when dealing with dynamic url query paths for filters:

``` js
if (options.model.rawAttributes[param].type instanceof  global.erp.orm.Sequelize.STRING
          || options.model.rawAttributes[param].type instanceof  global.erp.orm.Sequelize.CHAR
          || options.model.rawAttributes[param].type instanceof  global.erp.orm.Sequelize.TEXT
          || options.model.rawAttributes[param].type instanceof  global.erp.orm.Sequelize.ENUM) {

          query_fields.where[param].$like = '%' + options.req.query[param] + '%';
        }
        else {
          query_fields.where[param] = options.req.query[param];
        }
```

thing is that this info is missing from the docs, I've to dig in the source code to find out the correct way to do it, so it would be nice if is added to the Datatypes section as an informative paragraph.

**Comment by janmeier** [comment]
Yep, feel free to provide a PR :)

**Comment by diosney** [comment]
Sure! I will make the time in one day or two to batch the changes.

**Comment by janmeier** [comment]
Ping @diosney  :)
