### ISSUE TITLE
feat: Migrations: make migrations generation automatic like Django ones

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#4382]
I think has to be added to the Sequelize CLI in a way that when run fi: `sequelize-cli makemigrations`, they generate the migration files with *all the changes already coded in the migration* from the already loaded models.

**Comment by janmeier** [comment]
Hwo do you define "all the changes already coded"? Should we just include the current state of the model as a `createTable`, or figure out what changed? For the latter, see https://github.com/sequelize/sequelize/issues/537

Can you point to the documentation for this feature in django?

**Comment by diosney** [comment]
https://docs.djangoproject.com/en/1.8/topics/migrations/
https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-makemigrations

@janmeier I prefer the migration way, but in #537 they point out that altering the db directly or creating migrations would have the same output.

Thanks BTW, #537 is exactly what I was asking for.
