### ISSUE TITLE
question: Is there a way to specify common column attributes for all models?

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#4383]
at the sequelize construction time (new Sequelize(options)), fi?

**Comment by janmeier** [comment]
You could add a beforeDefine hook to the sequelize instance http://docs.sequelizejs.com/en/latest/api/hooks/#beforedefinename-fn, and that will allow you to add attributes before a `sequelize.define` call completes

**Comment by diosney** [comment]
@janmeier Thanks.

Can I add new common properties there too?

Can you post an example of using it? The examples I found in the docs are too simple for me to use them, I'm afraid :(

Thanks!

**Comment by janmeier** [comment]
```js
sequelize.beforeDefine(function(attributes) {
  attributes.hat = {
    type: DataTypes.STRING
  }
})
```

**Comment by diosney** [comment]
@janmeier Thanks, I will give it a try later. For now, I solved the the issue by doing:

```js
var Website = global.erp.orm.sequelize.define('Website',
  lodash.extend(mixins.models.attributes, {
    type: {
      type     : global.erp.orm.Sequelize.ENUM,
      comment  : 'The website type.',
      allowNull: false,
      values   : lodash.map(types, 'id')
    },
    name: {
      type     : global.erp.orm.Sequelize.STRING,
      comment  : 'The website name.',
      allowNull: false
    },
    url : {
      type    : global.erp.orm.Sequelize.STRING,
      comment : 'The website url.',
      validate: {
        isUrl: true
      }
    }
  }), {
    comment: 'A street address.'
  });
```
but prefer the global define above my solution.

Thanks again
