### ISSUE TITLE
Comment property

### ISSUE THREAD

**Issue by NAlexandrov** [sequelize/sequelize#4386]
If you open the url http://docs.sequelizejs.com/en/latest/docs/models-definition/ you can see that:

``` javascript
// Comments can be specified for each field for MySQL and PG
hasComment: { type: Sequelize.INTEGER, comment: "I'm a comment!" },
```

But this feature was not implemented in postgres dialect. I tried to add this in this PR https://github.com/sequelize/sequelize/pull/4385 but tests was failed. Somebody can fix it?

**Comment by mickhansen** [comment]
I removed it at one point because it did not work with other features we wanted to implement, IIRC.

**Comment by NAlexandrov** [comment]
Do you have any plans to return support comments on columns? Or will you remove this feature from docs soon?

**Comment by flancer64** [comment]
MySQL dialect does not support comments on columns too. This feature is not supported at all. It is very sad, because comments on columns on the target database structure are very helpful for DB admins and developers.

**Comment by flancer64** [comment]
This is the last [revision](https://github.com/sequelize/sequelize/blob/c749746e2cf48081f625b81697d571d859dbe705/lib/dialects/mysql/query-generator.js#L281) with support of the MySQL comments on columns. It would be very pretty to have this feature back.

Thanks for Sequelize, guys :)

**Comment by diosney** [comment]
+1

**Comment by o5** [comment]
+1

**Comment by Wadeck** [comment]
+1

**Comment by taozhi8833998** [comment]
+1

**Comment by aldafu** [comment]
+1

**Comment by cesiya23** [comment]
Why new versions remove the support of column comment of MYSQL?

**Comment by joshuapaling** [comment]
+1

**Comment by felixfbecker** [comment]
Please don't +1 issues, it clutters notification feed and adds no value to the discussion. Use GitHub reactions. This issue is labeled as good-first-pr, so if you really want it, go ahead and reimplement it.

**Comment by AntSworD** [comment]
why don't remove code from document if it doesn't support of column comment?
[](http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration)

**Comment by Anaphase** [comment]
@AntSworD is right; if this feature has been intentionally removed, the documentation should be updated to reflect that.

**Comment by adoyle-h** [comment]
Does anyone can fix it? I think it is better to support comments on columns.

**Comment by plusmancn** [comment]
waiting for this feature back.

**Comment by aldafu** [comment]
I'd argue this probot-stale is pretty useless. The issues remains. I get the stale tag, but closing the issue because of that isn't helpful.

**Comment by felixfbecker** [comment]
@aldafu it's supposed to leave a comment

**Comment by reggielee** [comment]
I use migrate update table field the comment.

**Comment by dickeylth** [comment]
May I ask if there's any workaround on this issue?

**Comment by natalia-torreira** [comment]
I would also like to have comments back in Postgres as this is an important feature to describe the intention of a field in a table. Thanks

**Comment by wbget** [comment]
Any progress?

**Comment by Luomusha** [comment]
Any progress？

**Comment by mirkojotic** [comment]
@janmeier Hi, I've made a pull request but tests for mssql dialect failed with:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

Nevertheless, I wasn't looking to get this merged immediately but to get some feedback on my direction.

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/pull/9573

**Comment by theRichu** [comment]
In migration process, addColumn and comment is not working
```
        return queryInterface.addColumn(
          {
            schema: 'project',
            tableName: 'scheduleAssigns'
          },
          'timeLogger',
          {
            type: Sequelize.JSONB,
            comment: 'Time Log on JSON',
            defaultValue: {}
          }
        )
```
Generated Query: 
```
ALTER TABLE "project"."scheduleAssigns" ADD COLUMN "timeLogger" JSONB DEFAULT '{}' COMMENT Time Log on JSON;
```

I've got ERROR: syntax error at or near "COMMENT"
