### ISSUE TITLE
Recommendation for updating a nested value inside a JSON field?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#4387]
I'd like to update a JSON field by changing one of it's nested fields.

In mongo, you do this like (http://docs.mongodb.org/manual/reference/operator/update/set/#up._S_set):

``` javascript
instance.update({
  json_field: {
    "$set": {
        "nested_field": "value"
     }
   }
})
```

Is there anything like that with Sequelize/Postgres? Right now all I can do is read/write the entire JSON field, it doesn't seem like I can do deep updates to parts of it.

**Comment by curiousdannii** [comment]
Try something like this:

```
Instance.json.field.deep = 'new';
Instance.changed( 'json', true);
Instance.save();
```

**Comment by GeoffreyPlitt** [comment]
Sorry, I meant ```model.update()```. I'm looking for a single atomic operation, not read-change-write.

What you suggested is my current workaround, but it doesn't solve the issue.

**Comment by janmeier** [comment]
Currently only complete updates are supported, but I can definitely see this being handy for bulk updates.

I believe following in mongo's steps with `$set` would be a good API

**Comment by vhmth** [comment]
Atomic JSON field updates are also useful for fields that may be updated frequently. For instance, we have an `analytics` JSON field on a video model that keeps track of the number of video plays for a given video:

```
analytics: {
  user_id_1: <num_plays>,
  user_id_2: <num_plays>,
  ...
}
```

Would be good to do what @GeoffreyPlitt was suggesting in this case since I simply need to increment the field by 1 (or set to 1 if it doesn't exist).

**Comment by felixfbecker** [comment]
This issue is old, `instance.set()` supports nested field updates through dot-syntax. It is an atomic operation on database level.

**Comment by vhmth** [comment]
Hell yeah thanks for the update @felixfbecker!

**Comment by vhmth** [comment]
@felixfbecker `.set` is working perfectly, but I can't seem to get increment to work with Sequelize `3.11`.

```
this.increment(`analytics.views.${userID}`, { by: 1 });
```

results in

```
[SequelizeDatabaseError: column "analytics.views.3" does not exist]
...
sql: 'UPDATE "campaign_sessions" SET "analytics.views.3"="analytics.views.3" + 1,"updatedAt"=\'2016-11-08 00:06:45.947 +00:00\' WHERE "id" = \'20db5e40a54611e6b2e38778a3f284ba\' RETURNING *' }
```

I can confirm that the `analytics` column in the DB looks like this:

```
{"views":{"3":1,"anonymous":{"::ffff:172-17-0-1":1}}}
(1 row)
```

So `analytics.views.3` should be a field that incrementable.

**Comment by felixfbecker** [comment]
Yeah `increment` is supposed to be an atomic operation on the DB and that is not implemented for JSON columns. You can do a find, increment the value and save

**Comment by tudor33sud** [comment]
How would you update a jsonB array using set? 

Currently, I have a column JSONB where I store data like this:

"output": [
        {
            "id": "4133d700-c9db-4536-82c3-c9251f4585e3",
            "_storage": {
                "xx": "dummy",
                "yy": "dummy"
            },
            "type": "asset",
            "value": "value"
        }
    ]

How can I atomicly update the column to push a new object?

I tried something like Instance.output.push({}) and then Instance.save() but it doesn't do anything.

PS: I know the query would be something like this:(using json array append operator)
UPDATE table
SET jsondata = jsondata || '{}'::jsonb
WHERE id = id;


Thank you

**Comment by dylanlingelbach** [comment]
@tudor33sud What I am doing is something like:
```
Table.update(
{
  output: Sequelize.literal(`output || '["${JSON.stringify(obj)"]'`)
},
{
  where: { id }
}
```

Where `obj` is the object you are trying to append.

This will do an atomic append to the array.

**Comment by aminariana** [comment]
The suggested `set` seems to have been deprecated and or removed, as in my tests it didn't work. But the `update` with dot notation did work for me:
```
# Merges without overriding all values at columnName
await model.update("columnName.nestedAttributeName", value);
```

**Comment by emclab** [comment]
> 
> 
> The suggested `set` seems to have been deprecated and or removed, as in my tests it didn't work. But the `update` with dot notation did work for me:
> 
> ```
> # Merges without overriding all values at columnName
> await model.update("columnName.nestedAttributeName", value);
> ```

If I want to update 2 fields and one of them is JSONB, can I do the following? : 
await instance.update({field1: value1, "json_field.attribute": value2})

**Comment by zaubara** [comment]
Doesn't work for me:
`await User.update({
        'json_field.something': true
      }, {
        where: {
          id: user.id
        }
      })`
It writes correctly to the json_field.something, but deletes all other fields in postgresql. That would make life a lot easier.

**Comment by tudor33sud** [comment]
@zaubara  I am using @dylanlingelbach 's option and works fine for me to update JSONB columns atomically. In my case, I need to update an array object -> push a new object into it. How I am doing that is that first I create the JSON object 
`const newOutput = {property:'value'}`

Then, what you need to do is using something similar to this 
     **const updatedTask = await task.update({
            output: db.Sequelize.literal(`output || '[${JSON.stringify(newOutput)}]'`)
        });**

PostgreSQL offers the || operator to concatenate a new object to the jsonb array.

**Comment by mahiraltinkaya** [comment]
> Doesn't work for me:
> `await User.update({ 'json_field.something': true }, { where: { id: user.id } })`
> It writes correctly to the json_field.something, but deletes all other fields in postgresql. That would make life a lot easier.
> 
> In other words, might work on an instance, certainly doesn't work on the model.

Hey bro, did you solve this ? or what did you for it ?

**Comment by bwoodlt** [comment]
Any thoughts on how I can push to the `mac` value? My object is as follows:

```data: {
 user_id: 1834,
invitees: [
 {ip: "192.1.x.x", mac: ['2A:2:4', '2B:2.5', ...]},
]
}```

**Comment by mboudreau** [comment]
I wasted a day trying to figure out why my simple update `model.update({jsonKey: changedJsonObject})` wasn't working...

It can't be that hard to compare the 2 for changes and actually update the object...

**Comment by cincodenada** [comment]
For @mboudreau and future readers: the issue here is that because it's the same object reference, the new value is strictly equal to the old value. Doing a deep equality comparison is actually more complicated that you might think.

In this case, as mentioned upthread, you can explicitly tell Sequelize that you've updated the field with `.changed()`, [as documented in the API](https://sequelize.org/master/class/lib/model.js~Model.html#instance-method-changed). I believe it 

```
model.changed('jsonKey', true)
model.jsonKey = changedJsonObject
model.save()
```

**Comment by KZTN** [comment]
> @tudor33sud What I am doing is something like:
> 
> ```
> Table.update(
> {
>   output: Sequelize.literal(`output || '["${JSON.stringify(obj)"]'`)
> },
> {
>   where: { id }
> }
> ```
> 
> Where `obj` is the object you are trying to append.
> 
> This will do an atomic append to the array.

Simple and elegant solution. Thanks
