### ISSUE TITLE
PostgreSQL - queryInterface.createTable - unable to set  the correct schema in attributes that reference tables in different schema.

### ISSUE THREAD

**Issue by gbahamondez** [sequelize/sequelize#4388]
```javascript
queryInterface.createTable('user', {
        id : {
          type : Sequelize.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        profile_id : {
          type: Sequelize.INTEGER,
          references: {
            model : 'profile',
            key: 'id',
            onUpdate: 'CASCADE',
            onDelete: 'RESTRICT'
          },
        }
      }, {
      schema: 'test_schema'
     })
```

Using the code above, the generated query for create statement is:

```sql
CREATE TABLE IF NOT EXISTS "test_schema"."user" ("id"  SERIAL , "profile_id" INTEGER REFERENCES "Profile" ("id"), PRIMARY KEY ("id"));
```
Which, is wrong,  giving the next  error: "relation profile doesn't exist" because is not referencing to the correct PostgreSQL schema ("test_schema").

The generated query should reference to the "test_schema" on the FK creation.

```sql
CREATE TABLE IF NOT EXISTS "test_schema"."user" ("id"  SERIAL , "profile_id" INTEGER REFERENCES "test_schema"."profile" ("id"), PRIMARY KEY ("id"));
```

There's no way to specify the schema of the referenced  table   in the attributes definition?

Or i'm misunderstanding something?

**Comment by cmaster11** [comment]
Are you sure this is a bug? The only thing needed is to explicitly define everything (example):

```
references: {
        model: {
          schema: 'auth'
          tableName: 'users'
        }
        key: 'id'
      }
```

Source: I went over the same issue today and looked inside Sequelize code.

:)

**Comment by gbahamondez** [comment]
Exactly was i looking for, someone that look the code for me , <3 thanks a lot.
