### ISSUE TITLE
No documentation for how to use includes

### ISSUE THREAD

**Issue by huckaby** [sequelize/sequelize#4390]
I'm just getting started with sequelize and I noticed that there is almost no documentation at all for the include option in queries. I would submit a PR, but honestly, I don't even know how they work, or what can be passed to them.

Am I missing some documentation?

**Comment by janmeier** [comment]
Includes are often referred to as eager loading in the docs http://docs.sequelizejs.com/en/latest/docs/models-usage/#eager-loading

**Comment by huckaby** [comment]
Ah-ha! that helps a little. However the eager loading documentation also have no reference to attributes. Are the attributes on an include object referencing what columns on the JOIN table you want to see, or are they referencing the foreign key somehow?

**Comment by janmeier** [comment]
`attributes` are always the columns you want to select. So in the case of includes, `attributes` are the columns of the related table you want to select 

```js
User.findAll({ include: [{
  model: Project,
  attributes: ['projectName', ... ]
}]});
```

If you want to query the join table, you can use `through.attributes`

```js
User.findAll({ include: [{
  model: Project,
  through: { attributes : ['joinedOn', ... ] }}
}]});
```

By default, `attributes` will be all attributes of the corresponding table.

The options are also explained in the api docs for findAll, but they might be a bit terse to read if you've never seen the syntax before http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance

I agree, the documentation could definitely be more comprehensive. Right now the tests are probably the  most comprehensive place to look for 'how-tos'. All documentation PRs are very welcomed

**Comment by huckaby** [comment]
Thanks so much for the information, it helped a great deal. As I come up to speed a bit more, I will see if there is anything I can do to help expand on the documentation.
