### ISSUE TITLE
Can't use environment variables for individual components of db URI in config.json

### ISSUE THREAD

**Issue by jteplitz602** [sequelize/sequelize#4391]
The following config.json file throws ```TypeError: undefined is not a function``` when loaded for a migration:

```json
{
  "development": {
    "username": {"use_env_variable": "DB_USERNAME"},
    "password": {"use_env_variable": "DB_PASSWORD"},
    "port": {"use_env_variable": "DB_PORT"},
    "host": {"use_env_variable": "DB_HOST_NAME"},
    "database": {"use_env_variable": "DB_DATABASE_NAME"}
  }
}
```

You can use "use_env_variable" for development as a whole, but it seems that you should be able to specify that a particular part of the URI should be loaded from the environment.

**Comment by janmeier** [comment]
Please post this issue in sequelize/cli or sequelize/umzug instead - not sure which one handles those parameters, but it's not sequelize core :-)
