### ISSUE TITLE
`findOne` and `find` triggering `TypeError` 

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#4392]
I'm having issues when finding a non-existent item in the db.

When doing:

```js
models
    .Organization
    .findOne({
      where: {
        id: req.params.organization_id
      }
    })
    .then(function (data) {
      console.log(data);
    })
    .catch(function (error) {
      console.log(error)
    });
```

or using `findById(req.params.oraganization_id)` and the id is missing from db, Sequelize is triggering a `TypeError` is that the normal behavior or it should return an empty object instead?

The full error is:

`error: { [TypeError: Cannot read property 'id' of null] 'error@context': {} }`

pd. it works OK when passing an id that is in DB

**Comment by diosney** [comment]
Now search through the docs I found that this is not the normal behavior, since it has to return null:

```js
Project.findById(123).then(function(project) {
  // project will be an instance of Project and stores the content of the table entry
  // with id 123. if such an entry is not defined you will get null
})

**Comment by diosney** [comment]
Oh boy, I did found the error and has nothing to do with Sequelize.

Keep the hard work :D

**Comment by imadu** [comment]
@diosney please what was the error, i'm having the same issue with sequelize

**Comment by diosney** [comment]
@imadu Truth be told, I don't remember what was triggering it...I should've to tell it in the description too. Ufg!

Sorry :(
