### ISSUE TITLE
Exclude attributes from eager loaded associations 

### ISSUE THREAD

**Issue by ahayschi** [sequelize/sequelize#4396]
My apologies if this is already a feature, but I searched through the docs, here in the issues, and on stackoverflow and can't seem to find any mention of this feature. 

Essentially, I'm proposing that we can specify which attributes of an association are loaded or not loaded when performing eager loading on find/findAll. I'm currently solving this issue by iterating over the returned data and removing the unwanted attributes, but I think it would be a benefit to not have those selected at all.

Say you have a Post model that belongs to a User model. On a ```findAll``` call you want to get posts and the user data for each post in the same object, so you add ```{ include: [ User ] }``` to the options. However, that User model defines 'password' and 'salt' and other sensitive data that should ultimately not be sent in a HTTP response. Instead of iterating over the returned posts to remove them, we could specify to not select those attributes in the query: 

```JavaScript
{ include: [ { model: User, ignore: [ 'password', 'salt' ] }] }
```

or something similar. Would a raw query be the suggested route to take for this functionality instead?

**Comment by janmeier** [comment]
Definitely a usercase we want to support :). Its described more generally here https://github.com/sequelize/sequelize/issues/4074. That issue covers `exclude` for both regular find and includes
