### ISSUE TITLE
Connecting to SQLite

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/sequelize#4397]
I am trying to connect to SQLite database file with the following code, but always I get the error 'no such table' 

`````js
var sequelize = new Sequelize('dbname', 'username', '', {
  dialect: 'sqlite',
  storage: './db.sqlite3'
})

````
How do I specify the path for the .sqlite3 database file. I have tried placing the .sqlite3 file in the same folder as this script.

**Comment by janmeier** [comment]
Looks alright to me - Its hard to really say anything more with the information given here. 

Does it work if you provide the absolute path?

**Comment by janmeier** [comment]
Closing, no response
