### ISSUE TITLE
null value violates not-null constraint on id, postgres

### ISSUE THREAD

**Issue by ianseyer** [sequelize/sequelize#4400]
hi there.

attempting to create() a new instance of my `menu` object, as described here:
```
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('menu', {
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    closed_view_title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    closed_view_photo_url: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    closed_view_message: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    soldout_view_title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    soldout_view_photo_url: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    soldout_view_message: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    max_items_per_order: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    starts_at: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    ends_at: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    service_boundary_url: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    service_boundary_updated: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false
    }
  });
};
```
`note: i have defined an id field previously, and removed it in an attempt to resolve this issue. sync() is being called on server start.`

However, calling create() is yielding this error:
```
{"name":"SequelizeDatabaseError","message":"null value in column \"id\" violates not-null constraint"
```

Any ideas why sequelize is expecting me to add my own ID value? This seems to be an issue that has floated up several times, but none of the proposed solutions have been working (`autoIncrement:true`, removing the ID field entirely)

**Comment by janmeier** [comment]
I can't reproduce this - It inserts `DEFAULT`

Perhaps you can create a self-contained example or a pull request with a failing test?

**Comment by ianseyer** [comment]
Perhaps.

However, it might be worth noting that I used a sequelize definition generator on an already existing database to get my model definitions.

However, calling `sync()` should take care of that issue, correct?

**Comment by janmeier** [comment]
Sync won't do anything if the table already exists, unless you pass `{ force: true} `. It's not required for an existing database. 

The query should insert default into the id field regardless of whether you call sync or not

**Comment by ianseyer** [comment]
Right, that's what I thought but I wanted to cover my bases.

Here is my `create()`:

```
    app.post('/menus/create', function(req, res){
      models.menu.create({
        title: req.body.title,
        starts_at: req.body.starts_at,
        ends_at: req.body.ends_at,
        closed_view_title: req.body.closed_view_title,
        closed_view_photo_url: req.body.closed_view_photo_url,
        closed_view_message: req.body.closed_view_message,
        soldout_view_title: req.body.soldout_view_title,
        soldout_view_photo_url: req.body.soldout_view_photo_url,
        soldout_view_message: req.body.soldout_view_message,
        service_boundary_url: req.body.service_boundary_url,
        service_boundary_updated: req.body.service_boundary_updated,
        max_items_per_order: req.body.max_items_per_order,
        active: false,
        created_at: Date.now(),
        updated_at: Date.now()
      })
      .then(function(menu){
        res.redirect(200, '/menus/'+menu.id+'/items');
      }, function(error){
        res.status(500).send(error);
      })
    });
```

**Comment by janmeier** [comment]
Everything looks fine to me. 

Since I can't reproduce the issue I can't really offer any more advice. If you are can create a self contained example or a pull request with a failing test we can work from there

**Comment by ianseyer** [comment]
Here is my full setup currently:

https://github.com/ianseyer/sequelize-failing-test

I left DB credentials intact for full demonstration purposes, will alter credentials upon issue resolution.

**Comment by janmeier** [comment]
@ianseyer Wow, that's a lot of code - When I said a self-contained example, I was hoping you could create the smallest possible example that still reproduces the error. I don't even know what to do to reproduce the error :) ?

**Comment by ianseyer** [comment]
Sorry; it isn't too large a project, though. Only a few routes defined and
next to zero assets to pull down.

Getting it going should just be
`npm install; node app.js`

Then navigate to `/menus/create` and fill in some garbage data.

The relevant files are `/controllers/menus.js`, `/views/create.jade`,
`/models/menu.js.`

**Comment by ianseyer** [comment]
Sorry; it isn't too large a project, though. Only a few routes defined and
next to zero assets to pull down.

Getting it going should just be
`npm install; node app.js`

Then navigate to `/menus/create` and fill in some garbage data.

The relevant files are `/controllers/menus.js`, `/views/create.jade`,
`/models/menu.js.`

**Comment by ianseyer** [comment]
Hello?
