### ISSUE TITLE
Eager Loading using reference without constraints

### ISSUE THREAD

**Issue by gustavovaliati** [sequelize/sequelize#4401]
Hello! I have searched for similar issues but no results.

Problem: I'm getting the error "Error: MyModelOne is not associated to MyModelTwo!" while trying to use Eager Loading and using the association [Reference Without Constraints](http://sequelize.readthedocs.org/en/latest/docs/associations/#enforcing-a-foreign-key-reference-without-constraints).

Is there a way to use Eager Loading when using Reference Without Constraints ? Am I doing something wrong?

Thank you :)

Code:
```javascript
var MyModelTwo = sequelize.define("MyModelTwo",
	{
		anotherString : {
			type : sequelize.STRING
		}
	},
	{
		paranoid : true,
		freezeTableName: true,
		tableName: 'tb_mymodelTwo'
	}
);

var MyModelOne = sequelize.define("MyModelOne", 
	{
		someString: {
			type : sequelize.STRING,
		},
		myModelTwo: {
			type : sequelize.INTEGER,
			allowNull : false,
			field : 'mymodeltwo_id',
			references: {
				model: MyModelTwo,
				key:   "id"
			}
		}
	},
	{
		paranoid : true,
		freezeTableName: true,
		tableName: 'tb_mymodelone',
	}
);

sequelize.sync().then(function(){
	MyModelOne.findOne(
		{ 
			include: [
				{
					model: MyModelTwo,
					where:	{ anotherString: 'hey'}
				}
			]
		}
	).then(function(data){});
});
```

**Comment by janmeier** [comment]
Nope, you need to set up the association in sequelize.

You could pass constraints: false to remove the constraints as well though: `MyModelOne.belongsTo(MyModelTwo, { constraints: false })` 
http://docs.sequelizejs.com/en/latest/api/associations/
