### ISSUE TITLE
Track project releases through GitHub

### ISSUE THREAD

**Issue by fixe** [sequelize/sequelize#4403]
@janmeier @mickhansen what do you guys think about using the [GitHub Releases](https://github.com/sequelize/sequelize/releases) so developers can be notified every time a new release is done?

**Comment by mickhansen** [comment]
It's something i've considered before.
As we're already using tags i assume it would just adding changelogs to each release?

**Comment by janmeier** [comment]
Sounds like a good idea :)

**Comment by mickhansen** [comment]
From 3.9.0 i've started adding the changelog to our release notes, that should work right @fixe?

**Comment by fixe** [comment]
Yup, awesome!
