### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by abhinav76** [sequelize/sequelize#4408]
So now that I have started using sequelize, I wanted to know how to paginate the data. Suppose I have 10000 users and when a call is made to display all users, so it displays or sends first 20 users the next 20 and so on. Is there any way to do that? @janmeier

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/docs/querying/#pagination-limiting

**Comment by abhinav76** [comment]
so i have to use both limit and offset?

**Comment by janmeier** [comment]
Yes

**Comment by abhinav76** [comment]
can you please give me the example query?

I am using 
<code>
retrieveUsers:function(){
return User.findAll()
}
</code>

**Comment by janmeier** [comment]
Add `offset` and `limit` like the example I posted 

```js
 retrieveUsers:function(){ return User.findAll({ offset: X, limit: Y ) } 
```

The limit is how many rows you want, the offset is which page you want ( `offset = limit * page` where page is indexed by 0)

**Comment by abhinav76** [comment]
ok thanks

**Comment by janmeier** [comment]
In future, questions like these are better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize). The issue tracker here is meant for feature requests and bugs.

You're also very welcome to join #sequelizejs on freenode for support
