### ISSUE TITLE
DataType BOOLEAN doesn't fetch NULL

### ISSUE THREAD

**Issue by beeant** [sequelize/sequelize#4410]
Hello,

I have an attribute

`is_active: {type: DataTypes.BOOLEAN, allowNull:true},`

when I do
```javascript
Model.find({
  where: {
    is_active: false
  }
});
```

Sequelize doesn't seem to fetch where is_active === NULL, it only fetch where is_active === 0

Is this a bug or meant to be?

Thank you!

**Comment by janmeier** [comment]
Yes, that is intended. 

You could use
```js

return Model.findAll({
    where: {
      is_active: {$or: [false, null] }
    }
  });
```
to get both

**Comment by mickhansen** [comment]
To clarify, that is how your database engine implements `NULL`, generally `NULL` is not an value and such is neither equal or not equal to any other value, thats why generally you need to use `IS NULL` or `IS NOT NULL` in SQL.

As a general schema comment, for a BOOLEAN value you'd probably be much better off having it NOT NULL and with a default value.
