### ISSUE TITLE
MSSQL fails silently on startup

### ISSUE THREAD

**Issue by lwansbrough** [sequelize/sequelize#4411]
I am unable to use MSSQL on neither OS X nor Windows using iojs 3.2/node 0.12.7 (tried both). I'm attempting to connect to a DB hosted in Azure (I'm able to connect using Visual Studio without a problem). Swapping the connections with Postgres connection info allows the app to start up fine.

You'll see in the code below that the application is setup to catch errors, however running the app when using MSSQL dialect causes the terminal to wait for a moment, then it exits, as opposed to throwing an error or running the server.

Here's the relevant code:

`app.js`

``` javascript
...
  let app = express();

  const sequelize = new Sequelize(config.database.NAME, config.database.USERNAME, config.database.PASSWORD, {
    dialect: config.database.DIALECT,
    host: config.database.HOST,
    port: config.database.PORT
  });

  models(sequelize);
  routes(app, controllers);

  const server = sequelize.sync().then(() => { 
    return app.listen(config.app.PORT);
  }).then((server) => {
    var host = server.address().address;
    var port = server.address().port;

    console.log('App listening at http://%s:%s', host, port);
  }).catch((err) => {
    console.error('Application failed to start. Reason: %s', err.message);
  });
```

`models/index.js`

``` javascript
import requireDirectory from 'require-directory';
const hash = requireDirectory(module, {
  recurse: false,
  exclude: /index\.js$/
});

export default function(sequelize) {

  var models = {};

  models.User = sequelize.import('User', hash.User);

  return models;
};
```

`User.js`

``` javascript
export default (sequelize, DataTypes) => {
  return sequelize.define('User', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4,
      validate: {
        isUUID: 4
      }
    },
    email: {
      type: DataTypes.STRING,
      validate: {
        isEmail: true
      },
      comment: "Email of user. Captured either from the third party service, or via user input."
    }
  }, {
    tableName: 'users',
    paranoid: true
  });
};
```

Again, this all works with Postgres.

**Comment by janmeier** [comment]
Sorry for not replying earlier - sometimes issues just get lost :(

Did you manage to solve this - If not, could you try connecting directly using tedious?

**Comment by lwansbrough** [comment]
I haven't solved this yet, but I can try the direct connection with tedious at some point.

**Comment by TameBadger** [comment]
Got the same issue atm, looking into now

**Comment by TameBadger** [comment]
It seems like it's because of the option encrypt: true that should be passed to tedious when using azure.

**Comment by janmeier** [comment]
@TameBadger in that case you should be able to use `dialectOptions` http://docs.sequelizejs.com/en/latest/api/sequelize/#new-sequelizedatabase-usernamenull-passwordnull-options

**Comment by TameBadger** [comment]
@janmeier Works perfectly thanks

**Comment by janmeier** [comment]
@lwansbrough Any progress?
