### ISSUE TITLE
Calling findOne with WHERE on primary key column and operator other than '=' doesn't add LIMIT 1 to query

### ISSUE THREAD

**Issue by shawnpwalsh** [sequelize/sequelize#4416]
It's possible this is intended behavior, but if so it should be detailed in the findOne documentation as you would always expect findOne to return exactly one record.

Dialect: PostgreSQL
Sequelize Version: 3.6.0
Sample Code:
```javascript
yield Content.findOne({where:{id: {$gt: 7}}});
```
Actual output: 
```sql
SELECT "id", "title" FROM "content" AS "Content" WHERE "Content"."id" > 7
```
Expected output: 
```sql
SELECT "id", "title" FROM "content" AS "Content" WHERE "Content"."id" > 7 LIMIT 1
```

**Comment by mickhansen** [comment]
A bug. We look for the presense of a primary key in where to remove the limit (easier queries), but this should only happen for primitives or buffers i guess.
