### ISSUE TITLE
Implement "flattening" when including fields in an association table

### ISSUE THREAD

**Issue by o-e** [sequelize/sequelize#4419]
I am not sure how to title this issue, but let me explain.

Suppose we have two tables `Person` and `Project` plus a `Role` association connecting a person with one or more projects (in both directions). The `Role` association/table has a field called say `RoleType`.

I could set this up and query the db with for example:

```
Person.find({
   where: { id: 1 },
   include: [
      { model: Project, as: "projects", attributes: ["id", "name"], though: { attributes: "roleType" } }
   ]
})
```

which could produce something like 

```
{
 name: "John Smith",
 id: 1,
 project: [ { id: 'a', name: 'Fix issue', role: { roleType: "manager" } }]
}
```

My issue is about the sub object `role: { roleType: "manager" }`. What I would like is a return similar to this: 

```
{
 name: "John Smith",
 id: 1,
 project: [ { id: 'a', name: 'Fix issue', roleType: "manager" } ]
}
```

Namely I would like the `roleType` field to be available directly on each project item. 

Is this possible to achieve? It would be nice to have it. Any suggestions for work arounds?

**Comment by mickhansen** [comment]
Not currently possible in any sequelize-native way (although i've wanted this at one point aswell).
For a work around you'll probably want to override `toJSON` for `Project` and implement flattening there.

**Comment by o-e** [comment]
Great, thanks for your reply!

**Comment by evanslify** [comment]
Sorry to 'resurrect' this issue, but may I ask if this is implemented in sequelize now, as I couldn't find it in documentation?

**Comment by mehemmelbachir** [comment]
Yes, you can add option `raw : true` so it becomes like:
```
Person.find({
   where: { id: 1 },
   include: [
      { model: Project, as: "projects", attributes: ["id", "name"], though: { attributes: "roleType" } }
   ],
   raw : true
})
```

And you can have a result like:
```
id : 1
name : 'Jhon'
...
Project.id : 4
Project.name : 'project name'
....
```

**Comment by VFC-elindgren** [comment]
I dont think the raw option really flattens in the way that was being requested. it just converts to dot-delineated objects, which still means you have to do some tedious post-processing.

**Comment by Hwan-seok** [comment]
Any further updates about this issue..?

**Comment by juber-ivre** [comment]
I do agree with @VFC-elindgren. Is there any plan to address it?

**Comment by agSant01** [comment]
I found a simple solution:
```js

  const person = await Person.find({
    where: { id: 1 },
    raw: true, // set raw return
    attributes: {
      // this will work as long as there are no collisions in the field names of Person and Project Schemas/Models
      include: [Sequelize.col('projects.*')], // include all columns of projects in root of JSON
    },
    include: [
      {
        model: Project,
        as: 'projects',
        attributes: ['id', 'name'],
        though: { attributes: 'roleType' },
      },
    ],
  });
```

**FYI for the reader**
There is a **very important** difference between
```js
...
{
  attributes: ['id',...],
}
...
```

and 

```js
...
{
  attributes: {
     include: ['fieldName', ...],
  },
}
...
```

[Official Docs](https://sequelize.org/master/manual/model-querying-basics.html#specifying-attributes-for-select-queries) for more info.

**Comment by redevill** [comment]
@agSant01 - I followed your links and tried to achieve the attributes: { include: [] } .... syntax. Not sure I can repro this working in the new Sequelize "FindOne" as opposed to "Find".

This syntax is accepted by the Linter:
    attributes: {
      include: [[Sequelize.col('projects.*'), 'myAlias']]
    },

However, sequelize expects an alias, which creates an invalid syntax in the sql for the .* construct.
Any ideas?
TIA

**Comment by agSant01** [comment]
@redevill 
the sequelize method I was going for was `findOne()`, I updated my comment to fix the typo.

```js
// more code
attributes: {
     include: [[Sequelize.col('projects.*'), 'myAlias']]
},
// more code
```

That syntax is valid in practice but it throws an error because of what you said _"...creates an invalid syntax in the sql for the .* construct."_

The `include: []` param in Sequelize can receive either a `Array<string>`, `Array<[col|fn, string]>` or an `Array<[col|fn, string] | string>`

**Ex:**
```js
attributes: {
      include: ['id', ['name', 'renamedName'], [col('lastName'), 'renamed']],
},
```

If you want to include the sub model then just do:
```js
include: [Sequelize.col('projects.*')]
```
That will put all the sub properties in the root of the JSON returned

**Comment by redevill** [comment]
@agSant01 - My types are slightly different " [string | Literal | Fn | Col, string]", but your type "Array<[col, **string**]>"  also expects the alias 
e.g. include: [Sequelize.col('projects.*'), "**string**"]

So, I am unable to get your sample include: [Sequelize.col('projects.*')] to be accepted by the linter.
I can get this to be accepted:    include: ['projects.*']

However, the naming of the fields, still has a hierarchy and the additional include has done nothing for me.
The output field names exist in the root of the object, but the fields are projects.x projects.y etc...

What versions? Sequelize? MySql?
