### ISSUE TITLE
dropTable not schema-aware?

### ISSUE THREAD

**Issue by paulxtiseo** [sequelize/sequelize#4422]
So, you can `createTable` in a schema, it creates the table in the assigned schema, but seems like we are not able to `dropTable` on the down migration when reversing changes?

When using this migration:

```
return queryInterface.dropTable('ivr', {
      schema: 'raw_filemaker'
    });
```

gives
`DROP TABLE IF EXISTS "ivr"`;

This is in v3.6.0 w/postgresql.

Upon superficial scan, seems like `return Utils._.template(query)(values).trim() + ';';` in createTableQuery properly prepends the schema, whereas `return Utils._.template(query)({...});` at the end of [dropTableQuery](https://github.com/sequelize/sequelize/blob/84c9a68e55d698f7ee999217aadf80604a5ed126/lib/dialects/postgres/query-generator.js#L89) does not. Oddly, they both call `this.quoteTable(tableName)`?

**Comment by andyATryonsoft** [comment]
I need this function to work with schemas as well. I also need the add and drop column calls to support schemas as well.

**Comment by mickhansen** [comment]
@paulxtiseo It might not support schema via options, you can try `{tableName: 'ivr', schema: 'raw_filemaker'}` instead of `'ivr'`

**Comment by alexmon** [comment]
@paulxtiseo 
@mickhansen is right, try : 

return queryInterface.dropTable(
  {
     tableName: 'ivr',
     schema: 'raw_filemaker'    
  }
);

it worked for me

**Comment by victorschinaider** [comment]
I think it will be better if the options of `dropTable` are consistent with `createTable`, so you could define schemas in `dropTable`like in `createTable`. I think it's a security issue.

**Comment by dkrypt** [comment]
@mickhansen is there a reason this why this is not documented anywhere on such a nice [website](https://sequelize.org/v6/index.html).
