### ISSUE TITLE
Query with include returns an array with one object containing all null values (because there is a column named options in the model)

### ISSUE THREAD

**Issue by andypellucid** [sequelize/sequelize#4423]
We are using sequelize 3.2.0

We have a parent table (e.g. `product`) that has associated tags (e.g. `tag` table) though a many-to-many `productTag` table).  If we query for `product` and include `tag`, but there are no tags, we get a `product` object with a `tags` array containing one `tag`-like object with all null values.  I think this is happening because the query has a left outer join on `productTag` (with inner join on `tag`), but the `tag` columns are all null, which get serialized into an associated `tag` object in the array.

Sorry if this issue already exists or is already fixed - I couldn't find anything related in my searches.

**Comment by janmeier** [comment]
Haven't heard aboy4 any similar issues. Could you post a self-contained test case with models, associations and test data that replicates the issue

**Comment by andypellucid** [comment]
Hi, thanks for your reply.  The code in question was kind of baked into a larger app, so I'm working on an isolated example.  I'll post the code if I can reproduce, or close the issue if I figure out what was wrong with the original code.

**Comment by andypellucid** [comment]
Ok, I think I figured out what's causing this.  If you have a column named `options` in the `product` model, it causes something to break in the instance.js `set` method I think.  The `options` data value is getting set on the instance and apparently blowing away the `Instance`'s `this.options` value, so you lose the `includeOptions`, etc.

Below is my example - some of this might be extraneous - the important part seems to be the field `options` on the `product` model.

### code

```js
#!/usr/bin/env node
var Sequelize = require('sequelize');

var sequelize = new Sequelize('postgres://awhite:@localhost:5432/awhite');

var Product = sequelize.define('product', {
  id: { type: Sequelize.UUID(), defaultValue: Sequelize.UUIDV4(), primaryKey: true, unique: true },
  name: Sequelize.STRING,
  options: Sequelize.JSON
}, {
  paranoid: true
});

var Image = sequelize.define('image', {
  id: { type: Sequelize.UUID(), defaultValue: Sequelize.UUIDV4(), primaryKey: true, unique: true },
  name: Sequelize.STRING
}, {
  paranoid: true
});

var Tag = sequelize.define('tag', {
  id: { type: Sequelize.UUID(), defaultValue: Sequelize.UUIDV4(), primaryKey: true, unique: true },
  name: Sequelize.STRING
}, {
  paranoid: true
});

var File = sequelize.define('file', {
  id: { type: Sequelize.UUID(), defaultValue: Sequelize.UUIDV4(), primaryKey: true, unique: true },
  name: Sequelize.STRING
}, {
  paranoid: true
});

var ProductFile = sequelize.define('productFile', {
  id: { type: Sequelize.UUID(), defaultValue: Sequelize.UUIDV4(), primaryKey: true, unique: true },
  name: Sequelize.STRING
}, {
  paranoid: true
});

Image.belongsToMany(Product, { through: "productImages" });
Product.belongsToMany(Image, { through: "productImages" });

Tag.belongsToMany(Product, { through: "productTags" });
Product.belongsToMany(Tag, { through: "productTags" });

Product.hasMany(ProductFile);
ProductFile.belongsTo(Product);

File.hasOne(ProductFile);
ProductFile.belongsTo(File);

Product.belongsToMany(File, { through: ProductFile });
File.belongsToMany(Product, { through: ProductFile });

var myProduct;

sequelize.sync({ force: true })
  .then(function() {
    return Product.create({
      name: "AAAA000",
      options: {
        key1: {
          value1: 123,
          value2: 456
        },
        key2: "test"
      }
    });
  })
  .then(function(product) {
    //console.log(product);
    myProduct = product;
    return Tag.create({ name: "Share Price" });
  })
  .then(function(tag) {
    myProduct.setTags([tag]);
    return myProduct.save();
  })
  .then(function() {
    return Product.findAll({
      //where: { name: "Andy" },
      include: [{
        model: Image,
        //as: "images"
      }, {
        model: Tag,
        //as: "tags"
      }, {
        model: ProductFile,
        include: {
          model: File
        }
      }]
    });
  })
  .then(function(products) {
    products.forEach(function(product) {
      console.log(JSON.stringify(product.toJSON(), null, 2));
    });
  })
  .catch(function(e) {
    console.log(e);
  });
```

### output

In the code, I have only associated a `tag` with the `product` and no `image` nor `file/productFile`.  However, in the output, the `images` collection and `productFiles` have arrays with a single object with all null values.

```json
{
  "options": {
    "key1": {
      "value1": 123,
      "value2": 456
    },
    "key2": "test"
  },
  "id": "b6b641e3-067f-4542-87e0-e242064f3718",
  "name": "AAAA000",
  "createdAt": "2015-09-03T19:10:07.415Z",
  "updatedAt": "2015-09-03T19:10:07.440Z",
  "deletedAt": null,
  "images": [
    {
      "id": null,
      "name": null,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "productImages": {
        "createdAt": null,
        "updatedAt": null,
        "productId": null,
        "imageId": null
      }
    }
  ],
  "tags": [
    {
      "id": "1e487d80-e2a0-4d61-a045-d0fa21cfe3d3",
      "name": "Share Price",
      "createdAt": "2015-09-03T19:10:07.426Z",
      "updatedAt": "2015-09-03T19:10:07.426Z",
      "deletedAt": null,
      "productTags": {
        "createdAt": "2015-09-03T19:10:07.446Z",
        "updatedAt": "2015-09-03T19:10:07.446Z",
        "productId": "b6b641e3-067f-4542-87e0-e242064f3718",
        "tagId": "1e487d80-e2a0-4d61-a045-d0fa21cfe3d3"
      }
    }
  ],
  "productFiles": [
    {
      "id": null,
      "name": null,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "productId": null,
      "fileId": null,
      "file": {
        "id": null,
        "name": null,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null
      }
    }
  ]
}
```

**Comment by andypellucid** [comment]
A solution on my side would be to not name a column `options`, but I was curious if any changes could be made in the code to avoid this name conflict?  I can take a stab at it, but I'm not familiar with the ins and outs of this code.

**Comment by mickhansen** [comment]
The goal is to get rid of all these conflicts by hiding privates behind a `$` prefix.

**Comment by andypellucid** [comment]
Cool - I tried changing `instance.js` to replace all uses of `this.options` and `self.options` with `this.$options` and `self.$options`.  That seems to fix the issue I'm seeing.  Would you like a pull request for that?

There is also a `this.__options` already in the class - should that be renamed to `this.$modelOptions` or something?

**Comment by andywhite37** [comment]
I created a PR for this - might require more discussion/review.

**Comment by janmeier** [comment]
@andypellucid Could you try latest master ?

**Comment by Shashika1992** [comment]
Are you referring to id field in parent table as foreign key? or Do you have 'id' field in parent table?
