### ISSUE TITLE
Possible bug in documentation: instance.Model()

### ISSUE THREAD

**Issue by angelxmoreno** [sequelize/sequelize#4425]
the docs say `instance.Model()` Returns the Model the instance was created from. However,

```javascript
User.create(data).then(function (user) {
    console.log(user.Model()); //throws `Unhandled rejection TypeError: object is not a function`
    console.log(user.Model); //works
});
```
Am I interpreting the docs correctly or is it a typo?

**Comment by janmeier** [comment]
A bug in the documentation https://github.com/sequelize/sequelize/issues/4193

**Comment by angelxmoreno** [comment]
:+1:
