### ISSUE TITLE
Foreign key constraints

### ISSUE THREAD

**Issue by khwerhahn** [sequelize/sequelize#4426]
Hi,

I would like to disable foreign key constraints in postgres in the seeding phase and after seeding to have them back. 

It would be nice, if there isn't already, if there was an easy to use function in sequelize to enable/disable constraints 

globally

``` javascript
sequelize.disableConstraints()
sequelize.enableConstraints()
```

and per model

``` javascript
Model.disableConstraints()
Model.enableConstraints()
```

**Comment by mariano-aguero** [comment]
+1

**Comment by theoinglis** [comment]
+1

**Comment by bruno-serfe** [comment]
Hi , so there's no way to disable foreign key from sequelize?
