### ISSUE TITLE
Use findOrCreate the Association setter and getter missing

### ISSUE THREAD

**Issue by martinoppitz** [sequelize/sequelize#4427]
If I use only create or find all adder setter remover and getter exists. 

What's wrong? 

Same issue by using findCreateFind.

Wrong Code-Snippet:
```js
Unit.findOrCreate({
    where: {
      id: 1
    },
    defaults: {
      ...
    },
    include: [...]
  })
  .then(function (unit, created) {
    typeof unit.getAssociation === 'function' // is false
    typeof unit.getAssociation === 'undefined' // is true
    ...
  });
```

**Comment by mickhansen** [comment]
The result of both these methods are `[instance, created]` are you taking that into effect? I.e. are you using .spread() or otherwise seperating the arguments?

**Comment by martinoppitz** [comment]
Oh sorry.... Thank you. 

... 
User
  .findOrCreate({where: {username: 'sdepold'}, defaults: {job: 'Technical Lead JavaScript'}})
  .spread

**Comment by mickhansen** [comment]
You'll need to show a bit more code, that looks like the example code from our site, please show your own failing code.

**Comment by martinoppitz** [comment]
Your tip -> I have looked again in the documentation.

That's it ... Thank you for your help.

Correkt Example:
```js
Unit.findOrCreate({
    where: {
      id: 1
    },
    defaults: {
      ...
    },
    include: [...]
  })
  .spread(function (unit, created) {
    typeof unit.getAssociation === 'function' // is true
    typeof unit.getAssociation === 'undefined' // is false
    ...
  });
```
