### ISSUE TITLE
specifying <table_name>.* does not add attributes in model instances

### ISSUE THREAD

**Issue by umar-muneer** [sequelize/sequelize#4430]
the following method call does not return all the attributes of a table.

``` javascript
Model.findAll({
		"attributes":[sequelize.literal("table_name.*"),[Sequelize.fn('COUNT',Sequelize.col('id')),'total']]
	});
```

The resulting array only has the 'total' attribute, the rest are ignored.

**Comment by janmeier** [comment]
Sequelize expects the attributes to be aliassed, thats why they are not added to the model. You could probably fix this by letting `attributes: Object.keys(Model.tableAttributes).concat([..])`

A better solution is https://github.com/sequelize/sequelize/issues/4074
