### ISSUE TITLE
Dialect specific types not handled on insert if field is aliased

### ISSUE THREAD

**Issue by madtrick** [sequelize/sequelize#4431]
## Summary

Dialect specific types (like for example `geometry` on PG) are not parsed/handled on `INSERTS` if they belong to a model attribute which is aliased (i.e. the attribute name is different to the db column name).

**expected behaviour**

After saving an entry the attribute with type `geometry` would contain a GeoJSON object

**broken behaviour**

After saving an entry the attribute with type `geometry` does not contain a GeoJSON object but the raw geometry value.

### Details

This happens because the map that holds the dialect specific attributes in the model [1] uses as keys the alias (not the db column names) but the key used to check if a column in the response rows is dialect specific [2] has the value of the db column.

I created a test that reproduces this behaviour https://github.com/sequelize/sequelize/compare/master...madtrick:fix/transform-aliased-fields

[1] https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query.js#L311
[2] https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query.js#L319

**Comment by janmeier** [comment]
I've added the test in https://github.com/sequelize/sequelize/commit/31da456e21defcc053e3a75c3d81e7afcee2c2a6, which is part of #4431

**Comment by madtrick** [comment]
@jamelt :+1:
