### ISSUE TITLE
ENUMs And Postgresql

### ISSUE THREAD

**Issue by paulxtiseo** [sequelize/sequelize#4436]
Am I right that if I declare this in `createTable()` in a migration:
```
return queryInterface.createTable('meta_ivr', {
...
datatype: {
        type: Sequelize.ENUM('binary','date','decimal','time','timestamp','varchar'),
        allowNull: false
      }
...
, {
      schema: 'raw_filemaker'
    });
```
In postgresql, sequelize only composes the `CREATE TABLE` statement, which in the above example would include the `"datatype" "raw_filemaker"."enum_meta_ivr_datatype" NOT NULL`, but not the necessary `CREATE TYPE "raw_filemaker"."enum_meta_ivr_datatype" AS ENUM ...` statement?

The above migration is giving me a `type "raw_filemaker.enum_meta_ivr_datatype" does not exist` error.

**Comment by janmeier** [comment]
Yes, migrations require a bit more work where you need to create the enum manually
