### ISSUE TITLE
Definition error for datatype Boolean on mssql

### ISSUE THREAD

**Issue by EricCat** [sequelize/sequelize#4438]
When I using ``Sequelize.BOOLEAN`` for definition, while I got type is ``bit`` not ``boolean`` in mssql.
Is it a bug?

**Comment by janmeier** [comment]
http://stackoverflow.com/questions/3138029/is-there-a-boolean-data-type-in-microsoft-sql-server-like-there-is-in-mysql I'm pretty sure mssql doesn't have a boolean type
