### ISSUE TITLE
Models across files and associations

### ISSUE THREAD

**Issue by OscarGodson** [sequelize/sequelize#4439]
I feel like I'm missing something obvious, so sorry if this is a dumb question.

I have a `Post` and `Comment` model. I have them in a `post.js` and `comment.js` file. When I `require()` `Comment` or `Post` and then try to use `belongsTo` or `hasOne` it explodes (full error below). I require them like:

```
var Post = require('./post');
// Model def...
Comment.belongsTo(Post);
module.exports = Comment;
```

And in Post

```
var Comments = require('./comment');
// Model def...
Post.hasMany(Comments);
module.exports = Post;
```

However, if I put comment.js' content directly into post.js it works fine. Requiring comment even works fine in Post as long as there `hasMany` call. It has something to do with requiring models and using them as associations?

```
Server stderr:

Server stderr: /node_modules/sequelize/lib/associations/mixin.js:94
      throw new Error(this.name + '.' + Utils.lowercaseFirst(Type.toString())

Server stderr:         ^

Server stderr: Error: Comment.function (source, target, options) {
  Association.call(this);

  this.associationType = 'BelongsTo';
  this.source = source;
  this.target = target;
  this.options = options;
  this.scope = options.scope;
  this.isSingleAssociation = true;
  this.isSelfAssociation = (this.source === this.target);
  this.as = this.options.as;
  this.foreignKeyAttribute = {};

  if (this.as) {
    this.isAliased = true;
    this.options.name = {
      singular: this.as
    };
  } else {
    this.as = this.target.options.name.singular;
    this.options.name = this.target.options.name;
  }

  if (_.isObject(this.options.foreignKey)) {
    this.foreignKeyAttribute = this.options.foreignKey;
    this.foreignKey = this.foreignKeyAttribute.name || this.foreignKeyAttribute.fieldName;
  } else if (this.options.foreignKey) {
    this.foreignKey = this.options.foreignKey;
  }

  if (!this.foreignKey) {
    this.foreignKey = Utils.camelizeIf(
      [
        Utils.underscoredIf(this.as, this.source.options.underscored),
        this.target.primaryKeyAttribute
      ].join('_'),
      !this.source.options.underscored
    );
  }

  this.identifier = this.foreignKey;

  if (this.source.rawAttributes[this.identifier]) {
    this.identifierField = this.source.rawAttributes[this.identifier].field || this.identifier;
  }

  this.targetKey = this.options.targetKey || this.target.primaryKeyAttribute;
  this.targetIdentifier = this.targetKey;
  this.associationAccessor = this.as;
  this.options.useHooks = options.useHooks;

  // Get singular name, trying to uppercase the first letter, unless the model forbids it
  var singular = Utils.uppercaseFirst(this.options.name.singular);

  this.accessors = {
    /**
     * Get the associated instance
     *
     * @param {Object} [options]
     * @param {String|Boolean} [options.scope] Apply a scope on the related model, or remove its default scope by passing false
     * @return {Promise<Instance>}
     * @method getAssociation
     */
    get: 'get' + singular,
    /**
     * Set the associated model
     *
     * @param {Instance|String|Number} [newAssociations] An array of instances or primary key of instances to associate with this. Pass `null` or `undefined` to remove all associations.
     * @param {Object} [options] Options passed to `this.save`
     * @param {Boolean} [options.save=true] Skip saving this after setting the foreign key if false.
     * @return {Promise}
     * @method setAssociation
     */
    set: 'set' + singular,
    /**
     * Create a new instance of the associated model and associate it with this.
     *
     * @param {Object} [values]
     * @param {Object} [options] Options passed to `target.create` and setAssociation.
     * @return {Promise}
     * @method createAssociation
     */
    create: 'create' + singular
  };
} called with something that's not an instance of Sequelize.Model
    at null.belongsTo (/node_modules/sequelize/lib/associations/mixin.js:94:13)
    at Object.<anonymous> (/models/comment.js:23:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/models/post.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/api/index.js:10:17)
```

**Comment by mickhansen** [comment]
You have a circular require, so in one of the cases the result of require
will be undefined (node require is built to resolve into undefined on
circular rather than throw, i'm unsure why but probably so that you can
later "fix" it).

On Sat, Sep 5, 2015 at 7:38 PM, Oscar Godson <notifications@github.com>
wrote:

> I feel like I'm missing something obvious, so sorry if this is a dumb
> question.
>
> I have a Post and Comment model. I have them in a post.js and comment.js
> file. When I require() Comment or Post and then try to use belongsTo or
> hasOne it explodes (full error below). I require them like:
>
> var Post = require('./post');
> // Model def...
> Comment.belongsTo(Post);
> module.exports = Comment;
>
> And in Post
>
> var Comments = require('./comment');
> // Model def...
> Post.hasMany(Comments);
> module.exports = Post;
>
> However, if I put comment.js' content directly into post.js it works fine.
> Requiring comment even works fine in Post as long as there hasMany call.
> It has something to do with requiring models and using them as associations?
>
> Server stderr:
>
> Server stderr: /node_modules/sequelize/lib/associations/mixin.js:94
>       throw new Error(this.name + '.' + Utils.lowercaseFirst(Type.toString())
>
> Server stderr:         ^
>
> Server stderr: Error: Comment.function (source, target, options) {
>   Association.call(this);
>
>   this.associationType = 'BelongsTo';
>   this.source = source;
>   this.target = target;
>   this.options = options;
>   this.scope = options.scope;
>   this.isSingleAssociation = true;
>   this.isSelfAssociation = (this.source === this.target);
>   this.as = this.options.as;
>   this.foreignKeyAttribute = {};
>
>   if (this.as) {
>     this.isAliased = true;
>     this.options.name = {
>       singular: this.as
>     };
>   } else {
>     this.as = this.target.options.name.singular;
>     this.options.name = this.target.options.name;
>   }
>
>   if (_.isObject(this.options.foreignKey)) {
>     this.foreignKeyAttribute = this.options.foreignKey;
>     this.foreignKey = this.foreignKeyAttribute.name || this.foreignKeyAttribute.fieldName;
>   } else if (this.options.foreignKey) {
>     this.foreignKey = this.options.foreignKey;
>   }
>
>   if (!this.foreignKey) {
>     this.foreignKey = Utils.camelizeIf(
>       [
>         Utils.underscoredIf(this.as, this.source.options.underscored),
>         this.target.primaryKeyAttribute
>       ].join('_'),
>       !this.source.options.underscored
>     );
>   }
>
>   this.identifier = this.foreignKey;
>
>   if (this.source.rawAttributes[this.identifier]) {
>     this.identifierField = this.source.rawAttributes[this.identifier].field || this.identifier;
>   }
>
>   this.targetKey = this.options.targetKey || this.target.primaryKeyAttribute;
>   this.targetIdentifier = this.targetKey;
>   this.associationAccessor = this.as;
>   this.options.useHooks = options.useHooks;
>
>   // Get singular name, trying to uppercase the first letter, unless the model forbids it
>   var singular = Utils.uppercaseFirst(this.options.name.singular);
>
>   this.accessors = {
>     /**
>      * Get the associated instance
>      *
>      * @param {Object} [options]
>      * @param {String|Boolean} [options.scope] Apply a scope on the related model, or remove its default scope by passing false
>      * @return {Promise<Instance>}
>      * @method getAssociation
>      */
>     get: 'get' + singular,
>     /**
>      * Set the associated model
>      *
>      * @param {Instance|String|Number} [newAssociations] An array of instances or primary key of instances to associate with this. Pass `null` or `undefined` to remove all associations.
>      * @param {Object} [options] Options passed to `this.save`
>      * @param {Boolean} [options.save=true] Skip saving this after setting the foreign key if false.
>      * @return {Promise}
>      * @method setAssociation
>      */
>     set: 'set' + singular,
>     /**
>      * Create a new instance of the associated model and associate it with this.
>      *
>      * @param {Object} [values]
>      * @param {Object} [options] Options passed to `target.create` and setAssociation.
>      * @return {Promise}
>      * @method createAssociation
>      */
>     create: 'create' + singular
>   };
> } called with something that's not an instance of Sequelize.Model
>     at null.belongsTo (/node_modules/sequelize/lib/associations/mixin.js:94:13)
>     at Object.<anonymous> (/models/comment.js:23:9)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/models/post.js:3:16)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/api/index.js:10:17)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/4439>.
>



-- 
Mick Hansen
@mhansendev
mhansen.io

**Comment by OscarGodson** [comment]
Ah, this is probably why Geddy Model (using it on a different project) only uses strings, not direct references. For example, the above in Geddy would be written like:

```
Comment.belongsTo('Post');
```

And I don't ever actually require `Post` in my Comment model definition. 

Didn't really click why they went with strings.

**Comment by mickhansen** [comment]
A common way to go is to attach all models to the sequelize instance and
then either call an `associate` method on each model or use a seperate
relations file.

On Sun, Sep 6, 2015 at 9:31 AM, Oscar Godson <notifications@github.com>
wrote:

> Ah, this is probably why Geddy Model (using it on a different project)
> only uses strings, not direct references. For example, the above in Geddy
> would be written like:
>
> Comment.belongsTo('Post');
>
> And I don't ever actually require Post in my Comment model definition.
>
> Didn't really click why they went with strings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/4439#issuecomment-138049973>
> .
>



-- 
Mick Hansen
@mhansendev
mhansen.io

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
