### ISSUE TITLE
Specify the column for .count

### ISSUE THREAD

**Issue by abhinav76** [sequelize/sequelize#4442]
I am trying this 
<code>
return Model.count({distinct:'col_name',where:{some condition}});
</code>
It isn't working and the corresponding sql query that it produces is:
<code>
SELECT count(DISTINCT(*)) AS `count` FROM `mail_box` AS `mail_box` WHERE `mail_box`.`to_username` = 'nikhil9999';
</code>

**Comment by abhinav76** [comment]
@janmeier

**Comment by janmeier** [comment]
You're not going to get a response faster by pinging people - we'll respond when we have the time :)

Currently specifying the column is not supported, so tagging this as a feature request

**Comment by janmeier** [comment]
This should only need a small amount of code + test, so if you have the time it'll be quicker if you fix it yourself and provide a PR than waiting till someone from core has time to do it

**Comment by abhinav76** [comment]
I''ve done it using literal. Thanks anyways

**Comment by abhinav76** [comment]
also if I am able to include more than 1 table in the above query but the they should all be distinct from_username?

**Comment by janmeier** [comment]
No, distinct is only supported for count and other aggregations

I'm not sure what you mean by your second question?

**Comment by abhinav76** [comment]
Actually i wanted to retrieve all the users who have sent message to the specific user along with their info from profile table. So is it any way I can do this?

**Comment by janmeier** [comment]
Maybe, but I have no idea what your schema looks like. Also, that is probably better suited as a SO / google groups / IRC question  - let's keep this issue restricted to `count`
