### ISSUE TITLE
Postgres: invalid input syntax for type bytea

### ISSUE THREAD

**Issue by sheltond** [sequelize/sequelize#4443]
Hi. I'm getting the error "invalid input syntax for type bytea" occasionally, which I believe is due to the escaping used in Sequelize not catching some cases - specifically when the string I assign to the field contains a backslash.

From looking at the Sequelize code (sql-string.js), it seems that if I assign a Buffer object to this field and save it, it uses the bytea hex format, whereas if I assign a string to it, it simply does a little manual escaping of the string.

The escaping is done like this (starting around line 84):

```
if (dialect === 'postgres' || dialect === 'sqlite' || dialect === 'mssql') {
    // http://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
    // http://stackoverflow.com/q/603572/130598
    val = val.replace(/'/g, "''");
}
```

however, the two links in the comments are only concerned with general-purpose escaping of string values for use in a Postgres query, whereas there are some extra constraints when assigning to a bytea field. These are described here: http://www.postgresql.org/docs/9.0/static/datatype-binary.html in section "8.4.2. bytea escape format".

The docs are a bit confusing, since they don't describe what happens when you try to assign a normal string literal to a bytea field, rather than an "Escape string literal" (see here: http://www.postgresql.org/docs/9.0/static/sql-syntax-lexical.html section "4.1.2.2. String Constants with C-Style Escapes").

However, I believe there is an explanation hidden in the text: using a "normal string literal" or an "escape string literal" just changes how the string is converted from its input text format into the internal string representation used in Postgres - the important part I think is what happens when that string is parsed by the "bytea input function". The documentation says:

```
The reason multiple backslashes are required, as shown in Table 8-7, is that an input
string written as a string literal must pass through two parse phases in the
PostgreSQL server. The first backslash of each pair is interpreted as an escape
character by the string-literal parser (assuming escape string syntax is used) and
is therefore consumed, leaving the second backslash of the pair. (Dollar-quoted
strings can be used to avoid this level of escaping.) The remaining backslash is
then recognized by the bytea input function as starting either a three digit octal
value or escaping another backslash. For example, a string literal passed to the
server as E'\\001' becomes \001 after passing through the escape string parser.
The \001 is then sent to the bytea input function, where it is converted to a single
octet with a decimal value of 1. Note that the single-quote character is not treated
specially by bytea, so it follows the normal rules for string literals. (See also
Section 4.1.2.1.)
```

Since Sequelize isn't using the "escape string literal" format, the first part of that quote doesn't really apply, but the important part about how the "bytea input function" treats its input still applies, I believe.

I interpret this to mean that by the time the string is processed by the "bytea input function", any backslash must either start a three digit octal sequence or be immediately before another backslash.

The simplest approach might be to change the code to use the escape string literal format, and escape any backslashes found. However, this might introduce problems with strings containing non-ascii values (which would also need to be escaped), so it probably wouldn't be as simple as that.

It might be possible to just convert '\' into '\' without using the escape string literal format - I suspect that would actually work fine, but I'm not sure.

It's probably worth noting the text in the description of the bytea escape format, which says that it

```
is usually confusing because it fuzzes up the distinction between binary strings
and character strings, and also the particular escape mechanism that was chosen
is somewhat unwieldy. So this format should probably be avoided for most new
applications.
```

so it might be better to just always use the hex format for bytea fields in postgres.

**Comment by janmeier** [comment]
Thorough research @sheltond  - Sorry for not responding to you earlier. Thats the problem with you being so thorough - I have to be so too :D

I believe you are right, that using the hex format always would be the best solution.

Right now the easiest way to do that would probably be to convert a string for a blob field to a buffer in the `instance.set` function. Either that or in `query-generator.escape`

I would also be solved by the data-types up / down system which makes it easier to specify a function which will always be used to stringify blobs

**Comment by ezequielmatalonwhiteprompt** [comment]
Reopen
