### ISSUE TITLE
how to make catch auto-run?

### ISSUE THREAD

**Issue by peze** [sequelize/sequelize#4445]
<pre>
Model.findById(10001).then(function(data){
        Model.create(data).then(function(data){
            res.send({
                status: 0,
                data: data,
                info: "success"
            })
        }).catch(function(err){
            if(err){
                res.send({
                    status: 300,
                    data: err,
                    info: err.message
                })
            }
        });
    }).catch(function(err){
        if(err){
            res.send({
                status: 300,
                data: err,
                info: err.message
            })
        }
    });
</pre>
so, how can i make function catch auto-run after the last function then ?

**Comment by mickhansen** [comment]
Not sure i understand what you mean by 'auto-run'.

In any case you should refactor your code to something like this:

```
Model.findById(10001).then(function(data){
  return Model.create(data);
}).then(function(data){
  res.send({
    status: 0,
    data: data,
    info: "success"
  });
}).catch(function(err){
  res.send({
    status: 300,
    data: err,
    info: err.message
  });
 });
```

To fully utilize promises (currently you're just using them as glorified callbacks)

**Comment by peze** [comment]
yes, it's a good solution...but i want that 
<pre>
Model.findById(10001).then(function(data){
  return Model.create(data);
}).then(function(data){
  res.send({
    status: 0,
    data: data,
    info: "success"
  });
})
</pre>
just use this code , and the catch will still run ...

**Comment by mickhansen** [comment]
`catch` is only triggered if there's an error, inspect the error to see where it's happening.
