### ISSUE TITLE
Model validation problem on update()

### ISSUE THREAD

**Issue by fgs-euf** [sequelize/sequelize#4447]
Hi there

It seems like, when performing an update() query, the validation methods are executed over the model class instead of the model instance (i.e. trying to access any field via ```this``` will return ```undefined```, thus rendering any validation useless).

Here's a quick unit test (I just modified [this one](https://github.com/sequelize/sequelize/blob/master/test/integration/model/update.test.js)):

```javascript
'use strict';

/* jshint -W030 */
var Support = require(__dirname + '/../support')
  , DataTypes = require(__dirname + '/../../../lib/data-types');

describe(Support.getTestDialectTeaser('Model'), function() {
  describe('update', function () {
    it('should only update the passed fields', function () {
      var Account = this.sequelize.define('Account', {
        ownerId: {
          type: DataTypes.INTEGER,
          allowNull: false,
          field: 'owner_id'
        },
        name: {
          type: DataTypes.STRING
        }
      }, {
        validate: {
          validateOwnerId : function () {
console.log('validate', this.ownerId, this.owner_id);
            if ( !this.ownerId ) {
              throw new Error('ownerId not defined');
            }
          }
        }
      });

      return Account.sync({force: true}).then(function () {
        return Account.create({
          ownerId: 2
        }).then(function (account) {
          return Account.update({
            name: Math.random().toString()
          }, {
            where: {
              id: account.get('id')
            }
          });
        });
      });
    });
  });
});
```
From the console.log output, you can see ```this.ownerId``` is ```2``` on insert but ```undefined``` on update

Using sequelize@3.7.1 and postgresql

**Comment by janmeier** [comment]
The problem is that the second validation is only invoked with the values that you pass - in this case the validator only has access to the `name`. This is because you are calling update on the model, as opposed to the instance.

If you only need to validate the ownerid, you can add the `validate` to the column instead, then it will only be invoked when an owner id is passed - the case where no id is passed is already caught by `allowNull: false`

**Comment by janmeier** [comment]
Closing, no response

**Comment by ShepelievD** [comment]
@janmeier what if I want to use custom validation on an update, what should it be?
```
....
validate: {
      async recipientShouldHaveEmail () {
          const tenant = await sequelize.models.User.findOne({
            where: { id: this.userId }
          });
          if (!get(tenant, 'email')) {
            throw new Error('Recipient should have an email');
          }
      }
    }
...
```

how can I access an instance? `this` is undefined on create, **but** on create it is not

**Comment by FernandoLuizNemeChibli** [comment]
Same problem here, I'm getting `this` as `undefined`, even if I set in third parameter of `Sequelize.define`to use other fields as [documentation](https://sequelize.readthedocs.io/en/2.0/docs/models-definition/#validations) describes.

**Comment by papb** [comment]
> how can I access an instance? `this` is `undefined` on update, but on create it is instance

@ShepelievD Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) showing this?

@FernandoLuizNemeChibli You have a mistake in your code, arrow functions do not bind the `this` variable, change the `() => {` to `function() {` and try again.
