### ISSUE TITLE
feat: Add "include" support for `instance.createAssociation()` and `instance.update()`

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#4448]
Like title says, something like the following could be awesome, since will save an extra query:

```js
instance
    .createAssociation(data, {
      include: [{all: true}] // This is not working now.
    })
```

and

```js
instance
    .update(data, {
      include: [{all: true}] // This is not working now.
    })
```

Thanks

**Comment by diosney** [comment]
For instance, now I've to do the following in order to create an object and at the same time return the object with all its associated data:

```js
instance
    .createAssociation(some_data)
    .then(function (data) {
      return models
        .Association
        .findById(data.id, {
          include: [{all: true}]
        })
    })
    .then(function (data) {
      if (!data) {
        return res.sendStatus(404); // Not Found.
      }

      json_api_body.data = data.toJSON();
      res.status(200).json(json_api_body); // OK.
    })

**Comment by mickhansen** [comment]
`createAssociation` should already work with `include` if it's a pure nested create (no existing entries, no updates), not sure if `all` works.

**Comment by diosney** [comment]
As per IRC chat with @mickhansen, this is too elaborate to land in core, so it is recommended to use a hook or the above extra lookup.

@mickhansen Thanks for your help
