### ISSUE TITLE
Polymorphic m:m possible?

### ISSUE THREAD

**Issue by thefabulousdev** [sequelize/sequelize#4450]
I've been looking at the example on the site and I implemented a n:m polymorphic relationship based on the tag example on the docs : 

```js 
ItemTag = sequelize.define('item_tag', {
  tag_id: {
    type: DataTypes.INTEGER,
    unique: 'item_tag_taggable'
  },
  taggable: {
    type: DataTypes.STRING,
    unique: 'item_tag_taggable'
  },
  taggable_id: {
    type: DataTypes.INTEGER,
    unique: 'item_tag_taggable',
    references: null
  }
});
Tag = sequelize.define('tag', {
  name: DataTypes.STRING
});

Post.belongsToMany(Tag, {
  through: {
    model: ItemTag,
    unique: false,
    scope: {
      taggable: 'post'
    }
  },
  foreignKey: 'taggable_id',
  constraints: false
});
Tag.belongsToMany(Post, {
  through: {
    model: ItemTag,
    unique: false
  },
  foreignKey: 'tag_id'
}); 
```

I'm wondering if a many to many polymorphic relationship is possible?

**Comment by mickhansen** [comment]
What's NOT working with the example you have there?

**Comment by thefabulousdev** [comment]
Merely a question , wanting to know if the library handles a many to many polymorphic relationship the way it can handle a one to many as the given example. Will attempt to do it then.

**Comment by mickhansen** [comment]
@thefabulousdev It's not as magic as if it had realy poly support - But you should be able to emulate most with association scopes. The example you posted is N:M, not one to many.
