### ISSUE TITLE
Reload doesn't check if the reloaded instance is defined

### ISSUE THREAD

**Issue by glutentag** [sequelize/sequelize#4452]
Hello,

When we reload an instance, it doesn't check if the returned object is defined:
```
 return this.Model.findOne(options).bind(this).then(function(reload) {
    this.set(reload.dataValues, {
      raw: true,
      reset: true && !options.attributes
    });
  }).return(this);
```
Returning us a TypeError: 
`Cannot read property 'dataValues' of null`

It would be nice to have an error to catch there. Should it be a native Error or a SequelizeErrors?

**Comment by mickhansen** [comment]
I suppose this would happen in cases where the object you're attempting to reload has been deleted in the meantime?

**Comment by glutentag** [comment]
Exactly.
