### ISSUE TITLE
Model definition without id as primaryKey raise error for mysql partitioned tables

### ISSUE THREAD

**Issue by vikramcp** [sequelize/sequelize#4454]
Hi,

In mysql we are partitioning a table which may not have a primary key or has composite primary key. This fix might break those model definitions. I have table with id and account_id, which is partitioned by account_id, so my primary key would be (id, account_id), but with this fix the table definition is not possible. In the below table since i could not define a composite primary key i just defined the same as unique index.

Is there some other workaround?

  var Project = sequelize.define('Project', {
    id:{
      type: Sequelize.BIGINT(20),
      allowNull: false,
      autoIncrement: true
    },
    title: Sequelize.STRING,
    description: Sequelize.TEXT,
    account_id: {
      type: Sequelize.BIGINT(20),
      allowNull: false
    }
  },
  {
    indexes: [
      {
        name: 'id_and_account_id',
        type: 'UNIQUE',
        fields: ['id', 'account_id']
      }
    ]
  });

**Comment by mickhansen** [comment]
You should be able to add `primaryKey: true` to multiple fields.
But no composite primary keys are poorly supported.

**Comment by mohitkumaronj** [comment]
In many to many relation table , I do not need any primary key. but sequelize give error for it. how to handle it .
