### ISSUE TITLE
targetKey not working in BelongsTo association (sync() problem?)

### ISSUE THREAD

**Issue by guigrpa** [sequelize/sequelize#4455]
Consider this very simple case (under Sequelize v3.7.1):

```coffee
User = sequelize.define 'user',
  name: Sequelize.STRING
  uid: 
    type: Sequelize.INTEGER
    unique: true
Photo = sequelize.define 'photo',
  location: Sequelize.STRING
  itemId: 
    type: Sequelize.INTEGER
Photo.belongsTo User,
  foreignKey: 'itemId'
  targetKey: 'uid'

sequelize.sync()
```

The query generated by `sync()` ignores the `targetKey` configuration:

```sql
CREATE TABLE IF NOT EXISTS "photos" (
    "id"   SERIAL , 
    "location" VARCHAR(255), 
    "itemId" INTEGER REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, 
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, 
    PRIMARY KEY ("id")
);
```

You can see it references `id` instead of `uid`, as intended.

If, on the contrary, we specify `{references: {model: User, key: 'uid'}}` when calling `sequelize.define()`, the relationship is created by `sync()` correctly. In this case, the relationship also works correctly when e.g. creating a photo and calling `getUser()` on it, so I guess the problem is in the implementation of `sync()`.

As a side note, when will `targetKey` be supported for HasMany relationships? It seems to me a very important feature.

**Comment by guigrpa** [comment]
See also #4269 and #4258

**Comment by guigrpa** [comment]
I can also confirm that, in the example above, finding `Photos` and `include`ing the corresponding `User` works as expected.

**Comment by mickhansen** [comment]
We have a working test here: https://github.com/sequelize/sequelize/blob/ea63814b62ffe3133ea9d4475d337b4b14792da8/test/integration/include/find.test.js#L173

**Comment by guigrpa** [comment]
Interesting. Looking at the test, I find the following line (I don't know why the `id` is removed in this test):

```js
User.removeAttribute('id');
```

If I do that in my case, the FK constraint is not created at all (this is not verified in the test):

```sql
CREATE TABLE IF NOT EXISTS "photos" (
    "id"   SERIAL , 
    "location" VARCHAR(255), 
    "itemId" INTEGER, 
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, 
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, 
    PRIMARY KEY ("id")
);
```

...and getting the `User` from a created `Photo` works correctly, just as in the test.

**Comment by mickhansen** [comment]
Hmm, curious if it works without removing the primary key, maybe it doesn't.

**Comment by jayfresh** [comment]
I also stumbled into this problem. Removing the id from the target removes the error, but I also fail to see the relation created in the SQL.

**Comment by mickhansen** [comment]
Looks like the test was written like that because SQLITE does not support constraints on anything other than primary key.

**Comment by mickhansen** [comment]
Ah well, neither does postgres, looks like there shouldn't be a constraint at all then.
