### ISSUE TITLE
Mocha and Sequelize

### ISSUE THREAD

**Issue by ThomasHambach** [sequelize/sequelize#4458]
I am trying to use the Mocha testing suite to test my code at this moment. Running Mocha throws the error "Cyclic dependency found". This because of the following:

Membership model

    ...
    classMethods: {
      associate: function(models) {
        Membership.belongsTo(models.User, {foreignKey: 'UserId'});
      }
    },
    ...
User model

    ...
    classMethods: {
      associate: function(models) {
        UserProfile.hasOne(models.Membership, {foreignKey: 'UserId'});
      } 
    },
    ...

Any ideas on how to solve this are greatly appreciated. I know this may not directly be an issue with Sequelize.

**Comment by mickhansen** [comment]
Those are your only two models?
`sync()` will throw a cyclic dependency if it finds one, but it generally requires a bit more than two models.

**Comment by angelxmoreno** [comment]
@ThomasHambach could you show the full context of your models?

**Comment by janmeier** [comment]
Closing, no response
