### ISSUE TITLE
Plugins system for sequelize

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#4463]
I've implemented very simple yet powerful plugin system for Sequelize in PR #4462.
I know that there were some discussions about plugins (#2462) but AFAIK for now there are some conventions only and not solutions.

Whole plugin system is based on built in Sequelize hooks: beforeInit, afterInit, beforeDefine and afterDefine. I've explained everything in PR #4462 comment (there is also plugin example and plugin usage example).

@janmeier @mickhansen could you look into PR comment (#4462) and tell me if you like this idea?

In my opinion such solution (or similar) would make writing and using plugins much easier and would also allow to keep plugins code consistent (each plugin "exports" just 4 callbacks). And, what's most important it would allow (more easily) to keep code DRY. AFAIK for now the most common approach for plugins is to initialize them by passing `Sequelize` to them  (ie. `require('my-plugin')(Sequelize)`) but anyway those plugins have to set up proper hooks on their own.

I think my solution makes it more DRY and consistent. It's also very powerful as it allows to completely modify both sequelize instance and sequelize models.

**Comment by overlookmotel** [comment]
Hi @alekbarszczewski.

I totally agree with you that the way plugins interface with Sequelize should ideally be standardized.

In my personal opinion, however, I don't think the way you've proposed is the right way to go about it.

There's also a more recent discussion of plugins here: https://github.com/sequelize/sequelize/issues/2508

It might be a good idea to continue this discussion there so it's all in one place?

**Comment by alekbarszczewski** [comment]
@overlookmotel Ah, damn, if I saw this issue (#2508) I would not make my own PR :). For some reason I didn't find it. Closing this one.
