### ISSUE TITLE
Bad SQL when using `include` in scoped models

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#4466]
Below is an example of some code using a scope to include an associated model.

`Folder` is associated with itself. When calling `find()` on the scoped model, also `include`-ing the scoped model, the SQL created is incorrect and causes an error.

```js
var Drive = this.sequelize.define('drive', { name: Sequelize.STRING });

var Folder = this.sequelize.define('folder', { name: Sequelize.STRING }, {
    scopes: {
        withDrive: function () {
            return {include: [{model: Drive, attributes: ['id']}]};
        }
    }
});

Folder.hasOne(Folder, { as: 'parent' });

Drive.hasMany(Folder);
Folder.belongsTo(Drive);

var ScopedFolder = Folder.scope('withDrive');

/*
 * This works. Generated SQL ends:
 * LEFT OUTER JOIN `drives` AS `parent.drive` ON `parent`.`driveId` = `parent.drive`.`id`
 */
Folder.findAll({
    include: [{model: ScopedFolder, as: 'parent'}]
});

/*
 * This doesn't work. Generated SQL ends:
 * LEFT OUTER JOIN `drives` AS `drive` ON `folder`.`driveId` = `drive`.`id`
 * LEFT OUTER JOIN `drives` AS `drive` ON `folder`.`driveId` = `drive`.`id`
 *
 * Throws error `ER_NONUNIQ_TABLE: Not unique table/alias: 'drive'`
 */
ScopedFolder.findAll({
    include: [{model: ScopedFolder, as: 'parent'}]
});
```

I don't know the code for scopes well enough to easily find a fix for this. But it worked previous to v3.5.0 and has been broken since.

If a PR with a failing test case would be helpful, could someone please point me to the right test file to put it in?

**Comment by janmeier** [comment]
Hmm, yeah this works if you include folder drive manually on both folders.. dammit :D

**Comment by overlookmotel** [comment]
Yeah, sorry to bring bad news to the table! Thanks for taking on fixing it. I don't use scopes myself but it was causing the tests to fail on one of my Sequelize plugins.

**Comment by mickhansen** [comment]
Possibly fixed by https://github.com/sequelize/sequelize/pull/4518?

**Comment by overlookmotel** [comment]
I don't know if it was #4518 which fixed it or not, but can confirm it's now working fine in v3.9.0. Sorted!
