### ISSUE TITLE
Getting columns from association table

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/sequelize#4469]
I would like to select all the columns from the association table:
````js
var UserProjects = sequelize.define('userprojects', {
  UserId: Sequelize.INTEGER,
  ProjectId: Sequelize.INTEGER,
  StartDate: Sequelize.Date,
  EndDate: Sequelize.Date
})
User.hasMany(Project, { through: UserProjects })
Project.hasMany(User, { through: UserProjects })
`````
If I use the following sequelize query:

```js
    models.user.findOne({where: {UserId: 1},
                           include: [{ model: models.project, as: 'Projects', required: true]}
                           ]}).success(function(order){
                           res.json(order)
                          }).error(function(err){
                            res.json({type: false, error: err});
                          })


````
I am only able to get UserId and ProjectId not the StartDate and EndDate.

**Comment by mickhansen** [comment]
2 x HasMany for N:M has been depecated a while and completely removed from `3.x.x`, what version are you using?

**Comment by zeeshanjan82** [comment]
I am facing the same issue with belongsToMany I am not able to get the columns of the association table. Also I have a question. I am implementing Orders and Articles. An Article belongs to many orders but I think I cannot have an order belonging to many articles. It should be like this

article.belongsToMany(order)
order.hasMany(article)

**Comment by zeeshanjan82** [comment]
I am now using the latest 3.8.0 version also am using belongsToMany on both sides but still I am not able to select all the columns from the association through table.

**Comment by zeeshanjan82** [comment]
Ok! I have found a work around to this problem and I am able to now move forward but have just put a comment that I need to come back and use the proper fix for this, I am not happy with the way I have done this now. Following are the details:

I have an Order table and Article table both tables have N:M relation through OrderItems table.Now my OrderItems table has columns like OrderId, ArticleId and extra columns like Quantity e.t.c My main issue has been to fetch the extra columns like Quantity when I perform a query on Orders table. Following is my query:

```js
    models.order.findOne({where: {OrderId: req.param('orderId')},
                           include: [{ model: models.table, as: 'Tables', required: true, attributes: ['Id', 'TableId','Name'] },
                                     { model: models.article, as: 'Articles', required: true, attributes: ['ArticleId', 'FullName', 'CurrentPrice'],
                                       //ToDo:Should not have used this as we should be able to get these details from orderitems
                                       include: [{model: models.orderitem, as: 'OrderAttributes', attributes: ['Quantity']}]}
                           ]}).then(function(order){
                           res.json(order)
                          }).error(function(err){
                            res.json({type: false, error: err});
                          })
  });
````
In the above code If I do not use the 'OrderAttributes' include then I cannot fetch the Quantity column, even though I am getting OrderId and ArticleId

**Comment by mickhansen** [comment]
```js
article.belongsToMany(order)
order.hasMany(article)
```

should be 

```
article.belongsToMany(order)
order.belongsTohasMany(article)
```

**Comment by mickhansen** [comment]
At the moment you generally need to include the join table if you need to do operations like order on it.

**Comment by zeeshanjan82** [comment]
Thanks @mickhansen It somehow does not feel right. But for now its time to move ahead.
