### ISSUE TITLE
Memory leak & maximum call stack exceeded using hasMany with scope

### ISSUE THREAD

**Issue by Verdier** [sequelize/sequelize#4470]
Considering the following model definitions:
```js
var User = sequelize.define('User', {
    name: Sequelize.STRING
});

var Project = sequelize.define('Project', {
    type: Sequelize.STRING,
    title: Sequelize.STRING
});

User.addScope('defaultScope', {
    include: [Project]
}, {
    override: true
});

Project.belongsTo(User);

User.hasMany(Project, {
    scope: {
        type: 'open'
    }
});
```
We create a user and a project:
```js
let user = yield User.create({
    name: 'John'
});
yield user.createProject({
    name: 'Project 1'
});
```
Then querying the user multiple times as following: 
```js
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
```
Result in a growing array `value` in `query-generator.js:1913` in `whereItemQuery` method. Logging the array `value` around line 1923 after the recursive call to `whereItemQuery`, we obtain the following: 
```sql
'((((((((((((("Projects"."type" = \'open\' AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\')',
  '"Projects"."type" = \'open\'' 
```
The size increase at each query.

**Comment by Verdier** [comment]
This result in an increasing *memory usage* and quickly result in a *call stack exceeded*.

**Comment by janmeier** [comment]
I believe we've had something similar before - are you on the latest version?

**Comment by Verdier** [comment]
Yes I'am using `3.8.0`.

**Comment by Verdier** [comment]
I'am actually looking for the origine of the issue. But I couldn't understand how a call to the query method could depend on a previous call. Is there a non reset array somewhere? that's very strange.

**Comment by mickhansen** [comment]
Likely an options object that's not cloned before use somewhere.

**Comment by Verdier** [comment]
@mickhansen the bug starts at `query-generator.js:947`
```js
  selectQuery: function(tableName, options, model) {
    // Enter and change at your own peril -- Mick Hansen
```
I've not fully localised the origine (in progress) but do you remembers the reason of the comment... ?

**Comment by mickhansen** [comment]
The select query generation codebase is just slightly complex, so just a warning in humour ;)

**Comment by Verdier** [comment]
Okey :smile: that's probably a good location for bug :+1: :cookie:

**Comment by Verdier** [comment]
@mickhansen the problem of history is due to `Model.$injectScope` which inject some reference of `Model.$scope` (such ase `$scope.include`) into the `option`. But somewhere after, the code modify that object (ie. something in `option.include` and consequently `Model.$scope`) which is used in the next call, modified again etc...

**Comment by Verdier** [comment]
Here is the `$scope` at the first call :
<img width="464" alt="screen shot 2015-09-14 at 11 23 43" src="https://cloud.githubusercontent.com/assets/2900150/9846592/5c03539c-5ad3-11e5-81d0-7be091918a6d.png">
At the second :
<img width="465" alt="screen shot 2015-09-14 at 11 24 27" src="https://cloud.githubusercontent.com/assets/2900150/9846595/64b90112-5ad3-11e5-91b1-3eb1c7306415.png">
<img width="462" alt="screen shot 2015-09-14 at 11 26 23" src="https://cloud.githubusercontent.com/assets/2900150/9846625/a89f947c-5ad3-11e5-93b0-e0fa8f4d1ccd.png">
At the third :
<img width="464" alt="screen shot 2015-09-14 at 11 27 34" src="https://cloud.githubusercontent.com/assets/2900150/9846633/b47c55d2-5ad3-11e5-9a9f-7162f267a5ee.png">

**Comment by mickhansen** [comment]
`$injectScope` should not be used anywhere in `selectQuery`, i believe there's another open issue about the first argument `scope` to `$injectScope` being modified without being cloned first.

**Comment by mickhansen** [comment]
Only problem i see is https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2541 though which reverses the array in place, shouldn't cause this bug though.

**Comment by Verdier** [comment]
the most strange thing is that `$scope.include[0]` type change after the first query, it first contain an object with a model, and then something else, which probably define the query ?!

**Comment by Verdier** [comment]
It's not in `selectQuery`, `$injectScope` is called from https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1299. The problem is before `selectQuery`.
