### ISSUE TITLE
Sequelize - BulkCreate over 100 000 rows cause ConnectionError

### ISSUE THREAD

**Issue by DemarsM** [sequelize/sequelize#4471]
I am using Sequelize to insert values from a json file into a Postgres database using bulkCreate. There is over 100 000 objects to insert.

I am simply doing like this:

    var fs = require('fs');
    var Point = require('./point');
    
    fs.readFile('data.json', function(err, data){
        if (err) throw err;
        data = JSON.parse(data);
        Point.bulkCreate(data);
    });

After a while I got this error: `SequelizeConnectionError: read ECONNRESET`

However, if I loop over the json objects an create rows individually, there is no problem:

    var fs = require('fs');
    var Point = require('./point');
    
    fs.readFile('data.json', function(err, data){
        if (err) throw err;
        data = JSON.parse(data);
        for (var i=0; i < data.length; i++){
            Point.create(data[i]);
        }
    });

What could be the problem with bulkCreate?

**Comment by mickhansen** [comment]
Connection timeout because of a long running query?
Have you tried running the query manually?

**Comment by DemarsM** [comment]
@mickhansen yes you are probably right. Is there an option you can use into bulkCreate to force connection to stay alive for a long query, or it's a setting that must be changed in the database itself?

I have not try the query manually. I will.

**Comment by mickhansen** [comment]
@DemarsM Not for bulkCreate specifically, you might be able to increase the general idle timeout, you might have to tweak the server settings aswell though.

**Comment by DemarsM** [comment]
@mickhansen  allright I'll look into that. Thank you!
