### ISSUE TITLE
DEFAULT 'NULL' on deletedAt

### ISSUE THREAD

**Issue by gaboAcosta** [sequelize/sequelize#4472]
We are creating our tables using migrations from sequelize, on sqlite we have a situation where two migrations result in two different values, for One, it will leave the default value for the deletedAt empty and in another it puts as default value the string 'NULL'

The definition of the field for the two of them is exactly the same

``` javascript
        createdAt: {
          type: Sequelize.DATE
        },
        updatedAt: {
          type: Sequelize.DATE
        },
        deletedAt: {
          type: Sequelize.DATE
        }
```

Has anybody got this issue? Maybe a poingter as to why on one migration it actually adds a default and not in the other?

**Comment by mickhansen** [comment]
That is odd. Models will add default values to createdAt/updatedAt but there should be no magic in migrations.

**Comment by gaboAcosta** [comment]
This is the result of: PRAGMA table_info(Shop)

![screen shot 2015-09-11 at 3 52 18 pm](https://cloud.githubusercontent.com/assets/4994205/9826092/5191e708-589d-11e5-8b98-db25163f880c.png)

**Comment by mickhansen** [comment]
Looks like `deletedAt` did in fact get a default value?

**Comment by gaboAcosta** [comment]
That's correct, but even with the default value, it should be NULL not 'NULL' which is a string.

**Comment by mickhansen** [comment]
@gaboAcosta Very odd, what does the SQL look like for the create table statement?
