### ISSUE TITLE
Model.create() ignoring includes option.

### ISSUE THREAD

**Issue by dnlsandiego** [sequelize/sequelize#4475]
I am having an issue with `Model.create()`, it seems to be ignoring the `include` option to eager load the associations for the model instance to be returned. Or at least thats what I understood from reading the docs.

Model definition:
```
var Post = sequelize.define('Post', {
    title: {
        type: Sequelize.STRING,
        field: 'title'
    },
    body: {
        type: Sequelize.STRING,
        field: 'body',
    },
},
{
    classMethods: {
        associate: function(models) {
              Post.belongsTo(models.User, { as: 'user' });
    }
} 
```
Instance creation:
```
Post.create({
    title: 'Test title',
    body: 'Test body',
    userId: 1
},
{
    include: [ { model: User, as: 'user' } ]
})
.then(function(post) {
    
    console.log(post.get({ plain: true }));
    //  {
    //      title: 'Test title',
    //      body: 'Test body',
    //      userId: 1,
    //      createdAt: Fri Sep 11 2015 23:40:45 GMT-0500 (CDT),
    //      updatedAt: Fri Sep 11 2015 23:40:45 GMT-0500 (CDT)
    //  }
});
```

What I expected to happen was that the user model that is associated with the post model is loaded as well and attached to the post instance that is being returned as per the docs but what's happening(for me, at least) is that user model instance is not being included.

I also tried `[ { all: true } ]` for the value in the `include` option but nothing works.

**Comment by mickhansen** [comment]
What you expected is not implemented. We support nested creation, we don't support nested loaded via creates.

You can implement it with a hook if you need it.
Closing this in favor of general expansion of nested creation (which should eventually support existing instances aswell).

**Comment by dnlsandiego** [comment]
Ahh cool. The reason I expected `Model.create` to accept a `include` option and include the associated model in the returned instance was based on what I read on the docs, http://docs.sequelizejs.com/en/latest/api/model/#createvalues-options-promiseinstance. The listed possible `params` for the method included a option for `include`. Is that the correct method definition for the `Model.create`?

**Comment by mickhansen** [comment]
Ah, the option is correct, but the description is wrong, `include` in the case of `create` is for nested creation.
