### ISSUE TITLE
BUG in bulkCreate: Not properly converting column names to snake case in the database

### ISSUE THREAD

**Issue by ilaif** [sequelize/sequelize#4476]
Hey guys,
Found a bug and/or inconsistency between create and bulkCreate.

Model:
```js
    var model = sequelize.define('Group', {
        name: {
            type: DataTypes.STRING,
            field: 'name',
            allowNull: false
        },
        description: {
            type: DataTypes.STRING,
            field: 'description',
            allowNull: true
        },
        createdAt: {
            field: 'created_at',
            type: DataTypes.DATE
        },
        updatedAt: {
            field: 'updated_at',
            type: DataTypes.DATE
        }
    }, {
        tableName: 'groups',
        classMethods: {
            associate: function (models) {
                model.belongsToMany(models.User, {through: 'UserGroup', foreignKey: 'user_id'});
            }
        }
    });
```

When calling:
```js
Group.create({
        id: 1,
        name: 'Administrators',
        description: 'Administrators'
});
```
Everything works as expected.

But when calling:
```js
Group.bulkCreate([{
        id: 1,
        name: 'Administrators',
        description: 'Administrators'
}]);
```
A sequelize error is raised stating that createdAt column doesn't exist - But I specifically defined that createdAt has field 'created_at'. Full error:
```js
{
   "name":"SequelizeDatabaseError",
   "message":"ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'",
   "parent":{
      "code":"ER_BAD_FIELD_ERROR",
      "errno":1054,
      "sqlState":"42S22",
      "index":0,
      "sql":"INSERT INTO `groups` (`id`,`name`,`description`,`createdAt`,`updatedAt`) VALUES (1,'Administrators','Administrators','2015-09-12 12:47:24','2015-09-12 12:47:24'),(2,'Users','Users','2015-09-12 12:47:24','2015-09-12 12:47:24'),(3,'Resellers','Resellers','2015-09-12 12:47:24','2015-09-12 12:47:24');"
   },
   "original":{
      "code":"ER_BAD_FIELD_ERROR",
      "errno":1054,
      "sqlState":"42S22",
      "index":0,
      "sql":"INSERT INTO `groups` (`id`,`name`,`description`,`createdAt`,`updatedAt`) VALUES (1,'Administrators','Administrators','2015-09-12 12:47:24','2015-09-12 12:47:24'),(2,'Users','Users','2015-09-12 12:47:24','2015-09-12 12:47:24'),(3,'Resellers','Resellers','2015-09-12 12:47:24','2015-09-12 12:47:24');"
   },
   "sql":"INSERT INTO `groups` (`id`,`name`,`description`,`createdAt`,`updatedAt`) VALUES (1,'Administrators','Administrators','2015-09-12 12:47:24','2015-09-12 12:47:24'),(2,'Users','Users','2015-09-12 12:47:24','2015-09-12 12:47:24'),(3,'Resellers','Resellers','2015-09-12 12:47:24','2015-09-12 12:47:24');"
}
```

Essentially what happens is that the conversion is not happening in bulkCreate like in create (where it is the expected behavior).

I'm using version: 3.8.0

Thanks!
Ilai

**Comment by ilaif** [comment]
Hey,

I'm seeing this is labeled as a bug, how can I see the pipeline so I can get an estimation when will it be handled?

Thanks,
Ilai

**Comment by janmeier** [comment]
@ilaif You can't - Our process isn't that formal, we are very few people, so people work on stuff when they have time.
The quickest way to get a fix is to do it yourself - we are happy to help :)

**Comment by ilaif** [comment]
Ok great!

So I've forked the project and started digging into the code.... many places to cover.

The problem in general as I see it:
I'm using js variable convention (camelCase) and underscore convention in my mysql db.
Therefore I define every attribute and every foreign key relation as:
attributeName: {
  field: 'attribute_name'
}

Regarding timestamp fields, I'm currently supposedly 'overriding' the defaults by adding an attribute:
createdAt: {
  field: 'created_at'
}

This works with most of the basic functions. But with upsert and bulkInsert it doesn't, and possibly other functions.

What I'm trying to achieve is understand how I can tell Sequelize that if a timestamp attribute should exist (timestamps: true, createdAt: true etc...) and an 'override' createdAt attribute exists, then use that as the attribute and therefore have the key of the attribute in camelCase and the db field as underscore.
I have yet to find a generic place where I can change that, if you point me to possible places in the code I can change there and run tests to verify it's working.

**Comment by janmeier** [comment]
Unfortunately we don't have a generic place to tell that- But if you're up to it we should definitely introduce one! :)

We do have `primaryKeyAttribute` and `primaryKeyField`, so perhaps `deletedAtField` etc. would be good.

**Comment by hiEven** [comment]
hello, is there anyone still working on fixing this bug ?
I just encountered the same issue and my workaround was writing some raw sql which might not be great.
If anyone can help, I will be appreciate and devote myself to help :+1:

**Comment by Kadrian** [comment]
I get the same error when using the seeders and 
```
return queryInterface.bulkInsert('Clients', [{
    name: 'Hello',
    email: 'my@test-mail.com',
}]);
```

I could just generate the timestamp manually on migration. But is that the way to go? I can also not find any documentation of the bulkInsert method anywhere.

**Comment by flyingrx** [comment]
mark
