### ISSUE TITLE
NULL for non-deleted would not work when deletedAt is used in composite unique keys

### ISSUE THREAD

**Issue by kenjitayama** [sequelize/sequelize#4481]
For exapmle, with a `users` table like the following, it is possible to create multiple non-deleted users with the same email (which we are trying to prevent using unique keys), because `NULL` is unmatchable.

```
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(100) NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `compositeUniqueKey` (`email`,`deletedAt`)
)
```

```
sequelize.define('user', {

  email: {
    type: Sequelize.STRING(10),
    allowNull: false,
    unique: 'compositeUniqueKey'
  },

  deletedAt: {
    type: Sequelize.DATE,
    unique: 'compositeUniqueKey'
  }

}, {
  paranoid: true,
});
```  

With help from comments in issue #3468, I added `defaultValue: 0` to `deletedAt` and figured out how to use it with the `paranoid` feature.

I made a fork for myself and dived in for the first time :)
https://github.com/kenjitayama/sequelize/commit/b5d19d80042c37f436dd549a4b1288b53544987e
With this modification, deletedAt's `defaultValue` is used instead of NULL, in `paranoidClause` and `restore`.
It's working for me so far, but I'm not sure if this is the ideal way to address this issue.

It would be great if we can use a syntax like the following when defining a model,
```
paranoid: {
  defaultValue: 0
}
```
but I couldn't figure out how to implement it.

**Comment by mickhansen** [comment]
A simple fix would be to have `paranoid` look at the defaultValue of `deletedAt` and then do a query based on that.

**Comment by kenjitayama** [comment]
@mickhansen 
I think thats just what I did in my new fork of Sequelize, and I made a PR from it now.
I am having trouble setting up Docker (first time using docker) and haven't written tests yet.

I installed boot2docker via homebrew, and need to fix the following somehow..
```
$ boot2docker init
error in run: Failed to initialize machine "boot2docker-vm": exit status 1
```

The OSX Docker Documentation says boot2docker is deprecated. Are the instructions in the CONTRIBUTING page still valid? Or should I use the Docker Machine instead?

**Comment by mickhansen** [comment]
The OSX instructions might not be valid, i personally use Ubuntu.
You can start out by testing against sqlite.

**Comment by kenjitayama** [comment]
Thanks for code review! Looks like I should checkout some JS style guide..
I'll try writing tests, and get my PR ready.

**Comment by kenjitayama** [comment]
Thanks for supporting on the PR!
I added a issue about the new paranoid option syntax.

**Comment by broofa** [comment]
What DB are you running on top of? I'm trying to use `defaultValue: 0` for deletedAt, but MySQL complains that `0` is an invalid value for DATETIME columns.
