### ISSUE TITLE
Does sequel support disk or me 

### ISSUE THREAD

**Issue by snowcxt** [sequelize/sequelize#4484]
Does sequelize support local memery and/or disk as waterline does? So we don't have to have the real database for development.

**Comment by mickhansen** [comment]
We don't have any disk/mem mock dialect - But you can use sqlite for the most part, but sqlite doesn't support everything that PG/MySQL does so if you want to use advanced features you should really test against what you deploy with (imo you should mimic your production environment as much as possible in any case).
