### ISSUE TITLE
foreign key constraint error

### ISSUE THREAD

**Issue by OscarGodson** [sequelize/sequelize#4485]
I'm not super great with MySQL yet so im struggling with why this is happening. I had everything working fine and then I dropped the DB to start fresh and now the code no longer works. Here's the error"

```log
2015-09-12 23:03:16 12d144000 Error in foreign key constraint of table app/comments:
FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB:
You have defined a SET NULL condition though some of the
columns are defined as NOT NULL.
```

Here's the SQL it's trying to inject:

```sql
CREATE TABLE IF NOT EXISTS `posts` (`id` CHAR(36) BINARY , `title` VARCHAR(255) NOT NULL, `body` TEXT NOT NULL, `slug` TEXT, `cover_photo` TEXT, `created_at` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;

SHOW INDEX FROM `posts`

CREATE TABLE IF NOT EXISTS `comments` (`id` CHAR(36) BINARY , `post_id` CHAR(36) BINARY NOT NULL, `body` TEXT NOT NULL, `created_at` DATETIME, PRIMARY KEY (`id`), FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
```

Here's my model definitions

```js
var Sequelize = require('sequelize');
var orm = require('../utils/orm');
var Comments = require('./comment');

var Post = orm.define('post', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4, // Generates a UUID V4
    primaryKey: true
  },
  title: {
    type: Sequelize.STRING, // Should cap titles to 255 characters
    allowNull: false
  },
  body: {
    type: Sequelize.TEXT,
    allowNull: false
  },
  slug: {
    type: Sequelize.TEXT, // URLs can be any length
    allowNull: true
  },
  cover_photo: {
    type: Sequelize.TEXT, // URLs can be any length
    allowNull: true
  },
  created_at: {
    type: Sequelize.DATE,
    defaultValue: Sequelize.NOW
  }
}, {
  timestamps: false,
  underscored: true
});

Post.hasMany(Comments);
Comments.belongsTo(Post);

module.exports = Post;
```

```js
var Sequelize = require('sequelize');
var orm = require('../utils/orm');

var Comment = orm.define('comment', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4, // Generates a UUID V4
    primaryKey: true
  },
  post_id: {
    type: Sequelize.UUID,
    allowNull: false
  },
  body: {
    type: Sequelize.TEXT,
    allowNull: false
  },
  created_at: {
    type: Sequelize.DATE,
    defaultValue: Sequelize.NOW
  }
}, {
  timestamps: false,
  underscored: true
});

module.exports = Comment;
```

I read in another post to try flipping the associations around, but it didn't help. I tried flipping it to:

```js
Comments.belongsTo(Post);
Post.hasMany(Comments);
```

**Comment by angelxmoreno** [comment]
I had something similar happen to me. I simply removed the foreign keys from the model definition and let the associations create it for me. When you attach associations Sequelize will create those foreign keys for you. I think the error is that they already exist because you defined them in the model. Try removing the `post_id` column from `Comments` model. Please let us know if it works.

**Comment by OscarGodson** [comment]
I _think_ that did it!

**Comment by OscarGodson** [comment]
Closing for now because I was able to create both a post and the associated comment

**Comment by angelxmoreno** [comment]
:+1: thumbs

**Comment by OscarGodson** [comment]
UPDATE: removing this didn't have it auto make the associations. I noticed my DB was showing NULL for all new comments after removing this. I added it back, changed `allowNull` to true and it started working. However, I don't want to ever allow for comments without a post so I ended up with this code:

```js
Comment.hook('beforeValidate', function (comment) {
  if (!comment.post_id) {
    throw new Error('post_id cannot be NULL');
  }
});
```

The above prevents null submissions. 

Then, to prevent non-UUID submissions:

```js
  post_id: {
    type: Sequelize.UUID,
    allowNull: true, // allow true because we catch this in a hook
    validate: { isUUID: 4 } // make sure it's always a UUID
  },
```

**Comment by Americas** [comment]
The problem is in the SQL that is being generated. The FK constraint states that if you delete a row in posts, and that row has comments associated, it will set that key to NULL, which it can't.

```sql
REFERENCES `posts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
```
should be 
```sql
REFERENCES `posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
```

**Comment by mickhansen** [comment]
@Americas https://github.com/sequelize/sequelize/issues/2831

**Comment by Americas** [comment]
@mickhansen so it is an old issue :laughing: I was just trying to explain to @OscarGodson that the models were correctly defined, and that the problem was in the SQL generated

**Comment by agalazis** [comment]
Had similar issue. The cause ended up being referring to the association  by field name in stead by property name (the field was snake case and the actual column name camel-case ). I ended up using @OscarGodson 's  snippet and while logging on the hook I figured that the set id was the snake cased one then I fixed the association foreign key names and it all worked without the hook xD

**Comment by tamil-03** [comment]
I too faced the same errors,
Thanks for the Solution

**Comment by s1nistr4** [comment]
Wish it could give an actual error on the sql than just saying "Foreign key constraint failed" and nothing to work with
