### ISSUE TITLE
Raw query with named substitution parameters gets quoted parameters

### ISSUE THREAD

**Issue by czardoz** [sequelize/sequelize#4494]
I'm using sequelize to perform a simple raw query:

```
    var queryStr = 'SELECT * FROM :tableName WHERE :deletionColumn > 0 LIMIT :limit;';

    return self.connection.query(queryStr, {
        replacements: {
            tableName: self.name,
            deletionColumn: self.options.deletionColumn,
            limit: self.options.limit
        }
    }).then(function (rowsToDelete) {
        _.each(rowsToDelete, function (row) {
            log.debug('Preparing to delete row: ', row);
        });
    });

```

The resulting query however, is (from the sequelize logs): 

```
Executing (default): SELECT * FROM 'test' WHERE 'deleted' > 0 LIMIT 421;
```

The generated query is invalid (table name must not be quoted).

Are there any options I can pass that'll disable the quoting? 
I'm using MySQL 5.6 here.

**Comment by janmeier** [comment]
This is not possible currently

First we'd need to come up with a syntax for this - any suggestions @czardoz ?

**Comment by czardoz** [comment]
Coming up with new syntax might not be necessary. 

Something like this should work too:
```
     replacements: {
            tableName: {value: self.name, quote: false}
        }
```

**Comment by janmeier** [comment]
Yeah, that coudl work as well :)

PR welcome

**Comment by mickhansen** [comment]
Hmm, but the value of `tableName` could be a JSON object that needs to be inserted as JSON.
We probably want to use `$` prefixed keys.

**Comment by mickhansen** [comment]
This change would also not make a lot of room for introducing proper prepared queries later, perhaps a different identifier than `:` for tables/identifiers? Not sure what other libraries do for this type of stuff? Some research might be warranted.

**Comment by janmeier** [comment]
I do remember we previously had support for using `??` as unescaped with unnamed replacement - but that won't work since `::` has a different meaning in postgres

**Comment by czardoz** [comment]
This is a pretty uncommon use case (I think), and I am not sure if this needs to be implemented at all. I've currently worked around this using Mustache, and it works just fine. The documentation should definitely be updated to point this out though.

**Comment by subjectix** [comment]
guys come on, don't we already have a familiar syntax for this: `sequelize.col('deleted')` :grin:

**Comment by janmeier** [comment]
@subjectix Quoting columns is not the issue - its _not_ quoting everything else

**Comment by subjectix** [comment]
From what I get, we need some way to escape from quoting. I wasn't explicitly referring to `col` I was referring to the pattern. we can add a feature like: `sequelize.unquote('tableOrColumnOrFunction')`  that we can use like:
```js
replacements: {
    tableName: sequelize.unquote('tableName')
}
```
The unquote function will return an instance of a function we can check with `instanceof` and not quote the result if it's `string` only sanitize it.

**Comment by janmeier** [comment]
@subjectix Actually we already have `sequelize.literal` which might be usefull here - we'd just need to implement support for that in the format method then

**Comment by subjectix** [comment]
Good idea! I didn't know that :grin:

**Comment by eraye1** [comment]
Is there a solution to this?

**Comment by mickhansen** [comment]
@eraye1 Mostly just not using table as a replacement. If you have a dynamic table you can use our private quoteTable manually.

**Comment by avbentem** [comment]
I know this is closed, but JUST for future reference: https://github.com/vitaly-t/pg-promise uses suffixes to denote the usage. Like:

    select ${columns:name} from ${table:name} where id = ${id} order by ${orderBy:name}

...which for pg-promise is the same as:

    select ${columns~} from ${table~} where id = ${id} order by ${orderBy~}

**Comment by corybill** [comment]
Yeah.. this is a super old thread, but NOT having this actually eliminates me from being able to use this node module. This is a feature available in basically every other module out there and they mostly all use the same syntax too.

? - params
?? - table / column names

This is a missing feature!

**Comment by rajangdavis** [comment]
Ran into some issues with this for running an query that uses ILIKE.

The way I got around this is to use string interpolation and using the interpolated string for replacement.

It doesn't solve the above issues, but it may be possible to just replace the entire query (I haven't tried).

Here is an example:
```
beersWithReviews: async (beerName) =>{
	try{
		let namesQuery =`
		SELECT beers.id, 
		beers.name || '(' || breweries.name || ')' as name 
		FROM beers, breweries 
		WHERE beers.name ILIKE :name_query 
		AND beers.brewery_id = breweries.id 
		AND beers.review_text_json IS NOT NULL
		LIMIT 4;
		`
		return await sequelize.query(
			namesQuery,
			{ replacements: { 
				name_query: `%${beerName}%`
			}, type: sequelize.QueryTypes.SELECT });
	}catch(err){
		return err;
	}
}
```

**Comment by eclewlow** [comment]
https://nodejs.org/api/util.html#util_util_format_format_args
util.format FTW !

**Comment by eclewlow** [comment]
Or you can lie to yourself, and pretend you're not using template literals.

```node
const dynamic_column = yes ? 'yes' : 'no'
const format = a => a
format(`select ${dynamic_column} from table`, { dynamic_column: yes ? 'yes' : 'no' })
```

**Comment by LeartS** [comment]
I wouldn't do that. Most developers would rightly assume that a function named `sql.format` escapes it's arguments to avoid SQL injection. Template literals and `util.format` obviously don't do that. If you pretend template literals/util.format are a function provided by a sql package; you may give the illusion of security where there is none.

I would use the template literals syntax so that it's clear that the line is possible source of SQL injection and therefore the variables passed must be checked carefully beforehand.

**Comment by eclewlow** [comment]
For reference, here is the line where single quotes are added.
https://github.com/sequelize/sequelize/blob/c15d9a5f68c8e4b6e17a38ec21c0e16decf0e23f/lib/sql-string.js#L91

### Proposition

Separate replacements into 2 categories:  *Literals* and *Identifiers*

#### Example
```javascript
query('SELECT *
  FROM :location 
  WHERE name=:name
  AND age=:age',
  {
    literals: {
      name: 'charlie',
      age: 12},
    identifiers: {
      location: 'chocolate_factory'
    }
  }
)
```

**Comment by robin-dunn** [comment]
Would also like to see this feature implemented.

**Comment by repodevs** [comment]
Is there anyone working on this issue?

**Comment by aayushksolves** [comment]
Any update on this issue, as I also need something like this with sequelize, having dynamic table names from the input.

**Comment by aayushmall** [comment]
Any update on this issue, as I also need something like this with sequelize, having dynamic table names from the input.

**Comment by guhkun13** [comment]
i think i found it. 
You can combine between backquote string and double string. 

the problem arise when you replace table name, so my solution is how to make it not replaced. 

Example : 
table_name = 'users'

db.default.query(
`SELECT name
        ` FROM ${table_name} ` +
        " WHERE age= :age"
      {
        replacements: {
          age: 24,
        },
        type: QueryTypes.SELECT,
      }
)

noted that i use backquote `` until FROM table_name part, and the rest i used doubel quote like usual.

**Comment by czardoz** [comment]
Please don't do that, it leaves your code vulnerable to SQL injection.
Avoiding string formatting was the whole point of this feature request.

**Comment by guhkun13** [comment]
then, any safe solution ?

**Comment by meSmashsta** [comment]
Guys, it's 2021, where are we with this? :'(

**Comment by meSmashsta** [comment]
For those wandering souls just like me, I manually escaped them like so :'(

```javascript
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize('postgres://postgres:postgres@localhost:5432/test_db');

const escapedOrderByColumn = sequelize.escape('username');
const escapedDirection = sequelize.escape('DESC');
sequelize.query(`SELECT * FROM players ORDER BY ${escapedOrderByColumn} ${escapedDirection}`);
```

**Comment by guhkun13** [comment]
for the steps, i prefer to separate the process of validation and actions (controller). 
1. using middleware to validate input (im using express-validator); columnName, orderDirection, etc.
    by doing that, controller only accept 'validated data'  
2. then in controller, u can query it in ORM way. in my experience, it's a bit faster than using raw query (cmiiw)

**Comment by AZS-99** [comment]
Almost 7 years and still nothing .... Any update on this apart from the cricket in the background?

**Comment by rscottlundgren** [comment]
@czardoz - Is this issue still "up for grabs"? It's been open for awhile and it would be cool for me to have my first issue be something that's both older and seemingly impactful. Please let me know!

**Comment by ephys** [comment]
Feature https://github.com/sequelize/sequelize/issues/14299 should be able to cover the use cases discussed in this issue:

```ts
sequelize.query(sql`SELECT * FROM ${col(tableName)} WHERE ${col(deletionColumn)} > 0 LIMIT :limit;`, {
  replacements: { limit },
})
```
