### ISSUE TITLE
query result: options object of include has all properties undefined

### ISSUE THREAD

**Issue by cruiser12** [sequelize/sequelize#4496]
When i do
```javascript
User
            .findOne(
                {
                    where :
                    {
                        id : req.params.id
                    },
                    include: [{ all: true,nested:true}]
                }
            )
            .then(function(user){
```

The result also has the options property, so with ```user.options.attributes``` i have access to all the attributes. But for the includes all option properties are undefined. e.g. ``` user.devices[0].options.attributes``` is ```undefined```. But i would also like to read all the attributes of the includes.

**Comment by janmeier** [comment]
Options (now called `$options`) is not part of the public API - So this is a won't-fix, since we can't promise to keep it consistent
