### ISSUE TITLE
GMT Utils deprecated Non-object references property found

### ISSUE THREAD

**Issue by brunoslalmeida** [sequelize/sequelize#4499]
Every time I sync my db from sequelize code I receive this message:

GMT Utils deprecated Non-object references property found. Support for that will be removed in version 4. Expected { references: { model: "value", key: "key" } } instead of { references: "value", referencesKey: "key" }. at node_modules/sequelize/lib/model.js:82:25

If you guys need more info I am available

**Comment by brunoslalmeida** [comment]
using "sequelize": "^3.7.x" with mysql

**Comment by janmeier** [comment]
Somewhere you have `{ references: "value", referencesKey: "key" }`, where it should be `{ references: { model: "value", key: "key" } }`

**Comment by brunoslalmeida** [comment]
My bad.. i was really doing something wrong. ...
