### ISSUE TITLE
When using 2 unique validations the custom message is being overwritten

### ISSUE THREAD

**Issue by corbanb** [sequelize/sequelize#4505]
Hi all,

Working on a new model an noticed that is you want to add 2 values to be unique and want both to have custom validation messages the first messages always overwrites the 2nd one.

Ex:
```javascript
slug: {
        unique: {
          args: true,
          msg: 'URL is already used by another collection.'
        },
        type: DataTypes.STRING,
        validate: {
          is: /^[a-z0-9]+(?:-[a-z0-9]+)*$/
        }
      },

      username: {
        unique: {
          args: true,
          msg: 'Username must be unique.'
        },
        type: DataTypes.STRING,
        validate: { max: 90 }
      },
```

This example gives the right response for slug validation but if username fails on unique I get back the msg from the slug.

```javascript
slug: {
        unique: {
          args: true,
          msg: 'URL is already used by another collection.'
        },
        type: DataTypes.STRING,
        validate: {
          is: /^[a-z0-9]+(?:-[a-z0-9]+)*$/
        }
      },

      username: {
        unique: true,
        type: DataTypes.STRING,
        validate: { max: 90 }
      },
```
In this example I get back the system username validation message.

Am I doing this wrong for the custom msg? Or is this a bug?

**Comment by janmeier** [comment]
Hmm, for me this tries to generate `UNIQUE ("slug", "username")` which is a whole other kind of wrong :D

However, adding `name` to both `unique`'s fixes that problem.

I tested with two conflicting usernames, and I get the correct error - same for slug. Could you please try on the latest version? If the problem persists, please open a pull request with a failing test
