### ISSUE TITLE
Support setting defaultValue to deletedAt via paranoid option

### ISSUE THREAD

**Issue by kenjitayama** [sequelize/sequelize#4510]
Now that `defaultValue` of `deletedAt` is used in paranoid clauses and restores (#4481) , it would be convenient to have a syntax like this.

```
var User = sequelize..define('user', {
  username: DataTypes.STRING,
}, {
  paranoid: {
    defaultValue: new Date(0)
  }
});
```

Otherwise, if you need a default value other than `NULL`, you would need to explicitly define the `deletedAt` column while `paranoid` is implicitly defining it at the same time.

I looked at the constructor of `Model` but couldn't find where `paranoid` option was creating `deletedAt`.

I think explanation about `defaultValue` of `deletedAt` should be added to the docs, but maybe it should be after this is implemented.

**Comment by kenjitayama** [comment]
Second thought...
If overriding implicitly defined columns is an usual thing, this syntax might not be necessary.
Afterall, I think you would usually set a `defaultValue` to `deletedAt` when you need to set a composite unique key to `deletedAt`.

**Comment by mickhansen** [comment]
I actually prefer the more explicit way of defining the deletedAt column together with paranoid.

**Comment by kenjitayama** [comment]
I now think so too. Maybe this issue can be closed?

**Comment by mickhansen** [comment]
Fine by me :)

**Comment by sainttail** [comment]
Is this implement in current sequelize.js or not? want to know the status. In my case I want to added composite unique for field in every table with the `deletedAt`. 

In my use case, the best one would be define deletedAt at the global options and specify `deletedAt` with some unique key string. 

In every model, I have to name the unique attribute to match that I define for `deletedAt` in global options

**Comment by mickhansen** [comment]
@sainttail What are you asking specifically? If you follow the linked issues you can see that a PR for using default values for deletedAt has been merged. This doesn't really relate to defining a delatedAt column globally though.
