### ISSUE TITLE
upsert should use defaultValue in ON DUPLICATE KEY clause

### ISSUE THREAD

**Issue by kenjitayama** [sequelize/sequelize#4512]
The following test fails at the last expect.

```
it('should use defaultValue in ON DUPLICATE KEY clause', function() {
  var Shop = this.sequelize.define('shop', {
    name: {
      type: DataTypes.STRING,
      unique: true
    },
    status: {
      type: Sequelize.ENUM(
        'open',
        'closed'
      ),
      defaultValue: 'open'
    }
  });

  return this.sequelize.sync({force: true}).then(function () {
    return Shop.upsert({name: 'shop1'}).then(function() {
      return Shop.findOne({where: {name: 'shop1'}});
    }).then(function(shop) {
      expect(shop.status).to.equal('open');
      shop.status = 'closed';
      return shop.save();
    }).then(function(shop) {
      expect(shop.status).to.equal('closed');
      return Shop.upsert({name: 'shop1'});
    }).then(function() {
      return Shop.findOne({where: {name: 'shop1'}});
    }).then(function(shop) {
      expect(shop.status).to.equal('open');
    });
  });
});
```

```
      AssertionError: expected 'closed' to equal 'open'
      + expected - actual

      -closed
      +open
```

The second upsert generates this SQL.
```
INSERT INTO `shops` (`name`,`status`,`createdAt`,`updatedAt`)
VALUES ('shop1',
        'open',
        '2015-09-15 06:54:39',
        '2015-09-15 06:54:39') ON DUPLICATE KEY
UPDATE `name`=VALUES(`name`), `updatedAt`=VALUES(`updatedAt`);
```
`status` is missing in `ON DUPLICATE KEY`.

**Comment by mickhansen** [comment]
For good reason, what if you're calling UPSERT on something that has a `status` other than the default value, that will then be overwritten?

defaultValue is expected to be used at create time.

**Comment by kenjitayama** [comment]
> For good reason, what if you're calling UPSERT on something that has a status other than the default value, that will then be overwritten? 

Yes, the test above expects to be so.
I had a image of upsert being kind of an idempotent function.
So whether the row exists or not or have been modified, the same upsert call should end up with the same row (except for updatedAt).

> defaultValue is expected to be used at create time.

On the other hand, I understand that it might sound wrong if `defaultValue` is used in `ON DUPLICATE KEY UPDATE`.

I feel upsert should be kind of idempotent, but not really confident about it.
I haven't experience of upsert in other ORMs, so I don't know the convention.

**Comment by mickhansen** [comment]
Well to me default value imples if the value doesn't exist, it does exist in a UPDATE scenario :)
upsert would not be idempotent if it continously applied the default value to a colum and it would introduce a lot of subtle bugs i'd say. Closing this, unlikely to be changed.

**Comment by kenjitayama** [comment]
I see now... :)  Thanks for explaining in detail!
