### ISSUE TITLE
Creating a generic check constraint

### ISSUE THREAD

**Issue by scandox** [sequelize/sequelize#4515]
I want to be able to create a custom check constraint that operates across multiple columns. So, for example, the SQL in postgres would be:

    ALTER TABLE "businessUnits" ADD CONSTRAINT operatorId_cannot_equal_managerId CHECK ("operatorId" <> "managerId");

I'm man enough to admit that having reviewed the docs, historical issues and stackoverflow.com, I haven't figured it out.

I have tried using `validate` for this, however, what I found was that the `this` in my validate function only had access to the fields being updated and not to values that were remaining unchanged. That would have meant loading the model in the validate function and checking against that - which just seemed too much coding given how easy that single line of SQL is.

If I've misunderstood how the `validate` function works, I'd be happy to know more.

**Comment by scandox** [comment]
Slight self-correction: actually I see now that if one calls update on an actual instance then the validate function does have access to all values. I'd still like to know how to create that constraint. In the meantime I have implemented the functionality with `validate`. So close issue if you wish.

**Comment by Americas** [comment]
You can't create a constraint like that through the model.

If you use migrations, run that query through ```migration.sequelize.query()```

**Comment by scandox** [comment]
Ok cool. I guess I'll stick with the validation now...since it does have the benefit of being very explicit.
