### ISSUE TITLE
Can't access data used to create models in hooks

### ISSUE THREAD

**Issue by tolgaek** [sequelize/sequelize#4516]
When using `someModel.create(data)` there might be some additional data in the `data` object.

I want to be able to access those in the `afterCreate` hook so that I can take some actions.

Mainly my use case is I have some data which also includes some child data and when creating, I would like my models to take care of the creation of their children but this 'extra' data seems lost in the hooks

**Comment by mickhansen** [comment]
`data` might very well be filtered in `create` by `set`

**Comment by janmeier** [comment]
I believe the hook is called with an instance, not the original data. Perhaps you could store the values you need in options instead?

**Comment by janmeier** [comment]
Closing, no response
