### ISSUE TITLE
Make Dialect Requiring Static

### ISSUE THREAD

**Issue by subjectix** [sequelize/sequelize#4517]
### The bundling applications fail to include the dialects.

[The Code](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L179):
```js
try {
    var Dialect = require('./dialects/' + this.getDialect());
    this.dialect = new Dialect(this);
  } catch (err) {
    throw new Error('The dialect ' + this.getDialect() + ' is not supported. ('+err+')');
  }
```
This would better be handled with a switch case:
```js
try {
    var Dialect;
    swtich(this.getDialect())
    {
         case '...':
             Dialect = require('./dialects/...'); break; 
         .
         .
         .
    }
    this.dialect = new Dialect(this);
  } ...
```

This isn't so hard to fix, should I make a pull request? or do you guys have time yourselves to fix this? ^^

**Comment by janmeier** [comment]
What bundling applications?

We are swamped right now, so if you want this quick creating a pull request is the way to go

**Comment by subjectix** [comment]
[Browserify](http://browserify.org/) to be precise. 
And no I don't need this fixed quickly. I used the require feature of browserify, but it's a very ugly hack. 
I'll open up a pull request and try to get this fixed as best as I can. 
Thanks for the response. ^^

**Comment by subjectix** [comment]
I opened a pull request, #4530

**Comment by mickhansen** [comment]
@subjectix How are you using Sequelize in the browser environment (just curious)

**Comment by janmeier** [comment]
+1 curiousity

**Comment by subjectix** [comment]
@mickhansen Well browserify doesn't only pack for browser, it also packs for node too. My project runs on devices that fetch their codes remotely.
It is much more efficient to fetch the code bundled and then run it, making deployment a lot easier and network traffic a lot less. Also, since the code runs on single board computers (a bunch of banana pies) it's better for performance too!
I hope that satisfies your curiosity :D

**Comment by mickhansen** [comment]
It does, thank you :) Always interested to know how people utilize Sequelize :)

**Comment by subjectix** [comment]
You are welcome. Sequelize has by far been the best ORM with the best possible API among all the ORM I've worked with (and not just node.js ones). I really love what you guys are doing here :D
