### ISSUE TITLE
'fields' option modifies passed object

### ISSUE THREAD

**Issue by Malgalad** [sequelize/sequelize#4520]
Suppose we have 
```
var obj = {a: 1, b: 2, c: 3}
```
and we want to update some model with it but pick only specific fields, and then we want to update other model with the same object, but with different fields:
```
some_model.update(obj, {fields: ['a', 'b']});

other_model.update(obj, {fields: ['c']}) // Error: column 'c' cannot be null

console.log(obj); // {a: 1, b: 2};
```

What happened? - First update function picked fields `a` and `b`, but instead of working with a clone of `obj`, it modified it.

Is it intended behaviour? The obvious workaround would be to clone `obj` manually before passing it to update function, but I think this is not intuitive.

**Comment by janmeier** [comment]
Yeah, the value object should probably be clone - PR welcome
