### ISSUE TITLE
bulk create should set isNewRecord to false when returning: true

### ISSUE THREAD

**Issue by Aweary** [sequelize/sequelize#4522]
_**note**: variable names changed due to internal code_

I have a list `items` with instances returned from `[Model].bulkCreate(dataObjs, opts)`.

With which I then do something like:

```js
/* myAssocation was set using belongsTo */
  items.forEach((item, idx) => {
    property.setMyAssociation(otherList[idx].id)
      .catch(err => console.log(err));
  });
```

Which logs out the error:

```js

   { [error: null value in column "propertyName" violates not-null constraint]
     name: 'error',
     length: 436,
     severity: 'ERROR',
     code: '23502',
     detail: 'Failing row contains (306, null, null, 0, 0, 0, 0, 0, null, null, f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, f, null, null, null, null, null, null, null, null, null, 2015-09-16 18:20:49.664+00, 2015-09-16 18:20:50.502+00, 606).',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'MyTable',
     column: 'propertyName',
     dataType: undefined,
     constraint: undefined,
     file: 'execMain.c',
     line: '1636',
     routine: 'ExecConstraints',
     sql: 'INSERT INTO "MyTable" ("myAssociationId","updatedAt","createdAt") VALUES (606,\'2015-09-16 18:20:50.502 +00:00\',\'2015-09-16 18:20:49.664 +00:00\');' },
  sql: 'INSERT INTO "MyTable" ("myAssociationId","updatedAt","createdAt") VALUES (606,\'2015-09-16 18:20:50.502 +00:00\',\'2015-09-16 18:20:49.664 +00:00\');' }
```

Which obviously fails because it's trying to use `INSERT INTO` when it should really be updating the existing records, because as the `detail` filed on the error shows, its `null`ing all the other fields which is totally wrong

**Comment by mickhansen** [comment]
Are you using `returning: true` with `bulkCreate`?

**Comment by Aweary** [comment]
Looks like thats set to `true`, yeah

**Comment by mickhansen** [comment]
Likely related to https://github.com/sequelize/sequelize/issues/2907

**Comment by Aweary** [comment]
Looks like `items.forEach(item => item.isNewRecord = false)` did resolve it for me for now, so definitely sounds like it :+1: 

Thanks!

**Comment by janmeier** [comment]
@mickhansen We seem to be getting a fair amount of these issues that can be solved by manually setting `isNewRecord` - bulkCreate should probably do that on its own. One problem might be that this will only work for postgres, and it might be confusing for users if the returned instances look more like 'proper' instances, when in fact  they are not (missing primary key values)

**Comment by mickhansen** [comment]
@janmeier we would only do it if `returning` is set tho.

**Comment by janmeier** [comment]
@mickhansen Yep, that sounds like a good solution. I'm pretty sure we don't have protection against missing pk in `instance.save`, but we definitely should!

**Comment by mickhansen** [comment]
We did in fact already have protection against non-PK updates.
