### ISSUE TITLE
Queries returning only strings.

### ISSUE THREAD

**Issue by lucasmerencia** [sequelize/sequelize#4523]
I using Sequelize 3.8.0 with postgres dialect and the queries are returning every columns as string.

For example, I have a definition like this:
```javascript

var Device = sequelize.define('Device', {
    id: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      autoIncrement: true
    },
    tenantId: {
      type: DataTypes.BIGINT,
      allowNull: false
    },
    token: {
      type: DataTypes.STRING,
      allowNull: false
    }
  }, {
    tableName: 'devices'
  });
```

When I try to find a device by Id all the fields are returned as string, including the Id...

This is my query:

```javascript

Device.findById(id).then( function(result) {
  console.log(result.toJSON());
});
```
The output is this: 
```json

{
  "id": "9",
  "tenantId": "123",
  "token": "sometoken"
}
```

So, my real problem is: If a try to sum the field with other value like `result.toJSON().id + 1` if the id is 9, the result will be `"91"` rather than `10`.

How can I select a device with the types that I defined previously?

**Comment by janmeier** [comment]
Bigints are not guaranteed to fit into js numbers, thus node pg will return them as strings by default

https://github.com/brianc/node-postgres/pull/353

**Comment by lucasmerencia** [comment]
Thanks @janmeier!
