### ISSUE TITLE
Enable .validate(options.skip) to skip specific model/custom validators

### ISSUE THREAD

**Issue by superclarkk** [sequelize/sequelize#4527]
This is a feature request.

It's already possible to skip field validations when calling [.validate([options])](http://sequelize.readthedocs.org/en/latest/api/instance/index.html?highlight=skip#validateoptions-promiseerrorsvalidationerrorundefined), by specifying an array of field names in the `options.skip` property.

It would be very useful to be able to skip model/custom validators too, by specifying their names/paths in the same list.

**Comment by ikraloz** [comment]
I'm not sure if this is the right place to ask for this, but can you provide me with an example to use this feature? I haven't been able to find any documentation refering to this feature.
