### ISSUE TITLE
Sequelize.NOW insert date without milliseconds 

### ISSUE THREAD

**Issue by Hanspagh** [sequelize/sequelize#4539]
When using Sequelize.NOW I get timestamps without milliseconds, is there any way to get the milliseconds like in createAt and updatedAt 

![udklip](https://cloud.githubusercontent.com/assets/1024416/9962060/2f374162-5e24-11e5-860d-ce746b5ff65f.PNG)

**Comment by mickhansen** [comment]
That's odd, Sequelize.NOW is just `new Date()` which definitely supports miliseconds.
What type is set for the field?

**Comment by Hanspagh** [comment]
This is my definition:
`lastChangedAt: {type: DataTypes.DATE, defaultValue: DataTypes.NOW}`
and the field supports milliseconds when I update it with times from moment

**Comment by mickhansen** [comment]
Odd, can you show the SQL for the INSERT query?

**Comment by Hanspagh** [comment]
Here you go: 
`Executing (768c49bf-7806-435a-b476-eaea3ad97205): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "RealEstateRatings", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_9bfb9dc31cdd45fcaafe16e534760bb9$ BEGIN INSERT INTO "RealEstateRatings" ("userId","realEstateId","rating","lastChangedAt","updatedAt","createdAt") VALUES (0,'9',4,'2015-09-18 16:53:03.000 +00:00','2015-09-18 16:53:03.078 +00:00','2015-09-18 16:53:03.078 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_9bfb9dc31cdd45fcaafe16e534760bb9$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
Executing (768c49bf-7806-435a-b476-eaea3ad97205): COMMIT;`

**Comment by Hanspagh** [comment]
I tried with just a create query, same problem, here is it working when doing updates:
`Executing (default): UPDATE "RealEstateRatings" SET "lastChangedAt"='2047-05-27 14:43:53.616 +00:00',"updatedAt"='2015-09-18 16:59:25.913 +00:00' WHERE "userId" = 0 AND "realEstateId" = '10'`

**Comment by mickhansen** [comment]
Does it work with a `create` rather than a `findOrCreate`?

**Comment by Hanspagh** [comment]
No I still get the timestamp like this 2015-09-18 16:59:25.000 +00:00

**Comment by Hanspagh** [comment]
Could this be the course of it:
https://github.com/sequelize/sequelize/blob/f678009d7514b81a6f87e12b86360e9a597e3ca8/lib/utils.js#L323
Since I am using the postgresql

**Comment by mickhansen** [comment]
That is likely it, that's very odd though, possible because it has to work for other types of columns, TIMESTAMPTZ definitely supports miliseconds though.

**Comment by Hanspagh** [comment]
I guess so, would be possible to make an extention, so milliseconds was ensured, since they they work for createdAt and updatedAt

**Comment by mickhansen** [comment]
`createdAt` and `updatedAt` actually don't use `NOW`, they have some special code in `save`

**Comment by Hanspagh** [comment]
I guess I can work around it for now using null, but it should properly be stated somewhere that NOW doesn't use milliseconds, since I spent some time debugging the error.
