### ISSUE TITLE
beforeFind hook not called when model is included

### ISSUE THREAD

**Issue by MakuraYami** [sequelize/sequelize#4546]
When doing
```
Model.findOne({ include: [ ModelWithBeforeFindHook ] }).then(result => {
  ...
});
```
The **beforeFind** hook is not called, and there is no other hook to use in this scenario.

In my **beforeFind** hook I add a few includes that I want to always load with this model, so I'm trying to have this happen also when the model is included.

I'm expecting **beforeFind** to be called, if this is not desired then I think a new hook should be added to solve this.

Discuss :)

**Comment by mickhansen** [comment]
What would you call the beforeFind hook with? The include options?
I've often needed an afterFind hook for inclues though, which should be doable.

**Comment by MakuraYami** [comment]
Internally I assume you will use a find or findAll when a model is included, no?

I don't think I should call the hook myself, but sequelize should be calling a hook automatically when I include the model.

And my goal is to make the model include more associations, so afterFind is not an option, though while you're at it that could be added aswell.

Here is a code snippet of what I'm trying to achieve

```javascript
let Model = sequelize.define('Model', {
  // ...
});

let IncludedModel = sequelize.define('IncludedModel', {
  // ...
}, {
  hooks: {
    beforeFind(args){
      // I wish to edit args for the included model, example:
      args.include = [ SubModel ];
    }
  }
});

IncludedModel.findOne().then(result => {
  // This works fine, beforeFind is called
  console.log( result.SubModel );
});

Model.hasOne(IncludedModel);

Model.findOne({ include: [ IncludedModel ] }).then(result => {
  // This doesn't work because beforeFind isn't called
  console.log( result.IncludedModel.SubModel );
});
```

So I suggest either having beforeFind called when you  include, or having a new hook to handle this.

**Comment by mickhansen** [comment]
No, includes use joins unless you use `separate: true`.
The options on `include` are `where`, `attributes`, `include` and others, they almost, but don't totally match the options available on a find call (so there's a subtle difference that could break for existing hooks).

**Comment by mickhansen** [comment]
`beforeFind` is also intended for possible cache use in the future, so calling it with include options would not work for that case.

**Comment by MakuraYami** [comment]
Alright that makes sense.
Do you see any way to make this code snippet work as I intended or is that just too much to ask for?
I suppose you can just have a class method returning the include array and add it when including the model as

```
Model.findOne({ include: [ {model: IncludedModel, include: IncludedModel.getIncludes() } ] })
```
I would think it should be possible to have this use a hook but for now this will do, hope you can find a 
think it should be possible to have this use a hook but for now this will do, hope you can find a way to support this in the future :)

**Comment by mickhansen** [comment]
@MakuraYami Adding a defaultScope to the model that always needs to include a submodel might work better as a workaround.

**Comment by MakuraYami** [comment]
@mickhansen You are absolutely right! I missed totally missed that, thank you.

**Comment by diosney** [comment]
Right now what I'm doing is defining two `hasMany` associations in a common model manually defined by me (ex: ABMemberships) instead of the `belongsToMany`. That, with `separate` in mind for the `hasMany` did the trick.

**Comment by diosney** [comment]
Ohh! Forgot, in my use case I need to trigger the `afterFind` hook in the included model.
