### ISSUE TITLE
belongsTo includes not working while in express?

### ISSUE THREAD

**Issue by mpermar** [sequelize/sequelize#4547]
Hi. First of all, amazing library and amazing docs. Really well done. Congratulations. 

Now, I got stuck trying to do some eager loading and I'm wondering if this could be related to the way the library works in express as the associations are done slightly different. I've got a simple one to many association from Photo to Album. The association does work and if I print the photo object for example I can see the AlbumId property there with the expected value. However, when I try now to eagerly fetch the Album data, I can't as it fails with an error like this:

```
Album is not defined ReferenceError: Album is not defined at router.get.id (/Users/martin/workspace/express-test/app/controllers/photos.js:51:14) at Layer.handle [as handle_request] (/Users/martin/workspace/express-test/node_modules/express/lib/router/layer.js:95:5) at 
...
```

My relationship is very simple as I said:

```
	var Photo = sequelize.define('Photo', 
		{
			description: DataTypes.STRING,
			addDatetime: DataTypes.INTEGER,
			hash: DataTypes.STRING,
			dimension: DataTypes.STRING,
			instagram: DataTypes.INTEGER,
			stars: DataTypes.INTEGER
		},
...

	var Album = sequelize.define('Album', 
		{
			name: DataTypes.STRING,
			createDatetime: DataTypes.INTEGER,
			description: DataTypes.STRING,
		},
		{
    		classMethods: {
      			associate: function(models) {
        			Album.hasMany(models.Photo, {
					  foreignKey: {
					    name: 'albumId'
					  }
					});
      			}
    		}
  		},	
```

And so is the query I'm running:

```
router.get('/:photoId', function (req, res, next) {
  var id = req.params.photoId;
  db.Photo.find({where: {id: id}, include: [ Album ]}).then(function(photo){
    console.log("Found " + util.inspect(photo));
```

It's probably something obvious but I can't spot what's wrong. Any ideas?

**Comment by mpermar** [comment]
Hrm, I see, there must be something fundamentally wrong in the way I'm using sequelize as when I use the code above, the table name part from the Album object is ignored and an Albums table is created instead. If I remove the associate objet then the expected ow_photo_album table is created instead. So probably the way I'm using associations is somehow wrong.

**Comment by janmeier** [comment]
The album variable is not defined - that's a jacasxrip

**Comment by mpermar** [comment]
Yeah, I thought the tablename was irrelevant but then found that it was actually being ignored as stated in the comment above. I imagine the root for all my trouble has something to do with that.

**Comment by janmeier** [comment]
@mpermar There is no tablename mentioned in your code above, so I can't really help you on that issue :D

As for `Album is not defined ReferenceError` - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError. You probably need `db.Album`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by mpermar** [comment]
Fair enough. somehow github editor is showing me the updated code with the table name but let me open a different ticket anyways.
