### ISSUE TITLE
aggregate query returns SUM as strings instead of integers

### ISSUE THREAD

**Issue by DemarsM** [sequelize/sequelize#4550]
I dont know if it is normal, or if there is something I am doing wrong, but the sums returned by my query below are in strings even if the datatype of nbrEleves field is integer. Why? The query is run against a postgres database.

    Point.aggregate('nbrEleves', 'SUM', {plain: false, where: {codecs: codecs}, order: '"codeSecteur" ASC', group:["codeSecteur", "codeWork"], attributes:['codeSecteur', 'codeWork']})

**Comment by janmeier** [comment]
Please show your model definition. Do you have a type defined for the field? In that case it should use that https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1508. Otherwise it should default to float

**Comment by DemarsM** [comment]
This is my model definition:

    var Point = sequelize.define('points', {
        codecs: Sequelize.STRING,
        codeSecteur: Sequelize.STRING,
        codeWork: Sequelize.STRING,
        nbrEleves: Sequelize.INTEGER,
        codePostal: Sequelize.STRING,
        coordinates : Sequelize.STRING
    });

This is a sample of the result I get when printed to the console:

    [ { codeSecteur: 'A', codeWork: 'Z', SUM: '177' },
      { codeSecteur: 'B', codeWork: 'K', SUM: '77' },
      { codeSecteur: 'B', codeWork: 'Z', SUM: '102' } ]

**Comment by sheepcount** [comment]
+1, just noticed the same issue. Sample project here: https://gist.github.com/sheepcount/88916f98380e10dcb129

**Comment by mickhansen** [comment]
Using postgres? Aggregates from postgres are returned as int8 which the node-postgres library does not convert in fear of data loss.

**Comment by sheepcount** [comment]
In my case, yes. Thanks for the explanation.

**Comment by DemarsM** [comment]
That's my case too. Thank you @mickhansen

**Comment by milovanderlinden** [comment]
I ran into the same problem with count. I solved it by parsing the count result in the model
```
      instanceMethods: {
        toJSON: function () {
          var data = this.get();
          for (var x in data) {
            if (x === 'mysumresult'){
              data[x] = parseInt(data[x]);
            }
          }
          return data;
        }
      }
```

**Comment by ms88privat** [comment]
@janmeier is it possible to specify `pg.defaults.parseInt8` in sequelize? (you can find it here https://github.com/brianc/node-postgres/wiki/pg)

**Comment by janmeier** [comment]
@ms88privat no, but you can just require pg and set it yourself before instantiating sequelize

**Comment by ms88privat** [comment]
@janmeier Thank you. I tried it like this but it did not work (my `instance.update({bigint: value})` and my `raw queries` are still returning strings):

``` javascript
var pg = require('pg');
pg.defaults.parseInt8 = true;

var Sequelize = require('sequelize');
sequelize = new Sequelize ...
``` 

Any Ideas?

**Comment by janmeier** [comment]
@ms88privat Hmm weird - seems to work fine for me. Are you using pg-native?

**Comment by bvandenbon** [comment]
Still having the same issue on sequelize version "5.22.4"
