### ISSUE TITLE
Eagerly loaded association with SUM produces incorrect SQL when combined with LIMIT 

### ISSUE THREAD

**Issue by sheepcount** [sequelize/sequelize#4551]
I have a very simple model: accounts, which have many transactions with positive and negative amounts (Gist with full model etc: https://gist.github.com/sheepcount/88916f98380e10dcb129).

I use the following query to get a list of accounts and their current balance:

```
db.Account.findAll({
    attributes: ['name', [db.sequelize.fn('SUM', db.sequelize.col('Transactions.amount')), 'balance']],
    order: [['name', 'ASC']],
    include: [{
        model: db.Transaction,
        attributes: []
    }],
    group: [db.sequelize.col('Account.id')]
});
```

It works great and results in the following SQL:

```
SELECT "Account"."id", "Account"."name", SUM("Transactions"."amount") AS "balance" FROM "Accounts" AS "Account" LEFT OUTER JOIN "Transactions" AS "Transactions" ON "Account"."id" = "Transactions"."AccountId" GROUP BY "Account"."id" ORDER BY "Account"."name" ASC;
```

However, when I try to limit the list of accounts, the resulting SQL is broken:

```
db.Account.findAll({
    attributes: ['name', [db.sequelize.fn('SUM', db.sequelize.col('Transactions.amount')), 'balance']],
    order: [['name', 'ASC']],
    limit: 2,
    include: [{
        model: db.Transaction,
        attributes: []
    }],
    group: [db.sequelize.col('Account.id')]
});

 SELECT "Account".* FROM (SELECT "Account"."id", "Account"."name", SUM("Transactions"."amount") AS "balance" FROM "Accounts" AS "Account" GROUP BY "Account"."id" ORDER BY "Account"."name" ASC LIMIT 2) AS "Account" LEFT OUTER JOIN "Transactions" AS "Transactions" ON "Account"."id" = "Transactions"."AccountId" ORDER BY "Account"."name" ASC;
```

This obviously causes a "missing FROM-clause entry for table Transactions" error in PostgreSQL, as the inner SELECT has no clue where to get Transactions.amount from.

**Comment by mickhansen** [comment]
Sequelize does a subquery because it expects a cartesian product.
We probably need a case that disables the `duplicating` setting for an include if it has `attributes: []`.

As a work around try adding `duplicating: false` to your Transaction include.

**Comment by sheepcount** [comment]
Worked like a charm, thanks!
