### ISSUE TITLE
hasMany relation, does not admit model instance.

### ISSUE THREAD

**Issue by exos** [sequelize/sequelize#4555]
Hi I'm using sequelize with two models; Users and ApiKeys.

My problem is when I try to add a _ApiKey_ to _User_, I've an error if I set or add an instance of model, but if I set the ID works:

My code:

models/auth/apikeys.js

    module.exports = function (sequelize, DataTypes) {
    
        var ApiKey = sequelize.define('Auth_ApiKeys', {
            // ...
        });
    
        return ApiKey;
    
    };

models/users.js

    var apiKeysFactory = require('./auth/apikeys');
    
    module.exports = function (sequelize, DataTypes) {
    
        var ApiKeysModel = apiKeysFactory(sequelize, DataTypes);
    
        var UserModel = sequelize.define('Users', {
            // ...
        });
    
        UserModel.hasMany(ApiKeysModel, {
            as: 'ApiKeys'
        });
    
        return UserModel;
    
    };

In my tests:

    var assert      = require('assert'),
        models      = require('../lib/models');
    
    describe("Api Keys", function () {
    
        var user = null;
    
        before(function (done) {
     
            // Sync
            models.sequelize.sync({
                force: false 
            }).then(function () {
    
                // Create test user 
                models.users.create({
                    username: 'testForApi',
                    password: 'apipaiaip'
                }).then(function (suser) {
    
                    suser.save().then(function () {
                        user = suser;
                        done();
                    }).catch(done);
    
                }).catch(done);
    
            }).catch(done);
        
        });
    
        it("Create API key", function (done) {
           
            models.auth.apikeys.create()
                .then(function (apiKey) {
    
                    apiKey.save().then(function () {
                        user.addApiKey(apiKey)
                            .then(function () {
                                done();
                            })
                            .catch(done);
                    }).catch(done);
    
                })
                .catch(done);
        });
    
    });

This throws:

     1) Api Keys Create API key:
         SequelizeDatabaseError: SQLITE_ERROR: near ",": syntax error
          at Query.formatError (node_modules/sequelize/lib/dialects/sqlite/query.js:243:14)
          at node_modules/sequelize/lib/dialects/sqlite/query.js:48:29
          at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

Logging the queries, I see it:

    UPDATE `Auth_ApiKeys` SET `UserId`=1,`updatedAt`='2015-09-22 05:50:29.069 +00:00' WHERE `id` IN (`dataValues` = '[object Object]', `_previousDataValues` = '[object Object]', `_changed` = '[object Object]', `$modelOptions` = '[object Object]', `$options` = '[object Object]', `hasPrimaryKeys` = true, `__eagerlyLoadedAssociations` = , `isNewRecord` = false, `_customGetters` = '[object Object]', `_customSetters` = '[object Object]', `validators` = '[object Object]', `rawAttributes` = '[object Object]', `attributes` = 'id', 'key', 'createdAt', 'updatedAt', `_hasCustomGetters` = 0, `_hasCustomSetters` = 1, `Model` = '[object SequelizeModel:Auth_ApiKeys]', `$Model` = '[object SequelizeModel:Auth_ApiKeys]')

I understand it's sending an object (stringified) on the _id in_, if I use

                        user.addApiKey(apiKey.id)

(Added the id property), this works.

**Comment by janmeier** [comment]
Hmm, the code you posted seems to work fine for me - which version are you on. If you still experience this on latest master, plese open a PR with a failing test case

Also, the test case you posted is unnessesarily wordy. This is equivalent:
```js
it("Create API key", function () {
  return models.auth.apikeys.create().then(function (apiKey) {
      return user.addApiKey(apiKey);
  });
});
```

There is no need to call `save` - create has already saved the model.
There is no need to take a done callback, you can just keep returning promises, mocha will await them, and fail the test if one of them is rejected. And even if it didn't handle rejections, you would only need a single `catch` at the end of the chain, since errors bubble up when you return promises.

**Comment by exos** [comment]
Yes, the unnessesary saves calls threr are for testing (now I don't use that), about the version:

```
├─┬ sequelize@3.9.0
│ ├── bluebird@2.9.34
│ ├── dottie@0.3.1
│ ├── generic-pool@2.2.0
│ ├── inflection@1.7.1
│ ├── moment@2.10.6
│ ├── moment-timezone@0.4.0
│ ├── node-uuid@1.4.3
│ ├── semver@5.0.3
│ ├── shimmer@1.0.0
│ ├── toposort-class@1.0.1
│ ├── validator@4.0.6
│ ├─┬ wellknown@0.3.4
│ │ └─┬ concat-stream@1.5.0
│ │   └── typedarray@0.0.6
│ └── wkx@0.1.0
├── sequelize-import@1.2.1
├─┬ sqlite3@3.1.0
│ ├── nan@2.0.9
│ └─┬ node-pre-gyp@0.6.10
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├─┬ nopt@3.0.3
│   │ └── abbrev@1.0.7
│   ├─┬ npmlog@1.2.1
│   │ ├── ansi@0.3.0
│   │ ├─┬ are-we-there-yet@1.0.4
│   │ │ ├── delegates@0.1.0
│   │ │ └─┬ readable-stream@1.1.13
│   │ │   ├── core-util-is@1.0.1
│   │ │   ├── inherits@2.0.1
│   │ │   ├── isarray@0.0.1
│   │ │   └── string_decoder@0.10.31
│   │ └─┬ gauge@1.2.2
│   │   ├── has-unicode@1.0.0
│   │   ├─┬ lodash.pad@3.1.1
│   │   │ ├── lodash._basetostring@3.0.1
│   │   │ └─┬ lodash._createpadding@3.6.1
│   │   │   └── lodash.repeat@3.0.1
│   │   ├─┬ lodash.padleft@3.1.1
│   │   │ ├── lodash._basetostring@3.0.1
│   │   │ └─┬ lodash._createpadding@3.6.1
│   │   │   └── lodash.repeat@3.0.1
│   │   └─┬ lodash.padright@3.1.1
│   │     ├── lodash._basetostring@3.0.1
│   │     └─┬ lodash._createpadding@3.6.1
│   │       └── lodash.repeat@3.0.1

```

I'm using sequelize-import, maybe the double define of model caouses problem.

PD: Sorry my english.

**Comment by janmeier** [comment]
I've never heard of sequelize-import, so I would'nt know if that causes the problems.

As I said, I can't replicate the problems with what you've given now. If you create a self-contained test-case we can look at this further

**Comment by janmeier** [comment]
Closing, no response
