### ISSUE TITLE
Child objects are created one by one

### ISSUE THREAD

**Issue by RoboBurned** [sequelize/sequelize#4557]
I try to create a parent object together with its children.

```
Person.hasMany(Task);
return Person.create({
        no: '1221212',
        Tasks: [
            { taskName: 'task1' },
            { taskName: 'task2' }
        ]}, {
            include: [ { model: Task  } ]
        });
```

However this generates an INSERT statement for each child object (task) causing performance degradation. Child objects must be created the same way as bulkCreate does.

Also related:
Create with includes #1838

**Comment by mickhansen** [comment]
bulkCreate could only be used for dialects that support returning the primary key for multiple inserts, that would be PG and MSSQL (iirc)

**Comment by cybercoder** [comment]
Is this feature implemented?
I used this method to save with associated models but errors happen.

**Comment by janmeier** [comment]
The issue is still open, so no...

**Comment by janmeier** [comment]
Please create a self-contained test case that shows your error

**Comment by cybercoder** [comment]
This is Order Model:
`'use strict';
module.exports = function(sequelize, DataTypes) {
  var Order = sequelize.define('Order', {
    price: DataTypes.INTEGER,
    address: DataTypes.TEXT,
    payed : DataTypes.BOOLEAN,
    delievered : DataTypes.BOOLEAN
  }, {
    classMethods: {
      associate: function(models) {
        Order.belongsTo(models.Restaurant,{
          'onDelete' : "CASCADE",
          foreignKey : {
            allowNull : false
          }
        });
        Order.belongsTo(models.User,{
              'onDelete' : "CASCADE",
              foreignKey : {
                allowNull : false
              }
            });
        Order.hasMany(models.OrderDetail);
      }
    }
  });
  return Order;
};`

and the OrderDetail model:
`'use strict';
module.exports = function(sequelize, DataTypes) {
  var OrderDetail = sequelize.define('OrderDetail', {
    qty : DataTypes.INTEGER,
    price: DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function(models) {
        OrderDetail.belongsTo(models.Order,{
          'onDelete' : "CASCADE",
          foreignKey : {
            allowNull : false
          }
        });
        OrderDetail.belongsTo(models.Food,{
              foreignKey : {
                allowNull : false
              }
        });
    }
  }});
  return OrderDetail;
};
`
Also the express route to save posted data is : 
`router.post('/order',function(req,res,next){
	models.Order.create(req.body,{include : [models.OrderDetails]}).then(function(order){
		console.log(order) ;
		return true;
	});
	return false;
});`

and the posted data like this:
`{ OrderDetails: [ { OrderId: 1, FoodId: 1, price: 23000, qty: 6 } ],
  address: 'No fffff',
  UserId: 1,
  RestaurantId: 1,
  price: 138000 }`

But this errors occurred: 
`TypeError: Cannot read property '_pseudo' of undefined
    at conformInclude (C:\Users\xxx\Desktop\gfoodAPI\node_modules\sequelize\li                   b\model.js:269:14)`

**Comment by cybercoder** [comment]
Oh it was my fault, I wrote OrderDetails instead OrderDetails, after correction it's inserted well.

**Comment by ashish-dehariya** [comment]
Is this feature implemented?
