### ISSUE TITLE
Cannot set Default to Now using Postgres

### ISSUE THREAD

**Issue by dexwiz** [sequelize/sequelize#4564]
I cannot create a now default

``` javascript
sequelize.define('Foo', {
 // instantiating will automatically set the flag to true if not set
 flag: { type: Sequelize.BOOLEAN, allowNull: false, defaultValue: true},

 // default values for dates => current time
 myDate: { type: Sequelize.DATE, defaultValue: Sequelize.NOW }
});
```

Resulting SQL

``` SQL
Executing (default): CREATE TABLE IF NOT EXISTS "Foos" ("id"   SERIAL , "flag" BOOLEAN NOT NULL DEFAULT true, "myDate" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
```

I have tested string, boolean, and date defaults. I can get Dates to default to new Date(), but not using the Sequelize.NOW enum. 

Node 4.0.0
psql (PostgreSQL) 9.3.9

npm
pg@4.4.2
sequelize@3.9.0

**Comment by apsavin** [comment]
Hi @janmeier!
Are you sure we need a `postgres` label here?
It seems to me that sequelize [can't](https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L254) generate `CREATE TABLE` queries with `DEFAULT` section for `NOW`, `UUIDV1` and `UUIDV2` types.

By the way, can I change it somehow on my side? I understand that it's hard to implement because of different syntax of different DBMS. I just want to make `sync` method work for me, with postgres only.

**Comment by mickhansen** [comment]
@apsavin on your side you should be aple to just put `'NOW()'` instead of `DataTypes.NOW()`

**Comment by apsavin** [comment]
Thanks, @mickhansen!
But what about UUID's?

**Comment by sebastianwahn** [comment]
Problem still exists. Although, there is a workaround:
```
return queryInterface.createTable('Collections', {
    ...
    updatedAt: {
        allowNull: false,
        type: Sequelize.DATE,
        defaultValue: Sequelize.fn('NOW')
    },
    ...
}
```

This will use the MySQL NOW() function. Stuck on this bug for some time now until i figured it out, sadly i found this issue afterwards. Nevertheless, this should work with other native-database functions also (UUID - Sequelize.fn('uuid')).

**Comment by caioflores** [comment]
I was having the same trouble with UUIDV4, my migration is, I solved it using postgres command to generate uuid (uuid_generate_v4) and Sequelize.fn(), maybe helpful:
```
      id: {
        primaryKey: true,
        type: Sequelize.UUID,
        defaultValue: Sequelize.fn('uuid_generate_v4'),
        comment: 'id of the user',
      },
```

**Comment by david-bojnansky** [comment]
Same problem with MSSQL, workaround provided by sebastianwahn works, but instead `fn('NOW')` has to be used `fn('GETDATE')`

**Comment by apsavin** [comment]
Still an issue

**Comment by nedex** [comment]
Using Sequelize.UUIDV4 as defaultValue didn't work with my PostgreSQL 9.6 database, resulting in a null id.
Had to use Sequelize.literal('uuid_generate_v4()') with type already set to Sequelize.UUID.

Current version: 4.37.10

**Comment by sushantdhiman** [comment]
Both `NOW` and `UUIDV4` defaults work, but not all dialects support setting functions as a default value.

**SSCCE**

```js
const User = sequelize.define('user', {
  id: {
    primaryKey: true,
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4
  },
  created: {
    primaryKey: true,
    type: Sequelize.DATE,
    defaultValue: Sequelize.NOW
  }
}, {
  timestamps: false
});

sequelize
  .sync({ force: true })
  .then(() => {
    return User.create({});
  })
  .then(() => {
    return User.findOne();
  })
  .then(user => {
    console.log(user.toJSON());
  });
```

```js
{ id: 'c6336286-2654-4657-9d4f-cd3847c087d7',
  created: 2018-06-18T05:08:54.271Z }
```

If you are only using Sequelize, you do'nt need to care about if defaults are present at schema level, Sequelize will always populate that NOW / UUID default before insertion and properly return them.

For some reason if you need them to present at schema level (a very valid use-case, I agree), then set `defaultValue: Sequelize.fn('uuid_generate_v4')`. Only downside for that case will be https://github.com/sequelize/sequelize/issues/9151

**Comment by nedex** [comment]
Maybe I understood the problem, don't know if it could be defined as a bug.
Basically, I didn't reflect the migration code into the define, so it would only work with the function as a default stored into the schema.
This is the migration code:

```javascript
module.exports = {
  up: (queryInterface, Sequelize) =>
    queryInterface.createTable('Users', {
      id: {
        primaryKey: true,
        type: Sequelize.UUID,
        defaultValue: Sequelize.UUIDV4,
      },
      name: {
        type: Sequelize.TEXT,
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
    }),
  down: (queryInterface, Sequelize) =>
    queryInterface.dropTable('Users'),
};
```

And this was the **broken** define (missing the `id` field):

```javascript
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {});

  User.associate = (models) => {
    // associations can be defined here
  };

  return User;
};
```

I had to fix it like this:

```javascript
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    id: {
      primaryKey: true,
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {});

  User.associate = (models) => {
    // associations can be defined here
  };

  return User;
};
```

So basically the `defaultValue` in the migrations doesn't do anything when the type is `UUID`.

**Comment by JoHens** [comment]
^ what above person said, confused the heck out of me

**Comment by Alexnder** [comment]
The problem still persists. Version: Sequelize CLI [Node: 8.16.0, CLI: 5.5.0, ORM: 4.42.0]
I got to use `defaultValue: Sequelize.fn('NOW')`
Instead of `defaultValue: Sequelize.NOW`

**Comment by GustavoContreiras** [comment]
I can't make it work.
Using Sequelize as adapter for Next Auth and PostgreSQL
```
"dependencies": {
    "@auth/sequelize-adapter": "^1.0.5",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@fontsource/roboto": "^5.0.8",
    "@mui/icons-material": "^5.14.14",
    "@mui/material": "^5.14.14",
    "@mui/x-date-pickers": "^6.16.2",
    "bcrypt": "^5.1.1",
    "date-fns": "^2.30.0",
    "dayjs": "^1.11.10",
    "jsonwebtoken": "^9.0.2",
    "material-react-table": "^2.0.0-beta.15",
    "next": "^13.5.6",
    "next-auth": "^4.24.4",
    "notistack": "^3.0.1",
    "pg": "^8.11.3",
    "pg-hstore": "^2.3.4",
    "react": "^18",
    "react-dom": "^18",
    "sequelize": "^6.33.0",
    "uuid": "^9.0.1",
    "zustand": "^4.4.3"
  },
  "devDependencies": {
    "@iconify/react": "^4.1.1",
    "@types/bcrypt": "^5.0.1",
    "@types/jsonwebtoken": "^9.0.4",
    "@types/node": "^20",
    "@types/pg": "^8.10.7",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/uuid": "^9.0.6",
    "typescript": "^5"
  }
```
