### ISSUE TITLE
references in query-generator.js does not respect schema

### ISSUE THREAD

**Issue by milovanderlinden** [sequelize/sequelize#4567]
I am using migrations and I ran into an issue when referencing a table in a schema other then public for postgresql.

I would like to see an option to pass a schema or pass tablename with a dot notation.

**Comment by milovanderlinden** [comment]
Lin 522 in https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js

**Comment by milovanderlinden** [comment]
By deep diving into the source code I managed to find a solution. The schema can be passed with the model, specified like this:

```javascript
references: {
    model: {
      schema: 'testSchema',
      tableName: 'otherTable'
    },
    key: 'id'
  },
```

**Comment by milovanderlinden** [comment]
This is no issue, just a matter of documentation.

**Comment by futurechan** [comment]
It seems this doesn't work. Do you have a current solution?
