### ISSUE TITLE
.nodeify isn't getting the SequelizeUniqueConstraintError, requires .catch

### ISSUE THREAD

**Issue by coderholic** [sequelize/sequelize#4571]
I have some code that's attempting to set the email address of a user to an email address that's already taken. I'm using normal node style callbacks in my code, so I'm using nodeify:

```
models.User.update({email: 'EMAIL_ALREADY_TAKEN', {where: {id: id}, returning: true}).nodeify (err, [num_updated, users]) ->
    console.log err
```

I expected the callback to get invoked with err set to the SequelizeUniqueConstraintError. The callback never gets invoked though. If I add a .catch block after the .nodify block I see that that does get called with the error. 

```
{ [SequelizeUniqueConstraintError: Validation error]
  name: 'SequelizeUniqueConstraintError',
  message: 'Validation error',
  errors:
   [ { message: 'email must be unique',
       type: 'unique violation',
       path: 'email',
       value: 'EMAIL_ALREADY_TAKEN' } ],
  fields: { email: 'EMAIL_ALREADY_TAKEN' } }
```

Why do I need an additional catch block to get this error? Shouldn't this be handled by nodeify? If not,what's the best way to handle invoking my normal node.js style callback with the error or success result, without resuling to something like the following that will result in the callback getting invoked multiple times in the case of an error withinin the callback itself:

```
models.User.update({email: 'EMAIL_ALREADY_TAKEN', {where: {id: id}, returning: true}).nodeify(callback).catch(callback)
```

**Comment by tsheaff** [comment]
Looks nasty.  May require digging into both Sequelize's implementation (stacktrace at error throw) and nodify's implementation from bluebird...

**Comment by mickhansen** [comment]
If catch works and nodeify doesn't it might be a problem with bluebird.
Our CLS shim https://github.com/sequelize/sequelize/blob/master/lib/promise.js might also be interfering.

**Comment by coderholic** [comment]
@mickhansen any suggestions on how I could narrow it down?

**Comment by mickhansen** [comment]
@coderholic Honestly no idea, seems like a weird one.

**Comment by coderholic** [comment]
I've updated the catch block (that follows nodeify) to log the stack trace, and here it is:

I've updated the catch block (that follows nodeify) to log the stack trace, and here it is:

```
SequelizeUniqueConstraintError: Validation error
  at [object Object].module.exports.Query.formatError (./node_modules/sequelize/lib/dialects/postgres/query.js:391:18)
  at [object Object].<anonymous> (./node_modules/sequelize/lib/dialects/postgres/query.js:106:21)
  at [object Object].emit (events.js:95:17)
  at [object Object].Query.handleError (./node_modules/pg/lib/query.js:99:8)
  at [object Object].<anonymous> (./node_modules/pg/lib/client.js:166:26)
  at [object Object].emit (events.js:95:17)
  at Socket.<anonymous> (./node_modules/pg/lib/connection.js:109:12)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```

Does that help at all?

**Comment by coderholic** [comment]
I found the problem! It wasn't with sequelize or bluebird, but with my callback defintion:

```
nodeify (err, [num_updated, users]) ->
```

That worked fine when there wasn't an error, but then there was en error and no success response I'm essentially doing this:

```
coffee> [num_updated, users] = null
TypeError: Cannot read property '0' of null
```

And that's what triggered the catch. I'm now doing this instead:

```
nodeify (err, res) ->
    if err
        ...

    [num_updated, users] = res
```

**Comment by mickhansen** [comment]
@coderholic Ah that's a tricky one
