### ISSUE TITLE
maxIdleTime not respected by a transaction?

### ISSUE THREAD

**Issue by zaggino** [sequelize/sequelize#4572]
Hi guys, I set up sequelize using `pool: { maxConnections: 1, maxIdleTime: 30},` and then opened a transaction manually using `sequelize.transaction().then(...)`. Due to code error I have never committed that transaction and it basically blocked all communication with the db (postgresql). Shouldn't it be cancelled after 30 seconds?

using version 3.9.0

**Comment by mickhansen** [comment]
`maxIdleTime` in this case actually refers to how long a connection has to be inactive before our pool will close it.

**Comment by zaggino** [comment]
so is there a timer for transactions? so i get at least a warning if a bug like this happens again? it wasn't easy to debug... doesn't posgresql emit an event if transaction times out?

**Comment by mickhansen** [comment]
@zaggino There isn't any app-side timer, generally a query has to be executed to hit a connection timeout actually.

No idea if postgres does that actually (we try to focus on cross-implementation possibilities).

**Comment by janmeier** [comment]
It doesn't seem to be possible to control any form of timeout at the connection level

http://stackoverflow.com/questions/13236160/is-there-a-timeout-for-idle-postgresql-connections
http://stackoverflow.com/questions/12583027/transaction-time-out-workaround-for-postgresql

The SO posts discusses having another process periodically check if there are any transactions which have been running for more than X seconds - I think that would be too complicated to add to sequlize core
