### ISSUE TITLE
Populating a findAll via a foreign key - Please help!

### ISSUE THREAD

**Issue by RSpicer** [sequelize/sequelize#4573]
Hey! So I'm having an issue with pulling data with the use of a foreign key.

Basically, my app is designed around ordering food. Without going through all the relationships in our app (which is here https://github.com/thequeueplate/queueplate if you're interested in that), the main relationship you need to know is that we have MenuItems (or dishes). This is the model for those:

```
module.exports = function(sequelize, DataTypes) {
  var MenuItem = sequelize.define("MenuItem", {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    name: {
      type: DataTypes.STRING(),
      allowNull: false
    },
    description: {
      type: DataTypes.TEXT()
    },
    price: {
      type: DataTypes.DECIMAL(4, 2)
    },
    pictureURL: {
      type: DataTypes.STRING(2083)
    },
    type: {
      type: DataTypes.ENUM,
      values: ['Dine-in', 'Take-out']
    }
  }, {
    classMethods: {
      associate: function(models) {
        MenuItem.belongsTo(models.Restaurant, {
          onDelete: "CASCADE",
          foreignKey: {
            allowNull: false
          }
        });
        MenuItem.hasMany(models.OrderItem);
      }
    }
  }
);
  return MenuItem;
};
```

We also have OrderItems, which need to reference a MenuItem. Basically, one MenuItem needs to be able to be used by multiple OrderItems. Here's the model:

```
module.exports = function(sequelize, DataTypes) {
  var OrderItem = sequelize.define("OrderItem", {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    quantity: {
      type: DataTypes.INTEGER(3)
    },
    comments: {
      type: DataTypes.STRING(200)
    }
  }, {
    classMethods: {
      associate: function(models) {
        OrderItem.belongsTo(models.Order);
      }
    }
  }
);
  return OrderItem;
};
```

The problem I'm having is that, in my database, I see a foreign key on each OrderItem that should correspond to a MenuItem. Thus, I thought I'd be able to do this: 

```
api.get('/item/:itemid', function(req, res) {
		models.OrderItem.findAll({
			where: { id: req.params.itemid },
			include: [ models.MenuItem ]
		}).then(function(orderitem) {
			res.send(orderitem);
		}).catch(function(err){
			res.send({message: 'Could not find Order Item', error: err})
		})
	})
```
To find an OrderItem by its' id, and then populate it with the MenuItem it's refrencing. Unfortunately, doing this results in my catch being fired, telling me that it could not find the order item. Taking out the include line, and leaving just the where, makes it work just fine... without the MenuItem details, obviously.

Thoughts? Any help at all is hugely appreciated - this has been a huge headache, and I'm almost sure this is something that should be possible!

Thanks!!

**Comment by mickhansen** [comment]
Looks like you might be missing `OrderItem.belongsTo(models.MenuItem);`

**Comment by RSpicer** [comment]
Good god, you have no idea how much I struggled with that. Such a small thing, lmao. Thank you so much :+1:

**Comment by mickhansen** [comment]
@RSpicer Yeah, it throws an error about stuff not being associated. It could really be optimized to attempt to guess at what might be missing (`as` mismatch, an existing `hasMany` but no `belongsTo`)
