### ISSUE TITLE
Request - I want to document examples for migrations, what should I do

### ISSUE THREAD

**Issue by milovanderlinden** [sequelize/sequelize#4576]
At the moment, the docs are part of this repository, but sequelize-cli which is really a gem in my opinion (thanks for making it!) needs some love in the documentation.

I spent the last couple of days fine tuning my own migrations to create exactly what sequelize.sync creates. This showed some minor things with schema's and enum's that I want to document so others need not spend so much time debugging in code.

What is the best way to go? And wouldn't it be good if a seperate repository for docs would be created so documentation cannot interfere with the general development process? I would be glad to step in and help out!

**Comment by mickhansen** [comment]
I have/had on my list to add a bunch of information here: http://docs.sequelizejs.com/en/latest/docs/schema/

Just haven't gotten there yet.

**Comment by milovanderlinden** [comment]
Would love to help out. Please let me know what would be a good way to go.

A first suggestion:

1. Fork
2. Write Doc
3. Send Pull request

Is that a good idea?

**Comment by mickhansen** [comment]
Yep, that's how it usually works :)
https://github.com/sequelize/sequelize/blob/master/docs/docs/schema.md
