### ISSUE TITLE
Unable to use sqlite.

### ISSUE THREAD

**Issue by Tankenstein** [sequelize/sequelize#4577]
My team has decided to use sequelize for a project. We will also use sqlite. However, i am unable to use sequelize with sqlite, as it gives me the following error:
`Error: The dialect sqlite is not supported. (Error: Please install sqlite3 package manually)`
I have manually installed sqlite3, i have even included it in the dependencies. Other teammembers got it to work, i, however, have not.

I am running node v4.1.1 and npm v2.14.4 on elementary os 0.3.1, with sequelize 3.9.0 and sqlite 3.1

Any help would be appreciated, i would love to use sequelize.

**Comment by mickhansen** [comment]
What node version are your team mates running?
Make sure you are using a sqlite3 version that is compatible with node v4.x.x

**Comment by Tankenstein** [comment]
Teammates are on 4.1.1 as well, which is the weird part. Officially, sqlite 3.1 should support node 4, but their travis build says otherwise, even though it installs just fine on my computer.

**Comment by mickhansen** [comment]
We kind of swallow the error, try doing more verbose logging on the error here: https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/connection-manager.js#L20 and post what it says.

Are you using NVM? Do you have multiple versions or only your v4? Keep in mind that sqlite3 installed on one nvm version won't work on other versions.

**Comment by Tankenstein** [comment]
I vaguely remembered having multiple node versions, so i checked. I had an old node version installed, which sqlite3 saw apparently. Upon removing that and reinstalling dependencies everything worked. Thanks!
