### ISSUE TITLE
How to define relationship when models are defined in separate files?

### ISSUE THREAD

**Issue by hezjing** [sequelize/sequelize#4578]
Hi

I'm wondering what is the recommended way to define the relationship when the models are defined in separate files.

Assuming that I have a company model,
```javascript
// models/Company.js
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Company', {
  }
};
```

and a project model,
```javascript
// models/Project.js
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Project', {
  }
};
```
Then, I have an `index.js` that will read and import the above models,
```javascript
// models/index.js
files.forEach(function(file) {
  sequelize.import(file);
});

// sequelize.models now contains Company and Project
// then define the relationship: a Company has many Projects
sequelize.models.Company.hasMany(sequelize.models.Project);
```
Is this the right way to define the relationships? I can imagine that there will be a lot of relationships defined in the same file when there are a lot of models.

**Comment by mickhansen** [comment]
I personally use a `relations.js` file, some people add an `associate` method to their models and call that after everything is imported.

**Comment by mjangir** [comment]
Can you please show me the code of your relation.js file?

**Comment by mickhansen** [comment]
```js
module.exports = function(models) {
  // setup relations
};
```

**Comment by mjangir** [comment]
Hi @mickhansen  thank you so much for this quick post. Actually I have really got stuck in the same situation. I have my two models in separate files:

**company.model.js**

```
module.exports = function(sequelize, DataTypes) {
  var Company = sequelize.define('Company', {
    id: {
      type: DataTypes.INTEGER(3),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      comment: "Primary and auto incremented key of the table"
    },
    companyName: {
      field: "company_name",
      type: DataTypes.STRING(255),
      allowNull: false,
      comment: "Company Name"
    }
},
{
    underscored: true,
    freezeTableName:true,
    tableName:'company',
    classMethods:{
      associate:function(models){
        Company.hasMany(models.Location);
      }
    },
  });
  return Company;
};
```

**location.model.js**

```
['use strict';

module.exports = function(sequelize, DataTypes) {
  var Location = sequelize.define('Location', {
    id: {
      type: DataTypes.INTEGER(5),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      comment: "Primary and auto incremented key of the table"
    },
    locationType: {
      field: "location_type",
      type: DataTypes.ENUM('HEAD_OFFICE','REGIONAL_OFFICE','FRANCHISE'),
      allowNull: false,
      comment: "Type of location"
    }
  },
  {
    timestamps: true,
    underscored: true,
    freezeTableName:true,
    tableName:'location',
    classMethods:{
      associate:function(models){
        Location.belongsTo(models.Company, { foreignKey:'company_id', foreignKeyConstraint:true} );
      }
    }
  });

  return Location;
};
```

and I have the this final js file **index.js**

```
'use strict';

import path from 'path';
import config from '../config/environment';
import Sequelize from 'sequelize';

var sequelizeConnection = new Sequelize(config.sequelize.database, null, null, config.sequelize.options);

var db = {
  Sequelize: Sequelize,
  sequelize: sequelizeConnection
};

// Insert models below
db.Company = db.sequelize.import('../api/company/company.model');
db.Location = db.sequelize.import('../api/location/location.model');
db.User = db.sequelize.import('../api/user/user.model');
db.Thing = db.sequelize.import('../api/thing/thing.model');

module.exports = db;
```

**When I run the following code**

```
db.sequelize.sync({force:true})
  .then(startServer)
  .catch(function(err) {
    console.log('Server failed to start due to error: %s', err);
  });
```

The tables are created absolutely fine but there is not foreign key collum on location table and nothing regarding foreign key constrain.

**Can you please help me to solve it. I will really appreciate your solution. Thanks a ton.**

**Comment by mickhansen** [comment]
I don't see you calling the .associate method anywhere. Keep in mind it's not a magic built in Sequelize method, it's just a pattern used by some examples.

**Comment by mjangir** [comment]
So what should I do to work it correctly. Do you have any proposed solution. I'm really new to sequelizeJS.

**Comment by mickhansen** [comment]
Either call the method or setup associations in a file like i suggested. Try SOMETHING, it doesn't sound like you've tried anything. The code that setups associations needs to be actually called, verify that happens :)

**Comment by mjangir** [comment]
I tried to call it using the following:

```
var db = {
  Sequelize: Sequelize,
  sequelize: sequelizeConnection
};

// Insert models below
db.Company = db.sequelize.import('../api/company/company.model');
db.Location = db.sequelize.import('../api/location/location.model');
db.User = db.sequelize.import('../api/user/user.model');
db.Thing = db.sequelize.import('../api/thing/thing.model');

Object.keys(db).forEach(function(modelName) {
  if (db[modelName].options.hasOwnProperty('associate')) {
    db[modelName].options.associate(db)
  }
})

module.exports = db;
```

**Comment by janmeier** [comment]
You are putting `associate` in classMethods, but looking for it in `options` - so the function is not called

**Comment by mjangir** [comment]
I also tried it `db[modelName].classMethods.associate(db)` man but nothing is working :(

**Comment by mickhansen** [comment]
classMethods are adding methods to the class, have you tried inspecting the object? Or just calling db[modelName].associate?

**Comment by mickhansen** [comment]
@mjangir Please do basic debugging on your own before taking up other peoples time, it's the polite thing to do :)

Basic debugging includes checking if and why a method is or is not called, this is basic javascript, nothing Sequelize specific.

**Comment by mjangir** [comment]
Wow, simply two lines worked like a charm for me.

```
db.Company.hasMany(db.Location);
db.Location.belongsTo(db.Company);
```

But I think its not a good practice. Please suggest me to manage all them in separate files whenever you get time.

By the way many many thanks to give your important time.

**Comment by mickhansen** [comment]
@mjangir I personally use a single `relations.js` file as mentioned.

**Comment by sharma-sunil** [comment]
@mjangir Can you please post a code snippet , how you are managing all relationship in `relationship.js` file.

**Comment by Infer-On** [comment]
@joinsunil 

index.js:

`
const CLASSMETHODS = 'classMethods';
const ASSOCIATE = 'associate';

var sequelize = new Sequelize(cfg.db.database, cfg.db.user, cfg.db.password, cfg.db.options);

fs.readdirSync(__dirname).filter(function (file) {
	return (file.indexOf('.') !== 0) && (file !== 'index.js');
}).forEach(function (file) {
	var model = sequelize['import'](path.join(__dirname, file));
	db[model.name] = model;
	});
Object.keys(db).forEach(function (modelName) {
	if (CLASSMETHODS in db[modelName].options) {
		if (ASSOCIATE in db[modelName].options[CLASSMETHODS]) {
			db[modelName].options.classMethods.associate(db);
		}
	}
});
`
Character.js:

`
module.exports = (sequelize, DataTypes) => {
	const Character = sequelize.define('Character', {
		Id: { type: DataTypes.INTEGER, primaryKey: true, autoincrement: true },
		FirstName: DataTypes.STRING,
		LastName: DataTypes.STRING,
		DoB: DataTypes.DATE,
		createdAt: DataTypes.DATE,
		updatedAt: DataTypes.DATE
	}, {
			classMethods: {
				associate: (models) => {
					Character.belongsTo(models.CharacterDetail, {
						foreignKey: 'fk_detail_id',
						as: 'Detail'
					})
				}
			}
		});
	return Character;
}

`

**Comment by delebash** [comment]
This worked for me

model animal.js

```
/* jshint indent: 2 */
module.exports = (sequelize, DataTypes) => {
  const animal = sequelize.define('animal', {
      id: {
        type: DataTypes.INTEGER(11),
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
      },
      non_shelter: {
        type: DataTypes.INTEGER(4),
        allowNull: true
      }
    }
  );

  animal.associate = function (models) {
    animal.hasMany(models.lookup_animal_type);
  };

  return animal
};
```

index.js

```

"use strict";

var fs        = require("fs");
var path      = require("path");
var Sequelize = require("sequelize");
var env       = process.env.NODE_ENV || "development";
const Op = Sequelize.Op;
var config    = require(path.join(__dirname, '..', 'config', 'config.json'))[env];
if (process.env.DATABASE_URL) {
  var sequelize = new Sequelize(process.env.DATABASE_URL,config);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}
var db = {};

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file !== "index.js");
  })
  .forEach(function(file) {
    var model = sequelize.import(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;
db.sequelize.sync();
modul
e.exports = db;


```

**Comment by shtse8** [comment]
importing single model file in sequelize is hell. Thanks for the above approaches.

**Comment by OmarKRostom** [comment]
Looks like @mickhansen is living the dream of being an absolute dickhead, congratulations.

**Comment by mickhansen** [comment]
@OmarKRostom Excuse me?

**Comment by OmarKRostom** [comment]
I see no reason not to help others, simple.

**Comment by OmarKRostom** [comment]
https://github.com/sequelize/sequelize/issues/4578#issuecomment-222650147

**Comment by OmarKRostom** [comment]
https://github.com/sequelize/sequelize/issues/4578#issuecomment-222667208

**Comment by OmarKRostom** [comment]
You have the credits for creating a very good ORM, yet you destroyed my respect to you with those disrespectful comments.

What a shame !

**Comment by OmarKRostom** [comment]
And not just me, in case you think about the heck you care about my opinion.

Because frankly am no body.

**Comment by mickhansen** [comment]
@OmarKRostom So you think a personal attack is okay? Interesting take. 

At the time we were probably having to answer 20-30 issues a day, so less important issues got less attention compared to actual bug reports etc. But thanks for your feedback on how to manage FOSS :)

I'm not the creator of Sequelize nor am i an active maintainer.

**Comment by OmarKRostom** [comment]
I am sorry on being rude replying, but I was very furious by your replies.

**Comment by mickhansen** [comment]
@OmarKRostom Understandable, no hard feeling - however context means a lot, especially on a 2+ year old thread. I could probably/definitely have been a lot more forthcoming but we probably had this question a few times a day and it took up attention from bugs.

**Comment by bradisbell** [comment]
> we probably had this question a few times a day and it took up attention from bugs

@mickhansen Perhaps the documentation could be clearer, then.  I've used Sequelize for a handful of projects over the years and I still have to spend a couple days fighting simple model associations every time I set it up.  Things simply don't work as expected.  The example code available does not work in several cases.  It's difficult to find anything clear or specific on the topic in the documentation.  The documentation makes a lot of assumptions about where the reader is coming from.

I'd be quite happy to improve the documentation, this is open source after all, but I'd have to figure out how to work this package myself first.

It's unfortunate, as Sequelize is definitely one of the better Node.js ORMs available, once you get it running.

**Comment by fraywing** [comment]
Ran into this problem, my approach was just to global require each model file, and spread, loop and associate. 

model `index.js`

``
// require our model files
const models = {
  ...require('./categoryModel'),
  ...require('./eventModel'),
  ...require('./featureModel'),
  ...require('./gameModel'),
  ...require('./mediaModel'),
  ...require('./milestoneModel'),
  ...require('./projectModel'),
  ...require('./roleModel'),
  ...require('./taskModel'),
  ...require('./teamModel'),
  ...require('./mediaModel'),
  ...require('./userModel')
};

// call associate on each of the models
Object.keys(models).forEach(key => {
  if (models[key] && models[key].associate) {
    models[key].associate(models);
  }
});

module.exports = models;
``

**Comment by abhitheawesomecoder** [comment]
I cannot find association function or any syntax like "Model.associate = function(models) {" any where in the sequelize docs. Can any one please help me to find details about association function in docs or anywhere.

**Comment by carweb99** [comment]
Looking for the same problem but as always documentation is bas and you have to guess or google a lot

**Comment by carweb99** [comment]
The solution was ver simple when you find it this was mine "models.chatuser" where chatuser is a model accociated 1-1 with
chatmessage.associate = function (models) {
    chatmessage.hasOne(models.chatuser, { foreignKey: 'chatuserid' });
  };

**Comment by netbofia** [comment]
> I tried to call it using the following:
> 
> ```
> var db = {
>   Sequelize: Sequelize,
>   sequelize: sequelizeConnection
> };
> 
> // Insert models below
> db.Company = db.sequelize.import('../api/company/company.model');
> db.Location = db.sequelize.import('../api/location/location.model');
> db.User = db.sequelize.import('../api/user/user.model');
> db.Thing = db.sequelize.import('../api/thing/thing.model');
> 
> Object.keys(db).forEach(function(modelName) {
>   if (db[modelName].options.hasOwnProperty('associate')) {
>     db[modelName].options.associate(db)
>   }
> })
> 
> module.exports = db;
> ```
Try it this way:
```
Object.keys(db).forEach(function(modelName) {
  if ('classMethods' in db[modelName].options) {
    db[modelName].options.classMethods.associate(db);
  }
});
```

**Comment by LaeraFelipe** [comment]
Here is a package to help with that: 
 https://www.npmjs.com/package/sequelize-associate

**Comment by quocvu** [comment]
Hi all,
I have done all that and it works great, except for one thing.  How can add a method to the model while its code reference another model?
For example, let's say I have a User model, which has many Bookmark objects.  I want to overwrite the createBookmark() method to include some logic before I add the bookmark.  Thus I might need to import another model if the logic needs to query a third model.  What would be a pattern to accomplish this?

**Comment by ephys** [comment]
We have plans to improve this in a future release https://github.com/sequelize/sequelize/issues/14024

**Comment by gabrielmlinassi** [comment]
My solution follows the tip given by @mickhansen at https://github.com/sequelize/sequelize/issues/4578#issuecomment-222650147

This is my server.js express file. Make sure to call the association file after you imported all your models
```
const User = require("./db/models/user");
const Product = require("./db/models/product");
const Cart = require("./db/models/cart");
const CartItem = require("./db/models/cartItem");

const sequelize = require("./db");
require("./db/associations")(sequelize.models);
```

And this is my associations file
```
module.exports = (models) => {
  models.cartItem.belongsTo(models.cart, {
    foreignKey: { allowNull: false },
  });

  models.cartItem.belongsTo(models.product, {
    foreignKey: { allowNull: false },
  });

  models.product.hasMany(models.cartItem, {
    foreignKey: { allowNull: true },
  });

  models.cart.belongsTo(models.user, {
    foreignKey: { allowNull: false },
  });

  models.cart.hasMany(models.cartItem, {
    foreignKey: { allowNull: false },
  });

  models.user.hasOne(models.cart, {
    foreignKey: { allowNull: true },
  });
};
```
