### ISSUE TITLE
[Documentation] API -> Associations -> BelongsTo Needs revision

### ISSUE THREAD

**Issue by subjectix** [sequelize/sequelize#4580]
> In the API reference below, replace `Assocation(s)` with the actual name of your association, e.g. for `User.belongsToMany(Project)` the getter will be `user.getProjects()`.

It doesn't seem like `User.belongsToMany(Project)` here `belongsTo` this page.

Or:

>| Name | Type | Description |
>| ---- | ---- | ----------- |
>| [newAssociations] | Instance &#124; String &#124; Number | An array of instances or primary key of >instances to associate with this. Pass `null` or `undefined` to remove all associations. |

Shouldn't this be: either one instance or one primary key, or null/undefined?

I need to know if this is my mistake or the doc is wrong :D
So I gotta be sure since I wanna make type definitions so we can make these association mixins type-safe. Something like:

```js
interface BelongsToAssociationGetMixin<TAssociationInstance> {
  (options?: { scope: string | boolean }): Promise<TAssociationInstance>;
}

interface BelongsToAssociationSetMixin<TAssociationInstance, TAssociationInstancePrimaryKey> {
  (newRole: TAssociationInstance|TAssociationInstancePrimaryKey, options?: { save: boolean }): Promise<void>;
}
```

**Comment by mickhansen** [comment]
belongsToMany and belongsTo are seperate associations, to what are you referring exactly?

**Comment by subjectix** [comment]
Yes, indeed. I'm saying that the [documentation](http://docs.sequelizejs.com/en/latest/api/associations/belongs-to/) for `belongsTo` in the association section of the api is talking about `belongsToMany` association not the `belongsTo` association. I get the feeling that is a regression bug. Maybe sequelize 2 looked like that? 
Anyways, all I wanna know is whether the documentation is buggy or I'm not understanding it. I simply can't wrap my head around some statements made there:
> In the API reference below, replace `Assocation(s)` with the actual name of your association, e.g. for `User.belongsToMany(Project)` the getter will be `user.getProjects()`.

the page is about `belongsTo` why does it refer to `belongsToMany`
and this:

>| Name | Type | Description |
>| ---- | ---- | ----------- |
>| [newAssociations] | Instance &#124; String &#124; Number | An array of instances or primary key of instances to associate with this. Pass `null` or `undefined` to remove all associations. |

*newAssociations*? why plural? doesn't `belongsTo` create a one-to-many association and put the foreign key on the source model? So that the source model has like a `role` that can be accessed using `getRole` and `setRole`? Am I missing something? I'm confused :confused:

**Comment by mickhansen** [comment]
Definitely a bug: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to.js#L86
