### ISSUE TITLE
iojs-3.3.1 has build error

### ISSUE THREAD

**Issue by jimtang9527** [sequelize/sequelize#4581]
iojs-3.3.1 has build error
Now using io.js v3.3.1
npm --version
2.14.3

https://s3.amazonaws.com/archive.travis-ci.org/jobs/82477303/log.txt

make: Entering directory `/home/travis/build/minicloud/minicloud/node_modules/pg-native/node_modules/libpq/build'
CXX(target) Release/obj.target/addon/src/connection.o
In file included from /home/travis/.node-gyp/iojs-3.3.1/include/node/node.h:42:0,
from ../node_modules/nan/nan.h:24,
from ../src/addon.h:4,
from ../src/connection.cc:1:
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:336:1: error: expected unqualified-id before â€˜usingâ€™
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:468:1: error: expected unqualified-id before â€˜usingâ€™
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:499:48: error: â€˜Handleâ€™ does not name a type
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:499:48: error: ISO C++ forbids declaration of â€˜parameterâ€™ with no type [-fpermissive]
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:499:54: error: expected â€˜,â€™ or â€˜...â€™ before â€˜<â€™ token
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:520:54: error: â€˜Handleâ€™ does not name a type
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:520:54: error: ISO C++ forbids declaration of â€˜parameterâ€™ with no type [-fpermissive]
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:520:60: error: expected â€˜,â€™ or â€˜...â€™ before â€˜<â€™ token
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:533:54: error: â€˜Handleâ€™ does not name a type
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:533:54: error: ISO C++ forbids declaration of â€˜parameterâ€™ with no type [-fpermissive]
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:533:60: error: expected â€˜,â€™ or â€˜...â€™ before â€˜<â€™ token
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h: In member function â€˜bool v8::PersistentBase::operator==(int) constâ€™:
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:522:65: error: â€˜thatâ€™ was not declared in this scope
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h: In member function â€˜bool v8::PersistentBase::operator!=(int) constâ€™:
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:534:24: error: â€˜thatâ€™ was not declared in this scope
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h: At global scope:
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:700:61: error: â€˜Handleâ€™ has not been declared
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:700:67: error: expected â€˜,â€™ or â€˜...â€™ before â€˜<â€™ token
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h: In constructor â€˜v8::Persistent::Persistent(v8::Isolate*, int)â€™:
/home/travis/.node-gyp/iojs-3.3.1/include/node/v8.h:701:60: error: â€˜thatâ€™ was not declared in this scope

**Comment by janmeier** [comment]
``/home/travis/build/minicloud/minicloud/node_modules/pg-native/node_modules/libpq/build'`

the problem is in the pg-native module, not with sequelize
