### ISSUE TITLE
BulkCreate don't return primary key (id)

### ISSUE THREAD

**Issue by krainet** [sequelize/sequelize#4583]
Hi,

I'm using "sequelize": "^3.9.0"

And i'm using a bulkCreate command like this:

models.Devicetoken.bulkCreate(devicetoken_data)
                .then(function (insertedObjects) {
console.log(insertedObjects[0].id); -------------------> returns null :(
                    models.Segment.findByPrimary(1)
                        .then(function(segment){
                                segment.addDevicetoken([1,2,3,4,5]);
                        });

Insert sentence seems to be OK in BBDD but when i'm check result of insert (insertedObjects array) i'm see that "id" field is set to NULL , in other words, last inserted id is not recovered and setted into object.

SQL::: "Executing (default): INSERT INTO `Devicetokens` (`id`,`token`,`CustomerId`,`PlatformId`,`createdAt`,`updatedAt`) VALUES (NULL,'c8bbba189779dec5559e463acdec6a74',1,1,'2015-09-28 14:06:20','2015-09-28 14:06:20'),(NULL,'4f6b0dfe449ea5b46126c370358c379c',1,1,'2015-09-28 14:06:20','2015-09-28 14:06:20'),(NULL,'cff296811857b21a718825dce99e3e0a',3,2,'2015-09-28 14:06:20','2015-09-28 14:06:20'),(NULL,'8f6f4f2e6ecc5a809108a5ae9e4dcbed',4,2,'2015-09-28 14:06:20','2015-09-28 14:06:20'),(NULL,'45fca06428df7843644cb42011825822',5,1,'2015-09-28 14:06:20','2015-09-28 14:06:20');
"

Is this normal ?

**Comment by mickhansen** [comment]
Looks like you are using mysql, mysql has never supported returning insert ids for multiple rows.

**Comment by krainet** [comment]
ouch ! I'm dumb! many thanks for your quick response

**Comment by HusseinOsman** [comment]
add this  {individualHooks: true}
like this:
models.Devicetoken.bulkCreate(data,{individualHooks: true})
