### ISSUE TITLE
UTF-8 encoding won't work in Postgres?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#4588]
I'm trying to save unicode characters correctly to my Postgres database. I have the following options set at the database, table, and field level: {charset: 'utf8', collate: 'utf8_general_ci'}.

My test string to be inserted uses 3 types of apostrophes: U+0027, U+2018, U+2019. These characters look fine in both my local text editor and my terminal.

But when I try inserting them into a Postgres database string field using sequelize, the characters all get converted to U+2019.

What am I doing wrong?

**Comment by janmeier** [comment]
```js
sequelize.sync({
  // logging: console.log,
  force: true
}).bind({}).then(function() {
  return Test.create({
    name: '\'‘’'
  });
}).then(function(rows) {
  return Test.findAll();
}).then(function(rows) {
  console.log(rows[0].get());
```

The characters seem to work fine for me - so I'm guessing something is off with your db setup perhaps?

The charset and collate options only work for mysql as far as I know

**Comment by GeoffreyPlitt** [comment]
Wow, sorry, the problem is elsewhere, thanks!
