### ISSUE TITLE
API -> Associations -> Overview seems to be old.

### ISSUE THREAD

**Issue by subjectix** [sequelize/sequelize#4591]
Hello again guys. I'm working on the typescript type defs for association mixins. And for that reason I need precise api documentations i.e. I'll be bothering you with a lot these :sweat_smile: 

The overview section of the association api documentation (phew) seems to be a bit old. From what I understand from [this](http://docs.sequelizejs.com/en/latest/docs/associations/#belongs-to-many-associations) `belongsToMany` *requires* `through` it's not optional any more. And that `hasMany` cannot be used for n:m associations (right?!). 

Give me the go ahead to fix this if I'm right :sunglasses:

**Comment by janmeier** [comment]
Yep, you are correct on both counts - through is required on BTM, and has many is only for 1:m
