### ISSUE TITLE
Document strong typings from Definately Typed

### ISSUE THREAD

**Issue by subjectix** [sequelize/sequelize#4592]
I do understand the fact that the type definitions from [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped/tree/master/sequelize) are entirely a different project. But the truth is I had to search a lot and find [sequelize-auto-ts](https://github.com/samuelneff/sequelize-auto-ts) only to understand how i should use the definitions to strong type my models and their instances. It would be really nice to add a section for these definitions so that everyone can fully utilize the power of sequelize and typescript combined :fire: :fire:
If my proposal is agreeable with you guys I'll get working on it :wink:

**Comment by janmeier** [comment]
Hmm, I dunno if sequelize + typescript is a widely enough used combination to warrant a section in the docs - but you might add it to the wiki https://github.com/sequelize/sequelize/wiki/Add-ons-&-Plugins

**Comment by subjectix** [comment]
I see. Well let me do a survey and get back to you on that. Thanks @janmeier

**Comment by subjectix** [comment]
I did my research, I'm not going to do that. But I might make a repo to explain how to use the definitions effectively.

**Comment by enriched** [comment]
:+1: for documentation on the ts, @subjectix did you ever do a write up?  Would love to see it, going through some of the same pains right now.  So far the best thing that I have found is #3176, I will check out that sequelize-auto-ts though.

**Comment by subjectix** [comment]
@enriched Actually I never found the time to do it. although it wouldn't take too long, the fundamental question still remains... where to put the tutorials :D maybe a README in the seqeulize's folder in the DefinitelyTyped repo? What do you think? Might that actually help people? Then how would they find them? Help me answer these questions and then I will write the README in that folder ^.^

**Comment by enriched** [comment]
Hmmm, if you dropped that README in the DefiinitelyTyped sequelize folder and then put a link to it in the [Add ons & Plugins](https://github.com/sequelize/sequelize/wiki/Add-ons-&-Plugins) and added a noticeable comment in the sequelize.d.ts that would probably be a good start. Then if we just drop comments in the threads talking about it that should be plenty of paths for people to find to it.

sequelize.d.ts actually has quite a bit of jsdoc in it so maybe if you just generated that and dropped it somewhere that might even work?  Although I don't know if it actually has a full working "best practice" example in there.

Thoughts?

**Comment by subjectix** [comment]
the jsdoc won't help set up the required type system for the Models, it's a little complicated. 
I guess adding a link to `Add ons & plugins` would do. But then people will have to know that there actually is such a place in the github repo's wiki section. I didn't even know about it until it was mentioned here :D 
If we could just somehow add a link in the docs page, it would make it very easy for people to find. 
Would that be ok with you @janmeier

**Comment by janmeier** [comment]
@subjectix Adding a mention to the repo repo would be fine i think

**Comment by subjectix** [comment]
Alright tnx. I'll get to it then
