### ISSUE TITLE
Question: Including a 1:m relation in query

### ISSUE THREAD

**Issue by YP28** [sequelize/sequelize#4595]
I'm trying to include a polymorphic relation in a query, but it fails to see the relationship.

Assume we have a User, Post and Slug model. Slug can be attached to either Post or User. I try to query the Slug, including the Post/User on forehand like this:
```
Slug.findOne({ where: { slug: req.params.slug }, include: [ 'sluggable' ] }).then(function (slug) {
  res.json(slug);
});
```
But I encounter an error:
```
Unhandled rejection Error: Include unexpected. Element has to be either a Model, an Association or an object.
```

In this particular case, I am sure it is the User model that should be returned. However, when using
```
Slug.findOne({ where: { slug: req.params.slug }, include: [{ model: User }] }).then(function (slug) {
  res.json(user);
});
```
I get: 
```
Unhandled rejection Error: User is not associated to Slug!
```

My models are setup exactly as described by [the documentation](http://docs.sequelizejs.com/en/latest/docs/associations/#1m).

**Comment by mickhansen** [comment]
Strings as include should not be anywhere in the docs, if they are it's definitely an error.

The include statement needs to match the association statement, so if you've used alias on the association you need to use it on the include aswell.

**Comment by YP28** [comment]
Doh! Thanks, that fixed it.

**Comment by federicojasson** [comment]
@mickhansen 

So, are the following two includes wrong as well? (From the latest docs).

(https://github.com/sequelize/sequelize/blame/master/docs/docs/models-usage.md#L507)
```
User.findAll({ include: ['Instruments'] }).then(...);
```

(https://github.com/sequelize/sequelize/blame/master/docs/docs/models-usage.md#L527)
```
User.findAll({ include: [{ association: 'Instruments' }] }).then(...);
```

**Comment by alisherafat** [comment]
what if you have multiple slugable model and you want to include that using both `sluggable_type` and `sluggable_id`?  
`Slug.findOne({ where: { slug: req.params.slug }, include: [ 'sluggable' ] }).then(function (slug) {
  res.json(slug);
});`
