### ISSUE TITLE
Generating the where clause for the in operator becomes inefficient with larger amount of elements

### ISSUE THREAD

**Issue by haohui** [sequelize/sequelize#4596]
I noticed around 1 second of latency when generating the SQL statement with an `$in` operator which contains around ~180 elements.

The codes are the following:

```
var model = sequelize.define('ProblemState', {
  uid_pid: {type: 'BINARY(8)', primaryKey: true},
  state: Sequelize.INTEGER(6)
}

keys = [new Buffer(),...] // around 180 elements
var results = model.findAll({where: {uid_pid: {$in: keys}}, limit: 10});
```

It takes around 1 second to generate the sql statement. The latency does not appear if I direct run the generated query with the same set of keys via `sequlize.query()`.

**Comment by haohui** [comment]
The latency drops to around ~100 msec if I generates an equivalent query using the `$or` operator (i.e., uid_pid = foo or uid_pid = bar ...).

**Comment by mickhansen** [comment]
I wonder if it's related to the use of Buffer.

**Comment by janmeier** [comment]
I've narrowed it down to `mapOptionFieldNames`, namely this piece of code: https://github.com/sequelize/sequelize/blob/7487701a861a847cedbafe7e38c110f5a55ab132/lib/utils.js#L133-L139

Which calls `mapOptionFieldNames` recursively for each buffer.

This is to support stuff like `{ $or: [ { foo : 'bar' }, { baz: 'zab' }]}`, where `field` names should be mapped properly.

I haven't been able to detect any difference between using or and in. Not really sure there's anything we can do. We might skip mapping if the key is `$in` but it feels like a hack to do stuff like that in utils - it shoudn't care about the keys

**Comment by mickhansen** [comment]
@janmeier It's looping once for the array and then recursively calling for each buffer? That sounds like a bug, no reason to attempt to map a binary value.

**Comment by mickhansen** [comment]
@janmeier Couldn't we simply tell it not to do a recursive call if a primitive value here: https://github.com/sequelize/sequelize/blob/7487701a861a847cedbafe7e38c110f5a55ab132/lib/utils.js#L135?

**Comment by janmeier** [comment]
My guess what that it was just looping over each element but you're right, that wouldn't explain why this only happens to buffers. 

That would probably work yeah :)

**Comment by mickhansen** [comment]
Although the recursive call should be a no-op since the passed value has no keys, so not sure why this is a performance hit for buffers, do they have magic getters that incur a performance penalty that we don't know off? ;p

**Comment by janmeier** [comment]
It's caused by [this](https://github.com/sequelize/sequelize/blob/a6a8146c46a629c16fa7513027b5ef2b691f7d36/lib/utils.js#L136) line, which sends `{ where: Buffer }` to as recursive `mapOptionFieldNames` call - Which then loops through the buffer because [this](https://github.com/sequelize/sequelize/blob/a6a8146c46a629c16fa7513027b5ef2b691f7d36/lib/utils.js#L120) loop is missing an `isPlainObject` call. Fix coming up
