### ISSUE TITLE
Naming collision in N-M options

### ISSUE THREAD

**Issue by glutentag** [sequelize/sequelize#4597]
When using a N-M association accessor method, addAssociation for instance, the signature is:

```
(newInstances, additionalAttributes)
```

transformed in

```
options = additionalAttributes
```

Thus, options is used in all queries (association.through.model.findAll), but also as additional attribute when creating the association through model. It can create bugs when this attribute is a keyword, 'order' for instance.

Could it be possible to separate in the signature additionalAttributes from options?

**Comment by janmeier** [comment]
Yeah, I've actually been thinking about the same thing - it would also make the code easier to maintain.

`options.through` would probably be best, in order to fit with the rest of the API

**Comment by mickhansen** [comment]
I've never liked this piece of the code. But from the end user it made sense if you never used options for the setters and didnt want to pass an empty object/null.

**Comment by subjectix** [comment]
I think what @janmeier proposed is the ideal solution but it introduces breaking changes (if someone has a join table with through as a column). So it will have to be fixed with the next major release.

So you might wanna consider this too:
Since every association mixin has options for the second argument, might it look ugly to modify the first argument? I mean something like this:

```js
// No through attributes.
source.addTarget(target, options);

// With through attributes.
source.addTarget({
    target: target, // Instance or PK
    through: {/* through attributes*/},
}, options);
```

I'd say this is easier to achieve without introducing breaking changes. All you have to do is take the extra attributes from options and assign the `firstArg.through` with them:
```js
// Values from the firstArg.through must override the attributes from extraAttribsFromOptions.
let throughAttributes = Object.assign({} , extraAttribsFromOptions, firstArg.though);
```
This will not introduce breaking changes, make it easy to add deprecation warnings, and keep the api consistent. As in: *"All data come from the first argument, all options come from the second argument"*.
What users will be faced with is this:

```js
// ---------------------------------------------------
// With through attributes. Without options:
// Before:
user.addProject(project, {role: 'admin'});
// After:
// OK
user.addProject({
    target: project,
    through: {role: 'admin'}
});
// OK but with deprecation warning: 
// "role is defined on the join table. This approach is deprecated please see blah blah blah..."
user.addProject(project, {role: 'admin'});


// ---------------------------------------------------
// With through attributes. With options:
// Before:
user.addProject(project, {role: 'admin', validate: true});
// After:
// OK
user.addProject({
    target: project,
    through: {role: 'admin'}
}, {validate: true});
// OK but with deprecation warning: 
// "role is defined on the join table. This approach is deprecated please see blah blah blah..."
user.addProject(project, {role: 'admin', validate: true});

// ---------------------------------------------------
// Without through attributes. Without options:
// Before:
user.addProject(project);
// After:
user.addProject(project);


// ---------------------------------------------------
// Without through attributes. With options:
// Before:
user.addProject(project, {validate: true});
// After:
user.addProject(project, {validate: true});
```

Not a lot of api inconsistency and no breaking changes :grin: 

P.S. If you like my proposal I can make a pull request ^^

**Comment by janmeier** [comment]
@subjectix Hmm, good question. At first I didn't like the `{ target, through }` thing very much, but you do have a good argument that it will keep all data in the first argument. 

In any case we'd want to support passing through in the options as well, for cases where you want to add the same `through` attributes to all targets, e.g.
```js
user.addProjects([
    {
        target: project1,
        through: {role: 'member'}
    }, {
        target: project2,
        through: {role: 'member'}
    }, {
        target: project3,
        through: {role: 'member'}
    },
], {validate: true});
```
Is tiresome, when you could just pass `{ through }` in options. Also, validating whether `options.through` is a column or attributes for the join table should be pretty straightforward - just check `isPlainObject`.

I think I'm stilll leaning most towards keeping the `.through` in options, but i want to hear @mickhansen s opinion as well

**Comment by mickhansen** [comment]
So the first argument can both be `target` and an item that holds `target` and `through`?
What if the target model has a target field?

**Comment by janmeier** [comment]
We don't support passing objects to `add`, so that can be checked for :). Might pose a problem for `createAssociation` though

**Comment by subjectix** [comment]
@janmeier You are right about it being tiresome. But in the real world that can be done with a for loop. 

It's true that it leads to a prettier aip but what if they want different values per association? They will have to either work around it to avoid multiple round-trips or just don't care and let it do many round trips and chock the database. 

But with what I purposed, they can very easily and declaratively state their purpose, and if they want same value for all of them just do a for loop and add the extra attributes. 

In my humble opinion I always prefer rich functionality + good documentation over simple api + less documentation. After all our end users are developers, we don't wanna give them a hard time and limit that they can achieve with this awesome library :grin:

**Comment by janmeier** [comment]
Actually we already support passing individual attributes for each instance by setting `instance.jointablename`, e.g `userInstance.userProjects = { role: 'admin' }` - its kinda ugly though, I like your version more.

PR with `{ target, through }`, and an option to set `through` in the options argument as well would be very nice! :)

**Comment by subjectix** [comment]
@janmeier Thanks, I'll try to understand the code and see if I can somehow get that to work. ^^

But if we are doing this, we have to do this for all belongsToMany mixins, I kinda have no idea how I should tackle `createAssociation` since it accepts objects, if we want this for `createAssociation` we have to introduce a breaking change :scream:

**Comment by janmeier** [comment]
Actually we should be able to detect whether `through` and `target` are attributes of the model during `createAssociation` or an option - if its an object, its and option, otherwise its an attribute

**Comment by sushantdhiman** [comment]
Breaking change discussed in this PR i.e. moving `through` option is implemented in https://github.com/sequelize/sequelize/pull/6931 so closing this PR for milestones.

Other remaining task is a non breaking feature which will be tracked in [#6934](https://github.com/sequelize/sequelize/issues/6934)
