### ISSUE TITLE
Automatically adds current utc time in date

### ISSUE THREAD

**Issue by shreychaturvedi123** [sequelize/sequelize#4598]
While fetching date it automatically adds current timezone time.

**Comment by janmeier** [comment]
Ehm, wat :D ? 

Can you please provide some more detail? Yes, sequelize defaults to saving everything in UTC, but that can be changed?

**Comment by shreychaturvedi123** [comment]
How can it be changed?

**Comment by janmeier** [comment]
`options.timezone? http://docs.sequelizejs.com/en/latest/api/sequelize/

**Comment by janmeier** [comment]
Closing, no response
