### ISSUE TITLE
readthedocs search breaks

### ISSUE THREAD

**Issue by kevinawoo** [sequelize/sequelize#4611]
When trying to search the [docs](http://docs.sequelizejs.com/en/latest/), the search redirects to the domain name `https://readthedocs.org` instead of sequelize. 

ex:
Doing a search for `create` redirects to:

results page: [https://readthedocs.org//search/?q=create...](https://readthedocs.org//search/?q=create&check_keywords=yes&area=default&project=sequelize&version=latest&type=file)
result link: https://readthedocs.org/en/latest/api/model/?highlight=create
changing the domain to sequelize: http://docs.sequelizejs.com/en/latest/api/model/?highlight=create
but the highlighting isn't working.

**Comment by janmeier** [comment]
Issues opened with rtd
