### ISSUE TITLE
How to change model associations without losing data?

### ISSUE THREAD

**Issue by lvarayut** [sequelize/sequelize#4612]
I have defined many models in my project using `sequelize.define()`. Now, the project has been launched in the production with a lot of data. I recently need to modify some of the models, changing some columns and associations. In order to make the changes take effect, I need to drop all tables and lose all data. 

So, is there any better way I can preserve my data while changing the models? I have read about migration but not quite understand how to use it in this particular problem.

**Comment by janmeier** [comment]
Migrations are exactly the way to go - You write a migration that adds / removes the particular columns and update your sequelize models to match the next schema

**Comment by lvarayut** [comment]
Thanks @janmeier for your quick response. If I wanted to change associations, for example, changing `{onDelete: 'DELETE'}` to  `{onDelete: 'CASCADE'}`, what should I write in the migration? Could you give me any documents or example to do so?

**Comment by janmeier** [comment]
Unfortunately migrations are one of our least documented areas + I'm not very familiar with them, so I can't really help you much.

You'll probably need some variation of [`changeColumn`](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L374)

**Comment by lvarayut** [comment]
@janmeier That's true it doesn't have a lot of documentations, plus I'm new to the database migration. I read many of them but didn't understand the whole idea. BTW,  Thanks so much, if you found some good explanation on this topic, please kindly let me know.

**Comment by janmeier** [comment]
@lvarayut I know its not very well documented, but I suggest you experiment with it and perhaps look at the tests to see how it can be used

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
