### ISSUE TITLE
add returning option and affected rows to .create() and .createFoo()

### ISSUE THREAD

**Issue by zachguo** [sequelize/sequelize#4614]
I'm using MySQL, `{returning: true}` takes no effect for `create` while `update` & `destroy` work fine.

**Comment by janmeier** [comment]
`returning` is only supported by postgres and mssql by the `RETURNING` and `OUTPUT INSERTED` keywords.

Also, why do you need affected rows for create? One row was created :D? 


I'm not totally sure what your issue is here - perhaps you can show some code and what you are expecting to happen?

**Comment by zachguo** [comment]
I'm using MySQL and `{returning: true}` does work for `update` & `destroy`, though documentation claims it's not supported.

It's just about the consistency. MySQL would return number of affected rows for all three actions(create, update & destroy), while sequelize only do so for two of them(update & destroy).

**Comment by mickhansen** [comment]
@zachguo `create` can only ever create a single row, unless there was a unique constraint error.

**Comment by mickhansen** [comment]
And no, returning doesn't work for update and destroy, it won't return the changed values. Affected rows count has nothing to do with `returning: bool`

**Comment by zachguo** [comment]
@mickhansen ah got it, `returning` is unrelated to affected rows. Number of affected rows would be return anyway by `update` & `destroy`.

**Comment by zachguo** [comment]
@mickhansen thx for the clarification
