### ISSUE TITLE
findAll returnin empty set but running logged query return a few rows.

### ISSUE THREAD

**Issue by x-warrior** [sequelize/sequelize#4615]
Running:

```models.User.findAll({where: {"last_access": {lte: date_str } } }).then(function (users) {
console.log(users.length);
});```

Outputs:
Executing (default): SELECT "id", "email", "authentication_token", "is_admin", "notifications_count", "last_access", "created_at", "updated_at" FROM "users" AS "User" WHERE "User"."last_access" <= '2015-10-7';

Users.length returns 0, running query manually returns 2.

Ideas on what could be wrong? 

sequelize@3.3.2

PS: date_str is a variable with value 2015-10-7

**Comment by janmeier** [comment]
Have you tried running the raw query with sequelize or through the command line?

This might be related to timezone offset - sequelize sets the connection timezone to UTC by default

**Comment by x-warrior** [comment]
You're probably right, by the time that I tested it was near midnight. I will give it a try again today and let you know. Thanks!

**Comment by janmeier** [comment]
Ping @x-warrior

**Comment by x-warrior** [comment]
I did some manual testing and you seem right. I will close this, if I have this again on any other scenario I will let you know. Thanks!
