### ISSUE TITLE
Problem in Order of migration file

### ISSUE THREAD

**Issue by moslemezzati** [sequelize/sequelize#4617]
I've some migrate file that when migration their foreign key dependencies cause error for example,
"20151006145304-create-coin-table.js" file conten is:
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('CoinTables', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      coin_id: {
        type: Sequelize.INTEGER,
        references: 'Coins',
        referenceKey: 'id',
        onUpdate: 'CASCADE',
        onDelete: 'CASCADE'
      },
    });
  }
};

and "20151006160735-create-coin.js" file content is:
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('Coins', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
    });
  }
};

Then it shows this error after migrate operation:
[SequelizeDatabaseError: relation "Coins" does not exist]
  name: 'SequelizeDatabaseError',
  message: 'relation "Coins" does not exist',

but when I migrate file one by one in dependencies order it works, is there any way to migrate files without concern about their dependencies?

**Comment by janmeier** [comment]
Please refer this issue to sequelize/umzug, which contains migration logic

**Comment by moslemezzati** [comment]
OK thanks
