### ISSUE TITLE
<Table> is not associated to <Table>

### ISSUE THREAD

**Issue by Name-less** [sequelize/sequelize#4618]
I have been through this issue for a while and I did not succeed to do what I want.

I have two models, Teams and Assocs ( that are related through A2t table as implemented below : 

```
   this.Assocs.belongsToMany(this.Teams, { as: 'AssocToTeam', through: this.A2t, foreignKey: 'a2t_assoId' });
   this.Teams.belongsToMany(this.Assocs, { as: 'TeamToAsso', through: this.A2t, foreignKey: 'a2t_teamId' });
```

When I have an object Team and I want the Assoc, I can call : 
```
myTeam.getTeamToAsso() 
```
and I get the assoc. Everything is normal.

But when I try to run the query : 
```
   orm.Teams.sync()
        .then(function(){
            return orm.Teams.findAll({
                include: [
                    {
                        model: orm.Assocs,
                        through: {
                            where: {asso_number: 1}
                        }
                    }
                ]
            })
        })
```
It says me that Teams and Assocs are not associated ... I think I miss one (or more) point(s) ...

```
Unhandled rejection Error: Assocs is not associated to Teams!
```

**Comment by janmeier** [comment]
You need to add the `as` part from the association to the include as well. Or you could save a reference to the association returned from belongsToMany and use `association:` instead

**Comment by Name-less** [comment]
Thanks for yout answer.

So basically, I need to call the query : 

’’’
orm.Teams.findAll({
                include: [
                    {
                        model: orm.Assocs,
                        as: 'TeamToAsso',
                        through: {
                            where: {asso_number: team_number}
                        }
                    }
                ]
            })
’’’
It return : ’’’Unknown column 'TeamToAsso.bdnet_a2t.asso_number' in 'on clause'’’’
I understand the error but not why he try to find this column ...

I do not understand the second part of your answer and more precisely what I need to do with the association returned from belongsToMany ?

**Comment by Name-less** [comment]
Ok i finally get the point, thank you !

That was the correct syntax : 

```
    orm.Assocs.sync()
        .then(function(){
            return orm.Assocs.findAll({
                where:{asso_number:team_number},
                include:[
                    {
                        model: orm.Teams,
                        as: 'AssocToTeam',
                        include:[
                            {
                                model:orm.Events,
                                as:'TeamsEventsId',
                                where:{
                                    evnt_id:1
                                }
                            }
                        ]
                    }
                ]
            })
        }).then(function(result){
            callback(result);
        })
```
