### ISSUE TITLE
like options

### ISSUE THREAD

**Issue by pinducin** [sequelize/sequelize#4624]
hello, as I do to generate this restriction "ILIKE ALL (ARRAY['%ROT%','%SUP%','%R12%'])" using ilike?
This code: "{$ilike: {$all: arrString}}}"  gives the following error
"Unhandled rejection SequelizeValidationError: {"$all":["%ROT%","%SUP%","%R12%"]} is not a valid string" and the query in postgresql is supported.
best regards.

**Comment by janmeier** [comment]
See https://github.com/sequelize/sequelize/issues/4314

**Comment by pinducin** [comment]
thanks !!!, but it seems to me that the problem is '$all'. Changing by '$any' runs smoothly.I need to do is to generate the SQL sequalize, for example: "ILIKE ALL (ARRAY['%ROT%','%SUP%','%R12%'])".
best regards.

**Comment by janmeier** [comment]
Have you actually tried with the latest master or tried the fix suggested in the linked issue? If you have then please open a new issue with a reproducible test case

**Comment by pinducin** [comment]
Hola, estoy usando sequalize 3.0, y postgresql el problema radica en que necesito generar la siguiente restricción en SQL en el WHERE. ... "ILIKE ALL (ARRAY['%ROT%','%SUP%','%R12%'])".
modificando el siguiente código  en abstract/query/generator lo he logrado...

//value = this.escape(value, field);
                if (_.isPlainObject(value) && value.$any) {
                    comparator += ' ALL';
                    value = value.$any;
                    value = '(' + this.escape(value) + ')';
                } else {
                    value = this.escape(value, field);
                }

básicamente lo que hice es cambiar el comparator += ' ANY'; por  comparator += ' ALL';

pero me queda sin funcionar el ANY. lo que necesito hacer es generar esto mismo para $all. Se entiende el problema?????

**Comment by janmeier** [comment]
I have no idea what you just said...

**Comment by pinducin** [comment]
ok!!!
im nedd add support for this operator !!!!!!! ----      LIKE ALL     -------
only has this
$like: { $any: ['cat', 'hat']}  // LIKE ANY ARRAY['cat', 'hat'] - also works for iLike and notLike
Im need
$like: { $all: ['cat', 'hat']}  // LIKE ALL ARRAY['cat', 'hat'] - also works for iLike and notLike
you understand?

**Comment by janmeier** [comment]
Looking at the code both should be supported. Have you actually tested it, and what was the output?

**Comment by pinducin** [comment]
as I put in the beginning ...
"Unhandled rejection SequelizeValidationError: {"$all":["%ROT%","%SUP%","%R12%"]} is not a valid string"

**Comment by janmeier** [comment]
And in my response to that I linked to a known issue, which has been fixed on in latest master, which I told you to try

**Comment by pinducin** [comment]
thanks, that I see. but I think that problem is on the other side

**Comment by janmeier** [comment]
Just test with latest master and see if it works. Otherwise, please open a new issue with a [SSCCE](http://sscce.org/)
