### ISSUE TITLE
Question: Apply Scopes to Eager Loaded Modules

### ISSUE THREAD

**Issue by dexwiz** [sequelize/sequelize#4625]
I am trying to write a scope that returns select number of fields for serialization.

```javascript
module.exports = function(sequelize, DataTypes) {
  var User= sequelize.define('User', {
    field1: {
      type: DataTypes.JSON,
      allowNull: false,
      defaultValue: {}
    },
    field2: {
      type: DataTypes.JSON,
      allowNull: false,
      defaultValue: {}
    }
  }, 
  {
    scopes: {
      json: {
        attributes: ['field1', 'field2' ]
      }
    },
    classMethods: {
      associate: function(models) {
        User.hasMany(models.Role);
      }
    },
  });

  return User;
};
```

This works in combination with ```user.get({ plain: true})``` to produce a valid serialized object for exposing via an API. However, I cannot seem to find a way to to apply scopes to eagerly loaded models.

Tried
```javascript
User.scope(['json']).findById(user.id, {
      include: [{
        model: Role,
        scope: 'json'
      }]
    })
```
Does not apply any scope

And specific scopes
```javascript
User.scope(['userJson', 'roleJson']).findById(user.id, {
      include: [{
        model: Role,
        scope: 'json'
      }]
    })
```
Throws an error.

Is there is a there no way to apply scopes to eagerly loaded objects?

**Comment by dexwiz** [comment]
I was able to apply scopes, but it appears to only work for where clauses. Attribute filters do not seem to work. 

```javascript
User.scope(['json']).findById(user.id, {
      include: [{
        model: Role.scope('json')
      }]
    })
```

**Comment by mickhansen** [comment]
That might actually not be supported. A solution could be to build in support for `include.scope` which then applies options and scopes the model.

/cc @janmeier

**Comment by dexwiz** [comment]
Its in the unit tests, but only seems to apply to some scope types

https://github.com/sequelize/sequelize/blob/538a095e28de93b5a97c96f6a28554ddea84ab28/test/integration/model/scope/associations.test.js#L146

**Comment by janmeier** [comment]
`Role.scope` is the supported way for wheres, but yeah it might not support `attributes`

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/538a095e28de93b5a97c96f6a28554ddea84ab28/lib/model.js#L590 we do call injectScope for include.

https://github.com/sequelize/sequelize/blob/538a095e28de93b5a97c96f6a28554ddea84ab28/lib/model.js#L2408
Doesn't look like `$injectScope` supports attributes at all actually @janmeier?

**Comment by mickhansen** [comment]
Or actually it should copy attributes here: https://github.com/sequelize/sequelize/blob/538a095e28de93b5a97c96f6a28554ddea84ab28/lib/model.js#L2411
