### ISSUE TITLE
PostGIS Support [Proposal]

### ISSUE THREAD

**Issue by louy** [sequelize/sequelize#4630]
I know that PostGIS support has been on the roadmap for a while now, but it doesn't seem to be an easy task at all.
I'm willing to help you with that. My only issue is that I didn't know how to do it really. I mean how should the api look like? I'd appreciate it if you could help me with its architecture.

The issue is that postgis usage is hard to predict. For instance, one might prefer to always work with geojson. Should we add a "geojson" option for the GEOMETRY type then, and add [`ST_AsGeoJSON(column)`](http://postgis.net/docs/ST_AsGeoJSON.html) to the `sequelize.col` method? What about "saves"? How should we always use [`ST_GeomFromGeoJSON(data)`](http://postgis.net/docs/ST_GeomFromGeoJSON.html)?

Lastly, queries. For example the `ST_Within` function which checks whether a point is inside a polygon. Does this makes any sense?

```javascript
Model.findAll({
  where: {
    $or: [{
      geom: { $contains: { $point: [0, 1] } },
      // ST_Within( ST_MakePoint(1,0), `table`.`geom` )
    }, {
      geom: { $contains: { $point: [0, 1], $fuzziness: 10 } }, // or maybe `$distance`
      // ST_DWithin( ST_MakePoint(1,0), `table`.`geom`, 10 )
    }, {
      point: { $is_inside: { $col: 'geom' } },
      // ST_Within( `table`.`point`, `table`.`geom` )
    }, {
      point: { $is_inside: { $geojson: {/* some geojson */} } },
      // ST_Within( `table`.`point`, ST_GeomFromGeoJSON({}) )
    }],
  },
});
```

Let me know if I'm on the right path. I'm currently using `sequelize.fn` but that's not convenient. I currently expose the sequelize api to other services in inter-service communications but I don't want other services to know anything about the actual implementation of the database. Hence I don't want to use `sequelize.fn('ST_Within')`.

**Comment by louy** [comment]
I see that `ST_GeomFromGeoJSON` is always enabled already, but `ST_AsGeoJSON` is not.  Any reason for this?

**Comment by janmeier** [comment]
We already have an issue for geometry support, see https://github.com/sequelize/sequelize/issues/2839

Postgis has already been implemented via the `GEOMETRY` type.

We use `ST_GeomFromGeoJSON` on insert to convert the geojson to geometry - on select we parse and convert the binary geometry data to geojson https://github.com/sequelize/sequelize/blob/46a3cd4276d36634a4041fbdadfcb372768d7545/lib/dialects/postgres/data-types.js#L180-L183, so from the user's perspective they are always working with geojson, in all dialects.

The operators you proposed would make sense, but please add that discussion to the linked issue instead

**Comment by unibasil** [comment]
@janmeier, GeoJSON and WKT are not the same things.

**Comment by t0lik** [comment]
This code in postgres/data-types.js

`
GEOMETRY.parse = GEOMETRY.prototype.parse = function parse(value) {
    const b = new Buffer(value, 'hex');
    return wkx.Geometry.parse(b).toGeoJSON();
};
`

still does not support coordinate projection and produces GeoJSON without 'crs' property.
This can be resolved by passing options.shortCrs or options.longCrs to toGeoJSON function.

**Comment by papb** [comment]
Hi @t0lik, can you please open a new issue about it, following our template? Thanks
