### ISSUE TITLE
PostgreSQL autocommit

### ISSUE THREAD

**Issue by foxy0669** [sequelize/sequelize#4631]
It looks like PostgreSQL 9.4 has dropped the support for AUTOCOMMIT=OFF and PostgreSQL 9.5 has dropped support all together.

9.4
`ERROR:  SET AUTOCOMMIT TO OFF is no longer supported`

9.5
`ERROR:  unrecognized configuration parameter "autocommit"`

Is there anyway to bypass then when in a transaction?

**Comment by mickhansen** [comment]
I'm not quite sure why we originally have that setting at all.
The default for all dialects is OFF i believe, having it ON would generally be weird given you're working in a transaction (maybe in CLI settings it makes sense).

/cc @janmeier

**Comment by janmeier** [comment]
I've honestly never understood that setting  :D

See also https://github.com/sequelize/sequelize/issues/3568

As you say its off by default, and I can't see a setting where you'd want to enable autocommit within a transaction

**Comment by mickhansen** [comment]
@janmeier We should refactor so autoCommit is only set if there's an ACTUAL value (other than a default value). Don't see it as breaking.

**Comment by foxy0669** [comment]
I noticed the problem after installing 9.5. It looks to me the setting is on by default, however setting it to off would break by the look of it at least 9.1 upwards. Unless off would not issue the statement?

This is a default transaction with no options.

```
Executing (57de5f41-bd7e-494c-b1c8-53735742d7cc): START TRANSACTION;

Executing (57de5f41-bd7e-494c-b1c8-53735742d7cc): SET SESSION TRANSACTION ISOLAT
ION LEVEL REPEATABLE READ;

Executing (57de5f41-bd7e-494c-b1c8-53735742d7cc): SET autocommit = 1;
```

**Comment by janmeier** [comment]
@mickhansen Agreed

**Comment by DigitalSkyline** [comment]
Having the same issue in postgres 9.5.

How does one prevent "SET autocomit = 1;" ? Is there a workaround/fix?

Seems to be happening with findOrCreate, here's the error.

www-0 Executing (c04f3f10-9ac6-4271-a642-d4f19ef16300): START TRANSACTION;
www-0 Executing (c04f3f10-9ac6-4271-a642-d4f19ef16300): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
www-0 Executing (c04f3f10-9ac6-4271-a642-d4f19ef16300): SET autocommit = 1;
www-0 Executing (c04f3f10-9ac6-4271-a642-d4f19ef16300): ROLLBACK;
www-0 Unhandled rejection SequelizeDatabaseError: unrecognized configuration parameter "autocommit"
    at Query.formatError (D:\workspace\cardflip\node_modules\sequelize\lib\dialects\postgres\query.js:443:14)
    at null.<an

**Comment by mickhansen** [comment]
@DigitalSkyline Fix still needs to be written so it only sets auto commit if defined by user.

**Comment by DigitalSkyline** [comment]
Thanks, for now I just commented the line out in the library, works for now. ;)

**Comment by tkalfigo** [comment]
On Postgres 9.5beta2 and having the same issue. Is a fix coming soon? Manual commenting out of the offending line worked, but not very practical across many deployments.

**Comment by mickhansen** [comment]
@tkalfigo No fix has been made yet, so it will arrive when someone writes the code for a fix.

**Comment by stanjer** [comment]
Could you please create a new patchset release with that fix included? It's really blocking us.

**Comment by mickhansen** [comment]
@stanjer I trust you understand it's the christmas holidays for some people :) I'll try to see if i can't get to it sometime tomorrow, do ping me :p

**Comment by DigitalSkyline** [comment]
Any updates here?

**Comment by mickhansen** [comment]
@DigitalSkyline Gone through the issue? References PR has been merged a while back.

**Comment by DigitalSkyline** [comment]
Thanks, I updated to latest and seems to be working. However, now I seem to be getting a bunch of bluebird warnings: "Warning: a promise was created in a handler but was not returned from it" 

Anyways different issue. Thanks for responding so quickly!

**Comment by mickhansen** [comment]
http://bluebirdjs.com/docs/api/environment-variables.html

**Comment by DigitalSkyline** [comment]
Ah yeah that makes sense... thanks again!
