### ISSUE TITLE
Problem with getter and attributes

### ISSUE THREAD

**Issue by Americas** [sequelize/sequelize#4632]
I have a model defined roughly as:

```js
sequelize.define("modelName", {
        id       : {
            type       : DataTypes.STRING,
            field      : "mn_id",
            primaryKey : true,
            get        :  function() {
                let id = this.getDataValue("id");
                return id.slice(7);
            },
        }
    });
```

And I am running a find all against this model like such:
```js
ss.db.AdjustType.findAll({
    attributes : [["mn_id", "name"]],
});
```

this throws an error because it is attempting to use the getter but the data value is named "name" instead of "id", so it fails. Is there a way to map these values so the getter works?

I am using version 3.10.0

**Comment by mickhansen** [comment]
You'd have to name your attribute `name` or create a new attribute `name` using `DataTypes.VIRTUAL`.

**Comment by Americas** [comment]
But why is it attempting to use the getter for "id" then?

**Comment by mickhansen** [comment]
Because you are asking for the value i assume. (Using .get() or .toJSON() will automatically loop all attributes and use getters).

**Comment by Americas** [comment]
OK, so the problem is that any getter will be called even if that getter's attribute is not present in the instance? Can I make the getter return nothing? will this make it so that the attribute does not show up after get()ing it?

**Comment by mickhansen** [comment]
Actually looking at the code the getter shouldn't be called unless there's a value for it, but there might be a bug. (https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L215)

In any case your case here is a slightly odd.

**Comment by janmeier** [comment]
`getDataValue` takes the value from the underlying, plain results object, which just stores whatever it got from the database (in this case an aliassed column) - I don't think there is any way to solve this, you'll just have to handle that it might have another name in the getter.

The getter should not be called in the first place though :D  The problem is [here](https://github.com/sequelize/sequelize/blob/5a046e3ea6db54d4ee461d94a058e075accf5d2d/lib/instance.js#L206) since the field has a custom getter its invoked regardless. If its a custom getter for a field it should only be invoked if that field was actually selected. I believe we already have an open issue for something similar, but i can't find it now..

**Comment by Americas** [comment]
@mickhansen yes it was an odd case, I had to refactor a part of my codebase, and to avoid doing more than what was necessary, I was trying to keep the names consistent. Ended up just refactoring everywhere, so this won't be an issue now :laughing: 

@janmeier that would be my suggestion as well. But it would not have solved my problem :cry:

**Comment by crispkiwi** [comment]
I've just come across this issue on perhaps a more common use case.

Consider a virtual field, longitude, with a custom getter.

```javascript
sequelize.define("Site", {
    name: { type: Sequelize.STRING },
    longitude: {
        type: Sequelize.VIRTUAL,
        get: function () {
            return this.getDataValue('geoPointLocation').coordinates[0];
        }
    },
    geoPointLocation: {
        type: Sequelize.GEOMETRY('POINT'),
        defaultValue: DEFAULT_GEOPOINT,
    }
});

```

I only select id and name
```javascript
Site.findAll({
    attributes : ['id', 'name']
});
```

Serializing the result will throw an error
```javascript
resp.json(sites); // will toJSON() 
// TypeError: Cannot read property 'coordinates' of undefined
```

Checking for undefined in the getter obviously fixes this, but it would be nice if the getter wasn't called altogether.

In a case where a virtual getter always returned a defined value, it would unexpectedly end up in results from queries that requested only specific attributes.

**Comment by mickhansen** [comment]
@crispkiwi https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L734

**Comment by crispkiwi** [comment]
@mickhansen the problem here is that the virtual field _isn't_ present in attributes but the getter is still being called. Unless I'm misunderstanding the documentation dependant fields will be populated only if the virtual _is_ present in attributes?

**Comment by mickhansen** [comment]
True, you need to atleast request the virtual.

**Comment by crispkiwi** [comment]
Which is undesirable in situations where you don't want the virtual.
You would have to do one of the following
A) Remember to include all virtuals in the every query attributes
B) Expect undefined properties in all getter functions
C) Have sequelize not call getters on virtuals when they are not requested in attributes

**Comment by mickhansen** [comment]
@crispkiwi Personally i lean towards B. But please open an issue about C and we can discuss a solution

**Comment by greghart** [comment]
Something to note in deciding whether to approach solution C. Even were you to follow solution B, you'd still end up with un-wanted properties in your resulting object

```javascript
Sequelize = require('sequelize')
db = new Sequelize('test', null, null, {dialect: 'sqlite'})

Test = db.define("test", {
    name: { type: Sequelize.STRING },
    first_name: {
        type: Sequelize.VIRTUAL,
        get: function () {
            if (this.getDataValue('name') !== undefined) {
                return this.getDataValue('name').split(' ')[0]
            } else {
                return undefined;
            }
        }
    }
});


Test.sync()
.then(function(){
    return Test.create({
        name: 'Billy Billyson'
    })
})
.then(function(){
    return Test.findOne({attributes: ['id']})
})
.then(function(user){
    console.log(user.get()) // {first_name: undefined ...} <- unexpected property
})
```

Seems to contradict expected behavior as outlined https://github.com/sequelize/sequelize/pull/1460

**Comment by ErnestBrandi** [comment]
I'm not sure what has been decided about that issue. Customs getters still are called even if a specific list of attributes is set in a `findAll({})` call for instance (not dealing with VIRTUAL types here). So what, do I have to check in every getter for undefined values ?!

**Comment by tqcc** [comment]
`    gcs_file_path: {
      type: new DataTypes.VIRTUAL(DataTypes.STRING, ['name']),
      get: function() {
        return 'gs://bucket/' + this.name;
      }
    },`

this works for me
