### ISSUE TITLE
Allow to specify inverse foreignKey name in a one-way 'belongsToMany' (N:M) association 

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#4634]
Currently it is required to add an association on each model to map a many to many relationship if the join table has non-default FK names. It is not always desired on the object model because sometimes the asociation would only makes sense in one side of the relation. I would like something as:

```javascript
var Sequelize = require('sequelize');
var sq = new Sequelize(null,null,null, { 
	dialect: 'sqlite',
	storage: './test.sqlite', 
	define: {timestamps: false}
});

var User     = sq.define('User');
var Property = sq.define('Property');

User.belongsToMany(Property, {
   through   : 'UserProperty',
   foreignKey: 'usuario_correlativo',
   //inverseForeignKey: 'propiedad_correlativo'   <-- Something like this
});

//I don't want this association but is necesary to 
//specify FK custom names, otherwise it would create
//a third field named "PropertyId" in the join table 
Property.belongsToMany(User, {
   through   : 'UserProperty',
   foreignKey: 'propiedad_correlativo'
});

sq.sync({force: true}).then(function(){
	console.log('Test database created!');
})
```

In [bookshelf](http://bookshelfjs.org/) this is [done](http://bookshelfjs.org/#Model-instance-belongsToMany) with an argument "otherKey" to belongsToMany

**Comment by mickhansen** [comment]
Sequelize supports `otherKey` aswell, have you given it a shot?

I was going to refer to the documentation: http://docs.sequelizejs.com/en/latest/api/associations/belongs-to-many/ but it doesn't look like it actually includes the options for the call, @janmeier?

**Comment by hendrul** [comment]
Reading the tests I realized it, sorry :)

**Comment by hendrul** [comment]
#3348

**Comment by janmeier** [comment]
@hendrul The link is not inactive, it's just a header for the points below.

**Comment by hendrul** [comment]
@janmeier can you show me a way to navigate to http://docs.sequelizejs.com/en/latest/api/associations/ without writing it in the address bar?

**Comment by janmeier** [comment]
Click on overview just below it :)

**Comment by hendrul** [comment]
I'm scratching my head right now!, I click overview before and it doesn't take me there... I think am just getting nut

**Comment by philipimperato** [comment]
This is such a glaring feature gap. I now can never use a many to many relationship outside of the original model.
