### ISSUE TITLE
Why doesn't db:seed found seeders?

### ISSUE THREAD

**Issue by moslemezzati** [sequelize/sequelize#4635]
I create seeder file after init:seeders.
this is the seeder file:

module.exports = {
  up: function (queryInterface, Sequelize) {
    queryInterface.bulkInsert( 'Countries', [
      {
        name: 'USA',
        direction: 'rtl',
        acronym: 'USA',
        money_id: 1,
        flag_picture_url: 'Images/flags/United_States_of_America.png'
      }
    ])
  },
  down: function (queryInterface, Sequelize) {
      return queryInterface.bulkDelete('Countries', null, {});
  }
};
But when I run "sequelize db:seed" it doesn't found seeders files and shows this message:
Sequelize [Node: 0.12.0, CLI: 1.9.1, ORM: 3.11.0, pg: ^4.4.2]

Loaded configuration file "config\config.json".
Using environment "development".
Using gulpfile ~\AppData\Roaming\npm\node_modules\sequelize-cli\lib\gulpfile.js
Starting 'db:seed'...
Finished 'db:seed' after 165 ms
No seeders were found.

How could I execute my seeders files?

**Comment by janmeier** [comment]
Please post migration related issues to sequelize/umzug

**Comment by moslemezzati** [comment]
OK THANKS AGAIN

**Comment by emerak** [comment]
@moslemezzati did you solve this??
