### ISSUE TITLE
Transitive Persistence (Cascading Saves, Updates and Deletes) and Offline concurrency.

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#4639]
Maybe there's a reason to this but after searching at several data mapper implementations for nodejs
I realized that none of them provides implementation of the [UnitOfWork](http://martinfowler.com/eaaCatalog/unitOfWork.html) pattern. The point of ORM is to abstract away low level storage-efficiency oriented relational model and operations, to the more conceptual and bussiness oriented Object model, but having the programmer keeping track and worring about the referential order in which they need to do things is a gap that needs to be filled by an ORM implementation.

The main points of Unit Of Work are:
1. As soon as you start doing something that may affect a database, you create a Unit of Work to keep track of the changes. Every time you create, change, or delete an object you tell the Unit of Work.
2. Check for inconsistent reads by verifying that none of the objects changed on the database during
    the business transaction. 
3. When it comes time to commit, the Unit of Work decides what to do. It opens a transaction, does any concurrency checking (using [Pessimistic Offline Lock](http://martinfowler.com/eaaCatalog/pessimisticOfflineLock.html) or [Optimistic Offline Lock](http://martinfowler.com/eaaCatalog/optimisticOfflineLock.html) ), and writes changes out to the database.  
4. Application programmers never explicitly call methods for database updates. This way they don't have to keep track of what's changed or worry about how referential integrity affects the order in which they need to do things.

**Comment by hendrul** [comment]
Following with #1393. What I see as the most wanted point of UoW pattern for sequelize is the cascading of operations for a graph of related instances. The programmer should be released from this task, without being aware of the order the operations should be performed considering this information already exists on the mapping. What prevents all node's ORM projects from implementing this pattern?. Excuses by my ignorance, I know there is a great effort to improve sequelize and I really appreciate it.

**Comment by hendrul** [comment]
Other important point is what's the recommended way to handle business transactions? 
how check the consistency of data edited offline before it is commited to BD?
Is it viable to include support on sequelize for this?

**Comment by mickhansen** [comment]
I don't have a great deal of insight to how UoW is implemented on other platforms.
But for Node.js i'd say a major issue is how concurrency is handled, we have no way of knowing whether or not a call should go in a specific unit of work (well we might with CLS, but the user would have to wrap evertyhing in a function anyways).

As for offline locks on transaction commit, if you hold all actual calls untill you're ready to commit we could implement something i suppose.

**Comment by hendrul** [comment]
In Hibernate Java, a "Session" is a context that manages entities (Instances) and it is an entrypoint to querying, saving, updating, merging back unmanaged entities into the context, deleting, evicting (removing entities from context), etc, and almost anything revolves around this facade. But one of its main responsabilities is to serve as a cache of retrived in-memory entities and keeps the uniqueness of them (Identity Map pattern) avoiding the load of many versions of the same database registry in memory, it keeps a one to one relation between an entity and its registry on the DB. 
The point is that this object keeps track of changes not only on atributes but also on the associations (added, removed, associated entities) and when the time comes to commit it saves all those changes in the managed entities at once, but the part that is really important to programmers is that from mapping metadata it knows how to travel recursively all the entities graphs and depending on the "cascade" policy placed on the metadata of an association it operates over changes on related instances. 

Lets concentrate on the most important feature first: Transitive persistence: In sequelize you need to add an option attribute for associations in which the programmers choose how sequelize should handle the cascading for them, sequelize should take a root Instance and recursively apply changes in the correct order depending on the kind of association and the cascade policy specified in the mapping.

**Comment by hendrul** [comment]
One problem I can see is how does sequelize know what associated instances needs to be deleted, created, or updated when traversing the object graph. What about adding some semantics in the instances like having an id present on the instance means that it exists and it needs to be save, but if the id is not present then proceed to creating the instance, and when an associated instance was deleted sequelize doesn't removed it from the associated object but instead deletes all attributes of the instance keeping the id only which at the time of cascading it is a delete. 
What would be the issues with this solution?

**Comment by janmeier** [comment]
Interesting discussion here! I'll try to answer some of the points. Sorry if this seems a bit scattered, I'm mostly just throwing around thougts

> Other important point is what's the recommended way to handle business transactions? 
how check the consistency of data edited offline before it is commited to BD?
Is it viable to include support on sequelize for this?

* Optimistic. Could probably be pretty easily solved by checking the `updatedAt` timestamp. 
* Pesimistic. A `locked` column could be added to the table, and the uow / or a hook could check if that column was set when selecting. One thought though, was happens if the locking uow fails, and the row is never unlocked? Maybe `locked` could be a timestamp and you could define when it should time out, or users would manually have to break the lock by setting `locked = null`

> and depending on the "cascade" policy placed on the metadata of an association it proceeds or not to apply the required operations on the related instances.


>Lets concentrate on the most important feature first: Transitive persistence: In sequelize you need to add a "cascade" option attribute for associations in which the programmers choose which operations sequelize are allowed to apply on that association when cascading.

Not really sure I understand this - what does cascade have to do with this? We already have support for on delete / update  cascade / delete / do nothing via db constraints - or are you talking about something else?

Now for some API thoughts:

```js
var uow = new Sequelize.UnitOfWork();

var user = yield uow.findOne(User, { where: { ... }}); 

user.set('foo', 42);
uow.save(user);

// Would be more pretty to just call user.getComments - but the comments should be included in the cache to follow the pattern
var comments = yield uow.findAll(User.associations.Comments, user);
uow.destroy(comments[0]);

var post = Post.build(...)
uow.save(User.associations.Posts, user, post); // equivalent to calling user.addPost
```

So far I've looked at [doctrine](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html) and [hibernate](https://docs.jboss.org/hibernate/orm/3.3/reference/en/html/transactions.html) - any other examples of how other orms do it?

**Comment by hendrul** [comment]
> Optimistic. Could probably be pretty easily solved by checking the updatedAt timestamp

Not so sure timestamps should be use for instance snapshot version as timestamps are base on the machine clock and they are too unreliable for versioning snapshots. I think there should be a version column for this.

> Not really sure I understand this - what does cascade have to do with this? We already have support for on delete / update cascade / delete / do nothing via db constraints - or are you talking about something else?

  Sequelize actually defer the cascading to the DB. First DB Cascades works in one direction, e.g. you can't say, delete the whole hand when deleting a single finger, you can only say, delete the fingers if I remove the hand. Maybe DB onDelete is enough for most cases, but when updating (or inserting) you can't relay on "onUpdate" which cascades when the primary key changes. Currently you need to manually operate on each changed instance and in the correct order depending on referential constrains. In #3386 I can see a new feature been developed which allows you to save a graph of instances specifying (manually) the relations which you want to save cascade, but apparently updating is harder to implement @mickhansen says. What I mean with cascade is propagating the updates, deletes, or inserts by Sequelize navigating the cached objects graph. 

> Now for some API thoughts:

The unit of work is the entrypoint for retrieving persistent instances which gets cached and managed in the context of the unit of work til it gets destroyed, cleaned, or the instance get evicted. After you retrieve instances you can navigate the object graph (eagerly or lazily), make changes, and in the end you flush the context with all changes to the DB.

There are a couple of ways you can delete an instance, calling the destroy method in the instance, using the destroy function in the context passing the instance as argument, or simply removing it from the collection of an association 1:M or setting the relation property to null in M:1 relations. This operations should trigger instance state transitions. In Hibernate an instance could be in four posible states:

 * **Transient:** Objects instantiated using the new operator aren’t immediately persistent. Their state is transient, which means they aren’t associated with any database table row
 * **Persistent:** Is an entity instance with a database identity, and is managed by the persistence context. 
 * **Removed:** You can delete an entity instance in several ways: For example, you can remove it with an explicit operation of the context. It may also become available for deletion if you remove all references to it
 * **Detached:** state is no longer guaranteed to be synchronized with database state; they’re no longer attached to a persistence context.

I make some changes to the sample code above

```javascript
var uow = new Sequelize.UnitOfWork();

var user = yield uow.findOne(User, { where: { ... }}); 

user.set('foo', 42);

//You can navigate the relations and these objects became managed by the context
//and every change in attribs and relations is registered in the uow
var comments = user.getComments();  //<- returns a managed collection of Comments
comments.remove(0);  //<- Collections have behavior and trigger instance state changes
comments[0].set('bar', 1);

//A transient post
var post = Post.build(...);
//now gets managed (not immediately created)
user.addPost( post );

//Just flush the UoW and all changes will be applied in referentially
//correct order in the last moment, keeping locks for shorter times.
uow.flush();
uow.close(); //<- Finishing the unit of work
```

> So far I've looked at doctrine and hibernate - any other examples of how other orms do it?

I use [Hibernate](https://en.wikipedia.org/wiki/Hibernate_(Java)) as reference not only because I have some experience with it but because it is very mature and active project, full of features, and ported to other non-java platforms as [NHibernate](https://en.wikipedia.org/wiki/NHibernate) for .Net or [doctrine](http://www.doctrine-project.org/) (which is heavily inspired in Hibernate see project description) for PHP. Adobe also integrated Hibernate into version 9 of ColdFusion (which runs on J2EE app servers) with an abstraction layer of new functions and syntax added into CFML. It became the reference implementation for the Java Persistence Arquitecture (JPA) specification. It have a lot of features that would be great to borrow from and add to sequelize.

**Comment by akaRem** [comment]
It would be great if fetched object will remember their transaction context and disallow mixing different UoWs.

```
var t1 = sequelize.transaction();
var user1 =  yield t1.models.User.findOne(..);  // in transaction t1
var groups1 = yield user1.getGroups(); // in the same transaction t1

var t2 = sequelize.transaction();
var user2 =  yield t2.models.User.findOne(..);  // in transaction t2
var groups2 = yield user2.getGroups(); // in the same transaction t2

yield user2.setGroups(groups2); // setting entities from t2 into t1 ->  error thrown
```

**Comment by hendrul** [comment]
Objects retrieved from one UoW should be considered in detached state on another UoW, this means it is not guaranteed to be synchronized with the DB and is going to be synchronized when you flush/commit/save the unit of work. You may merge that foreign object into another UoW by "merging" it into, this way the UoW now keeps track of this object as if it were taken from that same UoW.

**Comment by akaRem** [comment]
@hendrul How do you thing `uow#marge` should work?
I thing there could be some problems with entities which are travelling from one uow to another.

Here is example

Setup.
``` js
var uow1 = new Sequelize.UnitOfWork();
var user1 =  yield uow1.User.findOne({id:1});
var groups1 = yield user1.getGroups();

var uow2 = new Sequelize.UnitOfWork();
var user2 =  yield uow2.User.findOne({id:2}); 
var groups2 = yield user2.getGroups(); 
```

Merged entities are deleted
``` js
yield uow1.merge(groups2);
yield user1.setGroups(groups2);
yield groups2.delete(); 

uow1.flush(); 
uow2.flush();  
uow1.end();
uow2.end();
```
In context of which uow groups2 are deleted?

Things became more complicated with rolling back one of uow.

``` js
yield uow1.merge(groups2);
yield user1.setGroups(groups2);
yield groups2.delete(); 

uow1.flush(); 
uow2.rollback();  
uow1.end();
uow2.end();
```
What happened with groups at this point?
Are they deleted or not?

And the last example, the most difficult.
``` js
var uow1 = new Sequelize.UnitOfWork();
var user1 =  yield uow1.User.findOne({id:1});

var uow2 = new Sequelize.UnitOfWork();
var user2 =  yield uow2.User.findOne({id:1}); // the same user

user1.setName("John");
user2.setName("Stan");

uow2.merge(user1);
uow1.merge(user2);

// then I accidentally start to change duplicates of already managed entities
var user3 =  yield uow2.User.findOne({email: "user@example.com"}); // the same user, again, new query
user3.setName(user2.getName());

user2.setName("Clark");

uow1.rollback();
uow1.end();
uow2.flush();
uow2.end();
```
What is the name of the user will be at the end?
How to handle repeated reading of the same data?
This example looks very synthetic, but IRL similar things could happen when, for example, you calculate access policy for complicated enterprise systems.

Proposed solution: stay with transactions.
Let's say we have READ_COMMITED isolation level
``` js
var t1 = sequelize.transaction();
var t2 = sequelize.transaction();

var user1 = yield t1.User.findOne({id:1});  // name -> Alex
var user2 = yield t2.User.findOne({id:1});  // name -> Alex

user1.setName("John");  // name -> John, not saved, not commited
user2.setName("Stan");  // name -> Stan, not saved, not commited

var user3 = yield t2.query(user1); // name -> Alex, not saved, not commited
// but if we save and commit user1, here will be John and in final John too

// We may attach transaction as property for fetched objects like this
// user1.transaction -> t1
// user2.transaction -> t2
// user3.transaction -> t2
// ... and check when trying to combine objects which are in different transactions
// user2.setLawyer(user1) -> error

yield user2.save(); // name -> Stan, saved in t2, not commited
yield user1.save(); // name -> John, saved in t1, not commited
yield user3.save(); // name -> Alex, saved in t2, not commited

yield t1.commit(); // now name is John
yield t2.commit(); // now name is Alex again
```

This behavior is well known and familiar to lots of developers.
This behavior is more clear and easier to implement.

**Comment by hendrul** [comment]
1. user1 gets updated with group2 then uow2 remove it.
2. It is useless a rollback operation in the uow because at this point the uow hasn't executed any operation, it waits til the last moment to commit all changes, if you want to rollback then just don't flush, destroy the uow.
3. UoW! It looks like playing "watch the ball" game,  each uow is gonna be synchronized once with the actual state on DB of the entity being merge in order to know which operations needs to be performed when flushing (i.e. what has changed in relation to the DB registry). read below...
 
The same cases you posted here could also happen with transactions with the diference that uow doesn't flush every change to the database inmediately, but it keeps track of them to be executed later (i.e the transaction ocurrs at the end). If the database changed after a merge, then this is handled by concurrency check mecanism which will yield the error you felt should be thrown

**Unit of work is a higher level and proved solution which offers more:**
- You don't have to worry about referential integrity when persisting changes in a composed instance, you don't have to manually save every instance in the right order, you just pass the compose instance to the uow and it does the rest for you.
- Transactional write behind is delaying the execution of a transaction til the last second avoiding keeping locks for too long.
- At commit time the unit of work checks for concurrency locks before it writes the changes to the database.

**Conclusion:** If you grab a hammer the wrong way when placing a nail the result is uncertain, when using a tool you should handle it correctly and know what you're doing, the use cases you've placed seems improbable, it's non-sense interleaving two transactions that way, and that without mentioning you miss promises which are going to make it look even more weird, honestly I would never do something like this, maybe you could show me a more real use case showing where this move could be valuable.

**Comment by hendrul** [comment]
@janmeier to place a DELETE cascade constraint you need to declare a foreign-key on de DB but in the OO model which is higher level , you want to be able to associate objects through virtual relations were no foreign key constraint exists on the DB; one example of such relations are the main use case for [association scopes](http://docs.sequelizejs.com/en/latest/docs/scopes/#associations) which are "useful when implementing polymorphic associations", and there is no foreign key with cascades on the DB.

**Comment by manuc66** [comment]
This package seems to have implemented UnitOfWork on top of sequelize: https://github.com/BibbyChung/sequelize-adapter
