### ISSUE TITLE
Belongs-To-Many "add" method with similar column names

### ISSUE THREAD

**Issue by sitbackmedia** [sequelize/sequelize#4642]
So I have three models, just to keep it simple

User {
id,
username
}

Social {
id,
title,
order
}

SocialUser {
userId,
SocialId,
status,
order
}

When I try this I get no errors:
db.Social.addUser(db.user, {
status: active
});

But when I add "order", which is a column in both the Social table and SocialUser table, I get errors.
db.Social.addUser(db.user, {
status: active,
order: 1
});

How to update a join table with similar columns as it's parent tables?

**Comment by subjectix** [comment]
The issue isn't related to the fact that `Social` has `order`, the `options` argument holds arguments passed to `through.findAll`, `bulkCreate` and `update` ([see](http://docs.sequelizejs.com/en/latest/api/associations/belongs-to-many/#addassociationnewassociation-options-promise)). So i guess order shouldn't be number when passed to one of these functions. Try renaming it with something else. something not reserved by any options passed to these functions. 
This is a serious api bug, it needs to be addressed somehow -_-

**Comment by mickhansen** [comment]
See https://github.com/sequelize/sequelize/issues/4597

**Comment by sitbackmedia** [comment]
Thank you for the quick response!! I will change the column names
