### ISSUE TITLE
Querying doesn't lazy create tables like creating models

### ISSUE THREAD

**Issue by OscarGodson** [sequelize/sequelize#4643]
```
Executing (default): SELECT `id`, `email`, `password`, `verified`, `created_at`, `updated_at` FROM `users` AS `user` WHERE `user`.`email` = 'oscar@getpiggybank.com' LIMIT 1;
Unhandled rejection SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'example.users' doesn't exist
```

I get this error when I run code that queries tables that don't exist yet. To get around this error I have to remove the existing user check (checks to see if the email already exists), create a user, then add the check back. I tried to add `sync()` before the `.findOne` but that just gave an error that sync() had no `findOne` method.

Is there a way to install handle either install all the tables at once _or_ create them when querying?

**Comment by mickhansen** [comment]
`sequelize.sync()` will create all tables if they don't exist.

**Comment by OscarGodson** [comment]
Thanks! I'll give it a try and report back if it doesn't work.
