### ISSUE TITLE
how to update like this?

### ISSUE THREAD

**Issue by peze** [sequelize/sequelize#4644]
how can i use function update to get this sql 
<pre>
UPDATE mytable 
    SET myfield = CASE id 
        WHEN 1 THEN 'value'
        WHEN 2 THEN 'value'
        WHEN 3 THEN 'value'
    END
WHERE id IN (1,2,3)
</pre>

**Comment by janmeier** [comment]
Only using a raw query unfortunately - not sure what the javascript syntax for that would look like either
