### ISSUE TITLE
Unrecognized data type for field when setting a virtual field

### ISSUE THREAD

**Issue by ssmlee04** [sequelize/sequelize#4645]
I created a event Schema and do sequelize.import from somewhere else. In that schema I want to create a virtual getter / setter for a field `is_ongoing_campaign`. When I try to code it like this it gives me an error message.  Does anyone know what might be happening?  Thanks. 

My sequelize version is :3.11.0 
sequelize-mylsq version is: 1.7.0.. don't know if this is related though..

    module.exports = function(sequelize, DataTypes) {

    var Event = sequelize.define('Event', {
        campaign_start: DataTypes.DATE,
        campaign_end: DataTypes.DATE,
        is_ongoing_campaign: {
          type:DataTypes.VIRTUAL,
          get: function() {
            return this.get('createdAt') > Date.now() - (7 * 24 * 60 * 60 * 1000)
          }
        }
      }
    return Event;
    };

**Comment by janmeier** [comment]
Which error message?

**Comment by mickhansen** [comment]
`sequelize-mysql` is defunct and should not be used, especially not in combination with standalone `sequelize` (just FYI).

**Comment by ssmlee04** [comment]
I see. so it appears that `sequelize-mysql` is using `sequelize @ 1.7.x` as dependency so that's why `DataTypes.VITRUAL` is null.  That should be the problem thanks.
