### ISSUE TITLE
Documentation: Hook Parameters

### ISSUE THREAD

**Issue by dexwiz** [sequelize/sequelize#4649]
So different hook callbacks seem to provide different parameters, specifically the beforeSync, afterSync. They pass a callback function as the second parameter of the hook function, that must be called to end the function. This should be documented somewhere.

**Comment by mickhansen** [comment]
All hooks have a callback as the last parameter for legacy reasons. The reason why it's second argument on the sync hooks is because they only have a single argument, `options`.

If you leave your function at a single argument length you can still return a promise like usual.
