### ISSUE TITLE
duplicate foreign key column

### ISSUE THREAD

**Issue by jairoGilC** [sequelize/sequelize#4650]
I have a node project using sequelize, and have the following two tables

    "use strict";

    module.exports = function(sequelize, DataTypes) {
      var asset = sequelize.define("asset", {
        description   : DataTypes.STRING,
        maker         : DataTypes.STRING,
        model         : DataTypes.STRING,
        serialNumber  : DataTypes.STRING,
        barcode       : DataTypes.STRING,
        account       : DataTypes.INTEGER,
        usefulLife    : DataTypes.INTEGER,
        downtimeCosts : DataTypes.FLOAT,
        purchasePrice : DataTypes.FLOAT
      }, {
        classMethods: {
          associate: function(models) {
            /*Un estado es de muchas categorias, y no se puede borrar si tiene un activo asociado*/
            asset.belongsTo(models.assetState, {
              onDelete: "RESTRICT",
              foreignKey: {
                allowNull : false,
                name      : 'assetState_id'
              }
            });
          }

        }
      });

      return asset;
    };

    "use strict";

    module.exports = function(sequelize, DataTypes) {
      var assetState = sequelize.define("assetState", {
        state: DataTypes.STRING,
        assetState_id: {
               type: DataTypes.INTEGER,
               primaryKey: true,
               autoIncrement: true
        }
      }, {
        classMethods: {
          associate: function(models) {
            assetState.hasMany(models.asset)
          }
        }
      });

      return assetState;
    };

When i check the asset tables in postgres I have two columns ("assetState_id", "assetState") I suppose that is because i give the name of the relation explicitly, as I can do to not generate the column "assetState"?

**Comment by mickhansen** [comment]
`assetState.hasMany(models.asset)` will need to have the same foreign key options as the belongsTo call.
