### ISSUE TITLE
Inside LIKE %Russian% query is not working

### ISSUE THREAD

**Issue by rianby64** [sequelize/sequelize#4651]
```javascript
var query = "SELECT `id`, `name`, `comments`, `createdAt`, `updatedAt` FROM `categories` AS `categories` WHERE `name` LIKE '%ЧТО%' OR `comments` LIKE '%ЧТО%'";
SLRMdb.query(query, { type: Sequelize.QueryTypes.SELECT})
.then(function(entries) {
  console.log(entries);
});
```
If I put something in english then Sequelize returns me the correct result.
But if put something in russian then it returns an empty array.

Please help to solve.
I'm using the last version 3.12.0 under node 0.10.36 (CentOS). Even updating node up to 0.12.1 still doesn't work. Dialect = sqlite3

Thanks a lot!

**Comment by rianby64** [comment]
```javascript

  var Model = sequelize.define('categories', {
    name: Sequelize.TEXT,
    comments: Sequelize.TEXT
  }, {
    freezeTableName: true // Model tableName will be the same as the model name
  });

...

      var search = {}, ors = [];
      if (req.query) {
        if ((req.query.search) && (req.query.search.length > 0)) {
          for (var attr in Model.attributes) {
            if (attr === 'id') continue;
            ors.push(Sequelize.where(
              Sequelize.fn('UPPER', Sequelize.cast(Sequelize.col(attr), 'TEXT')),
              { $like: '%' + req.query.search.toUpperCase() + '%' }
            ));
          }
          search = Sequelize.or.apply(undefined, ors);
        }
      }
      
      return Model.findAll({ where: search }).then(function(entries) {
        console.log(entries);
        res.json(entries);
      });
```
In fact, the code above generates a query that I can run in Sqlite manager. The result is the expected. But Sequelize is working in a different way.

**Comment by janmeier** [comment]
Seems to work fine for me

```js
sequelize.sync({
  logging: console.log,
  force: true
}).bind({}).then(function() {
  return Model.create({
    name: 'ЧТОЧТОЧТО',
    comments: 'ЧТОЧТОЧТО'
  });
}).then(function() {
  return Model.findAll({
    where: { $or: {
    name: { $like: '%ЧТО%' },
    comments: { $like: '%ЧТО%' }
  }}
  });
}).then(function(rows) {
  console.log(rows)
})
```

Outputs one row. Please create a pull request with a [SSCCE](http://sscce.org/) if you still experience this problem

**Comment by rianby64** [comment]
Thanks! All works as expected. But I've one last question>
If I want to search by UPPER a CASTed column to Text using LIKE, can you please write a simple example?
I know that something else I've to add to your example
```javascript
return Model.findAll({
    where: { $or: {
    name: { /*UPPER(CAST(name, TEXT))*/ $like: '%ЧТО%' },
    comments: { /*UPPER(CAST(comments, TEXT))*/ $like: '%ЧТО%' }
  }}
```
But I can't imagine it.
Thanks a lot in advance

**Comment by janmeier** [comment]
Probably something along the lines of 
`    name: sequelize.where(sequelize.fn('upper', sequelize.fn('cast', sequelize.col('name'), 'text')), { $like: '%ЧТО%' })`

**Comment by rianby64** [comment]
Works nice under PostgreSQL. But if you try the same for Sqlite3 then the result won't be the expected. Thanks a lot @janmeier for your help!
