### ISSUE TITLE
Complex Mappings and Associations From Legacy Tables

### ISSUE THREAD

**Issue by bitsoflogic** [sequelize/sequelize#4652]
I'm open to any version of Sequelize for this problem (mssql dialect).

I have a table (on SQL Server 2008) that is denormalized like so:

```
Table: PhoneNumbers
Field: Partial varchar(8)   -- 123-1234
Field: [Data]               -- Refers to 800-123-1234 Data
Field: [888Data]            -- Refers to 888-123-1234 Data
etc

Table: OtherTables
Field: PhoneNumber varchar(10)   -- 8001231234

Table: SomeTables
Field: [NPA] varchar(3)    -- 800, 888, etc
Field: [Partial] varchar(8) -- 123-1234
```

I have 2 goals here:

1. I would like to create normalized objects from the denormalized table, `PhoneNumbers`.  Every row represents 6 phone numbers, which would be great to access directly.
2. I would like to create associations between these tables.

The`PhoneNumbers` table cannot change as there is a ton of business rules in an Access database that maps directly to it.

Is it possible to solve this problem with Sequelize?  I am searching for a database solution [here](http://dba.stackexchange.com/q/117419/64128) in the meantime.  If I can normalize the `PhoneNumbers` table (via replication or otherwise), I feel pretty confident that Sequelize is capable of the associations.

**Comment by mickhansen** [comment]
I'm not sure i quite get your table schema. OtherTables and SomeTables refer to PhoneNumbers how?
Sequelize does not support multi column foreign keys, seems like that might be needed here.

**Comment by bitsoflogic** [comment]
To answer your question, it's a nightmare atm and looks something like this:
```
PhoneNumber
Partial: '123-1234'
Data:    'asdf'
888Data: 'qwer'
877Data: 'zxcv'

OtherTables
PhoneNumber: '8001231234' -- Joining this to PhoneNumber and its "Data" is "asdf"
PhoneNumber: '8881231234' -- Joining this to PhoneNumber and its "Data" is "qwer"
```

I thought this would be too complex for Sequelize.  **Can Sequelize keep two tables in sync via hooks?** I may be able to replicate the `PhoneNumbers` table to a normalized version and alter `SomeTables` so everything can join on `PhoneNumber` (design at bottom).

Then, with Sequelize, I'd like to do something like this:
```
var PhoneNumber = sequelize.define('PhoneNumber', ...Partial, Data, 888Data, 877Data... );
var PhoneNumberNormalized = sequelize.define('PhoneNumberNormalized ', ... {
  hooks: {
    beforeCreate: function() {
      // Manually map the normalized object to the denormalized table 

      // Pseudocode
      if ( left(this.PhoneNumber, 3) === '800' ) {
        var dataField = 'Data'
      } else { 
        var dataField = left(this.PhoneNumber, 3) + 'Data';
      }

      PhoneNumber.create(...);
     
    },
    ... 
  }
});
```

```
Table: PhoneNumbers
Field: Partial varchar(8)   -- 123-1234
Field: [Data]               -- Refers to 800-123-1234 Data
Field: [888Data]            -- Refers to 888-123-1234 Data

Table: PhoneNumbersNormalized
Field: PhoneNumber varchar(10) -- 8001231234
Field: Data 

Table: OtherTables
Field: PhoneNumber varchar(10) -- 8001231234

Table: SomeTables
Field: PhoneNumber varchar(10) -- 8001231234
Field: NPA varchar(3) -- 800
Field: Partial varchar(8) -- 123-1234
```

**Comment by mickhansen** [comment]
Hooks always run, assuming not disabled and assuming all calls go through sequelize.
As for whether or not they can keep your table in sync, i propose you write tests with high amounts of concurrency, it's going to be up to your code really ;)

**Comment by bitsoflogic** [comment]
Thanks for the feedback!
