### ISSUE TITLE
 TypeError: self.$expandAttributes is not a function

### ISSUE THREAD

**Issue by novacrazy** [sequelize/sequelize#4653]
Just upgraded to the latest version (3.12.0) and I've been met with this error:

```
 TypeError: self.$expandAttributes is not a function
      at conformOptions (example.com/node_modules/sequelize/lib/model.js:245:10)
      at conformInclude (example.com/node_modules/sequelize/lib/model.js:300:5)
      at example.com/node_modules/sequelize/lib/model.js:261:15
      at Array.map (native)
      at conformOptions (example.com/node_modules/sequelize/lib/model.js:260:37)
      at Model.addScope (example.com/node_modules/sequelize/lib/model.js:1105:3)
```

And I can't tell what is causing it. There seems to be `scope` stuff in play, and the code throwing the error was added in this commit: https://github.com/sequelize/sequelize/commit/b503b51ecd009530cb2ebff8a33ff67bcd705169

I also know that in a few places I add extra functions to `Model.Instance.prototype` because I couldn't find any other way.

Just tested it, and `self` at https://github.com/sequelize/sequelize/commit/b503b51ecd009530cb2ebff8a33ff67bcd705169#diff-a140b60b6a99a8c69f4b5d0d1f1f2bfaR245 appears to be an empty object and is not an instance of `Instance` or `Model`, so I've no idea what it is. `self.constructor.name` is just `'Object'`. Weird.

**Comment by janmeier** [comment]
Hard to say without more information. If you can create a self-contained test case I can look at it

**Comment by novacrazy** [comment]
I don't think I can. It just popped up on my dev environment for a very large (to me at least) project. Probably about 15k LOC in play right now.

What is `self` supposed to be an instance of? A `Model`, I guess, since it used that custom `console.log` function when I was logging it a few minutes ago. 

In that commit I linked to, I noticed that `conformOptions` is being called with `this` instead of `self`, could that be the problem?

**Comment by janmeier** [comment]
Self is used as a reference to this in callbacks / promise chains so I doubt that's the issue. 

This seems to be related to calling add scope so perhaps you could try commenting out those calls to find the offending one. It could seem that something is trying to add a scope that includes something that's not a model. Or maybe there's something wrong with include and scope :-)

**Comment by novacrazy** [comment]
Aha! What you said about adding a scope that includes something other than a model was correct!

The "temporary workaround" for this issue: https://github.com/sequelize/sequelize/issues/4584, which is now fixed, is why `self` was an empty object. Since I set it to an empty object myself.

Cool, I'll go ahead and close this since everything is working normally again.
