### ISSUE TITLE
"null is not a valid date" even with allowNull: true

### ISSUE THREAD

**Issue by OscarGodson** [sequelize/sequelize#4654]
I have this in my model:

```
  is_recurring: {
    type: Sequelize.BOOLEAN,
    defaultValue: 0
  },
  recurring_start_datetime: {
    type: Sequelize.DATE,
    allowNull: true
  },
  recurring_end_datetime: {
    type: Sequelize.DATE,
    allowNull: true
  },
```

Recurring is an option, but if its `false` I don't need to set the start and end recurring times. However, it looks like sequelize is forcing me to put in a date? How can I get around this?

**Comment by OscarGodson** [comment]
This is actually also a problem for my `is_all_day` because there's no start or end time

**Comment by janmeier** [comment]
Try upgrading to the latest version
