### ISSUE TITLE
$or in where statement produces AND in sql query

### ISSUE THREAD

**Issue by Olgagr** [sequelize/sequelize#4656]
I have and object with query criteria:

```
{"limit":25,
"offset":0,
"order":"created_at DESC",
"where": {
   "$or":[
       {"email": 
           {"$iLike":"jo"},
        "firstName":
           {"$iLike":"jo"},
        "lastName":
           {"$iLike":"jo"}
        }
     ]
}}
```

and the sql produced by sequelize:

```
WHERE (("user"."email" ILIKE 'jo' AND "user"."first_name" ILIKE 'jo' AND "user"."last_name" ILIKE 'jo')) ORDER BY created_at DESC LIMIT 25;
```

**Comment by mickhansen** [comment]
What version of sequelize?

**Comment by Olgagr** [comment]
3.1.0

**Comment by mickhansen** [comment]
That should support $or, can you try upgrading though?

**Comment by Olgagr** [comment]
I tried but then all my tests stop working, so this is a pain for me :/

**Comment by mickhansen** [comment]
There should be no breaking changes between 3.1.0 and 3.11.0.
In any case we had `$or` support in 3.1.0 https://github.com/sequelize/sequelize/blob/v3.1.0/test/unit/sql/where.test.js#L181

**Comment by Olgagr** [comment]
Well, but somehow in my case on version 3.1.0 the produced sql is wrong.

**Comment by mickhansen** [comment]
That is odd, you can try debugging in the query generator but we definitely had tests for it and they passed at the time and still do.

**Comment by Olgagr** [comment]
Ok, thanks for confirmation. I'll be debugging.
