### ISSUE TITLE
Support for LIKE ALL (ARRAY... )

### ISSUE THREAD

**Issue by pinducin** [sequelize/sequelize#4657]
Hi, Hello, I am using sequelize 3.12.0 and this code 
ProviderItems.findAll({
            where: {$or: [{
                        code: {$ilike: {$any: arrString}}},
                    {object_name: {$ilike: {$all: arrString}}}
                ]
            },
            raw: true
        }).then(function (objects) {
            res.json({
                message: 'Total find ' + objects.length,
                data: objects
            });
        });

generates this SQL..

SELECT "id", "date_insert", "code", "object_name", "brand", "price" FROM "provider_items" AS "provider_items" WHERE ("provider_items"."code" ILIKE ANY (ARRAY['%ROT%','%SUP%','%R12%']) OR "provider_items"."object_name" ILIKE `$all` = '%ROT%', '%SUP%', '%R12%');

 and as can be seen in the "WHERE" query

("provider_items"."code" ILIKE ANY (ARRAY['%ROT%','%SUP%','%R12%'])

is correct, but

"provider_items"."object_name" ILIKE `$all` = '%ROT%', '%SUP%', '%R12%');

is not correct.
does not recognize `$all`

sequalize not support the operator $like: { $all: ['cat', 'hat']}, only support $like: { $any: ['cat', 'hat']}?????
Best Regards..

**Comment by mickhansen** [comment]
Please make an effort to format your issue.
We only have tests for `$like $any`: https://github.com/sequelize/sequelize/blob/master/test/unit/sql/where.test.js#L505

So `$like $all` is likely not supported at the moment.

**Comment by pinducin** [comment]
ok, thanks. Sorry for the format!!
