### ISSUE TITLE
MySQL Cluster

### ISSUE THREAD

**Issue by rafael-custodio** [sequelize/sequelize#4659]
The sequelize will have support to MySQL Cluster?
https://dev.mysql.com/tech-resources/articles/mysql-cluster-7.3.html

**Comment by mickhansen** [comment]
Nothing is planned yet.

**Comment by micksatana** [comment]
I tested on _MySQL distrib mysql-5.7.19 ndb-7.5.7, for Linux (x86_64)_

I changed engine configuration for migration files that using createTable() to execute with { engine: "ndbcluster" } option. After run tests on the API server, all my test cases are passed. However, I think it also depends on your table design and application code as well whether it answers to what MySQL Cluster needs. See [Noncompliance with SQL Syntax in NDB Cluster](https://dev.mysql.com/doc/mysql-cluster-excerpt/5.7/en/mysql-cluster-limitations-syntax.html)

_Note: As it's not officially supported, if you need to use cluster, better test well before use in production._
