### ISSUE TITLE
pg-hstore should not be a requirement to use postgres

### ISSUE THREAD

**Issue by ajsharp** [sequelize/sequelize#4662]
Is it required, or am I doing something wrong? I'm getting the error "The dialect postgres is not supported. (Error: Cannot find module 'pg-hstore')". Here's my config:

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('postgres://localhost:5432/my-db');
```

**Comment by mickhansen** [comment]
It's currently required yes. Code could likely be refactored to lazily require instead.
