### ISSUE TITLE
Cyclic scope dependency causes infinite loop

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#4663]
I have two models User and Company, User belongs to Company / Company hasMany User. 
I am setting default scope for user to include it's company. 
I am setting default scope for company to include all company users.

```js
var Sequelize = require('sequelize')

var sequelize = new Sequelize('postgres://localhost/db')
var User = sequelize.define('User')
var Company = sequelize.define('Company')

User.belongsTo(Company)
Company.hasMany(User)

Company.addScope('defaultScope', {
  include: [{ model: User.scope(null) }]
}, { override: true })

User.addScope('defaultScope', {
  include: [{ model: Company.scope(null) }]
}, { override: true })

User.find({ where: { id: 1 } })
```

output:

```sh
Unhandled rejection RangeError: Maximum call stack size exceeded
```

I think the problem is because in moment when `[{ model: User.scope(null) }]` is set, User model does not have overrided defaultScope yet. Easiest solution would be to pass scope option in include object to override included model scope. For example:

```js
Company.addScope('defaultScope', {
  include: [{ model: User, scope: null }] // or scope: 'scope1' or scope: ['scope1', 'scope2']
}, { override: true })
```

I am using scopes for the first time, so maybe I am doing something wrong?

**Comment by janmeier** [comment]
An unscoped model was not being marked as `.scoped = true`, which caused the default scope to be injected instead

**Comment by alekbarszczewski** [comment]
@janmeier Thank you! I was trying to find out what is causing this on my own but I always ended up with `Maximum call stack size exceeded` :).
