### ISSUE TITLE
Large amount of logging crash Windows cmd

### ISSUE THREAD

**Issue by trungtin** [sequelize/sequelize#4665]
It's just crash without any error. When using winston to log unhandleException I got this:

		"Error: write EPIPE",
		"    at exports._errnoException (util.js:837:11)",
		"    at Socket._writeGeneric (net.js:675:26)",
		"    at Socket._write (net.js:694:8)",
		"    at doWrite (_stream_writable.js:292:12)",
		"    at writeOrBuffer (_stream_writable.js:278:5)",
		"    at Socket.Writable.write (_stream_writable.js:207:11)",
		"    at Socket.write (net.js:618:40)",
		"    at Console.warn (console.js:44:16)",
		"    at warn (l:\\workspace\\m-project\\node_modules\\bluebird\\js\\main\\captured_trace.js:479:17)",
		"    at Function.CapturedTrace.formatAndLogError (l:\\workspace\\m-project\\node_modules\\bluebird\\js\\main\\captured_trace.js:195:13)",
		"    at Function.CapturedTrace.fireRejectionEvent (l:\\workspace\\m-project\\node_modules\\bluebird\\js\\main\\captured_trace.js:250:23)",
		"    at Promise._notifyUnhandledRejection (l:\\workspace\\m-project\\node_modules\\bluebird\\js\\main\\debuggability.js:40:23)",
		"    at Async._drainQueue (l:\\workspace\\m-project\\node_modules\\bluebird\\js\\main\\async.js:128:12)",
		"    at Async._drainQueues (l:\\workspace\\m-project\\node_modules\\bluebird\\js\\main\\async.js:135:10)",
		"    at Immediate.Async.drainQueues [as _onImmediate] (l:\\workspace\\m-project\\node_modules\\bluebird\\js\\main\\async.js:15:14)",
		"    at processImmediate [as _immediateCallback] (timers.js:371:17)"

At first I though it from bluebird, but when turn off logging SQL from sequelize, everything seem alright. It's not a huge log, though, when turn on logging, it crash after about 160 UPSERT.

**Comment by mickhansen** [comment]
Why do you suspect that this is a Sequelize error?
This is likely an issue with your logger.
