### ISSUE TITLE
Raw Select Query Issue

### ISSUE THREAD

**Issue by valtlfelipe** [sequelize/sequelize#4668]
I'm having some trouble with raw queries in sequelize 3.12.1. I'm executing a query like this:

```javascript
sequelize.query("<QUERY>", {
	raw: true,
	type: this._sequelize.QueryTypes.SELECT
}).then(function(vehicles) {
	
});
```

And the query (PostgreSQL) i'm executing is:

```sql
SELECT * FROM vehicles WHERE (
    (DATE_PART('day', vehicles.ipva_due_date::timestamp - NOW()::timestamp) <= 45)
    OR
    (DATE_PART('day', vehicles.dpvat_due_date::timestamp - NOW()::timestamp) <= 45)
    OR
    (DATE_PART('day', vehicles.required_insurance_due_date::timestamp - NOW()::timestamp) <= 45)
    OR
    (DATE_PART('day', vehicles.insurance_due_date::timestamp - NOW()::timestamp) <= 45)
) 
AND vehicles.id NOT IN  (
    SELECT vehicles_id FROM pendencies WHERE (
        (pendencies.type = 'ipva' AND pendencies.due_date = vehicles.ipva_due_date) 
        OR
        (pendencies.type = 'dpvat' AND pendencies.due_date = vehicles.dpvat_due_date)
        OR
        (pendencies.type = 'required_insurance' AND pendencies.due_date = vehicles.required_insurance_due_date)
        OR
        (pendencies.type = 'insurance' AND pendencies.due_date = vehicles.insurance_due_date)
    ) AND deleted_at IS NULL
) AND vehicles.deleted_at IS NULL AND vehicles.status = 'active'
```

The query when it is executed should not return any vehicle, I have tested it in pgAdmin, and actually it does not return anything. But when it runs in sequelize, it  does returns some vehicles.

How can this happen? Any solutions?

**Comment by mickhansen** [comment]
Very odd, and the target database is the same?

**Comment by valtlfelipe** [comment]
@mickhansen Yes, same database! It seems for me, after some tests, that in sequelize, the `vehicles` in the subquery has no value. So all conditions are false, and the ID of the vehicle is actually not in the subquery, so the vehicle is returned.

**Comment by valtlfelipe** [comment]
OMG! Just solved the problem... There was an colum type difference, `pendencies.due_date` = `Timestamp With Time Zone` and `vehicles.ipva_due_date` = `Date`. Strangely in sequelize they could not compare to each other.
