### ISSUE TITLE
Bug?! Model name ending with 'ta' changes to 'tum' on findAll

### ISSUE THREAD

**Issue by Rodrigojorge** [sequelize/sequelize#4670]
I have a model named 'motorista' , like this:

  var Motorista = sequelize.define('motorista', {
    matricula: {
      type: DataTypes.STRING,
      primaryKey: true,
      field: 'MATRICULA',
.....

and it is associated with another called 'movimentacao'

associate: function (models) {
        Movimentacao.belongsTo(models.motorista, {
          foreignKey: {
            type: DataTypes.STRING,
            field: 'MATRICULA_MOTORISTA',
            name: 'matriculaMotorista'
          }
        })

I can 'CRUD' the model 'motorista' normally, but when I execute a findAll from movimentacao, like this:

  model.movimentacao.findAll({
      include: [
        {model: model.motorista},

the result changes the name to motorist**um** , i can´t even set an alias !

If i name it motorista**r**  or motorista**ra** it isn´t changed 
If I name it **M**otorista or or motorist**t**a IT IS CHANGED
If i change my other model name 'solicitante' to 'solicitant**a** IT CHANGES TO solicitant**um** too

the sufix 'ta' changes to 'tum' ?!?!?!?!

Bug? Any idea? 

Thanks!

**Comment by mickhansen** [comment]
inflection is not always perfect, you should use `as` on your association to force a naming.

**Comment by Rodrigojorge** [comment]
I can't... When I use, it says that 'motorista' isn't related to 'movimentacao'

**Comment by mickhansen** [comment]
If you use `as` on an association statement you need to have the same `as` on the include.

**Comment by Rodrigojorge** [comment]
I have no 'as' on the association.  It doesn't let me define an 'as' on the include...  If I put only include model.motorista sequelize changes to motoristum... If I put an 'as' motorista it says motorista is not related.... If I change the model to motorisra I got no error.... It seems to me it is an 'ta' suffix problem

**Comment by mickhansen** [comment]
Did you read my previous comment at all?
If you add an `as` to the association call to fix the naming issue you NEED to add it to your includes aswell to fix the `is not related` error.

**Comment by Rodrigojorge** [comment]
I will make more tests on Monday...thank you

**Comment by Rodrigojorge** [comment]
Only to clear again, the as was on the include... I have never put it on the association

**Comment by janmeier** [comment]
You need to have the same `as` on both the include and the assocation.

Inflection (our string manipulation lib) is only meant to be used with english, so its using the pluralization rule for `data -> datum`

Try setting the model name manually, that's easier than doing it for each association:

```js
var Motorista = sequelize.define('motorista', {
 ...
}, {
  name: {
    plural: ...,
    singular: ...
  }
});
```

Also, please read up on [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) :)

**Comment by Rodrigojorge** [comment]
Thanks for the reply. It worked with the both aliases... 

For me, it should be enough to have it only in the include, that why i didn´t tested in the association before, only today and after Mick told me.

Thank you both.
