### ISSUE TITLE
Unhandled rejection Error: User (friends) is not associated to SNS!

### ISSUE THREAD

**Issue by seraphjiang** [sequelize/sequelize#4671]
I'm trying to design data model for represent network for user and user's friends

basically, there are two model. User for store user's own information. and SNS for store user's relationship.

here is my 

    var User = sequelize.define(
        'User', {
            id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                autoIncrement: true
            },
            name: DataTypes.STRING,
            email: DataTypes.STRING(256),
            pwd: DataTypes.STRING(2048),
            avatar: DataTypes.STRING(2048),
            property: DataTypes.JSON,
            preference: DataTypes.JSON
        })

    var SNS = sequelize.define("SNS", {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        status: DataTypes.INTEGER
    })

here is the code i added for association
                models.User.belongsToMany(models.User, {
                    as: 'friends',
                    foreignKey: "userId",
                    through: models.SNS
                });

                models.User.belongsToMany(models.User, {
                    as: 'networks',
                    foreignKey: "friendId",
                    through: models.SNS
                });

when i try to cal findAll() with "include" , i got a error. (refer to code below)

    SNS.findAll({
            include: [{
                model: models.User,
                as: 'friends'
            }]
        })
        .then(function(result) {
            res.send(result);
        });

here is the error
Unhandled rejection Error: User (friends) is not associated to SNS!

what's wrong with my model definition. I could a execute a query with include.

The findAll work if i remove the include part. but in that case i will get only userID in SNS model. however i want a user object as well. i don't want to do a query again.

**Comment by mickhansen** [comment]
You'll need SNS.belongsTo(models.User);
Sequelize does not automatically setup relations to the join model when using that model in a N:M relation i'm afraid.

**Comment by seraphjiang** [comment]
i added SNS.belongsTo(models.User);
but still get same error

                models.User.belongsToMany(models.User, {
                    as: 'friends',
                    foreignKey: "userId",
                    through: models.SNS
                });

                models.User.belongsToMany(models.User, {
                    as: 'networks',
                    foreignKey: "friendId",
                    through: models.SNS
                });

                models.SNS.belongsTo(models.User);

**Comment by janmeier** [comment]
You need to add `{ as: friends} ` so that you have to same as (or none) on both the model and the association

**Comment by seraphjiang** [comment]
thanks Jameier, it works, thanks for help.

here is association
                models.SNS.belongsTo(models.User, {
                    foreignKey: "userId"
                });

                models.SNS.belongsTo(models.User, {
                    foreignKey: "friendId", as: "Friend"
                });

here is the query

    SNS.findAll({
            include: [{
                model: models.User,
                as: 'User'
            }, {
                model: models.User,
                as: "Friend"
            }]
        })
        .then(function(result) {
            res.send(result);
        });

**Comment by jaspalucreate** [comment]
hello

By using belongsTo, relations not created in the database
please provide the solution

Code:

var Questions = Sequelize.define('questions',{
  id:{
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true    
  },
  question:{
    type: Sequelize.TEXT,
    unique: true,
    allowNull: false
  },
  parentId:Sequelize.INTEGER,
  questionType:Sequelize.STRING,
  serialNo:Sequelize.INTEGER,
  isActive:Sequelize.BOOLEAN,
  isDeleted:Sequelize.BOOLEAN
},{
  timestamps: false
});


var Answers = Sequelize.define('answers',{
  id:{
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true      
  },
  questionId:{
    type: Sequelize.INTEGER,
    allowNull: false
  },
  answers:{
    type: Sequelize.TEXT,
    allowNull: false
  },
  optionCode:Sequelize.STRING,
  isActive:Sequelize.BOOLEAN,
  isDeleted:Sequelize.BOOLEAN
},{
  timestamps: false
});

Questions.belongsTo(Answers, {
                foreignKey: "questionId", as: "Questions"
            });



Thanks

**Comment by Adiii717** [comment]
thanks solve my issue

**Comment by arenasgtz92** [comment]
alguien me podria ayudar es algo parecido al problema que presento la chica pero en mi caso me dice que no ay ningun tipo de asociacion. les dejo mis codigos 

//Relaciones 
productos.belongsTo(modulo, {foreignKey: 'IdModulo'});
modulo.belongsTo(areas, {foreignKey: 'IdAreas'});


//Modelos modulo
var ex = function(conector) {

    var Sequelize = conector.Sequelize;
    var sequelize = conector.sequelize;

    var Modulo = sequelize.define('Modulo', {
        id:{ type: Sequelize.INTEGER, autoIncrement: true, primaryKey: true},
        nombre: Sequelize.STRING,
    })

        return Modulo;
};

module.exports = ex;

//Modelo Productos
var ex = function(conector) {

    var Sequelize = conector.Sequelize;
    var sequelize = conector.sequelize;

    var Productos = sequelize.define('Productos', {
        id:{ type: Sequelize.INTEGER, autoIncrement: true, primaryKey: true},
            nombre: Sequelize.STRING,
            descripcion: Sequelize.TEXT,
            corto: Sequelize.INTEGER,
            mediano: Sequelize.INTEGER,
            largo: Sequelize.INTEGER,
            complejidad: Sequelize.INTEGER,
    })

    return Productos;
};

module.exports = ex;

//Modelo Areas
var ex = function(conector) {

    var Sequelize = conector.Sequelize;
    var sequelize = conector.sequelize;

    var Areas = sequelize.define('Areas', {
        id:{ type: Sequelize.INTEGER, autoIncrement: true, primaryKey: true},
        nombre: Sequelize.STRING,
        descripcion: Sequelize.STRING,
        logo:  Sequelize.BLOB('medium'),
    })

    return Areas;
};

module.exports = ex;
// controller Modulo
var db = require('../relations');
var modulo = db.modulo;
var areas = db.areas;

var ex = module.exports = {};

ex.create = function(req, res, next) {

    var data = req.body;
    modulo.create(data).then(function(result) {
        res.status(200).jsonp(result);
    });
};

// Delete [eliminar elemento]
ex.delete = function(req, res, next) {
    var id = req.params.id;
    modulo.findById(id).then(function(modulo) {
        modulo.destroy().then(function(result) {
            res.status(200).jsonp(result);
        });
    });
};
// Update [Actualizar elemento]
ex.update = function(req, res, next) {
    var id = req.params.id;
    var data = req.body;

    modulo.update(data, {
        where: {
            id: id
        }
    }).then(function(result) {
        res.status(200).jsonp(result);
    });
};

ex.read = function(req, res, next) {

    var id = req.params.id;

    if (id) {
        modulo.findById(id).then(function(modulo) {
            res.status(200).jsonp(modulo);
        });
    } else {
        modulo.findAll().then(function(modulo) {
            res.status(200).jsonp(modulo);
        });
    }
};
//Controller Areas
var db = require('../relations');
var areas = db.areas;
var proyectos = db.proyectos;
var modulo = db.modulo;

var ex = module.exports = {};

ex.create = function(req, res, next) {

    var data = req.body;
    areas.create(data).then(function() {
        res.status(200).jsonp(result);
    });
};

//Metodo set y put desde areas a proyectos

ex.crearAreasProyectos = function(req, res, next) {

    var idArea = req.params.idArea;
    var idProyecto = req.params.idProyecto;

    areas.findById(idArea)

        .then(function(areas) {

            return areas.addProyectos(idProyecto)

    }).then(res.send.bind(res))

        .catch(next);
};

// Delete [eliminar elemento]
ex.delete = function(req, res, next) {
    var id = req.params.id;
    areas.findById(id).then(function(areas) {
        areas.destroy().then(function(result) {
            res.status(200).jsonp(result);
        });
    });
};
// Update [Actualizar elemento]
ex.update = function(req, res, next) {
    var id = req.params.id;
    var data = req.body;

    areas.update(data, {
        where: {
            id: id
        }
    }).then(function(result) {
        res.status(200).jsonp(result);
    });
};

ex.read = function(req, res, next) {

    var id = req.params.id;

    if (id) {
        areas.findById(id, {
        include:
        [
            {
                model: modulo,
                as: 'Modulo'
            }
        ]
    }).then(function(area) {
            res.status(200).jsonp(area);
        });
    } else {
        areas.findAll({
            where: req.query,
            include: [
                {
                    all: true
                }
            ]
        }).then(res.send.bind(res)).catch(next);
        // .then(function (areas) {
        //     res.status(200).jsonp(areas);
        // });
        //
    }
};
  ----Espero me puedan ayudar. soy principiante en todo esto.
