### ISSUE TITLE
jscs config.use_env_variable All identifiers must be camelCase or UPPER_CASE

### ISSUE THREAD

**Issue by whisher** [sequelize/sequelize#4673]
Hi,
sorry to bother you.
I'm using jscs with 
https://github.com/jscs-dev/node-jscs/blob/master/presets/node-style-guide.json
Is there a way to avoid the All identifiers must be camelCase or UPPER_CASE warning ?
Thanks in advance.

**Comment by janmeier** [comment]
Not related to sequelize, I'd recommend asking the jscs devs instead
