### ISSUE TITLE
How to query by array length?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#4678]
Hi,

I have a Postgres DB with arrays, and I want to query for records that have a certain array length. I see "array_length" in http://www.postgresql.org/docs/8.4/static/functions-array.html, but I don't know how to do it with well-formed structured Sequelize queries in javascript.

Thanks.

**Comment by subjectix** [comment]
That's a hard one :grin:. 
You can use `sequelize.fn(fn, args)` according to [this](http://docs.sequelizejs.com/en/latest/api/sequelize/#fnfn-args-sequelizefn):
> `fn(fn, args) -> Sequelize.fn` 
> Creates a object representing a database function. This can be used in search queries, both in where and order parts, and as default values in column definitions. If you want to refer to columns in your function, you should use sequelize.col, so that the columns are properly interpreted as columns and not a strings.

I don't have the tools to test my proposal right now, but maybe you can try this: 
```js
Model.findAll({
  where: {
    // 10 being the required length
    [sequelize.fn('array_length', sequelize.col('myArray'), 1)] : 10 
  }
});
```
I have absolutely no idea if this works. if it doesn't maybe we need a feature request. and this feature is very crucial.

**Comment by GeoffreyPlitt** [comment]
Thanks for the reply. Could you clarify your suggestion though? I don't understand how you're using an array as a key in an object (everything to the left of the colon).  And what is the "1" ?

**Comment by janmeier** [comment]
`where: sequelize.where(sequelize.fn('array_length', sequelize.col('myArray'), 1), 10)`

Since objects (such as `.fn`) cannot be used as keys, you need to use `.where`

**Comment by subjectix** [comment]
O.o this is so deep buried within the api [documentation](http://docs.sequelizejs.com/en/latest/api/sequelize/#whereattr-comparator-logic-sequelizewhere). This should also be point out in the query section of the guides. Very good to know, thanks :D

**Comment by janmeier** [comment]
@subjectix, pull requests that improve the documentation are always welcome :-)

**Comment by subjectix** [comment]
@janmeier Sure, I'm working on it as we speak :grin:

**Comment by fahrenq** [comment]
As a note, to combine `.fn`-properties and other properties - just use an array.
```js
      where: [
        models.sequelize.where(
          models.sequelize.fn(
            'array_length',
            models.sequelize.col('patterns'),
            1,
          ),
          { [Op.gt]: 0 },
        ),
        { companyId: this.companyId },
      ],
```

**Comment by ranhalprin** [comment]
> Does anyone can help with the same situation but for **array inside a jsonb column**?

The Postgres function for this is `jsonb_array_length`, but you can't call it on a column because `tags` is not a column, so you'll need to get the nested element, e.g. using `Sequelize.literal("meta->'tags'"))`, giving you something like:
```
Sequelize.where( Sequelize.fn('jsonb_array_length', Sequelize.literal("meta->'tags'"), 1), { [Sequelize.Op.gt]: 0 } )
```

Of course, I'd rather avoid using `literal`, but not sure if there's a more proper way to get nested jsonb elements
