### ISSUE TITLE
When inserting new row, id for the row is returned as a key named "null" in response object

### ISSUE THREAD

**Issue by sunitJindal** [sequelize/sequelize#4682]
I have this structure for a table name "offer_url"

```
module.exports = function(sequelize,DataTypes){
    var OfferUrl = sequelize.define('offer_url',{
        id : {type:DataTypes.INTEGER,primaryKey:true},
        offer_url : DataTypes.STRING(400),
        offer_redirect_url : DataTypes.STRING(400)
    },{
        classMethods : {
            associate: function(models){
                OfferUrl.hasMany(models['offer'],{foreignKey:'offer_url_id'})
            }
        },
        underscored: true
    })

    return OfferUrl
}
```

To save a new record I am using following steps
```
offerUrl = OfferUrls.build({});

offerUrl.offer_url = msg_decoded.store_url;
offerUrl.offer_redirect_url = msg_decoded.redirect_url;

offerUrl.save()
```

The information is saved properly, but the "dataValues" inside the response object contains "id=null" and the response object contains a key named "null" with the id for the saved object. When i was using Postgres the dataValues contained the proper id for any insertion. Below is the screen shot:

<img width="333" alt="screen shot 2015-10-19 at 1 49 13 pm" src="https://cloud.githubusercontent.com/assets/2629625/10572700/432eff78-7668-11e5-9f05-e3f5a683bbc1.png">

In my package json sequelize version is : "^3.11.0" and mysql version on my system is 5.6.22.

Is there some sort of specific configuration required for Mysql dialect with Sequelize, to get ID properly

**Comment by janmeier** [comment]
The I'd column needs to be marked with `autoIncrement: true `, or you can just remove it since sequelize will add it automatically

**Comment by sunitJindal** [comment]
@janmeier Thanks alot, that was such a noob action by me. I just removed the ID and its working as expected.
