### ISSUE TITLE
beforeFind hook is not executed on Model.count()

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#4683]
It seems that `beforeFind` hook is not executed on `Model.count()`. I am not sure if this is intentional, but it would be cool if this could work. For example I am using `beforeFind` hook to apply custom query conditions (based on options passed to query) and when I am using `findAndCount` then those custom conditions are applied only to `findAll` call and not for `count` call. So I end up with count = 10 and 30 rows for example.

I think there are three options:

1. Pass extra option to count/findAndCount, for example `beforeCount: true` that will trigger `beforeFind`  also for `count` method. This wont break BC.

2. Just run beforeFind hook for count - this may break BC?

3. Add new hook `beforeCount`. This wont break BC.

What do you think @janmeier @mickhansen ?

**Comment by janmeier** [comment]
I think a separate `beforeCount` hook is the best option

**Comment by sushantdhiman** [comment]
Hi @janmeier , we can close this one
