### ISSUE TITLE
updating the first instance returned from findAll modifies all instances (mySQL)

### ISSUE THREAD

**Issue by bvschwartz** [sequelize/sequelize#4685]
In this example:
```
    Thingie.findAll().then(function(thingies) {
        thingies[0].update({ details: "details about 0" });
    });
```
if findAll returns an array of 10 thingies, then all of them will have their details field updated to "details about 0".  I would expect that only the first one would be updated. 

I've posted to stackoverflow as well and gotten no answers: http://stackoverflow.com/questions/32979623/in-sequelize-updating-the-first-instance-returned-from-findall-modifies-all-ins

**Comment by janmeier** [comment]
Can you show the model definition. Sounds like something is of with primary keys?

**Comment by bvschwartz** [comment]
The relevant part of the model looks like this where account_id is the primary key in mySQL:

module.exports = function(sequelize, DataTypes) {
  return sequelize.define('account', {
    account_id: {
      type: DataTypes.INTEGER(10),
      allowNull: false,
    },
etc…

like so I was doing a findAll on the account object and then updating individual accounts using Sequelize like

  account.set(values);
  account.save();

and as I said all the accounts returned by findAll were changed, not just the one I was operating on.

Thanks!

**Comment by Joshua-F** [comment]
I believe you need to supply ``primaryKey: true`` to ``acount_id``.

````javascript
module.exports = function(sequelize, DataTypes) {
        return sequelize.define('account', {
                    account_id: {
                        type: DataTypes.INTEGER(10),
                        allowNull: false,
                        primaryKey: true
                    },
````

**Comment by janmeier** [comment]
Yep, you definitely need to mark the `account_id` as the pk, otherwise sequelize will be very confused and try to select and `id` column ;)
