### ISSUE TITLE
Example dialect extention

### ISSUE THREAD

**Issue by EToreo** [sequelize/sequelize#4686]
I seem to remember a piece of documentation that lightly explained how to extend Sequelize to support more dialects - but I can't find it now.

I would like to try adding Oracle to the list of supported dialects and am a touch lost on how to go about it.  I have done the obvious things like add new directories and tell the sequelize.js file about the new dialect.  But the data-types.js, query.js, and query-generator.js files that I am supposed to provide confuse me as well as the `OracleDialect.prototype.supports` list in index.js.

Could someone give a a little overview or point me to some documentation on how to add a dialect?

**Comment by janmeier** [comment]
Dialect supports allows us to write a lot of queries more abstract. Instead of having an implementation for each dialect, we have an abstract one, and just check whether the current dialect supports a specific feature 

There is already work being done on oracle support in gintsgints/sequelize

**Comment by EToreo** [comment]
Thanks for pointing me towards gintsgints/sequelize.
