### ISSUE TITLE
limit fails when used with belongsToMany+hasMany association - even with separate: true

### ISSUE THREAD

**Issue by manuelbieh** [sequelize/sequelize#4687]
Hi,

I'm not quite sure whether it is really a bug or I just did something wrong but I have some issues getting data from a `belongsToMany` association which itself has another `hasMany` association which I want to limit to only 1 result in one certain case.

I have a `Product` model which *has* many `ProductImages` and *belongs to* many `ProductCategories`. When I try to get all *products* of a certain *category* with only the first *product image* included, I get an error *Invalid scope 'overview' called* - overview is the scope I use to get only the first product image as preview.

If I get the product directly via `Product.scope('overview').findAll()` everything works fine. I've already tried `separate: true` but with no success.

I created a fully executable gist so you can have a look: https://gist.github.com/manuelbieh/b0ec0f41614cf9924b14

(MySQL Version here: https://gist.github.com/manuelbieh/a7a0aa14b3ef53e0bb78)

Any idea what I've done wrong and/or how it can be fixed? Or is it really a bug?

Maybe a short explanation of what I want to do to get some context: I have a page with a *category* page where a user can see all *products* of that particular *category*. For each *product* in that list I want to show the product's first *image* as preview, so I really need only the first image. How can I realize that?

**Comment by mickhansen** [comment]
That is odd, it should simple call scope on the target model: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L466

Is any SQL emitted? Likely not since the error occurs before any queries are executed: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1215

Can you verify the scope exists by logging `Model.options.scopes`?

**Comment by manuelbieh** [comment]
Where do you mean should I log Model.options.scopes? I did it after defining all my models right before dropping and creating the tables:
`console.log(typeof Product.options.scopes.overview, Product.options.scopes.overview);`

It outputs:
```
object { include:
   [ { model: productImage,
       required: false,
       as: 'images',
       separate: true,
       limit: 1 },
     { model: productCategory,
       required: false,
       as: 'categories',
       through: [Object] } ] }
```

So yes, it exists. And I can use it, as long as I do it _directly_ on the Product model (`Product.scope('overview').findAll()`) and it works perfectly fine. Only when I specify my *overview* scope when trying to get a Category's products via `category.getProducts({scope: 'overview'})` it fails.

You can try my linked sqlite example out of the box. Just download it and run it using babel-node ;)

**Comment by manuelbieh** [comment]
I have just tried to add a console log to https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L466
```
    var model = association.target;
    if (options.hasOwnProperty('scope')) {
    console.log(model.options.scopes[options.scope]);
      if (!options.scope) {
        model = model.unscoped();
      } else {
        model = model.scope(options.scope);
      }
    }
```

Outputs the scope object from above. So it does not not exist. So why is it *invalid*?

**Comment by manuelbieh** [comment]
Ok, this is weird. I changed this line
https://github.com/sequelize/sequelize/blob/87358fae7abe6db82a1141b2d73d7f31b2726d87/lib/model.js#L1215
to:
`throw new Error('Invalid scope ' + scopeName + ' called on model ' + self.options.name.singular );`

And it looks like the scope `overview` get's applied on my `ProductImage` model:
`[Error: Invalid scope overview called on model productImage]`

Yep, exactly. Did some more testing. I can add an empty scope `overview` to `ProductImage` and it works!

```
let ProductImage = sequelize.define('productImage', {
    filename: Sequelize.STRING,
}, {
    scopes: {
        overview: {}
    }
});
```
Complete working example here:
https://gist.github.com/manuelbieh/c6756c3d46bc7b77c318

So it looks like the `overview` scope somehow gets *inherited* which (for my understanding) should not be the case, should it?

**Comment by mickhansen** [comment]
No that definitely sounds like a bug.

**Comment by manuelbieh** [comment]
I might have found another bug related to the scoping bug: adding `attributes` to the scope causes another error:
```
TypeError: Cannot read property 'push' of undefined
    at node_modules\sequelize\lib\associations\has-many.js:324:64
```

```
    scopes: {
        overview: {
            include: [
                {
                    model: ProductImage,
                    required: false,
                    as: 'images',
                    attributes: ['id', 'filename'], // this line causes "Cannot read property 'push' ... "
                    limit: 1
                },
                {
                    model: ProductCategory,
                    required: false,
                    as: 'categories',
                    through: {
                        attributes: []
                    }
                }
            ],
        },
    }
```

Either `limit` or `attributes` can be used. If `limit` is set, `attributes` causes the error mentioned above. Leaving `limit` out, `attributes` works fine.

**Comment by manuelbieh** [comment]
Okay, the deeper I dig the more bugs I can find ;) `limit` now works in my `Product` model scope when I add an empty "pseudoscope" to my `ProductImage` model but `offset` is still ignored however.

Should I open another ticket for that?

**Comment by janmeier** [comment]
Seems to be because the scope is being applied to `productImage` by `findSeparate`. We should probably omit the scope [here](https://github.com/sequelize/sequelize/blob/7f5a251bb7bf225960e163f036315a3024f4fa6f/lib/model.js#L1429), or use a whitelist instead of a blacklist

**Comment by mickhansen** [comment]
@janmeier i generally lean towards a blacklist rather than a whitelist since people might be using custom options that plugins depend on etc.

**Comment by janmeier** [comment]
True dat - then we should add scope to the black one :)

**Comment by mickhansen** [comment]
Definitely.

**Comment by manuelbieh** [comment]
:+1:
