### ISSUE TITLE
Join priority when mixing left join and inner join

### ISSUE THREAD

**Issue by vbogdanov** [sequelize/sequelize#4689]
I have models A, B, C
A.hasMany(B)
C.hasMany(B)

I need to get all A records and A.Bs to contain those B that have C with the proper flag value.

When using:

``` javascript
A.findAll({
  include: [{
     model: B,
     include: [{
        model: C,
        where: { flag: true },
        required: true //already set by where
     }],
     required: false
  }]
});
```

I end up with A left join B on ... inner join C on ..., essentially `(А left B) inner C`. I need `A left (B inner C)`. Is there a way (aside from raw queries) to force B inner join C to take priority over the left join.

**Comment by mickhansen** [comment]
Not possible currently, but that should possibly be the default. I think that would be a saner default in fact, not sure if it breaks BC for anyone.

**Comment by DeX3** [comment]
Has there been any progress on this? I'm facing a similar issue.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/6170
