### ISSUE TITLE
How Do I Count Associations Returned via Includes Efficiently?

### ISSUE THREAD

**Issue by alexbooker** [sequelize/sequelize#4691]
I am in a spot of bother using Sequelize and was hoping that someone would kindly help.

I am building a system where `Tutorial`s have many `Comment`s. Every `Comment` is associated with a `User` but I do not think that is relevant to my problem:

```javascript
const User = sequelize.define('User', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
}, {
  classMethods: {
    associate: function (models) {
      User.hasMany(models.Tutorial, {
        foreignKey: 'authorId'
      });
    }
  }
});
```

```javascript
const Tutorial = sequelize.define('Tutorial', {
  slug: {
    type: DataTypes.STRING,
    primaryKey: true
  },
  authorId: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
}, {
  classMethods: {
    associate: function(models) {
      Tutorial.belongsTo(models.User, {
        foreignKey: 'authorId'
      });
      Tutorial.hasMany(models.Comment, {
        foreignKey: 'tutorialSlug'
      });
    }
  }
});
```
```javascript
const Comment = sequelize.define('Comment', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  authorId: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  tutorialSlug: {
    type: DataTypes.STRING,
    allowNull: false
  },
}, {
  classMethods: {
    associate: function(models) {
      Comment.belongsTo(models.User, {
        foreignKey: "authorId"
      });
      Comment.belongsTo(models.Tutorial, {
        foreignKey: "tutorialSlug"
      });
    }
  }
});
```

Note: I have removed most columns from the model definition in an attempt to isolate the problem.

My aim is to list all tutorials and the *count of comments associated with each tutorial*. I *have* managed to achieve this using a hack. I run the following query:

```javascript
db.models.Tutorial.findAndCountAll({
  include: [{
    model: db.models.User
  }, {
    model: db.models.Comment,
  }]
});
```

Which yields the following result:

```json
{
  "count":1,
  "rows":[
    {
      "slug":"foo"
      "authorId":1,
      "User":{
        "id":1,
      },
      "Comments":[
        {
          "id":1,
          "authorId":1,
          "tutorialSlug":"foo"
        },
        {
          "id":2,
          "authorId":1,
          "tutorialSlug":"foo"
        }
      ]
    }
  ]
}
```

I then access the comment count using the `tutorial.Comments.length` property in JavaScript, which is a hack.

It it at all possible to use MySQL's `COUNT` function for a more efficient query?

I am writing this issue as a last resort. I have looked through a couple of issues ([1](https://github.com/sequelize/sequelize/issues/222), [2](https://github.com/sequelize/sequelize/issues/1025)) but am yet to figure this out. 

Many thanks.

**Comment by janmeier** [comment]
`findAndCount` is meant for pagination, so it only allows for counting the number of parent rows. If could use a normal `count` though

```js
Tutorial.count({
    attributes: ['slug'],
    include: [Comment],
    group: ['slug']
  })
```
Adding include to count will count number of included rows instead, and grouping by the pk of tutorial will split the count per tutorial

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by kaanyalti** [comment]
I'm actually trying to do the same thing, couldn't find anything helpful yet
