### ISSUE TITLE
Delete JSONB property (with PostgreSQL)

### ISSUE THREAD

**Issue by pensierinmusica** [sequelize/sequelize#4692]
Hi,

I'm using sequelize (v3.12.2), with pg (4.4.3), PostgreSQL (v9.4), and Node (v4.1.2).

I have a model that inlcudes a JSONB data type field.

``` js
var User = {
  data: {
    type: Sequelize.JSONB
}
```

Now I can do

``` js
User.findOne({where: {id: 12345}})
  .update({data: {x: 'foo'}});
```

And

``` js
User.findOne({where: {id: 12345}})
  .update({'data.y': 'bar'});
```

Now, if I want to delete just the `data.x` property how can I do it in one command?

``` js
User.findOne({where: {id: 12345}})
  .update({'data.x': null});
```

Obviously doesn't work. In fact, the resulting data object should be:

``` js
{y: 'bar'}
```

And not:

``` js
{x: null, y: 'bar'}
```

How can I do this with Sequelize? Thanks for your help!

**Comment by janmeier** [comment]
Not possible currently, but seems the syntax for pg 9.5 is 

> jsonb - text, which can be used to remove in a jsonb field a given key at the top-level of the field (no nested operations possible here).

```
=# SELECT '{"a1":"v1","a2":"v2"}'::jsonb - 'a1' AS field;
     field
--------------
 {"a2": "v2"}
(1 row)
```
http://michael.otacoo.com/postgresql-2/postgres-9-5-feature-highlight-new-jsonb-functions/

For older pg versions you have to create a function that loops through the object and removes the unwanted keys - ugly!! http://stackoverflow.com/questions/23490965/postgresql-remove-attribute-from-json-column

**Comment by pensierinmusica** [comment]
Thanks @janmeier, looking forward to see this implemented in future Sequelize releases  :)

Cheers

**Comment by pensierinmusica** [comment]
@janmeier has this been solved?
