### ISSUE TITLE
Use loaded model in `find` query

### ISSUE THREAD

**Issue by leebenson** [sequelize/sequelize#4699]
Let's say I have three tables: **users**, **accounts** and **accountTypes**.

An account belongs to a user. It also belongs to an accountType.

I have a loaded accountType model, and I want to find all of its associated accounts. `accountType.getAccounts()` does that for me.

But let's say I have a loaded 'user' instance, and want to use it to further whittle down the query.

It would be nice to be able to do `accountType.getAccounts({where: user})` to further limit the search. Even though accountType and users have no direct relation - Sequelize knows enough about each model to know how they're related.

The issue is explained here:

http://stackoverflow.com/questions/33200696/sequelize-js-find-on-model

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

(i've answered on SO instead)

**Comment by leebenson** [comment]
Does this functionality already exist? If not, please consider it a feature request.

**Comment by janmeier** [comment]
I was about to write this on SO, but since its kinda an argument against this feature I guess it belongs more here ;)

So, if i understand correctly you'd like to be able to write `{ where: { user: user } }` (user object) instead of `{ where: { userId: user.id } }` right? While I do see that it might be slightly cleaner, I think it would mostly just clutter up the API - we already have two ways of doing it, by attribute, or using includes. If you want to use include without loading unneccesary data you could always add `attributes: []` to the include

**Comment by leebenson** [comment]
That's a fair comment, and I don't want to clutter up the API.

The problem it solves, though, is model customisation. With UserId: user.id, it's easy to refine. With a stack of "as" definitions, different foreignKey references, pluralisation and other issues, it would mean not having to remember all that stuff (or worse, hard-coding column names that could get out of sync with later changes to model definitions.)

Since Sequelize already knows my models intimately and all of the connections between tables - why not let it figure this stuff out? It is an ORM after all :-)

Not the world's biggest problem, but it would be an elegant feature.

**Comment by mickhansen** [comment]
Perhaps an association could expose a where method that takes an instance or an array of instances and returns a where object that would identify the associations for those instances.

In this case it could be:

```js
accountType.getAccounts({where: userAccountsAssociation.where(instance)});
```

**Comment by mickhansen** [comment]
Just for reference, with ES6 it's trivial pretty trivial:

```js
User.Accounts = User.hasMany(Account);

accountType.getAccounts({
  [User.Accounts.foreignKey]: user.get('id')
});
```
