### ISSUE TITLE
How to use Sequelize.ARRAY() with custom array item type?

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#4700]
I am trying to use `Sequelize.ARRAY` type with custom array item type:

```js
var Sequelize = require('sequelize')

var sequelize = new Sequelize('postgres://localhost/db')

var Model = sequelize.define('Model', {
  time_ranges: Sequelize.ARRAY('tstzrange')
})

Model.sync()
```

And it throws following exception:

```
Unhandled rejection TypeError: Object tstzrange has no method 'toSql'
```

**Comment by janmeier** [comment]
Try `Sequelize.ARRAY(Sequelize.RANGE(Sequelze.RANGE))`

**Comment by alekbarszczewski** [comment]
@janmeier Thank you! works perfectly. I didn't event now that there is `Sequelize.RANGE` type. Now I see that it can be found here http://docs.sequelizejs.com/en/latest/api/datatypes/#range. Maybe it would be worth mentioning about `Sequelize.RANGE` also here http://docs.sequelizejs.com/en/latest/docs/models-definition/#data-types.

**Comment by janmeier** [comment]
Definitely worth mentioning,  PR welcome :)
