### ISSUE TITLE
minor issue with testcase / potentially unwanted sideeffects

### ISSUE THREAD

**Issue by User4martin** [sequelize/sequelize#4701]
the test case in sequelize.test.js (e.g. line 261) has code like
```
      var self = this
        , seq = Object.create(self.sequelize);

      seq.options.quoteIdentifiers = false;
```
I assume this is to make a temp copy, and modify seq.options.quoteIdentifiers for this test only, but not to modify it for remaining tests?

If my assumption is correct the code does not do this. (options is accessed via reference)

```
      var self = this
        , seq = Object.create(self.sequelize);
      seq.options = Utils.cloneDeep(seq.options);
      seq.options.quoteIdentifiers = false;
```
should solve this.

I have not searched if there are other occurrences.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/test/integration/sequelize.test.js#L223

it has an afterEach that rests it. In the future it's helpfull to simply link the code :)
