### ISSUE TITLE
instance.set('id', 1) returns undefined

### ISSUE THREAD

**Issue by lzrski** [sequelize/sequelize#4702]
Seems like setting a value of a field that is a primary key returns `undefined`. Consider this snippet:

```javascript
Foo
  .findOne()
  .then( (foo) -> foo.set('id', 100).save() )
```

It throws `TypeError: Cannot read property 'save' of undefined`. Instead of this I would expect a meaningful error to be thrown when I try to save the instance.

Note: It actually doesn't matter if the field name is `id` or what it's type is. The fact that it is a primary key is relevant.

I'm using v. 3.12.0 with `sqlite` dialect.

**Comment by mickhansen** [comment]
Looks like we have a bunch of return paths that simply `return;` rather than `return this;`.
https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L335

**Comment by lzrski** [comment]
It would be easy to `throw` instead of `return`-ing. Do you think it's a good idea?

**Comment by lzrski** [comment]
That's a good point.

In this case `return this` would result in just silently ignoring the `set` operation, right?

I would say it is an improvement, but can lead to very subtle bugs. Ultimately we should have some mechanism to notify the application code about a failure to set given field. Do you think throwing is an option for v. 4.x?
