### ISSUE TITLE
DatabaseError instead of ValidationError when inserting invalid enum value

### ISSUE THREAD

**Issue by adamwalz** [sequelize/sequelize#4704]
I have an enum defined at 
``` js
role: {
  type: Sequelize.ENUM,
  values: ['user', 'admin'],
  defaultValue: 'user'
}
```
Prior to Sequelize v0.12.0, when attempting to insert a value other that 'user' or 'admin' Sequelize threw a `SequelizeValidationError`, but is now throwing a `SequelizeDatabaseError`.

Is this to be expected?

I ran git-bisect to track the down the commit where this change occurs to 939203b4c157a03a38788068da513c1fa6b18f7b

**Comment by adamwalz** [comment]
cc. @janmeier

**Comment by janmeier** [comment]
Ah yes, the validation of enums was moved into datatype validations (https://github.com/sequelize/sequelize/pull/3472), which were then rolled back https://github.com/sequelize/sequelize/pull/4604

tl:dr - you should set `options.typeValidation` true to get validation for enums now :)

**Comment by adamwalz** [comment]
Great thank you!
