### ISSUE TITLE
Unhandled rejection RangeError: Maximum call stack size exceeded     at sequelize.define.classMethods.create

### ISSUE THREAD

**Issue by amangupta26** [sequelize/sequelize#4707]
If ClassMethod name is given "create" in 'sequelize.define' and if we are calling 'create' method for that model then the following error is thrown:
```
Unhandled rejection RangeError: Maximum call stack size exceeded     
at sequelize.define.classMethods.create (filename.js:48:24)
at sequelize.define.classMethods.create (filename.js:48:24)
at sequelize.define.classMethods.create (filename.js:48:24)
.
.
.
```

Eg: 
```javascript
classMethods : {
  create : function(obj){
    return this.create(obj).then(function(data){
      return data;
    });
  }
}
```

**Comment by janmeier** [comment]
> Provide functions that are added to the model (Model). If you override methods provided by sequelize, you can access the original method using this.constructor.prototype, e.g. this.constructor.prototype.find.apply(this, arguments)


http://docs.sequelizejs.com/en/latest/api/sequelize/
