### ISSUE TITLE
How to exiting gracefully?

### ISSUE THREAD

**Issue by tdzl2003** [sequelize/sequelize#4711]
Before exiting, I want to wait all queries finished, then connection destroyed gracefully. Like calling 'end' method in `mysql` package.

Is there any way to do this in sequelize? I found  `destroy` `$disconnect` method in connectionManager, but I didn't find the way to call them from a `Sequelize` instance.

**Comment by mickhansen** [comment]
There is `sequelize.close()`, not sure how graceful that is though.

**Comment by janmeier** [comment]
It should be pretty gracefully, telling the pool to empty, which in turns tells each connection in the pool to disconnect

**Comment by tdzl2003** [comment]
Currently .close didn't return a Promise, so I think it's clearly it doesn't wait queries to be finished.

```
Sequelize.prototype.close = function () {
  this.connectionManager.close();
};
```

I found `destroy` `$disconnect` method in connectionManager, but I didn't find a way to use it via sequelize instance.

**Comment by janmeier** [comment]
`.close` calls `connectionmanager.close` https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js, so yes you found it ;). It shuts down connections gracefully, but does not allow you to await it no. In any case, the process will not exit before connections have terminated, unless you call `process.exit`

**Comment by tdzl2003** [comment]
Thanks for answering!

**Comment by tedeh** [comment]
So the succint answer is `sequelize.connectionManager.close().then(() => console.log('shut down gracefully'));` for anyone else coming here.

**Comment by vajahath** [comment]
I guess as of now you can use `sequelize.close().then..`
