### ISSUE TITLE
How to pass in transaction object in custom validation?

### ISSUE THREAD

**Issue by rbudiharso** [sequelize/sequelize#4714]
How to pass in transaction object to be use in custom validation/model validation? hooks can access it via options object

```javascript
sequelize.define('Model', {
  username: {
    type: DataType.STRING,
    validate: {
      customValidation: function(value) {
        // how to get transaction object here?
        // someQuery
      }
    }
  }
}, {
hooks: {
  beforeCreate: function(instance, options, fn) {
    // here we got options.transaction <== like this
  }
});
```

**Comment by janmeier** [comment]
Hmm, I honestly don't think you should be able to access options in the validator for a single attribute. If you need to do any validations that are more involved I'd recommend `before/afterValidate` hooks

**Comment by rnemec** [comment]
I don't think running an additional query in a validator is involved.

**Comment by furqanaziz** [comment]
@janmeier Just wondering how I can access transaction in `before/afterValidate` hooks?

**Comment by guisehn** [comment]
Although there's no way to access the transaction in an attribute validator, you can access it in a model-wide validation if you inject the transaction object into your instance during the `beforeValidate` hook.

I made a blog post describing how to do that: http://blog.guisehn.com/access-sequelize-transaction-model-validator/

**Comment by guisehn** [comment]
Although there's no way to access the transaction inside an attribute validator function, you can transform your validation into a model-wide validation -- which has access to the instance -- and then inject the transaction object into your instance during the `beforeValidate` hook.

I made a blog post describing how I did that and it worked: https://blog.guisehn.com/access-sequelize-transaction-model-validator/
