### ISSUE TITLE
Is possible to pass searchPath using defaultScope?

### ISSUE THREAD

**Issue by aledbf** [sequelize/sequelize#4720]
I want to use the `searchPath` feature in postgresql without using the parameter in the queries.
I tried to use the `defaultScope` but it doesn't works. 
```
  defaultScope: function(){
    return {
      searchPath: global.cls.getNamespace('db').get('schema')
    }
  }
```

Is possible to achieve something like this? 
Thanks

**Comment by mickhansen** [comment]
`searchPath` is not supported, we suggest you simply use model schemas.

**Comment by aledbf** [comment]
@mickhansen ok, thanks

**Comment by mickhansen** [comment]
Ok actually `searchPath` is supposed in options to calls. But likely not supported by scopes currently.
