### ISSUE TITLE
sqlite URIs do not support absolute paths

### ISSUE THREAD

**Issue by binki** [sequelize/sequelize#4721]
I can use a URI like `sqlite:file.sqlite` to specify a file in the current directory called `file.sqlite`. But if I specify `sqlite:/home/ohnobinki/file.sqlite`, the file is not created.

Code that works:

```
#!/usr/bin/env node
var Sequelize = require('sequelize');
var sequelize = new Sequelize('sqlite:file.sqlite');
sequelize.define('user', { email: Sequelize.STRING});
sequelize.sync();
```

Code that doesn’t work but should:

```
#!/usr/bin/env node
var Sequelize = require('sequelize');
var sequelize = new Sequelize('sqlite:/home/ohnobinki/file.sqlite');
sequelize.define('user', { email: Sequelize.STRING});
sequelize.sync();
```

If I’m just forming the URIs incorrectly, then the correct syntax needs to be documented.

**Comment by janmeier** [comment]
Seems our string parsing is mostly tailored at urls, not files  https://github.com/sequelize/sequelize/blob/b8e0f378833acd445515f028f131a0be2930adc6/lib/sequelize.js#L98lL121

I think `new Sequelize('file:/...', { dialect: 'sqlite' })` would be a good compromise. PR welcome :)
https://www.sqlite.org/c3ref/open.html#urifilenameexamples

**Comment by binki** [comment]
I think being able to encode the entire set of connection parameters in just the URI string would be a worthwhile goal. Why not supporting something like `sqlite:?uri=file:database.sqlite%3fvfs%3dunix-dotfile`? I think in the existing URIs it is pretty clear that scheme sets the dialect. It’d be nice if an application’s configuration could just allow a user/sysadmin to provide one URI-formatted string when configuring an app that uses Sequelize regardless of what database type Sequelize configures.

**Comment by azeemba** [comment]
Looking through the code, I see that the pathname is already parsed and stored as "database". However the sqlite connection code doesn't seem to use that info at all.

https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/connection-manager.js#L62

So couldn't we just fix it by using the "database" value as a replacement of "storage"?
