### ISSUE TITLE
Why the callback is not being called when adding association (1:m)?

### ISSUE THREAD

**Issue by hezjing** [sequelize/sequelize#4723]
Hi

I'm creating a company and an employee, then adding the employee to the company models:
```javascript
const promise = Company.create({
  name: 'Apple'
}).then((company) => {
  console.log('Company is created');
  return [company, Employee.create({name: 'Jenny', ...})];
}).spread((company, employee) => {
  console.log('Employee is created');
  return company.addEmployees(employee);
}).then((company) => {
  // this is not printed!
  console.log('Employee is added to company');
});
```
Do you have any idea of why the last callback is not called? There is no error shown in the console except the following:
```
Executing (default): INSERT INTO `companies` (...);
Company is created
Executing (default): INSERT INTO `employees` (...);
Employee is created
Executing (default): UPDATE `employees` SET `company_id`=...;
```
It looks like Sequelize generated the SQL to update the employee table when adding the association to company.

**Comment by janmeier** [comment]
This works fine for me, and it's some of the most basic functionality so I'd be very surprised if it doesn't work. 

Can you provide a complete, copy paste able test case that shows the problem?

**Comment by mickhansen** [comment]
Do you have a catch statement attached so you can log possible errors?

**Comment by janmeier** [comment]
Closing, no response
