### ISSUE TITLE
Select fields when including

### ISSUE THREAD

**Issue by shockwork** [sequelize/sequelize#4726]
Is it possible to currently select fields when using include? 

__Example:__
``Include.push({ model: UserModel, as: 'Owner', fields: ['email'] });``

I skimmed through the source, but couldn't find any signs of support for this, but if there is; how can it be done? Currently I loop through the results and remove the fields before sending it to the client but it feels dirty..

**Comment by mickhansen** [comment]
`attributes` is what you're looking for, rather than `fields`.

See `options.include[].attributes`: http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance
