### ISSUE TITLE
Is there a way to order by where in field?

### ISSUE THREAD

**Issue by bammoo** [sequelize/sequelize#4730]
The sql is like this:

```sql
SELECT
	`id`,
	`name`
FROM
	`members` AS `member`
WHERE
	`member`.`id` IN('40', '44', '41', '42', '43', '45')
ORDER BY FIELD(`member`.`id`,'40', '44', '41', '42', '43', '45')
```

How to get this done by Sequelize ?

**Comment by mickhansen** [comment]
`order: [[sequelize.fn('FIELD', sequelize.col('member.id'), '40', 44', '...'))]]` should work.

**Comment by bammoo** [comment]
@mickhansen Thanks, it's work.

**Comment by Shivam-svelte** [comment]
> `order: [[sequelize.fn('FIELD', sequelize.col('member.id'), '40', 44', '...'))]]` should work.

work for me try this

**Comment by developersaif** [comment]
I tested this and it worked for me.

order: [[fn("FIELD", col("products.id"), [2, 3, 1])]]
