### ISSUE TITLE
connect remote database

### ISSUE THREAD

**Issue by abhinav76** [sequelize/sequelize#4731]
I'm trying to connect my node sequelize app with remote database. I am receiving this error
{
  "name": "SequelizeConnectionError",
  "message": "connect ETIMEDOUT",
  "parent": {
    "errorno": "ETIMEDOUT",
    "code": "ETIMEDOUT",
    "syscall": "connect",
    "fatal": true
  },
  "original": {
    "errorno": "ETIMEDOUT",
    "code": "ETIMEDOUT",
    "syscall": "connect",
    "fatal": true
  }
}
Can you tell me what is wrong?
config.js
<code>
var Sequelize = require('sequelize');
var env = "dev";
var config = require('./database.json')[env];
var password = config.password ? config.password : null;

// initialize database connection
var sequelize = new Sequelize(
	config.database,
	config.user,
	config.password,
	{
	//timezone:"+5:30",
	host: 'server_path',
	path:'/tmp/mysql.sock',
	
    dialect: config.driver,
    logging: console.log,
		define: {
			timestamps: false
		}
	}
);
module.exports=sequelize;
</code>

**Comment by abhinav76** [comment]
database.json
<code>
{
  "dev": {
    "driver": "mysql",
    "user": "root",
    "database": "db_name",
    "password": "password",
    "secret":"something"
  },
 
  "production": {
    "driver": "mysql",
    "user": "root",
    "database": "myapp"
  }
}
</code>

**Comment by janmeier** [comment]
No, we can't tell you whats wrong - you have only given us some very basic code for connecting, and not the actual details of your server - so there is no way for us to test it.

I'm 99.9999% sure this is not an issue with sequelize, but with your connection details.

Try to connect via the mysql command line and via node-mysql. If you can connect with node-mysql but not with sequelize then _maybe_  there might be an issue - most likely you just need to pass some extra settings in `dialectOptions`
