### ISSUE TITLE
Error in default scopes

### ISSUE THREAD

**Issue by festo** [sequelize/sequelize#4733]
This issue is reproducible in the latest release: 3.12.1 
We have an issue with late binding default scopes: we load models in alphabetic order and set scopes after that in a same order. For example we have three models:
```
ModelA
ModelB
ModelC
``` 

Everything is right if the models has associations like:
```
ModelB contains ModelA
ModelC contains ModelB
(ModelC -> ModelB -> ModelA)
```

So if I set default scope to ModelB at first, and after I set default scope for ModelC, a request to ModelC will conatins ModelA. This is the original and expected result.

If I set `ModelC -> ModelB` relations at first, and after the `ModelB -> ModelA`, the request to ModelC won't  contains ModelA. :(

In real life example, we have an App, a User and an Image model. A user has an image and an app has a user (or more).
```
App -> User
User -> Image
```

If we set default scopes alphabetic order, like above, the app won't contains user images.

**Comment by janmeier** [comment]
Can you provide a [SSCCE](http://sscce.org/) with actual sequelize models, relations and `addScope` calls instead of the conceptual decription :) ?

**Comment by janmeier** [comment]
Closing, no response
