### ISSUE TITLE
[Question] How to convert  results query to Array because {raw: true} remove in v3.12.2

### ISSUE THREAD

**Issue by kimthangatm** [sequelize/sequelize#4734]
In old version I use params: `raw: true` because I want change value in result query. But in Sequelize v3.12.2 I get error: **Error: Please note that find* was refactored and uses only one options object from now on. at Model.findAll**

**Question:** How to convert  results query to Array?

```
__models.categories.findAll({
    attributes: ['id', 'name', 'alias', 'description', 'icon'],
    order: 'name ASC'
}, {
    raw: true
}).then(function (resultCategories) {
    return res.json({logs:resultCategories});
});
```

**Comment by curiousdannii** [comment]
Just move it into the first options object.

**Comment by janmeier** [comment]
@curiosdannii is right

**Comment by kimthangatm** [comment]
@curiousdannii Thank for support!
