### ISSUE TITLE
Pass options when creating instance with nested associations

### ISSUE THREAD

**Issue by eventhough** [sequelize/sequelize#4736]
I use hooks on all my models to do certain things like adding user data whenever an instance is created. I do this by passing extra data in the options object which can then be used when the hook runs.

My problem occurs when I try to create nested associations along with a new instance. I'm following the example from the [docs](http://docs.sequelizejs.com/en/latest/docs/associations/#creating-elements-of-a-belongsto-association-with-an-alias).

When I dive into the code I can see that for nested association creation, not all the options are being passed through. This makes sense because different options are needed to create associations.

https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L711

But it doesn't hurt to ask - is there any way we could get additional options passed through for association creation as well?

**Comment by janmeier** [comment]
Yeah, should be possible to change that line to use a blacklist which removes `include` (and possible a couple of other options)<

**Comment by mickhansen** [comment]
A blacklist would be better, `include` and `fields` are obvious ones.

**Comment by fesaza** [comment]
is there any way to do this nowadays?
