### ISSUE TITLE
Pagination with nested where problem?

### ISSUE THREAD

**Issue by asuwend1** [sequelize/sequelize#4737]
Hi,

I'm seeing a pagination problem (latest stable release):

Code:
models.merchants.findAndCountAll({
        attributes: ['slug', 'name', 'description', ['image', 'imageFilename'], ['icon', 'iconFilename']],
        include: [{model: models.promotions, order:  ['priority', 'DESC'], attributes: ['priority','id','title','description'], include: [{model: models.events, attributes: ['id','start_at','end_at','special_event'], include: [{model: models.cities, attributes: [['slug', 'id'], 'city'], where:{} ]}]}],
        offset: 0,
        limit: 20, //expecting 20 items on a full page
        subQuery: false
    })

//yes, I am using where: {} so I can just replace {} to something else if I set a filter on the city

SQL command:
Executing (default): SELECT count(DISTINCT("merchants"."id")) AS "count" FROM "merchants" AS "merchants" LEFT OUTER JOIN "promotions" AS "promotions" ON "merchants"."id" = "promotions"."merchant_id" LEFT OUTER JOIN "events" AS "promotions.events" ON "promotions"."id" = "promotions.events"."promotion_id" INNER JOIN "cities" AS "promotions.events.city" ON "promotions.events"."city_id" = "promotions.events.city"."id";
Executing (default): SELECT "merchants"."id", "merchants"."slug", "merchants"."name", "merchants"."description", "merchants"."image" AS "imageFilename", "merchants"."icon" AS "iconFilename", "promotions"."priority" AS "promotions.priority", "promotions"."id" AS "promotions.id", "promotions"."title" AS "promotions.title", "promotions"."description" AS "promotions.description", "promotions.events"."id" AS "promotions.events.id", "promotions.events"."start_at" AS "promotions.events.start_at", "promotions.events"."end_at" AS "promotions.events.end_at", "promotions.events"."special_event" AS "promotions.events.special_event", "promotions.events.city"."id" AS "promotions.events.city.id", "promotions.events.city"."slug" AS "promotions.events.city.id", "promotions.events.city"."city" AS "promotions.events.city.city" FROM "merchants" AS "merchants" LEFT OUTER JOIN "promotions" AS "promotions" ON "merchants"."id" = "promotions"."merchant_id" LEFT OUTER JOIN "events" AS "promotions.events" ON "promotions"."id" = "promotions.events"."promotion_id" INNER JOIN "cities" AS "promotions.events.city" ON "promotions.events"."city_id" = "promotions.events.city"."id" LIMIT 20;

Result:
{
  "total_records": 1203,
  "total_pages": 61,
  "current_page": 1,
  "merchants": [ { ... }, ... ] //Only 12 items instead of expected 20 on this page!
}

Problem: The total records of 1203 is correct. However, on page 1 out of 61, I'm only seeing 12 merchants instead of the expected 20.

Any thought why is this happening/what am I doing wrong?

Thanks,
Ari

**Comment by asuwend1** [comment]
Have just found the answer: "subQuery: false" should be removed.

**Comment by asuwend1** [comment]
I am seeing this problem again... Have not found a workaround that works.
With pagination, the page 1 is expected to be full of records since the records count is high.

Code:
models.outlets.findAndCountAll({
            attributes: ['name', 'address', 'phone', 'distance','city_id','merchant_id'],
            include: [{model: models.merchants, attributes: ['id', 'name', 'slug', 'image','category_id'], include:[{model: models.categories, where: categoriesCondition, attributes: [['slug','id'],'name']}, {model: models.shares, attributes: ['url', 'city_id']}]}, {model: models.events, where: currentPromoCondition, attributes: ['id', 'start_at', 'end_at', 'special_event'], include:[{model: models.promotions, attributes: ['id', 'title', 'description','priority'], include:[{model: models.banks, where: banksCondition, attributes: ['id', 'name', 'slug', 'logo']}]}]}],
            offset: 0,
            limit: 20
        })


Generated SQL:
Executing (default): SELECT count(DISTINCT("outlets"."id")) AS "count" FROM "outlets" AS "outlets" LEFT OUTER JOIN "merchants" AS "merchant" ON "outlets"."merchant_id" = "merchant"."id" INNER JOIN "categories" AS "merchant.category" ON "merchant"."category_id" = "merchant.category"."id" INNER JOIN ("event_outlets" AS "events.event_outlets" INNER JOIN "events" AS "events" ON "events"."id" = "events.event_outlets"."event_id") ON "outlets"."id" = "events.event_outlets"."outlet_id" AND ("events"."start_at" <= '2015-10-29 04:55:50.566 +00:00' AND "events"."end_at" >= '2015-10-29 04:55:50.566 +00:00') LEFT OUTER JOIN "promotions" AS "events.promotion" ON "events"."promotion_id" = "events.promotion"."id" INNER JOIN "banks" AS "events.promotion.bank" ON "events.promotion"."bank_id" = "events.promotion.bank"."id";

Executing (default): SELECT "outlets".*, "merchant.category"."id" AS "merchant.category.id", "merchant.category"."slug" AS "merchant.category.id", "merchant.category"."name" AS "merchant.category.name", "merchant.shares"."id" AS "merchant.shares.id", "merchant.shares"."url" AS "merchant.shares.url", "merchant.shares"."city_id" AS "merchant.shares.city_id", "events"."id" AS "events.id", "events"."start_at" AS "events.start_at", "events"."end_at" AS "events.end_at", "events"."special_event" AS "events.special_event", "events.event_outlets"."id" AS "events.event_outlets.id", "events.event_outlets"."event_id" AS "events.event_outlets.event_id", "events.event_outlets"."outlet_id" AS "events.event_outlets.outlet_id", "events.event_outlets"."created_at" AS "events.event_outlets.created_at", "events.event_outlets"."updated_at" AS "events.event_outlets.updated_at", "events.promotion"."id" AS "events.promotion.id", "events.promotion"."title" AS "events.promotion.title", "events.promotion"."description" AS "events.promotion.description", "events.promotion"."priority" AS "events.promotion.priority", "events.promotion.bank"."id" AS "events.promotion.bank.id", "events.promotion.bank"."name" AS "events.promotion.bank.name", "events.promotion.bank"."slug" AS "events.promotion.bank.slug", "events.promotion.bank"."logo" AS "events.promotion.bank.logo" FROM (SELECT "outlets"."id", "outlets"."name", "outlets"."address", "outlets"."phone", "outlets"."distance", "outlets"."city_id", "outlets"."merchant_id", "merchant"."id" AS "merchant.id", "merchant"."name" AS "merchant.name", "merchant"."slug" AS "merchant.slug", "merchant"."image" AS "merchant.image", "merchant"."category_id" AS "merchant.category_id" FROM "outlets" AS "outlets" LEFT OUTER JOIN "merchants" AS "merchant" ON "outlets"."merchant_id" = "merchant"."id" WHERE ( SELECT "event_outlets"."id" FROM "event_outlets" AS "event_outlets" INNER JOIN "events" AS "event" ON "event_outlets"."event_id" = "event"."id" WHERE ("outlets"."id" = "event_outlets"."outlet_id") LIMIT 1 ) IS NOT NULL LIMIT 20) AS "outlets" INNER JOIN "categories" AS "merchant.category" ON "merchant.category_id" = "merchant.category"."id" LEFT OUTER JOIN "shares" AS "merchant.shares" ON "merchant.id" = "merchant.shares"."merchant_id" INNER JOIN ("event_outlets" AS "events.event_outlets" INNER JOIN "events" AS "events" ON "events"."id" = "events.event_outlets"."event_id") ON "outlets"."id" = "events.event_outlets"."outlet_id" AND ("events"."start_at" <= '2015-10-29 04:55:50.566 +00:00' AND "events"."end_at" >= '2015-10-29 04:55:50.566 +00:00') LEFT OUTER JOIN "promotions" AS "events.promotion" ON "events"."promotion_id" = "events.promotion"."id" INNER JOIN "banks" AS "events.promotion.bank" ON "events.promotion"."bank_id" = "events.promotion.bank"."id";

Result:
{
  "outlets": {
    "count": 1844,
    "rows": [{}... {}] //Only see 2 results here instead of 20!
}
//Only 2 records were returned for page 1 (I'm expecting a full 20 records since count is 1844)

Any thought what might be happening/workaround I can try?

Thanks,
Ari

**Comment by asuwend1** [comment]
Hi, was wondering if anybody have had a chance to look into this yet...

**Comment by mickhansen** [comment]
Honestly no, please format and try to reduce your issue, it's way too large for anything to quickly make sense of it.

**Comment by asuwend1** [comment]
Hi Mick,

Sorry, I didn't realize it's too large too analyze.
Here's the simplified version of what works and what does not work (expecting 20 records on page 1 since the count is larger than the limit of 20).

1. This works as it returns 20 rows
Code:
    findObject =  {
        attributes: ['id'],
        include: [{model: models.promotions, attributes: ['id'], include: [{model: models.events, attributes: ['id'], where: {id: {$gt:400}}}]}],
        offset: 0,
        limit: 20
    };

    models.merchants.findAndCountAll(findObject).then(function(allMerchants) {
        res.json(allMerchants);
    });

SQL:

Executing (default): SELECT count(DISTINCT("merchants"."id")) AS "count" FROM "merchants" AS "merchants" LEFT OUTER JOIN "promotions" AS "promotions" ON "merchants"."id" = "promotions"."merchant_id" INNER JOIN "events" AS "promotions.events" ON "promotions"."id" = "promotions.events"."promotion_id" AND "promotions.events"."id" > 400;

Executing (default): SELECT "merchants".*, "promotions"."id" AS "promotions.id", "promotions.events"."id" AS "promotions.events.id" FROM (SELECT "merchants"."id" FROM "merchants" AS "merchants" WHERE ( SELECT "merchant_id" FROM "promotions" AS "promotions" WHERE ("promotions"."merchant_id" = "merchants"."id") LIMIT 1 ) IS NOT NULL LIMIT 20) AS "merchants" LEFT OUTER JOIN "promotions" AS "promotions" ON "merchants"."id" = "promotions"."merchant_id" INNER JOIN "events" AS "promotions.events" ON "promotions"."id" = "promotions.events"."promotion_id" AND "promotions.events"."id" > 400;

Result:
{"count":1203,"rows":[{},...,{}]} //20 rows returned which is good

2. This does not work as expected... (another level of nest in the include)
Code:

    findObject =  {
        attributes: ['id'],
        include: [{model: models.promotions, attributes: ['id'], include: [{model: models.events, attributes: ['id'], include: [{model: models.event_outlets, attributes: ['id'], where: {id: {$gt:400}}}]}]}],
        //include: [{model: models.promotions, attributes: ['id'], include: [{model: models.events, attributes: ['id'], where: {id: {$gt:400}}}]}],
        offset: 0,
        limit: 20
    };

    models.merchants.findAndCountAll(findObject).then(function(allMerchants) {
        res.json(allMerchants);
    });

SQL:

Executing (default): SELECT count(DISTINCT("merchants"."id")) AS "count" FROM "merchants" AS "merchants" LEFT OUTER JOIN "promotions" AS "promotions" ON "merchants"."id" = "promotions"."merchant_id" LEFT OUTER JOIN "events" AS "promotions.events" ON "promotions"."id" = "promotions.events"."promotion_id" INNER JOIN "event_outlets" AS "promotions.events.event_outlets" ON "promotions.events"."id" = "promotions.events.event_outlets"."event_id" AND "promotions.events.event_outlets"."id" > 400;

Executing (default): SELECT "merchants".*, "promotions"."id" AS "promotions.id", "promotions.events"."id" AS "promotions.events.id", "promotions.events.event_outlets"."id" AS "promotions.events.event_outlets.id" FROM (SELECT "merchants"."id" FROM "merchants" AS "merchants" LIMIT 20) AS "merchants" LEFT OUTER JOIN "promotions" AS "promotions" ON "merchants"."id" = "promotions"."merchant_id" LEFT OUTER JOIN "events" AS "promotions.events" ON "promotions"."id" = "promotions.events"."promotion_id" INNER JOIN "event_outlets" AS "promotions.events.event_outlets" ON "promotions.events"."id" = "promotions.events.event_outlets"."event_id" AND "promotions.events.event_outlets"."id" > 400;

Result:
{"count":921,"rows":[{}...{}]} //11 rows returned instead of the expected 20



Any thought why the pagination is doing this? Or if there's any workaround for this?

Thank you,
Ari

**Comment by JSteunou** [comment]
It's kinda the same #4798 & #4716 `where` and `order` are sometimes on the all query whereas the `limit` is on the subquery.
