### ISSUE TITLE
Unhandled rejection SequelizeDatabaseError: column reference "id" is ambiguous

### ISSUE THREAD

**Issue by asuwend1** [sequelize/sequelize#4738]
=====Code   
 models.merchants.findOne({
        where: {slug: 'hotel-santika'},
        attributes: [['slug','id'], 'name', 'description', 'image'], // <------------['slug','idx'] works here
        include: [{model: models.shares, attributes: ['url']}, {model: models.outlets, attributes: ['id','name','address','phone','lat',['long','lng']]}, {model: models.promotions, attributes: ['priority','id','title','description'], include: [{model: models.events, required: false, attributes: ['id','start_at','end_at','special_event'], where: {$and: [{start_at: {$lte: currentDate}},{end_at: {$gte: currentDate}}]}}, {model: models.banks, required: false, attributes: [['slug', 'id'],'name','logo']}]}]
        })

=====PostgreSQL commands
Executing (default): SELECT "merchants".*, "shares"."id" AS "shares.id", "shares"."url" AS "shares.url", "outlets"."id" AS "outlets.id", "outlets"."name" AS "outlets.name", "outlets"."address" AS "outlets.address", "outlets"."phone" AS "outlets.phone", "outlets"."lat" AS "outlets.lat", "outlets"."long" AS "outlets.lng", "promotions"."priority" AS "promotions.priority", "promotions"."id" AS "promotions.id", "promotions"."title" AS "promotions.title", "promotions"."description" AS "promotions.description", "promotions.events"."id" AS "promotions.events.id", "promotions.events"."start_at" AS "promotions.events.start_at", "promotions.events"."end_at" AS "promotions.events.end_at", "promotions.events"."special_event" AS "promotions.events.special_event", "promotions.bank"."id" AS "promotions.bank.id", "promotions.bank"."slug" AS "promotions.bank.id", "promotions.bank"."name" AS "promotions.bank.name", "promotions.bank"."logo" AS "promotions.bank.logo" FROM (SELECT "merchants"."id", "merchants"."slug" AS "id", "merchants"."name", "merchants"."description", "merchants"."image" FROM "merchants" AS "merchants" WHERE "merchants"."slug" = 'hotel-santika' LIMIT 1) AS "merchants" LEFT OUTER JOIN "shares" AS "shares" ON "merchants"."id" = "shares"."merchant_id" LEFT OUTER JOIN "outlets" AS "outlets" ON "merchants"."id" = "outlets"."merchant_id" LEFT OUTER JOIN "promotions" AS "promotions" ON "merchants"."id" = "promotions"."merchant_id" LEFT OUTER JOIN "events" AS "promotions.events" ON "promotions"."id" = "promotions.events"."promotion_id" AND ("promotions.events"."start_at" <= '2015-10-27 08:25:03.458 +00:00' AND "promotions.events"."end_at" >= '2015-10-27 08:25:03.458 +00:00') LEFT OUTER JOIN "banks" AS "promotions.bank" ON "promotions"."bank_id" = "promotions.bank"."id";
=============
Error message:
Unhandled rejection SequelizeDatabaseError: column reference "id" is ambiguous
============

I believe the problem is in the attribute definition. Changing 'id' to something else is the workaround. 
I don't understand why I can't use 'id' there.

**Comment by mickhansen** [comment]
Please make an effort to format your issue.
Your model already has an `id` so renaming another field to it will clash, we automatically add `id` to `attributes` to properly do deduplication logic and other stuff.

**Comment by asuwend1** [comment]
Thank you for the explanation Mick!
