### ISSUE TITLE
timestamps are absent when using limit within include

### ISSUE THREAD

**Issue by bestan** [sequelize/sequelize#4740]
I noticed that timestamps are not passed to the instance when using limit within include (version `3.12.2`, postgres). 

Example that reproduces the issue:

```javascript
var Parent = sequelize.define('parent');
var Child = sequelize.define('child');
Parent.hasMany(Child);

//Sync etc.

Parent.create({
  children: [{
    id: 1
  }],
}, {
  include: [Child]
}).then(function(parent) {

  Parent.findAll({
    limit: 5,
    include: [{
      model: Child,
      limit: 5 //Removing limit brings 'created_at' back
    }]
  }).then(function(parents) {
    console.log(parents[0].children[0].created_at); //this is undefined when limit is specified
  });
});
```

Anything I'm doing wrong here?

**Comment by mickhansen** [comment]
Sounds odd, can you show the SQL query being run?

**Comment by bestan** [comment]
Sure

```sql
Executing (default): SELECT "parent"."id", "parent"."created_at", "parent"."updated_at" FROM "parents" AS "parent" LIMIT 5;
Executing (default): SELECT "child".* FROM ((SELECT "id", "created_at", "updated_at", "parent_id" FROM "children" AS "child" WHERE "child"."parent_id" = 1 LIMIT 5)) AS "child";
```

Running second statement (`SELECT "child".* ...`) returns all four columns - `id, parent_id, created_at and updated_at`

**Comment by mickhansen** [comment]
Odd, don't see any reason why it wouldn't work. Can you try logging `parents[0].children[0].dataValues`?

**Comment by bestan** [comment]
`parents[0].children[0].dataValues` returns `{ id: 1, parent_id: 1 }`

**Comment by mickhansen** [comment]
Appears to be a bug with how `separate` sets the values.

**Comment by mickhansen** [comment]
Specifically i think we're missing a `raw: true`.

**Comment by bestan** [comment]
@mickhansen confirming that it's fixed. Thanks!
