### ISSUE TITLE
belongsToMany eager loading get on duplicate non-unique foreign keys 

### ISSUE THREAD

**Issue by shaiherman** [sequelize/sequelize#4742]
Hi there - not sure if there's a better way to achieve what I need and/or if I have found a bug.

I'd like to allow multiple rows on a mapping table to have the same foreign keys.  As a result my belongsToMany is set with unique: false and the target has a primaryKey.  When I query one of the source models with eager loading, I receive only one of two rows that share the same foreign key combinations.  When I output the exact query Sequelize is using directly with my DB I receive the proper two rows.  It seems like Sequelize is still applying some uniqueness constraint with the correct output from the DB.

using postgres and Sequelize 3.12.2

Here's a paired down layout of models.

```
var UserObject = sequelize.define("UserObject", {
    uuid: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4
    }
});

var UserAttribute = sequelize.define("UserAttribute", {
  uuid: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4
  }
});
```

Here's the relationship between the two:

```
UserObject.belongsToMany(models.UserAttribute, { through: { model: models.UserObjectValue, unique: false } });
UserAttribute.belongsToMany(models.UserObject, { through: { model: models.UserObjectValue, unique: false } });
```

And here's paired down version of the mapping table:

```
var UserObjectValue = sequelize.define("UserObjectValue", {
  uuid: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4
  },
  value: {
    type: DataTypes.STRING(),
    allowNull: false,
    validate: {
      notEmpty: true
    }
  }
});
```

Sequelize query with eager loading:

```
models.UserObject.findAll({
  where: { user_uuid: req.user.getDataValue('uuid') },
    include: {
      model: models.UserAttribute,
    },
    logging: console.log
})
```

My test data

```
var userObjectValues = [{
  user_object_uuid: '5e068cce-15a1-4d37-b4e5-4439319d539e',
  user_attribute_uuid: '03f52441-dba2-4dae-8986-66ee8f6543cf',
  value: 'some value'
},{
  user_object_uuid: '5e068cce-15a1-4d37-b4e5-4439319d539e',
  user_attribute_uuid: '03f52441-dba2-4dae-8986-66ee8f6543cf',
  value: 'some other value with same foreign keys'
}]
```

When I receive back the resultant object from Sequelize, I only receive the second of these two values and not both as expected.  When I output the exact SQL and run that directly in my DB I do receive both rows.

**Comment by mickhansen** [comment]
`unique: false` support is not complete, so there's likely a bug somewhere yes, in this instance i think it's likely an issue with the deduplication logic we use.

**Comment by ansemjo** [comment]
I've hit the same issue and tried to trace the issue ..

All I can say so far is that it is caused somewhere in `groupJoinData` in [`/lib/dialects/abstract/query.js`](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query.js#L362). Because of the way the hashes are used as keys, any later duplicate simply overwrites the previous ones.

I don't fully understand the code yet but maybe that helps.

**Comment by miacelPereira** [comment]
I'm still having the same problem, even stating the 'unique: false' data is not duplicated.
Is there anything that can be done to work around this error?

**Comment by kd-krishna** [comment]
what is the solution for this has anyone figured out?

**Comment by imjordanxd** [comment]
I am also having this problem using V4. Does anyone have a workaround?

**Comment by ansemjo** [comment]
In my case I have simply resorted to creating duplicate entries in the database with unique primary keys – even if the `Process`' contents are absolutely identical. This may not be appropriate for larger applications due to the exploding number of rows however ..
