### ISSUE TITLE
Improve Unspported Dialect Error

### ISSUE THREAD

**Issue by alexbooker** [sequelize/sequelize#4747]
When instantiating Sequelize, I mistakenly specified the `dialect` value to be _"sqlite3"_ instead of _"sqlite"_ and got this error:

    Error: The dialect sqlite3 is not supported. (TypeError: Dialect is not a function)

I think this is is an easy mistake to make because the npm module for sqlite is called _"sqlite3"_.

It took me a couple of minutes to notice my error. 

I am yet to look at the code but I *imagine* the supported dialects are hard coded somewhere. 

What might have helped me realize my error quicker is a more descriptive error:

    Error: The dialect sqlite3 is not supported. Supported dialects: sqlite, mysql, etc. (TypeError: Dialect is not a function)

What do you think?

**Comment by mickhansen** [comment]
Sounds good, PR welcome.

**Comment by alexbooker** [comment]
I'll try my hand at this.
