### ISSUE TITLE
Upsert fails when primary key attribute and field names differ

### ISSUE THREAD

**Issue by BigDataSamuli** [sequelize/sequelize#4755]
I'm getting unique constraint violation errors when using upsert with models that have primary keys with custom DB field names. For example:

```javascript
var UpsertTestModel = sequelize.define(
    "UpsertTest",
    {
        testKey: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            field: "test_key"
        },
        value: {
            type: Sequelize.INTEGER
        }
    },
    {
        tableName: "upsert_test"
    }
).sync({ force: true });

UpsertTestModel.then(model => {
    return model.upsert({
        testKey: 1,
        value: 1
    }).then(() => {
        return model.upsert({
            testKey: 2,
            value: 1
        });
    }).then(() => {
        return model.upsert({
            testKey: 2,
            value: 2
        });
    });
}).done();
```

The third upsert will fail with SequelizeUniqueConstraintError. Removing the custom field name definition from the model will make the code work.

With a quick look, it seems like QueryInterface.prototype.upsert is trying to create a where-clause with the primary key values, but it's looking for the primary key attribute names in the values argument, which contains the values by field name instead. Thus, no where clause is created and the SQL UPDATE (in Postgres) fails.

**Comment by janmeier** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/5298
