### ISSUE TITLE
Possible issue with pagination

### ISSUE THREAD

**Issue by asuwend1** [sequelize/sequelize#4757]
Hi,

I am seeing "Unhandled rejection SequelizeDatabaseError: column outlets.merchant_id does not exist" with pagination. No problem without pagination. Anything I missed?

This works fine:
models.outlets.findAndCountAll({
            attributes: ['name', 'address', 'phone', 'distance','city_id'],
            include: [ {model: models.merchants}, {model: models.events}]
        };)

Resulting in this SQL:
Executing (default): SELECT count(*) AS "count" FROM "outlets" AS "outlets";
Executing (default): SELECT "outlets"."id", "outlets"."name", "outlets"."address", "outlets"."phone", "outlets"."distance", "outlets"."city_id", "merchant"."id" AS "merchant.id", "merchant"."category_id" AS "merchant.category_id", "merchant"."name" AS "merchant.name", "merchant"."slug" AS "merchant.slug", "merchant"."icon" AS "merchant.icon", "merchant"."image" AS "merchant.image", "merchant"."description" AS "merchant.description", "merchant"."created_at" AS "merchant.created_at", "merchant"."updated_at" AS "merchant.updated_at", "merchant"."tags" AS "merchant.tags", "merchant"."low_price" AS "merchant.low_price", "merchant"."hi_price" AS "merchant.hi_price", "events"."id" AS "events.id", "events"."promotion_id" AS "events.promotion_id", "events"."city_id" AS "events.city_id", "events"."start_at" AS "events.start_at", "events"."end_at" AS "events.end_at", "events"."created_at" AS "events.created_at", "events"."updated_at" AS "events.updated_at", "events"."is_hot" AS "events.is_hot", "events"."hot_deal_priority" AS "events.hot_deal_priority", "events"."special_event" AS "events.special_event", "events"."redeem_code" AS "events.redeem_code", "events"."redeem_availability" AS "events.redeem_availability", "events"."redeem_remaining" AS "events.redeem_remaining", "events"."redeem_waiting_period" AS "events.redeem_waiting_period", "events"."redeem_time" AS "events.redeem_time", "events"."redeem_day" AS "events.redeem_day", "events.event_outlets"."id" AS "events.event_outlets.id", "events.event_outlets"."event_id" AS "events.event_outlets.event_id", "events.event_outlets"."outlet_id" AS "events.event_outlets.outlet_id", "events.event_outlets"."created_at" AS "events.event_outlets.created_at", "events.event_outlets"."updated_at" AS "events.event_outlets.updated_at" FROM "outlets" AS "outlets" LEFT OUTER JOIN "merchants" AS "merchant" ON "outlets"."merchant_id" = "merchant"."id" LEFT OUTER JOIN ("event_outlets" AS "events.event_outlets" INNER JOIN "events" AS "events" ON "events"."id" = "events.event_outlets"."event_id") ON "outlets"."id" = "events.event_outlets"."outlet_id";

BUT the same thing with pagination caused error:
models.outlets.findAndCountAll({
            attributes: ['name', 'address', 'phone', 'distance','city_id'],
            include: [ {model: models.merchants}, {model: models.events}],
            offset: 0,
            limit: 20
        };)
Which resulted in the following:
Executing (default): SELECT count(*) AS "count" FROM "outlets" AS "outlets";
Executing (default): SELECT "outlets".*, "merchant"."id" AS "merchant.id", "merchant"."category_id" AS "merchant.category_id", "merchant"."name" AS "merchant.name", "merchant"."slug" AS "merchant.slug", "merchant"."icon" AS "merchant.icon", "merchant"."image" AS "merchant.image", "merchant"."description" AS "merchant.description", "merchant"."created_at" AS "merchant.created_at", "merchant"."updated_at" AS "merchant.updated_at", "merchant"."tags" AS "merchant.tags", "merchant"."low_price" AS "merchant.low_price", "merchant"."hi_price" AS "merchant.hi_price", "events"."id" AS "events.id", "events"."promotion_id" AS "events.promotion_id", "events"."city_id" AS "events.city_id", "events"."start_at" AS "events.start_at", "events"."end_at" AS "events.end_at", "events"."created_at" AS "events.created_at", "events"."updated_at" AS "events.updated_at", "events"."is_hot" AS "events.is_hot", "events"."hot_deal_priority" AS "events.hot_deal_priority", "events"."special_event" AS "events.special_event", "events"."redeem_code" AS "events.redeem_code", "events"."redeem_availability" AS "events.redeem_availability", "events"."redeem_remaining" AS "events.redeem_remaining", "events"."redeem_waiting_period" AS "events.redeem_waiting_period", "events"."redeem_time" AS "events.redeem_time", "events"."redeem_day" AS "events.redeem_day", "events.event_outlets"."id" AS "events.event_outlets.id", "events.event_outlets"."event_id" AS "events.event_outlets.event_id", "events.event_outlets"."outlet_id" AS "events.event_outlets.outlet_id", "events.event_outlets"."created_at" AS "events.event_outlets.created_at", "events.event_outlets"."updated_at" AS "events.event_outlets.updated_at" FROM (SELECT "outlets"."id", "outlets"."name", "outlets"."address", "outlets"."phone", "outlets"."distance", "outlets"."city_id" FROM "outlets" AS "outlets" LIMIT 20) AS "outlets" LEFT OUTER JOIN "merchants" AS "merchant" ON "outlets"."merchant_id" = "merchant"."id" LEFT OUTER JOIN ("event_outlets" AS "events.event_outlets" INNER JOIN "events" AS "events" ON "events"."id" = "events.event_outlets"."event_id") ON "outlets"."id" = "events.event_outlets"."outlet_id";

ERROR:
Unhandled rejection SequelizeDatabaseError: column outlets.merchant_id does not exist

Thanks,
Ari

**Comment by mickhansen** [comment]
`merchant_id` is not selected from the inner query so not available to the outer query.
You need to add the foreign key to your `attributes` as a work around.

We should add a mechanism for automatically adding foreign keys to `attributes` if required.

**Comment by asuwend1** [comment]
The workaround works. Thank you Mitch!
