### ISSUE TITLE
sequelize find and update  transaction not  rollback

### ISSUE THREAD

**Issue by Mararesliu** [sequelize/sequelize#4758]
User.update(attr, {transaction: t}) can not rollback, it seem like transaction can not inject.

**Comment by Mararesliu** [comment]
only support create.

**Comment by mickhansen** [comment]
You'll need to be more specific in this case.
Both bulk update and instance update should support transactions.

Please include relevant logs, code and errors.

**Comment by Mararesliu** [comment]
ok, thanks.
