### ISSUE TITLE
Unable to execute Model.update as a part of transaction (Sequelize 3.12.2)

### ISSUE THREAD

**Issue by manjuiotlabs** [sequelize/sequelize#4759]
The code is simple code:
return db.sequelize.transaction(function (t) {
    return Model.update({x: 10}, {where: {id>0}}, {transaction: t}).then(function() {
         A line to cause an EXCEPTION
    });
});

On exception, Sequelize logging shows ROLLBACK, but the update x=10 persists despite the ROLLBACK. This is because, my guess is, update is not executing as a part of transaction 't'.

Instead of Model.update, if I use object[].updateAttributes(), everything is fine: ROLLBACK removes the change x=10.

Thanks!

**Comment by janmeier** [comment]
The transaction should be in the second object (the same as `.where`) - right now you are passing 3

**Comment by manjuiotlabs** [comment]
Thanks! So stupid of me. I should have read the docs more carefully!
