### ISSUE TITLE
[Transaction] add onCommit, onRollback events

### ISSUE THREAD

**Issue by umidbekkarimov** [sequelize/sequelize#4760]
I have `sms service` that creates sms in database and send it to `rabbitmq`,

````javascript
// transaction is optional
static *createAuthCode(userInfo, transaction) {
    // lot of code that creates user and auth code to send via sms

     const text = `Your secret code is: ${code}`;
     yield SmsService.createOne(ActionTypes.SEND_AUTH_CODE, identity, text);
}
````

Currently i have to send sms body in message to `rabbitmq`, and even if transaction will be rollbacked, sms will be sent, so i need something like: 

````javascript
// transaction is optional
static *createAuthCode(userInfo, transaction) {
    // lot of code that creates user and auth code to send via sms
     
     if (transaction) {
         transaction.onCommit(() => AuthService.sendAuthCode(authCode.get('id')));
     } else {
         AuthService.sendAuthCode(authCode.get('id'));
     }     
}

static sendAuthCode(id) {
    return SmsService.createOne(ActionTypes.SEND_AUTH_CODE, id);
}
````

Also in this case auth code is committed in db, so i can send only auth code id, and topic subscriber can take all data from db by id

**Comment by mickhansen** [comment]
There's another issue for this. The solution could just be to attach the promise to the transaction object so hooks etc can listen on `transaction.promise.then|catch`

**Comment by umidbekkarimov** [comment]
@mickhansen oh, that awesome, thanks

**Comment by sushantdhiman** [comment]
Moved to #2805
