### ISSUE TITLE
unique constraint not working with MySQL

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#4766]
From migration script, using `createTable`, setting a constraint `unique` (true or a name) on a field has no effect. I tried both syntaxes, on field property, and the `indexes` table property.

**Comment by mickhansen** [comment]
We don't support indexes via createTable at the moment.
For model.sync() the indexes are created seperately, not as part of the createTable statement.

**Comment by JSteunou** [comment]
Ho ok, I just tested a bit more, and it appears to work on simple unique index, but not with *multiple columns* or *named* index

**Comment by mickhansen** [comment]
That is probably true since `UNIQUE` can be added to a column definition during a create table statement for a single unique column.

Not possible with composite/named though.

**Comment by JSteunou** [comment]
ok, I used queries to add it manually. Should I close this issue then or do you wanna keep it as an enhancement reminder?

**Comment by mickhansen** [comment]
We are aware of it in other issues.
