### ISSUE TITLE
adding searchPath options to queries doesnt work

### ISSUE THREAD

**Issue by kheide** [sequelize/sequelize#4771]
Hi, 

I am trying to make sequelize behave in a multi-tenant way by dynamically adding the searchpath to queries. If I do this: 

```javascript
models.Users.findAll({searchPath: 'customerB'}).then(function (users) {
```
I should expect it to search that schema, but instead the SQL looks like this: 

```sql
Executing (default): SELECT "id", "email", "password", "enabled", "createdAt", "updatedAt" FROM "Users" AS "Users";
```

**Comment by janmeier** [comment]
Hmm, should work - which version are you on?

**Comment by kheide** [comment]
3.12.2 

What I can get to work is the sequelize.createSchema and then use .sync() to create the tables on that schema. All well so far, but the CRUD methods I am unsuccessful in getting to work with schemas. 

Can you confirm that my syntax above for findAll() is correct? Also would it be the same for create() ?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L758

(this is not documented)

You need to enable search paths globally first.

```js
new Sequelize(/* ... */, {
  dialectOptions: {
    prependSearchPath: true
  }
});
```

**Comment by kheide** [comment]
Thank you @mickhansen ! That did the trick.

**Comment by ricardompb** [comment]
you can try it...


const connection = new Sequelize(database, username, password, {
      dialect: 'postgres',
      host,
      logging: true,
      repositoryMode: true,
      dialectOptions: {
        options: `-c search_path=${schema}`,
      },
    });
