### ISSUE TITLE
Eager loading max (newest, oldest, etc) association only

### ISSUE THREAD

**Issue by khanlou** [sequelize/sequelize#4772]
I've done a fair bit of googling for this and can't seem to find anything about how to do it in Sequelize (or really in Rails's ORM either). Basically, I have a `hasMany` parent/child association, and I'd like to be able to load the first child only.

My service has a concept of threads and messages; when fetching the 20 most recent threads, I also want to be able to fetch the most recent message in each (so I can display a little preview). As far as I can tell, these are the only ways to do this:

1. Duplicate the data from the most recent message in the thread model (lame)
2. Fetch the 20 most recent threads, then fetch the most recent message of each with a separate query (n+1 query problem)
3. Fetch the 20 most recent threads, then fetch all of the most recent messages with a single `WHERE..IN`-type query (complicated)
4. Use Sequelize's normal eager loading to load every message in all 20 threads and then limit them once they're in memory (doesn't scale well)
4. Totally custom SQL (ugly/not portable)

In regular SQL (MSSQL variant) I might do this with a subquery:

    SELECT * FROM threads
    INNER JOIN messages ON threads.id = messages.thread_id
    AND messages.created_at = (
        SELECT MAX(created_at) FROM messages WHERE thread_id = threads.id
    )
    ORDER BY posted_at DESC
    OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY

As far as I've seen, this isn't a common feature in ORMs, even though it seems like it would be super useful. Are there any better ways to do it than the ones I've listed here?

**Comment by mickhansen** [comment]
hasMany supports `include.separate` so you can give `include.limit = 1` with `include.order = [['createdAt', 'DESC']]`

**Comment by khanlou** [comment]
I'm not quite understanding how the outputted SQL works, but it works amazingly. Thank you so much!

**Comment by mickhansen** [comment]
@khanlou It's a way to solve limit-n-per-group which you're looking to do here :)
But basically it first fetches your threads, then it does a query for each thread to find messages and unions them together (so you save a roundtrip)

**Comment by khanlou** [comment]
I thought this was working, but I wasn't looking closely enough.

Here's my fetch query:
    
    Thread.findAll({
      where: {
        channel_id: req.query.channelID,
      },
      include: [
        {
          model: Message,
          as: "messages",
          include: { model: User, as: "author", include: [{ model: Attachment }] },
          order: [
            ["asdfasdf", "ASC"]
          ],
          limit: "a fake string",
        },
      ],
      order: [
        ["__createdAt", "DESC"],
      ],
      offset: (req.query.page-1 || 0)*20,
      limit: 20,
    }).then(function(threads) {
      res.sendJSON({ threads: threads });
    }).catch(function(error) {
      res.sendError(error, "There was an error getting the threads.");
    });

Note that the `order` of the included `messages` is set to "asdfasdf", and the `limit` is set to "a fake string". neither of those appear in [the outputted SQL](https://gist.github.com/khanlou/40d0594bb44ae9c7d4ba). What am I doing wrong here?

There's a second issue, where I want the threads to be listed by the order of the most recent messages, not the threads. I don't think I can access the messages association from the outer `order`, so i think I need to update the thread's `__updatedAt` every time there's a new message in the thread. Is there a better way to do that?

**Comment by khanlou** [comment]
Looks like it was a combination of issues, including being on version 3.2.0 and not using the `separate: true` key pair, which I didn't know was explicitly necessary.

Now that I've upgraded to 3.13.0 I'm seeing some other issues. Will report back when I've fixed them.

**Comment by khanlou** [comment]
I'm still seeing an issue here. My query is working, unless I include a sub-sub-include (in this case, attachments, which represent the user's avatar). Here is my query:

    Thread.findAll({
        where: {
          channel_id: req.query.channelID,
        },
        include: [
          {
            model: Message,
            include: { model: User, include: [{ model: Attachment }] },
            order: [
              ["__createdAt", "DESC"]
            ],
            limit: 1,
          },
        ],
        order: [
          ["__createdAt", "DESC"],
        ],
        offset: (req.query.page-1 || 0)*20,
        limit: 20,
      })

You can find the outputted [SQL here](https://gist.github.com/khanlou/e1d71d166658db2209c8) (MSSQL). I've added a few line breaks to make it easier to read.

This issue is the last line:

    LEFT OUTER JOIN [attachments] AS [user.attachment] ON [user.attachment_id] = [user.attachment].[id];

I get a `SequelizeDatabaseError: Invalid column name 'user.attachment_id'.` If I manually change it to:

    LEFT OUTER JOIN [attachments] AS [user.attachment] ON [user].[attachment_id] = [user.attachment].[id];

identifying the table and column separately, it works correctly. For some reason, the fake column that this SQL is creating (`user.attachment_id`) isn't valid, and referring to them by table and column separately makes it work, and I can't figure out why.

I can't tell if this is a Sequelize bug or just a quirk in MSSQL or something.
