### ISSUE TITLE
Can sequelize support execut transaction in sequence?

### ISSUE THREAD

**Issue by Mararesliu** [sequelize/sequelize#4774]
As titled. I only see Concurrent/Partial transactions? if can, how? pls.

**Comment by janmeier** [comment]
What do you mean? Separate transactions should  run in sequence? Or the operations in a transaction should run in sequence?

**Comment by Mararesliu** [comment]
i mean transaction one by one. second can get first result. not just Concurrent.

**Comment by janmeier** [comment]
`sequelize.transaction(function hereYouDoTransaction).then(function hereYouCreateTheNext) ` 

The then callback is called when the transaction is committed or rolled back. So yes you can definitely run transactions serially

**Comment by Mararesliu** [comment]
ok, many thanks

**Comment by Mararesliu** [comment]
sorry, i had tried, it's not i want, sequelize.transaction(function hereYouDoTransaction).then(function hereYouCreateTheNext("this Transaction has been committed, but i want to do more Transaction and then commit or rollback"))

**Comment by Mararesliu** [comment]
done, then( throw new Error)

**Comment by mickhansen** [comment]
@Mararesliu You're not being clear at all, are you familiar with how promises work?
If you are looking for database based sequential transactions you need to lock your table appropriately.
Depending on the type of locking you need, you may have to execute a raw query.
