### ISSUE TITLE
Models don't have association set methods... sometimes

### ISSUE THREAD

**Issue by OscarGodson** [sequelize/sequelize#4775]
I have this in my association file

```js
  Calendars.hasMany(EventGroups);
```

And I try to get EventGroups like so

```js
    CalendarModel.findById(req.params.id).then(function (calendar) {
      calendar.getEventGroups().then(function (eventGroups) {
        console.log(eventGroups);
        res.send(eventGroups);
      });
    });
```

But I just get

```
Unhandled rejection TypeError: Object [object SequelizeInstance:calendar] has no method 'getEventGroups'
```

I'm not sure the issue since I have a very similar setup, but more complex, for Users and Calendars which is

```
  Users.belongsToMany(Calendars, { through: 'calendar_membership' });
```

Then

```
    UserModel.findById(userSession.id).then(function (user) {
      user.getCalendars().then(function (calendars) {
        console.log(calendars);
      });
    });
```

And that works perfectly. Here's the EventGroup model:

```js
var EventGroup = Model.define('event_group', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4, // Generates a UUID V4
    primaryKey: true
  },
  calendar_id: {
    type: Sequelize.UUID,
    allowNull: false
  }
}, {
  underscored: true
});
```

I'm not sure what the difference is here and why the simpler association is failing.

**Comment by mickhansen** [comment]
The naming might be wonky, try logging `Object.keys(UserModel.Instance.prototype)`

**Comment by janmeier** [comment]
We try to change the model name as little as possible - so the function is called `getEvent_group`

You can either pass `as: 'EventGroups` to the association function, or change the name of the model (you can still have the table underscored using `tablename`)

**Comment by OscarGodson** [comment]
Ah! That did it `calendar.getEvent_groups()`.

I'll use the `as:`. I wasn't sure what the generated method would be called. I was trying to log out different things but couldn't ever find the method names console logged out so this `Object.keys(UserModel.Instance.prototype)` is super handy to know. 

Thanks!
