### ISSUE TITLE
Problem with upsert

### ISSUE THREAD

**Issue by dengyaolong** [sequelize/sequelize#4776]
Hello, I meet a problem when i use upsert.

I want to write a sql like (mysql)

```
INSERT INTO `production` (`id`,`pid`,`ptype`, `cnt`) VALUES (DEFAULT,1,1, 1) ON DUPLICATE KEY UPDATE `cnt`=`cnt`+1;
```

the unique key is `(pid, ptype)`;

when i use squelize's upsert

```
Production.upsert({
    pid: 1,
    ptype: 1,
    cnt:  //????how to let cnt+=1?I use Sequelize.literal('cnt+1'), it dones't work.
})
```

And now ,I use Production.create(..., {onDuplicate: 'UPDATE cnt=cnt+1'})
But , it looks so dirty.

**Comment by crzidea** [comment]
👍+1

**Comment by dengyaolong** [comment]
@mickhansen

**Comment by mickhansen** [comment]
Don't believe we support values doing something differently for update, but we'll have to ask @janmeier
