### ISSUE TITLE
Problem with destroy hooks on n:m association

### ISSUE THREAD

**Issue by kiddouk** [sequelize/sequelize#4777]
Hi,

I am having a weird behavior despite applying what the documentation says.

I have 2 models and an n:m association via a ```through``` table. On that association, I define a hook ```afterCreate``` and it works just great when I add an association with ```post.addLikingUser(user)```

I also made sure to add the ```onDelete:'cascade', hooks: true``` options for the association. Nonetheless, the beforeDestroy/afterDestroy are never called when calling ```post.removeLikingUser(user)```

What am I missing ? 

The code (in coffeescript).

```coffee
Post = sequelize.define 'Post',
  {text:
    type: Sequelize.STRING, default: "Not set"
  ...
  },{
  getterMethods:
    createdAt: () ->
      moment(@getDataValue 'createdAt').format 'x'
    updatedAt: () ->
      moment(@getDataValue 'updatedAt').format 'x'
  }

PostLikedByUser = sequelize.define 'PostLikedByUser',
  {
    date:
      type: Sequelize.DATE, defaultValue: sequelize.NOW
  },
  {
    hooks: {
      beforeDestroy: (relation, options) ->
        console.log "beforeDestroy"
      afterDestroy: (relation, options) ->
        console.log "afterDestroy"
    }
  }


User = sequelize.define "User",
  device_id:
    type: Sequelize.STRING
  is_admin:
    type: Sequelize.BOOLEAN, defaultValue: false
  lastLoginAt:
    type: Sequelize.DATE, defaultValue: Sequelize.NOW


Post.belongsToMany User, {as: 'LikingUser', through: 'PostLikedByUser', onDelete: 'cascade', onUpdate: 'cascade', hooks: true}
User.belongsToMany Post, {as: 'LikedPost', through: 'PostLikedByUser', onDelete: 'cascade', onUpdate: 'cascade', hooks: true}

```

**Comment by mickhansen** [comment]
As discussed on slack a `removeAssociation` call for `N:M` uses `Model.destroy` (bulk destroy) internally so the `individualHooks: true` option is needed to run a hook on each affected instance.

**Comment by kiddouk** [comment]
While discussing with @mickhansen about that problem, it rutns out that 

1) remove call will trigger bulkDestroy
2) remove call supports ```individualHooks: true``` option in order to trigger individual after/beforeHooks.

I willl make a doc PR on that to fix that issue here.
