### ISSUE TITLE
Adding properties to objects to return for responses

### ISSUE THREAD

**Issue by OscarGodson** [sequelize/sequelize#4781]
I'm running into a bizarre issue with Express + Sequelize. Express doesn't seem to want to spit out all of the object. If I manually do `response.calendar.event_groups` it returns that fine, but if I just do `response` or `response.calendar` it _only_ returns the calendar object, not `event_groups`

```js
    CalendarModel.findById(req.params.id)
    .then(function (calendar) {
      // Save the calendar in the response
      response.calendar = calendar;

      calendar.getEventGroups().then(function (eventGroups) {
        response.calendar.event_groups = [];
        // For each event group put it in the calendar response
        eventGroups.forEach(function (eventGroup) {
          response.calendar.event_groups.push(eventGroup);
        });
        res.send(response)
      });
    })
```

Above just returns

```json
{
  "calendar": {
    "id": "75f7f8a9-6aef-47ab-8271-e66e856b5db3",
    "title": "my calendar",
    "created_at": "2015-10-14T00:15:33.000Z",
    "updated_at": "2015-10-14T00:15:33.000Z"
  }
}
```

Maybe I'm doing it wrong? It's setup where Calendar is the parent of EventGroups and EventGroups is the parent of Events. I want to list all EventGroups with all of their Events inside of that. I figured that was a manual thing (get all event groups, get all events in event groups, put all in a response object), but it doesn't seem to work to add it manually then return it in a response for some reason.

I also tried cloning the `calendar` and `eventGroup` but that just caused `circular structure` errors :\

Oh, and I also tried just pure `response.calendar.event_groups = eventGroups;` which also did not work

**Comment by mickhansen** [comment]
`response.calendar` is a Sequelize Instance.
When you do res.send express calls toJSON which on a Sequelize Instance is defined to return `.get()` which returns its internal data values, not properties on the instance.

Solution: `response.calendar = calendar.toJSON()`.
Or just use prefetching.

**Comment by OscarGodson** [comment]
Ah, I thought toJSON actually made it JSON (like the string). thank you!

**Comment by mickhansen** [comment]
@OscarGodson toJSON is for converting into a object that can be serialized to a JSON string, in the Sequelize case we go from a special object to a POJO.
