### ISSUE TITLE
Sequelize Associated Table Attributes Appear as Nested objects in results

### ISSUE THREAD

**Issue by tejalshah84** [sequelize/sequelize#4783]
Hi All,

Need help with my project. I have joined two tables in sequelize: User and Announcement. When I execute a findAll query, the results show me values from the User table as a nested objected within announcement object. How can I get the user attributes to appear at the same level as announcement attributes, just like a normal sql query.

user.hasMany(announce, {foreignKey: 'publisher_username'});
announce.belongsTo(user, {foreignKey: 'publisher_username', targetKey: 'username'});

Announce.findAll({
				  attributes: ['id','publisher_username', 'content', 'createdAt'],
				  where: {
				    content: {
				    	$like: searchtxt
				    }
				  },
				  include: [{model: User, attributes: ['location']}],
				  order:'announcement.createdAt DESC',
				  offset: pageCount,
				  limit: 10
				  }).then(function (announcements) {
					  res.json(announcements);
				});

Resulting Query:
SELECT `announcement`.`id`, `announcement`.`publisher_usern
ame`, `announcement`.`content`, `announcement`.`createdAt`, `user`.`username` AS
 `user.username`, `user`.`location` AS `user.location` FROM `announcement` AS `a
nnouncement` LEFT OUTER JOIN `user` AS `user` ON `announcement`.`publisher_usern
ame` = `user`.`username` WHERE `announcement`.`content` LIKE '%hi%' ORDER BY ann
ouncement.createdAt DESC LIMIT 10;

Query Results:

Object {
content: "This is another new announcement!"
createdAt: "2015-10-24T09:08:15.729Z"
id: 21
publisher_username: "Test"
user: Object {
                  location: "Mountain View, CA"
          }
}

Don't want User to appear as a nested object. Just need location to appear as a property in the parent object.

Thank you.

**Comment by janmeier** [comment]
You can't - you'll have to format the result yourself.

Adding a nested property is just how includes work. You could add the code in a `toJSON` instance method, that way you don't have to format the result each time.

**Comment by tejalshah84** [comment]
Is there any other way to query associations without using include?

**Comment by janmeier** [comment]
```js
Announce.findAll().then(function (announces) {
  announces[0].getUser();
});
```
