### ISSUE TITLE
Sequelize doesn't escape column names in postgres  

### ISSUE THREAD

**Issue by niksrc** [sequelize/sequelize#4784]
```
Catalog.update({
      order: 'order + 1'
},{
  where:{
    order:{
     $between :[2,5] 
   }
  }
}).then(function(response){
      console.log(response)
});

```

This gives a sequelizeDatabaseError near or at order.

**Comment by mickhansen** [comment]
Have you taken a look at the SQL query?
In this case you're actually telling Sequeliz you want to update the `order` column to a string, which it likely doesn't support.

**Comment by niksrc** [comment]
I understand that. I'm just asking if it should support escaping column names by default.

**Comment by niksrc** [comment]
I had to build raw query string for the update.

**Comment by mickhansen** [comment]
@niksrc Are you saying that `order` in `where` is not escaped? That would be very odd, we have unit tests for that sort of thing.

When reporting issues with SQL generation, its generally helpfull to actually post the SQL.

**Comment by niksrc** [comment]
Sorry, my bad the generated SQL is escaped properly.Thanks :)
