### ISSUE TITLE
Find on association generating incorrect SQL?

### ISSUE THREAD

**Issue by HolySamosa** [sequelize/sequelize#4786]
I'm trying to perform a find using a field on an associated model, however the generated SQL is performing the the where on a column on the 'Case' table, rather than the associated 'Messageable' table, aliased as 'texter':

```
{
  "name": "SequelizeDatabaseError",
  "message": "SQLITE_ERROR: no such column: Case.texter.mobile",
  "parent": {
  "errno": 1,
    "code": "SQLITE_ERROR",
    "sql": "SELECT `Case`.`id`, `Case`.`createdAt`, `Case`.`updatedAt`, `Case`.`texterId`, `texter`.`id` AS `texter.id`, `texter`.`handle` AS `texter.handle`, `texter`.`mobile` AS `texter.mobile`, `texter`.`type` AS `texter.type` FROM `Cases` AS `Case` LEFT OUTER JOIN `Messageables` AS `texter` ON `Case`.`texterId` = `texter`.`id` WHERE `Case`.`texter.mobile` = '123' LIMIT 1;"
}
```

Here's my find query:

    models.Case.find({
      where: {'texter.mobile': '15556666'},
      include: [{model: models.Messageable, as: 'texter'}]
    })

And the association:

    Case.belongsTo(models.Messageable, { as: "texter"});

Am I doing something wrong here, or is this a Sequelize issue?  Looks like I can work around it using  `sequelize.literal`  for the where clause.

**Comment by janmeier** [comment]
You should add the where to the include, which will add it the the `ON` clause or use `$texter.mobile$` as the key, which adds it to the `WHERE ` clause

**Comment by HolySamosa** [comment]
Thanks!  `$texter.mobile$` did the trick.

Also, I didn't actually ask the proper question.  I was actually querying with `findOrCreate` which will throw the following exception if the `where` is moved to `include`:

```
Error: Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only (an object with where, defaults keys, transaction etc.)
```

I had read about moving the where to the include when querying associations in the docs.  Maybe use of `$foo.bar$` this is worth adding there as well?
