### ISSUE TITLE
Cannot set null to attribute when update a model

### ISSUE THREAD

**Issue by thakerng** [sequelize/sequelize#4792]
Why cannot set null anymore ,I've already set omitNull = true. this feature is very important why cut off this feature? 

```Task.update({status: null},{where:{id:1}})```

**Comment by mickhansen** [comment]
You shouldn't set `omitNull` if you actually want to set NULL values.
When opening issues please follow the contribution guide.
When dealing with failing queries, PLEASE include the SQL.
