### ISSUE TITLE
Foreign Key / Target Key setting ignored

### ISSUE THREAD

**Issue by jamesaspence** [sequelize/sequelize#4793]
I have two models: an `Order` and a `Customer`. A customer can have many orders, each order belongs to one customer. To that end, I have the two lines as such:

    Order.belongsTo(Customer, {foreignKey: 'local_customer_id', targetKey: 'id'});
    Customer.hasMany(Order, {foreignKey: 'id', targetKey: 'local_customer_id'});

The idea being that the `Order` table has a `local_customer_id` column, that maps to the `id` column on the `Customer` table.

However, my query doesn't seem to respect that:

    INNER JOIN `orders` AS `orders` ON `customer`.`id` = `orders`.`id` AND (`orders`.`deleted_at` IS NULL AND `orders`.`order_id` = '10000');

Any idea why this is happening? Am I doing something wrong?

I attempted to keep my code example short for clarity, let me know if more is needed.

**Comment by janmeier** [comment]
You should use `foreignKey: 'local_customer_id'` on both http://docs.sequelizejs.com/en/latest/api/associations/

**Comment by jamesaspence** [comment]
Ahh, I see... I must have missed that first little section. That makes more sense. Thanks!
