### ISSUE TITLE
How about take cps style in model query

### ISSUE THREAD

**Issue by superlbr** [sequelize/sequelize#4795]
I use waterline before,I like that style,looks like this.
![image](https://cloud.githubusercontent.com/assets/8142164/10900022/d8f0cbd2-8215-11e5-86c6-321294234293.png)

So I could catch error easliy

**Comment by mickhansen** [comment]
That would be a complete rewrite, so likely not.
In any case Promises are to be preferred to callbacks in my opinion, error catching in promises is way easier imho.
