### ISSUE TITLE
version "3.3.2", always throw Too many connection

### ISSUE THREAD

**Issue by kidyfirst** [sequelize/sequelize#4797]
2015-11-01 15:40:46.409|******|********|server error { [SequelizeAccessDeniedError:     ER_ACCESS_DENIED_ERROR: Access denied for user '******'@'*********:38571' Too many
    connection]
    name: 'SequelizeAccessDeniedError',
    message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'******\'@\'*********:38571\' Too   many connection',
      parent:
      { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user '******'@'******:38571' Too many connection]
       code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true },
     original:
       { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user '******'@'******:38571' Too many  connection]
       code: 'ER_ACCESS_DENIED_ERROR',
       errno: 1045,
       sqlState: '28000',
       fatal: true } }
    SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user  '****'@'****:38571' Too many connection
        at Handshake._callback (****/node_modules/sequelize/lib/dialects/mysql/connection-    manager.js:51:20)
        at Handshake.Sequence.end (****/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.ErrorPacket (****/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
    at Protocol._parsePacket (****/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (****/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (****/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (****/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20) { request:
  

and we have monitored the mysql connection count,  there are too many sleep count.
who can provide some suggestions?

**Comment by mickhansen** [comment]
How many instances of your app are you running?
Are you restarting the app often? (are you gracefully exiting?)
What's the timeout on the server?

**Comment by kidyfirst** [comment]
netstat -anp | grep ***** | wc -l
    (Not all processes could be identified, non-owned process info
     will not be shown, you would have to be root to see it all.)
     950

my sequelize pool configuration as follow according the usage http://docs.sequelizejs.com/en/latest/docs/getting-started/?highlight=maxIdleTime
 pool: {
       max: 10,
       min: 0,
       idle: 10000
  },

but the api http://sequelize.readthedocs.org/en/latest/api/sequelize/ doc tell us we should configrate as follow
pool: {
    maxConnections: 10,
    minConnections: 0,
    maxIdleTime: 10000
  },

which is right? and any body can tell me how to close the connection inside code. thanks.

**Comment by mickhansen** [comment]
Both works, `maxConnections` is the older format but both should be supported.

You didn't answer all the questions from my previous comment.

**Comment by kidyfirst** [comment]
@mickhansen  thank you for your answer,  my app only run one sequelize instance, once it throw below error, i have to restart my app.

**Comment by mickhansen** [comment]
And what is your server timeout set to? Please answer ALL the questions.

**Comment by mickhansen** [comment]
Are you running multiple app servers?

**Comment by kidyfirst** [comment]
we only run one app server,  i don't know  what your said the server timeout ?  we  don't set any timeout in koajs, also don't set mysql timeout  explicitly, and we found the sequelize can normally release the connection with mysql, but it can't release the connection with our company's distributed  database production based on  mysql.
Thanks.

**Comment by mickhansen** [comment]
Your server is configured to have a connection timeout, see what that is compared to the timeout defined for your pools.
