### ISSUE TITLE
[Migrations] UNIQUE constraint in Postgres doesn't get removed

### ISSUE THREAD

**Issue by Pliny** [sequelize/sequelize#4799]
Hi! Coming from RoR world, I love this tool!  

I ran into a issue, though, with undoing a migration.  

 when using the Postgres dialect, migrations that want to remove a _UNIQUE_ constraint from a column in fact does not remove it.  

Specifically, after one runs the following `up()` function where 'MyTable' already exists and has a 'my_attr' column:

``` javascript
up: function (queryInterface, Sequelize) {
  return queryInterface.changeColumn('MyTable', 'my_attr', {
    allowNull: true,
    unique: false,
    type: Sequelize.STRING
  });
}
```

they will still see _UNIQUE CONSTRAINT_ when running `=# \d+ "MyTable"` in _psql_.

Perusing through the code, it seems as if `changeColumnQuery()` in `query-generator.js` doesn't handle removing the unique constraint index at all.  It adds it just fine though.

This doesn't seem like a straightforward fix as you need to first see if an index exists, so I'm documenting the issue.. in the hope that someone more familiar with the code to come up with a nice solution :)

**Comment by bumpmann** [comment]
+1

As a workaround, i m making my own request for postgres:

`sequelize.query('ALTER TABLE ' + table_name + ' DROP CONSTRAINT ' + constraint_name)`

**Comment by Hoverbear** [comment]
Confirming this bug.

Here was our workaround to remove the `unique: true` from `Users.id`:

```javascript
'use strict';

module.exports = {
  up: (queryInterface, DataTypes) => queryInterface.changeColumn(`Users`, `email`, {
    type: DataTypes.STRING,
    unique: true,
    allowNull: false,
  }),

  down: (queryInterface, DataTypes) => Promise.resolve()
    .then(() => queryInterface.sequelize.query(`ALTER TABLE "Users" DROP CONSTRAINT email_unique_idx;`))
    .then(() => queryInterface.removeIndex(`Users`, `email_unique_idx`))
    .then(() => queryInterface.changeColumn(`Users`, `email`, {
      type: DataTypes.STRING,
      unique: false,
      allowNull: false,
    })),
};
```

**Comment by Pliny** [comment]
This was soooo long ago! 
It was a real bug... I'm not sure if it still exists as I'm not working with Sequelize these days...

**Comment by Hoverbear** [comment]
x

**Comment by ex3ndr** [comment]
It is still an issue

**Comment by aryeharmon** [comment]
still an issue

**Comment by Skanthappa** [comment]
still an issue

**Comment by aminalali8** [comment]
Issue on mysql as well

**Comment by sushantdhiman** [comment]
Use `removeConstraint` to drop constraints http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-removeConstraint

**Comment by aryeharmon** [comment]
still...

**Comment by oukano** [comment]
any news about this ?

**Comment by vatex** [comment]
Is sequelize abandoned? I have the same problem with Sequelize + PostgreSQL.

**Comment by florian-luce** [comment]
I have currently the same problem with Sequelize + MariaDB

**Comment by LakmalHarshana** [comment]
This worked for me with MYSQL If the constraint name was not defined when creating the index, have to use the default name set by the DB (check with DB version)
`await queryInterface.sequelize.query(
      `ALTER TABLE users DROP INDEX email;` // or email_unique
 )`
