### ISSUE TITLE
Model - Where on separated include relation

### ISSUE THREAD

**Issue by jamesaspence** [sequelize/sequelize#4800]
Is there a way to do a where statement on a separated include that is part of the initial query?

I have a query constructed, querying from the customer table and including orders, that looks like this:

```
{
    where: {
        // where statements
    },
    include: [
        {
            model: Order,
            where: {
                order_id: orderId
            },
            separate: true
        }
    ]
}
```

However, that being separate means that the initial query looks like this:

```
SELECT 
    `customer`.`id`, `customer`.`customer_id`, `customer`.`username`, `customer`.`first_name`, `customer`.`last_name`, `customer`.`email`, `customer`.`phone_number`, `customer`.`company`, `customer`.`store` 
FROM 
    `customers` AS `customer` 
LIMIT 10;
```

I need it to do an inner join on the order table in the initial query, to search by order id, then grab ALL the orders for that customer. I need to have the include separate because otherwise the query done is extremely inefficient, and takes a few seconds to process.

Is such a thing possible? I could write it manually, but I'm hoping that sequelize will have this flexibility available.

EDIT: This is the query I'm hoping sequelize will construct:

```
SELECT
    `customer`.*
FROM
    `customers` AS `customer`
INNER JOIN
    `orders` ON `customer`.`id` = `orders`.`local_customer_id`
WHERE
    `orders`.`order_id` = '123456'
LIMIT 10
```

**Comment by mickhansen** [comment]
Not possible natively with sequelize, but you could probably reverse your query for some speed.

Fetch order for order id including customer, then seperately include all orders for customer.

**Comment by jamesaspence** [comment]
Any chance of some sort of ability to add to the where statement for relations? I.e. `where : { order: { order_id: orderId } }` would trigger an inner join on that table?

**Comment by jamesaspence** [comment]
And in my case reversing the queries isn't really an option - I need to list customers, with their orders. Not the other way around (orders with their single customer)

**Comment by jamesaspence** [comment]
I think I'll end up doing a raw query, retrieving the IDs, then doing the original query where the IDs match. I'd love to see the ability to do something like this in the future, though.

**Comment by mickhansen** [comment]
You can use `$order.order_id` to generate nested field friendly where object, but it doesn't do any more logic than that.

We only trigger inner join on `include.required: true` or `include.where`.
