### ISSUE TITLE
Passing Date to Where clause gives SQLite error

### ISSUE THREAD

**Issue by peponerock** [sequelize/sequelize#4801]
Hi guys. Thank you for your time.
I'm trying to filter some products by "updated" column. For some reason, passing a js Date object is not "printing" its value correctly on the SQL sentence.
This is my table:

	CREATE TABLE product (
		id             INTEGER        PRIMARY KEY AUTOINCREMENT NOT NULL,
		...
		updated        DATETIME,
	);

Sequelize query:

	db.product.find({
		where:{updated:{$gte:new Date()}}
	}).then(function(my_products){
		console.log(my_products);
	},function(err){
		console.log(err);
	});

This is the query reurned within the SQLite error:

	SELECT `id`,...,`updated` FROM `product` AS `product` WHERE `product`.`updated` >=  LIMIT 1;

What is wrong here?

I'm working on Node Webkit v.0.12.3, Sequelize v.3.12.2, Sqlite3 v3.0.9, Win8 x64.

Thank you a lot!

**Comment by janmeier** [comment]
I get `SELECT `id`, `updated` FROM `products` AS `product` WHERE `product`.`updated` >= '2015-11-05 21:37:42.072 +00:00' LIMIT 1;`

Can you show the model definition, or perhaps a [SSCCE](http://sscce.org/)

**Comment by janmeier** [comment]
Closing, no response
