### ISSUE TITLE
boolean type, should not accept integer but 1,0

### ISSUE THREAD

**Issue by devmark** [sequelize/sequelize#4802]
```
 "sequelize": "^3.13.0"
```
using mysql

```
...
  isAdmin: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true
     }
...
```
param:
```
isAdmin: 2 // or 127
```
 
`isAdmin` boolean type should not be accept integer but 1,0
or should auto set to `true` / `1`

**Comment by janmeier** [comment]
Try enabling `typeValidation` http://docs.sequelizejs.com/en/latest/api/sequelize/
