### ISSUE TITLE
Convert USING utf8

### ISSUE THREAD

**Issue by gurpreetRosie** [sequelize/sequelize#4803]
Hi there

I want to use this function. 'convert using utf8' on one of my field value. Please help me with the correct syntax.
I am trying as follows:

sequelize.fn('CONVERT', sequelize.col('HTMLContent')),'HTMLContent'
But I have no idea where to write "USING" clause.

Regards

Gurpreet

**Comment by mickhansen** [comment]
You'll likely have to do something like:

```js
sequelize.fn('CONVERT', sequelize.literal('`HTMLContent` USING utf8'))
```

**Comment by gurpreetRosie** [comment]
Thank you so much. It worked.
