### ISSUE TITLE
Create with ascociation fails if ascociated table name ends with 'Data'

### ISSUE THREAD

**Issue by DPM1** [sequelize/sequelize#4804]
This works fine and enters the row into the User table:

```
   var Product = sequelize.define('Product', {
        title: Sequelize.STRING
    });
    var User = sequelize.define('User', {
        first_name: Sequelize.STRING,
        last_name: Sequelize.STRING
    });
    Product.hasOne(User, {
        foreignKey: 'TestJoinID'
    });
    sequelize.sync().then(function () {
        return Product.create({
            title: 'Chair',
            User: {
                first_name: 'Mick',
                last_name: 'Broadstone'
            }
        }, {
            include: [User]
        })
    })
```

But this does not enter the row into the UserData table:

```
    var Product = sequelize.define('Product', {
        title: Sequelize.STRING
    });
    var UserData = sequelize.define('UserData', {
        first_name: Sequelize.STRING,
        last_name: Sequelize.STRING
    });
    Product.hasOne(UserData, {
        foreignKey: 'TestJoinID'
    });
    sequelize.sync().then(function () {
        return Product.create({
            title: 'Chair',
            UserData: {
                first_name: 'Mick',
                last_name: 'Broadstone'
            }
        }, {
            include: [UserData]
        })
    })
```

If this is already documented. Then I apologize, I didn't see it, maybe you could link it here for anyone who has this problem.

**Comment by DPM1** [comment]
Using MSSQL.

**Comment by mickhansen** [comment]
Can you please post the relevant error?

**Comment by DPM1** [comment]
No Error - test passes, Nothing thrown, just doesn't insert the row into the UserData table. Debug out for the test with 'User':

Executing (default): INSERT INTO [Product] ([title],[updatedAt],[createdAt]) OUTPUT INSERTED.* VALUES ('Chair','2015-11-04 09:35:02.000 +00:00','2015-11-04 09:35:02.000 +00:00');
Executing (default): INSERT INTO [User] ([first_name],[last_name],[TestJoinID],[updatedAt],[createdAt]) OUTPUT INSERTED.* VALUES ('Mick','Broadstone',1,'2015-11-04 09:35:02.000 +00:00','2015-11-04 09:35:02.000 +00:00');

Debug out for the test with 'UserData':

Executing (default): INSERT INTO [Product] ([title],[updatedAt],[createdAt]) OUTPUT INSERTED.* VALUES ('Chair','2015-11-04 09:33:45.000 +00:00','2015-11-04 09:33:45.000 +00:00');

The second insert is simply not executed. No error is returned.

**Comment by mickhansen** [comment]
Your naming is not matching up then, verify that the association alias is as you expect by logging:

```js
Product.UserData = Product.hasOne(UserData, {
  foreignKey: 'TestJoinID'
});

console.log(Product.UserData.as);
```

**Comment by DPM1** [comment]
How strange...

When I use the name User then Product.ascociations is:
{ User:
   { associationType: 'HasOne',
     source:...
     target: { '$ref': '$["User"]["source"]["options"]["sequelize"]["models"]["User"]' },
     options: ...
     isSingleAssociation: true,
     isSelfAssociation: false,
     as: 'User',
     foreignKeyAttribute: { type: [Object], allowNull: true },
     foreignKey: 'TestJoinID',
     sourceIdentifier: 'id',
     associationAccessor: 'User',
     accessors: { get: 'getUser', set: 'setUser', create: 'createUser' },
     identifierField: 'TestJoinID' } }

**Comment by mickhansen** [comment]
Hmm, that sounds like a bug. We should only be pluralizing for :M associations.
As a workingaround you can use `as: 'UserData'` on the association.

Tagging as a bug, needs to be investigated (might relate to using the model name)

**Comment by mickhansen** [comment]
Not sure if a bug happens here: https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L562
Mind testing `sequelize.Utils.inflection.singularize('UserData')`?

**Comment by mickhansen** [comment]
Oh yeah that must be it, Data is plural, Datum is the singular form of Data, although no one actually uses Datum :P

**Comment by DPM1** [comment]
Yep that seems likely! Thanks!
