### ISSUE TITLE
instance.save() doesn't detect and save changes in arrays or objects

### ISSUE THREAD

**Issue by bestan** [sequelize/sequelize#4805]
Consider following schema

```javascript
var Model = sequelize.define('model', {
	array: Sequelize.ARRAY(Sequelize.INTEGER)
});
```

and following code

```javascript
Model.create({
  array: [1],
}).then(function(instance) {

  instance.array.push(2);
  instance.save().then(function() {

    instance.reload().then(function() {
      console.log(instance.array);
    });

  });
});

```

instance.array outputs `[1]`, but I expect it to be `[1,2]`.

Documentation states that `When you call save without changing any attribute, this method will execute nothing`, but I'm guessing only object references are being checked and not the actual values.

Same issue can be reproduced with `Sequelize.JSONB` type as well.

**Comment by curiousdannii** [comment]
Once proxies are properly supported in node they could be used to call changed() automatically.

**Comment by mickhansen** [comment]
JSONB has support for using `set(`nested.key`)`.
If you're modifying nested items you need to call `changed()` on the instance.

**Comment by adam-back** [comment]
This issue had me thinking I was crazy for a good 30 minutes. I'd like to submit a PR to improve the [API documentation](http://sequelize.readthedocs.org/en/latest/api/instance/#saveoptions-promisethiserrorsvalidationerror), but I'm not sure on the wording. Please review a draft:

##### Original #####
Validate this instance, and if the validation passes, persist it to the database. It will only save changed fields, and do nothing if no fields have changed.

On success, the callback[...]

##### Replacement #####
[...] do nothing if no fields have changed.

Note: If a JSON/JSONB attribute is called with a dot.seperated key, it will flag the entire object as changed. Changes to ARRAY types do not set a flag as changed and will not be persisted with `save`; use `update` instead.

```javascript
instance.dogs;
// ['lab', 'poodle']

// Wrong
instance.dogs.pop();
instance.dogs;
// ['lab']
instance.save()
.then(function(savedInstance) {
  savedInstance.dogs;
  // ['lab', 'poodle']
  // no change flag, no persistence
});

// Correct Usage
instance.update({ dogs: ['lab'] })
.then(function(updatedInstance) {
  updatedInstance.dogs;
  // ['lab']
  // persistence
});
```

On success, the callback[...]

**Comment by mickhansen** [comment]
@adam-back it comes down to that Sequelize does not do after-the-fact dirty checking but rather sets a flag when `set` is called, `set` is not called by a deep access.

**Comment by jcalfee** [comment]
This was unexpected behavior for me too.  I suggest something in the docs about the behavior and design decisions.  I need to add an elements in the array if they do not exist then save if changed but defer the save until other code runs so I minimize the updates.  So it looks like @ladamjaffeback solution works but may incur extra database calls.  I should be able to mark it as unsaved so it will save later.  Update forces a save at the time.  Is there a better way?  Thank you.

**Comment by jcalfee** [comment]
I think I figured it out.  It looks like Sequelize is doing an equality check `===`, so I can clone the array `b = [...a || []]` or just `b = [...a]` then if I change the clone I assign the cloned array back to the model and it saves.  There was no need to add additional Sequelize method calls to do this.
