### ISSUE TITLE
can't make many has many relations

### ISSUE THREAD

**Issue by mkuts12** [sequelize/sequelize#4806]
Consider the following situation:
I have a bank account and I have paid to and recieved from other accounts through transactions.
So I tried 
Account.hasMany(Transaction, {
    foreignKey: {
        name: 'outAccount',
        allowNull: false
      }
    });
Account.hasMany(Transaction, {
    foreignKey: {
        name: 'inAccount',
        allowNull: false
      }
    });

but when trying to fetch all my transactions, myacc.getTransactions() it fetched only the in transactions.

Is it a bug or I simply don't use it right.

sorry for bad english =\

**Comment by mickhansen** [comment]
Per the docs you need to use `belongsToMany` for N:M associations: http://docs.sequelizejs.com/en/latest/docs/associations/#belongs-to-many-associations

**Comment by mickhansen** [comment]
Your code can still work, but it will fetch transactions not the target accounts, you'll need to use different aliases for both associations though `as: 'incomingTransactions'` and `as: 'outgoingTransactions'` (you'll then be able to use `account.getIncomingTransactions` etc)

**Comment by mkuts12** [comment]
It's not belongs to many because the accounts are different. 
But your second comment is great. thank you!
