### ISSUE TITLE
SQL Server Update Fails with Trigger

### ISSUE THREAD

**Issue by lusid** [sequelize/sequelize#4807]
If a table in SQL Server has a trigger, then executing a .save() will cause it to fail because an OUTPUT clause is being used without an INTO clause. The error reads:

**Unhandled rejection SequelizeDatabaseError: The target table 'x' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.**

More information on this problem and the workaround here: http://stackoverflow.com/questions/13198476/cannot-use-update-with-output-clause-when-a-trigger-is-on-the-table

Is there a workaround for this in Sequelize?

**Comment by lusid** [comment]
Nevermind, I just realized there is a hasTrigger parameter.

**Comment by mgrivera** [comment]
Hi @lusid, I know this is an old post. I'm new to sequelize and just experiencing this problems while trying to insert to a table (mssql) that has triggers. 

Could you tell where do I have to put this attribute *hasTriggers*? It doesn't seem to be in the docs. 

Thanks and bye ...

**Comment by mgrivera** [comment]
Well, it seems I've have found where I have to put this new attribute, just for tables with triggers, at least for mssql dialect, to work with sequelize. 

Just take a look at this example: 
`
AsientosContables_sql = sequelize.define('AsientosContables_sql', {
    <field definitions> 
}, {
     tableName: 'Asientos', hasTrigger: true 
});
`
Thanks and bye ...

**Comment by Zignd** [comment]
I just ran into the same problem and until this date the documentation doesn't cover this `hasTrigger` parameter, at least I could not find a reference to it through the docs search box. It would be nice to have this feature documented.

**Comment by felixfbecker** [comment]
@Zignd please don't resurrect old issues.
