### ISSUE TITLE
aggregate functions in having clause

### ISSUE THREAD

**Issue by shaiherman** [sequelize/sequelize#4808]
Hi there,

Looking to see if this is possible with sequelize and if so how.
Using postgres 9.4 and Sequelize 3.12.2

Here's the basic sql paired down and simplified:
```sql
SELECT col1
FROM "tableA"
GROUP BY col1 
HAVING json_object_agg(col2,col3)::jsonb @> '{"key": ["some value 1"],"key2": ["some value 2"]}';
```
The sql is working fine for me when run off postgres.

here's my findAll paired down and simplified:
```javascript
models.tableA.findAll({
    attributes: ['col1', models.sequelize.fn('json_object_agg', models.sequelize.col('col2'), models.sequelize.col('col3') )],    
    group: 'col1',
    having: {
      "json_object_agg(col2,col3)::jsonb": {
        $contains: '{"key": ["some value 1"],"key2": ["some value 2"]}'
      }
    },
    logging: console.log
  })
```
Having difficulty with adding in the json_object_agg function and casting it to jsonb.
For this particular findall I get the issue: 
"json_object_agg(col2,col3)::jsonb" does not exist

I've managed to get the json_object_agg aggregate function working fine in my attributes options, but it's in the having clause where I run into issues.  The having clause is passing this as a string to the generated sql when I output the sql.

I dabbled inside the query-generator.js and was able to see that having is treated identically to where. In the getWhereConditions function I got in over my head.

I may have grossly overlooked something.  Any help is appreciated.

**Comment by curiousdannii** [comment]
You can cast and call functions with `sequelize.cast()` and `sequelize.fn()`.

**Comment by mickhansen** [comment]
The keys of a where (or having) object is expected to be columns, hence your JSON call is escaped.
You'll need to use `sequelize.where()` in this instance, /cc @janmeier

**Comment by janmeier** [comment]
`having: sequelize.where(sequelize.literal("json_object_agg(col2,col3)::jsonb"), {
        $contains: '{"key": ["some value 1"],"key2": ["some value 2"]}'
      })`

should work

**Comment by shaiherman** [comment]
Thanks all for your input.  I realize I need to familiarize myself more with the base Sequelize class. 

@janmeier your having clause worked perfectly.

Looks like sequelize.where could also help me in constructing subqueries inside a where clause, something I've been curious about.  At the least I could use sequelize.query to punch in a raw query in the second parameter of sequelize.where.  Wondering if I could use more than raw sql to do this - perhaps using a data retriever like findall.

**Comment by janmeier** [comment]
Yes, I think `.where` is the best way to go for subqueries for now. We have discussed being able to get methods like `findAll` to output sql for use in subqueries and the like, but no work has been done yet. So for now writing the sql manually is the way to go

**Comment by shaiherman** [comment]
Is there's a place I can follow along/track the possibility of using `findAll` to output sql, like as an open issue I can subscribe to or something else?  No worries if not.

Thanks again @janmeier .You guys are rocking it  :-)

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/2325 - feel free to comment on the API
