### ISSUE TITLE
How can multiple associations be required?

### ISSUE THREAD

**Issue by curiousdannii** [sequelize/sequelize#4809]
Apologies if this has been asked before, but I couldn't find any relevant issues.

I have two models: Extension, whose attributes are irrelevant to this question, and Tag, with a single TEXT attribute tag. I have relations set up as follows:

```
sequelize.define( "Tag", { tag: DataTypes.TEXT, } );
Tag.belongsTo( Extension );
Extension.hasMany( Tag );
```

I want to search for Extensions which have several associated tags, but can't figure out how. What I'm doing at the moment is searching for extensions which match any of the list of tags, and then filtering the results afterwards. It would be preferable to filter them in the SQL query instead, if that's possible.

```
Extension.findAll( {
	include: [{
		model: db.Tag,
		where: {
			tag: { $in: tagslist }, // [ 'tag1', 'tag2' ]
		},
	}]
} );
```

Bonus question: I don't actually need the Tag rows to be returned or instantiated. Can you require the associations to exist but not get them returned?

**Comment by janmeier** [comment]
Having a `where` on the include should give you an inner join, which in turn only returns those extensions with matching tags, so I'm not sure what the issue is :). Should it have all tags?

You should be able to `include.attributes = []` to prevent the data being returned

**Comment by curiousdannii** [comment]
> Having a where on the include should give you an inner join, which in turn only returns those extensions with matching tags, so I'm not sure what the issue is :). Should it have all tags?

Yeah I want to only select extensions with every tag. Using where.tag.$in selects extensions with any of the tags.

I don't know how it would be done with plain SQL either so I know my question is rather uninformed. :)

**Comment by janmeier** [comment]
Perhaps try `$all: taglist`

**Comment by curiousdannii** [comment]
@janmeier Sorry, I couldn't find any information about how to use $all.

I did find #1585 which alerted me to the having option. I've got what I wanted working through the following:

```
Extension.findAll( {
	include: [{
		model: db.Tag,
		attributes: [],
		where: {
			tag: { $in: tags },
		},
	}],
	group: '"Extension"."id"',
	having: [ 'COUNT(*) = ?', tags.length ],
} );
```

The having option seems to be completely undocumented!
