### ISSUE TITLE
Escape field name when ordering

### ISSUE THREAD

**Issue by moret** [sequelize/sequelize#4810]
Hi.

When running a query with ordering on a model attribute with a name different from the [table field name](http://sequelize.readthedocs.org/en/latest/docs/legacy/#fields) I expected the model attribute name to be [escaped]((http://sequelize.readthedocs.org/en/latest/docs/querying/#ordering)) in the resulting SQL query, but the actual resulting query is using the unescaped name given.

This is a condensed example of the mapping and query I tried:
```javascript
import Promise from 'bluebird';
import Sequelize from 'sequelize';

const peopleData = [
  {id: 1, name: 'John'},
  {id: 2, name: 'Jane'},
  {id: 3, name: 'Jill'}
];

const sequelize = new Sequelize(process.env.DB);

const Person = sequelize.define('Person', {
  name: {type: Sequelize.STRING, field: 'fullName'}
}, {
  tableName: 'LegacyPeople'
});

Person.drop().then(() => (
  Person.sync()
)).then(() => (
  Promise.each(peopleData, (person) => (Person.create(person)))
)).then(() => (
  Person.findAll({
    attributes: ['id', 'name'],
    order: [['name']]
  })
)).then((people) => {
  people.forEach((person) => {console.log(person.id, person.name)});
});
```
that generates this SQL query without escaping:
```sql
SELECT [id], [fullName] AS [name] FROM [LegacyPeople] AS [Person] ORDER BY [Person].[name];
```
on MS SQL 2012 11.0.5058.0 (x64) through tedious 1.13.1 at Sequelize 3.13.0. I initially thought this was a [graphql-sequelize](https://github.com/mickhansen/graphql-sequelize/issues/72) issue, but the same behaviour occurs when using Sequelize directly.

Thanks in advance for the attention!

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L101 needs to be expanded to work with order aswell.

**Comment by janmeier** [comment]
This is fxied on master
