### ISSUE TITLE
on duplicate key update id = last_insert_id(id)

### ISSUE THREAD

**Issue by gurpreetRosie** [sequelize/sequelize#4815]
Hi there

I am trying the following

insert into table (field1) values (val1) on duplicate key update id = last_insert_id(id)

Any suggestions how we do that using upsert?

Regards

Gurpreet

**Comment by janmeier** [comment]
Currently it's not possible to specify what to do in case of a conflict in upsert. However, I'm not really sure thats a good idea either - In my view upsert is either insert these values, or update the matching row to have those values.

**Comment by dubanflorin** [comment]
this is needed for mysql to have the correct insertId in the result
