### ISSUE TITLE
Update with associations

### ISSUE THREAD

**Issue by xizhao** [sequelize/sequelize#4816]
Is there a way to do an "update with associations"?  Similar to creating with associations, basically add "include" into the options of update()

**Comment by mickhansen** [comment]
Does not currently exist, not trivial to implement (how do we know if its a new or existing update? especially relevant for non-AI PKs)

**Comment by xizhao** [comment]
how does setAssociations differ?

**Comment by xizhao** [comment]
would your approach to be to do this in a 2-step process?

in an m:n relation
1. create all "n" relations that don't exist
2. create all associations between m&n

**Comment by mickhansen** [comment]
@xizhao setAssociations clears out the DB and then sets all new.
That could work, however it would likely not be too efficient with needing 2-3 queries på association instance.

**Comment by mickhansen** [comment]
A primitive solution could be to assume creation based on the presence of a primary key value, it's not strictly correct but it solves a lot of use cases.

**Comment by xizhao** [comment]
That makes sense -- we can associate value first and then use that info to create and re-associate missing ones.  As you said seems hacky though.

With setAssociations() if the fields on our through table are dependent on the values we're associating with -- or just different depending on the association -- is there a channel for that use case or should we be setting associations one by one?

Thanks!
