### ISSUE TITLE
 Problem in many to many associations  using Field

### ISSUE THREAD

**Issue by vishnumishra** [sequelize/sequelize#4817]
I'm using sequelize v3.11.0  and sails v0.11.0 using mysql db.

I have my models/User.js

```
module.exports = {
  attributes: {
    firstName: {
        type: Sequelize.STRING,
        allowNull: false,
        field:'first_name'
    },
    lastName: {
        type: Sequelize.STRING,
        field:'last_name'
    },
    phone: {
        type: Sequelize.STRING
    }
  }
}
```

model/Category.js

```
module.exports = {
    attributes: {
    name: {
         type: Sequelize.STRING,
         allowNull:false,
         unique:true,
    },
       description: {
        type: Sequelize.STRING
    }
   }
}
```

model/UsersCategory.js

```
module.exports = {
    attributes: { },
    options: {
        tableName: 'user_categories'
    },
    associations: function() {
        User.belongsToMany(Category, {
            through: UsersCategory,
            foreignKey: {
                name:'userId',
                field:'user_id'
            }
        });
        Category.belongsToMany(User, {
            through: UsersCategory,
            foreignKey: {
                name:'categoryId',
                field:'category_id'
            }
        });
    }
};
```

But when I'm executing this code In my database user_categories table I'm geting the attribute as:

> category_id , userId

I'm not getting that why userId in camelcase.

when I'm doing:

```
User.findAll({
    include: [
          {all:true}
        ]
   })
```

I'm getting error:

> "ER_BAD_FIELD_ERROR: Unknown column 'Categories.UsersCategory.user_id' in 'on clause'"
> 
> But If I user userId and CategoryId in my UserCategory model then It working Fine.

Is there is some problem with the Field in many to many association?

**Comment by mickhansen** [comment]
> sequelize v0.10

What version are you actually using?

Since this is a SQL error it would be helpfull to see the SQL :)

**Comment by vishnumishra** [comment]
sequelize  v 3.11.0

        "sql ": "
        SELECT `User`.*, `Categories`.
        `id`
        AS `Categories.id`, `Categories`.
        `category_name`
        AS `Categories.name`, `Categories`.
        `createdAt`
        AS `Categories.createdAt`, `Categories`.
        `updatedAt`
        AS `Categories.updatedAt`, `Categories.UsersCategory`.
        `createdAt`
        AS `Categories.UsersCategory.createdAt`, `Categories.UsersCategory`.
        `updatedAt`
        AS `Categories.UsersCategory.updatedAt`, `Categories.UsersCategory`.
        `category_id`
        AS `Categories.UsersCategory.categoryId`, `Categories.UsersCategory`.
        `userId`
        AS `Categories.UsersCategory.userId`
        FROM(SELECT `User`.
            `id`, `User`.
            `username`, `User`.
            `createdAt`, `User`.
            `updatedAt`
            FROM `user`
            AS `User`
            LIMIT 30) AS `User`
        LEFT OUTER JOIN(`user_categories`
            AS `Categories.UsersCategory`
            INNER JOIN `category`
            AS `Categories`
            ON `Categories`.
            `id` = `Categories.UsersCategory`.
            `category_id`) ON `User`.
        `id` = `Categories.UsersCategory`.
        `user_id`; "
