### ISSUE TITLE
Querying HSTORE in postgres

### ISSUE THREAD

**Issue by faceleg** [sequelize/sequelize#4818]
I have a model that has an HSTORE column. I would like to use Sequelize's `find` method to perform queries searching for records based on data in the HSTORE column.

The raw query is:

``` SQL
SELECT row_data
FROM audit.logged_action AS logged_action 
WHERE logged_action.action = 'I'
AND row_data ? 'id'
AND row_data->'id' = '16'
```

My (failed) attempt in Sequelize:

``` JS
LoggedAction.findOne({
  where: {
     action: 'I',
     row_data: {
       id: billingDetail.id
     }
   }
});
```

**Comment by janmeier** [comment]
Hmm, seems hstore querying was never implemented ... :)

**Comment by faceleg** [comment]
Haha!

I did my queries in SQL, no issues.

**Comment by legomind** [comment]
@janmeier I am considering creating a PR for this. Would the following be correct?

### Current Functionality
```js
User.findOne({
  where: {
    hstore_field: {
      fieldOne: 'some_value',
    },
  },
});
```

would produce

```sql
SELECT *
FROM Users
WHERE hstore_field = '"fieldOne" => "some_value"'
```

### New functionality

```js
User.findOne({
  where: {
    hstore_field: {
      $contains: {
        fieldOne: 'some_value',
      },
    },
  },
});
```

equals

```sql
SELECT *
FROM Users
WHERE hstore_field -> 'fieldOne' = 'some_value'
```

**Comment by janmeier** [comment]
@legomind Looks good to me :)

**Comment by faceleg** [comment]
@legomind this looks awesome!
