### ISSUE TITLE
sync() on a single model gets error [SequelizeUniqueConstraintError: Validation error]   

### ISSUE THREAD

**Issue by lxjuly** [sequelize/sequelize#4820]
For a HTTP POST REST end point, I did a `sync()` before the actual insert. Something like this:
```javascript
 SomeModel.sync()
    .then(function(SomeModel) {
      return SomeModel.upsert(theInsertedObject);
    });
```
Then I receive the following error during importing my test data:
```javascript
{ [SequelizeUniqueConstraintError: Validation error]
  name: 'SequelizeUniqueConstraintError',
  message: 'Validation error',
  errors:
   [ { message: 'typname must be unique',
       type: 'unique violation',
       path: 'typname',
       value: 'SomeModel' },
     { message: 'typnamespace must be unique',
       type: 'unique violation',
       path: 'typnamespace',
       value: '2200' } ],
  fields: { typname: 'Media', typnamespace: '2200' } }
```

Intuitively, the `sync()` should issue the SQL command `CREATE TABLE IF NOT EXISTS`, but it seems not to be the case here. I took a brief look at the code and it is only doing a normal `createTable` call inside `sync()`. 

Question is can we have a proper sync that supports `CREATE TABLE IF NOT EXISTS`

**Comment by mickhansen** [comment]
We already use `CREATE TABLE IF NOT EXISTS`: https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L49

However indexes are not necessarily created in the createTable statement.

**Comment by lxjuly** [comment]
@mickhansen Thx! In that case, do you think why I was receiving that error? It looks like the error stems from the fact that `sequelize` tried to create the same table twice.

**Comment by mickhansen** [comment]
@lxjuly Maybe you are calling sync twice?

**Comment by lxjuly** [comment]
@mickhansen I checked my code. I am only calling `sync` once. Don't you think that even when the `sync` is called twice. The `CREATE TABLE` call should still be guarded against?

**Comment by mickhansen** [comment]
@lxjuly The create table statements won't clash since they have NOT EXISTS.

Your error is more likely to be with your upsert statement i'd venture.

**Comment by lxjuly** [comment]
@mickhansen Thx! Let me find out :)

**Comment by Ubaidbutt** [comment]
@lxjuly Hey brother, how did you fix this issue because I am stuck exactly in a similar issue?
