### ISSUE TITLE
NOT contains?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#4821]
I was looking at the operators at http://docs.sequelizejs.com/en/latest/docs/querying/ and found a NOT version for most of them.

But it doesn't look like there's a NOT for contains. Please advise, thanks!

**Comment by curiousdannii** [comment]
You should use `$not`:

```
{
	$not: { $contains: [1, 2] },
}
```

**Comment by GeoffreyPlitt** [comment]
Ah, thanks!

**Comment by contra** [comment]
Would be great if the $not operator was documented!
