### ISSUE TITLE
Error while creating and inserting data

### ISSUE THREAD

**Issue by samundrak** [sequelize/sequelize#4827]
I am getting error while inserting data it is saying 
``` Unhandled rejection SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL    syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[object Object], `username` [object Object], `birthday` [object Object], `create' at line 1

Sequelize code is: 

var sequelize = new Sequelize(config.db.database, config.db.user, config.db.password);
var User = sequelize.define('nepal', {
    username: Sequelize.STRING,
    birthday: Sequelize.DATE
});

sequelize.sync().then(function() {
    return User.create({
        username: 'janedoe',
        birthday: new Date(1980, 6, 20)
    });
}).then(function(jane) {
    console.log(jane.get({
        plain: true
    }))
});

**Comment by mickhansen** [comment]
As a starter, try looking at the SQL query generated.
But looks like object values are being input for username/birthday, is that your ACTUAL code running?
