### ISSUE TITLE
getAndCountAssociations() similar to findAndCountAll()

### ISSUE THREAD

**Issue by manuelbieh** [sequelize/sequelize#4829]
Hi,

following situation: I have a **User** model and a **Follower** n:m association

```
User.belongsToMany(User, {
    as: 'Followings',
    foreignKey: 'follower_id',
    through: Follow
});

User.belongsToMany(User, {
    as: 'Followers',
    foreignKey: 'user_id',
    through: Follow
});
```

Now I want to get the total number of followers and at the same time the data for some of the followers: `user.getFollowers({limit: 24, offset: 48});`

Works fine, but currently I need to make a separate call `user.countFollowers()` to also get the total number of followers.

Maybe I just haven't seen it in the docs but if not: would it be possible to add a convenience method to count and receive all associations? Something like `user.getAndCountFollowers()`

Currently my _workaround_(?) looks like this:

```
let result = {count: 0, rows: []};
User.findById(req.params.id)
.then((user) => {
    return user.countFollowers()
    .then((count) => {
        result.count = count;
        user.getFollowers()
        .then((followers) => {
            result.rows = followers;
            return res.json(result);
        })
    })
})
.catch((err) => {
    console.error(err.stack);
    return res.status(500).json(err);
});
```

And I was wondering if there isn't an easier way to do just that. And if there is no such way, wouldn't it be a nice feature to add? ;)

**Comment by mickhansen** [comment]
For simple calls like these where you do not have subincludes it should be a rather trivial feature to implement :)

**Comment by manuelbieh** [comment]
So that means you might implement that in the future? I guess I don't know the internals of Sequelize good enough to make a fully tested, efficient PR by myself.

**Comment by manuelbieh** [comment]
Tried it by myself but can't get the tests to pass. I don't know why. I created a bounty to speed it up a little bit maybe ;)

https://www.bountysource.com/issues/28106333-getandcountassociations-similar-to-findandcountall

**Comment by trendsetter37** [comment]
@manuelbieh Could you swap your last promise for something like this as a workaround for now?
```
let result = {count: 0, rows: []};
User.findById(req.params.id)
.then((user) => {
    return user.getFollowers()
    .then((followers) => {
        result.count = followers.length;
        result.rows = followers;
        return res.json(result);
    })
})
.catch((err) => {
    console.error(err.stack);
    return res.status(500).json(err);
});
```

Or am I missing something? I think I will try to take a crack at a getAndCountAssociations() method.

**Comment by bakewellcake** [comment]
Any updates on this?
