### ISSUE TITLE
 sqlite dialect generating wrong queries

### ISSUE THREAD

**Issue by abec** [sequelize/sequelize#4831]
SELECT `Revision`.* FROM ((SELECT `locator`, `url`, `public`, `resolved`, `error`, `position`, `createdAt`, `updatedAt`, `projectId` FROM `Revisions` AS `Revision` WHERE `Revision`.`projectId` = 'npm+recast' ORDER BY position DESC LIMIT 1) UNION (SELECT `locator`, `url`, `public`, `resolved`, `error`, `position`, `createdAt`, `updatedAt`, `projectId` FROM `Revisions` AS `Revision` WHERE `Revision`.`projectId` = 'npm+esprima-fb' ORDER BY position DESC LIMIT 1)) AS `Revision`;

The above SQL is generated when we include Revisions with projects: Assuming Project.hasMany(Revision), include({model: Revision, limit: 1, order: "position DESC"}).

The issue is that LIMIT and ORDER BY aren't supported as part of the nested SELECT statements. Only the wrapping SELECT statement can have LIMIT and ORDER BY.

**Comment by mickhansen** [comment]
`include.separate` which is triggered by `include.limit` is not supported for SQLITE.
Could not get union queries to work properly with sqlite the first time around.
You're welcome to open a PR suggesting a fix, but moving the LIMIT and ORDER BY to the wrapper would defeat the entire purpose.

**Comment by thom-nic** [comment]
I just ran into this as well.  Is it possible for Sequelize to execute this as multiple queries, without the union?

**Comment by thom-nic** [comment]
Is there a way to break the above into multiple operations such that the end result looks the same?  e.g. using the original example, if I wanted to achieve:

```javascript
Project.findAll({include:[{model:Revision, as:'Revisions', limit: 1, order: 'position DESC'}]})
```

something like this to replace it...
```javascript
Project.findAll()
  .then(projects => Promise.all(projects.map(project => 
    project.getRevisions({limit: 1, order: 'position DESC'})
         .then(rev => project.revision = rev))
  .then(() => { /* projects should be populated with all revisions here? */ } )
```
I know that's not quite right but... close?
