### ISSUE TITLE
addAssociation(null) should throw

### ISSUE THREAD

**Issue by xizhao** [sequelize/sequelize#4832]
http://sequelize.readthedocs.org/en/latest/api/associations/belongs-to-many/#addassociationnewassociation-options-promise

To my understanding addAssociation only applies to one, and setting "null" should not clear all associations.

**Comment by mickhansen** [comment]
calling `addAssociation(null)` should throw actually, not a legal call.

**Comment by xizhao** [comment]
what about:

"Associate several instances with this." and newAssociation being an array?

addAssociation docs are identical to addAssociation***s***

**Comment by xizhao** [comment]
Also what about the case of adding an association where the foreign key is null? For instance you may want to create an instance on the through table but not have the fk pointing to anything yet.

**Comment by mickhansen** [comment]
`addAssociation/addAssociations` should both throw if the value is simply `null`.
The instance being added is not expected to have a foreign key yet, so that's fine.
