### ISSUE TITLE
setAssocations w/ contextual through

### ISSUE THREAD

**Issue by xizhao** [sequelize/sequelize#4835]
for .belongsToMany setAssociations(), it makes sense to be able to specify the fields of the through table on each individual association.  i.e.:

```javascript
reader.setBooks([{
  book: { id: 3 },
  through: {
    hasRead: true // can be contextual to the book instance
  }
}, ..., ..., ...], options)
```

**Comment by mickhansen** [comment]
Think there's a discussion for this elsewhere already, can't find it atm though.

/cc @janmeier

**Comment by RyanThomas73** [comment]
@janmeier You're book.[name of through table] = { ... } example only works if book is an instance of a db model. Is there no way to set the fields of the through table per association when setting via an array of ids?

e.g.
reader.setBooks([bookids], [{hasRead: true}, {hasRead: false}]);

**Comment by sushantdhiman** [comment]
Duplicate of #4597
