### ISSUE TITLE
Foreign key constraint fails when defining a targetKey

### ISSUE THREAD

**Issue by RSpicer** [sequelize/sequelize#4836]
Hey Sequelize team,

I have a model set up like so: 

``` javascript
var Race = sequelize.define("Race", {
    raceID: {
      type: DataTypes.INTEGER,
      unique: true
    },
    trackID: {
        type: DataTypes.INTEGER
    },
    startsAt: {
      type: DataTypes.DATE
    },
    raceStatus: {
      type: DataTypes.INTEGER
    }
  }
```

I want another model, RaceDetails, to have a foreign key refrencing a raceID, and I want to call it raceID. Note that raceID is not the primary key. I have it set up like this:

``` javascript
Race.hasMany(models.RaceDetail, {foreignKey: 'raceID', targetKey: 'raceID'});
```

And on RaceDetails:

``` javascript
 RaceDetail.belongsTo(models.Race, {foreignKey: 'raceID', targetKey: 'raceID'});
```

With this setup, when trying to create a new RaceDetail, it's clear that Sequelize is trying to reference the id (default primary key) of Race. This is the error:

> ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`rrplocal`.`rrp_racedetails`, CONSTRAINT `rrp_racedetails_ibkf_1` FOREIGN KEY (`raceID`) REFERENCES `rrp_races` (`id`) ON DELETE SET NULL ON UPDATE CASCADE

Any thoughts? I feel like I'm doing everything right, but please tell me if I'm missing something. I can change raceID to be the primary key if it's absolutely necessary, but it would be far better if I didn't.

Thanks guys, let me know what you see!

**Comment by mickhansen** [comment]
We currently only support the targetKey option for belongsTo relations, which is why you're seeing this issue.

**Comment by RSpicer** [comment]
Well that makes sense... but just so I understand it, aren't I supposed to have the matching pair for all of Sequelize's functionality to work? I remember in the past I was having trouble using the include: [] functionality without a matching pair.

Regardless, I can work around it. Just love Sequelize, so want to understand it better!
Thanks!

**Comment by mickhansen** [comment]
@RSpicer Matching pairs should not be required ever anymore (after we split belongsToMany from hasMany/x2)

**Comment by RSpicer** [comment]
That makes sense.

Last question, sorry for being a pain. When then, in that case, would you use hasMany over belongsTo, or vice-versa? They seem rather interchangeable - what's the difference?

**Comment by mickhansen** [comment]
@RSpicer Not being a pain. The difference is in the way you query, you need to have an association for the way you intend to query it.

So if you are usually loading the "parent" and then loading children, you'll want hasMany. If you are usually loading an item which has some related item, belongsTo.
Mostly you do want both :)

**Comment by janmeier** [comment]
Closing since this seems to be resolved :)
