### ISSUE TITLE
instance.update() not persisting changes made in hook to database

### ISSUE THREAD

**Issue by eventhough** [sequelize/sequelize#4837]
I'm using postgres 9.4.4, sequelize 3.13.0. I have a model hook that updates a column called `updatedById` whenever a user modifies a row in my database. I get the userId by passing it through via `options` when `instance.update()` is called.

Here is a repo I've set up with the smallest test case possible: https://github.com/eventhough/sequelize-test

The problem is, when my hook updates the `updatedById` column, the change is not being persisted to the database. The `updatedById` column even shows up when I call `.changed()` on my instance.

I'm *pretty* sure this used to work for me but for some reason it's not working now. I've also tried moving the hook to `beforeUpdate` but it's the same issue.

Here is my setup:

```javascript
var Sequelize = require('sequelize');

var sequelize = new Sequelize('sequelize_test', 'postgres', '', {
  host: 'localhost',
  dialect: 'postgres',
});

var User = sequelize.define('User', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
  },
});

var Widget = sequelize.define('Widget', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
  },
}, {
  hooks: {
    beforeValidate: function (widget, options) {
      if (!options.userId) {
        return Sequelize.Promise.reject(new Error('userId required in options for create or update'));
      }

      console.log('beforeValidate changed columns:', widget.changed());
      widget.name = widget.name + ' hello';

      if (!widget.createdById) {
        widget.createdById = options.userId;
      }

      if (widget.changed()) {
        widget.updatedById = options.userId;
      }

      return widget;
    }
  }
});

Widget.belongsTo(User, { as: 'createdBy', foreignKey: { allowNull: false } });
Widget.belongsTo(User, { as: 'updatedBy', foreignKey: { allowNull: false } });
```

If you run my example you'll see this in the console:

```bash
beforeValidate changed columns: [ 'name' ]
beforeValidate changed columns: [ 'name', 'updatedById' ]
Executing (default): UPDATE "Widgets" SET "name"='red horse hello hello',"updatedAt"='2015-11-10 23:31:52.029 +00:00' WHERE "id" = 1
```

I would expect the last line to include the `updatedById` column:

```bash
Executing (default): UPDATE "Widgets" SET "name"='red horse hello hello',"updatedById"=2,"updatedAt"='2015-11-10 23:31:52.029 +00:00' WHERE "id" = 1
```

**Comment by mickhansen** [comment]
Known issue with beforeValidate i'm afraid, changes in beforeCreate/beforeUpdate should be correctly detected, we need to apply the same logic to beforeValidate.

**Comment by eventhough** [comment]
@mickhansen Thanks. Just out of curiosity, why are these hooks treated differently when detecting changed columns?

**Comment by mickhansen** [comment]
@eventhough The case was not considered when semantics for default fields were changed, so it's "simply" an oversight.

**Comment by selrond** [comment]
I think I'm experiencing this with `afterSave` hook as well
