### ISSUE TITLE
getConnection fails with replication

### ISSUE THREAD

**Issue by anibali** [sequelize/sequelize#4838]
When using replication (as in https://github.com/sequelize/sequelize/issues/4201), there is still some code that tries to use global config and this causes an ECONNREFUSED. The line that fails is https://github.com/sequelize/sequelize/blob/2ab9439de52fefdcf4579c25fdf016b259676518/lib/dialects/abstract/connection-manager.js#L212

**Comment by mickhansen** [comment]
@janmeier

**Comment by kaspars** [comment]
Hi. Is this going to be fixed? I just spent too much time trying to setup the read/write connection, according to the documentation, and was very disappointed realising that it's actually broken for 4 months.

**Comment by mickhansen** [comment]
@kaspars everything will be fixed eventually. users of replication are the ones ideally suited to fix it. We don't have a test environment for replication hence why this wasn't caught in the change.

**Comment by kaspars** [comment]
For the test environment you could simply point both "read" and "write" to the same db node.

**Comment by mickhansen** [comment]
True, that should catch a few cases. PR welcome.
