### ISSUE TITLE
dao.get({ plain: true }) doesn't work for reloaded objects

### ISSUE THREAD

**Issue by garrett-gottlieb** [sequelize/sequelize#4844]
Consider the following example:
```js
var user = yield User.create({ settingsId })
yield user.reload({ include: settingsAssociation })

_.isPlainObject(user.get({ plain: true }).settings) // false
```

It works when the dao is retrieved using querying, just not when reloaded with `include`.

**Comment by mickhansen** [comment]
`reload` does not update the internal options of the instance (which contains what includes to iterate while doing a get).
