### ISSUE TITLE
Add support for merge/upsert

### ISSUE THREAD

**Issue by Daniel15** [sequelize/sequelize#485]
An upsert or merge does an update if a matching record already exists, otherwise does an insert. MySQL natively supports this as an atomic operation via [INSERT ... ON DUPLICATE KEY UPDATE](http://dev.mysql.com/doc/refman/5.6/en/insert-on-duplicate.html), whereas other database systems require you to do a SELECT, then an UPDATE or INSERT depending on whether the SELECT returned a row.

This is my naive generic-ish implementation, although I'm sure this could be improved and definitely needs better error handling. I'm very new at using Node.js but hopefully my code isn't too bad :P

``` javascript
/**
 * Performs an "upsert" - That is, does an update if a matching record already exists, otherwise does an insert
 *
 * @param whereProperties Names of the properties to use in the WHERE clause for matching
 * @param params Hash of parameters to use in the INSERT or UPDATE
 */
createOrUpdate: function (whereProperties, params) {
    var self = this,
        where = {};

    // Map the WHERE property names to the actual values
    whereProperties.forEach(function (key) {
        where[key] = params[key];
    });

    // Check if it already exists
    self.find({ where: where }).success(function (record) {
        // Doesn't exist, so try to do an insert
        if (!record) {
            self.create(params).error(function (error) {
                // If it's a duplicate key exception, a record with the same record was probably inserted
                // at exactly the same time, after the check above but before the insert (race condition /
                // threading issue). Just loop around again and re-run the update.
                if (error.code === 'ER_DUP_ENTRY') {
                    self.createOrUpdate(whereProperties, params);
                    return;
                }
                // TODO: If it's any other error, just throw it back
            });
        } else {
            // Record exists, so just do an update
            record.updateAttributes(params);
        }
    });
}
```

Which is used like this:

``` javascript
Blah.createOrUpdate(['username'], {
    username: 'Daniel15',
    email: 'daniel@dan.cx'
})
```

**Comment by andyxning** [comment]
@Daniel15 , i am Googling for the atomic  about INSERT ... ON DUPLICATE KEY UPDATE and is forwarded to this issue. Can you make sure that when i use multiple connection to do concurrent INSERT ... ON DUPLICATE KEY UPDATE, the procedure about in INSERT ... ON DUPLICATE KEY UPDATE will be atomic, i.e., just like an with an lock. 

Here is an example:
TABLE:

> CREATE TABLE `TICKET` (
>   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
>   `stub` char(1) NOT NULL DEFAULT '',
>   PRIMARY KEY (`id`),
>   UNIQUE KEY `idx_ticket_stub` (`stub`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8

When we execute the following sql, does it will be run perfectly without any race condition.
> INSERT INTO demo(stub) VALUES('a') ON DUPLICATE KEY UPDATE id = id + 1
