### ISSUE TITLE
Postgres should produce IS NULL query when field is undefined

### ISSUE THREAD

**Issue by GabeIsman** [sequelize/sequelize#4852]
The query

```
{
   where: {
     field: undefined
  }
}
```

Produces the unexpected output of `field = NULL`. This is contradicts postgres's [recommendation](http://www.postgresql.org/docs/8.3/interactive/functions-comparison.html) that such queries never be used. It also breaks with intuition since `field: null`, produces the different (correct) query `field IS NULL`.

Failing unit test: https://github.com/sequelize/sequelize/pull/4851.

**Comment by DoomFalc** [comment]
It's not specific to PG. It's a result of the following code in https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js, function whereItemQuery:

      if (comparator === '=' && value === null) {
        comparator = 'IS';
      } else if (comparator === '!=' && value === null) {
        comparator = 'IS NOT';
      }

**Comment by felixfbecker** [comment]
If you want to compare against `null`, you should use `null`, not `undefined`. I would actually expect sequelize to simply ignore `undefined` values.

**Comment by janmeier** [comment]
@felixfbecker Yep, me too

**Comment by DoomFalc** [comment]
Ignoring undefined values would be better than generating a XXX = NULL query
