### ISSUE TITLE
Problem with `in`

### ISSUE THREAD

**Issue by dengyaolong** [sequelize/sequelize#4855]
I want to query as the sql
```
select col1, col2 from table1 where (col1, col2) in ((1,2),(3,1))
```
If only use 
```
 col1: {
     $in: [1,3]
},
col2: {
    $in: [2,1]
}
```
just like 
```
select group_id, question_id from survey_answer where group_id in (1,3) and question_id in (2,1)
```
Output is (1,1)(1,2)(3,2)(3,1)
Actually , It's not satisfied

**Comment by dengyaolong** [comment]
now i use cycles for to build an $or array,just like.
```
$or: [{
  col1:1,
  col2:3
},{
  col1:2,
  col2:1
}]
```

**Comment by janmeier** [comment]
The code in your second post looks fine to me - we don't have a syntax for adding a where clause to several columns (actually I wasn't even aware that was possible)
