### ISSUE TITLE
Time to execute

### ISSUE THREAD

**Issue by sidneyvav** [sequelize/sequelize#4857]
I've done some tests in my application in order to discover what is slowing down my server's response time when I got many users trying to access.

I created a script that gets data from a random user so there's no cache problem, it's always a different set of data.

I created two routes, both call this script to get a random user, and realize the query. One uses sequelize and the other one uses node-mysql(https://github.com/felixge/node-mysql) that is basically a raw query, no ORM. I got the query generated by sequelize and applied to the raw query, so it's the same.

The test was done more than once per route, and the results has not a big variation.

Increasing the number of requests per minute, both routes increases response time but sequelize increases much more than raw, below a results:

40 requests per seconds during 1 minute.
response time:
node-mysql: 3.64
sequelize: 15.44

In order to node-mysql get to 15secs to respond, there must be 130 requests per seconds. With this numers of requests, sequelize can't handle. Over 30 seconds to respond.

I know that sequelize must create the objects with the result, also need to create the query by receiving the object, but is this sync according to new requests?

**Comment by mickhansen** [comment]
Not sure exactly what you're asking here? Obviously raw mysql will be faster than sequelize.
What type of query are you executing? If you have a lot of joins that will increase the parse time for Sequelize.

**Comment by sidneyvav** [comment]
It's a select with 5 joins. My question is: Does sequelize works synchronized when making the parse from multiple queries at once? Or does it needs to wait one parse to begin another?

Because the difference between response time when there're a low number of requests is insignificant. It's only a big deal with multiple processes running at once.

**Comment by mickhansen** [comment]
Parsing is synchronous yes, all javascript code but the calls that are to I/O are synchronous.
Large join queries take a great deal of parsing, which does block the event loop.
I suppose parsing could be split into pieces and done over ticks to allow other queries time to process, might be a bit complicated though.

**Comment by sidneyvav** [comment]
I'll give it a try,

thanks for the fast answer.
