### ISSUE TITLE
DATEONLY field is being parsed as a javascript Date with time/zone

### ISSUE THREAD

**Issue by arieljake** [sequelize/sequelize#4858]
I am using postgres.

My dateonly field is being stored as YYYY-MM-DD but when I pull that data down to the client, it is being sent as a full timestamp with time and timezone parts.

**Comment by dongseok0** [comment]
Same in mysql too

**Comment by denisazevedo** [comment]
It's happening in Sequelize `3.21.0` with a `date` type in Postgres :

**models/users.js:**

    dob: { 
      type: DataTypes.DATEONLY
    }

**routes/users.js:**

    User.create(user).then(function(result) {
      console.log('User created:', result.dob);
    });

**Postman response:**

`"dob": "1980-06-17T00:00:00.000Z",`

**console log:**

`User created: Mon Jun 16 1980 21:00:00 GMT-0300 (Hora oficial do Brasil)`

**Postgres select:**

`"1980-06-17"`

**Comment by lahvey** [comment]
+1
input is `"date": "2016-06-21T16:00:00.000Z"` which should be `Wed Jun 22 2016 00:00:00 GMT+0800 (CST)` with timezone, but sequelize saved as `2016-06-21`

**Comment by janmeier** [comment]
@lahvey DATEONLY saves only the date part - If you want the best time as well, use DATE

**Comment by lahvey** [comment]
So the date part should be the date string date part, no matter what the timezone is, right?
If the date string is `"2016-06-22T00:00:00+0800"`, it will save as `2016-06-22`.
If it is `"2016-06-21T16:00:00.000Z"`, then it should be `2016-06-21`

**Comment by janmeier** [comment]
Yes - I was confused by the mention of times, so I thought you were expecting the field to store timestamp as well as date.

**Comment by mbhin** [comment]
Sequelize should return only date part for DATEONLY fields. I am using below workaround in my model definitions for all DATEONLY fields and it seems to be working fine so far:

```
    regDate: {
      type: DataTypes.DATEONLY,
      get: function() {
        return moment.utc(this.getDataValue('regDate')).format('YYYY-MM-DD');
      }
    }
```

**Comment by felixfbecker** [comment]
I am constantly facing issues with this aswell. DATEONLY is timezone-independent on the database side, it should only return the date part as a string. `Date` objects are not timezone-independent. If you insert a UTC `Date` object into a DATEONLY column, the timezone will be cut off. If you query that same date, it will be parsed in local timezone, and the date part will be one day off if you are +UTC.

The problem though is not in Sequelize. It is already in the drivers, for example postgres-types which is used by pg parses DATEONLY columns as `Date` objects.

**Comment by Poitrin** [comment]
I tried @mbhin's code snippet, but it returns me the previous day of the date stored in the database. The following function is working for me:
```javascript
function getDateWithoutTime(date) {
    return require('moment')(date).format('YYYY-MM-DD');
}
```

**Comment by palodequeso** [comment]
But seriously, DATEONLY should not be parsed into a Date() object... orrrrr, at least can we just use {raw: true} to get the raw Date string? Right now, even raw is still parsing it into a Date() it seems. :(

**Comment by felixfbecker** [comment]
@palodequeso Yes. Absolutely. I want to tackle this for 4.0 as it affects me and it's a breaking change. But it depends on driver implementation. Need to open an issue at pg-types.

**Comment by afucher** [comment]
This will be avaiable in sequelize 4.0?

**Comment by sushantdhiman** [comment]
Yes, It will be. Its due in next release, hopefully end of this month.

**Comment by shan888** [comment]
+one

**Comment by shan888** [comment]
Any workaround to return date only, I tried @Poitrin way but its giving invalide date in date field

**Comment by cupliz** [comment]
this issue has been everywhere and existed from looong time ago...
please developers, at least give users freedom to get date output as we see in the database, pure output without adding timezone or bla bla in it

thanks @janmeier

**Comment by eduardrock** [comment]
Was it finally fixed?
I'm still having the same problem with the last version of Sequelize

**Comment by felixfbecker** [comment]
Could you elaborate what problem you have exactly? Please don't ping maintainers on random questions. We respond when we have time.

**Comment by eduardrock** [comment]
@felixfbecker forget it, I solved it. The problem is that I was using an old version of Sequelize

**Comment by javiertury** [comment]
DATEONLY ranges, defined as `DataTypes.RANGE(DataTypes.DATEONLY)`, are still an array of `Date` objects with timezone information.

**Comment by Vaelek** [comment]
And if we are not using Postgres?
I am simply trying to query a DATE field from a MSSQL db and get the DATE out of it.. instead I get a UTC date converted to a localized time which gives me the day before the one actually in the db.

**Comment by andersonmendesdev** [comment]
> And if we are not using Postgres?
> I am simply trying to query a DATE field from a MSSQL db and get the DATE out of it.. instead I get a UTC date converted to a localized time which gives me the day before the one actually in the db.

I'm having the same problem, my dateonly in mssql returns a date always with one day less, I even created a question in the stack but still no answer.

  Sequelize: 5.7.6
  Tedious: 6.1.1
  Sql Server 2014 express
  cloud AWS RDS.

**Comment by tonyguinta** [comment]
Same problem in MSSQL using DATEONLY. 

As an example, when querying the database directly the date is '2019-06-01', but Sequelize returns '2019-05-31'. I'm in the US Central timezone, so I assume it is still treating it as a UTC date and converting it to my timezone.

It is only returning the string in 'YYYY-MM-DD' format, which is good, but it is converting it based on my local time, which is bad.

Sequelize:  5.8.5
Tedious: 6.1.1
MS SQL Server 2017

**Comment by jpierrep** [comment]
Same Problem, DATEONLY type returns DATE complete from mysl 
 Sequelize 5.5.0

**Comment by silveoj** [comment]
Does somebody found workaround?
We updated sequelize from 4 to 5.
We use ```useUtc: false``` and ```timezone``` options.
Writing in DB works correctly.
But reading doesn't work:
- for DateTime we get JS Date as in Sequelize 4. It's good.
- for DateOnly (without time in table definitions) we get string, not Date.

I tried ```dateStrings: true/false```, ```typeCast: true/false/Function```. No results, no information about it in docs. Were they removed?

mssql: 6
tedious: 6 - 8
sequelize: 5.21.3

**Comment by jeancabral** [comment]
> Sequelize should return only date part for DATEONLY fields. I am using below workaround in my model definitions for all DATEONLY fields and it seems to be working fine so far:
> 
> ```
>     regDate: {
>       type: DataTypes.DATEONLY,
>       get: function() {
>         return moment.utc(this.getDataValue('regDate')).format('YYYY-MM-DD');
>       }
>     }
> ```

this work for me

**Comment by peabnuts123** [comment]
This isn't true any more, right? `this.getDataValue('myDateOnly')` seems to return a `YYYY-MM-DD` string now. I had to actually write a getter/setter to convert it _to_ a Date object …

**Comment by ninjasun** [comment]
It's all a bit confusing. I'm using sequelize 6.0.0-beta.3, with mysql and this is my current solution:
`
const dateOnlyFormat = "YYYY-MM-DD"
const dateTimeFormat = "YYYY-MM-DDTHH:mm"

function formatDate(date, format) {
  return moment(date).format(format);
}
dataOrdine: {
        type: DataTypes.DATEONLY,
        allowNull: true,
        get() {
          const date = this.getDataValue("dataOrdine");
          if (date) {
            return formatDate(date, dateOnlyFormat);
          }
          return null;
        },
        set(value) {
          if (value) {
            const date = new Date(value);
            this.setDataValue("dataOrdine", date);
          } else {
            this.setDataValue("dataOrdine", null);
          }
        },
      },`
maybe it can be written in a shortest way..

**Comment by Vaelek** [comment]
How is this still open after 5 years?

**Comment by imhappyfor** [comment]
@Vaelek because it's still a problem, at least it is for me when using Sequelize 5, MSSQL  with date column (remote db, have no control to change it!). Also supplying {raw:true}/{timezone: "-5:00") doesn't work either.

**Comment by pgcath** [comment]
Can confirm that this is a problem.  We're having the same issue with Sequelize 5 and MSSQL.   We can use elements of the workarounds above, but this is far less than optimal in production.

Any updates?

**Comment by igolskyi** [comment]
My [answer](https://stackoverflow.com/a/70267786/6011421) on StackOverflow for Postgres, but I duplicate it here.
For correct using queries with timezone, prepare your **pg** driver, see details [here](https://github.com/brianc/node-pg-types/issues/50#issuecomment-374412688):
```javascript    
const pg = require('pg')

const { types } = pg

// we must store dates in UTC
pg.defaults.parseInputDatesAsUTC = true

// fix node-pg default transformation for date types
// https://github.com/brianc/node-pg-types
// https://github.com/brianc/node-pg-types/blob/master/lib/builtins.js
types.setTypeParser(types.builtins.DATE, str => str)
types.setTypeParser(types.builtins.TIMESTAMP, str => str)
types.setTypeParser(types.builtins.TIMESTAMPTZ, str => str)
```
**It's must be initialized before initiating your Sequelize instance.**

You can now run a query indicating the **timezone** for which you want to get the date.

Suppose we make a SQL query, select all User's fields, and "createdAt" in timezone 'Europe/Kiev':
```SQL
SELECT "createdAt"::timestamptz AT TIME ZONE 'Europe/Kiev' FROM users WHERE id = 1;

# or with variables
SELECT "createdAt"::timestamptz AT TIME ZONE :timezone FROM users WHERE id = :id;
```

For Sequelize (for User model) it will be something like this:
```javascript
sequelize.findOne({
  where: { id: 1 },
  attributes: {
    include: [
      [sequelize.literal(`"User"."createdAt"::timestamptz AT TIME ZONE 'Europe/Kiev'`), 'createdAt'],
      
      // also you can use variables, of course remember about SQL injection:
      // [sequelize.literal(`"User"."updatedAt"::timestamptz AT TIME ZONE ${timeZoneVariable}`), 'updatedAt'],
    ]
  }
});
```

**Comment by KrisLau** [comment]
> My [answer](https://stackoverflow.com/a/70267786/6011421) on StackOverflow for Postgres, but I duplicate it here. For correct using queries with timezone, prepare your **pg** driver, see details [here](https://github.com/brianc/node-pg-types/issues/50#issuecomment-374412688):
> 
> ```js
> const pg = require('pg')
> 
> const { types } = pg
> 
> // we must store dates in UTC
> pg.defaults.parseInputDatesAsUTC = true
> 
> // fix node-pg default transformation for date types
> // https://github.com/brianc/node-pg-types
> // https://github.com/brianc/node-pg-types/blob/master/lib/builtins.js
> types.setTypeParser(types.builtins.DATE, str => str)
> types.setTypeParser(types.builtins.TIMESTAMP, str => str)
> types.setTypeParser(types.builtins.TIMESTAMPTZ, str => str)
> ```
> 
> **It's must be initialized before initiating your Sequelize instance.**
> 
> You can now run a query indicating the **timezone** for which you want to get the date.
> 
> Suppose we make a SQL query, select all User's fields, and "createdAt" in timezone 'Europe/Kiev':
> 
> ```sql
> SELECT "createdAt"::timestamptz AT TIME ZONE 'Europe/Kiev' FROM users WHERE id = 1;
> 
> # or with variables
> SELECT "createdAt"::timestamptz AT TIME ZONE :timezone FROM users WHERE id = :id;
> ```
> 
> For Sequelize (for User model) it will be something like this:
> 
> ```js
> sequelize.findOne({
>   where: { id: 1 },
>   attributes: {
>     include: [
>       [sequelize.literal(`"User"."createdAt"::timestamptz AT TIME ZONE 'Europe/Kiev'`), 'createdAt'],
>       
>       // also you can use variables, of course remember about SQL injection:
>       // [sequelize.literal(`"User"."updatedAt"::timestamptz AT TIME ZONE ${timeZoneVariable}`), 'updatedAt'],
>     ]
>   }
> });
> ```

Does anyone know of a similar solution for `tedious`?

**Comment by ephys** [comment]
If you're still experiencing this with Sequelize 5, you should update to Sequelize 6. Sequelize 5 is not maintained beyond security fixes anymore.
I can't guarantee this is fixed in Sequelize 6 but I have not personally encountered it since

**Comment by armordog** [comment]
I'm using Sequelize 6 with the 'postgres' dialect (Redshift).
And it still returns a JS Date (with the timezone screwed up) no matter what I do.
I've tried
 - setting the column type to _anything_ else (eg: `STRING`)
 - `pg.types.setTypeParser`...
 - an `afterConnect` hook that replaces the `DATE` type with a `CustomData` class that overrides `parse`

Can anyone tell me how to get Dates from a Redshift database in an actually usable fashion?

**Comment by ephys** [comment]
@armordog If you're using `DATE` instead of `DATEONLY`, then it's unrelated to this issue.
It's weird that using DataTypes.STRING returns a Date. If you open another issue that replicates the bug in question, we can take a closer look at it

**Comment by armordog** [comment]
Thanks, @ephys .
I thought it was related because they're both about Sequelize parsing a date column as a JS Date even when it shouldn't.
I'll make an SSCCE 👍

**Comment by ephys** [comment]
If your column type is actually `TIMESTAMP` then no need to open a SSCCE as it's not a sequelize bug (it only would have been a bug if both your DataType & Column Type were strings).

**Comment by ephys** [comment]
I'll close this issue as I haven't had feedback that Sequelize 6 still returns DATEONLY as Date instances

**Comment by theoephraim** [comment]
Plenty of reasons to want your DATEONLY fields as a string, but just wanted to chime in with a little tip for anyone getting very confusing incorrect dates due to the date conversion.

One of the first things I always do when setting up a new project is make sure everything is running in UTC.  Most deployed cloud/serveless/etc servers are likely to be set up this way by default already, so you're usually just making sure your local env and any edge cases are matching. To do this

## 1. Make sure you set your database timezone to UTC
Run this SQL (for postgres) - `ALTER DATABASE postgres SET timezone TO 'UTC'"); SELECT pg_reload_conf();`
Run it once, add to your migrations, etc... Just make sure your db is operating in UTC.

## 2. Make sure your running node process is operating in UTC
`process.env.TZ = 'UTC';`
Just add this to a setup file that runs before just about anything else
