### ISSUE TITLE
$notIn empty array

### ISSUE THREAD

**Issue by Znarkus** [sequelize/sequelize#4859]
Hi!

`where: { id: { $notIn: [] } }` produces `WHERE id NOT IN (NULL)` which returns nothing. Shouldn't that Sequelize query logically return every row? :)

Tested with 3.9 and 3.13.

**Comment by Znarkus** [comment]
Created a pull request https://github.com/sequelize/sequelize/pull/4860. But I realize this would be a breaking change.

**Comment by jesseditson** [comment]
Just ran in to this (using postgres), and was pretty tripped up by it. Thanks for the PR, and hopefully this will make it in so I can remove the hacks on my side!

**Comment by Znarkus** [comment]
Workaround:

```
var QueryGenerator = require('../node_modules/sequelize/lib/dialects/abstract/query-generator');
var whereItemQuery = QueryGenerator.whereItemQuery;

QueryGenerator.whereItemQuery = function(key, value, options) {
    if (value && value.$notIn && _.isArray(value.$notIn) && !value.$notIn.length) {
        return '';
    } else {
        return whereItemQuery.apply(this, arguments);
    }
};
```

**Comment by vineshhpatel** [comment]
for < 4 version, I found an alternative work around,
```
let idsToSkip = [...]; //generate array of ids, this may result in empty array
idsToSkip.push('-1'); // push a value that can not be the id in table. this will generate `not in ('-1')` query serving the purpose.
db.foo.findAll({
  where: {
    id: {
      $notIn: idsToSkip
    }
  }
});
```
check it out here, https://stackoverflow.com/a/46947550/842386
