### ISSUE TITLE
allowNull:false constraint not honoured, in case the key is mapped as a foreign key

### ISSUE THREAD

**Issue by rvnath** [sequelize/sequelize#4863]
I am creating a "requirements" table, where one of the fields "createdBy" is marked as {allowNull:false}.

```javascript
module.exports = function(sequelize, DataTypes){
  var ReqItem = sequelize.define("ReqItem", {
  ...
   createdBy: {
      type:DataTypes.INTEGER, 
      field:"created_by",
      allowNull: false
    },
  ...
```
In the same file, I am also marking this field as a foreign key.
```javascript
  //down the line...
      classMethods: {
        associate: function(models) {
          //ReqItem.hasMany(models.Attachment);
          ReqItem.belongsTo(models.User, {foreignKey:'created_by'});
          ReqItem.belongsTo(models.User, {foreignKey:'modified_by'});
       }
     }
```

But when I sync the model, I can see that `Not Null` constraint is not applied to "created_by" column.

mysql> desc requirements;

Field       | Type          | Null | Key | Default | Extra 
----------- | -------------- |----- | ----- | --------- |----------
| id          | int(11)       | NO   | PRI | NULL    | auto_increment |
| req_id      | varchar(32)   | NO   |     | NULL    |                |
| short_name  | varchar(64)   | NO   |     | NULL    |                |
| description | varchar(8192) | YES  |     | NULL    |                |
| status      | int(11)       | YES  |     | 0       |                |
| **created_by**  | int(11)       | **YES**  | MUL | NULL    |                |
| modified_by | int(11)       | YES  | MUL | NULL    |                |
| approver    | int(11)       | YES  |     | NULL    |                |
| category    | int(11)       | YES  |     | NULL    |                |
| created_on  | datetime      | NO   |     | NULL    |                |
| modified_on | datetime      | NO   |     | NULL    |                |
| deletedAt   | datetime      | YES  |     | NULL    |                |

What am I doing wrong here?

**Comment by rvnath** [comment]
[req_model.js.txt](https://github.com/sequelize/sequelize/files/34564/req_model.js.txt)
[users.js.txt](https://github.com/sequelize/sequelize/files/34565/users.js.txt)

Adding files for easy reproduction of the said issue.

**Comment by mickhansen** [comment]
`{foreignKey:'created_by'}` should match the attribute name, not field, so `{foreignKey:'createdBy'}`

**Comment by rvnath** [comment]
Thx. It works now.
