### ISSUE TITLE
unhandled validation error, message should include SQL

### ISSUE THREAD

**Issue by mark-lester** [sequelize/sequelize#4867]
I think this is a job for formatError. We dont get the offending SQL on unhandled validation errors, which would have helped a great deal in avoiding a wild goose chase I've just been on.
We print out loads of SQL as it is (which is very handy imo), I think on an error we should cough up all we've got.

**Comment by janmeier** [comment]
Can you show an example of this? Validations are run before hitting the database and before the sql is generated, so we can't really return the sql there.

**Comment by mark-lester** [comment]
yes I appreciate that there's doubtless very good reason why this isnt done.
I presume I should be catching stuff within my utility programs and printing the squeal there, so I'll go work out how to do that. we should close this.

**Comment by mickhansen** [comment]
For unique errors, which inherit validation errors, it could still be a nice thing to have.
