### ISSUE TITLE
Really slow query with include

### ISSUE THREAD

**Issue by super-cache-money** [sequelize/sequelize#4868]
I've got a really tiny postgres database (tables less than 500 rows altogether). I'm running the following query, and it's taking over 5s: 

    Job.findOne({
        where: {
            id: 162
        },
        include: [
            {
                model: models.ArtisanAssignment,
                include: [{
                    model: models.Call
                }, {
                    model: models.TeamComment,
                    attributes: ['id']
                }, {
                    model: models.StageAssignment
                }]
            },
            {
                model: models.Homeowner,
                include: [{
                    model: models.TeamComment,
                    attributes: ['id']
                }]
            },
            {
                model: models.TeamComment,
                attributes: ['id']
            }, {
                model: models.Call
            }
        ]
    }

Even weirder, however, is the raw query generated, when I enable logging. While the sequelize result takes a while, it's perfectly correct. If I run the raw query directly, it returns incorrect results. I get 1000's of records with the first row repeated. Here's the raw query generated:

    SELECT
      "Job"."id",
      "Job"."service",
      "Job"."subService",
      "Job"."details",
      "Job"."materialSupplied",
      "Job"."startDate",
      "Job"."startDateIsSpecific",
      "Job"."startDateIsFlexible",
      "Job"."area",
      "Job"."createdAt",
      "Job"."updatedAt",
      "Job"."HomeownerId",
      "Job"."TeamMemberId",
      "ArtisanAssignments"."id"                                   AS "ArtisanAssignments.id",
      "ArtisanAssignments"."wonJob"                               AS "ArtisanAssignments.wonJob",
      "ArtisanAssignments"."createdAt"                            AS "ArtisanAssignments.createdAt",
      "ArtisanAssignments"."updatedAt"                            AS "ArtisanAssignments.updatedAt",
      "ArtisanAssignments"."ArtisanId"                            AS "ArtisanAssignments.ArtisanId",
      "ArtisanAssignments"."JobId"                                AS "ArtisanAssignments.JobId",
      "ArtisanAssignments"."TeamMemberId"                         AS "ArtisanAssignments.TeamMemberId",
      "ArtisanAssignments.Calls"."id"                             AS "ArtisanAssignments.Calls.id",
      "ArtisanAssignments.Calls"."answered"                       AS "ArtisanAssignments.Calls.answered",
      "ArtisanAssignments.Calls"."createdAt"                      AS "ArtisanAssignments.Calls.createdAt",
      "ArtisanAssignments.Calls"."updatedAt"                      AS "ArtisanAssignments.Calls.updatedAt",
      "ArtisanAssignments.Calls"."ArtisanAssignmentId"            AS "ArtisanAssignments.Calls.ArtisanAssignmentId",
      "ArtisanAssignments.Calls"."JobId"                          AS "ArtisanAssignments.Calls.JobId",
      "ArtisanAssignments.Calls"."TeamMemberId"                   AS "ArtisanAssignments.Calls.TeamMemberId",
      "ArtisanAssignments.TeamComments"."id"                      AS "ArtisanAssignments.TeamComments.id",
      "ArtisanAssignments.StageAssignments"."id"                  AS "ArtisanAssignments.StageAssignments.id",
      "ArtisanAssignments.StageAssignments"."createdAt"           AS "ArtisanAssignments.StageAssignments.createdAt",
      "ArtisanAssignments.StageAssignments"."updatedAt"           AS "ArtisanAssignments.StageAssignments.updatedAt",
      "ArtisanAssignments.StageAssignments"."ArtisanAssignmentId" AS "ArtisanAssignments.StageAssignments.ArtisanAssignmentId",
      "ArtisanAssignments.StageAssignments"."StageId"             AS "ArtisanAssignments.StageAssignments.StageId",
      "ArtisanAssignments.StageAssignments"."TeamMemberId"        AS "ArtisanAssignments.StageAssignments.TeamMemberId",
      "Homeowner"."id"                                            AS "Homeowner.id",
      "Homeowner"."name"                                          AS "Homeowner.name",
      "Homeowner"."phoneNumber"                                   AS "Homeowner.phoneNumber",
      "Homeowner"."email"                                         AS "Homeowner.email",
      "Homeowner"."age"                                           AS "Homeowner.age",
      "Homeowner"."gender"                                        AS "Homeowner.gender",
      "Homeowner"."race"                                          AS "Homeowner.race",
      "Homeowner"."occupation"                                    AS "Homeowner.occupation",
      "Homeowner"."previousExperiences"                           AS "Homeowner.previousExperiences",
      "Homeowner"."usualChannels"                                 AS "Homeowner.usualChannels",
      "Homeowner"."siteExperience"                                AS "Homeowner.siteExperience",
      "Homeowner"."preferredContactMethod"                        AS "Homeowner.preferredContactMethod",
      "Homeowner"."furtherNotes"                                  AS "Homeowner.furtherNotes",
      "Homeowner"."createdAt"                                     AS "Homeowner.createdAt",
      "Homeowner"."updatedAt"                                     AS "Homeowner.updatedAt",
      "Homeowner.TeamComments"."id"                               AS "Homeowner.TeamComments.id",
      "TeamComments"."id"                                         AS "TeamComments.id",
      "Calls"."id"                                                AS "Calls.id",
      "Calls"."answered"                                          AS "Calls.answered",
      "Calls"."createdAt"                                         AS "Calls.createdAt",
      "Calls"."updatedAt"                                         AS "Calls.updatedAt",
      "Calls"."ArtisanAssignmentId"                               AS "Calls.ArtisanAssignmentId",
      "Calls"."JobId"                                             AS "Calls.JobId",
      "Calls"."TeamMemberId"                                      AS "Calls.TeamMemberId"
    FROM "Jobs" AS "Job" LEFT OUTER JOIN "ArtisanAssignments" AS "ArtisanAssignments"
        ON "Job"."id" = "ArtisanAssignments"."JobId"
      LEFT OUTER JOIN "Calls" AS "ArtisanAssignments.Calls"
        ON "ArtisanAssignments"."id" = "ArtisanAssignments.Calls"."ArtisanAssignmentId"
      LEFT OUTER JOIN "TeamComments" AS "ArtisanAssignments.TeamComments"
        ON "ArtisanAssignments"."id" = "ArtisanAssignments.TeamComments"."ArtisanAssignmentId"
      LEFT OUTER JOIN "StageAssignments" AS "ArtisanAssignments.StageAssignments"
        ON "ArtisanAssignments"."id" = "ArtisanAssignments.StageAssignments"."ArtisanAssignmentId"
      LEFT OUTER JOIN "Homeowners" AS "Homeowner" ON "Job"."HomeownerId" = "Homeowner"."id"
      LEFT OUTER JOIN "TeamComments" AS "Homeowner.TeamComments"
        ON "Homeowner"."id" = "Homeowner.TeamComments"."HomeownerId"
      LEFT OUTER JOIN "TeamComments" AS "TeamComments" ON "Job"."id" = "TeamComments"."JobId"
      LEFT OUTER JOIN "Calls" AS "Calls" ON "Job"."id" = "Calls"."JobId"
    WHERE "Job"."id" = '162';

What's going on here? Obviously happy to facilitate unpacking this problem further as much as I can.

**Comment by mickhansen** [comment]
The reason why the query is slow and why the raw query result is wrong is that Sequelize does deduplication of the cartesian product.

You have nested :M relations it looks like, that means for each top row there might actually be say, 60 association rows, Sequelize needs to parse all those rows and condense them into a single nested result, that is not necessarily speedy.

For hasMany you can try using `include.separate: true` to run includes in separate queries.

**Comment by super-cache-money** [comment]
Thank you!
