### ISSUE TITLE
PostgreSQL: Numeric treated as String

### ISSUE THREAD

**Issue by ErikvdVen** [sequelize/sequelize#4870]
I've created a view inside my PostgreSQL database, which contains data of two tables combined.

Inside that view, I have columns like "cost", which are of the type "numeric". I have specified those in my models as:
```
cost: {
    type: Sequelize.DOUBLE
},
```

I tried DECIMAL as well, no difference. The cost will be returned as String:
```
cost: "0.80",
```

Any ideas what could be the problem?

**Comment by mickhansen** [comment]
node-pg does it so you don't lose precision (since a pg double can not fully be expressed in a javascript number)

**Comment by ErikvdVen** [comment]
Ahaa! That does make sense. Thank you for the clarification :) So if I would like to calculate two fields,  it's better to do that within the query I guess?

**Comment by janmeier** [comment]
@ErikvdVen Yeah, thats probably easier
