### ISSUE TITLE
user.getAssociations not working

### ISSUE THREAD

**Issue by duncangraham** [sequelize/sequelize#4874]
I have a User and a Trip model. Users belong to many Trips and Trips belong to many Users (both through the UserTrip table). I'm using v3.13.0 with postgres. 

I can call trip.getUsers(), but when I try user.getTrips() I get the following error

```
Unhandled rejection TypeError: undefined is not a function
```

### User

```
"use strict";

module.exports = function(sequelize, DataTypes) {

  var User = sequelize.passportLocalSequelize.defineUser(sequelize, {
    // login stuff
      email:      DataTypes.STRING(254),
      hash:       DataTypes.TEXT,
      salt:       DataTypes.STRING(255),

    // personal info
      first_name: DataTypes.STRING,
      last_name:  DataTypes.STRING,
      phone:      DataTypes.STRING(12), //length needed for international numbers
      address:    DataTypes.STRING,
      city:       DataTypes.STRING,
      state:      DataTypes.STRING,
      country:    DataTypes.STRING,
      zip:        DataTypes.STRING,
      birthday:   DataTypes.DATEONLY,

    // app shit
      customerId:DataTypes.STRING(2000),
      role: DataTypes.STRING,
      credits: DataTypes.INTEGER,
      referral_id: DataTypes.STRING,
      referral_code: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        User.belongsToMany(models.Trip, {through: 'UserTrip'})
      }
    }
  });
return User;
};
```

### Trip
```
"use strict";
module.exports = function(sequelize, DataTypes) {
  var Trip = sequelize.define("Trip", {
    // waypoint info
      start_address:        DataTypes.TEXT,
      start_point:          DataTypes.STRING,

      destination_address:  DataTypes.TEXT,
      destination_point:    DataTypes.STRING,

      departure_time:       DataTypes.DATE,
      return_time:          DataTypes.DATE,

    // options
      is_private:           DataTypes.BOOLEAN,
      ride_type:            DataTypes.TEXT,
      max_passenger:        DataTypes.INTEGER,
      food_drink:           DataTypes.BOOLEAN,

    // non-visible
      passenger_count:      DataTypes.INTEGER,
      estimated_cost:       DataTypes.DECIMAL(10,2),
      actual_cost:          DataTypes.DECIMAL(10,2),
      is_completed:         DataTypes.BOOLEAN,
      organizer_id:         DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function(models) {
        Trip.belongsToMany(models.User, {through: 'UserTrip'});
        Trip.belongsTo(models.Event);
      }
    }
  });
  return Trip;
};
```

--

I can't for the life of me figure out what I'm doing wrong. I would massively appreciate any insight you might have– Let me know if there's anything I've left out that would help solve the issue

**Comment by mickhansen** [comment]
Are you sure the associate method is called on both models?
What output does `Object.keys(User.Instance.prototype)` give you?

**Comment by duncangraham** [comment]
The output  for ```Object.keys(User.Instance.prototype)``` was

```
[ '_customGetters',
  '_customSetters',
  'validators',
  '_hasCustomGetters',
  '_hasCustomSetters',
  'rawAttributes',
  'attributes',
  '_isAttribute',
  'Model',
  '$Model',
  'setPassword',
  'setActivationKey',
  'authenticate' ]
```

Testing the same for ```Object.keys(Trip.Instance.prototype)``` I got

```
[ '_customGetters',
  '_customSetters',
  'validators',
  '_hasCustomGetters',
  '_hasCustomSetters',
  'rawAttributes',
  'attributes',
  '_isAttribute',
  'Model',
  '$Model',
  'getUsers',
  'countUsers',
  'hasUsers',
  'hasUser',
  'setUsers',
  'addUser',
  'addUsers',
  'removeUser',
  'removeUsers',
  'createUser',
  'getEvent',
  'setEvent',
  'createEvent' ]
```

**Comment by mickhansen** [comment]
Does not look like `User.belongsToMany(models.Trip, {through: 'UserTrip'})` is actually called, please verify that it is.

**Comment by duncangraham** [comment]
The only time associate gets called is in [my models/index.js file](http://sequelize.readthedocs.org/en/rtd/articles/express/#modelsindexjs)

```
Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});

**Comment by mickhansen** [comment]
Please verify that the method is actually called, place a console.log statement in there or whatever.
I can't tell from your loop whether or not it actually happens, it looks like it should but from your log of the available methods it doesn't.

**Comment by mickhansen** [comment]
@duncangraham I suspected passport-local-sequelize was the culprit, hence the need for verification.
The best way to support Sequelize is to continue filing excellent issues and helping out where you can.
While we do appreciate bountysource it generally does not reach levels where it makes a real difference for the maintainers :)

**Comment by duncangraham** [comment]
Awesome! Before June I had never worked with an ORM or SQL itself. I've learned so much from Sequelize. Thanks for all of your hard work!

**Comment by dscarlin** [comment]
I am having a similar issue, none of the association methods are working for me. I am new to Sequelize.

`module.exports = (sequelize, DataTypes) => {
    let User = sequelize.define("User", {
      user_name: {
        type: DataTypes.STRING,
        allowNull: false, 
        unique: true,
        validate: {
          notEmpty: true,
        }
      },
      email: {
        type: DataTypes.STRING, 
        allowNull: false,
        unique: true, 
          validate: {
            isEmail: true
          }
      },
      phone_number: {
        type: DataTypes.STRING, 
        allowNull: false,
          validate: {
            not: ['[a-z]','i']
          }
      },
      status: {
        type: DataTypes.BOOLEAN, 
        defaultValue: false,
          validate: {
            isBoolean:function (val) {
              return (typeof(val)=='boolean')
                 }
          }
      },
      text_enabled: {
        type: DataTypes.BOOLEAN, 
        defaultValue: false,
          validate: {
            isBoolean:function (val) {
              return (typeof(val)=='boolean')
            }
          }
      } 
    });

    User.associate = (models) => {
      User.belongsToMany(models.Group, { through: 'UserGroup' } );
     
    };  
    
    return User;
}
`
`module.exports = (sequelize, DataTypes) => {
    let Group = sequelize.define("Group", {
      name: {
        type: DataTypes.STRING,
        allowNull: false, 
        validate: {
          notEmpty: true,
        }
      }
    });
    Group.associate = (models) => {
      Group.belongsToMany(models.User, { through: 'UserGroup'});
     
    };  
    return Group;
  }`

I console logged inside the if statement in index.js and they are both being associated.
They both have all the methods listed in the prototype chain. 
If I call them with db.`User.getGroups()` I get "is not a function" 
if i call `db.User.prototype.getGroups()` I get "Executing (default): SHOW INDEX FROM 'User Group' FROM 'My Database Name' and then "Unhandled rejection TypeError"Cannot read property 'id' of  undefined"

Any help would be appreciated.
