### ISSUE TITLE
Nested ordering on included models

### ISSUE THREAD

**Issue by xizhao** [sequelize/sequelize#4875]
I want to accomplish ordering with deeply included models:

```
...
include: [{
  model: models.Child,
  as: "children",
  attributes: [...],
  order: "id DESC"
}]
...
```

It seems like a top-level order[] orders your top-level query by an included field, but I'd like to instead sort the included models.  Is there a way to accomplish this?

**Comment by mickhansen** [comment]
That is only supported for hasMany associations that use `include.separate: true`.
Otherwise you'll have to use the top level nested syntax.

**Comment by jwhitmarsh** [comment]
@mickhansen can you explain how the top level nested syntax works? If I have the below query, how do I sort `Packs` by `createdAt`? 

```
app.findAll({
      where: {
        archived: false
      },
      order: [
        ['name', 'ASC']
      ],
      include: [{
        model: db.clientDbs[clientId].version,
        where: {
          archived: false
        },
        required: false,
        limit: 1,
        include: [{
          model: db.clientDbs[clientId].pack, // need to sort this model by createdAt
          where: {
            archived: false
          }
        }]
      }]
    }
```

**Comment by mickhansen** [comment]
What type of association is version here?
If it's a hasMany that code will trigger a `separate` for the second set of includes, so you might need something like:

```js
app.findAll({
  where: {
    archived: false
  },
  order: [
    ['name', 'ASC']
  ],
  include: [{
    model: db.clientDbs[clientId].version,
    where: {
      archived: false
    },
    required: false,
    limit: 1,
    order: [
      [db.clientDbs[clientId].pack, 'createdAt', 'DESC]'
    ],
    include: [{
      model: db.clientDbs[clientId].pack, // need to sort this model by createdAt
      where: {
        archived: false
      }
    }]
  }]
}
```

But not something i've tested at all.

**Comment by super-cache-money** [comment]
@xizhao Did this work?

**Comment by Maks-Yaremenko** [comment]
Anyone know how to limit and offset by an ordered nested object? =(

**Comment by MuhammadZaidSE** [comment]
@Maks-Yaremenko Same issue is happening with me.
Did you find a solution?

**Comment by derheld42** [comment]
> @mickhansen can you explain how the top level nested syntax works? If I have the below query, how do I sort `Packs` by `createdAt`?
> 
> ```
> app.findAll({
>       where: {
>         archived: false
>       },
>       order: [
>         ['name', 'ASC']
>       ],
>       include: [{
>         model: db.clientDbs[clientId].version,
>         where: {
>           archived: false
>         },
>         required: false,
>         limit: 1,
>         include: [{
>           model: db.clientDbs[clientId].pack, // need to sort this model by createdAt
>           where: {
>             archived: false
>           }
>         }]
>       }]
>     }
> ```

I tried something like the above and it did not work.

**Comment by IlyaAlpatov** [comment]
It is necessary to specify in the `order` a list of associations that lead to the desired table.
In our case, `version` and `pack`.
After that, we specify the name of the field and the type of sorting.

There can be a maximum of 4 levels of nesting.

```
app.findAll({
	where: {
		archived: false
	},
	order: [
		['name', 'ASC'],
		[
			{model: db.clientDbs[clientId].version, as: 'version' },
			{model: db.clientDbs[clientId].pack, as: 'pack'},
			'createdAt',
			'ASC'
		]
	],
	include: [{
		model: db.clientDbs[clientId].version,
		where: {
			archived: false
		},
		required: false,
		limit: 1,
		include: [{
			model: db.clientDbs[clientId].pack, // need to sort this model by createdAt
			where: {
				archived: false
			}
		}]
	}]
}
```
