### ISSUE TITLE
Table creation using schemas and PostgreSQL seems to fail

### ISSUE THREAD

**Issue by Etzos** [sequelize/sequelize#4877]
When syncing models that use a schema using PostgreSQL it seems that the tables aren't created under the schema properly, which makes references to them invalid.
NOTE: I have not tested this using anything other than PostgreSQL

**Versions:**
* Sequelize: 3.13.0
* pg: 4.4.3
* pg-hstore: 2.3.2

**Test Case:**
```javascript
sequelize.createSchema('test');

var User = sequelize.define('User', {
	first_name: Sequelize.STRING,
	last_name: Sequelize.STRING
});
User = User.schema('test');

var Product = sequelize.define('Product', {
	title: Sequelize.STRING
});

Product.belongsTo(User);

sequelize.sync({ force: true, logging: console.log });
```

**Expected Results:**
All tables are created correctly.

**Actual Results:**
`User` table is not created as `"test"."Users"` but as `"Users"`

**Edit: Forgot to include the queries actually being run, I'll spare you the errors. They boil down to `"test"."Users" not existing.`**
```
﻿Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("id"   SERIAL , "first_name" VARCHAR(255), "last_name" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "Products" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "Products" ("id"   SERIAL , "title" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "UserId" INTEGER REFERENCES "test"."Users" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
```

**Comment by janmeier** [comment]
You need to either pass schema in the options object, or call sync on the model returned by `.schema`

**Comment by Etzos** [comment]
Yeah, after poking around the code a bit I realized that the reference you get isn't the one stored by Sequelize. Perhaps the docs should mention that. Or just remove the `schema()` method altogether since it seems to be the only one that operates on a property of the object. As it is, it's very confusing.

**Comment by janmeier** [comment]
It is possible to have the same model in several schemas - for example a different schema for each customer. In that case it makes sense to dynamically change the schema, instead of storing separate models in the memory where the only difference is the schema. 

Documentation pr welcome :-)

**Comment by Etzos** [comment]
I'll see about making a doc PR later on. Hopefully later tonight if I can.

And for anyone curious about changing schema after definition and not wanting to handle their own syncing can do something like this:
```
sequelize.modelManager.removeModel(ModelName);
sequelize.modelManager.addModel(ModelName.schema('newname'));
```
Although that's using undocumented and potentially volatile calls.
