### ISSUE TITLE
NODE CRASHING BUG => Broken NPM Module

### ISSUE THREAD

**Issue by meticulo3366** [sequelize/sequelize#4878]
The `bluebird` module required by sequelize version number `3.13.0` causes a node cascade failure on the entire application stack. May be breaking other builds!

**Please revert or update the bluebird dependency so that it does not cause total application failure**

[I filed a bug report here on the broken Bluebird NPM module](https://github.com/petkaantonov/bluebird/issues/877)

![screen shot 2015-11-18 at 3 24 17 pm](https://cloud.githubusercontent.com/assets/3074572/11253538/307e08ba-8e0a-11e5-811b-61bad4e6b84d.png)

![screen shot 2015-11-18 at 3 26 47 pm](https://cloud.githubusercontent.com/assets/3074572/11253533/2a99ef2c-8e0a-11e5-9c1b-7318ab6a7c2e.png)

Package.json is below

{
  "name": "sequelize",
  "description": "Multi dialect ORM for Node.JS/io.js",
  "version": "3.13.0",
  "author": {
    "name": "Sascha Depold",
    "email": "sascha@depold.com"
  },
  "contributors": [
    {
      "name": "Sascha Depold",
      "email": "sascha@depold.com"
    },
    {
      "name": "Jan Aagaard Meier",
      "email": "janzeh@gmail.com,jmei@itu.dk"
    },
    {
      "name": "Daniel Durante",
      "email": "me@danieldurante.com"
    },
    {
      "name": "Mick Hansen",
      "email": "mick.kasper.hansen@gmail.com"
    }
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sequelize/sequelize.git"
  },
  "bugs": {
    "url": "https://github.com/sequelize/sequelize/issues"
  },
  "dependencies": {
    "bluebird": "^2.10.1",
    "depd": "^1.0.0",
    "dottie": "^1.0.0",
    "generic-pool": "2.2.0",
    "inflection": "^1.6.0",
    "lodash": "^3.9.3",
    "moment": "^2.9.0",
    "moment-timezone": "^0.4.1",
    "node-uuid": "~1.4.1",
    "semver": "^5.0.1",
    "shimmer": "1.0.0",
    "toposort-class": "^1.0.1",
    "validator": "^4.0.4",
    "wellknown": "^0.4.0",
    "wkx": "0.1.0"
  },
  "devDependencies": {
    "chai": "^3.0.0",
    "chai-as-promised": "^5.1.0",
    "chai-datetime": "^1.4.0",
    "chai-spies": "^0.7.0",
    "commander": "^2.6.0",
    "continuation-local-storage": "^3.1.4",
    "dox": "~0.8.0",
    "git": "^0.1.5",
    "hints": "^0.2.0",
    "istanbul": "^0.4.0",
    "jshint": "^2.8.0",
    "lcov-result-merger": "^1.0.0",
    "mocha": "^2.2.1",
    "mysql": "~2.9.0",
    "pg": "^4.2.0",
    "pg-hstore": "^2.3.1",
    "pg-native": "^1.8.0",
    "sinon": "^1.14.1",
    "sinon-chai": "^2.7.0",
    "sqlite3": "^3.0.6",
    "tedious": "^1.7.0",
    "watchr": "~2.4.11"
  },
  "keywords": [
    "mysql",
    "sqlite",
    "postgresql",
    "postgres",
    "mssql",
    "orm",
    "nodejs",
    "object relational mapper"
  ],
  "main": "index",
  "scripts": {
    "test": "make all",
    "test-docker": "docker-compose run sequelize /bin/sh -c \"make all\"",
    "test-docker-unit": "docker-compose run sequelize /bin/sh -c \"make test-unit-all\"",
    "build-docker": "docker-compose build",
    "docs": "node docs/docs-generator.js"
  },
  "engines": {
    "node": ">=0.6.21"
  },
  "license": "MIT",
  "gitHead": "2ec7baacd889d1627998cf8d353f43873787017e",
  "homepage": "https://github.com/sequelize/sequelize#readme",
  "_id": "sequelize@3.13.0",
  "_shasum": "245e66a7e6f6cd1d3626b81e5fb967599ee16269",
  "_from": "sequelize@>=3.10.0 <4.0.0",
  "_npmVersion": "2.14.2",
  "_nodeVersion": "4.0.0",
  "_npmUser": {
    "name": "mickhansen",
    "email": "mick.kasper.hansen@gmail.com"
  },
  "dist": {
    "shasum": "245e66a7e6f6cd1d3626b81e5fb967599ee16269",
    "tarball": "http://registry.npmjs.org/sequelize/-/sequelize-3.13.0.tgz"
  },
  "maintainers": [
    {
      "name": "sdepold",
      "email": "sascha@depold.com"
    },
    {
      "name": "durango",
      "email": "me@danieldurante.com"
    },
    {
      "name": "mickhansen",
      "email": "mick.kasper.hansen@gmail.com"
    },
    {
      "name": "janaameier",
      "email": "janzeh@gmail.com"
    }
  ],
  "directories": {},
  "_resolved": "https://registry.npmjs.org/sequelize/-/sequelize-3.13.0.tgz"
}

**Comment by janmeier** [comment]
According to you bug report on bluebird, the issue is on the 2.12 version?  Sequelize uses 3.0

**Comment by meticulo3366** [comment]
Look at my package.json it should have the detailed version used...

**Comment by janmeier** [comment]
Something is funky in your package.json then https://github.com/sequelize/sequelize/blob/master/package.json

**Comment by meticulo3366** [comment]
How would that specific sub module get funky?

**Comment by janmeier** [comment]
No idea - but our package.json specifically lists bluebird: 3.0 - Why yours looks different I have no idea
