### ISSUE TITLE
Using a column from a join table in the primary WHERE clause

### ISSUE THREAD

**Issue by jdhollis** [sequelize/sequelize#4880]
Hi, all.

Is it possible to produce equivalent SQL to this with findOne and some combination of includes?

```sql
SELECT * FROM Stories
INNER JOIN Contributions ON (Stories.id = Contributions.StoryId)
INNER JOIN Members AS Contributors ON (Contributions.ContributorId = Contributors.id)
WHERE (Stories.status = 'DRAFT' AND (Stories.AuthorId = 1 OR Contributors.id = 1));
```

It's not clear to me from the documentation, source, or my own experimentation.
Basically, I need to find a Story given either an Author id or a Contributor id, and while I can certainly run a raw query, I will also need to eager load additional associated models (which is tidier with findOne).

This is my Story model:

```javascript
const Story = sequelize.define('Story', {
…
}, {
  …
  classMethods: {
    associate: (models) => {
      …
      Story.hasMany(models.Contribution, {
        foreignKey: {
          allowNull: false,
          unique: 'ContributorId_StoryId'
        },
        onDelete: 'CASCADE'
      });

      Story.belongsToMany(models.Member, {
        as: 'Contributors',
        through: models.Contribution
      });
    }
  }
});
```

And my join model:

```javascript
const Contribution = sequelize.define('Contribution', {
  id: {
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
    type: DataTypes.INTEGER
  }
}, {
  classMethods: {
    associate: (models) => {
      Contribution.belongsTo(models.Member, {
        as: 'Contributor',
        foreignKey: {
          allowNull: false,
          unique: 'ContributorId_StoryId'
        },
        onDelete: 'CASCADE'
      });

      Contribution.belongsTo(models.Story, {
        foreignKey: {
          allowNull: false,
          unique: 'ContributorId_StoryId'
        },
        onDelete: 'CASCADE'
      });
    }
  }
});
```

**Comment by mickhansen** [comment]
Includes + 

```js
where: {
  status: 'draft',
  AuthorId: 1,
  '$Contributors.id$': 1
}
```

Should work. Can you give it a go?

**Comment by jdhollis** [comment]
I changed the query to this:

```javascript
Story.findOne({
  where: {
    $and: [
      {slug: req.params.slug, status: status.DRAFT},
      {$or: [
        {AuthorId: req.user.id},
        {'$Contributors.id$': req.user.id}
      ]}
    ]
  },
  include: [{model: Member, as: 'Contributors'}]
})
```

But I'm getting the following error:

```
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'Contributors.id' in 'where clause'
```

**Comment by mickhansen** [comment]
Ah, it's triggering a subquery because you have a limit, the `$field$` syntax won't work in that case.

**Comment by jdhollis** [comment]
Gotcha. Any workaround? Or should I just run the raw query and reload the resulting story with the right includes?

**Comment by mickhansen** [comment]
I assume you need the limit, so no not currently.

**Comment by jdhollis** [comment]
Wait. What limit?

**Comment by mickhansen** [comment]
The `limit 1` you get from using findOne, because you likely only want a single result :)

**Comment by jdhollis** [comment]
Ah. Doh. The slug part of the query will restrict it to a single record, so findOne isn't absolutely essential.

But I just tried this:

```javascript
Story.findAll({
  where: {
    $and: [
      {slug: req.params.slug, status: status.DRAFT},
      {$or: [
        {AuthorId: req.user.id},
        {'$Contributors.id$': req.user.id}
      ]}
    ]
  },
  include: [{model: Member, as: 'Contributors'}]
})
```

And ended up with a TypeError from Sequelize itself:

```
TypeError: Cannot read property '_pseudo' of undefined
      at conformInclude (node_modules/sequelize/lib/model.js:261:14)
      at node_modules/sequelize/lib/model.js:252:15
      at Array.map (native)
      at conformOptions (node_modules/sequelize/lib/model.js:251:37)
      at [object Object].Model.build (node_modules/sequelize/lib/model.js:1731:5)
      at [object Object].Model.create (node_modules/sequelize/lib/model.js:1788:15)
```

Oh well. I'll just use raw SQL for now.

**Comment by mickhansen** [comment]
Hmm, you should definitely not be getting that error.

**Comment by naellis89** [comment]
I am getting this error as well.  The only things that seem to be common with my query and the one above are they are both including a many-to-many association within a findAll with
    include: [{ model: some_model, as: 'some_models' }]

**Comment by Johnsel** [comment]
I had this error just now, turned out to be me trying to include a non-existent model in the findAll()

**Comment by spamguy** [comment]
For what it's worth, @jdhollis, digging up this ticket helped me immensely.

**Comment by MauriceButler** [comment]
Cannot read property '_pseudo' of undefined caused by non-existent model in include (typo in model name)

**Comment by Ninja-Coding-Git** [comment]
This basically happens when undefined model is included to the include collection, like @MauriceButler says, but it also can happen if you pass undefined variable/value to the list, something like:

`include: [ , ExistentModel] // look at that comma ( , )`

`include: [UnexistentModel, ExistentModel]`

`include: ['unexistent-model-name', ExistentModel]`

`include: [undefined, ExistentModel]`

`include: [null, ExistentModel]`

**Comment by ericblade** [comment]
Seems to be something worthy of adding an error condition for?  :-)

**Comment by JuanuMusic** [comment]
So, 2021. Does Sequelize have a solution to query on the parent `where` on a joined table column when using `findAllAndCount`?

**Comment by Diluka** [comment]
> So, 2021. Does Sequelize have a solution to query on the parent `where` on a joined table column when using `findAndCountAll`?
> 
> I ended up doing the filtrering the JOINED table referencing the parent... not the best solution, but it worked for my need to use findAndCountAll

So, it's 2022 now.

**Comment by ephys** [comment]
It is indeed 2022. Do you want to open a PR to resolve this issue? We'd be happy to review and merge it
We're still trying to figure out what the proper SQL for these queries should look like in https://github.com/sequelize/sequelize/issues/12971#issuecomment-1081127134

**Comment by Diluka** [comment]
As far as I know, `TypeORM` handles this very well.

**Comment by ephys** [comment]
Keep in mind that this project is entirely supported by volunteers. We'd love to be able to provide a software that is entirely bug free and feature rich, but when every change is done by someone for free in their free time, that's inevitably going to take time.
Unless you're willing to contribute to get the feature done, you'll have to be patient until someone is willing to take on this complicated task.

I'd be curious to see how TypeORM solves this though.

**Comment by nilsond** [comment]
I managed to solve it this way:

`const result: any = await MyModel.findAndCountAll({
      include: [
        {
          model: MyTwoModelModel,
          required: false,
          attributes: [],
        },
      ],
      where: condition,
      limit,
      offset,
      subQuery: false,
      raw: true,
    });`


I added subQuery: false, and raw: true
