### ISSUE TITLE
New babel update breaks sequelize imports

### ISSUE THREAD

**Issue by alexschneider** [sequelize/sequelize#4881]
The recent babel 6 update caused models written in es6 to fail to import. The reason being is because Babel killed support for CommonJS's default export behavior (default export behavior is if the default export is the only export in a file, `module.exports = exports["default"];`). Since babel doesn't do this anymore, the default export is only available as `require('modulename').default`. 

Since sequelize does a `require` [when you import a model](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L640-L641), it is impossible to import a model transformed by babel without a hack (adding `module.exports = exports["default"];` to the end of your model).

Is there any way sequelize can check for `require(path).default` for the `defineCall` function? Something like `defineCall = defineCall.default || defineCall;` or `if (typeof defineCall === 'object' && defineCall.default) { defineCall = defineCall.default; }`?

**Comment by mickhansen** [comment]
That would probably be a fine fix. You are probably most equipped to attempt a fix since you are running ES6 in your environment, PR welcome :)

**Comment by BerndWessels** [comment]
Hi, is there a npm release with babel 6 support out there already?
