### ISSUE TITLE
MySQL: multi-level dots $col parse issue

### ISSUE THREAD

**Issue by razakj** [sequelize/sequelize#4882]
Hi all,

Firstly thanks for a great ORM! Been using it for a while and we're really happy about it.

We use it mainly for MySQL and recently noticed (since ```$col``` querying functionality was introduced) that whenever actual alias generated by sequelize contains more than 2 dots it still splits all of them using ` identifier which then causes MySQL to throw syntax error.

ie.
```
{'columnName': {$col: '$user.tasks.todo.id$'}}
```
this would then generate
```
... columnName = `User`.`Tasks`.`Todo`.`id` ...
```
I'd assume that correct result should be Alias + column name since we always want to reference column
```
... columnName = `User.Tasks.Todo`.`id` ...
```

Am i missing something? For now we've been using ```$raw``` which seems to work as no parsing is applied.

**Comment by mickhansen** [comment]
It's a bug, i believe there's another issue for it.
It has tests for it aswell, which are wrong.

**Comment by razakj** [comment]
I see, could this be fixed just in ```quoteIdentifier``` in mysql query generator or is this requiring more sophisticated approach?

**Comment by mickhansen** [comment]
Just looked at the tests: https://github.com/sequelize/sequelize/blob/master/test/unit/sql/where.test.js#L309

Doesn't appear we have any for nested fields, so one will need to be added expected the new behaviour, and then it needs to be fixed here: 

https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L2187
https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L2228

**Comment by mickhansen** [comment]
Fixed recently.
