### ISSUE TITLE
upsert with MySQL returns true if the row exists but there are no changes to it

### ISSUE THREAD

**Issue by raffishquartan** [sequelize/sequelize#4885]
If `Model.upsert(data)` is called and the instance already exists but `data` has no changes to the instance's attributes then the method incorrectly returns `true`. This is using sequelize 3.14.0 and node-mysql 2.9.0.

If `data` represents a new instance then `upsert` returns true. If `data` represents an existing instance with changed attributes then `upsert` returns false. These are both as expected.

A repro demoing mysql's incorrect behavior and postgres's correct behavior (for comparison) is [here](https://github.com/cfogelberg/sequelize-playground/tree/master/tests/09-mysql-upsert-return-value) ([permalink](https://github.com/cfogelberg/sequelize-playground/tree/9928e1c43b7c66d1de77375ed6148ea4c2ed5675/tests/09-mysql-upsert-return-value)).

Interestingly, when I step through MySQL's [query.js](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query.js#L33) with a debugger, results.affectedRows == 2 when the upserted data is the same as an already existing row in the DB:

```
{
  "fieldCount": 0,
  "affectedRows": 2,
  "insertId": 0,
  "serverStatus": 2,
  "warningCount": 0,
  "message": "",
  "protocol41": true,
  "changedRows": 0
}
```

In that case, the repro script performs identically and correctly for both mysql and pg. Since the [upsert](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L546) function returns true (not false) when I don't step through it with the debugger though I am wondering if there is a race condition or async bug somewhere? I'm also don't know if this problem is in node-mysql or sequelize, but capturing here for now - hope you don't mind :)

**Comment by hlegendre** [comment]
I seem to be experiencing the same problem with mysql... An unchanged, existing row returns true instead of false...

Anyone else ?

**Comment by hlegendre** [comment]
Hi @cfogelberg,

I found the origin of this. The underlying node-mysql connection does get the right parameters (I do not know whether it is a sequelize, a node-mysql or mysql config issue) and returns the found rows instead of the affected rows...
To change this, I had to add this config to the `sequelize` object config:
```
    dialectOptions: {
      flags: '-FOUND_ROWS'
    }
```

I hope this will work for you...

Maybe a clear mention of this in the doc would be helpful...

Best,

HLG

**Comment by cfogelberg** [comment]
Thanks @hlegendre , great find
