### ISSUE TITLE
3.14.0 query with automatic model parsing error

### ISSUE THREAD

**Issue by bkniffler** [sequelize/sequelize#4886]
Hey, 
With sequelize 3.14.0 for some reason, I got unexpected behaviour when running this query (with sqlite, while previous versions work fine)
```javascript
db.query('SELECT * FROM items WHERE (lower(id) LIKE lower('%abc%') OR lower(name) LIKE lower('%abc%')) ORDER BY "id" DESC LIMIT 100',  { model: Items }).then(...).catch(...)
```

This is the error
```javascript
{ [TypeError: Cannot read property 'id' of undefined] __augmented: true }
```
My ID field is type TEXT.
```javascript
id: {
         primaryKey: true,
         type: DataTypes.TEXT,
         allowNull: false
      },
```

Rolling back to 3.13.0 works, skipping model parsing `{ model: Items }` and using the raw data also works.

**Comment by mickhansen** [comment]
You might need to combine `raw: true` with the model argument for it to work.

**Comment by bkniffler** [comment]
Hey, that seems to solve the problem, thanks!
