### ISSUE TITLE
Unable to findAll LEFT INNER JOIN for MSSQL

### ISSUE THREAD

**Issue by cly19891215** [sequelize/sequelize#4891]
HI,

I use the following query parameters for MSSQL query,

{
                where: {
                    COMPANY_GUID: company_guid,
                    USER_DIRECT_GROUP: {
                        $like: group_id
                    }
                },
                include: [
                    {
                        model: _that.sequelizeHelper.get_model('PersonalSite'),
                        where: {
                            'HOOK_INFO': 0
                        },
                        attributes: []
                    }
                ],
                attributes: ['USER_ID', 'USER_DISPLAYNAME'],
                order: [['USER_DISPLAYNAME', 'ASC']],
                offset: user_offset,
                limit: user_limit
}

For count query, it is correct,

SELECT count([tm_user].[USER_ID]) AS [count] FROM [tm_user] AS [tm_user] INNER JOIN [tm_personal_site] AS [tm_personal_sites] ON [tm_user].[USER_ID] = [tm_personal_sites].[USER_ID] AND [tm_personal_sites].[HOOK_INFO] = 0 WHERE [tm_user].[COMPANY_GUID] = '835ad170-7eac-11e5-903b-474fc7c465eb' AND [tm_user].[USER_PRIMARYEMAIL] IS NOT NULL AND [tm_user].[USER_DIRECT_GROUP] LIKE '%d8b93893-d1b3-4ca6-b64e-54284710a29d%';

But, for findAll, I get a strange sql string,

SELECT [tm_user].* FROM (SELECT [tm_user].[USER_ID], [tm_user].[USER_DISPLAYNAME] FROM [tm_user] AS [tm_user] WHERE [tm_user].[COMPANY_GUID] = 'd4ce58c0-76d6-11e5-a1de-e1ab8d5a662f' AND [tm_user].[USER_DIRECT_GROUP] LIKE '%d8b93893-d1b3-4ca6-b64e-54284710a29d%' ORDER BY [tm_user].[USER_DISPLAYNAME] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY) AS [tm_user] INNER JOIN [tm_personal_site] AS [tm_personal_sites] ON [tm_user].[USER_ID] = [tm_personal_sites].[USER_ID] AND [tm_personal_sites].[HOOK_INFO] = 0 ORDER BY [tm_user].[USER_DISPLAYNAME] ASC;

"OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY" is in the wrong place to cause get record failed.

However, I only expect the simple sql string like count query,

SELECT [tm_user].[USER_ID], [tm_user].[USER_DISPLAYNAME]   FROM [tm_user] AS [tm_user] INNER JOIN [tm_personal_site] AS [tm_personal_sites] ON [tm_user].[USER_ID] = [tm_personal_sites].[USER_ID] AND [tm_personal_sites].[HOOK_INFO] = 0 WHERE [tm_user].[COMPANY_GUID] = '835ad170-7eac-11e5-903b-474fc7c465eb' AND [tm_user].[USER_PRIMARYEMAIL] IS NOT NULL AND [tm_user].[USER_DIRECT_GROUP] LIKE '%d8b93893-d1b3-4ca6-b64e-54284710a29d%';

Thanks~~

**Comment by janmeier** [comment]
Why so you expect a select without offset and limit, when your sequelize query contains offset and limit? 

The limit has to be in a sub query in order to limit the number of user rows instead of the number of rows from the Cartesian product. 

Which error message are you getting?

**Comment by cly19891215** [comment]
Hi Janmeier,

Thanks for your reply.

The error is that using count query, I get 1. While I use the findAll query, I cannot get the record,  

In sub query, it should got 2 recordes, after INNER JOIN, one [tm_personal_sites].[HOOK_INFO] = 0,  another is 1, finally only 1 record match [tm_personal_sites].[HOOK_INFO] = 0.

Because I got the number = 1 using query count, so I set the limit = 1. But the limit is applied to the sub query, the sub query return 1 record, after INNER JOIN, it's [tm_personal_sites].[HOOK_INFO] = 1, so no record math  [tm_personal_sites].[HOOK_INFO] = 0.

**Comment by cly19891215** [comment]
Hi Janmeier,

I found a walk around, just set the [subQuery:false](http://stackoverflow.com/questions/26021965/sequelize-with-nodejs-cant-join-tables-with-limit) Parameter, then the limit is not applied to the sub query.

Please help to close this issue
Thanks a lot~~

**Comment by janmeier** [comment]
The limit needs to be added to a subquery, otherwise it will limit the number of rows from the cartesian product.

But I'm glad you found a solution :)
