### ISSUE TITLE
Proposal: "index" option in Schema definition

### ISSUE THREAD

**Issue by richthegeek** [sequelize/sequelize#4892]
When defining a schema, adding the indexes feels a bit messy as part of the options.

I was hoping there might be a shorthand like so:

```
db.define('things', {

  one: {
    type: Sequelize.STRING,
    index: true
  },

  two: {
    type: Sequelize.INTEGER,
    index: 'composite_two_three'
  },

  three: {
    type: Sequelize.INTEGER,
    index: 'composite_two_three'
  },

  four: {
    type: SEQUELIZE.INTEGER,
    index: {
      name: 'unique_four'
      unique: true
    }
  }

})
```

That would result in three indexes: things_one, composite_two_three, and unique_four.

The object-based definition (four) causes some conflicts with the existing `unique` option, and has the potential for weird behaviour if multiple columns define an index with the same name but different options.

Excluding the object-based definition this would behave almost identically to the existing `unique` option.

**Comment by richthegeek** [comment]
This seems to work when placed in models.js, around the same place the `unique` stuff takes place:

```
    if (definition.hasOwnProperty('index')) {
      var singleField = 'boolean' === typeof definition.index;
      var idxName = singleField ? self.tableName + '_' + name + '_index' : definition.index;
      var i = Utils._.findIndex(self.options.indexes, {name: idxName});

      if (i < 0) {
        i = self.options.indexes.push({
          name: idxName,
          fields: [],
          singleField: singleField
        }) - 1;
      }
      self.options.indexes[i].fields = _.uniq(self.options.indexes[i].fields.concat(definition.field))
    }
```

**Comment by BridgeAR** [comment]
@richthegeek this is already implemented. You're looking for the unique option: http://sequelize.readthedocs.org/en/latest/docs/models-definition/#definition

**Comment by richthegeek** [comment]
Not the case actually! This allows for non-unique indexes also.

**Comment by BridgeAR** [comment]
@richthegeek oh, true, I was just looking through the issues for something and should have read your comment thoroughly. Sorry about that.

**Comment by psabharwal123** [comment]
Are there any plans to implement this?
