### ISSUE TITLE
Issue with belongToMany association not working

### ISSUE THREAD

**Issue by iam-peekay** [sequelize/sequelize#4894]
Hi. I've been trying for 1.5 days to get many-to-many association nor self-association to work, but no luck. I know that I've looked at other's people code and am doing it correctly. For example, I have one self association like this 
```
User.belongsToMany(User, { as: 'Follower', through: 'Followers'});

followUser: function (userToFollow, user) {
    return Promise.all([
      User.findOne({where: {username: userToFollow}}), 
      User.findOne({where: {username: user}})])
    .then(function (userToFollow, user) {
          console.log('got here', userToFollow, user) // this returns fine, with 2 separate user objects
      return userToFollow.addFollower(user); // this throws saying: "[TypeError: userToFollow.addFollower is not a function]"
    })
    .then(function (something) {
      // DO SOMETHING;
    });
  }

```
Played around with this for hours and can't get to the bottom of it. Any help?

**Comment by mickhansen** [comment]
A `then` callback only receives a single argument, in this case it would be an array since you use Promise.all, try using `spread` instead.

**Comment by mickhansen** [comment]
If that still doesn't work, try logging `Object.keys(User.Instance.prototype)`

**Comment by iam-peekay** [comment]
@mickhansen thank you. that did work. really appreciate the quick response!
 
In terms of the N:M relationship, it works very funkily where it creates duplicate entries. Here's what I have:
```
Snippet.belongsTo(User, {foreignKey: 'userId'});
User.hasMany(Snippet, {foreignKey: 'userId'});

Snippet.belongsToMany(Tag, { through: 'snippet_tag'});
Tag.belongsToMany(Snippet, { through: 'snippet_tag'});

    User.findOrCreate({
      where: { username: user }
      // if found, adjusts snippet userId to match found user's id
    })
    .then(function (result) {
      post.userId = result[0].id;
      return Snippet.create(post);
    }).then(function (post) {
        Tag.findOrCreate({
          where: {tagname: tags[0]}
        })
        .then(function (tag) {
          post.addTag(tag); 
          cb(null, post);
        })
    })
    .catch(function(err){
      console.log(err.message);
      cb(err, null);
    });

```
The issue is that in the join table "snippet_tag", it creates the association sometimes and not other times. And when it does create it, it creates duplicate entries. In the image below, you can see it creates 2 tags for the same snippet. Is there something I am not doing correctly?

![image](https://cloud.githubusercontent.com/assets/5421194/11304767/5a924972-8f5e-11e5-9a8a-2509bccce341.png)

**Comment by iam-peekay** [comment]
Here's the error we get in the console. Any help would be appreciated! 

![image](https://cloud.githubusercontent.com/assets/5421194/11308159/6e71498a-8f71-11e5-83ec-dd94e137935e.png)

**Comment by mickhansen** [comment]
You are calling your callback before verifying that post.addTag is done.
You also need to add a return statement before Tag so the catch statement can catch everything.

**Comment by iam-peekay** [comment]
Thanks for the help! I got it to work using the below: 
```
User.findOrCreate({
      where: { username: user }
    })
    .then(function (result) {
      post.userId = result[0].id;
      Snippet.create(post)
        .then(function (post) {
        return Promise.map(tags, function (tag) {
          return Tag.findOrCreate({
            where: {tagname: tag}
          });
        })
        .then(function (tags) {
          var tagsArray = [];
          for (var i = 0; i < tags.length; i++) {
            tagsArray.push(tags[i][0]);
          }
          return post.addTags(tagsArray)
            .then(function () {
              cb(null, post);
            })
        })      
      })
    })
    .catch(function(err){
      console.log(err.message);
      cb(err, null);
    });
```

I will close the issue.

**Comment by mickhansen** [comment]
@iam-peekay You need a return before `Snippet.create` aswell to make your catch handler handle everything.
