### ISSUE TITLE
Transaction somehow hide errors when creating model with child

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#4895]
I have models Profile and User, simple 1:1 relation.

I have `User#onBeforeCreate` hook to invalidate creation on some very complicated conditions.

This code without transaction show the `onBeforeCreate` error and `User#onBeforeCreate` is called before the error is logged
```javascript
db.Profile.findOrCreate({
    where: {code: code, providerId: provider.id},
    include: [db.User],
    defaults: {user: userData}
}).spread(function(dbProfile/*, created*/) {
    return // some other promise...
}, function(e) {
    console.log('====> error', e);
    throw e;
}).then(function() {
    // other stuff
});
```

But this code with transaction swallow the error. Error is never catch, and more weird, the `User#onBeforeCreate` is logged just before the transaction commit
```javascript
db.sequelize.transaction().then(function(t) {
    db.Profile.findOrCreate({
        where: {code: code, providerId: provider.id},
        include: [{model: db.User, transaction: t}],
        defaults: {user: userData},
        transaction: t
    }).spread(function(dbProfile/*, created*/) {
        return // some other promise...
    }, function(e) {
        // never going here!
        t.rollback();
        console.log('====> error', e);
        throw e;
    }).then(function() {
        // just before commit I got log  from User#onBeforeCreate oO
        t.commit();
        // other stuff
    });
});
```

am I using transaction the wrong way?

**Comment by mickhansen** [comment]
It looks alright, although i actually have no idea if `spread` takes two arguments.
I would generally use the `catch` method callback rather than two argument then.

**Comment by JSteunou** [comment]
Promise then or spread is the same unless spread... spread the array arguments for the 1st function (resolve). Using 2nd function for reject is the same than using catch at the end.

My first example works very fine, using 2nd function for reject, or catch at the end. The result is the same.

My second example, which is just the first inside a transaction do not catch errors anymore, with 2nd function for reject nor catch.

**Comment by mickhansen** [comment]
Second example is missing a return statement (a few places actually, but the most important one is the one before the findOrCreate

**Comment by JSteunou** [comment]
I'll try that.

**Comment by JSteunou** [comment]
It changes nothing.

* Without the transaction: I really go into spread / then when creation for Profile + User going well, and I really go into the catch or spread / then 2nd argument (reject). I tried all user cases
* With transaction: I go into both spread / then and catch. In the spread / then as soon as the Profile creation is validate, so it never see the error on User creation and the transaction is comitted. If I remove the `transaction` options for Profile and just let the one for User, it catches the creation error but cannot revert the Profile creation of course.

**Comment by mickhansen** [comment]
Odd. You'll likely have to provide a SSCCE. The only meaningfull thing we changed is the bluebird upgrade.

**Comment by JSteunou** [comment]
I'm using npm shrinkwrap, I'm still with sequelize 3.12.2 and bluebird 2.10.2 for it.

**Comment by JSteunou** [comment]
Your last commits about transaction could match my issue, I'll try 3.14.1 when published.

**Comment by mickhansen** [comment]
It is published: https://www.npmjs.com/package/sequelize
That solved an issue with transaction not using correct connections in some cases, not sure it should be related here.

If it doesn't solve it you'll have to open a PR with a failing test, the info you provide here doesn't really help :/

**Comment by JSteunou** [comment]
ok just tested, it does not solve my case :(

I dont have enough time for a PR, but maybe you could let this issue open so maybe someone with the same bug will.

The use case is really simple, 2 requests, using a transaction, the promise get resolved because of the first request succeed, so t.commit is called, but the catch is still called anyway because of the 2nd request failed and the rollback cannot be perform. It's either an issue from transaction or from Promise usage or both.

I try to express this the simple I can with the little of English I know.
