### ISSUE TITLE
[BUG] using CounterCache will throw error when using the same field for multiple models

### ISSUE THREAD

**Issue by lyfeyaj** [sequelize/sequelize#4897]
My Schema:

``` javascript
Category.hasMany(Topic, { counterCache: { as: 'categoryables_count' } });
Category.hasMany(Product, { counterCache: { as: 'categoryables_count' } });

Topic.belongsTo(Category, { scope: { categoryable: 'topic' }, counterCache: { as: 'categoryables_count' } });
Product.belongsTo(Category, { scope: { categoryable: 'product' }, counterCache: { as: 'categoryables_count' } });
```

These relations will cause CounterCache plugin throw below errors

```
Error: Naming collision between attribute 'categoryables_count' and association 'categoryables_count' on model Category. To remedy this, change either foreignKey or as in your association definition
```

So, I have to comment out this line `Helpers.checkNamingCollision(this);` [counter-cache.js#L39](https://github.com/sequelize/sequelize/blob/master/lib/plugins/counter-cache.js#L39)  to make these relation definitions work as expected.

Since it is a common use case, I propose to remove that line or replace it with warnings instead of raising an error.

**Comment by mickhansen** [comment]
CounterCache is a contribution, it likely does not handle this case no.
PR with tests welcome :)

**Comment by sushantdhiman** [comment]
Closing since we have removed `counter cache` plug-in.
