### ISSUE TITLE
Database migration createTable with foreign key using schema name fails

### ISSUE THREAD

**Issue by wstallard-gobalto** [sequelize/sequelize#4898]
Fails with error: [TypeError: Cannot read property 'replace' of undefined]

Version:

````
./node_modules/sequelize-cli/bin/sequelize --version

Sequelize [Node: 0.12.0, CLI: 1.9.2, ORM: 3.12.2]
CLI version 3.9.0
Local version 3.9.0
````
using postgres dialect.

If I specify a foreign key relationship in my createTable migration passing an object specifying schema and tableName rather than a string, migration fails.

For example, the following migration fails:

````
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {

    return queryInterface.createTable({schema: 'bh', tableName: 'teststates'},
    {
      id : {type: Sequelize.UUID,
        primaryKey: true
      },
      country_id: {type: Sequelize.UUID,
        allowNull: false,
        references: {schema: 'bh',tableName:'countries'},
        referenceKey: 'id'
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false
      }
    })
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable({schema: 'bh', tableName: 'teststates'});
  }
};
````

giving the output:

````
$ NODE_ENV=dev ./node_modules/sequelize-cli/bin/sequelize db:migrate

Sequelize [Node: 0.12.0, CLI: 1.9.2, ORM: 3.12.2]

Loaded configuration file "configFiles/dev/config.js".
Using environment "dev".
Using gulpfile ~/workspace/bloodhound/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
Finished 'db:migrate' after 70 ms
== 20151120094530-test: migrating =======
[TypeError: Cannot read property 'replace' of undefined]

````

**Comment by mickhansen** [comment]
Please include the stack of the error.

**Comment by wstallard-gobalto** [comment]
Thanks again for the fast response. Unfortunately, what I posted above is the full output from db:migrate. It's not providing any more stack than that. 

Is there a way to persuade it to output more detailed errors?

**Comment by mickhansen** [comment]
Hmm, that's an issue with sequelize-cli then, it outputs error message instead of error stack.

**Comment by fredrikekelund** [comment]
I had the same problem, and I think I tracked it down to the Sequelize constructor. When 1 or 2 arguments are provided to it, it tries to parse the first argument as a URL, and uses the `protocol` property of the parsed URL to set the dialect. If the first option is a config object, which I assume is what sequelize-cli passes, this operation fails.

**Comment by kstarzyk** [comment]
Just want to +1 @fredrikekelund answer and add (maybe obvious) info: One can pass table reference by name but should be aware that if you don't override tableName (like this: http://stackoverflow.com/questions/21114499/how-to-make-sequelize-use-singular-table-names) you should add 's' to its name.

**Comment by sushantdhiman** [comment]
> seems my problem arose from requiring some of my own code

Can be closed ? @mickhansen @janmeier

**Comment by swimclan** [comment]
@fredrikekelund Thank you!!!!  FYI I needed to use the relation name (not the model name) as a string in the foreign key definition.
