### ISSUE TITLE
Database migration createTable specifying composite unique key does not work

### ISSUE THREAD

**Issue by wstallard-gobalto** [sequelize/sequelize#4899]
Migration runs, but no unique key created.

Version:

```
./node_modules/sequelize-cli/bin/sequelize --version

Sequelize [Node: 0.12.0, CLI: 1.9.2, ORM: 3.12.2]
CLI version 3.9.0
Local version 3.9.0
```

using postgres dialect.

Running the following migration:

```
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {

    return queryInterface.createTable({schema: 'bh', tableName: 'teststates'},
    {
      id : {type: Sequelize.UUID,
        primaryKey: true
      },
      country_id: {type: Sequelize.UUID,
        allowNull: false,
        unique: 'country_name'
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: 'country_name'
      }
    })
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable({schema: 'bh', tableName: 'teststates'});
  }
};
```

Creates the table, but does not create a unique key on the table. Specifying the unique key in the same way in the model and using sync() does generate the unique key.

**Comment by mickhansen** [comment]
We don't currently support adding uniques like that. It's only a feature for model.sync()

**Comment by wstallard-gobalto** [comment]
Thanks for the fast response. Are there plans to support this in the future? I am able to work around this by using raw sql in my migrations, but it would be great if Sequelize migrations had parity with what can be done with model.sync()...

Thanks for Sequelize by the way - it's a fantastic library, which I use on a daily basis....

**Comment by mickhansen** [comment]
Ideally yes sync() should map to createTable 1:1.
First priority is making sure we support all operations with individual migration calls (we need better unit testing here).
