### ISSUE TITLE
Support Sqlite3 Transaction Types: IMMEDIATE, EXCLUSIVE, RESERVED

### ISSUE THREAD

**Issue by EToreo** [sequelize/sequelize#4901]
Sqlite3 now supports 3 transaction types (IMMEDIATE, EXCLUSIVE, RESERVED): http://sqlite.org/lang_transaction.html

It seems to me that adding these to the options of a transaction would be desirable.

**Comment by EToreo** [comment]
I took a guess at how the Sequelize team would like to see this organized.  Let me know if there are any adjustments you would like to see from that pull request.

**Comment by sushantdhiman** [comment]
Transaction [types](https://github.com/sequelize/sequelize/blob/master/lib/transaction.js#L199) added in #4911
