### ISSUE TITLE
findAll raw where caluse with in and array replacements results in wrong query

### ISSUE THREAD

**Issue by umar-muneer** [sequelize/sequelize#4904]
I am using sequelize 3.14.1 with mysql and the following code fragment;

```javascript
var A = sequelize.define("A",{
	"id":{type:Sequelize.INTEGER,primaryKey:true,allowNull:false,autoIncrement:true},
	"name":Sequelize.STRING
});

var B = sequelize.define("B",{
	"id":{type:Sequelize.INTEGER,primaryKey:true,allowNull:false,autoIncrement:true},
	"aId":Sequelize.INTEGER,
	"detail":Sequelize.STRING
});
A.hasMany(B,{"foreignKey":'aId'});
return Promise.bind({}).then(function(){
	return sequelize.sync({
		"force":true
	});
}).then(function(){
	return A.create({
		"name":"test1"
	});
}).then(function(result){
	return B.bulkCreate([{"aId":result.id,"detail":"detail1"},{"aId":result.id,"detail":"detail2"}]);
}).then(function(){
	return A.findAll({
		"include":[{
			"model":B,
			"where":['aId not in (?)',[10,11]]
		}]
	});
}); 
```
the find All call results in the following query 

> SELECT `A`.`id`, `A`.`name`, `A`.`createdAt`, `A`.`updatedAt`, `Bs`.`id` AS `Bs.id`, `Bs`.`aId` AS `Bs.aId`, `Bs`.`detail` AS `Bs.detail`, `Bs`.`createdAt` AS `Bs.createdAt`, `Bs`.`updatedAt` AS `Bs.updatedAt` FROM `As` AS `A` INNER JOIN `Bs` AS `Bs` ON `A`.`id` = `Bs`.`aId` AND aId not in ([10,11]);

this query results in the following error
>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[10,11])' at line 1

However if i revert to 3.12 and run the same code fragment it runs without an error and generates the correct query

>SELECT `A`.`id`, `A`.`name`, `A`.`createdAt`, `A`.`updatedAt`, `Bs`.`id` AS `Bs.id`, `Bs`.`aId` AS `Bs.aId`, `Bs`.`detail` AS `Bs.detail`, `Bs`.`createdAt` AS `Bs.createdAt`, `Bs`.`updatedAt` AS `Bs.updatedAt` FROM `As` AS `A` INNER JOIN `Bs` AS `Bs` ON `A`.`id` = `Bs`.`aId` AND aId not in (10, 11);

I have gone through the change log for versions 3.13 and 3.14 but i couldn't find any related information.

**Comment by shoshomiga** [comment]
+1 I have seen the same issue, I'm pretty sure it is a bug in 3.14

**Comment by mickhansen** [comment]
Likely a bug. But why aren't you just using `$notIn: [10, 11]`?

**Comment by umar-muneer** [comment]
@mickhansen , some of our old production code still uses the raw where clause technique. Any ETA for the fix?

**Comment by mickhansen** [comment]
@umar-muneer No ETA. Looks like it's triggering the PG array logic though.

**Comment by NewGyu** [comment]
:+1:

**Comment by mickhansen** [comment]
@NewGyu Also using the mysql dialect?

**Comment by NewGyu** [comment]
@mickhansen Yes,using mysql dialect.

**Comment by shoshomiga** [comment]
I tracked this regression down to commit #6e13324ffe421589948602a415ec4a691a887e16

Possibly has something to do with this line of code https://github.com/sequelize/sequelize/commit/6e13324ffe421589948602a415ec4a691a887e16#diff-cd46718046bf2e6aded332613f220001L77

**Comment by shoshomiga** [comment]
https://github.com/sequelize/sequelize/pull/4949

**Comment by shoshomiga** [comment]
#4951

I had to make a new PR because I rebased, sorry about that, I'm still kinda new to this github thing
