### ISSUE TITLE
hasMany error: [TypeError: Cannot read property 'replace' of undefined]

### ISSUE THREAD

**Issue by villanuevawill** [sequelize/sequelize#4905]
const org = yield Organization.create(this.request.body.organization);
       yield org.addUser(user);

The relationship is as follows:

       Organization.hasMany(User);
       User.belongsTo(Organization);

The error is as follows:

    [TypeError: Cannot read property 'replace' of undefined]

However, below works fine:

    yield user.setOrganization(org)

Any ideas?  Can you lead me in the right direction?  Should I post more information?

**Comment by mickhansen** [comment]
Please include the error stack.
