### ISSUE TITLE
JSON Field Names Using Snake Case

### ISSUE THREAD

**Issue by poyannabati** [sequelize/sequelize#4906]
Is it possible to define a model which uses camelCase for the attributes, but underscore/snake case when converted to json, or maybe even a field name that will be used for JSON only?

Currently;

    var User = seq.define('user', {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true
        },
        shortLivedToken: {
            type: Sequelize.STRING,
            field: 'short_lived_token'
        },
        longLivedToken: {
            type: Sequelize.STRING,
            field: 'long_lived_token'
        }
    }, {
        underscored: true,
        underscoredAll: true,
    });

Turns into when calling response.json(user)

    {
      "id": null,
      "shortLivedToken": "abcde",
      "longLivedToken": "fghji",
      "updated_at": "2015-11-21T18:32:20.181Z",
      "created_at": "2015-11-21T18:32:20.181Z"
    }

And I want it to be

    {
      "id": null,
      "short_lived_token": "abcde",
      "long_lived_token": "fghij",
      "updated_at": "2015-11-21T18:32:20.181Z",
      "created_at": "2015-11-21T18:32:20.181Z"
    }

Any ideas?

**Comment by mickhansen** [comment]
Not possible. The attribute names are used for getting values, toJSON uses methods for getting values.
Overwrite toJSON or don't use camel cased attribute names.
