### ISSUE TITLE
3.14.0+ doesn't propagate unhandled rejections

### ISSUE THREAD

**Issue by bestan** [sequelize/sequelize#4907]
Running following code doesn't show any errors in 3.14.0 onwards:

```javascript
process.on("unhandledRejection", function(err) {
  //This is never called in 3.14.0 and above, but works fine in 3.13.0
  console.log('unhandled', err);
});

Model.findOne({
  where: {
    id:1
  }
}).then(function(instance) {
  throw err;
});
```

Ideally I should be catching errors in the findOne promise, but if it was forgotten, then application silently times out.

**Comment by mickhansen** [comment]
Bluebird was upgraded, possibly the reason.

**Comment by JSteunou** [comment]
Could it be possible to use native Promise ? node >= 0.12 I think.

**Comment by mickhansen** [comment]
@JSteunou native promises don't support the features we use, it has worse performance aswell.

**Comment by JSteunou** [comment]
Says bluebird author, but you could also find benchmark saying the opposite http://ciplogic.com/index.php/blog/92-native-vs-bluebird-vs-core-promise-benchmark 

I dont know who to trust on performance, but native Promise dont break on upgrade.

**Comment by mickhansen** [comment]
Refactoring the entire codebase to use native promises is not a priority.

**Comment by janmeier** [comment]
Works fine on latest master
