### ISSUE TITLE
DATE(6) fields are stored in MariaDB as '0000-00-00 00:00:00.000000'

### ISSUE THREAD

**Issue by ouadi** [sequelize/sequelize#4908]
Hi,

I have moved from version `3.13.0` to `3.14.0`. `sync()` now interprets `DATE(6)` as `DATETIME(6)`. However, inserting a value result in `0000-00-00 00:00:00.000000`.

Tracking down the issue, I found that the sql string supplied to `sequelize.query()` withing `QueryInterface.prototype.insert()` contains a date with time zone (something like `2047-10-03 05:34:42.412 +00:00`).

[As DATETIME columns doesn't support Time Zone in MariaDB](https://mariadb.com/kb/en/mariadb/time-zones/#time-zone-effects), the related part in the supplied string (`+00:00` in the above exemple) should be avoided.

More details about the issue are herein after.
##### The Model Definition

``` javascript
sequelize.define('SampleModel', {
    id: {
        field: 'ID',
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    code: {
        field: 'CODE',
        type: Sequelize.STRING(30),
    },
    name: {
        field: 'NAME',
        type: Sequelize.STRING(60),
    },
    date1: {
        field: 'DATE1',
        type: Sequelize.DATE(6),
        orgnlType: 'date',
    },
    createdBy : {
        field : 'CREATED_BY',
        type : Sequelize.STRING(30),
        allowNull : false,
        validate : {},
    },
    createdOn : {
        field : 'CREATED_ON',
        type : Sequelize.DATE,
        allowNull : false,
        validate : {},
    },
}, {
    tableName: 'SAMPLE_MODEL',
    timestamps: false,
    freezeTableName: true,
});
```
##### The created table with `sync()`

``` sql
CREATE TABLE IF NOT EXISTS `SAMPLE_MODEL` (
  `ID` INTEGER auto_increment , 
  `CODE` VARCHAR(30), 
  `NAME` VARCHAR(60), 
  `DATE1` DATETIME(6), 
  `CREATED_BY` VARCHAR(30) NOT NULL, 
  `CREATED_ON` DATETIME NOT NULL, 
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;
```
##### Sample SQL for insert as logged within `QueryInterface.prototype.insert`

``` sql
'INSERT INTO `SAMPLE_MODEL` (
  `ID`,
  `CODE`,
  `NAME`,
  `DATE1`,
  `CREATED_BY`,
  `CREATED_ON`) 
VALUES (
  DEFAULT,
  \'wQrDDnf$oE\',
  \'[Yxtn[Mr^H\',
  \'2047-10-03 05:34:42.412 +00:00\',
  \'System\',
  \'2015-11-22 16:54:38\'
);'
```

**Comment by janmeier** [comment]
This line https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/data-types.js#L35 should do its own stringificiation instead of calling the base type, which add time zone
