### ISSUE TITLE
Usage of promise anti-patterns in the docs

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#4909]
In the docs, you can see examples like this all over the place:
```js
Task.bulkCreate([
  {subject: 'programming', status: 'executing'},
  {subject: 'reading', status: 'executing'},
  {subject: 'programming', status: 'finished'}
]).then(function() {
  Task.destroy({
    where: {
      subject: 'programming'
    },
    truncate: true /* this will ignore where and truncate the table instead */
  }).then(function(affectedRows) {
    // affectedRows will be 2
    Task.findAll().then(function(tasks) {
      console.log(tasks) // no programming, just reading :(
    })
  })
})
```
This completely misses the best feature of promises and makes them no better than callbacks. You are not chaining the promises, you don't escape callback hell, and you don't propagate errors. It should really be like this:
```js
Task.bulkCreate([
  {subject: 'programming', status: 'executing'},
  {subject: 'reading', status: 'executing'},
  {subject: 'programming', status: 'finished'}
]).then(function() {
  return Task.destroy({
    where: {
      subject: 'programming'
    },
    truncate: true /* this will ignore where and truncate the table instead */
  })
}).then(function(affectedRows) {
  // affectedRows will be 2
  return Task.findAll()
}).then(function(tasks) {
  console.log(tasks) // no programming, just reading :(
}).catch(function(error) {
  console.error('bad error happened :/')
})
```
Flat structure, no callback hell, and you only need ONE catch at the end to handle errors. With arrow functions this would become even cleaner.

I think this is very important because it is a common pitfall for people coming from callback style to promises and then they just copy+paste examples from the internet and miss the point of promises.
Docs should teach people the best practice(s) to use their library, including showing how to handle errors.

**Comment by faceleg** [comment]
Are the docs PR-able?

**Comment by felixfbecker** [comment]
https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.DOCS.md
I would make a PR but I don't have any spare time atm, could be weeks or months before I find the time.
So I opened the issue first, maybe someone else has more time at his/her hands.

**Comment by mickhansen** [comment]
Great deal of the docs were converted with a search/replace when we moved to promises. They could definitely be better.
