### ISSUE TITLE
Add CUBRID Database support

### ISSUE THREAD

**Issue by kadishmal** [sequelize/sequelize#491]
As [CUBRID Database](http://www.cubrid.org) gaining its pace, I will be glad to work on adding CUBRID support to sequelize. At this moment we use CUBRID through plain [node-cubrid](https://github.com/CUBRID/node-cubrid) + [generic-pool](https://github.com/coopernurse/node-pool) combination.

I was planning to develop an ORM for node-cubrid, but when I read the sequelize documentation I thought it would be more beneficial to contribute to sequelize than start the work from scratch.

Please let me know whether you would accept PR with a CUBRID patch.

**Comment by janmeier** [comment]
There has been no requests for this for a very long time so I'm closing this
