### ISSUE TITLE
Strange warning with node 5 and Model.findAll()

### ISSUE THREAD

**Issue by bemon** [sequelize/sequelize#4910]
when using model.findAll() (no particular model definition) with node 5 and sequelize 3.14.1 warning is shown:

```
Warning: a promise was created in a  handler but was not returned from it
  at ConnectionManager.disconnect (server\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:126:10)
at ConnectionManager.$disconnect (server\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:257:41)
at server\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:223:16
From previous event:
     at Promise.then (\server\node_modules\sequelize\lib\promise.js:21:17)
     at Model.findAll (\server\node_modules\sequelize\lib\model.js:1365:6)
...
```

used code is just:
```javascript
campaigns.findAll({limit: 10});
```

Sequelize is used with koa.js with strong use of generators.

**Comment by mickhansen** [comment]
It's not Node 5, it's the new Bluebird version, we're working on fixing it.

**Comment by nadim** [comment]
Was this fixed? I'm still receiving this warning using findAll:

Warning: a promise was created in a handler but was not returned from it at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Model.findAll (node_modules/sequelize/lib/model.js:1343:18)

...

**Comment by mickhansen** [comment]
@nadim Most places in the Sequelize codebase should have been fixed.

**Comment by nadim** [comment]
In case you're interested, this code seems to be trigger it:

    ```
aModel.findAll({
            where: {
                modelId: {
                    $eq: null
                }
            },
            attributes: ['a', 'b', 'c', 'd'],
            include: [{
                model: anotherModel,
                as: anotherModel.tableName,
                where: {
                    'e': {
                        $gte: aThirdModel.f
                    }
                }
            }]
        });
```

I've turned off bluebird warnings using the environment variable (BLUEBIRD_WARNINGS=0) for now.
