### ISSUE TITLE
return last inserted id when creating a new value

### ISSUE THREAD

**Issue by feniixx** [sequelize/sequelize#4914]
Is there a way to get the last inserted id, or actually, the id of the inserted row?

I have this func to create a new value:

```javascript
function post( request, response ) {

    models.xxx.create( {

            field1: request.body.field1,
            field2: request.body.field2

        } )
        .then( function ( x ) {

            //x = 0 || 1;
            response.json( x );
            //What I would like to send is the `id` of the new row

        } );

}
```

Is there a way?

**Comment by janmeier** [comment]
`x` will be the created model, which has an id property (assuming you have added the id column to your model, or let sequelize add it for you). I'm not really sure what the issue is here, everything should work out of the box. If you still have issues, could you show your mode ldefinition?

**Comment by mickhansen** [comment]
It looks like you are casting a model instance to an integer hoping that will return the primary key?
While that would be neat it's not entirely practical since javascript does not allow operate overloading.

Simply `response.json(x.get('id'))`

**Comment by feniixx** [comment]
Oh you're right, don't know why I remmembered it outputed 1...
