### ISSUE TITLE
[TypeError: Object {34,3224} has no method 'map']

### ISSUE THREAD

**Issue by th3o6a1d** [sequelize/sequelize#4922]
```
[TypeError: Object {34,3224} has no method 'map']
Warning: a promise was created in a  handler but was not returned from it
    at process._tickDomainCallback (node.js:492:13)
Warning: a promise was created in a  handler but was not returned from it
    at ConnectionManager.disconnect (/var/app/current/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:162:10)
    at ConnectionManager.$disconnect (/var/app/current/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:257:41)
    at /var/app/current/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:223:16
From previous event:
    at Promise.then (/var/app/current/node_modules/sequelize/lib/promise.js:21:17)
    at Object.updateUser (/var/app/current/controllers/db.js:88:8)
    at Server.exports.postMe (/var/app/current/controllers/auth.js:411:8)
    at next (/var/app/current/node_modules/restify/lib/server.js:906:30)
    at f (/var/app/current/node_modules/restify/node_modules/once/once.js:17:25)
    at /var/app/current/controllers/auth.js:58:17
    at /var/app/current/node_modules/jsonwebtoken/index.js:130:18
    at process._tickDomainCallback (node.js:492:13)
Executing (default): SELECT "uuid", "scope", "givenNam"
```

Hello. When I upgraded from 3.13 to 3.14, I started getting these errors. Sequelize seems to be interpreting the input '{34,3224}' as an object instead of an array literal. I was surprised, as my understanding is that inputs are being escaped as strings. Would you be able to point me in the right direction of what to do so I can stay up to date with the latest builds?

Thanks,

Jason

**Comment by mickhansen** [comment]
Can you show the call you are doing?

**Comment by th3o6a1d** [comment]
```
function updateUser(account, callback) {
    User.update(account, {
        where: {
            email: account.email
        }
    }).then(function() {
        return getUser(account, callback);
    },function(error){
        console.log(error);
        return getUser(account,callback);
    });
};
```
Is this what you mean? Thanks.

**Comment by janmeier** [comment]
Where is the actual input `{34,322}` coming from ?

**Comment by th3o6a1d** [comment]
`{34,322}` comes from req.params and gets set as the `favorites` property of `account`. It's passed in a POST request to update the user's account.

**Comment by mickhansen** [comment]
@th3o6a1d what type is the field, JSON or ARRAY?

**Comment by th3o6a1d** [comment]
`type: Sequelize.ARRAY(Sequelize.TEXT)`

**Comment by mickhansen** [comment]
@th3o6a1d Sequelize expects a javascript array in that case. `['34', '322']`

**Comment by th3o6a1d** [comment]
I see. However, can you explain why upgrading from 3.13 to 3.14 broke it?

**Comment by mickhansen** [comment]
Can't point to a line of code, but it looks like we fixed a bug.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/blob/f482790b85ef2336bb97893c0eaa127d9d6bbc77/lib/dialects/postgres/data-types.js#L343-L360 expects an array when stringifying the array

**Comment by th3o6a1d** [comment]
Fair enough. I'll refactor. Might want to fix it so the error message is clearer, since this is a validation error, no?

Thanks for looking into this.

**Comment by janmeier** [comment]
It should be validated if you enable `options.typeValidation` http://docs.sequelizejs.com/en/latest/api/sequelize/

**Comment by th3o6a1d** [comment]
Already am.
