### ISSUE TITLE
Custom generated primary keys

### ISSUE THREAD

**Issue by oravecz** [sequelize/sequelize#4923]
Is there a technique that I haven't found in the documentation for providing my own primary key values? For example, I would like to use Flake to calculate PK.

**Comment by raffishquartan** [comment]
What happens when you specify the value of the column during instance
creation? E.g if primary key is id:

Model.create({ primary_key_column: 'foo' });

On Wednesday, 25 November 2015, Jim Cook notifications@github.com wrote:

> Is there a technique that I haven't found in the documentation for
> providing my own primary key values? For example, I would like to use Flake
> to calculate PK.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sequelize/sequelize/issues/4923.

##

**Comment by raffishquartan** [comment]
Typo, I'm on mobile and knocked send, substitute "primary_key_column" for
"id":

Model.create({ id: 'foo', ... });

On Wednesday, 25 November 2015:

> What happens when you specify the value of the column during instance
> creation? E.g if primary key is id:
> 
> Model.create({ primary_key_column: 'foo' });
> 
> On Wednesday, 25 November 2015, Jim Cook <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Is there a technique that I haven't found in the documentation for
> > providing my own primary key values? For example, I would like to use Flake
> > to calculate PK.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/sequelize/sequelize/issues/4923.
> 
> ## 
> 
> ## Christo Fogelberg
> 
> t: +44 797-2111006
> 
> e: xxxxx
> <javascript:_e(%7B%7D,'cvml','xxxx');>

##

**Comment by mickhansen** [comment]
```
sequelize.define('Model', {
  columnName: {
    type: DataTypes.STRING,
    field: 'column_name',
    primaryKey: true,
    defaultValue: function() { return flake(); }
  }
});
```

**Comment by oravecz** [comment]
@cfogelberg I don't want the user to create the key value while using the builder pattern as I want it hidden from them.
@mickhansen I had set the defaultValue to flake() -- straight up, and it didn't do as I expected. I'll attempt to wrap it in a function and see what happens.

**Comment by mickhansen** [comment]
@oravecz settings the default value to the result of a method call would mean the default value is the same for all creates.

**Comment by mickhansen** [comment]
You could however probably just do `defaultValue: flake`, without the method call.

**Comment by oravecz** [comment]
Thanks, that worked. I had to wrap my use of Flake because I implemented it as a generator.

```
   var Account = db.client.define( 'Account', {
        accountId: {
            type: Sequelize.STRING,
            primaryKey: true,
            defaultValue: function() {
                return db.flake.next().value
            }
        },
```

**Comment by oravecz** [comment]
I added a pull request for documentation of this feature
https://github.com/sequelize/sequelize/pull/4936
