### ISSUE TITLE
findAll() order by association counts?

### ISSUE THREAD

**Issue by poonwu** [sequelize/sequelize#4924]
```
User.hasMany(Post, {foreignKey: userId});
Post.belongsTo(User, {foreignKey: userId});
User.findAll( {
  include: [Post],
  order: 'COUNT(Post.id)'
});
```

How do I fetch user such that the rows are ordered by association counts?

**Comment by mickhansen** [comment]
Not sure it's possible like that, you likely either need a subquery or a grouping.
Joins create cartesian products, order works on rows, for each row there's only a single instance of each.
