### ISSUE TITLE
mixing replacements with ::TIMESTAMP

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#4928]
Hi,

Is that possible to mix the replacements ( http://docs.sequelizejs.com/en/latest/docs/raw-queries/#replacements ) for raw queries with type casting in postgresql?
I have the next example:

``` javascript
 let result = yield sequelize.query("SELECT count(id) from users where client=:client AND createdat>:from::TIMESTAMP)", {
     type: Sequelize.QueryTypes.SELECT,
     replacements: {
         client: client
         from: moment(from).format('YYYY-MM-DD HH:mm:ss'),
         //    to: to
     }
 });
```

And sequelize expects to have `TIMESTAMP` in `replacements`.
Even when I go with `createdat>to_timestamp(:from,'yyyy-MM-dd HH:mm:ss')` it results the same error (`:mm` missing).

Tried to search how it's possible to overcome this, but for now without the success.

Any thoughts? (I want to use replacements, not **bind**)

Regards,

**Comment by PavelPolyakov** [comment]
Question is still actual, any thoughts?

**Comment by PavelPolyakov** [comment]
@mickhansen

sorry for mentioning you directly, but still interested if it's possible to make it works somehow.
I found that replacements are merged to the query using the lodash method:
https://lodash.com/docs#template

However, for now I was not able to find where we set that ```:var``` placeholders are parsed.
Because, in the docs it's stated that it should support the next notation:
```javascript
var compiled = _.template('hello <%= user %>!');
compiled({ 'user': 'fred' });```

**Comment by mickhansen** [comment]
Hmm, `::` is supposed to be ignored actually.

**Comment by PavelPolyakov** [comment]
I think the best variant is to came up with some escape character for the ```:```.
