### ISSUE TITLE
Get type of field

### ISSUE THREAD

**Issue by masious** [sequelize/sequelize#4929]
Hi.
I want to have the types of the fields of a model, having the model class itself. How can I have it?

**Comment by mickhansen** [comment]
`Model.rawAttributes[key].type`

**Comment by masious** [comment]
@mickhansen But here is the result of `Model.rawAttributes.createdAt.type`:
```{ options: { length: undefined }, _length: '' }```
Which could be answer if I had something different for a field of `TEXT`. But they are exactly the same... :/

**Comment by mickhansen** [comment]
The attribute type is an instance of the data type prototype, you can check the prototype of the function for naming.

Or you can check that the prototype is what you expect, i.e. `type instanceof DataTypes.DATE`
