### ISSUE TITLE
Check if column exists

### ISSUE THREAD

**Issue by norisalsaadie** [sequelize/sequelize#4934]
Hello,

I have a question regarding DB migrations with an existing database and tables. Trying to get the flow to scaffold the tables and migrate columns automatically with npm start, both locally and on production. On production the table is already there with columns (we were using node-db-migrate to handle this), trying to replace this with sequelize. It works very well until it comes time to migrate the columns, if the column is already there it throws an unhanded exception. Is there a way to handle this gracefully or check if the column is already there before running the migration?

Of course, I can use the .error on the promise but I was looking for a solution within tool. 

Thanks

**Comment by mstmustisnt** [comment]
+
urgent for me as well

**Comment by justechn** [comment]
I am also interested in a way to check if a column exists before running the migration

**Comment by felixfbecker** [comment]
Take a look at QueryInterface.describeTable()

**Comment by justechn** [comment]
Thanks, that works for columns, but I noticed it does not contain any information about foreign keys, or indexes. Is this on purpose or something that will be added later?

**Comment by felixfbecker** [comment]
Not on purpose, contributions in that regard are welcome

**Comment by Benew** [comment]
+1... how comes this is closed and inactive for that long ?
