### ISSUE TITLE
Compatibility with shouldjs?

### ISSUE THREAD

**Issue by oravecz** [sequelize/sequelize#4937]
Has anyone been able to use the should-promised module with Sequelize? 
```
var save = account.save()
save.should.be.a.Promise()

save.should.eventually.be.rejected()
save.should.eventually.not.be.rejected()
save.should.finally.be.rejected()
save.should.finally.not.be.rejected()
save.should.be.rejected()
save.should.not.be.rejected()
```

This passes the test runner. Are the promises returned by Sequelize not compatible with the shouldjs library?

**Comment by mickhansen** [comment]
We use bluebird which implements the promise spec and more.
I know for a fact it works with chai-as-promised, it should work with should aswell i'd imagine, you might want to look for known issues with bluebird and should.
