### ISSUE TITLE
upsert in Postgres overwrites "createdAt" on update

### ISSUE THREAD

**Issue by konrad-garus** [sequelize/sequelize#4940]
If the row already exists, upsert overwrites its `createdAt` value. I believe it should leave this one intact and only touch `updatedAt`.

**Comment by sushantdhiman** [comment]
@mickhansen, @janmeier ,  I have tried to recreate the issue on my machine but `upsert` worked correctly. Then I findout this issue has been fixed 6 months ago [here](https://github.com/sequelize/sequelize/blob/master/test/integration/model/upsert.test.js#L253). I think @konrad-garus was using some old version.

**Comment by janmeier** [comment]
Thanks for the detective work @sushantdhiman ! :)
