### ISSUE TITLE
Count children

### ISSUE THREAD

**Issue by poyannabati** [sequelize/sequelize#4942]
I have a Poll which hasMany Items. Is it possible to create a virtual field like Poll.itemCount which always has the latest count of items for that poll?

The documentation was quite sparse on the scope of virtual fields IMHO.

**Comment by mickhansen** [comment]
You could create a virtual field like that by adding a count attribute statement to the default scope that targets a virtual column.

You can also take a look at CounterCache: https://github.com/sequelize/sequelize/blob/e6c42a4acc4af0caf20c9562c247784621982146/test/integration/plugins/counter-cache.test.js

**Comment by poyannabati** [comment]
Not sure exactly what you meant by the first suggestion; I was using a similar count attribute but it resulted in a left outer join instead of a subquery, as I would have wished. Is there any support for running subqueries? Is there an example in the docs perhaps?

For future Googlers, let me drop my solution here; probably not what you're supposed to do, but it seems to be working.

        numVotes: {
            type: Sequelize.VIRTUAL(Sequelize.INTEGER, '(SELECT COUNT(id) from votes WHERE image_id = `image`.id) as numVotes')
        }

**Comment by mickhansen** [comment]
VIRTUAL supports dependency fields via an array as the second argument to
the VIRTUAL constructor.
It's concatted onto the find options here:
https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L88

Your code would probably better as type: Sequelize.VIRTUAL(Sequelize.INTEGER,
[[db.literal('(SELECT COUNT(id) from votes WHERE image_id = `image`.id)'),
numVotes']]) We don't have any tests for this functionality at the moment,
but would be great to add :)

On Tue, Dec 1, 2015 at 9:23 PM, poyannabati <notifications@github.com>
wrote:

> Not sure exactly what you meant by the first suggestion; I was using a
> similar count attribute but it resulted in a left outer join instead of a
> subquery, as I would have wished. Is there any support for running
> subqueries? Is there an example in the docs perhaps?
>
> For future Googlers, let me drop my solution here; probably not what
> you're supposed to do, but it seems to be working.
>
>     numVotes: {
>         type: Sequelize.VIRTUAL(Sequelize.INTEGER, '(SELECT COUNT(id) from votes WHERE image_id = `image`.id) as numVotes')
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/4942#issuecomment-161084892>
> .
>



-- 
Mick Hansen
@mhansendev
mhansen.io

**Comment by tanepiper** [comment]
I have a working solution for this:

So in your model you can define a virtual field:

```
myVirtualCount: {
  type: Sequelize.VIRTUAL(Sequlize.INTEGER, [[sequelize.literal('(SELECT COUNT(`Subthings`.`id`) FROM `Subthings` WHERE `Subthings`.`thing_id` = `Thing`.`id`)'), 'thingCount']])
}
```

Then when you do a query you need to include it in the attributes:

```
Thing.findAll({ attributes: { include: ['thingCount'] }})
```

This will then pull through the correct value for the subquery count.

**Comment by nwalters512** [comment]
@tanepiper found this after hours of trying to make this work - many thanks! This should really be in the docs somewhere; this seems like a pretty common use case.
