### ISSUE TITLE
queryInterface.removeColumn fails during migration

### ISSUE THREAD

**Issue by apsavin** [sequelize/sequelize#4943]
Sequelize [Node: 4.2.2, CLI: 2.2.1, ORM: 3.14.0]
mssql

``` js
module.exports = {
  up: function(queryInterface) {
    return queryInterface.removeColumn('TableName', 'ColumnName'));
  },

  down: function(queryInterface, Sequelize) {
    return queryInterface
      .addColumn('TableName', 'ColumnName', {
        type: Sequelize.STRING(100),
        field: 'ColumnName',
        allowNull: false,
        defaultValue: 'some value',
      });
  },
};
```

`removeColumn` will fail because of `defaultValue` constraint.
And I [can't](https://github.com/sequelize/sequelize/issues/3116) set up a name for the constraint so it's not convenient to remove the constraint with plain sql query (query becomes more complex because I need to get the constraint's name firstly)

**Comment by mickhansen** [comment]
I was not aware that default values could constrain the table in any way.
Can you post the SQL called and the full error message?

**Comment by apsavin** [comment]
I was not aware, too, but now I am aware) Thanks to ms.

Sequelize error message:
`Unhandled rejection SequelizeDatabaseError: ALTER TABLE DROP COLUMN ColumnName failed because one or more objects access this column.`

```sql
sql> ALTER TABLE TableName DROP COLUMN ColumnName
[2015-11-29 15:00:28] [S0001][5074] The object 'DF_TableName_ColumnName is dependent on column 'ColumnName'.
```

Because of 

```sql
ALTER TABLE TableName
    ADD CONSTRAINT DF_TableName_ColumnName
    DEFAULT N'some value' FOR ColumnName;
```

When I use `queryInterface.addColumn` with `defaultValue` behavior is the same, just the name of constraint is not so `beautiful` because ORM auto-generates it.

See [this](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a1ea6d8d-bef1-4f6e-8f66-a16b812de6fc/drop-column-with-default-constraint?forum=transactsql) discussion on social.msdn.microsoft.com. It's a [common](https://github.com/laravel/framework/issues/4402) problem. Unfortunetaly, I can't find any official ms docs about it.

Workaround: just use `queryInterface.sequelize.query` instead of `addColumn`/`removeColumn` methods if the column has a default value.

**Comment by MichaelKearnsSoftwire** [comment]
This is also an issue my team has been working around for a while.

I've submitted a PR for this -- if somebody could take a look that would be useful.

**Comment by harshithkashyap** [comment]
PR #4990 has been merged. This issue should be closed.
