### ISSUE TITLE
Self Join through Bridge Table -> Cyclic Reference Error

### ISSUE THREAD

**Issue by frikkievb** [sequelize/sequelize#4946]
Hi

I am trying to achieve the following:

I have a table called "document". This contains some document entries.  Each document can be linked to another document via a table called "link".  I've tried various attempts at this, but I am always running into a cyclic reference error.

This is the associations for the Link model:

```
associate: function (models) {

                Link.belongsTo(models.Document,{
                    foreignKey:"documentID"
                });

                Link.hasOne(models.Document,{
                    foreignKey:"linkedDocumentID"
                })



            }
```

The associations for the Document model:

```
associate: function (models) {

                Document.hasMany(models.Link,{
                    foreignKey:"documentID"
                });

            }
```

With this implementation I am getting the cyclic reference.

So I attempted this:

```
associate: function (models) {

                Document.belongsToMany(models.Document,{
                    as:"LinkedDocuments",
                    through:models.Link,
                    foreignKey:"linkedDocumentID"
                });

            }
```

But this is not returning any data.

I am obviously missing something, but can't figure it out for the life of me.

Please assist.

Thank you!

**Comment by mickhansen** [comment]
You have a cyclical constraint. You'll need to add `constraints: false` to one of the your associations and add them manually after.
