### ISSUE TITLE
querying by date function

### ISSUE THREAD

**Issue by elliotstokes** [sequelize/sequelize#4947]
Im wanting to find all rows that are created less than 3 minutes ago in Postgres.

I can do the query in postgres: 

    where "createdAt" > now() - interval '3 minutes'

Im currently trying to work out how to specify that query via sequelize:

So far I have 

    models.MyModel.find({where:{ CreatedAt:  {$gt : "now() - interval '3 minutes'"}})

This isn't working. Any help/guidance would be appreciated.

**Comment by elliotstokes** [comment]
Would sequelize.literal help here or is there a better way?

**Comment by mickhansen** [comment]
You'll probably need to use `sequelize.literal()` for this atm yes.

**Comment by elliotstokes** [comment]
Cool thanks a lot.

**Comment by muhammad-bin-zafar** [comment]
`Model.findAll({where: {createdAt: ...}})` doesn't seem to work.
