### ISSUE TITLE
Build 3.14.x breaks postgresql geo column integration

### ISSUE THREAD

**Issue by AndyAdamczak** [sequelize/sequelize#4950]
I have class defined as the following:

  var Zone = sequelize.define('Zone', {
    id : { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true, allowNull: false, field: 'id' },
    name : { type: DataTypes.STRING(200), field: 'name' },
    comment : { type: DataTypes.TEXT, field: 'comment' },
    startDate: { type: DataTypes.DATE, field: 'start_date' },
    endDate: { type: DataTypes.DATE, field: 'end_date' },
    shape : { type: DataTypes.GEOMETRY, field: 'shape' },
    fieldArea : { type: DataTypes.DECIMAL(15, 5), field: 'field_area' },
  }

The shape field has the following description in postgres:
CREATE TABLE geo.zones
(
  id serial NOT NULL,
  name character varying(200),
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  deleted_at timestamp with time zone,
  shape geography,
  field_area numeric(15,5),
  comment text
}

When getting the shape property for the object in build 3.13.0 and before, I would get the following object (for example, with the coordinates removed), which is a geojson object:

{ type: 'Polygon',
  coordinates:
   [ [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] ] }

When I get the same shape property in 3.14.x I get the following:

0103000020E6100000010000000E00000010A467EBFE5558C0E8B04366AB3E45405525A377435658C030E2BCD9AB3E45409D418ADC415658C0F3A60D2B163F45405F7C99BE415658C02212F9184E3F4540B5B068FF415658C06194CBFC983F4540A4988C78315658C0D27E766D993F45404AB812A01C5658C030172C85983F4540D1FCE597F55558C00E075D9D983F454019042BB7F25558C0C727519D973F45403526D8B5E55558C0C2C2FC3C973F4540CD34F113C55558C032761684973F4540C8F519AEA45558C0917EE6A8953F4540219A354BA55558C0FC32872AAC3E454010A467EBFE5558C0E8B04366AB3E4540

This is the raw data in the column, not a geojson shape as it was before.

**Comment by janmeier** [comment]
Are you using model.find or a raw query? Seems the parser is not identifying the geometry type correctly

**Comment by AndyAdamczak** [comment]
It's part of a larger query (the model Zone part is what is getting the wrong data):
        
var searchOptions = {
          include: [ PlannedExpense, ActualExpense, { model: FieldImage, where: { missing: false, invalid: false }, required: false }, { model: Zone, include: [ ZoneProperty ], required: false, where: { layer_id: { $in : layerIds } } } ]
        };

        Field.findById(fieldId, searchOptions).then(function (field) {

**Comment by janmeier** [comment]
Can you create a [SSCCE](http://sscce.org/) - that makes it a lot easier to debug the isseu

**Comment by janmeier** [comment]
ping @AndyAdamczak

**Comment by janmeier** [comment]
Closing, no response
