### ISSUE TITLE
How to know if schema is up-to-date

### ISSUE THREAD

**Issue by thynson** [sequelize/sequelize#4959]
I want to do some test with my migrations.
After running all migration-tasks, is there a way to test if the tables in the database is **exactly** same as if they are created via `sync` method?

**Comment by mickhansen** [comment]
Not currently possible in any easy way.

**Comment by janmeier** [comment]
Related to https://github.com/sequelize/sequelize/issues/537 - once we know how the alter tables, we also know how to check if nothing needs altering
