### ISSUE TITLE
allowNull should prevent empty string

### ISSUE THREAD

**Issue by ericvicenti** [sequelize/sequelize#496]
I think this test should work, yet fails (can be tested with `mocha sequelize.bug.js`)

https://gist.github.com/ericvicenti/ee7dddb42e74d30aa912

If this is the wrong usage, then how can I validate against an empty string?

**Comment by JahnoelRondon** [comment]
https://sequelize.org/docs/v6/core-concepts/validations-and-constraints/

```
  effect: {
    type: DataTypes.TEXT("long"),
    allowNull: false,
    validate: {
      notEmp
```ty: true,
    },
  },
