### ISSUE TITLE
Confusion about the 'Enforcing a Foreign Key Reference Without Constraints' documentation

### ISSUE THREAD

**Issue by Chaulky** [sequelize/sequelize#4960]
In the section on [Enforcing a Foreign Key Reference Without Constraints](http://docs.sequelizejs.com/en/latest/docs/associations/#enforcing-a-foreign-key-reference-without-constraints), it say the example code will create the relations between the tables (the foreign keys) without any constraints. However, if you run that code (with a call to `sync()`), the tables created have both the explicit relation without constraints, and the implicit relation with constraints from calling `hasOne()` and `hasMany()`. What am I missing here?

When is says "In that case you can manually add the reference attributes to your schema definition, and mark the relations between them.", what does it mean to mark the relations between them?

**Comment by janmeier** [comment]
If you don't want the implicit relations, you should pass `constraints: false` to the associations http://docs.sequelizejs.com/en/latest/api/associations/

> In that case you can manually add the reference attributes to your schema definition, and mark the relations between them

It's just a slightly clunky way of saying that if you don't want to add a sequelize association or a `ON UPDATE` constraint, you can use `references`

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
