### ISSUE TITLE
schema option for sequelize constructor

### ISSUE THREAD

**Issue by thynson** [sequelize/sequelize#4962]
Sequelize constructor has default options for define, where we can specify a schema and later it will be applied when we define model.
However I think it should be put on root of the config object, that is,

``` javascript
{ schema: 'unit_testing' }
```

rather than

``` javascript
{ define: { schema: 'unit_test' }}
```

since `getQueryInterface()` has no place to set default schema. 
I know there is a `sequelize.schema()` function. But it would be nice to have globally specified schema via constructor, and it should make the code more clear.

**Comment by mickhansen** [comment]
Makes sense, might also simplify things for users with a few schemas by letting them have a sequelize instance per schema (although pooling would not be shared of course).
