### ISSUE TITLE
Sequelize.js. How to find object in JSON datatype?

### ISSUE THREAD

**Issue by mabc224** [sequelize/sequelize#4963]
I am writing `query JSON` data in `sequelize.js` using `postgres` db.

**Postgres table structure**

    id: integer,
    name: string,
    data: json

**Here is my data structure**

    {
    	id: 3,
    	name: "v4th79j"
    	data: {
    		phone: "123456789",
    		email: "example@gmail.com",
    		password: "$2a$10$qCttQ8leMPCzJfE",
    		company_id: 2
    	}
    }

**I am writing query like this**

    var filter = {};
    // Filter by email for a user
    filter.where = { data: { email: "example@gmail.com"} } ;
    Entity.findOne(filter)
    .then(function (entity) {
    console.log(JSON.stringify(entity))
    });

but it is not working. *How to find object in JSON datatype?*

**Comment by janmeier** [comment]
That should be the correct syntax, as per http://docs.sequelizejs.com/en/latest/docs/querying/#jsonb

What is happening? Error, filter ignored ? Which version?

**Comment by mabc224** [comment]
It just does not work. It stop there.
You are referring to jsnob. i am using `json` data type.

**Comment by mabc224** [comment]
PostgreSQL treat *json* datatype as text so querying about one field is not possible. It stores the raw text of the JSON data in the database, complete with white space and retaining all the orders of any keys and any duplicate keys.

I convert data type to *jsonb* which is introduced in [9.4][1] version of PostgreSQL. 

With JSONB, it turns the JSON document into a hierarchy of key/value data pairs. All the white space is discarded, only the last value in a set of duplicate keys is used and the order of keys is lost to the structure dictated by the hashes in which they are stored. We can apply index on specific field and can search any specific field using [sequelize.js][2] easily. 

You can read more about with practical example [here][3]


  [1]: http://www.postgresql.org/docs/9.4/static/datatype-json.html
  [2]: http://docs.sequelizejs.com/en/latest/docs/querying/#jsonb
  [3]: https://www.compose.io/articles/is-postgresql-your-next-json-database/

**Comment by mabc224** [comment]
i am nt getting data when it go

**Comment by mahnunchik** [comment]
Documentation was moved http://docs.sequelizejs.com/en/latest/docs/querying/#jsonb

**Comment by jobelenus** [comment]
☝️ docs are not there either.

**Comment by zubair-saif** [comment]
> I am writing `query JSON` data in `sequelize.js` using `postgres` db.
> 
> **Postgres table structure**
> 
> ```
> id: integer,
> name: string,
> data: json
> ```
> 
> **Here is my data structure**
> 
> ```
> {
>     id: 3,
>     name: "v4th79j"
>     data: {
>         phone: "123456789",
>         email: "example@gmail.com",
>         password: "$2a$10$qCttQ8leMPCzJfE",
>         company_id: 2
>     }
> }
> ```
> 
> **I am writing query like this**
> 
> ```
> var filter = {};
> // Filter by email for a user
> filter.where = { data: { email: "example@gmail.com"} } ;
> Entity.findOne(filter)
> .then(function (entity) {
> console.log(JSON.stringify(entity))
> });
> ```
> 
> but it is not working. _How to find object in JSON datatype?_

thanks its working for mine
