### ISSUE TITLE
transaction context

### ISSUE THREAD

**Issue by akaRem** [sequelize/sequelize#4964]
Is it possible to make transaction context?

Currently (according to docs) I do manually pass transaction as parameter and I hate this junk in my code.

Example:

```
...

function startTransaction(req, res, next) {
  db
    .transaction({
      autocommit: false
    })
    .then(function (tr) {
      req.transaction = tr;
      return next()
    })
}

const app = express()
  .use('/api', express
    .Router()
    .use(bodyParser.json())
    .use(startTransaction)
    .post('/accounts', wrap(function * (req, res) {
      try {
        req.auth = {};
        // create an account
        var account = yield db.models.Account.create({type: req.body.account.type}, {transaction: req.transaction});
        req.auth.account = account;

        // create user under account
        var user = yield account.createUser({
          name: req.body.user.name,
          email: req.body.user.email
        }, {transaction: req.transaction});
        req.auth.user = user;

        // set password for user
        yield user.setPassword(req.body.user.password);
        yield user.save({transaction: req.transaction});

        // create session
        var session = yield user.createSession({}, {transaction: req.transaction});
        req.auth.session = session;
        // commit all
        yield req.transaction.commit();
        // format the response
        return res.json({
          status: 'created',
          token: req.auth.session.token
        })
      } catch (err) {
        yield req.transaction.rollback();
        return res.json({status: err})
      }
    }))
```

this `{transaction: req.transaction}` everywhere makes code hard to read.

Is there any possibilities to use transaction "silently"?

I mean define once and then use by default like this (__MAGIC__ means starting transaction which works in context of request):

```

...

const app = express()
  .use('/api', express
    .Router()
    .use(bodyParser.json())
    .use(__MAGIC__)
    .post('/accounts', wrap(function * (req, res) {
      try {
        req.auth = {};
        // create an account
        var account = yield db.models.Account.create({type: req.body.account.type});
        req.auth.account = account;

        // create user under account
        var user = yield account.createUser({
          name: req.body.user.name,
          email: req.body.user.email
        });
        req.auth.user = user;

        // set password for user
        yield user.setPassword(req.body.user.password);
        yield user.save();

        // create session
        var session = yield user.createSession();
        req.auth.session = session;
        // commit all
        yield db.commit();
        // format the response
        return res.json({
          status: 'created',
          token: req.auth.session.token
        })
      } catch (err) {
        yield db.rollback();
        return res.json({status: err})
      }
    }))
```

If such things do exist, it would be very cool to update docs with info on how to do such things.

Many thanks in advance.

**Comment by mickhansen** [comment]
It's actually right there in the docs: http://docs.sequelizejs.com/en/latest/docs/transactions/

**Comment by akaRem** [comment]
@mickhansen Does this magic works with `co` module, generators, thunks and promises?
How can I be sure (debug and prove to myself), that it _really_ gives different unique transactions for every request? How can I find that this mechanism failed? And in which cases it will fail?
Can you suggest any midddleware which will automatically run every request in different transaction and automatically commit on success or revert on exception?

Is it possible to update documentation with more information?
Because for me it's very short and unclear explanation of CLS. I think, I'm not alone with this misunderstanding. (I thought it will automatically run every statement in one predefined transaction, e.g. same for every request.)

Many thanks in advance.

**Comment by akaRem** [comment]
@mickhansen 

I found this issue on SO: http://stackoverflow.com/questions/29351728/sequelize-cls-transaction-not-used

And there are a lot of issues about CLS under this repo.
So CLS doesn't seem to be reliable to me.

Is there any other option to create transaction context for queries?

something like

```
var transaction = new Transaction(sequelize)
var user = yield transaction.models.User.create(...)
var groups = yield user.getGroups()
```

or 

```
var wrapper = new Transaction()
var user = yield wrapper(sequelize.models.User).create(...)
var groups = yield wrapper(user).getGroups()
```

**Comment by mickhansen** [comment]
CLS is the only way currently.
Another solution would be to allow users to clone sequelize with a transaction option so its automatically applied to all calls.

**Comment by janmeier** [comment]
`new Transaction` sounds a bit like Unit of Work https://github.com/sequelize/sequelize/issues/4639
