### ISSUE TITLE
Includes only seem to work in a given order

### ISSUE THREAD

**Issue by Namingwaysway** [sequelize/sequelize#4966]
I am seeing the following error message from the following code:
Unhandled rejection Error: place is not associated to product_report!

product.findAll({include: [{        
                                        required: true,
                                        model: product_report,
                                        include : [place]
                                       }],
                                      where: {id:prod[0].id}}).then(function(prod){....

The models are defined to have the following relationships:
product.hasMany(product_report)
place.hasMany(product_report)

however, by changing the code to the following:
product.hasMany(product_report)
product_report.hasMany(place) <------

the error does not happen.

It seems that a relationship is not reflexive in sequelize, and the order of the includes must be correct.  Am I just using include incorrectly and this is proper behavior, or is this a bug?

**Comment by Namingwaysway** [comment]
In order to get the above to work, I had to also add 

product_report.belongsTo(place)

Should that not be added by default?

**Comment by mickhansen** [comment]
Order of include statements should not matter unless they differ in options.
Reverse associations are not added by default.

**Comment by Namingwaysway** [comment]
So, you are saying that in the above example, with only 
product.hasMany(product_report)
place.hasMany(product_report)
defined as associations,
both 
product_report.find(...[include: place]...) 
and 
place.find(...[include: product_report]...) 

should work without issue?

**Comment by mickhansen** [comment]
Well, no, because in that case you're likely wanting a N:M association and you should use belongsToMany.

Is your relationship 1:M or N:M?

**Comment by Namingwaysway** [comment]
It is 1:M, but when I select from the M by id, I would like the reference to the 1.

for example, a place has many product_reports.  When I findAll product reports, I also want to return the place they are at.  That does not seem to work if I simply define place.hasMany(product_report)

**Comment by mickhansen** [comment]
For 1:M you need a hasMany/belongsTo pair.
You want product_report.belongsTo(place)

**Comment by Namingwaysway** [comment]
If that is expected behavior, could you update the documentation to reflect that those relationships are only one way and need to be defined in pairs?

**Comment by mickhansen** [comment]
That is expected behaviour. PR to add clarification welcome.
