### ISSUE TITLE
Tagging Queries

### ISSUE THREAD

**Issue by nicolasgramlich** [sequelize/sequelize#4968]
ORMs tend to create very verbose queries that often have a similar beginning. Query logs of popular database setups tend to be capped at reasonable lengths (defaults usually 1k characters). The problem with this many database analysis tools (like vividcortex) group querys by query log, inadvertently confusing queries to be grouped together just because they start the same. 

One workaround generally suggested is tag a query with a comment, so that it ends up being executed like this:
`SELECT /* tag=foo */ * FROM ...`

Does sequelize provide an api to do something like this?

Thanks

**Comment by mickhansen** [comment]
Currently no API that would solve that issue.
