### ISSUE TITLE
Setting an instance's associations at create- or build-time is buggy

### ISSUE THREAD

**Issue by cfogelberg** [sequelize/sequelize#4970]
The script below fails with a `SequelizeUniqueConstraintError: Validation error`. This is because `isNewRecord` is set to true while creating the Thing. This option value is passed to `Instance#_setInclude` which passes it to `include.model.build`, so the built instance is set to be new. When the Thing object is saved its included objects are saved as well, generating the unique constraint error.

A script demonstrating (and an alternate approach using a transaction, you need to uncomment the correct block of code) is here: https://github.com/cfogelberg/sequelize-playground/tree/master/tests/15-build-with-associations

From a first look, the fix is to modify `Instance#_setInclude` to check the included instance if it is new.

Would a PR with tests demonstrating this bug and a fix for it be welcome?

Additionally, the syntax for creating or building an instance that is associated at creation time with another is pretty obscure and not documented. Would a PR for this be welcome?

Additionally additionally, I think there is a minor bug in line 277 of instance.js which means that all properties in the created instance which are not includes must be specified via the `fields` option.

```javascript
'use strict';

var Promise = require('bluebird');
var Sequelize = require('sequelize');
var _ = require('lodash');

var sq_config = require('../sequelize-config-pg');
sq_config.options.define.schema = 's14';
sq_config.options.define.paranoid = false;
var sq = new Sequelize(sq_config.database, sq_config.username, sq_config.password, sq_config.options);

var models = {
  User: sq.define('User', {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    email: {
      type: Sequelize.STRING
    }
  }),
  Thing: sq.define('Thing', {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    name: {
      type: Sequelize.STRING
    }
  })
};

models.Thing.belongsTo(models.User);

function print_result(description, result) {
  console.log(description + ':\n' + JSON.stringify(result, null, 2));
  return result;
}

function swallow_rejected_promise(result_set, err) {
  console.warn('REJECTED PROMISE: ' + result_set + ' -- ' + err);
  console.warn(err.stack);
  return null;
}

sq.sync({ force: true })
.then(function () {
  return models.User.create({email: 'asdf@example.org'});
})
.then(function(user) {
  return models.Thing.create({ // fails while trying to save included User instance - it is treated as a new record
    name: 'thingthing',
    User: user
  }, {
    include: [{
      model: models.User
    }],
    fields: ['name'] // seems nec to specify all non-included fields because of line 277 in instance.js - bug?
  });
})
.then(print_result.bind(null, 'Thing with User...'))
.catch(swallow_rejected_promise.bind(null, 'main promise chain'))
.finally(function() {
  return sq.close();
});
```

**Comment by mickhansen** [comment]
Known issue for belongsTo with non null fields, there's another issue somewhere.

**Comment by cfogelberg** [comment]
I think #3807 is the issue you mean (it is the only belongsTo and non-null fields issue I could find), but that is a different problem:

- This issue is a problem in Instance#_setInclude, where it requires included instances to have a defined primary key but have the same new-record state as the including instance.
- #3807 is a validation problem with non-null foreign key constraints

**Comment by mickhansen** [comment]
Hmm, i use nested create quite a bit without defining primary keys.

**Comment by mickhansen** [comment]
Oh, i completely missed that you are using an existing instance for nested create.
We actually don't support that currently, we only support creating with pure values.

**Comment by raffishquartan** [comment]
What about a PR that allows creation of an instance with an
already-persisted association? The API should mirror the existing API for
creation with pure values:

  models.Model.create({
    // ... other attributes
    AssociatedModel: a_user_instance
  }, {
    include: [AssociatedModel]
  });

**Comment by mickhansen** [comment]
@cfogelberg That would definitely be welcome :) We still need to flesh out exactly how creates with existing, and updates might work with nested create.

**Comment by DiegoRBaquero** [comment]
@mickhansen Was it ever implemented? Creating with an existing instance of the association?

**Comment by danfsd** [comment]
Any news on that? Because it seems like passing `include` into `Model.create` is still not including it on the resulting instance... 😕

**Comment by mickhansen** [comment]
@DiegoRBaquero Not to my knowledge
