### ISSUE TITLE
MySQL Fulltext support (MATCH AGAINST)

### ISSUE THREAD

**Issue by opsclub** [sequelize/sequelize#4971]
I'm looking to add/contribute http://dev.mysql.com/doc/refman/5.6/en/fulltext-search.html support for fulltext, so when passing:

``` javascript
where: {
  name: {
    $match: 'john'
  }
}
```

Your WHERE clause ends up with:

``` sql
MATCH(name) AGAINST('john')
```

Should I be doing this as key/comparators or a sequelize.fn (like 'cast' or 'max')?

Note the difference in dialects:

Postgres is:

``` sql
to_tsvector(name) @@ to_tsquery('john')
```

MSSQL is:

``` sql
CONTAINS(name, 'john')
```

**Comment by mickhansen** [comment]
key/comparators is the way to go, we're moving away from functions.
Would be great if you could come up with a design for full text operators that would work across dialects supporting full text search.

**Comment by opsclub** [comment]
I'll see what I can do. Thanks Mick

**Comment by ConAntonakos** [comment]
Hi. Are there any updates to this? This sounds like an awesome feature to have!

**Comment by ddeshmane** [comment]
Hi. Does Sequelize really support MySQL full test search ? At least following link give the impression that is does support:
https://github.com/sequelize/sequelize/issues/2979  

Please provide the links that describes how to do this.

**Comment by smich** [comment]
Hi. Are there any updates on this issue? This is a much needed feature. I tried to add a raw condition with literal replacement in a where object which apparently is not allowed in the current version.

Thanks,

**Comment by shoshomiga** [comment]
Would be nice if this was implemented as it seems there is no way to do this without raw queries in the current version

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/1580
