### ISSUE TITLE
Sequelize relations are represented flattened objects instead of objects with nested arrays

### ISSUE THREAD

**Issue by dzuluaga** [sequelize/sequelize#4973]
Hi there, I've just started using Sequelize and I love it! Kudos guys!

Currently, the output of my data from Sequelize is generated as a flattened structure with dot labels, instead one object with nested object arrays. What am I missing? Thanks!

Here's an example to visualize it better:

```javascript
[
  {
    "id": "5007000000OAWdm",
    "case_number": "1526",
    "CaseComments.commentbody": "..."
  },
  {
    "id": "5007000000OAWdm",
    "case_number": "1526",
    "CaseComments.commentbody": "..."
  }
]
```
Instead of this representation, I was expecting to get this one:
```javascript
[
  {
    "id": "5007000000OAWdm",
    "case_number": "1526",
    "CaseComments": [
        {"commentbody": "..."}, 
        {"commentbody": "..."}, 
        {"commentbody": "..."}
     ]
  },
  {
    "id": "5007000000OAWbb",
    "case_number": "1528",
    "CaseComments": [
         {"commentbody": "..."},
         {"commentbody": "..."},
         {"commentbody": "..."}
      ]
  },
]
```
My models and the route are defined as this:
```javascript
//case.js
module.exports = function(sequelize, DataTypes) {
  var Case = sequelize.define("Case", {
    case_number : DataTypes.STRING
    },
    {
      freezeTableName: true,
      timestamps: false,
      tableName: 'mt_case',
      schema: 'sfdc',
      classMethods: {
        associate: function(models) {
          Case.hasMany(models.CaseComment, {foreignKey: 'case_id'})
        }
      }
    });
  return Case;
};
```

```javascript
//case_comment.js
module.exports = function(sequelize, DataTypes) {
  var CaseComment = sequelize.define("CaseComment", {
      commentbody : DataTypes.STRING
    },
    {
      freezeTableName: true,
      timestamps: false,
      tableName: 'mt_casecomment',
      schema: 'sfdc',
      classMethods: {
        associate: function(models) {
          CaseComment.belongsTo(models.Case, {
            foreignKey: 'case_id'
          });
        }
      }
    });
  return CaseComment;
};
```
/cases route:
```javascript
router.get('/', function(req, res) {
  where = ( req.query.where && JSON.parse(req.query.where) || null );
  console.log( where );
  models.Case.findAll({
    where: where,
    order: req.query.order || [],
    include: [ {model: models.CaseComment, as: "CaseComments", attributes: ['commentbody']} ],
    raw: true
  })
  .then(function( cases ) {
    res.json( cases );
  })
  .catch( function( error ){
    res.send( error );
  })
});

```

**Comment by mickhansen** [comment]
You'll need to remove `raw: true`

**Comment by dzuluaga** [comment]
Awesome. Thanks @mickhansen. That worked. However, when I remove ```raw: true```, since my models definitions have no column definition, I get an array of empty elements. I used to pass ```attributes: ['*']``` to include all columns.

Is there a way to generate all columns by default when raw isn't set?

Like this:
```
[
  {},
  {}
]
```

**Comment by mickhansen** [comment]
Hmm, afraid not, you'll need to define the attributes on the mode or use `attributes: ['attr']`

**Comment by dzuluaga** [comment]
Makes sense. Thank you.

**Comment by tandalf** [comment]
Is there a way to keep using `raw: true` but in a recursive manner? Instead of the flat object, we get the loaded associations as nested objects.

**Comment by iamjoyce** [comment]
@tandalf 

**Set `nest: true`** - `model.findAll({ raw: true, nest: true })`

Note that, for example, a child has a 1:M relationship with toys, but there are no related records (i.e. no foreign key)

When `raw: false`, the result will be `{ ..., toys: [] }`
When `raw: true`, the result will be `{ ..., toys: { name: null, color: null } }`

**Comment by gavinbelson** [comment]
Is there a way to achieve this type of nested behavior with a raw SQL query?

IE.. sales_person table is joined by the sales table. The sales should be nested into each sales_person.

**Comment by nonybrighto** [comment]
@gavinbelson you can achieve same with raw SQL queries using dotted attributes. Check out the doc link [here](http://docs.sequelizejs.com/manual/raw-queries.html#-quot-dotted-quot--attributes) . In my case, I still had to add the nest property to make it work.  
**ie** 
`models.sequelize.query('select 1 as `foo.bar.baz`', {nest:true})`

**Comment by kervinpierre** [comment]
So basically "raw" is silently, fundamentally broken if your schema has 1:many relationships.

**Comment by weichen35** [comment]
Is anyone from the Sequelize team trying to solve the broken "raw" function?

**Comment by Paroca72** [comment]
I have a relations 1:many and I'm using

```
        const result = await database.query(sqlRows, {
            nest: true,
            raw: false, // Also without not work
            type: database.QueryTypes.SELECT,
        });
```
But the the result is always a flatting object collection.
1:many should be grouped in an array.

Thanks
