### ISSUE TITLE
Associating models without importing files from the filesystem directly

### ISSUE THREAD

**Issue by andrest** [sequelize/sequelize#4974]
Currently /models/index.js does:

```
fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file !== basename);
  })
  .forEach(function(file) {
    var model = sequelize["import"](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});
```

I'm using webpack and this doesn't work when everything is bundled up. Any ideas how to solve this without having have to manually require each module in the index.js file?

**Comment by mickhansen** [comment]
You could use a script to autogenerate a models file, otherwise i don't really see a solution since webpack/browserify requires paths to be available staticly.

**Comment by andrest** [comment]
@mickhansen any ideas how to implement that?

**Comment by mickhansen** [comment]
@andrest do what you do now, iterate over files, write javascript code to a file that statically imports

**Comment by jfletcher2** [comment]
@andrest : Were you able to figure out a solution for this? Please share.

**Comment by felixfbecker** [comment]
You have to require them all in index.js. I actually prefer this over dynamic requires. Just use a glob-cli, glob all your models, copy+paste the list of files into a decent editor and use multiple cursors to wrap the filenames in `require()`.

**Comment by andrest** [comment]
@jfletcher2 we explicitly require all the models in `/models/index.js` and loop over them.

**Comment by jfletcher2** [comment]
Thanks guys. Appreciate your help.

**Comment by trjstewart** [comment]
Apologies for the necro comment. @andrest or @felixfbecker, could you give an example of how you achieved this? My face is currently meeting a wall with this problem.

**Comment by felixfbecker** [comment]
```
require('models/a')
require('models/b')
require('models/c')
...
```

**Comment by andrest** [comment]
@trjstewart we've created a function that takes in a configuration object and returns the initialised models.

`models/index.js`:
```javascript
import Sequelize from 'sequelize';

let models = {};

function getModels (config, force = false) {
  if (Object.keys(models).length && !force) {
    return models;
  }

  const sequelize = new Sequelize(
    config.database,
    config.username,
    config.password,
    config.options
  );

  let modules = [
    require('./address.js'),
    require('./country.js'),
    ...
  ];

  // Initialize models
  modules.forEach((module) => {
    const model = module(sequelize, Sequelize, config);
    models[model.name] = model;
  });

  // Apply associations
  Object.keys(models).forEach((key) => {
    if ('associate' in models[key]) {
      models[key].associate(models);
    }
  });

  models.sequelize = sequelize;
  models.Sequelize = Sequelize;

  return models;
}

module.exports = {
  getModels
};
```

**Comment by trjstewart** [comment]
Thanks @andrest! I am still missing something or being a touch derpy though sorry.

```
// models/log.js
'use strict';

module.exports = (sequelize, DataTypes) => {
  const Log = sequelize.define('Log', {
    id: { type: DataTypes.UUID, primaryKey: true, defaultValue: DataTypes.UUIDV4 },
    level: { type: DataTypes.ENUM('critical', 'urgent', 'error', 'warning', 'general'), required: true },
    message: { type: DataTypes.STRING, required: true, allowNull: false },
    location: { type: DataTypes.STRING },
    body: { type: DataTypes.TEXT },
  }, {
    paranoid: true,
  });

  return Log;
};
```

```
// models/index.js
...
let modules = [
    require('./log.js'),
  ];
...
```

```
// helper/logger.js
'use strict';
import models from '../db/models';

export default (level, message, location = null, body = null) => {
    // Add the log entry to the database.
  models.log.create({ level: level, message: message, body: body, location: location });
};
```

When calling the log function I am getting hit with `Cannot read property 'create' of undefined`. I am assuming this is because I am either importing the model incorrectly or calling it incorrectly?

**Comment by sakhmedbayev** [comment]
@andrest can I see how your individual module files look like (in your example `address.js`)? I am getting following error

```
modules.forEach((module) => {
^
TypeError: module is not a function
```

**Comment by Gerst20051** [comment]
A similar solution to @andrest was posted in this gist. https://gist.github.com/ihavenoidea14/0dab8b461c057c427829fdc99bfb6743

**Comment by jamesjryan** [comment]
I was able to get this working with Typescript 3, Sequelize V4 and Webpack V4 by putting Sequelize as a [node external](https://www.npmjs.com/package/webpack-node-externals) and using dynamic `require` statements like

```
const models: Sequelize.Models = {
  User: require('db/models/user'),
}
```
