### ISSUE TITLE
sequelize table alias issue on postgres

### ISSUE THREAD

**Issue by kidyfirst** [sequelize/sequelize#4977]
when i use sequelize + postgres as follow.
```
var shopInfo = yield ShopPV.findAll({
     where: where
});
```
it throw follow exception, maybe postgres don't support quotes, but the sequelize how to configurate
```
Executing (default): SELECT "statis_date" AS "StatisDate", "pcyd" AS "Source", "fshopid" AS "ShopId", "fshapname" AS "ShopName", "pv" AS "PV", "uv" AS "UV" FROM "bi_jifen_BuyPage_shopinfo_pcyd" AS "bi_jifen_BuyPage_shopinfo_pcyd";
error SequelizeDatabaseError: relation "bi_jifen_BuyPage_shopinfo_pcyd" does not exist
```

**Comment by janmeier** [comment]
Please show your model definition. 

Does the table actually exist? Have you called sync, or is he table already created?

**Comment by kidyfirst** [comment]
sorry, i forget to add the quoteIdentifiers:false on connection. thanks
