### ISSUE TITLE
Updating multiple rows at once

### ISSUE THREAD

**Issue by feniixx** [sequelize/sequelize#4983]
I was reading the docs cause I need to know how to update many rows at once, but while reading [this section](http://docs.sequelizejs.com/en/latest/docs/instances/#working-in-bulk-creating-updating-and-destroying-multiple-rows-at-once) specifically : 
![up](https://cloud.githubusercontent.com/assets/15699775/11600705/30b4f6ea-9a94-11e5-82bf-bb9c5608eef9.PNG)

That doesn't describe how to update many rows at once, in fact it is a common update like 
```sql 
update ... WHERE x=y
```

What I'd like to know is how to update from an array where key = value, for example:

Having retrieved from db
```js
[
    {id: 1, name: 'John'},
    {id: 2, name: 'Sarah'}
]
```

I'd like to kow how could I just change the values to:
```js
[
    {id: 1, name: 'Jonathan'},
    {id: 2, name: 'Sara'}
]
```

and just specifying which one will be the property evaluated to make the `where` clause of the update... Is there such a thing?

**Comment by mickhansen** [comment]
A common update is the only way to do it unless you loop over the instances and do it one by one.

**Comment by feniixx** [comment]
Hmm, ok

**Comment by ziglee** [comment]
How would I loop over the instances using the same transaction?

**Comment by felixfbecker** [comment]
@ziglee StackOverflow or Slack is the more appropriate place to ask these kind of questions, especially since this is more a question about basic JavaScript than Sequelize. Transactions are well documented.

**Comment by ziglee** [comment]
@felixfbecker sorry, I thought that it would require some Sequelize specific function.
