### ISSUE TITLE
Defaultvalues aren't returned from getterMethods

### ISSUE THREAD

**Issue by dzuluaga** [sequelize/sequelize#4984]
Hi all,

I was expecting to get "/accounts" from the getter method, but instead it returns undefined. Am I missing anything? TIA

```javascript
module.exports = function(sequelize, DataTypes) {
  var Account;
  Account = sequelize.define("Account", {
    basePath: {
          type : DataTypes.STRING,
          defaultValue : "/accounts"
    }
  },
    {
      tableName: 'mt_account',
      schema: 'sfdc',
      getterMethods: {
        links : function() { return this.basePath; } // <- Returns undefined instead of "/accounts"
      }
    });
  return Account;
};
```

**Comment by mickhansen** [comment]
defaultValues should be added on build/create, how are you using the instance?

**Comment by dzuluaga** [comment]
I'm trying to use the attribute after findAll(...). So, I thought I could use it to store default values that could be used to generate hypermedia links. Maybe there's a more elegant way to do this. Thanks!

**Comment by mickhansen** [comment]
@dzuluaga Well for findAll the values are provided by the database, so there would be no default values no.

**Comment by dzuluaga** [comment]
That makes sense. Any suggestion on how to set static values on all instances? so that the payload includes an extra attribute. The use case is to generate hypermedia with a basepath with an identifier. The basepath in this case woultld be the static value. The output will look like this:

"link": "https://hostname/accounts/{account_I'd}"

**Comment by mickhansen** [comment]
You could add a `get` method to each invidual attribute that prefixes it's own value, that's what i do for stuff like this.

In this case link appears to be virtual, so you could do something like:

```js
link: {
  type: new DataTypes.VIRTUAL(DataTypes.STRING, ['id']),
  get: function() {
    return basePath + '/' + this.get('id');
  }
}
```

Also gives you the option of changing the static path in the future in case you need to change domain names or whatever.

**Comment by dzuluaga** [comment]
I've just tried it, but it looks like I'm not using it correctly as it's still trying to execute the query against the database, even though the attribute is declared as Virtual. So, I'm getting this error: ```error: column "link" does not exist```

Am I missing anything? Thanks in advance!

Here's the definition of my model:
```javascript
module.exports = function(sequelize, DataTypes) {
  var Account;
  Account = sequelize.define("Account", { },
    {
      freezeTableName: true,
      timestamps: false,
      tableName: 'mt_account',
      schema: 'sfdc',
      link: {
        type: new DataTypes.VIRTUAL(DataTypes.STRING),
        get: function() {
          return 'http://localhost' + '/' + this.get('id');
        },
      },
      classMethods: {
        associate: function (models) {
          Account.hasMany( models.Case, { foreignKey: 'account_id' } );
        }
      },
  Account.listAttributes = ["id", "account_name", "customer_since", "customer_segment", "link" ];
  return Account;
};
```

**Comment by mickhansen** [comment]
Hmm, that happened on older versions, what version of sequelize are you using?

**Comment by mickhansen** [comment]
Oh, you need to define link as an attribute, not as an option: 

``js
var Account;
  Account = sequelize.define("Account", {
    link: {
      type: new DataTypes.VIRTUAL(DataTypes.STRING),
      get: function() {
        return 'http://localhost' + '/' + this.get('id');
      }
    }
  },
  {
  freezeTableName: true,
  timestamps: false,
   tableName: 'mt_account',
  schema: 'sfdc',
  classMethods: {
    associate: function (models) {
      Account.hasMany( models.Case, { foreignKey: 'account_id' } );
    }
  };
  Account.listAttributes = ["id", "account_name", "customer_since", "customer_segment", "link" ];
  return Account;
```js

**Comment by dzuluaga** [comment]
Yeah. I was just posting about it. Thanks a lot!

**Comment by dzuluaga** [comment]
That does the trick! BTW, is there a way to externalize this value? ```return 'http://localhost' + '/accounts/' + this.get('id');``` I guess I can use an external module with static values. If do you have any suggestion, I'd really appreciate it.

**Comment by mickhansen** [comment]
@dzuluaga You can externalize it however you like. Have a config file, a config module, use environment variables.

**Comment by dzuluaga** [comment]
That makes sense. Loving virtual attributes! They open a lot of opportunities to hypermedia APIs. Cheers!

**Comment by mickhansen** [comment]
You're welcome :)
