### ISSUE TITLE
Is it possible to pass an object to model.update?

### ISSUE THREAD

**Issue by ves-krd** [sequelize/sequelize#4985]
Something like the following

    var data = {
      foo: "bar",
      bar: "foo
    };

    models.someModel.update({
      data
    })...

**Comment by mickhansen** [comment]
That's the syntax for model update. What are you doing that's not working?

**Comment by ves-krd** [comment]
Unhandled reqection SequelizeDatabaseError: SQLITE_ERROR: near "WHERE": syntax error

    var data = req.body;
    models.Monitor.update({
        data
    }, {
        where: {
            MonitorID: req.body.MonitorID
        }
    }).then(function (response) {
        console.log(response);
    });

**Comment by mickhansen** [comment]
That syntax is not legal javascript (you have an object in an object with no key), is that actual code from your application?
Never the less that errors means there's an error in the SQL, try taking a look at the generated SQL. (add  `logging: console.log` to the options.

**Comment by ves-krd** [comment]
an object in an object with no key?  req.body is an object...

**Comment by mickhansen** [comment]
Right but you have an object around it:

```js
{
  data
}
```

That is not legal unless you are using ES6 and you want it to expand to `{data: data}`

**Comment by ves-krd** [comment]
So that isn't the syntax for model.update?

**Comment by mickhansen** [comment]
I'm not sure what you are asking? Are you asking if the values object to a model update statement needs a data key? Then no.

Please follow instructions in previous comment by including the SQL.

**Comment by ves-krd** [comment]
var data = {
      foo: "bar",
      bar: "foo
    };

    router.post('/update/:id', function (req,res) {
      var data = req.body;
      models.Monitor.update({
        data
      }, {
        where: {
            ID: req.params.id
        }
      }).then(function (response) {
        console.log(response);
      });
  });

**Comment by mickhansen** [comment]
Are you using ES6? Or is javascript not barfing on that?

```js
models.Monitor.update(data, {
  where: {
        ID: req.params.id
    }
});
```

Pleeasseee include the SQL (add logging: console.log to the options next to where)

**Comment by ves-krd** [comment]
Javascript was not barfing, it was erroring at the WHERE clause, but changing it to your syntax worked.  Thank you

**Comment by mickhansen** [comment]
You must be using babel/es6 then?

**Comment by ves-krd** [comment]
I guess... Not sure.
