### ISSUE TITLE
Occasional foreign key constraint error

### ISSUE THREAD

**Issue by tinganho** [sequelize/sequelize#4987]
My code produces some errors that is very tricky to reproduce. Though I'm not sure if this is sequelize's wrong or Postgres. I got a foreign key constraint error like below:

```
SequelizeForeignKeyConstraintError: insert or update on table "posts" violates foreign key constraint "posts_postImageId_fkey"
```

Though, I have checked and verified that it indeed exists a primary key for the foreign key. I actually, insert the foreign object first and verified it got inserted by just console log the resulting object. And when it is time to insert the main object I got the error above. It happens randomly on my tests. Since, I already verified that my foreign object was inserted before the main object, this error shouldn't occur, but it does 1/3 times.

My clue is that Postgres is delaying the insert somehow. Since, nobody seem to have problem with Postgres, then I must do something unique? The unique thing I'm doing is with the testing. On each test I force sync all tables. The syncing happens in a `beforeEach` hook in Mocha. Directly after syncing of tables I insert my foreign object and then my main object. And it is there 1/3 times the error occur.

I just want to know if you have any clue what is going wrong here? Any help will be very helpful, I have tried to track down this issue for a week now.

**Comment by janmeier** [comment]
Syncing in before each is a very common pattern, used in almost all our integration tests, so that shouldn't give any problems. 

Nothing sounds of from your description here - If you can create a self-contained test case to show the problem it will be a lot easier for us to help you. I do realize that creating a test case for something that only happens one third of the time is not easy though...

**Comment by tinganho** [comment]
@janmeier how do you want me to create a self-contained test? Would be easy if it didn't rely on a DB.

**Comment by janmeier** [comment]
A db connection is okay, since sequelize is not worth much without it ;-) - what I meant was some code which contains all the model, associations and test data to replicate the issue

**Comment by janmeier** [comment]
No response, closing

**Comment by tinganho** [comment]
This error is still a problem for me. Though I don't think I have time to create a whole project just to verify this bug. Though I'm pretty sure that the force sync promise is resolved to early. Try to create a project with many tables (30+) and some of the table having many relations(3+). Directly after each force sync try to query one of the tables with `include`. And you can see that it errors.

My `beforeEach` just contains a single line of:
```ts
beforeEach((done) => {
    await DbContext.sync({ force: true });
    done();
});
```
And after that I query different tables. And I have tried to inspect the database on failures and I can see that not all tables have been created.

Original post is complaining about constraint issues. Though it is related.

It seems like this bug have increased with increased number of tables for me.

Also if I put a sleep after for sync. The bug never appears. 
```ts
beforeEach((done) => {
    await DbContext.sync({ force: true });
    setTimeout(done, 3000);
});

Though, I don't want to use the above trick. Since it is not the most effective.

I hope this info can help you narrow down the problem.
```

**Comment by SystemDisc** [comment]
This is happening to me, too. My error is ```Unhandled rejection SequelizeBaseError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`lyricszone`.`songs`, CONSTRAINT `songs_ibfk_2` FOREIGN KEY (`albumId`) REFERENCES `albums` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)```.

It seems that running an insert into the first table and then running an insert into the second table immediately afterward, where the second table has a foreign key constraint on the first table, **sometimes** fails. This would imply that the `upsert` promise resolves before the data is *definitely* available in the first table.

Example first query:
```sql
INSERT INTO `albums` (`id`,`name`,`slug`,`sourceUri`,`year`,`artistId`,`createdAt`,`updatedAt`) VALUES (44015,'Eaten Back To Life','eaten-back-to-life','/albums/44015',1990,41863,'2017-05-21 10:00:49','2017-05-21 10:00:49') ON DUPLICATE KEY UPDATE `id`=VALUES(`id`), `name`=VALUES(`name`), `slug`=VALUES(`slug`), `sourceUri`=VALUES(`sourceUri`), `year`=VALUES(`year`), `artistId`=VALUES(`artistId`), `updatedAt`=VALUES(`updatedAt`);
```

Example second query that fails:
```sql
INSERT INTO `songs` (`id`,`name`,`slug`,`sourceUri`,`lyrics`,`position`,`artistId`,`albumId`,`createdAt`,`updatedAt`) VALUES (213092,'Born In A Casket','born-in-a-casket','/songs/213092','<p>Enter the crypts of hell, to impregnate the dead<br>\nFresh burial sight, my hunger grows tonight<br>\nUndying lust for cadaverous molestation<br>\nSights of death building my sensations<br>\nFerocious need for decomposing bodies<br>\n<br>\nSex with the dead now I must breed<br>\nWithin the stiff corpse planting my seed<br>\nThe taste of formaldehyde, smell of the rot<br>\nSuck out the goo, feast on her crotch<br>\n<br>\nRaging fires of hell, burning through my soul<br>\nMy love for a dead fuck, I cannot control<br>\nThe child soon will rise, all evil will survive<br>\nBirth through death<br>\n<br>\nThe newborn needs a feast, its mother is the meal<br>\nChomping on her flesh, his teeth tearing her skin<br>\nI love to fuck the dead, demons in my head<br>\nTearing at my brain<br>\n<br>\nBleeding sores beginning to stench<br>\nWhile you lick the festering stump<br>\nGreen infection discharging pus<br>\nDevour the putrid afterbirth<br>\n<br>\nSex with the dead now I must breed<br>\nWithin the stiff corpse planting my seed<br>\nThe taste of formaldehyde, smell of the rot<br>\nSuck out the goo, feast on her crotch</p>\n\n',6,41863,44015,'2017-05-21 10:00:48','2017-05-21 10:00:48') ON DUPLICATE KEY UPDATE `id`=VALUES(`id`), `name`=VALUES(`name`), `slug`=VALUES(`slug`), `sourceUri`=VALUES(`sourceUri`), `lyrics`=VALUES(`lyrics`), `position`=VALUES(`position`), `artistId`=VALUES(`artistId`), `albumId`=VALUES(`albumId`), `updatedAt`=VALUES(`updatedAt`);
```

Code excerpt:
```javascript
Promise.resolve().then(() => {
  if (song.album && !savedAlbums[song.album.id]) {
    savedAlbums[song.album.id] = true; // I don't want to run upsert multiple times for the same data
    return Promise.resolve().then(() => {
      return genius.getAlbum(song.album.id);
    }).then((album) => {
      console.log('add album:', album.name);
      return Album.upsert({
        id: album.id,
        artistId: artist.id,
        name: album.name,
        slug: album.name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/^-+|-+$|(-)-+/g, (str, p1) => p1? p1:''),
        sourceUri: album.api_path,
        year: album.release_date? +album.release_date.replace(/^([0-9]+)-.*$/, (str, p1) => p1):null,
      }).delay(1000);
    });
  }
}).then(() => {
  return genius.getLyrics(song.path);
}).then((lyrics) => {
  return genius.getTrack(song.path).then((track) => {
    console.log('Artist:', artist.name, 'Song:', song.title);
    return Song.upsert({
      id: song.id,
      artistId: artist.id,
      albumId: song.album && song.album.id? song.album.id:null,
      name: song.title,
      slug: song.title.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/^-+|-+$|(-)-+/g, (str, p1) => p1? p1:''),
      sourceUri: song.api_path,
      lyrics,
      position: track,
    });
  });
});
```

**Comment by Maardje** [comment]
@tinganho Have you figured it out yet?

**Comment by sw-yx** [comment]
woudl like to know too!

**Comment by Laurensdc** [comment]
Same problem. I have an admin route that wipes all data and seeds it, and the ForeignKeyConstraintError will throw about half the time. Other times it just works. 

Can't deliberately throw it, and the workaround is to just force sync and re-seed one or two more times.

**Comment by sw-yx** [comment]
dunno if this is stating the obvious but i think this is some sort of race condition due to asynchronous execution of the seeding or testing. specifically a foreign key constraint error usually happens when you are trying to create an entry that has already been created.

every time i have run into this issue  (and it is not fun) i have basically broken through by scrapping what i was doing and rewriting from scratch in smaller files and then the error goes away. small reproducible chunks.

so what we really need (if the sequelize team cares about user mental health) is best practices around sequential testing/seeding of things.

**Comment by Laurensdc** [comment]
@sw-yx Yeah just figured out what happened in my case as well, and it's quite annoying that I can't properly get it coded.

I'm putting my seeds in different files, passing them with module.exports.
The seeds are Promises (e.g. BulkCreate).

Now first I was wrapping them in a function, and I just synchronously called those functions. So yeah, I was just hoping that the execution order would turn out right.

Now the problem is that requiring the files that export a single Promise, execute those promises immediately.

Right now I got something like this
``` js
// Independent seeds first
        let promises = [
            require('./user'),
            require('./bcomponent'),
            require('./material'),
            require('./defect'),
        ];

        Promise.all(promises).then(() => {
            // First layer dependency
            return Promise.all([
                require('./project'),
                require('./materialDefect'),
                require('./bcomponentMaterial')
            ]);
        }).then(() => {
            // Second layer dependency
            return require('./projectMaterial');
        }).then(() => {
            // Third layer dependency
            return require('./projectMaterialComment');
        }).then(() => {
            console.log('*** success ***');
        }).catch(error => {
            console.log(error);
        });
```

Which works, but NodeJS caches the requires, so I have to restart the server to do a new seed. Quite annoying.

And if I require those modules properly at the top, the Promises get executed immediately when the server starts. Also annoying.

So yeah, some best practices regarding seeding would definitely be welcome.

**Comment by Laurensdc** [comment]
I've found a better way to fix it!
I pass functions now that return a Promise (First project where I'm using Promises for me, so maybe this might be basics for other people) and then I can catch potential errors higher up, just the way I wanted it.

`Resetting DB and seeding`

``` js
const Seeds = require('../seeds/index');

sequelize.sync({ force: true }).then(() => {
    return Seeds.seed();
}).then(() => {
    // DB reset
}).catch(err => {
    // Error in one of the seeds, specific error in 'err'
});
```

`seeds/index.js` - Example of using seed in another file

``` js
const UserSeed = require('./user');
const BComponentSeed = require('./bcomponent');
const MaterialSeed = require('./material');

module.exports = {
    seed: function() {
        return Promise.all([
            // Independent seeds first
            UserSeed(),
            BComponentSeed(),
            MaterialSeed(),
        ]).then(() => {
            console.log('********** Successfully seeded db **********');
        });
    }
}
```

`seeds/user.js` - User seed

``` js
const User = require('../models/user');
const crypto = require('../globs/crypto');

let seed = function() {
    return User.bulkCreate([
        {
            email: 'John@doe.com',
            password: crypto.generateHash('john'),
        },
        {
            email: 'a@a.com',
            password: crypto.generateHash('a'),
        },
    ]);
};

module.exports = seed;
```
