### ISSUE TITLE
Can't limit joined rows (n:m associations)

### ISSUE THREAD

**Issue by nikolaykletskin** [sequelize/sequelize#4988]
There are two models defined by Sequelize: Post and Tag with many-to-many association.

    Post.belongsToMany(db.Tag, {through: 'post_tag', foreignKey: 'post_id', timestamps: false});
    Tag.belongsToMany(db.Post, {through: 'post_tag', foreignKey: 'tag_id',timestamps: false});

On a "tag" page I want to get tag data, associated posts and show them with pagination. So I should limit posts. But If I try limit them inside "include"

    Tag.findOne({
        where: {url: req.params.url},
        include: [{
            model : Post,
            limit: 10
        }]
    }).then(function(tag) {
        //handling results
    });

I get following error:

    Unhandled rejection Error: Only HasMany associations support include.separate

If I try to switch to "HasMany" associations I get following error

    Error: N:M associations are not supported with hasMany. Use belongsToMany instead

Looks like full circle: documentation says that limit "only supported with include.separate=true", include "only supported for hasMany associations", but i can't use "hasMany" for many-to-many associantion.

Is there a way to limit n:m associations?

**Comment by mickhansen** [comment]
`separate` is not supported for belongsToMany, there's an existing issue for it that you can track.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/4376
