### ISSUE TITLE
Find elements with associations and only return the elements without including the reference to their associations

### ISSUE THREAD

**Issue by dcodus** [sequelize/sequelize#4993]
```js
Entry.findAll({
        include: [{
            model: AddressBook,
            where: {id: 1}
            include: [{
                model: Account,
                where: {
                    id: req.accountId
                }
            }]
        }],
        limit: req.query.limit,
        offset: req.query.offset,
        order: req.query.order
    }).then(function(result[0].entry) {
        res.json(result);
    }, function(err) {
        res.json(err);
    })
```

As you can see from this code, i am search for an entry that belongs to a specific address book that itself belongs to a specific account. I would like to be able to send back only the found entry without the address book and account. The code as it is returns the found entry plus the address book and the account. 

```json
[
  {
    "id": 806,
    "firstName": "Super",
    "lastName": "Man",
    "birthday": "1900-10-10T00:00:00.000Z",
    "createdAt": "2015-12-04T05:08:20.000Z",
    "updatedAt": "2015-12-04T05:46:06.000Z",
    "addressbookId": 30,
    "AddressBook": {
      "id": 30,
      "name": "Cool!",
      "createdAt": "2015-12-04T04:17:17.000Z",
      "updatedAt": "2015-12-04T04:18:02.000Z",
      "accountId": 19,
      "Account": {
        "id": 19,
        "email": "hello@test.com",
        "password": "$2a$10$Tk3QjBCTdK55Up/cmsVwL.ufSm1Yx77PkR0pUsTm1hoRFFUsJYHeG",
        "createdAt": "2015-12-03T21:51:36.000Z",
        "updatedAt": "2015-12-03T22:18:57.000Z"
      }
    }
  }
]
```
I'm running the following code
```js
 var onlyEntry = result.get({plain: true});
 delete onlyEntry.AddressBook;
 return onlyEntry;
```
It gives the following result
```json
 {
    "id": 806,
    "firstName": "Super",
    "lastName": "Man",
    "birthday": "1900-10-10T00:00:00.000Z",
    "createdAt": "2015-12-04T05:08:20.000Z",
    "updatedAt": "2015-12-04T05:46:06.000Z",
    "addressbookId": 30
}
```
How do i achieve this without manually deleting the reference to addresbook. Thank you!

**Comment by steveschmitt** [comment]
Maybe you could use `.attributes` on the `.include` to reduce the fields:

        include: [{
            model: AddressBook,
            where: {id: 1},
            attributes: ['id'],
            include: [{
                model: Account,
                attributes: ['id`],
                where: {
                    id: req.accountId
                }
            }]
        }],

I don't know what happens if you use an empty attributes array.

**Comment by steveschmitt** [comment]
Yes, it worked for me - put an empty attributes array in each include, and it won't return the child objects at all:

    include: [{
        model: AddressBook,
        where: {id: 1},
        attributes: [],
        include: [{
            model: Account,
            attributes: [],
            where: {
                id: req.accountId
            }
        }]
    }],

**Comment by mickhansen** [comment]
Using an empty attributes array is the way to go.

**Comment by dcodus** [comment]
This fixed the issue! Much appreciated!
