### ISSUE TITLE
Ability to retrieve SQL generated and append it to JSON response

### ISSUE THREAD

**Issue by dzuluaga** [sequelize/sequelize#4994]
Is there a way to retrieve the SQL statement generated by a sequelize method? So, that it can be appended to the response. The use case for this is for troubleshooting of a production system with RAW SQL statements. I found [this response](http://stackoverflow.com/questions/21427501/how-can-i-see-the-sql-generated-by-sequelize-js) on SO, but it doesn't necessarily help me to solve my use case.

So for instance, I'm able to do something like this, but you can see it includes in the reponse additional string, plus it doesn't seem to elegant. Any suggestions? Thanks!
```
  var sql;
  models.Contact.findOne({
        where: where,
        attributes: utils.tryToParseJSON(req.query.attributes, messages.PARSE_ERROR_ATTRIBUTE_PARAM, models.Contact.listAttributes),
        offset: req.query.offset || 0,
        limit: Math.min( req.query.limit || 100, 100 ),
        order: req.query.order || [],
        include: utils.getIncludes( req.query.include ),
        logging: function( str ){ sql = str; }
      })
      .then(function( contact ) {
        //console.log( contact )
        contact.dataValues.sql = sql;
        res.json( contact );
      })
      .catch( function( error ){
        res.send( error );
      }) ;
});
```json
Response:
```
{
  "links": [
    {
      "rel": [
        "self"
      ],
      "href": "http://localhost:3000/contacts/0037000000XPCqM"
    }
  ],
  "id": "0037000000XPCqM",
  "sql": "Executing (default): SELECT \"id\" FROM \"sfdc\".\"mt_contact\" AS \"Contact\" WHERE \"Contact\".\"id\" = '0037000000XPCqM' LIMIT 100;"
}
```

**Comment by mickhansen** [comment]
That's the only way to do it currently.
A little bit more elegant would be to serialize the values first by using `contact.toJSON()` and then appending the SQL afterwards.

**Comment by dzuluaga** [comment]
Makes sense. Thanks!
