### ISSUE TITLE
Duplicated entries

### ISSUE THREAD

**Issue by feniixx** [sequelize/sequelize#4995]
I'm getting duplicated/triplicated/x-cated entries when inserting, here's my code:

```js
models.clients_and_suppliers.create( request.body.supplier_or_client )
    .then( function ( client_or_supplier ) {
        
        if ( request.body.supplier_or_client.isSupplier ) {
            
            request.body.contacts.forEach( function ( contact ) {
                contact.supplier = client_or_supplier.id
            } );
            
            request.body.vat_register.client_supplier = client_or_supplier.id;
            request.body.address.supplier             = client_or_supplier.id;
            request.body.nit.client_supplier          = client_or_supplier.id;
            
            var vat      = models.vat_registers.create( request.body.vat_register ),
                addr     = models.addresses.create( request.body.address ),
                nits     = models.nits.create( request.body.nit ),
                contacts = models.contacts.bulkCreate( request.body.contacts );
            
            Promise.all( [ vat, addr, nits, contacts ] )
                .then( function ( data ) {
                    response.json( data )
                } )
            
        }
        
    } );
```

When I go and check db table I notice that rows are duplicated:
![capture](https://cloud.githubusercontent.com/assets/15699775/11651869/d6743ae2-9d59-11e5-8363-e87ece56ae8a.PNG)

**Comment by mickhansen** [comment]
I'm not sure i understand the issue? Sequelize doesn't inheritely do anything against duplicate records, you either need to have unique constraints or use findOrCreate.

**Comment by feniixx** [comment]
No, when inserting I'm getting duplicated entries, like  ZII, is inserted two times

**Comment by mickhansen** [comment]
And which line of code corresponds to ZII?
Have you attempted to look at the SQL log generated?

**Comment by feniixx** [comment]
check out the image of the table content, there you can see ZII is duplicated, as is Valdes; the SQL Log generated only logs one insert...

**Comment by mickhansen** [comment]
Yes i see that, but i have no idea what model that table corresponds to.
If there is only one insert statement the duplication is not from Sequelize.

You must either have existing entries or some other code is running. Very unlikely that this is a Sequelize issue at all.

**Comment by mickhansen** [comment]
You'll note that the createdAt timestamps are several seconds apart, doubtfull that it's from the same block of code then.
