### ISSUE TITLE
MySQL UUIDs stored as CHAR(36)

### ISSUE THREAD

**Issue by nimish** [sequelize/sequelize#4997]
UUIDs are 128 bit integers, which means they should fit into BINARY(16), but sequelize generates CHAR(36) strings instead-- a rather huge increase in size.

Is there a way to get binary(16) support in?

**Comment by nathanmarks** [comment]
For reference:

http://iops.io/blog/storing-billions-uuid-fields-mysql-innodb/
http://mysql.rjweb.org/doc.php/uuid

**Comment by mickhansen** [comment]
Assuming this is not a breaking change it shouldn't be too tricky to change: https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/data-types.js#L45

**Comment by rafaelalmeidatk** [comment]
I began working on this issue and the database is already using the `BINARY(16)` format, but it shows the binary format to the user. How can I apply a function to the field before returning it?

**Comment by Rudedog9d** [comment]
@rafaelalmeidatk Could you leverage `BIN_TO_UUID` to convert the bytes to UUID?

Check out this article for more: https://mysqlserverteam.com/mysql-8-0-uuid-support/

**Comment by bradennapier** [comment]
@Rudedog9d see that #10290 already implements that natively without the need.  In addition you can utilize it without the need for MySQL / MySQL 8 by utilizing the libraries i built for them:

https://github.com/odo-network/sequelize-binary-uuid

https://github.com/odo-network/binary-uuid

which implement an identical effect.

**Comment by omidkrad** [comment]
@bradennapier thanks, this is great. I wished I could use [sequelize-binary-uuid](https://github.com/odo-network/sequelize-binary-uuid) with [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript). If this gets added to sequelize, there's a good chance that they also add it to typescript-sequelize.

**Comment by bradennapier** [comment]
@omidkrad well the good news is my company is switching to 100% typescript so... I’d imagine it will be supported soon :)

**Comment by spencerwasden** [comment]
@bradennapier 
> @omidkrad well the good news is my company is switching to 100% typescript so... I’d imagine it will be supported soon :)
> 
> They just decided to wait to see if there’s enough demand for binary uuid in this way so make sure you indicate your support for it officially as well :)

Any developments on using this with sequelize-typescript?

**Comment by bradennapier** [comment]
> @spencerwasden 
> Any developments on using this with sequelize-typescript?

It shouldn't be difficult to use the package with sequelize-typescript - you'd need to make the typings for now but it would be relatively straight forward/simple.  

Actually it couldn't have been 100% typed until the recent 4.1 launch which would allow adding custom-named keys to the types but I am not sure my bandwidth would have me updating that any time soon...

Ideally sequelize would add this for official support :-P
