### ISSUE TITLE
question regarding the postgreSQL timezones

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#5002]
Hi,

Open question regarding the postgresql timezones.

Here is the code:
```javascript
let Data = server.storage.getModel('Data');

            console.log(moment().format('YYYY-MM-DD HH:mm:ss'));
            console.log(moment().toDate());

            Data.create({
                metric_id: 1,
                client: 'HELLO',
                created_at: moment().subtract(1,'days').format('YYYY-MM-DD HH:mm:ss'),
                updated_at: moment().format('YYYY-MM-DD HH:mm:ss')
            });
```

Here is what I see in the console:
![image](https://cloud.githubusercontent.com/assets/839290/11662852/44a0d0c8-9dd9-11e5-9aee-316129fd51cb.png)

I'm curious - why the INSERT query has dates in UTC, and which effect it can take on me? Whenever I do a query using 0xDBE, for example, I see the correct timestamps (the timezone is updated, however).
![image](https://cloud.githubusercontent.com/assets/839290/11663142/d03daaba-9dda-11e5-8acc-9b170de7d009.png)

If I'll adjust my connection and set +01:00 timezone, then the INSERT query would show the "correct" dates in the console as well. However in the documentation it's stated, that ```timezone``` is used for the different thing.
> The timezone used when converting a date from the database into a JavaScript date. 

Could you, please, tell me, if I should consider this as important or not? Would I met this some unexpected behaviours if I don't understand how it's working? Should I state the timezone in the options or I can skip it? (the only difference which I found, was the console log of the INSERT query).

Currently:
```sql
SELECT  current_setting('TIMEZONE')
```

returns **Europe/Berlin**.

Any thoughts are welcome.

Regards,

**Comment by janmeier** [comment]
Timezone does not have much affect in postgres, since the actual offset is saved together with the data - so no matter what timezone you use, the output will be correct. In the case of pg, timezone controls which timezone inserted data has (as you've seen). It also controls the timezone for `NOW()` and friends.

In other dialects, which don't store timezone info in the DB, the timezone is also used when parsing the dwata

**Comment by PavelPolyakov** [comment]
@janmeier 

Thanks, it explains the situation and makes me feel safe.

However, from the PostgreSQL it's a bit unclear still.
Imagine I did the next:
```sql
SET TIME ZONE 'America/Resolute';
insert into users values(default,'USER','1','2','3',NOW(),NOW());
```

Which gives us the next:
![image](https://cloud.githubusercontent.com/assets/839290/11666132/2d5df58c-9deb-11e5-81dc-a85ddf2fb1a5.png)

Then I change my timezone and query the database again:
```sql
SET TIME ZONE 'Europe/Berlin';
select * from users where id=16
```

Which returns:
![image](https://cloud.githubusercontent.com/assets/839290/11666169/6057bed2-9deb-11e5-888c-d4b483272b8b.png)

Same time still...however the timezone was changed.

It has nothing with sequelize, of course, but would help me to understand the timezones issue.

Regards,

**Comment by mickhansen** [comment]
@PavelPolyakov Are those timestamptz fields? They usually have an offset on the value (not sure if your client removes it in the display though)

**Comment by PavelPolyakov** [comment]
@mickhansen 
The field type is:
```
created_at timestamp with time zone default now()
```

So you mean, that, in theory, I should receive something like the next in the output
*2015-12-08 20:34:32.180858 +01:00* ? However, the 0xDBE drops the timezone part?

In the console, I ,really, do see the next:
![image](https://cloud.githubusercontent.com/assets/839290/11682675/a336c72c-9e66-11e5-9164-5f64a0b8dae2.png)
![image](https://cloud.githubusercontent.com/assets/839290/11682768/3c1eff7c-9e67-11e5-9ea7-b26d3208ab5e.png)

Ok, so what conclusion I can do - any date which you save to the PostgreSQL with the timezone, is safe, and, you will receive the expected result in the current timezone each time you do query (whenever the timezone which you have used to save the data to the database).

Thanks for the help.

Regards,

**Comment by janmeier** [comment]
You're welcome :)

**Comment by webmobiles** [comment]
@PavelPolyakov  what type of data you use in sequelize for your time with timezone?

**Comment by PavelPolyakov** [comment]
@webmobiles 
I do not remember, but probably it was `timestamp`.

**Comment by webmobiles** [comment]
I use datetime, and it's working well, just to convert i use  js:

value.toLocaleDateString() +' '+ value.toLocaleTimeString()
