### ISSUE TITLE
setDataValue sets attribute as changed when updated from null to null

### ISSUE THREAD

**Issue by Thomathan** [sequelize/sequelize#5004]
Related to https://github.com/sequelize/sequelize/issues/3812

The setDataValue will set an attribute as changed when changing from null to null. 

It could be argued that I should have that check in my own code but the instance code does check for changes anyways.

```
Instance.prototype.setDataValue = function(key, value) {
  var originalValue = this._previousDataValues[key];
  if (!Utils.isPrimitive(value) || value !== originalValue) {
    this.changed(key, true);
  }

  this.dataValues[key] = value;
};
```

This differs from the set function which does

```
if (!options.raw && ((!Utils.isPrimitive(value) && value !== null) || value !== originalValue)) {
  this._previousDataValues[key] = originalValue;
  this.changed(key, true);
}
this.dataValues[key] = value;
```

**Comment by mickhansen** [comment]
`setDataValue` is meant more as a low level thing, it definitely doesn't have as much logic. Odd that null doesnt register as a primitive though.

**Comment by Thomathan** [comment]
null's have always been odd. It just seems like the setDataValue check should use the conditions as the set check (minus the raw of course). In it's current state, they give inconsistent behaviour.

**Comment by Kirill89** [comment]
Looks like this bug wasn't fixed.
It is currently an important issue for me.

Could you help me to fix this?
For which cases we need `isPrimitive` check?
According to me we can just remove first part of check - `!Utils.isPrimitive(value) || `. Am I right?

**Comment by Kirill89** [comment]
Guys, please take a look at the pull request. We really suffer about this bug.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/9347
