### ISSUE TITLE
SQLite migrations lose foreign keys on any column change

### ISSUE THREAD

**Issue by jocull** [sequelize/sequelize#5007]
I have a migration that iteratively walks through a series of columns, renaming them. However, I found that if I run a series of remove/create column calls, only the last one in keeps its foreign key constraint.

I believe it has to do with Sequelize's way of moving data into a backup table, performing changes, and then moving it back.

I'm not sure if this is a problem in other dialects.

**Comment by mickhansen** [comment]
Likely not a problem with other dialects since they have actual schema change capabilities.
SQLite does not allow schema changes, the only way to do it is to backup, new table, transfer data.
Looks like there's a bug with the new table creation.

**Comment by jocull** [comment]
I was able to work around it by calling `describeTable`, manipulating the
description to be what I need the final table to be, dropping the source
table, and creating it from scratch with `createTable`

Not something I'd want to do in production of course, but then again I
won't be using SQLite in production :)

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/7078
