### ISSUE TITLE
Can I place queries inside Sequelize Models?

### ISSUE THREAD

**Issue by notHyland** [sequelize/sequelize#5012]
Hello, first off, just wanted to say that I'm new to NodeJS/ExpressJS/SequelizeJS/PostgreSQL. I come from the typical PHP/MySQL/Apache app stack world, and the CI framework. But I love it thus far! Im on my first "real" project. Im creating a NodeJS/ExpressJS/SequelizeJS plugin for the Server-Side feature in DataTables. Using Sequelize, and making it as generic as I can, hopefully it will be able to support any database type that SequelizeJS can support, as opposed to just PostgreSQL, which is what I'm using.

So, to my question. I was following along with this article, so I created the ./models/ directory, and the ./models/index.js file to import the models in the directory, and it all seems to be working thus far. What I was wondering is, where is the best place to put the queries for the models? Im use to the CodeIgniter, which is an MVC framework, where all the queries are inside the models, and all you do is call the model methods, and they return the object or array. I guess I'm trying to reach a similar result using SequelizeJS. 

If I create a ./models/SSP.js file with the below content:
```javascript
"use strict";

// The config.ssp object contains all of the associations for
// the  DataTable column indexes to the DB Column names
const SSPCONFIG  = require('../config').ssp;

module.exports = function (sequelize, DataTypes) {
    var sspColumns = {};

    // Construct the Sequelize columns object from the config.db.columns
    SSPCONFIG.columns.forEach( function (element, index, arr) {
        sspColumns[ `dtCol_${arr[index].dt}` ] = {
            type: DataTypes.STRING,
            field: arr[index].db
        };
    });

    return sequelize.define( SSPCONFIG.table, sspColumns, {
        instanceMethods: {
            // Should the queries for the SSPCONFIG.table be in here?
        }
    });
}
```
And I want to create a method that executes a simple query, such as: 
```javascript
SSP.findAll({ where: { dtCol_1: 'Cox' } });
```
Wheres the best place to put it? I was thinking putting it inside the `instanceMethods` would be a good idea, but I couldn't find how to execute queries for the current model, I found plenty of docs on how to return queries for either other models, or based on associations, but not for the same model. I tried simply `return this.findAll();`, but that didn't work..

I know this seems like a basic question, and it is, I'm just not too experienced yet, and all of the tutorials I found online just showed how to execute queries inside the main file, but not inside the model files themselves. So maybe its not even possible?

Thanks!

**Comment by mickhansen** [comment]
I've answered you on google groups
