### ISSUE TITLE
Syntax error on sequelize.define()

### ISSUE THREAD

**Issue by AlexNasonov** [sequelize/sequelize#5015]
I have a simple setup for Sequelize.
```javascript
var config = require('../config'),
    Sequelize = require('sequelize'),
    sequelize = new Sequelize(
        config.get('database'),
        config.get('username'),
        config.get('password'), {
            host: config.get('host'),
            port: config.get('dbport'),
            dialect: config.get('dialect'),
            pool: {
                max: 5,
                min: 0,
                idle: 10000
            }
        })
```
If i run an ordinary check `sequelize.authenticate()` it works fine and shows that there are no problems with connection. But if i try to define any model, `sequelize.sync();` throws an error: `Unhandled rejection SequelizeDatabaseError: syntax error at or near "NOT"`. It seems to me that there is a problem within sequelize or a driver. 
BTW I use PostgreSQL 9.0.13
Package dependencies are:
*  "pg": "^4.4.3",
* "pg-hstore": "^2.3.2",
* "sequelize": "^3.14.2",

**Comment by janmeier** [comment]
Postgres 9.0 does not support `CREATE TABLE IF NOT EXISTS`

http://www.postgresql.org/docs/9.0/static/sql-createtable.html

You could add a check for pg version here 
https://github.com/sequelize/sequelize/blob/3ec4f6e7ab1342cab1739c67ab16d4c7f66ddb6f/lib/dialects/postgres/query-generator.js#L45, see https://github.com/sequelize/sequelize/blob/3ec4f6e7ab1342cab1739c67ab16d4c7f66ddb6f/lib/dialects/abstract/query-generator.js#L259 for an example of how to do that
