### ISSUE TITLE
Document inconsistency in 'Working with table schemas'

### ISSUE THREAD

**Issue by sainttail** [sequelize/sequelize#5028]
This page maybe in development, if that the case sorry about this.

Based on the probrem on #4899 

If one wants to create composite unique key have to use raw query for now.

But I saw in the document this [page](http://docs.sequelizejs.com/en/latest/docs/schema/) 

there has some method called `addConstraint`, `removeConstraint`

So maybe we can use that instead of using raw query. But currently `QueryInterface` object doesn't have both of these methods while have other methods on that page

**Comment by rianby64** [comment]
These two methods ```addConstraint```, ```removeConstraint``` are not present when doing migration.
```javascript
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    console.log(queryInterface.constructor.prototype.addConstraint);  // undefined, expected [Function]
    console.log(queryInterface.constructor.prototype.removeConstraint);  // undefined, expected [Function]
    return queryInterface.addConstraint();
  },
  down: function (queryInterface, Sequelize) {
    return queryInterface.removeConstraint();
  }
}

**Comment by rianby64** [comment]
cc @janmeier, @mickhansen

**Comment by janmeier** [comment]
Will be in v4 final, hopefully release next week
