### ISSUE TITLE
Cannot re-define a new message for unique attribute.

### ISSUE THREAD

**Issue by HassanAlthaf** [sequelize/sequelize#5033]
```js
module.exports = function (sequelize, DataTypes) {
    var users = sequelize.define('users', {
        full_name: {
            type: DataTypes.STRING,
            allowNull: false,
            validate: {
                len: {
                    args: [5, 50],
                    msg: 'Your full name may be 5 to 50 characters only.'
                }
            }
        },
        email: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: {
                msg: 'This email is already taken.'
            },
            validate: {
                isEmail: {
                    msg: 'Email address must be valid.'
                }
            }
        },
        username: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: {
                msg: 'This username is already taken.'
            },
            validate: {
                len: {
                    args: [5, 50],
                    msg: 'Your username may be 5 to 50 characters only.'
                }
            }
        },
        password: {
            type: DataTypes.STRING,
            allowNull: false,
            validate: {
                len: {
                    args: [5, 72],
                    msg: 'Your password may be 5 to 72 characters only.'
                }
            }
        },
        rank: {
            type: DataTypes.INTEGER,
            allowNull: false,
            validate: {
                isInt: true
            }
        }
    }, {
        hooks: {
            beforeValidate: function (user, options) {
                if (typeof user.email === 'string') {
                    user.email = user.email.toLowerCase();
                }

                if (typeof user.username === 'string') {
                    user.username = user.username.toLowerCase();
                }
            }
        }
    });

    return users;
};
```
As you can see, the `email` and `username` fields have two different messages set for `unique` attribute. However, whenever I enter a new email but an already existing username, I get this error:

```json
{
  "name": "SequelizeUniqueConstraintError",
  "message": "Validation error",
  "errors": [
    {
      "message": "This email is already taken.",
      "type": "unique violation",
      "path": "username",
      "value": "hassan"
    }
  ],
  "fields": {
    "username": "hassan"
  }
}
```

So as you can see, it says it is the username that is not unique, but uses the message defined for the email property.

**Comment by HassanAlthaf** [comment]
@mickhansen @sdepold @janmeier @durango Could this particular issue be a bug?

**Comment by mickhansen** [comment]
I haven't had time to look at it, but i'm not sure we actually support that way of defining uniques.
Are the indexes created by sequelize? If so could you post the create table statement?

**Comment by HassanAlthaf** [comment]
@mickhansen Yes, the indexes are created by Sequelize. How do I get you a create table statement?

**Comment by mickhansen** [comment]
You can add `logging: console.log` to sync()

**Comment by HassanAlthaf** [comment]
```sql
CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `full_name` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL, `username` VARCHAR(255) NOT NULL, `password_hash` VARCHAR(255), `rank` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, UNIQUE `undefined` (`email`, `username`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
Executing (default): INSERT INTO `users` (`id`,`full_name`,`email`,`username`,`password_hash`,`rank`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'Hassan','lol@lol.com','hassan','$2a$10$O34fCiG4MXwzZXO6XzvAEuQRDjeNmw9p9tsllf8bAkVkQeSOX1afC',0,'2015-12-15 11:16:16','2015-12-15 11:16:16');
```

**Comment by mickhansen** [comment]
As you see it's creating a composite unique index, which is not the intention here i imagine, as i suspected the syntax you're using is not actually supported.

**Comment by mickhansen** [comment]
Try it like this instead:

```js
email: {
  type: DataTypes.STRING,
  allowNull: false,
  unique: {
    msg: 'This email is already taken.',
    fields: ['email']
  }
},
username: {
  type: DataTypes.STRING,
  allowNull: false,
  unique: {
    msg: 'This username is already taken.',
    fields: ['username']
  }
}
```

**Comment by HassanAlthaf** [comment]
@mickhansen That didn't seem to work. :/

**Comment by mickhansen** [comment]
What happens?
Your initial code should work, but looks like there's a bug.

**Comment by HassanAlthaf** [comment]
@mickhansen Same thing as what happened to me previously.

```sql
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `full_name` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL, `username` VARCHAR(255) NOT NULL, `password_hash` VARCHAR(255), `rank` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, UNIQUE `undefined` (`email`, `username`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
```

**Comment by HassanAlthaf** [comment]
Sorry about that, clicked the wrong button.

**Comment by HassanAlthaf** [comment]
@mickhansen So, is this a bug or what?

**Comment by mickhansen** [comment]
Seems like it, but very odd, we should have tests for a case like that, maybe something is slightly off in your unique definitions, i'm not sure.

Can you try adding `args: true` alongside `msg` and `fields` for your unique definition?

**Comment by HassanAlthaf** [comment]
@mickhansen I gave up on that completely. Now I am stuck with this stupid allowNull: {} check. In that, I can't specify a message. :/ It gives an ugly message. If I disable it, other validations don't work. Any fix for that?
```js
full_name: {
            type: DataTypes.STRING,
            allowNull: {
                args: false,
                msg: 'The full name field cannot be empty!'
            },
            validate: {
                notNull: {
                    args: true,
                    msg: 'Your full name field cannot be empty.'
                },
                len: {
                    args: [5, 50],
                    msg: 'Your full name may be 5 to 50 characters only.'
                }
            }
        },
```

**Comment by mickhansen** [comment]
Unique messages are not supported for allowNull, there's an existing issue for that somewhere.
The general reason is that allowNull is a schema check and not a validator persay.

**Comment by HassanAlthaf** [comment]
@mickhansen Well, the problem is, if I set `allowNull: false` it gives me an ugly message which I don't want to use. And if I remove it, it disables all other validation checks. Any work arounds?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/1500

**Comment by HassanAlthaf** [comment]
@mickhansen That didn't provide a fix. The suggested workaround doesn't work for me either. It ignores the `notEmpty: {}` check.

**Comment by mickhansen** [comment]
Not sure what workaround you're referring to, either way it's still an open issue.
You can use beforeFind to work around it.

**Comment by Lube** [comment]
Re opening this as there seems to be an issue when creating composite unique index with custom messages.

```javascript
const Categoria = sequelize.define('Categoria', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    nombre: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: {
          args: 'uniqueKey',
          msg: 'Ya existe una categoría con ese nombre.'
      },
      validate: {
        notEmpty: {
            args: true,
            msg: 'La categoría debe tener un nombre.'
        }
      }
    },
    deletedAt: {
      type: DataTypes.DATE,
      unique: {
        args: 'uniqueKey',
        msg: 'Ya existe una categoría con ese nombre.'
      }
    }
  }, {
    tableName: 'Categoria',
    classMethods: {
      associate: function associate(models) {
        Categoria.hasMany(models.Cosita, { as: 'Cositas' }, { foreignKey: 'categoria' });
      }
    },
    paranoid: true
  });
```
Generates two indexes on each field instead of only one (which does get created when only passing a string as argument to unique)

Categoria_nombre_unique	BTREE		nombre	1	A		
Categoria_deletedAt_unique	BTREE		deletedAt	1	A

**Comment by jasonbodily** [comment]
Whoa. I have the same problem that this thread started out as. Can we take it back to the original discussion, or should I create a new thread?

**Comment by luxueyan** [comment]
Me too！ custom message not work when creating composite unique index ！

**Comment by BartusZak** [comment]
Any update on that?

**Comment by mhmdtshref** [comment]
Any updates?

**Comment by HassanAlthaf** [comment]
@mhmdtshref I don't use this ORM anymore because of so many problems that came up. You can try referring to the docs for updates or open up a new issue with your specific code.

**Comment by LarissaGuder** [comment]
Any updates?

**Comment by eclemens** [comment]
Try this, this worked for me
```
    email: {
      allowNull: false,
      unique: {
        name: 'email',
        msg: 'Oops. Looks like you already have an account with this email address. Please try to login.',
      },
    }
```

**Comment by lamuertepeluda** [comment]
@eclemens  have you tried with a `unique.name` different from attribute name (i.e. referred to another column, composite index).

In my case, it's not working: [this line of code](https://github.com/sequelize/sequelize/blob/main/lib/model.js#L3954) is throwing the raw SQL message from mysql and therefore I cannot see my custom message.

Even debugging seem to ignore the custom message, even though it [seems to be set somewhere in the model creation](https://github.com/sequelize/sequelize/blob/main/lib/model.js#L1196) but then it's not handled anywhere, at least when saving.

MySQL 8.0
Sequelize 6.6.2
Node 14.15.4


```javascript
  name: {
    type: Sequelize.STRING,
  },
  myAttribute: {
    type: Sequelize.STRING,
    unique: {
      name: 'name', // refers to name, defined above
      msg: 'myAttribute must be unique',
    },
    allowNull: false,
  },
```

This will throw a raw error `mytable.name must be unique` instead of an error with this message: `myAttribute must be unique'`

I am using ES6 class-based definitions, i.e.

```javascript
class MyClass extends Sequelize.Model{
 ...
}

MyClass.initialize(attributes, options)
```

**Comment by lamuertepeluda** [comment]
Ok I found the problem, at least for MySQL Users.

On MySQL 8.0 the returned error message differs from MySQL 5.x. It returns `tablename.field` instead of just `field`.

e.g. `'Duplicate entry 'somevalue' for key 'mytable.name''`

This causes

https://github.com/sequelize/sequelize/blob/main/lib/dialects/mysql/query.js#L219 to fail to match the attribute name, and therefore `uniqueKey` at line 221 will be always undefined in this case, and the custom message will be ignored...

With my previous example, `fieldKey` will be `'voice_chanspy.name'` instead of just `'name'`

If we split the returned value using `'.'` and take the last member, it should work

I'll try to make a PR

**Comment by lamuertepeluda** [comment]
@mickhansen I know this is an old one, but could you please re-open this issue while I make a PR that fixes this for MySQL 8.0?

**Comment by AkatGabrielGoncalves** [comment]
What solved my problem was using unique.name as 'yourTableName'.'your column', so for our users table if I need the column email to be unique it would be like that:

MySQL 8.0
Node v14.17.3
Sequelize 6.6.5

```js
email: {
  type: DataTypes.STRING,
  allowNull: false,
  unique: {
    name: 'users.email',
    msg: 'Email já cadastrado.',
  },
  validate: {
    len: {
      args: [6, 255],
      msg: 'O email precisa ter de 6 a 255 caracteres.',
    },
    isEmail: {
      msg: 'A entrada precisa ser um email válido.',
    },
  },
},
```

The returned error is:
```js
{
  "error": {
    "name": "SequelizeUniqueConstraintError",
    "errors": [
      {
        "message": "Email já cadastrado.",
        "type": "unique violation",
        "path": "email",
        "value": "gabriel@gabriel.com",
        "origin": "DB",
        "instance": {},
        "validatorKey": "not_unique",
        "validatorName": null,
        "validatorArgs": []
      }
    ],

```

**Comment by meckyblaze** [comment]
> 
> 
> Try this, this worked for me
> 
> ```
>     email: {
>       allowNull: false,
>       unique: {
>         name: 'email',
>         msg: 'Oops. Looks like you already have an account with this email address. Please try to login.',
>       },
>     }
> ```

You're a life save... struggled with this all night

**Comment by lamuertepeluda** [comment]
@meckyblaze which version of MySQL are you using?
