### ISSUE TITLE
Include not working properly if association is not on the primary key

### ISSUE THREAD

**Issue by YouriT** [sequelize/sequelize#5034]
Let's say I have the following models:

``` js
var Child = sequelize.define('Child', {
    description: {
        type: DataTypes.TEXT
    },
    createdAt: DataTypes.DATE,
    updatedAt: DataTypes.DATE
}, {
    name: {
        singular: 'child',
        plural: 'children'
    }
});

var Parent = sequelize.define('Parent', {
    myPrimaryKey: {
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    myUniqueCol: {
        type: DataTypes.STRING,
        unique: true,
        allowNull: true
    },
    description: DataTypes.STRING
    createdAt: DataTypes.DATE,
    updatedAt: DataTypes.DATE
}, {
    name: {
        singular: 'parent',
        plural: 'parents'
    }
});

Child.belongsTo(Parent, {
    foreignKey: {
        name: 'myUniqueKey',
        allowNull: false
    },
    targetKey: 'myUniqueCol',
    as: 'Parent'
});
Parent.hasMany(Child, {
    foreignKey: {
        name: 'myUniqueKey',
        allowNull: false
    },
    as: 'Children'
});
```

And I want to eager load all Children of Parent, I would do:

``` js
Parent
    .findOne({
        where: {
            myUniqueCol: 'someExistingValue'
        },
        include: [{
            model: Child,
            required: false,
            as: 'Children',
            order: [
                ['createdAt', 'DESC']
            ]
        }]
    })
```

The result is not as expected, when checking a bit deeper, I see the following SQL query:

``` sql
SELECT "Parent".*,
       "Children"."id" AS "Children.id",
       "Children"."description" AS "Children.description",
       "Children"."createdAt" AS "Children.createdAt",
       "Children"."updatedAt" AS "Children.updatedAt",
       "Children"."myUniqueKey" AS "Children.myUniqueKey",
FROM
  (SELECT "Parent"."myPrimaryKey",
          "Parent"."myUniqueCol",
          "Parent"."description",
          "Parent"."createdAt",
          "Parent"."updatedAt"
   FROM "Parent" AS "Parent"
   WHERE "Parent"."myUniqueCol" = 'someExistingValue' LIMIT 1) AS "Parent"
LEFT OUTER JOIN "Child" AS "Children" ON "Parent"."myPrimaryKey" = "Children"."myUniqueKey";
```

As you can see, the `ON` condition is wrong, it should be `"Parent"."myUniqueCol" = "Children"."myUniqueKey"`

Am I missing something in there or is this a bug?

Thanks,

Youri

**Comment by mickhansen** [comment]
Looks like a bug.

**Comment by YouriT** [comment]
Okay, good to know, was hurting my brain alone! I'm on latest stable ```3.14.2``` but on ```3.13.0``` it was the same problem.

As a work around, did the queries separately.

Also something to notice is that if your do first ```hasMany``` and then ```belongsTo``` the foreignKey column is not named properly.

Thanks for the update @mickhansen :)

**Comment by mickhansen** [comment]
Oh actually, this isn't a bug, only `hasMany` supports `targetKey`, no other association do yet.

**Comment by mickhansen** [comment]
And currently you only have `targetKey` on belongsTo, try moving it to `hasMany`

**Comment by YouriT** [comment]
If I do that, the constraint created in the database becomes:
```Child_myPrimaryKey_fkey (myUniqueKey) -> Parent(myPrimaryKey)``` instead of ```Child_myUniqueCol_fkey (myUniqueKey) -> Parent(myUniqueCol)``` so this is weird behaviour.

**Comment by mickhansen** [comment]
Hmm, as a work around you might have to disable constraints on belongsTo.
Otherwise you'll have to wait for belongsTo support targetKey

**Comment by YouriT** [comment]
Okay, but that does not really explain with when putting ```targetKey``` in ```belongsTo``` the constraint becomes right ^^
