### ISSUE TITLE
How can I set foreign key when creating a new object?

### ISSUE THREAD

**Issue by koyabr** [sequelize/sequelize#5036]
Say I have two models defined:
```
Patient.hasMany(MedicalRecord, { foreignKey: 'patientId' });
MedicalRecord.belongsTo(Patient, { foreignKey: 'patientId' });
```

When I create a new `MedicalRecord`, how can I set value for its `Patient`?

I tried
1.
```
MedicalRecord.create({
    ...,
    patientId: 1,
    ...
})
```
2.
```
MedicalRecord.create({
    ...
}).then(function(record){
    record.setPatient(patient);
    record.save();
})
```

Both method result in a `MedicalRecord` whose  column `patientId` is NULL in mysql.

**Comment by mickhansen** [comment]
Example 1 should work.
In your second example you should rather use:

```js
MedicalRecord.create({
    ...
}).then(function(record){
  return record.setPatient(patient);
});
```
or
```js
MedicalRecord.create({
    ...
}).then(function(record){
  record.setPatient(patient, {save: false});
  return record.save();
});
```

**Comment by koyabr** [comment]
@mickhansen Thanks for reply. I tried method 1 again but no lucky.

This is the content to be created:
```
 { patientId: 1,
   tooth: 0,
   date: '2015-12-08',
   doctor: 'jack',
   fee: 12 }
```
I can see this line in my log:
```
Executing (default): INSERT INTO `MedicalRecords` (`id`,`date`,`tooth`,`doctor`,`fee`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'2015-12-08 00:00:00',0,'jack',12,'2015-12-14 15:34:12','2015-12-14 15:34:12');
```

It seems the `patientId` is missing?

**Comment by mickhansen** [comment]
Odd, that would indicate that you have no `patientId` field at all, can you try logging `Object.keys(MedicalRecord.rawAttributes)`?

**Comment by koyabr** [comment]
@mickhansen Aha! Now I know what's going wrong, double checked my definition of `MedicalRecord` and there is no field called `patientId`. Somehow I thought the code below would automatically generate that field.
```
Patient.hasMany(MedicalRecord, { foreignKey: 'patientId' });
MedicalRecord.belongsTo(Patient, { foreignKey: 'patientId' });
```

I add `patientId` and everything works, thanks again for your quick help! :)

**Comment by mickhansen** [comment]
Well that code should actually add patientId automatically, so are you sure that code is being called?

**Comment by alisherafat** [comment]
foreign keys are not added automatically, I had the same issue and after adding `patientId` to model definition every thing worked!

**Comment by capiot-shobhit** [comment]
How can i get the list of foreign keys in a model. MedicalRecord.rawAttributes will return all the keys, I want only foreignKeys

**Comment by theoephraim** [comment]
+1 -- I thought it would add the field automatically as this is what the docs say.
