### ISSUE TITLE
conformOptions/conformInclude are not exported by lib/model.js module

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#5037]
In lib/model.js there are two functions (conformOptions and conformInclude) that are not available to public (not exported by module). I wanted to add some custom functionality to sequelize that requires those functions. Do you mind @janmeier / @mickhansen  if I will write PR which will add them to exports? I am not sure how to export them though - as Model.conformOptions (static) will be ok?

My issue is that I want to call public (exported) method `Model.$injectScope(...)` but in source code, before this method it states:

> Includes should have been conformed (conformOptions) before calling this ($injectScope)

**Comment by mickhansen** [comment]
Exposing them as `$conformOptions` and `$conformInclude` respectively is fine by me.
Don't add them to docs or anything though, they are still considering private methods.

**Comment by alekbarszczewski** [comment]
@mickhansen Thanks, created PR #5038
