### ISSUE TITLE
Change default value of allowNull for all models

### ISSUE THREAD

**Issue by ShimShamSam** [sequelize/sequelize#504]
I try to avoid null values as much as possible, unfortunately I have to go through every model and add "allowNull: false" to every column definition. It would be nice if there was some connection-wide setting that allowed me to default allowNull to false.

**Comment by benkaiser** [comment]
I'd like to reopen this issue. It appears that the answer of using `allowNull`, simply refers to the attribute level of a model, and not globally as this question from @ShimShamSam was referring.

There is no global `allowNull` attribute (`allowNull` always default to `true` if omitted).

@janmeier @durango could this issue be re-opened?

**Comment by mickhansen** [comment]
@benkaiser What are you looking to achieve? A default `allowNull: false` for all attributes? You could simply implement a beforeDefine hook and modify attributes.

**Comment by benkaiser** [comment]
@mickhansen does that still have to be added at a model level? Or can you add a hook for all of sequelize in one place?

**Comment by mickhansen** [comment]
@benkaiser A beforeDefine hook is added on the sequelize instance and called each time before a model is defined.

**Comment by AJamesPhillips** [comment]
Something like this should suffice (again all, thanks for the great library!):

```js
var _ = require("lodash");
var Sequelize = require("sequelize");

var sequelize = new Sequelize(DATABASE, USERNAME, PASSWORD, config);

var UserFields = {
    uuid: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.UUIDV4,
    },
    createdAt: {
        type: Sequelize.DATE(6),
    },
    updatedAt: {
        type: Sequelize.DATE(6),
    },
    deletedAt: {
        type: Sequelize.DATE(6),
    },
};

var USER_TABLE_NAME = "demo_user";

var NULLABLE_MODEL_FIELDS = {
    [USER_TABLE_NAME]: ["deletedAt"]
};

sequelize.beforeDefine(function (attributes, options) {

    // May break if name is defined by a string rather than object with {singular, plural}?
    var NULLABLE_FIELDS = NULLABLE_MODEL_FIELDS[options["name"]["singular"]] || {};
    _.keys(attributes).forEach(function (field_name) {

        var field_definition = attributes[field_name];
        if (!_.isString(field_definition) && !_.isUndefined(field_definition["type"])) {
            var nullable = _.includes(NULLABLE_FIELDS, field_name);
            // mutate attributes
            field_definition.allowNull = nullable;
        }
    });
});

var UserDb = sequelize.define(USER_TABLE_NAME, UserFields, DEFINE_OPTIONS);
```

**Comment by tsirolnik** [comment]
First of all, thanks for this great tool. 
Now, I would like to add that maybe there should be considered an option to pass default arguments in the model definition so we wouldn't have to come up with `beforeDefine` stuff or setting allowNull per each column.

Something as in -

```js
sequelize.define('user', {...}, {allowNull: false});
```

And then just doing Object.assign on the default values to the attributes or whatever the inner mechanism is/will be.

**Comment by DevSide** [comment]
I ended up with that solution which won't apply to foreign keys. I feel annoyed to use tricks for consistent typing. 

```js
function disallowNull(attributes) {
    for(let attributeName in attributes) {
        const attrDef = attributes[attributeName];

        if (typeof attrDef === 'function' || attrDef instanceof DataTypes.ABSTRACT) {
            attributes[attributeName] = {
                type: attrDef,
                allowNull: false,
            };
        } else if (attrDef.allowNull !== true){
            attrDef.allowNull = false;
        }
    }

    return attributes;
}

sequelize.define('Upsell', disallowNull({
  id: DataTypes.INTEGER,
  code: {
    type: DataTypes.STRING,
  },
  optional: {
    type: DataTypes.STRING,
    allowNull: true, // overrides default
  },
});
```

**Comment by d-luk** [comment]
Please re-open this feature request. It would be very useful to have an option to globally set `allowNull: false` as the default so we don't have to set it manually for every column.

**Comment by ephys** [comment]
Closing in favor of https://github.com/sequelize/sequelize/issues/14260
