### ISSUE TITLE
Add composite indexes in migration scripts

### ISSUE THREAD

**Issue by buunguyen** [sequelize/sequelize#5040]
I have searched the issues and it seems like it's possible in schema definition but I haven't seen an example of defining composite indexes with `queryInterface` from within a migration script. Is it possible and if not, what's a workaround in order to do so from within a migration script? Thanks.

**Comment by mickhansen** [comment]
Not possible at the moment, is on our todo list :)

**Comment by buunguyen** [comment]
Thanks. I've just found out in [the documentation](http://docs.sequelizejs.com/en/latest/docs/migrations/) that it's possible to add a composite index, like so (example from the doc):

```js 
queryInterface.addIndex(
  'Person',
  ['firstname', 'lastname'],
  {
    indexName: 'SuperDuperIndex',
    indicesType: 'UNIQUE'
  }
)
```

Do you mean the doc is right but the feature is not yet available?

**Comment by mickhansen** [comment]
Oh damn, i missed that. If it's in the docs it's available :) (it's usually the other way around)

**Comment by buunguyen** [comment]
Great, good to have it confirmed. Thanks.
