### ISSUE TITLE
[babel 6] is there a npm release supporting babel 6?

### ISSUE THREAD

**Issue by BerndWessels** [sequelize/sequelize#5041]
Hi
I found [this issue](https://github.com/sequelize/sequelize/issues/4881) but can't find a release on NPM that supports babel 6.
When are you planning to publish it?

**Comment by mickhansen** [comment]
It will be in the next release: https://github.com/sequelize/sequelize/blob/master/changelog.md
I'll try and find time to cut a release tomorrow.

**Comment by BerndWessels** [comment]
@mickhansen Great, thank you. really looking forward to it.
