### ISSUE TITLE
Error when updating date column on PostgreSQL

### ISSUE THREAD

**Issue by guisehn** [sequelize/sequelize#5046]
On 3.14.2, when trying to update a date column of a model instance:

```javascript
Model.findOne().then(function(instance) {
  var tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);

  instance.expiration = tomorrow;
  return instance.save();
});
```

On a model defined as:

```javascript
var Model = sequelize.define('Model', {
  expiration: Sequelize.DATE,
});
```

Over PostgreSQL, I get the following error:

````
Unhandled rejection TypeError: Object 2015-12-16T12:23:29+00:00 has no method 'getTime'
    at Instance.set (/path/to/node_modules/sequelize/lib/instance.js:348:68)
    at funcs.(anonymous function) (/path/to/node_modules/sequelize/lib/model.js:767:23)
    [...]
```

I looked over [the line 348 at sequelize/lib/instance.js](https://github.com/sequelize/sequelize/blob/f48110132a16d6a87deea4d6d6b172fd99a4520d/lib/instance.js#L348) at the specified line and noticed that the error occurs because `originalValue` is a string and doesn't have a `getTime` method.

```javascript
if (originalValue && value.getTime() === originalValue.getTime()) {
```

It appears that a [similar issue](https://github.com/sequelize/sequelize/issues/4289) has been created before for a similar scenario and has been fixed, however it's still not working for this one.

**Comment by guisehn** [comment]
After investigating further it appears that this has to do with a custom timestamp parser that we have in the codebase I'm working at.

```javascript
var types = require("pg").types;
types.setTypeParser(TIMESTAMP_OID, unction(val) {
  return val === null ? null : moment.tz(val, 'UTC').format();
});
```

It makes PostgreSQL return a string to Sequelize rather than a Date object, causing this problem on that `if` statement on `sequelize/lib/instance.js`.

I've checked the code again and saw that it transforms `value` into a Date object if it is not at [line 348](https://github.com/sequelize/sequelize/blob/f48110132a16d6a87deea4d6d6b172fd99a4520d/lib/instance.js#L348).

```javascript
if (!(value instanceof Date)) {
  value = new Date(value);
}
```

Do you guys think it would be a good idea to do a similar check for `originalValue`?

**Comment by mickhansen** [comment]
That check is on set. Sequelize assumes that its existing values are always dates since they come from the database. Not sure how to do this best, i believe there's an existing PR for parsing originalValue like you suggest but i'd like to avoid it if possible.

**Comment by guisehn** [comment]
@mickhansen thanks for the fast response!
