### ISSUE TITLE
$contains on JSONB fails

### ISSUE THREAD

**Issue by YouriT** [sequelize/sequelize#5048]
Let's say I've the following model:

``` js
var User = sequelize.define('User', {
    meta: {
        type: DataTypes.JSON,
        allowNull: false
    }
});
```

With the following row inside:

| Column id | Column meta |
| --- | --- |
| 1 | `{assets:[{id: 'abc', and: 'some', other: 'props'}]}` |

And I do the following query on it:

``` js
User.findAll({
    where: {
        'meta.assets': {
            $contains: {
                id: 'abc'
            }
        }
    }
})
```

I don't get any result, neither any error is thrown, neither an SQL generated. But if I `catch(...)` I can then see the following error with its associated stack:

```
TypeError: undefined is not a function
    at Object.SqlString.escape (...api/node_modules/sequelize/lib/sql-string.js:56:15)
    at Object.QueryGenerator.escape (...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:983:22)
    at Object.QueryGenerator.whereItemQuery (...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2228:22)
    at ...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2092:34
    at ...api/node_modules/sequelize/node_modules/lodash/index.js:3073:15
    at baseForOwn (...api/node_modules/sequelize/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (...api/node_modules/sequelize/node_modules/lodash/index.js:3378:16)
    at traverse (...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2087:15)
    at ...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2113:11
    at ...api/node_modules/sequelize/node_modules/lodash/index.js:3073:15
    at baseForOwn (...api/node_modules/sequelize/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (...api/node_modules/sequelize/node_modules/lodash/index.js:3378:16)
    at ...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2105:11
    at Object.QueryGenerator.whereItemQuery (...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2118:9)
    at ...api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1875:25
    at ...api/node_modules/sequelize/node_modules/lodash/index.js:3073:15
```

When looking deeper I can see that the problem comes from the `$contains` property of the `findAll(...)` request. But the doc states that:

> JSONB can be queried in three different ways.
> [Referred Doc](http://docs.sequelizejs.com/en/latest/docs/querying/#jsonb)

And `$contains` is one of those.

I would see that as a bug honestly but maybe I missed something that is not in the doc?

_Using v3.14.2_

**Comment by mickhansen** [comment]
We only have tests for `$contains` on a non nested key, https://github.com/sequelize/sequelize/blob/master/test/unit/sql/where.test.js#L723

Can you verify whether or not it works on a top level key?
But yeah this looks like it might be missing/broken functionality assuming postgres supports it.

**Comment by mickhansen** [comment]
Although specifically in this case i'm not sure if you actually want a containment query.

**Comment by YouriT** [comment]
Going to test it, will keep you posted.

Juste as a quick research, in `sql-string.js` there is `val = val.replace(/'/g, "''");` which is obviously not possible on an object.

**Comment by YouriT** [comment]
@mickhansen what would you use then?

**Comment by mickhansen** [comment]
Well it looks like you're simply matching an id, so you could just do `{'meta.assets.id': 'abc'}`

**Comment by YouriT** [comment]
Yeah but `meta.assets` is an array not an object.

About the top level I guess it works but in fact my field is a `JSON` type and not a `JSONB` so I can't try it but the request is properly generated as:
```SQL
SELECT "id", "meta", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."meta" @> '{"id":"abc"}';
```

**Comment by YouriT** [comment]
But I'm not even sure I can realise what I was trying to achieve in Postgres, it's more of a mongo way I think...

**Comment by mickhansen** [comment]
@YouriT well JSONB lets you do a lot of stuff, so probably possible in some way :)

**Comment by YouriT** [comment]
@mickhansen it's feasible through the following SQL request:
```SQL
SELECT "id", "meta", "createdAt", "updatedAt" FROM "Users" AS "User"
WHERE "User"."meta"->'assets' @> '[{"id":"abc"}]';
```
> Spotted on [Stackoverflow](http://stackoverflow.com/questions/22736742/query-for-array-elements-inside-json-type)

But I guess there is no support for that kind of request, right?

**Comment by mickhansen** [comment]
@YouriT I guess not right now, but it would makes sense to support with a syntax like `{'meta.assets': {$contains: [{id: 'abc'}]}}`

**Comment by YouriT** [comment]
Yep :) would see that as a nice feature. Will check to propose a PR on that. If I do it, will it be integrated if I provide it with tests?

**Comment by mickhansen** [comment]
Yeah i don't see why we wouldn't merge it :)

**Comment by nasrinmithila** [comment]
Is there any update on this? Because the syntax `meta.assets : {$contains: [{id: 'abc'}]}` doesn't seem to be worked. Instead `meta: {$contains: {assets: [{id: 'abc'}]}}` seems to be working for me. But what about searching a string using $like. I tried `meta: {$contains: {assets: [{string_field: {$like: '%' + search + '%'}}]}}`. It is not working.

**Comment by balazsnemeth** [comment]
Any solution for $like type of request in JSONB array? How can this be solved to detect partial matching texts instead of exact match?
