### ISSUE TITLE
Auto-appending "DEFAULT NULL" to sqlite queries result in incorrect table schemas

### ISSUE THREAD

**Issue by jasonku** [sequelize/sequelize#5051]
When using sqlite and Sequelize migrations to change a column (either rename, remove, or add), Sequelize backs up the table, creates a new table with the changes, then copies the data over, to get around the fact that [sqlite does not support table alterations](http://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite).

To construct the `CREATE TABLE` query for the new table, Sequelize gets the schema of the existing table by using `PRAGMA INFO(tablename)`, then mapping those into the clauses of the `CREATE TABLE` query. As part of this, Sequelize attempts to append `DEFAULT NULL` for columns where the `defaultValue: null`.

For example: the returned object from the `PRAGMA INFO(tablename)` call:

```
...
name:
   { type: 'VARCHAR(255)',
     allowNull: true,
     defaultValue: null,
     primaryKey: false }
...
```

will be used to generate a query like:

```
'CREATE TABLE IF NOT EXISTS `rules` ( ... `name` VARCHAR(255) DEFAULT NULL ...)',
```

When this table is created, sqlite will have a 'NULL' default value for that column:

```
sqlite> PRAGMA TABLE_INFO(rules);
...
cid         name        type        notnull     dflt_value  pk
----------  ----------  ----------  ----------  ----------  ----------
3           name        VARCHAR(25  0           NULL        0
...
```

Then, subsequent `PRAGMA INFO(tablename)` calls will yield this object:

```
...
  name:
   { type: 'VARCHAR(255)',
     allowNull: true,
     defaultValue: 'NULL',
     primaryKey: false },
...
```

Note the incorrect `NULL` string literal. As you can imagine, causes all sorts of problems downstream, for example, subsequent `INSERT`s into the table populating the field value with the `NULL` string literal.

**Comment by mickhansen** [comment]
What's the issue here exactly? That sqlite does not support `DEFAULT NULL` or that it's not parsed correctly on schema changes?

**Comment by jasonku** [comment]
Looking deeper at it, it seems like the latter is more accurate. 

sqlite behaves properly with `DEFAULT NULL`:

```
sqlite> CREATE TABLE IF NOT EXISTS `jku` (`id` INTEGER PRIMARY KEY, `name` VARCHAR(255) DEFAULT NULL, `color` VARCHAR(255));
sqlite> PRAGMA TABLE_INFO(jku);
cid         name        type        notnull     dflt_value  pk
----------  ----------  ----------  ----------  ----------  ----------
0           id          INTEGER     0                       1
1           name        VARCHAR(25  0           NULL        0
2           color       VARCHAR(25  0                       0
sqlite> INSERT INTO jku(color) VALUES('blue');
sqlite> select * from jku;
id          name        color
----------  ----------  ----------
1                       blue
sqlite> INSERT INTO jku(name) VALUES('hi');
sqlite> select * from jku;
id          name        color
----------  ----------  ----------
1                       blue
2           hi
```

but `QueryInterface.describeTable` populates the `defaultValue` attribute as the string `NULL`.

**Comment by mickhansen** [comment]
@jasonku So the bug is with describeTable parsing the default value accurately in SQLite

**Comment by jasonku** [comment]
@mickhansen So `describeTable` parsing the the default value as `NULL` string isn't the root issue. It is also a bug but it is a manifestation of the root issue. Let me try to re-explain:

* Attempt to rename a column: `sqlite/query-interface.js#renameColumn`
* `renameColumn` calls `describeTable` to get the schema into an object of fields like:
```
name:
   { type: 'VARCHAR(255)',
     allowNull: true,
     defaultValue: null,
     primaryKey: false }
```
* `renameColumn` generate the query via `sqlite/query-generator.js#renameColumnQuery`
* `renameColumnQuery` calls `attributesToSql` to turn the object of fields to SQL:
```
'CREATE TABLE IF NOT EXISTS `rules` ( ... `name` VARCHAR(255) DEFAULT NULL ...)',
```
* Note the addition of the `DEFAULT NULL` clause. This effectively changes the sqlite table to have an explicit default value of `NULL` where it wasn't specified before by the user. This is the root issue.
* The next time we attempt to do `describeTable`, `describeTable` will yield a different object of fields than the first time:
```
name:
   { type: 'VARCHAR(255)',
     allowNull: true,
     defaultValue: 'NULL',
     primaryKey: false }
```
* Note the string `NULL` rather than `null`.

**Comment by mickhansen** [comment]
Ah so it's getting `defaultValue: null` although no default value was ever defined previously?
That should definitely be undefined when not defined rather than null.

**Comment by jasonku** [comment]
Ah yes, I see that making it `undefined` rather than `null` would fix the issue as well, since `Utils.defaultValueSchemable(undefined)` returns false. I can try to amend my PR with this approach or you can make the fix directly, whichever will get the fix published to NPM the fastest.

**Comment by mickhansen** [comment]
Please ammend your PR :)

**Comment by jasonku** [comment]
@mickhansen Please have a look: https://github.com/sequelize/sequelize/pull/5061
