### ISSUE TITLE
Question about `afterCreate` and `afterBulkCreate` hooks

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#5053]
If I set a function to the `afterCreate` hook, it is also called inside `afterBulkCreate`?

or do I have to link those hooks separately to the same function if wanted that is triggered in both cases?

Thanks!

**Comment by mickhansen** [comment]
It is not, you can however pass `individualHooks: true` to a bulkCreate call to have it call afterCreate aswell.

**Comment by diosney** [comment]
Ok, thanks!
