### ISSUE TITLE
question: How can I use a running transaction inside an `instanceMethods` declaration?

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#5054]
**Setup:**
I have a model with one instance method defined. In this instance model I run other sequelize queries.

In a controller I'm executing several queries inside a transaction and also I'm executing that instance method I defined earlier in the method.

**Question:**

Inside a hook definition I had access to `options.transactions` so I can pass it to the inner queries.

The question would be: How can I pass that transaction reference to the body of the instance method definition?

There is a native way to do that? 

Or I should pass `transaction` or `t` (as the examples) as a parameter for the instance method?

Thanks

**Comment by diosney** [comment]
Or maybe if I'm using CLS I can omit to pass the transaction as an option since I want to run all queries under the same transaction and that is the default behavior with CLS enabled?

I need to run the instance method inside a hook too so the complete cycle would be:

    - controller code
          - inside the controller I execute queries under  `sequelize.transaction()`
              - inside that transaction callback I'm creating a model instance like:
                   sequelize.transaction(function(t) {
                        return SomeModel.create(data, {
                           transaction: t
                        });
                   });

              - now, as an `afterCreate` hook at the `SomeModel` definition, I want to execute the instance model of other Model, something like:
                   SomeModel definition
                   ...
                   hooks: function (instance, options) {
                         // Here I've access to `options.transaction`.
                         return AnotherModel.findOne().anInstanceMethod();  // YYY
                   }
 
              - and in the `anInstanceMethod` definition I need to do other queries as well, but I need that are inside the same transaction that I created in the controller, but I don't know if there is an already thought way to pass it to be used inside the instance method body as it is done in the hooks body.

So, the question would be, at the line marked with YYY, how can I pass the transaction reference to the instance method, so can link them together?

Thanks

**Comment by mickhansen** [comment]
CLS is a bit of magic so you'll just have to test it to see if it works, but yes it should be available inside the instanceMethod since there's no tick.

Otherwise just pass your options to the instanceMethod yes.

**Comment by diosney** [comment]
Ok, thanks! I will stick with passing the transaction to `instanceMethod`, it reads clearly since all is written.

Thanks again.
