### ISSUE TITLE
equalDate alone is not a suitable assertion for timestamp comparison in tests

### ISSUE THREAD

**Issue by nathanmarks** [sequelize/sequelize#5055]
I noticed that a timestamp related test had this sole expectation:

```
expect(user1.updatedAt).to.equalDate(updatedAt);
```

(source: https://github.com/sequelize/sequelize/blob/master/test/integration/instance.test.js#L1082)

This expectation will pass even if the time is different as [chai-datetime](https://github.com/mguterl/chai-datetime) does not compare the time portion for date assertions:

> There are a collection of assertions that work on times and dates. Any assertion that specifies date in the name only compares the date portion of the Date object.

Internally, chai-datetime uses [Date.prototype.toDateString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toDateString) to compare values when using the `equalDate` assertion. 

(relevant line in chai-datetime: https://github.com/mguterl/chai-datetime/blob/master/chai-datetime.js#L68)

**Comment by nathanmarks** [comment]
BTW, the `equalTime` assertion looks better as it uses [Date.prototype.getTime()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) which returns the timestamp.

> The value returned by the getTime() method is the number of milliseconds since 1 January 1970 00:00:00 UTC.

https://github.com/mguterl/chai-datetime/blob/master/chai-datetime.js#L68

**Comment by mickhansen** [comment]
That should definitely be changed to `equalTime`, you're right.
