### ISSUE TITLE
logging default value in sync

### ISSUE THREAD

**Issue by rafis** [sequelize/sequelize#5063]
Actual default value is `false`, not `console.log` like function doc saying:
https://github.com/sequelize/sequelize/blob/v3.15.0/lib/sequelize.js#L920
https://github.com/sequelize/sequelize/blob/v3.15.0/lib/sequelize.js#L931

Also there is an related issue I have met here:
https://github.com/sequelize/sequelize/blob/v3.15.0/lib/sequelize.js#L756-L760

I think it merges options improperly. I don't went deep in learning this issue, so I have two unconcrete solutions.

First is to swap arguments in `_.defaults`:

``` javascript
  options = Utils._.extend(Utils._.clone(this.options.query), options);
  options = Utils._.defaults({
    logging: this.options.hasOwnProperty('logging') ? this.options.logging : console.log,
    searchPath: this.options.hasOwnProperty('searchPath') ? this.options.searchPath : 'DEFAULT',
  }, options);
```

Second is to merge calls into single `_.extend`:

``` javascript
  options = Utils._.extend(Utils._.clone(this.options.query), options, {
    logging: this.options.hasOwnProperty('logging') ? this.options.logging : console.log,
    searchPath: this.options.hasOwnProperty('searchPath') ? this.options.searchPath : 'DEFAULT',
  });
```

**Comment by mickhansen** [comment]
Looks like there are a few issues yes.
