### ISSUE TITLE
Filter multiple joined tables?

### ISSUE THREAD

**Issue by menoz15** [sequelize/sequelize#5066]
Hello everybody,
I'm stuck with this problem and can't seem to find a solution. I have multiple tables arranged in a star schema (fact table in the middle, descriptive tables around it, joined by IDs). 

FactTable's model consist in an unique ID and two other columns, one for FirstContentId and the other for SecondContentId.

I can successfully get all the joined data using *include*

    models.FactTable.findAll({ 
		attributes: ['Id', 'IdFirstContent', 'IdSecondContent'],
		include: [
		{
			model: models.FirstContent,
			attributes: ['Id','Description'],
		}, {
			model: models.SecondContent,
			attributes: ['Id','Description'],
		}],
        where ...

Now my question: I have a filter keyword and would like to filter both FirstContent.Description or SecondContent.Description with this. 

I would basically like to write something like this in SQL:

    WHERE FirstContent.Description LIKE '%Filter%' OR SecondContent.Description LIKE '%Filter%'

I can't put this clause in the "include" part, since it would filter only that content, and not both.
I tried putting this clause in the final where but I get an error when writing models.FirstContent, saying the dot is an unexpected token.

How can I solve this problem?
Thank you very much

**Comment by mickhansen** [comment]
You can use the new `$col$` syntax:

```js
where: {
  '$FirstContent.Description$': {
    like: // ....
  }
}
```

**Comment by fabioespinosa** [comment]
Hi @mickhansen is it possible to use the $col$  with JSONB?

For example: 
```
where: {
    '$FirstContent.Description$.jsonb_column': {
           like: '%mick%'
    }
}
```
