### ISSUE TITLE
Migration: How to insert single row promising the new id?

### ISSUE THREAD

**Issue by Splact** [sequelize/sequelize#5067]
Actually when I have to insert some rows as migrations I use queryInterface.bulkInsert(tableName, records, options, attributes). But if I need to manage resulting ids for a subsequent query which method I have to use?

Reading QueryInterface definition (lib/query-interface.js) I found "QueryInterface.prototype.insert = function(instance, tableName, values, options)" seems perfect, but I don't understand the meaning of instance, I've not created yet any model instance at this time.

Any help?

**Comment by mickhansen** [comment]
insert assumes it's being called by an instance, a faulty assumption but one that exists at the moment never the less.

**Comment by Splact** [comment]
So "QueryInterface.prototype.insert" is not for my needs?

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L483
Looks you might be able to put `null` for instance
