### ISSUE TITLE
default value doesn't get the default set from db

### ISSUE THREAD

**Issue by Nosthertus** [sequelize/sequelize#5071]
I have a timestamp column and i make my db `mysql` to set it by default. after generating the models using `sequelize-auto`, i have seen that this attribute has the property `defaultValue` to be `CURRENT_TIMESTAMP` just as it is defined in `mysql` structure, but after creating a record, i don't see it sets the value i look for, instead i see it tries to set `CURRENT_TIMESTAMP` just like it is defined from the model rather than defined in db

**Comment by mickhansen** [comment]
Are you saying that the model is included a default on create although you've specified that it shouldn't?
Please include relevant code.

**Comment by Nosthertus** [comment]
@mickhansen this is the code what `sequelize-auto` has generated

```javascript
module.exports = function(sequelize, DataTypes) {
	return sequelize.define('user', {
		id: {
			type: DataTypes.INTEGER(10),
			allowNull: false,
			primaryKey: true,
			autoIncrement: true
		},
		name: {
			type: DataTypes.STRING,
			allowNull: false
		},
		user_email: {
			type: DataTypes.STRING,
			allowNull: false
		},
		password: {
			type: DataTypes.STRING,
			allowNull: false
		},
		password_token: {
			type: DataTypes.STRING,
			allowNull: true
		},
		first_name: {
			type: DataTypes.STRING,
			allowNull: true
		},
		last_name: {
			type: DataTypes.STRING,
			allowNull: true
		},
		biography: {
			type: DataTypes.STRING,
			allowNull: true
		},
		post: {
			type: DataTypes.ENUM('PUBLIC','PRIVATE'),
			allowNull: true,
			defaultValue: 'Public'
		},
		timestamp: {
			type: DataTypes.DATE,
			allowNull: true
		},
		country_id: {
			type: DataTypes.INTEGER(10),
			allowNull: false,
			references: {
				model: 'country',
				key: 'id'
			}
		},
		state_id: {
			type: DataTypes.INTEGER(10),
			allowNull: false,
			references: {
				model: 'state',
				key: 'id'
			}
		},
		city_id: {
			type: DataTypes.INTEGER(10),
			allowNull: false,
			references: {
				model: 'city',
				key: 'id'
			}
		}
	}, {
		tableName: 'user',
		freezeTableName: true,
		timestamps: false,
	});
};
```

**Comment by mickhansen** [comment]
Open issues about sequelize-auto on sequelize-auto, none of the sequelize maintainers have anything to do with that library i'm afraid :)

Sequelize might not support `'CURRENT_TIMESTAMP'` as a default value, no idea, what does the insert sql statement look at?

**Comment by Nosthertus** [comment]
@mickhansen a testing creation row logs this SQL

```sql
INSERT INTO `user` (`id`,`name`,`user_email`,`password`,`post`,`timestamp`,`country_id`,`state_id`,`city_id`) VALUES (DEFAULT,'test','darkfreaks17@hotmail.com',123456,'Public','Invalid date',237,4026,47294);
```

if this is not supported, then i suppose i would have to set "allowNull" to false.

**Comment by mickhansen** [comment]
You might try using `db.literal('CURRENT_TIMESTAMP')`.
Or simply use `DataTypes.NOW` instead.

**Comment by Nosthertus** [comment]
Perfect.. `sequelize.literal('CURRENT_TIMESTAMP')` has done the job for this..

**Comment by Nosthertus** [comment]
i would like to ask how to use references correctly, if you would allow me to ask me in this issue

**Comment by mickhansen** [comment]
@Nosthertus References are created automatically by most relations. But you can also use a `{references: Model, referencesKey: 'key'}` on attribute definitions.

**Comment by mickhansen** [comment]
If you're using sequelize-auto and not creating tables with sequelize you really don't need to replicate the constraints in your code though.

**Comment by Nosthertus** [comment]
i was just having problems how to add related data in a query result.. i finally got able to get that by defining the types of relations on the proper model and then include it into query calls.. 

but i thought the referenced attribute would be replaced by the model object rather than just id..

let's say this user has a column `foreignKey` named `country_id` which is referenced to the table "country", both tables are defined in sequelize (in this cause i imported both models and defined the type of relations like `user.belongsTo(country)` and `country.hasMany(user)`) and then do a query call like `user.findAll({include: [country]})`

this returns:
```json
{
	"id": 3,
	"name": "randomUser",
	"country_id": 237,
	"country": {
		"id": 237,
		"name": "United States"
	}
}
```

but i thought `country_id` would be replaced by `country` or just not show `country_id` for a faster way

**Comment by mickhansen** [comment]
The returned values are as expected, we don't filter out the foreign key automatically.

**Comment by Nosthertus** [comment]
ok, that's all i needed to know.. thank you
