### ISSUE TITLE
BulkCreate return objects with key=column name, not model attribute name

### ISSUE THREAD

**Issue by hoangphuoc25** [sequelize/sequelize#5073]
In my model, I have this attribute: 
```
userId: {
      type: 'string',
      allowNull: false,
      field: 'user_id',
}
```
In my code, I have this: 
```
var listOfObjects = [{ userId: '1234'}, {userId: '5678'}];
```
When I run `Model.bulkCreate(listOfObjects, {returning: true})`, the objects I got from the result is of the format `{user_id: '1234'}`. This causes an error when I try to update the my object into the database. How can I map the objects I got to models? (i.e., {userId: '1234'}).

I'm using Sequelize with Postgresql.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/3764

**Comment by hoangphuoc25** [comment]
So, this is intended behavior? Or is it a known bug?

**Comment by mickhansen** [comment]
Did you go through the issue i linked? It's a known bug, per the issue.
