### ISSUE TITLE
Option for Hiding eager loaded id

### ISSUE THREAD

**Issue by b22n** [sequelize/sequelize#5079]
```
AAA.findAll({include: [BBB]})

Current:
{
  id: xxx,
  bbbId: yyy,     // remove it
  BBB: {
    id: yyy
    ...
  }
}

Want to be:
{
  id: xxx,
  BBB: {
    id: yyy
    ...
  }
}
```

**Comment by mickhansen** [comment]
You'll need to use the `attributes` option.

**Comment by b22n** [comment]
Yeh I Know but a global option needed.

**Comment by mickhansen** [comment]
Use `beforeFind`

**Comment by b22n** [comment]
It's not for just a model.
the bottom format is more general usecase when populating nested models maybe

**Comment by mickhansen** [comment]
@b22n You can apply beforeFind to multiple models. It's not something that is likely to change (it would be semver:major and i don't think it's obvious it should happen at all)
