### ISSUE TITLE
Abstract Connection Manager does not pass dialectOptions on replication scenario

### ISSUE THREAD

**Issue by Khez** [sequelize/sequelize#5083]
Hello,

When using the replication read / write feature of Sequelize, the actual dialectOptions will be lost [@line 116](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L116)

The dialectOptions will be passed when no replication is used, due to the inherit usage of the entire config object [@line 90](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L90)

This feels inconsistent, can I make a pull request to fix this ?

Best Regards,
Khez

**Comment by mickhansen** [comment]
The write/read config objects should be inheriting the entire config options and only overwriting as needed.
PR welcome :)

**Comment by Khez** [comment]
Hello,

I figured the safest approach was to actually inherit the entire config except the replication key.

My use case was specific to postgresql and setting `application_name` on the main config did not have any effect. Testing the PR for my specific scenario worked :?

I can also do some minor test cases for this, but I doubt anything bad can happen, unless people were actively using the "feature" that replication did not have dialectOptions passed (?)

Best Regards,
Khez
