### ISSUE TITLE
PG transactions - some questions

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#5088]
Hey, I am not PG expert but I have couple of questions/remarks about transaction initialization in Sequelize, especially for PG:

1. On each transaction initialization routine `SET autocommit = 1` query is sent to the server - AFAIK, on pg 9.4 (not sure about older versions) this statement is ignored by PG server. In 9.5 this statement will be completely removed. By removing this command, number of client/server roundtrip could be reduced by 1 (on transaction initialization process).

2. On each transaction start, first `START TRANSACTION` is sent, and then `SET TRANSACTION ISOLATION LEVEL <isolation_level>`. This could be handled by single statement `START TRANSACTION ISOLATION LEVEL <isolation_level>` and it would allow to reduce number of client/server round trips by 1 (two statements vs single statement).

3. I have a question why default transaction isolation level in Sequelize is `REPEATABLE READ` while PG default (implicit) isolation level is "READ COMMITTED"?

**Comment by mickhansen** [comment]
1. Was recently fixed
2. Probably for cross dialect support?
3. Legacy, we really shouldn't be setting one unless the user decides to, i'll open an issue for that for 4.0

**Comment by mickhansen** [comment]
#5094

**Comment by alekbarszczewski** [comment]
@mickhansen Thanks. As for 2) I think this could be still improved by sending two statements in a single query, for example:

```sql
START TRANSACTION;
SET TRANSACTION ISOLATION LEVEL <level>;
```

For now statements are sent in a sequence:

```
  ...
  }).then(function () {
    return self.begin();
  }).then(function () {
    return self.setDeferrable();
  }).then(function () {
    return self.setIsolationLevel();
  ...
```

All those three statements could be merged into single query - what do you think?

**Comment by mickhansen** [comment]
@alekbarszczewski Assuming it can be done in a decent way across all dialects i'm all for it :)

**Comment by alekbarszczewski** [comment]
@mickhansen Ok, I will investigate if that's possible.
