### ISSUE TITLE
Can validations run for findOrCreate?

### ISSUE THREAD

**Issue by chickenwing** [sequelize/sequelize#5095]
Would it be possible to run validations for findOrCreate, if the model is created?

E.g. I have defined:

	var User = sequelize.define("User", {
		name: DataTypes.STRING,
		email: {
			type: DataTypes.STRING,
			validate: {
				notEmpty: {
					msg: "Please enter your email address."
				}
			}
		}
	});

And I call:

	User.findOrCreate({
		where: {
			email: req.body.email
		},
		defaults: {
			name: req.body.name,
			email: req.body.email
		}
	}).catch(function(e){
	  // no error here when req.body.email is empty
	})

When req.body.email is empty string, the validation will not run. I guess this is this expected?

**Comment by mickhansen** [comment]
`findOrCreate` uses `create` internally which uses `save` which uses `validate` so it should alreayd be happening.

Have you verified whether or not the validation error is triggered on a simple create?

**Comment by chickenwing** [comment]
I did that and it validated...

**Comment by mickhansen** [comment]
Are you sure create is called by findOrCreate then? It's not stopped after find?

**Comment by chickenwing** [comment]
Oh dear, indeed it was stopped after find because an empty req.body.email was already in the db. Thanks for bringing me back on track :)
