### ISSUE TITLE
Include not working even without declaring alias in model definition

### ISSUE THREAD

**Issue by daniellizik** [sequelize/sequelize#5103]
Seems like the most common mistake with `include` is not specifiying `as` in the query, as it must be if it was declared in the model. I am not specifying any aliases but still receiving `Error: Person is not associated to VideoPeople`. I'm on 3.15.0 using sqlite3 3.1.1

**`Person` model**

    module.exports = (sequelize, Datatypes) {
        var attrs = {
            firstname: Datatypes.STRING
        };
        var options = {
            classMethods: {
                associate: function(models) {
                    models.Person.belongsToMany(models.Video, { through: models.VideoPeople });
                }
            }
        };
        return sequelize.define("Person", attrs, options);
    };

**`Video` model**

    module.exports = (sequelize, Datatypes) {
        var attrs = {
            filename: Datatypes.STRING
        };
        var options = {
            instanceMethods: {

    /*         where the eager loading occurs            */

                includeMany: function() {
                    return sequelize.model("VideoPeople").findAll({
                        where: { videoId: this.dataValues.id },
                        include: [
                            { model: sequelize.model("Person") }
                        ]
                    }).then(function(people) {
                        return { people: people };
                    });
                } 

            },
            classMethods: {
                associate: function(models) {
                    models.Video.belongsToMany(models.Person, { through: models.VideoPeople });
                }
            }
        };
        return sequelize.define("Video", attrs, options);
    };

**`VideoPeople` model**

    module.exports = (sequelize, Datatypes) {
        var attrs = {
            videoId: {
                type: Datatypes.INTEGER,
                references: {
                    model: sequelize.models.Video,
                    key: "id"
                }
            },
            personId: {
                type: Datatypes.INTEGER,
                references: {
                    model: sequelize.models.Person,
                    key: "id"
                }
            }
        };
        var options = {
            indexes: [
                { unique: true, fields: ["videoId", "personId"], name: "unique_VideoPeople" }
            ]
        };
        return sequelize.define("Video", attrs, options);
    };

And in my test

    describe("VideoPeople include", function() {
        it("should find people associated with a video via a video id", function(done) {
            models.Video.findById(1)
                .then(function(video) {
                    return video.includeMany();
                })
                .then(function(result) {
                    expect(result).to.have.ownProperty("people");
                })
                .catch(console.log)
        });
    });

Only the first query is being executed, doesn't even get to the join query.

    SELECT id, name 
    FROM 'Videos'
    AS 'Video'
    WHERE 'Video'.'id' = 1;

**Comment by mickhansen** [comment]
Well obviously the first query would not have a join.
As for the second, you've only setup a relation from Video to People, not form VideoPeople to People.
