### ISSUE TITLE
Getting full data using foreign keys.

### ISSUE THREAD

**Issue by alizarg** [sequelize/sequelize#5104]
I have 2 models. A House model with an email, latitude, and longitude. And I have a Listing model with a foreign key to email along with some other data. Right now I am using findAll() on listings but I'd also like to get the latitude and longitude of the house. Is the any way to easily do this in sequelize?

**Comment by maleeb** [comment]
User associations (http://docs.sequelizejs.com/en/latest/docs/associations/) to bind the models.
Than use Eager Loading (http://docs.sequelizejs.com/en/latest/docs/models-usage/#eager-loading) to load the associations of the model u call "findAll()".

like

Eager Loading (include)
```javascript
Listing
.findAll({ 
    include: [{ 
        all: true
    }]
})
.then(function(foundListings) {
    console.log(foundListings);
});
```

**Comment by mickhansen** [comment]
Expanding on what @maleeb wrote with a simple example:

```js
Listing.House = Listing.belongsTo(House);

Listing.findAll({
  include: [Listing.House]
});
```
