### ISSUE TITLE
Is there any way to stop output to terminal?

### ISSUE THREAD

**Issue by AlexKhodaverdian** [sequelize/sequelize#5105]
I was wondering, every time I try to run a query etc I get SQL syntax logged on the terminal. Is there any way to suppress this output?

**Comment by Joshua-F** [comment]
You can give sequelize a ``logging`` function or set it to false to not log.

````javascript
var sequelize = new Sequelize('my_database', 'john', 'doe', {
    logging: false
});
````

You can also enable/disable it for specific methods, just pass a logging option.

````javascript
Model.findOne({
    where: {
        ....
    },
    logging: console.log
})
````

http://sequelize.readthedocs.org/en/latest/api/sequelize/#new-sequelizedatabase-usernamenull-passwordnull-options

**Comment by AlexKhodaverdian** [comment]
Thanks!
