### ISSUE TITLE
complex association queries consume all computer memory.

### ISSUE THREAD

**Issue by DoryZi** [sequelize/sequelize#5110]
I'm having issues with some associated model.

I have an Order which has an associated model called Placements
Order < hasMany> Placements. When I query the order model with all associated Placements, it kills finishes all of the process memory (due to a huge return set). I've tried to query in two steps (first limited scope) then individual queries of associated models, but then when converting to JSON from the Order I get incomplete results. What is the problem? Is there a way to limit the memory or use a two step query, I'm attaching the models and query bellow:

    /****************************************************************************************************
     *       Order Model (top level)
     *
     ****************************************************************************************************/ 
		'use strict';

		module.exports = function(sequelize, DataTypes) {
			var Io = sequelize.define('Io', {
				AdvertiserId: {
					type: DataTypes.INTEGER,
					unique: {
						name: 'AgencyNameAndId',
						msg: 'Agency Name And ID Must be unique within an Advertiser'
					} ,
					allowNull: false
				},
				agencyOrderName: {
					type: DataTypes.STRING,
					unique: {
						name: 'AgencyNameAndId',
						msg: 'Agency Name And ID Must be unique within an Advertiser'
					},
					validate: {
						len: {
							args: [1,107], 
							msg: 'Agency Name must be between 1-107 characters'
						}
					},
					allowNull: false
				},
				agencyOrderId: {
					type: DataTypes.STRING,
					unique: {
						name: 'AgencyNameAndId',
						msg: 'Agency Name And ID Must be unique within an Advertiser'
					},
					validate: {
						len: {
							args: [1,20], 
							msg: 'Agency ID must be between 1-20 characters'
						}
					},	
					allowNull: false
				},

				start: {
					type: DataTypes.DATE,
					allowNull: false
				},
				end: {
					type: DataTypes.DATE,
					allowNull: false
				},

				totalOrderAmount: {
					type: DataTypes.VIRTUAL,
					get: function() {
						if (!this.Placements) return 0;
						return this.Placements.reduce(function(memo, placement) {
							var amount = parseFloat(placement.totalContractAmount, 10) || 0;
							memo += amount;
							return memo;
						}, 0);
					}
				},

				comments: {
					type: DataTypes.STRING
				},
				jagIoGroup: {
					type: DataTypes.STRING
				},
				dfpOrderId: {
					type: DataTypes.INTEGER,
				},
				dfpLastModified: {
					type: DataTypes.DATE,
				},
				pushState: {
					type: DataTypes.INTEGER
				},
				dfpError: {
					type: DataTypes.STRING
				}
			},
			{
				scopes: {
					fullDetailWithPlacements: {
						include: [
							{
								model: sequelize.models.Placement,
		/*
								attributes: [ 
									// regular attributes
									'id',
									'agencyPlacementName',
									'agencyPlacementId',
									'start',
									'end',
									'comments',
									'billingGroup',
									'mediaRate',
									'contractedQuantity',
									'excludeGallery',
									'pubSelect',
									'IoId',
									'totalContractAmount',
									// associated attributes foreign keys
									'IoId',
									'StrategyId',
									'SalesProductId',
									'MediaRateTypeId',
									'FrequencyCapId',
									// dfp related fields
									'dfpLineItemId',
									'dfpLastModified',
									'dfpStatus'
								],
							*/
								include: [
									{
										model: sequelize.models.Strategy,
										attributes: ['id', 'name', 'RequiredDetailTypeId']
									},
									{
										model: sequelize.models.SalesProduct,
										attributes: ['id', 'name', 'code', 'canExcludeGallery', 'canPubSelect'],
									},
									{
										model: sequelize.models.CreativeProduct,
										attributes: ['id', 'name']
									},
									{
										model: sequelize.models.CustomCriteriaPreset,
										attributes: ['id', 'name']
									},
									{
										model: sequelize.models.DataFee,
										attributes: ['id', 'amount'],
										include: [sequelize.models.DataFeeType, sequelize.models.DataFeeRateType]
									},
									{
										model: sequelize.models.Geotarget,
										attributes: ['id', 'name', 'type', 'parentIds']
									},
									{
										model: sequelize.models.Publisher,
										attributes: ['id', 'name']
									},
									{
										model: sequelize.models.DeviceType,
										attributes: ['id', 'name', 'code'],
										include: [
											{
												model: sequelize.models.CreativeProduct,
												attributes: ['id', 'name']
											}
										]						
									},	
									{
										model: sequelize.models.FrequencyCap,
										attributes: ['numImps', 'numTimeUnits', 'id'],
										include: [sequelize.models.FrequencyCapTimeUnit]
									},
									{
										model: sequelize.models.MediaRateType,
										attributes: ['id', 'name']
									}					
								]
							},
							{
								model: sequelize.models.IoStatus
							},
							{
								model: sequelize.models.IoType
							}
						]				
					},
					fullDetailWithoutPlacementsDependencies: {
						include: [
							{
								model: sequelize.models.IoStatus
							},
							{
								model: sequelize.models.IoType
							},
							{
								model: sequelize.models.Placement,
								scope: ['onlyIds'],

							}
						]
					}
				},

				classMethods: {
					associate: function(models) {
						Io.belongsTo(models.Advertiser, {foreignKey: {allowNull: false}, onDelete: 'CASCADE'});
						Io.hasMany(models.Placement, {onDelete: 'CASCADE'});
						Io.belongsTo(models.IoStatus, {foreignKey: {allowNull: false}, onDelete: 'CASCADE'});
						Io.belongsTo(models.IoType, {foreignKey: {allowNull: false}, onDelete: 'CASCADE'});
					}
				}
				
			});

			return Io;
		}; 

      /******************************************************************************************************************
       *
       *     Placement Model (associated model)
       *
       ******************************************************************************************************************/

       		'use strict';

		module.exports = function(sequelize, DataTypes) {
			var Placement = sequelize.define('Placement', {
				agencyPlacementName: {
					type: DataTypes.STRING,
					allowNull: false
				},
				IoId: {
					type: DataTypes.INTEGER,
					allowNull: false
				},
				agencyPlacementId: {
					type: DataTypes.STRING,
					allowNull: false
				},
				start: {
					type: DataTypes.DATE,
					allowNull: false
				},
				end: {
					type: DataTypes.DATE,
					allowNull: false
				},
				totalContractAmount: {
					type: DataTypes.VIRTUAL,
					get: function() {
						if (!this.DataFees) return;
						var result = this.DataFees.reduce(function(memo, fee) {
							var amount = parseFloat(fee.amount, 10)
							if (fee.DataFeeRateType.name === 'CPM') {
								memo.cpmIncrease += amount;
							} else {
								memo.flatFees += amount;
							}
							return memo;
						}, {
							cpmIncrease: 0,
							flatFees: 0
						});
						return (((this.mediaRate + result.cpmIncrease) * this.contractedQuantity) / 1000) + result.flatFees;
					}
				},
				billingGroup: DataTypes.STRING,
				mediaRate: DataTypes.DECIMAL(10,2),
				contractedQuantity: DataTypes.INTEGER,
				dataFeeCpm: DataTypes.DECIMAL,
				mediaContractAmount: DataTypes.INTEGER,
				excludeGallery: DataTypes.BOOLEAN,
				pubSelect: DataTypes.BOOLEAN,
				comments: DataTypes.STRING,
				pushState: DataTypes.INTEGER, 
				dfpLineItemId: DataTypes.INTEGER,
				dfpLastModified: DataTypes.DATE,
				dfpStatus: DataTypes.STRING,
				carGurusClonedFrom : DataTypes.INTEGER,
			},
			{
				scopes: {
					fullDetail: {
						attributes:[
							// regular attributes
							'id',
							'agencyPlacementName',
							'agencyPlacementId',
							'start',
							'end',
							'comments',
							'billingGroup',
							'mediaRate',
							'contractedQuantity',
							'excludeGallery',
							'pubSelect',
							'IoId',
							// associated attributes foreign keys
							'IoId',
							'StrategyId',
							'SalesProductId',
							'MediaRateTypeId',
							'FrequencyCapId',
							// dfp 
							'dfpLineItemId',
							'dfpLastModified',
							'dfpStatus',
							'carGurusClonedFrom' // cloned from Guru's ID

						],		
						include: [
							{
								model: sequelize.models.Strategy,
								attributes: ['id', 'name', 'RequiredDetailTypeId']
							},
							{
								model: sequelize.models.SalesProduct,
								attributes: ['id', 'name', 'code', 'canExcludeGallery', 'canPubSelect']
							},
							{
								model: sequelize.models.CreativeProduct,
								attributes: ['id', 'name']
							},
							{
								model: sequelize.models.CustomCriteriaPreset,
								attributes: ['id', 'name']
							},
							{
								model: sequelize.models.DataFee,
								attributes: ['id', 'amount'],
								include: [sequelize.models.DataFeeType, sequelize.models.DataFeeRateType]
							},
							{
								model: sequelize.models.Geotarget,
								attributes: ['id', 'name', 'type', 'parentIds']
							},
							{
								model: sequelize.models.Publisher,
								attributes: ['id', 'name']
							},
							{
								model: sequelize.models.DeviceType,
								attributes: ['id', 'name', 'code'],
								include: [
									{
										model: sequelize.models.CreativeProduct,
										attributes: ['id', 'name']
									}
								]
							},	
							{
								model: sequelize.models.FrequencyCap,
								attributes: ['numImps', 'numTimeUnits', 'id'],
								include: [sequelize.models.FrequencyCapTimeUnit]
							},
							{
								model: sequelize.models.MediaRateType,
								attributes: ['id', 'name']
							}													
						]			
					},
					onlyIds : {
						attributes :[ 'id']
					}
				},

				classMethods: {
					associate: function(models) {
						Placement.belongsTo(models.Io, {
							foreignKey: {
								allowNull: false
							},
							onDelete: 'CASCADE'
						});

						Placement.belongsToMany(models.CreativeProduct, {through: 'PlacementCreativeProducts'});
						Placement.belongsToMany(models.CustomCriteriaPreset, {through: 'PlacementCustomTargeting'});
						Placement.belongsToMany(models.Geotarget, {through: 'PlacementGeotargets'});
						Placement.belongsToMany(models.Publisher, {through: 'PlacementPublishers'});
						Placement.belongsToMany(models.DeviceType, {through: 'PlacementDeviceTypes'});
						Placement.belongsTo(models.FrequencyCap)
						Placement.belongsTo(models.MediaRateType)
						Placement.belongsTo(models.Strategy);
						Placement.belongsTo(models.SalesProduct);
						Placement.hasMany(models.DataFee);				

					}
				}

			});

			return Placement;
		};

      /********************************* ways I tired to query **********************************/
      // original query (that works but kills off all memory)
      return db.Io.scope('fullDetailWithPlacements').findOne({
		where: {
			id: id
		},
		include: [db.Advertiser]
	})

      //using getPlacements queries:
      return db.Io.scope('fullDetailWithoutPlacementsDependencies').findOne({
		where: {
			id: id
		},
		include: [db.Advertiser]
	})
	.then (function (foundIo) {
		return foundIo.getPlacements({scope: 'fullDetail'})
		.then(function (placements) {
			foundIo.Placements = placements;
			return foundIo;
		})
	});

      // using individual queries
      return db.Io.scope('fullDetailWithoutPlacementsDependencies').findOne({
		where: {
			id: id
		},
		include: [db.Advertiser]
	})
	.then (function (foundIo) {
		return Promise.props( {
			foundIo : foundIo,
			ioPlacements : Promise.map(foundIo.Placements, function (placement) {
				return db.Placement.scope('fullDetail').findOne({
					where: {
						id: id
					}
				});
			})
		});
	})
	.then (function (IoAndPlacements) {
		IoAndPlacements.foundIo.Placements = IoAndPlacements.ioPlacements;
		return IoAndPlacements.foundIo;
	})

**Comment by mickhansen** [comment]
Sequelize instances take up memory, no way around that.
Two step query might be your best here.

**Comment by DoryZi** [comment]
Thanks, but my questions is how can I make the two step queries work?
When I connect the objects after it doesn't work well anymore?
Not the same as in one query anyhow?
How can I do the equivalent?

On Tue, Dec 29, 2015 at 9:40 AM, Mick Hansen <notifications@github.com>
wrote:

> Sequelize instances take up memory, no way around that.
> Two step query might be your best here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-167839725>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi <http://is.gd/FUbJYZ>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by mickhansen** [comment]
That's really up to your implementation.

**Comment by DoryZi** [comment]
I understand. I'm having issues with getting that to work. Can someone give
me suggestions what to do? I've been stuck on this for 2 days and can't
find any examples in the docs?

**Comment by DoryZi** [comment]
I'm not trying to get anyone to do my work, just get some help at doing
this right.
I assumed it might be an issue with the memory, and I understand I need to
do a two step process.
But when I query seperately then try to join (as per my example in the
issue towards the bottom).
Certain information get's dropped when converting to JSON and calculated
fields come up messed up.
Is there a proper way to do a two step query? by one scope, the re-query on
another scope on the associated objects?
If you don't know, don't care to help, can you please direct to me where I
can find a solution for this?
Or any lead etc, I'm really stuck and could use a little pointer or
something?




On Tue, Dec 29, 2015 at 10:10 AM, Dory Zidon <dory.zidon@gmail.com> wrote:

> I understand. I'm having issues with getting that to work. Can someone
> give me suggestions what to do? I've been stuck on this for 2 days and
> can't find any examples in the docs?
> On 29 Dec 2015 19:57, "Mick Hansen" <notifications@github.com> wrote:
>
>> That's really up to your implementation.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-167844066>
>> .
>>
>


-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=8355241f-0b90-43ff-ca1d-ec9e9a277686>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by sushantdhiman** [comment]
@DoryZi  Why don't you write a raw query for both scopes and offload the work to SQL. Write raw query based Class Methods like `getFullDetailWithPlacements()` and `getFullDetailWithoutPlacementsDependencies()`.

To save some work you can copy SQL code generated by `sequelize` and modify it to a raw query.

**Comment by mickhansen** [comment]
@DoryZi What is dropped exactly? To do the query in two steps you would first fetch the first set of instances, then do a query for the second set using the relevant foreign/primary keys from the first set, then map the values together.

**Comment by DoryZi** [comment]
I will check exactly what doesn't work, I believe the toJSON generates
problematic objects.

You can see at the bottom how I attempted to do that in two different ways.
I was querying via the main objects with limited scope (to get the list of
ids on the second table) (first I query for IO with limited scope
Placements)
Then I query the second table (Placements) for individual rows with full
details, which works ok to get the element.
But how should I connect the elements back together? Just do a strait up
placement?

Please check out the code at the bottom of the issue, this is how I attempt
to join them, am I doing this wrong?



On Mon, Jan 4, 2016 at 12:37 AM, Mick Hansen <notifications@github.com>
wrote:

> @DoryZi <https://github.com/DoryZi> What is dropped exactly? To do the
> query in two steps you would first fetch the first set of instances, then
> do a query for the second set using the relevant foreign/primary keys from
> the first set, then map the values together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-168611506>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=ee46a83d-1469-4e61-c57c-76b768e51ef4>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by DoryZi** [comment]
@mickhansen I posted above what my answer, but forgot to mention you. Also I will check exactly what is not working after I try to join the two objects, can you please have a look a the code I've attached?

**Comment by DoryZi** [comment]
@sushantdhiman (sorry for the delayed response, I was away and my phone broke so I was disconnected from the world). Thanks for trying to help. I can try and do that, but wouldn't that mean I'd need to change the queries each time I add or modify a field? Also if I do raw queries can I just use the models themselves, as they are today or do I need to modify the models too to cater for raw queries?
(Meaning would I still get the same object back as in a complex query done by node sequalize)?

**Comment by DoryZi** [comment]
@sushantdhiman @mickhansen It seemed that when I query and wish to connect the object once more I have to do it in two places?
sude code:

1) Query IO with Placements with only Id scope (so no complex joins).
2) query each Placements by the ids found in the previous query (query by primary key).
3) The assign the Placements array into the io object in two places? 
IO.Placements & IO.dataValues.Placements ?
Why did I need it in both places?

**Comment by mickhansen** [comment]
I would simply convert IO to json and then add placements on top of that.

**Comment by DoryZi** [comment]
@mickhansen but why would I need that in  two places?
Sometimes I actually might need to save the object, as such it might not be the JSON representation, it's just those two places that it appears, any clue why?

**Comment by mickhansen** [comment]
Two places? Why would you?
You need to save an object after a large fetch? How do you know what to save? You can probably optimize that part.

**Comment by DoryZi** [comment]
@mickhansen Please look at my function bellow, the last promise, unless I posted the Placements in two places it didn't work, are you saying that I got something wrong if it appears in two places? Might that be my problem?


```javascript
function IoById(id) {
	return db.Io.scope('fullDetailWithoutPlacementsDependencies').findOne({
		where: {
			id: id
		},
		include: [db.Advertiser]
	})
	.then (function (foundIo) {
		return Promise.props({
			foundIo: foundIo,
			ioPlacements: Promise.map(foundIo.Placements, function (placement) {
				return db.Placement.scope('fullDetail').findOne({
					where: {
						id: placement.id
					}
				});
			})
		});
	})
	.then (function (IoAndPlacements) {
		IoAndPlacements.foundIo.Placements = IoAndPlacements.ioPlacements;
		IoAndPlacements.foundIo.dataValues.Placements = IoAndPlacements.ioPlacements;
		return IoAndPlacements.foundIo;
	});
}
```

**Comment by mickhansen** [comment]
That's because you are working with instances rather than raw data.
There's no real support for setting an include on an instance after the fact.

**Comment by DoryZi** [comment]
you mean instances of models?
and by setting an include on an instance you mean setting on a model
instance, after the first query?


On Tue, Jan 5, 2016 at 8:45 AM, Mick Hansen <notifications@github.com>
wrote:

> That's because you are working with instances rather than raw data.
> There's no real support for setting an include on an instance after the
> fact.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-169057297>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=321c73d8-3f27-452b-8502-2fe1c2f0e1e4>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by mickhansen** [comment]
Yeah model instances, what is returned from find calls etc.
Yes, normally instances only support regular values, there are logic for getting/setting includes but that is only triggered when the instance has the correct options set (which are handled internally at the moment).

**Comment by DoryZi** [comment]
oh I see, that's too bad.
I did that two assignments and everything seems to work now..

But won't raw queries work different to models?
It terms of doing saves / updates?


On Tue, Jan 5, 2016 at 8:57 AM, Mick Hansen <notifications@github.com>
wrote:

> Yeah model instances, what is returned from find calls etc.
> Yes, normally instances only support regular values, there are logic for
> getting/setting includes but that is only triggered when the instance has
> the correct options set (which are handled internally at the moment).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-169060240>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=cf1f48dd-e46e-433b-f4d0-dd28ad9cc5a5>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by mickhansen** [comment]
> But won't raw queries work different to models?

Probably, not sure i see the relation to this question though?

**Comment by DoryZi** [comment]
Well the output I would get from a raw query would be different to the
object I get from a model find query.
And if the code (as this is not my code originally) depends on it being
models somewhere in the code I will come across various issues.


On Tue, Jan 5, 2016 at 9:41 AM, Mick Hansen <notifications@github.com>
wrote:

> But won't raw queries work different to models?
>
> Probably, not sure i see the relation to this question though?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-169076940>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=bfe77e72-907e-4d0a-b8fa-6d35aa1e4b29>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by mickhansen** [comment]
True, raw queries would not necessarily return the same.

**Comment by DoryZi** [comment]
Thanks Mick for your help!
I guess I'll take my chances with the two step that now that I assigned in
two places seems to work.
If it doesn't I will try to change to raw queries.

I really appreciate your help!


On Wed, Jan 6, 2016 at 12:22 AM, Mick Hansen <notifications@github.com>
wrote:

> True, raw queries would not necessarily return the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-169264806>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=425cb20e-a247-4054-f658-ac7bf09bb003>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by DoryZi** [comment]
Mick, looks like my solution has yet to resolve the issues I'm having with
performance.
I also came across your profile on CodeMentor and I was wondering if you
would be able to dedicate a little time to help me performance tune what
going on with this crazy database and sequalize as my last resort here is
to just yank sequalize out and replace it with pure db queries, stored
procedures and views, and I'd like to avoid that if possible.

Are you free perhaps over the next few days / week to assist me in that for
a few hours (paid of course)?


On Wed, Jan 6, 2016 at 12:25 AM, Dory Zidon <dory.zidon@gmail.com> wrote:

> Thanks Mick for your help!
> I guess I'll take my chances with the two step that now that I assigned in
> two places seems to work.
> If it doesn't I will try to change to raw queries.
>
> I really appreciate your help!
>
>
> On Wed, Jan 6, 2016 at 12:22 AM, Mick Hansen <notifications@github.com>
> wrote:
>
>> True, raw queries would not necessarily return the same.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=https%3A%2F%2Fgithub.com%2Fsequelize%2Fsequelize%2Fissues%2F5110%23issuecomment-169264806&si=5024752498376704&pi=e90b0901-161f-4d5f-a78e-c8d34d48f461>
>> .
>>
>
>
>
> --
>
> Dory Zidon
> Software & Product Lead Engineer
> http://www.doryzidon.com
>
> +1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
> <http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=425cb20e-a247-4054-f658-ac7bf09bb003>
> dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
> https://www.facebook.com/doryzi
> Location: SF, NYC, TLV, CEE
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=e90b0901-161f-4d5f-a78e-c8d34d48f461>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by mickhansen** [comment]
@DoryZi I don't have time at the moment to do consulting/mentoring i'm afraid :/
But perhaps you can help me understand why you need such a large fetch?

**Comment by DoryZi** [comment]
It's a complex database that is designed in a certain way with so many
joins, an I was hoping tweaking node sequalize can make it go quicker..
can you recommend someone that can assist for a few hours to make it work
better?


On Thu, Jan 7, 2016 at 11:13 PM, Mick Hansen <notifications@github.com>
wrote:

> @DoryZi <https://github.com/DoryZi> I don't have time at the moment to do
> consulting/mentoring i'm afraid :/
> But perhaps you can help me understand why you need such a large fetch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-169914102>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=be5d144b-ddd6-49f4-c8a6-265771792f1a>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE

**Comment by mickhansen** [comment]
Not sure, maybe someone will turn up :)
A workaround could be paging the query and doing it in a few goes?

**Comment by DoryZi** [comment]
The problem noda sequalize generates 5,000 and sometimes 256K rows
returned, but at the end we only have like 220 object (with other contained
objects).
So I'm not sure why it does that or why it doe that or why would paging
help me..


On Fri, Jan 8, 2016 at 8:10 AM, Mick Hansen <notifications@github.com>
wrote:

> Not sure, maybe someone will turn up :)
> A workaround could be paging the query and doing it in a few goes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5110#issuecomment-170043028>
> .
>



-- 

Dory Zidon
Software & Product Lead Engineer
http://www.doryzidon.com

+1 415 799 7865 | +1 415 324 0696 | Skype: doryzi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsdntGCN643W9MRYQh0W8pTc_456dJqNf8KTlFx02?t=http%3A%2F%2Fis.gd%2FFUbJYZ&si=5024752498376704&pi=0136a1f8-f631-47d0-ab82-4209b308e11e>
dory.zidon@gmail.com | Linkedin: http://goo.gl/39r2py  | Facebook:
https://www.facebook.com/doryzi
Location: SF, NYC, TLV, CEE
