### ISSUE TITLE
How to find distinct rows in a table including associations

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#5121]
Hi,

I'm trying to query for distinct values of a column with a where clause that references associations.

For example:
```
SomeModel.aggregate('some_col', 'DISTINCT', {
  plain: false,
  include: {
    model: SomeOtherModel,
    where: { foo: true },
    include: {
      model: YetAnotherModel,
      where: { bar: false }
    }
  }
})
```

This kind of query produces the following error: `Cannot read property 'association' of undefined`

Is there another way to achieve this? Or some way to fix the above example?

Thanks!

**Comment by Verdier** [comment]
This is fixed by PR #5106.

**Comment by mickhansen** [comment]
`include` should be an array.

**Comment by Verdier** [comment]
Even with an array, without #5106 this is not working
