### ISSUE TITLE
Can not get multi result when using stroed procedure with sequelize 3.15.1

### ISSUE THREAD

**Issue by wangcheng911** [sequelize/sequelize#5122]
I have the problem as same as https://github.com/sequelize/sequelize/issues/2747,
and my sequelize version is  3.15.1
but 
janmeier commented on 8 Apr :
This is fixed in latest master

my code is same to https://github.com/sequelize/sequelize/issues/2747,

the bug has been not fixed or some error in my code?
can you help me?

**Comment by mickhansen** [comment]
Please add the actual code your running, the stored procedure, the dialect, etc. I don't image that everything in your case is the same as the other issue.
