### ISSUE TITLE
Model file is not a valid model

### ISSUE THREAD

**Issue by ravinggenius** [sequelize/sequelize#5125]
Sequelize is rejecting my model definition, but doesn't explain why. No error is raise, but the model isn't available after the server starts. `sync()` only prints a line to the console: `<full/path/to/model.js> is not a valid model`. I tried searching the source code for "not a valid model", but came up empty-handed. How can I fix the issue without knowing what it is?

The model definition in full is below:

```javascript
'use strict';

module.exports = function (sequelize, DataTypes) {
	return sequelize.define('Slug', {
		id: DataTypes.INTEGER,
		key: DataTypes.STRING,
		expansion: DataTypes.STRING
	}, {
		timestamps: true,
		paranoid: true
	});
};
```

**Comment by foobar8675** [comment]
try this

````
module.exports = function (sequelize, DataTypes) {
	return sequelize.define('Slug', {
		id: {
			type: DataTypes.INTEGER,
			primaryKey: true
		},
		key: DataTypes.STRING,
		expansion: DataTypes.STRING
	}, {
		timestamps: true,
		paranoid: true
	});
};
````

**Comment by ravinggenius** [comment]
Sorry @foobar8675, I didn't see your answer. I kept poking at it and finally got something working. I noticed my original request for help was defining the types incorrectly, so I fixed the question, but I never fixed the real code. Anyway I also wanted to use UUIDs instead of integer ids, and I got that working too. Below is my model as it stands now. Everything seems to be working.

```javascript
'use strict';

module.exports = function (sequelize, DataTypes) {
	return sequelize.define('Slug', {
		id: {
			type: DataTypes.UUID,
			defaultValue: DataTypes.UUIDV4,
			primaryKey: true
		},
		key: {
			type: DataTypes.STRING
		},
		expansion: {
			type: DataTypes.STRING
		}
	}, {
		tableName: 'slugs',
		timestamps: true,
		paranoid: true
	});
};
```
