### ISSUE TITLE
postgres json columns not saving

### ISSUE THREAD

**Issue by foobar8675** [sequelize/sequelize#5127]
I think I found an issue. I have a postgres json column where I update the json and see the save does not actually save anything.
````
user.meta.resetPasswordToken = uuid.v4();
user.meta.resetPasswordExpires = Date.now() + 12*3600000;
return user.save();
````

however, if i update a text column, I see the text column update , but not the json one.
````
user.meta.resetPasswordToken = uuid.v4();
user.meta.resetPasswordExpires = Date.now() + 12*3600000;
user.email = "a@b.com"
return user.save();
````

finally, if i reset the collection, it saves fine.
````
user.meta.resetPasswordToken = uuid.v4();
user.meta.resetPasswordExpires = Date.now() + 12*3600000;
user.meta = _.clone(user.meta);
return user.save();
````

**Comment by mickhansen** [comment]
Use `user.set('meta.resetPasswordToken', uuid.v4())` etc and it should work properly.
