### ISSUE TITLE
Using a class method to log queries throws an error

### ISSUE THREAD

**Issue by bored** [sequelize/sequelize#5131]
Hello, I created a class that logs everything happens on my server and I'd like to use it to log queries that Sequelize creates, but I get an error:
``` sh
$ node sequelize.test.js
start - Amazing!!!
query - littleQuery
Unhandled rejection TypeError: Cannot read property 'write' of null
    at query (sequelize.test.js:13:7)
    at Sequelize.log (node_modules/sequelize/lib/sequelize.js:1283:21)
```
This is the test I used: https://gist.github.com/bored/6d7e4e86354af126d84e
As you can see the logger works until `log.query()` is called by Sequelize, the line that throws the error is part of this if statement https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1277-L1284. It seems that the function loses its context, note that if I replace `options.logging.apply(null, args)` with `options.logger('hi')` throws the same error.
What's the cause of the error?

Uh, another thing, [this if statement](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1278-L1281) is the same as [this one](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L161-L164), am I missing something?

**Comment by mickhansen** [comment]
We have no way to maintain context internally, you should use `bind`.
The if statements are the same because one deals with having a default sequelize value and the other deals with per call values.
