### ISSUE TITLE
findOrCreate inserts but throws a SequelizeUniqueConstraintError (MySQL)

### ISSUE THREAD

**Issue by okankaya** [sequelize/sequelize#5134]
In the example findOrCreate is inserting to the table when the record doesn't exist, but then throw a SequelizeUniqueConstraintError. I was expecting it to rollback in this case since this is supposed to be a single commit, but it doesn't. 

```
var Users = sequelize.define("users", {
      user_id: { type: DataTypes.INTEGER, primaryKey: true },
      s_id: { type: DataTypes.STRING(32) },
      pname: { type: DataTypes.STRING(255) },
      enabled: { type: DataTypes.BOOLEAN }
    },
    {
      indexes: [
        {
          unique: true,
          fields: ['s_id']
        }
      ]
    }
  );
```

```
models.users.findOrCreate({ where: { s_id: sid }, defaults: { pname: pname, enabled: 1 } })
        .spread(function(user, created) {
            console.log(created);
            return done(null, user);
        })
```

When above code is executed, it executes the following SQL queries:

```
Executing (3f6d778b-99d4-4d42-a6ed-17670629cb8c): START TRANSACTION;
Executing (3f6d778b-99d4-4d42-a6ed-17670629cb8c): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (3f6d778b-99d4-4d42-a6ed-17670629cb8c): SET autocommit = 1;
Executing (3f6d778b-99d4-4d42-a6ed-17670629cb8c): SELECT `user_id`, `s_id`, `pname`, `enabled` FROM `users` AS `users` WHERE `users`.`s_id` = '1234567890' LIMIT 1;
Executing (3f6d778b-99d4-4d42-a6ed-17670629cb8c): INSERT INTO `users` (`user_id`,`s_id`,`pname`,`enabled`) VALUES (NULL,'1234567890','name',true);
Executing (3f6d778b-99d4-4d42-a6ed-17670629cb8c): SELECT `user_id`, `s_id`, `pname`, `enabled` FROM `users` AS `users` WHERE `users`.`s_id` = '1234567890' LIMIT 1;
Executing (3f6d778b-99d4-4d42-a6ed-17670629cb8c): COMMIT;
```

Logged error message is as follows:

```
{ [SequelizeUniqueConstraintError: Validation Error]
  name: 'SequelizeUniqueConstraintError',
  message: 'Validation Error',
  errors: {},
  fields: undefined }
```

When the above insert statement is executed on the database directly, record is being inserted without an issue.

**Comment by okankaya** [comment]
Did some more digging. user_id field is set to auto_increment in the database, but wasn't configured that way in the model. 

Error was gone after updating the model, but I still suggest the idea it should rollback when it throws an Unique Constraint Exception.

**Comment by nofelmahmood** [comment]
I am facing the same issue. Creation succeds but also gives a SequelizeUniqueConstraintError. 
Anybody here you has found a solution ?

**Comment by okankaya** [comment]
If it is due to the id field being set to auto increment, setting the field's auto increment property on your model fixes it.

Example:
`tableID: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      field: 'table_id'
    }`

**Comment by zackfly** [comment]
@okankaya  thanks a lot  ,your way works well ,this problem almost drive me crazy .

**Comment by zackfly** [comment]
@okankaya  thanks ,you save me !

**Comment by nandeshnair** [comment]
Hello!
I am facing a similar issue. I have a User model with id as primary key which is set to auto increment. This model also has a unique key which is "username". I am using the findOrCreate method to create or lookup a user based on the "username" field. My code creates a record if it does not exist but throws a UniqueConstraintError (ER_DEP_ENTRY) --> SequelizeUniqueContraintError on the "username"  field when I try to find this record. Basically the findOrCreate tries to create a record for the second time instead of finding it.

**Comment by charlieargue** [comment]
I am also experiencing the same issue as @nandeshnair:
`Basically the findOrCreate tries to create a record for the second time instead of finding it.`

Error msg:
```
{
  "name": "SequelizeUniqueConstraintError",
  "errors": [
    {
      "message": "uniqueApprovalActionNeedAllTheseFields must be unique",
      "type": "unique violation",
      "path": "uniqueApprovalActionNeedAllTheseFields",
      "value": "16, req, approve, 6541, objcodeapproval, objcode, 5200, 1.0957, 0"
    }
  ],
  "fields": {
    "uniqueApprovalActionNeedAllTheseFields": "16, req, approve, 6541, objcodeapproval, objcode, 5200, 1.0957, 0"
  },
  "parent": {
    "message": "Violation of UNIQUE KEY constraint 'uniqueApprovalActionNeedAllTheseFields'. Cannot insert duplicate key in object 'dbo.approval_action'. The duplicate key value is (16, req, approve, 6541, objcodeapproval, objcode, 5200, 1.0957, 0).",
    "code": "EREQUEST",
    "number": 2627,
    "state": 1,
    "class": 14,
    "serverName": "KALEIKALANA81E6",
    "procName": "",
    "lineNumber": 1,
    "sql": "INSERT INTO [approval_action] ([patientType],[patientValue],[priceOrAmount],[itemId],[outcomeType],[documentType],[documentId],[approverUserAccountId],[action],[selfApproved],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'objcode',N'5200',1.09574972,N'0',N'objcodeapproval',N'req',6541,16,N'approve',1,N'2018-03-17 04:58:12.000 +00:00',N'2018-03-17 04:58:12.000 +00:00');"
  },
  "original": {
    "message": "Violation of UNIQUE KEY constraint 'uniqueApprovalActionNeedAllTheseFields'. Cannot insert duplicate key in object 'dbo.approval_action'. The duplicate key value is (16, req, approve, 6541, objcodeapproval, objcode, 5200, 1.0957, 0).",
    "code": "EREQUEST",
    "number": 2627,
    "state": 1,
    "class": 14,
    "serverName": "KALEIKALANA81E6",
    "procName": "",
    "lineNumber": 1,
    "sql": "INSERT INTO [approval_action] ([patientType],[patientValue],[priceOrAmount],[itemId],[outcomeType],[documentType],[documentId],[approverUserAccountId],[action],[selfApproved],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'objcode',N'5200',1.09574972,N'0',N'objcodeapproval',N'req',6541,16,N'approve',1,N'2018-03-17 04:58:12.000 +00:00',N'2018-03-17 04:58:12.000 +00:00');"
  },
  "sql": "INSERT INTO [approval_action] ([patientType],[patientValue],[priceOrAmount],[itemId],[outcomeType],[documentType],[documentId],[approverUserAccountId],[action],[selfApproved],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'objcode',N'5200',1.09574972,N'0',N'objcodeapproval',N'req',6541,16,N'approve',1,N'2018-03-17 04:58:12.000 +00:00',N'2018-03-17 04:58:12.000 +00:00');"
}

```
• db (sql server) unique constraint attached
• schema file attached as well

Thanks!
![carbon](https://user-images.githubusercontent.com/16597829/37551868-6d4f2c20-2966-11e8-9efe-f17ff75a32eb.png)


<img width="1680" alt="db-unique-constraint-sql-server" src="https://user-images.githubusercontent.com/16597829/37551859-3a537772-2966-11e8-9676-eb1258a087f9.png">

**Comment by nandeshnair** [comment]
@charlieargue Hi Karl! 

Can you please share your findOrCreate method call as well?

**Comment by stephenjesus** [comment]
Model.upsert({
    title:your title,
    desc:your description,
    location:your locations
}).then(function (test) {
    if(test){
        res.status(200);
        res.send("Successfully stored");
    }else{
        res.status(200);
        res.send("Successfully inserted");
    }
})
