### ISSUE TITLE
Can not create relations in postgres due to race condition

### ISSUE THREAD

**Issue by SerjoPepper** [sequelize/sequelize#5135]
Hello.
I have to models:
`User` and `Like`
`Like` model has `belongsTo` relation with `User`
`Like` model syncs first, `User` second
So I have this error:
```
'CREATE TABLE IF NOT EXISTS "likes" ("id"   SERIAL , "type" "public"."enum_likes_type", "entity" VARCHAR(30), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "userId" INTEGER REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "RelatedUserId" INTEGER REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));'
``` 

This means that relation is created BEFORE the `users` table is created (I check it). Why? I think that relations must created after all tables sync. How can I do it? Or how can I avoid this error. Thanks.

**Comment by janmeier** [comment]
Are you using sequelize.sync? In that case the correct order should be identified automatically

**Comment by SerjoPepper** [comment]
OK, understand. But what will happen if models has two-way relations? And second question: how can I add relations in migrations (add foreign key later).

**Comment by mickhansen** [comment]
@SerjoPepper Sequelize can't handle two way constraints in sync() at the moment.

**Comment by SerjoPepper** [comment]
@mickhansen OK, understand. So I have manually create this relations (with raw queries), right?
What about creation the relation in migrations? How should I work with it?

**Comment by mickhansen** [comment]
I don't believe we currently have migration helpers for creating foreign keys.
A raw query is probably the way to go.
