### ISSUE TITLE
associating table to itself

### ISSUE THREAD

**Issue by realisation** [sequelize/sequelize#5136]
I have a table trees which is self referential via column parent which refers to other rows within this table. 

I'm having difficulty giving the sequelize model a self referential association so that I may query it & include all children trees underneath their parent trees. 

I've tried a few things --- 

    m.Trees.hasMany(m.Trees, { as: 'childrenTrees', foreignKey: 'parent' });
    m.Trees.belongsTo(m.Trees, { as: 'childrenTrees', foreignKey: 'id' });

Also tried that w/ switching the foreign keys. 

Also have tried a belongsToMany approach: 
   
       m.Trees.belongsToMany(m.Trees, { as: 'childrenTrees', through: 'childrenTrees', foreignKey: 'id' });

None of it seems to work. I always get an error like Topics is not associated with Topics.

I'm writing it like Trees.find({ where: {thing: thing}, include: [ Trees ])

Or include: [childrenTrees]. In which case it says childrenTrees is not defined.

**Comment by mickhansen** [comment]
When using `as` on an association definition you need to use it on the include aswell.

```js
Trees.find({ where: {thing: thing}, include: [ {model: Trees, as: 'childrenTrees'} ])
```
