### ISSUE TITLE
Including table through relational table without including the relational table

### ISSUE THREAD

**Issue by realisation** [sequelize/sequelize#5137]
I have a relational table that ties two other tables together for a many to many relationship. 

BonoboIslands has a column Bonobo which is the ID of the table Bonobos, as well as a column Islands which is the ID of the table Islands.

I'd like to be able to query either of them with a .find, include the other model, and get all references to the other model in that include.

Right now I'm doing a double include, which still sort of works, yet obviously isn't ideal.

I've tried to relate them to eachother in a many to many fashion with .belongsToMany like so: 
    m.Bonobos.belongsToMany(m.Islands, { as: 'findIslands', through: 'BonoboIslands', foreignKey: 'bonobos' });
    m.Islands.belongsToMany(m.Bonobos, { as: 'findBonobos', through: 'BonoboIslands', foreignKey: 'islands' });

Both of these give me 'findIslands' or 'findBonobos' is not defined. 

Thank you for any help - I have looked through the docs a lot & it doesn't seem to be covered.

**Comment by mickhansen** [comment]
> Both of these give me 'findIslands' or 'findBonobos' is not defined.

When do they do that exactly?

**Comment by realisation** [comment]
When including the alias in a query method like so:

    Bonobos.findAll({
        where: {
            name: 'sandy'
        },
        include: [ findIslands ]
    }).then(function(result){
        res.send(result);
    });

with the relation defined as 
       m.Bonobos.belongsToMany(m.Islands, {as: 'findIslands', through: 'BonoboIslands', foreignKey: 'bonobos' });


Also, I made another post about not being able to associate a table to itself? What happened to that one?

**Comment by mickhansen** [comment]
I answered the other post and closed it, check your notifications.
`include: [ findIslands ]` what does the variable findIslands refer to here?

**Comment by realisation** [comment]
Ah, thank you! Notifications aren't very obvious on here.

`include: [ findIslands ]` refers to the `as` specification in `m.Bonobos.belongsToMany(m.Islands, {as: 'findIslands', through: 'BonoboIslands', foreignKey: 'bonobos' });`

I take it that's incorrect?

**Comment by mickhansen** [comment]
We don't allow association looks by string at the moment, but in that case it would still have to be `include: ['findIslands']`.

However we do allow lookup by association reference:

```js
m.Bonobos.findIslands = m.Bonobos.belongsToMany(m.Islands, {as: 'findIslands', through: 'BonoboIslands', foreignKey: 'bonobos' });

m.Bonobos.findAll({
  include: [m.Bonobos.findIslands]
});
```
