### ISSUE TITLE
Count documentation isn't very clear

### ISSUE THREAD

**Issue by mazzy89** [sequelize/sequelize#5139]
According to the documentation to use `count` in order to look for distinct entries we need to add `distinct: true`. Unfortunately it is not very clear which column it refers to. How to define the column to consider for the distinction?

**Comment by janmeier** [comment]
Currently the column will always be the primary key, see https://github.com/sequelize/sequelize/blob/433e25f65a89e310cee827097c3b7306cb905068/lib/model.js#L1564-L1588

You could use aggregate to count other coluns
