### ISSUE TITLE
Introduce IP address Data Type

### ISSUE THREAD

**Issue by slavafomin** [sequelize/sequelize#5140]
Hello!

Thank you for this great module! It's amazing.

However, please consider introducing an IP address data type. Some databases, e.g. MySQL, allows you to store IP addresses as compact integer values and provides special functions to convert IP address from string to integer and back again. PostgreSQL even has a special underlying data type.

Right now I will have to manually convert IP address in my Model's getters and setters.

Thank you!

**Comment by ajmas** [comment]
Just to try to summarize supported databases and data types they offer for this. Note that implementation should be mindful of both IPv4 and IPv6. As a generalised case IPv4 can be treated as an IPv6 address, by zeroing about the first 12 bytes. 
  
   - MySQL:  VARBINARY(16) or BINARY(16), [see here](http://www.rdeeson.com/weblog/168/updating-mysql-and-php-to-store-ipv6-addresses.html)
   - MariaDB: same as MySQL (did not see any new [data types](https://mariadb.com/kb/en/mariadb/data-types/))
   - PostgreSQL: [inet/cidr](http://www.postgresql.org/docs/9.1/static/datatype-net-types.html)
   - SQLite: unsure ([data types](https://www.sqlite.org/datatype3.html))
   - MSSQL: unsure, though maybe [this page ](https://msdn.microsoft.com/en-us/library/ms191530.aspx)as a starting point?

BTW is MSSQL the same as SQL Server?

This was the result of 10 minutes of research, so please update as appropriate.

**Comment by janmeier** [comment]
Yep, mssql == sql server

It would probably make sense to use the [inet](https://www.npmjs.com/package/inet) package to convert data to / from binary

**Comment by ajmas** [comment]
The inet package does not support IPv6. I'll put in a feature request. In the meantime, though we just need to be sure that the output of the operations are compatible with the equivalent functions that a given database might support.

**Comment by ajmas** [comment]
BTW while a larger, the ip-address package looks like it could also do the job?

**Comment by gzldx** [comment]
so use varchar 45 to store an ip address?
ip: {
      type: DataTypes.STRING(45),
      allowNull: false,
      defaultValue: ''
},

**Comment by ajmas** [comment]
Based on what I have read a string of 45 characters should be good, since it will support the mixed IPv6::IPv4 notation.

**Comment by shtse8** [comment]
Any updates?

**Comment by gabegorelick** [comment]
This was added to Sequelize in v4.38.0. See https://github.com/sequelize/sequelize/pull/9571.
