### ISSUE TITLE
Release 3.12.0 breaks specifying a schema (uses public instead)

### ISSUE THREAD

**Issue by jfkoch** [sequelize/sequelize#5141]
My model breaks between 3.11 and 3.12. I have included my index model and an example model which specifies a schema other than public. 

************************************************model index.js*****************************************************
'use strict'

const config = require('config')
const fs = require('fs')
const path = require('path')
const Sequelize = require('sequelize')

const postgresUsername = config.get('postgresUsername')
const postgresPassword = config.get('postgresPassword')
const postgresHostname = config.get('postgresHostname')
const postgresDatabaseName = config.get('postgresDatabaseName')

const sequelize = new Sequelize('postgres://' + postgresUsername + ':' + postgresPassword + '@' + postgresHostname + '/' + postgresDatabaseName, {
  logging: config.get('logging')
})

let db = {}

fs
  .readdirSync(__dirname)
  .filter(function (file) {
    return (file.indexOf('.') !== 0) && (file !== 'index.js')
  })
  .forEach(function (file) {
    var model = sequelize.import(path.join(__dirname, file))
    db[model.name] = model
  })

Object.keys(db).forEach(function (modelName) {
  if ('associate' in db[modelName]) {
    db[modelName].associate(db)
  }
})

db.sequelize = sequelize
db.Sequelize = Sequelize

module.exports = db

********************************************modelSmfUserHistory********************************************
'use strict'

const config = require('config')

module.exports = function (sequelize, DataTypes) {
  let SmfUserHistory = sequelize.define('SmfUserHistory', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false
    },
    ver: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    uid: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    nid: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    extra_nid: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    created: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    updated: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    processed: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    last_played: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    position: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    join_ms: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    watched: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    paused: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    seekcount: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    client_uid: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    location: {
      type: DataTypes.TEXT,
      allowNull: false,
      defaultValue: 'null'
    },
    hostname: {
      type: DataTypes.CHAR(128),
      allowNull: false
    },
    irdeto_code: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    irdeto_msg: {
      type: DataTypes.TEXT,
      allowNull: false,
      defaultValue: 'null'
    },
    type: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    user_agent: {
      type: DataTypes.TEXT,
      allowNull: false,
      defaultValue: 'null'
    },
    bad: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    embed_player_ms: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    switch_media_ms: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    player_ready_ms: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    bc_code: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    bc_msg: {
      type: DataTypes.TEXT,
      allowNull: false,
      defaultValue: 'null'
    },
    ign: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    }
  },
    {
      tableName: 'smfplayer_user_history'
    })

  SmfUserHistory.schema('drupal')       <----- THIS LINE SEEMS TO BE IGNORED AFTER 3.12

  let consumerEnables = config.get('consumerEnables')
  if (consumerEnables.consumerSmfUserHistory) {
    SmfUserHistory.sync()
  }

  return SmfUserHistory
}

**Comment by janmeier** [comment]
Please use github flavored markdown next time ;-)

The reason it worked before is because of a bug where calling schema would leak the schema option into the parent model 

You should either add schema to the options object (where you already have table name) or call sync on the model returned by `.schema`

As a side note it's probably not safe to call sync in the model file, without waiting for it to finish. You might potentially try to query the table before it exists
