### ISSUE TITLE
Changes made in beforeCreate hook are not persisted to the database

### ISSUE THREAD

**Issue by slavafomin** [sequelize/sequelize#5142]
Hello there!

I have an issue where changes made in `beforeCreate` hook are not saved to the database.

```javascript

console.log('Session.build()');
var session = Session.build({
  ipAddress: req.clientIp
});

console.log('setUser()');
session.setUser(user);

console.log('save()');
session.save();

```

```javascript

hooks: {
  beforeCreate: function (session) {

    console.log('Session.beforeCreate()');

    // Auto-generating token.
    // @todo: make sure it's unique
    session.token = randomstring.generate();

    console.log('Token set to: ' + session.token);

    // Setting default expiration time.
    if (!session.expiresAt) {
      session.expiresAt = new Date();
      console.log('Expiration set to: ' + session.expiresAt);
    }

  }
},

```

And here's the log:

```
Session.build()
setUser()
save()
Session.beforeCreate()
Token set to: usvnC9z76VNAJcCtch
Expiration set to: Tue Jan 05 2016 23:48:14 GMT+0300 (MSK)
Executing (default): INSERT INTO "sessions" ("userId","updatedAt","createdAt") VALUES (1,'2016-01-04 20:48:14.710 +00:00','2016-01-04 20:48:14.710 +00:00');
```

Is it related to #3534 and #4837?

---

Sequelize version: **3.15.1**
Node version: **5.3.0**

**Comment by mickhansen** [comment]
Both those issues relate to validation hooks, so not related.
Code here should work, does it workif you incldue token/expiresAt in `fields` explicitely?

**Comment by slavafomin** [comment]
I'm sorry, I've already rewritten this part of the program, we are trying to keep up the pace. I've tried that approach (i.e. providing fields option), but as far as I remember it didn't help.

**Comment by Verdier** [comment]
@slavafomin if you need to debug, here is the code https://github.com/sequelize/sequelize/blob/75b63d861b3db1fe63135d5bd52a443544de3ae9/lib/instance.js#L582, should work.
