### ISSUE TITLE
Make association accessors chainable?

### ISSUE THREAD

**Issue by slavafomin** [sequelize/sequelize#5143]
Hello!

Why don't we make association accessors chainable? It will allow us to write code like this:

```javascript
return Session
  .build({
    // ...
  })
  .setUser(user)
  .save()
;
```

Right now I have to write it like this:

```javascript
var session = Session.build({
  // ...
});
session.setUser(user);
return session.save();
```

which is somewhat cumbersome.

**Comment by sushantdhiman** [comment]
This is because  `setUser()` and `save()` returns a `promise` so you can do some work after each step. I think making them chainable will break many things. Like this

```
var sessionObj = Session.build({});

sessionObj.setUser(user).then(function(){
   // notify others about new user via Web socket maybe
});

sessionObj
  .save()
  .then(function(){
     //redirect to the homepage
  });
```

If we chain them it will be difficult to do same. Also You can handle errors for each step separately and take different action. That will not be possible after chanining them.

**Comment by mickhansen** [comment]
Sequelize is primarily async which makes chaining hard, however tap can achieve a lot of what you want.

```js
Promise.resolve(Session.build({}).tap(function (session) {
  // using tap does not change the value of the parent promise chain / the next then
  return session.setUser(user);
}).then(function (session) {
  return session.save();
});
```

**Comment by slavafomin** [comment]
Hmm, I see. Thank you for an example. But why does `setUser()` return a promise? Isn't it a synchronous operation?

**Comment by mickhansen** [comment]
setUser is asynchronous unless you use `save: false` in a belongsTo relation.
But even when it's not actually saving to the database it still returns a promise to keep the API consistent

**Comment by slavafomin** [comment]
Right, now I understand this. I had no idea that setter method will also save the model by default. It is somewhat counter-intuitive and looks like is not fully documented. I've stumbled into a nasty bug because of this = )

Is there an option to disable such *saving* behavior globally for an entire application? I prefer to do it explicitly, especially when setter is called after `build()` and instance is not yet fully constructed. Probably such behavior complicates Sequelize API as well, maybe we shouldn't do it. I think `save()` as a single point of entity persistence is a very good and straightforward thing.

P/S: I wanted to thank you for your hard work and for taking the time to answer all my silly questions. It's very nice to see such a great support for an important library like this. Keep up the good work!

**Comment by sushantdhiman** [comment]
Do you want to turn off the async mode in sequelize. Because every method that hits database will return promise. This implementation will be against node async nature and will create more confusion.

**Comment by mickhansen** [comment]
@slavafomin I can imagine it might not be totally obvious, but pretty much all methods are async and do something by default.

We don't have any way to set the default option for something like that.

You might be interesting in https://github.com/sequelize/sequelize/issues/4639
