### ISSUE TITLE
Automatic creation of inverse side of bidirectional relationships

### ISSUE THREAD

**Issue by slavafomin** [sequelize/sequelize#5144]
Hello!

Thank you for your great work!

However, I'm new to Sequelize and right now it's association configuration looks somewhat counter-intuitive to me. I've used Doctrine before that for PHP. The corresponding documentation is also pretty difficult to read.

I'm trying to setup a bidirectional association between two models. Let's call them `User` and `Order`. After some time figuring out the difference between `hasOne`, `belongsTo` and `hasMany` associations types I've came up with the following config:

``` javascript

User.hasMany(Order, {
  foreignKey: 'userId',
  onDelete: 'CASCADE',
  hooks: true
});

Order.belongsTo(User, {
  foreignKey: 'userId',
  onDelete: 'CASCADE',
  hooks: true
});

```

With such configuration I'm getting the correct database structure, foreign keys, accessor methods and such, however I have to duplicate options, i.e.: `foreignKey`, `onDelete` and `hooks` in both models. In other case I'm getting two foreign keys with different names or cascade is not set correctly.

Could you tell me if I'm doing something wrong? Or is it an actual issue with Sequelize?

In Doctrine there is a concept of _owning side_ of the association and all options are defined only on one side of it, not on both.

Thank you!

**Comment by mickhansen** [comment]
It's a requirement at the time since associations don't know about eachother.
Something i'd love to change but not quite sure how since users would still like do define aliases and stuff.

Perhaps a way to define that a relation in the inverse of another.

```js
User.Orders = User.hasMany(Order, {
  foreignKey: 'userId',
  onDelete: 'CASCADE',
  hooks: true
});

Order.belongsTo(User, {
  inverse: User.Orders,
  as: 'users'
});
```

**Comment by Verdier** [comment]
+1 looks good ! Every time I create a relation, I ask my self about that... It's hard to predict what will take precedence (mostly for `CASCADE`).

**Comment by slavafomin** [comment]
@mickhansen that looks good to me too. Doctrine solves this problem in the similar fashion.

As an alternative idea, maybe we could use just a single definition instead of two:

```javascript
User.hasMany(Order, {
  foreignKey: 'userId',
  onDelete: 'CASCADE',
  hooks: true,
  inverse: true // Will add singular mixins on target
});
```

However, I think that two definitions are more explicit, which is good in my opinion.

**Comment by mickhansen** [comment]
@slavafomin That would work aswell in cases where no alias is defined for the relation.

**Comment by Verdier** [comment]
@mickhansen we could imagine something like that:
```
User.hasMany(Order, {
  foreignKey: 'userId',
  onDelete: 'CASCADE',
  hooks: true,
  inverse: 'owner' // Will add singular mixins on target
});
```

**Comment by mickhansen** [comment]
@Verdier That could definitely work!

Then the user can include via `[User]` or `{model: User, as: 'owner'}` or perhaps in cases of:

```
User.Orders = User.hasMany(Order, {
  foreignKey: 'userId',
  onDelete: 'CASCADE',
  hooks: true,
  inverse: 'owner' // Will add singular mixins on target
});

Order.Owner = User.Orders.inverse

include: [Order.Owner]
```

**Comment by Verdier** [comment]
I think that include should remain as before (in a first time) `{model: User, as: 'owner'}`. It's just sugar.

We could just create the opposite in hasMany (and the other):
```js
hasMany = function(model, options)
 ...
 if (options.inverse) {
  inverseOptions = _.cloneDeep(options);
  delete inverseOptions.inverse;
  if(_.isString(options.inverse) inverseOptions.as = options.inverse;
  /* What about the foreignKey and the scope ? */
  model.belongsTo(this, inverseOptions);
 }
 ...
}

**Comment by Verdier** [comment]
@mickhansen we could also have more options:
```js
User.Orders = User.hasMany(Order, {
  foreignKey: 'userId',
  onDelete: 'CASCADE',
  hooks: true,
  inverse: {
   as: 'owner',
   scope: {}
  }
});
```

**Comment by mickhansen** [comment]
@Verdier Well we already have support for including by association reference, so this would just be exposing the inverse relation.

Yeah inverse taking an object also makes sense :)

**Comment by Verdier** [comment]
Yep, that's true and good for inverse association reference. What about the name `inverse`, `reverse`, `opposite`?

**Comment by mickhansen** [comment]
Not sure what is best, `inverse` is something that produces the reverse of a product, so it makes sense as an "action".

All three have the same meaning. Inverse might be harder for non-english proficients.

**Comment by Verdier** [comment]
Agree that `inverse` is for action, it's why it's not fully appropriate here.

**Comment by Verdier** [comment]
There is also some question about what we preset in the opposite association by default, such as the `hook` property.

**Comment by mickhansen** [comment]
The defaults should be what's defined on the "parent" relationship i think, that would generally make sense in all cases i believe.

`hooks` has no effect on belongsTo so would really only ever be specified on the hasMany side.

**Comment by Verdier** [comment]
Is there a property which needs to be set in the opposite relation... ? Other that the potential `as` or the options passed to `inverse`.

**Comment by mickhansen** [comment]
I don't believe so.

**Comment by overlookmotel** [comment]
I also raised the same kind of issue at #6091 (should have noticed this was here first).

**Comment by overlookmotel** [comment]
Anyone interested in the defining of associations, please also see: https://github.com/sequelize/sequelize/issues/6023#issuecomment-225442087

**Comment by overlookmotel** [comment]
Still seems like a good idea to me.
