### ISSUE TITLE
Sync raw query

### ISSUE THREAD

**Issue by kimthangatm** [sequelize/sequelize#5145]
Because my models need field `unique string with 6 character`, so I want `sync query` to check unique field.

**Comment by mickhansen** [comment]
I'm not sure what you need here exactly but you can define an attribute with the type VARCHAR(6) and have unique: true

**Comment by kimthangatm** [comment]
Hi @mickhansen. Thank you for support. 

I had write example:

```javascript
function checkUniqueKey(str) {
    //Check unique key exists
    var record = '...'//SELECT id FROM properties WHERE key = str LIMIT 1;
    return record ? 1 : 0;
}

var data = {};
var uniqueKey = generateToken(6);
while (checkUniqueKey(uniqueKey) == false) {
    uniqueKey = generateToken(6);
}

data.key = uniqueKey;
properties.create(data).then(function () {
    ///
});
```

**Comment by mickhansen** [comment]
Why not just use a regular unique constraint?
If you absolutely want a custom check you should use a beforeCreate hook

**Comment by kimthangatm** [comment]
Because I want auto generate unique key as Youtube Link `ep2YoVQoy4Y`: https://www.youtube.com/watch?v=ep2YoVQoy4Y And Unique key must 6 character.

On beforeCreate, because Query in sequelize is Async and While(checkUniqueKey(,,,,)) incorrect

**Comment by janmeier** [comment]
Then wrap the while look in a promise that is resolved when the while loop is done

```js
new Promise(function (resolve) {
  while (checkUniqueKey(uniqueKey) == false) {
    uniqueKey = generateToken(6);
  }
  resolve();
});

**Comment by mickhansen** [comment]
@janmeier Not exactly the issue here, his lookup code is async.
@kimthangatm Well you'll have to write code that deals with doing a continous async lookup.
