### ISSUE TITLE
Allow get/set for internal createdAt/updatedAt/deletedAt to be defined when creating Sequelize instance

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#5147]
I have a decorator I use to make the date columns I use work with moment.

``` js
@momentProperty
expiresAt: {
    type: DataTypes.DATE,
    allowNull: true
},
```

(It basically turns the object into one containing a mandatory DATE type, get, and set function)

The problem however is `createdAt` and `updatedAt`. I can write all my date code using moment. But then the moment I want to read `createdAt` I now have a Date object that violates the `*At = moment(*)` pattern that all my models follow.

I think it would be worthwhile to allow getters and setters to be defined for the internal properties. Only a little bit of internal code actually uses these columns and it's possible to refactor them to use raw `this.{get,set}DataValue`.

**Comment by dantman** [comment]
Ok I did some more digging into the code and testing Sequelize's behaviour and discovered:
* Internal code doesn't `get` and already seems to use `raw` values, so applying getters and setters to these props doesn't seem to make a difference
* These props 'can' be overridden by defining them, so it is possible to give them moment schemantics

The only issue it seems is probably a lack of documentation. And the fact that explicitly redefining `createdAt`, `updatedAt`, and `deletedAt` in your modules is a bit of a mess. So some way of defining a get/set pattern for internal date types would be nice.

**Comment by dantman** [comment]
I am aware that a `beforeDefine` hooks can alter all the models. However some internal sugar to do this is still very desirable. Because the suggestion "just use a hook to define the getters" actually means writing something along the lines of this:
```js
hooks: {
	beforeDefine(columns, {paranoid=false, underscored, timestamps, createdAt, updatedAt, deletedAt, sequelize: {Utils}}) {
		if ( timestamps ) {
			if (createdAt !== false) {
				createdAt = createdAt || Utils.underscoredIf('createdAt', underscored);
				columns[createdAt] = columns[createdAt] || momentProperty(createdAt, {
					type: Sequelize.DATE,
					allowNull: false
				});
			}
			if (updatedAt !== false) {
				updatedAt = updatedAt || Utils.underscoredIf('updatedAt', underscored);
				columns[updatedAt] = columns[updatedAt] || momentProperty(updatedAt, {
					type: Sequelize.DATE,
					allowNull: false
				});
			}
			if (paranoid && deletedAt !== false) {
				deletedAt = deletedAt || Utils.underscoredIf('deletedAt', underscored);
				columns[deletedAt] = columns[deletedAt] || momentProperty(deletedAt, {
					type: Sequelize.DATE
				});
			}
		}
	}
}
```

**Comment by mickhansen** [comment]
Ideally it should be possible to just add the attribute for say `createdAt` like we support for id in the cases where the user has `timestamps: true`

**Comment by janmeier** [comment]
One problem with changing dates to moment objects is that there are some places in set that validates the date is actually a JS date object - ideally it shouldn't be so but .. :)

**Comment by mickhansen** [comment]
Yeah i would suggest storing the type as Date internally but converting from and to Date/Moment on set/get

**Comment by dantman** [comment]
That is how the get/set code works.

**Comment by mickhansen** [comment]
@dantman Not exactly sure what the issue is here?
Internal getters will all use `raw: true` to bypass plugins, that's why the internal value should be a date.
Is the specific bug that you set/get doesn't work when called from the outside?

**Comment by dantman** [comment]
@mickhansen No, get/set is working. But look at comment 3 to see what trying to add get/set to the internal date types actually involves.

We need a simpler way to define set/get to use for these date types. I'll update the title.

**Comment by mickhansen** [comment]
Ah so you'd like some way to modify the attribute without defining the attribute on the model first?

**Comment by MContagious** [comment]
If we are using express.js then we can use the following hook. This may help someone.
```
app.set('json replacer', function (key, value) {
    if (this[key] instanceof Date) {
        // Your own custom date serialization
        value = moment(this[key]).format("YYYY-MM-DD HH:mm:ss.SSS");
    }

    return value;
});
```
