### ISSUE TITLE
findAll({searchPath: "abc"})  and   model.schema() aren't working

### ISSUE THREAD

**Issue by cherchyk** [sequelize/sequelize#5148]
Hi I spent already couple of hours to find why setting db schema for table dor postgres is not working

I tried
test_bohdan.schema('abc', {
	schemaDelimiter: '@@',
	logging: function (str) {
		logger.log({
			type: 'sequelize',
			msg: str
		});
	}
});

and also 

test_bohdan.findAll({searchPath: "abc"})

but all quesries are generated as 

SELECT \"id\", \"name\", \"value\" FROM \"test_bohdan\" AS \"test_bohdan\";"

and as a result I have error
Unhandled rejection SequelizeDatabaseError: relation "test_bohdan" does not exist

What am I doing wrong?
Please help !!!

Here is my code

test_bohdan = sqlz.define('test_bohdan', {

    id: {
        type: Sequelize.INTEGER
		// ,autoIncrement: true
		, primaryKey: true
		// ,allowNull: false
	},
	name: {
		type: Sequelize.STRING,
		allowNull: true,
		validate: {
			len: [0, 50]
		}
	},
	value: {
		type: Sequelize.STRING,
		allowNull: true,
		validate: {
			len: [0, 50]
		}
	}
}, {
		timestamps: false,
		freezeTableName: true,
		//tableName: 'abc.test_bohdan'
	});
test_bohdan.schema('abc', {
	schemaDelimiter: '@@',
	logging: function (str) {
		logger.log({
			type: 'sequelize',
			msg: str
		});
	}
});

**Comment by mickhansen** [comment]
You should generally probably use schemas OR search paths.
You also have to enable search paths at the top level (they impact performance) via:

```js
new Sequelize(..., {
  dialectOptions: {
    prependSearchPath: ture
  }
});
```

IIRC, check out https://github.com/sequelize/sequelize/pull/4534 for details

**Comment by cherchyk** [comment]
Thanks @mickhansen :+1: 

I was using schemas OR/AND search paths and didn't achieve result.

Strange that prependSearchPath option never mentioned here 
http://sequelize.readthedocs.org/en/latest/api/sequelize/

I just tried what you suggested and it is not working


Also very strange that http://docs.sequelizejs.com/en/latest/api/model/#schemaschema-options-this
doesn't say I need an option in parameter

also it was not mentioned here http://docs.sequelizejs.com/en/latest/api/model/?highlight=searchPath

**Comment by mickhansen** [comment]
You might want to comment on the PR that implemented search paths, i'm not too familiar with how it works.

> Also very strange that http://docs.sequelizejs.com/en/latest/api/model/#schemaschema-options-this
doesn't say I need an option in parameter

I'm sorry i'm not sure what you mean.
