### ISSUE TITLE
Include not working with many-to-many

### ISSUE THREAD

**Issue by RobGonda** [sequelize/sequelize#515]
Apparently include only works with a belongsTo, not working with a hasMany double association using a reference table.

**Comment by DuffmanBE** [comment]
I think the issue still exists. I am using postgresql and I have a model defined as follows:

    module.exports = function(sequelize,DataTypes){
	return DepartmentProblem = sequelize.define('DepartmentProblem', {
		departmentProblemId: {
			type: DataTypes.INTEGER,
			primaryKey: true,
			allowNull: false,
			autoIncrement: true,
			unique: true
		},
		problemId: {
			type: 			DataTypes.INTEGER,
			references: 	'problems',
			referencesKey: 	'problemId'
		},
		departmentId: {
			type: 			DataTypes.INTEGER,
			references: 	'departments',
			referencesKey: 	'departmentId',
			allowNull: 		true
		}
	},
	{
		tableName: 'departmentsproblems'
	})
    }

The relationships are set up as follows:

    db["Problem"].belongsToMany(db["Department"], {through: db["DepartmentProblem"] , foreignKey: 'problemId'});
    db["Department"].belongsToMany(db["Problem"], {through: db["DepartmentProblem"], foreignKey: 'departmentId'}); 

If I now try to run following statement:

    return models.DepartmentProblem.findAll({where: {problemId: problemId}, include: [models.Department]});

I get this error:

    'Error: Department is not associated to DepartmentProblem!'

**Comment by janmeier** [comment]
@DuffmanBE DepartmentProblem is a join table, and thus not directly related to Department. If you need to query it that way you should set up direct relations (`DepartmentProblem.belongsTo(Department)` etc.)

With your current setup you can do  `Problem.findAll({ where: { id : problemId }, include: [ models.Department]});`

**Comment by RedactedProfile** [comment]
experiencing the same problem over here

basic User Groups + Permissions setup. 

Model UserGroup has an association hasMany(model.Permission)
Model Permission has an association belongsToMany(model.UserGroup)

*yes, a group is able to have multiple permissions, and those same permissions associated to multiple groups

Sequelize automatically generates the Hash/Linking/Join/Reference table, but when using a basic find or findAll, even with `include:{all: true}` in the results we SEE the Permissions array in the returned structure, but it's entirely empty. When looking at the SELECT query being generated, it doesn't appear to take the hash table into account at all and thus just returns a bunch of `NULL`s

**Comment by mickhansen** [comment]
@RedactedProfile BTM does not support multiple associations betwen the same models currently.
What is the SQL for `getPermissions()` does it look right? if an empty set is returned it's because nothing matches the primary key generally.

**Comment by grabbou** [comment]
Same issue. Tables are created correctly, calling `user.getGroups()` works correctly, but including `Group` throws `user is not associated to a Group`. Tried replacing `Group` inside include with `through name` and than, including `Group` on that through association but got cannot call method of undefined or whatever.

**Comment by mickhansen** [comment]
@grabbou do you have `as` defined on the association? You'll need to add the `as` to the include aswell.

**Comment by grabbou** [comment]
Nope, no `as`. Just `through`. As I had this problem few months ago when I was playing around with Sequelize, I will try to make a small Github project where this problem is reproduced. How that sounds?

**Comment by mickhansen** [comment]
@grabbou Being able to reproduce with minor code is always great :) You can also submit a PR with a failing unit test.
