### ISSUE TITLE
Belongstomany with mandatory key MUL

### ISSUE THREAD

**Issue by moracarlos** [sequelize/sequelize#5152]
I'm trying to define a transaction table, to save a transaction made from user A to user B. One user can have multiple transactions to the other. I created the relationship with Belongstomany() and set the primary key as an id. The first time I insert a transaction everything goes ok:

transaction (id 1, user 1, user 2)

But when I try to insert the second transaction:

transaction (id 2, user 1, user 2)

I get an error because user 1 and 2 cannot be duplicated, how can I solve this?

Thanks.

**Comment by mickhansen** [comment]
You'll have to define `unique: false` on the BTM relation and remove the constraint in the database.
However Sequelize still has poor support for non-nunique N:M relations so you might be better off simply working with multiple hasMany/belongsTo

**Comment by janmeier** [comment]
Yep, several places in BTM still assumes the relation is unique, even with unique: false https://github.com/sequelize/sequelize/issues/3493

**Comment by DanFerro** [comment]
Any ideas on places to look for a potential patch/FR? I see that with debug mode, it's at least querying multiple correctly after manually adding duplicate records, but multiples get filtered out after processing at some point. It looks like in some situations it's as simple as checking to see if the duplicate record already exists or if unique has been set to false. i.e. https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L629
