### ISSUE TITLE
Replacement arguments of type Array are being flattened

### ISSUE THREAD

**Issue by rjw209** [sequelize/sequelize#5153]
Looks like this was introduced in v3.16.0 and still exists in v3.17.0. When executing a raw query and utilizing the `replacements` option, any replacements of type Array are flattened and break the query.

```
var query = 'SELECT public.my_proc(?::INTEGER[])'
  , replacements = [[0, 1]];

sequelize.query(query, { replacements: replacements });
```

The above will result in a query that resembles something like the following:

`SELECT public.my_proc(0, 1::INTEGER[])`

instead of

`SELECT public.my_proc([0, 1]::INTEGER[])`

**Comment by mickhansen** [comment]
This was introduced by fixing a bug with `IN (?)` (which was originally worked).
Not at all sure how we support both currently.

**Comment by mliszewski** [comment]
:+1: This is a breaking change that is preventing us from upgrading to the latest version. Is there an alternate syntax we can use to specify array parameters?

**Comment by mickhansen** [comment]
As mentioned we are not sure how to support both at the moment short of forcing all PG users to use = ANY ARRAY rather than IN

**Comment by codyrigney92** [comment]
I noticed the PR that caused the change [here](https://github.com/sequelize/sequelize/pull/5032/files) and I think this logic doesn't quite make sense.  If you pass an array javascript object to postgres, shouldn't it be a postgres array also?  That is `ARRAY[]`

With `In` you have to list separate parameters anyway in a SQL query like `IN (?,?,?)` so wouldn't it make sense that a query relying on this should build dynamically constructed SQL?  With the current behavior it's converting an array into a set that's comma separated, which seems to me to be counter-intuitive.  Shouldn't an array (`Any(Array[])`) be replaced with an array and comma separated values (`In(?,?,?...)`) be replaced by multiple parameters(vs array)?

**Comment by mickhansen** [comment]
@codyrigney92 We've had a ton of users using `IN(?)` passing in an array and having that break. Using `IN (?,?,?)` would not work in a real world scenario, you'd have to construct the query based on the amount of values your'e checking again.

**Comment by codyrigney92** [comment]
@mickhansen I see your point.  I wonder if an optional parameter to use an array alongside `replacements` would work for this.  At this point it's probably more important for the behavior to be consistent for compatibility reasons.  We can work around it I think `Any(ARRAY[?]::uuid[])`

**Comment by mickhansen** [comment]
@codyrigney92 I'd welcome any solution that just sort of adresses this. This particular issue has been a pain in our butts for a good long while.

Yeah it pains me that we didn't just ask PG raw query users to use ANY ARRAY from the beginning :)

**Comment by felixfbecker** [comment]
I 100% agree with @codyrigney92.
> With In you have to list separate parameters anyway in a SQL query like IN (?,?,?) so wouldn't it make sense that a query relying on this should build dynamically constructed SQL? With the current behavior it's converting an array into a set that's comma separated, which seems to me to be counter-intuitive. Shouldn't an array (Any(?)) be replaced with an array and comma separated values (In(?,?,?...)) be replaced by multiple parameters(vs array)?

Think about it if you use prepared statements (`bind`). A `?` is always a _single value_. That value _can_ be an array, but for `IN` you have to write multiple `?`. We should change this in v4.

**Comment by gvsakhil** [comment]
Issue still persists in 2020

replacements: { subType, brochure: [brochure], id },

UPDATE tbl_project_details set 'BROCHURE' = ('8bc55c00-36c0-11eb-bc24-d3485457b3cf', '8bc58310-36c0-11eb-bc24-d3485457b3cf') WHERE PROJECT_ID = '60dfbc30-2f1b-11eb-9b63-53d8848a310d'
