### ISSUE TITLE
Create JSONB index via queryInterface

### ISSUE THREAD

**Issue by buunguyen** [sequelize/sequelize#5155]
Hello, is it possible to create a JSONB index via `queryInterface`? I have searched but couldn't find any documentation on this, so not sure if it's supported or not. If not, is there any suggestion on how to do so with sequelize?

**Comment by mickhansen** [comment]
We allow setting method and operator so should be possible.
Something like:

```js
queryInterface.addIndex('table', {
  fields: ['JSONBFIELD'],
  using: 'GIN',
  operator: 'jsonb_path_ops'
});
```

**Comment by buunguyen** [comment]
Thanks a lot!

**Comment by kingjerod** [comment]
This doesn't work when trying to specify the JSONB attribute, example: `fields: ["jsonb_col->>'user_id'"]`

Sequelize will escape the quotes and try to create an index on `"jsonb_col->>\'user_id\'"`. 

This results in the error: `column "jsonb_col->>\'user_id\'" does not exist`.

The only solution I've found seems to be raw SQL to create the index.

**Comment by tedeh** [comment]
I really think the docs should explain this and show an example, but this is the right solution. @kingjerod almost got there, but not quite. The important difference is the extra parantheses enclosure and `sequelize.literal`.

```javascript
sequelize.define('TableName', {}, {
  indexes: [
    {name: 'MyIndexName', fields: [sequelize.literal('("jsonbColumnName"->>\'jsonPropertyName\')')]},
  ],
});
```

**Comment by tedeh** [comment]
Also for anyone else using postgres, here is how you actually get your Sequelize-queries to **use** the index created in my previous post.

```javascript
TableName.findAll({
  where: {
     // [...] possibly other where-conditions here
     [Op.and]: [
       sql.sq.json("jsonbColumnName->>'jsonPropertyName'", our_ref),
     ]
  },
});
```

This seems to be necessary because Sequelize by default uses the `#>>` operator (instead of `->>` shown above) to select the nested jsonb field, which prevents postgres from using the index.
