### ISSUE TITLE
Cyclic dependency even after constraints false

### ISSUE THREAD

**Issue by akashbudhia** [sequelize/sequelize#5158]
For this simple Student, College example:

```javascript
var Student = sequelize.define('Student', {
        id: {
            type: Sequelize.INTEGER,
            field: "id",
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        }
});

var College = sequelize.define('College', {
        id: {
            type: Sequelize.INTEGER,
            field: "id",
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        }
});


College.hasMany(Student, {
                    as: "Students",
                    foreignKey: "collegeId",
                    onDelete: "NO ACTION",
                    onUpdate: "NO ACTION"
                });

Student.belongsTo(College, {
                    as: "College",
                    foreignKey: "collegeId",
                    onDelete: "NO ACTION",
                    onUpdate: "NO ACTION"
                });

College.belongsTo(Student, {
                    as: "PrimaryStudent",
                    foreignKey: "primaryStudentId",
                    onDelete: "NO ACTION",
                    onUpdate: "NO ACTION",
                    constraints: false //*****Note Here****
                });
```
We get the following error on db.sync():
Cyclic dependency found. Students is dependent of itself.
Dependency chain: Students -> Colleges => Students

Going by the documents setting constraints to false should ideally get it working. What am I doing wrong here?

**Comment by mickhansen** [comment]
That should be working, does it work if you set `constraints: false` on the `Student.belongsTo(College)` association?

**Comment by akashbudhia** [comment]
I tested this exact code segment, without anything else and we get a Cyclic Dependency. Even setting ```constraints: false``` on the ```Student.belongsTo(College)``` gives the Cyclic Dependency. Could it be a bug where constraints: false is not being honored at all.

**Comment by mickhansen** [comment]
Not impossible at all :)

**Comment by akashbudhia** [comment]
:) Can you try rephrasing? I am stuck on this, not able to get past. Please check or suggest a workaround.

**Comment by mickhansen** [comment]
Not impossible there's a bug. However this issue is commonly fixed by disabling constraints.

**Comment by janmeier** [comment]
By default sequelize associations will add `onDelete` and `onUpdate` constraints - which may create cyclic dependencies. Using `contraints: false` overrides that. However, when you manually add those constraints, sequelize still thinks there's a dependency.

Removing the on update and on delete constraints from `College.belongsTo(Student)` fixes the issue
