### ISSUE TITLE
v3.17.0 no avialble through npm

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#5161]
Hi,

I tried to install the latest version of Sequelize with npm, but it's showing that the latest available version is v3.16.0.

```
> npm show sequelize version
3.16.0
```

Am I missing something?

Thanks!

**Comment by janmeier** [comment]
Just tested in an empty folder, and my install works fine - also https://www.npmjs.com/package/sequelize lists 3.17.1 as the latest.

```bash
jan@jan-740U:~$ npm show sequelize version
3.17.1
``` 

Perhaps the version number is fixed in yuor package.json

**Comment by sushantdhiman** [comment]
Yes there was an issue due to node-time package used in one of pull request. You should be able to use 3.17.1

**Comment by nareynolds** [comment]
Thanks!
