### ISSUE TITLE
Question about bulkCreate and update

### ISSUE THREAD

**Issue by SteveyPugs** [sequelize/sequelize#5163]
Hi All,

I'm trying to understand the bulkCreate + update.

My case is simple.

I want to insert a few records in a table (we can call it orders for an example) and it has Order ID (increment), OrderStatus, OrderRef

I insert the OrderStatus and leave OrderRef null as I want to update it after I've inserted it.

After the insert I want to update OrderRef with [OrderID + "-ABC"]

Looking at the docs (link below) I am trying to understand how you would return the inserted records for update (if possible). If not will the update only perform on the past inserted records or is going to be for all records?

http://docs.sequelizejs.com/en/latest/docs/instances/#working-in-bulk-creating-updating-and-destroying-multiple-rows-at-once

**Comment by janmeier** [comment]
BulkCreate only returns the ids for inserted rows in postgres (which has `RETURNING *`). In other dialects you won't be able to know the ids of the inserted rows http://docs.sequelizejs.com/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance

For that, you'd need to loop over and create the rows individually

**Comment by SteveyPugs** [comment]
Ok. I am using MSSQL, so I will more then likely have to do it that way. What about the update part? Will that only apply to insert records or all records?

**Comment by SteveyPugs** [comment]
Code for reference:

```
Order.bulkCreate([
  {OrderStatus: 1},
  {OrderStatus: 1}
]).then(function() {
  return Order.update({ OrderRef: [function to copy order id + ABC] });
}).then(function(affectedRows){
  return Order.findAll();
}).then(function(orders) {
  console.log(orders)
})
```

**Comment by janmeier** [comment]
When you just call update without a where clause that will apply to all records - `Order.update` has no knowledge about the rows you just created, it just sends a `UPDATE ... SET ...` query to the server.

Again, the API docs help to answer many of these type of questions :) http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

I would actually think that code to throw an error, because it won't allow you to bulk update without a where clause

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
