### ISSUE TITLE
s.replace is not a function when attempting to count with `attributes: [[ sequelize.fn('COUNT', 'id')]`

### ISSUE THREAD

**Issue by realisation** [sequelize/sequelize#5166]
I need to get the count of some includes and am getting error `Unhandled rejection TypeError: s.replace is not a function` when I compose an include with `attributes: [[ sequelize.fn('COUNT', 'id')]`. This also fails on the first level of the query without any includes.

This error was also thrown when I did it without an aggregation (at least in syntax) with just `[[ 'COUNT(*)' ]]`.

I tried using a findAndCountAll query, it only counted the first level of the resulting object, so that's not a fallback either. What am I doing incorrectly here?

**Comment by realisation** [comment]
Also fails when I do `attributes: [[ sequelize.fn('COUNT', sequelize.col('id'))]`

Probably something about this in aggregation docs.

**Comment by realisation** [comment]
Yep - aggregations require aliases.

**Comment by jackson-sandland** [comment]
@realisation Could you post an example of this working?

**Comment by fd-rey** [comment]
This should work, 
`let options = {
  include: [{model: TaskModel, as: 'tasks'}],
  attributes:[  [sequelize.fn('COUNT', sequelize.col('tasks.id')), 'countTask']],
}`

The key is using the aliased name 'tasks'
