### ISSUE TITLE
Error with aggregate count in include

### ISSUE THREAD

**Issue by realisation** [sequelize/sequelize#5168]
Working with version 3.15 using mysql dialect, when I try to include a model and find an aggregate count on it, I get this error: `Unhandled rejection SequelizeDatabaseError: ER_MIX_OF_GROUP_FUNC_AND_FIELDS: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'tools.Squeegies.id'; this is incompatible with sql_mode=only_full_group_by`

The code for the query:     
  
    Squeegies.findAll({
        where: {description: req.params.squeegie},
        include: [
            {
                model: Squeegies, as: 'DesignIterations',
                attributes: [[ sequelize.fn('COUNT', 'id'), 'count' ]]

Seems from some other googling this is an problem in MySQL?

**Comment by mickhansen** [comment]
The problem here is that sequelize will inject id onto the include attributes to allow effective deduplication, currently no way around it other than using raw: true on the find call overall.
You'll likely also want to add `attributes: []` to the overall find call.

**Comment by realisation** [comment]
Hmm - `raw: true` seems to beget the same error.

**Comment by mickhansen** [comment]
Please include the entire find call and the SQL log.

**Comment by realisation** [comment]
Alrighty: 
  SELECT 'Squeegies'.'id',
   'Squeegies'.'background',
    'Squeegies'.'parent',
     'Squeegies'.'viewOrder',
      'Squeegies'.'description',
       'Squeegies'.'createdAt',
        'Squeegies'.'createdBy',
         'Squeegies'.'updatedAt',
          'Squeegies'.'updatedBy',
           COUNT('id') AS 'SubSqueegies.count'
  FROM 
   'Squeegies' AS 'Squeegies' LEFT OUTER JOIN 'Squeegies' AS 'SubSqueegies'
   ON 'Squeegies'.'id' = 'SubSqueegies'.'parent'
   WHERE 'Squeegies'.'description' = 'squeakiness';

Unhandled rejection SequelizeDatabaseError: ER_MIX_OF_GROUP_FUNC_AND_FIELDS: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'tools.Squeegies.id'; this is incompatible with sql_mode=only_full_group_by

    m.Squeegies.belongsTo(m.Squeegies, { as: 'SubSqueegies', foreignKey: 'parent' });
    m.Squeegies.hasMany(m.Squeegies, { as: 'SubSqueegies', foreignKey: 'parent' });

**Comment by mickhansen** [comment]
You're still missing `attributes: []` on the top level options like i mentioned in a previous comment.

**Comment by realisation** [comment]
Whoops, yes, I tried that, but wasn't sure what I should put in it. I tried it with a few different things, mostly different ids, and the error changed from expression #1 to #10 or something - the id of the SubSqueegie join table

**Comment by realisation** [comment]
Ah hm, so having `attributes: []` works with that query with one include just like you said, but when I try it with a nested include, I'm getting a *slightly* different error. Here's the SQL & error: 

default): 
SELECT COUNT('id') AS `SubSqueegie.count`,
 `Brothers.Weegies`.`id` AS `Brothers.Weegies.id`,
  COUNT('id') AS `Brothers.Weegies.count` 
FROM 
`Squeegie` AS `Squeegie` LEFT OUTER JOIN `Squeegie` AS `SubSqueegie` 
 ON `Squeegie`.`id` = `SubSqueegie`.`parent` 
  LEFT OUTER JOIN `Brotherss` AS `Brothers` ON `Squeegie`.`Brothers` = `Brothers`.`id` 
   LEFT OUTER JOIN `Weegies` AS `Brothers.Weegies` ON `Brothers`.`id` = `Brothers.Weegies`.`Brothers` 
    WHERE `Squeegie`.`description` = 'squeaky';
Unhandled rejection SequelizeDatabaseError: ER_MIX_OF_GROUP_FUNC_AND_FIELDS: In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column '

And the code: 

    Squeegies.findAll({
        where: { description: req.params.description},
        raw: true,
        attributes: [ ],
        include: [
            {
                model: Squeegies, as: 'SubSqueegies',
                attributes: [[ sequelize.fn('COUNT', 'id'), 'count' ]]
            },
            {
                model: Brothers,
                attributes: [],
                include: [
                    {
                        model: Weegies,
                        attributes: [[ sequelize.fn('COUNT', 'id'), 'count' ]]
                    }
                ]
            }
        ]
    }).then(function(result){
        res.send(result);
    });

**Comment by mickhansen** [comment]
Aren't you missing a group statement?

**Comment by realisation** [comment]
That I tried too, but it gave another error. I don't think I know how what those are all about - about to go google sql group by.

**Comment by realalexhomer** [comment]
For anyone looking at this, what worked for me was putting the table that was being joined in (not the join table) the group array and setting raw to true on the top level of the query.

so: 
group: ['table_a.id', 'other_table.id', 'table_belonging_to_table_a.id, '],
raw: true

When I set attributes to [] on the top level every attribute I was querying came back as null, but it works without doing this.
