### ISSUE TITLE
destroy function isn't working with a where on a json column

### ISSUE THREAD

**Issue by fredericlefeurmou** [sequelize/sequelize#5171]
I am trying to delete an item based on an id contained in the `origin` jsonb column but it doesn't work.

Here is my code:
```
          Item.destroy({
            where: {
              'origin.id': originId
            }
          })
```

The resulting query:
`Executing (default): DELETE FROM "Items" WHERE "origin.id" = '904381360'`

The error:
`error: column "origin.id" does not exist`

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/5092

**Comment by rajajlidi** [comment]
i have problem 

 Client.destroy({
                where: {
                    id: id
                }
            }).success(onSuccess).error(onError);

Executing (default): DELETE FROM `plan_clients` WHERE `where`  '1'
