### ISSUE TITLE
Using relational table with reference column from related tables that are not id column

### ISSUE THREAD

**Issue by realisation** [sequelize/sequelize#5172]
I have an intermediate relational table that relates two tables `MataRays` and `Bats` via a `background` column. I'm trying to have an include where it finds them - but instead of using the `background` column on the two related tables, it uses the `id` column, and the `background` column from the relational table, which I added in there just to see if it would fix things - it is the same as the `id` from that table. 

Here's the query & relations: 

I tried to fix it by adding a hasMany and belongsTo association designating background as a foreign key, but this doesn't seem to have impacted anything.

    MantaRays.findAll({
        where: {description: req.params.description },
        include: [ {model: Bats, as: 'MantaRaysAndBats'} ]
    }).then(function(result){
        res.send(result);
    });

    m.ThingsWithWings.hasMany(m.MantaRays, { foreignKey: 'background' });
    m.MantaRays.belongsTo(m.ThingsWithWings, { foreignKey: 'background' });

    m.ThingsWithWings.hasMany(m.Bats, { foreignKey: 'background' });
    m.Bats.belongsTo(m.ThingsWithWings, { foreignKey: 'background' });

    m.MantaRays.belongsToMany(m.Bats, { as: 'MantaRaysAndBats', through: 'ThingsWithWings', foreignKey: 'background'});
    m.Bats.belongsToMany(m.MantaRays, { as: 'MantaRaysAndBats', through: 'ThingsWithWings', foreignKey: 'background'});

`MantaRays` AS `MantaRays` 
LEFT OUTER JOIN 
(`ThingsWithWings` AS `MantaRaysAndBats.ThingsWithWings` INNER JOIN `Bats` AS `MantaRaysAndBats` ON
 `MantaRaysAndBats`.`id` = `MantaRaysAndBats.ThingsWithWings`.`background`) 
  ON `MantaRays`.`id` = `MantaRaysAndBats.ThingsWithWings`.`background` WHERE `MantaRays`.`description` = 'really big';

**Comment by mickhansen** [comment]
Please plut SQL in code blocks aswell, otherwise it's imposible to read.
In belongsToMany foreignKey denotes the name of the foreign key on the join table, you can't have the same `foreignKey` definition on both sides of a BTM relation definition.
