### ISSUE TITLE
Automatic relation M:N

### ISSUE THREAD

**Issue by thebergamo** [sequelize/sequelize#5174]
Hello guys!

I have 2 models: `Product` and `Category`, so a Product can be in many Category and a Category has many Products.
Is a M:N relation, ok?

My models are here: https://gist.github.com/thebergamo/e3215d3f9874e72e1906

When I call sync in a migration file, sequelize not create the table ProductCategory why? What wrong are in my models?

**Comment by janmeier** [comment]
Calling sync on only product and category will not create the join table - it will only be created when calling sequelize.sync

**Comment by thebergamo** [comment]
@janmeier like this:

```
function up (db) {
  const Product = require('../src/catalog/product/model')(db.sequelize, db.Sequelize);
  const Category = require('../src/catalog/category/model')(db.sequelize, db.Sequelize);
  // const productCategory = require('../src/catalog/productCategory/model')(db.sequelize, db.Sequelize);
  return Promise.all([Product.sync(), Category.sync()])
  .then(() => {
    db.sequelize.sync();
  });
}
```

It still not creating the relation

**Comment by janmeier** [comment]
Ah - you need to call the associate method - it's not invoked automagically.

**Comment by thebergamo** [comment]
haha will try =D
