### ISSUE TITLE
BIGINT gets truncated

### ISSUE THREAD

**Issue by jsha** [sequelize/sequelize#5176]
Accordign to the [Changelog](https://github.com/sequelize/sequelize/blob/master/changelog.md#v160), bigints are supposed to be treated as a string, which is one good way to work around Javascript's inability to store [accurate 64-bit integers](https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake). Another way would be to use a module that implements 64-bit ints with native code, like [node-int64-native](https://github.com/candu/node-int64-native) or [node-int64](https://github.com/broofa/node-int64).

However, the current implementation turns BIGINT fields into Numbers when loading them from the DB, truncating them. The program below demonstrates the problem. The example number 90071992547409921 gets truncated to 90071992547409920 (note the last digit) when represented as a Number. Saving the value into MySQL works correctly, but it is truncated into a Number on read.

```
var Sequelize = require('sequelize');
var sequelize = new Sequelize('bigintz', 'bigintz', '');

var User = sequelize.define('User', {
  bid: Sequelize.BIGINT
});

sequelize.sync().then(function() {
  var u = User.build();
  u.bid = '90071992547409921'
  u.save().then(function() {
    return User.find({
      where: {
        bid: u.bid
      }
    });
  }).then(function(u2) {
    console.log('u2', u2.dataValues);
    console.log('typeof bid', typeof u2.bid);
  }).catch(function(err) {
    console.log(err);
  });
});
```

```
$ node bigint-test.js
Executing (default): INSERT INTO `Users` (`id`,`bid`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'90071992547409921','2016-01-09 19:09:28','2016-01-09 19:09:28');
Executing (default): SELECT `id`, `bid`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`bid` = '90071992547409921' LIMIT 1;
u2 { id: 1,
  bid: 90071992547409920,
  createdAt: Sat Jan 09 2016 11:00:14 GMT-0800 (PST),
  updatedAt: Sat Jan 09 2016 11:00:14 GMT-0800 (PST) }
typeof bid number

$ mysql -u bigintz -D bigintz -e 'select bid from Users limit 1;'
+-------------------+
| bid               |
+-------------------+
| 90071992547409921 |
+-------------------+

$ mysql -u bigintz -D bigintz -e 'describe Users;'
+-----------+------------+------+-----+---------+----------------+
| Field     | Type       | Null | Key | Default | Extra          |
+-----------+------------+------+-----+---------+----------------+
| id        | int(11)    | NO   | PRI | NULL    | auto_increment |
| bid       | bigint(20) | YES  |     | NULL    |                |
| createdAt | datetime   | NO   |     | NULL    |                |
| updatedAt | datetime   | NO   |     | NULL    |                |
+-----------+------------+------+-----+---------+----------------+
```

**Comment by jsha** [comment]
Some extra data:

- [here]'s the original PR adding BIGINT support, which doesn't appear to change how results get parsed.
- The `supportBigNumbers` and `bigNumberStrings` options in https://github.com/felixge/node-mysql#connection-options are probably necessary.

**Comment by jsha** [comment]
Confirming that changing bigint-test.js to include those dialectOptions generates correct results:

```
var sequelize = new Sequelize('bigintz', 'bigintz', '', {
  dialectOptions: {
    bigNumberStrings: true,
    supportBigNumbers: true
  }
});
```

```
$ node bigint-test.js 
Executing (default): INSERT INTO `Users` (`id`,`bid`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'90071992547409921','2016-01-09 22:49:56','2016-01-09 22:49:56');
Executing (default): SELECT `id`, `bid`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`bid` = '90071992547409921' LIMIT 1;
u2 { id: 1,
  bid: '90071992547409921',
  createdAt: Sat Jan 09 2016 11:00:14 GMT-0800 (PST),
  updatedAt: Sat Jan 09 2016 11:00:14 GMT-0800 (PST) }
```

Since BIGINT results are very subtly wrong without those dialect options, does it make sense to generate an error when trying to save or query a model containing BIGINTs, unless the right dialect options are present? Or perhaps set those two dialect options by default for mysql?

**Comment by janmeier** [comment]
Agreed, it probably makes sense to force bigints to strings
