### ISSUE TITLE
Cannot set association, failing silently.

### ISSUE THREAD

**Issue by xlexi** [sequelize/sequelize#5177]
I am trying to set an association between two existing entries, but nothing happens, it just fails without an error.

Model:     
```javascript
let User = db.define('User', {
    phone:    Sequelise.STRING,
    name:     Sequelise.STRING,
    password: Sequelise.STRING,
    salt:     Sequelise.STRING
});

let Parking = db.define('Parking', {
    number: Sequelise.INTEGER,
    type:   Sequelise.STRING,
});

Parking.belongsTo(User, { as: 'morning'});
Parking.belongsTo(User, { as: 'afternoon'});

db.sync();
```
Setting association:
```javascript
Parking.findOne({
    where: { id: 1 }
}).then((result) => {
    if (result) {
        // User object acquired earlier under authentication process.
        result.setMorning = user;
        db.sync().then(function() {
            response.send(result);
        });
    } else {
        response.send({error: "404"});
    }
});
```

**Comment by mickhansen** [comment]
I'm not sure what you're expecting to happen here, currently you're assigning a value to a property, overwriting the association method.

You need to use result.setMorning(user).

And you should definitely not be using sync are you are. sync creates tables, it should be called before using models, not after.

(looks like you might be assuming sync() is some kind of unit work implementation? It's not, just to clear that up)

**Comment by xlexi** [comment]
I can't believe I made the stupid mistake of confusing an assignment with a function call, I was way over-thinking this. Thank you for the help, apologies for wasting your time this.

I did read how sync works, I just added it in a feat of desperation when this wasn't working

**Comment by mickhansen** [comment]
Glad you solved it :)
