### ISSUE TITLE
Verification on how timestamps work

### ISSUE THREAD

**Issue by davidleureka** [sequelize/sequelize#5179]
Forgive the noob question, but I've been struggling with how the timestamp related settings work and I haven't been able to answer my questions through the docs.

I'm talking specifically about the `timestamps` and `paranoid` options work when using the `define` method to create a model.

I was expecting that specifying these would make sequelize create the `createdAt`, `updatedAt`, and `deletedAt` columns in my table. This does not appear to be the case. Since I'm using migrations to actually create the table, it looks like I need to explicitly create those columns in the migration. Something like:

    queryInterface.createTable('MyTable', {
        myId: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
        field2: Sequelize.INTEGER,
        field2: Sequelize.STRING(25),
        createdAt: { allowNull: false, type: Sequelize.DATE },
        updatedAt: { allowNull: false, type: Sequelize.DATE },
        deletedAt: { allowNull: true, type: Sequelize.DATE }
    })

I would guess that the `timestamps` and `paranoid` options simply tell sequelize to make use of these fields when creating, updating, and deleting things. So sequelize will assume you have taken the necessary steps to ensure those fields have been created with the proper settings. It will not do it for you.

Does all that sound right?

**Comment by janmeier** [comment]
Yep, that sounds correct.

At some point it would be nice if sequelize could figure out and add the missing columns automagically, but for now you'll have to do it yourself https://github.com/sequelize/sequelize/issues/537

**Comment by davidleureka** [comment]
Thank you for the quick response!
