### ISSUE TITLE
hasMany uses primary key from owner table but need to use a different column

### ISSUE THREAD

**Issue by realisation** [sequelize/sequelize#5180]
I'm trying to build three different associations from one model/table to another model/tabel, using three different columns on that first table.

My code for creating the associations goes like: 

```
m.HugeTemples.hasMany(m.Gods, { as: 'GodsAndHugeTemples', foreignKey: 'God'  });
```

This should take one huge temple and find all the gods associated with it. Similar associations for demi-gods and fish. 

But I am finding that the SQL generated by this is trying to match `HugeTemples.id` to `Gods.god` instead of `HugeTemples.god` to `Gods.god`.

Here's the query & code: 

```
HugeTemples.find({
    where: {id: 1},
    include: [
    {
        model: Gods,
        as: 'GodsAndHugeTemples',
    } ]
}).then(function(result){
    res.send(result);
});


FROM `HugeTemples` AS `HugeTemples` LEFT OUTER JOIN `Districts` AS `Gods`
ON `HugeTemples`.`id` = `Gods`.`god` WHERE `HugeTemples`.`id` = 1;
```

How do I instruct it to use `HugeTemples.god` instead of `HugeTemples.id`, or is there a more established way to accomplish this?

**Comment by realisation** [comment]
I see, this is an upcoming feature at some point. Any idea when it will be completed? Maybe you could use someone to finish it. 

Here is duplicate issue: https://github.com/sequelize/sequelize/issues/4258

**Comment by janmeier** [comment]
@realisation We could definitely use someone to finish it :). Its already implemented for belongsTo and belongsToMany, so you could take inspiration from there

**Comment by mickhansen** [comment]
buu from IRC is working on a refactor of this, not sure what his GH handle is.

**Comment by rmzg** [comment]
https://github.com/rmzg/sequelize/tree/foreignkey-fixes is the progress so far, working on the the api right now.
