### ISSUE TITLE
Missing transaction config parameter documentation on Transaction class

### ISSUE THREAD

**Issue by lifenautjoe** [sequelize/sequelize#5182]
As seen [here](https://github.com/sequelize/sequelize/blob/0de404640d4c71e2d1f1259356650dfb586a248b/lib/transaction.js#L26) there is a `transaction` parameter on the `config` object which is not documented in the `Transaction` class  [documentation](https://github.com/sequelize/sequelize/blob/master/docs/api/transaction.md)

**Comment by mickhansen** [comment]
Confirmed, savepoint support is missing from documentation.
