### ISSUE TITLE
Warning Promise

### ISSUE THREAD

**Issue by danielspk** [sequelize/sequelize#5187]
File lib/transaction.js generate warning:

Warning: a promise was created in a handler but was not returned from it
    at [object Object].ConnectionManager.releaseConnection (/project/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:239:10)
    at [object Object].Transaction.cleanup (/project/node_modules/sequelize/lib/transaction.js:279:46)
    at /project/node_modules/sequelize/lib/transaction.js:188:14

Resolution:

```javascript
Transaction.prototype.commit = function() {
  var self = this;

  if (this.finished) {
    throw new Error('Transaction cannot be committed because it has been finished with state: ' + self.finished);
  }

  this.$clearCls();

  return this
    .sequelize
    .getQueryInterface()
    .commitTransaction(this, this.options)
    .finally(function() {
      self.finished = 'commit';
      if (!self.parent) {
        return self.cleanup();
      }
      return null;
    });
};
```
Add return sentence.

**Comment by mickhansen** [comment]
Have you verified that this change fixed it? Was not aware that finally() needed a return.

**Comment by danielspk** [comment]
Yes.
The warning occurs when a new Promise is created and within the call a method sequelize. Example:

```javascript
  var promises = [];
  myArray.forEach(function(id) {
    var promise = new Promise(function(resolve, reject) {
      Model.Program.findOrCreate({
        where: { id: parseInt(id) },
        defaults: {...}
      }).then(function() {
        resolve();
      }).catch(function(e) {
        reject(e);
      });
    });
    promises.push(promise);
  });
  Promise.all(promises);
```

**Comment by mickhansen** [comment]
That example seems unrelated to the specific fix you're suggesitng here though?
Are you sure that new Promise() triggers warnings aswell?

**Comment by danielspk** [comment]
The code is only an example to prove when he gives warning. Including the return on sequelize warning is solved.

**Comment by mickhansen** [comment]
I'll apply the changes (in the future a PR is the most helpfull :))
