### ISSUE TITLE
Validators never run for null / undefined values

### ISSUE THREAD

**Issue by skleeschulte** [sequelize/sequelize#5189]
From the [docs about model definition, validators and allow null](http://docs.sequelizejs.com/en/latest/docs/models-definition/#validators-and-allownull):

> If a particular field of a model is set to allow null (with `allowNull: true`) and that value has been set to `null`, its validators do not run.

In fact (custom) validators for a specific field never run if the field is set to `null` or `undefined` (regardless of the value of `allowNull`): see [instance-validator.js (line 167-170)](https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js#L167-L170).

I'm not sure if this is a documentation issue or an implementation issue. The problem with the current implementation is that it's not possible to have custom validators detect the empty value and throw a custom error. This is related to [customizable allowNull error messages #1500](https://github.com/sequelize/sequelize/issues/1500).

**Comment by mickhansen** [comment]
I'd say this is probably an implementation error. The if could simply be removed if https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js#L67 is changed to be sequential instead (running schema validations first)

**Comment by iancamp22** [comment]
I was able to work around this by using `defaultValue: sequelize.literal("NULL")`.
