### ISSUE TITLE
Load from JSON object

### ISSUE THREAD

**Issue by maxsosa** [sequelize/sequelize#519]
Hello, I know any object from the model can be stringified. But there are any method to create an Sequelize object from a plain JSON that previously was a model object?

Thanks.

**Comment by faiwer** [comment]
Hm… 

`let dao = this.model.build(json, { isNewRecord : false });`

destroy it

`dao.destroy()`

debug:

`Executing (default): DELETE FROM "AccessSessions" WHERE "id" IN (SELECT "id" FROM "AccessSessions" WHERE "id" = NULL LIMIT 1)`

console.log(dao)

```
{ dataValues: 
   { id: 45,
     … },
  _previousDataValues: 
   { id: undefined,
     … },
  _changed: { id: true, hash: true, expireAt: true, userId: true },
  ...
  isNewRecord: false }
```

- dataValues.id === 45
- _previousDataValues.id === undefined
- _changed.id === true

test

```dao._previousDataValues.id = json.id; // 45
dao._changed.id = false;```

but again

`Executing (default): DELETE FROM "AccessSessions" WHERE "id" IN (SELECT "id" FROM "AccessSessions" WHERE "id" = NULL LIMIT 1)`

What I do wrong?

**Comment by faiwer** [comment]
Hm… 

`let dao = this.model.build(json, { isNewRecord : false });`

destroy it

`dao.destroy()`

debug:

`Executing (default): DELETE FROM "AccessSessions" WHERE "id" IN (SELECT "id" FROM "AccessSessions" WHERE "id" = NULL LIMIT 1)`

console.log(dao)

```
{ dataValues: 
   { id: 45,
     … },
  _previousDataValues: 
   { id: undefined,
     … },
  _changed: { id: true, hash: true, expireAt: true, userId: true },
  ...
  isNewRecord: false }
```

- dataValues.id === 45
- _previousDataValues.id === undefined
- _changed.id === true

test

```
dao._previousDataValues.id = json.id; // 45
dao._changed.id = false;
```

but again

`Executing (default): DELETE FROM "AccessSessions" WHERE "id" IN (SELECT "id" FROM "AccessSessions" WHERE "id" = NULL LIMIT 1)`

What I do wrong?
