### ISSUE TITLE
Association not loaded after create

### ISSUE THREAD

**Issue by Misiur** [sequelize/sequelize#5191]
Code below (without the `include: [Player]`) worked fine for me earlier (I guess sometime around Sequelize 3.8), and in last `then` I could access `access.players` without problem. However after I upgraded my deps, something changed, and now `access.players` is either 1) undefined without the `include`, or 2) an empty array. Why?

```js
return SatelliteAccess.create({
        domain: domain,
        task: task,
        token: token,
        expiresAt: SatelliteAuthentication.getExpiryDate()
    }, { include: [Player] })
    .then(function (access) {
        return access.reload();
    })
    .then(function (access) {
        return access.addPlayer(player).return(access);        
    })
    .then(function (access) {
        return access;
    })
    ;
```

SO question for free karma: http://stackoverflow.com/questions/34730768/sequelize-create-with-include

**Comment by mickhansen** [comment]
`addAssociation` has never modified the association values of parent so not quite sure why it would have worked previously.

It would work with:

```js
return SatelliteAccess.create({
        domain: domain,
        task: task,
        token: token,
        expiresAt: SatelliteAuthentication.getExpiryDate(),
        players: [player]
}, { include: [Player] });
```
