### ISSUE TITLE
How to set a float value to NaN?

### ISSUE THREAD

**Issue by gcatto** [sequelize/sequelize#5194]
This may totally be my problem, but I have a float value (with allowNull: false) that I would like to be able to see to NaN. However, when I do so, I get ```SequelizeDatabaseError: column \"nan\" does not exist```. Is there a specific way I am supposed to provide NaN as a value? Thanks!

**Comment by mickhansen** [comment]
Does your database support NaN as a value in any way?
My guess is you'd want to insert a null instead

**Comment by gcatto** [comment]
Thanks for the fast response! I'm using Postgres and I can write a raw SQL query to insert NaN into the same column.

**Comment by gcatto** [comment]
I could potentially use null (or perhaps another value), although I'd have to refactor things a bit I think, as I am currently using null to mean something else, so I'd prefer to avoid that route if possible.

And, to give a little more detail, I am using updateAttributes() to update a block of attributes (shocking, I know) within a transaction where one of the values can be NaN. Since the error is ```column \"nan\" does not exist``` that the NaN is being wrapped in "s instead of 's by the logic underneath updateAttributes()?

**Comment by mickhansen** [comment]
Can you try pasting the SQL query Sequelize generated?
If Postgres supports NaN we should ideally support that aswell.

**Comment by gcatto** [comment]
I've simplified out some of the other, irrelevant attributes from the code that gets generated:
```
INSERT INTO "powers" ("heuristics","id") VALUES (NaN,815) RETURNING *
```
So it looks like its not wrapping the NaN in anything, where it should be wrapping it in 's I think.

**Comment by Volox** [comment]
Hi,
i have the same problem with Integer types.
@jamelt is there a reason to have the solution applied only to `FLOAT, DOUBLE, REAL`?

**Comment by janmeier** [comment]
@Volox NaN is only supported by IEEE floating point types, see http://www.postgresql.org/docs/8.4/static/datatype-numeric.html sector 8.1.3
