### ISSUE TITLE
Using order random with include causes association to return random instead of target model

### ISSUE THREAD

**Issue by hestinr12** [sequelize/sequelize#5195]
Two models: 
* SurveyQuestion
* Answer

Associated using:

`SurveyQuestion.hasMany(Answer)`

Query using: 

```
SurveyQuestion.find({ 
		order: [ Sequelize.fn( 'RAND' ) ],
		include: [ Answer ]
	})
```

Returns the associated Answers randomly, but you always get the same SurveyQuestion back. Tried to make sure I wasn't just doing something stupid, but seems like unintended behavior?

**Comment by mickhansen** [comment]
How are the results coming back if you run the query manually?
Sequelize collects the nested results, but does not do any ordering.

**Comment by hestinr12** [comment]
The query spat out in the console for the app is

```SELECT `SurveyQuestion`.*, `Answers`.`id` AS `Answers.id`, `Answers`.`text` AS `Answers.text`, `Answers`.`count` AS `Answers.count`, `Answers`.`createdAt` AS `Answers.createdAt`, `Answers`.`updatedAt` AS `Answers.updatedAt`, `Answers`.`SurveyQuestionId` AS `Answers.SurveyQuestionId` FROM (SELECT `SurveyQuestion`.`id`, `SurveyQuestion`.`text`, `SurveyQuestion`.`createdAt`, `SurveyQuestion`.`updatedAt` FROM `SurveyQuestions` AS `SurveyQuestion` LIMIT 1) AS `SurveyQuestion` LEFT OUTER JOIN `Answers` AS `Answers` ON `SurveyQuestion`.`id` = `Answers`.`SurveyQuestionId` ORDER BY `SurveyQuestion`, RAND();```


Which actually throws an error when pasted into MySQL command line:

`ERROR 1054 (42S22): Unknown column 'SurveyQuestion' in 'order clause'`

Maybe I'm doing it wrong -_-  Removing the `SurveyQuestion` on the order clause, as seemingly expected, returns the id = 1 record each time.

**Comment by mickhansen** [comment]
Not sure how MySQL handles ordering of joined rows with RAND().

**Comment by hestinr12** [comment]
/shrug, will post workaround attempt for this when I conjure one up
