### ISSUE TITLE
what happened to otherKeyAttribute and foreignKeyAttribute?

### ISSUE THREAD

**Issue by ssteffl** [sequelize/sequelize#5199]
I just updated the sequelize version on my project and some of my associations code broke. Specifically it was some undocumented internal stuff i depended on, but I cannot seem to find a workaround right now. To be clear -- it was working before i updated to 3.17.1. I don't know what version i updated from.

Im my function below, the `OneToMany` section is broken. How am i supposed to do this code now? `associationConfig.foreignKeyAttribute.references.key;`, doesn't work because `associationConfig.foreignKeyAttribute` is just an empty object! 

This function is supposed to get the field on the other model that our model references in an association

    /**
        returns the field on the current model passed in that are
        used for the association
    */
	function _getForeignRefField(model, association, type){
		var associationConfig = model.associations[association];
		if(!associationConfig){
			throw new Error('invalid association: ' + association);
		}
		
		if(type.isOneToOne){ //hasOne
			return associationConfig.sourceIdentifier;
		}
		else if(type.isManyToOne){ //belongsTo
			return associationConfig.foreignKey;
		}
		else if(type.isOneToMany){ //hasMany
			return associationConfig.foreignKeyAttribute.references.key;
		}
		else if(type.isManyToMany){ //belongsToMany
			return {
				throughModelField: associationConfig.foreignKey,
				field: associationConfig.foreignKeyAttribute.references.key
			};
		}
		else {
			throw new Error('invalid model association type');
		}
	}

**Comment by ssteffl** [comment]
nvm i just replaced it with `model.attributes[associationConfig.foreignKey].references.key`.

It would be great if there was a documented API for getting the fields on the models associated with associations.

**Comment by mickhansen** [comment]
Those properties are an implementation detail and therefor specifically non public and non documented.
We don't want to have to bump major for changing internal variable naming.
