### ISSUE TITLE
Model.update({ ... }, {silent: true})

### ISSUE THREAD

**Issue by astephenb** [sequelize/sequelize#5200]
`silent` is an option when updating an instance, but not when doing bulk updates. Is it possible to do a bulk update without updating timestamps?

```js
Model.update({ foo: 'bar' }, { silent: true });
```

**Comment by mickhansen** [comment]
Not currently it looks like, other than using `fields`.

**Comment by astephenb** [comment]
Thanks a lot! I will close this issue.
