### ISSUE TITLE
Connecting to a new tenant created in a multi tenant db architecture.

### ISSUE THREAD

**Issue by hariprasadkulkarni** [sequelize/sequelize#5206]
I'm using Sequelize to connect to various tenants in my instance of MySQL. Connections to existing tenants are created when the node server is brought up. I'm using a modified version of "index.js" described here. https://sequelize.readthedocs.org/en/1.7.0/articles/express/

Modification is that I'm creating a list of tenant connections instead of just one connection. 

Now since the connections (exported using `db`) are created at the server startup and node caches it in `require.cache`, subsequent calls to `require('db')` return the cached object.

If I were to create a new tenant, how can I create a connection and add it to this object without having to restart the server?

**Comment by mickhansen** [comment]
You'd probably want to write a wrapper of some sorts that take the tenant as an argument and returns a sequelize instance (cached on the tenant id probably).

Sequelize itself does not currently have any type of multi tenant support, so you have to work around it.

**Comment by hariprasadkulkarni** [comment]
Yes, this is what I'm doing currently. But it comes across as a "hack". I was wondering if there was a better way of doing this, because googling with multiple keywords led me nowhere.

Thanks for the quick response!
