### ISSUE TITLE
how to execute a bit operation in where

### ISSUE THREAD

**Issue by bangbang93** [sequelize/sequelize#5207]
I need to execute some query like 
```
SELECT * FROM a.b where status & 2 = 2;
```

I use bit operation on status fields for store some complex switch(true/false) information,so I need to use bit operation in sql for query.

And I need to  use associations so can't use raw query

**Comment by janmeier** [comment]
```
Model.findAll({
    where: sequelize.where(sequelize.literal('status & 2'), 2)
})
```

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
