### ISSUE TITLE
Add option to name foreign keys in migrations

### ISSUE THREAD

**Issue by itsravenous** [sequelize/sequelize#5210]
It's great that we can add foreign keys in migrations when using `queryInterface.createTable()`, but I would really like to be able to name the foreign keys created. In MSSQL, this looks like:

```
CREATE TABLE Equipment (Id int NOT NULL, Name nvarchar(50), OwnerId int 
[...]
CONSTRAINT FK_Equipment_People FOREIGN KEY (OwnerID) 
    REFERENCES People (Id)
```

Naming the constraints makes it much easier to drop them in the down portion of migrations.

I know some of the migration stuff isn't documented in much detail, so I checked the source and I don't think it's currently possible.

(I'm sure I've seen a request for this elsewhere, but have searched to no avail).

**Comment by alexandrejunges** [comment]
Being able to name the foreign keys would be really nice.
The issue #3116 is probably related.

**Comment by itsravenous** [comment]
Been meaning to request this for a while. Naming constraints does make the down step easier, although perhaps dropping the FK constraint should be automatically handled by `dropColumn`, in a similar way to #4990 - I think dropping the column implies dropping the constraint, no?

**Comment by mickhansen** [comment]
@itsravenous Just merged PR that automatically drop FK constraints on dropColumn for MySQL/MSSQL

**Comment by itsravenous** [comment]
Wonderful! Thanks @treythomas123 and @mickhansen this will make life much easier :dancers:
