### ISSUE TITLE
Don't JSON stringify all the association attributes

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5214]
When I define a model like this:

``` js
const Foo = seq.define('Foo', {
  id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
  name: Sequelize.STRING
})
const Bar = seq.define('Bar', {
  id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
  name: Sequelize.STRING
})
Gericht.belongsTo(Bar, {as: 'bar', foreignKey: 'bar_id'})
```

And query like this:

``` js
Foo.findAll({include: [{model: Bar, as: 'bar'}]})
```

I expect the JSON to only include the attributes I initially defined in my `define` call. Instead, I get the association ID as an extra attribute aswell:

``` json
{
  "id": 1,
  "name": "test",
  "bar_id": 1,
  "bar": {
    "id": 1,
    "name": "test2"
  }
}
```

This is ok for a simple example like this, but when I include many to many associations with a lot of items it increases the output significantly, with what is basically redundant info. [Here](https://gist.github.com/felixfbecker/4590121d7616c654eb5c) is a real-life output.

Please disable or allow me to disable that behaviour at query and define time.

**Comment by mickhansen** [comment]
It's redundant info in your case, it's not redundant in everycase.
belongsTo adds an attribute to the mode, cause that's needed to have the asosciation work at all. findAll fetches all attributes by default.

It's not a feature we're likely to implement, but i'll leave it up here incase we find a good design.
A workaround would be a defaultScope that filters out your foreign keys.

**Comment by felixfbecker** [comment]
@mickhansen Could you provide an example? It doesnt seem very right... Maybe I should instead override `toJson()`?

**Comment by felixfbecker** [comment]
It also caused problems for me with legacy databases where the foreign key was the same name as the alias because it wasnt postfixed with `_id`. So I wanted to include `Bar` under the `bar` alias, but the foreign key was also named `bar` instead of `bar_id` :/

**Comment by mickhansen** [comment]
Overwriting toJSON is possible aswell.
With defaultScope you can do something like:

```js
sequelize.define(..., {
  ...
}, {
  defaultScope: {
    attributes: ['....']
  }
});
```

**Comment by arnaudbesnier** [comment]
I observed that if you declare a belongsTo with a specific foreign key (like you did with `bar_id`), the model attribute will contain the attribute `bar_id`. If you don't declare the foreign key, it won't appear. In my opinion, this is a quite strange and inconsistent behaviour.

It might be the origin of the issue you have.
