### ISSUE TITLE
Why do you have to define alias for association twice?

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5215]
It seems like currently you have to set the option `as` _both_ when defining the association with `belongsToMany` aswell as when querying with `include`. Why doesnt the alias I defined initially get persisted? I work with a lot of legacy tables and it really provokes typos to have to define the alias over and over again while querying.

**Comment by mickhansen** [comment]
It's possible to have multiple associations between the same models with different aliases.
You can save a reference to the association and query by it instead:

```js
User.Tasks = User.belongsToMany(Task);

User.findAll({
  include: [User.Tasks]
});
```

**Comment by felixfbecker** [comment]
Nice, I did not know that. Is this documented?

**Comment by mickhansen** [comment]
It's on my todo to move a lot of the documentation to primarily use this way of references in includes since it's less error prone :)
