### ISSUE TITLE
Dont convert DECIMAL to float

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5216]
DECIMAL is used whereever float is not accurate enough, like monetary values. It should not get converted to float automatically, loosing all the accuracy. Instead, it should either be a string (that can be passed to `parseFloat()` or an int (0.010 => 0010)

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/4893

**Comment by felixfbecker** [comment]
@mickhansen sorry, I must have overlooked that. Definitely searched for it.
