### ISSUE TITLE
Use include to return an array of ids

### ISSUE THREAD

**Issue by wanxie** [sequelize/sequelize#5217]
Given
```
User.findById(id, {
    include: [{
          model: File,     // The file model
          attributes: ['id'],
          as: 'files'
     }]
}).then(function(user) {
            console.log(user.get('files'));
});
```
user.get().files will return an array of objects,  [{id: 1}, {id: 2}, {id: 3}].
Anyway in the include options to return just an array of ids, [1, 2, 3]?

**Comment by mickhansen** [comment]
We don't have any option to do flattening like that, and i don't think it should be Sequelize's place to offer features for that sort of flattening.

**Comment by doArcanjo** [comment]
If using postgres Maybe you're looking into 'array_agg' function:
 
```javascript
return controller.db.models.storehouse_product_item_stocks.findAll({
            raw: true,
            where: where,
            attributes: ['storehouse_product_item_stocks.product_id', 'lot_id', 'storehouse_id', 'storehouse_product_item_stocks.original_date',
                [sequelize.fn('count', sequelize.col('remaining_net_weight')), 'number_of_items'],
                [sequelize.literal('array_agg(storehouse_product_item_stocks.id ORDER by storehouse_product_item_stocks.original_date,storehouse_product_item_stocks.id)'), 'ids'],
                [sequelize.fn('sum', sequelize.col('remaining_net_weight')), 'remaining_net_weight'],
                [sequelize.fn('sum', sequelize.col('initial_net_weight')), 'initial_net_weight']],
            include: [
                {
                    model: controller.db.models.product_items,
                    attributes: ['primary_product_package_id', 'secondary_product_package_id', 'tertiary_product_package_id', 'quaternary_product_package_id']
                }],

**Comment by wanxie** [comment]
If I'm using mysql, any suggestion on how I can do this?

**Comment by rgbchris** [comment]
+1 on any thoughts on how to achieve this.

**Comment by janmeier** [comment]
@rgbchris Use `Array.prototype.map` to flatten the array

**Comment by rgbchris** [comment]
@janmeier - would you do that within the callback of the `.then` chained to `findAll()`, or can you flatten the array somewhere within the `findAll` options object?

**Comment by janmeier** [comment]
@rgbchris In the `then` handler - or possibly in an `afterFind` hook if you want to do it more generally

**Comment by Crusader4Christ** [comment]
> If I'm using mysql, any suggestion on how I can do this?
You can use GROUP_CONCAT

**Comment by 7hibault** [comment]
@doArcanjo Could you share a more simple example of using array_agg so I can understand how it works with sequelize ? I tried something like below (based on [that post](https://medium.com/@tonyangelo9707/many-to-many-associations-using-sequelize-941f0b6ac102)) but couldn't make it work (got `missing FROM-clause entry for table `)


```javascript

// Get all orders
const allOrders = await Order.findAll({
    // Group products by id
    attributes: [
        'id',
        'location',
        sequelize.literal('array_agg(products.id)')
    ],
    include: [{
        model: Product,
        as: 'products',
        required: false,
        attributes: ['id'],
        through: {
            model: ProductOrder,
            as: 'productOrders',
            attributes: [],
        }
    }]
});

```
