### ISSUE TITLE
SequelizeDatabaseError: ER_EMPTY_QUERY: Query was empty v3.3.2

### ISSUE THREAD

**Issue by ebrian** [sequelize/sequelize#5223]
I know this has been brought up before, but, I'm curious if the functionality is desired.

The primary time I see this is when an undefined value is provided in the .create() object or an undefined value is assigned to a model instance and .save() is called on it.

Current result: Promise rejection and operation failure.

Potential or desired result:
Treat undefined as another term for null
Example:
user.name = 'Brian';
user.name = name; // name is undefined in this case
console.log(user.name); // Brian

-- or --

Treat undefined as having done nothing to that field
Example:
user.name = 'Brian';
user.name = name: // name is undefined in this case
console.log(user.name); // null

I'm mostly just thinking out loud, I don't have an intimate understanding of the code base at this time so I'm not even sure if that is viable.

**Comment by mickhansen** [comment]
In my opinion undefined is undefined, very different from null.
However a create statement should really never generate an empty query.

**Comment by ebrian** [comment]
Right, totally agree. Question really is how Sequelize should handle an undefined value being assigned to a model instance, and what that translates to before it makes it to the database.

**Comment by ebrian** [comment]
Also, here is the smallest piece of code I have that reproduces this.

```js
return db.users
    .findOne({
        where: {
            user_id: 1
        }
    })
    .then(function(user) {
        var name = {};

        user.first_name = name.name;

        return user
            .save();
    });
```

**Comment by redcomethk** [comment]
Leave a comment to reopen this issue as empty query should not be generated.

**Comment by warriorthereal** [comment]
Still error.

**Comment by adams-family** [comment]
Still an error in 2023 :(

**Comment by ephys** [comment]
Please open a new bug report with all relevant information
