### ISSUE TITLE
CPU usage of bluebird package

### ISSUE THREAD

**Issue by ThomasHambach** [sequelize/sequelize#5224]
Hi guys,

Adding the following as environment variables will dramatically reduce CPU usage of Sequelize. I know that this has to do with the underlying bluebird package, but perhaps this information could be added to the readme?

```
BLUEBIRD_DEBUG = 0
BLUEBIRD_WARNINGS = 0
BLUEBIRD_LONG_STACK_TRACES = 0
```

See http://bluebirdjs.com/docs/api/environment-variables.html for more info

**Comment by mickhansen** [comment]
Thanks for thei nformation @ThomasHambach, we'll definitely find a place to put it in the docs :)

**Comment by benjamingr** [comment]
Yes, this is intentional - it turns on debugging features by default if the environment is not production.
