### ISSUE TITLE
Is it possible to only eager load a nested attribute and not get the entire table?

### ISSUE THREAD

**Issue by Gacnt** [sequelize/sequelize#5225]
E.g.
```
    models.ChatMessage.findAll({
        include: [
            {model: models.User, attributes: ["id"], include: [
                {model: models.Character, as: 'Characters'}
            ]}
        ]
    })
    .then((messages) => {
        console.log(messages);
        res.json({success: true, messages});
    })
    .error((err) => {
        console.warn(err);
        res.json({success: false});
    });
```

Instead of `attributes: ["id"]` can I do like `attributes: false` because I don't need any of the users information and I cannot put an empty array as the argument so I'm just calling the `id` but realistically I need zero fields, I only want the `Characters` associated with their account, is it possible to do this?

Also is it possible to `includeOne`? Instead of getting an array returned, just an object

**Comment by mickhansen** [comment]
@Gacnt What you want atm is not possible.
We'd need to add support for getting an association through another association (it's on the list but not here yet).
