### ISSUE TITLE
Remove callback support for hooks

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#5228]

**Comment by overlookmotel** [comment]
I don't see any major reason not to remove support as the rest of the Sequelize API uses promises. But, on the other hand, I don't see a major advantage to removing them. Promisifying a callback-based hook function only happens once when the hook is created and after that there is no performance cost.

I only use promises myself, so it doesn't affect me anyway!

**Comment by mickhansen** [comment]
Nothing is set in stone yet, however i don't see much point in keeping code around that we don't advertise. And i don't see why we would have one part of the API support callbacks when the rest doesn't, that just seems odd. Would also allow us to remove the current callback guessing code.

**Comment by manchicken** [comment]
Would this include things like model hooks?

**Comment by overlookmotel** [comment]
@manchicken Yes, this would apply to all hooks.

But to be clear, no hooks will be disappearing. Just that writing hooks as a function which then calls a callback to finish will no longer be supported - your hook functions just have to return a promise.

**Comment by felixfbecker** [comment]
This happened in #5924

**Comment by janmeier** [comment]
Cool, I'll ammend the changelog then :)

**Comment by mickhansen** [comment]
I'd like to double check this and verify we have tests for non-bluebird promises aswell as ensuring that the code is cleaned up as much as possible.
