### ISSUE TITLE
Unexpected SQL when including associations with a limit

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#5230]
Hi,

I want to query for a set of "Substances" based on their associations. I also want to paginate the results of this search. The generated SQL places the LIMIT clause in an unexpected location (a sub-query). 

Example javascript is as follows.
```javascript
Substance.findAll({  
   where:{ active:true, type:'foo' },
   include:[{  
      model:lot,
      attributes:[],
      where:{ active:true },
      include:[{  
         model:container,
         attributes:[],
         where:{  
            barcode:{ '$iLike':'%ABCDEFGH%' },
            decommissioned:false,
            locationId:{ '$ne':null }
         }
      }]
   }],
   order:[  
      ['name','ASC']
   ],
   offset:0,
   limit:20
})
```

The resulting SQL the is as follows.
```sql
SELECT "substance".* FROM (
	SELECT "substance"."id", ...
	FROM "substances" AS "substance" 
	WHERE "substance"."active" = true AND "substance"."type" = 'foo'
	AND (
		SELECT "substanceId" FROM "lots" AS "lot" WHERE ("lot"."substanceId" = "substance"."id" AND "lot"."active" = true) LIMIT 1 
	) IS NOT NULL 
	ORDER BY "substance"."name"
	LIMIT 20
) AS "substance" 
INNER JOIN "lots" AS "lots" ON "substance"."id" = "lots"."substanceId" AND "lots"."active" = true 
INNER JOIN "containers" AS "lots.containers" ON "lots"."id" = "lots.containers"."lotId" AND "lots.containers"."barcode" ILIKE '%ABCDEFGH%' AND "lots.containers"."decommissioned" = false AND "lots.containers"."locationId" IS NOT NULL 
ORDER BY "substance"."name";
```

The `LIMIT 20` is positioned to modify the sub-query. I was expecting it to be positioned to modify the outer-most query as follows:

```sql
SELECT "substance".* FROM (
	SELECT "substance"."id", ...
	FROM "substances" AS "substance" 
	WHERE "substance"."active" = true AND "substance"."type" = 'foo'
	AND (
		SELECT "substanceId" FROM "lots" AS "lot" WHERE ("lot"."substanceId" = "substance"."id" AND "lot"."active" = true) LIMIT 1 
	) IS NOT NULL 
	ORDER BY "substance"."name"
) AS "substance" 
INNER JOIN "lots" AS "lots" ON "substance"."id" = "lots"."substanceId" AND "lots"."active" = true 
INNER JOIN "containers" AS "lots.containers" ON "lots"."id" = "lots.containers"."lotId" AND "lots.containers"."barcode" ILIKE '%ABCDEFGH%' AND "lots.containers"."decommissioned" = false AND "lots.containers"."locationId" IS NOT NULL 
ORDER BY "substance"."name"
LIMIT 20;
```

Is this a bug?

Thanks!

**Comment by nareynolds** [comment]
It seems that this is related to the following issues:
#4737, #4716, #4798

**Comment by nareynolds** [comment]
It seems that this is related to the following issues:
#4737, #4716, #4798

**Comment by mickhansen** [comment]
If you actually had the limit outside the subquery it would fail to do it's job since it would be limiting the total cartesian products rather than the end result (which is usually the intention).

The primary issue i see here is that the subquery is not taking the required containers into account (we don't have good supported for nested include wheres with limit :/)

**Comment by demege** [comment]
Hi, Im having the same issue.
Any progress on this topic.

**Comment by mickhansen** [comment]
@demege This issue is not one thing, you'll have to be more specific about your issue.

**Comment by rbjarnason** [comment]
I have the same issue where I would expect limit to limit to the total number of rows, the same way as offset works by adding it to the end of the query.  Currently when I add limit to my Post query it totally breaks it, I get an error: column Post.category_id does not exist while it this column certainly exists and everything works without the limit: option.

Example of my broken limit SQL.
```sql
SELECT "Post".*, "Category"."id" AS "Category.id", "Category"."name" AS "Category.name", "Category"."description" AS "Category.description", "Category"."deleted" AS "Category.deleted", "Category"."icon_file_name" AS "Category.icon_file_name", "Category"."created_at" AS "Category.created_at", "Category"."updated_at" AS "Category.updated_at", "Category"."group_id" AS "Category.group_id", "Category.CategoryIconImages"."id" AS "Category.CategoryIconImages.id", "Category.CategoryIconImages"."name" AS "Category.CategoryIconImages.name", "Category.CategoryIconImages"."description" AS "Category.CategoryIconImages.description", "Category.CategoryIconImages"."license" AS "Category.CategoryIconImages.license", "Category.CategoryIconImages"."cc_url" AS "Category.CategoryIconImages.cc_url", "Category.CategoryIconImages"."original_url" AS "Category.CategoryIconImages.original_url", "Category.CategoryIconImages"."photographer_name" AS "Category.CategoryIconImages.photographer_name", "Category.CategoryIconImages"."formats" AS "Category.CategoryIconImages.formats", "Category.CategoryIconImages"."original_filename" AS "Category.CategoryIconImages.original_filename", "Category.CategoryIconImages"."s3_bucket_name" AS "Category.CategoryIconImages.s3_bucket_name", "Category.CategoryIconImages"."ip_address" AS "Category.CategoryIconImages.ip_address", "Category.CategoryIconImages"."user_agent" AS "Category.CategoryIconImages.user_agent", "Category.CategoryIconImages"."created_at" AS "Category.CategoryIconImages.created_at", "Category.CategoryIconImages"."updated_at" AS "Category.CategoryIconImages.updated_at", "Category.CategoryIconImages"."user_id" AS "Category.CategoryIconImages.user_id", "Category.CategoryIconImages.CategoryIconImage"."created_at" AS "Category.CategoryIconImages.CategoryIconImage.created_at", "Category.CategoryIconImages.CategoryIconImage"."updated_at" AS "Category.CategoryIconImages.CategoryIconImage.updated_at", "Category.CategoryIconImages.CategoryIconImage"."image_id" AS "Category.CategoryIconImages.CategoryIconImage.image_id", "Category.CategoryIconImages.CategoryIconImage"."category_id" AS "Category.CategoryIconImages.CategoryIconImage.category_id", "PostRevisions"."id" AS "PostRevisions.id", "PostRevisions"."name" AS "PostRevisions.name", "PostRevisions"."description" AS "PostRevisions.description", "PostRevisions"."data" AS "PostRevisions.data", "PostRevisions"."created_at" AS "PostRevisions.created_at", "PostRevisions"."updated_at" AS "PostRevisions.updated_at", "PostRevisions"."post_id" AS "PostRevisions.post_id", "PostRevisions"."user_id" AS "PostRevisions.user_id", "Points"."id" AS "Points.id", "Points"."content" AS "Points.content", "PostHeaderImages"."id" AS "PostHeaderImages.id", "PostHeaderImages"."name" AS "PostHeaderImages.name", "PostHeaderImages"."description" AS "PostHeaderImages.description", "PostHeaderImages"."license" AS "PostHeaderImages.license", "PostHeaderImages"."cc_url" AS "PostHeaderImages.cc_url", "PostHeaderImages"."original_url" AS "PostHeaderImages.original_url", "PostHeaderImages"."photographer_name" AS "PostHeaderImages.photographer_name", "PostHeaderImages"."formats" AS "PostHeaderImages.formats", "PostHeaderImages"."original_filename" AS "PostHeaderImages.original_filename", "PostHeaderImages"."s3_bucket_name" AS "PostHeaderImages.s3_bucket_name", "PostHeaderImages"."ip_address" AS "PostHeaderImages.ip_address", "PostHeaderImages"."user_agent" AS "PostHeaderImages.user_agent", "PostHeaderImages"."created_at" AS "PostHeaderImages.created_at", "PostHeaderImages"."updated_at" AS "PostHeaderImages.updated_at", "PostHeaderImages"."user_id" AS "PostHeaderImages.user_id", "PostHeaderImages.PostHeaderImage"."created_at" AS "PostHeaderImages.PostHeaderImage.created_at", "PostHeaderImages.PostHeaderImage"."updated_at" AS "PostHeaderImages.PostHeaderImage.updated_at", "PostHeaderImages.PostHeaderImage"."post_id" AS "PostHeaderImages.PostHeaderImage.post_id", "PostHeaderImages.PostHeaderImage"."image_id" AS "PostHeaderImages.PostHeaderImage.image_id" FROM (SELECT "Post"."id", "Post"."name", "Post"."description", "Post"."status", "Post"."official_status", "Post"."counter_endorsements_up", "Post"."cover_media_type", "Post"."counter_endorsements_down", "Post"."counter_points", "Post"."counter_flags", "Post"."data", "Post"."location", "Post"."created_at" FROM "posts" AS "Post" WHERE "Post"."status" IN ('published', 'inactive') AND "Post"."group_id" = '34' AND "Post"."official_status" IN (-2, -1) LIMIT 25) AS "Post" LEFT OUTER JOIN "categories" AS "Category" ON "Post"."category_id" = "Category"."id" AND "Category"."deleted" = false LEFT OUTER JOIN ("CategoryIconImage" AS "Category.CategoryIconImages.CategoryIconImage" INNER JOIN "images" AS "Category.CategoryIconImages" ON "Category.CategoryIconImages"."id" = "Category.CategoryIconImages.CategoryIconImage"."image_id") ON "Category"."id" = "Category.CategoryIconImages.CategoryIconImage"."category_id" LEFT OUTER JOIN "post_revisions" AS "PostRevisions" ON "Post"."id" = "PostRevisions"."post_id" LEFT OUTER JOIN "points" AS "Points" ON "Post"."id" = "Points"."post_id" AND "Points"."deleted" = false LEFT OUTER JOIN ("PostHeaderImage" AS "PostHeaderImages.PostHeaderImage" INNER JOIN "images" AS "PostHeaderImages" ON "PostHeaderImages"."id" = "PostHeaderImages.PostHeaderImage"."image_id") ON "Post"."id" = "PostHeaderImages.PostHeaderImage"."post_id" ORDER BY (counter_endorsements_up-counter_endorsements_down) DESC, "PostHeaderImages"."updated_at" asc;
```

**Comment by janmeier** [comment]
@rbjarnason Please provide a (SSCCE)[sscce.org]

**Comment by rbjarnason** [comment]
Hi @janmeier 

Unfortunately I don't have the time at the moment, on a very tight deadline and my case is quite complex. I'm getting around the problem now by not using limit, in my case I have at the most few thousand rows and in most cases only hundreds so I just load everything and slice the rows before sending to the client, not optimal but works for now.

For further info then this is my model class:
https://github.com/rbjarnason/your-priorities-app/blob/master/server_api/models/post.js

And here I create the query that I will need limit to work on:
https://github.com/rbjarnason/your-priorities-app/blob/master/server_api/controllers/groups.js#L165

**Comment by boshido** [comment]
Hi @rbjarnason 
For me I can't load everything from the table because there are more than 40,000 rows in that table.
I need this process to be done from the database before querying (if it possible) and I'm not sure that the default findAll, findAndCountAll method can do something like that or not

**Comment by charlesdg** [comment]
Hello,

same problem from my side with include and limit. I add a post on stackoverflow:

http://stackoverflow.com/questions/36406163/sequelize-scope-with-include

**Comment by janmeier** [comment]
@charlesdg Adding the limit to the outer query _will not work_ because of the cartesian product (        `Agency.hasMany(models.service);`- You would be limiting the number of joined rows, not the number of parent rows

**Comment by charlesdg** [comment]
ok right, then I need to write a raw query to have the query I need.

No way to do it in an Active Record way ?

**Comment by janmeier** [comment]
What is the query you need - are you sure you want the limit on the outer query with the implications of the cartesian join (the end result is less than 10 parent rows).

In that case then no, there is currently no way to do that

**Comment by charlesdg** [comment]
what I need is this kind of query:

```
SELECT agency.*, services.id AS "services.id", services.expertise_id AS "services.expertiseId", 
  locationsAgency.id AS "locationsAgency.id", locationsAgency.location_id AS "locationsAgency.locationId", locationsAgency.agency_id AS "locationsAgency.agencyId" 
  FROM agencies AS agency 
  INNER JOIN locations_agencies AS locationsAgency ON agency.id = locationsAgency.agency_id 
  INNER JOIN services ON agency.id = services.agency_id 
  AND locationsAgency.location_id = 9260 
  AND services.expertise_id = 79 
  ORDER BY external_score DESC LIMIT 10
```

So yes, the parent rows (agencies) must be limited to 10 rows.

**Comment by rbjarnason** [comment]
@janmeier Is this a general limitation of Postgres? In my case the query I need is pretty simple, to enable the user to paginate through a list of ideas using offset and limit.  The ideas have associations to other models that ideally would be all eagerly loaded from one query and api call. I would expect this to be a common feature requirement. I can get around offset by using model dates but I do need limit to work for this. Is there any other way to get implement those requirements?

**Comment by janmeier** [comment]
@rbjarnason @charlesdg This is not related to postgres, it is a general database feature - consider the data below (sqlfiddle not working for some reason right now, so you'll have to run it manually:

```sql
CREATE TABLE "user" (
	id SERIAL
);

CREATE TABLE "project" (
	id SERIAL,
	user_id INT
);

INSERT INTO "user"(id) VALUES (DEFAULT), (DEFAULT), (DEFAULT);

INSERT INTO "project" (id, user_id) VALUES (DEFAULT, 1), (DEFAULT, 1), (DEFAULT, 2), (DEFAULT, 2), (DEFAULT, 3), (DEFAULT, 3);

SELECT u.id as u_id, p.id as p_id, p.user_id as p_user_id
FROM "user" u
LEFT JOIN "project" p
	on u.id = p.user_id
LIMIT 2;
```

Output:

| u.id | p.id | p.user_id |
| ---- | ---- | ---- |
| 1 | 1 | 1 |
| 1 | 2 | 1 |

As you can see from the above, a limit on the outer query does _NOT_ limit the parent rows, it limits the joined rows - giving us two rows for user 1, one for project 1 and one for project 2.

@rbjarnason What you want to do is fully supported by sequelize - we use sub-selects to work around the issue which means that will work for the most cases

**Comment by nareynolds** [comment]
Hi all,

I thought I'd share my solution to this problem. It's far from perfect, but it's a generalized solution, and it will work until Sequelize includes has a better one...

I've created the following class-function, `findPage`, for the model I wish to paginate. It takes 3 arguement: the page number (1-indexed), the page size, and the usual set of Sequelize options passed to `Model.findAll`.

It works by executing 2 queries. The first simply calls for all the primary keys (`id`), given the provided options. This list of IDs is then sliced based on the `page` and `pageSize`. This sliced list of IDs is then used to query for all the data originally requested.

There are a couple of caveats to note:
* The provided options are cloned to prevent modifying the original options. The cloning is done using lodash's `cloneDeepWith`. It was necessary to conditionally clone some properties to avoid a known issue (#3781). 
* The `attributes` of all included models is set to an empty array in the first query to speed up Sequelize's post-query processing.

```javascript
        const _modifyOptions = function (obj) {
            // remove offset, limit from options
            if (obj.limit) obj.limit = null;
            if (obj.offset) obj.offset = null;

            // minimize selected attributes for performance
            obj.attributes = [];

            // execute recursively
            if (obj.include && obj.include.length) {
                for (let i = 0; i < obj.include.length; i++) {
                    _modifyOptions(obj.include[i]);
                }
            }
            return obj;
        };

        const modifyOptions = function (options) {
            // clone deep with exception to avoid postgresql-related error
            const opts = _.cloneDeepWith(options, (elem, key) => {
                if (key === 'lib' && elem.hasOwnProperty('native')) {
                    return elem;
                }
            });

            // modify options
            const optsMod = _modifyOptions(opts);
            optsMod.attributes = ['id'];
            return optsMod;
        };

        /**
         * Paginated Model.findAll()
         */
        Model.findPage = function (page, pageSize, options) {
            options = options || {};
            if (page || pageSize) {
                if (typeof page !== 'number' || typeof pageSize !== 'number') {
                    throw new Error("page and pageSize must be provided and must be integers");   
                }
                options.offset = page - 1; // 1-indexed
                options.limit = pageSize;
            }

            // query for record IDs
            const opts = modifyOptions(options);
            return this.findAll(opts)
                .then(records => {
                    let ids = _.map(records, 'id');

                    // slice out IDs for request page
                    if (page && pageSize) {
                        const offset = options.offset * options.limit;
                        const upperLimit = offset + options.limit;
                        ids = ids.slice(offset, upperLimit);                   
                    }

                    // query for page
                    return this.findAll({
                        where: { id: ids },
                        include: options.include,
                        order: options.order,
                        transaction: options.transaction ? options.transaction : null
                    });
                });
        };
```

The major performance issue here is that the first query returns all the IDs in the table. The performance could be improved dramatically if we could set the offset and limit on this query. However, we can't do this, because Sequelize will add the primary keys of any included association to the select clause. Is there anyway to prevent this?

Thanks!

**Comment by rbjarnason** [comment]
Thanks @nareynolds for an interesting workaround I will give it a try :+1: And belated thanks to @janmeier for your explaination :)

**Comment by nareynolds** [comment]
Is there anyway to prevent Sequelize from adding the primary keys of any included association to the select clause if now attributes are requested from those associations?

**Comment by wavded** [comment]
Any progress on this issue?  Or more directly, is there a way to limit joined rows in Sequelize without a writing a raw query?

**Comment by nareynolds** [comment]
It appears the latest pre-release v4 (4.0.0-1) handles the `limit` property differently than it did in v3. Providing a `limit` of 3 will return a max of 3 distinct models regardless of the associations you've included. In other words, `limit` limits the total cartesian product, not the rows returned from the SQL query. 

@janmeier, could you confirm that this is the case?

If this is so, this is awesome and this issue can be closed! It is also much more intuitive considering that the whole point of an ORM is to abstract away the SQL!

**Comment by janmeier** [comment]
@nareynolds I can't find the PR that fixed this, but I'm going to trust you ;)

Anyone else, please open a PR with a test case if you still have problems on `4.0.0-1`

**Comment by hussammaher** [comment]
any solution for this guys ??


>

**Comment by hussammaher** [comment]
5230#issue-126927619

any solution ?
