### ISSUE TITLE
Error when creating schema on Postgresql from v9.4 and above

### ISSUE THREAD

**Issue by immanuel192** [sequelize/sequelize#5233]
I tested and found that, when calling createSchema to create Postgres schema, with postgresql installed version 9.4 and above, the schema will be created, but sequelize will throw exception that schema does not exist.

**Comment by immanuel192** [comment]
Is there any one solve this issue? I solved this issue but with my own plugin for Sails by try / catch when invoking Sequelize to create the schema

**Comment by mickhansen** [comment]
@immanuel192 No work has been done yet.
