### ISSUE TITLE
Sequelize filter parent based on 1:n association but include all associated objects

### ISSUE THREAD

**Issue by DPM1** [sequelize/sequelize#5235]
Hello, 

first of all, great library. Secondly I wonder if one of you clever people could help me. Its possible im missing something obvious, but if not, i'm sure I can't be the only one who would want to achieve this and so hopefully we can write how it is done, or how to work around the problem here. 

Here are 2 sample parent objects - I wish to search over (RelatedData is linked by 1:n association):

    {
        id: 1,
        Field1: "one",
        RelatedData: [{
            Related: 1
        }, {
            Related: 2
        }]
    }
    {
        id: 2,
        Field1: "one",
        RelatedData: [{
            Related: 2
        }, {
            Related: 3
        }]
    }

If i use this filter:

    loModel.findAll({
        where: {
            Field1: 'one'
        },
        include: [{
            model: RelatedModel,
            where: {
                Related: 1
            }
        }],
    })
This will return:

    {
        id: 1,
        Field1: "one",
        RelatedData: [{
            Related: 1
        }]
    }
I want:

    {
        id: 1,
        Field1: "one",
        RelatedData: [{
            Related: 1
        }, {
            Related: 2
        }]
    }
I want to filter the parent based on related - but in the result still see the related data.

Is this possible?

**Comment by mickhansen** [comment]
Instead of using `include.where` you can use a toplevel where wit the `$nested.key$` syntax.

```js
loModel.findAll({
    where: {
        Field1: 'one',
        `$Related.Related`: 1
    },
    include: [{
        model: RelatedModel,
        required: false
    }],
})
```

**Comment by DPM1** [comment]
Sorry, this still only returns the one entry for RelatedData. The where clause still filters the nested array. 

I guess what I am looking for is a "$Related.Related$": {$contains: 1} type of thing. For MSSQL.

Do you know if this exists?

**Comment by mickhansen** [comment]
Ah right, the row is still filtered.
What you wan't isn't possible with a single join in SQL.
I forgot the solution but there's an existing issue somewhere, but basically you probably need to filter with a subquery.

**Comment by aberigle** [comment]
Hi @DPM1, did you find a solution to this issue? I've been looking for the issue @mickhansen mentions but I'm can't find it.

Thanks!

**Comment by DPM1** [comment]
For MSSQL I did not find a satisfactory solution. I forget exactly but using include for the nested models with a where clause worked:

include: [{model: Model, where: {attribute: 1}]

and if I remember correctly sequelize generated the subquerys automatically and everything was almost fine. 

As a side note, in case you are working with MSSQL, with MSSQL I encountered bugs when filtering on nested models and using limit and order by. They are already listed as issues somewhere. Sequelize is a great library and I may consider using it again in the future, but the MSSQL support is not quite bug free enough for me at the moment and time constraints mean I can not delve any deeper.

**Comment by aberigle** [comment]
I've tried adding the where in the include and is filtering the associated items too. I'll keep looking for an alternative, thanks!

**Comment by evenfrost** [comment]
Sorry for necrobump, but @aberigle, have you found any solution to this?

**Comment by hugoobauer** [comment]
I'm also sorry but is there any solution for this issue ?
