### ISSUE TITLE
Sequelize RawQuery return Value()

### ISSUE THREAD

**Issue by taozhi8833998** [sequelize/sequelize#5237]
Hello,
when I use sequelize run raw query(the sql is insert ....on duplicate key ....), if the sql update the value it could return the id of the row, while if not, it return 0.

and if I run a sql first time return a id 
meanwhile, run a other sql and don't update the value but return the same id as the first sql

```
let sql = INSERT INTO A(a,b) VALUES(:a,:b) ON DUPLICATE KEY UPDATE b = VALUE(b)
let id = yiled sequelize.query(sql,{replacements:{a:'test',b:'value'},type: sequelize.QueryTypes.INSERT});
such as id = 20
```

at the same time the other sql run 

```
let sql = INSERT INTO B(a,b) VALUES(:a,:b) ON DUPLICATE KEY UPDATE b = VALUE(b)
let id = yiled sequelize.query(sql,{replacements:{a:'same',b:'time'},type: sequelize.QueryTypes.INSERT});
the sql update nothing and the id should be 0,
while it returns 20
```

execute sql concurrently may be a issue for sequelize
if I am wrong, correct me!  Thanks

**Comment by mickhansen** [comment]
Both your queries are defined as INSERT, INSERT will return the auto increment value from the returned data.

I'm not sure what's returned on the update, but apparently it's 20? Have you tested it out with the CLI?
