### ISSUE TITLE
Update including nested objects

### ISSUE THREAD

**Issue by DPM1** [sequelize/sequelize#5240]
Hi, 

I know it is possible to create an object including nested objects like this:

Product.create({
  title: 'Chair',
  User: {
    first_name: 'Mick',
    last_name: 'Broadstone'
  }
}, {
  include: [ User ]
});

But is there an equivalent for update? Is it possible to update an object and all nested objects in one step? or do you have to recursively loop through the objects calling update?

**Comment by mickhansen** [comment]
No nested update support currently.

**Comment by cperryk** [comment]
Hey @DPM1 — I just pubbed [sequelize-deep-update](https://www.npmjs.com/package/sequelize-deep-update) to do this. It's not very battle-tested yet, but give it a whirl and let me know if you have any issues. (Warning: This will definitely not work in Sequelize 4.0 but I'll do my best to refactor it).

**Comment by sushantdhiman** [comment]
@cperryk You might want to add it to https://github.com/sequelize/sequelize/wiki/Add-ons-&-Plugins
