### ISSUE TITLE
What are the potential callbacks for sequelize finds when nothing is found?

### ISSUE THREAD

**Issue by Gacnt** [sequelize/sequelize#5242]
I'm just trying to do some error handling and I can't find in the documentation what the potential callbacks are for if nothing is found in the database. Is the only callback going to be `null`

```
models.User.findOne(//data)
.then((user) => {
    console.log(user) // what can I be {}? null?
});

models.User.findAll()
.then((users) => {
    console.log(users) // what can I be []? null?
});
```

**Comment by mickhansen** [comment]
`null` and `[]` respectively
