### ISSUE TITLE
SQLite Write Ahead Logging

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/sequelize#5245]
How would I setup Write Ahead Logging when using Sequelize for SQLite, I would like to setup the WAL for a specific database which I am calling from Sequelize.

**Comment by mickhansen** [comment]
Would probably be a job for an after connection hook: https://github.com/sequelize/sequelize/issues/5246 which doesn't exist yet.

**Comment by damianobarbati** [comment]
any news on this? needed for same reason and other pragma statements

**Comment by RenathoAzevedo** [comment]
Although Sequelize does not offer it native, we can user raw query to achieve it: `sequelize.query("PRAGMA journal_mode=WAL;")`

**Comment by bradisbell** [comment]
For anyone else looking at this, it seems that the `afterConnect` hook exists now, but it doesn't seem to work with SQLite, unfortunately.  Separate issue opened here:  https://github.com/sequelize/sequelize/issues/12487
