### ISSUE TITLE
All instances of fieldsOrOptions should be refactored to only support options

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#5248]

**Comment by sushantdhiman** [comment]
Hi @mickhansen , @janmeier 

As per our discussion in #5925 , there are no methods that are using `fieldsAndOptions` other than `aggregate`, `increment` and `decrement`. There are some code cleanup task but not related to this issue. May be we can close this issue ?

For code cleanup task we can open a new issue. What do you think?

**Comment by janmeier** [comment]
Yep, let's close this
