### ISSUE TITLE
A lot of Promise (bluebird) warnings

### ISSUE THREAD

**Issue by tornillo** [sequelize/sequelize#5251]
Hi!

Bluebird has a excellent feature to testing of improper Promise usage (by enabling ```BLUEBIRD_DEBUG=1```).
In "development" environment warnings are enabled by default (according to the doc http://bluebirdjs.com/docs/api/environment-variables.html).

When I turned on this option for our "test" environment, I saw a huge number of warnings ...
Most of them belongs to mocha. PR (https://github.com/mochajs/mocha/pull/1967) has long been merged, but the new version has not yet been released.

Ok. I installed mocha directly from master and run the tests again.
Now there were a lot of warnings with ```Warning: a promise was rejected with a non-error```, and only one place with more important ```Warning: a promise was created in a handler but was not returned from it```.
**I've fixed them** (https://github.com/sequelize/sequelize/pull/5250).

But there are still some warnings, and I do not know what to do with them.
```Warning: a promise was rejected with a non-error: [object Array]```
```Warning: a promise was rejected with a non-error: [object Object]```
For example, here (https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2147) a Promise rejects with an array of objects, but "by design" is not allowed nothing except of ```instance of Error``` in error handler.

**Comment by janmeier** [comment]
Hmm, good question - We should probably add a container error type to store the bulkcreate errors. Dunno if it would be a bc break, or if it could be considered a bug-fix since the current code is doing promises wrong

**Comment by tornillo** [comment]
A new PR (https://github.com/sequelize/sequelize/pull/5253) completely removes the warnings with type
```Warning: a promise was rejected with a non-error: [object Object]```

And now remained only these warnings:
```Warning: a promise was rejected with a non-error: [object Array]```
They refer to only one place in the code https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2147

**Comment by mickhansen** [comment]
Semi break, might aswell schedule it for 4.0

**Comment by tornillo** [comment]
I agree.

**Comment by benjamingr** [comment]
If you'd like I would be happy to assist with any bluebird related warnings

**Comment by arnaudbesnier** [comment]
Hi guys! I see that the PR #5253 is merged. Does it mean that this issue is fixed in the 4.0 Release?

**Comment by janmeier** [comment]
Yes - Actually the corresponding PR was merged in 3.22
