### ISSUE TITLE
column "typarray" does not exist error on PostgreSQL 8.2

### ISSUE THREAD

**Issue by huguesdk** [sequelize/sequelize#5254]
What is the minimum supported version of PostgreSQL? I know it’s quite an old version, but Sequelize used to work well on PostgreSQL 8.2. Since commit 401adaf24b72e4d0c9212393f72e1080a504073c, it now fails with the error:

```
column "typarray" does not exist
```

because the typarray column was added to pg_type in PostgreSQL 8.3. If that query is removed, it works.

**Comment by mickhansen** [comment]
We only test against postgres 9.4 but try to support back to before 9.0.
8.2 is not we're looking to officially support but we would welcome a PR that does a version check before fetching typarray.

**Comment by doArcanjo** [comment]
Same issue

**Comment by barkerb1** [comment]
Same here as well, any updates on this issue?  Thanks

**Comment by marckaraujo** [comment]
+1

**Comment by vickymin** [comment]
I'm afraid that it still not works when connecting to Postgres SQL 8.2
I guess the commit above just fix the bug when query, but it did fail when connect
Following is the error:
Unable to connect to the database: { [error: column "typarray" does not exist]

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/7266
