### ISSUE TITLE
set method and validate in field

### ISSUE THREAD

**Issue by zhengnz** [sequelize/sequelize#5256]
Hello, when set method and validate in field, it will thorw error at any time. Is it a bug?
  password: {
      type: DataTypes.STRING 32
      validate:
        len:
          args: [5, 12]
      set: (val) ->
        @setDataValue 'password', utils.md5 "#{val}#{conf.md5_str}"
        return
    }

**Comment by mickhansen** [comment]
What error? When does the error happen?

**Comment by zhengnz** [comment]
When update this field, the validate error will throw, if I remove the validate, it will success

**Comment by mickhansen** [comment]
What error? What type of update? `instance.update`?
Please provide full information when reporting issues.
When an error occurs please always include the error and the stack, vital information for pretty much everyone.
