### ISSUE TITLE
empty updateOnDuplicate increments primary key

### ISSUE THREAD

**Issue by QuantumKing** [sequelize/sequelize#5257]
Whenever I use `bulkCreate` with an empty `updateOnDuplicate` array it will increment the primary key of a duplicate. I expected that it would leave the row unchanged ... 

```js
return Model.bulkCreate(records, {
  updateOnDuplicate: []
})
```
Is this a bug?

**Comment by mickhansen** [comment]
What does the SQL query look like?

**Comment by QuantumKing** [comment]
INSERT INTO `ActionParticipants` (`_id`,`action_id`,`user_participant_id`,`status`,`permissions`,`receive_updates`) VALUES (NULL,1,1,'accepted',0,true) ON DUPLICATE KEY UPDATE `_id`=VALUES(`_id`),`action_id`=VALUES(`action_id`),`user_participant_id`=VALUES(`user_participant_id`),`group_participant_id`=VALUES(`group_participant_id`),`notification_group_id`=VALUES(`notification_group_id`),`reason_for_joining`=VALUES(`reason_for_joining`),`status`=VALUES(`status`),`permissions`=VALUES(`permissions`),`receive_updates`=VALUES(`receive_updates`);

**Comment by QuantumKing** [comment]
`_id` is the primary key

**Comment by MrVoltz** [comment]
This is MySQL bug (or "feature"), not Sequelize's. More info: http://stackoverflow.com/questions/2787910/why-does-mysql-autoincrement-increase-on-failed-inserts

**Comment by QuantumKing** [comment]
Isn;t that query saying "on duplicate key, update everything?". I want it to say "on duplicate key, update nothing"

**Comment by QuantumKing** [comment]
I understand the MySQL "feature" happens when you try to update the primary key, but the primary key shouldn't be in that list in the first place.

**Comment by mickhansen** [comment]
The primary key should be left out of the insert if it's properly defined with primaryKey: true and autoIncrement: true.

In postgres your serials will increment even if a transaction rolls back, they are totally atomic.
insert ids in mysql are probably the same, and it will attempt to generate one before executing an insert.

**Comment by QuantumKing** [comment]
this is my model definition
```js
{
    _id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    action_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    user_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    group_id: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
    notification_group_id: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
    reason_for_joining: DataTypes.TEXT,
    status: {
      type: DataTypes.ENUM('pending', 'accepted', 'rejected', 'withdrawn'),
      defaultValue: 'pending'
    },
    permissions: {
      type: DataTypes.INTEGER,
      defaultValue: 0 // No permissions
    },
    receive_updates: {
      type: DataTypes.BOOLEAN,
      defaultValue: true
    }
  }
```

**Comment by QuantumKing** [comment]
how come its included in the insert?

**Comment by mickhansen** [comment]
Possibly a bug, i recall writing logic that only leaves in the primary key if absolutely necessary.
In any case i'm not sure this will fix your issue, have you tried running the query manually without the id in it and seeing what happens?

**Comment by QuantumKing** [comment]
I haven't tried that. To get around the issue I just use `updateOnDuplicate: ['action_id']` since I know `action_id` doesn't change.

**Comment by dubanflorin** [comment]
_id=VALUES(_id) is the problem. Using _id=LAST_INSERT_ID(_id) would return the correct _id for the row in all situations. (new row, updated row or row not changed at all)
