### ISSUE TITLE
Adding Column for Through Table

### ISSUE THREAD

**Issue by DavidTPate** [sequelize/sequelize#5258]
I have a M:M relationship between 2 tables in my MySQL database and I want to add a column to my through table.

Here's a diagram of basically what I'm trying to achieve:
![screen shot 2016-01-19 at 11 10 45 am](https://cloud.githubusercontent.com/assets/2223120/12424264/53d2c7ec-be9d-11e5-8967-0788d55e3633.png)

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('database', 'username', 'password', {
    host: 'localhost',
    dialect: 'mysql'
});
const Users = sequelize.define('users', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true
    },
    username: {
        type: Sequelize.STRING
    }
});
const Tasks = sequelize.define('tasks', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true
    },
    name: {
        type: Sequelize.STRING
    },
    description: {
        type: Sequelize.STRING
    }
});

Users.belongsToMany(Tasks, {
    through: 'UserTasks'
});

Tasks.belongsToMany(Users, {
    through: 'UserTasks'
});
```

But I'm not sure how to go about adding the `role` column to my through table. I'm pretty sure I could do it by defining a model for my Through table and then linking the users to it and tasks to it in a similar manner. Is there a better way that was intended?

**Comment by mickhansen** [comment]
`through` accepts a model as argument, it will then be included when you query

**Comment by DavidTPate** [comment]
Gotcha. So I would create a model form my through table and then reference it in the associations I am setting up.

Thanks!
