### ISSUE TITLE
Feature: String Functions like LEFT()

### ISSUE THREAD

**Issue by jpodwys** [sequelize/sequelize#5265]
I would really appreciate being able to SELECT a substring of text, especially when retrieving a list of items to show as previews. Does anyone know whether this exists or is being worked on?

Thanks!

**Comment by mickhansen** [comment]
`attributes` for find supports a syntax like:

```js
attributes: [
  [db.fn('LEFT', db.col('mycolumn'), 10), 'mycolumn_cut']
]
```

**Comment by jpodwys** [comment]
Thanks! This is exactly what I needed!

**Comment by dbads** [comment]
WHAT 

> `attributes` for find supports a syntax like:
> 
> ```js
> attributes: [
>   [db.fn('LEFT', db.col('mycolumn'), 10), 'mycolumn_cut']
> ]
> ```

what is db?
