### ISSUE TITLE
Add scope to nested create

### ISSUE THREAD

**Issue by paulussup** [sequelize/sequelize#5266]
I am using the nested create feature and think it would be good to be able to add scope variables to nested models.

```
organisation.createUser({
  Products: [ {}, {} ]
}, {
  include: [{
  model: Products,
  scope: {
    OrganisationId: organisation.get('id')
  }
}]
})
```

I have something working which seems simple enough. Is this something worth working on?

**Comment by mickhansen** [comment]
What would `scope` do in this example? We don't even have that sort of syntax for includes.

**Comment by paulussup** [comment]
```
Organisations.hasMany(Users)
Organisations.hasMany(Products)
Users.belongsTo(Organisations)
Users.hasMany(Products)
Products.belongsTo(Users)
Products.belongsTo(Organisations)
```

It would set the foreign key OrganisationId on Products in this case but potentially any other value that was specified

Going through the [nested create code](https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L719) I see that the include object is used to set the foreign key if another option was passed it could be accessed to set values.

**Comment by mickhansen** [comment]
So you esentially want to have a set of values that get applied to all the objects you passed to the create statement?

Seems oddly specific for something you can accomplish with a map function

**Comment by paulussup** [comment]
Essentially yes... 

That is true for the above example... If the nesting is deeper and more complex I find the more ungainly and oddly specific :) the map function becomes.

Ive been working on it for the last couple of days and think that it would be a useful feature I really appreciate the nested create and it doesn't seem too much of a hassle or too far from the sequelize philosophy
