### ISSUE TITLE
Behaviour of alias (as) to foreignKey translations in associations should be synchronized.

### ISSUE THREAD

**Issue by rmzg** [sequelize/sequelize#5267]
Right now the various associations (hasOne, belongsTo, hasMany, etc) treat aliases differently when attempting to create implicit, not defined, foreignKey names. This behaviour should be made consistent across all the different associations, either by using the alias as the foreignkey or not using it or by requiring an explicit foreignKey definition when using an alias as part of an association definition.

**Comment by sushantdhiman** [comment]
Who is already using proper `as` behavior

- [x] `hasOne` https://github.com/sequelize/sequelize/blob/master/lib/associations/has-one.js#L50
- [x] `belongsTo` https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to.js#L50
- [ ] `hasMany` https://github.com/sequelize/sequelize/blob/master/lib/associations/has-many.js#L75
- [ ] `belongsToMany` https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L116

**Comment by overlookmotel** [comment]
@mickhansen @janmeier @sushantdhiman Could one of you re-open this issue so we can discuss whether to change the keys created by `belongsToMany()` to use `as` or not?
