### ISSUE TITLE
seqluelize.fn with > sign

### ISSUE THREAD

**Issue by jpodwys** [sequelize/sequelize#5271]
I'm trying to have my database query add ellipsis to a column output if the output is greater than 140 characters. Everything works great up until sequelize encounters the `>` sign. I tried wrapping `> 140` in a `sequelize.literal`, but sequelize requires that a comma come before the `>` regardless, which breaks the generated query.

Does anyone know if it's possible to do what I'm trying here? Thanks!

```javascript
return Entry.findAndCountAll({
  where: {ownerId: userId},
  attributes: [
    'id', 'ownerId', 'date', 'isPublic',
    [sequelize.fn('CONCAT',
      sequelize.fn('LEFT', sequelize.col('text'), 140),
      sequelize.fn('IF', 
        sequelize.fn('LENGTH', sequelize.col('text')),
      > 140, "...", "")), // This doesn't work
    'text']
  ],
  order: [['date', 'DESC']],
  limit: offset,
  offset: 0,
  raw: true
});
```

**Comment by mickhansen** [comment]
In this case you might have to go with:

```js
sequelize.fn('IF', 
  sequelize.literal('LENGTH(text) > 140'),
  "...",
  ""
)
```

**Comment by jpodwys** [comment]
Hah, so that's how `sequelize.literal` works! Thank you yet again!
