### ISSUE TITLE
Nested self referential 1:1 associations

### ISSUE THREAD

**Issue by DPM1** [sequelize/sequelize#5278]
Hi,

I am having difficulty getting sequelize to create and find an object which is like this:

	"filter": {
		"fieldname": "FilterField1",
		"comparetype": "=",
		"criteria": "1",
		"filter": {
			"fieldname": "And",
			"comparetype": "=",
			"criteria": "and",
	        	"filter": {
		        	"fieldname": "And",
		        	"comparetype": "=",
		        	"criteria": "and"
	        	}
		}
	}

With the realtion setup:

		loModels.Filter.hasOne(loModels.Filter, {
			as: 'filter',
			constraints: false 
		});

Are nested self referential relationships supported?

Thanks in advance for feedback.

**Comment by mickhansen** [comment]
It's supported, but might not have the most extensive case covering.
For self referential associations you should always use the `foreignKey` option.

What's not working exactly?

**Comment by DPM1** [comment]
This is the relationship setup:
		loModels.Filter.hasOne(loModels.Filter, {
			as: 'and_filter',
			foreignKey: 'AndFilterId',
			constraints: false 
		});

And this Test:

		it("Should create nested and_filters", function (done) {
			var filter = {
				"fieldname": "And",
				"comparetype": "=",
				"criteria": "And",
				"and_filter": {
					"fieldname": "And1",
					"comparetype": "=",
					"criteria": "and1",
					"and_filter": {
						"fieldname": "And2",
						"comparetype": "=",
						"criteria": "and2"
					}
				}
			}

			db_models.GetModel("Filter", function (err, loModel) {
				loModel.create(filter, {
					include: [{
						all: true,
						nested: true
					}]
				}).then(function (created) {
					logger.debug(created)
					done()
				}).catch(function (err) { //Error handler
					logger.error(err);
					done()
				});
			});
		});

Sucessfully creates in the DB the filter with fieldname = "And" (level 0) 
It also creates the "And1" filter (level1) but does NOT create the "And2" filter. 
No error is thrown, No insert is attempted. It just inserts the root level, then one level down, then stops.

**Comment by DPM1** [comment]
I think I have misunderstood what nested: true does because if i replace the include with:

					include: [{
						all: true,
						nested: true,
						include: [{
							all: true,
							nested: true,
							include: [{
								all: true,
								nested: true
							}]
						}]
					}]

Then it works.

**Comment by mickhansen** [comment]
@overlookmotel might be able to chime in here as to whether or not nested: true should dig all the way down or just one level

**Comment by DPM1** [comment]
I have just re-opened the issue but feel free to close it if this does not strike you as a bug at the moment. 

Adding more nested include all levels fixes the problem BUT massively hits performance. There really needs to be a more performant method of retrieving nested data. Its the SQL select that is generated - it becomes very big and takes ages when there are more nested include [{all:true}] elements added - this can't be the best way to deal with it

Unless nested is actually supposed to do what I thought - in which case, this is a bug i think.

Thank you as always for your quick responses.

**Comment by mickhansen** [comment]
include all includes all, what did you expect exactly?
if you're looking to own include a chain of filter, do that instead of using include all.
You might also want to take a look at https://github.com/overlookmotel/sequelize-hierarchy

**Comment by DPM1** [comment]
Fair point. Will take a look at the lib. Thanks
