### ISSUE TITLE
What's the point of overriding Models's toString()?

### ISSUE THREAD

**Issue by ryanrolds** [sequelize/sequelize#5279]
Why override `Model.prototype.toString()`? It only makes trying to inspect the model more difficult.

https://github.com/sequelize/sequelize/blob/0de404640d4c71e2d1f1259356650dfb586a248b/lib/model.js#L117

```
Model.prototype.toString = function () {
  return '[object SequelizeModel:'+this.name+']';
};
```

**Comment by mickhansen** [comment]
To make logging/serialization easier. There are better tools for inspecting than .toString().
