### ISSUE TITLE
How to use a sequelize implementation sum (a - b) as ab

### ISSUE THREAD

**Issue by scliuyang** [sequelize/sequelize#5281]
I'm sorry, my English is poor。
I have a table named orders,There are two fields:ord_num,customer_num。
I want to implement the following SQL

```
select sum(ord_num - customer_num) as old_num from orders;
```
How do I use sequelize achieve,thanks

**Comment by mickhansen** [comment]
GitHub is for issues, feature requests and bugs, please use StackOverflow/IRC/Slack for general help questions.

```js
{
  attributes: [
    [db.fn('SUM', db.literal('ord_num - customer_num')), 'old_num']
  ]
}
```
