### ISSUE TITLE
Using a Scope as a Model

### ISSUE THREAD

**Issue by DavidTPate** [sequelize/sequelize#5285]
I have a table which contains a generic type of object that is re-used in different contexts. For this example let's say I have `groups` and `groupTypes`. In this example there's 2 types of groups, `roles` and `teams`, and I want to make it more fluent to access either.

So I would have models like the following:

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('database', 'username', 'password', {
    host: 'localhost',
    dialect: 'mysql'
});

var GroupType = sequelize.define('groupType', {
    id: {
        primaryKey: true,
        type: Sequelize.INTEGER
    },
    name: {
        type: Sequelize.STRING
    }
});

var Group = sequelize.define('group', {
    id: {
        primaryKey: true,
        type: Sequelize.INTEGER
    },
    name: {
        type: Sequelize.STRING
    }
}, {
    scopes: {
        roles: {
            include: [
                {
                    model: GroupType,
                    where: {
                        name: 'roles'
                    }
                }
            ]
        },
        teams: {
            include: [
                {
                    model: GroupType,
                    where: {
                        name: 'roles'
                    }
                }
            ]
        }
    }
});

Group.hasOne(GroupType);
GroupType.hasMany(Group);
```

What I'd like to be able to do is call `sequelize.models.teams.findAll()` and `sequelize.models.roles.findAll()` which would be accessing `sequelize.models.group.scope('teams')` and `sequelize.models.group.scope('roles')` respectively. 

Is there a way for me to define a scope as a model? It seems to me like this could be a good point for some abstraction of the data model when dealing with more dynamic items.

**Comment by mickhansen** [comment]
No way to do this currently, but you could write your own implementation rather quickly i'd think.
