### ISSUE TITLE
Query by multiple relation conditions

### ISSUE THREAD

**Issue by israelidanny** [sequelize/sequelize#5286]
Suppose I have a table named `posts` and a table named `tags` that has a HABTM relationship via a table named `post_tags`.

I'm trying to query for all the posts that have a tag named `featured` *AND* a tag named `bestseller`. If the post is related to only one of these, I do *not* want it.

The documentation seems to be very minimal on relation queries. How would I go about querying this?

**Comment by israelidanny** [comment]
In MySQL, these are the two queries we could achieve it through:
http://stackoverflow.com/questions/1870950/habtm-query-help

I'm wondering what's the equivalent in sequelize.

**Comment by mickhansen** [comment]
SO suggests using two joins on the same set of tables, Sequelize does not allow this ATM

**Comment by israelidanny** [comment]
Actually, the joins ended up being very non performant (exponential slowdown with each filtered tag), so I went for the GROUP HAVING solution. Is that one possible via Sequelize?

**Comment by mickhansen** [comment]
Both group and having are supported yes.
