### ISSUE TITLE
Defining a custom instance method named "then" breaks a lot of things

### ISSUE THREAD

**Issue by reidrankin** [sequelize/sequelize#5290]
I'm handling objects that represent tasks that will be completed (by another application) at some point in the future. In order to allow me to treat these tasks like promises, I added a "then" function to the instanceMethods list which reloads the Instance every 5 seconds or so and fires the provided callbacks when the database entry is updated to report completion.

However, sequelize uses bluebird's Promise.bind(this) a lot internally. Bluebird's bind function changes behavior when passed a "thenable". Instead of binding to the argument explicitly passed, it binds to its resolution value.

This is an unfortunate design choice by the Bluebird folks, but given that they have made it, users wanting explicit bind behavior from Promise.bind() must be sure that the object they pass in does not have a method named "then".

Either (preferably) the usage of Promise.bind() in Sequelize needs to be replaced with something more robust, or an explicit error needs to be thrown when defining a Sequelize model with an instance method named "then".

**Comment by mickhansen** [comment]
`Promise.bind` could be replaced with regular `.bind()` calls on the methods. I do strongly prefer the promise.bind style though.
