### ISSUE TITLE
Unhandled rejection TypeError: val.replace is not a function

### ISSUE THREAD

**Issue by tankerkiller125** [sequelize/sequelize#5292]
I'm thinking that this is the same problem to #5082 however I will go ahead and post all of my code related to the model and the problem.

Model:
```javascript
/* jshint indent: 2 */

module.exports = function (sequelize, DataTypes) {
    return sequelize.define('users', {
        id: {
            type: DataTypes.INTEGER(10),
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        email: {
            type: DataTypes.STRING,
            allowNull: false
        },
        password: {
            type: DataTypes.STRING,
            allowNull: false
        },
        permissions: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        last_login: {
            type: DataTypes.DATE,
            allowNull: true
        },
        username: {
            type: DataTypes.STRING,
            allowNull: false
        },
        created_at: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: '0000-00-00 00:00:00'
        },
        updated_at: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: '0000-00-00 00:00:00'
        },
        deleted_at: {
            type: DataTypes.DATE,
            allowNull: true
        }
    }, {
        tableName: 'users',
        freezeTableName: true
    });
};
```
Setup:
```javascript
Sequelize = require('sequelize');
orm = new Sequelize(config.get('mysql.database'), config.get('mysql.username'), config.get('mysql.password'), {
    host: config.get('mysql.host'),
    port: config.get('mysql.port'),
    dialect: 'mysql',
    define: {
        timestamps: false
    }
});
```

Usage:
```javascript
var mentions = function (message) {
    var userModel = orm.import(__dirname + '/models/users.js');
    // Match twitter like mentions
    var usernames = message.match(/\B@[a-z0-9_-]+/gi);
    var realUsers = {};
    // Verify that the user exist in the database
    var verify = function(element, index, array) {
        console.log(element);
        userModel.find({
            where: {
                username: element.replace('@', '')
            }
        }).then(function(data) {
            if(data != null) {
                realUsers[data.username]
            }
        })
    };
    // If there are mentioned user check them!
    if(usernames !== null) {
        usernames.forEach(verify);
        return realUsers;
    } else {
        // Return empty if there are no mentioned users.
        return {};
    }
};
```

And actually calling the mention function:
```javascript
var json = JSON.parse(data);
var mentionsObj = mentions(json.message);
```

**Comment by janmeier** [comment]
What data is in `data` - testing with foo and bar works fine for me

**Comment by tankerkiller125** [comment]
I'm guessing in the last code block?

It contains a JSON string from a websockets connection (socket.io) and the JSON would be something like:

```json
{
    "username": "username",
    "color": "#F2FAF3"
    "access_token": "oauth2token",
    "channel": "tankerkiller125"
    "message": "Messages support [markdown](https://daringfireball.net/projects/markdown/)!"
}
```

**Comment by janmeier** [comment]
Still works fine for me 
```sql
SELECT `id`, `email`, `password`, `permissions`, `last_login`, `username`, `createdAt`, `updatedAt` FROM `users` AS `users` WHERE `users`.`username` = 'tankerkiller125' LIMIT 1;
```

Can you provide a [SSCCE](HTTP://SSCCE.ORG/) 

Also, note that `realUsers` will never be filled, because you return it, before the query is done

**Comment by tankerkiller125** [comment]
I'll see what I can do.

**Comment by tankerkiller125** [comment]
@janmeier I am unable to duplicate the bug in a small test environment. I would take the code I used for the actual project and use it but unfortunately a lot of it is proprietary. I will continue trying to duplicate it however.

**Comment by janmeier** [comment]
@tankerkiller125 I'll go ahead and close this issue in the meanwhile then - Please ping me when you have something new

**Comment by rguntha** [comment]
Hi, I am facing this issue on the 3.20.0 version. I am using the Managed transactions. It works fine during creation, but fails while updating the object. Below is the stack trace:

When I debugged, I found that the val was the transaction object on which it's trying to do replace.

Hope this helps.


Executing (default): SELECT `pinCodeId`, `countryId`, `pinCode`, `longitude`, `latitude`, `createdByUserId`, `modifiedByUserId`, `statusId`, `createdDate`, `modifiedDate` FROM `PinCode` AS `PinCode` WHERE `PinCode`.`pinCode` = '4124231' AND `PinCode`.`coun
tryId` = 2 AND `PinCode`.`statusId` = 1 LIMIT 1;
Executing (cf2fa39c-5055-4ffa-8548-0984ef9cec6e): SELECT `Shelter`.`shelterId`, `Shelter`.`shelterName`, `Shelter`.`shelterDescription`, `Shelter`.`capacity`, `Shelter`.`openFromDate`, `Shelter`.`openTillDate`, `Shelter`.`addressLine1`, `Shelter`.`addressL
ine2`, `Shelter`.`localityId`, `Shelter`.`pinCodeId`, `Shelter`.`longitude`, `Shelter`.`latitude`, `Shelter`.`isTemporary`, `Shelter`.`contactUserId`, `Shelter`.`phoneNumber1`, `Shelter`.`phoneNumber2`, `Shelter`.`createdByUserId`, `Shelter`.`createdDate`,
 `Shelter`.`modifiedByUserId`, `Shelter`.`modifiedDate`, `Shelter`.`statusId`, `ShelterFacilities`.`shelterFacilityId` AS `ShelterFacilities.shelterFacilityId`, `ShelterFacilities`.`shelterId` AS `ShelterFacilities.shelterId`, `ShelterFacilities`.`shelterF
acilityTypeId` AS `ShelterFacilities.shelterFacilityTypeId`, `ShelterFacilities`.`quantity` AS `ShelterFacilities.quantity`, `ShelterFacilities`.`createdByUserId` AS `ShelterFacilities.createdByUserId`, `ShelterFacilities`.`createdDate` AS `ShelterFaciliti
es.createdDate`, `ShelterFacilities`.`modifiedByUserId` AS `ShelterFacilities.modifiedByUserId`, `ShelterFacilities`.`modifiedDate` AS `ShelterFacilities.modifiedDate`, `ShelterFacilities`.`statusId` AS `ShelterFacilities.statusId` FROM `Shelter` AS `Shelt
er` LEFT OUTER JOIN `ShelterFacility` AS `ShelterFacilities` ON `Shelter`.`shelterId` = `ShelterFacilities`.`shelterId` AND `ShelterFacilities`.`statusId` = 1 WHERE `Shelter`.`shelterId` = 5 AND `Shelter`.`statusId` = 1;
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\sql-string.js:63:15)
    at Object.QueryGenerator.escape (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:973:22)
    at Object.QueryGenerator.whereItemQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2229:22)
    at C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1865:25
    at C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\lodash\lodash.js:4040:15
    at baseForOwn (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\lodash\lodash.js:2573:24)
    at Function.forOwn (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\lodash\lodash.js:11030:24)
    at Object.QueryGenerator.whereItemsQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1864:9)
    at Object.QueryGenerator.whereQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1836:22)
    at Object.QueryGenerator.updateQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:480:19)
    at QueryInterface.bulkUpdate (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\query-interface.js:599:33)
    at C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\model.js:2630:32
    at tryCatcher (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:605:10)

Executing (cf2fa39c-5055-4ffa-8548-0984ef9cec6e): ROLLBACK;
PUT /shelter/5?authToken=f98187e5f974c2d761576b885f964e56621113fe 200 51.104 ms - 104

**Comment by janmeier** [comment]
@rguntha Please open a new issue, and follow the template there :)

**Comment by benjaminhon** [comment]
i have this problem too

**Comment by janmeier** [comment]
@benjaminhon Then please show some code that replicates the issue! [SSCCE](HTTP://SSCCE.ORG/)

**Comment by benjaminhon** [comment]
My model is as follows
```
# model
Map = sequelize.define('map', {
  name: {
    type:       Sequelize.STRING
    primaryKey: true
  }
  image:  Sequelize.BLOB
  scale:  Sequelize.FLOAT
}, {
  timestamps: false
})

MapGeometry = sequelize.define('mapGeometry', {
  geometry:   Sequelize.GEOMETRY
  properties: Sequelize.JSONB
}, {
  timestamps: false
})

# relationships
MapGeometry.belongsTo(Map)
Map.hasMany(MapGeometry)
```

the error comes when i do
```
Map.findOne({
        where: {name: name} 
      })
      .then (map) ->
        items = layers.map ({geometry, properties}) ->
          MapGeometry.create({
            geometry:   geometry.geometry
            properties: properties
          })
        map.setMapGeometries(items)
```

am i doing something wrong?

**Comment by janmeier** [comment]
`layers.map` returns an array of promises, not an array of instances - You need to wait for the create calls to return. Have a look at Promise.all

**Comment by benjaminhon** [comment]
Ah, thanks I changed it to
```
Map.findOne({
  where: {name: name} 
  attributes: ['name']
}).then (map) ->
  Promise.all(
    layers.map ({geometry, properties}) ->
      MapGeometry.create({
        geometry:   geometry.geometry
        properties: properties
      })
  ).then (items) ->
    map.setMapGeometries(items)
```
and it works.

However, can i ask if this is the right way? when i do MapGeometry.create, isn't that created in the database already (but without the mapName field)? then i have to do map.setGeometries, just to associate the geometries with the mapName?

It sounds like i should be doing something like map.setMapGeometries(geometries), and the geometries should be added with mapName referencing the map. It seems a bit iffy to me, but its the first time I'm using an ORM.

Thanks again

**Comment by janmeier** [comment]
You have two other options - You can either use [`createAssocation`](http://docs.sequelizejs.com/en/latest/api/associations/has-many/#createassociationvalues-options-promise)
```js
Map.findOne({
  where: {name: name} 
  attributes: ['name']
}).then (map) ->
  Promise.all(
    layers.map ({geometry, properties}) ->
      map.createMapGeometry({
        geometry:   geometry.geometry
        properties: properties
      })
  )
``` 
Or [nested creation](https://github.com/sequelize/sequelize/pull/3386) if you are creating the map instance as well

```js
Map.create({
  name: name
  mapGeometries: [...]
}, {
  include: [MapGeometry]
}).then (map) ->
  Promise.all(
    layers.map ({geometry, properties}) ->
      map.createMapGeometry({
        geometry:   geometry.geometry
        properties: properties
      })
  )
```

**Comment by benjaminhon** [comment]
ah thanks, that makes more sense

**Comment by iszlailorand** [comment]
... probably you assign something difrent from what is expected.   (object instead of string, integer)
