### ISSUE TITLE
Sequelize - create and get new entity (including primary key). From a view

### ISSUE THREAD

**Issue by istrau2** [sequelize/sequelize#5293]
We have an app where we are trying to implement sequelize against a postgres db. The structure we have is one where all of the models are created manually by us to reflect postgres views (tables are too normalized/abstracted to be used by the application). 

We have run into a problem when we try to create a persistent intance.
First the call to create:

```javascript
return sqModel.create(entity, {transaction: transaction})
.then(function(savedEntity) {
    //... process entity
}).catch(handleItemSaveError(entity, entityState));
```

The problem: savedEntity has a primary key value = null. I know the solution to this is often to set autoIncrement: true in the model definition. In this case, I have checked and I am definitely setting it to true.

I think the issue may be related to the db. In fact, this sqModel is actually a postgres view (not a table). Could this be the reason I am not getting back a primary key? I mean, the view's "primary key" does actually map back to the generating table's primary key but I guess that a view cannot formally have a primary key. Am I on the right track and what is the solution or what are possible solutions?

I guess this has caused me to question the whole approach of using sequelize with views. Can this even be achieved?

p.s. If it is relevant, the view uses a trigger to Insert/Update/Delete...

**Comment by istrau2** [comment]
I dove in to the sequelize source a little bit to try and figure out what the root issue is. I arrived at dialects/postgres/query.js:

In the Query.prototype.run method at the end I got to the following lines:

```javascript
query.on('end', function(result) {
      if (receivedError) {
        return;
      }

      resolve([rows, sql, result]);
    });
```

I placed a break in the event handler and I noticed that result has:

```javacript
{
rowAsArray: false,
rowCount: NaN
rows: []
}
```

Is the database supposed to be returning a results set? Is that the reason that sequelize is not updating the primary key of inserted instances?

**Comment by mickhansen** [comment]
Thanks for doing a bit of detective work yourself.
For Postgres sequelize will map any returned data from the INSERT query back onto the instance: https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query.js#L251
(usually by using RETURNING *).

Does your INSERT query include RETURNING *?
If it does the problem is likely in your DB, i'd try running the query manually.

**Comment by janmeier** [comment]
Closing, no response
