### ISSUE TITLE
How to perform offset with eager loading?

### ISSUE THREAD

**Issue by Gacnt** [sequelize/sequelize#5296]
I'm trying to perform an `offset` with an eager loading:

```
models.ForumMainSection.findOne({
       where: { id: req.params.section_id },
       include: [{
           model: models.ForumSectionPost,
           as: 'ForumSectionPosts',
           required: false,
           limit: 2,
           offset: req.query.skip || 0,
           include: [{
               model: models.User,
               required: false,
               include: [{
                   model: models.Character,
                   as: 'Characters',
                   required: false,
                   where: { character_main: 1 }
               }]
           },{
               model: models.ForumSectionPostReply,
               as: 'ForumSectionPostReplies',
               limit: 1,
               required: false,
               include: [{
                    model: models.User,
                    required: false,
                    include: [{
                        model: models.Character,
                        as: 'Characters',
                        required: false,
                        where: { character_main: 1 }
                    }]
               }]
           }]
       }]
   })
```

The `offset` in my first include seems to be being ignored completely, but the `limit` works just fine. I would expect my offset when provided to `skip` or `offset` however many (in the idea of pagination)

But I cannot seem to get the offset to work. Any information would be great.

**Comment by mickhansen** [comment]
It would help if you would explain what's not working and how you expect it to work, as per the https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues

**Comment by Gacnt** [comment]
@mickhansen Sorry for the terrible question, I put a bit of extra information at the bottom of the original post

**Comment by mickhansen** [comment]
`offset` should simply work, what does the SQL query look like?

**Comment by Gacnt** [comment]
@mickhansen just heading to bed, I'll report back with it in the A.M.
