### ISSUE TITLE
Issue : MSSQL 2012 and offset

### ISSUE THREAD

**Issue by Creadigme** [sequelize/sequelize#5299]
Hello,

Since last update (3.18.0), all my MSSQL 2012 queries with offset don't works anymore : 

"The number of rows provided for a TOP or FETCH clauses row count parameter must be an integer."

Sequelize add : **N**'0' even in offset/top :  

SELECT ... WHERE ... OFFSET **N'0'** ROWS FETCH NEXT **N'500'** ROWS ONLY;

If I change **N'0'** by **0**, it work like before (3.13).

Thanks

**Comment by mickhansen** [comment]
Looks like you are passing strings to limit/offset? Pass an integer instead and see if that works.

**Comment by Creadigme** [comment]
My bad, in deed, it work with parseInt. 

Don't you think it can be an issue ? (regression)

Thanks

**Comment by mickhansen** [comment]
It's sort of a regression yeah, but it was done to fix a security issue, however we didn't actually consider people passing strings to limit/offset :)

**Comment by Creadigme** [comment]
I agree about this ;-).
