### ISSUE TITLE
`this` returns undefined inside of getterMethods object

### ISSUE THREAD

**Issue by erikakers** [sequelize/sequelize#5304]
Used Sequelize CLI generate a new project and using the CLI to create models and migrations and created a Players model: 

```
module.exports = (sequelize, DataTypes) => {
    const Player = sequelize.define('Player', {
        firstName: {
            type: DataTypes.STRING
        },

        lastName: {
            type: DataTypes.STRING
        }
    }, {
        getterMethods: {
            fullName: () => {
                return this.firstName + ' ' + this.lastName;
            }
        },
        classMethods: {
            associate: (models) => {
                // associations can be defined here
            }
        }
    });

    return Player;
};
```

Trying to create the fullName inside of the returns an error:

```
Unhandled rejection TypeError: Cannot read property 'firstName' of undefined
    at [object Object].fullName (player.js:68:24)
    at [object Object].Instance.get (/vagrant/api/node_modules/sequelize/lib/instance.js:186:39)
    at [object Object].Instance.get (/vagrant/api/node_modules/sequelize/lib/instance.js:209:31)
    at [object Object].Instance.toJSON (/vagrant/api/node_modules/sequelize/lib/instance.js:1050:15)
    at [object Object].<anonymous> ({player_id}.js:9:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

If I do `console.log(this);` within the getterMethods it always returns undefined. I've tried to few different combinations to get access to the values but I can't get anything to work. What am I missing?

**Comment by Joshua-F** [comment]
I believe it might be due to you using the new anonymous function syntax, which actually changes how `this` behaves compared to just `function()`. Try changing `() => {` to `function() {`.

**Comment by mickhansen** [comment]
Yep, using arrow functions incorrectly.

**Comment by erikakers** [comment]
Drep, totally overlooked that.

**Comment by DiegoRBaquero** [comment]
Took me an hour to find this. I wasn't googling right I guess.

Thank you.

**Comment by BradlySharpe** [comment]
Also took me a while to find this :(

Have found instead of replacing arrow functions with `method: function() { return this.id; }` you can use

```
getterMethods: {
    method() {
        return this.id
    },
}
```

**Comment by snickroger** [comment]
Wowwwww. Thank you so much.
