### ISSUE TITLE
Auto Identity Column Value Jump 

### ISSUE THREAD

**Issue by taozhi8833998** [sequelize/sequelize#5313]
I define a model without id column(primary key), and when insert row the id should auto increase by 1, I think it's the default behavior, but I found out it jump some value and behavior unnormal

![jump](https://cloud.githubusercontent.com/assets/7252180/12606722/8b2f06c4-c50a-11e5-9d05-00d8ee1a0c52.png)

I didn't delete any rows in this table, I google this issue and found that the sql server 2012 may have this problem, while my database is mysql.

[sql_server_2012_id_jump](http://www.codeproject.com/Tips/668042/SQL-Server-Auto-Identity-Column-Value-Jump-Is)
[stack_overflow_sql_server_2012_jump_id](http://stackoverflow.com/questions/14162648/sql-server-2012-column-identity-increment-jumping-from-6-to-1000-on-7th-entry)

**Comment by mickhansen** [comment]
Not a sequelize issue. Usually caused by an insert/transaction failing.
