### ISSUE TITLE
Calling `set[association]` twice nullifies relationship

### ISSUE THREAD

**Issue by jocull** [sequelize/sequelize#5315]
I have an issue where calling a HasOne setter twice is removing the relationship. Calling it repeatedly switches the relationship on and off.

I have been pairing this with transactions and on subsequent calls my results are different.

Is this by design? It feels like a bug, as I would expect multiple sets to not change the relationships at all.

```
model: Home
model: Person
association: Person HasOne Home

person.setHome(homeInstance)
  .then(() => {
    // Run once: relationship exists
    // Run twice: relationship does not exist
  })
```

**Comment by mickhansen** [comment]
Definitely a bug, calling it twice in a row should be as close to a NOOP as possible.
