### ISSUE TITLE
Model.updateOne

### ISSUE THREAD

**Issue by ORESoftware** [sequelize/sequelize#5317]
hi

quick support question

is there a Model.updateOne and if not, is there a good reason for that?

thanks for your help

**Comment by mickhansen** [comment]
The first question could be answered by ssearching the docs: No
Good reason: Nobody put in the time :)

**Comment by ORESoftware** [comment]
oh boy, do I have to explain the difficulty of searching for something that
is not there? lol thanks though

**Comment by mickhansen** [comment]
Hah, i guess you're right :) However https://github.com/sequelize/sequelize/search?utf8=%E2%9C%93&q=updateOne should give you a pretty good idea that it isn't there :)

**Comment by ORESoftware** [comment]
well it could be named something besides updateOne..it seems clear that
this is needed, unless I am missing something. I havent done relational
databases in awhile but I assume it's possible to return an update query
after the first row is updated...

**Comment by janmeier** [comment]
You can pass a limit to `Model.update` http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows (only mysql and mariadb though)

**Comment by ORESoftware** [comment]
awesome thanks that should do as we use mariadb
