### ISSUE TITLE
lean queries with sequelize

### ISSUE THREAD

**Issue by ORESoftware** [sequelize/sequelize#5318]
Most recently I was using MongoDB (as probably many people have) and mongoose ODM has a lean() option for database reads

http://mongoosejs.com/docs/api.html#query_Query-lean

which means the database object will be returned without any decorators or functions, just pure data from the DB. Does sequelize have a similar option that returns undecorated object from mariadb etc? thanks!

**Comment by mickhansen** [comment]
`raw: true`

**Comment by ORESoftware** [comment]
ok thanks

**Comment by mickhansen** [comment]
However `raw: true` does not deduplicate includes, so it's not entirely as a lean query is suppose

**Comment by ORESoftware** [comment]
alright thanks I will have to read more to know what that means

**Comment by mickhansen** [comment]
It means that if you're doing joins with our include option you'll get a cartesian product rather than a nested product.

**Comment by molerat619** [comment]
Anything new here? I would like that too.

**Comment by felixfbecker** [comment]
@molerat619 Like what?

**Comment by molerat619** [comment]
To be able to run "lean" queries. `raw` seems not to work with includes, or did I get that wrong?

**Comment by felixfbecker** [comment]
Yes, raw is for returning plain DB results. What is the use case exactly?

**Comment by molerat619** [comment]
I want to work on the result after I get it before sending it to the frontend. I found out I have to manually run .toJSON() and that does what I need. Nevertheless, especially for former `mongoose` users, a `lean` option will be interesting.
