### ISSUE TITLE
Having a strange issue when using hasMany and belongsTo together

### ISSUE THREAD

**Issue by Keelar** [sequelize/sequelize#5319]
Okay, so I'm having an issue when using hasMany and belongsTo together. I'm using Sequelize v3.18.0 and PostgreSQL as my dialect.

I have two models, the first one is a user model:

```node
var User = sequelize.define(
    "User", {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        username: {
            type: DataTypes.STRING(24),
            unique: true,
            allowNull: false
        },
        password: {
            type: DataTypes.STRING,
            allowNull: false
        }
    }, {
        underscored: true,
        classMethods: {
            associate: function (models) {
                User.hasMany(models.Article, {
                    foreignKey: {
                        field: "author_id",
                        allowNull: false
                    }
                });
            }
        }
    }
);
```
and the second one is an article model:
```node
var Article = sequelize.define(
    "Article", {
        id: {
            type: DataTypes.CHAR(6),
            primaryKey: true
        },
        title: {
            type: DataTypes.STRING(500),
            allowNull: false
        },
        body: {
            type: DataTypes.STRING(50000),
            allowNull: false
        }
    }, {
        underscored: true,
        classMethods: {
            associate: function (models) {
                Article.belongsTo(models.User, {
                    as: "author",
                    foreignKey: {
                        field: "author_id",
                        allowNull: false
                    }
                });
            }
        }
    }
);
```
My issue is with creating article instances. After running `sequelize.sync()` my tables are created and the articles table appears to be correct when viewing from psql, although I'm still pretty new to SQL in general so I could be wrong:
```
                                  Table "public.Articles"
   Column   |           Type           | Modifiers | Storage  | Stats target | Description 
------------+--------------------------+-----------+----------+--------------+-------------
 id         | character(6)             | not null  | extended |              | 
 title      | character varying(500)   | not null  | extended |              | 
 body       | character varying(50000) | not null  | extended |              | 
 created_at | timestamp with time zone | not null  | plain    |              | 
 updated_at | timestamp with time zone | not null  | plain    |              | 
 author_id  | integer                  | not null  | plain    |              | 
Indexes:
    "Articles_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "Articles_author_id_fkey" FOREIGN KEY (author_id) REFERENCES "Users"(id) ON UPDATE CASCADE ON DELETE CASCADE
```
but when I try to create an article instance:
```node
models.User.create({
    username: "TestUser",
    password: "password"
}).then(function (user) {
    return models.Article.create({
        id: "123456",
        title: "Article title",
        body: "Article body",
        author_id: user.id
    });
}).then(function (article) {
    // done
});
```
I get a validation error `Unhandled rejection SequelizeValidationError: notNull Violation: user_id cannot be null`
I have specified the foreign key field as `author_id` in both hasMany and belongsTo, so why is it still asking for `user_id`? From what I understand that field shouldn't even exist, so what's going on here? Am I just misunderstanding something?

**Comment by mickhansen** [comment]
You'll want `name` rather than `field` for `foreignKey: {}` IIRC

**Comment by Keelar** [comment]
The examples in the documentation say to use field. Either way, I just tried name instead and it still has the same issue.

**Comment by mickhansen** [comment]
Can you please point to those examples?
https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to.js#L42

Try logging `Object.keys(Model.rawAttributes)`

**Comment by Keelar** [comment]
Alright, so the examples of `field` being used in the docs was not for foreignKey specifically. It's used [here](http://docs.sequelizejs.com/en/latest/docs/models-definition/) for general column options. I wasn't aware that foreignKey is different from those. I have switched from `field` to `name` even though they seem to do the same thing.

This was the output of `Object.keys(models.Article.rawAttributes)`:
`
[ 'id', 'title', 'body', 'created_at', 'updated_at', 'author_id' ]
`
No `user_id` value in there yet I still get the notNull violation as if it were.

**Comment by mickhansen** [comment]
Can you post the SQL for the insert statement, and can you double check the table structure in the database for article?

**Comment by Keelar** [comment]
Only the insert statement for the user actually gets executed. The error gets thrown before sequelize even attempts the insert of the article. Since that's the case the article SQL structure shouldn't be the problem since it doesn't even get that far, but here it is anyway. It hasn't changed from the top post.
```
                                  Table "public.Articles"
   Column   |           Type           | Modifiers | Storage  | Stats target | Description 
------------+--------------------------+-----------+----------+--------------+-------------
 id         | character(6)             | not null  | extended |              | 
 title      | character varying(500)   | not null  | extended |              | 
 body       | character varying(50000) | not null  | extended |              | 
 created_at | timestamp with time zone | not null  | plain    |              | 
 updated_at | timestamp with time zone | not null  | plain    |              | 
 author_id  | integer                  | not null  | plain    |              | 
Indexes:
    "Articles_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "Articles_author_id_fkey" FOREIGN KEY (author_id) REFERENCES "Users"(id) ON UPDATE CASCADE
```

**Comment by mickhansen** [comment]
You've verified that the user is inserted correctly and it actually hits the .create() statement for Article?

**Comment by Keelar** [comment]
This is the code being used to create them:
```node
models.User.create({
    username: "TestUser",
    password: "password"
}).then(function (user) {
    console.log(user.username);

    return models.Article.create({
        id: "123456",
        title: "Article title",
        body: "Article body",
        author: user
    });
}).then(function (article) {
    // done
});
```
The username gets logged to the console and then the error gets thrown.

**Comment by mickhansen** [comment]
Okay so that is a different create call than you previously used.
In this call you're using nested create, which doesn't actually support passing in an instance like that (nested create only supports a fully nested create).

Please try chaing your code back to authorId: user.get('id') again

**Comment by Keelar** [comment]
Shit. I was messing around with it and forgot that I changed `author_id` to `author` and passed it the user object instead of its id. Turns out it *was* `field` causing the original issue. Now that I've changed `author: user` to `author_id: user.id` it's working. Thanks a bunch for the help!

**Comment by mickhansen** [comment]
Glad we solved it :)
