### ISSUE TITLE
Model.attributes should be Model.rawAttributes

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#5320]

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/8160

Need to removed Model.attributes in v5

**Comment by superlbr** [comment]
Since attributes were loaded when model init,  what if I changed attributes defined in models and database later and keep the original js program running .I got an error because the attributes still unchanged in memory. Disappointed that I didn't take a picture...

**Comment by sushantdhiman** [comment]
This change is now included in v5 branch https://github.com/sequelize/sequelize/tree/v5
