### ISSUE TITLE
Connection hangs after syncing

### ISSUE THREAD

**Issue by mattecapu** [sequelize/sequelize#5330]
Here's my code
```js
const ORM = new Sequelize(
    'my_db',
    DB_USER, DB_PASSWORD,
    {
        dialect: 'mysql',
        host: 'localhost',
        port: 3306
    }
);

/* lots of entities definitions */

console.log('Syncing...');
ORM.sync({force: FORCE_SYNC})
    .then(() => console.log('Done!'));
```
When I run it, it displays "Done!" almost immediatly, but then the process hangs for about 10 seconds, then exits. If I forcefully close the connection from within the Promise handler, it closes immediatly but I'd like not to. My tests showed syncing happens correctly and the handler is called rightfully after sync completion, but then it hangs without any apparent reason.
I found in the code [this comment](https://github.com/sequelize/sequelize/blob/0de404640d4c71e2d1f1259356650dfb586a248b/lib/sequelize.js#L1258) explaining the connection should close automatically at process.exit, so what's going on?

**Comment by mickhansen** [comment]
Connections do close at process.exit, if you call process.exit, otherwise connections stay live till they idle out per your pool config (default in this case).
