### ISSUE TITLE
Column does not exist for findAll with limit, order on custom field, and hasMany associations

### ISSUE THREAD

**Issue by troyastorino** [sequelize/sequelize#5332]
I get a `SequelizeDatabaseError: column ${x} does not exist` for a findAll query with with limit, order on a custom field, and hasMany associations. The problem is that when there is a subquery, the subquery aliases the custom field to the attribute name in the sequelize model, but the `ORDER BY` in the main query still refers to the custom field.

This test in the associated PR (#5333) illustrates the issue:
https://github.com/sequelize/sequelize/pull/5333/files#diff-916a03a19d49cecbcd62820c088b9587R1881

The test doesn't pass without the changes in the PR.

**Comment by Maks-Yaremenko** [comment]
+1
