### ISSUE TITLE
Create related object

### ISSUE THREAD

**Issue by mattecapu** [sequelize/sequelize#5338]
I have two models `User` and `Dog`, which are related in this way
```js
Dog.belongsTo(User, {as: 'owner', foreignKey: {allowNull: false}});
User.hasMany(Dog);
```
I'm trying to create a `Dog` using `User`'s methods (`addDog` and `createDog`).

With the first method
```js
User.create({
    firstName: 'Bob',
    secondName: 'Smith'
}).then((bob => bob.addDog({name: 'Larry'}));
```
An error occurs: `Unhandled rejection TypeError: val.replace is not a function`, looking at the stack trace, it's seemigly trying to escape an `undefined` value.
Conversely, using `createDog` raises the error: ` Unhandled rejection SequelizeValidationError: notNull Violation: description cannot be null,
notNull Violation: ownerId cannot be null`.

I don't know what's wrong. I can't find any relevant documentation on the methods `add/create*` which are added to a model with relationships. What's going on?

**Comment by mickhansen** [comment]
addAssociation does not take values, it takes an instance or a primary key.
use createAssociation if you want to create an entirely new instance.

**Comment by mickhansen** [comment]
createDog is the correct one here, addDog does not take those parameters at all.
http://docs.sequelizejs.com/en/latest/api/associations/belongs-to/
http://docs.sequelizejs.com/en/latest/api/associations/has-many/

The likely issue here is that you're using an alias on the first relation which then defines a foreignKey named ownerId with allowNull: false.

However Sequelize is not currently smart enough to infer that when you make the inverse relationship manually, so User.hasMany(Dog) will likely add a userid to dog instead aswell.
