### ISSUE TITLE
How can I save new instance to existing table?

### ISSUE THREAD

**Issue by glebcha** [sequelize/sequelize#5342]
Here's how I use sequelize to hadle extisting table:

```
let sequelize = app.get('sequelize');
let SharedCache = sequelize.define(
  'SharedCache', 
  {}, 
  { tableName: 'SharedCache' }
);

SharedCache
.findOne({where: {id: account.id} })
.then(cached => {
    cached.account = {name: 'Jason'};
    return cached 
    .save()
    .then(() => {
      next();
    })
})
```

But record in DB is not updated, what am I doing wrong?

**Comment by mickhansen** [comment]
It looks like you're trying to add an association instance?
Or is `account` a JSONB value? Doesn't look like you've defined any attributes at all.
You need to go through the basics of the documentation.

http://docs.sequelizejs.com/en/latest/api/associations/

**Comment by glebcha** [comment]
@mickhansen I try to set value of 'account' field. Yes, it's jsonb. Table existed before and the main idea is to access/update fileds only.

**Comment by janmeier** [comment]
You need to specify in your model definition that the table has an account field - otherwise sequelize won't know that the field exists and save its value6

**Comment by mickhansen** [comment]
As a minimum you'll need:

```js
let SharedCache = sequelize.define(
  'SharedCache', 
  {
    account: {
      type: Sequelize.JSONB
    }
  }, 
  { tableName: 'SharedCache' }
);

```
