### ISSUE TITLE
How do you find by dateonly?

### ISSUE THREAD

**Issue by totty90** [sequelize/sequelize#5346]
How do you search when the field is dateonly? What format the dateonly accepts? A javascript date doesn't work (even if I expected to convert it to the proper date, without hour and minutes).

**Comment by janmeier** [comment]
Have you tried passing a plain string? It might also be that its simply not possible right now :)

**Comment by janmeier** [comment]
Tested - passing a string works fine

```js
var User = sequelize.define('user', {
  dob: Sequelize.DATEONLY
});
return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => User.create({ dob: '1990-01-07'}))
  .then(() => User.find({ where: { dob: '1990-01-07'}}))
  .finally(() => sequelize.close());
```
