### ISSUE TITLE
Updating multiple models at once..

### ISSUE THREAD

**Issue by sheeput** [sequelize/sequelize#5347]
I have a question and I hope this is the right place to ask it.

I have several models that are joined using foreign keys.  I know that I can use the Create method and pass the include option to save several models at once.   I can't see a way to update multiple models at once with something like upsert or update?

Am I missing something? 

I am using MySql and Sequelize 3.13.0.

Thanks.

**Comment by mickhansen** [comment]
`upsert` only works for a single row.
`Model.update` allows bulk updating via a WHERE parameter.

Other than that there's really no magic, a lot of the way because SQL doesn't support anymore magic thna that.
