### ISSUE TITLE
Can't revert adding a foreign key column

### ISSUE THREAD

**Issue by VandorpeDavid** [sequelize/sequelize#5348]
PR #5227 allows adding a foreign key column to already existing tables. However, these migrations can't be reverted by a simple undo function. Trying `queryInterface.removeColumn` results in 
`Unhandled rejection SequelizeDatabaseError: ER_ERROR_ON_RENAME`. See http://stackoverflow.com/questions/338978/mysql-innodb-need-to-delete-column-and-accompanying-foreign-key-constraint-a for SO question regarding the problem.

**Comment by sushantdhiman** [comment]
I think #5212 implementation will be able to fix it.

**Comment by sushantdhiman** [comment]
Moved to ( and will be implemented with ) #5212
