### ISSUE TITLE
truncate() should allow resetting sequences.

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#5356]
`Model.truncate()` method should optionally allow to reset the `sequence` of the `primary key`; It can be achieved by adding  these queries

* Postgres `truncate table table_name restart identity;`

**Comment by xorbis** [comment]
Can truncate reset sequences now?
The reference by kylehotchkiss does not seem related.

**Comment by janmeier** [comment]
The issue is still open, so that would be a no :)

**Comment by janmeier** [comment]
The reference is not present in the linked issue, so must have been a typo

**Comment by xorbis** [comment]
I look forward to this feature, thanks for the quick reply, you guys are awesome.
