### ISSUE TITLE
`through` attribute in M:N findAll calls should support `include`

### ISSUE THREAD

**Issue by xizhao** [sequelize/sequelize#5358]
I need to be able to query for eagerly-loaded models on my through table, and simply doing a N:M association won't work for this.  My query looks like:

```
model.findAll({
      include: [{
        model: models.otherModel,
        through: {
          include: [{
            model: models.thirdModel
          }]
        }
      }]
})
```

and I end up with an error in `Instance.set`

```
TypeError: Cannot read property 'indexOf' of undefined
    at Instance.set (node_modules/sequelize/lib/instance.js:314:79)
```

setting `includeNames` on the second-nested include does not help

**Comment by janmeier** [comment]
Please provide your models and associations

**Comment by xizhao** [comment]
Here's a full gist to replicate:

https://gist.github.com/xizhao/fe4d2cf1cd83ef5ba956

**Comment by mickhansen** [comment]
This is not supported and not sure it's likely to become.
You can easily make this work on your own by manually setting up associations and including them directly.

**Comment by xizhao** [comment]
We do manually set up associations, it's just that we can't include them in the query and instead would have to split it off into a big query and a filter in app logic.

Right now we're hacking some SQL directly into the query through `Sequelize.literal` --> any way we can help get that into the query builder?

**Comment by mickhansen** [comment]
Why can't you include them?
What's the issue specifically?

**Comment by xizhao** [comment]
@mickhansen sorry, here's the issue lined out.

We have 4 models, diagram:

```
ModelA <-- JoinModel --> ModelB
                ^
                |
            (hasMany)
                |
             ModelC
```

We can do `ModelA.findAll({ include: ModelB })`, and receive all the `JoinModel` instances, but we also want to include `ModelC` when we get the `JoinModel`.

This is an important feature, as one of the key benefits of RDBMS is the ability to create relationships on relationships.  I.e. i can subscribe to a newsletter and others can follow my subscription, 

In our case since we are including multiple join models, it would be very tedious for us to manually assemble all the `JoinModel` PKs, manually query for associated `ModelC`s, and reassemble.

I'm wondering if I'm missing how to do this the Sequelize way or if its currently unsupported.  If not I can draft a proposal on why this should be a key feature.

Thanks!

**Comment by mickhansen** [comment]
@xizhao No magic for that i'm afraid, you'll need to maintain a seperate relationship to JoinModel.
You can use beforeFind to ligthen some of the load

**Comment by mjy78** [comment]
We have a similar scenario with a M:N model linking "Systems" and "Installations" represented as "SystemInstallations". We then have a "SystemInstallationTimes" 1:N table off this to allow us to define time ranges that a system is associated with an installation.

```
Installation-(1)-----(*)-SystemInstallation-(1)-----(*)-System
                                 |
                                (1)
                                 |
                                 |
                                (*)
                                 |
                        SystemInstallationTime
```

We can use Sequelize to add the data and link the systems and installations along with time frames, but would be great if we could query as above, but we're getting the same error.

In our case we want to request an installation along with any systems that are CURRENTLY associated with the installation (systems may have been associated in the past but are no longer - in which case we're not interested in these).

```javascript
Installation.find({
    where: { _id: req.params.id },
    include: [ 
      {
        model: System,
        as: 'Systems', 
        required: false,
        through: {
          model: SystemInstallation,
          include: [  
            {
              model: SystemInstallationTime,
              as: 'SystemInstallationTimes',
              where: {
                effectiveTimeFrame: {
                  $contains: new Date()
                }
              }                
            }
          ]
        }
      }
    ]
  })
```

**Comment by mjy78** [comment]
It's worth mentioning that the reason we structured our tables above with a separate table (SystemInstallationTimes) linked to the join table (SystemInstallations) was because at the time, and as still is the case I believe, sequelize doesn't support [many-to-many join tables with multiple rows of identical foreign key pairs](https://github.com/sequelize/sequelize/issues/3493).

**Comment by exequiel09** [comment]
I have the same setup as mentioned above except that the third model has an optional one-to-one relationship with the join model as shown below. Been encountering the same issue as @mjy78 cited above.  @mjy78 and @xizhao  did you manage to get around with this issue? what steps did you take? Thanks :)

```
Technologies-(1)-----(*)-TechnologyProtectionTypes-(1)-----(*)-ProtectionTypes
                                 |
                                (1)
                                 |
                                 |
                                (0..1)
                                 |
                        ProtectionTypesMeta
```

**Comment by DanFerro** [comment]
We're suffering from the same issue. Have a 1:m many associated on the through table. It appears we have to run separate queries for each through association to load the attached association.

@lindsaylee
