### ISSUE TITLE
Validator len always fails on strings.

### ISSUE THREAD

**Issue by trattles** [sequelize/sequelize#5363]
Sequelize 3.19.0

*Relevant mode attributel with Validator:*

    password: {
			type: DataTypes.STRING,
			validate: {
				notEmpty: true,
				len: {
					args: [6, 20],
					msg: 'Password must be between 6 and 20 characters in length.'
				}
			}
		},

Passing in 'password' for the password should work (it is between 6 and 20 in length) however the validator always fails no matter then length of the string passed in. Removing the len validator allows the password through normally.

**Comment by sushantdhiman** [comment]
Can you give sample data that fails and exact error on failure?

**Comment by trattles** [comment]
Yes. Literally any string fails regardless of length.

For example, here I'm passing in password, which is between 6 and 20 characters so should theoretically go through.

    {  
      "email": "test@testmail.com",
      "password": "password"
    }

Will fail, with the error message I set for len in the initial comment.

If I set no error msg I just get the default

    {
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Validation error: Validation len failed"
    }

If I remove the len validator it works fine. All the other validators I'm using seem to be operating normally ie: isEmail, notEmpty etc.

**Comment by trattles** [comment]
I'm on phone right now so I cant confirm but I think I've realized the issue.

I'm hashing the password in a setter. So it the validation runs post setter (which makes sense) then my hash is going to be too long and I can't actually validate passwords on the model.

I'll confirm and close when I'm back at my machine if that's the case.

**Comment by sushantdhiman** [comment]
Yup your password hash are longer than 20 limit
