### ISSUE TITLE
Validation warning

### ISSUE THREAD

**Issue by eclipse1985** [sequelize/sequelize#5365]
Hi,

from today I see in my node logs this warning:

> warning: you tried to validate a number but this library (github.com/chriso/validator.js) validates strings only. Please update your code as this will be an error soon.

It seems caused by this [commit](https://github.com/chriso/validator.js/commit/1f67e1e15198c0ae735151290dc8dc2bf14da254)
in version 4.7 of validator.js.
Can I do something to avoid it, or do you plan to update the code?

Thanks a lot

**Comment by sankethkatta** [comment]
Same issue here on Sequelize 3.9.0. Upgrading to the latest Sequelize 3.19.1 seems to have fixed it.

**Comment by yonjah** [comment]
I'm still having this issue with Sequelize 3.19.2

**Comment by eclipse1985** [comment]
I tried with 3.19.1 and 3.19.2, same error

**Comment by yonjah** [comment]
This is a really weird requirement for a validation library to require all input to be strings.
I'm sure that in many cases you actually want to validate the type of the input.

Also I only looked at the code for a little bit and found a validation bug which is never a good sign
```javascript
val = require('validator');
val.isIP('0000000000000000123.000123.00123.00123'); //returns true
val.isIP('0000000000000000123.000123.00123.00123', 4); //returns true
```
I can only assume that in a limited length db column that might have some unexpected side effects

Probably a bit too big for this fix but I would suggest using [joi](https://github.com/hapijs/joi) it seem to have the same feature support and usually you can trust the stuff coming from hapi.js

**Comment by mickhansen** [comment]
@yonjah Yeah very odd

**Comment by mirek** [comment]
This is a problem when trying to extend validation (as described in https://github.com/sequelize/sequelize/commit/530d01027102032cd697e88cdff8d0cc7d137aa5) for example with your own json-schema validator.

Is sequelize going to create wrapper around validate.js delegating string based validation there and allowing custom validators for non-strings to be defined? At the moment value argument is coerced automatically to string (https://github.com/chriso/validator.js#extensions) which makes it impossible to do anything with json-schema/JSONB on postgres for example.

**Comment by validkeys** [comment]
I'm having this issue on 3.19.3. In the below code, everything works fine until I add the isUnique custom validator. Similar to what @mirek is talking about.

```javascript
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      validate: {
        notEmpty: true,
        isInt:    true,
        isUnique( value, next ) {
          next()
          // there must not be a record with the same userId, teamId and clientId
          const { teamId, userId, clientId } = this;

          let where = { teamId, userId, clientId };

          return this.Model.count({ where })
            .then((count) => {
              if (count > 0) {
                next(new Error("A permission for this user on this team and client already exist"));
                return;
              }

              next();
            })

        }
      }
    }
```

**Comment by janmeier** [comment]
Hmm I guess we should roll back to a version of validator.js that doesn't do co-ercion. Is there any way to lock the dependency so @greenkeeperio-bot doesn't try to update it?

In the longer run we should perhaps look for other validation libs, but that will most likely require writing a wrapper around it to maintain all the old methods. Or we could include it as a BC break in 4.0?

**Comment by Laubi** [comment]
It would also be possible to clone the project and release it with a different name for the usages of sequelize (For example, of course, "sequelize-validations"). 

The problems could be fixed without breaking compatiblility, and even if, it would me minimal.
Also, the [license](https://github.com/chriso/validator.js/blob/master/LICENSE) would allow it.

**Comment by Joanne16** [comment]
I am having the same error message... What should be done to correct it (rollback to an older version of validator.js ? If yes, to which version should we roll back ?)

Thanks

**Comment by elgambet** [comment]
I'm having the same error message using sequelize@3.19.3 in Debian 4.1.6-1 with nodejs V4.1.1, someone knows if this is already fixed?

**Comment by janmeier** [comment]
@elgambet The issue is still open, so no :)

**Comment by kylehotchkiss** [comment]
Can sequelize just cast the inputs as strings pre-test to make Validator happy? This seems like it's going to require me to remove my validators at the moment :/

**Comment by mickhansen** [comment]
@kylehotchkiss That could be an option, we're still looking at how best to solve it.
You are welcome to open a PR with a solution that coerces strings somewhere around here: https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js#L255 and we can discuss whether that's a good enough solution for now :)

**Comment by kylehotchkiss** [comment]
@mickhansen I added a `var valueString = String(value);` to the beginning of that function, and then changed `value` to `valueString` in https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js#L262 and tested it in my app, and I didn't see any more errors, but I am unable to get the tests to pass on master locally so don't think I could PR it.

**Comment by mickhansen** [comment]
@kylehotchkiss Try PR'ing and lets see what CI says :)

**Comment by sebastianoblom** [comment]
Hi,
This warning still happens for the specific case of using `isIn` validation, when the arguments are not strings. Like this example for instance;
```json
accountType: {
  type: Sequelize.INTEGER,
  allowNull: false,
  validate: {
    isIn: {
      args: [[0, 1, 50, 99]]
    }
  }
},
```
Possible fix converting the args to strings in the function `_extractValidatorArgs` in `lib/instance-validator.js` but that feels more of a dirty hack than a solution.
Another fix is ofcourse to input the args as array of strings instead of array of int, but that also feels wrong.
Any suggestion how to best deal with this?

**Comment by cusspvz** [comment]
I'm getting this while validating a `Date` instance.

```
message: This library (validator.js) validates strings only, 
path: birthday, 
type: Validation error, 
```

```
    birthday: {
      type: DATE,
      allowNull: true,
      defaultValue: null,

      validate: {
        // isDate: true,
        isAfter: moment(new Date())
          .year(new Date().getFullYear() - 113)
          .toDate(),
        isBefore: moment(new Date())
          .year(new Date().getFullYear() - 13)
          .toDate(),
      }
}
```

**Comment by cusspvz** [comment]
**SOLVED**
Changed the `.toDate()` with `.format()`. It now outputs a string which is accepted by `validator`.
