### ISSUE TITLE
Sequelize.sync() should support ALTER statements instead of full DROP+CREATE statements

### ISSUE THREAD

**Issue by ShimShamSam** [sequelize/sequelize#537]
It would be nice if we could call sync() and have it compare the model schema to the database schema  and make only the changes necessary using ALTER statements. The major benefit is preservation of data. If implemented correctly, this could probably eliminate most of the need for migration files.

**Comment by agchou** [comment]
+1

**Comment by Madd0g** [comment]
huge +1

I was hoping there was a way of detecting an out-of-sync model, that should be top priority, automatically creating the migrations seems so much harder than just listing columns and finding a mismatch.

**Comment by mickhansen** [comment]
@Madd0g well there's also a whole group of people that think something like this would be really irresponsible - what if there's a bug that suddenly whipes your table for some reason? (bugs happen in software, often).

It's not our highest priority, but something we do want to get to (but we are really only two developers in our spare time :))

**Comment by Madd0g** [comment]
@mickhansen - I meant that being able to see that a model is out-of-sync should be top priority among other related things like auto-migrate and other *really* scary and complex things like detecting/fixing out-of-sync properties in relationships. 

Just detecting the change within a single model and not doing anything until the dev chooses to do `force: true`, is not really dangerous. I would really welcome that feature.

**Comment by mickhansen** [comment]
@Madd0g Yeah ideally i would like to be able to run a base diff that can present the differences in some kind of format that we can then either transform to migrations, raw queries or execute immediately.

**Comment by h0vhannes** [comment]
+1

**Comment by zeeshanjan82** [comment]
+1

**Comment by zeeshanjan82** [comment]
I was initially really impressed with sequelize and coming from the .net world where I could do things much faster using framework like Entity Framework but the issue with sequelize is It really does not provide a way to sync the models and database other than using migration scripts and I am sure no programmer in the world would really like to update database on 2 places, models and then writing the migrations for them. I think if the sync {force: false} option is provided which could sync alter tables also then there is no need for migration scripts and those will become obsolete.

**Comment by mickhansen** [comment]
@zeeshanjan82 I would personally never use `sync({alter: true})`, and i'm a contributor. Bugs happen and i wouldn't want my production DB to disappear because of MAGIC.

**Comment by gustavpursche** [comment]
Now 2 years after my comment I agree to @mickhansen. I still think it would be nice, to allow an altering process, but since [sequelize-auto](sequelize-auto) already exists, it's not that hard, to create visual diffs or even replace/ enhance your model files ...

**Comment by mickhansen** [comment]
@gustavpursche It would still be a nice feature since the underlying functionality could be used to generate migrations you could manually inspect before running.

**Comment by gustavpursche** [comment]
@mickhansen Agree. But 2 years ago I gave my "+1" to auto-altering the table, without manual checks, why I wouldn't anymore. Maybe a long winter-night will bring a "sequelize-model-diff" to life :)

**Comment by diosney** [comment]
+1 to it, would be awesome.

Django even integrated `south` into the core.

link provided above: http://south.readthedocs.org/en/latest/commands.html#schemamigration

already integrated on django: 
https://docs.djangoproject.com/en/1.8/topics/migrations/
https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-makemigrations

**Comment by florian-rossiaud** [comment]
+1

**Comment by matthieuh** [comment]
+1

**Comment by bloodhawk** [comment]
+1

**Comment by vperezma** [comment]
+1

**Comment by schettino** [comment]
+1

**Comment by kewang** [comment]
+1

**Comment by lianyi** [comment]
+1

**Comment by gimenete** [comment]
I've just released an open source module that compares two postgresql databases and generates SQL statements to modify the schema so the first db matches the second one. 

https://github.com/gimenete/dbdiff

**Comment by GeoffreyPlitt** [comment]
@gimenete You are a champion among men.

**Comment by gimenete** [comment]
@GeoffreyPlitt Feel free to open an issue if you find something that could be improved or any suggestion :)

**Comment by nodecode** [comment]
+1

**Comment by pc3b3r** [comment]
+1

**Comment by gzsupos** [comment]
+1

**Comment by marcsolanadal** [comment]
+1

**Comment by yuredd** [comment]
+1

**Comment by n321203** [comment]
+1
Use https://github.com/gimenete/dbdiff as starting point.

**Comment by janmeier** [comment]
@n321203 However dbdiff is only part of the way - since it only supports postgres, and as far as I can see needs to connect to two existing database

**Comment by gimenete** [comment]
@janmeier I'm the author of dbdiff. I can make dbdiff support other databases in the near future. Which database are you using?

I don't think sequelize should use dbdiff internally to start supporting `alter` sql statements in `.sync()` but one thing we could do is a new module that using dbdiff and sequelize calls `sync()` in an empty database and compares this database with the regular one.

**Comment by mickhansen** [comment]
@gimenete MySQL, SQLite, Postgres, MSSQL
dbdiff looks great but i'm not sure it's a fit here, a better approach will likely still be to have describeTable work well enough that it can be compared to the attributes a model has.

**Comment by gimenete** [comment]
@mickhansen @janmeier @n321203 I've just released a module that uses dbdiff behind the scenes. It adds a new method to Sequelize: `syncDiff()`. Check it out:
https://github.com/gimenete/sequelize-sync-diff

It only supports Postgres though. I could add MySQL in the near future.

**Comment by trentjones21** [comment]
+1

**Comment by vekexasia** [comment]
+1

**Comment by janmeier** [comment]
_Note_: Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of filling the thread with +1 comments

**Comment by jerryladoo** [comment]
+1

**Comment by gimenete** [comment]
I've released a new version of dbdiff https://github.com/gimenete/dbdiff

This is a big refactoring and the first step for supporting multiple databases. Also now it can be used as a library (not only a cli) to compare two databases, two schemas, or generate a JSON-serializable object with the schema representation of an existing database. This could be integrated into sequelize this way: sequelize could create a "desired" schema representation and dbdiff could compare it with the current database schema. @mickhansen

I've also added "safety" levels of the SQL output. Check the docs for further info.

**Comment by idchlife** [comment]
@gimenete WOW! Actually developers of sequelize should consider using your library

**Comment by xiaofan2406** [comment]
will this be considered in 4.0 release?

**Comment by mickhansen** [comment]
@xiaofan2406 It's not breaking so it's not tied to any specific release.

**Comment by neoxack** [comment]
+1

**Comment by sylvainlap** [comment]
+1

**Comment by alexey2baranov** [comment]
+1

make 2 parameters --dump-sql and --force like in Doctrine2 schema tool. --dump-sql to write migration SQL  into console only. This is a safe way to migration on production database. And another key --force for applying commands to target database

**Comment by frogcjn** [comment]
+1

**Comment by frogcjn** [comment]
`apgdiff` http://apgdiff.com
 maybe help to migrate from different versions of schema generated by sequelize.
just use
 pg_dump --schema-only "address-to-your-postgresDB" > ~/Desktop/schema0
 pg_dump --schema-only "address-to-your-postgresDB" > ~/Desktop/schema1

and use apgdiff to generate alter commands.

**Comment by Synvox** [comment]
Any update on this after two years?

**Comment by frogcjn** [comment]
I think the easiest way to implement this feature is to use sql diff tool to generated alter SQL

**Comment by manuelfink** [comment]
+1

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by Wats0ns** [comment]
Still no PR about this ?

**Comment by TangMonk** [comment]
This issue opened 4 years ago, And how's the work?

**Comment by janmeier** [comment]
@TangMonk Appearently no-one has needed this enough that they actually took the time to sit down and write the code (Which would require a significant amount of time).

Remember that almost everyone here works on sequelize on their own time :)

**Comment by TangMonk** [comment]
@janmeier sorry, I understand, thanks everyone's work, I wish I could help.

**Comment by bwoodlt** [comment]
Can't wait for this to be out. Will come very handy and wouldnt have to drop table to see new changes!

**Comment by lbouriez** [comment]
+1

**Comment by ChristianTucker** [comment]
We've been using Sequelize in Production. Not having this option is leaving us stumped trying to find the best way to make modifications to the database in a production environment.

**Comment by meyer9** [comment]
I've submitted a patch for this. #7230 

Just waiting for a merge, but you can use my branch for now if you really need this feature - jmeyer2k/sequelize

**Comment by idchlife** [comment]
dear god

**Comment by gotojmp** [comment]
good job

**Comment by ahelord** [comment]
How Work ? link doc? video?

**Comment by sushantdhiman** [comment]
`sequelize.sync({ alter: true })`

**Comment by bwoodlt** [comment]
Do I need to update sequelize via npm or need a specific branch?

**Comment by mc-zone** [comment]
It seems that the latest version v3.30.4 does not include this changes. Wait for release.

**Comment by janmeier** [comment]
This feature has landed in master, so it will be available in v4

**Comment by ahelord** [comment]
@janmeier Friend, this functionality is important when you could leave this version thank the collaboration.Friend, this functionality is important when you could leave this version thank the collaboration.

**Comment by cyberdude** [comment]
Woah! It made it!!!!!!!

**Comment by atheros** [comment]
Yeah, but latest pre-release is 4.0.0-2 from 2016-09-12T07:13:18.104Z.

Is there a plan to release 4.0.0-3 which would include this feature?

**Comment by Vincz** [comment]
Any update about this feature?
For me it's clearly a game changer regarding the choice of an ORM. Have been using knex for a while, but schema updates and migrations are such a pain.

**Comment by meyer9** [comment]
It's in master. It will be released in 4.0.0 otherwise you can use the
github version.

**Comment by agramdass** [comment]
@meyer9 Did a couple of changes to your implementation that fixes column mappings and added a drop column option (so that columns are not dropped by default). Also fixed query generator for unique and foreign keys alteration for postgresql (don't use enum on my side, perhaps that might still be problematic).
Since you have the test scenarios/environment, perhaps you can validate the changes to be working correctly also on your side.
repo: https://github.com/lekkerapps/sequelize

Thanks

**Comment by meyer9** [comment]
Looks great! There are a couple small things to change. You should submit a PR so that more people can review the code though. @agramdass

**Comment by pvsousalima** [comment]
How do i use the latest version? is it the 
```
sequelize.sync({ alter: true })
```
and install sequelize 4.0?

**Comment by meyer9** [comment]
Yeah, you need to install it from the github by npm-installing
sequelize/sequelize. 4.0.0 isn't out yet.

**Comment by robbyemmert** [comment]
@meyer9 What do you think about adding an option to preserve removed columns (probably by re-naming them, but I am open to other options). If there is support for this, I could create a PR. This would allow implementers to more safely keep schemas up to date, while being able to revert changes if necessary. Could also be great for that "oh shoot, I want that column after all" moment.

For example: 
```
sequelize.sync({
    alter: true,
    preserveColumnsOnSync: true // PLEASE recommend a better name
})
```
This would add the following benefits:

1. If you remove a column named `foo` of type Boolean from the schema, instead of removing that column, it will be re-named to something like `__removed__foo__Boolean`.
2. If you re-add a column with the same name (`foo`) and same type back into the schema, your existing column will be used, being renamed back to `foo`.
3. Data is not lost in the process
4. Legacy data could be cleaned up safely at a later time, in a more deliberate manner.

**Comment by meyer9** [comment]
It sounds like a good idea to me especially since this is only for
development/debugging. Also, possibly make this on by default. I'm sure
there will be users who use alter in production and I think it would be a
good safeguard against data loss.

**Comment by manast** [comment]
after testing ```alter: true``` in a moderate complex database -> many different kind of errors with relations, enums and what not. Seems like the best thing to do is keep from all this automatic stuff as far away as you can and do your migrations by custom scripts or you are going to create the perfect scenario for a disaster... my two cents.

**Comment by janmeier** [comment]
@manast I definitely agree with you. At snaplytics we do all migrations by hand as well

**Comment by Vincz** [comment]
I disagree. It's not because it's complex that it's impossible. I have been using Doctrine ORM auto update with "ALTER TABLE" for years on countless PHP projects with complex databases and never get any issue with it (and you have the option to preview the queries about to be execute). I'm sorry but I really don't get the argument "Let's do all by hand it's better", especially for developers.

**Comment by kauffmanes** [comment]
@v1r it also isn't working for sqlite. Is there additional configuration that needs to be set for this?

**Comment by v1r** [comment]
@kauffmanes nop, I am not sure for sqlite.

**Comment by FarzanRNobakht** [comment]
It would be very nice if the significant limitations of the tool are disclosed in a topic on the manual page.

**Comment by campbellbrendene** [comment]
Bump! Any progress on this?

**Comment by Hiroki111** [comment]
> The `sync({alter: true})` does not take in consideration the `field` attribute, atleast for MySql.

I stumbled on the same issue today (I'm suing SQLite btw).
According to [the API doc](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-sync), this "Alters tables to fit models", but it doesn't run `ALTER` statements that are defined by `queryInterface.changeColumn` in migration files.

I wonder what `sync({alter: true})` is supposed to do...?

**Comment by sinasalek** [comment]
I thought, alter option is exactly for that. but it doesn't really work. it would have been great if it could detect changes in a smart way and update the database.

**Comment by williamyorkl** [comment]
try this, it may work,it will keep the old columns data, and create a  new column based on your alter action.
```
 Modal.sync({
   alter: {
     drop: false,
   },
 });
```
