### ISSUE TITLE
timestamps for join tables

### ISSUE THREAD

**Issue by rvnath** [sequelize/sequelize#5373]
I am trying to implement a custom join table for roles table and resources table.  This custom join table is called RoleResource table, as defined below:

```javascript
module.exports = function(sequelize, Types){
  
  var RoleResource = sequelize.define('RoleResource', {
    roleId:     { type:Types.INTEGER, field:"role_id", primaryKey:true},    // userId for which resource permission being defined.
    resource:   { type:Types.INTEGER, primaryKey:true},                     // resource Id whose access is being sought.
    perms:      { type:Types.INTEGER, defaultValue:0},                      // actions applicable. (rwx or 421 unix format, r=4,w=2,x=1).
    createdBy:  {type:Types.INTEGER, field:"created_by", allowNull:false},  // Below 4 fields are for audit tracking of table modifications.
    createdOn:  { type:Types.DATE, field:"created_on", allowNull:false},
    modifiedBy: { type:Types.INTEGER, field:"modified_by", allowNull:false},
    modifiedOn: { type:Types.DATE, field:"modified_on", allowNull:false}
  },  
  {
    tableName:  "role_resources_map",
    timestamps: true,
    createdAt:  "createdOn",
    updatedAt:  "modifiedOn",
    classMethods: {
      associate: function(models) {
        RoleResource.belongsTo(models.User, {foreignKey:'createdBy'});
        RoleResource.belongsTo(models.User, {foreignKey:'modifiedBy'});
      }   
    }   
  }); 
  return RoleResource;
};
```
And the master tables for role and resource are like this...
**role table definition**:
```javascript
module.exports = function(sequelize, DataTypes) {
  var Role = sequelize.define("Role", {
    id:           { type:DataTypes.INTEGER, primaryKey:true },
    name :        { type:DataTypes.STRING(32), allowNull:false },
    desc :        { type:DataTypes.STRING(128) },
    created_by :  { type:DataTypes.INTEGER, allowNull:false },
    created_on :  { type:DataTypes.DATE, allowNull:false },
    modified_by : { type:DataTypes.INTEGER, allowNull:false },
    modified_on : { type:DataTypes.DATE, allowNull:false }
  },  
  {
     tableName: "roles_master",
     timestamps: true,
     createdAt: "created_on",
     updatedAt: "modified_on", 
     classMethods: {
      associate: function(models){
        Role.belongsToMany(models.Permission, {through:'RolePermissions'})
        Role.belongsToMany(models.Resource, {through:'RoleResource', foreignKey:'roleId'})
      }   
    }   
  }); 
  return Role;
};
```

**resource table definition**:
```javascript
module.exports = function(sequelize, Types) {
  var Resource = sequelize.define("Resource", {
    id:         {type:Types.STRING(32), primaryKey:true},
    name:       {type:Types.STRING(128), unique:true},    // Name of resource (similar to mimetype. ex: "channel/sms")
    desc:       {type:Types.STRING(256)},
    createdBy:  {type:Types.INTEGER, field:"created_by", allowNull:false},
    createdOn:  {type:Types.DATE, field:"created_on", allowNull:false},
    modifiedBy: {type:Types.INTEGER, field:"modified_by", allowNull:false},
    modifiedOn: {type:Types.DATE, field:"modified_on", allowNull:false}
  },  
  {
    tableName:  "resources",
    timestamps: true,
    createdAt:  "created_on",
    updatedAt:  "modified_on",
    classMethods: {
      associate: function(models) {
        Resource.belongsTo(models.User, {foreignKey:'createdBy'});
        Resource.belongsTo(models.User, {foreignKey:'modifiedBy'});
        Resource.belongsToMany(models.Role, {through:'RoleResource'});
        Resource.belongsToMany(models.User, {foreignKey:"userId", through:'UserResource'});
      }   
    }   
  }); 
  return Resource;
};

```

Now, when I try to create an association entry in role_resource mapping table, by executing

```javascript
role.addResource(resource, {
    createdBy:1,
    modifiedBy:1, 
    createdOn: ''+ new Date() + '', 
    modifiedOn: '' + new Date() + '' 
})
```
it gives me error in timestamps.  I get different types of errors depending upon whether I included timestamp fields above.  If I include timestamps as above, I get this error:

> error: { [SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'createdOn' in 'field list']
>   name: 'SequelizeDatabaseError',
>   message: 'ER_BAD_FIELD_ERROR: Unknown column \'createdOn\' in \'field list\'',
>   parent: 
>    { [Error: ER_BAD_FIELD_ERROR: Unknown column 'createdOn' in 'field list']
>      code: 'ER_BAD_FIELD_ERROR',
>      errno: 1054,
>      sqlState: '42S22',
>      index: 0,
>      sql: 'INSERT INTO `role_resources_map` (`role_id`,`perms`,`created_by`,`created_on`,`modified_by`,`modified_on`,`ResourceId`,`createdOn`,`modifiedOn`) VALUES (0,0,1,\'2016-02-05 13:58:22\',1,\'2016-02-05 13:58:22\',\'1\',\'2016-02-05 13:58:22\',\'2016-02-05 13:58:22\');' },
> 

And, if I don't include timestamps, then this error:

>     errors: 
>      { [SequelizeValidationError: notNull Violation: createdOn cannot be null,
>      notNull Violation: modifiedOn cannot be null]
>        name: 'SequelizeValidationError',
>        message: 'notNull Violation: createdOn cannot be null,\nnotNull Violation: modifiedOn cannot be null',
>        errors: [Object] } } ]
> 

What am I doing wrong here?  Are custom timestamp names not supported for join tables? I haven't yet tried by removing custom names though.  Any help is highly appreciated.

**Comment by trattles** [comment]
If you look at your first error:, check out th eactual insert statement.

    sql: 'INSERT INTO role_resources_map     (role_id,perms,created_by,created_on,modified_by,modified_on,ResourceId,createdOn,modifiedOn) VALUES (0,0,1,\'2016-02-05 13:58:22\',1,\'2016-02-05 13:58:22\',\'1\',\'2016-02-05 13:58:22\',\'2016-02-05 13:58:22\');' },

It is trying to insert both created_on and createdOn.

I believe this is because sequelize automatically handles updating your timestamps for you. The way you have it configured is that you are saying

" rename createdAt to 'createdOn'"

So when it updates it actually tries to insert createdOn.

You don't need to explicitly declare your timestamp columns. Sequelize will make those automatically. But I think you explicitly declaring the createdOn column and telling it the field is 'created_on' is futzing with that auto generation.

Try not declaring your timestamp columns.

Remove createdOn and modifiedOn from your attribute declaration, but leave

    createdAt: "created_on",
     updatedAt: "modified_on",

in your config.

Then theoretically, sequelize should just handle timestamps for you and you shouldn't have to manually pass them in when updating the model.

Also note that in all your RoleResource model you are saying

createdAt: "createdOn",
     updatedAt: "modifiedOn",

and in your other models you are saying

createdAt: "created_on",
     updatedAt: "modified_on",

In role resource your'e telling sequelize to try and insert on those columns that don't exist, I think.

**Comment by trattles** [comment]
@rvnath Any progress on this issue?

**Comment by rvnath** [comment]
Sorry, I was down with fever for last 2 days. Couldn't check. Will chk shortly..

**Comment by rvnath** [comment]
Okay. I confirm that this works, If I let Sequelize manage the timestamps, or I just do the mapping like 

createdAt: "created_on",
updatedAt: "modified_on"

thank you.
