### ISSUE TITLE
"addAssociation" doesn't affect the "getAssociation" in associating object

### ISSUE THREAD

**Issue by yayayayazam** [sequelize/sequelize#5374]
Hi, I am new in sequelize. It is a very good job. Thank you.
When using the association, I would like to use the "addAssociation" and "removeAssociation" to change the relations between objects. For example:

```javascript
var User = sequelize.define('user', {
    name: { type: Sequelize.STRING }
});

var Post = sequelize.define('post', {	
    text: { type: Sequelize.STRING }
});

User.hasMany(Post);
Post.belongsTo(User);

sequelize.sync().then(function(){
    return [
        User.create({ name: 'James'}),
        Post.create({ text: 'Hello'})
     ];
}).spread(function(user, post){
    return [
          user, post,
          user.addPost(post),
     ];
}).spread(function(user, post){
    return [
          user.getPosts({raw: true}),
          post.getUser({raw: true})		
     ];	
});
```

In the case above, I thought "addPost" would establish the relation between "user" and "post". 
However, "post.getUser" still return "null" unless the "post.setUser" is set.
The same thing happens when using "removePost". It doesn't affect the "post.getUser" either.

Does it mean that I need to use "user.addPost" and "post.setPost" pairwise?

**Comment by mickhansen** [comment]
getUser is async so it should work as expected with the code you have there.
Closing since not a feature request or bug report.

**Comment by yayayayazam** [comment]
Sorry, but I think it is a bug.
After I set "user.addPost(post)", the "post.setUser()" return null.

**Comment by janmeier** [comment]
yayayayazam please post a self-contained test case

**Comment by mickhansen** [comment]
@yayayayazam I doubt there's a bug since we have extensive test coverage on that. Please post applicable SQL logs for the calls related to getUser and addPost

**Comment by yayayayazam** [comment]
Here is a test code:

```javascript
var User = sequelize.define('user', {

	name: {
		type: Sequelize.STRING
	}

});

var Post = sequelize.define('post', {

	text: {
		type: Sequelize.STRING
	}

});

User.hasMany(Post);
Post.belongsTo(User);

// data
var ut;

sequelize.sync({force: true}).then(function(){

	return User.create({name: 'test'});

}).then(function(user){

	ut = user;
	return Post.create({ text: 'Hello'});

}).then(function(post){

	ut.addPost(post);
	return Post.find({text: 'Hello'});

}).then(function(post){

	return post.getUser({raw: true});

}).then(function(res){

	console.log(res);

});
```

The "res" returns "null".

I don't know if I make any mistake here.
Thank you :D

**Comment by janmeier** [comment]
Like all other functions, addPost is async - you need to wait for it to finish before calling getPost

**Comment by yayayayazam** [comment]
I see. You are right. I need to return the promise.
And I also misused the "spread" function in my first case.
Thank you :D
