### ISSUE TITLE
options passed in setAssociations not updated in join table

### ISSUE THREAD

**Issue by ApoorvSaxena** [sequelize/sequelize#5378]
I've defined the schema of table by the name labels_association, which associated labels and model X as follows:
```
'use strict';

module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('labels_association', {
      labelId: {
        allowNull: false,
        type: Sequelize.INTEGER
      },
      associationId: {
        allowNull: false,
        type: Sequelize.INTEGER
      },
      associationType: {
        allowNull: false,
        type: Sequelize.ENUM('x', 'y')
      }
    });
  },
  down: function(queryInterface) {
    return queryInterface.dropTable('labels_association');
  }
};
```

Defining the has and belongs to many relationship of model X with labels via labels_association table
```
X.belongsToMany(Label, {
  as: 'labels',
  through: {
    model: 'labels_association',
    attributes: ['associationId', 'associationType'],
    scope: {
      associationType: 'x'
    }
  },
  foreignKey: 'associationId',
  otherKey: 'labelId'
});
```

Though at the time of setting labels for instance of model X, I am not able to set the associationType as 'x', while it should've already been taken care of by scope attribute in belongsToMany association.
```
instanceOfX.setLabels(labelIds, {
  associationType: 'x'
})
```

How can I set associationType with value 'x' in the above scenario?

**Comment by mickhansen** [comment]
the scope value should be applied automatically.

**Comment by ApoorvSaxena** [comment]
@mickhansen it works fine in find queries, but not in 'setAssociations' queries(for destroying and association). Possible for you to share the syntax of how to pass options for the join table in setAssociations call as the following doesn't work?

```
instanceOfX.setLabels(labelIds, {
  associationType: 'x'
})
```

**Comment by mickhansen** [comment]
It should work for setAssociations aswell: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L619

attributes via the second argument is the correct syntax, what does the SQL query look like?

**Comment by mickhansen** [comment]
this might be the issue:

```js
through: {
    model: 'labels_association'
}
```

`model` should always refer to an actual model, not a string

**Comment by ApoorvSaxena** [comment]
@mickhansen we intend to pass the table name via the model attribute, do we need to create a new model for the associations table? Was able to see that string can be passed in the model as well, which is used as the table name (which is exactly our use case)
https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L159

**Comment by janmeier** [comment]
When you define additional attributes on the join table, you need to pass the model

**Comment by mickhansen** [comment]
@ApoorvSaxena The intention is that you should use a model if you have attributes, we have no tests for  the other way, regardless of whether or not the code suggests it should work.

**Comment by ApoorvSaxena** [comment]
@mickhansen Thanks for the insight, can you share an example for how to define the model of N:M relationship table? Also in that case we'll have a 1:M relationship between the model and relationship table, right?

**Comment by mickhansen** [comment]
You'll only have a 1:M relationship if you explicitely define that aswell:

```js
let LabelAssociation = sequelize.define('labelAssociation', {
  associationType: {
    type: STRING
    // etc
  }
}, {
  tableName: 'label_associations'
});

X.belongsToMany(Label, {
  as: 'labels',
  through: {
    model: LabelAssociation,
    attributes: ['associationId', 'associationType'],
    scope: {
      associationType: 'x'
    }
  },
  foreignKey: 'associationId',
  otherKey: 'labelId'
});
```

**Comment by ApoorvSaxena** [comment]
Thanks a ton @mickhansen, had understood the solution, though I earlier thought that 
```
sequelize.define('labelAssociation'
```
contains labelAssociation as the table name, didn't know that had to define the table name seperately in the options of sequelize.define.

**Comment by mickhansen** [comment]
@ApoorvSaxena You don't HAVE TO unless the automatic table name generation is not behaving as you'd like.

**Comment by ApoorvSaxena** [comment]
@mickhansen Can you point me to the conventions used by sequelize for naming tables(assuming them to be plural like rails does), possible to verify the same some way?

Also, I assumed the things to work fine while removing all associations using `x.setLabels([])`, though it seems like scope is not respected during deletion, while the `x.setLabels[ids]` (for association works fine, and associationType is set respecting the scope variable). Do I need to make certain changes while removing all associations with Labels model or not?

**Comment by mickhansen** [comment]
Hmm, might be an issue with unsettings and scope.
I don't think we have a document on naming atm, but it's pluralization by default unless you use `freezeTableName`

**Comment by ApoorvSaxena** [comment]
> Hmm, might be an issue with unsettings and scope.

Can you share a resolution for the same?

**Comment by mickhansen** [comment]
Scope is not being applied in a bunch of places where it should be, to mention a few:
https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L551
https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L551

**Comment by ApoorvSaxena** [comment]
With the existing implementation, will it work if I create a composite primary key using "associationId" and "associationType"? 
https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L539

**Comment by mickhansen** [comment]
For the join table it shouldn't matter since we operate on the foreign keys, and if we fix the missing .scope support for setAssociations then it should just work, but we're not specifically testing for composites in that scenario.

**Comment by ApoorvSaxena** [comment]
Ok @mickhansen, for now, have used the following code to delete the LabelAssociation:

```
LabelAssociation.destroy({
  where: {
    associationId: x.id,
    associationType: 'x'
  }
});
```

Btw, this seems to be a more performant approach as well, as it directly triggers the `DELETE` command with the where clause, while `x.setLabels([])` first gets all ids using SELECT and WHERE clause, and then executes the DELETE command over the selected label associations.

**Comment by mickhansen** [comment]
@ApoorvSaxena setLabels is probably not optimized for the case of null|[], so your code is definitely better if the intent is a full whipe.

**Comment by ApoorvSaxena** [comment]
@mickhansen in the following case, is it possible to define attribute in the scope which is not a part of the join table but the `Label` table?

```
let LabelAssociation = sequelize.define('labelAssociation', {
  associationType: {
    type: // STRING
    // etc
  }
}, {
  tableName: 'label_associations'
});

X.belongsToMany(Label, {
  as: 'labels',
  through: {
    model: LabelAssociation,
    attributes: ['associationId', 'associationType'],
    scope: {
      type: 'first' // checks for the specific value of type
    }
  },
  foreignKey: 'associationId',
  otherKey: 'labelId'
});
```

**Comment by mickhansen** [comment]
@ApoorvSaxena Yes but then the scope would not be on `through`, rather on the association itself.
