### ISSUE TITLE
SQLite Busy database is locked

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/sequelize#5384]
I am facing lot of issues when using Sequelize as I am not really able to know the root cause of why certain sequelize queries are not working in my application. I have experienced that when there is any issue with a sequelize query I am not able to see the exact cause of the issue but can only see the message 'SQLite is Busy, database is locked' which is very frustrating. I can give an example. I have created a transaction table in my SQLite db and when I try to insert into this table using the following code:
```js
        models.transaction.create({TransactionStatusId: 1, TransactionTypeId: 1, TransactionTimeStamp: '123', TransactionEntityId: '0'}).then((trn) => {
          console.log('Test');
        }).catch((err) => {
          throw err;
        });
````
I always land up in the catch block with an error: SQLite is busy , database is locked. I cannot come to know why this error is showing and every time in past this error has always come whenever there has been some issue with writing sequelize query properly.

**Comment by janmeier** [comment]
Can you show an [SSCCE](HTTP://SSCCE.ORG/)?

**Comment by zeeshanjan82** [comment]
sure , I will try to be as detailed as I can: I am using SQLite DB and have created a model 
````js
'use strict';
module.exports = function(sequelize, DataTypes){
  var Transaction = sequelize.define("transaction", {
   TransactionId: {
     type: DataTypes.INTEGER,
     primaryKey: true,
     autoIncrement: true
   },
  TransactionStatusId: DataTypes.INTEGER,
  TransactionTypeId: DataTypes.INTEGER,
  TransactionTimeStamp: DataTypes.STRING,
  TransactionEntityId: DataTypes.STRING
  })
  return Transaction;
}
````
This is my transaction table and am trying to insert new row into this table using the query
````js
 models.transaction.create({TransactionStatusId: 1, TransactionTypeId: 1, TransactionTimeStamp: '123', TransactionEntityId: '0'}).then((trn) => {
          console.log('Test');
        }).catch((err) => {
          throw err;
        });
``````
In the above code models is
````js
var models = require('./models'),
`````
Its the folder which includes the index.js model class where I have defined the location of my sqlite file.

**Comment by sushantdhiman** [comment]
@zeeshanjan82 Which version you are using?

**Comment by zeeshanjan82** [comment]
@sushantdhiman I am uisng version 3.8 of Sequelize

**Comment by sushantdhiman** [comment]
Can you give it a try against latest version i.e. `3.19.2`, A related [PR](https://github.com/sequelize/sequelize/pull/5157) might have solved this issue.

**Comment by zeeshanjan82** [comment]
Thanks @sushantdhiman I will try that

**Comment by zeeshanjan82** [comment]
The issue is fixed with latest version of Sequelize thanks @sushantdhiman
