### ISSUE TITLE
MySql DATE(6) insertion fails on InnoDB with "Error Code: 1292. Incorrect datetime value"

### ISSUE THREAD

**Issue by AJamesPhillips** [sequelize/sequelize#5387]
I'm using mysql `Ver 14.14 Distrib 5.7.10, for osx10.9 (x86_64)` which is greater than 5.6.4+ mentioned in https://github.com/sequelize/sequelize/blob/2115a06d5a87fa130e191a73b58c63a062ad6dd7/lib/dialects/mysql/data-types.js#L33

But trying to execute the SQL queries:
```sql
CREATE TABLE `tests` (
  `datetime_field` datetime(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `tests` (`datetime_field`) VALUES ('2016-02-09 22:07:13.014123 +00:00');
```
generated by:
```js
var Test = sequelize.define('tests', {
  datetime_field: Sequelize.DATE(6)
});
// sync
Tests.create({datetime_field: new Date()});
```
gives the error:
```
Error Code: 1292. Incorrect datetime value: '2016-02-09 22:07:13.014123 +00:00' for column 'datetime_field' at row 1
```
However without the timezone it succeeds:
```sql
INSERT INTO `tests` (`datetime_field`) VALUES ('2016-02-09 22:07:13.014123');
```

I'm new to both MySql and Sequelize but this commit seems to fix it, haven't run tests so not sure if it's also broken on other dialects or if there's a better way of fixing this:  https://github.com/AJamesPhillips/sequelize/commit/ed94a656e31c083033cc807d2a3bbd4894e91ac6

**Comment by sobotklp** [comment]
I believe it should not be writing the timezone, as it'll be ignored by MySQL. Versions of MySQL prior to 5.7 would ignore the timezone info, but it seems newer versions produce the error you're seeing.

**Comment by AJamesPhillips** [comment]
@sobotklp ok, yeah I haven't been able to test anything else but I hope the commit is in the right direction.  Thanks very much for [your original commit](https://github.com/sobotklp/sequelize/commit/f333d295364d24dd9b2be80223b6f607de0b7956) :+1:

**Comment by AJamesPhillips** [comment]
p.s. how did you find out about this issue so quickly?!... you have some super subscription / filter settings set somewhere?  :smile:

**Comment by sobotklp** [comment]
Heh, you can subscribe to all updates from the sequelize project by clicking the Watch button at the top of the screen :)

**Comment by Sencerd** [comment]
Can we get this merged?

**Comment by AJamesPhillips** [comment]
@Sencerd this PR doesn't currently meet the contribution guidelines as it lacks a test:  https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md  could you take a look an add one please?  Sorry I can't prioritise this at the moment.  If you're in a real bind remember you can add and install github repos as npm dependencies.

**Comment by AJamesPhillips** [comment]
@Sencerd, thanks for the interest in this issue.  This PR unfortunately doesn't currently meet the contribution guidelines as it lacks a test: https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md  Could you take a look and add one please? Sorry I can't prioritise this at the moment. If you're in a real bind remember you can add and install github repos as npm dependencies.

**Comment by sobotklp** [comment]
My PR above adds a test case for serialization of fractional datetimes with MySQL.

**Comment by AJamesPhillips** [comment]
That's great @sobotklp thanks!  @Sencerd looks like it's good to merge now.

**Comment by AJamesPhillips** [comment]
Thanks @janmeier
