### ISSUE TITLE
Sequelize + Mysql  returns  null  id  but in my table the id is correctly created

### ISSUE THREAD

**Issue by matteolefthanders** [sequelize/sequelize#5388]
I use sequelize with mysql and in my table 'users' i have a before_insert trigger that calls a function that create my row's id.

when i run:

userObj = {someField: 'some1', someOtherField: 'some2'};   // Obviously without id
 db.User.create(userObj, { fields: Object.keys(userObj), transaction: t })
 .then( (newUser) => {
    // HERE
    newUser['id'] = null; // BUT ON MY TABLE it has a valid value
 });
so i have correct entry on my id but sequenze, after  User.create returns null.

**Comment by mickhansen** [comment]
We'll need to see your model definition. However this is usually caused by an incorrect configured primary key (missing primarKey, autoIncrement or both)

**Comment by matteolefthanders** [comment]
Hi and thanks  for the reply.
My id is a STRING(6) that has  primaryKey: True ( autoIncrement for string
value is not allowed).
With sequelize-cli  migration i added triggers and stored function (that
help me to create unique  id)
Ps.  I need that triggers  and function on mysql cause my service that use
sequelize isnt the only that Connect to db
Il 10/feb/2016 08:22 AM, "Mick Hansen" <notifications@github.com> ha
scritto:

**Comment by janmeier** [comment]
If the id is not autoincrement, then how is it generated?

**Comment by matteolefthanders** [comment]
Jan theres a before insert trigger that call a function  that create unique
string
Il 10/feb/2016 08:42 AM, "Jan Aagaard Meier" <notifications@github.com> ha
scritto:

**Comment by janmeier** [comment]
Is the table created by `.sync` - if not you should add `autoIncrement`, since it will not change the table, but make sequelize work :)

**Comment by matteolefthanders** [comment]
Try it as soon as possibile.
Thanks
Il 10/feb/2016 08:48 AM, "Jan Aagaard Meier" <notifications@github.com> ha
scritto:

**Comment by matteolefthanders** [comment]
@janmeier the tables are created using .sync :(

**Comment by mickhansen** [comment]
@matteolefthanders does `mysql_last_insert_id` work with a mysql trigger?
In any case Sequelize only knows to look for an auto generated value if autoIncrement: true.
MySQL does not support RETURNING like PG

**Comment by matteolefthanders** [comment]
i don't think so, from MySQL Documentation 
" LAST_INSERT_ID() returns only automatically generated AUTO_INCREMENT values. "

**Comment by mickhansen** [comment]
Okay, it's likely not possible. In any case your first step should be to verify that you can get the desired effect using mysql directly with an INSERT

**Comment by matteolefthanders** [comment]
Okay i'll try, tnx.

**Comment by GopalPatidar54** [comment]
Sequelize create method returns a null value on those fields which are created using the before_insert trigger. Anyway, create a method to return the correct value.

-  I create a table of users {id, name, last_name, uuid}
- create a Row-Level Trigger before_insert on uuid
`before_insert_users | INSERT | users | BEGIN SET new.uuid = uuid();`
-  user.create({name:"cyz",last_name:"abc"}), return value {id:213,name:"cyz",last_name:"abc" ,uuid:null }

- select * from users;
 {id:213,name:"cyz",last_name:"abc" ,uuid: "98ba5d71-85e5-11ed-aa69-b06088d9a387" };


there is any way to return the correct value in create method?
