### ISSUE TITLE
Question: Is it safe to use custom property configurations?

### ISSUE THREAD

**Issue by VividVisions** [sequelize/sequelize#5393]
I'd like to add custom property-specific configurations to my models (e.g. hints for the UI how to handle this property in forms, etc…). To avoid redundancy, I thought about adding them directly to the respective definition object using some sort of namespace. Sequelize just ignores unknown values, right?

```javascript
var Foo = sequelize.define('foo', {
    bar: {
        type: Sequelize.STRING,
        // [...],
        ns_my_custom_propery: 'my custom value',
        // or
        namespace: {
            one: 1,
            two: 2
        }
    }
});
```

If this is considered unsafe and/or an awful hack, what would be an (as redundancy-free as possible) alternative?

**Comment by mickhansen** [comment]
Should be safe as long as you don't clash with current or future naming.

**Comment by VividVisions** [comment]
Great, thank you! My namespace should be safe enough. Would also be easy enough to change in the future. At least easier than to maintain two or more separate property configurations.
