### ISSUE TITLE
Can't insert self reference

### ISSUE THREAD

**Issue by WalterC87** [sequelize/sequelize#5397]
Hi, I have a problem when I'm trying to insert a self reference in my table.

- I'm using MySql
- I'm using Sequelize 3.12.2 (that version show my package.json)

- I have this code:

### Model
```JavaScript
module.exports = function (sequelize, DataTypes){
	var User= sequelize.define('User', {
		userLogin: {
			type: DataTypes.STRING,
			allowNull: false,
			unique: true,
			validate: {
				len: [2,150]
			}
		},
		password: {
			type: DataTypes.STRING,
			allowNull: false,
			validate: {
				len: [4, 150]
			}
		},
		email: {
			type: DataTypes.STRING,
			allowNull: false,
			validate: {
				isEmail: true
			}
		},
		token:{
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null
		},
		phone: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null,
			validate: {
				len: [8,15]
			}
		},
		status: {
			type: DataTypes.BOOLEAN,
			defaultValue: true
		}
	},{
		classMethods: {
			associate: function(models){
				User.hasOne(models.User, {as: 'Dad', foreignKey: {field: 'dadId', allowNull: true}});

			}
		},
		freezeTableName: true,
		tableName: 'user'
	})

	return User;
}
```

this create a table named user with the attribute dadId, but when I've try to insert a row, and sent all parameters, the instruction dont insert dadId, even if I send the parameter with a value.

### My Insert
```JavaScript
exports.postSeller = function(req,res,next){
	models.User.create({
		userLogin: req.body.userLogin,
		firstName: req.body.firstName,
		lastName: req.body.lastName || null,
		email: req.body.userLogin,
		password: req.body.password,
		token: genToken(),
		status: 1,
		dadId: req.body.dadId
	}).then(function (user){
		if(!user){
			res.status(500);
			res.json({
				type: false,
				data: "Error: " + user
			});
		}else{
			res.status(200);
			res.json({
				type: true,
				data: "success"
			});
		};
	});
};
```

the console show me the insert and that looks good but, don't appear the instruction to insert the attribute dadId, I'm sending this from postman:

![testapi](https://cloud.githubusercontent.com/assets/3922920/12958817/1dd4bdc2-cff9-11e5-91cd-e4cd6d352ba5.PNG)

my insert works fine, but not like I need it, because is not inserting the attribute dadId.

**Comment by janmeier** [comment]
Please show the code you are using to insert as well. What is happening?

**Comment by WalterC87** [comment]
@janmeier tell me if you need more info, thanks.

**Comment by janmeier** [comment]
Try `DadId` with a capital d. The name of the attribute matches the string you pass to `as`. `field ` only controls the name of the field in the db

**Comment by WalterC87** [comment]
@janmeier I've tried with your advice, but still happen the same issue, I'm doing something wrong in my statements?

**Comment by janmeier** [comment]
Hmm, it seems the attribute (the name in the model) actually defaults to `userId`, even when `as` is set. I though it would always be `[as][primaryKey]` for all associations, right @mickhansen ?  Thats how it works for belongsTo.

@WalterC87 For now you can use `foreignKey: { name: 'dadId', field: 'dadId', allowNull: true}` - `name` specifies the name of the attribute in the model, while `field` specifies the name of the attribute in the database

**Comment by mickhansen** [comment]
@janmeier belongsTo is the only one that uses the alias for foreign key. Simply for the reason that having `Organization.hasMany(User, {as: 'Employee'})` generating a `employeeId` on User would be wrong.

**Comment by janmeier** [comment]
True dat :D - And in this case it should actually also be belongsTo User as Dad and hasMany User as Offspring foreignKey DadId

Thanks for clearing it up , I must be tired :)

**Comment by WalterC87** [comment]
So, how should be my statement, for it works? @mickhansen

**Comment by janmeier** [comment]
Did you was my comments @walterc87? Use either name or switch to belongs to

**Comment by WalterC87** [comment]
@janmeier hehe sorry, I'll try, I let you know if works.

**Comment by WalterC87** [comment]
@mickhansen @janmeier thanks a lot for your help, works with belongsTo.
