### ISSUE TITLE
rethinkdb

### ISSUE THREAD

**Issue by KiPSOFT** [sequelize/sequelize#5398]
this possible ? rethinkdb dialect or hows prepare custom dialect ?

**Comment by janmeier** [comment]
All of sequelize internals are built around sql queries, while rethinkdb has a radically different api. I think that alone is would make it too difficult to integrate. 

Additionally, the streaming and push ideas from rethinkdb would be lost if it was integrated with sequelize. 

We prefer to stick to regular sql based databases, in order not to spread ourselves too thin
