### ISSUE TITLE
Question: different approach for eager loading

### ISSUE THREAD

**Issue by josser** [sequelize/sequelize#5402]
Hi
I have found interesting technique for handling nested models.

Here is gist: https://gist.github.com/josser/e14ae571d0f94417cd65

What do you think, can it be better than current implementation with several sub-queries? 
I see some profits: 
- use limit/offsets and any conditions in sub-queries. 
- no need for post-processing of query results.
Cons: works only in postgresql and looks like only 9.4+ :( 

This is just an idea and I'm not a big SQL-guru so I don't know will it fast enough or have some backsides. 
Thanks and sorry for my bad english.

**Comment by mickhansen** [comment]
Only having it work in PG makes it a non-starter i'm afraid. However you can use it as a optimization in your own code.

**Comment by josser** [comment]
So, theoretically I can write custom postgresql-driver which will generate such queries?

**Comment by mickhansen** [comment]
Possibly, but you can also just target a view with your models.

**Comment by josser** [comment]
With view I can't add where conditions to sub-queries
