### ISSUE TITLE
how to mix $or and $col

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#5408]
Hi,

Assuming I need to do the next conditioning:
`where user.email=fake@gmail.com or user.table1.table2.number = 333`

I need to user `$or` operator, from the other side, I need to use `$col` operator, to tell the sequelize that I've prepared the columnname for it.

What I've tried is:
```
where: {
    $or: [{
        email: 'fake@gmail.com'
    }, {
        $col: 'table1.table2.number',
        $eq: 333
    }]
}
```

However, it turns to the error:
![image](https://cloud.githubusercontent.com/assets/839290/13006388/0444d9aa-d189-11e5-901e-84aa2835531e.png)

How can I pass the custom column name to `$or` operator?

Regards,

**Comment by mickhansen** [comment]
That setup should just work, looks like you've found a bug

**Comment by janmeier** [comment]
Are you using the latest version :) ?

**Comment by PavelPolyakov** [comment]
@janmeier 
just installed the `3.19`, the behaviour is the same though.

Is there a way I can overcome this behaviour for now?

**Comment by PavelPolyakov** [comment]
@janmeier @mickhansen 

I have found, that I can do the next:
```javascript
this.find({
    include: [{
        model: server.methods.getModel('ClientData'),
        include: [{
            model: server.methods.getModel('PhoneNumber')
        }]
    }],
    WHERE: this.sequelize.literal(`email='${email}' OR clientData.phoneNumbers.number='${phonenumber}'`)
});
```

However, the query which will be generated, looks the next way:
```sql
SELECT "user".*,
       "clientData"."xx" AS "clientData.xx",
       "clientData"."yy" AS "clientData.yy",
FROM
  (SELECT "user"."xx",
          "user"."yy"
   FROM "user_" AS "user"
   WHERE email = 'fake@gmail.com'
     OR "clientData.phoneNumbers".number = '333' LIMIT 1) AS "user"
LEFT OUTER JOIN "clientdata" AS "clientData" ON "user"."id" = "clientData"."owner_id"
LEFT OUTER JOIN "phonenumber" AS "clientData.phoneNumbers" ON "clientData"."id" = "clientData.phoneNumbers"."clientdata_id";
```

The condition is applied to the *user* table (pay attention on WHERE condition), however, I want it to be applied to the whole query, like this:

```sql
SELECT "user".*,
       "clientData"."xx" AS "clientData.xx",
       "clientData"."yy" AS "clientData.yy",
FROM
  (SELECT "user"."xx",
          "user"."yy"
   FROM "user_" AS "user") AS "user"
LEFT OUTER JOIN "clientdata" AS "clientData" ON "user"."id" = "clientData"."owner_id"
LEFT OUTER JOIN "phonenumber" AS "clientData.phoneNumbers" ON "clientData"."id" = "clientData.phoneNumbers"."clientdata_id"
WHERE "user".email = 'hello@gmail.com' or "clientData.phoneNumbers".number = '333';
```

Is that possible to apply those conditions on the whole query? Or I'm using the wrong concept? I do this query using the "user" model.

Regards,

**Comment by janmeier** [comment]
Try with 
```js
where: {
    $or: {
        email: 'fake@gmail.com',
        '$table1.table2.number$': 333
    }
}
```

**Comment by PavelPolyakov** [comment]
@janmeier 

This one works and generates the query I want, is it documented somewhere?

And, still interesting, with the `sequelize.literal` concept - is it an expected behaviour that condition goes to "inner" query? Or I should create another issue?

Regards, thanks for helping me!

**Comment by janmeier** [comment]
I dunno whether its documented yet - @mickhansen ? Never seen the `$col` syntax before actually, so maybe you're confusing it with that :D ?

The expected behavior is to use the inner query, since we don't know that you are querying the join when using `.literal`. The whole reason we are doing in inner query is because of the limit - we need to filter and limit first before joining. (the limit 1 is added because you are using `find` as opposed to `findAll`).

Using the `$$` syntax tells sequelize that you are querying on joined rows, which moves the where clause to the outer query.

**Comment by mickhansen** [comment]
@janmeier $col is the counter part of $key$ letting users target a column, generally used in conjunction with $key

**Comment by PavelPolyakov** [comment]
Thanks!

**Comment by PavelPolyakov** [comment]
@janmeier 
Hi,

does that mean that `$col` variant works now?
Don't see it in the latest release: https://github.com/sequelize/sequelize/releases .

Regards,

**Comment by janmeier** [comment]
@PavelPolyakov As mick said, $col is used in conjunction with $$, e.g https://github.com/sequelize/sequelize/blob/a49a7c1d7281952c19af9daf416634c56f90bf7f/test/unit/sql/where.test.js#L366

**Comment by PavelPolyakov** [comment]
Thanks, now it's clear.

**Comment by knoxcard** [comment]
How would one mix "and and or" together?  Where is the documentation? Christ Almighty...lol

For example, WHERE a=1 AND b=1 OR c=3
