### ISSUE TITLE
Use $like on JSON data type

### ISSUE THREAD

**Issue by pensierinmusica** [sequelize/sequelize#5409]
Hi,

I'm using Sequelize with PSQL. 

I need to build a destroy query that can use the `$like` operator on a JSON data type.

For example, let's take this model definition:

``` js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('database', 'username', 'password');

var Project = sequelize.define('project', {
  name: Sequelize.STRING,
  details: {
    type: Sequelize.JSON,
    defaultValue: {}
  },
});
```

Now, I would like to be able to run a query to destroy all Project entries that don't have any details:

``` js
Project.destroy({
  where: {
    details: {
      $like: '{}'
    }
  }
})
```

But I get this error:

```
[SequelizeDatabaseError: operator does not exist: json ~~ unknown]
```

So, is there any way to do this and how?

Thanks!!

**Comment by janmeier** [comment]
Can't you just use 
```js
Project.destroy({
  where: {
    details: {}
  }
})
```

**Comment by pensierinmusica** [comment]
@janmeier what you suggest seems to destroy all instances. Can you please check? Thx

**Comment by janmeier** [comment]
Hmm, that's because `details: {}` gives an empty where clause - definitely a bug.

I think we need to add a special case to handle empty objects:
```sql
DELETE FROM projects where details::jsonb = '{}'::jsonb;
```
Note that both columns need to be cast to jsonb, since json does not support equality

**Comment by janmeier** [comment]
Or we could cast to string or use `json_each` for something that also works without jsonb http://stackoverflow.com/questions/24292575/how-to-query-a-json-column-for-empty-objects

**Comment by janmeier** [comment]
On a side-note, this case also shows that we probably need to add a safeguard against update / delete with empty where clauses, for these cases where the `where` clause is interpreted incorrectly

**Comment by pensierinmusica** [comment]
@janmeier agree to add a safeguard against update / delete with empty where clauses.

Regarding the rest, in this case I chose JSON vs JSONB for reasons and would prefer not having to change it. On the other hand, the [SO article](http://stackoverflow.com/questions/24292575/how-to-query-a-json-column-for-empty-objects) you mentioned states:

> There is no equality (or inequality) operator for the data type json as a whole.

I wish PostgreSQL offered a quick, easy way to check if the object has been modified or is empty. It seems like it currently doesn't though, right?

My workaround in the end will probably be to keep another column as a "flag" boolean to know if the JSON is empty or not. Wish there was a more elegant solution, let me know if you find one.

Thanks! Cheers

**Comment by janmeier** [comment]
Should be possible to implement the empty check by casting the json to string though :-) (in sequelize, not knowing what your own code)

**Comment by pensierinmusica** [comment]
@janmeier do you mean permanently changing the column data type from JSON to String, or going through each row, read the values and output them as text?

**Comment by janmeier** [comment]
No, you don't need to change anything, I'm saying that for this particular query we need to cast the field to a string to check whether it's empty

**Comment by pensierinmusica** [comment]
Sure, this means though that you need to read each row in the db and can't keep an index, right?

**Comment by pensierinmusica** [comment]
Why has this been closed?

**Comment by GabeAtWork** [comment]
I'm experiencing the same issue, as I'm attempting to find a string in a `JSON` field. It returns the following error: `operator does not exist: json ~~ unknown`.

That same query works fine on a `STRING` field, though. I'm puzzled, as the docs specify that the field should be treated as plain string on PostgreSQL (which I'm using): http://docs.sequelizejs.com/manual/tutorial/querying.html

**Comment by oaeide** [comment]
I have the same problem as @GabeAtWork

**Comment by ephys** [comment]
https://github.com/sequelize/sequelize/pull/15598 implements this.

```ts
Project.destroy({
  where: {
    // Depending on the dialect you may need to cast the value like this:
    'details::text': {
      [Op.like]: '{}'
    }
  }
})
```

Produces

```ts
DELETE FROM "Project" WHERE CAST("details" AS TEXT) LIKE '{}'
```
