### ISSUE TITLE
Support for defining table and schema owner

### ISSUE THREAD

**Issue by tayden-hakai** [sequelize/sequelize#5411]
I understand there is currently no way to override the database connected user as being the owner of tables and schemas created. It'd be nice if this was available so that the owner could be set to some group role instead of the user role.

**Comment by janmeier** [comment]
Not really sure this is usecase we need to support. You could just connect with the other user using sequelize and call `.sync` - since that is the only place tables will ever be created (apart from migrations).

Is there any syntax for defining the owner, or do you have to connect as that user?

**Comment by tayden-hakai** [comment]
Typically you use AUTHORIZATION and/or GRANT commands to give permissions to other users. My personal use case is to give other's access to the tables via a postgres role that I don't have a password for. Thinking about it more though, this might allow modification of tables without it being reflected in the Sequelize model definitions, screwing up the API I've written. Thus, I'm closing the issue.
