### ISSUE TITLE
set autocommit=0 in transaction bug.In a concurrent,generating a large number of deadlock

### ISSUE THREAD

**Issue by bugall** [sequelize/sequelize#5415]
The default configuration of a transaction autocommit is 1

In a concurrent , if autocommit is set to 0. Then the connection of execute the transaction will then perform other DML statements. These statements are not submitted。Because the connection execute dml statements set autocommit＝0.

if user set autocommit=0 .connection should be closed when the connection of execute transaction is finished,avoid execute other DML sql

**Comment by mickhansen** [comment]
Not exactly sure what you're trying to get at here.
There's existing issues that deal with setting any default values from Sequelzie in 4.0

**Comment by bugall** [comment]
@mickhansen why sequelize support user to set a error parameter in transaction(autocommited=0)?
in other words，when user use connection-pool  to finish a transaction ,the connection should be closed immediately.

**Comment by bugall** [comment]
@mickhansen 
i see the sequelize current version is 3.19 on the npmjs.com。
why sequelize support user to set a error parameter in transaction(autocommited=0)?
in other words，when user use connection-pool to finish a transaction ,the connection should be closed immediately, but connection-pool did not do it

**Comment by mickhansen** [comment]
It's not an error in earlier versions of postgres.
A connection can be reused after a transaction. We reserve the connection for the transaction period after which it's returned to the pool.

**Comment by bugall** [comment]
@mickhansen 
i know about reserve the connection,but if we set transaction commit level is not auto-commit, the connection will execute DML sql without commit。

**Comment by mickhansen** [comment]
Only if you're executing DML statements, and that should be reserved for migrations in my opinion. You can change the auto commit setting.

**Comment by bugall** [comment]
but connection not be reserved when a tranasction finished ,it will be execute other sql. if we can release the connection when finish transaction,it will be not produce deadlock。

i means that connection pool shuold be reserved connection when transaction commit level set not auto commit

**Comment by mickhansen** [comment]
The connection is reserved untill you commit or rollback - It won't execute any other SQL. If you have a case where this happens open a pull request with a failing test.

**Comment by bugall** [comment]
i'm sure that connection not be reserved when transaction commit. 
i will pull request a failing test as soon as possible

Thank you for your patience.

**Comment by mickhansen** [comment]
Well that would definitely be a bug then - But the connection reservation is in no way dependent on the options you pass to a transaction, so the bug would exist under all conditions.

**Comment by bugall** [comment]
i find a lot of deadlock in mysql project then i check mysql execute log, have some transaction connectionId execute DML statements not be commited when set autocommit=0

**Comment by bugall** [comment]
wrong case in here
https://github.com/bugall/sequelize-case/tree/master

**Comment by mickhansen** [comment]
You list having autocommit: true as the fix, however that's the default for transactions?
Connections are not shared while being used in a transactions, it's however released back to the pool on a commit or rollback.

Can you please reduce your case to a integration test and submit that as a PR?

**Comment by mickhansen** [comment]
Or can you point to MySQL documentation that sheds light on whether or not reusing a query after a ROLLBACK on a autocommit=0 connection is the wrong thing to do?

**Comment by bugall** [comment]
Sorry I didn't make myself clear enough. 

What I'm confused here is, under what circumstance, we should set autocommit = false?

In the past, I misunderstood that, if I set autocommit to be true, the steps in transaction would be committed automatically after each is done, instead of committing after the whole transaction is executed . Thus I set autocommit = 0 on each transaction. 

After the transaction got committed, the connection was not released after the transaction, but got reused by other DML sql requests. As autocommit was set to be false, the following non-transaction-DML sqls would never be committed, and the resources that got locked would never be released, all the read/write requests on the resource would be on the waiting list until the time is due. 

After some exploring, I found that transaction would be be committed sentence by sentence when setting autocommit=true, then I switched autocommit to the default setting, and the deadlocks disappeared.

Now my confusion is, why should we have the option on transaction to set autocommit = 0, as it has no positive impact but cause lots of deadlocks?

**Comment by mickhansen** [comment]
@bugall It's a valid option so it's present, up to the user when it's correct to use. The question is what we should do with the connection after a ROLLBACk in these cases, sounds like it has to be discarded, which i wouldn't think would be the case, since it's a transaction.
