### ISSUE TITLE
Duplicate primary key error while inserting records into a table wtih composite primary key

### ISSUE THREAD

**Issue by rvnath** [sequelize/sequelize#5419]
I created a join table using sequelze define, as below:

```javascript
module.exports = function(sequelize, Types) {

  var UserResource = sequelize.define("UserResource", {
    userId:     {type:Types.INTEGER, primaryKey:true},                      // references user id in ecp_user_master table
    resourceId: {type:Types.STRING(32), primaryKey:true},                   // references resource id in resources table.
    perms:      {type:Types.INTEGER, defaultValue:0},                       // unix perms rwx format (r=4,w=2,x=1)
    createdBy:  {type:Types.INTEGER, field:"created_by", allowNull:false},  // Below 4 fields are for audit tracking of table modifications.
    modifiedBy: { type:Types.INTEGER, field:"modified_by", allowNull:false},
  },
  {
    tableName:    "user_resources",
    timestamps:   true,
    createdAt:    "created_on",
    updatedAt:    "modified_on",
    classMethods: {
      associate:  function (models) {
        UserResource.belongsTo(models.User, {foreignKey:'createdBy'});
        UserResource.belongsTo(models.User, {foreignKey:'modifiedBy'});
      }
    }
  });
  return UserResource;
}
```

In order to test this from commandline, I ws inserting a few records.  First insertion successful, but the 2nd one fails, even though the composite key is unique.

> 
> mysql> desc user_resources;
> +-------------+-------------+------+-----+---------+-------+
> | Field       | Type        | Null | Key | Default | Extra |
> +-------------+-------------+------+-----+---------+-------+
> | userId      | int(11)     | NO   | PRI | 0       |       |
> | resourceId  | varchar(32) | NO   | PRI |         |       |
> | perms       | int(11)     | YES  |     | 0       |       |
> | created_by  | int(11)     | NO   | MUL | NULL    |       |
> | created_on  | datetime    | NO   |     | NULL    |       |
> | modified_by | int(11)     | NO   | MUL | NULL    |       |
> | modified_on | datetime    | NO   |     | NULL    |       |
> +-------------+-------------+------+-----+---------+-------+
> 7 rows in set (0.00 sec)
> 
> mysql> select * from user_resources;
> +--------+------------+-------+------------+---------------------+-------------+---------------------+
> | userId | resourceId | perms | created_by | created_on          | modified_by | modified_on         |
> +--------+------------+-------+------------+---------------------+-------------+---------------------+
> |      3 | 4          |     4 |          1 | 2016-02-14 13:54:22 |           1 | 2016-02-14 13:54:22 |
> +--------+------------+-------+------------+---------------------+-------------+---------------------+
> 1 row in set (0.00 sec)
> 
> mysql> insert into user_resources value(3, '3',0, 1,now(),1, now());
> ERROR 1062 (23000): Duplicate entry '3' for key 'user_resources_userId_userId_unique'
> mysql> 

However, if I create the table outside of sequelize (i.e. by using create table syntax), it seems to work.  Am I doing something wrong here?  Is my sequelize syntax for creating a compsite primary key correct?

**Comment by rvnath** [comment]
I enabled creation script logging, and this is the snippet for creating this table.

>  Executing (default): CREATE TABLE IF NOT EXISTS `user_resources` (`userId` INTEGER , `resourceId` VARCHAR(32) , `perms` INTEGER DEFAULT 0, `created_by` INTEGER NOT NULL, `modified_by` INTEGER NOT NULL, `created_on` DATETIME NOT NULL,     `modified_on` DATETIME NOT NULL, UNIQUE `user_resources_userId_userId_unique` (`userId`), PRIMARY KEY (`userId`, `resourceId`), FOREIGN KEY (`userId`) REFERENCES `ecp_user_master` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN     KEY (`created_by`) REFERENCES `ecp_user_master` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`modified_by`) REFERENCES `ecp_user_master` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;

I am not an expert of database, but I can see that this UNIQUE seems to be preventing insertion of another row for same user id, even though the overall composite key is unique.  

> UNIQUE `user_resources_userId_userId_unique` (`userId`)

Any help how to overcome my problem...?

**Comment by mickhansen** [comment]
Sequelize does not add unique indexes based on a belongsTo relation.
Is UserResource also used as the join model of a N:M relation?

**Comment by rvnath** [comment]
UserResource is a custom join table that I created.  It is used in a N:M relation between user master and resource master table (via "through").  The javascript code for these 3 models viz., user master, resources master and user_resources has been shared in a similar issue reported #5418

**Comment by mickhansen** [comment]
N:M creates a unique index on the two foreign keys, not one. Something must be misconfigured.
Do note that GitHub is not for common questions but for bugs and feature requests. Please use appropriate channels for general questions (Slack, IRC, StackOverflow)
