### ISSUE TITLE
(Sequelize+Postgres+NodeJS) Inster FK (userID) from afterCreate hook

### ISSUE THREAD

**Issue by Hoax00** [sequelize/sequelize#5420]
I'm using Sequelize connected to PostgreSQL and as I want to use sync function I would like to prepare valid models to create tables on every environment.

I want to insert PK from User to Wallet as FK.

Wallet:

    'use strict';
    
    module.exports = function(db, DataTypes) {
      var Wallet = db.define('Wallet', {
        id: {
          type: DataTypes.INTEGER,
          autoIncrement: true,
          allowNull: false,
          primaryKey: true
        },
        money: {
          type: DataTypes.INTEGER,
          allowNull: false,
          defaultValue: 0
        }
        createdAt: DataTypes.DATE,
        updatedAt: DataTypes.DATE
      }, {
        tableName: 'wallet',
        classMethods:{
          associate : function( models ) {
            Wallet.belongsTo( models.User,{ foreignKey : 'id_user'});
          }
        }
    
      });
    
      return Wallet;
    };

User:

    'use strict';
    var bcrypt = require('bcrypt-nodejs');
    var crypto = require('crypto');
    var moment = require('moment');
    var models = require('./');
    
    
    var afterCreateHook = function(user, options, fn) {
      models.Wallet.build({id_user: user.id}).save();
      fn(null, user);
    };
    
    module.exports = function(db, DataTypes) {
      var User = db.define('User', {
        id: {
          type: DataTypes.INTEGER,
          autoIncrement: true,
          allowNull: false,
          primaryKey: true
        },
        password: DataTypes.STRING,
        email: {
          type: DataTypes.STRING,
          unique: true,
          allowNull: false,
          isEmail: true
        },
        login: {
          type: DataTypes.STRING,
          unique: true,
          allowNull: false
        }
      }, {
        tableName: 'pl_users',
        instanceMethods: instanceMethods,
        classMethods: {
          associate : function( models ) {
            User.hasOne( models.Wallet);
          }
          
        },
        hooks: {
          afterCreate: afterCreateHook
        }
      });
    
      return User;
    };

Why 

    models.Wallet.build({id_user: user.id}).save();

is not working? Account is creating and then I want to create wallet with specific user_id. I don't have even an error...

Help please!

**Comment by mickhansen** [comment]
It should just work. What isn't working exactly?
What have you tried in terms of debugging? You're not giving us a lot to go on here.

**Comment by Hoax00** [comment]
I managed to get it working by using 

```
var afterCreateHook = function(user, options, fn) {
  this.associations.Wallet.target.create({ id_user: user.id })
      .then(function(otherModel) {
        fn(null, user);
      })
      .catch(function(err) {
        return;
      });
};
```

any other solution? And why regular one doesnt work?

**Comment by mickhansen** [comment]
You never told us exactly what wasn't working, so i have no way to answer that. create and build/save are equivelant. The only change is that you're actually waiting for the call to finish before you execute the callback, so it depends on what you're doing after to veridy "that it works"
