### ISSUE TITLE
`$key$` with `limit` with get `missing FROM-clause entry for table`

### ISSUE THREAD

**Issue by devmark** [sequelize/sequelize#5423]
`$key$` with `limit` with get `missing FROM-clause entry for table`
Without limit, will be work. 
using postgresql
code: 

```
filter = {
    where: {
      $or: [
          {baseOn: 'all'},
          {baseOn: 'group', where:{'$group.id$' : {$in : [1,2,3]}}}
      ]
    },
    include: [
      {
        model: models.Group, as: 'groups', required: false,
        through: models.GroupUser,
      }
    ],
    limit: 100,
};
```

If using limit , query will look like
```
SELECT * FROM (SELECT ... )
```

only $key$
```
SELECT * FROM User ...
```

**Comment by mickhansen** [comment]
There's no logic to move `$key$` to outside the main table.
Even if there was your query would be faulty since your limit would be useless.
