### ISSUE TITLE
Search string inside tables

### ISSUE THREAD

**Issue by Randikaprasad** [sequelize/sequelize#5424]
I tried to get search results from few tables but I didn't get matched results according to my selection.  My Issue is : 

There are few tables and they have many-to-many relations each other. Then I want to search a string which has included in any table.  How I implement such a functions to find a string in all tables's columns ? Please Help !!!

**Comment by janmeier** [comment]
Please show some code, preferrably a [SSCCE](HTTP://SSCCE.ORG/)
