### ISSUE TITLE
Failed to getAssociation() in afterCreate

### ISSUE THREAD

**Issue by Aukhan** [sequelize/sequelize#5437]
Hi Guys,

So i'm running into some trouble here,
sequelize@3.19.2
node@5.6.0
npm@3.6.0
MariaDB@5.5.47

I have a hook in a data model , after saving the data it is supposed to parse that data and do stuff,
It has an association for a parser and therefore has a foreign key inside it called `extractorId`
An association is built like `Data.belongsTo(models.Extractor)`

I am able to use `Data.getExtractor()` easily Except in the afterCreate Hook.
In the afterCreate Hook it returns a null instance and even the query output goes something like
`select x, y, z from Extractor as Extractor where Extractor.id = NULL`   <== the null part here

```javascript
hooks: {
		afterCreate: function(instance, options) {
			instance.getExtractor();  //<== this returns null in the then callback
                       // and instance.extractorId is not null it wouldn't have saved
                       // because its a foreign key
		}
	}
```

However, If I do something like this (which somehow sounds absurd to me), it works flawless;

```javascript
hooks: {
		afterCreate: function(instance, options) {
			Data.findById(instance.id)    
                       /*Data here is the self class
                       * so in other words finding the same instance again
                       *returns the complete model with associations*/
                              .then(function(_actualInstance){
                                       _actualInstance.getExtractor()  /// works as expected
                              });
		}
	}
```

**Comment by mickhansen** [comment]
Is your create running in a transaction?

(Closing since question, not feature request / bug)

**Comment by Aukhan** [comment]
Hi @mickhansen ,
Thanks for replying, really appreciate your help !

No Sir, my create is not running in a transaction.
I'm gonna change the behaviour to make it run in a transaction and report back.

**Comment by mickhansen** [comment]
Don't do that, since then it'll definitely fail.
Your exisitng code should really just work

**Comment by Aukhan** [comment]
oops :|
sorry ... thought that was the issue with my code.

I'm gonna try to create a more detailed reproducible script and share that.

**Comment by Aukhan** [comment]
ok guys, I've recreated and tested this outside of my current setup and like @mickhansen said the code should've worked as it is.
So there's a catch inside the project that i'm having this issue in. Need to debug that.

@mickhansen thanks for your time man ! and sorry to bother you !
