### ISSUE TITLE
Multiple associations of the same Model

### ISSUE THREAD

**Issue by gu-stav** [sequelize/sequelize#544]
Is it possible (and how) to have multiple associations of the same model? The following gives me `getImages()` but not `getTeaserImage()`. Is there anything to do in the back-reference?

``` js
Gallery.hasMany( Image )
       .hasOne( Image, {as: 'TeaserImage'} );

Image.hasMany( Gallery );
```

**Comment by TechnicalRhino** [comment]
@janmeier Wont that create a cyclic reference?
