### ISSUE TITLE
Connection with pool never closes

### ISSUE THREAD

**Issue by jirehstudios** [sequelize/sequelize#5441]
I am using AWS Lambda and API Gateway together to build a REST API for the web application at my job. I noticed that the connections to the MySQL server never get closed, or am I wrong based on the info below?

**Code**

```javascript
    var Sequelize = require('sequelize'),
        seqlz = new Sequelize('database', 'username', 'password', {
            host: 'mydbdomain.com',
            port: '3306',
            dialect: 'mysql',
            timezone: 'UTC-05:00',
            pool: {
                max: 1,
                min: 0,
                idle: 5000
            }
        }),
        Promotion = seqlz.define('promotion', {
            tournamentId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            iconFilePath: Sequelize.STRING,
            name: Sequelize.STRING(75),
            eventStartDate: Sequelize.DATE,
            eventEndDate: Sequelize.DATE
        }, {
            timestamps: false,
            tableName: 'Tournament'
        }),
        Advertiser = seqlz.define('advertiser', {
            advertiserId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            name: Sequelize.STRING(75),
        }, {
            timestamps: false,
            tableName: 'Advertiser'
        }),
        Game = seqlz.define('game', {
            gameId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            name: Sequelize.STRING(75)
        }, {
            timestamps: false,
            tableName: 'Game'
        }),
        GamePlayLog = seqlz.define('gamePlayLog', {
            gamePlayLogId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            createdDate: Sequelize.DATE
        }, {
            timestamps: false,
            tableName: 'GamePlayLog'
        });
    
    Promotion.belongsTo(Advertiser, {foreignKey: 'advertiserId'});
    Promotion.belongsTo(Game, {foreignKey: 'gameId'});
    Promotion.hasMany(GamePlayLog, {foreignKey: 'tournamentId'});
    
    exports.handler = function(event, context) {
        Promotion.findAll({
            attributes: [
                'tournamentId',
                'name',
                'eventStartDate',
                'eventEndDate'
            ],
            where: {status: 3},
            include: [
                {
                    model: Advertiser,
                    attributes: ['name']
                },
                {
                    model: Game,
                    attributes: ['name']
                },
                {
                    model: GamePlayLog,
                    attributes: ['createdDate']
                }
            ]
        }).then(function(promos) {
            context.done(null, promos);
        });
    };
```

I'd assume the connection would automatically close after 5 seconds of no use, but it's not not unless I'm misinterpreting what I'm seeing on MySQL Workbench. I tried using `sequelize.close()` before `context.done()` (with and w/o the pool) but would get an error at random times: `Unhandled rejection Error: ConnectionManager.getConnection was called after the connection manager was closed!`

Here's an image of my MySQL Workbench. At the time of this screenshot, the connections had been hanging for over 500 seconds if I'm not mistaken. Way more than 5 seconds lol. They are the ones that begin with `ec2`.

http://oi67.tinypic.com/314qkqe.jpg

Any help is appreciated!

**Comment by mickhansen** [comment]
Please make an effort to format code.
The pool should close the connection after 5 seconds of idle.
Are you using new Sequelize inside each lambda file or are you using a shared file? I know that the "globals" in lambda can be reused so maybe you're not actually using a new instance each time.

**Comment by jirehstudios** [comment]
@mickhansen I am using `new Sequelize` inside each Lambda file, yes. The sample code above is for one single Lambda function tied to an endpoint on API Gateway.

**Comment by mickhansen** [comment]
But where in the lambda file? In the global context? Then it might possible be reused by multiple parallel calls.

**Comment by mickhansen** [comment]
Closing since most likely not a Sequelize issue unless a SSCCE for a non-lambda environment can be produced.

**Comment by jirehstudios** [comment]
@mickhansen The code above is inside a file called `getActivePromotions.js'. This file is zipped together with all the folders of the npm packages, so I end up with soemthing like this:

```
getActivePromotions.zip
  - getActivePromotions.js
  - module-name
  -- ...
  - module2-name
  -- ...
```

I then upload `getActivePromotions.zip` to the AWS Lambda. I'm get those connection hangs from running (test) the same Lambda function a few times.

**Comment by mickhansen** [comment]
Threatening to move to another ORM because you're unwilling to isolate the error to Sequelize isn't really helpfull to solving it.

Like i mentioned a few times Lambda will reuse the context, have you ruled out that this is the issue?
Please test whether it also hangs when using it outside of Lambda.

**Comment by mickhansen** [comment]
You need to be more specific about "never closes", i'm pretty sure no mysql servers leaves connections up forever unless they have activity.

Some server configurations also keep around connections for a bit.
The reason you're seeing issues with `sequelize.close` is likely because of the Lambda global sharing.

**Comment by jirehstudios** [comment]
@mickhansen I am not threatening anything, I am simply in need of an ORM to get this working and I'd rather not move away from Sequelize so any help would be great. I would need to move to another ORM if I can't get this wokring because that's the obvious thing to do, no threats here. Is it too much to ask?

**Comment by jirehstudios** [comment]
I will try to investigate the context issue you mentioned and come back with what I find.

**Comment by jirehstudios** [comment]
@mickhansen Thanks for your patience, it turns out that putting everything inside the `exports.handler` function did the trick. BUT, using `pool`, the connection still never closed after man yseconds. I AM able to now close the connection manually without getting the previous error.

```javascript
exports.handler = function(event, context) {
    var Sequelize = require('sequelize'),
        seqlz = seqlz || new Sequelize('db', 'user', 'pw', {
                host: 'mydbdomain.com',
                port: '3306',
                dialect: 'mysql',
                timezone: 'UTC-05:00'
            }),
        Promotion = seqlz.define('promotion', {
            tournamentId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            iconFilePath: Sequelize.STRING,
            name: Sequelize.STRING(75),
            eventStartDate: Sequelize.DATE,
            eventEndDate: Sequelize.DATE
        }, {
            timestamps: false,
            tableName: 'Tournament'
        }),
        Advertiser = seqlz.define('advertiser', {
            advertiserId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            name: Sequelize.STRING(75),
        }, {
            timestamps: false,
            tableName: 'Advertiser'
        }),
        Game = seqlz.define('game', {
            gameId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            name: Sequelize.STRING(75)
        }, {
            timestamps: false,
            tableName: 'Game'
        }),
        GamePlayLog = seqlz.define('gamePlayLog', {
            gamePlayLogId: {
                type: Sequelize.BIGINT(20),
                primaryKey: true
            },
            createdDate: Sequelize.DATE
        }, {
            timestamps: false,
            tableName: 'GamePlayLog'
        });

    Promotion.belongsTo(Advertiser, {foreignKey: 'advertiserId'});
    Promotion.belongsTo(Game, {foreignKey: 'gameId'});
    Promotion.hasMany(GamePlayLog, {foreignKey: 'tournamentId'});

    Promotion.findAll({
        attributes: [
            'tournamentId',
            'name',
            'eventStartDate',
            'eventEndDate'
        ],
        where: {status: 3},
        include: [
            {
                model: Advertiser,
                attributes: ['name']
            },
            {
                model: Game,
                attributes: ['name']
            },
            {
                model: GamePlayLog,
                attributes: ['createdDate']
            }
        ]
    }).then(function(promos) {
        seqlz.close();
        context.done(null, promos);
    });
};
```

**Comment by mickhansen** [comment]
The default pool idle is 5000ms, you can try tweaking that to 1000ms.
I would possible consider using a pool in the lambda context and have that be max 5 connections.
Right now your connection count will equal your concurrency count, that is probably not ideal.

**Comment by halt-hammerzeit** [comment]
@mickhansen 
> Like i mentioned a few times Lambda will reuse the context

Thx, that was the case of closing the connection in `finally` with `sequelize.close()`.
Using `context.callbackWaitsForEmptyEventLoop = false` instead.

**Comment by halt-hammerzeit** [comment]
> by multiple parallel calls.

Not parallel, but consequetive
https://aws.amazon.com/ru/blogs/compute/container-reuse-in-lambda/

**Comment by marcogrcr** [comment]
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.

**Comment by catamphetamine** [comment]
^^^ The guy looks credible

**Comment by catamphetamine** [comment]
> Dec 21, 2016

Used to be still young...
Almost 3 years passed.
Ah.
