### ISSUE TITLE
Property sets in beforeValidate hook don't get persisted when updating row

### ISSUE THREAD

**Issue by guisehn** [sequelize/sequelize#5449]
On 3.19.3 with node.js 5.1.0 and Postgres (didn't test with other dialects), when I set some property inside the `beforeValidate` hook when updating a model, some changes set inside the hook don't get persisted.

Model definition:
```js
var User = sequelize.define('User', {
  name: { type: Sequelize.STRING, allowNull: false },
  firstName: { type: Sequelize.STRING, allowNull: false },
  lastName: { type: Sequelize.STRING, allowNull: false }
});
```

Hook definition:
```js
// This will trim user.name and update user.firstName and user.lastName
// based on user.name
User.hook('beforeValidate', function(user, options) {
  if (user.changed('name')) {
    user.set('name', user.name.trim());

    var parts = user.name.split(' ');
    user.set('firstName', parts[0]);
    user.set('lastName', parts.length > 1 ? parts.pop() : '');
  }
});
```

Failing test:
```js
sequelize.sync({ force: true }).then(function() {
  return User.create({
    name: ' First Middle Last '
  })
  .then(function(user) {
    return User.findById(user.id); // 1st reload - make sure we are retrieving the data stored in DB
  })
  .then(function(user) {
    assert.equal(user.name, 'First Middle Last'); // passes
    assert.equal(user.firstName, 'First'); // passes
    assert.equal(user.lastName, 'Last'); // passes

    return user;
  })
  .then(function(user) {
    return user.update({ name: ' NewFirst Middle1 Middle2 Middle3 NewLast  ' });
  })
  .then(function(user) {
    return User.findById(user.id); // 2nd reload - make sure we are retrieving the data stored in DB
  })
  .then(function(user) {
    assert.equal(user.name, 'NewFirst Middle1 Middle2 Middle3 NewLast'); // passes
    assert.equal(user.firstName, 'NewFirst'); // rejects (user.firstName is still "First")
    assert.equal(user.lastName, 'NewLast'); // rejects (user.lastName is still "Last")
  });
});
```

Query log:
```
Executing (default): INSERT INTO "Users" ("id","name","firstName","lastName","createdAt","updatedAt") VALUES (DEFAULT,'First Middle Last','First','Last','2016-02-18 12:24:02.898 +00:00','2016-02-18 12:24:02.898 +00:00') RETURNING *;

Executing (default): SELECT "id", "name", "firstName", "lastName", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."id" = 1;

Executing (default): UPDATE "Users" SET "name"='NewFirst Middle1 Middle2 Middle3 NewLast',"updatedAt"='2016-02-18 12:24:02.921 +00:00' WHERE "id" = 1 -- only "name" got updated

Executing (default): SELECT "id", "name", "firstName", "lastName", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."id" = 1;
```

Some considerations:
- The `firstName` and `lastName` properties are not persisted only on update (it works with create), but `name` persisted on both;
- If I didn't run the 2nd reload (the line indicated in a comment on the failing test), the test would pass, which means that the model instance on JavaScript would have its values updated, but those changes wouldn't get persisted to the DB server;
- This problem doesn't happen if I had used the hooks `beforeCreate` + `beforeUpdate`;
- This issue also happens if I run the same function under the `afterValidate` hook.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/4837

**Comment by MJB-Khorasani** [comment]
I have the same problem. i saw this problem when node.js was version 6 and now node.js version is 12. why is it still a bug.

[this is from doc](https://sequelize.org/master/manual/hooks.html):
> Arguments to hooks are passed by reference. This means, that you can change the values, and this will be reflected in the insert / update statement. A hook may contain async actions - in this case the hook function should return a promise.

so what can i do? or what we should do?
