### ISSUE TITLE
Possible regression in 3.19.3: updatedAt getting overridden?

### ISSUE THREAD

**Issue by jasonku** [sequelize/sequelize#5450]
Hi,

After updating sequelize to 3.19.3, one of our unit tests started failing:

```javascript
        it('should always bump the updatedAt of the model, even if no changes', function(done) {
            jasmine.clock().mockDate(new Date('12/31/2019'));

            var originalUpdatedAt;
            return models.Policy.findById(policyFixture1.data.id)
                .then(function (policy) {
                    originalUpdatedAt = policy.updatedAt;
                    return policy.update({description: policy.description});
                })
                .then(function (policy) {
                    expect(policy.updatedAt.getTime()).toBeGreaterThan(originalUpdatedAt.getTime());
                })
                .then(done)
                .catch(done.fail);
        });
```

It seems like `updatedAt` is getting overridden somewhere, and looking at the 3.19.3 changelog it looks like it might be related to https://github.com/sequelize/sequelize/pull/5367 . What's the expected way to make `updatedAt` always get touched upon a call to `update`, even if no fields have changed?

@rafis

**Comment by mickhansen** [comment]
Sequelize should no-op by default when nothing is changed, that should not have changed in that PR as far as i could tell.

**Comment by janmeier** [comment]
Yep, save with nothing changed has been a no-op since 3.5, see https://github.com/sequelize/sequelize/commit/8df98ded5c3bbd4f62a37a7fd5ed2c8c6a450b9e

To force an update you can do `policy.changed('updatedAt', true);`

**Comment by holm** [comment]
I'm seeing the same issue after updating from 3.19.2 to 3.19.3. Doing `entity.changed('updatedAt', true);` no longer causes `updatedAt` to be set on an entity.update() without any changes.

**Comment by janmeier** [comment]
`update` only saves the passed values, see http://docs.sequelizejs.com/en/latest/api/instance/#updateupdates-options-promisethis. Use `save` to force an update
