### ISSUE TITLE
Table doesn't exist " ER_NO_SUCH_TABLE:" while showing on mysql

### ISSUE THREAD

**Issue by phoenixcod** [sequelize/sequelize#5451]
sequelize wont recognize a specific table (region) check error log. I checked if table existed after each nodemon reload through mysql command line. it would show everytime. I am at a loss.

```
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | int(11)      | NO   | PRI | NULL    | auto_increment |
| name       | varchar(255) | YES  |     | NULL    |                |
| created_by | int(11)      | YES  |     | NULL    |                |
| updated_by | int(11)      | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
4 rows in set (0.07 sec)
```

**sequelize sync code**

```
sequelize.query('SET FOREIGN_KEY_CHECKS = 0').then(function() {
    sequelize
        .sync({
            force: true,logging: console.log
        }).then(function() {
            sequelize.query('SET FOREIGN_KEY_CHECKS = 1').then(function() {
                console.log('Database synchronised.');
            });
        }).error(function(err) {
            console.log(err);
        });;
}).error(function(ee) {
    console.log(err);
});
```

**models with errors**

**hospital**
```
var Hospital = sequelize.define("Hospital", {
		
		name: DataTypes.STRING,
		mak_code: DataTypes.STRING,
		type: {
			type: DataTypes.INTEGER,
			foreignKey: true,
			allowNull: false
		},
		region: DataTypes.STRING,
		regional_group: DataTypes.STRING,
		address: DataTypes.INTEGER,
		licensed_tm_lab: DataTypes.BOOLEAN,
		lis: DataTypes.INTEGER, 
		created_by: DataTypes.INTEGER,
		updated_by: DataTypes.INTEGER
	}, {

		classMethods: {
			associate: function(models) {

				Hospital.hasMany(models.Issue,{foreignKey: {fieldName:'hospital_id'}});
				Hospital.belongsToMany(models.Contact, { through: 'hospitals_contacts',foreignKey: {fieldName:'hospital_id'}});
				Hospital.belongsTo(models.Address, {foreignKey: {fieldName:'address'}});
				Hospital.belongsTo(models.Type, {foreignKey: {fieldName:'type'}});
				Hospital.belongsTo(models.Lis, {foreignKey: {fieldName:'lis'}});
				Hospital.belongsTo(models.Region, {foreignKey: {fieldName:'region'}});
				Hospital.belongsTo(models.RegionalGroup, {foreignKey: {fieldName:'regional_group'}});
			}
		},
		tableName: 'hospitals',
		createdAt: false,
		updatedAt: false
	});

	return Hospital;
```

**Region**
```	var Region = sequelize.define("Region", {

		name: DataTypes.STRING,
		created_by: DataTypes.INTEGER,
		updated_by: DataTypes.INTEGER
	}, {
		tableName: 'regions',
		createdAt: false,
		updatedAt: false
	}, {

	classMethods: {
			associate: function(models) {
					
				Region.hasMany(models.Hospital, { foreignKey:{fieldName:region_id} });
			}
		}
	});	

	return Region; ```


**error log**

```
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
Executing (default): SELECT 1+1 AS result
Executing (default): SET FOREIGN_KEY_CHECKS = 0
Connection has been established successfully.
Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): DROP TABLE IF EXISTS `issues`;
Executing (default): DROP TABLE IF EXISTS `hospitals_contacts`;
Executing (default): DROP TABLE IF EXISTS `hospitals`;
Executing (default): DROP TABLE IF EXISTS `lis`;
Executing (default): DROP TABLE IF EXISTS `regional_groups`;
Executing (default): DROP TABLE IF EXISTS `contacts_committees`;
Executing (default): DROP TABLE IF EXISTS `contacts`;
Executing (default): DROP TABLE IF EXISTS `regions`;
Executing (default): DROP TABLE IF EXISTS `types`;
Unhandled rejection SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'orbcon.regions' doesn't exist
    at Query.formatError (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\sequelize\lib\dialects\mysql\query.js:174:14)
    at Query._callback (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query.ErrorPacket (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\Parser.js:73:12)
    at Protocol.write (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Executing (default): DROP TABLE IF EXISTS `communication_methods`;
Executing (default): DROP TABLE IF EXISTS `Committees`;
Executing (default): DROP TABLE IF EXISTS `addresses`;
Executing (default): DROP TABLE IF EXISTS `addresses`;
Executing (default): CREATE TABLE IF NOT EXISTS `addresses` (`id` INTEGER NOT NULL auto_increment , `address_line1` VARCHAR(255), `address_line2` VARCHAR(255), `postal_code` VARCHAR(255), `city` VARCHAR(255), `province` VARCHAR(255), `country` VARCHAR(255), `created_by` INTEGER, `updated_by` INTEGER, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `addresses`
Executing (default): DROP TABLE IF EXISTS `Committees`;
Executing (default): CREATE TABLE IF NOT EXISTS `Committees` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `created_by` INTEGER, `updated_by` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Committees`
Executing (default): DROP TABLE IF EXISTS `communication_methods`;
Executing (default): CREATE TABLE IF NOT EXISTS `communication_methods` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `created_by` INTEGER, `updated_by` INTEGER, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `communication_methods`
Executing (default): DROP TABLE IF EXISTS `types`;
Executing (default): CREATE TABLE IF NOT EXISTS `types` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `created_by` INTEGER, `updated_by` INTEGER, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `types`
Executing (default): DROP TABLE IF EXISTS `regions`;
Executing (default): CREATE TABLE IF NOT EXISTS `regions` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `created_by` INTEGER, `updated_by` INTEGER, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `regions`
Executing (default): DROP TABLE IF EXISTS `contacts`;
Executing (default): CREATE TABLE IF NOT EXISTS `contacts` (`id` INTEGER NOT NULL auto_increment , `first_name` VARCHAR(255), `last_name` VARCHAR(255), `type` INTEGER, `job_title` VARCHAR(255), `primary_email` VARCHAR(255), `business_number` VARCHAR(255), `created_by` INTEGER, `updated_by` INTEGER, `TypeId` INTEGER, `RegionId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`TypeId`) REFERENCES `types` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`RegionId`) REFERENCES `regions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `contacts`
Executing (default): DROP TABLE IF EXISTS `contacts_committees`;
Executing (default): CREATE TABLE IF NOT EXISTS `contacts_committees` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `ContactId` INTEGER , `CommitteeId` INTEGER , PRIMARY KEY (`ContactId`, `CommitteeId`), FOREIGN KEY (`ContactId`) REFERENCES `contacts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`CommitteeId`) REFERENCES `Committees` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `contacts_committees`
Executing (default): DROP TABLE IF EXISTS `regional_groups`;
Executing (default): CREATE TABLE IF NOT EXISTS `regional_groups` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `region_id` INTEGER, `created_by` INTEGER, `updated_by` INTEGER, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `regional_groups`
Executing (default): DROP TABLE IF EXISTS `lis`;
Executing (default): CREATE TABLE IF NOT EXISTS `lis` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `created_by` INTEGER, `updated_by` INTEGER, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `lis`
Executing (default): DROP TABLE IF EXISTS `hospitals`;
Executing (default): CREATE TABLE IF NOT EXISTS `hospitals` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `mak_code` VARCHAR(255), `type` INTEGER NOT NULL, `region` VARCHAR(255), `regional_group` VARCHAR(255), `address` INTEGER, `licensed_tm_lab` TINYINT(1), `lis` INTEGER, `created_by` INTEGER, `updated_by` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`type`) REFERENCES `types` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`region`) REFERENCES `regions` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`regional_group`) REFERENCES `regional_groups` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`address`) REFERENCES `addresses` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`lis`) REFERENCES `lis` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
Unhandled rejection SequelizeDatabaseError: ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
    at Query.formatError (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\sequelize\lib\dialects\mysql\query.js:174:14)
    at Query._callback (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query.ErrorPacket (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\Parser.js:73:12)
    at Protocol.write (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Ragy\Documents\projects\ORBCN_App\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by mickhansen** [comment]
DROP IF EXISTS should not ever throw on a table not existing, that's the entire point.

**Comment by phoenixcod** [comment]
@mickhansen At runtime the table does exist. I think that error is what triggers the error in the other model (hospital). Maybe the defined associations are not done right so models are read in the wrong sequence? im not sure.

**Comment by mickhansen** [comment]
You can log `err.sql` to figure out what SQL query triggered the error specifically.
Might help us debug your issue here.

**Comment by phoenixcod** [comment]
can you please provide an example to using that log? I tried using `err.sql` but it didnt log sql that triggers errors only the error handler as visible above. Sorry for the inconvenience, I couldnt find it in docs.

**Comment by mickhansen** [comment]
Well the rejection is currently unhandled so you have to figure out how to handle it first, then you can inspect err.sql
