### ISSUE TITLE
$or: [] (empty array) should degenerate to an empty result set.

### ISSUE THREAD

**Issue by brendonboshell** [sequelize/sequelize#5453]
I believe the current behaviour of having an empty $or condition is unexpected. If findAll is being called with { where: { $or: [] } }, I would expect an empty result set. Instead, the query runs without any WHERE condition, fetching all results.

[The union of sets in the empty set is the empty set](http://math.stackexchange.com/questions/370188/empty-intersection-and-empty-union), hence this query should return no data. Intuitively, every item added to the $or array should increase the scope of the query. Hence, an empty $or array should be an empty result set.

This has the potential to cause some nasty degenerate behaviour in some applications. For example, in one part of my application, I do the following:

    userDetailTable.findAll({
      where: {
        $or: _.map(userDetails, function (ud) {
          return {
            userId: ud.userId,
            version: ud.version
          };
        })
      }
    });

The intention of this query is to always filter by userId, which ultimately determines what records a session is allowed to view. In the case that userDetails is empty, however, the query degenerates and returns all records, a potential security issue.

Consider the following:

```
var user = sequelize.define('user', {
  id: {
    type: Sequelize.INTEGER(10),
    allowNull: false,
    primaryKey: true,
    autoIncrement: true
  }
}, {
  timestamps: false,
  tableName: 'user',
  freezeTableName: true
});

user.findAll({
  where: {
    $or: [{
      id: 5
    }]
  }
});
```

This produces the SQL:

    SELECT `id` FROM `user` AS `user` WHERE (`user`.`id` = 5);

However, if we run:

```
user.findAll({
  where: {
    $or: []
  }
});
```

it runs the following SQL:

    SELECT `id` FROM `user` AS `user`;

**Comment by janmeier** [comment]
I agree, it is a dangerous default

**Comment by brendonboshell** [comment]
I have updated the pull request to also deal with the cases $not: [], $or: {} and $not: {} which I believe should also return no data.

**Comment by aides** [comment]
Guys, I've just encountered a problem with this particular issue and here are my thoughts:
1. When I started using $or my assumption was that empty array there would result in empty where (how things worked before) and that worked good for me.
2. I do not completely understand what is the danger with this approach, one should just account for this behavior. Empty $or means *no constraints*, thus full result set should be returned. I think current behavior is quite counter-intuitive, as when where is empty you just do not expect something will add WHERE 0 = 1 to the query.
3. Even fix might be argued to be ok, but it is kind of a breaking change in 3.20 (assuming I was on 3.19.3) and I even do not see this fix in the changelog.
4. As for original use case I think the author should not call findAll at all if userDetails are empty. 

I assume I might be wrong here, but this point made me a little bit upset.

**Comment by mickhansen** [comment]
@aides I can agree with you on certain points, however an ORM should in my opinion be default safe. unintended empty statements from bad dynamic handling should not result in a default unsafe leak.

But there will undoubtebly be people in boths camps for this issue :)
The easiest fix for you is to supply a global beforeFind hook that removes empty $or statements.

**Comment by brendonboshell** [comment]
@aides Empty $or does not mean "no constraints". Consider the query "(id = 1) OR (id = 2)". It will return two records. Now remove a clause, you have "(id = 1)". It will return one record. What should you return if you remove this last clause? If you need more convincing, run the following SQL on your database (the IN statement is logically equivalent to a series of OR statements):

`SELECT * FROM user WHERE id IN (SELECT id FROM user WHERE FALSE);`

The inner select query returns the empty set. If your logic was true, then this entire query should return all users in the user table. Instead, it returns no data, which is what I would expect.

That said, I know from the [mongodb documentation](https://docs.mongodb.org/manual/reference/operator/query/or/) (which has a similar query format), they have the restriction that you have an "array of two or more expressions". I guess this could be a middle ground to prevent confusion, although it wouldn't be my preferred approach personally.

**Comment by aides** [comment]
@mickhansen @brendonboshell Thanks for your answers. I think I see your points more clear now and that makes me think that "empty $or means no constraints" might not be as evident as I thought :) I was also trying to find an example of a different ORM to find out how they behave in similar cases, but haven't found anything yet. Thanks for Mongo example, though!

Just for understanding of my perspective I will provide my use case. It is a search where a query string is searched in multiple textual columns via ILIKE expression. So when I have no query, I have no columns to add to $or list, so I expect all results to be returned. As well as for original case there is a simple workaround that I do not need to add $or if no there is no query string.
