### ISSUE TITLE
belongsTo relationship with two-column foreign key.

### ISSUE THREAD

**Issue by jamespedid** [sequelize/sequelize#5455]
I have a table A with a composite primary key (X, Y), and I have a table B that has a one-to-one relationship with table A, with the following association: A.X = B.X and A.Y = B.Y. It seems that I can only specify one column per foreign key. Is there a way I can use two columns for a foreign key?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/311
