### ISSUE TITLE
Sequelize returning different values than the raw query

### ISSUE THREAD

**Issue by jeffprandall** [sequelize/sequelize#5459]
When I run this function

```
function getOpenTxCalls(date) {
 return sequelize.query(
 'SELECT \
  CT.center_name, \
  COUNT(CASE WHEN CL.disposition_type IN(3, 4, 22, 23,25, 42) AND CL."createdAt"::date = :date THEN CL.disposition_type END) AS "CallsMadeToday", \
  COUNT(CASE WHEN CL.disposition_type = 3 AND CL."createdAt"::date = :date THEN CL.disposition_type END) AS "AppointmentsMadeToday" \
FROM "Centers" AS CT \
 LEFT JOIN "Users" AS US ON US."centerId" = CT.id \
 LEFT JOIN "CallLogs" AS CL ON CL."createdBy" = US."id"  \
WHERE US."centerId" NOT IN(11, 13)\
GROUP BY CT.center_name \
ORDER BY CT.center_name',
{ replacements:
  {
    date: date
  },
  type: sequelize.QueryTypes.SELECT })
.then(function(openTXCalls) {
  console.log(openTXCalls);
  return openTXCalls;
})
.catch(console.log.bind(console));
}
```

It's returning incorrect counts of data.

I watched the CLI as I ran the function and copy and pasted the SQL query in CLI into PG3 Admin and received different (correct) values. Here is what was in the CLI.

```
Executing (default): SELECT     
CT.center_name,     
COUNT(CASE WHEN    CL.disposition_type IN(3, 4, 22, 23,25, 42) AND CL."createdAt"::date = '2016-02-17' THEN CL.disposition_type END) AS "CallsMadeToday",     
COUNT(CASE WHEN CL.disposition_type = 3 AND CL."createdAt"::date = '2016-02-17' THEN CL.disposition_type END) AS "AppointmentsMadeToday"   
FROM "Centers" AS CT     
LEFT JOIN "Users" AS US ON US."centerId" = CT.id     
LEFT JOIN "CallLogs" AS CL ON CL."createdBy" = US."id"    
WHERE US."centerId" NOT IN(11, 13)  
GROUP BY CT.center_name   
ORDER BY CT.center_name
```

I am querying the same local Postgres database on my machine. Any thoughts on what could be causing this?

**Comment by janmeier** [comment]
Could be related to timezone difference - sequelize will set the connection timezone to UTC, which could change the results of you date filter. What's the default timezone for your server?

**Comment by jeffprandall** [comment]
It should be set to HST - Hawaiian standard time.  We have people in Hawaii and the Philippines entering in records.  Is there a Sequelize settings that will store all records as HST?

**Comment by janmeier** [comment]
Use the `timezone` option http://docs.sequelizejs.com/en/latest/api/sequelize/#new-sequelizedatabase-usernamenull-passwordnull-options. It supports both offset and named timezones

**Comment by jeffprandall** [comment]
I edited my config file as such
`"development": {
    "username": "xxxx",
    "password": "yyyyy",
    "database": "database_dev",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "timezone": "-10:00"
  },`

Then I went in created a new record and the timestamp was still PST (-08:00).  Is that timezone setting I need to do on each model?

**Comment by jeffprandall** [comment]
So I double checked my server's timezone, it is set to HST.  And when I PG3 Admin and look at all the records their timestamps reflect -10 as the timezone.  The above comment might have been my bad since my dev machine is PST but you would think the Sequelize config file would override that??

**Comment by janmeier** [comment]
The date will be stored with the timezone you specify in the database, but it will always be shown in your local timezone by sequelize - that's how Date works in javascript

**Comment by jeffprandall** [comment]
Who's local timezone?  The server or the clients web browser?

**Comment by janmeier** [comment]
The timezone of the server - when console.log a date on the server, it wil always be shown in the timezone of the server
