### ISSUE TITLE
Large amount of tables and though table with hasmany association

### ISSUE THREAD

**Issue by exotfboy** [sequelize/sequelize#5464]
I am working on a new web application where I need the orm,and I found `sequelize`, however after I read almost all the docs, I am not sure if `sequelize` is the best choice, so I tried to post it here to get some suggestion.

Here are the main models in the application,

![image](https://cloud.githubusercontent.com/assets/16457917/13201566/22847f08-d8b2-11e5-811b-e0d992669f0c.png)

As shown, there are 4 kinds of models:

1 Department

This is a tree-like structure, and I need to display this tree in the client, the user with super_admin role can manage the departments(crud).

2 User

Each user belongs to a certain department.

3 Attachment

Save the image, pdf  or docx.

4 Record

There are almost 200+ different types of `Record` like `Record-1` and `Record-2`. Every record must belongs to a certain `Department`, and have one `User` as creator, and one record can have multiple attachments.

Also a user can manage the records belongs to his department(include the sub department).

At the first glance, I tried to use this kind of schema:
```
var Department  = this.sequelize.define('department', {/* attributes */});
var User = this.sequelize.define('user', {/* attributes */})

User.belongsTo(Department); 

var Attachment  = this.sequelize.define('attachment', {/* attributes */});

var RecordA = this.sequelize.define('record_a', {/* attributes */});
RecordA.belongsTo(Department)
RecordA.belongsTo(User)

RecordA.hasMany(Attachment, {
  foreignKey: 'attachmentable_id',
  constraints: false,
  scope: {
    attachmentable: 'record_a'
  }
});
Attachment.belongsTo(RecordA, {
  foreignKey: 'attachmentable_id',
  constraints: false,
  as: 'record_a'
});

var RecordB = this.sequelize.define('record_b', {/* attributes */});
RecordB.belongsTo(Department)
RecordB.belongsTo(User)

RecordB.hasMany(Attachment, {
  foreignKey: 'attachmentable_id',
  constraints: false,
  scope: {
    attachmentable: 'record_b'
  }
});
Attachment.belongsTo(RecordB, {
  foreignKey: 'attachmentable_id',
  constraints: false,
  as: 'record_b'
});
```

While I still have some problems:

1 Too many records

There are so many different types of records, it would be a hard job to create the schemas one by one, also it will be hard to maintenance, for example each record will add or remove some common fileds, I will have to change too many places.

Also I need to make statistics for the records by different department, it will be complex if save in several tables.

Or if schemaless is a good alternative? I have thought this, but I need the validation in both the client and the server. :(

2 Attachment

In the above schema, the `Attachment` will have a `attachmentable_id` in the table, while I think an attachment should be a pure model, it should know nothing about who refer to it. So I wonder if it is possible to create the through table for the `hasMany` association?

3 Update for the `attachmentable` model

Generally when I save an attachmentable model, I have save the attachments first, and get the attachment ids. Then I will send the attachment ids when save the model, for example I may save a `RecordA` like this;

```
var record=gatherFromFrom();
// record = {name:..... attachments:[{id:1},{id:2}]};
```

Then on the server side when I call:

`RecordA.create(record);`

It would not create the relation. I may use this:

```
Attachment.findAll({where:{$in:{id:[1,2]}}},function(err,attachments){
	record.setAttachments(attachments):
	RecordA.create(record);
});

```
Is there a better idea?

What's more, when I tried to update a record whose attachments have been changed:

```
var record=gatherFromFrom();
// record = {name:..... attachments:[{id:1}]}; // the attachment with id 2 should be removed
```

Then on the server side how can I update the record and delete the removed attachment?

**Comment by janmeier** [comment]
1. Not really any good solution for this - perhaps table inheritance, https://github.com/sequelize/sequelize/issues/1243, but its not on the roadmap
2. You can use `belongsToMany` (n:m) to create the join table and then just use it as a 1:m
3. dfsd
  1. You can use nested creation to create both in one go http://docs.sequelizejs.com/en/latest/docs/associations/#creating-with-associations
  2. `setAttachments([1])` will remove 2.

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
