### ISSUE TITLE
Bulk Creating does not return each object's ID

### ISSUE THREAD

**Issue by HopefulLlama** [sequelize/sequelize#5466]
Example: User Accounts where the ID is autoincremented

    Account.bulkCreate([

        email: "example@email.com", type: "standard",

        email: "rick@astley.com", type: "legend"

    ]).then(function(accounts) {

        console.log(accounts[0].id); // prints null

        console.log(accounts[1].id); // prints null

    });

Checking the database shows that the IDs have been generated successfully.

**Comment by janmeier** [comment]
It is not possible to get all auto-generated values without doing an additional select in mysql and pg. In postgres you can use `returning: true ` http://docs.sequelizejs.com/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance

**Comment by HusseinOsman** [comment]
try this:

Account.bulkCreate([

    email: "example@email.com", type: "standard",

    email: "rick@astley.com", type: "legend"

],{individualHooks: true}).then(function(accounts) {

    console.log(accounts[0].id); // prints null

    console.log(accounts[1].id); // prints null

});

**Comment by SalathielGenese** [comment]
https://stackoverflow.com/a/35081421/3748178

**Comment by information-security** [comment]
> It is not possible to get all auto-generated values without doing an additional select in mysql and pg. In postgres you can use `returning: true` http://docs.sequelizejs.com/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance

I am able to get auto-generated IDs after a `bulkCreate` in `mysql` database. Considering that the docs clearly state that this is not supported for `mysql`, can somebody please clarify what's going on? Maybe there has been an update on this but the docs are not updated? Or is `bulkCreate` auto selecting the rows after insertion?
