### ISSUE TITLE
Where in many to many relationship

### ISSUE THREAD

**Issue by iblazevic** [sequelize/sequelize#5473]
Hi,

we are having some issues with executing a list query in a many to many relationship. In our case its a standard relationship (sites and groups with groupsites mapping table). Basically we are trying to list all of the sites that belong to a certain group. Now here is the code I'm trying with the assumption that it should work.

```
Site.findAll({
  include: [
    {
      model: Group,
      where: {id: 1 },
      attributes: ['id']
    }
  ],
  raw: true,
  limit: 5,
  offset: 0,
  order: [['name', 'ASC']]
});
```

That generates a following query:

```
SELECT "site".*,
       "groups"."id" AS "groups.id",
       "groups.groupsites"."siteId" AS "groups.groupsites.siteId",
       "groups.groupsites"."groupId" AS "groups.groupsites.groupId"
FROM
  (SELECT *
   FROM "sites" AS "site"
   WHERE
       (SELECT "groupsites"."siteId"
        FROM "groupsites" AS "groupsites"
        INNER JOIN "groups" AS "group" ON "groupsites"."groupId" = "group"."id"
        WHERE ("site"."id" = "groupsites"."siteId" AND "group"."id" = 1) LIMIT 1) IS NOT NULL
   ORDER BY "site"."name" ASC LIMIT 5) AS "site"
INNER JOIN ("groupsites" AS "groups.groupsites"
            INNER JOIN "groups" AS "groups" ON "groups"."id" = "groups.groupsites"."groupId") ON "site"."id" = "groups.groupsites"."siteId"
AND "groups"."id" = 1
ORDER BY "site"."name" ASC;
```

As you can see limit is applied on the subquery and WHERE from the include is applied after the JOIN which results in incorrect data (incorrect in regard to limit and offset). For example that first subquery might return 5 sites where only two are from wanted group, but it doesn't mean there is no more sites from that group, so we'll end up with two sites returned and in reality there might be a lot more of sites in that group.

In our case subquery would be enough so I'm wondering if its possible to use sequelize to get a query that would be something like this:

```
SELECT *
FROM "sites" AS "site"
WHERE
    (SELECT "groupsites"."siteId"
     FROM "groupsites" AS "groupsites"
     INNER JOIN "groups" AS "group" ON "groupsites"."groupId" = "group"."id"
     WHERE ("site"."id" = "groupsites"."siteId" AND "group"."id" = 1 ) LIMIT 1) IS NOT NULL
ORDER BY "site"."name" ASC LIMIT 3;
```

In the meantime we just might use manual query for this use case, but I would like to find a way on how to do this with sequelize as what I described first can't really work in our case and can't seem to get something like the above query using sequelize.

Thanks in advance

**Comment by mickhansen** [comment]
There's no way to currently both filter on an association and then get all results form that association.
If you add a include.where it will be used to filter both the main rows and the included rows.

**Comment by BridgeAR** [comment]
This should work:

```js
Site.findAll({
  include: [
    {
      model: Group,
      attributes: ['id']
    }
  ],
  raw: true,
  limit: 5,
  offset: 0,
  order: [['name', 'ASC']],
  where: { '$Group.id$': 1}
});
```

**Comment by vesurbag** [comment]
@BridgeAR it doesn't work
