### ISSUE TITLE
pg-native incorrectly accessed for lodash@^4.4.0

### ISSUE THREAD

**Issue by jasonchoimtt** [sequelize/sequelize#5476]
The following code errors for lodash@^4.4.0:

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('postgres://localhost/db', {
    native: false,
});

var User = sequelize.define('user', {});

var Role = sequelize.define('role', {}, {
    defaultScope: {
        include: [User],
    },
}); // throws Error: Cannot find module 'pg-native'
```

The main point is that `lib/sequelize.js:574` calls `_.merge`, which proceeds to inspect:

```
options.defaultScope.include[0].options.sequelize.dialect.connectionManager.lib.pg.native
```

Since `pg.native` is a getter, it triggers the said error.

To fix it I think all `_.merge` need to be replaced.

**Comment by janmeier** [comment]
See https://github.com/sequelize/sequelize/pull/5438

**Comment by jibwa** [comment]
Running into the same issue here.

**Comment by aliatsis** [comment]
+1

**Comment by janmeier** [comment]
Should be fixed by https://github.com/sequelize/sequelize/pull/5745
