### ISSUE TITLE
Make it possible to use findOrCreate in nested create

### ISSUE THREAD

**Issue by Laubi** [sequelize/sequelize#5477]
``` javascript
var Player = seq.define('player',{
  name: Sequelize.STRING
},{
  indexes: [
    {
      unique: true,
      fields: ['name']
    }
  ]
});

var Village = seq.define('village',{
  name: Sequelize.STRING
});

var VillageOwner= Village.belongsTo(Player, {as: 'owner'}),

Village.create({
  name: "Sample",
  owner: {
    name: "Greenhorn"
  }
},{
  include: [VillageOwner]
}).then(/**/).then(/**/);
```

Since the player's name is unique, i can't use the simple nested create functionality. It would be nice if there was an option like

``` javascript
/**/
owner: {
  name: "Greenhorn",

  $options: {
    useFindOrCreate: true
  }
} 
/**/
```

for easy usage.

**Comment by Laubi** [comment]
Just found an option ``` * @param {String}        [options.onDuplicate]``` in model.js@line:1831

I don't know if this option can help me, because there is no documentation, nor usage description.

**Comment by daamsie** [comment]
@Laubi the lack of documentation on `onDuplicate` is unfortunate. From trial and error, it seems to allow you to specify what to insert in a query after the ON DUPLICATE KEY ... runs. 

ie.
`onDuplicate: 'UPDATE updatedAt = now()'`

will result in a query with 

`ON DUPLICATE KEY UPDATE updatedAt = now()`
