### ISSUE TITLE
Undefinded addAssociation method

### ISSUE THREAD

**Issue by mgorka92** [sequelize/sequelize#5478]
Hi I tried add new record with association but model don't contain addAssociation method. Below I added parts of my code
/**part of product model**/
` var Product = sequelize.define('product', { /**fields**/  }, {
            tableName: 'product.product'
        });
/**part of recipe model**/
var Recipe = sequelize.define('recipe', { /**fields**/ }, {
            tableName:'recipe.recipe'
        });

/**set association**/
db.product.belongsToMany(db.recipe,{through: 'Recipe.Product'});
db.recipe.belongsToMany(db.product,{through: 'Recipe.Product'});

/**part of router  code**/
router.post('/add', function(req, res) {
    var recipe =  recipeModel.create({
        name: req.body.name,
        description: req.body.description,
        image: req.body.image
    });    
    var product = productModel.findOne( {where:{id:1}});
    
    recipe.addProduct(product);

});`

In console I have error: "TypeError: recipe.addProduct is not a function"

**Comment by janmeier** [comment]
Works fine for me 

```js

var Product = sequelize.define('product', {  }, {
tableName: 'product.product'
});

var Recipe = sequelize.define('recipe', { }, {
tableName:'recipe.recipe'
});

Product.belongsToMany(Recipe,{through: 'Recipe.Product'});
Recipe.belongsToMany(Product,{through: 'Recipe.Product'});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => Promise.join(
    Product.create(),
    Recipe.create()
  ))
  .spread((product, recipe) => recipe.addProduct(product))
  .finally(() => sequelize.close());
```
Can you post a [SSCCE](HTTP://SSCCE.ORG/)?

**Comment by janmeier** [comment]
Oh - `recipeModel.create` returns a promise - you have to wait for it to return before adding the recipe

```js
recipeModel.create().then(function (recipeinstance) {
  recipeInstance.addProduct ...
});
```

**Comment by janmeier** [comment]
In the future, please use [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) to format your post, that makes it easier for us to spot the problem :)
