### ISSUE TITLE
Find returns a null instance instead of catch

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#5480]
So this is my section of code:
```JavaScript
  /**
   * Verifies the specified user against the specified token
   * @param {string | number} user
   * @param {string} token
   * @returns {Object} promise
   */
  static verifyEmailVerificationToken(user, token) {
    return models.User.findOne({where: {$or: [{email: user}, {id: user}], emailToken: token}}).then(function(user) {
      return user.update({emailConfirmed: true, emailToken: null}).then(function(user) {
        eventService.emit('users.verifyEmailVerificationToken', user);
        return user;
      });
    });
  }
```

The `user.update` section should not be fired am I correct? The promise's "catch" callback should be the code that is triggered, however it is not. The "then" callback is being called with a null instance.

now I know this is the intended purpose, but shouldn't it invoke the catch instead?

**Comment by janmeier** [comment]
Do you want for findOne to throw an error when nothing is found? In that case, see https://github.com/sequelize/sequelize/issues/272
