### ISSUE TITLE
Sequelize.truncate causes deadlocks with cascade: true

### ISSUE THREAD

**Issue by mkornblum** [sequelize/sequelize#5486]
We have a table schema something like:

```sql
CREATE TABLE "ToDos" (
    id integer NOT NULL,
    "personId" integer NOT NULL,
    "organizationId" integer NOT NULL,
    text character varying(255) NOT NULL,
);
CREATE TABLE "Persons" (
    id integer NOT NULL,
    "firstName" character varying(255) NOT NULL,
    "lastName" character varying(255),
);
CREATE TABLE "Organizations" (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
);

ALTER TABLE ONLY "ToDos"
    ADD CONSTRAINT "ToDos_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organizations"(id);
ALTER TABLE ONLY "ToDos"
    ADD CONSTRAINT "ToDos_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Persons"(id);

```
We want to call `Sequelize.truncate` to truncate all our tables as part of our test suite. We are using Postgres, and so have to use `Sequelize.truncate({ cascade: true })`, because otherwise we have dangling foreign keys and the truncate fails. This occasionally leads to deadlocks. We believe this is because Sequelize internally uses `Promise.map` [here](https://github.com/sequelize/sequelize/blob/a49a7c1d7281952c19af9daf416634c56f90bf7f/lib/sequelize.js#L1003), which has the impact of attempting to run the truncate calls in parallel. If the truncate calls for Persons and Organizations happen near enough to the same time, they both try to cascade to "ToDos" and it fails.

It appears switching to use `Promise.each` instead, as `Sequelize.drop` does [here](https://github.com/sequelize/sequelize/blob/a49a7c1d7281952c19af9daf416634c56f90bf7f/lib/sequelize.js#L1034), will sort out this issue, since `.each` executes the promises serially.

We would be happy to open a PR with this fix if you think it would help.

**Comment by mickhansen** [comment]
Switching to `each` when `cascade` is defined seems fair, i could see how multiple cascading truncates in parallel might cause issues.

**Comment by mkornblum** [comment]
Opened PR here: https://github.com/sequelize/sequelize/pull/5487

**Comment by mkornblum** [comment]
Closing issue as the PR was merged :+1:
