### ISSUE TITLE
"IS NOT" conditions for BOOLEAN in Postgres 

### ISSUE THREAD

**Issue by SerjoPepper** [sequelize/sequelize#5489]
In Postgres `val IS NOT TRUE` and `val != TRUE` is different expressions. In second case `null` values don't match.
So, when I write `val: {$ne: true}`, it should be coverted to `val IS NOT TRUE`

**Comment by mickhansen** [comment]
`$ne` is an abbrevation for `not equal` so that should definitely convert to `!= true`.
We can discuss whether or not `$not: true` should map to IS NOT though.

**Comment by SerjoPepper** [comment]
I think BOOLEAN should have same behavior as NULL.
Now in Sequelize `{$eq: null}` coverted to `IS NULL` and `{$ne: null}` converted to `IS NOT NULL`

**Comment by mickhansen** [comment]
> I think BOOLEAN should have same behavior as NULL.

And i disagree, either way it should be up to the user and changing `$eq` would make it impossible for the user.

**Comment by SerjoPepper** [comment]
> We can discuss whether or not $not: true should map to IS NOT though.
OK. I agree with this construction.
Now I write raw queries to match not `TRUE` values. It is very sad.

**Comment by mickhansen** [comment]
As mentioned we can definitely look at fixing `$not: true`

**Comment by SerjoPepper** [comment]
What do you mean in `fixing`?
I did not found `$not` here http://docs.sequelizejs.com/en/stable/docs/querying/

**Comment by mickhansen** [comment]
Because that case isn't covered yet, however $not does exist for other cases.
