### ISSUE TITLE
Possibility to ignore 'allowNull: false' for modification on beforeCreate

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#5490]
Possibility to have `allowNull: false`, but add the value on the beforeCreate hook. So for example, here is something I'm trying to achieve:

```JavaScript
// Here is the column I want to auto fill
authCode: {
  type: DataTypes.STRING(6),
  allowNull: false
}
```
```JavaScript
// Here are my hooks
hooks: {
      beforeCreate: function(user) {
        user.generateEmailVerificationToken();
        user.generateAuthenticationCode();
        user.setDataValue('password', bcrypt.hashSync(user.password, 8));
      },
      beforeUpdate: function(user) {
        user.setDataValue('password', bcrypt.hashSync(user.password, 8));
      }
    }
```

**Comment by janmeier** [comment]
I'd prefer not to change the order that hooks and actions are run in - it has potential to cause annoying breaks for a lot of users.

You can use a `beforeValidate` hook instead
```js

var User = sequelize.define('user', {
  foobar: {
    type: Sequelize.STRING,
    allowNull: false
  }
}, {
  hooks: {
    beforeValidate: function (instance) {
      if (instance.isNewRecord) {
        instance.foobar = 'baz';
      }
    }
  }
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => {
    return User.create({});
  })
  .finally(() => sequelize.close());

```

**Comment by KieronWiltshire** [comment]
You wouldn't be changing the order?
This does solve my problem though. Is there a way to check which data values were updated in the onUpdate hook?

**Comment by janmeier** [comment]
> You wouldn't be changing the order?

I don't want to change the order that hooks are called - e.g. so beforeCreate is called before validation.

You can use `.changed` to see what was has changed http://docs.sequelizejs.com/en/latest/api/instance/#changedkey-booleanarray

**Comment by KieronWiltshire** [comment]
@janmeier that's not what I asked, what I asked is for the possibility of `allowNull: false` to skip the validation phase so we can provide it in the beforeCreate

**Comment by janmeier** [comment]
You should also be able to pass `{skip: ['authCode'] } to the create / save call - which will disable validations for the field
