### ISSUE TITLE
.destroy({where : {} }) is not destroying everything

### ISSUE THREAD

**Issue by DanMMX** [sequelize/sequelize#5491]
I have some testing using `User.destroy({ where: {} });` but the destroy isn't happening.

https://gist.github.com/DanMMX/d4faef5d3bafc4ef0591

**Comment by janmeier** [comment]
Can you please show a [SSCCE](HTTP://SSCCE.ORG/) - Preferrably model defintions and a single test that is failing instead of a CP of some of your specs

**Comment by DanMMX** [comment]
My fault @janmeier , forgot about forcing the deletion because of the paranoid option.
