### ISSUE TITLE
Microsoft SQL Server Support

### ISSUE THREAD

**Issue by tahosa** [sequelize/sequelize#5492]
Related to #4404, the support for SQL server (especially pre-2012) is lacking in a couple of key areas:

#### Automatically detecting version
SQL Server [doesn't use semver](https://github.com/sequelize/sequelize/blob/046620a6c6fdd61e17cb72751ac0fef331f5611e/lib/dialects/abstract/connection-manager.js#L210), and the [query to fetch version](https://github.com/sequelize/sequelize/blob/046620a6c6fdd61e17cb72751ac0fef331f5611e/lib/dialects/mssql/query-generator.js#L41) can be improved. These combined means that the `databaseVersion` gets set in the options to the default value of `0`, which is not very helpful. There is a [TechNet article](https://gallery.technet.microsoft.com/Determining-which-version-af0f16f6) that has some better queries for fetching version information from the server.

Adding this support would also allow the query generator to automatically switch syntax based on the server version. This has already been implemented in some of the postgres code.

#### Using `LIMIT` and `OFFSET` (issue fully described in #4404)
Before SQL Server 2012, this syntax was invalid for querying. You need to do something like `SELECT TOP 10 ... FROM ...`, and there is no built-in support for `OFFSET`

I'm starting to work on a pull request that would fix at least these two problems, but I'd appreciate if anyone else has information on other issues they've hit with SQL server version incompatibilities.

**Comment by mickhansen** [comment]
We haven't heard from the guy who originally comitted to maintaing MSSQL for a good while so don't expect much to change.

@janmeier & I do not work with MSSQL and have 0 experience with it, so we are looking for someone else to provide expertise and patches.

**Comment by janmeier** [comment]
Any contributions would be very welcome
