### ISSUE TITLE
findOrCreate and MySQL sql_mode NO_AUTO_VALUE_ON_ZERO

### ISSUE THREAD

**Issue by riemannzeta** [sequelize/sequelize#5493]
Just a note to anybody else who ends up scratching their head on this one.

Was getting the following

ame: 'SequelizeUniqueConstraintError',
  message: 'Validation error',
  errors: 
   [ { message: 'PRIMARY must be unique',
       type: 'unique violation',
       path: 'PRIMARY',
       value: '0' } ],
  fields: { PRIMARY: '0' } }

DESPITE the fact that my table was setup with an auto_increment id field (normally this is the problem for most people).

Sequelize was auto-generating an INSERT query with the id field set to value DEFAULT.  Apparently DEFAULT means 0 to MySQL, and 0 (when that sql_mode is on) does _not_ trigger an autoincrement.

I understand that this setting is on for my server for security reasons, so not sure whether or not there is a change that could be implemented in the ORM to avoid this... like I said, just a heads up.

**Comment by mickhansen** [comment]
Ah, that's a curious case, we use `DEFAULT` so we don't have empty queries.

**Comment by janmeier** [comment]
Actually mysql does support empty values - But `{ id: null }` is passed to the insert query, so the path for empty values is never triggered https://github.com/sequelize/sequelize/blob/eabab6f7d97a5cd55d0b2a9096553e493370a443/lib/dialects/abstract/query-generator.js#L214

**Comment by janmeier** [comment]
And the null value is added here: https://github.com/sequelize/sequelize/blob/eabab6f7d97a5cd55d0b2a9096553e493370a443/lib/instance.js#L36 - To fix postgres which does not allow empty values. I think it might be better to fix that problem in the query generator, rather than in instance.js though

**Comment by magp3** [comment]
I also had this issue, took a while before I found out what was causing this!

**Comment by Hugh-wong** [comment]
Maybe you should mark this issue to the document.
