### ISSUE TITLE
Inabilty to retrive anything when using mssql [urgent]

### ISSUE THREAD

**Issue by MaximilianLloyd** [sequelize/sequelize#5494]
I am trying to do a very simple findAll() call. I have been fighting with this library all night and trying to get it to work. No matter what version of find/findOne, etc i try to call i allways get an error even though it successfully connects to the database. When i use findAll i get something like Invalid column name 'updatedAt'(like shown in the picture below). This column name isn't even apart of the table in the actual database or the model, strange right? Mind you that the model i am using is generated from the sequelize-auto utility. 
![skjermbilde](https://cloud.githubusercontent.com/assets/10583205/13369762/4671783a-dcf9-11e5-980c-d4e2d43c1193.PNG)

**Comment by janmeier** [comment]
See http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration for info on how to disable some / all timestamps

**Comment by MaximilianLloyd** [comment]
Thank you this solved my issue. The reason this was happening i belive is because it is a table i only have read permission on :smile
