### ISSUE TITLE
Associations are bugged when using as (3.19.3 + MySQL)

### ISSUE THREAD

**Issue by geoffreak** [sequelize/sequelize#5496]
After banging my head against the wall trying to get sequelize to generate the correct query for eager loading, I came to realize that it was actually the association that was bugged.

I have the following relations setup between two models, invoice and subscription, such that invoices are in a one-to-many relationship with subscriptions (a subscription has many invoices) and in a one-to-one relationship with subscriptions (a subscription has a currently due invoice).

Association setup (association to unrelated `account` model not shown):
```coffee
models.invoice.belongsTo models.subscription, { onUpdate: 'cascade', onDelete: 'set null', as: 'Dickbutt' }
models.subscription.hasMany models.invoice, { as: 'Invoices' }

models.invoice.belongsTo models.subscription, { onUpdate: 'cascade', onDelete: 'cascade', as: 'DueForSubscription' }
models.subscription.hasOne models.invoice, { as: 'CurrentlyDueInvoice' }
```

The problem is that this doesn't generate the correct keys (underscored is on):
![](http://take.ms/f5cfF)
Where did this `subscription_id` come from? We can see the expected `dickbutt_id` and `due_for_subscription_id`, but there isn't any code to add this `subscription_id`!

It gets worse when trying to eager load. I was trying to use a query like the following:
```coffee
models.subscription.findAll
  include: [
    model: models.invoice
    as:    'CurrentlyDueInvoice'
  ]
```

But the resulting MySQL query didn't care about my plight. It just defaulted to this undesired `subscription_id` field that shouldn't exist.
```sql
LEFT OUTER JOIN `invoices` AS `CurrentlyDueInvoice` 
  ON `subscription`.`id` = 
     `CurrentlyDueInvoice`.`subscription_id` 
     AND `CurrentlyDueInvoice`.`deleted_at` IS NULL 
```
Ditching the `as` in the eager loading informs me `invoice is not associated to subscription!`, so that doesn't fix anything

Let me know if more information is needed or if there's a simple fix for this. I've tried reversing the relationship on the one-to-one, but received a recursive relationship error.
```
Fatal Error: Cyclic dependency found. invoices is dependent of itself.
Dependency chain: invoices -> subscriptions => invoices
```

EDIT:
I should also add that removing either of the two relations does not cause the `subscription_id` to vanish, so it seems to have nothing to do with double relations to the same table. It is always added as a foreign key immediately after whichever is first.

**Comment by geoffreak** [comment]
Another datapoint to add:

I also tried `invoice.getCurrentlyDueInvoice()` and that also doesn't work. It produces a MySQL query like:
```sql
WHERE (`invoice`.`deleted_at` IS NULL AND (`invoice`.`subscription_id` = 1));
```
where once again we've got our bogus `subscription_id` being used

**Comment by janmeier** [comment]
`subscription.hasMany(invoice, { as: 'Invoices' })`

Adds `subscription_id` - If you want it to match up with `dickbutt_id` you should add `foreignKey: 'dickbutt_id'` to the options.

The same is true for the due for subscription - we cannot figure that the two calls are two sides of the same association, so sequelize tries to add two FKs

**Comment by geoffreak** [comment]
Yep, that's what I was missing. Thanks for the tip. Somehow I had got it into my head that `foreignKey` wasn't what I was looking for. 

Looking back in the docs, I do see a small note regarding this in the Belongs-To-Many examples section of the Relations/Associations page, but there is nothing explaining this in the Foreign Keys section.
> Sometimes you may want to rename your models when using them in associations. Let's define users as workers and projects as tasks by using the alias (`as`) option. We will also manually define the foreign keys to use:
> ```javascript
> User.belongsToMany(Project, { as: 'Tasks', through: 'worker_tasks', foreignKey: 'userId' })
> Project.belongsToMany(User, { as: 'Workers', through: 'worker_tasks', foreignKey: 'projectId' })
> ```
> `foreignKey` will allow you to set **source model** key in the **through** relation. `otherKey` will allow you to set **target model** key in the **through** relation.

So while this section does mention using foreign keys with `as`, it specifically is in the context of `through`, which makes it seem like it is used for a different use-case.

I would suggest adding a note about this in the foreign keys section and the naming strategy section to help people find this out.
