### ISSUE TITLE
How to get last inserted ID of a raw query?

### ISSUE THREAD

**Issue by ryurage** [sequelize/sequelize#5499]
I'm trying to get the last inserted ID of this query:
```

mysql_sequelize.query(
    'INSERT IGNORE INTO steamer(steamer_id, prov_id, name, avatar) VALUES(UNHEX(REPLACE(UUID(),\'-\',\'\')), \'' + prov_id + '\', \'' + steamer_name + '\', \'' + steamer_avatar + '\')',
).then(function (data) {
    console.log('inserted STEAMER data---> ',data)  // not very helpful info below
});
```

But I get a pretty useless response back:
```
inserted STEAMER data--->  [ OkPacket {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 1,
    message: '',
    protocol41: true,
    changedRows: 0 },
  OkPacket {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 1,
    message: '',
    protocol41: true,
    changedRows: 0 } ]
```

I just want the affected row's ID (it's a binary) so I can throw it into a variable and use it for a subsequent query.  

At this point, you may be saying "well give it a model" that looks like this maybe:
```
mysqlSteamer = mysql_sequelize.define('steamer', {
                    'steamer_id': {
                        primaryKey: true,
                        type: Sequelize.BLOB(16)
                    },
                    'prov_id': Sequelize.INTEGER(6),
                    'name': Sequelize.STRING(250),
                    'avatar': Sequelize.STRING
                }, {
                    tableName: 'steamer'
                }),
```

but I don't think that's right because I get this error in response:
```
TypeError: valueSets.map is not a function
    at Model.bulkBuild (/Users/sadpanda/git/my_repo/node_modules/sequelize/lib/model.js:1792:20)
```

Ideas?

**Comment by janmeier** [comment]
You can pass `{ type: sequelize.QueryTypes.INSERT }` as the options argument - this will tell sequelize to return the insert it. Or you could use the `insertId` or the result you get back (in the case of your example it's probably 0 because the insert is ignored

**Comment by ryurage** [comment]
@janmeier passing the optional parameter as you noted returns this result for data:
`inserted STREAMER data--->  0`
which is again, a very unhelpful result.  

It's also worth noting that the insert is not ignored, it's actually inserting into the table.  It's just the data returned back in response gives me nothing useful.

**Comment by janmeier** [comment]
> If you use INSERT IGNORE and the row is ignored, the AUTO_INCREMENT counter is not incremented and LAST_INSERT_ID() returns 0, which reflects that no row was inserted.

http://stackoverflow.com/questions/6291405/mysql-after-insert-ignore-get-primary-key

```js
var user = sequelize.define('user', {
  email: {
    type: Sequelize.STRING,
    unique: true
  }
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => {
    return sequelize.query(
      'INSERT IGNORE INTO users(email) VALUES(\'foobar\')', {
        type: Sequelize.QueryTypes.INSERT
      }
    ).then(function (data) {
      console.log('inserted STEAMER data---> ',data)  // not very helpful info below

      return sequelize.query(
        'INSERT IGNORE INTO users(email) VALUES(\'foobar\')', {
          type: Sequelize.QueryTypes.INSERT
        }
      ).then(function (data) {
        console.log('inserted STEAMER data---> ',data)  // not very helpful info below
      });
    });
  })
  .finally(() => sequelize.close());
```

```sql
Executing (default): INSERT IGNORE INTO users(email) VALUES('foobar')
inserted STEAMER data--->  1
Executing (default): INSERT IGNORE INTO users(email) VALUES('foobar')
inserted STEAMER data--->  0
```
So I'm pretty sure that 0 means no row was inserted. If not, it sounds like a mysql / node-mysql issue.

By all means, please provide a [SSCCE](HTTP://SSCCE.ORG/), I just can't replicate the issue

**Comment by ryurage** [comment]
@janmeier per your request for an SSCCE: https://github.com/ryurage/testsequelize

**Comment by amdp** [comment]
https://github.com/tediousjs/node-mssql/issues/32#issuecomment-480527587

**Comment by amdp** [comment]
Duplicate of #https://github.com/tediousjs/node-mssql/issues/32

**Comment by amdp** [comment]
https://github.com/tediousjs/node-mssql/issues/32

**Comment by amdp** [comment]
router.post("/link", (req, res) => { 
  const rowData = { autoincrementId: req.body.id, name: req.body.name }
    yourModel.create(rowData)
          .then(row => { 
            sequelize.query('SELECT @@IDENTITY', {type: Sequelize.QueryTypes.SELECT}) .then(id => console.log(id));
...
