### ISSUE TITLE
[Question] Join multiple databases

### ISSUE THREAD

**Issue by dongseok0** [sequelize/sequelize#5500]
Hi,

I'd like to join tables from different databases like T1 from DB1 and T2 from DB2.
```
SELECT * FROM DB1.T1 JOIN DB2.T2
```

I've made 2 sequelize instances for each database.
And tried to set relation between model instances from each db
```
T1 = DB1.import(...);
T2 = DB2.import(...);
T1.belongsTo(T2, {foreignKey: 'studentId', as: 'student', constraints: false});  // <- Is it available??
```
And when try to query, error occur:
```
SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'DB1.T2' doesn't exist
```

Is it possible set association for multiple databases?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/3023
