### ISSUE TITLE
DISTINCT ON multiple fields

### ISSUE THREAD

**Issue by galioy** [sequelize/sequelize#5501]
Is it possible to use the API to get `DISTINCT ON` multiple fields? As I can see now, it's only possible to aggregate over 1 field, by passing `DISTINCT` as aggregate function to `MyModel.aggregate(...)`. But what if I want todo it over 2 fields? F.e. this SQL query:
```sql
SELECT DISTINCT ON (column_1, column_2) * FROM my_table ORDER BY column_1, column_2, create_time DESC
```
How can this be written in JS, using the API, but not executing a raw query?

**Comment by thynson** [comment]
Related to #5475

**Comment by sushantdhiman** [comment]
Duplicate #5475
