### ISSUE TITLE
Is there any way to include "hasAssociation" attribute in the result.

### ISSUE THREAD

**Issue by faressoft** [sequelize/sequelize#5503]
I have a a model called "User" and "Follow" as through table.
A user can follow another user.

```
User.belongsToMany(User, { as: 'followers', foreignKey: 'following_id', through: Follow });
User.belongsToMany(User, { as: 'following', foreignKey: 'follower_id', through: Follow });
```

Is there any way to make a "findAll" operation and including an attribute called "isFollowed" to a specific another user that I can pass somehow ?

Lets assume that "userJames" is an instance.
I want to find a user called "John" and return with result "isFollowed" attribute to userJames

**Comment by mickhansen** [comment]
Not possible i'm afraid, you'll have to do an include matching your target and then simply check if the result has a length.

**Comment by faressoft** [comment]
How can I include the "followers" in my case ?

**Comment by mickhansen** [comment]
`include: [{model: User, as: 'followers', where: {id: 'james'}}]`

**Comment by faressoft** [comment]
Thanks :+1:
