### ISSUE TITLE
Migration - Column Unique and Not null

### ISSUE THREAD

**Issue by Turok21** [sequelize/sequelize#5507]
Hi, 

I have an issue with a sequelize migration.
I need to add a column on a table name "Agency", and the new row to be UNIQUE and NOT NULL.

I already try lot of Migration without a complete success 
- Or the row is unique but can be null,
- Or the row is null but the KEY is on multiple 

A already tried : with addColumn, changeColumn, addIndex, 
`queryInterface.addColumn("Agency","typeInfos",
            {
                type      : Sequelize.STRING,
                unique    : true,
                allowNull : false
            }
);`

AND

`queryInterface.changeColumn("Agency","typeInfos",
            {
                type      : Sequelize.STRING,
                unique    : true,
                allowNull : false
            }
);`

AND

` queryInterface.addIndex(
            'Agency',
            ['typeInfos'], {
                indexName   : "typeInfos_unique",
                indexType   : "BTREE",
                indicesType : "UNIQUE"
    },`

All try is a not complete succes - row is at the end like bellow 
+-------------------------+-------------------+------+-----+---------+----------------+
| Field                       | Type               | Null | Key | Default | Extra          |
+-------------------------+-------------------+------+-----+---------+----------------+
| typeInfos    | varchar(255)    | **YES | UNI** | NULL    |                |
OR
| typeInfos    | varchar(255)    | **NO  | MUL** | NULL    |                |

I'l have something like this : 
+---------------+--------------+------+-----+---------+----------------+
| id            | int(11)      | NO   | PRI | NULL    | auto_increment |
| name          | varchar(255) | **NO   | UNI** | NULL    |                |

**Comment by Turok21** [comment]
Auto update and self answer ;)
so if other have the same ''issues'

Because it's a migration,
there is already data on BDD, 
so i can't make row unique and not null without before update existing rows


So need to  : 
```
 queryInterface.addColumn(
            "Agency",
            "idLumdocsType",
            {
                type   : Sequelize.STRING,
                unique : true,
            }
        ).then(function (data) {
                  // DO STUFF TO FILL ALL EXISTING ROWS
            }).then(function (data) {
                queryInterface.changeColumn(
                    "Agency",
                    "idLumdocsType",
                    {
                        type      : Sequelize.STRING,
                        allowNull : false
                    }
                );
            });
```

**Comment by manoellribeiro** [comment]
If you are using Postgres and want to change a column of ENUM type it won't work. It throws an error saying that the data TYPE you are trying to create already exists. I turned it around setting the defaultValue, but I don't think it'll work in all cases.
