### ISSUE TITLE
Sequelize Healthcheck

### ISSUE THREAD

**Issue by MarkHerhold** [sequelize/sequelize#5509]
I was wondering if anyone has any experience implementing a healthcheck function that checks the health of Sequelize's connection pool. Any ideas on how this could be best accomplished or what people have done in the past would be extremely helpful.

**Comment by mickhansen** [comment]
Health as in current amount of connections or health as checking the individual connections?

**Comment by MarkHerhold** [comment]
I don't see why not both. If we monitor the number of active connections as well as the health of each connection, monitoring tools could key off of that information to determine if an application is trending towards failure.

But if we want to start simple, I'd say that I am most concerned that there is at least one connection in the pool that is able to communicate with the database.

**Comment by evfreethy** [comment]
I second that motion. Currently diagnosing a bug that boils down to multiple idle connections exhausting the connection pool. How many connections are allocated by default when using the connection pool anyway? 

A way to inspect this without any arcane sql queries would be ideal - thats one of the reasons we use ORM's anyway right?

**Comment by mickhansen** [comment]
The default pool config is `0/5` IIRC.
At a lower level, some way to inspect the pool (and connections) would be ideal, then health checks could be added on top of that.

**Comment by DaAwesomeP** [comment]
+1 for health checks. I use basic 200 HTTP statuses in my apps to report periodically to a monitor instance that the app is functioning properly. I would like to be able to check the DB as well.
