### ISSUE TITLE
Add child objects to a parent model

### ISSUE THREAD

**Issue by davidleureka** [sequelize/sequelize#5511]
Let's say I have a `car` model and a car has 0 or more `seat` objects associated with it. I have a web method that allows the user to update fields on the car itself and add new seats all at once.

```
db.Car.findById(carId, { include: [{ model: db.Seat, as: 'seats' }] })
.then((car) => {
    car.color = 'blue'
    car.make = 'Jaguar'
    //...
    car.seats.push({
        type = 'standard',
        cover = 'leather'
    })
    return car.save()
})
```

This apparently does not work. I'm guessing you have to use `db.Seat.create` and not just add generic objects to the `car.seats` list. Is that right?

**Comment by mickhansen** [comment]
In this case you'd have to use `car.createSeat({... values})`. We don't currently have any support for nested updates.
