### ISSUE TITLE
Read-replication bad connection

### ISSUE THREAD

**Issue by bringking** [sequelize/sequelize#5512]
### Sequelize Version

3.17.1
### Dialect

MySQL
### Behavior

Given a config with a write-master and multiple read-replicas -

``` js
  "replication": {
      "read": [
        {
          "host": "localhost",
          "username": "root",
          "password": "root",
          "port": 8882 // THIS DB DOESN'T EXIST
        },
        {
          "host": "localhost",
          "username": "root",
          "password": "root",
          "port": 8883 // THIS DB DOESN'T EXIST
        }
      ],
      "write": {
        "host": "localhost",
        "username": "root",
        "password": "root",
        "port": 8889
      }
    },
    "pool": {
      "maxConnections": 1,
      "maxIdleTime": 30,
      "handleDisconnects":true
    }
```

Sequelize seems to continually retry connections to the read partners even though the first two connections throw a `SequelizeConnectionRefusedError`.
### Enhancement or Clarification

After a connection refused error, is it possible to remove a read-replica from the replica set? Or swap it with a backup replica?

**Comment by mickhansen** [comment]
I'd love to make connections more modular so people could plug in logic for this.
As a default we don't have anything atm, but i could see a case for backoff-attempts on servers and possible swapping them out, but we also need recovery in cases where a server is only down for 5 minutes.
