### ISSUE TITLE
Is this type of association possible?

### ISSUE THREAD

**Issue by philraj** [sequelize/sequelize#5514]
I'm still very new to how Sequelize does things, and was wondering if there's an official way to do what I'm trying to accomplish. 

I have 3 inter-related models: User, Post, and Comment.
I've set up the following associations:
```
User.hasMany(Comment);
Post.hasMany(Comment);
Comment.belongsTo(User);
Comment.belongsTo(Post);
```
What I'd like to be able to do, as I've done in similar cases, is create a comment by using a syntax like:
```
user.addComment(post, { ... } )
```
Where 'user' and 'post' are instances of their respective models. What I'm trying to do here is add the comment to the underlying table, and have Sequelize insert the appropriate userId and postId based on the instances I'm referencing.

In other cases, I was able to use such a syntax by including a many-to-many association, through an intermediary model _(via the_ {through: x, as: 'y'} _feature)_. But it's my understanding that I won't be able to set that up in this case, because comments are not unique to a combination of user and post instances, as there can be many comments by the same user on a given post.

Am I doing this completely wrong? Please don't hesitate to correct me if that's the case. I would love to know the proper way of addressing such a situation.

Thanks!

**Comment by mickhansen** [comment]
We have poor support for non-unique N:M at the moment, but that wouldn't really solve your issue here.
Your best bet is to main comment manually, you'll have to use `user.createComment({postId: post.id})` or similar.

**Comment by philraj** [comment]
Ok, that's what I was already doing. Thanks for the response.
