### ISSUE TITLE
Create associations via key on belongsToMany 

### ISSUE THREAD

**Issue by dexwiz** [sequelize/sequelize#5519]
The following is possible:

```javascript
Task.belongsTo(User, { foreignKey: 'userId' })

Task.create({name: 'taskName', userId: 123})
```
This will create a task, and associate it to an existing user. This seems to work find for M:1, but I want to do something similar for N:M.

```javascript
User.belongsToMany(Project, {through: 'UserProject', foreignKey: 'userId', otherId: 'projectId'})
Project.belongsToMany(User, {through: 'UserProject', foreignKey: 'projectId', otherId: 'userId'})

User.create({name: 'userName', projectIds: [321, 432, 543]})
```

In this case I want to be able to create a user and associate to the existing projects 321, 432, and 543. The usecase is to use an object directly from an API request payload. I want to be able to set up my models to accept this payload directly, instead of having to parse it out, look up the projects, and manually associate them. 

I am guessing this is not possible. The task example is just inserting an ID into a field and checking a reference, but the Project example would have to create entries on both User and UserProject.

**Comment by mickhansen** [comment]
It might become a part of nested updates, but can't say for sure.
This case is sort of specific so i suggest you simply implement your own code in an afterCreate hook.

**Comment by dexwiz** [comment]
How can I access values passed to User.create() in a hook? The hooks only seem to have access to the model which would only contain name. I want to try to avoid tricks with involving scope to access projectIds.

**Comment by mickhansen** [comment]
Hmm right, the hooks are only run with the instance. You'd have to rely on accessing undefined values, which should work but isnt technically a 100% correct.
