### ISSUE TITLE
In the where of findAll, I want to use a spatial function in where

### ISSUE THREAD

**Issue by yhyuan** [sequelize/sequelize#5528]
Hi,
I want to use a calculated attribute: isContained, which is used to specific whether a point is inside a polygon or not. 
Here is my code. 
 **const point = "'POINT(" + lng + " " + lat + ")'";
 const forecasts = await Forecasts.findAll({where: {isContained: true}, attributes: ['forecast_type', 'the_geom', [sequelize.fn('ST_Contains', sequelize.col('the_geom'), sequelize.literal("ST_GeomFromText(" + point + ", 4326)")), 'isContained']]});**

The generated SQL will be.
**SELECT "forecast_type", "the_geom", ST_Contains("the_geom", ST_GeomFromText(\'POINT(100.5 0.5)\', 4326)) AS "isContained" FROM "Forecasts" AS "Forecasts" WHERE "Forecasts"."isContained" = true**

However, since isContained is not a column name, it does not work. I want to move ST_Contains("the_geom", ST_GeomFromText(\'POINT(100.5 0.5)\', 4326)) to the WHERE part. The final SQL should be
 **SELECT "forecast_type", "the_geom" FROM "Forecasts" AS "Forecasts" WHERE , ST_Contains("the_geom", ST_GeomFromText(\'POINT(100.5 0.5)\', 4326));**
How can I do it?

**Comment by mickhansen** [comment]
You can use `sequelize.fn(fn, arg1, arg2)` to generate SQL function queries
