### ISSUE TITLE
 _componentsSequel2.default.define is not a function

### ISSUE THREAD

**Issue by MaximilianLloyd** [sequelize/sequelize#5532]
It keeps giving " _componentsSequel2.default.define is not a function". I am just doing a simple export and trying to import it in my user model. 

Screencap: 
![capture](https://cloud.githubusercontent.com/assets/10583205/13544814/6c9cf066-e27b-11e5-837b-4d3e939bc2c8.PNG)

**Comment by MaximilianLloyd** [comment]
Got a step further. The reason i got the previous error was because i was importing the user model in while the user model was importing the sequel module.

**Comment by MaximilianLloyd** [comment]
Currently getting this error: "TypeError: store.on is not a function"
![capture](https://cloud.githubusercontent.com/assets/10583205/13544896/5e99ba4c-e27d-11e5-8488-f4174173a4b3.PNG)

**Comment by mickhansen** [comment]
I'm not sure how express-session works. However if Sequelize is the store, we don't have any event emitter.
