### ISSUE TITLE
How to query custom defined join table

### ISSUE THREAD

**Issue by Hnus-** [sequelize/sequelize#5537]
I have three models `user`, `tab`, `subscription`. User can subscribe to many tabs and tab can have many subscribers. 
`user --* subscription *-- tab`

Diagram from navicat
![diagram](http://i.imgur.com/WUGEtdL.png)

```javascript
sequelize.define('subscription', {})

Tab.belongsToMany(User, { through: Subscription })
User.belongsToMany(Tab, { through: Subscription })
```

How do I get all subscribers for specific tab or all tabs which specific user subscribes to?
I could do that in two queries but it have to be possible in one.

I tried every possible combination of `where`, `include`, `through` which I would rather not share here. Every time I try to get access to `subscription` from any side I get `subscription (subscriptions) is not associated to user`.

I would like to be able to do something like this
```javascript
  await Tab.findAll({
    where: { name: ctx.params.tabname },
    include: [{
      model: Subscription,
      through: {
        where: { userUsername: ctx.params.username }
      }
    }]
  })
```
Please help I am going crazy over this.

**Comment by mickhansen** [comment]
You don't have an association to Subscription, you have one to User, through subscription, so you're not able to query subscription directly.

Simply change the include model to User rather than Subscription and it should work.

**Comment by Hnus-** [comment]
@mickhansen Thanks I guess I need to RTFM a bit more:)
I posted the same question on SO and got an answer explaining my misconception about how relations are made in detail.
http://stackoverflow.com/questions/35826684/how-to-query-custom-defined-join-table
