### ISSUE TITLE
how to use limit order in include

### ISSUE THREAD

**Issue by turengege** [sequelize/sequelize#5539]
Itry like this , but faild 
`person.findAll({
include:{model:comments,separate:true,limit:5,order:["id","DESC"]}
        })
`
and get typeError: Cannot read property 'push' of undefined

**Comment by mickhansen** [comment]
It sohuld work with seperate assuming its a hasMany association.
Please include the entire stack trace.

**Comment by turengege** [comment]
TypeError: Cannot read property 'push' of undefined
    at /home/juximao/project/juximao1.0_nor/juximao/node_modules/sequelize/lib/associations/has-many.js:331:64
    at Array.forEach (native)

 I use separate:true and limit. it gave this Error
this is my code 
`.dynamic
    .findAll({
        include:[
            {model:dbv2.hlr_user,attributes:['name','head_image']},
            {model:dbv2.dynamic_team,attributes:['hlr_name','hlr_head_img','hlr_id']},
            {model:dbv2.dynamic_img,attributes:['img_url'],separate:true,limit:2},
            {model:dbv2.dynamic_changwen,attributes:['description','id']},
            {model:dbv2.comment,attributes:['id','name','content','head_image','create_date'],where:{is_delete:0},required:false}],
        attributes:['id','content','title','hlr_id','cover_img','view_count','type','update_date'],
        limit:ps,
        offset:startIndex,
        where:{is_delete:0},
        order:[['update_date','DESC']]
    })
`

`
 classMethods:{
        associate:function(models){
            this.belongsTo(models.hlr_user,{foreignKey:'hlr_id'});
            this.hasMany(models.dynamic_team,{foreignKey:'dynamic_id'});
            this.hasMany(models.dynamic_img,{foreignKey:'dynamic_id'});
            this.hasOne(models.dynamic_changwen,{foreignKey:'dynamic_id'});
            this.hasMany(models.comment,{foreignKey:'commented_id'});
        },

`

**Comment by mickhansen** [comment]
Please make an effort to properly format your code.
Also that code is a lot more than what you originally posted, it helps everyone if you can reduce your error producing code to as little as possible.

**Comment by turengege** [comment]
sorry. 
```javascript
person.hasMany(comments,{foreignKey:'dynamic_id'})  


comments.belongsTo(Person,{foreignKey:'dynamic_id'})  

Person.findAll({
include:[{model:comments,seperate:true,limit:5}]
})
```
and get error：
```javascript
TypeError: Cannot read property 'push' of undefined
at /home/juximao/project/juximao1.0_nor/juximao/node_modules/sequelize/lib/associations/has-many.js:331:64
at Array.forEach (native)
```
thanks for quick reply

**Comment by mickhansen** [comment]
It looks like your models don't have properly configured primary key definitions, please post both your models.

**Comment by Vorob-Astronaut** [comment]
@mickhansen have the same error

**Comment by janmeier** [comment]
@Vorob-Astronaut  well ... Show some code, otherwise we have _no_ way of debugging .... [SSCCE](HTTP://SSCCE.ORG/)
