### ISSUE TITLE
Invalid validation when used custom get, set methods

### ISSUE THREAD

**Issue by 7davido** [sequelize/sequelize#5543]
Incident occur when I'am trying update model where field has defined get or/and set methods.

I expect that data will be checked before mutations from custom methods.

Now events are following:
1. set data by custom set()
2. get data by modelInstance.dataValues[field]
3. validate this data omitting my custom get()

``` javascript
var Model = sequelize.define('users', {
  id: {
    type: DataTypes.BIGINT,
    allowNull: false,
    primaryKey: true,
    autoIncrement: true,
    unique: true
  },
  example_field: {
    type: DataTypes.STRING,
    allowNull: false,
    get: function () {
      var value = this.getDataValue('example_field');
      var decrypted = someFunction(value);
      return decrypted;
    },
    set: function (value) {
      var encrypted = someFunctionr(value);
      return this.setDataValue('example_field', encrypted);
    },
    validate: {
      len: {
        args: [3, 10]
      }
    },
  }
});

Model.update({example_field: someValue}, {where: {id: 2}});
```

**Comment by mickhansen** [comment]
`validate` is called on `save` since they can be asynchronous.
we don't currently validate on `set`

**Comment by JSteunou** [comment]
Same issue. I though validation would be before / appart the custom getter/setter. I had to remove the validation and put it manually inside setter method :/

**Comment by DominikSerafin** [comment]
Validation should be run before set.
