### ISSUE TITLE
date.utcOffset is not a function when creating model

### ISSUE THREAD

**Issue by blove** [sequelize/sequelize#5547]
The following exception is being thrown when executing model.create().

**Exception**
TypeError: date.utcOffset is not a function
   at DATE.$applyTimezone (/www/local.example.com/node_modules/sequelize/lib/data-types.js:457:19)
   at DATE.$stringify (/www/local.example.com/node_modules/sequelize/lib/dialects/mysql/data-types.js:39:37)
   at ABSTRACT.stringify (/www/local.example.com/node_modules/sequelize/lib/data-types.js:76:17)
   at Object.QueryGenerator.escape (/www/local.example.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:972:32)
   at Object.QueryGenerator.insertQuery (/www/local.example.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:298:28)
   at QueryInterface.insert (/www/local.example.com/node_modules/sequelize/lib/query-interface.js:492:33)
   at null.<anonymous> (/www/local.example.com/node_modules/sequelize/lib/instance.js:665:56)
   at tryCatcher (/www/local.example.com/node_modules/bluebird/js/release/util.js:16:23)
   at Promise._settlePromiseFromHandler (/www/local.example.com/node_modules/bluebird/js/release/promise.js:497:31)
   at Promise._settlePromise (/www/local.example.com/node_modules/bluebird/js/release/promise.js:555:18)
   at Promise._settlePromise0 (/www/local.example.com/node_modules/bluebird/js/release/promise.js:600:10)
   at Promise._settlePromises (/www/local.example.com/node_modules/bluebird/js/release/promise.js:683:18)
   at Async._drainQueue (/www/local.example.com/node_modules/bluebird/js/release/async.js:125:16)
   at Async._drainQueues (/www/local.example.com/node_modules/bluebird/js/release/async.js:135:10)
   at Immediate.Async.drainQueues [as _onImmediate] (/www/local.example.com/node_modules/bluebird/js/release/async.js:16:14)
   at processImmediate [as _immediateCallback] (timers.js:374:17)

**Model**
My model is written in TypeScript (and compiled to JavaScript for execution in Node.js with Express):

```javascript
var user = sequelize.define(NAME, {
  "id": { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
  "email": Sequelize.STRING,
  "first_name": Sequelize.STRING,
  "last_name": Sequelize.STRING,
  "facebook_token": Sequelize.STRING,
  "facebook_user_id": Sequelize.STRING,
  "google_plus_token": Sequelize.STRING,
  "google_plus_user_id": Sequelize.STRING,
  "password": Sequelize.STRING,
  "twitter_token": Sequelize.STRING,
  "twitter_user_id": Sequelize.STRING
}, {
  classMethods: {
    associate: function(models: models.IDatabase) {
      user.hasMany(models.groupsUser, { foreignKey: "user_id" });
      user.hasMany(models.groupsUsersRole, { foreignKey: "user_id" });
      user.belongsToMany(models.group, { through: models.groupsUser.getName() });
      user.belongsToMany(models.role, { through: models.groupsUsersRole.getName() });
    },
    getName: function() {
      return NAME;
    }
  },
  underscored: true
});
```

**Environment**
```
{
	"engines": {
	    "node": "~5.6"
	},
	"dependencies": {
	    "autoprefixer": "latest",
	    "bcrypt-nodejs": "0.0.3",
	    "body-parser": "^1.14.2",
	    "bower": "latest",
	    "connect-flash": "^0.1.1",
	    "cookie-parser": "^1.4.1",
	    "debug": "^2.2.0",
	    "errorhandler": "^1.4.3",
	    "express": "^4.13.4",
	    "express-session": "^1.13.0",
	    "grunt": "latest",
	    "grunt-cli": "latest",
	    "grunt-contrib-clean": "latest",
	    "grunt-contrib-cssmin": "latest",
	    "grunt-contrib-sass": "latest",
	    "grunt-contrib-uglify": "latest",
	    "grunt-contrib-watch": "latest",
	    "grunt-postcss": "latest",
	    "grunt-ts": "latest",
	    "jade": "^1.11.0",
	    "lodash": "^4.4.0",
	    "method-override": "^2.3.5",
	    "morgan": "^1.6.1",
	    "mysql": "^2.10.2",
	    "passport": "^0.3.2",
	    "passport-facebook": "^2.1.0",
	    "passport-google-oauth": "^1.0.0",
	    "passport-local": "^1.0.0",
	    "passport-twitter": "^1.0.4",
	    "sequelize": "^3.19.3",
	    "sequelize-cli": "^2.3.1",
	    "serve-favicon": "^2.3.0",
	    "typescript": "^1.7.5",
	    "typings": "^0.6.9",
	    "umzug": "^1.9.0"
	}
}
```

**Comment by blove** [comment]
It appears this is expecting the date variable to be a momentjs instance. Do I need to include momentjs in my package.json dependencies?

**Comment by blove** [comment]
A console.log(date) on line 452 of data-types.json results in:

```
{ [Number: 1457409981000]
  _isAMomentObject: true,
  _i: Mon Mar 07 2016 21:06:21 GMT-0700 (MST),
  _isUTC: false,
  _pf:
   { empty: false,
     unusedTokens: [],
     unusedInput: [],
     overflow: -2,
     charsLeftOver: 0,
     nullInput: false,
     invalidMonth: null,
     invalidFormat: false,
     userInvalidated: false,
     iso: false },
  _locale:
   Locale {
     _ordinalParse: /\d{1,2}(th|st|nd|rd)/,
     ordinal: [Function],
     _abbr: 'en',
     _ordinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/ },
  _d: Mon Mar 07 2016 21:06:21 GMT-0700 (MST) }
```

As expected, logging out the value of of the date.utcOffset property results in `undefined`.

**Comment by blove** [comment]
A workaround for this issue appears to be to exclude the createdAt and updatedAt columns. I updated my model as follows, dropped by schema and created it again, and then executed sequelize.sync().

```
var user = sequelize.define(NAME, {
  "id": { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
  "email": Sequelize.STRING,
  "first_name": Sequelize.STRING,
  "last_name": Sequelize.STRING,
  "facebook_token": Sequelize.STRING,
  "facebook_user_id": Sequelize.STRING,
  "google_plus_token": Sequelize.STRING,
  "google_plus_user_id": Sequelize.STRING,
  "password": Sequelize.STRING,
  "twitter_token": Sequelize.STRING,
  "twitter_user_id": Sequelize.STRING
}, {
  classMethods: {
    associate: function(models: models.IDatabase) {
      user.hasMany(models.groupsUser, { foreignKey: "user_id" });
      user.hasMany(models.groupsUsersRole, { foreignKey: "user_id" });
      user.belongsToMany(models.group, { through: models.groupsUser.getName() });
      user.belongsToMany(models.role, { through: models.groupsUsersRole.getName() });
    },
    getName: function() {
      return NAME;
    }
  },
  createdAt: false,
  updatedAt: false,
  underscored: true
});
```

**Comment by amansharma0091** [comment]
I'm facing the same issue after updating to 3.19.3

**Comment by amansharma0091** [comment]
My quick fix is this:
`DATE.prototype.$applyTimezone = function (date, options) {
  date = momentTz(date);

  if (options.timezone) {
    if (momentTz.tz.zone(options.timezone)) {
      date = date.tz(options.timezone);
    } else {
      date = moment(date.toDate()).utcOffset(options.timezone);
    }
  }

  return date;
};`

**Comment by kevinwang** [comment]
I have the same issue, and this fixes it. Thanks!

**Comment by theptrk** [comment]
@amansharma0091 What file did you put that code? 

What do you think is causing this? It works on my computer locally but I get this error on Azure.
