### ISSUE TITLE
Model.findAndCount breaks with primary composite index and relations

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#5548]
Dialect: MySQL
Version: Latest (3.19.3)

We experienced a problem when performing a `.count` call via `.findAndCount` on a model whose primary key is composed of multiple columns while using `include:` with `required: true`.

The problem boils down to [this line](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1610) where it uses only 1 column of the  composite primary key, which, in combination with the `distinct` from `findAndCount` causes the query to return an incorrect result.

Ideally it would check if the model uses a composite primary index and perhaps transform into `COUNT(DISTINCT(tableName.*))` or `COUNT(DISTINCT tableName.column1, tableName.column2, ...))` rather than `COUNT(DISTINCT(tableName.anyCompoundIndexColumn))`.

**Comment by SimonSchick** [comment]
Code sample:

```javascript
'use strict';

const Sequelize = require('sequelize');

const db = new Sequelize(
   'test',
   'root',
   ''
);

const ReferencedModel = db.define('ReferencedModel', {
   id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true,
   },
   something: Sequelize.STRING,
}, {
   tableName: 'referencedModel',
});

const CompoundModel = db.define('CompoundModel', {
   a: {
      type: Sequelize.INTEGER,
      primaryKey: true,
   },
   b: {
      type: Sequelize.INTEGER,
      references: {
         model: ReferencedModel,
         key: 'id',
      },
      primaryKey: true,
   },
   c: {
      type: Sequelize.INTEGER,
      primaryKey: true,
   },
}, {
   tableName: 'compoundModel',
});

CompoundModel.hasOne(ReferencedModel, {
   foreignKey: 'id',
});

db.sync({ force: true })
.then(() =>
   ReferencedModel.bulkCreate([
      { something: '1' },
      { something: '2' },
      { something: '3' },
   ])
)
.then(() => CompoundModel.bulkCreate([
   {
      a: 1,
      b: 1,
      c: 1,
   },
   {
      a: 1,
      b: 2,
      c: 1,
   },
   {
      a: 1,
      b: 3,
      c: 1,
   },
]))
.then(() => CompoundModel.findAndCount({
   include: [{
      model: ReferencedModel,
      required: true,
   }],
}))
.then(result => console.log(result.count, result.rows.length))
.catch(console.error);
```

**Comment by saavedrajl** [comment]
Marca.hasMany(Modelo, { foreignKey: 'idmarca' });
Modelo.belongsTo(Marca, { foreignKey: 'idmarca' });

Modelo.hasMany(Modem, { foreignKey: 'idmodelo' });
Modem.belongsTo(Modelo, { foreignKey: 'idmodelo' });

Marca.findAll({
    include : [{
    	model: Modelo, 
    	required: true ,
    	on: {
    		'idmarca': {$col: 'Marca.idmarca'}
    	},
    	include: [{
    		model: Modem,
    		required: true,
    		on: {
	    		'idmodelo': {$col: 'Modelos.idmodelo'}
    		}
    	}]
    }],
}).then(function(result) {
	console.log(JSON.stringify(result))
})

**Comment by mickhansen** [comment]
@saavedrajl Sorry?
