### ISSUE TITLE
Add max length to describe results

### ISSUE THREAD

**Issue by itsravenous** [sequelize/sequelize#5549]
I'm using `Model#describe()` to generate a basic validation schema I can provide as a resource on my API. It would be really useful to get the length of columns back as well as the type and nullability. I'm using MSSQL - I guess the change required is just adding `c.CHARACTER_MAXIMUM_LENGTH` in the [query generator](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query-generator.js#L112), but I assume you'd want a cross-dialect PR?

**Comment by mickhansen** [comment]
A cross dialect PR would be great, but we would accept a mysql specific one aswell (although we might hold off on a full merge untill we've implemented cross dialect on our own)

**Comment by itsravenous** [comment]
Hmm, looks like mysql uses the `DESCRIBE` call in the [base query generator](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L76) so presumably the output is slightly different? Or perhaps it gets normalised somewhere? Apologies, I'm not within reach of a mysql DB just now.

**Comment by janmeier** [comment]
`query.js` for the dialect handles formatting the results to roughly the same structure, see [here](https://github.com/sequelize/sequelize/blob/6fb971f9436c79477074e63a9d6ad76a082474ca/lib/dialects/mysql/query.js#L91) for mysql
