### ISSUE TITLE
include.on support for belongsToMany

### ISSUE THREAD

**Issue by jharting** [sequelize/sequelize#5551]
I run into the lack of support for composite keys in sequelize (https://github.com/sequelize/sequelize/issues/311). I thought about working around that limitation by defining a custom "ON" clauses for the join. This seems to work fine for 1:N relations using 'include.on' (http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance).

However, 'include.on' does not have any effect when used with the belongsToMany relation. Please add support for customized ON clauses for both source and target collections when querying using a belongsToMany association.

**Comment by bjrmatos** [comment]
didn't know about the `include.on` option, am i right to assume that it supports the same options that the `where` option object?

**Comment by mickhansen** [comment]
@bjrmatos It uses the same logic yes, it's not quite as well tested.

**Comment by bjrmatos** [comment]
thnks for your fast reply @mickhansen, until i can prepare a PR for #311 i will try to use the `include.on` option to generate a condition like this `on table1.itemId = table2.itemId and table1.typeId = table2.typeId` i think i will need to build a `where` object using `Sequelize.where` and use that object for the value of `include.on`

**Comment by mickhansen** [comment]
@bjrmatos You can try:

```js
on: {
  '$table1.itemId': {$col: 'table2.itemId'},
  '$table1.typeId': {$col: 'table2.typeId'}
}
```

**Comment by bjrmatos** [comment]
@mickhansen thnks i will try that way!

**Comment by saavedrajl** [comment]
Marca.hasMany(Modelo, { foreignKey: 'idmarca' });
Modelo.belongsTo(Marca, { foreignKey: 'idmarca' });

Modelo.hasMany(Modem, { foreignKey: 'idmodelo' });
Modem.belongsTo(Modelo, { foreignKey: 'idmodelo' });

Marca.findAll({
    include : [{
    	model: Modelo, 
    	required: true ,
    	on: {
    		'idmarca': {$col: 'Marca.idmarca'}
    	},
    	include: [{
    		model: Modem,
    		required: true,
    		on: {
	    		'idmodelo': {$col: 'Modelos.idmodelo'}
    		}
    	}]
    }],
}).then(function(result) {
	console.log(JSON.stringify(result))
})

**Comment by saavedrajl** [comment]
SELECT 
	`Marca`.`idmarca`, 
	`Marca`.`nombre`, 
	`Marca`.`estado`, 
	`Modelo`.`idmodelo` AS `Modelo.idmodelo`, 
	`Modelo`.`idmarca` AS `Modelo.idmarca`, 
 	`Modelo`.`nombre` AS `Modelo.nombre`, 
 	`Modelo`.`estado` AS `Modelo.estado`, 
 	`Modelo.Modem`.`idmodem` AS `Modelo.Modem.idmodem`,
 	`Modelo.Modem`.`idmodelo` AS `Modelo.Modem.idmodelo`, 
 	`Modelo.Modem`.`nombre` AS `Modelo.Modem.nombre`, 
 	`Modelo.Modem`.`estado` AS `Modelo.Modem.estado` 
FROM `marca` AS `Marca` 
INNER JOIN `modelo` AS `Modelo` 
	ON `Modelo`.`idmarca` = `Marca`.`idmarca` 
INNER JOIN `modem` AS `Modelo.Modem` 
	ON `Modelo.Modem`.`idmodelo` = `Modelos`.`idmodelo`;

**Comment by saavedrajl** [comment]
SELECT 
	`Marca`.`idmarca`, 
	`Marca`.`nombre`, 
	`Marca`.`estado`, 
	`Modelos`.`idmodelo` AS `Modelos.idmodelo`, 
	`Modelos`.`idmarca` AS `Modelos.idmarca`, 
 	`Modelos`.`nombre` AS `Modelos.nombre`, 
 	`Modelos`.`estado` AS `Modelos.estado`, 
 	`Modelos.Modems`.`idmodem` AS `Modelos.Modems.idmodem`, 
	`Modelos.Modems`.`idmodelo` AS `Modelos.Modems.idmodelo`, 
	`Modelos.Modems`.`nombre` AS `Modelos.Modems.nombre`, 
	`Modelos.Modems`.`estado` AS `Modelos.Modems.estado` 
FROM `marca` AS `Marca` 
INNER JOIN `modelo` AS `Modelos` 
	ON `Modelos`.`idmarca` = `Marca`.`idmarca` 
INNER JOIN `modem` AS `Modelos.Modems` 
	ON `Modelos.Modems`.`idmodelo` = `Modelos`.`idmodelo`;

**Comment by mickhansen** [comment]
@saavedrajl Please format your code, please include error traces, please describe your issue at all.

**Comment by atulhm** [comment]
Just found this issue.  @bjrmatos @mickhansen I'm about to tackle #311 but if you've made some progress on it, would you like some support/collaborate on it?

**Comment by sepans** [comment]
Hello,

Is `include.on` still not supported for `belongsToMany` relations or am I doing something wrong bellow?

For my models I have:
```js
module.exports = (sequelize, DataTypes) => {
  const Question = sequelize.define('Question', {
    title: DataTypes.STRING,
    /* ... */

  }, {});
  Question.associate = function(models) {
    Question.belongsToMany(models.User, { through: models.UserResponse, foreignKey: 'questionId' })
  };
  return Question;
};

module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    username: DataTypes.TEXT
    /* ... */
  }, {});
  User.associate = function(models) {
    User.belongsToMany(models.Question, { through: models.UserResponse, as: 'answers', foreignKey: 'userId' })
  };
  return User;
};

module.exports = (sequelize, DataTypes) => {
  const UserResponse = sequelize.define('UserResponse', {
    response: DataTypes.INTEGER,
    deleted: DataTypes.BOOLEAN
  }, {});
  return UserResponse;
};
```

And in query I have:
```js
sequelize.User.findByPk(userId, {
  include: [{
    model: db.Question,
    as: 'answers',
    on: {
      '$UserResponses.deleted': false
    }
  }]
})
```

But still not getting the `deleted` part. I get:
```sql
SELECT ... FROM "Users" AS "User"
LEFT  JOIN ( "UserResponses" AS "answers->UserResponse" 
LEFT JOIN "Questions" AS "answers" 
ON "answers"."id" = "answers->UserResponse"."questionId") 
ON "User"."id" = "answers->UserResponse"."userId"
```

where I want to get something like:
```sql
SELECT  ... FROM "Users" AS "User" 
LEFT  JOIN ( "UserResponses" AS "answers->UserResponse"
LEFT JOIN "Questions" AS "answers" 
ON "answers"."id" = "answers->UserResponse"."questionId" 
AND "answers->UserResponse"."deleted" = false) /* <--- */
ON "User"."id" = "answers->UserResponse"."userId"
```
