### ISSUE TITLE
Support for MSSQL Connection URL/URI

### ISSUE THREAD

**Issue by akanieski** [sequelize/sequelize#5557]
I haven't been able to get my MSSQL connection urls to work. 

`mssql://user:password@host.com:port/dbname`

Is this supported?

**Comment by mickhansen** [comment]
It should work for all dialects since we parse the URI at top level.

**Comment by agustinleiraCDS** [comment]
I couldn't make it work neither.

**Comment by sts-lauri** [comment]
> I couldn't make it work neither. Does anyone have this method working?

@agustinleiraCDS I had an issue with this, but it turned out to be a malformed URI error, which is resolved with this:

```
require("dotenv").config();
const { Sequelize } = require("sequelize");
const yourDatabaseConnector= new Sequelize(
  encodeURI(process.env.YOUR_DATABASE_URL),
  {}
);
```

In the above example, your .env URI needs to look like this:

`YOUR_DATABASE_URL=mssql://username:password@domain:port`
