### ISSUE TITLE
Using limit and offset causes error due to the security fix

### ISSUE THREAD

**Issue by DanMMX** [sequelize/sequelize#5560]
sequelize@3.19.3

[Here](https://gist.github.com/DanMMX/d85d1da6c89e9921caec) are my models, associations and queries.

You can notice `DESC LIMIT \'0\', \'10\'` and `AND `Payments`.`payingModel` = \'sale\'` are causing the errors, if I remove those `\'` on the limits and the `\` on the sale the errors go out

**Comment by mickhansen** [comment]
You need to pass integers to offset/limit.
Use parseInt or validate the input you're receiving.
