### ISSUE TITLE
Support "SELECT ... FOR UPDATE OF table"

### ISSUE THREAD

**Issue by soulchild** [sequelize/sequelize#5564]
Sequelize already supports `SELECT ... FOR UPDATE`, but when joining tables you have to be more specific, which tables you want to lock for update. PostgreSQL allows this via `SELECT ... FOR UPDATE OF <table>`. Could Sequelize's current lock feature be extended to support this as well?

**Comment by mickhansen** [comment]
We could extend `LOCK.UPDATE` to also support `LOCK.UPDATE(Model)`. If lock `=== UPDATE` then do regular FOR UPDATE, if `lock instanceof UPDATE` do `FOR UPDATE OF ${Model.tableName}`

**Comment by mickhansen** [comment]
Or should it just default to always use `UPDATE OF [select table]`?

**Comment by soulchild** [comment]
Cool! IMHO, the table/model should be configurable as there might be use-cases where you want to lock a joined table.

**Comment by mickhansen** [comment]
Agreed. If you could provide a pull request based on the API we discussed that would be great.

**Comment by soulchild** [comment]
Or maybe, [this](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1568) already does exactly what I want ... :smile: So I'm closing this issue with an example:

```js
Order.findAll({
  where: {
    'status': 'closed' 
  },
  include: [{
    model: OrderTransaction,
    required: false,
  }],
  transaction: t,
  lock: {
    of: Order,
  }
});
````
will produce the following query:

```sql
SELECT ... FROM "Orders" AS "Order" LEFT OUTER JOIN "OrderTransactions" AS "OrderTransaction" ON "Order"."id" = "OrderTransaction"."OrderId" FOR UPDATE OF "Order";
```

**Comment by mickhansen** [comment]
So it does :)
