### ISSUE TITLE
conditional transactions

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#5567]
Hi,

I often have a situation where I've create a function that executes multiple queries that should belong to the same transaction. However, when this function is used inside another function that must also execute in a single transaction, I'd like all queries in both functions to use the same transaction. In other words, I need to start a transaction or use an existing one.

What is the best way to accomplish this. I've been doing something like the following:

```javascript
class  SomeService {
        create(data, options) {
            // ensure transaction
            const transaction = options && options.transaction ? options.transaction : null;
            if (transaction) {
                return this._create(data, { transaction });
            } else {
                return sequelize.transaction(t => {
                    return this._create(data, { transaction: t });
                });
            }
        }

        _create(data, options) {
            // some series of DB queries...
        }
}
```

I'd love to be able to just do something like the following:
```javascript
class  SomeService {
        create(data, options) {
                return sequelize.transaction(options.transaction, t => {
                        // some series of DB queries...
                });
        }
}
```

Is something like this available?

Thanks!

**Comment by mickhansen** [comment]
`transaction` takes a transaction as an option, but that tells the system you want a nested transaction, not to reuse.

The simplest solution is for you to simply write your own method for creating new transactions or reusing if passed one.
