### ISSUE TITLE
raw: true inside findAll returning duplicate results inside promise.

### ISSUE THREAD

**Issue by jamesone** [sequelize/sequelize#5570]
So I for some reason using raw: true in findAll() will return duplicate results.

```
Post.findAll({
			include: [
	            { model: User  },
	            { model: Comment },
	        ],
	        where: 
	        {
	        	city: city,
	        	$or: typeIds,

	        },
	        order: [
	        	['createdAt', 'DESC'],
	        	['typeId', 'DESC'],
	        ],
	        limit: limit,
	        raw: true,
	        offset: offset,
		}).then(function(posts){
			console.log(posts); // Returns duplicate posts (post) objects
			res.json(JSON.stringify({posts, nextUrl: local_url+"post/"+city+"/?offset="+nextOffset+"&latestId="+nextId+queryParams}));
		}).catch(function(err){
			res.json(JSON.stringify({error: "Something went wrong"}));
			console.log(err);
		});
```

- In my database, I've got no duplicate typeIds, I've checked. 

I just thought I should let everyone know that this may be a possible bug. It's an easy fix, just remove raw: true from your constructor.

**Comment by mickhansen** [comment]
If you use `raw: true` we don't do deduplication of the result so you're getting back the cartesian product.

**Comment by potatosenior** [comment]
Is there a way to use `raw: true` in `findAll` without diplicated results?

**Comment by ephys** [comment]
You'd have to handle it manually afterwards as the point of raw is to give you what we receive from the database as-is
