### ISSUE TITLE
How to get multiple result sets by calling a stored procedure using sequelize?

### ISSUE THREAD

**Issue by Jeff534** [sequelize/sequelize#5572]
I noticed someone asked the same question, but not answered. Want to try this question here. 
To help understanding my question, the code below is an example to call stored procedure using sequelize:

sequelize.query(`CALL GetLatestNews();`,
  { 
      type: sequelize.QueryTypes.RAW
  })
  .then(function(results) {
    console.log(JSON.stringify(results));
  })

The stored procedure returns 3 result sets. However, only the first result set being returned. 

I tried to change the line 
.then(function(results) { 
to 
.spread(function(results, metadata) {

This time, results is holding only the first row of the first result set, while metadata holding the second row of the first result set. 

Any help is highly appreciated!

**Comment by janmeier** [comment]
Can you give an example of a stored procedure which returns multiple result sets / or a [SSCCE](HTTP://SSCCE.ORG/)? I don't have much experience with stored procs, so I don't really have a good case to test this

**Comment by Jeff534** [comment]
Here is a very basic stored procedure example in MySQL:

CREATE PROCEDURE `SearchOrderInfo`(
)
BEGIN

	SELECT * FROM users ORDER BY name;

	SELECT * FROM orders;

	SELECT * FROM products;

END

Hope that helps. And thanks a lot for looking into this issue.

**Comment by indrajeet0510** [comment]
I don' think so sequelize is having this kind of problem. 

First you have to make sure that **multipleStatements**  should be true.
Next whenever your procedure is returning more than one result set, your code should look like this

```
var query = "CALL someprocedure(:userId,:status)";
sequelize.query(query,{ replacements : { userId : userId, status : status}, type : sequelize.QueryTypes.SELECT}
```

I got multiple resultset into same results in array form using this.

**Comment by janmeier** [comment]
@indrajeet0510 Are you sure you need `multipleStatements` - as far as I recall, that is needed if you want to execute multiple queries in one go (e.g. `SELECT * FROM user; SELECT * FROM task`).

In any case, thanks for chiming in, I'll close this :)

**Comment by ghiden** [comment]
I can confirm that ```multipleStatements``` is not necessary on mysql.
But I did need to specify ```type``` as ```QueryTypes.SELECT```.

**Comment by manikmi** [comment]
Is there a way to return the SP into a model. like we do for table.

**Comment by rkumar1904** [comment]
this is fix for me!: 
```javascript
 sequelize.query('CALL getUnitData(' + queryData + ');', { type: sequelize.QueryTypes.SELECT })
        .then(entity => {
            var Unit = Object.keys(entity[0]);
            var UnitList = [];
            for (var i = 0; i < Unit.length; i++) {
                UnitList.push(entity[0][i]);
            }
            var Fyear = Object.keys(entity[1]);
            var FyearList = [];
            for (var j = 0; j < Fyear.length; j++) {
                FyearList.push(entity[1][j]);
            }
            return res.status(200).json({ "UnitList": UnitList, "FyearList": FyearList });
        }).catch(handleError(res));
```

**Comment by mshaikh-cci** [comment]
For me entity  is returning the merged result and not seperate arrays from SP.
I am using nodejs, sequelize and sql server
        model.sequelize.query('AssetCountAsPerStatus', { multipleStatements: true, type: model.sequelize.QueryTypes.SELECT })
            .then(data => {
                console.log('data', data);
                var res_1 = Object.keys(data[0]);
                var res_1_List = [];
                for (var i = 0; i < res_1.length; i++) {
                    res_1_List.push(data[0][i]);
                }

                var res_2 = Object.keys(data[1]);
                var res_2_List = [];
                for (var j = 0; j < res_2.length; j++) {
                    res_2_List.push(data[1][j]);
                }
                return res.status(200).json({ "res_1_List": res_1_List, "res_2_List": res_2_List })
            })
