### ISSUE TITLE
Support question - update one

### ISSUE THREAD

**Issue by ORESoftware** [sequelize/sequelize#5573]
hey all, new to this lib so forgive me for noob question

looking through the basic docs

http://docs.sequelizejs.com/en/latest/docs/querying/

I am looking for a way to do an updateOne call or updateById:

```js
Post.update({
  updatedAt: null,
}, {
  where: {
    deletedAt: {
      $ne: null
    }
  }
});
```

is there a way to update by id or run an updateOne?
Seems a lot more efficient for the query to return after updating the first row etc.

thanks

**Comment by mickhansen** [comment]
Use `where: {id: id}` to update by id, you can apply `limit: 1` to update a single row (although postgres does not support limits so it will do a IN SUBQUERY)

**Comment by mautematico** [comment]
>although postgres does not support limits so it will do a IN SUBQUERY

Could you please elaborate furter on this part? Does that mean that it would be cost ineficient (but still a valid solution) to use `limit: 1`  in postgres for this propouse, or does it mean that we need to find a workarround?

`
                const usuario_email = 'email@example.org';
                const transaction_hash = 'superlongtxhash'; 

                Retiro.update({ usuario_email, transaction_hash }, {
                    where: {
                        usuario_email: null,
                        transaction_hash: null,
                        monto: 100,
                    },
                    returning: true,
                    limit: 1
                }).then(
                    r =>
                        console.log(JSON.stringify(r)),
                    e =>
                        console.log(JSON.stringify(e)));
`
¡Gracias!

**Comment by mautematico** [comment]
http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-update

> options.limit | Number | optional | How many rows to update (only for mysql and mariadb, implemented as TOP(n) for MSSQL)

It seems we need to find a workarround for the postgres case, like doing a findOne() and then the update itself, although that seems not to be atomic.
