### ISSUE TITLE
invalid node exit code when an exception is thrown and not caught

### ISSUE THREAD

**Issue by xdarklight** [sequelize/sequelize#5576]
I have a command-line script which uses sequelize as ORM.
Most of my database functions do not have .catch() handlers since there's not much I could do in those cases.
However, when running into an uncaught exception I'd assume that the exit code is 1 (or at least != 0).

example code:
```js
var Sequelize = require('sequelize');

var sequelize = new Sequelize("", "", "", { dialect: "sqlite", storage: "./database.sqlite" });

var Foo = sequelize.define('foo', {
	foo: {
		type: Sequelize.STRING,
		allowNull: false,
		validate: {
			notEmpty: true
		}
	},
});

Foo.sync({ force: true }).then(function() {
	Foo.create({ foo: "" }).then(function() {
		
	});
});
```

run it with:
```bash
npm install sequelize sqlite3 && node main.js; echo $?
```

expected output: an exit code other than 0
actual output: script exits with status 0 (= success)

I did not find out how to write an automated integration-test for this.
Let me know if you think that it's possible to write such a test (and give some hints) - then I'll give it a go.

**Comment by mickhansen** [comment]
You need to throw the uncaught exception, with bluebird you can add a handler for uncaught exceptions and then rethrow to the process. You'll have a non-zero in that case. In this instance the uncaught is just logged.

**Comment by xdarklight** [comment]
thanks @mickhansen 

in case anyone else is interested, here's the "fix":
```
process.on("unhandledRejection", function(exception, promise) {
    throw exception;
});
```
see also: http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events
