### ISSUE TITLE
returned to promise but still gets warning

### ISSUE THREAD

**Issue by 1mp4cty** [sequelize/sequelize#5577]
I got these warnings even if I return to handler promise

Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Instance.save (/Users/Tulgaa/Projects/webProject/server/node_modules/sequelize/lib/instance.js:567:18)
    at Model.create (/Users/Tulgaa/Projects/webProject/server/node_modules/sequelize/lib/model.js:1824:6)
    at /Users/Tulgaa/Projects/webProject/server/auth/local/index.js:32:10

    router.post('/', function(req, res, next){

    var newUser = User.build(req.body);
    newUser.setDataValue('provider', 'local');
    newUser.setDataValue('role', 'user');
    newUser.save()
      .then(function (user) {
        req.logIn(user, function(err){
          if (err){
            console.log('Error in req.logIn',err);
          }
        })
        res.status(200).json({ message: 'success' });
        return null
      })
      .catch(function(err) {
        if (err){
          console.log('Error in newUser.save()',err);
          res.status(500).json({ message: 'error' });
        }
        return null;
      });

**Comment by mickhansen** [comment]
Known issue, search for existing issues.
The issue is usually in your own code though.
