### ISSUE TITLE
Error when adding a `where` to an include when included model has not entries

### ISSUE THREAD

**Issue by faceleg** [sequelize/sequelize#5578]
I have a tree that has categories. 

 - Each category may have child categories. 
 - Root level categories are those categories where `categoryId` is `null`.

When retrieving the tree, I want the first level categories eagerly loaded. 

When listing trees for a given user, have to do some funky joining to get the correct trees, so I use a custom query to get the initial tree list, then loop over this list calling `reload` with an includes block to populate the trees how I need them. _Suboptimal? Likely but let's please ignore that aspect for now_.

I'm getting the following error when I added a `where` clause to the `categories` portion of my reload includes block, but only when the tree in question has no categories associated with it:

>  SequelizeInstanceError: Instance could not be reloaded because it does not exist anymore (find call returned null)

My tree reload code:

```JS
tree.reload(
    include: [
      {
        model: Category,
        as: 'categories',
        where: {
          categoryId: {
            $eq: null
          }
        }
      }
    ]
  });
```

**Comment by mickhansen** [comment]
`reload` with `include` is not well tested, but it should just work since it uses a find internally.

**Comment by janmeier** [comment]
But its probably because the reload query does not return any results at all - Which makes sequelize think that the row has been deleted. Try adding `required: false` to the incldue

**Comment by faceleg** [comment]
Thanks for the response. I'll test your suggestion @janmeier tonight.

**Comment by faceleg** [comment]
Works! This is much nicer than post-processing the categories list to remove non-root categories. Thanks!

Is this something I should have known, or is it a quirk of the library?

**Comment by mickhansen** [comment]
@faceleg Bit of both i suppose, the include logic is correct, but it just messes with reload since it always expects a row.

**Comment by janmeier** [comment]
It's mentioned [here](http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance) - though there are a lot of options for includes, so its hard to know them all ;)

Basically, adding a where turn the include to an inner join, which means it only returns parent rows, if the child matches. `required` turns it back to a left join

**Comment by faceleg** [comment]
<3 this library, in no small part due to the responsive maintainers :)

**Comment by faceleg** [comment]
I've found it intuitive enough that I seldom need to look at the docs. Which in this case resulted in my foot being blown off :package:
