### ISSUE TITLE
Cannot use association on the result of findOrCreate

### ISSUE THREAD

**Issue by todorus** [sequelize/sequelize#5580]
version 3.19.2

I have a model that has a belongsToMany relationship with itself and while I was trying to use findOrCreate() I ran into a difference in behaviour with the findOne() and create() methods.

```
var RegionToRegion = sequelize.define('RegionToRegion', {});

  var Region = sequelize.define('Region', {
    name: {
      type:DataTypes.STRING,
      unique: "compIndex"
    },
    type: {
      type: DataTypes.INTEGER,
      unique: "compIndex"
    },
    description: DataTypes.TEXT
  });

  Region.belongsToMany(
    Region,
    {
      as: 'Parents',
      foreignKey: 'ChildId',
      through: RegionToRegion
    }
  );

  Region.TYPE_ZIP = 1;
  Region.TYPE_PLACE = 100;
  Region.TYPE_MUNICIPALITY = 200;
  Region.TYPE_PROVINCE = 300;


  return Region;
```

When I try to call addParent() on the result of findOrCreate(), then it throws an error, stating the function addParent() is undefined. When I try to call addRegion() on the result of findOne() or create() I am able to call addParent() and the join table gets the correct record added.

I would expect that when I call a method on Region that returns a Region object, that I can always use the defined associations as well. At the moment findOrCreate() does not seem to honour that expectation. If this is expected behaviour, I would really like to see it documented.

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/api/model/#findorcreateoptions-promiseinstance-created findOrCreate returns an array of instance, created
