### ISSUE TITLE
Combining array values in scopes

### ISSUE THREAD

**Issue by itsravenous** [sequelize/sequelize#5581]
We would love to be able to specify how array values on the same property in different scopes are handled. For instance, we have a convention for access control of adding a scope named "user" on the model which takes a user argument and applies a where filter. A contrived example:

tasks.js:
```javascript
scopes: {
  user: function (user) {
    var allowed_categories = user.task_categories.map(function (task_category) { return task_category.id });
    return {
      where: {
        category: {
          $in: allowed_categories
      }
    }
  }
```

This works really well because it means that tasks included from another model's find (e.g. projects) automatically have the access control applied as well. The problem is, if we add another scope on the tasks model:

```javascript
scopes: {
  user: function (user) {
    var allowed_categories = user.task_categories.map(function (task_category) { return task_category.id });
    return {
      where: {
        category: {
          $in: allowed_categories
      }
    },
    // Only show tasks from certain categories
    by_category: function (ids) {
      return {
        where: {
          $in: ids
        }
      }
    } 
  }
```

then the "user" scope will always override whatever ids are passed to the "by_category" scope. This is good in one way, because the user will never be able to see tasks in categories which they aren't allowed to see. On the other hand, if a user legitimately wants to pass a subset of the category ids they're allowed to see then the user scope will override their choice and show them tasks from all the categories.

It would be great to be able to specify a merge method for the arrays, e.g. intersect (which is what we'd want to do in this case).

I'm happy to look at doing a PR, but I wanted to check whether you thought this fit within the design of Sequelize.

I should mention that the scopes on our models get used to generate URI templates for our API, so for the above imaginary model, our app would facilitate URIs something like:

http://example.com/api/tasks/
http://example.com/api/tasks/?by_category=1&by_category=2

We generate a lot of the routing logic solely from the models - we're writing a new frontend for an existing database and there are literally hundreds of tables. I realise if we weren't doing that it would be easy to simply add a where clause in, say, the controller for the tasks route to do the access control.

**Comment by mickhansen** [comment]
This would require that scope knows about nested fields that it provides.
Perhaps we could simply provide a generic function that let's users do their own merge logic for scopes.

/cc @janmeier

**Comment by itsravenous** [comment]
That would be a great alternative too, and I think this is probably a better fit for my strange use case (i.e. I'm the one doing something weird, so give me a way to completely change how things work, rather than try and make Sequelize bend over backwards to fit my specific needs). Look forward to thoughts on that, and as I said happy to write you a PR if I can figure it out.

**Comment by mickhansen** [comment]
I think it's the way to go.
I'm thinking it should probably be an option for the model (i don't see any other alternatives).

It could then be checked and called here: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2674
The question is whether or not the original merging logic should be used at all, probably not. In that case we probably want to pull out the individual scope merge logic into public function so they can be used (probably be enough with mergeScopeOptions and mergeScopeInclude).

**Comment by janmeier** [comment]
Shouldn't you rather be able to override `scopeCustomizer` https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1221 

(We might need both actually, since you might both want to customize how several scopes are merged, and how scope and regular options are merged)

**Comment by mickhansen** [comment]
@janmeier One method could handle both in theory since it's always the same set of options being merged.

**Comment by itsravenous** [comment]
Sorry this has been sitting here for so long. I just took a look at the 4.0.0 source code and couldn't immediately see where to start (I think the `scopeCustomizer` method listed above has since been [re]moved).

For my specific use case, I've found the following workaround to be sufficient, because I know the access control (`user`) scope is always applied last (though this obviously doesn't solve the general case):

```javascript
scopes: {
  user: function (user) {
    var proposed_categories = this.$scope.where.category.$in // Should also handle if it's set as an array without "$in"
    var allowed_categories = user.task_categories.map(function (task_category) { return task_category.id });
    var proposed_categories_screened = allowed_categories.filter(cat => return proposed_categories.includes(cat));

    if(!proposed_categories.length) throw new Error('No access to those categories');

    return {
      where: {
        category: {
          $in: proposed_categories
      }
    },
    // Only show tasks from certain categories
    by_category: function (ids) {
      return {
        where: {
          $in: ids
        }
      }
    } 
  }
```

Closing since no-one else has asked for the general case.
