### ISSUE TITLE
update() after failed update() does not validate nor execute

### ISSUE THREAD

**Issue by mattecapu** [sequelize/sequelize#5584]
This is my reduced test case
```js
import * as Sequelize from './schema';

const o = Sequelize.Place.findById(1);
let a;
const nop = (err) => {
    console.log('ignore this error');
    return a;
};
o.then(x => {
    a=x;
    return a;
}).then(x => x.update({
    location: null
})).catch(nop).then(x => x.update({
    location: {lat: 5, long: -443}
})).catch(nop).then(x => x.update({
    location: {lat: 5623, long: -43}
}));
```
Here `location` is a virtual field that sets the `locationLatitude` and `locationLongitude` (real) fields, which are **not-null fields with custom validators**.
The first update fails because the "children" fields cannot be null. The error is ignored and the same instance is used to try a new update with invalid data.
**Expected**: data rejection by validation.
**Observed**: data is never validated and the update never performed

**Possible reason**: 
Looking at the update method [here](https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L785):
```js
// Now we need to figure out which fields were actually affected by the setter.
sideEffects = _.without.apply(this, [this.changed() || []].concat(changedBefore));
fields = _.union(Object.keys(values), sideEffects);

if (!options.fields) {
  options.fields = _.intersection(fields, this.changed());
  options.defaultFields = options.fields;
}

return this.save(options);
```
After the first update (which fails to validate), the fields that were going to be updated are still flagged as changed, thus despite the custom setters should cause `sideEffects` to be `['locationLatitude','locationLongitude']`, they are removed by `_.without` and thus the intersection with `fields` becomes empty. Then `save()` tries to save... nothing: that's why I get no validation errors and no query execution either.

I found adding a simple error handler for the rejection which reverts all the changes made to the objects attributes solves the issue for my test case. This code would replace the last line of `update()`
```js
var self = this;
return this.save(options).catch(function(error) {
    options.fields.forEach(function(field) {
        self.changed(field, false);
        self.setDataValue(field, self.previous(field));
    })
    throw error;
});
```
It's a naive solution because I don't know all the edge cases, and honestly I tried my best guess based on what I learned hunting down the bug.
As soon as someone approves this fix (or instructs me on how to do it properly) I'll be happy to open a PR.

**Comment by mickhansen** [comment]
On a failed save the changed fields should be preserved as the `set` part should still have happened (when an update)

**Comment by mattecapu** [comment]
Mmmh, yes, but I didn't explicilty call `set` (you could say is a side-effect, albeit a predictable one) so I expect `update` to be atomic in that sense, without polluting the instance object.
Anyway, I think we can agree that changing again the fields should trigger everything it triggered before.
Possibly the issue is more fundamental, in the way changed attributes are detected? From what I've seen, the fields are flagged changed or not, and not actually compared (in `changed` method at least).
But I might (and I'm probably) wrong.

**Comment by mickhansen** [comment]
They are flagged based on them being different on set.
`update` being atomic would probably be more ideal, but is not practical with the current way saves work.

**Comment by mattecapu** [comment]
Should I fetch a new instance every time an update fails to validate then?

**Comment by mickhansen** [comment]
No, that does not sound like the ideal option :)
