### ISSUE TITLE
Where clause for left column in LEFT OUTER JOIN

### ISSUE THREAD

**Issue by saadullah-aleem-10p** [sequelize/sequelize#5594]
I'm trying to translate this query in sequelize:

```SQL
SELECT users.id as uid, connections.id as connid, circleId, initiatorId, 
mainUserId, otherUserId, status 
FROM users 
LEFT OUTER JOIN connections on users.id = connections.mainUserId 
WHERE connections.otherUserId = 1 and users.id = 2;
```

This is my criteria object:

```javascript
let criteria = {
    attributes: ['mainUserId'],
    where: {'otherUserId': payload.initiatorId, 'user.id': payload.otherUserId},
    include: [
      {model: models.User, attributes: ['id'], paranoid: false, required: false, where: {}}
    ],
    raw: true
  };
```

But the query I get is the following:

```SQL
SELECT `connection`.`mainUserId`, `user`.`id` AS `user.id` 
FROM `connections` AS `connection`      
LEFT OUTER JOIN `users` AS `user` ON `connection`.`otherUserId` = `user`.`id` 
WHERE `connection`.`otherUserId` = 1 AND `connection`.`user.id` = 3 LIMIT 1;
```

And the error message says:
> "ER_BAD_FIELD_ERROR: Unknown column 'connection.user.id' in 'where clause'

I don't get it. From the examples I've seen, the where clause should work.

Also, sequelize automatically joins on 'otherUserId'. I want to join on 'mainUserId', how could I accomplish that?

**Comment by saadullah-aleem-10p** [comment]
Ok, so I found out how to get the user.id key to be considered a key of the other table by wrapping it in $ signs. The criteria object now looks like this:

```javascript
  let criteria = {
    where: {'otherUserId': payload.initiatorId, '$user.id$': payload.otherUserId},
    include: [
      {model: models.User, attributes: ['id'], paranoid: false, required: false}
    ],
    raw: true
  };
```

And the following query is generated 

```SQL
 SELECT `connection`.`id`, `connection`.`visibility`, `connection`.`circleId`, 
`connection`.`status`, `connection`.`createdAt`, `connection`.`updatedAt`, 
`connection`.`initiatorId`, `connection`.`mainUserId`, `connection`.`otherUserId`,
 `user`.`id` AS `user.id` 
FROM `connections` AS `connection` LEFT OUTER JOIN `users` AS `user` 
ON `connection`.`otherUserId` = `user`.`id` 
WHERE `connection`.`otherUserId` = 1 AND `user`.`id` = 2 LIMIT 1;
```

**Comment by mickhansen** [comment]
Correct, to reference other columns in a where key they need to be wrapped in `$` so we know that this needs to be broken down before being escaped.

Any other issues or can we close?

**Comment by saadullah-aleem-10p** [comment]
Yes, I've three columns in connection that refer to the users table. Here, sequelize uses otherUserId for the left join even though I did not mention it anywhere. How do I make it join using initiatorId or mainUserId.

**Comment by mickhansen** [comment]
You need to configure your association to use those keys.
