### ISSUE TITLE
Changes don't tracked in model in JSON/JSONB/ARRAY

### ISSUE THREAD

**Issue by SerjoPepper** [sequelize/sequelize#5597]
Hi
Suppose I have follow object
```
db.define 'Item', {
  name: Sequelize.TEXT
  tags: 
    type: Sequelize.ARRAY
    defaultValue: []
}
```
When I change field in instance and save it
```
item.tags.push('black')
yield item.save()
```
changes don't track and field tags not saving, i think it's because you compare fields by link, not deeply.

**Comment by mickhansen** [comment]
For regular sets you can use `item.set('nested.key', value)`, for arrays you'll have to call `item.changed('tags', true)`.

We don't compare on read, we compare on set.

**Comment by PavelPolyakov** [comment]
another version of updating the array:
https://github.com/sequelize/sequelize/issues/3819#issuecomment-376930468
