### ISSUE TITLE
Sequelize swallows error when using incorrect includes

### ISSUE THREAD

**Issue by DeX3** [sequelize/sequelize#5598]
When it comes to more complex queries, I often resort to using `sequelize.query`. By passing the includes as options to the functions, sequelize will properly parse them into sequelize models. The approach is working nicely, there's only one problem (at least for the mysql-dialect which I am using):

When I pass in an incorrect include into `sequelize.query`, the `formatResults` function will throw synchronously. In `lib/dialects/mysql/query.js`, `run` simply ignores this and swallows the error.

A possible solution would be to wrap the call of `formatResults` in a try-catch and reject the promise when an error is called, or simply use something like [Promise.try](http://bluebirdjs.com/docs/api/promise.try.html) or [Promise.method](http://bluebirdjs.com/docs/api/promise.method.html).

**Comment by mickhansen** [comment]
Ideally i'd love to offer most of what findAll does to raw queries, i.e. parsing results with includes.
So it would probably be better to duplicate some of the include parsing to sequelize.query to make sure it's all correct.
