### ISSUE TITLE
Literal queries not getting evaluated on through attributes

### ISSUE THREAD

**Issue by xizhao** [sequelize/sequelize#5602]
In a belongsToMany association, Sequelize.literal attributes do not show up in the response:

```
...
include: [{
  model: ModelA,
  attributes: [[Sequelize.literal('3'), 'normaltest']], // Shows up in response as ModelA.normaltest: 3
  through: {
    attributes: [[Sequelize.literal('3'), 'throughtest']] // Does not show up
  }
}]
...
```

**Comment by xizhao** [comment]
A greater issue seems to be I am not able to specify which attributes are getting selected,

i.e. `attributes: ['attr1', 'attr2']` yields the same results at `attributes: ['attr1']`

**Comment by mickhansen** [comment]
Please move the second comment seperate issue and show some code that verifies it.

I can see definitely see mappings not working for through.attributes

**Comment by xizhao** [comment]
If #1 is a symptom of #2, should we just rename this issue to that?

**Comment by janmeier** [comment]
@xizhao I believe they are two separate issues

**Comment by PragnaGH** [comment]
I am using sequelize 5.2.1

I have used sequelize.literal in attributes but not working.
Throwing error 
attr[0].includes is not a function
    at attributes.map.attr (sequelize/lib/dialects/abstract/query-generator.js:1382:29)

when I removed the literal it is working.
But I want to calculate distinct count of an item.
like this:
Sequelize.literal('count(distinct('id'))')

**Comment by MarianyFerreira** [comment]
Up https://github.com/sequelize/sequelize/issues/5602#issuecomment-477148412
