### ISSUE TITLE
Empty array on belongsToMany

### ISSUE THREAD

**Issue by scripter-co** [sequelize/sequelize#5603]
I have a model setup like:

    var User = sequelize.define('User', {
            name: { type: Sequelize.STRING },
            facebook_id: { type: Sequelize.STRING, unique: true },
            facebook_token: { type: Sequelize.STRING }
        },{
            freezeTableName: true
        }
    );
    
    var Lounge = sequelize.define('Lounge', {
        name: { type: Sequelize.STRING }
        },{
            freezeTableName: true
        }
    );
    
    var LoungeUser = sequelize.define('LoungeUser', {
        is_admin: Sequelize.BOOLEAN
    });
    var UserAssoc = User.belongsToMany(Lounge, {through: LoungeUser, foreignKey: 'LoungeId'});
    var LoungeAssoc = Lounge.belongsToMany(User, {through: LoungeUser, foreignKey: 'UserId'});

I then try and fetch a row:

    Lounge.findById(123, {
        include: [ models.loungeAssoc, models.userAssoc ]
    });

The problem is that the object is returning `[]` for my joins:

    ...
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false,
    Users: [],
    Lounges: [] }

but the query does return rows:

[![][1]][1]

I've tried so many things and I just can't get it to work. I'm clearly missing something obvious.

  [1]: http://i.stack.imgur.com/jLSlw.png

**Comment by mickhansen** [comment]
You've logged the SQL and executed it manually and it returns those results?
That is odd.

**Comment by scripter-co** [comment]
@mickhansen yep, (there are other columns but not really needed to show them). It's making the join correctly, and returning the results (in raw SQL) so I don't get why they're not being mapped to the models. I assume my association definitions are incorrect?

The basic gist is that a `User` can have many `Lounge`s and many `Lounge`s belong to many `User`s, therefore I needed a join table (in this case `LoungeUser` which will contain which members are in which lounge.

**Comment by mickhansen** [comment]
Ah, your association foreign keys are inverted. foreignKey is the column holding the value pointing back at the source.

```js
var UserAssoc = User.belongsToMany(Lounge, {through: LoungeUser, foreignKey: 'LoungeId'});
var LoungeAssoc = Lounge.belongsToMany(User, {through: LoungeUser, foreignKey: 'UserId'});
```

should be

```js
var UserAssoc = User.belongsToMany(Lounge, {through: LoungeUser, foreignKey: 'UserId'});
var LoungeAssoc = Lounge.belongsToMany(User, {through: LoungeUser, foreignKey: 'LoungeId'});
```

**Comment by scripter-co** [comment]
@mickhansen so I correct that issue, dropped the joining table and re synced. The inserts are still OK:

    INSERT INTO "Lounge" ("id","name","createdAt","updatedAt") VALUES (DEFAULT,'test','2016-03-17 12:02:07.624 +00:00','2016-03-17 12:02:07.624 +00:00') RETURNING *;
    INSERT INTO "LoungeUsers" ("LoungeId","UserId","createdAt","updatedAt") VALUES (14,4,'2016-03-17 12:02:07.934 +00:00','2016-03-17 12:02:07.934 +00:00');
    INSERT INTO "LoungeUsers" ("LoungeId","UserId","createdAt","updatedAt") VALUES (14,2,'2016-03-17 12:02:07.940 +00:00','2016-03-17 12:02:07.940 +00:00');

(those userID's are correct)

but when I do the following:

    models
            	.lounge.findById(payload.id, {
                    include: [ models.userAssoc ]
                })
            	.then(function(results){
                    console.log(results);
                    console.log('-------');
                    results.getUsers().then(function(r){
                        console.log(r);
                    });
                    return;
                })
            ;

I get back:

console.log 1:
```
{ dataValues:
   { id: 14,
     name: 'test',
     createdAt: Thu Mar 17 2016 12:02:07 GMT+0000 (GMT),
     updatedAt: Thu Mar 17 2016 12:02:07 GMT+0000 (GMT),
     Users: [] },
```

console.log 2:

    []

Interestingly, when I do the `.getUsers()` the query is:

    SELECT "User"."id", "User"."name", "User"."facebook_id", "User"."facebook_token", "User"."createdAt", "User"."updatedAt", "LoungeUser"."is_admin" AS "LoungeUser.is_admin", "LoungeUser"."createdAt" AS "LoungeUser.createdAt", "LoungeUser"."updatedAt" AS "LoungeUser.updatedAt", "LoungeUser"."LoungeId" AS "LoungeUser.LoungeId", "LoungeUser"."UserId" AS "LoungeUser.UserId" FROM "User" AS "User" INNER JOIN "LoungeUsers" AS "LoungeUser" ON "User"."id" = "LoungeUser"."UserId" AND "LoungeUser"."LoungeId" = 16

and returns the correct two users:

![screen shot 2016-03-17 at 12 09 15](https://cloud.githubusercontent.com/assets/1334111/13845619/19d01ed6-ec39-11e5-8fab-a6b2351d20a9.png)
