### ISSUE TITLE
Model.update() ignores DataTypes validation

### ISSUE THREAD

**Issue by ghuenlee** [sequelize/sequelize#5607]
Hello.
I've recently started using sequelize, and it's pretty much my first post on github.
So, The first time I used sequelize, it was version 3.5.1. When trying to update a row with a set of attributes, it used to display an error if I passed a value of a different datatype than the one declared in the model.
Today, I updated to the latest, 3.19.x. I tried running my code again, and whenever I try passing a value with a different datatype than the one declared in the model, there is no error message and the invalid value is updated in the database.
I tried looking through the changelog on docs.sequelize, but I couldn't find anything related to this issue.

**Comment by mickhansen** [comment]
We had to roll back validations since they broke BC for a lot of users.
You can re-enable them with `typeValidation: true` in the Sequelize constructor.
