### ISSUE TITLE
Who is using sequelize in production?

### ISSUE THREAD

**Issue by youxiachai** [sequelize/sequelize#5608]
Someone want to know sequelize in production when I introduce sequelize.

Are there any Sequelize website?

**Comment by MrVoltz** [comment]
I'm using Sequelize in production (small website for local scouts) and other than the issue with equals, I haven't encountered any problems.

**Comment by mickhansen** [comment]
http://actimo.com/
http://snaplytics.io/
http://www.pumpup.com/ @garrett-gottlieb

**Comment by sushantdhiman** [comment]
3 with MySql and 1 with Postgres, Works great :)

**Comment by garrett-gottlieb** [comment]
Yeah, we're 100% dependent on Sequelize (Postgres 9.3.5 on Amazon RDS). Currently v3.3.2 and we'll likely upgrade soon. Hasn't had any issues yet at 100k+ concurrent users and 10k+ rps.

**Comment by mickhansen** [comment]
Closing, but people are still welcome to comment as a reference base.

**Comment by ahelord** [comment]
@garrett-gottlieb Friend where you placed the RDS configuration in Sequelize I can not get error and says that can not find the host.

**Comment by mickhansen** [comment]
@ahelord Nothing magical about setting up RDS in sequelize, you have to be more specific

**Comment by ahelord** [comment]
@mickhansen  Agree. I use a json configuration file for Sequelize. In the production environment should I put the rds endpoint on the host?

**Comment by mickhansen** [comment]
@ahelord Host can be any type of TCP accessable address, an IP or a address resolvable by DNS works

**Comment by wannymiarelli** [comment]
Using Sequelize in production for two different apps with 30k+ daily users. Beside all the critics it works for me :) and i doubt there is something better at this moment.

**Comment by sushantdhiman** [comment]
@wannymiarelli http://docs.sequelizejs.com/manual/faq/whos-using.html just a PR away :D

**Comment by wannymiarelli** [comment]
@sushantdhiman done ;)
