### ISSUE TITLE
SQLite: schema result of migration differs from schema result of sync() -- migration not adding UNIQUE(field) constraint

### ISSUE THREAD

**Issue by ghost** [sequelize/sequelize#5610]
## Software Versions

Ubuntu `14.04 x86-64`
Nodejs `5.4.1`
Sequelize `3.19.3`
SQLite `3.8.2`
## The problem

The table schema resulting from running migrations on sqlite3 differs from the auto-generated schema resulting from running `sequelize.sync ()`.

Specifically, the migrations don't add `UNIQUE(fieldname)` to the table creation SQL but `sync()` does.
## Exploration

I wrote a migration for a model:

``` javascript
// migrations/20160318180341-create_servers_table.js
'use strict';

module.exports = {
    up: function (queryInterface, Sequelize) {
        return queryInterface.createTable ('servers', {
            id: {
                type: Sequelize.INTEGER,
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: Sequelize.STRING,
                allowNull: false,
                unique: true // notice these-- they're the important part
            },
            address: {
                type: Sequelize.STRING,
                allowNull: false,
                unique: true // notice these-- they're the important part
            },
            last_heartbeat: {
                type: Sequelize.DATE,
                defaultValue: Sequelize.NOW
            },
            created_at: {
                type: Sequelize.DATE,
                allowNull: false,
                defaultValue: Sequelize.NOW
            },
            updated_at: {
                type: Sequelize.DATE,
                allowNull: false,
                defaultValue: Sequelize.NOW
            }
        });
    },

    down: function (queryInterface, Sequelize) {
        return queryInterface.dropTable ('servers');
    }
};
```

and the model is this:

``` javascript
// models/server.js
module.exports = function (sequelize, DataTypes) {
    var Server = sequelize.define ('Server', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        name: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true // notice these-- they're the important part
        },
        address: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true // notice these-- they're the important part
        },
        last_heartbeat: {
            type: DataTypes.DATE,
            defaultValue: DataTypes.NOW
        }
    }, {
        tableName: 'servers'
    });

    return Server;
};
```

and this is `models/index.js` which was auto-generated by sequelize_cli. I modified it to add the `sequelize.sync ()` call

``` javascript
// models/index.js
'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(module.filename);
var env       = process.env.NODE_ENV || 'development';
var config    = require(__dirname + '/../config/config.json')[env];
var db        = {};

if (config.use_env_variable) {
    var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
    var sequelize = new Sequelize(config.database, config.username, config.password, config);
}


fs.readdirSync(__dirname).filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
}).forEach(function(file) {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
});


Object.keys(db).forEach (function (modelName) {
    if (db[modelName].associate) {
        db[modelName].associate (db);
    }
});

// I added this
sequelize.sync ();

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```
1. No database existed when I ran the migrations like so: `node_modules/.bin/sequelize db:migrate`
2. The migration ran fine and the database was created at `database/database.sqlite3` as specified in my config (so I'm having no problems so far).
3. Then I opened up the database with sqlite3 on the command line to take a peek: `sqlite3 database/database.sqlite3`
4. then inside sqlite3: `.schema servers` spits out this:

``` sql
CREATE TABLE `servers` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `address` VARCHAR(255) NOT NULL UNIQUE,
    `last_heartbeat` DATETIME,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL
);
```

"Looks OK to me" I thought. But I've noticed that the `sync()` method auto-generates the tables slightly differently by putting in the `created_at` and `updated_at` fields but the migrations don't. So, since I'm paranoid I then did the following:
1. I deleted the database: `rm database/database.sqlite3`
2. then ran the nodejs app: `npm start`
3. Now, remember, inside `index.js` I'm calling `sequelize.sync()` so the database and all the tables were created just fine right?
4. I open up the database to make sure: `sqlite3 database/database.sqlite3`
5. Then check the table schema: `.schema servers` and it spits out this:

``` sql
CREATE TABLE `servers` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `address` VARCHAR(255) NOT NULL UNIQUE,
    `last_heartbeat` DATETIME,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    UNIQUE (name), UNIQUE (address)
);
```

_Notice that last line_ where it says `UNIQUE (name), UNIQUE (address)`! That wasn't there before when running the migration!

This discrepancy doesn't appear to break anything-- the `unique: true` validation works just fine. But the difference in table schema definition seems like something that needs to be ironed out so I thought I'd tell you guys.

I don't know if this is related to issue #2051 where @mickhansen said 

> @janmeier could we potentially fix this by not relying on inline unique indexes at all?

**Comment by mickhansen** [comment]
With `sync` `unique` is pulled into a seperate `model.indexes` field.
We definitely need to streamline sync/createTable. A model definition should be copy/pasteable to a createTable statement.

**Comment by doctorme** [comment]
This appears to be related:

I used sequelize_cli to create a seed: `node_modules/.bin/sequelize seed:create --name=seed_servers`

and here's the seeder file:

```javascript
// seders/20160321185917-seed_servers.js
'use strict';

module.exports = {
	up: function (queryInterface, Sequelize) {
		// this does not work
		// gives error "Seed file failed with error: Validation error" on the console.
		// further inspection using console.log() shows
		// that is a 'SequelizeUniqueConstraintError'
		return queryInterface.bulkInsert ('servers', [
			{ name: 'somewhere', address: 'localhost' }
		], {});
		/*
		* however, this DOES work
		*
		var models = require ('../models');
		return models.Server.bulkCreate ([
			{ name: 'somewhere', address: 'localhost' }
		]);
		*/
	},

	down: function (queryInterface, Sequelize) {
		// this works just fine
		return queryInterface.bulkDelete ('profiles', null, {});
	}
};
```

The comments should explain the situation.

Also, the documentation [here](http://docs.sequelizejs.com/en/latest/docs/models-usage/) was extremely sparse regarding how to do seeding so I don't know if I'm doing it "right" though I do have it working using the above workaround that I have commented out.
