### ISSUE TITLE
conditional columns, joins, and where clause parameters

### ISSUE THREAD

**Issue by mg1075** [sequelize/sequelize#5611]
In a node.js + postgresql environment, with sequelize as the orm, what is the best way to go about building a "dynamic" query?

Imagine the user has a web interface where he/she can select what fields to output in a report and apply any conditions (=, <>, >, <, etc.) for filtering the field. 

Depending on the fields selected, table joins may be needed.

In the web interface you could generate the values for the parameters, but for building the query on the server, can sequelize help? A few github issues seem to suggest _not_. If not, then how would one go about this task in this environment?

The query building issue is referred to here:
https://github.com/sequelize/sequelize/issues/394

...and in this issue, the OP says he went with Knex.
https://github.com/sequelize/sequelize/issues/4026

**Comment by mickhansen** [comment]
`where` in sequelize can expressed by a POJO, so yeah it should definitely be possible.

**Comment by mg1075** [comment]
@mickhansen 

If a user had 20 columns to pick from, and the user only selects 5 columns, how would you let sequelize know what columns to pick? 

If a user had 20 columns to pick from, and the user only selects 5 columns, but adds filtering conditions to 10 of those columns, .... 

Is there a simple starter example for this kind of scenario?

**Comment by mickhansen** [comment]
@mg1075 This is more of a UI issue, you construct an object based on what's selected and send that to Sequelize.

What you could do:

For each condition a user adds (via a + field or whatever), you add an entry to an $and array.
Inside each condition the user can add a field, a comparator, and a value, you then convert that into an object and add it to $and.

etc.

**Comment by mg1075** [comment]
How can sequelize dynamically SELECT columns and conditionally JOIN tables and build a dynamic set of WHERE clause filters for a raw query? The raw query examples do not indicate this is possible.

**Comment by mickhansen** [comment]
@mg1075 YOU, not sequelize, would build a dynamic query that is sequelize friendly. `include` is just an array, etc.

**Comment by mg1075** [comment]
Looks like sequelize raw queries don't like dynamic table names. 
https://github.com/sequelize/sequelize/issues/4494

**Comment by mickhansen** [comment]
I was assuming you'd use `findAll` since that'd work best with a user generated filter in my opinion.
You'd have to escape dynamic table names on your own.
