### ISSUE TITLE
Method QueryInterface.bulkDelete no longer working when the model parameter is missing. (PostgreSQL)

### ISSUE THREAD

**Issue by pparlev** [sequelize/sequelize#5615]
When in a migration I'm trying to delete all the rows in one of my tables I get the following error
"TypeError: Cannot read property 'primaryKeys' of undefined".

My code looks like this 
```
up: function(queryInterface, Sequelize) {
	return queryInterface.bulkDelete('Foo');
}
```
I expect that all rows matching a where condition get deleted.

This happens when using sequelize 3.19.3 with PostgreSQL.

IMO the bug is caused by the changes in this PR #5443. 
More precisely, the exception occurs [here](https://github.com/sequelize/sequelize/pull/5443/files#diff-7e347c4738c97261969fbeb802a3c363R367) as `model` is undefined.

**Comment by cgreening** [comment]
In case anyone else comes here looking for a solution. You need to pass a dummy object for the last two arguments to get the bulkDelete to work as expected.

First argument should be the name of the table, second argument the where clause.

```js
return queryInterface.bulkDelete('headings', { title: {$in: headingTitles} }, {}, {primaryKeys:[],primaryKeyAttributes:[]});
```

**Comment by markelog** [comment]
@janmeier could release new version with this fix?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/releases/tag/v3.23.0

**Comment by prabhat4ever** [comment]
@cgreening you saved my life . . . thanks for that suggestion :-) 👍

**Comment by markelog** [comment]
@janmeier thank you!

**Comment by Hoverbear** [comment]
This seems to produce a

```
Seed file failed with error: val.replace is not a function
````

Code:

```js
    down: function (queryInterface, Sequelize) {
        return queryInterface.bulkDelete('Flags', {
            where: {
                keyword: [
                    "groupRegistration",
                    "memberRegistration",
                    "exhibitorRegistration",
                    "facilitatorRegistration",
                    "volunteerRegistration",
                    "workshopSignup"
                ]
            },
        }, {}, {});
    }
```

**Comment by diosney** [comment]
It is happening me what @Hoverbear said (the `Seed file failed with error: val.replace is not a function` error).

There is any fix for the issue?

**Comment by diosney** [comment]
Using MySQL adapter in my case.

@janmeier Any ideas?

**Comment by boxman0617** [comment]
@diosney @Hoverbear Just remove the `where`. So instead of what you have do this:

```javascript
    down: function (queryInterface, Sequelize) {
        return queryInterface.bulkDelete('Flags', {
            keyword: [
                "groupRegistration",
                "memberRegistration",
                "exhibitorRegistration",
                "facilitatorRegistration",
                "volunteerRegistration",
                "workshopSignup"
            ]
        });
    }
```

You don't need to pass the last two arguments if you don't need them.

**Comment by diosney** [comment]
@box Say whaaaaat!!! I can't believe it!!! What a catch man!

Worked like a charm! Finally someone who put some light into this! Thanks!

**Comment by boxman0617** [comment]
@diosney no problem!

**Comment by firdanirp** [comment]
Guys i need to truncate the table use queryInterface. Is that possible?

**Comment by hadasmaimon** [comment]
> Guys i need to truncate the table use queryInterface. Is that possible?

@firdanirp  how did you do it finally?
