### ISSUE TITLE
UPDATE not really updating on the database when using 'set'

### ISSUE THREAD

**Issue by govem** [sequelize/sequelize#5619]
Hi guys.
I'm new to sequelize and i run in to this weird behaviour:

```javascript
var friendship = models.Friendship.create().then(function(friendInstance){
  //both friend and user are sequelize instances, results of findById
  friendInstance.setFriend(friend); 
  friendInstance.setOwner(user); 
}).catch(function(err){
  //stuff
});
```

when i log the querys of sequelize, i've got:

```sql
Executing (default): INSERT INTO `Friendships` (`friendship_id`,`createdAt`,`updatedAt`) VALUES (NULL,'2016-03-22 01:21:39.063 +00:00','2016-03-22 01:21:39.063 +00:00');
Executing (default): UPDATE `Friendships` SET `friendUserId`=417,`updatedAt`='2016-03-22 01:21:39.072 +00:00' WHERE `friendship_id` = 131
Executing (default): UPDATE `Friendships` SET `ownerUserId`=416,`updatedAt`='2016-03-22 01:21:39.072 +00:00' WHERE `friendship_id` = 131
```

..that seems ok. But when i look at the database, i can't see the last updates:

```sql
sqlite> select * from Friendships;
131|2016-03-22 01:21:39.063 +00:00|2016-03-22 01:21:39.072 +00:00|||  <-- missing fields
```

If i take one of the updates to test it, and execute it on sqlite, it works ok

```sql
sqlite> UPDATE `Friendships` SET `ownerUserId`=416,`updatedAt`='2016-03-22 01:21:39.072 +00:00' WHERE `friendship_id` = 131;
sqlite> select * from Friendships;
131|2016-03-22 01:21:39.063 +00:00|2016-03-22 01:21:39.072 +00:00|416||
```

I don't know what to do now.. the models are here, for reference:

https://gist.github.com/govem/0f0291868750b09c0b19.js
https://gist.github.com/govem/754abddebd719ed7ff35.js

Please tell me if you need any more information.
Thanks in advance.

**Comment by mickhansen** [comment]
If there's no errors it should just work. We can't really help you diagnose why it appears the the queries aren't executed here. Maybe you're looking in the wrong place.

Please provide a SSCEE, closing this for now.

**Comment by govem** [comment]
i'm sorry, what is a SSCEE?

**Comment by mickhansen** [comment]
http://sscce.org/ Short, Self Contained, Correct (Compilable), Example

It's a piece of code that i can copy/paste to verify that something is wrong. Ideally with an assertion.
