### ISSUE TITLE
"MSSQL does not support self referencial constraints", why is do you have this limitation?

### ISSUE THREAD

**Issue by gkorland** [sequelize/sequelize#5625]
I got the following error while MSSQL doesn't have such limitation.

> MSSQL does not support self referencial constraints, we will remove it but we recommend restructuring your query

**Comment by mickhansen** [comment]
MSSQL does not support inline references which Sequelize uses for other dialects so the original implementation of MSSQL skipped it i guess.

**Comment by janmeier** [comment]
Without it you get `Unhandled rejection SequelizeDatabaseError: Could not create constraint or index. See previous errors.` for this query: 
```sql
CREATE TABLE [users] ([id] INTEGER NOT NULL IDENTITY(1,1) , [userId] INTEGER NULL, PRIMARY KEY ([id]), FOREIGN KEY ([userId]) REFERENCES [users] ([id]) ON DELETE SET NULL);
```
