### ISSUE TITLE
Call scope functions with the "scopes" object as this

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#5628]
I think on a way to reduce redundance in scope declarations by make references between them, so I could e.g declare various tiny reusable scopes and reference them from more complex ones, instead of repeating the same.

```javascript
scopes: {
  includePropertiesWithCategories: function(){...}
  includeContractWithProperties: function(){...}
  includeProfileWithProperties: function(){...}
  cascadeProperties: function(where) {
     return {
       include: [
         this.includePropertiesWithCategories(),
         this.includeContractWithProperties(),
         this.includeProfileWithProperties()
       ],
       where: where||{}
     }
   }
}
```
I know there is some merging functionality offered already but the point here is that it would be cool if at least I got access to the other scopes from one scope, like in the above snippet where I'm assuming this points to the "scopes" object.

**Comment by mickhansen** [comment]
Should technically be possible via `Model.options.scope.method()`

**Comment by mickhansen** [comment]
Although you'll want to use `[].concat(this.includePropertiesWithCategories().include)` since scopes should return an options object, not a single include

**Comment by hendrul** [comment]
I write it like this and it works:
```javascript
allProperties: function(where) {
  var self = models.User.options.scopes;
  return {
    include: [].concat(
      self.includeProperties().include,
      self.includeContractWithProperties().include,
      self.includeProfileWithProperties().include
    ),
    where: where||{}
  }
}
```

**Comment by mickhansen** [comment]
Great :)
