### ISSUE TITLE
Association getters allows "scope" and "where" only but not complete query objects

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#5633]
When lazy-loading an association through the corresponding getter I can only filter via where conditions, or by naming a scope, but I also want to be able to add nested inclusions or include/exclude some attributes, in that specific call; I don't want to add a scope in the target just for that particular case.
```javascript
//This is how I must proceed currently, I'm forced to create an scope on Property "includeCategory"
//which have the include.
User.getProperties({ scope: 'includeCategory', where: { configurableByUser: true }});
//What I want is to be able to specify the query directly on the call, not only a where attribute
User.getProperties({ include: [{model: Category, as: 'category'}], where: { configurableByUser: true }});
```

**Comment by mickhansen** [comment]
`getAssociations` maps directly to findAll, so it should support all find options that `find` does.

**Comment by hendrul** [comment]
@mickhansen you're right, but the docs for getAssociations only mention the where attribute.

**Comment by mickhansen** [comment]
Ah i see, yes it should refer to `findAll` for a full set of options.
