### ISSUE TITLE
Raw result sets by default

### ISSUE THREAD

**Issue by scragg0x** [sequelize/sequelize#5634]
Is is possible to have raw set to true by default when using find functions?

**Comment by sushantdhiman** [comment]
There is `raw` option that you can set to `true`, More docs [here](http://docs.sequelizejs.com/en/latest/docs/models-usage/?highlight=raw#raw-queries)

**Comment by janmeier** [comment]
You can add a beforeFind hook which sets raw to true

**Comment by scragg0x** [comment]
@janmeier Thanks
