### ISSUE TITLE
Bug in latest version while using findAll with $or: []

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#5637]
```js
var Sequelize = require('sequelize')

var sequelize = new Sequelize('postgres://localhost/db')
var Model = sequelize.define('Model')

Model.findAll({
  where: {
    $or: []
  }
})
```

Generates following query:

```sql
SELECT "id", "createdAt", "updatedAt" FROM "Models" AS "Model" WHERE 0 = 1;
```
Commenting out `$or: []` solves the issue.

Using sequelize `3.20.0`.
This is serious one - it has broken all tests for all my apps :)

**Comment by mickhansen** [comment]
What version did you upgrade from? I don't recall a change in regards to this.

**Comment by valtlfelipe** [comment]
Same problem here, but in production with version `3.20.0`, where we have a report generator that has `$and` and `$or` set to `[]`, and get populated dynamically, so there are situations where `$or` stays empty. PR where this has been merged is #5458 and issue #5453 .

**Comment by alekbarszczewski** [comment]
Sorry, I totally forgot about this. So it seems that this behaviour is intentional :(.
In my opinion it is totally not intuitive and will cause more trouble than it helps.
Fortunately it is easy to bypass it like this:

```js
var sequelize = new Sequelize('postgres://localhost/db', {
  hooks: {
    beforeFind: function (options) {
      if (options.where && Array.isArray(options.where.$or) && !options.where.$or.length) {
        delete options.where.$or
      }
    }
  }
})
```

**Comment by sushantdhiman** [comment]
Considering #5453 empty `$or / $and` will resolve to a empty set `0 = 1`.

As already pointed out, desired behavior could be achieved using `beforeFind` hook or even pre-parsing `options` before doing `findAll` call.
