### ISSUE TITLE
model attribute's dynamic default value

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#5646]
A way to define default value for attributes which aren't defined on the DB but only in the definition as a function, which is called each time we build/create/save an instance. Would be as great to have as #5647
```javascript
var Branch = sequelize.define('Branch', {
  name: { 
    type: DataTypes.STRING,
    defaultValue: ''  //DB default value
  },
  contractId: {
    type: DataTypes.BIGINT,
    defaultValue: function(ctx){ //A function which returns the default value any time an instance is build/created/saved
        //ctx could come from the options pass as argument to build/create/save
    	return ctx.session.user.contractId
        //Or maybe a CLS namespace which we could set on the service layer
    }
  }
  code: {
  	type: DataTypes.STRING,
  	defaultValue: function(ctx){           
  		return ctx.codeSequenceGen.next(); //Maybe this could even return a Promise as shown here, 
        //for create and save it's fine because they're async, the problem would be build() which is sync
  	}
  }
})

//On Branch service Create Endpoint
Branch.create({
	name: 'BranchXYZ'
}, { context: {session: req.session, codeSequenceGen: ...}}).then(function(branch){
	console.log('New branch created with code: ' + branch.code);
})
```
A default method by itself is not terribly useful without some context from which we can get the value, as in the above example where we get the contractId from the user session object. This context is being pass via the options object of methods for building/creating/saving instances in this case but maybe we could even use a CLS namespace from which to get this context object.

**Comment by mickhansen** [comment]
I'm not sure exactly what your usecase here, but in any case i feel it's a lot of unneeded complexity in the core codebase.

We already support defaultValue as functions, but they are called on model init for a completely new model (create/build, not find).

This would be better off coded as a plugin of sorts (if only in your codebase), using beforeCreate/Update hooks you could easily look at the context, map through defined attributes and see if have a method that you'll want to inject values based on.

**Comment by hendrul** [comment]
> I'm not sure exactly what your use case here

There are attributes which values cannot be set by users but instead this value must be calculated dynamically on save (e.g a value from the user session ), there is no static default value defined for them.

> We already support defaultValue as functions

Yes, I'll use another name then

> This would be better off coded as a plugin

You're right with hooks I could implement an addon

Thanks!
