### ISSUE TITLE
model attribute's fake values for easy testing

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#5647]
New model methods (buildFake, createFake) to create fake instances with arbitrary generated values, maybe with some support for node libraries like faker or chance. This would be great for testing and it seems a feature easy to add. Something like this (open to ideas) e.g:

```javascript
var Branch = sequelize.define('Branch', {
  name: { 
    type: DataTypes.STRING,
    fakeValue: ['name', {middle: true}]  //Here Sequelize makes use of chance.js internally
  },
  code: {
    type: DataTypes.STRING,
    validate: {
       length: 6  
    },
    fakeValue: ['string']  //Sequelize could even try to satisfy validations! passing {length: 6} in this case
  },
  startDate: {
    type: DataTypes.DATE
    //If a fake value is not specified Sequelize uses DataTypes default random values
    //and could even try to satisfy validations!
  },
  email: {
    type: DataTypes.STRING,
    fakeValue: function(){  //Maybe chance.js won't cover all cases so we could add our own logic
      return require('faker').internet.email()
    }
  }
})

//Building/creating a single fake instance
var fakeInstance = Branch.buildFake(); //Or Branch.build(null, { fake: true })
Branch.createFake().then(...)          //Or Branch.create(null, { fake: true }).then(...)

//Building/Creating many fake instances at once
var fakeInstances = Branch.buildFake({ times: 5 }); //Or Branch.build(null, { fake: true, times: 5 })
Branch.bulkCreate({ fake: true, times: 5 }).then(...)
```

**Comment by mickhansen** [comment]
While i like the idea i don't think it has merit enough to add to the core codebase.
Are you looking to use this for some sort of fuzzer testing?

**Comment by hendrul** [comment]
For integration test with sequelize and the DB I need to easily create valid test data, I need to create complex  (nested) json objects to insert, this tests would get much simpler and I could write it much faster if I could indicate per attribute the kind of data I want to be generated so it pass validations.

**Comment by mickhansen** [comment]
In my opinion the codebase should contain as little test-helper code as possible, if any.
Think is likely more suitable for a plugin/user land project.
