### ISSUE TITLE
Struggling to find information on join syntax with Sequelize

### ISSUE THREAD

**Issue by ORESoftware** [sequelize/sequelize#5648]
Hey all

I am really struggling

http://docs.sequelizejs.com/en/latest/

to find a section on how to do "joins" in the docs

am I completely blind?

**Comment by daniel-pedersen** [comment]
This is mainly done through [associations](http://docs.sequelizejs.com/en/latest/docs/associations/) and the [include option](http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance) in findAll/findOne/etc.

**Comment by ORESoftware** [comment]
Ok understood thanks, so I suppose if you need to do any super-fancy joins, you do it will plain query strings, right?

**Comment by ORESoftware** [comment]
Or is there a Middle Way?

**Comment by mickhansen** [comment]
If you need super fancy queries in general then you'll need another way to model them.
I'd love to offer a way to do it in Sequelize but i don't see a great API for it.

The best solution would probably be to offer better raw query support for model building.
