### ISSUE TITLE
"internal" attributes

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#5649]
Add an "internal" attribute to the definition of attributes to tell sequelize that this attribute:
  - Must be excluded when stringifying the instance
  - Must be ignored when creating/updating the instance and defaultValue should be used instead
    which after resolving #5646 could do some logic to assign the right value.

The idea is to hide some attributes to clients when we send responses as JSON and prevent clients from updating this attributes and only internal logic be use to assign value to these, without having to resort to using hooks.

**Comment by mickhansen** [comment]
This is not possible with core but plugins like https://github.com/mickhansen/ssacl-attribute-roles might accomplish some of this.
