### ISSUE TITLE
how can i do some aggregate function but still get multiple rows ？

### ISSUE THREAD

**Issue by p2227** [sequelize/sequelize#5652]
let's say there are two rows of data like this:
```
field1
10
20
```
if i run `model.findAll()` ,it will get 
```
[{field1:10},{field:20}]
```

if i run 
```
model.findAll({
   attributes:{
			include:[
				[sequelize.fn('AVG',sequelize.col('field1')),'field1_AVG']
			]
		}
})
```

it will get 
```
[{field1:10,field_AVG:15}]
```

how can i get

```
[{field1:10,field_AVG:15},{field1:20,field_AVG:15}]
```

**Comment by yogesum** [comment]
You can use `group by` primary key.
```js
model.findAll({
   attributes:{
            include:[
                [sequelize.fn('AVG',sequelize.col('field1')),'field1_AVG']
            ]
        },
   group: ['id']
})
```

**Comment by p2227** [comment]
@yogesum that will get 

```
[{field1:10,field_AVG:10},{field1:20,field_AVG:20}]
```

**Comment by mickhansen** [comment]
With postgres and mssql you can use window functions to do aggregations without grouping.
However your example here doesn't make a lot of sense, there's no case where it makes sense to have both every field value of `field1` and also the average.
