### ISSUE TITLE
Association `add` and `remove` methods don't resolve or reject

### ISSUE THREAD

**Issue by mdibaiee** [sequelize/sequelize#5657]
Hey,

It seems _sometimes_, using add or remove association methods promise doesn't either resolve or reject, thus hanging my process (I'm using async functions).

Models:
```javascript
  sequelize.define('Employee', { ... });
  sequelize.define('Project', { ... });
  ...
  // Employee <--> Project
  Employee.belongsToMany(Project, { through: 'EmployeeProjects' });
  Project.belongsToMany(Employee, { through: 'EmployeeProjects' });
```

Code:
```javascript
(async function() {
  const emp = Employee.findOne({ ... });
  try {
    await emp.removeProject(project);
  } catch (e) {
    console.error('E', e);
  }
}());
```

The promise just doesn't resolve or reject, but, the association happens, so if I don't `await` on the promise, and test the association after a timeout, it works.

Another clue I found is, sometimes doing `emp.addProject` doesn't work, while `project.addEmployee` works, weird.

This issue might be related, too: https://github.com/sequelize/sequelize/issues/4723

**Comment by mickhansen** [comment]
All code paths return a promise: https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L638

So there shouldn't be any issue. Please provide a [SSCCE](http://sscce.org/)

**Comment by mdibaiee** [comment]
I found the problem, it was the hooks, passing `{ hooks: false }` as second parameter to `add`/`remove` methods, they don't hang anymore, but I'm not sure why.

My hooks don't return a promise, here is the definition:
```javascript
  ['afterCreate', 'afterUpdate',
  'afterBulkCreate', 'afterBulkDestroy', 'afterBulkUpdate'].forEach(ev => {
    sequelize.addHook(ev, (model, options) => {
      try {
        update(model, options); // a function which updates some models, does interact with the database
      } catch (e) {
        error(e); // a fancy console.error
      }
    });
  });
```

I would be grateful if you help on this. Thanks.

**Comment by mickhansen** [comment]
You can't use try/catch for async methods unless you're using ES7 async/await.
I think we might have a edge case here with the arrow function, can you test with a regular function?

**Comment by mdibaiee** [comment]
The try/catch is was leftover, removed it.

Tried using regular functions, no luck.
```javascript
  ['afterCreate', 'afterUpdate',
  'afterBulkCreate', 'afterBulkDestroy', 'afterBulkUpdate'].forEach(ev => {
    sequelize.addHook(ev, function createUpdateHook(model, options) {
      update(model, options);
    });
  });
```

**Comment by janmeier** [comment]
What does the `update` function do? Perhaps you are encountering some infinite recursion? If `update` returns a promise, try returning it

**Comment by mdibaiee** [comment]
@janmeier: It _might_ cause a recursion, but even if so, it should not prevent `team.addProject(project)` from resolving. On the other hand, we have `project.addTeam(team)` working well. That's just weird.

Anyways, I tried it, it works.
I also tried returning `Promise.resolve()`, this works, too.
```javascript
    sequelize.addHook(ev, function createUpdateHook(model, options) {
      update(model, options);
      return Promise.resolve();
    });
```

So it seems the hook always expects a promise, but that's not what documentation says, I think it's not the expected behaviour, or is it?

**Comment by mickhansen** [comment]
returning undefined should resolve the hook immediately aswell if we don't detect a callback param in the hook callback signature.

**Comment by mdibaiee** [comment]
Oh noes, I had the `{ hooks: false }` flag accidentally on while trying the `Promise.resolve()` and `return update` examples, sorry. Returning `update` or `Promise.resolve`, with arrow or regular functions doesn't work.

**Comment by mickhansen** [comment]
Does it work with a standalone `Promise.resolve()` with no `update` call?
Does it work if you add the hook directly to the model rather than to sequelize?

**Comment by mdibaiee** [comment]
> Does it work with a standalone Promise.resolve() with no update call?
No
> Does it work if you add the hook directly to the model rather than to sequelize?
Not either

**Comment by mickhansen** [comment]
I have no idea, we have plenty of tests for this that just work

**Comment by mdibaiee** [comment]
@mickhansen I'll see if I can find anything interesting in the source code, thanks for the help.

**Comment by sushantdhiman** [comment]
**SSCCE Test**

```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();


['afterCreate', 'afterUpdate',
  'afterBulkCreate', 'afterBulkDestroy', 'afterBulkUpdate'].forEach(ev => {
    sequelize.addHook(ev, (model, options) => {
      // doing nothing
    });
  });

var E = sequelize.define('E', { });
var P = sequelize.define('P', { });

E.belongsToMany(P, { through: 'EPs' });
P.belongsToMany(E, { through: 'EPs' });

sequelize.sync({ force: true })
.then(() => {
  return E.create({});
})
.then((e) => {
  return P.create({}).then((p) => (
    p.addEs(e)
  ));
})
.then(console.log)
.catch(console.error)

```

Output
```js
Using database:  sequelize-test-90
[ [ EPs {
      dataValues: [Object],
      _previousDataValues: [Object],
      _changed: [Object],
      '$modelOptions': [Object],
      '$options': [Object],
      hasPrimaryKeys: true,
      __eagerlyLoadedAssociations: [],
      isNewRecord: true } ] ]

```
