### ISSUE TITLE
Reference keys not adding Postgresql schema name

### ISSUE THREAD

**Issue by erayalakese** [sequelize/sequelize#5659]
I'm trying to create Sequelize (3.20) models of these 2 tables:

```
| user  |          | comment  |
|-------|          |----------|
| id    |          | id       |
| email |          | userId   |
```

_user_ table is on _crm_ schema and _comment_ table is on _comment_ schema. `comment.userId` has foreign key to `user.id`.

```
var User = db_conn.define('user', {
  email: {
    ...
  }
}, {
  'schema' : 'crm',
  ...
});
User.sync({force: true}).then(function () {
  return User.create({
    email: 'mail@gmail.com'
  });
});

var Comment = db_conn.define('comment', {
  userId: {
    type: Sequelize.INTEGER,
    allowNull: false,
    references: {
        model: User,
        key  : 'id',
        deferrable: Sequelize.Deferrable.INITIALLY_DEFERRED
    }
  }
}, {
  'schema' : 'comment',
  ...
});
Comment.sync({force: true}).then(function () {
  return Comment.create({
    userId: 1,
  });
});
```

But i'm getting this error:

```
Unhandled rejection SequelizeForeignKeyConstraintError: insert or update on table "comment" violates foreign key constraint "comment_userId_fkey"
```

Generated SQL :

```
ADD CONSTRAINT comment_userId_fkey
FOREIGN KEY (userID) REFERENCES  ();
```

As you see generated SQL is not valid, REFERENCES part is empty. Can you please tell me what is I'm missing?

Thank you.

**Comment by mickhansen** [comment]
I don't see you using the schema option on the model definition but i assume that's just something you've left out?

**Comment by erayalakese** [comment]
@mickhansen  No I'm actually using them but forget to add them to question while trying to simplify codes to paste here. Now codes updates.

**Comment by eraye1** [comment]
if the db_conn defines a connection that sets the schema, shouldn't that propagate over to the model definition when we create it so that the table update should update in the right schema?

**Comment by mickhansen** [comment]
@eraye1 In this case he's applying schema to the models.
