### ISSUE TITLE
Add a way to attach a transaction to a model (or a wrapper of the model)

### ISSUE THREAD

**Issue by PlasmaPower** [sequelize/sequelize#5661]
This would be hard to implement, but it would be very useful, especially for making servers, a major use case of Sequelize.

# Use case
Most frameworks have a method for attaching objects to a request, for example with Connect/Express you can use the request object itself or for Koa you can use the context object. I've been automatically creating a transaction for every `/api` call, and then putting that in the context. It will automatically commit when done and rollback after an error. However, it's a pain to specify the transaction for every sequelize call. It would be much more useful if I could create a models wrapper. I'm already storing the models in the context, and while a lot of people aren't this wouldn't be to hard to do. If the models automatically used the transaction for that request, that would be ideal. It would save a lot of time troubleshooting issues where I forgot to use the transaction, and it would remove some hassle from database requests.

# Details
- Any returned models should also carry the transaction (refered to here as tainted models)
- Attaching a transaction to a model shouldn't taint all instances of the model
- This should be only the default transaction, if another transaction is manually specified then it should override the default

# Implementation
It wouldn't make sense to attach a transaction to a model itself, as it would taint all instances and sequelize is asynchronous. However, we could create a wrapper of models that carries with it a transaction. The easy way to do this is to map API calls to arguments needed to signal a transaction, and then taint any returned models. The harder way is to implement a hook or attribute system to attach a transaction to a copy of a model and taint any returned models with this hook or attribute.

**Comment by mickhansen** [comment]
Have you looked at CLS? http://docs.sequelizejs.com/en/latest/docs/transactions/

**Comment by PlasmaPower** [comment]
That's perfect, actually. For some reason I thought it was for a global transaction when I read it.
