### ISSUE TITLE
sql injection in "IN" statement

### ISSUE THREAD

**Issue by leibale** [sequelize/sequelize#5671]
i'm using mssql.
sequelize version is 3.19.3.

sample:
```javascript
const Sequelize = require('sequelize'),
    database = new Sequelize( ... );

database.query('SELECT * FROM Table WHERE Id IN (:ids)', {
  replacements: {
    ids: [1, 2, 3, "'asdf"]
  }
}).catch(function (err) {
  // got sql syntax error
});
```
because `tedious` doesn't support arrays as parameters you must add a parameter for every item in the array and use it in the query (`IN (:ids0, :ids1, :ids2, :ids3)`).

now there is an option to do sql injection.

**Comment by mickhansen** [comment]
Sequelize handles replacements before passing it along to the driver IIRC.
Under what case are you sayings there's an injection issue? `IN (:ids0, :ids1, :ids2, :ids3)` would not be vulnerable.

**Comment by leibale** [comment]
Let me explain myself.
Sequelize accepts strings in an array as parameters.
Instead of adding the parameters as a parameter, it injects them as strings straight into the sql query.

example
```javascript
const Sequelize = require('sequelize'),
    database = new Sequelize( ... );

database.query('SELECT * FROM Table WHERE Name IN (:names)', {
  replacements: {
    names: ["test", "'); DELETE Table WHERE Id = 1 --')"]
  }
});
```
the query will be
```sql
SELECT Id FROM Table WHERE Name IN ('test', '\'); DELETE Table WHERE Id = 1 --')
```
in mssql backslash isn't a special character.

**Comment by mickhansen** [comment]
`\`  does not escape `'` in mssql?
Well original implementation of mssql in sequelize does have a major bug then, anything we escape should not be injectable.

**Comment by leibale** [comment]
in mssql `\` doesn't escape `'`, instead of escaping with `\` you should escape with double `'`.
pls let me know if someone started to deal with it.

tnx

**Comment by mickhansen** [comment]
Yeah it should actually already be doing that: https://github.com/sequelize/sequelize/blob/master/lib/sql-string.js#L61

**Comment by leibale** [comment]
so this is not working as you expected.. i'm debugging this now.

**Comment by leibale** [comment]
found the mistake. creating PR now.

**Comment by leibale** [comment]
somebody already fixed this one in 23952a2b020cc3571f090e67dae7feb084e1be71.
when are you going to publish a new version to npm?

**Comment by mickhansen** [comment]
That version is already on npm, as is evident from the tags on that commit

**Comment by leibale** [comment]
right, my mistake.
tnx.
