### ISSUE TITLE
Create a new relation with migrations

### ISSUE THREAD

**Issue by WalterC87** [sequelize/sequelize#5677]
Hello again;

I've created a model with some initial relations, but during the development process I realized that I need another relation in my model, my inconvenient is, in the development environment are doing test and insert data, and I don't want drop the table or tables to add this new relation.

I was reading the documentation about migrations and just explain how add a new index for a table, I'ts possible Add new relation with migrations?, or I need drop the table(s) to create this new relation and lost my data?

**Comment by mickhansen** [comment]
For 1:? relations you'll need a migration that adds a foreign key attribute and possible constraints/indexes.
For N:M you need to create a join table aswell.

**Comment by WalterC87** [comment]
thanks @mickhansen I've resolve the problem with your advice, and add the belongsTo and hasMany relations in each model plus create the migration where I added a new foreign key field.

thanks
