### ISSUE TITLE
Filter by 2-way belongsToMany but still fetch all values

### ISSUE THREAD

**Issue by JosephDuffy** [sequelize/sequelize#5678]
I currently have a situation as follows:
- `Item` is related to many `Tag`s via `ItemTag`
- `Tag` is related to many `Item`s via `ItemTag`
- I wish to retrieve all `Item`s that contain a specified tag, but still pull all of the tags

``` js
Item.belongsToMany(models.Tag, {
       as: "tags",
       through: models.ItemTag,
       foreignKey: "itemId"
});
[...]
Tag.belongsToMany(models.Item, {
    as: "items",
    through: models.ItemTag,
    foreignKey: "tagName"
});
[...]
var tag = ['tag-name', 'tag2'];

models.Item.findOne({
    where: [...],
    include: [
        {
            model: models.tag,
            as: "tags",
            through: {
                model: models.ItemTag,
                where: {
                    tagName: {
                        $in: tags
                    }
                }
            }
        }
    ]
});
```

This filters the results to only include `Item`s associated with a matching `Tag`, however, it also only pulls the tags that match the filter.

I would like to be able to do something similar to:

``` js
var tag = ['tag-name', 'tag2'];

models.Item.findOne({
    where: [
        "tags.displayName": {
            $in: tags
         }
    ],
    include: [
        {
            model: models.tag,
            as: "tags",
            through: models.ItemTag
        }
    ]
});
```

However, this does not work as intended:

`column Item.tags.displayName does not exist`

(note that `displayName` is the primary key on the `Tag` table)

**Comment by mickhansen** [comment]
Might be doable by including the same include twice, but it might fail.

**Comment by JosephDuffy** [comment]
If I have the include twice then I get the error "table name 'tags.ItemTag' specified more than once". Maybe if I changed the value in `as` it would work, but I cannot get it to work that way.
