### ISSUE TITLE
Updating one model record when associated model recored deleted.  

### ISSUE THREAD

**Issue by narri007** [sequelize/sequelize#5679]
Hi i am using sequelize in my project its working great, 
i am facing one problem to update one model record when i delete another model record.I have 3 sequelize models which are defines as below, 

Model1 : Device
```
module.exports = function(sequelize, DataTypes) {
    var device = sequelize.define("device",
      {
            uuid: {type: DataTypes.STRING(767)},
            geofenceBool :{type: DataTypes.BOOLEAN},
    }, {
        classMethods:
        {
            associate: function(models)
            {
                device.hasMany(models.geoFence, {as : 'geoFencings',onDelete: 'cascade'});
            }
        }
    });
    return device;
};
```
Model2 : Location 
```
module.exports = function(sequelize, DataTypes) {
    var location = sequelize.define("location", {
        name:{type: DataTypes.STRING(767)},
    }, {
        classMethods:
        {
            associate: function(models)
            {
                location.hasMany(models.geoFence, {as : 'geoFencings',onDelete: 'cascade'});
            }
        }
    });
    return location;
};
```
Model3: GeoFence 
```
module.exports = function(sequelize, DataTypes)
{
    var geoFence = sequelize.define("geoFence", {
        fenceType: DataTypes.STRING(767)
    }, {
        classMethods:
        {
            associate: function(models)
            {
                geoFence.belongsTo(models.device);
                geoFence.belongsTo(models.location);
            }
         }
    });
    return geoFence;
};

```
when i insert new **Device** into db, i can add number of **geoFence** records which is internally associated with **Location** model. And i am maintaining a Bool variable (**geoFenceBool**) in **Device** table to check the geoFence associations are there or not.
After inserting one device, 3 locations and related geoFencings the records stored in dB as, 

Device table Records: 
id: '1',uuid: '1235', geoFenceBool: 1 createdAt: '2016-03-30 09:00:52'
Location Records: 
ID : '1', name: 'living room ', createdAt: '2016-03-30 09:00:27'
ID : '2',name: 'rest room ', createdAt: '2016-03-30 09:00:27'
ID : '3',name: 'wash room ', createdAt: '2016-03-30 09:00:27'

GeoFence Table Records: 
id: '1',  type: 'Enter Only',  createdAt: '2016-03-30 09:00:52',  deviceID: '1', locationID: '1'
id: '2',  type: 'Exit Only',    createdAt: '2016-03-30 09:00:52',   deviceID: '1', locationID: '2'
id: '3',  type: 'Enter Only', createdAt: '2016-03-30 09:00:52',   deviceID: '1', locationID: '3'

Now my issue is when i delete  the location records from my db, i can delete the associated geoFencings using the _onDelete_ rule.But how can i update the **geoFenceBool** in Device tabel if all geoFences related to that device are deleted. I mean if i delete all locations from **location** table, the geoFencings associated with locations will delete from **geoFence** tabel, but how can i update the geoFenceBool as FLASE in Device table record. Please help me on this.

I am using : __ mysql Database 
__Sequelize version: ^3.19.3
__Node Js __ Express Js. 

Thanks !

**Comment by mickhansen** [comment]
Please make the minor effort to actually format your entry so it's readable :)

**Comment by narri007** [comment]
Hi mickhansen, 
Thanks for reply, 
Sorry, i am new to GitHub,  i edited my code please help me :)

**Comment by mickhansen** [comment]
Database foreign key constraints don't allow setting a generic value. You can either update the foreign key value or delete the entire row.

You'll need to remove database cascading and do your own cascading client side.
