### ISSUE TITLE
Problems using findAndCount when looking for models with non-existent associations

### ISSUE THREAD

**Issue by VividVisions** [sequelize/sequelize#5680]
Hi! 

I have the models Item and Category, which have a n:m relation. Now, I want to get all Items, where no Category has been assigned yet, which works when I use _findAll_ but fails when I use _findAndCount[All]_ (for pagination).

This works:
```js
models.Item.findAll({
    attributes: ['name'],
    where: sequelize.literal('"categories"."id" IS NULL'),
    include: [models.Category]
});
```

This does not:
```js
models.Item.findAndCountAll({
    attributes: ['name'],
    where: sequelize.literal('"categories"."id" IS NULL'),
    include: [models.Category]
});
```

I'm getting the following error:
`Error:  missing FROM-clause entry for table "categories"`

In a similar setup, I'm getting the error `SequelizeDatabaseError: column Item.val does not exist` as soon as I change _findAll_ to _findAndCount_.

I'm using: 
-  Sequelize v3.20.0
-  Dialect: postgres
-  PostgreSQL v9.4.4.1

**Comment by janmeier** [comment]
Try
```js
where: { '$categories.id$': null }
```

**Comment by VividVisions** [comment]
@janmeier Thanks, but same effect.

**Comment by janmeier** [comment]
The problem is that includes are removed from the count part - And when using literal or `$$`, we can't figure out that we should actually keep the include. Try adding `required:true` to the include, see https://github.com/sequelize/sequelize/issues/2663

**Comment by VividVisions** [comment]
`required:true` would return only Items with Categories in the first place.

**Comment by janmeier** [comment]
Yes - unfortunately there is no good way to fix the issue right now - we need to be able to figure out that the $$ clause means we should keep the include, https://github.com/sequelize/sequelize/pull/4195 and https://github.com/sequelize/sequelize/issues/3095

**Comment by VividVisions** [comment]
That's unfortunate. :( I don't really get why the query has to be altered for the count in the first place but I guess, there's a reason. Making it optional, as mentioned in the linked issues, would be great.

In the meantime, I tried a Postgres-specific workaround using `COUNT(*) OVER()`:

```javascript
models.Item.findAll({
    attributes: [
         [sequelize.literal('COUNT(*) OVER()'), 'all'],
        'name'
    ],
    where: { '$categories.id$': null },
    include: [models.Category]
});
```

This works well until I add `limit`. Then the `missing FROM-cause` error occurs again.

**Comment by mickhansen** [comment]
@VividVisions When using postgres the window function is much better in any case.
I'm not sure hwy it's not working for you here, can you try posting your SQL? (sounds like you might have some naming mismatch)

We should really implement the window function in findAndCount for dialects that support it.

**Comment by mickhansen** [comment]
Hmm, except that PG does not support DISTINCT in window functions, so that won't work.

**Comment by VividVisions** [comment]
> Hmm, except that PG does not support DISTINCT in window functions, so that won't work.

Yes. But this wouldn't matter in my specific case or generally with models without any or only 1:1 or n:1 relations. (Right?)

> I'm not sure why it's not working for you here, can you try posting your SQL?

Here's the generated (working) query without `limit`:

```sql
SELECT "Item"."id", COUNT(*) OVER() AS "all", "Item"."name", "categories"."id" AS "categories.id", "categories"."name" AS "categories.name", "categories.CategoryRelation"."item_id" AS "categories.CategoryRelation.item_id", "categories.CategoryRelation"."category_id" AS "categories.CategoryRelation.category_id" FROM "items" AS "Item" LEFT OUTER JOIN ("category_relations" AS "categories.CategoryRelation" INNER JOIN "categories" AS "categories" ON "categories"."id" = "categories.CategoryRelation"."category_id") ON "Item"."id" = "categories.CategoryRelation"."item_id" WHERE ("categories"."id" IS NULL);
```

And this one with `limit` fails :

```sql
SELECT "Item".*, "categories"."id" AS "categories.id", "categories"."name" AS "categories.name", "categories.CategoryRelation"."item_id" AS "categories.CategoryRelation.item_id", "categories.CategoryRelation"."category_id" AS "categories.CategoryRelation.category_id" FROM (SELECT "Item"."id", COUNT(*) OVER() AS "all", "Item"."name" FROM "items" AS "Item" WHERE ("categories"."id" IS NULL) LIMIT 2) AS "Item" LEFT OUTER JOIN ("category_relations" AS "categories.CategoryRelation" INNER JOIN "categories" AS "categories" ON "categories"."id" = "categories.CategoryRelation"."category_id") ON "Item"."id" = "categories.CategoryRelation"."item_id";
```
Am I interpreting this right: Adding `limit` changes the query to use a sub-query which doesn't know anything about categories at this point. Hence the error `missing FROM-clause entry for table "categories"`.

**Comment by VividVisions** [comment]
Just for the record: I solved this by denormalizing the number or categories per `Item`. I just added an `integer` field to `Item` and used Sequelize hooks to automatically update this field whenever categories get added or removed. Not very elegant, but it works.

(I also changed the title of this issue because it has nothing to do with `sequelize.literal`.)

**Comment by Djalmar** [comment]
I'm having the same problem the SQL code is 

`SELECT count(*) AS "count" 
FROM "public"."Item" AS "Item" WHERE "Category"."_id" IS NULL;`

There is any way to force add the **Category** join in the count clause ??
