### ISSUE TITLE
Unhandled rejection TypeError: val.replace is not a function

### ISSUE THREAD

**Issue by rguntha** [sequelize/sequelize#5681]
## What you are doing?
I am trying to update an entity using transactions. It works fine when I create the same entity with transactions.

Model is below..

```
"use strict";
var Sequelize = require("sequelize");

module.exports = function(sequelize, DataTypes) {
    var Shelter = sequelize.define("Shelter", {
            shelterId: {
                type: DataTypes.INTEGER,
                autoIncrement: true,
                primaryKey : true
            },
            shelterName: {
                type: DataTypes.STRING,
                allowNull : false
            },
            shelterDescription: {
                type: DataTypes.STRING,
                allowNull : false
            },
            capacity: {
                type: DataTypes.INTEGER,
                allowNull : false
            },
            openFromDate: {
                type: DataTypes.DATE,
                allowNull : false
            },
            openTillDate: {
                type: DataTypes.DATE,
                allowNull : false
            },
            addressLine1: {
                type: DataTypes.STRING,
                allowNull : false
            },
            addressLine2: {
                type: DataTypes.STRING
            },
            localityId: {
                type: DataTypes.INTEGER,
                references : 'Locality',
                referencesKey : 'localityId',
                allowNull : false
            },
            pinCodeId: {
                type: DataTypes.INTEGER,
                references : 'PinCode',
                referencesKey : 'pinCodeId',
                allowNull : false
            },
            longitude: {
                type: Sequelize.DECIMAL(8, 5),
                allowNull : false
            },
            latitude: {
                type: Sequelize.DECIMAL(7, 5),
                allowNull : false
            },
            isTemporary: {
                type: DataTypes.BOOLEAN,
                allowNull : false
            },
            contactUserId: {
                type: DataTypes.INTEGER,
                references : 'User',
                referencesKey : 'userId',
                allowNull : false
            },
            phoneNumber1: {
                type: DataTypes.STRING,
                allowNull : false
            },
            phoneNumber2: {
                type: DataTypes.STRING
            },
            createdByUserId: {
                type: DataTypes.INTEGER,
                allowNull : false
            },
            createdDate: {
                type: DataTypes.DATE,
                allowNull : false
            },
            modifiedByUserId: {
                type: DataTypes.INTEGER,
                allowNull : false
            },
            modifiedDate: {
                type: DataTypes.DATE,
                allowNull : false
            },
            statusId: {
                type: DataTypes.INTEGER,
                allowNull : false
            }
        },
        {
            tableName:'Shelter',
            timestamps:false
        });

    return Shelter;
};
```
// code here
```
update:function(shelterToUpdate,updaterId){
        var shelterHelper = this;
        return models.sequelize.transaction(function(t){
            return pinCodeHelper.findOrCreate(shelterToUpdate.pinCode,shelterToUpdate.countryId,updaterId,t).then(function(pinCodeObj){
                return shelterHelper.findById(shelterToUpdate.shelterId,t).then(function(shelter){
                    if(new Date(shelter.modifiedDate).getTime() === new Date(shelterToUpdate.modifiedDate).getTime()){
                        shelterToUpdate.pinCodeId = pinCodeObj.pinCodeId;
                        shelterToUpdate.modifiedDate = new Date();
                        shelterToUpdate.modifiedByUserId = updaterId;
                        var promises = [];
                        var promise = models.Shelter.update(shelterToUpdate,{where:{shelterId:shelterToUpdate.shelterId,transaction:t}});
                        promises.push(promise);
                        return Promise.all(promises).then(function(unused){
                            return shelterHelper.findById(shelterToUpdate.shelterId,t);
                        })
                    }
                })
            })
        });
    }
```

## What do you expect to happen?
I want the object to be updated

## What is actually happening?
Unhandled rejection TypeError: val.replace is not a function error is being thrown.
When I debugged based on the below stack trace, I found that it's trying to do replace operation on the transaction object.

```
Executing (default): SELECT `pinCodeId`, `countryId`, `pinCode`, `longitude`, `latitude`, `createdByUserId`, `modifiedByUserId`, `statusId`, `createdDate`, `modifiedDate` FROM `PinCode` AS `PinCode` WHERE `PinCode`.`pinCode` = '4124231' AND `PinCode`.`coun
tryId` = 2 AND `PinCode`.`statusId` = 1 LIMIT 1;
Executing (cf2fa39c-5055-4ffa-8548-0984ef9cec6e): SELECT `Shelter`.`shelterId`, `Shelter`.`shelterName`, `Shelter`.`shelterDescription`, `Shelter`.`capacity`, `Shelter`.`openFromDate`, `Shelter`.`openTillDate`, `Shelter`.`addressLine1`, `Shelter`.`addressL
ine2`, `Shelter`.`localityId`, `Shelter`.`pinCodeId`, `Shelter`.`longitude`, `Shelter`.`latitude`, `Shelter`.`isTemporary`, `Shelter`.`contactUserId`, `Shelter`.`phoneNumber1`, `Shelter`.`phoneNumber2`, `Shelter`.`createdByUserId`, `Shelter`.`createdDate`,
 `Shelter`.`modifiedByUserId`, `Shelter`.`modifiedDate`, `Shelter`.`statusId`, `ShelterFacilities`.`shelterFacilityId` AS `ShelterFacilities.shelterFacilityId`, `ShelterFacilities`.`shelterId` AS `ShelterFacilities.shelterId`, `ShelterFacilities`.`shelterF
acilityTypeId` AS `ShelterFacilities.shelterFacilityTypeId`, `ShelterFacilities`.`quantity` AS `ShelterFacilities.quantity`, `ShelterFacilities`.`createdByUserId` AS `ShelterFacilities.createdByUserId`, `ShelterFacilities`.`createdDate` AS `ShelterFaciliti
es.createdDate`, `ShelterFacilities`.`modifiedByUserId` AS `ShelterFacilities.modifiedByUserId`, `ShelterFacilities`.`modifiedDate` AS `ShelterFacilities.modifiedDate`, `ShelterFacilities`.`statusId` AS `ShelterFacilities.statusId` FROM `Shelter` AS `Shelt
er` LEFT OUTER JOIN `ShelterFacility` AS `ShelterFacilities` ON `Shelter`.`shelterId` = `ShelterFacilities`.`shelterId` AND `ShelterFacilities`.`statusId` = 1 WHERE `Shelter`.`shelterId` = 5 AND `Shelter`.`statusId` = 1;
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\sql-string.js:63:15)
    at Object.QueryGenerator.escape (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:973:22)
    at Object.QueryGenerator.whereItemQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2229:22)
    at C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1865:25
    at C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\lodash\lodash.js:4040:15
    at baseForOwn (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\lodash\lodash.js:2573:24)
    at Function.forOwn (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\lodash\lodash.js:11030:24)
    at Object.QueryGenerator.whereItemsQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1864:9)
    at Object.QueryGenerator.whereQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1836:22)
    at Object.QueryGenerator.updateQuery (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\dialects\abstract\query-generator.js:480:19)
    at QueryInterface.bulkUpdate (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\query-interface.js:599:33)
    at C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\lib\model.js:2630:32
    at tryCatcher (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\Code\CrowdSourcing\Server\NodeJS\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:605:10)

Executing (cf2fa39c-5055-4ffa-8548-0984ef9cec6e): ROLLBACK;
PUT /shelter/5?authToken=f98187e5f974c2d761576b885f964e56621113fe 200 51.104 ms - 104

```
__Dialect:__ mysql 
__Database version:5.7
__Sequelize version:3.20.0

**Comment by mickhansen** [comment]
Please make an effort to properly format your code

**Comment by rguntha** [comment]
Dear Sir,
Sorry for the inconvenience. I copied and pasted the code from my webstorm
editor.  Since its formatted in the editor I assumed that it remains
formatted in the forum as well.  I will fix it soon.

Thanks
Ramesh

**Comment by rguntha** [comment]
Please check now.

**Comment by mickhansen** [comment]
A lot of the code is wrong.

```js
pinCodeHelper.findOrCreate(shelterToUpdate.pinCode,shelterToUpdate.countryId,updaterId,t)
shelterHelper.findById(shelterToUpdate.shelterId,t)
```

Calls dont take transaction as an argument, they usually do take an options object that can contain a `transaction` key.
The signature for your `findOrCreate` is just plain wrong, please look at the docs for proper use of `where`/`defaults`

**Comment by rguntha** [comment]
I think there is a misunderstanding here..
These are not the straight api calls, these are calls to my methods which call the api as mentioned by you.

I have been using sequelize for more than an year now, and used it across 4 projects so far..I know about the usage and the docs. This is not my first hello world..

However this is my first time I using transactions in sequelize. I used transactions heavily in hibernate and in ejbs earlier so I know about these concepts as well.

The transaction code (similar to the above code) is working find for inserts, but fails with the above error while updating.

Please focus on the tip I gave you towards the bottom of my issue post, the code is trying to replace the special chars on the transaction object.

**Comment by mickhansen** [comment]
You are wrapping findOrCreate and findById? That's uncommon and with limited time we always look at the most obvious errors first.

`val.replace` is almost always a user error.

You're incorrect about transactions being the issue. The code is triggered from the `whereItemQuery` path which does not care at all about transactions and only deals with generating where statements.

**Comment by rguntha** [comment]
Thanks for the tip about the where clause..And you are right about the user error part..

I made a typo in the code..
It was in the line..
`var promise = models.Shelter.update(shelterToUpdate,{where:{shelterId:shelterToUpdate.shelterId,transaction:t}});`

I mistakenly added the transaction as part of the where..

I fixed the code as 
`var promise = models.Shelter.update(shelterToUpdate,{where:{shelterId:shelterToUpdate.shelterId},transaction:t});`

and it works..Thanks very much for your time.

**Comment by mickhansen** [comment]
Oh, that's why it was enumerating the transaction :D

**Comment by Priyangaruba** [comment]
app.js:1446 Unhandled rejection TypeError: contract.mintToken is not a function
    at http://localhost:8080/app.js:16073:13
From previous event:
    at Object.val.then (http://localhost:8080/app.js:5735:12)
    at ChildScope.$scope.createToken (http://localhost:8080/app.js:16071:20)
    at https://code.angularjs.org/1.2.13/angular.js:10288:21
    at https://code.angularjs.org/1.2.13/angular.js:18086:17
    at ChildScope.$eval (https://code.angularjs.org/1.2.13/angular.js:12045:28)
    at ChildScope.$apply (https://code.angularjs.org/1.2.13/angular.js:12145:23)
    at HTMLFormElement.<anonymous> (https://code.angularjs.org/1.2.13/angular.js:18085:21)
    at https://code.angularjs.org/1.2.13/angular.js:2626:10
    at forEach (https://code.angularjs.org/1.2.13/angular.js:311:20)
    at HTMLFormElement.eventHandler (https://code.angularjs.org/1.2.13/angular.js:2625:5)
printWarning @ app.js:1446

am getting this type of error ,pls do needful

**Comment by Priyangaruba** [comment]
am using angular for front end ,is anything wrong to call the solidity function
var token = angular.module('TokenController',[]);

token.controller('TokenController',['$scope','$window', '$location','$state', '$rootScope', 'EthereumFunctionalityService',function($scope, $window, $location,$state, $rootScope, EthereumFunctionalityService){
	$scope.createToken = function(initialSupply,tokenName,tokenSymbol,decimalUnits,address){
		Token.deployed().then(function(contract){
			console.log("Inside the Contract Function");
			contract.mintToken(address,initialSupply).then(function(){
				console.log("Inside the AssetToken Function");
				$scope.transfer_success = true;
                $scope.$apply();
			}).catch(function (error) {
                console.error(error);
                $scope.has_errors = error;
                $scope.$apply();
            });
		});
	}
}]);

**Comment by Priyangaruba** [comment]
solidity file
=============
pragma solidity ^0.4.8;

contract admined{
  address public admin;

  function admined(){
    admin = msg.sender;
  }

  modifier onlyAdmin(){
    if(msg.sender != admin) throw;

    _;
  }

  function transferAdminship(address newAdmin) onlyAdmin {
    admin = newAdmin;
  }
}
contract Token {
  mapping (address => uint256) public balanceOf;
  string public name;
  string public symbol;
  uint8 public decimal;
  uint256 public totalSupply;
  event Transfer(address indexed from, address indexed to, uint256 value);

  function Token(uint256 initialSupply, string tokenName, string tokenSymbol, uint8 decimalUnits){
    balanceOf[msg.sender] = initialSupply;
    totalSupply = initialSupply;
    decimal = decimalUnits;
    symbol = tokenSymbol;
    name = tokenName;
  }

  function transfer(address _to, uint256 _value){
    if(balanceOf[msg.sender] < _value) throw;

    if(balanceOf[_to] + _value < balanceOf[_to]) throw;

    balanceOf[msg.sender] -= _value;
    balanceOf[_to] += _value;
    Transfer(msg.sender, _to,_value);
  }

}

contract AssetToken is admined, Token {

  function AssetToken(uint256 initialSupply, string tokenName, string tokenSymbol, uint8 decimalUnits, address centralAdmin) Token(0, tokenName, tokenSymbol, decimalUnits){
    totalSupply = initialSupply;
    if(centralAdmin != 0){
      admin = centralAdmin;
    }
    else
    {
      admin = msg.sender;
    }

    balanceOf[admin] = initialSupply;

    totalSupply = initialSupply;
  }

  function mintToken(address target, uint256 mintedAmount) onlyAdmin{
    balanceOf[target] += mintedAmount;
    totalSupply += mintedAmount;
    Transfer(0, this, mintedAmount);
    Transfer(this, target, mintedAmount);
  }

  function transfer(address _to, uint256 _value){
    if(balanceOf[msg.sender] < 0) throw;
    if(balanceOf[msg.sender] < _value) throw;
    if(balanceOf[_to] + _value < balanceOf[_to]) throw;

    balanceOf[msg.sender] -= _value;
    balanceOf[_to] += _value;
    Transfer(msg.sender, _to, _value);
  }
}
