### ISSUE TITLE
Transactions doesn't work for me

### ISSUE THREAD

**Issue by AndrewBryukhov** [sequelize/sequelize#5689]
I'm trying to execute this:

```
     return servSeqInstance.transaction({
        isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.SERIALIZABLE
    }, function (t) {

        // your transactions
        //return servSql.Location.create(locationName, { transaction: t });
        return Promise.all([
            servSql.Location.create(locationName, { transaction: t }),
            servSql.Location.create("2", { transaction: t }),
            servSql.Location.create("3", { transaction: t })
        ]);
    }).then(function(result) {
        // transaction has been committed. Do something after the commit if required.
        console.log(result);
    }).catch(function(err) {
        // do something with the err.
        console.log(err);
    });
```

with result:

> Executing (5f946d9d-a048-4068-8dad-24956cb1dc74): START TRANSACTION;
> Executing (5f946d9d-a048-4068-8dad-24956cb1dc74): SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
> Executing (5f946d9d-a048-4068-8dad-24956cb1dc74): SET autocommit = 1;
> Unhandled rejection TypeError: Cannot read property 'uuid' of undefined

Without transaction INSERT command is successfull.

**Comment by janmeier** [comment]
Please show the complete stack-trace. Please show the model-definition for the Location model. Preferrably as a [SSCCE](HTTP://SSCCE.ORG/)

It seems you are passing `locationName` / a number as the first parameter to create -  that is not going to work unless you have wrapped the create function, `create` expects an object of attributes as the first arg

**Comment by AndrewBryukhov** [comment]
The problem is in "transaction: t" param. If i removed them, all work properly.

**Comment by AJamesPhillips** [comment]
@AndrewBryukhov I'd recommend you follow janmeier's advice of providing a SSCCE, or close this issue if it's "no longer a problem".

**Comment by AndrewBryukhov** [comment]
Sorry guys

**Comment by juratitov** [comment]
I had the same error, but I solved it this way:

```
 const t = await sequelize.transaction();
 try {
     const purchase = await Model1.create({ .... }, { transaction: t });
     
     await Model2.update({ .... }, { .... }, { transaction: t });
     await t.commit();
} catch(error) {         
     await t.rollback(); 
}  
```

Maybe it will help someone.

**Comment by LiuWeiMr** [comment]
> I'm trying to execute this:
> 
> ```
>      return servSeqInstance.transaction({
>         isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.SERIALIZABLE
>     }, function (t) {
> 
>         // your transactions
>         //return servSql.Location.create(locationName, { transaction: t });
>         return Promise.all([
>             servSql.Location.create(locationName, { transaction: t }),
>             servSql.Location.create("2", { transaction: t }),
>             servSql.Location.create("3", { transaction: t })
>         ]);
>     }).then(function(result) {
>         // transaction has been committed. Do something after the commit if required.
>         console.log(result);
>     }).catch(function(err) {
>         // do something with the err.
>         console.log(err);
>     });
> ```
> 
> with result:
> 
> > Executing (5f946d9d-a048-4068-8dad-24956cb1dc74): START TRANSACTION;
> > Executing (5f946d9d-a048-4068-8dad-24956cb1dc74): SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
> > Executing (5f946d9d-a048-4068-8dad-24956cb1dc74): SET autocommit = 1;
> > Unhandled rejection TypeError: Cannot read property 'uuid' of undefined
> 
> Without transaction INSERT command is successfull.

What version of your sequelize? I run transaction ioslationLevel: serializable produce sql of sequelize is not same of you.This is my sql : 
![image](https://user-images.githubusercontent.com/17976666/110269923-af567900-7fff-11eb-8365-dd96bf14ccb9.png)
I hope sql :" SET SESSION TRANSACTION ISOLATION LEVEL", "SESSION" is removed of my sql
