### ISSUE TITLE
Instance.get() and Lazy loading associations doesn't plays well

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#5690]
Instance.get({plain: true}) returns the JSON representation of all the object including its associations and with the use of the [ssacl-attribute-roles](https://github.com/mickhansen/ssacl-attribute-roles ) plugin I can specify which attributes should be hidden or not, but I can't find a way to make it work when the associations are lazy loaded because I don't know how to set this lazy-loaded associations so get() recognize it. I think #3424 should be a priority, it is a serious flaw, unless there is other way to handle this.

**Comment by hendrul** [comment]
ok I could set them with Instance.setDataValue()

**Comment by afloyd** [comment]
Would be helpful if the necessity for `Instance.setDataValue(...)` requirement for lazy loaded associations to play well with `Instance.get({plain: true})` was in the docs
