### ISSUE TITLE
Associations migrating problem

### ISSUE THREAD

**Issue by AndrewBryukhov** [sequelize/sequelize#5694]
I have to create migration. I have correct models and its successfully integrates into DB. But i have problem with associations

```
'use strict';
module.exports = function (sequelize, DataTypes) {
    var items = sequelize.define('items', {
        name: DataTypes.STRING,
        volume: DataTypes.INTEGER,
        weight: DataTypes.INTEGER,
        code: DataTypes.INTEGER,
        condition: DataTypes.INTEGER
    }, {
        classMethods: {
            associate: function (models) {
                items.hasMany(models.links);
            }
        },
        instanceMethods: {
        }
    });
    return items;
};
//links.js: ...

links.belongsTo(models.items, {foreignKey: 'items'});
or

links.hasMany(models.items);
...
```

Problem at line items.hasMany(models.links); I don't see changes (new columns at tables) after db:migrate:undo:all, db:migrate

**Comment by mickhansen** [comment]
Migrations are seperate from model/association config.
You'll need to write migrations that perform the same changes as sync() would.

**Comment by AndrewBryukhov** [comment]
I must do this at migration folder for up() method?

**Comment by mickhansen** [comment]
Depends on the migration runner you use. If using umzug you'd add scripts to the up part yeah.

**Comment by AndrewBryukhov** [comment]
If i use only cli

**Comment by mickhansen** [comment]
The CLI uses umzug IIRC.

**Comment by AndrewBryukhov** [comment]
I want to do all DB operations by hand, but with cli

**Comment by mickhansen** [comment]
@AndrewBryukhov I'm not sure what you're asking, so do them by hand? Add the calls you need to.
Use the ENUM type to have enum fields, documented here: http://docs.sequelizejs.com/en/latest/docs/models-definition/

**Comment by AndrewBryukhov** [comment]
I meam:
SET seq="./node_modules/.bin/sequelize.cmd"

call %seq% model:create --name users --attributes type:enum('A', 'B', 'C') --underscored
