### ISSUE TITLE
Model name "genus" doesn't pluralize correctly

### ISSUE THREAD

**Issue by jsera** [sequelize/sequelize#5699]
the model name "genus" creates all sorts of havoc. If you create an association, method names become addGenu, setGenu, etc.

**Comment by janmeier** [comment]
You can use 
```js
{ 
  name: {
    singular: ...,
    plural: ...
}
```

In the model options to hardcode what the plural and singular forms of the name will be http://docs.sequelizejs.com/en/latest/api/sequelize/#definemodelname-attributes-options-model
