### ISSUE TITLE
TypeError: Illegal invocation at Sequelize.log

### ISSUE THREAD

**Issue by andrewex** [sequelize/sequelize#5700]
I am getting the following error on my electron app when I upgraded sequelize to 3.21.0. 

`Unhandled rejection TypeError: Illegal invocation at Sequelize.log`

everything works fine with prior versions of sequelize.

**Comment by janmeier** [comment]
Must be related to https://github.com/sequelize/sequelize/pull/5282 - What you are passing to `options.logging`?

**Comment by bumpmann** [comment]
I got the same error, it seems to crash when using `undefined`, `true` or `console.log` to the `options.logging`.

You can fix it by setting it to `false` or a custom function (i did it with a wrapper around console.log and works fine).

**Comment by janmeier** [comment]
Hmm weird - using console.log works fine for me - maybe its related to node version?

**Comment by bumpmann** [comment]
I think it's related as how electron apps work.

I get the error with
```
let x = console.log
x.apply(null, ['console.log test'])
```

but using `x.apply(console, ...` seems to fix it.

This looks like https://github.com/sequelize/sequelize/blob/v3.21.0/lib/sequelize.js#L1340 is throwing the error, though i don't know why it's happening now.

**Comment by janmeier** [comment]
Seems we have a solution then :)

**Comment by Silviu-Marian** [comment]
`new Sequelize({ /* ... */ logging: console.log.bind(console) });` worked for me.

**Comment by ua2004** [comment]
npm uninstall sequelize --save
    npm install sequelize@3.20.0 --save

helped me.

**Comment by sierran** [comment]
@ua2004 Thank you! Works like charm!
