### ISSUE TITLE
How to use queryInterface.bulkInsert for associations?

### ISSUE THREAD

**Issue by AndrewBryukhov** [sequelize/sequelize#5703]
How to seed associations?
I have tables with dependencies.
When i trying to seed tables, i was recieve:

> == 20160404141904-links: migrating =======
> Seed file failed with error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (test.links, CONSTRAINT links_ibfk_1 FOREIGN KEY (loc_begin) REFERENCES locations (id))
> seeders:

```
        return queryInterface.bulkInsert('links', [
            {type: 1, cost: 2, delivery_period: 5, carrier_id: 1, loc_begin: 1, loc_end: 2, id_item: 1, created_at: new Date(), updated_at: new Date()},
            {type: 1, cost: 2, delivery_period: 5, carrier_id: 2, loc_begin: 3, loc_end: 4, id_item: 2, created_at: new Date(), updated_at: new Date()},
            {type: 1, cost: 2, delivery_period: 5, carrier_id: 3, loc_begin: 5, loc_end: 6, id_item: 3, created_at: new Date(), updated_at: new Date()},
            {type: 1, cost: 2, delivery_period: 5, carrier_id: 4, loc_begin: 7, loc_end: 8, id_item: 4, created_at: new Date(), updated_at: new Date()},
        ], {});

```
models:
```
{
        classMethods: {
            associate: function (models) {
                links.belongsTo(models.locations, {foreignKey: 'loc_begin'}); //пункт отправления
                links.belongsTo(models.locations, {foreignKey: 'loc_end'}); //пункт назначения

                links.belongsTo(models.items, {foreignKey: 'id_item'});

                //links.hasMany(models.providers, {foreignKey: 'lnk_grp'});

                links.belongsTo(models.providers, {
                    through: 'providers_links',
                    foreignKey: 'link_id'
                })
            }
        },
        instanceMethods: {}
    }
```

migrations:

```
            loc_begin: {
                type: Sequelize.INTEGER,

                // Expected { references: { model: "value", key: "key" } } instead of { references: "value", referencesKey: "key" }

                references: 'locations',
                referencesKey: 'id'

                //onUpdate: "CASCADE",
                //onDelete: "RESTRICT"

            },
```

**Comment by mickhansen** [comment]
Please don't open the exact same issue in two locations: https://github.com/sequelize/cli/issues/282

**Comment by mickhansen** [comment]
Are there corresponding primary key entries for the foreign key values?

**Comment by AndrewBryukhov** [comment]
Ok.
Primary keys located in different js seed files.
Therefore i think that priority of bulkInsert() is incorrect.

**Comment by AndrewBryukhov** [comment]
I'm trying -seed option, but it does not work
> C:\Users\andrew\IdeaProjects\multimodal>"./node_modules/.bin/sequelize.cmd" db:seed --seed items.js --seeders-path ./seeders
> 
> Sequelize [Node: 4.4.1, CLI: 2.3.1, ORM: 3.21.0, mysql: ^2.10.2]
> 
> Loaded configuration file "config\config.json".
> Using environment "development".
> Using gulpfile ~\IdeaProjects\multimodal\node_modules\sequelize-cli\lib\gulpfile.js
> Starting 'db:seed'...
> Finished 'db:seed' after 26 ms
> Seed file failed with error: Unable to find migration: items.js

**Comment by AndrewBryukhov** [comment]
Sequence of filling tables was not help

**Comment by AndrewBryukhov** [comment]
I add autogenerated field by hands in associated tables: id: value, and now tables ok.

**Comment by borislemke** [comment]
@AndrewBryukhov did you find a fix for this? My seeders are executed in the wrong order, although the file names are in the correct order. `sequelize` is attempting to insert a child record before it's parent record is created.

**Comment by hounsellal** [comment]
I figured out how to do this:

Check out this documentation:
http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-removeConstraint

So, first you remove the foreign key constraint. Then you seed. Then you add back the constraint.

Code:
```
up: (queryInterface, Sequelize) => {

    return queryInterface.removeConstraint('users', 'users_ibfk_1', {}).then(()=>{
      return queryInterface.bulkInsert('users',
        [{}, {} ..... INSERT YOUR BULK INSERT STUFF HERE]
      , {}).then(()=>{
        return queryInterface.addConstraint('users', ['userId'], {
          type: 'FOREIGN KEY',
          name: 'users_ibfk_1',
          references: { //Required field
            table: 'users',
            field: 'id'
          },
          onDelete: 'set NULL',
          onUpdate: 'cascade'
        });
      });
    });

  },
```

**Comment by abelosorio** [comment]
Any news on this issue? I'm facing the same problem right now.

I think there are two options:

1. Provide some method to the user to **change the order**** the seeds are loaded. That way we insert first the dependencies and then the dependents.
2. **Disable** temporarily **foreign keys** checks. (I don't like to much this one).

**Comment by deksden** [comment]
@abelosorio : I opened this issue with slightly same problem in my mind: https://github.com/sequelize/sequelize/issues/9798

IMHO, for bulk inserting seed data disabling foreign key checks is good solution: but it should be simplified. If your seed data have some errors with foreign keys, enabling checks should raise an error. 

Changing order of seed is not always possible because some schemas have cross-links that require slow and painful one-by-one inserting of records. Bulk inserting them at once without foreign key's checks is much faster and simpler, but enabling checks for database should check all records for proper foreign keys.

**Comment by kasvith** [comment]
Having the same issue

**Comment by feliperyan** [comment]
No need, just prefix you seed files with `0_` and `1_` so on and so forth and `db:seed:all` will execute them in order.

**Comment by ninjasun** [comment]
@feliperyan  where did you found it?
