### ISSUE TITLE
Sequelize Sync and Postgres Schemas have bugs.

### ISSUE THREAD

**Issue by eraye1** [sequelize/sequelize#5706]
Sequelize: 1.17.3
PostGres

using sync doesn't work with schemas.  I set the schema as an option in my sequelize by passing in the config but the foreign key references don't work and the wrong databases are dropped.

I give the following as options to my sequelize:
```
options: {
    'username': 'postgres',
    'password': null,
    'database': 'database',
    'host': '127.0.0.1',   // e.g., the ip of the docker-machine instance.
    'dialect': 'postgres',
    'logging': false,
    'schema': 'test_1'
  },
````

then I run sequelize.sync, which drops the databases without appending the schema name in front of it.  If I do add the tables to the public schema, it will then not add the foreign keys and say it succeeds, but when I inspect the database with ```\d+ (database_name)```, all the foreign keys are missing

**Comment by mickhansen** [comment]
1.17 is ancient, and there has been a lot of improvements for schemas since then.
