### ISSUE TITLE
Upsert should skip notNull validations

### ISSUE THREAD

**Issue by asafyish** [sequelize/sequelize#5711]
## What you are doing?

I am trying to partial update a row, after insertion.

``` js
const test = sequelize.define('test', {
    id: {
        primaryKey: true,
        type: Sequelize.INTEGER.UNSIGNED,
        field: 'my_id'
    },
    val1: {
        type: Sequelize.STRING(36),
        allowNull: false,
        field: 'value_1'
    },
    val2: {
        type: Sequelize.STRING(36),
        allowNull: false,
        field: 'value_2'
    }
});
test.sync().then(function () {
    test.upsert({
        id: 1,
        val1: 'hello',
        val2: 'world'
    }).then(function () {

        // I was expecting this to partially update the row
        test.upsert({
            id: 1,
            val2: 'world222222'
        }).then(function () {
            console.log('Expected')
        }).catch(function (err) {
            // That's what really happens
            console.error(err);
        });
    });
});
```
## What do you expect to happen?

I want val2 only to be updated
## What is actually happening?

I am getting an exception SequelizeValidationError: notNull Violation: val1 cannot be null

Dialect: mysql
Database version: 5.6.24
Sequelize version: 3.21.0
node version: 5.7.0

**Comment by ErichBSchulz** [comment]
+1

**Comment by Americas** [comment]
You should pass the `fields` option to fix your problem.

```js
const test = sequelize.define('test', {
    id: {
        primaryKey: true,
        type: Sequelize.INTEGER.UNSIGNED,
        field: 'my_id'
    },
    val1: {
        type: Sequelize.STRING(36),
        allowNull: false,
        field: 'value_1'
    },
    val2: {
        type: Sequelize.STRING(36),
        allowNull: false,
        field: 'value_2'
    }
});
test.sync().then(function () {
    test.upsert({
        id: 1,
        val1: 'hello',
        val2: 'world'
    }).then(function () {

        let values = {
            id: 1,
            val2: 'world222222'
        };
        test.upsert(values, {
            fields : Object.keys(values),
        }).then(function () {
            console.log('Expected')
        }).catch(function (err) {
            // That's what really happens
            console.error(err);
        });
    });
});
```

@janmeier [this line](https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/model.js#L2022) could be changed to `options.fields = Object.keys(values);` and the validations would only happen on the given values by default. But I am of a mind that if you want to skip validations, then you should explicitly pass the fields option.

**Comment by BridgeAR** [comment]
@Americas what do you want to validate if there is nothing in the field? The database would fail if you may not use a empty (null) value anyway. So your proposed fix seems absolutely correct to me.

**Comment by ehe888** [comment]
This only solves program level validation issue. But doesn't handle the SQL table level non-null constraints. The generated SQL of upsert is like:

 `CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $func$ BEGIN INSERT INTO table(columns) VALUES(...); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE SET ...; RETURN 2; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert(); `

Given there is a nonNull field not in the fields list need to be updated, the CREATE phrase does not raise the exception unique_violation but notNull violation exception. 

So what is the solution to this problem?

**Comment by Americas** [comment]
We need to switch the commands, update first, insert if nothing is updated..

**Comment by Akhilesh05** [comment]
Exactly!!
Sequelize should first try to **update** then **insert**
I am also having difficulties with upsert because I get not-null violations.

**Comment by evangow** [comment]
How have other people fixed this? It still seems to be an issue

**Comment by evangow** [comment]
This is a little janky, but for anyone else that runs across this issue, what I did is right after iterating through the models to associate them, I iterate through each model to add an 'upsertById' function simply checks your 'values' includes an 'id.' If it does, run an 'update' and if not, run a 'create.' The array passed back mimics the 'upsert' array that sequelize passes back, so that if this issue is ever fixed, then it should be relatively easy to go through your code and change every 'upsertById()' to simply 'upsert()'.

Note, the below assumes you are using postgres, as I am using the 'returning: true' option on the update.

```javascript
Object.keys(models).forEach(modelName => {
  if (models[modelName]) {
    models[modelName].upsertById = values => {
      if (values.id) {
        return models[modelName]
          .update(values, { where: { id: values.id }, returning: true })
          .then(res => {
            if (res[0] !== 1)
              throw new Error("upsert should just update 1 row");
            return [res[1][0], false];
          });
      } else {
        return models[modelName].create(values).then(res => {
          return [res, true];
        });
      }
    };
  }
});
```

**Comment by phillip055** [comment]
Any updates? I could help work on it

**Comment by lfk** [comment]
Absolutely still an issue. Would it be appropriate to extend the integration test suite with the item @BridgeAR introduced in #6215, as this issue only surfaces when the engine comes into play..?

**Comment by juanmartin** [comment]
I stumbled upon this issue too, even using the `fields` option I had to overwrite `NOT NULL` fields when upserting. It should validate when inserting but if an update succeeds then this error shouldn't rise up since the not null values should already be not null from some previous successful insert.

**Comment by elizatlawy** [comment]
Any update on this issue?

**Comment by ephys** [comment]
I don't understand what the goal of this would be
Why are you using upsert if the insert part of the operation would never work? Why not just use update for that?

**Comment by ErichBSchulz** [comment]
if the database has default values specified then these maybe left blank in
an upsert

**Comment by ephys** [comment]
That is already supported, the following works in Sequelize 6:

```ts
const Test = sequelize.define('Test', {
  id: {
    primaryKey: true,
    type: DataTypes.INTEGER.UNSIGNED,
  },
  val1: {
    type: DataTypes.STRING(36),
    allowNull: false,
    defaultValue: 45,
  },
  val2: {
    type: DataTypes.STRING(36),
    allowNull: false,
  }
});

await Test.sync({ force: true });

await Test.upsert({
  id: 1,
  val2: 'world222222'
});
```

**Comment by ErichBSchulz** [comment]
What about if the default is specified in the database. Why should this be
duplicated in the client layer?

**Comment by ephys** [comment]
Sequelize uses the models as the source of truth so you should try to keep it as up to date as possible.

But even if you don't, that still works. If the property is not specified and doesn't have a default value, the upsert query simply does not try to insert a default value itself, this is the query it produces:

```ts
const Test = sequelize.define('Test', {
  id: {
    primaryKey: true,
    type: DataTypes.INTEGER.UNSIGNED,
  },
  val1: {
    type: DataTypes.STRING(36),
    allowNull: false,
    // not default value here
  },
  val2: {
    type: DataTypes.STRING(36),
    allowNull: false,
  }
});

await Test.upsert({
  id: 1,
  // val 1 is not mentioned here
  val2: 'world222222'
});
```

```sql
INSERT INTO "Tests" ("id", "val2") VALUES ($1, $2) 
ON CONFLICT ("id") DO UPDATE SET "id"=EXCLUDED."id", "val2"=EXCLUDED."val2" 
RETURNING "id","val1","val2";
```

As you can see it doesn't set any value for `val1`, it lets the database do it

**Comment by ErichBSchulz** [comment]
Ok, thanks. Sorry I'm not in this project anymore so perhaps it is not an
issue.
