### ISSUE TITLE
Sequelize Compatibility Issue

### ISSUE THREAD

**Issue by tyron-j** [sequelize/sequelize#5714]
## What you are doing?

I installed Sequelize on a remote server, but it doesn't behave the same way as it does locally. In my package.json I have:

```
"sequelize": "^3.17.1"
```

## What do you expect to happen?

Having said that, I expect whatever version I install through NPM to be compatible with the version I'm working with locally (3.19.3). However, the remote server installed 3.21.0 and this broke some of the queries (no significant errors were being thrown in particular, but the ``` count ``` method returned zeroes when I was expecting non-zero values. I was fetching by the ``` status ``` property (which is being stored as an integer), but passed in a string that evaluates to the integer instead (ex. ``` '3' ```, which works perfectly well locally). I'm not entirely sure if ``` parseInt ``` would solve this issue, but it seems inconsistent as the ``` id ``` property is being stored as an integer but I can fetch rows by ``` id ``` just fine even when I pass in an equivalent string (ex. ``` '1337' ```).

## What is actually happening?
Locally, the ``` count ``` method is returning ``` [355,51,0,152,5,1139] ```. On the remote server, the ```count ``` method is returning ``` [0,0,0,0,0,0] ```.

__Dialect:__ mysql
__Database version:__ 5.6.23
__Sequelize version:__ 3.21.0

**Comment by janmeier** [comment]
Please show a [SSCCE] (http://sscce.org) otherwise we have no way of debugging and fixing the issue

**Comment by tyron-j** [comment]
The only thing I want to know is if you guys changed the way queries work so that the comparisons are more strict. Consider the following code snippet:

```
Order.count({
  where: {
    status: '3' // If status is being stored as an integer, does this also have to be an integer?
  }
}).then(function (count) {
  // Follow-up.
}); 
```

The above code counts all orders with ``` status === 3 ``` in version 3.19.3 but returns zero in version 3.21.0.

**Comment by janmeier** [comment]
If passing a string worked before that was a bug - You should always make sure the input has the right type.

I just tried going back to 3.0, and looking at the query it doesn't parse the number (`WHERE "order"."status" = '3';`) so I don't know how this worked before :)
