### ISSUE TITLE
findAll returns wrong number of instances when using LIMIT and filtered many-to-many association

### ISSUE THREAD

**Issue by VividVisions** [sequelize/sequelize#5715]
When using `LIMIT` and a filtered many-to-many association, `findAll` returns the wrong number of instances. In my case, it was always one less than expected.

``` javascript
Item.findAll({
   limit: 2,
   include: {
      model: Category,
      required: true,
      where: {
         name: {
            $like: '%1'
         }
      }
   }
});
```

I've written a simple app to check if I can reproduce the behaviour, which I copied to this [gist](https://gist.github.com/VividVisions/dc575e1430598d5c351a514bdc03c28a). (Sorry it's not a proper test.) This code should return two items, but it returns only one.

I'm using:
- Sequelize v3.21.0
- Dialect: postgres
- PostgreSQL v9.4.4.1

**Comment by janmeier** [comment]
What does the sql look like?

**Comment by VividVisions** [comment]
This is the generated SQL:

```sql
SELECT "items".*,
       "categories"."id" AS "categories.id",
       "categories"."name" AS "categories.name",
       "categories.relation"."categoryId" AS "categories.relation.categoryId",
       "categories.relation"."itemId" AS "categories.relation.itemId"
FROM
  (SELECT "items"."id",
          "items"."name"
   FROM "items" AS "items"
   WHERE
       (SELECT "relation"."categoryId"
        FROM "relations" AS "relation"
        INNER JOIN "categories" AS "category" ON "relation"."categoryId" = "category"."id"
        WHERE ("items"."id" = "relation"."itemId") LIMIT 1) IS NOT NULL LIMIT 2) AS "items"
INNER JOIN ("relations" AS "categories.relation"
INNER JOIN "categories" AS "categories" ON "categories"."id" = "categories.relation"."categoryId") ON "items"."id" = "categories.relation"."itemId"
AND "categories"."name" LIKE '%1';
```

**Comment by mickhansen** [comment]
The include.where statement is not used in the subquery filter on the include. So the subquery will return two rows but they won't all have the correct categories.name and then be filtered further.

**Comment by Djalmar** [comment]
Same problem here, any workaround ?

**Comment by nmtdavid** [comment]
Any news, about this problem?

**Comment by Alexsey** [comment]
My issue https://github.com/sequelize/sequelize/issues/7344 is looks like the same. https://github.com/sequelize/sequelize/issues/4716 is also looks like the same and there is a workaround - add `subQuery: false`

**Comment by Djalmar** [comment]
is still a issue

**Comment by SirWojtek** [comment]
I found another workaround working for me. I've just added `distinct: true` to my `findAndCountAll`.

**Comment by mllumiquinga194** [comment]
> Any news, about this problem?

subQuery: false, 16-08-2019

**Comment by papb** [comment]
I am confused, is this still an issue with the latest Sequelize? If yes, can someone please post an [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))? Once it's done I will reopen this.

**Comment by Drilonpacarizi** [comment]
Item.findAll({
   limit: 2,
   include: {
      model: Category,
      required: true,
      separate: true       <--------------- add this if Item associate with  Category is ,1: many or many: many
      where: {
         name: {
            $like: '%1'
         }
      }
   },
  subQuery: false,           <-------- Add this
   distinct: true,               <--------
});
