### ISSUE TITLE
Eager loading and filtered many-to-many associations

### ISSUE THREAD

**Issue by VividVisions** [sequelize/sequelize#5716]
I have the models `Item` and `Category` in a many-to-many relation. When I want to get all items of a certain category, any other categories of these items are omitted. It doesn't matter if I filter in the `SELECT`

``` js
Item.findAll({
  where: {
    '$categories.id$': 1
  },
  include: {
    model: Category,
    required: true
  }
});
```

or the `JOIN` statement:

``` js
Item.findAll({
  include: {
    model: Category,
    required: true,
    where: {
      id: 1
    }
  }
});
```

I expected to get all items of category 1, complete with all other assigned categories. I know how to do it in multiple steps but I assumed Sequelize would handle this for me in one `findAll` call. Or have I completely overlooked something (it's late here)?

I'm using:
- Sequelize v3.21.0
- Dialect: postgres
- PostgreSQL v9.4.4.1

**Comment by mickhansen** [comment]
`include` simply produces a join with an added condition from your where statement.
I agree it would be nice to have a case of having an INNER JOIN or subquery to filter and then a LEFT JOIN to get all the rows.

However there's no way semantically to know what the `where` is intended to do here (filter main rows or also filter included rows).
