### ISSUE TITLE
No null check for dates when setting previous data values

### ISSUE THREAD

**Issue by Cody157** [sequelize/sequelize#5719]
## What you are doing?

``` js
beforeValidate(model) {
  return model.timestamp && !model.previous('timestamp')
}
```
## What do you expect to happen?

Return `true` when timestamp changes from `null` to some date.
## What is actually happening?

When timestamp was previously `null`, `model.previous('timestamp')` is a `Date` set at the epoch. In other words - it is getting converted to `new Date(null)`
Hence, this can never return true.

https://github.com/ojolabs/sequelize/commit/e2b2eb7313bb0dcce924e772edf8eed28e501b5a

**Comment by mickhansen** [comment]
Go ahead and open a PR with your fix, looks correct :)
