### ISSUE TITLE
feat: Add `createMultiple` association method to a `hasMany` and `belongsToMany`

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#5721]
## What you are doing?

Trying to create multiple pictures and associate them in one call by means of an associate method already added my a `hasMany` relationship.

Something like:

``` js
user.createPictures([{}, {}]);
```

The singular `user.createPicture({})` is already on `sequelize`, but the plural variant is missing.

You can use as template the `create<singular>` and `add<Plural>` methods, the last one being implemented in the code as `addMultiple`.

**Dialect:** any
**Sequelize version:** 3.21.0

**Comment by Djalmar** [comment]
bulkCreate( [ {} , {} ] ) does not solve the issue ?

**Comment by mickhansen** [comment]
@Djalmar I imagine it does, but it's about a sugar method, like we have singular create.

**Comment by diosney** [comment]
@Djalmar Exactly as @mickhansen pointed out, right now I solved this using `bulkCreate`, since I don't have other choice, but it could be great to have a companion `create<Plural>` to easily support API endpoints that creates both single resources or multiple resources, like a POST to a collection endpoint.

The code to accomplish that could be so simple as:

```js
var associationMethod = lodash.isArray(req.body) ? 'createChildModelInstances' : 'createChildModelInstance';

parentInstance[associationMethod](req.body, options);
```

Notice that is only a `s` larger, using `bulkCreate` is another history, since I've to manually set all the FK in each new record that I want to add, which complicates de controller for nothing.

And that is just one use case.

**Comment by diosney** [comment]
Besides, it adds consistency to the ORM API, since it already does support a `create<Singular>` method :smile:

**Comment by alexbooker** [comment]
@janmeier or @mickhansen,

How would I start to implement something like this?

Is it an attainable first time contribution?

Thanks.

**Comment by mickhansen** [comment]
@alexbooker Yeah it should not be too difficult actually.

**Comment by janmeier** [comment]
[This](https://github.com/sequelize/sequelize/blob/776e4851e3342ecc8b107b85ad2d07cc76697365/lib/associations/belongs-to-many.js#L744) is how create single is done for BTM - the methods are going to look pretty similar. Ideally we would like to share code between the two methods, but I don't think that is a good idea for now - create multiple would use bulkCreate, which means we can't return the created instance

**Comment by mickhansen** [comment]
`createMultiple` probably needs a way to disable bulk and just use a loop since i imagine a lot of the use cases would like the instances.

**Comment by janmeier** [comment]
Actually yeah, let's just skip bulk for now - I think 90% of the cases I can imagine you'd like to have the instance data
