### ISSUE TITLE
Limit and ofset not working correctly when include has multiple searches

### ISSUE THREAD

**Issue by Djalmar** [sequelize/sequelize#5722]
I want to get the Users who have certain Tags ordered by the user name, and paginated

## Sample

```js
{ limit: 15,
  offset: 0,
  order: 'nombres',
  include: [ 
    { model: Tag, 
      as: 'Tags', 
      where: [
         $or: [
          {
               tagName: {
                $like: 'tag1%'
               }
          },
          {
              tagName: {
              $like: 'tag2%'
              }
          }
          ]
        ]
      , required: true } ],
  subQuery: false }
```

## Result
The answer should be the first 15 users who have those tags, but it shows less

## What is actually happening?
The output is just 8 items
When i run the query it return 15 records but many users are duplicated there
There is any way to group or something?

```sql
SELECT "User"."_id", "Postulante"."nombres", "Postulante"."apellidos", "Postulante"."ci", "Postulante"."fecha_creacion", "Postulante"."fecha_modificacion", "Tags"."_id" AS "Tags._id", "Tags"."nombre" AS "Tags.nombre", "Tags"."fecha_creacion" AS "Tags.fecha_creacion", "Tags"."fecha_modificacion" AS "Tags.fecha_modificacion", "Tags.TagPostulante"."_id" AS "Tags.TagPostulante._id", "Tags.TagPostulante"."fecha_creacion" AS "Tags.TagPostulante.fecha_creacion", "Tags.TagPostulante"."fecha_modificacion" AS "Tags.TagPostulante.fecha_modificacion", "Tags.TagPostulante"."fk_postulante" AS "Tags.TagPostulante.fk_postulante", "Tags.TagPostulante"."fk_tag" AS "Tags.TagPostulante.fk_tag" 
FROM "public"."User" AS "User" 
INNER JOIN ("public"."tag_user" AS "Tags.TagUser" 
INNER JOIN "public"."tag" AS "Tags" ON "Tags"."_id" = "Tags.TagUser"."fk_tag") 
ON "User"."_id" = "Tags.TagUser"."fk_user" 
AND nombre ILIKE '%mysql%' OR nombre ILIKE '%j%' ORDER BY nombres LIMIT 15 OFFSET 0;
```

__Dialect:__  postgres 
__Sequelize version:__ latest

My system is writen in spanish(company internal politics), any where you see Postulante it means User.

**Comment by mickhansen** [comment]
You're disabling the subquery and still limiting a cartesian product, that won't ever work as intended.

**Comment by Djalmar** [comment]
When i don't use subQuery: false, limit and offset are made inside the where condition, any advise of  achieve what i am loking for ?

**Comment by mickhansen** [comment]
@Djalmar Your case is tricky, you'll probably need to filter in a subquery, not sure it's easy to express with Sequelize.

However having the LIMIT in the same level as a cartesian join won't ever yield the right number of rows (unless you're lucky).

**Comment by Djalmar** [comment]
@mickhansen thanks for the quick answer, i believe the subquery is the best option (btw sorry for the bad english)
