### ISSUE TITLE
specification for the naming of model files?

### ISSUE THREAD

**Issue by zzbo** [sequelize/sequelize#5726]
When I using sequelize.js to create RBAC models, I have encountered a strange problem with a model filename start with 'u'.

```js
// models/user.js
'use strict';

module.exports = function(sequelize, DataTypes) {
    var Users = sequelize.define('users', {
        title: {
            type: DataTypes.CHAR(64),
            allowNull: false
        }
    });

    return Users;
}
```

```js
// models/role.js
'use strict';

module.exports = function(sequelize, DataTypes) {
    var Roles = sequelize.define('roles', {
        name: {
            type: DataTypes.CHAR(64),
            allowNull: false,
            unique: true
        }
    });

    return Roles;
}
```

```js
// models/user-role.js
'use strict';

var Users = require('./user.js');
var Roles = require('./role.js');

module.exports = function(sequelize, DataTypes) {
	Users = Users(sequelize, DataTypes);
	Roles = Roles(sequelize, DataTypes);

    var UserRole = sequelize.define('user_role', {
        type: {
            type: DataTypes.INTEGER(),
            allowNull: false
        }
    });

    Users.belongsToMany(Roles, {'through': UserRole});
    Roles.belongsToMany(Users, {'through': UserRole});

    return UserRole;
}
```

```js
var Sequelize = req.server.plugins['hapi-sequelize'].db.Sequelize;
    var sequelize = req.server.plugins['hapi-sequelize'].db.sequelize;
    var models = sequelize.models;
    var note = models.note;
    var tag = models.tag;
    var users = models.users;
    var roles = models.roles;

    users.findAll({
        include: [{
            model: roles
        }]
    }).then(function(results, metadata) {
        console.log(results);
    });
```

And I will get the error:
![image](https://cloud.githubusercontent.com/assets/3053640/14423148/d1f6bdb2-000c-11e6-95f3-d79cbd05cf76.png)

If rename 'models/user.js' to 'models/suser.js', or other names dosen't start with 'u', it works. Does the sequelize.js have a specification for the naming of model files?

__Dialect:__ mysql
__Database version:__ 5.6.24
__Sequelize version:__ 3.20.0

**Comment by mickhansen** [comment]
The problem is that you're redefining your models each time. Sequelize expects that you use the same model.

Implement a cache of some sorts and you should be fine.

**Comment by zzbo** [comment]
@mickhansen because I redefine as following?
```js
Users = Users(sequelize, DataTypes);
Roles = Roles(sequelize, DataTypes);
```
but why I rename the model file, it can works?

**Comment by mickhansen** [comment]
I can't say why that might work, maybe some naming collissions, but right now it looks like you're redefening the model each time, and that is not the way to go generally.

**Comment by zzbo** [comment]
Have some demos for this problem?

**Comment by mickhansen** [comment]
No, it's sort of a given that you only call define once per model unless you've got multiple schemas or whatever.

**Comment by zzbo** [comment]
I modify user-role.js as following:
```js
'use strict';

module.exports = function(sequelize, DataTypes) {
    var models = sequelize.models;
    var userRole = sequelize.define('user_role', {
        type: {
            type: DataTypes.INTEGER(),
            allowNull: false
        }
    }, {
        classMethods: {
            associate: function(models) {
                models.users.belongsToMany(models.roles, {'through': userRole});
                models.roles.belongsToMany(models.users, {'through': userRole});
            }
        }
    });

    return userRole;
}
```
It works!
I think the document of sequelize.js is not good enough for newcomer. And it is difficult to find some examples of case.

**Comment by mickhansen** [comment]
@zzbo There are of course rooms for difference of opinion, but generally in any language when you're working with defining some entity i wouldn't think it safe to assume that it works as a singleton.

**Comment by zzbo** [comment]
I agree your opinion, a very important point is that I couldn't see the definition of it in the course of my use, because I don't know how does sequelize.js working, so I didn't realize that I had defined it, if I know I don't.

**Comment by mickhansen** [comment]
Ah, you mean an example of a folder setup? We do have the express boilerplate which gives you some clue - But you are right, it's not immediately obvious how you might set that up.

**Comment by zzbo** [comment]
I don't need example of a folder setup, in this case I want to know how to set Many-To-Many associations in different model files.
