### ISSUE TITLE
Sequelize initializes only one out of two connections

### ISSUE THREAD

**Issue by galioy** [sequelize/sequelize#5731]
I've defined 2 connections in the `/config/connections.js` file:
```js
      monolithMysql: {
        user: 'store_app',
        database: 'store',
        dialect: 'mysql',
        options: {
          dialect: 'mysql',
          host: 'dockerhost',
          port: 3306,
          logging: console.log
        }
      },
    
      postgres: {
        user: 'user_app',
        database: 'user_authentication',
        dialect: 'postgres',
        options: {
          dialect: 'postgres',
          host: 'dockerhost',
          port: 8201,
          logging: console.log
        }
      }
```
and in the different models I've put the property `connection`, so that they're distinguished, as follows:
```js
/**
  * model User
  */
    module.exports = {
    
      options: {
        connection: 'monolithMysql',
        ...
```
```js
/**
  * model Token
  */
    module.exports = {
    
      options: {
        connection: 'postgres',
        ...
```

In `/config/models.js` I set as default connection the `monolithMysql` one. *If I comment out or do not specify the `connection` property in `/config/models.js` then Sequelize hook fails to load.*
But that should be overridden by the `connection` property, if specified in the models. 

Nevertheless, when trying to query models that have `postgres` as connection, f.e.:
```js
Token.findOne(...).then();
```
it still queries them in the MySQL DB, and obviously fails... If I set `postgres` as default connection, then it will always query in the Postgres DB connection, no matter what the local `connection` property of the different models says.

**After some debugging in the module code, I found out that it initializes only 1 instance of Sequelize - an instance with the default connection, specified in `/config/models.js`**

I've been working with sequelize on 4 different projects, every time setting up the connection in this same way, *but always having only one single connection for the project*.

__Dialect:__ `mysql` and `postgres`
__Sequelize version:__ `^3.21.0`

**Comment by mickhansen** [comment]
`/config/connections.js` nor `/config/models.js`is not a Sequelize thing.
Sequelize does not work with any type of config format, you can only init an instance with a dialect and credentials.

I'm not quite sure what you're expecting here, if you need to do different connections based on environment, inititiate sequelize based on environment.

**Comment by galioy** [comment]
I don't need to have different connections based on environment. I need to have them based on different models. So, I was wondering, if I can setup a Sequelize connection through the `config` files, why can't I setup two (or multiple)?

**Comment by mickhansen** [comment]
You can, just call `new Sequelize` per database, and then define models per sequelize instance.
There's no standard setup for this so you'll need to work it out in your code.

**Comment by galioy** [comment]
Hmmm... Okay, will try out this way. You say there's no standard way, but what's the "suggested" place/file of initializing the Sequelize instance (calling `new Sequelize`)?

**Comment by mickhansen** [comment]
I'd probably have an entry file that for each set of configs creates a sequelize instance and imports the model files.

**Comment by alex-jss** [comment]
I also encountered this error. And I can not figure out how to make 2 connections to use different models for each database (in my case it is `mssql` and `postgres`). Please tell me how to solve this error?
