### ISSUE TITLE
Separated include inherits offset from main options.

### ISSUE THREAD

**Issue by jontelm** [sequelize/sequelize#5733]
If I don't set OFFSET or LIMIT in the separated query it takes the offset value from the main query.

``` models.Rooms.findAndCountAll({
      where,
      order,
      include: [{
        separate: true,
        model: models.Images,
        order: 'bild ASC',
        limit: 1,
      }, {
        separate: true,
        model: models.Weekcalendar,
        where: {
          year: moment().year(),
        },
        required: false,
        limit: 1, // ---------------------- HERE ----------------------
      }],
      limit,
      offset,
```

offset: null
OR
limit: 1 

Solves the problem.

**Comment by troyastorino** [comment]
Should this get in the 4.0 milestone to be included with the other separate: true work?(https://github.com/sequelize/sequelize/issues/4376)

**Comment by gerenrot** [comment]
For me offset=0 solved the problem.
Anyone with a moderately complex sequelize integration has to deal with it.
I think closing it as stale is a mistake.

**Comment by SBRK** [comment]
What @gerenrot said. We ran into this problem and I don't think it should have been stalled

**Comment by oeddyo** [comment]
why close this? this is super subtle and people spend hours debugging raw queries and then find this is the cause :(

**Comment by jontelm** [comment]
@mickhansen can maybe open this again?
