### ISSUE TITLE
Unit tests within docker environment fails

### ISSUE THREAD

**Issue by bwyss** [sequelize/sequelize#5734]
I am using sequelize within the context of the MEAN stack running inside a docker compose. I ran into issues when I wanted to run the testing suite.

The error I got was `Mocha exploded! docker Error: Please install sqlite3 package manually`

After digging around a bit I found out that my issue was that the bcrypt compiled on OSX will not quite work on Linux ([ref](http://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app)) as my host is OSX and the guest is Linux.

My (hackey) solution was:
a) install sqlite3 globally inside the docker image
b) modify [connection-manager.js#L21](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/connection-manager.js#L21)  so that if/when the sqlite3 require fails to then fall back on the globally installed sqlite3 version:

```
try {
    this.lib = require(sequelize.config.dialectModulePath || 'sqlite3').verbose();
  } catch (err) {
    // Hack!!! so that we can access a linux version of sqlite3 that is installed globally
    this.lib = require('/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node');
    //throw new Error('Please install sqlite3 package manually');
  }

```

This is quite the edge case, so I am am not sure this can really be considered a bug, but I wanted to point this out in case someone else runs into this issue. One more note, the error 'Please install sqlite3 package manually' was not as helpful as the actual 'err' returned.

**Comment by mickhansen** [comment]
It's an issue with NaN, you need to have the same node version inside and outside of docker. Or run npm install in the docker instance.

**Comment by bwyss** [comment]
I was not able to resolve the issue by using the same node version because the path in OSX is `/usr/lib/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node` and on Linux it's `/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node`, but maybe I'm missing something.

**Comment by mickhansen** [comment]
Oh i completely skipped the part about your host OS being OSX, yeah then you'd need to run npm install inside the container.

**Comment by bwyss** [comment]
I tried that as well without success, the error persisted, but maybe its user error on my part.

**Comment by failpunk** [comment]
I'm having this same issue in my automated tests on Heroku.  This seems really problematic...sometimes it works and sometimes it doesn't.
