### ISSUE TITLE
Unit tests within docker environment fails

### ISSUE THREAD

**Issue by bwyss** [sequelize/sequelize#5735]
I am using sequelize within the context of the MEAN stack running inside a docker compose. I ran into issues when I wanted to run the testing suite.

The error I got was `Mocha exploded! docker Error: Please install sqlite3 package manually`

After digging around a bit I found out that my issue was that the bcrypt compiled on OSX will not work on Linux ([ref](http://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app)) as my host is OSX and the guest is Linux.

My (hackey) solution was:
a) install sqlite3 globally inside the docker image
b) modify [connection-manager.js#L21](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/connection-manager.js#L21)  so that if/when the sqlite3 require fails to then fall back on the globally installed sqlite3 version:

  ```
try {
    this.lib = require(sequelize.config.dialectModulePath || 'sqlite3').verbose();
  } catch (err) {
    // Hack!!! so that we can access a linux version of sqlite3 that is installed globally
    this.lib = require('/usr/lib/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node');
    //throw new Error('Please install sqlite3 package manually');
  }

```

This is quite the edge case, so I am am not sure this can really be considered a bug, but I wanted to point this out in case someone else runs into this issue. One more note, the error 'Please install sqlite3 package manually' was not as helpful as the actual 'err' returned.

**Comment by mickhansen** [comment]
Lets stick to one issue
