### ISSUE TITLE
Get fields from query

### ISSUE THREAD

**Issue by GilVieira** [sequelize/sequelize#5740]
Hi, is there a way to get the fields of a select query executed by the command? For example:

`sequelize.query("SELECT * FROM `users`", { type: sequelize.QueryTypes.SELECT}).then(function(users, FIELDS) {
    ...
  });`

An alternative would be through the properties of the return object, but would not work if the query does not return any value.

Tks

**Comment by AndrewBryukhov** [comment]
May be: `.then(function(result) {} );`

**Comment by mickhansen** [comment]
`users` should be a key value object, try inspecting it.

**Comment by mickhansen** [comment]
There's no way to get the field for an empty result i'm afraid. We get the result from our database connector libraries.

**Comment by GilVieira** [comment]
ok, tks.
