### ISSUE TITLE
query on nested include A ----m:n---- B ----1:n---- C does not work

### ISSUE THREAD

**Issue by carera** [sequelize/sequelize#5754]
I have the following scheme in postgres:
`A ----m:n---- B ----1:n---- C`
set up with
```
A.belongsToMany(B, { through: AB });
B.belongsToMany(A, { through: AB });
B.hasMany(C);
C.belongsTo(B);
```
Now if I define the query for resource C the way to include nested models
```
options.include = [
      {
        model: models.B,
        include: [
          {
            model: models.A
          }
        ]
      }
    ];
```
I get a nice result with a list of Cs, each with a single nested B that has nested list of As.
But when i add a condition in the deepest include:
```
options.include = [
      {
        model: models.B,
        include: [
          {
            model: models.A,
            where: {propA: 'a'}
          }
        ]
      }
    ];
```
The query fails with error
```
"column B.b_id does not exist"
```
Interesting finding is that if i flip the 1:N relation the other way around
``A ----m:n---- B ----n:1---- C`
The query works but the relations do not fulfill my needs.
Any ideas?

**Comment by janmeier** [comment]
Duplicate of https://github.com/sequelize/sequelize/issues/3718

**Comment by Assemble-illicit1** [comment]
> Duplicate of [#3718](https://github.com/sequelize/sequelize/issues/3718)





https://ecstatic4.github.io/qgpP5zhXN3AB7qzopriWVhhsUfmAkM9bWTqSoMb8P-g/
