### ISSUE TITLE
Can not execute raw SQL queries for sqlite3 (sequelize.query)

### ISSUE THREAD

**Issue by 907th** [sequelize/sequelize#5755]
I try to use raw SQL queries with `sqlite` adapter:

```
    q = db.query(
      `SELECT c.* FROM cities c ....`,
      {
        type: db.QueryTypes.SELECT,
        model: City,
        replacements: { ... }
      }
    );
```

But I'm getting this error:

```
Executed (default): SELECT c.* FROM ... in 5ms
/Users/laise/Work/itowl/eps-online-service-countries/node_modules/sqlite3/lib/trace.js:28
                    throw err;
                    ^

TypeError: Cannot read property 'geonameid' of undefined
    at /Users/laise/Work/itowl/eps-online-service-countries/node_modules/sequelize/lib/dialects/sqlite/query.js:161:46
    at /Users/laise/Work/itowl/eps-online-service-countries/node_modules/lodash/lodash.js:12449:23
    at /Users/laise/Work/itowl/eps-online-service-countries/node_modules/lodash/lodash.js:4332:15
    at baseForOwn (/Users/laise/Work/itowl/eps-online-service-countries/node_modules/lodash/lodash.js:2731:24)
```

SQL is valid and successfully executes.

Furthemore, a query with (undocumented?) `raw: true` option set executes succesfully:

```
    q = db.query(
      `SELECT c.* FROM cities c ....`,
      {
        raw: true,
        type: db.QueryTypes.SELECT,
        model: City,
        replacements: { ... }
      }
    );
```

The source of the issue is `type = tableTypes[name]` assignment [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L159).
`tableTypes` is always `undefined`, because it is being assigned in `tableTypes = columnTypes[tableName]` line [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L147) and `columnTypes` is always equal to `{}`.

__Dialect:__ sqlite
__Database version:__ sqlite3
__Sequelize version:__ 3.21.0

**Comment by 907th** [comment]
This query works too:
```
    q = db.query(
      `SELECT c.* FROM cities c ....`,
      {
        tableNames: ["cities"],
        type: db.QueryTypes.SELECT,
        model: City,
        replacements: { ... }
      }
    );
```

Seems like the adapter was not able to deduce a table name from my SQL.
I was not able to find any documentation on `raw` and `tableNames` params.
I think it needs to be documented somewhere.

**Comment by 907th** [comment]
A full query:

```
        SELECT c.* FROM ft_search f LEFT JOIN cities c ON f.geonameid == c.geonameid
        WHERE f.names MATCH :prefix AND c.country = :countryAlpha2
        ORDER BY c.population DESC
        LIMIT :count OFFSET :skip
```

And I (see that you handle)[https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L253] only `FROM ...` tables. May be `JOIN ...` tables should be handled too?

**Comment by mickhansen** [comment]
Generally you want to use `raw: true`, it should probably be the default actually.
When using non-raw queries sequelize assumes (poorly) that it's an internal call that has all the correct internal values.

**Comment by ivo-stefchev** [comment]
sequelize/lib/dialects/sqlite/query.js
`var columnTypes = {};
    ...
 var tableName = model.getTableName().toString().replace(/`/g, '')
   , tableTypes = columnTypes[tableName];
 ...
 var type = tableTypes[name];`
columnTypes never sets any key, hence tableTypes would always be undefined.

**Comment by witem** [comment]
Can you fix this in v3 branch?

**Comment by felixfbecker** [comment]
Feel free to backport

**Comment by witem** [comment]
@felixfbecker done
