### ISSUE TITLE
Simple limit property problem

### ISSUE THREAD

**Issue by AndrewBryukhov** [sequelize/sequelize#5761]
```
Executing (default): SELECT `id`, `name`, `country_id`, `created_at`, `updated_at` FROM `locations` AS `locations` WHERE `locations`.`id` >= '0' LIMIT '20';
```

>  [SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''20'' at line 1]

```
Locations.findAll({where: {id: {gte: startIdx}}, limit: pageSize}).then(function (locs) {
});
```

Without limit property there is no errors.

**Comment by janmeier** [comment]
parseInt is your friend

**Comment by janmeier** [comment]
The reason this worked previously is that we didn't properly escape the limit parameter before - now we do, so the limit is escaped as a string

**Comment by AndrewBryukhov** [comment]
great
