### ISSUE TITLE
Suggest to implement updated_at result for models.update()

### ISSUE THREAD

**Issue by AndrewBryukhov** [sequelize/sequelize#5762]
I suggest to implement **updated_at** result for **models.update()** with specific option flag.
I'm found in documentation only this:

`[options.returning=false]	Boolean	Return the affected rows (only for postgres)`
But i'm using mysql.

For this purpose:
```
Locations.update({name: req.body.name}, {where: {id: req.body.city_id}}).then(function (result) {
    Locations.findById(req.body.city_id, {attributes: ['updated_at']}).then(function (result) {});
});
```

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2514

Already implemented.

**Comment by AndrewBryukhov** [comment]
How i can use it?

**Comment by mickhansen** [comment]
Not sure what you mean? It's part of the `Model.update` codepath so you use it when you use that method.

**Comment by AndrewBryukhov** [comment]
In result of calling update i have only array[1] with field: id = 1;

**Comment by mickhansen** [comment]
You have an array where? Are you using `returning: true`? Your original code sample did not show that.
Can you also try posting the SQL executed?

**Comment by AndrewBryukhov** [comment]
returning option is for postgres only, how i can use it for mysql?

```
Executing (default): UPDATE `locations` SET `name`='Город 12123666777999123',`updated_at`='2016-04-18 16:00:12' WHERE `id` = '1'
Executing (default): SELECT `updated_at` FROM `locations` AS `locations` WHERE `locations`.`id` = '1'
```

**Comment by mickhansen** [comment]
You can't, i updated my comment, you need to re-read the model update return signature.

**Comment by AndrewBryukhov** [comment]
I was mean array as result for:
`Locations.update({name: req.body.name}, {where: {id: req.body.city_id}}).then(function (result)`

How i can reread?

**Comment by AndrewBryukhov** [comment]
Could you put simple example? Can't understand this (

**Comment by mickhansen** [comment]
MySQL does not support returning the actual values.
All dialects return an array containing first the number of affected rows, and second the affected rows (if the dialect supports it).

`update().spread(function (affectedCount, affectedRows /* not supported by mysql */) {});`

**Comment by AndrewBryukhov** [comment]
But time value for update_at field is created on sequelize side, therefore sequelize can parse special option for returning current time, that used for update() call.

**Comment by mickhansen** [comment]
You can't access the values for bulk update calls, use a non bulk update if you wish to see the values after updating.

**Comment by AndrewBryukhov** [comment]
i use function: models.update() only for one instance.
I doesn't know instance model from models.
How to get updated_at value? I see only result[0] = 1 <= counter of affected rows only.

**Comment by mickhansen** [comment]
Do a find first to get the instance.
As i mentioned three times now you can't get the inserted values unless you use postgres.

**Comment by AndrewBryukhov** [comment]
Does update_at field is created NOT on sequelize side?

**Comment by mickhansen** [comment]
Yes it is, but we don't return it since it would be an incomplete experience, take a look at the source code.

**Comment by AndrewBryukhov** [comment]
Ok, how i can to "find first" ?

**Comment by mickhansen** [comment]
Location.findOne({where: {}})

**Comment by AndrewBryukhov** [comment]
I mean, it is equals first message method.
