### ISSUE TITLE
There is a createAssociation method but not a createAssociations method

### ISSUE THREAD

**Issue by alexbooker** [sequelize/sequelize#5763]
According to [the documentation](http://docs.sequelizejs.com/en/latest/api/associations/has-many/) and indeed, [the source code](https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/associations/has-many.js#L143), there is a `createAssociation` method but not a `createAssociations` method. There is, however, both `addAssociation` and `addAssociations` functions!

I would like a `createAssociations` feature so I can insert multiple associated records at once (similar to `bulkCreate`):

```javascript
Poll
  .create({
    question: 'What is the best Node.js ORM?'
  })
  .then(createdPoll => {
    createdPoll.createAssociations([ 
      { text: 'Sequelize' },
      { text: 'Sequelize' }
    ])
  })
```

What do you think?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/5721
