### ISSUE TITLE
queryInterface.createTable is case sensitive

### ISSUE THREAD

**Issue by merlinpatt** [sequelize/sequelize#5764]
## What you are doing?
```js
queryInterface.createTable('members', {
  id: {
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
    type: Sequelize.INTEGER
  },
  lastName: {
    type: Sequelize.STRING
  },
  firstName: {
    type: Sequelize.STRING
  }
});
```

## What do you expect to happen?
I wanted to create a table `members` with columns of `id`, `lastName`, and `firstName 

## What is actually happening?
I got a table `members` but there was no `id` column.

Also, the columns were `lastname` and `firstname` (both lowercase n instead of uppercase)

__Dialect:__ postgres
__Database version:__ 9.5.0
__Sequelize version:__ 3.20.0

**Comment by mickhansen** [comment]
Can you show the SQL query?

**Comment by merlinpatt** [comment]
How do I do that?

**Comment by mickhansen** [comment]
You can add `logging: console.log` to the options object of most calls

**Comment by janmeier** [comment]
Ping @merlinpatt

**Comment by merlinpatt** [comment]
This hasn't come up since I posted about it. Apologies for not responding sooner. I'll close this for now and if I encounter it again, I'll reopen it.
