### ISSUE TITLE
How can I create custom functions related to a model?

### ISSUE THREAD

**Issue by Gacnt** [sequelize/sequelize#5766]
Hi,

I was going to create a separate `.js` file and have it so I could make common queries (e.g. findById) or something instead of having to type out the entire `where:  { }` and what not repetitively.

e.g. 

instead of
```
models.User.findOne({
    where: { id: 1 },
    include: [{ // }}
})
.then(function(blah) {
  // We Won!
})
.catch(function(err) {
   // Handle it
});
```

I'd rather just do

`var foundUser = await models.User.findById(1);`

How can I implement my own custom `.findById` method? I was looking through the readme but couldn't seem to find what I was looking for, is it a instance method or? Thanks.

**Comment by Gacnt** [comment]
Figured it out thanks.

**Comment by mickhansen** [comment]
And you can really also simply do `models.User.method = function() {}`
