### ISSUE TITLE
seed data containing JSONB columns in postgres

### ISSUE THREAD

**Issue by keymsg** [sequelize/sequelize#5767]
I am trying to run the seed data script for inserting bulk records into the table on postgres db. 
My data file persons.js looks like this:

```
(function (seedData) {
    seedData.defaultData = [
        {
            "firstName": "Abcd",
            "middleName": "Xyz",
            "lastName": "Mnop",
            "birthDate": "2000-12-20T05:39:17",
            "address": {
                "street": 1234
            }
        }
    ];
})(module.exports);

// the seed script code looks like this:
var data = require('persons').defaultData;
return queryInterface.bulkInsert('Persons', data, {});
```

When I run the seed command, I get the following error:
The issue here is only caused by the address field. If I remove it, the seed completes successfully.

Could you please help? Thanks.

```
Loaded configuration file "config\config.json".
Using environment "development".
Using gulpfile c:\Keyur\Workspaces\LimeTable\Source\api\School\node_modules\sequelize-cli\lib\gulpfile.js
Starting 'db:seed:all'...
== 20160418164736-person: migrating =======
Seed file failed with error: val.replace is not a function

Dialect: postgres 
```

**Comment by mickhansen** [comment]
Does it work if you use a regular model bulkcreate?

**Comment by keymsg** [comment]
Model.bulkCreate works just perfect. Thanks

**Comment by mickhansen** [comment]
Then the issue is that the queryInterface doesn't know about the types for each input

**Comment by keymsg** [comment]
Is there any way I can fix it in my code to get that working? Thanks

**Comment by markelog** [comment]
So you currently can't add jsonb data with seeds?

**Comment by markelog** [comment]
Ping, is there any possible solution or estimation for the fix?

**Comment by janmeier** [comment]
@markelog The estimate is somewhere between now and forever :) 

Generally, if something is bothering you in an open source project, the easiest is to fix it yourself - [scratch your own itch](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar). That's how Mick and I got involved in the project as well :)

**Comment by markelog** [comment]
> Generally, if something is bothering you in an open source project, the easiest is to fix it yourself

Nuh, sounds like hipster thing to do, fix it i say!

In all seriousness, if it is a open source project it doesn't mean you can't have task prioritizations, deadlines, roadmap and staff. 

I am considering tackling this thing, but it is important to note that last two comments from users weren't answered - https://github.com/sequelize/sequelize/issues/5767#issuecomment-212415536, which might makes me thing that even if i provide pr for this it wouldn't be considered

**Comment by janmeier** [comment]
We try to answer all comments, but given that we are only 2-5 people sometimes it slips :)

A PR would be very welcome!

**Comment by markelog** [comment]
Before doing the pr, could clarify me that bit - 

> So you currently can't add jsonb data with seeds?

Am i right in assuming so?

**Comment by janmeier** [comment]
Correct :)

**Comment by tsabolov** [comment]
It seems to work when wrapping the JSONB field's content with ```JSON.stringify```, i.e.:

```js
        {
            "firstName": "Abcd",
            "middleName": "Xyz",
            "lastName": "Mnop",
            "birthDate": "2000-12-20T05:39:17",
            "address": JSON.stringify({
                "street": 1234
            })
        }
```

Of course, it is need to be tested.

**Comment by b0gok** [comment]
> It seems to work when wrapping the JSONB field's content with JSON.stringify

It's working for me too.

**Comment by andRyanMiller** [comment]
> In all seriousness, if it is a open source project it doesn't mean you can't have task prioritizations, deadlines, roadmap and staff.

@markelog - [please read this](https://hueniverse.com/2016/01/26/how-to-use-open-source-and-shut-the-fuck-up-at-the-same-time/).

**Comment by menocomp** [comment]
it fixed my issues when the column is jsonb, but now I have the same issue with jsonb[] (array of jsonb column), how can I fix it if I am using queryInterface.bulkInsert?

**Comment by DiegoRBaquero** [comment]
@menocomp Did you ever fix that? I'm having the same issue with an array of json

**Comment by DiegoRBaquero** [comment]
Based on: https://stackoverflow.com/questions/18099589/postgres-array-of-json-avoid-casting

Having `json[]` column named examples, this worked:

```js
examples: '{"' + JSON.stringify({
        name: 'Diego'
      }).replace(/"/g, '\\"') + '", "' + JSON.stringify({
        name: 'Pacho'
      }).replace(/"/g, '\\"') + '"}',
```

Hope it's useful!

**Comment by menocomp** [comment]
@DiegoRBaquero No, actually I am not looking at this at the moment.
