### ISSUE TITLE
Issue while updating associated model ( with no primary key)

### ISSUE THREAD

**Issue by Xenope** [sequelize/sequelize#5773]
Hello,

I'm trying to update a model and its association based on this example : 
http://stackoverflow.com/questions/33918383/sequelize-update-with-association

I have a doc and a docmem model defined as following : 
**model doc :**
`let p_doc = sequelize.define('doc', {
    docincde: {
      type: DataTypes.INTEGER,
      allowNull: false,
      autoIncrement: false,
      defaultValue: 0,
      primaryKey: true
    } ,
etc ....
  })`

**model docmem :**
`let p_docmem = sequelize.define('docmem', {
    docincde: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    memo: {
      type: DataTypes.TEXT,
      allowNull: true
    }
   })`
**note that there is no primary key in this model (legacy database)**

docmem is associated like this : 
`models.doc.hasOne( models.docmem, { as: 'docmem', foreignKey: 'docincde'});`

and i added `models.docmem.removeAttribute('id');` because there is no primary key.

Here is my simple unit test :

``` js

    /** modify memo */
  it.only('modify memo', function (done) {

    let models = testService.getTestDatabase();

    return models.doc.find({where: [{docincde : 57286}], include: [ { model : models.docmem, as: 'docmem' } ] })
    .then(resultData => {
      //here i got the good instance of docmem with the current value of memo
      console.dir(resultData.docmem);
      //and here it fails when i try to update the memo value
      resultData.docmem.update({memo : 'fooooooo'}).then (()=> {  
        done();
      })       
    })
    .catch(done);
  })
```

I expected the memo value of docmem to be updated, but instead got this error :

> Unhandled rejection TypeError: Cannot convert undefined or null to object
>     at Function.keys (native)
>     at null.<anonymous> (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/lib/instance.js:660:56)
>     at tryCatcher (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:502:31)
>     at Promise._settlePromise (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:559:18)
>     at Promise._settlePromise0 (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:604:10)
>     at Promise._settlePromises (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:683:18)
>     at Async._drainQueue (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:16)
>     at Async._drainQueues (/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/async.js:148:10)
>     at Immediate.Async.drainQueues [as _onImmediate](/home/jschlosser/edevelo/workspaceAurelia/webapi/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
>     at processImmediate [as _immediateCallback](timers.js:383:17)

I tried to do the same with another associated model which has a primary key and it works great, so this could come from the fact that there is no primary key in the docmem model.

**Comment by mickhansen** [comment]
We generally assume a primary key: https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L126

We also support `whereCollection` but that wouldn't be set for a prefetch.
