### ISSUE TITLE
insert 2016-4-21 17:36:19 but the result is 2016-04-22 01:36:19

### ISSUE THREAD

**Issue by wu123456** [sequelize/sequelize#5774]
All of my code is below:

```js
var Sequelize = require('sequelize');
var db = new Sequelize('****', '*****', '****',
            {
                "host" : "*******",
                "define" : {
                    "timestamps": false,
                    "freezeTableName": true
                }
            });

var sq =  db.define('t_sign_record',{
    id: {type: Sequelize.INTEGER, autoIncrement: true, primaryKey: true, unique: true},
    user_id: {type: Sequelize.INTEGER},
    day: {type: Sequelize.STRING},
    ip: {type:  Sequelize.STRING},
    status : {type: Sequelize.BLOB, defaultValue: '0'},
    create_time: {type: Sequelize.STRING, comment: '创建时间'},
    update_time: {type: Sequelize.STRING, comment: '更新时间'}
});

var date = new Date();

var day = "" + date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate();
var ip = "192.168.43.44";
var create_time = day + " " + date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
sq.create({user_id: '12', day: day, ip : ip, create_time : create_time, update_time : create_time});`
```

and then I run node it 
it prints out 
Executing (default): INSERT INTO `t_sign_record` (`id`,`user_id`,`day`,`ip`,`status`,`create_time`,`update_time`) VALUES (DEFAULT,'12','2016-4-21','192.168.43.44','0','2016-4-21 17:36:19','2016-4-21 17:36:19');

but the result in mysql the create_time and update_time are both 2016-04-22 01:36:19

I did not set the UTC, but I saw the sql sentence, so I believe the result should be the same as the sql sentence execute.

I hope someone can help me.Thanks.

**Comment by janmeier** [comment]
I get `Executing (default): INSERT INTO `t_sign_records` (`id`,`user_id`,`day`,`ip`,`create_time`,`update_time`) VALUES (DEFAULT,'12','2016-4-21','192.168.43.44','2016-4-21 12:5:53','2016-4-21 12:5:53');`, which matches my local time. And the data in mysql matches fine

```
+----+---------+-----------+---------------+--------+-------------------+-------------------+
| id | user_id | day       | ip            | status | create_time       | update_time       |
+----+---------+-----------+---------------+--------+-------------------+-------------------+
|  1 |      12 | 2016-4-21 | 192.168.43.44 | NULL   | 2016-4-21 12:5:53 | 2016-4-21 12:5:53 |
+----+---------+-----------+---------------+--------+-------------------+-------------------+
```
When you are inserting strings into string columns, sequelize will not do any kind of formatting, so there must be something else at play here. 

Is your table created by sequelize, or is it a pre-existing table, where the columns actually have timestamp data type - in that case its mysql doing the formatting, not sequelize, and we can't really do much about that

**Comment by mickhansen** [comment]
You should really insert date objects directly instead of converting to a string.

**Comment by wu123456** [comment]
@janmeier @mickhansen
I copy the sql ，and execute it in mysql，it's right.So I think mysql did not format it.
The table is create by sql，not sequelize.I will show the create table sql soon. But now I am outside.Thank you.

**Comment by wu123456** [comment]
The create table sql is 
`CREATE TABLE `t_sign_record` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL COMMENT '用户ID',
  `day` date NOT NULL COMMENT '签到日期',
  `ip` varchar(16) DEFAULT NULL COMMENT '客户端IP',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '记录状态',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`,`day`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8`

I think there must be somewhere wrong.Do you think my code is wrong?I think it's not good, but it should still work well.I am really confused.

**Comment by janmeier** [comment]
Very likely related to timezone - sequelize sets the default connection timezone to UTC, but if you do a select directly through mysql the date will be shown in your local timezone. You can set timezone in the constructor http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=timezone

**Comment by wu123456** [comment]
@janmeier
I think sequelize executes a sql like ` set time_zone='+0:00'` for default.
And my mysql client is +8:00. 
I think sequelize should not set time_zone with a default value.

**Comment by janmeier** [comment]
I know it does - thats what I told you above :)

I also linked to where you can change that default
```js
var db = new Sequelize('****', '*****', '****',
            {
                "host" : "*******",
                "timezone" : "+08:00",
                "define" : {
                    "timestamps": false,
                    "freezeTableName": true
                }
            });
```

**Comment by wu123456** [comment]
Oh,I know.
Thank you for your help.

**Comment by aiwb** [comment]
@mickhansen 
How can i turn the default createdAt and updatedAt field type from DATE to INT or BIGINT in mysql ?
In our company, the DBA prevent us from using DATE or TIMESTAMPS type in database.
