### ISSUE TITLE
Pass options to custom getters for association-based fields

### ISSUE THREAD

**Issue by akre54** [sequelize/sequelize#5775]
I have an m:m relationship (projects and users) and I want to define a virtual field called `enabled` that lets me know that there is an entry in my join table for the relation. (i.e. it desugars to `project.hasUser(user)`)

My `enabled` virtual field setter takes a value object, which I've kind of hacked around to destructure an `[enabled, user]` array pair and that works fine. However, getter fields are only [called with the key name](https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/instance.js#L187), which makes it impossible to pass any extra arguments to the getter function. 

Here's what my code looks like currently.

```js
const Project = sequelize.define('Project', {
  // ...
  enabled: {
    type: DataTypes.VIRTUAL,
    set([user, enabled]) {
      let promise
      if (enabled) {
        promise = user.addProject(this)
      } else {
        promise = user.removeProject(this)
      }
      return promise.then(() => this.setDataValue('enabled', enabled))
    },
    get() {
      return p.hasUser(user) // ??
    }
  }
}, {
  classMethods: {
    associate(models) {
      Project.User = Project.belongsToMany(models.User)
    }
  }
})
```

If I could pass `options` to `get`/`set` I would be able to pass along this dependency data, which could be useful in a host of other uses too.

I understand this implementation suffers the N+1 problem, so my original solution was to query `user.getProjects()` and then check if the project is in that array in JS, which also seems like a hack.

Are there any alternative solutions?

__Sequelize version:__ 3.21.0

**Comment by mickhansen** [comment]
You can try `this.$options`, but i'm not sure if the options from findAll are passed all the way dwon.

**Comment by akre54** [comment]
Ok this is a good hackaround in the meantime.

I'm thinking virtual fields may not be the best approach to this problem. Any other ideas?

**Comment by mickhansen** [comment]
virtuals could work, but you probably want a hook to modify the value based on whether or not the virtual was requested

**Comment by akre54** [comment]
What would that look like?

On Fri, Apr 22, 2016, 15:13 Mick Hansen <notifications@github.com> wrote:

> virtuals could work, but you probably want a hook to modify the value
> based on whether or not the virtual was requested
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5775#issuecomment-213558193>
>
-- 

Adam K (mobile)

**Comment by mickhansen** [comment]
You'd use an afterFind hook, check options to see if the virtual was requested, fetch and inject as needed.

**Comment by akre54** [comment]
ok cool. Thanks

On Fri, Apr 22, 2016, 15:17 Mick Hansen <notifications@github.com> wrote:

> You'd use an afterFind hook, check options to see if the virtual was
> requested, fetch and inject as needed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/issues/5775#issuecomment-213559290>
>
-- 

Adam K (mobile)
