### ISSUE TITLE
Creating elements of a "HasMany" association does not work

### ISSUE THREAD

**Issue by boetnet** [sequelize/sequelize#5778]
## What you are doing?
Hi all,

I am just using the example from the doc web site and it does not seems to work.
http://docs.sequelizejs.com/en/latest/docs/associations/#creating-elements-of-a-hasmany-or-belongstomany-association

```js
var Product = sequelize.define('product', {
    title: Sequelize.STRING
});

var Tag = sequelize.define('tag', {
    name: Sequelize.STRING
});

Product.hasMany(Tag);

sequelize.sync({ force: true })
    .then(function () {
        Product.create({
            id: 1,
            title: 'Chair',
            Tags: [
                { name: 'Alpha' },
                { name: 'Beta' }
            ]
        }, {
                include: [Tag]
            }).then(function(value) {

            })
    });
```

## What do you expect to happen?
I expect tags to be created at the same time that the product.

## What is actually happening?
The only output is the following:

Executing (default): INSERT INTO `products` (`id`,`title`,`createdAt`,`updatedAt`) VALUES (1,'Chair','2016-04-21 22:30:27.710 +00:00','2016-04-21 22:30:27.710 +00:00');

I am thus missing the tags creation.

__Dialect:__ sqlite
__Database version: 3.1.2
__Sequelize version: 3.21.0

**Comment by mickhansen** [comment]
That should just work. You'll have to provide more info or add some debugging in the code.
Is product.get('Tags') available after create?

**Comment by janmeier** [comment]
You need a lower case the in tags, because the name of the model is in lower case

**Comment by boetnet** [comment]
Thank you for your answers.

```js
Product.create({
            id: 1,
            title: 'Chair',
            Tags: [
                { name: 'Alpha' },
                { name: 'Beta' }
            ]
        },
```
should indeed be changed to
```js
 Product.create({
            id: 1,
            title: 'Chair',
            tags: [
                { name: 'Alpha' },
                { name: 'Beta' }
            ]
        },
```

Could the documentation be updated to avoid this question being asked a second time ? Can I help?

**Comment by mickhansen** [comment]
@boetnet The documentation could be made clearer i guess, but i'm not sure why you assumed a capitalized name actually :)

**Comment by boetnet** [comment]
@mickhansen I didn't assume anything. I just made a copy paste from the doc. :)
Thanks for the amazing work !

**Comment by mickhansen** [comment]
Ah, then there's an issue with the docs! Looks like we changed model names to lowercase but not the association names in create.
