### ISSUE TITLE
What is correct way to test sequelize database in CRUD?

### ISSUE THREAD

**Issue by xdvarpunen** [sequelize/sequelize#5779]
As stated in issue [#5770](https://github.com/sequelize/sequelize/issues/5770), test code written in different way causes unknown problems. Is there preferred way/good way to test sequelize based code? There is nothing documented about this. Complete Express CRUD example would be awesome.

_Libraries used: chai, mocha_

```javascript
// bad code causing unknown problems from prefix to missing foreign key randomly
it('It should create Fish table, Fish and Eye table with Eye as Fish child', function (done) {
    models.Fish.sync().then(function () {
        models.Fish.create({ id: 2, name: 'Test Fish 2' }).then(function () {
            models.Eye.sync().then(function () {
                models.Eye.create({ id: 2, FishId: 2, name: 'Test Eye 2' }).then(function () {
                                    done();
                }).catch(function (err) {
                    console.log(err);
                    done();
                });
            }).catch(function (err) {
                console.log(err);
                done();
            });
        }).catch(function (err) {
            console.log(err);
            done();
        });
    }).catch(function (err) {
        console.log(err);
        done();
    });
});
```

```javascript
// Good code
it('It should create Fish table, Fish and Eye table with Eye as Fish child', function () {
  return sequelize.sync({ 
    force: true,
    logging: console.log
  }).then(() => {
    return Fish.create({ id: 2, name: 'Test Fish 2' }).then(function () {
      return Eye.create({ id: 2, FishId: 2, name: 'Test Eye 2' })
    });
  })    
})
```

-XDVarpunen

**Comment by mickhansen** [comment]
I generally run a `sync({force: true})` in beforeEach.
If i want faster test performance i'll run a sync only in before and truncate specific tables in beforeEach.

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
