### ISSUE TITLE
undefined when using raw query

### ISSUE THREAD

**Issue by ramaravindd** [sequelize/sequelize#5785]
Hi,

I am parsing a JSON data and trying to insert the values in .csv. When one of the value is null, sequelize reads it as undefined and stops parsing the remaining data. 

Is it possible to just insert Null value when the field is undefined and continue the parsing till the end of the file?

**Comment by janmeier** [comment]
Please show a [SSCCE](http://sccee.org)

**Comment by ramaravindd** [comment]
JSON file:
   {	"color":"black",
	"height":"12.7",
	"type":"table",
	"chair":"included",
	"material":"wood"
   },
   {   "color":"red",
       "height":"10.6",
       "type": "bean bag",
       "material":"leather"
}

If you look at the json, there is no chair for "bean bag". 

I parse the json and insert into mysql using the following query
for(var i=0; i < jsonContent.data.length; i++)
 {
sequelize.query("insert into general(color,height,type,chair,material) values (:a,:b,:c,:d,:e)",{,replacements:{a:jsonContent.data[i].color, b:jsonContent.data[1].height,c:jsonContent.data[i].type,d:jsonContent.data[i].chair,e:jsonContent.data[i].material},type: sequelize.QueryTypes.INSERT})
    .then(function(general) {
      console.log(a);
 })
}

So when there is no value for chair, I get the result as undefined and it stops executing. 

Output:
 i = 0
color: black
height: 12.7
type: table
chair: included
material:wood
i = 1
color: red
height: 10.6
type: bean bag
chair: undefined
      throw new Error('Named parameter "' + value + '" has no value in the given object.');

I want to ignore the undefined and just pass the values as null.

**Comment by janmeier** [comment]
That you'll have to handle in your own code - when you pass undefined, we try to insert undefined :)

**Comment by ramaravindd** [comment]
But I am not able to proceed further. The code stops running as soon as it finds undefined. I don;t bother even if undefined is inserted.

**Comment by janmeier** [comment]
Then loop through each object and check, `if typeof o[k] === 'undefined' then o[k] = null` before inserting

**Comment by ramaravindd** [comment]
ok. thanks for the help
