### ISSUE TITLE
Polymorphic BelongsTo

### ISSUE THREAD

**Issue by marcusmota** [sequelize/sequelize#5787]
Is that possible use Polymorphic Association with belongsTo? 

For example, my user can be all person that use app, but some users are doctor, some are dentist, some are nutricionist. so i want to load the user with userData, my tables are describe as follows

User Table
id
email
password
model_id
model_name

Doctor Table
crm

Dentist Table
cro

In docs i just saw belongsToMany (that's not what i want)

**Comment by janmeier** [comment]
I think you are looking for table inheritance https://github.com/sequelize/sequelize/issues/1243 and https://github.com/sequelize/sequelize/issues/1679.

You could also add a `type` column or similar to the user table, to be able to load the correct sub-type

**Comment by marcusmota** [comment]
Thanks for help but it i'snt what i want, i was trying this https://github.com/sequelize/sequelize/issues/1307

**Comment by janmeier** [comment]
That's what I was suggesting with the `type` column - Have a look at [association scopes](https://github.com/sequelize/sequelize/pull/2268)

You'll then manually have to call `getDentist / getDoctor`, or implement a custom method that checks the `type` column
