### ISSUE TITLE
.sync() options.logging=console.log

### ISSUE THREAD

**Issue by yanxyz** [sequelize/sequelize#5788]
The method `Sequelize.prototype.sync` says "options.logging=console.log"(Line 967 of the file "lib/sequelize.js"), however, it's default value is `false`  due to  line 978:

```js
options.logging = options.logging === undefined ? false : options.logging;
```

The method `Sequelize.prototype.query` fallbacks to `this.options.logging`,  method `truncate` and some other methods by contrast do not test `options.logging`. So which should be chosen here?

**Comment by mickhansen** [comment]
truncate/etc should pass options along to sequelize.query, sequelize.query ultimate decides whether to log or not.

The logic for all queries SHOULD (might not be) `options.logging === undefined ? this.sequelize.options.logging : options.logging`

**Comment by yanxyz** [comment]
So the fix is as bellow?

line 967: `@param {Boolean|function} [options.logging] A function that logs sql queries, or false for no logging`
line 978  `options.logging === undefined ? this.options.logging : options.logging`

**Comment by janmeier** [comment]
Shouldn't it be enough to have this logic only in `sequelize.prototype.query`?

**Comment by mickhansen** [comment]
@janmeier I believe so, but i think there were historic reasons that no one remembers now.
