### ISSUE TITLE
toJSON method not getting invoked on res.json(<resultset>)

### ISSUE THREAD

**Issue by SohaibFarooqi** [sequelize/sequelize#5789]
**I have a model class like this:**

var path      = require("path");
var appConfig = require(path.join(__dirname, '..', 'config', 'application_config.js'));
var _ = require ('lodash');

module.exports = function(sequelize, DataTypes) {
  var agent = sequelize.define("agent", {
        agentid:                     {type: DataTypes.INTEGER , primaryKey: true},
        agent_status:                 DataTypes.INTEGER,
	    flag:                         DataTypes.STRING,
	    company_name: 		          DataTypes.STRING,
	    company_address:              DataTypes.STRING,
	    agent_country:                DataTypes.INTEGER,
	    description:                  DataTypes.STRING,
	    short_description:            DataTypes.STRING,
	    company_phone:                DataTypes.STRING,
	    company_cell:                 DataTypes.STRING,
	    company_fax:                  DataTypes.STRING,
	    company_email:                DataTypes.BOOLEAN,
	    company_website:              DataTypes.STRING,
	    counter:                      DataTypes.INTEGER,
	    mailcounter:                  DataTypes.INTEGER,
	    webcounter:                   DataTypes.INTEGER,
	    contactcounter:               DataTypes.INTEGER,
	    comment:                      DataTypes.STRING,
	    read_comments:                DataTypes.BOOLEAN,
	    creator_id:                   DataTypes.INTEGER,
	    auto_approve_listing:         DataTypes.BOOLEAN,
	    auto_email_listing:           DataTypes.BOOLEAN,
	    bypass_cc_email:              DataTypes.STRING,
	    bypass_email_userid:          DataTypes.BOOLEAN,
	    hide_deleted_contact:         DataTypes.BOOLEAN,
	    date_upgrade:                 DataTypes.DATE,
	    listing_logo:                 DataTypes.BOOLEAN,
	    listing_hot_text:             DataTypes.INTEGER,
	    agent_home_spot:              DataTypes.BOOLEAN,
	    agent_profile_hot_text:       DataTypes.BOOLEAN,
	    agent_profile_num_listings:   DataTypes.INTEGER,
	    paying_agent:                 DataTypes.BOOLEAN,
	    agent_logo:                   DataTypes.STRING,
	    new_agent_logo:               DataTypes.STRING,
	    agent_logo_bg_color:          DataTypes.STRING,
	    moved_id:                     DataTypes.INTEGER,
	    gov_reg_authority_1:          DataTypes.STRING,
	    gov_reg_number_1:             DataTypes.STRING,
	    gov_reg_authority_2:          DataTypes.STRING,
	    gov_reg_number_2:             DataTypes.STRING,
	    agent_company_reg_name:       DataTypes.STRING,
.....

 },
  {
  	timestamps: false,
  	freezeTableName: true,
  	tableName: appConfig.DB_PREFIX + 'agents'
  },
  {
  instanceMethods: {
  	toJSON: function(){

  		var privateAttributes = [
  		                           'agent_status' , 'flag' , 'counter' , 'mailcounter' , 'webcounter' , 'contactcounter' , 'read_comments' , 
  		                           'creator_id', 'auto_approve_listing' , 'auto_email_listing' , 'bypass_cc_email' , 'bypass_email_userid' ,
  		                            'hide_deleted_contact'
  		                        ];
  		return _.omit(this.dataValues, privateAttributes);
  	}
  }
});
 return agent;
};

**Query:**
var agent_list =  models.agent.findAll({
          
                                          where:   qry_filter,
                                          include:include_models,
                                          limit: agent_data.num_results || appConfig.DEFAULT_RESPONSE_SIZE,
                                          order: agent_data.sort || appConfig.DEFAULT_AGENT_SORT,
                                        })

                                       .then(function(agent_list){
                                           res.json(agent_list);
                                       });
But in response i see privateAttributes as well. do i have to call toJSON myself?

**Comment by janmeier** [comment]
`instanceMethods` should be in the same options object as `freezeTableName` and `tableName` - would have been a lot easier to spot if you formatted your code properly ;)

**Comment by SohaibFarooqi** [comment]
Hi, Thankyou that worked like charm.! :)
Sorry about the formatting. I will ensure proper formatting next time :)
