### ISSUE TITLE
Documentation has an error.

### ISSUE THREAD

**Issue by CaffeinatedCodeMonkey** [sequelize/sequelize#5793]
When using an instance of a model and trying to retrieve the actual model, I receive the error instance.Model() is not a function. I did it per this documentation: 

> Model() -> Model
> 
> View code
> 
> Returns the Model the instance was created from.

After looking through the code, I found that Model is actually a property of the instance and not a function.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/4193
