### ISSUE TITLE
catch or error function on bulkCreate not being fired

### ISSUE THREAD

**Issue by houssemFat** [sequelize/sequelize#5794]
## What you are doing?
Here i wont to insert a list of objects using bulkCreate, when objects are valid the `then` block is executed but when a database error is happend , the `error` or the `catch` is not being fired.
```js
       
sequelizeInstance.bulkCreate(objects)
            .then(function (results) {
                callback(null, _parseArrayResults(config.database.dialect, results));
            })

            .error(function (err) {
                callback(err);
            });
```

## What do you expect to happen?
I expect to catch the `sequelizeErrors.DatabaseError` when an error occured, example (filed database length)

## What is actually happening?
The code inside the error block not fired, neither with catch 

__Dialect:__ postgres
__Database version:__ 9.4.5
__Sequelize version:__ 3.21.0

**Comment by mickhansen** [comment]
http://bluebirdjs.com/docs/api/error.html
http://bluebirdjs.com/docs/api/catch.html

error is different from catch, you want catch

**Comment by houssemFat** [comment]
thank you @mickhansen !
