### ISSUE TITLE
Similar behavior for beforeUpdate and beforeDestroy

### ISSUE THREAD

**Issue by denisazevedo** [sequelize/sequelize#5795]
Hi,

The changes we make in the `model` during `beforeUpdate` hook are applied to the database during the update itself. - that's definitely a nice feature.

What about the changes we do during the `beforeDestroy` hook for a _paranoid_ model?
That would be nice too if we could apply the updates to the model at the same time the _update_ sets the `deletedAt` column to the current time.

For instance, take this scenario in consideration:
In the `User` model we have the property `isActive` that gets _true_ when the user confirms its account (via e-mail for example).
Later this user decides to delete its profile. When we destroy this user we also want to set the `isActive` to _false_ in the same update that sets the `deletedAt` to current timestamp.

I know we can accomplish that with different queries, but it would be good to have the same behavior between the `beforeUpdate` and `beforeDestroy` when the _destroy_ calls the update under the hood (_paranoid: true_).

Please let me know if a PR would be wellcome.

Thanks for your attention

**Comment by mickhansen** [comment]
@denisazevedo Sounds reasonable, but probably best decided when we have a concrete PR to discuss/work with (good integration tests reveal use cases)

**Comment by denisazevedo** [comment]
Thanks @mickhansen, I'll prepare this PR in the next weeks.

**Comment by teb02** [comment]
Would love to have this feature. At my project I need to update "isProcessed" field to false when the record is soft deleted, so some other Worker can process it. Now I have to do it in afterDestroy hook writing: model.update({isProcessed: false});

**Comment by komalpervez** [comment]
It would be great to have this feature
