### ISSUE TITLE
Field comment doesn't work for PostgreSQL

### ISSUE THREAD

**Issue by Beingbook** [sequelize/sequelize#5799]
## What you are doing?
I filled comment like:
```js
const GameModel = PostgresDB.define('game', {
  ...,
  title: {
    type: Sequelize.STRING(20),
    allowNull: false,
    comment: 'Game title',
  },
 ...,
});
```

## What do you expect to happen?
I wanted comment is in the field.

## What is actually happening?
Table comment attribute worked, field comments didn't work.

__Dialect: postgres
__Database version: postgres (PostgreSQL) 9.5.2
__Sequelize version: 3.21.0

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/pull/4385 and https://github.com/sequelize/sequelize/issues/4386
