### ISSUE TITLE
Is there a way include an attribute contained in JSONB with Sequelize.js?

### ISSUE THREAD

**Issue by dzuluaga** [sequelize/sequelize#5802]
I've just posted this in [StackOverflow](http://stackoverflow.com/questions/36873019/is-there-a-way-include-an-attribute-contained-in-jsonb-with-sequelize-js), but I wanted to give the heads up here. Sorry, if this shouldn't go here.

The second column in the SQL statement below retrieve Platform__c attribute from a JSONB column (entity_json).

When I try to use the syntax `["account_name", "entity_json ->> 'Platform__c'"]` as the column name, it fails. with this error: `"column \"entity_json ->> 'Platform__c'\"` does not exist"

Is there a way in Sequelize.js to retrieve this column using some syntax highlighted in the documentation?

```SQL
SELECT "account_name", entity_json ->> 'Platform__c' test 
FROM "sfdc"."mt_account" AS "Account" WHERE "Account"."account_name" ILIKE
'somecustomer' LIMIT 10;
```

**Comment by mickhansen** [comment]
When you need literals you need to wrap the individual attribute in something like `[db.literal("entity_json ->> 'Platform__c'"), 'platform']` so that's its aliased and not escaped.
