### ISSUE TITLE
shorthand for options.where in model.destroy

### ISSUE THREAD

**Issue by zolaemil** [sequelize/sequelize#5804]
```
testDb.user.destroy({where: user.id}).then(function(){
  done();
});
```
Up to 3.19.3, this used to work as a shorthand, but now it's breaking with `Expected plain object, array or sequelize method in the options.where parameter of model.destroy.` Either I was wrong in relying on this shorthand or this is a bug now.

**Comment by janmeier** [comment]
That syntax has never been officially supported, see here for the PR that removed accidental support https://github.com/sequelize/sequelize/pull/5516
