### ISSUE TITLE
"Query logging: false" not working

### ISSUE THREAD

**Issue by SohaibFarooqi** [sequelize/sequelize#5805]
I am using Sequelize 3.21.0. I am trying to turn-off query logging on console. I came across an answer on one of the github issues and have implemented it. But unfortunately sequelize is still logging queries on console.
Can you please look and tell me what i am doing wrong? I am using findAll method. 

```
`var config    = require(path.join(__dirname, '..', 'config', 'env_config.json'))[env];
 var sequelize = new Sequelize(config.database, config.username, config.password, config , {
	
            dialect: 'mysql',
            pool: { maxConnections: 10, maxIdleTime: 3000},
            maxConcurrentQueries: 100,
            logging: false
  

     });`
```

**Comment by janmeier** [comment]
We have several tests for this, https://github.com/sequelize/sequelize/blob/master/test/integration/sequelize.test.js#L254L303, and I have often used the logging feature in my programs - could you please provide a [SSCCE](HTTP://SSCCE.ORG/)

**Comment by SohaibFarooqi** [comment]
I have mailed you a sample project with instruction to run on your email. Please check when you have time.

**Comment by janmeier** [comment]
The output from your example is `here` when I test it - no quries logged

**Comment by SohaibFarooqi** [comment]
![logging_test](https://cloud.githubusercontent.com/assets/13061583/14878563/c3c8e7b8-0d3d-11e6-8dfd-ee8981f48ea1.JPG)

**Comment by janmeier** [comment]
But if I can't replicate your issue, it's hard to fix it :)

I didn't look at the package.json in your example (I just ran models/index in my own setup) - have you tested against the latest version?

**Comment by SohaibFarooqi** [comment]
Yes i know it is kinda strange. I have "sequelize": "^3.21.0" dependency in package.json.

**Comment by janmeier** [comment]
Try to create a PR with a failing test case

**Comment by SohaibFarooqi** [comment]
If i specify logging: false in sequelize/lib/sequelize.js then it stops logging on console. somehow it is not overriding this option if i do it in models/index.js. 
Will create PR with test case.

**Comment by SohaibFarooqi** [comment]
I figured out. If i remove fourth parameter "config" from the above code it works. 
       
      `var sequelize = new Sequelize(config.database, config.username, config.password , {
	
          dialect: 'mysql',
         logging: false
  
 
    });`

is this desired behavior? Shouldn't it be throwing error in case of 5 parameters?

**Comment by janmeier** [comment]
In the ideal world yes, but this is javascript - No argument checking, and its too cumbersome to add checks to each method :)
