### ISSUE TITLE
Error: Only HasMany associations support include.separate

### ISSUE THREAD

**Issue by topikachu** [sequelize/sequelize#5806]
## What you are doing?

```js
var Product = sequelize.define('Product', {
    //fields
},
{
    defaultScope: {
        limit: 10
    }
});


var Order = sequelize.define('Order', {
    //fields
});

Order.belongsTo(Product);

sequelize.sync();

Order.findAll(
    {
        include: [Product]
    }
);

```

## What do you expect to happen?
_No error happens_

## What is actually happening?
_Error: Only HasMany associations support include.separate_

__Dialect:__ postgres

__Sequelize version:__ 3.22.0

**Comment by mickhansen** [comment]
We are aware, see existing issues for lacking support for belongsToMany.
belongsTo has no real need for seperate (you're also not using a seperate option here)

**Comment by nibblesnbits** [comment]
Is `hasMany` actually working this way in the first place?
```js
UserGroups.hasMany(AppUsers, {
  foreignKey: 'appUserId',
});
// ...
const {
  count: totalCount,
  rows,
} = await UserGroupsModel.findAndCountAll({
  where: { groupId },
  include: [
    {
      model: AppUsersModel,
      where: {
        appUserId: { [Op.gt]: Number(after || 0) },
      },
      limit: first,
    },
  ],
  attributes: ['appUserId'],
});
const appUsers = rows.map((r) => r.AppUsers).flat();

const [{ appUserId: endId }] = rows.reverse();
return {
  totalCount,
  endId,
  values: appUsers,
};
```

I'm currently trying to use this for pagination via [this approach](https://graphql.org/learn/pagination/), and it's not breaking, but it's also not actually pulling the associated `AppUser` records (the array is empty).  There should be a single `AppUser` record per `UserGroup` record.

The generated SQL is a repeated pattern of
```sql

SELECT [AppUsers].*
FROM (
	SELECT *
	FROM (
		SELECT [appUserId]
			,[firstName]
			,[lastName]
			,[fullName]
			,[picUrl]
			,[birthday]
			,[gender]
			,[phone]
			,[email]
			,[frequency]
			,[budgetPerMonth]
			,[budgetPerActivity]
			,[country]
			,[timezone]
			,[isBanned]
			,[setupMode]
			,[viewedWitticismsCount]
		FROM [AppUsers] AS [AppUsers]
		WHERE ([AppUsers].[appUserId] > 80759)
			AND [AppUsers].[appUserId] = 47066  ---------------- Here's the problem
		ORDER BY [AppUsers].[appUserId] OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY
		) AS sub
	) AS [AppUsers];
```

And the commented line is the issue.  Removing that line returns exactly what I need.
Is this a bug or a config issue?

**Comment by SirCameron** [comment]
I have the same issue but I'm using `belongsToMany` with a `through` model. 
Any fixes for this? it's almost 3 years later...

**Comment by shubhamp-sf** [comment]
> I have the same issue but I'm using `belongsToMany` with a `through` model. Any fixes for this? it's almost 3 years later...

+1
