### ISSUE TITLE
removeColumn tries to delete non-existant foreign key constraint (mysql)

### ISSUE THREAD

**Issue by DeX3** [sequelize/sequelize#5808]
Hello,

I've noticed the following problem when trying removing a column that has an index other than a foreign key constraint associated with it (in mysql).

## What am I doing?

```js
    return migration.createTable( 'Images', {
      id: {
        type: Sequelize.INTEGER.UNSIGNED,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false
      },
      path: {
        type: Sequelize.STRING,
        allowNull: false
      }
    } )
    .then( function() {
      return migration.addIndex( 'Images', [ 'path' ], {
        indexName: 'images_path_unique',
        indicesType: 'UNIQUE'
      } );
    } )
    .then( function() {
      return migration.removeColumn( 'Images', 'path' );
    } );

```

## What do I expect to happen?

The `path` column should be dropped along with the `UNIQUE` index.

## What is actually happening?
the mysql-specific implementation for `removeColumn` tries to manually drop foreign key constraints before actually dropping the column. However, the query returned by getForeignKeyQuery `lib/dialects/mysql/query-generator.js:352` also seems to return indexes on the relevant column (like UNIQUE). `removeColumn` then tries to remove that index with `DROP FOREIGN KEY` which causes an error:

```
{ [SequelizeDatabaseError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'images_path_unique'; check that column/key exists]
  name: 'SequelizeDatabaseError',
  message: 'ER_CANT_DROP_FIELD_OR_KEY: Can\'t DROP \'images_path_unique\'; check that column/key exists',
  parent:
   { [Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'images_path_unique'; check that column/key exists]
     code: 'ER_CANT_DROP_FIELD_OR_KEY',
     errno: 1091,
     sqlState: '42000',
     index: 0,
     sql: 'ALTER TABLE `Images` DROP FOREIGN KEY `images_path_unique`;' },
  original:
   { [Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'images_path_unique'; check that column/key exists]
     code: 'ER_CANT_DROP_FIELD_OR_KEY',
     errno: 1091,
     sqlState: '42000',
     index: 0,
     sql: 'ALTER TABLE `Images` DROP FOREIGN KEY `images_path_unique`;' },
  sql: 'ALTER TABLE `Images` DROP FOREIGN KEY `images_path_unique`;' }
```

Also, I noticed that the `getForeignKeyQuery`-function doesn't restrict the query to the relevant database (mysql's INFORMATION_SCHEMA is global).

It seems like mysql is able to remove unique indexes cleanly along with the column when the parent column is dropped. Ideally, the `getForeignKeyQuery` function should really only return proper foreign key indexes.

__Dialect:__ mysql
__Database version:__ mysql  Ver 14.14 Distrib 5.7.11, for osx10.11 (x86_64)
__Sequelize version:__ 3.20.0

**Comment by mickhansen** [comment]
Sounds like you got a decent handle on the cause, a PR would be great.

**Comment by scottbeacher** [comment]
I'm still having this issue with version 3.24.1 and mysql. I have a column created with a unique index. Trying to remove it with a migration fails with the error that it cannot drop the field or key and to check that it exists. But the reason is sequelize is calling `ALTER TABLE devices DROP FOREIGN KEY deviceToken`

The migration:
```
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.removeColumn('devices', 'deviceToken')
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.addColumn('devices', 'deviceToken',
      {
        type: Sequelize.STRING,
        unique: true
      }
    )
  }
}
```

I get the same error as reported in the ticket.

**Comment by myaskevich** [comment]
@mickhansen Please reopen this ticket.

> Also, I noticed that the getForeignKeyQuery-function doesn't restrict the query to the relevant database (mysql's INFORMATION_SCHEMA is global).

I have prod and test databases and rolling out migration on one causes `SequelizeDatabaseError: ER_CANT_DROP_FIELD_OR_KEY` error on another. This is insane!

**Comment by Undeadlol1** [comment]
@scottbeacher making two independent migrations worked for me.
Remove indexes in first one, remove column in second one.

**Comment by rraina** [comment]
Still an open issue as of 3.30.4 ORM and 2.7.0 CLI

**Comment by julienvincent** [comment]
Running into this issue too

**Comment by JulsRicketti** [comment]
I'm also running into this same issue and haven't had luck with any of the suggested work arounds. One difference is that with my table, there is an association, but it has nothing to do with the column I'm trying to remove.

Have their been any updates or any other work arounds for this?

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/9ca86af20c72a4ae20544290a00e5a27695e860a
