### ISSUE TITLE
Raw Query with group gives two results in output.

### ISSUE THREAD

**Issue by drewdotpro** [sequelize/sequelize#5809]
## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_
`sequelize.query('SELECT t.status, SUM(b.workload) as workload FROM workloads w JOIN transactions t ON w.transactionId = t.id AND t.status != "ERROR" WHERE userId = :userId GROUP BY w.userId, t.status', {replacements: {userId: parseInt(user.id)}})
.then(function(result){
console.log(result);
});`

## What do you expect to happen?
Return one array of two items.

## What is actually happening?
returns two arrays of identical items

_Output, either JSON or SQL_
`[ [ RowDataPacket { status: 'PROCESSING', workload: 1200000 },
    RowDataPacket { status: 'COMPLETE', workload: 16147600 } ],
  [ RowDataPacket { status: 'PROCESSING', workload: 1200000 },
    RowDataPacket { status: 'COMPLETE', workload: 16147600 } ] ]
`

__Dialect:__ mysql
__Database version:__ 5.6.30
__Sequelize version:__ 3.19.3

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/3333
