### ISSUE TITLE
Subquery with limit generates wrong SQL

### ISSUE THREAD

**Issue by hanjukim** [sequelize/sequelize#5812]
## What am I doing
https://gist.github.com/hanjukim/1790a0039365577e79922b0b625c0dac
Save above gist into test directory and test.

## Reproduce & Expected to happen
Please look second testsql function
Query generator produces reversed column comparison in WHERE clause with subQuery: true and limit option.

```WHERE `Tag`.`id` = `Post`.`targetId` LIMIT 1```

expected to be,
```WHERE `Tag`.`targetId` = `Post`.`id` LIMIT 1```

__Dialect:__ any / postgres
__Database version:__ PostgreSQL 9.5.2
__Sequelize version:__ 3.22.0

**Comment by mickhansen** [comment]
If you have a failing test please submit a PR, otherwise please submit a piece of code we can copy to https://github.com/sequelize/sequelize/blob/master/sscce_template.js and run easily to verify.

I'm pretty sure this is a known bug though.
