### ISSUE TITLE
Sequelize.define breaks, if there are addition to Object.prototype

### ISSUE THREAD

**Issue by sandeepraheja** [sequelize/sequelize#5816]
We are working on a Node application, using Sequelize (3.14.2) with postgres. 

For the ease of writing, and writing generic code, we have extended on Javascript's Object prototype.

Doing so breaks the Sequelize's define method, when mapping the rawAttributes in model.js function constructor. 
Internally using the lodash's isPlainObject, it breaks on hasOwnProperty.

Any insight will be helpful?

**Comment by mickhansen** [comment]
It's considered a really bad practice to extend built-ins.
If you break lodash, which we use a lot, we're unlikely to have an easy fix.

Are you defining the properties as non enumerable?

**Comment by sandeepraheja** [comment]
Thanks for the reply. No the properties are not "non enumerable".
And, I agree not to extend in-built.

Thanks again

**Comment by mickhansen** [comment]
Consider extending them as non emurable if you wan't to retain the features then :)
