### ISSUE TITLE
User provided timestamp data gets overwritten

### ISSUE THREAD

**Issue by TylerBrock** [sequelize/sequelize#5817]
## What you are doing?

```js
const Lead = sequelize.define('lead', {
  ...
  createdAt: {
    type: Sequelize.DATE,
    field: 'created_at',
  },
  updatedAt: {
    type: Sequelize.DATE,
    field: 'updated_at'
  }
}, {
  freezeTableName: true, // Model tableName will be the same as the model name
  timestamps: false,
  underscored: true
});
```

## What do you expect to happen?
I expect that inserting an object with createdAt and updatedAt would set created_at and updated_at to the provided values instead of overwriting it with generated timestamps.

I'm importing data from another store via `bulkCreate()`, and feel as though it is a common use case to want the original timestamps for the data instead of having new ones generated (not useful).

## What is actually happening?
The values are generated and overwrite the provided values for those fields.

Running latest sequelize against latest postgres but I'm assuming it would work similarly for all backing stores.

**Comment by janmeier** [comment]
I just tested locally, and it seems to work fine for me:

```js
const Lead = sequelize.define('lead', {
  createdAt: {
    type: Sequelize.DATE,
      field: 'created_at',
  },
  updatedAt: {
    type: Sequelize.DATE,
      field: 'updated_at'
  }
  }, {
    freezeTableName: true, // Model tableName will be the same as the model name
    timestamps: false,
    underscored: true
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => Lead.create({
    createdAt: moment().subtract(10, 'day'),
    updatedAt: moment().subtract(1, 'day')
  }))
  .finally(() => sequelize.close());
```

```sql
INSERT INTO "lead" ("id","created_at","updated_at") VALUES (DEFAULT,'2016-04-19 07:11:06.251 +00:00','2016-04-28 07:11:06.258 +00:00') RETURNING *;
```
