### ISSUE TITLE
Relationships are not applied in the database

### ISSUE THREAD

**Issue by noodlesftw** [sequelize/sequelize#5819]
## What you are doing?
I'm defining two models and have a hasMany relation and a belongsTo relation setup between them.

```js
'use strict';

// Dependencies
//==============================================================================
const db = require('../lib/db');

// User
//==============================================================================
const User = db.connection.define('user', {
	// attributes
}, {
	paranoid: true,
	underscored: true
});

// Inquiry
//==============================================================================
const Inquiry = db.connection.define('inquiry', {
	// attributes
}, {
	underscored: true
});

// Relations
//==============================================================================
Inquiry.belongsTo(User);
User.hasMany(Inquiry, {as: 'Inquiries'});

// Exports
//==============================================================================
module.exports.User    = User;
module.exports.Inquiry = Inquiry;
```

## What do you expect to happen?
I expect to have a user_id column in the `inquiries` table, but it doesn't appear there.

## What is actually happening?
No relations are setup in the database.

__Dialect:__ mysql
__Database version:__ 5.7.10
__Sequelize version:__ ^3.21.0

**Comment by janmeier** [comment]
Are you running sync with `force: true `? Sequelize will not do any table diff to add missing columns, we only create tables from scratch

**Comment by noodlesftw** [comment]
@janmeier I tried it on an empty database and also using `force: true`, but that doesn't make a difference.

**Comment by noodlesftw** [comment]
@janmeier Seems like I was requiring the Inquiry model from another (older) model definition in another file. Closing this issue as it's not a bug or feature request. My apologies.
