### ISSUE TITLE
no table field comment generate when create table use sequelize models

### ISSUE THREAD

**Issue by baijian** [sequelize/sequelize#5820]
## What you are doing?
I write models(with field comment) and create table using modes, table is created success,but no field comment, I do not know why, version: 3.2.0

```js
var table1=sequelize.define('test', {
    fieldone: {
        type: DataTypes.STRING(200),
        defaultValue: "",
        comment: "this is filed one",
    });
```

## What do you expect to happen?
table created and table field with comments.

## What is actually happening?
no comments show in my table of my database.

__Dialect:__ mysql 
__Database version:__ 5.6.16
__Sequelize version:__ 3.2.0

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/4386
