### ISSUE TITLE
update instance attribute in "beforeUpdate" hook

### ISSUE THREAD

**Issue by Joanne16** [sequelize/sequelize#5821]
Hi,

I am having an issue with resetting instance attribute value in beforeUpdate hook when doing bulk update. The before update hook looks like below (taken from model):
```js
beforeUpdate: function(instance, options) {
var self = this,                    
                    promise;

                promise = new record.sequelize.Promise(function (resolve, reject) {
                    record.theAttributeName = 'newValue';
                    resolve(record);
                });

                return promise;
}

.....
model.update({anotherAttr: '1234', {where: {someField: 1111}})
  .....
```
When only one record is found for the "where" condition, the record's "theAttributeName " is set correctly to the new value, but as soon as more than 1 record is returned for the where clause, the "theAttributeName" new value is not set (even the generated SQL update in the log does not contain the change)

Is it OK to change some record's attributes in "beforeUpdate" when updating multiple or do we need to use the "beforeBulkUpdate" hook to do so ?

Dialect: mysql
Sequelize version:3.19.3

Thanks

**Comment by Joanne16** [comment]
Updated to sequelize '3.22.0' and having same issue (i.e. attributes values set in beforeUpdate are not included in the save SQL query when more than 1 record found for update)

**Comment by janmeier** [comment]
By default bulk update does a single update, so the bulk hook is run. If you want to run individual update books (on top of the bulk hook), use `individualHooks` http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows
