### ISSUE TITLE
Node.js 6.0.0 complains about deprecated v8::FunctionTemplate::Set() with non-primitive values

### ISSUE THREAD

**Issue by Aaronov** [sequelize/sequelize#5824]
> 
> 
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: (node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: (node) and will stop working in the next major release.
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: ==== JS stack trace =========================================
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: Security context: 0x1bbb8433f3b1 <JS Object>#0#
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 1: .node [module.js:568] [pc=0x1c7658185024] (this=0x1089dbedec39 <an Object with map 0x124c1342f239>#1#,module=0x2189c9515e31 <a Module with map 0x124c1342f811>#2#,filename=0x2189c9515df9 <String[78]: /usr/lib/node_modules/
> sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 2: load [module.js:456] [pc=0x1c7657f9b652] (this=0x2189c9515e31 <a Module with map 0x124c1342f811>#2#,filename=0x2189c9515df9 <String[78]: /usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1c7657f9b17d] (this=0x1bbb84304139 <undefined>,module=0x2189c9515e31 <a Module with map 0x124c1342f811>#2#,filename=0x2189c9515df9 <String[78]: /usr/lib/node_modules/
> sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 4: _load [module.js:407] [pc=0x1c7657f96dc2] (this=0x2cecfae94521 <JS Function Module (SharedFunctionInfo 0x3bb77f5aca49)>#3#,request=0x2189c950f1f1 <String[78]: /usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64/n
> ode_sqlite3.node>,parent=0x2189c9320e09 <a Module with map 0x124c1342f811>#4#,isMain=0x1bbb843043b1 <false>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 5: require [module.js:~463] [pc=0x1c765800f74f] (this=0x2189c9320e09 <a Module with map 0x124c1342f811>#4#,path=0x2189c950f1f1 <String[78]: /usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 6: require(aka require) [internal/module.js:20] [pc=0x1c7657fa5546] (this=0x1bbb84304139 <undefined>,path=0x2189c950f1f1 <String[78]: /usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 7: /* anonymous */ [/usr/lib/node_modules/sqlite3/lib/sqlite3.js:4] [pc=0x1c765814437e] (this=0x2189c9320e59 <an Object with map 0x124c13406679>#5#,exports=0x2189c9320e59 <an Object with map 0x124c13406679>#5#,require=0x2189
> c9324b39 <JS Function require (SharedFunctionInfo 0x2cecfae23191)>#6#,module=0x2189c9320e09 <a Module with map 0x124c1342f811>#4#,__filename=0x2189c9320dd1 <String[44]: /usr/lib/node_modules/sqlite3/lib/sqlite3.js>,__dirname=0x2189c9324ad1 <String[33]: /usr/lib/node_mod
> ules/sqlite3/lib>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 8: _compile [module.js:541] [pc=0x1c7657fa2e04] (this=0x2189c9320e09 <a Module with map 0x124c1342f811>#4#,content=0x2189c93217b9 <Very long string[5550]>#7#,filename=0x2189c9320dd1 <String[44]: /usr/lib/node_modules/sqlite3
> /lib/sqlite3.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 9: .js [module.js:~548] [pc=0x1c76580109ec] (this=0x1089dbedec39 <an Object with map 0x124c1342f239>#1#,module=0x2189c9320e09 <a Module with map 0x124c1342f811>#4#,filename=0x2189c9320dd1 <String[44]: /usr/lib/node_modules/s
> qlite3/lib/sqlite3.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 10: load [module.js:456] [pc=0x1c7657f9b652] (this=0x2189c9320e09 <a Module with map 0x124c1342f811>#4#,filename=0x2189c9320dd1 <String[44]: /usr/lib/node_modules/sqlite3/lib/sqlite3.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 11: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1c7657f9b17d] (this=0x1bbb84304139 <undefined>,module=0x2189c9320e09 <a Module with map 0x124c1342f811>#4#,filename=0x2189c9320dd1 <String[44]: /usr/lib/node_modules
> /sqlite3/lib/sqlite3.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 12: _load [module.js:~381] [pc=0x1c7658116185] (this=0x2cecfae94521 <JS Function Module (SharedFunctionInfo 0x3bb77f5aca49)>#3#,request=0x232bfe5e1051 <String[7]: sqlite3>,parent=0x2189c923fc11 <a Module with map 0x124c1342f
> 811>#8#,isMain=0x1bbb843043b1 <false>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 13: require [module.js:~463] [pc=0x1c765800f74f] (this=0x2189c923fc11 <a Module with map 0x124c1342f811>#8#,path=0x232bfe5e1051 <String[7]: sqlite3>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 14: require(aka require) [internal/module.js:20] [pc=0x1c7657fa5546] (this=0x1bbb84304139 <undefined>,path=0x232bfe5e1051 <String[7]: sqlite3>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 15: new constructor [/usr/lib/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22] [pc=0x1c765814401d] (this=0x2189c9317711 <JS Object>#9#,dialect=0x2189c9317669 <JS Object>#10#,sequelize=0x2189c92325c9 <JS O
> bject>#11#)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 17: new constructor [/usr/lib/node_modules/sequelize/lib/dialects/sqlite/index.js:12] [pc=0x1c7658143a49] (this=0x2189c9317669 <JS Object>#10#,sequelize=0x2189c92325c9 <JS Object>#11#)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 19: new constructor [/usr/lib/node_modules/sequelize/lib/sequelize.js:233] [pc=0x1c76581252d8] (this=0x2189c92325c9 <JS Object>#11#,database=0x232bfe5dfb99 <String[8]: database>,username=0x1bbb843a4191 <String[8]: username>,
> password=0x2cecfae1f5b1 <String[8]: password>,options=0x2189c9232461 <an Object with map 0x35a37b61e301>#12#)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 21: /* anonymous */ [server/models/index.js:5] [pc=0x1c765801cfe8] (this=0x2b19ec735f31 <an Object with map 0x124c13406679>#13#,exports=0x2b19ec735f31 <an Object with map 0x124c13406679>#
> 13#,require=0x2b19ec735dd1 <JS Function require (SharedFunctionInfo 0x2cecfae23191)>#14#,module=0x2b19ec735d41 <a Module with map 0x124c1342f811>#15#,__filename=0x2b19ec735ed9 <String[59]: server/models/index.js>,__dirname=0x2b19ec73
> 5eb1 <String[50]: server/models>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 22: _compile [module.js:541] [pc=0x1c7657fa2e04] (this=0x2b19ec735d41 <a Module with map 0x124c1342f811>#15#,content=0x2b19ec7362d1 <String[747]\: var fs        = require("fs");\nvar path      = require("path");\nvar Sequeli
> ze = require("sequelize");\n\nvar sequelize = new Sequelize('database', 'username', 'password', {\n  host: 'localhost',\n  dialect: 'sqlite',\n  storage: '/home/dss/database.sqlite',\n  logging: false\n});\n\nvar db        = {};\n\nfs\n  .readdirSync(__dirname)\n  .filt
> er(function(file) {\n    return (file.indexOf(".") !== 0) && (file !== "index.js");\n  })\n  .forEach(function(file) {\n    var model = sequelize["import"](path.join(__dirname, file));\n    db[model.name] = model;\n  });\n\nObject.keys(db).forEach(function(modelName) {\
> n  if ("associate" in db[modelName]) {\n    db[modelName].associate(db);\n  }\n});\n\ndb.sequelize = sequelize;\ndb.Sequelize = Sequelize;\n\nmodule.exports = db;>,filename=0x2b19ec735ed9 <String[59]: server/models/index.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 23: .js [module.js:~548] [pc=0x1c76580109ec] (this=0x1089dbedec39 <an Object with map 0x124c1342f239>#1#,module=0x2b19ec735d41 <a Module with map 0x124c1342f811>#15#,filename=0x2b19ec735ed9 <String[59]: /opt/d
> ss/webinterface/server/models/index.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 24: load [module.js:456] [pc=0x1c7657f9b652] (this=0x2b19ec735d41 <a Module with map 0x124c1342f811>#15#,filename=0x2b19ec735ed9 <String[59]: server/models/index.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 25: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1c7657f9b17d] (this=0x1bbb84304139 <undefined>,module=0x2b19ec735d41 <a Module with map 0x124c1342f811>#15#,filename=0x2b19ec735ed9 <String[59]: /opt/
> dss/webinterface/server/models/index.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 26: _load [module.js:407] [pc=0x1c7657f96dc2] (this=0x2cecfae94521 <JS Function Module (SharedFunctionInfo 0x3bb77f5aca49)>#3#,request=0x2cecfae1ef61 <String[15]: ./server/models>,parent=0x1089dbee1341 <a Module with map 0x1
> 24c1342f811>#16#,isMain=0x1bbb843043b1 <false>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 27: require [module.js:~463] [pc=0x1c765800f74f] (this=0x1089dbee1341 <a Module with map 0x124c1342f811>#16#,path=0x2cecfae1ef61 <String[15]: ./server/models>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 28: require(aka require) [internal/module.js:20] [pc=0x1c7657fa5546] (this=0x1bbb84304139 <undefined>,path=0x2cecfae1ef61 <String[15]: ./server/models>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 29: /* anonymous */ [app.js:3] [pc=0x1c7657fa39ca] (this=0x1089dbee1681 <an Object with map 0x124c13406679>#17#,exports=0x1089dbee1681 <an Object with map 0x124c13406679>#17#,require=0x10
> 89dbee13d1 <JS Function require (SharedFunctionInfo 0x2cecfae23191)>#18#,module=0x1089dbee1341 <a Module with map 0x124c1342f811>#16#,__filename=0x1089dbee1639 <String[43]: app.js>,__dirname=0x1089dbee1611 <String[36]: webinterface>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 30: _compile [module.js:541] [pc=0x1c7657fa2e04] (this=0x1089dbee1341 <a Module with map 0x124c1342f811>#16#,content=0x1089dbee4801 <Very long string[12489]>#19#,filename=0x1089dbee1639 <String[43]: /opt/dss/w
> ebinterface/app.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 31: .js [module.js:~548] [pc=0x1c7657f9cc4b] (this=0x1089dbedec39 <an Object with map 0x124c1342f239>#1#,module=0x1089dbee1341 <a Module with map 0x124c1342f811>#16#,filename=0x1089dbee1639 <String[43]: /opt/d
> ss/webinterface/app.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 32: load [module.js:456] [pc=0x1c7657f9b652] (this=0x1089dbee1341 <a Module with map 0x124c1342f811>#16#,filename=0x1089dbee1639 <String[43]: app.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 33: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1c7657f9b17d] (this=0x1bbb84304139 <undefined>,module=0x1089dbee1341 <a Module with map 0x124c1342f811>#16#,filename=0x1089dbee1639 <String[43]: /opt/
> dss/webinterface/app.js>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 34: _load [module.js:407] [pc=0x1c7657f96dc2] (this=0x2cecfae94521 <JS Function Module (SharedFunctionInfo 0x3bb77f5aca49)>#3#,request=0x1089dbee7909 <String[43]: app.js>,parent=0x1bbb843
> 04111 <null>,isMain=0x1bbb84304349 <true>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 35: runMain [module.js:575] [pc=0x1c7657f9688a] (this=0x2cecfae94521 <JS Function Module (SharedFunctionInfo 0x3bb77f5aca49)>#3#)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 36: startup(aka startup) [node.js:159] [pc=0x1c7657f646fe] (this=0x1bbb84304139 <undefined>)
> Apr 29 18:01:25 P04025-00000150 dss-web[379]: 37: /* anonymous */(aka /* anonymous */) [node.js:444] [pc=0x1c7657f62072] (this=0x1bbb84304111 <null>,process=0x1bbb843b5b21 <a process with map 0x124c134775e9>#20#)

**Comment by BridgeAR** [comment]
This is not a sequelize issue. [SQLite3](https://github.com/mapbox/node-sqlite3/issues/638) has to be rebuild with the newest [nan](https://github.com/nodejs/nan) version and the message is going to go away.

**Comment by mickhansen** [comment]
Thanks @BridgeAR
