### ISSUE TITLE
Foreign key is being capitalised in query resulting in "SequelizeDatabaseError: column Book.UserId does not exist"

### ISSUE THREAD

**Issue by alexdrans** [sequelize/sequelize#5828]
## What you are doing?
I am trying to perform a simple join;

```js
models.User.find({
      where: {
        emailAddress: request.payload.emailAddress
      },
      include: [{
        model: models.Book,
      }]
    })
```

## What is actually happening?
and I get the error '"SequelizeDatabaseError: column Book.UserId does not exist"'

The field is called 'userId'. How can I fix this?

__Dialect:__ postgres
__Database version: 9.4
__Sequelize version: 3.20.0

**Comment by janmeier** [comment]
Please show your model definitions and associations

**Comment by alexdrans** [comment]
`module.exports = function (sequelize, DataTypes) {
  var User = sequelize.define('User', {
    emailAddress: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    uniqueId: {
      type: DataTypes.UUID,
      allowNull: false
    },
    hashedPassword: {
      type: DataTypes.STRING,
      allowNull: false
    },
    firstName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    emailConfirmed: {
      type: DataTypes.BOOLEAN,
      defaultValue: 0
    },
    active: {
      type: DataTypes.BOOLEAN,
      defaultValue: true
    },
    accessLevel: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      allowNull: false
    },
    acquisitionSource: {
      type: DataTypes.STRING,
      allowNull: false
    },
    stripeCustomerId: {
      type: DataTypes.STRING
    },
    referredBy: {
      type: DataTypes.STRING
    }
  }, {
      classMethods: {
        associate: function (models) {
          User.hasOne(models.Book, {
            foreignKey: 'userId'
        }
      }
    });
  return User;
};`

and 

`module.exports = function(sequelize, DataTypes) {
  var Book = sequelize.define('Book', {
    membershipExpires: {
      type: DataTypes.DATE,
      allowNull: false
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false
    }
  }, {
    timestamps: false,
    classMethods: {
      associate: function(models) {
        Book.belongsTo(models.User, {
          type: sequelize.INTEGER,
          foreignkey: 'userId'
        })
      }
    }, 
    
  });
  return Parent;
};`

**Comment by alexdrans** [comment]
`User.hasOne(models.Book, {
            foreignKey: 'userId'
          });`

The 'Book' model doesn't have an explicit 'userId' defined - I let the association do this. 

Isn't the error just in the capitalisation? Sequelize looks for 'UserId', but the column name is 'userId'

**Comment by janmeier** [comment]
(Didn't you post your complete models before ;)?)

The foreign key name will match the name of the model - so if the user has `User` as the name, the foreign key will be `UserId`. For example if you defined 

```js
User.hasOne(models.Book, { foreignKey: 'userId' });
Book.belongsTo(User)
```

Sequelize will get confused and add both `userId` and `UserId` - You have to add the foreign key to both associations.

Without seeing your complete model definitions and associations so I can replicate the issue, its hard to say whats at play here ;)

**Comment by fiftin** [comment]
Does exit other solution for this problem?

**Comment by papb** [comment]
@fiftin You should explicitly specify the foreign key on both ends:

```
User.hasOne(models.Book, { foreignKey: 'userId' });
Book.belongsTo(User, { foreignKey: 'userId' });
```

Or not specify it at all.

Are you looking for a different solution? I don't think that exists.

**Comment by kezzico** [comment]
make sure quoteIdentifiers is set to true

```new Sequelize(..., { quoteIdentifiers: true })```

**Comment by limmie** [comment]
God bless youu @papb, I wrote my sequelize/express project with help of you (https://github.com/sequelize/express-example). Thank you so much :)

**Comment by hongphuc5497** [comment]
Thank you @papb, really helpful answer

**Comment by ephys** [comment]
@alexpetros Thank you for notifying us. I'm working on bringing a few improvements to the documentation, I'll include that :)

**Comment by ThirteenTempest** [comment]
Just wanted to bump this: the documentation as it exists lead me to making this same mistake. 

The documentation on the [associations page](https://sequelize.org/docs/v6/core-concepts/assocs/#providing-the-foreign-key-name-directly) seems to heavily imply that Sequelize lowercases the model name. 

```js
Ship.belongsTo(Captain); // This creates the `captainId` foreign key in Ship.

// Eager Loading is done by passing the model to `include`:
console.log((await Ship.findAll({ include: Captain })).toJSON());
// Or by providing the associated model name:
console.log((await Ship.findAll({ include: 'captain' })).toJSON());

// Also, instances obtain a `getCaptain()` method for Lazy Loading:
const ship = Ship.findOne();
console.log((await ship.getCaptain()).toJSON());
``` 

Is it possible to make it so every model is capitalized in the documentation?
