### ISSUE TITLE
Is there any way to return a key value pair from a join where the joined table key is not in the format Table.Column

### ISSUE THREAD

**Issue by mattyicce** [sequelize/sequelize#5833]
## What you are doing?
_Is there any way to return a key value pair from a join where the joined table key is not in the format Table.Column?  I need to use the results with ui-grid which does not like the format of Table.Colum for a cell value. I posted the question on stack over flow. http://stackoverflow.com/questions/36872373/using-sequelize-join-table-how-do-i-set-the-key-of-the-attributes-grabbed-while_

```js
{
    id: yada,
    name: yada,
    bar.version: yada,
    bar.changed: yada
}
```

## What do you expect to happen?
_I want just id, name, version, and changed in the joined result._

## What is actually happening?
_I get id, name, bar.version, bar.changed._

__Dialect:__ mssql
__Database version:__ XXX
__Sequelize version:__ 2.0.5

**Comment by janmeier** [comment]
Its very likely not possible on v2 - There is a ton of changes to includes in v3. 

Its hard to say anything without seeing your models associations and find call ......

**Comment by mattyicce** [comment]
Aren't all join table results going to return the joined table in the format of Table.ColumnName?

**Comment by janmeier** [comment]
@mattyicce Again, its hard to say anything without seeing some actual code ...

**Comment by mattyicce** [comment]
In general,

```
var User = sequelize.define('user', {
    firstName: {
        type: Sequelize.STRING,
    },
    fk_project: {
        type: Sequelize.INTEGER
    }
})
var Project = sequelize.define('project', {
    name: {
        type: Sequelize.STRING
    }
})
 
// One-way associations
Project.hasOne(User, {foreignKey: "fk_project"});

User.findAll({
    include: ['Project']
}).then(function(data){
    //  whatever
})
```
would return an array of objects in the form of 
[{ "firstName" : "Matty", Project.name : "Getting some help" }]

**Comment by mickhansen** [comment]
@mattyicce Are you using `raw: true` for your queries?

**Comment by mattyicce** [comment]
Yes @mickhansen sorry I forgot to add that.

**Comment by mickhansen** [comment]
Well there you go then, raw turns off stuff
