### ISSUE TITLE
Sequelize upsert does not seem to be implemented for sql server (2012) 

### ISSUE THREAD

**Issue by mgrivera** [sequelize/sequelize#5846]
Hi, 

I just realized Sequelize seems to fail to do an _upsert_ when using Sql Server. 

In the docs, in **Implementation details**, you can find details for all the databases (mysql, postgress, sqlite) but not for sql server. 

When you try to do an upsert to a sql server database (2012), this message is issued: 

> The method "upsertQuery" is not defined! Please add it to your sql dialect.

Thanks and bye ...

**Comment by mickhansen** [comment]
Correct, it's not implemented. Original implementer skipped it. You are welcome to attempt implementing it :)

**Comment by mgrivera** [comment]
Thanks for answering @mickhansen.

**Comment by armand1m** [comment]
Am.. sequelize does use a `tedious` connection for handling MSSQL queries, right?

**Comment by armand1m** [comment]
I just need to implement an `upsertQuery` property in the `Query` function exported by the file `lib/dialects/mssql/query-generator.js`?

**Comment by janmeier** [comment]
@armand1m Should be enough, yes

**Comment by armand1m** [comment]
Cool, I've already forked it, I'm going to try to implement this one and send a PR

**Comment by iamchristopher** [comment]
Any luck on this, @armand1m?

**Comment by armand1m** [comment]
@iamchristopher actually I couldn't have some time to start it in the sequelize repository yet, but I do got a manual implementation of a bulkUpsert function using the available sequelize API. Not sure if it is what you need right now, but you can see the gist in here https://gist.github.com/armand1m/b2bd6b551d3c1f2b7254bcb339c0d869

**Comment by derimagia** [comment]
This was added here: https://github.com/sequelize/sequelize/pull/6842
