### ISSUE TITLE
[feature request] Add INFORMATION_SCHEMA.COLUMNS CHARACTER_MAXIMUM_LENGTH

### ISSUE THREAD

**Issue by mkelley82** [sequelize/sequelize#5850]
Add INFORMATION_SCHEMA.COLUMNS CHARACTER_MAXIMUM_LENGTH to the describeTableQuery so that we can then use it in sequelize-auto or whatever project, to get the max length of a given field.

**Comment by hd719** [comment]
Hello I am new to Open source can I work on this?
