### ISSUE TITLE
mysql DATETIME(3) results in incorrect format on insert

### ISSUE THREAD

**Issue by dbrinda-db** [sequelize/sequelize#5854]
I am receiving the following error when trying to insert a DATETIME(3). 

[SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '1970-01-06 00:09:03.436 +00:00' for column 'x' at row 1]
     name: 'SequelizeDatabaseError',
     message: 'ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: \'1970-01-06 00:09:03.436 +00:00\' for column \'releaseDate\' at row 1',

I don't believe the date is in the correct format:
1970-01-06 00:09:03.436 +00:00
should be
1970-01-06 00:09:03.436

Mysql does not seem to like the timezone information included there. When using normal DATETIME, it does not seem to include the timezone information and does not have this issue.

If I replace DATE.prototype.$stringify in dialects/mysql/data-types.js with the same function from dialiects/mssql/data-types, the problem is resolved.

Seems related to https://github.com/sequelize/sequelize/issues/3892

**Comment by sobotklp** [comment]
This is related to #5387 . MySQL 5.7 and above doesn't accept timezone information by default, where previous versions of MySQL did. 

As specified in #5387 , I agree that the proper solution is to omit timezone information in dialects/mysql/data-types.js since MySQL's DATETIME fields don't store the tz anyways.

**Comment by dbrinda-db** [comment]
Yes I think this is the same issue.

**Comment by zazoomauro** [comment]
I still having this problem:

* `mysql: 5.6.13`
* `sequelize: 3.30.2`
* `node: v4.4.2`
* `npm: 2.15.0`

Sequelize does: 
```sql
`UPDATE `users` SET `?`='?',`updatedAt`='2017-02-22 09:22:30.448 +00:00' WHERE `id` = ?`
```

Error: `SequelizeUniqueConstraintError: Validation error`
