### ISSUE TITLE
There are redundant fields in the query results?

### ISSUE THREAD

**Issue by zzbo** [sequelize/sequelize#5856]
I implement a joint query as following:
```js
models.proj.findAll({
      attributes: ['proj_id', 'proj_name', 'proj_time'],
      limit: param.limit,
      offset: param.offset,
      include: {
          model: models.user,
          attributes: ['user_id'],
          where: {
              user_id: user_id
          }
      },
      raw: true
});
```

get the results:
```js
[ { proj_id: 1,
    proj_name: 'edu',
    proj_time: Wed Nov 26 2014 16:55:38 GMT+0800,
    'users.user_id': 17,
    'users.user_proj.proj_id': 1,
    'users.user_proj.user_id': 17 } ]
```
Actually, I don't need attributes  `users.user_proj.proj_id` `users.user_proj.user_id`, how to make these attributes do not appear in the query results.

__Dialect:__ mysql
__Database version:__ 5.6.24
__Sequelize version:__ 3.20.0

**Comment by mickhansen** [comment]
You need to use `include.through.attributes = []` but i believe there's actually a bug with that right now.

**Comment by zzbo** [comment]
I have tried your advice, but the issue still remain.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/5590
