### ISSUE TITLE
Unhandled rejection Error: Can Someone Kindly Point Me In The Correct Direction?

### ISSUE THREAD

**Issue by thedavey92** [sequelize/sequelize#5857]
I am a little confused either with the documentation as something is wrong with my code. I am sure it is a simple fix. I am basically getting this error.

Unhandled rejection Error: licenses is not associated to categories!
`Unhandled rejection Error: licenses is not associated to categories!
```
var licenses = sequelize.define("licenses",{
    //Types
},{timestamps: false,underscored: true,freezeTableName: true});

var categories = sequelize.define("categories",{
  //Types
},{timestamps: false,underscored: true,freezeTableName: true});

//Forign Key
licenses.hasMany(categories ,{foreignKey: 'cat_lic_id', as:'lic'});

//Connection
var query = sequelize.sync({force:false}).then(function(){
            categories.findAndCountAll({
                where:{cat_lic_id:1},
                include:[licenses]
            })

```
I have checked the forign key in phpmyadmin and it links up perfectly. I can't get my head around why it is not associated.

**Comment by janmeier** [comment]
You need to set up the relation category > license (categories.belongsTo(licenses)
