### ISSUE TITLE
instanceMethods with es6 arrow function

### ISSUE THREAD

**Issue by xiaofan2406** [sequelize/sequelize#5858]
## What you are doing?
With Node js moving to es6, it would be great if arrow function works when defining instanceMethods.

```js
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    name: DataTypes.STRING
  }, {
    instanceMethods: {
      foo: () => { // this is not gonna work as expected
        return this.name
      }
    }
  });
  return User;
};
```

## What do you expect to happen?
above code to work.

## What is actually happening?
I may be wrong. I think the lexical scoping is not working in our favor here.

**Comment by janmeier** [comment]
There is no way to override the scope of arrow functions - that's one of their main features. So there's nothing we can do here

**Comment by vajanishant** [comment]
can you elaborate why this thing is happening!!!
