### ISSUE TITLE
Safe string on query

### ISSUE THREAD

**Issue by carlitux** [sequelize/sequelize#5859]
I want to modify the SUM aggregate but when query the 

    "Advertisement"."id" WHEN now() <= "Publication"."ended_at" THEN 1 ELSE 0 END

is escaped and query is not working... here is the complete query build.

    db.Advertisement
      .findAll({
        where: { UserId: req.user.id },
        attributes: [
          '*',
          [db.sequelize.fn('SUM', '"Advertisement.id" WHEN now() <= "Publication.ended_at" THEN 1 ELSE 0 END'), 'active'],
        ],
        raw: true,
        group: ['Advertisement.id'],
        order: ['Advertisement.id'],
        logging: true,
        include: [
          {
            model:db.Publication,
            attributes: []
          }
        ],
      }).then(function (advertisements) {
        console.log(advertisements);
      });

**Comment by mickhansen** [comment]
You can use `db.sequelize.literal` to stop escaping
