### ISSUE TITLE
Instance update does not preserve previous dataValues

### ISSUE THREAD

**Issue by sherpya** [sequelize/sequelize#5866]
instance update calls save() a the end, then in instance.js:
```
        .then(function(result) {
          options.fields.forEach(function (field) {
            result._previousDataValues[field] = result.dataValues[field];
            self.changed(field, false);
          });
          self.isNewRecord = false;
          return result;
        })
```
result._previousDataValues is overwritten with new values

**Comment by janmeier** [comment]
This is intentional - `_previousDataValues` and `changed` are used to track there data that has been changed application side, but not yet saved. So when you save, `_previousDataValues` are emptied.

Why do you need to preserve the values after saving?

**Comment by janmeier** [comment]
Other than that, `_previousDataValues` is a private variable, so you shouldn't rely on it. Use [previous](http://docs.sequelizejs.com/en/latest/api/instance/#previouskey-anyarrayany) and [changed](http://docs.sequelizejs.com/en/latest/api/instance/#changedkey-booleanarray)

**Comment by sherpya** [comment]
the variable is overwritten internally, so previous returns new values and changed always false

**Comment by janmeier** [comment]
When the instance is saved previous is no longer previous, thats why it is overwritten ;). As I said, preivous is used to track changes that have not yet been saved.

**Comment by sherpya** [comment]
I see perhaps the doc is not very clear about it

**Comment by janmeier** [comment]
PRs are always welcome :)

**Comment by pablodgonzalez** [comment]
What About afterUpdate hook? There is a good point to do somethings related to new and old values.
