### ISSUE TITLE
setterMethods for definition model not working as expected - getterMethods works fine

### ISSUE THREAD

**Issue by xtianus79** [sequelize/sequelize#5867]
## What you are doing?
Post a minimal code sample that reproduces the issue, including models and associations_

```js
var Foo = sequelize.define('foo', {
  firstname: Sequelize.STRING,
  lastname: Sequelize.STRING
}, {
  getterMethods   : {
    fullName       : function()  { return this.firstname + ' ' + this.lastname }
  },

  setterMethods   : {
    fullName       : function(value) {
        var names = value.split(' ');

        this.setDataValue('firstname', names.slice(0, -1).join(' '));
        this.setDataValue('lastname', names.slice(-1).join(' '));
    },
  }
});
```
## What do you expect to happen?
I can use the getterMethods but there is nothing I can do to set the setterMethods in the options. It just doesn't do anything.  When I put it in the options it works

## What is actually happening?
Nothing

node JS
Dialect:__** mysql **
Database version:__ 5.7
Sequelize version:__ 3.22

**Comment by janmeier** [comment]
I'm not sure what you are doing that doesn't work? 
```js
    let foo = Foo.build();

    foo.fullName = 'bar';
```
When I test it, the setter method is called

**Comment by mickhansen** [comment]
As a general note we're looking to move away from getterMethods, setterMethods.
Use virtuals + set/get instead.

**Comment by xtianus79** [comment]
@mickhansen are you referring to using those in the properties instead of options

**Comment by xtianus79** [comment]
@janmeier did you follow the syntax I used for an option and not a property

**Comment by janmeier** [comment]
Yes, I copy- :spaghetti: 'ed you code

**Comment by mickhansen** [comment]
@xtianus79 Yes, defining virtuals for stuff like fullName is recommended.

**Comment by xtianus79** [comment]
@mickhansen So, in general use properties instead of options.  thanks!

yea @janmeier I never got it to work that way but the properties set/get works fine.

**Comment by xtianus79** [comment]
ok just to make this clear and now I believe I gather what the documentation might be trying to say but could be cleaned up a little to make things clearer.  

@mickhansen so using the getterMethods will allow for virtuals to be built within the options... doesn't make sense in the attributes of a particular property because you most likely are trying to combine properties together.  Using the get / set methods should be done per the attribute of the property. Especially setter methods.  

this makes sense to me.
