### ISSUE TITLE
Hooks: false ignored

### ISSUE THREAD

**Issue by blanchma** [sequelize/sequelize#5868]
Sequelize version 3.23.0

User.findAll({attributes: ['id', 'email', 'created_at', 'enabled', 'confirmed_at'], order: [ order ], hooks: false })

In the hook I still get: 
options { where: '"User"."id" = \'1\'',
  plain: true,
  rejectOnEmpty: false,
  hooks: true...

It should say false and it shouldn't enter the hook.

**Comment by janmeier** [comment]
Please show a complete [SSCCE](HTTP://SSCCE.ORG/)

```js
let User = sequelize.define('user', {}, {
  hooks: {
    beforeFind() {
      console.log('beforefind!')
    }
  }
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(user => {
    return User.findAll({attributes: ['id', 'email', 'created_at', 'enabled', 'confirmed_at'], order: [ 'foo' ], hooks: false });
  })
```

With hooks: true it logs `beforefind`, without, it doesn't
