### ISSUE TITLE
Sequelize - querying by association questions

### ISSUE THREAD

**Issue by istrau2** [sequelize/sequelize#5873]
I have searched and searched and I cannot find the answers to these questions. I thought I would post here.

Here are a some models:

```
///Models/Account.js
module.exports = {
    attributes: {
        accountPkey: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            field: 'account_pkey'
        },
        accountName: {
            type: Sequelize.STRING,
            allowNull: false,
            field: 'account_name'
        },
        imagePkey: {
            type: Sequelize.INTEGER,
            field: 'image_pkey'
        }
    },
    associations: function() {
        Account.hasMany(Privilege, {
            as: 'Privileges',
            foreignKey: 'account_pkey'
        });

        Account.hasMany(AccountContact, {
            as: 'Contacts',
            foreignKey: 'account_pkey'
        });
    },
    options: {
        tableName: 'v_account',
        timestamps: false
    }
};

///Models/Privilege.js
module.exports = {
    attributes: {
        privilegePkey: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            unique: true,
            autoIncrement: true,
            field: 'privilege_pkey'
        },
        privilegeTypePkey: {
            type: Sequelize.INTEGER,
            field: 'privilege_type_pkey'
        },
        privilegeTypeName: {
            type: Sequelize.STRING,
            validate: {
                max: 255
            },
            field: 'privilege_type_name'
        },
        accountPkey: {
            type: Sequelize.INTEGER,
            field: 'account_pkey'
        },
        accountName: {
            type: Sequelize.STRING,
            validate: {
                max: 255
            },
            field: 'account_name'
        },
        userPkey: {
            type: Sequelize.INTEGER,
            field: 'user_pkey'
        },
        userName: {
            type: Sequelize.STRING,
            validate: {
                max: 255
            },
            field: 'user_name'
        }
    },
    associations: function() {
        Privilege.belongsTo(Account, {
            foreignKey: 'account_pkey'
        });

        Privilege.belongsTo(User, {
            foreignKey: 'user_pkey'
        });
    },
    options: {
        tableName: 'v_privilege',
        timestamps: false,
        classMethods: {},
        instanceMethods: {},
        hooks: {}
    }
};
```

Here is  a query (using the models above and a user model which I did not post for brevity - I can edit it in if needed):

```
function findByPrivilegeId(req, res, next) {

    Account.findAll(
        {
            where: req.query,
            include: [
                {
                    model: Privilege,
                    include: [
                        {
                            model: User,
                            where: {
                                userPkey: req.tokenData.user.userPkey
                            }
                        }
                    ],
                    where: {
                        privilegeTypeId: {
                            $in: req.query.privilegeTypeIds.split(',').map(id => parseInt(id))
                        }
                    }
                }
            ]
        })
        .then(accounts => res.ok(accounts))
        .catch(err => res.serverError(err));
}
```

Some questions:

1) Ideally, I would like to name my associations for a number of reasons
a) I would like to name my associations and include by association name so that there can be two associations between two models. So something like:

```
include: [
    associationName: 'owner',
    where: ...
]
```
For example a sports team might be associated with a person in two different ways, it can have an owner and a manager.
b) I would like to be able to access them in a more friendly way. Taking my model for example, I currently have account.Privileges, I would like it to be camelcase.

So the question is: Am I currently naming my association correctly (using 'as' in the definition) and how can I include by association name as opposed to model type?

2) How can I filter by joining (using includes) but not load any of the nested properties. In the query above, I only want to filter the accounts by privileges of a certain type having a certain userPkey. I don't actually want those privileges. I don't want sequelize to do the extra work involved in nesting the properties and I don't want to take the extra time to send all the extra information down the wire to the client.

**Comment by mickhansen** [comment]
You can disable attribute loading with `attributes: []` (however there's a bug with this currently for `through`)

You can have multiple associations between model, look at `as` or including by association reference.

**Comment by istrau3** [comment]
@mickhansen Thanks for the reply. So, suppose I said something like 
```
Privilege.belongsTo(Account, {
            as: 'account',
            foreignKey: 'account_pkey'
        });
```
1) would my setter and getter functions become setaccount and getaccount?
2) How would I use that reference in an include:

like this?

```
include: [
    model: 'account'
]
```

Thanks in advance.

**Comment by mickhansen** [comment]
@istrau2 i believe we still capitalize the first letter, but that's it.
No, it would be `{model: model, as: 'as'}` or `{association: association}` where association is `association = Mode.belongsTo(OtherModel);`

**Comment by istrau3** [comment]
@mickhansen Ok, thanks. So when I say:

```
include {
    model: Account
    as: 'account'
}

Does that mean that if my model has

```
Privilege.belongsTo(Account, {
            as: 'account',
            foreignKey: 'account_pkey'
        });
Privilege.belongsTo(Account, {
            as: 'other_account',
            foreignKey: 'other_account_pkey'
        });
```

that it will use the first association (i.e. join using foreign key account_pkey)? Does it match the 'as' used in the include to the 'as' used in the association definition?

**Comment by mickhansen** [comment]
No, it matches on `as`

**Comment by istrau3** [comment]
@mickhansen Sorry, not following. Do you mean that it uses ```as``` as the foreign key?

**Comment by mickhansen** [comment]
No, includes match on as.

**Comment by overlookmotel** [comment]
```js
Privilege.belongsTo( Account, { as: 'account', foreignKey: 'account_pkey' } );
Privilege.belongsTo( Account, { as: 'other_account', foreignKey: 'other_account_pkey' } );

Privilege.findAll( { include: { model: Privilege, as: 'account' } } );
Privilege.findAll( { include: { model: Privilege, as: 'other_account' } } );
```

Defining associations is covered here: http://docs.sequelizejs.com/en/latest/docs/associations/
And fetching them here: http://docs.sequelizejs.com/en/latest/docs/models-usage/#eager-loading (see the example with `Tools` aliased as `Instruments`)

@istrau3 Maybe just give it a go and see if you can get it working?
