### ISSUE TITLE
Travis: test Node 4, 5, 6?

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5878]
I just saw that Travis only tests against iojs4, what about newer Node versions?

**Comment by mickhansen** [comment]
For 4.0 we're considering moving to Node 6 only support, not sure yet.
Right now we don't want to increase number of builds

**Comment by felixfbecker** [comment]
You should atleast always test against latest stable and LTS imo... Is anyone still using iojs?
I think Node 6 doesn't provide that much more in features than Node 4, which already has classes. But that is a different issue of course.

**Comment by mickhansen** [comment]
We still officially support 0.10 and 0.12 tho. We could consider removing iojs 1-2 for Node 4 & 6.

**Comment by overlookmotel** [comment]
Agreed could be good to switch iojs 1-2 for Node 4 & 6 in Sequelize v4. Personally I'd appreciate continued support for Node 0.12, but maybe 0.10 could be dropped.

**Comment by janmeier** [comment]
Let's move this discussion to https://github.com/sequelize/sequelize/pull/5918
