### ISSUE TITLE
deletedAt should be compare against NOW rather than IS NULL

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#5880]
Under current implementation sequelize always compare `deletedAt` field with `IS NULL`, while it works but it just act as a boolean field.

It should ideally compare `deletedAt` against current timestamp value like `NOW`. This will make `deletedAt` semantically correct because its a date field.

This will also allow instances to be deleted on future dates. Some features can be implemented easily which requires expiration after some time like session, tickets, oauth tokens etc...

__Dialect:__  any
__Sequelize version:__ master

**Comment by janmeier** [comment]
Sounds good :)
