### ISSUE TITLE
beforeUpdate only get called for save() and not update()

### ISSUE THREAD

**Issue by mickeyckm** [sequelize/sequelize#5882]
I'm trying to update a model but my beforeUpdate hook doesn't get called when I use the update method. However, if I use the select and save(), then the beforeUpdate method gets call. This is a rather strange behaviour. 

__Dialect:__ postgres
__Database version:__ 9.3
__Sequelize version:__ 3.19.3

**Comment by janmeier** [comment]
Please show some code

**Comment by mickeyckm** [comment]
```
// Update works but without calling beforeUpdate()
Model.update({
   field: value,
   field2: value2,
}, {
   where: {
      field3: value3
   }
});

// Update works with beforeUpdate() executed.
Model.find({
   where: {
      field3: value3
   }
})
.then(function (model) {
   model.field2 = value2;
   return model.save();
});


// model.js
Model.beforeUpdate(function (coverLetter, options, callback) {
   console.log("beforeUpdate");
});
```

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

Use `individualHooks` or `beforeBulkUpdate`

**Comment by mickeyckm** [comment]
it works. thank you for your time.
