### ISSUE TITLE
Calling Instance.create with an array does not work

### ISSUE THREAD

**Issue by cgreening** [sequelize/sequelize#5883]
From the documentation you should be able to call Instance.create and pass an array of objects to be created.

Looking at the code in model.js when you pass an array of objects in it uses the bulkBuild function:

```
Model.prototype.build = function(values, options) { // testhint options:none
  if (Array.isArray(values)) {
    return this.bulkBuild(values, options);
  }
```

```
Model.prototype.bulkBuild = function(valueSets, options) { // testhint options:none
...
  return valueSets.map(function(values) {
    return this.build(values, options);
  }.bind(this));
};
```

bulkBuild returns an array of objects and the save method tries to call save on this array resulting in a crash.

```
Model.prototype.create = function(values, options) {
  options = optClone(options || {});

  var buildResult = this.build(values, {
    isNewRecord: true,
    attributes: options.fields,
    include: options.include,
    raw: options.raw,
    silent: options.silent
  });
  buildResult.save(options);
};
```

TypeError: buildResult.save is not a function

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance

**Comment by frogcjn** [comment]
Any one here? Same question.

**Comment by cgreening** [comment]
I'm not sure why the issue was closed, doesn't feel resolved to me.

**Comment by janmeier** [comment]
As @frogcjn says, `create` is for a single row, `bulkCreate` that i linked is for an array of rows

**Comment by frogcjn** [comment]
@janmeier 
but  in `create`, there is a case to resolve array of objects, what this used for?

**Comment by janmeier** [comment]
@frogcjn Where do you see that case? https://github.com/sequelize/sequelize/blob/4b2bc4a6a2fca033f2990320a9b6a77f571bb0e0/lib/model.js#L1761

**Comment by frogcjn** [comment]
@janmeier 

Create directly call build, and build can work with array of objects, and return array of objects.
https://github.com/sequelize/sequelize/blob/4b2bc4a6a2fca033f2990320a9b6a77f571bb0e0/lib/model.js#L1714

**Comment by janmeier** [comment]
Thats a performance optimization, used when rows are loaded from the database. You are welcome to call `build` with an array, just not `create`

**Comment by frogcjn** [comment]
@janmeier 
OK.
