### ISSUE TITLE
Unable to order by createdAt PostgreSQL...

### ISSUE THREAD

**Issue by nvrnight** [sequelize/sequelize#5886]
Given this query...
model.token.findOne({
    where: {
        memberId: member.id
    },
    order: 'createdAt DESC'
}).then(...);

It generates the following SQL, which fails in PostgreSQL when I execute manually in workbench.
SELECT "id", "value", "used", "createdAt", "updatedAt", "memberId" FROM "tokens" AS "token" WHERE "token"."memberId" = 64 ORDER BY createdAt DESC LIMIT 1;

If I replace createdAt with "token"."createdAt" the query works fine.

Maybe I'm using the order API wrong? Below is what I'm doing for now as a workaround for now, if anyone has better ideas, please let me know.
model.token.findOne({
    where: {
        memberId: member.id
    },
    order: '"token"."createdAt" DESC'
}).then(...)

Ubuntu 16.04 64bit
"sequelize": "^3.22.0",
"sequelize-cli": "^2.4.0",

**Comment by mkay581** [comment]
I'm getting this same error. Hopefully there is a fix coming. 👍

**Comment by mjgpy3** [comment]
Hi there!

I'm fairly new to Sequelize but if you look at [their docs](http://docs.sequelizejs.com/en/latest/docs/querying/?highlight=order:#ordering) they state that ordering statements which are simply strings will be used literally.

It looks like you can give it an array with the key and "direction" to avoid this behavior, so, something like
```
model.token.findOne({
  where: {
    memberId: member.id
  },
  order: [
    ['createdAt', 'DESC']
  ]
})
```
should cut it.

Let me know if that doesn't work

**Comment by janmeier** [comment]
@mjgpy3 Is right, wrap it in an arrray. 

Camel cased columns in postgres need to be quoted, thats why the query without quotes is failing
