### ISSUE TITLE
Returning associated entities in defaultScope

### ISSUE THREAD

**Issue by aray12** [sequelize/sequelize#5887]
I have been following the workaround provided in #3963 for defining scopes with associations even if the associated entity hasn't been initialized since I am using the recommend bootstrapping method. This has been great except now I want to accomplish the same thing with a `defaultScope`. It says in the docs that the defaultScope must be a plain object (not a function that returns an object). I have tried wrapping it in a function anyway just to see what happens and I get no error and it just returns a plain object as if there was no `defaultScope` defined. If I make the scope a standard scope and call it explicitly everything works perfectly.

My question is, is there a standard workaround for this and shouldn't an error be thrown when `defaultScope` is a function instead of failing silently?

```
module.exports = function define(sequelize, DataTypes) {
	return sequelize.define('billing_policy',
		{
			billing_policy_id: {
				type: DataTypes.INTEGER,
				primaryKey: true,
				autoIncrement: true,
			},
			billing_policy_name_meta: {
				type: DataTypes.STRING,
				allowNull: true,
			},
		},
		{
			defaultScope: () => ({
				include: [
					{
						model: sequelize.models.lang_label,
						as: 'billing_policy_name',
					},
				],
			}),

			classMethods: {
				associate: function associate(models) {
					models.billing_policy.belongsTo(models.lang_label,
						{
							as: 'billing_policy_name',
							foreignKey: 'billing_policy_name_label',
						});
				},
			},

			timestamps: false,
		});
};


// Response 
[
  {
    "billing_policy_id": 1,
    "billing_policy_name_meta": "Flexible",
    "billing_policy_name_label": 20,
  },
  {
    "billing_policy_id": 3,
    "billing_policy_name_meta": "Moderate",
    "billing_policy_name_label": 21,
  }
]

// Expected
[
  {
    "billing_policy_id": 1,
    "billing_policy_name_meta": "Flexible",
    "billing_policy_name_label": 20,
    "billing_policy_name": {
      "en": "Flexible"
    }
  },
  {
    "billing_policy_id": 3,
    "billing_policy_name_meta": "Moderate",
    "billing_policy_name_label": 21,
    "billing_policy_name": {
      "en": "Moderate"
    }
  }
]
```

**Comment by janmeier** [comment]
`addScope` http://docs.sequelizejs.com/en/latest/api/model/#addscopename-scope-options allows you to add a default scope after the model has been defined
