### ISSUE TITLE
Can't connect to postgres using SSL when using "use_env_variable" in config.json

### ISSUE THREAD

**Issue by cgreening** [sequelize/sequelize#5891]
This works without any issues:

```json
  "production": {
    "username": "XXX",
    "password": "XXX",
    "database": "XXX",
    "host": "XXX",
    "port": "XXX",
    "dialect": "postgres",
    "dialectOptions": {
      "ssl": true,
      "native": true
    }
  }
```

But this does not:

```json
  "production": {
  "use_env_variable": "DATABASE_URL",
    "dialect": "postgres",
    "dialectOptions": {
      "ssl": true,
      "native": true
    }
}
```

Using a database URL like this:

```
 export DATABASE_URL="postgres://XXX:XXXX@XXXXX:XXXX/XXXX?ssl=true
```

Adding the ?ssl=true makes no difference, using the dialectOptions makes no difference. Seems like the ssl is ignored completely when using a DATABASE_URL...

**Comment by janmeier** [comment]
Sequelize does not support a config.json file - If you are using a config file with sequelize you must be passing those variables manually to sequelize. If you are using it with umzug / cli, please report the issue in the corresponding repo
