### ISSUE TITLE
Getting many-to-many association additional attributes

### ISSUE THREAD

**Issue by edpop** [sequelize/sequelize#5894]
Hello.
I have a simple user - role association with some association options.

```js
/**
 * define
 */
var User = db.define('user', {
  "name": DataTypes.STRING(250)
});

var Role = db.define('role', {
  "name": DataTypes.STRING(250)
});

var UserRole = db.define('user_role', {
  "opts": DataTypes.JSONB
});

User.belongsToMany(Role, {
  through: UserRole
}
```

```js
/**
 * example
 */
var myOptions = { some: "options" };

User.create({
  "name": "Petya"
}).then(function (user) {
  Role.create({
    "name": "admin"
  }).then(function (role) {
    user.addRole(role, { "opts": myOptions })
  });
});
```

How can i get my { some: "options" } attribute more correctly?
After some debugging, I found this solution, but it is very ugly and better use simple SQL.
```js
/**
 * Not pretty solution
 */
user.getRoles().then(function (roles) {
  console.log(roles[0].user_role.opts); // { some: "options" }
});
```

Please, include your answer to your [example](http://docs.sequelizejs.com/en/latest/api/associations/belongs-to-many/), to get role of user in project.

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.21.0

**Comment by janmeier** [comment]
That is the correct way to get there data - I'm not sure why you find it ugly. What do you mean by 'use simple SQL'? Do you want to only select the data from the join table, without selecting from the role table?

**Comment by edpop** [comment]
No, I need user role + opts. Truly I can't imagine any good semantics for this. Thank you.
