### ISSUE TITLE
bulkCreate with updateOnDuplicate:true changes created_at timestamps on updates

### ISSUE THREAD

**Issue by daamsie** [sequelize/sequelize#5899]
## What you are doing?

Using bulkCreate to "INSERT INTO .. ON DUPLICATE KEY UPDATE _" multiple fields

``` js
models.Image.bulkCreate(
  images,
 {
   updateOnDuplicate:true
  }
)
```
## What do you expect to happen?

Maintain the created_at date when updating a record
## What is actually happening?

When a duplicate key is encountered, the created_at date is also updated

`INSERT INTO`images`(`id`,`src`,`width`,`height`,`created_at`,`updated_at`) VALUES (NULL,'http://example.com/1.jpg','205','162','2016-05-17 00:06:06','2016-05-17 00:06:06'),(NULL,'http://example.com/2.jpg','205','162','2016-05-17 00:06:06','2016-05-17 00:06:06') ON DUPLICATE KEY UPDATE`id`=VALUES(`id`),`src`=VALUES(`src`),`width`=VALUES(`width`),`height`=VALUES(`height`),`created_at`=VALUES(`created_at`),`updated_at`=VALUES(`updated_at`);`

Dialect:  mysql 
Database version: mariadb 10.0.16
Sequelize version: 3.23.0

Suggestion: The performed query above should be adjusted to the following (removing created_at from the UPDATE):

`INSERT INTO`images`(`id`,`src`,`width`,`height`,`created_at`,`updated_at`) VALUES (NULL,'http://example.com/1.jpg','205','162','2016-05-17 00:06:06','2016-05-17 00:06:06'),(NULL,'http://example.com/2.jpg','205','162','2016-05-17 00:06:06','2016-05-17 00:06:06') ON DUPLICATE KEY UPDATE`id`=VALUES(`id`),`src`=VALUES(`src`),`width`=VALUES(`width`),`height`=VALUES(`height`),`updated_at`=VALUES(`updated_at`);`

**Comment by daamsie** [comment]
I looked in the source for bulkCreate and see that this line should be taking care of it

`var updatableFields = Utils._.pull(Object.keys(this.tableAttributes), 'createdAt');`

I'm using underscored timestamp attributes though and it seems that perhaps that is not accounted for in this code.

I'm working around this issue by passing an array of only the attributes that need to be updated, ie.. 

`updateOnDuplicate: ['width','height']`

rather than 

`updateOnDuplicate: true`

**Comment by mscheffer** [comment]
updateOnDuplicate is an array of fields, not  a boolean, (bad name by the way), just pass the name of all the fields -createdAt

**Comment by aasmm7x** [comment]
@mscheffer actually following the docs, we can pass an boolean to update all the fields by default, but the implementation is incomplete. For example, it tries to update the primary key as well.

**Comment by pradeeppal2677** [comment]
abcdef
