### ISSUE TITLE
Question about postgres multi-schema support

### ISSUE THREAD

**Issue by FoxMcCloudDX** [sequelize/sequelize#5901]
This is not a bug, but a question.

I want to use sequelizejs/postgresql for a SaaS application where data for different accounts(tenants) will be stored in different schemas.

I use several models and associations between them. Both the same models and associations are used for the different schemas.

When i use `model.schema('my-tenant-schema')`  associations still use the default schema, not 'my-tenant-schema'.

How can I set the schema for the queried model and the associated models in a per-request basis?

**Comment by llonchj** [comment]
+1

**Comment by janmeier** [comment]
Have a look at [searchPath](https://github.com/sequelize/sequelize/pull/4534). We might need to add an option to override the default search path for the sequelize instance (which currently defaults to `DEFAULT`) - Such that you can create a sequelize instance with the correct search path for each tenant.

**Comment by offero** [comment]
I have the same exact issue.
