### ISSUE TITLE
Timezone bug for raw query

### ISSUE THREAD

**Issue by helloyou2012** [sequelize/sequelize#5903]
`Model.create` and `sequelize.query(insertSQL, { replacements: [new Date()] } )` timezone is different.

Maybe bug at: https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L81

**Comment by janmeier** [comment]
Yep, timezone should definitely be passed down from `.query`. I'm taging this as a mysql bug, since postgres and sqlite are not affected (they store the timezone info in the db, so it doesn't matter that the timezone is lost)

**Comment by xycloud** [comment]
I have the same problem

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by drc-tshannon** [comment]
I believe this is an issue with SQL Server as well as the data type for dates defined for the sqlserver dialect is datetime2 which is UTC.
