### ISSUE TITLE
Correct way to model.get({plain: true})

### ISSUE THREAD

**Issue by SohaibFarooqi** [sequelize/sequelize#5904]
Hi,
I have a findAll() query that returns array. I am struggling with correct way to place 
```model.get({plain: true})```. Do i have to iterate over array and call .get() on each individual object or is there a way to specify this inside model class. 
Right now what i am doing is i have a classMethod call trimMeta(array) which iterates over and perform 
```model.get({plain: true})```. But doing this cause toJSON() [instanceMethod] to never invoke.

**Comment by sushantdhiman** [comment]
with `findAll` results you can just

`results = results.map( (r) => ( r.toJSON() ) )`

**Comment by SohaibFarooqi** [comment]
It doesn't trim meta properties. I have checked it with console.log(results[0]) and it displays meta info

**Comment by sushantdhiman** [comment]
What meta info ?  `toJSON` will only have your table attributes nothing more.

**Comment by SohaibFarooqi** [comment]
like attributes definition  XYZ: {type: ... , model: ... , fieldname: ...} for each attribute. It does have an array of attributes.

**Comment by sushantdhiman** [comment]
Are you sure you are printing the toJSON output? can you me the code you use to output?

**Comment by SohaibFarooqi** [comment]
.then(function(agent_list){
         var result = agent_list.map((r) => (r.toJSON()));
         console.log(result[0]);
         callback(null,agentCategory,result);})

**Comment by sushantdhiman** [comment]
What extra output do you see in the result[0], can you show it?

**Comment by SohaibFarooqi** [comment]
![log1](https://cloud.githubusercontent.com/assets/13061583/15319938/235c6c82-1c47-11e6-8c78-8561a4e5f9ca.JPG)
![log2](https://cloud.githubusercontent.com/assets/13061583/15319939/23f5ab90-1c47-11e6-837a-3a90f315ac52.JPG)

**Comment by sushantdhiman** [comment]
Show your findAll code ?

**Comment by SohaibFarooqi** [comment]
var agent_list =  models.agent.findAll({
       subQuery:   false,
      where:      qry_filter,
      attributes: select_attributes,
      include:    include_models,
      group:      ['agent_id'],
      order:      agent_data.sort        || appConfig.DEFAULT_AGENT_SORT,
      limit:      agent_data.num_results || appConfig.DEFAULT_RESPONSE_SIZE
                                        }).then(function(agent_list){
                                         var result = agent_list.map((r) => (r.toJSON()));
                                         console.log(result[0]);
                                         callback(null,agentCategory,result); 
                                         }).catch(function(reason){
                                         console.log(reason);
                                       });

**Comment by sushantdhiman** [comment]
Your filter may have some issue, because for my tests plain `findAll` works fine (its just a plain `map()` call), may be try removing your `attributes` and `include` will help.

**Comment by SohaibFarooqi** [comment]
Sorry i just checked my code. I was overriding toJSON method that was causing the problem. It is working good now. Thank you.
However nested json objects still carry meta info with them. any work around for them?

**Comment by sushantdhiman** [comment]
You may have overridden the toJSON method for those nested models as well

**Comment by SohaibFarooqi** [comment]
yes i have overridden those nested models. Parent model's tojson is also overridden. But only in child model it is creating issue

**Comment by sushantdhiman** [comment]
You have to 'free' all `toJSON` methods for all involving models. Internally we call the `toJSON` for each included model.

**Comment by SohaibFarooqi** [comment]
Yes i know but i have to omit certain attributes in response to i have to override tojson

**Comment by sushantdhiman** [comment]
You know one time I had the same exact question #5524 , Its clear that we are not going to support this feature. 

May be you should build custom method which you can use to remove any attributes you may want to. If you build it in organized way its called DTOs. You have to build it by yourself rather than overriding `toJSON`

**Comment by SohaibFarooqi** [comment]
Oh I read the issue you mentioned some time back. It will give it a try. 
Thank you for your time.! :)

**Comment by sushantdhiman** [comment]
Hi @janmeier , this issue can be closed. OP overridden the `toJSON` on models which resulted the issue.

**Comment by janmeier** [comment]
@sushantdhiman Thanks :)

I'm wondering whether `.toJSON` should recursively call `toJSON`, instead of caling `.get` on includes - It just feels more natural to override to json than get - But lets close this one in any case
