### ISSUE TITLE
How to sort queries from serialized/virtual values calculated asynchronously?

### ISSUE THREAD

**Issue by Neefay** [sequelize/sequelize#5907]
I'm not the type to open issues to ask for help, but this time around I am beyond stumped on how to proceed, and any hints or points would be appreciated beyond the words in my vocabulary. I apologize for the length of this post, but I'm afraid to fall short on attempted brevity.

## The Setup
This particular issue arises from a table for items/products(_ItemsModel_), containing the regular fields you'd imagine, including one for its base value.
Another table, also relevant for this issue, is a table for discounts and deductions(_ModifiersModel_), which contains the positive or negative percentage to be applied over the value of every type and class of item.

Now, within the _ItemsModel_ schema, we have two other fields which are stored with null values, functioning like a Virtual data type: _ItemDiscount_ and _ItemCurrentPrice_, which are calculated from the _ModifierModel_(more on that later). Since Sequelize does not support asynchronous methods on the field's getter, the aforementioned fields are populated on a _afterFind_ hook once queried, and then returned to the user.

_ItemsModel_
```js
var ItemModel = sequelize.define('items_table',
			{
				nameField: {
					type: DataTypes.STRING,
					field: 'name',
					defaultValue: 'Generic Item'
				},
				valueField: {
					type: DataTypes.FLOAT,
					field: 'value',
					defaultValue: 0
				},
				currentPrice: { // Dummy field.
					type: DataTypes.INTEGER,
					field: 'current_price',
					defaultValue: 0
				},
				discountField: { // Dummy field.
					type: DataTypes.INTEGER,
					field: 'discount',
					defaultValue: 0
				},
			},
[...]
```

```js
ItemModel.afterFind(function(model, options) {
[...]
// Queries the ModifierModel and returns the active price modifier.
return ModifierModel.findOne({ where: {"activeField": true}}).then(function(modifier) {
[...] 
// Logic is performed afterwards.
```

**To recap**:

1. _ItemsModel_ has two null/Virtual fields: _ItemDiscount_ and _ItemCurrentPrice_.
2. _ModifierModel_ holds the discount values for all Item types and classes.
3. The user queries _ItemsModel_ with the relevant query options. 
4. _afterFind_ing all relevant data, the hook then queries _ModifierModel_ for the relevant discount percentages, calculates the correct value, and then utilizing `setDataValue(ItemCurrentPrice, calculatedValue)` attributes it to the Virtual fields.
5. The queried items are returned to the user, containing the item's base price, fixed value adjusted with the discounts, and the discount percentage itself.

## The Issue
My problem, as a more savvy user might have already caught on, is pretty straightforward: **since the Virtual values are only set _after_ the query, they are therefore impossible to be used as a sorting parameter**. For example, it becomes impossible to query products within a certain discount or price range, which spells a pretty huge issue for the UX.

__Dialect:__ mysql
__Sequelize version:__ "3.14.2"

## In Closing
So far my time with Sequelize has been fantastic and I've been progressing on my project smoothly and without any major headaches - I'd like to make a note to acknowledge how awesome it is.

I have no attachment to the current method I'm utilizing, by the way. So if anyone feels like pointing me to a different approach or angle to this problem that will let me reach the results I need, please, feel free.

Thank you very much for reading through this issue.

**Comment by janmeier** [comment]
Thanks for the kind words :)

Sadly I don't think there is any good way to solve this right now. I imagine a good way to do this would be something like `Sequelize.CALCULATED` - which allows you to add attributes to a model that are calculated as aggregates / from other tables 

```js
ItemCurrentPrice: {
  type: Sequelize.CALCULATED('SELECT ... FROM ModifierModel...' )
}
```
Then you would be able to add `ItemCurrentPrice` to attributes, and also add orders and where params based on it (the subs-select would be alissed to `ItemCurrentPrice`).

For now you could add a `beforeFind` hook, which maps through `options.attributes`, and replaces `ItemCurrentPrice` with `[sequelize.literal(query), 'ItemCurrentPrice]`

**Comment by Neefay** [comment]
@janmeier Thanks for the reply!

That's a big shame to hear, but I guess now I have no other option but to bite the bullet and assign the _ModifierModel_ to synchronously read from a static file and retrieve the values through a getterMethod - it's a bit of a ghetto solution but it should probably get the job done.

Finally, is there a piece of the documentation I could read further to understand this last bit about using `[sequelize.literal(query), 'ItemCurrentPrice]` ? Admittedly I'm a huge newbie when it comes to coding, so I'm a bit confused.

**Comment by janmeier** [comment]
There is a bit about its usage here : http://docs.sequelizejs.com/en/latest/docs/querying/

Basically you can put an array into `attributes` to rename it, i.e. `attributes: [['foo', 'bar']]` gives you `SELECT foo AS bar`

Literal allows you to write anything, and it will be put into the query without escaping (by default strings are escaped, so passing the raw sql string won't work.

If you add a `beforeFind` hook you could turn `attributes: ['ItemCurrentPrice']` into `attributes: [[sequelize.literal('query to select ItemCurrentPrice'), 'ItemCurrentPrice']], which again turns into `SELECT [query to select ItemCurrentPrice] AS 'ItemCurrentPrice'` - which means you'll be able to sort and filter based on the value

**Comment by Neefay** [comment]
Ah, no, sadly this won't work.

The whole issue arises from the fact that before the _ItemCurrentPrice_ is assigned, it is always 0, and only has a correct value assigned to it once the _ModifierModel_ is queried to figure out the proper discount numbers - after those are retrieved there is some logic involved on how to process those numbers back into the _ItemCurrentPrice_ value, which is then returned to the player. All the aforementioned logic has to happen within an _afterFind_ hook, otherwise I would have to query every single item in the database and assign its respective _ItemCurrentPrice_ every time a query, no matter how small, is performed.

Like you suggested, an asynchronous getter method, or a specialized dataType could do the trick, but the more I discuss this issue, the more it sounds like a failure within my own design than something that should be blamed on Sequelize itself. Maybe I should move this to stackoverflow or something.

Thank you for the help.

**Comment by Neefay** [comment]
I've taken a less optimized, brutal approach to this issue by updating every single item whenever a modifier is changed. Thanks again @janmeier for your assistance.

**Comment by Mohamed-Taher-Ali** [comment]
i found a solution GOD welling @Neefay 
you can use sequelize.literal in order statement so you can just pass the name of new calculated field
