### ISSUE TITLE
'hasMany' associated query:  ER_BAD_FIELD_ERROR

### ISSUE THREAD

**Issue by kkthxby3** [sequelize/sequelize#5912]
## What you are doing?
Attempting to query a defined Sequelize model through a mySQL database.  The query was working as expected with an included model that is associated to the query model via 'belongsTo'.  However, after including a second model that is associated to the query model through a 'hasMany' relationship an error is being thrown. 

The error is thrown with or without the multiple includes.  The issue is solely with the include of the 'hasMany' model which results in the same error. 

The models and query are shown below: 

```
var post = Sequelize.define('post', {
column1: {}, .... 
},
{
		freezeTableName: true,
		classMethods: {
		associate: function(models) {
			post.belongsTo(models.user, {foreignKey: 'user_id'});

			**post.hasMany(models.comment, {foreignKey: 'post_id'});**
		}
	},
	tableName: 'post'
});
```

```
var comment = Sequelize.define('comment', {
column1: {}, .... 
},
{
		freezeTableName: true,
		classMethods: {
		associate: function(models) {
			comment.belongsTo(models.user, {foreignKey: 'user_id'});

			**comment.belongsTo(models.post, {foreignKey: 'post_id'});**
		}
	},
	tableName: 'comment'
});
```

```
db.post.findAll({ limit: 10, 
			attributes: ['id', 'content', 'user_id'], 
			order: [['createdAt', 'DESC']], 
			include: [{model: db.comment,
			              attributes: ['id', 'comment', 'post_id'], 
			              order: [['createdAt', 'DESC']]
			}]
		})
```

## What do you expect to happen?
I expect the query to return the columns of the 'post' table with the associated columns of the 'comment' table. 

## What is actually happening?
```sql
SELECT `post`.*,
       `comments`.`id` AS `comments.id`,
       `comments`.`comment` AS `comments.comment`,
       `comments`.`post_id` AS `comments.post_id`
FROM
  (SELECT `post`.`id`,
          `post`.`content`,
          `post`.`user_id`
   FROM `post` AS `post`
   ORDER BY `post`.`createdAt` DESC LIMIT 10) AS `post`
LEFT OUTER JOIN `comment` AS `comments` ON `post`.`id` = `comments`.`post_id`
ORDER BY `post`.`createdAt` DESC;
```
**Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'post.createdAt' in 'order clause'**

The 'post' table has the expected 'createdAt' column.  The query itself was working fine by itself and with includes that are associated by 'belongsTo' in the post model.  It's only with the 'hasMany' comment model added does this error occur.  Comment has the expected date columns and has been used by itself so not sure what the issue is. 

One issue is do see in the SQL syntax is the reference of 'comments'.  The table is defined as 'comment' and I don't recall seeing this in other queries. 

I did see previous issues posted on here that look similar but with different error messages or from 2013.  

Any insight into working around this or if there is something improper will be much appreciated.  

Thank you.  

__Dialect:__ mysql
__Database version:__ 5.5.47-0+deb8u1
__Sequelize version:__ ^3.19.2

**Comment by janmeier** [comment]
`post` in the outer query refers to the subquery, so you need to select `createdAt` from the subquery (add `createdAt` to the attributes of the include)

**Comment by kkthxby3** [comment]
Thank you for the response... 

I tried adding 'createdAt' to the attributes for the included model, comment, but I get the same error.  Even if I remove the attributes where the entire row is selected, I get the same error.

However, I did try adding the 'createdAt' column to the post's attributes...  And that worked.  

Thank you again.  =)

**Comment by janmeier** [comment]
Ah yes, thats what I meant - Glad you figured it out ;)
