### ISSUE TITLE
Dollar prefixes on methods

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5919]
When working with the code and also when debugging I wondered why Sequelize mixes dollar, underscore and double underscore prefixes for methods and what their meaning are. The convention seems to be to use underscore for private methods / properties, and dollar should imo be buried with jQuery. Sometimes Sequelize even assigns the same method with both a dollar and an underscore. Maybe this can be cleaned up for 4.0?

**Comment by janmeier** [comment]
They are all meant to signify private methods - So this could definitely be clean up! :)

**Comment by mickhansen** [comment]
I actually prefer $ for privates rather than _, but nothing i care too deeply about.
We should probably pick one thing and go with that atleast :)

**Comment by felixfbecker** [comment]
@mickhansen from my experience underscore is the convention and used in all great javascript libraries, so I would vote for that.

**Comment by mickhansen** [comment]
@felixfbecker You're probably right about that, don't know where i found $ originally.
