### ISSUE TITLE
Interpreting complex query issues

### ISSUE THREAD

**Issue by Djalmar** [sequelize/sequelize#5920]
## What you are doing?
I'm using [sequelize-hierarchy](https://github.com/overlookmotel/sequelize-hierarchy), to create nested hierarchys for an organization.
And it creates a huge query

```
 params.include = [
    {
      model: Oficina,
      as: 'Oficinas',
      include: [
        {
          model: UnidadOrganizacional,
          as: 'OficinaUnidad',
          include: [
            {
              model: UnidadOrganizacional,
              as: 'descendents',
              hierarchy: true,
              include: [
                {
                  model: Cargo,
                  as: 'Cargos'
                }]
            },
            {
              model: Cargo,
              as: 'Cargos'
            }]
        }]
    },
    {
      model: Entidad,
      as: 'descendents',
      hierarchy: true,
      include: [
        {
          model: Oficina,
          as: 'Oficinas',
          include: [
            {
              model: UnidadOrganizacional,
              as: 'OficinaUnidad',
              include: [
                {
                  model: Cargo,
                  as: 'Cargos'
                }]
            }]
        }]
    }];
params.where = {
    _id: req.params.id
  };
  // params.raw = true;
  Entidad.find(params)
```

## What do you expect to happen?
The generated query works fine, it returns what it should do, but the `then()` clause is never been accessed, i think  the problem is when sequelize is parsing it to an object or adding its, because when i use `{raw: true}` it works fine.

## What is actually happening?
The error thrown is:

> [TypeError: key.indexOf is not a function]

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.5.1

**Comment by janmeier** [comment]
Please include the stack-trace. Please include models and associations so we can try to reproduce the issue, preferrably as a [SSCCE](HTTP://SSCCE.ORG/)
