### ISSUE TITLE
Using sequelize.fn as defaultValue in alterColumn

### ISSUE THREAD

**Issue by ncwhale** [sequelize/sequelize#5923]
I want to got id column with `DEFAULT gen_random_uuid()` auto when set the `defaultValue: UUIDV4`, but for now it did not do this.

Define some models like this one:

``` js
Topic = sequelize.define('Topic', {
    id: {
      type: DataTypes.UUID,
      allowNull: false,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4
    },
    author: {
      type: DataTypes.UUID,
      allowNull: false
    },{});
```

And create DB struct like this:

``` js
  up: function (queryInterface, Sequelize) {
    return models.Topic.sync({ force: true })
      .then(result => {
        return queryInterface.sequelize.query("ALTER TABLE \"Topics\" ALTER COLUMN id SET DEFAULT gen_random_uuid();");
      });
  },
```

BTW, queryInterface need a `query` function(just a suger from sequelize object) to do better job when up/down db by SQL.

**Dialect:**  postgres 
**Database version:** 9.5
**Sequelize version:** 3.23.2

**Comment by janmeier** [comment]
By default uuids are generated software side - You can use `defaultValue: sequelize.fn('gen_random_uuid');` to use a function in the DB

**Comment by ncwhale** [comment]
gen uuid in software side is one option, but some times when we need to import/export data directly, to use a database default is more helpful.

**Comment by ncwhale** [comment]
When I try to do this in migrate, it did not work:
```js
   return models.Topic.sync({ force: true })
      .then(result => {
        return queryInterface.changeColumn(
          "Topics", 'id', {
            defaultValue: queryInterface.sequelize.fn('gen_random_uuid')
          }
        );
      });
```

this is the error code:

```
    return models.Topic.sync({ force: true })
      .then(result => {
        return queryInterface.changeColumn(
          "Topics", 'id', {
            defaultValue: queryInterface.sequelize.fn('gen_random_uuid')
          }
        );
        // sequelize.query("ALTER TABLE \"Topics\" ALTER COLUMN id SET DEFAULT gen_random_uuid();");
      });
```

**Comment by janmeier** [comment]
Tagging as a bug then
