### ISSUE TITLE
Is it possible to JOIN tables that are not associated?

### ISSUE THREAD

**Issue by Neefay** [sequelize/sequelize#5929]
Due to the fact that bulk updating did not quite work for me when using the Relations/Associations methods, I was forced to manually set the relations between the tables using values other than the foreign key - it's a bit of a clustercuss but it works.

So I was wondering if it's at all possible to Include models not related on regular queries? For example, this will **NOT** work, without even outputting any errors or queries:

```js
InventoryModel.findAndCountAll({
	include: [{
		model: ItemModel,
		as: 'Items',
		through: {
			attributes: ['nameField'],
			where: {hashField: ["0edf65a5bdbfbb1318de"]}
		}
	}]
}).then(function(ownedItems) {	
```

As where this will just do the trick:

```js
sequelize.query(
'SELECT * FROM `player_items` LEFT JOIN `items_tables` on player_items.item = items_tables.hashField'
).then(function(results) {
```

Of course, for the sake of cohesion and efficiency I would like to stick with the first method instead of using a raw query, but so far every single place I've searched has indicated that JOINs are only available to models bound together by Associations.

Thank you for your time.

**Comment by sushantdhiman** [comment]
Atleast you can map raw query result to a model by

```js
sequelize.query('SELECT * FROM projects', { model: Projects }).then(function(projects){
  // Each record will now be a instance of Project
})
```

But you have to write the join as raw query.

**Comment by Neefay** [comment]
@sushantdhiman Well crud, thanks for answering. I guess before I close the issue, is anyone aware if there's a method to convert the sequelize operators ($and, $like, $between) to a raw SQL query? That would help a lot on compensating.

**Comment by Neefay** [comment]
I went ahead and just wrote something myself. Thanks, closing.

**Comment by janmeier** [comment]
`sequelize.dialect.QueryGenerator.whereItemsQuery` https://github.com/sequelize/sequelize/blob/3d14a4a63b2b8ecc517cb03e8d4ed59b1d177132/lib/dialects/abstract/query-generator.js#L1868
