### ISSUE TITLE
Consider using TypeScript for 4.0

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5938]
The idea to use a transpiler (Babel) in 4.0 has been brought up numerous times (also as the idea of using coroutines). If Sequelize is going to use Babel, that would allow to use new features like classes without raising Node version requirement at the cost of an transpilation step and worse performance compared to native classes/arrow functions/etc. In my opinion that transpilation step is not worth it if it doesn't provide any real benefit other than better BC.
However, one transpiler would hugely benefit Sequelize, and that is TypeScript. Sequelize has a huge code base. Understanding it (especially for new contributors), preventing bugs (mistyped method name, types, members, params etc), and documenting all the options with JSDoc is extremely hard.

Why I think 4.0 should use TypeScript:
 - Clear declaration of class members, exports and parameter types
 - Catch errors like wrong methods, types or params at compile time
 - Awesome Autocompletion support for contributors, maintainers and users of Sequelize
 - Direct output of .d.ts files instead of third-party
 - Beautiful documentation with [typedoc](http://typedoc.io/)
 - Instead of specifying nested params in docblocks like `@param {(string|Model)} options.include[].model` over and over for every variation of the `find()` method, we could define _interfaces_ that can be used for all the methods and documented individually. There will never be undocumented options, because to prevent a compile-time error that option has to be defined and then it will also appear in the docs.
 - Supports `async`/`await`
 - TypeScript is a superset of JavaScript. Every JS code is already valid TS code. The learning curve is very little, it's just JS with typing on top
 - The type system is extremely flexible, even the association mixins can be modeled

What do you think?

**Comment by janmeier** [comment]
While I definitely see the merits of more magic documentation, and making it easier for typescript users to use sequelize, we have opted not to have a transpilation step in 4.0 - neither babel nor typescript.

The reasoning is two-fold - for one, it creates a lower barrier of entry for new developers, they don't have to learn new syntax (I know typescript is a superset, so they could still write in plain JS, but they would still have to understand existing ts code). Secondly, we want to make it possible users to install directly from git (i.e. poiniting their package.json file directly at a specific commit) - which is not possible if we have a transpilation step.

**Comment by felixfbecker** [comment]
@janmeier Good reasoning.

**Comment by SimonSchick** [comment]
@janmeier Is this up for consideration for v5?

**Comment by janmeier** [comment]
@SimonSchick I'm not actively involved in the development anymore, but I doubt it. @sequelize/orm

**Comment by sushantdhiman** [comment]
I'll prefer vanilla, we may align with Node's LTS version to access more features and drop Node 4

**Comment by SimonSchick** [comment]
We've been using sequelize with typescript for a couple of months now and the productively gain is just insane as we don't have to look through the docs every 5 minutes (among other things).

I'd argue that sequelize is probably one of the richest and most complex node packages I'm sure a lot of users would benefit from it being moved to TS, or at least being shipped with official typings.

Would you at least consider the latter?

**Comment by SimonSchick** [comment]
@sushantdhiman any comments?

I really believe that adding typings from https://github.com/types/sequelize/commits/master is going to significantly help consumers of this library with relatively little development overhead.

**Comment by sushantdhiman** [comment]
@SimonSchick what would be the difference of including typing from `@types/sequelize` to say to officially maintained `@sequelize/types`?

If its more updated types and covering full API surface then I dont have enough experience, interest and time for maintain those types.

Another issue I see is that sometimes certain API is difficult to type (again I am no expert but I remember case of `BelongsToMany.through`). I certainly want to keep API simple and typable, but wont block a feature/fix because API cant be typed

**Comment by SimonSchick** [comment]
The main difference would be that the typings are always (or almost always) completely up to date with the sequelize implementation.

In 99% of the cases adding new types is also really trivial, I've not seen any recent changes (ignoring v4) that require complex typings.

I do agree that some of the current API is difficult to type, especially the magic association functions that are added on the fly, but ~95% of the sequelize API is relatively trivial to define in typescript, when in doubt you can always `any` that and let a contributor deal with it, worst case you have the same type safety as using JS.

It also should be noted that `@types/sequelize` **doesn't play well with v4** as they do not have any class definitions.
https://github.com/types/sequelize/commits/master are the de-facto v4 typings (however they conflict with the typings of `umzug` as these depend of `@types`).
I've seen numerous people trying to use `@types/sequelize` with v4 which lead to really confusing results at times.

**Comment by 3-harish-3** [comment]
good discussion,
