### ISSUE TITLE
Why aren't unique indexes in options.indexes added into uniqueKeys of model? 

### ISSUE THREAD

**Issue by daleoooo** [sequelize/sequelize#5942]
## Problem:

When I define a model like this:

``` js
var User = sequelize.define('user', {
  username: {
    type: Sequelize.STRING,
    unique: true
  }
});
```

unique index defined above will be added into uniqueKeys prop of user model, but when I define user like below:

``` js
var User = sequelize.define('user', {
  username: Sequelize.STRING,
}, {
  indexes: [{
    unique: true,
    fields: ['username']
  }]
});
```

unique index will not be added into uniqueKeys whether user.sync is called or not. 

It is ok when I just need the UniqueConstraintError. But if I want to know the error fields which is returned with UniqueConstraintError object, I would be stuck. This is because UniqueConstraintError's fields prop depends on uniqueKeys of model.
## Expect:

Add options.indexes to uniqueKeys when model.refreshAttributes() is called.

BTW, I use sequelize 3.23.2(which is latest version in npm).

Thanks

**Comment by janmeier** [comment]
Actually I think it should rather be the other way around - that unique constraints are added to `options.indexes`

**Comment by daleooo** [comment]
Yep, it's good. Add unique indexes into options.indexes and make unique indexes in uniqueKeys, attributes, and options.indexes consist with each other. Or adding all indexes into options.indexes and changing some code in function which throw unique constraint error solve this problem either. In the later way, uniqueKeys is redundant. Can I think like this way?

**Comment by skn3** [comment]
I have just encountered this issue as well. Possible to reopen?

**Comment by skn3** [comment]
Currently I am doing this to get a list of sets of fields to do some unique checking.
```javascript
const indexes = [].concat(this.options.indexes.map(index => index.fields), Object.values(this.options.uniqueKeys).map(uniqueKey => uniqueKey.fields));
```
