### ISSUE TITLE
upsert return row 

### ISSUE THREAD

**Issue by miguelslemos** [sequelize/sequelize#5949]
## What you are doing?
insert or update a user 

```js
models.User.upsert(data.body);
```

## What do you expect to happen?
return all attributes from model or another way return model when insert or update 

## What is actually happening?
when the user already exist upsert return true or false

 output: JSON

__Dialect:__ mysql
__Sequelize version:__ 3.23.2

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2054
