### ISSUE TITLE
Nested objects orderring of Polymorphic Association

### ISSUE THREAD

**Issue by gztchan** [sequelize/sequelize#5950]
**Defining Relationship**

1. User hasMany UserContent
2. UserContent hasMany Item
3. UserContent hasMany Post
4. Item hasMany ItemImage

```js
scopes: {
	'content': function () {
		include: [
			{ model: sequelize.models.Post, as: 'posts'},
			{ 
				model: sequelize.models.Item, 
				as: 'items',
				include: [
					{ model: sequelize.models.ItemImage, as: 'itemImages' }
				],
				order: [
					[ { model: sequelize.models.ItemImage }, 'created_at', 'desc' ]
				]
			}
		],
		order: [
			['created_at', 'desc']
		]
  	}
}
```

So i start to get UserContents, but **item_images in item are not ordered by created_at**

```js
user.getUserContent({
	scope: ['content']
})
```

What i expect is:

```js
[
	// this is item object
	{
		"id": 'xxxx',
		"item_images": [
			// images should be ordered
			{
				"created_at": '{timestamp here}' 
			},
			{
				"created_at": '{timestamp here}'
			}
		]
	},
	// this is post object
	{
		"id": 'xxxx',
		"content": 'xxxxx'
	}
]
```

Can you tell me how to order nested objects of Polymorphic Association?

**Comment by mickhansen** [comment]
`include` does not support order unless you using `separate: true`

**Comment by gztchan** [comment]
@mickhansen Can you provide an example or URL for me to take reference ?

**Comment by gztchan** [comment]
```js
separate: true,
include: [
  {
    model: sequelize.models.Post,
    as: 'post'
  },
  {
    model: sequelize.models.Item,
    as: 'item',
    include: [
      { model: sequelize.models.ItemImage, as: 'itemImages' }
    ],
    order: [
      [
        { model: sequelize.models.ItemImage }, 'position', 'ASC'
      ]
    ]
  }
]
```

It still doesn't work.

**Comment by mickhansen** [comment]
http://docs.sequelizejs.com/en/latest/docs/querying/#ordering

**Comment by mickhansen** [comment]
`separate` needs to be on each individual include statement - it tells sequelize that you want to run it in a seperate query.

**Comment by gztchan** [comment]
Solved!! Just posing my solution for guys who will face the same problem.

```js
include: [
  {
    model: sequelize.models.Post,
    as: 'post'
  },
  {
    model: sequelize.models.Item,
    as: 'item',
    include: [
      { 
      	model: sequelize.models.ItemImage, 
      	as: 'itemImages', 
      	// -- set separate true
      	separate: true,
      	order: [
      		['created_at', 'ASC']
      	]
      }
   	]
  }
]
```

@mickhansen thank you!

By the way, does sequelize has solution to separate "not has many" **include** ? When model include many other models, the query string will be large because of left join, which make response takes much more time to return.

**Comment by mickhansen** [comment]
@gztchan We're working on supporting seperate for all includes.
