### ISSUE TITLE
Group By is not ignored in findAndCountAll

### ISSUE THREAD

**Issue by SohaibFarooqi** [sequelize/sequelize#5952]
I was trying findAndCountAll method to count the number of rows with offset and limit. Count query is as follows:
```SELECT count(DISTINCT(`agent`.`agentid`)) AS `count` FROM `byt_agents` AS `agent` INNER JOIN (`byt_agents_cat` AS `categories.agent_category` INNER JOIN `byt_category` AS `categories` ON `categories`.`cat_id` = `categories.agent_category`.`cat_id`) ON `agent`.`agentid` = `categories.agent_category`.`agentid`  WHERE `agent`.`agent_status` IN ('on', 'edited') GROUP BY `agent`.`agentid```

I get array of objects in count [...{count: 1} , {count: 1}...] due to group statement in query. 

I saw the code model.js where ```'offset', 'limit', 'order', 'attributes'``` are being ignored when calculating count. Is there a way to ignore GROUP as well from count?

**Comment by sushantdhiman** [comment]
- `offset`, `limit` are removed because we want full count
- `attributes` and `order` removed because they wont make any difference when counting
- `group` is not removed because it can produce different set of records. If you dont want to group, dont include it in your `where` conditions

**Comment by sushantdhiman** [comment]
Duplicate #6148 , Issue is real. Will fix soon @SohaibFarooqi
