### ISSUE TITLE
`initialAutoIncrement` for postgres?

### ISSUE THREAD

**Issue by WestleyArgentum** [sequelize/sequelize#5954]
When creating a model there's an `[options.initialAutoIncrement]` argument which seems to only support MySQL. Could that be extended to support Postgres?

I'm in a situation where I want to have `autoIncrement` id keys, but I also need to create fixtures and relationships between them. When I'm creating fixtures, I manually specify ids (so that I don't have to depend too much on order and assumptions that may turn out to be wrong). But when I go to create instances without specifying ids later, I get collisions with the ids from the fixtures.

I'd like to be able to set `initialAutoIncrement` to something like `1000` so that I can create plenty of fixtures with manually chosen ids without running into trouble...

**Comment by mickhansen** [comment]
https://www.postgresql.org/docs/9.1/static/sql-altersequence.html

**Comment by WestleyArgentum** [comment]
Thanks for that, I'm using `alter sequence` now. Should I leave this issue open as a feature request -- to extend sequelize `[options.initialAutoIncrement]` to generate `alter sequence` code that will work for postgres?

**Comment by mickhansen** [comment]
We can do that, i'm not sure it will ever be implemented actually, i have to look into if the MySQL code could be removed in 4.0 (if there's an alternative)

**Comment by felixfbecker** [comment]
For postgres, this should rather sit on the attribute object, because you can have multiple sequences in a table.

**Comment by felixfbecker** [comment]
What is the correct workaround for now? Using a `afterBulkSync` hook? Should I set `START WITH` or `MINVALUE`?

**Comment by Ankit-Salvi** [comment]
What is the workaround for initialAutoIncrement in Postgres?Any suggestions on this?

**Comment by fzn0x** [comment]
> What is the workaround for initialAutoIncrement in Postgres?Any suggestions on this?

You can't declare initial auto increment like MySQL (`AUTO_INCREMENT=${options.initialAutoIncrement}`) in PostgreSQL, the current workaround is to create sequence and modify it or alter the existing sequence. There's no support for `initialAutoIncrement` in PostgreSQL for now in Sequelize.

```sql
# create sequence
CREATE SEQUENCE user_id_seq
  START 1234 # important
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1;
# assign sequence to root user
ALTER TABLE user_id_seq
  OWNER TO postgres;
# assign to table 
ALTER TABLE users ALTER COLUMN user_id SET DEFAULT nextval('user_id_seq'::regclass);

# or...
# alter the existing sequence (use with caution)
ALTER SEQUENCE user_id_seq RESTART WITH 1453;
```

Setting AUTO_INCREMENT isn't part of the SQL standard, it's specific to MySQL.
