### ISSUE TITLE
ER_DATA_TOO_LONG shows in Mac but not in Ubuntu VM

### ISSUE THREAD

**Issue by miparnisari** [sequelize/sequelize#5955]
## What you are doing?

```js
var crypto = require('crypto');
var q = require('q');

module.exports = function(sequelize, Sequelize) {

	var User = sequelize.define('User', 
	{
	  passcode  : Sequelize.STRING(128),
	},
	{
	  instanceMethods: {
		setPasscode: function(newPasscode){
		  var def = q.defer();
		  var that = this;
		  var pass = new Buffer(newPasscode, 'base64');
		  var salt = new Buffer(that.id.toString(), 'base64');

		  crypto.pbkdf2(pass, salt, 1000, 128, function(err, res){
			  if(err) def.reject(err);
			  that.passcode = res.toString('base64'); // this may be >128 chars long
			  that.save() // but this doesn't throw any errors
				.then(function(u) { def.resolve(u); });
			});
		  return def.promise;
		}
	  }
	});

	return User;
}
```

## What do you expect to happen?
When running `user.setPasscode('1234')` I expected an error to be thrown because the transformed passcode is bigger than 128 chars after converting it to base64.

## What is actually happening?
Running this code in an Ubuntu VM hosted in Windows, no errors are thrown and the field is saved cut off. On Mac, an error is shown: `Unhandled rejection SequelizeDatabaseError: ER_DATA_TOO_LONG: Data too long for column 'passcode' at row `

__Dialect:__ mysql, charset: 'utf8mb4'
__Database version:__ not sure how to check
__Sequelize version:__ ^2.0.3

**Comment by mickhansen** [comment]
Sounds like MySQL is configured with different defaults between the two OS'es.
Not related to Sequelize since it's a dialect data type issue (you could try enabling type validations though).
