### ISSUE TITLE
cannot add comment to attribute in table

### ISSUE THREAD

**Issue by kangho99** [sequelize/sequelize#5962]
## What you are doing?

I'm trying to add some comments to each attribute.
{
    customer_id: {type: DataTypes.TEXT, allowNull: false, comment:  "some comment1"},
    customer_name: {type: DataTypes.TEXT, allowNull: false, comment: "some comment2"},
    customer_email: {type: DataTypes.TEXT, allowNull: false, validate: {isEmail: true}, comment: "some comment3"},
    ...
}

## What do you expect to happen?
I think adding the comment field as above should add additional queries like
'alter table blah comment on column customer_id is  "some comment1"' 
but all I get is 'create table ...' query, without comments on attributes.

## What is actually happening?
no alter query, no comment added.

__Dialect:__ postgres
__Database version:__ 9.4.5
__Sequelize version:__ tested with 3.18.0 and 3.23.2

I'll try to look into it on my free time.

btw thanks for great orm with pg support!

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/4386
