### ISSUE TITLE
Switch from JSHint to ESLint

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#5963]
ESLint has much better support and way more rules. There is a CLI tool for converting JSHint configs to ESLint, I already tried it out on Sequelize and ESLint caught a whole more errors. For example, JSHint doesn't seem to catch indentation errors. There were a lot of errors in the code like `expected indentation of 4 characters but found 3` that break indentation-based code collapsing in editors.

Would do PR

**Comment by mickhansen** [comment]
Sounds good to me.
