### ISSUE TITLE
connectionLock.unwrap is not a function

### ISSUE THREAD

**Issue by djorg83** [sequelize/sequelize#5964]
```js
connect() {
	this.sequelizeConnection = new Sequelize(this.sqlConfig.dbName, this.sqlConfig.username, this.sqlConfig.password, {
	        host: this.sqlConfig.ip,
	        dialect: 'mssql',
	        pool: {
	            max: 5,
	            min: 1,
	            idle: 10000
	        },
	        dialectOptions: {
	            encrypt: true,
	            requestTimeout: 0,
	            connectTimeout: 0
	        }
	    });

    	this.defineModels();
}
```

## What do you expect to happen?
I expect this to maintain a connection pool of 1 to 5 connections.

## What is actually happening?
This unhandled exception is causing my server to crash.  I am on version 3.23.0.  This happens after roughly 12 hours of uptime.

[0] ..\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:127
[0]   var connection = connectionLock.unwrap();
[0]                                   ^
[0]
[0] TypeError: connectionLock.unwrap is not a function
[0]     at ConnectionManager.disconnect (..\node_modules\sequelize\lib\dialects\mssql\connection-manager.j
s:127:35)
[0]     at ConnectionManager.$disconnect (..\node_modules\sequelize\lib\dialects\abstract\connection-manag
er.js:253:41)
[0]     at Object.ConnectionManager.initPools.pool.Pooling.Pool.destroy (..\node_modules\sequelize\lib\dia
lects\abstract\connection-manager.js:99:14)
[0]     at Pool.destroy (..\node_modules\sequelize\node_modules\generic-pool\lib\generic-pool.js:193:17)
[0]     at Connection.<anonymous> (..\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:118:
21)
[0]     at emitOne (events.js:77:13)
[0]     at Connection.emit (events.js:169:7)
[0]     at Connection.socketError (C:\dev\git\rsp-client\node_modules\tedious\lib\connection.js:795:12)
[0]     at Socket.bind (..\node_modules\tedious\lib\connection.js:33:15)
[0]     at emitOne (events.js:82:20)
[0]     at Socket.emit (events.js:169:7)
[0]     at emitErrorNT (net.js:1250:8)
[0]     at doNTCallback2 (node.js:429:9)
[0]     at process._tickCallback (node.js:343:17)

Dialect: mssql 
Database version: 
Sequelize version: 3.23.0

**Comment by djorg83** [comment]
This happened again after less than an hour of uptime.

**Comment by djorg83** [comment]
```js
ConnectionManager.prototype.disconnect = function(connectionLock) {
  var connection = connectionLock.unwrap();

  // Dont disconnect a connection that is already disconnected
  if (!!connection.closed) {
    return Promise.resolve();
  }

  return new Promise(function (resolve, reject) {
    connection.on('end', resolve);
    connection.close();
  });
};

ConnectionManager.prototype.validate = function(connectionLock) {
  var connection = connectionLock.unwrap();

  return connection && connection.loggedIn;
};
```

It looks to caused by the recent refactoring of ConnectionManager.disconnect and .validate to take in a connectionLock and try to unwrap it instead of taking a connection as an argument.

**Comment by djorg83** [comment]
I'm reverting to version 3.11.0 (our previous stable version) until this is fixed.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/5752
@kjvalencik

**Comment by kjvalencik** [comment]
@djorg83  Your stack trace shows that it was in the disconnect phase when it occurred. Is that what your other stack traces show as well?

**Comment by djorg83** [comment]
Yes.  Same thing in all stack traces.  I'm trying updating the tedious library to the latest version to see if that makes a difference.

**Comment by kjvalencik** [comment]
It suggests that one of the code paths to `.disconnect` is *not* passing the connect stored in the pool but an already unwrapped connection. I haven't found that code path yet.

**Comment by kjvalencik** [comment]
I see the problem, it's on the disconnect handling. I'll have a PR up shortly to fix.

**Comment by shilu911** [comment]
@kjvalencik I am using 4.22.5 and still have this issue. This happens after about 20 hours of uptime.

**Comment by SteveyPugs** [comment]
I am still having this issue as well. 48 hours in the process just stalls, no response whatsoever.

**Comment by kjvalencik** [comment]
I have not observed this. Are you able to provide any more of a stack trace? For example is this coming from the `validate` method or `disconnect`?

**Comment by SteveyPugs** [comment]
Nope. I get back no error message. It started as deadlocks on 3.18.x, then this on 3.23.x. I’ve upgraded to 3.33.x to see if it fixed this issue.

We use SQL server 2008.

**Comment by funkydev** [comment]
Hi guys. I have the same issue.

It happens after `SequelizeDatabaseError: Connection closed before request completed.` error.

So to reproduce this case you need close connection before request completed (eg. using webstorm debbuger). Then every request will fail with `TypeError: connectionLock.unwrap is not a function`.

I'm using `sequelize v.4.27.0` with `tedious v.2.2.0`

**Comment by kjvalencik** [comment]
Looking through the code. I can't quite figure out how it's getting a type that's not a `ResourceLock`. The simple--but, not great--option is to put an `if` guard around that `unwrap` in `validate`.

**Comment by funkydev** [comment]
I have updated sequelize lib and for now I can't reproduce my case. Probably changes related with #9037 have fixed my issue. 

Thanks for timing!
