### ISSUE TITLE
Error when use momentjs in where part of update statement

### ISSUE THREAD

**Issue by bobahvas** [sequelize/sequelize#5966]
__Dialect:__ mysql
__Database version:__ 5.5.49
__Sequelize version:__ 3.23.2

"moment": "^2.12.0"
"sequelize": "^3.23.2"

TypeError: val.replace is not a function
```js
return models.Task.update({
    status: 'success'
}, {
    where: {
        status: 'working',
        updated_at: {
            $lt: moment()
        }
    }
});
```

But I can use
```js
return models.Task.find({
    where: {
        updated_at: {
            $lt: moment()
        }
    }
});
```

**Comment by mickhansen** [comment]
Does it work with `moment().toDate()`? moment is not an official supported input type.

**Comment by bobahvas** [comment]
Yes, it works. Thanks for reply.
Also we can use `moment().toISOString()` if need UTC. Sequelize work with it well.
