### ISSUE TITLE
setAssociations mixin of hasMany relationship doesn't save new dependent models

### ISSUE THREAD

**Issue by JustBlackBird** [sequelize/sequelize#5969]
I'm trying to use `setAssociations` mixin for hasMany relation but with no success. Here is my code:

```js
var User = sequelize.define('user', {name: Sequelize.STRING}),
    Post = sequelize.define('post', {title: Sequelize.STRING});

User.hasMany(Post);
Post.belongsTo(User, {
    as: 'Owner',
    onDelete: 'CASCADE',
    foreignKey: {
        // A Post has no meaning without an owner. 
        allowNull: false
    }
});

sequelize.sync({force: true}).then(function() {
    return User.create({name: 'jane'});
}).then(function(user) {
    return user.setPosts([Post.build({title: 'foo'})]);
}).then(function() {
    return Post.count();
}).then(function(c) {
    console.log('There is ' + c + ' post in the database');
})
```

I expect that the post is inserted into the database and the console shows me:

> There is 1 post in the database

Unfortunately, the post is not created and the console shows me:

> There is 0 post in the database

I've checked `posts` table in database and it's empty.

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.23.2

**Comment by mickhansen** [comment]
`setPosts` operate on persisted instances, use `createPost` if you're working with values.

**Comment by JustBlackBird** [comment]
There is no clean way to persist dependent entities when foreign key is not nullable (just like in the example above). The only option is to set this key manually, but it's just a dirty workaround. I don't think it's a way how relations should work. `createAssociation` does not support bulk creation, so I have to run as many queries as many instances I have.

The only thing i suggest is alter `setAssociations` behavior to bulk save all new dependent models on call.

**Comment by mickhansen** [comment]
setAssociations should be as atomic as possible, so we prefer it this way.
It's better if createAssociations could a bulk capable sister.

createAssociation handles non-nullable foreign keys or you could look at doing nested creates.

**Comment by JustBlackBird** [comment]
Correct me if I wrong, there is no `createAssociations` method.

Also can `createAssociation` deal with models created with build?

**Comment by mickhansen** [comment]
Correct, i'm suggesting you implement it.
`createAssociation` accepts POJOs

**Comment by JustBlackBird** [comment]
Ok, thanks for the clarification.
