### ISSUE TITLE
Sequelize model inheritance implementation?

### ISSUE THREAD

**Issue by jamesone** [sequelize/sequelize#5970]
I came across this wiki:
https://github.com/sequelize/sequelize/wiki/Suggestion-for-Inheritance-API
And was wondering if something like this has, or will be implemented?

**Comment by janmeier** [comment]
See https://github.com/sequelize/sequelize/pull/5757, https://github.com/sequelize/sequelize/issues/1679 and https://github.com/sequelize/sequelize/issues/1243
