### ISSUE TITLE
validate dosen't work 

### ISSUE THREAD

**Issue by dahuahe** [sequelize/sequelize#5971]
_Thanks for wanting to report an issue you've found in Sequelize. Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_Note that it will be much easier for us to fix the issue if a test case that reproduces the problem is provided. Ideally this test case should not have any external dependencies. We understand that it is not always possible to reduce your code to a small test case, but we would appreciate to have as much data as possible. Thank you!_

_Github should only be used for feature requests and bugs - all questions belong on StackOverflow, Slack, or Google groups._

_This template is for submitting issues - if you want to submit a feature request you may skip this template_

## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_

```js
var test=sequelize.define("test",{
    Id:{type:  Sequelize.INTEGER,
        allowNull: false,
        primaryKey: true,
        autoIncrement:true},
    user:{
        type:Sequelize.INTEGER,
        validate: {
            ismin: function (val) {
                if (val < 0) {
                    throw new Error("不能小于零")
                }
            }
        }
    }
},{tableName:"test"})

test.daochuqu.find({where: {Id: 1}}).then(function (user) {
      if(user.user-5<0){
        res.send("<script>alert('ENDING')</script>")
      }else{
          user.decrement("user",{by:5}).then(function(users){
              users.reload();
           res.status(200).json({data:"SUCCESSFUL" })
       }).catch(function(err){res.status(404).json({data:err })})
      }
 })
  })
```

## What do you expect to happen?
when user=0   res.send("<script>alert(' ENDING')</script>") and vilidate do work
## What is actually happening?
_But the output was bar!_
Ask too much! user may be -5 or -10,
i find when insance.decrement validate's function ismin(){} dosen't work
_Output, either JSON or SQL_

__Dialect:__ mysql
__Database version:__ XXX
__Sequelize version:__ XXX

**Comment by janmeier** [comment]
* There is no `ismin` validation - http://docs.sequelizejs.com/en/latest/docs/models-definition/#validations
* As stated in the docs, decrement happens in the DB (`SET X = X - Y`), we don't calculate the new value in sequelize. So there is no way to validate the value. http://docs.sequelizejs.com/en/latest/api/instance/#decrementfields-options-promise

**Comment by dahuahe** [comment]
ismin is my validate function 
var test=sequelize.define("test",{
    Id:{type:  Sequelize.INTEGER,
        allowNull: false,
        primaryKey: true,
        autoIncrement:true},
    user:{
        type:Sequelize.INTEGER,
        validate: {
            ismin: function (val) {//there
                if (val < 0) {
                    throw new Error("不能小于零")
                }
            }
        }
    }
},{tableName:"test"})
When the concurrency value is very big, if the value = 100 value each request subtract 5 how to ensure the value cannot be less than zero, not negative

**Comment by janmeier** [comment]
You'll have to load the value in a transaction and update the model manually - That way validations are run. Or you could add a `CHECK` constraint in the DB

**Comment by dahuahe** [comment]
@janmeier  Thank you for your timely answer,sequelize provide the DB check definition? I tried to use transaction if transaction affairs need to lock? Otherwise the request more, transaction can open a lot

**Comment by janmeier** [comment]
No, we do not provide db checks. You don't need to lock, but you need to handle serialization errors (multiple transactions that tried to update the count

**Comment by dahuahe** [comment]
Thank you very much,sequelize Is very nice,What you said'transactions  is sequelize transactions? i know sequelize's transactions a little,Thank you  i will Continue to learn   sequelize's transactions
