### ISSUE TITLE
Proposal: Include "Isolate" Options

### ISSUE THREAD

**Issue by cbauerme** [sequelize/sequelize#5976]
In the case of nested includes there is no way to "protect" an outer include from a more-inner one being `required`. By adding an `isolate` option to include the effects of a required include can be prevented from bubbling up. 

Example:

(see the full example here  https://github.com/cbauerme/sequelize-isolate-include-example)

I have created the following models and assocations
``` js
var User = sequelize.define('user', {
    name: { type: Sequelize.STRING, allowNull: false },
});

var Group = sequelize.define('group', {
    groupName: { type: Sequelize.STRING, allowNull: false },
});

var Budget = sequelize.define('budget', {
    balance: { type: Sequelize.FLOAT, allowNull: false },
});

User.belongsTo(Group, { as: 'group' });
Budget.belongsTo(Group, { as: 'group' });
Group.hasMany(User, { as: 'users' });
Group.hasOne(Budget, { as: 'budget' });
```
And filled them with 

```js
Group.create({
    groupName: 'Group A',
     users: [
         { name: 'Alice' },
         { name: 'Bob' }
    ],
    budget: {
        balance: 34.58
    }
});
Group.create({
    groupName: 'Group B',
    users: [
        { name: 'Hannah' },
        { name: 'Ed' }
    ],
});
```

Finally I have an unique report to write. I want to select all users. I also want the group only for the cases where the group has a budget.

```js
return User.findAll({
        include: [
            {
                model: Group,
                as: 'group',
                required: false,
                include: [
                    {
                        model: Budget,
                        as: 'budget',
                        required: true,
                    }
                ]
            }
        ]
    });
```

Unfortunately this find will only return "Alice" and "Bob". With my proposal

```js
return User.findAll({
        include: [
            {
                model: Group,
                as: 'group',
                required: false,
                isolate: true,
                include: [
                    {
                        model: Budget,
                        as: 'budget',
                        required: true,
                    }
                ]
            }
        ]
    })
```
We would get all four users, but only Bob & Alice would also have their associated groups.

**Comment by mickhansen** [comment]
I understand the issue, but there should be no need for a separate option.

A grand-child having required: true should not override a child with required: false (as upposed to undefined which should be bubbled).

**Comment by cbauerme** [comment]
I can't seem to get that behavior on the example I linked. Is there some other mistake I am making?

**Comment by mickhansen** [comment]
@cbauerme should as in doesn't happen at the moment but it should, as in a bug, but a subtle BC break aswell so something we want for 4.0

**Comment by cbauerme** [comment]
Ah, gotcha! I will get this out of the way, then.

**Comment by mickhansen** [comment]
@cbauerme please open a bug report for child being overwritten by grand child
