### ISSUE TITLE
Valid username/password characters break URL connection

### ISSUE THREAD

**Issue by jonathanboswell** [sequelize/sequelize#5978]
Special URL characters which are valid Postgres password characters will cause the Sequelize constructor to fail when a URL is passed in.

For example:
```js
var sequelize = new Sequelize("postgres://dbadmin:passChar?or#21@website.us-west-2.rds.amazonaws.com/dbName",{ssl:true,logging:false});
```
This will have various impacts depending on where the ? or the # fall, but most common seemed to be a connection timeout error - which can lead one into thinking it is an SSL connection error (see #956)

Using the latest Sequelize (3.23.2) it is url.parse() on line 125 of sequelize.js that chokes. Wrote a validation that looks to raise the error:
```js
if(/^[^@]*[\?#].*@/.test(arguments[0])) throw new sequelizeErrors.ValidationError('Unable to pass connection as a URL because username/password contain special characters.');
var urlParts = url.parse(arguments[0]);
```

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.23.2

**Comment by MichaelBuhler** [comment]
Looks like URL/URI percent encoding might be a workaround for this!

https://en.wikipedia.org/wiki/Percent-encoding

```
> require('url').parse('postgres://dbadmin:passChar%3For%2321@website.us-west-2.rds.amazonaws.com/dbName');
Url {
  protocol: 'postgres:',
  slashes: true,
  auth: 'dbadmin:passChar?or#21',
  host: 'website.us-west-2.rds.amazonaws.com',
  port: null,
  hostname: 'website.us-west-2.rds.amazonaws.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/dbName',
  path: '/dbName',
  href: 'postgres://dbadmin:passChar%3For%2321@website.us-west-2.rds.amazonaws.com/dbName' }
>
 ```

**Comment by janmeier** [comment]
Ah yes, that makes sense - Since its a connection _url_ you should of course make sure to URL encode it! :) Thanks @MichaelBuhler
