### ISSUE TITLE
Adding logs for connection create / destroy

### ISSUE THREAD

**Issue by foobar8675** [sequelize/sequelize#5980]
i think it would handy if when logging is turned on, it would also log when db connections are created and destroyed. i'm trying to troubleshoot some performance issues and would like to eliminate or at least benchmark how long it takes for the the connection of a new db connection

**Comment by mickhansen** [comment]
Instrumentation support would probably be better than logging

**Comment by foobar8675** [comment]
Thanks for writing @mickhansen . Can you elaborate on what you mean by Instrumentation support?

**Comment by mickhansen** [comment]
instrumentation support would be to implement code that allows any user to add tracing / timing around pretty much any operation inside the sequelize codebase, to identify bottlenecks etc.
