### ISSUE TITLE
Range DataType's default bound inclusion inconsistent with postgres

### ISSUE THREAD

**Issue by alitaheri** [sequelize/sequelize#5983]
The default bounds for range types are [exclusive, exclusive] while postgres's defaults are [inclusive, exclusive], see [here](https://www.postgresql.org/docs/9.5/static/rangetypes.html#RANGETYPES-CONSTRUCT). 

## What are you doing?

```js
Timeline.create({range: [new Date(2016, 5, 1), new Date(2016, 6, 1)]});
```

## What do you expect to happen?
```
'["2016-06-01 00:00:00.000 +00:00","2016-07-01 00:00:00.000 +00:00")'
```

## What is actually happening?
```
'("2016-06-01 00:00:00.000 +00:00","2016-07-01 00:00:00.000 +00:00")'
```

## Solution

Fixing it is just a [single line of code](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/range.js#L38). But it's a silent and somehow dangerous breaking change. It's ok if it's added to 4.0 but before submitting a PR, fixing the code, updating docs and tests (also there really aren't any docs on the usage, I will write them with the PR) i wanted to be sure everyone agrees with the change.

__Dialect:__ postgres
__Database version:__ any
__Sequelize version:__ any

**Comment by janmeier** [comment]
Well if the postgres default is inclusive, exclusive I think we should follow that - And more docs are always welcome! :)

**Comment by alitaheri** [comment]
Ok, Thanks :smile:
