### ISSUE TITLE
Add Support for HANA Dialect

### ISSUE THREAD

**Issue by vpmenon** [sequelize/sequelize#5984]
HANA Has a nodejs Driver Implementation. Also a small time ORM like feature called CDS. Adding a dialect for HANA which is a growing DataBase in the industry would be great

**Comment by janmeier** [comment]
Personally, I've never heard about HANA - For us to support it, someone would have to volunteer to write __and maintain__ the code, and we would have to be able to test it on travis.

It might happen, but you'll probably have to do the work yourself :)

**Comment by vpmenon** [comment]
I can :P

**Comment by janmeier** [comment]
There's still the problem of testing it on travis - I'd rather not have to increase testing times by installing it locally in each test job - So someone would have to sponsor some instances.

You are welcome to take a stab at it - You can ask @mbroadst (mssql) and @gintsgints (oracle) about their experiences with it :)

**Comment by dabadlia** [comment]
Hello @vipinvkmenon any update on this support. I could to contribute if there is any existing WIP on this topic.

**Comment by vipinvkmenon** [comment]
no... long left that world

**Comment by dabadlia** [comment]
Ok, thanks for your reply. Enjoy the new world :)
