### ISSUE TITLE
[BUG] Id injection in a group by query

### ISSUE THREAD

**Issue by sebay00** [sequelize/sequelize#5987]
## Id injection in a group by query

Hi there, 

I'm facing a problem when I'm querying with group by and a SUM aggregate.
Sequelize automatically added the id of my main Table, so my group by is not valid. 
`ER_WRONG_FIELD_WITH_GROUP`

``` js
    attributes: {
      include: [
        'userId',
        [ orm.fn('SUM', orm.col('tokens')), 'busyTokens' ]
      ],
      exclude: ['id']
    },
    include: [{
      attributes: [],
      model: orm.models.Game,
      as: 'game',
      where: { finished: false }
    }],
    group: ['userId']
  };
```

I wanted to count all my user points on all games still in process.
But Here's the query Sequelize's building:

``` sql
SELECT `Bet`.`id`, `Bet`.`tokens`, `Bet`.`createdAt`, `Bet`.`updatedAt`, `Bet`.`userId`, `Bet`.`gameId`, `Bet`.`userId`, SUM(`tokens`) AS `busyTokens` FROM `Bets` AS `Bet` INNER JOIN `Games` AS `game` ON `Bet`.`gameId` = `game`.`id` AND `game`.`finished` = false GROUP BY `userId`;
```

If i'm doing my query like this (with attributes array):

``` js
  const queryBet = {
  attributes: [
      'userId',
      [ orm.fn('SUM', orm.col('tokens')), 'busyTokens' ]
    ],
    include: [{
      attributes: [],
      model: orm.models.Game,
      as: 'game',
      where: { finished: false }
    }],
    group: ['userId']
  };
```

I'm getting this query:

``` sql
SELECT `Bet`.`id`, `Bet`.`userId`, SUM(`tokens`) AS `busyTokens` FROM `Bets` AS `Bet` INNER JOIN `Games` AS `game` ON `Bet`.`gameId` = `game`.`id` AND `game`.`finished` = false GROUP BY `userId`;
```

I'd like to get rid of the the `SELECT Bet.id` in order to have a valid query.

**Dialect:** mysql 5.7
**Sequelize** version: 4.0.0-0

**Comment by mickhansen** [comment]
We add the id to do deduplication (faster), but i guess we shouldn't in cases where `group` is in use.
@janmeier

**Comment by janmeier** [comment]
Hmm, no I guess not

**Comment by arnaudbesnier** [comment]
Hi guys,

I am facing the same problem and the Sequelize requests are invalid because of the injected `id`.
Do you have a workaround for this issue?

**Comment by arnaudbesnier** [comment]
@sebay00,

If you add the `raw: true` option, you prevent the primary key to be loaded in the query.
It is the best "workaround" I found.
