### ISSUE TITLE
Model.build: `include` option requires array of models, fails when provided object of models and their options

### ISSUE THREAD

**Issue by adrukh** [sequelize/sequelize#5988]
## What am I doing?
I am storing a serialised user object on my session, deserialising it when serving requests. When `build`-ing the ORM object from the serialised object, I am `include`-ing relevant models. This works ok when the related models are stated in an array, but fails when these models are mentioned in a more complex object.

```js
  // models definition
  models.User.hasMany(models.ApiKey);
  models.ApiKey.belongsTo(models.User);
  models.User.belongsToMany(models.Org, { through: models.OrgMembership });
  models.Org.belongsToMany(models.User, { through: models.OrgMembership });
```

## What I tried first and didn't work:
```js
  // the user object is a plain object with related instances
  // i.e., `user.ApiKeys` and `user.Orgs` exist and are valid
  models.User.build(user, {
    isNewRecord: false,
    include: [
      { model: models.ApiKey },
      { model: models.Org, through: models.OrgMembership },
    ],
  });
```
The code above generated the following error, similar to https://github.com/sequelize/sequelize/issues/2798:
```
Error: include all 'function (options) {
  return this.findAll(options);
}' is not valid - must be BelongsTo, HasOne, HasMany, One, Has, Many or All
```
## What worked well:
```js
  // the user object is a plain object with related instances
  // i.e., `user.ApiKeys` and `user.Orgs` exist and are valid
  models.User.build(user, {
    isNewRecord: false,
    include: [models.ApiKey, models.Org],
  });
```

Would appreciate a confirmation this is the right way to go, will create a PR for the documentation to make this visible.

__Dialect:__ postgres
__Database version:__ 9.5.2
__Sequelize version:__ 3.20.0

**Comment by janmeier** [comment]
The `through` argument on includes is used to add filters and attributes to the include - That's probably why its failing when you provide a model. 

Passing them as an array should be fine
