### ISSUE TITLE
Sequelize admin panel functionality?

### ISSUE THREAD

**Issue by jamesone** [sequelize/sequelize#5989]
I'm assuming you're all aware of djangos ORM, it has a pretty powerful admin panel. I was wondering if this has crossed anyones mind for Sequelize?

**Comment by sushantdhiman** [comment]
Django is a **web framework** thats why they provide admin panel to control the application. We are just an ORM library, doing this would be out of our scope.

**Comment by jamesone** [comment]
Ah Yeah. Fair enough, I guess someone could create a framework which integrates with sequelize.

Sent from Outlook




On Sat, May 28, 2016 at 9:00 PM -0700, "Sushant" <notifications@github.com> wrote:












Django is a web framework thats why they provide admin panel to control the application. We are just an ORM library, doing this would be out of our scope.

**Comment by kuzmenko1256** [comment]
done! :)
Admin Interface it is library for provide Admin UI on base Sequelize and Express.
https://github.com/admin-interface/admin-interface
