### ISSUE TITLE
Having problems searching by distance in Postgres with Postgis.

### ISSUE THREAD

**Issue by jamesone** [sequelize/sequelize#5995]
I've got a point datatype (location) which holds the location of a result. I'm wanting to find all results having, or where `distance  < 10` . Here is what I'm using:

```
results.findAll({
			attributes: [
				'description', 'location',
				[sequelize.literal('ST_Distance_Sphere(location, ST_MakePoint(-126.4,45.32))'), 'distance'],
			],
                       //include: [] I'll need to include some models, so using a raw query is not a good option
			where: sequelize.literal(`distance < 50000`),

```

The following would generate:

```sql
SELECT  
  "location", 
  ST_Distance_Sphere(location, ST_MakePoint(-126.4,45.32)) AS "distance" 
FROM "results" AS "results" WHERE distance < 10;
```

I've looked around and it seems though this is not a valid postgres sql query. It seems as though a sub query would need to be generated, like in the following example (found here: http://stackoverflow.com/questions/32730296/referring-to-a-select-aggregate-column-alias-in-the-having-clause-in-postgres)
```
select
  c
from (
  select 
    sum(clicks) c
  from table
  where event_date >= '1999-01-01'
  group by keyword_id 
) x
where c > 10;
```

Is there another way I could search `where` a literal value is `< X` ?

**Comment by janmeier** [comment]
```js
where: sequelize.where(sequelize.literal('ST_Distance_Sphere(location, ST_MakePoint(-126.4,45.32))'), { lt: 10 })
```
` .where` is for cases where the key cannot be expressed simply (an object etc.)

**Comment by janmeier** [comment]
where can also be combined with others, e.g. `{ $and: [sequelize.where.., { id: 42] }`
