### ISSUE TITLE
Grandchild include `required` option overwriting child include `required`

### ISSUE THREAD

**Issue by cbauerme** [sequelize/sequelize#5999]
## What you are doing?
(see the full example here  https://github.com/cbauerme/sequelize-isolate-include-example)

I have created the following models and assocations
``` js
var User = sequelize.define('user', {
    name: { type: Sequelize.STRING, allowNull: false },
});

var Group = sequelize.define('group', {
    groupName: { type: Sequelize.STRING, allowNull: false },
});

var Budget = sequelize.define('budget', {
    balance: { type: Sequelize.FLOAT, allowNull: false },
});

User.belongsTo(Group, { as: 'group' });
Budget.belongsTo(Group, { as: 'group' });
Group.hasMany(User, { as: 'users' });
Group.hasOne(Budget, { as: 'budget' });
```
And filled them with 

```js
Group.create({
    groupName: 'Group A',
     users: [
         { name: 'Alice' },
         { name: 'Bob' }
    ],
    budget: {
        balance: 34.58
    }
});
Group.create({
    groupName: 'Group B',
    users: [
        { name: 'Hannah' },
        { name: 'Ed' }
    ],
});
```

Finally I have an unique report to write. I want to select all users. I also want the group only for the cases where the group has a budget.

```js
return User.findAll({
        include: [
            {
                model: Group,
                as: 'group',
                required: false,
                include: [
                    {
                        model: Budget,
                        as: 'budget',
                        required: true,
                    }
                ]
            }
        ]
}).then(function (users) {
    users.forEach(function (user) {
        console.log("User: " + user.name);
        if (user.group !== undefined) {
            console.log("   Group: " + user.group.groupName);
            console.log("   Budget: " + user.group.budget.balance);
        }
    });
});
```

## What do you expect to happen?
I want the following output (in no particular order)
```
User: Alice
   Group: Group A
   Budget: 34.58
User: Bob
   Group: Group A
   Budget: 34.58
User: Hannah
User: Ed
```

## What is actually happening?
```
User: Alice
   Group: Group A
   Budget: 34.58
User: Bob
   Group: Group A
   Budget: 34.58
```

__Dialect:__ sqlite (any?)
__Sequelize version:__ 3.4

**Comment by cbauerme** [comment]
I am willing to work on a fix for this, but I would like coordinate on a plan beforehand.

**Comment by mickhansen** [comment]
Not sure where this happens exactly, we detect children here: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L372 but i don't see that being transformed to required anywhere (yet)

**Comment by cbauerme** [comment]
Is the goal to make the parent or include a subQuery?

**Comment by sushantdhiman** [comment]
Yes

**Comment by mickhansen** [comment]
@cbauerme It's both needed for join type and for determining if we need the include to filter the main table via a subquery

**Comment by cbauerme** [comment]
In the specific case of my example the SQL we get is (roughly)
```sql
SELECT (stuff) FROM User LEFT OUTER JOIN Group INNER JOIN Budget
```
To solve this problem we need to isolate the `INNER JOIN` through a sub query like
```sql
SELECT (stuff) FROM User LEFT OUT JOIN ( SELECT (subset of stuff) FROM Group INNER JOIN Budget)
```
However it looks to me like we cannot put together a set of options from the model.js side of a find to get the second query to happen. Therefore we will need to go down to abstract/query-generator.js for this fix. Does that sound reasonable? Am I mistaken about needing to work from the query-generator side of things?

**Comment by cbauerme** [comment]
If a fix does require non-trivial work in query generator we could try a different structure for the SQL, like
```sql
SELECT (stuff) FROM User LEFT OUTER JOIN ( Group INNER JOIN Budget ON [condition] ) ON [outer condition]
```

**Comment by mickhansen** [comment]
@cbauerme All nested includes could be wrapped in a () by default i assume, shouldn't cause any issues and should work better with nested required

**Comment by cbauerme** [comment]
I have the bones of the solution [here](https://github.com/cbauerme/sequelize/tree/nested-required-fix), but I need to put everything back together and make some more tests. Do we want the behavior to be different if the child include specifically set `required` to false instead of just omitting it? [This line](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L520) prevents that from looking any different down in query-generator, but that would be pretty easy to fix.

**Comment by mickhansen** [comment]
@cbauerme A user defined required: false should always result in a left join

**Comment by cbauerme** [comment]
@mickhansen absolutely, but I am trying to figure out how to keep the current behavior.

`required: false` results in a nested left join
```js
modelA.findAll({
	include : [
		{
			model : modelB,
			required : false,
			include : [
				{
					model : modelC,
					required : true,
				}
			]

		}
	]
})
```
will give us this SQL
```sql
SELECT a.*, b.*, c.* FROM modelA AS a
LEFT OUTER JOIN ( modelB AS b INNER JOIN modelC AS c ON c.modelBId = b.id ) ON b.modelAId = a.id;
```
However, we might want to be able to get the old results as well
```js
modelA.findAll({
	include : [
		{
			model : modelB,
			include : [
				{
					model : modelC,
					required : true,
				}
			]

		}
	]
})
```
 ```sql
SELECT a.*, b.*, c.* FROM modelA AS a 
LEFT OUTER JOIN modelB AS b ON b.modelAId = a.id INNER JOIN modelC AS c ON c.modelBId = b.id;
```
Working as it does in the example makes sense to me, but it also seems a bit tricky to have an omitted option changing the result so much.

**Comment by mickhansen** [comment]
@cbauerme Currrently an undefined required with a required children will result in two INNER JOINS correct? Or does it result in what you just posted?

**Comment by cbauerme** [comment]
@mickhansen Currently an undefined required will fall back to `!!include.where`, so with a where it becomes two INNER JOINS and without a where it becomes a LEFT OUTER JOIN and an INNER JOIN.

**Comment by mickhansen** [comment]
@cbauerme No `include.where` and no `include.required` should be synonomous with `required: false` i think
