### ISSUE TITLE
Change structure returned by findX

### ISSUE THREAD

**Issue by furyscript** [sequelize/sequelize#6003]
I need to change structure returned when I use `findX`'s method like:
```javascript
User.findAll({ include: [{ model: Tool, as: 'Instruments' }] }).then(function(users) {
  console.log(JSON.stringify(users))

  // Actually
  /*
    [{
      "name": "John Doe",
      "id": 1,
      "created_at": "2013-03-20T20:31:45.000Z",
      "updated_at": "2013-03-20T20:31:45.000Z",
      "Instruments": [{
        "name": "Toothpick",
        "id": 1,
        "created_at": null,
        "updated_at": null,
        "user_id": 1
      }]
    }]
  */
  // What I wuold
  /*
    [{
      "name": "John Doe",
      "id": 1,
      "created_at": "2013-03-20T20:31:45.000Z",
      "updated_at": "2013-03-20T20:31:45.000Z",
      "instrument_name": "Toothpick",
      "instrument_id": 1,
      "instrument_created_at": null,
      "instrument_updated_at": null,
      "instrument_user_id": 1
      }]
    }]
  */
})
```

I prefered to not change it manually after result, but a feature of sequelize

**Comment by sushantdhiman** [comment]
You can write a parser code to achieve this using `lodash` very easily.

**Comment by furyscript** [comment]
@sunshinewyin can you give me an example for porting it?

**Comment by sushantdhiman** [comment]
Well I don't have the exact code but you can `map` the `Instrument` array to have keys append with `instrument` then call the `underscored` on each key. Finally `merging` the object to main object.

But in your case you are considering that `Instruments` will have only one entry. What will happen if it have two records?

**Comment by furyscript** [comment]
Usually I use `findOne` so it returns an object with only one elements.
I'd try with underscore for map object but it takes all property of record like `dataValues`, `_changed` and so on..

**Comment by sushantdhiman** [comment]
So you want to merge two models along with their `dataValues`, `_changed` ? As per you scheme there is no distinction between both models then. This will create confusion like calling `save`, which model it will refer to after merge?

**Comment by furyscript** [comment]
This work, but I not like it:
```
        var tmp = {}; 
        _.map(res.data.instrument.dataValues, function (value, key, object) {
            tmp["instrument_" + key] = value;
        });
        delete res.data.dataValues.instrument;
        res.data = _.extend(res.data.dataValues, tmp);
        return reply(res).code(200);
```

```

**Comment by sushantdhiman** [comment]
You can call `toJSON` method on `instance` received from `findOne`. This will only contain plain data, will be lot easy to work with and much cleaner. @furyscript

**Comment by sushantdhiman** [comment]
Although in `findAll` you have to call `toJSON` on each element ( instance ) in the results array

**Comment by furyscript** [comment]
Ok with `toJSON` I have only data, but always I need to map or something D: or manually create a new object ... @sushantdhiman

**Comment by sushantdhiman** [comment]
Yes you have to `map` as per you requirements. But yeah with `toJSON` we have only data, very clean to work with :)
