### ISSUE TITLE
Use leftJoin instead of innerJoin on hasOne relation

### ISSUE THREAD

**Issue by guidsen** [sequelize/sequelize#6004]
I have a `Person` model with an `hasOne` relation to a `Network`. But there is an use-case where the `Person` doesn't have a related `Network`. When using a `hasOne` relation with the query like this below

```
Person
    .findById(personId, {
      include: [
        { model: Network, where: { networkId } },
      ],
    });
```

Sequelize won't return the `Person` model but just a `null` value. But in this case the `Person` is found, only the related `Network` is not found.

So I expect the result to be like this:

- id: 1
- firstName: 'John'
- Network: null

Is this possible? Seems like Sequelize it using a inner join under the hood if I'm correct.

**Comment by mickhansen** [comment]
Use `required: false` if you want a left join while using `where`
