### ISSUE TITLE
Alias for include models

### ISSUE THREAD

**Issue by SohaibFarooqi** [sequelize/sequelize#6007]
Hi,
I want to use alias for include models. I have tried it with this:
```ModelA.hasMany(ModelB, {foreignKey: 'ABC'});```
```ModelB.belongsTo( ModelA, {as: 'XYZ' , foreignKey: 'ABC'});```
But this does't work.
I have tried to specify "as" in include model array like:
```model: models.ModelB,```
                        ```required: false,```
                      ```as: 'Model_ALIAS'```
                       ``` attributes:```
                                           ```[```
                                                   ```'id',```
                                                ``` 'selector',```
                                                ```[sequelize.fn('COUNT', sequelize.col('selector')), 'total_count']```
                                          ```  ],```
                        ```group: ['id'],``` 
                        ```order: "total_count DESC"```

But this throws an error that ModelB (Model_ALIAS) is not associated to ModelA. How can i define an alias to associated model so that all column prefix gets that alias like Model_ALIAS.`id`?

**Comment by mickhansen** [comment]
The relation and the include needs to use the same alias.
`hasMany(ModelB, {as: 'Model_ALIAS'}`

**Comment by mickhansen** [comment]
We allow multiple associations between the same models.

**Comment by anatolyzolotar** [comment]
@mickhansen 
Sorry, I have a similar problem (imo) and don't understand.
I have two models, for example: **Project** ----1:N---- **Task** and use complex query with join to get list of Projects with Tasks count for each ModelA row. I spent ton of time before I've figured out that if i define
```
Task.belongsTo(Project, { foreignKey: 'projectRef' });
Project.hasMany(Task, { as: 'Tasks', foreignKey: 'projectRef' });
// or 
Task.belongsTo(Project, { as: 'Project', foreignKey: 'projectRef' });
Project.hasMany(Task, { as: 'Tasks', foreignKey: 'projectRef' });
```
it doesn't work, but if I remove aliases
```
Task.belongsTo(Project, { foreignKey: 'projectRef' });
Project.hasMany(Task, { foreignKey: 'projectRef' });
```
it works well. So, relating to issue, if I want to leave 
`Project.hasMany(Task, { as: 'Tasks' ...` alias how should I define `as` in `belongsTo` accosiation?

Thank you for your contribution

**Comment by mickhansen** [comment]
@anatolyzolotar aliases should have no effect on the query actually working, unless you're targetting the old names with raw col matching

**Comment by chornbe** [comment]
Let's say I have a simple, but multi-associated model. Something like (to over-use the favorite blog/person example):

model -> Blog
model -> Person

a Blog might have an author, a moderator, and a commenter.

Can I do something like:

var Blog = sequelize.define( "Blog", {
blogName : { type : DataTypes.STRING }
});

var Person = sequelize.define( "Person", {
name : { type : DataTypes.STRING }
});

Super simple for this example.

Can I not then associate Person to Blog three times, using different aliases...

Person.belongsToMany( models.Blog, { as : "author" } );
Person.belongsToMany( models.Blog, { as : "moderator" } );
Person.belongsToMany( models.Blog, { as : "commenter" } );

Blog.hasMany( models.User, { as : "author" } );
Blog.hasMany( models.User, { as : "moderator" } );
Blog.hasMany( models.User, { as : "commenter" } );

Can I not, then, just use them in an include?

models.Blog.findAll({
include : [ "author" ]
})
.then( function( blog ){
// reference blog.author(s) <---- ?
});

Nothing approaching this seems to work, and I thought I'd seen something saying that string-based aliases and includes was working.

Do I have this completely wrong? 

Thanks.

**Comment by raxod502** [comment]
Needing to specify the aliases because of multiple associations between the same models makes sense to me, but if I'm using `include: [{ all: true }]`, then why can't Sequelize figure it out? Is `include: all` really unusable if you use any aliases? Or have I misunderstood what is happening? (It seems that Sequelize drops aliases and queries the default table names, when I use `include: all`.)

**Comment by upasanadash** [comment]
here how to fetch the name total_count?

**Comment by upasanadash** [comment]
resolve: (parent, args, context, resolveInfo) => {
                // return joinMonster.default(resolveInfo,{}, sql => ({
              
                return MovieDb.models.movie_streams.findAll({
                    distinct: true,
                    attributes:[
                       
                            //  include:[{
                                'series_number',
                    
                                [sequelize.literal('COUNT(DISTINCT(series_number))'), 'total_series'],
                                //  attributes: ['organizationName', 'admin']

                                 [sequelize.fn('GROUP_CONCAT', sequelize.literal("DISTINCT(series_number) order by series_number asc  SEPARATOR '||'" )), 'series_number'],
                            //  }]
              ],
                    group: ['movie_id'],
                   where: {movie_id:parent.id, is_episode:1, episode_parent_id:0, is_converted:1 },
                 
                 });

this is my code. In sql we can fetch through two names like total_series and series_number. But how to fetch this name using graphql?

**Comment by ariful-regfire** [comment]
_**Model B**  is associated to **Model A** using an alias. You must use the 'as' keyword to specify the alias within your include statement._

But I have added 'as' keyword to the include already. Can anyone help me with this?

**Comment by omerinjo** [comment]
you specify alise in parent table . 
example:

you have two tables user and comments. User is parent of comments 1:N
foreignKey is in comments table ref to user table (foreignKeys are in childe tables).Sow when you write your associations you set your alies in parent table not in chalde table


user.hasMany(models.comments, {as:"sometthing":foreignKey :"user_id" }) // user_id is primarykey
comments.belongsTo(models.user, {foreignKey :"user_id"})               //user_id is  foreignKeys 

then when you write method

users.findAll({
   include:[{
   model:"comments",
as:"what ever you set in parent table "sometthing""
}]
})
