### ISSUE TITLE
Duplication of the auto-generated primary key with uuid

### ISSUE THREAD

**Issue by exotfboy** [sequelize/sequelize#6010]
Hi:

I am using sequlize in my application, and so far so good, while I want to use the `uuid` as the primary key of the table to prevent the track of the ids.

```
	id: {
		type: Sequelize.UUID,
		defaultValue: Sequelize.UUIDV4,
		primaryKey: true
	},
```

It works, but the length of the uuid is 32 which is to long to display in the url, also there are `-` in the id.

So I wonder if I can generate random string with length of 6 by myself, I know sequelize suppor this by: 

```
  uuid: {
    type: DataTypes.UUID,
    defaultValue: function() {
      return generateMyId()
    },
    primaryKey: true
  }
```

But the `generateMyId` may generate duplicated ids, can sequelize detect this and generate id again?

If not, how can we make sure the unique of the id?

**Comment by sushantdhiman** [comment]
You can hash your numerical primary key using `SHA1`, `MD5` etc, You can come up with a hashing method that is constant for same number.

I think sequelize should not be doing this stuff. This is an domain layer problem not database layer's.

**Comment by exotfboy** [comment]
So, where is the right place to catch the duplication error and re-insert the record?

**Comment by sushantdhiman** [comment]
Keep using numerical primary key, Create a instance level method to convert PK to hash and vice versa. Use hash in express routing.

**Comment by exotfboy** [comment]
Thanks I will have a try.

**Comment by mickhansen** [comment]
You should not base your internal primary key structure on the url needs of your application.
Many hashing schemes exist, take a look at https://www.npmjs.com/package/hashids for one.

**Comment by exotfboy** [comment]
If this conversion is done manually, there will be a lot of work: decode it in the router, and encode the id when data are returned.

Is it possible to make sequlize to handle this?

**Comment by mickhansen** [comment]
You can add a getter to the field aswell as use a beforeFind hook.
Personally i believe you should have the abstraction in the routing layer, it isn't that much work, just two methods.

**Comment by exotfboy** [comment]
Generally there are two procedures where the hash related:

1 From hashed string to `int` id.

For routes like
```
/user/:id
/project/:id 
```
I can create a middleware to de-code the hashed string to the `id`, while there are still some cases like query where the param should be decoded:

`/user?projectId=Edske`

The `Edske` have to be decoded, and there are no rules can be used here, you have to deal with this in the router.


2 From `id` to `string` after you find the record

I can use the `afterFind` to encode the `int` id to `string`, however after this record is retrieved, I may get other related models according to its primary key which has been hashed.

So seems there is not a perfect solution?

Did I miss anything?

**Comment by mickhansen** [comment]
There are hardly ever any perfect solutions :)
