### ISSUE TITLE
beforeUpdate called in bulk update but instance not updated.

### ISSUE THREAD

**Issue by redcomethk** [sequelize/sequelize#6011]
In my application, I update some of the fields of an instance in the beforeUpdate hooks:

```js
beforeUpdate(instance, options) {
  console.log('beforeUpdate');
  instance.title = 'Modified';
},
```
If i call instance.update, the beforeUpdate hook is triggered and the instance is updated.
However, if I call Table.update() with individualHooks: true and in a transaction, I found that the beforeUpdate hook is actually triggered but the instance is not updated. How should I handle the instance so that in both case it will be updated? Thanks!

**Comment by mickhansen** [comment]
Hmm, sounds like Sequelize things nothing has changed so it no-ops.
Please provide a SSCCE (http://sscce.org/)

**Comment by ua2004** [comment]
Same problem.
