### ISSUE TITLE
Need to return customized result using RAW query

### ISSUE THREAD

**Issue by manishchauhanquovantis** [sequelize/sequelize#6012]
Hi,
I am trying to use raw query with multiple joins to list out results.

**Below is the query:-**
  var sql= `'Select * from articles a  Left join article_medias ams on ams.article_id=a.id inner join hcp_topic_article_map htam on htam.article_id = a.id inner join member_topic_map mtm on mtm.topic_id = htam.topic_id inner join hcp_member_map hmm on hmm.member_id = mtm.member_id and hmm.hcp_id = htam.hcp_id inner join auth_tokens at on at.user_id=mtm.member_id and at."token"=:token where article_tab = :type ORDER BY a.created_at DESC  ';`

**index.sequelize.query(sql);**

**Result from query :-**
{"id": 4,
      "title": "4",
      "body": "What is Lorem Ipsum?\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
      "article_type": "Curata",
      "article_tab": "how",
      "image_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
      "content_url": null,
      "created_at": "2016-05-18T12:03:01.405Z",
      "updated_at": "2016-05-18T12:03:01.405Z",
      "type": "image",
      "media_id": "2",
      "media_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
      "preview_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
      "media_extension": "jpg",
      "article_id": 3,
      "hcp_id": 4,
      "topic_id": 1,
      "member_id": 6,
      "token": "be8fc788fd55c7f09dcc6a0fb57d4363f68ee3d1ed9de8e083db608c53573913",
      "login_type": "Chrome",
      "user_id": 6
}

The issue that I am facing is that i need results in below format 
{
"id": 4,
      "title": "4",
      "body": "What is Lorem Ipsum?\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
      "article_type": "Curata",
      "article_tab": "how",
      "image_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
      "content_url": null,
      "created_at": "2016-05-18T12:03:01.405Z",
      "updated_at": "2016-05-18T12:03:01.405Z",
      "type": "image",
     "media":[ {
             "media_id": "2",
              "media_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
              "preview_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
              "media_extension": "jpg"
               
          } ,  
          {
             "media_id": "3",
              "media_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
              "preview_url": "http://skyhigh.city/wp-content/uploads/2015/04/sky_colors-670x447.jpg",
              "media_extension": "jpg"
               
          }  ]
}
There is 1:N mapping between article and article media and thus we want array of media within an article as shown above.

**Comment by mickhansen** [comment]
You'll need to do your own post processing, unless you use proper find calls with includes sequelize doesn't know what to do.
