### ISSUE TITLE
[security] build parameterized queries instead of escaping strings

### ISSUE THREAD

**Issue by taoeffect** [sequelize/sequelize#6017]
## What you are doing?

While troubleshooting #6016 I noticed the stack trace went through a function called `SqlString.escape` in a file `sql-string.js`.

I was surprised to learn that Sequelize uses string escaping instead of binding to parameterized queries. Searching for `?'` and `parameterized` in the repository revealed no results, suggesting that sequelize does not use parameterized queries at all.

## What do you expect to happen?

For sequelize to properly construct and use parameterized queries like anything that uses SQL should.

## What is actually happening?

It does not, instead it uses inefficient and potentially insecure string escaping to protect against SQLi.

__Dialect:__ any
__Database version:__ any
__Sequelize version:__ 3.23.3

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/1608
