### ISSUE TITLE
Handle more than 1000 records when bulk inserting in MSSQL

### ISSUE THREAD

**Issue by diegobfernandez** [sequelize/sequelize#6022]
MSSQL limits insert statement to 1000 records, would be very nice to have sequelize handling it for me.
For instance I have worked around this limitation doing the following:

    var batchSize = 500,
        batches = [[]],
        currentBatch = 0;

    for (var item of items) {
      if (batches[currentBatch].length >= batchSize) {
        batches.push([]);
        currentBatch = batches.length - 1;
      }

      batches[currentBatch].push(item);
    }

    Promise.all(batches.map(batch => models.Product.bulkCreate(batch, { transaction })));

Is it possible to implement this behaviour?

Thanks!

**Comment by mickhansen** [comment]
It's unlikely that we'll introduce custom logic for a single dialect.
You could very easily create your own wrapper in any case.

**Comment by klondikemarlen** [comment]
Even though this is marked as close/solved, I still can't batch create records in Seqeulize 7, so I added this to my base model.
```ts
import {
  Attributes,
  BulkCreateOptions,
  CreationAttributes,
  Model,
  ModelStatic,
} from "@sequelize/core"

// See api/node_modules/@sequelize/core/lib/model.d.ts -> Model
export abstract class BaseModel<
  // eslint-disable-next-line @typescript-eslint/ban-types, @typescript-eslint/no-explicit-any
  TModelAttributes extends {} = any,
  // eslint-disable-next-line @typescript-eslint/ban-types
  TCreationAttributes extends {} = TModelAttributes,
> extends Model<TModelAttributes, TCreationAttributes> {
  /**
   * Add the missing batchSize option to bulkCreate.
   */
  public static async bulkCreateBatched<M extends BaseModel>(
    this: ModelStatic<M>,
    records: CreationAttributes<M>[],
    options?: BulkCreateOptions<Attributes<M>> & {
      batchSize?: number
    }
  ): Promise<void> {
    const batchSize = options?.batchSize ?? 1000

    for (let i = 0; i < records.length; i += batchSize) {
      const batch = records.slice(i, i + batchSize)
      await this.bulkCreate(batch, options)
    }
  }
}
```

I wonder if Sequelize will every consider using Knex under the hood? That way they would get a lot of these things for relatively low cost.
