### ISSUE TITLE
Performance hit with sequalize on lambda?

### ISSUE THREAD

**Issue by foobar8675** [sequelize/sequelize#6026]
I am you performance issues with (i believe) sequalize on lambda and am wondering if this is just the norm. For example, I have a call where my app thinks the timing is 97 mc but lambda actually takes 1102 ms.  The timings of my test lambda without sequalize seem to make more sense. Anyways, any thoughts are appreciated.

// my pool

    pool: {
    max: 1,
    min: 0,
    idle: 100
   },

// snippet

    module.exports.handler = function (event, context, cb) {
      console.time("reqstart")
      var model = require('../models');
      var group;
		model.Group.create({})
      .then(function (localGroup) {
	    console.timeEnd("reqstart")
        return cb(null, {
          message: 'Go Serverless! Your Lambda function executed successfully! '+JSON.stringify(event, null, 2)
       });
    })
    .catch(function (err) {
      console.log(err);      
    });
};

// cloudwatch logs

    START RequestId: 7384364a-2b93-11e6-9d8f-83d013cc53d6 Version: 60  
    2016-06-06T03:04:59.120Z	undefined	Executed (default): INSERT INTO "Groups"  ("id","createdAt","updatedAt") VALUES ('54d96b10-7e24-4c0b-ac26-6f2444f65978','2016-06-06 03:04:59.030 +00:00','2016-06-06 03:04:59.030 +00:00') RETURNING *; 10 
    2016-06-06T03:04:59.123Z	7384364a-2b93-11e6-9d8f-83d013cc53d6	reqstart: 97ms
    END RequestId: 7384364a-2b93-11e6-9d8f-83d013cc53d6 
    REPORT RequestId: 7384364a-2b93-11e6-9d8f-83d013cc53d6	Duration: 1102.49 ms	           Billed Duration: 1200 ms Memory Size: 1024 MB	Max Memory Used: 41 MB

**Comment by sushantdhiman** [comment]
> 2016-06-06T03:04:59.123Z    7384364a-2b93-11e6-9d8f-83d013cc53d6    reqstart: 97ms

- It appears `sequelize` took only `97 ms`, rest time is consumed in resolving `cb` , may be something wrong on that part of code.

>  model.Group.create({})

- What are you passing as `{}`

> .then(function (localGroup) {

- How many entries you got in `localGroup` , `10` ?

- Can you try the `model.Group.create({})` with `benchmark:true`

> console.time("reqstart")

- try placing it after ` var model = require('../models');`

**Comment by mickhansen** [comment]
if lambda isn't continously hot you'll be relaunching instances of sequelize often so you need to setup new connections often which slows down queries.

Try doing a few queries in a row to see if the duration drops or not.

**Comment by foobar8675** [comment]
Hi @samkelleher , 

It does make sense it's something with resolving the cb. However, in cases where I comment out all the sequalize calls, my console.time calls align with the lambda execution times. Confusing.

For the Group.create, I'm just passing in an empty {} using the following model. It's just inserting a UUID and createdAt, updatedAt. So localGroup always just returns 1. 

	var Group = sequelize.define("Group", {
		id: {
			type: DataTypes.UUID,
			defaultValue: DataTypes.UUIDV4,
			primaryKey: true
		},
		name: {
			type: DataTypes.STRING,
			field: 'name'
		},
		meta: {
			type: DataTypes.JSON,
			field: 'meta'
		}
	} 

entire project using serverless is here (with some extra logging) . https://github.com/foobar8675/foo

here's the logging with the benchmarking. since the console time reqstart is 828ms and the total time is 1832ms, there's an extra second in there I can't account for.

This is after a few requests from postman, so I assume I'm hitting the same container and everything is warmed up. (i think) My initial request usually times out, which is another problem

```
START RequestId: 5d42b5d4-2bfa-11e6-8dd0-232c884bdf07 Version: 71 
2016-06-06T15:21:40.287Z	5d42b5d4-2bfa-11e6-8dd0-232c884bdf07	Executed (default): INSERT INTO "Groups" ("id","createdAt","updatedAt") VALUES ('c621f127-a7d7-4eee-af8b-7c6b510b8cf6','2016-06-06 15:21:40.187 +00:00','2016-06-06 15:21:40.187 +00:00') RETURNING *; Elapsed time: 7ms 
2016-06-06T15:21:40.290Z	5d42b5d4-2bfa-11e6-8dd0-232c884bdf07	reqstart: 828ms 
END RequestId: 5d42b5d4-2bfa-11e6-8dd0-232c884bdf07 
REPORT RequestId: 5d42b5d4-2bfa-11e6-8dd0-232c884bdf07	Duration: 1832.20 ms	Billed Duration: 1900 ms Memory Size: 1024 MB	Max Memory Used: 41 MB	

```

Anyways, if you have any thoughts or if you are / are not seeing this problem, I'd love to hear.

**Comment by foobar8675** [comment]
@mickhansen unfortunately, that first posting was after submitting a few requests. My first request usually times out or takes a super long time.

**Comment by foobar8675** [comment]
dont think this is a sequalize bug, so closing

**Comment by atwoodjw** [comment]
I'm seeing the exact same thing w/ my Serverless Lambda using Sequelize. I have a query that purportedly takes ~ 1s, yet the Lambda function takes over ~11s to run.

```
START RequestId: 21106e3c-31e7-11e6-a7de-9b56e206bc93 Version: $LATEST
2016-06-14T04:19:04.372Z	21106e3c-31e7-11e6-a7de-9b56e206bc93	START: findAll
2016-06-14T04:19:04.454Z	0f28ff11-31e7-11e6-a728-35c07750591a	Executing (default): SELECT "agencyId", "id", "code", "name", "description", "direction", "lat", "lon", "zoneId", "url", "locationType", "parentStation", "timezone", "vehicleType", "wheelchairBoarding", "platformCode" FROM "gtfs_stops" AS "GtfsStop";
2016-06-14T04:19:05.638Z	21106e3c-31e7-11e6-a7de-9b56e206bc93	DONE: findAllDone
END RequestId: 21106e3c-31e7-11e6-a7de-9b56e206bc93
REPORT RequestId: 21106e3c-31e7-11e6-a7de-9b56e206bc93	Duration: 11293.65 ms	Billed Duration: 11300 ms 	Memory Size: 1024 MB	Max Memory Used: 69 MB
```

And this is with the callback returning an empty object, which should rule out the callback as a suspect.

```
console.info('START: findAll');

model.GtfsAgency.findAll().then(function(data) {
    console.info('DONE: findAllDone');
    return cb(null, {
        data: data
    });
})
```

Once warmed up, this behavior is consistent -- losing ~10s on every invocation.

**Comment by mickhansen** [comment]
@atwoodjw How quick is the entire findAll call?

**Comment by atwoodjw** [comment]
Using the START & DONE logging statements above to calculate, the findAll took 1.266s. Not great, but I'm less worried about that, since I can have API Gateway cache results. I also haven't done anything with connection pool yet, so it also includes the connection setup time. 

I'm more concerned with the extra ~ 10s of execution time that I can't account for.

**Comment by mickhansen** [comment]
@atwoodjw I no next to nothing about Lambda so not sure we can help you there. If tracing around sequelize shows that it's only using 10% of the operational time i can't really tell you where the rest is coming from :)

Assuming the code isnt hot the connection setup time should be counted towards the findAll time.

**Comment by foobar8675** [comment]
@atwoodjw if you change your pool like mine above, you might see it improve, once warmed up. i have a ticket with aws to try to dig a bit deeper. if anything is found out, i'll post here.

**Comment by foobar8675** [comment]
i heard back from aws tech support. basically there's nothing we can do.

--

The "executing static blocks outside of the handler" is lambda processing things.
Lambda specific static blocks.
That is beyond your control.

However because this requires processing, the time to do this is included in the timing calculation.

> does that mean you are saying the loading of sequalize, which is about 12M
From your code, it looks like your are loading sequalize before your timer starts.
It is safe to say that 'var Sequelize = require('sequelize');' did not cause the delay.
however the back end process related to that, before the function starts, may cause the delay.
What the back end processes involved, I am unable to say as it is internal to AWS.

**Comment by atwoodjw** [comment]
I think static blocks outside the handler is a red herring; it only applies to "cold" calls anyway.

See the two examples below. The code is identical, excect for the findAll() call. In the 1st example, findAll() is called and I print DONE after this promise is resolved. In the 2nd example, I findAll() isn't called; I print DONE right away. Otherwise, they're identical -- same imports outside the handler, etc.

\#1 takes ~10s while \#2 takes ~2ms.

### 1. findAll() Example -- Takes ~10s

```
import Sequelize from "sequelize";
import model from "../../lib/model";

function handler(event, context, cb) {
  console.info('Initializing Sequalize...');

  const sequelize = new Sequelize('devDb', 'devUsername', 'devPassword', {
    host: 'xxx',
    dialect: 'postgres'
  });

  console.info('Initializing Models...');
  model.init(sequelize);

  function getData() {
    console.info('START');

    model.GtfsAgency.findAll().then(function (data) {
      console.info('DONE');
      return cb(null, {
        data: {}
      });
    })
  }

  getData();
}

exports.handler = handler;
```

```
START RequestId: 084557a1-3285-11e6-82d2-cb5e4fee5a5c Version: $LATEST
2016-06-14T23:09:23.234Z  084557a1-3285-11e6-82d2-cb5e4fee5a5c  Initializing Sequalize...
2016-06-14T23:09:23.236Z  084557a1-3285-11e6-82d2-cb5e4fee5a5c  Initializing Models...
2016-06-14T23:09:23.236Z  084557a1-3285-11e6-82d2-cb5e4fee5a5c  START
2016-06-14T23:09:23.251Z  00067148-3285-11e6-a708-1b0892528d4d  Executing (default): SELECT "id", "fareUrl", "lang", "name", "phone", "timezone", "url" FROM "gtfs_agencies" AS "GtfsAgency";
2016-06-14T23:09:23.253Z  084557a1-3285-11e6-82d2-cb5e4fee5a5c  DONE
END RequestId: 084557a1-3285-11e6-82d2-cb5e4fee5a5c
REPORT RequestId: 084557a1-3285-11e6-82d2-cb5e4fee5a5c  Duration: 10031.95 ms Billed Duration: 10100 ms 
```

### 2. WITHOUT findAll() Example -- FAST

```
import Sequelize from "sequelize";
import model from "../../lib/model";

function handler(event, context, cb) {
  console.info('Initializing Sequalize...');

  const sequelize = new Sequelize('devDb', 'devUsername', 'devPassword', {
    host: 'xxx',
    dialect: 'postgres'
  });

  console.info('Initializing Models...');
  model.init(sequelize);

  function getData() {
    console.info('START');

    // model.GtfsAgency.findAll().then(function (data) {
      console.info('DONE');
      return cb(null, {
        data: {}
      });
    // })
  }

  getData();
}

exports.handler = handler;
```

```
START RequestId: a3f17194-3284-11e6-8e3a-673841ce84c7 Version: $LATEST
2016-06-14T23:06:34.928Z  a3f17194-3284-11e6-8e3a-673841ce84c7  Initializing Sequalize...
2016-06-14T23:06:34.930Z  a3f17194-3284-11e6-8e3a-673841ce84c7  Initializing Models...
2016-06-14T23:06:34.930Z  a3f17194-3284-11e6-8e3a-673841ce84c7  START
2016-06-14T23:06:34.930Z  a3f17194-3284-11e6-8e3a-673841ce84c7  DONE
END RequestId: a3f17194-3284-11e6-8e3a-673841ce84c7
REPORT RequestId: a3f17194-3284-11e6-8e3a-673841ce84c7  Duration: 2.38 ms Billed Duration: 100 ms
```

I'm not sure where the issues lies. ¯\\\_(ツ)_/¯

**Comment by atwoodjw** [comment]
Found the issue after RTFM.

http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html#nodejs-prog-model-context-properties

You have to set `context.callbackWaitsForEmptyEventLoop = false`. Otherwise, the process isn't terminated until the event loop is empty.

Hope this helps someone.

**Comment by mickhansen** [comment]
@atwoodjw God is that a dumb default to have for an async language.

**Comment by foobar8675** [comment]
@atwoodjw thanks a ton for figuring that out and @mickhansen ditto.

**Comment by marlomgirardi** [comment]
Unfortunately, Sequelize is not good for lambda because the higher cost is the startup...

With sequelize it takes almost 1s to return the request and with mysql2 in most cases lower than 100ms.


```
2018-05-30T15:42:11.370Z	04395f47-6420-11e8-9c1a-95b27db38b01	DBREQUEST: 141.998ms
2018-05-30T15:42:11.371Z	04395f47-6420-11e8-9c1a-95b27db38b01	REQUESTEND: 622.803ms
END RequestId: 04395f47-6420-11e8-9c1a-95b27db38b01
REPORT RequestId: 04395f47-6420-11e8-9c1a-95b27db38b01	Duration: 623.37 ms	Billed Duration: 700 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
```

**Comment by Lan19094** [comment]
thanks for the solutions :)

**Comment by marcogrcr** [comment]
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.
