### ISSUE TITLE
relation does not exist for multiple hasOne/belongsTo

### ISSUE THREAD

**Issue by benjaminhon** [sequelize/sequelize#6027]
```
#############
# Model
#############

Node = sequelize.define('node', {
  id: {
    type:       Sequelize.INTEGER
    primaryKey: true
  }
}, {
  timestamps: false
})

Beacon = sequelize.define('beacon', {
  major: Sequelize.INTEGER
  minor: Sequelize.INTEGER
}, {
  timestamps: false
})

StaticDevice = sequelize.define('staticDevice' ,{
  coordinates:  Sequelize.GEOMETRY
  type:         Sequelize.ENUM('NODE', 'BEACON', 'BOTH')
  battery:      Sequelize.FLOAT
})

#############
# Relations
#############

StaticDevice.hasOne(Node)
StaticDevice.hasOne(Beacon)

#############
# sync
#############
StaticDevice.sync(force: true)
Node.sync(force: true)
Beacon.sync(force: true)
```

I get this error:
```
relation "staticDevices" does not exist
```

Why does this exists? im really lost, im doing exactly what the docs say.

**Comment by janmeier** [comment]
Node and Beacon have foreign key references to StaticDevice. Each call to `sync` is asyncronous, so when you fire them of like they were serial, the StaticDevice is not created at the time you try to create the two other tables. You can use promises (`.then`), es7 (`await`), or simply `sequelize.sync()` to have sequelize handle syncing the tables in the correct order

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by benjaminhon** [comment]
hi jan, yes i just solved it as i actually created the model in Promise.all

it is now
```
Map.sync(force: true)
  .then ->
    MapGeometry.sync(force: true)
  .then ->
    StaticDevice.sync(force: true)
  .then ->
    MobileDevice.sync(force: true)
  .then ->
    Node.sync(force: true)
  .then ->
    Beacon.sync(force: true) 
```

However, i think this should still be reported as a Bug. Because this is what is sugested in the Docs.
Even the 'Team, Player' example in the docs did what i did. It is plain wrong, i get errors even with that example. just that sometimes it doesnt show because sometimes team gets created first before player

So shouldnt this be a bug? since the docs way of creating does not work?

**Comment by benjaminhon** [comment]
Hi Jan,

do you mean that instead of
```
StaticDevice.sync(force: true)
Node.sync(force: true)
Beacon.sync(force: true)
```
i just do ?
```
sequelize.sync()
```

**Comment by benjaminhon** [comment]
ok that works

**Comment by janmeier** [comment]
Where in the docs did you see the `.sync` without waiting for it to return? That should definitely be fixed

**Comment by benjaminhon** [comment]
My bad, I guess i should be just using sequelize.sync(). Because i was doing as per the docs, copying the examples, but just syncing them manually.

However, please correct me if i am wrong, but i am just copying this directly from the docs
http://docs.sequelizejs.com/en/latest/docs/associations/#creating-elements-of-a-belongsto-or-hasone-association

```
var Product = this.sequelize.define('product', {
  title: Sequelize.STRING
});
var User = this.sequelize.define('user', {
  first_name: Sequelize.STRING,
  last_name: Sequelize.STRING
});

Product.belongsTo(User);

return Product.create({
  title: 'Chair',
  User: {
    first_name: 'Mick',
    last_name: 'Broadstone'
  }
}, {
  include: [ User ]
});
```

However, in the table, only products get create, no entry for users is created.

**Comment by janmeier** [comment]
Tiny typo, the key should match the name / alias of the model (in this case `user` with lower case u) https://github.com/sequelize/sequelize/commit/d524adc870e378af4d02de682b53e9a3462c7714

**Comment by benjaminhon** [comment]
ahh ok
