### ISSUE TITLE
creating-elements-of-a-belongsto-or-hasone-association

### ISSUE THREAD

**Issue by benjaminhon** [sequelize/sequelize#6028]
Under the docs example:
http://docs.sequelizejs.com/en/latest/docs/associations/#creating-elements-of-a-belongsto-or-hasone-association

I just did exactly as it says, however only a product entry is created, no user entry is created, it says
'A new Product and User can be created in one step in the following way: '

is this description really correct? or do i need to create user first then do the following? the description seems to indicate that it will create a new user for me.

```
var Product = this.sequelize.define('product', {
  title: Sequelize.STRING
});
var User = this.sequelize.define('user', {
  first_name: Sequelize.STRING,
  last_name: Sequelize.STRING
});

Product.belongsTo(User);

return Product.create({
  title: 'Chair',
  User: {
    first_name: 'Mick',
    last_name: 'Broadstone'
  }
}, {
  include: [ User ]
});
```

**Comment by janmeier** [comment]
Please don't open a new issue, I'm still subscribing to the old one even though its closed :)
