### ISSUE TITLE
:hasMany with parameterized scopes

### ISSUE THREAD

**Issue by akaNightmare** [sequelize/sequelize#6029]
Hi.
## What you are doing?

I want to create a custom relation with a custom input param? How to do it.
Thank you.

Scope:

``` js
scopes: {
            active: {where: {is_active: true}},
            /**
             * @param {String=} username
             * @returns {{include: *[]}}
             */
            includeApplications: (username) => {
                const queryBuilder = {
                    include: [{model: product.associations.application.target}]
                };

                if (username !== undefined) {
                    queryBuilder.include[0].where = {username: username};
                }

                return queryBuilder;
            }
        },
```

Relation:

``` js
product.hasMany(models.Application, {
                    foreignKey: 'product_id',
                    as: 'userApplications',
                    scope: {
//                        includeApplications: with parameter custom input param
                    }
                });
```

**Dialect:** mysql
**Database version:** 5.6
**Sequelize version:** 3.20.0

**Comment by akaNightmare** [comment]
@janmeier can you write some example?

**Comment by janmeier** [comment]
No wait - Do you want to have a fixed value for username, or to specify it each time?

**Comment by akaNightmare** [comment]
@janmeier 
>> specify it each time,
about fixed value - I know how to do it.

Thanks

**Comment by janmeier** [comment]
In that case you don't need to specify the scope in association setup. The code i linked handles `getUserApplications( { scope: 'foobar' })`. That could be extended to support ``getUserApplications( { scope: ['foobar', 'baz'] })`, which would mean all the values are passed to the `.scope`function

**Comment by akaNightmare** [comment]
@janmeier hm, it generates a separate query. But I want make(select) it in one query with JOIN.

**Comment by janmeier** [comment]
Huh? What generates a separate query?

**Comment by akaNightmare** [comment]
```js
const products = yield models.product.findAll();
const userApps = yield products.getUserApplications();
```

**Comment by janmeier** [comment]
Ah yes, two different calls create two different queries :)

We should be able to do the `.apply` trick for includes as well, https://github.com/sequelize/sequelize/blob/d524adc870e378af4d02de682b53e9a3462c7714/lib/model.js#L519

(btw, I'm just handing out pointers here, you'll probably have to dig into the code and provide a PR yourself if you need this)
