### ISSUE TITLE
Sequelize + Typescript build error. pg-native and not a constructor.

### ISSUE THREAD

**Issue by lrojas94** [sequelize/sequelize#6034]
## What you are doing?
Basically trying to build a **typescript** code using sequelize and then compiling it using webpack. However, I seem to be getting two different errors: 
* I'm required to install pg-native (even though native is set to false).
* If I happen to have pg-native installed, I get:

```ts
import Sequelize from 'sequelize';
import {constants} from './../constants.ts';

export var initialized: Boolean = false;

export function initialize():void {
  if(this.initialized){
    return;
  }

  var sequelize = new Sequelize(constants.DATABASE_NAME,constants.DATABASE_USERNAME,constants.DATABASE_PASSWORD,{
    host: constants.DATABASE_HOST,
    dialect: 'postgres',
    native : false,
    pool: {
      maxConnections: 100,
      minConnections: 0,
      maxIdleTime: 10000
    }

  });

  this.initialized = true;
};

```
I'm just calling the intialize function on my server.js file (which builds and runs just fine if I omit the sequelize functionality)

## What do you expect to happen?
I expected it to build and run, as you might expect.

## What is actually happening?
I'm getting 
```js
ERROR in ./~/pg/lib/native/index.js
Module not found: Error: Cannot resolve module 'pg-native' in /home/luis/Projects/FinalProject-Gamify-Education/node_modules/pg/lib/native
 @ ./~/pg/lib/native/index.js 1:13-33
```
and, If I manage t install pg-native (which is currently giving away problems to work), I get:
```js
ERROR: new sequelize_1.default is not a constructor. 
which points to the line sequelize = new Sequelize ...
```
__Dialect:__ postgres
__Database version:__ 9.3.13
__Sequelize version:__ 3.23.3

**Comment by mickhansen** [comment]
Please show the compiled code, we don't actively support TypeScript or babel.
Sounds like babel is compiling the imports and expecting that Sequelize exports a default prop, which it currently doesn't

**Comment by lrojas94** [comment]
Here you go:

```js
[2] /home/luis/Projects/FinalProject-Gamify-Education/www/app.bundle.js:60989
[2] 	    var sequelize = new sequelize_1.default(constants_ts_1.constants.DATABASE_NAME, constants_ts_1.constants.DATABASE_USERNAME, constants_ts_1.constants.DATABASE_PASSWORD, {
[2] 	                    ^
[2] 
[2] TypeError: sequelize_1.default is not a function
[2]     at Object.initialize (/home/luis/Projects/FinalProject-Gamify-Education/www/app.bundle.js:60989:22)
[2]     at Server.<anonymous> (/home/luis/Projects/FinalProject-Gamify-Education/www/app.bundle.js:70:9)
[2]     at Server.g (events.js:260:16)
[2]     at emitNone (events.js:67:13)
[2]     at Server.emit (events.js:166:7)
[2]     at emitListeningNT (net.js:1260:10)
[2]     at nextTickCallbackWith1Arg (node.js:431:9)
[2]     at process._tickCallback (node.js:353:17)
[2]     at Function.Module.runMain (module.js:443:11)
[2]     at startup (node.js:139:18)
[2]     at node.js:968:3

```

**Comment by lrojas94** [comment]
Thanks @felixfbecker, but I'm still getting the helper.js problem when using postgres. Any ideas as of what could be happening?

**Comment by felixfbecker** [comment]
@lrojas94 That is not a module of sequelize. You should enable source maps in Webpack to see where the error is actually thrown. But why are you using Webpack for NodeJS?

**Comment by lrojas94** [comment]
@felixfbecker  How are you using TS in your backend if you're not building it with Webpack (or something of the sort)? I'm only using webpack in order to build the TS into a NodeJS compatible server side script (a JS basically).

**Comment by felixfbecker** [comment]
@lrojas94 Webpack is a bundler for client (browser) usage. You can compile TypeScript files with the typescript compiler `tsc`, see http://www.typescriptlang.org/docs/tutorial.html#compiling-your-code.

**Comment by mickhansen** [comment]
Good to know @felixfbecker :)

**Comment by lrojas94** [comment]
After reading for a while I see your point now @felixfbecker . Thanks a lot! and you too @mickhansen , I'll be marking this as solved.
