### ISSUE TITLE
Group By clause issue

### ISSUE THREAD

**Issue by manishchauhanquovantis** [sequelize/sequelize#6043]
Hey I am trying to use group by to count list of users liking a article.
```
models.ArticleLike.findAll({
   attributes: ['ArticleLike.user_id', [models.sequelize.fn('count', models.sequelize.col('ArticleLike.user_id')), 'total_count']],
   include:[{model:models.Article}], group: ['Article.id']
 }).then(function(results){
   console.log(results);
 }).catch(function(error){
   console.log(error);
```
i am getting this issue after running it
 [SequelizeDatabaseError: column "ArticleLike.id" must appear in the GROUP BY clause or be used in an aggregate function]
  name: 'SequelizeDatabaseError',
  message: 'column "ArticleLike.id" must appear in the GROUP BY clause or be used in an aggregate function',

**Comment by mickhansen** [comment]
Try adding `attributes: []` to the include options.

**Comment by manishchauhanquovantis** [comment]
Still it didnt work

`  models.ArticleLike.findAll({
   attributes: ['ArticleLike.user_id', [models.sequelize.fn('sum', models.sequelize.col('ArticleLike.user_id')), 'total_count']],
   include:[{model:models.Article,attributes:[]}], group: ['Article.id']
 }).then(function(results){
   console.log(results);
 }).catch(function(error){
   console.log(error);
 });`

again the same above error

**Comment by mickhansen** [comment]
Please make an effort to properly format your code so it's readable.
Look at the SQL query, also your `attributes` are using prefixes which is not exactly supported.
