### ISSUE TITLE
Random Operator

### ISSUE THREAD

**Issue by jamestwiggle** [sequelize/sequelize#6057]
I'm trying to get random `product` rows from `products` table and limit the random rows retrieved to 16 rows. I can't seem to find the operators to handle this case. I also checked StackOverFlow and couldn't find what I was looking for. I found limit in the docs but is that best to be used or the `$lt`?
```js
DB.models.products.findAll({
    limit: args.quantity,
    order: [
      [Sequelize.fn('RAND', '')]
    ]
})
```

This peice of code returns the following errors:
`"function rand(unknown) does not exist"`

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/3139 

Which dialect are you using?

**Comment by jamestwiggle** [comment]
Im using postgresql @janmeier 

would I just need :
```js
order: [ random ]
```

**Comment by janmeier** [comment]
http://stackoverflow.com/questions/5297396/quick-random-row-selection-in-postgres

**Comment by jamestwiggle** [comment]
Thats doesn't really show how to do it in `sequelize`

**Comment by janmeier** [comment]
If you look at the query you'll see that the code you have now is passing an empty string to the random function, thats why its failing

```js
    order: [
      [Sequelize.fn('RAND')]
    ]
```

**Comment by harrison0723** [comment]
^The above answer still gives me an error

`"function rand() does not exist"`

**Comment by sushantdhiman** [comment]
@harrison0723 `MySQL` have `RAND()` and `Postgres` have `RANDOM()` , different names for different database for same task :)

**Comment by harrison0723** [comment]
@sushantdhiman  Got it! Thanks
