### ISSUE TITLE
Generated MySQL queries inserting BOOLEAN field values as booleans, not integers

### ISSUE THREAD

**Issue by terraflubb** [sequelize/sequelize#607]
I'm seeing a bug similar to #149 but for MySQL, I wanted to double check this before getting started on a PR.

I'm using MySQL and I have a model with a field I set up as Sequelize.BOOLEAN.

```
var value = false;
Foo.create( {booleanField: value;})
Foo.create( {booleanField: value ? 0 : 1;}) // I tried to be sneaky here in case it was my fault. didn't help
```

These both generate:

`INSERT INTO foo (booleanField) VALUES (false);`

Looking at the query generator for MySQL I see that it doesn't handle booleans explicitly, so even though it sets up the tables as `TINYINT(1)` and so the value just ends up using the default value for that column.

Am I correct in thinking that I need to do to MySQL what was done to SQLite in #149? I guess it just seems weird to me that nobody else ran into this yet, so I wanted to double check.

**Comment by geyuqiu** [comment]
@terraflubb @sdepold We do have to save boolean as bool and not as tinyInt for some use cases in Sqlite. But currently it is saved as tinyInt although defaultValue: false (and not 1 or 0)

**Comment by geyuqiu** [comment]
https://github.com/sequelize/sequelize/issues/10288

**Comment by geyuqiu** [comment]
Is there any work around to achieve Boolean for CREATE TABLE?

**Comment by papb** [comment]
@geyuqiu Can you please open a new issue, filling the template, describing your issue in more detail? And link to this one? Thanks.
