### ISSUE TITLE
JSONB $not isn't acting how I expected

### ISSUE THREAD

**Issue by rainhawk616** [sequelize/sequelize#6070]
Hello,

I'm writing a fileAll query using a $not on a JSONB field.  The resulting query uses a != operator when I expected it to use a NOT.  No matter how I use $not I can't seem to get the resulting query to look how I expected.

Here is my table:

```
CREATE TABLE public.cards
(
  cardid integer NOT NULL DEFAULT nextval('cards_cardid_seq'::regclass),
  name character varying(255) NOT NULL,
  subtypes jsonb
)
```

Here is my where object:

```
{
  "subtypes": {
    "$and": {
      "$contains": [
        "Human"
      ],
      "$or": [
        {
          "$contains": "Knight"
        },
        {
          "$contains": "Wizard"
        }
      ],
      "$and": {
        "$not": {
          "$or": [
            {
              "$contains": "Wizard"
            },
            {
              "$contains": "Soldier"
            }
          ]
        }
      }
    }
  }
}
```

Here is the resulting query:

```
SELECT "cardid", "name", "subtypes"
FROM "cards" AS "Card"
WHERE (
    "Card"."subtypes" @> '["Human"]'
    AND (
        "Card"."subtypes" @> '"Knight"'
        OR "Card"."subtypes" @> '"Wizard"'
    )
    AND (
        "Card"."subtypes" != '{"$or":[{"$contains":"Wizard"},{"$contains":"Soldier"}]}'
    )
);
```

Here is the query I expected:

```
SELECT "cardid", "name", "subtypes"
FROM "cards" AS "Card"
WHERE (
    "Card"."subtypes" @> '["Human"]'
    AND (
        "Card"."subtypes" @> '"Knight"'
        OR "Card"."subtypes" @> '"Wizard"'
    )
    AND (
        NOT (
            "Card"."subtypes" @> '"Wizard"'
            OR "Card"."subtypes" @> '"Soldier"'
        )
    )
);
```

**Comment by mickhansen** [comment]
JSONB comparison is not perfect yet, we fail to handle a few cases.
PR welcome :)

**Comment by Alexolp** [comment]
I'll have to check out the source and see if I can come up with a good solution for a PR.

Do you have a recommendation for a work around in the meantime?  Is there a way for me to write sql in the where object so I can explicitly use the NOT operator?

**Comment by rainhawk616** [comment]
I'll have to check out the source and see if I can come up with a good solution for a PR.

Do you have a recommendation for a work around in the meantime? Is there a way for me to write sql in the where object so I can explicitly use the NOT operator?

**Comment by felixfbecker** [comment]
@rainhawk616 You can always do a raw query or use `sequelize.where()`
