### ISSUE TITLE
[docs] npm run docs fails

### ISSUE THREAD

**Issue by adam-back** [sequelize/sequelize#6071]
## What you are doing?

Trying to generate API docs using `npm run docs` command from master branch.
## What do you expect to happen?

I expect to generate API docs from source code comments.
## What is actually happening?

![screen shot 2016-06-09 at 3 51 51 pm](https://cloud.githubusercontent.com/assets/8163408/15949167/32e0a1a8-2e5a-11e6-8673-27ebd2903b00.png)

Docs fail to generate because docs-generator.js is failing to find `lib/instance.js` [here](https://github.com/sequelize/sequelize/blob/master/docs/docs-generator.js#L24).

`instance.js` was renamed to `model.js` with commit https://github.com/sequelize/sequelize/commit/d25456441a1fdd92216c37b06a802f9d34b44e56.
## Suggested Fix

Remove `lib\instance.js` from `docs-generator.js`. `model.js` is already there.

**Dialect:** N/A
**Database version:** N/A
**Sequelize version:** 4.0.0-0

**Comment by adam-back** [comment]
This fundamentally changes the structure of the API docs. If we remove the Instance doc, should we also remove the non-source code documentation for Instance?

**Comment by janmeier** [comment]
I guess we should, but then we need a clearer distinction between instance and static methods then.

Ideally I'd like to remove the manual docs generation completely and use something like https://github.com/lipp/doclets. @lipp - Any progress on the local testing tool :) ?

**Comment by adam-back** [comment]
We could organize Model and Instance under a heading, kind of like Associations:

![screen shot 2016-06-13 at 1 36 02 pm](https://cloud.githubusercontent.com/assets/8163408/16022292/f863b122-316b-11e6-8bf2-47b4f689cba5.png)

The overview would define the distinction, but what would the grouping header be?

**Comment by janmeier** [comment]
The home-rolled parser has been replaced with esdoc
