### ISSUE TITLE
LIMIT of query placed in subquery when using include

### ISSUE THREAD

**Issue by saekort** [sequelize/sequelize#6073]
This is related to #6025 
## The situation

I have simplified the 'issue' to this: Say I have a Book, a Book has one or more authors. Authors have written one or more books. I want to do count and get all Books that are written by authors with the name 'Scott' in their name field.
## The code

```
Book model:
var Book = sequelize.define('book', {
  title: Sequelize.STRING,
  description: Sequelize.TEXT
})

Author model:
var Author= sequelize.define('author', {
  name: Sequelize.STRING,
})

Associations:
Book.belongsToMany(Author, {as: 'authors', foreignKey: 'book_id', through: 'j_author_book'});
Author.belongsToMany(Book, {as: 'books', foreignKey: 'author_id', through: 'j_author_book'});

Query:
Book.findAndCountAll({
  limit: 15,
  include: [ {model: Author, as: 'authors', where: {name: {$like: '%' + 'Scott' + '%'}}, order: [ ['name', 'ASC'] ]}
})
```
## What do you expect to happen?

I expect 2 queries:
1: A count (this works, it is not the point)
2: A select that gets me the first 15 results that apply to the '%Scott%' LIKE in the include statement.
## What is actually happening?

I get a COUNT that for example says '5' while the actual get query gives me no results. I have tracked this down to how sequelize seems to generate a subquery and puts the LIMIT in that subquery instead of in the parent query. See below for the SQL it generates. This would mean it would effectively 'look in the first 15 books and then apply the 'Scott' LIKE statement to those 15' even though the database might have hundreds of books. I have simplified the query slightly.

I have also ran a few scenarios where I left out the LIMIT (it works then) but also where I left out the LIKE (it works then as well), but if both are present, wham, no result.

```
SELECT 
    `Book`.*
FROM 
    (
        SELECT 
            `Book`.*
        FROM 
            `books` AS `Book` 
        WHERE 
            (
                `Book`.`deleted_at` >= CURRENT_TIMESTAMP 
                OR `Book`.`deleted_at` IS NULL
            ) 
            AND (
                SELECT 
                    `j_author_book`.`author_id` 
                FROM 
                    `j_author_book` AS `j_author_book` 
                    INNER JOIN `authors` AS `Author` ON `j_author_book`.`author_id` = `Author`.`id` 
                WHERE 
                    (
                        `Book`.`id` = `j_author_book`.`book_id`
                    ) 
                LIMIT 
                    1
            ) IS NOT NULL 
        ORDER BY 
            `Book`.`title` asc 
        LIMIT 
            0, 15 # <---- THIS IS THE PROBLEM
    ) AS `Scenario` 
    INNER JOIN (
        `j_author_book` AS `authors.j_author_book` 
        INNER JOIN `authors` AS `authors` ON `authors`.`id` = `authors.j_author_book`.`author_id`
    ) ON `Book`.`id` = `authors.j_author_book`.`book_id` 
    AND (
        (
            `authors`.`deleted_at` >= CURRENT_TIMESTAMP 
            OR `authors`.`deleted_at` IS NULL
        ) 
        AND `authors`.`name` LIKE '%Scott%'
    ) 
ORDER BY 
    `Book`.`title` asc
```

**Dialect:** mysql (not tested with anything else)
**Database version:** MySQL 5.6
**Sequelize version:** Most recent build on github: https://github.com/sequelize/sequelize/commit/cc4ee8b86f656f9706e1dbf3a5d5600333f8975b 
## Why I referenced the other issue at the top

The situation seems more or less the same and adding 'duplicating: false' to the include DOES fix it, because it will remove the subquery. That issue did not seem to actually lead to a fix for the problem though. My opinion is that sequelize is placing that LIMIT in the wrong place and using 'duplicating: false' to work around it does not seem like a solution to me. With all due respect of course. :)

**Comment by janmeier** [comment]
Did you test that duplicating gives the correct number? Did you have a book with multiple authors?

The problem is that adding a limit to the outer query will limit the rows from the cartesian join (multiple rows for each book) which means you might end up with fewer than 15 unique books. 

`duplication: false` tells sequelize that you expect there to never be any duplication, i.e. only one author for each book. But if that is always the case, the association might as well be `1:m`, in which sequelize would handle it correctly

**Comment by saekort** [comment]
Duplicating gives the correct number. I think that is because the subquery is not really neccesary.

I had books with multiple authors, authors with multiple books, but not authors with more then one association to a book (that seems like a weird thing).

The thing is that while the Book + Author example might indeed have `1:m`, the situation occurs when you could have more then one relation, so 1 Book had 3 or 4 relations to the same Author. Then I would not be able to use `duplication: false` and I would not be able to workaround it. If you know what I mean?

**Comment by janmeier** [comment]
```js

var Book = sequelize.define('book');
var Author = sequelize.define('author');

Author.belongsToMany(Book, { through: 'j_author_book'});
Book.belongsToMany(Author, { through: 'j_author_book'});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() =>  Promise.join(
    Book.create(),
    Book.create(),
    Author.create(),
    Author.create()
  ))
  .spread((b1, b2, a1, a2) => b1.setAuthors([a1, a2]).return(b1))
  .then(() => Book.findAll({
    limit: 2,
    include: [ {model: Author, duplicating: false}]
  }))
  .then(books => {
    console.log(books.length)
  })
  .finally(() => sequelize.close());
```

The sub-query is definitely necessary - In the above example, duplicating: true gives 2 rows, while false gives 1 row.

I see how the result you are getting right now is not correct either, but the solution is not as easy as moving the limit to the outer query

**Comment by saekort** [comment]
I concur that the solution is not that easy. :) I just wanted to bring to your attention that it does seem to be a 'issue'. One that I can work around, but it seemed fair to inform those that build this great tool on a regular basis. :)

**Comment by suksin** [comment]
Anyone found a solution for this?

**Comment by Kumagor0** [comment]
@suksin subQuery: false did the trick for me. https://github.com/sequelize/sequelize/issues/1756#issuecomment-54748245

**Comment by mrded** [comment]
I also noticed, that if you have two includes, both must have `duplicating: false`.

```
var Book = sequelize.define('book');
var Author = sequelize.define('author');
var Language = sequelize.define('language');

Book.belongsToMany(Author, { through: RefBookAuthor, as: 'authors' });
Book.belongsToMany(Language, { through: RefBookLanguage, as: 'languages' });
```

Following call will give an error:
```
Book.findAll({
  limit: 2,
  include: [
    {model: Author, duplicating: false},
    {model: Language}
  ]
}))
```

> SequelizeDatabaseError: Unknown column 'authors->RefBookAuthor.book_id' in 'field list'

**Comment by mrded** [comment]
I think, it make senses to reopen the issue.

The question is: How? :)

**Comment by sangkwonlim** [comment]
https://github.com/sequelize/sequelize/issues/1756#issuecomment-445920187
