### ISSUE TITLE
Cannot eager load associated models with default scope

### ISSUE THREAD

**Issue by guidsen** [sequelize/sequelize#6074]
Version: 3.19.3

When I query a User I always need the associated Network models. For the Network models I also always need the Integration model. But when I query a User I receive the following error:
`Error: Integration is not associated to Network!` When I query a Network model itself and include the Integration relationship, it's working fine. In this case I need a collection of Network models with the associated Integration models, instead of a single Network model.

My models looks like this.

```
model.define('User', {
  username: {
    type: Sequelize.STRING,
    allowNull: false,
  },
}, {
  tableName: 'users',
  timestamps: true,
  defaultScope: {
    include: [{ model: Network }],
  },
});
```

```
model.define('Network', {
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
}, {
  tableName: 'networks',
  defaultScope: {
    include: [{ model: Integration, required: false }],
  },
});
```

This is how I define the relationships between the models.

```
User.belongsToMany(Network, {
  foreignKey: 'user_id',
  otherKey: 'network_id',
  through: 'network_user',
  timestamps: false,
});

Network.belongsToMany(Integration, {
  foreignKey: 'network_id',
  otherKey: 'service_id',
  through: 'network_service',
  timestamps: false,
});
```

**Comment by janmeier** [comment]
When both models are depent on each other, you cannot define the default scope for both at definition time - One model needs to be completely defined first. 

Try using `addScope` http://docs.sequelizejs.com/en/latest/api/model/#addscopename-scope-options after the models have been imported, same places as you define the associations
