### ISSUE TITLE
Refactor of tests

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6084]

**Comment by sushantdhiman** [comment]
I think this one need more than just ES6 conversion. We need to come up with a proper structure to organize tests. Currently some files like `findAll` tests have more than 2-3k lines. We are also suffering from duplicate tests, unorganized tests. A few tests are in different files others in different section entirely.

These should be our targets 

- Organize tests so one type of tests should be placed together
- Divide tests so no file become a big giant test
- Add tests to conform our API layer so issue like #5999 are caught early on
- Convert most of tests to unit tests where possible

If anyone else want to work on it then they are welcome to do so. But if no one has time to refactor tests and re-group them I can start working on them.

**Comment by felixfbecker** [comment]
We should also use BDD (`describe`/`it`) interface consistently. Currently in some places TDD is used (`suite`/`test`).

**Comment by mickhansen** [comment]
@felixfbecker When you're testing stuff like SQL generation BDD is wrong in my opinion, we'll have thousands of assertions ideally, but they don't exactly fit to a behaviour `it should generate SQL equaling this very long line`

**Comment by mickhansen** [comment]
@sushantdhiman I don't see how #5999 would have been caught? It's a matter of an extensive test suite, no matter how hard you try you never catch all cases the first go around.

I totally agree on test organization, but it's hard to maintain as you add more and more cases.

**Comment by felixfbecker** [comment]
@mickhansen Could you give an example of such a test? Imo what you describe (_it should generate SQL equaling this very long line_) is not what comes in the `it` description, but in the assertions, and you can have multiple assertions per `it` block.

**Comment by mickhansen** [comment]
@felixfbecker `test/unit/sql`

**Comment by felixfbecker** [comment]
@mickhansen Imo it _would_ be possible to write them with BDD but it is probably not worth the effort.
But really the main point is the ES6 refactor so we can switch to ESLint and enforce the ES6 style in the whole lib.
