### ISSUE TITLE
Replace lodash.template with ES6 template strings

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6085]
- `AbstractQueryGenerator`
  - [x] `insertQuery`
  - [x] `bulkInsertQuery`
  - [ ] `updateQuery`
  - [ ] `incrementQuery`
- `MySqlQueryGenerator`
  - [ ] `createTableQuery`
- `PostgresQueryGenerator`
  - [ ] `createTableQuery`
  - [ ] `changeColumnQuery`
  - [ ] `renameColumnQuery`
- `MsSqlQueryGenerator` (missing ES6 refactor)
  - [ ] `createTableQuery`
  - [ ] `renameTableQuery`
  - [ ] `dropTableQuery`
  - [ ] `addColumnQuery`
  - [ ] `removeColumnQuery`
  - [ ] `changeColumnQuery`
  - [ ] `renameColumnQuery`
  - [ ] `bulkInsertQuery`
  - [ ] `deleteQuery`
  - [ ] `showIndexesQuery`
  - [ ] `removeIndexQuery`
  - [ ] `dropForeignKeyQuery`
  - [ ] `getDefaultConstraintQuery`
  - [ ] `dropConstraintQuery`

**Comment by joshrickert** [comment]
This looked easy enough so I took a stab at a few of them. Anyone else is free to pick up the torch, or I may keep messing with it.

**Comment by felixfbecker** [comment]
@joshrickert nice. It is a bit more complicated than it seems because with template strings the values are evaluated when the string is created, while with lodash you can first build the template and then evaluate the values later (if that makes sense).

**Comment by felixfbecker** [comment]
Did you open a PR?

**Comment by felixfbecker** [comment]
I also just noticed that I forgot to ES6-refactor the MSSQL `QueryInterface` and `QueryGenerator`

**Comment by joshrickert** [comment]
Yeah, I noticed that. I figured I would get some feedback before I put any significant amount of time into it. No PR yet.

**Comment by joshrickert** [comment]
I have been looking at it more this morning. Another difference in behavior is that ES2015 template literals cast `undefined` to `'undefined'` whereas `_.template` cast it to `''`. Something to watch out for.

**Comment by joshrickert** [comment]
Hey, it's been a while, but I am still working on this. My current progress on [my working branch](/joshrickert/sequelize/tree/6085-template-literals) vs your checklist:
- Finished everything in `PostgresQueryGenerator`
- Finished everything in `MsSqlQueryGenerator` **except**:
  - [ ] `createTableQuery`
  - [ ] `bulkInsertQuery`

I also addressed all of your comments you left on the commits. Appreciate the feedback.

Should I open a PR while I continue to work on it?

**Comment by janmeier** [comment]
Sure - We can also merge the changes in several smaller steps - Makes it easier if there are merge conflicts
