### ISSUE TITLE
Benchmark ES6 refactor

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6086]
I would love to see if the native classes, arrow functions instead of `bind()` and some arrow functions instead of `lodash.template()` improved performance. Could someone do this?

**Comment by sushantdhiman** [comment]
I dont think we need to open an issue for this :)

**Comment by felixfbecker** [comment]
Why not? I thought it would be a good place for someone to paste the results and it should definitely be done given the refactor pretty much completely changed every single file in the lib.

**Comment by sushantdhiman** [comment]
**Without ES6**
![machine 1 - without es6](https://cloud.githubusercontent.com/assets/9989487/16195419/26ac798c-3717-11e6-8b69-4d25fe986ad6.png)

**With ES6**
![machine 1](https://cloud.githubusercontent.com/assets/9989487/16195420/26b9fe5e-3717-11e6-90f5-ea4037511ab2.png)

Yup there are improvements in throughput @felixfbecker ,You can use benchmark tool to further test it
