### ISSUE TITLE
insert query conditional

### ISSUE THREAD

**Issue by cly19891215** [sequelize/sequelize#6087]
Hi all,

 INSERT query that only executes if the number of rows satisfying some condition already in the table is less than 20, and fails otherwise?

The SQL looks like,

INSERT INTO TargetTable(Column1, Column2, ...)
    SELECT 'Value For Column 1', 'Value For Column 2', ..
     WHERE (SELECT COUNT(*) FROM TargetTable WHERE ...Some Condition...) < 20;

How can I do this query with sequelizejs?

Thanks~~

**Comment by sushantdhiman** [comment]
I dont see how you can achieve this in single shot using Sequelize. But you could to this with [transactions](http://docs.sequelizejs.com/en/latest/docs/transactions/).

```js
return sequelize.transaction(function(t) {
    return User.count({
        where: { /* conditions */ },
        transaction: t
    })
    .then((count) => {

        if (count < 20) {
             return User.bulkCreate([
                  { name: 'naruto' },
                  { name: 'sasuke' }
             ], { transaction: t  })
        }
   });
});


```

**Comment by sushantdhiman** [comment]
You will have to commit or rollback as required

**Comment by cly19891215** [comment]
Hi Sushantdhiman,

Thanks for you update.

If I do this with transactions, it will have a 'race condition' issue. When count = 19, and there are two transactions begin at the same time, then both of them will be commited.

If I use the subquery, it can prevent the 'race condition' issue, because the subquery is atomic.

Thanks~~

**Comment by janmeier** [comment]
@cly19891215 You can set a higher isolation level so that only one transaction can insert at a time - But that is a general SQL issue, not a seqeulize issue
