### ISSUE TITLE
on association not updating?

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#6088]
beforeUpdate: function(self) {
        if (self.changed('password')) {
          self.hashPassword();
          self.updateJwt();
        }
        if (self.changed('email')) {
          self.generateEmailVerificationToken();
        }
        if (self.changed('PermissionRoleId')) {
          self.updatePermissionRoleUpdatedAt();
          console.log(self.permissionRoleUpdatedAt);
        }
      }

So, I'm using `(self.changed('PermissionRoleId'))` and, i'm logging it to the console, and the column value is being updated, however it's still NULL in the database?

Note: PermissionRoleId is an associated column

**Comment by janmeier** [comment]
Please show the full model definition with relevant methods and test data ([SSCCE](HTTP://SSCCE.ORG/))
