### ISSUE TITLE
Allow foreignKey filed name and column name definition

### ISSUE THREAD

**Issue by ssljivic** [sequelize/sequelize#6094]
## What you are doing?
When association is defined like below sequelize will expect column with name 'image_type_id' to exists in the 'image' table and will add a field in the Image model instance with name 'image_type_id'.

```js
Image.belongsTo(ImageType, {
	foreignKey: {
		name: 'image_type_id'
	},
	as: 'imageType'
});
```

## What do you expect to happen?
I would like to be able to separately define model filed name and table column name, so that I do not have to use snake case column names in sequelize queries.

## What is actually happening?
The name of the model field is 'image_type_id' instead of 'imageTypeId'.

Something like would be ok:

```js
Image.belongsTo(ImageType, {
	foreignKey: {
		name: 'image_type_id',
		fieldName: 'imageTypeId'
	},
	as: 'imageType'
});
```

__Dialect:__ postgres
__Database version:__ 9.4.4
__Sequelize version:__ 3.23.3

**Comment by mickhansen** [comment]
Define the foreign key on the model and target it with `foreignKey`

**Comment by ssljivic** [comment]
I do not understand. Can you please give an example @mickhansen ?

**Comment by ssljivic** [comment]
OK, I see what you think. I will post an example, so that we have this documented at least here, since sequelize doc is not very clear about this.

**Comment by ssljivic** [comment]
It should be mapped like this:

```js
sequelize.define('Image', {
	id: {
		field: 'image_id',
		type: DataTypes.BIGINT,
		allowNull: false,
		primaryKey: true,
		autoIncrement: true
	},
	//...
	imageTypeId: {
		field: 'image_type_id',
		type: DataTypes.BIGINT
	}
}, {
	tableName: 'image',
	classMethods: {
		associate: function (models) {
			models.Image.belongsTo(models.ImageType, {
				foreignKey: {
					fieldName: 'imageTypeId'
				},
				as: 'imageType'
			});
		}
	}
});
```

Thanks @mickhansen .

**Comment by mickhansen** [comment]
@ssljivic Mostly correct, you can simply use `foreignKey: 'imageTypeId'`

**Comment by weldermarcosxd** [comment]
@ssljivic how that association would be defined in ImageType side, Im getting 'model is not associated with model2' no matter hard I try, Thank you.
