### ISSUE TITLE
any way to disable ST_GeomFromGeoJSON for query

### ISSUE THREAD

**Issue by benjaminhon** [sequelize/sequelize#6097]
Hi, 

Is there anyway to disable ST_GeomFromGeoJSON during a query? this is because i need the output as a geojson string, not with the "type" and "coordinates" json keys.

Thanks

**Comment by janmeier** [comment]
You could select the data into another attribute: `attributes: { include: [['geojson_column', 'geojson]]}`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by benjaminhon** [comment]
that does'nt work though,

i did this,
```
MapGeometry.findAll({
      where: {mapName: name}
      attributes: {
        include: [['geometry', 'geojson']]
      }
    })
```

and still got this,
```
{   geometry: { type: 'Polygon', coordinates: [Object] },
    properties: { type: 'geometry', layer: 'rooms' },
    mapName: 'test',
    geojson: { type: 'Polygon', coordinates: [Object] } }
```

as you can see, the value for 'geojson' is still the same as 'geometry'.

in my database, geometry is
```
LINESTRING(-171.123046875 83.8957189346558,-174.462890625 83.9050579559856,-174.462890625 81.2282665600554)
```

is it possible to get it as a string ?
```
"LINESTRING(-171.123046875 83.8957189346558,-174.462890625 83.9050579559856,-174.462890625 81.2282665600554)"
```

**Comment by janmeier** [comment]
As yes, I guess I was thinking mysql here. For postgres the parsing happens in the datatype https://github.com/sequelize/sequelize/blob/3ca87eb97124c2c418885f2902c01e5169509462/lib/dialects/postgres/data-types.js#L303

You could try overriding `Datatypes.postgres.GEOMETRY.parse`, but mind you that this will apply to all  fields and not only this specific one.

I think the easiest would be to just convert the column in question using https://www.npmjs.com/package/wkx or similar

**Comment by benjaminhon** [comment]
ok i see, i tried using a raw query
```
select * from "mapGeometries" where "mapName" = 'test'
```

however, it looks like the geometry data is encoded in its own format
```
01020000000300000000000000F06365C04EB0827553F9544000000000D0CE65C0567C3478ECF9544000000000D0CE65C0588D58EB9B4E5440
```

guess ill have to parse it using wkx

thx :)
