### ISSUE TITLE
Group concat using custom query is trimming the output by 1024 character

### ISSUE THREAD

**Issue by ashishyadav311** [sequelize/sequelize#6098]
## What you are doing?
I am writing a custom query which involves the use of group_concat

// code here
select
....
"group_concat(concat('\"\',`videoPostMeta`.`meta_key`,'\"\:\"\', 
"replace(`videoPostMeta`.`meta_value`,'\"','\^')),'\"\') AS `videoMeta`,
....

## What do you expect to happen?
i want videometa column to contain the full column value

## What is actually happening?
it is trimming the result to 1024 characters,

__Dialect:__ mysql 
__Database version:__ 5.6.23
__Sequelize version:__ 3.23.2

**Comment by janmeier** [comment]
Please create a [SSCCE](HTTP://SSCCE.ORG/) with model definition and test data so we can copy and paste to replicate.

Have you tested if this is also an issue when using raw node-mysql?

**Comment by ashishyadav311** [comment]
I have tested with workbench , it is giving the correct result.

**Comment by janmeier** [comment]
I meant have you tested connecting and executing the query directly with the node mysql driver https://github.com/felixge/node-mysql?

**Comment by ashishyadav311** [comment]
I have tested it on , working fine on it, you can take any wordpress db.
Here is what i did.


    var mysql      = require('mysql');
    var connection = mysql.createConnection({
      host     : 'localhost',
      user     : 'root',
      password : 'root',
      database : 'wordpress'
    });
    connection.connect();

    connection.query(" SELECT      `post`.`ID` AS `id`,GROUP_CONCAT(CONCAT('\"',                 `videoPostMeta`.`meta_key`,                 '\":\"',                 REPLACE(`videoPostMeta`.`meta_value`,                     '\"',                     '^')),         '\"') AS `videoMeta` FROM     `wp_posts` AS `post`            INNER JOIN     `wp_term_relationships` AS `category.wp_term_relationships` ON `post`.`ID` = `category.wp_term_relationships`.`object_id`         INNER JOIN     `wp_term_taxonomy` AS `category` ON `category`.`term_taxonomy_id` = `category.wp_term_relationships`.`term_taxonomy_id`         AND `category`.`taxonomy` = 'category'         AND `category`.`term_taxonomy_id` != '1'         AND (`category`.`term_id` IN (1622)         OR `category`.`parent` IN (1622))      LEFT OUTER JOIN     `wp_postmeta` AS `postMeta` ON `post`.`ID` = `postMeta`.`post_id`         AND `postMeta`.`meta_key` = '_thumbnail_id'         LEFT OUTER JOIN     `wp_posts` AS `postMeta.post` ON `postMeta`.`meta_value` = `postMeta.post`.`ID`         LEFT OUTER JOIN     `wp_postmeta` AS `postMeta.post.postMeta` ON `postMeta.post`.`ID` = `postMeta.post.postMeta`.`post_id`         AND `postMeta.post.postMeta`.`meta_key` = '_wp_attachment_metadata'         LEFT OUTER JOIN     `wp_postmeta` AS `videoPostMeta` ON `post`.`ID` = `videoPostMeta`.`post_id`         AND `videoPostMeta`.`meta_key` IN ('video_url' , 'video_transcript', 'video_poster_image')         LEFT OUTER JOIN     `wp_postmeta` AS `newsBytesMeta` ON `post`.`ID` = `newsBytesMeta`.`post_id`         AND `newsBytesMeta`.`meta_key` IN ('media_name' , 'media_logo_image_link') WHERE     `post`.`post_status` IN ('publish' , 'inherit')         AND `post`.`post_type` IN ('post' , 'attachment') GROUP BY `post`.`ID` ORDER BY `post`.`menu_order` DESC", function(err, rows, fields) {
      if (err) throw err;

      console.log('!!!!!!############&&&&&&&&&&&&&&&&&&The solution is: ', JSON.stringify(rows));
    });

    connection.end();

**Comment by janmeier** [comment]
Well, I don't have any wordpress DB on hand (and please don't send me one ...)

What I need to be able to reproduce the issue is a copy-pasteable testcase with model definition and data - [SSCCE](HTTP://SSCCE.ORG/)

**Comment by ashishyadav311** [comment]
table post_meta;
+----+---------------+---------------+  
| ID |  meta_key  |	meta_value   |  
+----+---------------+---------------+-
|  1 |  sample_data3 |  sample_value2 |  
|  1 |  sample_data1 |  sample_value4 |  
|  1 |  sample_data1 |  sample_value2 |  
|  1 |  sample_data2 |  sample_value1 |    
|  1 |  sample_data3 |  sample_value2 |  
|  1 |  sample_data1 |  sample_value4 |  
|  1 |  sample_data1 |  sample_value2 |  
|  1 |  sample_data2 |  sample_value1 |  
|  1 |  sample_data3 |  sample_value2 |  
|  1 |  sample_data1 |  sample_value4 |  
|  1 |  sample_data1 |  sample_value2 |
+----+---------------+----------+----


 SELECT ID ,GROUP_CONCAT(CONCAT('\"', `meta_key`,'\":\"',`meta_value`)) FROM post_meta GROUP BY ID;

hope this explain my problem

**Comment by janmeier** [comment]
Still not a copy-paste able test case - Please provide some javascript code that I can copy and paste to replicate the issue

**Comment by ashishyadav311** [comment]
table post_meta defination;
+----+---------------+---------------+

| ID | meta_key | meta_value |

+----+---------------+---------------+-
| 1 | sample_data3 | sample_value2 |

| 1 | sample_data1 | sample_value4 |

| 1 | sample_data1 | sample_value2 |

| 1 | sample_data2 | sample_value1 |

| 1 | sample_data3 | sample_value2 |

| 1 | sample_data1 | sample_value4 |

| 1 | sample_data1 | sample_value2 |

| 1 | sample_data2 | sample_value1 |

| 1 | sample_data3 | sample_value2 |

| 1 | sample_data1 | sample_value4 |

| 1 | sample_data1 | sample_value2 |
+----+---------------+----------+----

var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'root',
  database : 'wordpress'
});
connection.connect();

connection.query("SELECT ID ,GROUP_CONCAT(CONCAT('\"', meta_key,'\":\"',meta_value)) FROM post_meta GROUP BY ID;", function(err, rows, fields) {
  if (err) throw err;

  console.log('The solution is: ', JSON.stringify(rows));
});
connection.end();




now what happens id that when the value of 2nd column exceed 1024 , it chops off the remaining string.

**Comment by mickhansen** [comment]
Provide code runnable in https://github.com/sequelize/sequelize/blob/master/sscce_template.js.
Showing code that runs with node-mysql does not really help you or us.

**Comment by janmeier** [comment]
http://stackoverflow.com/questions/2567000/mysql-and-group-concat-maximum-length

**Comment by ashishyadav311** [comment]
@janmeier when i am running this custom query through workbech or terminal it is giving the correct result and even with the node-mysql , but when i am running this raw query through sequilize it is trimming the result.

sequelize.query("SELECT ID ,GROUP_CONCAT(CONCAT('\"', meta_key,'\":\"',meta_value)) FROM post_meta GROUP BY ID;", { type: sequelize.QueryTypes.SELECT})
  .then(function(users) {
//do something
  })

**Comment by janmeier** [comment]
Sequelize does _nothing_ to chop of the value, and since the length matches exactly the default limit I'm having a very hard time believing sequelize is doing something here http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_group_concat_max_len

**Comment by ashishyadav311** [comment]
I have already seen the stackoverflow answer that you have sent me.
here is the value for it .
![screen shot 2016-06-14 at 3 39 44 pm](https://cloud.githubusercontent.com/assets/7725704/16039236/48223b90-3246-11e6-91f8-9875d95272a8.png)

**Comment by janmeier** [comment]
Group concat max len _is_ the issue - Raising it fixes the problem for me `sequelize.query(`SET @@group_concat_max_len = 2048`)`
