### ISSUE TITLE
Enable test shims

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#6104]
PR #5836 fixed the tests shims and updated them to also check that `options` object is never altered by Sequelize methods.

At present the shims are not enabled though and do not run on Travis. The concern was that the shims increase Travis run times considerably.

Just opening an issue so this doesn't get forgotten.

It'd be ideal if at least:
1. the shims run on Travis for one node version (or even one node version/db dialect combination); or
2. the shims are run and any bugs exposed are fixed before releases to npm

(2) has the disadvantage that fixing any bugs will fall upon Sequelize's maintainers, rather than authors of the PRs which introduced bugs.

**Comment by overlookmotel** [comment]
I'd like to keep this issue open for now.

**Comment by overlookmotel** [comment]
I'd like to keep this issue open for now.

**Comment by overlookmotel** [comment]
I'd like to keep this issue open for now.

**Comment by overlookmotel** [comment]
I'd like to keep this issue open for now.

**Comment by papb** [comment]
@overlookmotel What is the status on this?

**Comment by ephys** [comment]
I think this is so outdated I don't even know what it's about :p
