### ISSUE TITLE
Methods are not properly generated when mixing camelCase and snake_case

### ISSUE THREAD

**Issue by Freezystem** [sequelize/sequelize#6105]
I'm trying to join table with `.hasMany()` and  `.belongsTo()` methods using camelCase variable name and snake_case named table.
So here is my code: 

```js
const Campaign = DB.define('campaigns', {...});
const CampaignType = DB.define('campaign_types', {...});

// Campaign 1<->n CampaignType
Campaign.hasMany(CampaignType, { onDelete : 'cascade' });
CampaignType.belongsTo(Campaign);
```

Later I'm trying to use `.createAssociation()` methods on the objects and I get this error

```js
DB.models.create.Campaign({...})
  .then(( campaign ) => {
    campaign.createCampaignType({...}); 
    // Unhandled rejection TypeError: campaign.createCampaignType is not a function
  });
```

I can mitigate the issue by using camelCase name for `campaign_types` table, but I'd like to stick to camelCase for Variable and snake_case for tables:
```js
const CampaignType = DB.define('campaignTypes', {...});
```
I wonder if I'm doing something wrong or if its a known limitation.

__Dialect:__ postgres
__Database version:__ 9.5.3
__Sequelize version:__ 3.23.3

**Comment by janmeier** [comment]
Its a known limitation of sorts - We choose to be slightly stupid when generating names, as opposed to trying to be clever and ending up in weird egde-cases. 

You can mitigate it by using `as: 'campaignTypes'`

**Comment by Freezystem** [comment]
Ok thanks a lot. 
I was aware of the `as` attribute as I'm actually using it somewhere else but I didn't think of using it this way.
