### ISSUE TITLE
Large query blocks the node process

### ISSUE THREAD

**Issue by valgayres** [sequelize/sequelize#6110]
Hi everybody, 

I'm using sequelize for around two, and I noticed that when loading several records at the same time, the server blocks during (I guess) the parsing of the sql response (I observed this in production, but I have the same issue with in local)

I'm using postgres 9.4.5, and sequelize 3.19.3.

The query for which I observed this issue is the following.

Let assume that I have the following models:
  - Company  - 3 columns
  - Customer - 15 columns, including a `company_id`, `date` (type `DataTypes.DATEONLY`), and `active` (type `DataTypes.BOOLEAN`)
  - Order        - 15 columns, including a `company_id`, and `date` (type `DataTypes.DATEONLY`)

I have the following function in company:

```
function getDatas(companyId, date, callback){
    this.findById(companyId, {
        include: [
            {
                model: Customer,
                where: { date: date },
                required: false
           },
           {
                model: Order,
                where: { date: date },
                required: false
            }
        ]
    }).then(callback)
}
```

The query looks like : 
```
    Executing(default): SELECT "Company"........................... 
    FROM "companies" AD "Company" 
    LEFT OUTER JOIN "customers" AS "Customers" ON "Company"."id" = "Customers"."company_id" AND "Customers"."date" = '2016-02-01' AND "Customers"."active" = true 
    LEFT OUTER JOIN "orders" AS "Orders" ON "Company"."id" = "Orders"."company_id" AND "Orders"."date" = '2016-02-01'
    WHERE "Company"."id" = 1;
```

For the `date` and `companyId` I use, I retrieve around 250 customers and 470 orders.

I don't think that there is an impact, but I have several `classMethods` and `instanceMethods` on both "classes" (between 3 and 8 of each).

I reproduced visually the problem with the following code that I have executed in a node process in a terminal

```
var date = "2016-02-01";
var saasOfficeId = 1;
var datas;

setInterval(function(){console.log('waiting', new Date())},200);
function callback(company){console.log('finished', new Date()); datas = company}

Company.getDatas(companyId, date, callback)
```

The console output is the following: 

```
waiting Tue Jun 14 2016 15:13:22 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:22 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:23 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:23 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:23 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:23 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:23 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:24 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:24 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:24 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:24 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:24 GMT+0200 (CEST)
finished Tue Jun 14 2016 15:13:35 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:35 GMT+0200 (CEST)
waiting Tue Jun 14 2016 15:13:36 GMT+0200 (CEST)
```

As we can see, between the "finished" lines and the previous "waiting" line, there is around 11s.....

Is this a known issue, or maybe only a configuration option that I failed to add?

I hope the description is clear.

Thanks a lot!
Vincent

**Comment by mickhansen** [comment]
Parsing of results (including deduplication which can be expensive) is blocking.
How many rows is your query returning? (when run raw, not through sequelize)

**Comment by valgayres** [comment]
Hi mickhansen,

Ok, so that explains this... Executing the query directly, I realised that it returned around 115k individual rows (which is logical, given that at the end there are  250 customers and 470 orders...).

I guess was too much used to rails `includes(association)` that eager load through several queries to think about what real queries were behind.

I just tried to use async.parallel to the the three queries, and I got the result almost immediately without any blocking

Thanks a lot for the quick answer!

**Comment by mickhansen** [comment]
@valgayres If it's a hasMany association you can try out  `include.separate` which will make it run in a separate query.

**Comment by valgayres** [comment]
@mickhansen Just checked this option, it's exactly what I want.

Thanks a lot!

**Comment by mickhansen** [comment]
Great :) We hope to add it for belongsToMany soon, and likely make it the default in the future.
