### ISSUE TITLE
Auto increment doesn't work.

### ISSUE THREAD

**Issue by abelbarbosa** [sequelize/sequelize#6112]
I'm trying to create a nested entity in Postgres with sequelize but it only works the first execution. My models:

CategoryGroup.js:
```
module.exports = function (sequelize, DataTypes) {
  var CategoryGroup = sequelize.define("categoryGroup", {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    }
   /*attributes*/
  }, {
      classMethods: {
        associate: function (models) {
          CategoryGroup.hasMany(models.categoryGroupDetail)
        }
      }
    });

  return CategoryGroup;
};
```
CategoryGroupDetail .js:
```
module.exports = function (sequelize, DataTypes) {
    var CategoryGroupDetail = sequelize.define("categoryGroupDetail", {
        id: {
            type: DataTypes.INTEGER,
			autoIncrement: true,
            primaryKey: true
        },
        /*attributes*/
    });

    return CategoryGroupDetail;
};
```

```js
return models.sequelize.transaction(function (t) {
        return models.categoryGroup.create({
            name: req.body.name,
            showOnMenu: req.body.showOnMenu,
            showOnFilters: req.body.showOnFilters,
            categoryGroupDetails: req.body.categoryGroupDetails
        }, {
                include: [models.categoryGroupDetail],
                transaction: t
            });
    }).then(function (result) {
        //success
    }).catch(function (error) {
        //rollback
    });
```

The code is supposed to create a CategoryGroup with several CategoryDetails.

It only works the first time. After that I get an validation error. When I checked the queries being executed I saw that the second insert is not using an incremented id but always "1".

INSERT INTO "categoryGroups" ("id","name","showOnMenu","showOnFilters") VALUES (DEFAULT,'Material',false,true) RETURNING *;
INSERT INTO "categoryGroupDetails" ("id","name","slug","description","categoryGroupId","languageId") VALUES (1,'Material','material',NULL,5,'pt_PT') RETURNING *;

__Dialect: postgres
__Database version: 9.5.3
__Sequelize version: 3.23.2

**Comment by janmeier** [comment]
Have you checked the data in req.body to see if it includes id? 

Please create a completely self contained test case, with test data

**Comment by abelbarbosa** [comment]
Oops. Thank you Jan Meier you are correct. I never thought the problem was on the client side. It was passing an id in the request that was being used for presentation purposes.

I'm sorry and thank you for your time.

Best regards.
