### ISSUE TITLE
parseLengthCodedNumber: JS precision range exceeded, number is >= 53 bit: 

### ISSUE THREAD

**Issue by yuxichina** [sequelize/sequelize#6113]
Error：
parseLengthCodedNumber: JS precision range exceeded, number is >= 53 bit: 

filed id  primaryKey， bigint（12）

Use model.create fun， throw error ， but data already created in db.

 
__Dialect:__ mysql 
__Database version:__ XXX
__Sequelize version:__ 3.21.0

**Comment by sushantdhiman** [comment]
My guess would be that table `last insert id` is a signed number. This might help you https://github.com/felixge/node-mysql/issues/1205 , I think this is a `node-mysql` issue.

Please post full error stack trace and data that is created in table.

**Comment by sushantdhiman** [comment]
`mysql` precision issue was solved in https://github.com/sequelize/sequelize/pull/5905, Can you try with `master` branch?

**Comment by sushantdhiman** [comment]
@yuxichina It seems to be numerical overflow issue solved in https://github.com/sequelize/sequelize/pull/5905, Let me know if your code doesn't work with `master`
