### ISSUE TITLE
Feature Request: prefix table names

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#6119]
I'd personally like to see the ability to prefix table names.
I was thinking perhaps an option in the config.

This would benefits me as I have multiple tables from different applications, all accessing the same database. It'd be nice and easy for me to just quickly glance at the tables and see which table is associated with which app.

**Comment by mickhansen** [comment]
Can be solved by using a `beforeDefine` hook to apply prefixes.

**Comment by KieronWiltshire** [comment]
@mickhansen why is that hook not documented?

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/api/hooks/

**Comment by janmeier** [comment]
(I'm not saying the documentation could not be better, just that no-one has had the time to make it better yet :) )

**Comment by KieronWiltshire** [comment]
@janmeier oh my apologies, It isn't included here: http://docs.sequelizejs.com/en/latest/docs/hooks/

**Comment by medmin** [comment]
It's March 17th, 2019 today.

Unfortunately, the documentation  about beforeDefine is still missing. 

It's kind of an important feature to add a prefix to a table name.

**Comment by ryanburnette** [comment]
I could really use `beforeDefine`. Does anyone have a code sample they could link up demonstrating the usage?
