### ISSUE TITLE
findAnCount for subQuery returns count which is an array of ids

### ISSUE THREAD

**Issue by matthewarkin** [sequelize/sequelize#6121]
## What you are doing?
I have this query (if the actual models are needed I can paste them in, or they're also in #6099)
```js
 var query = {
    limit: 10,
    where: {},
    include: [{model: db.FinancialCompany, through:{where:{address_zip:req.query.zip}}, required:true}, {model: db.Disclosure, required: false}],
    order: [['last_name', 'ASC']],
    group: [ 'FinancialProfessional.id'],
    subQuery: true
  }
  db.FinancialProfessional.findAndCount(
      query
  ).then(function (professionals) {
    res.jsonp(professionals);
    return professionals;
  })
}
```

## What do you expect to happen?
When I set `subQuery: false` in the `.then()`, `professionals.count` is an integer

## What is actually happening?
`professionals.count` is an array of objects: `{"count":[{"count":"1","id":2781},{"count":"1","id":3032},...], "rows":...}`

__Dialect:__ postgres
__Database version:__9.5.2
__Sequelize version:__ 3.23.3

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/6148
