### ISSUE TITLE
Get rid of tablename from column name when joining

### ISSUE THREAD

**Issue by keyursakaria** [sequelize/sequelize#6122]
```
DB.Event.belongsTo(DB.AppUser, {foreignKey : 'user_id', targetKey : 'id'});

DB.Event.findAndCountAll({
                            where : conditions,
                            attributes : {exclude : ['created_at', 'updated_at', 'active']},
                            offset : count, limit : 25,
                            logging : false,
                            include : [{
                                model : DB.AppUser,
                                // as: 'user',
                                required : true, // converts left outer to inner join
                                attributes : ['first_name', 'last_name', 'image'],
                                where : {
                                    active : 1
                                }
                            }],
                            raw : true
                        });                   
```

This works fine. The result i get is mixture of two tables. Now the problem is the second table data is in tablename.columnname 

`{
 "notify_prev_venue": 1,
"link_third_party": 0,
"third_party_id": "",
 "event_picture": "",
 "location": "Mumbai",
 "publish": 1,
 "ev_app_user.first_name": "asd",
  "ev_app_user.last_name": "sakaria",
 "ev_app_user.image": "profile_pic/146538004870564252.jpeg",`
}

i want to get rid of tablename ev_app_user from the key 

Any suggestions on how to accomplish this

Thanks

**Comment by janmeier** [comment]
If you want us to do mapping, don't use `raw`.

We need to prefix attributes with table name in includes, because the two tables might have columns with the same name (e.g. they might both have `createdAt` etc - If we don't prefix, the value from one will overwrite the other. If you need if without prefix, you'll need to do the mapping yourself
