### ISSUE TITLE
findAndCountAll with null nested field

### ISSUE THREAD

**Issue by vangoz** [sequelize/sequelize#6123]
I need to left join to a table and check with `is null`, so I do it with nested field. 

```js
clause.include = [{
  model: 'Table',
  required: false
}]
clause.where['$Table.x$'] = null;
```
The query works as expected with findAll(), however with findAndCountAll() it returns error
`The multi-part identifier \"Table.x\" could not be bound."`.

I think it happens because the count query does not do the actual join because of `required: false`.

**Comment by janmeier** [comment]
Please create a complete [SSCCE](HTTP://SSCCE.ORG/)
