### ISSUE TITLE
defaultScope as function

### ISSUE THREAD

**Issue by hendrul** [sequelize/sequelize#6126]
PR #5772  seems as an attemp made by someone else, but it should call the defaultScope function each time, not at initialization only.
Well the issue for me comes when I want to make a defaultScope  from other scopes I need a function like this:
```javascript
//Currency.js
{ 
 //...
defaultScope: function() {
  return {
    include: this.scopes.includeExchanges().include.concat( 
             this.scopes.includeSystemDefaults().include )
  }
},
scopes: {
  includeExchanges: function(where) {
    return {
      include: [
        {
          as: 'exchanges',
          model: models.CurrencyExchange,
          required: false,
          where: where||{}
        }
      ]
    }
  },
  includeSystemDefaults: function() {
    return {
      include: [
        {
          as: 'systemDefaults',
          model: models.SysCurrency,
          required: true
        }
      ]
    }
  }
},
```
Where by the way I need to manually merge the includes because the scope's merging mecanism does not support that case.

**Comment by hendrul** [comment]
Scopes as objects are useless for includes where you need to have your models already defined

**Comment by janmeier** [comment]
You can use [`addScope`](http://docs.sequelizejs.com/en/latest/api/model/#addscopename-scope-options) to add scopes that depend on other models being defined. I really don't think the added complexity of allowing defaultScope to be a function is worth the trouble

**Comment by hendrul** [comment]
Ok, I did the following, use functions as defaultScope and after defining all models I run it's associations and replace all defaultScope's functions with the result of calling it.
