### ISSUE TITLE
ExpressJS integratrion?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6128]
Here you write something about integration http://docs.sequelizejs.com/en/1.7.0/articles/express/
That's not bad, but the version is 1.7.0

And here you don't write about ExpressJS integration at all https://readthedocs.org/search/?q=express&check_keywords=yes&area=default&project=sequelize&version=latest&type=file

Does your plugin latest version work with ExpressJS?

**Comment by sushantdhiman** [comment]
Yes Sequelize do work with Express JS or any other framework. A detailed example https://github.com/sequelize/express-example

**Comment by mickhansen** [comment]
Why would it NOT work with Express? :)
