### ISSUE TITLE
ReferenceError: DataTypes is not defined

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6129]
[Here](http://sequelize.readthedocs.io/en/latest/api/datatypes/) we read:

```
sequelize.define('model', {
  column: DataTypes.INTEGER
})
```

When I do the same in my code, I get:

> ReferenceError: DataTypes is not defined

```
const mysql = require('../dataAccessClass').mysql; // mysql is configured sequelize

const UserProfile = mysql.define('user', {
    fname: {
        type: DataTypes.STRING,
        field: 'fname'
    },
    lname: {
        type: DataTypes.STRING,
        field: 'lname'
    },
});
```

How to use `DataTypes` class? Why do you provide info that is not correct, that throws errors?

**Comment by wzup** [comment]
```
const mysql = require('../dataAccessClass').mysql; // mysql is configured sequelize

const UserProfile = mysql.define('user', {
    fname: {
        type: mysql.Sequelize.STRING,
        field: 'fname'
    },
    lname: {
        type: mysql.Sequelize.STRING,
        field: 'lname'
    },
});
```

**Comment by sushantdhiman** [comment]
That example assument the `index.js` based setup like https://github.com/sequelize/express-example/blob/master/models/user.js

If you want to use `define` you need the access `Sequelize` object for datatypes

**Comment by wzup** [comment]
@sushantdhiman 
> If you want to use define

What do you mean? Is there any other way?

**Comment by sushantdhiman** [comment]
@wzup 

Please review https://github.com/sequelize/express-example

Under `/models/index.js` you can see we can also `import` model files. With `define` method you will have to use `Sequelize` object to get access to data-types. But using `import` we inject `Datatype` object for you.
