### ISSUE TITLE
simplify the validation errors array

### ISSUE THREAD

**Issue by odorisioe** [sequelize/sequelize#6130]
Could you consider give an simple array with the  validation messages?
Maybe this is already included but I did not find it. This is how look now:

[ { message: 'Validation isEmail failed',
    type: 'Validation error',
    path: 'email',
    value: [Error: Validation isEmail failed],
    __raw: [Error: Validation isEmail failed] } ]

Would be more simple to include on templates with an array like
field1: message, field2: message

**Comment by JacopoDaeli** [comment]
👍 :thumbsup:

**Comment by janmeier** [comment]
Failed validations are returned as an error object, to make it easier to catch - you can do `foo().catch(Sequelize.ValidationError)`.

If you need field and message you should simply map `err.errors` to produce the structure you want
