### ISSUE TITLE
PSQL queries with groupedLimit associations misquote schemas

### ISSUE THREAD

**Issue by ekosz** [sequelize/sequelize#6131]
## What you are doing?

```js
// Setup
var Sequelize = require('sequelize');
var sequelize = new Sequelize(process.env.DATABASE_URL, { 
  paranoid: false, timestamps: false, freezeTableName: true 
});
var Team = sequelize.define('Team', {}, { schema: 'entity', tableName: 'teams' });
var Goal = sequelize.define('Goal', {}, { schema: 'entity', tableName: 'goals' });
Team.Goals = Team.hasMany(Goal, { foreignKey: 'team_id' });

// The offending code
Team.findAll({ include: [{ model: Goal, limit: 100 }] });
```

## What do you expect to happen?
I expected to get get a list of `teams`, each one having upto 100 `goals`.

## What is actually happening?
Instead, the generated SQL throws an error: 

```
Unhandled rejection SequelizeDatabaseError: relation "entity.goals" does not exist
```

```sql
SELECT "Team"."id" FROM "entity"."teams" AS "Team";
SELECT "Goal".* FROM (
          (SELECT "id", "team_id" FROM "entity.goals" AS "Goal" WHERE "Goal"."team_id" = 1 LIMIT 
100) 
UNION ALL (SELECT "id", "team_id" FROM "entity.goals" AS "Goal" WHERE "Goal"."team_id" = 2 LIMIT 100)
) AS "Goal";
```

As you can see its trying to pull data from `"entity.goals"`. 
It should instead be correctly quoting the schema as `"entity"."goals"`

__Dialect:__ postgres
__Database version:__ psql (PostgreSQL) 9.4.4
__Sequelize version:__ 3.23.3

Related Issue: https://github.com/mickhansen/graphql-sequelize/issues/253

**Comment by ekosz** [comment]
Looking through the code, it seems most likely to be a bug with [`groupedLimit`s in the `query-generator`](https://github.com/sequelize/sequelize/blob/v3.23.3/lib/dialects/abstract/query-generator.js#L1420-L1442). But I don't know the codebase well enough to pinpoint the issue past that.

**Comment by ekosz** [comment]
Looking further I've traced the code to https://github.com/sequelize/sequelize/blob/v3.23.3/lib/dialects/abstract/query-generator.js#L1047 where Sequelize is calling `this.quoteTable('"entity"."goals"')` and its becoming `"entity.goals"`.

This is ultimately done by the [postgres version of `quoteIdentifier`](https://github.com/sequelize/sequelize/blob/v3.23.3/lib/dialects/postgres/query-generator.js#L839-L851) which strip out the `"` signs. But this is where my knowledge stops as I don't know why we would strip the quotes. 

This is a show stopping bug for me using [`graphql-sequlize`](https://github.com/mickhansen/graphql-sequelize). I would love to help fix the bug myself, I just need a bit of guidance.

**Comment by mickhansen** [comment]
Hey @ekosz, if you provide a pull request with a failing unit test i'll look at a fix. It looks like it might be passing along the formatted table where it needs to pass through the raw `Model.getTableName()`

**Comment by ekosz** [comment]
@mickhansen I created a PR here: https://github.com/sequelize/sequelize/pull/6293

**Comment by ekosz** [comment]
@mickhansen Thanks!
