### ISSUE TITLE
[db:migrate] Error: Please install mysql package manually

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6132]
I have everything installed properly. I easily can run `sync()` manually and create tables with models and easily create/delete/update/etc records in tables. But `sequelize db:migrate` throws an error

> Error: Please install mysql package manually

How can it be? What's going on? How to make it execute the command?

2) How to run only specific migration? Not 

> db:migrate             Run pending migrations.

but a migration I want to run.

**Comment by janmeier** [comment]
If you have the cli installed globally, you need the mysql package globally as well

**Comment by sushantdhiman** [comment]
@wzup Did it worked after `mysql` global install?

**Comment by manast** [comment]
I am having this same error on production, the funny thing is that I am not using mysql, but postgres:
```
{
  "development": {
    "dialect": "postgres",
    "url": "postgres://postgres@localhost:5432/mydb"
  },
  "production": {
    "dialect": "postgres",
    "url": "postgres://postgres@database:5432/mydb"
  }
}
```

**Comment by jeanru** [comment]
Have same issue on Windows 10

**Comment by paolo-tanium** [comment]
So interesting tidbit that I ran into in Windows:

If I set my NODE_ENV in cmd.exe as such: 

```
set NODE_ENV="production"
sequelize-cli db:migrate --config sequelize.json
```

I get the aforementioned problem. But if I remove the double quotes, I don't:

```
set NODE_ENV=production
sequelize-cli db:migrate --config sequelize.json
```

**Comment by fabiano-amaral** [comment]
Solution: look at the config/config.json probably in production, test or development keys is set dialect to another SGDB

**Comment by CreatiCoding** [comment]
I just solve this problem.
The err is in this code.
```
 if (sequelize.config.dialectModulePath) {
```
So I just install sequelize by global config. Then It is solved.
```
npm install -g sequelize
```
If you still have error, I am sorry.

**Comment by sonygod** [comment]
still got this error on ubuntu 18

**Comment by Ankit7991** [comment]
CONFIG
 "development": {
    "username": "root",
    "password": "root",
    "database": "sql-cli",
    "host": "localhost",
    "dialect": "mysql"
  }

---------------------------------------------------------------------------
TERMINAL
$ node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 10.11.0, CLI: 5.5.1, ORM: 5.21.3]

Loaded configuration file "config/config.json".
Using environment "development".

ERROR: Please install mysql2 package manually

**Comment by Ankit7991** [comment]
CONFIG
"development": {
"username": "root",
"password": "root",
"database": "sql-cli",
"host": "localhost",
"dialect": "mysql"
}
----------------------------------------
TERMINAL
$ node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 10.11.0, CLI: 5.5.1, ORM: 5.21.3]

Loaded configuration file "config/config.json".
Using environment "development".

ERROR: Please install mysql2 package manually

-----------------------------------------------------
PACKAGE
"dependencies": {
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "mysql2": "^2.1.0",
    "nodemon": "^2.0.2"
  },
  "devDependencies": {
    "sequelize-cli": "^5.5.1"
  }

**Comment by EbEpOs** [comment]
Try to install sequelize globally in admin admin depending on your system

4me cmd in admin mod
system32>npm install -g sequelize

it'll work probably after

**Comment by pedrovrima** [comment]
Ubuntu user here, installing mysql2 globally solved it:

npm install -g mysql2

**Comment by japsolo** [comment]
VPS with UBUNTU, same problem.

Like other guy said. Installing mysql2 globally solved it:

`npm install -g mysql2`

**Comment by bonheurbercove** [comment]
> If you have the cli installed globally, you need the mysql package globally as well

This worked for me since I have installed sequelize globally, so you have to install mysql globally too
