### ISSUE TITLE
MSSQL doesn't support native library / trusted authentication

### ISSUE THREAD

**Issue by davewthompson** [sequelize/sequelize#6133]
The MSSQL support you have - based on Tedious - doesn't support the SQL native library, so trusted authentication doesn't work.

As excellent as Sequelize is, we can't use it because we have to use Trusted Authentication.

Can I please submit a feature request for this?

**Comment by janmeier** [comment]
If it's not supported by tedious, we can't support it either. Are there any mssql drivers for node which support trusted auth? 

It's probably better to open this issue with tedious instead

**Comment by davewthompson** [comment]
Thanks for the response. I don't believe Tedious could support this because of the trusted auth exchange which requires a MSSQL native library - such as [https://github.com/TimelordUK/node-sqlserver-v8].

I'm hacking around with the Sequelize source code now to see if I can get it to work via creating a 'mssql-native' dialect - if I can, I'll let you know.

Dave

**Comment by janmeier** [comment]
Does it work on Linux? - we need to be able to run tests on Travis

**Comment by davewthompson** [comment]
Ahh... now that it won't I'm afraid as it's backed by a Win32/64 DLL... What would you advise is the best course of action?

**Comment by janmeier** [comment]
It seems that the official node sql server driver is being rewritten with
Linux support. Once that is done we can consider switching driver (I
haven't checked whether there are any other differences between the two -
but of course there are cases where a js only driver is preferable)

For now I guess you'll need to maintain you own fork, unless the driver is
completely api compatible with tedious
Den 19/06/2016 15.35 skrev "Dave Thompson" <notifications@github.com>:

**Comment by davewthompson** [comment]
I've actually hacked in a version this morning and it works for the basic operations (schema, query, add, delete) - it wasn't hard as Sequelize is modular and once the query is created the same Tedious MSSQL queries work out of the box.

I'll maintain a fork and upload to Github so people can use if they wish - the one annoying thing is there's a bit of hardcoding required to manually load this library instead.

I too look forward to MS releasing a new driver - espcially as the Linux driver already supports Kerberos (https://msdn.microsoft.com/en-us/library/hh568450(v=sql.110).aspx) !

Thanks for your help and advice.

Dave

**Comment by davewthompson** [comment]
https://github.com/davewthompson/sequelize/commit/7cd413a866d34b75fc24ca9a7898945c48084ee0 - this is my change. It's a small hack, but it does work.

**Comment by deejbee** [comment]
Is there a way to use the the https://github.com/tediousjs/node-mssql driver in sequelize now?
