### ISSUE TITLE
[unique: true] creates two unique indexes on a column

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6134]
For some a reason column option `unique: true` creates two unique indexes on a column. How to prevent it? Please take a look at an `email` field:

```
const mysql = require('../getConnection').mysql; // configured and connected sequelize here

const modelAttrs = {
    fname: {
        type: mysql.Sequelize.STRING(255),
        field: 'fname',
        allowNull: true,
        defaultValue: null,
    },
    email: {
        type: mysql.Sequelize.STRING(254),
        field: 'email',
        allowNull: true,
        defaultValue: null,
        unique: true,      // <<== here an email column is unique
        validate: {
            isEmail: true,
        }
    },
    time_zone: {
        type: mysql.Sequelize.STRING(100),
        field: 'time_zone',
        allowNull: true,
        defaultValue: null,
    }
};

const modelOpts = {
    freezeTableName: true,
    tableName: 'UserProfile',
    timestamps: true,
}

const UserProfile = mysql.define('UserProfile', modelAttrs, modelOpts);

mysql.sync({ force: true });
```

And here is what is actually created, one unique key on `email` is redundant:

```
CREATE TABLE `userprofile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fname` varchar(255) DEFAULT NULL,
  `lname` varchar(255) DEFAULT NULL,
  `full_name` varchar(500) DEFAULT NULL,
  `email` varchar(254) DEFAULT NULL,
  `accept_ts` tinyint(1) NOT NULL DEFAULT '0',
  `time_zone` varchar(100) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`), //      <<==  One
  UNIQUE KEY `UserProfile_email_unique` (`email`)  //     <<==  Two ??
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

Why does it happen? How to prevent it?

**Comment by wzup** [comment]
**UPD 1**

Funny thing happens. When you delete `unique: true` from column definition and set it in Model options instead, unique index doesn't duplicate:

```
    email: {
        type: mysql.Sequelize.STRING(254),
        field: 'email',
        allowNull: true,
        defaultValue: null,
        // unique: true,      // comment out
        validate: {
            isEmail: true,
        }
    },

const modelOpts = {
    freezeTableName: true,
    tableName: 'UserProfile',
    timestamps: true,

    // Declare it here
    indexes: [
        {
          unique: true,
          fields: ['email']
        }
    ]
}
```

And the result is no redundant index:

```
CREATE TABLE `userprofile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fname` varchar(255) DEFAULT NULL,
  `lname` varchar(255) DEFAULT NULL,
  `full_name` varchar(500) DEFAULT NULL,
  `email` varchar(254) DEFAULT NULL,
  `accept_ts` tinyint(1) NOT NULL DEFAULT '0',
  `time_zone` varchar(100) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_profile_email` (`email`)  // <<== only one !!
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

Why? I don't want to move indexes to model options. I want to declare them in column definitions. How can I do it without duplications in results?

**Comment by janmeier** [comment]
Which version does this happen on?

**Comment by wzup** [comment]
`Sequelize [Node: 5.9.1, CLI: 2.4.0, ORM: 3.23.3]`

`"version": "3.23.3"`

**Comment by janmeier** [comment]
unique columns are added to `uniqueKeys` https://github.com/sequelize/sequelize/blob/47b3f61e6d29e050e75366a28cbfd185f9ff3437/lib/model.js#L806 - You are welcome to see if you can provide a fix for this, but I don't really see this as an issue

**Comment by nmarley** [comment]
I'm getting this too -- and I agree that it's an issue. There shouldn't be two unique indexes that are the exact same (only with different names) -- it's completely redundant.

    nmarley$ node --version
    v6.3.1
    nmarley$ npm --version
    3.10.3
    nmarley$ npm view sequelize version
    3.24.0

**Comment by sabakugaara** [comment]
I have this problem to

**Comment by kaidiren** [comment]
me too

**Comment by gzlock** [comment]
I have this problem too.
but i found the solution: use string instead of the true
example:
```
email: {
        unique: 'email',
    }
```

**Comment by broofa** [comment]
Had this same problem. @gzlock 's solution worked for me.  I agree with others - it's disconcerting to see two nearly-identical indexes being created where you would expect to see one.  Seems inefficient.

@janmeier - I haven't dived into the code to understand why you're comment about `uniqueKeys` implies this isn't an issue.   Can you elaborate?

**Comment by janmeier** [comment]
@broofa Not being an issue is not specifically related to `uniqueKeys`, but just don't think this is a very serious bug ;)

The comment about `uniqueKeys` was just a pointer to anyone who wants to try and fix it

**Comment by naviapis** [comment]
+1

**Comment by AkivaLandsberg** [comment]
+1

**Comment by fcpauldiaz** [comment]
This still happens on version 3.30.4

**Comment by jorrit** [comment]
This is still a bug, afaik.

**Comment by dashmug** [comment]
This is still a bug.

**Comment by slightlytrue** [comment]
This is still happening.

**Comment by psabharwal123** [comment]
still a bug

**Comment by iaptsiauri** [comment]
@janmeier is this still a bug? If so I will try to give it a shot, any tips where it is better to start?

**Comment by psabharwal123** [comment]
@iaptsiauri yes it is still a bug. you can try a simple example with unique true with mysql.

**Comment by Diluka** [comment]
still happen in latest version

**Comment by thecatontheflat** [comment]
Same here, using version `4.22.6`

**Comment by x11joe** [comment]
This is happening for me also, exact issue as Diluka

**Comment by lostcodder** [comment]
I have same issue

**Comment by abelosorio** [comment]
I'm facing this issue but with a foreign key:

Model:
```javascript
const Event = sequelize.define('event', {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    allowNull: false,
    defaultValue: DataTypes.UUIDV4
  },
  createdBy: {
    type: DataTypes.UUID,
    allowNull: false,
    references: {
      model: 'user',
      key: 'id'
    },
    onUpdate: 'cascade',
    onDelete: 'restrict'
  },
  // ...
}
```

Migration:
```javascript
return queryInterface.addColumn('event', 'createdBy', {
  type: Sequelize.UUID,
  allowNull: true,
  references: {
    model: 'user',
    key: 'id'
  },
  onUpdate: 'cascade',
  onDelete: 'restrict'
});
```

Result:
```
"createdBy_foreign_idx" FOREIGN KEY ("createdBy") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE RESTRICT
"event_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE RESTRICT
```
