### ISSUE TITLE
Alias using "as" property doesn't appear to be working

### ISSUE THREAD

**Issue by bradleygore** [sequelize/sequelize#6136]
## What you are doing?
I have some models with associations, and I'm using `addScope` to define the default scope to bring in specific associations by default. However, any time I'm using the "as" property to alias the model, I get an error stating that ModelA isn't related to ModelB.  For instance, with my User and Organization models:

```js
// Organization model
sequelize.define('Organization', {
        ...fields
    }, {
        classMethods: {
            associate: (sqldb) => {
                sqldb.Organization.hasMany(sqldb.User, {foreignKey: 'orgId'});
            }
        }
    });

// User model
sequelize.define('User', {
  ...fields
    }, {
          classMethods: {
            associate: (sqldb) => {
                sqldb.User.belongsTo(sqldb.Organization, {foreignKey: 'orgId'});
            },

            defineScopes: (sqldb) => {
                sqldb.User.addScope('defaultScope', {
                    include: [
                        {
                            model: sqldb.Organization
                        },
                        ...other associations
                    ]
                }, { override: true });
            }
        }
    });

// the above works, but if I add "as" anywhere, it breaks. i.e.

// User model includes:
 include: [
   {
     model: sqldb.Organization,
     as: 'someAlias'
   },
     ...other associations
   ]

// or in the relationship definition
sqldb.User.belongsTo(sqldb.Organization, {foreignKey: 'orgId', as: 'someAlias'});


// But when I don't use "as", then it all works fine and relationships are eagerly loaded as they should be...
```

## What do you expect to happen?
Relationships to be eagerly loaded and aliased

## What is actually happening?
I'm told that the entities aren't even related, but removing the "as" alias allows them to be eagerly loaded, just as the "normal" name (i.e. "Organization" instead of "org")

_Output, either JSON or SQL_
Organization (theAliasUsedIn_as_Property) is not associated to User!

__Dialect: postgres 
__Database version: 9.5.3
__Sequelize version: 3.23.3

**Comment by janmeier** [comment]
You need to use the same `as` in the association and the include. So if you have `as: 'org'` on the association, you also need it on the include.

Alternatively, you can save the return value from the association (e.g. `User.Organization = sqldb.User.belongsTo(sqldb.Organization, {foreignKey: 'orgId', as: 'someAlias'});`) and then use that for includes instead  -` include: [{ association: User.Organization }]`

**Comment by bradleygore** [comment]
Oh ok - will try this. Thanks @janmeier - I appreciate the help! :smile:
