### ISSUE TITLE
Convert ignore and ignoreDuplicates to a single option

### ISSUE THREAD

**Issue by huzhenjie** [sequelize/sequelize#6138]
I want to insert a list into the MySQL db. and I want to use 

```
sequelize.query("INSERT IGNORE INTO tb SET col1=?, col2=?", .....
```

Here is my table.
```
CREATE TABLE tb(col1 INT, col2 INT);
```

Here is the data I want to insert into the table `tb`
```
[
  {'col1': 11, 'col2': 12},
  {'col1': 21, 'col2': 22},
  {'col1': 31, 'col2': 32}
]
```

**Comment by janmeier** [comment]
`{ ignore: true }` for create, `{ ignoreDuplicates: true }` for bulkCreate

This should probably be united into a single option ...

**Comment by sushantdhiman** [comment]
Implemented in https://github.com/sequelize/sequelize/pull/6214
