### ISSUE TITLE
Q: Prevent parsing of DATE model data types?

### ISSUE THREAD

**Issue by simov** [sequelize/sequelize#6147]
Is it possible to prevent automatic parsing of DATE model data types to Date objects? `raw: true` doesn't seems to work as expected:

```js
someModel.findById('..', {raw: true})
```

The returned object is missing the usual Sequelize methods, but the returned column in question is still an instance of Date.

**Comment by janmeier** [comment]
Try to add a no-op parsing function to the date type along the lines of https://github.com/sequelize/sequelize/blob/master/test/integration/data-types.test.js - But notice that this will affect _all_ dates

**Comment by simov** [comment]
Thank you for your quick reply @janmeier ! Your suggestion looks like a good solution, but I'm not going to use it because I revised my app logic and it turned out that I won't need it. Still a valuable information for future reference. Closing.
