### ISSUE TITLE
QueryInterface.renameTable() ignores case modifications

### ISSUE THREAD

**Issue by edrpls** [sequelize/sequelize#6158]
## Trying to rename a table by capitalising doesn't work 

```js
const allowedTables = [
    {name: 'account'},
    {name: 'account_type', pluralise: true},
    {name: 'image'},
    {name: 'image_type', pluralise: true},
    {name: 'asset', exclude: ['excludeThis', 'excludeToo']},
    {name: 'asset_detail', pluralise: true},
    {name: 'tag'},
    {name: 'user'}
];

module.exports = {
    up (queryInterface, Sequelize) {
        return tablesToCamel(queryInterface))
            .catch(console.log)
    }
};

function tablesToCamel(_q) {
    console.log(allowedTables.length);
    let queries = allowedTables.map(t => {
        let oldName = t.name;
        let newName = toCamel(oldName);
        newName = newName.charAt(0).toUpperCase() + newName.slice(1);
        if (t.pluralise) {
            newName = newName + 's';
        }
        console.log('NEWTABLENAME:', newName, 'OLDTABLENAME:', oldName);
        return _q.renameTable(oldName, newName);
    });
    queries.push(_q.renameTable('extraTable', 'ExtraTables'));
    return Promise.all(queries);
}

function toCamel(str) {
    return str.replace(/_\w/g, (m) => m[1].toUpperCase());
}
```

## Expected
- Tables in allowedTables object with the pluralise attribute to change from snake_case to CamelCases.
- Tables in allowed tables without the pluralise attribute to change from snake_case to CamelCase.
(Note the pluralisation and first uppercase letter)

## What is actually happening?
- Tables in allowedTables object with the pluralise attribute to change from snake_case to CamelCases (This is working as expected).
- Tables in allowed tables without the pluralise attribute are not being renamed (account should change to Account)
- I can successfully rename all tables if I pluralise all of them (but this is just a workaround).

```js
function tablesToCamel(_q) {
    console.log(allowedTables.length);
    let queries = allowedTables.map(t => {
        let oldName = t.name;
        let newName = toCamel(oldName);
        newName = newName.charAt(0).toUpperCase() + newName.slice(1) + 's'; //Pluralise everything
        console.log('NEWTABLENAME:', newName, 'OLDTABLENAME:', oldName);
        return _q.renameTable(oldName, newName);
    });
    queries.push(_q.renameTable('extraTable', 'ExtraTables'));
    return Promise.all(queries);
}
```

I checked the code in lib/query-interface.js and lib/dialects/abstract/query-generator.js since I thought maybe there was a faulty regex but it seems the names are passed "as is", so I'm not sure if this could be a MySQL problem.

Any help is greatly appreciated!

__Dialect:__ mysql
__Database version:__ 5.6.24 Homebrew
__Sequelize version:__ 3.23.3

**Comment by janmeier** [comment]
> In MySQL, databases correspond to directories within the data directory. Each table within a database corresponds to at least one file within the database directory (and possibly more, depending on the storage engine). Triggers also correspond to files. Consequently, the case sensitivity of the underlying operating system plays a part in the case sensitivity of database, table, and trigger names. This means such names are not case sensitive in Windows, but are case sensitive in most varieties of Unix. One notable exception is OS X, which is Unix-based but uses a default file system type (HFS+) that is not case sensitive

http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html
