### ISSUE TITLE
[MSSQL] Big problem sorting by primaryKey (duplicate order by column error)

### ISSUE THREAD

**Issue by juansev** [sequelize/sequelize#6162]
## What you are doing?

I am using the "mssql" dialect and trying to make a sorted findAndCountAll query with includes that uses the primary key as sorting.

Below i give you an example and i have debugged the code and the problem comes from the file located at lib/dialects/mssql/query-generator.js in the function addLimitAndOffset.

This condition is not ok because when you try to sort by the primaryKey this fragment is also added and then SQL Server gives a "duplicated column" error:
```js
if (!options.order || (options.include && !orders.subQueryOrder.length)) {
        fragment += (options.order && !isSubQuery) ? ', ' : ' ORDER BY ';
        fragment += this.quoteIdentifier(model.primaryKeyField);
      }
```

I am using Sequelize 3 so please fix this in Sequelize 3 as well , not only in Sequelize 4.

```js

var OrderLog = sequelize.define('OrderLog',{
        id: {type : Sequelize.INTEGER(10).UNSIGNED, primaryKey:true, autoIncrement:true}
        , userid: { type: Sequelize.INTEGER(11)  }
        , state: {type: Sequelize.INTEGER(10).UNSIGNED }
        , orderid: {type: Sequelize.INTEGER(10).UNSIGNED,allowNull:false }
        , logdate: {type: Sequelize.DATE }
        , info: {type: Sequelize.TEXT }
        , visibility_level: {type: Sequelize.INTEGER(11),allowNull:false }
    },{
        tableName: 'jos_vxc_orderlog', timestamps: false
    });

var OrderState = sequelize.define('OrderState',{
        id: {type : Sequelize.INTEGER(10).UNSIGNED, primaryKey:true, autoIncrement:true}
        , nameid: {type: Sequelize.STRING(255) , allowNull:false }
        , name: {type: Sequelize.STRING(255) , allowNull:false }
    },{
        tableName : 'jos_vxc_orderstate', timestamps: false
    });

               OrderLog.findAndCountAll({
                    limit: 8, // You can put whatever number but don't leave undefined
                    offset: 0, // You can put whatever number but don't leave undefined
                    include: [{model: OrderState}], // Include at least one include
                    order:  [["id", "desc"]]  // Sort by primary key
                }).then(function(data) {
                    callback({result: "ok", data: {orderlogs: data.rows, numPages: (pageSize != -1)? Math.ceil(data.count / pageSize): 1}});
                }).catch(function(error) {
                    callback({result: "error", error: error.message});
                })

```

## What do you expect to happen?

I wanted the function to work properly and give me results sorted as expected.

## What is actually happening?

SQL Server gives the following error "A column has been specificied more than once in the order by list. Columns in the order by list must be unique.

__Dialect:__ mssql
__Database version: SQL Server 2014
__Sequelize version:__ 3.23.3

**Comment by janmeier** [comment]
Since you have already identified where the problem happens, why don't you give it a shot and provide a PR :)? 

None of the core devs have any experience with mssql, so you are just as good at finding a solution as we are

**Comment by juansev** [comment]
My main problem is that i don't understand what's the main purpose of the problematic block of code. It seems to be like a "default sorting" when limit and/or offset is used but no sorting columns are provided. 

Is this default sorting even needed? Is that an expected behaviour?

I don't have have full knowledge of how Sequelize is made so may fear is to modify something that hurts someone else.

I see 3 options here:

- Update code to only add the default sorting when no other sorting is provided
`
     if (!options.order || (!options.order && options.include && !orders.subQueryOrder.length)) {
        fragment += ' ORDER BY ' + this.quoteIdentifier(model.primaryKeyField);
      }
`
- Remove this "default sorting" completely

- Search for the primaryKeyField in the current options.order and orders.subQueryOrder object and if found then not include the fragment. This requires two searchs and the code won't seem very straightforward. 

Any advice? Also i am not used to make modifications in GitHub and i don't know if i have to modify branch v3 and you will merge it into master, or if i should do it in master and cherry-pick to v3.

**Comment by juansev** [comment]
I have seen that this is also related with this other bug.

[Link to issue #5932 ](https://github.com/sequelize/sequelize/issues/5932)

More points to just delete that part if nobody gives a good reason of why does it exist.

**Comment by janmeier** [comment]
> ORDER BY is mandatory to use OFFSET and FETCH clause.

https://technet.microsoft.com/en-us/library/gg699618(v=sql.110).aspx

So the default sorting is definitely needed, but only if no sorthing is provided

**Comment by juansev** [comment]
Ok, what would you think about this code?

I only append the ORDER BY clause when it is a subquery and it has subQueryOrder items and when it is not a subquery and it hasn't any main ordering.

`
if (subQuery && !orders.subQueryOrder.length || !subQuery && !options.order) {
        fragment += ' ORDER BY ' + this.quoteIdentifier(model.primaryKeyField);
}
`

**Comment by janmeier** [comment]
As long as `order` is set, we should be good, as far as i understand. So `!options.order || subQuery && !orders.subQueryOrder.length` I think

**Comment by AckerApple** [comment]
I'm going to try my dern' best right now to make my first pull request, to fix for this. It's an easy fix:

At Line:692 of lib/dialects/mssql/query-generator.js INSERT THIS CODE:
```
if(model.name){
  fragment += this.quoteIdentifier(model.name) + '.';
}
```

Wish me luck!

**Comment by AckerApple** [comment]
I made the pull request to fix

https://github.com/sequelize/sequelize/pull/6181

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/6181
