### ISSUE TITLE
Include with only one attribute -> replace top level

### ISSUE THREAD

**Issue by molerat619** [sequelize/sequelize#6163]
Hey there!

I have this query: 

```
LocationMatrix.findAll({
    include: [
       ...
      {model: ServiceType, as: 'service', attributes: ['code']}
    ]})
    .then(respondWithResult(res))
    .catch(handleError(res));
}
``` 

and I would like to receive a result in that format:

`{_id: 123, name: "some name", service: "THE ACTUAL CODE"}`

I **don't want** service to be an object holding the `code`attribute that has the actual code - in this case. Is that possible?

**Comment by mickhansen** [comment]
You could use an afterFind hook to modify this, but the easiest would simply to have a wrapper around the result that modifies it as you see fit.
