### ISSUE TITLE
Feature Request : cross database JSON data type

### ISSUE THREAD

**Issue by jaumard** [sequelize/sequelize#6175]
Currently JSON data type is only available for postgresql, it would be nice to have it for all databases. For databases who doesn't support JSON sequelize could stringify it and parse it when it fetch it from the DB.

**Comment by janmeier** [comment]
We have an issue for mysql json support (5.7) here https://github.com/sequelize/sequelize/issues/4727

The big benefit of the json datatype is that you can also query it - which you wouldn't be able to do with a string.

You can add getter and setter functions which stringify / parse the column
