### ISSUE TITLE
Foreign key being pulled from incorrect schema.

### ISSUE THREAD

**Issue by emmceemoore** [sequelize/sequelize#6178]
## What you are doing?

I have an existing database and I wanted to spin up a new database to try something out. I updated my sequelize config to point to a different database and I ran my migrations to get the tables created.
## What do you expect to happen?

I expected the migrations to run without issue.
## What is actually happening?

One of the migrations fails. The failure occurs because [`getForeignKeyQuery()`](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query-generator.js#L315) returns the name of a foreign key in a _different_ schema.

Here's the error I'm getting:

``` bash
SequelizeDatabaseError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'fooId_foreign_idx'; check that column/key exists
```

(The real name of the key is `foo_ibfk_1`. I'm not sure if the difference in name is because of a newer version of sequelize or a newer version of mysql.)

Regardless, it seems like it would be a good idea to additionally consider the schema when performing this query. (Similar to how [`getForeignKeysQuery()`](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query-generator.js#L303) does it.)

**Dialect:** mysql
**Database version:** 5.7.13
**Sequelize version:** 3.23.4

**Comment by myaskevich** [comment]
Still relevant

-- 
Maxim Yaskevich
