### ISSUE TITLE
Hooks do not work

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6179]
I have a `beforeValidate`  hook in my model. It never works with **associated model**
```
UserAccount.hasOne(UserSession, {
    hooks: true
});

// UserSession Model options
const modelOpts = {
    freezeTableName: true,
    timestamps: true,
    indexes: [
        {
          unique: true,
          fields: ['token']
        }
    ],
    hooks: {
        beforeValidate: function(inst, opts, fn) {
            inst.token = "1234567890"
        }
    },
```

And when I create new `UserSession` instance through `UserAccount` instance, `UserSession` hook stops execution! Program run never gets neither `.then` nor `.catch`

```
   User.create({...}).then(function(user) {

        // Hook should set default token in `beforeValidate`
        // But neither .then nor .catch are executed
        user.createUserSession({
            UserAccountId: user.id,
        }).then(function(session) {
            // NEVER CALLED!
        }, function(a, b, c) {
            // NEVER CALLED!
        });
    })
```

But your docs says we can set instance values in hooks (http://docs.sequelizejs.com/en/latest/docs/hooks/#declaring-hooks):

```
  hooks: {
    beforeValidate: function(user, options) {
      user.mood = 'happy'
    },
    afterValidate: function(user, options) {
      user.username = 'Toni'
    }
  }
```

Why it doesn't work in real life?

**Comment by sushantdhiman** [comment]
Sequelize version ?

**Comment by janmeier** [comment]
When you take a third argument `fn`, the hook is not considered finished before you call the callback. So either remove it, or call it.

The fn argument has been removed in 4.0, so you could also update to that (though its easier to just remove the `fn` arg :) )
