### ISSUE TITLE
What are "association calls"?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6182]
Could you please be more specific when writing docs. 

What does that mean "_by passing `onUpdate` and `onDelete` options to the **association calls**._"? What are **association calls**? 

> _These options can be overridden by passing `onUpdate` and `onDelete` options to the association calls._ 

http://docs.sequelizejs.com/en/latest/docs/associations/#foreign-keys_1

I want to set my model `CASCADE `and `CASCADE`, as follows:
```
ON DELETE CASCADE ON UPDATE CASCADE
```

By default a table is created `SET NULL` and `CASCADE`:
```
ON DELETE SET NULL ON UPDATE CASCADE
```

It is not clear how to do it from your 

> _by passing `onUpdate` and `onDelete` options to the **association calls**._

Here is I'm defining a model. Where in `ModelChild` do I have to define `ON DELETE CASCADE`?

```
const ModelParent = mysql.define('ModelParent', {...}, {...});
const ModelChild = mysql.define('ModelChild', {...}, {...});

ModelParent.hasOne(ModelChild);
```

**Comment by mickhansen** [comment]
Association calls are `hasMany/hasOne/belongsTo/belongsToMany`, it's the calls you make to setup associations.

All association setup methods take a secondary options object, http://docs.sequelizejs.com/en/latest/api/associations/

**Comment by sushantdhiman** [comment]
Pass the 2nd argument with these options

```js
ModelParent.hasOne(ModelChild, {
     onUpdate: 'CASCADE',
     onDelete: 'CASCADE'
})
```
