### ISSUE TITLE
how update one to many data's 

### ISSUE THREAD

**Issue by dahuahe** [sequelize/sequelize#6185]
_Thanks for wanting to report an issue you've found in Sequelize. Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_Note that it will be much easier for us to fix the issue if a test case that reproduces the problem is provided. Ideally this test case should not have any external dependencies. We understand that it is not always possible to reduce your code to a small test case, but we would appreciate to have as much data as possible. Thank you!_

_Github should only be used for feature requests and bugs - all questions belong on StackOverflow, Slack, or Google groups._

_This template is for submitting issues - if you want to submit a feature request you may skip this template_

## What you are doing?
I'd like to update the child table data, but make sure they are new so I can only delete all added again. But I didn't find the delete child table shortcut or not found can directly update method, I use the Role. The setRoleToTables ([]), found that just delete the relationship does not delete data.

```js
// code here
Role.hasMany(RoleToTable);

  model.Role.findById(req.params.Id)
        .then(function(Role){
        return  Role.setRoleToTables([]);
    })




## What do you expect to happen?
example in Role a row data {Id:"1",Name:"test"}
in RoleToTable data[{Id:"1",RoleId:"1",TableId:"A",},{Id:"2",RoleId:"1",TableId:"B"}]

now a new data
Role: {Id:"1",Name:"test"}
RoleToTable data [{Id:"1",RoleId:"1",TableId:"C",},{Id:"2",RoleId:"1",TableId:"D"}]  A and B is delete
## What is actually happening?
_But the output was bar!_
RoleToTable data [{Id:"1",RoleId:"",TableId:"B",},{Id:"2",RoleId:"",TableId:"A"},{Id:"1",RoleId:"1",TableId:"C",},{Id:"2",RoleId:"1",TableId:"D"}]
_Output, either JSON or SQL_


__Dialect:__ mysql 
__Database version:__ XXX
__Sequelize version:__ XXX

**Comment by mickhansen** [comment]
It'd be great if you make the minimum effort of actually following the issue template that was right infront of you as you opened the issue.

**Comment by sushantdhiman** [comment]
**SSCCE**

```js
var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

var Main = sequelize.define('Main');
var Child = sequelize.define('Child');

Main.hasMany(Child);

sequelize.sync({ force: true })
.then(() => Main.create({}))
.then(m => Child.bulkCreate([{id: 1}, {id: 2}])
                .spread((c1, c2) => m.setChildren([c1, c2]))
                .then(() => (m))
)
.then((m) => Child.bulkCreate([{id: 3}, {id: 4}])
                .then((cs) => m.setChildren(cs))
)
.then(() => Child.findAll({ raw: true}))
.then((d) => { console.log(d) });
```

**Output**

```bash
Using database:  sequelize-test-79
[ 
  { id: 1,
    createdAt: 2016-06-29T07:47:42.505Z,
    updatedAt: 2016-06-29T07:47:42.598Z,
    MainId: null },
  { id: 2,
    createdAt: 2016-06-29T07:47:42.505Z,
    updatedAt: 2016-06-29T07:47:42.598Z,
    MainId: null },
  { id: 3,
    createdAt: 2016-06-29T07:47:42.569Z,
    updatedAt: 2016-06-29T07:47:42.600Z,
    MainId: 1 },
  { id: 4,
    createdAt: 2016-06-29T07:47:42.569Z,
    updatedAt: 2016-06-29T07:47:42.600Z,
    MainId: 1 }
]
```

@mickhansen @janmeier What do you think? should we remove the old records with `null` ids when issuing `set<Relation>` method. In case of `belongToMany`, we should to apply same logic there as well?

**Comment by mickhansen** [comment]
@sushantdhiman Not by default. It could be an option, and we've previously discussed a `destroy[Association]` method

**Comment by sushantdhiman** [comment]
This will be better solved with https://github.com/sequelize/sequelize/issues/6095 @dahuahe , You will have a `destroy[Association]` method which can be used to remove the records explicitly, but `set[Association]` will not remove any records.

**Comment by dahuahe** [comment]
This version has destroy [Association]  method??@sushantdhiman

**Comment by sushantdhiman** [comment]
#6095 is still open, I don't know if anyone is working on it. @dahuahe

**Comment by chrys1110** [comment]
Can anyone give me example how to workaround this issue with **destroy**?
