### ISSUE TITLE
SequelizeDatabaseError: Incorrect syntax near '.'

### ISSUE THREAD

**Issue by ww9rivers** [sequelize/sequelize#6186]
Test program: https://gist.github.com/ww9rivers/2da567033b6418552d9da443174be2b6
Environment:
- OS: Ubuntu 14.04.4 LTS
- node: v5.12.0
- sequelize@3.23.4
- Microsoft SQL Server 2012 on Windows 2012 64-bit

I get the error in the title of this issue when running my program with a database table name including periods (.) in it.

With the (.)s changed to (-)s and no other change in the program, the error is not thrown.

With or without the error being thrown, the database table is created. The error seems to affect anything that has to do with the index.

**Comment by janmeier** [comment]
I (and stackexchange) would strongly recommend not using dots in table names https://dba.stackexchange.com/questions/1166/is-it-okay-to-put-dots-in-sql-server-database-names

If you want to, you are welcome to track down where the proper escaping is missing and provide a PR, but this is not something we in the core team will have to time look at
