### ISSUE TITLE
hasOne relationship create[Association]() method not working?

### ISSUE THREAD

**Issue by jamestwiggle** [sequelize/sequelize#6187]
I posted a StackOverFlow of the problem:
http://stackoverflow.com/questions/38113625/sequelize-hasone-relationship-association-method-not-a-function

No one has responded, if you would be willing to answer please do.

**Comment by mickhansen** [comment]
`createAssociation` works on instances, not on models.
Might also be a naming issue, try inspecting `Model.Instance.prototype`
