### ISSUE TITLE
Composite primary key with associations

### ISSUE THREAD

**Issue by jaumard** [sequelize/sequelize#6188]
Hi,

I'm trying to create three models Role, Resource and Permission and I want a primary key with RoleId, ResourceId and action for my Permission model. I can't manage to do it and doesn't find any info on this on the doc, it's possible ?

Here is my models : 
Role : 
```
module.exports = class Role extends Model {
  static config(app, Sequelize) {
    return {
      options: {
        classMethods: {
          associate: (models) => {
            models.Role.hasMany(models.Permission, {
              as: 'permissions',
              onDelete: 'CASCADE',
              foreignKey: {
                allowNull: false
              }
            })
          }
        }
      }
    }
  }

  static schema(app, Sequelize) {
    return {
      name: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: true
      },
      active: {
        type: Sequelize.BOOLEAN,
        allowNull: false,
        defaultValue: true
      }
    }
  }
}
```
Resource: 
```
module.exports = class Resource extends Model {
  static config(app, Sequelize) {
    return {
      //More informations about supported models options here : http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration
      options: {
        classMethods: {
          associate: (models) => {
            models.Resource.hasMany(models.Permission, {
              as: 'permissions',
              onDelete: 'CASCADE',
              foreignKey: {
                allowNull: false
              }
            })
          }
        }
      }
    }
  }

  static schema(app, Sequelize) {
    return {
      type: {
        type: Sequelize.ENUM('model', 'controller', 'other'),
        allowNull: false
      },
      action: {
        type: Sequelize.STRING,
        allowNull: false
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false
      }
    }
  }
}
```
And Permission : 
```

module.exports = class Permission extends Model {
  static config(app, Sequelize) {
    return {
      options: {
        classMethods: {
          associate: (models) => {
            models.Permission.belongsTo(models.Role, {
              onDelete: 'CASCADE',
              primaryKey: true,
              foreignKey: {
                allowNull: false
              }
            })
            models.Permission.belongsTo(models.Resource, {
              onDelete: 'CASCADE',
              primaryKey: true,
              foreignKey: {
                allowNull: false
              }
            })
          }
        }
      }
    }
  }

  static schema(app, Sequelize) {
    return {
      type: {
        type: Sequelize.ENUM('model', 'controller', 'other'),
        allowNull: false
      },
      action: {
        type: Sequelize.ARRAY(Sequelize.STRING),
        primaryKey: true,
        allowNull: false
      }
    }
  }
}
```

At the and my primary key look like `ALTER TABLE public.permission
  ADD CONSTRAINT permission_pkey PRIMARY KEY(action);` instead of `ALTER TABLE public.permission
  ADD CONSTRAINT permission_pkey PRIMARY KEY(RoleId, ResourceId, action);`

Any idea ?

**Comment by janmeier** [comment]
Try adding `primaryKey` inside the `foreignKey` object

With that said, sequelize doesn't have awesome support for composite primary keys, so you might have trouble longer down the road

**Comment by jaumard** [comment]
Ho great it's working ! What kind of problem can I have (if you aware of them) ?

**Comment by janmeier** [comment]
Relation methods only support a single primary key - For example [`belongsTo.get`](https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to.js#L176-183) only supports a single attribute as the foreign key

**Comment by jaumard** [comment]
Ok I'll give it a try like this and if there to much problem I'll revert to one primary key and code my primary key logic. Thanks for your help =)

**Comment by jaumard** [comment]
@janmeier did you know how can I have non uppercase field ? sequelize is creating me RoleName and ResourceName on my permission model and I have to define permissions like : 

```
 {
      RoleName: 'roleName',
      ResourceName: 'modelName',
      action: 'update'
    }
```
Witch is ugly... roleName and resourceName will be perfect but if I add a `as` like : 
```
models.Permission.belongsTo(models.Role, {
              as: 'role',
              onDelete: 'CASCADE',
              primaryKey: true,
              foreignKey: {
                allowNull: false
              }
            })
            models.Permission.belongsTo(models.Resource, {
              as: 'resource',
              onDelete: 'CASCADE',
              primaryKey: true,
              foreignKey: {
                allowNull: false
              }
            })
```
I have the error : `SequelizeDatabaseError: SQLITE_ERROR: duplicate column name: RoleName`

**Comment by janmeier** [comment]
What do the `ResourceName` and `RoleName` keys do - they have no meaning in sequelize :)

Can you create a [SSCCE](HTTP://SSCCE.ORG/)?

**Comment by jaumard** [comment]
Sorry I didn't see models definition was not up to date ^^ they are just primary key of Resource and Role and was automatically create by sequelize on Permission model. Here is a simplify example : 
```
const Resource = {
      name: {
        type: Sequelize.STRING,
        primaryKey: true,
        allowNull: false
      }
    }
const Role = {
      name: {
        type: Sequelize.STRING,
        primaryKey: true,
        allowNull: false
      }
    }
const Permission = {
      action: {
        type: Sequelize.STRING,
        primaryKey: true,
        allowNull: false
      }
    }
```
Associations: 
```
Resource.hasMany(Permission, {
              as: 'permissions',
              foreignKey: {
                allowNull: false
              }
            })
Role.hasMany(Permission, {
              as: 'permissions',
              foreignKey: {
                allowNull: false
              }
            })
Permission.belongsTo(Role, {
              foreignKey: {
                primaryKey: true,
                allowNull: false
              }
            })
Permission.belongsTo(Resource, {
              foreignKey: {
                primaryKey: true,
                allowNull: false
              }
            })
```

This will create ResourceName and RoleName attributs on Permission when I prefer roleName and resourceName. Don't know why each time I do an association with sequelize it create a capitalize attributs instead of lowercase/camel case one.

**Comment by janmeier** [comment]
The name of the foreign key matches the name of the model - So if you have an upper case model name, the foreign key name will also be upper case.

If you use `as`, the foreign key will match the `as` - But you need the `as` part of both sides of the association

**Comment by jaumard** [comment]
Ho ok ! I understand I also try this (to have `as` in both side) : 
```
Resource.hasMany(Permission, {
              as: 'permissions',
              foreignKey: {
                allowNull: false
              }
            })
Role.hasMany(Permission, {
              as: 'permissions',
              foreignKey: {
                allowNull: false
              }
            })
Permission.belongsTo(Role, {
              as: 'role',
              foreignKey: {
                primaryKey: true,
                allowNull: false
              }
            })
Permission.belongsTo(Resource, {
              as: 'resource',
              foreignKey: {
                primaryKey: true,
                allowNull: false
              }
            })
```
But then I have `SQLITE_ERROR: duplicate column name: RoleName` and `SQLITE_ERROR: duplicate column name: ResourceName`

**Comment by janmeier** [comment]
Minimal test case:
```js
var Permission = sequelize.define('Permission')
var Role = sequelize.define('Role')
Role.hasMany(Permission, {
  as: 'permissions',
})
Permission.belongsTo(Role, {
  as: 'role',
})
```

Ah yes - `as: role` of course only fixes on side of the association. The other side still tries to add `RoleId`.

You need to use `foreignKey` on both sides. 

This is one of the unfortunate parts of having to define the assocation both ways. See https://github.com/sequelize/sequelize/issues/6091

**Comment by jaumard** [comment]
@janmeier with foreignKey on both side it works great thanks a lot ! Yeah sequelize association are far from easy to use/understand ^^ hope you'll success to make them better ! :)
I didn't understand how to make find request based on associations and docs is really empty on this subject http://sequelize.readthedocs.io/en/latest/docs/querying/#relations-associations :( 

```
User = sequelize.define('User', {
    name: {type: Sequelize.STRING}
  })
Item = sequelize.define('Item', {
        name: {
          type: Sequelize.STRING,
          allowNull: false
        }
      }
User.belongsToMany(models.Item, {
     as: 'items',
     through: 'UserItem'
})
Item.belongsToMany(models.User, {
     as: 'owners',
     through: 'UserItem'
})
Item.findAll({
    include: [{
      model: User,
      through: {
        where: {id: 2}
      }
    }]
  }).then(items => {
    log.debug(items)
  }).catch(err => {
    log.error(err)
  })
```
I have `Error: User is not associated to Item!` Is there any more documentation on the subject ?

**Comment by janmeier** [comment]
You need to provide the alias `as` part to the include as well. You can also do `Item.Owners = Item.belongsToMany...` `include: [{ association: Item.Owners }]`

**Comment by jaumard** [comment]
Yes I add the `as` and request is ok thanks :) make more sens now but request doesn't return what I want maybe I forget something ^^

I want to retrieve all Item associate with the User with id 1, unfortunately the request above return all Item and include User with id 1 in it :( 

Maybe something like this exist in sequelize ? : 
```
Item.findAll({
      where: {
        'owners.id': 1
      }
    include: [{
      model: User, as: 'owners'
    }]
  }).then(items => {
    log.debug(items)
  }).catch(err => {
    log.error(err)
  })
```

I know I can do a `find` on User with id 1 and include Items but in my project I need to do it from Item, do you think it's possible ? 
When I have some time I'll try to make a PR on sequelize doc about association to explain all this ^^

**Comment by janmeier** [comment]
Add the where clause to the include (I'm not sure how adding it to the parent with `$$` even works) :)

I think its time for you to join us on slack - https://sequelize-slack.herokuapp.com/ - Its a lot easier to answer questions there
