### ISSUE TITLE
findAll collation (help)

### ISSUE THREAD

**Issue by crephix** [sequelize/sequelize#6189]
How do I use collate for a single query? I haven't found something in the documentation how to specify a collation for just one query.

I have tried the following which didn't work:

```
    models.Players.findAll({
        where: {
            FullName: {
                $like: '%' + req.query.term + '%'
            }
        },
        collate: 'utf8_general_ci'
    }).then(function(players) {
        res.send(JSON.stringify(players));
    });
```

**Comment by janmeier** [comment]
As i understand it, you need to specify collation for each attribute, right?

```js
$like: sequelize.literal(`'%${req.query.term}%' COLLATE utf8_general_ci`)
```
Is probably the easiest

**Comment by crephix** [comment]
Yes you understood it correctly, thanks for the fast response. I thought there is a more easy way like adding it as option as I tried originally.
