### ISSUE TITLE
Reduce BLOB in logging?

### ISSUE THREAD

**Issue by semaja2** [sequelize/sequelize#6199]
Hi Guys,

Is it possible to reduce/truncate the logging when it comes to using the BLOB data type?

At the moment I am using the BLOB data type to store files that are a few megabytes in size, and when a user uploads the file the sequelize logging system will spam the console with the BLOB data which can take some time to output

The temporary fix is to simply disable logging on the specific code blocks that deal with the blob, however a nicer solution would be to truncate the BLOB to either the first x amount or simply replace it with <binary data>

Thanks :)

**Comment by mickhansen** [comment]
I'm afraid we simply log the SQL that is executed. We'd have no way of retroactively changing the output.
You can disable logging on a call per call basis.
