### ISSUE TITLE
'errors' and 'fields' empty in SequelizeUniqueConstraintError

### ISSUE THREAD

**Issue by Xenope** [sequelize/sequelize#6202]
Hello, 

when i try to insert new datas in my sql database i got  a **SequelizeUniqueConstraintError**.
It's OK because one of the field is defined like that 

`ksourceexcde: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },` 

and i send an already existant value on purpose  for that field

The only problem is that i got nothing in the `errors` and `fields` of the SequelizeUniqueConstraintError.

```
{ [SequelizeUniqueConstraintError: Validation error]
  name: 'SequelizeUniqueConstraintError',
  message: 'Validation error',
  errors: [],
  fields: {} }

```
Shouldn't it be filled like that : 

```
errors: 
   [ { message: '"ksourceexcde" must be unique',
       type: 'unique violation',
       path: '"ksourceexcde"',
       value: 'firstTest' }],
  fields: { '"ksourceexcde"': 'firstTest', }
```

in that way i could show the issue to the user.

**Comment by janmeier** [comment]
Which dialect are you using? Which language is your database installation? 

There is no way to get the affected fields directly, so we rely on string parsing to see which columns were affected - But that only works for english

**Comment by aegenet** [comment]
Hello, 

He (@Xenope) uses the MSSQL  dialect.

Database installation is in french.

So we (@Xenope or me) can create a pull request for this feature (multilingual).

**Comment by sushantdhiman** [comment]
**SSCCE Test**

```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

var M = sequelize.define('M', {
  name: {
    type: Sequelize.STRING,
    unique: true
  }
});

M.sync({ force: true })
.then(() => M.create({ name: 'Alpha' }))
.then(() => M.create({ name: 'Alpha' }))
.then(console.log)
.catch((e) => {
  console.log(JSON.stringify(e, 2, 2));
});
```

**Output**
```js
Using database:  sequelize-test-99
{
  "name": "SequelizeUniqueConstraintError",
  "errors": [
    {
      "message": "name must be unique",
      "type": "unique violation",
      "path": "name",
      "value": "Alpha"
    }
  ],
  "fields": {
    "name": "Alpha"
  }
}
```

@Xenope @aegenet You guys can submit a PR to support this for multilingual installations

**Comment by aegenet** [comment]
I said "multilingual", no a french version of error code... If it's for create 50+ "if", I am not interested, I like standard code.
We can handle this in our own code if you don't want handle this at all, it's your project.

It's maybe just sad for other developers/users of Sequelize.

As you wish, In all case, we have planned to work on that in near future.
