### ISSUE TITLE
Renaming column removes reference when using sqlite

### ISSUE THREAD

**Issue by lrills** [sequelize/sequelize#6205]
It seems only table schema is copied while constructing new table, neither do index and reference.
https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query-interface.js#L94
## What you are doing?

Using renameColumn in migration with cli, happened when test with sqlite.

``` js
export default {
  up(queryInterface) {
    return queryInterface.renameColumn('mytable', 'updated_at', 'registered_at');
  },
  down(queryInterface) {
    return queryInterface.renameColumn('mytable', 'registered_at', 'updated_at');
  },
};
```
## What do you expect to happen?

Reference remain still.
## What is actually happening?

Reference gone, this is comparison to schema generated by sync:

```
      -    "foreignKeyList": []
      +    "foreignKeyList":[
      +       {
      +        "from": "band_id"
      +        "match": "NONE"
      +        "on_delete": "CASCADE"
      +        "on_update": "CASCADE"
      +        "seq": 0
      +        "table": "bands"
      +        "to": "id"
      +      }
      +    ]
```

**Dialect:** sqlite
**Database version:** 3.8.10.2
**Sequelize version:** 3.23.3

**Comment by sushantdhiman** [comment]
Related #2033

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/7078
