### ISSUE TITLE
MySQL table name capitalization is different on Windows and Ubuntu

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6207]
First off, here are similar questions, both have no answers.
https://github.com/sequelize/sequelize/issues/3487
http://stackoverflow.com/questions/30029426/is-there-a-way-to-lock-table-name-case-in-sequelize-js-migration

**The problem**: Table are named differently between machines. On Windows table names are all lowercase, on Ubuntu they are capitalized.

**Example:**
&ensp; Actual table name: `UserAccountStatus`
&ensp; Table name on Windows: `useraccountstatus`
&ensp; Table name on AWS RDS (MySQL): `UserAccountStatus`

Dev machine:
&ensp; Windows 10
&ensp; MySQL (`Ver 14.14 Distrib 5.7.13, for Win64 (x86_64)`)
&ensp; Sequelize (`"version": "3.23.3"`)

Production machine:
&ensp; AWS Ubuntu:
```
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.3 LTS
    Release:        14.04
    Codename:       trusty
```
DB Server: 
&ensp; Amazon Aurora is a MySQL-compatible (`"Aurora-5.6.10a.16.39",`)

Model definition example (`mysql` is a `sequelize` instance):
```
const modelAttrs = {
    token: {
        type: mysql.Sequelize.STRING(254),
        field: 'token',
        allowNull: false,
        primaryKey: false,
        autoIncrement: false,
    },
}

const modelOpts = {
    freezeTableName: true,
    tableName: 'UserAccountStatus', 
    timestamps: true,
    indexes: [
        {
            unique: true,
            fields: ['token']
        }
    ],
    classMethods: {
        validator: mysql.Sequelize.Validator
    }
}

const UserAccountStatus = mysql.define('UserAccountStatus', modelAttrs, modelOpts);

mysql.sync({
    force: true
}).then(...)
```

Why does it happen? How to make these work consistently on all platforms?

If it is not Sequelize's issue why not to reflected it in docs anyways? Because we start thinking that it is exactly Sequelize that causes the issue.

**Comment by sushantdhiman** [comment]
`freezeTableName` option should work ( [more docs](http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=freezeTableName) )

**Comment by sushantdhiman** [comment]
Maybe `MySQL` configuration is causing the issue, Can you confirm if [this](http://stackoverflow.com/questions/6248735/how-to-force-case-sensitive-table-names) isn't the issue ?

**Comment by sushantdhiman** [comment]
Did more research it seems to be a common Windows related issue.

[Link 1](http://stackoverflow.com/questions/8550789/where-to-change-the-value-of-lower-case-table-names-2-on-windows-xampp), [LInk 2](http://stackoverflow.com/questions/6248735/how-to-force-case-sensitive-table-names), [Link 3](http://www.neiland.net/blog/article/mysql-case-sensitivity-differences-between-linux-and-windows/), [MySQL Bug 1](https://bugs.mysql.com/bug.php?id=20356), [MySQL Bug 2](https://bugs.mysql.com/bug.php?id=55669) 

This is a misconfiguration issue on Windows, I never develop on Windows for reasons like this :wink: . You can set case insensitive identifier to fix this.
