### ISSUE TITLE
Updating association from association

### ISSUE THREAD

**Issue by jamestwiggle** [sequelize/sequelize#6209]
I have a Model `User` and trying to grab an association `CarList` which contains more associations `Car` and act on `CarList` to clear all the `Car` associations from it. I don't want to delete `CarList ` just empty it. To do this I'm running the code below:

```js
// Get the CarList
var carList = await user.getCarList(); // User hasOne() CarList
//remove all Car associations from CarList();
var clearCars = await carList.removeCars(); // CarList hasMany() Car
```

However this code fails and returns the following error message:
```js
  "errors": [
    {
      "message": "carList.removeCars() is not a function"
    }
   ]
```

I'm not completely sure why this is occurring, if this behavior is known can you explain to me how to work around this?

**Comment by janmeier** [comment]
`carList` is a sequelize object. If you want to remove all cars you can either `user.setCarsList(null)`
