### ISSUE TITLE
Postgres jsonb querying not using @> operator

### ISSUE THREAD

**Issue by umar-muneer** [sequelize/sequelize#6217]
I am using sequelize 3.24 with postgres. I have a table  PG table 'A' with the following structure
```javascript
var A = sequelize.define("A",{
    "id":{type:Sequelize.INTEGER,primaryKey:true,allowNull:false,autoIncrement:true},
    "json":Sequelize.JSONB
});
```

the JSONB column contains data in the following format

> {id: 100}

i have created a gin index on the JSONB column

```javascript
CREATE INDEX "idxJSON" ON "A" USING gin (json)
```

I am querying the table through the following code fragment

```javascript
A.findAll({
  where: {
      id: 100
  }
})
```

Sequelize generates the query in the following format

> select * from A where "json" #>> '{id}' = '2'

Because of the #>> operator the json column cannot be indexed. However if i use the following raw query with the @> operator, the index on the json column is triggered.

>  select * from A where "son" @>  '{"id": 2}'

Is the support for the @> in the pipeline or do we have to use raw queries for it?

**Comment by alitaheri** [comment]
have you tried: http://docs.sequelizejs.com/en/stable/docs/querying/#containment

**Comment by janmeier** [comment]
You can use the `$contains` operator http://docs.sequelizejs.com/en/latest/docs/querying/#operators

```js
A.findAll({
    where: {
      json: {
        $contains: {
          id: 100
        }
      }
    }
  })
```
```sql
SELECT "id", "json" FROM "As" AS "A" WHERE "A"."json" @> '{"id":100}';
```
