### ISSUE TITLE
Easiest way of accessing associated data?

### ISSUE THREAD

**Issue by crephix** [sequelize/sequelize#6222]
Assuming I have two tables: `TradeSetting` and `TradePrices`. One TradePrice may be used by multiple TradeSettings. In Express I want to list all TradeSettings with the according TradePrice and thus I use sequelize's `findAll` for both tables and pass the results to my jade view.

**My problem:**

How can I output the right price for the according TradeSetting without creating a new select for every iteration of my jade view:

    each tradeSetting in tradeSettings
      td #{tradeSetting.Name}
      td #{tradeSetting.PriceId}
      td // the according price for this tradeSetting

I thought about using something like an associative array so that I could output it with `#{TradePrice[tradeSetting.PriceId]}` but I am not sure if this is possible and what I would need to do? What is the easiest way to achieve my goal, is there something what sequelize offers if I use foreign keys in my database?

**My two tables look like this (simplified):**

TradeSettings (**Id**, Name, *PriceId*)

TradePrices (**Id**, Price)

**Side note:** I am not using foreign keys in my database yet, but I could add them there and adapt the models accordingly if necessary.

**Comment by janmeier** [comment]
Assuming that `TradeSetting.belongsTo(TradePrice)` you can do `TradeSetting.findAll({ include: [TradePrice])`, and then in your template `tradeSetting.get('TradePrice').get('Price')`

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize). (slack is probably the most active)

**Comment by crephix** [comment]
@janmeier unfortunately I wasn't able to join your slack room, it seems like I need an invitation from you guys?

I have tried your suggestion, added the foreign key in the database and used sequelize-auto to create the models. I get this exception:

> Unhandled rejection Error: ResourcePrices is not associated to TradeSettings!
>     at validateIncludedElement (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\lib\model.js:550:11)
>     at C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\lib\model.js:432:29
>     at Array.map (native)
>     at validateIncludedElements (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\lib\model.js:428:37)
>     at .<anonymous> (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\lib\model.js:1364:32)
>     at tryCatcher (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:502:31)
>     at Promise._settlePromise (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:559:18)
>     at Promise._settlePromise0 (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:604:10)
>     at Promise._settlePromises (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:683:18)
>     at Async._drainQueue (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\async.js:138:16)
>     at Async._drainQueues (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\async.js:148:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\h9pe\WebstormProjects\base-express\node_modules\sequelize\node_modules\bluebird\js\release\async.js:17:14)
>     at tryOnImmediate (timers.js:543:15)
>     at processImmediate [as _immediateCallback] (timers.js:523:5)

Even though, sequelize-auto has added this into the TradeSettings model:

```
    ResourceId: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      references: {
        model: 'ResourcePrices',
        key: 'ResourceId'
      }
    }
```
Multiple `TradeSettings` may reference to one `ResourceId`, thus I think I don't need to add anything to the `ResourcePrices` model??

**Comment by janmeier** [comment]
If you follow the link and enter your email you should get an invitation. 

Adding references to attributes is not enough - that only handles database foreign keys. You need to call belongsTo to tell sequelize about the association

**Comment by crephix** [comment]
@janmeier thanks for pointing this out, I finally figured how to join your slack channel.

Unfortunately I am still struggling with this problem and it appears a bit to much to describe there for me, thus I write here once again.

This is how I have tried to render the price for my tradeSetting: 
`td #{tradeSetting.get('ResourcePrices').get('Price')}` . This line throws an exception: 

> TypeError: Cannot read property 'get' of undefined

When I remove .get('Price') I actually get the resource id (which is the primary/foreign key). 

**My models setup:**
Since I am using express I had this in my index.js (models folder):
```
Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});
```

I have added this to the **TradeSettings** model (one or multiple Tradesettings belons to one ResourcePrice):
```
classMethods: {
      associate: function (models)
      {
        models.TradeSettings.belongsTo(models.ResourcePrices, {
          onDelete: 'CASCADE',
          foreignKey: 'ResourceId',
          targetKey: 'ResourceId'
        })
      }
    }
```

And I added this to my **ResourcePrices** model:
```
classMethods: {
        associate: function (models)
        {
          models.ResourcePrices.hasMany(models.TradeSettings, {foreignKey: 'ResourceId', targetKey: 'ResourceId'})
        }
      }
```

Did I miss something?

**Comment by janmeier** [comment]
Try to check which part is undefined - trade settings or resource price. Try calling get without any arguments to see all attributes of the model - perhaps the capitalization is different

**Comment by crephix** [comment]
Maybe I am just too dumb to understand, but tradeSetting is at this point nothing else but a JSON object which contains all the attributes of the current row or? At least this is what JSON.stringify(tradeSetting) tells me. So what should .get('ResourcePrices') actually return then?

To answer your question:
`td #{tradeSetting.get('ResourcePrices')` => Doesn't cause an exception
`td #{tradeSetting.get('ResourcePrices').get('Price')}` => Causes the cannot read property 'get' of undefined exception. I tried to figured it by myself by reading the entire sequelize doc, but in regards of outputting associated data it lacks in my oppinion.

**Comment by felixfbecker** [comment]
@crephix You use different model names in your descriptions. What are you trying to include? `TradePrice` or `ResourcePrice`? Please post your query code. You need to pass the model you want to include to the `include` option. After that, you will have an array of the associated instances on the model name in plural. You can also pass `as` to override the attribute name. Then you can simply access this array in your template, iterate over it and use attributes from the included instances.

**Comment by crephix** [comment]
@felixfbecker thanks, I finally figured out by stringifying and outputting my tradeSetting that I can access the associated data by typing: `td #{tradeSetting.ResourcePrice.Price}`

That doesn't make to much sense for me as I have nowhere provided the name "ResourcePrice". It was "ResourcePrices" (plural) everywhere. It's probably intended but this is way to much "magic" for me as this leads to confusion if you are new to sequelize.

**Comment by felixfbecker** [comment]
@crephix If it's plural or singular depends on the type of association. If it is one-to-many or many-to-many, the property will be an array, therefor plural. In your case it seems to be has-one or belongs-to, therefor singular and you get the object directly. You may face problems because you name your models in plural.

**Recommendations:**
1. Name your models in singular PascalCase, like it was a class (like `ResourcePrice`).
2. Always provide `as` to avoid inflection errors. The convention here is actually camelCase (like `resourcePrice`)
