### ISSUE TITLE
[mssql] dialect: issue with applying brackets to multipart table names

### ISSUE THREAD

**Issue by wilkog** [sequelize/sequelize#6225]
## What you are doing?

I'm defining a model which maps to a table (view) in the non default database (AppDB).

Model: 'InkoopOrder' and View: 'OtherDB.dbo.vw_InkoopOrder'

The dialect driver / plugin replaces 'OtherDB.dbo.vw_InkoopOrder' with '[OtherDB.dbo.vw_InkoopOrder]' this causes a sql error, it should be '[OtherDB].[dbo].[vw_InkoopOrder]'.

```js
	var sequelize = new Sequelize('AppDB', 'appdb-user', 'appdb-password', {
	  host: 'some-system',
	  port: 1433,
	  dialect: 'mssql',
	  dialectOptions: {
	  	instanceName: 'sqlexpress'
	  }
	});

	var InkoopOrder = sequelize.define('InkoopOrder', 
		{
			OrderNr: {
				type: Sequelize.STRING,
				primaryKey: true
			},
			BedrijfNr: {
				type: Sequelize.STRING
			},
			ActiviteitsCode: {
				type: Sequelize.STRING
			},
			StatusCode: {
				type: Sequelize.STRING
			}
		},
		{
			timestamps: false,
			tableName: 'OtherDB.dbo.vw_InkoopOrder'
		}
	)
```

## A possible fix

I already found the bug and applied a solution (see code below), but I don't know whether this introduces new bugs. As I'm not very familiar with githubs fork / push approach I thought it was best to put the bug with a solution here...

```js
  --- libs\dialects\mssql\query-generator.js, starting at line 511: ---

  // current code
  quoteIdentifier: function(identifier, force) {
    if (identifier === '*') return identifier;

    return '[' + identifier.replace(/[\[\]']+/g,'') + ']';
  }

  // patched code
  quoteIdentifier: function(identifier, force) {
    if (identifier === '*') return identifier;

    // check for multipart identifier
    if (identifier.indexOf('.') > -1) {
      var parts = identifier.split('.');
      for (var i = 0; i < parts.length; i++) {
        parts[i] = '[' + parts[i].replace(/[\[\]']+/g,'') + ']';
      }
      return parts.join('.');
    }

    return '[' + identifier.replace(/[\[\]']+/g,'') + ']';
  }
```

__Dialect:__ mssql
__Database version:__ Microsoft SQL Server 2012 – 11.0.5343.0 (X64)
__Sequelize version:__ 3.23.4

**Comment by janmeier** [comment]
We don't have great support for connecting models in different databases, see https://github.com/sequelize/sequelize/issues/2945, https://github.com/sequelize/sequelize/issues/2049 and https://github.com/sequelize/sequelize/issues/3023

You can use the `schema` option to add the `dbo` part.

**Comment by rogertcd** [comment]
@janmeier , thanks for your support, I have the same problem if I put the "dbo" part in schema option, the result is similar to: SELECT [FIELD1], [FIELD2] FROM [DATABASE.dbo].[TABLENAME] AS [table1] 
It doesn't work
Could you please help me with a solution?

**Comment by NoamWe** [comment]
I am having the same problem. 
It's 2019 perhaps there's a fix for that already?

**Comment by papb** [comment]
@NoamWe Can you please try OP's patch and see if it works for you?

**Comment by NoamWe** [comment]
@papb thank you so much for replying.
I'm pretty new to node.js so sorry if this question is stupid.
1. if I go and change code in the node_modules directory, I won't be able to use it in production, and that's a problem for me. Or am I wrong?
2. I searched the OP's code in here: node_modules/sequelize/lib/dialects/abstract/query-generator.js and could not find it. 
I am using sequelize 5.16.0. perhaps this code is no longer in use?

**Comment by papb** [comment]
> @papb thank you so much for replying.
> I'm pretty new to node.js so sorry if this question is stupid.

Don't worry, feel free to ask anything! If it's easy to respond that's better for me, not worse :grimacing:

> 1. if I go and change code in the node_modules directory, I won't be able to use it in production, and that's a problem for me. Or am I wrong?

You're right (you could make some dirty hacks but I don't recommend that). When I asked this, the goal was just to see if it works, by no means it shall be a permanent solution. Once you tell me that it works we shall proceed to work out a real fix.

> 2. I searched the OP's code in here: node_modules/sequelize/lib/dialects/abstract/query-generator.js and could not find it.
>    I am using sequelize 5.16.0. perhaps this code is no longer in use?

Hmm, looks like the code was refactored, the `quoteIdentifier` is now in another file: [here](https://github.com/sequelize/sequelize/blob/4478d74a3e5dc8cd30837d8a193754867d06ccf5/lib/dialects/abstract/query-generator/helpers/quote.js#L35).

**Comment by marcelo-haytek** [comment]
> @papb thank you so much for replying.
> I'm pretty new to node.js so sorry if this question is stupid.
> 
> 1. if I go and change code in the node_modules directory, I won't be able to use it in production, and that's a problem for me. Or am I wrong?
> 2. I searched the OP's code in here: node_modules/sequelize/lib/dialects/abstract/query-generator.js and could not find it.
>    I am using sequelize 5.16.0. perhaps this code is no longer in use?

I did the first thing and changed the node_modules and it worked... but there's no way around to carry this into my production code??? The added brackets in the fields makes my queries fail... i removed in the node_modules and it all begun to work.
