### ISSUE TITLE
Publish from travis

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#6227]
Use https://www.npmjs.com/package/publish + an NPM token to automate publishing from travis when we push new tags.

**Comment by sushantdhiman** [comment]
So whenever we bump version in package.json, it will automatically do publish. Thats really good :)

If CI run was successful it will do publish. No extra overhead on CI ?

**Comment by mickhansen** [comment]
`npm version major|minor|patch` handles bumping the package and creating a tag, travis would then publish when that commit is pushed.

Next to no overhead, it would not run as part of a job (atleast i don't image so) and with the `publish` package it takes a few seconds to publish.

**Comment by overlookmotel** [comment]
That sounds great!

Maybe a stupid question, but presumably the script can be configured not to run on PRs? Otherwise if I submit a PR which includes a version bump, hey presto I've published my PR to npm!

**Comment by sushantdhiman** [comment]
@overlookmotel Great point, I am sure there will be some sort of safeguards. But I am not familiar with with publish package either.

**Comment by mickhansen** [comment]
travis can be configured to only run the deployment code on master or tags IIRC

**Comment by mickhansen** [comment]
but in any case PRs should not include version changes since we cant maintain releases with git tags then ;p

**Comment by overlookmotel** [comment]
Yeah, but my point was that it would be a security hole if anyone could submit a PR with arbitrary code and it automatically gets deployed to npm. I assume this can be prevented (and it's probably obvious), but I thought it worth mentioning just to be sure.
