### ISSUE TITLE
Exclude createdAt, updatedAt, deletedAt from defaultScope easily

### ISSUE THREAD

**Issue by gauravarora** [sequelize/sequelize#6229]
I am currently going about adding 
```
defaultScope: {
      attributes: {
        exclude: ['created_at', 'updated_at']
      }
    }
```
I would request that an easier way be added so we can exclude default timestamp properties. It also appears that the excluded properties must be defined by name depending on the value of ```underscored```. This is a little fragile in case the value is changed globally.

**Comment by janmeier** [comment]
Do you want to remove them completely from the table, or do you just not want to select them by default?

**Comment by gauravarora** [comment]
I'd just like to remove them from queries by default.

**Comment by janmeier** [comment]
You can do 
```js
new Sequelize(..., {
  define: {
    defaultScope ...
  }
});
```
That adds a default scope to all models (but it will be overridden if you create a default scope on a model.

**Comment by gauravarora** [comment]
I don't know how I missed that. Thanks @janmeier

**Comment by hemanjosko** [comment]
```
{ 
    timestamps: false,
}
```

**Comment by stormbytes** [comment]
> ```
> { 
>     timestamps: false,
> }
> ```

Where did you find this?

**Comment by raphaelmro** [comment]
@stormbytes
https://sequelize.org/v5/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

Take a look at the code snippet that says:
> Specify options, which are used when sequelize.define is called.
> The following example:
> `define: { timestamps: false }`
>  is basically the same as:
> `Model.init(attributes, { timestamps: false });`
> `sequelize.define(name, attributes, { timestamps: false });`
> so defining the timestamps for each model will be not necessary
