### ISSUE TITLE
Postgres migration support for UNIQUE

### ISSUE THREAD

**Issue by paulmars** [sequelize/sequelize#623]
```
    migration.changeColumn(
      'Users',
      'name',
      {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true
      }
    );
```

generates

```
ALTER TABLE "Users" ALTER COLUMN "name" SET NOT NULL;ALTER TABLE "Users" ALTER COLUMN "name" DROP DEFAULT;ALTER TABLE "Users" ALTER COLUMN "name" TYPE VARCHAR(255)  UNIQUE;
```

The last part is wrong, it needs to generate something that looks like this:

```
ALTER TABLE "Users" ADD CONSTRAINT name_key UNIQUE ("name");
```

**Comment by IAMprodigi** [comment]
hmm. Still an issue?

0|| Model initialization error: Error
0||     at Query.run (D:\workspace\\server\node_modules\sequelize\lib\dialects\postgres\query.js:50:25)
0||     at D:\workspace\\server\node_modules\sequelize\lib\sequelize.js:315:28
0||     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
0||     at async tbl_Types.sync (D:\workspace\\server\node_modules\sequelize\lib\model.js:984:11)
0||     at async Sequelize.sync (D:\workspace\\server\node_modules\sequelize\lib\sequelize.js:377:9)
0||     at async buildCfg.init_models (D:\workspace\\server\db\db.js:46:17)
0||     at async module.exports (D:\workspace\\server\db\db.js:533:12)
0||     at async initializeApp (D:\workspace\\server\app.js:29:20) {
0||   name: 'SequelizeDatabaseError',
0||   parent: error: syntax error at or near "UNIQUE"

0||     sql: `ALTER TABLE "tbl_Types" ALTER COLUMN "slug" DROP NOT NULL;ALTER TABLE "tbl_Types" ALTER COLUMN "slug" DROP DEFAULT;ALTER TABLE "tbl_Types" ALTER COLUMN "slug" TYPE VARCHAR(100) UNIQUE; COMMENT ON COLUMN "tbl_Types"."slug" IS 'Unique identifier for the type';`,
