### ISSUE TITLE
Lower/uppercase issue when using another model's id as an attribute

### ISSUE THREAD

**Issue by TeemuKoivisto** [sequelize/sequelize#6232]
So I have development db for my app that uses SQLite and in my code I update model's data with lazy ES6 shortcut like this:

```js
  setGraderEvalDone(thesisId) {
    return this.getModel().update({
      graderEvalDone: true,
    }, {
      where: { thesisId, },
    });
  }
```

So thesisId : thesisId and surprisingly it works with SQLite and no error was ever thrown by this as I now know it to be incorrect. Because I declare my model as "Thesis" any reference to that model should begin with "Thesis" I presume. Funnily enough when I use that same statement on my production version which has Postgres that aforementioned statement causes my query to freeze and throw server timeout error 504.

So I humbly request someone to fix this small but annoying inconsistency between SQLite and Postgres. In hindsight it is kinda lazy to use different db for development but well convenience brought me over to Sequelize in first place so I take no responsibility :neckbeard:

**Comment by janmeier** [comment]
Please create a [SSCCE](HTTP://SSCCE.ORG/)

If your model name is upper case, the foreign keys will be as well, unless you use the `foreignKey` option in associations

**Comment by TeemuKoivisto** [comment]
This works with SQLite but not with Postgres:
```js
  setGraderEvalDone(thesisId) {
    return this.getModel().update({
      graderEvalDone: true,
    }, {
      where: { thesisId: thesisId },
    });
  }
```

This works with both:
```js
  setGraderEvalDone(thesisId) {
    return this.getModel().update({
      graderEvalDone: true,
    }, {
      where: { ThesisId: thesisId },
    });
  }
```

**Comment by janmeier** [comment]
Please show a complete test case, including models and associations

**Comment by TeemuKoivisto** [comment]
Models:

```js
const Thesis = seq.define("Thesis", {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
  authorFirstname:
  {
    type: Sequelize.STRING,
    validate: {
      notEmpty: true,
    },
  },
  authorLastname:
  {
    type: Sequelize.STRING,
    validate: {
      notEmpty: true,
    },
  },
  authorEmail: {
    type: Sequelize.STRING,
    validate: {
      isEmail: true,
      notEmpty: true,
    },
  },
  title: {
    type: Sequelize.STRING,
    validate: {
      notEmpty: true,
    },
  },
  urkund: {
    type: Sequelize.STRING,
  },
  ethesis: {
    type: Sequelize.STRING,
  },
  grade: {
    type: Sequelize.STRING,
    validate: {
      notEmpty: true,
      isIn: [[
        "Approbatur",
        "Lubenter Approbatur",
        "Non Sine Laude Approbatur",
        "Cum Laude Approbatur",
        "Magna Cum Laude Approbatur",
        "Eximia Cum Laude Approbatur",
        "Laudatur",
      ]],
    },
  },
  deadline: {
    type: Sequelize.DATE,
    validate: {
      isDate: true,
      notEmpty: true,
    },
  },
  graderEval: {
    type: Sequelize.TEXT,
  },
});

const ThesisProgress = seq.define("ThesisProgress", {
  id: { type: Sequelize.INTEGER, autoIncrement: true, primaryKey: true },
  ethesisDone: { type: Sequelize.BOOLEAN, defaultValue: false },
  graderEvalDone: { type: Sequelize.BOOLEAN, defaultValue: false },
  printDone: { type: Sequelize.BOOLEAN, defaultValue: false },
  done: { type: Sequelize.BOOLEAN, defaultValue: false },
});

// they have a bunch of other associations but I believe they are rather meaningless concerning this
ThesisProgress.belongsTo(Thesis);
Thesis.hasOne(ThesisProgress);
```

The libraries and other are:
Node 5.9.1
"pg": "^4.5.2",
 "pg-hstore": "^2.3.2",
"sequelize": "^3.19.3",
 "sqlite3": "^3.1.3"

Postgres versions were 9.6 and 9.3

And I do not really know what else you'd want me to tell you. I mean simple as that, Sequelize automatically or SQLite, corrects the faulty lowercase model name to uppercase. Which doesn't happen with Postgres causing a hard-to-track bug.

**Comment by janmeier** [comment]
Sqlite ignores the casing of table and column names - see http://www.alberton.info/dbms_identifiers_and_case_sensitivity.html

There's not really anything we can do about that in sequelize

**Comment by Anubis523** [comment]
This is also a problem when using Postgres. I just capitalize everything now.
