### ISSUE TITLE
http://readthedocs.io site doesn't work.

### ISSUE THREAD

**Issue by vteremasov** [sequelize/sequelize#6234]
http://readthedocs.io site doesn't work right now! Could you add more add full doc in github MD?

**Comment by janmeier** [comment]
The full docs are already here https://github.com/sequelize/sequelize/tree/master/docs

**Comment by vteremasov** [comment]
Yeah! Sorry. Found it. Created issue because of this link in index.md follows nowhere https://github.com/sequelize/sequelize/blob/master/docs/docs/getting-started
That's the was a problem. But, anyway, it should be fixed. Don't need for a new issue I guess?

**Comment by janmeier** [comment]
That link is not in index.md? https://github.com/sequelize/sequelize/blob/master/docs/index.md

The links are correct on rtd, but not on github - unfortunately we can only have one be correct

**Comment by vteremasov** [comment]
Ok, I see, thank you! I know it's not a place for questions here, but can you answer or say where can I ask you: I needed some actions for finding and getting entities like encoding and decoding id's because I store them in Buffer. So I found some hooks I need when was digging the source code which not described in docs such as `beforeFind` and so on. Is it ok to use it in my code and is there any other options to realize such functionality?

**Comment by janmeier** [comment]
Currently https://github.com/sequelize/sequelize/blob/master/lib/hooks.js - I'm rewamping the docs, which should hopefully include all the hooks
