### ISSUE TITLE
UPSERT adding `OR "unique indexes"` to update's where clause

### ISSUE THREAD

**Issue by ke1Del** [sequelize/sequelize#6240]
While using `upsert` on a table with unique indexes, I found that the `UPDATE` part of the generated query is not what I expected.

Quick demonstration:
`Demo` model:

``` js
"use strict";

module.exports = function (sequelize, DataTypes) {
    let Demo = sequelize.define("Demo", {
        id      : {
            type         : DataTypes.STRING,
            field        : "id",
            primaryKey   : true,
        },
        unique1 : {
            type  : DataTypes.STRING,
            field : "unique1",
        },
        unique2 : {
            type  : DataTypes.STRING,
            field : "unique2",
        },
    }, {
        indexes : [{
            unique : true,
            fields : ["unique1", "unique2"],
            where  : {
                unique2 : {$ne : null},
            },
        }, {
            unique : true,
            fields : ["unique1"],
            where  : {
                unique2 : null,
            },
        }],
    });

    return Demo;
};
```

Do an upsert:

``` js
let Seq = require("sequelize"),
    db  = new Seq("demo", "demo", "demo", {});  // Fill with your settings

db.Demo = db.import("./Demo.js");
db.sync()
.then(() => {
    db.Demo.destroy({truncate : true});
    db.Demo.bulkCreate([{
        id      : "1",
        unique1 : "1",
        unique2 : "1",
    }, {
        id      : "2",
        unique1 : "2",
        unique2 : "2",
    }]);

    db.Demo.upsert({
        id      : "1",
        unique1 : "1",
        unique2 : "2",
    });
});
```

Queries:

``` sql
Executing (default): TRUNCATE "Demos"
Executing (default): INSERT INTO "Demos" ("id","unique1","unique2","createdAt","updatedAt") VALUES ('1','1','1','2016-07-07 10:47:32.508 +00:00','2016-07-07 10:47:32.508 +00:00'),('2','2','2','2016-07-07 10:47:32.508 +00:00','2016-07-07 10:47:32.508 +00:00');
Executing (default): CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $func$ BEGIN INSERT INTO "Demos" ("id","unique1","unique2","createdAt","updatedAt") VALUES ('1','2','2','2016-07-07 10:47:32.523 +00:00','2016-07-07 10:47:32.523 +00:00'); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE "Demos" SET "id"='1',"unique1"='2',"unique2"='2',"updatedAt"='2016-07-07 10:47:32.523 +00:00' WHERE ("id" = '1' OR ("unique1" = '2' AND "unique2" = '2') OR "unique1" = '2'); RETURN 2; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
```

My issue is with: `UPDATE (...) WHERE ("id" = '1' OR ("unique1" = '1' AND "unique2" = '2') OR "unique1" = '1')`
The [upsert function](https://github.com/sequelize/sequelize/blob/v3.23.4/lib/query-interface.js#L508) is adding the unique key fields to the WHERE clause even though the PK is already present, which doesn't make a lot of sense to me. Even worst, it's doing it using `OR` which might cause unwanted behavior (I know at first glance using unique indexes sounds fine but unique indexes can be nullable and have where clauses, so it's not so straightforward).
Furthermore, the model's `index` field [allows a `where` clause](http://docs.sequelizejs.com/en/latest/docs/models-definition/#indexes) which is not being taken into account while adding the unique keys to the WHERE clause.

What I would expect/suggest: 
- When PK is present, use only the PK on the WHERE clause;
- I would agree/understand the use of unique indexes as PK if the PK is not available (i.e. either if the table doesn't have one or if it was not provided to the upsert);
  - If using unique indexes as PK, it should at least take into account it's own where clause.

**Dialect:** any
**Sequelize version:** 3.23.4

**Comment by janmeier** [comment]
If PK is present, it definitely makes sense to only upsert on that - PR welcome :)

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/8552
