### ISSUE TITLE
Group and then filter?

### ISSUE THREAD

**Issue by kristoffernolgren** [sequelize/sequelize#6241]
I want to get one item per user and remove all items where the riderId is set:

```
return Hail.findAll({
    group: 'riderId',
    where: {
        driverId: null
    }
})
```

This doesn't work ofcorse because the filtering happens first so it just picks another item for each riderId. I tried to use $and aswell, but that is only for `where` as far as I can understand.

With this data:
```
"id"    "driverId"  "userId"
"1"     "NULL"      "2"
"2"     "NULL"      "3"
"3"     "NULL"      "1"
"4"     "1"         "1"
```
I would like to get id 1 and 2 back. But now i'm getting 1, 2 and 3.

I would like to first get items by userID, 1,2 and 4. and then remove driverId because driverID !== NULL.

Something like this:
```
SELECT id, lat, lon, createdAt, updatedAt, driverId, riderId
FROM hails hail
WHERE hail.riderId IN (SELECT riderId FROM hails WHERE driverId IS NOT NULL) AND hail.driverId IS NOT NULL
GROUP BY riderId;

```

**Comment by janmeier** [comment]
Can you give some context please? What do your models look like? - Can you formulate what you want to achieve in SQL? Perhaps some demo data?

**Comment by kristoffernolgren** [comment]
updated

**Comment by janmeier** [comment]
Whats the value of riderId? Please read up on [SSCCE](HTTP://SSCCE.ORG/)
