### ISSUE TITLE
How to prevent inner join when querying

### ISSUE THREAD

**Issue by JasonFang93** [sequelize/sequelize#6242]
Hi~
Two models is associated by `belongsToMany` function, eg: `Project.belongsToMany(User, { through: UserProject })` , I can get all user datas which are associated with the project by `project.getUsers()` . However, the join table will be selected by inner join at the same time. I hope to prevent that.
AnyOne, who can help me ? Thanks inadvance.

**Comment by mickhansen** [comment]
Join table has to be selected by inner join, otherwise you can get inconsistent data with paranoid join tables.

Not possible to disable, not sure why you'd need to (it should be scoped so it doesn't have any effect on the rest).

Show SQL you think might be incorrect.

**Comment by JasonFang93** [comment]
@mickhansen The datas I have selected are too many and the data from join table is not essential. So I have to delete the data that I don't need . Is there any good methods?

**Comment by mickhansen** [comment]
@JasonFang93 Not sure i understand

**Comment by JasonFang93** [comment]
That is to say, I hope to reduce the size of the data which I have selected. I get. Thanks ~

**Comment by JasonFang93** [comment]
Keeping inner join when select, the data of userProjects table(not users or projects) doesn't be returned when i select. Can do this by some settings? @mickhansen

**Comment by mickhansen** [comment]
`include.through.attributes = []` is supposed to work, but doesn't atm (needs to be fixed)

**Comment by JasonFang93** [comment]
Thanks , let me try~

**Comment by JasonFang93** [comment]
Thanks , let me try~ @mickhansen
