### ISSUE TITLE
using scopes removes foreign keys?

### ISSUE THREAD

**Issue by contra** [sequelize/sequelize#6245]
## What you are doing?

``` js
const scopes = {
  public: {
    attributes: {
        exclude: ['secret']
    }
  }
}

// imagine i made a model named User with two fields:
// - secret
// - name
User.belongsTo(City) // user now has cityId field

User.scope('public').findById(123).then((user) =>
  // user === { id: 123, name: 'Bob' }
)
```
## What do you expect to happen?

The foreign key `cityId` should exist on the result
## What is actually happening?

The foreign key `cityId` does not exist on the result

When not using scopes, cityId appears in the result as expected.

**Dialect:** postgres
**Sequelize version:** 3.23.4

**Comment by mickhansen** [comment]
That's highly odd, can you post a full SSCCE? https://github.com/sequelize/sequelize/blob/master/sscce_template.js

**Comment by janmeier** [comment]
I'm pretty sure this happens because scopes are converted from `attributes: { include, exclude }` to `attributes: [..]` when the model is defined - at which point the foreign keys have not been added yet

**Comment by contra** [comment]
@janmeier That would actually explain it if that's how things are implemented currently

**Comment by contra** [comment]
SSCE:

```js
var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

// boilerplate
const City = sequelize.define('city', {
  name: Sequelize.STRING
})

const User = sequelize.define('user', {
  name: Sequelize.STRING,
  secret: Sequelize.STRING
}, {
  scopes: {
    public: {
      attributes: {
        exclude: ['secret']
      }
    }
  }
})
User.belongsTo(City)

const makeCity = () => City.create({ name: 'Test' })
const makeUser = () =>
  makeCity().then((city) =>
    User.create({
      name: 'Bob',
      city: city
    })


// actual problem, code exactly the same as first comment
makeUser().then((ourUser) => {
  User.scope('public').findById(ourUser.id).then((user) =>
    // user === { id: 123, name: 'Bob' }
  )
})
```

For the record, it's really cumbersome to go through this SSCE rigmarole for an issue this simple to repro - might be worth revisiting this policy. Seems like a serious deterrent for people who want to report bugs and contribute on issues.

**Comment by contra** [comment]
Any word on this? Didn't get a response

**Comment by felixfbecker** [comment]
@contra Could you try first defining the model, then associating, and then using `addScope()` to add the scope?

**Comment by contra** [comment]
@felixfbecker That fixes it

**Comment by felixfbecker** [comment]
Great. The only real fix I think would be to store the scopes raw and normalize JIT, but that might have have a small performance impact.

**Comment by contra** [comment]
@felixfbecker Sounds good to me

**Comment by xxxtonixxx** [comment]
I use a function instead of objects and it works 👍 

An example:
```javascript
scopes: {
    teachers: () => ({
        where: {
            rol: TEACHER,
        },
    }),
    public: () => ({
        attributes: {
            exclude: ['password'],
        },
    }),
},
```

**Comment by scottbeacher** [comment]
I'm having this issue when trying to define a defaultScope that uses `exclude` in `attributes`. @felixfbecker is there a way to use `addScope` to modify the defaultScope? Trying to override it with `addScope('defaultScope')` doesn't seem to work.

**Comment by DMan577** [comment]
You need to pass `{override: true}` to the 3rd parameter of `addScope` to override it. 
`addScope('defaultScope', {...}, {override:true} `

**Comment by scottbeacher** [comment]
That worked, thank you.

**Comment by contra** [comment]
Keep it open.

**Comment by contra** [comment]
Still an issue.

**Comment by xxxtonixxx** [comment]
> Still an issue.

**Comment by contra** [comment]
Keep it open. Can we get any response here to get rid of this stale bot? I've bumped this for months and the ticket has been open for 1.5 years.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/commit/88a340dacec0b1b27d4f67866e2b416482ce7b85
