### ISSUE TITLE
[Associations] Method remove[Association] doesn't exist

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6249]
How to remove associations. Neither `remove`, nor `delete`, nor `destroy` methods exist.
But docs say they do http://sequelize.readthedocs.io/en/latest/docs/associations/#associating-objects
```
project.removeTask(task1).then(function() {})
```

Example:
```
UserAccount.hasOne(UserSession);

UserAccount.sequelize.transaction(function(t) {
    return UserAccount.findOne({
            where: {
                email: _email
            }
        }, { transaction: t }
    )
    .then(user => {
        return user.removeUserSession  (
            { transaction: t }
        )
        .then(rowsDestroyed => {
            // Never here, no user.removeUserSession  
        })
    })
})
.then(...)
.catch(...)

// No one of these methods exist
user.destroyUserSession  // undefined
user.deleteUserSession  // undefined
user.removeUserSession  // undefined

user.destroyUserSessions  // undefined
user.deleteUserSessions  // undefined
user.removeUserSessions  // undefined
```

**Comment by janmeier** [comment]
Please show your model definitions. You can also try to inspect `User.Instance.prototype` to see what methods are available

**Comment by sushantdhiman** [comment]
`hasOne` doesn't offer `removeAssociation` accessors ( [docs](http://sequelize.readthedocs.io/en/latest/api/associations/has-one/) ). You can use `setAssociation(null)` to achieve same result.

Example that you have linked to is for `belongsToMany`
