### ISSUE TITLE
documentation not working

### ISSUE THREAD

**Issue by r45r54r45** [sequelize/sequelize#6250]
certainly, some documents are not available. 
it shows 
 

Service

The service is temporarily unavailable. Please try again later.

where can i see documents?

**Comment by sushantdhiman** [comment]
We use http://readthedocs.org for docs, It seems to be down atm

**Comment by r45r54r45** [comment]
too sad ㅠㅠ when can i expect to see it again?

**Comment by sushantdhiman** [comment]
Please use https://github.com/sequelize/sequelize/tree/master/docs until the service is restored

**Comment by r45r54r45** [comment]
thx
