### ISSUE TITLE
beforeUpdate not called when updated via model where.

### ISSUE THREAD

**Issue by abelbarbosa** [sequelize/sequelize#6253]
Hi. I'm trying to to hash a password before updating an object.

**model:**
```js
module.exports = function (sequelize, DataTypes) {
	var User = sequelize.define("user", {
		//attributes
	}, {
			hooks: {
				beforeCreate: function (user) {
					user.password = user.getHash(user.password);
				},
				beforeUpdate: function (user) {
					if (user.password) {
						user.password = user.getHash(user.password);
					}
				}
			},
			instanceMethods: {
				getHash: function (password) {
					return hash(password);
				}
			}
		});

	return User;
};
```

**update code:**
```js
return models.user.update(uData, {
	where: { id: req.body.id }
}).then(function () {
	res.end();
});
```
## Expected
The hook beforeUpdate should be called before persisting the changes.

## What is actually happening?
The changed are saved but the hook "beforeUpdate" is never called unless I change the code to something like this:
```js
return user.findOne({
	where: { id: req.body.id }
}).then(function (result) {
	return result.update(uData).then(function () {
		res.end();
	});
});
```

Is this the expected behaviour? Am I doing something wrong?

__Dialect:__ postgres
__Database version:__ 9.5.3
__Sequelize version:__ 3.23.3

**Comment by janmeier** [comment]
You're looking for `beforeBulkUpdate `

**Comment by abelbarbosa** [comment]
Oh ok. That makes sense. Thank you

**Comment by shuperry** [comment]
I worked this out, `beforeUpdate` hook called when use `instance.save()` or `instance.update()`, when use `model.update()`, `beforeBulkUpdate ` will be called.

**Comment by abelbarbosa** [comment]
@shuperry janmeier Yes you are correct, janmeier already helped me to figure this one out. Nevertheless, thank you for your help.

**Comment by yusbel80** [comment]
You may also pass `individualHooks: true` for beforeUpdate to trigger

**Comment by ronak2898** [comment]
even in Default Hooks beforeUpdate is not working however bulkupdate is working
