### ISSUE TITLE
Joining sequelize model with some data (defined with VALUES)

### ISSUE THREAD

**Issue by lbeschastny** [sequelize/sequelize#6254]
I've been optimizing one of our API endpoints (I've tried to minimize the number of calls to PostgreSQL and maximize query index coverage).

In the end I've came up with something like this:

```sql
SELECT
  "foo",
  "bar",
  "baz"
FROM
  "Table", 
  (VALUES
    ('foo 1', 'bar bar%'),
    ('foo 2', 'bar baz%')
  ) AS data(c1, c2)
WHERE
  "Table"."foo" = data."c1" AND
  "Table"."bar" LIKE data."c2";
```

So basically I want to `JOIN` one of my models with an explicit table made from user data.

Is there any way to express this kind of query with `sequelize`?

**Comment by sushantdhiman** [comment]
It looks like you will have to do a custom query for this one using `sequelize.query`, We don't have any way to specify custom table selection like this under current implementation.
