### ISSUE TITLE
Creating an index with custom operator class in PostgreSQL

### ISSUE THREAD

**Issue by lbeschastny** [sequelize/sequelize#6255]
PostgreSQL support [several operator classes][1], i.e.:

```sql
CREATE INDEX test_index ON test_table (col varchar_pattern_ops);
```

Right now we could _cheat_ `sequelize` by passing operator class instead of on `order`:

```js
indexes: [{
  method: 'BTREE',
  fields: [{
    name: 'foo'
  }, {
    name: 'bar',
    order: 'text_pattern_ops'
  }]
}]
```

But it will break all others dialects.

 [1]: https://www.postgresql.org/docs/9.5/static/indexes-opclass.html

**Comment by BridgeAR** [comment]
There is a option to set the operator class directly. Check http://sequelize.readthedocs.io/en/latest/docs/models-definition/#indexes

**Comment by lbeschastny** [comment]
@BridgeAR thanx!
