### ISSUE TITLE
$or turns into $and

### ISSUE THREAD

**Issue by buzzijavier** [sequelize/sequelize#6256]
Im not sure if i encountered a bug or its just late and im tired, but im running this query:

```
({
  where: {
    $or: [
      {
        airportCode: {
          $ilike: "%" + req.query.q + "%"
        },
        airportName: {
          $ilike: "%" + req.query.q + "%"
        }
      }
    ]
  }
});
```

and the output is:

`SELECT * FROM "airport" AS "Airport" WHERE (("Airport"."airportCode" ILIKE '%aaa%' AND "Airport"."airportName" ILIKE '%aaa%')) ORDER BY "airportCode" LIMIT 10`

instead of:

`SELECT * FROM "airport" AS "Airport" WHERE (("Airport"."airportCode" ILIKE '%aaa%' OR "Airport"."airportName" ILIKE '%aaa%')) ORDER BY "airportCode" LIMIT 10`

__Dialect:__ postgres
__Database version:__ 9.4.4
__Sequelize version:__ 3.23.4

**Comment by mickhansen** [comment]
Try removing the array:

```js
$or: {
  airportCode: {
    $ilike: "%" + req.query.q + "%"
  },
  airportName: {
    $ilike: "%" + req.query.q + "%"
  }
 }
 ```

**Comment by mickhansen** [comment]
If you do want to use an array, airportCode/airportName should be seperate entities in the array.

**Comment by buzzijavier** [comment]
Confirmed. It works. Damn im tired. Thanks!

**Comment by sushantdhiman** [comment]
Issue resolved :), Closing.
