### ISSUE TITLE
Converting enum using setters / getters while using where clause

### ISSUE THREAD

**Issue by ivanwagner** [sequelize/sequelize#6259]
## What you are doing?
I'm using a model with an enum column (type) as follows:
```
module.exports = function(sequelize, DataTypes) 
   return sequelize.define('Fruits', {
        id: {
            type: DataTypes.INTEGER,
            field: 'id',
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
       type: {
            type: DataTypes.ENUM,
            values: ['Apple', 'Banana', 'Orange'],
            field: 'type',
            allowNull: false,
            get: function() {
              var val = this.getDataValue('type');
              if (val == 'a') {
                return 'Apple';
              } else if (val == 'b') {
                return 'Banana';
              } else if (val == 'o') {
                return 'Orange';
              } else {
                return 'None';
              }
            },
            set: function(value) {
              if (value == 'Apple') {
                return this.setDataValue('type', 'a');
              } else if (value == 'Banana') {
                return this.setDataValue('type', 'b');
              } else if (value == 'Orange') {
                return this.setDataValue('type', 'o');
              }
            },
        },
        created: {
            type: DataTypes.DATE,
            field: 'created',
            allowNull: true
        },
        lastModified: {
            type: DataTypes.DATE,
            field: 'last_modified',
            allowNull: true
        }
    }, {
        schema: 'public',
        tableName: 'fruits',
        timestamps: false
    });
```

I'm using the enum because within the db table I've set the column as a single character but when I set / get data from sequelize I have the "friendly" translation of what the value actually means (o is Orange, b is Banana and a is Apple).

Everything works fine with the exception of when I query the table and search for a specific fruit type using findAll and where as follows:

`model.Fruits.findAndCountAll({ where: { type: 'Banana' } })`

I'd like that Banana gets converter to b within the model to actually make the query.

I'm using Postgres 9.1 and Sequelize version: 3.23.4

Thank you very much,

**Comment by janmeier** [comment]
I'd recommend using a beforeFind hook to alter the options - look for type in options.where and alter it to the correct value. 

Do keep in mind that this will only work for regular finds. So if you for example want to do a bulk update where type = banana, you need a beforeBulkUpdate hook as well. 

Personally, I think I would just use the db values in the query to avoid confusion
