### ISSUE TITLE
Migrations with n:m relations

### ISSUE THREAD

**Issue by jdnichollsc** [sequelize/sequelize#6260]
## What you are doing?

Creating migrations to the relations of the tables with postgres
## What do you expect to happen?

Any example to use the migrations with associations in the best way
## What is actually happening?

There are no examples

**Dialect:** postgres
**Sequelize version:** ^3.23.4

**Comment by sushantdhiman** [comment]
Thank you for following the Issue template :) 

Yeah docs are pretty much lacking in the migration department. Tagging this as `documentation` update.

Basic thing in N:M migration is to use correct keys in `through` migration and set `cascade `etc correctly. Migration mostly looks just like model definition along with some `addIndex` or `removeIndex` queries in the mix.

Here is a case where camel cased keys are used.

**User Migration**

```js
'use strict';
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('users', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      deletedAt: {
        allowNull: true,
        type: Sequelize.DATE
      }
    });
  },
  down: function(queryInterface) {
    return queryInterface.dropTable('users');
  }
};
```

**Project Migration**

```js
'use strict';
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('projects', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      deletedAt: {
        allowNull: true,
        type: Sequelize.DATE
      }
    });
  },
  down: function(queryInterface) {
    return queryInterface.dropTable('projects');
  }
};
```

**UserProject Migration**

```js
'use strict';
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('userprojectmap', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      userId: {
        type: Sequelize.INTEGER,
        references: { model: 'users', key: 'id' },
        onDelete: 'CASCADE'
      },
      projectId: {
        type: Sequelize.INTEGER,
        references: { model: 'projects', key: 'id' },
        onDelete: 'CASCADE'
      }
    });
  },
  down: function(queryInterface) {
    return queryInterface.dropTable('userprojectmap');
  }
};
```

**Comment by jdnichollsc** [comment]
Is possible create these migrations using the CLI? :+1:

**Comment by sushantdhiman** [comment]
Yes, `model:create` command will create both model and migration

**Comment by jdnichollsc** [comment]
But only the User and Project, how is with the UserProject?

Thanks for your help my friend! :dancers:

**Comment by sushantdhiman** [comment]
Well you need to define the through model as well, because you need that model when associating using BelongsTo, Like

```js
ModelM.belongsTo(ModelN, { through: ModelMN }) // need through model here 
```

So you have to create this junction model too, using `model:create`

**Comment by dmbrowne** [comment]
is there a way to specify a name for the key, of the foreignKey constraint?

**Comment by NilsBaumgartner1994** [comment]
push

**Comment by shailesh-kanzariya** [comment]
@sushantdhiman Thank you, this is almost complete migration example for many-to-many.
I read in doc that when 'junction-model' is created, sequelize also adds 'composite unique key'. 
How do we add such 'composite unique key' in this migration-example?

**Comment by YoannBuzenet** [comment]
This info is still hard to find.

By chance, would you have an example of bulkinsert (with seeds) for a NN relation ?
