### ISSUE TITLE
Question regarding n:m relationships

### ISSUE THREAD

**Issue by ybrodsky** [sequelize/sequelize#6261]
I know this is not stackoverflow, but I am guessing you are most suitable to erradicate this doubt I have, which is primarily a doubt regarding how much of a headache (or not) will sequelize do this for me.

I have two models related in a way that's similar to this example of the doc:

```
User = sequelize.define('user', {})
Project = sequelize.define('project', {})
UserProjects = sequelize.define('userProjects', {
    status: DataTypes.STRING
})
 
User.belongsToMany(Project, { through: UserProjects })
Project.belongsToMany(User, { through: UserProjects })
```

What I would like to do is to create a project and associate it several users. My data would look similar to this:

```
{
  somefield: 'foo',
  users: [
    {
      id: 1
    },
    {
      id: 2
    }
  ]
}
```

That's my idea. When I create a Project I want to specify the users to which it is associated. I also want to be able to update Project and add/remove users associated.

So, my question is: is the n:m relationship in this case the best choise? Will sequelize be friendly enough for me to do what I want to do? Or perhaps I will be better of breaking this association into a couple of hasMany (Project hasMany UserProject, User hasMany UserProject)?

Hope it's clear, any guidance is appreciated.

**Comment by sushantdhiman** [comment]
Please refrain from asking "questions" on Github , You can use [Slack](sequelize.slack.com) or StackOverflow :)

- You have N Users who can have M Project
- You want to be able to Edit Users without disturbing Projects and vice versa
- You want be able to add / remove Users from Project, without disturbing any existing relations 

You should go for N:M relation i.e [belongsToMany ](http://docs.sequelizejs.com/en/latest/docs/associations/#belongs-to-many-associations), just like the example you have used. If you read [Association ](http://docs.sequelizejs.com/en/latest/docs/associations/#associating-objects)section in docs you will get all answers there.
