### ISSUE TITLE
When sequelize close connection pool?

### ISSUE THREAD

**Issue by furyscript** [sequelize/sequelize#6265]
Hi, I have an ask about sequelize pool config.

When sequelize release a connection after some user make a query in throught API? I need to call some methods after query finished or it is automatically?

**Comment by mickhansen** [comment]
It closes after the configured idle timeout after the latest use.

**Comment by furyscript** [comment]
So with this configuration `pool: { max: 500, idle: 10000 },` I have max 500 contemporary connections and it closes ONE connection after 10000 ms?

**Comment by sushantdhiman** [comment]
If any connection was not used for `10000ms` pool will release it. We support debug module https://github.com/sequelize/sequelize/pull/6117, You can use it to check when connections are released or acquired.

**Comment by furyscript** [comment]
Ok! Thanks a lot!!
