### ISSUE TITLE
Coroutine yield handler

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#6266]
I'm now close to solving the problems with CLS and coroutines - see https://github.com/sequelize/sequelize/issues/6116#issuecomment-232377612

Therefore the time of coroutines is almost upon us! Next question is how to implement.

Method of wrapping ES6 class methods is being covered in https://github.com/sequelize/sequelize/issues/6116.

But also there's the question of yield handlers.

`Bluebird.coroutine()` out of the box only supports yielding a Promise i.e. `yield promise`. But [co](https://www.npmjs.com/package/co) adds other options like yielding an array of promises for parallel execution (`yield [promise, promise, promise]` as sugar for `yield Promise.all( [promise, promise, promise] )`).

I've been using [co](https://www.npmjs.com/package/co) for a long time and find these extra features invaluable. But I think we'd need to stick with `Bluebird.coroutine()` to maintain CLS support, performance, and nice stack traces. `Bluebird.coroutine.addYieldHandler()` can then be used to implement some sugar.

There are some projects out there like [bluebird-co](https://www.npmjs.com/package/bluebird-co) that do this, but I think it's important we maintain the principle that `Sequelize.Promise` is an independent instance of `Bluebird` and that any yield handler is added __only__ to`Sequelize.Promise`, and not to the global Bluebird instance - as that could cause unexpected behavior in apps/other modules. And I'm not sure if [bluebird-co](https://www.npmjs.com/package/bluebird-co) supports that.

Questions:

1. Do others agree with me that the sugar is desirable?
2. Do we agree about the principles I outline above?
3. Any ideas as how to implement the yield handler?

@mickhansen @janmeier @sushantdhiman @felixfbecker

**Comment by felixfbecker** [comment]
I don't know wether this is a good idea. The `async`/`await` proposal doesn't contain this. If you `await` a value that is not a promise, it is the same as wrapping it with `Promise.resolve()`. If we add a yield handler for arrays that means we change the behaviour from what a developer would expect, from what the spec describes and we cannot easily upgrade the syntax to `async`/`await` later.

Spec-compliant:
```js
yield [1, 2, 3];
// equivalent to
yield Promise.resolve([1, 2, 3]);
```
With yield handler:
```js
yield [1, 2, 3];
// equivalent to 
yield Promise.all([1, 2, 3]);
```
It _could_ introduce super nasty bugs when we yield a value somewhere that may not always be a promise (for example the return value of a user-defined hook) and it suddenly gets `Promise.all`ed instead of `Promise.resolve`d. I always prefer explicit over implicit and spec-compliant over custom.

**Comment by mickhansen** [comment]
I'm learning towards not having sugar - Although i love the sugar it's usually user error or a bad mock that results in needing it.

**Comment by felixfbecker** [comment]
Imo explicitely writing `Promise.all()` or `Promise.race()` or `Promise.some()` or whatever is needed is better.

**Comment by overlookmotel** [comment]
OK, well I like that sweet sugar, but I don't feel so strongly about it if others feel it's better to be explicit.

By the way, the behavior of `Promise.coroutine()` isn't quite as described above. It *only* accepts a Promise (or thenable) and doesn't implicitly use `Promise.resolve()`. I guess Bluebird's author considers this unnecessary sugar!

So all of the following yield statements throw (causing the coroutine to return a rejected promise):

```js
Promise.coroutine( function*() {
	yield 1;
	yield [1, 2, 3];
	yield function() {};
	yield function*() {};
	yield {};
} )();
```

**Comment by sushantdhiman** [comment]
I too feel that `Promise.all` should be explicitly applied, So I am against this sugar syntax.

Also I think none of these will be rejected. Unless we throw an error explicitly or yield results into an error, these statement will be resolved as it is;
```js
Promise.coroutine( function*() {
    yield 1;
    yield [1, 2, 3];
    yield function() {};
    yield function*() {};
    yield {};
} )();
```

**Comment by mickhansen** [comment]
@sushantdhiman Bluebird will reject for `yield` of non promises

**Comment by sushantdhiman** [comment]
@mickhansen It is possible to do `[1, 2, 3]` or `{ a: 1 }`, they will not be rejected.

**Comment by overlookmotel** [comment]
@sushantdhiman current bluebird does reject on all of the above examples. Try it out.

**Comment by overlookmotel** [comment]
Or did you mean that Sequelize should change bluebird's default behavior? - that Sequelize should apply an additional yield handler to make `yield` act as Promise.resolve()`?

**Comment by felixfbecker** [comment]
Just don't change bluebird behaviour, always call the functions explicitely.

**Comment by sushantdhiman** [comment]
I did used `addYieldHandler(bluebird_co.toPromise);` thats why it didn't rejected, So without any yield handler it did reject. You guys are right :checkered_flag:

**Comment by overlookmotel** [comment]
@sushantdhiman So you were using the sugar that you are arguing against using?

**Comment by felixfbecker** [comment]
@overlookmotel well, you see to what kinds of confusion it leads 😃

**Comment by sushantdhiman** [comment]
@overlookmotel I tried out bluebird-co because of this discussion and copy pasted the example. My understanding was it yields plain values as resolved values and we now need some sugar upon `Array` values.

I have to admit I never used co before. But after trying it out, Now I think it will be better to have a `yieldHandler` added.

**Comment by overlookmotel** [comment]
On the question of whether to change bluebird's behavior to do an implicit `Promise.resolve()`...

I agree with @felixfbecker that I don't think it's a good idea.

The consensus seems to be to avoid sugar, and I think if you're going that way might as well make *everything* explicit. It's useful to get a rejection when you try to `yield` a non-promise - it'll warn you of bugs that could otherwise go un-noticed.

It seems that `async/await` is going to do an implicit `Promise.resolve()` (though hard to tell for sure - I've read different accounts of what `async/await` does/doesn't do, and the spec itself is hard going to read!)

But...

1. coroutines aren't going to be replaced by async/await any time soon until native Promise implementation improves performance dramatically.
2. current Bluebird behavior is *stricter* than async/await so when the transition does come it will be completely compatible.

**Comment by overlookmotel** [comment]
[cls-bluebird](https://www.npmjs.com/package/cls-bluebird) v2 is finally complete! So I'm now working on a PR to integrate it into Sequelize.

What's consensus on the sugar in the end? Avoid it? Everyone except me was dead set against, but then @sushantdhiman changed his mind!

**Comment by sushantdhiman** [comment]
> I have to admit I never used co before. But after trying it out, Now I think it will be better to have a yieldHandler added.

@overlookmotel , I want the `yieldHandler` added. But I dont think its even worth it to try rewrite everything to `co`, because

- We dont have enough time/resources to do that
- We will add one more dependency to our already long chain of dependency
- Many programmers (like me) never used `co` before, it will make things difficult for new contributors

I would prefer `async / await` (babel transpiler) over `co`. Now question is, do we all agree to use babel in sequelize code base ?

**Comment by mickhansen** [comment]
We've previously agreed that we won't add transpilation to the codebase.
I'm still not too happy with adding sugar.

Did we have any performance benchmarks on a switch to co yet?

**Comment by felixfbecker** [comment]
My vote is against co in general because of performance worries (bad V8 optimization) and async/await will already be in Node 7 with --harmony, so probably stable in Node 8.
Also against yield handler because it's unclear for new contributors and breaks compat at with async/await.

**Comment by overlookmotel** [comment]
@felixfbecker OK I take your point about the imminent arrival of `async`/`await` (Node v8 is due to arrive in 6 months time). So probably best not to use yield handlers which would be incompatible with `async`/`await`. You've convinced me!

Since we seem to have reached consensus that there won't be yield handlers, closing this issue. I've posted to continue discussion about coroutines in general on issue #6116.

**Comment by overlookmotel** [comment]
(with apologies to @sushantdhiman - it seems you're outvoted on yield handlers, though it'd also be difficult to achieve without adding a dependency, which you're also against)
