### ISSUE TITLE
Getter method called on m:m relation

### ISSUE THREAD

**Issue by Ziao** [sequelize/sequelize#6269]
I have two models, snip and tag, joined through an m:m relation called sniptags. When toJSON is called on a snip, the getter for url is called on the relation model, please see code for more clarity.

``` js
var Snip = DB.define('snip', {
    //fields
},
{
    getterMethods: {
        url: function(){
            // 'this' is NOT always a snip, but a sniptag (having snipId and tagId)
            console.log('url called for '+this.id);
        }
    }
});

var Tag = DB.define('tag', {
    //fields
});

Snip.belongsToMany(Tag, {through: 'sniptags', as: 'tags'});
Tag.belongsToMany(Snip, {through: 'sniptags', as: 'snips'});

Snip.findOne({}).then(function(snip){
    snip.toJSON(); // -> will call the url getter twice, once with the actual snip, and once with the relation data
});
```
## What do you expect to happen?

Call the url getter only once, with just the snip
## What is actually happening?

Url getter is called twice, once with wrong data

_Output, either JSON or SQL_

```
url called for 1
url called for undefined
```

I don't think I am doing something wrong here, and after spending a lot of time reading the documentation and fiddling around, I am giving up. I am assuming this is a bug.
Can someone shed some light on this?
Thanks!

**Dialect:** postgres
**Database version:** 9.5.2
**Sequelize version:** 3.23.4

**Comment by davidyang** [comment]
Just saw the same thing - adding the join model as an explicit model fixes it though.  In this case the getterMethod of the model was being called on the join model causing an issue with `this`.

**Comment by zekenie** [comment]
Just saw this as well. @davidyang's fix worked for me. BTW hi @davidyang!
