### ISSUE TITLE
Diff against a clone of attributes instead of using setters

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6270]
Currently, Sequelize holds all attributes inside `dataValues`. You can use them on the instance, but it is all one big lie as on instance creation, sequelize simply defines getters and setters that proxy to `dataValues` and mark the attribute as dirty. The problem is though that setters don't catch the following changes to attributes:
- When using a JSON column, you can alter the object
- When using an ARRAY column, you can push new items, remove item etc #6197 
- When using a DATE column, you can call `setDate()` etc on the object

You have to manually call `instance.changed('myAttribute', true)` (no autocomplete for the attribute name) or reassign with `instance.myAttribute = instance.myAttribute` (wtf, should be a noop).

Now think about how a Model is defined in Sequelize 4.0 and ES6 / TS:

``` ts
class User extends Sequelize.Model {
  public username: string;
  public roles: string[];
  public createdAt: Date;
}
```

You define your class with these attributes, but in reality, they are not there - it's all a big lie. You look at the debugger and they are not there:

![image](https://cloud.githubusercontent.com/assets/10532611/16817248/3d23a2d4-4942-11e6-82de-54a0acb68ebd.png)

I think it would be a lot better if instead of `dataValues`, there was only `_previousDataValues`. When an instance is retrieved from the DB, the _actual_ instance gets all attributes set as real attributes. `_previousDataValues` gets set to a deep copy of the attributes - that means every `Date` object, every `JSON` object, every `Array` gets deeply cloned. This does not include aggregate columns, it's only about the values of the database row.

A user can then modify and use the instance as much as he likes, nothing goes through any setters or getters (except if he defined them of course).

Only upon a call to `save()` we deeply compare the instance _once_ to the `_previousDataValues`. That includes `JSON` objects and arrays. We can then generate a minimal query that only contains the exact changes that were made to the instance.

It doesn't even have to replace a whole array column, since we have an exact diff we can even use advanced array functions to only remove / insert what changed.
### Performance

`saving` would be a bit more complex because we have to compare the objects, but every userland function containing property access (get/set) will be faster because getters and setters are an optimization killer.

**Comment by felixfbecker** [comment]
I just found the needed info is already there under `_previousDataValues`

**Comment by mickhansen** [comment]
This will break all computes values that aren't targeted virtuals.
Virtuals don't make sense in all cases like doing a window function for a full count.

**Comment by mickhansen** [comment]
```js
class User extends Sequelize.Model {
  public username: string;
  public roles: string[];
  public createdAt: Date;
}
```

Doesn't actually exist in Sequelize 4.0 / ES6 yet

**Comment by felixfbecker** [comment]
@mickhansen we discussed this on Slack already, how exactly will it break? Those can simply be set on the instance, but for `save()` we only look at the known attributes.

> Doesn't actually exist in Sequelize 4.0 / ES6 yet

huh? this is exactly how it works in master... The properties can of course only be defined if you're using TypeScript. But my point were the semantics behind it (you expect these properties to exist on the instance).

**Comment by mickhansen** [comment]
@felixfbecker 

> we discussed this on Slack already, how exactly will it break? Those can simply be set on the instance, but for save() we only look at the known attributes.

`get()` will break unless we simply enumerate over `this` (which i have no idea the performance impact of vs just returning `dataValues`.

> huh? this is exactly how it works in master... The properties can of course only be defined if you're using TypeScript. But my point were the semantics behind it (you expect these properties to exist on the instance).

They are defined on an object on the class, but i suppose it's close to the same.

**Comment by felixfbecker** [comment]
@mickhansen `get()` can indeed simply return the properties that are known attributes, like
```js
get() {
  return _.pick(this, Object.keys(this.constructor.attributes));
}
```
Honestly I think the use case of manipulating arrays, date or JSON objects is much bigger than using `get()`, since you can also just get the properties from the instance directly. We have a ~50k LOC codebase and don't use `get()` at all.

**Comment by mickhansen** [comment]
@felixfbecker You never use `toJSON` or `get`? That's rare. Read performance is important and a lot of people optimize for that, why `get` was written as it is.

But manipulating arrays doesn't really have anything to do with how get works. You're advocating for deep compare on save rather than on set, but that doesn't strictly have anything to do with how the values are stored.

On-write diffs was introduced for better perf, but it introduces too many oddities so i agree it should be changed to deep diff on save.

**Comment by mickhansen** [comment]
```
get() {
  return _.pick(this, Object.keys(this.constructor.attributes));
}
```

this won't work with aggregates or computed values that aren't VIRTUALs

**Comment by felixfbecker** [comment]
I use `toJSON` implicitely, yes, by calling `JSON.stringify()`. But we don't strictly need a method for that if the properties sit directly on the instance. We could have sequelize internal methods / properties defined as non-enumerable properties or even use symbols. I was under the impression that `get()` returned only columns in the database, but my example was just pseudo-code, `get()` / `toJSON` could also just return everything except the sequelize internal properties. Or look at the `attributes` option to see exactly what the user included.
```js
get() {
  return _.omit(this, ['isNewRecord', 'hasPrimaryKeys', '_previousDataValues']);
}
```
> But manipulating arrays doesn't really have anything to do with how get works. You're advocating for deep compare on save rather than on set, but that doesn't strictly have anything to do with how the values are stored.

Well, when we do diff on save, we just don't need the setters on the instance anymore. Setters have quite a performance impact too. They would just be a useless proxy to `dataValues`, so I advocate to remove the extra layer and put the properties directly on the instance as you would expect them to be.

**Comment by mickhansen** [comment]
> I was under the impression that get() returned only columns in the database

It returns dataValues, but with `plain` it also iterates over them so you get values back and not instances when you have includes.

```js
get() {
  return _.omit(this, ['isNewRecord', 'hasPrimaryKeys', '_previousDataValues']);
}
```

Could work, requires a loop on each `get`, but so does most cases of `get` currently.

> Well, when we do diff on save, we just don't need the setters on the instance anymore

`set` also handles the logic for building nested instances, which are used in a few scenarios. Could be solved in other ways though.

I'm not at all against this, i just see a lot of edge cases that might end up broken with this - But it's worth experimenting with.
I'm not at all against this, i just see a ton of edge cases that might end up broken with this - But it's worth experimenting with.

**Comment by sushantdhiman** [comment]
@felixfbecker Which tool or IDE you used to render this

![](https://cloud.githubusercontent.com/assets/10532611/16817248/3d23a2d4-4942-11e6-82de-54a0acb68ebd.png)

**Comment by felixfbecker** [comment]
@sushantdhiman The integrated Node debugger of [Visual Studio Code](http://code.visualstudio.com)
