### ISSUE TITLE
Need feature "update column=column+value" when insert on duplicate key? 

### ISSUE THREAD

**Issue by helloqhx** [sequelize/sequelize#6271]
Maybe this is already implemented, but I just don't where to config.
I found the option '**updateOnDuplicate**' in **bulkCreate** options, which is just replace the value.
Can anybody help?

Thanks!

**Comment by sushantdhiman** [comment]
I think this one goes out of scope, some one may ask for different operation among various columns and that will make code even complex.

You can find the models based on conditions and updated them with their current values by combining `findAll` and `update / save`, If you have very large number of records, I would suggest `sequelize.query` .

If you still need this feature to be included in Sequelize, you can start by submitting a PR and we might merge if solution is simple / clean to maintain.

**Comment by helloqhx** [comment]
Actually, I have large number of inserts like this.
It seems that i have to use raw sqls to achieve it. But  `sequelize.query` support multiple sqls? I found no tips from the docs, neither the source code. By the way, the query API will prevent **SQL injection** attack, right?

**Comment by sushantdhiman** [comment]
Sequelize query is just like running raw query on db client library. It supports whatever features sql supports.

Regarding SQL injection, you never want to run a raw query without proper escaping.
