### ISSUE TITLE
Select from a table and order by its column content

### ISSUE THREAD

**Issue by SmaranNA** [sequelize/sequelize#6272]
## Im trying to arrange rows of a select statement based on a column's values.
```js
SELECT * from TABLE
ORDER BY COL1="value1",COL1="value2";
```

## This feature is supported by MySQL. It would be great if sequelize could also support it.

__Dialect:__ mysql
__Database version:__ 5.6.27
__Sequelize version:__ 3.23.4

**Comment by sushantdhiman** [comment]
You can pass `[ ['col1' , 'DESC'], ['col2', 'DESC'] ]` in `order` field of any finder method.

**Comment by SmaranNA** [comment]
I guess my question was not understood properly.
```js
SELECT * from TABLE
ORDER BY Name="Test1",Name="TEST2";
```
##This is performed on the same column and using the values TEST1 and TEST2 which are in Name column of TABLE.

I'm looking for this feature because I have to arrange the rows of a table according to the corresponding value of Name in each row.

**Comment by felixfbecker** [comment]
@SmaranNA can you post a link to the MySQL docs where this is documented?

**Comment by sushantdhiman** [comment]
This is an non standard practice only available in `mysql` , May be `Sequelize.literal` can help here
