### ISSUE TITLE
include in findOrInitialize 

### ISSUE THREAD

**Issue by poonwu** [sequelize/sequelize#6273]
How do I include association in find or initialize?

**Comment by sushantdhiman** [comment]
`findOrIntialize` don't support the `include`. Why you need such feature ?

**Comment by bayssmekanique** [comment]
@sushantdhiman , I have ran into a few instances now where I would expect this to work and it does not.  When you are updating a model and need to update its associated models, it would be very clean to be able to call `findOrInitialize` using an `include` just like you would if you were to query it using `findOne`.

For example, if you have a `user` model with an associated `emailAddress` model and you would like to update the email address.  If `include` was an option, you could call `emailAddress.findOrInitialize({include: [{model: user, where: {user: user}]})` and it would either return the associated model or create a new model instance already associated to the `user` model.

**Comment by felixfbecker** [comment]
@bayssmekanique a) `findOrInitialize` doesn't do updates b) the `include` would not _associate_, but _create_ the included model
