### ISSUE TITLE
Conditions for associations, or return query results in a virtual attribute?

### ISSUE THREAD

**Issue by statiklabs** [sequelize/sequelize#6274]
I'm very new to Sequelize so I apologize if this is pretty straight forward. Here's a simple example of what I'm trying to do. I have an API end point that returns all posts.

``` javascript
models.Post.findAll().then(function(posts) {
   res.json(posts);
});
```

My Post model has many comments.

``` javascript
 var Post = sequelize.define('Post', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4
    },
    name: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        Post.hasMany(models.Comment, {
          foreignKey: {
            name: 'post_id'
          }
        });
      }
    }
  });
```

What I'd like is for Posts to always include the latest comment. 

I know I can do the following to load the model when I query:

``` javascript
models.Post.findAll({attributes: { include: [{model: models.Comment, limit: 1, order: '"createdAt" DESC', required: false} ]})
```

which results in something like this:

``` json
[
  {
    "id": "...",
    "name": "Post 1",
    "Comments": [
      {
        "id": "...",
        "post_id": "...",
        "comment": "...",
      }
    ]
  }
]
```

But I would much prefer it returns a single object like this:

``` json
[
  {
    "id": "...",
    "name": "Post 1",
   "last_comment": {
        "id": "...",
        "post_id": "...",
        "comment": "..."
    }
  }
]
```

Is this possible somehow without looping through each post and injecting an attribute?

In my mind, it would be great if I could either provide a new one to one association with conditions:

``` javascript
classMethods: {
      associate: function(models) {
        Post.hasMany(models.Comment, {
          foreignKey: {
            name: 'post_id'
          }
        });
        Post.hasOne(models.Comment, {
          as: 'latest_comment',
          foreignKey: {
            name: 'post_id'
          },
          limit: 1,
          order: 'createdAt DESC'
        });
      }
    }
```

or have a virtual attribute that would query the Comment model for the latest one. Something like:

``` javascript
last_comment: {
    type: DataTypes.VIRTUAL,
    get: function() {
      return this.models.Comment.findOne({order: 'createdAt', limit: 1}).then(function(comment){
        return comment
      })
    }
  }
```

Is something like this possible, or I just need to do some post fetch processing?

**Comment by carlosscheffer** [comment]
how to you solved?

**Comment by statiklabs** [comment]
@carlosscheffer I didn't. I left as an array.

`models.Post.findAll({attributes: { include: [{model: models.Comment, limit: 1, order: '"createdAt" DESC', required: false} ]})`
