### ISSUE TITLE
What is the intention of setAssociation()?

### ISSUE THREAD

**Issue by poonwu** [sequelize/sequelize#6275]
I read into `setAssociation` methods. It first build an instance then save within the function itself. I would like to ask how is this different from `createAssociation`? I thought `createAssociation` is suppose to build and save in one call, while `setAssociation` only build without saving.

For example, shouldn't 1) and 2) be equivalent?
1)
```
var user = User.build( { Profile: { name: 'foo' }, { include: [Profile] } );
user.save();
```

2)
```
var user = User.build({}, { include: [Profile] });
user.setProfile( { Profile: { name: 'foo' });
user.save(); // eager load
```

At the current version, to achieve 2), I'll have to do
```
var user = User.build({}, { include: [Profile] });
user.set('Profile', { name: 'foo' });
user.save(); // eager load
```

**Comment by sushantdhiman** [comment]
Please keep the question on [Slack ](sequelize.slack.com)or Stackoverflow , Github is only for feature request or bug reports.

Most of time you want to associate two models after they are created.  For example,  `User` and Its `Group`. When user decide to join the group only at that time you want to link `User` to `Group` not before (like at creation time). In such cases you will call

```js
userInstance.setGroup(groupInstance); // provided user and group model are related to each other
```

**Comment by jedwards1211** [comment]
@sushantdhiman we're getting errors when passing a model instance to `setAssociation` like that, it only works for us when passing an id.  Do you know if there's already an issue for this bug?  Seems a bit difficult to search for since the method name is dynamically generated.

**Comment by jedwards1211** [comment]
But it should work if I pass a model instance instead of passing the primary key of that model, right?

**Comment by jedwards1211** [comment]
I don't understand why the singular `setAssociation` accepts an array anyway since the plural `setAssociations` method is what I should be using for that right?

**Comment by sushantdhiman** [comment]
setAssociations accepts array and `setAssociation` accepts instance, it is clear from docs as well.

In both cases what you pass is either a primaryKey or object with primary key (can be instance)

**Comment by jedwards1211** [comment]
I should clarify in code.

```js
userInstance.setGroups([1, 2]) // works
userInstance.setGroups([groupInstance1, groupInstance2]) // works
userInstance.setGroup(1) // works
userInstance.setGroup(groupInstance1) // Error: invalid value
// Shouldn't this work though?
```

**Comment by sushantdhiman** [comment]
`userInstance.setGroup(groupInstance1)` should work, can you show a SSCCE? Is that instance is missing PK?

**Comment by jedwards1211** [comment]
Okay.  I'll investigate and try to open an issue when I get back to work tomorrow.
