### ISSUE TITLE
How to: condition in parent or condition in assocation

### ISSUE THREAD

**Issue by istrau2** [sequelize/sequelize#6276]
I am trying to create a sequelize query that mimics the following:

```
SELECT * from player as p
join team as t on p.teamId = t.id
where p.isCaptain = 1
or team.isGreatest = 1
```

Obviously the above is a simplification but the idea is to have a query where there is one condition on a table and then another condition on an associated table and it only needs to fulfill one or the other.

I know something like this won't work:
```
User.findAll({
   where: {
       isCaptain: true
   }
   include: [
       {
           model: Team,
           where: {
               isGreates: true
           }
       }
   ]
});
```
because there is no 'or' there. Is there any way to accomplish what I am seeking?

Thanks in advance.

**Comment by sushantdhiman** [comment]
```js
User.findAll({
   include: [
       {
           model: Team,
           required: true,
           where: {
               '$Users.isCaptain$': true,
               isGreates: true
           }
       }
   ]
});
```
