### ISSUE TITLE
Trying to make a cross table $or statement

### ISSUE THREAD

**Issue by Russ93** [sequelize/sequelize#6292]
## Trying to make a cross table or statement
_I am unsure is this is already possible but I kind of need to be able to have a cross table '$or' statement._

like so
```js
var like = '%rschlup%'
Rate
	.findAll({
		where:{
			'task': like,

			// user or users either would be find
			'users.username': like,

			// client or clients either would be find
			'clients.name': like,
		},
		include: [ User, Client, ]
	})
	.done(function(users, err){
		return res.json({ users: users, err: err });
	});
```

## What do you expect to happen?
_I would like the SQL statement to pull back all rates that the name or username looks like the name provided_

## What is actually happening?
_Unknown column 'rate.users.username' in 'where clause'_

__Dialect:__ mysql / sqlite / any
__Database version:__ 5.5.42
__Sequelize version:__ ^3.21.0

**Comment by mickhansen** [comment]
`'$clients.name$': like`

**Comment by Russ93** [comment]
Awesome thank you can you please put this in the documentation. Please.
