### ISSUE TITLE
TypeError: TypeError: Illegal invocation

### ISSUE THREAD

**Issue by x-cold** [sequelize/sequelize#6294]
### Description
While running a query, there throws a type error.

TypeError: TypeError: Illegal invocation
    at Sequelize.log (http://project\node_modules\sequelize\lib\sequelize.js:1338:21)
    at Query.run (http://project\node_modules\sequelize\lib\dialects\mysql\query.js:36:20)
    at http://project\node_modules\sequelize\lib\sequelize.js:843:20

### Which cause the error

*  I list partial code of `llib/sequelize.js`, line 1100 to 1112 (on master branch)

```js
    if (options.logging) {
      if (options.logging === true) {
        console.log('DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log');
        options.logging = console.log;
      }

      // second argument is sql-timings, when benchmarking option enabled
      if ((this.options.benchmark || options.benchmark) && options.logging === console.log) {
        args = [args[0] + ' Elapsed time: ' + args[1] + 'ms'];
      }

      options.logging.apply(null, args); // While `options.logging === console.log`, it throws a type error.
    }
```

* In fact, if we run `console.function` and change the context to bind  any other object, V8 will throws this type error.

console.log.apply(null, 'test')
VM154:1 Uncaught TypeError: Illegal invocation(…)(anonymous function)

console.log.apply(null, ['test'])
VM155:1 Uncaught TypeError: Illegal invocation(…)(anonymous function)

### How to fix

We should just modify little code to fix the problem.

```js
    if (options.logging) {
      if (options.logging === true) {
        console.log('DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log');
        options.logging = console.log;
        options.logging.apply(console, args);
      }

      // second argument is sql-timings, when benchmarking option enabled
      if ((this.options.benchmark || options.benchmark) && options.logging === console.log) {
        args = [args[0] + ' Elapsed time: ' + args[1] + 'ms'];
        options.logging.apply(null, args);
      }
    }
```

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/5700
