### ISSUE TITLE
increment / decrement doesn't map fields properly

### ISSUE THREAD

**Issue by FoghostCn** [sequelize/sequelize#6296]
## What you are doing?

Is there some way to use sequelize api generate sql like this 

```
update table set field = field - 1 where id = 1
```
## What do you expect to happen?

can I use sequelize api to do it

**Dialect:** mysql 
**Database version:** 5.7
**Sequelize version:** 3.21.0

**Comment by mickhansen** [comment]
Are you asking about generating SQL in general or are you asking about executing atomic increment/decrement statements?

**Comment by FoghostCn** [comment]
increment/decrement in my case

**Comment by sushantdhiman** [comment]
We support atomic increment / decrement. You can check these docs http://docs.sequelizejs.com/en/latest/docs/instances/#incrementing-certain-values-of-an-instance

**Comment by FoghostCn** [comment]
thank you

**Comment by FoghostCn** [comment]
@sushantdhiman I did as you said, 
the sql it generate is

```
UPDATE `table` SET `count`=`count` + -1,`updatedAt`='2016-07-19 06:36:51' WHERE `id` = 1
```
actually I have a custom field name `updated_at` with updatedAt, so it came up with another error 😳

**Comment by sushantdhiman** [comment]
for `updateAt` attribute you will have to set `field : 'updated_at'`

**Comment by FoghostCn** [comment]
yeah, I have set `field : 'updated_at'` in my model definition, but it still generate `updatedAt` in sql

**Comment by sushantdhiman** [comment]
Can you show basic case with model definition and sql generated ?

**Comment by FoghostCn** [comment]
```
const Table = sequelize.define('table', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  userId: { type: Sequelize.STRING, field: 'user_id', allowNull: false },
  createdAt: { type: Sequelize.DATE, field: 'created_at', allowNull: false },
  updatedAt: { type: Sequelize.DATE, field: 'updated_at', allowNull: false },
  deletedAt: { type: Sequelize.DATE, field: 'deleted_at' }
}, {
  freezeTableName: true,
  timestamps: true,
  paranoid: true,
  }
})
```

**Comment by sushantdhiman** [comment]
Test on `master`, We have a bug here :)

**SSCCE Code**

```js
var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

var Model = sequelize.define('Model', {
  myPrecious: Sequelize.INTEGER,
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: true,
    field: 'updated_at'
  }
});

sequelize.sync({force: true})
.then(() => ( Model.create({}) ))
.then((instance) => instance.increment('myPrecious', { logging: console.log }))
.then(console.log)
.catch(console.error);
```

**Output**
```js
{ SequelizeDatabaseError: column "updatedAt" of relation "Models" does not exist
    at Query.formatError (/var/www/sequelize/lib/dialects/postgres/query.js:347:16)
    at query.on.err (/var/www/sequelize/lib/dialects/postgres/query.js:92:21)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Query.handleError (/var/www/sequelize/node_modules/pg/lib/query.js:125:8)
    at .<anonymous> (/var/www/sequelize/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket.<anonymous> (/var/www/sequelize/node_modules/pg/lib/connection.js:
```

**Comment by felixfbecker** [comment]
Shouldn't it be
```
var Model = sequelize.define('Model', {
  myPrecious: Sequelize.INTEGER
}, {
  updatedAt: 'updated_at'
});
```
or simply `underscored: true`?

**Comment by FoghostCn** [comment]
in my case, I want it is camelcase in sequelize model but underscored in database table schema

**Comment by felixfbecker** [comment]
@FoghostCn You can underscore all your attributes in the table by using `underscored: true`. They will be camelCased in the model.

**Comment by FoghostCn** [comment]
@felixfbecker I have tried using `underscored: true`, but it's not as you said
