### ISSUE TITLE
.sum on an empty matching set results in NaN

### ISSUE THREAD

**Issue by yktv4** [sequelize/sequelize#6299]
## What you are doing?

I'm trying to use the SUM aggregate on an empty matching set

``` js
//imagine we have Payments table empty yet
Payment.sum('amount').then(console.log)
//logs NaN
```
## What do you expect to happen?

I'd like the value in this case to be `0` since by definition, a sum is a number, not a NaN.
## Why this happens?

I've quickly found that this happens due to this:

``` js
//node_modules/sequelize/lib/query-interface.js:702
//result contains null as we don't have any matching records
result = parseFloat(result);
```
## What could be done?

since the dataType requested is `dataType instanceof DataTypes.DECIMAL || dataType instanceof DataTypes.FLOAT` as stated in `node_modules/sequelize/lib/query-interface.js:701`, we can additionally check whether the `result` variable  contains `null` and in this case return `0`. I can submit a PR with this fix easily though I'd first like to ensure that I'm not the only one expecting `0` in this case rather than `NaN`.

__Dialect: postgres
__Database version: 9.5.3
__Sequelize version: 3.19.3

**Comment by sushantdhiman** [comment]
Sequelize version ? I remember fixing this issue, I think we already have test for something like this

**Comment by yktv4** [comment]
@sunshinewyin sorry for not providing it initially. here it is: `3.19.3`

**Comment by janudewangga** [comment]
Is it fixed yet? I just had a same problem in `4.36.1`

**Comment by bminer** [comment]
This is silly IMHO. `sum` should return `null` or 0.  Not `NaN`.

**Comment by jdestep93** [comment]
I agree with @bminer

**Comment by yktv4** [comment]
I guess mentioning any core developer could help. anyone knows their handles?
