### ISSUE TITLE
afterBulkCreate hook unexpectedly firing on relationship model

### ISSUE THREAD

**Issue by harto** [sequelize/sequelize#6300]
I have a `User` model. Users can have many followers/followees via the `Relationship` model.

When I add a relationship via `user1.addFollower(user2)`, I'd expect the individual `afterCreate` hook on `Relationship` to fire, but the `afterBulkCreate` hook fires instead.

Steps to reproduce:
```js
'use strict';

const Sequelize = require('sequelize');

let sequelize = new Sequelize(
    // your sandbox details here
);

let User = sequelize.define('user', {
    id: {primaryKey: true, type: Sequelize.UUID, defaultValue: Sequelize.UUIDV4}
});

let Relationship = sequelize.define('relationship', {
    id: {primaryKey: true, type: Sequelize.UUID, defaultValue: Sequelize.UUIDV4}
}, {
    hooks: {
        afterCreate: () => console.log('Relationship.afterCreate'),
        afterBulkCreate: () => console.log('Relationship.afterBulkCreate')
    }
});

User.belongsToMany(User, {as: 'Followers', through: Relationship, foreignKey: 'followee_id'});
User.belongsToMany(User, {as: 'Followees', through: Relationship, foreignKey: 'follower_id'});

let user1, user2;
sequelize.sync({force: true}).
    then(() => User.create()).
    then(u => user1 = u).
    then(() => User.create()).
    then(u => user2 = u).
    then(() => user1.addFollower(user2));
```

I expected to see: `Relationship.afterCreate` printed to the console.
I actually saw: `Relationship.afterBulkCreate`.

Full output:
```
Executing (default): INSERT INTO "users" ("id","createdAt","updatedAt") VALUES ('e2f1ad28-1324-4ce8-91d6-9ad7f6577fdb','2016-07-18 17:58:34.565 +00:00','2016-07-18 17:58:34.565 +00:00') RETURNING *;
Executing (default): INSERT INTO "users" ("id","createdAt","updatedAt") VALUES ('d66c5992-140f-4f14-a913-3ee0629255c7','2016-07-18 17:58:34.575 +00:00','2016-07-18 17:58:34.575 +00:00') RETURNING *;
Executing (default): SELECT "id", "createdAt", "updatedAt", "followee_id", "FollowerId" FROM "relationships" AS "relationship" WHERE "relationship"."followee_id" = 'e2f1ad28-1324-4ce8-91d6-9ad7f6577fdb' AND "relationship"."FollowerId" IN ('d66c5992-140f-4f14-a913-3ee0629255c7');
Executing (default): INSERT INTO "relationships" ("id","followee_id","FollowerId","createdAt","updatedAt") VALUES ('5ba1aa52-ebb7-419f-ac77-3de558626e21','e2f1ad28-1324-4ce8-91d6-9ad7f6577fdb','d66c5992-140f-4f14-a913-3ee0629255c7','2016-07-18 17:58:34.589 +00:00','2016-07-18 17:58:34.589 +00:00');
Relationship.afterBulkCreate
```

Dialect: postgres
Database version: 9.5.3
Sequelize versions: noticed on 3.19.3, reproduced on latest 3.23.4

**Comment by jduhls** [comment]
Same. Thanks for the tip to check "afterBulkCreate".

__Dialect__: mysql
__Database version__: 5.6.10
__Sequelize version__: 3.24.3

**Comment by sushantdhiman** [comment]
Its correct, 1:N and N:M relationships triggers bulk hooks, because you can always do `addFollowers([1,2, ...n])`

**Comment by felixfbecker** [comment]
Thats probably because relationship instances are created with bulkcreate?

**Comment by harto** [comment]
@sushantdhiman I see. Perhaps if a single instance is provided, and not an array, the individual hook should fire instead?

**Comment by sushantdhiman** [comment]
@harto Perhaps, but thats something we would like to discuss and will be treated as semver major change.

**Comment by harto** [comment]
Makes sense. I can work around it for now. I guess I was suprised because I don't use the multiple instance invocation.

**Comment by sushantdhiman** [comment]
@harto I am closing the issue for now, if there is more demand for changing the hooks for single instance cases we will consider :)

**Comment by jduhls** [comment]
Just adding a tip that is related:

You will also get ```bulkBeforeCreate``` instead of ```beforeCreate``` and apparently (due to hook execution order?) if you want to trigger ```beforeCreate``` you can ```addFollower(follower, {individualHooks: true})```.  I was not able to trigger ```afterCreate``` I assume because it is BEFORE ```afterBulkCreate``` in order of operations.

src: http://sequelize.readthedocs.io/en/latest/docs/hooks/#order-of-operations
