### ISSUE TITLE
TypeError: Cannot read property 'dataValues' of null on Instance.reload()

### ISSUE THREAD

**Issue by IpaliboWhyte** [sequelize/sequelize#6301]
I am on version sequelize 2.x, and anytime I try to reload the instance after **Instance.increment({},{transaction: t})** I get `TypeError: Cannot read property 'dataValues' of null` .

It looks something like 

```
//async-series-call 1
  return user.increment({'points' : CREATED_FEED}, {transaction: t.transaction});
.....
//async-series-call 2
  return user.reload() // <- error is generated
```

My guess is that due to the transaction, it's not yet been created on the DB or could I just be using an outdated version ? 

Thanks

**Comment by sushantdhiman** [comment]
We no longer support `v2.0`, Please consider switching to v3.0 or above ( [migrating from v2 to v3](https://github.com/sequelize/sequelize/wiki/Upgrade-from-2.0-to-3.0) )
