### ISSUE TITLE
Association between tables in different DBs ignored

### ISSUE THREAD

**Issue by Naoto-Ida** [sequelize/sequelize#6307]
I have two tables. They belong to different databases.

```
export default db1.define(`hero`, {
teamId: {
    type: Sequelize.INTEGER
    ....
},
name; {
    type: Sequelize.STRING
}
....
}

export default db2.define(`team`, {
id: {
    type: Sequelize.INTEGER
},
name; {
    type: Sequelize.STRING
}
....
}
```

Then in another file, I associate `hero` with `team` like this in another file.

```
import Hero
import Team
Hero.hasOne(Team, {foreignKey: 'teamId'})

```

Now it is telling me that `"ER_NO_SUCH_TABLE: Table 'db1.team' doesn't exist"`.
It seems to be ignoring my db specification. Is this normal? And how should I counteract this?
It should be trying to associate `db1.hero` with `db2.team`.
Thanks.

**Dialect:** mysql
__Database version: 5.6.31
__Sequelize version: ^3.14.2

**Comment by felixfbecker** [comment]
You omitted a lot of code... clearly it has something to do with some `country` table

**Comment by Naoto-Ida** [comment]
@felixfbecker Sorry, will supply the correct code.

**Comment by Naoto-Ida** [comment]
Updated `db1.country` with `db1.hero` to reflect the aforementioned table name.

**Comment by felixfbecker** [comment]
What function call is throwing the error?

**Comment by Naoto-Ida** [comment]
Realized this is a dupe of #2049. Closing for now and hoping it gets resolved there.

**Comment by sushantdhiman** [comment]
:) I was looking for that issue the whole time :dancers:

**Comment by Naoto-Ida** [comment]
@sushantdhiman I managed to find it, but it's two years old. I guess there isn't much demand for it...?

**Comment by sushantdhiman** [comment]
@Naoto-Ida All main contributors are busy with `v4` stuff and we all contribute in our spare time. So I guess there is very slim chance that we ever try to solve #2049, Some one who is facing the issue has to contribute :) Would you like to take a stab at it ?

**Comment by Naoto-Ida** [comment]
@sushantdhiman I'd love to solve this, as our team really need it if we are going to make an API out of GraphQL + Sequelize, and I bet many people would require this.

Only issue is, I'm rather new to non-jQuery Javascript with about 3 months of anything related to Node, but am willing to take a look at the innards of the library.

**Comment by sushantdhiman** [comment]
You can start with these[ simple issues ](https://github.com/sequelize/sequelize/labels/good-first-pr) to see how small things work ( Thats how I got started, via doing documentation work initially :))

Then you can move on to bit complex issues or even #2049 , Since you are new to Node I guess this is the best way to get introduced with sequelize internals. 

If you need any guidance about what possible fixes you can apply in [simple issues](https://github.com/sequelize/sequelize/labels/good-first-pr), don't hesitate to ask, just comment on the issue and we all will try to help as much as we can

**Comment by Naoto-Ida** [comment]
@sushantdhiman Thanks for the introduction. Hopefully I can get to figuring out #2049 soon as this API is one of the next projects I'm proposing, and not solving this would be detrimental to green lighting it.

**Comment by Naoto-Ida** [comment]
@sushantdhiman I want to `console.log()` the argument values passed [here](https://github.com/sequelize/sequelize/blob/df3cb0c247ff73b74731d35f9ce8ad74718d8cba/lib/dialects/abstract/query-generator.js#L991).

**Comment by sushantdhiman** [comment]
`model` is already being passed ( 3rd argument), main challenge is to generate the select queries correctly with database names prefixed.

**Comment by Naoto-Ida** [comment]
@sushantdhiman How do you usually add features? I am planning on forking the code, then putting into the same directory as my GraphQL stuff and make it read from there.

**Comment by sushantdhiman** [comment]
**How to properly clone**

- Fork `Sequelize` repository
- Clone your forked version on your local machine, Do usual `npm install`
- Setup remote called `upstream` (or anything else) linked to original sequelize repo. So you will have two remotes `origin` => linked to your fork ,`upstream` => linked to sequelize repo. `upstream` is used to get new changes from core repo via usual `git pull upstream master`

[Detailed Tutorial](https://help.github.com/articles/fork-a-repo/)

**How to work on fixes**

- Now create a new branch, here you should work on your fix.
- I usually start with writing tests that fails for particular case which I am trying to solve. Once tests are ready I work on solution.
- Once your solution is working, commit the changes and push the branch to your own fork. This will be done by `git push origin <new-branch-name>`
- Open Github, you will see your branch in your fork. Now send a PR for that branch. It will be applied by default to `core` repo.

**Comment by Naoto-Ida** [comment]
Ok, thanks. I've cloned it.
Now looking at the `test` directory. Sorry, I'm not that familiar with tests yet.

The tests seem to be using `this.sequelize` which is the reference to one DB.
I guess to write the tests I need to have `this.anotherSequelize` or something?

**Comment by sushantdhiman** [comment]
Take a look inside `unit` folder (especially `sql test`). You should test for correct statements generation with database usage.

**Comment by Naoto-Ida** [comment]
I traced the database config back to `test/config/config`. There doesn't seem to be anyway to manipulate this an create another instance of Sequelize referencing another Db.

**Comment by sushantdhiman** [comment]
You dont need to use another database for now. If database from current connection is properly appended then it will be prefix in case of second database too. But you need to test if we are able to generate the sql properly first.

**Comment by Naoto-Ida** [comment]
Oh, I see what you mean. Thank you. I'll look into that first.

**Comment by valoupeca** [comment]
Hello, any update about this issue ?

**Comment by valoupeca** [comment]
Hello, any update about this issue ?

**Comment by valoupeca** [comment]
Hello, any update about this issue ?

**Comment by jonathan-de-souza** [comment]
Hello, any update about this issue ?

**Comment by papb** [comment]
This is a duplicate of #2089 as said above.
