### ISSUE TITLE
Where should we import the class DataTypes?

### ISSUE THREAD

**Issue by hezjing** [sequelize/sequelize#6309]
In the [API documentation of class DataTypes](http://sequelize.readthedocs.io/en/latest/api/datatypes/), can you please describe where does the DataTypes import from?

**Comment by mickhansen** [comment]
They are provided when you use `sequelize.import` but otherwise they are also available on `Sequelize`

**Comment by hezjing** [comment]
Yes, but is this mention any where in the document?

**Comment by mickhansen** [comment]
http://docs.sequelizejs.com/en/latest/docs/models-definition/

**Comment by hezjing** [comment]
I was thinking if it would be clearer if you can mentioned that the `DataType` is provided in `sequelize.import` because I was wondering how to use the `DataType` when I click directly to the [API](http://sequelize.readthedocs.io/en/latest/api/datatypes/).

At least, I was trying out the following example mentioned in the API without knowing that it is only applicable in `sequelize.import`.
```
sequelize.define('model', {
  uuid: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV1,
    primaryKey: true
  }
})
```
