### ISSUE TITLE
selecting with multiple where in 

### ISSUE THREAD

**Issue by polearnik** [sequelize/sequelize#6312]
I want write code for this query "SELECT * FROM `orders ` WHERE (account,ticket) IN ((1,222),(2,333))"

How i can do this ?

**Comment by mickhansen** [comment]
`{$in: []}`

**Comment by mickhansen** [comment]
Not possible with operators, you'll need to use something like `sequelize.where(sequelize.literal(`(account, ticket)`, {$in: []}))`

**Comment by polearnik** [comment]
{$in: [ [1,222],[2,33] ]} ?

**Comment by mickhansen** [comment]
@polearnik Ah yeah, likely not possible, you'll need to use a raw query.
