### ISSUE TITLE
Order by + group + include issue

### ISSUE THREAD

**Issue by pwerth** [sequelize/sequelize#6314]
I have a store with products. Each product has many SKUs (product variants); each SKU has a price - the product itself does not have a price. I would like a query that returns the products based on their highest SKU price.

For instance, if I have the following SKUs:

```js
{
productId: 1,
price: 3
},
{
productId: 1, 
price: 5
},
{
productId: 2,
price: 8
},
{
productId: 2,
price: 1
},
{
productId: 3,
price: 6
}
```

The query should return [product2, product3, product1] in order of descending SKU price.

## What I've tried
My current query is:

```js
var query = { 
where: { isActive: true }, 
offset: 0,
limit: 12,
include: [
 { model: db.sku,
   required: true,
   group: 'productId',
   where: { isActive: true }
  }
],
limit: 100,
order: [[db.sku, 'price', 'DESC']],
subQuery: false
};
```

I suspect I am messing up the grouping, as I get the same result whether or not I include `group: 'productId'`.

## What is actually happening?
The query returns the 3 products with the highest SKU price, in descending order as desired. However, the limit is 12 so most of the products are missing. I am using pagination, and when I increase the offset, the products are still sorted properly, but still the limit of 12 is never achieved.

What I suspect is that the query is finding the highest 12 SKU prices, and then returning the products associated to them. The problem is that, say, the 10 highest SKU prices may all point to the same product, so only 3 products are returned.

Note: I am using `subQuery:false` to fix an issue with the limit. Before I added that option, I was receiving 12 products, in correct order, but they were not the 12 with the highest price. In other words, it was applying the sorting after the limit, not the other way around. 

__Dialect:__ mysql
__Sequelize version: 3.23.2

**Comment by Maks-Yaremenko** [comment]
+1
