### ISSUE TITLE
"should work with two schema models in a hasMany association" test undeterministic failure

### ISSUE THREAD

**Issue by cbauerme** [sequelize/sequelize#6320]
## What you are doing?
I am running the `should work with two schema models in a hasMany association` test with postgres or mysql on the master branch.

`GREP='should work with two schema models in a hasMany association' npm run test-integration-postgres`
or 
`GREP='should work with two schema models in a hasMany association' npm run test-integration-mysql`
 

## What do you expect to happen?
I expect the test to pass every time.

## What is actually happening?
Every 5th or 6th time, the test manages to fail, and it can fail in multiple ways

```
  1) [POSTGRES] Include separate should work with two schema models in a hasMany association:

      AssertionError: expected 'a' to equal 'b'
      + expected - actual

      -a
      +b
```
or
```
1) [POSTGRES] Include separate should work with two schema models in a hasMany association:

      AssertionError: expected 'd' to equal 'b'
      + expected - actual

      -d
      +b
```

__Dialect:__ postgres | mysql

**Comment by sushantdhiman** [comment]
Yes I noticed this too, And it seems to be failing a lot lately. I think some sort of race condition in this test when creating the stub data

**Comment by cbauerme** [comment]
That was my assumption as well. I can't seem to find a way to order on association on a separate query, so the best solution may be to create the data in a way that the creation order is guaranteed.

**Comment by sushantdhiman** [comment]
If we can pass the `id` around [here ](https://github.com/sequelize/sequelize/blob/df3cb0c247ff73b74731d35f9ce8ad74718d8cba/test/integration/include/seperate.test.js#L392)then order will be guaranteed

**Comment by cbauerme** [comment]
That did it! I can't get it to fail anymore. I will throw a PR up.
