### ISSUE TITLE
Query regarding virtual fields and hiding fields

### ISSUE THREAD

**Issue by sfaizanh** [sequelize/sequelize#6322]
User model

`sequelize.define('users', {
  uid: { autoIncrement: true, type: DataTypes.INTEGER(11), allowNull: false, primaryKey: true },
  username: { type: DataTypes.STRING, allowNull: true },
  email: { type: DataTypes.STRING, allowNull: false },
  first_name: { type: DataTypes.STRING, allowNull: false },
  last_name: { type: DataTypes.STRING, allowNull: true },
  name: {
    type: DataTypes.VIRTUAL,
    get: function () {
       return this.getDataValue('first_name') + ' ' + this.getDataValue('last_name');
     },
  }
})`

Now when i query 
`Users.findAll({where: {uid: [1,2]})`
result

```
[{
	"uid": 1,
	"username": "john.doe",
	"email": "john.doe@example.com",
	"first_name": "John",
	"last_name": "Doe",
	"name": "John Doe"
}, {
	"uid": 2,
	"username": "paul.smith",
	"email": "paul.smith@example.com",
	"first_name": "Paul",
	"last_name": "Smith",
	"name": "Paul Smith"
}]
```

Now how can i exclude first_name and last_name attributes from output?

```
[{
	"uid": 1,
	"username": "john.doe",
	"email": "john.doe@example.com",
	"name": "John Doe"
}, {
	"uid": 2,
	"username": "paul.smith",
	"email": "paul.smith@example.com",
	"name": "Paul Smith"
}]
```

founded solution 
```
instanceMethods : {
    toJson : function () {
      // Object manipulation
    }
}
```
but InstanceMethods won't run on **findAll**, is there any other solution then **promise.map**, all the object manipulation in model only

**Comment by felixfbecker** [comment]
`Users.findAll({where: {uid: [1,2], attributes: {exclude: ['first_name', 'last_name']}})`
http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance

**Comment by mickhansen** [comment]
toJSON runs on findAll, when you jsonify it.

**Comment by sfaizanh** [comment]
@felixfbecker when i exclude attribute virtual field get doesn't have first_name or last_name

`"name": "undefined  undefined",`

@mickhansen when i include instanceMethods in Model it gives me 

`Unhandled rejection TypeError: otp.toJSON is not a function
    at null.<anonymous> (/Users/sfaizanh/Documents/API/controllers/Test.js:124:26)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/sfaizanh/Documents/API/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)`

**Comment by mickhansen** [comment]
@sfaizanh Because it's an array, use a map (this is basic javascript, not sequelize related).

**Comment by felixfbecker** [comment]
@sfaizanh You don't call `toJSON` directly, you call `Model.findAll().then(models => JSON.stringify(models))`

**Comment by AyaMagdyMohamed** [comment]
@sfaizanh  how did you solve this problem ?

**Comment by sfaizanh** [comment]
@AyaMagdyMohamed What do want to know? Virtual Fields or toJSON?

**Comment by AyaMagdyMohamed** [comment]
@sfaizanh  Virtual Fields i have the same issue like  when you used exclude first name and last name the 
username return empty object
