### ISSUE TITLE
Primary key type UUID and default value UUIDV1 results in ER_TRUNCATED_WRONG_VALUE_FOR_FIELD

### ISSUE THREAD

**Issue by SkamDart** [sequelize/sequelize#6326]
## What you are doing?
I am trying to define a table with a primary key. I have tried the following code below with both `Sequelize.UUIDV1` and `Sequelize.UUIDV4`.
```
const Sequelize = require('sequelize')
let sequelize = new Sequelize(env.mysqlConn, {})
let Foo = seq.define('Foo', { 
      LCID: { 
		type: Sequelize.UUID,
		primaryKey: true,
		defaultValue: Sequelize.UUIDV1
    },
    // more properties below
}, {})
```

## What do you expect to happen?
_I wanted Foo to have a column LCID that is a primary key as described in the datatypes documentation_

```
sequelize.define('model', {
  uuid: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV1,
    primaryKey: true
  }
})
```
## What is actually happening?
`Unhandled rejection SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'bf595154-903a-49f9-b324-91d22bf8e777' for column 'LCID' at row 1`

__Dialect:__ mysql 
__Database version:__ mysql  Ver 14.14 Distrib 5.7.13, for osx10.11 (x86_64)
__Sequelize version:__ 3.23.6

Thought I was following the documentation well. Any suggestions?

**Comment by sushantdhiman** [comment]
It works in `master` and `v3`

**SSCCE Test**

```js
var M = sequelize.define('model', {
  uuid: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV1,
    primaryKey: true
  }
})

sequelize.sync({ force: true})
.then(() => M.create({}))
.then(() => M.findAll())
.then(console.log)
.catch(console.error)
```

**Output**
```js
[ { uuid: '7cddd200-5095-11e6-845b-1970bb45e00c',
    createdAt: 2016-07-23T05:22:45.666Z,
    updatedAt: 2016-07-23T05:22:45.666Z } ]
```

But I haven't started using the `MySQL 5.7` yet, May be that is the issue. Travis also only test against `5.6`. Can you please post the SQL queries generated

**Comment by SkamDart** [comment]
Same configuration as above.
```
Executing (default): 
INSERT INTO `Foo` (`LCID`,`createdAt`,`updatedAt`) 
VALUES ('e34fc9d1-50d4-417b-a8b3-c78a9e6f0cdf',
        '2016-07-27 04:53:01','2016-07-27 04:53:01');
```
With the error
`
Unhandled rejection SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'e34fc9d1-50d4-417b-a8b3-c78a9e6f0cdf' for column 'LCID' at row 1
`

**Comment by sushantdhiman** [comment]
@SkamDart Are you using any `charset` or mysql specific configuration ?

**Comment by sushantdhiman** [comment]
And how are you creating your tables @SkamDart , Do you have enough size in `LCID` field to hold the `UUID`

**Comment by SkamDart** [comment]
@sushantdhiman No, I'm not using any specific charset or config.

**Comment by SkamDart** [comment]
@sushantdhiman So I discovered the issue. Don't think its any fault of the module/a compatibility issue rather a misunderstanding of your documentation and bad coding practices. Thanks for the help though!

If you're curious what I was doing to setup the tables and the root of the issue.
```
constructor() {
    this.sequelize = sequelize;
    this.Sequelize = Sequelize;
}

init() {
    this.openConnection()
    this.syncDB()
}

openConnection() {
	this.sequelize
	    .authenticate()
        .then(function(err) {
            console.log('Connection has been established successfully.');
         }, function (err) { 
            console.log('Unable to connect to the database:', err);
         });
    }

syncDB() {
	this.sequelize
        .sync()
		.then(function(err) {
			console.log('Sync Sequelize with MySQL')
		}, (function(err) {
			console.log('err ', err)
		}); 
	}
```

**Comment by sushantdhiman** [comment]
@SkamDart Thanks, but it seems we really have some issues with `MySQL 5.7`, We are tracking them here #6345
