### ISSUE TITLE
Migrate to Node-MySQL2

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#6327]
I have internally started migrating Sequelize code base to [node-mysql2](https://github.com/sidorares/node-mysql2). 

This is one of the step to add prepared statement support #3495 #1608 . Apart from prepared statements `node-mysql2` offers significant improvements in [performance](https://gist.github.com/sidorares/ffe9ee9c423f763e3b6b).

Are there any reasons we should stick with `node-mysql` ?

**Comment by mickhansen** [comment]
mysql2 was originally not that stable, but it must be atleast a year since we last looked at it so i'm sure that's changed.

**Comment by felixfbecker** [comment]
I used mysql2 in a project and was very satisfied  with it.
