### ISSUE TITLE
Count includes problem with Postgres

### ISSUE THREAD

**Issue by AlexNasonov** [sequelize/sequelize#6328]
I have tried all options, mentioned in [Issue#222](https://github.com/sequelize/sequelize/issues/222), but still have some problems with my code:
```javascript
User.belongsToMany(Role, {through: 'user_roles'});
Role.belongsToMany(User, {through: 'user_roles'});

models.Role.findAll({
                attributes:['name',
                   [models.sequelize.fn('COUNT', models.sequelize.col('users.email')), 'users']
                ],
                include: [{
                    model: models.User,
                    attributes: ['email'],
                    through: {
                        attributes: []
                    },
                    duplicating: false

                }],
                group: ['role.name']
```
I have Postgres and ManyToMany relation. I can't remove `email` attribute, because if i remove it, i get an error from through model: `Unhandled rejection TypeError: Cannot set property 'user_roles' of undefined`.

Without `group: ['role.name']` I get `Unhandled rejection SequelizeDatabaseError: column "role.name" must appear in the GROUP BY...`

If I let it be, it says `column "users.email" must appear in the GROUP BY...`))

If I add "users.email" to group it hits with `Unhandled rejection SequelizeDatabaseError: column "users.user_roles.createdAt"` - as it did not remove through attributes((

And in the end, when I have `group: ['role.name', 'users.email', "users.user_roles.createdAt",  "users.user_roles.updatedAt", "users.user_roles.userEmail", "users.user_roles.roleName" ]`. It makes a fatality with `Unhandled rejection TypeError: Cannot set property 'user_roles' of undefined`

**Comment by mickhansen** [comment]
Your issue with removing email should be fixed as of master, but yes there was a bug with it.
That bug likely effectively stops you from going forward since you need to remove all regular attributes.
