### ISSUE TITLE
Polymorphic model setter not including scope attributes

### ISSUE THREAD

**Issue by TillaTheHun0** [sequelize/sequelize#6330]
I have created a 'polymorphic' model, as detailed in the sequelize documentation.

The association table:
```js
var GenreAssoc = sequelize.define('genreAssoc', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        genreId: {
            type: DataTypes.INTEGER,
            unique: 'genre_assoc_comp'
        },
        genreable: {
            type: DataTypes.STRING,
            unique: 'genre_assoc_comp'
        },
        genreableId: {
            type: DataTypes.INTEGER,
            unique: 'genre_assoc_comp',
            references: null
        }
    });
    
    return GenreAssoc;
```
And the relationship across both models:
```js
Genre.belongsToMany(models.Artist, {
    through: {
        model: models.GenreAssoc,
        unique: false,
        scope: {
            genreable: 'artist'
        }
    },
    foreignKey: 'genreId',
    constraints: false
}); 

Artist.belongsToMany(models.Genre, {
    through: {
        model: models.GenreAssoc,
        unique: false,
        scope: {
            genreable: _able // _able='artist'
        }
    },
    foreignKey: 'genreableId',
    constraints: false
});
```

The `getGenres()` on an `Artist` instance works as intended ie. it includes the `genreable` to the query producing:

```sql
SELECT "genre"."id", "genre"."name", "genreAssoc"."id" AS "genreAssoc.id", "genreAssoc"."genreId" AS "genreAssoc.genreId", "genreAssoc"."genreable" AS "genreAssoc.genreable", "genreAssoc"."genreableId" AS "genreAssoc.genreableId" FROM "genres" AS "genre" INNER JOIN "genreAssocs" AS "genreAssoc" ON "genre"."id" = "genreAssoc"."genreId" AND "genreAssoc"."genreableId" = 1 AND "genreAssoc"."genreable" = 'artist';
```

However the `setGenres()` on an `Artist` instance, which is being used to delete/add associations, is not including `genreable` causing deletions that should not occur, producing:

```sql
DELETE FROM "genreAssocs" WHERE "genreableId" = 1 AND "genreId" IN (1)
```

I was expecting `setGenres()` to only delete rows pertaining to that particular model, producing something like: 

```sql
DELETE FROM "genreAssocs" WHERE "genreableId" = 1  AND 'genreable' = 'artist' AND "genreId" IN (1)
```

Am I missing something? Thanks!

__Dialect: postgres
__Database version: 9.5.3.0
__Sequelize version: 3.23.6 (latest)

**Comment by TillaTheHun0** [comment]
Issue #1600 seems to suggest this may not work?

**Comment by mickhansen** [comment]
Looks like it might be a bug, for `through.scope` it should obviously apply to the join table in both cases and if you're using the same string value it should match up.

**Comment by TillaTheHun0** [comment]
I'll take more time to look into it. Maybe perhaps an assoc model instance needs to be on each genre instance and they aren't or something. I will post back here if I determine anything. Thanks!

**Comment by TillaTheHun0** [comment]
Closing this because I found a better way to accomplish what I was trying. Thank you for Sequelize!
