### ISSUE TITLE
Would it be possible to merge this query by using the default lookup function with a sequelize.literal?

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#6333]
I'd like to be able to merge this query with a default lookup, so something like:

models.FreeForAll.findAll() ... then ...

but I'd like to include this:

http://dba.stackexchange.com/questions/13703/get-the-rank-of-a-user-in-a-score-table

would it be possible without doing the full raw query myself?

**Comment by KieronWiltshire** [comment]
Okay here is what I have, and it works great.
```JavaScript
      _.extend(options, {
        attributes: Object.keys(models.FreeForAll.attributes).concat([
          [models.sequelize.literal('FIND_IN_SET(' + 'totalKills' + ', (SELECT GROUP_CONCAT(' + 'totalKills' + ' ORDER BY ' + 'totalKills' + ' ' + 'DESC' + ') AS orderId FROM ' + models.FreeForAll.tableName + '))'), 'rank']
        ])
      });

      models.FreeForAll.findAll(options).then(function(data) {
        resolve({
          data: data
        });
      }).catch(function(error) {
        debug(error);
        reject(new responses.InternalServerError);
      });
```

However, I now want to escape the sequelize.literal, is this possible?

**Comment by KieronWiltshire** [comment]
So I resulted to this instead,
this query works in MySQL workbench but doesn't work in Sequelize
``JavaScript
models.sequelize.query(`
        SET @rank = 0;
        SELECT *, (@rank := @rank + 1) AS rank FROM battleground_freeforall ORDER BY (totalKills - totalDeaths) DESC;
      `).then(function(data) {
        console.log(data);
      }).catch(function(error) {
        console.log(error);
      });
```

**Comment by KieronWiltshire** [comment]
Ughh, why is adding a rank so difficult?
Basically I never want the same two people to have the same rank and I'd also like ranks to be given by their score, (score = totalKills - totalDeaths). If someone could please help me with this as well as implement it into sequelize, I'd really appreciate it. I've been struggling on it for quite some time now.

**Comment by Baconiser** [comment]
idk if you still need this. But thats how i am doing it with pgsql.
```
var query = 'select ROW_NUMBER() over (ORDER BY ("totalKills" - "totalDeaths")) DESC) AS rankingpos from battleground_freeforall';
        models.sequelize.query(query, {
            type: db.sequelize.QueryTypes.SELECT
        }).then(function(result) {
            //result as list
        }).catch(/*error handling*/);
```
