### ISSUE TITLE
model.schema(....) not setting model.$schema

### ISSUE THREAD

**Issue by afloyd** [sequelize/sequelize#6336]
## What you are doing?

``` js
let myModel = sequelize.define('foo', {...});
myModel.schema('test');
myModel.find({...});
```
## What do you expect to happen?

I want generated SQL statements to prefix the correct schema ("test") to the model's table name.
e.g. `select ... from "test"."foo"...`
## What is actually happening?

The schema provided is not found in the generated SQL. This used to work in a previously used version... Updating my code to call `myModel.$schema = 'test';` makes this work as expected. But the documentation should reflect that and/or the `.schema()` should be fixed/removed

**Dialect:** postgres
**Database version:** 9.4
**Sequelize version:** 4.0.0-0

**Comment by mickhansen** [comment]
If this worked previously it sounds like it might be a bug, `schema` is supposed to return a cloned object that you then use.

**Comment by afloyd** [comment]
Although the [latest docs](http://docs.sequelizejs.com/en/latest/api/model/#schemaschema-options-this)  state "Apply a schema to this model.", which is how it used to work

**Comment by felixfbecker** [comment]
Is there a reason why it clones the model class? It may have unintended side effects with the inheritance in v4

**Comment by mickhansen** [comment]
@felixfbecker So you can have multiple schemas active, IIRC.
@afloyd Hmm, yeah - maybe you're right.

**Comment by felixfbecker** [comment]
@mickhansen maybe this could be solved better by a `Model.clone()` method
