### ISSUE TITLE
Passing DataType function instead of function result, results in [object Object] type in sqlite

### ISSUE THREAD

**Issue by TimNZ** [sequelize/sequelize#6337]
The doc examples have many columns with 'type: Sequelize.STRING' (STRING as an example)
This results in a column type in sqlite of [object Object]. 
I have to specify 'Sequelize.STRING()' instead.

Bug or misunderstanding?

**Comment by sushantdhiman** [comment]
Which version you are using ? Have you tried the latest `master` branch ?

**Comment by TimNZ** [comment]
It's Webpack and whatever mechanism sequelize uses when processing the 'type' property when pointing to a packed DataType function.  Works fine in regular require() file.

**Comment by TimNZ** [comment]
Odd that there is no column type validation error though..

**Comment by TimNZ** [comment]
I'll damn well use Webpack for Node if I want to sir! :)

In this case it's a commercial Electron app where I want to make it slightly trick to rip off the code..

I think there should still be a validation check for the type because ultimately [object Object] is being used which is clearly not a valid db type.

**Comment by felixfbecker** [comment]
I think the data types all have `toString`, which returns `[object Object]` for objects.
