### ISSUE TITLE
Connect after aws rds failover

### ISSUE THREAD

**Issue by powellquiring** [sequelize/sequelize#6338]
In using sequelize + mysql on aws aurora.  It does not seem possible to handle the failover of an aurora write instance.  The nodejs/sequalize program is configured with the aurora cluster name.
1.  Start the sequelize program to deal with aurora: connect, read, writes, ... (all is good)
2. In aws rds console select the aurora writer instance and choose "Failover"
3. Watch the console update the read replica to be the writer (original writer instance is now read only).
4. Check the logs of the program and notice a failure with the following reason:
   
    reason: { [SequelizeDatabaseError: ER_OPTION_PREVENTS_STATEMENT: The MySQL server is running with the --read-only option so it cannot execute this statement]
      name: 'SequelizeDatabaseError',
     message: 'ER_OPTION_PREVENTS_STATEMENT: The MySQL server is running with the --read-only option so it cannot execute this statement',
     parent:
      { [Error: ER_OPTION_PREVENTS_STATEMENT: The MySQL server is running with the --read-only option so it cannot execute this statement]
        code: 'ER_OPTION_PREVENTS_STATEMENT',
        errno: 1290,
        sqlState: 'HY000',
        index: 0,
        sql: 'INSERT INTO ...},
     original:
      { [Error: ER_OPTION_PREVENTS_STATEMENT: The MySQL server is running with the --read-only option so it cannot execute this statement]
        code: 'ER_OPTION_PREVENTS_STATEMENT',
        errno: 1290,
        sqlState: 'HY000',
        index: 0,
        sql: 'INSERT INTO ... },
     sql: 'INSERT INTO ... }

This makes sense since the IP address that the program is connected to is now read only.

Expected: There is a programmatic way to close the current connection and then re-open the connection to the cluster, thus getting a new IP address to the writeable node.
Actual: I can not find a way to handle this error.  I need to stop the program and start it.

**Comment by mickhansen** [comment]
For DNS based discovery it definitely makes sense to allow programmatic disconnect/reconnect for certain error cases.

**Comment by malmamun** [comment]
I had a similar type of issue where the RDS was deployed was installed within a VPC and a host had a **/etc/hosts** entry of RDS host to the read-only endpoint and that was causing the error. Just after removing the entry, the RDS DNS was getting resolved to private IP and all was good. But thanks anyway for giving me direction.

**Comment by tafelnl** [comment]
@powellquiring Did you ever find a solution or this?
