### ISSUE TITLE
Should replication connections work with sockets

### ISSUE THREAD

**Issue by tdreyno** [sequelize/sequelize#6343]
My config is like so:

```
{
  replication: {
    read: [{
      dialectOptions: {
        socketPath: 'read_socket',
      },
    }],
    write: {
      dialectOptions: {
        socketPath: 'write_socket',
      },
    },
  },
}
```

But it's not connecting. Is that config correct or are sockets even supported with replication?

**Comment by mickhansen** [comment]
In theory it should work but i'm not sure if replication supports dialectOptions per item.

**Comment by tdreyno** [comment]
I dug into the code and I can't seem to find any evidence that it's reading `dialectOptions`.

I'm building a node app on Google App Engine and sockets are the only means of connecting to MySQL. Anything I can do to help?

**Comment by mickhansen** [comment]
We could explore a PR to also apply dialectOptions per item

**Comment by tdreyno** [comment]
Awesome. Got a deadline this week, so all I could provide is testing such a PR on my staging...

Otherwise, I'll loop back after this ships and see about submitting that PR. Thanks

**Comment by tdreyno** [comment]
Well... Hello again. We've been in production since December and it's about time to start looking at optimizing the database. Can we get some movement on this issue @mickhansen ?

This basically blocks Sequelize from being able to use replicas on Google Cloud.
