### ISSUE TITLE
Reliable way to detect and fail on mysql server fail over

### ISSUE THREAD

**Issue by powellquiring** [sequelize/sequelize#6344]
When working around https://github.com/sequelize/sequelize/issues/6338 the program was modified  to write a record every 5 sec and then exit if the write fails.  There is another layer of software (elastic beanstalk) that will restart the program.  This worked around this original issue since the new program would re-evaluate the DNS and all is good.  I tested this a few times using aws/mysql (instead of aurora) using the instance > reboot > failover on reboot using the aws rds console UI.  It worked OK for 4 times in a row and on the 5th time I saw this:

    Executing (default): INSERT INTO `Timestamps` (`id`,`timestamp`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'2016-07-27 22:59:21','2016-07-27 22:59:21','2016-07-27 22:59:21');
    Unhandled rejection SequelizeConnectionError: Quit inactivity timeout
        at Quit._callback (/var/app/current/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:135:30)
        at Quit.Sequence.end (/var/app/current/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
        at /var/app/current/node_modules/mysql/lib/protocol/Protocol.js:399:18
        at Array.forEach (native)
        at /var/app/current/node_modules/mysql/lib/protocol/Protocol.js:398:13
        at nextTickCallbackWith0Args (node.js:420:9)
        at process._tickCallback (node.js:349:13)
    

After this error message was logged the 5 second timer function created via setinterval() stopped being called.  BTW line 135 in connection-manager.js is the  'return new Promise(...) below

    ConnectionManager.prototype.disconnect = function(connectionLock) {
      var connection = connectionLock.unwrap();
    
      // Dont disconnect a connection that is already disconnected
      if (!!connection.closed) {
        return Promise.resolve();
      }
    
      return new Promise(function (resolve, reject) {
        connection.on('end', resolve);
        connection.close();
      });
    };

**Comment by sushantdhiman** [comment]
Main Discussion https://github.com/sequelize/sequelize/issues/2113

**Comment by rajajlidi** [comment]
sorry i have the same probleme with id  , if  you have solution tel me
