### ISSUE TITLE
Instance _changed with objects and dates

### ISSUE THREAD

**Issue by ybrodsky** [sequelize/sequelize#6347]
If you have a JSON or Date fields, the `_changed` attribute of your instances before or after updating always states that you have changed this fields, even if you havent.

It should do the proper comparison when it's json / date instead of treating them as strings which seems to be the case.

**Comment by felixfbecker** [comment]
See #6270 and #6197

**Comment by sushantdhiman** [comment]
Thanks @felixfbecker , Closing in favor of #6270
