### ISSUE TITLE
Don't select association's IDs when all their attributes are explicitly excluded

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#6349]
This is a feature request.

We use Sequelize for a full suite of apps. It's great. The biggest issue we always run into is performing a paginated search of models that have associations (see related issue #5230). Our solution has been to break our search into 2 queries (as explained in issue #5230). This solution is okay, but it is not scalable. A scalable solution would be possible if the IDs of the models association where not included in the select clause when all the attributes of the model's associations are explicitly excluded.

For example, if we wanted to find the only primary key ID of all the "workers" who were in a set of "teams" with some set of "managers", we could do the following
```js
Worker.findAll({
  attributes: ['id']
  include: [{
    model: Team,
    attributes: [],
    where: { name: ['foo', 'bar'] },
    include: [{
      attributes: [],
      model: Manager,
      where: { name: ['baz', 'whatever']}
    }]
  }]
})
```
Currently, Sequelize will construct SQL something like:
```sql
SELECT "id", "team"."id" AS "team.id", "manager"."id" AS "manager.id" FROM "workers"...
```
and this will retrieve the following from the DB:
```
"id"    "team.id" "manager.id"
1       10        100
1       11        100
3       10        100
3       11        100
4       11        100
5       10        100
```
In this scenario, the "team" and "manager" IDs are irrelevant. Worse, though, is this makes it impossible to efficiently return only the first N number of "workers."

If the "team" ID was not added to the select clause when "team" attributes are explicitly excluded, then we could do the following:
```js
Worker.findAll({
  attributes: ['id']
  include: [{
    model: Team,
    attributes: [],
    where: { name: ['foo', 'bar'] },
    include: [{
      attributes: [],
      model: Manager,
      where: { name: ['baz', 'whatever']}
    }]
  }],
  limit: 2
})
```
Then, Sequelize could construct SQL something like:
```sql
SELECT "id" FROM "workers"...
```
and retrieve only the IDs of interest from the DB:
```
"id"
1
3
```

This would make efficient scalable paginated searching of complex models possible.

Please, please, please add this feature...

__Dialect:__ any
__Database version:__ 9.4
__Sequelize version:__ ^3.23.3

**Comment by sushantdhiman** [comment]
I suppose https://github.com/sequelize/sequelize/pull/6297 fix this one

**Comment by sushantdhiman** [comment]
No, I think you want to remove ids from SELECT statement too, thats not supported yet

**Comment by nareynolds** [comment]
I'd only want the ID of the "worker" model. Does #6297 fix this?

**Comment by sushantdhiman** [comment]
Yes it will, but we need the actual `id` in SELECT statement (to query). But final result will have only `Worker` object without any nested `Team` and `Manager`

Roughly Like 

`[{ id : 1}, { id : 2}]`

**Comment by nareynolds** [comment]
Which ID are you reference to when you write "but we need the actual id in SELECT statement"? In the example I outlined above. Would the resulting SQL look like:
'''sql
SELECT "id" FROM "workers"...
'''
If so, could you cut a new 3.X.X release that includes it? This would be a huge improvement for our business!

**Comment by nareynolds** [comment]
@sushantdhiman, could you please respond to my last comment?
