### ISSUE TITLE
3 tests failing on master?

### ISSUE THREAD

**Issue by nadavoosh** [sequelize/sequelize#6350]
hi all — we use Sequelize at my company, and I wanted to get up to speed on contributing as well. Thanks for making something awesome!

## What you are doing?
I'm running tests, on a fresh pull of master, with `npm run test-docker`

# What do you expect to happen?
Since this is a fresh pull of master, I expect all the tests to pass

## What is actually happening?

I have `1369 passing (3m)`, and 3 failing tests:

```
  1) [MYSQL] DataTypes allows me to return values from a custom parse function:
     SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2011-10-31 00:00:00 +00:00' for column 'dateField' at row 1

  2) [MYSQL] Sequelize query logging logs warnings when there are warnings:
     SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: 'HORSE' for column 'createdAt' at row 1

  3) [MYSQL] Sequelize sync fails with incorrect database credentials (1):
     AssertionError: expected 'connect ECONNREFUSED 127.0.0.1:3306' to match /.*Access\ denied.*/
```

(Note: I also posted this in the #general slack channel, to no replies)

**Comment by sushantdhiman** [comment]
We are ware of issue, Its seems to be appearing on `MySQL 5.7`. Closing in favour of #6345
