### ISSUE TITLE
[Suggestion] Increment fields using Model.

### ISSUE THREAD

**Issue by sjfkai** [sequelize/sequelize#6359]
We can increment fields by using [instance.increment(fields, [options])](http://docs.sequelizejs.com/en/latest/api/instance/#incrementfields-options-promisethis).

But I think increment with Model is also necessary. Like:

``` js
  const fields = { answer: 42, tries: 1};
  someModel.increment(fields, {
     where: {
      id: 111,
    }
  });
```

Thanks.

**Comment by joaolucasl** [comment]
Was going for this one, but it seems to have been [tackled already?](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3636)

**Comment by janmeier** [comment]
@joaolucasl Thats an instance method :) - it only supports updating a single row

**Comment by joaolucasl** [comment]
Oh! My bad! Got confused w/ that. Gonna try and make a PR for this one then!

**Comment by hieven** [comment]
I don't find `increment` method in `Model`, so I guess this issue is still open for everyone, right?
If yes, I'd love to give it a try to implement this feature :)
