### ISSUE TITLE
Searching using findAll with belongsToMany relationship 

### ISSUE THREAD

**Issue by mb0606** [sequelize/sequelize#6362]
I have tried every method to search through a Join table it keeps throwing errors. The Docs are really lacking on Querying your database on relationships 

////// db File
User.belongsToMany(Skill, {through: 'UserSkills', foreignKey: 'mentorId'});
Skill.belongsToMany(User, {through: 'UserSkills', foreignKey: 'skillId'});

////// model file
exports.learnerSearchMentors = function(req, res, term){
  db.User.findAll({
      where: {
        $or: [

```
      { username       : { $like: '%' + term + '%'}},
      { firstname      : { $like: '%' + term + '%'}},
      { lastname       : { $like: '%' + term + '%'}},
      { email          : { $like: '%' + term + '%'}},
      { phone          : { $like: '%' + term + '%'}},
      { description    : { $like: '%' + term + '%'}},
      {'$skills.title$': { $like: '%' + term + '%'}}
    ]
  },
  include : [{
               model : db.Skill, {through: 'UserSkills'},
               as: 'skills'
            }]
})
.then(function(mentors){
    console.log("line 58: list of found mentors by term");
    res.status(200).send(mentors)
})
.catch(function(err){
    console.error(err.message);
    res.status(500).send(err.message);
});
```

}

**Comment by janmeier** [comment]
Which errors are being thrown? When using `'$skills.title$'` you have to exactly match the name of the table  (including pluralization and capitalization)

**Comment by mb0606** [comment]
I have tried the include multiple ways. The through breaks it. When I remove it, it doesn't access the Skill table at all 
include : [{
               model : db.Skill
               as: 'skills'
            }]

  include : [{
               model : db.Skill, {through: 'UserSkills'},
               as: 'skills'
            }]

**Comment by janmeier** [comment]
Oh, you don't need the `through: UserSkills` part on the includes. You should only use `through` if you want to add `where`, `attributes` etc. to the through table.

How does it break exactly?

**Comment by mb0606** [comment]
Yes I took out the  --through-- . I also changed the relationship to User.hasMany(skills) which I thought would make it easier. Now it errors out and says ERROR ::  Skill (skills) is not associated to User!

Do I need to add the userId for it to search for the specific skill for that user ? I am at a loss !

**Comment by janmeier** [comment]
Did you remove the `as: skill` part while changing the association? In that case you need to remove it from the include as well. Or you can store the association and use that instead: `User.Skills = User.hasMany(Skill)` - `include: [User.Skills]`

You definitely do not need to add the userId to the query - sequelize handles to that for you :)

**Comment by mb0606** [comment]
User.Skills = User.hasMany(Skill, {foreignKey: 'mentorId'});
 I would do this in my db file ?

**Comment by janmeier** [comment]
Or whereever you setup the associations (most likely yes9

**Comment by mb0606** [comment]
Where is this in the docs? I thought that when you set up the User.hasMany it sets up the relationship. I didn't realize that you could saved as a prop. If I do this in my db do I have to export it ?

User.hasMany(Skill, {foreignKey: 'mentorId'});
exports.User         = User;

**Comment by janmeier** [comment]
You have to export the user somehow :) - Adding extra properties to the model does not change that.

It might not be in the regular docs, but it's mentioned in the API docs that you can pass an association to includes
