### ISSUE TITLE
Model class prototype is undefined

### ISSUE THREAD

**Issue by marcinc81** [sequelize/sequelize#6364]
Hi. first of all thank you for this awesome library - it's amazing! :+1: 

I wanted to add custom method to the model class, but I'm having problems with accessing to 'prototype' property - it's undefined. Just followed manual, the code below is actually copied over from the doc:

```js
var Sequelize = require('sequelize');

db = new Sequelize('test', 'root', '', {
  host: 'localhost',
  dialect: 'mysql'
});

db.authenticate()
	.then(function(err) {
		debug('Connection has been established successfully.');
	})
	.catch(function (err) {
		debug('Unable to connect to the database:', err);
		process.exit();
	});

var User = db.define('user', { firstname: Sequelize.STRING });

// Adding a class level method
User.classLevelMethod = function() {
  return 'foo';
};

// Adding an instance level method
User.prototype.instanceLevelMethod = function() {  // <---- HERE
  return 'bar';
};```

I have no idea WHY it's undefined... :| To me it looks like not up to date manual or some bug.

sequelize: 3.23.6
nodejs: 6.2.2

**Comment by janmeier** [comment]
The docs are for 4.0 - for 3.0, you need to do `User.Instance.prototype

**Comment by janmeier** [comment]
And thanks for the kind words :)

**Comment by valeriy-devpronet** [comment]
Hi.
How to get access to class level methods?

```javascript
var User = db.define('user', { firstname: Sequelize.STRING });

// Adding a class level method
User.classLevelMethod = function() {
  return 'foo';
};
// How can I get access to classLevelMethod
User.??????

```

**Comment by cojack** [comment]
@janmeier so documentation is still outdated: http://docs.sequelizejs.com/manual/tutorial/models-definition.html#expansion-of-models

**Comment by janmeier** [comment]
@cojack How so? 

The docs you linked say that you you put static methods directly on the class and instance methods on its prototype

**Comment by cojack** [comment]
@janmeier as you said year ago:
`User.Instance.prototype` works vs one from docs: `User.prototype` doesn't.

**Comment by janmeier** [comment]
In that case you must be using v3

**Comment by cojack** [comment]
@jamelt you're f*** right, sorry :<

**Comment by chipach** [comment]
Am I understanding the v3 vs. 4 difference correctly in that in v3, `Model.Instance.prototype.functionName` is required and in v4, that becomes `Model.prototype.functionName` (as per the v4 documentation)?   Apart from checking to see if Model.prototype exists yet or not (it doesn't in v3, at least), is there a good way of future-proofing code before the v3 to v4 transition?
