### ISSUE TITLE
Precision of milliseconds not correct.

### ISSUE THREAD

**Issue by frikkievb** [sequelize/sequelize#6367]
## What you are doing?
I am trying to get a DATETIME (not DATETIME2) from a MSSQL database.  We need this accuracy for our concurrency checks.

## What do you expect to happen?
I wanted what was in the database.  The value is =2016-08-02 12:42:11.087

## What is actually happening?
But I am getting: 2016-08-02T12:42:11.086Z

__Dialect:__ mssql

__Sequelize version:__Currently 4.0.0-0 - but have tried multiple versions of 3 as well.

**Comment by mickhansen** [comment]
How are you checking the value in the database?

**Comment by frikkievb** [comment]
With Navicat Premium.

**Comment by frikkievb** [comment]
I've stumbled upon this post and I suspect that the problem might be with tedious:
https://github.com/tediousjs/tedious/issues/391

**Comment by janmeier** [comment]
Closing, most likely a tedious problem (very tedious indeed, haha.. :D )

**Comment by frikkievb** [comment]
Is there a way for me to use a different MSSQL driver?  If so, can you be so kind as to point me to the documentation for this?  Thank you!
