### ISSUE TITLE
Feature request: Allow setting individualHooks on model definition

### ISSUE THREAD

**Issue by johnbrett** [sequelize/sequelize#6368]
Hey AWESOME job with sequelize first of all.

I've encountered this issue multiple times with individualHooks, as far as I can tell, my choices are set individualHooks: true per query, or use the bulk** hooks. The issue with using the bulk hooks is I don't have the instances making it quite awkward, so in cases where I might want to log the actions with the instance in certain places it makes it quite difficult. 

My proposal is to allow setting individualHooks to true on a model basis mean, by default queries against a certain model will run the individualHooks:
```js
var User = sequelize.define('user', {
  username: DataTypes.STRING,
  mood: {
    type: DataTypes.ENUM,
    values: ['happy', 'sad', 'neutral']
  }
}, {
  hooks: {
    beforeValidate: function(user, options) {
      user.mood = 'happy'
    }
  },
  individualHooks: true // New option
});
```
Related issue looking for something similar: https://github.com/sequelize/sequelize/issues/3419.

Happy to work on a PR myself for this if it's wanted. Would easily take another solution that didn't require me to set individualHooks to true on every query / do some messing around inside the bulk hooks either if I've missed something either also! Thanks everyone!

**Comment by janmeier** [comment]
I still think using hooks is the best solution :)

**Comment by johnbrett** [comment]
Hey @janmeier - thanks for the quick response! Did you mean the bulk hooks are the best solution? Is there any "recommended" way of accessing each model instance within a bulk hook in that case?

**Comment by janmeier** [comment]
You don't need to access the instances in the bulk hook - You can use the bulk hook to modify options so individual hooks get triggered

```js
 hooks: {
    beforeBulkUpdate: function(options) {
      options.individualHooks = true;
    }
  },
```

**Comment by johnbrett** [comment]
ah! I wasn't aware of this, that suits me perfectly, thanks a mil!
