### ISSUE TITLE
Suggestion MySQL Index Hints

### ISSUE THREAD

**Issue by bsapot** [sequelize/sequelize#6370]
Has anyone thought about the ability to add index hints in queries for MySQL. I thought an option like useIndex could passed into the find functions. 

Something like the following 

``` javascript
var options = {
    useIndex: "my_fast_index"
};
mymodel.findAll(options);
```

I can look at submitting a PR if this interests anyone else.

**Comment by janmeier** [comment]
PR welcome :)

**Comment by mickhansen** [comment]
I'd like to see this kept plugin-level somehow.

**Comment by bsapot** [comment]
@mickhansen by plugin level do you mean the mysql dialect?

**Comment by janmeier** [comment]
Hard to do a plugin that does SQL generation (at least at the moment)

**Comment by sfaizanh** [comment]
@bsapot Any update?

**Comment by bsapot** [comment]
I have it done I just need to write the tests. I probably won't get to it for about a month.

**Comment by anthonyu** [comment]
@bsapot I would love to be able to use this code. Please submit the PR or push what you have so far to a fork. Thanks!

**Comment by jwt1143** [comment]
Did this ever happen? This functionality would be amazing.

**Comment by jwt1143** [comment]
I have an MR ready for this feature but it was closed and a new issue was created so we can have an API design discussion first. We would like to support MySQL, MSSQL, SQLite.

Anyone interested in this feature should go here:
https://github.com/sequelize/sequelize/issues/9421

And thumbs up it and/or contribute to the api design discussion 😄

**Comment by monukanyal** [comment]
Is this feature added now?
