### ISSUE TITLE
Storing Really Long Text

### ISSUE THREAD

**Issue by sandysaders** [sequelize/sequelize#6378]
I'm wondering how to store large amount of text for say an article or blog post. As when I store something I get the following error:
```
Unhandled rejection SequelizeDatabaseError: value too long for type character varying(255)
```

Heres the model type:
```js
  body: {
    type: Sequelize.STRING,
    allowNull: false
  },
```

**Comment by Sigmus** [comment]
Use ```Sequelize.TEXT``` instead.
http://docs.sequelizejs.com/en/latest/docs/models-definition/#data-types

**Comment by sandysaders** [comment]
@Sigmus thanks!

**Comment by rishabhkadam** [comment]
this dont support LONGTEXT

**Comment by WikiRik** [comment]
> this dont support LONGTEXT 

Use TEXT('long')
