### ISSUE TITLE
How to query items that have a lesser Id than an arbitrary number?

### ISSUE THREAD

**Issue by sandysaders** [sequelize/sequelize#6379]
I'm trying to query a list of items from my database who have a smaller id than lets say `15`, so when the query executes it would ideally return items with ID's greater than `15`:
`14, 13, 12, 11, 10, ...` along with their other information. 

I'm not sure how to accomplish this with sequelize

**Comment by sandysaders** [comment]
I'm trying something like the following however it's not working:
```js
    if (quantity) {
      return DB.models.post.findAll({
        limit: quantity,
        order: [[Sequelize.fn('max', Sequelize.col('createdAt')), 'DESC']]
      });
    } else if (quantity && lastPost) {
      return DB.models.post.findAll({
        where: {
          id: {
            $lt: lastPost
          },
        },
        limit: quantity,
        order: [[Sequelize.fn('max', Sequelize.col('createdAt')), 'DESC']]
      });
    }
```

throws this error:
```
column \"post.id\" must appear in the GROUP BY clause or be used in an aggregate function
```

**Comment by janmeier** [comment]
Can you create a [SSCCE](HTTP://SSCCE.ORG/) that throws that error? It should only happen if you have a group by clause.

**Comment by sandysaders** [comment]
@janmeier What does group by clause mean?

**Comment by janmeier** [comment]
http://www.w3schools.com/sql/sql_groupby.asp

**Comment by sandysaders** [comment]
This is the post schema:
```js
import Sequelize from 'sequelize';

const Post = {
  id: {
    type: Sequelize.INTEGER,
    allowNull: false,
    primaryKey: true,
    autoIncrement: true
  },
  title: {
    type: Sequelize.STRING,
    allowNull: false
  },
  body: {
    type: Sequelize.TEXT,
    allowNull: false
  },
  proofed: {
    type: Sequelize.BOOLEAN,
    allowNull: false
  }
}

export default Post;
```
This is the the instantiation:
```js
import Sequelize from 'sequelize';
import User from './User.js';
import Post from './Post.js';

const Setup = new Sequelize(
  'postgres',
  'postgres',
  null,
  {
    dialect: 'postgres',
    host: 'localhost',
    port: '5432',
  }
);

const UserModel = Setup('user', User);
const PostModel = Setup('post', Post);

UserModel.hasMany(PostModel);
PostModel.belongsTo(UserModel);

Setup({force:true}).then(async () => {
  var user = await UserModel.create({
    firstName: 'test',
    lastName: 'person',
    email: 'test@somemail.com',
    password: 'test1234',
  });
  var post = await PostModel.create({
    userId: user.id,
    title: "test post 1",
    body: 'test body 1',
    proofed: false
  });
});

export default Setup;
```
@janmeier

**Comment by janmeier** [comment]
Group by is added to the query, not your model definitions - Please create a small, self contained test case that shows the issue

**Comment by sandysaders** [comment]
Well the rest of it is the initial code snippet I sent. Thats all the code pretty much. @janmeier

**Comment by janmeier** [comment]
Ah yes - You are using the `max` function on createdat - which implicitly turns this into a grouping without adding `GROUP BY` - And postgres then wants you to explicitly say what should happen to the other rows - You take the max value of created at, but what should happen with the other rows (id in this case).

But why are you using max without group by or joins?

**Comment by sandysaders** [comment]
I was trying to follow the examples in the documentation, the section on ordering. http://docs.sequelizejs.com/en/latest/docs/querying/#ordering

**Comment by sandysaders** [comment]
Essentially the query should return the from newest posts to oldest posts.

**Comment by janmeier** [comment]
Well, those are just examples, taken out of a context, to show the different ways you can write order by :) - If you just want to order by creation date `    ['createdAt', 'DESC']` is fine

**Comment by sandysaders** [comment]
@janmeier for the `else if` portion, is the `$lt` used correctly? I'm trying to get posts who's id is less than the last post previously retrieved?

**Comment by janmeier** [comment]
Yep, that looks finew

**Comment by sandysaders** [comment]
@janmeier thank you very much! 👍🏼
