### ISSUE TITLE
sequelize express framework many to many association not working

### ISSUE THREAD

**Issue by vaibhavramteke787** [sequelize/sequelize#6381]
can some one help in the issue  Model1 is not associated to Model 2 in many to many relationship

I have a **Depts Model**

module.exports = function (sequelize, DataTypes) {
    var Depts = sequelize.define('Depts', {
        Id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            primaryKey: true
        },
        Name: {
            type: DataTypes.STRING,
            allowNull: false
        }
    },
        {
            classMethods: {
                associate: function (models) {

                    Depts.hasMany(models.Employees, {
                        foreignKey: 'DeptId'
                    });
                    Depts.belongsToMany(models.Students, {
                        foreignKey: 'DeptId',
                        through: models.StudentDepts,
                        unique: false
                    });
                }

            },
            timestamps: false
        },
        {
            tableName: 'Depts'
        }

    );
    return Depts;
};

**Student Models as** 

module.exports = function (sequelize, DataTypes) {
    var Students = sequelize.define('Students', {
        Id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'Students',
                key: 'Id'
            }
        },
        Name: {
            type: 'NCHAR',
            allowNull: true
        }
    },
        { timestamps: false },
        { tableName: 'Students' },
        {
            classMethods: {
                associate: function (models) {
                    Students.belongsToMany(models.Depts,
                        { foreignKey: 'StudentId', through: models.StudentDepts, unique: false });
                }
            }
        }
    );
    return Students;
};

**Employees Models as**
module.exports = function (sequelize, DataTypes) {
    var Employees = sequelize.define('Employees', {
        Id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            primaryKey: true
        },
        Name: {
            type: DataTypes.STRING,
            allowNull: false
        },
        DeptId: {
            type: DataTypes.INTEGER,
            allowNull: false,
        }
    },
        {
            classMethods: {
                associate: function (models) {
                    Employees.belongsTo(models.Depts);
                }
            },
            timestamps: false
        },

        {
            tableName: 'Employees'
        }
    );

    return Employees
};

Many to Many Relation here in 
**StudentDepts Model as** 
module.exports = function(sequelize, DataTypes) {
	var StudentDepts =  sequelize.define('StudentDepts', {
		StudentId: {
			type: DataTypes.INTEGER,
			allowNull: false,
			references: {
				model: 'Students',
				key: 'Id'
			}
		},
		DeptId: {
			type: DataTypes.INTEGER,
			allowNull: false,
			references: {
				model: 'Depts',
				key: 'Id'
			}
		}
    },
        { timestamps: false },
        {
		tableName: 'StudentDepts'
        });

    return StudentDepts;
};

Models are initialized by indesx.js which is 

var fs = require("fs");
var path = require("path");
var Sequelize = require("sequelize");
var config = require('../db_config');

var sequelize = new Sequelize(config.database, config.username, config.password, {
    host: config.host,
    dialect: config.dialect,
    dialectOptions: {
        instanceName: config.instanceName
    },
    pool: {
        max: config.max,
        min: config.min,
        idle: config.idle
    },
});

var db = {};

fs.readdirSync(__dirname)
    .filter(function (file) {
        return (file.indexOf(".") !== 0) && (file !== "index.js");
    })
    .forEach(function (file) {
        var model = sequelize.import(path.join(__dirname, file));
        db[model.name] = model;
    });

Object.keys(db).forEach(function (modelName) {
    if ("associate" in db[modelName]) {
        db[modelName].associate(db);
    }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;

Now the issue is when I run 

models.Students.findAll({ raw: true, include: models.Depts }).then(function (data) {
    console.log(data);
});

this works fine

but when I run 

models.Depts.findAll({ raw: true, include: models.Students }).then(function (data) {
    console.log(data);
});

This throws the error of  **Depts is not associated to Students!**

Also how to give more than one association in classMethods ?

currently I am doing 

 classMethods: {
                associate: function (models) {

                    Depts.hasMany(models.Employees, {
                        foreignKey: 'DeptId'
                    });
                    Depts.belongsToMany(models.Students, {
                        foreignKey: 'DeptId',
                        through: models.StudentDepts,
                        unique: false
                    });
                }

            },

**Comment by janmeier** [comment]
The code looks correct - are you sure all associate methods are being called correctly? Try creating all models in a single file and see if it still fails

**Comment by vaibhavramteke787** [comment]
still has same result

**Comment by janmeier** [comment]
Can you post the code you have as a [SSCCE](HTTP://SSCCE.ORG/)? (self-contained test case)

**Comment by vaibhavramteke787** [comment]
hello,
Really sorry but I am not aware of SSCCE
How can I provide my code as SSCCE?

Thanks,
Vaibhav

**Comment by janmeier** [comment]
Just paste the code here - the important part is that it is as small as possible, and that I can simply paste it into my own editor and run it to reproduce the error - see https://github.com/sequelize/sequelize/blob/master/sscce_template.js where you already have a sequelize instance setup, you just need to defined models and code

**Comment by vaibhavramteke787** [comment]
Done

**Comment by janmeier** [comment]
I don't see it :)

**Comment by vaibhavramteke787** [comment]
https://github.com/vaibhavramteke787/sequelize/blob/684c4c97fe55d05b919c5e2db579b617b8f0b083/sscce_template.js

**Comment by janmeier** [comment]
```js
var Students = sequelize.define('Students', {
        Id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'Students',
                key: 'Id'
            }
        },
        Name: {
            type: 'NCHAR',
            allowNull: true
        }
    },
        { timestamps: false },
        { tableName: 'Students' },
        {
            classMethods: {
                associate: function (models) {
                    Students.belongsToMany(models.Depts,
                        { foreignKey: 'StudentId', through: models.StudentDepts, unique: false });
                }
            }
        }
    );
```

You are passing 4 objects to define, instead of two, putting each option into its own object - all options should be in the same object...

**Comment by vaibhavramteke787** [comment]
Thanks.. that worked like  a charm :)
