### ISSUE TITLE
Please make Sequelize alter the table structure instead of dropping the whole schema with data

### ISSUE THREAD

**Issue by SumantaBee** [sequelize/sequelize#6382]
Please make the 'sync' function to alter the table schema instead of dropping all the tables with data. This is not even practical in a production environment. Yes I know about migration. But that is hardly helpful. The best thing I can do right now is changing the orm script, then change the table structures with alter commands manually to prevent data loss.

**Comment by janmeier** [comment]
Please don't open duplicate issues :) https://github.com/sequelize/sequelize/issues/537
