### ISSUE TITLE
Use Indexes in Sequelize.js

### ISSUE THREAD

**Issue by sfaizanh** [sequelize/sequelize#6383]
How to use indexes in Sequelize.js

```
SELECT * FROM tbl1 USE INDEX (index_name)
inner join tbl2 ON tbl1.id = tbl2.fid
order by tbl1.created;
```
Code example:
```
tbl1.findAll({indexes:{name: index_name}, include:{model:tbl2}}).then(function(result){
   console.log(result)
})
```

Already posted on [Stackoverflow](http://stackoverflow.com/questions/38695593/use-indexes-in-sequelize-js)

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/6370
