### ISSUE TITLE
Documentation : `instance.Model` not `instance.Model()`

### ISSUE THREAD

**Issue by iamjochem** [sequelize/sequelize#6384]
hi there,

the [auto-generated] docs are a little but confused regarding the `Model` property of an instance ...
the docs are convinced it's a method:

> http://docs.sequelizejs.com/en/latest/api/instance/#model-model

but the source is quite adamant it's a property 😀 :

> https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/model.js#L732

completely minor - but having not used sequelize for quite a while I've been relying on the docs and this one caught me out.

**Comment by janmeier** [comment]
PR welcome ;) - We've removed the `model` property in 4.0 in favor of inheritance, so not a big concern

**Comment by iamjochem** [comment]
hi @janmeier et al,

I couldn't figure out how to make the auto-gen doc stuff do the right thing (otherwise I would have made a PR) ... looks to me like the relevant doc-block is already defining a property (rather than a method), I figure it's a "docgen" issue (_also the search on the doc site seems to be broken for awhile now_)

I'm not sure inheritance of `Instance` object's from `Model` objects is without problems/complications - there is bound to be some kind of conflict between model properties and instance property ... `name` springs to mind ... I originally stumbled on this because I was writing a couple of global hooks (`after*`), and wanted to determine the name of the underlying model from the given instance (in order to generate strings for use as rabbitmq topic), if the `Instance` object had inherited from `Model` and the `Model` defined an attribute called `name` then I'd be rather stuck (as it happened I was testing with a *User* model that did define a `name` attribute)

I'd love to hear your thoughts on this! possibly I'm worrying about nothing (please do point me to the relevant 4.0 code if you think it will help to enlighten me!)
