### ISSUE TITLE
Migrations and model definitions complains when using TEXT('long') on sqlite

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#6385]
I'm aware of:

https://github.com/sequelize/sequelize/pull/3836
https://github.com/sequelize/sequelize/pull/3839

but still don't like https://github.com/sequelize/sequelize/pull/3839, IMHO is completely unnecesary, and at least there has to be a way to disable that behavior. 

## What you are doing?

Using SQLite adapter for development and MariaDB for staging/production, and defining an unlimited TEXT attribute:

```js
description: {
      type   : Sequelize.TEXT('long')
    }
```

## What do you expect to happen?

In SQLite, it should treat the attribute as a TEXT, and in MariaDB as a LONGTEXT, without complaining and triggering the error, since I think an ORM should do like jQuery did in the past, homogenize the same code and make easier changing the adapter without changing the code (among other thing, I know).

The funny thing is that it correctly translates the type according with the adapter, since was added in https://github.com/sequelize/sequelize/pull/3836, but it also triggers an annoying error/warning that IMHO it should not be doing. 

## What is actually happening?

It is triggering the following error/warning, preventing my app to start correctly:

```
error: >> WARNING: SQLite does not support TEXT with options. Plain `TEXT` will be used instead. 
>> Check: https://www.sqlite.org/datatype3.html
 module=core/db, stack=>> WARNING: SQLite does not support TEXT with options. Plain `TEXT` will be used instead. 
>> Check: https://www.sqlite.org/datatype3.html
``` 

__Dialect:__ mysql / sqlite
__Sequelize version:__ 3.21.0

**Comment by diosney** [comment]
There is a difference between:

a) using an adapter that completely doesn't support a datatype which in this case I agree with triggering an error.

and
b) using an adapter that has a nice way to support the datatype, which doesn't have to trigger the error IMHO.

I think that b) is where support for TEXT datatype fall of, so it should not trigger the error/warning.

**Comment by sushantdhiman** [comment]
Its just a warning and IMHO for correct reason.

SQLite doesn't support `LONGTEXT` ( [their docs](http://sqlite.org/datatype3.html#section_2) ), They only have `TEXT`.

When you try to add the `LONGTEXT` into a dialect which doesn't support it we have to warn you about this incompatibility. Otherwise you would have noticed that for some reason you are unable to insert strings bigger than `64 Kb` in SQLite `LONGTEXT`, surprise :tada: 

Its better to warn / crash ahead of time for any incompatibilities.

**Comment by j-m** [comment]
Would be nice to be able to silence this warning for dev and test environments. 
I use SQLite to run tests as it's much faster and less memory intensive than other dialects. 
For obvious security reasons I use MySQL or PG for production environments.

**Comment by rhwinter** [comment]
@j-m I have the exact same issue!

Did you ever find a way around this, other than (for example) running `jest` with `--silent`?

Thanks in advance :)

**Comment by j-m** [comment]
Apologies @rhwinter but it was a long time ago and I don't remember, I think I just put up with it or worked around it

**Comment by ephys** [comment]
We're working on making all console output generated by Sequelize go through the `log` option that the Sequelize constructor accepts.

Once that is done you'll be able to mute any warning you want.

I must warn that perfect feature parity between dialects is not one of our goals and using a different dialects in prod VS in test can lead to bugs appearing in production. You're of course still free to handle your tests any way you want.
