### ISSUE TITLE
Include filtering while returning the full include results

### ISSUE THREAD

**Issue by FoxMcCloudDX** [sequelize/sequelize#6386]
hello, I am trying to do a query that filters authors by associated books(many-to-many relation) with the following query.

```
Author.findAndCount({
include:[{
    model: Books,
    where: {
          id: 1
     }
   }],
   limit:10,
   offset:0,
   order: [ [ 'id', 'ASC' ] ]
})
```

the problem is, even tough i want only the authors that wrote that specific book, I want each author to have the full list of the books they wrote, but the query only returns the book that matches the where clause inside the include for each author.

Is there a proper way for me to achieve the result that i want, considering that i also need limit,offset and ordering for the authors list?

i tried an alternative way by first getting the book by id with `findOne()` and then getting the associated authors with `book.getAuthors()` but it seems it seems this method does not support neither limit or offset:

```
const book = Book.findOne({
    where:{
      id: 1
    }
});


const authors = book.getAuthors({
    include:[{
       model: Book
    }],
    limit:10,
    offset:0,
    order: [ [ 'id', 'ASC' ] ]
});
```

**Comment by sushantdhiman** [comment]
**You want to find**

- Author of a Book
- Also get all books by that author

**This should work**

```js
Author.findAndCount({
          include:[{
              model: Book,
              where: { id: 1 },
              include: [{ model: Author, include: [Book] }]
          }],
          limit:10,
          offset:0,
          order: [ [ 'id', 'ASC' ] ]
        });
```

You will have to access like `Book.Authors.Books`

**Full Example (With creating sample data and then accessing it)**

```js
var Author = sequelize.define('Author'),
    Book = sequelize.define('Book'),
    AB = sequelize.define('AB');

Author.belongsToMany(Book, { through : AB });
Book.belongsToMany(Author, { through : AB });

sequelize.sync({ force: true })
.then(() => {
  return Author.create().then((a) => {
    return Sequelize.Promise.all([
      Book.create().then((b) => a.addBooks(b)),
      Book.create().then((b) => a.addBooks(b)),
    ]);
  });
})
.then(() => {
  return Author.findAndCount({
          include:[{
              model: Book,
              where: { id: 1 },
              include: [{ model: Author, include: [Book] }]
          }],
          limit:10,
          offset:0,
          order: [ [ 'id', 'ASC' ] ]
        });
})
.then((a) => {
  console.log(a.rows[0].Books[0].Authors[0].Books)
})
.catch(console.error);
```
