### ISSUE TITLE
options.plain is different in model.count() and association.count ()

### ISSUE THREAD

**Issue by daleoooo** [sequelize/sequelize#6387]
I found `options.plain` of `count()`of [model](https://github.com/sequelize/sequelize/blob/v3/lib/model.js#L1606) has value according `options.group`

```
options.plain = !options.group;
``` 

but `options.plain` of `count()` in [hasMany](https://github.com/sequelize/sequelize/blob/v3/lib/associations/belongs-to-many.js#L503) and [belongsToMany](https://github.com/sequelize/sequelize/blob/v3/lib/associations/has-many.js#L348) is just set to be true.

But I think the `options.plain` in association should be set as same as in model, like this:

```
options.plain = !options.group;
``` 

 Am I right?

Thank you for your comments.

__Dialect:__ mysql
__Database version:__ 5.7
__Sequelize version:__ 3.23.6

**Comment by sushantdhiman** [comment]
Not sure but, When group is used result is like `[ {}, {}, {} ]`, in other case its simply a number. I think to get the result into array form we need full result. Thats why its set to `options.plain = !options.group`.

**Comment by sushantdhiman** [comment]
@daleoooo I hope my comment clears the reasoning behind such pattern. I am closing the issue. If you have any specific error, please report. Thanks
