### ISSUE TITLE
Large includes, limit and order create a large ugly query.

### ISSUE THREAD

**Issue by Kyderman** [sequelize/sequelize#6389]
## What you are doing?

``` js
db.customer.findAll(
        {   logging:true,

            include: [{
                model: db.company,

                include: [{
                    model: db.backup_item,
                    include: [{
                        model: db.application,
                    }, {
                        model: db.backup_event,
                        order: [['backup_time', 'DESC']],
                        limit: 1,
                    }],
                }]
            }]
        })
```

With something like the above, I want the customers returned, linked all the way to the backup event containing the latest backup only, I do this to process this time and see whether the latest backup was successful for a given company and then subsequently customer. The backup_event has around 60k rows, each of the other a couple of hundred at most.
## What do you expect to happen?

I expect the query to run generally quickly, however, a massive UNION ALL is generated on each backup items backup events to do the limit and ordering. The query is absolutely gigantic and split into 2 parts. The first part doing all the joins is fine, but that second UNION ALL mess is horrid.

A colleague of mine thinks that the query could be a lot better, but I was wandering whether something has been missed in my usage of the library, to get a more perform-ant query

Any help is appreciated.

**Dialect:** postgres

**Comment by janmeier** [comment]
The query needs to be split somehow, in order for limit and order to be applied correctly (to ensure that it isn't applied to any of the outer queries.
Having deep includes quickly turns into a bit of a mess, and it also takes longer to parse - You might consider adding `separate: true` to the include, which will run it in a separate query, after the main query has been run

**Comment by Kyderman** [comment]
Ive tried a few different configs of separate in different places.
The way it stands is the quickest execution.
