### ISSUE TITLE
Circular models?

### ISSUE THREAD

**Issue by ghost** [sequelize/sequelize#639]
Circular models?

I am creating a nested comment system where comments can have comments (or replies) inside them. The level of nested items can be unlimited (although I could limit it to only a few). I'm familiar with mongoose and noSQL, but not SQL nor have I utilized sequelize. Could someone point me in an accurate direction on the architecture and structure required for this.

Things to consider:

Comments can be replied to
We should be able to count and query direct replies also all nested replies of a comment not just immediate siblings
Needs to be quick and index
Check of reddit it's similar to reddit

**Comment by MJB-Khorasani** [comment]
> ```
> Comment.belongsTo(Comment, {as: "Parent"});
> Comment.hasMany(Comment, { as: "Children", foreignKey: "parent_id", useJunctionTable: false });
> ```
> 
> Should handle most of what you need. The big issue is getting all nested replies in one go, i don't think that will be possible with what we have currently.
> 
> Sequelize doesn't currently create indexes on .sync() but you could skip using sync and create the tables yourself.

what about this one: `Comment.hasMany(Comment, { as: 'Replies' })`;
and now how can i show it in the view like nested comments in other websites.

```
const post = await PostModel.findOne({
  where: { slug, isPublished },
    include: [{ model: CommentModel, include: { model: CommentModel, as: 'Replies' } }],
});
```
