### ISSUE TITLE
Create values in n:m created Table

### ISSUE THREAD

**Issue by atodicebear** [sequelize/sequelize#6392]
Sorry to ask it here but I saving Datas in the Created n:m Table is not working.
Tried several things allready from the Examples of the Documentation.

If you could have a Look and suggest something ?
In short on my Backend the saving Data function is not working.
http://stackoverflow.com/questions/38791728/sequelize-save-data-in-belongstomany-created-table-and-read-from-it/38797541#38797541

## What you are doing?
See link above
## What do you expect to happen?
I want to save Data in the Created n:m Table

## What is actually happening?
Nothing or Error

__Dialect:__ mssql
__Database version:__ sql server 2014
__Sequelize version:__ 3.5.1

**Comment by sushantdhiman** [comment]
Please provide a SSCCE ( [What is SSCCE ?](http://sscce.org), [How to create one in Sequelize ?](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

**Comment by atodicebear** [comment]
If i search for ssccee.js it finds nothing only
sscce_template.js where stands the same as in the HowTo.
Trying npm run sscce-mssql is saying missing script.
Have I to create it myself the sscce.js or did went something wrong in the Installation and its not there?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/blob/master/sscce_template.js#L2

**Comment by atodicebear** [comment]
Ive Copied it to "sscce.js" and tried as well with ".sscce.js".
Add some code from me.
But npm run still says missing script.
Its in the nodemodules sequelize.
Then I copied it to the npm folder where npm-cli.js is, its where the Error is thrown and still not running.

Im sorry if I misunderstood something and did wrong.

**Comment by janmeier** [comment]
If you have some other way of running a test script, thats fine as well - The important thing is that you create a self contained test case that we can copy paste and easily run

**Comment by atodicebear** [comment]
Sorry iam new to this all so I dont really know how to get it run.
But maybe if u have just a Look at the code you can Tell what i did wrong:
In short I create a n:m Table with Sequelize:
```
// Tasks n:m Keys
db.DictKey.belongsToMany(db.Task, { through: 'TaskKeys' , foreignKey:'key_id',otherKey:'task_id'});
db.Task.belongsToMany(db.DictKey, { through: 'TaskKeys' , foreignKey: 'task_id',otherKey: 'key_id'});
```
For Tests I Inserted myself then Data in this TaskKey table
```
TaskID | KeyID
1      | 1
1      | 2
1      | 3
2      | 4
2      | 5
```
Getting it is working. Getting the right Task from Task-Table with the Dependant Keys with Values through TaskKey
```
export function show(req, res) {
  return Task.findAll({
    where: {
      _id: req.params.id
    },
    include: [{
      model: DictKey
    }]
  })
    .then(handleEntityNotFound(res))
    .then(respondWithResult(res))
    .catch(handleError(res));
}
```
But saving throws an 500Error
```
**FrontEnd**
this.$http.post('/api/tasks', {
              task:{
              user_id: $scope.selectUser,
              lang_id: $scope.selectLang,
              name: $scope.newTask
            },
            keys:[1,2,3,4,5]
          });
**BackEnd**
// Creates a new Task in the DB
export function create(req, res) {
  return Task.create({//this works he creates a Task
    name: req.body.task.name,
    user_id: req.body.task.user_id,
    lang_id: req.body.task.lang_id,
  })
  .then(function(task){// this error. He shall create in TaskKey the new TaskId with the send Keys
    return Task.addKey(req.body.keys);
  })
    .then(respondWithResult(res, 201))
    .catch(handleError(res));
}
```
I think i misunderstood the Syntax of the Function?
But ive tried allready several Forms:
Task.addKey(task),
Task.addKey(1),
Task.addKeys(task),
Task.addKey(req.body.keys),
DictKey.addTask(task),
DictKey.addTask(1),
DictKey.addTaskKey(req.body.keys)
and and not one was working.

Thx for your help

**Comment by janmeier** [comment]
`Task` (capital T) refers to the task model - You should probably use the instance `task`.

If the key rows are already created, you can pass the ids as you do - otherwise you need to create them first. Either with `DictKey.bulkCreate`, or a loop that calls `task.createDictKey`

Telling us that it gives you error 500 doesn't really help - You need to see what the actual error message is (javascript syntax error, sql error, sequelize error etc)

**Comment by atodicebear** [comment]
Can I just use task instance?
Because 
```
// Tasks n:m Keys
db.DictKey.belongsToMany(db.Task, { through: 'TaskKeys' , foreignKey:'key_id',otherKey:'task_id'});
db.Task.belongsToMany(db.DictKey, { through: 'TaskKeys' , foreignKey: 'task_id',otherKey: 'key_id'});
```
Is in my index.js where I set all ForeignKeys/Import the db.Models and doing my Connection.
The Create/Get is in task.controller.js where I just
`import {Task} from '../../sqldb';`
So
```
.then(function(task){
    return task.addKey(req.body.keys);
  })
```
Small Capital t is fine? Or have is somehow to initialize the Instance?
task = this.Task; //?

How could I get a more Detailed Error Info?
Because in cmd Console : 
POST /api/tasks 500
and Browser Conole the only output is:
`POST http://localhost:9000/api/tasks 500 (Internal Server Error)(anonymous function) @ angular.js:11881sendReq @ angular.js:11642serverRequest @ angular.js:11352processQueue @ angular.js:16170(anonymous function) @ angular.js:16186$eval @ angular.js:17444$digest @ angular.js:17257$apply @ angular.js:17552(anonymous function) @ angular.js:25627dispatch @ jquery.js:5110elemData.handle @ jquery.js:4918`

**Comment by janmeier** [comment]
> Small Capital t is fine? Or have is somehow to initialize the Instance?
capital means a large t (T), there is no such thing as a small capital letter :P

Whats important is that you refer to the variable you get in - if you call it `task`, use `task` - if you call it `foobaR`, use `foobaR`. 

You have to look at the server console to see the error - But that depends on whatever backend framework you are using, and is not related to sequelize.

**Comment by atodicebear** [comment]
haha ok thx learning every Day something new :+1: 
That is where I started
Example of Sequelize Docs
```
Project.create({ id: 11 }).then(function (project) {
  user.addProjects([project, 12]);
});
So I changed it to mine
.then(function(task){
    return Task.addKey(task);
  })

```
But I didnt have the Instances user/project like in the Example used. So I went with DictKey and Task.

Node + Express for Backend.
Checked Express in Error/Debug
For Error:
```
  .then(function(task){
    return task.addKey(req.body.keys);
  })
    .then(respondWithResult(res, 201))
    .catch(handleError(res));//catches here
}
function handleError(res, statusCode) {// works here but not much help
  statusCode = statusCode || 500;
  return function(err) {
    res.status(statusCode).send(err);
  };
}
```
Debug:
setting
set DEBUG=express:* & node index.js
in nodemodules/express
Didnt change the output of Error, still just 500

**Comment by janmeier** [comment]
I'm simply not sure what your question is anymore - Figuring out what error you are getting is related to express, not sequelize

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
