### ISSUE TITLE
hasOne relationship should have an unique foreign key? 

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6393]
for example:
`Person.hasOne(Head)`
 // foreign key on Head, which is Head.personId, in default, unique is not unique

`Person.hasOne(Head, { foreignKey: { unique: true } })`
 // this should be expected for default case,

since Person only has one Head, that means Head.personId should be an unique key.

**Comment by sushantdhiman** [comment]
Should a foreign key be unique or not, well it depends upon use-case.

We have just chosen the simplest form, to just add the foreign key without unique. If user really need unique foreign key, they can set `unique: true`
