### ISSUE TITLE
How to know 'create'and'update' result?

### ISSUE THREAD

**Issue by hezhongfeng** [sequelize/sequelize#6396]
like this 
```js
  let result = await User.update(
    {name : 'shjhkj' },
    {
      where: {id: id}
    });
```
how to use the `result ` to know update/create is successful or fail?

**Comment by sushantdhiman** [comment]
[Update](http://docs.sequelizejs.com/en/v3/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows) doesn't create anything, it just update the records matched by `where`. It returns `affectedCount` and `affectedRows`

To update or create you can use [Upsert](http://docs.sequelizejs.com/en/v3/api/model/#upsertvalues-options-promisecreated).

**Comment by hezhongfeng** [comment]
@sushantdhiman 
Thank you for your answer.
And I know the different between create and update.
I just want to know this execution's result is successful or fail?
For example:
The model `User` has a unique  field `name`
So when I create a same one twice, the first will be successful and the second will be fail.
Do you know how to distinguish successful or fail?
I think I will be found in `result`

**Comment by sushantdhiman** [comment]
Do you realize every function in Sequelize Public API returns a Promise, on which you can add `.then` or `.catch` ? Make sure you understand what [Promise](http://bluebirdjs.com/docs/why-promises.html) and [Async/await](http://rossboucher.com/await/#/5) are.

In `ES7`, async/await function also return Promise, you can add `.then` `. catch` on them too, otherwise you can warp await statement with `try/catch`

**Comment by hezhongfeng** [comment]
@sushantdhiman 
Do you means when it fail.
I will catch the err?

**Comment by sushantdhiman** [comment]
@hezhongfeng Yup, second time it will fail with unique constraint error.

**Comment by hezhongfeng** [comment]
@sushantdhiman 
Thank you for your answer.
And I will close this issue.

**Comment by sushantdhiman** [comment]
@hezhongfeng np :)

**Comment by jehnsen** [comment]
please help.. can't update data with this syntax

router.post('/updatemainads/:id', function (req, res, next) {
  db.Ad.upsert(
   {filename: req.body.imgName},
   {link: req.body.txtLink},
   {where:  { id: req.params.id }}
 )
 .then(function(rowsUpdated) {
   res.json(rowsUpdated)
   console.log(rowsUpdated)
 })
 .catch(next)
})

**Comment by eseliger** [comment]
@jehnsen why are you passing 3 arguments to upsert? 
see here for correct syntax and feel free to refer to stackoverfow os sequelize slack for help on programming: http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-upsert
