### ISSUE TITLE
sequelize does not support JSONB column as foreign key

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6399]
I tried to make a JSONB column as a primary key.
It's OK for postgreSQL and normal use of sequelize.
But it will get error when use the `getXXX` associate function.

in
model.js
```
    if (typeof param === 'number' || typeof param === 'string'  || Buffer.isBuffer(param)) {
      options.where = {};
      options.where[this.primaryKeyAttribute] = param;
    } else {
      throw new Error('Argument passed to findById is invalid: '+param);
    }
```
The if statement should be

```
    if (typeof param === 'number' || typeof param === 'string'  || typeof param === 'object' || Buffer.isBuffer(param)) {
```

**Comment by janmeier** [comment]
Feels really dirty to me to use a json column as a primary key - Whats wrong with a regular `SERIAL` :)?

**Comment by frogcjn** [comment]
SERIAL requires developer to loop up the max value, so I'm afraid of that situation.

**Comment by janmeier** [comment]
> SERIAL requires developer to loop up the max value,

What do you mean - Serials are auto incrementing.

You can use UUID if you want a unique string

**Comment by frogcjn** [comment]
1，2，3，（insert a 9), 4，5，6，7，8，9（conflict）

or copy data from other database.

**Comment by frogcjn** [comment]
like: https://www.postgresql.org/docs/8.1/static/sql-createsequence.html

Update the sequence value after a COPY FROM:
```pg
BEGIN;
COPY distributors FROM 'input_file';
SELECT setval('serial', max(id)) FROM distributors;
END;
```

**Comment by janmeier** [comment]
In that case, I'd recommend using UUIDs - you can even make postgres generate them automagically

**Comment by frogcjn** [comment]
It is just a test to use a JSONB as primary key.
