### ISSUE TITLE
'Order by' like Mongoose.js

### ISSUE THREAD

**Issue by jdnichollsc** [sequelize/sequelize#6403]
Is possible use the **order** like Mongoose.js?

- Current way:
```javascript
something.findOne({
  order: [
    ['username', 'DESC'],
    ['firstname', 'ASC'],
    ['lastname', 'DESC'],
  ]
})
```

- Like Mongoose.js:
```javascript
something.findOne({
  order: { username : -1, firstname : 1, lastname : -1 }
})
```

What do you think? :dancers:

**Comment by felixfbecker** [comment]
Imo the current syntax is much more concise and there is no reason why it should be changed. Also your example does not specify in what order the attributes should be considered.

**Comment by jdnichollsc** [comment]
In the same order: { username : -1, firstname : 1, lastname : -1 }

I think you can include this option because is more easy, see my following code to support that:

```javascript
var getOrderByParams = function (cols) {
    var arrayOrder = [];
    cols = cols || {};
    for (var col in cols) {
        if (cols.hasOwnProperty(col)) {
            arrayOrder.push([col, cols[col] === 1 ? "ASC" : "DESC"]);
        }
    }
    return arrayOrder;
};
```

Thanks for your quickly response!

**Comment by felixfbecker** [comment]
The order of properties in object literals is not preserved, only in arrays. And ASC and DESC is definitely more meaningful than -1 and 1.

**Comment by jdnichollsc** [comment]
> The order of properties in object literals is not preserved, only in arrays
What? In particular the V8 engine preserves the ordering, which is the engine used in node.js so it's no problem... check please http://stackoverflow.com/a/18514551/1532821

> And ASC and DESC is definitely more meaningful than -1 and 1.
And What do you think about that?
```javascript
something.findOne({
  order: getOrderByParams({ username : "DESC", firstname : "ASC", lastname : "DESC" })
})
```

Considers this option please

**Comment by felixfbecker** [comment]
But it is not guaranteed and non-standard. There are lint rules that require that all object literals have alphabetically sorted properties. Coworkers might move around keys because they don't expect it to change anything. There is no way to change the order at runtime. Minifiers might mangle them during their code -> AST -> minified code conversion.

Plus the current syntax also supports `Sequelize.literal()` and `Sequelize.col()`. You would not be able to support that with an object literal.

**Comment by janmeier** [comment]
This is definitely not going to happen - Felix already gave you several reasons why this is a bad idea. If you really want to do it in your own code, you can use hooks to alter the options http://docs.sequelizejs.com/en/v3/docs/hooks/
