### ISSUE TITLE
Will sequelize support Array ELEMENT foreign keys association for PostgreSQL?

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6405]
Will sequelize support Array ELEMENT foreign keys association for PostgreSQL?
https://www.postgresql.org/message-id/1343842863.5162.4.camel@greygoo.devise-it.lan

**Comment by janmeier** [comment]
Pretty sure this never made it into the trunk https://www.postgresql.org/message-id/CAA-aLv437K%3Dj24LuGoeOaz%3DY6NN5o5tvMfMay%3D_7LtaEmVWz%3DQ%40mail.gmail.com. I don't see it in the reference for create table https://www.postgresql.org/docs/9.1/static/sql-createtable.html
