### ISSUE TITLE
One to Many relation on Foreign Key column - Postgres 9.5.3

### ISSUE THREAD

**Issue by JesseDavid** [sequelize/sequelize#6410]
I’m having issues setting up the relations for a one to many relationship where the “many" table references the “one” table through a non-primary key column on the “one” table. The schema has already been predetermined, so I'm not able to edit it at all.

Postgres v9.5

Here’s the models:

`
var Offer = sequelize.define(‘offer’,{
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            allowNull: false,
            field: "id"
        },
        otherid:{
            type: Sequelize.STRING,
            allowNull: false,
            field: “otherid"
 });
`
`
var Attachment = sequelize.define(‘attachment’,{
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            allowNull: false,
            field: "id"
        },
        otherid:{
            type: Sequelize.STRING,
            allowNull: false,
            field: “otherid"
        },
        parentid:{
            type: Sequelize.STRING,
            allowNull: true,
            field: "parentid",
            references: {
                model: Offer,
                key: "otherid"
            }
        }
)
`

Each Offer should have many Attachments.

I set up the relations like this:

`
Attachment.belongsTo(Offer, {foreignKey:'parentid', targetKey:’otherid'});
`
`
Offer.hasMany(Attachment, {as: 'Attachments',foreignKey:'otherid'});
`

I know the Attachment.belongsTo relation is set up correctly, since I’m able to query for it and get the related Offer object returned:

`
attachments.findOne({
                include: [
                    {model: m_offerCreatives}
                ]
            })
`

However, when I go to find the Offers, I get an error saying they aren’t related:

`
Offer.findAll({
                include: [
                    {model: Attachment, as:'Attachments'}
                ]})
`

Error:
"attachment (Attachments) is not associated to offer!"

I’ve tried setting this up every way I can think of from the docs, including defining Offer.belongsToMany(Attachment), but since there is no join table, I can’t seem to get it correct. I tried to do something similar for a Many-to-Many relationship with a join table that stores non-primary keys, but wasn’t able to get that to work either (I think it was the same issue in #4092).

Is it possible to have this one-to-many relationship on a non-primary key column?

Thanks!

**Dialect:**  postgres
**Database version:** 9.5.3
**Sequelize version:** 3.16

**Comment by janmeier** [comment]
Try to make sure the association methods are actually called - everything looks correct to me. 

You could also save the return value from he association `offer.attachments = offer.hasMany...` followed by `include: [{association: offer.attachments}] `

**Comment by felixfbecker** [comment]
@janmeier Isn't that association object already available through `offer.associations.Attachments`? 😉

**Comment by JesseDavid** [comment]
I updated my code to:

```js
Attachment.belongsTo(Offer, {as: 'Creative',foreignKey:'parentid', targetKey:'otherid'});

Offer.attachments =
	Offer.hasMany(Attachment, {as: 'Attachments',foreignKey:'otherid'});

offerCreatives.findOne({
				include: [
					{association: Offer.attachments}
				]
			})
```
But I get a db error now:

`
"operator does not exist: integer = character varying"
` 
This comes from the JOIN on the tables not including the proper foreign key relation.

```SQL
SELECT
  "offer".*,
  "Attachments"."id"          AS "Attachments.id",
  "Attachments"."otherid"        AS "Attachments.otherid",
  "Attachments"."parentid"    AS "Attachments.parentid"
FROM
  (SELECT
      "offer"."id",
      "offer"."otherid"
    FROM "schema"."offer" AS "offer"
    LIMIT 1) AS "offer"
LEFT OUTER JOIN "schema"."attachment" AS "Attachments"
    ON "offer"."id" = "Attachments"."otherid";
```
The error comes from the id column being a number, and otherid being a varchar.

Shouldn't the last line of above should be?
```SQL
ON "offer"."otherid" = "Attachments"."otherid";
```

I would think that the hasMany should be able to take a "targetKey" parameter like the belongsTo call can.

**Comment by janmeier** [comment]
@felix yes, but it's broken for belongs to many (have to get that fixed soon)... 

@jessedavid you need target key on both sides of the association

**Comment by JesseDavid** [comment]
I added the targetKey but still got the same error and the SQL doesn't look like it updated:

```js
	m_offerCreatives.hasMany(m_attachments, {as: 'Attachments', foreignKey: 'sfid', targetKey: 'parentid'});
```

(SQL the same)

I'm using Typescript and the interface definition for hasMany doesn't seem to have "targetKey" defined (not sure if this is a typings error or not).
