### ISSUE TITLE
result.count for findAndCountAll is incorrect with include

### ISSUE THREAD

**Issue by andreabianco** [sequelize/sequelize#6418]
## What you are doing?
Hello, I'm trying to use findAndCountAll methods for list view pagination.
I have different models but I can post one example.

```js
sequelize.define('Model1');
sequelize.define('SubModel1');
sequelize.define('SubModel2');
sequelize.define('SubModel3');
```
Model1 is associated with SubModule1, SubModule2 and SubModules with hasMany relation.

Now in the database I have 15 Model1 items.

## What do you expect to happen?
If I perform the findAndCountAll I expect to see the following response:
```js
{ count: 15,
  rows: [...] }
```
## What is actually happening?
But the real result is:
{ count: 33,
  rows: [...] }

__Dialect:__ mysql
__Database version:__ 5.6
__Sequelize version:__ 3.23.2

**Comment by janmeier** [comment]
Please show the actual code for each model, their associations, and the call to find and count - we can't help you if we can't replicate the issue...

**Comment by andreabianco** [comment]
Sure!

```js
var Module1 = sequelize.define('Module1', {
    name: DataTypes.STRING
  }, {
  associate: function(models) {
     Module1.hasMany(models.SubModel1);
     Module1.hasMany(models.SubModel2);
    Module1.addScope('all', {
        include: [{
          model: models.SubModel1
        }, {
          model: models.SubModel2
        }]
      });
  }
});

var SubModel1 = sequelize.define('SubModel1', {
    name: DataTypes.STRING
  });

var SubModel2 = sequelize.define('SubModel2', {
    name: DataTypes.STRING
  });

return Module1
    .scope('all')
    .findAndCountAll({ where: {}, limit: 10, offset: 0 })

```

Sorry for bad formatting

**Comment by leohihimax** [comment]
+1, we met the same issue.

**Comment by sushantdhiman** [comment]
@leohihimax and @andreabianco Have you tried passing `distinct: true` ( with `col`, if required).

**Comment by andreabianco** [comment]
@sushantdhiman Can you explain better how to use distinct property?

**Comment by leohihimax** [comment]
@sushantdhiman thx, distinct option solved this issue.
@andreabianco [distinct usage](http://sequelize.readthedocs.io/en/v3/api/model/#countoptions-promiseinteger).  Actually, the API `findAndCountAll` use `count` API to count.

**Comment by andreabianco** [comment]
@leohihimax Is it right?

```js
return Module1
    .scope('all')
    .findAndCountAll({ where: {}, limit: 10, offset: 0, distict:true })
```

**Comment by leohihimax** [comment]
@andreabianco That's right, except the `distinct` typo.

**Comment by sushantdhiman** [comment]
@andreabianco @leohihimax It seems `distinct` solves it. I am closing the issue. Let me know if it doesn't :)

**Comment by andreabianco** [comment]
I tested with Sequelize v. 3.19.3 and it's working correctly. 
I update to the version 3.24.0 but it generate an invalid query.

SELECT count(DISTINCT(*)) AS `count` FROM `model1` AS `Model1` LEFT OUTER JOIN `submodel1` AS `SubModel1` ON `Model1`.`id` = `SubModel1`.`Model1Id` ...
