### ISSUE TITLE
running in browser

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6424]
Suppose i will write browser side driver for Sequelize, would it run in browser with this driver?

Thanks

**Comment by janmeier** [comment]
Probably not - I'm pretty sure we have a lot of code that assumes a node.js environment and requires the node.js "standard library"

**Comment by sushantdhiman** [comment]
Agree with @janmeier , We need lots of Node stuff to perform queries. Not sure how we can run the dialect drivers on browser

**Comment by alexey2baranov** [comment]
thanks for fast reply.
