### ISSUE TITLE
parent child association  (Postgres dialect)

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6425]
could not save parent-child relation.
hire is my model definition :

As you can see i would like Zemla (location) to have a parent and children reference to itself

```
module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Zemla', {
        id: {
            type: DataTypes.BIGINT,
            primaryKey: true,
            autoIncrement: true
        },
        name: {
            type: DataTypes.STRING,
            allowNull: false
        }
    });
};

  models.Zemla.belongsTo(models.Zemla, {
    as: "Parent"
  });
 models.Zemla.hasMany(models.Zemla, {
    as: "Children",
    foreignKey: "parent_id"
  });
```

and now simple test code :
```
models.sequelize
    .authenticate()
    .then(function (err) {
        console.log('Connection has been established successfully.');

        return models.sequelize.sync({force:true, logging: console.log})
    })
    .then(()=> {
        return models.Zemla.create({ name: 'world'});
    })
    .then((world)=> {
        var region= models.Zemla.build({name: 'region', Parent: world});
        region.setParent(world);
        return region.save();
    })
```

get this log. as i can see first part of log (DDL) is very correct but second part (SQL) are wrong. What is my mistake?

> DROP TABLE IF EXISTS "Zemla" CASCADE;
> Executing (default): CREATE TABLE IF NOT EXISTS "Zemla" ("id"  BIGSERIAL , "name" VARCHAR(255) NOT NULL,"parent_id" BIGINT REFERENCES "Zemla" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));

> Executing (default): INSERT INTO "Zemla" ("id","name") VALUES (DEFAULT,'world') RETURNING *;
> Executing (default): INSERT INTO "Zemla" ("parent_id") VALUES ('1');
> Executing (default): INSERT INTO "Zemla" ("id","name","parent_id") VALUES (DEFAULT,'region','1') RETURNING *;

**Comment by sushantdhiman** [comment]
`region.setParent(world);` is a Promise too

```js
.then((world)=> {
        var region= models.Zemla.build({name: 'region', Parent: world});
        return region.save()
                     .then((regionSaved) => {
                          return regionSaved.setParent(world);
                     });
    })
```

**Comment by alexey2baranov** [comment]
can i do the same task inside build() or create() method?

like this
`let region= models.Zemla.create({name: 'region', Parent: world});`

**Comment by sushantdhiman** [comment]
This will help you http://docs.sequelizejs.com/en/v3/docs/associations/#creating-with-associations

**Comment by alexey2baranov** [comment]
yes i got this page before, thank you. but mots times new model associated with persisted objects. 
So how can I associate new model with persisted models? can i do some short like this ?
`let region= models.Zemla.create({name: 'region', Parent: world});`  //world is a persisted object

**Comment by sushantdhiman** [comment]
For already saved instance you will have to use `setParent`

**Comment by alexey2baranov** [comment]
ok. thank you. hope you'l  find time to implement this feature

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/5325
