### ISSUE TITLE
Double timestamps in JSON

### ISSUE THREAD

**Issue by szemek** [sequelize/sequelize#6426]
Hey,
I want to accomplish following scenario:
- columns in database are using underscores
- keys in JSON (serialized instance) are using camelCase naming
- bulkCreate works

Here's the example:

```js
var User = sequelize.define('user', {
  username: Sequelize.STRING,
  birthday: Sequelize.DATE,
  createdAt: {
    type: Sequelize.DATE,
    field: 'created_at',
  },
  updatedAt: {
    type: Sequelize.DATE,
    field: 'updated_at',
  },
}, {
  timestamps: true,
  underscored: true,
});
```

Following snippet:
```js
sequelize.sync({ force: true }).then(function() {
  return User.create({ name: 'john' });
}).then(function() {
  User.bulkCreate([{ name: 'simon' }]);
}).then(function() {
  return User.findAll();
}).then(function(result) {
  console.log(JSON.stringify(result));
});
```
produces:

```json
[
  {
    "id": 1,
    "name": "john",
    "createdAt": "2016-08-12T10:42:30.754Z",
    "updatedAt": "2016-08-12T10:42:30.754Z",
    "created_at": "2016-08-12T10:42:30.754Z",
    "updated_at": "2016-08-12T10:42:30.754Z"
  },
  {
    "id": 2,
    "name": "simon",
    "createdAt": "2016-08-12T10:42:30.766Z",
    "updatedAt": "2016-08-12T10:42:30.766Z",
    "created_at": "2016-08-12T10:42:30.766Z",
    "updated_at": "2016-08-12T10:42:30.766Z"
  }
]
```

As you can see I have doubled timestamps. I'd like to have only camelCase version. I was trying different set of options but at some point `bulkCreate` stopped working.
As a workaround it's possible to override `toJSON` function, but I'd prefer to configure desired behaviour via model definition.

I checked that for:
__Dialect:__ sqlite, mysql, postgres
__Database version:__ sqlite3 3.8.10.2, MySQL 5.7.12, PostgreSQL 9.5.1
__Sequelize version:__ 3.24.0

**Comment by sushantdhiman** [comment]
Its fixed in `master` (v4), https://github.com/sequelize/sequelize/pull/6219. Not released in `v3`
