### ISSUE TITLE
Please Consider export an Connection Object for User

### ISSUE THREAD

**Issue by xxxman2008** [sequelize/sequelize#6429]
Hi, guys

     I have seen someone discuss "catch connection errors". And i also agree these errors is  driver-level errors .

    But , i really  have no idea when Sequelize told me  "Unhandled rejection SequelizeConnectionError: connect ETIMEDOUT".

    Sequelize is an ORM ,not driver. ---  OK .
    But ,why don't you make DB Connection  keep alive always??  
    if Sequelize will not charge the db connection ,how about export an "Connection object"  to User , let them do anything they like?
    
     Just advise.

Raymond

**Comment by janmeier** [comment]
When do you get this error? Does it happen sometimes or are you not able to connect at all? 

What do you think should happen instead? There's nothing sequelize can do if it cant reach the database - so it tells you that there was an error.

**Comment by felixfbecker** [comment]
A `Sequelize` instance represents a pool of connections. _Unhandled rejection_ actually means that this was probably a rejected promise from one of your queries that you didn't handle.
