### ISSUE TITLE
Best way to select row of a max record in group?

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6430]
a table has a groupId field, and a value field

How to select the full row record the max value in the group using sequelize?

I can only figure it out with SQL:
```sql
SELECT 
    a.*
FROM
    table a
        INNER JOIN
    (SELECT 
        groupId, MAX(value) value
    FROM
        table
    GROUP BY groupId) b ON a.groupId = b.groupId
        AND a.value = b.value
GROUP BY a.groupId
```
and let sequelize run it.
```js
const results = await sequelize.query(sqlSentence, { model: SiteContent })
```

**Comment by janmeier** [comment]
Currently we only support joins on relations defined in sequelize, and we don't have great subquery support either https://github.com/sequelize/sequelize/issues/2787

**Comment by frogcjn** [comment]
OK. Thanks. It's best enough.

**Comment by PatrickGeyer** [comment]
Any news on this @janmeier, is this still not possible?

**Comment by yosagar** [comment]
I managed to get the required result as below
```
Model.findAll({
        where: { id: { [Sequelize.Op.in]: [Sequelize.literal('SELECT MAX(id) FROM table a GROUP BY groupId')] } },
      });
```

**Comment by 7hibault** [comment]
Still using a little bit of SQL, I think the following should work, using `DISTINCT ON` ([official doc](https://www.postgresql.org/docs/9.0/sql-select.html#SQL-DISTINCT)).

- order by your groupId
- order by the value on which you check the max
- select only the first row (the max because it is ordered) for each groupId

```javascript
const results = await MyModel.findAll({
	attributes: [sequelize.literal('DISTINCT ON ("groupId") "MyModels"."groupId"'), 'value'],
	order: [['groupId', 'DESC'], ['value', 'DESC']]
})
```

**Comment by Salmandabbakuti** [comment]
> I managed to get the required result as below
> 
> ```
> Model.findAll({
>         where: {
>           id: { 
>             [Sequelize.Op.in]: [Sequelize.literal('SELECT MAX(id) FROM a GROUP BY groupId')]
>           }
>         },
>       });
> ```
above query returning duplicate values too. is there any workaround to prevent duplicates using above query?
