### ISSUE TITLE
Error with wrong alias in 'like ?' inside findAndCountAll

### ISSUE THREAD

**Issue by stefanoeb** [sequelize/sequelize#6431]
## What you are doing?
Here are my models:
```js
var Author = sequelize.define('Author', {
    id: {
        type: Sequelize.BIGINT,
        primaryKey: true
    },
    name: Sequelize.STRING
}, {
    tableName: 'author'
});
var Book = sequelize.define('Book', {
    id: {
        type: Sequelize.BIGINT,
        primaryKey: true
    },
    name: Sequelize.STRING
}, {
    tableName: 'book'
});

//1:n relation between them
Author.hasMany(Book, {
    foreignKey: {
        name: 'author_id',
        allowNull: false
    },
    onDelete: 'CASCADE'
});
```

And this is the query
```js
Author.findAndCountAll({
    include: [
        {
            model: Book,
            required: true,
            where: ['Books.name like ?', '%bar%']
        }
    ],
    offset: 0,
    limit: 20
})
```

## What do you expect to happen?

- A count(*) select of all rows (works just fine)
- A query that retrieves the rows that match my filter

## What is actually happening?
Well, the count() query works perfectly, but the seconds query breaks with ER_BAD_FIELD_ERROR: Unknown column 'Books.name' in 'where clause'..
As seen in the output below, the seconds query "forget" to name the alias from Book table (should be Book as Books, since it is a 1:n relation).
**IMPORTANT: Sequelize 3.1.1 works fine, this issue is in the 3.24.0**

`SELECT `Author`.*,
       `Books`.`id` AS `Books.id`,
       `Books`.`name` AS `Books.name`,
       `Books`.`createdAt` AS `Books.createdAt`,
       `Books`.`updatedAt` AS `Books.updatedAt`,
       `Books`.`author_id` AS `Books.author_id`
FROM
  (SELECT `Author`.`id`,
          `Author`.`name`,
          `Author`.`createdAt`,
          `Author`.`updatedAt`
   FROM `author` AS `Author`
   WHERE
       (SELECT `author_id`
        FROM `book` AS `Book`
        WHERE (`Book`.`author_id` = `Author`.`id`
               AND (Books.name LIKE '%bar%')) LIMIT 1) IS NOT NULL LIMIT 0,
                                                                         20) AS `Author`
INNER JOIN `book` AS `Books` ON `Author`.`id` = `Books`.`author_id`
AND Books.name LIKE '%bar%';`

__Dialect:__ mysql
__Database version:__ 5.7.14
__Sequelize version:__ 3.24.0

**Comment by edgardksb** [comment]
+1

**Comment by Lichtjaeger** [comment]
Try: `where: { name: { $like: '%bar%' } }`

**Comment by stefanoeb** [comment]
@Lichtjaeger Yes, it works, but the problem is that I need to do some replaces in the column value before the comparison.

Anyway, I "solved" it by executing a count(*) query apart from the select.
I'm closing the issue for now.
