### ISSUE TITLE
Provide delete() as alias for destroy()

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6433]
Now that we don't have to support old Node versions anymore we could provide `delete()`. When I started using Sequelize I always expected it to be `delete()` (because it's DELETE in SQL) and had to look at the docs first to find the right method.

**Comment by sushantdhiman** [comment]
We should also change paranoid to softdelete, that one always confuse me.

**Comment by opatut** [comment]
`delete` is a reserved keyword in javascript though. While newer environments allow the syntax `foo.delete`, some older ones fail with that, and one has to write `foo['delete']`. I guess that was the rationale behind naming it `destroy` in the first place.

Similarily, `select` is defined on `window` in browser scope, which might be why we have `find` instead. And `.catch()` on promises fails in old versions of IE, one needs to use `myPromise['catch']()` there (urgh!).

I'm against adding more aliases, and even more against using reserved words as variable names (even though it might work under some conditions).

Source: http://www.w3schools.com/js/js_reserved.asp

**Comment by felixfbecker** [comment]
Yeah that's why I said _since we don't need to support old Node versions anymore_. Express once also provided `del` instead of `delete`, now it's deprecated. Your `window.select` argument doesn't make much sense though as it is on `window` and Sequelize will never run in the browser anyway. And as you pointed out even the native `Promise` API uses `catch` now. Reserved words are only invalid as variable names, not property names. You cannot define a variable `static`, `case`, `delete` etc. but it's perfectly fine to have them as property.

**Comment by opatut** [comment]
Sorry, I missed the part about old node versions. And you're right with the variable vs property names.

Still, if you're interested in my opinion: I dislike the tendency of naming properties with reserved keywords. I ran into problems with express' `delete` already, e.g. while destructuring or using object literal shorthands: 

    export function get() { /* ... */ }
    export function delete_() { /* ... */ } // meh
    export default {get, delete: delete_}; // meh meh

I furthermore dislike aliases if the original name is not being deprecated, and prefer it if there is exactly one way to do something.

**Comment by felixfbecker** [comment]
> I furthermore dislike aliases if the original name is not being deprecated, and prefer it if there is exactly one way to do something.

Sequelize authors don't share this opinion :D We have so many aliases `findAll`, `find`, `findAndCount`, `findAndCountAll`, `findById`, `findByPrimary`....
And I think it's a good thing (even though I maintain the Sequelize TS typings and have to duplicate everything).
