### ISSUE TITLE
Unable to populate postgresql id serial column

### ISSUE THREAD

**Issue by milovanderlinden** [sequelize/sequelize#644]
I have models set up using a postgresql database. Since I have legacy data, I want to populate the tables with preset id-column values. This is possible in postgresql itself.

But when using sequelize, I discover that it simply ignores me setting the id. Can I bypass this? I tried by adding a second column that holds my id and is no primary key and no serial (autoincrement) but than the associations fail. Is what I want possible?

```
models.Role.create({id: -1, name: 'no access'});
models.User.create({id: 1, name: 'Milo': role_id: -1})
models.Role.find({where: {id: -1}}).success(function(place) {
        console.log('Found!' );
    })
```

(the statement above fails)

**Comment by ashwin-sekhar** [comment]
i still have this issue. is this because of any version conflict?
