### ISSUE TITLE
support updateOnDuplicate in create w/ postgres?

### ISSUE THREAD

**Issue by contra** [sequelize/sequelize#6445]
Postgres 9.5 seems to support this functionality, so no longer the case that you should only be able to do this with MySQL.

Thoughts?

**Comment by frogcjn** [comment]
https://github.com/sequelize/sequelize/pull/6325
Someone already has been working on this. But there are many bugs.
I even transfered my database from Postgres to MySQL.

**Comment by contra** [comment]
Ah didn't come up in the search, I'll close this.
