### ISSUE TITLE
private database field Instance? Only allow a VIRTUAL property to read/write it?

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6447]
can sequalize make database field private with Instance? Only allow an VIRTUAL property to read/write it?

**Comment by felixfbecker** [comment]
You could use the Javascript convention of prefixing the attribute with an underscore but keeping the column name by setting the field option

**Comment by janmeier** [comment]
Theres nothing built in, but have a look at https://github.com/mickhansen/ssacl-attribute-roles

**Comment by frogcjn** [comment]
@felixfbecker , @janmeier Thanks.
