### ISSUE TITLE
allowNull: false and defaultValue: Sequelize.NOW not populating field with default value.

### ISSUE THREAD

**Issue by patrickod** [sequelize/sequelize#645]
Noticed this issue with `1.7.0-alpha1` this morning.

I have a model with a timestamp field which is defined as follows 

``` js
started_at: {
  type: DataTypes.DATE,
  allowNull: false,
  defaultValue: Sequelize.NOW
},
```

Using a build statement with a hash that doesn't set the started_at timestamp field like so

``` js
Model.build({foo: "bar"}).save()
```

doesn't set the `started_at` field to a current timestamp, instead leaving it null.

Expected behavior: That started_at contain a timestamp from the record's creation
Actual behavior: started_at is left as null.

Reverting to `1.6.0` fixed the issue for me. This seems to be a regression in later alpha versions

**Comment by HarshD-infynno** [comment]
hello all, I am facing an issue with the default date. 
I want to set defaultValue= NULL 
`` date: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: NULL.
    } ``
