### ISSUE TITLE
auto pass transaction when nesting didn't work

### ISSUE THREAD

**Issue by Normanlife** [sequelize/sequelize#6450]
```js
var cls = require('continuation-local-storage')
var namespace = cls.createNamespace('lalala')
Sequelize.cls = namespace

test.only('事务嵌套', async t => {

  return sequelize.transaction({autocommit: true},async function (tt) {

    let prize = await Prize.create({title:'xxx'})

    await t1(prize.id)

  });

})

async function t1(prizeId) {

  return sequelize.transaction({autocommit: true},async function (t2) {

    let prize =  await Prize.findOne({where:{id:prizeId}})

    console.info(prize.title)

    return prize

  });

}
```

 TypeError: Cannot read property 'title' of null

and:
console.log(prize) === null

I already check the database and method are working

**Comment by janmeier** [comment]
Where does it break? (look at the logs to see which transaction each query is executed on)

Does it work if you remove the second transaction?

**Comment by overlookmotel** [comment]
What transpiler are you using to convert async/await to generators/yield? And can you please post the code that it's transpiled to?

I think this is likely related to the transpiled code not using a Promise implementation which has proper CLS support.
