### ISSUE TITLE
Could you please cut a new pre-release (4.0.0-1) and publish to NPM?

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#6465]
My team at work are trying to switch our applications over to v4.X.X.

v4.0.0-0 is missing a couple of the critical fixes that are at the HEAD of master.

Could you please cut a new pre-release (4.0.0-1) and publish to NPM?

We are stuck without this...

**Comment by janmeier** [comment]
Sure thing! https://github.com/sequelize/sequelize/releases/tag/v4.0.0-1

**Comment by nareynolds** [comment]
Thank you! You all rock!
