### ISSUE TITLE
Lock down dependency versions for releases

### ISSUE THREAD

**Issue by afloyd** [sequelize/sequelize#6467]
For tagged/release versions it may be helpful to "lock down" the dependency package versions? Yesterday I had an issue it took me a bit to figure out after trying to deploy, due to the [`terraformer-wkt-parser`](https://github.com/Esri/terraformer-wkt-parser/commits/master) getting a update from `1.1.0` to `1.1.1` and sequelize having a dependency of `"terraformer-wkt-parser": "^1.1.0",`.

So even though all my tests/etc had previously passed with `terraformer-wkt-parser 1.1.0`, when deploying to a new server it got the latest via NPM and version `terraformer-wkt-parser 1.1.1` had an error (causing the entire node server to not be able to boot). Thankfully within a couple hours their error was found and resolved with `1.1.2`, but it leaves the potential for an unknown build state from deployment to deployment unless I statically include the `node_modules` folder in our repository when tests are known to pass.

So the error wasn't specific to either my own app, or sequelize... But rather the integration of sequelize and it's dependencies. Obviously I know you cannot easily control nested dependencies with NPM, but at least at the top level it may be helpful

__Sequelize version:__ 4.0.0-0

**Comment by felixfbecker** [comment]
The issue was a breaking change in a minor release of a dependency. If you want to lock down your versions for all your developers / production environments you should use npm-shrinkwrap - but Sequelize will not lock down the deps in package.json because it would prevent all users from getting bug fixes in dependencies, even if they manually `npm update`.

**Comment by janmeier** [comment]
Plus, shrinkwrapping (which is the only way to completely lock down dependencies and sub-dependencies) is not considered good practice for public modules, since it does not work for people who host their own npm

**Comment by janmeier** [comment]
I do definitely recommend shrinkwrapping your own module though. Or, like we do at snaplytics, build a static docker container with the dependencies inside.

**Comment by afloyd** [comment]
Good point, somehow I had totally forgotten about shrinkwrap... And yes
with Docker that's definitely an easy way to go!
