### ISSUE TITLE
DECIAL as number

### ISSUE THREAD

**Issue by jvbianchi** [sequelize/sequelize#6468]
## What you are doing?
sequelize is converting DECIMAL into string instead of number.

```js
var Product = sequelize.define('product', {
  price: {
    type: Sequelize.DECIMAL
  },
  name: {
    type: Sequelize.STRING
  }
});

Product.sync({force: true}).then(() => {
  // Table created
  return Product.create({
    name: 'test product',
    price: 10.65
  })
    .then((result) => {
      console.log('result.name', typeof result.name); // returns string => rigth
      console.log('result.price', typeof result.price);  // returns string => should be NUMBER
    })
    ;
});
```

## What do you expect to happen?
the price field should have a typeof  number

## What is actually happening?
the price field has a typeof string

__Dialect:__ postgres
__Database version:__ 9.5
__Sequelize version:__ 3.24.1

**Comment by sushantdhiman** [comment]
JS number can't handle full precision of Postgres Decimal type. What you want will actually result in loss of precision.  See https://github.com/sequelize/sequelize/issues/4893 (issue) and https://github.com/sequelize/sequelize/pull/5860 (fix)

If you still want them as numbers, just pass them through `parseFloat`, but it will result in loss of precision :)

**Comment by felixfbecker** [comment]
If you want to keep precision and still do math look at https://github.com/MikeMcl/bignumber.js/
