### ISSUE TITLE
limit in findAndCountAll with "where" in  include doesn't work (MSSQL)

### ISSUE THREAD

**Issue by Lichtjaeger** [sequelize/sequelize#6471]
## What you are doing?

I want a pagination for an user table.

``` js
const Abteilung = GBNallgemein.import(__dirname + '/abteilungen.js')
const User = GBNallgemein.import(__dirname + '/benutzer.js')
const Rolle = GBNallgemein.import(__dirname + '/rolle.js')

User.belongsTo(Abteilung, { foreignKey: 'AbteilungID' })
Abteilung.hasMany(User, { foreignKey: 'AbteilungID' })

User.belongsToMany(Rolle, {
    through: 'tblBenutzerRollen',
    foreignKey: 'BenutzerID',
    otherKey: 'RollenID'
})
Rolle.belongsToMany(User, {
    through: 'tblBenutzerRollen',
    foreignKey: 'RollenID',
    otherKey: 'BenutzerID'
})

User.findAndCountAll({
    attributes: [
        'ID',
        'NK',
        'Name',
        'Vorname',
        ['Loginname', 'username'],
        ['EMail', 'mail'],
        'AbteilungID'
    ],
    where: {
        Vorname: { $like: `%e%` },
        Name: { $like: `%e%` },
    },
    include: [
        {
            model: Abteilung,
            attributes: ['ID', 'Name'],
            where: undefined
        }, {
            model: Rolle,
            attributes: ['ID', 'Rollenname'],
            where: {
                Rollenname: { $like: `%Berat%` }
            }
        }
    ],
    limit: 5,
    offset: 0,
    order: [
        ['Name', 'ASC'],
        ['Vorname', 'ASC']
    ]
})
```
## What do you expect to happen?

The result should be an object in the form:

``` js
{
    count: 'Number with the count',
    rows: 'Array with lenght of the limit or count (if offset is 0)'
}
```
## What is actually happening?

The Array was empty but 19 results are counted:

``` js
{
    count: 19,
    rows: []
}
```

_Output, either JSON or SQL_

Executing (default): SELECT count(DISTINCT([benutzer].[ID])) AS [count] FROM [tblBenutzer] AS [benutzer] INNER JOIN ([tblBenutzerRollen] AS [rollen.tblBenutzerRollen] INNER JOIN [tblRollen] AS [rollen] ON [rollen].[ID] = [rollen.tblBenutzerRollen].[RollenID]) ON [benutzer].[ID] = [rollen.tblBenutzerRollen].[BenutzerID] AND [rollen].[Rollenname] LIKE N'%Berat%' WHERE [benutzer].[Vorname] LIKE N'%e%' AND [benutzer].[Name] LIKE N'%e%';

Executing (default): SELECT [benutzer].*, [abteilung].[ID] AS [abteilung.ID], [abteilung].[Name] AS [abteilung.Name], [rollen].[ID] AS [rollen.ID], [rollen].[Rollenname] AS [rollen.Rollenname], [rollen.tblBenutzerRollen].[BenutzerID] AS [rollen.tblBenutzerRollen.BenutzerID], [rollen.tblBenutzerRollen].[RollenID] AS [rollen.tblBenutzerRollen.RollenID] FROM (SELECT TOP 5 [benutzer].[ID], [benutzer].[NK], [benutzer].[Name], [benutzer].[Vorname], [benutzer].[Loginname] AS [username], [benutzer].[EMail] AS [mail], [benutzer].[AbteilungID] FROM [tblBenutzer] AS [benutzer] WHERE [benutzer].[Vorname] LIKE N'%e%' AND [benutzer].[Name] LIKE N'%e%' AND ( SELECT TOP 1 [tblBenutzerRollen].[BenutzerID] FROM [tblBenutzerRollen] AS [tblBenutzerRollen] INNER JOIN [tblRollen] AS [rolle] ON [tblBenutzerRollen].[RollenID] = [rolle].[ID] WHERE ([benutzer].[ID] = [tblBenutzerRollen].[BenutzerID]) ) IS NOT NULL ORDER BY [benutzer].[Name] ASC, [benutzer].[Vorname] ASC) AS [benutzer] LEFT OUTER JOIN [tblAbteilungen] AS [abteilung] ON [benutzer].[AbteilungID] = [abteilung].[ID] INNER JOIN ([tblBenutzerRollen] AS [rollen.tblBenutzerRollen] INNER JOIN [tblRollen] AS [rollen] ON [rollen].[ID] = [rollen.tblBenutzerRollen].[RollenID]) ON [benutzer].[ID] = [rollen.tblBenutzerRollen].[BenutzerID] AND [rollen].[Rollenname] LIKE N'%Berat%' ORDER BY [benutzer].[Name] ASC, [benutzer].[Vorname] ASC;

__Dialect: mssql
__Database version: 10.50.1600.1 (SQL2008R2)
__Sequelize version: 3.24.1

**Comment by Lichtjaeger** [comment]
PS: offset doesn't work with order

**Comment by SmaranNA** [comment]
Anyone looking into this? Facing a similar issue in my project.

**Comment by syadykin** [comment]
I have same issue in my project. Removing limit from query produces working query.

**Comment by CbCaio** [comment]
I'm having the same problem here, still trying to figure out a solution, please if anyone find out how to solve it please share with us ;D
