### ISSUE TITLE
MySQL created instance has a null id field. 

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6474]
MySQL created instance has a null id field.
Though the instance is in the database and has an id.

version 4.0.0-0
version 4.0.0-1

**Comment by sushantdhiman** [comment]
# #
Please provide a SSCCE ( [What is SSCCE ?](http://sscce.org), [How to create one in Sequelize ?](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

**Comment by frogcjn** [comment]
let books = await Book.bulkCreate(attributes)

**Comment by frogcjn** [comment]
It has a bigInteger serial id filed

**Comment by frogcjn** [comment]
mysql and mysql2 will return a result of ResultSetHeader
but sequelize cannot correctly handle this in`formatResults`

**Comment by frogcjn** [comment]
https://github.com/sequelize/sequelize/pull/6475
I've made a PR for this issue.
