### ISSUE TITLE
Include paranoid models via association

### ISSUE THREAD

**Issue by guidsen** [sequelize/sequelize#6480]
I'm trying to retrieve all the `user` models (including the paranoid models) associated to the `network`. I couldn't find a way of doing this.

I was thinking of something like this:

```
return network.getUsers({
  paranoid: false,
});
```

I've tried this as well without success.

```
return Network.findById(networkId, {
  include: [{
    model: User,
    paranoid: false,
  }]
});
```

**Comment by felixfbecker** [comment]
Hm this should be supported. But try
```js
network.getUsers({
  where: {
    deletedAt: {
      $or: [ null, {  $not: null } ]
    }
  }
})
```

**Comment by guidsen** [comment]
The problem is that I've added `paranoid: true` to the pivot model.

**Comment by felixfbecker** [comment]
Try passing the `where` clause I posted inside `include: { model: User, where: ... }`

**Comment by guidsen** [comment]
That's not possible because I'm already doing `.getUsers()`

**Comment by caioflores** [comment]
This is still not possible?
