### ISSUE TITLE
Getting association identificator without SQL query?

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6482]
Hello! 

Let suppose simple Parent - Child relation 
```
Parent.hasMany(Child);
Child.belongsTo(Parent);
```

Now let's 

`child= Child.findById(1);  //SELECT "id", "parent_id" FROM "Model" WHERE "Model"."id" = 1;`

And the question is how to get child.parent.id (parent_id column) from js code without extra SQL? If i do 

`child.getParent().id  `

this will produce addition SQL which is not necessary for getting parent.id

Thanks

**Comment by felixfbecker** [comment]
`child` should have `parentId` set (or `parent_id`, not sure, may depend on how you defined your model). Additionally, you can do
```js
Child.findById(1, { include:  [ Child.associations.Parent ] });
```

**Comment by alexey2baranov** [comment]
child.parent_id works
