### ISSUE TITLE
Get attributes with datatype

### ISSUE THREAD

**Issue by katana2w** [sequelize/sequelize#6484]
Hi!

Im using Sequelize and MySQL. For checking changes in Model I just want to get all attributes and their datatype by Model. How I can do it? findAll returns data from DB - but i need only column names and types.

Thank you.

**Comment by felixfbecker** [comment]
@katana2w The `QueryInterface` has a method `describeTable` that should do what you are after. You can get the table name of a model with `Model.getTableName()`.

http://docs.sequelizejs.com/en/v3/docs/migrations/#describetabletablename-options

**Comment by katana2w** [comment]
Yes - its work. But I need attribute from Model, not table. Is it possible?

**Comment by felixfbecker** [comment]
As I told you you can get the table name from the model and then pass it to describeTable.

**Comment by sushantdhiman** [comment]
@katana2w `Model.rawAttributes` should work

**Comment by katana2w** [comment]
Thank you for quick answer. If I create model const Car = client.define('Car', MODEL_ATTRIBUTES, MODEL_CONFIGURATION);  => it is Car.rawAttributes? But still nothing (

**Comment by felixfbecker** [comment]
Yes, that should be it. I believe `Car.attributes` should be defined aswell.

**Comment by katana2w** [comment]
.... other variants? Car.attributes didnt work for me (

**Comment by felixfbecker** [comment]
You are probably doing something wrong, at least `Model.rawAttributes` should be defined. What is the output when you `console.log()` your model?

**Comment by katana2w** [comment]
Thank you! You are right. Model was undefined. 
And one more question - can I get type of each attribute from Model.attributes ? I mean now I describe model attributes like that:
const attr_model = {
    field1 : { type : Sequelize.INTEGER , primaryKey : true },
    field2 : Sequelize.INTEGER,
    ........
}

But when I get Model.attribites - no type found here for fields.

**Comment by felixfbecker** [comment]
Have you tried `rawAttributes` aswell? Somewhere the type should be defined.

**Comment by katana2w** [comment]
Tried rawAttributes - the same things

**Comment by felixfbecker** [comment]
What does it look like when you `console.log()`?
