### ISSUE TITLE
Model.destroy() does not take scopes into account when checking presence of where clause

### ISSUE THREAD

**Issue by sj82516** [sequelize/sequelize#6489]
## What you are doing?

I set up scope in my model Items.

``` js
scopes:{
       delete:{
            where:{
                status:false
            }
        }
}
```

When I try to use it in destroy method,it throw error

> Missing where or truncate attribute in the options parameter of model.destroy.

``` js
return Item.scope('delete').destroy();
```

But when I add some condition in destroy method, it works.

``` js
return Item.scope('delete').destroy({where:{name:'卡比獸'}});
```

I trace the log and found out that scope condition was added into SQL as well.

> Executing (default): DELETE FROM `items` WHERE `name` = '卡比獸' AND `status` = false

**Dialect:** mysql 
__Database version: MySQL v5.7
__Sequelize version: 3.24.0

**Comment by sj82516** [comment]
I try update , it failed as well.
```js
return Item.scope('delete').update({name:'卡比獸'});
```
>Missing where attribute in the options parameter passed to update.

However, findAll works well. Scope works as I imagine.
>Executing (default): SELECT `item_id`, `name`, `price`, `onShelfDate`, `status`, `category` FROM `items` AS `items` WHERE `items`.`status` = false;

**Comment by sj82516** [comment]
I try to fill in "where" json object with empty property and it works!
```js
return Item.scope('delete').destroy({where:{}});
```

**Comment by felixfbecker** [comment]
Having a custom `delete` scope is not a use case we thought about - the check inside `destroy()` that checks wether a `where` clause is defined should take scopes into account.

**Comment by sj82516** [comment]
This is different from document.
Do I misunderstand it?
http://sequelize.readthedocs.io/en/v3/docs/scopes/
“*Usage*

Scopes are applied by calling .scope on the model definition, passing the
name of one or more scopes. .scope returns a fully functional model
instance with all the regular
methods: .findAll, .update, .count,.destroy etc. "

2016年8月25日 14:43於 "Felix Becker" <notifications@github.com>寫道：

**Comment by felixfbecker** [comment]
As you can see I labeled it a bug

**Comment by iamjoyce** [comment]
+1

**Comment by iamjochem** [comment]
this looks to affect everything that expects a "where" clause in an options parameters - a missing "where" property is considered an error even when a scope is in affect, an empty "where" porperty does not trigger an error:

```js

var scope  = { foreign_id : 123 }, fields = { status : 'critical' };

// assume Model is a valid instance! and it has a valid scope of "foreign_id"!

Model.scope(scope).update(fields); // Error!
Model.scope(scope).update(fields, { where : {} }); // No Problem!
```
ideally an empty "where" object would be considered the same as a non-existent one (both effectively map to the same empty SQL WHERE clause).

**Comment by iamjochem** [comment]
this is still a thing

**Comment by iamjochem** [comment]
this is still relevant
