### ISSUE TITLE
Sequelize.query not resolving or rejecting.

### ISSUE THREAD

**Issue by ltegman** [sequelize/sequelize#6492]
## What you are doing?
I am using Sequelize within a Hapi webserver. Every time this server receives a post request it will call the following code to create a transaction and then use that transaction to insert a record into the database. This error only occurs when the load on the server causes a call to the following code while all the connections in the pool are already active in a transaction.

```js
sequelize.transaction(options)
    .then((tx) => {
        let setTimeout = 'SET statement_timeout to ' + transactionTimeout + ';';
        this._tx = tx;

        // Set the transaction timeout
        return sequelize.query(setTimeout).then(() => {
            this._log('Beginning transaction id ' + this._tx.id);

            return this._tx;
        });
    })
    .catch(err => {
        this._log('error creating a transaction:', err);
    });
```

## What do you expect to happen?
The promise from the `sequelize.query` call should resolve/reject and I'll see one of the corresponding log statements from the `.then` or `.catch`

## What is actually happening?
The promise from `sequelize.query` never resolves/rejects, preventing the transaction from ever being committed or rolled back.

__Dialect:__ postgres
__Database version:__ 9.3/9.4/9.5
__Sequelize version:__ 3.24.0

**Comment by felixfbecker** [comment]
Have you tried passing the transaction object to `query()`? I also don't see any code for actually commiting or rolling back. You say this only happens when all connections are in a transaction, that would be a logical explanation if your transaction never commits/rolls back.

**Comment by ltegman** [comment]
Of course -- if I open the transactions fast enough and don't pass the transaction into the query I have no more connections left to make that query on. I feel super embarrassed I didn't notice that! Passing it in resolves the error -- thank you so much!
