### ISSUE TITLE
Cannot exclude attributes when creating scope as a function

### ISSUE THREAD

**Issue by SergeyKhval** [sequelize/sequelize#6495]
When trying to exclude attributes in scope I get this error:

``` js
options.attributes.slice is not a function
```

I create a scope like this: 

``` js
accessLevel: (role) => {
  queryObj = {
    attributes: {
      exclude: ['subscriptionKey']
    }
  };

return role  ? queryObj : {};
}
```

And then invoke it like this `{method: ['accessLevel', req.user.role]}`

If I set scope as an obj:

``` js
    scopes: {
      accessLevel: {
        attributes: {
          exclude: ['subscriptionKey']
        }
      }
    }
```

then everything works fine

**Dialect:** postgres 
**Database version:** 9.5
**Sequelize version:** 3.24.0

**Comment by janmeier** [comment]
Should be fixed by https://github.com/sequelize/sequelize/pull/6721
