### ISSUE TITLE
Is support for Oracle in the Cards?

### ISSUE THREAD

**Issue by owendall** [sequelize/sequelize#6497]
I have several use cases. Just checking about the roadmap. Oracle has recently put priority into a node driver...

**Comment by felixfbecker** [comment]
Someone started a PR but it was abandoned: https://github.com/sequelize/sequelize/pull/4586
Afaik none of us plans to implements this as we don't need it ourselves but we would love contributions.

**Comment by sushantdhiman** [comment]
@owendall We would love to add oracle into sequelize. But Its a really big work to implement new dialect. No one from core team have any additional time for that. Someone from community will have to do this contribution, which I think is very rare for task this big :(
