### ISSUE TITLE
MSSQL broken build, lock Node version at 6.3?

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6504]
The broken build is coming from https://github.com/nodejs/node/issues/8127, introduced in 6.4.0.
This will be fixed in Node 6.5 as the fix landed in master, but in the meantime, the constant broken build in every PR is getting annoying. Should we lock the Node version at ^6.3 until 6.5 is out?

**Comment by mickhansen** [comment]
Locking sounds good to me
