### ISSUE TITLE
Sequelize adding ORDER BY to subquery and main query causing ER_BAD_FIELD_ERROR

### ISSUE THREAD

**Issue by jylinman** [sequelize/sequelize#6513]
## What you are doing?

When I add these two scopes, my publishedAt order gets added twice, once to the subquery (which is what i want), and once to the encasing query which causes a ER_BAD_FIELD_ERROR

FIELD_ERROR: Unknown column 'Ticket.published_at' in 'order clause'

If I remove it from the outer query, the query works as expected, so my question is why would it be being added to both queries?

``` js
// Scope 1
published: function() {
 var data = {
   where: {
     status: 'published',
     publishedAt: {
       $lt: models.sequelize.fn('NOW')
     }
   },
   order: [
     ['publishedAt', 'DESC']
   ]
 };

 return data;
},


// Scope 2
decorated: function() {
  var includes = {
    include: [{
      model: models.Asset,
      as: 'FeaturedAsset'
    }, {
      model: models.Category
    }, {
      model: models.User,
      as: 'Author'
    }]
  };

  return includes;
}
```
## What do you expect to happen?

I wanted it to order the inner query
## What is actually happening?

It added the order to both inner and outer query.

``` sql
SELECT ... FROM (
    SELECT ... FROM `tickets` AS `Ticket` WHERE (`Ticket`.`deleted_at` IS NULL AND (`Ticket`.`status` = 'published' AND `Ticket`.`published_at` < NOW() AND `Ticket`.`channel_id` = 3)) 
    ORDER BY `Ticket`.`published_at` DESC LIMIT 0, 6) AS `Ticket` ... 
ORDER BY `Ticket`.`published_at` DESC;
```

**Dialect:** mysql
**Database version:** 5.6
**Sequelize version:** latest

**Comment by lemelon** [comment]
+1

**Comment by lemelon** [comment]
Is there a fast way to solve this issue?

**Comment by Chapurin** [comment]
Is this problem solved?

**Comment by jylinman** [comment]
I haven't encountered this problem in a while and with that codebase so I
believe it's fixed!

**Comment by pauloddr** [comment]
I'm having this issue with Sequelize 4.8.0. Should I open a new issue?

In any case:

I have a `Patient` model with belongs to `User` which has a `full_name` and has many `Address`es.

The error happens when I add `Address` in the query as an `User` include (a nested association):

```javascript
Patient.findAll({
  include: [
    {
      model: User, 
      attributes: ['full_name'],
      include: [ // <-- error happens if I include this
        {
          model: Address,
          attributes: ['city', 'state']
        }
      ]
    }
  ],
  limit: 1,
  offset: 1,
  order: [
    [User, 'full_name']
  ]
})
```

It gives me the following error:

`Error: Unknown column 'user.full_name' in 'order clause'`

The SQL being generated is somehow weird because it's turning the main table (patients) into a subquery, which does not happen if I don't include the nested association:

```SQL
SELECT `patient`.*, 
`user->addresses`.`id` AS `user.addresses.id`, 
`user->addresses`.`city` AS `user.addresses.city`, 
`user->addresses`.`state` AS `user.addresses.state`
FROM ( /* why is this a subquery? */
    SELECT `patient`.`id`, `patient`.`accepted_terms_at`,  
    `patient`.`created_at`, `patient`.`updated_at`, 
    `patient`.`user_id`, `user`.`id` AS `user.id`, 
    `user`.`full_name` AS `user.full_name` 
    FROM `patients` AS `patient` 
    INNER JOIN `users` AS `user` 
      ON `patient`.`user_id` = `user`.`id` 
    ORDER BY `user`.`full_name` LIMIT 1, 1
) AS `patient` 
LEFT OUTER JOIN `addresses` AS `user->addresses` 
  ON `user.id` = `user->addresses`.`user_id` 
ORDER BY `user`.`full_name`
```

If I remove the nested association (`Address`), everything works fine. But I need it and the order clause.

Thanks.

**Comment by LordSuricato** [comment]
I had the same error and solved it using  `subQuery: false`

**Comment by LordSuricato** [comment]
It happens the same to me. I have a relationship "through". When I order the elements in order of added, this error occurs to me. Above all along with limit and offset.

**Comment by husnulhamidiah** [comment]
@LordSuricato did you find the solution, for your problem?

**Comment by EliasSeccom** [comment]
Same problem here! Someone has a solution?

**Comment by Yuiffy** [comment]
Same problem here! Someone has a solution? I only want to add order in the out most query, not in the subquery

**Comment by alemarcha** [comment]
Any news about this?

**Comment by saumya04** [comment]
Any update?

**Comment by antony** [comment]
I have the same issue. It's not valid to add the clause to both queries, so I'm not sure why it's happening. This issue needs to be reopened.

**Comment by BohdanRusinka** [comment]
+1

**Comment by NoMoreViolence** [comment]
+ 1 Help me

**Comment by watch-janick** [comment]
Same issue here, anyone came up with something?

**Comment by matbalazsi** [comment]
does adding `required:true` to either user or address help?

`Patient.findAll({
  include: [
    {
      model: User, 
      attributes: ['full_name'],
      required:true,  // <-- require a user
      include: [ // <-- error happens if I include this
        {
         required:true,  // <-- require the address
          model: Address,
          attributes: ['city', 'state']
        }
      ]
    }
  ],
  limit: 1,
  offset: 1,
  order: [
    [User, 'full_name']
  ]
})`

**Comment by atanudolui** [comment]
For me same issue I have tried with the latest version (5.7.0).

**Comment by psyanite** [comment]
http://docs.sequelizejs.com/manual/querying.html#ordering

**Comment by exos** [comment]
+1

**Comment by rabiaasif** [comment]
+1

**Comment by joacub** [comment]
why this is closed, I have a same issue if this work the order was super fast the differences is just the quotes in the subquery because the alias is not a `table`.column obviously

**Comment by ravog** [comment]
Any solution ?

**Comment by joacub** [comment]
> Any solution ?

yes use in the order this `\`table.columane\``

**Comment by Hwan-seok** [comment]
Any updates until now? it is been 5 years passed since the issue came up

**Comment by KimHyeonGyeom** [comment]
나쁜놈들

**Comment by KimHyeonGyeom** [comment]
Any updates until now? it is been 6 years passed since the issue came up

**Comment by kishan102** [comment]
still an issue on sequelize 6.29, can someone give an update?

**Comment by scerdal** [comment]
I found a workaround for this issue that might work for other people, too. What you do is basically add the problematic column that comes from the associated model as an attribute of the topmost model, and order by the literal value of that column. So going by @pauloddr's example, instead of

```js
Patient.findAll({
  include: [
    {
      model: User, 
      attributes: ['full_name'],
      include: [ // <-- error happens if I include this
        {
          model: Address,
          attributes: ['city', 'state']
        }
      ]
    }
  ],
  limit: 1,
  offset: 1,
  order: [
    [User, 'full_name']
  ]
})
```
We would have:

```js
Patient.findAll({
  include: [
    {
      model: User, 
      attributes: ['full_name'],
      include: [ // <-- error happens if I include this
        {
          model: Address,
          attributes: ['city', 'state']
        }
      ]
    }
  ],
  limit: 1,
  offset: 1,
  attributes: { include: [[sequelize.col('user.full_name', 'full_name')]] },
  order: [sequelize.literal('full_name'), 'asc'],
})
```

**Comment by jhawkins11** [comment]
For those who are still having this issue:
Add `subquery: false` as in the top level of the options object.
The problem being if you set a LIMIT, that value defaults to true and uses a subquery to recreate the table so you're included columns are not in scope.

**Comment by scerdal** [comment]
> For those who are still having this issue: Add `subquery: false` as in the top level of the options object. The problem being if you set a LIMIT, that value defaults to true and uses a subquery to recreate the table so your included columns are not in scope.

the problem with this approach is if you have one to many models associated with your main model in the query, then disabling the subquery and having the LIMIT statement at the same time will incorrectly limit the query according to the associated model, so you will miss some of the records.

**Comment by viveksinghvats** [comment]
Is there any solution available for this, In my case I cannot do SubQuery as false, because I also have to apply the limit.

**Comment by xavierbourretsicotte** [comment]
Hello - is there any solution available or plan on making it available ? We have a limitation as well

**Comment by scerdal** [comment]
> Hello - is there any solution available or plan on making it available ? We have a limitation as well

Please take a look at my previous comment for a work around

> I found a workaround for this issue that might work for other people, too. What you do is basically add the problematic column that comes from the associated model as an attribute of the topmost model, and order by the literal value of that column. So going by @pauloddr's example, instead of
> 
> ```js
> Patient.findAll({
>   include: [
>     {
>       model: User, 
>       attributes: ['full_name'],
>       include: [ // <-- error happens if I include this
>         {
>           model: Address,
>           attributes: ['city', 'state']
>         }
>       ]
>     }
>   ],
>   limit: 1,
>   offset: 1,
>   order: [
>     [User, 'full_name']
>   ]
> })
> ```
> 
> We would have:
> 
> ```js
> Patient.findAll({
>   include: [
>     {
>       model: User, 
>       attributes: ['full_name'],
>       include: [ // <-- error happens if I include this
>         {
>           model: Address,
>           attributes: ['city', 'state']
>         }
>       ]
>     }
>   ],
>   limit: 1,
>   offset: 1,
>   attributes: { include: [[sequelize.col('user.full_name', 'full_name')]] },
>   order: [[sequelize.literal('full_name'), 'asc']],
> })
> ```

**Comment by AKikhaev** [comment]
Seems like It doesn't work in case we have an option minifyAliases: true
