### ISSUE TITLE
bulkCreate does not respect createdAt 'field' (created_at)

### ISSUE THREAD

**Issue by au2** [sequelize/sequelize#6519]
## What you are doing?

module.exports = function (sequelize, DataTypes) {
    const QuestionType = sequelize.define('question_type', {
        name: {
        	type: DataTypes.TEXT
        },
        createdAt: {
            type: DataTypes.DATE,
            field: 'created_at',
        },
        updatedAt: {
            type: DataTypes.DATE,
            field: 'updated_at',
        },
    }, {
        freezeTableName: true,
        createdAt: 'createdAt',
        updatedAt: 'updatedAt'
    });

    return QuestionType;
};

import this model and

QuestionType.bulkCreate([{name: 'name1'}, {name: 'name2'}]);

## What do you expect to happen?

I expect the records to be inserted.

## What is actually happening?

It fails because createdAt 'field' is not respected

Executing (default): INSERT INTO "question_type" ("id","name","createdAt","updatedAt") VALUES (DEFAULT,'name1','2016-08-30 19:03:45.285 +00:00','2016-08-30 19:03:45.285 +00:00'),(DEFAULT,'name2','2016-08-30 19:03:45.285 +00:00','2016-08-30 19:03:45.285 +00:00');

createdAt should in created_at in the query.

QuestionType.create({name: 'name1'}); works so I do not think it is user error.

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.24.1

**Comment by sushantdhiman** [comment]
Its fixed in master https://github.com/sequelize/sequelize/pull/6219 , You are free to port it to `v3`
