### ISSUE TITLE
Sequelize get "where' clause from nowhere

### ISSUE THREAD

**Issue by mich4s** [sequelize/sequelize#6520]
I want to make simple "greater than" query with this code:

`app.get('/api/v1/debtor/signed', function (req, res) {
    Debtor.findAll({
        where: ['group_id > 0']
    }).then(function (result) {
        res.send(result);
    });
});`

I don't know why i get this output in console:
... WHERE `debtors`.`group_id` = `signed`;

Is this bug, or somehow sequelize parse route to get arguments?

I'm using mysql with "sequelize": "^3.24.0" in package.json

I'm very new to nodeJS, so maybe there's something i didn't know.

**Comment by felixfbecker** [comment]
Sequelize does not parse any express parameters. Please show your model definition and the whole query. Also, you recommend you to read https://help.github.com/articles/creating-and-highlighting-code-blocks/ and http://docs.sequelizejs.com/en/v3/docs/querying/#where

**Comment by mich4s** [comment]
Sorry for that late reply. I had crazy day.

`var Debtor = sequelize.define('debtors', {
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        primaryKey: true
    },
    group_id: {
        type: Sequelize.INTEGER
    },
    name: {
        type: Sequelize.STRING
    },
    surname: {
        type: Sequelize.STRING
    },
    born: {
        type: Sequelize.DATE
    },
    address: {
        type: Sequelize.STRING
    },
    city: {
        type: Sequelize.STRING
    },
    phone: {
        type: Sequelize.STRING
    },
    mail: {
        type: Sequelize.STRING
    }
});`

This is model. I know how where works. I have many different queries that works fine. This one is only problem.

And this is my query:
`Executing (default): SELECT `id`, `group_id`, `name`, `surname`, `born`, `address`, `city`, `phone`, `mail`, `createdAt`, `updatedAt` FROM `debtors` AS `debtors` WHERE `debtors`.`group_id` = 'signed';`

**Comment by felixfbecker** [comment]
Have you tried
```js
Debtor.findAll({
  where: {
    group_id: { $gt: 0 }
  }
})
```
?

**Comment by mich4s** [comment]
Yes, same query is builded. I don't know why is that, but if i change last url part i have the same parameter in my query.

**Comment by felixfbecker** [comment]
So if you change _signed_ to _whatever_ the query will end with `WHERE WHERE `debtors`.`group_id` = 'whatever'`?!

**Comment by mich4s** [comment]
Yep for example:
```
Executing (default): SELECT `id`, `group_id`, `name`, `surname`, `born`, `address`, `city`, `phone`, `mail`, `createdAt`, `updatedAt` FROM `debtors` AS `debtors` WHERE `debtors`.`group_id` = 'signedgittest';
GET /api/v1/debtors/signedgittest 304 172.681 ms - -
```

**Comment by felixfbecker** [comment]
weird, never seen something like this before. Logically this cannot be possible.

**Comment by mich4s** [comment]
I know... I'll try later maybe with post. I had some time ago problem when POST ajax with url: 'example/' was sending GET, but with 'example' POST...

**Comment by felixfbecker** [comment]
Is this really 100% the exact code you are using?

**Comment by mich4s** [comment]
Yes, i have no point to lie here ;D I want this to works. I like simplicity of node/JS, but this is kinda painfull. At last i can make raw query, but i found this bug interesting.

**Comment by janmeier** [comment]
Please read up on how to create a [SSCCE](HTTP://SSCCE.ORG/) 

We cannot help you debug the issue from small snippets of code, we need a self-contained example so we can actually replicate the issue.

Trying to create one also often leads you to discover the problem yourself, when you try to cut the code down to the bare minimum required to replicate.

**Comment by mich4s** [comment]
Ok, I've been few days out of PC. I was analising my code for a while. And there was a letter missing... So sorry for that.

**Comment by sushantdhiman** [comment]
Great
