### ISSUE TITLE
multiply in sequalize function with sequalize literal

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#6521]
i want multiplication with two columns of sequalize literal
   include: [
                       {
                           model: hp_unit_type,
                          /* attributes:[[Sequelize.fn('SUM',Sequelize.literal("`hp_unit_detail.hp_unit_type`.`unit_type_name`"),'*',Sequelize.literal("`hp_unit_detail`.`no_toilet_available`"),'T'),'UnitName']],
                       */
                     attributes:[[Sequelize.fn('ABS',Sequelize.literal("`hp_unit_detail`.`no_toilet_available`"),'*',Sequelize.literal("`hp_unit_detail`.`no_toilet_available`")),'UnitName']],
                           required:true
                       }
]

__Dialect:__ mysql 
__Database version:__ mysql
__Sequelize version:__ 2.0.0

**Comment by janmeier** [comment]
What do you want the query to look like? Which attributes do you need to multiple? 

`literal` allows you to write whatever you want, and it will be inserted into the query exactly like that, so you can simply write `x * y`

**Comment by SIMHACHALAM1001** [comment]
ya got it. thanq
