### ISSUE TITLE
Getting `Error: Please install 'pg' module manually` when trying to use native/SSL

### ISSUE THREAD

**Issue by OKNoah** [sequelize/sequelize#6522]
When doing

```
const sql = new Sequelize(process.env.DATABASE_URL, {
  native: true,
  ssl: true
});
```

I get the error `Error: Please install 'pg' module manually`, this is with the following versions of `pg` and `libpq` installed.

```
"libpq": "^1.8.5",
"pg": "^4.5.6",
```

Is there another package that is meant by `pg`?

**Comment by felixfbecker** [comment]
Do you have `pg-native` installed too?

**Comment by OKNoah** [comment]
@felixfbecker Nope, that worked.
