### ISSUE TITLE
When will  4.0 be stable?

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6527]
We are starting new project with sequelize. So we would like to know when you will finally release 4.0 . Maybe we should get a pause and wait for 4.0 if this will very soon.

**Comment by janmeier** [comment]
There's still plenty of open issues we'd like to land https://github.com/sequelize/sequelize/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0, so probably not soon

**Comment by felixfbecker** [comment]
@alexey2baranov I would also say it will take some more months, because we have features that we want to implement for v4 that are _slightly_ breaking changes. Most of the v4 roadmap is just enabling new syntax though, and most of the old syntax is still supported.
