### ISSUE TITLE
model.build().setRelation() generates wrong sql

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6528]
this construction

model.build().setRelation(target) generates very strange SQL

> INSERT INTO "model_table" ("target_id","updated_at","created_at") VALUES ('1','2016-09-01 11:17:31.572 +00:00','2016-09-01 11:17:31.572 +00:00');

**Comment by janmeier** [comment]
Why is this strange? `build` only creates a javascript instance, not an actual row in the DB. When you call `setRelation`, the instance is saved

**Comment by mickhansen** [comment]
If `setRelation` is a belongsTo relationship you can use `{save: false}`. Otherwise your call is close to incorrect

**Comment by alexey2baranov** [comment]
@janmeier because it does not insert model.id

**Comment by alexey2baranov** [comment]
@mickhansen    
{save: false} where should i set this parameter ?
