### ISSUE TITLE
"val.replace is not a function" very hard to debug

### ISSUE THREAD

**Issue by clivend** [sequelize/sequelize#6530]
Hello everyone and thanks for sequelize :) Here I try to describe a bug(?) I encountered lately.
## What you are doing?

MODEL

``` js
var session = sequelize.define("session", {
    userId: {
      type: DataTypes.BIGINT(11),
      allowNull: false,
      unique: false
    },
    guid: {
      type: DataTypes.STRING(255),
      allowNull: false,
      unique: true,
      primaryKey: true
    },
    json: {
      type: DataTypes.TEXT,//I store a JSON string in here
      allowNull: true
    },
    completed: {
      type: DataTypes.BOOLEAN,
      allowNull: true
    }
  }, {
    indexes: [
      {
        unique: true,
        fields: ['guid']
      },
      {
        unique: false,
        fields: ['userId']
      }
    ],
    charset: 'utf8',
    collate: 'utf8_general_ci',
    paranoid: true
  });
```

CONTROLLER (hapi.js handler)

``` js
let where = request.auth.credentials.scope === 'superuser' ? {} : {
        where: {
          userId: request.auth.credentials.id
        }
      };

Session
            .findAll(where); //here it stops execution and I get server error 400 with "val.replace is not a function"
```

I arrived to this conclusion filling the code with node debugger. I managed to work around this using raw queries.

``` js
let whereRaw = request.auth.credentials.scope === 'superuser' ? ' WHERE deletedAt IS NULL' : ' WHERE userId=\'' + request.auth.credentials.id + '\'  AND deletedAt IS NULL';

app.models.sequelize
        .query('SELECT * FROM sessions' + whereRaw, { type: Sequelize.QueryTypes.SELECT })
```

Dialect: mysql, node package mysql 2.11.1

Node v5.11.0

Database version: MySQL: mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using readline 5.1

Sequelize version:3.24.1

Need more? let me know :)

Possible related #5292 #5082 #5185

**Comment by nullivex** [comment]
I was able to Reproduce this very simply.

```js
var bar
AnyModel.find({where: {bar: boo}})
```

Just passing undefined or anything not Type String will yield replace not being a function. The big problem is the callstack not making it obvious where this is happening.

To me it would be nice to have it simply dump whatever environmental information  that is available like the options object passed to the call so it might be obvious which call is passing an undefined value.

**Comment by felixfbecker** [comment]
Before opening an issue, please next time look if the bug may already be fixed.
https://github.com/sequelize/sequelize/blob/c88bc257647edca87a8a8132fd15e94e6af64177/lib/sql-string.js#L58
