### ISSUE TITLE
Custom null validation errors in v4 don't seem to work

### ISSUE THREAD

**Issue by leebenson** [sequelize/sequelize#6531]
I can't seem to get custom null validation errors working in v4. (This may not be exclusive to v4; I haven't tried it in other versions).

I've tried several field definitions, including:

``` javascript
{
  email: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      notNull: {
        msg: 'Please enter your e-mail',
      },
      isEmail: {
        msg: 'Please enter a valid e-mail'
      }
    },
  },
}
```

... and variants, including setting `allowNull: true` and custom functions inside of `validate`.

**Expected:**

Using this set-up...

``` javascript
const user = new User;
user.email = args.email // null value fed in from a form
return user.save()
```

... or this...

``` javascript
return (new User(args)).save()
```

... I'm expecting to throw `Sequelize.ValidationError` with the following message:

> Please enter your e-mail

**Actual:**

This is the actual error I'm getting back:

> email cannot be null

**Workaround:**

Setting the field to any non-null value works.

``` javascript
const user = new User({ email: ''});
return user.save(); // now it'll throw the correct error
```

The issue with this approach is that I specifically need to set every value to be non-null before `validate` rules kick-in, which means adding a middleware step before processing form input.

It could also mean (not yet tested) that fields that use non-strings need to be initialised with a value other than `''` to work, which is a further workaround.

**Comment by felixfbecker** [comment]
Have you tried
```js
allowNull: false,
validate: {
  notNull(value) {
    if (value == null) {
      throw new Error('please enter your e-mail')
    }
  }
}
```
?

**Comment by leebenson** [comment]
Same error:

> email cannot be null

**Comment by felixfbecker** [comment]
Could you provide an sscce? https://github.com/sequelize/sequelize/blob/master/sscce_template.js

**Comment by jifeon** [comment]
Using `notNull` as in example above I get an error:

```
Validation error: Warning "notNull" validation has been deprecated in favor of Schema based "allowNull"
SequelizeBaseError: null
```

How can I set custom message for `allowNull`? Should I use validate method of a model?

**Comment by jifeon** [comment]
Oh sorry, just notices that PR is for 4th version

**Comment by sultan99** [comment]
@jifeon Did you find how to set custom message for allowNull?

**Comment by jifeon** [comment]
@sultan99 no, postponed until migration to v4
