### ISSUE TITLE
WARNING: PostgreSQL does not support BIGINT with options. Plain `BIGINT` will be used instead.

### ISSUE THREAD

**Issue by hezhongfeng** [sequelize/sequelize#6533]
when I  used the field's type as "BIGINT" or "INTEGER"
It will show this warning
```
>> WARNING: PostgreSQL does not support BIGINT with options. Plain `BIGINT` will be used instead.
>> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
```
I will use a type to store scores.
And there types has warning both.
I need to ignore it?

**Comment by mickhansen** [comment]
Can you post your actual code? Looks like you are using a modifier for the data type.

**Comment by hezhongfeng** [comment]
@mickhansen 
Yes
I tried `INTEGER.UNSIGNED` ,warring too
```
	integration: {
		type: Sequelize.BIGINT.UNSIGNED,
		allowNull: false,
		defaultValue: 0,
		comment: "用户积分"
	}
```
I tried use`Sequelize.INTEGER` ,there is no warring.
So,I will use `Sequelize.INTEGER`?

**Comment by felixfbecker** [comment]
@hezhongfeng Afaik and as the error message says, Postgres doesn't have `UNSIGNED BIGINT`. You can use `BIGINT`, just not with `UNSIGNED`.

**Comment by hezhongfeng** [comment]
@felixfbecker 
Thank you.
I will just use `INTEGER`
