### ISSUE TITLE
Lost ability to GREP tests

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#6534]

**Comment by felixfbecker** [comment]
Sorry, I had to do this because it was using the linux-specific env var syntax. It was only implemented in integration tests anyway. I guess you have do add it back locally if you need it, couldn't come up with a cross platform solution

**Comment by sushantdhiman** [comment]
But its very useful for local development :(

**Comment by felixfbecker** [comment]
If you have any idea how to make it work cross-platform... we could refactor all the npm scripts to a js file that uses mocha's programmatic API

**Comment by janmeier** [comment]
I think `npm run test -- -g WHATEVER` should work - Anything after `--` is passed on to the script

**Comment by felixfbecker** [comment]
nice, didnt know that!

**Comment by sushantdhiman** [comment]
Yep , confirmed `-- -g WHATEVER` works. Thanks @janmeier , cool trick :+1:
