### ISSUE TITLE
Raw queries Model conversion

### ISSUE THREAD

**Issue by jdnichollsc** [sequelize/sequelize#6536]
## What you are doing?
I'm using raw queries to get data between some tables.

```js

//models/order.js
module.exports = function (sequelize, DataTypes) {

    var Order = sequelize.define('order', {
        orderDescription: {
            type: DataTypes.STRING(250),
            allowNull: false,
            field: "order_description"
        },        
        siteId: {
            type:DataTypes.STRING(12),
            allowNull: false,
            field: "site_id"
        }
    },
    {
        timestamps: true,
        underscored: true,
        freezeTableName: true
    });

    return Order;
};

//Woks perfect
models.order.findOne({ where: where }).then(function(orderDB){
    /*
    order.toJSON() === {
       orderDescription: "my order",
       siteId: "1234"
    }
    */
});

//******* ERROR ******* Getting orders using Raw queries
sequelize.query('SELECT * FROM orders...', { 
   type: models.sequelize.QueryTypes.SELECT,
   model: models.order,
   raw: true
 }).then(function(orders){

  /* 
  orders === [
      {
         order_description: "my order", <== ERROR PROPERTY NAME
         site_id : "1234"
      }
  ]
  */
})
```

## What do you expect to happen?
Convert the query respecting the model using the property names from the Sequelize Model.

## What is actually happening?
The query return the column names from the database instead of property names from the Sequelize Model.

__Dialect:__ postgres
__Database version:__ 9.5.3
__Sequelize version:__ 3.23.6

**Comment by krutijan1** [comment]
+1

**Comment by felixfbecker** [comment]
That's simply how raw queries work, they return the result set. You can map it to a model, but not with includes, and you need to alias the column names to the correct properties. Sequelize does this internally as well.

**Comment by felixfbecker** [comment]
That being said, better support for raw queries is something we would like to do, so any contributions in that area are welcome

**Comment by janmeier** [comment]
See https://github.com/sequelize/sequelize/issues/5685

**Comment by foisonocean** [comment]
@janmeier Any news?
And why #5685 is closed now?
