### ISSUE TITLE
RESTART IDENTITY does not work with CASCASE

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6537]
https://www.postgresql.org/docs/9.1/static/sql-truncate.html
The syntax of TRUNCATE is:
```sql
TRUNCATE [ TABLE ] [ ONLY ] name [ * ] [, ... ]
    [ RESTART IDENTITY | CONTINUE IDENTITY ] [ CASCADE | RESTRICT ]
```
When doing
```js
sequelize.truncate({restartIdentity: true, cascade: true})
```
the SQL executed is
```sql
TRUNCATE "Table" CASCADE RESTART IDENTITY
```
which leads to an SQL syntax error.
It should be 
```sql
TRUNCATE "Table" RESTART IDENTITY CASCADE
```

@gouroujo Mentioning you as this was your PR https://github.com/sequelize/sequelize/pull/6415. Maybe you are able to fix this?

**Comment by sushantdhiman** [comment]
Merged in https://github.com/sequelize/sequelize/commit/f13eb40efa69d2b491d649d3fb1a7922bdbeb008
