### ISSUE TITLE
how to sync Sequelize model with pre defined table

### ISSUE THREAD

**Issue by hasan3ysf** [sequelize/sequelize#6543]
I understand the below code is creating `NEW` table in the data base and call it `User` then add data to it.
I've the table `User` already existing in my data, I just want to do a model to sync with with this table, how can I do it?

    var Sequelize = require('sequelize');
    var sequelize = new Sequelize('database', 'username', 'password');

    var User = sequelize.define('user', {
        username: Sequelize.STRING,
        birthday: Sequelize.DATE
    });

    sequelize.sync().then(function() {
       return User.create({
           username: 'janedoe',
           birthday: new Date(1980, 6, 20)
        });
    }).then(function(jane) {
           console.log(jane.get({
           plain: true
        }));
    });

**Comment by felixfbecker** [comment]
What do you mean by "syncing the model to the table"? Running `sync({force: true})` will drop the table first, but you will lose all your data. If you want to keep your data, but only change the schema, you need to write a migration.
