### ISSUE TITLE
CLS lost with native Promises in 4.0?

### ISSUE THREAD

**Issue by leebenson** [sequelize/sequelize#6544]
In v4, does CLS work with native Promises, or is `Sequelize.Promise` currently required?

Instrumenting the usual way:

```javascript
import Sequelize from 'sequelize';
import cls from 'continuation-local-storage';
Sequelize.cls = cls.createNamespace('transactions');
```

... this simple example is _not_ executing in a transaction:

```javascript
this.sequelize.transaction().then(t => {
  return (new ModelName({ some: 'data'})).save();
});
```

I get the following output:

> server_1         | Executing (df667891-2dee-4d1f-b3b1-8c276e5f69d7): START TRANSACTION;
server_1         | Executing (default): INSERT INTO `tableName` (`id`,createdAt`,`updatedAt`) VALUES ('fa9f08ce-48cf-4e2b-b3e1-2127fd6eb9d5', // cut for brevity

Note:

- The insert is being performed on the default connection (i.e not inside a transaction)
- No implicit commit/rollback - the transaction is left open

I can fix the above by passing in an explicit `{ transaction }`, but then I also need to use `try/catch` block and wire up `t.commit()` or `t.rollback()` manually.

**Comment by leebenson** [comment]
Also note that...

```javascript
this.sequelize.transaction().then(t => {
  throw new Error("will never rollback");
  return (new ModelName({ some: 'data'})).save();
});
```

... doesn't implicitly run `.rollback()`

**Comment by janmeier** [comment]
You need to pass a callback to `transaction` to get a managed (automagically commit / rollback) and CLS http://docs.sequelizejs.com/en/v3/docs/transactions/#managed-transaction-auto-callback

That said, I doubt if CLS will work with native promises

**Comment by leebenson** [comment]
ah, that was my bad - I was running it in the `.then` block instead of the callback.

It actually does work with native 👍

**Comment by janmeier** [comment]
Sweet beans! There's no guarantee that it works 100% in all cases though - Not before we can integrate @overlookmotel's major rewrite of CLS bluebird https://github.com/TimBeyer/cls-bluebird/pull/15/files

**Comment by leebenson** [comment]
thanks for the heads-up @janmeier - I'll keep a close eye.

At first pass, even async/await (with a polyfill) seems to working pretty nicely...

```javascript
return this.sequelize.transaction(async t => {
  const model = new Model1({
    some: 'data',
  });

  await model.save();
  await model2.addDependentModelName(model1);

  return model1;
});
```

Output:

> server_1         | Executing (b2880e89-9f35-442d-81ad-677cdc8577b7): START TRANSACTION;
server_1         | Executing (b2880e89-9f35-442d-81ad-677cdc8577b7): INSERT INTO `table1` (`id`,`createdAt`,`updatedAt`) VALUES ('7c549332-4e30-4c71-a099-da35666b079b',2016-09-05 07:16:38','2016-09-05 07:16:38');
server_1         | Executing (b2880e89-9f35-442d-81ad-677cdc8577b7): UPDATE `table2` SET `UserId`='8855f935-4e04-4e9b-92e9-f7e67daa5287',`updatedAt`='2016-09-05 07:16:38' WHERE `id` IN ('7c549332-4e30-4c71-a099-da35666b079b')
server_1         | Executing (b2880e89-9f35-442d-81ad-677cdc8577b7): COMMIT;

... which is frickin' _sweet_

**Comment by overlookmotel** [comment]
I'm not sure if you can rely on CLS passing correctly with async/await. It all depends on what the polyfill converts it to.

Often with CLS, you test an example like that and it all seems fine, but then once you have multiple async "threads" of execution in flight at the same time it can go pear-shaped, with the CLS context getting mixed up between the "threads".

Also, native promises do claim to support CLS. But it works slightly differently from my CLS bluebird patch, and also I don't know how thoroughly it's tested.

I'd advise using `cls-bluebird` (once the new version is released, probably in next couple of days) and do this:

```js
return this.sequelize.transaction( Bluebird.coroutine( t => {
  const model = new Model1({
    some: 'data',
  });

  yield model.save();
  yield model2.addDependentModelName(model1);

  return model1;
}));
```

I can pretty much guarantee that'll work 100%.

**Comment by janmeier** [comment]
For anyone wanting to keep with the sweet ES7 syntax, https://www.npmjs.com/package/babel-plugin-transform-async-to-module-method can transform it to bluebird

**Comment by leebenson** [comment]
Thanks @overlookmotel - good to know.

The polyfill I'm currently using is [babel-plugin-transform-async-to-generator](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-async-to-generator), which transpiles down to something like this:

```javascript
return _this.sequelize.transaction(_asyncToGenerator(function* () {
  const model = new Model1({
    some: 'data',
  });

  yield model2.save();
  yield model2.addRecall(model1);

  return recall;
}));
```

`_asyncToGenerator` is relatively simple:

```javascript
function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { return step("next", value); }, function (err) { return step("throw", err); }); } } return step("next"); }); }; }
```

It doesn't seem that there's too much scope to bleed out CLS (unless CLS is doing something weird I'm not sure about), but I'll set-up unit tests with multiple simultaneous transactions to confirm and switch to `cls-bluebird` in the meantime.

**Comment by leebenson** [comment]
@overlookmotel FWIW, 'flat' CLS with native promises seems to work at scale:

```javascript
await Promise.all([...Array(1000)].map(() => {
  return this.sequelize.transaction(async () => {

    const model1 = new Test({
      test: Sequelize.cls.get('transaction').id,
    });

    await model1.save();
    await model2.addTest(model1);
    return model1;
  });
}));
```

> mysql> select distinct count(test) from test;
+----------------+
| count(test)    |
+----------------+
|           1000 |
+----------------+
1 row in set (0.01 sec)

haven't tested with nested CLS contexts yet...

**Comment by felixfbecker** [comment]
My approach is to simply pass `transaction` explicitly. It's not _that_ much boilerplate with property shorthands. Explicit > implicit.

**Comment by overlookmotel** [comment]
@leebenson The polyfill you're using will work mostly, but... *only* if the functions producing promises that you `await`/`yield` maintain CLS context throughout their code.

A lot of libraries don't support CLS and lose CLS context within them. `redis` is a well-known example. And it's hard to know which libraries do maintain CLS context and which don't as it's generally not tested for.

Try this:

```js
var cls = require('continuation-local-storage');
var ns = cls.createNamespace('test');

// An example function which returns a promise but loses CLS context
// Could be substituted for e.g. various promisified redis methods
function loser() {
    return new Promise(function(resolve) {
        ns.bind(resolve, {})();
    });
}

async function fn() {
    console.log('before:', ns.get('id'));
    await loser();
    console.log('after:', ns.get('id'));
});

ns.run(function() {
    ns.set('id', 123);
    fn();
});
```

I think you'll find it outputs:

```
before: 123
after: undefined
```

i.e. CLS context has got lost after the `await`. If you were using `sequelize.transaction()`, this would translate into any Sequelize calls after the `await` being executed outside the transaction. Oops!

My cls-bluebird patch ensures that, if you use `Bluebird.coroutine()`, the CLS context is always restored after a `yield` statement - so this problem doesn't occur.

So, my advice would be either:

1. Use `Bluebird.coroutine()` for coroutines
2. Find/write an alternative transpiler which allows you to provide your own `_asyncToGenerator` function and use `Bluebird.coroutine` (with the cls-bluebird patch applied to `Bluebird`)

Does this make sense?

**Comment by overlookmotel** [comment]
@felixfbecker Yes, you're right explicit passing is a more bullet-proof method. But some people (including me) prefer the implicit style. For me, the danger of explicit is that I forget `{transaction: t}` sometimes.

**Comment by overlookmotel** [comment]
@janmeier I'm not sure if [babel-plugin-transform-async-to-module-method](https://www.npmjs.com/package/babel-plugin-transform-async-to-module-method) will exhibit the same problems or not. Probably it will if you can't specify the Promise constructor which you want promises returned from async functions to be created from.

**Comment by felixfbecker** [comment]
@overlookmotel Well then we have a fallback to CLS :D
Btw you can write it with property shorthands like `Model.update({...}, {transaction})`

**Comment by overlookmotel** [comment]
@felixfbecker Hahaha! Well for me at least, after spending 3 months working on cls-bluebird and writing 100,000 tests to make sure it's completely bulletproof, I'm sure as hell going to use it as my primary method :)

**Comment by felixfbecker** [comment]
Sure you are free to do whatever you prefer :D

**Comment by leebenson** [comment]
Forgive me if I'm being naive, but isn't _explicit_ just a less forgiving _implicit_ with more keystrokes?

**Comment by felixfbecker** [comment]
I guess you could put it that way. I just don't like magic argument passing.

Btw, why do we even need to pass a transaction object to the methods? From a DB point of view, all you need to is `BEGIN`, do your queries, `COMMIT`.

**Comment by janmeier** [comment]
> Btw, why do we even need to pass a transaction object to the methods? From a DB point of view, all you need to is BEGIN, do your queries, COMMIT.

But we might have several concurrent transactions, and other code paths that shouldn't run on a transaction at all - So we need to explicitly tell which queries should be on which transaction (unless we want it to be implicitly defined by the context, which you don't like ;) )

**Comment by felixfbecker** [comment]
Ah alright. But you can only have one transaction per connection, right? So it's basically a question on which connection we run the query on?

**Comment by janmeier** [comment]
Yes, the transaction object is a wrapper around a connection object, with utility methods for commit and rollback

**Comment by leebenson** [comment]
> Explicit > implicit

It's a personal preference but IMO, wrapping it in a `.transaction()` block _is_ being explicit. It also avoids messy function signatures like `createUser(transaction=null)` everywhere.

Running it inside `.transaction` = "scope this to a transaction"

Running it outside = don't.

As far as I can tell, there's no scenario in which explicitly passing `{ transaction }` is preferable except in circumstances where `{ transaction: null }` (i.e. _never_ run inside a transaction)... but then, that same rule would hold-up inside a transaction block anyway, right?

**Comment by leebenson** [comment]
@overlookmotel, just to follow up on this code blurb:

```javascript
var cls = require('continuation-local-storage');
var ns = cls.createNamespace('test');

// An example function which returns a promise but loses CLS context
// Could be substituted for e.g. various promisified redis methods
function loser() {
    return new Promise(function(resolve) {
        ns.bind(resolve, {})();
    });
}

async function fn() {
    console.log('before:', ns.get('id'));
    await loser();
    console.log('after:', ns.get('id'));
});

ns.run(function() {
    ns.set('id', 123);
    fn();
});
```

This Mocha test seems to yield the right result with native promises:

```javascript
it('should maintain context', async function () {

  const cls = require('continuation-local-storage');
  const ns = cls.createNamespace('test');

  const loser = function () {
    return ns.runAndReturn(async function () {
      return new Promise(resolve => {
        ns.bind(resolve, {})();
      });
    });
  };

  const func = async function () {
    console.log('before:', ns.get('id'));
    await loser();
    console.log('after:', ns.get('id'));
  };

  return ns.runAndReturn(async function () {
    ns.set('id', 123);
    return func();
  });
});
```

> before: 123
after: 123

**Comment by leebenson** [comment]
actually scratch that, it doesn't work when setting a new value inside the inner Promise...

Argh. I'm trying to figure out a way to get CLS working properly with native promises. Native async/await is going to land in V8 before the year's out, and Node 7 will pick it up fast.

`Bluebird.coroutine(function*() { } )` is really just a stop-gap, IMO.

**Comment by leebenson** [comment]
(sorry for multiple posts.. kinda thinking out loud here...)

It seems to work with promises natively if every new 'context' is wrapped in a `namespace.runAndReturn` block.

Like:

```javascript
it('should maintain context', async function () {

  const loser = async function () {
    return ns.runAndReturn(async function (a) {
      ns.set('id', 789);
    });
  };

  const func = async function () {
    return ns.runAndReturn(async function () {
      ns.set('id', 456);
      console.log('middle before:', ns.get('id'));
      await loser();
      console.log('middle after:', ns.get('id'));
    });
  };

  return ns.runAndReturn(async function (a) {
    ns.set('id', 123);
    console.log('before: ', ns.get('id'));
    await func();
    console.log('finally: ', ns.get('id'));
  });
});
```

... correctly outputs:

> before:  123
middle before: 456
middle after: 456
finally:  123

How that relates to Sequelize transaction blocks is basically to create a 'wrapper' that looks something like this (obviously, you wouldn't roll back each time.. I'm using this inside Mocha just to roll-back anything that's created within a block)

```javascript
// Wraps promisified function in a transaction block
export function transaction(func) {
  return db.ns.runAndReturn(function () {
    return db.sequelize.transaction().then(async t => {
      db.ns.set('transaction', t);
      try {
        await func();

      } finally {
        await t.rollback();
      }
    });
  });
}
```

This _seems_ to correctly bind to the right transaction and handle nested transactions correctly. I don't have 100k tests to prove that, but it seems to withstand `ns.bind` and nested `ns.set` in early tests.

I'm really trying to find a way not to use Bluebird. When native async/await hits, I'm hoping to drop Babel completely and stick with plain JS. Hopefully this solves my use case.

**Comment by mdarveau** [comment]
Sorry to jump on this thread but it seems that other could use this information in the contect of this thread.

I almost lost my sanity this week debugging why I was loosing CLS context (transaction) in some circumstances.

The following code is broken (coffeescript):
```
sequelize.transaction( async (t)->
    console.log "Initial tx=#{Sequelize.cls.get('transaction')?.id}"
    await(1)
    console.log "After await(1) tx=#{Sequelize.cls.get('transaction')?.id}"
  )
```

On my computer, I get the tx id in both log. When I deploy to my server (heroku), the second log does not have the tx id. Why is it different on my computer vs heroku is a mistery I would love to solve.

Looks like when await is called on a constant, the tx is lost. When it's called on a promise, everything is fine. For example:
```
sequelize.transaction( async (t)->
    console.log "Initial tx=#{Sequelize.cls.get('transaction')?.id}"

    fn = ( returnPromise ) ->
      if returnPromise then return Promise.resolve(2) else return 1

    await fn(true)
    console.log "After fn(true) tx=#{Sequelize.cls.get('transaction')?.id}"
    
    await fn(false)
    console.log "After fn(false) tx=#{Sequelize.cls.get('transaction')?.id}"
  )
```
Will return a tx after ```fn(true)``` but no tx after ```fn(false)```. Painfull...

Workaround: make sure the function return a promise by adding the async keyword:
```
fn = async ( returnPromise ) ->
      if returnPromise then return Promise.resolve(2) else return 1
```

My questions are:
* Do you have an idea why the tx is lost after calling await on a constant?
* Do you have an idea why I get different results on my computer vs heroku. I know asyncawait depends on Fiber and maybe the fact that I'm on a mac and heroku is on some other linux flavor.

Can I use ```cls-bluebird``` with Sequelize?

Thanks!

**Comment by leebenson** [comment]
@mdarveau, you should only ever await on a Promise. What are you 'waiting' for, otherwise?

If the result is different on Heroku, maybe you're using different async/await polyfills of some kind? I'm not familiar with coffeescript transpilation, so I can't comment on possible pipeline differences

The code I've given above solves CLS issues for native Promises, in my use case. It's probably not as thorough as cls-bluebird. The only reason I'm not using cls-bluebird is because I want to get away from third-party Promise libraries and anticipate a design that will work with native async/await. The above seems to work.

This is what I have as my current `transaction` wrapper:

```javascript
export async function transaction(func) {
  return ns.runAndReturn(async function () {

    // If we already have an existing transaction, re-use it
    if (ns.get('transaction')) {
      return func();
    }

    // If not - start a new one
    return sequelize.transaction(async t => {
      return func();
    });
  });
}
```

This does a few things:

1. It attaches itself to the CLS namespace's `runAndReturn` block, so everything inside is guaranteed to be scoped to the CLS

2. If there's an existing transaction, it simply runs the passed in `func()`, which has the effect of 'binding' it to the existing transaction block. This means if there's an existing transaction occurring somewhere in the system for that request, it will scope it to it.

3. If there's no transaction, it will use sequelize's `transaction` block to return a 'managed' transaction, and run the block inside of the newly created transaction. Since this occurs within `runAndReturn` too, any promise chain inside of it should maintain the CLS context.

**Comment by leebenson** [comment]
```javascript
export async function transaction(func) {
  return ns.runAndReturn(async function () {
    return sequelize.transaction(async t => {
      return func();
    });
  });
}
```

(`func` should always return a promise, btw)

**Comment by leebenson** [comment]
(updated the above for clarity, btw, in case you read it before I finished)

**Comment by overlookmotel** [comment]
@leebenson This isn't going to be a particularly useful comment, but... I think you're misunderstanding what `ns.runAndReturn()` does, and also to some degree how CLS works overall.

This isn't surprising! It's really pretty hard to get your head around as it's totally against the grain of how everything else works in Node and it's much more subtle than it looks when it comes to Promises. It took me a *long* time to work it out and feel confident I really understood it.

I'm really sorry this is so negative! I'll try to post properly explaining myself, but right now I'm totally tied up. I just didn't want someone else to grab your code example and then get themselves into tricky water.

In the meantime, this issue might help you: https://github.com/othiym23/node-continuation-local-storage/issues/64

**Comment by overlookmotel** [comment]
I get the feeling this is going to be a really common theme, especially with async/await coming on the horizon. I'll try to write up a proper explainer when I get a chance.

**Comment by leebenson** [comment]
@overlookmotel 

I'm definitely no expert on CLS (before last week, I hadn't read more than a couple of lines) so it's likely that I'm missing some of the implementation details.

I'd appreciate any pointers on what you suspect I'm missing.  I've read the issue you posted (matter of fact, I read it a few days ago when I was down the CLS rabbit hole and trying to figure it out) and I (think) I understand the 3 different ways CLS _could_ work, and some semblance of the way it actually _does_. But if you're getting code smells from the snippets I posted above, clearly I'm missing something!

Despite that, the code _seems_ to be working how I'd expect it to. Namely:

1. Transactions are scoped to the Promise chain in which they occur.
2. Separate Promise chains have separate transactions.
3. A promise that is awaited _inside_ another Promise forms part of its parent chain.
4. Any promise that mutates the namespace keeps that namespace for the life of the `.then` callback chain
5. Any sub-promise that mutates the namespace is disregarded when the promise has 'finished', returning the previous namespace value to the parent chain

Again, it's possible I'm **way off**, but isn't that how they're supposed to work? Or am I totally missing the point?

**Comment by leebenson** [comment]
And btw @overlookmotel , thanks for all your help. I really appreciate

**Comment by mdarveau** [comment]
> @mdarveau, you should only ever await on a Promise. What are you 'waiting' for, otherwise?

According to https://github.com/yortus/asyncawait#8-await-in-depth-awaitable-expressions, a constant is an "awaitable" expression. Granted, it does not sounds super useful but look at the following scenario:

```
      # Promise<GameCredit> Result can be null if no credit is associated with game
      getGameCredit: async ->
        return null unless this.GameCreditId?
        return GameCredit.findById(this.GameCreditId)
```

It's pretty convenient!

> If the result is different on Heroku, maybe you're using different async/await polyfills of some kind? I'm not familiar with coffeescript transpilation, so I can't comment on possible pipeline differences

This is the part that puzzle me the most. I don't think it's related to the coffeescript and I checked a bunch of dependencies and they are at the same version. Node version is also the same. The only difference I can see if the OS but that seems far fetched.

In the example above, `getGameCredit: async ->` is ok but `getGameCredit: ->` is not and I can't figure why.

@overlookmotel if you have any guess, I'd be a happy camper! :-)

**Comment by felixfbecker** [comment]
It is convenient if you have a function that _may_ return a promise, but imI would always be explicit and wrap it in a Promise.resolve(). In your example it is of no use though, an say c function will always return a promise (or I'm not understanding coffeescript)

**Comment by leebenson** [comment]
> According to https://github.com/yortus/asyncawait#8-await-in-depth-awaitable-expressions, a constant is an "awaitable" expression

Looking at the current working draft, it appears the runtime should 'cast' a constant to a promise if it isn't already one. But I agree with @felixfbecker - I'd always try to be explicit with this, so you know exactly what you're getting.

A small caveat too- if you happen to be using `nodent`, 'await' won't wrap non-promises by default. Using `async` in your function will turn that `null` into a promise, so you're covered.

> In the example above, getGameCredit: async -> is ok but getGameCredit: -> is not and I can't figure why.

I ran into exactly the same scenario with a function returning a promise. Adding `async` fixed it. I put it down to the semantic difference of a function _returning_ a promise vs. the function _being_ a Promise. I didn't explore it too much, since all of my promise chains use async functions. If you figure it out, I'd be interested to hear!

**Comment by getvega** [comment]
Hi @leebenson,

Have you managed to make it work within a mocha test suite?

What we had working perfectly under Sequelize 3.3.x / CLS 3.x seems to be broken under Sequelize 3.24.x. We're used to write all our mocha tests (500+) in this flavor to have our db resetted between each suite.

```javascript

// test.js

describe('test', () => {

  before(() => sequelize.transaction());

  after(() => namespace.get('transaction').rollback());

  it('is created under the right transaction', async () => {
    await models.User.create({ ... });
  });

});
```

But migrating to Sequelize 3.24 broke this... :( but it's hard to know which of Bluebird / Babel / Sequelize introduced regressions here...

We even tried those cls-bluebird recipes without success:

```javascript

// init-tests.js

var bluebird = require('bluebird').getNewLibraryCopy();
var cls = require('continuation-local-storage');
var clsBluebird = require('cls-bluebird');
var namespace = cls.createNamespace('tests');

clsBluebird(namespace);
require('babel-runtime/core-js/promise').default = bluebird;
Sequelize.cls = namespace;
```

**Comment by leebenson** [comment]
@getvega - apologies for the tardy response.

Yes, I've been using Mocha with Sequelize 4.0 pretty well.

It's comprised of these three parts:

**1. Generic `rollback` function**

This returns a transaction that automatically rolls back at the end, regardless of what happens in between. This is the code:

```js
// snippets from my `db.js` instantiation file, that I also share with my Mocha tests
import cls from 'continuation-local-storage';
export const ns = cls.createNamespace('sequelize');
Sequelize.useCLS(ns);

// regular DB instantiation stuff here
// ...

export async function rollback(func) {
  return ns.runAndReturn(async () => (
    sequelize.transaction().then(async t => {
      ns.set('transaction', t);
      try {
        await ns.bind(func)(t);
      } finally {
        await t.rollback();
      }
    })
  ));
}
```

Note: As discussed above, @overlookmotel said this probably won't guarantee that CLS won't 'bleed' out to other transactions. In a single-user test paradigm like Mocha, I've not (yet) come across any issues, but YMMV. I lack the knowledge on the subject that @overlookmotel has!

**2. Test wrapper**

This is a function that will wrap your tests. I use this wrapper to start a new server instance for _each_ test, and then kill it at the end. The benefit to this is that anything that happens ANYWHERE in the app (even to HTTP requests against that same server that occur externally) will then re-use the same CLS (again, this is true in my own testing- YMMV), which has the nice side-effect of catching random insertions and other DB changes that occur anywhere in live code.

You might not need a wrapper like this, but it's useful for general spin-up/tear-down:

```js
// inside a `common.js` file that I import into Mocha
export function test(func) {
  return async function () {

    return db.rollback(async function () {
      const server = new Server;
      await server.start();

      await func.bind({
        server,
      })();

      await server.stop();
    });
  };
}
```

Again, most of that stuff probably won't make any sense to your environment, but what I'm doing here is basically spawning a new web server (on a new/dynamic port), passing that server into my test function context so I can access it via `this.server`, and then stopping the server at the end -- per test.

**2. The tests themselves**

I then wrap each `it()` callback with the `common.test` above, so my tests wind up looking like this...

```js
it('should sign-up a new user', common.test(async function () {

  // Create user
  const { id } = await graphql.createUser(this.server.client(), fixtures.validUser);

  const instance = await db.models.User.findOne({
    where: {
      id,
    },
  });

  // should have an entry in the DB
  assert.equal(instance.id, id, 'IDs should match');
}));
```

What's interesting about this particular test (and can be done wherever `common.test` is used) is that the GraphQL stuff I'm doing doesn't happen in this 'stack' - it uses a third-party client to send mutations via HTTP, that I can then test locally inside of Mocha.

This is important in my tests because I'm not just testing local API functionality, I'm also testing live staging endpoints within my app. This approach ensures that _whatever_ happens inside my app is going to yield access to the underlying DB records within the current 'context', and is going to rollback and disappear as soon as this test is finished.

Hopefully that gives you some food for thought. My test suite is quite complex and domain-specific, so there's a ton of interdependencies that won't make any sense to copy and paste here, but that's the gist.

**Comment by felixfbecker** [comment]
@getvega I want to point out that while your idea sounds very nice in theory, it can't work in practice if the subject under test uses transaction itself. None of the DB engines Sequelize supports have support for nested transactions. A transaction is nothing but a `BEGIN`, a series of SQL commands, and a `ROLLBACK` or `COMMIT`. Any `BEGIN` inside a `BEGIN` will not work. The only thing that comes close to this is savepoints in Postgres, but that does not allow you to nest transactions infinitely. It basically gives you the ability to have two-level transactions, one outer transaction and multiple savepoints inside it. Sequelize tries to emulate nested transactions with this but you cannot 100% emulate this as it is only two-level. I tried to implement your style too (without any CLS, we use explicit transactions everywhere), but our tests began failing because it doesn't work in practice as one might think it does.

**Comment by leebenson** [comment]
@felixfbecker, that's generally a very good point, but I should make it clear that my implementation _kinda_ solves that (to an extent) by doing the following:

Instead of using the generic `sequelize.transaction`, I use this:

```js
export async function transaction(func) {
  return ns.runAndReturn(async () => {
    // If we already have an existing transaction, re-use it
    if (ns.get('transaction')) {
      return func();
    }

    // If not - start a new one
    return sequelize.transaction(async () => (func()));
  });
}
```

Again, disclaimer: @overlookmotel said this may not be doing exactly what I _hope_ it's doing with native promises, so YMMV. But what it's _supposed_ to do is detect whether the transaction is running within an existing transaction - and if so, use that same context.

So in effect, a "transaction within a transaction" runs within the parent transaction.

It's a bit _Inception_, but since MySQL doesn't offer any real choice and I want my tests to reflect some semblance of real-world usage, this is the best I've come up with so far.

![Inception](https://memecrunch.com/meme/CTBE/inception-meme/image.jpg?w=350&c=1)

**Comment by felixfbecker** [comment]
@leebenson That doesn't work because if your subject under test calls `transaction.commit()`, it will commit the parent transaction

**Comment by leebenson** [comment]
@felixfbecker - none of my code uses an explicit `.commit` - I'm using implicit transaction blocks that leave committing/rolling back to the parent scope.

**Comment by leebenson** [comment]
(which is another reason why my use-case above is probably slim and YMMV!)

**Comment by overlookmotel** [comment]
All change in the world of CLS with async_hooks now arrived in Node core. But still some kinks need to be worked out in async_hooks itself with how it works with Promises, and it's going to take a while until lots of npm modules make the necessary changes to support async_hooks.

The CLS implementation in Sequelize (using [cls-bluebird](https://www.npmjs.com/package/cls-bluebird)) works. But I wouldn't expect any progress on some of the questions posed above any time soon. Now that async_hooks is here, it's a matter of rip up most of what came before and re-write from scratch. So that's going to take time.

**Comment by leodutra** [comment]
@overlookmotel so using CLS with cls-bluebird async and await works normally?

**Comment by leodutra** [comment]
Nested CLS calls fails hard with native promises.

**Comment by leodutra** [comment]
My workaround was to replace sequelize.transaction for 
```js
async function transaction(task) {
  return clsNamespace.get('transaction') ? task() : sequelize.transaction(task);
}
```
