### ISSUE TITLE
transaction status

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6547]
hello!

How to check is transaction executing, commited, or rollbacked?  This is neccecary for try - catch error handlings

Thanks!

**Comment by felixfbecker** [comment]
Please show some code

**Comment by alexey2baranov** [comment]
```
async createModel(args, {type, value}) {
    var tran = await models.sequelize.transaction();
    var result = null;

    try {
        let result = await models[type].create(value);

        switch (type) {
            case "Zemla":
                //some staff
                await tran.commit();
                //some staff
                break;
            case "Kopa":
                //some staff
                await tran.commit();
                //some staff
                break;
            case "Golos":
                //some staff
                await tran.commit();
                //some staff
                break;
            case "Slovo":
                //some staff
                await tran.commit();
                //some staff
                break;
            case "Kopnik":
                //some staff
                await tran.commit();
                //some staff
                delete result.password;
                break;
            case "File":
                break;
        }
        return result.id;
    }
    catch (err) {
        **if (!tran.commited && !tran.rollbacked) {
            tran.rollback();
        }**
        throw err;
    }
}
```

**Comment by felixfbecker** [comment]
This is not needed - if there was an error, the transaction of course was not commited and you have to roll it back. If your code doesnt allow this, you should narrow your try/catch block down or refactor your code into functions.

**Comment by alexey2baranov** [comment]
@felixfbecker 

>  if there was an error, the transaction of course was not commited and you have to roll it back

yes! but error may be throwned before and after transaction commit. if it was thrawned before transaction then tran.rollback() in catch block do his job. Otherwise it throws another error "transaction already commited".

the only way refactor this is to add try - catch inside every case block. but i would like to miss this job

**Comment by felixfbecker** [comment]
That's why `transaction.commit()` should be the last statement in your `try` block. Also, you are not `await`ing `tran.rollback()`, so your statement about throwing error "transaction already commited" is actually not true.

**Comment by alexey2baranov** [comment]
in out case transaction could not be the last statement in try block because some staff should be done when new model available to others. Of cause we can rewrite this part but code become overloaded. I think tran state is very usefull instead of doing tran.commit the last statement of try block.

**Comment by alexey2baranov** [comment]
@felixfbecker **do_not_await** transtaction.roolback() is a little hack by now to avoid error throwing

**Comment by felixfbecker** [comment]
What needs to happen after commit()? Why can't you move it after the try/catch?
An alternative is to save a boolean yourself.

**Comment by alexey2baranov** [comment]
it is not important what we do after commit because each project has their specific. and what we do other will not. I think it would be good for all if Transaction has their state. We publicate specific for each model WAMP publication and other clients will receive this publication and fetch new model from DB. So we should commit transaction before publication.

> Why can't you move it after the try/catch? An alternative is to save a boolean yourself.
yes. as i can sad we can rewrite it but code become overloaded

Anyway i understand that Transaction.state is not possible by now. Thank you for you time

**Comment by felixfbecker** [comment]
You might wanna look at the internals, I think it is saved somewhere. If you really need it do a PR. You can also use the `transaction(callback)` signature.

**Comment by AiDirex** [comment]
there is a property named `finished` on the transaction object that you can check to see if a transaction has been committed or not. However, It is not official API and may change.
```js
// ...
if (transaction.finished === 'commit') {
    // transaction has been committed
} else {
    // transaction has not been committed
}
```

**Comment by DashBarkHuss** [comment]
> there is a property named `finished` on the transaction object that you can check to see if a transaction has been committed or not. However, It is not official API and may change.
> 
> ```js
> // ...
> if (transaction.finished === 'commit') {
>     // transaction has been committed
> } else {
>     // transaction has not been committed
> }
> ```

Why don't I see this property?

```javascript
 const t = await sequelize.transaction();
 
 t.finished > undefined
 ````

**Comment by Mohim-Singla** [comment]
@DashBarkHuss As per my observation, `finished` property is appended to the transaction instance object once commit/rollback function is called. Try below mentioned code snippet.

```
const t = await sequelize.transaction();
 await t.commit();
 console.log(t.finished);
```
