### ISSUE TITLE
Semantic release

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6550]
https://github.com/semantic-release/semantic-release
- Automatic changelog
- Automatic releases

Commit message convention can be followed easily with https://github.com/commitizen/cz-cli
and validated with https://github.com/kentcdodds/validate-commit-msg

**Comment by mickhansen** [comment]
I like the idea, primary pet peeve is that it doesn't update package.json or do git tags

**Comment by janmeier** [comment]
No git tags makes me sad :( - I know that a fair amount of people rely on github releases (which are connected to tags)

**Comment by felixfbecker** [comment]
Um guys?
> A changelog gets generated and a release (including a git tag) on GitHub gets created.

**Comment by felixfbecker** [comment]
@mickhansen @janmeier @sushantdhiman We should revisit this now that we have v4 out :)

**Comment by mickhansen** [comment]
I definitely like the idea @felixfbecker
