### ISSUE TITLE
Links to Docs in README are broken

### ISSUE THREAD

**Issue by mattpolicastro** [sequelize/sequelize#6555]
## What you are doing?
Looking at (stable) documentation for the project on Read the Docs. (Silly maintenance quibble.)

## What do you expect to happen?
Documentation to open for the stable versions of "Getting Started", "Documentation", and "API Reference".

## What is actually happening?
A "Maze Found..." error is shown on RTD.

**Comment by sushantdhiman** [comment]
Please use these official docs http://docs.sequelizejs.com/en/v3/

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/commit/3dd9fc056cf8f02bb9b405fcdf152eade98c484d

**Comment by mattpolicastro** [comment]
Looks like https://github.com/sequelize/sequelize/commit/6d90b5ba66a4ae44cd5fb81cf0a7288115ca4482 re-added the broken links removed in https://github.com/sequelize/sequelize/commit/3dd9fc056cf8f02bb9b405fcdf152eade98c484d.

**Comment by sushantdhiman** [comment]
Fixed again in https://github.com/sequelize/sequelize/commit/270ae22ee39d0d068a07244411df8502eda90a7c

**Comment by glebec** [comment]
Any particular reason you took down the `stable` links? It just invalidated many pages of urls scattered across multiple projects at our company. Not a huge deal, just wondering.

**Comment by felixfbecker** [comment]
@glebec the reason was that `stable` always linked to `v4.0.0-1` instead of `v3` because readthedocs didn't consider it a prerelease. For v4 we will have the docs at doclets.io, see #6226
