### ISSUE TITLE
Inline query support

### ISSUE THREAD

**Issue by Runlikewind** [sequelize/sequelize#6561]
Hello, does 'sequelize' support inline query? I have met a problem that I have to select some data from inline view today. I have tried some methods which others offered, just like: use sequelize. literal in property of 'attributes', but it doesn't work and results in just like below:

``` sql
select (select * from dbname) from ...
```

Execpt sequelize.query, can i find other methods to do select like this:

``` sql
SELECT 'hid', count('max') FROM (SELECT 'hid', max('version') AS max, 'uid' FROM db WHERE db.hid = 'xxx' AND db.time <= '245527422' GROUP BY db.uid);
```

Thanks a lot.

**Comment by mickhansen** [comment]
We don't currently, it's something i see crop up in my own work aswell.
Not quite sure how to design it yet.

**Comment by Runlikewind** [comment]
@mickhansen Thanks.
That is to say, i have to use 'sequelize.query' for inline query. T_T
By the way, will inline query be supported in the future? maybe next version?😁

**Comment by mickhansen** [comment]
I'll refer to my previous comment :)

**Comment by felixfbecker** [comment]
The API is tricky to design because Sequelize uses an active record pattern, and when you SELECT from an inline query you don't actually select from a model, so we have no model to call the method on. We could do it through `QueryInterface.select()` though. Something like
```js
QueryInterface.select({
  attributes: ['hid', sequelize.fn('COUNT', 'max')],
  from: {
    attributes: ['hid']
    from: 'db',
    where: {
      hid: 'xxx',
      time: '245527422'
    },
    groupBy: 'uid'
  }
})
```
`select(model, options)` would just be a shorthand for `select({from: model})` then

**Comment by felixfbecker** [comment]
Alternative:
```js
QueryInterface.select(sequelize.inlineQuery({
  attributes: ['hid']
  from: 'db',
  where: {
    hid: 'xxx',
    time: '245527422'
  },
  groupBy: 'uid'
}), {attributes: ['hid', sequelize.fn('COUNT', 'max')]})
```

**Comment by Runlikewind** [comment]
@felixfbecker 👍
The version of sequelize that i use is 3.24.1, and do i need to update the version of sequelize?
`console.log(sequelize.inlineQuery)` results in `undefined`

**Comment by felixfbecker** [comment]
As @mickhansen said we don't support it currently. That was an API proposal.

**Comment by Runlikewind** [comment]
uh... i got it!😅 Thanks a lot~
