### ISSUE TITLE
defining models with scopes etc. in v4

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#6563]
In v4.0.0 you can now define a model (e.g. User) as follows: User extends Sequelize.Model

How should you define you model's indexes and scopes with this method?

**Comment by felixfbecker** [comment]
If you subclass the model you need to call `Model.init(attributes, options)` on it (same parameters as `define`).
You might want to look through #6439

**Comment by nareynolds** [comment]
thanks!
