### ISSUE TITLE
How access a model's associated models

### ISSUE THREAD

**Issue by nareynolds** [sequelize/sequelize#6564]
Is there a programmatic way to access the associated models of a model?

For example, if there is a 1:M association between the models `Author` and `Book`, is there a way that I can access the `Book` model from the `Author` model along with the type of association?

Something like `Author.getAssociations()` would return something like:
```javascript
[{
    relationship: "hasMany",
    model: Book
}]
```

**Comment by felixfbecker** [comment]
Yes, the associations are saved under `Model.associations`, which is an object hash from alias to association object. The association objects are seperate classes for hasMany / belongsTo / ... and have a couple of attributes, if they are not documented you might wanna peek into the source.

**Comment by nareynolds** [comment]
thanks, again!
