### ISSUE TITLE
No documentation about "Working with table schemas"?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6565]
Where are links here http://sequelize.readthedocs.io/en/v3/docs/schema/? Where may I find docs?
You have table of contents:

![working with table schemas - sequelize _ the node js _ io js orm for postgresql mysql sqlite and mssql - google chrome 2016-09-08 12 48 46](https://cloud.githubusercontent.com/assets/3880497/18337412/f9059e2e-75c2-11e6-9729-14a09a623dd5.png)

But there are no any of those sections:

![working with table schemas - sequelize _ the node js _ io js orm for postgresql mysql sqlite and mssql - google chrome 2016-09-08 12 50 48](https://cloud.githubusercontent.com/assets/3880497/18337411/f84cb81e-75c2-11e6-99c1-674a8d4a819c.png)

**Comment by felixfbecker** [comment]
That part was moved to migrations
http://docs.sequelizejs.com/en/v3/docs/migrations/

**Comment by mickhansen** [comment]
Actually i was in the process of moving it from migrations to table schemas, i just never really did it.

**Comment by felixfbecker** [comment]
I think that would be good, because you can use `QueryInterface` in other contexts than migrations.

**Comment by mickhansen** [comment]
Yes, the intention was to have a good general table schema API that could be used in migrations but not tied to it (it isn't know either but the schema modification API hasn't had a lot of love)
