### ISSUE TITLE
Why does sequelize create new connection for each query?

### ISSUE THREAD

**Issue by adamkecskes** [sequelize/sequelize#6567]
_It seems, sequelize creates new connection for each query instead of using existing ones from pool._

## What you are doing?
_I'm sending sleep queries in every two seconds._

```js
var sequelize = new Sequelize(options.database, options.user, options.password, {
    host: options.host,
    dialect: 'mysql',
    port: options.port,
    pool: {
        max: 10,
        min: 2,
        idle: 10000
    }
});

setInterval(function () {
    sequelize.query('SELECT SLEEP(1);');
}, 2000);
```

## What do you expect to happen?
_I would except all these queries to get the same connection from the pool_

## What is actually happening?
_When I check the mysql processes, I see different connection ids for each sleep query._
```console
| 12973820 | admin         | 10.179.195.173:34544 | FieldServices | Query   |    0 | User sleep | SELECT SLEEP(1)  |         0 |             0 |
```
```console
| 12973822 | admin         | 10.179.195.173:34545 | FieldServices | Query   |    0 | User sleep | SELECT SLEEP(1)  |         0 |             0 |
```
```console
| 12973818 | admin         | 10.179.195.173:34545 | FieldServices | Query   |    1 | User sleep | SELECT SLEEP(1)  |         0 |             0 |
```

_But when I use default mysql pool, all my queries use the same connection:_

```js
var mysql = require('mysql');
var pool  = mysql.createPool({
    connectionLimit : 10,
    host            : !options.tunnel ? options.host : "127.0.0.1",
    user            : options.user,
    password        : options.password,
    database        : options.database,
    port: !options.tunnel ? options.port : config.get('tunnel.' + options.tunnel).localPort,
});

setInterval(function () {
    pool.query('SELECT SLEEP(1);', function (err, rows, fields) {
        if (err) throw err;
        console.log('sleep');
    });
}, 2000);
```

```console
| 12975966 | admin         | 10.179.195.173:36196 | FieldServices | Query   |    1 | User sleep | SELECT SLEEP(1)  |         0 |             0 |
```
```console
| 12975966 | admin         | 10.179.195.173:36196 | FieldServices | Query   |    0 | User sleep | SELECT SLEEP(1)  |         0 |             0 |
```
```console
| 12975966 | admin         | 10.179.195.173:36196 | FieldServices | Query   |    0 | User sleep | SELECT SLEEP(1)  |         0 |             0 |
```

__Dialect:__ mysql
__Database version:__ 5.5.40
__Sequelize version:__ 4.0.0-1

**Comment by felixfbecker** [comment]
Connections are cycled round-robin style, so it's not always connection A that gets 90% of the queries while connection B, C, D idle mostly.

**Comment by adamkecskes** [comment]
It's not round-robin, when you run it for one minute, it'll create 30 connections although, there are 10 in the pool.

**Comment by mickhansen** [comment]
@adamkecskes Sequelize will never create more connections than the pool.max. Also see https://github.com/coopernurse/node-pool

**Comment by mickhansen** [comment]
> I would except all these queries to get the same connection from the pool

You've defined a minimum set of connections, so there will always be 2. I don't know if generic-pool uses random or round robin.

**Comment by felixfbecker** [comment]
I think it's round-robin
> returnToHead : boolean, if true the most recently released resources will be the first to be allocated.
>                     This in effect turns the pool's behaviour from a queue into a stack. optional (default false)

**Comment by adamkecskes** [comment]
The connection ID in processlist keeps increasing. Even if there should only be one connection in the pool and never let idle for 10 seconds.

```js
var sequelize = new Sequelize(options.database, options.user, options.password, {
    host: options.host,
    dialect: 'mysql',
    port: options.port,
    pool: {
        max: 1,
        min: 1,
        idle: 10000
    }
});

setInterval(function () {
    sequelize.query('SELECT SLEEP(1);');
}, 2000);
```

It creates new connections for each query instead of using existing connection.
Please notice the `Connect` and the `Quit` statements.

_mysql log:_
```log
160908 11:09:00    60698 Quit
60699 Connect    root@localhost on FieldServices
60699 Query    SET time_zone = '+00:00'
60699 Query    SELECT SLEEP(1)
160908 11:09:02    60699 Quit
60700 Connect    root@localhost on FieldServices
60700 Query    SET time_zone = '+00:00'
60700 Query    SELECT SLEEP(1)
160908 11:09:04    60700 Quit
60701 Connect    root@localhost on FieldServices
60701 Query    SET time_zone = '+00:00'
60701 Query    SELECT SLEEP(1)
160908 11:09:06    60701 Quit
60702 Connect    root@localhost on FieldServices
60702 Query    SET time_zone = '+00:00'
60702 Query    SELECT SLEEP(1)
160908 11:09:08    60702 Quit
60703 Connect    root@localhost on FieldServices
60703 Query    SET time_zone = '+00:00'
60703 Query    SELECT SLEEP(1)
```

**Comment by mickhansen** [comment]
So question is if there's a bug in Sequelize (not passing the values to generic-pool correctly) or a bug in generic-pool in that it doesn't really work with min/max as the same value, or doesn't respect the idle.

**Comment by janmeier** [comment]
Adding a log to pool.create inside abstract connection manager shows we only create a connection once, and keep reusing that.

**Comment by steveetm** [comment]
Adding a log to pool.create means there is only one pool created, but multiple connections.

```js
// sequelize/lib/dialects/abstract/connection-manager.js:232

  _connect(config) {
    console.log('Newconnection');
    return this.sequelize.runHooks('beforeConnect', config)
      .then(() => this.dialect.connectionManager.connect(config));
  }
```

The result:
```log
Newconnection
Newconnection
Executing (default): SELECT SLEEP(1);
Newconnection
Executing (default): SELECT SLEEP(1);
```

**Comment by janmeier** [comment]
Running your example with `DEBUG=sequelize*`

``` 
  sequelize:pool creating connection +0ms
  sequelize:pool creating connection +5ms
  sequelize:connection:mysql connection acquired +28ms
  sequelize:connection:mysql connection acquired +0ms
  sequelize:pool pool created max/min: 10/2 with no replication +3ms
  sequelize:pool pool created max/min: 10/2 with no replication +3ms
  sequelize:pool creating connection +2s
  sequelize:connection:mysql connection acquired +9ms
  sequelize:sql:mysql executing(default) : SELECT VERSION() as `version` +14ms
  sequelize:sql:mysql executed(default) : SELECT VERSION() as `version` +18ms
  sequelize:connection:mysql connection disconnected +5ms
  sequelize:pool connection acquired +1ms
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +1ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +2ms
  sequelize:pool connection acquired +952ms
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +0ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +0ms
  sequelize:pool connection acquired +1s
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +0ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +0ms
  sequelize:pool connection acquired +1s
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +0ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
 sequelize:pool connection released +1ms
  sequelize:pool connection acquired +997ms
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +1ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +1ms
  sequelize:pool connection acquired +998ms
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +1ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +2ms
  sequelize:pool connection acquired +997ms
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +1ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +1ms
  sequelize:pool connection acquired +998ms
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +1ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +1ms
  sequelize:pool connection acquired +1s
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +2ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
  sequelize:pool connection released +0ms
  sequelize:pool connection acquired +1s
  sequelize:sql:mysql executing(default) : SELECT SLEEP(1); +0ms
  sequelize:sql:mysql executed(default) : SELECT SLEEP(1); +1s
```
Some connections are created at the start, but after that we keep re-using them.

**Comment by steveetm** [comment]
Because the bug was not in sequelize but in mysql2 package, which is fixed now indeed, but there is no version requirement or warning in sequelize about which mysql2 package you should use.

**Comment by felixfbecker** [comment]
Imo tracking bugs for drivers and printing bugs for every version is out of scope for sequelize. The first thing you should do when you encounter a bug is `npm update` :)

**Comment by dinhanhhuy** [comment]
### Environment:
node: v8.5.0
"sequelize": "^4.38.0",
mySQL:
<img width="336" alt="screen shot 2018-07-19 at 2 46 16 pm" src="https://user-images.githubusercontent.com/20637671/42928821-8a60f182-8b62-11e8-9d09-b9b3fc503be1.png">

### Problem
> Some connections are created at the start, but after that we keep re-using them.

In my case it create too much connection:

### Testing output

As text:
[Terminal Saved Output.txt](https://github.com/sequelize/sequelize/files/2208824/Terminal.Saved.Output.txt)

As image:
<img width="752" alt="screen shot 2018-07-19 at 2 42 18 pm" src="https://user-images.githubusercontent.com/20637671/42928616-fea1d09e-8b61-11e8-8e0a-6aee9616e817.png">

**Comment by sushantdhiman** [comment]
@dinhanhhuy How are you tracking number of connections? Just by logs?

**Comment by dinhanhhuy** [comment]
@sushantdhiman sorry for my late response. I already check the number connection in MySQL and get `error too many connections`.  But i found that my code issue, create too much query at same time and dont limit max_pool in config sequelize. So sequelize create many connection is the right behavior in my case.

**Comment by knoxcard** [comment]
@dinhanhhuy close ticket?

**Comment by scriptsure** [comment]
quick question i am running into a strange issue on RDS where i have a ton of OS sleeping threads. My show full processlist shows about half the total that cloudwatch is showing. aws is saying that connections are not being closed properly. 

I am on version 3.40 of sequelize would i be using mysql or mysql2? Right now i am using mysql 2.17.1....
