### ISSUE TITLE
Raw values in hooks

### ISSUE THREAD

**Issue by ozthegreat** [sequelize/sequelize#6568]
It would be handy to be able to access the raw values passed to the methods in hooks. At the moment any params & values that aren't specifically defined are stripped out by the validation, any subsequent hooks that run only see the validated and sanitised params & values. Sometimes it's handy to pass flags with the input values that aren't necessarily saved but are used in the hooks.

A new param on the instance could be set that contains these raw, unvalidated values. I believe other ORMs (such as eloquent) do do something similar.

**Comment by mickhansen** [comment]
Extra options should generally be passed around as-is, that's the goal atleast.

**Comment by ozthegreat** [comment]
Maybe my use case is too specific then. To be more exact, I use the "beforeCreate" hook to ping an API, this call uses fields that the DB doesn't require, but (from what I can tell), there's no way to pass extra fields through the validation without the ORM expecting them to exist in the DB.
