### ISSUE TITLE
What is "options" param for schema functions (createTable, dropTable, etc) ?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6569]
What are the options? They are not described on the [page](http://sequelize.readthedocs.io/en/v3/docs/migrations/), aren't they?

![migrations - sequelize _ the node js _ io js orm for postgresql mysql sqlite and mssql - google chrome 2016-09-08 20 42 28](https://cloud.githubusercontent.com/assets/3880497/18349701/28813e14-7605-11e6-95a8-072b67392fef.png)

I need to drop several tables that has FKs. I need to drop them with specific sequence. Can those `options` 
help with it? How?

```
queryInterface.dropTable('TableOne', { ? })
queryInterface.dropTable('TableTwo', { ? });
queryInterface.dropTable('TableThree', { ? });
```

**Comment by wzup** [comment]
Figured out. But what is `options` parameter? Interesting.

```
queryInterface.dropTable('TableOne', {})
.then(res => {
    console.log();

    queryInterface.dropTable('TableTwo', {})
    .then(res => {
        console.log();

        queryInterface.dropTable('TableThree', {})
        .then( res => {
            console.log();
        })
    })
});
```

**Comment by felixfbecker** [comment]
QueryInterface is not documented well atm, you might have to look at the source to figure out.
Let me improve your code:
```js
queryInterface.dropTable('TableOne')
  .then(() => queryInterface.dropTable('TableTwo'))
  .then(() => queryInterface.dropTable('TableThree'))
  .then(() => {
    console.log();
  });
```

**Comment by undisplay** [comment]
options is an object where you can specify cascade to be true or false ,you can use force instead of cascade also . [https://github.com/sequelize/sequelize/blob/d47a702f47c1f57c87607e32c00c367e41593c22/lib/query-interface.js#L201](url)
