### ISSUE TITLE
Saving a model with a default scope doesn't include the default scope.

### ISSUE THREAD

**Issue by Pfeifenjoy** [sequelize/sequelize#6570]
## What you are doing?
I am not sure if this is intentional or a bug.
I have two models a user and a student.
Because a student is a user I created a one to one relationship between them
and included the user in the default scope.
That way I want to get some abstraction.

```js
var User = sequelize.define("user", {
name: STRING, ...})
var Student = sequelize.define("student", {
matnr: INTEGER,....},{
defaultScope: {
    include: [ User ]
}})
Student.hasOne(User)
```

When I run find on Students I the student includes the user,
but when I create a student and a user and then connect them after saving the 
student doesn't include the user.

```js
Promise.all([
    Student.create(),
    User.create()
])
.then(([student, user]) => {
    student.setUser(user)
    return Promise.all([
         student.save(), user.save()
    ])
})
.then(([student, user]) => {
    student.user // => undefined
})
```

## What do you expect to happen?
I would expect the user to be included in the student.

## What is actually happening?
The user is not included only when I run find

__Dialect:__ sqlite
__Database version:__ 3.1.4
__Sequelize version:__ 3.24.1

**Comment by janmeier** [comment]
Scopes are only included on finds - So you need to do a `findOne / all` after the `save`
