### ISSUE TITLE
Postgres timestamptz not working (datestyle paramater)

### ISSUE THREAD

**Issue by venca163** [sequelize/sequelize#6571]
Hello everyone, 

I have not been able to get it working, I have searched it deeply so I am trying to ask here:

Is it possible during connection (`new Sequelize(connstring, opts)`) to provide `dateStyle='ISO,MDY'` parameter, so this datestyle will be used for all queries? 

My DB server has set `dateStyle="SQL, MDY"` and if I query any column of type "timestamptz", sequelize is returning me null. If I change the param value manually (`ALTER DATABASE dbname SET datestyle TO "ISO, MDY"`) sequelize is returning the correct values for those "timestamptz" columns, but I can change it only on local database, not on production database.

I have tried to pass the argument durring the Sequelize object init

```
opts =
            logging: no
            databaseVersion: config.db.databaseVersion
            dialect: 'postgres'
            dateStyle: 'iso,mdy' # both here
            dialectOptions:
                dateStyle: 'iso,mdy' # and here
```

and also directly in Sequelize lib (in connection-manager.js):

```
connectionConfig.options = {};
connectionConfig.options.datestyle = '"ISO, MDY"';

var connection = new self.lib.Client(connectionConfig)
      , responded = false;
```

and also pass it as an argument in connection string in the same file:

```
connectionConfig = 'pg://user:password@localhost:5432/dbname?dateStyle=iso,mdy';
var connection = new self.lib.Client(connectionConfig)
      , responded = false;
```

but non of them seems to be working. I have also tried combinations like dateStyle/DateStyle/datestyle and iso,mdy/ISO,MDY/"iso,mdy" (letter size, quotes...) but no use.

I have also tried to call `SET datestyle TO "ISO, MDY"` as query just before the query retrieving values from timestamptz columns and it is surprisingly working only for the first time. (I have the endpoint for retrieving data -> I start server -> call the endpoint for the first time -> datetime value is correctly retrieved -> called it for the 2./3./4./... time -> null is retrieved).

```
sequelize.query('SET datestyle TO "ISO, DMY"')
.nodeify (err) ->
   return next err if err
   # do the data query in callback, getting "null"
```

If I query "show datestyle" right after the "set datestyle", it is working (returning correct timestamptz values), but it is very strange code:

```
sequelize.query('SET datestyle TO "ISO, DMY"')
.nodeify (err) ->
   return next err if err

   sequelize.query('show datestyle')
   .nodeify (err) ->
     return next err if err

     # do the data query in callback, getting correct values
```

I use node v4.2.6, sequelize 3.24.1, coffee 1.10.0.

I would be glad for any solution or word of advice.

Thank you,
Vaclav Hosticka

**Comment by janmeier** [comment]
The reason running a `SET datestyle` query only works the first time is that sequelize uses connection pooling, so you are not guaranteed to get the same connection each time. So you might be changing the datestyle on one connection, but the querying on another connection (I'm pretty sure datestyle is session dependent).

What you basically need is to run a query to set the datestyle each time a new connection is opened. For this we would need an `afterConnect` hook that is called [here](https://github.com/sequelize/sequelize/blob/32b7631761fd71e4fa4692f08881b935291477bd/lib/dialects/abstract/connection-manager.js#L234)

PR welcome - should be pretty straight forward
