### ISSUE TITLE
Better Error Message for unknown DataTypes

### ISSUE THREAD

**Issue by molerat619** [sequelize/sequelize#6574]
I have created a model like this one

![image](https://cloud.githubusercontent.com/assets/3458576/18390261/c88dd3fa-76a9-11e6-8bb5-f376a486f9b1.png)

and since `NUMBER` apparently is not a valid DataType, I got this error message:

![image](https://cloud.githubusercontent.com/assets/3458576/18390250/b2d2807e-76a9-11e6-8e15-8f60691c519f.png)

It took me 20 Minutes to find out that I had to change `NUMBER` to `INTEGER` because the error message does not help.

Thanks

**Comment by janmeier** [comment]
Try upgrading to latest version, then it should throw an error for undefined data types https://github.com/sequelize/sequelize/blob/93304e734830c2f1ff748ea6717ccf42d83ccb75/lib/model.js#L95

**Comment by felixfbecker** [comment]
The problem here is that `NUMBER` actually _is_ a valid data type: https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L175
