### ISSUE TITLE
JSON format for queries using "include"

### ISSUE THREAD

**Issue by brianmmorton** [sequelize/sequelize#6576]
First, thanks for the awesome library. Saves me a ton of time in my projects. I've had this problem for quite a while and made a bunch of workarounds, finally decided to just ask you guys. Thanks in advance!

Basically i want to query the db and include an association as nest json. EG:

```
User.findOne({
    raw: true,
    include: [{
      model: Company,
      as: 'company'
    }]
  })
```

What im getting is:

```
{
  id: 1234,
  name: 'Blah',
  company.id: 1234,
  company.name: 'blah blah'
}
```

I would expect:

```
{
  id: 1234,
  name: 'Blah',
  company: { 
    id: 1234,
    name: 'blah blah'
  }
}
```

What am i doing wrong here?

__Dialect:__ postgres 
__Database version:__ 9.5.2.0
__Sequelize version:__ 3.23.4

**Comment by brianmmorton** [comment]
Does this have to do with using raw?

**Comment by felixfbecker** [comment]
Yes, this is not supported why using raw. Is there any reason why you need raw?

**Comment by brianmmorton** [comment]
Perhaps not? My impression was that i should use raw when I am looking to only return json data. So typically in express I will query data with raw, then res.json(results). Do i not need raw in that case?

**Comment by felixfbecker** [comment]
No, not at all. You can just `JSON.stringify()` the result.

**Comment by brianmmorton** [comment]
Great. thanks for the help!

**Comment by felixfbecker** [comment]
No problem :)

**Comment by felixfbecker** [comment]
Oh, and if it wasn't clear, of course you can also just `res.json()` the result.

**Comment by rafaelvmedeiros** [comment]
another option is set: nest: true

where: {},
      raw: true,
      nest: true,
      attributes: ['cnpj', 'razao_social', 'inscricao_estadual'],
      include: [{}]
