### ISSUE TITLE
Slack invites?

### ISSUE THREAD

**Issue by OKNoah** [sequelize/sequelize#6579]
How do I get an invite to the Slack channel? Is there an auto-inviter?

**Comment by OKNoah** [comment]
Via IRC: http://sequelize-slack.herokuapp.com

Should be elsewhere maybe.

**Comment by felixfbecker** [comment]
there is a button in the readme.

**Comment by OKNoah** [comment]
@felixfbecker The only button I found goes straight to Slack, which asks for a username and password. You need an invite before you can sign in to the channel.

**Comment by OKNoah** [comment]
Here is a PR #6584
