### ISSUE TITLE
npm release?

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/sequelize#6580]
Just a request whether it'd be possible to push a new rc release to npm? There have been a lot of changes since 4.0.0-1 and I'm particularly keen to road test #6556 cls support.

Sorry if it's a palaver, but would be much appreciated if it's feasible.

Also, can anyone advise how stable master is at present (I mean how buggy, not how likely further breaking changes before 4.0.0 final)? I'm tempted to use it in production on one site to get the new features, but not sure how wise that is.

**Comment by felixfbecker** [comment]
@leebenson uses 4.0.0, maybe he can comment?

**Comment by leebenson** [comment]
So far, all my tests are passing. But the project I'm using it for is still in dev, so I couldn't comment about using it at scale in production.

**Comment by mickhansen** [comment]
I'm sure that @janmeier can push a new pre-release for 4.0 on monday

**Comment by janmeier** [comment]
`4.0.0-2`

**Comment by overlookmotel** [comment]
Thank @janmeier!

And thanks @leebenson @felixfbecker for the feedback on stability. I'll get it running on my dev machine, and then see if I dare to make the jump to production!

**Comment by felixfbecker** [comment]
Would like to hear your experience!
