### ISSUE TITLE
Cannot find module 'pg-native'  ver 3.23.6 

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#6581]
i found closed issue https://github.com/sequelize/sequelize/issues/3781 and get the same error on very simple model.findAll()

```javascript
instanceMethods: {
    getValues: async function(){
                let result= await Kopnik.findAll({
                    where:{
                        id:{
                            $in:IDs
                        }
                    },
                    order:[["path", "desc"]]
                });
    }
```

As I read in previous issue this error can be on client side inside browser (is it possible???). We use it on server side.

> Executing (default): SELECT "id", "email", "password", "name", "surname", "patronymic", "voiskoSize", "birth", "path", "note", "created_at", "updated_at", "deleted_at", "rodina_id", "starshina_id" FROM "Kopnik" AS "Kopnik" WHERE ("Kopnik"."deleted_at" IS NULL AND "Kopnik"."id" IN ('47', '4')) ORDER BY "Kopnik"."path" desc;
> Cannot find module 'pg-native'
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
> <--- Last few GCs --->
> 
>   181161 ms: Scavenge 1405.3 (1458.0) -> 1405.3 (1458.0) MB, 28.4 / 0 ms (+ 6.8 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
>   183565 ms: Mark-sweep 1405.3 (1458.0) -> 1405.3 (1456.0) MB, 2403.7 / 0 ms (+ 1342.2 ms in 2318 steps since start of marking, biggest step 788.0 ms) [last resort gc].
>   185996 ms: Mark-sweep 1405.3 (1456.0) -> 1405.3 (1458.0) MB, 2431.1 / 0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     2: arguments adaptor frame: 1->3
> Security context: 0xa93817b4629 <JS Object>
>     3: _stringify(aka _stringify) [/usr/lib/node_modules/mocha/lib/utils.js:495] [pc=0xd43d78151ab] (this=0xa93817041b9 <undefined>,val=0x318a4f46069 <String[7]: CASCADE>)
>     4: jsonStringify(aka jsonStringify) [/usr/lib/node_modules/mocha/lib/utils.js:507] [pc=0xd43d78159d7] (this=0xa93817041b9 <undefined>,object=0x358ae963d191 <an Object with map 0x70fecc0...
> 
> 
> Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by felixfbecker** [comment]
the stack trace isnt very useful...

**Comment by alexey2baranov** [comment]
that's all i see in console. First SQL line generates by Sequelize. Then 10 seconds of active work of eating all memory and then error message when memory out

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by michaeljota** [comment]
I have this issue. However, I'm using a, heavily modified, version of keunlee `sequelize-auto-ts`. 

I did not touch any in core, just change a few things to properly connect to the postgres database. But the files are generated with the same schema.

**Comment by michaeljota** [comment]
@alexey2baranov were you trying to require it with Electron or Webpack? 

I post the [issue](https://github.com/brianc/node-postgres/issues/1138) in [node-postgres](https://github.com/brianc/node-postgres) repo.

I don't know which part fail, but somewhere between Electron and Webpack make me apply comments in the ´index´ of the ´pg´ module.

**Comment by janmeier** [comment]
No [SSCCE](HTTP://SSCCE.ORG/) provided, closing
