### ISSUE TITLE
Support postgreSQL's EXCLUDE constraint 

### ISSUE THREAD

**Issue by alitaheri** [sequelize/sequelize#6582]
PostgreSQL has an [extension](https://www.postgresql.org/docs/9.5/static/ddl-constraints.html#DDL-CONSTRAINTS-EXCLUSION) to sql that creates exclusive indices like ( no overlapping ranges, no overlapping GIS shapes, etc ) using the gist indices. The syntax isn't all that complex. I would like to add this feature since we use it extensively and we would like it to be supported by sequelize. I only need to know if adding this feature is alright with the maintainers.

**Comment by felixfbecker** [comment]
I would be fine with it. Have youchecked if the other dialects support it in some form?

**Comment by jameskennethrobinson** [comment]
This would be a great thing to have!

**Comment by brianemoore57** [comment]
I am adding them manually myself right now.
