### ISSUE TITLE
[Model.build] [options.include] what does "See set" mean?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6583]
What do you mean?

![model - sequelize _ the node js _ io js orm for postgresql mysql sqlite and mssql - google chrome 2016-09-11 01 24 43](https://cloud.githubusercontent.com/assets/3880497/18412378/349bc352-77bf-11e6-85ec-83684ba22334.png)

**Comment by felixfbecker** [comment]
http://docs.sequelizejs.com/en/v3/api/instance/#setkey-value-options
