### ISSUE TITLE
Connection should be released to pool as soon as possible

### ISSUE THREAD

**Issue by janmeier** [sequelize/sequelize#6590]
Currently, the connection is only released after the result has been processed. 

The connection is released [here](https://github.com/sequelize/sequelize/blob/00bf32a398806a73a73638805f515810d170b3ce/lib/sequelize.js#L566), after `query.run` has finished.

As we can see [here](https://github.com/sequelize/sequelize/blob/00bf32a398806a73a73638805f515810d170b3ce/lib/dialects/postgres/query.js#L109-L275), the `run` promise is not resolved before the whole "what type of query is this and how should we format it"-dance is done.

I think moving the `releaseConnection` call inside `Query.run` should solve it

**Comment by felixfbecker** [comment]
But isn't all that code synchronous? Shouldn't have an impact on performance then

**Comment by janmeier** [comment]
It is, so other code won't be able to run once the data formatting has started (or can it, dunno if node preempts long running functions?)

But if we release the connection [here][(https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query.js#L109), before we start the formatting functions, a query waiting for an open connection will be able to claim the connection and set its query, before we start formatting the data

**Comment by felixfbecker** [comment]
I doubt thought that the query formatting is taking _that_ long compared to the actual release, as it has to go through the network. Have you run a benchmark before/after moving the statement?

**Comment by mickhansen** [comment]
@felixfbecker Query formatting can be a major bottleneck actually, especially when we're reducing large cartesian products

**Comment by felixfbecker** [comment]
Wait - is this the query generation or the handling of the result rows?

**Comment by mickhansen** [comment]
@felixfbecker handling of result rows, currently this blocks the connection release

**Comment by felixfbecker** [comment]
Yeah that can of course take some time 👍

**Comment by jeonghyeon-net** [comment]
why this issue closed?
