### ISSUE TITLE
queryInterface.removeColumn fails during migration 

### ISSUE THREAD

**Issue by hebinda** [sequelize/sequelize#6592]
## What you are doing?
I am trying to use below code to remove a column in migration

```js
queryInterface.removeColumn('Table1', 'column1');
```

## What do you expect to happen?
I am expecting column1 is removed after migration.

## What is actually happening?
column1 is still remaining.

_Output, either JSON or SQL_

Executing (default): SELECT CONSTRAINT_NAME as constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE (REFERENCED_TABLE_NAME = 'Table1' AND REFERENCED_COLUMN_NAME = 'column1' ) OR (TABLE_NAME = 'Table1' AND COLUMN_NAME = 'column1' )

__Dialect:__ mysql
__Database version:__ 5.7.12
__Sequelize version:__ 3.24.3

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by hebinda** [comment]
It looks like sequelize migration didn't wait until everything is done and terminated the process.
If worked after I turned all migration calls into Promise and wait for the end.
https://github.com/sequelize/sequelize/issues/1872#issuecomment-45474732
