### ISSUE TITLE
The update method executes the query even if no data to be saved

### ISSUE THREAD

**Issue by sberlinches** [sequelize/sequelize#6597]
Hi sequelize lovers.
I'm building an API with Sequelize 4.0 and Express and I'm stuck with this issue.

When the method gets the request data, the 'request.body' contains this JSON object.

``` js
{ 'field0':'some value' }
```

I have defined only these two fields to be saved, 'field1' and 'field2', of course they're defined in the model.

``` js
var values = request.body;
var options = {
  where: { id: request.params.id },
  fields: ['field1', 'field2']
};
Model.update(values, options);
```

And even there's no data to save, the method fires the execution. In this case the timestamp parameter is setted to true, that's why it updates the 'updated_at' field.

``` sql
Executing (default): UPDATE `table` SET `updated_at`='0000-00-00 00:00:00' WHERE `id` = '1'
```

In the case of the timestamp is setted to false, the method fires the execution anyway and the response catches an error.

``` sql
Executing (default): 
```

``` json
{
  "errors": {
    "name": "SequelizeDatabaseError",
    "message": "ER_EMPTY_QUERY: Query was empty",
    "parent": {
      "code": "ER_EMPTY_QUERY",
      "errno": 1065,
      "sqlState": "42000",
      "index": 0,
      "sql": ""
    },
    "original": {
      "code": "ER_EMPTY_QUERY",
      "errno": 1065,
      "sqlState": "42000",
      "index": 0,
      "sql": ""
    },
    "sql": ""
  }
}
```

In my opinion, the correct behaviour would be the no execution and a message error.

**Comment by felixfbecker** [comment]
So you do expect Sequelize to throw an error?

**Comment by sberlinches** [comment]
I expect that Sequelize at least doesn't execute an empty-lame query
