### ISSUE TITLE
Join on the same ForeignKey twice.

### ISSUE THREAD

**Issue by atodicebear** [sequelize/sequelize#6604]
## What you are doing?

``` js
return db.sequelize.query(`
    SELECT k.name as Name,
    k._id as _id,
    k.notice as notice,
    dv1.value as value1,
    dv2.value as value2,
    dv2._id as v_id,
    pk.product_id as pid
    FROM dict_Keys k
    LEFT JOIN dict_Values dv1 ON k._id=dv1.key_id and dv1.lang_id=` + req.params.id + `
    LEFT JOIN dict_Values dv2 ON k._id=dv2.key_id and dv2.lang_id=` + req.params.id2 + `
    LEFT JOIN ProductKey pk ON k._id= ` + 7 + `
    `, {
      type: Sequelize.QueryTypes.SELECT
    })
```
## What do you expect to happen?

At the moment Iam Joining twice on the same Foreignkey to get a Data twice.
I want to code this in the ORM norm but couldnt find a Solution to that.
## What is actually happening?

trying just to Include a Model twice

```
    return DictKey.findAll({
      attributes: ['name'],
      include :[{
          model : DictValue,
          where : {
            lang_id : req.params.id
          }
        },
        {
          model : DictValue,
          where: {
            lang_id : req.params.id2
          }
        }
      ]})
```

Correlation Error cause using DictValue twice.
If I declare two Different once with as then I have to create as well a second foreignKey for the second one and that is not wanted.

```
// If you need to join a table twice you can double join the same table
Team.hasOne(Game, {as: 'HomeTeam', foreignKey : 'homeTeamId'});
Team.hasOne(Game, {as: 'AwayTeam', foreignKey : 'awayTeamId'});
```

Is there an Easy Solution to that?

**Dialect:**  mssql 
**Database version:** server 2014
**Sequelize version:** 3.5.1

**Comment by janmeier** [comment]
Should be fixed with https://github.com/sequelize/sequelize/pull/6103

**Comment by felixfbecker** [comment]
How should this work if you don't provide separate aliases for the includes?

**Comment by janmeier** [comment]
Yeah, that's what I meant - It would work if you could provided different `as`'es - So you can  LEFT JOIN dict_Values dv1, LEFT JOIN dict_Values dv2` like in the raw query

**Comment by atodicebear** [comment]
Its been a while since I tried it so I dont remember which Error this gave me.
At the moment Busy with other things but will try this out and reply.
Still thanks for reply :)
