### ISSUE TITLE
Implementing Sequelize Model interface for custom data access

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6607]
I have this very wild idea. In a new (legacy) API I have a user model where the data is primarily saved in LDAP. Only the permissions are in a MySQL database. Currently, this is defined as a custom class, which is similar to a sequelize model: it has `find`, `findOne` etc with params like `where` and `attributes`.

For a new part of the API I want to use Sequelize. In that part there are a lot of models that reference users through the uid (1:n and n:m relations). Now, it would be nice to be able to setup actual associations to the user model, to use `include`.

So my idea was to make `User` inherit `Sequelize.Model`, but never call `init` and completely override the methods. I plan to implement a `find` method that implements a minimal Sequelize API. Then I could associate the model and use `include` - given that Sequelize will only ever use the stuff I actually implemented. Could this work?

**Comment by Noiwex** [comment]
Switch to bookshelf or knex
