### ISSUE TITLE
Postgres Json column query SQL: Should use #> instead of #>> ?

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6608]
I have a json object contains a boolean property:

``` json
{ where: { "a.b.c": { $or: [ { $eq: null }, { $ne: true } ] } } }
```

Then I got an error:
There is no operator for text <> boolean

sequelize generated wrong sql:

``` pg
"table"."a"#>>'{b,c}' = true
```

But if I change where option to

``` json
{ where: { "a.b.c": { $or: [ { $eq: null }, { $ne: "true" } ] } } }
```

it will not trigger error. Since `#>>` always using string type as result.

``` pg
"table"."a"#>>'{b,c}' = 'true'
```

---

So should sequelize use `#>` instead of `#>>`?
I think it should be:

``` pg
"table"."a"#>'{b,c}' = 'true'::jsonb
```

https://www.postgresql.org/docs/9.4/static/functions-json.html

**Comment by Noiwex** [comment]
Switch to bookshelf or knex
