### ISSUE TITLE
sequelize.query, join tables many to many, can i set attribute of array ?

### ISSUE THREAD

**Issue by fruct007** [sequelize/sequelize#6609]
_Is it possible to use sequelize.query with join tables with many to many relationships to get an array of attribute values ​​?_

## What you are doing?
Join tables many to many

```js
sequelize.query("select `user`.`name` as `user`, `roles`.`name` as `roles.name` from `users` left outer join (`roles_users` inner join `roles` on `roles`.`id` = `roles_games`.`role_id`) on `roles`.`user_id` = `user`.`id` ",{type: sequelize.QueryTypes.SELECT,nest: true})
```

## What do you expect to happen?
[{user:'sosic', roles:[{name:'Admin'},{name:'User'}]}] 

## What is actually happening?
[{user  : 'sosic',roles : { name : 'Admin' }},{user  : 'sosic',roles : { name : 'User' }}] 

__Dialect:__ mysql
__Database version:__ 5.7.13
__Sequelize version:__ 3.13.0

**Comment by felixfbecker** [comment]
That query looks very simple, any reason you are using a raw query for that?

In PostgreSQL you can use JSON functions, MySQL might have something similar.
https://medium.com/@felixfbecker/how-to-include-your-joins-as-object-arrays-in-postgresql-799df75a8542#.pnrnrjxrw

**Comment by fruct007** [comment]
_This is an example . Did not want to describe all the query, meaning would remain the same._

_Is it possible to get the same result using mysql?_
_When working with models with declared a relational context, we get the same result._

##For example:
_Select users and include roles by many to many associations_

```js
models.User.findAll({include:[{model:Role,as:'Roles'}]})
```
##return:
[{user:'sosic',Roles:[{name:'User'},{name:'Admin'}]}]

_Is exist the way to get the same using sequelize.query ?_

**Comment by felixfbecker** [comment]
not with a feature of sequelize, but with some kind of JSON / array_agg function I linked you already
