### ISSUE TITLE
i18n on validation

### ISSUE THREAD

**Issue by zion03** [sequelize/sequelize#6610]
Is I understand from https://github.com/sequelize/sequelize/issues/4361 the internationalization is still not implemented.

I trying to write i18n validation like:

     isEmail: {
          msg: i18n.__("Email")
        } 

But validation initialize once on start, so when I changing locale - this is doesn't work.

What about to provide opportunity write text like function?
Or you planing integrate i18n to sequelize in ?

     isEmail: {
          msg: function(){return i18n.__("Email");}
        }

When throw error check if  `msg` is function or not:

`throw new Error(test.msg() || 'Validation ' + validatorType + ' failed');` 
`throw new Error(test.msg || 'Validation ' + validatorType + ' failed');`

**Comment by felixfbecker** [comment]
you can define a custom validator:
```js
isEmail(value) {
  if (!isEmail(value)) {
    throw new Error(i18n.__('Email')
  }
}
```

**Comment by felixfbecker** [comment]
Closing as duplicate
