### ISSUE TITLE
targetKey setting for belongsToMany

### ISSUE THREAD

**Issue by hareshp** [sequelize/sequelize#6612]
## What you are doing?

I have a Bills table and Products table. The Bills and Product relation is m:n relationship.

``` js
Product.belongsToMany(models.Bill, {otherKey: 'PROD_ID', foreignKey: "BPD_ITEM_ID", through : models.BillProduct});
Bill.belongsToMany(models.Product, {otherKey: 'BLH_REFR_NO', foreignKey : "BPD_BILL_REFR", through : "BillProduct",});
```
## What do you expect to happen?

Now what is required is a table BILL_PRODUCT with columns BPD_BILL_REFR referring to BLH_REFR_NO in Bills, BPD_ITM_ID referring to PROD_ID in products.
## What is actually happening?

But the join table is always referring to primary keys of the tables id of Bill and id of product

Is it a bug in Sequelize or can this be achieved in a different way.
_Output, either JSON or SQL_

**Dialect:** mssql 
**Database version:** Sql Server 2014
**Sequelize version:** latest

**Comment by Noiwex** [comment]
Switch to bookshelf or knex

**Comment by felixfbecker** [comment]
@Noiwex if you continue to post this everywhere I will delete your comments.

**Comment by hareshp** [comment]
@felixfbecker basically i am working with legacy tables.....the tables `Bill`, 'Product' and 'BillProduct' are already created. M:N relation exists between `Bill` and `Product` hence the mapping table `BillProduct`....Now `BPD_ITEM_ID` in `BillProduct` maps to the column `PROD_ID` in `Product`, `BPD_BILL_REFR` in `BillProduct` maps to `BLH_REFR_NO`.
I am not able represent this relation in sequelize. hope it is clear??

**Comment by felixfbecker** [comment]
How did you define `Bill` and `Product`? Did you set `PROD_ID` as the primary key?

**Comment by hareshp** [comment]
@felixfbecker One solution that i got is defining `PROD_ID` as primary key in Product and `BLH_REFR_NO` as primary key in `Bill` and `Bill.removeAttribute('id')` and `Product.removeAttribute('id')` and giving foreignKeys as `BPD_ITEM_ID` and `BPD_BILL_REFR` then it is referring to respective columns. But then if i have to write M:N relation will it always refer to primary key only??

**Comment by felixfbecker** [comment]
I think so. [`belongsTo`](http://docs.sequelizejs.com/en/v3/api/associations/#belongstotarget-options) has a `targetKey` setting, apparently we dont have that for the other relations (or it is missing from the docs). If you want to submit a PR for that feel free.

But no matter what, in a symmetric relation `foreignKey` and `otherKey` must match.

**Comment by hareshp** [comment]
@felixfbecker Okk fine i will work on that and try to submit a PR for that....but i still didn't understand the solution u gave can u please elaborate with the present example then what does `otherKey` and `foreignKey` both refer to if they has to be same?

**Comment by felixfbecker** [comment]
If Model A belongsToMany C through B.
Then B has a `foreignKey` of `a_id` to `A.id` and an `otherKey` of `b_id` to `B.id`.

**Comment by hareshp** [comment]
what you are telling is to define the model B like `B.belongsTo(A, {foreignKey: 'a_id', otherKey: 'b_id'})`
not sure what definition of B should be?

**Comment by felixfbecker** [comment]
I need your model definitions to give you an example.
Did you read through http://docs.sequelizejs.com/en/v3/docs/associations/?

**Comment by felixfbecker** [comment]
For hasMany, this is tracked by #4258 (PR #5823)

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/sequelize/issues/4092
