### ISSUE TITLE
findAll WHERE, using previously defined sequelize.fn attribute

### ISSUE THREAD

**Issue by oliv23** [sequelize/sequelize#6616]
Hello,

I have two tables: **products** and **brands** and I am trying to fetch all brands where the associated product count is superior to 0.

So far I've been able to count the associated products and return that with the data as the attribute "product_count", using a **sequelize.fn**:

``` js
models.Brand.findAll({
    order: 'id ASC',
    attributes: ['id', 'name', 'slug', [sequelize.fn('COUNT', sequelize.col('products.id')), 'product_count']],
    include: [{model: models.Product, attributes:[]}],
    group: ['brand.id']
})
```

This creates the following query (which works perfectly):

``` SQL
SELECT "brand"."id", "brand"."name", "brand"."slug", COUNT("products"."id") AS "product_count" 
FROM "brands" AS "brand" 
LEFT OUTER JOIN "products" AS "products" ON "brand"."id" = "products"."brand_id" 
GROUP BY "brand"."id" 
ORDER BY id ASC;
```

Now, instead of returning all of the brands, I'd like to only return brands where the product count is superior to 0.
I tried this:

``` js
models.Brand.findAll({
    order: 'id ASC',
    attributes: ['id', 'name', 'slug', [sequelize.fn('COUNT', sequelize.col('products.id')), 'product_count']],
    include: [{model: models.Product, attributes:[]}],
    group: ['brand.id'],
    where: {
        'product_count': {
            $gt: 0
        }
    }
})
```

But it spits out an error:

``` json
{"error":{"name":"SequelizeDatabaseError","message":"column brand.product_count does not exist"}}
```

With the query being:

``` sql
SELECT "brand"."id", "brand"."name", "brand"."slug", COUNT("products"."id") AS "product_count" 
FROM "brands" AS "brand" 
LEFT OUTER JOIN "products" AS "products" ON "brand"."id" = "products"."brand_id" 
WHERE "brand"."product_count" > 0 
GROUP BY "brand"."id" 
ORDER BY id ASC;
```

Is it not possible to reference an attribute previously defined with **sequelize.fn** in the where?
Is there a solution that I am not aware of?

Thank you

**Comment by felixfbecker** [comment]
try `sequelize.where('product_count', {$gt: 0})`

**Comment by oliv23** [comment]
I used this: 

```
models.Brand.findAll({
    order: 'id ASC',
    attributes: ['id', 'name', 'slug', [sequelize.fn('COUNT', sequelize.col('products.id')), 'product_count']],
    include: [{model: models.Product, attributes:[]}],
    group: ['brand.id'],
    where: sequelize.where('product_count', {$gt: 0})
})
.then(function(brands) {
    console.log(brands);
})
.catch(function(err) {
    return reply({error: err});
});
```

Doesn't work.  Causes a blank error:
```
{
    "error": { }
}
```

**Comment by felixfbecker** [comment]
If you just JSON.stringify() the error, it will not include non-enumerable properties. Try to console.log it

Maybe `sequelize.where(sequelize.col('product_count'), {$gt: 0})`?

**Comment by oliv23** [comment]
My bad: the logged error was actually this:
`[TypeError: Cannot read property 'name' of undefined]`

Now, I tried using **sequelize.col('product_count')** and now it does run the query but spits out the following error:

```
error: {
    "name": "SequelizeDatabaseError",
    "message": "column \"product_count\" does not exist",
    [...]
}
```

**Comment by ramblingenzyme** [comment]
Try `sequelize.where(sequelize.fn('COUNT', sequelize.col('products.id')) '>', 0`
You can pass in an operator as a string as the second argument of `sequelize.where`.
Also you have to just copy paste the `sequelize.fn` call to create "product_count" instead of using the alias.
