### ISSUE TITLE
underscoredAll option not overriding underscored option

### ISSUE THREAD

**Issue by leroydev** [sequelize/sequelize#6619]
I'd expect `underscored` to be set to true when `underscoredAll` is set to true, but this is not happening. 
Code was written in order to support this, but the code was written incorrectly.
I'm talking about the following line of code:

```
this.underscored = this.underscored || this.underscoredAll;
```

Which is located in the following places in the following versions:
V4: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L761
V3: https://github.com/sequelize/sequelize/blob/v3/lib/model.js#L56
V2: https://github.com/sequelize/sequelize/blob/2.0/lib/model.js#L52

As you can see, it's trying to set `this.underscored` and is evaluating `this.underscored` and `this.underscoredAll`. It's supposed to be `this.options.*` though, as that's where those two options are located. Currently this line of code has no result.

Could someone confirm if `underscoredAll: true` should result in `underscored` being set to true or not? 

I'd be willing to make the pull request if it's supposed to work like this.

**Dialect:** any
**Database version:** any
**Sequelize version:** 2.x, 3.x & 4.x

**Comment by felixfbecker** [comment]
I think you are right. While this could be considered a bugfix it will be a breaking change though, so I would target it vor v4.

**Comment by overlookmotel** [comment]
According to the [API docs](http://docs.sequelizejs.com/en/v3/api/sequelize/), `underscored` and `underscoredAll` have different meanings:

* options.underscored - Converts all camelCased columns to underscored if true
* options.underscoredAll - Converts camelCased model names to underscored table names if true

So, according to that, `underscored` should not inherit from `underscoredAll`.

The [API docs](http://docs.sequelizejs.com/en/latest/api/sequelize/#class-sequelize) say that `model.options` should inherit from `sequelize.options.define`. And indeed it is so! https://github.com/sequelize/sequelize/blob/master/lib/model.js#L680

So if you want to turn on `underscored` option on all models by default `sequelize.options.define.underscored = true` is the place to do it.

I think the line you point out @leroydev `this.underscored = this.underscored || this.underscoredAll;` is incorrect usage and should be removed entirely. It's not doing anything, and what it's trying to do is wrong anyway!

**Comment by overlookmotel** [comment]
Really I'd say `underscoredAll` should be changed to a more descriptive name like `underscoredTables` to prevent confusion.

**Comment by felixfbecker** [comment]
@overlookmotel `underscoredAll` suggests that _both_ table names and column names should be underscored. `underscoreTableNames` suggests that _only_ table names are underscored. Maybe we can clear this up for v4 completely, so that `underscoreFields` underscores columns, `underscoreTableNames` underscores tables, and `underscore` underscores everything?

**Comment by overlookmotel** [comment]
@felixfbecker You're right that the name `underscoredAll` suggests everything should be underscored, but this is not what it says in the API docs, and neither is it what is implemented! Hence the confusion.

I like your suggesting of changing these property names so they reflect what they do. But:

1. `underscoreAttributes` might be better than `underscoreFields` - as it affects the naming *model* attributes, not table fields.
2. I'd suggest not making `underscored` underscore everything as this will be an unexpected breaking change for a lot of people.

I don't know if you missed off the "d" from the end of `underscored` intentionally, but it's a good idea anyway.

How about:

1. introduce new options `underscoreAttributes`, `underscoreTableNames` and `underscoreAll` (without a "d") which are what's used in the codebase and API docs.
2. Make the old options `underscored` (with a "d") and `underscoredAll` set the new options, and so retain BC (maybe with a deprecation warning)

**Comment by overlookmotel** [comment]
Optionally, could also add `underscoreFields` for database fields and `underscoreModelNames` too.

**Comment by overlookmotel** [comment]
@leroydev What do you think? And would you like to implement? It sounds like you're interested in this!

**Comment by felixfbecker** [comment]
Does it really underscore model attributes? The common use case we should support is having JavaScript attributes in camelCase, but column names underscored. I think introducing differently named options is a good idea, but deprecation warnings are a must.

**Comment by mickhansen** [comment]
I'd like to see something like naming strategies so it's easy, in one place, to decide that we want camelCase javascript side and snake_case db side.

**Comment by felixfbecker** [comment]
Yes, that would be the best. Would also clean up our code, no more `underscoredIf`
```js
namingStrategy: {
  tables: modelName => _.underscore(modelName),
  fields: fieldName => _.underscore(fieldName)
}
// shorthand
namingStrategy: name => _.pascalCase(name)
```

**Comment by overlookmotel** [comment]
Wait a second! Are you saying remove the `underscored` options entirely? I can speak as one user who wouldn't like that at all. I'm all about camelCase all the things! And anyone else who hasn't being used underscored would have to change all column names in their database.

**Comment by overlookmotel** [comment]
Oh sorry, I misunderstood. But I think your code example above should be:

```js
namingStrategy: {
  tables: modelName => _.underscore,
  fields: fieldName => _.underscore
}
// shorthand
namingStrategy: name => _.pascalCase
```

...unless I'm really missing the point?

**Comment by felixfbecker** [comment]
@overlookmotel No, `namingStrategy` would be a function that provides the name for the database. You could also write it like this:
```js
namingStrategy: _.underscore
```
I just wanted to highlight the parameter names so I wrote it in an arrow function.

**Comment by overlookmotel** [comment]
Doh! Sorry, I've only just managed to free my main project from the backwoods of node 0.12, so only started coding ES6 in the past week. Now I get you.

Yes, this sounds like a much better approach than all the `underscoredIf()` business.

So when an new model is created, Model constructor would include something like:

```js
this.options.namingStrategy = _.extend(
    {},
    this.sequelize.options.namingStrategy,
    this.options.namingStrategy
);
```
?

(So you can set a naming strategy per model too)

**Comment by felixfbecker** [comment]
Actually `Model.init()` would include that 😉  And of course you can set it per sequelize instance, that will work fine with lodash's deep merge. This would not only allow us more control over the casing used, but also over pluralizing. For example 
```js
namingStrategy: {
  tables: modelName => _.underscore(inflection.pluralize(modelName))
}
```
Things that could also have a naming strategy:
- foreign keys
- table names of through models
- foreign key constraints

In these more complex cases it might make sense to pass more info to the function, like the whole model instead of just the name.

**Comment by overlookmotel** [comment]
This sounds like an excellent solution to what's become a bit of a mess over time. I like it.

Do you think this could be done while maintaining BC with Sequelize v3 (i.e. the old API still works but deprecated)? I'd be wary of adding yet another feature that v4.0.0 has to wait for to be complete. It's been quite a long time in the works already and I understand v3 isn't under development any more so it's a bit of a limbo state for anyone not willing to use an unstable version (4.0.0-2).

**Comment by felixfbecker** [comment]
@overlookmotel I think this is a good idea. When `underscored` or `underscoredAll` are set, we could just set the namingStrategy to the (broken) behavior of v3.

**Comment by overlookmotel** [comment]
`sequelize.define()`, `Model.init()`... bah! You and your ES6 refactor!

By the way, what I was trying to say about inheritance was it'd be good if you could define `model.options.namingConvention` to over-ride defaults from `sequelize.options.namingConvention` (i.e. set options on a model-by-model basis).

Personally I think there should be as few options on the `Sequelize` *constructor* as possible, since `require('Sequelize')` is essentially a global.

And should the `namingConvention` option be set on `sequelize.options` or `sequelize.options.define`?

One other thing: should we be using merge on options? Or would `Object.create()` be better? Only difference is then `sequelize.options` can be mutated *after* models have been created and the new values would "update" options for all models. Not sure if there's really a use case for this. But it'd be good to be consistent everywhere.

**Comment by felixfbecker** [comment]
@overlookmotel Nobody is forced to use classes, or arrow functions, or object literal shorthands, or decorators, or async await :D

It should be on `options.define` since it is just a "default" option for models. We should use a merge because the options need to be merged deeply, Object.create() only merges shallow.

**Comment by overlookmotel** [comment]
@felixfbecker I was only joking about the ES6 thing. I'm slowing transitioning to classes etc myself and liking it. I'm just amused (in a friendly way) by your "ES6 everywhere!" stance.

Back to the point...

Yes, understand the need for deep merge, but could also do it using inheritance:

```
// in `Model.prototype.init`:

const globalOptions = this.sequelize.options.define;
if (options.namingConvention) options.namingConvention = Object.create( options.namingConvention, globalOptions.namingConvention);

// ... same as above for any other "deep" options ...

options = Object.create( options, globalOptions);
```

I guess whether deep merge or prototypal inheritance is better depends on which has better performance. Models are only created once but their options accessed often, so deep merge will likely be the winner.

But... my real point is that last time I looked there was a mixture in the codebase of some options being merged in from `sequelize.options.define` in model initialization, and some other places where it's left until a sequelize method (`model.find()`) to check the global sequelize options. e.g. methods starting with something like `options = _.extend({}, sequelize.options.define, options)`.

If this is still the case, it's inconsistent and also inefficient. I suggest that all model options should be set at the point that the model is attached to a sequelize instance, and then the global sequelize options should never need to be referenced again.

Am I making sense?

**Comment by felixfbecker** [comment]
100% agree 🙂

**Comment by kurtzilla** [comment]
Where did this end up? The documentation is confusing and does not work as advertised. Perhaps I am using the incorrect sequelize version (4.13.5)?

I find it necessary to use:
```
const sequelize = new Sequelize(DB_NAME, DB_USER, DB_PASSWORD, {
  dialect: 'postgres',
  define: {
    underscored: true,
  },
});
```
to make it work. The docs suggest that the define statement is no  longer necessary.

http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-init

**Comment by Rovack** [comment]
The discussion here seemed to have had some really good ideas, that would have avoided a lot of confusion.
Sad to see this seemingly closed without any actual results.

**Comment by sushantdhiman** [comment]
@Rovack https://github.com/sequelize/sequelize/issues/6423

**Comment by souserge** [comment]
[The docs](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-init) still say that `underscored` affects all camelCased columns, while in fact it does not.
