### ISSUE TITLE
Getting Started docs require a password

### ISSUE THREAD

**Issue by jcalfee** [sequelize/sequelize#6623]
http://docs.sequelizejs.com/en/stable/docs/getting-started/

**Comment by jcalfee** [comment]
Permission Denied

You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.

**Comment by sushantdhiman** [comment]
lol, only @janmeier can save us now :)

**Comment by sushantdhiman** [comment]
Oh just realized your url is worng @jcalfee, try this 
`http://docs.sequelizejs.com/en/v3/docs/getting-started/`

**Comment by jcalfee** [comment]
Thank you, that url came from the README.md...

**Comment by sushantdhiman** [comment]
@jcalfee Fixed in https://github.com/sequelize/sequelize/commit/f07b58a75e27c54eb704412c975618cd981a633d
