### ISSUE TITLE
_previousDataValues doesn't have the deletedAt property for restored paranoid model instances

### ISSUE THREAD

**Issue by Tyler-Murphy** [sequelize/sequelize#6624]
## What you are doing?

``` js
const Sequelize = require('sequelize')
const assert = require('assert')

const db = new Sequelize(process.env.DATABASE_URL, { dialect: 'postgres' })
const model = db.define('model', {}, { paranoid: true })

db.sync({ force: true })
.then(() => model.create())
.call('destroy')
.tap(instance => assert.notEqual(instance.dataValues.deletedAt, null))
.call('restore')
.tap(instance => assert.notEqual(instance._previousDataValues.deletedAt, null))
```

Run it with a `DATABASE_URL` environment variable. For example:

```
DATABASE_URL="postgres://localhost:5432/sequelize_test" node test.js
```
## What do you expect to happen?

I'd expect `_previousDataValues` for a restored paranoid instance to have the `deletedAt` property.
## What is actually happening?

`_previousDataValues.deletedAt` is `null`.

**Dialect:** Only tested for postgres
**Database version:** 9.5.3
**Sequelize version:** "sequelize": 3.24.3

**Comment by felixfbecker** [comment]
`_previousDataValues` is private, underscore-prefixed, undocumented API. You must not rely on it. That being said, all properties should be on there really.
