### ISSUE TITLE
Swap order of $between?

### ISSUE THREAD

**Issue by gigafied** [sequelize/sequelize#6625]
Is there anyway to swap the order of `$between`? i.e. I want to do something like this using `findAll())`

```sql
SELECT * FROM "events" WHERE "start" BETWEEN ${start} AND ${end} OR ${start} BETWEEN "start" AND "end"
```
Using postgres 9.4

**Comment by felixfbecker** [comment]
Please show what you tried and didn't work

**Comment by gigafied** [comment]
I want to do something like `SELECT * from bla WHERE start BETWEEN ${start} AND ${end} OR ${start} BETWEEN "start" AND "end"`
