### ISSUE TITLE
Rename field to column?

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#6627]
`foreignKeyField` vs `foreignKeyColumn` 
etc

**Comment by felixfbecker** [comment]
Where do we have a `foreignKeyField` option? Afaik its `foreignKey: { name: 'whateverId' }`
I also think column is a better choice but I am against change for the sake of change

**Comment by mickhansen** [comment]
It's come up in other thoughts about building something like `fieldMap` into `sequelize.query` for better raw query integration where i think `columnMap` makes more sense when thinking about RDBMS
