### ISSUE TITLE
Custom validation of len not working.

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#6628]
## What you are doing?

``` js
var Tag = sequelize.define("Tag", {
    name: {
      type: DataTypes.STRING,
      validate: {
        len: {
          args: [[0,32]],
          msg: 'Name too long.'
        }
      }
    }
  }
)
```
## What do you expect to happen?

I'm expection an error message like

```
errors:
   [ { message: 'Name too long',
       type: 'Validation error',
       path: 'name',
       ...
```
## What is actually happening?

No error is thrown. Nothing gets catched by Sequelize.ValidationError.

Without custom settings it works:

```
validate: {
        len: [0,32]
      }
```

throws a validation error.

sequelize: 3.24.3
node: 6.2.2
maria DB (Server version: 10.1.9-MariaDB Homebrew, Protocol version: 10)

**Comment by ro70** [comment]
I did a little bit of debugging myself and found this:

In lib/instance-validator.js on line 293 if I change
```
validatorArgs = validatorArgs.slice(0);
```
to
```
validatorArgs = validatorArgs[0];
```
then it works. But maybe this causes some other problems.

**Comment by ro70** [comment]
My fault. I'm sorry.

**Comment by bpaczkowski** [comment]
+1

I tested `len` and `is` and they both don't work for me, I need to use a custom validator instead.

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by bpaczkowski** [comment]
How does that work? Does it mock the db or do I need to configure it? It won't let me run the test, presumably because I don't have docker installed.

**Comment by felixfbecker** [comment]
Just give us a self-contained piece of code we can paste into that file to reproduce the issue.

**Comment by bpaczkowski** [comment]
I'm not sure if that's how it works but here you go: https://gist.github.com/bpaczkowski/1000839a3a5123a8cbde8ac79f6116da
This uses both `len` and `is` validations and the object I'm creating shouldn't pass any of them yet it does without any errors, according to my tests.

**Comment by ro70** [comment]
Here's the code:
```
var Sequelize = require('sequelize')
var sequelize = new Sequelize('...', '...', '...')

var Tag = sequelize.define("Tag", {
    name: {
      type: Sequelize.STRING,
      validate: {
        len: { // <- Not throwing an error.
          args: [[0,32]],
          msg: 'Name too long.'
        }
        // len: [0, 32] // <- Throws 'SequelizeValidationError: Validation error: Validation len failed'
      }
    }
  }
)

// Creating values.
sequelize.sync({force: true})
.then(function() {
  return Tag.create(
    {
      name: '0123456789012345678901234567890123456789'
    }
  )
})

// Catching errors...
.catch(function(err) {
  console.log(err)
})

```

**Comment by theo-ptz** [comment]
i have the same problem

**Comment by ro70** [comment]
@felixfbecker Code example is ready since about a month.

**Comment by sushantdhiman** [comment]
@ro70 you have been passing arguments incorrectly to the `args`, it needs to be single array.

From Sequelize docs http://docs.sequelizejs.com/en/v3/docs/models-definition/#validations

> Note that where multiple arguments need to be passed to the built-in validation functions, the arguments to be passed must be in an array. But if a single array argument is to be passed, for instance an array of acceptable strings for isIn, this will be interpreted as multiple string arguments instead of one array argument. To work around this pass a single-length array of arguments, such as  [['one', 'two']] as shown above.


**SSCCE Test**
```js
var Tag = sequelize.define("Tag", {
  name: {
    type: Sequelize.STRING,
    validate: {
      len: {
        args: [0, 6],
        msg: 'Name too long.'
      }
    }
  }
});

sequelize
  .sync({ force: true })
  .then(() => Tag.create({ name: 'qwertyqwertyqwerty'}))
  .then((t) => console.log(t.toJSON()))
  .catch(console.error);
```

**Output**
```js
Using database:  sequelize-test-39
{ SequelizeValidationError: Validation error: Name too long.
    at Promise.all.then (/var/www/github/sequelize/lib/instance-validator.js:76:15)
From previous event:
    at InstanceValidator._validate (/var/www/github/sequelize/lib/instance-validator.js:74:7)
    at modelInstance.constructor.runHooks.then (/var/www/github/sequelize/lib/instance-validator.js:95:16)
From previous event:
    at InstanceValidator.validate (/var/www/github/sequelize/lib/instance-validator.js:94:10)
    at model.validate (/var/www/github/sequelize/lib/model.js:3521:49)
    at Promise.try (/var/www/github/sequelize/lib/model.js:3321:21)
From previous event:
    at model.save (/var/www/github/sequelize/lib/model.js:3318:23)
    at Function.create (/var/www/github/sequelize/lib/model.js:1890:8)
    at sequelize.sync.then (/var/www/github/sequelize/sscce_template.js:26:19)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```
