### ISSUE TITLE
Feature request: .transaction should accept an options.transaction parameter

### ISSUE THREAD

**Issue by rbalicki2** [sequelize/sequelize#6633]
I have class functions on certain models that take an optional `options` object, which may include a transaction. If so, I want all of the model updates to be included in that transaction. If not, I want the model updates to be in their own transaction. Currently, I am implementing that as:

```
Model.updateExisting = (id, options) => {
  DB.transaction(transaction =>
    Model.update(updates, {
      transaction,
      ...options
    }).then(...)
  )
};
```

If I pass in a transaction, this creates a dummy (empty) transaction. I doubt there are many performance penalties, but it would be nice if `.transaction` took a transaction as an object, and just passed it through if one was passed in.

Thank you for this amazing library

FWIW I'm on 3.21 with postgres 9.5

EDIT: I noticed in the code it explicitly deletes the transaction, so I assume this is a design decision?

**Comment by felixfbecker** [comment]
I don't get your feature request. If you do a query without explicit BEGIN/COMMIT, your DB will actually automatically be in _autocommit mode_. E.g. it will implicitly automatically _commit_ every query. Doing a BEGIN just switches this autocommit mode off, so you have to commit manually. There should be no performance impact.

**Comment by rbalicki2** [comment]
Hi felix,

The proposed feature could be implemented (by the user of Sequelize) as follows:

```
Model.doSomething = (id, options) => {
  const modifyTheModel = (childOptions) => Model.update(updates, childOptions).then(...);
  if (options.transaction) {
    // doSomething is called in the context of a transaction; there is no need to 
    // create a transaction.
    return modifyTheModel(options);
  }

  // else: doSomething is not called within a transaction. Create one.
  return DB.transaction(transaction => modifyTheModel({ ...options, transaction });
}
```

If sequelize implemented this, the above behavior would have the following api:

```
DB.transaction(innerTransaction => {}, { transaction, ...otherOptions })
```

If the second parameter included a `transaction` key, then `options.transactions` would equal `innerTransaction`.

This could be considered a backwards incompatible change, so perhaps naming the method `optionalTransaction` or something could work.

**Comment by felixfbecker** [comment]
You could just use recursion
```js
static doSomething(id, options) {
  if (!options.transaction) return sequelize.transaction(() => this.doSomething(id, options))
  return Model.update(updates, childOptions)
}
```

**Comment by rbalicki2** [comment]
Yup, sounds good to me. Anyway, it's definitely not crucial that this functionality be within Sequelize. It could also be handled as a decorator
