### ISSUE TITLE
belongsToMany not work?

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6635]
I have two table "cat" & "item",single cat can has many item,single item can belongs to many cat.i want can setItems in cat model,but not want edit cat in item model,so i define model as below:
```
let Item = sequelize.define('item', {name: { type: Sequelize.STRING, allowNull: false, field: 'fname' }});
let Cat= sequelize.define('cat', {name: { type: Sequelize.STRING, allowNull: false, field: 'fname' }});
Item.belongsToMany(Cat, { as: 'items',through: 'cat_item'});

Cat.findOne({where:{id:1}}).then(cat=>{
    console.log(cat.name);//ok! 
    cat.setItems([1,2,3]);//error!
})
```
when I run then get error:
`TypeError: rst.setItems is not a function`

**Comment by janmeier** [comment]
You need to set up the reverse relation ( `Cat.belongsToMany(Item, { as: 'items' , through: 'cat_item' })`)

For the Item <-> Cat relation the alias should probably be something like `cats` or similar, see http://docs.sequelizejs.com/en/v3/docs/associations/#belongs-to-many-associations

**Comment by keyiis** [comment]
@janmeier I added reverse relation,but still get same error
```
let Item = sequelize.define('item', {name: { type: Sequelize.STRING, allowNull: false, field: 'fname' }});
let Cat= sequelize.define('cat', {name: { type: Sequelize.STRING, allowNull: false, field: 'fname' }});
Item.belongsToMany(Cat, { as: 'items',through: 'cat_item'});
Cat.belongsToMany(Item, { as: 'cats',through: 'cat_item'});

Cat.findOne({where:{id:1}}).then(cat=>{
    console.log(cat.name);//ok! 
    cat.setItems([1,2,3]);//error!
})
```

**Comment by janmeier** [comment]
You need to reverse the `as` (Cat BTM Item as items and vice verca) - from the example:

```js
User.belongsToMany(Project, { as: 'Tasks', through: 'worker_tasks', foreignKey: 'userId' })
Project.belongsToMany(User, { as: 'Workers', through: 'worker_tasks', foreignKey: 'projectId' })
```

**Comment by felixfbecker** [comment]
You have the aliases switched. Should be Item belongsToMany Cat as cats

**Comment by keyiis** [comment]
@janmeier @felixfbecker thks!this problem has solved. but i try access items through "cat.items",
```
Object.assign({},options,{include:{ model: Item,as:'items' }});
sequelize.findOne('Cat', options).then(cat=>{
    console.log(cat.item);//no property error!
})
```

**Comment by janmeier** [comment]
Your relation is called `items`, so you need to access `cat.items`...

**Comment by keyiis** [comment]
@janmeier sorry,that was a typo.
```
Object.assign({},options,{include:{ model: Item,as:'items' }});
sequelize.findOne('Cat', options).then(cat=>{
    console.log(cat.items);//no property error!
})
```
![qq 20160926172842](https://cloud.githubusercontent.com/assets/7766085/18829437/cc27f5dc-840e-11e6-9cf0-435330cdf755.jpg)

**Comment by janmeier** [comment]
Include should be an array -  does the query look correct?  Try `cat.get()` to see all attributes on the row.

This is really not the correct forum for this kind of support - Please join us on slack, or pose your question on SO instead

**Comment by keyiis** [comment]
@janmeier ok,i am dowloading slack,i already change Include to array,
`Object.assign({},options,{include:[{ model: Item,as:'items' }]});`
but still can't get items,below is cat.get()
![qq 20160926173954](https://cloud.githubusercontent.com/assets/7766085/18829770/6893f8b6-8410-11e6-940e-d4776c400b1e.jpg)
