### ISSUE TITLE
sending a different queries  from client side(json format) and execute the same service and get the response 

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#6639]
options.where = {
            hp_builders_id: builders_id
}

options.include = [{
            model: hp_builders,
            required: true
        }, {
            model: hp_country,
            attributes: ['country_id', 'country_name'],
            required: true
        }, {
            model: hp_city,
            attributes: ['city_id', 'city_name'],
            required: true
        }, {
            model: hp_location,
            attributes: ['location_id', 'location_name'],
            required: true
        }]... many inner joins

   
 app.get('/v1/project-listing', function(req, res) {
 hp_property.findAll(options).then(function(result) {
});
});

so here i want perform dynamic queries like

 dynamic queries:

/app/v2/project-listing?selector={"filters":{"and":[{"equal":{"cityLabel":"hyderabad"}}]}
,"paging":{"start":0,"rows":5}}

/app/v2/project-listing?selector={"filters":{"and":[{"equal":{"builderId":100002}},{"equal":{"builderId":100002}}]}
,"paging":{"start":0,"rows":15}}

/app/v2/project-listing?selector=
{"filters":{"and":[{"equal":{"cityId":2}},{"equal":{"localityId":50175}},{"equal":{"suburbId":10008}},{"equal":{"cityId":2}},{"equal":{"localityId":50175}},{"equal":{"suburbId":10008}}]},"paging":{"start":0,"rows":15}}

__Dialect:__ mysql 
__Sequelize version:__ 2.0.2

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by SIMHACHALAM1001** [comment]
hey give atleast a small approach

**Comment by janmeier** [comment]
Hey, give me at least an idea of what you want to do? 

As mentioned, this is really not the right forum for "how do I do this?" type of questions. Please use the appropriate channels

**Comment by SIMHACHALAM1001** [comment]
ya.
 i created one service using sequalize is good .its working fine but i want to filter in particular scenarious to same service 
so i want to perform as where condtion in different scenarious.for example:
var options;
options.where = {
hp_builders_id: builders_id
}
so here iam sending builders_id from client side its working,
In some other scenaroius after getting details particular builder_id in some bed rooms only like(bedrooms:[1bhk/2bhk,3bhk])
In some other scenaroius after getting details particular builder_id in some bed rooms with cost only like(cost: (2lakhs ,3lakhs,4crs))
 but i want to utilize the same service

app.get('/v1/project-listing', function(req, res) {
hp_property.findAll(options).then(function(result) {
});
});

**Comment by SIMHACHALAM1001** [comment]
so from client side i wiil take like this 
{"filters":{"and":[{"equal":{"builderId":100002}},bedrooms:[1,2,3]]}
,"paging":{"start":0,"rows":15}}

**Comment by felixfbecker** [comment]
Your question is unclear, your code is unreadable and this is neither a bug nor a feature request. Use SO.
