### ISSUE TITLE
About multiple tables query and the usage of hasMany

### ISSUE THREAD

**Issue by yangjiedage** [sequelize/sequelize#6646]
## What you are doing?

```
 classMethods: {
            associate: function(models) {
                _this.hasMany(models.EmployeeFile, {                
                    foreignKey:'employees_code'                                  
                });
            }
        },


router.get('/employee', function(req, res) {
    models.EmployeeView.findAll({
        where: {
            active: req.query.active
        },
        include: [ {
            model: models.EmployeeFile,
        }]
    }).then(function(employee) {
        res.json(employee);
    });
});

```

## What do you expect to happen?
I have 'employee' table and 'employee_files' table in my database.  'employees_code' is the field in 'employee_files'  as primary key and it is also the foreignKey which matches 'code' field in 'employee'.
So I want to get the data through the relation. 

## What is actually happening?
Actually,I got nothing. Because the sequelize will execute "employee.id == employee_files.employees_code". But I want the sequelize to execute "employee.code == employee_files.employees_code" .What should I do?

__Dialect:__ mysql

**Comment by felixfbecker** [comment]
This question is more suited for StackOverflow or Slack. You also need to show more code.
