### ISSUE TITLE
Complex forms with Sequelize

### ISSUE THREAD

**Issue by equicolor** [sequelize/sequelize#6647]
Hello! I'm new to Sequelize and I have an issue. I try to create REST action that will save model with associated multiple child models. And my code is uggly, in MVC terms it called "Fat Stupid Ugly Controllers". I figured out that I need some pseudo-model that do not connect with db, performs validation and saves own models. It represents form. This is typical task but I cant find some example implementation for Sequelize. All I found was a promise chaining in actions and it looked ugly. I will be glad any hint!

The result of my attempts
```
router.post('/', async(req, res, next) => {
    try {
      let goals
      const
        // load parent model by request data...
        offer = Offer.build(getReqData(req.body, ...Offer.safeAttributes())),
        goalsData = req.body.goals

      if (goalsData && goalsData instanceof Array) {
        goals = goalsData.map(goal => {
          return Goal.build(goal);
        })
      } else {
        next(new HttpError(405))
      }

      if (req.body.validate) {
        let offerErrors = await offer.validate({skip: ['token']})
        if (offerErrors) {
          offerErrors = utils.reduceErrors(offerErrors.errors);
        }
        const promises = [];
        goals.map(goal => {
          promises.push(goal.validate())
        })
        Bluebird.all(promises).spread((...errors) => {
          // TODO: send validation errors
          errors.map(err => console.log(err.errors))
        })
      } else {
        offer.save()
          .then(offer => {
            // TODO: Goals saving
            res.status(201).send(offer)
          })
          .catch(err => next(err))
      }
    } catch (e) {
      next(e)
    }
  })
```

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
