### ISSUE TITLE
Crash when serializing result with multiple-nested models without attributes

### ISSUE THREAD

**Issue by daniel-pedersen** [sequelize/sequelize#6649]
When sequelize tries to serialize the result of a query returning an instance within an instance (with no attributes), within an instance (with no attributes), it fails with the following error:
`TypeError: Cannot set property 'C' of undefined`

Probably a hidden assumption that there must be at least one attribute included in each included instance somewhere in the code. Notably, with only one nested instance, sequelize manages it, but fails with two or more.

Below is a minimal example showing the problem, one would expect to get the following output in the console, but instead gets the error above.

```
[{
  B: {
    C: {
      x: "hello"
    }
  }
}]
```

**Code:**

``` js
/* ----- SETUP ----- */

const Sequelize = require("sequelize")

const db = new Sequelize("mysql://localhost:3306/test")

const A = db.define("A")
const B = db.define("B")
const C = db.define("C", {
  x: Sequelize.STRING
})

A.belongsTo(B)
B.hasOne(C)

db.query("SET FOREIGN_KEY_CHECKS = 0")
  .then(() => db.sync({ force: true }))
  .then(() => A.create())
  .then(a => a.createB())
  .then(() => B.findById(1))
  .then(b => b.createC({ x: "hello" }))

/* ----- PROBLEM STARTS HERE ----- */

  .then(() => A.findAll({ attributes: [], include: [{ attributes: [], model: B, include: [{ model: C, attributes: ["x"] }] }] }))
  .then(x => console.log(x.toJSON()))

```

**Dialect:** mysql
**Database version:** 5.7.13
**Sequelize version:** 3.24.3

**Comment by felixfbecker** [comment]
you are calling `toString()` on the array resolved by `findAll()`. What are you trying to accomplish with this?

**Comment by daniel-pedersen** [comment]
Not really relevant as it's still a bug, but in our case it is to be returned from our API backed by Sequelize on top of a legacy database.

I know it's a very arcane example, but our API is flexible enough to produce cases like this.

**Comment by daniel-pedersen** [comment]
After some investigating I've found that the problem is that `groupJoinData` in [query.js](/sequelize/sequelize/blob/v3.24.3/lib/dialects/abstract/query.js#L59) assumes that the rows returned will contain attributes at every level of depth up to the deepest level. This assumption only holds when the depth is 2 or less, because [this code in model.js](https://github.com/sequelize/sequelize/blob/v3.24.3/lib/model.js#L1367-L1370) ensures the root attributes array is never empty, instead it tacks on the `primaryKeyAttribute`, which is filtered out after the result has been passed to `groupJoinData`.

The problem is that the `primaryKeyAttribute` is not force added in this way for nested instances, which means a nested model can go without any attributes, fatally breaking the assumption in `groupJoinData`. For example in my post the row contains columns `['id','B.C.id','B.C.x']`, missing any direct attribute of `B`. If we add the `id` attribute for model `B` in the code above the problem goes away (the returned row contains `['id','B.id','B.C.id','B.C.x']`), since the assumption is again fulfilled.

Now, there are a few places where one can force the `primaryKeyAttribute` of nested models with further nested models, such as right after [here in query-generator.js](/sequelize/sequelize/blob/v3.24.3/lib/dialects/abstract/query-generator.js#L1129), wrapped in an `if (include.include && include.attributes.length === 0)`. This attribute will then simply be filtered when the result returns just as with the root attributes.

**Comment by felixfbecker** [comment]
@daniel-pedersen Thanks for investigating. I think it would be a great idea to implicitly include the `primaryKeyAttribute` for included models as well, and any foreign key that is also needed to make the JOIN. PR welcome! :)

**Comment by juniorh2o** [comment]
Same problem here, I was using version 3.0.0. and query with empty attributes used to work
{
model: db.User,
    attributes: [],
    required: true,
    include: {
        model: db.Test
    }
}

After updating to 3.25.0, in order to work I had to add the primary to attributes list, so the objects won't be undefined:

model: db.User,
    attributes: ['id'],
    required: true,
    include: {
        model: db.Test
    }
