### ISSUE TITLE
dialectOption 'log' not used for postgres

### ISSUE THREAD

**Issue by andreas-wagner** [sequelize/sequelize#6653]
I am using `postgres` with [npm:pg](https://www.npmjs.com/package/pg) (or [github:brianc/node-postgres](https://github.com/brianc/node-postgres)) and it has the option to assign a [logger](https://github.com/brianc/node-postgres/blob/master/lib/index.js#L67).

I checked `dialects/postgres/connection-manager.js` and found that you are very [picky](https://lodash.com/docs/4.16.2#pick) about config settings as you only take ['user', 'password', 'host', 'database', 'port'](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L60) and ['application_name', 'ssl', 'client_encoding', 'binary'](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L65).

Can you do a very small update that would also accept 'poolLog' and/or 'log'?
This way we could log what pg does.

Thank you!

**Comment by sushantdhiman** [comment]
We use our own pool, if you want logging you can pass `DEBUG=sequelize`

**Comment by janmeier** [comment]
If you look a couple of lines further down you'll see `dialectOptions`

**Comment by andreas-wagner** [comment]
@janmeier that would be here  ['application_name', 'ssl', 'client_encoding', 'binary'](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L65).

@sushantdhiman I will try that

**Comment by janmeier** [comment]
Ah, sorry - Other dialects pass all options through, but not postgres appearently :)

**Comment by andreas-wagner** [comment]
@sushantdhiman `DEBUG=sequelize` does not seem to do anything.

**Comment by janmeier** [comment]
Which version are you on? debug support is only implemented in v4
