### ISSUE TITLE
Parent association still created even if child association fails validation

### ISSUE THREAD

**Issue by scf4** [sequelize/sequelize#6657]
I have a model `Thread` which `hasMany()` of a model called `Post`.

If I do something like `Thread.create({ title: 'Blah', posts: [{ content: '' }]  }` then my Post content's `notEmpty:true` validator fails, but the thread row is still created when I look in the database.

How can I ensure Post validators pass before saving the Thread?

**Comment by felixfbecker** [comment]
What are you passing as `options`? Are you using a transaction?

**Comment by scf4** [comment]
Options are `{ include: [Post] }`

Is a transaction the only way to do it, or can we validate both before creating either?

**Comment by felixfbecker** [comment]
Not sure. Try it
