### ISSUE TITLE
handling different requests from angularjs to nodejs single service using sequelize literal?

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#6659]
JSON data request from client side in different ways like this 
[![enter image description here][1]][1]

client requests from angular  as filters with different parameters to single service which is in node Js.So this nodejs code handle all these requests. based on request. i have to give the response.

my nodejs code:

    app.get('/v1/project-listing', function(req, res) {
        var country_id = 1;
        var filter;
        var options = {};
        var row = 4;
        var perPage = 1;
        var page = 1;
        var results;
        var items = [];
        var builders;
        var locality = {};
        var dummy = [];
        var hp_Unit_Details;
        var hp_Unit_Types;
        var hp_Unit_Prices;
        var propertyName;
        var bedrooms;
    
        options.where=getcondition(req,Sequelize);
    
        var maxRange=4479558;
        var minRange=0;
    
        options.include = [{
            model: hp_builders,
            required: true
        }, {
            model: hp_country,
            attributes: ['country_id', 'country_name'],
            required: true
        }, {
            model: hp_city,
            attributes: ['city_id', 'city_name'],
            required: true
        }, {
            model: hp_location,
            attributes: ['location_id', 'location_name'],
            required: true
        }, {
            model: hp_sub_location,
            attributes: ['sub_location_id', 'sub_location_name'],
            required: true
        }, {
            model: hp_gallery,
            attributes: ['gallery_id', 'gallery'],
            required: true
        }, {
            model: hp_property_inhibition_status,
            required: true
        }, {
            model: hp_property_availability,
            required: true
        }, {
            model: hp_unit_details,
            required: true,
            include: [{
                model: hp_unit_type,
                attributes: [
                    [Sequelize.fn('concat', Sequelize.literal("`hp_unit_details.hp_unit_type`.`unit_type_name`"), '+', Sequelize.literal("`hp_unit_details`.`no_toilet_available`"), 'T'), 'UnitName'],
                    'unit_type_name',
                    'unit_type_id',
                    'unit_type_status'
                ],
                required: true
            }, {
                model: hp_unit_price,
                attributes: [
                    [Sequelize.literal("`hp_unit_details.hp_unit_prices`.`price_per_sqft`  * `hp_unit_details`.`property_size`"), 'UnitPrice'],
                    'price_per_sqft',
                    'hp_property_id',
                    'unit_price_id'
                ],
                required: true
            }],
    
        }];
    
        hp_property.findAndCountAll(options).then(function(result) {
            results = JSON.parse(JSON.stringify(result.rows));
            console.log(JSON.stringify(result));
    
    
            for (var property in results) {
                builders = results[property].hp_builder;
                hp_Unit_Details = results[property].hp_unit_details;
    
    
                items.push({
                    builders: builders,
                    propertyId: results[property].property_id,
                    hp_builders_id: results[property].hp_builders_id,
                    property_name: results[property].property_name,
                    property_start_date: results[property].property_start_date,
                    property_completion_date: results[property].property_completion_date,
                    property_launch_date: results[property].property_launch_date,
                    total_launched_apartments: results[property].total_launched_apartments,
                    total_property_area: results[property].total_property_area,
                    property_description: results[property].property_description,
                    property_latitude: results[property].property_latitude,
                    property_longitude: results[property].property_longitude,
                    property_status: results[property].property_status,
                    created_date: results[property].created_date,
                    update_date: results[property].update_date,
                    hp_sub_location: results[property].hp_sub_location,
                    hp_location: results[property].hp_sub_location,
                    hp_gallery:results[property].hp_gallery,
                    properties: []
                });
                for (var hp_unit_detail in hp_Unit_Details) {
    
                    hp_Unit_Types = hp_Unit_Details[hp_unit_detail].hp_unit_type;
                    hp_Unit_Prices = hp_Unit_Details[hp_unit_detail].hp_unit_prices;
    
                    for (var Unitprice in hp_Unit_Prices) {
                        console.log(hp_Unit_Types.unit_type_name);
    
                        if(hp_Unit_Types.unit_type_name == "1 BHK"){
                            bedrooms=1;
                        }
                        else if (hp_Unit_Types.unit_type_name == "2 BHK"){
                            bedrooms=2;
                        }
                        else if (hp_Unit_Types.unit_type_name == "3 BHK"){
                            bedrooms=3;
                        }
                        else if (hp_Unit_Types.unit_type_name == "4 BHK"){
                            bedrooms=4;
                        }
                        else if (hp_Unit_Types.unit_type_name == "4BHK villas") {
                            bedrooms=0;
                        }
    
                        propertyName = results[property].property_name;
                        if (items[property].property_name === propertyName) {
                            items[property].properties.push({
                                UnitName: hp_Unit_Types.UnitName,
                                property_size:hp_Unit_Details[hp_unit_detail].property_size,
                                bedrooms:bedrooms,
                                unit_type_name: hp_Unit_Types.unit_type_name,
                                unit_type_status: hp_Unit_Types.unit_type_status,
                                UnitPrice: hp_Unit_Prices[Unitprice].UnitPrice,
                                price_per_sqft: hp_Unit_Prices[Unitprice].price_per_sqft,
                                hp_property_id: hp_Unit_Prices[Unitprice].hp_property_id,
                                unit_price_id: hp_Unit_Prices[Unitprice].unit_price_id
                            });
                        } else {
                            items[property].properties.push({
                                UnitName: hp_Unit_Types.UnitName,
                                property_size:hp_Unit_Details[hp_unit_detail].property_size,
                                bedrooms:bedrooms,
                                unit_type_name: hp_Unit_Types.unit_type_name,
                                unit_type_status: hp_Unit_Types.unit_type_status,
                                UnitPrice: hp_Unit_Prices[Unitprice].UnitPrice,
                                price_per_sqft: hp_Unit_Prices[Unitprice].price_per_sqft,
                                hp_property_id: hp_Unit_Prices[Unitprice].hp_property_id,
                                unit_price_id: hp_Unit_Prices[Unitprice].unit_price_id
                            });
                        }
                    }
                }
            }
            return res.json({
                items: items
            });
        });
    });

   getting request to this getcondition (req,Sequelize) method by using this method, i am returning where condition in different ways 

        function getcondition(req,Sequelize) {
    condition={};
    
        
     return condition;
    }

so  how can i handle these requests in this getcondition() method for different type of requests 
 
i tried but  i am writing so many if conditions 

[![enter image description here][2]][2]

 

  [1]: http://i.stack.imgur.com/DiBHu.png
  [2]: http://i.stack.imgur.com/6kXUo.png

**Comment by sushantdhiman** [comment]
Please provide a SSCCE ( [What is SSCCE ?](http://sscce.org), [How to create one in Sequelize ?](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )
