### ISSUE TITLE
handling different requests from angularjs to nodejs single service using sequelize literal?

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#6660]
JSON data request from client side in different ways like this 
[![enter image description here][1]][1]

client requests from angular  as filters with different parameters to single service which is in node Js.So this nodejs code handle all these requests. based on request. i have to give the response.

my nodejs code:

    app.get('/v1/project-listing', function(req, res) {
        var country_id = 1;
        var filter;
        var options = {};
        var row = 4;
        var perPage = 1;
        var page = 1;
        var results;
        var items = [];
        var builders;
        var locality = {};
        var dummy = [];
        var hp_Unit_Details;
        var hp_Unit_Types;
        var hp_Unit_Prices;
        var propertyName;
        var bedrooms;
    
        options.where=getcondition(req,Sequelize);
    
        var maxRange=4479558;
        var minRange=0;
    
        options.include = [{
            model: hp_builders,
            required: true
        }, {
            model: hp_country,
            attributes: ['country_id', 'country_name'],
            required: true
        }, {
            model: hp_city,
            attributes: ['city_id', 'city_name'],
            required: true
        }, {
            model: hp_location,
            attributes: ['location_id', 'location_name'],
            required: true
        }, {
            model: hp_sub_location,
            attributes: ['sub_location_id', 'sub_location_name'],
            required: true
        }, {
            model: hp_gallery,
            attributes: ['gallery_id', 'gallery'],
            required: true
        }, {
            model: hp_property_inhibition_status,
            required: true
        }, {
            model: hp_property_availability,
            required: true
        }, {
            model: hp_unit_details,
            required: true,
            include: [{
                model: hp_unit_type,
                attributes: [
                    [Sequelize.fn('concat', Sequelize.literal("`hp_unit_details.hp_unit_type`.`unit_type_name`"), '+', Sequelize.literal("`hp_unit_details`.`no_toilet_available`"), 'T'), 'UnitName'],
                    'unit_type_name',
                    'unit_type_id',
                    'unit_type_status'
                ],
                required: true
            }, {
                model: hp_unit_price,
                attributes: [
                    [Sequelize.literal("`hp_unit_details.hp_unit_prices`.`price_per_sqft`  * `hp_unit_details`.`property_size`"), 'UnitPrice'],
                    'price_per_sqft',
                    'hp_property_id',
                    'unit_price_id'
                ],
                required: true
            }],
    
        }];
    
        hp_property.findAndCountAll(options).then(function(result) {
  
            return res.json({
                items: items
            });
        });
    });

   getting request to this getcondition (req,Sequelize) method by using this method, i am returning where condition in different ways 

        function getcondition(req,Sequelize) {
    condition={};
    
        
     return condition;
    }

so  how can i handle these requests in this getcondition() method for different type of requests 
 
i tried but  i am writing so many if conditions 

[![enter image description here][2]][2]

 

  [1]: http://i.stack.imgur.com/DiBHu.png

**Comment by sushantdhiman** [comment]
@SIMHACHALAM1001 Dont duplicate same issues. What you want is a coding help that I am afraid we cant offer. If you think you have found any bugs please produce a clear description or SSCCE.

Please provide a SSCCE ( [What is SSCCE ?](http://sscce.org), [How to create one in Sequelize ?](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

**Comment by felixfbecker** [comment]
I want to add, this is also not a question that is related to Sequelize. Your question boils down to "how can I transform an object of this form into an object of this other form" which is just basic JavaScript.

**Comment by SIMHACHALAM1001** [comment]
just give some small approach code man
