### ISSUE TITLE
limited field query via "attributes" doesn't actually limit the field set returned

### ISSUE THREAD

**Issue by bingomanatee** [sequelize/sequelize#6668]
## What you are doing?

Selecting a limited set of attributes (sqlite)

``` js
.then(model.BoardTile.findAll({
                attributes: ['lat', 'lon', 'content', 'BoardId'],
                where: {
                  BoardId: newBoard.id
                },
                order: [
                  ['lat', 'ASC'],
                  ['lon', 'DESC']
                ]
              }))
```
## What do you expect to happen?

only those named fields' data is returned
## What is actually happening?

I get all the fields (createdAt, etc.)

**Dialect:** sqlite
**Database version:** 3
**Sequelize version:** 3.24.3

**Comment by janmeier** [comment]
We have tests for that specific case https://github.com/sequelize/sequelize/blob/v3/test/integration/instance.test.js#L1722 - If you add `attributes`, only those will be selected.

Can you create a [SSCCE](http://sscce.org/)?
