### ISSUE TITLE
how to call the custom sql function in attributes/where condition in sequelize

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#6672]
how to call custom sql function in Sequelize

I tried like this 

its working 
app.get('/callservice',function () {
    Sequelize.query('select fun_GetGalleryCount(1,1);',
    {
        type: Sequelize.QueryTypes.RAW
    })
    .then(function(results) {
        console.log(JSON.stringify(results));
    })
})

but in attributes/where condition is not working like this: 
 options.where=getcondition(req,Sequelize);
     options.attributes=[
           [Sequelize.query('select fun_GetGalleryCount(1,1);',
                {
                    type: Sequelize.QueryTypes.RAW
                }),'ima']

        ];
  hp_property.findAndCountAll(options).then(function(result) {
});
 
errror:
Possibly unhandled TypeError: attr[0].indexOf is not a function

i tried in another way like this 
options.attributes=[
           [Sequelize.query('select fun_GetGalleryCount(1,1);'),'image']
  ];

so please give the solution 

__Dialect:__ mysql 
__Database version:__ XXX

**Comment by felixfbecker** [comment]
`query` will execute directly and return a promise. You are looking for `sequelize.fn` and `sequelize.literal`

**Comment by SIMHACHALAM1001** [comment]
options.attributes=[
[Sequelize.literal('select fun_GetGalleryCount(1,1);'),'image']
];

also getting the sam error

**Comment by felixfbecker** [comment]
Log the SQL generated. If you have further questions, ask on StackOverflow or Slack

**Comment by SIMHACHALAM1001** [comment]
thanq its solved

**Comment by miltz9** [comment]
With me this error only occurred when the model was not associated with the correct table name.
Like:
sequelize.define('Users', {
      ... <fields> ...
}, {
	tableName: 'USER', // wrong table name needs to be "USERS" to search the table in the database
});
