### ISSUE TITLE
Sesequelize add 'um' in hasOne relation

### ISSUE THREAD

**Issue by zion03** [sequelize/sequelize#6677]
I have relation `User.hasOne(models.UserMeta, {foreignKey: 'userId'});`
then execute query `return models.User.findAll({include: {model: models.UserMeta}});`

In query  UserMeta become `UserMetum` `LEFT OUTER JOIN "UserMeta" AS "UserMetum"`

why?

**Comment by janmeier** [comment]
This is a deliberate choice by the inflection library we use to singularize and pluralize names - https://github.com/dreamerslab/node.inflection/issues/19.

You can override the singular and plural names,  http://docs.sequelizejs.com/en/v3/api/sequelize/#definemodelname-attributes-options-model Look for `options.name`
