### ISSUE TITLE
Eager Loading with Sorting/Limiting?

### ISSUE THREAD

**Issue by leeola** [sequelize/sequelize#668]
Correct me if i am wrong, but the purpose of `include` is to basically join objects in a meaningful manner, correct? Allowing you to load various object(s) with only one database query.

Well, if that is the case than i think we need more than basic eager loading. For example, What about sorting options on an included list of objects? What about limiting included objects?

I feel like includes offer far more options than i see exposed. Thoughts?

**Comment by theptrk** [comment]
What does it mean to define a nested key set?
I'd like to do something like this to get only 1 Assignment per user
```
 Group.findOne({
   where: {id: "someId"},
    model: models.Group,
      include: [{
        model: models.User,
        include: [{ 
          limit: 1,
          model: models.Assignment,
          include: [{ 
            model: models.Job,
            include: [
              { model: models.Company }
            ]
          }],
        }] 
      }]
```

I get an error SequelizeDatabaseError: column "Job.CompanyId" does not exist. 
Is this nested to deeply?

**Comment by mickhansen** [comment]
@theptrk not specifically related to sorting, i think you're facing the bug with includes on `separate`, there's an existing issue somewhere.
