### ISSUE TITLE
Don't override custom methods with association mixins

### ISSUE THREAD

**Issue by tornillo** [sequelize/sequelize#6682]
Hi!
Just an example:

``` js
var User = sequelize.define('user', { name: Sequelize.STRING });
var Project = sequelize.define('project', { title: Sequelize.STRING });

// custom Instance method
User.prototype.addProject = function () {
    console.log('do custom stuff');
};

Project.belongsTo(User);


let user = User.build();

user.addProject() // custom stuff works
```

After awhile, when the project grows, I add backward association:

``` js
User.hasMany(Project);
```

And now the custom method stops working because it overridden "silently" by new DAO method:

``` js
user.addProject() // it's a new DAO method
```

In big projects with 10+ models is too hard to keep in mind all naming conventions.

I can suggest two solutions to the problem:
1. Do not override custom Instance methods when create association, and keep new DAO methods to be accessed via `this.constructor.super_.prototype`
2. Just print a warning to console.log to notify developer about of name conflicts.

**Comment by felixfbecker** [comment]
You could just patch your method _after_ you associated. But I agree this is not very nice, especially with ES6 classes. I think we should not override user methods. The getters/setters should be available under `Model.associations.alias.set/get/add/create/...`

**Comment by tornillo** [comment]
> You could just patch your method after you associated.

If I add the custom method after the association, I will lose access to the original association method. This is not good, because, for example, I want to call the original from my own method + do something else.

> But I agree this is not very nice, especially with ES6 classes.

I think It's not related to ES6 classes. Sequelize V3 has the same behavior.

> Do a PR if you want

I'll try to do it:)

**Comment by felixfbecker** [comment]
> If I add the custom method after the association, I will lose access to the original association method. This is not good, because, for example, I want to call the original from my own method + do something else.

That's not true, you can save yourself a reference. Actually this is the _only_ way to get that reference atm.

> I think It's not related to ES6 classes. Sequelize V3 has the same behavior.

The point is that with ES6 class syntax the method will always be defined before the mixin is applied.

**Comment by tornillo** [comment]
Agree. But it's too complex way: check that method is already exist, then save reference...
In my applications at first I always define the models and methods, then make the associations in a loop. In such approach every new association can break of my already defined methods.
Therefore, I need a protective mechanism:)

**Comment by tornillo** [comment]
It seems that problem is more complicated.
V4 does not allow override even basic DAO method without losing access to the original one:
```js
User.prototype.save = function () {
	console.log('custom method');
	console.log(this.constructor.super_); // undefined
}
```
`this.constructor.super_` does not exist as specified in the documentation.
So now there is no place where we could save the methods of associations (issue subject).
Or maybe I'm wrong?

**Comment by felixfbecker** [comment]
@tornillo `super` is available as a native keyword for accessing the prototype object. But that doesn't help you here - the methods are a _mixin_, they don't work with inheritance, they get _patched_ on the prototype. Which is why I said the association methods that get patched should be available under `Model.associations.alias.get/set/create/count/add...`, so you can reference them from there. I think @janmeier recently implemented something like that, but not for all methods.

**Comment by janmeier** [comment]
`get` is exposed for all associations, count might not be for all.

I think throwing if there is a naming conflict would be a good idea

**Comment by felixfbecker** [comment]
Throwing would prevent us to override the methods, so that would be kind of useless 😄 
But I think it would be great to have all the mixin functions available from the association object generically.

**Comment by tornillo** [comment]
As I understand, `super_` comes from `util.inherits`, which not used in the V4 in favor of native classes and prototypes. That is why we are losing the opportunity (regarding the V3) to redefine basic methods (like `save`, etc.)
`Model.associations._alias_name_.*` - is a good place to preserve class methods, but not instance.
So maybe we should choose only one logical place for all originals of instance methods?

**Comment by tornillo** [comment]
Throwing - is a simplest way without a lot of refactoring, it's good as temporary solution.

**Comment by felixfbecker** [comment]
@tornillo yes, `super_` comes from `util.inherits`, but you don't need it in Node 4/6 because you can use the native `super` keyword. You can still override methods just fine. As I said, it doesn't help you here though, because it is a mixin. `Model.associations` is a hash from association alias to `Association` object. It does not "preserve class methods", it already has a couple of useful attributes, like `accessors` that gives you the names of the mixin functions. But currently except for `get` the mixin functions are made available there, I proposed to make them all available.

Throwing definitely is not a good "temporary solution" because it is a breaking change to throw where you didn't throw before. But as I said it doesn't solve the problem.

**Comment by tornillo** [comment]
@felixfbecker I understand how `inherits` works and how now it works in 4/6:) And has no questions about patching of mixin methods.
But, please, show me, how to access to the original `save` after this https://github.com/sequelize/sequelize/issues/6682#issuecomment-253006197

Throwing doesn't solve the problem, but allow to developer to do not "shoot in the foot" via silent overriding.

**Comment by felixfbecker** [comment]
```js
User.prototype.save = function save() {
    super.save()
}
```

Throwing will prevent you from overriding _at all_ that's the problem.

**Comment by tornillo** [comment]
```js
User.prototype.save = function save() {
    super.save()
}
let user = User.build();
user.save();
// error: 'super' keyword unexpected here
```
What i'm doing wrong? Node v6

Seems like _super is only allowed in concise methods, not regular function expression properties. It also is only allowed in super.XXX form (for property/method access), not in super() form._ (from [You-Dont-Know-JS](https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch2.md))

> Throwing will prevent you from overriding at all that's the problem.

For methods of associations is not a problem, because at present Sequelize prevent me from overriding:) Warning + custom names = good enough solution.

**Comment by felixfbecker** [comment]
Okay, but this should work:
```js
User.prototype.save = function save() {
  Model.prototype.save();
}
```

**Comment by tornillo** [comment]
`Model.prototype.save.call(this)` works, thanks!
