### ISSUE TITLE
JSONB DataTypes specified by strings do not get JSONB behaviours

### ISSUE THREAD

**Issue by scandox** [sequelize/sequelize#6683]
## What you are doing?
If I have a model like:

```js
var Annotation = sequelize.define("annotation", {
    annotation: { type: 'JSONB', allowNull: false },
    isOK: { type: dataTypes.BOOLEAN, allowNull: false, defaultValue: false }
}....
```

The Postgres DB will correctly create a field of type `jsonb` for annotation. However, Sequelize itself will not recognize that the it is a `jsonb` field and queries will be treated as if it was a Text field.

By changing the definition to use `dataTypes.JSONB` this is fixed.

## What do you expect to happen?
If datatypes can be specified by string instead of using the predefined types, I think Sequelize should recognize / honor the behaviours for the type specified. Otherwise it's very easy to introduce hard to explain errors in a mid to large project.

## What is actually happening?
If you try to do a json type query on a `jsonb` field defined with a string datatype, then you will get a val.replace error.

**Comment by felixfbecker** [comment]
The DataTypes are actually objects that define `parse` and `stringify` methods. When you use a string, these are not specified. The string argument should only be used for datatypes that are not supported by Sequelize.
