### ISSUE TITLE
How to get plain object form 'findAll'

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6687]
I use findAll get resualt like:
```
{
rows:[Instance,Instance,Instance]
}
```
hoe to get plain object in rows?

**Comment by sushantdhiman** [comment]
You will have to loop through each Instance and call `getJSON`, or you could set option `raw: true` in `findAll` , ([more docs](http://docs.sequelizejs.com/en/v3/api/model/#findalloptions-promisearrayinstance))
