### ISSUE TITLE
group by in scopes does not concatenate the group clauses.

### ISSUE THREAD

**Issue by Mijago** [sequelize/sequelize#6690]
It seems that using the group by in scopes does not concatenate the group-clauses.

```
            /* GROUP */
            g_date     : {
                attributes: [
                    ["datum", "date"]
                ],
                group     : ["datum"]
            },
            g_lanr     : {
                attributes: ["lanr"],
                group     : ["lanr"]
            },
```

with
`xxx.scope("g_date", "g_lanr").findAll()`
just creates
`SELECT "datum" AS "date", "lanr" FROM "xxx" AS "xxx" GROUP BY "datum" LIMIT 10;`
which throws an error, because `lanr` is not in the GROUP clause.
I'm using PostgreSQL.

I can work around this by creating an extra scope, but this is not the perfect solution, because I want to store specific scope-collection-settings per user.

```
            g_lanr_date     : {
                attributes: ["lanr", ["datum", "date"]],
                group     : ["datum","lanr"]
            },
```

**Comment by felixfbecker** [comment]
The attributes get merged, correct?

**Comment by Mijago** [comment]
Yes, you can see this in the query. 
Just the GROUP BY does not get merged.

**Comment by Mijago** [comment]
I think i got some kind of fix; I'll test it and give it a try :)

**Comment by brettvitaz** [comment]
@Mijago Your fix solves a problem for me. What is the status of this? Can we get this included?

**Comment by felixfbecker** [comment]
Where is the PR?

**Comment by brettvitaz** [comment]
I'll submit a PR based on @Mijago's branch. I just have to add tests.
