### ISSUE TITLE
Use mention-bot

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6693]
https://github.com/facebook/mention-bot

Automatically mentions potential reviewers for PRs by analyzing git blame on the lines changed.

**Comment by sushantdhiman** [comment]
Too much spam may be, we have way too many contributors.

**Comment by felixfbecker** [comment]
Yeah but a lot of time we get PRs where I get notified, do some minor review but cannot review in-depth because I didn't write that code. So people will ping me and ask if there is any update and I have to respond "sorry I didn't write that someone else needs to review this I don't know who though". The mention bot would help with this

**Comment by sushantdhiman** [comment]
For core repo, at least 2 core members will have to review even if its a small change (more for large change per case basis), everyone works asynchronously so at the end we still have to wait for others to give their views.

May be we should be more transparent about who is maintaining what primarily

| Repository | Maintainers |
| ------------- | ------------- |
| **core** | @mickhansen @janmeier @sushantdhiman @felixfbecker |
| **cli** | @sdepold @Americas | 
| **umzug** | @jukkah |
| **sequelize-auto** | @durango | 
| **docs** | @janmeier |
| **express-example** | @sushantdhiman |

And post it somewhere :)

**Comment by mickhansen** [comment]
mention-bot could be a good thing, if we consider it a advisory tool and not a assigning tool.

**Comment by felixfbecker** [comment]
Heres an example in the wild: https://github.com/Microsoft/vscode/pull/13678#issuecomment-253512676

**Comment by janmeier** [comment]
Fine with me :)

**Comment by janmeier** [comment]
I've enabled the bot - let's see how it goes
