### ISSUE TITLE
i am getting different requests from client side angular to nodejs server,so i want to handle all the requests?

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#6694]
i am getting different request from angularjs to filtering, I wrote so many if condition but i want some clean code .

different requests from angular :

    var selector={"Inhibition":"8,6","city_name":"Bangalore","location_id":"15"};
    var selector={"Inhibition":"8,6","bedrooms:[1,2,3,4,5]","city_name":"Bangalore","location_id":"15"}
    var selector={"city_name":"Bangalore","location_id":"15"}
    var selector={"city_name":"Bangalore","location_id":"15","Resale":"true"}
    var selector={"city_name":"Bangalore","location_id":"15","Resale":"true","bedrooms:[1,2,3,4,5]"}
    var selector={"city_name":"Bangalore","location_id":"15","Resale":"true","bedrooms:[1,2,3,4,5]","Inhibition":"8,6"}

    In this  client side requests common in 3 conditions is after filtering with bedrooms,inhibition,bedrooms,avilability,resale,....etc:
    1. may be "location_id":"15"
    2. may be "location_id":"12"
    3. may be "builders_id":"1"

so iam getting different requests from client-side to server side.
so iam assigning different request in where condition in nodejs

  

    options.where = getcondition(req, Sequelize);
           options.include = [{
                    model: hp_builders,
                    required: true
                }, { ....  },{ .... }]
    
    
    
    
     hp_property.findAndCountAll(options, {
                subQuery: false
            }).then(function(result) {
    res.json(result);
    });

so how can i write in an effective manner for getcondition(req, Sequelize);

my getcondition(req, Sequelize) function code is:

        function getcondition(req, Sequelize) {
    
            var condition = JSON.parse(req.query.selector);
    
            if (condition.hasOwnProperty("city_id")) { 
    	               comparison(condition,"city_id","hp_city_id");			
                 }
    
            else if (condition.hasOwnProperty("id")) {
                 comparison(condition,"id","hp_builders_id");
    			 }
    
             else if (condition.hasOwnProperty("location_id")) {
    			 comparison(condition,"location_id","hp_location_id"); 
                  }
       
       
       }
    
    
    function comparison(condition,id,dbId){
    	  
    	     if (condition.hasOwnProperty("Inhibition")){
                    console.log(JSON.stringify(condition));
                    return {
                        $and: [{
                            dbId: condition.id
                        },
                            Sequelize.literal("`hp_property`.`hp_property_inhibition_status_id` IN (" + condition.Inhibition + ")"),
                        ]
                    }
    
                }
    
                if (condition.hasOwnProperty("bedrooms") && condition.hasOwnProperty("budgetPrice")) {
                    var budgetPrice = condition.budgetPrice.split(",");
                    var minRange = budgetPrice[0];
                    var maxRange = budgetPrice[1];
                    return {
                        $and: [{
                            dbId: condition.id
                        },
                            Sequelize.literal("`hp_unit_details`.`hp_unit_type_id` IN (" + condition.bedrooms + ")"),
                            Sequelize.literal("`hp_unit_details.hp_unit_prices`.`price_per_sqft` * `hp_unit_details`.`property_size`  BETWEEN " + minRange + " AND " + maxRange)
                        ]
    
                    }
                }
    
                if (condition.hasOwnProperty("bedrooms") && !condition.hasOwnProperty("budgetPrice")) {
                    return {
                        $and: [{
                            dbId: condition.id
                        },
                            Sequelize.literal("`hp_unit_details`.`hp_unit_type_id` IN (" + condition.bedrooms + ")")
                        ]
    
                    }
                } else if (condition.hasOwnProperty("budgetPrice") && !condition.hasOwnProperty("bedrooms")) {
                    var budgetPrice = condition.budgetPrice.split(",");
                    var minRange = budgetPrice[0];
                    var maxRange = budgetPrice[1];
                    return {
                        $and: [{
                            dbId: condition.id
                        },
                            Sequelize.literal("`hp_unit_details.hp_unit_prices`.`price_per_sqft` * `hp_unit_details`.`property_size`  BETWEEN " + minRange + " AND " + maxRange)
    
                        ]
                    }
    
                }
    
    
                return {
                    dbId: condition.id
                }
    }

**Comment by mickhansen** [comment]
I'm sorry but we don't have the capacity to support "how to write this better" questions, also we only allow bug reports and feature requests on GitHub.

Give StackOverflow or Slack a shot.

**Comment by felixfbecker** [comment]
Furthermore, [opening issues like these over and over again (even with the exact same question!) will not change that fact](https://github.com/sequelize/sequelize/issues?utf8=%E2%9C%93&q=author%3ASIMHACHALAM1001). This is spamming volunteer maintainers and wasting the free time we could use for serious bug reports and features. This is an issue tracker, not StackOverflow or CodeSchool.
