### ISSUE TITLE
node-uuid: crypto not usable

### ISSUE THREAD

**Issue by manast** [sequelize/sequelize#6699]
I am wondering if more people is getting this error when instantiating Sequelize:
`[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()`

Seems like not very safe to not generate truly cryptographic safe uuids. According to this thread we should use the uuid module instead of node-uuid:
https://github.com/broofa/node-uuid/issues/116

Pull that never was merged in node-uuid:
https://github.com/broofa/node-uuid/pull/136

UPDATE:

```
└─┬ sequelize@3.24.3
  └── node-uuid@1.4.7
```

Node version: 4.6.0

**Comment by felixfbecker** [comment]
I don't get this warning. If crypto is not usable, uuid won't be able to use it either...

**Comment by felixfbecker** [comment]
Maybe you're missing an OpenSSL on your machine or something like that?

**Comment by manast** [comment]
hmm, this is on Mac, I did not get this warning before, I am trying other versions of node to see if it depends on that.

**Comment by manast** [comment]
I get the same warning on 4.5, 4.6 and 6.8.
I will try on ubuntu later today, I can update status after that.

**Comment by excitement-engineer** [comment]
I am getting the same error with sequelize @3.24.3

**Comment by felixfbecker** [comment]
I'm closing this as in any way it is nothing that Sequelize can control. If crypto is not usable for whatever reason on your machine, there is nothing we can do about it - it's an environment issue

**Comment by manast** [comment]
thing is that crypto works well otherwise in my machine, it is only sequelize that is complaining about it. If you check this pull (https://github.com/kelektiv/node-uuid/pull/136), you may see that there is a know issue that triggers a bug that may be the one reported in this thread. Why not upgrade to the new, maintained uuid anyways?

**Comment by felixfbecker** [comment]
Okay, makes sense. PR appreciated

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/commit/b6e1c154dad8952262fcc9cbd5a4aa26650cab11
