### ISSUE TITLE
strange issues!

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6700]
aSchema has property 'mode'
`mode: { type: Sequelize.INTEGER, allowNull: false, defaultValue: 1, field: 'fmode' },`
aSchema.findAll() work well.
but if use the schema as include as 
`otherSchema.findAll({include:{ model: aSchema,as:'aSchema' }})`
the 'mode' always equal 1, actual value is 2,why?

**Comment by janmeier** [comment]
Please include a complete [SSCCE](HTTP://SSCCE.ORG/)
