### ISSUE TITLE
Document [options.fields] on instance.validate()

### ISSUE THREAD

**Issue by guisehn** [sequelize/sequelize#6703]
The documentation for the `validate()` method on instances only covers the `skip` option, which allows you to specify which fields you want to ignore when running the validations. 

<img width="763" alt="screen shot 2016-10-14 at 18 07 47" src="https://cloud.githubusercontent.com/assets/830208/19402748/338a6a1a-9239-11e6-8b70-bef54e3903f1.png">

However, looking at the code, we also have the option to pass a `fields` option, which allows you to specify which exact fields you want to validate.

https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/instance-validator.js#L21

Is it safe to rely on this option, or is it meant to be private for internal usage only? If it's ok to be supported, I can send a PR to update the documentation to include this option on the list, just let me know.

**Comment by janmeier** [comment]
Yep, feel free to provide a docs PR :)!
