### ISSUE TITLE
Cannot find module 'pg-native' in version 3.24.4

### ISSUE THREAD

**Issue by ashnamuh** [sequelize/sequelize#6716]
## What you are doing?
related [issue](https://github.com/getsentry/raven-node/issues/212)

I tried to attach a [sentry](https://docs.sentry.io/clients/node/integrations/express/) on my server to trace some errors. But the error `Cannot find module 'pg-native'` occurred. I had known the error is related to [raven](https://github.com/getsentry/raven-node) from the beginning. However, the error may be related to Sequelize. I really don't know why the error occurred and why happen the error after raven was attached.

detail info is in [issue](https://github.com/getsentry/raven-node/issues/212)

__Dialect: postgres__
__Database version: `9.3`__
__Sequelize version: `3.24.4`__

**Comment by janmeier** [comment]
If we can't replicate the issue we really can't help you - I don't even see any sequelize code in the issue you've linked, so there's really not anything we can do.

**Comment by ashnamuh** [comment]
Oh, sorry. I was nuts.. If i can show the Sequelize code, i can get a help?

**Comment by janmeier** [comment]
Yes, but there is nothing in the stacktraces you have show pointing to sequelize.

As someone already mentioned in the other thread, you are probably cloning or otherwise accessing the `native` property of the pg modules, which causes it to try to require the module, see https://github.com/brianc/node-postgres/issues/945

**Comment by felixfbecker** [comment]
This can often happen when you try to clone some object from sequelize or use any method that recursively iterates over all properties, like `_.omit()` or `_.isEqual()`. It will access the connection property, then the dialect, and then the `native` property which tries to load `pg-native`.

**Comment by ashnamuh** [comment]
So, how can i fix it? Maybe i abuse Sequelize? It seems `node-postgres` have not yet resolved.

code here

models/index.js
```js
'use strict';

const _ = require('lodash');
const dbConfig = require('../config/loader').load('db');
const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');

const connection = new Sequelize(
  dbConfig.database,
  dbConfig.username,
  dbConfig.password,
  _.chain(dbConfig)
    .omit(['database', 'username', 'password'])
    .extend({
      dialect: 'postgres'
    })
    .value()
);

console.log(_.chain(dbConfig)
    .omit(['database', 'username', 'password'])
    .extend({
      dialect: 'postgres'
    })
    .value());

// initialize models
let models = {connection};
let relationships = [];

const defineModel = (name, schema, option) => {
  option = option ? option : {};
  models[name] = connection.define(name, schema, option);
};

const defineRelationship = (relationship) => {
  relationships.push(relationship);
};

fs.readdirSync(__dirname).forEach(model => {
  let ext = path.extname(model);
  let basename = path.basename(model, ext);
  if (ext !== '.js' || basename === 'index') {
    return;
  }
  require('../models/' + basename)(defineModel, defineRelationship, models);
});

relationships.forEach(relationshipDefinition => relationshipDefinition());

module.exports = models;
```

models/user.js
```js
'use strict';

const Sequelize = require('sequelize');

module.exports = (defineModel, defineRelationship, models) => {
  defineModel('User', {
    id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
    email: {type: Sequelize.STRING, allowNull: false, unique: true},
    password: {type: Sequelize.STRING},
    name: {type: Sequelize.STRING, allowNull: false},
    loginMethod: {type: Sequelize.ENUM('email', 'facebook'), defaultValue: 'email'}
  });

  defineRelationship(() => {
    models.User.hasOne(models.Admin, {as: 'admin', foreignKey: 'userId'});
  });
};
```

models/admin.js
```js
'use strict';

module.exports = (defineModel, defineRelationship, models) => {
  defineModel('Admin', {}, {
    indexes: [
      {
        unique: true,
        fields: ['userId']
      }
    ]
  });
  defineRelationship(() => {
    models.Admin.belongsTo(models.User, {as: 'user', foreignKey: 'userId', onDelete: 'CASCADE'});
  });
};
```

requiring model
```js
const Admin = require('../models/').Admin;
const User = require('../models/').User;
```

**Comment by felixfbecker** [comment]
Cannot see what's wrong there, but watch out for `omit()`. Ask on SO if you need more help

**Comment by kytwb** [comment]
Just leaving this here; watch out also if you use `dialectModule`.
