### ISSUE TITLE
removeAttribute does not update default scope

### ISSUE THREAD

**Issue by dsbert** [sequelize/sequelize#6717]
I have a one-to-many relationship between two models (`Parent` and `Child`). My `Child` model is defined with a default scope. It also does not have a primary key (_yeah I know_). So I've used `removeAttribute('id)` to prevent the wrong column from being used in a query. However, when the query builder steps through and builds the select statement, it uses the `$scope` field to populate the attributes. It appears that calling `removeAttribute` does not update the default scope, because the `id` field is still present. This causes the query to break. If I remove the default scope from my model definition, then the query works as expected.

``` js
module.exports = function Child(sequelize, DataTypes) {
  const Child = sequelize.define('child', {
    labelId: {
      field: 'Label',
      type: DataTypes.STRING,
      allowNull: false,
    },
    locationId: {
      field: 'Location',
      type: DataTypes.STRING,
      allowNull: false,
    },
    // snip
  }, {
    tableName: 'ChildTable',
    schema: 'Schema',
    classMethods: {
      associate: (db) => {
        Child.belongsTo(db.parent, { foreignKey: 'labelId' });
      },
    },
    defaultScope: {
      attributes: {
        exclude: [
          'attribute1',
          'attribute2',
        ],
      },
    },
  });

  Child.removeAttribute('id');

  return Child;
};

module.exports = function Parent(sequelize, DataTypes) {
  const Parent= sequelize.define('parent', {
    labelId: {
      field: 'Label',
      type: DataTypes.STRING,
      allowNull: false,
      primaryKey: true,
    },
    // snip
  }, {
    tableName: 'ParentTable',
    schema: 'Schema',
    classMethods: {
      associate(db) {
        Parent.hasMany(db.child, {
          as: 'children',
          foreignKey: 'labelId',
        });
      },
    },
  });
  return Parent;
};

Parent.findAndCount({
      include: [{
        model: Parent.sequelize.models.child,
        as: 'children',
      }],
    });

// SELECT parent.*, [child].id, ...

```

The problem seems to be in the call to `model.$injectScope(include);` in model.js (~ line 590)

**Dialect:** mssql
**Database version:** 2012
**Sequelize version:** 3.24.3

**Comment by janmeier** [comment]
Hmm yes, I guess we should call `conformOptions` on scope each time attributes change. However, `removeAttribute` is a bit of a hack (in my mind at least). You could add `id` to `attributes.exclude` as a fix for now

**Comment by dsbert** [comment]
I do not know if this was ever fixed because I no longer use sequelize.

**Comment by anoopsthakur** [comment]
I am getting the same problem

**Comment by ccemeraldeyes** [comment]
please reopen, this is still an issue.

**Comment by papb** [comment]
Hello @ccemeraldeyes - To me it looks like the specific problem in the first post stems from the fact that sequelize automatically adds an `id` field to every model; so when #3142 gets fixed, OP's problem would cease to exist as well.

Have you experienced a similar problem (i.e. as in title, "*removeAttribute does not update default scope*"), with a field other than the auto-generated `id`?
