### ISSUE TITLE
Sequelize findOrCreate creates new user, but 'created' is false

### ISSUE THREAD

**Issue by InstaK** [sequelize/sequelize#6719]
What you are doing?

I'm using Express to make a route for fetching a user. If the user is found in the db, he gets added, else I will find that user in the chat, make an object for him, add him to the db and then return him. 
```js
app.get('/api/users/:username', (req, res) => {
  let username = req.params.username;
  getUserByUsername(username).then(foundUser => {
    if (foundUser) {
      res.send(foundUser);
    }else{
      findChattersPerRole()
        .then(chattersPerRole => {
          let wantedUser = find(chattersPerRole, {username});
          findOrCreateViewer(wantedUser.username, wantedUser.role)
            .then(addedUser => res.send(addedUser));
        });
    }
  });
});

const findChattersPerRole = () => {
  return fetch('https://tmi.twitch.tv/group/user/instak/chatters')
    .then(parseJSON)
    .then(r => {
      let chatters = r.chatters;
      let chattersPerRole = Object.keys(chatters).map(role => {
        return chatters[role].map(username => {
          findOrCreateViewer(username, role);
          return {
            username: username,
            role: role
          };
        });
      });
      return Promise.resolve(flattenDeep(chattersPerRole));
    }).catch(err => {
      console.log(`Error in fetch: ${err}`);
    });
};

const findOrCreateViewer = (username, role) => {
  return Viewer.findOrCreate({
    where: {
      username
    },
    defaults: {
      instakluiten: 5,
      role
    }
  }).spread((unit, created) => {
    if(created){
      return `User created got created ${unit}`;
    }else{
      return unit;
    }
  });

};
```

## What do you expect to happen?
When, in findOrCreateViewer, the user is created I expect 'created' to be true.

## What is actually happening?
Created is false EVEN THOUGH the user is added in the db!

__Dialect:__ mysql
__Sequelize version:__ ^3.24.3

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by InstaK** [comment]
I'm having some trouble creating the SSCCE since it's the first time I'd be making one... How would I add the connection to the DB? My terminal logs "Using database:  sequelize-test-xx", but I don't seem to get how I can connect to that...

**Comment by janmeier** [comment]
In the template you already have a sequelize instance - Define some models, sync it and write a small example that shows the problem

**Comment by InstaK** [comment]
I think I made an error. By trying to make the SSCCE I realised I was wrong, I don't know how I saw it differently. You could even remove this issue I suppose, sorry for the inconvenience.
