### ISSUE TITLE
FLOAT data type is not validated, accepts string values

### ISSUE THREAD

**Issue by vamsiampolu** [sequelize/sequelize#6720]
I have a model where some of the fields look like this:

```
lastReadingNo2PumpHours: {
      type: DataTypes.FLOAT,
      set(input) {
        const output = Number(input)
        if (!isNaN(output)) {
          this.setDataValue('lastReadingNo2PumpHours', output)
        }
      },
      validate: {
        isNumeric: true,
        min: {
          args: [0],
          msg: `Last Reading's No 2 Pump Hours cannot be negative`
        }
      }
    }
```

I am testing the validations for the model by passing in bogus values such as:

```
{
   "lastReadingNo2PumpHours": "zz"
}
```

I find that no validation is triggered for the model when `create` is called with these values. I have tried several variants of `isNumeric` like this:

```
//version 1
{
  isNumeric:{
     msg:'We need a number'
  }
}

//version 2
{
  isNumeric:{
     args:true,
    msg:"We need a number" 
  }
}

//version 3:
{
  isNumeric:{
     args:[true],
     msg:'We need a number,really" 
  }
}

//version 4:
/*no isNumeric validation*/
```

The validation is not triggered with any of these variants, instead the field is bypassed and a null value is inserted into the table. 

__Dialect:mysql
__Database version:5.7.12
__Sequelize version: 3.24.3

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by ro70** [comment]
Try version 5:
```
{
        isNumeric: true,
        min: {
          args: [0]
        }
      }
```
Is it throwing an error?

See https://github.com/sequelize/sequelize/issues/6628

**Comment by felixfbecker** [comment]
Again, please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by sushantdhiman** [comment]
@vamsiampolu Validation works properly.

Its your `setter` which prevent setting non numeric data to model. When you to try to set `lastReadingNo2PumpHours : "zz"`, your setter see `isNaN` check fails and never set it to instance. This value is never reached to validations and thus neither validated nor saved.

If you remove the setter you will see the validation fails properly for the cases you have tried to test.
