### ISSUE TITLE
TypeError: Cannot read property '2' of null

### ISSUE THREAD

**Issue by abartolo** [sequelize/sequelize#6725]
## What you are doing?

Creating a record with the same value in a column that is Unique:true. I'm using FeathersJS with uses Sequelize. I successfully inserted new record via restful api using Postman.  However if I send the same request again( create a user with the same email which the column is unique) it crashes the server with error "TypeError: Cannot read property '2' of null".

Below is the model I am using

``` js
// code here
const Sequelize = require('sequelize');

module.exports = function(sequelize) {
  const user = sequelize.define('users', {
    email: {
      type: Sequelize.STRING,
      allowNull: false,
      unique: true
    },
    password: {
      type: Sequelize.STRING,
      allowNull: false
    }
  }, {
    freezeTableName: true
  });
```
## What do you expect to happen?

I expected to get a response back with an error stating its a duplicate or at least a clean error.
## What is actually happening?

Crashed server since error wasn't caught.

_Output, either JSON or SQL_

![image](https://cloud.githubusercontent.com/assets/5394228/19537833/7c84e15c-961f-11e6-9f0e-ec5aaa9a72f3.png)

**Dialect:** mysql
**Database version:** 5.7.13
**Sequelize version:** 3.24.4

**Comment by felixfbecker** [comment]
That stack trace does not mention sequelize anywhere. If you still believe this is a sequelize bug, create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by janmeier** [comment]
@felixfbecker Actually it does ;), [here](https://github.com/sequelize/sequelize/blob/v3/lib/dialects/mysql/query.js#L132)

@abartolo Which language is your mysql installation? Currently we only support parsing messages in english?

In any case, we need a guard before accessing the match, checking if anything was actually matched

**Comment by felixfbecker** [comment]
Sorry, overlooked that on the screenshot.

**Comment by abartolo** [comment]
@janmeier Mysql is installed in english.

So last night I tried to replicate the issue in my home environment since this was at work, and it worked! Sooo.... I assumed perhaps the installation of node_modules went wrong since my workplace has a lot of firewalls and strict security. But after reinstalled dependencies I still got the issue.

The DB at my home env is 5.6.x and I doubt Mysql version is the issue so I looked at my node version found I'm using v4.2.1 @ work. This is a red flag since FeatherJS documentation is stating nodeV 5+ and if anything is below is required to use babel.

Not sure if this is related to this issue but I will work on updating my node and see if that fixes the issue.

**Comment by janmeier** [comment]
I'm actually pretty sure the mysql version is the issue then - We've had these kind of problems in the past where the error message as different between different versions of mysql.

I think moving forward we should abstract the code that parses messages into a separate method that we can then easily unit test. There is no need to actually run tests against several different versions, but we'd like to be able to support them and at least not crash still :)

**Comment by abartolo** [comment]
@janmeier I can also confirm that mysql version is the issue. Luckily the mysql version locally installed at work is version 5.6.15  VS. the mysql 5.7.13 where I got this issue.

I replicated both table structures and unique indexes as seen below. Sent a POST to create a new record and immediately sent the POST again to recreate the crash but this time the server did not crash and instead got a JSON error as expected.

Expected Response with mysql version 5.6.15
`
{
	"test_description": "b2b_edgeFlow_creditCard_visa_splitpayment_3",
	"status": "failed",
	"build_date": "2016-08-01 15:20:28"
}
`

Both have the same Table and Indexes
![image](https://cloud.githubusercontent.com/assets/5394228/19568893/75e6e550-96c1-11e6-8554-d936820598a0.png)


Indexes
![image](https://cloud.githubusercontent.com/assets/5394228/19568909/89dd2632-96c1-11e6-952c-796802e24bb9.png)

**Comment by janmeier** [comment]
Could you post the different error messages?

**Comment by abartolo** [comment]
@janmeier Not sure what you mean. I get the same error I originally posted.
https://cloud.githubusercontent.com/assets/5394228/19537833/7c84e15c-961f-11e6-9f0e-ec5aaa9a72f3.png

**Comment by janmeier** [comment]
I mean that actually error messages from MySQL - so the code can be fixed to support both

**Comment by crzidea** [comment]
I got the exactly issue with this. Any update?

**Comment by janmeier** [comment]
@crzidea Some details please? Which mysql version, and what is the wording of the message? As i've already mentioned before we need to know the actual wording of the error message to be able to support it

**Comment by Aziz-JH** [comment]
I use Currently v3.30.2 and mysql version is 5.7.11

**Comment by ThomasEcalle** [comment]
Hi, I have the same issue that talked before.

I'm running a 5.6.17 MySql's version and using Sequelize on version 3.30.2.

The issue is about the "unique" validator on one of my attributes. I have the "cannot read property 2 of null" error just as abartolo.

Do you have any idea that could help ?

**Comment by akhoury** [comment]
this is till happening

**Comment by akhoury** [comment]
The issue is here: 

https://github.com/sequelize/sequelize/blob/f8a98a145443c890be9cab4c941abda28845e4c0/lib/dialects/mysql/query.js#L199-L212

I put a log statement to see the `err` and it looks like this. 

```javascript
{
  "code": "ER_DUP_ENTRY",
  "errno": 1062,
  "sqlState": "23000",
  "sqlMessage": "",
  "sql": "INSERT INTO `users` (`id`,`email`,`password`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'xxxxx@gmail.com','$2a$10$0yoLkp7LQD.IcHFfNCib..hL8LeM/soCUdSuOF1c1.NGHjeF8nNbO','2018-04-21 08:52:42','2018-04-21 08:52:42');"
}
```

There is no `err.message` so `match` is `null`, and there are 2 statements that don't guard against it.
```javascript
        const uniqueKey = this.model && this.model.uniqueKeys[match[2]];
```
and 
```javascript
          fields[match[2]] = match[1];
```
I am using `MySQL 5.7.21`

**Comment by Wadeck** [comment]
Same error here, using MySQL in french, exception is "Duplicata du champ 'UC....-UC....-xxx' pour la clef '<key_name> etc.

The approach to use the translated name in the trace does not seem really stable :(

**Comment by zhangshichun** [comment]
this is because that: 
you save a date like 'cccc\r',so the err.message is ''Duplicate entry 'cccc\r' for key ...",then,the method match return null.
