### ISSUE TITLE
Specifying custom "field" attribute results in lacking modifiers

### ISSUE THREAD

**Issue by trriplejay** [sequelize/sequelize#6726]
## What you are doing?

creating a table via `define` that uses the `field` attribute to set a custom field name

``` js
status: {
  type: Sequelize.INTEGER,
  allowNull: false,
  field: 'statusCode',
  defaultValue: 0
}
```
## What do you expect to happen?

issuing `\d` to the table in postgres should show:

```
         Column         |           Type           |                               Modifiers                                
------------------------+--------------------------+------------------------------------------------------------------------
 statusCode             | integer                  | not null default 0
```
## What is actually happening?

issuing `\d` to the table instead shows:

```
         Column         |           Type           |                               Modifiers                                
------------------------+--------------------------+------------------------------------------------------------------------
 statusCode             | integer                  | 
```

(modifiers are not getting set)

Seems like it has something to do with that `field` attribute since it works fine for any other column.

**Dialect:**  postgres
**Database version:** `PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit`
**Sequelize version:** 3.23.4

**Comment by janmeier** [comment]
Does the happen when the attribute is on a model, and calling `sync`, or does it happen when altering a table through the query interface? (or both)

**Comment by trriplejay** [comment]
Attribute on the model and calling sync. Not sure about the second case.
