### ISSUE TITLE
Use giorgos/takis in Travis Setup

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#6733]
Tests are failing most of time because Postgres was not able to start in `30 sec` sleep time (ah.. hack). We need to replace this with something realistic like https://hub.docker.com/r/giorgos/takis/

**Comment by janmeier** [comment]
Looks good to me.

We could also consider switching to an alpine based image - It feels to me like they boot quicker as well

**Comment by sushantdhiman** [comment]
Good Idea, we can switch to these images 

- Alpine Postgres https://hub.docker.com/r/kiasaki/alpine-postgres/
- Alpine MySQL https://hub.docker.com/r/wangxian/alpine-mysql/

**Comment by janmeier** [comment]
We need an image with postgis though (might be easiest to just roll our own on top of alpine postgres)

**Comment by janmeier** [comment]
I just tested locally, and it seems the postgis 9.5 container crashes the first time you try to start it .. https://github.com/camptocamp/docker-postgis/issues/3
