### ISSUE TITLE
addAssociation not working

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#6734]
## What you are doing?
```js
var Sequelize = require('sequelize')
var sequelize = new Sequelize('...', '...', '...')

// B and C inherit from A.
var A = sequelize.define('A',
  {
    // id is the primary key.
    attrA: Sequelize.STRING
  },
  {
    timestamps: true,
    deletedAt: 'deletedAt',
    paranoid: true
  }
)

var B = sequelize.define('B',
  {
    // id is the primary key and the foreign key (A).
    attrB: Sequelize.STRING
  },
  {
    timestamps: false,
    paranoid: true
  }
)

var C = sequelize.define('C',
  {
    // id is the primary key and the foreign key (A).
    attrC: Sequelize.STRING
  },
  {
    timestamps: false,
    paranoid: true
  }
)

B.belongsTo(A, {foreignKey: 'id'})
C.belongsTo(A, {foreignKey: 'id'})
A.hasOne(B, {foreignKey: 'id'})
A.hasOne(C, {foreignKey: 'id'})

// Creating values.
sequelize.sync({force: true})
.then(function() {
  return A.create(
    {
      attrA: 'AA'
    }
  )
})
.then(function(a) {
  a.addB(
    {
      attrB: 'BB'
    }
  )
})
// Catching errors...
.catch(function(err) {
  console.log(err)
})
```

## What do you expect to happen?
Expecting two new entities: AA in table A and BB in table B.

## What is actually happening?
AA is created. Creation of BB throws
```
TypeError: a.addB is not a function
```

__Dialect:__ mysql
__Database version:__ 10.1.9-MariaDB
__Sequelize version:__ 3.24.4

**Comment by PerGullberg** [comment]
You are confusing hasOne and hasMany. For hasMany you are correct in using addB, but for hasOne you should use setB.

**Comment by ro70** [comment]
@PerGullberg Thank you Per. But a.setB is not working either:
```
Unhandled rejection TypeError: val.replace is not a function
```

**Comment by PerGullberg** [comment]
@ro70 https://gist.github.com/PerGullberg/08cfcfb59bffbd3513444ecabef2a03a
I ran these tests just fine.

**Comment by janmeier** [comment]
Set can only be used with an instance of B that is already saved (has an ID set) 

To create a new instance of B and associate it with a you can use `a.createB`

http://docs.sequelizejs.com/en/v3/api/associations/has-one/

**Comment by ro70** [comment]
@janmeier @PerGullberg Thank you.
