### ISSUE TITLE
Support multidimensional arrays for PostrgreSQL

### ISSUE THREAD

**Issue by apsavin** [sequelize/sequelize#6737]
## What you are doing?

I'm creating a table

``` js
      // ...
      rows: {
        type: Sequelize.ARRAY(Sequelize.ARRAY(Sequelize.STRING(30))),
      },
      // ...
```
## What do you expect to happen?

`columns character varying(30)[][]` - notice dimensions
## What is actually happening?

`columns character varying(30)[]` - notice dimensions

Dialect: postgres
Database version: 9.5
Sequelize version:  CLI: 2.2.1, ORM: 3.18.0

**Comment by dashmug** [comment]
@apsavin Can you replicate this on the latest sequelize release?

**Comment by Smona** [comment]
Same is happening here for a 2D array of doubles. Setting `defaultValue: new Array(60).fill([])` doesn't help.

**Comment by anuccio1** [comment]
Are multi-dimensional arrays supported? I am having trouble finding any documentation on this

**Comment by squallstar** [comment]
@anuccio1 multidimensional arrays are supported on Sequelize as per https://www.postgresql.org/docs/9.1/static/arrays.html _[...] and a two-dimensional array of text [...]_

```
text[][]
```

**Comment by markjackson02** [comment]
It doesn't look like this is supported yet, can anyone confirm?

**Comment by nastari** [comment]
Sad,
I will have to choose another orm
