### ISSUE TITLE
UUID with unique constraint

### ISSUE THREAD

**Issue by beworker** [sequelize/sequelize#6739]
I have a short question. It might look strange but... I have a field like this:

```
code: {
    type: DataTypes.UUID,
    allowNull: false,
    defaultValue: DataTypes.UUIDV4,
    unique: 'channels_code_unique'
}
```

If it magically occurs that UUIDV4 generates a duplicate id, will the creation of the object fail due to violation of unique index or sequelize will take care for it and will retry with another UUID? Thanks!

**Comment by mickhansen** [comment]
It will fail due to violation of unique index, although that's certainly rare with UUIDv4

**Comment by beworker** [comment]
@mickhansen Thanks for rush response! Where would you implement a promise-based retry for this case: hooks, outside of the model, etc?

**Comment by felixfbecker** [comment]
@beworker For general questions please ask on StackOverflow or Slack. This is an issue tracker for feature requests and bugs.
