### ISSUE TITLE
Duplicate order clause on 

### ISSUE THREAD

**Issue by jlawrencecfm** [sequelize/sequelize#6741]
Hi,

We're having a problem where sequelize is inserting multiple 'ORDER BY' clauses when issuing a query using the MSSQL adapter.
## What you are doing?

``` js
var p1 = Model1.findAll({
            attributes: ['attr1', 'attr2'],
            include: [
                {
                    model: Model2,
                    attributes: ['model2ID', 'model2Name'],
                    where: { model2ID: 5}
                }
            ],
            order: ['createdDate'],
            offset: (0 * 10),
            limit: 10
        });
```
## What do you expect to happen?

The query should execute successfully and return a resultset
## What is actually happening?

A SequelizeDatabaseError is thrown:
Unhandled rejection SequelizeDatabaseError: Invalid usage of the option NEXT in the FETCH statement.

The query was generated incorrectly with two ORDER BY clauses instead of one.  The second one is incorrectly inserted from lib/dialects/mssql/query-generator.js in addLimitAndOffset function, ordering by the primary key of the first table.

``` sql
SELECT
    [model1].[attr1],
    [model1].[attr2],
    [model2].[model2ID] AS [model2.model2ID],
    [model2].[model2Name] AS [model2.model2Name]
FROM
    [model1] AS [model1]
    INNER JOIN [model2] AS [model2] ON [model1].[model2ID] = [model2].[model2ID] AND [model2].[model2ID] = 5
ORDER BY [createdDate] ORDER BY [model1ID]
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;
```

**Dialect:** mssql
**Database version:** SQL Server 12.0.5000.0
**Sequelize version:** 3.24.3

A suggested fix would be to not add a sort if limit and offset is set and force the user to do this themselves (as they would have to when writing a query) - but this could break legacy code that relies on this feature.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/pull/6706
