### ISSUE TITLE
feat: Add new hook `afterBuild`

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#6742]
Right now the best place to set a complex default value that requires promises is in the `beforeCreate` hook, which has some limitations:

- is the field is set as required in the model the it will trigger an error, since `beforeCreate` runs after the validation hooks.

- if the instance is `build()`, and there is no plan to save it but it needs to be validated with `validate()` is won't have those default values, since the `beforeCreate` hook won't be called.

By adding those hooks and moving the logic of creating complex default values from `beforeCreate` to `afterBuild` those issues are fixed and give more options to us devs to overcome edge cases.

So, in resume:

- `afterBuild` will run after a `.build()` call.
- It should run before a `validate()` call, that will 

Thanks

**Comment by diosney** [comment]
Right now to overcome this limitation, I'm doing something like:

```js
beforeValidate: function (instance, options) {
          if (instance.isNewRecord) {
            // Set default value here.
          }
        }
```

**Comment by felixfbecker** [comment]
An `afterBuild` hook cannot be async because `build()` is synchronous. In v4 `User.build()` is even equivalent to `new User()`.

**Comment by diosney** [comment]
@felixfbecker I understand. Then I will have to stick with the `beforeValidate` workaround.
