### ISSUE TITLE
Intended findAndCount functionality

### ISSUE THREAD

**Issue by dsbert** [sequelize/sequelize#6744]
## What you are doing?
I have a many-to-many association. I'm doing a simple `findAndCount` across all rows.

`user <-> user-group <-> group`

In my user table, I have a single user who is a member of 8 groups.

```json
"users": [ "admin" ],
"groups": [
  "foo1",
  "foo2",
  "foo3",
  "foo4",
  "foo5",
  "foo6",
  "foo7",
  "foo8"
]
```

The query

```js
const data = yield User.findAndCount({
  include: [
    {
      model: User.sequelize.models.group,
    },
  ],
});

console.log('count:' + data.count);
// count: 8
```

I understand why this is returning a value of 8 in the database. The join produces 8 rows. However, in the javascript code, my `data.rows` object only actually contains a single row, as the rest of the data has been included as an array on that single row.

Is this the expected behavior? Intuitively, I would expect data.count to be representative of data.row, meaning the count query should only count unique rows of my primary model. With the way it is currently working, the behavior is confusing. In this example, `count` indicates I have 8 rows. However, if I use 8 to perform paging, the result doesn't work out very well.

```js
// Our last call returned a row count of 8
// so I should be able to get the 5th row
// with this query

const data = yield User.findAndCount({
  limit: 1,
  offset: 5,
  include: [
    {
      model: User.sequelize.models.group,
    },
  ],
});

console.log('rows:' + data.rows);
// rows: [ ]
// since the primary model only actually had a single row, this won't work
```

__Dialect:__ mssql
__Database version:__ 2012
__Sequelize version:__ 3.24.4

**Comment by janmeier** [comment]
You can add `distinct: true` to count distinct users.

`findAndCount` maps to separate calls to count and find, so you can pass options through to either http://docs.sequelizejs.com/en/v3/api/model/#countoptions-promiseinteger
