### ISSUE TITLE
Updates Not Persistent

### ISSUE THREAD

**Issue by aaronclong** [sequelize/sequelize#6745]
I have tried many ways to update and persist changes to the database and all of them failed to persist. 

Sometimes functions such as save or update where not available on the instance.

## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_

Model.update({state: 1},{where: {id: 1} }).then();

## What do you expect to happen?
update database entry

__Dialect:postgres

**Comment by felixfbecker** [comment]
The example you gave is working fine
