### ISSUE TITLE
DataTypes.DECIMAL.UNSIGNED is not a valid DataType but it should be...

### ISSUE THREAD

**Issue by Hackbyrd** [sequelize/sequelize#6746]
## What you are doing?

_Post a minimal code sample that reproduces the issue, including models and associations_

``` js
    length: {
      type: DataTypes.DECIMAL.UNSIGNED,
      allowNull: false,
      validate: {
        isDecimal: {
          args: true,
          msg: 'Box length must be a decimal.'
        },
        notIn: {
          args: [[0]],
          msg: 'Box length must be greater than 0.'
        }
      }
    },
```
## What do you expect to happen?

It should create the datatype DECIMAL UNSIGNED, but DataTypes.DECIMAL.UNSIGNED isn't recognized...
## What is actually happening?

/Users/jonathan/Documents/stuff-api/node_modules/sequelize/lib/model.js:95
      throw new Error('Unrecognized data type for field ' + name);
      ^

Error: Unrecognized data type for field length

__Dialect:postgres
__Database version: 9.5.4.1
__Sequelize version: 3.24.5

**Comment by janmeier** [comment]
Needs a backport, see https://github.com/sequelize/sequelize/pull/6281 inspiration
