### ISSUE TITLE
timezone problem

### ISSUE THREAD

**Issue by xycloud** [sequelize/sequelize#6747]
there is a strange problem about timezone within mysql:
version: 

config:
`
    ...
    timezone: '+08:00'
`

model is:

```
module.exports = function (sequelize, DataTypes) {
  var Label = sequelize.define('Label', {
    id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    gmt_create: {type: DataTypes.DATE, allowNull: false}
  }, {
      tableName: 'label',
      freezeTableName: true,
      timestamps: false,
      underscoredAll: true,
    }
  );
  return Label;
};
//gmt_create is a DATETIME type in mysql
```

when insert:

```
  const moment = require('moment');
  const now = moment().format('YYYY-MM-DD HH:mm:ss');
  ...Label.create({gmt_create: now});
```

from the sql log, I can find the datetime is ok. and inserted data in mysql is also ok. but when i select it
, it is less 8 hours comparing with the real time: (when I set timezone with '+00:00' the select is ok, but insert log is less 8 hours.  when I cancel the timezone field, select is still less 8 hours, its so strange, didn't timezone's default value is '+00:00'? )

`
  ...Label.findAll({where:{id:1}});
`

I just wanna the datetime is same with local time whatever select or insert

**Comment by janmeier** [comment]
Are you per ANY change located in UTC-8? Javascript date objects are always formatted in local time.

You should check whether the dates represent the same unix timestamp, not whether they look identical in the db and in node
