### ISSUE TITLE
Which version is stable?

### ISSUE THREAD

**Issue by srcnix** [sequelize/sequelize#6749]
I'm currently starting a new project and I've been playing around with Sequelize. I like it, a lot, but I'm finding there are some noticeable bugs.

As an example, validation rules are applied during create() and save(), but not with validate() - at least not in the latest v3 on NPM. 

However, the Pre-release of v4 seems to work fine with validate() and v3.24.0 seems to work fine also, except v4-PR uses then().catch() correctly, whereas v3.24.0 uses just then() and passes in error.

I was intending to use this ORM in production but can't risk such issues being so different between minor version changes.

Recommendations welcomed!

**Comment by felixfbecker** [comment]
v3 is stable/latest, while v4 is pre-release. Sequelize follows semver and any breaking change will land only in a major version. If you found a bug please open an issue (or rather, please search first if there is one already).
