### ISSUE TITLE
hstore keys renamed when `options.field` is specified on a model column with the same name

### ISSUE THREAD

**Issue by legomind** [sequelize/sequelize#6752]
## What you are doing?

``` js
const Test = sequelize.define('test', {
    testField: {
      field: 'test_field',
      type: STRING,
    }
    kv: HSTORE,
  }, {
    tableName: 'test',
    underscored: true,
    timestamps: true,
  }).schema('public')

await Test.create({
  testField: 'value1',
  kv: { testField: 'value2' },
})

const r = await Test.findAll({ where: { kv: $eq: { testField: 'value2' } } })
```
## What do you expect to happen?

I expected the following SQL Query:

``` sql
SELECT * FROM "public"."test" WHERE "kv" = '"testField"=>"value2"'
```
## What is actually happening?

Instead, I get

``` sql
SELECT * FROM "public"."test" WHERE "kv" = '"test_field"=>"value2"'
```

**Dialect:** postgres
**Sequelize version:** 3.24.3

**Comment by legomind** [comment]
I would be more than happy to submit a PR, but I would need a little guidance as to a starting point.

**Comment by janmeier** [comment]
Where conditions are generated here https://github.com/sequelize/sequelize/blob/95d3a5713499ab90b19d7a312b8cb878b26eb1b4/lib/dialects/abstract/query-generator.js#L1737

So the first thing I would do is see whether the input looks wrong (underscored) here, or if it happens earlier

**Comment by legomind** [comment]
@janmeier thanks. I will start with a failing test, and debug where you indicated.
