### ISSUE TITLE
Instance methods in models retrieved using raw queries

### ISSUE THREAD

**Issue by brunosiqueira** [sequelize/sequelize#6754]
I need to query one model from the database using a raw query, like this

  ```
  db.sequelize.query('select * from users_active where id = :userId', {
      raw: true,
      replacements: {userId: token.userId},
      type: db.sequelize.QueryTypes.SELECT,
      model: db.user
    }).then(function (result) {
     var user = result[1];
     //do anything...
    })
```
Even though I can load the model properly, I can not access instance methods specified in the model definition. Eg:
```

   instanceMethods : {
      validatePassword : function(password, done) {
        crypto.verify(this.passwordSalt, this.passwordHash, password, function(err, valid) {
          return done(valid);
        });
      },
//...
 
```

. Could this be an improvement on next versions or am I forgetting something?

**Comment by felixfbecker** [comment]
http://docs.sequelizejs.com/en/v3/api/sequelize/#querysql-options-promise

> [options.raw]
> Boolean
> If true, sequelize will not try to format the results of the query, or build an instance of a model from the result
