### ISSUE TITLE
update not returning the instance?

### ISSUE THREAD

**Issue by m3l7** [sequelize/sequelize#6757]
update method is not returning correctly the model instance (the query run correctly)

      this.db.models.User.update(fields, { where: { id: 2 }, returning: true})
      .then((data) => {
          console.log(data[0]); // undefined
          console.log(data[1]); // 1
      }

I'm using mariadb 10, sequelize 3.24.3

**Comment by janmeier** [comment]
`returning` is only supported by postgres , http://docs.sequelizejs.com/en/v3/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

**Comment by m3l7** [comment]
so with mysql update() doesn't return the instance?

if I remove the "returning" option:

   this.db.models.User.update(fields, { where: { id: 2 }})
     .then((data) => {
         console.log(data[0]); // 1
         console.log(data[1]); // undefined
     }

is it correct?

**Comment by felixfbecker** [comment]
You need to do a separate `find()`

**Comment by xubayr007** [comment]
Same problem faced by me. I first insert into the table by keeping Status='Pending', then on successful transaction i try to update that row by keeping Status='Success',Everything is going well and promise of sequelize update also executing well but update doesnt happpen and status still showing pending,Help please

**Comment by SalathielGenese** [comment]
Use

```js
model.field = value;
model = await model.save();
```

Thanks to @roychri who just helped me about this.
