### ISSUE TITLE
Sequelize with postgres leaves jest hanging after all tests executed

### ISSUE THREAD

**Issue by LaurentVB** [sequelize/sequelize#6758]
Hello, I have made a sscee for this issue:

1. clone the following repo: https://github.com/LaurentVB/sequelize-hanging-test
2. `npm install`
3. setup an empty postgresql DB named 'test', accessible by 'root' without password
4. `npm test`

## What do you expect to happen?
The test executes and the prompt returns.

## What is actually happening?
After all tests pass, the execution of jest hangs until it's killed with CTRL+C. The same test with an embedded in-memory sqlite DB behaves as expected.

Dialect: postgres
Sequelize version: 3.24.6

**Comment by janmeier** [comment]
This is because sequelize keeps a connection pool, which keeps the process alive. Try setting `pool.timeout`, or calling `sequelize.close` once all tests are done

**Comment by LaurentVB** [comment]
Thanks Jan.
Just tried setting the `pool.maxIdleTime` but it has no influence on this issue.
Will investigate the `sequelize.close` solution.

**Comment by janmeier** [comment]
Hmm yeah, I see that behaviour as well - I've never seen it happen in mocha tests, so it must be something jest is doing :)

Adding
```js
afterAll(function () {
 sequelize.close();
});
```
works fine though

**Comment by julienvincent** [comment]
This is not working anymore. Using latest version of jest and sequelize, jest still hangs after calling sequelize.close()

**Comment by malissa** [comment]
I am also having this problem.

**Comment by malissa** [comment]
@julienvincent I figured out my problem. For me it is the models sync that does not exit. In my test setup I do:

const models = require('../src/db/models');
`beforeAll(() => {
      models.sequelize.sync().then(()=>{
          models.sequelize.close();
      })
});`

**Comment by julienvincent** [comment]
@malissa I am getting this issue after performing _any_ query, not just table syncs

**Comment by dee-el** [comment]
i got this issue too, just hanged

**Comment by mvilrokx** [comment]
This happens with [tape](https://github.com/substack/tape) too btw.  I've tried calling sequelize.close() at then end of my tests as well but it does not end the test.

**Comment by palemium** [comment]
@janmeier I'm getting `(node:50842) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit` error calling `sequelize.close()` and hanged.

**Comment by pkandathil** [comment]
I just used the  --forceExit option and it fixed the freezing issue.

Details:
Doing a sequelize.close() was causing an issue as it needed to be in the afterAll method. But this method had to run after all tests were done. Getting this configured was getting too difficult so I just used the --forceExit flag in Jest and it seems to work.

**Comment by chris-fa** [comment]
Using `jest: 22.4`, `sequelize: 4.37` and `express: 4.16`, I fixed it:

```
// on the tests
beforeAll(() => app.close())  // NOTE: there is NO "end" callback passed

// on app.js
app.on('close', () => sequelize.close())
```

**Comment by bradisbell** [comment]
Is it possible to unref the connection pool somehow so that everything cleans up nicely, and consistently with other apps and databases?

**Comment by adamlutz** [comment]
This works for me: 

```

const db = require('../app/db/models')

before(function(done) {
  db.sequelize.sync({force: true}).then(function() {
    db.sequelize.close();
    done();
  });
});
```

**Comment by adamlutz** [comment]
The cleanest way is by leveraging the global before() and after() hooks.
The following is generally what I use.  This is a my `setup.js` file
```
const db = require('../app/db/models')

before(function(done) {
  db.sequelize.sync({force: true}).then(function() {
    done();
  });
});

after(function(done) {
  db.sequelize.close();
  done();
});

```
and corresponding package.json definition I use to run the full test suite.
```
"scripts": {
    "test": "NODE_ENV=test ./node_modules/.bin/mocha ./tests/**/*.js ./tests/setup.js"
  },
```

**Comment by ladeiko** [comment]
try to set 
pool: { evict: 0 }
for sequelize (internally some timer is created to check connection is alive)

see http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

**Comment by slifty** [comment]
I'm still facing this issue -- I added [more detail here](https://stackoverflow.com/questions/60217417/jest-tests-hang-due-to-open-sequelize-connections)

The issue seems to be that every single test file in Jest opens a new Sequelize connection pool.  Setting evict to 0 did not solve my problem.

**Comment by slifty** [comment]
I found a [solution](https://stackoverflow.com/a/60267873/159522), which was to leverage Jest's [setupFilesAfterEnv](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array) to run `afterAll(() => sequelize.close())` on every test suite.

I know this is similar to what others have suggested, but by putting it inside `setupFilesAfterEnv` it feels like a more appropriate solution since it hits every test without violating DRY.

**Comment by psanchez1982** [comment]
> models.sequelize.sync().then(()=>{ models.sequelize.close(); })

Thanks!! That's helped me a lot!!
