### ISSUE TITLE
String getting cast to number in Model.findAll() [Using sqlite]

### ISSUE THREAD

**Issue by paolo-tanium** [sequelize/sequelize#6766]
## What you are doing?
My string field is getting cast to a number if the contents of the field is a number. For example, if I have store the text `11` in the field `Table.value`, and I execute the following code:

```js

let Sequelize = require('sequelize');

var sequelize = new Sequelize('sqlite://dbName', {
  host: 'localhost',
  dialect: 'sqlite',
  storage: './service/data.db'
});

var Table = sequelize.define('Table', {
    value: {
        type: Sequelize.STRING
    }
});

Table.findAll().then(results => {
    console.log(results[0].value, typeof results[0].value);
});
```

... the result will be `11 'number'`. If I change that same field to `11a`, then it returns the correct type (STRING).

## What do you expect to happen?
Since the field is a field of type STRING, and I defined the model as such, I want it to return a STRING type (not number).

## What is actually happening?
It is returning it of type number.

__Dialect:__ sqlite 
__Database version:__ sqlite3 
__Sequelize version:__ 3.24.0

**Comment by janmeier** [comment]
Can't replicate 

```js

var Table = sequelize.define('Table', {
  value: {
    type: Sequelize.STRING
  }
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => {
    return Table.create({
      value: '11'
    });
  })
  .then(() => {
    return Table.findAll().then(results => {
      console.log(results[0].value, typeof results[0].value);
    });
  })
  .then(console.log)
  .finally(() => sequelize.close());
```
```sql
Executing (default): DROP TABLE IF EXISTS `Tables`;
Executing (default): DROP TABLE IF EXISTS `Tables`;
Executing (default): CREATE TABLE IF NOT EXISTS `Tables` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `value` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Tables`)
Executing (default): INSERT INTO `Tables` (`id`,`value`,`createdAt`,`updatedAt`) VALUES (NULL,'11','2016-10-28 08:27:36.679 +00:00','2016-10-28 08:27:36.679 +00:00');
Executing (default): SELECT `id`, `value`, `createdAt`, `updatedAt` FROM `Tables` AS `Table`;
11 string
undefined
```

Do note, that sqlite is not so strict about the data types - So if you've inserted something as int at some point it might come back as int

**Comment by paolo-tanium** [comment]
@janmeier thanks! I just figured out the problem thanks to your response. 

In your version, sequelize was creating a varchar datatype while I was using STRING. In sqlite's docs:

```
And the declared type of "STRING" has an affinity of NUMERIC, not TEXT.
```

So lesson learned - don't use String datatype when you want to store varchar!
