### ISSUE TITLE
how to create a custom mysql function

### ISSUE THREAD

**Issue by peze** [sequelize/sequelize#6768]
i read the api doc ,find this ：

    something.find({
      order: [
        'name',
        // will return `name`
        'username DESC', 
        // will return `username DESC` -- i.e. don't do it!
        ['username', 'DESC'], 
        // will return `username` DESC
        sequelize.fn('max', sequelize.col('age')), 
        // will return max(`age`)
        [sequelize.fn('max', sequelize.col('age')), 'DESC'], 
        // will return max(`age`) DESC
        [sequelize.fn('otherfunction', sequelize.col('col1'), 12, 'lalala'), 'DESC'], 
        // will return otherfunction(`col1`, 12, 'lalala') DESC
        [sequelize.fn('otherfunction', sequelize.fn('awesomefunction', sequelize.col('col'))), 'DESC'] 
        // will return otherfunction(awesomefunction(`col`)) DESC, This nesting is potentially infinite!
        [{ raw: 'otherfunction(awesomefunction(`col`))' }, 'DESC']
        // This won't be quoted, but direction will be added
        ]
    })

it means i can use 

> otherfunction 

to order the rows, but how can i create a custom mysql function by sequelize?

**Comment by janmeier** [comment]
Creating the function is outside the scope of sequelize - Simply too many intracacies, and its done so seldom, that it doesn't make sense to do so in code - You should do it in sql https://dev.mysql.com/doc/refman/5.7/en/create-function.html

We only support caling the function from sequelize

**Comment by felixfbecker** [comment]
How about we take a JavaScript closure as an argument, parse the source with esprima and translate it to SQL? 😄

**Comment by janmeier** [comment]
@faceleg :gun: :D
