### ISSUE TITLE
Can't define compound primary key made of multiple foreign keys

### ISSUE THREAD

**Issue by mweitzman** [sequelize/sequelize#6769]
## What you are doing?

I'm trying to define a compound primary key made of multiple foreign keys for a weak entity.
I've reduced the problem to a simple analogy that still doesn't work.

``` js
var Sequelize = require('sequelize');
var db = new Sequelize({...});

var Book = db.define('book', {
    id: {
        type: Sequelize.INTEGER.UNSIGNED,
        primaryKey: true
    }
});

var Chapter = db.define('chapter', {
    id: {
        type: Sequelize.INTEGER.UNSIGNED,
        primaryKey: true
    }
});

var Paragraph = db.define('paragraph', {
    id: {
        type: Sequelize.INTEGER.UNSIGNED,
        primaryKey: true
    }
});

Chapter.belongsTo(Book, {
    foreignKey: {
        primaryKey: true
    },
    onDelete: 'CASCADE'});

Paragraph.belongsTo(Book, {
    foreignKey: {
        primaryKey: true
    },
    onDelete: 'CASCADE'});
Paragraph.belongsTo(Chapter, {
    foreignKey: {
        primaryKey: true
    },
    onDelete: 'CASCADE'});

db.sync({force: true, logging: console.log}).catch(function(err) {console.log(err)});
```
## What do you expect to happen?

I expected `sync()` to create the `paragraphs` table including **both** foreign keys as follows

``` sql
CREATE TABLE IF NOT EXISTS `paragraph` (
    `id` INTEGER UNSIGNED ,
    `book_id` INTEGER UNSIGNED ,
    `chapter_id` INTEGER UNSIGNED ,
    PRIMARY KEY (`id`, `book_id`, `chapter_id`),
    FOREIGN KEY (`book_id`) REFERENCES `book` (`id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (`chapter_id`) REFERENCES `chapter` (`id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;
```
## What is actually happening?

Only _one_ foreign key is being created

``` sql
CREATE TABLE IF NOT EXISTS `paragraph` (
    `id` INTEGER UNSIGNED ,
    `book_id` INTEGER UNSIGNED ,
    `chapter_id` INTEGER UNSIGNED ,
    PRIMARY KEY (`id`, `book_id`, `chapter_id`),
    FOREIGN KEY (`book_id`) REFERENCES `book` (`id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;
```

**Dialect:** mysql
**Database version:** mysql Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper
**Sequelize version:** 3.24.6

**Comment by branmcf** [comment]
I'm trying to do the same thing and experiencing the same problem. Did you ever find a solution?

**Comment by mweitzman** [comment]
No, I found very complex workarounds, but it made other things stop working.

In the end I stopped using sequelize, the outstanging amount of bugs and missing features, in addition to the lack of support makes this package completely unsuitable for production.

**Comment by yonjah** [comment]
@mweitzman  what did you end up using ?
I agree Core team has a lot on their mind and it seem most focus went to shipping 4.x and some issues like this one fell between the cracks. Notice that this highly popular open source project so core is mostly volunteers helping out of their own free time. Personally I couldn't find any better ORM for my needs and I found the team here mostly responsive and quick to solve issues and merge pull requests.

@branmcf This is a funny bug due to redundant primary key being left on the target model attribute.
I'll try and get a pull request going, but as a temporary work around you can change the order of defining relationships on your Models (so first use them as target for relationship and only then as source) -
```javascipt
Paragraph.belongsTo(Chapter, {
    foreignKey: {
        primaryKey: true
    },
    onDelete: 'CASCADE'});

Paragraph.belongsTo(Book, {
    foreignKey: {
        primaryKey: true
    },
    onDelete: 'CASCADE'});

Chapter.belongsTo(Book, {
    foreignKey: {
        primaryKey: true
    },
    onDelete: 'CASCADE'});
```

So this will work fine with current version (Personally I wouldn't trust an orm with defining my schema and prefer this to so it manually but this is up to you)

**Comment by yonjah** [comment]
Sorry I just realized I missed your whole point of having compound primary keys.

So My suggestion won't work since you the keys will still be defined separately instead as a compound PK. 
There is a discussion about compound keys here -
https://github.com/sequelize/sequelize/issues/1485

**Comment by abelosorio** [comment]
I'm facing the same situation. I have a n-m relationship and I want to use a composite primary key in the association table.

I think this issue should be re opened and discussed.

Thanks!

**Comment by abelosorio** [comment]
No-so-pretty workaround (using Postgres):

```javascript
export default (sequelize, DataTypes) => {
  const EventProgram = sequelize.define('eventProgram', {
    eventId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true
    },
    programId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true
    }
  });

  EventProgram.associate = (models) => {
    EventProgram.belongsTo(models.event);
    EventProgram.belongsTo(models.program);
  };
};
```

```
xxx=# \d+ "eventPrograms"
                              Table "public.eventPrograms"
  Column   |           Type           | Modifiers | Storage | Stats target | Description 
-----------+--------------------------+-----------+---------+--------------+-------------
 eventId   | integer                  | not null  | plain   |              | 
 programId | integer                  | not null  | plain   |              | 
 createdAt | timestamp with time zone | not null  | plain   |              | 
 updatedAt | timestamp with time zone | not null  | plain   |              | 
Indexes:
    "eventPrograms_pkey" PRIMARY KEY, btree ("eventId", "programId")
Foreign-key constraints:
    "eventPrograms_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE
    "eventPrograms_programId_fkey" FOREIGN KEY ("programId") REFERENCES programs(id) ON UPDATE CASCADE ON DELETE CASCADE
```
