### ISSUE TITLE
Async validation functions failing

### ISSUE THREAD

**Issue by leebenson** [sequelize/sequelize#6770]
Not the fault of Sequelize, but please bump lodash at the next release. Using async validator functions yields this error:

> Error: Members of the validate option must be functions

See [here](https://github.com/lodash/lodash/issues/2768) for why.

**Comment by janmeier** [comment]
Can you ping me when the new version is released :)?

**Comment by leebenson** [comment]
sure, will do

**Comment by felixfbecker** [comment]
Isn't that a patch version? Should be picked up automatically

**Comment by leebenson** [comment]
Actually yeah, looks like it is.

**Comment by felixfbecker** [comment]
Okay, closing then

**Comment by felixfbecker** [comment]
Actually: our lodash version is pinned https://github.com/sequelize/sequelize/blob/master/package.json#L47

No idea why. This is exactly the kind of problems it causes.

**Comment by felixfbecker** [comment]
Also, why are we not simply doing `typeof x === 'function'`?

**Comment by felixfbecker** [comment]
> ```js
> // The use of `Object#toString` avoids issues with the `typeof` operator 
> // in Safari 9 which returns 'object' for typed arrays and other constructors. 
> ```

Sequelize will never, ever run in Safari 9. It also will never ever accept a `TypedArray` constructor for a validator. We really need to stop using lodash everywhere. Another example: `_.isPlainObject()` prevents us from passing instances.

**Comment by leebenson** [comment]
I was going to post those things in another issue (I followed the trail down to lodash, and saw it's _toString workaround to appease Safari 9). Lodash is a great utility belt, but it's 90% redundant on Node. There are native/faster alternatives nowadays.

**Comment by felixfbecker** [comment]
100% agree. During ES6 refactor I tried to change a lot of `_.each` to `for of`, `_.assign` to `Object.assign`, but there is a lot left.

**Comment by mickhansen** [comment]
It's mostly redundant, but it's still faster than native in a few cases.

**Comment by leebenson** [comment]
Lodash is well organised - it's easy to pull in the pieces that JS either lacks, or where it offers a faster-than-native alternative. Definitely not the case with everything though (e.g. `typeof x === 'function'` has gotta be faster than `Object.toString()` followed by several string comparisons).

Now that Node 6.x has entered LTS and 6.x has [99% support](http://node.green/) of ES6, it's a safe bet to gut out most of it. Would be happy to help with the effort.

**Comment by janmeier** [comment]
We are committed to supporting node 4 as long as it is still in LTS (until april 2017), but we would definitely welcome all changes that work on node 4 as well ;)

**Comment by leebenson** [comment]
Understood @janmeier. I'll jump in after April, then, if you'd welcome the help. We can make things far prettier when Node 4 is relegated to the boneyard.

**Comment by felixfbecker** [comment]
@leebenson for example? 99% of our lodash use will work with native Node 4 functions too. The difference between Node 6 and Node 4 is not that big, it is only a few features like destructuring assignments.

**Comment by leebenson** [comment]
@felixfbecker - not even lodash specifically, just a general tidy-up. In no particular order...

- Default function parameters
- Rest/spread params
- for... of (probably fine in 4, unless anything needs throwing/breaking)
- Destructuring
- Proper use of `const`
- `this` scoped generators
- Array sub-classes to replace lodash features (if needed)
- Object.getOwnPropertyNames (if there's any need to iterate over 'shallow' keys)
- etc

It's possible (even likely) that none of the above is a bottleneck to replacing lodash 100% - or that you'll even need half that stuff - but if it's an opportunity to dig into the internals and fully take advantage of ES6, then it'd be nice to do it in one go. A lot of the above crops up in my own code, and Node 6/7 means I'm finally free of a transpilation step.

**Comment by lekhnath** [comment]
I am getting `Error: Members of the validate option must be functions.` what should I do? I've validate option configured as below:

Node v8.0.0
Sequelize : v3.30.4

```
uniqueName: async function uniqueName() {
  try {
    // Validation goes here
  } catch (e) {
    throw e;
  }
}
```

**Comment by felixfbecker** [comment]
@lekhnath validation must be synchronous.
