### ISSUE TITLE
Don't pin version dependencies

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6771]
Currently inflection, generic-pool, lodash and wkx are pinned to a fixed patch release. node-uuid is pinned to a minor.
This means that users will not get bug fixes for these libraries if they are released (unless we bump the version too and make another release, which we don't so often). It causes stuff like #6770.
It also means users will always have two versions of the libraries installed if they depend on it in another way.
There is no reason for this: In a semver-following package, nothing can break during a minor or patch release. Of course, mistakes can happen, but if the user wants to protect himself against that there is npm-shrinkwrap. It should be the user's decision whether to lock dependencies or use soft versioning.

**Comment by mickhansen** [comment]
inflection is fixed because it can break sequelize in a semver major way

**Comment by felixfbecker** [comment]
Maybe we can keep it for inflection, but for all others it is unneeded.

**Comment by Hoverbear** [comment]
Please note NPM does not require this.
