### ISSUE TITLE
addAssociation on a new record causes an UPDATE

### ISSUE THREAD

**Issue by fpolowood** [sequelize/sequelize#6778]
### add{Association} to a built object
After generating a sequelize object using .build and verifying that it has a isNewRecord, I did not expect that adding an associated record would trigger an UPDATE on the database.

```js
var User = sql.define('user', {
  id:{
    type:sequelize.INTEGER,
    primaryKey:true
  }
});

var Project = sql.define('project', {
  projectID:{
    type:sequelize.INTEGER,
    primaryKey:true
  }
});
 
Project.hasMany(User, {foreignKey:'projectID'});
var project = Project.build();
var user = User.build();
project.addUser(user);
```

## What do you expect to happen?
I expected that, since both objects are marked as isNewRecord:true, there wouldn't be any attempts to write to the database until the project was save(d), which is what the documentation implies:
_Using the build-method will return an unsaved object, which you explicitly have to save._ [http://docs.sequelizejs.com/en/v3/docs/instances/](url)

## What is actually happening?
But, as soon as addUser is executed, sequelize attempts to update records in a potentially unsafe way.  If all the records involved are new records, there shouldn't be any need for this UPDATE.
``` SQL
Executing (default): UPDATE `users` SET `projectID`=NULL,`updatedAt`='2016-10-31 14:57:10' WHERE `id` IN (NULL)
```

__Dialect:__ mysql 
__Sequelize version:__ 3.24.6

**Comment by hongymagic** [comment]
I was also looking for something like this for 1:m mapping:

```
User.hasMany(Task);

const user = await User.find(...);
user.addTask({ ... except user_id });
```

But it seems that according to document this is only available for `belongsToMany`, http://docs.sequelizejs.com/manual/tutorial/associations.html#belongs-to-many-associations

Either way executing `UPDATE` is probably not the right implementation here.
