### ISSUE TITLE
How to query data with id in('1', '2', ...) through sequelize and use the index and do not full table scan

### ISSUE THREAD

**Issue by shuperry** [sequelize/sequelize#6780]
```
model.findAll({
  where: {
    id: {
      $in: ['1', '2', ...]
    }
  }
})
```

This way will abandon the index and scan full data of table, can we use this way and use the index enforce?

**Comment by janmeier** [comment]
What index? Why will this abandon the index? What does the query look like, and what do you wish it to look like? (basically everything the template you removed told you to fill out)

[SSCCE](HTTP://SSCCE.ORG/)

**Comment by shuperry** [comment]
@janmeier The id field is primary key, the sql is 
`select ... from table where id in('1', '2', '3', ...)`
I run this sql and explain it, the result shows full table scan.

**Comment by janmeier** [comment]
Please look at the [SSCCE](HTTP://SSCCE.ORG/) link I posted, and create a complete, self-contained test case that shows the issue.

If your DB is not hitting the index, thats not really something we can do anything about
