### ISSUE TITLE
Deep Create With Associations

### ISSUE THREAD

**Issue by timscott** [sequelize/sequelize#6785]
[Creating with associations](http://docs.sequelizejs.com/en/latest/docs/associations/#creating-with-associations) more than one level down seems to not be working or is not supported. I tried by simply nesting attributes. Most ORMs support cascading persistence, and it would be nice to have that with Sequelize. Thanks!

**Comment by felixfbecker** [comment]
What exactly did you try?

**Comment by timscott** [comment]
This is the exact structure (content is faked):

```javascript
let params = {
  foo: 123,
  groups: [{
    foo: 123,
    items: [{
      foo: 123,
    }]
  }],
  items: [{
    foo: 123
  }]
};
Bar.create(params, {
  include: [
    Bar.Groups,
    Bar.Items
  ]
});
```

The Bar is created as well as the group and the immediate child item. The child items of the group are not created.

**Comment by felixfbecker** [comment]
Try 
```js
Bar.create(params, {
  include: [
    { association: Bar.Groups, include: [ Bar.Items ] }
    Bar.Items
  ]
});
```

**Comment by timscott** [comment]
Thanks @felixfbecker. I just figured that out by trial and error. Might be good to add an example to the docs in the "Creating with associations" subsection. Is it possible to contribute to the docs?

**Comment by felixfbecker** [comment]
Yes, the guides are in markdown

**Comment by timscott** [comment]
Pull request created. https://github.com/timscott/sequelize/pull/1

**Comment by felixfbecker** [comment]
You need to submit the PR to Sequelize, not your fork 😉

**Comment by timscott** [comment]
It's been a while since I made a PR to someone else's OSS project. I think I did it right now: https://github.com/sequelize/sequelize/pull/6791 :)

**Comment by sushantdhiman** [comment]
Docs Updated https://github.com/sequelize/sequelize/commit/a89fda26d0af67e6b6ff885e0bcc896e5c5d1035
