### ISSUE TITLE
Using other models in instance methods

### ISSUE THREAD

**Issue by olalonde** [sequelize/sequelize#679]
I was wondering if there is any way at all to use other models from within instance methods. I have been trying to but keep getting this error:

``` javascript
node_modules/pg/lib/client.js:160
      throw error;
            ^
TypeError: object is not a function
    at sequelize.define.instanceMethods.populateSampleData (models/Client.coffee:17:18)

```

**Comment by francof** [comment]
The solution from @janmeier works, but becomes cumbersome when used with an app with the structure in:
https://github.com/sequelize/express-example/blob/master/models/index.js

As a sequelize user I can't find a nice solution... 
the ideas here http://www.redotheweb.com/2013/02/20/sequelize-the-javascript-orm-in-practice.html (using __factory feels hackish)

Am I missing something?

**Comment by mickhansen** [comment]
@francof A usual practice is just to attach the models to the sequelize instance.

**Comment by fabiomartins87** [comment]
I use the sequelize instance and it works great;
An example of a simple user model file with and example class method.

```
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('comment', { 
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
      },
      name: {
           type: DataTypes.TEXT,
      }
    }, {
      classMethods: {
          exampleFunction: function(id){
                var Model = sequelize.models.example_model;
               model.create({id: id});
          }
      }
}
```

**Comment by angelxmoreno** [comment]
whoa, @fabiomartins87 nice find.

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/en/latest/api/sequelize/#modelmodelname-model

**Comment by lemol** [comment]
The solution I found works well with the structure in https://github.com/sequelize/express-example/blob/master/models/index.js also:

```javascript
var instanceMethodsPure = {
  // ...
};

var instanceMethodsDb = function(models) {
  return {
    example: function() {
      return models.Example.findById(this.exampleId);
    }
  };
};

module.exports = function(db, DataTypes) {
  var User = db.define('User', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true
    }
 }, {
    tableName: 'pl_users',
    instanceMethods: instanceMethodsPure,
    classMethods: {
      associate: function(models) {
        User.belongsTo(models.UserType, {as: 'type', constraints: true});
        User.Instance.prototype = _.extend(User.Instance.prototype, instanceMethodsDb(models));
      }
   }
};

```

**Comment by mujtaba01** [comment]
Other models can be accessed using first argument of the exported function 
`module.exports = function(db, DataTypes) {
  var User = db.define('User', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true
    }
 }, {
    instanceMethods: instanceMethodsPure,
    classMethods: {
       firstMethod: function() {
         db.models.OtherModel.findAll().then(function() {
             //doSomething
         });
       }
   }
};`

**Comment by mujtaba01** [comment]
Other models can be accessed using first argument of the exported function 
```js
module.exports = function(db, DataTypes) {
  var User = db.define('User', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true
    }
 }, {
    instanceMethods: instanceMethodsPure,
    classMethods: {
       firstMethod: function() {
         db.models.OtherModel.findAll().then(function() {
             //doSomething
         });
       }
   }
};
```

**Comment by mikefowler** [comment]
For those using ES6 classes in Sequelize, here's yet another way to skirt this issue, which takes advantage of the fact that the `sequelize` instance is set as a static property on every model class:

```js
// Foo.js

class Foo extends Sequelize.Model {
  get(id) {
    // ...
  }
}

export default (sequelize) => {
  Foo.init(schema, { sequelize });
}

// Bar.js

class Bar extends Sequelize.Model {
  get foo() {
    const Foo = Bar.sequelize.model('Foo');
    // OR
    const { Foo } = Bar.sequelize.models;

    return Foo.get(1);
  }
}

export default (sequelize) => {
  Bar.init(schema, { sequelize });
}
```
