### ISSUE TITLE
cockroachdb question

### ISSUE THREAD

**Issue by edwardsmarkf** [sequelize/sequelize#6799]
hello - 

i am trying to use sequelize with cockroachdb.  supposedly cockroachdb has all the same protocols as posgresql.

when i start up cockroach i see the following:

build:      beta-20161013 @ 2016/10/25 17:49:20 (go1.7.1)
admin:      http://localhost:8080
sql:        **postgresql://root@localhost:26257?sslmode=disable**
logs:       cockroach-data/logs
store[0]:   path=cockroach-data
status:     initialized new cluster
clusterID:  {9ebbf706-4d58-405c-a66a-7c9c106281ff}
nodeID:     1

my simple code looks like this:

var sequelize = new Sequelize('transanlys', 'maxroach', 'password', {
  host: 'localhost',
  port:  '26257',
  dialect: 'postgres',

  pool: {
    max: 5,
    min: 0,
    idle: 10000
  },

});
**// i tried this too:
//var sequelize
//= new Sequelize('postgres://maxroach@localhost:26257?sslmode=disable/transanlys');**

sequelize.query("SELECT * FROM `grandparenttable`", { type: sequelize.QueryTypes.SELECT})
  .then(function(users) {
        console.log(users);
    // We don't need spread here, since only the results will be returned for select queries
}

error:

Unhandled rejection error: unimplemented
    at Connection.parseE (/root/nodeTest/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/root/nodeTest/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/root/nodeTest/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20

i also tried this using a model but received the same error.

any idea what the problem might be?

**Comment by felixfbecker** [comment]
Seems like Sequelize uses some SQL that CockroachDB doesn't support... But given that it's only a simple SELECT I'm not sure. The error should have more properties, try to set a breakpoint or catch and log the error.

**Comment by sushantdhiman** [comment]
May be try without `?sslmode=disable/transanlys`

**Comment by edwardsmarkf** [comment]
>> May be try without ?sslmode=disable/transanlys
same error

**Comment by edwardsmarkf** [comment]
>>> Seems like Sequelize uses some SQL that CockroachDB doesn't support... But given that it's only a >>>simple SELECT I'm not sure. The error should have more properties, try to set a breakpoint or catch >>>and log the error.

strangely enough, try/catch does not seem to even go into catch.

**Comment by edwardsmarkf** [comment]
here is the entire script:

> var Sequelize = require('sequelize');
> var sequelize   = new Sequelize('postgres://maxroach@localhost:26257');
> 
> sequelize.query("SELECT * FROM `grandparenttable`", { type: sequelize.QueryTypes.SELECT})
>   .then(function(users) {
>         console.log(users);
> })

**Comment by felixfbecker** [comment]
You can't try/catch a promise, you need to call `.catch(err => console.error(err))`

**Comment by edwardsmarkf** [comment]
>>> You can't try/catch a promise, you need to call .catch(err => console.error(err))

awesome - here is what i see now:

{ error: unimplemented
    at Connection.parseE (/root/nodeTest/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/root/nodeTest/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/root/nodeTest/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'error',
  length: 78,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'sql/pgwire/v3.go',
  line: '674',
  routine: '(*v3Conn).sendError' }
undefined

**Comment by janmeier** [comment]
Have you tried connecting directly using node postgres? (with without
sequelize)

It seems that the database is sending a message the driver isn't expecting

**Comment by edwardsmarkf** [comment]
>>> Have you tried connecting directly using node postgres? (with without sequelize)

yes i have - here is the code (cut/paste from the cockroach site)

>>>var pg = require('pg');
>>>
>>>var config = {
>>>  user: 'maxroach',
>>>  host: 'localhost',
>>>  database: 'transanlys',
>>>  port: 26257
>>>};

>>>pg.connect(config, function (err, client, done) {
>>>  var finish = function () {
>>>    done();
>>>    process.exit();
>>>  };

  if (err) {
    console.error('could not connect to cockroachdb', err);
    finish();
  }

**Comment by felixfbecker** [comment]
Could also be the client is sending a message the server isnt expecting. CockroachDB only implements a subset of the SQL standard

**Comment by felixfbecker** [comment]
Does the query work with raw pg?

**Comment by edwardsmarkf** [comment]
>>> Could also be the client is sending a message the server isnt expecting. 

i wonder if there is a way to trap for those messages?

>>> CockroachDB only implements a subset of the SQL standard

i could ask this on the CockroachDB forum, but thought i better start here first.

**Comment by edwardsmarkf** [comment]
>>  Does the query work with raw pg?

it works with node pg, so i would assume so - felix did you read your email ?

**Comment by felixfbecker** [comment]
Sure.
Could you set `logging` parameter in the Sequelize constructor? Because if it is the exact same SQL query there is no reason why it should work in pg and not in Sequelize 🤔

**Comment by edwardsmarkf** [comment]
i set logging but didnt see anything different:

>var Sequelize = require('sequelize');
>function mark(e)        {    /*added */
>        console.log(e)  ;
>}
>var sequelize = new Sequelize('transanlys', 'maxroach', 'password', {
>  host: 'localhost',
>  port:  '26257',
>  dialect: 'postgres',
>logging: mark,    /*added */
>  pool: {
>    max: 5,
>    min: 0,
>    idle: 10000
>  },
>});
>sequelize.query("SELECT * FROM `grandparenttable`", { type: sequelize.QueryTypes.SELECT})
>  .catch ( (err) => { console.log(err);  })
>  .then(function(users) {
>        console.log(users);
>})

**Comment by edwardsmarkf** [comment]
any ideas on this?

**Comment by felixfbecker** [comment]
Setting `logging` should log the SQL statement executed to the console. I would like to compare it to the original query.
Your pg example only connects, but doesn't do a query, have you tried that?

**Comment by edwardsmarkf** [comment]
>>  Setting logging should log the SQL statement executed to the console. 
>> I would like to compare it to the original query.

agreed - but the logging is not showing me anything new.  i will display the results below.

>>  Your pg example only connects, but doesn't do a query, have you tried that?

yes, this simple cut/paste example works fine:

>var pg = require('pg');
>var util = require('util');
>var config = {
>  user: 'maxroach',
>  host: 'localhost',
>  database: 'transanlys',
>  port: 26257
>};
>pg.connect(config, function (err, client, done) {
>  var finish = function () {
>    done();
>    process.exit();
>  };
>  client.query('SELECT grandParentTable_name FROM grandparenttable;', function (err, result) {
>    if (err) throw err;
>    console.log('results:' + util.inspect(result.rows));
>    client.end(function (err) {
>      if (err) throw err;
>    });
>  });
>});


simple sequelize code:

>var Sequelize = require('sequelize');
>var sequelize = new Sequelize('transanlys', 'maxroach', '', {
>  host: 'localhost',
>  port:  '26257',
>  dialect: 'postgres',
>logging: console.log,
>  pool: {  max: 5,  min: 0, idle: 10000
>  },
>});
>
//var sequelize = new Sequelize('postgres://maxroach@localhost:26257?sslmode=disable/transanlys');
>
>sequelize.query("SELECT * FROM `grandparenttable`", { type: sequelize.QueryTypes.SELECT})
>  .catch ( (err) => { console.log(err);  })
>  .then(function(users) {
>        console.log(users);
>})

results shown again:

> { error: unimplemented
>     at Connection.parseE (/root/nodeTest/node_modules/pg/lib/connection.js:554:11)
>     at Connection.parseMessage (/root/nodeTest/node_modules/pg/lib/connection.js:381:17)
>     at Socket.<anonymous> (/root/nodeTest/node_modules/pg/lib/connection.js:117:22)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:548:20)
>   name: 'error',
>   length: 78,
>   severity: 'ERROR',
>   code: 'XX000',
>   detail: undefined,
>   hint: undefined,
>   position: undefined,
>   internalPosition: undefined,
>   internalQuery: undefined,
>   where: undefined,
>   schema: undefined,
>   table: undefined,
>   column: undefined,
>   dataType: undefined,
>   constraint: undefined,
>   file: 'sql/pgwire/v3.go',
>   line: '674',
>   routine: '(*v3Conn).sendError' }
> undefined

**Comment by edwardsmarkf** [comment]
stupid question:  cockroach only started [implementing passwords the past couple of days](https://forum.cockroachlabs.com/t/creating-user-passwords/334).  by any chance is this some password issue where sequelize insists on using a password?  i was tempted to play with that, but somehow this seems unlikely.

also, i realize that cockroachdb is rather experimental - and i very much appreciate the help !

**Comment by edwardsmarkf** [comment]
[from the cockroach forum regarding deepstream connectors:](https://forum.cockroachlabs.com/t/deepstream-io-connector/295/2

> i am getting the impression that whatever can talk to posgresql can talk to cockroachDB - true ?

>> Sort of... Cockroach has elected to implement the Postgres wire protocol rather than making a new one, so most of the drivers and connectors that work with Postgres in the language of your choice should be able to connect to a Cockroach node and execute commands. However, Cockroach's SQL dialect does not currently and I don't believe plans to ever have parity with that of Postgres, so things which rely on certain SQL functions or features, such as ORMs, likely will not work with Cockroach as they do with Postgres, if they work at all.)

**Comment by felixfbecker** [comment]
Even though it only implements a subset of SQL I doubt it would choke on a simple SELECT - especially when the example works fine with pg. Are you 100% sure that the logged SQL is the same?

**Comment by edwardsmarkf** [comment]
100% sure:

ordinary pg-node connector:
>  client.query('SELECT grandParentTable_name FROM grandparenttable;', function (err, result) {

sequelize:
> sequelize.query("SELECT grandParentTable_name FROM grandparenttable", { type: 

i tried with and without the backtick   ~  character

**Comment by edwardsmarkf** [comment]
CLOSING - cockroachdb now has passwords, and that seemed to fix it.  i ran into another issue straight away and i will post that as a new issue.
