### ISSUE TITLE
Use async as sync in hook!!

### ISSUE THREAD

**Issue by Hamiid** [sequelize/sequelize#6800]
Sorry me for the bad title of this issue, but I can't find a better one. 
I want to check username is already taken or not before create a new user. So I write a method for my user model that do for me and call it in `beforeCreate` hook. 
The problem is `findOne` method is async and new user added to database before I get the result of the `username checker` method. 
How can I wait for the result of checking username and after that save the user?

**Comment by felixfbecker** [comment]
your hook can return a promise

**Comment by carlosscheffer** [comment]
I have the same problem, have you found a solution?

**Comment by exos** [comment]
Same here

**Comment by hamidhadi** [comment]
@carlosscheffer @exos Finally I returned a promise in `beforeCreate` hook in this way:

```javascript
let User = sequelize.define('User', {/* Model Config */})
// - Username Checker -------------
    User.usernameChk = function(username) {
        return this.findOne({where: {username: username}});
    };

User.hook('beforeCreate', function(instance, options) {
    // Some codes .....

    return new Promise((resolve, reject) => {
        this.usernameChk(instance.dataValues.username).then((foundedInstace)=>{
            if(foundedInstace !== null){
                reject('This username is already taken!');
            }
            resolve(foundedInstace);
        });
    });
}
```

**Comment by exos** [comment]
Yes I fix it by the same way, but it's an ISSUE.

**Comment by Papooch** [comment]
How it it an issue when the solution was in front of you all the time? Either return a promise or define the function as `async` and then you can use `await` in the hook.
