### ISSUE TITLE
Upsert to update the association?

### ISSUE THREAD

**Issue by Abhimanyu310** [sequelize/sequelize#6808]
I have a Project model and a FacultyInfo Model and the relation between the two is:

```js
Project.belongsTo(models.FacultyInfo, {
              as : 'Faculty',
              onDelete: "CASCADE"
          })
```
Now when creating the models, I use a web form to submit the data and create both the models simultaneously as below:
```js
var project = models.Project.create({
        description: req.body.description,
        url: req.body.url,
        // ...
        Faculty: {
            name: req.body.name,
            email: req.body.email,
            }
    }, {
        include: [ {model: models.FacultyInfo, as: 'Faculty'} ]
    }).then(function (task) {
        //
    });
```
And this works perfectly. Now I want to do an upsert in a similar way. In the above code, if I replace `create` with `upsert`, and pass in the primary key for the Project as an argument, the Project model gets updated (if found), but the FacultyInfo model does not get updated. And if the project was not found, it gets created (as expected), but the FacultyInfo model does not get created, and the faculty_id in the projects table which is the foreign key stays at `Null`

Maybe, there is a way to get upsert working the way I want, but I haven't been able to find it, and I've searched so many posts on github/stackoverflow and what not.

I would appreciate if someone would show me how to achieve this, or show me an alternative way to achieve this.

**Comment by felixfbecker** [comment]
I think this is not supported atm, but it would be a nice feature!
For the time being, you must use separate function calls.

**Comment by zlatinejc** [comment]
So this feature would mean that you coul actually update associated models when passed as an attribute, correct ?

**Comment by EugineBelfer** [comment]
It would be the greatest feature ever!
Cause for current moment I can easily CREATE instance with associations(using INCLUDE option). 
But if I want to update instance with some changes in instances, associated with parent one, it become really painful.
 Or maybe I don't know how to do it. Any ideas, guys?

**Comment by yussinsharp** [comment]
I agree! I had this functionality in a RethinkDB ORM called [Thinky](https://justonepixel.come/thinky) and it made my API endpoints really clean and simple. I have a Practitioner-Service m2m relationship and it would be great if I could do:

```js
const p = await Practitioner.findOne({
  where: { id: practitioner.id },
  include: [{ model: Service, as: 'services' }],
});

// Now we can remove/add more services
p.services.pop();
await p.save();
// p.services.length === 1

// Add by pushing in another service object, if object does not have id, we create
p.services.push(anotherServiceObject);
await p.save();
// p.services.length === 2
```

**Comment by eth0izzle** [comment]
+1

**Comment by johncade** [comment]
👍

**Comment by joesabido** [comment]
+1

**Comment by dariospadoni** [comment]
+1

**Comment by vidit-bhatia** [comment]
+1

**Comment by dennerevaldt** [comment]
+1

**Comment by candreoliveira** [comment]
+1

**Comment by droconnel22** [comment]
+1

**Comment by iamjoyce** [comment]
`instance.update(..)` has the same problem

**Comment by wilson-adap** [comment]
+1

**Comment by lpedromachado** [comment]
I too need this badly, but given that it is not possible with 'upsert' (nor with 'findOrCreate'), how can we achieve what the OP wants with what Sequelize offers?

**Comment by WTKersten** [comment]
+1 would be a clean feature for upsert

**Comment by atishayjain** [comment]
+1

**Comment by NijsTom** [comment]
+1

**Comment by lracicot** [comment]
+1

**Comment by papb** [comment]
This has been centralized in #11836
