### ISSUE TITLE
`crypto.randomBytes` is called sychronously for every query to generate an unused UUID

### ISSUE THREAD

**Issue by brendanlong** [sequelize/sequelize#6814]
I ran my program with `--trace-sync-io` and got:

    WARNING: Detected use of sync API
    at _rng (/home/blong/trello-idea-powerup/node_modules/node-uuid/uuid.js:60:53)
    at v4 (/home/blong/trello-idea-powerup/node_modules/node-uuid/uuid.js:224:55)
    at Query (/home/blong/trello-idea-powerup/node_modules/sequelize/lib/dialects/mysql/query.js:14:20)

The relevant line is:

    this.uuid = uuid.v4();

The problem is that [this internally calls `crypto.randomBytes` synchronously](https://github.com/broofa/node-uuid/issues/150).

The weird thing is that you don't seem to actually use this UUID at all, so I'm not sure what the point of generating it every time is anyway?

**Comment by felixfbecker** [comment]
What makes you think it is not used? UUIDs are used for transactions. I don't think the async crypto API would be faster given UUIDs are very short.

**Comment by sushantdhiman** [comment]
Using async version of `crypto.randomBytes` will not improve performance by any measurable metric. On other hand using async version of that will introduce unnecessary complexity in code base.

There is not much to gain by moving to async api for method with very small footprint on resources.
