### ISSUE TITLE
Validation doesn't work with custom message

### ISSUE THREAD

**Issue by Jonik19** [sequelize/sequelize#6816]
`isURL` validatation doesn't work if I'm passing an options object to args. I use `isURL` instead of `isUrl`. If I use `isUrl` it doesn't work, though in the docs is wrote nothing about `isURL`.

Doesn't work:
```js
url: {
      type: DataTypes.STRING,
      field: 'url',
      allowNull: false,
      validate: {
        isURL: {
          args: {
            protocols: ['https'],
            require_protocol: true,
          },
          msg: 'Incorrect URL'
        }
      }
    }
```
Works, but without custom message:

```js
url: {
      type: DataTypes.STRING,
      field: 'url',
      allowNull: false,
      validate: {
        isURL: {
            protocols: ['https'],
            require_protocol: true
        }
      }
    }
```

I want to get validation work with custom message.

**Comment by felixfbecker** [comment]
Please see the documentation for https://www.npmjs.com/package/validator

**Comment by Jonik19** [comment]
@felixfbecker I saw it. I pass correct options. It works in my last example, but doesn't in first.

**Comment by ro70** [comment]
https://github.com/sequelize/sequelize/issues/6628

**Comment by janmeier** [comment]
Closed as duplicate
