### ISSUE TITLE
BeforeFind hook called without model

### ISSUE THREAD

**Issue by euqen** [sequelize/sequelize#6817]
Hi, everyone! Doing:

```js
let MyModel = db.define('MyModel', {...}, {...})
```

```js
MyModel.findOne({ where: {id: 'my-id'}})
```

```js
MyModel.addHook('beforeFindAfterOptions', function(options) {
    console.log(options.model); // undefined
};

MyModel.addHook('beforeFind', function(options) {
    console.log(options.model); // undefined
};
```
After query above, this hooks have been called without model `MyModel` included. I think it might be better to always  include current model to hook arguments, because currently I need to determine by what model I performing query.

**Comment by felixfbecker** [comment]
I'm not sure, but the model might be available under `this`

**Comment by euqen** [comment]
let me check

**Comment by euqen** [comment]
@felixfbecker yes, it works. Thank you! It will be awesome, if you add this info in documentation :+1:

**Comment by sushantdhiman** [comment]
No need to add this in docs, calling a method on object will point to that object via `this`

**Comment by felixfbecker** [comment]
@sushantdhiman It is not clear though that a function you had through `addHook()` will be attached/applied with `this` to the Model
@euqen If you want to do a PR I think this would be a nice addition to the docs
