### ISSUE TITLE
new cockroachdb issue

### ISSUE THREAD

**Issue by edwardsmarkf** [sequelize/sequelize#6821]
simple cockroachdb script is giving me issues:

>var Sequelize = require('sequelize');
>var sequelize = new Sequelize('transanlys', 'maxroach', 'maxroachX', {
>  host: 'localhost',
>  port:  '26257',
>  dialect: 'postgres',
>logging: console.log,
>  pool: {
>    max: 5,
>    min: 0,
>    idle: 10000
>  },
>});

>sequelize.query("SELECT grandParentTable_name FROM grandparenttable", { type: >sequelize.QueryTypes.SELECT})
>  .catch ( (err) => { console.log(err);  })
>  .then(function(users) {
>        console.log(users);
>})

{ error: unimplemented at or near "MINUTE"
SET client_min_messages TO warning; SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE;SELECT typname, oid, typarray FROM pg_type WHERE typtype = 'b' AND typname IN ('hstore', 'geometry', 'geography')
                                                                            ^

    at Connection.parseE (/root/nodeTest/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/root/nodeTest/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/root/nodeTest/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'error',
  length: 374,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'sql/pgwire/v3.go',
  line: '769',
  routine: '(*v3Conn).sendError' }
undefined

**Comment by felixfbecker** [comment]
Yes, now we come to the part where we use SQL cockroachDB doesn't recognize. Seems like some configuration related to timezones and/or geometry. It may be possible to tweak/suppress this.

**Comment by edwardsmarkf** [comment]
hmmm  and here i figure out that sequelize absolutely needs a username/password to be using cockroach, only to run into another issue right away....   i was SO proud of myself for about 8 seconds or so.

what does it take to beg a sequelize wizard to 'tweak/suppress' this?

**Comment by sushantdhiman** [comment]
These queries are executed when we connect to new connection through our own connection pool, to set proper timezone and retrieve the proper OIDs. There is no option to turn them off and they are vital so we can't allow that either.

This is now CockroachDB's compatibility issue which they have to solve. I think you should switch to Postgres, what extra features CockroachDB offers?

**Comment by edwardsmarkf** [comment]
i am tempted to create a separate dialect for cockroachdb, and make it available on the sequelize page.

any suggestions on this?

**Comment by mickhansen** [comment]
@edwardsmarkf The future goal is to split stuff into connectors and dialects, but we're quite a bit of work away from that.

**Comment by edwardsmarkf** [comment]
i am tempted to hire somebody to write a cockroachdb dialect.   if i were to do this, would you be able to use the results?

i am assuming it would look pretty similar to the mariadb and postgresql connector already in place.

**Comment by mickhansen** [comment]
The problem is also future maintenance, ideally it would come as a plugin so we don't have to maintain it in mainline.

If CockroachDB supports mostly the same SQL standard it could probably reuse all the PG dialect code but have a seperate connector library.
