### ISSUE TITLE
Sequelize.fn('NOW') returns time in UTC time zone

### ISSUE THREAD

**Issue by ShrujanKotturi** [sequelize/sequelize#6823]
Sequelize.fn('NOW') return time in UTC not in the time zone the server is running.

db.table= sequelize.define('TABLE', {
        dateTime: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: sequelize.fn('NOW')
        });

mysql, 
__Database version: 2.11.1
__Sequelize version: 3.24.6

**Comment by sushantdhiman** [comment]
`NOW` is executed on DB server level, Are you sure your DB is not running in UTC.

Try running 
```sql
SELECT @@global.time_zone, @@session.time_zone;
```
