### ISSUE TITLE
ROW_FORMAT support for MySQL InnoDB

### ISSUE THREAD

**Issue by noderat** [sequelize/sequelize#6824]
There isn't currently support for ROW_FORMAT in the Query Generator, which is incredibly handy for InnoDB on newer versions of MySQL.

InnoDB's new [Barracuda](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_barracuda) file format offers [2 new types of row formats](https://dev.mysql.com/doc/refman/5.5/en/innodb-row-format-dynamic.html) which offer significant improvements if working with utf8mb4 collation by supporting index key prefixes up to 3072 bytes instead of the default of 767 bytes offered with [COMPACT or REDUNDANT](https://dev.mysql.com/doc/refman/5.7/en/innodb-row-format-antelope.html) row types offered in the legacy Antelope file format. To enable the new row formats one must pass ROW_FORMAT when creating a table.

I was looking through v3 and v4, both seem pretty easy to add and it's something that's been driving me crazy because I keep running into the 767 byte limit. Is this something on the roadmap or should I work on a PR?

**Comment by felixfbecker** [comment]
Not on the roadmap. Feel free to open a PR

**Comment by noderat** [comment]
Okay, I've got a PR for v3 almost ready, just verifying tests pass.

**Comment by felixfbecker** [comment]
We need it for master first though, you can backport it afterwards

**Comment by noderat** [comment]
Okay, I'll submit a PR for master, await approval to submit PR for v3 backport.

**Comment by noderat** [comment]
Submitted #6825 though I'm not sure why GitHub didn't link the issues
