### ISSUE TITLE
where: false is querying as where: true

### ISSUE THREAD

**Issue by STRd6** [sequelize/sequelize#6827]
## What you are doing?
Using a where clause that should never find something instead finds anything.

```js
Project.findOne({
  attributes: ["id"],
  where: false
});
```

## What do you expect to happen?

```sql
SELECT "id" FROM "projects" AS "project" WHERE false LIMIT 1;
```

## What is actually happening?

```sql
SELECT "id" FROM "projects" AS "project" WHERE 1=1 LIMIT 1;
```

__Dialect:__  postgres
__Sequelize version:__ 3.24.7

**Comment by sushantdhiman** [comment]
I think its fixed in master, can you try unstable v4 i.e. master branch

**Comment by felixfbecker** [comment]
Where is that syntax documented? You should use `Sequelize.literal('false')`

**Comment by STRd6** [comment]
@felixfbecker I don't think I saw it documented anywhere, just how I would expect it to work.

@sushantdhiman Thanks, I'll check it out!

**Comment by sushantdhiman** [comment]
Its not critical issue, possibly should deprecated. Closing
