### ISSUE TITLE
Rollback leaving modifications

### ISSUE THREAD

**Issue by patrickcorrigan** [sequelize/sequelize#6828]
`db.sequelize.transaction({autocommit: false}, function(t) {
    return db.sequelize.query(createModelQuery, {type: db.Sequelize.QueryTypes.CREATE,transaction: t
        })

.then(function(created) {
            return db.sequelize.query(createModelQuery, {
                type: db.Sequelize.QueryTypes.ALTER,
                transaction: t
            })
        });
    })
    .then(function(result) {
        console.log('transaction failed');
        res.json(result);
    })
    .catch(function(reason) {
        console.log('transaction failed');
        if (reason.original.code === 'ER_TABLE_EXISTS_ERROR') {
            res.status(409).json(reason)
        } else {
            res.status(400).json(reason)
        }
    });
});
`

[grunt-develop] > Executing (52af9fd2-3604-4bde-9716-48e3cd87c5a6): START TRANSACTION;

[grunt-develop] > Executing (52af9fd2-3604-4bde-9716-48e3cd87c5a6): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

[grunt-develop] > Executing (52af9fd2-3604-4bde-9716-48e3cd87c5a6): SET autocommit = 0;

[grunt-develop] > Executing (52af9fd2-3604-4bde-9716-48e3cd87c5a6): CREATE TABLE dogs (id int NOT NULL AUTO_INCREMENT,name varchar(255) NOT NULL DEFAULT 'ali',age int not null ,PRIMARY KEY (id));

[grunt-develop] > Executing (52af9fd2-3604-4bde-9716-48e3cd87c5a6): CREATE TABLE dogs (id int NOT NULL AUTO_INCREMENT,name varchar(255) NOT NULL DEFAULT 'ali',age int not null ,PRIMARY KEY (id));

[grunt-develop] > Executing (52af9fd2-3604-4bde-9716-48e3cd87c5a6): ROLLBACK;

[grunt-develop] > transaction failed

The transaction fails but when I check the database the dogs table still exists.

**Comment by janmeier** [comment]
> Most of these statements also cause an implicit commit after executing. The intent is to handle each such statement in its own special transaction because it cannot be rolled back anyway. Transaction-control and locking statements are exceptions: If an implicit commit occurs before execution, another does not occur after.


https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

**Comment by patrickcorrigan** [comment]
@janmeier Thank you. So the create table causes an implicit commit?

**Comment by janmeier** [comment]
Yep, there's basically no way to roll DDL statements back

**Comment by patrickcorrigan** [comment]
Time to switch to Postgres.
