### ISSUE TITLE
Oracle Dialect Implementation - Q&A

### ISSUE THREAD

**Issue by ggrimbert** [sequelize/sequelize#6831]
Hi,

I am currently working on Oracle support for Sequelize.

I have a problem with inserts: Oracle (as sqlite) doesn't support returning the inserted row, which may be a problem after inserted in tables with identity. The solution I found is to execute a select statement after the insert on the last row of the table. 

But to be sure this will be atomic, I need to lock the table and wait for the insert statement to end. 

I'm not very proud of this solution, by the only other way I know is to create a PL/SQL function that executes the insert...

Do you believe this could work without slowing the system ? 
By the way, how does it work with DB that doesn't have a returning statement ?

**Comment by mickhansen** [comment]
both sqlite and mysql use the metadata in someway:

https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L138
https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query.js#L110

**Comment by ggrimbert** [comment]
Ok, I found the solution.

By the way, I ask another question to don't open a new issue : 
The oracledb connector returns results into an object, but it sets the column names in uppercase. 
So the following code (instance.js - line 286), cannot work : 
```
for (i = 0, length = keys.length; i < length; i++) {
          if (values[keys[i]] !== undefined) {
            this.set(keys[i], values[keys[i]], options);
          }
        }
```

This function sets the results from the db into the model. My question is, as oracle returns everything in uppercase, should I do some treatments in query.js (for Oracle dialect), or can  I just simply do : 
```
for (i = 0, length = keys.length; i < length; i++) {
//If all column names in results are Upper Case, use Upper Case key value
	var val = values[keys[i]] ? values[keys[i]]: values[keys[i].toUpperCase()];
	if (val) {
		this.set(keys[i], val, options);
	}
}
```
diretly inside the instance.js (but this becomes global for all dialects).

**Comment by sushantdhiman** [comment]
Probably in the dialect because its Oracle specific.

Also from your usage of `instance.js`,  you might want to target `master` rather than `v3` for this change, its a big change so it will be difficult to manage it on both `v4` and `v3` versions.

**Comment by felixfbecker** [comment]
I would try to map the column names back to model attributes

**Comment by sushantdhiman** [comment]
Other past attempts to introduce Oracle

PR By @gintsgints  https://github.com/sequelize/sequelize/pull/4586

**Comment by ggrimbert** [comment]
@sushantdhiman I work with his repository and https://github.com/adeo-proxideco/sequelize-oracle too.

@felixfbecker I don't have the model inside the query.formatResults method. For my tests now I will just do a new mapping with column names back to lowercase (the case I have). I think that later I will work with the metadata returned by Oracle, it should contains the column names as it's really in DB.

**Comment by ggrimbert** [comment]
Hi,

as I said in https://github.com/sequelize/sequelize/pull/6903, I am having a problem with identifiers tool long for Oracle. We have thought about generating the aliases with a crc (the result should be : tablenameCRC(columnName)).

As this problem can too appear with PostGres, we think this should be done in the Sequelize's abstract code; so before doing anything I want to have your opinion, or maybe another solution we can check to implement.

**Comment by gintsgints** [comment]
@ggrimbert may be just create new merge request for alias name feature you want to change?

**Comment by ggrimbert** [comment]
We will, but before doing anything about this problem, we wanted to be sure that the solution we've found is OK for you.

**Comment by gintsgints** [comment]
You will see it when merge request will or will not be accepted :)

**Comment by gintsgints** [comment]
Have you tought about test execution on travis? That was main showstoper for me.

**Comment by sushantdhiman** [comment]
Sequelize now use Docker on Travis, https://github.com/oracle/docker-images/tree/master/OracleDatabase can be used without much worries about setup

**Comment by ggrimbert** [comment]
I've done this with https://hub.docker.com/r/sath89/oracle-12c/, using a little script modification.

The problem with https://github.com/oracle/docker-images/tree/master/OracleDatabase is that the image takes more than 10GB, but the one I've decided to use about 3GB.

About what I said for aliases, someone can give me its opinion ? Just be sure that we will not work on this for nothing.

**Comment by gintsgints** [comment]
As I said... just make _seperate_ merge request for aliases. So it will be accepted _before_ all other code in mainstream.
