### ISSUE TITLE
Setting schema on loaded models does not work

### ISSUE THREAD

**Issue by manixx** [sequelize/sequelize#6832]
## What you are doing?
I want to alter the schema *after* the model was imported using `sequelize['import']`. 

```js
model = this.sequelize['import']('./models/foo');
model.schema('test');
model.sync();
```

## What do you expect to happen?
Model should created under schema 'test';

## What is actually happening?
Model will be created under public schema. 

## Workaround
```js
var model = this.sequelize['import']('./models/migrationMeta');
model = model.schema('test');

model.sync(); // model created with **correct** schema
sequelize.sync(); // model created with **wrong** schema 
```

It looks like that `schema()` only clones the model with the new schema. 
* Is there a way to alter the schema of the *loaded* model so `sequelize.sync()` also work? 
* or is there a way to set a schema globally, so all models use the same schema without defining it in the model itself? 

Thanks in advice! 

__Dialect:__ postgres
__Database version:__ 9.6.1
__Sequelize version:__ 3.24.8
__pg__: 6.1.0
__pg-hstore__: 2.3.2

**Comment by felixfbecker** [comment]
For general questions like this, please use StackOverflow or Slack.
