### ISSUE TITLE
`Sequelize.useCLS()` breaks with native async/await

### ISSUE THREAD

**Issue by leebenson** [sequelize/sequelize#6834]
In node 7 with `--harmony-async-await`, transactions hang when using `Sequelize.useCLS()`.

Calling `.rollback` or `.commit` explicitly has the same effect- nothing happens.

**Comment by manuelzamboni** [comment]
async and await are based on native ES6 promises but Sequelize.useCLS dependes on BlueBird promises to implement its behaviour.

**Comment by felixfbecker** [comment]
Could you do `global.Promise = require('sequelize').Promise` to make it work? That way `async`/`await` would use Sequelize promises and it shouldn't cause a problem since Bluebird is compatible with native promises.

**Comment by leebenson** [comment]
> Could you do global.Promise = require('sequelize').Promise to make it work? 

That should work, although requiring an overwrite of native objects to make something work feels a bit hacky.

**Comment by jeremija** [comment]
It does not seem that using `global.Promise = require('sequelize').Promise` works - async functions still return native Promises:
```bash
$ node --version
v7.10.0
```

```javascript

$ node
> NativePromise = Promise;
[Function: Promise]
> global.Promise = require('sequelize').Promise
> test = async () => {}
> test() instanceof Promise
false
> test() instanceof NativePromise
true
```
