### ISSUE TITLE
join with the junction table only 

### ISSUE THREAD

**Issue by jony89** [sequelize/sequelize#6836]
## What you are doing?

This is the definition of the junction table : (a many-to-many relation between users and jobs)

```js
    var userToJob = sequelize.define(
        'userToJob', {
            userid: {
                type: DataTypes.INTEGER
            },
            jobid: {
                type: DataTypes.INTEGER
            },
            state: {
                type: DataTypes.INTEGER 
            }
        }, {
            classMethods: {
                associate: (models) => {
                    models.user.belongsToMany(models.job, {
                        through: {
                            model: userToJob,
                            unique: false
                        },
                        foreignKey: 'userid',
                        constraints: false
                    });

                    models.job.belongsToMany(models.user, {
                        through: {
                            model: userToJob,
                            unique: false
                        },
                        foreignKey: 'jobid',
                        constraints: false
                    });                    
                }
            },
            underscored: true,
            tableName: 'users_to_jobs',
            paranoid: false,
            timestamps: true
        }        
    ); 
```

## What do you expect to happen?
I want to be able to  join jobs table with the userToJob junction table without accessing the users table.

so for example i will be able to write somthing like : 

```js
models.job.findAndCountAll({
                         where: {
                             createdby_userid: criteria.userid
                         },
                         limit: 10,
                         include: [{
                            model: models.userToJob,
                            attributes: [['COUNT(case userToJob.state when 1 then 1 else null end)', 'stateCount']]   
                         }],
                         attributes: [
                             'jobid', 'title', 'updated_at', 'created_at', 'description'
                         ],
                         group: ['job.jobid']
                    });
```

## What is actually happening?
the junction table is not associated with the entities (user nor job) so include is not possible.

__Dialect:__ mysql

**Comment by felixfbecker** [comment]
The behavior is expected, because nowhere in your code are you declaring an association between jobs and jobsToUsers, only jobs and users and reverse. Add a has many from jobs to jobstousers and it should work

**Comment by jony89** [comment]
I dont think it makes sense to create association of "hasMany" with the junction table.
I've already declared the association between the two entities.

further more, what if one is using the default junction table ? which means he didn't even define the junction table, so in this case this is totally does not make sense. it should come out of the box once i declared the many-to-many relation (whether defining my self with the "through" property or using the default sequelize table)

**Comment by felixfbecker** [comment]
If we start to generate the associations implicitely there would be no way anymore override the alias for example. Using the junction table directly is not a common use case and it is supported atm in a logical way. Calling an association method will add an association object to Model.asscoations[alias] (and only that model - not the target or a through model or anything). You can pass that object to the include option. If you never associate the model explictely, there will be no association set up. It is clear that passing a string to through is just a convenience shorthand that only works for simple n:m relations where the through model is not relevant - it will still generate a model though, not just a table.

**Comment by mysuf** [comment]
@felixfbecker The point is that ORM should ideally cover 100% of what user can do with raw query. These are gaps that are advocated by "not common use". It is absolutely legit to join only junction table (e.g. to filter results on left side via primary key). It saves one useless join. So for table M, MN and N. If I make `ModelM.findAll({ include: [{ model: ModelMN }] })`, it should know that there is a relation. Instead now (v6) it prints: `SequelizeEagerLoadingError: model_mn is not associated to model_m!` even though there is obvious relation on both model and associations level.

**Comment by mysuf** [comment]
Btw I would expect that when I set M.belongsToMany(N, { through: MN }), it will be shortcut for: `M.hasMany(MN)`, `MN.belongsTo(M)`, `MN.belongsTo(N)`, `N.hasMany(MN)`. And writing the opposite: `N.belongsToMany(M)` will just return existing association from opposite side.
