### ISSUE TITLE
Getter is still calling when attributes field is set

### ISSUE THREAD

**Issue by psnet** [sequelize/sequelize#6838]
## Getter field is in answer when not in attributes list

```js
// model definition
field1: {
  type: Sequelize.STRING,
  get: function() {
    return 'field1'
  }
},
field2: {
  type: Sequelize.STRING,
}
```
```js
// code
model.findAll({
  attributes: ['field2']
})
```

## Expected behavior
Response is array of objects that have **only one** attribute - field2

## What is actually happening?
Response is array of objects that have **two** attributes - field2 **and field1 with value "field1" from getter**.

__Dialect:__ postgres
__Database version:__ 9.5
__Sequelize version:__ 3.21

**Comment by ro70** [comment]
https://github.com/sequelize/sequelize/issues/6761

**Comment by sgimeno** [comment]
I can confirm this is also happening with mysql dialect
