### ISSUE TITLE
Buffer Deprecation warning

### ISSUE THREAD

**Issue by kengz** [sequelize/sequelize#6840]
## What you are doing?
running migration, on `MacOSX, node v7.0.0, sequelize v3.24.3` with postgres.

```shell
node_modules/.bin/sequelize db:migrate --env development
```

## What do you expect to happen?
Run without warning

## What is actually happening?
Got a deprecation warning for Buffer:

```shell
Sequelize [Node: 7.0.0, CLI: 2.4.0, ORM: 3.24.3]

Loaded configuration file "config/db.json".
Using environment "development".
(node:25647) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
No migrations were executed, database schema was already up to date.
```

__Dialect:__ postgres
__Database version:__ 9.3
__Sequelize version:__ 3.24.3

**Comment by felixfbecker** [comment]
Quite hard to find out if that is really caused by Sequelize without a stack trace. Maybe you could do a search in your folder for the call?

**Comment by ianwalter** [comment]
Probably caused by: https://github.com/brianc/node-postgres/issues/1158

**Comment by kengz** [comment]
Confirmed @ianwalter 's speculation. Warning does not show up with mysql.
