### ISSUE TITLE
Performing FULLTEXT search after JOIN operation in sequelize.

### ISSUE THREAD

**Issue by MacBox7** [sequelize/sequelize#6845]
I have two tables Category and Events and I want to perform a FULLTEXT search on the columns Events.Name,Description,Society and Category.Name after performing a join operation on both the tables in sequelize.<br>
The modals have been defined as follows:<br><br>
Events.js<br>

    (function () {
       'use strict';
       module.exports = function(sequelize, DataTypes) {
         var Events = sequelize.define("Events", {        //Must be same as table name
           Id: {
             type: DataTypes.INTEGER,
             primaryKey: true,
             autoIncrement: true // Automatically gets converted to SERIAL for postgres
           },
           Name: {
             type: DataTypes.STRING,
             notNull: true
           },
           Description: {
             type: DataTypes.STRING,
             notNull: true
           },
           Venue: {
             type: DataTypes.STRING,
             notNull: true
           },
           StartTime: {
             type: DataTypes.STRING,
             notNull: true
           },
           EndTime: {
             type: DataTypes.STRING,
             notNull: true
           },
           StartDate: {
             type: DataTypes.STRING,
             notNull: true
           },
           EndDate: {
             type: DataTypes.STRING,
             notNull: true
           },
           CurrentRound: {
             type: DataTypes.STRING,
             notNull: true
           },
           Society: {
             type: DataTypes.STRING,
             notNull: true
           },
           CategoryId: {
             type: DataTypes.INTEGER,
             notNull: true
           },
           MaxContestants: {
             type: DataTypes.INTEGER,
             notNull: true
           },
           Status: {
             type: DataTypes.STRING,
             notNull: true
           },
           Pdf: {
             type: DataTypes.STRING,
             notNull: true
           }
         }, {
           timestamps: false,
           tableName: 'Events',
           freezeTableName: true
         }, {
           indexes: [
             { type: 'FULLTEXT', fields: 'name' }
           ]
         },{
           classMethods: {
             associate: function(models) {
               Events.belongsTo(models.Category);
             }
           }
         });
         return Events;
       };
    }());
<br><br>
Category.js<br>

    module.exports = function(sequelize, DataTypes) {
      var Category = sequelize.define("Category", {
        Id: {
          type: DataTypes.INTEGER,
          primaryKey: true,
          autoIncrement: true // Automatically gets converted to SERIAL for postgres
        },
        Name: DataTypes.STRING
      }, {
        timestamps: false,
        tableName: 'Category',
        freezeTableName: true
      },{
        Indexes: [
          { type: 'FULLTEXT', fields: ['Name'] }
        ]
      }, {
        classMethods: {
          associate: function(models) {
            Category.hasMany(models.Events);
          }
        }
      });
      return Category;
    };
<br><br>
The query I am performing is :<br>

    Model.Events.findAll({
          include: [{ model: Model.Category }],having: ['MATCH(Events.Name,Description,Society,Category.Name) AGAINST(?)', query]   }).then(function(data) {
          console.log(JSON.stringify(data));
          r.status = statusCodes.SUCCESS;
          r.data = JSON.stringify(data);
          return res.end(r.toString());
        }).catch(function(err){
          console.log(err);
          r.status = statusCodes.SERVER_ERROR;
          r.data = err;
          return res.end(r.toString());
        });
<br><br>
The errors I am getting are :<br>

 1. FULLTEXT index does not exits.<br> 
 2. Incorrect arguments to the match.<br>
 3. I am not sure if a foreign key has been created.<br><br>

Please help me out by correcting my query.

**Comment by janmeier** [comment]
You shouldn't put `indexes` in a separate object - it should be in the same object as the other options. Also, it's camel cased, like other options.

This is also the reason associations are not being set up correctly (you are passing class method in the wrong object)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
