### ISSUE TITLE
Questions about associate and distinct

### ISSUE THREAD

**Issue by gzlock** [sequelize/sequelize#6847]
__Dialect:__ mysql
__Database version:__ 5.7.5
__Sequelize version:__ 3.*

__Define__
```
user = sequelize.define('user', {username: Sequelize.STRING});
message  = sequelize.define('message', {content: Sequelize.TEXT});
message.belongsTo(user, {as:'to', foreignKey: 'toUserId'});
message.belongsTo(user, {as:'from', foreignKey: 'fromUserId'});
```
__Fill data__
userA and userB both send two messages to userC
```
user.create({username: 'userA'});
user.create({username: 'userB'});
user.create({username: 'userC'});
message.create({content: 'message 1',fromUserId: 1, toUserId: 3});
message.create({content: 'message 2',fromUserId: 2, toUserId: 3});
message.create({content: 'message 3',fromUserId: 1, toUserId: 3});
message.create({content: 'message 4',fromUserId: 2, toUserId: 3});
```

__How to do ?__
Merge the message records from the same user, like this
```
[
    {content: 'message 3', from: {username: 'userA'}, createdAt: 'blablabla' ...},
    {content: 'message 4', from: {username: 'userB'}, createdAt: 'blablabla' ...}
]
```

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).

**Comment by gzlock** [comment]
@felixfbecker  The request is i can't found about 'DISTINCT' usage in the doc website
