### ISSUE TITLE
MSSQL Bulk Insert - need to split up the queries.

### ISSUE THREAD

**Issue by TimMurnaghan** [sequelize/sequelize#6856]
Sql Server has some counter intuitive behavior on big inserts.
Its parser gets confused with too many inputs - so they've imposed a limit on it.

This problem is analyzed well here:
[http://stackoverflow.com/questions/8635818/multiple-insert-statements-vs-single-insert-with-multiple-values/8640583#8640583](url)

We need to change the bulkInsertQuery method to unbulk the rows (like I say - counter intuitive).

## What you are doing?
Putting in 10K data rows into a pretty simple data values table (and therefore not included inline here).

## What do you expect to happen?
We should be able to put pretty large data sets in via bulkCreate (as that's what it's for).

## What is actually happening?
SequelizeDatabaseError: The number of row value expressions in the INSERT statement exceeds the maximum allowed number of 1000 row values.

__Dialect:_ mssql 
__Database version: 12.0.2000 (SQL Server 2014 Express 64 bit)
__Sequelize version: 3.25.0

**Comment by sushantdhiman** [comment]
This was discussed some time ago and rejected https://github.com/sequelize/sequelize/issues/6022 , you can easily batch on via `Promise.reduce` or any other code.

**Comment by TimMurnaghan** [comment]
@sushantdhiman @mickhansen 
Sorry - but this is just wrong.  The logic in MickHansen's response in #6022 is exactly backwards.
In my system I need to be able to bulk insert - so I call the bulkinsert method. 
You suggest that I have to make changes in the APPLICATION for a dialect specific problem. That's what the database layer is meant to manage and abstract for us. You already have dialect specific implementations so that's the right place to apply this.

Chosing to put a large single insert for MS sql server is always a bad idea as explained in the stackoverflow I attached. That means that you're tying yourselves to a bad implementation for some curious reason that you want that piece of code to look like some other dialects. I don't get it.  Especially when the fix is so simple.

To stay portable I'll always have to avoid bulkInsert - if you're not going to properly support it across dialects - then why have it in the API?

I recognize that SQL server is a not the easiest thing to support - but having it on your list is a huge plus for the project - so it's probably worthwhile having a bit more engagement with folks using it in non-trivial ways.

**Comment by felixfbecker** [comment]
@mickhansen @sushantdhiman I kind of agree with @TimMurnaghan. A cross-dialect ORM should abstract away dialect limitations.

**Comment by leodsgn** [comment]
@sushantdhiman you've mentioned that you would use `Promise.reduce` to solve the issue. Do you mind making a example?

PS.: Thanks so much for supporting this lib. It's awesome and I know it took hard work!

**Comment by TimMurnaghan** [comment]
@leodsgn If you look at the linked issue #6866 you can see that we found a way of supporting this directly. In recent versions it should just work without any need for Promise.reduce. Are you seeing some issues with big bulk inserts?
