### ISSUE TITLE
Attributes can't be renamed using a nested array if you are using Relations / Associations and raw.

### ISSUE THREAD

**Issue by rafaelfcads** [sequelize/sequelize#6858]
Attributes can't be renamed using a nested array if you are using Relations / Associations and raw.
When I put the renamed using a nested array, Sequelize start not finding it "'testTwo.id'".

`Test.findOne({
       raw:true,
       include: [
        { model: TestTwo, as: 'testTwo' }
      ],
      attributes: ['id', 'name', 'testTwo.id', ['testTwo.id', 'testTwoId'] ]
    })
    .then((result) => { resolve(result); })
    .catch((err) => { reject(err); });
  });`

**Comment by felixfbecker** [comment]
That is not enough info to identify the issue - how are your models set up?

**Comment by rafaelfcads** [comment]
`'use strict';
module.exports = function (sequelize, DataTypes) {
  var Test = sequelize.define('Test', {
    name: DataTypes.STRING,
    testTwoId: DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function (models) {
        Test.belongsTo(models.TestTwo, {'as': 'testTwo'});
        });
    }
  });

  return Test;
};


'use strict';
module.exports = function(sequelize, DataTypes) {
  var TestTwo = sequelize.define('TestTwo', {
    name: DataTypes.STRING   
  }, {
    classMethods: {
      associate: function(models) {
        TestTwo.hasMany(models.Test, { foreignKey: 'testTwoId', as: 'test' });
      }
    }
  });
  return TestTwo;
};
`

**Comment by felixfbecker** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

**Comment by felixfbecker** [comment]
Have you tried using `Sequelize.col()`?
