### ISSUE TITLE
A feature similar to ActiveRecord's find_each

### ISSUE THREAD

**Issue by thawatchai** [sequelize/sequelize#686]
I'm wondering if Sequelize has a feature similar to ActiveRecord's [find_each](http://apidock.com/rails/ActiveRecord/Batches/ClassMethods/find_each)? We want to process millions of records. What's the recommended way to do it with Sequelize?

BTW, thank you for this wonderful library. We use it in production in a fairly high traffic website for a while now. We plan to port more of our code from Rails to Node. This is possible because of Sequelize. :+1:

**Comment by scaryguy** [comment]
I've been considering to use Sequelize with Postgres but when I've seen this thread, I feel scared.

I'm also playing with millions of rows. So if I use Sequelize, won't I be able to have anything like Rails' find_each? Is Sequelize's findAll() the only option? I think I'm misunderstanding something here. Can you please explain more?

**Comment by mickhansen** [comment]
@scaryguy Unfortuneatly we still don't support streaming, so yes findAll is your only option (or i suppose you could use a recursive findAll with increasing offset).

**Comment by scaryguy** [comment]
Thanks for fast response @mickhansen . But I'm still not clear. Can you please tell me what are the issues one may encounter if he's using Sequelize with millions of rows of data? Let's say I have a `records` table and it has more than 30M records. What if I'd like to make some operation on ALL of thr rows?

Is the best option with Sequelize is using `findAll()` and getting ALL rows into memory first and then iterate over the result? But it's not something possible? Isn't there a way of dealing with it using Sequelize? 

Could you please give a small example?

**Comment by mickhansen** [comment]
The issue is that findAll loads all instances into memory since we don't support streaming.
I haven't personally dealt with this issue but i assume you could just do a iterative set of OFFSET/LIMIT queries to mitigate it, but the best solution would be a streaming solution so you could manually handle the pressure.

**Comment by ippeiukai** [comment]
FYI: I've ported `find_each` to sequelize for my own use. Receiving a block and `yield`ing each value to it in Ruby is not dissimilar to receiving a callback function and executing it with each value in JS.

https://gist.github.com/ippeiukai/1d9f717711414118b360eff0718c07c0

**Comment by felixfbecker** [comment]
@ippeiukai you are doing this with multiple queries, correct? Not the fastest of course. Instead of doing a $gt on the ID I would recommend you to use `offset`.

I think if we implement this API we would return a stream object that you can attach a listener to. The dialects all support this in some way, but there are internal changes required because we pass promises around everywhere.

One way to solve this might be like node-postgres does it and returning a stream/event emitter that implement a promise interface with `.then()` and `.catch()`. That way our internal code changes would be minimal because we could still use them as promises everywhere, and also expose only promises to other methods by doing `Promise.resolve()`. Only for streaming we could return the actual stream. _Or_ we could even decide to always return this kind of thenable stream for `findAll()`.

**Comment by ippeiukai** [comment]
@felixfbecker
 I'm doing in the way ActiveRecord does, which is to load records in batches. Yes, there will be `Math.ceil(recordCount/batchSize)` queries in all, but queries are reasonable and memory consumption too would be reasonable with right `batchSize`.
Use of `offset` on the other hand is known to be slow as offset gets bigger (at least with MySQL and PostgreSQL).

Streaming is a nice idea, but, as you said, it is very different from the way Sequelize currently works both internally and API-wise. 
Meanwhile, as shown in my gist, implementing `findEach` and `findInBatches` is practical and their interface is reasonably in line with the current Promise heavy APIs (you can compare them with bluebird's [Promise#each](http://bluebirdjs.com/docs/api/promise.each.html)).
You can consider adding `findEach` as an intermediate solution to this particular problem that many of us seem to face right now until the proper streaming is implemented.

**Comment by felixfbecker** [comment]
> their interface is reasonably in line with the current Promise heavy APIs

> Use of offset on the other hand is known to be slow as offset gets bigger

But it won't work if the model has not a sequential ID, for example because it uses UUIDs.

How is a callback API in line with promise APIs? The point of promises is to not pass the return value(s) in a callback call, but use an _object_ to represent the return value(s).

> You can consider adding findEach as an intermediate solution to this particular problem that many of us seem to face right now until the proper streaming is implemented.

No, then we would have to support the API long-term. This is better suited as a user-land workaround for now.

**Comment by ippeiukai** [comment]
> But it won't work if the model has not a sequential ID, for example because it uses UUIDs.

It works as long as the model has a single primary key that can be sorted. No problem with UUIDs. This is same as `find_each` in ActiveRecord (http://api.rubyonrails.org/classes/ActiveRecord/Batches.html ).

> How is a callback API in line with promise APIs? The point of promises is to not pass the return value(s) in a callback call, but use an object to represent the return value(s).

I have modeled the interface after [Promise#each](http://bluebirdjs.com/docs/api/promise.each.html). I guess what I'm trying to say is rather that this is a reasonable extension to how Promise works in practice.
I can see why you insist this needs be a streaming API though. If iterating with a callback isn't the thing, we need to pass around an object that represents a stream of async results.

**Comment by felixfbecker** [comment]
So you would then be sorting by the UUID? Interesting.

@mickhansen @janmeier @durango what do you think of the thenable stream idea?

**Comment by felixfbecker** [comment]
Reopening because this is neither implemented nor a duplicate

**Comment by lsl** [comment]
In need of this. Does anyone know if mscdex/node-mariasql ever got integrated with sequelize? Using a secondary connection for the meantime.

**Comment by sony-mathew** [comment]
Very much in need of this.

**Comment by fourcolors** [comment]
I could use this as well.

**Comment by Ricardonacif** [comment]
I think most people using sequelize would love a feature like this.

**Comment by kwanso-nadeem** [comment]
Looking for an update or solution here.

**Comment by ippeiukai** [comment]
> Looking for an update or solution here.

For a solution, have you tried https://github.com/sequelize/sequelize/issues/686#issuecomment-247531723 ?
https://gist.github.com/ippeiukai/1d9f717711414118b360eff0718c07c0

I would be happy to help you in anyway I can.

**Comment by MattiaMalonni** [comment]
I've made a new version for sequelize `^6.4.0` without external dependencies.

https://gist.github.com/MattiaMalonni/5b64d2a66f2f8276e1b50d20d1c03a78

**Comment by mateusluizfb** [comment]
+1 here, currently I'm using a solution similar from the ones commented above

**Comment by WikiRik** [comment]
Reopening this issue, would be nice if somebody could make a PR with a solution similar to posted above and some tests so we can include this in sequelize

**Comment by mateusluizfb** [comment]
Cool!! I'll if I can do something

**Comment by ephys** [comment]
There was discussion about this feature in https://github.com/sequelize/sequelize/pull/15357. This is a draft of what the API could look like

```ts
interface FindAllBatchedOptions extends FindOptions {
  // if mode is "offset", it uses "findAll" & updates the "offset" option
  // if mode is "stateful-cursor", it uses "findAll" and paginates using a stateful cursor
  // if mode is "stateless-cursor", the first query uses "findAll", subsequent queries use "findAllByStatelessCursor" with after & first parameters
  // no default value, they all have different advantages over the others
  mode: 'offset' | 'stateful-cursor' | 'stateless-cursor';
  batchSize: number;
}

class Model {
  findAllBatched(options: FindAllBatchedOptions): AsyncIterator<Model>;
}
```

- `stateless-cursor` mode would be built on top of https://github.com/sequelize/sequelize/issues/15827

**Comment by klondikemarlen** [comment]
I've been using this slightly hacky version for Sequelize 7, if it helps anyone.
```ts
import {
  Attributes,
  CreationOptional,
  FindOptions,
  Model,
  ModelStatic,
  Op,
  WhereOptions,
} from "@sequelize/core"

// See api/node_modules/@sequelize/core/lib/model.d.ts -> Model
export abstract class BaseModel<
  // eslint-disable-next-line @typescript-eslint/ban-types, @typescript-eslint/no-explicit-any
  TModelAttributes extends {} = any,
  // eslint-disable-next-line @typescript-eslint/ban-types
  TCreationAttributes extends {} = TModelAttributes,
> extends Model<TModelAttributes, TCreationAttributes> {
  // See api/node_modules/@sequelize/core/lib/model.d.ts -> findAll
  // Taken from https://api.rubyonrails.org/v7.1.0/classes/ActiveRecord/Batches.html#method-i-find_each
  // Enforces sort by id, overwriting any supplied order
  public static async findEach<M extends BaseModel & { id: CreationOptional<number> }>(
    this: ModelStatic<M>,
    processFunction: (record: M) => Promise<void>
  ): Promise<void>
  public static async findEach<
    M extends BaseModel & { id: CreationOptional<number> },
    R = Attributes<M>,
  >(
    this: ModelStatic<M>,
    options: Omit<FindOptions<Attributes<M>>, "raw"> & {
      raw: true
      batchSize?: number
    },
    processFunction: (record: R) => Promise<void>
  ): Promise<void>
  public static async findEach<M extends BaseModel & { id: CreationOptional<number> }>(
    this: ModelStatic<M>,
    options: FindOptions<Attributes<M>> & {
      batchSize?: number
    },
    processFunction: (record: M) => Promise<void>
  ): Promise<void>
  public static async findEach<
    M extends BaseModel & { id: CreationOptional<number> },
    R = Attributes<M>,
  >(
    this: ModelStatic<M>,
    optionsOrFunction:
      | ((record: M) => Promise<void>)
      | (Omit<FindOptions<Attributes<M>>, "raw"> & {
          raw: true
          batchSize?: number
        })
      | (FindOptions<Attributes<M>> & { batchSize?: number }),
    maybeFunction?: (record: R | M) => Promise<void>
  ): Promise<void> {
    let options:
      | (FindOptions<Attributes<M>> & { batchSize?: number })
      | (Omit<FindOptions<Attributes<M>>, "raw"> & {
          raw: true
          batchSize?: number
        })

    // TODO: fix types so that process function is M when not raw
    // and R when raw. Raw is usable, just incorrectly typed.
    let processFunction: (record: M) => Promise<void>

    if (typeof optionsOrFunction === "function") {
      options = {}
      processFunction = optionsOrFunction
    } else if (maybeFunction === undefined) {
      throw new Error("findEach requires a processFunction")
    } else {
      options = optionsOrFunction
      processFunction = maybeFunction
    }

    const batchSize = options.batchSize ?? 1000
    let lastId = 0
    let continueProcessing = true

    while (continueProcessing) {
      // TODO: fix where option types so cast is not needed
      const whereClause = {
        ...options.where,
        id: { [Op.gt]: lastId },
      } as WhereOptions<Attributes<M>>
      const records = await this.findAll({
        ...options,
        where: whereClause,
        limit: batchSize,
        order: [["id", "ASC"]],
      })

      for (const record of records) {
        await processFunction(record)
        lastId = record.id
      }

      if (records.length < batchSize) {
        continueProcessing = false
      }
    }
  }
}
```
