### ISSUE TITLE
MSSQL Bulk Insert - need to split up the queries(2)

### ISSUE THREAD

**Issue by TimMurnaghan** [sequelize/sequelize#6866]
As #6856 got closed - there isn't a very visible place for a discussion.

As I said in the original issue, the current implementation of bulkInsertQuery for MS SQL server isn't fit for purpose. There's plenty of evidence showing that SQL server has hardwired limits and bad performance for the queries being generated.
 
The original issue was closed saying that I shouldn't use a large dataset on MS SQL and should work round it in the application - which isn't acceptable for a portable solution.

Are you likely to reconsider or am I going to have to live with the fork that I'm currently using?

**Comment by sushantdhiman** [comment]
@TimMurnaghan I have see your implementation https://github.com/AnalyticRiskTechnology/sequelize/commit/c1837564c128a5b4b34a753ea3d43714fbbff127 and I am ok with that as you have found out a solution using query generator itself :+1: 

I think what we didnt want to involve was some batching at sequelize level, where we have to run queries in a loop one after other and aggregate them, which was most likely a non atomic solution.

PR will be most appreciated. Please open one and other members will review your implementation. You will have to add some tests as well :)

**Comment by TimMurnaghan** [comment]
@sushantdhiman Thanks, Happy to do that. I was expecting to have to do the tests  - but wanted to see whether you'd adopt it. Give me a day or two to put it all together into a PR.

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/commit/aeaf1e5741a3267bccbdf492ff287e289990f7bf
