### ISSUE TITLE
Feature request: "Model.resolveById()" to intelligently resolve objects or ids to model objects

### ISSUE THREAD

**Issue by broofa** [sequelize/sequelize#6868]
It is often helpful to allow code calling into a method to provide either a model object or the id of the model object, and then only do the `findById` call if needed.  Unfortunately in the world of promises, the code for this is just cumbersome enough to be awkward.  It'd be nice if there were a companion method to findById() called, `resolveById()` that takes care of this.

I've currently monkey-patched this into my code base as a classMethod extension, below, but I thought I'd go ahead and propose it here since this might be a common enough problem to make it worth adding to Sequelize.

```javascript
classMethods: {
  resolveById: function(idOrInstance) {
      return idOrInstance instanceof this.Instance ?
        Promise.resolve(idOrInstance) :
        this.findById(idOrInstance);  }
}
```

**Comment by felixfbecker** [comment]
Sorrry, I don't understand your feature request
