### ISSUE TITLE
"Error: SequelizeDatabaseError: column reference "data" is ambiguous" when trying to order results by a JSON field

### ISSUE THREAD

**Issue by FoxMcCloudDX** [sequelize/sequelize#6869]
## What you are doing?
I have the following models:

```
module.exports = function(sequelize, Types) {
    return sequelize.define('Foo', {
        name: Types.STRING,
        data: Types.JSON,
        uuid: {
            type: Types.UUID,
            defaultValue: Types.UUIDV4
        }
    }, {
        comment: 'Foo',
        underscored: true,
        tableName: 'foo'
    });
};

module.exports = function(sequelize, Types) {
    return sequelize.define('Drink', {
        label: {
            type: Types.STRING,
            allowNull: false,
            comment: 'label'
        },
        properties: Types.JSON,
        data: Types.JSON,
        uuid: {
            type: Types.UUID,
            defaultValue: Types.UUIDV4
        }
    }, {
        comment: 'drinks',
        underscored: true,
        tableName: 'drink'
    });
};
```

with the following relations:

```
models.Drink.hasMany(models.Foo);
models.Foo.belongsTo(models.Drink);
```

Ans I'm doing the following query:

```
Foo.findAll({
    include: [{
        model: Drink
    }],
    order: [
        [Sequelize.json('data.Number'), 'ASC']
    ]
})
```

## What do you expect to happen?
I wanted the results to be ordered by the `data.Number` field of the model `Foo`.

## What is actually happening?
Instead i get the following error:

`SequelizeDatabaseError: column reference "data" is ambiguous`

and the generated SQL query is the following:

```
'SELECT "Foo"."id", "Foo"."name", "Foo"."data", "Foo"."uuid", "Foo"."created_at",
 "Foo"."updated_at", "Foo"."drink_id", "Drink"."id" AS "Drink.id", "Drink"."label" AS "Drink.label",
 "Drink"."properties" AS "Drink.properties", "Drink"."data" AS "Drink.data", "Drink"."uuid" AS
 "Drink.uuid", "Drink"."created_at" AS "Drink.created_at",
 "Drink"."updated_at" AS "Drink.updated_at" FROM "foo" AS "Foo" LEFT OUTER JOIN "drink" AS
 "Drink" ON "Foo"."drink_id" = "Drink"."id" ORDER BY data#>>\'{Number}\' ASC;' },
  sql: 'SELECT "Foo"."id", "Foo"."name", "Foo"."data", "Foo"."uuid", "Foo"."created_at",
 "Foo"."updated_at", "Foo"."drink_id", "Drink"."id" AS "Drink.id", "Drink"."label" AS "Drink.label",
 "Drink"."properties" AS "Drink.properties", "Drink"."data" AS "Drink.data", "Drink"."uuid" AS
 "Drink.uuid", "Drink"."created_at" AS "Drink.created_at", "Drink"."updated_at" AS "Drink.updated_at"
 FROM "foo" AS "Foo" LEFT OUTER JOIN "drink" AS "Drink" ON "Foo"."drink_id" = "Drink"."id"
 ORDER BY data#>>\'{Number}\' ASC;'
```
As I can understand, it looks like the query does not specify which model the `data` field belongs to on the `ORDER BY` clause. I tried to do something like `[Foo, Sequelize.json('data.Number'), 'ASC']` but it seems it only works with associated models and I can't reference the main model.

Is there a way to specify the model which the `data` field belongs to on the `order` clause or any alternative to do this kind of query?

__Dialect: postgres
__Sequelize version: 3.25.1

**Comment by janmeier** [comment]
It actually works for the other case (ordering by foo.data

```js
return Foo.findAll({
      logging: console.log,
      include: [{
        model: Drink
      }],
      order: [
        [Drink, Sequelize.json('data.Number'), 'ASC']
      ]
    });
```
It's probably because `.json` is not being prefixed with the table name by default.

**Comment by FoxMcCloudDX** [comment]
Yes @janmeier , from what i could tell, it seems exactly the case. The example you posted works because it prefixes the table name correctly, but if i try to do [Foo, Sequelize.json('data.Number'), 'ASC'], i get an error because `Foo` is not associated with `Foo`. Either that could be done by default or the order config array could support not only the associated models, but the model itself to be specified.

**Comment by FoxMcCloudDX** [comment]
Hello. Is there any update on this issue?

**Comment by shime** [comment]
I'm getting the same issue. Any known workarounds?
