### ISSUE TITLE
Parent model is not associated to child model

### ISSUE THREAD

**Issue by guiconti** [sequelize/sequelize#6872]
Hi, i am new to sequelize and i am struggling a little with associations.

Basically i have two models Country and City as follows
```js
CountryDB = sequelize.define('country', {
        name: {
            type: DataTypes.STRING,
            unique: true
        },
        active: {
             type: DataTypes.BOOLEAN,
             defaultValue: true
        }
    });

CityDB = sequelize.define('city', {
        name: {
            type: DataTypes.STRING,
            unique: true
        },
        active: {
             type: DataTypes.BOOLEAN,
             defaultValue: true
        }
    });
```

I am trying to make that the country have many cities and a city have one country. I did the association as follows
```js
CountryDB.hasMany(CityDB, {as: 'City', foreignKey: 'countryId'});
CityDB.belongsTo(CountryDB, {as: 'Country', foreignKey: 'countryId'});
```

When i insert a new City into my CityDB i pass a countryId that refers to the Country that it belongs. So far so good. But when i try to get a City and include the CountryDB model into it i get a "country is not associated to city!" error.

This is how i did my select query
```js
CityDB.findAll({include: [{model: CountryDB}]}).then((cityList) => {

        return res.status(200).json({
            data: cityList
        });

    }, (err) => {

        console.log(err);

        return res.status(500).json({
            data: err
        });

    });
```

I expected that it returned all my cities with the country values that belongs to each countryId but i did not manage to make it work.

Can someone give me a hint about what i am doing wrong?

Thanks!

__Dialect:__ postgres
__Database version:__ 6.1.0
__Sequelize version:__ 3.25.0

**Comment by felixfbecker** [comment]
You have not specified `as`. The default is the plural, eg `Cities`. Either specify the `model`, `as` pair or use the `Association` object from `CountryDB.associations.City` (where `City` is the association alias)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
