### ISSUE TITLE
id autoincrement is update when upsert

### ISSUE THREAD

**Issue by errok** [sequelize/sequelize#6873]
Hello ! 

I have a problem with autoIncrement and upsert. My code : 

```javascript
return sequelize.define("user", {
	id : {
            type          : db.INTEGER,
            autoIncrement : true,
            primaryKey    : true,
            allowNull     : false
        },
        login : {
            type      : db.STRING,
            allowNull : false
        }
    }, {
        indexes: [
            {
                unique : true,
                fields : ["login"]
            }
        ],
        freezeTableName : true
    });
```

```javascript
exports.upsert = function (postgresql, login) {
    return postgresql.user.upsert({
        login      : login,
        updated_at : ""
    });
};
```

If in my DB, the last user have "id=6" and I execute twice the function upsert on user table (regardless login), the next insert of user will have an id=9...

I feel upsert update anyway autoincrement of id user table. Have you an idea to prevent this behavior ?

**Comment by mickhansen** [comment]
postgres sequences are globally atomic, they don't reset if a transaction fails either.
You'll have to look and see if there's a postgres solution for this but i doubt it, out of the scope of Sequelize in any case.
