### ISSUE TITLE
Not an issue just a question. Can we use mariasql instead of nodemysql ?

### ISSUE THREAD

**Issue by anuranjit** [sequelize/sequelize#6876]
Is it possible to use mariasql instead of node mysql for connecting to MySql.

**Comment by janmeier** [comment]
We did so previously - Any specific reasons?

**Comment by anuranjit** [comment]
@janmeier  I am facing performance issues with node mysql,  so in my project (using python and node) database inserts take around 20ms in node and takes around 2ms in python (According to newrelic). I compared raw sql performance of node mysql and python, it turned out the node mysql  driver takes more time. Then I tried benchmarking mariasql against node mysql, mariasql performs better (it is at par with python ).

**Comment by janmeier** [comment]
Have you tried node-mysql2? 

As far as i remember, mariasql has the same api as node-mysql, so you could also try

```js
new Sequelize(...., {
  dialectModulePath: 'mariasql'
});
```

**Comment by anuranjit** [comment]
@janmeier  Tried this, i am getting the error, 
`Unhandled rejection TypeError: self.lib.createConnection is not a function
sequelize/lib/dialects/mysql/connection-manager.js:72:31
`

**Comment by janmeier** [comment]
Have you tried node-mysql2? (We are using it on master / v4)

**Comment by anuranjit** [comment]
node-mysql2 performance is lower than node-mysql, as per my benchmark, so the sequence goes like 
mariasql > node mysql > mysql2 :smile: .

**Comment by sushantdhiman** [comment]
@anuranjit Mind sharing your benchmarks

**Comment by felixfbecker** [comment]
@anuranjit mysql2 uses binary protocol which is faster than mysql's text protocol. More importantly though, it supports prepared statements, which are more secure. There are also efforts to merge the codebases.
