### ISSUE TITLE
Troubles with .catch and async/waterfall

### ISSUE THREAD

**Issue by cmercuri** [sequelize/sequelize#6877]
Hello,
I'm building web services with NodeJS (6.3.1) and Sequelize (3.25.0) and async module (2.1.2). My database is MySQL.

If I'm in an async waterfall, for example, and I'm trying to save a model I cannot use the .catch function because it report me "done is not a function".

## What you are doing?
```
import async from "async";

app.get("/", function(request, response)  {

	async.waterfall([
		function(done) {
			var instance = MyModel.build();
			
			// set some data to instance of MyModel
			
			instance.save().then(function(instanceSaved) {
				console.log("Save success!");
				done(null);
			}).catch(function(error) {
				if (error) {
					console.log("Save fail!");
					console.log(error);
				}
			});
		}
	], function(error) {
		if (error) {
			response.json({
				success: false;
			});
		} else {
			response.json({
				success: true
			});
		}
	});
});
```
## What do you expect to happen?
I expect to read in console only "Save success!" if saving was successful, only "Save fail!" if saving got error.

## What is actually happening?
Happens that I read in console both and the `console.log(error);` write something like:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: done is not a function
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
From previous event:
    at Promise.then (.../node_modules/sequelize/lib/promise.js:21:17)
    at waterfallFunction (.../distribution/routes/myroute.js:91:16)
    at nextTask (.../node_modules/async/dist/async.js:5208:14)
    at .../node_modules/async/dist/async.js:5202:13
    at apply (.../node_modules/async/dist/async.js:41:25)
    at .../node_modules/async/dist/async.js:76:12
    at .../node_modules/async/dist/async.js:988:16
    at Object.waterfall (.../node_modules/async/dist/async.js:5211:5)
```

I'm doing something wrong? I have to do in another way?

Thank you in advance!

**Comment by janmeier** [comment]
`done` is a function from async, not from sequelize - Not really much we can help you with there :)

I realize this might be a shortened down, but it can be written much simpler without async

```js

app.get("/", function(request, response) {
  var instance = MyModel.build();

  // set some data to instance of MyModel

  instance.save().then(function() {
    console.log("Save success!");
    response.json({
      success: true
    });
  }).catch(function(error) {
    console.log("Save fail!");
    console.log(error);
    response.json({
      success: false
    });
  });
});
```

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
