### ISSUE TITLE
Configuration to use underscore in fields

### ISSUE THREAD

**Issue by lucasdoamaral** [sequelize/sequelize#6879]
Already exists the param "underscored" that defines if the name of automatically generated fields (like `createdAt` or `updatedAt`) should use `camelCase` (if the param is false) or `underscored_names`.

It would be great if it was possible to set if the normal fields must be created using camelCase or underscored in the database! I know that I can use the `field` option to explictly define the field name, but in most cases the only reason I use it is to define the name in underscore, in order to avoid camelCase in the db.

Thanks in advance!

**Comment by janmeier** [comment]
This should be very easy to do with `beforeDefine` https://github.com/sequelize/sequelize/blob/00bf32a398806a73a73638805f515810d170b3ce/test/integration/hooks/hooks.test.js#L41

It allows you to alter all attributes before they are added to the model
