### ISSUE TITLE
Issue with many to many association

### ISSUE THREAD

**Issue by nishthaarora** [sequelize/sequelize#6880]
I have 2 tables events and teams and they have belongsToMany Association and i created a bulk data through migration file for both of those tables. Attaching some screenshots. 

<img width="602" alt="screen shot 2016-11-17 at 10 39 48 am" src="https://cloud.githubusercontent.com/assets/19481533/20398230/362260aa-acb2-11e6-8734-559a3b33df05.png">

<img width="771" alt="screen shot 2016-11-17 at 10 38 29 am" src="https://cloud.githubusercontent.com/assets/19481533/20398189/038a68fe-acb2-11e6-9f17-c44835638ce3.png">

below is the code for association in Team models

module.exports = function(sequelize, DataTypes) {
  var Team = sequelize.define('Team', {
    Team_name: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        Team.belongsToMany(models.Event, {through:'eventTeam'});

      }
    }
  });
  return Team;
};

below is the code for association in Event models
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Event = sequelize.define('Event', {
    date: DataTypes.DATE,
    start_time: DataTypes.TIME,
    end_time: DataTypes.TIME,
    type: DataTypes.STRING,
    score1: DataTypes.INTEGER,
    score: DataTypes.INTEGER,
    location: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
        Event.belongsToMany(models.Team, {through: 'eventTeam'});

      }
    }
  });
  return Event;
};

Tables are created. eventTeam Table is also available. 

<img width="666" alt="screen shot 2016-11-17 at 10 42 21 am" src="https://cloud.githubusercontent.com/assets/19481533/20398316/8c256b1e-acb2-11e6-817a-b471e9af14d2.png">

All have tables had the data as expected but association is not happening. my table for eventTeam which is created by defining "though" in association is empty.
I am pretty new to this. I may be missing something extremely small. Can somebody please help.

Also, below is the structure for the association table
<img width="903" alt="screen shot 2016-11-17 at 10 44 23 am" src="https://cloud.githubusercontent.com/assets/19481533/20398397/e7bb37c4-acb2-11e6-8122-6346cb884377.png">

**Comment by sushantdhiman** [comment]
What do you mean by `All have tables had the data as expected but association is not happening` ? Do you have any specific error or odd behavior to point out

**Comment by nishthaarora** [comment]
Hi Sushant thanks for replying. I think i found the problem. Associations doesn't work with bulk created data. I had a data which was bulk created. and i did belongToMany association on 2 models. eventTeam is my table created by doing association. which means my association created the table but i could not see the keys from other 2 tables in my eventTeam. It was a blank table.

**Comment by sushantdhiman** [comment]
Since you have solved the issue yourself I think we can close this one for now
