### ISSUE TITLE
Polish docs for v4

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6886]
General review, migration of articles and a landing page
Make it clear that a model is just a class

**Comment by janmeier** [comment]
ping @lipp

We'd like to add a custom landing page for our docs, instead of people ending up directly on the API docs when they visit `docs.sequelizejs.com` - How do we best fit that into doclets?

**Comment by sushantdhiman** [comment]
Does `doclets` offers custom documentation which is not tied to comments (like we have on `ReadTheDocs` http://docs.sequelizejs.com/en/v3/docs/models-usage/). How we plan on migrating them? We should definitely have docs moved and cleaned up before publishing `v4`

**Comment by mickhansen** [comment]
doclets is only for API documentation is it not?

**Comment by felixfbecker** [comment]
No, doclets supports "articles" written in markdown

**Comment by lipp** [comment]
@janmeier I could add index page prop in the doclets.yml to allow directing to an article or the API docs.... would this be ok?

**Comment by janmeier** [comment]
Yeah, that would work fine for us I think 

We like to host docs on our own domain. What we do now is have the DNS record actually point at readthedocs.org, and then there's a setting on RTD that says to listen for request for `docs.sequelizejs.com`, and serve up the correct docs with relative links so people stay on our domain even while navigating around. Would you be open to supporting something similar?

**Comment by felixfbecker** [comment]
Specifying one markdown article as landing page should be fine

**Comment by janmeier** [comment]
@lipp Do you need any help - Is there something I can do to speed this along?

**Comment by lipp** [comment]
@janmeier looking into this tomorrow....

**Comment by sushantdhiman** [comment]
@janmeier what will take more time

- Creating an auto deploy mechanism for current docs
- Moving docs to doclets

Current docs are good (apart from broken search + polishing, which can be fixed), I am just considering do we really need migration at all ?

**Comment by janmeier** [comment]
@sushantdhiman Dunno - Read the docs read md files from a repo, so we would need to figure out a way to run some kind of generator on travis, and commit it to a repo

I think search not working is a pretty big issue though, and one a lot of people have complained about

**Comment by janmeier** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/7490 - All that's needed is to update the DNS once v4 is released
