### ISSUE TITLE
Generate Sequelize query in a string before executing it

### ISSUE THREAD

**Issue by zenithtekla** [sequelize/sequelize#6892]
To follow up on [previous issue](https://github.com/sequelize/sequelize/issues/6891)
I have defined models. Is there any way for me to get the query string generated for this?

```js
function getlastDossierEagerLoading(req, res, next){
    ECMS_Equipment.findOne({
      where: req.params,
      attributes: ['asset_id', 'model', 'asset_number', 'last_cal', 'schedule', 'next_cal'],
      include: [
        { model: ECMS_Location, attributes: ['desc']},
        { 
             model: ECMS_Dossier, 
             attributes: ['time_field', 'file_id', 'filename', 'createdAt', 'updatedAt', 'file'], 
             limit: 1
        }
      ],
      // limit: [ [ECMS_Dossier, 1] ], problem is the limit option does not support on associated model, resort to include.separate?
      order: [ [{model: ECMS_Dossier}, 'time_field', 'DESC'] ] // orderBy is fine.
    }).then(function(result){
      res.json(result.dataValues);
    }).catch(function(err){res.json(err);});
  }
```

Assuming I have ECMS_Equipment model, can I have a method like `ECMS_Equipment.queryGenerator()` and that I can throw the same object in there to get the query and modify|tailor|curtail the query string by myself.

```js
let generated_query = ECMS_Equipment.queryGenerator({where: req.params, include: []});
let updated_query = generated_query + 'LIMIT 1';
```

Ideally, I should have another method so I can invoke the transaction by `ECMS_Equipment.runQuery(updated_query);`

Can you implement that? Or if implemented, walk me through the usage. Thanks

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/2325

**Comment by zenithtekla** [comment]
Thank you for relating to my question with that thread.
`Model.findAll().on('sql', function (sql) {
// assume I make changes to the query through modifying the 'sql' string, e.g.
sql += " LIMIT 1";

// how can I tell Sequelize now, it's good to execute it down here?

});`
