### ISSUE TITLE
Error adding table column with foreign key constraint using migrations

### ISSUE THREAD

**Issue by ahennie** [sequelize/sequelize#6895]
I'm trying to add a user_id column with a foreign key contraint to a Todo-table in Node Express using Sequelize with Postgresql. I get an error message when running 
```
Executing (default): SELECT "id", "name", "assignedDate", "priority", "done", "position", "userId", "createdAt", "updatedAt", "UserId" FROM "Todos" AS "Todo" ORDER BY "Todo"."createdAt" ASC;
```
error message

`Unhandled rejection SequelizeDatabaseError: column "UserId" does not exist`

 As you can see there is both "userId" and "UserId" in the SELECT query. 
The SELECT query is built by a simple Todo.findAll().

I believe it's something wrong in how I create the foreign key contraints in the migration file 20161116202040-add-user-id-to-todos.js, but it could also be a bug. 

```
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.addColumn(
      'Todos',
      'userId', {
        type: Sequelize.INTEGER,
        references: {
          model: 'Users',
          key: 'id'}})};
```

I am also including the models/user.js

```
module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define('User', {
    email: DataTypes.STRING,
    password: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        User.hasMany(models.Todo);}}});
return User;};
```
and models/todo.js

```
module.exports = function(sequelize, DataTypes) {
  var Todo = sequelize.define('Todo', {
    name: DataTypes.STRING,
    userId: DataTypes.INTEGER
  },{  
    classMethods: {
      associate: function(models) {
        Todo.belongsTo(models.User); }}});
  return Todo;};
```

Anyone who knows how to solve this or if it is a bug?

__Dialect:__ postgres
__Node version:__ 6.9.1
__Database version:__ 9.5.4
__Sequelize version:__ 3.24.6

**Comment by dioptrique** [comment]
Hi may I know how you solved this issue? I am facing the same issue.
