### ISSUE TITLE
Error in sequelize.import: defineCall is not a function

### ISSUE THREAD

**Issue by HerbertTot** [sequelize/sequelize#6898]
## What you are doing?
I just had this line in my bin/www `require('../models')` this load the index.js (seen below).
The it generated an error. 

File structure in the models folder:
models
  |- index.js
  |- user.js

index.js:
```js
'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(module.filename);
var env       = process.env.NODE_ENV || 'development';
var config    = require('../config/config.json')[env];
var db        = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
    var sequelize = new Sequelize(process.env.MYSQL_DATABASE , process.env.MYSQL_USER, process.env.MYSQL_PASSWORD, {
        host: process.env.MYSQL_HOST || 'localhost',
        dialect: 'mysql',

        pool: {
            max: 5,
            min: 0,
            idle: 10000
        }
    });
}

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(function(file) {
    var model = sequelize.import(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

user.js:

```js
module.export = function(sequelize, DataTypes)
{
    return sequelize.define('users', {
        username: {type: DataTypes.STRING, primaryKey: true},
        password: DataTypes.STRING,
        stamm: DataTypes.STRING,
        lv: DataTypes.String,
        countSipplinge: DataTypes.INT,
        avgAge: DataTypes.INT,
        sifüName: DataTypes.STRING,
        sifüEMail: DataTypes.STRING,
        sifüAdresse: DataTypes.STRING,
        sifüTel: DataTypes.STRING,
        email: DataTypes.STRING,
        admin: DataTypes.BOOLEAN,
        sippe: DataTypes.BOOLEAN,
        inactive: DataTypes.BOOLEAN
        })
    };
```

## What do you expect to happen?
I expected to load the File and Model user.js as seen below:

## What is actually happening?
But just run into an error: 

```
C:\Users\Jan\WebstormProjects\BdPWebanwendung\node_modules\sequelize\lib\sequelize.js:691
    this.importCache[path] = defineCall(this, DataTypes);
                             ^

TypeError: defineCall is not a function
    at Sequelize.import (C:\Users\Jan\WebstormProjects\BdPWebanwendung\node_modules\sequelize\lib\sequelize.js:691:30)
    at C:\Users\Jan\WebstormProjects\BdPWebanwendung\models\index.js:32:33
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\Jan\WebstormProjects\BdPWebanwendung\models\index.js:31:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jan\WebstormProjects\BdPWebanwendung\config\passport.js:5:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
I checked with an debugger where it actually happens.
The error is generated by the following line:

```js
if (!this.importCache[path]) {
    var defineCall = (arguments.length > 1 ? arguments[1] : require(path));
    if (typeof defineCall === 'object') {
      // Babel/ES6 module compatability
      defineCall = defineCall.default;
    }
    this.importCache[path] = defineCall(this, DataTypes);
  }
 ```

defineCall is undefined and it was set by the line `defineCall = defineCall.default;`.
In this line is defineCall the object of `require('path/to/user.js')` but `defineCall.default` is `undefined`.

Dialect: mysql
Database version: 5.7.12
Sequelize version: 3.27.0

**Comment by felixfbecker** [comment]
That means you have tried to import a module that did not do a `module.exports = function()`

**Comment by HerbertTot** [comment]
The only model i imported is the `user.js` and this file has a `module.exports = function()`

**Comment by sushantdhiman** [comment]
There is a spelling mistake in `user.js`, you need the `module.exports` but you actually have `module.export` :stuck_out_tongue:

**Comment by murnun** [comment]
In my case, it was the index.js file created inside my models directory by sequelize CLI when i ran its init command. After simply removing this file, the error went away. This still seems like a conflicting behavior between the CLI and how sequelize imports models; and I'd like to learn why this is so -- or, if it's more of poor incompatibility issue between diff versions of sequelize & postgresand other accompanying tools. If anyone has more insight, please kindly do let me know here.

**Comment by alvaro-paco** [comment]
This is a CLI issue and must be fixed. This occurs when you make a module.exports in a object like module.exports = {...}. If you make module.exports = () =>{} the error gone but the Sequelize cannot import you module. To correct this bug declare you models as:
`module.exports = () => {
  return {
     username: {type: DataTypes.STRING, primaryKey: true},
        password: DataTypes.STRING,
        stamm: DataTypes.STRING,
        lv: DataTypes.String,
        countSipplinge: DataTypes.INT,
        avgAge: DataTypes.INT,
        sifüName: DataTypes.STRING,
        sifüEMail: DataTypes.STRING,
        sifüAdresse: DataTypes.STRING,
        sifüTel: DataTypes.STRING,
        email: DataTypes.STRING,
        admin: DataTypes.BOOLEAN,
        sippe: DataTypes.BOOLEAN,
        inactive: DataTypes.BOOLEAN
  }
}
`

**Comment by riazXrazor** [comment]
thanks @HerbertTot  was facing the same problem.

**Comment by vintuwei** [comment]
You might need to delete old models on the dist folder if you are using babel

**Comment by bbalban** [comment]
Re murnun: There is no conflict. This ensures to skip index.js:
 .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })

**Comment by bbalban** [comment]
I resolved this issue by removing old require("./models") and similar calls

**Comment by ZendyLim** [comment]
@bbalban How i suppose to import models if I removed require("./models") part from my code?
Thanks

**Comment by aprilmintacpineda** [comment]
I experienced this issue, the reason was because I added a file on my models directory that is not a model, just some code that's meant to do some stuff. I suppose we can only add model files on the models directory, as `index.js` checks every file in the whole directory.

Can we edit the codes in the `index.js` to look for `filename.model.js` instead of every file or maybe make it configurable with `model` as the default?

**Comment by andrejoshua** [comment]
I'm experiencing this issue as well right now, i tried to put console.log in the index.js to check that sequelize is really imported, but the log didn't show up at all, is it normal that index.js in the model was seemed skipped or something was wrong?

**Comment by BenCook28** [comment]
Thanks @aprilmintacpineda for your insight, I removed the error when I cut the contents of a model I had commented out, pasted the contents into a repl.it, and deleted the file which previously contained the commented out code.

**Comment by grety22** [comment]
@aprilmintacpineda thanks

**Comment by rimiti** [comment]
You've to .import() de default function like that:

```
// db/index.ts
const Users = sequelize.import("./models/users");
```

```
// db/models/users.ts
const UserModel = (sequelize: Sequelize.Sequelize, dataTypes: Sequelize.DataTypes) => {
  const User = sequelize.define<IUserModelInstance, IUserModelAttribute>(
    "users",
    {
      id: {
        type: dataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
      email: {
        type: dataTypes.STRING(255),
        allowNull: false,
      },
      password: {
        type: dataTypes.STRING(255),
        allowNull: false,
      },
    },
    {
      tableName: "users",
      underscored: true,
      freezeTableName: true,
      paranoid: true,
      },
    },
  );
  return User;
};

export {UserModel as default};
```

Have a nice coding day ;)

**Comment by MaybeSomeone** [comment]
> You might need to delete old models on the dist folder if you are using babel

I fix it !!!   Thank you.

**Comment by validvendor** [comment]
I also had this issue, and for me it was caused by a file in the models folder that I had completely commented out - and was redundant. After I deleted the file, things continued as normal.

**Comment by dewaleolaoye** [comment]
I'm having this same issue now and i can't figure how to fix it

**Comment by dewaleolaoye** [comment]
Okay, it was caused by an empty file in the models folder. 
Sequelize is trying to import a file that isn't a model.

**Comment by papb** [comment]
Hi everyone, as a side note, `sequelize.import` will probably be deprecated soon (of course the CLI will be updated accordingly). Just so you know.

**Comment by vanunu1987** [comment]
This new ./models/index.js helps me

const dotenv = require('dotenv');
const fs = require('fs');
const path = require('path');
const { Sequelize, DataTypes } = require('sequelize');

const filebasename = path.basename(__filename);
const db = {};

// Get env var from .env
dotenv.config()
const { DB_HOST, DB_USER, DB_PASS, DB_NAME, DB_FORCE_RESTART } = process.env;

const config = {
  host: DB_HOST,
  dialect: 'mysql',
  dialectOptions: {
    charset: 'utf8',
  }
}

const sequelize = new Sequelize(DB_NAME, DB_USER, DB_PASS, config);

fs
  .readdirSync(__dirname)
  .filter((file) => {
    const returnFile = (file.indexOf('.') !== 0)
      && (file !== filebasename)
      && (file.slice(-3) === '.js');
    return returnFile;
  })
  .forEach((file) => {
    const model = require(path.join(__dirname, file))(sequelize, DataTypes)
    db[model.name] = model;
  });


Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

const sequelizeOptions = { logging: console.log, };

// Removes all tables and recreates them (only available if env is not in production)
if (DB_FORCE_RESTART === 'true' && process.env.ENV !== 'production') {
  sequelizeOptions.force = true;
}

sequelize.sync(sequelizeOptions)
  .catch((err) => {
    console.log(err);
    process.exit();
  });

module.exports = db;

**Comment by Ba7er** [comment]
Same Here!

**Comment by IsraelTorresFullSail** [comment]
I found this solution:
Replace this line:
const model = sequelize.import(path.join(__dirname, file));
By:
const model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);

**Comment by Ba7er** [comment]
@IsraelTorresFullSail  yes, i ended up doing something similar 

```
"user strict";
const fs = require("fs");
const { Sequelize, DataTypes } = require("sequelize");

let DB = {};

module.exports = {
  init: async (System) => {
    const sequelize = await new Sequelize(
      System.serverDB.database,
      System.serverDB.user,
      System.serverDB.password,
      {
        host: System.serverDB.host,
        dialect: "mysql",
      }
    );

    fs.readdirSync("./modules").forEach((file) => {
      let modelsName = require(`../../modules/${file}/models/${file}`);
      modelsName(sequelize, DataTypes)
        .sync({ force: true })
        .then((model) => {
          DB[file] = model;
          console.log("the model is ", model);
        });
    });

    await sequelize.authenticate();
  },
  DB,
};
```

**Comment by ImanthaOnline** [comment]
hey guys i'm having this issue **TypeError: sequelize.import is not a function**
`'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(module.filename);
var env       = process.env.NODE_ENV || 'development';
var config    = require(__dirname + '/../config/config')[env];
var db        = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(function(file) {
    console.log(file,__dirname);
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;
db.Op = Sequelize.Op;
db.fn=sequelize.fn
module.exports = db;
`
this is my index.js file


`'use strict';

const sequelizePaginate = require('sequelize-paginate');

module.exports = (sequelize, DataTypes) => {
  const Album = sequelize.define('Album', {
    title: { type: DataTypes.STRING, allowNull: false },
    thumbnail: { type: DataTypes.STRING, allowNull: true },
    userId: { type: DataTypes.INTEGER(11), allowNull: false },
    active: { type: DataTypes.BOOLEAN, allowNull: false }
  });

  Album.associate = function (models) {
    Album.belongsTo(models.User, { foreignKey: 'userId' });
    Album.hasMany(models.Images, { foreignKey: 'albumId' })
  };
  
  sequelizePaginate.paginate(Album);

  return Album;
};
`
this is my table query why do i get this error

**Comment by ImanthaOnline** [comment]
@IsraelTorresFullSail thanks man you are a savior it works for me

**Comment by Helder-Hernandez** [comment]
Utilizando la v5 la declaración **import** no funcionara...
```js
// not working 😞 
const models = {
    artista: sequelize.import('./artista'),
    cancion: sequelize.import('./cancion')
}
```

si esta utilizando la v6 utilice la declaración **require**...
```js
// working 😃 
const models = {
    artista: require("./artista").default(sequelize, Sequelize),
    cancion: require("./cancion").default(sequelize, Sequelize)
}
```
