### ISSUE TITLE
Model#find() through join table fails due to LIMIT 1 in intermediate queries [minimal test case included]

### ISSUE THREAD

**Issue by broofa** [sequelize/sequelize#6899]
## What you are doing?
Using find() to query for results through a Many:Many relationship.  I have (I believe) the standard ModelA -> (JoinTable) -> ModelB configuration in [this Gist](https://gist.github.com/broofa/f65038f6642d12ac67510a13d4095e1a)

In that gist, I create two entries in each of the ModelA and ModelB tables, "a1", "a2", and "b1", b2".  I then create two associations in the join table, linking a1 -> b1 and a2 -> b2.

I then run queries for the 4 permutations of findAll() / find() that query for ModelA entries linked to 'b1' and 'b2'.

## What do you expect to happen?
Each of the four find()/findAll() queries should find one result, yielding the following output:

```
ModelA.findAll( ... "b1"...) found 1
ModelA.findAll( ... "b2"...) found 1
ModelA.find( ... "b1"...) Worked
ModelA.find( ... "b2"...) Worked
```

## What is actually happening?

The first three queries work, but the last one fails, yielding the following output:

```
ModelA.findAll( ... "b1"...) found 1
ModelA.findAll( ... "b2"...) found 1
ModelA.find( ... "b1"...) Worked
ModelA.find( ... "b2"...) NONE FOUND, WTF???
```

Here's the [full output with generated SQL](https://gist.github.com/broofa/29917b3d130a17f8dd76c4d93953317c).

I believe the problem is that the `find()` is generating sub-queries with `LIMIT 1`.  This truncates the intermediate results needed to properly resolve the outermost query to the expected row.  For example, if I edit the last [failing] `SELECT model_b....` query so there is only a single, final LIMIT clause at the and, like thus:

```
SELECT `model_b`.*, `model_as`.`modelBUuid` AS `model_as.modelBUuid`, `model_as`.`createdAt` AS `model_as.createdAt`, `model_as`.`updatedAt` AS `model_as.updatedAt`, `model_as.join_table`.`someProp` AS `model_as.join_table.someProp`, `model_as.join_table`.`createdAt` AS `model_as.join_table.createdAt`, `model_as.join_table`.`updatedAt` AS `model_as.join_table.updatedAt`, `model_as.join_table`.`modelAUuid` AS `model_as.join_table.modelAUuid`, `model_as.join_table`.`modelBUuid` AS `model_as.join_table.modelBUuid` FROM (SELECT `model_b`.`modelAUuid`, `model_b`.`createdAt`, `model_b`.`updatedAt` FROM `model_bs` AS `model_b` WHERE ( SELECT `join_table`.`modelAUuid` FROM `join_tables` AS `join_table` INNER JOIN `model_as` AS `model_a` ON `join_table`.`modelBUuid` = `model_a`.`modelBUuid` WHERE (`model_b`.`modelAUuid` = `join_table`.`modelAUuid`)) IS NOT NULL) AS `model_b` INNER JOIN (`join_tables` AS `model_as.join_table` INNER JOIN `model_as` AS `model_as` ON `model_as`.`modelBUuid` = `model_as.join_table`.`modelBUuid`) ON `model_b`.`modelAUuid` = `model_as.join_table`.`modelAUuid` AND `model_as`.`modelBUuid` = 'b2'  LIMIT 1
```

... it returns the expected row.

__Dialect:__ mysql
__Database version:__ mysql  Ver 14.14 Distrib 5.7.13, for osx10.11 (x86_64) using  EditLine wrapper
__Sequelize version:__ 3.25.0

**Comment by broofa** [comment]
After wading through the code in abstract/query-generator.js, I've found that adding `groupedLimit:true` fixes the problem... maybe?

Alas, I have no idea if this is an expected usecase for `groupedLimit`.  There are quite a few references to it in query-generator.js, so I don't fully understand it's intended use.  What I do know is that this removes the interior LIMIT clauses.  But it doesn't create an outer clause, which is a little disconcerting.

I would love to get a little guidance on whether this is a legit bug, a valid use of groupedLimit, or if I've someone gotten off in the weeds on this.

**Comment by istrau2** [comment]
I believe I am experiencing the same issue. I am trying to execute the following query:

```
transaction.findAll({
            where: {
                '$tenant.privileges.user_pkey$': {
                    $eq: userPkey
                }
            },
            include: [
                {
                    model: this.account,
                    as: 'tenant',
                    attributes: [],
                    include: [
                        {
                            model: this.privilege,
                            as: 'privileges',
                            attributes: []
                        }
                    ]
                }
            ],
            order: 'transactionPkey',
            limit: 10
        });
```

which produces this:

> SELECT "Transaction".* FROM (SELECT "Transaction"."transaction_pkey" AS "transactionPkey", "Transaction"."global_transaction_pkey" AS "globalTransactionPkey", "Transaction"."tenant_pkey" AS "tenantPkey", "Transaction"."tenant_name" AS "tenantName", "Transaction"."counterparty_pkey" AS "counterpartyPkey", "Transaction"."counterparty_name" AS "counterpartyName", "Transaction"."transaction_direction_pkey" AS "transactionDirectionPkey", "Transaction"."transaction_direction_name" AS "transactionDirectionName", "Transaction"."transaction_status_pkey" AS "transactionStatusPkey", "Transaction"."transaction_status_name" AS "transactionStatusName", "Transaction"."transaction_type_pkey" AS "transactionTypePkey", "Transaction"."transaction_type_name" AS "transactionTypeName", "Transaction"."transaction_timestamp" AS "transactionTimestamp", "Transaction"."gross_quantity" AS "grossQuantity", "Transaction"."tare_quantity" AS "tareQuantity", "Transaction"."seal_identifier" AS "sealIdentifier", "Transaction"."vehicle_identifier" AS "vehicleIdentifier", "Transaction"."note", "Transaction"."image_path" AS "imagePath" FROM "v_transaction" AS "Transaction" WHERE ("tenant.privileges"."user_pkey" = 158) ORDER BY "Transaction"."transaction_pkey" asc LIMIT '10' OFFSET '0') AS "Transaction" LEFT OUTER JOIN "v_account" AS "tenant" ON "Transaction"."tenantPkey" = "tenant"."account_pkey" LEFT OUTER JOIN "v_privilege" AS "tenant.privileges" ON "tenant"."account_pkey" = "tenant.privileges"."account_pkey" ORDER BY "Transaction"."transactionPkey" asc;

Which produces the following database error:
`missing FROM-clause entry for table "tenant.privileges"`

I believe this error is occuring because the where clause is in the inner subquery while the joins are done in the outer query.

**Comment by janmeier** [comment]
I would recommend against using `groupedLimit` - its not part of the public API, and its only a side-effect that it works here.

See https://github.com/sequelize/sequelize/issues/3007 et. al. for hints about why this case is hard to solve (basically, cartesian joins are hard to reason about).

In your specific case you can add `duplicating: false` to the include. This way you tell sequelize, that even though the general case of a n:m include might provide a cartesian join, you know that this one will not (since we will always match a single B). This could probably be inferred from the fact that you do a where primaryKey = X in the future :)
