### ISSUE TITLE
Many-to-many  table with identical foreign key is overriding the value

### ISSUE THREAD

**Issue by ricardomachadosb** [sequelize/sequelize#6902]
Hi guys, i have the following structure:

```js
var User = sequelize.define('user', {
  name: DataTypes.STRING
});

var Post = sequelize.define('post', {
  text: DataTypes.STRING
});

var PostComment = sequelize.define('ownership', {
  id: {
    type: DataTypes.BIGINT,
    primaryKey: true,
    autoIncrement: true
  },
  comment: DataTypes.TEXT
});

Post.belongsToMany(User, { as: 'postUserComment', through: PostComment });
User.belongsToMany(Post, { through: PostComment });
```

The same user, should be able to make multiples comments to the same post.
But when i execute 

```js
post.addPostUserComment(currentUserId, {comment: "teste"})
```

If i already have a comment to this post made by the currentUser, it override it's "comment" value in the database when it should create a new row. 

Dialect: mysql 
Sequelize version: ~3.24.2

Am i doing something wrong?

**Comment by sushantdhiman** [comment]
You want N:M relation with multiple similar records. You will need `unique: false`. Please checkout these discussions

https://github.com/sequelize/sequelize/issues/2459
https://github.com/sequelize/sequelize/issues/1997

**Comment by ricardomachadosb** [comment]
Hi sushantdhiman , thanks for your help, i tried it, but it seems to be ignoring the unique: false property 

```
Post.belongsToMany(User, {as: 'postUserComment', through: PostComment, unique: false, foreignKey: 'idPost', constraints: false});
```

I noticed that it is creating an index called postComment_idUserComment_idPost_unique in the database even i ser unique to false

**Comment by sushantdhiman** [comment]
@ricardomachadosb You are passing `unique` incorrectly, pass it as prop of `through`

```js
Event.belongsToMany(Member, { through: { model: EM, unique: false }});
Member.belongsToMany(Event, { through: { model: EM, unique: false }});
```

**Comment by ricardomachadosb** [comment]
Thanks @sushantdhiman it worked, no i am having some trouble to select them, but it's something for another issue, thanks.
