### ISSUE TITLE
 Nodejs use JOIN for two tables on sequelize

### ISSUE THREAD

**Issue by tux-world** [sequelize/sequelize#6905]
I'm trying to implementing this mysql command on sequelize, but as far as i'm newbie to use this library i can't implementing that

i want to make this sql command:

    SELECT * FROM users 
    join users_contacts_lists on users_contacts_lists.mobile_number = users.mobile_number 
    WHERE users_contacts_lists.user_id = 1

My models to create database schema:

    'use strict';
    var config = require('../config');
    
    var User = config.sequelize.define('users', {
        id: {
            type: config.Sequelize.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        password: {
            type: config.Sequelize.STRING
        },
        username: {
            type: config.Sequelize.STRING
        },
        mobileNumber: {
            type: config.Sequelize.STRING,
            field: 'mobile_number'
        },
        status: {
            type: config.Sequelize.STRING
        },
    }, {freezeTableName: true});
    
    var UsersContactsLists = config.sequelize.define('users_contacts_lists', {
        id: {
            type: config.Sequelize.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        userId: {
            type: config.Sequelize.INTEGER,
            field: 'user_id'
        },
        mobileNumber: {
            type: config.Sequelize.STRING,
            field: 'mobile_number', defaultValue: 0
        }
    }, {freezeTableName: true});
    
    UsersContactsLists.belongsTo(ChannelsTypes, {foreignKey: 'mobile_number'});
    User.hasMany(Channels, {foreignKey: 'mobile_number'});
    
    User.sync();
    UsersContactsLists.sync();
    
    module.exports =
    {
        users: User,
        usersContactsLists: UsersContactsLists
    };

how can i resolve this problem? Thanks in advance

**Comment by sushantdhiman** [comment]
Have you gone through http://docs.sequelizejs.com/en/v3/docs/associations/ ?

**Comment by tux-world** [comment]
yes, but as far as i'm newbie to use this library on nodejs i can't do that


my issue updated with this lines:

```
UsersContactsLists.belongsTo(ChannelsTypes, {foreignKey: 'mobile_number'});
User.hasMany(Channels, {foreignKey: 'mobile_number'});
``

for example this is my code:

```
models.users.findAll({
    include: [{model: models.usersContactsLists}]
}).then(function (result) {
    console.log(JSON.stringify(result));
});
```

but i get this error:

```
Unhandled rejection Error: users_contacts_lists is not associated to users!
```

**Comment by istrau3** [comment]
@tux-world 

First off, you didn't post any code associating users to usersContactLists. So maybe you forgot that association?

Secondly, You need an `as` in both the association and the query. This is because the same two tables can have multiple named associations. 

Try something like this:
```

User.hasMany(Channels, {foreignKey: 'channel_fk', as: 'channels'});

models.users.findAll({
    include: [{model: models.channels, as: 'channels'}]
}).then(function (result) {
    console.log(JSON.stringify(result));
});
```

**Comment by tux-world** [comment]
@istrau3 Thanks, problem resolved
