### ISSUE TITLE
Many-to-many table with identical foreign key is selecting just one value

### ISSUE THREAD

**Issue by ricardomachadosb** [sequelize/sequelize#6906]
Hi guys, i have the following structure:

```js
var User = sequelize.define('user', {
  name: DataTypes.STRING
});

var Post = sequelize.define('post', {
  text: DataTypes.STRING
});

var PostComment = sequelize.define('postComment ', {
  id: {
    type: DataTypes.BIGINT,
    primaryKey: true,
    autoIncrement: true
  },
  comment: DataTypes.TEXT
});

Post.belongsToMany(User, {as: 'postUserComment', through: {model: models.PostComment, unique: false}, foreignKey: 'idPost'});

User.belongsToMany(Post, {through: {model: models.PostComment, unique: false}, foreignKey: 'idUserComment'});
```

I am able to create multiples comments to the same post with an user.

But if i have more then one comment to the same post with the same user and try to select them by doing:

```js
 Post.findAll({
          include: [{model: models.User, as: 'postUserComment', attributes:['name'], through: {attributes: ['comment']}},
          limit: 10,
          offset: 0,
          order: "id DESC"
...
```
it just return 1 comment for each user in a post. What do i have to do to select them all?

**Comment by sushantdhiman** [comment]
Have you checked https://github.com/sequelize/sequelize/issues/2459 (which I also linked earlier in last thread https://github.com/sequelize/sequelize/issues/6902)

**Comment by ricardomachadosb** [comment]
@sushantdhiman  I think it was fixed for PostComment .findAll() 

but not for post.findAll() with include

i am "~3.27.0" and still getting just one result.

**Comment by ricardomachadosb** [comment]
Yep, just tried, it works for postComment.findAll() but not for 

Post.findAll({
          include: [{model: models.User, as: 'postUserComment', attributes:['name'], through: {attributes: ['comment']}},
          )

**Comment by raducostea** [comment]
@ricardomachadosb ,

Did you found any solution to this? Having the same issue.

**Comment by ricardomachadosb** [comment]
@raducostea  i changed it to 
```js
Post.hasMany( models.PostComment, { as: 'postComment', foreignKey: 'idPost' } );
```

And the query :

```js
        Post.findAll({
          include: [{model: models.PostComment, as: 'postComment', attributes:['id', 'comment'], 
                      include: [{model: models.User, as: 'userComment', attributes: ['id','userName']}]
                    },
```

**Comment by raducostea** [comment]
Thanks, i could not make the second include work without also setting "PostCommet" belongsTo relation. It works now which is good. To bad i cannot use a many to many relation.

**Comment by ricardomachadosb** [comment]
@raducostea sorry you are right i forgot to mention this

```js
PostComment.belongsTo(models.User, {as: 'userComment', foreignKey: 'idUserComment'});
PostComment.belongsTo(models.Post, {as: 'postComment', foreignKey: 'idPost'});
```

**Comment by dpmott** [comment]
My team has spent several days investigating odd behavior with the belongsToMany() relationship, where unique is set to false.  We've written some tests to characterize the odd behaviors.  See attached zip of a small project that demonstrates the issues.

Feedback on these tests is welcome and desired.  If we're misusing Sequelize, we'd like to know it.

Thanks.

[nm-pg.zip](https://github.com/sequelize/sequelize/files/842340/nm-pg.zip)
