### ISSUE TITLE
Error: Please install 'pg' module manually

### ISSUE THREAD

**Issue by Fjandin** [sequelize/sequelize#6907]
I'm in the process of switching to Yarnpkg from npm, and i hit this issue. Was working fine before when i was using npm, but using yarn i get this error.

```js
Error: Please install 'pg' module manually
    at new ConnectionManager (/home/app/kerberos/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:27:13)
    at new PostgresDialect (/home/app/kerberos/node_modules/sequelize/lib/dialects/postgres/index.js:12:28)
    at new Sequelize (/home/app/kerberos/node_modules/sequelize/lib/sequelize.js:233:18)
```

**Comment by felixfbecker** [comment]
Do you have pg installed?

**Comment by Fjandin** [comment]
yes i have
```
"pg": "6.1.0"
"sequelize": "3.27.0"
```

**Comment by Fjandin** [comment]
I noticed that this is only an issue when i have installed with `yarn --production` or having NODE_ENV=production, so most probably a yarn issue... but still wierd as i have no module devDependencies that i would link to sequelize

**Comment by Fjandin** [comment]
Seems it's linked to this yarn issue: https://github.com/yarnpkg/yarn/issues/761

closing

**Comment by bbnnt** [comment]
node v7.2.1, sequelize 3.27.0, pg 6.1.1 returns the same problem when running migrations. Seleted node_modules, reinstalled sequelize and sequelize-cli globally, etc… still stuck with this error

**Comment by iamkirkbater** [comment]
Looks like this has to do with where you have the modules installed.

I was running a globally installed `sequelize`, and got this error.  When I ran `./node_modules/.bin/sequelize` from the node_modules folder it ran fine.

So if you're running `sequelize` from the globally installed node folder, you'll need to also have `pg` installed globally

**Comment by Jeffchiucp** [comment]
Looks like this has to do with where you have the modules installed.
`npm uninstall -g sequalize`

**Comment by presmini** [comment]
for me the solve was to use npm install instead of yarn.

**Comment by jevdiego** [comment]
Hey,

I'm receiving this issue too. I'm running on Windows 10. When I run 'sequelize db:migrate', I get the following:

> Sequelize CLI [Node: 8.6.0, CLI: 4.0.0, ORM: 4.37.6]
> 
> Loaded configuration file "database\config\config.json".
> Using environment "development".
> 
> ERROR: Please install 'pg' module manually

I've made sure pg is installed, but still receive this. I have also tried removing sequelize globally as mentioned above. Any ideas on what else I can do to fix this?

**Comment by jevdiego** [comment]
After a good 2 hours of trying to solve this, I ran 'npm link' because I wanted to place some debug logs in the sequelize module. It then worked :/

I'd like to properly understand this. Does this mean that it was using the global sequelize folder in "C:\Users\_User_\AppData\Roaming\npm\node_modules"? And then couldn't load 'pg' from there?

I did try to install pg globally though -> npm install -g pg
So in that case I would have thought this would work.

**Comment by apoorvparijat** [comment]
Adding the below code solved my problem

```
custom:
  webpackIncludeModules:
    forceInclude:
      - pg
```

**Comment by jerrychong25** [comment]
> node v7.2.1, sequelize 3.27.0, pg 6.1.1 returns the same problem when running migrations. Deleted node_modules, reinstalled sequelize and sequelize-cli globally, etc… still stuck with this error.
> Solved this by installing pg globally (`npm install -g pg`). Is that a new requirement ?

Thanks, `npm install -g pg` fixed this issue.

**Comment by nahumzs** [comment]
I followed the proposed solutions but didn't work:

```yml
custom:
  webpack:
    includeModules:
      forceInclude:
        - pg
        - pg-hstore
```

I ended switching to mysql because I tried even the solution that I copy/pasting from https://github.com/sequelize/sequelize/issues/9489#issuecomment-493304014 and couldn't make Postgres worked.

```js
// this works with mysql
import Sequelize from 'sequelize';
import mysql2 from 'mysql2'; // Needed to fix sequelize issues with WebPack

const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    dialect: 'mysql',
    dialectModule: mysql2, // Needed to fix sequelize issues with WebPack
    host: process.env.DB_HOST,
    port: process.env.DB_PORT
  }
)

export async function connectToDatabase() {
  console.log('Trying to connect via sequelize')
  await sequelize.sync()
  await sequelize.authenticate()
  console.log('=> Created a new connection.')

  // Do something 
}
```

**Comment by mrazadar** [comment]
This issue can be resolve either by installing `pg` package globally. Or by installing `sequelize` and `sequelize-cli` packages locally. With local installation you can run sequelize like `./node_modules/.bin/sequelize db:migrate`

**Comment by SANCHEZSJD** [comment]
I have same error, But no solution work for me.
someone has another solution. I work with serverles offline and sequialize

**Comment by ElijahKaftanov** [comment]
a workaround that just works
```typescript
import * as pg from 'pg';
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize('postgres://admin:admin@localhost:5432/mydb', {
  dialectModule: pg
});
```

**Comment by ElijahKaftanov** [comment]
a workaround that just works
```typescript
import * as pg from 'pg';
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize('postgres://admin:admin@localhost:5432/mydb', {
  dialectModule: pg
});
```

**Comment by wa4-fearless-otter** [comment]
I still have this issue, why is this issue closed?

**Comment by wa4-fearless-otter** [comment]
I'm starting to think this is because we use a build tool (something like webpack)?

**Comment by iamkirkbater** [comment]
I've been out of the Javascript ecosystem for a while now, so I can't be certain, but have you tried any of the "workarounds" listed above?  Either `npm install -g pg` or `./node_modules/bin/sequelize [rest of sequelize command]`?

**Comment by wa4-fearless-otter** [comment]
@iamkirkbater Yeah i tried those, both don't work for me.

**Comment by leolio86400** [comment]
This issue has been fixed in v5 but is back in v6 😬

**Comment by abhishekpal1993** [comment]
I was using webpack and I got it working by following changes:

- npm install: 
```bash
npm install --save-dev noop2
npm install pg pg-hstore
```

- webpack.config.js

```javascript
module.exports = {
  // .... all your webpack config here after that add resolve
  resolve: {
    alias: {
      'pg-native': 'noop2',
      tedious: 'noop2',
      sqlite3: 'noop2',
      mysql2: 'noop2',
    },
  },
};
```

- code:

```javascript
import * as pg from 'pg';
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize(
  process.env.DB_NAME, //database
  process.env.DB_USER, //username
  process.env.DB_PASSWORD, //password
  {
    host: process.env.DB_HOST,
    dialect: 'postgres',
    dialectModule: pg,
  });

(async () => {
  try {
    await sequelize.authenticate();
    console.log('Connection has been established successfully.');
  } catch (error) {
    console.error('Unable to connect to the database:', error);
  }
})();
```

**Comment by leolio86400** [comment]
Hum, in your case makes sense that it works as you use `import * as pg from 'pg';` webpack will import it, solving the issue.

Where did you find the documentation for `dialectModule: pg` ? 

the documentation is using dialect with a string (and the search don't seem to find it -_-) 
```
// Option 1: Passing a connection URI
const sequelize = new Sequelize('sqlite::memory:') // Example for sqlite
const sequelize = new Sequelize('postgres://user:pass@example.com:5432/dbname') // Example for postgres

// Option 2: Passing parameters separately (sqlite)
const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: 'path/to/database.sqlite'
});

// Option 2: Passing parameters separately (other dialects)
const sequelize = new Sequelize('database', 'username', 'password', {
  host: 'localhost',
  dialect: /* one of 'mysql' | 'mariadb' | 'postgres' | 'mssql' */
});```

**Comment by abhishekpal1993** [comment]
@leolio86400 I found it in the source code: https://github.com/sequelize/sequelize/blob/d06aa0327a3c4f5dfbe9a563813d1ff1e7fec41c/src/sequelize.js#L132

**Comment by samgj18** [comment]
> I was using webpack and I got it working by following changes:
> 
> * npm install:
> 
> ```shell
> npm install --save-dev noop2
> npm install pg pg-hstore
> ```
> 
> * webpack.config.js
> 
> ```js
> module.exports = {
>   // .... all your webpack config here after that add resolve
>   resolve: {
>     alias: {
>       'pg-native': 'noop2',
>       tedious: 'noop2',
>       sqlite3: 'noop2',
>       mysql2: 'noop2',
>     },
>   },
> };
> ```
> 
> * code:
> 
> ```js
> import * as pg from 'pg';
> import { Sequelize } from 'sequelize';
> 
> const sequelize = new Sequelize(
>   process.env.DB_NAME, //database
>   process.env.DB_USER, //username
>   process.env.DB_PASSWORD, //password
>   {
>     host: process.env.DB_HOST,
>     dialect: 'postgres',
>     dialectModule: pg,
>   });
> 
> (async () => {
>   try {
>     await sequelize.authenticate();
>     console.log('Connection has been established successfully.');
>   } catch (error) {
>     console.error('Unable to connect to the database:', error);
>   }
> })();
> ```

Thanks a lot!

**Comment by jmrapp1** [comment]
Ran into this issue while using NextJS and the `serverless-nextjs-plugin`. The solution for me was the following:

Original code with error:
```
import { Sequelize, Model } from 'sequelize';

export const sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_USERNAME, process.env.DB_PASSWORD, {
    host: process.env.DB_HOST,
    port: 5432,
    dialect: 'postgres'
});
```

Fix (notice pg import and `dialectModule` specification):
```
import { Sequelize, Model } from 'sequelize';
import pg from 'pg';

export const sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_USERNAME, process.env.DB_PASSWORD, {
    host: process.env.DB_HOST,
    port: 5432,
    dialect: 'postgres',
    dialectModule: pg
});
```

**Comment by jhonsore** [comment]
Hey coders.

I had this same problem and lost a long time to figure out the solution.

My project is based on lambda serverless from AWS.

In my serverless.yml file i was using [serverless-bundle](https://www.npmjs.com/package/serverless-bundle) to optimize my package.

After a long time of testing i figured out that this pack need some configurations when using sequelize.

https://www.npmjs.com/package/serverless-bundle#sequelize

About documentation:

To use the Sequelize package along with pg, you'll need to ignore it from Webpack and using the dialectModule option. Read more here.

In your serverless.yml:

```
custom:
  bundle:
    ignorePackages:
      - pg-native
```

And in your Lambda code:

```
const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USERNAME,
  process.env.DB_PASSWORD,
  {
    host: process.env.DB_HOST,
    dialect: process.env.DB_DIALECT,
    dialectModule: pg
  }
);
```

Wehre pg is your pg module import like: 

`import pg from "pg";`

I hope it helps someone!

Enjoy coding.

**Comment by Murmurianez** [comment]
The same but without webpack and etc.:

```
import * as pg from 'pg';

const sequelize = new Sequelize({
    ...
    dialectModule: pg
});

```
npm install --save-dev noop2

package.json:

```
{
    dependencies: {
        "pg-native": "file:./node_modules/noop2"
    }
}
```

**Comment by papb** [comment]
Possibly related: #13169

**Comment by luca-serra** [comment]
If that can help someone: 

In my case, the version of sequelize-cli I was running was not functional, I had to use `npx`:
`npx sequelize *command*`

**Comment by ali-soltanii** [comment]
I found a fix that worked for me! If you have webpack configured it might help.
First, install webpack-node-externals

`yarn add -D webpack-node-externals`

then in your webpack require it

`const nodeExternals = require('webpack-node-externals')`

and finally in your config :

`externals: [nodeExternals()]`

**Comment by narayoga** [comment]
> node v7.2.1, sequelize 3.27.0, pg 6.1.1 returns the same problem when running migrations. Deleted node_modules, reinstalled sequelize and sequelize-cli globally, etc… still stuck with this error. Solved this by installing pg globally (`npm install -g pg`). Is that a new requirement ?

**Comment by Kmelow** [comment]
I'm having the same issue while using `npm` so the problem is not linked to `yarn` (as suggested above), those are the things I tried:

- I can't install it globally, as suggested, because I need it to run in a Lambda funtcion
- I installed `npm i --save pg` and also installed `npm i -D @types/pg` because I'm using TS
- I imported `import * as pg from 'pg';` and also `import { Sequelize } from 'sequelize';`, then `const s = new Sequelize(connecStr, {dialectModule: pg})`
- I do not need to manually configure webpack and do not want to include it just for the sake of making a SQL query.

Related issues:
- [sequelize-auto](https://github.com/sequelize/sequelize-auto/issues/109)

**Comment by MuhammadZeeshan2** [comment]
I have developed an Express app that is working correctly on my local machine. Now, I am attempting to host it on Vercel, but I am encountering the following error. 
![image](https://github.com/sequelize/sequelize/assets/123735611/4b9b180a-8785-45e6-97ea-8cc9bbb1db56)

When I check the logs, it indicates that there is an issue.
"
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/var/task/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:55:15)
    at new ConnectionManager (/var/task/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:18:21)
    at new SqliteDialect (/var/task/node_modules/sequelize/lib/dialects/sqlite/index.js:13:30)
    at new Sequelize (/var/task/node_modules/sequelize/lib/sequelize.js:194:20)
    at Object.<anonymous> (/var/task/services/database.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Ze.e.<computed>._module.Module._load (/var/task/___vc/__launcher/__launcher.js:14:1964)
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/var/task/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:55:15)
    at new ConnectionManager (/var/task/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:18:21)
    at new SqliteDialect (/var/task/node_modules/sequelize/lib/dialects/sqlite/index.js:13:30)
    at new Sequelize (/var/task/node_modules/sequelize/lib/sequelize.js:194:20)
    at Object.<anonymous> (/var/task/services/database.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Ze.e.<computed>._module.Module._load (/var/task/___vc/__launcher/__launcher.js:14:1964)
Error: Runtime exited with error: exit status 1
Runtime.ExitError

"
I think i have installed sqlite3 already as i am using the following package.json file 
package.json file 
"
{
  "name": "funrun4",
  "version": "0.0.0",
  "private": true,
  "main": "/index.js",
  "engines": {
    "node": "18.x"
  },
  "scripts": {
    "start": "node ./bin/www",
    "dev": "nodemon ./bin/www -e js,ejs,html,css"
  },
  "dependencies": {
    "app-module-path": "^2.2.0",
    "cookie-parser": "~1.4.4",
    "debug": "~2.6.9",
    "dotenv": "^16.3.1",
    "ejs": "^3.1.9",
    "express": "^4.18.2",
    "http-errors": "~1.6.3",
    "morgan": "~1.9.1",
    "sequelize": "^6.33.0",
    "sqlite3": "^5.1.6"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  }
}

"



 I am not sure how to resolve this problem. Please provide guidance on how to correct it.

**Comment by lemaar** [comment]
I can see this problem is around since last few years.  I had the same issue with Next.js.

**The solution is**:
- call to the sequelize connection should be processed before calling any other sequelize functions.
- In the Next config file add sequelize in array serverComponentsExternalPackages 
- And, assign MySQL2 in the dialectModules.

See the video https://youtu.be/jO8y1vHsyD0?si=kmSvKqBDBdMDqYSJ for more details.

Any questions, feel free to comment 😊

**Comment by salil-khanna** [comment]
In case anyone still has the issue with vercel, add at the top:

import "pg"

**Comment by OkancanCosar** [comment]
"next": "15.0.3",

"pg": "^8.13.1",
"pg-hstore": "^2.3.4",
"sequelize": "^6.37.5",


import pg from "pg"
import { Sequelize } from 'sequelize'

const sequelize = new Sequelize('dbname', 'dbuser', 'dbpass', {
   host: 'localhost',
   dialect: 'postgres',
   dialectModule: pg, // add this !
});
