### ISSUE TITLE
queryInterface.bulkUpdate usage

### ISSUE THREAD

**Issue by Jhovanni** [sequelize/sequelize#6909]
Is there any documentation or info available to use queryInterface.bulkUpdate method?
I'm trying to update several columns using a seeder file. But I cannot get it work, log keeps trowing
Seed file failed with error: val.replace is not a function

I know it should be something with the parameters passed, but looking at the method signature, there is no way I can figure out what params should be passed and how.

This is my code right now:

```
up : function(queryInterface, Sequelize) {
	return queryInterface.bulkUpdate("Catalogo", catalogos, {});
}
```

```
var catalogos = [
	{numero:"001", eExperiencia:64, eSalud:2},
	{numero:"002", eExperiencia:56, eSalud:3}
];
```

Table Catalogo has numero as primary key, and I'm trying to change its eExperiencia and eSalud values.

**Comment by janmeier** [comment]
Bulk update allows you to update a set of rows, matching a where clause (http://docs.sequelizejs.com/en/v3/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows), i.e. something like `UPDATE foo SET bar = 42 WHERE baz = 50;`. It does not support updating multiple rows to different values

**Comment by Jhovanni** [comment]
But that documentation is about update in sequelize object. There is a bulk update with the following signature in queryInterface

`bulkUpdate(tableName, values, identifier, options, attributes);`

How can I use it?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/blob/50866b8b89417f68ce3fc2e841c671931fc111a7/lib/model.js#L2391
https://github.com/sequelize/sequelize/blob/50866b8b89417f68ce3fc2e841c671931fc111a7/lib/query-interface.js#L569

You've already read this far into the code, why don't you go ahead and read the rest. As I've said it's not part of the public API, and it _cannot_ be used for what you want to do - Many separate updates in bulk. It can only do a single update (setting the same values) on many rows

**Comment by Jhovanni** [comment]
Thank you.
Then I'll make a promise to update each item individually

**Comment by mmenik** [comment]
I dont understand how pass parameters of function
queryInterface.bulkUpdate(tableName, values, identifier, options, attributes);

I need for update a single row (filter by id) in a seeders file, you can show an example? 
Thanks

**Comment by bruno-serfe** [comment]
Where is the documentation of bulkUpdate? this is the only I can see in the docs: 

http://docs.sequelizejs.com/manual/tutorial/instances.html#working-in-bulk-creating-updating-and-destroying-multiple-rows-at-once-

but there's no information about multiple records update at one time.

**Comment by bruno-serfe** [comment]
So specifically that I'm trying is to update is one field from multiple records (rows) with different values for that field on each row.

**Comment by chaoxihailing** [comment]
I dont understand how pass parameters of function
queryInterface.bulkUpdate(tableName, values, identifier, options, attributes);

I hava a table monitorDevice has fileld like id, monitorSpotId, alarmTypeDeviceSubType, isAvailable; 
and I want to update column alarmTypeDeviceSubType, but it not work;

I write query like below, How can I work
![image](https://user-images.githubusercontent.com/17508916/33206011-e17b4aaa-d143-11e7-98ba-87f5395e8612.png)
