### ISSUE TITLE
Unicode Datatype

### ISSUE THREAD

**Issue by amitava82** [sequelize/sequelize#691]
Hi, If I define a column with Sequelize.STRING, can it store unicode character? If not, how would I go about doing it? Thanks.

**Comment by rafis** [comment]
Converting type from DataType class to String causes different processing in Sequelize internals. If type is String it considered as strict instruction to use this type as is and it looks non-native to Sequelize.

    {
        type: 'VARCHAR(255)',
        allowNull: false,
        Model: table,
        fieldName: 'column',
        _modelAttribute: true,
        field: 'column'
    }

If type is native DataType:

    {
        type: {
            options: {
                length: 255,
                binary: undefined
            },
            _binary: undefined,
            _length: 255
        },
        allowNull: true,
        defaultValue: 0,
        Model: table,
        fieldName: 'column',
        _modelAttribute: true,
        field: 'column'
    }

It has valuable `_length` attirbute which I need. Can you please add to column definition ability to specify `charset` and `collate` like it done on table params:

    slug: {
            type: DataTypes.STRING(255),
            charset: 'latin1',
            collate: 'latin1_bin',
            allowNull: false
    }

**Comment by alfaproject** [comment]
@rafis was that ever implemented? I can't find it anywhere. ):

**Comment by Benew** [comment]
+1
