### ISSUE TITLE
Managed transaction not work with sqlite

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6910]
## I use sequelize with sqlite3,but Managed transaction still not commit.
below is my code:
```js
insertUser(obj,options) {
         return new Promise((resolve, reject) =>{//sequelize use deferred,so i use es6 Promise warp it.
             sequelize.transaction().then(t => {
                  Object.assign(options, { transaction: t });
                 return user.create(obj,options);
            }).then(resolve).catch(reject);
         });
}
findUser(){
   insertUser({name:'mike'}).then(u=>{
       console.log(u);//i can get u,but not commit into sqlite!
       user.find({where:{id:u.id}}).then(r=>{
              console.log(r);//only get 'null'
       });
   })
}
```

## What do you expect to happen?
I hope insertUser commited before invoke findUser

## What is actually happening?
insertUser not commit.

__Dialect:sqlite 
__Database version:sqlite3
__Sequelize version:^3.24.5

**Comment by felixfbecker** [comment]
Because you are not calling `t.commit()` anywhere.
Btw Sequelize does not not use "deferred", it uses Bluebird promises. You can convert them to an ES6 promise with `Promise.resolve()`.

**Comment by keyiis** [comment]
@felixfbecker document said `Notice how the callback passed to transaction returns a promise chain, and does not explicitly call t.commit() nor t.rollback(). If all promises in the returned chain are resolved successfully the transaction is committed. `.

**Comment by felixfbecker** [comment]
> Notice how the callback passed to transaction returns a promise chain

You do not pass a callback to the transaction though. You need to pass a callback that returns a promise, or call `t.commit()` yourself.

This is not a help forum - if you have question about usage, please use StackOverflow or Slack.

**Comment by keyiis** [comment]
@thanks reply! how to `pass a callback that returns a promise` in the foregoing code?
