### ISSUE TITLE
sequelize js count result set model association

### ISSUE THREAD

**Issue by shivshankar3578** [sequelize/sequelize#6911]
Sequelize@latest
I've three models
- post
- postTag
- tag
I  just like to add tag count while getting postTag. Here is my getPost controller 
<pre>models.post.findAll({
  include: [
      {
            model: models.postCity,
            include:[{model:models.region}]
     },
    {
      model: models.postTag,
      //include:[{model:models.tag}],
      //attributes: [[models.sequelize.fn('count', models.sequelize.col('postTags.post_id')), 'count']]
     // adding above count error : post_id is unambiguous 
 }
  ],
    where: postData.where
})
</pre>
here is my PostTag model
<pre>
var models = require('../models');
module.exports = function (sequelize, DataTypes) {
  return sequelize.define('postTag',
    {
      post_id: {
          type:DataTypes.INTEGER,
          primaryKey: true
      },
      tag_id: {
          type:DataTypes.INTEGER,
          primaryKey: true
      },
      order_no: DataTypes.INTEGER,
      create_time: DataTypes.DATE,
    },
    {
      timestamps: false,
      underscored: true,
      freezeTableName: true,
      tableName : 't_post_tag',
      classMethods:
        {
          associate: function (models) {
          models.postTag.belongsTo(models.post,{  foreignKey :"post_id", targetKey:"post_id" });
          //models.postTag.belongsTo(models.tag,{  foreignKey :"tag_id", targetKey:"tag_id" });
        }
        },
        instanceMethods: {
          tag_name: function () {
              return models.tag.findById(this.getDataValue('tag_id'));
          },
          count: function(){
            // please  complete this
          }
        },
        getterMethods: {
            // tag_name: function () {
            //     return models.tag.findById(this.getDataValue('tag_id'));
            // }
        },
        setterMethods: {

        }
    }
    );
  }</pre>
Now i'm gtting this response
<pre>
{
  "status": true,
  "response": [
    {
      "create_time": "Tue Nov 22 2016",
      "post_id": "38",
      "description": "good palce",
      "create_by": 67,
      "update_time": "2016-11-22T15:32:22.985Z",
      "country_id": 156,
      "postTags": [
        {
          "post_id": 38,
          "tag_id": 8,
          "order_no": 1,
          "create_time": "2016-11-21T18:30:00.000Z",
          "tag": {
            "tag_id": 8,
            "tag_name": "Hiking",
            "tag_type": "Travel Activity",
            "create_time": "2016-09-23T06:12:00.000Z"
          }
        }
      ]
    }
  ]
}</pre>
Here is two issues
- [ ] i'm not getting count key in postTag array
- [ ] Can anyone tell a method to get tag_name as key in postTag array instead of containing whole array see the response 
- [ ] I need to search using tag_name and  result order by count of  matched tag
- [ ] I also need to search a value in both model postCity and postTag, how to use where clause
I gets tired of paying efforts in instanceMethod see in model. save me please

**Comment by janmeier** [comment]
Your example is missing some model defintions and associations - Please provide a complete [SSCCE](HTTP://SSCCE.ORG/)

**Comment by shivshankar3578** [comment]
I didn't miss anything important. There is  a tag model also, pointing table tag which tag_name. My code working fine accept count and i want to modify response

**Comment by janmeier** [comment]
Please read the description of a [SSCCE](HTTP://SSCCE.ORG/) - We need a self contained test case to be able to replicate your issue

**Comment by janmeier** [comment]
(I tried, but everything I did worked fine, so there must be something more to your setup)
