### ISSUE TITLE
Conditional exclude on findAll()

### ISSUE THREAD

**Issue by AliUz** [sequelize/sequelize#6912]
```js
 sequelize.define('Person', {
    about: {
      type: Sequelize.STRING
    },
    phone: {
      type: Sequelize.STRING,
    },
    isPhonePublic: {
      type: Sequelize.BOOLEAN
    }
  })

```

```js
  return Personl.findAll({
    attributes: { exclude: ['phone'] }
  })
```

I want to exclude `phone` only if `isPhonePublic` is set to false, otherwise I want to include it. Is there a way to do an conditional exclude like this? Or do I need to filter out the phone numbers by post-processing the list of people that is returned?

Thank you.

**Comment by janmeier** [comment]
Post-processing, most definitely - Not even sure how that would look in sql :) ?
