### ISSUE TITLE
BelongsTo declaration with a constraint false make the foreignKey accessible in the model attributes

### ISSUE THREAD

**Issue by arnaudbesnier** [sequelize/sequelize#6917]
If I have a model declared like this:
```javascript
  var project = sequelize.define('project', {
    name: { type: DataTypes.STRING }
  }, {
    classMethods: {
      associate: function () {
        project.belongsTo(models.environment, {
          as: 'defaultEnvironment',
          foreignKey: 'defaultEnvironmentId',
          constraints: false
        });
      }
    }
});
```
The `project.attributes` will contain a `defaultEnvironmentId` key.

If I remove the `constraints: false`, `defaultEnvironmentId` will disappear from the `project.attributes`.

I would like not to have the foreignKey in the attributes even with `constraints: false`.
Is it a bug or a feature?

**Comment by janmeier** [comment]
Cannot reproduce - Please open a PR with a failing test, or provide a [SSCCE](HTTP://SSCCE.ORG/)

**Comment by arnaudbesnier** [comment]
Sorry for the first explanation.

This is what I observed on this SSCCE:

```javascript
'use strict';
const Sequelize = require('sequelize');
const express = require('express');

let databaseOptions = {
  logging: process.env.NODE_ENV === 'development' ? console.log : false,
  pool: { max: 10, min: 1 }
};

if (['staging', 'production'].indexOf(process.env.NODE_ENV) > -1) {
  databaseOptions.dialectOptions = { ssl: true };
}

console.log(process.env.DATABASE_URL);
let sequelize = new Sequelize(process.env.DATABASE_URL, databaseOptions);
let db = {};

const Environment = sequelize.define('environment', {
  name: { type: Sequelize.DataTypes.STRING },
});

const Project = sequelize.define('project', {
  name: { type: Sequelize.DataTypes.STRING },
});

Environment.belongsTo(Project);
Project.hasMany(Environment);
Project.belongsTo(Environment, {
  as: 'defaultEnvironment',
  constraints: false // NOTICE: Here is the interesting property
});

console.log('= defaultEnvironment Attribute:', Project.attributes.defaultEnvironmentId);
```

If I set the `constraints` property, the `Project.attributes.defaultEnvironmentId.references` will be `undefined`.

I feel that this is a bug. @janmeier what do you think about that?

**Comment by janmeier** [comment]
That is by definition what constraints false does - it does not not create referential constraints.

It's useful in cases where you have circular references so you need to remove the reference on one side when creating the table

**Comment by arnaudbesnier** [comment]
ok, so by doing model introspection, their is no way for me to detect that this specific column is related to a `belongsTo` association (with the `constraints` set to `false`).

A workaround would be to look at the model associations and detect the column related.
I'll try that.

**Comment by arnaudbesnier** [comment]
ok `association.identifierField` enables to do what I wanted to do.
See the code here: https://github.com/ForestAdmin/forest-express-sequelize/pull/111/files

Thanks for the help!
