### ISSUE TITLE
Row not insert sequelize transaction findOrCreate  

### ISSUE THREAD

**Issue by shivshankar3578** [sequelize/sequelize#6922]
I'm facing a issue while findOrCreate using transaction 
sequelize@latest
database@Postgresql
here id my function
<pre>   models.sequelize.transaction(function (t) {
     return models.itineraryDay.findCreateFind({where: where, defaults:{summary:postData.summary}, transaction: t })
     .then(function(day) {
      console.log(day)
// other transaction ...
}
.error(function (err) {
      console.log(err);
        return res.status(200).json({ status: false, message: "serverError" });
    });
</pre> 
here is my itineraryDay model 
<pre>
var models = require('../models');
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('itineraryDay',
      {
        itinerary_id: {
            type:DataTypes.INTEGER
        },
        day: {
          type: DataTypes.INTEGER
        },
        summary: DataTypes.TEXT,
        day_id:{
          type:DataTypes.INTEGER,
          primaryKey:true,
          autoIncrement:true
        }

      },
      {
        timestamps: false,
        underscored: true,
        freezeTableName: true,
        tableName : 't_itinerary_day',
        classMethods:
          {
            associate: function (models) {
              models.itineraryDay.belongsTo(models.itinerary,{  foreignKey :"itinerary_id", targetKey:"itinerary_id" });
              models.itineraryDay.hasMany(models.itineraryItem,{foreignKey :"day_id", targetKey:"day_id"});
              }
          },
          getterMethods: {
               
          },
          setterMethods: {
   
          }
          });
  }
</pre>
 i'm providing var where **{ itinerary_id: '1', day: '8' }**
Here i m getting  response **{ day_id: 36, summary: 'test', itinerary_id: '1', day: 8 }** but actually no row insert into database and this failed other subsequent  transaction.
**Here is also notice autoIncrement value updated mean if i insert manually form database then autoIncreament in 38  instead of 37**

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by shivshankar3578** [comment]
I didn't get  SSCCE but issue sloved by myself. thanks
