### ISSUE TITLE
Defined DataTypes Being Ignored, String being treated as Date

### ISSUE THREAD

**Issue by Aukhan** [sequelize/sequelize#6923]
Hey Guys,
I know that Questions are for Stackoverflow but this is different(hopefully), All your response and attention is much appreciated.
We ran into a lot of trouble with dates and sequelize, we just wanted to create an api with sequelize where it should ideally just import and export the data into and from the database, but thats not the case with `DataTypes.Date/DateTime`. We had to setup getters, setters to avoid timezone issues and then the worst was to override the `toJSON` methods to make sure the dates exported were in the same format as in the DB. Since Sequelize reads it as a JS Date object, it exports it as Date.toString() output.

After all this, I know you aren't going to like this, we decided to change the `DataTypes.Date/DateTime` to `DataTypes.String` to make Sequelize just avoid parsing date fields into JS Date objects. Unexpectedly, Sequelize DOES NOT treat it as a string value. What Im experiencing is that it still sees the database (type) for the field and converts it into a JS Date object even though we have defined it to be a string as `type: DataTypes.String`.

We're in too deep with sequelize at this point, and we love all the functionality that it brings for us, but there doesn't seem to be an easy way to handle dates. Ideally, we just want it to export the value fetched from the DB with less code.

Testing this is easy, define a date column in the database as a string column in sequelize, and the fetched value by sequelize is still `typeof field => object` not string.

Thanks a lot for reading.

__Dialect:__ mysql
__Database version: MariaDB 10.0.25
__Sequelize version: 3.23.3

**Comment by janmeier** [comment]
Much of the date handling is handled by the DB drivers, and not by sequelize, so it's hard to disable completely.

Can you be more specific about the issues you have been experiencing? By default sequelize assumes that you want to store dates in UTC, and parses them back is if they were UTC - But this can of course be configured.
Javascript dates can be confusing, especially the fact that logging them to the console shows them in your local timezone, not in the timezone of the input (what was stored in the database), but this is just how javascript works, and the date still represents the same point in time

**Comment by felixfbecker** [comment]
The data type you set in the model definition must match the data type in the database.
Sequelize converts `DATE` to `Date` (which is the job of a good driver/ORM). `DATEONLY` will not be parsed as `Date` in v4 anymore, see https://github.com/sequelize/sequelize/pull/6709.

**Comment by Aukhan** [comment]
@felixfbecker thanks for clearing that, like I said it was just a weird workaround, now I know that it can't be done that way.

@janmeier 
so when I pass a date such as "2016-11-28 12:15:00"
Sequelize will add/remove the timezone to bring it to UTC.
Then I have to add a `Z` at the end and a `T` between data and time to tell it that the sent date is already UTC. Since we are building an api we want to enforce a format, we want to tell sequelize to treat dates as is and not add/remove any timezone information to it.

The second part is when I read an object and want to export it, I want the same format as was in the database, but this is represented as "2016-11-28T12:15:00.000Z".
My code and api does not expect it to be in that format, Ideally I dont want to change any client side code or mobile app code to integrate this. So that forces me to override the toJSON() methods to make sure the format remains the same.
Need to understand the best possible way to deal with all this. Dont want my code to smell, is my main concern here :(

**Comment by felixfbecker** [comment]
@Aukhan Any date that comes _into_ Sequelize will be parsed as local timezone or by the timezone that is embedded in the date. This works with `Date` objects and ISO date strings. Dates that _come out_ of Sequelize are `Date` objects which get JSON-stringified to an ISO date string with local time zone. In Postgres, Sequelize uses a `timestamp_tz` data type (date/time with timezone) to represent the date, and will save it normalized with a UTC time zone (it will still represent the same point in time!). Sending back the Postgres-specific format to your client would not make sense, ISO is standardized and any client should be able to parse an ISO date string. It is not clear to me where you are seeing an issue in Sequelize's behavior here.

**Comment by janmeier** [comment]
Well, actually any timestamp that comes from mysql will be parsed as UTC by default. Mysql does not store the timezone like postgres does, so we tell the driver that it should parse the date is UTC: https://github.com/sequelize/sequelize/blob/9b73d157b3adfdf05bdefe0da3df6db1526408d2/lib/dialects/mysql/connection-manager.js#L78

I guess you could override the parse function for dates, like [this](https://github.com/sequelize/sequelize/blob/9b73d157b3adfdf05bdefe0da3df6db1526408d2/test/integration/data-types.test.js#L46) to return strings instead of dates - But other parts of sequelize might assume that the date is a date object, and ttry to call date methods on it.

You don't need to override `toJSON`, you should be able to just provide custom getters for the date fields, which should be slightly cleaner

**Comment by Aukhan** [comment]
@janmeier I think the parse and stringify methods you've pointed me towards are what I need.
If I can force the parse to use `moment.utc` does that mean that any "incoming" date will also be parsed into UTC or in other words date setters will parse it as UTC ?
On the other hand I think @felixfbecker is right that the stringify output is formatting irrespective for date, dateonly and timeonly fields. We may have to change some of our client side code for that but I think it makes sense in the long run.

This is a legacy application guys that we are porting to node and we want to make sure we use the best practices. I really appreciate your response and the work you guys are doing for this library. :+1:

**Comment by felixfbecker** [comment]
Okay, as there is nothing really that should be changed in Sequelize I will close this - feel free to ask questions on Slack if you need further help

**Comment by Aukhan** [comment]
@janmeier The Date.parse override idea was great, because I wanted for any date type to return a `moment` instance for me instead of plain `Date`. There I could also force it to work with utc.
But I can't seem to get that override to work in version 3.27, Is it a 4.0 only thing ?
Is it possible in 3.27 ?

Thanks for your help man !

**Comment by janmeier** [comment]
Should work in v3 as well, but there might have been some further changes in v3
