### ISSUE TITLE
[Associations] HasMany Method remove[Associations] use update not user destroy

### ISSUE THREAD

**Issue by LowryTang** [sequelize/sequelize#6926]
Hi, I have a problem with this. I have one to many models, and want to remove the associations and really delete from table. In the document, it said the removeAssociations function through destroy. But it still use update, and I check the source code, the remove function in has-many.js is use update not user destroy.

any possible that I can delete associations, not just SET NULL? 

example

```js
User = sequelize.define();
Role = sequelize.define();

User.hasMany(Role);
Role.belongsTo(User);

var user = User.findById(id);

user.removeRoles(user.Roles);

```
sql output, I want to delete role in table.
```
Executing (default): SELECT `User`.`id`, `User`.`firstname`, `User`.`lastname`, `User`.`display_name` AS `displayName`, `User`.`email`, `User`.`active`, `User`.`isAdmin`, `User`.`created_at`, `User`.`updated_at`, `UserRoles`.`id` AS `UserRoles.id`, `UserRoles`.`name` AS `UserRoles.name`, `UserRoles`.`created_at` AS `UserRoles.created_at`, `UserRoles`.`updated_at` AS `UserRoles.updated_at`, `UserRoles`.`user_id` AS `UserRoles.user_id` FROM `users` AS `User` LEFT OUTER JOIN `user_roles` AS `UserRoles` ON `User`.`id` = `UserRoles`.`user_id` WHERE `User`.`id` = '0faacfa5-e998-43bb-b37d-4d73a7d8cb04';
Executing (default): UPDATE `user_roles` SET `user_id`=NULL,`updated_at`='2016-11-29 00:53:42' WHERE `user_id` = '0faacfa5-e998-43bb-b37d-4d73a7d8cb04' AND `id` IN ('ad3b7cbe-9ebb-4c20-b9ac-17d6d429b39a')
```

__Dialect:__ mysql
__Database version:__ 5.7
__Sequelize version:__ 3.27.0

**Comment by felixfbecker** [comment]
No, at least not for hasMany. That would require another function like `destroyAssociation`.
But you can do this in one line.
```js
Promise.all(user.roles.map(role => role.destroy()))
```
But I don't know if this is what you want. If another user still has that role, the role will be deleted for him too. Are you aware of that?

**Comment by LowryTang** [comment]
@felixfbecker  Thanks you for your response, the way you mentioned is what I used now. as your said, if another user also has the same role, the model for association should be N to N, not 1 to N, right? is any plan to add destroy associations function in 1:N? Thanks again.

**Comment by felixfbecker** [comment]
No, there are no plans.

**Comment by Somebi** [comment]
Was surprised about this behavior as well in recent project.

**Comment by Somebi** [comment]
I think difference in remove and destroy should be mentioned in the docs

**Comment by jeffersonaguilar95** [comment]
> No, at least not for hasMany. That would require another function like `destroyAssociation`.
> But you can do this in one line.
> 
> ```js
> Promise.all(user.roles.map(role => role.destroy()))
> ```
> 
> But I don't know if this is what you want. If another user still has that role, the role will be deleted for him too. Are you aware of that?

This works, but can be improved:

```
const rolesToBeRemoved = await user.getRoles()
await user.removeRoles(rolesToBeRemoved)
```

PD: tested with sequelize v5 and v6

**Comment by cincodenada** [comment]
> This works, but can be improved:
> 
> ```js
> const rolesToBeRemoved = await user.getRoles()
> await user.removeRoles(rolesToBeRemoved)
> ```
> 
> PD: tested with sequelize v5 and v6

For those who might stumble across this, this "improved" solution is incorrect, please do not use it. It is in fact exactly what OP was already doing. As OP posted, it doesn't actually remove the associated role records from the database, but rather updates their userId column to null. This disassociates them from the user, but leaves them lingering in the database.

The original solution that @felixfbecker posted does remove the records from the database, as desired. Also, if it is a hasMany association, the concern about other users having the role is moot because the role necessarily only belongs to one user. belongsToMany relationships, of course, are a different matter.

I've created a breif SSCCE that demonstrates the difference, querying the database to assert that the roles were deleted from the database - the first commit uses @jeffersonaguilar95's solution and fails the tests, the second commit uses @felixfbecker's solution and passes.

**Comment by premiumwatchdevice** [comment]
> No, at least not for hasMany. That would require another function like `destroyAssociation`. But you can do this in one line.
> 
> ```js
> Promise.all(user.roles.map(role => role.destroy()))
> ```
> 
> But I don't know if this is what you want. If another user still has that role, the role will be deleted for him too. Are you aware of that?

Amazing.. the best solution to delete along with all associated model files in the path folder..
Worked for me adding `fs.unlink` also inside `promise.all` code
