### ISSUE TITLE
Query related models without primary key

### ISSUE THREAD

**Issue by bayssmekanique** [sequelize/sequelize#6929]
I'm not certain if this is a bug or just a quirk that needs to be documented better.

(Possibly related to https://github.com/sequelize/sequelize/issues/1485)

When querying a model with includes using a `hasMany` relationship, if the model being included does not have a `primaryKey` set only 1 record will be included in the final model.

In the case that I stumbled into, I have a model which has a unique index using a UUID column (`userId`) and string column (`emailAddress`).  Together, these two are sufficiently unique and should not require a dedicated `id` attribute for the tuple, but only 1 record would return from this model without a `primaryKey` attribute on one of the columns.

Is this expected behavior?  Is there a potential fix that I've overlooked?

**Comment by Aukhan** [comment]
This is not a solution as I'm trying to learn things with this community.
Have you declared the primary key in your model definition for one of those columns, userId or emailAddress, something like,

`emailAddress: {}`

**Comment by bayssmekanique** [comment]
The `user` model has a primary key:
```
{
	id : {
		type : Sequelize.UUID,
		defaultValue : Sequelize.UUIDV4,
		primaryKey : true
	},
	createdAt : {
		type : Sequelize.DATE
	},
	updatedAt : {
		type : Sequelize.DATE
	},
	deletedAt : {
		type : Sequelize.DATE
	},
},
```

The `email` did not have a primary key (because neither attribute was sufficiently unique on it's own):
```
{
	userId : {
		type : Sequelize.UUID,
		allowNull : false
	},
	createdAt : {
		type : Sequelize.DATE
	},
	updatedAt : {
		type : Sequelize.DATE
	},
	emailAddress : {
		type : Sequelize.STRING,
		allowNull : false
	},
}
```

The `email` model had a unique index added:
```
queryInterface.addIndex('oauthServices', ['userId', 'emailAddress'], {
	indexName: 'userId_emailAddress_index',
	indicesType: 'UNIQUE'
});
```

So, when I'd perform a `findOne` on the `user` with associations, it would only return the first email (though there are multiple attached).  If I add an `id` attribute as the primary key it solves the problem, but I feel like this should not be necessary since there is already a `unique` constraint.

**Comment by Aukhan** [comment]
In theory I think an `Active Record` should have an `id` attribute or a primary key.

perhaps forging `primaryKey: true` to the `userId` column resolves the issue for you.
Again Im looking forward to learn, if you find a clean solution please do share.
