### ISSUE TITLE
[V4] : remove -> usage

### ISSUE THREAD

**Issue by ggrimbert** [sequelize/sequelize#6933]
Hi,

I was wondering if there is a way to disable the use of ```->``` in queries with Sequelize V4. I am experimenting this version in my app and I have some problems with this.

**Comment by felixfbecker** [comment]
What exact problems?

**Comment by sushantdhiman** [comment]
No I am afraid as we discovered in https://github.com/sequelize/sequelize/pull/6170#issuecomment-234340601 we need to use `->` at least for SQLIte to overcome materialization

Can you elaborate what kind of problems you are facing? We are also working on having aliases removed completely https://github.com/sequelize/sequelize/issues/5708, but there is no ETA

**Comment by ggrimbert** [comment]
In fact, I have a problem generating order by fields on included associations. 
My problem is that the generated order by is not a->b.field but a.b.field
After some researches, I know it's our fault (we generate the string a.b.field in our code).

But as we want to do things right and don't add the character by hand, is this separator into a variable that we can get in our code ?
I mean something like the ```TICK_CHAR_LEFT``` that we can access inside our code ?

**Comment by sushantdhiman** [comment]
Character `->` is overridable, at least for now

**Comment by felixfbecker** [comment]
You should use `[attributeName, direction]` for ordering.

v4 is a breaking release, and there are reasons why we have to use `->` - closing
