### ISSUE TITLE
Allow passing through for each instance in N:M relationship setters

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#6934]
Continuation of #4597 

With this feature something like this will be possible for two N:M linked models

```js
// setting different through entries for each instance linked
N.addMs([
{ target: m1, through: { status: 1 } },
{ target: m2, through: { status: 0 } },
{ target: m3, through: { status: 3 } },
{ target: m4, through: { status: 4 } },
...
])
```

Usual stuff will still work

```js
N.addMs([m1, m2, m3, m4], { through: { status: 12 }}) // setting through for all entries
```

**Comment by felixfbecker** [comment]
Shouldn't this be the inverse of a find? When you do a find on an n:m with an include, you get an object like `ProductTasks` (the alias) that holds the through attributes. So Imo when you do `addMs()` it should read the through attributes from `ProductTasks` per-instance too

**Comment by sushantdhiman** [comment]
I think we already support that, so if you pass an instance with `ProductTasks` already set it will use those values for setting the `through` model attributes. So you may say we actually have a proper (may be ugly) workaround.

I suppose its not always clear what would be the junction table name (due to inflection), this change aims to provide a clean api for setting the individual through attributes, for instances being passed to `addMs`

**Comment by felixfbecker** [comment]
I actually prefer the API where it is actually included in the instance. It's a nice symmetry, `set`/`add` accepts the output of `get`. You can always set the alias yourself. Do we have tests for it?

**Comment by sushantdhiman** [comment]
No I don't think we have any test for setting `through` via junctionTable name in `set/add/create` (for BelongsToMany)
