### ISSUE TITLE
provide sample code for upsert.

### ISSUE THREAD

**Issue by nasr18** [sequelize/sequelize#6937]
whenever i do `upsert`, only new values are inserting. but not updating. 
Here is my query.

```
Model.upsert({
  name: 'myname',
  age: 'myage',
  gender: 'male'
}, {where: {id: 1}}).then(function());
```

where `id` is a unique one.

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by nasr18** [comment]
sorry i don't know what how to do. better you post sample code here. please. @felixfbecker

**Comment by mickhansen** [comment]
@nasr18 how would he be able to post sample code showing a bug in your code?

First of all add some SQL logging so you can see what's going on

**Comment by felixfbecker** [comment]
@nasr18 No. This is an issue tracker for feature requests and bug reports. There is documentation available for upsert. There are also unit and integration tests for upsert, which you can look at. If you need help, ask on StackOverflow or Slack. If you think you found a bug, provide a full test case to reproduce the issue.

**Comment by nasr18** [comment]
ok just tell me one thing. Is my code mentioned above in correct syntax? or wrong? @felixfbecker @mickhansen

**Comment by felixfbecker** [comment]
I would have to look at the documentation myself
