### ISSUE TITLE
afterUpdate not triggered

### ISSUE THREAD

**Issue by rastkojokic** [sequelize/sequelize#6938]
Hey guys! What am I doing wrong? Here is the code (nothing special):

model:
```
'use strict';
module.exports = function(sequelize, DataTypes) {
  var JobApplication = sequelize.define('JobApplication', {
    RecruitId: DataTypes.INTEGER,
    JobId: DataTypes.INTEGER,
    status: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        JobApplication.belongsTo(models.Job);
        JobApplication.belongsTo(models.Recruit);
        JobApplication.hasOne(models.BoardOrder);
      }
    },
    hooks: {
      afterCreate: function(jobApplication, options, next) {
        jobApplication.createBoardOrder({
          JobId: jobApplication.JobId,
          order: 99,
          status: jobApplication.status
        });

        next();
      },
      afterUpdate: function(jobApplication, options, next) {
        console.log('APACHE HELICOPTER');

        next();
      }
    }
  });
  return JobApplication;
};
```

update:

```
db.JobApplication.update(
  {
    status: 'fooStatus'
  },
  {
    where: {
      id: req.params.id
    }
  }
);
```

I never get to the 'Apache Helicopter'...

**Comment by janmeier** [comment]
Calling update on the model is known as a bulk update, and therefore you should either add `afterBulkUpdate`, or pass `individualHooks: true` in the options. The `afterUpdate` hook is fired after calling `update` on an instance

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [Slack](http://sequelize-slack.herokuapp.com/), [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Comment by rastkojokic** [comment]
@janmeier Got it! Thanks for the super fast answer!

**Comment by hbgdPro** [comment]
@janmeier `individualHook: true` didn't help.

**Comment by janmeier** [comment]
@hbgdPro I think you dropped this `s` :)

(it `individualHooks`)

**Comment by hbgdPro** [comment]
@janmeier Sorry, that was a typo I made here, its `individualHooks` in my code. Thanks for super fast answer.

**Comment by hardikverma24** [comment]
@janmeier Thank you so much for your answer. It just solved my issue.

**Comment by himanshugogroup** [comment]
In Sequelize, the `afterBulkUpdate` hook is triggered after a bulk update operation, regardless of whether any records were actually updated. This means that the hook will execute even if the `WHERE` clause of the update query does not match any records.

### Key Points Regarding `afterBulkUpdate`

- **Execution Condition**: The `afterBulkUpdate` hook is always executed after the bulk update operation, irrespective of whether any rows were affected by the update. This is in contrast to instance-level hooks like `afterUpdate`, which only run if a specific instance was successfully updated[1][6].
  
- **Affected Rows**: To determine if any records were updated, you can check the result of the update operation. The result will typically include a count of affected rows, allowing you to infer whether any changes occurred. For example, if the affected rows count is zero, it indicates that no records matched the update criteria[1][2].

- **Using `individualHooks`**: If you need to perform operations on individual instances and want to utilize instance-level hooks like `afterUpdate`, you can set the option `individualHooks: true` during the update call. This causes Sequelize to execute separate updates for each matching record, triggering `afterUpdate` for each one[6][4].

### Example Code Snippet

Here’s an example illustrating how to use `afterBulkUpdate` and check affected rows:

```javascript
// Controller code
const [affectedCount] = await User.update(
  { lastName: 'Doe' },
  { where: { lastName: null } }
);

// Hook definition in the model
User.addHook('afterBulkUpdate', (options) => {
  console.log(`Number of affected rows: ${options[0]}`); // This will log affected count
});
```

In this example, even if no users are found with a last name of `null`, the `afterBulkUpdate` hook will still execute, allowing you to log or handle post-update logic as needed.

Citations:
[1] https://stackoverflow.com/questions/66509135/sequelize-afterbulkupdate-how-get-if-updated-or-not
[2] https://github.com/sequelize/sequelize/issues/10202
[3] https://ryansn.gitbooks.io/sequelize-docs/content/hooks.html
[4] https://sequelize.org/docs/v7/querying/update/
[5] https://sequelize.org/docs/v6/other-topics/hooks/
[6] https://github.com/sequelize/sequelize/issues/6938
