### ISSUE TITLE
benchmark not working with custom logger

### ISSUE THREAD

**Issue by OlivierCuyp** [sequelize/sequelize#6947]
Hi,

For now, if I add a custom logger while activating benchmark I don't get the benchmark time.

```js
function myLoggingFunction (message) {
  // Log in an instance of bunyan
  log.info(message);
}

{
  logging: myLoggingFunction,
  benchmark: true
}
```

I don't really understand why the benchmark time is not included in the message when not using `console.log`.

Apparently the issue comes from the following code :

 https://github.com/sequelize/sequelize/blob/afc25e3db8fa0a9a8bed3aa14869cafa1194f9fd/lib/sequelize.js#L1076

Should the test rather be :

```js
if ((this.options.benchmark || options.benchmark) && (typeof options.logging === 'function')) {
  ...
}
```

Still I can make it work if I define my myLogingFunction like this :

```js
function myLoggingFunction (message, benchmark) {
  if (!benchmark) {
    return log.info(message);
  }
  log.info(`${message} Elapsed time: ${benchmark} ms`);
};
```
I also don't really understand why the benchmark is pass as a second argument ...

**Comment by felixfbecker** [comment]
Feel free to fix

**Comment by OlivierCuyp** [comment]
Just want to understand first what's the intention when passing the benchmark as a second argument.

**Comment by felixfbecker** [comment]
Probably so your logger can handle benchmark results in a custom way, differently than SQL logs?

**Comment by janmeier** [comment]
This is intentional - Suppose for example that you want to trace slow queries, and only log those that take more than xx milliseconds. If the timing was embedded into a string, you would have to split and parse that string to get the number
