### ISSUE TITLE
Order by aggregate field issues

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6949]
##  i want order by 'count' and get it in resualt,it's a aggregate field,code as below:
```js
table1.findAll({
  include: [{
    model:table2 ,
    attributes: [
      [db.sequelize.fn('COUNT', db.sequelize.col('table2.id')), 'count']
    ],
    duplicating: false,
    required: false
  }],
  group: ['table1.id'],
  order: [['count', 'ASC']]
})
```

## What do you expect to happen?
 i want order by count and get it in resualt

## What is actually happening?
1. sequelize auto add prefix('table1.') to aggregate field.
`select sum(table2.id) as count from table1 LEFT OUTER JOIN table2 on table1.id=table2.t1id order by table1.count`
2. 'count' not in resualt

__Dialect:__ sqlite
__Database version:__ 3
__Sequelize version:__ 3.24.5

**Comment by janmeier** [comment]
```js
return table1.findAll({
      attributes: {
        include: [
          [sequelize.fn('COUNT', sequelize.col('table2s.id')), 'count']
        ]
      },
      include: [{
        attributes: [],
        model:table2,
        duplicating: false,
        required: false
      }],
      group: ['table1.id'],
      order: [['count', 'ASC']]
    });
```
Since you don't need any attributes from table2, set attributes to `[]`, and move the count to top level attributes

**Comment by mattfysh** [comment]
@janmeier - how might this work if we are including attributes from other tables? thanks :)

**Comment by mattfysh** [comment]
Using `order: sequelize.literal('count ASC')` as a workaround

**Comment by knoid** [comment]
Is this still valid? I'm getting a `SQLITE_ERROR: no such column: table1.count`.

**Comment by lpedromachado** [comment]
I'm having a problem similar to this, but I'm getting this error if `attributes` option in table2 is not set to `[]`:
```
column "table2.id" must appear in the GROUP BY clause or be used in an aggregate function
```
But I'm using "table2.id" in the aggregate function! I really don't understand this error.

If I use the @keyiis's version, I get this error! If I use @janmeier's, I can't add attributes to table2 without getting the error. What can I do?

I'm using PostgreSQL version 11.1 and Sequelize version 4.42.0 .

**Comment by lpedromachado** [comment]
Also, I get this error when I add `order: [["count", "DESC"]]`:
```
column table1.count does not exist
```

**Comment by RikieriSartor** [comment]
It happens because Sequelize try use table name before field, doing something like `order by TableName.ColumnName DESC` but this field really doesn't existis at the table. You can "fix" it by using `sequelize.literal` to take control of this SQL instruction.

**Comment by hpallantla** [comment]
> Using `order: sequelize.literal('count ASC')` as a workaround

Thanks boss
