### ISSUE TITLE
Can findAll() directly get plain objects?

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6950]
## I used findall get data from database,the modelA has a DATE type field
modelA
```js
{
  date:{type:Sequelize.DATE,field:'fdate'},
}
```
findall
`modelA.findAll({raw:true}).then(rst=>console.log)`

## What do you expect to happen?
i want get plain objects and the  'date' field is DATE type.

## What is actually happening?
but sequelize convert the 'date' field to string, there any way get plain object through 'QueryOptions' ,not fetch resualt use instanse.get({plain:true})?

__Dialect:__  sqlite
__Database version:__ 3
__Sequelize version:__ 3.24.5

**Comment by sushantdhiman** [comment]
Have you read the documentations @keyiis ??

You need the `{ plain: true }` options in `findAll`. With `{ raw: true }` we just pass what `db` client has returned.

**Comment by keyiis** [comment]
@sushantdhiman Are you sure { plain: true } can add into options  for findAll()?i havn't find about you say in [documentations ](http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance) and i has tried model.findAll({ plain: true } ),it's not work.

**Comment by sushantdhiman** [comment]
Can you show me sample of output you expect ?

**Comment by keyiis** [comment]
@sushantdhiman i expect findAll can get resualt as below:
```
[
{id:1,name:'aaa'},
{id:2,name:'bbb'},
...
]
```

**Comment by keyiis** [comment]
@sushantdhiman findAllOptions can achieve this objective?

**Comment by sushantdhiman** [comment]
This is not supported, but you could do a `map` pretty easily over the raw Date strings you received from database using `{raw: true}`

**Comment by enxtur** [comment]
This is what i need. Whenever will it support on findAll.

**Comment by DiegoRBaquero** [comment]
This should be a feature

**Comment by smithaitufe** [comment]
I desperately need this 

I want ids to be just array of values like `ids = [2,4,13,67,89,90,...]`

How can I achieve that? I have tried the query below but it not working

```js

let ids = await db.ResellerRoyaltyPurchase.findAll({
                attributes: ["id"],
                include: [
                    {
                        model: db.UserRoyaltyPurchase,
                        attributes: [],
                        required: true,                    
                    }
                ],
                group: ["ResellerRoyaltyPurchase.id"],
                having: db.sequelize.where(db.sequelize.fn("SUM", db.sequelize.col("UserRoyaltyPurchases.points")), availableWhereCond)
            }, { raw: true, mapToModel: false })
```

**Comment by alnorris** [comment]
Only way I've seen so far that actually returns plain array of results is this...

```
const users = await db.users.findAll({}).map(el => el.get({ plain: true }))
```

**Comment by amritms** [comment]
In my case I wanted only array of names. for that i did

`const users = await db.users.findAll({}).map(el => el.get('name'))`

**Comment by itsTeknas** [comment]
We should consider this as a query option.

**Comment by shmilyoo** [comment]
if I must query thousands of rows together, an extra map may cause some performance issue.

**Comment by frct1** [comment]
Hey
In case if you reading it after long time:
There is option like
```ts
{
  raw: true,
  nest: true 
}
```

**Comment by L-U-C-K-Y** [comment]
> Hey
> In case if you reading it after long time:
> There is option like
> 
> ```ts
> {
>   raw: true,
>   nest: true 
> }
> ```

Thanks for your answer!

Is nest missing from the docs, I'm not able to find it here:

https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findAll

**Comment by frct1** [comment]
> > Hey
> > In case if you reading it after long time:
> > There is option like
> > ```ts
> > {
> >   raw: true,
> >   nest: true 
> > }
> > ```
> 
> Thanks for your answer!
> 
> Is nest missing from the docs, I'm not able to find it here:
> 
> https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findAll

idk man, sequelize is kinda buggy in places

**Comment by garymcm** [comment]
> Hey
> In case if you reading it after long time:
> There is option like
> 
> ```ts
> {
>   raw: true,
>   nest: true 
> }
> ```

This converts booleans (TINYINT(1)) to 1s and 0s, whereas { plain: true } converts them to primitive values. This caused a problem for me recently, believe it or not.

**Comment by muhammad-bin-zafar** [comment]
> Hey In case if you reading it after long time: There is option like
> 
> ```ts
> {
>   raw: true,
>   nest: true 
> }
> ```

Does it work with associations?

**Comment by gustavos00** [comment]
> > Hey In case if you reading it after long time: There is option like
> > ```ts
> > {
> >   raw: true,
> >   nest: true 
> > }
> > ```
> 
> Does it work with associations?

Yes, at least should be... I'm where with this problem (`raw: true, nest: true`) and the response continues having dataValues property

**Comment by falaxfala** [comment]
I've got a problem with that. `{raw: true, nest: true}` just cuts content from associations and changes arrays into object with only one field. Without `raw: true` there is an array with many of them. Any suggestions?

**Comment by yisibl** [comment]
Thanks to @alnorris for the answer. 

```js
const users = await db.users.findAll({}).map(el => el.get({ plain: true }))
```

We can also use the ergonomically better `toJSON()`.

```js
const users = await db.users.findAll({}).map(el => el.toJSON())
```

https://github.com/sequelize/sequelize/blob/bc35a52af967dd49bbc5969450d4d80ad2926d84/packages/core/src/model.js#L4190-L4196
