### ISSUE TITLE
wrong code generation for distinct count in sql

### ISSUE THREAD

**Issue by PinkaminaDianePie** [sequelize/sequelize#6953]
```
MyModel.findAndCountAll({
    distinct: true
})
```
generates wrong sql output:
```
SELECT count(DISTINCT(*)) AS `count` FROM `MyModel`
```
which throws error in MySQL:
```ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*)) AS `count` FROM `MyModel`...```

**Comment by doovers** [comment]
This is still an issue

**Comment by Chocobozzz** [comment]
Same issue here, with a default scope that already defines includes.

A workaround is to add directly the include in the query.

**Comment by dsbert** [comment]
This is still a problem... Also impacts MSSQL

**Comment by erkmene** [comment]
Still an issue impacting MySQL with included hasMany relations.

**Comment by dsbert** [comment]
When doing a .count(), you can use options.col #6114

**Comment by erkmene** [comment]
@dsbert you are correct. The documentation is up to date on this too.

**Comment by TimMensch** [comment]
You _can't_ use `options.col` if your code is generated by an ORM like Feathers-Sequelize.

Sequelize is _generating incorrect code here_. This should be fixed! At least re-open the bug!
