### ISSUE TITLE
find using model association 

### ISSUE THREAD

**Issue by shivshankar3578** [sequelize/sequelize#6955]
Dialect: postgres
Database version: @latest
Sequelize version: @latest
Hello,
I'm trying to find using associate model .I've 3 model  post, PostCity and region. they have following relation
_postCity (post_id, region_id) associate to post (post_id) and region (region_id)_
i am using search function as
```models.post.findAll({
   include: [
     {
       model: models.postCity,
       include:[{model:models.region}],
       attributes: [[models.sequelize.fn('count', 'post_id'), 'count']],
     }
     ],
     where: {
     $or: [
         {
             "create_by" : {$not: 67}
         },
         {
        //   "postCities.region_name":{$iLike: "%Guangazhou2%"}
         },
         {
           "description":{$iLike: "%India%"}
         }
       ]
     }
```
this generate follwoing query 
```SELECT "post"."post_id", "post"."description", "post"."create_by", "post"."create_time", "post"."update_time", "post"."country_id", "postCities"."post_id" AS "postCities.post_id", "postCities"."region_id" AS "postCities.region_id", "postCities"."order_no" AS "postCities.order_no", "postCities.region"."region_id" AS "postCities.region.region_id", "postCities.region"."region_name" AS "postCities.region.region_name", "postCities.region"."country_id" AS "postCities.region.country_id", "postCities.region"."province_id" AS "postCities.region.province_id" FROM "t_post" AS "post" LEFT OUTER JOIN "t_post_city" AS "postCities" ON "post"."post_id" = "postCities"."post_id" LEFT OUTER JOIN "t_region" AS "postCities.region" ON "postCities"."region_id" = "postCities.region"."region_id" WHERE ("post"."create_by" != 67 OR "post"."description" ILIKE '%India%')```
when i comment out  _"postCities.region_name":{$iLike: "%Guangazhou2%"}_ then this show _error    **column post.postCities.region_name does not exist**
I simply like to my query as **.... WHERE ("post"."create_by" != 67 OR "post"."description" ILIKE '%India%'  OR "postCities.region_name" ILIKE: "%Guangazhou2%")**
**Update**
I also use include:[{model:models.region, where:{"region_name":{$iLike: "%Guangazhou2%"}}}] but this  doesn't give me appropriate result.

please help me

**Comment by janmeier** [comment]
```js
  {
   "$postCities.region_name$": {$iLike: "%Guangazhou2%"}
}
```

**Comment by shivshankar3578** [comment]
thanks janmeier to save me. I've also issue while count post_id in same issue similar   #3417 .
 when i use  **attributes: [[models.sequelize.fn('count', 'post_id'), 'count']]**, then it show error "postCities.post_id" in aggregate function.

**Comment by janmeier** [comment]
Well, does postCities have a city id? What is the main table? Do you have that attribute on the include of or the main options object? What are the relations between them? What is the full SQL?

It is incredibly hard to debug anything without knowing what your setup looks like

**Comment by shivshankar3578** [comment]
post, PostCity and region. they have following relation
**postCity (post_id, region_id) associate to post (post_id) and region (region_id)** 
where postCity have primary key (post_id, region_id), post (post_id)  hasMany postCity (post_id) and postCity (region_id) belongsTo region (region_id)

**Comment by shivshankar3578** [comment]
also when i use   group: ["postCities.region.region_id", ""postCities.region_id"", " "post.post_id""] then count  always  1.

**Comment by janmeier** [comment]
Please look into creating an [SSCCE](HTTP://SSCCE.ORG/) - Its really hard to imagine your setup from a textual description
