### ISSUE TITLE
Add Flow type annotations to the project

### ISSUE THREAD

**Issue by excitement-engineer** [sequelize/sequelize#6957]
Many popular javascript libraries are adopting Flow for better type safety in their code. Are there any plans to bring Flow type annotations to sequelize?

**Comment by felixfbecker** [comment]
There are no plans for using Flow. We considered TypeScript in the past, but decided against it. You can find well-maintained TypeScript definitions here: https://github.com/types/npm-sequelize
I don't know if there is something similar for Flow.
I also don't know any big popular library really that is using Flow, only many TypeScript ones. It seems a lot more popular to me: https://www.google.de/trends/explore?q=flow%20type,typescript

**Comment by toddw** [comment]
React is a big popular library that uses Flow. It is gaining a lot of popularity. Thanks for posting the typscript definitions, shouldn't be too difficult to translate them and contribute to [flow-typed](https://github.com/flowtype/flow-typed)

**Comment by zuhair-naqvi** [comment]
+1

**Comment by doganmurat** [comment]
+1

**Comment by jedwards1211** [comment]
Sequelize is very dynamic.  Not only do relations define methods on models that can only be typed manually with flow, any relations and fields can be aliased to different names in query results, hence I think there might wind up being disagreement about how to type certain features, and flow types would be best left to 3rd-party libraries (or code generators!) outside of `flow-typed`.

**Comment by jedwards1211** [comment]
but @felixfbecker do consider that since Facebook uses flow internally it will gain a lot of popularity through their influence on open source.
