### ISSUE TITLE
afterBulkCreate hook missing primary key in instances

### ISSUE THREAD

**Issue by CodestarGames** [sequelize/sequelize#6965]
## What you are doing?
after doing a bulk create, the afterBulkCreate function fires, but all the instances don't have a primary key, they are all null.

## What do you expect to happen?
I wanted the instances to have the primary keys already inserted, in the postgres database they are inserted.

## What is actually happening?
They are null

__Dialect:__ postgres 
__Database version:__ 9.5
__Sequelize version:__ 3.25.0

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/6475
