### ISSUE TITLE
SQLITE query date type issues

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6968]
## What you are doing?
I used raw query with sqlite3

```js
let date = new Date();
sequelize.query('SELECT * FROM projects WHERE date >= :startDate',
  { replacements: {startDate:date}, type: sequelize.QueryTypes.SELECT }
).then(function(rst) {
  console.log(rst)
})
```

## What do you expect to happen?
_I wanted get correct date format
`WHERE date >= '2016-12-09 15:06:24.086 +00:00';`
or
`WHERE date >= '2016-12-09 07:06:24.086 +08:00';`

## What is actually happening?
sequelize generate sql
`WHERE date >= '2016-12-09 15:06:24.086 +08:00';`

__Dialect:__ sqlite
__Database version:__ 3
__Sequelize version:__ 3.24.5

**Comment by janmeier** [comment]
What is date? A string ? A date object?

**Comment by keyiis** [comment]
@janmeier date is Date object.
i find a temporary solution,use Moment.js
```
let date = new Date();
let dateStr = Moment.utc(date).format('YYYY-MM-DD HH:mm:ss.SSS Z');
sequelize.query('SELECT * FROM projects WHERE date >= :startDate',
  { replacements: {startDate:dateStr}, type: sequelize.QueryTypes.SELECT }
).then(function(rst) {
  console.log(rst)
})
```
so the issues is sequelize.query will not convert localtime to utc time automatically,but sqlite only access utc time.

**Comment by janmeier** [comment]
I know this might just be a simple example, but what you are doing can easily be expressed with sequelize

```js
Projects.findAll({
  where: {
    date: {
      $gte: startDate
    }
  }
});
```

Which will handle the date correctly. Nevertheless, this is a valid bug

**Comment by keyiis** [comment]
@janmeier Here is a simple example,i need excute complex query,if use findAll that will has many include and complex relations,so i think raw query is best chioce,thank's reply!
