### ISSUE TITLE
Can't delete corrupted DB file and create new one

### ISSUE THREAD

**Issue by Pecyn** [sequelize/sequelize#6969]
## What you are doing?
Syncing model to the DB. If the DB file already exists but it is corrupted for some reason then sync returns rejected Promise (e.g. SequelizeDatabaseError: SQLITE_CORRUPT: database disk image is malformed)
I need to handle the situation - create a new empty DB. So I tried to delete the file and call sync again.
```js
// code is simplified a little bit
function init(models) {
    models = models || modelsModule
    return new Promise((resolve, reject) => {
        models.sequelize.sync()
        .then(() => {
          resolve()
        })
        .catch(() => {
          _deleteFile(file)
          models.sequelize.sync()
            .then(() => {
              resolve()
            })
            .catch((err) => {
              reject(err)
            })
        })
    })
}
```

## What do you expect to happen?
The file is deleted and new db file is created 

## What is actually happening?
The file can't be deleted because it is still in use (Error: EBUSY: resource busy or locked). I suppose it is still being used by some sequelize process and I need the file to be released. I tried sequelize.close() but it did not help.

Or is there other - recommended way how to handle this case?

__Dialect:__ sqlite
__Database version:__ SQLite 3
__Sequelize version:__ 3.27.0

**Comment by sushantdhiman** [comment]
Related https://github.com/sequelize/sequelize/issues/6798

**Comment by felixfbecker** [comment]
Just wanted to say your code can be simplified:
```ts
// code is simplified a little bit
function init(models) {
    models = models || modelsModule
    return models.sequelize.sync().catch(() => {
       _deleteFile(file)
       return models.sequelize.sync()
    })
}
