### ISSUE TITLE
Feature: make association methods update foreign keys

### ISSUE THREAD

**Issue by JD-Robbs** [sequelize/sequelize#6973]
I wonder if methods such as `addAssocModel` and `setAssocModel` should automatically update the passed entity's respective foreign key fields.

        let company = await Company.create(accountData.company);
        let user = await User.create(accountData.user);

        let freshCompany = await company.setUsers([user]);
        // At this point, I would have expected `user.companyId` to have been populated with `company.id`

Sure, I could just use `company.id`, but I think it would be nice if any updates were fully reflected in the entity objects that are hanging around - useful when these are passed around (e.g. in events) and one assumes they're at the latest state where they actually aren't.

Also likely that this is absolutely intended by design - in that case, I'll close. 😄

**Comment by sushantdhiman** [comment]
You could do `reload`, but I think it will be good feature to have

**Comment by JD-Robbs** [comment]
Yes, that's definitely a nice solution - albeit that would fire another `SELECT`.  The benefit of doing it automatically could be that, if the `setX` and `addX` methods don't throw any exceptions, the foreign key fields could be populated without executing any additional queries.

**Comment by JD-Robbs** [comment]
I think that this might still make a nice feature.
