### ISSUE TITLE
[Feature Request] Doc: update return result of `update` method

### ISSUE THREAD

**Issue by bigopon** [sequelize/sequelize#6974]
I'm having a bit of trouble adjusting to fit with result of method `update` from sequelize. Currently I cannot find any clear doc for this. Something like this would indeed help:

* update called from model: return array of row affected ?
* update called from instance: return instance itself

**Comment by sushantdhiman** [comment]
> update called from model: return array of row affected ?

http://docs.sequelizejs.com/en/v3/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

> update called from instance: return instance itself

http://docs.sequelizejs.com/en/v3/api/instance/#updateupdates-options-promisethis

**Comment by bigopon** [comment]
Ok so it was my bad. But Would be really nice if there were few more words indicating this. For me, a normal user, would staying in document section all the time instead of API (to look for guide) and find it quite confusing. Or maybe put a link to API for a reminder ?
