### ISSUE TITLE
sequelize initialization issues

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6975]
## I used sequelize with sqlite3, i want listening sequelize created all table event 
**sequelizeUtil.ts**
```js
export class sequelizeUtil{
   private sequelize: Sequelize.Sequelize;
   public User : Sequelize.Model;
   constructor() {
        this.sequelize= new Sequelize(cfg.conn.database, cfg.conn.username, cfg.conn.password, cfg.conn.options);
        this.User = this.sequelize.define('user', {
              firstName: {
                 type: Sequelize.STRING,field: 'first_name'
              },
              lastName: {
                 type: Sequelize.STRING
              }
         });
         this.sequelize.sync();
   }
}
```
**userService.ts**
```
class userService{
     private util;   
     constructor() {
            this.util = new sequelizeUtil();
     }
     findUser(){
           this.util.User.find().then(console.log).catch(console.log);
     }
}

```
## What do you expect to happen?
when i first run program,will console:
```
"SQLITE_ERROR: no such table: user"
name:"SequelizeDatabaseError"
original:Error: SQLITE_ERROR: no such table: user at Error (native)
parent:Error: SQLITE_ERROR: no such table: user at Error (native)
```
but when i  run program  a Second time,all work fine.
so i think,Sequelize create table is asynchronous,how can i detact all table created?

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ sqlite 
__Database version:__ sqlite3
__Sequelize version:__ 3.25.4

**Comment by felixfbecker** [comment]
```ts
sequelize.sync().then(() => {
 // all tables created
})
async function whatever() {
  await sequelize.sync()
  // all tables created
}
```

**Comment by keyiis** [comment]
@felixfbecker thanks reply!i used es5,so not support async/await.
if i call sequelize.sync() in every CRUD method can cause sequelize.sync() to repeatedly execute?
 example: i need insert admin account after first start app.
```
sequelize.sync().then(() => {
  sequelize,query("insert into user values(1,'admin','admin')").then();
})
function find() {
  call sequelize.sync() again?
}
function update() {
  call sequelize.sync() again?
}
function save() {
  call sequelize.sync() again?
}
```

**Comment by felixfbecker** [comment]
I don't get your question exactly, but you should not sync before every CRUD operation. Please ask general questions on Slack or StackOverflow.

**Comment by keyiis** [comment]
@felixfbecker i update sequelize4, now i want execute some sql after specify table first created,so how can i catch the "first created" event?
