### ISSUE TITLE
custom getters/virtual attributes are always placed on the top in the resulting JSON

### ISSUE THREAD

**Issue by rdhanasekar** [sequelize/sequelize#6976]
## What you are doing?

```js
	var Sequelize = require('sequelize');
	var sequelize = new Sequelize('demo', 'root', '', {
	    host: 'localhost',
	    dialect: 'mysql',
	    pool: {
	        max: 5,
	        min: 0,
	        idle: 10000
	    },
	});
	sequelize
	    .authenticate()
	    .then(function(err) {
	        console.log('Connection has been established successfully.');
	    })
	    .catch(function(err) {
	        console.log('Unable to connect to the database:', err);
	    });


	var User = sequelize.define('user', {
	    firstName: Sequelize.STRING,
	    lastName: Sequelize.STRING,
	    age: {
	        type: Sequelize.STRING,
	        get: function() {
	            return Number(this.getDataValue('age'));
	        }
	    },
	    gender: Sequelize.STRING
	}, {
	    getterMethods: {
	        fullName: function() {
	            return this.firstName + ' ' + this.lastName;
	        }
	    }
	});

	User.sync({ force: true }).then(function() {
	    User.create({
	        firstName: 'John',
	        lastName: 'Hancock',
	        age: '25',
	        gender: 'Male'
	    }).then(function() {
	        User.findAll().then(function(users) {
	            console.log(JSON.stringify(users));
	        })
	    });
	});
```

## What do you expect to happen?

[
  {
    "id": 1,
    "firstName": "John",
    "lastName": "Hancock",
    "age": 25,
    "gender": "Male",
    "createdAt": "2016-12-11T11:33:53.000Z",
    "updatedAt": "2016-12-11T11:33:53.000Z",
    "fullName": "John Hancock"
  }
]

## What is actually happening?
[
  {
    "fullName": "John Hancock",
    "age": 25,
    "id": 1,
    "firstName": "John",
    "lastName": "Hancock",
    "gender": "Male",
    "createdAt": "2016-12-11T11:33:53.000Z",
    "updatedAt": "2016-12-11T11:33:53.000Z"
  }
]

Dialect:  any
Database version: any
Sequelize version: any

[Stackoverflow link : ](http://stackoverflow.com/questions/41085742/sequelize-custom-getters-virtual-attributes-are-always-placed-on-the-top-in-th)

**Comment by felixfbecker** [comment]
And what is the problem with this? You should never rely on property order in objects

**Comment by rdhanasekar** [comment]
I have a dynamic ui which relies on the order of this object. So i expect it be in the same order as in its definition. Why does sequelize alter the order?

**Comment by felixfbecker** [comment]
Sequelize does not "alter" the order. The order of properties is never guaranteed in any JS runtime. In V8, it is the order of assignment, and we simply assign the getters first. Your code should never rely on that.

**Comment by rdhanasekar** [comment]
Thanks and i agree with your point. And as you said In V8 it is the order of the assignment and nodejs is based on the V8 engine. So i completely rely on the order. And i was able to fix this issue with just a code swap in sequelize.

**Comment by aman-verma-Ta** [comment]
> Thanks and i agree with your point. And as you said In V8 it is the order of the assignment and nodejs is based on the V8 engine. So i completely rely on the order. And i was able to fix this issue with just a code swap in sequelize.

I am facing the same issue how did you fix this?
