### ISSUE TITLE
Model update not return affectedRows

### ISSUE THREAD

**Issue by rohmanhm** [sequelize/sequelize#6977]
_Thanks for wanting to report an issue you've found in Sequelize. Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_Note that it will be much easier for us to fix the issue if a test case that reproduces the problem is provided. Ideally this test case should not have any external dependencies. We understand that it is not always possible to reduce your code to a small test case, but we would appreciate to have as much data as possible. Thank you!_

_Github should only be used for feature requests and bugs - all questions belong on StackOverflow, Slack, or Google groups._

_This template is for submitting issues - if you want to submit a feature request you may skip this template_

## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_

```js
Db.models.persons.update( args.value, {
  where: args.where
}).then((result) => {
  console.log(result);
  return result;
})
```

## What do you expect to happen?
_I wanted it's console and return the result (affectedRows)_

## What is actually happening?
_But in my console not show anything_

_Output, nothing_

__Dialect:__ mysql
__Database version:__ XXX
__Sequelize version:__ 3.27.0

**Comment by sushantdhiman** [comment]
I doubt thats a problem with `Sequelize`, it seems something wrong with your setup. If there was any error it should have been on terminal.

Could you check if `console.log` isn't overrided in your code somewhere?

**Comment by rohmanhm** [comment]
I tried, and show `affectedCount` but `affectedRows`  `undefined`

This is message from my console
`[ 1 ] undefined`

Here my code
```
updatePerson: {
  type: Person,
  args: {
    value: {
      type: UpdatePersonInputType
    },
    where: {
      type: WhereUpdatePersonInputType
    }
  },
  resolve(_, args) {
    return Db.models.persons.update( args.value, {
      where: args.where
    }).then((result, affect) => {
      console.log(result, affect);
    });
  }
},
```

**Comment by sushantdhiman** [comment]
Pretty sure you need `spread` rather than `then` http://docs.sequelizejs.com/en/v3/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

You will find `affectedRows` in second index

**Comment by rohmanhm** [comment]
Like this?

```
updatePerson: {
  type: Person,
  args: {
    value: {
      type: UpdatePersonInputType
    },
    where: {
      type: WhereUpdatePersonInputType
    }
  },
  resolve(_, args) {
    return Db.models.persons.update( args.value, {
      where: args.where
    }).then((...dargs) => {
      console.log(dargs);
    });
  }
},
```

this is the result from my console
```
Executing (default): UPDATE `persons` SET `firstName`='john',`email`='doe@john.com',`updatedAt`='2016-12-12 08:11:02' WHERE `id` = '1'
[ [ 1 ] ]
```

still just show `[ [ 1 ] ]`

**Comment by rohmanhm** [comment]
I'm sorry I forgot something.
in this case, I using `mysql`

**Comment by janmeier** [comment]
> , while the second element is the actual affected rows (only supported in postgres with options.returning true.)

http://docs.sequelizejs.com/en/v3/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

**Comment by sushantdhiman** [comment]
@rohmanhm I was talking about [bluebird's spread](http://bluebirdjs.com/docs/api/spread.html)

**Comment by anabaei** [comment]
you need to add  `returning:true` to your query to get all results. In your case you code would be like 
```javascript
Db.models.persons.update( args.value, {
  where: args.where,
  returning: true
}).then((result) => {
  console.log(result);
  return result;
})
```

**Comment by rohmanhm** [comment]
@anabaei I did, but it won't work if you're using `mysql`

**Comment by DICOT4** [comment]
I'm still facing this issue. Using `returning: true` seems to be not working with `mysql`.
```
const response = await User.update(data, {
    where: {id: id},
    returning: true
});
return res.send({
    data: response
});
```
Here's the output
```
data: [null, 1]
```

**Comment by DICOT4** [comment]
I'm still facing this issue. Using `returning: true` seems to be not working with `mysql`.
```node
const response = await User.update(data, {
    where: {id: id},
    returning: true
});
return res.send({
    data: response
});
```
Here's the output
```json
data: [null, 1]
```

**Comment by yogithesymbian** [comment]
> ```js
> returning: true
> ```

so how ? did you have solve ?
