### ISSUE TITLE
not null violation error on defining setter model

### ISSUE THREAD

**Issue by Nosthertus** [sequelize/sequelize#6978]
Greetings.

I am trying to run a hashing function for the password when the password property is set on the model (generated from `sequelize-auto`) and provided on row creation, the code looks like this:

```js
var bcrypt = require("bcrypt");

const saltRounds = 8;

module.exports = function(sequelize, DataTypes) {
	return sequelize.define('accounts', {
		.....
		password: {
			type: DataTypes.STRING,
			allowNull: false,
			set: function(password){
				var self = this;

				bcrypt.hash(password, saltRounds)
					.then(function(hash){
						self.setDataValue("password", hash);
					})
					.catch(function(error){
						console.error(error);
					});
			}
		},
		......
	}, {
		tableName: 'accounts',
		timestamps: false
	});
};
```

i define this function on the model so i could just call it from wherever i need it and call the hashing function just before the record is created and then save the record with the hashed password.

But, `sequelize` throws an error saying:

``
notNull Violation: password cannot be null
``

This only happens when i execute `setDataValue` in another nested function. i actually have no idea why it happens

__Dialect:__ mysql 
__Database version:__ 5.6.31-0ubuntu0.15.10.1
__Sequelize version:__ 3.27.0

**Comment by janmeier** [comment]
Setters cannot be async (https://github.com/sequelize/sequelize/search?q=async+setter&type=Issues&utf8=%E2%9C%93) - The problem is that the instance is saved before the promise is resolved.

If you need to do async stuff, use a hook instead (and remember to return the promise)
