### ISSUE TITLE
findById doesn't accept where clause

### ISSUE THREAD

**Issue by Alexis-benoist** [sequelize/sequelize#6979]
## What you are doing?

I want to do a query using the helper findById with a where clause. It's overidden on this [line](https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/model.js#L1456).

## What do you expect to happen?
I expect the where clause to be taken into account. If I do a where inside a include, it's taken into account.
 

## What is actually happening?
But it wasn't taken into accoutn.

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Database version:postgres 9.5
__Sequelize version: 3.10.9

**Comment by felixfbecker** [comment]
This is expected behavior. `options.where` is not documented for `findById`. Use `findOne`.

**Comment by Alexis-benoist** [comment]
Though the include works and is undocumented.

**Comment by felixfbecker** [comment]
It's pretty clear that `findById()` is for finding an item by its ID. It is a shorthand for `findOne` with a `where` on the ID. If you need a custom `where` query you should use `findOne()`
