### ISSUE TITLE
Upsert doesn't respects createdAt and updatedAt renamed fields 

### ISSUE THREAD

**Issue by wmangelardo** [sequelize/sequelize#6981]
## What you are doing?
I am trying to execute a upsert with a model that renamed createdAt and updatedAt fields.

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize(config.database, config.username, config.password, config);
const test = sequelize.define('test', {
  testId: {type: Sequelize.INTEGER, allowNull: false, field: 'test_id'},
  wserial: {type: Sequelize.BIGINT, allowNull: false},
  status: {type: Sequelize.TEXT},
  createdAt: {type: Sequelize.DATE, field: 'created_at'},
  updatedAt: {type: Sequelize.DATE, field: 'updated_at'}
});
test.sync().then(function () {
  // Create works properly, changing createdAt and updatedAt to created_at and updated_at.
  test.create({
    testId: 1,
    wserial: 123456,
    status: 'DELIVERED'
  }).then(function () {
    // I was expecting that upsert works as well
    test.upsert({
      testId: 2,
      wserial: 456789,
      status: 'REFUSED'
    }).then(function () {
      console.log('Expected')
    }).catch(function (err) {
      // but upsert not respects field option to createdAt and updatedAt like create does 
      console.error(err);
    });
  });
});
```

## What do you expect to happen?
I was expecting upsert generate SQL with fields createdAt and updatedAt renamed like happens in create method.

## What is actually happening?
I am getting the following exception: SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'.

Maybe this issue, if is really a new one, is related with #2946 issue.

#### Test case Output

Executing (default): CREATE TABLE IF NOT EXISTS `tests` (`id` INTEGER NOT NULL auto_increment , `test_id` INTEGER NOT NULL, `wserial` BIGINT NOT NULL, `status` TEXT, `created_at` DATETIME, `updated_at` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `tests`
Executing (default): INSERT INTO `tests` (`id`,`test_id`,`wserial`,`status`,`created_at`,`updated_at`) VALUES (DEFAULT,1,123456,'DELIVERED','2016-12-13 15:00:35','2016-12-13 15:00:35');
Executing (default): INSERT INTO `tests` (`test_id`,`wserial`,`status`,`createdAt`,`updatedAt`) VALUES (2,456789,'REFUSED','2016-12-13 15:00:35','2016-12-13 15:00:35') ON DUPLICATE KEY UPDATE `test_id`=VALUES(`test_id`), `wserial`=VALUES(`wserial`), `status`=VALUES(`status`), `updatedAt`=VALUES(`updatedAt`);
SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'

__Dialect:__ mysql
__Database version:__ 5.6.34
__Sequelize version:__ 3.27.0

Thanks in advance

**Comment by sushantdhiman** [comment]
Probably fixed in `master`, need to confirm

**Comment by naseem-qadium** [comment]
I am still having this issue for Sequelize V4.28.6
