### ISSUE TITLE
sum a column value and update

### ISSUE THREAD

**Issue by nasr18** [sequelize/sequelize#6984]
Is there any option to update a column by `summing` with previous value, instead of `finding, incrementing and then updating`?

**Comment by sushantdhiman** [comment]
[Model.sum](http://docs.sequelizejs.com/en/v3/api/model/#sumfield-options-promisenumber) (simple cases)
[Model.aggregate](http://docs.sequelizejs.com/en/v3/api/model/#aggregatefield-aggregatefunction-options-promiseoptionsdatatypeobject) (advance cases)

**Comment by sushantdhiman** [comment]
Yeah it doesn't update

**Comment by nasr18** [comment]
`aggregate` & `sum` returning only the value. but not an updated value. Thanks for adding this feature.

**Comment by micrub** [comment]
+1
