### ISSUE TITLE
$or condition between 2 included relations

### ISSUE THREAD

**Issue by pawelhertman** [sequelize/sequelize#6987]
Hi, I'd like to know if it is possible in Sequelize to fetch items with alternative (I mean $or) condition between 2 included relations. I can't find any solution.

Example models:
```js
const options = {
    tableName: 'parent',
    classMethods: {
      associate: (models) => {
        Parent.belongsToMany(models.Child, {
          as: 'childrenOne',
          through: 'children_one',
        });
        Parent.belongsToMany(models.Child, {
          as: 'childrenTwo',
          through: 'children_two',
        });
      }
    }
  };
Parent = sequelize.define('Parent', attributes, options);
```
```js
const attributes = {
    id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    name: DataTypes.STRING,
  };
Child = sequelize.define('Child', attributes, options);
```

In this situation I want to fetch all Parents, which contain Child with "x" id in "childrenOne" relation **OR** "childrenTwo" relation. So sth like
```js
Parent.findAll({
  where: {
    $or: [
      {'childrenOne.id': x},
      {'childrenTwo.id': x}
    ]
  },
  contains: [
    {model: Child, as: 'childrenOne'},
    {model: Child, as: 'childrenTwo'},
  ]
});
```
what of course is wrong, because _where_ conditions of relations have to be in "contains" section.

**Comment by pawelhertman** [comment]
Ok, problem solved by using query almost like my "fake" one, but with relation's field wrapped with $ sign:
```js
Parent.findAll({
  where: {
    $or: [
      {'$childrenOne.id$': x},
      {'$childrenTwo.id$': x}
    ]
  },
  contains: [
    {model: Child, as: 'childrenOne'},
    {model: Child, as: 'childrenTwo'},
  ]
});
```

Solution found deep in https://github.com/sequelize/sequelize/issues/3095 - I highly recommend adding this info into documentation. Anyway, it still doesn't work with **limit**, as mentioned in #3095 over year ago.

**Comment by gauravsingla05** [comment]
this method is giving me error
`: Invalid value { notice_to_class: 'all' }`
notice_to_class is my field and "all" is matching value
