### ISSUE TITLE
Cannot modify the type/shape of instance in afterFind hook parameter

### ISSUE THREAD

**Issue by lapinskicho** [sequelize/sequelize#6988]
## What you are doing?

Using Sequelize 3.27.0

Comment is a Sequelize model.  After Comment.findAll(), I am trying to use afterFind hook to do a query on User to retrieve user data.  For simplicity, I am simply adding the data without doing a User.findAll here (to eliminate Promise as a culprit).  I am trying to change the data "shape" of comments from an array to an object of arrays (see line 3 below) in the afterFind hook.

line 1: Comment.hook('afterFind', (comments) => {
line 2:   users = [ { id: 1, name: 'Joe' }]; // to simply from User.findAll().then((users) => { ... })
line 3:   comments = { comments, users };  
line 4: };
line 5:
line 6:   Comment.findAll().then((comments) => {
line 7:     ....
line 8:   });

## What do you expect to happen?

I expected line 3 above would modify comments so that comments in line 6 is an object and will have the following data shape: { comments: [ ] , users: [ ] }

## What is actually happening?

The assignment in line 3 seems to be ignored.  comments in line 6 is still an array just as afterFind hook is never called.

So I tried different ways and eventually this works "as expected":

line 3a: comments.push(users);

With line3a, comments is still an array in line 6, but at least its last element contains an array of users object.

I could not find any documentation mention about it, but is modifying an instance of a hook parameter from an array to be an object not supported/allowed?  Or it is a bug in sequelize that the "type" of the instance cannot be modified?

Thanks!

**Comment by felixfbecker** [comment]
That's not how JS works... If you assign a parameter, it will just override it in the local scope. You can mutate the objects, but you cannot reassign, and it would also not be a good idea because it would break the interface

**Comment by lapinskicho** [comment]
Thanks for the reply.  Yes, I understand javascript parameters are pass by value, what I don't know is what Sequelize hooks do behind the scene.  

So if there are additional objects that I would want a hook (e.g. afterFind) to pass it back to the model instance, what is the best way to do it?

Or say if I want to normalize the instance data (changing the shape of the model instance), I should not use afterFind hooks to achieve it?

How are these cases usually handled in Sequelize?

**Comment by felixfbecker** [comment]
Like I said, you can mutate the object. Please ask general questions on Slack or StackOverflow.
