### ISSUE TITLE
sync({force:true}) potential bug in windows

### ISSUE THREAD

**Issue by excitement-engineer** [sequelize/sequelize#6989]
## What you are doing?
I am trying to write some tests in which I want to make use of a test database. This database gets cleared after every test using the following code: 

```js
beforeEach(async () => {
      //clear the database before each test. Make sure that the name of the database table matches test.
      await sequelize.sync({force: true, match: /test$/});
  });

  afterAll(() =>sequelize.close());
```

## What do you expect to happen?
I expect the database to be cleared before each test run. 

## What is actually happening?
This works fine on mac and linux however, on Windows I am running into an issue that the database the entities and relations between objects seem to be cleared as well. 

I am getting errors such as: 

```
SequelizeDatabaseError: relation "..." does not exist
```

Anyone knows if `sync({force: true})` does not work on windows?

__Dialect: postgres
__Database version:9.5
__Sequelize version:3.24.3

**Comment by felixfbecker** [comment]
> I am running into an issue that the database the entities and relations between objects seem to be cleared as well.

That is the expected behavior for `sync({force: true})`

**Comment by excitement-engineer** [comment]
There was an error with my test runner I just found out. It was running tests in parallel causing there to be conflicts between tests interacting with the test database.
