### ISSUE TITLE
model destroy not return affectedRows

### ISSUE THREAD

**Issue by rohmanhm** [sequelize/sequelize#6990]
Please add option to returning `affectedRows` when I destroy data with dialect `postgres`

`DELETE FROM "users" WHERE "id"=2 RETURNING *`

References: http://docs.sequelizejs.com/en/latest/api/model/#destroyoptions-promiseinteger

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 3.27.0

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/4122
