### ISSUE TITLE
Dynamic where clause in raw queries 

### ISSUE THREAD

**Issue by matt212** [sequelize/sequelize#6991]
Hi , 

Thank for awesome Orm.
I have some complex mysql queries , which i have written in raw queries .
I have query for multiple where clause like name="matt" and sex="male" in raw queries !

**Comment by felixfbecker** [comment]
Cool, so what is the issue?

**Comment by matt212** [comment]
currently i am using string manipulation for passing value for multiple where clause 
eg:-
if(selector=="")
{
              selector=searchkey+'= $like%' + searchvalue + '%';
}
else
{
              selector=selector+" "+searchkey+'= $like%' + searchvalue + '%';
}
wherein searchkey is columname and searchvalue  is fieldvalue
select * from tablname where  [selector]

**Comment by felixfbecker** [comment]
The way you do it will expose you to SQL injection. Please see the docs for raw queries with replacements or simply use a `find()`. Please ask general questions on Slack or StackOverflow

**Comment by matt212** [comment]
Hi 
Agree with replacement i am unable to find any doc for "multiple where clause" on stack or doc and i am using complex mysql query hence i cannot use find()

**Comment by matt212** [comment]
Hi 
1.updated stackoverflow with actual code let me know of your inputs
2. is there any other Orm for nodejs and mysql !
