### ISSUE TITLE
Regression: bulkCreate does not respect createdAt 'field' (created_at)

### ISSUE THREAD

**Issue by spasam** [sequelize/sequelize#6992]
See: https://github.com/sequelize/sequelize/issues/6519
I am able to reproduce it with latest sequelize version: 3.27.0

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/6219, but not released to `v4`. Feel free to back port to `v3` (as I said in linked issue #6519)

**Comment by spasam** [comment]
Oops, sorry. Thought it was fixed in v3.

**Comment by kevflynn** [comment]
Is this going to be added to a release soon?
