### ISSUE TITLE
sequelize.query in migration does not return created row

### ISSUE THREAD

**Issue by SergeyKhval** [sequelize/sequelize#6995]
```js
module.exports = {
  up: (queryInterface, Sequelize) => {
    const q = `INSERT INTO "Subscriptions" ("triggerId", "communityId", "actionId", "optionId") VALUES (1,1,1,1)`;
    const options = {type: queryInterface.sequelize.QueryTypes.INSERT};

      return queryInterface.sequelize.query(q, options)
        .then(res => {
            //do something with res
        })
  }
```

I expect that `res` contains newly created row, but it contains `[]`. If I use `.spred((res, meta) => {})` instead of 'then()' than both `res` and `meta` are undefined

__Dialect:__ postgres 
__Sequelize version:__ 3.27.0

**Comment by sushantdhiman** [comment]
`query` is just utilizing just plain connector library, it will do what you ask for. Your query doesn't specify anything about returning any data.

You might want to use `RETURNING` option https://www.postgresql.org/docs/9.5/static/sql-insert.html

**Comment by felixfbecker** [comment]
An INSERT query does not return any data unless you use `RETURNING`

**Comment by SergeyKhval** [comment]
Thank you, guys!
