### ISSUE TITLE
Foreign key allowNull constraint enforcement depends on association order

### ISSUE THREAD

**Issue by torfsen** [sequelize/sequelize#6997]
I'm using `foreignKey: {allowNull: false}` to create a mandatory foreign key. In the following code, that works correctly:
```js
'use strict'

const Sequelize = require('sequelize')

const sequelize = new Sequelize('', '', '', {
    dialect: 'sqlite',
    storage: 'test.sqlite'
})

const A = sequelize.define('A', { foo: Sequelize.STRING })
const B = sequelize.define('B', { bar: Sequelize.STRING })

A.belongsTo(B, {
    onDelete: 'CASCADE',
    foreignKey: { allowNull: false }
})
B.hasMany(A)

sequelize
    .authenticate()
    .then(() => sequelize.sync({force: true}))
    .then(() => B.create({bar: 'b'}))
    .then(() => A.create({foo: 'f'}))
```
Since the code doesn't specify `BId` in the last line an error is thrown:
```
Executing (default): INSERT INTO `Bs` (`id`,`bar`,`createdAt`,`updatedAt`) VALUES (NULL,'b','2016-12-16 18:21:06.611 +00:00','2016-12-16 18:21:06.611 +00:00');
Unhandled rejection SequelizeValidationError: notNull Violation: BId cannot be null
...
```
However, if I switch the order of the `A.belongsTo` and `B.hasMany` statements, then no error is thrown. Instead, the instance is created without setting `BId` (resulting in a null value):
```
Executing (default): INSERT INTO `Bs` (`id`,`bar`,`createdAt`,`updatedAt`) VALUES (NULL,'b','2016-12-16 18:23:56.246 +00:00','2016-12-16 18:23:56.246 +00:00');
Executing (default): INSERT INTO `As` (`id`,`foo`,`createdAt`,`updatedAt`) VALUES (NULL,'f','2016-12-16 18:23:56.417 +00:00','2016-12-16 18:23:56.417 +00:00');
```
I would have expected that the order of the `A.belongsTo` and the `B.hasMany` statements doesn't matter. In particular, I'm using the automatic assignment setup from the [express example](http://docs.sequelizejs.com/en/1.7.0/articles/express/), so I cannot really control the order of these calls.

I'm using `sqlite3` 3.1.8 and `sequelize` 3.27.0 with Node 6.3.1.

**Comment by felixfbecker** [comment]
That's because you pass the wrong options to `hasMany`. The options must match the options you pass to `belongsTo`.

**Comment by torfsen** [comment]
Ah, must have missed that. Passing the same options to `belongsTo` and `hasMany` does fix the error. Thanks for the clarification!
