### ISSUE TITLE
rename the field in hasMany

### ISSUE THREAD

**Issue by rmanrique** [sequelize/sequelize#6998]
is there an option for renaming the field for a hasMany Association. What I mean by this is say I have this, 
```javascript
classMethods: {
			associate: function(models) {
				Gym.hasMany(models.Route, {
					foreignKey: 'gym_id'
				});
			}
		}
```
I know this will add the field gym_id, to the Route model. This is correct and is the db column I need it to connect to. However, I would like it to be named gymId. So what it would do is something like SELECT gym_id as gymId from route. I like to have my databases in snake case, but deal with it in code with camel case. I know you can do that on a normal field by doing,
```javascript
routeType: {
			type: DataTypes.STRING,
			field: 'route_type'
		}
```
so I was wondering if there is a way to do it on the relationships.

**Comment by felixfbecker** [comment]
Not sure, but maybe
```js
foreignKey: {
  name: 'gymId',
  field: 'gym_id'
}
```
Also, have you tried playing with the `underscored` option?

**Comment by rmanrique** [comment]
not sure why I didn't think about trying that, but that works! Thanks a lot. I did try the underscored option and it wasn't exactly doing what I wanted, but the option you showed above is exactly what I'm looking for. appreciate it!
