### ISSUE TITLE
v3. Create index for some_function(column) on Postgres

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#7006]
Hello!

Is it possible to do this index on Postgres? the main point is index should be of reverse(name). This is very important for name like '%abc' search. Thanks!

```sql
CREATE INDEX zemla_name
  ON "Zemla"
  USING btree
  (reverse(name))
```

When i try
```javascript
                {
                    unique: false,
                    fields: ['reverse(name)'],
                    where:{
                        level: {
                            $in: [35,4,5,6]
                        }
                    },
                    operator: 'varchar_pattern_ops'
                },
```
get this fail sql 
`CREATE INDEX "zemla_reverse(name)" ON "Zemla" ("reverse(name)" varchar_pattern_ops) WHERE "level" IN (35, 4, 5, 6)`

**Comment by felixfbecker** [comment]
I think `fields` gets interpreted as a column. Have you tried `literal()`

**Comment by alexey2baranov** [comment]
@felixfbecker 
I have not. Can you rewrite my code with literal() or point me to the manual please
