### ISSUE TITLE
Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#7008]
## What you are doing?
I runing sequelize with electron,but get error

```
D:\work\nodejs\angular\angular2-electron\output\build\node_modules\depd\index.js:374 
Uncaught TypeError: Error.captureStackTrace is not a function
```

__Dialect:__ sqlite 
__Database version:__ sqlite3
__Sequelize version:__ 3.27.0
nodejs version:__ 6.9.2

**Comment by janmeier** [comment]
Sequelize is built with node in mind, which supports the `captureStackTrace` function. Try monkey-patching the function
