### ISSUE TITLE
A belongsTo B and C using the same foreignKey, A.find({include: [B, C]}) cannot use scope on JOIN conditions.

### ISSUE THREAD

**Issue by lapinskicho** [sequelize/sequelize#7009]
## What you are doing?
As shown in the online documentation http://docs.sequelizejs.com/en/latest/docs/associations/#1m
We may define Post:Comment and Image:Comment as 1:n relationships like the following:

this.Post.hasMany(this.Comment, {
  foreignKey: 'commentable_id',
  constraints: false,
  scope: {
    commentable: 'post'
  }
});
this.Comment.belongsTo(this.Post, {
  foreignKey: 'commentable_id',
  constraints: false,
  as: 'post'
});

this.Image.hasMany(this.Comment, {
  foreignKey: 'commentable_id',
  constraints: false,
  scope: {
    commentable: 'image'
  }
});
this.Comment.belongsTo(this.Image, {
  foreignKey: 'commentable_id',
  constraints: false,
  as: 'image'
});

But when I do a Comment.findAll({ include: [Post, Image] }).then(...), the outer join conditions are not as expected.

## What do you expect to happen?
I would expect the SQL query to make use of the scopes in the outer join conditions

SELECT ... FROM `Comments` AS `Comment` 
LEFT OUTER JOIN `Posts` AS `Post` ON `Comment`.`commentable_id` = `Post`.`id` AND `Comment`.`commentable` = "post"
LEFT OUTER JOIN `Images` AS `Image` ON `Comment`.`commentable_id` = `Image`.`id` AND `Comment`.`commentable` = "image" 

so that if `Comment`.`commentable` = "post" then Image.* will all be NULL (and vice versa).

## What is actually happening?

SELECT ... FROM `Comments` AS `Comment` 
LEFT OUTER JOIN `Posts` AS `Post` ON `Comment`.`commentable_id` = `Post`.`id` 
LEFT OUTER JOIN `Images` AS `Image` ON `Comment`.`commentable_id` = `Image`.`id` 

With this query, when there exists the same id number for both Post.id and Image.id, then both Post.* and Image.* will have non-null values, regardless of the value of Comment.commentable.

Is it a bug or it works as expected?  If it works as expected, I am not still able to find a workaround from the online documentation how to apply the scope to the outer join in the above case though.

**Comment by lapinskicho** [comment]
I am using MySQL 5.7.16 and Sequelize 3.27.0

**Comment by felixfbecker** [comment]
I don't understand the issue fully and your code is not very readable. Please [format your code](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by lapinskicho** [comment]
Thanks for your reply.  The following is an SSCCE (just replace the database name/user/password) to run.

```

'use strict';

const Sequelize = require('sequelize');
const sequelize = new Sequelize('database', 'user', 'password');
sequelize.authenticate()
  .then(() => {
    console.log('Successfully connected to sequelize database');
    const Post = sequelize.define('Post');
    const Image = sequelize.define('Image');
    const Comment = sequelize.define('Comment', {
      commentable: Sequelize.STRING,
      commentable_id: Sequelize.INTEGER
    });
    Post.hasMany(Comment, {
      foreignKey: 'commentable_id',
      constraints: false,
      scope: {
        commentable: 'post'
      }
    });
    Image.hasMany(Comment, {
      foreignKey: 'commentable_id',
      constraints: false,
      scope: {
        commentable: 'image'
      }
    });
    Comment.belongsTo(Post, {
      foreignKey: 'commentable_id',
      constraints: false
    });
    Comment.belongsTo(Image, {
      foreignKey: 'commentable_id',
      constraints: false
    });

    sequelize.sync({})
      .then(() => {
        return Post.findAll({ include: [Comment] });
      })
      .then(() => {
        // console.log("\nSELECT `Post`.`id`, `Post`.`createdAt`, `Post`.`updatedAt`, `Comments`.`id` AS `Comments.id`, `Comments`.`commentable` AS `Comments.commentable`, `Comments`.`commentable_id` AS `Comments.commentable_id`, `Comments`.`createdAt` AS `Comments.createdAt`, `Comments`.`updatedAt` AS `Comments.updatedAt` FROM `Posts` AS `Post` LEFT OUTER JOIN `Comments` AS `Comments` ON `Post`.`id` = `Comments`.`commentable_id` AND `Comments`.`commentable` = 'post';\n");
        console.log("\nThe query above has `Comments`.`commentable` = 'post' in the JOIN conditions\n");
        return Comment.findAll({ include: [Post] });
      })
      .then(() => {
        // console.log("SELECT `Comment`.`id`, `Comment`.`commentable`, `Comment`.`commentable_id`, `Comment`.`createdAt`, `Comment`.`updatedAt`, `Post`.`id` AS `Post.id`, `Post`.`createdAt` AS `Post.createdAt`, `Post`.`updatedAt` AS `Post.updatedAt` FROM `Comments` AS `Comment` LEFT OUTER JOIN `Posts` AS `Post` ON `Comment`.`commentable_id` = `Post`.`id`;");
        console.log("\n\nBut the above query does not have `Comments`.`commentable` = 'post' in the JOIN conditions\n\n");
        return Comment.findAll({ include: [Post, Image] });
      })
      .then(() => {
        // console.log("SELECT `Comment`.`id`, `Comment`.`commentable`, `Comment`.`commentable_id`, `Comment`.`createdAt`, `Comment`.`updatedAt`, `Post`.`id` AS `Post.id`, `Post`.`createdAt` AS `Post.createdAt`, `Post`.`updatedAt` AS `Post.updatedAt`, `Image`.`id` AS `Image.id`, `Image`.`createdAt` AS `Image.createdAt`, `Image`.`updatedAt` AS `Image.updatedAt` FROM `Comments` AS `Comment` LEFT OUTER JOIN `Posts` AS `Post` ON `Comment`.`commentable_id` = `Post`.`id` LEFT OUTER JOIN `Images` AS `Image` ON `Comment`.`commentable_id` = `Image`.`id`;");
        console.log("\n\nIn the query above, as there is no `Comments`.`commentable` = 'post' in the JOIN conditions, both Post.* and Image.* will have non-null values, if it happens there exists Comments.commentable_id = Post.id and Comments.commentable_id = Image.id, it will be a bug.\n\n");
      })
      .catch((err) => {
        console.log(err);
      })
      .finally(() => sequelize.close());
  }, (err) => {
    console.log('Unable to connect to the sequelize database: ', err);
  })

```

The above code illustrates the issue.  In general, belongsTo doesn't seem to make use of scopes and I am not sure if it is by design or it is a bug.
