### ISSUE TITLE
Postgres DROP CONSTRAINT IF EXISTS returns error instead of warning

### ISSUE THREAD

**Issue by jdforsythe** [sequelize/sequelize#7013]
## What you are doing?
```
queryInterface.sequelize.query(`ALTER TABLE abc DROP CONSTRAINT IF EXISTS "someId_foreign_idx"`);
```
Where the "someId_foreign_idx" constraint doesn't exist.

## What do you expect to happen?
PG returns:
```
NOTICE:  constraint "someId_foreign_idx" of relation "abc" does not exist, skipping

Query returned successfully with no result in 27 msec.
```

## What is actually happening?
Sequelize is returning:
```
SequelizeDatabaseError: constraint "someId_foreign_idx" of relation "abc" does not exist
```

_Output, either JSON or SQL_

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.23.6

**Comment by TheZyppi** [comment]
How do you fix this issue? I have the same problem?
