### ISSUE TITLE
how to set 'updated_at' field manually

### ISSUE THREAD

**Issue by zhangxiaoyang** [sequelize/sequelize#7015]
Modifing `updatedAt` field by `instance.update` or `model.update` is not working. But, sequelize.query('update table set updatedAt ...') works good.

Does sequelize provide official APIs for setting `updatedAt` manually?

I found the relative issues below, however not working for me.

<https://github.com/sequelize/sequelize/issues/3759>
<https://github.com/sequelize/sequelize/issues/4230>

__Dialect:__ mysql
__Sequelize__ 3.24.6

**Comment by janmeier** [comment]
One of the linked issues is still open, please don't open new ones :)
