### ISSUE TITLE
Raw query with '+' sign adding output of two queries not working

### ISSUE THREAD

**Issue by piyushsf** [sequelize/sequelize#7020]
Hi there, 

I am trying to run the following raw query but not getting correct results:
select (select count(tables.id) from tables WHERE tables.ride_category = 'issue' AND tables.ride_status != 'Ride Canceled' AND ride_status != 'Potential Unavailability')
+
(select count(*) from (select count(table.appt_id) from tables as table WHERE table.ride_category = 'issue' AND table.ride_status != 'Ride Canceled' AND table.ride_status = 'Potential Unavailability' group by table.appt_id, table.ride_status) as ride_sum) 
AS sum

It gives result from first query only. I tried change '+' sign to ',' and got strange results. If I run the same query on postgres, it works fine. In javascript + sign might have been considered as concatinating string but ',' should have worked. Below is the code in nodejs:

sequelize.query("select (select count(tables.id) from ride_details WHERE tables.ride_category = 'issue' AND tables.ride_status != 'Ride Canceled' AND ride_status != 'Potential Unavailability')`+`(select count(*) from (select count(table.appt_id) from tables as table WHERE table.ride_category = 'issue' AND table.ride_status != 'Ride Canceled' AND table.ride_status = 'Potential Unavailability' group by table.appt_id, table.ride_status) as ride_sum) AS sum",)
                    .then(function (res,) {
                        console.log(res);
})

If the above query can be build, I am okay with it but could not figured it out.

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)
