### ISSUE TITLE
Dynamically setting associations with instance created using model.build

### ISSUE THREAD

**Issue by noelfelix** [sequelize/sequelize#7023]
## What you are doing?
Attempting to dynamically set association using an instance instantiated with model.build

```js
instance[`set${relationName}`](foundInstance)
```

## What do you expect to happen?
Instance relationship updated.

## What is actually happening?
The instance relationship is being updated (verified with logs), but an insert is taking place that causes an error.

_Output, either JSON or SQL_
Executing (26311bc9-cb20-4596-b749-fff754c8c494): INSERT INTO "AccountAddresses" ("id","CountryId","updatedAt","createdAt") VALUES ('586c6e26-548d-46f7-9d12-35ab2ccb9192','25d34ee0
009-46d5-8db5-c03893d3f4ea','2016-12-22 20:12:43.700 +00:00','2016-07-29 17:57:38.000 +00:00'); +0ms
retry-as-promised:error SequelizeDatabaseError: null value in column "firstName" violates not-null constraint +3ms

detail: 'Failing row contains (586c6e26-548d-46f7-9d12-35ab2ccb9192, null, null, null, null, null, null, null, null, null, null, 2016-07-29 17:57:38+00, 2016-12-22 20:12:43.684+00, null,
).',

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 3.24.2

**Comment by sushantdhiman** [comment]
Need model definition and relationship. Be careful to include only just the required code to reproduce your case :)
