### ISSUE TITLE
update doesn't return the number of influence records

### ISSUE THREAD

**Issue by Wolf-Jia** [sequelize/sequelize#7027]
I am using sequelize and mysql as database, but update statment in sequelize.query(sql).then(function(){})  can not return number of influence records.  I think it is important to know if the UPDATE successful. 
My code is like 
    `var sql = "UPDATE user SET username = 'abc' WHERE user_id=1;";`
    `DbStat.sequelize.query(sql, {`
    `   type: Sequelize.QueryTypes.UPDATE`
    `}).then(function(**[I think here must be return a number of influence records]**){`
    `});`

Or there some other ways to know the update execute successful ?

thanks

**Comment by sushantdhiman** [comment]
Ask yourself does `UPDATE` return anything ? Please check https://github.com/sequelize/sequelize/issues/6995

**Comment by sushantdhiman** [comment]
Although underlying library will return it, You might want to use http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

**Comment by Wolf-Jia** [comment]
@sushantdhiman as I said, i want to find a way to know if UPDATE execute successful. I can get number of influence records  in C#,  so, I ask this question, it's okay if there some other ways to reslove my problem. 
I try to use function update() as you said, it works with easy UPDATE.  But I want sql like this: "UPDATE test SET `count`=`count`+1 WHERE `id`= 1",  I tried many ways :
  `dbLog.test.update({"count": `count`+1},{where:{"id":1}}).then(function(aa,bb){});`
  `dbLog.test.update({"count": "count"+1},{where:{"id":1}}).then(function(aa,bb){});`
  `dbLog.test.update({"count": "count+1"},{where:{"id":1}}).then(function(aa,bb){});`
can not works.

regards.

**Comment by sushantdhiman** [comment]
@Wolf-Jia 
```js
const M = sequelize.define('M', {
  count: Sequelize.INTEGER
});

sequelize.sync({ force: true })
  .then(() => M.bulkCreate([{ count: 12 }]))
  .then(() => sequelize.query('UPDATE Ms SET count = count + 1 WHERE id = 1;'))
  .then(console.log);
```

Will return affected rows 

```js
[ ResultSetHeader {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    info: 'Rows matched: 1  Changed: 1  Warnings: 0',
    serverStatus: 2,
    warningStatus: 0,
    changedRows: 1 },
  ResultSetHeader {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    info: 'Rows matched: 1  Changed: 1  Warnings: 0',
    serverStatus: 2,
    warningStatus: 0,
    changedRows: 1 } ]
```

which indicate how many rows were updated

**Comment by Wolf-Jia** [comment]
@sushantdhiman  thanks

**Comment by Wolf-Jia** [comment]
@sushantdhiman, one more question, why there 2 ResultSetHeaders, and total same ?

**Comment by sushantdhiman** [comment]
@Wolf-Jia They both are same object, we might need to do some cleanup so it returns only one object
