### ISSUE TITLE
Geometry BulkInsert....Rep.value

### ISSUE THREAD

**Issue by blankstar85** [sequelize/sequelize#7028]
## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_
Model:
```
'use strict';
module.exports = function(sequelize, DataTypes) {
  var airport = sequelize.define('airport', {
    place: DataTypes.STRING,
    geo: DataTypes.GEOMETRY('POINT', 4326),

  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return airport;
};
```
Seeder:

```
'use strict';
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('airport',[
      {
        "id": "313629",
        "place": "ZZZZ",
        "geo": {"type": "Point", "coordinates": [130.270556,30.784722]},
        "created_at": new Date(),
        "updated_at": new Date()
      }

    ],{});
  },

  down: function (queryInterface, Sequelize) {
  }
};
```

## What do you expect to happen?

I have setup npm script to execute the following: sequelize db:migrate:undo:all && sequelize db:migrate && sequelize db:seed:all
I'm on the latest sequelize and sequelize-cli as well as using mysql.  this is in an express app, however the problem lies in the script, specifically the bulkInsert function.

When i run the above script I expect the geoJson inside the seeder to be entered into the database.

## What is actually happening?
Seed file failed with error: val.replace is not a function

I get the above message. If in my express app i use the model.create method passing the same json, it properly creates the geometry point in the database from the GeoJson.

_Output, either JSON or SQL_

__Dialect:__ mysql(mariadb) 
__Database version:__ 10.1.20   (npm mysql package "^2.12.0")
__Sequelize version:__ "sequelize": "~3.27.0", "sequelize-cli": "~2.4.0",

**Comment by rbnogueira** [comment]
This happens because the **bulkInsert** function on the **queryInterface** is not able to properly understand structured values for the attributes. While what you presented may work on regular **<model>.create** statements (or **<model>.bulkCreate**), it is not true for **bulkInsert** because **bulkInsert** handles the attributes as literals (mainly as strings...).

Nevertheless you can force a database function to be applied on these literals as they are inserted. On mysql you can have:

```javascript
'use strict';
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('airport',[
      {
        "id": "313629",
        "place": "ZZZZ",
        "geo": queryInterface.sequelize.fn('GeomFromText','POINT(130.270556 30.784722)'),
        "created_at": new Date(),
        "updated_at": new Date()
      }
    ],{});
  },

  down: function (queryInterface, Sequelize) {
  }
};
```

**Comment by blankstar85** [comment]
I Thought it worked that way just wast sure and couldn't figure out the proper way to call the GeomFromText function. I was missing the queryInterface.sequelize.fn. 

Thanks i'll have to update my seeder. I ended up calling the model and running it through that.
