### ISSUE TITLE
Support for SQL Server Table Hints & Locks

### ISSUE THREAD

**Issue by smassin** [sequelize/sequelize#7031]
Hi All,

This a feature request to support SQL Server table hints and locks. I did try to look through the issues list to see if it has already been discussed and code to see if its already available but didn't find anything. I apologize if this has already been discussed.

For now I've only put in a very hacky workaround into my own local version that essentially allows you to use strings to define a `SELECT ... FROM ... WITH(...)` statement that's appended onto the main query.

```
findAll({
  where: ...
  with: ["XLOCK", ... ]
})
```

In no way would that be a final implementation but I wanted to bring it up for discussion and see if there is some way we could add official support and what would be the best practice for doing so.

Thanks

**Comment by sushantdhiman** [comment]
For now Sequelize will support singular `tableHints` https://github.com/sequelize/sequelize/commit/11ff7764819f2812018f3a7b8fa16ba1851e8c4d , which will be expanded later to support multiple hints if required.
