### ISSUE TITLE
replace id with name from reference in a query

### ISSUE THREAD

**Issue by amit034** [sequelize/sequelize#7034]
I have a Project model which keeps ids of the related party owners like Project manager,Designer,UX, and Project Owner. the are all users and i want to get allProject with includes onwers names. like
  id, pm, designer,name,name.
my models:
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('Project', {
        Id: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
            field: 'id'
        },
        ownerId: {
            type: DataTypes.INTEGER(11),
            allowNull: true,
            field: 'owner_id'
        },
        pmId: {
            type: DataTypes.INTEGER(11),
            allowNull: true,
            field: 'pm_id'
        },
        designerId: {
            type: DataTypes.INTEGER(11),
            allowNull: true,
            field: 'designer_id'
        },
        uxId: {
            type: DataTypes.INTEGER(11),
            allowNull: true,
            field: 'ux_id'
        }   
    }, {
        tableName: 'project',
        timestamps: false,
        engine: 'InnoDB',
        charset: 'utf8',
        classMethods: {
            associate(models) {
                models.Project.belongsTo(models.User, {
                    'as': 'owner'
                    foreignKey: 'ownerId',
                    otherKey: 'id'
                }); 
           models.Project.belongsTo(models.User, {
                    'as': 'projectManager'
                    foreignKey: 'pmId',
                     otherKey: 'id'
           }); 
           models.Project.belongsTo(models.User, {
                    'as': 'designer'
                    foreignKey: 'designerId',
                     otherKey: 'id'
           }); 
           models.Project.belongsTo(models.User, {
                    'as': 'ux'
                    foreignKey: 'uxId',
                     otherKey: 'id'
           }); 
})};
sequelize.define('User', {
        id: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        name: {
            type: DataTypes.STRING,
            allowNull: false
        }
})

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
