### ISSUE TITLE
Named parameter ":Mi" has no value in the given object

### ISSUE THREAD

**Issue by eversnow** [sequelize/sequelize#7039]
Hello:
       I am trying to execute a sql with raw queries
      `select to_date(a.game_date|| ' ' ||a.game_time, 'yyyy-MM-dd HH24:Mi') as "beginTime",
        a.game_id "gameId" ........`
       but sequelize treat the date format string ':Mi' as a replacement,how can i  avoid that?
   
__Dialect:  postgres
__Sequelize version:3.27.0

**Comment by janmeier** [comment]
Not sure there is any good solution to this, since we don't have a way of circumventing parmeter replacement. You could do this to work around it though

```js
sequelize.query('select to_date(a.game_date|| ' ' ||a.game_time, $dateString) as "beginTime", a.game_id "gameId" ........',  { bind: { dateString: 'yyyy-MM-dd HH24:Mi' }})`

**Comment by ArttuPakarinen** [comment]
Hello, I replaced all the : with CHR(58).
from
'HH24:MI:SS'
to
'HH24'||CHR(58)||'MI'||CHR(58)||'SS'

and it works.

CHR(58) is function for ascii character ':'

**Comment by suryaiitg** [comment]
This works as well `E'YYYY-MM-DD"T"HH24\\:\\MI\\:\\SS"Z"'`
