### ISSUE TITLE
Can sequelize support adding UDF?

### ISSUE THREAD

**Issue by shangshujie365** [sequelize/sequelize#7042]
e.g. To solve a problem, I can write a function using js, or write an udf in db, but the later method get high performance. When I create table, I want add some udf with it. 
Can sequelize support this feature? It seems not hard.

**Comment by felixfbecker** [comment]
What is a UDF?

**Comment by KiPSOFT** [comment]
i think user defined functions in sql.

**Comment by felixfbecker** [comment]
What do you want Sequelize to do for this?

**Comment by shangshujie365** [comment]
@felixfbecker , when I call Table.sync, sequelize will create a table in db. So, I want you may be add a similar func to create an UDF. maybe createUDF(' create function')

**Comment by felixfbecker** [comment]
How would that be different from `sequelize.query('CREATE FUNCTION ...')`?

**Comment by shangshujie365** [comment]
@felixfbecker, that't ok
