### ISSUE TITLE
getAndCountAssociations function please?

### ISSUE THREAD

**Issue by laurenskling** [sequelize/sequelize#7045]
I would love to see a `getAndCountAssociations` as there is `findAndCountAll`
http://docs.sequelizejs.com/en/latest/docs/models-usage/#findandcountall-search-for-multiple-elements-in-the-database-returns-both-data-and-total-count

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/4829

**Comment by OKNoah** [comment]
LOL
