### ISSUE TITLE
Can auto sync two database

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#7050]
I want use sequelize sync local database(sqlite) to remote database(mysql),has any simple way?

**Comment by felixfbecker** [comment]
What do you mean with sync, scema or data?

**Comment by keyiis** [comment]
@felixbecker schema and data,remote and local has same schema,i hope sync execute insert/update/delete .

**Comment by keyiis** [comment]
like pouchdb.

**Comment by sushantdhiman** [comment]
If you are talking about a feature to copy your local database to server database then its not possible by sequelize. Also its a feature that Sequelize being an ORM will not support.

You might want to use external tooling provided `mysql` and `sqlite` for exporting and importing databases, possibly by `csv` like mediums
