### ISSUE TITLE
Get affected row counts on method bulkCreate

### ISSUE THREAD

**Issue by iamcrypticcoder** [sequelize/sequelize#7051]
## What you are doing?
I am using **Model.bulkCreate()** method with option **ignoreDuplicates: true**. Currently **bulkCreate()** method has only one promise which gives array of instances.

```
StoryView.bulkCreate(rows, { ignoreDuplicates: true }).then(function(response) {
    // response is array of instance which is always same length of **rows**
}).catch(function(err) {
    // handle error
});
```

## What do you expect to happen?
I wanted to know **affected rows count** as MySQL provides

## What is actually happening?
Getting response of instance

__Dialect: mysql
__Database version: 10.1.19-MariaDB
__Sequelize version: 3.13.0

**Comment by fahrenq** [comment]
For those who want to get a number of inserted rows with bulkcreate and ignore duplicates:

```
  const bulkSaveResponse = await Transaction.bulkSave(transactions);
  const insertedTransactions = bulkSaveResponse.filter((i) => i.dataValues.id);

  if (insertedTransactions.length !== 0) {

  }
```

**Comment by slidenerd** [comment]
@fahrenq this returns every ID if the id in question is primary key of type UUID, we are talking sequelize v5.19.0 and dialect postgres

**Comment by bhuvana-guna** [comment]
@slidenerd Found any solution?

**Comment by papb** [comment]
Can someone please post how would they do it with a raw query?

**Comment by yoya93** [comment]
> ## ¿Qué estás haciendo?
> Estoy usando el método **Model.bulkCreate ()** con la opción **ignoreDuplicates: true** . Actualmente, el método **bulkCreate ()** tiene solo una promesa que proporciona una matriz de instancias.
> 
> ```
> StoryView.bulkCreate(rows, { ignoreDuplicates: true }).then(function(response) {
>     // response is array of instance which is always same length of **rows**
> }).catch(function(err) {
>     // handle error
> });
> ```
> 
> ## ¿Qué esperas que pase?
> Quería saber que **las filas afectadas cuentan** como MySQL proporciona
> 
> ## ¿Qué está pasando realmente?
> Obteniendo respuesta de instancia
> 
> __Dialect: mysql
> __Versión de la base de datos: 10.1.19-MariaDB
> __Sequelize versión: 3.13.0

@iamcrypticcoder @papb @slidenerd @bhuvana-guna 
Hello Do you have any way to solve this currently ????. Thank you very much
