### ISSUE TITLE
model.create(...) - INSERT INTO "table" DEFAULT VALUES RETURNING *;

### ISSUE THREAD

**Issue by dlarr** [sequelize/sequelize#7054]
Hi,

I am struggling with this strange behaviour. I am just trying to insert a new row on a table that has 3 associations through a simple model.table.create({attributes});

## What you are doing?
I am creating a row in the table typeutilisateur who has 3 foreign key, but For now, I didn't declare it in index.js (no belongsTo , hasMany etc...)

```js
router.post('/', function (req, res) {
    models.typeutilisateur.create({
        id_utilisateur: req.body.id_utilisateur,
        id_entreprise: req.body.id_entreprise,
        id_profil: req.body.id_profil,
        type_utilisateur: req.body.type_utilisateur
    }).then(function(data) {
        res.status(200);
        res.json(data.get({plain: true}));
    }).catch(function(error) {
        res.status(500);
        res.json({error:error, stackError:error.stack});
    });
});
```

## What do you expect to happen?
I want the object properly inserted into the database, with a normal query output (here is a sample from sequelize logging)
Executing (default): INSERT INTO "typeutilisateur" ("id","type_utilisateur","id_entreprise","id_utilisateur","id_profil") VALUES (DEFAULT,'Invité',2,4,1) RETURNING *;

## What is actually happening?
Nothing gets  inserted because of a Not Null constraint on id_entreprise. But it comes from SQL that is not properly rendered : (sample from sequelize logging)
Executing (default): INSERT INTO "typeutilisateur" DEFAULT VALUES RETURNING *;

## Additionnal informations : 

- I am performing other sequelize request during the web page scenario
- When I click the button performing the INSERT after the complete scenario I get the error
- If I reboot the server.js, and without making the complete scenario I just click on the button : It works properly.
- Main Difference between both req objects (OK and KO) seems to be WritableState.sync : The one who is not working it's set to false.

__Dialect:__  postgres 
__Database version:__ 9.6.1
__Sequelize version:__ 3.27.0

**Comment by dlarr** [comment]
Ok I got it :)


## Problem
I was performing several calls of model.typeutilisateur.create() in a for loop. The callback wasn't done but another call was being done.

## Solution
I resolved this by doing the right way with bulkCreate() instead.

You can close this issue.

Best regards,
Denis.

You can close this.

**Comment by dlarr** [comment]
Hello, 

I am reopening this issue because the methode models.typeutilisateur.create() ALWAYS have the behaviour I described. Even wen I call it only once.

I have the fallback solution using bulkCreate even for 1 object but, I can't make it work.

1. The post is done with proper JSON
2. The req.body has the good values server side.

The request is generated without any values as described in section problems...

**Comment by felixfbecker** [comment]
Please try to create an [SSCCE](http://www.sscce.org/). You can find a template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by dlarr** [comment]
1st post is SSCCE

**Comment by sushantdhiman** [comment]
Looks like a userland problem, we have 100s of tests creating / inserting records. Please reply with short self contained replication of issue.
