### ISSUE TITLE
BigInteger columns are displayed as String type, despite dialect settings.

### ISSUE THREAD

**Issue by charlesdeuter** [sequelize/sequelize#7055]
## What you are doing?
converting some values to BIGINT

setting the options:

```
    "dialectOptions": {
      "supportBigNumbers": true,
      "bigNumberStrings": false
    }
```

## What do you expect to happen?
Sequelize should continue to return a number for those ID's up until Number.MAX_SAFE_INTEGER

## What is actually happening?
It outputted a string.

__Dialect:__  postgres 
__Database version:__ 9.6.1
__Sequelize version:__ 3.27.0

**Comment by sushantdhiman** [comment]
Are you sure `node-postgres` supports these dialect options ? It looks like `pg`  module just return strings for BIGINT https://github.com/brianc/node-postgres/issues/924

**Comment by charlesdeuter** [comment]
@sushantdhiman **Please** reopen this issue, if this is the case then documentation is needed for those dialect options.

**Comment by sushantdhiman** [comment]
Can you point to part of documentation which says `supportBigNumbers` is supported for all dialects.

As name suggests these are dialect options, will be different for different dialects. `supportBigNumbers` is `mysql` specific and not supported by `pg`

**Comment by charlesdeuter** [comment]
@sushantdhiman nevermind, I revisited the page and it does have documentation although the wording is poor.

**Comment by sushantdhiman** [comment]
@charlesdeuter Yeah lots of work needed on documentation, its in v4 milestone #6886
