### ISSUE TITLE
scope method syntax loses parameters when used multiple times

### ISSUE THREAD

**Issue by doowb** [sequelize/sequelize#7058]
## What you are doing?
```js

// simple model with scopes that take parameters
var Location = sequelize.define('Location', {
  state: types.STRING,
  city: types.STRING
}, {
  scopes: {
    state: function(state) {
      return {where: {state: state}};
    },
    city: function(city) {
      return {where: {city: city}};
    }
  }
});

// create a scopes array to be reused
var scopes = [
  {method: ['city', 'Springfield']},
  {method: ['state', 'OH']}
];

// do some queries
Location.scope(scopes).count().then(console.log);
Location.scope(scopes).findAll().then(console.log);
```

## What do you expect to happen?

I expect the arguments in the scopes to be passed into the queries for both queries.

## What is actually happening?

Only the first query is using the arguments because the internal `method` arrays on the `scopes` array are being modified [here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1298) when using `.splice`.

Locally, I changed that to `.slice` so the array isn't mutated and it fixed my use case. I did a little digging in the issues, but not enough to determine if this has come up before. If this is a bug, I can try to submit a PR when I get a chance to make the changes and provide unit tests.

**Comment by felixfbecker** [comment]
PR welcome

**Comment by doowb** [comment]
PR submitted!

**Comment by tommybananas** [comment]
Strange, I am still seeing this behavior on 4.7.5
