### ISSUE TITLE
Get stored procedure output parameter

### ISSUE THREAD

**Issue by DeekshithShetty** [sequelize/sequelize#7060]
Hey i am using sequelize to execute a stored procedure in MS SQL Server. I get the result records in the callback. But i am not able to retrieve the output parameters set in the stored procedure. How do we get this? Thank you.

__Dialect:__ mssql 
__Sequelize version:__ 3.28.0

**Comment by sushantdhiman** [comment]
Can you post a minimal example with expected and real output ?

**Comment by DeekshithShetty** [comment]
@sushantdhiman The stored procedure actually sets a value to the output parameter. On executing the SP as a raw query only the select records are recieved in the callback. Any idea how we get the output parameters set in SP? Here is the code snippet for calling the stored procedure.
`sequelize.query('EXEC storedProcedure' })
       .spread(function(outputValue , records) {
            console.log(records);
        }).error(function(err){
                res.json(err);
        });`

**Comment by sushantdhiman** [comment]
Its not implemented in Sequelize @DeekshithShetty but you can access output parameters via using underlying connector library https://github.com/tediousjs/tedious/issues/14

**Comment by DeekshithShetty** [comment]
Ok thank you :). Just want to know whether this will be implemented in sequelize in the future with ORM?

**Comment by sushantdhiman** [comment]
AFAIK its something specific to MSSQL, If you can propose a clean API we might add it. But please note MSSQL is mostly user contributed and someone will have to contribute for this feature

**Comment by roblom** [comment]
@sushantdhiman , I have the same requirement as @DeekshithShetty but I do find any documentation on how to pass output parameters, nor how to extract them. Could I ask for a link to the proper documentation or an example? Thanks!

**Comment by carloshpdoc** [comment]
@sushantdhiman , I also have the same problem as  @DeekshithShetty and @roblom . Today I use the procedure, and how I will put the sequelize to the application if  not supported?

**Comment by sushantdhiman** [comment]
@carloshpdoc Its not supported. So you will have to use tedious directly for that part of your application.

If you think Sequelize should have it, please propose an API and action plan how will you manage this with current MSSQL implementation.

**Comment by ggb88** [comment]
In order for my exec to work (mssql 2016), my syntax needed to use the OUTPUT clause:
`DECLARE @NewIdentity BIGINT; EXEC s_DimItemUpsert :Modify, ... , @NewIdentity OUTPUT; SELECT @NewIdentity AS ItemID;`

**Comment by lucafrancescato** [comment]
> In order for my exec to work (mssql 2016), my syntax needed to use the OUTPUT clause: `DECLARE @NewIdentity BIGINT; EXEC s_DimItemUpsert :Modify, ... , @NewIdentity OUTPUT; SELECT @NewIdentity AS ItemID;`

This worked, however I had to place the @output parameter in the exact order where the output parameter was expected by the stored procedure, e.g.:
`const results = await sequelize.query('DECLARE @out AS int; EXEC stored_procedure_name :param1, :param2, @out output, :param4; SELECT @out AS result;', { replacements: { param1: value1, param2: value2, param4: value4 }, type: QueryTypes.SELECT });`
