### ISSUE TITLE
Creating an instance from an instance of the model

### ISSUE THREAD

**Issue by amir-s** [sequelize/sequelize#7063]
Hello,

I'm trying to refactor a piece of code and use Sequelize to access the database.
Basically all I need to do with it comes down to have a function which gets the `user` object and do something with it. Now this `user` object, could be just `{id: 1}`, or could be an actual `User` object with all the properties and functionalities. 

```js
var User = sequelize.define('user', {
    name: Sequelize.STRING
});
let Permission = sequelize.define('permission', {
    label: Sequelize.STRING
});
Permission.belongsToMany(User, { through: 'UserPermission' });
User.belongsToMany(Permission, { through: 'UserPermission' });
// ....
function giveAccess(user) {
    return User.build(user).addPermission(/* ... */)
}
```

Now, calling `giveAccess` with `{id: 1}` or any other properties that `User` could have, works fine. `User.build` gets those properties and builds the instance from it. However, we can not simply build a `User` by passing an actual instance of it.

```js
giveAccess({id: 1}) //works fine
giveAccess({id:1, name: 'Amir'}) // works fine, assuming User has a name field

let user = User.build({id: 1});
giveAccess(user); // doesn't work
giveAccess(user.get()); // works
```

Can we discuss about this functionality that if the input argument is already an instance of the model, `Model.build` (and possibly `Model.create` etc) call `model.get()` on it automatically?

**Comment by felixfbecker** [comment]
Why dont you check that yourself?

**Comment by amir-s** [comment]
It would be nice if the framework does it by itself. If the framework needs the input object to have columns as its properties, i dont see why it shouldnt work with the instance if the model as it has those props.

Honestly, i didn't think it wont work. Seems it can not read the PK from the instance.

**Comment by felixfbecker** [comment]
Well it's a bit more tricky than that because the properties are actually inside `dataValues` atm (which may change in the future) and the props are just getters/setters.

Sequelize is not a framework.

**Comment by janmeier** [comment]
Yeah, I don't really see the benefit on this  - It can very easily be implemented in userland
