### ISSUE TITLE
options.pool.validateConnection

### ISSUE THREAD

**Issue by zaggino** [sequelize/sequelize#7068]
Hi,
the option is mentioned here: https://github.com/sequelize/sequelize/blob/master/docs/api/sequelize.md

Searching the repository it seems to be only mentioned in docs: https://github.com/sequelize/sequelize/search?utf8=%E2%9C%93&q=validateConnection

And when I tried to do this with latest sequelize, nothing seems to happen:
```
const poolConfig = {
    min: 1,
    max: maxConnections,
    idle: 60000,
    validateConnection: function (arg1) {
      console.log('validateConnection', this, arg1);
      return false;
    }
  };
```

Is this feature actually implemented?

**Comment by felixfbecker** [comment]
That is a method of generic-pool

**Comment by zaggino** [comment]
@felixfbecker 
Sequelize depends on `"generic-pool": "^2.4.4",`
I've cloned `node-pool ((v2.5.0))`
but I can't any implementation in there either

also did a full file search (including all downloaded node_modules) with my project but nothing except the mention in the docs:
![image](https://cloud.githubusercontent.com/assets/1067319/21667345/3fed1f60-d34c-11e6-9285-1d15041271cc.png)

**Comment by sushantdhiman** [comment]
@zaggino `validateConnection` is used when a connection is reused from pool, `genereic-pool` run this method by passing it resource object (connection in sequelize case) to see if resource can be reused.

Docs https://github.com/coopernurse/node-pool/blob/v2.5/lib/generic-pool.js#L90

**Comment by zaggino** [comment]
Yeah, but I don't think sequelizes `validateConnection` options actually translates to `factory.validate` in the generic-pool. Where's the code that actually uses something called `validateConnection` ?

**Comment by sushantdhiman** [comment]
Its used here https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L28 , but you are right it should be called `validate` not `validateConnection`

**Comment by felimartina** [comment]
@zaggino how would you use the `validate` option for pool after this PR?

just something like this?
```
validate: function (arg1) {
      console.log('validate', this, arg1);
      return false;
  }
```

**Comment by zaggino** [comment]
@felimartina 
```
    validate: (obj) => {
      if (!obj.connection.createdAt) {
        obj.connection.createdAt = Date.now();
        return true;
      }
      return Date.now() - obj.connection.createdAt < maxConnectionAge;
    }
```
For some reason (which is not 100% clear to me), if we kept the connections open indefinitely (days) they started eating out postgres memory - this keeps memory usage on our machine stable. I think maxConnectionAge is defined as 1 hour.

**Comment by felimartina** [comment]
Great! thanks for the quick feedback! I am using mysql but I think this `validate` option can be of much help! thanks a lot

**Comment by JustinMGaiam** [comment]
@zaggino We are running into a Postgres memory leak across all of AWS RDS instances due to connections staying open forever after upgrading from Postgres 9.6.6 to 9.6.11 and Postgres 9.6.6 to 10.6 using the same Sequelize version before and after upgrade.  Did you find your `validate` fix effective in permanently fixing the issue?

If so I would like to get figure out how to get this as a PR into Sequelize.

**Comment by zaggino** [comment]
@JustinMGaiam yeah, we still use the fix above and never had any memory issues since

**Comment by JustinMGaiam** [comment]
@zaggino We implemented this fix and it worked for us too, much appreciated!  I am going to post this as an issue and see if I can get momentum on a PR since others will eventually run into this issue.
