### ISSUE TITLE
Enabling logging depending on process.env.ENV variable

### ISSUE THREAD

**Issue by JakobLofgren** [sequelize/sequelize#7071]
## What you are doing?

```
const sequelize = new Sequelize(config[env].database, config[env].username, config[env].password, {
  host: config[env].host,
  dialect: "mysql",
  pool: {
    min: 0,
    max: 10,
    idle: 10000
  },
  logging: process.env.ENV == "dev" ? console.log : false
})
```

## What do you expect to happen?
I want to disable logging when process.env.ENV == "prod", otherwise log everything using console.log

## What is actually happening?
Nothing gets logged either way, in either enviroments.

__Dialect:__ mysql
__Database version__: Unrelated
__Sequelize version__: 3.27.0

**Comment by sushantdhiman** [comment]
`process.env.ENV` is not set, have you tried `process.env.NODE_ENV`

**Comment by JakobLofgren** [comment]
Oh wow, I recently changed the way I load in enviroment variabels. Must have overlooked this.
Thx @sushantdhiman, you can close this issue.
