### ISSUE TITLE
Sqlite remove/change/rename column don't pass foreign key references along in the new table

### ISSUE THREAD

**Issue by francescoinfante** [sequelize/sequelize#7078]
## What you are doing?
I'm trying to rename a column on an Sqlite db. I use `renameColumn` on the `QueryInterface` that, in the Sqlite case, is going to call `renameColumn` on the `SQLiteQueryInterface`.

## What do you expect to happen?
I expect that:
1) a temporary table is created equal to the first one (except the renamed column) including foreign key references.
2) data is copied over to the temporary table
3) old table is deleted
4) a new table is created equal to the first one (except the renamed column) including foreign key references.
5) data is copied over to the new table

## What is actually happening?
1) a temporary table is created equal to the first one (except the renamed column) **NOT including foreign key references**.
2) data is copied over to the temporary table
3) old table is deleted
4) a new table is created equal to the first one (except the renamed column) **NOT including foreign key references**.
5) data is copied over to the new table

This is the original table:
```SQL
CREATE TABLE `matches` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `hash` VARCHAR(200) NOT NULL UNIQUE, `alertId` INTEGER REFERENCES `alerts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
```

This is the table after the renameColumn on 'hash' -> 'foo'
```SQL
CREATE TABLE `matches` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `foo` VARCHAR(200) NOT NULL, `alertId` INTEGER)
```

__Dialect:__ sqlite
__Database version:__ 3.9.x
__Sequelize version:__ 3.24.x

**Comment by francescoinfante** [comment]
Even **UNIQUE** are lost.

**Comment by francescoinfante** [comment]
A solution, not sure if correct, would be to create a particular case of `QueryInterface::describeTable` for Sqlite, basically to implement `SQLiteQueryInterface::describeTable` s.t. it doesn't use 
```SQL
PRAGMA TABLE_INFO('tableName');`
```
but
```SQL
SELECT type, sql FROM sqlite_master WHERE tbl_name='tableName'
```

The correct result of the new describeTable would be used by `renameColumnQuery` and `removeColumnQuery`

**Comment by sushantdhiman** [comment]
Some old related issue, this issue might be affecting other dialects.

https://github.com/sequelize/sequelize/issues/2033
https://github.com/sequelize/sequelize/issues/6205
https://github.com/sequelize/sequelize/issues/3466
https://github.com/sequelize/sequelize/issues/5007

**Comment by francescoinfante** [comment]
Any idea other than using:
```SQL
SELECT type, sql FROM sqlite_master WHERE tbl_name='tableName'
```

This query returns the original CREATE TABLE statement. Parsing it is probably not an option.

**Comment by bartcone** [comment]
#7108 didn't address this issue unfortunately..in my case, I'm using a `removeColumn` in a migration (sqlite dialect). The temporary table loses a UNIQUE constraint. I'll try to get an example project together. Until then, going to try and get back 3 hours of my life. :)

**Comment by sushantdhiman** [comment]
No stale bot closed it, its meant to be kept open

**Comment by nashika** [comment]
I am avoiding similar problem in the following bad patch code.
This patch modify queryInterface.describeTable method.

```javascript
function up(queryInterface) {
  let backupDescribeTable = queryInterface.describeTable;
  queryInterface.describeTable = async function (tableName, options) {
    let tableDatas = await backupDescribeTable.call(queryInterface, tableName, options);
    // add auto increment to id column
    tableDatas.id.autoIncrement = true;
    // get foreign key info
    let foreignKeyDatas = (await queryInterface.sequelize.query(`PRAGMA FOREIGN_KEY_LIST("${tableName}");`))[0];
    for (let foreignKeyData of foreignKeyDatas) {
      let tableData = tableDatas[foreignKeyData.from];
      tableData.references = {model: foreignKeyData.table, key: foreignKeyData.to};
      tableData.onDelete = foreignKeyData.on_delete;
      tableData.onUpdate = foreignKeyData.on_update;
    }
    return tableDatas;
  };
}
```

This patch can restoration of foreign keys.
AutoIncrement is force set to id column.

**Comment by mwohlert** [comment]
Still an issue.

**Comment by papb** [comment]
@mwohlert Does @nashika's workaround work for you?

Also, can you please check if this problem really only occurs with SQLite, or if it is a problem with another dialect as well (like postgres, for example)?

**Comment by Pierre-Gilles** [comment]
The problem still exists, and only in SQlite because of the nature of the change/remove/rename column code which recreate a new table because SQLite doesn't support ALTER TABLE fully.

**Comment by thomasleese** [comment]
Yes, this problem still happens - makes it very difficult to write migrations for SQLite.

I also had to change @nashika's example when running inside a transaction (which is necessary for consistency). You need to pass the transaction as the second argument to the query:

```js
let foreignKeyDatas = await queryInterface.sequelize.query(
  `PRAGMA FOREIGN_KEY_LIST("${tableName}");`,
  { transaction: transaction }
)[0];
```

**Comment by Pierre-Gilles** [comment]
Could we integrate this code in SQlite changeColum/renameColumn/removeColumn code in a PR ?

https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query-interface.js#L58

We need to migrate constraint as well (unique for ex)

**Comment by dyc3** [comment]
Here's what I've found so far:

- addColumn, changeColumn removes unique constraints on other columns 
- sqlite: `PRAGMA TABLE_INFO(table);` does not include the unique constraint in the response
- sqlite: `PRAGMA INDEX_LIST(table);` returns constraints on everything in the table

**Comment by dyc3** [comment]
I've created a rough fix that fixes the behavior for the sscce here: https://github.com/papb/sequelize-sscce/pull/86

Is there an sscce for the foreign key thing?

> ```js
> function up(queryInterface) {
>   let backupDescribeTable = queryInterface.describeTable;
>   queryInterface.describeTable = async function (tableName, options) {
>     let tableDatas = await backupDescribeTable.call(queryInterface, tableName, options);
>     // add auto increment to id column
>     tableDatas.id.autoIncrement = true;
>     // get foreign key info
>     let foreignKeyDatas = (await queryInterface.sequelize.query(`PRAGMA FOREIGN_KEY_LIST("${tableName}");`))[0];
>     for (let foreignKeyData of foreignKeyDatas) {
>       let tableData = tableDatas[foreignKeyData.from];
>       tableData.references = {model: foreignKeyData.table, key: foreignKeyData.to};
>       tableData.onDelete = foreignKeyData.on_delete;
>       tableData.onUpdate = foreignKeyData.on_update;
>     }
>     return tableDatas;
>   };
>   change or remove or renameColumn(...);
> }
> ```

Is this code still relevant?

**Comment by Androphin** [comment]
I just did a migration with renameColumn() and lost all the foreign keys in other tables to that referenced table I did the column rename on.
Sequelize: v6.5.0
Sequelize-CLI: v6.2.0
SQLite3: v5.0.2

**Comment by Uko** [comment]
changeColumn() removes the onUpdate and onDelete constarints from the foeigh keys…

Sequelize: v6.6.2
Sequelize-CLI: v6.2.0
SQLite3: v5.0.0
