### ISSUE TITLE
Can't use "ALL" as a parameter for "LIMIT" in PostGres

### ISSUE THREAD

**Issue by relwell** [sequelize/sequelize#7079]
## What you are doing?
Given a table called "tbl" and a model called "Table", I will perform the following query:

```js
let query = 'SELECT * FROM tbl LIMIT :limit OFFSET :offset';
sequelize.query(query, {model: Table, replacements: {limit: "ALL", offset: 0}})
```

## What do you expect to happen?
Passing "ALL" should act like we put no limit on the query.

## What is actually happening?
I receive the following error:
```
Unhandled rejection SequelizeBaseError: invalid input syntax for integer: "all"
```

__Dialect:__ postgres
__Database version:__ 9.6.1
__Sequelize version:__ 3.28.0

**Comment by relwell** [comment]
Note that if you pass null, it works the same as `LIMIT ALL`.

It may make sense to introduce better error handling or validation for this case.

**Comment by janmeier** [comment]
I've never heard of that syntax

>  LIMIT ALL is the same as omitting the LIMIT clause.

So just do that :)
