### ISSUE TITLE
Docs search is broken

### ISSUE THREAD

**Issue by ashlux** [sequelize/sequelize#7080]
The search on http://docs.sequelizejs.com/en/v3/ doesn't work. It forwards to https://readthedocs.org/search/?q=promise&check_keywords=yes&area=default&project=sequelize&version=v3&type=file but no results are found.

**Comment by sushantdhiman** [comment]
We depend upon Readthedocs for this, External issue https://github.com/rtfd/readthedocs.org/issues/2025

**Comment by ashlux** [comment]
Wow, I can't believe it's been broken that long.

**Comment by tnrich** [comment]
Just an update that the documentation search for v3 is still broken. It looks like there might have been a workaround mentioned in https://github.com/rtfd/readthedocs.org/issues/1487
