### ISSUE TITLE
Model#belongsTo() doesn't create foreign key in database

### ISSUE THREAD

**Issue by jeafa** [sequelize/sequelize#7083]
I'm trying to make two tables with one-to-many relationship using **sequelize@3.29.0** and **sqlite3@3.1.8**. The following code I'm using for that:

    // node v6.9.2

    const Sequelize = require('sequelize');
    
    const sequelize = new Sequelize('sqlite:database', {
      storage: 'db.sqlite3',
      define: { timestamps: false }
    });
    
    const User = sequelize.define('users', {
      name: Sequelize.STRING
    });
    
    const Task = sequelize.define('tasks', {
      title: Sequelize.STRING
    });
    
    User.hasMany(Task);
    Task.belongsTo(User);
    
    sequelize.sync({ force: true });

It produces the following scheme:

    CREATE TABLE IF NOT EXISTS "users" (
      "id" integer PRIMARY KEY AUTOINCREMENT,
      "name" varchar(255)
    );

    CREATE TABLE IF NOT EXISTS "tasks" (
      "id" integer PRIMARY KEY AUTOINCREMENT,
      "title" varchar(255),
      "userId" integer
    );

Accordingly to the [project docs](http://docs.sequelizejs.com/en/v3/docs/associations/#foreign-keys) it should create __userId__ as FOREIGN KEY however it doesn't.

What I'm doing wrong? or How can I fix it?

**Comment by adampetrie** [comment]
@jeafa - Did you figure this out? I am experiencing something similar.

**Comment by jeafa** [comment]
@adampetrie yes, the problem was in GUI which doesn't show foreign keys. You can check it in sqlite3 REPL if your table has foreign key by dot-command `.schema`:
```
$ sqlite3 db.sqlite3 
SQLite version 3.14.0 2016-07-26 15:17:14
Enter ".help" for usage hints.

sqlite> .schema
CREATE TABLE `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255));
CREATE TABLE `tasks` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `title` VARCHAR(255), `userId` INTEGER REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);
```
