### ISSUE TITLE
Connections not closed on server restart

### ISSUE THREAD

**Issue by fnbns** [sequelize/sequelize#7084]
Dear Sequelize users,

I just stumbled into a problem using the package and I wonder if this is a bug or a missues:
I am running a nodejs server with forever[1] that is connecting to a mysql instance through sequelize. I just observed that if an error occurs on the server and forever restarts it, the old connection is not closed, therefore, the number of database connections keep increasing. As a test, I ran a small script that crashed on every request and reached 100 connections in 100 restarts.

Is there a way to close the database connection manually before the server 'crashes'?
Am I using the module correctly or this is a bug?

Thank you,
Best thoughts,
Alex.

[1] https://www.npmjs.com/package/forever

**Comment by sushantdhiman** [comment]
You didn't followed the issue template so I dont know which version you are using ? 

Have you tried master, which enforce pooling that might solve it.

**Comment by funnybones** [comment]
Hello, I am sorry, I am using the latest version from npm with enforce pooling and it is not solved.

**Comment by sushantdhiman** [comment]
You should use `sequelize.close` before application shutdown to close all connections. more details https://github.com/sequelize/sequelize/issues/7144#issuecomment-275027512
