### ISSUE TITLE
upsert return false even when row is updated

### ISSUE THREAD

**Issue by hulloanson** [sequelize/sequelize#7089]
### Codes
```js
// Product model definition
this.Product = this.sequelize.define('product', {
      id: {
        type: Sequelize.INTEGER(11).UNSIGNED,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false
      },
      pid: {
        type: Sequelize.STRING,
        unique: true,
        allowNull: false
      },
      ean: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: true
      },
      alias: {
        type: Sequelize.STRING,
        unique: true
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false
      },
      cost: {
        type: Sequelize.DECIMAL(18, 9),
        allowNull: false
      },
      price: {
        type: Sequelize.DECIMAL(18, 9),
        allowNull: false
      }
    })

// upsert code (I'm using expressjs):
Product.upsert({
      id: 1,
      name: 'Test Product 100',
      pid: 'test-pid-113',
      ean: 'test-ean-43',
      alias: 'test-alias-23',
      cost: 1.5,
      price: 3
    })
      .then((ins) => {
        res.send({
          OK: true,
          updated: ins
        })
      })
      
      .catch((err) => {
        res.send({
          OK: false,
          err: err
        })
      })
```

### Results

Originally, I had:
```JSON
{
  "id": 1,
  "pid": "test-pid-113",
  "ean": "test-ean-43",
  "alias": "test-alias-23",
  "name": "Test Product 5",
  "cost": 1.5,
  "price": 3,
  "createdAt": "2017-01-08T10:17:54.000Z",
  "updatedAt": "2017-01-09T04:11:44.000Z"
}
```

After update, I had:
```JSON
{
  "id": 1,
  "pid": "test-pid-113",
  "ean": "test-ean-43",
  "alias": "test-alias-23",
  "name": "Test Product 100",
  "cost": 1.5,
  "price": 3,
  "createdAt": "2017-01-08T10:17:54.000Z",
  "updatedAt": "2017-01-09T04:11:44.000Z"
}
```

Looked good, but the return value from the `.then` promise was false. That is, when I went to the http endpoint, I got this result:
`{ OK: true, updated: false }`

Placed a break-point at the promise function and inspected the return value. Got the same result.

What I expect is:
`{ OK: true, updated: true }`

Thanks for reading all these. Any help will be greatly appreciated.

__Dialect:__ mysql
__Database version:__ 5.7.11
__Sequelize version:__ 3.29.0

**Comment by hulloanson** [comment]
Ah. My bad. Didn't read the doc carefully. 

In Sequelize doc on upsert(): 

> Returns: Returns a boolean indicating whether the row was created or updated. 

If the row was updated, it returned false. Reading the source code confirmed that:

```js
// at the end of upsert 
// MySQL returns 1 for inserted, 2 for updated http://dev.mysql.com/doc/refman/5.0/en/insert-on-duplicate.html. Postgres has been modded to do the same

    return rowCount === 1;
```

**Comment by vinhboy** [comment]
@hulloanson Thanks for looking into this

I feel like returning `false` for an update is very unintuitive.

Also, the documentation saying

> Returns: Returns a boolean indicating whether the row was created or updated.

is really ambiguous. Why should we assume `true` is created and `false` is updated.

And what if the query fails? Is that also a `false`?

I think true should be for both updated and created. And `false` for when the query fails.

**Comment by hulloanson** [comment]
Indeed... but I haven't been using sequelize lately. Perhaps you can open a new issue on this?

**Comment by stephan-nordnes-eriksen** [comment]
@vinhboy I agree that this might seem a bit unintuitive, and perhaps a string, or some other data model is better, but with your suggestion you would loose the knowledge of weather or not you updated or created the item. Very often that is exactly the distinction you need (eg. returning 201 vs 200 from an api endpoint).

**Comment by FreitasMurillo** [comment]
I think the problem is in the docs. The doc should explain better the return type.
If the query fails there will be no "then()" since the Promise will be rejected and we can get the error using the "catch()";

**Comment by 2359junius** [comment]
This is still a problem today. Documentation should be updated to be less ambiguous. 

"Returns a boolean indicating whether the row was created or updated."
