### ISSUE TITLE
[Oracle] Promise.join causes weird result at integration test runtime

### ISSUE THREAD

**Issue by ggrimbert** [sequelize/sequelize#7092]
Hi,

I am working on integration tests with Oracle adn I'm having a problem with the following : https://github.com/sequelize/sequelize/blob/master/test/integration/schema.test.js#L1152.

At each time the function fixtureA() is called, I have a different behavior on runtime. 
It seems that the call to Promise.join sometimes doesn't work and some actions are not made (from line 152 to the end of the function).

I don't understand why this doesn't work, but this make the test failing in some times, and when it works, I know that the results are false compared to MsSql.

**Comment by sushantdhiman** [comment]
@ggrimbert I dont see `fixtureA` anywhere in file you linked. Are you working with master as base ?

Random failure in promise can be caused due to `cls-bluebird` but not sure.

**Comment by ggrimbert** [comment]
Sorry, wrong file it's https://github.com/sequelize/sequelize/blob/master/test/integration/include/schema.test.js#L1152, fixtureA is at the top of the file.

**Comment by sushantdhiman** [comment]
Can you tell me what error or non linear behavior you are noticing :)

**Comment by ggrimbert** [comment]
Well, I have no error.

The behavior is that sometimes, a part of the code inside the Promise.join isn't executed.

For example, sometimes 
```
Promise.join(
                        products[(i * 5) + 0].setTags([
                          tags[0],
                          tags[2]
                        ]),
                        products[(i * 5) + 1].setTags([
                          tags[1]
                        ]),
                        products[(i * 5) + 0].setCategory(tags[1]),
                        products[(i * 5) + 2].setTags([
                          tags[0]
                        ]),
                        products[(i * 5) + 3].setTags([
                          tags[0]
                        ])
                      ),
```
is not executed for some values of i (never the same value of i), so the records are not valid. And at the end of the execution, I don't have the correct record number
```
expect(products.length).to.equal(10);
```
Sometimes products.length is 8, sometimes 4.

After requesting the tables directly, the product_tag table has from 10 to 20 records (in MsSql it's always 25).

In the same way, some records of product table are not updated, so records in product_tag are not created.
All records in product are made, but some are not updated, so they are in invalid state for the test.

I hope I've been clear enough, it's not easy to explain this strange behavior.

**Comment by sushantdhiman** [comment]
You can always notice this behavior ?

Do you have latest code pushed in your PR, with this issue ?

**Comment by ggrimbert** [comment]
Yes, it's at any time.

Even if the test is ok, some records are not inserted.

My PR is old and on the bad version (V3) and I haven't tried to pass integration tests. I am working with master actually, I am up to date.
If this is really needed I may push it on my company's fork for you to take a look, but you'll need to have an Oracle DB, the docker image I use is not ready.

**Comment by sushantdhiman** [comment]
You can push the latest code and update the PR. I dont have Oracle DB but try to setup docker if required

**Comment by ggrimbert** [comment]
Well, I can't change the source branch for the PR. As my work isn't finished yet, I'm not ready to open a new one. 
But my code is on our github, so you can access it.

For docker with oracle, I work with https://hub.docker.com/r/sath89/oracle-12c/.
In order for this to work, launch the docker without SID / service name. After the database is initialized, connect with sql developer and create a user sequelize (or another).
And then change https://github.com/sequelize/sequelize/blob/master/test/config/config.js.

The only important point, is that the schema has to be EMPTY. (SELECT * FROM user_tables should return nothing), that's why you must create a user before launching tests or everything will fail.

**Comment by ggrimbert** [comment]
Found the problem.

You call a findAll without passing an order. https://github.com/sequelize/sequelize/blob/master/test/integration/include/findAll.test.js#L137

It works with MsSql as it internally does an order by id, but Oracle doesn't. So the results of the FindAll may (or not), be order correctly for the test.

The fix is to add an order.

I will check all tests to be sure the an order by clause has been setted for findAll.
