### ISSUE TITLE
afterDestroy not triggered for associations

### ISSUE THREAD

**Issue by andreabianco** [sequelize/sequelize#7093]
Hello! I noticed that afterDestroy hook is not triggered for associated model. 
In my case, I have an association 1:1 and I expect to receive the afterDestroy hook for each involved model.
I follow the documentation and I add the property ```jshooks:true``` but nothing changed.

```js
var Model1 = sequelize.define('Model1', {
 ...
 associate: function(models) {
  Model1.hasOne(models.Model2, {
	onDelete: 'cascade',
	hooks: true
  });
 })
})
```

I expected to receive the hook for Model1 and Model2 but I receive the afterDestroy hook only for Model1. Why?

Did I made a mistake in my configuration?

Dialect:__ mysql
Database version:5.6
Sequelize version:3.19.3

**Comment by sushantdhiman** [comment]
You need to use `individualHooks: true`, Please look here https://github.com/sequelize/sequelize/issues/6938 for more info

**Comment by andreabianco** [comment]
Hi @sushantdhiman, thanks for the reply. I'm using `individualHooks: true` and it's not working.
```js
return Model1
    .destroy({
      where: {
        id: req.query.ids
      },
      individualHooks: true
    })
```

If I don't use bulkDestroy, it's working as expected.
```js
return Model1
    .findById(req.params.id)
    .then(function(model1) {
      if (!model1) {
        return res.sendStatus(404);
      }

      return model1.destroy();
    })
```

**Comment by sushantdhiman** [comment]
@andreabianco You need the `afterBulkDestroy` (as mentioned in linked issue)

**Comment by sushantdhiman** [comment]
individualHooks should work, It could be the case nothing actually being updated in your query, can you confirm ?

**Comment by andreabianco** [comment]
In the database the rows in main table and the associated model are deleted. The hooks is working for the main model (Model1) but it's noto working for the associate model (Model2)
