### ISSUE TITLE
Double hasMany through possible?

### ISSUE THREAD

**Issue by justinpincar** [sequelize/sequelize#7099]
Hi, I'm trying to figure out how to do a double hasMany through.

User hasMany Projects hasMany Invoices hasMany CostCenters

I know I could define each relationship individually and then use includes to do eager loading. Is there some way to express User.hasMany(CostCenters)?

**Comment by sushantdhiman** [comment]
I suppose you are talking about a feature like this https://github.com/sequelize/sequelize/issues/3845, Its currently not possible and you have to do nested includes

**Comment by justinpincar** [comment]
Yeah that's basically the same issue - thanks for the prompt reply.
