### ISSUE TITLE
How to query with many table's associations without foreign key

### ISSUE THREAD

**Issue by AntSworD** [sequelize/sequelize#7104]
My company DBA didn't allow use foreign key，I need connect tables by my codes.
Can I include other tables without create foreign key?

**Comment by sushantdhiman** [comment]
You can use `constraints:false` on relationships

We have a dedicated docs section on this topic http://docs.sequelizejs.com/en/v3/docs/associations/#enforcing-a-foreign-key-reference-without-constraints

**Comment by DerangedMind** [comment]
Updated URL:

http://docs.sequelizejs.com/manual/tutorial/associations.html#enforcing-a-foreign-key-reference-without-constraints

Though, might be nice if there was something to help redirect you on that 404 page. I'm sure I'm not the only one that got stuck on it.  😄

**Comment by cirosantilli** [comment]
Until doc links break again: https://sequelize.org/master/class/lib/model.js~Model.html#static-method-hasMany

**Comment by WikiRik** [comment]
If you are using v6, you can also use this one; https://sequelize.org/v6/class/lib/model.js~Model.html#static-method-hasMany
