### ISSUE TITLE
Instance.decrement losing precision in big numbers

### ISSUE THREAD

**Issue by pedrobranco** [sequelize/sequelize#7112]
## What you are doing?
When calling `Instance.decrement` to decrement a specific column value, _Sequelize_ internally it uses the `Instance.increment` with the negative value. When converting the value to its negative form it loses precision right [here](https://github.com/sequelize/sequelize/blob/6f9a53bfa542f962e5df1892657d607a2c6318ab/lib/model.js#L3840) (**due to Javascript floating point problem**).

## What do you expect to happen?
For a given big number value `'1123.123456789012345678'` in its _string_ form, I was expecting a query like this:
```sql
UPDATE x = x - '1123.123456789012345678';
```

## What is actually happening?
It is using the `Instance.increment` with the Javascript negative form of the input value:
```sql
UPDATE x = x + '-1123.1234567890124';
```

Example of the JS issue:
```bash
❯ node
> const x = '1123.123456789012345678'; -x
-1123.1234567890124
```

The issue is actually in the negative form of the value. 

I'm willing to add a PR to fix this, but we have 2 choices:
- Fix the interpretation of the negative form of the value (keeping the hack)
- Implement the decrement method in the query interface to use the database subtract operator and to prevent the mutation of the input value (**IMHO** I prefer this one).

__Dialect:__  postgres
__Database version:__ 9.5.4
__Sequelize version:__ 3.23.2

**Comment by sushantdhiman** [comment]
Thanks for properly explaining the issue and following issue template.

You are right (**2**) is better option, we have to support this for other dialects as well, I think common method can be shared.

Please go ahead and add PR with these changes

- Add a generic method which will accept an operator (`+` , `-`) [incrementQuery](https://github.com/sequelize/sequelize/blob/964999dd9919f5557353439e16aef35fe4fa7aa2/lib/dialects/abstract/query-generator.js#L388)
- Compose two versions increment , decrement from generic method based on operator
- Use query generator for increment / decrement directly

If you have any improvement over my proposal, please do let me know :)

**Comment by pedrobranco** [comment]
I've pushed the PR https://github.com/sequelize/sequelize/pull/7118.
