### ISSUE TITLE
Unhandled rejection SequelizeBaseError: deadlock detected

### ISSUE THREAD

**Issue by klimentLambevski** [sequelize/sequelize#7116]
I created custom seed file for seeding my database. Also i have made factories for creating number of model instances.  

```
function createModelFactory(model, mapper) {
  return function(data, count){
    count = count || 1;
    data = data || {};

    let instances = [];

    for(let i=0; i < count; i++) {
      instances.push(mapper(_.clone(data)));
    }

    return model.bulkCreate(instances).then((createdModels) => {
      return createdModels;
    }, (errors) => {
      return Promise.reject(errors);
    });
  }
}
//user
function mockDataMapper(data) {
  return _.defaults(data, {
    email: faker.internet.email(),
    password: faker.internet.password(),
    name: faker.name.firstName(),
    surname: faker.name.lastName(),
    type: ['VET', 'CUSTOMER'][_.random(0, 1)]
  });
}

const UserFactory = {
  create: createModelFactory(User, mockDataMapper)
};
//patient
const PatientFactory = {
  create: createModelFactory(Patient, patientMockDataMapper)
};

//seed.js
sequelize.sync({force: true}).then(() => {
  UserFactory.create({}, 50).then((users) => {
    _.each(users, (user) => {
      PatientFactory.create({}, 10).then(patients => {
        user.setPatients(patients);
      });
    })
  })
});
```

## What do you expect to happen?
This code should add 10 patients to each user

## What is actually happening?
I get `SequelizeBaseError: deadlock detected` because i debug and realize that all users are trying to associate with all 500 patients and not only 10 patients that are meant for them self's

_Output, either JSON or SQL_

__Dialect:__ postgres
__Database version:__ 9.5
__Sequelize version:__ 3.29.0

**Comment by klimentLambevski** [comment]
```bulkCreate(instances, {returning: true})``` solved the problem

**Comment by tzohpilotl** [comment]
> `bulkCreate(instances, {returning: true})` solved the problem

This only works for Postgres as per the docs

**Comment by papb** [comment]
Hello @tzohpilotl, if you are still experiencing an issue like this one please open a new one an link to this one, thanks!
