### ISSUE TITLE
Could I use Ms SQL on Mac/Ubuntu?

### ISSUE THREAD

**Issue by thearabbit** [sequelize/sequelize#7119]
I base on `Meteor JS and Mongo` (Mac/Ubuntu).
But Now I would like to try use `Ms SQL` with `Meteor JS`.
Could I use/install `Ms SQL` on `Mac/Ubuntu`?

**Comment by sushantdhiman** [comment]
**This is not Stackoverflow**, Please only open issue for discussions, bugs and features related to Sequelize.

>Could I use/install Ms SQL on Mac/Ubuntu?

Yes

**Comment by thearabbit** [comment]
Excuse me for incorrect title.
I would to ask about how to use `sequelize` in `Meteor JS` on `Mac/Ubuntu`.
Thanks for your quick reply. could use provide the Like to install `Ms SQL` on `Mac/Ubuntu`, and then I will try it with `sequelize`.
(sorry my English not good)

**Comment by sushantdhiman** [comment]
Best way to install MSSQL on Ubuntu for development purpose is `docker`, You can find image here https://hub.docker.com/r/microsoft/mssql-server-linux/

Start reading our documentation http://docs.sequelizejs.com, It will give you some overview how you could connect to your database

You can also study https://github.com/sequelize/express-example , a basic working version of express application using Sequelize

I have never used Meteor before so have no idea about particular requirements, but its Node based so there should be no issues using Sequelize with that.

**Comment by thearabbit** [comment]
Thanks again, good job.

**Comment by thearabbit** [comment]
Excuse I base on `Mac`.
I can't run `docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=123456' -p 1433:1433 -d microsoft/mssql-server-linux`
It show
```js
Microsoft(R) SQL Server(R) setup failed with error code 1. Please check the setup log in /var/opt/mssql/log for more information.
```

**Comment by thearabbit** [comment]
OK now it work fine, when I change to strong password.
