### ISSUE TITLE
mysql Executing issues

### ISSUE THREAD

**Issue by webliving** [sequelize/sequelize#7120]
## What you are doing?
when I use sequelize having statement, Executing result is not running?

```js
OrderModel.findAll({
      attributes: [
        'userId',
        [Sequelize.fn('SUM', Sequelize.col('payAmount')), 'sum']
      ],
      order: 'sum DESC',
      group: 'userId',
      having: ['SUM(?)>?', 'payPoints', 15000],
      rollup: true
    }).then(function (result) {
      jsonWrite(res, {
        code: 200,
        data: result
      });
    })
```

## What do you expect to happen?
SELECT `userId`, SUM(`payAmount`) AS `sum` FROM `qc_order` AS `order` GROUP BY userId HAVING AVG  SUM(payPoints)>15000 ORDER BY sum DESC;

## What is actually happening?
_SELECT `userId`, SUM(`payAmount`) AS `sum` FROM `qc_order` AS `order` GROUP BY userId HAVING AVG  SUM('payPoints')>15000 ORDER BY sum DESC;

__Dialect:__ mysql
__Database version: 5.7.11 
__Sequelize version: 3.29.0

**Comment by janmeier** [comment]
Using `?` replacements will escape the value as a string, not as an identifier - So you are trying to sum the string 'payPoints'

```js
.findAll({
  having: {
    $and: [
      sequelize.where(sequelize.fn('SUM', sequelize.col('payPoints')), 15000)
    ]
  }
});
```
