### ISSUE TITLE
Polymorphic 1:n with n:1 relations

### ISSUE THREAD

**Issue by bydooweedoo** [sequelize/sequelize#7125]
Hello everyone,

I have an issue with Sequelize polymorphic associations.

What I want to achieve is a little bit different from the examples from the documentation, or any other issues I found online.

Let's say I have three Models. One called `Entity`, another one called `EntityAttribute` and last one called `AttributeType`.

`Entity` have multiple `EntityAttribute` using `hasMany`.

So far no problem, but then one `EntityAttribute` can be either link to one `AttributeType` or one `Entity`.

## What you are doing?

```js
var Entity = this.sequelize.define('entity', {
  name: Sequelize.STRING,
});

var EntityAttribute = this.sequelize.define('entity_attributes', {
  name: Sequelize.STRING,
  relation: Sequelize.STRING,
  relationId: Sequelize.INTEGER,
  entityId: Sequelize.INTEGER,
});

var AttributeType = this.sequelize.define('attribute_types', {
  type: Sequelize.STRING,
});

Entity.hasMany(EntityAttribute, {
  foreignKey: 'entityId',
  as: 'attributes',
});

EntityAttribute.belongsTo(AttributeType, {
  foreignKey: 'relationId',
  constraints: false,
  as: 'relationAttributeType',
  scope: {
    relation: 'ATTRIBUTE_TYPE',
  },
});

EntityAttribute.belongsTo(Entity, {
  foreignKey: 'relationId',
  constraints: false,
  as: 'relationEntity',
  scope: {
    relation: 'ENTITY',
  },
});
```

## What do you expect to happen?

After I insert some data like this:
```js
Entity.create({
  name: 'BigBox',
  attributes: [{
    name: 'label',
    relationAttributeType: {
      type: 'string',
    },
  }, {
    name: 'content',
    relationEntity: {
      name: 'SmallBox',
    },
  }],
}, {
  include: {
    model: EntityAttributes,
    as: 'attributes',
    include: [{
      model: AttributeType,
      as: 'relationAttributeType',
      required: false,
    }, {
      model: Entity,
      as: 'relationEntity',
      required: false,
    }]
  },
});
```

I want to be able to retrieve data like this:
```js
Entity.findAll({
  include: {
    all: true,
    nested: true,
  }
});
```

And have this kind of result:
```js
[{
  id: 1,
  name: 'BigBox',
  attributes: [{
    id: 1,
    entityId: 1,
    name: 'label',
    relationId: 1,
    relation: 'ATTRIBUTE_TYPE',
    relationAttributeType: {
      id: 1,
      type: 'string',
    },
  }, {
    id: 2,
    entityId: 1,
    name: 'content',
    relationId: 2,
    relation: 'ENTITY',
    relationEntity: {
      id: 2,
      name: 'SmallBox',
    },
  }]
}]
```

## What is actually happening?

Actually I can't find a way to do that. If I use belongsTo the scope will try to goes to the target Model (but I want the scope to apply to the source Model).

And If I add the scope inside `Entity`/`AttributeType` `hasMany` for each, it will not work either.

Sorry I can't copy past the whole code but I put the idea I want to achieve here.

Thanks !!

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 3.28

**Comment by sushantdhiman** [comment]
Sorry but Polymorph is currently not supported, You could achieve it but then you will have to manually do findAll calls to get relations per poly type.

Main discussion https://github.com/sequelize/sequelize/issues/1307

**Comment by sushantdhiman** [comment]
If you are interested in implementing it, there is `$500` bounty on this feature https://github.com/sequelize/sequelize/issues/1307#issuecomment-121407192

**Comment by quintencls-4c** [comment]
It seems to be implement in the mean while, you can find the docs [here](http://docs.sequelizejs.com/en/latest/docs/associations/#scopes)

Example:
```javascript
this.Comment = this.sequelize.define('comment', {
  title: Sequelize.STRING,
  commentable: Sequelize.STRING,
  commentable_id: Sequelize.INTEGER
});

this.Comment.prototype.getItem = function() {
  return this['get' + this.get('commentable').substr(0, 1).toUpperCase() + this.get('commentable').substr(1)]();
};

this.Post.hasMany(this.Comment, {
  foreignKey: 'commentable_id',
  constraints: false,
  scope: {
    commentable: 'post'
  }
});
this.Comment.belongsTo(this.Post, {
  foreignKey: 'commentable_id',
  constraints: false,
  as: 'post'
});

this.Image.hasMany(this.Comment, {
  foreignKey: 'commentable_id',
  constraints: false,
  scope: {
    commentable: 'image'
  }
});
this.Comment.belongsTo(this.Image, {
  foreignKey: 'commentable_id',
  constraints: false,
  as: 'image'
});
```
