### ISSUE TITLE
how to return .findAll()?

### ISSUE THREAD

**Issue by thearabbit** [sequelize/sequelize#7126]
I use `Meteor js`, and then I would like to return data
```js
// Server
Meteor.methods({
    'getData'(){
            User.findAll().then(function (user) {
                return user;
            });
    }
});
```
But don't work, pl help me.

**Comment by sushantdhiman** [comment]
User.findAll() implements Bluebird promise. You so need to return the promise and access the output by hooking `.then` at caller location.

If you dont understand how promise works, Please read http://bluebirdjs.com/docs/why-promises.html

Neither an issue nor a feature request, closing it

**Comment by thearabbit** [comment]
Thanks for your reply, could you example me to `return the result`.
