### ISSUE TITLE
Sequelize is inserting wrong date in datetime column in MySQL

### ISSUE THREAD

**Issue by mayagithub87** [sequelize/sequelize#7127]
Hello everyone, I'm having an issue few days ago, I have a table with a datetime column, and I'm using momentjs for managing dates, when I print in console current date it is just fine, but when I insert the same date in the table it is saved with 5 hours in advance. What can be happening?
Thanks in advance!
Maya

__Dialect:__ mysql
__Database version:__5.6.14
__Sequelize version:__3.29.0

**Comment by sushantdhiman** [comment]
Are you sure your "MySQL server" is not running in UTC? Different from your application server ?

**Comment by mayagithub87** [comment]
Hi sushant, both MySQL server and application server are in the same machine, besides when I request current_timestamp from MySQL server it returns it just OK. Could you help me?

**Comment by mayagithub87** [comment]
Doing some research I have found functions that return the UTC_TIMESTAMP, and that's what is messing up my datetime columns, they are 5 hours in advance wrong. Could anyone tell me how can I change this to go get right date?

**Comment by sushantdhiman** [comment]
You need timezone option, http://docs.sequelizejs.com/en/v3/api/sequelize/#new-sequelizedatabase-usernamenull-passwordnull-options Please read its description carefully.

As an alternative you might want to run your database at same timezone as your application server (but I dont recommend it)

This is neither an issue nor a feature request, so closing it.

**Comment by mayagithub87** [comment]
Sushant could you help? I followed your instructions and my project worked with database configuration timezone: "-05:00". Records now are saved with the correct date, but when I retreive them there are 5 hours in advance, how can I resolve this?
