### ISSUE TITLE
beforeUpsert hook not firing

### ISSUE THREAD

**Issue by nstuyvesant** [sequelize/sequelize#7132]
## What you are doing?
When upserting a user, encrypt the password.

```js
      beforeUpsert(user, fields, fn) {
        if(user.changed('password')) {
          if(!user.password) user.password = config.secrets.session;
          return user.updatePassword(fn);
        }
        fn();
      }
    }
```

## What do you expect to happen?
When calling .upsert(userToUpsert), thought it would fire the beforeUpsert hook. The beforeCreate and beforeUpdate hooks work as expected.

## What is actually happening?
beforeUpsert() is never called. Sorry if I'm doing something incorrectly (am new to sequelize). The beforeUpsert is only briefly mentioned in the docs and struck out on StackOverflow.

__Dialect:__ postgres
__Database version:__ 9.6.1
__Sequelize version:__ 3.29.0

**Comment by sushantdhiman** [comment]
Looks like a bug, have you tried master branch ?

**Comment by sushantdhiman** [comment]
Its not released on `v3` , https://github.com/sequelize/sequelize/pull/6165

I think you have are referring latest documentation which is for `v4`, Please use http://docs.sequelizejs.com/en/v3/ for `v3` docs

**Comment by Cybolic** [comment]
This also seems to be the case on version 4.22.6.
