### ISSUE TITLE
transaction rollback doesn't work.

### ISSUE THREAD

**Issue by aoxls** [sequelize/sequelize#7136]
This is my code:

    models.sequelize.transaction({
        autocommit: false
    }, function (t) {
        return models.classes.destroy({
            where: {  id: id }
        }, { transaction: t }).then(count => {
            return models.teaches.destroy({
                where: {  classid: id }
            }, { transaction: t });
        }).then(() => {
            // I want to roll back
            throw new Error('test');
        });
    }).then(count => {
        // success
    }).catch(err => {
        // fail
    });

the log is below:

    START TRANSACTION;
    Executing (ea7cda41-a165-4175-af06-b6abcce23409): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
    Executing (ea7cda41-a165-4175-af06-b6abcce23409): SET autocommit = 0;
    Executing (default): DELETE FROM `classes` WHERE `id` = 115 AND `masterid` = 10001
    Executing (default): DELETE FROM `teaches` WHERE `classid` = 115
    Executing (ea7cda41-a165-4175-af06-b6abcce23409): ROLLBACK;

but the rollback doesn't work, what's problem?

**Comment by harshithkashyap** [comment]
If you observe your logs, delete statements are not run under transaction. See the [Model.destroy](http://docs.sequelizejs.com/en/v3/api/model/#destroyoptions-promiseinteger) api. `Model.destroy` takes only one argument, i.e options. The following snippet should work.

```javascript
models.sequelize.transaction({
    autocommit: false
}, function (t) {
    return models.classes.destroy({
        where: {  id: id },
        transaction: t 
    }).then(count => {
        return models.teaches.destroy({
            where: {  classid: id },
            transaction: t
        });
    }).then(() => {
        // I want to roll back
        throw new Error('test');
    });
}).then(count => {
    // success
}).catch(err => {
    // fail
});
```

**Comment by aoxls** [comment]
It really works! Thank you very much!
