### ISSUE TITLE
Postgres requires empty arrays to be explicitly cast

### ISSUE THREAD

**Issue by domasx2** [sequelize/sequelize#714]
eg,

``` SQL
CREATE TABLE foo (
   id serial NOT NULL PRIMARY KEY,
   bar integer[]
);
INSERT INTO "foo" ("bar") VALUES (ARRAY[]);
```

will produce error:

```
cannot determine type of empty array at character xx
Explicitly cast to the desired type, for example ARRAY[]::integer[].
```

Currently working around this by converting empty arrays to null before passing values to sequelize. Will look into it when I find the time... Maybe this is pg lib problem?

**Comment by nkreshchenko** [comment]
You can add type of column and it will be saved correctly. For example
```
ARRAY[]::text[]
```
