### ISSUE TITLE
Use of Over clause through sequelize.fn

### ISSUE THREAD

**Issue by getglad** [sequelize/sequelize#7140]
I am trying to figure out the best way to use the 'over clause' (https://msdn.microsoft.com/en-us/library/ms189461.aspx) using `sequelize.fn`.

My raw query might read something like this:
```
SELECT
    Distinct [DataPoint],
    MIN([Value]) OVER (PARTITION BY [DataPoint]) AS [Value MIN],
    MAX([Value]) OVER (PARTITION BY [DataPoint]) AS [Value MAX],
    AVG([Value]) OVER (PARTITION BY [DataPoint]) AS [Value AVG],
    PERCENTILE_DISC(0.5)
        WITHIN GROUP 
        (ORDER BY [Value])
        OVER 
        (PARTITION BY [DataPoint])
        AS MedianCont
    FROM [Table] AS [Table]
    WHERE ([DataPoint]
        IN (
            ...
        )
    )
```
For `MIN`, `MAX`, `AVG`, I could construct an array of objects that look like:
`[sequelize.fn(type, sequelize.col('table.col')), 'colName']`
Combined with a group by object for my distinct datapoint.

But if I also include this `PERCENTILE_DISC` function, I need to make use a window function, else I get a `not contained in either an aggregate function or the GROUP BY clause` error.

Not sure if the sequelize methods would allow me to construct a query this way (short of writing a raw query). If I do need a raw query, is it possible to only make a raw query of the `PERCENTILE_DISC` section?

**Comment by janmeier** [comment]
I think the easiest way is definitely to write a raw query here. You can add raw attributes using `.literal`

```js
.findAll({
  attributes: [
    [sequelize.literal('PERCENTILE_DISC ....'), 'MedianCont']
 ]
});
