### ISSUE TITLE
Unable to close and reopen same instance

### ISSUE THREAD

**Issue by gsccheng** [sequelize/sequelize#7144]
I am doing some seeding and want to reopen a connection to MongoDB after closing it using on the instance (i.e. `sequelize.close`). However, I can't seem to be able to reestablish my connection and make any more calls, and instead keep getting a 
```
Error: ConnectionManager.getConnection was called after the connection manager was closed!
```

I can provide more code later, but is there a good method to re-open a `closed` connection? Thanks.

Dialect: mariadb
Database version: 10.0.21
Sequelize version: 3.29.0

**Comment by sushantdhiman** [comment]
`Sequelize.close` is used for closing pool, you should ideally call it when your application is shutting down or you want to close the pool.

I am afraid there is no method to restart pool effectively, If you are already using pool then you dont need to worry about closing connections, pool should handle that.

But if you want to just close all connections without closing pool, you can use these methods
- [destroyAllNow in v3](https://github.com/sequelize/sequelize/blob/cb6c493daef679b9076d062e86bc45044ca553b1/lib/dialects/abstract/connection-manager.js#L144)
- [clear in v4](https://github.com/sequelize/sequelize/blob/306417f9127b659bbf4b2b671785930984ea16df/lib/dialects/abstract/connection-manager.js#L160)

But these methods will not prevent creating more connections, if your application demands them later on

**Comment by kresimir-franin** [comment]
@sushantdhiman How to reopen them? :)
