### ISSUE TITLE
Why addAssociation returns nested array ?

### ISSUE THREAD

**Issue by thomasthiebaud** [sequelize/sequelize#7145]
__Dialect:__ postgres
__Database version:__ 9.6.11
__Sequelize version:__ 3.30.0

I have this associations

    Customer.belongsToMany(ServiceType, { through: Service });
    ServiceType.belongsToMany(Customer, { through: Service });

and the following code

    const customer = await customerModel.create({/* ... */});
    const serviceType = await serviceTypeModel.findOne({/* ... */});

    const service = await serviceType.addCustomer(customer, { returning: true });

In the documentation it is written that `addAssociation` (singular) is using `bulkCreate`. 

> addAssociation([newAssociation], [options]) -> Promise
[options]	Object	Options passed to through.findAll, bulkCreate and update. Can also hold additional attributes for the join table.

Is it necessary since I'm only adding one association ?

Also if I print `service`, I get 

     [ [ Instance {
           dataValues: [Object],
           _previousDataValues: [Object],
           _changed: [Object],
           '$modelOptions': [Object],
           '$options': [Object],
           hasPrimaryKeys: true,
           __eagerlyLoadedAssociations: [],
           isNewRecord: true } ] ]

Why do I get 2 nested arrays ? In order to access the data using `get` or `toJSON` I need to do something like this

    const json = service[0][0].toJSON();

**Comment by janmeier** [comment]
We are using bulk create because the same code is used for adding one of several associated rows.

The return value is not defined in the API, so I wouldn't rely on it (it can change without notice)
