### ISSUE TITLE
Order by Count of Association (Select, Where, IN, Count)

### ISSUE THREAD

**Issue by iDVB** [sequelize/sequelize#7150]
I have the raw SQL query. I'm trying to see if there is a way to write the same using either 100% Sequelize or part and part literal.

```sql
SELECT * FROM "Video" WHERE "Video".id IN (
        SELECT "VideoTag".video_id 
        FROM "VideoTag" 
        WHERE "VideoTag".video_id!=@item 
        GROUP BY "VideoTag".video_id 
        ORDER BY COUNT(CASE WHEN "VideoTag".tag_id IN (
                SELECT "VideoTag".tag_id 
                FROM "VideoTag" 
                WHERE "VideoTag".video_id=@item) 
                THEN 1 END) DESC);
```

Basically, it a bunch of Videos that have a many-to-many with Tags. I will pass in a video_id and expect that this query will return all the videos that have Tags that this video does, while ordering them, videos with more similar tags at the top.

**Comment by iDVB** [comment]
ok, so I got this working... and could move on... but still interested if there is a way to do it all in pure sequelize and not have to reach for `sequelize.literal`

```javascript
Models.Video.findAll({
  where: {
    id: {
      $in: [sequelize.literal(`SELECT "VideoTag".video_id FROM "VideoTag" WHERE "VideoTag".video_id!='${video.id}' GROUP BY "VideoTag".video_id ORDER BY COUNT(CASE WHEN "VideoTag".tag_id IN (SELECT "VideoTag".tag_id FROM "VideoTag" WHERE "VideoTag".video_id='${video.id}') THEN 1 END) DESC`)],
    },
  },
});
```

**Comment by sushantdhiman** [comment]
You could possibly generate query in the `sequelize.literal` with help of [whereItemQuery](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1777)

But as query becomes more complex beyond normal join etc, this is the correct way to tackle it
