### ISSUE TITLE
Sequelize generates incorrect SQL

### ISSUE THREAD

**Issue by bz0z** [sequelize/sequelize#7163]
Hello. I have a problem in postgresql using ILIKE

```js
    db.companies.findAll({where: {name: {$iLike: "%"+name+"%"}}}).then(function(companies) {
        callback(companies)
    }).catch(function(error) {
        throw error;
    })
```

generates this SQL

SELECT "id", "name", "city", "sphere", "founder", "accountType", "visible", "createdAt", "updatedAt" FROM "companies" AS "companies" WHERE "companies"."name"  '%z%';

and I always get an error because of ILIKE: Possibly unhandled SequelizeDatabaseError: error: schema "companies" does not exist

**Comment by janmeier** [comment]
This works fine for me on both master and latest v3. Try upgrading your sequelize version
