### ISSUE TITLE
Error: Cyclic dependency found. Zemla is dependent of itself.

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#7169]
hello!

I was very surprised today. when see this message 

> Error: Cyclic dependency found. Zemla is dependent of itself.
Dependency chain: File -> Zemla -> Kopnik => Zemla

Can't sequelize create schema in two steps, First create table and Second create relation to avoid cycle limitation?

**Comment by sushantdhiman** [comment]
> Can't sequelize create schema in two steps, First create table and Second create relation to avoid cycle limitation?

No, not yet. But we will accept PR if someone take initiative 

You can use `constraints: false` option when creating associations, to prevent cycles

**Comment by douglasjunior** [comment]
> No, not yet. But we will accept PR if someone take initiative

So, I think it could be tagged as a *Feature Request* .

**Comment by jedwards1211** [comment]
[this is causing problems with `dataloader-sequelize`](https://github.com/mickhansen/dataloader-sequelize/issues/88), either `ModelManager.forEachModel` should not be public API, or the toposorting for schema creation should be done in a separate internal method.

**Comment by papb** [comment]
@jedwards1211 Can you (or someone else) post a SSCCE/MCVE/reprex for OP's error?
