### ISSUE TITLE
Connections don't close

### ISSUE THREAD

**Issue by vixa2012** [sequelize/sequelize#7171]
Hello everyone. Yesterday I used "sequelize": "~3.24.1", "sequelize-cli": "~2.4.0"
I have script which started by cron each 5 minutes and load some statistics to database.
**Each query open new mysql connection and never close it.**

<img width="334" alt="2017-01-30 22 41 36" src="https://cloud.githubusercontent.com/assets/1618041/22463983/57c49ed0-e7bd-11e6-9ba5-97013220ab30.png">

After I saw that bug I downloaded "sequelize": "~4.0.0-2",  "sequelize-cli": "~2.5.1"

Now I have new bug.
Count of connection is less then yesterday, but this connections never close too.

On my script finish I make sequelize.close(); but all connections is also open in mysql.

<img width="322" alt="2017-01-31 14 01 23" src="https://cloud.githubusercontent.com/assets/1618041/22464088/ccf30c82-e7bd-11e6-913c-620d93e2ab14.png">

Please help me, how I can close all connections after script finish?

This is my configuration
<img width="599" alt="2017-01-31 14 03 14" src="https://cloud.githubusercontent.com/assets/1618041/22464164/220ec12a-e7be-11e6-985f-eeac5d70a8fe.png">

and this is my script
<img width="728" alt="2017-01-31 14 03 46" src="https://cloud.githubusercontent.com/assets/1618041/22464174/2ddd30c2-e7be-11e6-804c-31e58668ea3a.png">

**Comment by sushantdhiman** [comment]
This comment will address your issue https://github.com/sequelize/sequelize/issues/7144#issuecomment-275027512

As you are using `v4-0-2`, you still want to use `destroyAllNow` as pooling has been changed in `master` but not released yet.

**Comment by vixa2012** [comment]
Maybe I doing not right something, please help me. Write an example how I have to use method **clear()**

<img width="1040" alt="2017-01-31 14 11 28" src="https://cloud.githubusercontent.com/assets/1618041/22464591/496e33d4-e7c0-11e6-9c76-ae121c174770.png">

**Comment by sushantdhiman** [comment]
As I said in my comment, clear method is not available on `v4-0-2`

To use these methods you need to get connection manager object, like

```js
sequelize.connectionManager.destroyAllNow();
```

**Comment by vixa2012** [comment]
Okay I did it. But also got error.

<img width="1194" alt="2017-01-31 14 33 34" src="https://cloud.githubusercontent.com/assets/1618041/22465080/ad75fcca-e7c2-11e6-9978-3ff40f2bea61.png">

**Comment by sushantdhiman** [comment]
Which version v4 ?

**Comment by vixa2012** [comment]
Viktors-MBP:adserver_redis viktorchukhlov$ ./node_modules/.bin/sequelize -v

Sequelize [Node: 6.9.4, CLI: 2.5.1, ORM: 4.0.0-2]

**Comment by sushantdhiman** [comment]
`connectionManager` should be defined, hmm try console log `sequelize.connectionManager`

**Comment by vixa2012** [comment]
Please see my config, maybe I don't write something.

<img width="776" alt="2017-01-31 14 41 50" src="https://cloud.githubusercontent.com/assets/1618041/22465255/748e864c-e7c3-11e6-88db-808065c61537.png">


This is cron script
<img width="976" alt="2017-01-31 14 42 30" src="https://cloud.githubusercontent.com/assets/1618041/22465264/8510baee-e7c3-11e6-9cd4-d3bd42d62f61.png">

**Comment by sushantdhiman** [comment]
`IdleTime`, is should be `idle`

**Comment by vixa2012** [comment]
Changed to idle but error also has

**Comment by sushantdhiman** [comment]
Now connection should automatically released no need to call close or anything else

**Comment by vixa2012** [comment]
No, if I don't close connection script don't finish.
And connections do not released(( As I can see count of connections increase

**Comment by sushantdhiman** [comment]
```js
sequelize.connectionManager.pool.destroyAllNow();
```

**Comment by vixa2012** [comment]
Ok thats has not errors
 models.sequelize.connectionManager.pool.destroyAllNow();

But connections count increase too((
<img width="343" alt="2017-01-31 14 58 42" src="https://cloud.githubusercontent.com/assets/1618041/22465733/da4afd74-e7c5-11e6-9659-604e234e2448.png">

I run my script
<img width="458" alt="2017-01-31 14 59 54" src="https://cloud.githubusercontent.com/assets/1618041/22465762/f405a020-e7c5-11e6-9d90-cfba0053e968.png">

After finish
<img width="338" alt="2017-01-31 15 00 21" src="https://cloud.githubusercontent.com/assets/1618041/22465770/0163b91e-e7c6-11e6-904c-441dfe903d17.png">

<img width="472" alt="2017-01-31 15 02 52" src="https://cloud.githubusercontent.com/assets/1618041/22465858/6464dce6-e7c6-11e6-8262-8db0d92c68ee.png">


I tried every thing/))

**Comment by sushantdhiman** [comment]
Please use 

```sql
show status where `variable_name` = 'Threads_connected';
```

which show actual connection connected at that time. The status you are currently using indicate connection thought the session, which will always increase.

This also means, there was actually no problem form the beginning. But also indicate v4 is far better in properly utilizing connections :laughing:

**Comment by vixa2012** [comment]
Ohhh thank you very much. Its really work.

**Comment by sushantdhiman** [comment]
Great :smile:
