### ISSUE TITLE
Load-balancing using sequelize

### ISSUE THREAD

**Issue by shriramshankar** [sequelize/sequelize#7176]
Is load balancing possible using sequelize? I want to be able to separate the read/write queries and direct the read queries to the read-only database.

**Comment by sushantdhiman** [comment]
Load balancing is not in our scope, but we do offer [replication](https://github.com/sequelize/sequelize/blob/master/test/integration/replication.test.js#L16)

You can define two database config in `replication.read` and `replication.write` options for Sequelize constructor config. You can define any number of read replicas (config accept array). All your read queries will be sent to read replicas by round robin scheduling technique.

**Comment by shriramshankar** [comment]
Once I define the replication options for Sequelize, does it replicate the data too?

**Comment by sushantdhiman** [comment]
ORM should never be in charge of populating read / write replicas, it should be managed by your db service provider. Have you used replicas before?

**Comment by shriramshankar** [comment]
This will be my first time using the replication option in Sequelize. Our database replicas will be populated by the service provider. I just want to redirect the reads to these replicas. Thanks for your pointers.

**Comment by sushantdhiman** [comment]
Great
