### ISSUE TITLE
Regression in affected rows reporting for updates

### ISSUE THREAD

**Issue by jharting** [sequelize/sequelize#7184]
## What you are doing?

Imagine having a controller that handles updates to a given resource, e.g:

```
PUT /users/493824

{
    name: "Jozef",
    surname: "Hartinger",
    notes: [{
        id: "foo",
        text: "Lorem ipsum dolor sit amet..."
    }, {
        id: "bar"
        text: "Lorem ipsum dolor sit amet..."
    }]
}
```

Note that the controller is supposed to return 404 if the resource does not exist. A different method is used for creating resources. The controller could be implemented like this:

```js
sequelize.transaction(function (transaction) {
    return User.update(user, {
        where: {
            id: user_id
        },
        transaction: transaction,
        limit: 1
    }).then(function (count) {
        if (count === 0) {
            return res.status(404).end();
        } else {
            // run a query to update/create notes
            // left out for brevity
        }
    });
});
```

The "affected rows" count is used to determine if the entity exists in the database and if it does then another query is issued to update related entities.

## What do you expect to happen?
The expectation is for the "affected rows" count value to be 1 if there is an entity in the User table with the matching id or 0 if there is none.

## What is actually happening?
This works as expected with all versions of sequelize until 3.28.0

With 3.28.0 and later the count is 0 even if the User entity exists in the database as long as no data was actually changed (the data in the update query are the same as the data already in the database).

I traced this down further and found that https://github.com/sequelize/sequelize/commit/4f95f176eba4a7ad7c71108dd48955884d16eb6b is the breaking commit. The commit addresses https://github.com/sequelize/sequelize/issues/6310

In the issue @janmeier originally talked about making this the default behavior in 4.0 which sounds reasonable to me. Unfortunatelly, the behavior was also backported to 3.28.0 where it is also enabled by default without any configuration option to switch to the old behavior. This breaks our app.

__Dialect:__ mysql
__Database version:__ 10.1.20
__Sequelize version:__ 3.28.0

**Comment by janmeier** [comment]
Yeah, that was a wrong merge on my part, it should definitely be hidden behind a flag on v3.

**Comment by jharting** [comment]
@janmeier does `config.dialectOptions.foundRows` sound OK to you as the name of the config property?

**Comment by janmeier** [comment]
Sounds good to me

**Comment by sdotson** [comment]
Any updates on this? I'm still seeing this in the latest 3.x.x version.

**Comment by jharting** [comment]
I am using
```
dialectOptions: {
    flags: ''
}
```
