### ISSUE TITLE
Supprot options.returning for other dialects

### ISSUE THREAD

**Issue by rusmichal** [sequelize/sequelize#7185]
Documentation:
```
Update multiple instances that match the where options. The promise returns an array with one or two elements. The first element is always the number of affected rows, while the second element is the actual affected rows (only supported in postgres with options.returning true.)
```
When we can expected support options.returning for mysql and other?

I have `update` function like that. In response I get array: `[1, null]` I want to get updated object.
```
updateById: function(body, id) {
        return db.application.upsert({
            name: body.name,
            package_name: body.package_name,
            version_name: body.version_name,
            version_code: body.version_code,
            os: body.os,
            status: body.status
          }, {
            returning: true,
            plain: true,
            where: {
                id: id
            }
        });
    },
```

Dialect: mysql 
Database version: 5.6.31-0ubuntu0.15.10.1 - (Ubuntu)
Sequelize version: 3.30.1

**Comment by janmeier** [comment]
Whenever it's implemented in mysql ;)

Postgres and mssql has special syntax (`UPDATE foo SET bar = 42 RETURNING *`), that actually returns the new values of the rows. The same goes for inserts, where it returns any default values + ids for all inserted rows, which mysql doesn't.

So it's simply a limitation of mysql et. al., not sequelize
