### ISSUE TITLE
Empty instance._changed object in afterUpdate hook after someScope.update()

### ISSUE THREAD

**Issue by VanTudor** [sequelize/sequelize#7187]
## What you are doing?
I'm trying to log update events in an app. This relies heavily on ```afterUpdate``` hooks. I'm updating through an organization scope with 

```
yield someScope.update(updateInput, {
  where: {
    id,
  },
  returning: true,
  user: ...,
  individualHooks: true,
//  updatedFields: _.keys(updateInput),
});
```

## What do you expect to happen?
I expect to see the changed fields in the update event as when using ```.save()``` on an model instance, i.e. the model instance having a ```_changed``` object with properties set to ```true``` or ```false``` accordingly; the ```change()``` method also returning changed fields.

## What is actually happening?
The instance available in ```beforeUpdate()``` hooks has an empty ```_changed``` object; The ```change()``` method also reports no changed fields.

### Sidenote1:
If I update a single field, the ```options.fields``` array in ```afterUpdate()``` lists the changed field along with two other fields that have not been changed and that are not featured in the SQL UPDATE statement, although I might be missing something.

### Sidenote2:
My current workaround is to add a ```updatedFields: _.keys(updateInput)``` property on the  second parameter of ```someScope.update()```, which gets passed further to options parameter in the hook, but it seems logical that I could access changed fields, despite update being of ```bulkUpdate``` type.

__Dialect:__ postgres
__Sequelize version:__ 3.25.0

**Comment by mkozjak** [comment]
I too get some 'cached' fields that are not supposed to be in `fields` (Sidenote1).
