### ISSUE TITLE
Feature Deprecate Raw Plain Object `{raw: '...'}`

### ISSUE THREAD

**Issue by mkaufmaner** [sequelize/sequelize#7188]
## What you are doing?
```js
Model.findAll({order: [{raw: 'id DESC; SELECT username, password FROM user; SELECT NULL '}]});
```

## What do you expect to happen?
Sequelize would throw an error saying unknown structure.  This logic resides in the abstract query-generator.js inside the method `quote()` at line 619.

## What is actually happening?
This relates to SQL injection which has been started here https://github.com/sequelize/sequelize/pull/7160#partial-pull-merging .  Instead, if a developer wants to represent something as raw, they should use `Sequelize.literal`.

__Dialect:__ any
__Database version:__ any
__Sequelize version:__ 4

**Comment by felixfbecker** [comment]
Totally.

**Comment by mkaufmaner** [comment]
@janmeier @felixfbecker I believe this should also drop support for raw replacements.

For example, ```javascript
{where: ['name IN (?)', [1, 'test', 3, "derp"]]
```

**Comment by felixfbecker** [comment]
yeah, looks like the above can be used as a raw query (with SQL injection potential) just as well and can be expressed with operators instead

**Comment by mkaufmaner** [comment]
This has been rectified.
