### ISSUE TITLE
Allow the use of `WITH INDEX` when including relationships (joins) in MSSQL

### ISSUE THREAD

**Issue by renatoargh** [sequelize/sequelize#7194]
This is a feature request. I have a scenario where I need to force the use of a specific index in my database like the following:

```
SELECT
  *
FROM 
  MyTable AS [myTable]
INNER JOIN 
  HugeTable AS [hugeTable] WITH (INDEX(hugeTable_IDX)) -- note this line
    ON [myTable].[fooId] = [hugeTable].[fooId]
```

My suggestion is to add the property `index` to the include objects like so:

```
MyTable.findAll({
   where: { field: 'foobar' },
   include: [{
     model: HugeTable,
     as: 'bars',
     index: 'hugeTable_IDX'
  }]
})
```

I have googled for it and found nothing, also I browsed through the open/closed issues and again I found nothing regarding this issue. If I missed something please point me to the right resources. Thank you for the project, sequelize rules! :)

**Comment by tvaamorim** [comment]
Just came across the same problem

**Comment by danielfsousa** [comment]
up
