### ISSUE TITLE
instance.updateAttributes updates numerous db rows

### ISSUE THREAD

**Issue by puzlpix** [sequelize/sequelize#7202]
## What you are doing?
Finding one model instance and updating it.

    'use strict';

    module.exports = function(sequelize, DataTypes) {
      var RoomUser = sequelize.define('RoomUser', {
        roomId: {
          type: DataTypes.INTEGER,
          validate: { notEmpty: true }
        },
        userId: {
          type: DataTypes.INTEGER,
          validate: { notEmpty: true }
        },
        isCurrentRoom: {
          type: DataTypes.BOOLEAN,
          validate: { notEmpty: true }
        },
        lastDeliveredMessageId: {
          type: DataTypes.INTEGER
        },
        lastSeenMessageId: {
          type: DataTypes.INTEGER
        }
      }, {
        classMethods: {
          associate: function(models) {
            // associations can be defined here
          }
        }
      });
      return RoomUser;
    };

    RoomUser.findOne({
      where: {
        userId: data.userId,
        roomId: data.roomId
      }
    })
    .then(function(roomUser) {

      console.log(util.inspect(roomUser.get({plain: true})));

      if (roomUser.isCurrentRoom === true) {
        roomUser.lastSeenMessageId = data.newestMessageId;
        console.log('isCurrentRoom = true. roomUser: ' + util.inspect(roomUser.get({plain: true})));
        return roomUser.updateAttributes({
          lastSeenMessageId: data.newestMessageId
        });
      }
    });

## What do you expect to happen?
The single instance returned by findOne should update a single db row, the row with userId=1 and roomId=4,  with a new lastSeenMessageId.

## What is actually happening?
All db rows with roomId = 4 are updated. The userId from the instance is ignored.

Here is the sql statement for findOne() :
Executing (default): SELECT `roomId`, `userId`, `isCurrentRoom`, `lastDeliveredMessageId`, `lastSeenMessageId`, `createdAt`, `updatedAt` FROM `RoomUsers` AS `RoomUser` WHERE `RoomUser`.`userId` = 1 AND `RoomUser`.`roomId` = 4;

Here is the instance returned by findOne():
isCurrentRoom = true. roomUser: { roomId: 4,
   userId: 1,
   isCurrentRoom: true,
   lastDeliveredMessageId: null,
   lastSeenMessageId: 85,
   createdAt: 2017-01-30T23:28:52.000Z,
   updatedAt: 2017-02-05T20:46:44.000Z }

Here is the sql statement from updateAttributes():
Executing (default): UPDATE `RoomUsers` SET `lastSeenMessageId`=86,`updatedAt`='2017-02-05 20:47:10' WHERE `roomId` = 4

The instance updateAttributes is called on is missing userId=1 in the WHERE clause that was used in the findOne that returned the instance.

mysql  Ver 14.14 Distrib 5.6.27, for osx10.11 (x86_64)
"sequelize": "3.30.1",
"sequelize-cli": "2.5.1",

**Comment by harshithkashyap** [comment]
@puzlpix What is the primaryKey in `RoomUser` table? `Instance.updateAttributes` uses the primaryKey field for the where part since we already know the primaryKey field.
