### ISSUE TITLE
Sequelize Scope multiple sub queries from other tables

### ISSUE THREAD

**Issue by IbraheemAlSaady** [sequelize/sequelize#7205]
I want to do something like the following query 
```mysql
    select id, username from user where id in 
    (select DISTINCT user_id from items where item.id in (1,2,3) and user_id not in (
    select DISTINCT blocked_user_id from user_blocks where blocked_by_user_id = 4)
    )
```
I have the **user** model, **block** model, and **items** model. all properly linked and associated.

What I have now is the following scope in the user model: 
```node

filter: function (id, items) {
            return {
                attributes: ['id', 'username'],
                where: {
                    id: {
                        in: [sequelize.literal(`select DISTINCT item.user_id from items as item 
                           where item.id in (${items.join()}) and item.user_id not in ( 
                           select DISTINCT blocked.blocked_user_id from user_blocks as blocked where          
                           blocked.blocked_by_user_id = ${id})`)]
                    }
                },
                raw: true
            };
        }

```
I don't like the above although it's working perfectly, possibility to sql injection, and also not nice to look at.

Is there anyway I can do the above in the Sequelize way? perhaps getting scopes from other models?
Thanks

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
