### ISSUE TITLE
Class method nod found

### ISSUE THREAD

**Issue by vixa2012** [sequelize/sequelize#7206]
Hello everyone.
I created the model and added classMethods

<img width="727" alt="2017-02-06 12 58 57" src="https://cloud.githubusercontent.com/assets/1618041/22644661/106f0396-ec6c-11e6-9e60-054d73cba59d.png">

But when i'm trying to use it, i got error
<img width="1258" alt="2017-02-06 13 00 13" src="https://cloud.githubusercontent.com/assets/1618041/22644715/4e6ae138-ec6c-11e6-9460-9cf228abbf75.png">

What is not right?

**Comment by vixa2012** [comment]
I did it by another way

<img width="969" alt="2017-02-06 14 02 13" src="https://cloud.githubusercontent.com/assets/1618041/22646563/abe80652-ec75-11e6-9abd-428c4812716b.png">
<img width="569" alt="2017-02-06 14 02 21" src="https://cloud.githubusercontent.com/assets/1618041/22646562/abe78a2e-ec75-11e6-8acb-54b2c2dd1f9c.png">

**Comment by sushantdhiman** [comment]
@vixa2012 Please follow the issue template, now I dont know which version you are using 😛
