### ISSUE TITLE
queryInterface.removeColumn() function actually drop my sqlite table

### ISSUE THREAD

**Issue by darrenchiu** [sequelize/sequelize#7208]
## What you are doing?
Not sure if it is just me or my setup is incorrect. I am trying to drop a column from a table in migrations. While it works well on mysql but it's actually dropping my whole table for sqlite database.

```js
  up: function (queryInterface, Sequelize) {
    return [
      queryInterface.removeColumn('ReimbursementForms', 'projectId')
    ];
  },
```

## What do you expect to happen?
I would expect it works the same as mysql, which drop the column only

## What is actually happening?
It drop my whole table...

## Note for investigation
I notice that my IDE is able to recognize the correct addColumn method can be hinted/referenced correctly while removeColumn does have a separate implementations for different dialect. Would that be sequelize is referencing the wrong dialect implementations?

Dialect: sqlite
Sequelize [Node: 6.9.1, CLI: 2.5.1, ORM: 3.29.0]

**Comment by harshithkashyap** [comment]
@darrenchiu  We have tests for `queryInterface.removeColumn`
https://github.com/sequelize/sequelize/blob/master/test/integration/query-interface.test.js#L610-L742, so its not a problem here.

`queryInterface.removeColumn` returns promise but you seem to return `[]`. If you need to return multiple promises, return `Promise.all`. 
Verify that it works with `return queryInterface.removeColumn('ReimbursementForms', 'projectId')`;

**Comment by sushantdhiman** [comment]
> Would that be sequelize is referencing the wrong dialect implementations?

We inherit SQLite dialect from MySQL dialect rather than Abstract dialect, that might be the reason

I would like to see the SQL generated by `removeColumn` @darrenchiu

**Comment by darrenchiu** [comment]
Hi all, sorry for all the confusions. @harshithkashyap's reply resolved my solution completely. Thanks a lot. Although I am still wondering why returning a list does work in some cases...
