### ISSUE TITLE
Cant get an Array of Objects parsed

### ISSUE THREAD

**Issue by danielfelipe113** [sequelize/sequelize#7209]
## What you are doing?
Hi, I'm trying to get an array of objects from the DB.

```js
// model
  checklist: {
      type: DataTypes.ARRAY(DataTypes.JSON),
      allowNull: true,
      defaultValue: []
    }
.....
//query

return Note.findAll({
    order: '_id ASC',
    attributes: [
      '_id',
      'checklist'
 ]
})
```

## What do you expect to happen?
An object like this:

```js
"checklist": [
    {checked: true, text: "Shortening"},
    {checked:true, text: "Margarine"},
    {checked:false, text: "Canned Stewed Tomatoes"},
    {checked:true, text: "Onions"}
  ]
```

## What is actually happening?
I'm getting an array of strings

_Output, JSON_
```js
"checklist": [
    "{\"checked\":true,\"text\":\"Shortening\"}",
    "{\"checked\":true,\"text\":\"Margarine\"}",
    "{\"checked\":false,\"text\":\"Canned Stewed Tomatoes\"}",
    "{\"checked\":true,\"text\":\"Onions\"}"
  ]
```

##Extra
I tried with a getter and setters, for get it works but when I try to update an element it throws an error.
Thanks!

__Dialect:__ postgres
__Sequelize version:__ 3.23.6

**Comment by sushantdhiman** [comment]
Have you tried that against `master`, I dont think we have any tests for `Array(JSON)`. So this might be a bug :)

**Comment by danielfelipe113** [comment]
@sushantdhiman Thanks! I updated sequelize and even this don't fixed my issue it makes my code better. For this issue I get some help on  stackoverflow and post a solution:  [http://stackoverflow.com/questions/42073837/cant-get-an-array-of-objects-parsed](Solution).

There is a little question in the final edit section if you can see it.

Thank you so much!
