### ISSUE TITLE
Many to Many failing with 'is not associated to' when trying to associate entries?

### ISSUE THREAD

**Issue by ajmas** [sequelize/sequelize#7210]
I am having a problem with my many to many configuration with Sequelize, where it complains that ``site_article_keyword is not associated to article_keyword``. The code below represents a minimal test case to try to understand what I am doing wrong (I hoped to provide something smaller, but this is what I have). I am using bluebird for the Promise API.

My main goal here is to list all the keywords associated with an article, though the next step was to also provide functionality for returning both the article and associated keywords. At the moment, I trying to resolve the first goal.

```
    const Sequelize = require('sequelize');
    
    var sequelize = new Sequelize(undefined, undefined, undefined, {
        dialect: 'sqlite',
        storage: './mydatabase',
    });
    
    const SiteArticle = sequelize.define('site_article', {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        ownerId: {
            type: Sequelize.INTEGER,
            field: 'owner_id'
        },
        title: Sequelize.STRING
            // other fields omitted
    }, {
        timestamps: true
    });
    
    const ArticleKeyword = sequelize.define('article_keyword', {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        name: Sequelize.STRING,
        language: Sequelize.STRING
            // other fields omitted
    }, {
        timestamps: true
    });
    
    const SiteArticleKeyword = sequelize.define('site_article_keyword', {
        siteArticleId: {
            type: Sequelize.INTEGER,
            field: 'site_article_id',
            references: {
                model: SiteArticle,
                key: 'id'
            }
        },
        articleKeywordId: {
            type: Sequelize.INTEGER,
            field: 'article_keyword_id',
            references: {
                model: ArticleKeyword,
                key: 'id'
            }
        }
        // other fields omitted
    }, {
        timestamps: true
    });
    
    (ArticleKeyword).belongsToMany(
        SiteArticle, { through: SiteArticleKeyword, as: 'SiteArticle' });
    
    (SiteArticle).belongsToMany(
        ArticleKeyword, { through: SiteArticleKeyword, as: 'ArticleKeyword' });
 ```   

That's the model defined, now for trying to create the source and destination entries, that I then want to associate. The failure happens on the line where I call ``ArticleKeyword.findAll()``:

```
    sequelize.sync({}).then(function() {
    
        // populate some data here
    
        let siteArticle;
    
        SiteArticle.create({
            ownerId: 1,
            title: 'hello world'
        }).then(function(entry) {
            siteArticle = entry;
            console.log('site article: ', JSON.stringify(entry, undefined, 2));
    
            return ArticleKeyword.findOrCreate({
                where: {
                    name: 'keyword1',
                    language: 'en'
                }
            });
        }).spread(function(entry, success) {
            console.log('article keyword: ', JSON.stringify(entry, undefined, 2));
            return siteArticle.addArticleKeyword(entry);
        }).spread(function(entry, success) {
            console.log('site article keyword: ', JSON.stringify(entry, undefined, 2));
    
            const siteArticleId = 1;
            const language = 'en';
    
            return ArticleKeyword.findAll({
                where: {
                    language: language,
                },
                include: [{
                    model: SiteArticleKeyword,
                    where: {
                        siteArticleId: siteArticleId
                    }
                }]
            });
        }).then(function(articleKeywords) {
            if (articleKeywords) {
                console.log('entries: ', JSON.stringify(articleKeywords, undefined, 2));
            } else {
                console.log('entries: ', 'none');
            }
        }).catch(function(error) {
            console.log('ERROR: ', error);
        }.bind(this));
    
    }).catch(function(error) {
        console.log(error);
    });
```
I am basing my code on the '[Mixin BelongsToMany][1]' example in the Sequelize documentation.

Any ideas?

Using Sequelize 3.27.0 and NodeJS 6.7.0.

  [1]: http://docs.sequelizejs.com/en/latest/api/associations/belongs-to-many/#mixin-belongstomany

**Comment by ajmas** [comment]
Resolved. The answer would appear to be that it isn't associated, because it is the association. Thus the find should become:

```
return ArticleKeyword.findAll({
    where: {
        language: language,
    },
    include: [{
            model: SiteArticle,
            as: 'SiteArticle',
            siteArticleId: siteArticleId
        }]
    });
```

BTW would it be possible to clarify this in the documentation?

**Comment by shuaibq3** [comment]
having same issue. sequelize version: 4.38.0, node version: 8.11.3

Models: 
`//Group model
  module.exports = (sequelize, DataTypes) => {
  const Group = sequelize.define(
    "Group",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false
      }
    },
    { freezeTableName: true, tableName: "Group" }
  );

  Group.associate = function(models) {
    Group.belongsToMany(models.Camera, {
      through: models.CameraGroupUserMapping,
      as: "groupCameras",
      foreignKey: 'groupId',
      otherKey: 'cameraId',
      onDelete: "CASCADE"
    });
  };

  return Group;
};`

`//camera model
  module.exports = (sequelize, DataTypes) => {
  const Camera = sequelize.define(
    "Camera",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false
      },
      address: {
        type: DataTypes.STRING
      },
      lat: {
        type: DataTypes.FLOAT
      },
      lon: {
        type: DataTypes.FLOAT
      }
    },
    { freezeTableName: true, tableName: "Camera", timestamps: false }
  );

  Camera.associate = function(models) {
    Camera.belongsToMany(models.Group, {
      through: models.CameraGroupUserMapping,
      as: "cameraGroups",
      foreignKey: 'cameraId',
      otherKey: 'groupId',
      onDelete: "CASCADE"
    });
  };

  return Camera;
};`

`//CameraGroupUserMapping model
  module.exports = (sequelize, DataTypes) => {
  const CameraGroupUserMapping = sequelize.define(
    "CameraGroupUserMapping",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      status: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
    }
    },
    { freezeTableName: true, tableName: "CameraGroupUserMapping" }
  );

  CameraGroupUserMapping.associate = function(models) {
    // associations can be defined here
    CameraGroupUserMapping.belongsTo(models.Camera, {
      type: "FOREIGN KEY",
      name: "cameraId",
      references: {
        table: "Camera",
        field: "id"
      },
      onDelete: "CASCADE"
    });

    CameraGroupUserMapping.belongsTo(models.Group, {
      type: "FOREIGN KEY",
      name: "groupId",
      references: {
        table: "Group",
        field: "id"
      },
      onDelete: "CASCADE"
    });
  };

  return CameraGroupUserMapping;
};
`

query:

`models.Camera.findAll({
    include: [{
        model: models.Group,
        as: "cameraGroups"
      },
    ]
  });`

error:  "Group is not associated to Camera!"

any idea what i am doing wrong?
