### ISSUE TITLE
To have control MySQL foreign key name

### ISSUE THREAD

**Issue by apapacy** [sequelize/sequelize#7213]
## What you are doing?
Create foreign key with name 'defaultCurrenciId' (for migration up/down comfort)

```sql
  KEY `defaultCurrencyId` (`defaultCurrencyId`),
  CONSTRAINT `Countries_ibfk_1` FOREIGN KEY (`defaultCurrencyId`) REFERENCES `Currencies` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMEN
```

## What do you expect to happen?
CONSTRAINT `defaultCurrencyId`

## What is actually happening?
 CONSTRAINT `Countries_ibfk_1`

__Dialect:__ mysql
__Sequelize version:__ 3.30.1

**Comment by sushantdhiman** [comment]
Its coming soon https://github.com/sequelize/sequelize/pull/7108 in `v4`
