### ISSUE TITLE
FindALL adding the child filter criteria to the main query

### ISSUE THREAD

**Issue by rishirajgarg** [sequelize/sequelize#7214]
# **What you are doing?**

Below is our use case, we are trying to add a filter condition for the child model (shown below in bold) under Sequelize Query but the Equivalent Postgres query is returning a query having filter both at child (sub query) and parent level (main query).

Please help us to know if this is a normal behaviour of Sequelize.

**Sequelize Query**

Db.models.accounts.findAll({offset:0,limit:2,order:"account_number DESC",where:{account_number:4521},**include[{"model":Db.models.ibx,"where":{"ibx_code":{"$in":["SV11","SV2"]**}}]})

# **What do you expect to happen?**

**Converted Query in Postgres**

SELECT "account".*,
  "ibxes"."id"        AS "ibxes.id",
  "ibxes"."ibx_code"  AS "ibxes.ibx_code",
  "ibxes"."gatewayaccountId" AS "ibxes.gatewayaccountId"
FROM
  (SELECT "account"."account_number",
    "account"."account_type_code",
    "account"."parent_ucm_id",
    "account"."account_status",
    "account"."streamlined_flag",
    "account"."account_name",
    "account"."region",
    "account"."id"
  FROM "gatewayaccount" AS "account"
  WHERE "account"."account_number" = '4521'
  AND (SELECT "gatewayaccountId"
    FROM "ibx" AS "ibx"
    WHERE ("ibx"."gatewayaccountId" = "account"."id"
    **AND "ibx"."ibx_code"    IN ('SV11', 'SV2'**)) LIMIT 1 ) IS NOT NULL
  ORDER BY account_number DESC LIMIT 2 OFFSET 0
  )              AS "account"
INNER JOIN "ibx" AS "ibxes"
ON "account"."id"       = "ibxes"."gatewayaccountId"
ORDER BY account_number DESC;

# What is Actually Happening

**Converted Query in Postgres**
"**AND "ibxes"."ibx_code" IN ('SV11', 'SV2')** condition added in the parent query'

SELECT "account".*,
  "ibxes"."id"        AS "ibxes.id",
  "ibxes"."ibx_code"  AS "ibxes.ibx_code",
  "ibxes"."gatewayaccountId" AS "ibxes.gatewayaccountId"
FROM
  (SELECT "account"."account_number",
    "account"."account_type_code",
    "account"."parent_ucm_id",
    "account"."account_status",
    "account"."streamlined_flag",
    "account"."account_name",
    "account"."region",
    "account"."id"
  FROM "gatewayaccount" AS "account"
  WHERE "account"."account_number" = '4521'
  AND (SELECT "gatewayaccountId"
    FROM "ibx" AS "ibx"
    WHERE ("ibx"."gatewayaccountId" = "account"."id"
    **AND "ibx"."ibx_code"    IN ('SV11', 'SV2'**)) LIMIT 1 ) IS NOT NULL
  ORDER BY account_number DESC LIMIT 2 OFFSET 0
  )              AS "account"
INNER JOIN "ibx" AS "ibxes"
ON "account"."id"       = "ibxes"."gatewayaccountId"
**AND "ibxes"."ibx_code" IN ('SV11', 'SV2')**
ORDER BY account_number DESC;

**Comment by rishirajgarg** [comment]
Hello Folks..Please help me to fix it or provide some feedback on this..

**Comment by janmeier** [comment]
Hello @rishirajgarg - Please relax! Everyone here "works" on the project in their free time

Try adding something similar to 

```js
where:{
  "$ibx.ibx_code$ ":{"$in":["SV11","SV2"]}
}
```

And look at similar issues asking the same question

**Comment by sudheerj** [comment]
Just a small question,Is it mongoDB kind of chain access will be supported in sequelize? Because I didn't find anywhere in the documentation on it.

For example,

`DB.models.people.findAll({where:{"$post.title$":{"$in":["Title is learn sequelize"]}}});`

The current approach we followed is
`DB.models.people.findAll({include[{model:Db.models.post,where:{"title":{"$in":["Title is learn sequelize"]}}}]});`
