### ISSUE TITLE
how to assign the subquries values to parent in sequelize? 

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [sequelize/sequelize#7215]
My sql query is:
SELECT prop.hp_builders_id, builder.builders_name, count(prop.hp_builders_id) total_properties,
count(hp_property_inhibition_status_id)
 FROM hp_property prop
inner join hp_builders builder on prop.hp_builders_id =builder.builders_id
where prop.hp_builders_id in (
SELECT distinct p.hp_builders_id FROM hp_property p  where p.is_builder_best=1 and p.hp_city_id=5)
AND prop.hp_city_id=5
group by prop.hp_builders_id;

 so i tried like this
hp_property .findALL({
where : {
 hp_city_id:5
 }
include:[{
model:hp_builders 
required:true
  }] ,
group By:['hp_builders_id']
});

so first i want to execute the sub query of 
SELECT distinct p.hp_builders_id FROM hp_property p  where p.is_builder_best=1 and p.hp_city_id=5
and after that i want to assign the  hp_builders_id to this parent subquery .

how is it possible/any ideas ?

__Dialect:__ mysql
__Sequelize version:__ 2.0.2

**Comment by janmeier** [comment]
You can write the sub query in plain SQL, but otherwise there is no other way to do it currently

```js
where: {
  hp_builders_id: {
    $in: sequelize.literal('...')
  }
}
```

https://github.com/sequelize/sequelize/issues/2325
