### ISSUE TITLE
defaultValue on `id` type `uuid` in MySQL does not work

### ISSUE THREAD

**Issue by dinusuresh** [sequelize/sequelize#7218]
Tried the following:

```
const uuid = require('uuid/v4');
-
-
id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: function() {
          return uuid.v4();
        }
      }
```

and

```
id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.UUIDV4
      }
```

both on seeding (sequelize db:seed:all) throw the following error:
`Seed file failed with error: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value`

Seed file code:
```
return queryInterface.bulkInsert('question_banks', [{
      name: 'Jane Doe',
      description: 'Awesome Person',
    }, {
      name: 'John Doe',
      description: 'Magnificent Man.'
    }], {});
  }
```

_Versions:_
Sequelize: 3.30.1
sequelize-cli: 2.5.1
mysql-server: 5.7
npm mysql: 2.13

**Comment by ecolman-ap** [comment]
Bump.  Running into this issue as well.

**Comment by dinusuresh** [comment]
@ecolman-ap  Currently I am generating uuid's manually before record creation as a work around to this problem.

**Comment by uvizhe** [comment]
I'd like this to get resolved. Seems like it's the same problem as #2263

**Comment by CamHenlin** [comment]
This is still an issue

**Comment by Habtesoft** [comment]
first install uuid package
```npm install uuid --save```
then call to the package as follows
```const uuid  = require('uuid')```
then use it 
```id: uuid.v4()```

**Comment by ephys** [comment]
Let's redirect newer comments for using `DataTypes.UUIDV4` in migrations here https://github.com/sequelize/sequelize/issues/13224
