### ISSUE TITLE
Improving 'X is not associated to Y' error text?

### ISSUE THREAD

**Issue by ajmas** [sequelize/sequelize#7221]
I have recently had to deal with an error of type 'X is not associated to stress_event Y', and curious as to whether there are one or many interpretations of the error. For example:

-  'table X is not associated to table Y'
-  'no entries in X are not associated to entries in Y'
-  'table X is not associated to table Y, since table X is an association'

Or maybe something else? May it be worth looking at which errors are resulting in the most questions and seeing if clarifying the text may help in their interpretation?

Additionally, would there be any objection to adding a wiki section for dealing with common error types and allowing the community to add details  on how to resolve?

**Comment by janmeier** [comment]
These error messages have already been improved somewhat in v4 (see https://github.com/sequelize/sequelize/blob/8cbd3750f5f8034cc53096de6ddb43593ba1c983/lib/model.js#L563), with hints about missing alias etc.

The wiki should already be editable by everyone, and you are welcome to improve it! :)

**Comment by ajmas** [comment]
I'll start by creating a place holder: https://github.com/sequelize/sequelize/wiki/Error-Messages-(Sequelize-3.x)
