### ISSUE TITLE
can't use limit with sqlserver2008r2?

### ISSUE THREAD

**Issue by szy0syz** [sequelize/sequelize#7233]
```javascript
 "dependencies": {
    "sequelize": "^3.30.2",
    "sequelize-auto": "^0.4.18",
    "tedious": "^1.14.0"
  }
```

```javascript
var T_BAS_BillType = sequelize.import('./models/T_BD_PaymentType')
T_BAS_BillType.findAll({limit: 10}).then(function(rows) {
    console.log(rows);
})
```

Unhandled rejection SequelizeBaseError: Invalid usage of the option NEXT in the FETCH statement.

hello, my db is sqlserver2008r2. i see "[FIXED] Improved offset and limit support for SQL server 2008 #5616", and have any options?

**Comment by L3V147H4N** [comment]
I'm using SQL SERVER 2012 and it's not working either, from what I gather the problem is that the query using OFFSET and NEXT is not adding the ORDER BY clause and according to the MSSQL Doc OFFSET should always be used with an ORDER BY but I don't know if this is an issue of Sequelize or Tedious

**Comment by szy0syz** [comment]
@L3V147H4N thank you.
i have solved this issue with `sequelize.query()`.
