### ISSUE TITLE
findOne with include v3->v4

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#7236]
## What you are doing?
With sequelize v3 the following works as expected.
```js
...
var models = req.app.get('models')
  models.Session.findOne({
    where: {
      id: payload.session
    },
    include: [
      {
        model: models.Login,
        include: [
          {
            model: models.User,
            where: {id: {$col: 'Session.activeUserId'}}
          }
        ]
      }
    ]
  })
  .then(function(session) {...}
...
```

## What do you expect to happen?
```
SELECT `Session`.`id`, `Session`.`activeUserId`, `Session`.`loginId`,
`Login`.`id` AS `Login.id`,
`Login.Users`.`id` AS `Login.Users.id`,
`Login.Users`.`loginId` AS `Login.Users.loginId`,
FROM `Sessions` AS `Session`
LEFT OUTER JOIN `Logins` AS `Login` ON `Session`.`loginId` = `Login`.`id`
INNER JOIN `Users` AS `Login.Users` ON `Login`.`id` = `Login.Users`.`loginId` AND `Login.Users`.`id` = `Session`.`activeUserId`
WHERE `Session`.`id` = '...';
```

## What is actually happening?
With sequelize v4 the sql statement looks like:
```
SELECT `Session`.`id`, `Session`.`activeUserId`, `Session`.`loginId`,
`Login`.`id` AS `Login.id`,
`Login->Users`.`id` AS `Login.Users.id`,
`Login->Users`.`loginId` AS `Login.Users.loginId`,
FROM `Sessions` AS `Session`
LEFT OUTER JOIN ( `Logins` AS `Login`
INNER JOIN `Users` AS `Login->Users` ON `Login`.`id` = `Login->Users`.`loginId` AND `Session`.`activeUserId` )
ON `Session`.`loginId` = `Login`.`id`
WHERE `Session`.`id` = \'...\';
```
and it throws
```
SequelizeDatabaseError: Unknown column 'Session.activeUserId' in 'on clause'
```

What do I have to change from v3 to v4?

__Dialect:__ mysql
__Database version:__ XXX
__Sequelize version:__ XXX

**Comment by harshithkashyap** [comment]
You are looking for an `on` instead of `where`. Have a look at this [unit test](https://github.com/sequelize/sequelize/blob/master/test/unit/sql/generateJoin.test.js#L293-L304)

**Comment by ro70** [comment]
@harshithkashyap I appreciate your help. But I don't get it with these unit tests. How do I have to change the code above?
Unfortunately I can't access the slack.

**Comment by harshithkashyap** [comment]
@ro70 If you observe your sql query, the `INNER JOIN` takes place in a sub query. Because of parens around subQuery which is valid, it is evaluated first and the subQuery does not know what `Session.activeUserId` and hence your error. Can you verify your associations/findAll query?
If you really want the intended result, Login table INNER JOINed with User table has to happen first in a subquery, the result of which you'll JOIN with Session table.
