### ISSUE TITLE
[Advice] change `hasOne` to a more semantic structure

### ISSUE THREAD

**Issue by xialvjun** [sequelize/sequelize#7238]
At today's(2017-02-12) version, on the database structure, `A.belongsTo(B)`  euqals to `B.hasOne(A)`.

But I think it's not that precise.

Be more semantic, I think `B.hasOne(A)` means `B is A's owner and one B to one A, not 0 A or 2 A`. 

1. To prevent `0 A or 2 A`, we should put the foreign key on `B.A_id` rather than `A.B_id`. 

2. To show `B is A's owner`, we should make a unique index on `B.A_id`.

~~And there is another 1:1 relationship --- `is`, like `class extends`, `Cow.is(Animal)`. We should put the foreign key on `Cow.Animal_id`. Eh, it seems `is` is totally the same as `hasOne`~~

**Comment by smithaitufe** [comment]
It is very annoying to see issues closed by this stale bot when the issues have not been addressed.
