### ISSUE TITLE
Sequelize Default Promise Behaviour

### ISSUE THREAD

**Issue by shahromil** [sequelize/sequelize#7239]
Hello,

I am having an issue with promise behavior of Sequelize. I want to execute a query which is giving me total count of records in a table and in a immediate next line based on that count, I want to perform some operation. 

The problem is, due to promise pattern of sequelize, I have to write every code into .then() which i want to execute in sequential manner. 

Is there any way, I can avoid promise behavior of sequelize as and when it's needed ?

Cheers,
Romil

**Comment by m4rcelofs** [comment]
Not sure this is related to sequelize at all, but you could use async/await (currently enabled with the `--harmony_async-await` flag on node v7.4, probably released on node v8) or, if you are feeling a bit crazy, something like [promise-to-callback](https://www.npmjs.com/package/promise-to-callback).

**Comment by janmeier** [comment]
Everything io related in node is asynchronous - you can wrap it up in pretty abstractions, but there is no way around it
