### ISSUE TITLE
Updating relative to column

### ISSUE THREAD

**Issue by kevinmartin** [sequelize/sequelize#724]
I am trying to create a tree structure. In doing so, I need to update columns relative to themselves and possibly other columns. I dont want to do a query to get the values then update based on those values because the values may change before the update queries go through.

I've tried several variations of the following. The source code eventually lead me to the impossibility of doing anything like this. I've got a temporary fix on my branch, but not sure if it's a "good" fix.

Code:

``` javascript
Model.update({
    rght: 'rght + 2'
}, conditions);
```

Expected:

```
UPDATE `accounts` SET `rght`=`rght`+2 WHERE ...
```

Actual:

```
UPDATE `accounts` SET `rght`='[object Object]' WHERE ...
```

**Comment by gorangajic** [comment]
Is there any reason why there is still no increment/decrement methods on the model ? I have copied Model.prototype.update method and played a bit with it so it's possible to create one.

I would like to create pull request and implement that but I am not that much familiar with the codebase and not sure what half the things do in that update method :D
