### ISSUE TITLE
Does Sequelize support the MySql JSON Data Type?

### ISSUE THREAD

**Issue by hussainb** [sequelize/sequelize#7241]
MySql has introduced the JSON data type as seen in the below documentation link:

[https://dev.mysql.com/doc/refman/5.7/en/json.html](https://dev.mysql.com/doc/refman/5.7/en/json.html)

I cound not find any documentation in Sequelize to use the same. If it exists, kindly share the documentation link.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/4727
