### ISSUE TITLE
Can't exclude original association in belongsToMany when querying from table

### ISSUE THREAD

**Issue by lukeify** [sequelize/sequelize#7244]
## What you are doing?

I have two models: `projects` and `users`, and are joined in a many-to-many relationship with a `projectsusers` table. Model definitions:

```js
Project.belongsToMany(models.user, { through: 'projectuser' });
[..]
User.belongsToMany(models.project, { through: 'projectuser' });
```

I want to retrieve all projects for a specific user by email address, **while excluding** the `users` table entirely.

```
    models.project.findAll({
        include:[{
            model: models.user,
            where: { emailAddress: 'admin@caduceus.com' }
        }]
    }
``` 

## What do you expect to happen?

I want an array of just the projects' table, **with no `users` or `projectsusers` table.**

## What is actually happening?

The above query outputs:

```
[{"id":1,
"name":"bldg",
"description":"bldg",
"users":[...]}]
```

I haven't been able to find a way to exclude the users table so far.

__Dialect:__ mssql
__Sequelize version:__ 4

**Comment by harshithkashyap** [comment]
Have you tried setting `attributes: []`? 
```javascript
models.project.findAll({
        include:[{
            attributes: []
            model: models.user,
            where: { emailAddress: 'admin@caduceus.com' }
        }]
    }
```

**Comment by saudpunjwani101** [comment]
attributes: [] does not removes the attributes from the select query. It doesn't just shows it in the result.

**Comment by lassmann** [comment]
I am having the same issue

**Comment by JanMesaric** [comment]
Experiencing the same issue.
