### ISSUE TITLE
How to get value before update in beforeUpdate hook

### ISSUE THREAD

**Issue by yifei2043** [sequelize/sequelize#7245]
## What you are doing?
I have a model ftest, i want to get the data value before update in beforeUpdate hook, but the data i got is the data going to be update.For example, the value of first_name field value is 'cheng', i want to update the filed to 'wang', in beforeUpdate hook i want to get 'cheng' by user._previousDataValues.firstName, but the output value is 'wang'. Am i wrong?
// code here
```javascript
app.get('/test', function(req, res) {
    dao.update({ firstName: 'wang' }, { where: { id: 1 }, individualHooks: true }).catch(function(err) { console.log(err.message) });
    res.send("Hello World");
});

module.exports = function(sequelize, datatype) {
    return sequelize.define('ftest', {
        firstName: {
            type: datatype.STRING,
            field: 'first_name' // Will result in an attribute that is firstName when user facing but first_name in the database
        },
        lastName: {
            type: datatype.STRING
        }
    }, {
        hooks: {
            beforeUpdate: function(user, options) {
                console.log(user._previousDataValues.firstName);
            },
        }
    });
};
```

**i traced the dataValues and _previousDataValues in beforeUpdate, they are identical...**

## What do you expect to happen?
I wanted the value before updated 'cheng'

## What is actually happening?
_But the output was 'wang'!_

__Dialect:__ mysql 
__Database version:__ 5.7.17
__Sequelize version:__ 3.30

**Comment by yifei2043** [comment]
i traced the dataValues and _previousDataValues in beforeUpdate, they are identical...

**Comment by harshithkashyap** [comment]
@yifei2043 in `dao.update`, is `dao` an instance or model? If its a model, the previousDataValues will be same as the current one as sequelize doesn't know the existing record.

**Comment by yifei2043** [comment]
@harshithkashyap  thanks for your help. dao is a model, i changed the dao to an instance, and finally i got the value before updated.
**Thanks a lot!**
