### ISSUE TITLE
Caching layer?

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#7249]
Why is there still no support/mech for a caching layer? I came across an issue from 2013 that stated it was being planned?

**Comment by sushantdhiman** [comment]
I dont think sequelize core will ever include caching layer
- caching requirements are different for different applications
- hard to maintain
- kinda goes beyond ORM scope
- buggy and hard to reproduce issues

You can try https://github.com/mickhansen/dataloader-sequelize
