### ISSUE TITLE
Trouble with creating and nested asociations

### ISSUE THREAD

**Issue by adampetrie** [sequelize/sequelize#7252]
## What you are doing?
I have 4 models - Flyer, FlyerPage, RuleSet and Rule. I am trying to create a Flyer, an associated RuleSet and it's associated Rule inside of a single create statement. I am following this example from the docs: http://docs.sequelizejs.com/en/latest/docs/associations/#creating-with-associations

Models:
```js
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Flyer = sequelize.define('Flyer', {
  }, {
    classMethods: {
      associate: function(models) {
        Flyer.hasMany(models.FlyerPage);
        Flyer.hasOne(models.RuleSet);
      }
    }
  });
  return Flyer;
};

'use strict';
module.exports = function(sequelize, DataTypes) {
  var FlyerPage = sequelize.define('FlyerPage', {
  }, {
    classMethods: {
      associate: function(models) {
        FlyerPage.belongsTo(models.Flyer);
        FlyerPage.hasOne(models.Rule);
      }
    }
  });
  return FlyerPage;
};

'use strict';
module.exports = function(sequelize, DataTypes) {
  var RuleSet = sequelize.define('RuleSet', {
  }, {
    classMethods: {
      associate: function(models) {
        RuleSet.hasMany(models.Rule);
        RuleSet.belongsTo(models.Flyer);
      }
    }
  });
  return RuleSet;
};

'use strict';
module.exports = function(sequelize, DataTypes) {
  var Rule = sequelize.define('Rule', {
  }, {
    classMethods: {
      associate: function(models) {
        Rule.belongsTo(models.RuleSet);
        Rule.belongsTo(models.FlyerPage);
      }
    }
  });
  return Rule;
};

models.Flyer.create({
  id: 456,
  FlyerPages: [{id: 1}],
  RuleSet: {
    Rules: [
      {
        flyer_page_id: 1
      }
    ]
  }
},
{
  include: [
    models.FlyerPage,
    {
      association: models.RuleSet,
      include: [models.Rule]
    }
  ]
}).then(function(flyer) {
    console.log(flyer);
});

```

## What do you expect to happen?
I want to have a model instance with its related RuleSet and a single associated Rule

## What is actually happening?

```js
TypeError: Cannot read property 'name' of undefined
      at conformInclude (node_modules/sequelize/lib/model.js:291:45)
      at node_modules/sequelize/lib/model.js:266:15
      at Array.map (native)
      at conformOptions (node_modules/sequelize/lib/model.js:265:37)
      at Model.build (node_modules/sequelize/lib/model.js:1757:5)
      at Model.create (node_modules/sequelize/lib/model.js:1815:15)
      at Context.<anonymous> (test/lib/personalizedflyer.js:50:18)
```

Any help is appreciated. Thanks!

__Dialect:__ mysql
__Sequelize version:__ 3.29.0

**Comment by Aukhan** [comment]
Are you sure the associate method on the models is being called after all the models have read/imported by sequelize ?

**Comment by adampetrie** [comment]
I have been able to create flyers with flyer pages and rulesets as well as rulesets with rules, just not everything all at once.

That leads me to believe the issue is somewhere in:

```js
{
  include: [
    models.FlyerPage,
    {
      association: models.RuleSet,
      include: [models.Rule]
    }
  ]
}
```

**Comment by Aukhan** [comment]
Looking into the source code and docs it looks like the `association` key is expecting an `Instance of Association` whereas you are passing an `Instance of model` hence the error.
If you look here http://docs.sequelizejs.com/en/latest/docs/associations/#creating-with-associations
the docs suggest that you capture the association reference like
`var Product.User = Product.belongsTo(User);`
and then pass `Product.User` as the value to your `association` key.

In your case Im assuming these are all separate files so you could try something like
`models.Flyer.associations.RuleSet` 
hopefully the name of the RuleSet association is RuleSet else you can console.log and find it out.

**Comment by adampetrie** [comment]
Thanks @Aukhan! You were correct. The following created all the records I wanted:

```js
models.Flyer.create({
      id: 123,
      FlyerPages: [{id: 1},{id: 2},{id: 3}],
      RuleSet: {
        Rules: [{
          flyer_page_id: 1,
          flyer_position: 1
        }]
      }
    },  
    {
      include: [
        models.FlyerPage,
        {
          association: models.Flyer.associations.RuleSet,
          include: [models.Rule]
        }
      ]
    })
```

**Comment by sureshdmavericks** [comment]
Hi @Aukhan , I'm having the same issue. I did what you did above.. But I'm having the below error..
"Error: Include unexpected. Element has to be either a Model, an Association or an object."

**Comment by gsqrt2** [comment]
Regarding the error, you have probably defined the association with an alias. Try to `console.log(SUserLogin.associations);` and you will find the correct the valid association name.
The problem is that, even with the error fixed, the nested association will still not be created in my tests.
