### ISSUE TITLE
Performance issues with few results and no includes

### ISSUE THREAD

**Issue by stefanobider** [sequelize/sequelize#7256]
With Postgres dialect, a simple query with `findAll()` on a single table with only 3 results seems to take a long time.
Here is the query created by Sequelize:
```
SELECT "artist_id" AS "artistId", "name", "label", "relevance", "catalogue", "source", "source_id" AS "sourceId" 
FROM "artists" AS "artists" 
WHERE "artists"."label" LIKE '%mozart%' 
ORDER BY "artists"."relevance" DESC 
LIMIT 3
```

And a comparison of times:
- Outside node, using Valentina Studio (db management tool): 5 ms
- Without Sequelize, directly with `pg`: 193 ms
- With Sequelize, `query()`: 359 ms
- With Sequelize, `findAll()` (also with `raw : true`) : 373ms

From 5 to 373 seems quite the leap for such a simple query. Any insights?

**Comment by itaied246** [comment]
I can't explain how Valentina Studio is so fast, but the difference between native`pg` library and `sequelize` library seems OK.
Think about the mapping it has to make from the execution to SQL query and then back to a JSON.
So if performance is an issue here, I would point out the comparison between`pg` and `sequelize`, but I don't think that DB management tools are relevant here.

**Comment by sushantdhiman** [comment]
We have a tool for performance testing https://github.com/sushantdhiman/sequelize-benchmark , if you like you can benchmark using this tool

```
With Sequelize, query(): 359 ms
With Sequelize, findAll() (also with raw : true) : 373ms
```

raw and full response difference isn't very big, so I dont think we can improve much here. If you can find a bottleneck, we are happy to accept PR with fix
