### ISSUE TITLE
incorrect hstore parsing when using multiple PG databases

### ISSUE THREAD

**Issue by nelapsi13** [sequelize/sequelize#7257]
## What you are doing?
we have two PG databases which have different OIDs for hstore type.
Then PG connection manager connects first time it reads these OIDs from database and stores them in dataTypes.HSTORE.types.postgres.oids. Then it connects to the second database it uses OIDs from the first connection and therefore does not parse HSTORE columns (and treats them as strings).

```js
const co = require('co')
const dbpool = require('./server/db/pool')

function getFirstConnection() {
        return dbpool.getConnectionByAppId(1).sequelize
}
function getSecondConnection() {
        return dbpool.getConnectionByAppId(5).sequelize
}

const oidQuery = "SELECT oid FROM pg_type WHERE typtype = 'b' AND typname IN ('hstore')"
const hstoreQuery = 'SELECT wordlists FROM "Apps" limit 1'

function * proof(db) {
  let res = yield db.query(oidQuery, {type: db.QueryTypes.SELECT})
  console.log("oid is ", res[0].oid)
  res = yield db.query(hstoreQuery, {type: db.QueryTypes.SELECT})
  console.log("parsed type of hstore is ", typeof res[0].wordlists)
}

co(function* () {
  yield proof(getFirstConnection())
  yield proof(getSecondConnection())
})
```

## What do you expect to happen?
parsed type should always be object

## What is actually happening?
parsed type on second connection is string

_Output_
oid is  8278719
parsed type of hstore is  object
oid is  16388
parsed type of hstore is  string

__Dialect:__ postgres
__Database version:__ first: 9.4.8 second: 9.4.1
__Sequelize version:__ current master is affected

seems like following patch should fix the problem

```
diff --git a/lib/dialects/postgres/connection-manager.js b/lib/dialects/postgres/connection-manager.js
index a8f08b8..c53e4d0 100644
--- a/lib/dialects/postgres/connection-manager.js
+++ b/lib/dialects/postgres/connection-manager.js
@@ -145,9 +145,9 @@ class ConnectionManager extends AbstractConnectionManager {
       }   
 
       // oids for hstore and geometry are dynamic - so select them at connection time
-      if (dataTypes.HSTORE.types.postgres.oids.length === 0) {
-        query += 'SELECT typname, oid, typarray FROM pg_type WHERE typtype = \'b\' AND typname IN (\'hstore\', \'geometry\', \'geography\')';
-      }
+      // we have to reload them on every new connection as it is possible for OIDs to be different on different databases
+      // we can't even cache them based on "hostname+port+database" as it may point to smth like PGBOUNCER which in turn can proxy real connection to different databases for the same credentials
+      query += 'SELECT typname, oid, typarray FROM pg_type WHERE typtype = \'b\' AND typname IN (\'hstore\', \'geometry\', \'geography\')';
 
       return new Promise((resolve, reject) => {
         connection.query(query)
@@ -162,8 +162,8 @@ class ConnectionManager extends AbstractConnectionManager {
               type = dataTypes.postgres.GEOGRAPHY;
             }   
 
-            type.types.postgres.oids.push(row.oid);
-            type.types.postgres.array_oids.push(row.typarray);
+            type.types.postgres.oids = [row.oid];
+            type.types.postgres.array_oids = [row.typarray];
 
             this._refreshTypeParser(type);
           })  

```

**Comment by sushantdhiman** [comment]
Above solution although works for different connections when used one after another directly, but fails in other scenarios because Sequelize is not storing OIDs per connection basis.

So this will fails randomly

Pool Conn 1 (9.4) // all sequelize method will use oids for 9.4
Pool Conn 2 (9.4.8) // all sequelize method will use oids for 9.4.8
Pool Conn 3 (9.4) // all sequelize method will use oids for 9.4

What is actually happening here is you are using most recent connection's oids, which is not always correct for multi database version. When a method run it can try to use invalid OIDs for a connection of different database version

I suggest you either create two instance for Sequelize or bring both database engine to same versions.
