### ISSUE TITLE
Nested includes generate column name in SQL that exceeds PostgreSQL column max length

### ISSUE THREAD

**Issue by l4harry** [sequelize/sequelize#7262]
## What you are doing?
I am creating a SELECT query with joins across several tables using nested includes. The result set from the generated SQL query returns column names that exceed the default 63-character limit in PostgreSQL. The result of this is that data is missing in the result set.

```js
User.findById(id, {
  include: [{
    model: FooBarFooBar,
    include: [{
      model: BarBarBarBar,
      include: [{
        model: FooFooFooFoo,
        include: [{
          model: FooBarBazFooBarBaz,
          include: [{
            model: What
          }]
        }]
      }]
    }]
  }]
});
```

The generated SQL query statement is correct and succeeds in returning data for the nested includes until the character limit is reached.  The max column name length in PostgreSQL is NAMEDATALEN-1 bytes. NAMEDATALEN is 64 in a default PostgreSQL installation. Changing the column name length requires recompiling PostgreSQL with a new value for NAMEDATALEN.

## What do you expect to happen?
There should be data returned for:
"User" 
"User.FooBarFooBar"
"User.FooBarFooBar.BarBarBarBar"
"User.FooBarFooBar.BarBarBarBar.FooFooFooFoo"
"User.FooBarFooBar.BarBarBarBar.FooFooFooFoo.FooBarBazFooBarBaz"
"User.FooBarFooBar.BarBarBarBar.FooFooFooFoo.FooBarBazFooBarBaz.What"

## What is actually happening?
Data is returned for:
"User" 
"User.FooBarFooBar"
"User.FooBarFooBar.BarBarBarBar"
"User.FooBarFooBar.BarBarBarBar.FooFooFooFoo"
"User.FooBarFooBar.BarBarBarBar.FooFooFooFoo.FooBarBazFooBarBaz"
"User.FooBarFooBar.BarBarBarBar.FooFooFooFoo.FooBarBazFooBarBaz." (<-- Note this is 63 characters long)

__Dialect:__ postgres
__Database version:__ 9.5
__Sequelize version:__ 3.30.1

**Comment by sushantdhiman** [comment]
Known issue https://github.com/sequelize/sequelize/issues/2084
