### ISSUE TITLE
fire and forget raw query?

### ISSUE THREAD

**Issue by BardiaAfshin** [sequelize/sequelize#7263]
I'm looking for running a raw query against RedShift and not waiting for it's result.

Does this library support that?

**Comment by harshithkashyap** [comment]
@BardiaAfshin If you are looking for sequelize to not process the result, there isn't such a feature. However you can still do it at your application level. Fire the query and don't attach then/catch blocks to it.

**Comment by sushantdhiman** [comment]
@BardiaAfshin `Sequelize.query` dont then / catch it, we will still perform operation on result.

If you want to go at more low level `Sequelize.connectionManager.getConnection()` get raw connection and  perform query on internal connection object directly
