### ISSUE TITLE
Sequelize.DATE(6)

### ISSUE THREAD

**Issue by semicoyoung** [sequelize/sequelize#7265]
hello,

## here is my schema

```
let schema = dbs.DATARC.define('hehe', {
  firstAccessTime: {
    type: Sequelize.DATE(6),
    field: 'first_access_time'
  },
}, {
  tableName: 'hehe'
} 
```
 
## and data store in my mysql database is like this: 
```
2015-12-26 10:35:37.980000
```

 ## but when I update the first_access_time, I logging it out ,and it looks like this:

```
Executing (default): UPDATE `hehe` SET `first_access_time`='2015-12-26 10:35:37.020' WHERE `first_access_time` >= '2015-12-26 10:35:37'
```
## the where options value should like this: 
```
UPDATE `hehe` SET `first_access_time`='2015-12-26 10:35:37.020' WHERE `first_access_time` >= '2015-12-26 10:35:37.030'
```

are there something wrong with that?
thanks.

**Comment by sushantdhiman** [comment]
@semicoyoung Please follow issue template next time, I have no idea which sequelize version you are working with.

It should have been fixed with https://github.com/sequelize/sequelize/pull/6709#discussion_r83587674
