### ISSUE TITLE
How to update and increment?

### ISSUE THREAD

**Issue by novoxudonoser** [sequelize/sequelize#7268]
I do:
```
return models.myModel.findById (model_id ).then( my_model => {
  return my_model.decrement(['some_fild'], { by: 2 })
 });
```
I get:
```
SELECT "id", "some_fild" FROM "myModel" AS "myModel" WHERE "myModel"."id" = '1';
UPDATE "myModel" SET "some_fild"="some_fild" + -2 WHERE "id" = '1' RETURNING *
```

I want: (only update query)
```
UPDATE "myModel" SET "some_fild"="some_fild" + -2 WHERE "id" = '1' RETURNING *
```
How can I do this?

**Comment by sushantdhiman** [comment]
`decrement / increment` works only on instance, there is no model level method. Although you could use update

```js
Model.update({ field: sequelize.literal('field + 2') }, { where: { id: model_id } });
```

**SSCCE**

```js
const A = sequelize.define('A', {
  field: Sequelize.INTEGER
});

A.sync()
.then(() => A.create({ field: 1 }))
.then(() => A.update({ field: Sequelize.literal('field + 2') }, { where: { id: 1 }}))
.then(() => A.findOne({ raw: true }))
.then(console.log);
```

**Output**
```js
Executing (default): CREATE TABLE IF NOT EXISTS `As` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `field` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`As`)
Executing (default): INSERT INTO `As` (`id`,`field`,`createdAt`,`updatedAt`) VALUES (NULL,1,'2017-02-19 08:36:09.197 +00:00','2017-02-19 08:36:09.197 +00:00');
Executing (default): UPDATE `As` SET `field`=field + 2,`updatedAt`='2017-02-19 08:36:09.213 +00:00' WHERE `id` = 1
Executing (default): SELECT `id`, `field`, `createdAt`, `updatedAt` FROM `As` AS `A` LIMIT 1;
{ id: 1,
  field: 3,
  createdAt: '2017-02-19 08:36:09.197 +00:00',
  updatedAt: '2017-02-19 08:36:09.213 +00:00' }

```

**Comment by arifath** [comment]
@sushantdhiman hallo. i've try on increment
`Model.update({ field: sequelize.literal('field + 2') }, { where: { id: model_id } });`
and its works

but on decrement
`Model.update({ field: sequelize.literal('field - 2') }, { where: { id: model_id } });`
its doesnt works. what am I miss ?

**Comment by predescu** [comment]
@arifath , try 
`Model.decrement(['field', '2'], { where: { id: model_id } });`

http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-decrement

**Comment by arifath** [comment]
@predescu i've tried, but nothing change. different version maybe? mine is 4.23

**Comment by selmansamet** [comment]
_or:_
```javascript
Model.decrement({field: 2}, { where: { id: model_id } })
```
http://docs.sequelizejs.com/manual/instances.html#incrementing

**Comment by ketavchotaliya** [comment]
@predescu Model.decrement function not found, Can you tell me what are the sequalize version?

**Comment by sabarimani-r-xelp** [comment]
I checked sequellize doc. to decrement, we have to give negative value as below

`User.increment({point: -50}, { where: { id: 1 } })`

**Comment by hrabizadeh** [comment]
User.increment("field", {
          by: 1,
          where: {
            id: 1
          });

**Comment by GorgeousPuree** [comment]
> ```js
> User.increment({point: 50}, { where: { id: 1 } })
> ```

Can't I specify which columns to return? Executing this code, it generates `RETURING *` at the end. I found in documentation, that there is `options.returning` boolean parameter, but that's not what I want. In this case I have to make separate query?

**Comment by farhan787-cp** [comment]
Is this not possible to do 
``` js 
User.upsert({ userOtherData, point: Sequelize.literal('point + 1') })
``` 
to increment point by 1 and update user's other data at the same time? 

In SQL, I want to do something like,
```sql
-- Column point has default value 0
INSERT INTO user(data_1, data_2), VALUES (data_1_value, data_2_value) ON DUPLICATE KEY UPDATE  data_1 = data_1_value, data_2 = data_2_value, point = point + 1
```
