### ISSUE TITLE
findOrCreate multiple call issue

### ISSUE THREAD

**Issue by vlakam** [sequelize/sequelize#7271]
## What you are doing?
Multiple call learn method in model provided below.

```js
sequelize.define('Word', {
      word: DataTypes.STRING
  }, {
      classMethods: {
          learn: async function (words) {
              let self = this;
              let result = [];
              for(let iter in words) {
                  let response = await self.findOrCreate({
                      where: {
                          word: words[iter]
                      }
                  });
                  result.push(response[0]);
              }

              return result;
          }
      }
  });
```

## What do you expect to happen?
Sequentional execution

## What is actually happening?
According to log sequelize.js makes many identical insert queries which makes DB hangup.

Executing (5232e3f8-4885-409b-ac77-15b312b9799d): SELECT `id`, `word`, `createdAt`, `updatedAt` FROM `Words` AS `Word` WHERE `Word`.`word` = 'я' LIMIT 1;
Executing (189c3e03-7896-4f6d-99fd-dc080ffc63ac): COMMIT;
Executing (5232e3f8-4885-409b-ac77-15b312b9799d): INSERT INTO `Words` (`id`,`word`,`createdAt`,`updatedAt`) VALUES (NULL,'я','2017-02-19 17:53:32.304 +00:00','2017-02-19 17:53:32.304 +00:00');
Executing (default): INSERT INTO `Replies` (`id`,`createdAt`,`updatedAt`,`PairId`,`WordId`) VALUES (NULL,'2017-02-19 17:53:31.286 +00:00','2017-02-19 17:53:31.286 +00:00',15,16);
Executing (5232e3f8-4885-409b-ac77-15b312b9799d): INSERT INTO `Words` (`id`,`word`,`createdAt`,`updatedAt`) VALUES (NULL,'я','2017-02-19 17:53:32.304 +00:00','2017-02-19 17:53:32.304 +00:00');
Executing (5232e3f8-4885-409b-ac77-15b312b9799d): INSERT INTO `Words` (`id`,`word`,`createdAt`,`updatedAt`) VALUES (NULL,'я','2017-02-19 17:53:32.304 +00:00','2017-02-19 17:53:32.304 +00:00');
Executing (5232e3f8-4885-409b-ac77-15b312b9799d): INSERT INTO `Words` (`id`,`word`,`createdAt`,`updatedAt`) VALUES (NULL,'я','2017-02-19 17:53:32.304 +00:00','2017-02-19 17:53:32.304 +00:00');
Executing (189c3e03-7896-4f6d-99fd-dc080ffc63ac): COMMIT;
Executing (default): INSERT INTO `Replies` (`id`,`createdAt`,`updatedAt`,`PairId`,`WordId`) VALUES (NULL,'2017-02-19 17:53:31.286 +00:00','2017-02-19 17:53:31.286 +00:00',15,16);
Executing (5232e3f8-4885-409b-ac77-15b312b9799d): INSERT INTO `Words` (`id`,`word`,`createdAt`,`updatedAt`) VALUES (NULL,'я','2017-02-19 17:53:32.304 +00:00','2017-02-19 17:53:32.304 +00:00');
Executing (5232e3f8-4885-409b-ac77-15b312b9799d): COMMIT;
(node:8180) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): SequelizeTimeoutError: SQLITE_BUSY: database is locked

__Dialect:__ sqlite
__Database version:__ XXX
__Sequelize version:__ 3.24.1

**Comment by vlakam** [comment]
My apologize. This is not a bug.

**Comment by lstanard** [comment]
@vlakam do you mind sharing what you did to resolve this?
