### ISSUE TITLE
Auto-generation of methods from associations should be documented

### ISSUE THREAD

**Issue by Grsmto** [sequelize/sequelize#7276]
Hi,

I'm an absolute beginner in ORMs in general and I just spent a few hours trying to understand why some methods had no declaration.

From the doc: 
http://docs.sequelizejs.com/en/v3/api/associations/#mixin-associations
```
User.hasMany(Picture)
user.getPictures() // gets you all pictures
```
As a beginner how are you suppose to know what is `getPictures`? Is it something contextual to the code example above and declared virtually somewhere else? Or is it a function generated by Sequelize?
I now know that it's the later.

I think this deserve a line in the documentation like:
`Sequelize will auto-generate get/set methods for you based on the association name you defined.`

**Comment by sushantdhiman** [comment]
This has been explain so many times in http://docs.sequelizejs.com/en/v3/docs/associations/

> This will add methods getUsers, setUsers, addUser,addUsers to Project, and getProjects,  setProjects, addProject, and addProjects to User

> // In both cases you will be able to do:
Person#setFather
Person#getFather

> Instances of Project will get the accessors getWorkers and setWorkers.

**Comment by travis** [comment]
these links are broken and this documentation is devilishly hard to find

**Comment by qqaimh** [comment]
> This has been explain so many times in http://docs.sequelizejs.com/en/v3/docs/associations/
> 
> > This will add methods getUsers, setUsers, addUser,addUsers to Project, and getProjects,  setProjects, addProject, and addProjects to User
> 
> > // In both cases you will be able to do:
> > Person#setFather
> > Person#getFather
> 
> > Instances of Project will get the accessors getWorkers and setWorkers.
Are these  removed ? I can't use the generated function in the last vision 5.8.5

https://github.com/sequelize/sequelize/issues/10934#issue-442992244

**Comment by JandyStephens** [comment]
It was difficult to find: https://sequelize.org/master/manual/associations.html#naming-strategy.

>By default sequelize will use the model name (the name passed to sequelize.define) to figure out the name of the model when used in associations. For example, a model named user will add the functions get/set/add User to instances of the associated model, and a property named .user in eager loading, while a model named User will add the same functions, but a property named .User (notice the upper case U) in eager loading.

**Comment by papb** [comment]
Hopefully the docs are better now :)

**Comment by mohammedSlimani** [comment]
They are documented at https://sequelize.org/master/manual/assocs.html#special-methods-mixins-added-to-instances
