### ISSUE TITLE
Postgres ENUM values can not be altered by running migrations back and forth

### ISSUE THREAD

**Issue by hal0gen** [sequelize/sequelize#7278]
## What you are doing?
This is similar to #1871 although not exactly the same. In addition to the ENUM not being dropped when dropping the corresponding table, the new values for the ENUM are simply ignored, with no errors or warnings about what's going on.

## Steps to reproduce:
1) create a migration with an ENUM 
```js
  up: function (queryInterface, Sequelize) {
      return queryInterface.createTable('users', { 
        id: {
          type: Sequelize.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        test: Sequelize.ENUM('a','b') 
      });
  },
  down: function (queryInterface, Sequelize) {
      return queryInterface.dropTable('users');
  }
```

2) run `sequelize db:migrate` and then `sequelize db:migrate:undo`

3) modify the migration
```js
  up: function (queryInterface, Sequelize) {
      return queryInterface.createTable('users', { 
        id: {
          type: Sequelize.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        test: Sequelize.ENUM('c','d') 
      });
  },
  down: function (queryInterface, Sequelize) {
      return queryInterface.dropTable('users');
  }
```

4) run `sequelize db:migrate` again

## What do you expect to happen?
It should be possible to create a `users` record with `test: 'c'`

## What is actually happening?
Creating a record with `test: 'c'` fails: 
`ERROR: invalid input value for enum enum_users_test: "c"` 

## Current workaround
Run `sequelize db:migrate:undo`, execute query `DROP TYPE "enum_users_test";` on the database and then run `sequelize db:migrate` again

__Dialect:__ postgres 
__Database version:__ 9.6.1
__Sequelize version:__ 3.30.2

**Comment by ajmueller** [comment]
This is still an issue and seems to be related to #2554.
