### ISSUE TITLE
min/max Zero Argument Validation Failure

### ISSUE THREAD

**Issue by meanjoe45** [sequelize/sequelize#7279]
Hello,

I have been trying to use the `min` and `max` validation functions and have a bug.

```js
var Test = sequelize.define('Test', {
    foo: {
        type: Sequelize.INTEGER,
        validate: {
            min: {
                args: 0,
                msg: 'Oops'
            }
        }
    }
}
```

When creating a `Test` instance, the valiation for `min` fails even when `foo` is set to a valid value. Note this does not fail if the validate statement is set to a number `min: 0` (instead of an object). It boils down to the assignment statement in instance-validator.js `_extractValidatorArgs()` function:

```js
  var validatorArgs = test.args || test;
```

The assignment above incorrectly assigns the validatorArgs to the whole `{ args: ..., msg: ... }` object. Something like the following corrects the assignment to set `validatorArgs` to the `min` argument of zero.

```js
  var validatorArgs = (typeof test.args !== 'undefined') test.args : test;
```

This may not be the final fix in the `_extractValidatorArgs()` function for all validators, but it does fix the issue for `min` and `max` validators.

Thanks for all the work you put in with Sequelize!

__Dialect:__ any
__Sequelize version:__ 3.30.2

**Comment by sushantdhiman** [comment]
```diff
var Test = sequelize.define('Test', {
    foo: {
        type: Sequelize.INTEGER,
        validate: {
            min: {
---                args: 0,
+++                args: [0]
            msg: 'Oops'
            }
        }
    }
}
```

You need to pass `args` an array, https://github.com/sequelize/sequelize/issues/6628#issuecomment-264634110

**Comment by meanjoe45** [comment]
I guess the documentation wasn't quite clear to me in the case of one argument that can be interpreted as falsy. I understand the case of multiple arguments needing to be based as an array of arguments. Maybe some clarification could be added to the documentation?

---
> To use a custom error message instead of that provided by validator.js, use an object instead of the plain value or array of arguments, for example a validator which needs no argument can be given a custom message with
...
or if arguments need to also be passed add an `args` property:
...

Note that when using an `args` property, it is good practice to assign even single arguments as an array to avoid misinterpretation of a falsy value.
```js
min: {
  args: [0],
  msg: "Must be a non-negative number"
}
```
---

Either way, thanks for the quick reply.
