### ISSUE TITLE
Limit record count in 'include' clause failed on mysql database.

### ISSUE THREAD

**Issue by colin-han** [sequelize/sequelize#7280]
Hi, developer,

I use sequelize to operate mysql database, and I want to limit record count in a sub-table query. I use limit option in include clause just like the code I shared in GitHub gist: https://gist.github.com/colin-han/e7a10b840fd436f8c968baf219c25710

I got an exception: "Cannot read property 'push' of undefined" (You can found whole call stack at bottom of the gist).

PS, if I change my code to use sqlite database, it is working correctly.

Thanks for your help.

**Comment by colin-han** [comment]
Oh, no. Why there has nobody answer me? please don't close it automatically.

**Comment by Ieremchuk** [comment]
bump
