### ISSUE TITLE
Sequelize stucks when promise is not caught

### ISSUE THREAD

**Issue by facuspagnuolo** [sequelize/sequelize#7285]
Sequelize is not responding when an error happens if I don't catch the promise manually. I was expecting it to be thrown, but the request suddenly timeouts. See an example:

Given a User model with unique constraint on the email field, when I try to create a new User with a duplicated email doing something like:
```js
const params = { name: "Carl Palmer", email: "duplicated@email.com", password: "password" }
User.create(params)
    .then(worksheet => response.status(200).send(user))
```

The last log that I see is Sequelize trying to insert a new User in the Users table:
```
Executing (default): INSERT INTO "Users" ("id","email","name","password","createdAt","updatedAt") VALUES (DEFAULT,'example@mail.com','Carl Palmer','password','2017-02-24 10:41:29.256 +00:00','2017-02-24 10:41:29.256 +00:00') RETURNING *;
```

Then the request time outs. If I catch the error while creating like this:
```js
const params = { name: "Carl Palmer", email: "duplicated@email.com", password: "password" }
User.create(params)
    .then(worksheet => response.status(200).send(user))
    .catch(error => console.log(error));
```

I get the error, but if not, like I mentioned the first time, the request time out. I was expecting it to be thrown.

Dialect: postgres
Database version: PSQL 9.5.3
Sequelize version: 3.30.2

**Comment by janmeier** [comment]
If you catch the error, you need to rethrow it, if you want it to be handled elsewhere.

When an error happens, you need to call response.error (or the equivalent for your framework) somewhere. You probably need to return / await / yield the promise for the general error handler to kick in
