### ISSUE TITLE
Check if associated entity found

### ISSUE THREAD

**Issue by euqen** [sequelize/sequelize#7289]
Hi, guys. I have one Parent entity, and I want to select all parent entities where either it has no child entity associated with it, or child's field1 is 40 for example. ParentEntity has one ChildEntity.

So I do the following: 
```js
ParentModel.findAll({}, {
include: [{
    model: ChildModel,
    where: {
       $or: [
            { field: 40 },
            { id: null } // not sure that I can do like this
        ]
    }
}]
})
```

And this doesn't work, because it returns me only where field is 40. Also I can do the following:

```js
ParentEntity.findAll({}, {
include: [{
    model: ChildModel,
    as: 'child',
}],
where: {
     $or: [
             sequelize.literal('child.field IS NULL'),
             sequelize.literal(`child.field=40`),
     ]
}
})
```

This works fine. But what if I want to use where inside the included entity?  How I can check if child entity was found inside the where object of include? Can anyone suggest something? Thanks in advance.

**Comment by sushantdhiman** [comment]
Try this

```diff
ParentModel.findAll({}, {
include: [{
+++ required: true,
    model: ChildModel,
    where: {
       $or: [
            { field: 40 },
            { id: null } // not sure that I can do like this
        ]
    }
}]
})
```

**Comment by euqen** [comment]
@sushantdhiman nope, does not work. 

It also does not work when I do this:

```
ParentEntity.findAll({}, {
include: [{
    model: ChildModel,
    as: 'child',
    where: {
         $or: [
             sequelize.literal('child.field IS NULL'),
             sequelize.literal(`child.field=40`),
         ]
     }
}],
})
```

or 

```
ParentEntity.findAll({}, {
include: [{
    model: ChildModel,
    as: 'child',
    where: {
         $or: [
             sequelize.literal('field IS NULL'),
             sequelize.literal(`field=40`),
         ]
     }
}],
})
```

**Comment by sushantdhiman** [comment]
@euqen Oh I meant `required: false`, because you want to select parent regardless child present or not. Can you try with `required: false`

And what version of Sequelize you are using, be sure to be on latest v3 or v4

**Comment by euqen** [comment]
@sushantdhiman nope, doesn't work. When I use `required: false` sequelize always returns me all entries, it looks like he doesn't use where query of the included entity if `required: false` provided.

Sequelize version: 3.24.1

**Comment by euqen** [comment]
@sushantdhiman Hi! Have you got any news according to this issue?
