### ISSUE TITLE
Where is the, afterSave, hook?

### ISSUE THREAD

**Issue by robskrob** [sequelize/sequelize#7292]
I just updated my sequelize package to the latest, 3.30.20. I see in github that afterSave exists in the hook.js but when I check the installed sequelize package in my project, it is missing. Why is afterSave absent?

**Comment by robskrob** [comment]
Ok after downloading the source, https://github.com/sequelize/sequelize/releases/tag/v3.30.2, and checking hooks.js, I just learned that the afterSave hook is absent. With the "latest" version of sequelize, how have people been able to run functions that have to run either when an instance gets created or updated?

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/6155#issuecomment-238143366
