### ISSUE TITLE
Disable sequelize default PrimaryKey behavior

### ISSUE THREAD

**Issue by sudheerj** [sequelize/sequelize#7294]
By default Sequelize expects "id" as PrimarKey if it is not defined for the model.It is not going to create for tables having  explicit PrimaryKey.But it creates problem for tables without explicit primary key(for example,views don't have primary keys).Is there any application level configuration to disable this behavior?

__Dialect: postgres
__Sequelize version:_ latest version

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/5297
