### ISSUE TITLE
anybody known how to query results with 'rowid'  by model api?  i can't find the reference anywhere

### ISSUE THREAD

**Issue by jarvanxing** [sequelize/sequelize#7298]
>   async findAll(options) {
        let rs = await this.model.findAll(options)
       if (rs && rs instanceof Array) {
          rs = rs.map(function (obj) {
             return obj.dataValues
          })
       }
       return rs
     }

i  use sequelize(model api) in my project, i want get the 'rowid' in query results, but i can't find the reference document anywhere. i known origin sql 'select rowid from ...' can do this, but this is not what i want, i use the sequelize model api
this is not a issue,  i will close this in three days or earlier

**Comment by sushantdhiman** [comment]
```js
Model.findOne({
  attributes: [
    Sequelize.literal('rowid')
  ],
  where: {
    name: { $ne: null },
    // any other conditions
  }
});
```
