### ISSUE TITLE
scopes merging with attributes field not happening

### ISSUE THREAD

**Issue by thatisuday** [sequelize/sequelize#7302]
```
scopes : {
			withStats : {
				attributes : {
					include : [
						[sequelize.literal('(SELECT COUNT(*) FROM story_view WHERE story.id = story_view.storyId)'), 'viewCount'],
						[sequelize.literal('(SELECT COUNT(*) FROM story_reported WHERE story.id = story_reported.storyId)'), 'reportedCount']
					]
				}
			},
			withoutBody : {
				attributes : {
					exclude : ['body']
				}
			}
		}
```

but `Story.scope( 'withStats', 'withoutBody').findAll()` failed to remove `body` field. Why is that?

**Comment by sushantdhiman** [comment]
It seems there is still a bug when dealing with `include` / `exclude`, Here is my comment explaining the issue with them https://github.com/sequelize/sequelize/issues/4856#issuecomment-166831300 about a year ago.

I think we need to keep intersection of whatever set of attribute left after applying various scopes.

Any PR with proposed fix will be appreciated

**Comment by thatisuday** [comment]
@sushantdhiman Was this issue addressed before? Did it got fixed at some point? How can I help to fix it?

**Comment by thatisuday** [comment]
@sushantdhiman Was this issue addressed before? Did it got fixed at some point? How can I help to fix it?
