### ISSUE TITLE
Need global option of set formatter or getter of the created_at, updated_at field.

### ISSUE THREAD

**Issue by helloqhx** [sequelize/sequelize#7304]
I know `created_at` and `updated_at` field will be auto added to every model. Sequelize also provide the `getter` option to format Date, when we retrieve these fields. But there is no global option or configuration. I have to set the getter method to every model of my project, which makes me crazy.

Can anybody help?

**Comment by janmeier** [comment]
You can add a `beforeDefine` hook (http://docs.sequelizejs.com/en/v3/docs/hooks/), which does this automagically
