### ISSUE TITLE
Add math operation to attributes include

### ISSUE THREAD

**Issue by oleksiipysanko** [sequelize/sequelize#7305]
## What you are doing?
I need to include result of multiplication between two columns into `findAll` query with associations. Though the way of adding some `sequelize.fn` to result attributes is clear in docs, I can't still understand how to work with basic math operations. I've browsed through couple of questions here (the one which suggested use of `sequelize.condition`), but nothing worked for me, maybe I'm missing something.

I have `Order` -> hasMany -> `Document` -> hasMany -> `DocumentProduct` -> belongsTo -> `Product`. Each `DocumentProduct` has `amount` and `price` columns on which I want to do multiplication and get `priceTotal` as a result. A thing to note is that one order has to have two documents (a DB representation of uploaded PDF) which are orderDocument and invoiceDocument. They both stored in `Document` table with `is_order` flag. I've set up two scoped associations for this, so it looks like:

```js
Order.hasMany(Document);
Order.hasMany(Document, {
        foreignKey: 'order_id',
        constraints: false,
        scope: {
          is_order: false,
        },
        as: 'invoiceDocuments',
);
Order.hasMany(Document, {
        foreignKey: 'order_id',
        constraints: false,
        scope: {
          is_order: true,
        },
        as: 'orderDocuments',
);
```

No problems here and I'm able to get proper results with:

```js
Order.findAll({
  include: [{
    as: 'invoiceDocuments',
    include: DocumentProduct,
    model: Document,
    required: true,
  }, {
    as: 'orderDocuments',
    include: DocumentProduct,
    model: Document,
    required: true,
  }]
})
```

But then I've tried to add `priceTotal` to `DocumentProduct` with default scope like this:

```js
defaultScope: {
      attributes: {
        include: [[Sequelize.literal(`${Sequelize.col('amount').col} * ${Sequelize.col('price').col}`), 'priceTotal']],
      },
    },
```

And it works if I include only one scoped association, but breaks for two, because it generates such sql:

```sql
SELECT ..., amount * price AS "invoiceDocuments.documentPr
oducts.priceTotal", ..., amount * price AS "orderDocuments.documentProducts.priceTotal",
...
```

Which gives, obviously, an error - `SequelizeBaseError: column reference "amount" is ambiguous`

Can you please let me know how I can achieve desired behavior with sequelize?

## What do you expect to happen?
To get columns multiplication

## What is actually happening?
Error: `SequelizeBaseError: column reference "amount" is ambiguous`

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 3.27

**Comment by kartik115** [comment]
Yes this is issue
