### ISSUE TITLE
Sequelize 2.0.0-alpha2 auto add table name + 's'

### ISSUE THREAD

**Issue by youxiachai** [sequelize/sequelize#731]
Using sqlite3
I have table: wavall
and I define model:
exports.Sound = sqlite.define('wavall', {
    rowid: Sequelize.INTEGER,
    name: Sequelize.STRING,
    description: Sequelize.STRING,
    folder: Sequelize.STRING,
    size: Sequelize.STRING
});

It throw error no such table wavalls !!!!!!!!!!! why? I define table name wavall not wavalls!

**Comment by zhou-yg** [comment]
good.

**Comment by santosh9991** [comment]
I get the same error, resolved it by adding freezeTableName: true. But, why do we get that error. ?
