### ISSUE TITLE
[Question] push onto array

### ISSUE THREAD

**Issue by idibidiart** [sequelize/sequelize#7311]
Mongoose has $push to push a value onto an array in the db. Does Sequelize have anything similar?

**Comment by euqen** [comment]
@idibidiart I assume that you actually do not need that. Mongodb is document-oriented database which allows you to store arrays. In MySQL you have to use intermediate table is this case.

**Comment by idibidiart** [comment]
So I have User table in one db and Orders table in another db (each being encapsulated by a mivroservice)  I want to have a list of order id's per each user so I can look up each user's orders by id via the Order service. Since the two tables are in different db's (that is common with microservices) how do I associate a user with a set of orders and how do I efficiently add and delete orders from that set? Any ideas?

**Comment by idibidiart** [comment]
@euqen I think I've figure this out... the Orders table will contain orders which themselves reference a user id. That is each order record will contain a user id rather than each user record containing a list of orders. Reading about 1NF, 2NF 3NF, et al helped! Thanks. Closing.
