### ISSUE TITLE
cls not works 

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#7314]
Hello!

i wrote test which is not works. Can you explain me where is my mistake.
```javascript
    it.only('different transactions async/await', async () => {
      await Promise.all([1,2].map(async ()=>{
        let tran= await models.sequelize.transaction()
        let clsTran= tran.sequelize.constructor.cls.get("transaction")
        console.log(tran===clsTran) //why false???
        assert.equal(models.sequelize.Sequelize.cls.get('transaction'), tran, "cls.get('transaction')== tran")
      }))
```

> AssertionError: cls.get('transaction')== tran: expected undefined to equal { Object (sequelize, savepoints, ...) }

**Comment by felixfbecker** [comment]
CLS does not work with async/await

**Comment by leodutra** [comment]
@felixfbecker still not working?

**Comment by nicooga** [comment]
> CLS does not work with async/await
This is not mentioned in the docs.

**Comment by marcelothebuilder** [comment]
CLS not working with async/await is something that can be overlooked. It would be nice if it was mentioned in the docs. Just lost an hour and half because of this :(
