### ISSUE TITLE
CLS session lost with custom logging function and benchmark flag enabled

### ISSUE THREAD

**Issue by lpapacek** [sequelize/sequelize#7315]
I am using **sequelize@3.24.8** with custom logging function which is logging the executed queries into a session object in CLS namespace. After the request middleware chain, the logging messages are returned in response object. Module for CLS control is **continuation-local-storage@3.2.0**. 
Everything worked fine through various project, with benchmark: false. However, with benchmark: true, the CLS is lost on exact point every time. This applies to all dialects (tested on mysql and postgres), showing you the position in mysql/query.js.
The issue is at lines 42-44.

As far as I saw, developers involved in this matter: @mknapik, @sushantdhiman 

```
Utils.inherit(Query, AbstractQuery);
Query.formatBindParameters = AbstractQuery.formatBindParameters;
Query.prototype.run = function(sql, parameters) {
  var self = this;
  this.sql = sql;

  //do we need benchmark for this query execution
  var benchmark = this.sequelize.options.benchmark || this.options.benchmark;

  if (benchmark) {
    var queryBegin = Date.now();
  } else {
    this.sequelize.log('Executing (' + (this.connection.uuid || 'default') + '): ' + this.sql, this.options);
  }

  var promise = new Utils.Promise(function(resolve, reject) {
    self.connection.query(self.sql, function(err, results) {
     
      // BUG: if self.sequelize.log is called, the active session object in CLS Namespace is reset to empty object! 
     // Calling it anywhere else outside this callback function, the log function is working fine.
      if (benchmark) {
        self.sequelize.log('Executed (' + (self.connection.uuid || 'default') + '): ' + self.sql, (Date.now() - queryBegin), self.options);
      }

      if (err) {
        err.sql = sql;

        reject(self.formatError(err));
      } else {
        resolve(self.formatResults(results));
      }
    }).setMaxListeners(100);
  });

  return promise;
};
```

Dialect: any
Database version: mysql  Ver 14.14 Distrib 5.5.44
Sequelize version: 3.24.8

**Comment by emckay** [comment]
I'm seeing the same thing on 3.27.0. Did you find a solution to this other than `benchmark: false`?

**Comment by lpapacek** [comment]
Hello, yes I've fixed it for postgres. It should be similiar fix for other dialects too (eventually, I should do a pull request). Basically moved the logging part outside the `on('end')` callback.
Code snippet below:
File: **sequelize/lib/dialects/postgres/query.js**

` ...
var promise = new Promise(function(resolve, reject) {
    query.on('row', function(row) {
      rows.push(row);
    });

    query.on('error', function(err) {

      // set the client so that it will be reaped if the connection resets while executing
      if(err.code === 'ECONNRESET') {
        self.client._invalid = true;
      }

      receivedError = true;
      err.sql = sql;
      reject(self.formatError(err));
    });

    query.on('end', function(result) {

      // BENCHMARK PATCH
      /*if (benchmark) {
        self.sequelize.log('Executed (' + (self.client.uuid || 'default') + '): ' + self.sql, (Date.now() - queryBegin), self.options);
      }*/

      if (receivedError) {
        return;
      }

      resolve([rows, sql, result]);
    });
  }).spread(function(rows, sql, result) {

    // BENCHMARK PATCH
    if (benchmark) {
      self.sequelize.log('Executed (' + (self.client.uuid || 'default') + '): ' + self.sql, (Date.now() - queryBegin), self.options);
    } else {
      self.sequelize.log('Executing (' + (self.client.uuid || 'default') + '): ' + self.sql, self.options);
    }
...
`

**Comment by emckay** [comment]
Thank you! I'm using mysql, but I'll probably be able to base a patch on what you did for postgres.

________________________________

**Comment by lpapacek** [comment]
Yes, I think it is straight forward for mysql, too. Apparently, the problem is when you are logging in query's callback functions, it messes up the cls context.
