### ISSUE TITLE
Invoking `MyModel.scope({method:['scopeName']})` not working with findAll()

### ISSUE THREAD

**Issue by alockwood05** [sequelize/sequelize#7316]
I have created a scope method that takes one argument.  I ran into an unexpected error.  I tested two cases which point to differences in the syntax of invoking the scope causing an issue.  

## What you are doing?
I am using a scope to find all items with a certain where clause.  

```js
const userid = 1; // for example
const scopedModel = MyModel.scope({method: ['forUser', userid]});
return scopedModel.findAll()
```

## Expected 
A promise for query result rows.  

## What i got?

> Error while processing route, get: /v1/buyers/{hashid}/purchase-orders: include all 'function (options) {\n  return this.findAll(options);\n}' is not valid - must be BelongsTo, HasOne, HasMany, One, Has, Many or All
>  at Model.expandIncludeAllElement (node_modules/sequelize/lib/model.js:337:15)
    at Model.$expandIncludeAll (node_modules/sequelize/lib/model.js:644:31)
    at Model.<anonymous> (node_modules/sequelize/lib/model.js:1355:22)
    at bound (domain.js:280:14)
    at Model.runBound (domain.js:293:12)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

### WORKS:  
```js
// 'active' scope being a scope method function requiring no parameters
const scopedModel = MyModel.scope('active');
return scopedModel.findAll()
```

### Throws Error, same as above:
```js
const userid = 1; // for example
const scopedModel = MyModel.scope({method: ['active']});
return scopedModel.findAll()
```

Note the scopes I am actually working with have nested includes.

**Comment by alockwood05** [comment]
sequelize version: 3.23.6

**Comment by alockwood05** [comment]
## What does this scope actually look like?

It uses a nested scope.  This nested part seems like the part that ends up causing the failure. when Sequelize goes into unravelling the nested scopes in ' sequelize/lib/model.js'  line 639 or so, `expandIncludeAll` function.

```
scopes: {
      active() {
        const {Transaction, BuyerSupplierRelationship} = sequelize.models;
        return {include: [Transaction, BuyerSupplierRelationship.scope('list')]};
      }
```

**Comment by javaguy** [comment]
I'm hitting the same issue. @alockwood05, did you figure out the cause?

**Comment by trojanh** [comment]
Didn't work for me either today. This should be debugged and fixed.
