### ISSUE TITLE
How to define type JSON in MySql

### ISSUE THREAD

**Issue by umair-khanzada** [sequelize/sequelize#7320]
Hi, 
I am using `sequelize` with `MySql`.
my problem is I wanna save `JSON object` but when  define type `JSON` it's throwing error.

`Server failed to start due to error: SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use              near 'JSON,twitterJSON,googleJSON,providerVARCHAR(255)`

Related issues:
[https://github.com/sequelize/sequelize/issues/3698](https://github.com/sequelize/sequelize/issues/3698)
[https://github.com/angular-fullstack/generator-angular-fullstack/issues/1860](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1860)

**Comment by sushantdhiman** [comment]
JSON type is currently only supported for Postgres and SQLite. Support for MySQL will land soon https://github.com/sequelize/sequelize/pull/7106

**Comment by gaochengyidlmu** [comment]
land soon...
how long
