### ISSUE TITLE
Calling stored procedure returns array with 2 sets of duplicate data

### ISSUE THREAD

**Issue by kentonbmax** [sequelize/sequelize#7321]
![image](https://cloud.githubusercontent.com/assets/15804484/23553660/ccf51104-ffef-11e6-9485-7f02f728e45c.png)

## What you are doing?
See my stored procedure call here for MSSQL. 
[Stored Procedure](http://stackoverflow.com/questions/42538525/sequelize-sytax-for-calling-stored-procedure-with-input-parameters-using-mssql/42545732?noredirect=1#comment72252914_42545732)

## What do you expect to happen?
1 array of resulting rows returned. 

## What is actually happening?
I get back 2 arrays with the same results. 

__Dialect:__ mssql 
__Database version:__ 2014
__Sequelize version:__ 3.10.10

**Comment by sushantdhiman** [comment]
Hey @kentonbmax 

It would be great if you can prepare a test case for me something like this https://github.com/sequelize/sequelize/issues/7326#issuecomment-284135609, which I can quickly execute on my system.

I will reopen this issue when a testcase has been submitted

**Comment by kentonbmax** [comment]
@sushantdhiman I'm used to the owner providing burden of proof that their code is working properly. 
To test please execute a stored proc per my syntax above and pass the result into the logic below, if you get false an array of arrays is returned. I do not believe it matters if the stored proc has parameters or not. I'm currently only working with MSSQL. 
 
    export function isolateResults(inArry:Array<any>) {
    // this is to compensate for a bug with sequelize. 
    if(inArry.length > 0 && inArry[0] instanceof Array) {
        return false
    } else {
        return true
    } 
}
