### ISSUE TITLE
Add a sequelize.increment function for better update and upsert functionality

### ISSUE THREAD

**Issue by smassin** [sequelize/sequelize#7322]
I'm proposing a suggestion that a new type of sequelize function be added called "increment" which would be used with update and upsert functions to indicate the field is an increment field without using Sequelize.literal.

Why?
Reason 1: Clearer code
Reason 2: Minimize the use of Sequelize.literal as much as possible
Reason 3: Queries like merge use multiple table names for the same query and its not good to have to guess what table name will be used.

The use case:

Example 1: Simple update and increment

instance.update({ field1: "static", field2: Sequelize.increment(20) })

What happens? The update query generator sees the increment function and automatically generates the right increment syntax.

Example 2: Upsert with insert or increment

model.upsert({ primaryKey: 1, field2: Sequelize.increment(20) })

What happens? On insert the increment is treated as a static 20 but on update it is considered as an incremental 20.

I have built the changes into a fork for my own use https://github.com/smassin/sequelize/tree/v3. I've only done an upsert example for MSSQL and there are a couple other changes that exist in the branch as well.

Any thoughts from the community on this idea?

**Comment by sushantdhiman** [comment]
Does it add any benefit, `Sequelize.increment` can be very easily replaced with `Sequelize.literal`, why you want to reduce `Sequelize.literal` use, its a great way to write custom queries.

Also you propose `Sequelize.increment` to behave different in different scenarios, On insert its just an assignment and on update its relative. That seems wrong to me

**Comment by smassin** [comment]
In general literal is good and has great uses. The benefit is that the (a)
the functionality stays in the javascript and not in constant strings. That
means name changes or queries like upsert for mssql that use multiple
tables don't require guesswork. (B) from my view the intention of the code
is clearer (c) for insert it's really acting as 0+increment. Being able to
do an upsert as an insert or increment is an incredibly common use case.

**Comment by smassin** [comment]
'Also you propose Sequelize.increment to behave different in different scenarios, On insert its just an assignment and on update its relative. That seems wrong to me'

True. After more thought the more accurate answer is when it's an insert it should be column.default value + increment that's inserted or throw and exception if the column is not a number or doesn't have a default value. Hopefully that eases your mind about the validity of the feature.
