### ISSUE TITLE
Support for upsert without update

### ISSUE THREAD

**Issue by smassin** [sequelize/sequelize#7325]
Hi,

I'm requesting support for doing an upsert without requiring any fields be updated.

Why? There are some cases where its only necessary to ensure that the record exists and not necessarily need to update it such that you can retrieve the record and do processing before doing the real data commit. This is especially useful in high concurrency/shared row situations. While, yes you can use an insert instead, it poses a problem when getting unique key violations. Basically the use case is insert or do nothing without throwing unique key violation errors.

I've done an example here https://github.com/smassin/sequelize/v3 with the MSSQL dialect.
I'm not using other DBs at the moment so I don't know how translatable it is to other dialects.

An example use case:
- There is a unique record that may or may not exist which can be created via multiple pathways, i.e. user created, server created, etc...
- With insert or do nothing (+ the right locking mechanism) a single transaction can merge in the row if its needed, then exclusively lock it, do processing (with data needed from that record), and then commit.

Thoughts?

**Comment by sushantdhiman** [comment]
Couldn't this problem be solved by http://docs.sequelizejs.com/en/v3/api/model/#findorcreateoptions-promiseinstance-created ?

Basically you just want to create a record if it doesn't exists otherwise do nothing, right ? This method is perfectly suitable for such operation.

**Comment by smassin** [comment]
Hi @sushantdhiman, thanks for the response. Yes looking at the source it looks like that does cover the case.

I would be happy to use it however I see this comment in the code:
`// Someone must have created a matching instance inside the same transaction since we last did a find. Let's find it!`
Then my question is findOrCreate safe across separate transactions?

With the method I suggested above it could done safely across separate transactions.

**Comment by smassin** [comment]
@sushantdhiman Outside of the high concurrency problem as mentioned above there is also another useful case for this feature: When using findOrCreate with a unique index to govern the duplicates it will cause your identity column to increase when the unique constraint fails for MSSQL.
Using upsert does not have this issue. This is helpful in large rapidly growing tables. So if you did an upsert without an update, basically insert is not exists, then you can guarantee no dupes without clobbering the identity column. The same could be done if you made the update only update fields from the unique index. its a bit of a waste of a query though.
