### ISSUE TITLE
Is the Documentation on Schema complete?

### ISSUE THREAD

**Issue by dmitriz** [sequelize/sequelize#7330]
This page has several menu items like `createTable` which are only copied by names with no other content:

http://docs.sequelizejs.com/en/latest/docs/schema/

Are there any parts of documentation missing for those menu items?

**Comment by sushantdhiman** [comment]
Yes documentation around that part is pretty slim for now, AFAIK its not properly autogenerated or wrose comments are missing. we are trying to improve that in upcoming v4 https://github.com/sequelize/sequelize/issues/6886
