### ISSUE TITLE
incorrect reference to path and field from SequelizeUniqueConstraintError

### ISSUE THREAD

**Issue by fjoesne** [sequelize/sequelize#7331]
## What you are doing?
Using unique fields in the model defined like this:
```
(...)
    indexes: [
      {unique: true, fields: ['email']},
      {unique: true, fields: ['username']}
    ],

(...)
```

## What do you expect to happen?
When given existing email or username, the path should be same path and field as defined in the model. 

## What is actually happening?
The return object refers to "**table**Model"(camelCased) as path and "**table**_model" as field when getting unique constraint error, while a conventional validation error behaves as expected.

unique constraint error: 
```
{
  "name": "SequelizeUniqueConstraintError",
  "message": "Validation error",
  "errors": [
    {
      "message": "user_email must be unique",
      "type": "unique violation",
      "path": "userEmail",
      "value": “mail@example.com"
    }
  ],
  "fields": {
    "user_email": “mail@example.com”,
(…)
```
while validation error for the same field looks like this:
```
(…)
      "message": "Invalid email.",
      "type": "Validation error",
      "path": "email",
      "value": {
        
      },
(…)
```

__Dialect:__ mysql
__Database version:__  5.7.17
__Sequelize version:__ ^3.27.0

**Comment by AnderLuiz** [comment]
Same issue here with Sequelize version 5.0.0-beta.16. The path should be same path and field as defined in the model, not in the database.

**Sequelize model**:

```
...
name: {
      field: 'nome',
      type: DataTypes.STRING,
   },
```

**Result**: `(path: 'nome')`
```
ValidationErrorItem {
       message: 'nome must be unique',
       type: 'unique violation',
       path: 'nome',
...
```

**Expected result**: ` (path: 'name')`

```
ValidationErrorItem {
       message: 'nome must be unique',
       type: 'unique violation',
       path: 'name', //<<<<<<<<<
..
.```
