### ISSUE TITLE
beforeCreate callback is not a function

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#7335]
## What you are doing?

```js
Login.beforeCreate(function(login, options, cb) {
    bcrypt.genSalt(5, function(err, salt) {
      if(err) return cb(err)

      bcrypt.hash(login.password, salt, null, function(err, hash) {
        if(err) return cb(err)

        login.password = hash
        return cb(null, options)
      })
    })
  })
```

## What do you expect to happen?
Crypted password written in DB.

## What is actually happening?
`Uncaught TypeError: cb is not a function`

__Dialect:__ mysql
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
A callback is only supported in v3, for v4 you need to return a promise

**Comment by derekprice** [comment]
I do realize this is over a year old, but I ran into this same issue today. The "Upgrade to V4" documentation says that callbacks are deprecated, not that it would be a breaking change. Can you please update that just for future users who run into the same issue?
