### ISSUE TITLE
Documentation shows two different ways of setting the size of the connection pool

### ISSUE THREAD

**Issue by Murphydbuffalo** [sequelize/sequelize#7338]
[This page](http://docs.sequelizejs.com/en/v3/api/sequelize/) says that `maxConnections` should be set, but [this page](http://docs.sequelizejs.com/en/v3/docs/getting-started/) says that `max` should be set.

Looking at [the source](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js) is appears that `max` is the correct field name.

Ditto for `min` vs `minConnection` and `idle` vs `maxIdleTime`.

If you agree that this is an issue I'm happy to make a PR updating the docs so that they are consistent.

**Comment by sushantdhiman** [comment]
PR is always appreciated, please keep in mind these docs are auto-generated, especially the one inside `docs/api`, you want to target actual file comments
