### ISSUE TITLE
permanent 'beforeFind' hook doesn't contain model in 'this'

### ISSUE THREAD

**Issue by farichter** [sequelize/sequelize#7339]
## What you are doing?
```js
const sequelize = new Sequelize(...
  {
    define: {
      hooks: {
        beforeFind(options) { // default hook
          console.log(this); // object
        }
      }
    }
  });
```

```js
sequelize.addHook('beforeFind', options => { // permanent hook
    console.log(this); // undefined
  });
```

```js
let MyModel = db.define('MyModel', {...}, {...})
MyModel.findOne({ where: {id: 'my-id'}})
```

## What do you expect to happen?
In the permanent hook, I also expect 'this' to be the current model.

## What is actually happening?
In the default hook, I can access the model through 'this', but not in the permanent hook.

Is it intended to work like that?

__Dialect:__ postgres
__Database version: 9.6
__Sequelize version: 3.29.0

**Comment by euqen** [comment]
@farichter I'm not sure, but have you tried to use regular function declaration instead of arrow function?

**Comment by farichter** [comment]
@euqen That's it! Thank you. I wonder why. Now I'll have to disable eslint at that line :)

**Comment by euqen** [comment]
@farichter you are welcome :+1:

**Comment by janmeier** [comment]
By defintion you cannot rebind the `this` context of an arrow function, it will always be the `this` in which it was defined

**Comment by prashant9428** [comment]
by default there is no option to get model, if you see the function definition you will find single param (options) and there to you will not find model. to get model you can bind it with this.

sequelize.addHook('beforeFind',function(options){
  const model = this
   if(model.rawAttributes.hasOwnProperty("orgId")){
 
   }

})

this = the model
this.rawAttributes = return your schema
