### ISSUE TITLE
Sequelize/Bluebird is gone again

### ISSUE THREAD

**Issue by irothschild** [sequelize/sequelize#7340]
The sequelize-bluebird dependency is gone from github again.
See https://github.com/sequelize/sequelize/issues/2520

**Comment by sushantdhiman** [comment]
Hi @irothschild , 

Opps, I deleted that repository, I wasn't aware some of our users were still using that old version. I have written to Github support about that, I am sure they will restore our bluebird fork soon. I will add a note `DO NOT DELETE` or something like that so this doesnt happen again.

On side note, please do check our latest version, hopefully you will migrate your apps to v3 or upcoming v4 :)

**Comment by sushantdhiman** [comment]
And its back https://github.com/sequelize/bluebird , I have also added a note so it doesn't get deleted in future https://github.com/sequelize/bluebird/commit/59e942bb1c0276aada8e09233dacd3cfa014848c

**Comment by irothschild** [comment]
Thanks. Most of my projects use the latest version but there i one I haven't upgraded yet. I've made a local copy of this old module now so I don't mind if it goes away now.
