### ISSUE TITLE
How to connect to MySQL with skip-networking?

### ISSUE THREAD

**Issue by ttionya** [sequelize/sequelize#7341]
Sorry, English isn't my native language.

## What you are doing?
My MySQL database have `skip-networking` config in `my.cnf`, and I can't remove it.
And how can I connect to MySQL with `skip-networking`?

I know [mysqli/mysql](https://github.com/mysqljs/mysql) can use `socketPath` to set socket file. But I can't find any options in sequelize.

```js
let sequelize = new Sequelize(config.database.database, config.database.username, config.database.password, {
    host: config.database.host, // localhost
    port: 3306,
    dialect: 'mysql',
    pool: {
        max: 5,
        min: 0,
        idle: 10000
    }
});
```

## What is actually happening?

SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306

Thank you.

Dialect: mysql
Database version: 5.6.30
Sequelize version: 3.30.0

**Comment by sushantdhiman** [comment]
You can pass `dialectOptions`, which run directly on dialect library, in this case `mysql`

```diff
let sequelize = new Sequelize(null, null, null, {
    dialect: 'mysql',
+++ dialectOptions: { socketPath: '' },
    pool: {
        max: 5,
        min: 0,
        idle: 10000
    }
});
```

**Comment by ttionya** [comment]
@sushantdhiman Thank you. I have test and it work well.
