### ISSUE TITLE
how to implement hasMany relation ???

### ISSUE THREAD

**Issue by umair-khanzada** [sequelize/sequelize#7342]
Hi,
I just wasted my whole day to implement `hasMany` relation but no luck still I am struggling.
any help can highly appreciated. 

**Scenario**
I have an like table and post table.
so post have multiple like how can i implement this.

```
***Like***
var Like = sequelize.define('like', {
    id: {
      type: DataTypes.BIGINT(16),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    link: {
      type: DataTypes.STRING,
      allowNull: false
});


***Post***
var Post = sequelize.define('post', {
    id: {
      type: DataTypes.BIGINT(16),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    file_name:
    {
      type: DataTypes.STRING,
      allowNull: false
    }
});

Post.hasMany(Like, {foreignKey: 'file_name'});
```

this is not working thrown an error `unknown file_name claues`

**Comment by sushantdhiman** [comment]
We have docs about `hasMany` relationship http://docs.sequelizejs.com/en/v3/docs/associations

If you think you have found an issue or would like to request for new feature, please open new issue with proper explanation
