### ISSUE TITLE
Multi virtual columns query issue

### ISSUE THREAD

**Issue by FlappyHeart** [sequelize/sequelize#7350]
## What you are doing?
I had two virtual columns in the business table, and I run this query`Business.find({where: req.query, attributes: {include: ['contact_name']}, include: [Contact]})`
```js
var Business = database.define('business', {
    id:{ //自增长id,主键,整形
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    contact_id: {
        type: Sequelize.INTEGER// 0为入库 1为出库
    },
    contact_name: {
        type: Sequelize.VIRTUAL(Sequelize.STRING(20), "(`contact`.name) as contact_name")
    }
    count: {
        type: Sequelize.VIRTUAL(Sequelize.INTEGER(30), "sum(`records`.count) as count")
    },
    total: {
        type: Sequelize.VIRTUAL(Sequelize.FLOAT(30), "sum(`records`.price * `records`.count) as total")
    }
},
{
    timestamps: false,
    freezeTableName: true,
    tableName: 'business'
});
```

## What do you expect to happen?
I just need the id + contact_id + contact_name and other columns which I didn't put here.

## What is actually happening?
But it also returns count and total, and even throw an error with column records.price not found

I will put my database schemas if anyone need, but you can also try with just three tables.

**Comment by FlappyHeart** [comment]
I had work it out by excluding the count and total columns before I post this issue, and I just want to know if this is a bug. I don't want to exclude the virtual columns every time.

**Comment by janmeier** [comment]
By default virtual columns are always included - You need to explicitly exclude them, or select only a subset ( `attributes: ['id', 'contact_id', 'contact_name']`
