### ISSUE TITLE
SequelizeBaseError: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#7351]
## What you are doing?
When defining
```js
var Login = sequelize.define('Login', {
    name: {
      type: DataTypes.STRING.BINARY,
      unique: true
    }, ...
}
```
then the error below occurs.

If I change `unique: true` to `unique: false` everything works fine. See http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

## What do you expect to happen?
No error.

## What is actually happening?
`SequelizeBaseError: Specified key was too long; max key length is 767 bytes`

__Dialect:__ mysql
__Database version:__ MySQL-Version 10.1.21-MariaDB-5+b1 Debian 9.0
__Sequelize version:__ 4.0.0

**Comment by janmeier** [comment]
This is a limitation in mysql - There is a limit to how long the key in the unique index can be. I'm guessing that making the column binary affects the length.

You could make the column shorter, or look at some of the suggestions [here](https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes) - You probably need to write the sql manually to be a prefix index on part of the column

**Comment by ro70** [comment]
@janmeier Thank you. This fixed the issue:
```
var Login = sequelize.define('Login', {
    name: {
      type: DataTypes.STRING(126).BINARY,
      unique: true
    }, ...
}
```

**Comment by behestee** [comment]
you might be used utf8mb4 charecter, use utf8, because the maximum length of a utf8mb4 character is four bytes. For a utf8 character it would be three bytes..
