### ISSUE TITLE
findOrCreate fails when objects are passed to fields (needed for ilike)

### ISSUE THREAD

**Issue by LoneWolfPR** [sequelize/sequelize#7353]
I'm using findOrCreate and I need to use the PostGres ILIKE feature. However, if I put an object to the field in the where clause it fails at the create step because it is trying to assign an object to the value instead of value inside the ILIKE. Here's my code example:
```
    db.Student.findOrCreate({
      where: {
        first_name: {
          $ilike: studentEnrollment.first_name,
        },
        last_name: {
          $ilike: studentEnrollment.last_name,
        },
        birthdate: helpers.cleanDate(studentEnrollment.birthdate),
        state_id: {
          $or: [
            { $eq: studentEnrollment.state_id },
            { $eq: null },
            { $eq: '' },
          ],
        },
      },
      include: {
        model: db.Enrollment,
        attributes: {
          classroom_id: studentEnrollment.classroom_id,
          grade: studentEnrollment.grade,
          enrollment_status_id: 1,
        },
      },
    }).spread(([student, created]) => ({
      student,
      errors: '',
    }));
```

I get string validation errors on first_name, last_name, and state_id. Is this a bug or is there a way to tell the query to use the value passed in the ilike?

**Comment by thehappycoder** [comment]
@LoneWolfPR Did you find a workaround?

**Comment by lanceheld** [comment]
I just encountered this issue today. I, too, am trying to perform a findOrCreate with an $iLike in my where and it is attempting to assign `{ $iLike: "value" }` to the field.

**Comment by psikoi** [comment]
Any solutions for this?

**Comment by Tapendra-Nickelfox** [comment]
any solution?

**Comment by ephys** [comment]
If you're still experiencing this issue I recommend opening a new issue

**Comment by smohanty92** [comment]
Bump..I'm tryna parameterize queries using Op but I run into this issue
