### ISSUE TITLE
Docs: "has many" through 

### ISSUE THREAD

**Issue by donpinkus** [sequelize/sequelize#7357]
There does not seem to be any documentation on writing a "has many, through" association.

There is an example on a "belongs to, through". 

Maybe we can assume that a similar syntax works for has many, through associations - but it would be better if we gave explicit syntax.

**Comment by janmeier** [comment]
Only the belongs to many relation supports `through`. Has many is a 1:m relation, so it doesn't need a join table.

See http://docs.sequelizejs.com/en/v3/docs/associations/#belongs-to-many-associations and http://docs.sequelizejs.com/en/v3/api/associations/belongs-to-many/

**Comment by donpinkus** [comment]
@janmeier - that's interesting, so how do people handle selecting through multiple associations? Do you just need to write custom methods when you want to do this?

Example: http://stackoverflow.com/questions/42708811/has-many-through-association-in-sequelize

**Comment by DiegoRBaquero** [comment]
This should be a thing. RoR has it.

**Comment by Ricardonacif** [comment]
+1 for that.
