### ISSUE TITLE
Database function not execute in raw query

### ISSUE THREAD

**Issue by kotharinilay** [sequelize/sequelize#7358]
I have function which convert binary data to UUID, when I tried to use that function in raw query it returns original column value (binary data).

here is my code:

```
let baseQuery = '
SELECT fn_BinToUuid(ServiceTypeId) AS ServiceType
FROM companyservicetype'
sequelize.query(baseQuery, {type: models.sequelize.QueryTypes.MULTIPLE }).
then(function(res){
console.log(res)
});
```

then I am getting following result : 
```
[ { ServiceType: { type: 'Buffer', data: [Object] } } ]
```

and when I execute same query in IDE, it gives converted result

![query](https://cloud.githubusercontent.com/assets/3488822/23784291/1c39cb14-0587-11e7-9252-1bc21225609c.PNG)

**Comment by janmeier** [comment]
The function seems to be returning binary data - Which is returned as a buffer. You can get the data by calling `toString()` on it
