### ISSUE TITLE
"listener" argument must be a function

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#7360]
Hello! Can you point me you suggestion what kind of mistake i should look? It is very hard to debug this error. It appears on production server only. I can not understand what to do. Same code works fine on dev machine same OS and same nodejs v7.7.2

Every sequelize request throws this error

> { TypeError: "listener" argument must be a function
>     at Socket.once (events.js:307:11)
>     at Socket.connect (net.js:943:10)
>     at Socket.connect (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/async-listener/index.js:76:27)
>     at Connection.connect (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/pg/lib/connection.js:66:17)
>     at Client.connect (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/pg/lib/client.js:56:9)
>     at Promise.tap.query (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:93:16)
>     at Promise._execute (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/bluebird/js/release/debuggability.js:300:9)
>     at Promise._resolveFromExecutor (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/bluebird/js/release/promise.js:483:18)
>     at new Promise (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/bluebird/js/release/promise.js:79:10)
>     at ConnectionManager.connect (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:89:10)
>     at ConnectionManager.<anonymous> (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
>     at ConnectionManager.<anonymous> (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/continuation-local-storage/context.js:84:17)
>     at ConnectionManager.tryCatcher (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/home/alexey2baranov/htdocs/kp-sequelizejs/node_modules/bluebird/js/release/promise.js:614:10) 'error@context': {} }

**Comment by vhain** [comment]
https://github.com/nodejs/node/pull/11762 there is bug on Node 7.7.2. use another version for now

**Comment by fcanela** [comment]
Yes, @vhain have a patch and is trying to merge it. As far as I understood from the merge request comments, Node 7.7.3 with that patch could be ready Tuesday or Wednesday next week (https://github.com/nodejs/node/pull/11762#issuecomment-286010094).

A temporal solution is downgrading to 7.7.1, which is unaffected.
