### ISSUE TITLE
Unique Constraints not actually enforced at the DB Level

### ISSUE THREAD

**Issue by jasonbodily** [sequelize/sequelize#7361]
## What you are doing?
Part of my model attributes include a composite unique key as follows:
```
{ ...
  branch_id: {
    type: sequelize.INTEGER,
    allowNull: false,
    unique: 'oneBranchStatusTypeIndex',
    references: {
      model: 'Branches',
      key: 'id'
    },
    onDelete: 'cascade'
  },
  type: {
    type: sequelize.ENUM('worked', 'reviewed', 'approved'),
    validate: { isIn: [['tagged', 'reviewed', 'approved']] },
    unique: 'oneBranchStatusTypeIndex',
    allowNull: false,
  },...
}
```
## What do you expect to happen?
An index to be generated at the DB level called 'oneBranchStatusTypeIndex' that prohibits non-unique entries

## What is actually happening?
I can violate this constraint. Looking at the Database, the constraint is never generated. I'm using postgres, sequelize 3.30.2. I have remigrated my database with this constraint in place and it is never considered. 

The docs make it sound like this should be taken care of: 
http://docs.sequelizejs.com/en/latest/docs/models-definition/

**Comment by jasonbodily** [comment]
Just realized this is handled here: https://github.com/sequelize/cli/issues/272

**Comment by sushantdhiman** [comment]
**Master and v3.30.2**

```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const N = sequelize.define('N', {
  testA: {
    type: Sequelize.TEXT,
    field: 'test_a',
    unique: 'my_unique'
  },
  testB: {
    type: Sequelize.TEXT,
    field: 'test_b',
    unique: 'my_unique'
  }
});

sequelize.sync({ force: true });
```

```sql
CREATE TABLE IF NOT EXISTS "Ns" (
   "id"   SERIAL ,
   "test_a" TEXT,
   "test_b" TEXT,
   "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
   "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
   UNIQUE ("test_a", "test_b"),
   PRIMARY KEY ("id")
);
```

It seems no matter how hard you try, you cant break this composite unique index
