### ISSUE TITLE
Foreign key: snake_case in DB and CamelCase in code. Does it possible?

### ISSUE THREAD

**Issue by 700ghz** [sequelize/sequelize#7362]
Hello!
I use **snake_case** **in** my MySql **DB**. And I use **CamelCase** **in** my **JS code.** 
So my code looks like:
```
sequelize.define('User', {
        'UserId': {
            field: 'user_id',
        },
        'UserName': {
            field: 'user_name',
        },
```

I created foreign key:
```
 classMethods: {
    associate: function (models) {
        User.belongsTo(models.UserRole, {
            foreignKey: {
                name: 'user_role_id',
            }
        });
    }
}
```
Does sequelize able to use `user_role_id` in DB and `UserRoleId` in JS code? 

Thanks!

**Comment by Alexsey** [comment]
Yes, you need to use "field" field in <a href="http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration">model definition</a> to set different name for model field and column name. A had use a beforeDefine <a href="http://docs.sequelizejs.com/en/latest/api/hooks/">Hook</a> to set all "fields" to all models automatically in snake case based on camel case name I define defined in JS. But you will also need to set createdAt, updatedAt and deletedAt separately in table definition

**Comment by 700ghz** [comment]
@Alexsey great thanks!

**Comment by durango** [comment]
Closing since this has been answered, thanks @Alexsey
