### ISSUE TITLE
Not able to initialize if .sequalizerc contains paths with subdirectories

### ISSUE THREAD

**Issue by samuliasmala** [sequelize/sequelize#7363]
## What you are doing?
I tried to initialize sequelize in Windows environment using `sequelize init` with following `.sequelizerc`:
```js
const path = require('path');

module.exports = {
  "config": path.resolve('local-config', 'database.json'),
  "models-path": path.resolve('db', 'models'),
  "seeders-path": path.resolve('db', 'seeders'),
  "migrations-path": path.resolve('db' ,'migrations')
};
```

## What do you expect to happen?
I expected following output:
```
Sequelize [Node: 6.9.1, CLI: 2.5.1, ORM: 3.30.2]

Created "local-config\database.json"
Successfully created migrations folder at "C:\Users\asmala\Programming\kuura\db\migrations".
Successfully created seeders folder at "C:\Users\asmala\Programming\kuura\db\seeders".
Successfully created models folder at "C:\Users\asmala\Programming\kuura\db\models".
Loaded configuration file "local-config\database.json".
Using environment "development".
```

## What is actually happening?
I got the following output error message:
[sequelize init error.txt](https://github.com/sequelize/sequelize/files/836092/sequelize.init.error.txt)

**The problem is that two folders (e.g. db/migrations) cannot be created, probably issue with Windows' mkdir. If I remove db (or create it manually) then it works.**

Version
[Node: 6.9.1, CLI: 2.5.1, ORM: 3.30.2]

**Comment by janmeier** [comment]
Please open this issue in github.com/sequelize/cli instead
