### ISSUE TITLE
Associations not being registered between any models

### ISSUE THREAD

**Issue by dannyhertz** [sequelize/sequelize#7364]
## What you are doing?

Hello! I've been banging my head on my laptop for over 10 hours trying to get very basic object relationships working with equalize and have had zero success. I was able to generate all models and migrations properly, seed some data, and make some basic requests, but I cannot get any associations to register or work properly. Whenever I try to do a query involving any associated objects with an 'include' clause, I get an error similar to this:

```  
Error: Occupant (occupants) is not associated to Apartment!
```

I've stripped all my models and controllers to their basics and have still been unable to figure out what I did wrong. Here are my models:

```js

module.exports = function(sequelize, DataTypes) {
  var Apartment = sequelize.define('Apartment', {
    floor: DataTypes.INTEGER,
    unit: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
          Apartment.hasMany(models.Occupant, {
              foreignKey: 'apartmentId',
              as: 'occupants'
          });
      }
    }
  });

  return Apartment;
};

```

```js

module.exports = function(sequelize, DataTypes) {
  var Occupant = sequelize.define('Occupant', {
    firstName: DataTypes.STRING,
    lastName: DataTypes.STRING,
    phoneNumber: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        Occupant.belongsTo(models.Apartment, {
          foreignKey: 'apartmentId',
          onDelete: 'CASCADE',
        });
      }
    }
  });

  return Occupant;
};

```

And my simple controller/route:

```js

var models  = require('../models');
var express = require('express');
var router  = express.Router();

router.get('/', function(req, res) {
    models.Apartment.findAll({
        include: [{ model: models.Occupant, as: 'occupants' }]
    })
    .then(function(apartments) {
        res.status(200).send(apartments);
    })
    .catch(function (err) {
        console.log(err);
    });
});

module.exports = router;

```

I've tried all sorts of variants with and without the the 'as' property without success as well. I've tried doing some debugging in the index.js file on the models directory and it looks like the 'associate' loop is never entered even though the db object seemed to contain all models in my app:

```js

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    console.log('THIS IS NEVER PRINTED');
    db[modelName].associate(db);
  }
});

 ```

Printing db shows the following:

```js

{ Apartment: Apartment,
  Occupant: Occupant }

```

Any help would be really appreciated. Thanks!!

__Dialect:__   postgres
__Database version:__ 9.6
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
`classMethods` has been removed in v4 - You should add the functions directly to the model (`Occupant.associate = ...`)
