### ISSUE TITLE
How to do a join on shared id's tables

### ISSUE THREAD

**Issue by omarcespedes** [sequelize/sequelize#7365]
I have 4 tables/models that shares ids as primary keys, but for the example I will just show 2

```js
User: {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        allowNull: false
    }
Person: {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        allowNull: false
    },
    name: {
        type: Sequelize.STRING
    }
```
I am using shared ids, so the person primary key is the primary key of User, it doesn't have autoimcrement. So is there a way to make a join between those 2 tables? I've tried to do something like:

```js
getAll(){
    return User.getAll({
        include: [{
            model:Person,
        }]
    })
}
```
But since there is no relation it doesn't work. What should I do? Thanks

{
  "error": "person is not associated to user!"
}

__Dialect:__ mysql
__Sequelize version:__ latest

**Comment by harshithkashyap** [comment]
@omarcespedes  Have you created the association between `User` and `Person`? The error is self explanatory. You should be able to fix it with `User.hasMany(Person, { foreignKey: 'id' })`.
