### ISSUE TITLE
findAndCount, error: missing FROM-clause entry for table

### ISSUE THREAD

**Issue by Mikeysax** [sequelize/sequelize#7367]
When I add **limit** and **offset** to this query I get **error: missing FROM-clause entry for table "Instruments"**. When **limit** and **offset** are not in this query, it works perfectly.
```
let searchParams = {
      TeacherId: req.params.teacherId,
      $or: [
        { 'title': { $iLike: `%${req.query.text}%` }},
        { '$Instruments.name$': { $iLike: `%${req.query.text}%` }},
        { '$Genres.name$': { $iLike: `%${req.query.text}%` }},
      ]
    };
    if (req.query.skillLevel) searchParams.skillLevel = req.query.skillLevel;
    const offset = req.query.page > 1 ? (req.query.page - 1) * req.query.perPage : 0;

    models.Lesson.findAndCount({
      where: { ...searchParams },
      include: [{ model: models.Instrument }, { model: models.Genre }],
      order: '"createdAt" DESC',
      attributes: { exclude: ['video'] },
      distinct: true,
      limit: req.query.perPage,
      offset: offset
    })
    .then((lessons) => {
      let pageTotal = Math.ceil(lessons.count / req.query.perPage);
      res.json({
        success: true,
        lessons: lessons.rows,
        pageTotal: pageTotal,
        totalLessons: lessons.count
      });
    })
    .catch((error) => {
      console.log(error);
      return res.status(500).json({ success: false, error: error });
    });
```

I expected it to work the same with or without limit or offset. There is just an error:

```name: 'SequelizeDatabaseError',
  message: 'missing FROM-clause entry for table "Instruments"',
  parent: 
   { error: missing FROM-clause entry for table "Instruments"
       at Connection.parseE (/home/michael/Documents/Code/qelodyUniversal/node_modules/pg/lib/connection.js:569:11)
       at Connection.parseMessage (/home/michael/Documents/Code/qelodyUniversal/node_modules/pg/lib/connection.js:396:17)
       at Socket.<anonymous> (/home/michael/Documents/Code/qelodyUniversal/node_modules/pg/lib/connection.js:132:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:189:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at TCP.onread (net.js:551:20)
     name: 'error',
     length: 116,
     severity: 'ERROR',
     code: '42P01',
     detail: undefined,
     hint: undefined,
     position: '829',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3129',
     routine: 'errorMissingRTE',
```

Dialect: postgres
Database version: 9.5
Sequelize version: 3.30.2

**Comment by sudheerj** [comment]
The issue occurs only when you append limit.I'am also waiting for the fix on this.

**Comment by sudheerj** [comment]
This issue will be fixed by appending duplicating:false on include

**Comment by jackturnbull** [comment]
Appending `duplicating: false` breaks offset for me - anyone else seeing this? Limit works fine.

**Comment by Mikeysax** [comment]
With duplicating: false, it fixes the error from happening but instead of limit 10, I get a random number, like 3 or 2 and 2 total pages of results instead of the full 6 or 4 results.

**Comment by jackturnbull** [comment]
@Mikeysax; this may or may not help you all that much but the way we've "worked around" this is to perform the query twice. Once to collect the IDs of the parent entities and another perform the limit and offset. Somewhat thankfully we built an abstraction layer above sequelize that allowed us the flexibility. There's the obvious and large downside of it requiring two SELECTs on any query that includes a where clause but for us the accuracy outweights the marginal performance concerns (it's a pretty low percentage of the whole response time).

Here's a non-generified started for 10:

```js
async function all(TargetModel, scopes, opts) {
  const rawResults = await TargetModel.scope(scopes).findAll(_.omit(opts, ['limit', 'offset']));

  opts.include.forEach((include) => {
    if ('where' in include) {
      delete include.where;
    }
  });

  const ids = rawResults.map(result => result.id);
  const appendedWhereQuery = _.merge({}, opts, { where: { id: ids } });
  const results = await TargetModel.scope(scopes).findAll(appendedWhereQuery);

  return {
    data: results.map(entity => entity.get({ plain: true })),
    count: ids.length,
  };
}
```

**Comment by jackturnbull** [comment]
Not stale. We're still having to perform a double query and manual count in order to get this working.

**Comment by seblemeur** [comment]
Someone found a solution ?

**Comment by Djalmar** [comment]
still a problem here

**Comment by Leerat** [comment]
still

**Comment by papb** [comment]
This issue contains a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Can someone please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example))?

**Comment by lstone** [comment]
Same here - adding limit breaks query containing aggregate function logic.

**Comment by Drilonpacarizi** [comment]
subQuery: false 

on main query will fix this

**Comment by Gefyaqiilah** [comment]
> Same here - adding limit breaks query containing aggregate function logic.

hi i solved this problem, for you who need count and data match.

if you want to get duplicating data, you must add raw: true, and duplicating: false. and now total data and count must be same. like this :

users.findAndCountAll({
{
  "raw": true,
  "where" : {
    "jobid":req.params.jobid
  },
  "attributes":
    Object.keys(this.db.model("Run").attributes).concat([
      [sequelize.fn('COUNT',sequelize.col('messages.id')),"msg_count"]
    ]),
  "include":[
      {
        "model": this.db.model("RunMessage"),
        "as" : "messages",
        "attributes":[],
        "duplicating: false
      }
  ],
  "order":[["createdAt","DESC"]],
  "logging": console.log,
  "limit": 10,
  "offset": 1
}
})

> Same here - adding limit breaks query containing aggregate function logic.

**Comment by codewithgoodlife** [comment]
Any updates on this?

**Comment by ephys** [comment]
This thread is for an extremely old version of Sequelize. If you're still experiencing this issue in the currently maintained versions of Sequelize, please open a new bug report
