### ISSUE TITLE
Sharing models between database connections

### ISSUE THREAD

**Issue by jackturnbull** [sequelize/sequelize#7369]
I'm using postgres row level security to isolate data between users. Separate database users are used so there are separate Sequelize connections, although the schema is the same so models should be shared.

Is this supported? Or is there a good pattern for this? It seems like the models hold a singleton and switch to the latest instantiated connection:

```js
// models/index.js
const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');

const connections = {};

function instantiateConnection({ connString, logger }) {
  const sequelize = new Sequelize(connString, {
    logging: (log) => {
      if (logger && logger.debug) {
        logger.debug(log);
      }
    },
  });

  const db = {};
  fs
    .readdirSync(__dirname)
    .filter((file) => {
      const basename = path.basename(module.filename);
      return !file.startsWith('.') && (file !== basename) && file.endsWith('.js');
    })
    .forEach((file) => {
      const model = require(path.join(__dirname, file)); // eslint-disable-line global-require, import/no-dynamic-require
      db[model.name] = model.init(sequelize);
    });

  Object.keys(db).forEach((modelName) => {
    if (typeof db[modelName].associate === 'function') {
      db[modelName].associate(db);
    }
  });

  db.sequelize = sequelize;
  db.Sequelize = Sequelize;

  connections[connString] = db;

  return db;
}

function getConnection({ connString, logger }) {
  return connections[connString] || instantiateConnection({ connString, logger });
}

module.exports = getConnection;
```

In use, with a `userId` column that defaults to postgres `current_user`
```js
const models = require('./index');

const UserABusiness = models('postgres://userA@db/production');
const UserBBusiness = models('postgres://userB@db/production');

const business = UserBBusiness.create({}).then(business => console.log(business.get({ plain: true })));

// => {
  userId: 'userA'
}
```

Now, I have been able to get this to work by decorating the models per-connection per-use as so:

```js
const Sequelize = require('sequelize');

const Business = require('./business');

const models = {
  Business,
};

const connections = {};

function attachModels({ sequelize }) {
  const instances = {};

  Object.entries(models).forEach(([name, model]) => {
    instances[name] = model.init(sequelize);
  });

  Object.entries(models).forEach(([, model]) => {
    if (typeof model.associate === 'function') {
      model.associate(instances);
    }
  });

  return Object.assign(instances, { sequelize });
}

function instantiateConnection({ connString, logger }) {
  const sequelize = new Sequelize(connString, {
    logging: (log) => {
      if (logger && logger.debug) {
        logger.debug(log);
      }
    },
  });

  connections[connString] = { sequelize };

  return connections[connString];
}

function getConnection({ connString, logger }) {
  return attachModels(connections[connString] || instantiateConnection({ connString, logger }));
}
```

Which will now make the following work:

```js
const models = require('./index');

const UserABusiness = models('postgres://userA@db/production');
const UserBBusiness = models('postgres://userB@db/production');

const business =  models('postgres://userB@db/production').Business.create({}).then(business => console.log(business.get({ plain: true })));

// => {
  userId: 'userB'
}
```

But it doesn't feel anywhere near as good as it could, and even though I don't need to worry about thread safety; there is a chance that other developers (including myself) could redefine the model `const` and end up with some undesirables.

## What do you expect to happen?
I'd expect all instances of a Business created by userB to use the userB connection, and not be affected by re-initialization of a Model class.

## What is actually happening?
Rerunning `init` reconfigures the models' sequelize config to use the latest sequelize passed into `init`.

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.0.0-2

**Comment by secmohammed** [comment]
any update on this?, facing similar issue

**Comment by ephys** [comment]
Models are hardwired to their Sequelize instance and cannot be used with multiple instances.

You need to create a model per Sequelize instance if you wish to do that. You can also wait for https://github.com/sequelize/sequelize/issues/15389 to be implemented, but that feature is not currently being prioritized

**Comment by secmohammed** [comment]
if I create two sequelize instances with each having its models bounded. if I keep switching the sequelize instance (for simplicity having a hashmap and getting the proper instance through the request header), it could work for the requests while instantiating the connections. Still, if I ever switch back to the old connection through the header as It got initially registered, it never switches again as if it's cached which is quite weird.
