### ISSUE TITLE
Warning message : Unhandled rejection SequelizeBaseError: Received packet in the wrong sequence.

### ISSUE THREAD

**Issue by gj1118** [sequelize/sequelize#7370]
Hi, 
I am creating a connection to a mysql database as part of my app. (This app is a VUE + Electron + Webpack) app. I am setting up the connection as follows

```js
const Sequelize = require('sequelize');

const Connection = new Sequelize('database', 'root', '12345', {
    host: 'localhost',
    dialect: 'mysql',
    logging: console.log.bind(console)
});



module.exports = {
    Connection
}
```

When I am running the app I am getting this error below
```
Unhandled rejection SequelizeBaseError: Received packet in the wrong sequence.
``` 

Dialect: mysql 
Database version:5.6
Sequelize version: 3.30.2

Can you please let me know how I can resolve this issue ?

**Comment by janmeier** [comment]
I've never seen this error before - it's not coming from sequelize, but from the underlying connector (node-mysql) https://github.com/mysqljs/mysql/search?q=Received+packet+in+the+wrong+sequence&type=Issues&utf8=%E2%9C%93
