### ISSUE TITLE
AutoGen Date attributes returning as literal

### ISSUE THREAD

**Issue by jasonbodily** [sequelize/sequelize#7371]
## What you are doing?
I'm updating my record and finding that the returned `updated_at` attribute is still literal

```js
resource.update({
  ...attrs 
}).then(r => {
   r.updated_at; // the value is { "val": "NOW()" } 
})
```

## What do you expect to happen?
I would expect the returned value to be the new date. The problem is this is the value returned to other apps, which don't know how to handle the unexpected date. I posted to stackoverflow and it doesn't look like anyone knows why or how to get around this: http://stackoverflow.com/questions/42561057/sequelize-update-after-create-hook-and-literal-date

## What is actually happening?
It's returning the date literal that was supposed to be updated in the db.

postgres 9.4, sequelize version: 3.30.2

**Comment by harshithkashyap** [comment]
@jasonbodily Could you please share your model/hook/create code so that we can try to reproduce it? Better yet submit a PR with a failing test. We can take a look a it sooner.

**Comment by sushantdhiman** [comment]
I suspect `updated_at` field is set to `NOW()`, but need model definition from OP to confirm

**Comment by jasonbodily** [comment]
Sorry to be late coming back to this. @sushantdhiman. Yes, you are correct. All my models follow the following convention: 

    id: {
        type: sequelize.INTEGER,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
    },
     //... other attrs
    created_at: {
        type: sequelize.DATE,
        allowNull: false,
        defaultValue: sequelize.literal('NOW()')
    },
    updated_at: {
        type: sequelize.DATE,
        allowNull: false,
        defaultValue: sequelize.literal('NOW()')
    }

I would like my updated_at and created_at fields to be underscored, which is why I did that in the first place. The problem is that I don't use the sync method. I had some trouble originally using sync with some custom code, so I've been passing my attributes off to migration files to be explicitly built in the DB. For example.

    // Migration Code
    let stage_attributes = require('../../src/models/stage/attributes'),
        { Stage } = require('../../src/models');

    module.exports = {
        up: function(queryInterface, DataTypes) {
            return queryInterface.createTable(Stage.tableName, stage_attributes[0]);
        },
        down: function(queryInterface, DataTypes) {
            return queryInterface.dropTable(Stage.tableName);
        }
     };

And then in the Model file:

    // Model Code
    let attrs = require(../'attributes');
    sequelize.define('Stage', attrs, { timestamps: true, underscored: true })


This has worked beautifully (and yes I have extra code for handling attribute changes between migrations), except when I update as shown above, my updated_at values are replaced with the default values. Why is that? Is there a better way to do this?

**Comment by jasonbodily** [comment]
Oh. I think I see now that we're using `Sequelize.NOW` instead of `sequelize.literal('NOW()')`. That seems to have solved my problem.
