### ISSUE TITLE
options.include[]. required = false

### ISSUE THREAD

**Issue by hnsylitao** [sequelize/sequelize#7374]
## What you are doing?

```js
const res = yield service.company.model.count({
        logging: console.log,
        include: [{
          as: 'industry',
          model: app.model.companyIndustry,
          where: {level: 2},
          require: false,
        }]
      })
```

## What do you expect to happen?
require:false  is inner join

count = 3
SELECT count(`company`.`id`) AS `count` FROM `company` AS `company` 
LEFT OUTER JOIN `company_industry` AS `industry` ON `company`.`industry_id` = `industry`.`id` AND `industry`.`level` = 2;

## What is actually happening?

count = 2
SELECT count(`company`.`id`) AS `count` FROM `company` AS `company` 
INNER JOIN `company_industry` AS `industry` ON `company`.`industry_id` = `industry`.`id` AND `industry`.`level` = 2;

__Dialect:__ mysql

**Comment by harshithkashyap** [comment]
You have a type in your code. It's `required: false`. Notice the `d` at the end.
