### ISSUE TITLE
type:BIGINT returns string, should be number

### ISSUE THREAD

**Issue by kentonbmax** [sequelize/sequelize#7377]
## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_
From model:
PKId: {
		type: sequelize.Sequelize.BIGINT,
		primaryKey: true,
		autoIncrement: true
	},

## What do you expect to happen?
adheres to number type provided by typescript interface. Changing to int returns number not string. 

## What is actually happening?
returns string. DescId is also a bigint FK set to typescript type number. 

JSON: 
[
  {
    "PKId": "100",
    "Name": "Test",
    "DescId": "0",
    "SiteId": "001"
  }
]

__Dialect:__ mssql 
__Database version:__ 2014
__Sequelize version:__ 3.10.10

**Comment by harshithkashyap** [comment]
@kentonbmax Please see the following https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L252-L276

`BIGINT` is converted to string to avoid value loss. You can also find the same on tedious page.
http://tediousjs.github.io/tedious/api-datatypes.html

**Comment by cirosantilli** [comment]
Related: https://github.com/sequelize/sequelize/issues/1774
