### ISSUE TITLE
this.options.indexes.map is not a function update version to 3.30.2

### ISSUE THREAD

**Issue by mic3ael** [sequelize/sequelize#7386]
I try to update version from 3.19.1 to 3.30.2.
After installation version 3.30.2 I ran my server and got the following error

> /home/mic3ael/src/prizmacloud/node_modules/sequelize/lib/model.js:720
>   this.options.indexes = this.options.indexes.map(this.$conformIndex);
>                                               ^
> 

> TypeError: this.options.indexes.map is not a function
>     at Model.init (/home/mic3ael/src/prizmacloud/node_modules/sequelize/lib/model.js:720:47)
>     at Sequelize.define (/home/mic3ael/src/prizmacloud/node_modules/sequelize/lib/sequelize.js:632:17)
>     at module.exports (/home/mic3ael/src/prizmacloud/models/sql/prizma.js:6:30)
>     at Sequelize.import (/home/mic3ael/src/prizmacloud/node_modules/sequelize/lib/sequelize.js:691:30)
>     at /home/mic3ael/src/prizmacloud/models/sql/index.js:17:37
>     at Array.forEach (native)
>     at Object.<anonymous> (/home/mic3ael/src/prizmacloud/models/sql/index.js:15:6)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/mic3ael/src/prizmacloud/middleware.js:4:16)
>     at Module._compile (module.js:570:32)

__Dialect: postgresSQL
__Database version: psql (PostgreSQL) 9.5.4
 __Sequelize version: 3.30.2

thanks, Michael.

**Comment by sushantdhiman** [comment]
@mic3ael Please share your model definition along with `find*` code which triggered this error.

**Comment by sushantdhiman** [comment]
Now it seems like a userland problem, I cant be sure if its a regression unless OP provide requested data. Remove tag for now

**Comment by mic3ael** [comment]
I found and fixed the problem, it was indexing definitions 
```
 indexes: [{
                    unique: true
                }, {
                    fields: ['user_name']
                }]
```
I commented it and now it is working perfectly but may I have an example how to define indexes on version 3.30.4? 

thanks.

**Comment by sushantdhiman** [comment]
Here are some examples, And full section in docs http://docs.sequelizejs.com/en/v3/docs/models-definition/#indexes

```js
{
   indexes: [
      { fields: ['field_a'] },
      { fields: ['field_b1', 'field_b2'], unique: true },
      { fields: ['field_c'], using: 'gin' },
      { fields: ['field_d'], name: 'RnM-s3e01' },
    ]
}
```

**Comment by kleinjm** [comment]
@sushantdhiman looks like that link is broken

**Comment by sushantdhiman** [comment]
@kleinjm Here you go http://docs.sequelizejs.com/manual/tutorial/models-definition.html#indexes
