### ISSUE TITLE
onDelete: restrict not working with Azure SQL 

### ISSUE THREAD

**Issue by malinosqui** [sequelize/sequelize#7388]
## What you are doing?

```
server.app.models.company.schema.hasMany(server.app.models.user.schema, { foreignKey: { allowNull: false }, onDelete: 'restrict' });
```

## What do you expect to happen?
onDelete restrict work on Azure SQL, this works normally in MySql

## What is actually happening?
Incorrect syntax near the keyword 'RESTRICT'.

__Dialect: mssql
__Sequelize version: 3.30.2

**Comment by harshithkashyap** [comment]
The equivalent of `RESTRICT` is `NO ACTION` in [SQL server](https://msdn.microsoft.com/en-in/library/ms188066.aspx). Closing this as it's not an issue with sequelize.
