### ISSUE TITLE
Optionally apply an include's where constraint only to a sub-query.

### ISSUE THREAD

**Issue by Nick-Riggs** [sequelize/sequelize#7389]
This is feature request after a conversation in Sequalize's Slack.

## Example

```javascript
const Sequelize = require("sequelize");

(async () => {
    const sequelize = new Sequelize("example", null, null, {
        dialect: "sqlite",
        storage: "./example.sqlite"
    });

    const Post = sequelize.define("post", {
        body: Sequelize.STRING
    });

    const Tag = sequelize.define("tag", {
        name: Sequelize.STRING
    });

    Post.hasMany(Tag);
    Tag.belongsTo(Post);

    await sequelize.sync({ force: true });

    //create a post that has two tags
    await Post.create(
        {
            body: "example post",
            tags: [
                { name: "example" },
                { name: "post" }
            ]
        },
        {
            include: [Tag]
        }
    );

    //query for a posts that have a tag with a name of "example"
    const post = await Post.findAll({
        include: {
            model: Tag,
            where: {
                name: "example"
            }
        }
    });

    console.log(JSON.stringify(post, null, 2));
    /* Results in (as expected with current behavior):
    [
        {
            "id": 1,
            "body": "example post",
            "createdAt": "2017-03-16T17:48:13.737Z",
            "updatedAt": "2017-03-16T17:48:13.737Z",
            "tags": [
                {
                    "id": 1,
                    "name": "example",
                    "createdAt": "2017-03-16T17:48:13.780Z",
                    "updatedAt": "2017-03-16T17:48:13.780Z",
                    "postId": 1
                }
            ]
        }
    ]
    */
})();
```

## Current Behavior

The current behavior when applying a constraint to an include, is to apply it from at the root level. So only tags with the name "example" will be included for matching posts:

```sql
SELECT
  `post`.`id`,
  `post`.`body`,
  `post`.`createdAt`,
  `post`.`updatedAt`,
  `tags`.`id`        AS `tags.id`,
  `tags`.`name`      AS `tags.name`,
  `tags`.`createdAt` AS `tags.createdAt`,
  `tags`.`updatedAt` AS `tags.updatedAt`,
  `tags`.`postId`    AS `tags.postId`
FROM `posts` AS `post` INNER JOIN `tags` AS `tags` ON `post`.`id` = `tags`.`postId` AND `tags`.`name` = 'example';
```
<table border="1" style="border-collapse:collapse">
<tr><th>id</th><th>body</th><th>createdAt</th><th>updatedAt</th><th>tags.id</th><th>tags.name</th><th>tags.createdAt</th><th>tags.updatedAt</th><th>tags.postId</th></tr>
<tr><td>1</td><td>example post</td><td>2017-03-16 17:48:13.737 +00:00</td><td>2017-03-16 17:48:13.737 +00:00</td><td>1</td><td>example</td><td>2017-03-16 17:48:13.780 +00:00</td><td>2017-03-16 17:48:13.780 +00:00</td><td>1</td></tr>
</table>
</body>
</html>

## Proposed Behavior

As an example, I'd like to constrain to only posts that include a tag with the name of "example". But I'd like the resulting posts to include all of their tags, not just those that met the constraint. 

I think adding a flag to the include options would do a good job of optionally applying this behavior:

```javascript
const post = await Post.findAll({
    include: {
        model: Tag,
        subQuery: true,
        where: {
            name: "example"
        }
    }
});
```
The results being:
```json
[
  {
    "id": 1,
    "body": "example post",
    "createdAt": "2017-03-16T18:11:01.220Z",
    "updatedAt": "2017-03-16T18:11:01.220Z",
    "tags": [
      {
        "id": 1,
        "name": "example",
        "createdAt": "2017-03-16T18:11:01.266Z",
        "updatedAt": "2017-03-16T18:11:01.266Z",
        "postId": 1
      },
      {
        "id": 2,
        "name": "post",
        "createdAt": "2017-03-16T18:11:01.267Z",
        "updatedAt": "2017-03-16T18:11:01.267Z",
        "postId": 1
      }
    ]
  }
]
```
```sql
SELECT
  `post`.`id`,
  `post`.`body`,
  `post`.`createdAt`,
  `post`.`updatedAt`,
  `tags`.`id`        AS `tags.id`,
  `tags`.`name`      AS `tags.name`,
  `tags`.`createdAt` AS `tags.createdAt`,
  `tags`.`updatedAt` AS `tags.updatedAt`,
  `tags`.`postId`    AS `tags.postId`
FROM (
       SELECT `post`.*
       FROM `posts` AS `post` INNER JOIN `tags` AS `tags` ON `post`.`id` = `tags`.`postId` AND `tags`.`name` = 'example'
     ) AS `post` INNER JOIN `tags` AS `tags` ON `post`.`id` = `tags`.`postId`
```
<table border="1" style="border-collapse:collapse">
<tr><th>post</th><th>post</th><th>post</th><th>post</th><th>tags.id</th><th>tags.name</th><th>tags.createdAt</th><th>tags.updatedAt</th><th>tags.postId</th></tr>
<tr><td>1</td><td>example post</td><td>2017-03-16 17:48:13.737 +00:00</td><td>2017-03-16 17:48:13.737 +00:00</td><td>1</td><td>example</td><td>2017-03-16 17:48:13.780 +00:00</td><td>2017-03-16 17:48:13.780 +00:00</td><td>1</td></tr>
<tr><td>1</td><td>example post</td><td>2017-03-16 17:48:13.737 +00:00</td><td>2017-03-16 17:48:13.737 +00:00</td><td>2</td><td>post</td><td>2017-03-16 17:48:13.781 +00:00</td><td>2017-03-16 17:48:13.781 +00:00</td><td>1</td></tr>
</table>
</body>
</html>

**Comment by janmeier** [comment]
Actually I think that : 
```js
const post = await Post.findAll({
  include: [{
    model: Tag,
    subQuery: true,
    where: {
      name: "example"
    }
  }, {
    model: Tag
  }]
});
```

While slightly more verbose, would more cleanly convey what is happening here - We use a subquery to filter, and then we also want to include all Tags, with no filter. In this way we could also use the syntax to filter all posts with the tag `example`, without actually returning those tags.

Also, I think using an actual subquery: 

```sql
SELECT
  ...
FROM `post` 
INNER JOIN `tags` AS `tags` ON `post`.`id` = `tags`.`postId`
WHERE EXISTS (SELECT 1 FROM `tags` WHERE postId = post.id AND name = 'example')
```
Will be cleaner - It also makes it easier to apply limit and offset, especially if we are filtering on other things than just tags.

**Comment by Nick-Riggs** [comment]
`While slightly more verbose, would more cleanly convey what is happening here`

I completely agree, that syntax is better.

**Comment by honcharov-viktor** [comment]
Hi guys. I have problem with that.
```javascript
//User.js
models.User.belongsToMany(models.UserGroup, {
  through: 'UserUserGroup',
  constraints: false,
});
```
```javascript
//UserGroup.js
models.UserGroup.belongsTo(models.User, {
  through: 'UserUserGroup',
  constraints: false,
});
```
trying run
```javascript
db.User.findAndCountAll({
  include: [
    {
      model: db.UserGroup,
      subQuery: true,
      where: {
        name: {
          $in: groups,
        }
      },
    },
    {
      model: db.UserGroup,
    },
  ],
});
```
and got error

> "SequelizeDatabaseError: table name \"UserGroups->UserUserGroup\" specified more than once"

what am I doing wrong?
Sequelize version: "4.37.3"
pg version: "7.4.1"
pg-hstore version: "2.3.2"
Postgres version: "9.3"
node version: "9.5.0"

**Comment by daenuprobst** [comment]
Is there a workaround to achieve the proposed result with the current sequelize version?

**Comment by Nick-Riggs** [comment]
@daenuprobst We've had to fire off two queries as a solution. The first query to do the "search" and bring back a list of ids. Then second query to do all the includes and constrain only by the ids we got from the first query.

**Comment by daenuprobst** [comment]
Thank you. I was really hoping for a solution that avoids two queries. I can't see how this hasn't be given a high priority... (or has it?)
