### ISSUE TITLE
Not possible to use sequelize's include while foreign key is not a primary key or a key of type Text

### ISSUE THREAD

**Issue by zlatinejc** [sequelize/sequelize#7393]
Hi!
 I am trying to include an entity that is associated via TEXT/String typed FK.

My SensorValue Entity model sample:
`
uuidTopic: {
      type: DataTypes.TEXT,
      allowNull: true,
      references: {
        model: 'Sensor',
        key: 'uuidTopic'
      }
    }
`

The referenced key in the Sensor modle is also type TEXT/String.

What I expect is to get all the SensorValues included for every Sensor executing the following:
`Sensor.findAll({
	include : [{ model: SensorValue }]
})`

The output I am getting is actually an error:

`ERR
{ [SequelizeDatabaseError: operator does not exist: integer = text]
  name: 'SequelizeDatabaseError',
  message: 'operator does not exist: integer = text',
  parent:
   { [error: operator does not exist: integer = text]
     name: 'error',
     length: 202,
     severity: 'ERROR',
     code: '42883',
     detail: undefined,
     hint: 'No operator matches the given name and argument type(s). You might need to add explicit type casts.',
     position: '763',`

When I inspect the SQL created using sequelize I notice that it generated a left join on primary key of the Sensor and the uuidTopic column of SensorValue like this:

`LEFT OUTER JOIN "SensorValue" AS "SensorValues" ON "Sensor"."id" = "SensorValues"."uuidTopic";`

Is it possible to use sequelize's include while foreign keys are not primary keys and are of type TEXT ? 

Any ideas ?

__Dialect:__ postgres 
__Database version:__ 9.6
__Sequelize version:__ 3.30.2

**Comment by ayZagen** [comment]
I have this issue too. @zlatinejc Do you remember any solution ?
