### ISSUE TITLE
model.create fails silently (doesn't return rejected Promise) on bad input

### ISSUE THREAD

**Issue by nikfrank** [sequelize/sequelize#7398]
## What I'm doing
```js
const routeHandler = (req, res) =>
  model.create( req.body.payload )
    .then(res.json)
    .catch(err => res.status(500).json(err);

routeHandler({ body: { payload: [ { modelJSON... } ] } }, expressRes)
```

## What I expect to happen
when passing { modelJSON... } to model.create, I receive in return a Promise, which resolves some time later.

when passing [{ modelJSON... }] I expected that this function should return a rejected Promise in this case in order that I .catch in the Promise chain.

## What is actually happening
An error is thrown, nothing is returned.
I can catch an error 'this.build(...).save is not a function' - effectively failing silently as far as the async logic was concerned.

My solution now involves Proxy-ing all of the Sequelize models, wrapping all function calls in a try block and converting uncaught errors into Promise.rejects

Dialect: POSTGRES, but probably affects any
Database version: 9.something, shouldn't matter
Sequelize version: 3.30.1

**Comment by janmeier** [comment]
See also https://github.com/sequelize/sequelize/issues/6116
