### ISSUE TITLE
Update swallows database level error

### ISSUE THREAD

**Issue by EdmundLeex** [sequelize/sequelize#7399]
Dialect: mysql (although I believe this applies to all)

Context: I have a database trigger that will raise error using `SIGNAL`

Bug: When I `update` my model with attributes that would trigger the mysql trigger, it silently fails. No error is thrown, promise is not rejected.

The trigger is tested in mysql console.

Here's my trigger:
```sql
CREATE TRIGGER lock_x_id BEFORE UPDATE ON Games " +
      "FOR EACH ROW " +
      "BEGIN " +
        "IF new.xid <> old.xid AND old.xId IS NOT NULL THEN " +
          "signal SQLSTATE VALUE '45000' SET MESSAGE_TEXT = 'Game has started'; " +
        "END IF; " +
      "END;
```

```js
game.update({xId: currentUser.id});
```

**Comment by armadill-odyssey** [comment]
I'm having a similar problem. Did you ever figure this one out? @EdmundLeex

**Comment by EdmundLeex** [comment]
yes, I forgot what it was though. I might've been catching it. But I can responsibly tell you that it wasn't a bug. @armadill-odyssey
