### ISSUE TITLE
How to handle specific database date function (Postgres)

### ISSUE THREAD

**Issue by jy95** [sequelize/sequelize#7401]
Hello,

I am new in sequelize and I wonder why there is no chapter inside documentation about date function like date_part (in Postgres). 
The only way I saw is to create intervals and make a date between intervals.
Not so great , for example if you want to filter by year,month,etc

**Comment by knoxcard** [comment]
Take a look at moment JS, you can easily preprocess info then submit the formatted data to Sequelize.  You mentioned you are new to Sequelize, if you have not done so,  make sure you have your MVC (model, view, controller) completely setup correctly before getting real deep into your project.

**Comment by jy95** [comment]
If you have an example with a where clause , i will take it XD

**Comment by sushantdhiman** [comment]
I am not entirely sure what you are looking for, but if you just want to execute and retrieve some SQL functions, you may use `Sequelize.literal` 

Here https://github.com/sequelize/sequelize/issues/7326#issuecomment-284135609 In this example code you can see how `Sequelize.literal` is used for grouping, that might help

**Comment by jy95** [comment]
I talked about something like that in the query: 

".... WHERE date_part('year',WhatEverTimestampYouWant) = someYear"

**Comment by sushantdhiman** [comment]
```js
{
  where: {
     $and: ['// your conditions here']
  }
}
```

**Comment by jy95** [comment]
still not an example with year. Sorry if I am bothering you, I just don't understand how to make this where clause with sequelize ...

With Squel JS ( https://hiddentao.com/squel/ ) , I have the power to do that (but I didn't have the advantages of ORM XD)

**Comment by sushantdhiman** [comment]
```diff
{
  where: {
---  $and: ['// your conditions here']
+++  $and: ['date_part('year', WhatEverTimestampYouWant) = someYear']
  }
}
```

**Comment by jy95** [comment]
Thanks. Any way to make it SQL independant ? (for example mysql doesn't handle this) ?

**Comment by sushantdhiman** [comment]
@jy95 I am not sure about API, if you want you may propose an example API that you would like to see and its use case, then we may discuss upon it further
