### ISSUE TITLE
Changing default value with `changeColumn` does not work in SQL Server

### ISSUE THREAD

**Issue by joshuapaling** [sequelize/sequelize#7403]
## What you are doing?

```js
// In SQL Server...
queryInterface.changeColumn(
  'my_table', 'my_column',
  {
    type: Sequelize.INTEGER,
    defaultValue: 0,
    allowNull: false,
  }
)
```

## What do you expect to happen?
It should successfully change the column data type and the default value.

## What is actually happening?
The SQL generated does not work : `ALTER TABLE [my_table] ALTER COLUMN [my_column] INTEGER NOT NULL DEFAULT 0;` gives `Incorrect syntax near the keyword \'DEFAULT\'`

Changing a default value in SQL Server is a bit more of a pain than other RDBMSs - it basically means dropping an existing constraint (if there was a previous default value) and adding a new constraint - see http://stackoverflow.com/questions/15547210/modify-default-value-in-sql-server for more info.

__Dialect:__ SQL Server
__Database version:__ SQL Server for Linux
__Sequelize version:__ Sequelize [Node: 6.3.0, CLI: 2.4.0, ORM: 3.28.0]
CLI version 3.9.1

**Comment by joshuapaling** [comment]
Further to this, even just changing the type of a column without changing the default value might not work if the column has an existing default value. So even just to change the type, I'm pretty sure you need to drop the constraint which enforces the existing default value first. Perhaps not if the old and new types are compatible - eg. INT and BIG INT. This answer has some info on that: http://stackoverflow.com/a/10758357/1373987

**Comment by harshithkashyap** [comment]
This will be solved by https://github.com/sequelize/sequelize/pull/7108

**Comment by Xenope** [comment]
Sorry, for my ignorance but how does this pull request have solved the original problem?
All I see is that handling constraints have been added but it doesn't appear to be used in the changeColumn.

Am i wrong?
