### ISSUE TITLE
Passing parameters to model getters

### ISSUE THREAD

**Issue by jharting** [sequelize/sequelize#7404]
This is a feature request. There may already be a way to achieve what I am trying to do in which case I'll be grateful for pointers.

## What you are doing?
I am implementing a versioned API. Assume the following simple example:

```
GET /v1/places

200 OK
[{
    name: "Luigi's Pizza Place",
    rating: 84
}, {
    name: "Greek Taverna",
    rating: 78
}]
```

The rating field is implemented as an INTEGER in the db and expected to have values 0-99

Now assume that for v2 of the API we need to change how we present rating so that it instead of 0-99 it returns 0-4 floating point number rating.

We can implement that easily with model a getter:

```js
getterMethods: {
    rating: function () {
        return this.getDataValue('rating') / 20;
    }
}
```

So far so good.

The problem now is how to preserve backwards compatibility in v1 but at the same time support new representation in v2. IMHO the cleanest would be to do that in the getter, e.g:

```js
getterMethods: {
    rating: function () {
        const value = this.getDataValue('rating');

        if (apiVersion === 1) {
            return value;
        }

        return value / 20;
    }
}
```

Now what I am struggling with is how to actually pass the apiVersion down to model getters. I can obviously get that value from some global constant but that can get tricky as execution of different requests may overlap.

The cleanest approach IMO would be for Sequelize to support passing in query context. Here's an example:

```js
sequelize.places.findAll({
    limit: 5
},
{ // this is a context object
    apiVersion: req.param.version
})
```

now the getter could be written as:

```js
getterMethods: {
    rating: function (param, context) {
        const value = this.getDataValue('rating');

        if (context.apiVersion === 1) {
            return value;
        }

        return value / 20;
    }
}
```

WDYT? Is there already a nice way to implement this that I am missing? If not would the aforementioned proposal make sense in Sequelize?

**Comment by janmeier** [comment]
I think the options object passed to `get` will actually be passed down to each getter function http://docs.sequelizejs.com/en/v3/api/instance/#getkey-options-objectany (i.e. you would do 

```js
places.findAll().then(places => res.json(places.map(places.get({ apiVersion: 42 })))
```

If not, you could look into using cls or domains to maintain a context

**Comment by jharting** [comment]
@janmeier thanks for the suggestion. It unfortunately does not seem to be the case. When I call
```
place.get({apiVersion: 3});
```

the rating getter is called with `"rating"` as a param.

Mind if I change the getter logic for this to work?

cls will work I assume but I don't love that solution as it seems to be an overkill for this usecase.

I was thinking about another approach to address this. What I am trying to achieve would be trivial if the following feature was available in Sequelize: **When I issue a Sequelize query then the original query object (options object passed to findAll, findOne, etc...) is made available to the model instance**

Example:
```js
const options = {
    where: {
        ...
    }
    limit: 5,
    request: {
        apiVersion: 3
    }
});

sequelize.places.findAll(options);
```

Sequelize would make the options object passed in available in the instance under an attribute of `this`, e.g. `this.options` or `this.query`

The getter would then look like:

```js
getterMethods: {
    rating: function (param, context) {
        if (this.query.request.apiVersion === 1) {
            return value;
        }

        return value / 20;
    }
}
```

@janmeier WDYT?

**Comment by jharting** [comment]
@janmeier actually you can disregard the second part of my previous comment. Fixing the options object passing to getters is actually all I need. I sent a PR here: https://github.com/sequelize/sequelize/pull/7435

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/7435
