### ISSUE TITLE
Why column value changed ?

### ISSUE THREAD

**Issue by DivXPro** [sequelize/sequelize#7406]
I use sequelize query a table. 

this is my model code, it's typescript
```javascript
this.UserSalaryOption = this.sequelize.define<Instance.UserSalaryOption, Attribute.UserSalaryOption>('userSalaryOption', {
      id: {
        type: DataTypes.INTEGER(14),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true
      },
      billCycle: {
        type: DataTypes.STRING(6),
        field: 'bill_cycle',
      },
      userId: {
        type: DataTypes.INTEGER(14),
        field: 'user_id',
      },
      subjectId: {
        type: DataTypes.INTEGER(10),
        field: 'subject_id',
      },
      subjectName: {
        type: DataTypes.STRING(100),
        field: 'subject_name',
      },
      amount: {
        type: DataTypes.INTEGER(12),
        field: 'amount',
      },
      isDeleted: {
        type: DataTypes.INTEGER(1),
        field: 'is_deleted',
      }
    }, {
      freezeTableName: true,
      tableName: 'user_salary_option',
      timestamps: false,
      underscored: true,
    });
```
I console log the instance. You can see the "amount" changed from 10000 to undefined. But I don't define any hook function in the model.
`[2017-03-21 17:47:53.358] [INFO] console - opt Instance {
  dataValues:
   { id: 1,
     billCycle: '201703',
     userId: 1,
     subjectId: 2,
     subjectName: 'salary',
     amount: undefined,
     isDeleted: 0 },
  _previousDataValues:
   { id: 1,
     billCycle: '201703',
     userId: 1,
     subjectId: 2,
     subjectName: 'salary',
     amount: 10000,
     isDeleted: 0 },
  _changed: { amount: true },`

If i change the "amount"  to "fee" in model code.  everything will be ok.  sequelize have any reserved words for column define ?

`[2017-03-21 17:54:22.119] [INFO] console - opt Instance {
  dataValues:
   { id: 1,
     billCycle: '201703',
     userId: 1,
     subjectId: 2,
     subjectName: 'salary',
     fee: 10000,
     isDeleted: 0 },
  _previousDataValues:
   { id: 1,
     billCycle: '201703',
     userId: 1,
     subjectId: 2,
     subjectName: 'salary',
     fee: 10000,
     isDeleted: 0 },
  _changed: {},`

**Comment by janmeier** [comment]
Plaese show a complete [SSCCE](HTTP://SSCCE.ORG/), instead of just some logging statements - We have no way to reproduce your issue

**Comment by janmeier** [comment]
Any news @DivXPro
