### ISSUE TITLE
isDeleted is not a function 

### ISSUE THREAD

**Issue by lekhnath** [sequelize/sequelize#7407]
This [docs](http://docs.sequelizejs.com/en/2.0/api/instance/) says I can use `instance.isDeleted()` method, but when I do I am getting TypeError that says `instance.isDeleted` is not a function..

**Comment by lekhnath** [comment]
My mistake, I was referring to the old v2 docs. But how to achieve this in v3 when paranoid is set to true for the model?

**Comment by sushantdhiman** [comment]
Follow the issue template. I think you are using v3.9.* but reading docs for v2.0

**Comment by lekhnath** [comment]
@sushantdhiman yes it was a silly mistake, and sorry to bother again but because this method is no more available in v3 how would I know whether I am dealing with deleted recrod or not?

**Comment by Crusader4Christ** [comment]
@lekhnath method is renamed to isSoftDeleted()
