### ISSUE TITLE
Helper method to determine whether instance has been soft deleted or not

### ISSUE THREAD

**Issue by lekhnath** [sequelize/sequelize#7408]
## What you are doing?
Trying to determine whether I am dealing with deleted record or not.

## What do you expect to happen?
Provide us with some helper method.

## What is actually happening?
When the model is configured to use `paranoid:true` the `deletedAt` attribute could be renamed to whatever name. But sequelize will definitely know about this column name even if custom name is provided.

So, I was expecting some helper method to identify whether the instance has be soft deleted or not. So that we don't have to hard code the `deletedAt` column name some other place in our code.

__Dialect:__ sqlite
__Database version__: v3.1.8
__Sequelize version__: v3.30.2

**Comment by hd719** [comment]
Hello I am new to Open source can I work on this?

**Comment by sushantdhiman** [comment]
@hd719 Thanks but Its already tackled in https://github.com/sequelize/sequelize/pull/7531, you may look at other `good-first-pr` issues https://github.com/sequelize/sequelize/labels/good-first-pr

**Comment by jsatk** [comment]
@hd719 I tacked this here https://github.com/sequelize/sequelize/pull/7531, but the build is failing. It is failing at different steps each time though and seems very unrelated to my changes. If you have any feedback on my changes or have any idea why the build may be failing I'd appreciate any extra help. 😁

**Comment by sushantdhiman** [comment]
Added in v4 https://github.com/sequelize/sequelize/pull/7531
