### ISSUE TITLE
Don't have a column call id column

### ISSUE THREAD

**Issue by ZheFeng** [sequelize/sequelize#741]
I have an existing table. In this table I have a column call uid, which is the primary key column. And it's a unique column but not an auto increase column. I put UUID there to make sure it's unique. 

But when I'm using sequelize to create new row there. I got error said "Unknown column 'id' in 'field list'". Seems sequelize put the "id" column there, and I can't find a way to config it.

**Comment by Ramla123** [comment]
I have the same problem and I made the same configuration as ZheFeng  but the same error that appears i can't find a way to config it correctly
