### ISSUE TITLE
Upsert in Sqlite doesn't do what's expected

### ISSUE THREAD

**Issue by HoneyryderChuck** [sequelize/sequelize#7410]
upsert feature is broken for sqlite. Although it doesn't support this out of the box, I think this is manageable. 

## What you are doing?

I'm doing a plain upsert call to create a user. My User has an id as primary key, but it also has a uniqueness constraint for the email:

```js
User.upsert({email: "bing@bing.com", name: "Poo Poo"}).
then(user => ...
```

This generates the following SQL:

```SQL
INSERT OR IGNORE INTO `users` (`email`, `name`) VALUES ('bing@bing.com', 'Poo Poo'); UPDATE `users` SET `email`='bing@bing.com', `name`='Poo Poo' WHERE (`id` IS NULL)
````

Note the `WHERE` clause. It's clearly doing it wrong. Now, I've seen in stackoverflow people recommending me to pass the id. However, to get an ID I have to fetch it from the DB, which defeats the purpose of an upsert. 

I also tried to use the `onDuplicate`option, but the generated query breaks (`ON` is not supported in sqlite). However, I think that this option could be reused for sqlite, in that the fields passed to it should be used in the `WHERE` clause where the id is being wrongly used. 

## What do you expect to happen?

I would like to generate the following SQL:

```SQL
INSERT OR IGNORE INTO `users` (`email`, `name`) VALUES ('bing@bing.com', 'Poo Poo'); UPDATE `users` SET `name`='Poo Poo' WHERE (`email`='bing@bing.com')
````

__Dialect:__ sqlite
__Database version:__ 3.14.0
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
Is the email column marked with `unique: true` in your model definition?

**Comment by HoneyryderChuck** [comment]
ouch. that's exactly what was missing. Thx for the quick support!
