### ISSUE TITLE
Is the save() result's id column atomic / immune to other inserts?

### ISSUE THREAD

**Issue by subatomicglue** [sequelize/sequelize#7412]
In MySQL, when we insert a row, we can get the ID using `LAST_INSERT_ID()` thing, which needs database locking around both the `INSERT` and `LAST_INSERT_ID()` operations to ensure no other insert happened to disturb the value or "the last id".

Considering the above,  Does **Sequelize** guarantee that the `id` returned from the `save()` promise is ALWAYS going to be the correct ID?   If so, then it might be good to add a comment about that in the `save()` [documentation](http://docs.sequelizejs.com/en/v3/api/instance/#save) to help MySQL people rest easy.  If not, then a warning in the save() [documentation](http://docs.sequelizejs.com/en/v3/api/instance/#save) would be good (plus suggestion to use transaction with locking perhaps??)
```
Users.build( { name: "fred" } ).save()).then( user => user.id ); // <- can we trust the id?
```

Using Sequelize 3.30.0
Thanks for any clarification.  We're trying to determine if we can use the save() result straight up, or if we need to protect it with locking to ensure consistent ID returned...

**Comment by janmeier** [comment]
We are not calling `LAST_INSERT_ID()` manually - We get the id back from the mysql connector [here](https://github.com/sequelize/sequelize/blob/b31b662870c30338a266c47f9f8b2057b4c1e10a/lib/dialects/mysql/query.js#L104-L110). I would very much assume that mysql2 does the right thing, but you will have to ask there to be sure :). Feel free to update the documentation once you get a reply from them
