### ISSUE TITLE
Raw Queries and Loading Scopes

### ISSUE THREAD

**Issue by foomoto** [sequelize/sequelize#7414]
It will be nice if raw queries could have the associations loaded as well. For example,

After a Route model is defined then I added the scopes

Route.addScope ('defaultScope', {
    include : [{
        model : Journey
    }, {
        model : Location,
        as : 'startLocation'
    }, {
        model : Location,
        as : 'endLocation'
    }]
}, {
    override : true
})

findRoutes : function (startPoint, endPoint, skip, size) {
            return sequelize.query("SELECT * FROM routes LIMIT :size OFFSET :skip",
                {
                    model: Route,
                    type: db.QueryTypes.SELECT,
                    replacements : {
                        skip : skip,
                        size : size
                    }
                })
        },
}

does not return associations.

**Comment by janmeier** [comment]
By definition a raw query is raw - i.e. not cooked or seasoned with scopes or any of the other sequelize helper methods - We can't just start modifying the SQL that the user provides ....

**Comment by foomoto** [comment]
I figured that scopes actually result to joins etc. I had thought scopes eager loaded by the model.

**Comment by janmeier** [comment]
Scopes are options you can apply to regular sequelize calls (`findAll` etc.), kinda a way to provide a default set of options, that you use a lot - These methods generate the sql for you.

`query` allows you to input raw SQL - Which sequelize does not modify

**Comment by foomoto** [comment]
thanks jammier
