### ISSUE TITLE
Sequelize support to escape wildcard characters

### ISSUE THREAD

**Issue by ShaharyarAhmed** [sequelize/sequelize#7421]
## Escape Wildcard characters
I have to generate following query:
```sql
SELECT * FROM `table` WHERE `value` LIKE '%|%username%' ESCAPE '|';
```
But when I pass in function:
```js
sequelize.escape('%username%')
//returns
//%\'%username%\'%
```	
How to tell `sequelize` what character I want to escape? Does `sequelize` support this type of escape?

__Dialect:__ mysql
__Database version:__ 5.6
__Sequelize version:__ 3.23.4

**Comment by sushantdhiman** [comment]
I dont know how you are constructing your query, But you can use `$like /$iLike` http://docs.sequelizejs.com/en/v3/docs/querying/#operators in `find*`

Otherwise you can do raw query If you need `ESCAPE '|'` syntax
