### ISSUE TITLE
Self-referencing in belongsToMany doesn't take both ids in the query

### ISSUE THREAD

**Issue by HoneyryderChuck** [sequelize/sequelize#7427]
I'm trying to model the relationship "User is a friend and has many friends". The belongs-to-many associations seems to fit. Sadly, I'm not being able to set this. The documentation states:

> Person.belongsToMany(Person, { as: 'Children', through: 'PersonChildren' })
> // This will create the table PersonChildren which stores the ids of the objects.

I'm doing:

```js
User.belongsToMany(User, {as: 'Friends', through: Friendships})
````

The mid-table will be created with  `userId` and `friendId`. All good, until I create my first friendship, which I do by using the API:

```js
user1.addFriend(user2)
#=> ..
#=> INSERT INTO `friendhips` (`userId`, `friendId`) VALUES (2, 1)
```

Problem is that, now, I can only query friends from user1. If I do it from user2 side, it'll return an empty list. This is because calling `user1.getFriends()` will generate the query: 

```SQL
Executing (default): SELECT `users`.`id`, `users`.`email`, `users`.`full_name` AS `fullName`, `users`.`token`, `users`.`createdAt`, `users`.`updatedAt`, `friendships`.`userId` AS `friendships.userId`, `friendships`.`FriendId` AS `friendships.FriendId` FROM `users` AS `users` 
INNER JOIN `friendships` AS `friendships` ON `users`.`id` = `friendships`.`FriendId` AND `friendships`.`userId` = 1;
```

It should be `userId = 1 OR friendId = 1`, for this to be bi-directional and fulfill the requirement. 

Is this a bug or an unexisting feature? I tend to the bug side, but then again, there might be a workaround I'm not familiar with. 

__Dialect:__ sqlite
__Database version: 3.14.9
__Sequelize version:__ 4.0.0-2

**Comment by sushantdhiman** [comment]
> Problem is that, now, I can only query friends from user1. If I do it from user2 side, it'll return an empty list. 

Because `user1` has `user2` as friend, opposite is not true. You need to call `user2.addFriend(user1)` as well. Only then we can refer data from `user2` side

We need a relation only then we can query it. Other wise you can define a method yourself which will roughly do this, include `User` where `userId = 1 OR friendId = 1`
