### ISSUE TITLE
Get used scope name in hooks?

### ISSUE THREAD

**Issue by oscarr-reyes** [sequelize/sequelize#7433]
I am in the need of getting the name of the scope used when i am executing functions on hooks, i would find this useful for processing values through scopes, if there is any function that could be executed on scope after find i would like to know, meanwhile if this could be a new feature i'm thinking this could be used this way:

```JavaScript
sequelize.define("accounts", {. . . .}, {
	tableName: "accounts",
	scopes: {
		bash: {. . . .}
	},
	hooks: {
		afterFind: afterFind
	}
});

function afterFind(rows, options){
	if(options.scopeName == "bash"){
		for(i = 0; rows.length > i; i++){
			var row = rows[i];

			// Transform the text to be only a short chunk for preview display
			if(row.biography.length > 60){
				row.text = row.biography.slice(0, 60);
			}
		}
	}

	return rows;
}
```

**Comment by sushantdhiman** [comment]
Not much but you can get current scope structure with `this._scope` inside `afterFind`, you can do manual test against scopes defined in `this.options.scopes`

**Comment by Nosthertus** [comment]
I tried that but `this._scope` is undefined in all scopes. I am using Sequelize `v3.28.0` and i don't know if any further update defines that property in the instance

**Comment by sushantdhiman** [comment]
Its `this.$scope` for `v3` and `this._scope` for `v4`(master)

**Comment by Nosthertus** [comment]
Oh.. looks like i need to check the differences in order to see if i need to update. But still i think getting the name of scope could be a good feature

**Comment by sushantdhiman** [comment]
Yes, I agree. It should be easy to do.

Just need to set new prop like `this._scopeName` in `Model.scope` and unset in `Model.unscope` + tests

You may open a PR, I am keeping this issue open as a feature request.

**Comment by oscarr-reyes** [comment]
sorry for the late response, i was working on upgrading sequelize 3 to 4 and i found out there i a change with the `scope` property and the where the scopes are stored now.. since i am now including nested models in a scope it is a bit harder to compare objects of the used scoped with the list of scopes, of course this takes a bit more time to be resolved so i would like to know if there is a PR already that makes this

I will find if the code that does this is already pulled anyways, if not then i will make my own PR now

**Comment by oscarr-reyes** [comment]
PR #8753

**Comment by BerkSpar** [comment]
How can I do it today in v6?
