### ISSUE TITLE
Where clause in findById not working

### ISSUE THREAD

**Issue by Diluka** [sequelize/sequelize#7434]
## What you are doing?
call findById with additional where clause

```ts
await Document.findById(id,{where:{owner}});
```

## What do you expect to happen?
If file with this `id` belongs to `owner`,  get this file, else error somehow.

## What is actually happening?
where clause doesn't work

Dialect: mysql
Database version: 5.7.16-1debian8
Sequelize version: 4.0.0-2

I found this. [where clause has been cleared](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1668)

**Comment by sushantdhiman** [comment]
`findById` is just find by id, use `findOne` if you want to add extra conditions
