### ISSUE TITLE
Return assosiation after update?

### ISSUE THREAD

**Issue by lucas-aragno** [sequelize/sequelize#7437]
I'm trying to update a record of a table that is associated with another record, but I want the `update` return the record with the associated record as json as well but right now I'm just getting the ids.

```javascript
      post.update(body, {
        include: { model: Tag, as: 'tags' }
      }).then(post => {
        res.json(post);
      });
```

in that snippet on `post` im getting the post (updated) but on the `tags` field I get an array with **only** the ID of the associated tags. Is that something doable? I am missing something?

**Comment by sushantdhiman** [comment]
Please follow the issue template with Models, relation between them.

You can also do a `findOne with include` after update is successful
