### ISSUE TITLE
allowNull behavior varies depending on the alphabetical order of models.

### ISSUE THREAD

**Issue by barkan** [sequelize/sequelize#7440]
Following the documentation:
1) You define a Task that belongsTo User with foreignKey allowNull:false.
2) You define a User that hasMany Tasks. foreignKey can be null.

Defining models this way, you cannot create a Task without providing the ID of a User.

However, if you change the name of the User model to Author like this:
1) Define an Author that hasMany Tasks. foreignKey can be null.
2) Define a Task that belongsTo Author with foreignKey allowNull:false.

... the Author foreignKey is no longer required when creating a Task.

So the Author's lax requirements override the Tasks more stringent requirements. It appears this is based on the name of the models or the filenames so that the alphabetical parsing produces different results.

**Comment by sushantdhiman** [comment]
Sequelize take all relationships defined and generate join fields based on all those relations. Its possible to face issue like this when one relation is defining a field null and other is defining as non-null.

I believe users should be more careful when defining relationship and keep constraints same for both cases.

But again sometime it may be missed by user. A warning of some sort might be helpful.
