### ISSUE TITLE
sequelize return data to variable

### ISSUE THREAD

**Issue by hariskhaliquecs** [sequelize/sequelize#7442]
I want to make following array 
{
    reasontypes:[{},{},....]
    users:[{},{},{}]
}
I have two models reasontype, user both are not depend on each other but on front I need both in single object I can achieve by chaining  promise like 

```
reasontype.findall().then(function( reasons){ 
       return reasons; 
}).then(function(reasons){
    user.findall().then(function(users){
         return res.status(200).send({
             reason: reasons,
             userinfo: users
          });
       }).catch();
}).catch();

```
is there any other batter way ? because if I need one more object I need to this object to another promise (then) there will be too many nested then.

**Comment by harshithkashyap** [comment]
If you can't associate the two models, sequelize can't help you here. You could use [Promise.all](http://bluebirdjs.com/docs/api/promise.all.html) and return the result to avoid nesting.
