### ISSUE TITLE
struggling with join "orders is not associated to delivery details."

### ISSUE THREAD

**Issue by vikramCheethirala** [sequelize/sequelize#7443]
## What you are doing?
I have two tables orders and deliverydetails:
deliverydetails :

module.exports = function(sequelize, DataTypes) {
    const deliverydetails = sequelize
        .define('deliverydetails', {
            deliveryid: {
                type: DataTypes.BIGINT,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
            orderid: {
                type: DataTypes.STRING,
                allowNull: false
            }

        }, {
            classMethods: {
                associate: function(models)  {
                    deliverydetails.belongsTo(models.orders, {foreignKey:'orderid',as : 'orderid'});
                }
            }
        });
    return deliverydetails;
};
orders:
module.exports = function (sequelize, DataTypes) {
    const orders = sequelize
        .define('orders', {
                orderid: {
                    type: DataTypes.BIGINT,
                    allowNull: false,
                    primaryKey: true,
                    autoIncrement: true
                }
                
            },
            {
                classMethods: {
                    associate: function (models) {
                        orders.hasMany(models.deliverydetails, {foreignKey: 'orderid', as :'orderid'});
                    }
                }
            });
    return orders;
};
var options = {include: [{model: orderdetails, as: 'orders',  required: true}]};

deliverydetails.findall(options).then(....)

## What do you expect to happen?
No exceptions.

## What is actually happening?
orders is not associated to delivery details.

_Output, either JSON or SQL_
N/A

__Dialect:__ mysql

**Comment by harshithkashyap** [comment]
You've specified the alias in association as `orderid` and trying to use alias `orders` in include. The following will work.
```javascript
 var options = {include: [{model: orderdetails, as: 'orderid', required: true}]};
```

**Comment by vikramCheethirala** [comment]
Thank you @harshithkashyap .I tried that as well. That did not help.

**Comment by harshithkashyap** [comment]
If you could format you code better, we'll be able to help you better.

**Comment by vikramCheethirala** [comment]
orders :<script src="https://gist.github.com/vikramCheethirala/873e9b396a290271052fd4a658a39c33.js"></script>

delivery details : <script src="https://gist.github.com/vikramCheethirala/427ad89052e8f001ef56ed59f7c64883.js"></script>

var options = {include: [{model: orderdetails, as: 'orders', required: true}]};

deliverydetails.findall(options).then(....)

**Comment by vikramCheethirala** [comment]
@harshithkashyap  Thanks. 

orders :
```
module.exports = function (sequelize, DataTypes) {
    const orders = sequelize
        .define('orders', {
                orderid: {
                    type: DataTypes.BIGINT,
                    allowNull: false,
                    primaryKey: true,
                    autoIncrement: true
                }
            },
            {
                classMethods: {
                    associate: function (models) {
                        orders.hasMany(models.deliverydetails, {foreignKey: 'orderid', as :'orderid'});
                    }
                }
            });
    return orders;
};
```
delivery details :
```
module.exports = function(sequelize, DataTypes) {
    const deliverydetails = sequelize
        .define('deliverydetails', {
            deliveryid: {
                type: DataTypes.BIGINT,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
            orderid: {
                type: DataTypes.STRING,
                allowNull: false
            }

        },
		{
            classMethods: {
                associate: function(models)  {
                    deliverydetails.belongsTo(models.orders, {foreignKey:'orderid',as : 'orderid'});
                }
            }
        });
    return deliverydetails;
};
```
join code : 

var options = {include: [{model: orders, as: 'orderid', required: true}]};

deliverydetails.findall(options).then(....)
