### ISSUE TITLE
Postgres JSON(B) 'destroy' with 'where' object fails in paranoid mode

### ISSUE THREAD

**Issue by zbigg** [sequelize/sequelize#7444]
This is actually refinement of #5092 which i commented some time ago with no feedback. 

## What you are doing?
Table with `paranoid` enabled and column with `JSON` or `JSONB` type. When destroying by using where object, it throws an exception.

```js
var Page = sequelize.define('Page', {
  content: Sequelize.JSONB
}, { paranoid: true} )
Page.destroy({ where: { content: { title: "Title" } } })
```
(full code here: https://gist.github.com/zbigg/883eadd98f608cbdec3fba8f5cc5b58c)

## What do you expect to happen?
Destroy shall work at least attempt to query DB even with empty table.

## What is actually happening?

Exactly same error  as in #5062 post:
 - `Page.destroy({ where: { content: { title: "Title" } } })` triggers
```
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (.../node_modules/sequelize/lib/sql-string.js:61:15)
    at Object.escape (.../node_modules/sequelize/lib/dialects/abstract/query-generator.js:978:22)
```
 - `Page.destroy({ where: { 'content.title': "Title" } })` triggers 
```
Unhandled rejection SequelizeBaseError: column "content.title" does not exist
    at Query.formatError (/.../node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/.../node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
```

__Dialect:__ postgres 
__Database version:__ 9.6.2 / OS X El Capt
__Sequelize version:__ 3.30.2  / node 7.1.0 / OS X El Capt

**Comment by sushantdhiman** [comment]
Its related to https://github.com/sequelize/sequelize/issues/5811 somehow
