### ISSUE TITLE
where to config "max_allowed_packet" 

### ISSUE THREAD

**Issue by matt212** [sequelize/sequelize#7451]
Hi, 
When i am using bulkcreate of sequelize , I am getting below error 

> 
> Unhandled rejection SequelizeDatabaseError: ER_NET_PACKET_TOO_LARGE: Got a packe
> t bigger than 'max_allowed_packet' bytes

In order to solve the issue , it was suggested to put max_allowed_packet=100M
://stackoverflow.com/questions/93128/mysql-error-1153-got-a-packet-bigger-than-max-allowed-packet-bytes
my query where should i put "max_allowed_packet" in order to avoid this issue !

**Comment by matt212** [comment]
hi, 

I resolved the issue by changing value of max_allowed_packet to 100M in my.ini from below location
C:\ProgramData\MySQL\MySQL Server 5.7\
and restarted my "MySql" services !

**Comment by albertotorresfoltyn** [comment]
What if i want to do this programatically?
