### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by strommmm** [sequelize/sequelize#7452]
sequelize/lib/dialects/abstract/query-generator.js line 2129-2132

//if ANY is used with like, add parentheses to generate correct query
if (escapeOptions.acceptStrings && (comparator.indexOf('ANY') > comparator.indexOf('LIKE'))) {
  value = '(' + value + ')';
}

if ALL is used with like|ilike, same as ANY
but codes only judge ANY

**Comment by sushantdhiman** [comment]
Please follow the issue template and clearly state nature and steps to reproduce the bug
