### ISSUE TITLE
findAndCountAll and count not support group

### ISSUE THREAD

**Issue by 8473874** [sequelize/sequelize#7453]
I need the SQL:
select count(1) from (
 select billYear,billMonth from bills
 where billYear = 2017
 group by billYear,billMonth
) as t;

select sum(introduceTotal),billYear,billMonth as Total  
from bills 
where billYear = 2017
group by billYear,billMonth;

*****************************************************************************

use Sequelize:

bills.findAndCountAll({
  where: {
    billYear: 2017
  },
  attributes: ['sum(introduceTotal)', 'billYear', 'billMonth'],
  group: ['billYear', 'billMonth']
});

Sequelize to sql

SELECT count(*) AS `count` FROM `bills` AS `bills` WHERE `bills`.`billYear` = 2017 GROUP BY `billYear`, `billMonth`; //is error
SELECT sum(introduceTotal) AS `total`, `billYear`, `billMonth` FROM `bills` AS `bills` WHERE `bills`.`billYear` = 2017 GROUP BY `billYear`, `billMonth`; //is right

*****************************************************************************

Dialect:  mysql 
Database version: 5.6
Sequelize version: 3.30.2

**Comment by 8473874** [comment]
My temporary solution

https://github.com/8473874/sequelize/blob/master/lib/dialects/abstract/query-generator.js

The place where I modify
annotation // if group by, and select count do

**Comment by sushantdhiman** [comment]
Closing as per https://github.com/sequelize/sequelize/issues/6148#issuecomment-227439517
