### ISSUE TITLE
Unable to join two associated tables.

### ISSUE THREAD

**Issue by vikramCheethirala** [sequelize/sequelize#7470]
## What you are doing?
Trying to join two tables , and i get an exception saying

orders(orderid) is not associated to delivery details.

```js
orders :

module.exports = function (sequelize, DataTypes) {
    const orders = sequelize
        .define('orders', {
                orderid: {
                    type: DataTypes.BIGINT,
                    allowNull: false,
                    primaryKey: true,
                    autoIncrement: true
                }
            },
            {
                classMethods: {
                    associate: function (models) {
                        orders.hasMany(models.deliverydetails, {foreignKey: 'orderid', as :'orderid'});
                    }
                }
            });
    return orders;
};
delivery details :

module.exports = function(sequelize, DataTypes) {
    const deliverydetails = sequelize
        .define('deliverydetails', {
            deliveryid: {
                type: DataTypes.BIGINT,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
            orderid: {
                type: DataTypes.BIGINT,
                allowNull: false
            }

        },
		{
            classMethods: {
                associate: function(models)  {
                    deliverydetails.belongsTo(models.orders, {foreignKey:'orderid',as : 'orderid'});
                }
            }
        });
    return deliverydetails;
};
join code :

var options = {include: [{model: orders, as: 'orderid', required: true}]};

deliverydetails.findall(options).then(....)
```

## What do you expect to happen?
No exception and join smoothly

## What is actually happening?
An exception saying "orders(orderid) is not associated to "deliverydetails".

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Database version:__ XXX
__Sequelize version: 3.24.8

**Comment by sushantdhiman** [comment]
You need to define inverse relationship as well. So you are missing something like

```js
orders.hasMany(deliverydetails, {foreignKey: 'orderid', as :'orders'});
deliverydetails.belongsTo(orders, {foreignKey: 'orderid', as :'order'});
```

**Comment by vikramCheethirala** [comment]
@sushantdhiman , I think i exactly have the same stuff in my code.

**Comment by sushantdhiman** [comment]
Try with different alias as I have used, you are currently defining alias which are same as one of your field. Which I think resulting in collision

**Comment by vikramCheethirala** [comment]
Thanks @sushantdhiman , I tried several options like renaming foreign key and alias. still it doesn't work.

orders.hasMany(models.deliverydetails, {foreignKey: 'orderid', as :'orders'});
deliverydetails.belongsTo(orders, {foreignKey: 'orderid', as :'orders'});

Does plural/singular matters? as you mentioned in your sample code?

**Comment by sushantdhiman** [comment]
Now both alias are named `orders`, name them as I have. Because `belongsTo` with `orders` doesn't make much sense
