### ISSUE TITLE
ER_NO_DB_ERROR: No database selected

### ISSUE THREAD

**Issue by nanom1t** [sequelize/sequelize#7472]
Hello.

I'm using sequelize in my Express.js application and I've faced with strange issue/bug. I get an exception exactly after starting of application. All database credentials are correct. It seems like sync() method is called before db connection is completely initialized or something like that. The sequelize.authenticate() method works properly.
```
ER_NO_DB_ERROR: No database selected
Unhandled rejection SequelizeDatabaseError: ER_NO_DB_ERROR: No database selected
    at Query.formatError (/vagrant/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/vagrant/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/vagrant/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/vagrant/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/vagrant/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/vagrant/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/vagrant/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/vagrant/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
``` 
The problem happens in these lines of code, but it may be more deeper:
```
models.sequelize.sync().then(function () {
    var server = http.createServer(app);
    server.listen(configs.APP_PORT);
    server.on('error', onError);
    server.on('listening', function () {
        console.log('Listening on port ' + configs.APP_PORT);
    });
}).catch(function (error) {
    onError(error);
});
```
Also I get the same error when I'm trying to run migrations (sequelize db:migrate). Here is my /models/index.js
```
var fs = require('fs');
var path = require('path');
var Sequelize = require('sequelize');
var configs = require('../../configs');
var basename = path.basename(module.filename);
var database = {};

/**
 * Inialize models connection
 */
var sequelize = new Sequelize(configs.DATABASE_NAME, configs.DATABASE_USER, configs.DATABASE_PASSWORD, {
  host: configs.DATABASE_HOST,
  port: configs.DATABASE_PORT,
  dialect: configs.DATABASE_DIALECT,
  logging: configs.APP_DEBUG
});

fs
  .readdirSync(__dirname)
  .filter(function(filename) {
    return (filename.indexOf('.') !== 0) && (filename !== basename) && (filename.slice(-3) === '.js');
  })
  .forEach(function(filename) {
    var model = sequelize['import'](path.join(__dirname, filename));
    database[model.name] = model;
  });

Object.keys(database).forEach(function(modelName) {
  if (database[modelName].associate) {
    database[modelName].associate(database);
  }
});

database.sequelize = sequelize;
database.Sequelize = Sequelize;

module.exports = database;
```

Dialect: MariaDB
Database version: 10.0.29
Sequelize version: [Node: 6.10.0, CLI: 2.7.0, ORM: 3.30.4]

**Comment by sushantdhiman** [comment]
Can you show what SQL queries are executing in `sequelize.sync` step, using `logging`

Are you sure `configs.DATABASE_NAME` is set ?

**Comment by AlpacaGoesCrazy** [comment]
I am experiencing exact same issue right now, is there any solution for this?

**Comment by mmarovich** [comment]
I saw someone have a similar error to this.  The problem was that they were using process.env variables in their config file, and for whatever reason, sequelize simply couldn't read those variables.  I don't know if this helps at all, but I thought I'd mention it in passing.

**Comment by mmarovich** [comment]
Update on this.  It seems like my colleague needed to use the dotenv-cli, and then migrate with `dotenv sequelize db:migrate` etc

**Comment by fallsantos** [comment]
> Atualize sobre isso. Parece que meu colega precisou usar o dotenv-cli e migrar com o `dotenv sequelize db:migrate`etc

Foi justamente isso, basta saber como resolver agora.

**Comment by balkoonline** [comment]
Like @mmarovich mentioned the issue could be that sequelize process runs before dotenv is fully initiated. Solution which works is to define individual vars/constants before calling new Sequelize() and then use those vars in Sequelize options as arguments so they will not be read as the reference to configs/dotenv object.

Example:

```
const database = process.env.DB_DATABASE;
const username = process.env.DB_USER;
const password = process.env.DB_PASSWORD;
```
or like in this particular case
```
const database = configs.DATABASE_NAME;
const username = configs.DATABASE_USER;
const password = configs.DATABASE_PASSWORD;
```
and then
```
const sequelize = new Sequelize(
    database,
    username,
    password
);
```
