### ISSUE TITLE
return the updated records using sqlite

### ISSUE THREAD

**Issue by munzx** [sequelize/sequelize#7478]
it's not possible to return the updated record when using sqlite database. I tried all examples i found online but nothing has worked for me. Here's a code i've tried.

`        User.update({
            name: req.body.user.name,
            password: req.body.user.password
        }, {
            where: {id: req.params.id},
            returning: true,
            plain: true
        })`

**Comment by janmeier** [comment]
It's simply not possible to get back the ids of the affected rows in sqlite - You could do a `find` with the same where clause to get the rows

**Comment by cirosantilli** [comment]
SQLite implemented it in 2021 apparently: https://www.sqlite.org/lang_returning.html
