### ISSUE TITLE
Update on cascade doesn't work with update()

### ISSUE THREAD

**Issue by mattp94** [sequelize/sequelize#7479]
Hello,

I'm using sequelize in my Koa project. I have two tables in my database: `users` & `documents`.
There is a **one-to-one association** between them as a **user has one document**.

So, I defined the below association in my model:

```js
Users.hasOne(models.Documents, { foreignKey: 'users_id', onUpdate: 'cascade' })
```

When I use a simple findById(), it well works:

```js
await Users.findById(id, { include: [ Documents ] })

// {
//     name: 'Bob',
//     Document: {
//         title: 'Hello.txt'
//     }
// }
```

Now, I want to update these fields:

```js
const input = {
    name: 'John',
    Document: {
        title: 'Bye.txt'
    }
}
```

It doesn't work with the below syntax: only `name` is updated, not `title`.

```js
await Users.update(input, { where: { id }, include: [ Documents ] })
```

I'm forced to use this syntax which is not friendly:

```js
const user = await Users.findById(id, { include: [ Documents ] })

await Promise.all([user.updateAttributes({
    name: input.name
}), user.Document.updateAttributes({
    title: input.Document.title
})])
```

Is there a way to use directly `Users.update()`?

Thanks!

**Comment by sushantdhiman** [comment]
I dont think we support nested updates (we although do support nested creation http://docs.sequelizejs.com/en/v3/docs/associations/#creating-elements-of-a-belongsto-or-hasone-association)

Also cascade is not used to updated related records, it enforces dropping or blocking updates when parent model is updated http://stackoverflow.com/questions/1481476/when-to-use-on-update-cascade#1481524

**Comment by kvsystems** [comment]
If someone else comes in handy....

```
const ids = [1,2,3];
const user = await Users.findById(id);

// overwrite
user.setDocuments(ids);

// push
user.setDocument(ids[0]);
user.setDocument(ids[1]);
user.setDocument(ids[2]);
```
