### ISSUE TITLE
Cannot find module 'pg-native' from node_modules/pg/lib/native in MySql dialect 

### ISSUE THREAD

**Issue by delockdown** [sequelize/sequelize#7480]
Hi All,
I'm just creating connection to a MySql database and trying to check the connection via my angular appliction. every time I run my bundling process(Browserify process) it says
```
Error : Cannot find module 'pg-native' from  [myprojectpath]/node_modules/pg/lib/native
```
and bundling process is stopped. Here is the code I used. 
```js
var sequelize = new Sequelize('central', 'root', 'password', {
    host: "192.168.51.4",
    port: 3306,
    dialect: 'mysql'
});

module.exports = sequelize;
```
and in my controller I just ran following code,
```js
    sequelize
      .authenticate()
      .then(function () {
        console.log('Connection successful');
      })
      .catch(function (error) {
        console.log("Error creating connection:", error);
      });
```

I am using latest version 3.30.3. I have added this thing to application run on electron. 

Angular version: 1.5.8
Electron: 1.6.2

Regards, 
Thank you.

**Comment by janmeier** [comment]
You will need to configure browserify to exclude the other dialects - This is outside the scope of sequelize
