### ISSUE TITLE
Quick documentation improvement: many-to-many association 

### ISSUE THREAD

**Issue by DagmaraSz** [sequelize/sequelize#7481]
Hi, 
I'm using sequelize in an express app, with mysql as dialect. I spent ages trying to figure out why my join table in the many to many association wasn't being created and I was getting a reference error. In the end, turns out I just needed to use a string in the {through: ... } bit.

So proposing this change to docs (sequelize/docs/api/associations/belongs-to-many.md):

Instead of:
User.belongsToMany(Project, { through: UserProject });
Project.belongsToMany(User, { through: UserProject });

Let's have:
User.belongsToMany(Project, { through: "UserProject" });
Project.belongsToMany(User, { through: "UserProject" });

Wanted to pull request or smth, but don't how to, sorry!

**Comment by janmeier** [comment]
`UserProject` refers to the model defined on the line above :)

**Comment by DagmaraSz** [comment]
I realise that. What I'm trying to point out is that unless you put it within quotation marks, Express is going to throw errors at you before it even gets around to creating the UserProject join table.

**Comment by janmeier** [comment]
It's two different ways though - You can't expect the example to work if you only paste half of it ;)

Using a model is the preferred way (in my mind at least), since you have more control of naming + can add extra columns

**Comment by DagmaraSz** [comment]
Ok, fair. However, if you don't want to add any extra attributes to the join table, what's the point of defining the UserProject model? But if you don't define it, you're stuck with something js doesn't understand. Would you say the correct action in that case is to do: 
`UserProject = sequelize.define('user_project', { });`
or just use as string in the through bit as per my suggestion?

**Comment by janmeier** [comment]
Both would be correct, and give the same result
