### ISSUE TITLE
instanceMethods: not able to reach`this` anymore

### ISSUE THREAD

**Issue by HoneyryderChuck** [sequelize/sequelize#7483]
## What you are doing?

I defined a method in the instanceMethods module for one of my models:

```js
  const User = db.define('users', {
	id: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		autoIncrement: true,
	},
  ...
  {
     instanceMethods: {
      getContacts: (options => {
        console.log(this) // returns undefined
        ...
      })
    }
}

```

## What do you expect to happen?

I expect `this` inside the `instanceMethods` methods to point at the instance, as it is described in most of the documentation I find. Instead, I get `undefined`. This blocks me from using model attributes in instance-level queries. 

__Dialect:__ sqlite
__Database version:__ 3.14.0
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
That's how arrow functions work

**Comment by HoneyryderChuck** [comment]
hum, ES6 feature-not-a-bug? Is there a way to bind them in such a scenario, or I don't have a choice?

**Comment by sushantdhiman** [comment]
Use a normal function instead of arrow function here
