### ISSUE TITLE
Deadlock error when updating multiple rows at once with Promise.all

### ISSUE THREAD

**Issue by raz3r** [sequelize/sequelize#7484]
I am trying to make multiple updates at once on a specific model but I get an error.

```
var promises = [];
for (var i = 0; i < workflow.steps.length; i++) {
promises.push(
	models.step.update({
		stepOnSuccessStepId : workflow.steps[i].stepOnSuccessStepId,
		stepOnFailStepId : workflow.steps[i].stepOnFailStepId
	},{
		where : {
			stepId : workflow.steps[i].stepId
		}
	})
);
}
Promise.all(promises).then(function(values) {

});
```

I have a model named Step that has a simple ID and two foreign keys defined like this:

```
Step.belongsTo(Step, {
as : 'stepOnSuccess'
});
Step.belongsTo(Step, {
as : 'stepOnFail'
});
```

Step model initially is like this in the database.

stepId: 2,3,4,5
stepOnSuccessStepId: null,null,null,null
stepOnFailStepId : null,null,null,null

Then I try to update the model like this.

stepId: 2,3,4,5
stepOnSuccessStepId: 0,4,5,0
stepOnFailStepId: -1,2,3,4

However the the Step with ID 4 is not updated and the other two fields remain null.

I get the following error.

> Unhandled rejection SequelizeDatabaseError: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction

Since I am upadting 4 rows with different IDs I don't understand why it's giving me a deadlock error. Can it be related to the amount of connections being made?

I am using bluebird for promises.

__Dialect:__ mysql
__Database version:__ 5.6
__Sequelize version:__ latest

**Comment by raz3r** [comment]
I also tried with Promise.each but I get the same error and again, the third row is not updated.

```
Promise.each(workflow.steps, function(step) {
			models.step.update({
				stepOnSuccessStepId : step.stepOnSuccessStepId,
				stepOnFailStepId : step.stepOnFailStepId
			},{
				where : {
					stepId : step.stepId
				}
			});
		}).then(function(values) {

		});
```

**Comment by sushantdhiman** [comment]
> particular model has two foreign keys that reference itself.

Yeah that may be the problem, I suggest running them with `.each` (I saw you have already tried it, but you need sequential execution).

Deadlock error is not something we can help with, your rows depend upon each other and concurrently updating them will cause deadlock.

You may try using transaction (with proper isolation level) to solve this issue.

If you can give me a test case to work with (code which I can run like [this](https://github.com/sequelize/sequelize/issues/7268#issuecomment-280904532)), I may be able to help.

**Comment by vicenteguerra** [comment]
For me, works first find and next update 

```javascript
models.step.findOne({
  where: {
    stepId : workflow.steps[i].stepId
  }
}).then(function(step){
  step.update({
    stepOnSuccessStepId : step.stepOnSuccessStepId,
    stepOnFailStepId : step.stepOnFailStepId
  });
});
```
