### ISSUE TITLE
Does sequelize compatible with Vuejs ?

### ISSUE THREAD

**Issue by lyquocnam** [sequelize/sequelize#7491]
Hi ad, i tried use vuejs project with sequelize, but error:
```
These dependencies were not found:

* fs in ./~/pgpass/lib/index.js, ./~/bindings/bindings.js
* dgram in ./~/native-dns/lib/server.js, ./~/native-dns/li

To install them, you can run: npm install --save fs dgram
```
so i try:
`npm install --save fs dgram`
but it still now working...

**Comment by janmeier** [comment]
vue is a frontend (browser) framework  - sequelize is meant to be used on the backend (server)
