### ISSUE TITLE
comparing child table column in parent table where condition

### ISSUE THREAD

**Issue by RanjeetAvghad** [sequelize/sequelize#7495]
example : let's say i have tables Vehicle, Car, Bike
vehicle belongs to Car and Bike

i have query like:

models.findAll({
where :{user_id:1}
include:[{model:models.Car,required:false},{model:models.Bike, required:false}]
});

i want Vehicle result only if Car or Bike is returned 

it gives me result even if Car and Bike is null but vehicle has id.

**Comment by harshithkashyap** [comment]
You should pass `required: true` instead of `required: false` to convert this to an inner join.

**Comment by RanjeetAvghad** [comment]
yes but if i add required true then Or operation will not done.
**i want Vehicle result only if Car _or_ Bike is returned**

so required: true will not be the solution

**Comment by harshithkashyap** [comment]
You can't perform an OR operation as bike and car are not related and you are joining both of them to vehicle. You can use the following in the where clause. You are expecting the foreignKeys carId or bikeId to not be null.
```
where: {
 $and: [
    { $or: [{ carId: { $ne: null }, { bikeId: { $ne: null }}] },
    { user_id: 1 }
  ]
}
```
