### ISSUE TITLE
Limit on findAll doesn't work with associations

### ISSUE THREAD

**Issue by thatisuday** [sequelize/sequelize#7500]
__Dialect:__ mysql
__Database version:__  Ver 14.14 Distrib 5.7.17, for Win64 (x86_64)
__Sequelize version:__ 3.30.2

I am not able to limit the results with **findAll** query which has associations with where clause on it.

```
where : {
	status : 'active'
},
include : [{
	model : ProductCategory,
	as : 'categories',
	where : {
		urlKey : req.params.urlKey
	}
}],
limit : 2
```

Here, I am trying to fetch products when included product category has a particular key. This returns empty result when limit is added. Problem seems to be `where` clause because once I remove it, it works with limit on.

**Comment by thatisuday** [comment]
Adding `subQuery: false` worked. What happened here?

**Comment by armgoja** [comment]
I can confirm that subQuery options fix it, but why ?
