### ISSUE TITLE
Sequelize transactions do not work. I try to create a record that depends on a previous creation

### ISSUE THREAD

**Issue by ahelord** [sequelize/sequelize#7501]
## What you are doing?
Good afternoon some expert that I collaborate with a simple transaction in sequelize, I want to create an user and later to create a staff with the id_user of the user: I have this
```js
var user = require('../../models/index').user;
var staff = require('../../models/index').staff;
var models = require('../../models/index');
module.exports = {
 transaction(req, res) {
   return models.sequelize.transaction(function (t) {

            // chain all your queries here. make sure you return them.
            return user.create(req.body, {transaction: t}).then(function (userCreated) {
                var staff = {id_user: userCreated.id_user}
                return staff.create(staff, {transaction: t}).then(function (staffCreated) {
                });
            });

        }).then(function (result) {
            console.log("entro sin errores")
            res.status(200).json(result)
            // Transaction has been committed
            // result is whatever the result of the promise chain returned to the transaction callback
        }).catch(function (err) {
            console.log(" errores")
            res.status(500).json(err)
            // Transaction has been rolled back
            // err is whatever rejected the promise chain returned to the transaction callback
         #});
}
}
```

## What do you expect to happen?
But in the record of the log it starts that the transaction inserts the user and then does rollback, does not try to create the staff do not know that some help can be wrong and print "errores".
But if I create the user and save it in the clause "then" and I nested the other promise with the creation of the staff works without problems (without transactions)

_Output, either JSON or SQL_

Executing (b97a07c8-47c0-4913-9a2a-9eba469928bc): START TRANSACTION;
Executing (b97a07c8-47c0-4913-9a2a-9eba469928bc): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (b97a07c8-47c0-4913-9a2a-9eba469928bc): INSERT INTO "user" ("id_user","identification_number","id_identification_type","id_profile","id_gender","email","password","birth_date","first_name","last_name","mobile","telephone","address","enable","health_promotion_company","medical_restriction","work_telephone","extension_number","emergency_telephone","setup","created_at","updated_at") VALUES (DEFAULT,'9999999999',0,1,1,'admin_final007@centros.test.com','Y2hlY2tMZW1vblBydWViYXMyMDE3Kw==','2016-12-15 00:00:00.000 -05:00','User','Test',1,1,'1',true,NULL,NULL,NULL,NULL,NULL,false,'2017-04-04 17:05:18.989 -05:00','2017-04-08 17:18:58.672 -05:00') RETURNING *;
Executing (b97a07c8-47c0-4913-9a2a-9eba469928bc): ROLLBACK;

__Sequelize version:__ 3.30.4
__Dialect:__ postgres
__Database version:__ 9.4

**Comment by iamjoyce** [comment]
That's because you overwrote your `staff` variable.

Initially `staff` was a Sequelize model.

But you overwrote it with `var staff = {id_user: userCreated.id_user}`.

Try using another variable name e.g. `var newStaff= {id_user: userCreated.id_user}` and it should work fine.
