### ISSUE TITLE
Time Zone UTC

### ISSUE THREAD

**Issue by vixa2012** [sequelize/sequelize#7503]
Hello. Please help me. When I added timezone: "UTC",

i got exception **SequelizeBaseError: Unknown or incorrect time zone: 'UTC'**

Now I have time 17:48, if I will add timezone : '+00:00' server will show 20:48, but it have to be 14:48.

How i can set up utc timezone?

**Comment by iamjoyce** [comment]
By default, Sequelize uses UTC timezone. Have you tried **not** specifying `timezone` property in your options?

**Comment by sushantdhiman** [comment]
Sequelize assume two things

1. Your DB server is running in UTC
2. Your App server if running in non UTC server, you have configured `Sequelize.options.timezone` to specify your current timezone.

Please checkout [this discussion](https://github.com/sequelize/sequelize/pull/7290#issuecomment-284207184) and [this one](https://github.com/sequelize/sequelize/issues/854#issuecomment-29069241) for more details

**Comment by jlapton** [comment]
@sushantdhiman What if my db server is running on local timezone? These timezone issues puzzled me a lot :(

**Comment by mhbseal** [comment]
@sushantdhiman @jlapton I have the same problem

**Comment by carlosscheffer** [comment]
Have you found a solution?
