### ISSUE TITLE
Contradictions in documentation

### ISSUE THREAD

**Issue by Alexsey** [sequelize/sequelize#7506]
On <a href="http://docs.sequelizejs.com/en/latest/docs/models-definition/ ">models definition page</a> on definition of `underscored` property it says
```
  // don't use camelcase for automatically added attributes but underscore style
  // so updatedAt will be updated_at
```
at the same time on <a href="docs.sequelizejs.com/en/latest/api/sequelize/">API page</a> in section related to `[options.createdAt]`, `[options.updatedAt]` and `[options.deletedAt]` all have sentence `Not affected by underscored setting`

Upd.:
As far as I can see `underscored` affects `createdAt`, `updatedAt` and `deletedAt`. And I think this is how it should be

**Comment by janmeier** [comment]
I see how this is not 100% clear. `Not affected by underscored setting` means that if you add `{ createdAt: 'fooBar` }` in the options object, it will not be converted to `foo_bar`, even if `underscored` is true.

You are free to provide a PR if you can come up with a better wording ;)
