### ISSUE TITLE
Feature: Changing database credentials after sequelize init

### ISSUE THREAD

**Issue by StyleT** [sequelize/sequelize#7507]
I'm planning to use Sequelize together with dynamic DB credentials (provided by [Vault](https://www.vaultproject.io/docs/secrets/mysql/index.html)) which can be retrieved when app already running & expire in 30min for example. For this I need some method to refresh them inside Sequelize so that new connections will be established using new creds.

I found #3190 & looks like nothing changed since that time, feature wasn't implemented. Please correct me if I'm wrong.

Any implementation suggestion appreciated. If it's not a very big amount of work & can be included in current major release I would say that it's possible to contribute this feature as a part of my current job.

**Comment by kristofferostlund** [comment]
I am also interested in this feature as we use auto rotating password at work. This together with the ability to update credentials before attempting to add new connections to the pool would be awesome for how we work.

I could probably implementing this a go as well.

**Comment by StyleT** [comment]
Issue is still here as far as I know

**Comment by renatoargh** [comment]
I have a lot of interest in this feature (currently using v3). My scenario is the following: every user in our database has his own schema w/ his own set of tables. Each user in the application corresponds to a user in the database, with specific privileges for his own schema. What we need is the ability to reset credentials on every request (on a connection basis). More or less like the the following workflow:

`REQUEST ARRIVES -> APP RETRIEVES CONNECTION FROM THE POOL -> CONNECTION IS SET WITH RIGHT CREDENTIALS -> QUERIES ARE PERFORMED -> CONNECTION IS RELEASED TO THE POOL`

Is there any way I can achieve this with the latest v3? Or is it necessary some development?

**Comment by kristofferostlund** [comment]
I haven't had the time to create a fix for this as of yet, and since we've stopped using node at my current workplace I won't have the time to look into this at all sadly.

**Comment by marcusbalbi** [comment]
any news about this feature?

**Comment by papb** [comment]
If the suggestion by sushantdhiman above doesn't work for someone, let me know.
