### ISSUE TITLE
Rollback database when a migration fails automatically.

### ISSUE THREAD

**Issue by ezequielrozen** [sequelize/sequelize#7508]
Hi! Is there a way to make a rollback when a migration fails in the middle? In my development environment occurs many times then I have to make the rollback manually (remove new table, column, etc). I wouldn't like it occurs on production. I'm using alembic in  python in other project, for instance, and when something wrong happens the migration is rolled back automatically.

**Comment by sushantdhiman** [comment]
Migrated to CLI https://github.com/sequelize/cli/issues/455

**Comment by sushantdhiman** [comment]
It should be possible when we support using Transaction with migrations https://github.com/sequelize/sequelize/issues/1882
