### ISSUE TITLE
Can't resolve 'pg-hstore'

### ISSUE THREAD

**Issue by dlimkin** [sequelize/sequelize#7509]
May be necessary need move 'pg-hstore' with devDependencies in dependencies?

```js
ERROR in ./~/sequelize/lib/dialects/postgres/hstore.js
Module not found: Error: Can't resolve 'pg-hstore' in 'node_modules/sequelize/lib/dialects/postgres'
 @ ./~/sequelize/lib/dialects/postgres/hstore.js 3:15-35
 @ ./~/sequelize/lib/dialects/postgres/data-types.js
 @ ./~/sequelize/lib/data-types.js
 @ ./~/sequelize/lib/sequelize.js
 @ ./~/sequelize/index.js
```
__Dialect:__ any
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
pg-hstore is only installed in dev (when you run `npm install` directly in the sequelize directory) - In which case are you seeing this?

**Comment by dlimkin** [comment]
When I build my project with webpack.

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/search?q=webpack&type=Issues&utf8=%E2%9C%93

**Comment by rozzzly** [comment]
**This needs to be reopened**,  This is an issue with how `sequelize` conditionally `require`s its dependencies. If I can't just `yarn add sequelize` and have it work then _its a problem on your end_.  I'm using `mysql`, not using `postgress` so ideally the code that attempts `require('pg-hstore')` should never had ran. I didn't use to have this issue so its due to a regression. 

By the way, telling someone to "do a search first" isn't a constructive approach to fixing this when there's no other issues referring to this problem. I've done a search.

**Comment by alucic** [comment]
@janmeier Can you reopen this issue? 
It is impossible to bundle up code using webpack without installing all dependencies that are required. 

> Why are you trying to webpack sequelize at all - its a backend library?
https://github.com/sequelize/sequelize/issues/6142#issuecomment-227659153

Were deploying single bundled up file to the production servers and here all data types are being required which breaks our build since not all dependencies are installed
https://github.com/sequelize/sequelize/blob/v4.1.0/lib/data-types.js#L842-L845

**Comment by janmeier** [comment]
> This needs to be reopened, This is an issue with how sequelize conditionally requires its dependencies. If I can't just yarn add sequelize and have it work then it's a problem on your end. I'm using mysql, not postgress so ideally the code that attempts require('pg-hstore') should never had ran. I didn't use to have this issue so its due to a regression.

Hstore is only loaded, if you actually use it. https://github.com/sequelize/sequelize/blob/584b6f741251bc7928186ac190f48297c6a69e95/lib/dialects/postgres/data-types.js#L363

> @janmeier Can you reopen this issue?
It is impossible to bundle up code using webpack without installing all dependencies that are required.

I'm sure webpack can be configured to ignore some modules, but that is outside the scope of sequelize

**Comment by stunningpixels** [comment]
Even though i'm using Postgres as my dialect, it doesn't seem like Tedious is a conditional import.
Workaround by just installing Tedious but it is a little tedious ;) having to bundle unnecessary modules

Webpack build warnings and errors:

```
WARNING in ./node_modules/sequelize/lib/dialects/mssql/connection-manager.js
Module not found: Error: Can't resolve 'tedious' in '/Users/louiskw/Documents/GitHub/WhoTargetsMe-Backend/node_modules/sequelize/lib/dialects/mssql'
 @ ./node_modules/sequelize/lib/dialects/mssql/connection-manager.js 23:19-37
 @ ./node_modules/sequelize/lib/dialects/mssql/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ ./src/db/models.js
 @ ./src/handler.js

WARNING in ./node_modules/sequelize/lib/dialects/mysql/connection-manager.js
Module not found: Error: Can't resolve 'mysql2' in '/Users/louiskw/Documents/GitHub/WhoTargetsMe-Backend/node_modules/sequelize/lib/dialects/mysql'
 @ ./node_modules/sequelize/lib/dialects/mysql/connection-manager.js 33:19-36
 @ ./node_modules/sequelize/lib/dialects/mysql/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ ./src/db/models.js
 @ ./src/handler.js

WARNING in ./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
Module not found: Error: Can't resolve 'sqlite3' in '/Users/louiskw/Documents/GitHub/WhoTargetsMe-Backend/node_modules/sequelize/lib/dialects/sqlite'
 @ ./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js 27:19-37
 @ ./node_modules/sequelize/lib/dialects/sqlite/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ ./src/db/models.js
 @ ./src/handler.js

WARNING in ./node_modules/sequelize/lib/sequelize.js
374:61-74 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/sequelize/lib/dialects/mssql/connection-manager.js
21:19-62 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/sequelize/lib/dialects/postgres/connection-manager.js
21:16-59 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/sequelize/lib/dialects/mysql/connection-manager.js
31:19-62 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
25:19-62 Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/sequelize/lib/dialects/mssql/query.js
Module not found: Error: Can't resolve 'tedious' in '/Users/louiskw/Documents/GitHub/WhoTargetsMe-Backend/node_modules/sequelize/lib/dialects/mssql'
 @ ./node_modules/sequelize/lib/dialects/mssql/query.js 10:14-32
 @ ./node_modules/sequelize/lib/dialects/mssql/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ ./src/db/models.js
 @ ./src/handler.js

ERROR in ./node_modules/pg/lib/native/client.js
Module not found: Error: Can't resolve 'pg-native' in '/Users/louiskw/Documents/GitHub/WhoTargetsMe-Backend/node_modules/pg/lib/native'
 @ ./node_modules/pg/lib/native/client.js 10:13-33
 @ ./node_modules/pg/lib/native/index.js
 @ ./node_modules/pg/lib/index.js
 @ ./node_modules/sequelize/lib/dialects/postgres/connection-manager.js
 @ ./node_modules/sequelize/lib/dialects/postgres/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ ./src/db/models.js
 @ ./src/handler.js
```

**Comment by Maushundb** [comment]
Same issue as @stunningpixels, would love to have this reopened as well.

**Comment by EdByrnee** [comment]
Same issue

**Comment by corysimmons** [comment]
@janmeier Re-open until there's a solid workaround.

**Comment by louisremi** [comment]
I have been able to get rid of those warnings and errors using Webpack's built-in `NormalModuleReplacementPlugin` plugin:
```
new webpack.NormalModuleReplacementPlugin(
  /^(rc|yamlparser|tedious|pg-hstore|node-gyp|node-pre-gyp)$/,
  'lodash/noop' // This assumes lodash is already a dependency of your project
)
```

I'm no Webpack expert so I'm not sure it's the best solution (shimming might also work). I hope this helps :-)

**Comment by corysimmons** [comment]
Anyone in thread happen to know if Browserify/Rollup/etc suffer from this?

**Comment by kareljuricka** [comment]
Similar problem here when build with webpack. Using webpack-node-externals to make node_modules externals but does not help.

First possible workaround I found to build without errors is **install all dialect libraries**.

Second possible workaround is add array  ["pg", "sqlite3", "tedious", "pg-hstore"] to webpack externals, for me:

`externals: [nodeExternals(), ["pg", "sqlite3", "tedious", "pg-hstore"]]`

But warnings still remains - for example:

`WARNING in ./node_modules/sequelize/lib/sequelize.js
374:61-74 Critical dependency: the request of a dependency is an expression`

Inspirated from comment here  https://github.com/angular/angular/issues/11580#issuecomment-282705332 I rewrite this piece of code for sequelize, and warnings dissapeared:
```
new webpack.ContextReplacementPlugin(
            /Sequelize(\\|\/)/,
            path.resolve(__dirname, '../src')
          )
```

If anyone find better workaround, please write a comment. Also I agree that this issue should be reopened , as build bug using webpack.

**Comment by sparticvs** [comment]
The following fix worked for me in my `webpack.config.js`:
```
var config = {
    ...
    externals: ['pg', 'sqlite3', 'tedious', 'pg-hstore'],
};
```

**Comment by demiters** [comment]
The `externals: ...` workaround you guys listed worked. However, this seems to have almost doubled my webpacked chunk sizes. What to do about it?

**Comment by Ibbus93** [comment]
I met the same errors listed above. My project is available [here ](https://github.com/sebastianpodda/doutdes) and the package.json is [here](https://github.com/sebastianpodda/doutdes/blob/master/package.json). Should I add the webpack for avoiding this issue? Thanks!

**Comment by mschipperheyn** [comment]
Hmm, we saw an issue that looks like this out of the blue when we added `date-io`

**Comment by papb** [comment]
I agree this should not be closed...

**Comment by enBonnet** [comment]
> The following fix worked for me in my `webpack.config.js`:
> 
> ```
> var config = {
>     ...
>     externals: ['pg', 'sqlite3', 'tedious', 'pg-hstore'],
> };
> ```

This works to me

**Comment by igolopolosov** [comment]
> The following fix worked for me in my webpack.config.js
> var config = {
>     ...
>     externals: ['pg', 'sqlite3', 'tedious', 'pg-hstore'],
> };

Worked locally, but failed on pipeline.

**Comment by IazLur** [comment]
Please I have same issue without having webpack ?!!!!!!!

**Comment by athongintel** [comment]
Same problem here when trying to build single file application using webpack.

I suggest adding pg-hstore into dependencies instead of devDependencies.

**Comment by anhthu127** [comment]
> The following fix worked for me in my `webpack.config.js`:
> 
> ```
> var config = {
>     ...
>     externals: ['pg', 'sqlite3', 'tedious', 'pg-hstore'],
> };
> ```

it worked for me , many thanks

**Comment by PooriyaHVN** [comment]
i fix this problem in next js . my problem was used require() in src attribute img tag

**Comment by AshotN** [comment]
Had the same issue using Klex, tried Sequelize and hitting this issue.

**Comment by bob11m11** [comment]
Had this problem in Electron Forge w/ Webpack, trying to get a simple SQLite database and Sequelize wired up. 

None of the webpack.config options resolved it so on a whim I simply installed pg and pg-hstore as devDependencies, and the error went away. I'm not even trying to use PostGreSQL, I'm using SQLite as my dialect. Strange.

**Comment by briantical** [comment]
@bob11m11 your solution is not really viable. the number of modules to install will just keep increasing. I found a solution though I still don't understand why it works. 

The link is [here](https://github.com/netlify/netlify-lambda/issues/112#issuecomment-488644361) 

The issue no longer persists

**Comment by Trinovantes** [comment]
I think the problem is on https://github.com/sequelize/sequelize/blob/master/src/data-types.js#L1023 where it imports every dialect and Webpack (currently) isn't smart enough to infer at compile time that Postgres (https://github.com/sequelize/sequelize/blob/master/src/dialects/postgres/data-types.js#L361) will never be reached at runtime and thus will try to package all the dialects into the final bundle.

A possible backwards-compatible solution would be to change `data-types.js` to
```
if (!process.env.SEQUELIZE_DISABLE_POSTGRES) {
  dialectMap.postgres = require('./dialects/postgres/data-types')(DataTypes);
}
```
and just have Webpack users define `process.env.DISABLE_POSTGRES` to be `false` at compile time with the `DefinePlugin` so that Webpack's (dumb) dead code elimination pass will avoid including the other dialect drivers.

However, I have no idea what the implications will be if the `dialectMap` only has one dialect.

**Comment by Andersama** [comment]
Tried to make an app, this is definitely a pain point, was not using postgres, wasn't planning on using postgres, yet this is preventing me from getting started. The way the library reads it gives the impression you're set to use any of the databases as needed, not necessarily that all of them are required on the off chance you'll use several at the same time. Fairly certain the patches above will fix the issue. Consider this another vote for the above comment.

**Comment by diegoazh** [comment]
> , ["pg", "sqlite3", "tedious", "pg-hstore"]

I had to deal with the same issue in a serverless application of azure functions and the following configuration works well for me

```js
// webpack.config.js

module.exports = {
  ...
  externals: [nodeExternals(), 'pg', 'sqlite3', 'tedious', 'pg-hstore'],
  plugins: [
    new webpack.ContextReplacementPlugin(
      /Sequelize(\\|\/)/,
      path.resolve(__dirname, './src'),
    ),
  ],
  ...
}
```

**Comment by papb** [comment]
Hello, I will concentrate all efforts involving Webpack problems in this new issue: #13169 - Please help me there if possible.

**Comment by qld-cf** [comment]
webpack add 
externals: ['pg-hstore'],

**Comment by upkhoev** [comment]
use https://www.npmjs.com/package/esbuild-plugin-ignore

**Comment by ephys** [comment]
Since this is very relevant to this thread, see my answer on how you can work around this, and how we're fixing it: https://github.com/sequelize/sequelize/issues/13169#issuecomment-1387465063

**Comment by misterrodger** [comment]
Was getting the pg-hstore error in a monorepo.  Tried the above solutions with partial success

Then read about [externals](https://webpack.js.org/configuration/externals/) and have fixed everything by simply adding to the webpack.config:

externals: 'sequelize'

**Comment by SamuelBucher** [comment]
I don't know what a webpack is, but I have been getting this issue when trying to make Sequelize work with npm

![image](https://user-images.githubusercontent.com/56469863/231628578-1829212a-2207-4ec8-b54f-828af9de8221.png)
![image](https://user-images.githubusercontent.com/56469863/231628716-d26e51a2-4445-4752-a822-73a6acc4d7f1.png)

**Comment by Robert-Ernst** [comment]
In **AstroJS** this is the intended way of solving this:

In the root folder create a file with the name `astro.config.mjs`

```
import { defineConfig } from "astro/config";
export default defineConfig({
  vite: {
    optimizeDeps: {
      exclude: ['sequelize', 'sqlite3'],
    },
  }
});
```
Explanation:
AstroJS uses Vite under the hood. This way it will be excluded from the build(?) process. I assume it tries to rebuild/treeshaking the dependencies. It works for me.

Source:
- https://docs.astro.build/en/reference/configuration-reference/#vite
- https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-exclude

**Comment by WikiRik** [comment]
> I don't know what a webpack is, but I have been getting this issue when trying to make Sequelize work with npm
> 
> And the funny thing is that Sequelize launches for me just fine if I use "node" to launch it.


You're using parcel which is another bundler. From a quick Google search, I think using [`ignoreNodeModules`](https://parceljs.org/features/targets/#includenodemodules) could be used to ignore sequelize although I have no experience with using parcel

**Comment by SamuelBucher** [comment]
> > I don't know what a webpack is, but I have been getting this issue when trying to make Sequelize work with npm
> > And the funny thing is that Sequelize launches for me just fine if I use "node" to launch it.
> 
> You're using parcel which is another bundler. From a quick Google search, I think using [`ignoreNodeModules`](https://parceljs.org/features/targets/#includenodemodules) could be used to ignore sequelize although I have no experience with using parcel

I already solved my issue. Turns out I just didn't have pg-hstore installed.

**Comment by manuchis** [comment]
> 

I had the same issue with NextJS 13, I've solved it by adding 'sequelize' to the 'next.config.mjs' under the 'experimental' label: 
`serverComponentsExternalPackages: ['sequelize']`

**Comment by Danielgzp** [comment]
> > 
> 
> I had the same issue with NextJS 13, I've solved it by adding 'sequelize' to the 'next.config.mjs' under the 'experimental' label: `const nextConfig = { output: 'standalone', experimental: { appDir: true, serverComponentsExternalPackages: ['sequelize'] } } module.exports = nextConfig; `

This totally worked for me

**Comment by tjgragg** [comment]
Sorry to bring this back up, but I'm getting this same error when trying to run `sam build` for an AWS lambda. Using Node/TS.
I'm just trying to use sequelize with mysql2.

**Comment by WeiGrand** [comment]
> > 
> 
> I had the same issue with NextJS 13, I've solved it by adding 'sequelize' to the 'next.config.mjs' under the 'experimental' label: `const nextConfig = { output: 'standalone', experimental: { appDir: true, serverComponentsExternalPackages: ['sequelize'] } } module.exports = nextConfig; `

Same situation  and this works for me. I just wonder why this work, can anyone explain it?

**Comment by EnkhAmar** [comment]
> Sorry to bring this back up, but I'm getting this same error when trying to run `sam build` for an AWS lambda. Using Node/TS. I'm just trying to use sequelize with mysql2.

I have same happened to me when trying use with mysql and node/ts . This occurs when i try to test my serverless function with
`sls offline`

**Comment by EnkhAmar** [comment]
> > Sorry to bring this back up, but I'm getting this same error when trying to run `sam build` for an AWS lambda. Using Node/TS. I'm just trying to use sequelize with mysql2.
> 
> I have same happened to me when trying use with mysql and node/ts . This occurs when i try to test my serverless function with `sls offline`

I have solved it simply just putting 'pg-hstore' in exclude of esbuild.
Config below is my serverless.ts
```serverless.ts
custom: {
   ...other custom

    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ['aws-sdk', 'pg-hstore'],
      target: 'node18',
      define: { 'require.resolve': undefined },
      platform: 'node',
      concurrency: 10,
    },
  },
```

**Comment by Jan-T-Berg** [comment]
I make a new Next13 Application with src and app folder. 

install sequelize

connect to mysql2 and get
Module not found: Can't resolve 'pg-hstore'


It works with:
const nextConfig = { output: 'standalone', experimental: { appDir: true, serverComponentsExternalPackages: ['sequelize'] } } module.exports = nextConfig; 


but its bad for our CI/CD. Pls fix it

**Comment by ephys** [comment]
There is nothing to fix on our end. Marking these packages as external is exactly what you need to do. They are not designed to be bundled.

**Comment by unikitty37** [comment]
@ephys Would it be worth at least mentioning this in the [Getting Started](https://sequelize.org/docs/v7/getting-started/) page? It seems like a lot of people have ended up here trying to find out how to fix the problem, so it's maybe not as intuitive as you think…

**Comment by RLain** [comment]
> Was getting the pg-hstore error in a monorepo. Tried the above solutions with partial success
> 
> Then read about [externals](https://webpack.js.org/configuration/externals/) and have fixed everything by simply adding to the webpack.config:
> 
> externals: 'sequelize'

This worked for me.

```
module.exports = {
    externals: {
        '@aws-sdk/client-secrets-manager': '@aws-sdk/client-secrets-manager',
        'sequelize': 'sequelize'
    },
  ...etc
```

**Comment by AlexanderPolenov** [comment]
To make it work with MySQL & NextJS 15+ add this to next.config.mjs:
```
const nextConfig = {
    serverExternalPackages: ['sequelize'],
};
```
Also, when connect to DB use `127.0.0.1` and not the `localhost`. Because this will be the second problem that you will face.
