### ISSUE TITLE
Obsolete classMethods and instanceMethods in latesl docs

### ISSUE THREAD

**Issue by Alexsey** [sequelize/sequelize#7513]
In <a href="http://docs.sequelizejs.com/en/latest/api/sequelize/">latest docs for v4</a> there is still a description of classMethods and instanceMethods. But according <a href="http://docs.sequelizejs.com/en/latest/changelog/">to change log</a> in has been removed in 4.0.0-1. So it should be removed from the docs or (better) marked as removed

**Comment by janmeier** [comment]
As of https://github.com/sequelize/sequelize/pull/7490, docs are automagically generated - So this issue will be fixed once we switch away from RTD

Thanks for pointing it out though :)
