### ISSUE TITLE
defaultScope: Way to generate values at "query time"

### ISSUE THREAD

**Issue by nbrady-techempower** [sequelize/sequelize#7515]
## What you are doing?

Trying to define a model with a defaultScope using a value that needs to be generated at "query time". 

```js
  return sequelize.define("entries", {
    key: DataTypes.STRING,
    text: DataTypes.TEXT,
    privacy: DataTypes.STRING,
    name: DataTypes.STRING,
    title: DataTypes.STRING,
    filename: DataTypes.STRING,
    expiration: DataTypes.STRING,
    created: DataTypes.STRING
  }, {
    defaultScope: {
      where: {
        $or: [
          {
            expiration: { $gt: postgresTimestamp() }
          },
          {
            expiration: null
          }
        ]
      }
    },
    timestamps: false
  });
```

## What do you expect to happen?
postgresTimestamp() to generate a new value when the query is performed

## What is actually happening?
Same value

_Output, either JSON or SQL_

__Dialect: postgres
__Database version: 9.6
__Sequelize version: 3.30.4

**Comment by nbrady-techempower** [comment]
### Note

I am able to do this in scopes like:

```js
    scopes: {
      available: function() {
        return {
          where: {
            $or: [
              {
                expiration: { $gt: postgresTimestamp() }
              },
              {
                expiration: null
              }
            ]
          }
        }
      }
    },
```
This produces a new value every time, but I have to use `.scope('available')` instead of making it the default. When I try to do the same on defaultScope, an error is thrown. Is this functionality not available?

**Comment by janmeier** [comment]
For performance reasons the default scope is resolved once, so it cannot be a function.

But you can use `expiration: { $gt: sequelize.fn('NOW') }`

**Comment by nbrady-techempower** [comment]
Thanks @janmeier 

Was looking at it for more than just timestamps but this answers my question.
