### ISSUE TITLE
MS SQL: $or generating AND SQL statement

### ISSUE THREAD

**Issue by charlieargue** [sequelize/sequelize#7516]
## What you are doing?
Using sequelize with MS SQL Server, using a where $or clause.

```js
var searchACS = {
      color: {
        $like: color
      },
      species: {
        $like: species
      }
    };
...
model.sequelize.authenticate().then(function () {
        model.inventory_antibody.findAll({
          where: {
            $or: [searchACS]
          },
          raw: true,
        }).then(function (results) {
      ...
```

## What do you expect to happen?
_I wanted an OR statement produced/generated, but using SQL profiler I'm seeing an AND generated!_

## What is actually happening?
_But the output was an AND!_

```
exec sp_executesql @statement=N'SELECT [_id], [antibody], [color], [amount], [department], [species] FROM [inventory_antibody] AS [inventory_antibody] WHERE (([inventory_antibody].[color] LIKE N''%3%'' AND [inventory_antibody].[species] LIKE N''%u%''));'
```

__Dialect:__ mssql
__Database version:__ SQL2014, vers. 12.0.5000.0
__Sequelize version:__ 3.30.4 (failed with 3.30.2 also)

Thanks!

**Comment by harshithkashyap** [comment]
You should pass an array of objects to `$or`. This should fix it.
```
var searchACS = [{
      color: {
        $like: color
      },
    },{
      species: {
        $like: species
      }
    }];
...
model.sequelize.authenticate().then(function () {
        model.inventory_antibody.findAll({
          where: {
            $or: searchACS
          },
          raw: true,
        }).then(function (results) {
      ...
```

**Comment by charlieargue** [comment]
Thanks! It sure did.

* Karl Golka*
*Senior Full-Stack C#.NET / AngularJS / NodeJS Application Developer*
contact@karlgolka.com
*cell*: (619) 581-6529
*voip*: (630) 687-1410
*skype*: webstruments
