### ISSUE TITLE
Cannot get model definition from sequelize.models.<modelname>

### ISSUE THREAD

**Issue by NobleUplift** [sequelize/sequelize#7521]
I found a reference in the code to saving model definitions in sequelize.models.modelname here:

https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L308

## What you are doing?
I have all of my model definitions generated by sequelize-auto, so they look like this:

```js
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('account', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    parent_account_id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      references: {
        model: 'account',
        key: 'id'
      }
    },
    master_account_id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      references: {
        model: 'account',
        key: 'id'
      }
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    // ...
```

## What do you expect to happen?
I expected to be able to get the column definition with: `sequelize.models.account.id = {type: DataTypes.BIGINT, allowNull: false, primaryKey: true, autoIncrement: true}`

## What is actually happening?
It says sequelize.models.account.id is undefined.

__Dialect:__ mysql
__Database version:__ 5.6.35
__Sequelize version:__ 3.30.4

**Comment by NobleUplift** [comment]
I was referencing the wrong variable. It was actually sequelize["modelManager"].getModel('account').attributes.id.type.key to get the input type of the account ID, for example.

**Comment by tomprogers** [comment]
Here's code I use to get a hash of all registered models:

```
sequelizeInstance.modelManager.models.reduce( ( hash, model ) => ( {
	...hash,
	[ model.name ]: model
} ), {} )
```
