### ISSUE TITLE
Transactions - commit manual managed transaction

### ISSUE THREAD

**Issue by roytz** [sequelize/sequelize#7525]
## What you are doing?
I want to create a transaction and control which queries it will run.
I want to do that using node 7.8.0 and async/await syntax.
Here is a sample of the code I'm trying to run -
```
const transaction = await db.sequelize.transaction();
await db.User.create({ username: 'roy' }, { transaction });
await transaction.commit();
```

## What do you expect to happen?
The transaction to complete

## What is actually happening?
I get this error-
```
commit has been called on this transaction(3b1ab60a-172c-4795-9ace-b89b855c92ce), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
```

btw, if I run my code without using transactions it works. I just want to understand how to use transactions the right way using async/await.

Thanks.

__Dialect:__ postgres
__Sequelize version:__ 4.0.0-2

**Comment by dkushner** [comment]
This feature is desperately needed for code quality purposes and to ease the pain of testing with Sequelize at the moment.

@roytz, from everything I could find, the prescribed way to use transactions is to perform all of the operations you need to do from within the context of the next handler in the promise chain like so:

```
await db.sequelize.transaction().then(async transaction => {
    await db.User.create({ username: 'roy' }, { transaction })
})
``` 

Which I find fairly annoying to deal with.

**Comment by roytz** [comment]
thanks @dkushner

**Comment by kfrajtak** [comment]
In my case the problem was a stupid mistake - missing `await` when calling the `save` 
```
await entity.save({ transaction });
```

**Comment by ChaelWafo** [comment]
What if it,s inside a route and i cannot use the keyword await ?

**Comment by bhumit070** [comment]
Hello guys I am getting the same error and here is my code

`
const Order = require('../../db/index').order;
const db = require('../../db/index');

exports.createOrder = async (req, res) => {
  try {
    const orderTransaction = await db.sequelize.transaction();
    // data is an array which needs to inserted inside Order table
    const { data } = req.body;
    data.forEach(
      async (order) =>
        await Order.create(order, { transaction: orderTransaction }),
    );
    await orderTransaction.commit();
    return res.status(200).json(data);
  } catch (error) {
    console.log('error is', error);
    await orderTransaction.rollback();
  }
};
`

**Comment by rhayart** [comment]
@bhumit070 the simplest way to do that is to transform your loop into simple loop (for of, for in, for, ...)

```
const Order = require('../../db/index').order;
const db = require('../../db/index');

exports.createOrder = async (req, res) => {
  try {
    const orderTransaction = await db.sequelize.transaction();
    // data is an array which needs to inserted inside Order table
    const { data } = req.body;
    
    for(const order of data) {
        await Order.create(order, { transaction: orderTransaction }),
    }

    await orderTransaction.commit();
    return res.status(200).json(data);
  } catch (error) {
    console.log('error is', error);
    await orderTransaction.rollback();
  }
};
```

The other way is to group everything in a Promise.all(), but i find that way more complex reading.

**Comment by Ravi1717** [comment]
I am getting the same error, please help me out.

exports.registerSubAdmin = async (req, res) => {
  const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).send({ errors: errors.array() });
    }
    try {
  const result = await db.sequelize.transaction(async (transact) => {
  const { token } = req.params;
  const { email, name, newPassword,confirmPassword, phone, profile_photo, } = req.body;

  jwt.verify(token, config.secret, async(err, verifiedJwt) => {
    if(err)
     return res.status(400).send({
        status:{
          "msg": "Token in Invalid! Please resend the link.",
          "action_status": false
      }
      });

      let user = await db.User.findOne({ where: { email } },{transaction: transact});
       if (user) {
        return res.status(400).send({
          status:{
            "msg": "Email already registered. Please use different email.",
            "action_status": false
        }
        });
     }

      if (newPassword !== confirmPassword) {
       return res.status(400).send({
          status:{
            "msg": "Password does not match.",
            "action_status": false
        }
        });
      }
      let newPasswordHash = await bcrypt.hash(newPassword, 10);
      let result =  await db.User.create({ 
        name: name,
        email:email,
        password: newPasswordHash, 
        phone: phone,
        role:"sub admin",
        profile_photo:profile_photo 
      }, {transaction: transact});
      if (result) {
        return res.status(200).send({
          status:{
            "msg": "Sub Admin registration successfull!",
            "action_status": true
        },
        });
      }
  });
});
    } catch (error) {
      res.status(500).send({
      status: 'Failed',
      message: error.message,
      data: null,
      description: error,
    });
    }
};

**Comment by rhayart** [comment]
Hi @Ravi1717,

This line seems incorrect : 
`let user = await db.User.findOne({ where: { email } },{transaction: transact});`

The transaction parameter should be at the root level like this : 

```
let user = await db.User.findOne({ 
      where: { email }, 
      transaction: transact
});
```

If does not help i recommend you to convert the `jwt.verify` to a synchronous  function to extract the content : 

```
const verified = jwt.verify(token, config.secret);
let user = await db.User.findOne({ 
	where: { email },
	transaction: transact
});
...
```

That way `jwt.verify` run synchronous and if is invalid it throw an error and you can catch it in a try...catch.

**Comment by Ravimatrix** [comment]
Hi @rhayart, the issue has been resolved. I forget to use await within the async block so that's why I was getting the error.
Thanks for the help.

 await jwt.verify(token, config.secret, async(err, verifiedJwt) => {
    if(err)
     return res.status(400).send({
        status:{
          "msg": "Token in Invalid! Please resend the link.",
          "action_status": false
      }
      });
