### ISSUE TITLE
Associations not generating appropriate columns

### ISSUE THREAD

**Issue by christopherdiehl** [sequelize/sequelize#7526]
I'm trying to associate `Products` model with `User` model while making sure to force sync in order to ensure that the newest changes are present. I get the error that columns `UserId and ProductManagerId` are not created.

 Why are the columns not auto-generated?

Product.js

```
'use strict';
/* Model ONLY for DePuy Products */
module.exports = function(sequelize, DataTypes) {
  var Product = sequelize.define('Product', {
    name: {
      type: DataTypes.STRING,
      allowNull : false
    },
    sku: {
      type:DataTypes.STRING,
      allowNull: false,
      primaryKey: true,
    },
  }, {
    classMethods: {
      associate: function(models) {
        Product.belongsTo(models.User,{ as : 'ProductManager'});
        // associations can be defined here
      }
    }
  });
      Product.sync({force: true}).then(() => {
        console.log('Sequelize forced');
      })

  return Product;
};
```

User.js

```
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      unique: true,
    },
  }, {
    classMethods: {
      associate: (models) => {
        // associations can be defined here
        User.hasMany(models.Product);
      },
    },
    freezeTableName: true,
  });
  // FORCE FOR NOW Use only if make model changes
    User.sync({force: true}).then(() => {
     console.log('Sequelize forced');
   })
  return User;
};

```

__Dialect:__  postgres
__Sequelize version:__ 3.30.1

Ps. I originally used sequelize-cli to generate the model file, then changed to my needs.

**Comment by harshithkashyap** [comment]
You are using sync before the models are associated. You should call `Model.sync` after you call the classMethods -> associate.

**Comment by christopherdiehl** [comment]
@harshithkashyap  I'm not quite sure I understand what you mean. I am calling sync after associate.

**Comment by harshithkashyap** [comment]
@christopherdiehl I believe you are requiring the models in a loop as of `express-sequelize` correct? You should call sync after this line https://github.com/sequelize/express-example/blob/master/models/index.js#L25-L29
When you require a model, you are only defining the classMethods associate function. You call the associate function as above. But the sync function is called even before the models are associated. Hence you are ending with without foreignKey.
