### ISSUE TITLE
CURRENT_TIMESTAMP MySQL

### ISSUE THREAD

**Issue by fegauthier** [sequelize/sequelize#7527]
Hi guys,

I used sequelize-auto to generate Models from my database. Everything works fine. But now when i want to create an instance of a model to the database, my timestamp column is not update to the current timestamp.

There is my call to create the model instance in the database

![screen shot 2017-04-14 at 11 56 46 pm](https://cloud.githubusercontent.com/assets/12112673/25060549/0cba88a6-216e-11e7-9bc6-76b8ef6a6b2b.png)

There is my model file

![screen shot 2017-04-14 at 11 57 23 pm](https://cloud.githubusercontent.com/assets/12112673/25060552/207229da-216e-11e7-903a-8196c33ebdee.png)

This is my POST request with Postman

![screen shot 2017-04-14 at 11 58 02 pm](https://cloud.githubusercontent.com/assets/12112673/25060555/3b40a962-216e-11e7-80f4-cf0da35bf05a.png)

This is the response

![screen shot 2017-04-14 at 11 59 24 pm](https://cloud.githubusercontent.com/assets/12112673/25060572/72d814be-216e-11e7-9e63-f84432683712.png)

This is what I have in my database

![screen shot 2017-04-14 at 11 59 31 pm](https://cloud.githubusercontent.com/assets/12112673/25060573/79cdaf0e-216e-11e7-8964-affee6e93657.png)

As you can see, the fields "createdAt" and "updatedAt" are set to nothing...
I don't know what to do? Somebody can help me?

__Dialect:__ mysql
__Database version:__ 
![screen shot 2017-04-14 at 11 54 34 pm](https://cloud.githubusercontent.com/assets/12112673/25060533/c2026fae-216d-11e7-9fb6-516e9941d05f.png)

__Sequelize version:__ 3.30.4

**Comment by OpenGG** [comment]
This was a bug of `sequelize-auto`, which is now fixed.
https://github.com/sequelize/sequelize-auto/issues/147

**Comment by pursual** [comment]
This bug is back in 4.1.0

**Comment by pursual** [comment]
I have a similar bug in 4.1. When using CURRENT_TIMESTAMP in a create, the row is created fine, but the return value is an object: {val:"CURRENT_TIMESTAMP"} instead of the timestamp that was put into the row.

**Comment by yoolook** [comment]
Is it resolved yet, facing similer problem

**Comment by suanmei** [comment]
> I have a similar bug in 4.1. When using CURRENT_TIMESTAMP in a create, the row is created fine, but the return value is an object: {val:"CURRENT_TIMESTAMP"} instead of the timestamp that was put into the row.

Same problem

**Comment by papb** [comment]
I think you should simply let Sequelize do the default behavior here, which is already to set the current timestamp.

Therefore the solution should be to simply remove the `defaultValue` from `createdAt` and `updatedAt` fields.
