### ISSUE TITLE
How could I use the sequelize.fn with the MySQL function `FIND_IN_SET`

### ISSUE THREAD

**Issue by LuoLee** [sequelize/sequelize#7535]
I have a query and an update query using the MySQL Function `FIND_IN_SET`, but the manual does not file a usage aboud this.
The query like:
```
sequelize.query('SELECT * FROM house WHERE FIND_IN_SET(:uid, users)',
    {replacements: {uid: uid},
    type: sequelize.QueryTypes.SELECT}).then(function (houses) {
})
```

**Comment by knoxcard** [comment]
http://docs.sequelizejs.com/en/latest/docs/querying/

Search for "$in"

**Comment by LuoLee** [comment]
@knoxcard `$in` or `in` is an SQL exception, but `FIND_IN_SET` is a function only for MySQL.
This seems different ?

**Comment by LuoLee** [comment]
@knoxcard sorry for mistake, it stands for operator or expression.

**Comment by knoxcard** [comment]
Right, my apologies as well, it is different.  Looks like you have to run a raw SQL call.

**Comment by sushantdhiman** [comment]
Maybe something like ?

```js
Model.findAll({
  where: sequelize.where(sequelize.fn('FIND_IN_SET', uid,  'users'))
})
```

https://github.com/sequelize/sequelize/issues/7517#issuecomment-298051949

**Comment by LuoLee** [comment]
@sushantdhiman Thx for your reply, the below is I'm using in my project:
```
model.findAndCountAll({where: sequelize.where(sequelize.fn('FIND_IN_SET', uid, sequelize.col('users')), 'is', {$ne: null})})
```

**Comment by windsome** [comment]
@sushantdhiman @LuoLee  how to combine with other options in where? eg: I want query createdAt > 'now()' and sequelize.where(sequelize.fn('FIND_IN_SET', uid, sequelize.col('users')), '>', 0).

**Comment by sadikhasanpalsaniya** [comment]
@sushantdhiman @LuoLee how to add another where condition with find_in_set?
e.g. user_id>0 and sequelize.where(sequelize.fn('FIND_IN_SET', uid, sequelize.col('users')), '>', 0).

**Comment by sushantdhiman** [comment]
```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const User = sequelize.define('user', {
  name: Sequelize.STRING
});

sequelize.sync({}).then(() => {
  return User.build({ id: 1, name: 'abc' }).save().then(() => {
    return User.findAll({
      where: {
        name: { [Sequelize.Op.ne]: 'a' },
        [Sequelize.Op.and]: [
          sequelize.where(sequelize.fn('random'), Sequelize.Op.ne, 0)
        ]
      },
      logging: true
    });
  });
}).then(r => {
  console.log(JSON.stringify(r, null, 2));
});
```

```sql
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE (random() != 0) AND `user`.`name` != 'a';

[
  {
    "id": 1,
    "name": "abc",
    "createdAt": "2018-11-22T12:50:59.140Z",
    "updatedAt": "2018-11-22T12:50:59.140Z"
  }
]
```
