### ISSUE TITLE
ondelete paranoid style

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#7537]
Hello!

Is it possible to ask sequelize to write deleted_at on every child entity when parent entity soft deleted?

Thanks

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/2586

**Comment by alexey2baranov** [comment]
Hm. What about answer?

**Comment by sushantdhiman** [comment]
As mention in discussion over https://github.com/sequelize/sequelize/issues/2586 , Its not possible as `onDelete` constraints enforced by database which wont work for paranoid model, which doesnt get deleted actually

**Comment by alexey2baranov** [comment]
I see. I added my "like" to fesature request in #2586. hope it will be in future version.

Thanks

**Comment by shotokai** [comment]
the cascading paranoid is easily done using a `hook` on the model.  e.g.:
`'use strict';
module.exports = function (sequelize, DataTypes) {
  var Project = sequelize.define('Project', {
    name: DataTypes.STRING
  }, {
    paranoid: true,
    classMethods: {
      associate: function (models) {
        Project.hasMany(models.Task);
      }
    }
  });

  Project.addHook('afterDestroy',(project, options) => {
    return sequelize.models.Task.destroy({where: {ProjectId: project.id}})
  });

  return Project;
};
`
