### ISSUE TITLE
findAll include associated table, returns one, should return many.

### ISSUE THREAD

**Issue by subatomicglue** [sequelize/sequelize#7541]
Hello we are using `Sequelize` 3.30.0,  `NodeJS` 7.5.0, `mysql` Ver 14.14 Distrib 5.7.17, for osx10.11 (x86_64)

### The Query:
Making a `content.findAll` query `include:`ing all rows from another table `content_groupings` who's column `content_id` references the `content` `id`...   

### The Problem:
Instead of seeing multiple `content_groupings` rows returned for each `content` item, we only see 1   (even though MySQL table has multiple - see below).   But we set up the association with `hasMany`, which should allow many.

### Detailed Info / Reproduction steps:
These models are **auto generated** by `sequelize-auto` (*we have a legacy database in MySql*)
so we **never edit this code by hand**

```
sequelize.define('content', {
  id: { type: DataTypes.BIGINT, allowNull: false, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(255), allowNull: true }
});
sequelize.define('content_groups', {
  id: { type: DataTypes.BIGINT, allowNull: false, primaryKey: true, autoIncrement: true },
  name: { type: DataTypes.STRING(255), allowNull: true }
});
sequelize.define('content_groupings', {
  content_id: {
    type: DataTypes.BIGINT,
    allowNull: true,
    references: {
      model: 'content',
      key: 'id'
    }
  },
  group_id: {
    type: DataTypes.BIGINT,
    allowNull: true,
    references: {
      model: 'content_groups',
      key: 'id'
    }
  }
});
```

for some reason Sequelize insists on there being an 'id', even though our MySQL table (and auto-genned model) don't have an 'id' column.
removing `id` avoids certain errors...  and returns us back to reality.
```
content_groupings.removeAttribute('id');
```

We auto-generate this code at initialization of our nodejs server, based on the "references" found in the above models. (yes, we iterate through all models looking for 'references')
Note the `hasMany`, for the associated table include we do later in `findAll`.
We have also tried replacing `belongsTo` with `hasMany`, but same result.

```
// -> for content_id "references", found in "content_groupings" model:
//    Associate content_groupings <--> content         (for both nested and associated includes)
content_groupings.belongsTo( content, {as: content_id_obj, foreignKey: content_id});
content.hasMany( content_groupings, {as: 'associated__content_id__content_groupings_obj, foreignKey: content_id});

// -> for group_id "references", found in "content_groupings" model:
//    Associate content_groupings <--> content_groups  (for both nested and associated includes)
content_groupings.belongsTo( content_groups, {as: group_id_obj, foreignKey: group_id});
content_groups.hasMany( content_groupings, {as: 'associated__group_id__content_groupings_obj, foreignKey: group_id});
```

Find all content with "Healthcare" in the title
```
let items = await content.findAll({
  where: { name: { $like: '%Healthcare%' }},
  attributes: ['id','name'],
  include: [
    { model: content_groupings, as: 'associated__content_id__content_groupings_obj' }
  ]
});
return items;
```

In MySQL:
```
'content'
id    name
1     Healthcare blah blah blah
```
```
'content_groupings'
content_id  group_id
1           97
1           4
```
```
'content_groups'
id          name
4           Guts
97          Blood
```

Returned JSON, **only has 1 result** (97) in the array, but we **expected 2**   (97 and 4 as seen in `content_groupings` table)

```
[
  {
    "id": 1,
    "name": "Healthcare blah blah blah",
    "associated__content_id__content_groupings_obj": [
      {
        "content_id": 1,
        "group_id": 97
      }
    ]
  }
]
```

**Comment by subatomicglue** [comment]
Using the logging feature, I can see the SQL generated by sequelize

```
SELECT `content`.`id`, `content`.`name`, `associated__content_id__content_groupings_obj`.`content_id` AS `associated__content_id__content_groupings_obj.content_id`, `associated__content_id__content_groupings_obj`.`group_id` AS `associated__content_id__content_groupings_obj.group_id`, `associated__content_id__content_groupings_obj`.`last_accessed` AS `associated__content_id__content_groupings_obj.last_accessed`, `associated__content_id__content_groupings_obj`.`modified` AS `associated__content_id__content_groupings_obj.modified`, `associated__content_id__content_groupings_obj`.`created` AS `associated__content_id__content_groupings_obj.created` FROM `content` AS `content` LEFT OUTER JOIN `content_groupings` AS `associated__content_id__content_groupings_obj` ON `content`.`id` = `associated__content_id__content_groupings_obj`.`content_id` WHERE `content`.`name` LIKE '%Healthcare%';
```

which returns actually 2 items!!

```
id name   associated__content_id__content_groupings_obj.content_id  associated__content_id__content_groupings_obj.group_id
1  Healthcare blah blah blah   1   97
1  Healthcare blah blah blah   1   4
```

So why isn't the `findAll` returning both?

**Comment by Alexsey** [comment]
Looks like the same as [mine](https://github.com/sequelize/sequelize/issues/7344) and some others

**Comment by subatomicglue** [comment]
And before you say I need `belongsToMany`, notice above that I am not using `group_id`

Nowhere below is `group_id`... nor is it needed or relevant...
```
content.hasMany( content_groupings, {as: 'associated__content_id__content_groupings_obj, foreignKey: content_id});

await content.findAll({
  where: { name: { $like: '%Healthcare%' }},
  attributes: ['id','name'],
  include: [
    { model: content_groupings, as: 'associated__content_id__content_groupings_obj' }
  ]
});
```

I have also tried with `required:false`:
```
{ model: content_groupings, as: 'associated__content_id__content_groupings_obj',
  required: false }
```
per the advice here: http://docs.sequelizejs.com/en/latest/docs/models-usage/#nested-eager-loading, but it too only returns 1 result.

**Comment by subatomicglue** [comment]
I have also tried with `required:false` and `required:true`:
```
{ model: content_groupings, as: 'associated__content_id__content_groupings_obj',
  required: false }
```

With `required:false` generates `OUTER JOIN` returning 2 results in mysql, but only 1 from `findAll()`   
(NOTE: **NO CHANGE** from above, `requires:false` seems to be **the default**):

```
SELECT `content`.`id`, `content`.`name`, `associated__content_id__content_groupings_obj`.`content_id` AS `associated__content_id__content_groupings_obj.content_id`, `associated__content_id__content_groupings_obj`.`group_id` AS `associated__content_id__content_groupings_obj.group_id` FROM `content` AS `content` LEFT OUTER JOIN `content_groupings` AS `associated__content_id__content_groupings_obj` ON `content`.`id` = `associated__content_id__content_groupings_obj`.`content_id` WHERE `content`.`name` LIKE '%Healthcare%';

id name   associated__content_id__content_groupings_obj.content_id  associated__content_id__content_groupings_obj.group_id
1  "Healthcare blah blah blah"   1   97
1  "Healthcare blah blah blah"   1   4

content.findAll({
    logging: console.log,
    where: { name: { $like: '%Healthcare%' }},
    attributes: ['id','name'],
    include: [
      {
        attributes: ['content_id','group_id'],
        model: content_groupings, as: 'associated__content_id__content_groupings_obj',
        required: false
      }
    ]
  });

result:
{
    "id": 1,
    "name": "Healthcare blah blah blah",
    "associated__content_id__content_groupings_obj": [
      {
        "content_id": 1,
        "group_id": 97
      }
    ]
  }
```

And of course with `required:true`, generates `INNER JOIN`,  returning 2 results in mysql, but only 1 from `findAll()`:
```
SELECT `content`.`id`, `content`.`name`, `associated__content_id__content_groupings_obj`.`content_id` AS `associated__content_id__content_groupings_obj.content_id`, `associated__content_id__content_groupings_obj`.`group_id` AS `associated__content_id__content_groupings_obj.group_id` FROM `content` AS `content` INNER JOIN `content_groupings` AS `associated__content_id__content_groupings_obj` ON `content`.`id` = `associated__content_id__content_groupings_obj`.`content_id` WHERE `content`.`name` LIKE '%Healthcare%';

id name   associated__content_id__content_groupings_obj.content_id  associated__content_id__content_groupings_obj.group_id
1  "Healthcare blah blah blah"   1   97
1  "Healthcare blah blah blah"   1   4

content.findAll({
    logging: console.log,
    where: { name: { $like: '%Healthcare%' }},
    attributes: ['id','name'],
    include: [
      {
        attributes: ['content_id','group_id'],
        model: content_groupings, as: 'associated__content_id__content_groupings_obj',
        required: true
      }
    ]
  });

result:
{
    "id": 1,
    "name": "Healthcare blah blah blah",
    "associated__content_id__content_groupings_obj": [
      {
        "content_id": 1,
        "group_id": 97
      }
    ]
  }
```

**Comment by subatomicglue** [comment]
So... end of day friday I added the id column back to `content_groupings`, and all of a sudden the `findAll` `include` was returning multiple results instead of 1!!!

Looks like whatever collects the row results from SQL into a hierarchical JSON structure needs that primary `id` key there.   

So, In the case when no `id` column, this would be a **bug** in `sequelize`.  And would affect legacy databases, i.e. especially when using `sequelize-auto` to auto-gen the models on tables without `id` columns…   

Thanks!

**Comment by sushantdhiman** [comment]
@subatomicglue I am glad that you were able to resolve your issue, Sequelize depend upon primaryKey for many operations especially aggregating records after they have been retrieved from database. Without any pivot columns  (which is primaryKey) in most cases things break.

If a model is without any primaryKey then there are chances many things wont work as we depend upon id or primaryKey field so much.

I am closing this issue, but this doesnt mean we dont want to support legacy tables. We just dont have enough resources to focus on that yet :)

**Comment by evenfrost** [comment]
For anyone still having same issue with `id` provided: check if you have `DISTINCT ON` clause in your query. It causes DB query to return single rows in relations. In Sequelize query it looks like this:
```js
attributes: [
  literal('DISTINCT ON("description") 1'), // remove this line to get all rows in relations
  'id',
  // ...
]
```

**Comment by smithaitufe** [comment]
@evenfrost @sushantdhiman Please what is the way forward? I am currently stock in this issue as well.

[Look at this issue I created today](https://github.com/sequelize/sequelize/issues/8964)

**Comment by ahelord** [comment]
Solve the problem after placing aliases in the relations "hasMany - belongsTo", and in "findAll" since the names of the attributes of the primary keys were shortened by the name restrictions in Postgresql, which meant that it did not correctly "JOIN", once the names were shortened I got all the records in the array.

**Comment by Itsindigo** [comment]
Thanks @subatomicglue, your problem case was identical to mine, and you no doubt saved me countless hours.

**Comment by BartusZak** [comment]
@subatomicglue I'm facing similar issue, but I do have `id` column. 

SQL returned 2431 rows but sequelize merged them to 456 :(
When I use `{raw: true}` it returns all records correctly but `virtual` columns definitions is not working..

![image](https://user-images.githubusercontent.com/16143176/63640319-f93a7100-c69e-11e9-9706-16d44a0c0d46.png)

```node
    StShipmentHeader.addScope('test', {
      include: [
        {
          model: models.st_shipment_event,
       }
...
```

```node  
const StShipmentEvent = sequelize.define(
    'st_shipment_event',
    {
      id: {
        type: DataTypes.BIGINT,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
      },
...
StShipmentEvent.associate = models => {
    StShipmentEvent.belongsTo(models.st_shipment_header)
  }
```

```node
StShipmentHeader.hasMany(models.st_shipment_event, {
      onDelete: 'CASCADE',
      foreignKey: models.st_shipment_event.id
    })
```

**Comment by EdilsonAndrade** [comment]
> @subatomicglue I'm facing similar issue, but I do have `id` column.
> 
> SQL returned 2431 rows but sequelize merged them to 456 :(
> When I use `{raw: true}` it returns all records correctly but `virtual` columns definitions is not working..
> 
> ![image](https://user-images.githubusercontent.com/16143176/63640319-f93a7100-c69e-11e9-9706-16d44a0c0d46.png)
> 
> ```js
>     StShipmentHeader.addScope('test', {
>       include: [
>         {
>           model: models.st_shipment_event,
>        }
> ...
> ```
> 
> ```js
> const StShipmentEvent = sequelize.define(
>     'st_shipment_event',
>     {
>       id: {
>         type: DataTypes.BIGINT,
>         allowNull: false,
>         primaryKey: true,
>         autoIncrement: true
>       },
> ...
> StShipmentEvent.associate = models => {
>     StShipmentEvent.belongsTo(models.st_shipment_header)
>   }
> ```
> 
> ```js
> StShipmentHeader.hasMany(models.st_shipment_event, {
>       onDelete: 'CASCADE',
>       foreignKey: models.st_shipment_event.id
>     })
> ```

Did if fix it? I am stuck on this now :-(
