### ISSUE TITLE
`sync({force: true, logging: false})` still logs the `DROP TABLE IF EXISTS`

### ISSUE THREAD

**Issue by jon-adams** [sequelize/sequelize#7542]
Calling `sync` while forcing table recreation but turning off logging (when it is normally enabled in the global config) correctly disables logging of the `CREATE TABLE` statements, but the `DROP TABLE IF EXISTS` SQL that comes right before (due to the `force:true` option) is still logged via the global setting, ignoring the override in the `SyncOptions`:

```js
myModel.sync({ force: true, logging: false})
```

All SQL statements involved in the call to `sync` should be disabled if `{logging: false}` is supplied to the `sync` method call.

But the output (log) was: 

`DROP TABLE IF EXISTS 'my_models'` 

Note there was no `CREATE TABLE` log (correct) but it still logged the `DROP TABLE` SQL line (incorrect).

Dialect: sqlite (though I assume this is a problem for all dialects since it is an issue with Sequelize logging, not the SQL generation or response)
Database version: sqlite3
Sequelize version: 3.30.4

Obviously, this is a pretty low priority bug, since it is just a one extra log line (per `sync` call) in a specific scenario.

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/pull/6216

**Comment by sushantdhiman** [comment]
Available in v4
