### ISSUE TITLE
Adding joing to an aggregation function breaks logic?

### ISSUE THREAD

**Issue by georgeedwards** [sequelize/sequelize#7544]
## What you are doing?
Trying to sum and group a set of data with joins. 

```ts
db.History.findAll({
        where: {
            type: 'tal',
            createdAt: {
                $lt: start,
                $gt: end
            },
            '$Line.name$': line
        },
        attributes: ['tag', [sequelize.fn('sum', sequelize.col('value')), 'val']],
        group: ["tag"],
        include: [{
            model: db.Line
        }]
    })
```

## What do you expect to happen?
This to return data in the form:
`[{tag: "something", val: 50}, {tag: "something2", val: 70}]`

## What is actually happening?
Error - `Column 'Histories.id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.` 
For some reason the addition of the include property causes this issue, whereas if I remove `'$Line.name$': line` from the where clause and the include, then this works fine? 

__Dialect:__ mssql
__Sequelize version:__ 3.30.4

**Comment by sushantdhiman** [comment]
Ah, this is similar to https://github.com/sequelize/sequelize/issues/7534 , We add a extra id field which breaks grouping
