### ISSUE TITLE
Support parameterized query for mssql when using Bind Parameter 

### ISSUE THREAD

**Issue by kjatti** [sequelize/sequelize#7553]
The docs clearly say that only SQLite and PostgreSQL dialects support true binding of parameters of a query and for other dialects the parameters are just appended to the generated SQL. Since tedious supports parameterised statements, and using parameters when calling procedures, sequlize should be able to make use of this feature when executing raw queries. 

Note: This is intended to be a feature request.

**Comment by janmeier** [comment]
Covered by https://github.com/sequelize/sequelize/issues/3495
