### ISSUE TITLE
Do you really need ALL of Lodash?

### ISSUE THREAD

**Issue by tristanhoy** [sequelize/sequelize#7558]
Lodash is a monster of a package at 5MB, is there any chance you could just include the routines you require?

**Comment by felixfbecker** [comment]
We use quite a lot of lodash functions and installing one 5MB package (especially when cached) is faster than installing hundreds of single-file packages. Overall we are moving away from lodash and are replacing it more with native methods.

**Comment by tristanhoy** [comment]
Understood - most projects that depend on Lodash are only using one or two functions.

I'm currently deploying sequelize to an AWS Lambda function and I'm rolling up all the 3rd party modules first to speed up deployments - and now deployment times to AWS seem to be related to payload size. Minification complicates debugging, so now I'm looking to reduce dependencies.

I couldn't find one, but do you have an issue tracking the migration away from Lodash?

**Comment by felixfbecker** [comment]
No, it's just something we point out in reviews for new code.

**Comment by tristanhoy** [comment]
All good. I'll watch for your release.
