### ISSUE TITLE
issue with sequelize install 3.30.4

### ISSUE THREAD

**Issue by varunj90** [sequelize/sequelize#7559]
here is the issue when we are trying to do an npm install. 
We have been using node version 0.10.39 and npm 1.4.28

FYI this has always been working.

λ npm install sequelize
npm WARN engine cross-env@3.2.4: wanted: {"node":">=4.0"} (current: {"node":"0.10.39","npm":"1.4.28"})
npm WARN engine terraformer@1.0.8: wanted: {"node":">=4.2.6"} (current: {"node":"0.10.39","npm":"1.4.28"})
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Path /types/geojson not found in group repository &quot;npm-all&quot; [id=npm-all].</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm ERR!
npm ERR!     <link rel="icon" type="image/png" href="https://repo.dcts.tdbank.com:9443/favicon.png">
npm ERR!     
npm ERR!
npm ERR!     <link rel="stylesheet" href="https://repo.dcts.tdbank.com:9443/static/css/Sonatype-content.css?2.11.4-01" type="text/css" media="screen" title="no title" charset="utf-8">
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>404 - Path /types/geojson not found in group repository &quot;npm-all&quot; [id=npm-all].</h1>
npm ERR!     <p>Path /types/geojson not found in group repository &quot;npm-all&quot; [id=npm-all].</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (C:\Users\Redirection\jainv4\AppData\nvm\v0.10.39\node_modules\npm\node_modules\npm-registry-client\lib\request.js:274:23)
npm ERR!     at Request._callback (C:\Users\Redirection\jainv4\AppData\nvm\v0.10.39\node_modules\npm\node_modules\npm-registry-client\lib\request.js:246:65)
npm ERR!     at Request.self.callback (C:\Users\Redirection\jainv4\AppData\nvm\v0.10.39\node_modules\npm\node_modules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Users\Redirection\jainv4\AppData\nvm\v0.10.39\node_modules\npm\node_modules\request\request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Users\Redirection\jainv4\AppData\nvm\v0.10.39\node_modules\npm\node_modules\request\request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sequelize"
npm ERR! cwd C:\Users\jainv4\Marketplace\temp
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! type unexpected_token
npm ERR! not ok code 0

**Comment by janmeier** [comment]
https://github.com/Esri/Terraformer/issues/304

**Comment by varunj90** [comment]
Hi Please provide an update here.

This library isn't working.

Can you please help us figure this out.

**Comment by n30r3b3l** [comment]
updating to the latest version (4.5.0) of npm seems to resolve the issue. 
`npm install npm@latest -g`

**Comment by xb1itz** [comment]
+1 on this. Can't install sequelize and using custom registries is not an option for me :/
