### ISSUE TITLE
Wrong pluralization of model 'grammar'

### ISSUE THREAD

**Issue by TimAstier** [sequelize/sequelize#7562]
```js
// Model definition
const Grammar = sequelize.define('grammar', {...});
// Query
models.grammar.findOne(...);
```

This should generate SQL query on the table 'grammars'
Instead I get: SequelizeBaseError: relation "grammar" does not exist

This happens to be an issue from the inflection package:

```js
var inflection = require('inflection');
console.log(inflection.pluralize('grammar'));
// "grammar" instead of expected "grammars"
```

Currently having to use this workaround:

```js
const Grammar = sequelize.define('grammar', {
...
freezeTableName: true,
tableName: 'grammars'
});
```

__Sequelize version:__ 3.29.0

PS: This is the first time I submit an issue on an open source project, I'm not sure if it's relevant or if I would better submit it on the inflection repository. Thanks!

**Comment by sushantdhiman** [comment]
Track https://github.com/dreamerslab/node.inflection/issues/63

We need to update to patch version once original issue is fixed over `inflection`

**Comment by contra** [comment]
IMO you should use the `pluralize` module instead of inflection - simpler, more correct, and better maintained. I've opened another ticket w/ `inflection` that works fine with the `pluralize` module.

They basically do the same thing but some inflection drops the ball on many cases.

https://github.com/dreamerslab/node.inflection/issues/64

**Comment by contra** [comment]
Yes, keep it open.

**Comment by eseliger** [comment]
Made a PR to node.inflection, I will update this issue when it's merged.
https://github.com/dreamerslab/node.inflection/pull/67

**Comment by contra** [comment]
Keep it open.

**Comment by contra** [comment]
Keep it open.
