### ISSUE TITLE
Does model:create on the CLI accept "define" configuration options, specifically freezeTableName?

### ISSUE THREAD

**Issue by embolden** [sequelize/sequelize#7566]
## What you are doing?
I am trying to globally enable the `freezeTableName` option as described here: http://stackoverflow.com/a/34558832/957545

Using the following command:
`sequelize model:create --name user --attributes username:string`

With the following config.json:
```json
{
  "development": {
    "username": "root",
    "password": "root",
    "database": "databasename",
    "host": "127.0.0.1",
    "dialect": "mysql",
    "dialectOptions": {
      "socketPath": "/Applications/MAMP/tmp/mysql/mysql.sock"
    },
    "define": {
      "freezeTableName": true
    }
  }
}
```

## What do you expect to happen?
I expected the generated migration to use the singular table name.

## What is actually happening?
The migration file has the plural table name:
```js
'use strict';
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('users', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      username: {
        type: Sequelize.STRING
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: function(queryInterface, Sequelize) {
    return queryInterface.dropTable('users');
  }
};
```
The model does not have the `freezeTableName` option.
```js
'use strict';
module.exports = function(sequelize, DataTypes) {
  var user = sequelize.define('user', {
    username: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return user;
};
```

__Dialect:__ mysql
__Database version:__ 5.6.35
__Sequelize version:__ Sequelize [Node: 7.2.0, CLI: 2.7.0, ORM: 3.30.4]

**Comment by sushantdhiman** [comment]
I dont think CLI config support `define` option, beside you need to add if only once in your main `models/index.js` file (where you would create Sequelize instance). Then it will be automatically used by all models internally

**Comment by embolden** [comment]
I believe this is the generated file where my Sequelize instance is getting created.

```js
'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(module.filename);
var env       = process.env.NODE_ENV || 'development';
var config    = require(__dirname + '/../config/config.json')[env];
var db        = {};

if (config.use_env_variable) {
	var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
	var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
	.readdirSync(__dirname)
	.filter(function(file) {
		return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
	})
	.forEach(function(file) {
		var model = sequelize['import'](path.join(__dirname, file));
		db[model.name] = model;
	});

Object.keys(db).forEach(function(modelName) {
	if (db[modelName].associate) {
		db[modelName].associate(db);
	}
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

If I add a `console.log` for the config, I am seeing my config data.  Is my CLI config separate from this config?  Is there any other information I can provide that would be helpful to you?

**Comment by sushantdhiman** [comment]
This docs section will help you http://docs.sequelizejs.com/en/v3/docs/getting-started/#application-wide-model-options

In your `models/index.js` (which you have pasted above) you have to set define just like docs explains. CLI config will not set `define` option AFAIK.

**Comment by embolden** [comment]
Holy moly, can't believe I missed that.  I'm still a bit lost though.  The docs show passing in just the `connectionUri` and the object with the `define` option in it.  I have that `define` option in my config file which is getting passed into `var sequelize = new Sequelize(config.database, config.username, config.password, config);` but it doesn't seem to have any effect.  Is there something I'm missing between the 2 param and 4 param constructors?

I wonder if I'm framing this question incorrectly.. Should I not be using `sequelize db:migrate` if I want that config to be applied?

**Comment by sushantdhiman** [comment]
> Should I not be using sequelize db:migrate if I want that config to be applied?

With `freezeTableName` your table names will not be pluralized, if you are already using migrations this means you have been creating tables with migration as well, so there should be no need for special migration.

For example if you had a model name 'User', then its table would be `Users` without `freezeTableName`. For each model you will need to set correct table name from now on, with `freezeTableName` they wont be pluralized any more

**Comment by embolden** [comment]
I'm no longer working on the project that used Sequelize, so this is no longer an issue for me.  Thank you for you time and patience.

**Comment by ajbeach2** [comment]
If Iadd a console.log in my model/index.js nothing happens. Heck, i can delete that entire file, and i am still able to create models. It seems that the models/index.js is not used when use model:create

**Comment by brunofunnie** [comment]
After having the same issue I found this post. And still today on 2020 there are people having this "problem". The fact is, sequelize-cli doesn't look for the "define" option nor "freezeTableNames". In fact it was designed to generate the migrations with plural as standard. People are not supposed to change it because it will imply into problems with the models. So I think thats the way sequelize-cli wasn't developed with the "define" option available to freeze the table names.

So... not an issue, just UNpluralize manually the table names, or fork sequelize-cli project and create a patch for this.

> > Should I not be using sequelize db:migrate if I want that config to be applied?
> 
> With `freezeTableName` your table names will not be pluralized, if you are already using migrations this means you have been creating tables with migration as well, so there should be no need for special migration.
> 
> For example if you had a model name 'User', then its table would be `Users` without `freezeTableName`. For each model you will need to set correct table name from now on, with `freezeTableName` they wont be pluralized any more
