### ISSUE TITLE
Unhandled rejection SequelizeConnectionError: Quit inactivity timeout

### ISSUE THREAD

**Issue by J0NNYZER0** [sequelize/sequelize#7570]
_Thanks for wanting to report an issue you've found in Sequelize. Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_Note that it will be much easier for us to fix the issue if a test case that reproduces the problem is provided. Ideally this test case should not have any external dependencies. We understand that it is not always possible to reduce your code to a small test case, but we would appreciate to have as much data as possible. Thank you!_

_Github should only be used for feature requests and bugs - all questions belong on StackOverflow, Slack, or Google groups._

_This template is for submitting issues - if you want to submit a feature request you may skip this template_

## What you are doing?
I am bringing back an entity back with an n:m relationship. I have included a simple mysql schema which is the only external dependency. This database is a cleardb sitting in a heroku instance.

```sql
CREATE TABLE `menus` (
  `id` varchar(45) NOT NULL DEFAULT '',
  `name` varchar(145) DEFAULT NULL,
  `description` varchar(345) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `restaurants` (
  `id` varchar(45) DEFAULT NULL,
  `name` varchar(145) DEFAULT NULL,
  `description` varchar(345) DEFAULT NULL,
  UNIQUE KEY `restaurant_id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `restaurants_menus` (
  `restaurant_id` varchar(45) NOT NULL,
  `menu_id` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```server.js

'use strict'

const Hapi = require('hapi'),
  Boom = require('boom'),
  Inert = require('inert'),
  Path = require('path'),
  Url = require('url'),
  Server = new Hapi.Server(),
  Connection = Url.parse('mysql://username:password@hostname/heroku_database?reconnect=true'),
  MySql = require('mysql'),
  Sequelize = require('sequelize'),
  //Orm = new Sequelize(process.env.CONNECTION_STRING1),
  Orm = new Sequelize(
    Connection.pathname.substring(1),
    Connection.auth.split(':')[0],
    Connection.auth.split(':')[1],
    {
      host: Connection.hostname,
      dialect: 'mysql',
      pool: {
        max: 5,
        min: 0,
        idle: 10000
      }
    }
  ),
  Utils = {
    create_date: () => {
  		let today = new Date(),
  		year = today.getFullYear(),
  		month = today.getMonth(),
  		day = today.getDate(),
  		hour = today.getHours(),
  		minute = today.getMinutes(),
  		second = today.getSeconds()
  		return new Date(Date.UTC(year, month, day, hour, minute, second))
  	}
  },
  Models = {
    Menu: Orm.define('menus', {
      id: {
        type: Sequelize.STRING,
        field: 'id',
        primaryKey: true
      },
      name: {
        type: Sequelize.STRING,
        field: 'name'
      },
      description: {
        type: Sequelize.STRING,
        field: 'description'
      }
    },
    {
      timestamps: false,
      underscored: true
    }),
    Restaurant: Orm.define('restaurants', {
      id: {
        type: Sequelize.STRING,
        field: 'id',
        primaryKey: true
      },
      name: {
        type: Sequelize.STRING,
        field: 'name'
      },
      description: {
        type: Sequelize.STRING,
        field: 'description'
      }
    },
    {
      timestamps: false,
      underscored: true
    }),
    RestaurantMenu: Orm.define('restaurants_menus', {
      restaurant_id: {
        type: Sequelize.STRING,
        field: 'restaurant_id'
      },
      menu_id: {
        type: Sequelize.STRING,
        field: 'menu_id'
      }
    },
    {
      timestamps: false
    })
  }

Models.Menu.belongsToMany(Models.Restaurant, { through: Models.RestaurantMenu, foreignKey: 'menu_id' })
Models.Restaurant.belongsToMany(Models.Menu, { through: Models.RestaurantMenu, foreignKey: 'restaurant_id' })

Server.connection({
    host: '0.0.0.0',
    port: process.env.PORT || 9000,
    state: { ignoreErrors: true },
    routes: {
        files: { relativeTo: Path.join(__dirname, '../../dist') },
        cors: true
    }
})

Server.register(Inert, (err) => {
    if (err) throw err
})

Server.route([
  {
    method: 'GET',
    path: '/{files*}',
    handler: {
      directory: {
        path: '.',
        redirectToSlash: true,
        index: true
      }
    }
  },
  {
    method: 'GET',
    path: '/restaurant/detail/{id}',
    handler: (request, reply) => {
      Models.Restaurant.findOne({
        include: [{
          model: Models.Menu
        }],
        where: { id: request.params.id }
      }).then((restaurant) => {
        restaurant.getMenus().then(menu => reply({
          status: 'success',
          data: {
            restaurant: {
              name: restaurant.get('name'),
              menus: menu
          }
        }
      }))
      })
    }
  }
])

Server.start((err) => {
    if (err) throw err
    console.log('Server running at:', Server.info.uri)
})


```

```package.json

  "dependencies": {
    "boom": "^4.3.1",
    "hapi": "^16.1.1",
    "inert": "^4.2.0",
    "mysql": "^2.13.0",
    "sequelize": "^3.30.4"
  }

```

## What do you expect to happen?
No error on the server. Graceful disconnection after response is sent to client and all code has been executed.

## What is actually happening?
Unhandled rejection SequelizeConnectionError: Quit inactivity timeout
    at Quit.<anonymous> (/Users/jon/github/J0/orm/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:30)
    at bound (domain.js:280:14)
    at Quit.runBound [as _callback] (domain.js:293:12)
    at Quit.Sequence.end (/Users/jon/github/J0/orm/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /Users/jon/github/J0/orm/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /Users/jon/github/J0/orm/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at doNTCallback0 (node.js:428:9)
    at process._tickDomainCallback (node.js:398:13)

Unhandled rejection SequelizeConnectionError: Quit inactivity timeout
    at Quit.<anonymous> (/Users/jon/github/J0/orm/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:30)
    at bound (domain.js:280:14)
    at Quit.runBound [as _callback] (domain.js:293:12)
    at Quit.Sequence.end (/Users/jon/github/J0/orm/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /Users/jon/github/J0/orm/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /Users/jon/github/J0/orm/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at doNTCallback0 (node.js:428:9)
    at process._tickDomainCallback (node.js:398:13)

_Output, either JSON or SQL_
{
status: "success",
data: {
restaurant: {
name: "zzz",
menus: [
{
id: "0fe9a74b-bffd-3ab5-117e-67aeb7d9ce9c",
name: "a",
description: "aa",
restaurants_menus: {
restaurant_id: "a64d0e1c-0f7c-5f44-9a2a-a88b4480aee8",
menu_id: "0fe9a74b-bffd-3ab5-117e-67aeb7d9ce9c"
}
},
{
id: "18c5aad4-b6b3-5190-7339-f36079b53c11",
name: "ee",
description: "eee",
restaurants_menus: {
restaurant_id: "a64d0e1c-0f7c-5f44-9a2a-a88b4480aee8",
menu_id: "18c5aad4-b6b3-5190-7339-f36079b53c11"
}
}
]
}
}
}

__Dialect:__ mysql
__Database version: 5.5.46
__Sequelize version:3.30.4

**Comment by SPAHI4** [comment]
Same for me 
heroku cleardb
