### ISSUE TITLE
Issues with Bluebird, native Promise, and Sequelize typings

### ISSUE THREAD

**Issue by Kitanotori** [sequelize/sequelize#7573]
## What you are doing?
Writing a database transaction script in TypeScript using Node.js v7.9 Promise implementation, Sequelize typings, and async/await.

## What is actually happening?
The code does not compile:
`Argument of type '(transaction: any) => Promise<any[]>' is not assignable to parameter of type '(t: Transaction) => Bluebird<any>'`

I am able to compile the code by uninstalling Sequelize typings, but that is not really a solution.

__Sequelize version:__ 3.30.4
__Sequelize typings version:__ 4.0.51

## Related to
https://github.com/sequelize/sequelize/issues/6834
http://stackoverflow.com/questions/42689713/es6-promise-typescript-and-the-bluebird-promise

**Comment by janmeier** [comment]
We don't have any official typings - Please bug the author of the sequelize typings instead :)
