### ISSUE TITLE
Join on two tables where relationship is not recognised

### ISSUE THREAD

**Issue by PCFNode** [sequelize/sequelize#7582]
## What you are doing?
I have 3 tables (models). A 'Location' and then two Location types 'LocationStorage' and 'LocationVehicle'. I then have 'Items' which have a single 'Location'

My Location table has many items, but no stated relationship with LocationStorage or LocationVehicle
```js
Location.hasMany(models.Item}); 
```

Now my LocationStorage has this
```js
LocationStorage.belongsTo(models.Location, {
  foreignKey: 'LocationId'
})
```

If I knew a collection of items were in a location of type 'LocationStorage' then I could do this in SQL

```sql
SELECT * FROM Items
INNER JOIN Locations ON Locations.id = Items.LocationId
INNER JOIN LocationStorages ON LocationStorages.LocationId = Locations.id
```

## What do you expect to happen?
I would have expected by doing the following, I could get the same result

```js
 models.Item.findAll({
      include: [{ model: models.Location, include: [{ model: models.LocationStorage, required: false }] }],
    })
```

## What is actually happening?
I am getting a complaint 

```js
"LocationStorage is not associated to Item!"
```

## What I would like

I would like a way to get the LocationStorage details for an item when querying the item table

**Comment by harshithkashyap** [comment]
@PCFNode  The error is self explanatory. If you observe your models,  there is no association between Item and LocationStorage. Add the following to fix it. 
```
Item.hasMany(models.LocationStorage)
```
