### ISSUE TITLE
documentation search broken

### ISSUE THREAD

**Issue by samdenicola** [sequelize/sequelize#7583]
Searching the docs is broken

<img width="1284" alt="screen shot 2017-04-30 at 8 51 22 pm" src="https://cloud.githubusercontent.com/assets/13247167/25571654/d17a834c-2de6-11e7-8d52-3c5032571d93.png">

__Sequelize version:__ V4

**Comment by sushantdhiman** [comment]
Docs upgraded to ESDocs which now use Google Custom search

**Comment by samdenicola** [comment]
@sushantdhiman cool thanks!
