### ISSUE TITLE
Missing docs on http://docs.sequelizejs.com/en/v3/docs/schema/

### ISSUE THREAD

**Issue by FabioDMastrorilli** [sequelize/sequelize#7590]
## What you are doing?
I've opened this page: http://docs.sequelizejs.com/en/v3/docs/schema/

## What do you expect to happen?
I would expect that the page will contain more helpfully information

## What is actually happening?
Links don't work

Thank you,
Fabio :)

**Comment by janmeier** [comment]
This is described in http://docs.sequelizejs.com/en/v3/docs/migrations/ (and the schema page has been removed in v4)
