### ISSUE TITLE
Publish V4 in npm, please

### ISSUE THREAD

**Issue by selvavalluvan** [sequelize/sequelize#7595]
Please publish the v4 in npm. There are some necessary fixes and cool new features in v4 and the version at npm repository is currently at 3.30.4. Please publish the latest stable v4. @janmeier

**Comment by sushantdhiman** [comment]
v4 has been released in alpha channel which can be installed using `npm install sequelize@latest` (till v4.0.0-2 https://github.com/sequelize/sequelize/blob/master/changelog.md#400-2)

Stable release for v4 is coming soon

**Comment by snewell92** [comment]
@sushantdhiman 
```
$ npm dist-tag ls sequelize                           
  latest: 3.30.4                                        
  unstable: 4.0.0-2                                     
```

You meant `npm i --save sequelize@unstable`, right? ;)

**Comment by sushantdhiman** [comment]
@snewell92 Right :)

**Comment by keyiis** [comment]
@sushantdhiman Still use `npm i --save sequelize@unstable` today?

**Comment by eseliger** [comment]
nope v4 has a stable release now

**Comment by keyiis** [comment]
@eseliger I used `npm i --save sequelize` to install,but still 3.30.X, should i use `npm i --save sequelize@stable` or `npm i --save sequelize@lastest` ?

**Comment by eseliger** [comment]
`npm i --save sequelize@latest`
