### ISSUE TITLE
webpack can't compile the code by sequelize.import(path_model)

### ISSUE THREAD

**Issue by threem0126** [sequelize/sequelize#7600]
Hello!

we use "sequelize.import(path_model)" to  import model dynamic. But the webpack do not compile these model files on building.

How to resovle it ?

Thanks

**Comment by felixfbecker** [comment]
Of course not, webpack can only follow `require` statements. I would not use webpack

**Comment by lerit** [comment]
webpack support bundle node program,and analyse module by import or require.i also want sequelize model can be bundle,but now,it not support,expect a solution,thanks!

**Comment by bradennapier** [comment]
lol @ devs fail

**Comment by raphaelsoul** [comment]
similar here.
try using callback function for `sequelize.import` still fails.

```ts
import {default as UserDefine } from "../models/User.pg"
export const User = sequelize.import<UserInstance, IUserAttributes>('', db => UserDefine(db))
```

```ts
// models/User.pg.ts
export default function (db: sequelize.Sequelize) {
    return db.define<UserInstance, IUserAttributes>("User", COLUMNS, OPTIONS)
}
```

**Comment by jnreynoso** [comment]
I use serverless-webpack, and I have the same problem ...

**Comment by yongruning** [comment]
Models cannot be packaged successfully using an absolute path
