### ISSUE TITLE
Sequelize.NOW doesn't work

### ISSUE THREAD

**Issue by ohpyupi** [sequelize/sequelize#7603]
## Setting default time value for "createdAt" attribute
Thanks for the great module! I just started learning and using sequelize for my node.js and mysql project.
I wanted to set default current time value for "createdAt" and "updatedAt" using Sequelize.NOW as written in the document, but it fails to give default time to the attributes. I searched google and stackoverflow to figure out solution. However, it doesn't seem there are clear solution for this matter and now I am positing this issue here!

```js
...
 createdAt: {type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW},
...
```

__Dialect:__ mysql

**Comment by Drakehawk** [comment]
It should be like this:

``
createdAt: {type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.fn('NOW')}
``

But I'm also having an issue with NOW:

``
...
Users.update(
			{..., UsEstado: "A", UsIntentosFallidos: 0, UsChangeDate: sequelize.fn('NOW')}
...
``

When it creates the query it returns this (from the log):

``
SET ... `UsChangeDate`=[object Object] WHERE ...
``

And so I get a mysql error.

**Comment by balexandre** [comment]
@ohpyupi 

the `defaultValue` should be `Sequelize.NOW` like

    dt: { type: Sequelize.DATE, defaultValue: Sequelize.NOW }

as stated in the documentation, `NOW` is a function and used in setting default values.

as you can see from the image below, works:

[![](http://s6.postimg.org/hjcbh59up/screenshot_368.png)](http://s6.postimg.org/hjcbh59up/screenshot_368.png)

@Drakehawk 

just run a simple test with `Create` and `Update` and works flawless

[![](http://s6.postimg.org/r55vxg10h/screenshot_369.png)](http://s6.postimg.org/r55vxg10h/screenshot_369.png)

this are the querys I got:

    Executing (default): INSERT INTO `Projects` (`slug`,`project_name`,`UsChangeDate`,`createdAt`,`updatedAt`) VALUES ('p-123','P 123',NOW(),'2017-05-11 03:32:46','2017-05-11 03:32:46');
    Executing (default): UPDATE `Projects` SET `UsChangeDate`=NOW(),`updatedAt`='2017-05-11 03:32:51' WHERE `slug` = 'p-123'

**Comment by damianb** [comment]
Is there a reason you're trying to set the column for updatedAt/createdAt by explicitly defining it in the model? Why not use the second parameter for model definition and simply change the name of the column there?  e.g.

```
var Foo = sequelize.define('foo',  { /* bla */ }, {
  timestamps: true,
  updatedAt: 'UsChangeDate'
```

http://docs.sequelizejs.com/en/v3/docs/models-definition/#configuration

**Comment by Drakehawk** [comment]
I just try it again on my test machine. Everything works fine and I got:

``UPDATE `usuarios` SET `... `UsFechaHoraCambioPW`=NOW() WHERE ...
``

But still on my test server I get:

``UPDATE `usuarios` SET ... UsFechaHoraCambioPW`=[object Object] WHERE ... ``

Using the same code, sequelize version, etc. No idea why. Anyone knows what could cause this?

```js
query = this.app.orm.Usuarios.update(
			{UsFechaHoraCambioPW: sequelize.fn("NOW")},
			{where: {UsId: payload.id}},
		);
```

**Comment by balexandre** [comment]
@damianb is just an example simple app to help the [Gitter channel](https://gitter.im/sequelize/sequelize) better :)

**Comment by sushantdhiman** [comment]
You dont have to set default value for createdAt / updatedAt to work.

```js
const Model = sequelize.define('Model', {
    createdAt: {
        type: Sequelize.DATE,
        allowNull: false
    },
    updatedAt: Sequelize.DATE
}, {
  timestamps: true
});
```

**Comment by alexvicegrab** [comment]
Sequelize.fn("NOW") is a poor solution as it's database specific. This issue should be re-opened and fixed properly. It is true that createdAt and updatedAt will work fine without being required, but it's still an issue that needs fixing.

**Comment by AZS-99** [comment]
I need to insert values through PgAdmin, so I must set a default value or I'll have to type a complete timestamp in the raw query. Any recent solution has come up?
