### ISSUE TITLE
Can't update the column with "sequelize.col('value')+25" expression, forced to use "literal"

### ISSUE THREAD

**Issue by LuckStock** [sequelize/sequelize#7609]
Hello,

Updating to the latest doesn't solve the following issue for me.

If I try to update the integer/float column with a simple statement:
`models.User.update({value:sequelize.col('value')+25},{where:{id:123}})`
Sequelize results in:
`UPDATE `User` SET `value`='NaN' WHERE `id` = 123`

So, I'm forced to use literal to get the result that is not safe:
`models.User.update({value:sequelize.literal('value'+25)},{where:{id:123}})`

Is it going to be fixed as this issue exists for 6+ months, or I'm missing something?

**Comment by guihuxiansheng** [comment]
`models.User.update({value:sequelize.literal().value+1},{where:{id:123}})`

**Comment by guihuxiansheng** [comment]
I `models.User.update({value:sequelize.literal('\`value\`+25')},{where:{id:123}})`

**Comment by guihuxiansheng** [comment]
models.User.update({value:sequelize.literal('`value`+25')},{where:{id:123}})

**Comment by guihuxiansheng** [comment]
`models.User.update({value:sequelize.literal('"value"+25')},{where:{id:123}})`

**Comment by LuckStock** [comment]
If you read the above,I know how to do that with literal, but it should work with .col('value'). So, it's either a bug, or the wrong syntax. Any hints on that?

**Comment by balexandre** [comment]
@LuckStock I think what you're looking for is 

http://sequelize.readthedocs.io/en/latest/api/instance/#incrementfields-options-promisethis

in my example:

    Project.create({
        slug: "p-123",
        project_name: "P 123",
        UsChangeDate: sequelize.fn("NOW")
    });

    setTimeout(() => {           
        // so we have the insert query above added to db
        Project.find({
            where: {
                slug: "p-123"
            }
        }).then((model)=>{
            return model.increment({"Nb": 5});
        });
    }, 1000);

from the model:

    var Project = sequelize.define("Project", {
        slug: { type: Sequelize.UUID, defaultValue: Sequelize.UUIDV4, primaryKey: true },
        project_name: { type: Sequelize.STRING },
        UsChangeDate: { type: Sequelize.DATE, defaultValue: Sequelize.NOW },
        Nb: { type: Sequelize.INTEGER, defaultValue: 0 }
    });

**Comment by LuckStock** [comment]
In your example, there is a need to run 2 queries - SELECT and then UPDATE.
Is there a way to UPDATE it in one query without using literal and SELECT, then UPDATE?
A simple query like:
`UPDATE User SET value=value+25 WHERE id=123`

**Comment by balexandre** [comment]
the problem is that `incremental` is an instance and not the modal, so you kind'a need to get the instance first, and I thought the only way was to `findOne()`  / `findOne()` ... 

a sequelize developer would need to answer better what would be the best way to get an **instance**.

**Comment by Jairos2015** [comment]
I have the same problem.
models.User.update({value:sequelize.col('value')+newValue},{where:{id:123}})
Sequelize results in:
UPDATEUserSETvalue='NaN' WHEREid= 123
Is there any way to update the value of a field through arithmetic operations?

**Comment by sushantdhiman** [comment]
`Model.increment / decrement` methods are now supported http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-increment

```js
const Model = sequelize.define('Model', {
  hats: Sequelize.INTEGER,
  color: Sequelize.ENUM('red', 'green', 'blue')
});

Model.sync({ force: true })
  .then(() => Model.bulkCreate([
    { hats: 3, color: 'red' },
    { hats: 4, color: 'green' },
    { hats: 2, color: 'blue' },
    { hats: 3, color: 'red' },
    { hats: 4, color: 'green' },
    { hats: 1, color: 'blue' },
    { hats: 3, color: 'red' },
    { hats: 4, color: 'green' },
    { hats: 3, color: 'blue' }
  ]))
  .then(() => {
    return Model.increment('hats', {
      by: 25,
      where: {
        id: 1
      },
      logging: console.log
    });
  });
```

```sql
Executing (default): UPDATE `Models` SET `hats`=`hats`+ 25,`updatedAt`='2018-04-07 03:54:44.970 +00:00' WHERE `id` = 1
```
