### ISSUE TITLE
model.validate() always return not null object

### ISSUE THREAD

**Issue by fptmobility** [sequelize/sequelize#7614]
## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_

```js
// Here is my model and validate
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('user', {
        username: {
            type: DataTypes.STRING(255),
            allowNull: false,
            field: 'username',
            validate: {
                isEmail: true
            }
        }
    }, {
        timestamps: false,
        tableName: 'user'
    });
};
//Here is my route
router.get('/', function (req, res, next) {
     var user = models.user.build({username:'hihie'});
     var abc = user.validate();
     if(abc){
         console.log(abc);
         res.send("fail"); 
     }else{
        res.send("ok");  
     }

});
```

## What do you expect to happen?
         console.log('ok');
        res.send("ok");  

## What is actually happening?
It always return this object whether username is true or wrong
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }

__Dialect:__ mysql
__Database version:__ 10.1.21
__Sequelize version:
    "sequelize": "^3.30.4",
    "sequelize-cli": "^2.7.0",

**Comment by sushantdhiman** [comment]
`Instance.validate` returns a Promise, which you need to `.then / .catch` ([Docs](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-validate))
