### ISSUE TITLE
How do you manage the documentation?

### ISSUE THREAD

**Issue by itaied246** [sequelize/sequelize#7618]
I have a question regarding the documentation of `sequelize`.
I am trying to use `mkdocs` in my project as well, but I find it uncomfortable to write it in raw `md`.
Do you use any rich text editor?
Is there any documentation about the process of writing the docs?

**Comment by balexandre** [comment]
I really love the simplicity of markdown and I actually write documentation in raw markdown, you just get used to and stop using the mouse that often to write...

but if you can't do it, it's ok, just use any GUI for your OS, there are plenty out there... or even try in a browser with, for example, https://stackedit.io/editor

**Comment by itaied246** [comment]
Markdown is easy and comfortable, but I find it more suitable for developers.
It can be a bit difficult for people without this background to jump in.
We want to document our system, where designers and not technical staff could write as well.

We have used another system that works like `MS word` in the web, but the generated site wasn't that great so we look for alternatives.

**Comment by sushantdhiman** [comment]
Atom has inbuilt markdown support (`Ctrl + Shift + M`) to live preview markdown output. I often use this feature when working with docs.

Now we have migrated from ReadTheDocs to ESDocs but our custom docs are still written using markdown. I dont think there is much "process" with writing markdown, its the simplest format. You just write a documentation section and preview it, then push it
