### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by thebillkidy** [sequelize/sequelize#7622]
When running a `update` statement on one of my models, I get the following stacktrace:

```
TypeError: Cannot read property 'indexOf' of undefined
    at Instance.set (/Users/<redacted>/Projects/<redacted>/site/backend/node_modules/sequelize/lib/instance.js:328:20)
    at Instance.update (/Users/<redacted>/Projects/<redacted>/site/backend/node_modules/sequelize/lib/instance.js:835:8)
```
Probably since that line says key.indexOf, even though key should be a string?

Sequelize Version: Latest

**Comment by balexandre** [comment]
please provide the model and query to be able to help...

**Comment by thebillkidy** [comment]
Hey, Thanks! So I found the problem after digging deeper. It seems that
when you pass a undefined value to the update method that it results into
the indexOf crash. I guess this is because no check is being done?
