### ISSUE TITLE
What's best way I can make 'select' query with such like 'limit {start} {count}' within SQL?

### ISSUE THREAD

**Issue by AkashiX** [sequelize/sequelize#7623]
As title.

## What you are doing?
What I'm gonna do as follow.

```js
const sql = `SELECT * FROM myTable limit 10, 20`
```

## What do you expect to happen?
20 records returned and start with 10

## What is actually happening?

__Dialect:__ mysql
__Database version:__ newest
__Sequelize version:__ newest

**Comment by balexandre** [comment]
BTW **suck** !== **such** :)

[from the docs](http://docs.sequelizejs.com/en/latest/docs/querying/#pagination-limiting), you can pass limit and offset like:

    db.emails.findAndCountAll({
        where: {
            campaign_id: campaignId
        },
        offset: page * rows,
        limit: parseInt(rows),
        order: "`created_at` desc"
    }).then(function (data) {
        ...
    });

**Comment by AkashiX** [comment]
@balexandre Thanx, it works well for me.
