### ISSUE TITLE
Invalid singularized foreign keys in belongsToMany

### ISSUE THREAD

**Issue by KevinMann13** [sequelize/sequelize#7629]
## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_

```js
var MatchCriteria = sequelize.define('MatchCriteria', {
    shipto_address: DataTypes.STRING
//Some other fields
  }, {
    tableName: "match_criteria",
    underscored: true
  });

var Transaction = sequelize.define('Transaction', {
    shipto_address: DataTypes.STRING,
    //Some other fields
  }, {
    tableName: 'transactions',
    underscored: true,
    classMethods: {
      associate: function(models) {
        Transaction.belongsToMany(models.MatchCriteria, {
          through: models.PotentialMatch
        });
      }
    }
  });

var PotentialMatch = sequelize.define('PotentialMatch', {
    score: DataTypes.INTEGER,
    rank: DataTypes.INTEGER
  }, {
    tableName: "potential_matches",
    underscored: true,
    classMethods: {
      associate: function(models) {}
    }
  });


Transaction
   .findAll({
      include: [ models.MatchCriteria]
   })
   .then(results => {
console.log(success)
})
.catch(error => {
console.log(error);
});
```

## What do you expect to happen?
I expect to get match criteria back

## What is actually happening?
"ER_BAD_FIELD_ERROR: Unknown column 'MatchCriteria.PotentialMatch.match_criterium_id' in 'field list'"

It is converting criteria to criterium for some reason. The forgein key in the potential_matches table is match_criteria_id.

__Dialect: mysql
__Database version:__ XXX
__Sequelize version: 3.30.4

**Comment by sushantdhiman** [comment]
> // disable the modification of table names; By default, sequelize will automatically
   // transform all passed model names (first parameter of define) into plural.
  // if you don't want that, set the following

  ```freezeTableName: true```

https://sequelize.readthedocs.io/en/v3/docs/models-definition/#definition
