### ISSUE TITLE
sequelize can't hash password

### ISSUE THREAD

**Issue by FilipeCosta** [sequelize/sequelize#7632]
I am having a issue trying to hash password using bcrypt-nodejs with sequelize, when i route to my register i don't get any response and no register is added to my database :/.

So my model is this:
```

    "use strict";
var sequelize = require('./index');
var bcrypt = require('bcrypt-nodejs');

module.exports = function (sequelize, DataTypes) {
  var User = sequelize.define("User", {
    username: DataTypes.STRING,
    email: DataTypes.STRING,
    password: DataTypes.STRING
  }, {
      instanceMethods: {
        generateHash: function (password) {
          return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
        },
        validPassword: function (password) {
          return bcrypt.compareSync(password, this.password);
        }
      },


    });

  return User;
}
```
on my register route i try to hash the password and assing it to my password field like this:

```
var express = require('express');
var User = require('../../models').User;
var router = express.Router();

/* GET users listing. */
router.post('/', function (req, res, next) {
 console.log("hi");
  if (JSON.stringify(req.body) == "{}") {
    return res.status(400).json({ Error: "Register request body is empty" });
  }
  if (!req.body.email || !req.body.username || !req.body.password) {
    return res.status(400).json({ Error: "Missing fields for registration" });
  }
console.log(req.body.password);
  var password = User.generateHash(req.body.password);
  console.log(password);

  User.create({
    username: req.body.username,
    email: req.body.email,
    password: password
  }).then(function () {
    return res.status(200).json({message: "user created"});
  })

});

module.exports = router;
```
as i said i don't get any response from postman to the register route and nothing get added in the database, the problem just occurs when i add password, without the password field, the register get added :/.

thank you :)

**Comment by sushantdhiman** [comment]
You have added `generateHash` to `instanceMethods` but calling it on Model (`User`), this throws an Error which you haven't handled.

You need to do two things
- Set `generateHash` as a `classMethods` in `User` model
- Add some proper error handling in express

**Comment by pkassar** [comment]
Hi @FilipeCosta did you manage to solve your problem? I'm struggling with something very similar.

All the best,
PK

**Comment by FilipeCosta** [comment]
Hello pkassar, yes i solved basicly the problem was related to the instanceMethod, i can't use that to hash and salt the password, try to use the classMethod as suggested above,

If you have any problem with the classMethod say something maybe the problem is different and i can help you.

Best regards

**Comment by pkassar** [comment]
Thanks for your help @FilipeCosta, the problem was with the instance method like you suggested.

Best,
Paul

**Comment by FilipeCosta** [comment]
Glad i could help, any more problem you can ask :)

Happy coding,
Filipe Costa

**Comment by rajajlidi** [comment]
helli @FilipeCosta  @pkassar  please can you post you route and model files i have the same problem without solving

**Comment by FilipeCosta** [comment]
Here you have a simple example with authentication 
`module.exports = function (sequelize, DataTypes) {
  var User = sequelize.define("User", {
    username: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isUnique: function (value, next) {
          var self = this;
          User.find({ where: { username: value } })
            .then(function (user) {
              // reject if a different user wants to use the same username
              if (user && self.id !== user.id) {
                return next('username already in use!');
              }
              return next();
            })
            .catch(function (err) {
              return next(err);
            });
        }
      }
    },

    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isUnique: function (value, next) {
          var self = this;
          User.find({ where: { email: value } })
            .then(function (user) {
              // reject if a different user wants to use the same email
              if (user && self.id !== user.id) {
                return next('Email already in use!');
              }
              return next();
            })
            .catch(function (err) {
              return next(err);
            });
        }
      }
    },

    typeOfUser: {
      type: DataTypes.INTEGER,
      allowNull:true,
      defaultValue:null
    },

    country: {
      type: DataTypes.STRING,
      allowNull:true,
      defaultValue:null
    },

    birthDate:{
      type: DataTypes.DATEONLY,
      allowNull:true,
      defaultValue:null
    },

    reports: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },

    points: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },

    password: {
      type: DataTypes.STRING,
      allowNull:false
    },
    
    numberFotos: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    }
  }, {
      classMethods: {
        generateHash: function (password) {
          return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
        },
        associate: function(models){
          User.hasMany(models.Foto,{foreignKey: "userId"});
        }

      },
      instanceMethods: {
        validPassword: function (password) {
          return bcrypt.compareSync(password, this.password);
        }
      }

    });

  return User;
}`


now if you think, you need to compare the password from a existing user(no hashed) with the database(hashed), you need to call user.validPassword, the user is the instance

**Comment by rajajlidi** [comment]
what about the route file my probleme is there ?

**Comment by rajajlidi** [comment]
my problem that when i put the generateHash() in classMethods in the modelthe file route don't find the function add or create even when i put it in instanceMethods nothing done the password not be crypted can you hel me? @FilipeCosta

**Comment by FilipeCosta** [comment]
**Here my route**

module.exports = {
    login: function (req, res, next) {
 
        if (JSON.stringify(req.body) == "{}") {
            return res.status(400).json({ Error: "Login request body is empty" });
        }
        if (!req.body.username || !req.body.password) {
            return res.status(400).json({ Error: "Missing fields for login" });
        }
         console.log(req.body.username);
        // search a user to login
        User.findOne({ where: { username: req.body.username } }) // searching a user with the same username and password sended in req.body
            .then(function (user) {
                if (user && user.validPassword(req.body.password)) {
                    //return res.status(200).json({ message: "loged in!" }); // username and password match
                        

                    var payload = { user: user.id };

                    // create a token
                    var token = jwt.sign(payload, jwtConfig.secret, {
                        expiresIn: jwtConfig.expirationTime
                    });


                    // return the information including token as JSON
                    res.json({
                        success: true,
                        message: 'Enjoy your token!',
                        token: token
                    });

                }
                else {
                    return res.status(401).json({ message: "Unauthorized, invalid fields" }); // if there is no user with specific fields send
                }
            }).catch(function (err) {
                console.error(err.stack)
                return res.status(500).json({ message: "server issues when trying to login!" }); // server problems
            });
    },

    register: function (req, res, next) {

        if (JSON.stringify(req.body) == "{}") {
            return res.status(400).json({ Error: "Register request body is empty" });
        }
        if (!req.body.email || !req.body.username || !req.body.password) {
            return res.status(400).json({ Error: "Missing fields for registration" });
        }

        var password = User.generateHash(req.body.password);

        User.create({
            username: req.body.username,
            email: req.body.email,
            password: password
        }).then(function () {
            return res.status(200).json({ message: "user created" });
        }).catch(function (err) {
            return res.status(400).send({ message: err.message }); // 
        }).catch(function (err) {
            return res.status(500).json({ message: "issues trying to connect to database" });
        })

    }
};

**Comment by FilipeCosta** [comment]
if you can't solve it with that, reply me, say the error you get i try to help!

**Comment by ravirathoreds** [comment]
Hello Every One,

I am getting this error .

TypeError: User.validPassword is not a function
![Screenshot_7](https://user-images.githubusercontent.com/55428204/72234923-666e8480-35f5-11ea-9603-ebaf7283b837.png)
![Screenshot_3](https://user-images.githubusercontent.com/55428204/72234924-666e8480-35f5-11ea-8754-1f645c81f21a.png)

Please help me solve this issue.

Thank you.
