### ISSUE TITLE
specifying unique in model seems to generate duplicative indices in my-sql

### ISSUE THREAD

**Issue by tony-kerz** [sequelize/sequelize#7635]
> this is against `master` branch using `sync({alter: true})`, so i kno pre-release, but just wanted to capture here for reference

## What you are doing?
in model file:
```
export default function (sequelize, DataTypes) {
  return sequelize.define(
    'user',
    {
      userid: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true
      }
    }
  )
```
elsewhere:
```
await models.sequelize.sync({alter: true})
```
## What do you expect to happen?
just one index to be created

## What is actually happening?
when running `sync({alter: true})` i see:
```
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `userid` VARCHAR(255) NOT NULL UNIQUE, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): DESCRIBE `users`;
Executing (default): ALTER TABLE `users` CHANGE `userid` `userid` VARCHAR(255) NOT NULL UNIQUE;
Executing (default): SHOW INDEX FROM `users`
Executing (default): ALTER TABLE `users` ADD UNIQUE INDEX `users_userid` (`userid`)
```
then:

<img width="690" alt="screen shot 2017-05-14 at 8 27 48 am" src="https://cloud.githubusercontent.com/assets/1223231/26033751/c3b4fda2-387f-11e7-8c9b-b800b374be9c.png">

also, subsequent runs of `sync({alter: true})` seem to be adding additional indexes like `userid_{n+1}`...

__Dialect:__ mysql
__Database version:__ 5.7.18
__Sequelize version:__ master

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/6134
