### ISSUE TITLE
Include by alias or association doesn't work

### ISSUE THREAD

**Issue by L3V147H4N** [sequelize/sequelize#7640]
Using version 3.30.4 on SQL Server 2008 R2

This examples from the docs do not work

```js
User.findAll({ include: ['Instruments'] }).then(users => {
  console.log(JSON.stringify(users))

  /*
    [{
      "name": "John Doe",
      "id": 1,
      "createdAt": "2013-03-20T20:31:45.000Z",
      "updatedAt": "2013-03-20T20:31:45.000Z",
      "Instruments": [{
        "name": "Toothpick",
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "userId": 1
      }]
    }]
  */
})

User.findAll({ include: [{ association: 'Instruments' }] }).then(users => {
  console.log(JSON.stringify(users))

  /*
    [{
      "name": "John Doe",
      "id": 1,
      "createdAt": "2013-03-20T20:31:45.000Z",
      "updatedAt": "2013-03-20T20:31:45.000Z",
      "Instruments": [{
        "name": "Toothpick",
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "userId": 1
      }]
    }]
  */
})
```
First one throws: `Include unexpected. Element has to be either a Model, an Association or an object.`
Second one throws: `Cannot read property 'getTableName' of undefined`

This is the only one that works

```javascript
User.findAll({
      include: [
        {
          model: sequelize.models.Role,
          as: 'roles'
        }
      ]
    });
```

**Comment by gabrieltaets** [comment]
Just bumped into the same error and found absolutely nothing helpful anywhere.
Using sequelize@5.0.0-beta.15 with mysql2@1.6.4.
Funny thing that before upgrading from v4, including by association worked, but include.separate was broken. v5 fixed include.separate but broke include.association for me. Huh.

**Comment by hzburki** [comment]
@gabrieltaets I'm using sequelize@5.0.0-beta.15 as well. including by association works for me. Any suggestions on how would I add multiple associations? 

`include: [{ association: 'numuFamily' }, { association: 'transactions' }],`
This ^ overrides the first association

Passing an array like `['numuFamily', 'transactions']` returns
> Include unexpected. Element has to be either a Model, an Association or an object.
