### ISSUE TITLE
Soft-deleted entities are included by default when loading associations in Sequelize v4

### ISSUE THREAD

**Issue by adamjmurray** [sequelize/sequelize#7641]
## What you are doing?
I am evaluating Sequelize v4 by installing via `npm install sequelize@4.0.0-2`. A lot of tests in our app's test suite started failing with this version of Sequelize. One of the problems I am facing is that soft-deleted associated entities (we are using `paranoid: true` models) in a one-to-many relationship are being returned when I include them in a query. This appears to be a regression from Sequelize v3, where soft-deleted entities are never returned by default.

Here is an example: 

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('mysql://root@localhost/sequelize_test');

var User = sequelize.define('user', {
  name: {
    type: Sequelize.STRING
  }
});

var Role = sequelize.define('role', {
  name: {
    type: Sequelize.STRING
  }
}, { paranoid: true });

Role.belongsTo(User);
User.hasMany(Role);

var roles = [];

sequelize.sync({ force: true })
  .then(function() {
    return Role.create({ name: 'Role 1' });
  })
  .then(function(role) {
    roles.push(role);
    return Role.create({ name: 'Role 2' });
  })
  .then(function(role) {
    roles.push(role);
    return User.create({ name: 'John Doe' });
  })
  .then(function(user) {
    return user.setRoles(roles);
  })
  .then(function() {
    return roles[0].destroy();
  })
  .then(function() {
    return User.findAll({ include: [{ model: Role }] });
  })
  .then(function(users) {
    console.log(JSON.stringify(users, null, 2));
  });

```

## What do you expect to happen?
This is the output I got with Sequelize v3, and what I still expect to happen with v4:
```
[
  {
    "id": 1,
    "name": "John Doe",
    "createdAt": "2017-05-15T23:03:14.000Z",
    "updatedAt": "2017-05-15T23:03:14.000Z",
    "roles": [
      {
        "id": 2,
        "name": "Role 2",
        "createdAt": "2017-05-15T23:03:14.000Z",
        "updatedAt": "2017-05-15T23:03:14.000Z",
        "deletedAt": null,
        "userId": 1
      }
    ]
  }
]
```

## What is actually happening?
In Sequelize v4, the soft-deleted role is returned:
```
[
  {
    "id": 1,
    "name": "John Doe",
    "createdAt": "2017-05-15T23:02:36.000Z",
    "updatedAt": "2017-05-15T23:02:36.000Z",
    "roles": [
      {
        "id": 1,
        "name": "Role 1",
        "createdAt": "2017-05-15T23:02:35.000Z",
        "updatedAt": "2017-05-15T23:02:36.000Z",
        "deletedAt": "2017-05-15T23:02:36.000Z",
        "userId": 1
      },
      {
        "id": 2,
        "name": "Role 2",
        "createdAt": "2017-05-15T23:02:36.000Z",
        "updatedAt": "2017-05-15T23:02:36.000Z",
        "deletedAt": null,
        "userId": 1
      }
    ]
  }
]
```

__Dialect:__ mysql
__Database version:__  5.5.46
__Sequelize version:__ 4.0.0-2

So far, the only workaround I have found is to query like this:
```
return User.findAll({ include: [{ model: Role, where: { deletedAt: null } }] });
```
But, we include associations all over our codebase, so it would be burdensome to have to explicitly do this in every query.

Was this change intentional, or do you agree it's a regression? 

If it was intentional, is there a more convenient workaround, like being able to global configure Sequelize v4 to behave like it did in v3 in this scenario?

**Comment by adamjmurray** [comment]
PS - Your documentation says: http://docs.sequelizejs.com/manual/tutorial/models-usage.html#including-soft-deleted-records

> In case you want to eager load soft deleted records you can do that by setting include.paranoid to true

This makes me think soft-deleted associations should not be included by default, so this probably is a regression. 

I tried querying with `return User.findAll({ include: [{ model: Role, paranoid: false }] });` (and paranoid: true for comparison) and there is no effect on the query results in v4.

**Comment by sushantdhiman** [comment]
Paranoid records aren't included by default, that wont make sense :) I think you are facing same second query problem, Please check https://github.com/sequelize/sequelize/issues/7204 (Related Issue) / https://github.com/sequelize/sequelize/pull/7332 (Fix PR)

Can you please run your test against latest master ?

**Comment by adamjmurray** [comment]
Seems to be working correctly in the latest master.
