### ISSUE TITLE
Support fast storage of binary files 

### ISSUE THREAD

**Issue by radcapitalist** [sequelize/sequelize#7646]
I have an application that involves storing uploaded binary files in the database (PostgreSQL in my case).  I tried to implement this in Sequelize the way I had originally done it in MongoDB/mongoose - I pass a buffer in as the value for a bytea column.  However, it seems that when I do this, Sequelize wants to uuencode the buffer and pass it in as a SQL argument, which takes a long time - easily 10 times as long as it was taking in MongoDB.

Couldn't you support binding the buffer rather than uuencoding it?

I see that Sequelize supports raw queries, so I guess I will go that route, but it seems I lose most of the value of Sequelize by doing so.

Thanks,

Eric

**Comment by sushantdhiman** [comment]
We want bind to be used all over Sequelize queries https://github.com/sequelize/sequelize/issues/3495#issuecomment-233946112
