### ISSUE TITLE
TypeError: Cannot read property '_ended' of undefined when using mysql2

### ISSUE THREAD

**Issue by jay-davidson** [sequelize/sequelize#7647]
While attempting to use the mysql2 package for sequelize I encountered the following problem:

```
TypeError: Cannot read property '_ended' of undefined
at ConnectionManager.disconnect (./node_modules/sequelize/lib/dialects/mysql/connection-manager.js:132:27)
```
The code appears to rely on a 'private' property of the mysqljs/mysql library to see whether a connection has ended that does not exist in mysql2 (connection._protocol._ended)

```js
  // Dont disconnect connections with an ended protocol
  // That wil trigger a connection error
  if (connection._protocol._ended) {
    return Promise.resolve();
  }
```

It seems that this code has been around for over 3 years so I'm not sure why it hasn't been addressed/discovered before.

## What do you expect to happen?
I expect the code to execute correctly.  I understand that the newer versions have more support for mysql2, but as far as I can tell, the latest version that is available on npm is 3.30.2.  I have commented out the above lines and saw that the code continued.  I suggest if you are going to support both mysql and mysql2 you need to account for their incompatibilities.

## What is actually happening?
Since the condition cannot be checked when using mysql2 your library is throwing an exception and nothing will work.

__Dialect:__ mysql 
__Database version:__ 5.6.1
__Sequelize version:__ 3.30.2

**Comment by sushantdhiman** [comment]
`mysql2 ` is not supported for v3, its added in v4

**Comment by jay-davidson** [comment]
Thank you for your quick response.  I believe there is some confusion as the documentation link from npm is directed to a page with the 'latest' docs, that mention installing mysql2.  It took me quite a while to track down what was happening as I need to use features from mysql2 (authSwitch) but it appears that v4 is not packaged yet.  Hopefully the wrapper I had to write until v4 is released will hold up as it appears that the only mysqljs/mysql specific dependency was on the above mentioned code.

```js
'use strict'

const mysql2 = require('mysql2')

mysql2.Connection.prototype._protocol = function() {
  return {
    _ended: this._closing
  }
}

module.exports = mysql2

```
