### ISSUE TITLE
the result of SUM different output format

### ISSUE THREAD

**Issue by Lautitia** [sequelize/sequelize#7650]
Update sequelize from 3.30.4 to 4.0.0-2 by npm, i find the result of sum in sql have different output format

```js
select sum(amount) as amount from xxx
```
version 3.30.4

    {
      amount:-600.00
    }
version 4.0.0-2

    {
      amount:"-600.00"
    }

the result changed from number to string, i want to know if it's a feature or bug,thanks

__Dialect:__ mysql
__Database version:__ mysql 5.6
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
It's a feature - The sum might return a value that is larger than what can safely be stored in js integers

**Comment by ruiann** [comment]
@janmeier 
But can I close this feature by give some setting?
