### ISSUE TITLE
Documentation to update from 3.0 to 4.0

### ISSUE THREAD

**Issue by Joanne16** [sequelize/sequelize#7653]
Hi, do you have a manual/documentation guide for updating sequelize from 3.0 (we are actually on 3.27.0) to latest 4.0 version ? Also the documentation site does not seem to work (http://docs.sequelizejs.com/).

Thanks

**Comment by sushantdhiman** [comment]
You can have a look on BC Breaks as mentioned in https://github.com/sequelize/sequelize/blob/master/changelog.md

**Comment by DaAwesomeP** [comment]
@sushantdhiman what happened to the docs site?

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/7740
