### ISSUE TITLE
how to disable addDefaultAttributes

### ISSUE THREAD

**Issue by jiaxingzheng** [sequelize/sequelize#7656]
`addDefaultAttributes.call(this);`
Is there a option to decide whether to addDefaultAttributes?

    if ('id' in this.rawAttributes) {
      // Something is fishy here!
      throw new Error("A column called 'id' was added to the attributes of '" + this.tableName + "' but not marked with 'primaryKey: true'");
    }

Or how to  suppress the error throwed here?

**Comment by sushantdhiman** [comment]
`addDefaultAttributes` ? Please follow the issue template it saves our time
