### ISSUE TITLE
Save and fetch file using sequelize and PostgreSQL

### ISSUE THREAD

**Issue by borellaster** [sequelize/sequelize#7658]
Hello,

Someone can help me with an example, or link of how can I save and fetch (write) files (zip, rar, jpg, png and etc) with sequelize and PostgresSQL database?
I followed this link (https://gist.github.com/saumyapatel/bd29a46533a726960c10c79b1b8b4445), but didn't work as well. It generated a corrupted file (1kb).

Any help will be helpful

Thanks

Felipe

**Comment by borellaster** [comment]
Hello,

I solved that using base64 encode and decode.

Thanks.

Felipe

**Comment by thomaslc66** [comment]
@borellaster 
Hello is it possible to know how you've done it?
I'm currently trying to do the same on on of my project and retrive the file thumbnails {type: buffer, data: [array]} using the encode() in base64, but it seems that I'm not able to do it in a findAll()

Thank you for your help

Cheers
