### ISSUE TITLE
VIRTUAL that is returned

### ISSUE THREAD

**Issue by reinert** [sequelize/sequelize#7660]
I would like to declare a column that exists in the database, but should never me modified.

In other words, a VIRTUAL type that is included in SELECT statements.

How can I achieve that?

**Comment by SimonSchick** [comment]
Would overriding `set` on the attribute do the trick for you?

**Comment by reinert** [comment]
I solved by declaring a normal field (not virtual) and using 'beforeCreate' and 'beforeUpdate' hooks I remove the field I don't want to be persisted from `options.fields` array.
