### ISSUE TITLE
How I can insert GEOMETRY Point by queryInterface.bulkInsert ?

### ISSUE THREAD

**Issue by polesskiy-dev** [sequelize/sequelize#7663]
Hello! I'm trying to create seeder and insert geometry point (e.g. { type: 'Point', coordinates: [39.807222,-76.984722]}) by queryInterface.bulkInsert. But I didn't understand how I can perform it. Any suggestions?

__Dialect:__postgres 
__Database version: 9.6
__Sequelize version: 3.30.2

**Comment by SpikeO** [comment]
I found a solution for this problem:
`geoLocation: sequelize.fn('ST_GeomFromText', 'POINT(50.871962 4.287370999999999)'),`

(**NOTE**: there is only a space between the coordinates, no comma)

**Comment by Camophile** [comment]
If you're still getting an error with this code, I had to add the SRID as a third parameter, so

```
geoLocation: sequelize.fn('ST_GeomFromText', 'POINT(50.871962 4.287370999999999)', '4326'),
```

worked for me
