### ISSUE TITLE
error: password authentication failed for user for Postgres

### ISSUE THREAD

**Issue by dylanjt** [sequelize/sequelize#7666]
## What you are doing?

```js
const sequelize = new Sequelize('postgres://admin:PASSWORD@URL:PORT/compose', { dialect: 'postgres', protocol: 'postgres', ssl: true })
```

## What do you expect to happen?
I expect to establish a connection to my Compose-hosted Postgres instance. I am 100% certain that my connection string is valid, as I got it directly from Compse, and I've tested it on other clients: Positco and pg-promise.

## What is actually happening?
`error: password authentication failed for user "admin"`

I have added a console output in `node_modules/pg/lib/connection.js` to verify the config object getting passed in:

```
{ database: 'compose',
  username: 'admin',
  password: 'PASSWORD',
  host: 'URL',
  port: 'PORT',
  pool:
   { max: 5,
     min: 0,
     idle: 10000,
     handleDisconnects: true,
     validate: [Function: bound ] },
  protocol: 'postgres',
  native: false,
  ssl: true,
  replication: false,
  dialectModulePath: null,
  keepDefaultTimezone: undefined,
  dialectOptions: undefined }
```

Postgres 9.5.5, Sequelize 3.6.0

**Comment by dylanjt** [comment]
updated and tested on 3.30.4, same output.

**Comment by dylanjt** [comment]
Update: I've resolved this issue by bringing pg and pg-hstore up to date.

**Comment by parth3004** [comment]
how you resolved the issue
