### ISSUE TITLE
findAndCountAll counts more then needed with hasMany associations in includes as filters

### ISSUE THREAD

**Issue by rusekr** [sequelize/sequelize#7671]
Hello!
Using Sequelize 3.30.2. Mysql 5.6 / MariaDB 10.1.22 / Postgres 9.6.2 (examples from it)

I have Products model and ProductSaleComponents (prices) model.

Products.hasMany(ProductSaleComponents)

ProductSaleComponents has regionId property and one Product can have many prices with same regionId (but different associated to price features).

Now I need to to Filter products ids for one page (using principle to filter out IDs with first query and then get all information for resulting IDs with another query):

   Products.findAndCountAll({
      subQuery: false,
      attributes: ['id'],
      where: {
        type: 'service',
      },
      include: [{model: ProductSaleComponents, as: 'prices', where: { regionId: { $in: [regionId, defaultRegionId] } } }],
      limit: limit,
      offset: offset,
      order: productsOrder
    })

I'm using subQuery === false because with subqueries limit placed in wrong place (in internal query).

It generates query for count:

SELECT count("Products"."id") AS "count" FROM "Products" AS "Products" INNER JOIN "ProductSaleComponents" AS "prices" ON "Products"."id" = "prices"."productId" AND "prices"."regionId" IN (1, 1) WHERE "Products"."type" = 'service';

which returs 35 instead of 20 because of "prices".

And query for find: 

SELECT "Products"."id", "Products"."hidden", "Products"."sortIndex", "prices"."id" AS "prices.id", "prices"."regionId" AS "prices.regionId", "prices"."productId" AS "prices.productId" FROM "Products" AS "Products" INNER JOIN "ProductSaleComponents" AS "prices" ON "Products"."id" = "prices"."productId" AND "prices"."regionId" IN (1, 1) WHERE "Products"."type" = 'service' ORDER BY "Products"."hidden" ASC, "Products"."sortIndex" ASC, "Products"."id" ASC LIMIT 24 OFFSET 0;

With subQuery: true query for count is the same as above but query for find is:

SELECT "Products".*, "prices"."id" AS "prices.id", "prices"."regionId" AS "prices.regionId", "prices"."productId" AS "prices.productId" FROM (SELECT "Products"."id", "Products"."hidden", "Products"."sortIndex" FROM "Products" AS "Products" WHERE "Products"."type" = 'service' AND ( SELECT "productId" FROM "ProductSaleComponents" AS "ProductSaleComponents" WHERE ("ProductSaleComponents"."productId" = "Products"."id" AND "ProductSaleComponents"."regionId" IN (1, 1)) LIMIT 1 ) IS NOT NULL ORDER BY "Products"."hidden" ASC, "Products"."sortIndex" ASC, "Products"."id" ASC LIMIT 24 OFFSET 0) AS "Products" INNER JOIN "ProductSaleComponents" AS "prices" ON "Products"."id" = "prices"."productId" AND "prices"."regionId" IN (1, 1) ORDER BY "Products"."hidden" ASC, "Products"."sortIndex" ASC, "Products"."id" ASC;

## What do you expect to happen?

I'am expecting to get number of products, filtered by assocications.

## What is actually happening?

I'am getting number of products plus number of prices..

Can I generate something like?:

SELECT count("Products"."id") FROM "Products" AS "Products" 
INNER JOIN 
    (select "prices_inner"."productId" from "ProductSaleComponents" AS "prices_inner"  where "prices_inner"."regionId" IN (1, 1) group by "productId") as "prices" 
    ON "Products"."id" = "prices"."productId" WHERE "Products"."type" = 'service';

It is subquery but only for association with grouping by parent table id for not alter parent table rows count.

Tried group in prices include (group: 'productId') but without success, it won't affect the query.

Is any workaround?

**Comment by preraksola** [comment]
I am also facing the same issue with `hsaMany` relationship. @rusekr did you get any workaround or the correct way to make this work?

**Comment by rusekr** [comment]
No workaround so far except of manual query.

**Comment by MofeLee** [comment]
you need add "distinct" option

```js
Products.findAndCountAll({
 /.../
 distinct: true
});
```

```sql
SELECT count(DISTINCT ([Product].[Id])) AS [count]
```

**Comment by L3V147H4N** [comment]
see answer at #2713, you need to use `distinct: true`

**Comment by rusekr** [comment]
Case closed with `distinct: 'id'` Thanks!

**Comment by AnhTuan2804** [comment]
> you need add "distinct" option
> 
> ```js
> Products.findAndCountAll({
>  /.../
>  distinct: true
> });
> ```
> 
> ```sql
> SELECT count(DISTINCT ([Product].[Id])) AS [count]
> ```

Good solution.
