### ISSUE TITLE
Sequelize and pg-promise

### ISSUE THREAD

**Issue by radcapitalist** [sequelize/sequelize#7677]
Hey,
I asked this on [StackOverflow ](https://stackoverflow.com/questions/44080223/node-js-reconciling-sequelize-and-pg-large-object) a few days ago but did not get a response.  So I'm making it into a feature request so I can post it here.

I started out using [Sequelize](https://github.com/sequelize/sequelize) with Postgres underneath, but my project requires storage of large binary files in the database, which Sequelize cannot seem to do efficiently.  So I found [pg-large-object](https://github.com/Joris-van-der-Wel/node-pg-large-object), which works well for the binary file aspect.  But pg-large-object is built on [pg-promise](https://github.com/vitaly-t/pg-promise), which seems to have its own pg connection pool. I don't see a way to make Sequelize and pg-promise share a pg connection

Is there any way that Sequelize and pg-promise can share a connection pool?  If not, that is my feature request.  I would hate to have to jettison Sequelize just so I can use pg-large-object/pg-promise to handle binary files.  But I don't think I can have a transaction that encapsulates two connections, one for Sequelize and one for pg-promise.

Thanks,

Eric

**Comment by vitaly-t** [comment]
If Sequelize can execute against a specified [Client](https://github.com/brianc/node-postgres/blob/master/lib/client.js#L20) object, then it is possible to share a task/transaction between Sequelize and pg-promise. But I don't know if Sequelize can actually do it.

**Comment by radcapitalist** [comment]
Thanks, Vitaly.  I have searched Sequelize source code and docs for a way to do something like that, and I do not see a way.  I think if it were an easy "Yes, you can!", that answer would have appeared here by now.

Eric

**Comment by janmeier** [comment]
Sequelize uses it's own pool, instead of that built into the pg library. This is so that we can share the pool code between all dialects, instead of relying on the implementation of the connector library. So thee is no easy way to share connections

**Comment by vitaly-t** [comment]
> Sequelize uses it's own pool, instead of that built into the pg library.

This was ok in the past, but now that `node-postgres` 6.x uses a stand-alone connection pool [pg-pool], it makes sense to start reusing it. Without reusing it you will end up with more than one connection pool in the process, which creates such problem as impossibility to match the physical connection limit that a hosting provider enforces.

This is why [pg-promise 6.x] switched over to the new pool fully, and in addition, its [Database] object also exposes the pool object via property [$pool], to make it possible to reuse the pool where necessary.

[pg-pool]:https://github.com/brianc/node-pg-pool
[pg-promise 6.x]:https://github.com/vitaly-t/pg-promise/tree/6.x
[Database]:http://vitaly-t.github.io/pg-promise/Database.html
[$pool]:http://vitaly-t.github.io/pg-promise/Database.html#.$pool
