### ISSUE TITLE
How to define column type smallint in migration file

### ISSUE THREAD

**Issue by vipzhicheng** [sequelize/sequelize#7678]
I even can not find smallint or int2 in sequelize source code, so how should I do if I want to define smallint type field.

Do I need to define fields half by Sequelize.TYPE, and/or 'smallint', this way?

Sorry for my poor English. But it confuse me a lot.

**Comment by vipzhicheng** [comment]
My db engine is Postgres

**Comment by felpin** [comment]
This is still an issue
