### ISSUE TITLE
Super Weird Issue

### ISSUE THREAD

**Issue by Dellybro** [sequelize/sequelize#7679]
## What you are doing?

Let me begin by saying that PRODUCTMETUMID EXISTS NO WHERE IN MY PROJECT

SEQUELIZE has created this field and attached it to the sql database call

models.orderItem.findOne({}).then(item => {

}).catch(err => {

})

## What do you expect to happen?

I expect to get the instance of my OrderItem back, the thing is there is no such column as productMetumID, like no where in my project is there the word ProductMetumID, 

sequelize has some how randomy just created this field name and threw it in my field list

## What is actually happening?

{
  "message": "Internal Error",
  "code": 500,
  "result": {
    "success": false,
    "errors": {
      "name": "SequelizeDatabaseError",
      "message": "ER_BAD_FIELD_ERROR: Unknown column 'ProductMetumId' in 'field list'",
      "parent": {
        "code": "ER_BAD_FIELD_ERROR",
        "errno": 1054,
        "sqlState": "42S22",
        "index": 0,
        "sql": "SELECT `id`, `value`, `OrderItemId`, `ProductMetaId`, `createdAt`, `updatedAt`, `ProductMetumId` FROM `OrderItemMeta` AS `OrderItemMeta` WHERE `OrderItemMeta`.`id` = '1';"
      },
      "original": {
        "code": "ER_BAD_FIELD_ERROR",
        "errno": 1054,
        "sqlState": "42S22",
        "index": 0,
        "sql": "SELECT `id`, `value`, `OrderItemId`, `ProductMetaId`, `createdAt`, `updatedAt`, `ProductMetumId` FROM `OrderItemMeta` AS `OrderItemMeta` WHERE `OrderItemMeta`.`id` = '1';"
      },
      "sql": "SELECT `id`, `value`, `OrderItemId`, `ProductMetaId`, `createdAt`, `updatedAt`, `ProductMetumId` FROM `OrderItemMeta` AS `OrderItemMeta` WHERE `OrderItemMeta`.`id` = '1';"
    }
  }
}

 code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     index: 0,
     sql: 'SELECT `id`, `value`, `OrderItemId`, `ProductMetaId`, `createdAt`, `updatedAt`, `ProductMetumId` FROM `OrderItemMeta` AS `OrderItemMeta` WHERE `OrderItemMeta`.`id` = \'1\';' },
  original: 
   { Error: ER_BAD_FIELD_ERROR: Unknown column 'ProductMetumId' in 'field list'

Dialect: mysql
__Database version:__ latest-stable
__Sequelize version:__ latest-stable

**Comment by Dellybro** [comment]
Edit: Metum, Seems to be the singular version of Meta so when using a belongsTo relationship

**Comment by danscrima** [comment]
I believe I am having a similar issue. I have a Question model and an Answer model. I have it set that Answer.belongsTo(Question) and when I try to query for an Answer using .findOne, the query that is generated is added an "answer_id" as part of the SELECT. I have answer_is nowhere as well!! I'm using version 4.1.0

**Comment by josersleal** [comment]
I am having the same error...

Full error dump:

Executing (default): SELECT `user`.*, `roles`.`id` AS `roles.id`, `roles`.`role` AS `roles.role`, `roles->user_has_role`.`User_id` AS `roles.user_has_role.User_id`, `roles->user_has_role`.`Role_id` AS `roles.user_has_role.Role_id`, `roles->user_has_role`.`userId` AS `roles.user_has_role.userId`, `roles->user_has_role`.`roleId` AS `roles.user_has_role.roleId` FROM (SELECT `user`.`id`, `user`.`email`, `user`.`first_name`, `user`.`last_name`, `user`.`access_start`, `user`.`access_end`, `user`.`phone_number`, `user`.`attachment_link`, `user`.`Overall_status_id`, `user`.`account_valid` FROM `user` AS `user` LIMIT 10) AS `user` LEFT OUTER JOIN ( `user_has_role` AS `roles->user_has_role` INNER JOIN `role` AS `roles` ON `roles`.`id` = `roles->user_has_role`.`roleId` AND `roles->user_has_role`.`Role_id` = 3) ON `user`.`id` = `roles->user_has_role`.`userId`;
{ SequelizeDatabaseError: Unknown column 'roles->user_has_role.userId' in 'field list'
    at Query.formatError (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:89:29)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
  name: 'SequelizeDatabaseError',
  parent:
   { Error: Unknown column 'roles->user_has_role.userId' in 'field list'
    at Packet.asError (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:89:29)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     sqlMessage: 'Unknown column \'roles->user_has_role.userId\' in \'field list\'',
     sql: 'SELECT `user`.*, `roles`.`id` AS `roles.id`, `roles`.`role` AS `roles.role`, `roles->user_has_role`.`User_id` AS `roles.user_has_role.User_id`, `roles->user_has_role`.`Role_id` AS `roles.user_has_role.Role_id`, `roles->user_has_role`.`userId` AS `roles.user_has_role.userId`, `roles->user_has_role`.`roleId` AS `roles.user_has_role.roleId` FROM (SELECT `user`.`id`, `user`.`email`, `user`.`first_name`, `user`.`last_name`, `user`.`access_start`, `user`.`access_end`, `user`.`phone_number`, `user`.`attachment_link`, `user`.`Overall_status_id`, `user`.`account_valid` FROM `user` AS `user` LIMIT 10) AS `user` LEFT OUTER JOIN ( `user_has_role` AS `roles->user_has_role` INNER JOIN `role` AS `roles` ON `roles`.`id` = `roles->user_has_role`.`roleId` AND `roles->user_has_role`.`Role_id` = 3) ON `user`.`id` = `roles->user_has_role`.`userId`;' },
  original:
   { Error: Unknown column 'roles->user_has_role.userId' in 'field list'
    at Packet.asError (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (C:\Projects\acn\hr_tool\hr-tool-api\node_modules\mysql2\lib\connection.js:89:29)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     sqlMessage: 'Unknown column \'roles->user_has_role.userId\' in \'field list\'',
     sql: 'SELECT `user`.*, `roles`.`id` AS `roles.id`, `roles`.`role` AS `roles.role`, `roles->user_has_role`.`User_id` AS `roles.user_has_role.User_id`, `roles->user_has_role`.`Role_id` AS `roles.user_has_role.Role_id`, `roles->user_has_role`.`userId` AS `roles.user_has_role.userId`, `roles->user_has_role`.`roleId` AS `roles.user_has_role.roleId` FROM (SELECT `user`.`id`, `user`.`email`, `user`.`first_name`, `user`.`last_name`, `user`.`access_start`, `user`.`access_end`, `user`.`phone_number`, `user`.`attachment_link`, `user`.`Overall_status_id`, `user`.`account_valid` FROM `user` AS `user` LIMIT 10) AS `user` LEFT OUTER JOIN ( `user_has_role` AS `roles->user_has_role` INNER JOIN `role` AS `roles` ON `roles`.`id` = `roles->user_has_role`.`roleId` AND `roles->user_has_role`.`Role_id` = 3) ON `user`.`id` = `roles->user_has_role`.`userId`;' },
  sql: 'SELECT `user`.*, `roles`.`id` AS `roles.id`, `roles`.`role` AS `roles.role`, `roles->user_has_role`.`User_id` AS `roles.user_has_role.User_id`, `roles->user_has_role`.`Role_id` AS `roles.user_has_role.Role_id`, `roles->user_has_role`.`userId` AS `roles.user_has_role.userId`, `roles->user_has_role`.`roleId` AS `roles.user_has_role.roleId` FROM (SELECT `user`.`id`, `user`.`email`, `user`.`first_name`, `user`.`last_name`, `user`.`access_start`, `user`.`access_end`, `user`.`phone_number`, `user`.`attachment_link`, `user`.`Overall_status_id`, `user`.`account_valid` FROM `user` AS `user` LIMIT 10) AS `user` LEFT OUTER JOIN ( `user_has_role` AS `roles->user_has_role` INNER JOIN `role` AS `roles` ON `roles`.`id` = `roles->user_has_role`.`roleId` AND `roles->user_has_role`.`Role_id` = 3) ON `user`.`id` = `roles->user_has_role`.`userId`;' }
{
    "name": "SequelizeDatabaseError",
    "parent": {
        "code": "ER_BAD_FIELD_ERROR",
        "errno": 1054,
        "sqlState": "42S22",
        "sqlMessage": "Unknown column 'roles->user_has_role.userId' in 'field list'",
        "sql": "SELECT `user`.*, `roles`.`id` AS `roles.id`, `roles`.`role` AS `roles.role`, `roles->user_has_role`.`User_id` AS `roles.user_has_role.User_id`, `roles->user_has_role`.`Role_id` AS `roles.user_has_role.Role_id`, `roles->user_has_role`.`userId` AS `roles.user_has_role.userId`, `roles->user_has_role`.`roleId` AS `roles.user_has_role.roleId` FROM (SELECT `user`.`id`, `user`.`email`, `user`.`first_name`, `user`.`last_name`, `user`.`access_start`, `user`.`access_end`, `user`.`phone_number`, `user`.`attachment_link`, `user`.`Overall_status_id`, `user`.`account_valid` FROM `user` AS `user` LIMIT 10) AS `user` LEFT OUTER JOIN ( `user_has_role` AS `roles->user_has_role` INNER JOIN `role` AS `roles` ON `roles`.`id` = `roles->user_has_role`.`roleId` AND `roles->user_has_role`.`Role_id` = 3) ON `user`.`id` = `roles->user_has_role`.`userId`;"
    },
    "original": {
        "code": "ER_BAD_FIELD_ERROR",
        "errno": 1054,
        "sqlState": "42S22",
        "sqlMessage": "Unknown column 'roles->user_has_role.userId' in 'field list'",
        "sql": "SELECT `user`.*, `roles`.`id` AS `roles.id`, `roles`.`role` AS `roles.role`, `roles->user_has_role`.`User_id` AS `roles.user_has_role.User_id`, `roles->user_has_role`.`Role_id` AS `roles.user_has_role.Role_id`, `roles->user_has_role`.`userId` AS `roles.user_has_role.userId`, `roles->user_has_role`.`roleId` AS `roles.user_has_role.roleId` FROM (SELECT `user`.`id`, `user`.`email`, `user`.`first_name`, `user`.`last_name`, `user`.`access_start`, `user`.`access_end`, `user`.`phone_number`, `user`.`attachment_link`, `user`.`Overall_status_id`, `user`.`account_valid` FROM `user` AS `user` LIMIT 10) AS `user` LEFT OUTER JOIN ( `user_has_role` AS `roles->user_has_role` INNER JOIN `role` AS `roles` ON `roles`.`id` = `roles->user_has_role`.`roleId` AND `roles->user_has_role`.`Role_id` = 3) ON `user`.`id` = `roles->user_has_role`.`userId`;"
    },
    "sql": "SELECT `user`.*, `roles`.`id` AS `roles.id`, `roles`.`role` AS `roles.role`, `roles->user_has_role`.`User_id` AS `roles.user_has_role.User_id`, `roles->user_has_role`.`Role_id` AS `roles.user_has_role.Role_id`, `roles->user_has_role`.`userId` AS `roles.user_has_role.userId`, `roles->user_has_role`.`roleId` AS `roles.user_has_role.roleId` FROM (SELECT `user`.`id`, `user`.`email`, `user`.`first_name`, `user`.`last_name`, `user`.`access_start`, `user`.`access_end`, `user`.`phone_number`, `user`.`attachment_link`, `user`.`Overall_status_id`, `user`.`account_valid` FROM `user` AS `user` LIMIT 10) AS `user` LEFT OUTER JOIN ( `user_has_role` AS `roles->user_has_role` INNER JOIN `role` AS `roles` ON `roles`.`id` = `roles->user_has_role`.`roleId` AND `roles->user_has_role`.`Role_id` = 3) ON `user`.`id` = `roles->user_has_role`.`userId`;"
}
