### ISSUE TITLE
Foreign Key names duplicate when fetching

### ISSUE THREAD

**Issue by hassanrazakhalid** [sequelize/sequelize#7682]
Hello i am facing an issue when i user findAll i get response
```
{
"id": 1,
"caqhId": null,
"caqhPassword": "323",
"degree": "323",
"dob": null,
"emails": "[{"email": "pk112233@hotmail.com"}]",
"faxNumbers": null,
"firstName": "sss",
"lastName": "ddd",
"medicareId": null,
"npiNum": "1336150432",
"phoneNumbers": null,
"socialSecurityNumber": null,
"entityId": 3,
"otherInfoId": null,
"qualiticationId": null,
"entity_id": 3,
"otherInfo_id": null,
"qualitication_id": null
}
```
Buti get duplicated 'entity_id' and 'entityId'. Here sequelizer is generating entityId and in my DB i ve 'entity_id'. I know i can use exclude when fetching but is there some other way i can configure when making associations and with changing the db structure.

```
this.entity.hasMany(this.provider, {as: 'entity', foreignKey: 'entity_id'})
this.provider.belongsTo(this.entity, {as: 'entity', foreignKey: 'entity_id'})
```
In provider.js i ve defined foreignKey 
```
//more fields
entityId: {
      type: DataTypes.INTEGER(11),
      allowNull: true,
      references: {
        model: 'entity',
        key: 'id'
      },
      field: 'entity_id'
    }
```

**Comment by weldermarcosxd** [comment]
This happens to me as well. How to remove this modelId or even rename it in foreign keys?

**Comment by xxxtonixxx** [comment]
I have the same problem, how could I resolve it? 😢

**Comment by xxxtonixxx** [comment]
This issue isn't resolved yet

**Comment by grutty-sf** [comment]
😓me too  This issue isn't resolved yet

**Comment by grutty-sf** [comment]
`
                attributes: {
                    exclude: ['createdAt', 'updatedAt', 'deletedAt', 'created_at', 'updated_at', 'deleted_at'],
                },
`

**Comment by sushantdhiman** [comment]
`foreignKey` is attribute name not field name, its the attribute that will be injected or used if already defined in model.

So by setting `entity_id` as `foriegnKey` you are asking sequelize to inject an attribute `entity_id` in `provider` plus your are defining an attribute `entityId` yourself, you will 100% get duplicate results. Now you have two attributes `entity_id` and `entityId` in `provider` model both pointing to field `entity_id`

```js
/// Change this
this.entity.hasMany(this.provider, {as: 'entity', foreignKey: 'entity_id'})
this.provider.belongsTo(this.entity, {as: 'entity', foreignKey: 'entity_id'})

/// To this
this.entity.hasMany(this.provider, {as: 'entity', foreignKey: 'entityId'})
this.provider.belongsTo(this.entity, {as: 'entity', foreignKey: 'entityId'})
```

As you already have defined attribute `entityId` (with field `entity_id`) in `provider` model, it will use `entity_id` when communicating with database

```js
//more fields
   entityId: {
      type: DataTypes.INTEGER(11),
      allowNull: true,
      references: {
        model: 'entity',
        key: 'id'
      },
      field: 'entity_id'
    }
```
