### ISSUE TITLE
A simple question about the `null` value filter

### ISSUE THREAD

**Issue by JackieLs** [sequelize/sequelize#7687]
I have a demand like these:
- If a field's value is `null`, Model.find() could not auto filter the field. Just like the field `userID`. How could I filter the `null` field?
- ` tid` is our primaryKey, but in some Model, I would not return it to the frontend.I konw I could use `removeAttribute`, but is there any other solution? Maybe some option in the model.

My code is here
```js
const services = Mind.define('service_order_logs', {
	tid:{
		type: Sequelize.BIGINT,
		primaryKey: true,
		autoIncrement: true
	},
	service_order_id: {
		type: Sequelize.STRING,
		allowNull: false
	},
	userID: {
		type: Sequelize.STRING,
		field: 'user_id'
	},
	comment: {
		type: Sequelize.STRING,
	},
	action:{
		type: Sequelize.STRING,
		allowNull: false
	},
	source: {
		type: Sequelize.TEXT
	},
	logTime: {
		type: Sequelize.DATE,
		defaultValue: Sequelize.NOW,
		field: 'log_time'
	}
}, {
	createdAt: 'create_time',
	updatedAt: false
})
```

**Comment by ox** [comment]
Do you mean something like ["scopes"](http://docs.sequelizejs.com/manual/tutorial/scopes.html), where you can specify to always have a filter enabled? Are you trying to only return `service_order_logs` where `userID` is not `null`?

For your second question: our application deals with this by creating an instance method on the model that strips the model of any sensitive columns like (assuming you're using Sequelize v3):

```js
const services = Mind.define('service_order_logs', {
  // model attributes
}, {
  createdAt: 'create_time',
  updatedAt: false,
  instanceMethods: {
    safeResponse() {
      const response = this.get({plain: true});
      delete response.tid;
      return response;
    }
  }
});
```

and so when you want to send a response:

```js
// example express.js app
app.get('/service_order_logs/:tid', (req, res) => {
  return services.findById(req.params.tid)
    .then((service_order_log) => {
      res.json({
        log: service.order_log.safeResponse()
      });
    });
});
```

**Comment by JackieLs** [comment]
Thx for the second question.
For the First Just like
the data in database is
```
[{
 a: null,
 b: 123
},{
 a: 123,
 b: null
}]
```
and what i wanna it return is 
```
[{
 b: 123
},{
 a: 123
}]
```
the `null` value is filtered. 
Just Like the golang `omitempty`

**Comment by danfsd** [comment]
+1 that would be *very helpful*.

Maybe this `omitEmpty` key could be added to the `scopes` like we do with  `attributes.include` and `attributes.exclude`.
