### ISSUE TITLE
Not returning id on create

### ISSUE THREAD

**Issue by hudson-t** [sequelize/sequelize#7689]
## What you are doing?
Using `model.create` to insert an item in the database and using .then(item) to capture the inserted item.

> BTW: I am using TypeScript!

```ts
db.unity.SiteAlias.create(siteAlias).then((addedAlias: ISiteAlias) => {
    console.log(addedAlias);
});
```

**Model**
```ts
export default function (sequelize: Sequelize, dataTypes: DataTypes) {
    const SiteAlias = sequelize.define("SiteAlias", {
        id: {
            type: dataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        name: {
            type: dataTypes.STRING,
            unique: true
        },
        ignore: {
            type: dataTypes.BOOLEAN,
            defaultValue: false
        },
        serviceType: {
            type: dataTypes.INTEGER,
            allowNull: true,
            defaultValue: 1
        },
        siteId: {
            type: dataTypes.INTEGER,
            allowNull: true
        }
    }, {
            freezeTableName: true
        });
    return SiteAlias;
}
```

## What do you expect to happen?
I expected the returned object to contain the id of the inserted item.

## What is actually happening?
I get the item returned but with an undefined id value:
![image](https://cloud.githubusercontent.com/assets/26221061/26452274/4fc1785e-4157-11e7-9c15-2c72e5557853.png)

__Dialect:__ mssql
__Database version:__ 11.0.3000.0
__Sequelize version:__ 3.34.4

**Comment by felixfbecker** [comment]
Please check if the issue is still present in v4.

**Comment by hudson-t** [comment]
@felixfbecker - still a problem:
![image](https://user-images.githubusercontent.com/26221061/27024888-5bcc15ee-4f50-11e7-8ffa-594bbb12640f.png)

**Comment by felixfbecker** [comment]
Can you show the actual schema in the database?

**Comment by hudson-t** [comment]
@felixfbecker - I assume you meanm just the table? Here you go:

![image](https://user-images.githubusercontent.com/26221061/27024995-bd4e4ed6-4f50-11e7-8bf8-c0fa2c810de7.png)

**Comment by ox** [comment]
Having trouble reproducing this (postgres 9.6, sequelize 3.30.4). Are you sure that the `id` column has the `auto_increment` EXTRA attribute in your table (from looking at [this comment on SO](https://stackoverflow.com/a/13772062))?

**Comment by hudson-t** [comment]
@ox - I made a mistake on my post. I am using MsSQL not MySQL. Sorry!

If I enable logging of queries and run the SQL Sequelize generates on the DB directly (different table in this example):
```
INSERT INTO [AssetAlias] ([name],[ignore],[siteAliasId],[assetTypeAliasId],[serviceType]) OUTPUT INSERTED.* VALUES (N'Linked Alias 1',0,3693,5795,1);
```

The inserted entry is returned post execution. Sequelize just doesn't seem to be grabbing the ID and sending it back.

**Comment by Tom-Hudson** [comment]
@felixfbecker - can this be re-opened. Its been 8 months, I am using Sequelize v4.28.6 with tedious v2.1.5 now and I am still not getting the id returned on the model returned from the promise for a create!

I have tried every suggestion and gave you everything I possibly can. Can someone do a remote session with me or something?

**Comment by Tom-Hudson** [comment]
For anyone who lands here, I had come support via Slack from @janmeier. My problem was that the Id column in the database is capitalised, and my model definition was lowercase. So I added  `field: 'Id'` to the id property of my model and it to worked!

**Comment by dsbert** [comment]
@Tom-Hudson Thank you for coming back and updating this. I hit the same issue and your solution worked.

**Comment by jnreynoso** [comment]
Hi, I have the same problem, but in my case the column id of my model is equal to database column, and I still have the same error.

**Comment by Tom-Hudson** [comment]
@jnreynoso post your sequelize model and the database schema. I assume your situation was like mine in that you are looking to work with an existing database and not creating it with sequelize?

**Comment by jnreynoso** [comment]
@Tom-Hudson my solution was to do the migrations and go back to running them, I have no idea why that happened.

Greetings.

**Comment by ryanburnette** [comment]
I'm having this issue with 4.41.0 + sqlite. My `id` column is not capitalized. I'm creating my database using `sync`.

**Comment by insanjati** [comment]
Hi all, I have exactly the same problem, in my case also the column id of my model is equal to database, but I can't undo the migrations, because I didn't use it from the first time. I just migrated from loopback and use sequelize ORM not long ago in my project. So I applied Sequelize in existing table.

**Comment by ldonis** [comment]
I had the same issue a couple of days ago, my problem was that model needs to have same properties of the migrations. example: in this case, model also needs to have auto-increment property set to true, not only migration.
        id: {
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
            type: DataTypes.INTEGER(10)
        },

**Comment by Palpie** [comment]
This is still a problem when using UUID as primary key and the value is generated by the database, for example using `NEWSEQUENTIALID()` as default value in Microsoft SQL Server.

**Comment by nicolaelia** [comment]
It seems like this problem occurs also when a model is defined as join table between other two models. 
@skaterdav85 's answer solved the issue in this case.

**Comment by niraj-khatiwada** [comment]
The id will be undefined if you have any other field name _id in the same model. Remove that and it will work.

**Comment by smcaleese** [comment]
One solution to this problem is to have a custom variable (eg. let id = 0) in your server and increment it every time you sign up a new user.

**Comment by BergerMarcin** [comment]
***MY SOLUTION***
After 2h research **I found solution for PostgreSQL with UUID as id and raw SQL queries by ... adding `RETURN id` at the end of the query** (for example: `INSERT INTO tasks VALUES (uuid_generate_v4(), $1 , NOW()) RETURNING id`)

I found it @ https://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id inspired by https://github.com/sequelize/sequelize/issues/5499#issuecomment-480528090

More details on my recruitment public small project: https://github.com/BergerMarcin/time-tracking

**Comment by Clearmist** [comment]
Based on skaterdav's answer. This solution worked for me. Normally the key of the object in your definition is taken as the field name, but for the primary key field the id could not be returned after creation unless I changed the key in the definition to `id` and moved the column name to the `field` key.

### Before
```js
const columns = {
  accountID: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
};
```

### After
```js
const columns = {
  id: {
    field: 'accountID',
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
};
```

**Comment by amouratoglou** [comment]
Created response doesn't include id, is null?
Solution:
- Remove the id from the model definition.
