### ISSUE TITLE
Can't create geometric point 

### ISSUE THREAD

**Issue by FilipeCosta** [sequelize/sequelize#7693]
Hello guys,

I am working with NodeJS/Sequelize and i am building my models like this:

```
module.exports = function (sequelize, DataTypes) {
  var Foto = sequelize.define("Foto", {
    reports: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    image: {
      type: DataTypes.STRING,
      allowNull: false
    },
    date: {
      type: DataTypes.DATE,
      allowNull: true
    },
    position: {
      type: DataTypes.STRING,
      allowNull: true
    },
    userId:{
      type: DataTypes.INTEGER,
      allowNull:false
    },
     plantId:{
      type: DataTypes.INTEGER,
      allowNull:true
    }
  });

  return Foto;
}
```

as you guys can see i have a **position field** it is as a String at the moment, but i want to set it as a geomtic point Datatype, i tried GEOMETRY('POINT') but it say that it is not a function :/.

Any help with this?

**Comment by janmeier** [comment]
Which sequelize version are you using? Are you sure it includes geometry support? 

Please show the code you tried
