### ISSUE TITLE
'include'  automatically add itself issue?

### ISSUE THREAD

**Issue by xkguq007** [sequelize/sequelize#7696]
The sql I wanted is
select * from [Booking] inner join [Room] room on room.pensionId = 'Foo'
this comes out exactly what i want. (tested on heidisql)
so, i did is

models.Booking
  .findAll({
    attributes: ['id'], // for testing
    include: [
      {
        model: models.Room,
        attributes: ['name'], // for testing
        where: { pensionId: request.params.pensionId }
      }
    ]
  })

However, it comes

SELECT [Booking].[id], [Room].[id] AS [Room.id], [Room].[name] AS [Room.name] FROM [Booking] AS [Booking] INNER JOIN [Room] AS [Room] ON [Booking].[roomId] = [Room].[id] AND [Room].[pensionId] = N'Foo';

Problem is why automatically include this clause????
[Booking].[roomId] = [Room].[id]
this will be perfect without above clause.

am i use wrong?

**Comment by sushantdhiman** [comment]
Properly format your code and follow the issue request format
