### ISSUE TITLE
'include' itself issue?

### ISSUE THREAD

**Issue by xkguq007** [sequelize/sequelize#7697]
## What you are doing?
```js
models.Booking
.findAll({
attributes: ['id'], // for testing
include: [
{
model: models.Room,
attributes: ['name'], // for testing
where: { pensionId: request.params.pensionId }
}
]
})
```

## What do you expect to happen?
The sql I wanted is
````select * from [Booking] inner join [Room] room on room.pensionId = 'Foo'````
this comes out exactly what i want. (tested on heidisql)

## What is actually happening?
However, it comes
````SELECT [Booking].[id], [Room].[id] AS [Room.id], [Room].[name] AS [Room.name] FROM [Booking] AS [Booking] INNER JOIN [Room] AS [Room] ON [Booking].[roomId] = [Room].[id] AND [Room].[pensionId] = N'Foo';````

Problem is why automatically include this clause????
````[Booking].[roomId] = [Room].[id]````
this will be perfect without above clause.

__Dialect:__ mssql

**Comment by sushantdhiman** [comment]
`[Booking].[roomId] = [Room].[id]` is the join condition between these two models, for each booking it will look for its room + other conditions you want to query for.

If we dont add this condition it will add other rooms to query as well which may not belong to booking, giving incorrect result

**Comment by xkguq007** [comment]
Oh i understand.
it was my fault.
If that clause doesn't exist, it returns same arrays. thanks.
I will close issue.
