### ISSUE TITLE
Documentation for Installation is incorrect

### ISSUE THREAD

**Issue by kylegoetz** [sequelize/sequelize#7709]
According to https://github.com/sequelize/sequelize, v4 is the stable branch. If you go to the "Stable" documentation (https://github.com/sequelize/sequelize/blob/master/docs/getting-started.md), it says in the installation section to run `npm install sequelize`. However, this installs v3, not v4 (npm's own site lists 3.30 as the latest sequelize). The documentation needs to be corrected. I don't know how to install v4 with npm or else I'd do it and submit a PR for the docs.

I caught this because the docs say to `npm install mysql2`, but `npm install sequelize` followed by that will not work because you will have installed mysql2, but the sequelize v3 that gets (erroneously) installed does not like this one bit and demands mysql instead to be installed.

`npm show sequelize@* version` reveals that there are no v4 packages on npm. So I suggest removing the indication that v4 docs are for the "stable" branch until this gets changed.

**Comment by snewell92** [comment]
FYI, [another issue pointed out how to install the latest version](https://github.com/sequelize/sequelize/issues/7595#issuecomment-301017934).
