### ISSUE TITLE
Ground for sql-injection in "order" parameter for find.. funcitons. Suggestion to some restriction.

### ISSUE THREAD

**Issue by rusekr** [sequelize/sequelize#7711]
Hello!
Using Sequelize 3.30.2. Mysql 5.6.

We make some REST web interface for findAll functions and found that possibility to set "order" parameter simple way like:

findAll({
order: 'id desc'
})
makes possible to launch sql injection like so (generated with sqlmap):

findAll({
order: "1 AND (SELECT 2*(IF((SELECT * FROM (SELECT CONCAT(0x716b6a6271,(SELECT (ELT(4005=4005,1))),0x7170786271,0x78))s), 8446744073709551610, 8446744073709551610)))"
})

We currently locked that "order" interface in our engine to allow only :

order [['id', 'desc']] 

format.

All other sequelize interfaces seem well escaped (without using "literal" like functions for passing raw data).

There fore suggestion to disable simple unescaped format (order: 'id desc') in order clause in future versions (allowing breaking of back compatibility).

**Comment by sushantdhiman** [comment]
Thanks for brining this up, this has already been resolved in `v4` by https://github.com/sequelize/sequelize/pull/7160
