### ISSUE TITLE
Many-to-Many through not working

### ISSUE THREAD

**Issue by ahmed-anas** [sequelize/sequelize#7716]
Many-to-many association `through` is not populating additional fields. Code sample taken directly from docs: http://docs.sequelizejs.com/manual/tutorial/associations.html
## What you are doing?

```js

var Sequelize = require('sequelize');
var sequelize = new Sequelize('seqt', 'root', '', {
    host: 'localhost',
    dialect: 'mysql',

    pool: {
        max: 10,
        min: 0,
        idle: 10000
    },

});
const User = sequelize.define('user', {})
const Project = sequelize.define('project', {})
const UserProjects = sequelize.define('userProjects', {
    status: Sequelize.STRING
})

User.belongsToMany(Project, { through: UserProjects })
Project.belongsToMany(User, { through: UserProjects })

sequelize.sync().then(v => {

    var user, project;
    User.create({}).then(_user => {
        user = _user;

        Project.create({}).then(_project => {
            project = _project;
            // project.addUser(user, { through: { status: 'started' } })
            user.addProject(project, { through: { status: 'started' } });


        })
    })

})
```

## What do you expect to happen?
The created association should have the status field populated

## What is actually happening?
The status field has null

Executing (default): INSERT INTO `users` (`id`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'2017-06-01 21:55:36','2017-06-01 21:55:36');
Executing (default): INSERT INTO `projects` (`id`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'2017-06-01 21:55:36','2017-06-01 21:55:36');
Executing (default): SELECT `status`, `createdAt`, `updatedAt`, `userId`, `projectId` FROM `userProjects` AS `userProjects` WHERE `userProjects`.`userId` = 2 AND `userProjects`.`projectId` IN (2);
Executing (default): INSERT INTO `userProjects` (`userId`,`projectId`,`createdAt`,`updatedAt`) VALUES (2,2,'2017-06-01 21:55:36','2017-06-01 21:55:36');

**Comment by sushantdhiman** [comment]
You are referring to incorrect documentation i.e. v4, for current `master` which is not stable.

As you are using `v3` which is current stable, you should refer to https://sequelize.readthedocs.io/en/v3/ docs.

```js
user.addProject(project, { through: { status: 'started' } }); // Will work in v4

user.addProject(project, { status: 'started' }); // Will work in v3
```
