### ISSUE TITLE
Get object inside tree 1 to many relationship

### ISSUE THREAD

**Issue by FilipeCosta** [sequelize/sequelize#7719]
I couldn't get a response for the eager loading reverse side, because maybe it doesn't make sense.

I have two models: User and Foto.

Each user can take a lot of fotos, and each foto is associated to 1 User.

So for that i have a foreign key in the fotos side that identifies the user that took it.

Now in my client i need to get all fotos, and the specific id and name for the user, so i need to querie all fotos and get the user inside the foto:

at the moment with eager loading i can get something like this:

```
  {
    "id": 1,
    "username": "afcosta5",
    "email": "filipecosta_10@hotmail.com",
    "typeOfUser": 2,
    "country": null,
    "birthDate": null,
    "reports": 0,
    "points": 0,
    "numberFotos": 0,
    "createdAt": "2017-06-01T16:52:31.330Z",
    "updatedAt": "2017-06-01T16:52:31.330Z",
    "Foto": [
      {
        "id": 1,
        "reports": 0,
        "image": "images/Aceras_anthropophorum/r1ARV90bb1-1.jpg",
        "date": null,
        "lat": "22.89999833333333",
        "lon": "-55.2",
        "altitude": null,
        "userId": 1,
        "plantId": 1,
        "createdAt": "2017-06-02T07:33:41.986Z",
        "updatedAt": "2017-06-02T07:33:41.986Z"
      }
    ]
  },
  {
    "id": 2,
    "username": "afcosta1",
    "email": "filipecostaa_10@hotmail.com",
    "typeOfUser": 2,
    "country": null,
    "birthDate": null,
    "reports": 0,
    "points": 0,
    "numberFotos": 0,
    "createdAt": "2017-06-01T16:52:42.843Z",
    "updatedAt": "2017-06-01T16:52:42.843Z",
    "Foto": []
  },
  {
    "id": 3,
    "username": "afcosta3",
    "email": "filipecosata_10@hotmail.com",
    "typeOfUser": 3,
    "country": null,
    "birthDate": null,
    "reports": 0,
    "points": 0,
    "numberFotos": 0,
    "createdAt": "2017-06-01T16:54:12.622Z",
    "updatedAt": "2017-06-01T16:54:12.622Z",
    "Foto": []
  }
]
```
but i actually need to get All fotos, and then the user inside the foto

i can query for a specific user inside the Foto, but how can i get him inside the foto?

**My User model**
`"use strict";
var sequelize = require('./index');
var bcrypt = require('bcrypt-nodejs');
var Foto = require('./Foto');

module.exports = function (sequelize, DataTypes) {
  var User = sequelize.define("User", {
    username: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isUnique: function (value, next) {
          var self = this;
          User.find({ where: { username: value } })
            .then(function (user) {
              // reject if a different user wants to use the same username
              if (user && self.id !== user.id) {
                return next('username already in use!');
              }
              return next();
            })
            .catch(function (err) {
              return next(err);
            });
        }
      }
    },

    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isUnique: function (value, next) {
          var self = this;
          User.find({ where: { email: value } })
            .then(function (user) {
              // reject if a different user wants to use the same email
              if (user && self.id !== user.id) {
                return next('Email already in use!');
              }
              return next();
            })
            .catch(function (err) {
              return next(err);
            });
        }
      }
    },

    typeOfUser: {
      type: DataTypes.INTEGER,
      allowNull:false,
      defaultValue:2
    },

    country: {
      type: DataTypes.STRING,
      allowNull:true,
      defaultValue:null
    },

    birthDate:{
      type: DataTypes.DATEONLY,
      allowNull:true,
      defaultValue:null
    },

    reports: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },

    points: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },

    password: {
      type: DataTypes.STRING,
      allowNull:false
    },
    
    numberFotos: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    }
  }, {
      classMethods: {
        generateHash: function (password) {
          return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
        },
        associate: function(models){
          User.hasMany(models.Foto,{foreignKey: "userId", as: "Foto"});
        }

      },
      instanceMethods: {
        validPassword: function (password) {
          return bcrypt.compareSync(password, this.password);
        }
      }

    });

  return User;
}
`

**PHOTO**

```
"use strict";
var sequelize = require('./index');
var bcrypt = require('bcrypt-nodejs');
var User = require('./User');


module.exports = function (sequelize, DataTypes) {
  var Foto = sequelize.define("Foto", {
    reports: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    image: {
      type: DataTypes.STRING,
      allowNull: false
    },
    date: {
      type: DataTypes.DATE,
      allowNull: true
    },
    lat: {
      type: DataTypes.STRING,
      allowNull: true
    },
    lon: {
      type: DataTypes.STRING,
      allowNull: true
    },
    altitude: {
      type: DataTypes.STRING,
      allowNull: true
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    plantId: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
  },
    {
      associate: function (models) {
        Foto.hasOne(models.User, {as:'User'});
      }
    }
  );


**in my route:**

 allPictures: function (req, res) {
        Foto.findAll({include: [{ model: User, as: "User" }]})
        .then(function (fotos) {
            res.send(fotos);
        })
    },

this fails because it doesn't fins any association :/


```

**Comment by harshithkashyap** [comment]
Kindly format your code and follow the issue template​.
Your association should be 
```
Foto.belongsTo(models.User)
```

**Comment by FilipeCosta** [comment]
updated, i changed it to belongsTo but the error is the same, i can include a model just in 1 direction the other not, so if i want all the Users and the fotos related to them i can get them, if i want all the fotos and the users inside i can't dunno why.

**Comment by FilipeCosta** [comment]
I solve the issue, the problem can be related to two things that we ignore
and always think that it is just related to the association by itself.

The Index.js mode file that specify the assocations:

"use strict";

var fs = require("fs");
var path = require("path");
var Sequelize = require("sequelize");
var env = process.env.NODE_ENV || "development";
var config = require(path.join(__dirname, '..', 'config', 'config.json'))[
env];
if (process.env.DATABASE_URL) {
var sequelize = new Sequelize(process.env.DATABASE_URL,config);
} else {
var sequelize = new Sequelize(config.database, config.username, config.
password, config);
}
var db = {};

fs
.readdirSync(__dirname)
.filter(function(file) {
return (file.indexOf(".") !== 0) && (file !== "index.js");
})
.forEach(function(file) {
var model = sequelize.import(path.join(__dirname, file));
db[model.name] = model;
});

Object.keys(db).forEach(function(modelName) {
if ("associate" in db[modelName]) {
db[modelName].associate(db);
}
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;


or (My case) the missing classMethod, in one side i had this:

associate: function (models) {
console.log("HITFOTO");
Foto.belongsTo(models.User, { as: "user" });
}


but not this:

{
classMethods: {
associate: function (models) {
console.log("HITFOTO");
Foto.belongsTo(models.User, { as: "user" });
}

}


as sugested from some cool guys on slack, check if it hits the associate
method!









2017-06-02 14:46 GMT+01:00 Harshith Kashyap <notifications@github.com>:

**Comment by harshithkashyap** [comment]
What is the result you are getting?
