### ISSUE TITLE
Is there a problem with `transactions` and `async/await`?

### ISSUE THREAD

**Issue by jlpellicer** [sequelize/sequelize#7720]
## What you are doing?
I am using `async/await` and I can't get a `transaction` to rollback if there's an error.

```js
async changeOrderStatus (order_id, state) {
		const t = await db1.sequelize.transaction();
		try {
			//<snip>
                        const destroy_result = await db1.models.order_status.destroy({where: {order_status_id: old_status.order_status.order_status_id}}, {transaction: t});
                        if (!destroy_result) {
                        	throw new Error('COULD_NOT_REMOVE_STATUS');
                        }
                        const status_result = await db1.models.order_status.create(new_status, {transaction: t});
                        if (!status_result) {
                        	throw new Error('COULD_NOT_CHANGE_STATUS');
                        }
                        await t.commit();
		} catch(error) {
                        await t.rollback();
			return error;
		}
```

## What do you expect to happen?
If `status_result` fails, I expect the `transaction` to rollback and the attempted `destroy_status` not be destroyed.

## What is actually happening?
Doesn't rollback, the deleted status remains deleted.

postgres 9.6, sequelize: 3.30.4, node: 8.0.0

What am I missing? thanks!

**Comment by jlpellicer** [comment]
Turning on debugging, I can see this:
`Executing (bbbc8ed6-a72f-4136-a07f-b720ca1f1398): START TRANSACTION;`

`Executing (bbbc8ed6-a72f-4136-a07f-b720ca1f1398): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;`

Then I see this when creating:
`Executing (bbbc8ed6-a72f-4136-a07f-b720ca1f1398): INSERT INTO "order_status"...`

But the delete (paranoid) doesn't show the transaction:
`Executing (default): UPDATE "order_status" SET "deleted_date"... `

**Comment by PierBover** [comment]
The notation is wrong:

`models.order_status.destroy({where: {order_status_id: old_status.order_status.order_status_id}}, {transaction: t})`

If should be:

`models.order_status.destroy({where: {order_status_id: old_status.order_status.order_status_id},transaction: t})`
