### ISSUE TITLE
Set a belongsTo association as primary key

### ISSUE THREAD

**Issue by reinert** [sequelize/sequelize#7721]
I would like to do something like: `Child.belongsTo(Parent, { primaryKey: true, onDelete: 'CASCADE' })` but sequelize doesn't use the `primaryKey` option. My goal is to have a double PK in child (`parentId` and `id`).

**Comment by hesamd** [comment]
@reinert shouldn't you use `foreignKey` instead, so you have an `id` as your child primary key and the foreingKey as your child key to the parent. Why are you trying to have primary keys while one of them is actually a foreign key to the parent?

**Comment by janmeier** [comment]
@hesamd Is correct
