### ISSUE TITLE
User w/ Tags database scheme

### ISSUE THREAD

**Issue by jacob-cross99** [sequelize/sequelize#7722]
I want Users in my database to have a list of tags. I'd like the Tags table to be two columns:
User ID (userId)
Tag Name (tag)

I currently have tried by making User.hasMany(Tags, { primaryKey: true, foreginKey: 'userId' });
But I end up with an 'ID' column on top of all of the other columns. I'd like for UserID/TagName to be a unique correlation (meaning there can only be once instance of a User and tag)

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
