### ISSUE TITLE
Assigning a model value to null works, but model.update a value to null does not

### ISSUE THREAD

**Issue by sidewalksalsa** [sequelize/sequelize#7726]
I am using Sequelize 3.30.4.

I have a scenario where after I find a specific user, I want to update one of the user's fields to NULL. What I am seeing is that if I assign the field to null, the field value gets set to NULL, however, if I use model.update and pass the key, value as `value: null`, the value is set to an empty string. **Why?**

Note: `user` below is the user object returned by User.find(...).

**Works**
_The value in the DB actually gets set to NULL_
```js
user.confirmed_token = null;
user.save(['confirmed_token']);
```

**Does not work**
_The value in the DB gets set to an empty string `''`_
```js
user.update({
  confirmed_token: null,
}, { fields: ['confirmed_token'] }).then((updatedUser) => {...});
```

**Comment by janmeier** [comment]
I tried, but couldn't replicate this

```js
const User = sequelize.define('user', {
  confirmed_token: Sequelize.STRING
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => {
    return User.create({
      confirmed_token: 'foobar'
    });
  })
  .then((user) => {
    return user.update({
      confirmed_token: null
    }, { fields: ['confirmed_token']})
  })
  .then((results) => {
    console.log(results.toJSON());
  })
  .then(console.log)
  .finally(() => {
    sequelize.close();
  });
```
```sql
INSERT INTO "users" ("id","confirmed_token") VALUES (DEFAULT,'foobar') RETURNING *;
UPDATE "users" SET "confirmed_token"=NULL WHERE "id" = 1
{ id: 1, confirmed_token: null }
```
