### ISSUE TITLE
Migrations: queryInterface.[add|remove|show]Constraint(...) are undefined

### ISSUE THREAD

**Issue by david-bojnansky** [sequelize/sequelize#7731]
Methods addConstraint, removeConstraint and showConstraint are _undefined_ on _QueryInterface_ class. Currently using 4.0.0-2, previously 3.30.4 and on both the same result. `http://docs.sequelizejs.com/manual/tutorial/migrations.html#addconstraint-tablename-attributes-options-`

**Comment by sushantdhiman** [comment]
Yes because they arent included current release. They will be included in v4 stable release.

If you wish to use them you can use master for now
