### ISSUE TITLE
Can't access models's instance custom property 

### ISSUE THREAD

**Issue by altjsus** [sequelize/sequelize#7733]
I am new to nodejs and sequelize, so probably it's not a bug, but I think it's an unexpected behavior.

## What am I doing?
I have a `product` and a `category` models. So, that:
`category.hasMany(product, {as: 'product'});`

Here is function that appends to product object `.category` property.
```js
	getFullProductInfo: async function(product){
		try{
			product.category = await models.category.findById(product.categoryId);
...[more code]..
		}catch (err){
			console.log(err);
		}
		return Promise.resolve(product);
	},

```
And here to `res.send(..)` send all products
```js
	app.get('/products', async function (req, res){
		var products = await models.product.findAll();
		var productsFullInfo = await Promise.all(products.map(functions.getFullProductInfo));
		res.send(productsFullInfo);
	});

```

output: 
```json
[{
"id": 1,
"name": "Лось",
"waste": 1,
"createdAt": "2017-06-05T12:41:31.537Z",
"updatedAt": "2017-06-05T12:41:31.560Z",
"categoryId": 1
}, 
...
```
Same output with `console.log(...)` If I change `res.send(...)` to `res.send(products[0].category)`,  I get the real product's category: 
```json
{
"id": 1,
"name": "Продукты",
"createdAt": "2017-06-05T12:41:31.516Z",
"updatedAt": "2017-06-05T12:41:31.516Z",
"parentId": null
}
``` 
If I use npm lib `js-object-pretty-print`, I get really huge serialized model's instance as with at lot of properties. Bad idea to use it in application and pass to Angular, the point I want to achieve for now.

## What I expect to happen?
I expect to get `product` object with `.category` property.

__Dialect:__ postgres
__Database version:__ 9.6-1
__Sequelize version:__ 3.30.4

**Comment by felixfbecker** [comment]
Sequelize overrides `.toJSON()` to only include attributes defined on the model. You probably want to use the `include` option.

**Comment by altjsus** [comment]
Thanks for the answer. But how can I append property to sequelize instance object?

**Comment by felixfbecker** [comment]
You can, but you will have to override `toJSON()` then to consider it

**Comment by altjsus** [comment]
Thank you again for a quick answer
