### ISSUE TITLE
belongsToMany helper methods not created

### ISSUE THREAD

**Issue by PierBover** [sequelize/sequelize#7738]
## What you are doing?
I'm trying to create a many-to-many relationship from elements in the same table using a junction table.

```js
const Product = sequelize.define('product',
{
	id: {
		type: Sequelize.UUID,
		defaultValue: Sequelize.UUIDV4,
		primaryKey: true,
		allowNull: false
	},
	name: {
		type: Sequelize.STRING(120),
		unique: true,
		allowNull: false,
	},
});

const SubProduct = sequelize.define('subproduct',
{
	productId:{
		type: Sequelize.UUID,
		allowNull: false
	},
	parentProductId:{
		type: Sequelize.UUID,
		allowNull: false
	}
}
);

Product.belongsToMany(Product, {
	through: SubProduct,
	as:'subproducts',
	foreignKey: 'productId',
	otherKey: 'parentProductId'
});
```

This creates the tables ok. The problem comes when I want to create data in the relationship.

According [to the v3 docs](https://sequelize.readthedocs.io/en/v3/docs/associations/#belongs-to-many-associations) using `belongsToMany` should create these methods:

> This will add methods getUsers, setUsers, addUser,addUsers to Project, and getProjects,  setProjects, addProject, and addProjects to User.

I've tried all combinations (`addProduct`,`setProduct`,`addProducts`,`setProducts`) and I always get the error `addProducts is not a function`.

```js
const result = await Product.find({where:{id:'75aa889a-7812-48e2-9120-06c030dd558d'}});
result.addProducts(['faccdcd0-672b-44b6-beb3-fa5b73a734df','c3084522-b2d3-4e57-9f12-c756dd3d9fa1']);
```

## What do you expect to happen?
I want to create a relationship in a junction table.

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 3.30.4

**Comment by harshithkashyap** [comment]
Since you have aliased your association, IIRC it should be `addSubproducts`. Could you give to a try?

**Comment by PierBover** [comment]
Thanks @harshithkashyap that was it.

Could you give me a hand in how I would query this? For example how to find if a Product has SubProducts?

**Comment by harshithkashyap** [comment]
You should pass the alias `as` key.
```js
const result = await Product.find({
	where:{
		id:'75aa889a-7812-48e2-9120-06c030dd558d'
	},
	include: [{
               model: Product,
               as: 'subproducts'
        }]
});
```
