### ISSUE TITLE
Association getters not created.

### ISSUE THREAD

**Issue by sapostolou** [sequelize/sequelize#7739]
## What you are doing?
I noticed that the association setters are not created when belongsTo is stated.

```js
// Dmodel.js
var Table = sequelize.define('D', {
    // some attributes
    mID:{
        // stuff
    },
    // some more attributes
}, {
    classMethods: {
        associate: function (models) {
            Table.belongsTo(models.U, {as:'M', foreignKey: 'mID' });
        }
    }
});

// Droute.js
var newD;
models.D.create({}})
    .then(function (d) {
        newD = d;
        return models.U.create({}});
    })
    .then((newU) => {
        // none of these worked.
        return newD.addU(newU);
        // return newD.setU(newU);
        // return newD.addM(newU);
        // return newD.setM(newU);

    })
```

## What do you expect to happen?
I would expect the mID field to be set to the ID field of the newU instance

## What is actually happening?
I get the following error for all 4 statements.

_Output_
`TypeError: newD.addU is not a function`

__Dialect:__ mysql
__Database version:__ XXX
__Sequelize version:__ 4.0.0-2

**Comment by knoxcard** [comment]
Where is your function addU? 

```
addU: function() {

}
```

**Comment by sapostolou** [comment]
addU is the function which to my knowledge should be created when associating the two  models through belongsTo. 

[Here](http://docs.sequelizejs.com/class/lib/associations/base.js~Association.html) you car read the following:

> There are several ways to update and add new associations. Continuing with our example of users and pictures:

```
user.addPicture(p) // Add a single picture
user.setPictures([p1, p2]) // Associate user with ONLY these two picture, all other associations will be deleted
user.addPictures([p1, p2]) // Associate user with these two pictures, but don't touch any current associations
```

**Comment by sapostolou** [comment]
According to [line 70](https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to.js#L70) of lib/associations/belongs-to.js, a setter with the name setM should have been created.

**Comment by knoxcard** [comment]
Oh I see the problem now, I am spending all day upgrading my platform, loads of fun!

```
// Dmodel.js
var Table = sequelize.define('D', {
    // some attributes
    mID:{
        // stuff
    },
    // some more attributes
})

Table.associate = function (models) {
    Table.belongsTo(models.U, {as:'M', foreignKey: 'mID' });
}

```
classMethods are now deprecatd in 4.0.0

Read more here:
http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

**Comment by sapostolou** [comment]
Thanks a lot. I never saw that page before.
