### ISSUE TITLE
Migration configuration should be based on node-config

### ISSUE THREAD

**Issue by denisw** [sequelize/sequelize#774]
The Sequelize migrations system uses a config file ´config/config,json` for database credentails, which is fine by itself, but doesn't mesh well with other configuration libraries such as the quite popular [node-config](https://github.com/lorenwest/node-config). If I use this together with Sequelize, I suddenly have two types of configuration files with different structures (node-config uses one file per configuration environment, while in Sequelize the environments are sections in the same file).

It would be nice if Sequelize would simply use node-config for configuration, at least optionally when it's available.

**Comment by janmeier** [comment]
This issue belongs in https://github.com/sequelize/umzug now
