### ISSUE TITLE
Instance.Model is no longer available on 4.X

### ISSUE THREAD

**Issue by yonjah** [sequelize/sequelize#7744]
It seem like the `Model` property on the created instance is no longer defined -
```javascript
const User = db.define('user', { name: { type: Sequelize.STRING }});
const inst = new User() // Or using User.build()
console.log(inst.Model)  // will be undefined
```

Since the changes made to 4.x  `Model` can be still accessed from `inst.constructor` but it feels a bit brittle and hacky doing it that way.

I couldn't find any info if this change was done intentional and it is not mentioned in the changelog or  breaking changes.
If this is intentional, documentation and changelog should be updated and alternative/best practice for accessing the Instance Model if exist should be mentioned

**Comment by felixfbecker** [comment]
`instance.constructor` is the intended per ECMAScript standard way of accessing the class of an object, just like `Model.prototype` is the standard way of accessing the instance type. I will update the migration guide.

Context:

https://github.com/sequelize/sequelize/pull/5877
> The property instance.Model is now exactly the same as instance.constructor (a reference to the class that created the object)

**Comment by yonjah** [comment]
@felixfbecker I know `instance.constructor` is the ES way for accessing the constructor but I don't think this should be reconsidered from the following reasons -
- It is not really future proof. Using it you are relying on the spec not to change (small chance for that but an option) and for the current implementation not to use any other way to create the instance (higher chance for this to change) So if we rely on the constructor as the way for accessing the Model from the instance the implementation is locked and cannot be changed without major BC. where offering backward compatibility by accessing `Instance.Model` is probably an easy solution with minor side effects that will probably always be made available (probably one line change to current code)

- Using `.constructor` is asking the user to be aware of internal implementation.  This is probably not specific for this issue and not too major (since most user will need to know Model is class that create Instances) but when using `Model.build` or `Instance.Model` does not require any understanding about the internal implementation `new Model()` and `Instance.constructor` do ( and as with previous point I would argue using `build` is something that will always be available unlike calling `new Model()` which lock you to very specific implementation)

- On a large enough code base this is probably a painful change the same way `.build` is still available on the model even thought ECMA spec define a way to initiate objects from a class

So I would say the internal implementation change is great and very useful, but I would not change the actual API unless there is some major benefit for changing it

**Comment by felixfbecker** [comment]
Here are the reasons for the decision:
- The notion that Models are classes and instances are instances is here to stay, and was discussed in-depth publicly on several issues
- Overall, this is much simpler to understand for new users, because terms like "instance" are not overloaded with different semantics
- There is nothing internal about Models being classes, this is the future way to define models
- `object.constructor` won't go away, just like `function.prototype` will never go away. They are fundamentals of the JavaScript object model
- A different property than `.constructor` to access the constructor just implies that they are not the same and causes confusion
- We shouldn't reinvent the wheel to work around classes and instances, but embrace what's there in the language
- If `.Model` is kept, `.Instance` should be kept too
- `.Instance` would be a self-reference to the model, which is a heavy code smell and even more confusing
- There are already 100 aliases and ways in Sequelize to do the same thing. We need to reduce complexity
- If `.Model` and `.Instance` are properties, they use RAM. If they are getters, they use CPU
- `Model.build()` doesn't have the same confusion points
- I've done the change myself on a very large codebase, it is mostly just a search+replace

In my opinion they outweigh the cons

**Comment by yonjah** [comment]
> The notion that Models are classes and instances are instances is here to stay, and was discussed in-depth publicly on several issues

And that was a great decision which highly simplified things. But it doesn't imply `.Model` should not be available on the instance

> A different property than .constructor to access the constructor just implies that they are not the same and causes confusion

No it just implies there is a Sequlize supported documented and explicit way to access the Model though technically exactly the same all this meaning is missing when using `.constructor`.

> If .Model is kept, .Instance should be kept too

I don't see why that should be the case.

> .Instance would be a self-reference to the model, which is a heavy code smell and even more confusing

Exactly why there is a good reason not to do that. Not as `Instance.Model` which is much clearer than `Instance.constructor`

> If .Model and .Instance are properties, they use RAM. If they are getters, they use CPU

I don't see how a pointer to an existing method is going to cost you in so much RAM but if this is an issue I'm sure there is a way to put in on the prototype and not on every instance.
If you set it as a getter I would say the CPU cycles are negligible and even if some users don't want to use it they are welcome to access what ever underlining API they want (taking the risk it might change but as you mentioned that is never going to happened) but not having it forces everybody to take this risk.

> Model.build() doesn't have the same confusion points

Why not ? I don't see how they differ also I don't see how `new Sequelize().Sequelize` is, and I'm sure there are many more examples where it made a lot of sense to use an explicit API instead of implicit one 

Any way this is up to you to decide which API you want to support but removing `.Model` just means there is no proper way accessing the model from an Instance. And this is a good decision if you don't think it should be available that way. But I would consider accessing `.constructor` equal to accessing any other private property on the Model and not something that I'd be keen on doing on any long term code

**Comment by yonjah** [comment]
You are coming back to a point that  is just irrelevant to this issue. 

Should we expect this line - https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1134 and many of the following to be removed in 4.0.1 since they are wrongly leftover of pointers which are available from the `constructor` ?
