### ISSUE TITLE
Mssing changelog for constructor Utils methods on 4.x

### ISSUE THREAD

**Issue by yonjah** [sequelize/sequelize#7745]
#6059 changed many of the Utils method to be proper constructors and changed their name to be uppercased (fn -> Fn, where -> Where, etc)
Maybe some other changes I missed since this is a major redactor.

This changes should be mentioned in the changelog and BC

**Comment by janmeier** [comment]
They are still available on the sequelize object https://github.com/sequelize/sequelize/blob/4b10b002cfd89aa3f9e1065dbaf2c7daa85edaa5/lib/sequelize.js#L788 http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#static-method-fn

The utils object is not meant for public use

**Comment by yonjah** [comment]
> The utils object is not meant for public use

Than it shouldn't be exposed and documented at v3
And removing it from public use should still be documented as breaking change at v4.

**Comment by janmeier** [comment]
I see what you mean, but I don't think this documentation entry really invites you to dive deep into the object :P https://sequelize.readthedocs.io/en/v3/api/sequelize/#utils.

Migration guide updated

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/commit/bb42049d5e763032d73d5c5ea9e52c459b9ba346
