### ISSUE TITLE
Tag.init is not a function

### ISSUE THREAD

**Issue by kollors** [sequelize/sequelize#7749]
## What you are doing?

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize(`mysql://${username}:${password}@localhost:3306/${database}`);
class Tag extends Sequelize.Model {}
Tag.init({title: Sequelize.STRING}, {sequelize});
```

## What do you expect to happen?
I wanted to register model Tag in Sequelize and create table tag

## What is actually happening?
TypeError: Tag.init is not a function

__Dialect:__ mysql
__Database version:__ 2.13.0
__Sequelize version:__ 4.0.0

**Comment by knoxcard** [comment]
classMethods are now deprecated in 4.0.0

Read more here:
http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

Need to set up your function like this

```
Tag.init = function (title_obj, sequelize_obj) {
    ...
}
```

**Comment by kollors** [comment]
So, I should write something like that?
```js
Tag.init = function (title_obj, sequelize_obj) {
    sequelize_obj.define('Tag', title_obj);
}
```

**Comment by felixfbecker** [comment]
No, `Tag.init()` should work. Are you using a transpiler?

**Comment by kollors** [comment]
No, error was solved after I fully delete the node_modules, apparently some dependencies were not updated to the latest version

**Comment by knoxcard** [comment]
Use this tool to update npm, it's the best thing out there to prevent these sort of issues moving forward...

npm install npm-update-all -g
