### ISSUE TITLE
non-english characters shown as "????" after migrating to v4

### ISSUE THREAD

**Issue by everthis** [sequelize/sequelize#7750]
non-english characters shown as "????" after migrating to v4.
Those characters in database are alright, but shown as question marks in the output of   `sequelize.Model.query`

__Dialect: mysql
__Database version: mysql 5.1.73
__Sequelize version: 4.0.0

**Comment by sushantdhiman** [comment]
Care to provide atleast some sample code so we can check the issue

**Comment by knoxcard** [comment]
Try this thread...
https://github.com/sequelize/sequelize/issues/395#issuecomment-29132224

**Comment by knoxcard** [comment]
Run this mysql query in your console program
`SHOW VARIABLES LIKE 'character_set_%'
