### ISSUE TITLE
calling `.close` on Sequelize db instance does not properly close the connection socket

### ISSUE THREAD

**Issue by yonjah** [sequelize/sequelize#7751]
on v4.0.0 Sequlize is not properly closing the socket and process will not exit cleanly -
demo code -
```javascript
const Sequelize = require('sequelize');
const db  = new Sequelize('test', 'root', null, {dialect: 'mysql'});

db.query('SHOW TABLES')
	.then(() => db.close());
```

running this code process will not exit running it with `wtfnode` shows socket is still open after calling close

**Comment by nrschultz** [comment]
I saw this as well, I think it has to do with the fact that the generic-pool library was upgraded and the drain call went from taking a callback to returning a promise.  I messed around in my local environment and I think I got it working by changing the callback to a `.then`.  I'll file a PR and hopefully that fixes the problem

**Comment by galki** [comment]
doesnt work on windows and i have to use `process.exit()` instead of `db.close()`

**error:** `Unhandled rejection Error: pool is draining and cannot accept work`

**sequelize version:** 4.33.4
