### ISSUE TITLE
Multiple inner joins on the same table

### ISSUE THREAD

**Issue by Nilos** [sequelize/sequelize#7754]
## What you are doing?
I am trying to get an inner join on the same table two times.
I have got two tables, a chat and a receiver. Every chat has many receivers. I want to have every chat which has the receivers 1 and 2. My solution would be:

```js
Chat.findAll({
  attributes: ["id"],
  include: [{
    attributes: [],
    association: Chat.Receiver,
    required: true,
    where: { userID: 1 }
  }, {
    attributes: [],
    association: Chat.Receiver,
    required: true,
    where: { userID: 2 }
  }]
})
```

## What do you expect to happen?
I would like to get a result set with only chats where user 1 and user 2 are among the receivers

## What is actually happening?
```sql
SELECT "Chat"."id" FROM "Chats" AS "Chat" INNER JOIN "Receivers" AS "chat" ON "chat"."id" = "receiver"."ChatId" AND "receiver"."userID" = 1 INNER JOIN "Receivers" AS "receiver" ON "chat"."id" = "receiver"."ChatId" AND "receiver"."userID" = 2;
````
Error: table name "receiver" specified more than once

Thanks in advance for any help!

__Dialect:__ postgres
__Database version:__ psql (PostgreSQL) 9.6.2
__Sequelize version:__ 3.30.4

**Comment by mightyplow** [comment]
I have the same problem and don't know how to solve that. Any ideas?

**Comment by overflowz** [comment]
bump, same problem.

**Comment by Nilos** [comment]
bump, also still got the problem. created a custom query as a workaround

**Comment by michaelunltd** [comment]
I got a similar case. A `Hotel` and `Amenity` many to many relationship, I need to filter Hotels by `Amenity`.
 
Before:
```
  Hotel
    .findAll({
      include: [{
        model: Amenity,
        as: 'amenities',
        where: {
          id: [1, 2, 3]
        }
      }]
    })
    .then(hotels => {
      console.log(JSON.stringify(hotels));
    })
```
Result: It does work but I return a Hotel with at least on of the given id. It should return only hotels which has all three provided ids.

After:
```
  Hotel
    .findAll({
      include: [{
        model: Amenity,
        as: 'amenities',
        where: sequelize.literal(`ARRAY[${amenityIds}] <@ ARRAY(SELECT "amenityId" FROM "HotelAmenity" WHERE "hotelId" = "Hotel"."id")`)
      }]
    })
    .then(hotels => {
      console.log(JSON.stringify(hotels));
    })
```
Result: This works perfectly.

Got it from: @janmeier

**Comment by michaelunltd** [comment]
@Nilos May I know your work around?

**Comment by overflowz** [comment]
@michaelunltd workaround is to write raw query instead, I did the same thing as well.

**Comment by mradkov** [comment]
Is this resolved, or the workarount is still to write raw queries  ?

**Comment by me21** [comment]
@sushantdhiman do you have any new information?

**Comment by mradkov** [comment]
As a workaround I've created a raw union query.

**Comment by ericmaier** [comment]
Here's my solution

`const filters = [];
const mapToClause = (list) => _.map(list);
if (!_.isEmpty(filters)) {
  const qry = sequelize.dialect.QueryGenerator.selectQuery(intersect.model.name, {
    attributes: ['fkId'],
    where: { $or: mapToClause(filters) },
    group: 'fkId',
    having: sequelize.where(sequelize.fn('count', sequelize.col(format('%s.fkId', intersect.model.name))), {
      $eq: filters.length,
    }),
  }).slice(0, -1);
  intersect.where = { fkId: { $in: sequelize.literal(format('(%s)', qry)) } }
}`

**Comment by abhi5658** [comment]
You can do multiple inner joins with same table by adding extra same association with that model but with a different alias that is `as: 'alias1'` , `as: 'alias2'` ,... - all this existing with the same model + same type  of association.

Now you are left to include associated model multiple times all with different alias so it does not gets overridden.
E.g. for OP's models
Associations (Duplicating for as many needed)
```js
Chat.hasMany(Receiver, {
    // foreignKey: ...
    as: 'chatReceiver',
});
Chat.hasMany(Receiver, {
    // foreignKey: ...
    as: 'chatReceiver2',
});
```

Now you can use them in query:
```js
Chat.findAll({
    attributes: ["id"],
    include: [{
        required: true,
        model: Receiver,
        as: 'chatReceiver', // Alias 1
        attributes: [],
        where: { userID: 1 }, // condition 1
    }, {
        required: true,
        model: Receiver,
        as: 'chatReceiver2', // Alias 2
        attributes: [],
        where: { userID: 2 }, // condition 2 as needed
    }]
});
```

**Comment by bugrevealingbme** [comment]
"SequelizeEagerLoadingError: user is associated to tirini using an alias. You've included an alias (users_2), but it does not match the alias(es) defined in your association (users)."
