### ISSUE TITLE
No warnings when model named "Model" is defined

### ISSUE THREAD

**Issue by dmlukichev** [sequelize/sequelize#7755]
## What you are doing?

```js
/**
 *  Definition
 */
const Model = sequelize.define('Model', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    name: Sequelize.STRING(128),
});

const SparePart = sequelize.define('SparePart', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    model_id: { 
        type: Sequelize.INTEGER, 
        allowNull: false, 
    },
    sku: Sequelize.STRING(128),
}, {
    classMethods: {
        associate() {
            SparePart.belongsTo(Model);
        }
    }
});
```

```js
/**
 *  Usage
 */
const sku = 'abc';
const spart = SparePart.find({
    where: { sku },
    include: [ Model ]
}) ;

await spart.update({ sku: 'some new sku' });
```

## What do you expect to happen?
My first expectation was `spart` to be saved properly.
But since inside 'save()' method Model means sequelize's Model, I get an error. 
So 'Model' should be a reserved word.
I think it would be nice to completely disallow defining model "Model". Or at least to warn a developer when he does this so he would be very carefull.

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Database version:__ XXX
__Sequelize version:__ 3

**Comment by felixfbecker** [comment]
What do you mean with "inside 'save()' method Model means sequelize's Model"?

**Comment by dmlukichev** [comment]
In my example `spart` is not saved because sequelize throws error in the following lines:
https://github.com/sequelize/sequelize/blob/v3/lib/instance.js#L531-L534
