### ISSUE TITLE
about autoIncrement primaryKey ,use bulkCreate function, response id=null

### ISSUE THREAD

**Issue by yujintang** [sequelize/sequelize#7761]
## What you are doing?
about autoIncrement primaryKey ,use bulkCreate function, response id=null. but use create is right

__Dialect:__ mysql 
__Database version:__^2.13.0
__Sequelize version: __^3.30.4

**Comment by helloqhx** [comment]
u should query them from db again.

**Comment by janmeier** [comment]
As the documentation mentions, it is not possible to get the ids from mysql in the same query http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-bulkCreate
