### ISSUE TITLE
multiple setAssociation on model does not work with individual hooks

### ISSUE THREAD

**Issue by linpekka** [sequelize/sequelize#7764]
I have a model with an association. I use the setAssociations call on the model, and i include individualHooks: true in the options. The first time I set it, all seems to work well, but when I set a subset of the previous input, some of the data is lost. I know the setup below is incomplete, i am thinking I need to post something asap, and if I find time I can update later. I can also add that all seems to work as intended without individualHooks.
 
## What you are doing?

```js
// Actual association
Circle.belongsToMany(models.LibraryCategory, {through: models.CircleCategory, foreignKey: 'circle_id', targetKey: 'library_category_id'});

// Actual call, from instance function, only sets correct data if LibraryCategories is not set for the Circle
this.setLibraryCategories(categories, {transaction:t, individualHooks: true})
```

## What do you expect to happen?
I wanted the data included in categories to be reflected in postgres after the set

## What is actually happening?
The data included in categories that was already present in postgres was missing after the call, only the part of the data that was extended was reflected in postgres after the set

For the moment I am using the following workaround that seems to work
```js
          this.setLibraryCategories([], {transaction:t, individualHooks: true})
          .then(() => {
            return this.setLibraryCategories(categories, {transaction:t, individualHooks: true})
```

**Comment by amit034** [comment]
+1
