### ISSUE TITLE
Asynchronous 3rd-party Hydration of Model

### ISSUE THREAD

**Issue by tom2strobl** [sequelize/sequelize#7765]
Hi folks, we try to transition to `sequelize` from `bookshelf` and ran into a problem we seemingly can't find a solution for in the sequelize-world.

In the users-table of our database, we only store certain values and have a field called `uimId` that stores an id through which we have to get information like avatar, username and so on basically through an HTTP-request to a different server. In an ideal world whenever we want to retrieve a user model through any means (findOne, findAll and being included from other Models queries), we would hydrate the database-contents with the contents from this http-call. We actually have a caching layer to speed this up, but that's a different story.

### Idea 1: Virtuals
As far as I'm concerned virtuals can't be asynchronous, therefore HTTP requests not possible. Apart from that we'd want to fire just one request and then hydrate multiple fields and virtuals afaik would solely operate on a one-field level.

### Idea 2: Read-Hooks
Although we managed to hydrate `find` and `findAll` with the following approach, the hook unfortunately is not fired when the model is included in a different Models query. In any way the documentation is imho not existant when it comes to read hooks _(What should I fulfill the promise with actually?)_.

```javascript
hooks: {
  afterFind: function(result) { // beforeValidate / cb after options
    return new Promise((fulfill, reject) => {
      if (isArray(result)) {
        const uimIds = result.map(user => user.dataValues.uimID);
        UIM.getUsers(uimIds).then(newUserDataArray => {
          newUserDataArray.forEach((newUserData, index) => {
            // if we provided an not-existing uimID, then the data is not an object but the uimID as string
            if (isObject(newUserData)) {
              result[index].dataValues = assign(result[index].dataValues, newUserData);
            }
          });
          fulfill(null);
        });
      } else {
        UIM.getUser(result.uimID).then(newUserData => {
          if (isObject(newUserData)) {
            result.dataValues = assign(result.dataValues, newUserData);
          }
          fulfill(null);
        }).catch(reject);
      }
    });
  }
}
```

### Idea 3: Monkey Patching find

In `bookshelf` we monkey patched the `fetch()` and `fetchAll()` methods of the model which resulted in the expected behaviour, we used bookshelf for quite a while and knew what we were doing. I'm not sure if monkey patching is actually possible with sequelize (so that the model requested through an include is hydrated). Here's the fetch method as an example:

```javascript
fetch: function (fetchOptions, naked) {
  return new Promise((fulfill, reject) => {
    let dbData;
    // first get the regular data from the database
    bookshelf.Model.prototype.fetch.bind(this)(fetchOptions).then(data => {
      dbData = data;
      // now get the data from UIM
      if (naked !== true && data && data.attributes && data.attributes.uimID) {
        return UIM.getUser(data.attributes.uimID);
      } else {
        return Promise.resolve({});
      }
    }).then(newUserData => {
      // now merge the data if there was a user found
      if (dbData && dbData.attributes) {
        // if the uimID was not existing, then the user should not be hydrated, obviously
        if (_.isObject(newUserData)) {
          dbData.attributes = _.assign({}, dbData.attributes, newUserData);
        }
      }
      fulfill(dbData);
    }).catch(err => {
      reject(err);
    });
  });
},

```

I'm open to any ideas and inputs and if you guys say it's impossible then that's fine as well!

**Comment by felixfbecker** [comment]
First of all, I would recommend you to not begin every method with `return new Promise()`, but just return your promise chain.

Readhooks can return `Promise<void>`, they don't need to fulfill the promise with anything.

Sequelize Models are just ES6 classes. You are free to override any method you want, I would just recommend to honor Liskov's substitution principle.
I wouldn't call `.bind()` on every call though, just use `.call()`. Or just call `super.find()`.
