### ISSUE TITLE
Sequelize 4.0.0 no associations created

### ISSUE THREAD

**Issue by NevilDabre** [sequelize/sequelize#7767]
I was using sequelize: "^3.30.4"  belongsTo as following

            **classMethods: {
                associate: function (models) {
                    Jobs.belongsTo(models.Employers);
                    Jobs.belongsTo(models.JobTypes);
                    Jobs.belongsTo(models.JobCategories);
                }
            }**

I upgraded Sequelize 4.0.0 and my belongsTo associations stopped working. I am getting only primary fields of my Jobs Model.

**Comment by tom2strobl** [comment]
Classmethods are removed in 4.0.0, see here to resolve your case: http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

**Comment by geluso** [comment]
Will sequelize-cli be updated to work with 4.0.0? It currently uses the old classMethods format.

https://github.com/sequelize/cli/blob/master/lib/assets/models/model.js
