### ISSUE TITLE
instance.validate() has inconsistent return

### ISSUE THREAD

**Issue by dpatti** [sequelize/sequelize#7769]
## What you are doing?
After upgrading to 4.0:

```js
const err = await model.validate();
if (err) {
  // handle error
}
```

## What do you expect to happen?
I expect the return type of `validate()` to be `Promise<undefined|Errors.ValidationError>` as the docs state and the branch to be taken in the case of an invalid model.

## What is actually happening?
The branch is always taken because I received a `Promise<Model>` instead. Taking a quick look at `InstanceValidator`, this is happening because with `hooks: true` (the new default in 4.0), the result is the model instance in the case of success instead of `null`. Relevant code:

```js
validate() {
  return this.options.hooks ? this._validateAndRunHooks() : this._validate();
}
```

```js
_validate() {
  // ...
  return Promise.all(/* ... */).then(() => {
    if (this.errors.length) {
      throw new sequelizeError.ValidationError(null, this.errors);
    }
  });
}
```

```js
_validateAndRunHooks() {
  // ...
  return runHooks('beforeValidate', this.modelInstance, this.options)
    // ...
    .return(this.modelInstance);
}

```

**Comment by felixfbecker** [comment]
It would be best if `validate` just always rejected instead of returning an error :(

**Comment by dpatti** [comment]
I would agree. That's how I expected it to work initially.

**Comment by felixfbecker** [comment]
I think it's a leftover from the switch from callbacks to promises... Unfortunately it would be a breaking change.
The actual bug here is an easy fix if you want to do it

**Comment by dpatti** [comment]
Okay, I'm sorry, I wasn't completely correct before. It looks like the functionality for both paths is to reject with the error if there is one. The resolution value is always `null` in the no-hooks case and always the model instance in the hooks case. I traced the change back to [here](https://github.com/sequelize/sequelize/commit/d56076652eef7651a121c5b2b3d80eef553f867b#diff-6eed5d5a54bdcfa65b0d7f6557362965R74).

Given that this is a 4.0 commit, it looks like the issue was that the docs weren't updated to match the new functionality ([here](https://github.com/sequelize/sequelize/blob/99d87dfff6c494994239588d0193a30a0093e7df/lib/model.js#L3722-L3733)). Though, it still might make sense to fix the inconsistency in the resolution value.

**Comment by felixfbecker** [comment]
PR appreciated
