### ISSUE TITLE
Unit tests failing on Node.js 7+

### ISSUE THREAD

**Issue by leroydev** [sequelize/sequelize#7770]
## What you are doing?
I tried running `npm run test-unit`.

## What do you expect to happen?
I expected the unit tests to pass since I made no modifications.

## What is actually happening?
I got the following error:
```
  1) errors should maintain stack trace:

      AssertionError: expected 'SequelizeBaseError: this is a message' to equal 'SequelizeValidationError: this is a message'
      + expected - actual

      -SequelizeBaseError: this is a message
      +SequelizeValidationError: this is a message

      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:487:12)
      at Assertion.ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at Context.it (test/unit/errors.test.js:19:30)
```
This happens on both Node.js 7.10.0 and 8.1.0. 
On Node.js 6.11.0, all unit tests do pass.

__Sequelize version:__ 4.0.0 (not happening on 3.x.x)
__Node.js versions:__ 7.10.0 and 8.1.0

**Comment by leroydev** [comment]
This could be fixed by adding the following line to the constructor of `ValidationError`:
`Error.captureStackTrace(this, this.constructor);`

This would result in all unit tests passing on 6.11, 7.10 and 8.1.0. 
I don't know if this is an acceptable fix though, as my knowledge about error stack traces isn't this in-depth.
If it's an acceptable fix, I'll gladly make the PR. :)

**Comment by felixfbecker** [comment]
PR appreciated!

**Comment by leroydev** [comment]
@felixfbecker after thinking about it a little bit and experimenting, that wouldn't be an acceptable fix in my opinion as it would only fix it for `ValidationError`. All the other error classes would still have stack traces with `SequelizeBaseError` as error name. 

Adding another unit test that checks the same but for `UnknownConstraintError` for example leads to the same result. 😕

**Comment by felixfbecker** [comment]
I think the `Error.captureStackTrace()` is simply needed in every Error subclass, I would add it to all of them

**Comment by leroydev** [comment]
@felixfbecker yeah that's what the easy fix would be, but it doesn't seem too elegant to me. When someone creates another Error subclass, it'd be easy to forget the `captureStackTrace`. But if there's no solution that's more elegant, that'll have to be the fix I guess.
