### ISSUE TITLE
Question about name strategy for "as" in relationships

### ISSUE THREAD

**Issue by Alexsey** [sequelize/sequelize#7776]
In documentation there are examples with first letter in upper case and in lower case. Is there any difference between how to name it? Like
```
Project.hasMany(User, {as: 'Workers'})
```
vs
```
Project.hasMany(User, {as: 'workers'})
```

Thank you

**Comment by ox** [comment]
It depends on how you define the associations in your `Project` model. The `as` naming should line up with what you named the association in your model. I would read through the ["Naming Strategy"](http://docs.sequelizejs.com/manual/tutorial/associations.html#naming-strategy) and ["Creating with Associations"](http://docs.sequelizejs.com/manual/tutorial/associations.html#creating-with-associations) tutorials a few times (it took me a while to wrap my head around it). I know that postgres likes everything to be lower case, so I do it that way. Hope this helps in some way.

**Comment by Alexsey** [comment]
@ox thanks for reply. The question is does casing of the first letter changes anything. Because as I can see from the docs and my experience it looks like there is no any difference. Or it is just not mentioned. And no advice on this point in [Naming Strategy](http://docs.sequelizejs.com/manual/tutorial/associations.html#naming-strategy)

**Comment by ox** [comment]
From testing a bit, it seems like the particular case of the first letter doesn't matter, just that the name is consistent across all of the associations. I was using this sample code:

```js
const Post = sequelize.define('post', {}, {timestamps: false});
const Comment = sequelize.define('comment', {}, {timestamps: false});

Comment.belongsTo(Post);
Post.hasMany(Comment, {as: 'Comments'});

sequelize.sync({force: true, match: /_dev$/})
  .then(() => {
    return Post.create()
      .then((post) => Comment.create({postId: post.id}));
  })
  .then(() => {
    return Post.findAll({include: [{model: Comment, as: 'Comments'}]});
  })
  .then(([foo]) => {
    console.log(foo.get({plain: true}));
    // #=> { id: 1, Comments: [ { id: 1, postId: 1 } ] }
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => sequelize.close());
```

Changing the case in both `as:` statements at the same time didn't change the program, but having one case be different threw an error: `Error: comment (comments) is not associated to post!`.

If your `Project` model has a named association with a different cased name than the one you put into `as`, it won't work. I'm also using Postgres which is strict with case.

**Comment by Alexsey** [comment]
May be there are something more. It would be great to here something from the core team
