### ISSUE TITLE
Raw Query Replacement is error

### ISSUE THREAD

**Issue by sonha** [sequelize/sequelize#7782]
This is my sql : 
`        var commonSql = " FROM building A                                               \
                            WHERE IF(:status IS NULL, TRUE, A.status = :status)         \
                            AND IF(:keyword IS NULL, TRUE, A.name LIKE :keyword)        \
                            AND A.active_flag = 1                                       ";
        var sql = "SELECT                                                               \
                        A.*,                                                            \
                        (SELECT COUNT(*)                                                \
                            FROM room B                                                 \
                                WHERE A.id = B.building_id                              \
                                AND B.active_flag = 1) AS no_of_zooms                   \
                   "+commonSql + " ORDER BY :order :dir LIMIT :offset, :limit ";`

  return this.model.sequelize.query(sql, {
                replacements: {
                    keyword: keyword,
                    status: status,
                    order: order,
                    dir: dir,
                    offset: offset,
                    limit: limit
                },
                type: this.model.sequelize.QueryTypes.SELECT
            }).then(data => {

But, When I received data, it not ordered ? Can you tell me why ? thank you ?

**Comment by yonjah** [comment]
I would suggest turning on Sequelize loggging and see what is the actual query being sent.
Also I'm npt sure how this will work with Sequelize auto escaping of parameters.
You probably need to use `Sequelize.literal` to set the order so it wont be escaped.
There is an example here -
http://docs.sequelizejs.com/manual/tutorial/querying.html

**Comment by sonha** [comment]
@yonjah thank you for your help !

**Comment by armenparonikyan** [comment]
Leave me alone
