### ISSUE TITLE
Implement freetext search for mssql OR bring back support for literal replacements

### ISSUE THREAD

**Issue by devspireRoland** [sequelize/sequelize#7783]
My company is implementing an application where we have to do a lot of freetext search queries. There was no "out of the box" support fot this in Sequelize v3.x so we just used literal replacements like in this query-json:

{ include: [ { model: ArticleResource, as: 'ArticleResource' } ],
  order: 'CreatedAt DESC',
  distinct: true,
  offset: 0,
  limit: 20,
  where: [ ' (FREETEXT ([Title], \'some%20text%20to%20search%20for\') OR FREETEXT ([Summary], \'some%20text%20to%20search%20for\') )' ] }

We are unable to migrate to v4 because of this issue.

**Comment by janmeier** [comment]
You can use `where: sequelize.literal('FREETEXT ...')` - I'm pretty sure the error message mentions this as well.
