### ISSUE TITLE
SQL generator for WHERE clause equal null bug

### ISSUE THREAD

**Issue by hmilkovi** [sequelize/sequelize#7790]
## What you are doing?
Querying database where some of variables ` product ` , ` language ` , ` page ` and ` source ` are equal to ` null ` .

```js
// Does not work as expected
Test.findAll({
		where: {
			test1: product,
			test: language,
			page: pagel,
			source: source
		},
		raw: true,
		include: [{
			model: models.TestRelated
		}]
	}).then(cb);
```

vs

```js
// Works
Test.findAll({
		where: {
			test1: product ? product : null,
			test: language ? language : null,
			page: page ? page : null,
			source: source ? source : null
		},
		raw: true,
		include: [{
			model: models.TestRelated
		}]
	}).then(cb);
```

## What do you expect to happen?
Generate SQL in where clause ` product IS NULL AND page IS NULL  etc. `

## What is actually happening?
Note ` column=NULL ` will never be true. It generates sql with equal, only last is generated with ` IS NULL ` but only when I pass variable. When I explicit pass ` null ` the SQL generator does fine.

```sql
SELECT `test`.`id`, 
       `Test`.`product`, 
       `Test`.`language`, 
       `Test`.`page`, 
       `Test`.`source`, 
       `Test`.`createdat`, 
       `Test`.`updatedat`, 
       `Test`.`testrelatedid`, 
       `TestRelated`.`id`        AS `TestRelated.id`, 
       `TestRelated`.`url`       AS `TestRelated.url`, 
       `TestRelated`.`createdat` AS `TestRelated.createdAt`, 
       `TestRelated`.`updatedat` AS `TestRelated.updatedAt` 
FROM   `test` AS `RedirectSource` 
       LEFT OUTER JOIN `TestRelateds` AS `TestRelated` 
                    ON `test`.`testrelatedid` = `TestRelated`.`id` 
WHERE  `Test`.`product` = NULL 
       AND `Test`.`language` = NULL 
       AND `Test`.`page` = 'home' 
       AND  `Test`.`source` IS NULL; 
```

Dialect: mysql
MySQL version: 5.5.52
Sequelize version: 4.0.0

**Comment by yonjah** [comment]
Not sure about this one. But from JS perspective -
`test1: product ? product : null`
and 
`test1: product`
Are exactly the same if `product === null`
So If one works and the other not `product` probably has some other falsy value, maybe `undefined`
What do you get if you `console.log(product === null);` (notice the triple `=` ) ?

**Comment by hmilkovi** [comment]
Ouuu demit now i see only this 3 first paramets can be ` undefined ` but last I allways pass string or null. Thx for hint :)
