### ISSUE TITLE
V4 hooks is not working with callbacks

### ISSUE THREAD

**Issue by albertosouza** [sequelize/sequelize#7792]
Hello, 
Sequelize v4 not is working with callbacks in hooks like are documented and was working on last sequelize version.

In documentation:
```
afterCreate(instances, options, fn)
```
And if do something like:
```
Book.addHook('afterCreate', 'doSomething', (book, options, cb) => {
  console.log('callback is undefined>', cb);
});
```
The callback function is undefined.
This seens to be a bug and is important to keep this callback on hooks feature to prevend big breaking changes.

If this is a bug i can help with fix ...

**Comment by albertosouza** [comment]
Code to show this problem: https://github.com/albertosouza/sequelize_v4_issue_7792

**Comment by deimosOmegaChan** [comment]
Hi,
The callback parameter has been removed at hooks. You need to return a Promise object.
```
Book.addHook('afterCreate', 'doSomething', (book, options) => {
  return Promise.resolve();
  // or
  return Promise.reject();
});
```

**Comment by albertosouza** [comment]
Then documentation update is needed
