### ISSUE TITLE
Encrypting column data before insert

### ISSUE THREAD

**Issue by skumar200015** [sequelize/sequelize#7798]
## What you are doing?
We use SQL server 2016, hosting one database for multiple clients. We have a requirement from some clients to encrypt data on some columns within a model before insert/update into the 
database. Is there a way this could be done within sequelize natively? We know SQL server provides column encryption but this would enable encryption for all clients. 

## What do you expect to happen?
The idea would be that during insert we would know the clientid and if the client is enabled for encryption then we would use the client's encryption key to either encrypt or decrypt the column data.

__Dialect:__ mssql
__Database version:__ 2016
__Sequelize version:__ 3.30.4

Thanks for your help in advance.

**Comment by ox** [comment]
You could try to experiment with adding [hooks](http://docs.sequelizejs.com/manual/tutorial/hooks.html), either just for certain models or globally. The `before*` and `after*` hooks could check the clientid and conditionally encrypt/decrypt certain columns.

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
