### ISSUE TITLE
`sync({ alter: true })` seems to ignore `field` option

### ISSUE THREAD

**Issue by wwgc** [sequelize/sequelize#7799]
__Dialect:__ mysql 
__Database version:_5.6.25
__Sequelize version:4.1.0

### code
```js
sequelize.define('Test',{
  systemName: {
    type: DataTypes.STRING(32),
    field: 'system_name'
  }
});
```

### What do you expect to happen?

Using `db.sync()`, Column 'system_name' is created in right way. 

```js
models.drop().then(function() {
  return models.sync();
});
```

### What is actually happening?

Using `db.sync({ alter: true })`, column 'systemName' is created. I need 'system_name', not 'systemName'.

```sql
ALTER TABLE `Test` ADD `systemName` VARCHAR(32);
ALTER TABLE `Test` DROP `system_name`;
```

**Comment by Rishabhk07** [comment]
i am facing the same problem

**Comment by Rishabhk07** [comment]
any update on this issue ?

**Comment by ctpstudy** [comment]
I have the same problem

**Comment by tomgao365** [comment]
me too

**Comment by varun-coditas** [comment]
I'm still facing this issue. Any update on this?

**Comment by arthurfauq** [comment]
Any update ? Facing the same issue here

**Comment by yeongjet** [comment]
Same problem, bug?

**Comment by papb** [comment]
This doesn't seem to be restricted to MySQL, can someone please check that this also happens with another dialect? Thanks

**Comment by sushantdhiman** [comment]
```
Executing (default): ALTER TABLE "public"."listing" ADD COLUMN "some_a_name" VARCHAR(20) NOT NULL;
```

It seems like it is working in master
