### ISSUE TITLE
Connection pool cleaning cannot work on process exit event

### ISSUE THREAD

**Issue by marqu3z** [sequelize/sequelize#7801]
## What you are doing?
I'm trying to graceful exit the process cleaning the db connections.

```js
process.exit(1)
// or
throw new Error("foo")
// or
notExsistingFunction()
// or
lastCommand() // node event loop is clean, the process will exit
```

## What do you expect to happen?
To properly clean the connection

## What is actually happening?
The `ConnectionManager` will listen to the `exit` event calling the `onProcessExit` method. (https://github.com/sequelize/sequelize/blob/e239a04da62f7fa5bb127743e67da5ff0f80b756/lib/dialects/abstract/connection-manager.js#L42)
But the `exit` event cannot be listened with a callback running async tasks. 
The node docs says (https://nodejs.org/api/process.html#process_event_exit):
> Listener functions must only perform synchronous operations. The Node.js process will exit immediately after calling the 'exit' event listeners causing any additional work still queued in the event loop to be abandoned.

__Dialect:__  postgres
__Database version:__ 9.5.7
__Sequelize version:__ 4.1.0

**Comment by yasuhiroki** [comment]
I faced same problem too.

**Dialect:** mysql
**Database version:** 5.7
**Sequelize version:** 4.1.0

**Comment by janmeier** [comment]
I see that it's not ideal, but I think it's the best we can do - Hopefully the pool will at least start to clear out, and most connections will be released.

There is also beforeExit, which can do async actions, but it is not invoked for uncaught exceptions, or when calling `process.exit`

**Comment by marqu3z** [comment]
Hi @janmeier 
Maybe something could be done to improve the cleanup.
Except for a manual `process.exit()` a process `exit` event is usually triggered after some other useful events happened like `beforeExit`,  `uncaughtException`, `SIGTERM`, `SIGINT`.

Those events can be used to cleanup the connections.
My concern is that events like `uncaughtException` could be handled by the application logic and therefore not trigger an exit at all. 
So it could be a bad idea to unconditionally add a listener there.

Maybe a discussion here could be helpful.
IMHO there are 2 options: 
 - Provide a method to force the connection cleanup on those events: `sequelize.forceCleanup()`
 - Let the user handle it, and improve the docs and be clear about the connection cleanup and the nature of the `exit` event.

For now i'm handling this adding listeners to all the possible events causing an exit:

```javascript
let events = [
  {name: 'beforeExit', exitCode: 0 },
  {name: 'uncaughtExecption', exitCode: 1 },
  {name: 'SIGINT', exitCode: 130 },
  {name: 'SIGTERM', exitCode: 143 }
]

events.forEach((e) => {
  process.on(e.name,  () => {
    sequelize.connectionManager.close()
      .then(() => { 
        console.log('connection cleaned') 
        process.exit(e.exitCode) 
      })
      .catch((e) => {
        console.error(e)
        process.exit(1)   
      })    
  })
))


```

**Comment by janmeier** [comment]
> Provide a method to force the connection cleanup on those events:

Already exists http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-method-close

> Let the user handle it, and improve the docs and be clear about the connection cleanup and the nature of the exit event.

I think closing as much as we can before the process exists is a good idea. That said, we might still want to make users more aware of what to do - Docs PR welcome! 

Personally I always add this to scripts that use sequelize `.finally(() => sequelize.close());` so the script does not hang after it's done
