### ISSUE TITLE
How to define class methods in connection in Sequelize 4?

### ISSUE THREAD

**Issue by Flame2057** [sequelize/sequelize#7804]
In Sequelize 3, I could say

```javascript
new Sequelize(DBInfo.db, DBInfo.username, DBInfo.password, {
    define: {
        classMethods: {
	    ClassLevelFunction() {
                // function
            }
	}
    }
});
```

and have `ClassLevelFunction` registered as a class method on all my models. Now this does not work? What is the new way of doing this?

**Comment by Flame2057** [comment]
Since you cannot use `classMethods` when defining a model, it appears that you also cannot use it in the `define` option when creating a connection.

**Comment by yonjah** [comment]
Please refer to the docs -
http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html
It is all explained there.
Basically for `classMethods` you now just define the method directly on the returned Model.

**Comment by Flame2057** [comment]
Well you clearly didn't read the issue

**Comment by yonjah** [comment]
I guess I misunderstood what you are trying to  do.
There is a way but it is undocumented. 
So just wait for someone from the project core team to help you out

**Comment by Flame2057** [comment]
That's okay. What you said is that I have been doing in the meantime, and I guess it works, but still it would be nice to have it defined like I could in Sequelize 3.

**Comment by jacksonCamara** [comment]
module.exports = (sequelize, DataType) => {
  const Telefones = sequelize.define("Telefones", {
    id: {
      type: DataType.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    numero: {
      type: DataType.STRING,
    }
  });

  Telefones.associate = models => {
    Telefones.belongsTo(models.Clientes);
  }

  return Telefones;
};

====================================================

var fs = require('fs');
var path = require('path');
var Sequelize = require('sequelize');
var basename = path.basename(module.filename);
var config = require('../config/env/config')();
var env = config.env || 'development';
var db = {};

console.log(config.db)

const sequelize = new Sequelize(config.db, config.username, config.password, {
  host: 'localhost',
  dialect: 'postgres',
  pool: {
    max: 5,
    min: 0,
    idle: 10000
  }
});


fs
  .readdirSync(__dirname)
  .filter(function (file) {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(function (file) {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function (modelName) {
  console.log('===================entrou no index =======================')

  console.log(db[modelName])
  console.log(db[modelName].associate)
  if (db[modelName].associate) {
    console.log('===================entrou no index associate=======================')
    console.log(db[modelName])
    db[modelName].associate(db);
  }
});

sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;

**Comment by janmeier** [comment]
@yonjah Is right - *The classmethod option has been remove, so you will have to add the methods directly to your model

**Comment by AlexShuraits** [comment]
I have achieved the same functionality as in Sequelize 3 by adding methods on Sequelize.Model class inside sequelize index.js:

```
Sequelize.Model.newStaticMethod = function(){}
Sequelize.Model.prototype.newInstanceMethod = function(){}
```

**Comment by pkyeck** [comment]
sorry to dig this up but I was wondering how I can access other model-classes from class methods?
In the `index.js` we pass the `db` object into the `associate` function and can access the different models. but I don't want to do that for my manually called class functions. Should I create the other class functions inside the `associate` to be able to access the models?

**Comment by aprilmintacpineda** [comment]
is it safe to use the `index.js` on the models' directory? I mean we're not supposed to commit that right?

**Comment by iamjoyce** [comment]
@aprilmintacpineda Do you mean [https://github.com/sequelize/express-example/blob/master/models/index.js](https://github.com/sequelize/express-example/blob/master/models/index.js)?

Yes it's mean to commit. It's a singleton pattern where other files will `require('../models')` instead of each individual model file.
