### ISSUE TITLE
autoIncrement, not PK, is set to PK value

### ISSUE THREAD

**Issue by timscott** [sequelize/sequelize#7805]
## What you are doing?
I have a UUID PK and an autoIncrement integer that is not the PK, like so:

```javascript
  User = sequelize.define('User', {
    id: {
      primaryKey: true,
      allowNull: false,
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV1
    },
    number: {
      type: DataTypes.INTEGER,
      autoIncrement: true
    },
   ...
```

Then I create:

```js
User.create(attrs).then(user => {
  console.log(user.id);
  console.log(user.number);
})
```

Outputs:

```bash
> 020ff1f0-52e4-11e7-882d-e57357f98104
> 020ff1f0-52e4-11e7-882d-e57357f98104
```

If I re-fetch the user, then `user.number` is again correct.

## What do you expect to happen?
Immediately after create, I expect the `user.number` to be the auto generated integer that I can see is now in the database.

I tried, setting `primaryKey: false` for `number` attribute, which did not work.

## What is actually happening?
`user.number` is set to the `user.id` value until re-fetched.

__Dialect: mssql
__Sequelize version: 3.30.2

**Comment by Flame2057** [comment]
use `user.dataValues.id` and `user.dataValues.number`

And read the docs next time

**Comment by timscott** [comment]
Wow. Douchiness == epic.

**Comment by Flame2057** [comment]
You're welcome.

**Comment by timscott** [comment]
```bash
> console.log(user.dataValues.number)
`020ff1f0-52e4-11e7-882d-e57357f98104`
```

So no.

**Comment by Flame2057** [comment]
You posted some incomplete code there

**Comment by timscott** [comment]
I can see how it might be hard follow for an inexperienced (or deliberately obtuse) dev.

In any case, the behavior is certainly wrong.

**Comment by Flame2057** [comment]
You won't get any help with that attitude

**Comment by Flame2057** [comment]
But yes it is not right. The reason I said use `dataValues` was because that's what I've been using, and the `user` object itself will have a lot of other properties not related to the columns you fetched from the DB.

**Comment by timscott** [comment]
Still broken.
