### ISSUE TITLE
Sequelize v4 does not update the instance when using .increment or .decrement

### ISSUE THREAD

**Issue by LaurentVB** [sequelize/sequelize#7810]
## What you are doing?

Hello, upgrading from v3 to v4, I had the following issue:

```js
const User = sequelize.define('user', {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4
  },
  username: {
    type: DataTypes.STRING,
    allowNull: false
  },
  balance: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  }
});

describe('.increment', ()=> {
  it('increments the property in the instance', () => {
    return User.create({username: 'alice'})
      .then(user => {
        user.increment('balance', 5)
        .then(()=> {
          expect(user.balance).toBe(5);
        });
      });
  });
});
```

## What do you expect to happen?
In Sequelize v3, the test would pass. the balance would be incremented in the object, without the need to reload it from the DB. After the upgrade, I expected the same behaviour as demonstrated by the test.

## What is actually happening?
With Sequelize v4, the record is updated in DB but the instance itself is not.
This is not documented in the upgrade notes.

__Sequelize version:__ v4.1.0

**Comment by felixfbecker** [comment]
I think this was a regression from a PR that introduced the static `increment` method and made instance `increment` call that.

**Comment by hieven** [comment]
Hi,
I was the one who raised the PR for introducing the static `increment` method. I am sorry for your inconvenience. 
If possible, please let me fix the bug.

**Comment by hieven** [comment]
Hey @LaurentVB
May I know what kind of database and what is the specific version of sequelize you are using?

I spent some time doing an experiment, however I didn't found any inconsistency during different version of sequelize.

Please correct me if I did it in a wrong way.

Here is the result of the experiment

| DB/version   | 3.30.4 | 4.0   | 4.1   |
|-------------|--------|-------|-------|
| MySQL         | 0/0/5  | 0/0/5 | 0/0/5 |
| PostgreSQL | 0/5/5  | 0/5/5 | 0/5/5 |
| Sqlite           | 0/0/5  | 0/0/5 | 0/0/5 |

(X/Y/Z means the `balance` **before increment**/**after increment**/**after reload**)

Here is the code how I run the test
```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('database', 'username', 'password', {
    // dialect: 'mysql',
    // dialect: 'postgres',
    dialect: 'sqlite',
    storage: './database.sqlite'
});

const User = sequelize.define('user', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
    defaultValue: Sequelize.UUIDV4
  },
  username: {
    type: Sequelize.STRING,
    allowNull: false
  },
  balance: {
    type: Sequelize.INTEGER,
    defaultValue: 0
  }
});

sequelize.sync()
  .then(async () => {
    User.create({ username: 'alice' })
      .then(user => {
        console.log('before increment');
        console.log(user);

        user.increment({ balance: 5 })
        .then(()=> {
          console.log('after increment');
          console.log(user);

          return user.reload()
        })
        .then(user => {
          console.log('after reload');
          console.log(user);
        })
        ;
      });
  });
```

**Comment by dainis** [comment]
@hieven 

Regression is with decrement method(on pg)

```js
sequelize.sync()
  .then(() => {
    User.create({ username: 'alice' })
      .then(user => {
        console.log('before decrement');
        console.log(user.balance);

        user.decrement({ balance: 5 })
        .then(()=> {
          console.log('after decrement');
          console.log(user.balance);

          return user.reload()
        })
        .then(user => {
          console.log('after reload');
          console.log(user.balance);
        })
        ;
      });
  });
```

4.0 | 4.1
--- | --- 
0/-5/-5 | 0/0/-5


[increment uses model option and decrement uses instance option](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L677-L696) (changing decrement to mimic increment fixes this inconsistency)

**Comment by hieven** [comment]
@dainis 

Sorry for the late reply and thanks for pointing out the bug!
I've issued a PR for solving the regression of the `decrement` instance method.
Thanks again 😃

**Comment by saboteurkid** [comment]
Hi there, I got a problem about understanding Sequelize (I've thought about open new issue but this one is relate to me)

1: This one run and return expected value but the reload (SELECT query) is out of the transaction.
```
return db.transaction(trx => {
        return Post
            .findById(id)
            .then(post => {
                return post.increment({ views: 1 }, { transaction: trx })
            })
    }).then(post => {
        return post.reload()
    })
```
vs
2: This one run and return old value.
```
return db.transaction(trx => {
        return Post
            .findById(id)
            .then(post => {
                return post.increment({ views: 1 }, { transaction: trx })
            }).then(post => {
        return post.reload()
    })
    })
```
What is the difference between these two? I try to query in sqlite3 and there nothing wrong with the result.

Thanks in advance

P/s: Sorry for my bad English.

**Comment by icharge** [comment]
> Hi there, I got a problem about understanding Sequelize (I've thought about open new issue but this one is relate to me)
> 
> 1: This one run and return expected value but the reload (SELECT query) is out of the transaction.
> 
> ```
> return db.transaction(trx => {
>         return Post
>             .findById(id)
>             .then(post => {
>                 return post.increment({ views: 1 }, { transaction: trx })
>             })
>     }).then(post => {
>         return post.reload()
>     })
> ```
> 
> vs
> 2: This one run and return old value.
> 
> ```
> return db.transaction(trx => {
>         return Post
>             .findById(id)
>             .then(post => {
>                 return post.increment({ views: 1 }, { transaction: trx })
>             }).then(post => {
>         return post.reload()
>     })
>     })
> ```
> 
> What is the difference between these two? I try to query in sqlite3 and there nothing wrong with the result.
> 
> Thanks in advance
> 
> P/s: Sorry for my bad English.

I use v5. But same.

So I experienced like you and then I find out that `reload()` you have to pass `transaction` too.

```
return db.transaction(trx => {
        return Post
            .findById(id)
            .then(post => {
                return post.increment({ views: 1 }, { transaction: trx })
            })
    }).then(post => {
        return post.reload({ transaction: trx }) // <---- here
    })
```
