### ISSUE TITLE
Optimistic Locking MSSQL

### ISSUE THREAD

**Issue by Riclas1** [sequelize/sequelize#7811]
Hello Everybody,
i´m new to sequelize, that´s why maybe I misunderstood somethings in the documentation. Right now I’m trying to implement an optimistic locking to a database.

` 
this.antiVirusSoftwares = sequelizeConnection.define('antiVirusSoftwares', { 
`
`
ComputerID: { type: Sequelize.STRING(50), primaryKey: true, allowNull: false },
`
`
Manufacturer: { type: Sequelize.STRING(50), allowNull: true },
`
`
VersionSW: { type: Sequelize.STRING(50), allowNull: true },
`
`
ProdName: { type: Sequelize.STRING(50), primaryKey: true, allowNull: true }
`
`
}, {
`
`
 timestamps: false,
`
`
 tableName: 'AntiVirusSoftwares',
`
`
version: true
`
`
});
`

This is the table which is created concerning the model definition from sequelize. 

`
/****** Script for SelectTopNRows command from SSMS  ******/
`
`
SELECT TOP 1000 [ComputerID]
`
`
,[Manufacturer]
`
`  
,[VersionSW]
`
`
,[ProdName]
`
`
FROM [SMMC].[dbo].[AntiVirusSoftwares]
`

At the documentation it is written that with version: true a version count attribute is added. 
![image](https://user-images.githubusercontent.com/19823655/27283690-ba4c49d6-54f5-11e7-8f41-2a1301243b0e.png)

What did I miss?

One more Question not directly connected to this but still at my agenda.
Is it possible to connect to the MSSQL server and create a database, which can be filled from sequelize with tables and start up data? If it possible where I found some documentation about it?

Thanx in advanced

Rico

**Comment by SVRao19056** [comment]
You need to set timestamp and version to true for optimistic locking to be enabled . The destination table should have the timestamp columns created_at , modified_at
