### ISSUE TITLE
[BUG] [4.1.0] {alter: true} tries to create unique index every time on sync()

### ISSUE THREAD

**Issue by felixbrucker** [sequelize/sequelize#7813]
## What you are doing?

```js
const Plugin = sequelize.define('Plugin', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        someId: {
            type: DataTypes.INTEGER,
            allowNull: false,
        },
    }, {
        indexes: [
            {
                unique: true,
                fields: ['someId'],
            },
        ],
    });

[...]

sequelize.sync({alter: true});
```

## What do you expect to happen?

I expect the unique index to be created once if it doesn't exist yet.

## What is actually happening?

Actually it is created once when transitioning from old schema (3.X), but even in this same startup it tries to create it again, and fails:

```
Executing (default): ALTER TABLE "Plugins" ALTER COLUMN "someId" SET NOT NULL;ALTER TABLE "Plugins" ALTER COLUMN "someId" DROP DEFAULT;ALTER TABLE "Plugins"  ADD CONSTRAINT "someId_unique_idx" UNIQUE ("someId");ALTER TABLE "Plugins" ALTER COLUMN "someId" TYPE INTEGER  ;
(node:13647) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SequelizeDatabaseError: relation "someId_unique_idx" already exists
```

this only happens if the `someId` key appears in some other model as well.

Upon a second start with `alter: true` it always fails, even if the key name is unique within all models (`someId` and `someId2`)

looking at the [code](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L263) `definition` is `INTEGER NOT NULL UNIQUE` for every sync() so the `UNIQUE` match is executed every time. I'm not very familiar with such things, but i suppose `UNIQUE` should be gone after the `CONSTRAINT` got added.

__Dialect:__ postgres
__Database version:__ 9.6.2
__Sequelize version:__ 4.1.0

**Comment by kristijan-ujevic** [comment]
Can confirm, i'm getting the same issue.

Any ETA on the fix?

**Comment by marqu3z** [comment]
Same issue here.
Can't sync with `alter: true` and unique constraints. 
Another buggy behaviour is the `UnhandledPromiseRejectionWarning` error that is triggered even with a `.catch()`

**Comment by OfekA** [comment]
Can confirm, same issue.

**Comment by skn3** [comment]
#7915 duplicate issue?

**Comment by skn3** [comment]
a potential fix for now is to manually specify the unique index name?

**Comment by skn3** [comment]
posted a work around for this issue for anyone that needs it:
[https://github.com/sequelize/sequelize/issues/7915#issuecomment-314222662](https://github.com/sequelize/sequelize/issues/7915#issuecomment-314222662)

**Comment by ronster37** [comment]
Can confirm, I'm getting the same issue.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/7606
