### ISSUE TITLE
Validation min: 0 always return false 

### ISSUE THREAD

**Issue by eBaeza** [sequelize/sequelize#7815]
## What you are doing?
_Validate a float number that is not less than 0_

```js
    price: {
      type: DataTypes.FLOAT,
      allowNull: false,
      validate: {
        isFloat: { msg: 'The price must be numeric.' },
        min: { args: 0, msg: 'The price should not be less than 0.' },
      },
    },
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_Always does not pass that validation _

__Sequelize version:__ 4.1.0

**Comment by ox** [comment]
`args` takes an array. So if you change the validation to:

```js
    price: {
      type: DataTypes.FLOAT,
      allowNull: false,
      validate: {
        isFloat: { msg: 'The price must be numeric.' },
        min: { args: [0], msg: 'The price should not be less than 0.' },
      },
    },
```

then it should validate as expected. This worked for me on postgres 9.6.3, sequelize: 3.30.4.

**Comment by eBaeza** [comment]
Thanks!! that works for me :D
