### ISSUE TITLE
could Unmanaged transaction been rollback in 3.27.0?

### ISSUE THREAD

**Issue by jyunhan** [sequelize/sequelize#7816]
Hi,
I'm trying to use unmanaged transaction to handle the sql trade process.
I wanna rollback even the trade process is fine.
so I give a new error into promise.
but this trade still successful.
why does it matter??

* same situation occur in Model.findOrCreate({option})

the following are my code...

```js
return sequelize.transaction().then( t => {
        Account.create(
            {
                email: 'test @gmail.com',
                name: 'LIOU',
                role: 'enduser',
            },
            {
                transaction: t
            }
        )
        .then( () => {
            throw new Error('error occur!!!!!!!~~~~');
            return t.commit();
        })
        .catch(function (err) {
            return t.rollback();
        });
    })
    .then( () => res.status(200).json('done'))
```

**Comment by janmeier** [comment]
You need to return the promise chain from `Account.create`, otherwise `res.status` is called immediately
