### ISSUE TITLE
Logging problem with Winston

### ISSUE THREAD

**Issue by benjhoo** [sequelize/sequelize#7821]
When using Winston.info() function as main Sequelize logging function, logs contain Sequelize logging function code.

Simple example : 

```js
const
    config  = require("./config"),
    winston = require("winston"),
    Sequelize = require("sequelize");

const sequelize = new Sequelize(config.db.name, config.db.username, config.db.password, {
    host: config.db.host,
    dialect: "mysql",
    logging: winston.info
});

sequelize.authenticate()
    .then(() => winston.info("Connection has been established successfully."))
    .catch(err => winston.error("Unable to connect to the database: ", err));
```

This example outputs the following log :

```
info: Executing (default): SELECT 1+1 AS result logging=function (msg) {
      // build argument list (level, msg, ... [string interpolate], [{metadata}], [callback])
      var args = [level].concat(Array.prototype.slice.call(arguments));
      target.log.apply(target, args);
    }, plain=true, raw=true, showWarnings=false, type=SELECT
info: Connection has been established successfully.
```

__Dialect:__ mysql
__Database version:__ 5.7.12
__Sequelize version:__ 4.2.0

**Comment by ox** [comment]
I'm using bunyan and what worked for me was binding the function to the logger, like so:

```js
const log = require('bunyan').createLogger({name: 'db'});
const sequelizeOpts = {
  logging: log.debug.bind(log),
};
```

maybe that works for you?

**Comment by felixfbecker** [comment]
If you pass `winston.info`, you unbind the `info` method from the `winston` object. See @ox' answer.

**Comment by benjhoo** [comment]
Thanks for your answers.
But, nope, it doesn't work for me when using :
```js
logging: winston.info.bind(winston)
```

Using sequelize@3.20.0 instead seems to work.

**Comment by felixfbecker** [comment]
Can you reproduce the problem with plain `console.log`?

**Comment by benjhoo** [comment]
The following works:
```js
logging: console.log
```

But this doesn't:
```js
logging: console.log.bind(console)
```

**Comment by felixfbecker** [comment]
That doesn't make any sense

**Comment by DeeSnow97** [comment]
[This method](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1022) may be the source of both bugs. It allows to pass `options` as the last argument and removes it *only if the logging function is `console.log`*, which is probably why the object is included if `winston.info` is used. Since `console.log.bind(console)` isn't equal to `console.log`, `options` is also included that way.

Also, the actual invocation of the logging function is `options.logging.apply(null, args)`, which sets `this` to the current global object. Apparently, `console.log` is fine with that, that's why it even works with the default value.

**Comment by felixfbecker** [comment]
This is the PR that changed this: https://github.com/sequelize/sequelize/pull/7555

I don't understand _at all_ why `console.log` should be treated any different than other loggers. @janmeier @contactakagrawal could you explain?

**Comment by contactakagrawal** [comment]
Actually, we wanted to access the options object in our custom log method provided to sequelize, so we skipped splicing the option object in case of anything other than console.log, am I missing anything here?

**Comment by felixfbecker** [comment]
@contactakagrawal why should `console.log` be treated any different from other loggers, or a bound `console.log`?

**Comment by DeeSnow97** [comment]
I can see a feature behind it. With `options` included for custom loggers, you could maybe do some advanced handling instead of just collecting text data. However, I wouldn't call handling `console.log` differently great design, especially since [you can create your own Console object in Node](https://nodejs.org/api/console.html#console_new_console_stdout_stderr), and custom loggers are exactly where someone would use such a trick.

The problem is, initial reasons aside, handling this issue may not be as easy as it seems. Even though this is not a very well documented part of the public API, removing the `options` object from custom loggers is a breaking change and therefore would need to be delayed until 5.0.

My proposal would be to accept an object on `options.logging` as well that makes the trailing `options` object explicitly configurable, in a similar fashion:

```js
const sequelizeOptions = {
  logging: {callback: winston.info, includeOptions: false}
}
```

Then, as a second step, deprecate the implicit `true` value on `includeOptions` so that in the next major version it could switch to `false` by default. Those who would like to keep the `options` object could just use this object notation with `includeOptions: true` and for others it would be as simple as adding a drop-in replacement for console.log, like must logging libraries do.

Currently, if you supply an object to `options.logging`, it just breaks because objects are not handled anywhere (unless you supply one with an `apply` attribute, in which case it's called). I highly doubt anything depends on that error.

**Comment by felixfbecker** [comment]
> removing the options object from custom loggers is a breaking change and therefore would need to be delayed until 5.0

I disagree. Log messages, just like error messages, don't fall under any contract. You should never assert on the content of error messages or log messages, therefor no application breaks if any of these change (otherwise fixing a typo in a log or error message would be breaking change too).

Regarding the proposal, I would just add a `logOptions` flag.

**Comment by DeeSnow97** [comment]
It would be nice to have some examples for that, but the scenario I would imagine here is where a custom logger parses the `options` object in the log message. I see that this is non-standard behavior, but most people have something like `"sequelize": "^4.2.0"` in their package.json, and if this is changed in 4.3.0 (or worse, 4.2.1), some apps and their dependencies could suddenly break after an npm install. This is exactly why we have semver in the first place, and npm heavily depends on it.

About the flag, I absolutely agree with `logOptions`, it definitely feels more consistent with Sequelize's API design. However, I would set it to `true` by default if `logging` is set, at least until 5.0.

**Comment by felixfbecker** [comment]
Users who
- use private (underscore-prefixed) API
- rely on error messages
- rely on log messages
- use older node versions not officially supported anymore
- use older database versions not officially supported anymore

have to expect that their applications can break on minor versions.

**Comment by contactakagrawal** [comment]
@felixfbecker  After reading all the pros & cons, I also feel now logOptions flag should do if that is doable.

**Comment by ox** [comment]
@benjhoo: how about a simple work-around for now:

```js
logging: (msg) => winston.info(msg),
```

This prints out the following in my test:

```
info: Executing (default): SELECT 1+1 AS result
info: Connection has been established successfully.
```

**Comment by benjhoo** [comment]
@ox: thank you for your proposal but it seems to act like console.log (displays the log on console but not in my log file defined in Winston conf)

**Comment by felixfbecker** [comment]
If anyone wants to do a PR to remove the different handling of `console.log` (and maybe a `logOptions` parameter instead) be my guest

**Comment by ox** [comment]
@benjhoo how are you configuring your winston logger? I created a logger that logs to console and file and it wrote to both:

```js
const Sequelize = require('sequelize');
const winston = require('winston');
const logger = new winston.Logger({
  level: 'info',
  transports: [
    new (winston.transports.Console)(),
    new (winston.transports.File)({filename: 'somefile.log'}),
  ],
});

const {POSTGRES_DB, POSTGRES_USER, POSTGRES_HOST, POSTGRES_PORT, POSTGRES_PASSWORD, = process.env;

const opts = {
  host: POSTGRES_HOST,
  port: POSTGRES_PORT,
  dialect: 'postgres',
  logging: (msg) => logger.info(msg),
};

const sequelize = new Sequelize(POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, opts);

sequelize.authenticate()
    .then(() => logger.info('Connection has been established successfully.'))
    .catch((err) => logger.error('Unable to connect to the database: ', err))
    .finally(() => sequelize.close());
```

After running it and seeing the console output, I checked `somefile.log`:

```
$ cat somefile.log
{"level":"info","message":"Executing (default): SELECT 1+1 AS result","timestamp":"2017-06-28T15:37:09.576Z"}
{"level":"info","message":"Executing (default): SELECT 1+1 AS result","timestamp":"2017-06-28T15:37:21.876Z"}
{"level":"info","message":"Connection has been established successfully.","timestamp":"2017-06-28T15:37:21.885Z"}
```

**Comment by contactakagrawal** [comment]
@felixfbecker I can raise the PR with logOptions if you want, my question is where should this configuration go, in main sequelize configurations or per query options object. kindly suggest

**Comment by felixfbecker** [comment]
Like `logging` I would say both

**Comment by contactakagrawal** [comment]
@felixfbecker what should be the case if logging: true, logOptions: true. should console.log also log the options?

**Comment by felixfbecker** [comment]
of course, why not

**Comment by contactakagrawal** [comment]
ok, in that case are we using any library which can take care the circular jsons?, as logging options may result into circular references, if not can you suggest any library, one of them is https://www.npmjs.com/package/circular-json

**Comment by felixfbecker** [comment]
Afaik `console.log` (which uses `util.inspect`) supports circular structures just fine.

**Comment by felixfbecker** [comment]
```
> var x = {}
undefined
> x.x = x
{ x: [Circular] }
```

**Comment by contactakagrawal** [comment]
I just tried, the normal console.log throwing error ERROR 2017-07-11 10:05:31.491 UTC uncaughtException: Converting circular structure to JSON

**Comment by felixfbecker** [comment]
What input? What call stack?

**Comment by contactakagrawal** [comment]
Sequelize.prototype.log = function() {
  var args = Utils.sliceArgs(arguments)
    , last = Utils._.last(args)
    , options;

  if (last && Utils._.isPlainObject(last) && last.hasOwnProperty('logging')) {
    options = last;

    // remove options from set of logged arguments
    **_if(!options.logOptions){
      args.splice(args.length-1, 1);
    }_**

  } else {
    options = this.options;
  }

  if (options.logging) {
    if (options.logging === true) {
      console.log('DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log');
      options.logging = console.log;
    }

    // second argument is sql-timings, when benchmarking option enabled
    if ((this.options.benchmark || options.benchmark) && options.logging === console.log) {
      args = [args[0] + ' Elapsed time: ' + args[1] + 'ms'];
    }
    **_if ((this.options.logOptions || options.logOptions) && options.logging === console.log) {
      args = [args[0] + '; options = ' + options];
    }_**
    options.logging.apply(null, args);
  }
};

I have added bold italics

**Comment by felixfbecker** [comment]
You need to log `options` as a dedicated argument

**Comment by contactakagrawal** [comment]
Sequelize.prototype.log = function() {
  var args = Utils.sliceArgs(arguments)
    , last = Utils._.last(args)
    , options;

  if (last && Utils._.isPlainObject(last) && last.hasOwnProperty('logging')) {
    options = last;

    // remove options from set of logged arguments
    if(!options.logOptions){
      args.splice(args.length-1, 1);
    }

  } else {
    options = this.options;
  }

  if (options.logging) {
    if (options.logging === true) {
      console.log('DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log');
      options.logging = console.log;
    }

    // second argument is sql-timings, when benchmarking option enabled
    if ((this.options.benchmark || options.benchmark) && options.logging === console.log) {
      args = [args[0] + ' Elapsed time: ' + args[1] + 'ms'];
    }
    // also add the options to the args if logOptions is true
    if ((this.options.logOptions || options.logOptions) && options.logging === console.log) {
      args.push(options);
    }
    options.logging.apply(null, args);
  }
};

I think this should be fine rather than having dedicated console.log just for options, kindly suggest

**Comment by contactakagrawal** [comment]
Sequelize.prototype.log = function() {
  var args = Utils.sliceArgs(arguments)
    , last = Utils._.last(args)
    , options;

  if (last && Utils._.isPlainObject(last) && last.hasOwnProperty('logging')) {
    options = last;

    // remove options from set of logged arguments
    if(!options.logOptions){
      args.splice(args.length-1, 1);
    }

  } else {
    options = this.options;
  }

  if (options.logging) {
    if (options.logging === true) {
      console.log('DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log');
      options.logging = console.log;
    }

    // second argument is sql-timings, when benchmarking option enabled
    if ((this.options.benchmark || options.benchmark) && options.logging === console.log) {
      args = [args[0] + ' Elapsed time: ' + args[1] + 'ms'];
      // also add the options to the args if logOptions is true
      if ((this.options.logOptions || options.logOptions)) {
        args.push(options);
      }
    }

    options.logging.apply(null, args);
  }
};

I think finally this should do the justice with console.log

**Comment by dskrvk** [comment]
A pattern I've seen in Unix utilities and some libraries is to provide a logLevel option - not directly translatable into traditional DEBUG, WARN, etc., but rather controlling the type of emitted log events from the author's standpoint. This seems like a better pattern than having a special flag that controls the logging of one special argument.

Example log levels in this case:
* normal / errors only - only log serious issues or deprecation warnings
* debug - log executed sql statements
* verbose - log everything; `options` would fall into this category

Even better would be to combine both approaches, thus allowing the user to provide a logger function for each category defined by library authors.

**Comment by papb** [comment]
I also believe that a `logOptions` flag would be much better than current behavior. I am having problems with it too.

@felixfbecker @contactakagrawal Looks like you stopped in the middle of it? Any particular reason?

@dskrvk That would be nice too, but having different log levels would be a bigger work, personally I would be happy with the idea by @felixfbecker for now.

**Comment by yogithesymbian** [comment]
> ```js
> const logger = new winston.Logger({
>   level: 'info',
>   transports: [
>     new (winston.transports.Console)(),
>     new (winston.transports.File)({filename: 'somefile.log'}),
>   ],
> });
> ```

sorry i could ask something , so in any controller we need to redifine the variable to use loggin ?

**Comment by ceilitellu777** [comment]
I just hacked this and it worked for me, am using winston as logger and it writes in all of the transports I defined :  

//before the db connection

Sequelize.prototype.log = (msg) => {
  logger.info(msg);
};

**Comment by ephys** [comment]
You don't need to overwrite `Sequelize.prototype.log`. You can set the `logging` option to a function when constructing the Sequelize instance. It will be called every time Sequelize wants to log something:

```ts
new Sequelize({
  logging: msg => {
    logger.info(msg);
  },
});
```
