### ISSUE TITLE
No way to customize created_at name in both model and database?

### ISSUE THREAD

**Issue by raxod502** [sequelize/sequelize#7822]
It appears that there is no way to create a model whose `created_at` attribute is named something different than the corresponding column in the database. By default, Sequelize expects the database column and the model attribute to both be called `created_at`. Providing the `createdAt` configuration option allows overriding the name, but it takes effect in both the model definition and the database column. There appears to be no way to specify *separate* names for the two.

See also https://github.com/sequelize/sequelize/issues/94#issuecomment-162024842.

**Comment by ox** [comment]
You can specify the attributes and the fields that you want each to use by setting the `field` for the attribute. For example:

```js
const Post = sequelize.define('post', {
  createdAt: {
    field: 'created_at',
    type: DATE,
  },
  updatedAt: {
    field: 'updated_at',
    type: DATE,
  },
}, {
  timestamps: true,
});

sequelize.sync({force: true, match: /_dev$/})
  .then(() => {
    return Post.create();
  })
  .then((post) => {
    console.log(post.get({plain: true}));
    /* #=>
    { id: 1,
      updatedAt: 2017-06-21T21:53:28.448Z,
      createdAt: 2017-06-21T21:53:28.448Z }
    */
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => sequelize.close());
```

and querying the database for the table shows the fields as underscored:

```
$ psql
psql (9.6.3, server 9.6.2)
Type "help" for help.

svrf_dev=# \d posts
                                    Table "public.posts"
   Column   |           Type           |                     Modifiers                      
------------+--------------------------+----------------------------------------------------
 id         | integer                  | not null default nextval('posts_id_seq'::regclass)
 created_at | timestamp with time zone | 
 updated_at | timestamp with time zone | 
Indexes:
    "posts_pkey" PRIMARY KEY, btree (id)
```

**Comment by raxod502** [comment]
Ah, I hadn't realized that if I specified `updatedAt` and `createdAt` attributes manually, then they would be automatically used by Sequelize. I guess one could also specify the `updatedAt` and `createdAt` options in order to make both the model attribute name and the database column name customizable. Thanks!

**Comment by codewithamitpatil** [comment]
to customize createdAt and updatedAt field do like this -
```
sequelize.define( 'product', {
        product_id: {
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER
        }
    }, {
        createdAt: "create_at",
        updatedAt: "updated_at"
    } );

```
