### ISSUE TITLE
Where's findAll and findOne?

### ISSUE THREAD

**Issue by palmtale** [sequelize/sequelize#7823]
I didn't found any docs or upgrade or changelog from v3 - v4 to show the model class has drop the method findAll and findOne.

But why I can use it in v3, and failed after installed v4.

**Comment by hesamd** [comment]
@palmtale your error should be somewhere else. I have version `4.1.0` and my `findOne` is working without any issue.

**Comment by ox** [comment]
How are you using the models? The [`findOne`](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findOne) and [`findAll`](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll) methods are still in the docs and usable.
