### ISSUE TITLE
Model.findOne query issue using $like %query%

### ISSUE THREAD

**Issue by tianyingchun** [sequelize/sequelize#7832]
_Thanks for wanting to report an issue you've found in Sequelize. Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_Note that it will be much easier for us to fix the issue if a test case that reproduces the problem is provided. Ideally this test case should not have any external dependencies. We understand that it is not always possible to reduce your code to a small test case, but we would appreciate to have as much data as possible. Thank you!_

_Github should only be used for feature requests and bugs - all questions belong on StackOverflow, Slack, or Google groups._

_This template is for submitting issues - if you want to submit a feature request you may skip this template_

## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_

```js
// matchEmail='dolamber@'
 return CustomerExtensionModel.findOne({
      where: { email: { $like: '%' + matchEmail + '%' } }
    });
```

## What do you expect to happen?

the sql string
```sql
SELECT `id`, `email`, `order_amount` AS `orderAmount`, `order_count` AS `orderCount`, `categories`, `tag
s`, `admin_comments` AS `adminComments`, `mailgun_failed_count` AS `mailgunFailedCount`, `mailgun_unsubscribe_count` AS `isUn
subscribeCount`, `mailgun_try_send_count` AS `mailgunTrySendCount`, `created_at`, `updated_at`, `customer_id` FROM `oz_custom
er_extension` AS `CustomerExtension` WHERE `CustomerExtension`.`email` LIKE '%dolamber@%' LIMIT 1;
```

it seems like %d has be escaped 

## What is actually happening?
 
```sql
 SELECT `id`, `email`, `order_amount` AS `orderAmount`, `order_count` AS `orderCount`, `categories`, `tag
s`, `admin_comments` AS `adminComments`, `mailgun_failed_count` AS `mailgunFailedCount`, `mailgun_unsubscribe_count` AS `isUn
subscribeCount`, `mailgun_try_send_count` AS `mailgunTrySendCount`, `created_at`, `updated_at`, `customer_id` FROM `oz_custom
er_extension` AS `CustomerExtension` WHERE `CustomerExtension`.`email` LIKE '**NaNolamber@%**' LIMIT 1;
```

__Dialect:__ mysql
__Database version__: mysql2@1.3.5 
__Sequelize version__: sequelize@4.1.0

**Comment by felixfbecker** [comment]
You are responsible for escaping your user input yourself, Sequelize can't handle this for you (it has no way to know which special characters are supposed to be escaped and which not)
