### ISSUE TITLE
Is there a way to disable SQL console logging on a specific table

### ISSUE THREAD

**Issue by eduardrock** [sequelize/sequelize#7834]
I know it can be disabled globally by setting "logging: false" on a new Sequelize() instance, but, Is there a way to disable it specifically on a table?

**Comment by felixfbecker** [comment]
no.

**Comment by eduardrock** [comment]
Could you consider this feature for a new release? I think it would be useful @felixfbecker

**Comment by felixfbecker** [comment]
If you come up with a good API and implement it, sure :)
There are some threads here regarding passing `options` and other metadata to the logging function.

**Comment by eduardrock** [comment]
I don't know how to implement it, that's why I'm asking to you that know the code of Sequelize at depth.
