### ISSUE TITLE
Wrong index being created

### ISSUE THREAD

**Issue by dvarnai** [sequelize/sequelize#7837]
## What you are doing?
I'm trying to add a composite unique index on an attribute + foreign key

```js
db.define('Meta', {
	key: {
		type: Sequelize.STRING,
		allowNull: false,
		unique: false
	},

    value: {
        type: Sequelize.STRING,
        allowNull: true
    },
}, {
	freezeTableName: true,
    indexes: [{
        unique: true,
        fields: ['key', 'UserId']
    }],
})
```

## What do you expect to happen?
Only a unique index on key+UserId

## What is actually happening?
A unique constraint is created on 'key'

```sql
CREATE TABLE IF NOT EXISTS `meta` 
  ( 
     `id`         INTEGER NOT NULL auto_increment, 
     `key`        VARCHAR(255) NOT NULL UNIQUE, 
     `value`      VARCHAR(255), 
     `createdat`  DATETIME NOT NULL, 
     `updatedat`  DATETIME NOT NULL, 
     `userid`     INTEGER, 
     `usermetaid` INTEGER, 
     UNIQUE `meta_key_unique` (`key`), 
     PRIMARY KEY (`id`), 
     FOREIGN KEY (`userid`) REFERENCES `user` (`id`) ON DELETE SET NULL ON 
     UPDATE CASCADE, 
     FOREIGN KEY (`usermetaid`) REFERENCES `user` (`id`) ON DELETE SET NULL ON 
     UPDATE CASCADE 
  ) 
engine=innodb 
DEFAULT charset=utf8 
COLLATE utf8_general_ci; 
ALTER TABLE `Meta` ADD UNIQUE INDEX `meta_key__user_id` (`key`, `UserId`)
```

__Dialect:__ mysql
__Database version:__ 5.7.18
__Sequelize version:__ 4.2.0

**Comment by dvarnai** [comment]
After further investigation I found that in lib/model.js all rawAttributes listed in a composite unique index got unique set, UserId didn't get it as it was a foreign key. As a nasty workaround I came up with this:

```js
module.exports = db.define('Meta', {
    key: {
	    type: Sequelize.STRING,
	    allowNull: false,
	    unique: 'Unique_Meta_UserId_Key'
    },

    value: {
	    type: Sequelize.STRING,
	    allowNull: true
    },

    UserId: {
	    type: Sequelize.INTEGER,
	    unique: 'Unique_Meta_UserId_Key'
    }
}, {
	freezeTableName: true
});
```
Interestingly if I used indexes, UserId got a unique constraint too and the composite unique index was only added later by Sequelize. While the above works, I shouldn't have to define an auto-generated foreign key in the model

**Comment by Matheus28** [comment]
I'm also experiencing this issue. It also seems to happen in postgres.

**Comment by toddhickerson** [comment]
Also experiencing same issue in MySQL 5.7. This is preventing us from upgrading to Sequelize 4.0.

**Comment by dvarnai** [comment]
i think the issue is caused by the following piece of code in lib/model.js:

```js
          if (this.rawAttributes[fieldName]) {
            this.rawAttributes[fieldName].unique = this.attributes[fieldName].unique = index.name || index.unique;
          }
```

basically unless you name the index manually, it will just set unique to true on the fields instead of setting a string to make them a composite index. i havent got a chance to try it yet but i have a feeling foreign keys are not in rawAttributes either, so even if an index name was autogenerated it still wouldnt fully work

**Comment by harshithkashyap** [comment]
This has been fixed in the latest release - https://github.com/sequelize/sequelize/releases/tag/v4.2.1
