### ISSUE TITLE
Property assignment not working inside hook for PK

### ISSUE THREAD

**Issue by javiertury** [sequelize/sequelize#7838]
I'm trying to create hooks as documented [here](http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks). The problem is that the hook fails to assign a value to the instance property. It's a very simple assignment but doesn't even last to the next command.

It looks familiar to #2273 and I'm using sequelize 4.2

## What you are doing?

```js
module.exports = function(sequelize, DataTypes) {
  var UserEmail = sequelize.define('UserEmail', {
    email: {
      type: DataTypes.STRING(254),
      field: 'email',
      primaryKey: true,
    },
    user: {
      type: DataTypes.UUID,
      field: 'user',
    },
  },{
    timestamps: false,
    underscored: true,
    freezeTableName: true,
    tableName: 'user_email',
  });

  UserEmail.hook('afterValidate', (instance) => {
    instance.email = 'test@test.com';
    console.log(instance.email);
    // original@address.com
  });

  return UserEmail;
};
```
Now when I create a new UserEmail with email `original@address.com`, the console.log command still logs `original@address.com` even though it was replaced with `test@test.com`. In reality the model UserEmail is associated with User, but the bug is reproducible even after removing the association.

EDIT: The error happens only if `primaryKey: true` is set for the email field.

__Dialect:__ postgres
__Database version:__ 10
__Sequelize version:__ 4.2

**Comment by javiertury** [comment]
It's extrange, using `instance.setDataValue('email', 'test@test.com')` works as expected.

**Comment by javiertury** [comment]
After debugging I found the culprit [here](https://github.com/sequelize/sequelize/blob/4313a49409689f4ed5de6abfa8c3307cce983d26/lib/model.js#L3270)

In `lib/model.js`
```js
class Model{
  ...
  set(key, value, options) {
    ...
    // If attempting to set primary key and primary key is already defined, return
    if (this.constructor._hasPrimaryKeys && originalValue && this.constructor._isPrimaryKey(key)) {
      return this;
    }
    ...
  }
  ...
}
```

The problem is that are primary keys can't ever be modified after being set. You may wonder why I wanted to validate and modify a primary key during hooks. The reason is that I want to create a table where there is a unique and not null(PK) email address for each user. More over I want first to canonize the address so that user@domain.com and user@DoMaIn.CoM are both canonized to user@domain.com.

Why don't you use user UUID as PK? Because users can have primary and secondary email addresses. This UserEmail table is a relationship model, there is another model named User that stores username and pass.

Workaround: I can get await substituting `primaryKey: true` with
```js
unique: true,
allowNull: false,
```

I understand that my use of primary key in this context is not the typical use of a PK as a UUID or an INT/BIGINT. It's you that have to judge whether this use case merits to be accepted. Regardless of your decision, the documentation about hooks should remember/warn users that primary keys are not modifiable.

**Comment by eric-radiant** [comment]
I seem to have run into this (or similar) issue today, fairly annoying.
