### ISSUE TITLE
how can i use sequelize.fn('ifnull') on two columns from different tables

### ISSUE THREAD

**Issue by pangz1** [sequelize/sequelize#7839]
here is the sql:

`SELECT IFNULL(A.price, B.price) FROM table1 B INNER JOIN (SELECT price, product_id FROM table2 WHERE user_id=xxx) A ON A.product_id=B.product_id`

how can I get the same results with sequelize

I use mysql

**Comment by ox** [comment]
Have you tried using [raw queries](http://docs.sequelizejs.com/manual/tutorial/raw-queries.html)? It looks like it will solve your problem by letting you run arbitrary SQL:

```sql
sequelize.query('SELECT IFNULL(A.price, B.price) FROM table1 B INNER JOIN (SELECT price, product_id FROM table2 WHERE user_id=xxx) A ON A.product_id=B.product_id')
  .then(([results, metadata]) => {
    /* work on `results` here */
  });
```

**OR** if you have models defined for `table1` and `table2`, you could accomplish this with [eager loading](http://docs.sequelizejs.com/manual/tutorial/models-usage.html#eager-loading) and [query attributes](http://docs.sequelizejs.com/manual/tutorial/querying.html#attributes). This would be a `findAll` on `table1` with an eager load of the `table2` model, where you add an `attributes` set to something like:

```js
const table1 = sequelize.define('table1', { /* attributes */ });
const table2 = sequelize.define('table2', { /* attributes */ });

table1.hasMany(table2, {foreignKey: 'product_id', sourceKey: 'product_id'});

table1.findAll({
  attributes: [[sequelize.fn('IFNULL', sequelize.col('A.price'), sequelize.col('B.price')]],
  include: [table2],
});
```

I'm not 100% certain but you can log the SQL statements being run to see how sequelize is interpreting your request. I hope this helps somehow!

**Comment by pangz1** [comment]
I do tried raw queries, but I also need orther columns from a third table, it becomes  complicated, in the sequelize way, I can simply eager load it. 
This is exactly what I was looking for, thank you so much.

**Comment by tbyoran** [comment]
```javascript
const user = await db.User.findOne({
    where: {
      [email ? 'email' : 'phoneNumber']: email || phoneNumber,
      password: md5(password),
    },
  });
```
