### ISSUE TITLE
[Question] How I can get query result rows count?

### ISSUE THREAD

**Issue by mtvspec** [sequelize/sequelize#7841]
I know how to get count with `findAndCountAll` model method, but I can't find it in `findById` or another model methods. And why `findAndCountAll` method makes two separate queries to database (postgres) to fetch count and rows? Thank you for any response.

**Comment by knoxcard** [comment]
Just get the length of returned results...

```
    shop.findByID(shop_id, fields, function(ret_shop) {
       if(ret_shop)
          var num_results = ret_shop.length
    })

```
findByID only returns one record though, not sure what you are trying to accomplish.

**Comment by felixfbecker** [comment]
`findById` only returns a single instance or `null`

**Comment by felixfbecker** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](http://sequelize-slack.herokuapp.com/).
