### ISSUE TITLE
v4 updates | Error: No Sequelize Instance Passed

### ISSUE THREAD

**Issue by peterb0yd** [sequelize/sequelize#7842]
As per this part of the new updates to v4:

- Instances (database rows) are now instances of the model, instead of being an instance of a separate class. This means you can replace `User.build()` with `new User()` and `sequelize.define(attributes, options)` with

```
class User extends Sequelize.Model {}
User.init(attributes, options)

```

Now, how do I pass the sequelize instance to the class?

I've tried requiring it above the class instantiation  `var sequelize = require(path/to/db-file).sequelize`  and passing it by doing:

`User.init({ attributes: { ... }}, { sequelize, hooks: { ... });`

in the "options" object in the `User.init` function, but that still gives me this error.

I've tried referencing the class from my DB file multiple ways to no avail:

1. `db.User = sequelize.import(__dirname + '/user.js');`

 - I figured this method would pass along the sequelize instance on it's own, no?

2.  `db.User = require('./user.js');`

Very confused, really appreciate any help. Thanks.

**Comment by peterb0yd** [comment]
I've given up on the method above and now trying the old way of doing things and am getting some success, but I'm still failing in the instance methods

```
// user.js

module.exports = (sequelize, DataTypes) => {
  var User = sequelize.define('user', {
    attributes ....
  }, { 
    hooks: { 
      afterSave(user, options) {
        user.testFunction();
      }
    }
  });

  // Instance methods
  User.prototype.testFunction = () => {
    this.firstName = "John";
  }

  // Class methods
  User.anotherTestFunction = () => {
    User.findOne().then(() => doSomething());
  }

  return User;
}


// index.js
var sequelize;
sequelize = new Sequelize(config.DATABASE_URL);
db.User = sequelize.import(__dirname + '/user.js');
module.exports = db;


// usersController.js
var db = require('../path/to/db');
function create_post_function = (req, res) => {
  var body = getBody();
  db.User.create(body).then(user => respondSuccess());
}
```

Now, everything in this example works perfectly EXCEPT the instance method!!! 

I'm continually getting `TypeError: Cannot set property 'firstName' of undefined`

For some reason, it's not applying the instance method to the sequelize Model. Very strange, but I'm probably doing something noticeably wrong and not seeing it. 

Really appreciate any help!

**Comment by peterb0yd** [comment]
Figured it out thanks to [this majestic person](https://stackoverflow.com/a/44752012/3386826).

You can't use arrow functions for the instance methods. BTW - the method in my second comment is working, not the one in the first comment.

**Comment by frankthelen** [comment]
I had the same problem when I first tried to use [the new way of writing models by subclassing Sequelize.Model](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html#new-features): "Error: No Sequelize Instance Passed". This is how I solved it. The trick is to pass in the `sequelize` instance just like you did before. The rest of the code, e.g., `index.js` (see above), stayed the same.

File `User.js`
```js
const Sequelize = require('sequelize');

class User extends Sequelize.Model {
  constructor(...args) {
    super(...args);
  }
  getName() { // instance method
  }
}

const attributes = { /* ... */ };

const options = { /* ... */ };

module.exports = sequelize => User.init(attributes, { ...options, sequelize });
```

**Comment by hyoretsu** [comment]
In my case it was a sorta dependency loop case. I was syncing the models (which required the instance to be created) in the same file where I created the instance.
