### ISSUE TITLE
Sort a collection (containing belongsTo) with a primary key on MSSQL

### ISSUE THREAD

**Issue by lucasscariot** [sequelize/sequelize#7851]
I have a collection whose model has an association. The primarykey of this collection is constantly added as a sorting parameter on find query.

```js
var Model = sequelize.define('ProductCategory', {
    ProductCategoryID: {
        type: DataTypes.INTEGER,
        primaryKey: true
    },
    Name: { type: DataTypes.STRING },
}, {
    classMethods: {
        associate: () => {
            Model.hasMany(models.Product, { foreignKey: 'ProductCategoryID' });
        }
    }
}
```

## What do you expect to happen?
I want to sort the collection by the `ProductCategoryID` field.

## What is actually happening?
But the query crash because the field is added two times in the order parameters.

### Query
`Executing (default): SELECT [Product].[ProductID], [Product].[Name], [Product].[ProductNumber], [Product].[Color], [Product].[Size], [Product].[Weight], [Product].[ProductCategoryID], [Product].[ProductModelID], [Product].[SellStartDate], [Product].[SellEndDate], [Product].[DiscontinuedDate], [Product].[ThumbnailPhotoFileName], [Product].[rowguid], [Product].[ModifiedDate], [ProductCategory].[ProductCategoryID] AS [ProductCategory.ProductCategoryID], [ProductCategory].[ParentProductCategoryID] AS [ProductCategory.ParentProductCategoryID], [ProductCategory].[Name] AS [ProductCategory.Name], [ProductCategory].[rowguid] AS [ProductCategory.rowguid], [ProductCategory].[ModifiedDate] AS [ProductCategory.ModifiedDate] FROM [SalesLT].[Product] AS [Product] LEFT OUTER JOIN [SalesLT].[ProductCategory] AS [ProductCategory] ON [Product].[ProductCategoryID] = [ProductCategory].[ProductCategoryID] ORDER BY [Product].[ProductID] DESC, [ProductID] OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;`
**ORDER BY [Product].[ProductID] DESC, [ProductID]**

### Console error
SequelizeBaseError: A column has been specified more than once in the order by list. Columns in the order by list must be unique.

__Dialect:__ mssql
__Sequelize version:__ 3.29.0

**Comment by lucasscariot** [comment]
Working with sequelize `4.4.2`

**Comment by arnaudbesnier** [comment]
Probably due to this old change...
https://github.com/sequelize/sequelize/commit/6e13407aa#diff-7326c670d3f83779ae65be6a1e992deaR1180
