### ISSUE TITLE
bulkCreate with validate and explicit timestamp fields fails with notNull violation

### ISSUE THREAD

**Issue by seally1186** [sequelize/sequelize#7861]
## What you are doing?
It seems that, when a model has a timestamp field explicitly defined (not auto-generated), bulkCreate validations happen before the field is filled, leading to a notNull violation.

```js
const Test = sequelize.define("Test", {
  createdAt: { type: DataTypes.DATE, allowNull: false },
  value: { type: DataTypes.STRING, allowNull: false }
});

Test.sync({force: true}).then(function() {
  return Test.bulkCreate([{value: "foo"}], {validate: true});
}).then(function() {
  console.log("Success");
}, function(err) {
  console.log(err[0]);
});
```

## What is actually happening?
```
SequelizeValidationError: notNull Violation: createdAt cannot be null
```

This issue doesn't happen if `validate` is false, or using `create`. It doesn't affect auto-generated timestamp fields (`updatedAt` in this case).

(I believe this issue is related to #5541, since internally adding an association calls bulkCreate.

__Dialect:__ any (tested on mysql)
__Database version:__ MariaDB 10.2
__Sequelize version:__ 4.2.0

**Comment by dpelatrix** [comment]
Same happened here, with a Pg DB. Sequelize: 4.2.1

**Comment by frederikhors** [comment]
Is this maybe related to this? https://github.com/sequelize/sequelize/issues/9767
