### ISSUE TITLE
Misuse of ESDoc @property tag in DataTypes

### ISSUE THREAD

**Issue by rpcarver** [sequelize/sequelize#7872]
## What you are doing?
WebStorm (and other JetBrains IDEs) inspection parses JSDoc/ESDoc comments for code completion and validation via inspection.   The following representative use of the ESDoc comments are taking advantage of non-standard use of the @property tag to get the documentation to look pretty (But its the same for ALL the DataTypes:

 * @property {function(length=255: integer)} INTEGER A 32 bit integer.

{function(length=255: integer)} is NOT a valid javascript datatype....

## What do you expect to happen?
Standard use of ESDoc Tags so downstream consumers are not affected

## What is actually happening?
Models show inspection warnings in WebStorm.

From the ESDoc Documentation:
@property <type> <name> [description]
...
   * @property {number} foo this is description.

__Dialect:__ any
__Database version:__ N/A
__Sequelize version:__ 4.2.1

**Comment by felixfbecker** [comment]
> {function(length=255: integer)} is NOT a valid javascript datatype....

What exactly is wrong about this datatype? What spec are you basing this assumption on? I don't see a reason why it shouldn't?

See the ESDoc docs:

```js
/**
 * @param {function(foo: number, bar: string): boolean} param - this is function param.
 */
function myFunc(param){...}
```
https://esdoc.org/manual/usage/tags.html#function

```js
/**
 * @param {number} [param=10] - this is default param.
 */
function myFunc(param){...}
```
https://esdoc.org/manual/usage/tags.html#optional-and-default

It is a combination of the function type syntax and the syntax for default values. ESDoc doesn't seem to have a problem with it.
