### ISSUE TITLE
Is there any way to disable SQL logging temporary

### ISSUE THREAD

**Issue by raphaelsoul** [sequelize/sequelize#7873]
hi there! I'am using sequelize to do stuff with mysql. My App has a task to synchronize data periodly and then updates a data table, which contains at least 20,000 rows at once. Surely those SQL will also be logged(I wrote raw SQLs into `profiles.log`). This log file became 200mb in few days. 

Is there some way to tempory disable Sql logging?

**Comment by harshithkashyap** [comment]
@raphaelsoul You can pass `{ logging: false }` as options to the sequelize methods where you do not need queries to be logged. You could also pass a function and skip some queries.
```
{
  logging: sql => {
     if (someCondition) {
          //Log the query
     }
  }
}
```
