### ISSUE TITLE
Sequelize 4.0: Custom instance method for all models

### ISSUE THREAD

**Issue by Joanne16** [sequelize/sequelize#7877]
Hi, how do we create custom instance methods to be applied/inherited by all models with sequelize 4.2? In sequelize 3 we used to have an "instanceMethods: {custom1: function (){} }" in the "define" section of a main model which was extended to all other models. How do we achieve the same behaviour with sequelize 4.0?

**Comment by yonjah** [comment]
This has been discussed on #7804
I've created a pull request that will allow you to do that by passing a custom class to `options.Model`
