### ISSUE TITLE
Sequelize 4.0: Remove timezone on database options

### ISSUE THREAD

**Issue by Joanne16** [sequelize/sequelize#7879]
Hi, how do we remove/bypass the timezone on sequelize options (dialect mysql) ? With version 3.0 setting timezone: '' did the trick and the dates where not modified. With sequelize 4.0, setting timezone to blank string throws an error... What option can be used so that the server date is used without any timezone applied ?

Thanks

**Comment by Shadowman4205** [comment]
@Joanne16  Did you find solution for this?

**Comment by Joanne16** [comment]
Hi @Shadowman4205 , the solution I found is to put a timezone in the options, else the wrong time is given.

**Comment by Shadowman4205** [comment]
@Joanne16  That's a pity, i will stuck for previous version for a while cause i do not want timezone at all. Cause of that [issue:7930](https://github.com/sequelize/sequelize/issues/7930)

**Comment by Joanne16** [comment]
@Shadowman4205 Yep. I hope there will be another way of disabling the timezone option. As putting the value as '+00:00' (the default) still modifies the dates returned from queries.

**Comment by cladjules** [comment]
that may look ugly but, in sequelize/lib/data-types.js, you can replace the method:

```
DATE.prototype._stringify = function _stringify(date, options) {
  date = this._applyTimezone(date, options);

  // Z here means current timezone, _not_ UTC
  // return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
  return date.format('YYYY-MM-DD HH:mm:ss.SSS');
};
```

**Comment by Shadowman4205** [comment]
So i have to go into node-modules, data-types.js, and modify it or fork this lib? Yes this is messy for simple option. :/

**Comment by cladjules** [comment]
I copied the file locally, applied the change and I did a postinstall script in package.json which copies the file into node_modules, that will run automatically after every npm install.

In package.json:
```
  "scripts": {
    "postinstall": "./fixme.sh",
```

fixme.sh
```
#!/bin/sh
cp data-types.js ./node_modules/sequelize/lib/data-types.js
```

**Comment by dlredden** [comment]
I'm so thankful to @cladjules for his solution to this problem. I thought I'd share how I solved this in my singleton file. I like this a little better because the change is still ubiquitous in my app and I didn't have to modify a node_modules file.

In db.js:
```javascript
import Sequelize from 'sequelize';
import settings from '../settings';

// Override timezone formatting
Sequelize.DATE.prototype._stringify = function _stringify(date, options) {
  date = this._applyTimezone(date, options);

  // Z here means current timezone, _not_ UTC
  // return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
  return date.format('YYYY-MM-DD HH:mm:ss.SSS');
};

let sequelize;

if (!sequelize) {
  sequelize = new Sequelize(
    settings.database.db_name,
    settings.database.db_user,
    settings.database.db_password,
    {
      host: settings.database.host,
      dialect: 'mssql',
    }
  );
}

export default sequelize;
```

**Comment by cladjules** [comment]
@dlredden Thanks, that's definitely a better approach :)

**Comment by Benew** [comment]
This is still an issue as no fix outthere ! We should not have to modify Sequelize's DataTypes prototype !

**Comment by welderprog** [comment]
Em 2019 estou com esse problema para escrever no banco (post, put) 
Para escrita corre no SQL Server "yyyy-mm-dd hh:mm:ss)
SQL Server, Tedious, Sequilize

**Comment by edrpls** [comment]
On the latest version I am passing the date as `Date.parse(date)` and it works just fine.

**Comment by aat2703** [comment]
I don't understand why Sequelize wants to tamper with dates passed to for example FindOptions... 

In most cases timezone is set in the application level (not fixed in Sequelize config) or best practice uses UTC?

**Comment by kippllo** [comment]
It is very surprising that I am still having this problem in sequelize v5.21.13!
Am thankful for the easy solutions here.

And I would like to offer my remix of the fix.
Here is a quick fix at import time with very little overhead:

```
const { Sequelize, DataTypes } = require('sequelize');
DataTypes.DATE.prototype._stringify = function(date, options) {
    date = this._applyTimezone(date, options);
    return date.format('YYYY-MM-DD HH:mm:ss.SSS');
}.bind(DataTypes.DATE.prototype);
```

The only issue with this fix is that you'll need it in every file using "DataTypes".
But if you only use it in one file, like I am, it is pretty nice!

**Comment by avalladaresm** [comment]
I have been stuck on this since yesterday, as the previous solutions, yours @kippllo worked nicely.

**Comment by LiamKarlMitchell** [comment]
Still a problem for MSSQL it seems.

**Comment by rishat5081** [comment]
> I'm so thankful to @cladjules for his solution to this problem. I thought I'd share how I solved this in my singleton file. I like this a little better because the change is still ubiquitous in my app and I didn't have to modify a node_modules file.
> 
> In db.js:
> 
> ```js
> import Sequelize from 'sequelize';
> import settings from '../settings';
> 
> // Override timezone formatting
> Sequelize.DATE.prototype._stringify = function _stringify(date, options) {
>   date = this._applyTimezone(date, options);
> 
>   // Z here means current timezone, _not_ UTC
>   // return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
>   return date.format('YYYY-MM-DD HH:mm:ss.SSS');
> };
> 
> let sequelize;
> 
> if (!sequelize) {
>   sequelize = new Sequelize(
>     settings.database.db_name,
>     settings.database.db_user,
>     settings.database.db_password,
>     {
>       host: settings.database.host,
>       dialect: 'mssql',
>     }
>   );
> }
> 
> export default sequelize;
> ```

I have tried to change in the /lib/date_type file  but still, it is printing the time zone like 2021-02-11T08:31:59.000Z I don't want 000Z at the end

**Comment by befabry** [comment]
> that may look ugly but, in sequelize/lib/data-types.js, you can replace the method:
> 
> ```
> DATE.prototype._stringify = function _stringify(date, options) {
>   date = this._applyTimezone(date, options);
> 
>   // Z here means current timezone, _not_ UTC
>   // return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
>   return date.format('YYYY-MM-DD HH:mm:ss.SSS');
> };
> ```

@cladjules : In case you were wondering, this piece of code hack is still used in 2022 in a project with new technologies using an legacy DB we can't get rid off yet

**Comment by ephys** [comment]
I'm trying to figure out what the issue being talked about in this thread is but I can't. I don't see anything wrong with how the dates are stringified: https://github.com/sequelize/sequelize/blob/main/test/unit/sql/insert.test.js#L108

**Comment by matthews314** [comment]
> I'm trying to figure out what the issue being talked about in this thread is but I can't. I don't see anything wrong with how the dates are stringified: https://github.com/sequelize/sequelize/blob/main/test/unit/sql/insert.test.js#L108

I'm having the same issue people are reporting on this thread right now.

I created a modeland wanted to add the `createdAt` field manually, since I'm disabling the automatic one Sequelize provides by default.

I'm using TypeScript, so I wrote:

```
export class ValidationCode extends Model<InferAttributes<ValidationCode>, InferCreationAttributes<ValidationCode>> {
  // more declarations here
  declare createdAt: Date;
}

export function createValidationCodesModel() {
  ValidationCode.init(
    {
      // more columns defined here
      createdAt: {
        type: DataTypes.DATE,
        allowNull: false,
      },
    },
    {
      // my options, irrelevant now
    }
  );
}
```

In another file, inside a function, I create an instance of the model:

```
ValidationCode.create({
  // more parameters set here, as usual
  createdAt: new Date()
});
```

This causes the transaction to roll back, since it complains about the date, that is formatted like this:

`2022-12-13 18:44:53.574 +00:00`

By adding the flollowing lines of code just before I instantiate Sequelize, everything works fine:

```
DataTypes.DATE.prototype._stringify = function (date: Date, options: { timezone?: string | undefined }) {
  return this._applyTimezone(date, options).format('YYYY-MM-DD HH:mm:ss.SSS')
}
```

So this is definitely still happening. Datetime on Microsoft SQL Server won't accept the final `+00:00` if the column type is set to `datetime`, but Sequelize always adds them when processing a Javascript `Date`.

My Sequelize version is 6.26.0.

**Comment by aat2703** [comment]
After all this time. My conclusion is it's amazing to avoid using ORMs. Write you're abstraction and implement your adapter as a repository. Way too many headaches using weird ORM's :-)

**Comment by befabry** [comment]
> I'm trying to figure out what the issue being talked about in this thread is but I can't. I don't see anything wrong with how the dates are stringified: https://github.com/sequelize/sequelize/blob/main/test/unit/sql/insert.test.js#L108

@ephys I'll try to explain my problem as best as I can without giving too much info as I can't legally.

The image :

    sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest`

We have to work with a legacy sql server database (sql server 2017, that probably was upgraded from a way older version), the field appears as "d_d_date" and I don't know what it is. It's not a datetime or datetime2. If I alter the field as a datetime or datetime2, no problem, I can query and go on with my day. But I can't do it, a legacy app is also using that database, no idea about the different side effects. It's said it's trash and we'll be getting rid off in the coming year or years, the client don't want to bother updating it. We receive an anonymized DB dump that we load on the database. It's not created by us. We cannot alter the database.

It isn't a problem when reading the date from the database, but when searching on it, it's where it breaks. The stored field is a "d_d_date". I don't know what the f*** that is.

If I look up the fields in my database with :

    SELECT c.name,
       c.max_length,
       c.precision,
       c.scale,
       c.is_nullable,
       t.name
    FROM sys.columns c
    JOIN sys.types   t
      ON c.user_type_id = t.user_type_id
    WHERE c.object_id    = Object_id('DB.table');

It returns me :

![image](https://user-images.githubusercontent.com/17452648/207603472-b1bd69ab-b422-4846-8bdf-e708ad019816.png)

Where datetime I altered myself. The date types are the "d_d_date". No idea wtf that is.

For example, a query that's not working. The default output is as following :

    SELECT
        [id] AS [id]
        -- removed fields for anonymity
    FROM
        [DB].[Table] AS [Table]
    WHERE
        [Table].[date_timestamp] >= N'2010-11-01 00:00:00.000 +00:00';

But my database doesn't support the timezone notation (d_d_date) field. By removing the timezone, it works.

    SELECT
        [id] AS [id]
        -- removed fields for anonymity
    FROM
        [DB].[Table] AS [Table]
    WHERE
        [Table].[date_timestamp] >= N'2010-11-01 00:00:00.000';

Thus I have to override the method for it to work.

I hope it's clear enough, I gave you as much info as I can. If you have question, do not hesitate.

**Comment by dlredden** [comment]
> > that may look ugly but, in sequelize/lib/data-types.js, you can replace the method:
> > ```
> > DATE.prototype._stringify = function _stringify(date, options) {
> >   date = this._applyTimezone(date, options);
> > 
> >   // Z here means current timezone, _not_ UTC
> >   // return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
> >   return date.format('YYYY-MM-DD HH:mm:ss.SSS');
> > };
> > ```
> 
> @cladjules : In case you were wondering, this piece of code hack is still used in 2022 in a project with new technologies using an legacy DB we can't get rid off yet. It's been injected in a Nest v9 app in the app.module and it's picked in any module. I mixed it with @dlredden code and it's working

We are still patching Sequelize for this but we've changed how. We now are using [patch-package](https://github.com/ds300/patch-package) which is much more elegant and extendible if you end up with more than one package that needs a little help working in your environment.

**Comment by ephys** [comment]
@matthews314 @befabry thank you for all that information :)

It seems that the issue both of you have is that the data type you're using in your database is not datetimeoffset, which is what `DataTypes.DATE` uses.

That's not something we can change, but there are solutions:

- it's possible to [create your own data type](https://sequelize.org/docs/v6/other-topics/extending-data-types/). It's a bit awkward to do in V6 but it's been completely redesigned in the upcoming V7 alpha. You'll be able to easily extend an existing Data type class and replace the formatting too
 That's a more future proof solution than patching imo
- We're also working on [adding more date related data types](https://github.com/sequelize/sequelize/issues/14295)

I think these two options should be able to cover your needs

**Comment by matthews314** [comment]
@ephys Thanks for the answer! Last night I did some digging into the codebase and the docs and found the huge changes you made to the DataType for V7, including the docs for the custom data types. I guess I would have deserved an invite to RTFM 😄 

I'm looking forward for V7 to become a stable version. Thanks again and keep up the good work! 👍🏻
