### ISSUE TITLE
pool connection never destroy after idle milliseconds

### ISSUE THREAD

**Issue by fourcels** [sequelize/sequelize#7882]
## What you are doing?

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize($mysqlUri, {
  pool: {
    max: 5,
    min: 0,
    idle: 10000
  }
})

sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });
```

## What do you expect to happen?
pool connection  should be destroyed after idle(10000 milliseconds) 

## What is actually happening?
pool connection  hadn't destroyed after idle(10000 milliseconds) 

__Dialect:__ mysql 
__Database version:
__Sequelize version:4.2.1

## ps
I had found a option __evictionRunIntervalMillis__ in [generic-pool](https://github.com/coopernurse/node-pool)
__evictionRunIntervalMillis__: How often to run eviction checks. Default: 0 (does not run).
sequelize options need add this option to control idle connection destroy

**Comment by RayneHwang** [comment]
Plz check if my [pullrequest](https://github.com/sequelize/sequelize/pull/7922) fixed you problem

**Comment by swordfish444** [comment]
@RayneHwang Please see the comments on your PR. Once you've resolved the formatting error, lets get this tested and scheduled for release.

**Comment by sushantdhiman** [comment]
#7924
