### ISSUE TITLE
[Sequelize v3.30.4] Where condition on Multiple Scopes not merging

### ISSUE THREAD

**Issue by radAragon** [sequelize/sequelize#7883]
Hi guys, I think there's a problem using multiple Scopes with overlapping Where conditions. Sequelize seems to not be able to concatenate Where clausules on same attribute.

Here's a sample model:

```js
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Permission', {
    registryStatus: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    name: {
      type: DataTypes.STRING(45),
      allowNull: false
    },
    description: DataTypes.STRING,
    objectTypeId: DataTypes.INTEGER,
    relatedProfile: DataTypes.STRING
  }, {
    scopes: {
      manage: {
        where: {
          registryStatus: 0,
          name: {
            $in: ['manage', 'supervisor']
          }
        }
      }
      createActivity: {
        where: {
          registryStatus: 0,
          name: {
            $in: ['createActivity']
          }
        }
      }
    }
  })
}
```

So I use the below query with scopes:

```js
return model.Permission.scope('createActivity', 'manage').findAll()
```

The raw query excerpt looks like:

```sql
SELECT ...
FROM `Permission`
WHERE
    `Permission`.`registryStatus` = 0
    AND `Permission`.`name` IN ('manage', 'supervisor');
```

Here's the problem: Where clausule `name IN ()` only recognizes 'manage' scope ignoring 'createActivity'.

I expected Sequelize to concatenate the `name` options resulting in a big where clausule `name IN (all 3 options)`.

**Comment by felixfbecker** [comment]
Not sure if I agree. a `WHERE` clause that says `name` must be _exactly_ `createActivity` and a `WHERE` clause that says `name` can be either `manage` or `supervisor` contradict each other, they are two different operators applied to the same attribute. It wouldn't be clear to me whether they should be merged with OR semantics (like you suggest) or with an AND. Right now the latter just overrides the former.

**Comment by radAragon** [comment]
I'm trying to concatenate scope clausules, they are not conflicting because the field isn't binary. I'll replace the main example with the `$in ['createActivity']` for clarity.
