### ISSUE TITLE
Pass parameters to findAll and use it in custom getter

### ISSUE THREAD

**Issue by fcioffi** [sequelize/sequelize#7886]
I world like to generate a virtual field in my model using some data from instance and some data using a value in express request.

Is possible to pass a parameter in options of findAll and use it in custom getter of instance?

Thanks for your help,
Francesco

**Comment by felixfbecker** [comment]
A getter does not receive any parameters. If you want parameters, you need a custom method.

**Comment by fcioffi** [comment]
Ok, I know!

I have resolved using CLS. I don't want pass parameter to getter, i would like to pass parameter in options in findAll and use it (as context) in getter.


Thanks.

**Comment by rdshoep** [comment]
@fcioffi How did you resolve? 

Can you show you code? Thanks

**Comment by fcioffi** [comment]
Hi @rdshoep,

i resolved with CLS but then I re-changed implementation.

Using CLS, I can access to variable globally but it was very strong.

Thanks,
FC

**Comment by rdshoep** [comment]
Hi @fcioffi,
Thanks for your reply.

I use custom getter and setter for id attribute, then I have two problems:
1. I can't use model instance's update method, because it will use the converted value to query
2. I have to convert each id attr, then pass to findAll... methods.

Do you have some ideas? Thanks

**Comment by fcioffi** [comment]
Hi @rdshoep,

can you use an idAlias with custome getter so you can untouch id, for your purpose?

**Comment by rdshoep** [comment]
Hi @fcioffi,

Yeah,  this way can resolve the problems except a redundant field.  And i need to target the idAlias for the other tables's foreign key.

I just want to convert the auto increment id to the converted outer key. I want find a simple way to achieve.

Thank you.

**Comment by fcioffi** [comment]
Hi,

I believe you can achieve this in a more reliable way :).

Why do you have this need? Using sequelize I think, you must design your db simple and thinking about sequelize features.

Thanks,
Framcesco

**Comment by rdshoep** [comment]
Hi @fcioffi ,

I have many autoIncrement primary id, and use [hashids](https://github.com/ivanakimov/hashids.js) module to convert the numeric id. Then, the customer can't know the records count easily.

I need complete the converter. I don't want to expose the converter to each data layers except the db layer. And, I have done this in the db source layer.

I quite agree with you about the solving direction. So I want to find the solution that the converter be achieved in the sequelize self level.

Thank you.

**Comment by kuznetsov-online** [comment]
Hello @fcioffi!

Have can I do like this?

const Test = sequelize.define('test', {
  name_en: Sequelize.STRING,
  name_ru: Sequelize.STRING,
  name: {
    type: Sequelize.VIRTUAL,
    get: function () {
      // ??? how can I get locale from context?
      const locale = ...
      return this.getDataValue(`name_${locale}`)
    },
  },

// ???
Test.findAll({context: {locale: 'en'}})

**Comment by kuznetsov-online** [comment]
I think this is solution:
```javascript
const Test = sequelize.define('test', {
  name_en: Sequelize.STRING,
  name_ru: Sequelize.STRING,
  name: {
    type: Sequelize.VIRTUAL,
    get: function (_, {locale}) {
      return this.getDataValue(`name_${locale}`)
    },
  },

Test.findAll.then(docs => docs.map(doc => doc.get({locale: 'en'})))
```
