### ISSUE TITLE
Sequelize tries to select a missing column(id) of a join table on invoking the model.Add() method using BelongsToMany

### ISSUE THREAD

**Issue by kristijan-ujevic** [sequelize/sequelize#7891]
## What you are doing?

I'm trying to add a new role to my user which can have many roles by using user.addRoles(role).

My models:
```js
module.exports = function (sequelize, DataTypes) {
    var role = sequelize.define('role', {
        id: { type: DataTypes.INTEGER, autoIncrement: false, primaryKey: true },
        name: DataTypes.STRING,
    },
        { timestamps: false }
    );

    return role;
};
```
```js
module.exports = function (sequelize, DataTypes) {
    var user = sequelize.define('user', {
        first_name: DataTypes.STRING,
        last_name: DataTypes.STRING,
    });

    user.associate = (db) => {
        user.belongsToMany(db.role, { as: 'roles', through: 'user_role', foreignKey: 'user_id' });
    };

    return user;
};
```

The actual code running the Add method:
```js
return db.role.findById(role_id, { transaction: transaction })
    .then(function (role) {
        return user.addRoles(role, { transaction: transaction })
    })
```

## What do you expect to happen?
I was expecting a new row in the join table to be added.

## What is actually happening?
Promise gets rejected with this in the logs:

```
Executing (041f9852-1d60-4126-bd4b-6d3a5a5e4028): SELECT "id", "name" FROM "role" AS "role" WHERE "role"."id" = '2';
Executing (041f9852-1d60-4126-bd4b-6d3a5a5e4028): SELECT "id" FROM "user_role" AS "user_role" WHERE "user_role"."user_id" = 1 AND "user_role"."role_id" IN (2);
Executing (041f9852-1d60-4126-bd4b-6d3a5a5e4028): ROLLBACK;
error: {"name":"SequelizeDatabaseError","parent":{"name":"error","length":94,"severity":"ERROR","code":"42703","position":"8","file":"parse_relation.c","line":"3183","routine":"errorMissingColumn","sql":"SELECT \"id\" FROM \"user_role\" AS \"user_role\" WHERE \"user_role\".\"user_id\" = 1 AND \"user_role\".\"role_id\" IN (2);"},"original":{"name":"error","length":94,"severity":"ERROR","code":"42703","position":"8","file":"parse_relation.c","line":"3183","routine":"errorMissingColumn","sql":"SELECT \"id\" FROM \"user_role\" AS \"user_role\" WHERE \"user_role\".\"user_id\" = 1 AND \"user_role\".\"role_id\" IN (2);"},"sql":"SELECT \"id\" FROM \"user_role\" AS \"user_role\" WHERE \"user_role\".\"user_id\" = 1 AND \"user_role\".\"role_id\" IN (2);"}

```

Dialect: postgres
Database version: 9.5
Sequelize version: 4.2.0

**Comment by SEUNAGBEYE** [comment]
I have this error when performing a query

**Comment by Emyboy** [comment]
i get this when findAll where Id =>Error .............."message": {
        "name": "SequelizeDatabaseError",
        "parent": {
            "name": "error",
            "length": 128,
            "severity": "ERROR",
            "code": "42703",
            "position": "38",
            "file": "parse_target.c",
            "line": "1005",
            "routine": "checkInsertTargets",
            "sql": "INSERT INTO \"Reviews\" (\"id\",\"review\",\"hostelid\",\"username\",\"useravatar\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'hostel three na die her hererehre','3','emyboybeats','http://mrmrs.github.io/photos/p/2.jpg','2018-11-28 13:19:43.702 +00:00','2018-11-28 13:19:43.702 +00:00') RETURNING *;"
        },

**Comment by Emyboy** [comment]
helo...!! any solutions ?

**Comment by robinbiondi** [comment]
I have the same problem...

**Comment by grezxune** [comment]
I just ran into this as well. :/

**Comment by grezxune** [comment]
I have a fix for my issue! It was a silly typo... 

`        special_type.hasMany(models.verified_special_space, {
            as: 'verifiedSpecialSpaces',
            foriegnKey: 'specialTypeId',
            sourceKey: 'specialTypeId'
        });
`

because "foreignKey" was spelt "foriegnKey", Sequelize was auto-generating me a join attribute when associating my models. Once I fixed that, all was good with the world and Sequelize recognized this as the join attribute.
