### ISSUE TITLE
keepAlive option for connections not configurable through sequelize, although the underlying pg library supports it

### ISSUE THREAD

**Issue by contactakagrawal** [sequelize/sequelize#7896]
## What you are doing?

```js
keepAlive: true
```

## What do you expect to happen?
_keepAlive option should be set for each connection alive in the pool_

## What is actually happening?
_Sequelize doesnt have any option to support this attribute although the underlying pg library supports it_

_Output, either JSON or SQL_

__Dialect:__ postgres
__Database version:__ XXX
__Sequelize version:__ ^3.30.4

**Comment by contactakagrawal** [comment]
@janmeier @mickhansen Kindly evaluate this issue, I can raise a PR which provides the fix

**Comment by janmeier** [comment]
Have you looked at `dialectOptions`? http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html

**Comment by contactakagrawal** [comment]
I looked at dialectOptions, we are not picking keepAlive option from it, below is the excerpt from /postgres/connection-manager.js
![image](https://user-images.githubusercontent.com/13332952/27947702-936fae88-6329-11e7-9bf8-5304627f7bdf.png)
Kindly suggest

**Comment by contactakagrawal** [comment]
@janmeier Please let me know if I am missing anything in my above comment.

**Comment by contactakagrawal** [comment]
Hi @felixfbecker  @janmeier I have raised the PR for the same, kindly review and approve it in your available time, thanks :)
Below is the pull request link:
https://github.com/sequelize/sequelize/pull/7927

**Comment by DavidMorton** [comment]
I'm not sure if I'm missing something here, but I'm passing in this value into my options, but the connections continue to churn.... Has something been changed in pg 7 that I'm missing here? Maybe I'm approaching this wrong, but I assumed that setting keepAlive to true would cause the client to respond to keepalive requests, thus preventing the server from closing the connection.
