### ISSUE TITLE
SequelizeConnectionError: ER_HANDSHAKE_ERROR: Bad handshake

### ISSUE THREAD

**Issue by Karthikds** [sequelize/sequelize#7899]
I have a new azure MySQL server and I am trying to use that with my existing Nodejs app.

When I try to connect to the Mysql instance from my terminal(using mysql command), I am able to successfully connect.

However, We I try to connect through my Nodejs app, which is using sequentialize for ORM, I am unable to connect.

It shows the following error

Unhandled rejection SequelizeConnectionError: ER_HANDSHAKE_ERROR: Bad handshake
Please find my code below

var sequelize = new Sequelize(config.database, config.username, config.password, {
  "host": config.host,
  "dialect": "mysql",
  "dialectOptions": {
    "ssl": {ca:fs.readFileSync("./BaltimoreCyberTrustRoot.crt")},
    insecureAuth: true
  }
});

FYI: 
sequelize@2.0.0
mysql@^2.11.1

**Comment by cohowap** [comment]
Probably good to review this chain:  There is quite a few issues noted from using Azure Database for MySQL https://github.com/sequelize/sequelize/issues/7633

**Comment by Karthikds** [comment]
Issue fixed in the latest sequelize version(>4.0)
