### ISSUE TITLE
Hooks mixin static methods are not document into Model documentation

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#7901]
I override without knowing a Model static method, mixin methods do not appears in the model documentation.

See http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-init

**Comment by JSteunou** [comment]
I think this is still an issue

**Comment by papb** [comment]
@JSteunou Can you clarify what you mean here? Which method did you override unintentionally?
