### ISSUE TITLE
Properties changed in beforeValidate hook don't get persisted when updating a record

### ISSUE THREAD

**Issue by mrstif** [sequelize/sequelize#7903]
I'm getting the exact same error described in https://github.com/sequelize/sequelize/issues/5449 and https://github.com/sequelize/sequelize/issues/4837

To summarise, what happens is that in an **update** operation when changing attributes in a **beforeValidate** hook, those changes are not persisted to the database.

I was using *v3.30.4* and upgraded to *v4.2.1* to try and solve this issue but apparently it's still there...

The tests included by @sushantdhiman in https://github.com/sequelize/sequelize/pull/5506 aren't really testing the whole scenario since what's persisted in the database isn't actually what's returned in the save/update callback. I hit the same pitfall in which the object in the callback is updated whereas getting the record directly from the database is not...

@guisehn described the right test that should be used to validate this case:

```javascript
sequelize.sync({ force: true }).then(function() {
  return User.create({
    name: ' First Middle Last '
  })
  .then(function(user) {
    return User.findById(user.id); // 1st reload - make sure we are retrieving the data stored in DB
  })
  .then(function(user) {
    assert.equal(user.name, 'First Middle Last'); // passes
    assert.equal(user.firstName, 'First'); // passes
    assert.equal(user.lastName, 'Last'); // passes

    return user;
  })
  .then(function(user) {
    return user.update({ name: ' NewFirst Middle1 Middle2 Middle3 NewLast  ' });
  })
  .then(function(user) {
    return User.findById(user.id); // 2nd reload - make sure we are retrieving the data stored in DB
  })
  .then(function(user) {
    assert.equal(user.name, 'NewFirst Middle1 Middle2 Middle3 NewLast'); // passes
    assert.equal(user.firstName, 'NewFirst'); // rejects (user.firstName is still "First")
    assert.equal(user.lastName, 'NewLast'); // rejects (user.lastName is still "Last")
  });
});
```
__Node version:__ 6.9.4
__Dialect:__ postgres
__Database version:__ 9.6.2
__Sequelize version:__ 4.2.1

**Comment by igorescobar** [comment]
Same here. :(

**Comment by mrstif** [comment]
Just as an update, I managed to fix this by adding the *fields* option in the **update** call:
```javascript
 user.update({ name: ' NewFirst Middle1 Middle2 Middle3 NewLast  ' }, { fields: ['name', 'firstName', 'lastName'] })
```

Dunno if needing this addition is actually a planned requirement in sequelize. IMO, it's not really nice to have to know which fields are updated in hooks every time a record is updated...

**Comment by dejan9393** [comment]
I'm having the same issue, I think this needs another look

**Comment by peter-bankuti** [comment]
this is still happening and it is really wrong, should be fixed.

**Comment by hobbydevs** [comment]
I'm experiencing the same issue. Should be reopened.
I'm using:
```
sequelize: 5.18.1
pg: 7.17.0
pg-hstore: 2.3.3
sequelize-cli: 5.5.1
```

**Comment by MarianyFerreira** [comment]
Same issue

"sequelize": "^5.21.2",

**Comment by Abenezer** [comment]
same here, beforeUpdate works fine .. so for now i am using both beforeCreate and beforeUpdate running the same function
