### ISSUE TITLE
Reopening issues closed by probot-stale?

### ISSUE THREAD

**Issue by jsha** [sequelize/sequelize#7904]
probot-stale recently closed a handful of issues I created or commented on. One of them, https://github.com/sequelize/sequelize/issues/2121#event-1153708509, is still a live issue AFAICT. It seems like I don't have the option to reopen. Would a project member reopen it? Thanks!

**Comment by eseliger** [comment]
Will reopen it, thank you for your feedback. We really needed to install probot to keep the issuetracker manageable somehow. unfortunately, we can't double check every issue created back in 2014 if it's still valid.
But you can still comment on closed issues, just fyi :)
