### ISSUE TITLE
Rename/disable Timestamp columns

### ISSUE THREAD

**Issue by joshbrw** [sequelize/sequelize#791]
It would be nice to have an option where we could disable/rename the timestamps in models, as I use Laravel the timestamps are created_at in Laravel and createdAt in Sequelize it can cause conflicts, so a way to rename and even disable the need for them would be appreciated!

**Comment by dfliess** [comment]
it would be nice to be able to rename those fields as it's needed sometimes for internacionalization.. I found several mysql tables with table and field names for example in spanish.

**Comment by janmeier** [comment]
@dfliess http://docs.sequelizejs.com/en/latest/api/sequelize/#definemodelname-attributes-options-model `timestamps` and `createdAt` etc. options

**Comment by dfliess** [comment]
thank you.!

**Comment by ericnelson1** [comment]
Example of how to rename timestamp columns:
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#configuration

**Comment by vbhakta8** [comment]
I was able to find how to rename the timestamp columns:
[https://sequelize.org/master/manual/model-basics.html#timestamps](https://sequelize.org/master/manual/model-basics.html#timestamps)
