### ISSUE TITLE
Query failing when offset/limit is passed as a string (Need auto parsing to integer)

### ISSUE THREAD

**Issue by abdulmoizeng** [sequelize/sequelize#7913]
## What you are doing?
Following is the code sample
```js
//user model
var UserModel = sequelize.define('user', {
    id: {type: DataTypes.INTEGER, primaryKey:true, autoIncrement: true},
    name: DataTypes.STRING
  }, {
    classMethods: {
      associate : function(models){
            }
    },
    timestamps: false
  });
//Running following query
UserModel.findAll({attributes:['id', 'name'],limit: '5'}).then(
    function(users){
        console.log('Users are Fetched!!, ', users.length);
    },
    function(err){
        throw(err)
    }
);

```

## What do you expect to happen?
I am expecting it to auto parse my `offset/limit` options to integer (if provided) and only throw error in case when auto parsing to integer is failed

## What is actually happening?
Currently its running query like `some query LIMIT '5'` and this stirng `'5'` is generating error in query

__Dialect: mysql (but its a global issue i beleive)
__Sequelize version: latest

**Comment by eseliger** [comment]
IMO string should not automatically be parsed to number. `limit` and `offset` should definitely be of type `Number`, not string. But a `TypeError` should be thrown. Or do you have any explicit use case for it? 
I think passing a _string_ as in your example is not correct usage of the api. It's weird that the method should magically convert your type for you.

**Comment by abdulmoizeng** [comment]
I was expecting library to convert `'5'` to`5`  as JavaScript has loosely types variables and for some reason we have pagination options in stringify number( library should not use `'5'` is the SQL query) but yes may be you are correct and we just need a `TypeError` to be thrown here

**Comment by felixfbecker** [comment]
Imo this is as designed. What prevents you from doing the conversion on your side? JavaScript has dynamic types, but not "loose" types. For example, `'5' + '5'` is `'55'`, not `10` like in PHP. I also don't think every single option's type should be validated on every call at runtime, that is the job of type checking tools like TypeScript or Flow.

**Comment by abdulmoizeng** [comment]
@felixfbecker , It was a sequelize version update in one my project and as sequelize versions `v3.16.0` and prior were working with `'5'` i.e `UserModel.findAll({attributes:['id', 'name'],limit: '5'})` is running proper query for that, I was expecting the later ones (from `v3.17.0` and above) to behave same

**Comment by felixfbecker** [comment]
Well, it was never documented as taking a string

**Comment by abdulmoizeng** [comment]
I think you guys are correct on this . it was previous versions behaviour due to which i opens this issue. Closing this now.
Thanks @eseliger @felixfbecker  for your time on this

**Comment by farzer** [comment]
v4.4.2 still meet this problem.

![image](https://user-images.githubusercontent.com/9881593/34594015-58e745d6-f209-11e7-8524-daa6fd6747f1.png)

![image](https://user-images.githubusercontent.com/9881593/34594003-4b1f518c-f209-11e7-9198-6ab88efbd474.png)
