### ISSUE TITLE
setting attribute unique:true fails on second run of sync alter operation

### ISSUE THREAD

**Issue by skn3** [sequelize/sequelize#7915]
## What you are doing?
Attempting to set a unique attribute on a Model defintion and then rebuild (sync) the database structure multiple times without fail.

```js
'use strict';

const Sequelize = require('sequelize');

//first connect to the database
const database = new Sequelize('database', 'user', 'password', {
    dialect: 'postgres',
    host: '127.0.0.1',
    port: 5432,

    pool: {
        max: 5,
        min: 0,
        idle: 10000
    },
});

return database.authenticate()
.then(() => {
    //success connecting,
    console.log('database connected');
    return database;
})
.then(database => {
    const containerModel = database.define('TestContainer', {
            number: {
                type: Sequelize.DataTypes.STRING(128),
                allowNull: false,
                unique: true,
            },
    });

    return database.sync({
        alter: true,
        force: false,
    });
})
.catch(err => {
    //failed to connect
    console.error(err);
    process.exit(1);
});
```

## What do you expect to happen?
The database to sync properly on the second run.

## What is actually happening?
_But the output is an error rejection!_

_Unhandled rejection SequelizeDatabaseError: relation "number_unique_idx" already exists_

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ master branch

**Comment by skn3** [comment]
If we manually set the unique constraint name to something (instead of just `true`) then it succeeds!

**Comment by skn3** [comment]
also related to #7606 and #7649

**Comment by skn3** [comment]
After some digging it also seems that this may be related to postgres specific issue. I did not know that postgres unique indexes were on schema level. I guess sequelize builds unique index names internally to counter act this? So when we rebuild (sync alter), this key name generation doesn't happen.

**Comment by OfekA** [comment]
This definitely also happens in MySQL as well.

**Comment by skn3** [comment]
I have tried working around this issue and I have reached an impossible situation!
Basically I have encountered the problem as I am trying to do concurrent findOrCreate operations. After reading previous issues, an index is required on the columns to be searched. No problem I set unique and everything works fine. The problem comes when trying to sync the structure the second time. I face teh following interlocking issues:

1. cant use findOrCreate concurrently without unique index
2. cant use unique index because the alter operation fails on second .sync()
3. cant work around by dropping constraints manually, as sequelize sync build sequence doesn't seem to rebuild indexes in the same order as 1st run, when the table already exists
4. cant use force/drop sync as all data is lost!

What am I supposed to do now? Any assistance guys?

**Comment by skn3** [comment]
Well the following code can be used to do a really ugly operation! It basically renames the existing tables in the database (assuming all your tables are generated ONLY by sequelize). It lets sequelize do its sync logic, from scratch and then copies the data back in. Finally it drops the old table. This is by no means a good way to do it and the code is using raw postgres queries. But until the bugs can be fixed, it might help anyone else in this same position.

```javascript
const syncOldTables = [];

function dropConstraints(database) {
    function getConstraintQuery(table) {
        return database.query(`SELECT r.*, conname as name, contype as type, pg_catalog.pg_get_constraintdef(r.oid, true) as def FROM pg_catalog.pg_constraint r WHERE r.conrelid = (SELECT oid FROM pg_class WHERE relname = '${table}' LIMIT 1) AND r.contype IN ('f', 'u', 'c', 'p') ORDER BY 1;`)
        .then(result => result[0]);
    }

    function removeConstraintQuery(table, constraint) {
        return database.query(`ALTER TABLE ${queryInterface.quoteIdentifiers(table)} DROP CONSTRAINT IF EXISTS ${queryInterface.quoteIdentifiers(constraint)} CASCADE`);
    }


    //get all tables
    const queryInterface = database.getQueryInterface();
    return queryInterface.showAllTables()

    //process each table individually
    .then(tables => Promise.all(tables.map(table => {
		return getConstraintQuery(table)
		.then(constraints => Promise.all(constraints.map(constraint => removeConstraintQuery(table, constraint.name))));
	})));
}

function syncBefore(database) {
    return dropConstraints(database)
    .then(() => {
        //rename all tables so that sequelize will rebuild our proper tables from scratch
        const queryInterface = database.getQueryInterface();

		//rename all tables
        return queryInterface.showAllTables()
        .then(tables => Promise.all(tables.map(table => {
			//rename this table
			const copyTable = table+'_____old';
			syncOldTables.push({
				oldTable: copyTable,
				newTable: table,
			});
			return queryInterface.renameTable(table, copyTable);
		})));
    });
}

function syncAfter(database) {
    const queryInterface = database.getQueryInterface();

    //copy data and drop the old table
    return Promise.all(syncOldTables.map(info => {
        return database.query(`INSERT INTO ${queryInterface.quoteIdentifiers(info.newTable)} SELECT * FROM ${queryInterface.quoteIdentifiers(info.oldTable)};`)
        .then(() => queryInterface.dropTable(info.oldTable));
    }))
    .then(() => {
        syncOldTables = [];
    })
}

function syncCollections(database) {
	return syncBefore(database)
	.then(() => database.sync({
		alter: config.server.database.sync.alter,
		force: config.server.database.sync.drop,
	}))
	.then(() => syncAfter(database));
}
```

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/7606

**Comment by FlamboD** [comment]
Bump. I hit the key limit (64) because I kept running my application with sequelize.sync({alter:true})

**Comment by ephys** [comment]
I'm 90% sure this was fixed in the Sequelize 7 alpha release following https://github.com/sequelize/sequelize/pull/14619
