### ISSUE TITLE
Raw query parsing error on replacements

### ISSUE THREAD

**Issue by anonrig** [sequelize/sequelize#7916]
Hello,

I'm using sequelize's latest version with Postgres. Trying to do basic Select query as raw query with `sequelize.query` function.

The following SQL query gives the following error:

```
Error occurred: Named parameter ":MI" has no value in the given object.
```

The line: `sum(case when TO_CHAR(bets.placed_time, 'YYYY-MM-DD HH24:MI:SS') <= ` creates ambiguity. Are there any solution to solve this problem without changing the query?

```javascript
    sequelize.query(`
      select
        bet_odds.sport_name,
        sum(case when TO_CHAR(bets.placed_time, 'YYYY-MM-DD HH24:MI:SS') <=  TO_CHAR(TO_TIMESTAMP(bet_odds.match_start_time / 1000), 'YYYY-MM-DD HH24:MI:SS') then bets.total_stake/bets.odd_count else 0 end) as pre_match_turnover,
        sum(case when TO_CHAR(bets.placed_time, 'YYYY-MM-DD HH24:MI:SS') >  TO_CHAR(TO_TIMESTAMP(bet_odds.match_start_time / 1000), 'YYYY-MM-DD HH24:MI:SS') then bets.total_stake/bets.odd_count else 0 end) as live_turnover,
        sum(case when TO_CHAR(bets.placed_time, 'YYYY-MM-DD HH24:MI:SS') <=  TO_CHAR(TO_TIMESTAMP(bet_odds.match_start_time / 1000), 'YYYY-MM-DD HH24:MI:SS') then (bets.total_stake/bets.odd_count) - (bets.win_or_lose_amount/bets.odd_count) else 0 end) as pre_match_gross,
        sum(case when TO_CHAR(bets.placed_time, 'YYYY-MM-DD HH24:MI:SS') >  TO_CHAR(TO_TIMESTAMP(bet_odds.match_start_time / 1000), 'YYYY-MM-DD HH24:MI:SS') then (bets.total_stake/bets.odd_count) - (bets.win_or_lose_amount/bets.odd_count) else 0 end) as live_gross
      from

...

{
        type: sequelize.QueryTypes.SELECT,
        replacements: {
          start: new Date(start),
          end: new Date(end),
          minStake: parseFloat(minStake),
          maxStake: parseFloat(maxStake)
        }
      
```

**Comment by eseliger** [comment]
This is a question regarding an (postgre)sql query, not really associated to sequelize. Please use stackoverflow or slack, ... to ask usage questions. We really invest every free minute we have to fix bugs and implement new features in sequelize and it makes it so hard to keep track of all the open issues.

**Comment by anonrig** [comment]
@eseliger Sequelize automatically thinks that `'YYYY-MM-DD HH24:MI:SS'` includes a parameter with`:MI`. This is not a question related to Postgresql but a question related to Sequelize. This was the main reason why I wrote it on Github but not on StackOverflow.

Thanks.

**Comment by anonrig** [comment]
Still not resolved.
