### ISSUE TITLE
Model.create with Sequelize.literal works, but not return result values. 

### ISSUE THREAD

**Issue by rokoroku** [sequelize/sequelize#7919]
## What you are doing?

```js
// code here
const model = await Model.create({ 
  id: sequelize.literal(`SELECT MAX(id)+1 FROM "some_table" WHERE "foreign_key"="some_id"`),
  ... 
}, { returning: true });

// model.dataValues = { id: Literal, ... }

```

## What do you expect to happen?
`id` will be returned as executed result value

## What is actually happening?
Above query is executed successfully, but `id` is returned as `Sequelize.Literal` object

__Dialect:__ postgres / sqlite
__Database version:__ XXX
__Sequelize version:__ 4.2.0

**Comment by ox** [comment]
Can you read the value if you print `model.id`? What if you did `model.get('id')` or `model.get({plain: true})`?

**Comment by LeonardEyer** [comment]
Same when dealing with current timestamp literal
`Instance {
dataValues:
   { createdAt: 2017-07-26T14:17:02.124Z,
     updatedAt: literal { val: 'CURRENT_TIMESTAMP' },...`

**Comment by yordis** [comment]
@ox I think this is related to #9151
