### ISSUE TITLE
wrong value of isNewRecord 

### ISSUE THREAD

**Issue by bookman920** [sequelize/sequelize#7926]
as the result of findCreateFind, the model Object's property isNewRecord equal false, at the same time, the _options.isNewRecord equal true.

in 3.30.4,  $options.isNewRecord worked well, but it disappeard.

Dialect: mysql
Database version: mysql 5.6
Sequelize version: 4.3.0

**Comment by felixfbecker** [comment]
underscore-prefixed, dollar-prefixed and undocumented API is private
