### ISSUE TITLE
Sequelize.authenticate (and) Sequelize.import = is not a function

### ISSUE THREAD

**Issue by MichelDiz** [sequelize/sequelize#7934]
## What you are doing?

Hi, greetings,

I got these two errors from sequelize (node.js Express server).

The context is I'm doing a connection with an existing MySql database. I use the sequelize-auto to accomplish this and it works! Sequelize-auto give-me all tables that I need from my database. Right away organized on models!

The Docs says "Which makes it easy for you to simply Sequelize.import it." And isn't... I'm trying to do the examples from the Docs - Actually I'm a newbie with Sequelize.

## What do you expect to happen?

I'm doing a connection betwen MySql and GraphQL. With my current config below.

I'm missing something here?

Thank you for you pacientice

Best Regards

## What is actually happening?
`var Project = Sequelize.import(_customer2.default);`
`TypeError: Sequelize.import is not a function`
`at loader (...) babel-register/lib/node.js:144:5`

```
{

"presets": [
"env"
// "latest"
// "es2015",
// "stage-0"
// "stage-1",
// "stage-2"
],
"plugins": [
"transform-runtime",
"transform-dirname-filename"
]
}

My package
{
"name": "express-api-plus",
"version": "0.0.0",
"private": true,
"scripts": {
"start": "nodemon ./bin/www --exec babel-node",
"dev": "nodemon . --exec babel-node",
"test": "babel-node .",
"sequelize": "./node_modules/.bin/babel-node ./node_modules/.bin/sequelize init"
},
"dependencies": {
"babel-plugin-transform-dirname-filename": "^1.1.0",
"body-parser": "~1.17.1",
"cookie-parser": "~1.4.3",
"debug": "~2.6.3",
"express": "~4.15.2",
"firebase": "^3.9.0",
"firebase-admin": "^4.2.1",
"graphql": "^0.9.6",
"graphql-server-express": "^0.7.2",
"jade": "~1.11.0",
"morgan": "~1.8.1",
"mysql2": "^1.3.5",
"sequelize": "^4.3.1",
"sequelize-cli": "^2.7.0",
"serve-favicon": "~2.4.2"
},
"devDependencies": {
"babel-cli": "^6.24.1",
"babel-plugin-transform-runtime": "^6.23.0",
"babel-preset-env": "^1.4.0",
"graphql-subscriptions": "^0.3.1",
"jest": "^19.0.2",
"jest-cli": "^19.0.2",
"nodemon": "^1.11.0"
}
}

exemple of the model created from S.auto:
/* jshint indent: 2 */

module.exports = function(sequelize, DataTypes) {
return sequelize.define('customer', {
id_customer: {
type: DataTypes.INTEGER(10).UNSIGNED,
allowNull: false,
primaryKey: true,
autoIncrement: true
},
id_gender: {
type: DataTypes.INTEGER(10).UNSIGNED,
allowNull: false
},
},
firstname: {
type: DataTypes.STRING(255),
allowNull: false
},
lastname: {
type: DataTypes.STRING(255),
allowNull: false
},
email: {
type: DataTypes.STRING(128),
allowNull: false
},
passwd: {
type: DataTypes.STRING(60),
allowNull: false
},

}, {
tableName: 'customer'
});
};
```
`

__Dialect:__ mysql
__Database version:__ "mysql2": "^1.3.5" + 10.1.25-MariaDB + InnoDB + DbPDO
__Sequelize version:__     "sequelize": "^4.3.1",   "sequelize-cli": "^2.7.0",

**Comment by ox** [comment]
`sequelize.import` and `sequelize.authenticate` are functions on the sequlize client, after you've made the connection to your database. So first you make the db connection, then you call `.import` with the connection.

```js
const Sequlize = require('sequelize');

const sequelize = new Sequelize(db, username, password, {});
const Project = sequelize.import(_customer2.default);

sequelize.authenticate()
  .then(() => {
    console.log('connected to DB');
  });
```

Notice the lowercase `sequelize` instead of `Sequelize`; the first being a DB connection, the second being the Sequlize library.

**Comment by MichelDiz** [comment]
Okay, I have a connection here. Using the "models/index.js" generated through 

> "./node_modules/.bin/sequelize init"

This command generates an simple connection template for me right? I see that the syntax is kind "old". But it's okay right?

I'm not undestanding the organization from that command. The "init" gives me a template models/index.js (and a config/config.json) to connect with Database. But all the tutorials from internet create something like "db.js" outside the models folder. And from there call all models from models folder...

my code was (util/db.js)
```
import myImport from './../models/customer';
const Project = equelize.import(myImport);
```

But Babel transformed it to
`_customer2.default);` i don't know why about "under_trace" + "2" in the end.

and this (at the same file db.js)

```
module.exports = (Sequelize, DataTypes) => {
  return Sequelize.define("Project", {
    name: DataTypes.STRING,
    description: DataTypes.TEXT
  })
}
```
My init code from Sequelize command.
```
'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(module.filename);
var env       = process.env.NODE_ENV || 'development';
var config    = require(__dirname + '/../config/config.json')[env];
var db        = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(function(file) {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

sequelize
.authenticate()
.then(() => {
console.log('Connection has been established successfully.');
})
.catch(err => {
console.error('Unable to connect to the database:', err);
});




db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;

```

**Comment by ox** [comment]
In your first code blurb, it should be
```js
const Project = conect.import(myImport);
```

Notice how the init code from the `sequelize` command first makes the connection to the DB:
```js
var sequelize = new Sequelize()
```
and then the connection calls `.import`:

```js
var model = sequelize['import'](...);
```

The _connection_ has to call `.import`, not the library.

**Comment by LiamKarlMitchell** [comment]
TypeError: sequelize.import is not a function

**Comment by jokashongwe** [comment]
thanks @LiamKarlMitchell,
it works for me!

**Comment by ninjasun** [comment]
thanks @LiamKarlMitchell 
same here. 2 months ago was working, now on a fresh install it show errors on the file imports.
I had to change:
` var model = sequelize['import'](path.join(__dirname, file));` with
   `var model = require(path.join(__dirname, file))(sequelize, Sequelize)`

And it works again.

**Comment by syd-botz** [comment]
also experienced difficulty importing files, even after switching to "require". However, now we are getting " TypeError: require(...) is not a function" error messages with `const model = require(path.join(__dirname, file))(sequelize, Sequelize);`. Has anyone had to change anything about the way their model files are exported as well?

**Comment by Morgbn** [comment]
I have also encountered difficulties importing my sequelize models. Based on @LiamKarlMitchell's answer I did (using Webpack) :
```javascript
const Sequelize = require('sequelize')
const db = {}

const sequelize = new Sequelize(...) // init Sequelize

const files = require.context('.', false, /\.js$/)
files.keys().forEach(key => {
  if (key === './index.js') return
  db[key.replace(/(\.\/|\.js)/g, '')] = files(key)(sequelize, Sequelize) // import model
})

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db)
  }
})

db.sequelize = sequelize
db.Sequelize = Sequelize

module.exports = db
```

**Comment by YuyaoZhong** [comment]
> require(...) is not a function

I met the same issue when executing as well. i think you may check the files you scan inside the loop. For my case just skip index.js can make the code work

**Comment by nckswt** [comment]
Another solution to `require(...) is not a function (if your models are defined as ES6 exports):

```js
const model = require(modelPath).default(sequelize, Sequelize);
```

**Comment by AryanChothani** [comment]
> TypeError: sequelize.import is not a function
> 
> ```js
>         const fs = require('fs');
>         const path = require('path');
>         fs
>             .readdirSync('./models')
>             .forEach((file) => {
>                 //const model = sequelize.import(path.join('./models', file));
>                 const model = require(path.join(__dirname,'models', file))(sequelize, Sequelize)
>                 sequelize[model.name] = model;
>             });
> ```
> 
> Only that worked.

    const fs = require('fs');
     const path = require('path');

      module.exports = {
      load({ sequelize, baseFolder, indexFile = 'index.js' }) {
      const loaded = {};

    fs
      .readdirSync(baseFolder)
      .filter((file) => {
        return (file.indexOf('.') !== 0) && (file !== indexFile) && (file.slice(-3) === '.js');
      })
      .forEach((file) => {
        const model = sequelize['import'](path.join(baseFolder, file));
        const modelName = file.split('.')[0];
        loaded[modelName] = model;
      });

    Object.keys(loaded).forEach((modelName) => {
      if(loaded[modelName].associate) {
        loaded[modelName].associate(loaded);
      }
    });

    loaded.database = sequelize;

    return loaded;
    }
     };

**Comment by cscim918** [comment]
Why is the error with import when I changed it to require?
![image](https://user-images.githubusercontent.com/56328811/94240080-b441d780-ff4d-11ea-9559-6d6be349c791.png)

**Comment by KHADIM-hub** [comment]
C:\wamp64\www\sentechniciensinformel\sentechnciensBackend\models\artisan.js:17
  artisan.init({
          ^

TypeError: artisan.init is not a function
    at module.exports (C:\wamp64\www\sentechniciensinformel\sentechnciensBackend\models\artisan.js:17:11)
    at C:\wamp64\www\sentechniciensinformel\sentechnciensBackend\models\index.js:24:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\wamp64\www\sentechniciensinformel\sentechnciensBackend\models\index.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
