### ISSUE TITLE
model.define create table everytime

### ISSUE THREAD

**Issue by chenkang084** [sequelize/sequelize#7936]
i am a new sequelizeer, when i establishes object relation mapping via model.define ,i found it create table everytime from console. i am not sure it is the correct method to mapping relation.

```js
var SocialUrl = db.define(
            "SocialUrl",
            {
                NT_LOGIN: {type: Sequelize.STRING, primaryKey: true},
            },
            {
                tableName: "game_usr_prfl",
                timestamps: false
            }
        );

        SocialUrl.sync()
            .then(() => {
            })
            .then(() => {
                SocialUrl.findAll({
                    where: {
                        NT_LOGIN: 'kanchen'
                    }
                }).then(users => {
                    res.send(users)
                });
            });
```

if it is right , create table everytime even if it exists, whether it is now efficient ?

i have tested query row using **sequelize** and **mysql** ,sequelize spent 20ms ,mysql library spent 2ms.

 ![github 样式效果图](https://dn-cnode.qbox.me/FnPmx-ATXj6Q9KUeIyffOYnrSaPU)

**Comment by ox** [comment]
Calling `SocialUrl.sync()` will try to create the table ([reference](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#database-synchronization)). Synchronizing the model should only be done in the first migration for a fresh DB, or not at all if connecting to an existing DB.

If the table already exists, don't run `SocialUrl.sync()`.

**Comment by chenkang084** [comment]
@ox Thanks for your reply, it is very helpful . `If the table already exists, don't run SocialUrl.sync()`  ,if i want to map exists table to Object, how to handle it ?

**Comment by ox** [comment]
@chenkang084 the mapping is implicit from Object to table. If you try to create a `SocialUrl` while connected to an existing DB where the `game_usr_prfl` table already exists, sequelize will call an `INSERT INTO game_usr_prfl ...`. Sequelize does not check if the model definition maps the table. `SocialUrl.sync()` changes the table, but you have to call that function if you want to change the table.

If you have an existing table that you want to make an object, you need to either `.define` another object in JS, or you can use [`sequelize.raw`](http://docs.sequelizejs.com/manual/tutorial/raw-queries.html) queries to just send raw SQL queries to the DB.

Sequelize is simply a nice way to write SQL against a database, validate the results, and unmarshal them into a JS object. It does not concern itself with much else. If there are errors issuing some query that sequelize generated, you'll get a rejected promise telling you what happened.

I hope any of that helps you.

**Comment by chenkang084** [comment]
@ox thanks. i will try your advice.

**Comment by hardik-singhal** [comment]
It is not efficient to remove every time tablename.sync() if created and add if it is not created if u have to use this in production and have to give it to client how should one can manage with no prior knowledge of coding
