### ISSUE TITLE
+8:00 timezone issues

### ISSUE THREAD

**Issue by Symous** [sequelize/sequelize#7938]
Hi,awesome lib!

when I use sequelize create to add a record to mysql database,
in the debug sql it print out that the time column is 2017-07-12 12:00:00,

but it stored as 2017-07-12 20:00 at last.

the only way I found to solve it now is add timezone when I define the model:
```js
timezone: '+08:00' 
```

Is there any to just save the time column without any increasing or decreasing? Thanks.

**Comment by yonjah** [comment]
Are you sure this is not the timezone set on your database server ?

**Comment by Symous** [comment]
@yonjah this is no relate to my configuration of my database, since that if I execute the debug sql generated by sequelize in the database , the time is correct as excepted.

**Comment by yonjah** [comment]
Maybe I'm not understanding this properly but if you see the sql passed to the db has the correct time and somehow the db stores a different value I would assume it's in the db config.

Can you attach a short code with logged queries to reproduce this issue ?

**Comment by Gpia** [comment]
I have this problem too

**Comment by kennylbj** [comment]
Same issue to me.
