### ISSUE TITLE
Why you guys add 's' automatically on table name ?

### ISSUE THREAD

**Issue by awesomehimanshu** [sequelize/sequelize#7940]
Suppose this is code

/*global sequelize Sequelize */
module.exports = (function () {
    'use strict';
    var blurbs = sequelize.define('blurb', {
        firstName: {
            type: Sequelize.STRING
        },
        lastName: {
            type: Sequelize.STRING
        }
    },
    {schema: 'mobile'});

// // force: true will drop the table if it already exists
    blurbs.sync({force: false}).then(function () {
        // Table created
        return true;
    });
    return blurbs;
}());

when i run code the name of table become "blurbs" instead of "blurb".

**Comment by ox** [comment]
It pluralizes the table name to make it look "nice" in the DB. You can set `freezeTableName: true` in the model configuration to turn it off. ([reference](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#configuration))

**Comment by awesomehimanshu** [comment]
Perfect

**Comment by awesomehimanshu** [comment]
How to disable "id" column also.

**Comment by namnm** [comment]
Plural name is making issue: https://github.com/sequelize/cli/issues/600

**Comment by AssouaAlbert** [comment]
I was wonder why I had an error. Nice work!

**Comment by charliechensz** [comment]
add the following code to config/config.json  ：
``
    "define": {
      "id": false,
      "freezeTableName": true,
      "createdAt": false,
      "updatedAt": false
    }
``
![code1](https://user-images.githubusercontent.com/45444203/153695590-1e5d8820-a2e9-4bc8-8097-4c60f92eb56d.png)
