### ISSUE TITLE
findOrCreate fails concurrently when unique attribute contains comma in value. Postgres unique constraint error incorrectly parses error message 23505 when the value contains a ','. 

### ISSUE THREAD

**Issue by skn3** [sequelize/sequelize#7941]
## What you are doing?
Trying to concurrently use findOrCreate when an attribute set to unique, would contain a comma.

```javascript
'use strict';

const Sequelize = require('sequelize');

//first connect to the database
const database = new Sequelize('database', 'user', 'password', {
    dialect: 'postgres',
    host: '127.0.0.1',
    port: 5432,

    pool: {
        max: 5,
        min: 0,
        idle: 10000
    },
});

return database.authenticate()
.then(() => {
    //success connecting,
    console.log('database connected');
    return database;
})
.then(database => {
    const containerModel = database.define('TestContainer', {
        name: {
            type: Sequelize.DataTypes.STRING(32),
            allowNull: false,
            unique: 'name',
        },
    });

    return database.sync({
        alter: true,
        force: false,
    })
    .then(database => {
        return database.transaction({
            autoCommit: false,
        })
        .then(transaction => {
            return Promise.all(['hello, world', 'hello, world'].map(name => {
                console.log(`findOrCreate({name: '${name}'})`);
                return containerModel.findOrCreate({
                    where: {
                        name: name,
                    },
                    defaults: {
                        name: name,
                    },
                    transaction: transaction,
                    returning: true,
                });
            }))
            .then(() => {
                transaction.rollback();
            })
            .catch(() => {
                transaction.rollback();
            });
        });
    });
})
.catch(err => {
    //failed to connect
    console.error(err);
    process.exit(1);
});
```

## What do you expect to happen?
concurrent operations to succeed without fail!

## What is actually happening?
So lets say i set attribute of my Model attribute 'name' to unique. If i were to try and findOrCreate multiple of these models concurrently, and there is a unique validation error, then it fails!

It fails because the findOrCreate checks the fields in the err object generated by postgres/query.js. The parsing of said fields is done from the error message generated by postgres. In the postgres/query.js it is splitting the regex matched values by ',' for both the field name and value. This incorrectly truncates the field value if it contained a ','. When the findOrCreate attempts to check for concurrency, it fails because the reported value from the error and the value its expecting do not match!

Get an error of 

> TestContainer#findOrCreate: value used for name was not equal for both the find and the create calls, 'hello, world' vs 'hello'

__Dialect:__ postgres 
__Database version:__ 9.6
__Sequelize version:__ master

**Comment by skn3** [comment]
Possible workarounds/fixes are:
limit to 1 concurrent operation

or change dialects/postgres/query.js to:
```javascript
      case '23505':
        // there are multiple different formats of error messages for this error code
        // this regex should check at least two
        if (errDetail && (match = errDetail.replace(/"/g, '').match(/Key \((.*?)\)=\((.*?)\)/))) {
          fields = _.zipObject(match[1], match[2]);
```

I have not done a pull request as I feel I don't yet have enough experience with sequelize internals to contribute.

**Comment by mhuggins** [comment]
I'm getting a similar issue when trying to record a DATE value on a column called `timestamp`.  In my case, there are no commas in the value.

> Executing (2c0b1659-cad4-4a10-aa51-194a2b53e918): START TRANSACTION;
> Executing (bc0bd2fd-94c8-40db-a05d-24f2ed9addfb): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "volumes", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_88296ea26a7740f0b7562fe0112d02a5$ BEGIN INSERT INTO "volumes" ("id","timestamp","volume","created_at","updated_at") VALUES (DEFAULT,'2017-08-20 18:45:00.000 +00:00',0,'2017-08-20 13:45:48.078 +00:00','2017-08-20 13:45:48.078 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_88296ea26a7740f0b7562fe0112d02a5$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
> Executing (2c0b1659-cad4-4a10-aa51-194a2b53e918): SAVEPOINT "2c0b1659-cad4-4a10-aa51-194a2b53e918-savepoint-1";
> Executing (2c0b1659-cad4-4a10-aa51-194a2b53e918): SELECT "id", "timestamp", "volume", "created_at", "updated_at" FROM "volumes" AS "volumes" WHERE "volumes"."timestamp" = '2017-08-20 18:45:00.000 +00:00' LIMIT 1;
> Executing (bc0bd2fd-94c8-40db-a05d-24f2ed9addfb): UPDATE "volumes" SET "volume"="volume"+0.0007606088924967,"updated_at"='2017-08-20 13:45:48.090 +00:00' WHERE "id" = 31 RETURNING *
> Executing (2c0b1659-cad4-4a10-aa51-194a2b53e918): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "volumes", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_93485fd32e4f41a8b6a30a0ecec91d8b$ BEGIN INSERT INTO "volumes" ("id","timestamp","volume","created_at","updated_at") VALUES (DEFAULT,'2017-08-20 18:45:00.000 +00:00',0,'2017-08-20 13:45:48.093 +00:00','2017-08-20 13:45:48.093 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_93485fd32e4f41a8b6a30a0ecec91d8b$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
> Executing (bc0bd2fd-94c8-40db-a05d-24f2ed9addfb): COMMIT;
> Error updating volume for BTC-NEO: Error: volumes#findOrCreate: value used for timestamp was not equal for both the find and the create calls, 'Sun Aug 20 2017 13:45:00 GMT-0500 (CDT)' vs '2017-08-20 18:45:00+00'
>     at _.each (/Users/mhuggins/Development/monitor/node_modules/sequelize/lib/model.js:2091:21)
>     at /Users/mhuggins/Development/monitor/node_modules/lodash/lodash.js:4944:15
>     at baseForOwn (/Users/mhuggins/Development/monitor/node_modules/lodash/lodash.js:3001:24)
>     at /Users/mhuggins/Development/monitor/node_modules/lodash/lodash.js:4913:18
>     at Function.forEach (/Users/mhuggins/Development/monitor/node_modules/lodash/lodash.js:9359:14)
>     at create.then.catch.err (/Users/mhuggins/Development/monitor/node_modules/sequelize/lib/model.js:2088:13)
>     at tryCatcher (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/util.js:16:23)
>     at /Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/catch_filter.js:17:41
>     at tryCatcher (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/promise.js:689:18)
>     at Async._drainQueue (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/Users/mhuggins/Development/monitor/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:781:20)
>     at tryOnImmediate (timers.js:743:5)
>     at processImmediate [as _immediateCallback] (timers.js:714:5)
> Executing (2c0b1659-cad4-4a10-aa51-194a2b53e918): ROLLBACK;

**Comment by mhuggins** [comment]
It looks like I can work around the issue by changing the first line of my example code to this, but seems like a hack:

```js
const timestamp = new Date(new Date(timestampString).getUTCDate());
```

**Comment by Mathiasduc** [comment]
```
Error: Venue#findOrCreate: value used for normalizedName was not equal for both the find and the create calls, 'msitj_"manggha"' vs 'msitj_manggha'
```

**Comment by sushantdhiman** [comment]
This feature was first introduced in https://github.com/sequelize/sequelize/pull/2173/files#diff-3efcb8c0187bb8e172796a804e246b7bR225  , and it's correctly implemented. Here are the details

We look into error details and try to find field and value from `Key "(key_name, ...)=(key_value, ...)" already exists.` Now [postgres implementation](https://github.com/postgres/postgres/blob/8224de4f42ccf98e08db07b43d52fed72f962ebb/src/backend/access/index/genam.c#L178) says there can be multiple keys separated by commas. But it does not escape or wrap that string in quotes, so error can look like this

```js
// what postgres returns
{
  code: '23505',
  detail: 'Key (name, code)=(john, son, agent, johnson) already exists.'
}

 // what postgres SHOULD return
{
  code: '23505',
  detail: 'Key (name, code)=("john, son", "agent, johnson") already exists.'
}
```
Now we can do two things

1. Fix this issue in Postgres itself :D
2. Explode keys based on number of attributes in `key_name` list

(2) should be easy to do, will accept PR

**Comment by siyb** [comment]
@sushantdhiman thanks for the quick response. Am I correct in assuming that the coordinate insertion issue is not related to the issue that is currently being discussed? If so I would open up another ticket.

**Comment by sushantdhiman** [comment]
@siyb yes, with a small test case preferably, so I can test / fix it quickly

**Comment by siyb** [comment]
@sushantdhiman I can't seem to recreate the issue in an isolated environment. The issue is 100% reproducible in the context of our database, but unfortunately, the data is confidential and cannot be handed over :(.

**Comment by idris** [comment]
@siyb / @sushantdhiman  an easy test case would be:
Create a table (projects) with unique constraint on a field `name`

Then run:
```js
await Projects.create({ name: 'foo, bar' });
try {
  await Projects.create({ name: 'foo, bar' });
} catch (err) {
  assert err.fields.name === 'foo, bar';
}
```

**Comment by idris** [comment]
By the way, this same issue happens with `)` in the string as well as `,`

**Comment by papb** [comment]
@idris Can you please convert that to a complete [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) that I can copy-paste and run? Thanks!

**Comment by huned** [comment]
still a problem fwiw

**Comment by jeetmehta13** [comment]
This issue is also occurring for MySQL, with `/` present for in the value for an attribute with unique constraint.
In my case, it seems to be doing something different.

For example if I were to pass following values to findOrCreate:

```
where: {
    uniqueStringParameter: '12345/1234567/text/123',
    uniqueIntegerParameter: 789
  },
  defaults: { jsonData: {} }
```
I would get the error: 
> Error: ModelName#findOrCreate: value used for uniqueStringParameter was not equal for both the find and the create calls, '12345/1234567/text/123' vs '789'

**(Note that it is comparing the values passed for uniqueStringParameter and uniqueIntegerParameter)**

This is also difficult to reproduce since it only happens when findOrCreate runs concurrently

**Comment by gabs-invoicesimple** [comment]
Having the same issue with Postgres. 
I created a Model that contains only id (unique, int, auto-increment) and message (text). Here are my findings:

- Despite receiving an error, the row is actually created with the correct message on the first time;
- The error happens only when the message doesn't exist;
- Subsequent calls with the same message work with no issues.
