### ISSUE TITLE
sync({ alter: true }) does nothing

### ISSUE THREAD

**Issue by demian85** [sequelize/sequelize#7946]
## What you are doing?
```js
'use strict';

const models = require('./index');

models.sequelize.sync({ alter: true });
```
Then running script as `node sync.js`

## What do you expect to happen?
Some kind of log message...

## What is actually happening?
Nothing, and there are pending changes to db.

_Output, either JSON or SQL_
nothing...

__Dialect:__ mysql
__Database version:__ Mysql 5.7.11
__Sequelize version:__ 4.3.2

**Comment by felixfbecker** [comment]
Sequelize doesn't log anything if you don't tell it to. You also have to catch the error

**Comment by demian85** [comment]
Docs say that logging option is `console.log` by default.
Catching error prints nothing.
Does sequelize calls queue until a connection is established?
I'm creating a Sequelize instance, then defining models and then calling `sync`.
Seems that script hangs when importing models, then exits (???)
Will come back with more details...

**Comment by demian85** [comment]
Okay, `mysql2` package is needed, somehow the error is swallowed in my script -_-
You can mention that in migration guide.

**Comment by felixfbecker** [comment]
Feel free to do a PR
