### ISSUE TITLE
Documentation error: Sequelize option "dialect" is not optional?

### ISSUE THREAD

**Issue by haches** [sequelize/sequelize#7958]
## What you are doing?
Using Sequelize in v4.3.2.
I didn't provide a `dialect` in the Options object for the constructor. That results in

```
node_modules/sequelize/lib/sequelize.js:169
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^
```

## What do you expect to happen?
According to [the docs](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html) the dialect is optional and should default to `'mysql'`.

## What is actually happening?
Error as listed above.

__Dialect:__ mysql
__Database version:__ 5.5
__Sequelize version:__ 4.3.2

**Comment by sagarora77** [comment]
I also faced the same issue.

**Comment by gloorx** [comment]
Here too.

**Comment by Jadex1** [comment]
I'm getting this as well. I just started using sequelize. I'm not sure what's wrong. I tried setting my files up like this https://gist.github.com/andrewmunro/030f0bf62453239c495b0347c8cd1247#file-how-to-use-md.

**Comment by MaxPleaner** [comment]
The error goes away when I add "dialect" as shown here:

```json
{
  "development": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  },
  "production": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  }
}
```

**Comment by rohitsud** [comment]
This should also be a part of breaking changes for v4.0.0 instead of just being in the changelog.

**Comment by SouengKimmeng** [comment]
I also got this issue. anyone help?

**Comment by eseliger** [comment]
Thank you for reporting this, I will update the docs.
Yes, the dialect is requires as of v4. If using a URI, the protocol is used to infer the dialect type, otherwise, when using the host, username, .. variant, the protocol needs to be set.

**Comment by ahiezerrivas** [comment]
var connection = new Sequelize('database,' user', 'password',{
    host: 'localhost',
    dialect: 'mysql'
});

**Comment by eseliger** [comment]
?

**Comment by yassinMk** [comment]
face the same issue and fixed it by setting the `NODE_ENV` to the specified environment in the `config.json`

**Comment by grenudi** [comment]
as ahiezerrivas comment , you should first add 
var connection = new Sequelize('database,' user', 'password',{
host: 'localhost',
dialect: 'mysql'
});
var connection = new Sequelize('database,' user', 'password',{
host: 'localhost',
dialect: 'mysql'
});
and then download pg module (using: npm install pg)

**Comment by dancitron** [comment]
I've been having issues with it as well. In my config file I have 

>         "dialect": "mysql"

I'm still getting the "Error: Dialect needs to be explicitly supplied as of v4.0.0". Very frustrating and can't figure out why Sequelize doesn't see my specifying the dialect.

**Comment by jlherren** [comment]
@dancitron I had the same issue and it was due to not having a development config as seen in most tutorials. For some weird reason it continues using the entire {'testing':..., 'production':...} object as options, which obviously doesn't have a 'dialect' attribute.

**Comment by AlessioMTX** [comment]
@jlherren where should I add a development config? I have my `sequelize = new Sequelize(database, dbUsername, dbPassword, dbOptions);` where dbOptions is
 `{
    "host": url,
    "dialect": "mysql",
    "pool": {
      "max": 5,
      "min": 0,
      "idle": 10000
    }`

I'm on Windows

**Comment by WilixLead** [comment]
I have config.json file, but I don't what for sequelize use it. I have different structure of this file and manually call constructor line in example:

```
const sequelize = new Sequelize(config.dbo.database, config.dbo.username, config.dbo.password, {
  host: config.dbo.host,
  port: config.dbo.port,
  dialect: config.dbo.dialect
});
```

It throw the error and I can understand what happen?

**Comment by Mr-emeka** [comment]
Having this same issue " throw new Error('Dialect needs to be explicitly supplied as of v4.0.0')"  and dialect has been specified in my config.Json file..

**Comment by hyedhiraj** [comment]
It worked for me on windows by adding following in config.json

"NODE_ENV":"development"

**Comment by aron-ivarsson** [comment]
Why is this closed? This error still persists, and I can't seem to find a solution. Even though you specify dialect, it throws this error.

**Comment by kwalew** [comment]
I am getting this error as well. I'm not using a config file, and below is the list of packages:

`  "dependencies": {
    "body-parser": "^1.19.0",
    "ejs": "^3.1.5",
    "express": "^4.17.1",
    "express-handlebars": "^3.0.2",
    "pg": "^8.3.3",
    "pg-hstore": "^2.3.3",
    "pug": "^3.0.0",
    "sequelize": "^6.3.5"
  }
}`

**Comment by bjornbrandy** [comment]
I also have the same issue, although when I log the environment and config it is correct:

` [2021-03-31T05:26:13.910240767Z] Environment: test
[2021-03-31T05:26:13.912376565Z] {
[2021-03-31T05:26:13.912397149Z]   database: 'something',
[2021-03-31T05:26:13.912402033Z]   username: 'moresomething',
[2021-03-31T05:26:13.912404994Z]   password: 'randomnumbersetc',
[2021-03-31T05:26:13.912409279Z]   options: {
[2021-03-31T05:26:13.912412661Z]     host: 'someurl,
[2021-03-31T05:26:13.912416608Z]     port: 'morenumbers',
[2021-03-31T05:26:13.912419406Z]     dialect: 'postgres'
[2021-03-31T05:26:13.912422035Z]   }
[2021-03-31T05:26:13.912424736Z] }
[2021-03-31T05:26:13.914017848Z] /workspace/node_modules/sequelize/lib/sequelize.js:281
[2021-03-31T05:26:13.914030695Z]       throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
[2021-03-31T05:26:13.914035184Z]       ^
[2021-03-31T05:26:13.914038389Z] 
[2021-03-31T05:26:13.914041186Z] Error: Dialect needs to be explicitly supplied as of v4.0.0`

How else should this be declared?
