### ISSUE TITLE
updatedAt (on update) not working

### ISSUE THREAD

**Issue by ja-heller** [sequelize/sequelize#7961]
## What you are doing?
When updating a model the "updated_at" field is not updated automatically.

```js

//price model
const Price = sequelize.define('prices', {
  	amount: Sequelize.INTEGER.UNSIGNED,
  	updated_at: Sequelize.DATE,
},
{
  underscored: true,
  timestamps: true,
  createdAt: false,
});

//updating the model
Price.findOne({
  where: {id: 1}
}).then(price => { 
	price.update({
    	amount: 150,
    })
});
```

## What do you expect to happen?
Automatic updating "updated_at" attribute.

## What is actually happening?
No updated of "created_at" occurs after updating the price value.

__Dialect:__ mysql
__Database:__ version:5.7.18
__Sequelize:__ version:4.3.2

**Comment by srslafazan** [comment]
This appears to still be an issue -- perhaps "stale" bot should not be closing issues unless there is reasonable reason to close them.

**Comment by srslafazan** [comment]
Related to  #9803
