### ISSUE TITLE
Support for Postgres broken since pg 7.0.0

### ISSUE THREAD

**Issue by thiloo** [sequelize/sequelize#7973]
Since the update of the `pg` module to version 7.0.0 support for Postgres is broken. 

Sequelize fails to establish a connection to a Postgres database. The following error message occurs:

"TypeError: connection.query(...).on is not a function"

NPM packages used pg 7.0.0, sequelize 4.3.2 and pg-hstore 2.3.2

When downgrading to pg 6.3.0 the error disappears and a connection can be established. 

My JS code:

```javascript
const Sequelize = require('sequelize');

const connection = new Sequelize('db', 'username', 'password', {
    dialect: 'postgres'
});

// test connection
connection
    .authenticate()
    .then(() => {
        console.log('Connection has been established successfully.');
    })
    .catch(err => {
        console.error('Unable to connect to the database:', err);
    });
```

**Comment by alitaheri** [comment]
@thiloo take a look at #7888.

**Comment by iEricKoh** [comment]
Have the same problem, waiting the PR to be merged.

**Comment by DesignByOnyx** [comment]
This is due to the fact that pg connection manager [no longer returns an event emitter](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#breaking-changes). Hopefully it gets fixed sooner than later. Thanks for all the hard work sequelize team!
