### ISSUE TITLE
Query with `having` clause with aggregate function does not work as described

### ISSUE THREAD

**Issue by brettvitaz** [sequelize/sequelize#7975]
## What you are doing?
I am trying to create a query using Sequelize v4.3 that will return rows where a the max date in a joined table is greater than now.

There is an "order" table with columns "id", "name", etc., and a "guarantee" table with columns "id", "order_id", "start_date", "end_date", etc.

Here is an example of a SQL query which produces the result I am hoping for:

```sql
SELECT
  "order"."id",
  "order"."name",
  min("guarantees"."start_date") AS "start_date",
  max("guarantees"."end_date")   AS "end_date"
FROM "api"."order" AS "order"
  LEFT OUTER JOIN "api"."guarantee" AS "guarantees" ON "order"."id" = "guarantees"."order_id"
WHERE "order"."is_enabled" = TRUE
GROUP BY "order"."id"
HAVING min("guarantees"."start_date") >= now();
```

Here is the Sequelize query that gets me 90% of the way there, minus the "having" clause:

```js
Order.findAll({
  attributes: [
    'id',
    'name',
    [sequelize.fn('min', sequelize.col('guarantees.start_date')), 'start_date'],
    [sequelize.fn('max', sequelize.col('guarantees.end_date')), 'end_date'],
  ],
  group: ['order.id'],
  include: [
    { model: Guarantee, attributes: [] },
  ],
})
```

I have everything but the "having" clause working. Here are some things I have tried:

```js
  having: ['min(?) >= ?', '"guarantees"."start_date"', sequelize.fn('now')],

  having: { '$min("guarantees"."start_date")$': { $gte: sequelize.fn('now') } }

  having: { [sequelize.fn('min', sequelize.col('guarantees.start_date'))]: { $gte: sequelize.fn('now') } }

  having: ['$min("guarantees"."start_date") >= now()']
```

The first example was described in the issue #1585 as the correct method: https://github.com/sequelize/sequelize/issues/1585#issuecomment-39317886

## What do you expect to happen?
Add a having clause which resembles:

```sql
HAVING min("guarantees"."start_date") >= now();
```

## What is actually happening?
- Using: `  having: ['$min("guarantees"."start_date") >= now()']` and `  having: ['min(?) >= ?', '"guarantees"."start_date"', sequelize.fn('now')]`

`Error: Support for literal replacements in the `where` object has been removed.`

- Using: `  having: { '$min("guarantees"."start_date")$': { $gte: sequelize.fn('now') } }`

`SequelizeDatabaseError: missing FROM-clause entry for table "min(guarantees"`

Creates query:

```sql
SELECT
  "order"."id",
  "order"."name",
  min("guarantees"."start_date") AS "start_date",
  max("guarantees"."end_date")   AS "end_date"
FROM
  "api"."order" AS "order" LEFT OUTER JOIN "api"."guarantee" AS "guarantees" ON "order"."id" = "guarantees"."order_id"
GROUP BY "order"."id"
HAVING "min(guarantees"."start_date)" >= now();
```

__Dialect:__ postgres
__Database version:__  PostgreSQL 9.6.1
__Sequelize version:__ 4.3

**Comment by meuwka** [comment]
+1

**Comment by meuwka** [comment]
Solved for me as:
```
having: Sequelize.literal(`count(role_id) = ${rolesCount}`),
```

**Comment by brettvitaz** [comment]
A solution was eventually found, but I do not consider this to be obvious at all:

```js
          having: sequelize.where(sequelize.fn('max', sequelize.col('guarantees.end_date')), {
            $lte: sequelize.fn('now'),
          })
```

**Comment by meuwka** [comment]
Agree, this solution doesn't look clear

**Comment by ErKiran** [comment]
Any Update on it

**Comment by farnazj** [comment]
How would you write an AND of statements in having clause in Sequelize? Sth like this:
HAVING min("guarantees"."start_date") >= now() AND max("guarantees"."start_date") < some_date;

**Comment by bradleyy1012** [comment]
@farnazj You would do
`
having: {
        someColumn: 'someValue',
        someOtherColumn: 'someOtherValue',
      }
`

**Comment by harlesbayu** [comment]
I think you can use this code

`having: where(
sequelize.fn('min', sequelize.col('guarantees.start_date')), 'start_date',
{ [sequelize.Op.gte]: new Date() }
)`

**Comment by rhayart** [comment]
> How would you write an AND of statements in having clause in Sequelize? Sth like this:
> HAVING min("guarantees"."start_date") >= now() AND max("guarantees"."start_date") < some_date;

To write an AND statement inside having clause, you can do something like this :
```
having: sequelize.and(
sequelize.where(sequelize.fn('count', sequelize.col('user.id')), {
                  [Op.gte]: users.length,
                }),
sequelize.where(sequelize.fn('count', sequelize.col('role.id')), {
                  [Op.gte]: roles.length,
                }),
),
```
