### ISSUE TITLE
Unhandled rejection TypeError: connection.query(...).on is not a function

### ISSUE THREAD

**Issue by wayne-o** [sequelize/sequelize#7977]
## What you are doing?
Trying to connect to postgres running localy

```js
Unhandled rejection TypeError: connection.query(...).on is not a function
```

## What do you expect to happen?
I wanted to conenct and initialize the DB - it worked using MSSQL

## What is actually happening?
Unhandled rejection TypeError: connection.query(...).on is not a function

__Dialect:__ postgres

**Comment by wayne-o** [comment]
related: 

https://github.com/brianc/node-postgres/issues/1377

Maybe I am using wrong versions of stuff? Or is this a geniune bug?

**Comment by vitorsilvalima** [comment]
I'm having the exact same issue. 
sequelize@4.3.2:

**Comment by wayne-o** [comment]
this line here: https://github.com/brianc/node-postgres/blob/master/lib/client.js#L394

Should be returning query I think - I changed that line in my local code base and it now works so i think it's a bug

**Comment by vitorsilvalima** [comment]
Oh I see. I just installed version  pg@6.4.1 and it worked fine. It may be an issue related with the support for pg ^ 7.0.0. That's good that you have found a workaround

**Comment by sgehly** [comment]
Just a bit of help for the Sequelize maintainers: node-postgres is now returning promises, so .on() is no longer a valid method in sequelize/lib/dialects/postgres/connection-manager.js:158:12 and in a few other places in that dialect.

**Comment by iambriansreed** [comment]
Had the same issue and @vitorsilvalima's comment worked.

**Comment by wayne-o** [comment]
Reverting to an old version is the fix?
		
		

		Get Outlook for iOS
	




On Sat, Jul 22, 2017 at 11:07 PM +0100, "Felix Becker" <notifications@github.com> wrote:












Closed #7977.

**Comment by felixfbecker** [comment]
Why "old" version? This issue is about Postgres 7.0, which was not supported when this issue was opened (and not documented as being supported). Issues with the new v7 support are tracked in different issues. v7 is out now for barely 5 days

**Comment by wayne-o** [comment]
So reverting to an older version of node-pg is the fix? I'm not having a dig I'm asking because I followed the install flow and immediately ran into this. Maybe having the user manually depend on pg is flawed? And if so maybe we can fix that. 
		
		

		Get Outlook for iOS
	




On Sat, Jul 22, 2017 at 11:14 PM +0100, "Felix Becker" <notifications@github.com> wrote:












Why "old" version? This issue is about Postgres 7.0, which was not supported when this issue was opened (and not documented as being supported). Issues with the new v7 support are tracked in different issues. v7 is out now for barely 5 days

**Comment by felixfbecker** [comment]
Yes, v6

**Comment by wayne-o** [comment]
Would there be a case for installing these deps via the CLI? If so how hard would it be for me to implement?
		
		

		Get Outlook for iOS
	




On Sun, Jul 23, 2017 at 9:26 AM +0100, "Felix Becker" <notifications@github.com> wrote:












Yes, v6

**Comment by felixfbecker** [comment]
I don't understand how the CLI is supposed to help here

**Comment by wayne-o** [comment]
For instance 
sequelize:install:pg 
Would install the appropriate version of node pg...
It means the users of sequelize are kept in the context when using the CLI (much better UX) and it means the version they pull is not random based on when they install it. 
		
		

		Get Outlook for iOS
	




On Sun, Jul 23, 2017 at 9:28 AM +0100, "Felix Becker" <notifications@github.com> wrote:












I don't understand how the CLI is supposed to help here

**Comment by felixfbecker** [comment]
It's not random if you read the documentation first 😄 
But feel free to open an issue at sequelize-cli

**Comment by wayne-o** [comment]
From the docs
$ npm install --save sequelize$ npm install --save pg pg-hstore
No version info.
I'll open a bug and try and submit a PR if I'm right here. Please correct me if I'm wrong.
		
		

		Get Outlook for iOS
	




On Sun, Jul 23, 2017 at 9:33 AM +0100, "Felix Becker" <notifications@github.com> wrote:












It's not random if you read the documentation first 😄

But feel free to open an issue at sequelize-cli

**Comment by wayne-o** [comment]
I've only been using the fw for a week and I've already migrated my DB from sails to hapijs with proper migrations and it's ridiculously easy to use and work with - I think this project is immense so if I can help improve it in anyway I would be very happy. 
		
		

		Get Outlook for iOS
	




On Sun, Jul 23, 2017 at 9:36 AM +0100, <wayne@prjatk.com> wrote:













	
		
		
	
		
From the docs
$ npm install --save sequelize$ npm install --save pg pg-hstore
No version info.
I'll open a bug and try and submit a PR if I'm right here. Please correct me if I'm wrong.
		
		

		Get Outlook for iOS
	




On Sun, Jul 23, 2017 at 9:33 AM +0100, "Felix Becker" <notifications@github.com> wrote:












It's not random if you read the documentation first 😄

But feel free to open an issue at sequelize-cli

**Comment by felixfbecker** [comment]
It’s here: https://github.com/sequelize/sequelize/blob/4383922ae910e64d8e22b91b97f4aed608973f3b/docs/usage.md#postgresql
Not sure why it’s not in the docs. Anyway, v7 came out 5 days ago. Before that, the steps worked fine and we now already support v7 (albeit there are bugs).

**Comment by paolo-lizarazu** [comment]
seems the issue is only in versions conflict

**Comment by sathishadi** [comment]
Can Some One Please look into this ASAP

![conn_issue](https://user-images.githubusercontent.com/32728575/31481791-da7854be-af42-11e7-96ef-0033587706fb.png)

**Comment by timedata** [comment]
I have the same ıssue.

So sequelize .on method is no longer valid, but sequelize auto using that at the programatic api.

cause of that sequelize auto programatic api not working now

**Comment by bruno-serfe** [comment]
Nobody will look into this issue?

**Comment by alexpmorris** [comment]
try updating the sequelize depency in your project's `package.json` to the latest version, that seemed to solve it for me:

```
    "sequelize": "^4.22.12",
    "sequelize-cli": "^3.1.0",
```

**Comment by Lzok** [comment]
@alexpmorris 's comment worked for me! I just updated sequelize from ^3 to ^4.22.12

**Comment by stonedraider** [comment]
I am also getting "connection.query(...).on is not a function" when trying to use sequelize-auto, downgrading pg from 7.4.0 to 6.4.1 didn't help. Is there a way that sequelize-auto is working right now?
