### ISSUE TITLE
invalid reference to FROM-clause entry for table

### ISSUE THREAD

**Issue by AdrianoMoura** [sequelize/sequelize#7978]
## What you are doing?

I making a query with a relationship between a model and itself as a children, and the children and another model.

```js
Category.findAndCountAll({
      include: [{
          model: Category,
          include: [{
            model: Item
          }]
        }]
    })
```

## What do you expect to happen?

My objective is to return a tree based on a relationship between the model Category and itself and the Item model.

## What is actually happening?

The resulting query create a wrong alias to Itens table

the resulting SQL is
```sql
SELECT 
   "Category"."id", 
   "Category"."title", 
   "Category"."CategoryId", 
   "Category"."createdAt", 
   "Category"."updatedAt", 
   "Categories"."id" AS "Categories.id",
   "Categories"."title" AS "Categories.title", 
   "Categories"."CategoryId" AS "Categories.CategoryId", 
   "Categories"."createdAt" AS "Categories.createdAt",
   "Categories"."updatedAt" AS "Categories.updatedAt", 
   "Itens"."id" AS "Itens.id", 
   "Itens"."title" AS "Itens.title",
   "Itens"."createdAt" AS "Itens.createdAt", 
   "Itens"."updatedAt" AS "Itens.updatedAt" 
FROM "Categories" AS "Category" 
LEFT OUTER JOIN "Categories" AS "Categories" ON "Category"."id" = "Categories"."CategoryId" 
LEFT OUTER JOIN "Itens" AS "Categories.Itens" ON "Categories"."id" = "Categories.Itens"."CategoryId";
```

As you can see the LEFT JOIN calls the Itens table and give "Categories.Itens" alias, but on SELECT it makes a reference to "Itens" directly, so the method returns the following error

```js
message: "invalid reference to FROM-clause entry for table "Itens""
```

__Dialect:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ 3.30.4

**Comment by idrisadetunmbi** [comment]
I am currently having this issue too, I don't know what I might be doing wrongly.

**Comment by irinawetransfer** [comment]
I'm having this issue as well; this http://discourse.metabase.com/t/basic-sql-query-not-working-with-field-filter/1057 does not help me.

**Comment by idrisadetunmbi** [comment]
@irinawetransfer, this error most times occur when the query includes a model name (or association alias) that is not associated with the model you are querying from. 
What exactly are you trying to do? Can you post snippets and the errors you are getting?

**Comment by irinawetransfer** [comment]
@idrisadetunmbi I see what you mean, however, I do not think that that is the case, I am not using any aliases. What I noticed is that the filters work directly on a table:

```
select
    var1,
    count (distinct var2)
from
    table_x
where
    {{curency}}
group by
    var1
```

However, when there is an extra step - I create an intermediate table - before applying the filters, the query produces the error mentioned in this issue:
```
with

intermediate_table as
(
    select
        var1,
        var2
    from
        table_x
    where
        var0 > 0
)

select
    var1,
    count (distinct var2)
from
    intermediate_table
where
    {{curency}}
group by
    var1
```
