### ISSUE TITLE
How can I use force index on query?

### ISSUE THREAD

**Issue by felipefdl** [sequelize/sequelize#7980]
Hello, I would like to use force index on a query, how can I use this?

```sql
SELECT
	`id` ,
	`variable` ,
	`created_at`
FROM
	`data` AS `data`
FORCE INDEX(variable_created_at)
WHERE
	`data`.`created_at` <= '2017-07-18 14:39:45'
	AND `data`.`variable` = 'xxx'
ORDER BY
	`data`.`created_at` DESC
LIMIT 10;
```

**Comment by henryarbolaez** [comment]
Hey @felipefdl did you found a way to do this, I have the same issue. Thanks!

**Comment by felipefdl** [comment]
@henryarbolaez I just moved from sequelize to knex. Anyway, I have a fork of sequelize with that function, you can use, https://github.com/tago-io/sequelize.

**Comment by felipefdl** [comment]
@henryarbolaez 
I just added a few lines, https://github.com/tago-io/sequelize/commit/8275571753a53f292d6a7f874926bfefc5fed5d6

Good luck.

**Comment by henryarbolaez** [comment]
Thanks!
