### ISSUE TITLE
Connection-manager Error with Sequelize 4.4. and pg 7.0.1 (TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined)

### ISSUE THREAD

**Issue by wolframkleis** [sequelize/sequelize#7985]
## What you are doing?

I just upgraded to Sequelize 4.4.0 and [node-postgres](https://github.com/brianc/node-postgres) (pg) version 7.0.1 

Then, when I call some function that connect to database (for example `findAll()` or `sync()`) the connection to Postgres database fails with error. 

It happens, for example, when I run this  example from the documentation

```js
const User = sequelize.define('user', {
  username: Sequelize.STRING,
  birthday: Sequelize.DATE
});
sequelize.sync()
  .then(() => User.create({
    username: 'janedoe',
    birthday: new Date(1980, 6, 20)
  }))
  .then(jane => {
    console.log(jane.get({
      plain: true
    }));
  })
```

## What do you expect to happen?
Sequelize should connect to Postgres and create tables, insert records and so on

## What is actually happening?
Connection to postgres database fails with the following error:
```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Promise.then.result (C:\test\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:157:31)
    at tryCatcher (C:\test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\test\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\test\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\test\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\test\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\test\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\test\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\test\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

When I switch back to  pg 6.4.0 the same code runs nicely. 
Interesting: With  pg 6.4.0,  it works with both Sequelize 4.4.0 and 4.3.2 
(This shows also that my database connection options are correct)

But the combination of 4.4.0 and pg 7 gives my this error.  Am I doing something wrong? 

Dialect:  postgres
Database version: 9.6
Sequelize version:  4,4.0

**Comment by saudpunjwani101** [comment]
Well any luck so far?

**Comment by saudpunjwani101** [comment]
I just upgraded to sequelize 4.4.0 and pg to 7.0.1 and getting this same error

**Comment by scttcper** [comment]
Same versions, same problem.

Roll back to pg 6.4.1 and sequelize 4.3.2

**Comment by nstuyvesant** [comment]
Same same

**Comment by sairamkrish** [comment]
Same versions, same problem. Any updates on this ?

**Comment by marcklei** [comment]
Same for me, rolled back to pg 6.4.1 and sequelize 4.4.0.

**Comment by adampasz** [comment]
I'm a n00b, but roll back worked for me. Make sure to do a clean `npm install` after you roll back.

**Comment by MarkusPint** [comment]
Having this happen with sequelize cli...

**Comment by saudpunjwani101** [comment]
Yes it's not migrating because no table is being createx when using pg 7.

**Comment by alitaheri** [comment]
Version 7 had a [breaking change](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#breaking-changes) that they didn't warn about. Multiple statements now return an array of results. this might have broken the code in many places. either originating from user code or the library code. please included the stack trace whenever you an error looking like this:

` TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined`

**Comment by AskYous** [comment]
It works now! Thanks @felixfbecker!

**Comment by tapz** [comment]
With 4.4.2 and sg 7.0.2 I get this with sync. No errors with sg 6.4.1...

Unhandled rejection TypeError: Cannot read property '0' of undefined

**Comment by dotorify** [comment]
Same for me, rolled back to pg 6.4.1 and sequelize 4.4.3.

Error Message -`Unhandled rejection TypeError: Cannot read property '0' of undefined`

**Comment by tapz** [comment]
I created a new issue for this [#8043](https://github.com/sequelize/sequelize/issues/8043)
