### ISSUE TITLE
Query interface suppose to return list of ids when perform bulkInsert function

### ISSUE THREAD

**Issue by boshido** [sequelize/sequelize#7988]
## What you are doing?
I use query interface for seeding prepared data into database.
And I found that query interface suppose to return all of inserted result not just first one

Based on this code
[query-interface.js#L591](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L591)

My code
```
queryInterface.bulkInsert('coordinate', [{
        lat: 13.723037,
        lng: 100.56960,
        createdAt: new Date(),
        updatedAt: new Date(),
        geoStatus: 'GOOGLE',
        geoUpdatedAt: new Date()
      }, {
        lat: 13.723037,
        lng: 100.56960,
        createdAt: new Date(),
        updatedAt: new Date(),
        geoStatus: 'GOOGLE',
        geoUpdatedAt: new Date()
      }, {
        lat: 13.723037,
        lng: 100.56960,
        createdAt: new Date(),
        updatedAt: new Date(),
        geoStatus: 'GOOGLE',
        geoUpdatedAt: new Date()
      }], {})
```
## What do you expect to happen?
  - [ 1, 2, 3]

## What is actually happening?
  - 1

__Dialect:__ mysql 
__Database version: 5.7.18
__Sequelize version:  3.25.0
__Sequelize-CLI version:  2.7.0

**Comment by boshido** [comment]
This is still an issue

**Comment by mozkng** [comment]
This is still an issue

**Comment by sushantdhiman** [comment]
Try passing `returning: true`

**Comment by mankutila** [comment]
Please pay attention that `returning: true` works only for PostgreSQL (as I found in source code) and works incorrectly for MySQL (returns only first insterted row id). I think that for MySQL it is still an issue

**Comment by Skillvendor** [comment]
Still an issue... on MySQL

**Comment by ilyago** [comment]
MySQL only return first ID with {returning: true}

**Comment by Saisreenivas** [comment]
Still an issue... on MySQL.
returning first ID even with { returning: true}.

**Comment by mansa-dev** [comment]
Still and issue

**Comment by ephys** [comment]
@mansa-dev which version of sequelize, mysql2 (the npm package) and mysql (database) are you using?

**Comment by ErwanTouba** [comment]
Hi @mansa-dev , i'm facing the same issue.

 "sequelize": "^6.15.0",
 "mysql2": "^2.3.3",
 
 MySQL 5.7

**Comment by ephys** [comment]
Same issue as https://github.com/sequelize/sequelize/issues/14325
