### ISSUE TITLE
DataTypes vs Sequelize

### ISSUE THREAD

**Issue by musicformellons** [sequelize/sequelize#7990]
In code from 2016 is see model types defined with this pattern:
```
 module.exports = function(sequelize, DataTypes) {
     const Tasks = sequelize.define("Tasks", {  id: {
       type: DataTypes.INTEGER,
[ ...etc.]
```
However in the current docs you see mainly used: Sequelize.INTEGER (or other type).
At the same time in the current docs I find also DataTypes still documented/used:
http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

On same page the Sequelize.INTEGER is used..., is that only for deferrables or something?

I tried to find whether this altered over time or something but could not find it.

When Sequelize is 'current solution' could I just alter above code into:
```
 module.exports = function(sequelize, Sequelize) {
     const Tasks = sequelize.define("Tasks", {  id: {
       type: Sequelize.INTEGER,
[ ...etc.]
```
Or would using Sequelize as argument somehow make this fail?

**Comment by eliecerthoms** [comment]
Oh god why is this module so freaking hellish to figure out!!! I'm having the same doubts.
