### ISSUE TITLE
$contains operator doesn't work with a plain value

### ISSUE THREAD

**Issue by DesignByOnyx** [sequelize/sequelize#7992]
## What you are doing?
I am trying to use the`$contains` operator to check if a column (`integer[]`) contains a value. Here is a full standalone example which shows the error:

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('postgres://...', { dialect: 'postgres' });

const Container = sequelize.define('container', {
  targets: {
    type: Sequelize.ARRAY(Sequelize.INTEGER)
  }
});

sequelize.sync().then(() => {
  Container.findAll({
    where: {
      targets: {
        $contains: 1
      }
    }
  }).then(result => {
    console.log('RESULT:', result);
  }).catch(err => {
    console.log('ERROR:', err);
  });
});
```

## What do you expect to happen?
I would expect that the query would work as [described in the docs](http://docs.sequelizejs.com/manual/tutorial/querying.html#range-operators).

## What is actually happening?
I get the following error:
> TypeError: values.map is not a function

The error goes away if the `$contains` operator is passed an array: 
```
targets: {
    $contains: [1]
}
```

__Dialect:__ postgres
__Database version:__ PostgreSQL 9.5.3
__Sequelize version:__ sequelize@4.4.0

**Comment by gabegorelick** [comment]
Still seeing this on Sequelize v4.6.0 and Postgres 9.6.5.

**Comment by guilhermeKodama** [comment]
having the same issue here

**Comment by ephys** [comment]
Hello, please open a new issue with a reproducible example :)

**Comment by WikiRik** [comment]
Do note that this issue was originally created for sequelize v4. The current release is v6 and some functionality has changed since.
Check the docs first to see how the `contains` operator functions; https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#postgres-only-range-operators
