### ISSUE TITLE
A where: $like '%query %' produces weird logs

### ISSUE THREAD

**Issue by clov3r** [sequelize/sequelize#7994]
## What you are doing?

```js
let q = 'jordan';
User.findAll({
          where: { $or: [ { firstName: { $like: '%'+ q +'%'} } , { lastName: { $like: '%'+q+'%'} } ] }
        });
```

## What do you expect to happen?
The resulting SQL should contain: 
`WHERE ("user"."firstName" LIKE '%jordan%' OR "user"."lastName" LIKE '%jordan%')`

## What is actually happening?
The SQL is output like so
`WHERE ("user"."firstName" LIKE '"\u001b[33m+23ms\u001b[0m"ordan%' OR "user"."lastName" LIKE '"\u001b[33m+23ms\u001b[0m"ordan%')`

I found a hint as to what is happening: 
https://stackoverflow.com/questions/26266232/j-specifier-in-console-log-excludes-some-properties#answer-26266961

Node escapes "%j" to the JSON stringified version of a later argument. (https://github.com/nodejs/node/blob/master/lib/util.js#L85)

I'm not sure how this is affecting the query (should only happen when using `console.log`?) but it appears to be.

I'm working around it locally by using `$like: '%%'+ q +'%'}`, but also considered `q = q.replace(/^[dfijs%]/ , "%$0")`.

Maybe something similar is needed in the query-generator.js ?

__Dialect:__ postgres / sqlite / mssql / any
__Database version:__ 9.4
__Sequelize version:__ 3.30.4

**Comment by felixfbecker** [comment]
I think it only has this treatment for the first parameter to `console.log()`, so we could always pass an empty string as the first argument.
