### ISSUE TITLE
Question: how to set all Foreign Keys to be camelCased instead

### ISSUE THREAD

**Issue by ralphchristianeclipse** [sequelize/sequelize#8000]
I'm doing an apollo server with a sequelize integration

but it seems that foreign keys are generated by CapitalizeWord rather than a default camelCased

is there an option to turn all the foreignKeys to be camelCased

![image](https://user-images.githubusercontent.com/25447231/28501814-851e93fe-7016-11e7-9880-6ad022cc3d7c.png)

Instead of UserId

i want it to be userId without putting an option to every relation just to change it to camelCased

**Comment by FrenchBully** [comment]
set the foreignKey
http://docs.sequelizejs.com/manual/tutorial/associations.html
