### ISSUE TITLE
CREATE SCHEMA IF NOT EXISTS

### ISSUE THREAD

**Issue by raxod502** [sequelize/sequelize#8004]
## What you are doing?

```js
await sequelize.createSchema('my-schema', { ifNotExists: true });
```

## What do you expect to happen?

I want to create the schema if it doesn't exist, using `CREATE SCHEMA IF NOT EXISTS`.

## What is actually happening?

The options to `createSchema` do not have any key like `ifNotExists`, so I get an error in the database log about how the schema can't be created since it already exists.

__Dialect:__ PostgreSQL
__Database version:__ 9.6.3
__Sequelize version:__ 4.3.2

**Comment by gabegorelick** [comment]
Still an issue AFAIK. This would be a nice addition.

**Comment by raxod502** [comment]
So what I do on my repositories is: automatically close issues that have been inactive for 90 days **and** have the `waiting on response` label. This eliminates the need for me to track down and triage old issues that can't be reproduced, but prevents this frustrating situation where a bug report is made, several people agree that it should be fixed, and then the issue is closed automatically. Perhaps you would consider doing that?

**Comment by sushantdhiman** [comment]
stale-bot is configured to close any issues not tagged as bug / features etc. This issue should have been marked as bug.

**Comment by Aubtin** [comment]
This issue seems to still exist. Running the following calls `CREATE SCHEMA IF NOT EXISTS` for `createSchema("inventory")` but not `createSchema("authentication")`.
```
await models.sequelize.createSchema("authentication");
await models.sequelize.createSchema("inventory");
```
