### ISSUE TITLE
ResourceRequest timed out

### ISSUE THREAD

**Issue by smithaitufe** [sequelize/sequelize#8008]
I am trying to insert 20000 records into my postgres database.

After inserting 9745,

I get this error.

```
Unhandled rejection TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/smith/Documents/projects/schoolville/carrito/src/server/node_modules/generic-pool/lib/ResourceRequest.js:58:17)
    at Timeout.bound [as _onTimeout] (/home/smith/Documents/projects/schoolville/carrito/src/server/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```
What could be responsible?
What is the solution?

This is dependencies

```
"pg": "^6.4.1",
    "pg-hstore": "^2.3.2",
    "sequelize": "^4.3.2",
```

**Comment by shukiAnavi** [comment]
Same problem here..
I would happy to know if you have a solution.

It's works fine when I'm using bulkCreate() but in this case I don't have any control on catching exceptions.

If one row in the CSV contains defective data,
the function ( bulkCreate() ) will failed so it's not an optimal solution in my case.

**Comment by northlandsnow** [comment]
I got same problem when merge some data to pg.
my code like below: 
for(let r of list) {
  let re = yield db.models.table.findOne({r})
  if(re) {
   db.model.table .update()
  } else {
   db.model.table.create()
}
}

**Comment by maxsommer** [comment]
I have the same issue – somehow the same code worked in sequelize 3, though.
Sadly this has catastrophic impact on our current schedule, thinking about downgrading to sequelize 3 again.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/8008

**Comment by smithaitufe** [comment]
@sushantdhiman Please can you explain why you closed this issue?

**Comment by sushantdhiman** [comment]
@smithaitufe I meant to link to https://github.com/sequelize/sequelize/issues/7884 and by mistake linked to this same issue :)
