### ISSUE TITLE
onDelete: cascade doesn't set on MySQL

### ISSUE THREAD

**Issue by Cartman720** [sequelize/sequelize#8009]
I am trying to add to my `hasMany` association `onDelete: 'CASCADE'` and expected to see on my server foreign key with same option, but instead I got SET NULL.

This is how my code looks like 

       Model.hasMany(models.Income, {
		foreignKey: 'companyId',
		onDelete: 'CASCADE'
	   }); 

and this is what I got after syncing

![image](https://user-images.githubusercontent.com/12465135/28600446-a6a03b72-71ba-11e7-9460-b794faf28ea4.png)

Please help me to solve this issue or show me right way to set this property.

Dialect: mysql
Sequelize version: ^4.4.2

**Comment by galmet** [comment]
@Cartman720 I am using sequelize version 4.8 and Mysql 

The following code worked for me :
associations: function() {
        Template.hasMany(Variable, {
            onDelete: 'cascade',
            hooks: true,
            as: 'variables',
            foreignKey: {
                name: 'templateId'
            }
        });
    }
