### ISSUE TITLE
Allow filtering on associated objects.

### ISSUE THREAD

**Issue by Meaglin** [sequelize/sequelize#801]
Booking.findAll({ where: { 'owner.admin' : true }, include: [ { model: User, as: 'owner' } ] });

When will something like this be possible in sequelize?

**Comment by ConAntonakos** [comment]
You can also perform the following syntax in your where clause since `v3.12.0`: `{'$nested.table.field$': 'value'}`

Reference: https://github.com/sequelize/sequelize/issues/3095#issuecomment-149277205

**Comment by arvinhubert** [comment]
@ConAntonakos , that does not work in my project, I am using 3.30.2

**Comment by YonatanKiron** [comment]
Worked for me in version `4.33.4` 
Using `{'$nested->table->field$': 'value'}`
