### ISSUE TITLE
findAll: Include multiple joins to the same model without alias at the definition level.

### ISSUE THREAD

**Issue by alexlatchford** [sequelize/sequelize#8013]
## What you are doing?

This is a contrived example but imagine a Blog that has many Users and each user can have many Blogs. Now I want to find all Blogs a user has and then bring back all the Users for that blog in a single query. I believe this should work by doing an `INNER JOIN` first to find all the affected blogs, then a `LEFT JOIN` next to find all the users for each blog. 

Trouble is with doing x2 joins to the same table I get an alias conflict and nothing I can seem to try (I've read the docs, the code and frustratingly just tried random combinations of options) and nothing I can try seems to be able to reset the alias of one of these joins successfully.

```js
const Blog = sequelize.define('user', { id: ..., title: Sequelize.STRING });
const User = sequelize.define('user', { id: ..., name: Sequelize.STRING });

Blog.belongsToMany(User);
User.belongsToMany(Blog);

// db.sync(..) etc, fill with data.

// Objective: Find all blogs for a user and return the users foreach blog..

const userId = 'abc123';

await Blog.findAll({
    include: [
        {
            // Do an INNER JOIN to find the blogs that user has access to.
            attributes: [], // Don't return any data here.
            model: User,
            where: { userId }
        },
        {
            // Now perform a 2nd LEFT JOIN to return the same table to return the users.
            model: User
        }
    ]
});
```

I've tried adding `as` to alias but because I haven't set it in the `belongToMany` it doesn't seem to take affect. I shouldn't have to alias the relationship at the definition level to be able to alias at the query level (I think) but the docs seem to suggest otherwise.

## What do you expect to happen?

I should be able to alias a query without aliasing the definition. I've tried doing:

```
    include: [
        {
            // Do an INNER JOIN to find the blogs that user has access to.
            as: 'currentUsers',
            association: Blog.associations.blogUsers,
            attributes: [], // Don't return any data here.
            model: User,
            where: { userId }
        },
        {
            // Now perform a 2nd LEFT JOIN to return the same table to return the users.
            model: User
        }
    ]
```

But even with this change I still get: `SequelizeBaseError: table name "blogUsers" specified more than once` even though I've supplied an `as` option.

## What is actually happening?

```
SequelizeBaseError: table name "blogUsers" specified more than once
```

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 3.30.2

PS. This is psuedo-code (might work but probably not), my example is a lot more complicated but tried to narrow down the example to just enough.

**Comment by jacinto123** [comment]
I have a similar issue. Is there anyway we can get this added?

**Comment by fmileto** [comment]
Same  issue here..

**Comment by znamilya** [comment]
Any news?

**Comment by StojanovicM** [comment]
I have the same problem.
If this is not working, is there any other way to do this kind of query?

**Comment by henninghorn** [comment]
You need to define the "intermediate model" which connects the two models together.
Documentation: [Belongs-To-Many associations](http://docs.sequelizejs.com/manual/tutorial/associations.html#belongs-to-many-associations)

So, beside having the User and Blog models you need the following:
```js
const BlogUsers = sequelize.define('blogUsers', {
  role: Sequelize.STRING // Just an example, it is a optional column to the relation
})

// Correction many-to-many association
User.belongsToMany(Blog, { through: BlogUsers }
Blog.belongsToMany(User, { through: BlogUsers }
```

**Comment by akpankit** [comment]
same issue, any updates. to this issue ?

**Comment by seenivasanpalanisamy** [comment]
similar issue, alias name have no effect

**Comment by abhi5658** [comment]
Similar issue described here: https://github.com/sequelize/sequelize/issues/7754
I have provided a workaround if it helps: https://github.com/sequelize/sequelize/issues/7754#issuecomment-783404779
