### ISSUE TITLE
TypeError: Class constructor Model cannot be invoked without 'new' at new Model, when i pass it to a base class constructor

### ISSUE THREAD

**Issue by TalissonJunior** [sequelize/sequelize#8021]
## What you are doing?
I´m trying to create a generic base repository class that receives a Model in the constructor,  so that others repository inherit from  it  and get some boilerplate implemented like CRUD.

Well it wasn´t hard to do it, and the typescript doesn´t complain about errors, but when try to acess my repository i receive this error : TypeError: Class constructor Model cannot be invoked without 'new' at new Cardapio.

Cardapio.ts - Model
```js
import {Table, Column, Model, PrimaryKey,AutoIncrement} from 'sequelize-typescript';

@Table
export class Cardapio extends Model<Cardapio> {

  @PrimaryKey
  @AutoIncrement
  @Column
  id: number;

  @Column
  nome: string;

  @Column
  descricao: string;

  @Column
  valor: number;
}


```
 IBaseRepository.ts  - interface class to make sure that base class will implement all the methods
```js
export interface IBaseRepository<T>{
    GetByID(identifier: number): T;
    ListAll() : T[];
    Insert(model : T): Boolean;
    Delete(identifier : number) : Boolean;
    Update(identifier:number ,model : T): Boolean;
}
```
BaseRepository.ts - Base repository that contains the generic code for all my repository class
```js
import {Sequelize, Model} from 'sequelize-typescript';
import {IBaseRepository} from '../Interfaces/IBaseRepository';

export abstract class BaseRepository<T> implements IBaseRepository<T>{

    private _model:any;
    private _sequelize:any;

    public get sequelize(){return this._sequelize };
    
    //receives a Model ex:Cardapio
    constructor(model:any){
       this._model = new model();
       this._sequelize =  new Sequelize({
            name: "db_name",
            username: "name",
            password: "password",
            host:'myhost',
            dialect:'mysql'
       });

       this._sequelize.addModels([model]);
    }

    GetByID(identifier: number){
        return this._model.findById(identifier)
        .then(model => {          
            return model;
        });
    }

    ListAll(){
        return this._model.findAll().then(result =>{
            return result;
        });
    }

    Insert(model: T){
        return true;
    }

    Delete(identifier: number){
        return true;
    }

    Update(identifier:number, model: T){
        return true;
    }
}
```
CardapioRepository - repository class that will have all the baseRepository methods,
```js
import {BaseRepository} from './BaseRepository';
import {Cardapio} from '../../Models/DataBase/Cardapio';

export class CardapioRepository extends BaseRepository<Cardapio>{

    constructor(){
        //error is pointing to this line, [TypeError: Class constructor Model cannot be invoked without 'new' at new Cardapio]
        super(Cardapio);
    }

}

```

## What do you expect to happen?
I want to be able to pass a Model to a generic base class and use it .

Dialect: mysql
Sequelize version: 4.4.2

#ERRO log
TypeError: Class constructor Model cannot be invoked without 'new' at new Cardapio (C:\Users\junio_000\Desktop\Projetos\nodejs\dist\Models\DataBase\Cardapio.js:26:42) at Function.build (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize\lib\model.js:1914:12) at Function.target.(anonymous function) [as build] (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize-typescript\lib\models\BaseModel.js:49:37) at valueSets.map.values (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize\lib\model.js:1934:41) at Array.map (native) at Function.bulkBuild (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize\lib\model.js:1934:22) at Function.target.(anonymous function) [as bulkBuild] (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize-typescript\lib\models\BaseModel.js:49:37) at Query.handleSelectQuery (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize\lib\dialects\abstract\query.js:302:27) at Query.formatResults (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize\lib\dialects\mysql\query.js:116:21) at Utils.Promise.then.then.results (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\sequelize\lib\dialects\mysql\query.js:69:29) at tryCatcher (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\promise.js:512:31) at Promise._settlePromise (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\promise.js:569:18) at Promise._settlePromise0 (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\promise.js:614:10) at Promise._settlePromises (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\promise.js:693:18) at Async._drainQueue (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\async.js:133:16) at Async._drainQueues (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\async.js:143:10) at Immediate.Async.drainQueues (C:\Users\junio_000\Desktop\Projetos\nodejs\node_modules\bluebird\js\release\async.js:17:14) at runCallback (timers.js:672:20) at tryOnImmediate (timers.js:645:5) at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by tylerjwatson** [comment]
This isn't really an issue with sequelize itself, but your Typescript is wrong.  In your constructor of the base repository you should `this._sequelize.addModels([this._model]);`.

**Comment by TalissonJunior** [comment]
Well i was só Focus that i didn't notice , thanks man

**Comment by karim-mirazul** [comment]
after implement exactly same code I got this error : 

D:\Miraz\Programming\Sequalize\seq-ts\models\Cardapio.js:23
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^

TypeError: Class constructor Model cannot be invoked without 'new'
    at new Cardapio (D:\Miraz\Programming\Sequalize\seq-ts\models\Cardapio.js:23
:42)
    at CardapioRepository.BaseRepository (D:\Miraz\Programming\Sequalize\seq-ts\
BaseRepository.js:8:23)
    at new CardapioRepository (D:\Miraz\Programming\Sequalize\seq-ts\CardapioRep
ository.js:19:23)
    at Object.<anonymous> (D:\Miraz\Programming\Sequalize\seq-ts\CardapioReposit
ory.js:24:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3


Can you please share @TalissonJunior  tsconfig.json file and package.json file
