### ISSUE TITLE
Suggestions for implementing a caching layer

### ISSUE THREAD

**Issue by babsonmatt** [sequelize/sequelize#803]
Any suggestions as to where I should start in terms of implementing a caching layer in front of sequelize?  I'd like to be able to check memcached on a find for example before allowing sequelize to pull from the DB (unless need be).  What would be the best way to go about doing this?

Much appreciated!

**Comment by janmeier** [comment]
Discussion on plugins is going on in https://github.com/sequelize/sequelize/issues/2508 and  https://github.com/sequelize/sequelize/issues/2462
