### ISSUE TITLE
Exception on changeColumn with postgresql (or: query with multiple statements)

### ISSUE THREAD

**Issue by renan-ti** [sequelize/sequelize#8034]
## What you are doing?
Trying to execute a migration:

```js
    await queryInterface.changeColumn('MyTable', 'myColumn', {
      type: Sequelize.TEXT
    });
```
This tries to execute the following statement:
```sql
ALTER TABLE "MyTable" ALTER COLUMN "myColumn" DROP NOT NULL;ALTER TABLE "MyTable" ALTER COLUMN "myColumn" DROP DEFAULT;ALTER TABLE "MyTable" ALTER COLUMN "myColumn" TYPE TEXT;
```
So, I also tried:
```js
    await queryInterface.sequelize.query('ALTER TABLE "MyTable" ALTER COLUMN "myColumn" DROP NOT NULL;ALTER TABLE "MyTable" ALTER COLUMN "myColumn" DROP DEFAULT;ALTER TABLE "MyTable" ALTER COLUMN "myColumn" TYPE TEXT');
```
Same problem.

## What do you expect to happen?
No errors, migration complete.

## What is actually happening?

```
TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (/home/.../node_modules/sequelize/lib/dialects/postgres/query.js:112:17)
```
I did some debugging and it appears that the commit for #7888 broke it. In query.js:98 and so on, it assumes that queryResult will be a Result object, however, when there are multiple statements, it is an array of Result objects. It also assumes in line 112 that there will be at least 1 row, which is not the case for an ALTER statement.

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.4.2

**Comment by renan-ti** [comment]
Upon further inspection, this is duplicating #7998.

**Comment by aviranco** [comment]
I have the same issue. "pg": "^7.2.0",    "sequelize": "^4.7.5"
