### ISSUE TITLE
Sync with alter errors out when constraint exists

### ISSUE THREAD

**Issue by Misiur** [sequelize/sequelize#8041]
## What you are doing?
```js
import Sequelize from 'sequelize';

const db = new Sequelize('testdb', 'root', '', {
  host: 'localhost',
  dialect: 'mysql',
});

db.authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.log(`Unable to connect to the database: ${err}`);
  });

db.sync({ alter: true });

const Foo = db.define('foos', {});

const Bar = db.define('bars', {});

Bar.hasMany(Foo);
```

## What do you expect to happen?
_It should create my schema on first run, and add new columns on subsequent runs_

## What is actually happening?
_It creates schema on first run, but on second run it errors out_

```
Unhandled rejection SequelizeDatabaseError: Can't create table `testdb`.`#sql-8cc_61` (errno: 121 "Duplicate key on write or update")
```

__Dialect:__ mysql
__Database version:__ 10.1.8-MariaDB
__Sequelize version:__ 4.4.2

**Comment by whittakergroupinc** [comment]
Same: Unhandled rejection SequelizeDatabaseError: Can't write; duplicate key in table '#sql-6215_4f2'

**Comment by bruno02100** [comment]
Having the same issue.

**Comment by zl810881283** [comment]
Having the same issue.

**Comment by Misiur** [comment]
Still an issue with 4.10

**Comment by lessu** [comment]
Having the same issue.with 4.12.0

**Comment by robin-garnham** [comment]
Also having this issue. I have it with a number of tables and find if I remove the constraints manually in the DB then it passes over them... but then the next time it re-syncs it fails again

**Comment by grahammills** [comment]
This still seems to be an issue in 4.20.3
Does anyone have an update to this?

**Comment by cyrille-gaucher** [comment]
related to this: https://github.com/sequelize/sequelize/issues/7606

**Comment by sushantdhiman** [comment]
Duplicate of https://github.com/sequelize/sequelize/issues/8041

**Comment by niksudan** [comment]
@sushantdhiman This is issue 8041 - did you close this by mistake?

**Comment by kartik-proctur** [comment]
Do Anyone have solution for this??

**Comment by RahmatAliMalik5** [comment]
I have the same issue. I have updated the `sequelize` and it solved my problem...
