### ISSUE TITLE
Where is the api for getAssociations?

### ISSUE THREAD

**Issue by hackhat** [sequelize/sequelize#8047]
I always had issues with sequelize docs/api being very confusing, but now seems like there is missing info about `getAssociations`. 

Tried to:

 - search in the http://docs.sequelizejs.com docs;
 - http://docs.sequelizejs.com/class/lib/associations/belongs-to-many.js~BelongsToMany.html

The only thing I find is 
![image](https://user-images.githubusercontent.com/11173732/28832700-20b91b30-76d5-11e7-9ac0-a91244e74ab4.png)

Which is worthless. 

(I would hope some other library comes up with a better API because I've wasted so much time looking for things on these docs.)

**Comment by snewell92** [comment]
`getAssociations` appears to be an internal method, not exposed as part of the Sequelize API. It's referenced in the docs if you wanted to explore the code to learn how the `has` method retrieves associations. (Not a Sequelize team member, just a guy - anyone who knows better feel free to correct me!).

Also, if you've wasted time, consider investing a Saturday or a morning in exploring another ORM. There's more than one choice, and they aren't hard to grasp.

The docs are quite good imo - and dropping by in a slack channel has helped me out before.

**Comment by hackhat** [comment]
@snewell92  

> getAssociations appears to be an internal method, not exposed as part of the Sequelize API. It's referenced in the docs if you wanted to explore the code to learn how the has method retrieves associations. (Not a Sequelize team member, just a guy - anyone who knows better feel free to correct me!).

Thanks but when I mean `getAssociations` I mean `library.getBooks()` after you made a relationship between `Library` and `Book`. So is definitively a public method.

Look at http://docs.sequelizejs.com/manual/tutorial/associations.html 

```
const User = sequelize.define('user', {/* ... */})
const Project = sequelize.define('project', {/* ... */})

// One-way associations
Project.hasOne(User)
```

> In this example hasOne will add an attribute projectId to the User model!
> Furthermore, Project.prototype will gain the methods **getUser** and **setUser** according....

I'm looking to understand where is the api for that `getUser` or more generically `get${modelName}`.


> Also, if you've wasted time, consider investing a Saturday or a morning in exploring another ORM. There's more than one choice, and they aren't hard to grasp.

At this moment the project is too big to move to another ORM. Last time I've checked ORM (last year) sequelize alternatives are even worse.

Yeah, maybe I will try the slack.

**Comment by snewell92** [comment]
Ah okay. I'm not familiar with that feature of Sequelize. [I've only used include in my queries](http://docs.sequelizejs.com/manual/tutorial/querying.html#relations-associations) to retrieve associated data. Maybe someone else can chime in if they've used that feature before.
