### ISSUE TITLE
createTable doesn't handle VIRTUAL fields

### ISSUE THREAD

**Issue by kukukk** [sequelize/sequelize#8054]
## What you are doing?
I have a Profile model with a VIRTUAL field defined like:
```js
    avatar_base_url: {
        type: DataTypes.VIRTUAL,
    }
```
Instead of manually defining all fields in the migration file I'm using the following code snippet to generate the table:

```js
let model = require('../models').Profile;

module.exports = {
    up: (queryInterface, Sequelize) => {
        queryInterface.createTable(model.tableName, model.attributes, model.options);
    },

    down: (queryInterface, Sequelize) => {
        queryInterface.dropTable(model.tableName);
    },
};
```

## What do you expect to happen?
I expect the profile table to be created.

## What is actually happening?
I get the following error:
> Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VIRTUAL, `user_id` INTEGER NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`)' at line 1

__Dialect:__ mysql
__Database version:__ 5.6.27
__Sequelize version:__ 4.3.0

**Comment by SeasonSu** [comment]
同上，新版怎么有这个问题，是不是改了写法

**Comment by kukukk** [comment]
Can somebody translate it?
