### ISSUE TITLE
Where is a list of function that can be use with sequelize.fn()?

### ISSUE THREAD

**Issue by pda2564** [sequelize/sequelize#8055]
Hi,
I can't find a docs or link that lists all function that can be used with sequelize.fn().
E.g: sequelize.fn('UPPER')...
Anyone can list me?
Thanks

**Comment by zxdvd** [comment]
IMO, all built-in / self-created function can be used.
And it's had to have a list in sequelize since every database has its own functions.

**Comment by fov42550564** [comment]
how to self-created function

**Comment by fov42550564** [comment]
I want to use sequelize do like this:
```sql
SELECT momey/100 as yuan from table;
```
show can I use sequelize.fn or other resolvent. thanks.

**Comment by zxdvd** [comment]
@fov42550564  you can define virtual field in you model.
[definition](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#defining-as-part-of-a-property)

**Comment by fov42550564** [comment]
@zxdvd  thanks very mush
