### ISSUE TITLE
Error: Dialect needs to be explicitly supplied as of v4.0.0 - being thrown even though mysql is supplied in two files

### ISSUE THREAD

**Issue by afflatus480** [sequelize/sequelize#8067]
## What you are doing?

```js
______
// index.js
if (config.use_env_variable) {
    var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
    var sequelize = new Sequelize('burger_shop_DB', 'root', 'hoist', {
        host: "127.0.0.1",
        dialect: 'mysql',
        define: {
            timestamps: false
        }
    });
//config.json
 "production": {
        "use_env_variable" : "JAWS_URL",
        "dialect": "mysql"
    }
}
```
}

#### preface: 

zobri@LAPTOP-OKM3KH21 MINGW64 ~/UAbcProjects/sequelizedBurger (master)
$ sequelize -v
<strong>Sequelize [Node: 6.11.1, CLI: 2.7.0, ORM: 4.4.2]</strong>

## What do you expect to happen?
I'm trying to host my sequelize app on Heroku

## What is actually happening?
<em> /app/node_modules/sequelize/lib/sequelize.js:169 
Aug 05 22:09:54 seq-eat-da-burga app/web.1:       throw new Error('Dialect needs to be explicitly 
                                                                                  supplied as of v4.0.0'); 
Aug 05 22:09:54 seq-eat-da-burga app/web.1:       ^ 
Aug 05 22:09:54 seq-eat-da-burga app/web.1: Error: Dialect needs to be explicitly supplied as of v4.0.0     
                                                                             at new Sequelize 
                                                                           (/app/node_modules/sequelize/lib/sequelize.js:169:13) 
                                                                         at Object.<anonymous> (/app/models/index.js:12:21) </em>

<strong>Reference my index.js snippet above, where MySQL is implicitly stored as dialect</strong>

I noticed you closed a similar issue 5 days ago, which stumped the heck out of me while trying to debug - any guidance would be greatly appreciated.

**Comment by afflatus480** [comment]
//config.json
 "production": {
        "use_env_variable" : "JAWS_URL",
        "dialect": "mysql"
    }
}
^^
**## solution**
"use_env_variable": "JAWSDB_UR" instead of  "use_env_variable" : "JAWS_URL",

**Comment by yassinMk** [comment]
face the same issue and fixed it by setting the NODE_ENV to the specified environment in the config.json

**Comment by nzediegwu1** [comment]
yassinMK, pls how did you do that

**Comment by nzediegwu1** [comment]
afflatus, pls whats the difference in your solution..just the comma?

**Comment by sergiyvoytovych** [comment]
Check your config file (env names)





    {
      development: {
        username: 'root',
        password: null,
        database: 'database_development',
        host: '127.0.0.1',
        dialect: 'mysql'
      },
      test: {
        username: 'root',
        password: null,
        database: 'database_test',
        host: '127.0.0.1',
        dialect: 'mysql'
      },
      production: {
        username: 'root',
        password: null,
        database: 'database_production',
        host: '127.0.0.1',
        dialect: 'mysql'
      }
    }

**Comment by yassinMk** [comment]
@nzediegwu1 take a look at this answer [https://stackoverflow.com/a/35040401/4467928](https://stackoverflow.com/a/35040401/4467928)

**Comment by nzediegwu1** [comment]
Thanks a lot guys. I have been able to resolve my issue. My observation is that .env file which I used to define my environment variable was not being read by heroku node.js when my app has not yet been successful started (when my server is not get up). So I had to manually enter the environment variable via console or within the sequelizd model index file for it to work

**Comment by Asharudheen-VNC** [comment]
Use this 
export NODE_ENV=development
