### ISSUE TITLE
Bug all hange, when create more than 4 db.sequelize.transaction() 

### ISSUE THREAD

**Issue by KlachkoAlexander** [sequelize/sequelize#8069]
## What you are doing?

```js
function saveRecords(createObj, table) {
  const createObj = [];
  const updateObj = [];
  const results = [[], [], []];
  const insert = [];
  const update = [];
  let promise = Promise.resolve();
  let promiseInsert = Promise.resolve();

  const options = { validate: false };
  return promise.then((result) => {
      createObj.forEach(itemObj => {
        promiseInsert = Promise.resolve().then((result) => {
          return db.sequelize.transaction().then(function (t) {
            return table.create(itemObj, options, {transaction: t})
            .then((resultCreate) => {
              results[1].push(resultCreate.dataValues);
            })
            .then(function () {
              return t.commit();
            }).catch(function (err) {
              const errObj = {};
              errObj.message = err.message ? err.message.replace(/['"]+/g, '') : '';
              errObj.detail = err.parent && err.parent.detail ? err.parent.detail.replace(/['"]+/g, '') : '';
              errObj.id = itemObj.sfRecordId;
              insert.push(errObj);
              return t.rollback();
            });
          })
        });
      })
      return promiseInsert.then((resultInsert) => {
        return resultInsert;
      });
  })
  .then((result) => {
	console.log('results[1]: ', results[1]);
	return results;
  })
  .catch((err) => {
    return Promise.reject(err);
  });
}
```

## What do you expect to happen?
I expect that valid data will insert, and invalid data don`t insert

## What is actually happening?
All hang, as only createObj.length >= 5

Dialect: postgres
Database version: 9.6.2
Sequelize version: 3.30.2

**Comment by Mikhail1994** [comment]
Is anybody going to answer? This question is very relative to me as well. Considering that bulkCreate fails on first object that has invalid fields the only way to create an amount of data is to loop through an array of objects and use transaction's rollback if some of them has invalid data and commit valid ones.

**Comment by ldmarz** [comment]
Hello, I had the same problem and I figured out than increasing de pool size of my connection allows me to execute more than 4 transactions, but this is not ok, and I see i had missing to pass de transaction object to all sub querys involved, You make sure you pass always de transaction to all sub queryes

**Comment by iamjochem** [comment]
I use MySQL and I believe am seeing the same behaviour, it *seems* that there is a structural problem related to the use of transactions whose origin is not tied to any particular "db driver".

AFAICT sequelize seems to run into problems with transactions when the number of running transactions starts to exceed the max number of connections available in the pool. I would like to note that it does not seem to be something simple or clear cut - I have been trying, on and off, for weeks to develop a clear, robust repro-script for this ... so far without success ... I will keep trying!

@sdepold, @felixfbecker, et al - any advice, opinions on the issues related to transactions (to me there seems to be mounting evidence that something is awry)? It would be great if you could confirm/deny that there might be something structurally amiss (as oposed to everyone with [related] transaction problems just "doing it wrong" ... which is possibility)

**Comment by KlachkoAlexander** [comment]
I solved this problem when move away transaction from my code. 
function saveRecords(listObj, checkFields, table) {
  const createObj = [];
  const updateObj = [];
  const results = [[], [], []];
  const insert = [];
  const update = [];
  let promise = Promise.resolve();
  let promiseInsert = Promise.resolve();
  listObj.forEach(itemObj => {
    if (checkProperty(itemObj, checkFields)) {
      if (!itemObj.id) {
        createObj.push(itemObj);
      } else {
        updateObj.push(itemObj);
      }
    }
  });
  const options = {validate: false};
  return promise.then((result) => {
    return table.bulkCreate(createObj, options)
    .catch(function (err) {
      createObj.forEach(itemObj => {
        promiseInsert = Promise.resolve().then((result) => {
          return table.create(itemObj, options)
          .then((resultCreate) => {
            results[1].push(resultCreate.dataValues);
          })
          .catch(err => {
            const errObj = {};
            errObj.message = err.message ? err.message.replace(/['"]+/g, '') : '';
            errObj.detail = err.parent && err.parent.detail ? err.parent.detail.replace(/['"]+/g, '') : '';
            errObj.id = itemObj.sfRecordId ? itemObj.sfRecordId : itemObj.sfLEId;
            insert.push(errObj);
          });
        });
      })
      return promiseInsert.then((resultInsert) => {
        return resultInsert;
      });
    });
  })
  .then((resultObj) => {
    if (resultObj && resultObj.length > 0 && results.length > 1 && results[1].length === 0) {
      results[1] = resultObj.map(i => {
        return i.dataValues;
      });
    }

    let i = 0;
    updateObj.forEach(itemObj => {
      promise = promise.then((result) => {
        return table.update(itemObj, {
          where: {id: itemObj.id},
          returning: true
        })
        .then((resultUpdate) => {
          if (resultUpdate[1].length > 0) {
            results[0].push(resultUpdate[1][0].dataValues);
          }
        })
        .catch(err => {
          const errObj = {};
          errObj.message = err.message ? err.message.replace(/['"]+/g, '') : '';
          errObj.detail = err.parent && err.parent.detail ? err.parent.detail.replace(/['"]+/g, '') : '';
          errObj.id = itemObj.sfRecordId ? itemObj.sfRecordId : itemObj.sfLEId;
          update.push(errObj);
        });
      });
    });
    return promise.then((result) => {
      results[2].push({updateErr: update});
      results[2].push({insertErr: insert});
      return results;
    });
  })
  .catch((err) => {
    return Promise.reject(err);
  });
}
