### ISSUE TITLE
Associations belongsTo's create return Promise<sourceInstance> instead Promise<newAssociatedObject>

### ISSUE THREAD

**Issue by shaunho57** [sequelize/sequelize#8074]
## What you are doing?

```js
// associate Projects with Users
Projects.belongsTo(Users);

// attempt to use project instance to create user that associate with project
project.createUser(data).then((newRecord) => {
    // newRecord suppose to be user, but project returned.
});
```

## What do you expect to happen?
`newRecord` is `user`

## What is actually happening?
`newRecord` is `project`

__Dialect:__ mysql
__Database version:__ 5.7.9
__Sequelize version:__ 4.4.2

**Comment by guilleasz** [comment]
Inside the newRecord should be a project, inside the project is the user you created.

**Comment by shaunho57** [comment]
@guilleasz 
> Inside the newRecord should be a project, inside the project is the user you created.

newRecord is the project instance. Eventually inside the project instance don't have any other instance. 

------------------

Moreover, hasOne / hasMany's create return Promise\<newAssociatedObject>
```js
Users.hasMany(Projects);

user.createProject(data).then((newRecord) => {
    // newRecord is project. which is expected.
});
```

**Comment by guilleasz** [comment]
In the second argument of the createUser you need to add options with the include property, for the User to be added in the project.
