### ISSUE TITLE
Many updates get deadlock error

### ISSUE THREAD

**Issue by agafonovnikita** [sequelize/sequelize#8075]
### Use:

nodejs + sequelizejs + mssql

### SequelizeDatabaseError:  
Transaction (Process ID 57) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

### sequlize.js generate:

sql: 'SET IDENTITY_INSERT [DeviceCurrentData] ON; MERGE INTO [DeviceCurrentData] WITH(HOLDLOCK) AS [DeviceCurrentData_target] USING (VALUES(9, N\'28.300000\', \'2017-08-07 15:26:28.000\', 12)) AS [DeviceCurrentData_source]([Id], [Value], [DateStamp], [DevParamId]) ON [DeviceCurrentData_target].[Id] = [DeviceCurrentData_source].[Id] WHEN MATCHED THEN UPDATE SET [DeviceCurrentData_target].[Value] = N\'28.300000\', [DeviceCurrentData_target].[DateStamp] = \'2017-08-07 15:26:28.000\', [DeviceCurrentData_target].[DevParamId] = 12 WHEN NOT MATCHED THEN INSERT ([Id], [Value], [DateStamp], [DevParamId]) VALUES(9, N\'28.300000\', \'2017-08-07 15:26:28.000\', 12) OUTPUT $action, INSERTED.*; SET IDENTITY_INSERT [DeviceCurrentData] OFF;'

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/7484
