### ISSUE TITLE
Support for db:drop and db:create

### ISSUE THREAD

**Issue by aledalgrande** [sequelize/sequelize#8082]
## What you are doing?
Creating and dropping database for testing.

```js
// ...
const sequelize = new Sequelize('postgres', config.username, config.password, {
  dialect: config.dialect,
  host: config.host,
});

const database = config.database;
logger.info(`Creating database "${database}"...`);
sequelize.query(`CREATE DATABASE IF NOT EXISTS "${database}"`).then(() => logger.info('Database created'));
```

## What do you expect to happen?
This is fine for creating a database. But it would be much nicer if we had a command like `sequelize db:create`, and `sequelize db:drop` for dropping a database. This is mostly used during development for running tests.

## What is actually happening?
There is no functionality built to automate this.

__Dialect:__ any
__Sequelize version:__ 4.4.2

**Comment by sushantdhiman** [comment]
Sequelize CLI related

**Comment by aledalgrande** [comment]
There is need to support in _core_ though, see https://github.com/sequelize/cli/issues/70:

> Once the core supports something like sequelize.createDatabase and sequelize.dropDatabase

**Comment by aledalgrande** [comment]
I can contribute the methods if resources are constrained.

**Comment by sushantdhiman** [comment]
createDatabase  / dropDatabase could be achieved pretty easily with raw query. If you are open to it please consider sending PR to cli project :)

**Comment by aledalgrande** [comment]
Got it! I'm actually using sh + js scripts that do that in my projects.

**Comment by dagumak** [comment]
@sushantdhiman I understand where you are coming from, but the more systematic approach would be to have a database creation step as well as a drop step for multiple environments. It's something I really appreciate having in Rails, and it can go a long way when you have multiple developers onboarding.

**Comment by Jarred-Sumner** [comment]
+1 to what @dagumak said.

One of the things that makes Rails great is it handles details like these really well. Sequelize's lack of support for this breaks the expectations of developers new to Sequelize, and is a less happy experience.

That being said, I completely lack context on what the priorities are and this is free software probably put together in many people's spare time. I feel like a jerk complaining about this.

**Comment by sushantdhiman** [comment]
This issue was about CLI, which now supports `db:create` / `db:drop`

**Comment by Jarred-Sumner** [comment]
Yes, however it looks like it might not for PostgreSQL:
```bash
$ sequelize db:drop

Sequelize CLI [Node: 8.9.1, CLI: 3.2.0, ORM: 4.31.2]

Loaded configuration file "config/config.js".
Using environment "development".

ERROR: Dialect postgresql does not support db:create / db:drop commands
```

**Comment by sushantdhiman** [comment]
There is no `postgresql` dialect, there is `postgres`

**Comment by jayarjo** [comment]
There's still no support for sqlite dialect, although might have been easiest to implement?

**Comment by wly185** [comment]
in config.json use dialect:'postgres' https://www.youtube.com/watch?v=3qlnR9hK-lQ

**Comment by taylor1119** [comment]
I can see the error (ERROR: cannot drop the currently open database) when I run this command. (heroku run npx sequelize-cli db:drop --app $HEROKU_APP_NAME) in bitbucket-pipeline.yml.
