### ISSUE TITLE
BulkCreate updateOnDuplicate crash with foreignKey

### ISSUE THREAD

**Issue by Unsigno** [sequelize/sequelize#8083]
## What you are doing?
I am doing a bulkCreate of a model with a foreignKey

```js

User = sequelize.define("user", {
    public_id: {
        type: DataTypes.STRING,
        unique: true
    },
    name: DataTypes.STRING
},{
    underscored: true
});

Group = sequelize.define("group", {
    name: DataTypes.STRING
},{
    underscored: true
});

User.belongsTo(Group);
Group.hasMany(User);

Group.create({ name; 'Group1' })
// then
User.bulkCreate([{
    public_id: 'aaa',
    name: 'User1',
    group_id: 1
},{
    public_id: 'bbb',
    name: 'User2',
    group_id: 1
}], {
    updateOnDuplicate: [ 'group_id' ],
})
// then
// i remove User2 and set group_id NULL to User1
// then 
// same bulk as before 

```

## What do you expect to happen?
I expect the User1 set to group_id 1, and User2 inserted 

## What is actually happening?
It works on DB , the user with duplicated "public_id" is updated and User2 is inserted , but sequelize crash throwing : 
 
TypeError: Cannot read property 'set' of undefined
    at results.forEach (C:\...\node_modules\sequelize\lib\model.js:2354:27)

If i change "updateOnDuplicate: [ 'name' ]" it works well , on DB and Sequelize , but it crash with group_id.

Also if check the result Sequelize set the new id for User2 to User1 ( this is advertised on the doc , so its not the problem, but could be related )

__Dialect:__ mysql
__Database version:__ 5.7.14
__Sequelize version:__ 4.4.2

**Comment by sampleblood** [comment]
did you fix the problem? It happens to me too

**Comment by sampleblood** [comment]
maybe problem with that primaryKey and unique key should only have one. I removed 'id' and use another unique key as primaryKey,  it worked.

**Comment by Unsigno** [comment]
At the moment i haven't a clean solution .

``` js 

var users = { ... }
var public_ids = users.map(function(user) return user.public_id)

User.bulkCreate([
...
],{
    ignoreDuplicates: true
})

User.findAll({ where: { public_id: { $in: public_ids } }})

groupInstance.setUsers(userInstances);
```
