### ISSUE TITLE
On migration file create, auto detect model change

### ISSUE THREAD

**Issue by tarakeshwebdeveloper** [sequelize/sequelize#8086]
I have a model say User with columns Id, first_name, last_name.

a migration file "user-init" is created and db:migrate created the table and column in the database.

Now I would like add a new column in the User model "email, phone, address"

When I create a migration, I am getting empty "Up and Down" routines rather I would expect it would have detected the model changes and filled "Up and Down".

Now it is a headache changing at 2 places.
1. create migration with the column
2. add the new column in the model ie User.js

if there is any solution, it is much appreciated. I am comparing with EntityFramework the way it works.

**Comment by sushantdhiman** [comment]
A version of https://github.com/sequelize/cli/issues/157 , CLI related issue
