### ISSUE TITLE
Paranoid option does not work with associations

### ISSUE THREAD

**Issue by bengotow** [sequelize/sequelize#809]
Hi folks,

I'm using `sequelize@2.0.0-alpha2` with `sequelize-postgres@1.7.0-alpha2`. In my app, I'm using Sequelize with the paranoid option enabled and declaring a relationship like this:

```
User.hasMany(Stream, { as: 'RequestedStreams', joinTableName: 'StreamsWaitingUsers'})
Stream.hasMany(User, { as: 'WaitingUsers', joinTableName: 'StreamsWaitingUsers'})
```

Now, all is well, until I go and delete a user from a stream:

```
stream.removeWaitingUser(user)
```

When I do that, the relationship stays in the join table, but deleted_at is set to the current timestamp. This is correct behavior with the paranoid flag set, as far as I know.

When I then query for the stream's waiting users:

```
stream.getWaitingUsers() // returns deleted items
```

I get all of the deleted relationships as well as the active ones. In order to get the correct result, I have to manually filter this query by adding a WHERE deleted_at IS NULL:

```
stream.getWaitingUsers({where: 'deleted_at IS NULL'}) // works
```

I don't care all that much about keeping the deleted records around, and I might just disable paranoid mode for the time being. It'd be great to get this fixed though! I'd be happy to contribute but I'm not sure how to cleanly resolve this issue.

**Comment by tommedema** [comment]
@mickhansen does that mean that paranoid should not be used?

**Comment by mickhansen** [comment]
@tommedema It's not supported for N:M associations.

**Comment by djmccormick** [comment]
Boooooooo

**Comment by lehaiquantb** [comment]
Any update? It still not working
