### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by CnApTaK** [sequelize/sequelize#8099]
## What you are doing?
I want to create one foreign key (FK), but actually creates two

```js
sequelize.define('user', {
	userId: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true }
});
sequelize.define('session', {
	sessionId: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true }
	, userId: { type: Sequelize.INTEGER, allowNull: false, references: { model: 'users', key: 'userId' }}
});
```

## What do you expect to happen?
I believe that you should create only one FK
And maybe because of that when i'm trying to use .sync({ alter: true, force: false })
i got error: constraint "userId_foreign_idx" for relation "sessions" already exists

## What is actually happening?
CONSTRAINT "sessions_userId_fkey" FOREIGN KEY ("userId")
        REFERENCES public.users ("userId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "userId_foreign_idx" FOREIGN KEY ("userId")
        REFERENCES public.users ("userId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION

__Dialect:__ postgres
__Database version:__ 9.6.4 (pg@6.4.1 or latest)
__Sequelize version:__ 4.4.2 or 4.4.3

**Comment by CnApTaK** [comment]
Rolled back a few versions and found out that in the version sequelize@3.30.4 it works correctly. Only one FK is created and no errors occur when calling .sync({ alter: true, force: false }). So the bug appeared in version 4.0...  a few months ago...

**Comment by iamjoyce** [comment]
Did you specify any relationships? It happened to me before (it was version 3.x)

For example,
```js
session.belongsTo(user, { foreignKey: "userId" });
user.hasMany(session, { foreignKey: "userId" });
```

**Comment by CnApTaK** [comment]
yep.. i use

```
const User = sequelize.define('user', {
	userId: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true }
	, dtCreated: { type: Sequelize.DATE, defaultValue: Sequelize.NOW, allowNull: false }
	, isAdmin: { type: Sequelize.BOOLEAN, allowNull: false, defaultValue: false }
	, login: { type: Sequelize.TEXT, unique: 'compositeIndex', allowNull: false }
	, hash: { type: Sequelize.TEXT, allowNull: false }
	, salt: { type: Sequelize.TEXT, allowNull: false }
}, modelOptions );
const Session = sequelize.define('session', {
	sessionId: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true }
	, dtCreated: { type: Sequelize.DATE, defaultValue: Sequelize.NOW, allowNull: false }
	, userId: { type: Sequelize.INTEGER, allowNull: false}
	, value: { type: Sequelize.TEXT, unique: 'compositeIndex', allowNull: false }
}, modelOptions );
sequelize
	.authenticate()
	.then(() =>	{
		sequelize
			.sync({ alter: true, force: false })
```

no problem for me in 3.30.4

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/7606
