### ISSUE TITLE
Comment for Index

### ISSUE THREAD

**Issue by NessunKim** [sequelize/sequelize#8109]
## What you are doing?

```js
{
  engine: 'Mroonga',
  comment: 'engine "InnoDB"',
  indexes: [{
    type: 'FULLTEXT',
    fields: ['content'],
    comment: 'parser "TokenBigramIgnoreBlankSplitSymbolAlphaDigit"',
  }],
}
```

## What do you expect to happen?
Index comment is used for specifing parser in mroonga storage engine.

```ALTER TABLE `search` ADD FULLTEXT INDEX `search_content` (`content`) COMMENT 'parser "TokenBigramIgnoreBlankSplitSymbolAlphaDigit"'```

## What is actually happening?
Index comment doesn't work.

```ALTER TABLE `search` ADD FULLTEXT INDEX `search_content` (`content`)```

__Dialect:__ mysql
__Database version:__ 10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
__Sequelize version:__ 4.4.2

**Comment by sushantdhiman** [comment]
Sequelize does not support field `comment`, https://github.com/sequelize/sequelize/issues/4386
