### ISSUE TITLE
This socket has been ended by the other party

### ISSUE THREAD

**Issue by euqen** [sequelize/sequelize#8111]
Hi, @sushantdhiman. Unfortunately #7924 didn't help with this issue [sidorares/node-mysql2](https://github.com/sidorares/node-mysql2/issues/447). So after upgrading sequelize to 4.4.4 this issue is still reproducing. I came across this problem and figured out that if I validate connections in following way, this problem will disappear:

```
function validate(connection) {
    return connection &&
           connection._fatalError === null &&
           connection._protocolError === null &&
           !connection._closing &&
           !connection.stream.destroyed;
}
```
Sometimes socket closes and sequelize unable to use it. I don't understand why it happens but anyway I have this fix. If you approve this fix I'll create pull request with this changes. Or maybe you have some input here which can help

**Comment by sushantdhiman** [comment]
@euqen This fix looks good to me. Please open a PR with this change

**Comment by sushantdhiman** [comment]
Close https://github.com/sequelize/sequelize/pull/8112

**Comment by zhangbowy** [comment]
How to solve this problem？
![image](https://user-images.githubusercontent.com/33514252/125413009-075c1c80-e3f2-11eb-8cf9-0852ce55ee0d.png)
