### ISSUE TITLE
No more beforeDefine in docs

### ISSUE THREAD

**Issue by Alexsey** [sequelize/sequelize#8119]
It was there and I have very important scenarios based on it. In [hooks section of the docs](http://docs.sequelizejs.com/manual/tutorial/hooks.html) there is no mention of it any more. Did it become deprecated?

**Comment by p0vidl0** [comment]
> For a full list of hooks, see [Hooks file](https://github.com/sequelize/sequelize/blob/master/lib/hooks.js#L7).

**Comment by Alexsey** [comment]
Hm... this link should be in the docs. May be I'll make a PR for that. In any way - thank you for it

**Comment by v1shva** [comment]
Why this hasn't been added yet?

**Comment by frlinw** [comment]
I spent 1h to find a clue about `beforeDefine`.
I'm new to sequelize and I told you, this doc will kill me.
For christmas I want a complete docs for v5 !
