### ISSUE TITLE
Cannot access Alias value. Alias is returning undefined.

### ISSUE THREAD

**Issue by intcreate** [sequelize/sequelize#8121]
If you zoom in the images will be easier to see.

aliasName: -1

The value of aliasName is -1.

![3](https://user-images.githubusercontent.com/23142395/29288031-e2e6ef58-80fc-11e7-8b1a-f5d0b66fae4a.png)

aliasName: undefined

aliasName is giving me undefined. 

![2](https://user-images.githubusercontent.com/23142395/29288038-e9dfc5e6-80fc-11e7-806c-b62768887626.png)

**Comment by younowidan** [comment]
@intcreate I opened an issue about the same thing a few hours ago.

If you'll use `posts[0].get('aliasName')` it should work for you, for some reason when using the sequelize functions the direct property access is not working.

**Comment by intcreate** [comment]
@younowidan thanks that worked
