### ISSUE TITLE
Issue with filtering on the join model for belongsToMany associations

### ISSUE THREAD

**Issue by prismm** [sequelize/sequelize#8123]
The Sequelize docs suggest that you can filter your query on join table attributes using the following params on the options object:
[options.include[].through.where]

I've tried to use this formulation in the code below and found that the filtering does not work. 

Model User and model Network are associated through the join table network-affiliations, which has additional attribute (boolean) 'confirmed'. I can't seem to write a query that returns only confirmed networks associated with a user.

My code is excerpted below.

```js
const network_affiliations = db.define('network_affiliations', {
    networkEmail: { type: Sequelize.STRING },
    confirmed: { type: Sequelize.BOOLEAN }
}, {
    freezeTableName: true,
    defaultScope: {
        where: {
            confirmed: true
        }
    },
});

// User belongs to many Networks and Networks belong to many Users (join table)
User.belongsToMany(Network, { through: network_affiliations });
Network.belongsToMany(User, { through: network_affiliations });

User.findOne({
            where: {
                email: req.body.email
            },
            include: [{ model: Network, through: { network_affiliations: { where: { confirmed: true } } } }]
        })

```

I expect this query to return a user instance with its associated networks -- but only networks where confirmed: true. Instead I'm getting all networks associated with the user. As you can also see in the above code, I tried setting a defaultScope for the join table ({confirmed: true}). This also appears not to do anything.

I've also tried a User.findAll query that similarly did not work.

__Dialect:__ postgres
__Sequelize version:__ "^3.30.4"

**Comment by prismm** [comment]
Still unable to find an answer for this.

**Comment by Sarvesh67** [comment]
I was also facing the same problem.
What you need here is something called eager loading, i.e coverting the default
outer join to inner join. 
This can be done by passing { required: true } inside include

User.findOne({
            where: {
                email: req.body.email
            },
            include: [{ model: Network, required: true, through: { network_affiliations: { where: { confirmed: true } } } }]
        })

The above code should work for you.

PS. I can see that issue is 2 years old but hopefully someone finds this answer useful now.
