### ISSUE TITLE
Unidirectional many-to-one onto model with composite keys?

### ISSUE THREAD

**Issue by SamuelMarks** [sequelize/sequelize#8128]
How do I create a one-way relation, where each `Album` has 0–∞ `photo`s, but there is no [efficient] way to get 'parent' `album` starting from `photo`?

## What you are doing?

```js
const Photo = sequelize_obj.define('photo_tbl', {
    name: {
        type: sequelize.STRING(10),
        primaryKey: true
    },
    description: {
        type: sequelize.STRING(10),
        primaryKey: true
    }
}, { tableName: 'photo_tbl' });

const Album = sequelize_obj.define('album_tbl', {
    name: {
        type: sequelize.STRING(10),
        primaryKey: true
    },
    /*  */
}, { tableName: 'photo_tbl' });

Album.hasMany(Photo);
```

## What do you expect to happen?
Album has many Photos, but you can't go from Photo back to Album [easily].

## What is actually happening?
Photo has a reference back to Album.

__Dialect:__ any
__Database version:__ any
__Sequelize version:__ 4.5.0

**Comment by iamjoyce** [comment]
You will need a link from Photo to Album. Add this to your last line.

`Photo.belongsTo(Album);`

**Comment by mwaeckerlin** [comment]
It is still an issue!

I have a table User and a table Ressource and a table Location. User can have Ressources. But also Locations can have Ressources. But Ressources exist completely independent of an owner. So ther must never be any link back from Ressources!

How to setup this?!?
