### ISSUE TITLE
Resource Request Timed out

### ISSUE THREAD

**Issue by jeremyklein** [sequelize/sequelize#8133]
## What you are doing?

I have a script which parses XML and loads them into a database. This script previously worked with Postgres SQL. I must switch to MSSQL. I have the following db connection settings:
```js
// code here
    { "username":username,
      "password":"password,
      "database":database,
      "host":host,
      "port": "post,
      "dialect":"mssql",
     "connectionTimeout": 0,
      "pool":{
         "max": 1,
         "min": 1,
         "idle": 200000,
        "acquire": 200000
      },
    "retry":{"max": 3},
    "logging": false,
    "dialectOptions": {
                "requestTimeout": 0,
     },
     "options":{
                "port": port
     }
}

```

## What do you expect to happen?
I wanted the data to load into the database.

## What is actually happening?
The records load for approximately 4 minutes. Then i get the following error:
```js
{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/jcook/riqi_provider_directory/node_modules/sequelize/node_modules/generic-pool/lib/ResourceRequest.js:59:17)
    at Timeout.bound [as _onTimeout] (/home/jcook/riqi_provider_directory/node_modules/sequelize/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) name: 'TimeoutError' }
```

Some data continues to load, but it looks like not all of my records are inserted into the database.

__Dialect:__ mssql 
__Database version:__ 2008
__Sequelize version:__ 4.1.0

**Comment by jeremyklein** [comment]
Increasing the max pool size allowed the data to be loaded. I would prefer not to need 100 connections to the database to load this data.

**Comment by xdamman** [comment]
I have the same issue but increasing the max pool size didn't help

**Comment by jeremyklein** [comment]
Which verson of Tedious are you using?

**Comment by xdamman** [comment]
@jeremyklein tedious? Not using it / never heard of it. Using Postgres 9.6 btw

**Comment by xdamman** [comment]
Still having the same issue with sequelize 4.8.2 and sequelize cli 3.0.0

**Comment by xdamman** [comment]
Here is how I solved it:

I've added `{ concurrency: 10 }` to `Promise.map(array, Promise, { concurrency: 10 });`

**Comment by kumbhanialex111** [comment]
Same issue but still not solved for me 
@xdamman please can you tell me where you change and what you changed ?
My code is 
var config = {
    user: process.env.user,
    password: process.env.password,
    server: process.env.server,
    database: process.env.database
        // pool: {
        //     max: 20,
        //     min: 10,
        //     idleTimeoutMillis: 3000
        // }
};
const pool = new sql.ConnectionPool(config)
module.exports = pool;

**Comment by idris** [comment]
I can't seem to get rid of the `ResourceRequest timed out` errors.  I've tried various settings.  Here are my current `pool` settings:
```
    pool: {
      max: 5,
      min: 0,
      idle: 20000,
      acquire: 40000,
      evict: 20000,
    },
```

I'm using RDS Postgres.  If it's exceeding the 40 second acquire time I set, does that essentially mean that all 5 connections are busy for 40 seconds?

**Comment by Celadora** [comment]
We are experiencing this problem across all services now (that had previously been working fine for over a year) that use Sequelize to connect to a Digital Ocean droplet (where the MySQL database is located). It seems like the more the service connects to the database, the sooner the error appears. After it appears the services must be restarted.

**Comment by idris** [comment]
@Celadora if I understand this issue correctly, this is just a matter of tweaking the pool settings.  In v2 (not sure about v3), there was no acquire timeout, so if all connections in the pool were busy, your app would just wait forever until a connection freed up.  This was obviously not ideal.  Although it did not throw an error, it was dangerous.

In v4, you need to decide on timeouts that make sense for your app.  If you want the old behavior, I think the closest thing would be to increase `acquire` to something ridiculously high like `1000000`.  Obviously, that's silly.  My real recommendation would be to increase the pool `max` to something higher (I used `30`), and set `acquire` to something reasonable for your app.

I think the main root cause for this whole issue is long-running queries.  If you have a pool max of 5 connections, and you have 5 concurrent queries going, with each query taking 30 seconds, your acquire is going to have to wait at least 30 seconds to get a connection.  Those queries can also queue up a bit, thereby exacerbating the problem.

Hope that helps, and I hope everything I said is accurate.  Anyone, please correct me if I'm wrong on any of that.

**Comment by Celadora** [comment]
@idris Thank you very much! Your advice corrected the issue.

**Comment by mkaufmaner** [comment]
For those of you still using v4 of Sequelize, this problem may have been fixed by [v4.44.1](https://github.com/sequelize/sequelize/releases/tag/v4.44.1).

See PR: https://github.com/sequelize/sequelize/pull/11140
See Issue: https://github.com/sequelize/sequelize/issues/11139

**Comment by ndangles** [comment]
My issue was that I was using [unmanaged transactions](https://sequelize.org/master/manual/transactions.html#unmanaged-transactions) which require manual calls of commit and rollback and I was forgetting to call rollback in the catch block of my try/catch after throwing an error. Examples below.

Faulty Code

```
app.post("/signup", async (req, res) => {
  const t = await sequelize.transaction();

  try {
    const { first_name, last_name, email } = req.body;

    const user = await Users.findOne({
      where: {
        email,
      },
    });

    if (user) {
      throw new Error("A user with that email already exists");
    }

    let newUser = await Users.create(
      {
        first_name,
        last_name,
        email,
      },
      { transaction: t }
    );

    await t.commit();

    res.status(200).send({});
  } catch (e) {
    // MISSING TRANSACTION ROLLBACK HERE

    res.status(500).send({});
  }
});
```

Correct Code
```
app.post("/signup", async (req, res) => {
  const t = await sequelize.transaction();

  try {
    const { first_name, last_name, email } = req.body;

    const user = await Users.findOne({
      where: {
        email,
      },
    });

    if (user) {
      throw new Error("A user with that email already exists");
    }

    let newUser = await Users.create(
      {
        first_name,
        last_name,
        email,
      },
      { transaction: t }
    );

    await t.commit();

    res.status(200).send({});
  } catch (e) {
    await t.rollback(); // THE FIX
    res.status(500).send({});
  }
});
```

**Comment by MiguelHuamanMedina** [comment]
> if (user) {
>       throw new Error("A user with that email already exists");
>     }

@ndangles can you send this error to your client? because that error would jump to the catch block, something similar happened to me and I had to handle the errors of the try block, in the catch block
