### ISSUE TITLE
Scoped models in associations lead to cryptic errors when using association methods

### ISSUE THREAD

**Issue by csreid** [sequelize/sequelize#8139]
## What you are doing?

There's a PR [here](https://github.com/sequelize/sequelize/pull/8138) with an example of the code to reproduce.

## What do you expect to happen?
The association methods (`add<Model>` et al.) should work like they do if the associated model is not scoped. If there's some technical reason that that can't happen, the error should be more helpful and fire at the time of the association.

## What is actually happening?
The error in the test is

`Error: Invalid value [object SequelizeInstance:User]`, and a stacktrace entirely contained within Sequelize code.

__Dialect:__ postgres
__Database version:__ 9.5
__Sequelize version:__ 4.3.1

**Comment by alvelig** [comment]
Actually it is. It says that you are passing an array with object SequelizeInstance:User. Likely you need to add<Model>s or get the first item of your array.

**Comment by csreid** [comment]
Look at the PR [here](https://github.com/sequelize/sequelize/pull/8138/files), that I mentioned in the issue.

I'm definitely not passing an array of users. Furthermore, like I mentioned, the stacktrace is contained entirely within sequelize code.

I'm fine with the response I got over there, but I just wish this error could at least be thrown way way way earlier so I could see what the actual problem is.

**Comment by alvelig** [comment]
Sorry, did not see the PR. Found this issue searching for the same error signature. In my case it was passing Array to add<Model>.
