### ISSUE TITLE
Can't bind array parameters

### ISSUE THREAD

**Issue by bishopw** [sequelize/sequelize#8140]
## What you are doing?
Trying to pass an array to postgres via sequelize.query() in a bound param, like this:
```js
sequelize.query(
  'SELECT * FROM people WHERE id IN ($ids)',
  {
    bind: {ids: [1, 2, 3]},
    type: sequelize.QueryTypes.SELECT
  }
)
```

## What do you expect to happen?
I get some records back.

## What is actually happening?
```
SequelizeDatabaseError: invalid input syntax for integer: "{"1","2","3"}"
```

__Dialect:__ postgres
__Database version:__ PostgreSQL 9.6.2
__Sequelize version:__ 4.4.2

Sorry if I've got the syntax wrong or something.  Checked the docs and the tests but couldn't find any bound array parameters being sent.

**Comment by bishopw** [comment]
Seems like this is actually a problem with the postgres binding library 'pg' (https://github.com/brianc/node-postgres) or something about how PostgreSQL handles IN clause syntax.  It looks like the typical workaround is to use WHERE x = ANY($bound_var) instead of WHERE x IN ($bound_var) (https://stackoverflow.com/questions/10720420/node-postgres-how-to-execute-where-col-in-dynamic-value-list-query), which... seems weird that I have to do it that way and can't use IN but whatever I'll go with it.  Closing this issue here anyway.

**Comment by bishopw** [comment]
> if you could post a solution to how you handled this

@KidA001 I posted it in my followup above already:

>  It looks like the typical workaround is to use WHERE x = ANY($bound_var) instead of WHERE x IN ($bound_var) (https://stackoverflow.com/questions/10720420/node-postgres-how-to-execute-where-col-in-dynamic-value-list-query)

**Comment by mortillan** [comment]
For those looking for a solution to this. Here is what worked for me to achieve binding an array to raw queries.

![image](https://user-images.githubusercontent.com/7253957/73905674-1e344080-48db-11ea-9201-c8ae6e0dec54.png)

Screenshot the code from docs instead of link

**Comment by cxcorp** [comment]
@mortillan Might note that `replacements` and `bind` are different. According to the [docs](https://sequelize.org/master/manual/raw-queries.html#bind-parameter), `replacements` are just escaped and inserted into the query by Sequelize, whereas `bind` seems to do an actual parameterized query.

**Comment by HyopeR** [comment]
Hello. I ran into this issue recently on an ongoing project. And if you are working with postgresql here is a temporary solution you can use.

I will exemplify on this query
> ```js
> let ids = [1,2,3]
>
> sequelize.query(
>   'SELECT * FROM people WHERE id IN ($ids)',
>   {
>     bind: {ids: ids},
>     type: sequelize.QueryTypes.SELECT
>   }
> )
> ```

**Let's take advantage of Postgre sql functions**
> ```js
> let ids = [1,2,3]
>
> sequelize.query(
>   'SELECT * FROM people WHERE id IN(SELECT UNNEST(STRING_TO_ARRAY($ids, ','))::int)',
>   {
>     bind: {ids: ids.toString()},
>     type: sequelize.QueryTypes.SELECT
>   }
> )
> ```

**Comment by ollydixon** [comment]
@HyopeR you don't need to do all that, just use ANY like this:

```WHERE users.id = ANY($user_ids)```

Bind can be like this:

`bind: {user_ids: ids},`
