### ISSUE TITLE
Sequelize package contains a Trojan

### ISSUE THREAD

**Issue by staoz94** [sequelize/sequelize#8142]
The scan below is of a zip file containing only the Sequelize package. If you use virustotal and scan your sequelize folder you will get the same result.

https://www.virustotal.com/#/file/06f8b2d3649e28aab105d4e4bf94046d4cad52acfb5d0c9a66614f89fcfa3a54/relations

**Comment by snewell92** [comment]
What? Can you post the different hashes, your sentence is confusing me. The title says you think there's a trojan, but your comment says the hashes match...

**Comment by staoz94** [comment]
Where can I get the hashes?

**Comment by staoz94** [comment]
I tracked down the trojan to this file called  "terraformer-wkt-parser".

https://www.virustotal.com/#/file/6f7811fc858fe96fa1aef6ddb741dffbaadd2455df228c9a0efbbdd8860be890/detection

You can find this file by going to your

node_modules  -> sequelize -> node_modules -> terraformer-wkt-parser

**Comment by staoz94** [comment]
I've tracked it down further. 

https://www.virustotal.com/#/file/6cd0e50f0dad42bf4b9ffc53e74ee89125ca257f95f42bb8818cdefc34ff9c02/detection

You can find this file by going to

node_modules -> sequelize -> node_modules -> terraformer-wkt-parser -> node_modules -> spec
