### ISSUE TITLE
Mariadb dialect already inherits mysql

### ISSUE THREAD

**Issue by imsamurai** [sequelize/sequelize#8146]
Maybe this is not needed?
https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/dialects/abstract/connection-manager.js#L52

**Comment by usmandap** [comment]
I am going to fix it.

**Comment by usmandap** [comment]
@imsamurai Is it fixed? I am not able to find this if statement in the file you had mentioned. In fact this statement does not contain in the whole project I searched it.
