### ISSUE TITLE
Postgres support for cidr, init, macaddr column types

### ISSUE THREAD

**Issue by tadman** [sequelize/sequelize#8154]
## What you are doing?

Trying to make use of the Postgres [network column types](https://www.postgresql.org/docs/current/static/datatype-net-types.html).

## What do you expect to happen?

That Sequelize would have DataType information for `CIDR`, `INET`, and `MACADDR` like it does for things like `UUID` or `HSTORE`.

## What is actually happening?

Sequelize currently has no idea what these columns mean. I've started working on a [branch](https://github.com/tadman/sequelize/tree/with_inet) to address this, but Issue #8153 is holding me up on testing it.

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ master

**Comment by gabegorelick** [comment]
@tadman Any chance you could throw a PR up?

**Comment by gabegorelick** [comment]
I opened up https://github.com/sequelize/sequelize/pull/9567 to start.

**Comment by tadman** [comment]
I didn't want to mess up the PR, so thanks for doing that!
