### ISSUE TITLE
Pooled connections to MySQL not closed after specified timeout

### ISSUE THREAD

**Issue by lekoder** [sequelize/sequelize#8155]
## What you are doing?
I am interacting with legacy MySQL system that uses DNS-based master selection in master-master replication (via [consul](https://www.consul.io/)). Therefore I need a new connection established on regular basis. I have configured my Sequelize with pooling:

```js
    pool: {
        max: 5,
        min: 0,
        idle: 1000,
        evict: 5000
    }
```

## What do you expect to happen?
I expected connection to MySQL to be closed after 1 second of being idle or 5 seconds of being stale. I also expected re-connection if query is being made after closing connection.

## What is actually happening?
MySQL connection is not closed after timeouts and subsequent queries are passed trough it. New connections are established as expected.

_Output, either JSON or SQL_
```
Id	User	Host	db	Command	Time	State	Info
13797	db	172.17.0.1:54612	db	Sleep	220		NULL
14967	db	localhost	NULL	Query	0	init	SHOW PROCESSLIST
```

__Dialect:__ mysql
__Database version:__ 5.6 ([dockerized](https://hub.docker.com/_/mysql/))
__Sequelize version:__ 4.5.0
__mysql2 version:__ 1.4.1

**Comment by sushantdhiman** [comment]
https://github.com/coopernurse/node-pool/pull/201
