### ISSUE TITLE
BelongsToMany error: <table> (alias) is not associated to <table>

### ISSUE THREAD

**Issue by oliv23** [sequelize/sequelize#8156]
Hi,

I can't seem to figure this one out. I've set up **belongsToMany** associations as well as the "as" value and still, I get this error:
`Error: "user" (savers) is not associated to "link"`

I have two models:

`var User = sequelize.define("user", {...});`
`var Link = sequelize.define("link", {...});`

and the following associations: 

`Link.belongsTo(User, {as: 'original_saver'});`
`Link.belongsToMany(User, {through: Save, as: 'saves'});`
`User.belongsToMany(Link, {through: Save, as: 'savers'});`

The query I'm trying to get working is the following:

`models.Link.findAll({`
`include: [ {model: models.User, as: 'savers'}, {model: models.User, as: 'original_saver'} ],`
`})`

What am I doing wrong here?

**Comment by Alexsey** [comment]
Your `Link` is associated to `User` as `saves` and you are mentioning it in `inslude`'s `as` as `savers`. Try
```
models.Link.findAll({
include: [ {model: models.User, as: 'saves'}, {model: models.User, as: 'original_saver'} ],
})
```

**Comment by oliv23** [comment]
@Alexsey oh geez thanks. I had it the other way around...
