### ISSUE TITLE
Using include all on Model#build doesn't seem to work

### ISSUE THREAD

**Issue by Enitoni** [sequelize/sequelize#8164]
## What you are doing?
Adding the include wildcard to include all associations on a query

```js
Post.build({
   'userId': 1,
   'content': 'Foo',
}, {
   'include': [{ all: true }]
})
.save()
.then(instance => {
   console.log(instance.user);
});
```

## What do you expect to happen?
The `User` instance will be available on the created instance (`instance.user`)

## What is actually happening?
`instance.user` is undefined

__Dialect:__ postgres
__Database version:__ 9.5.8
__Sequelize version:__ 4.6.0

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/8938
