### ISSUE TITLE
Transactions not closing their connections

### ISSUE THREAD

**Issue by axetroy** [sequelize/sequelize#8172]
## What you are doing?

```js
const Sequelize = require('sequelize');
const cls = require('continuation-local-storage');
const namespace = cls.createNamespace('xxx');

Sequelize.useCLS(namespace);

const sequelize = new Sequelize('postgres', 'postgres', 'admin', {
  host: 'localhost',
  dialect: 'postgres',
  pool: {
    max: 200,
    min: 0,
    idle: 1000,
    // DO NOT ASK ME WHY I SET THIS UNKOWN FIELD
    idleTimeoutMillis: 1000,
    acquire: 1000
  },
   // DO NOT ASK ME WHY I SET THIS UNKOWN FIELD
  autocommit:true,
  autoClose:true,
  autoReconnect: true,
  // native: true,
  retry: {
    max: 2
  },
  // isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.REPEATABLE_READ,
  // transactionType: Sequelize.Transaction.TYPES.DEFERRED,
  benchmark: true
});

export default sequelize;
```

## What is actually happening?

In the case of high concurrency

It will throw error **'too many clients already.'** or **'ResourceRequest timed out'**

and I found the connections will not be released after transactions commit or rollback.

connection still there. Increment until get the max_concurrent setting(default: 100), Postgres will throw the error **'too many clients already.'**.

So, why would not released the connections.

ref: https://github.com/sequelize/sequelize/issues/1601

![1](https://user-images.githubusercontent.com/9758711/29606375-b1783456-8820-11e7-800f-e34ee111f794.png)

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 4.7.0

**Comment by shifubrams** [comment]
I have the same issue :/ transaction doesn't close the connection after a commit. So if I do several transaction. The database will freeze and block new  connections

**Comment by mattgi** [comment]
@axetroy / @shifubrams figure out a solution to this?

**Comment by papb** [comment]
Hello everyone, can anyone try to create a [sequelize-sscce](https://github.com/papb/sequelize-sscce) for this?

**Comment by shifubrams** [comment]
Nope ... Sorry :/ I did left sequelize for transactions

**Comment by Shahor** [comment]
So this is still happening 🤔 ?

**Comment by realFranco** [comment]
Rebuild the logic of my backend with transactions it is not a way to go.

I want to know how can I release or drain pools connections.

**Comment by bozzmob** [comment]
I'm facing the same issue.  Facing deadlocks
```
original: Error: Deadlock found when trying to get lock; try restarting transaction
```

Is there any way to have a transaction?

**Comment by giovanni-bertoncelli** [comment]
I've encountered the same problem in particular when a transaction throws an error. Besides in this situation the `max` pool configuration is not event respected and the client might create more connections than the max parameter specifies.

**Comment by itair-miguel** [comment]
We have been having similar issues as well. Are you guys using managed or unmanaged transactions? CLS enabled? Also, what is your sequelize version? Ours is currently **4.38.1**. Thanks.

**Comment by marcusleandro** [comment]
I am facing the same issues, I am opening a Thread the runs queries against the db with lock and skipLock options, but in the end lot of connection stay in idle state forever :(

![image](https://user-images.githubusercontent.com/12412974/150621344-0380d2b7-e453-45ad-9006-02af65bf1e81.png)


![image](https://user-images.githubusercontent.com/12412974/150621316-f0d00fae-52be-4cb7-aa66-5fe34810cb4f.png)

**Comment by ephys** [comment]
It's probably resolved for the same reason https://github.com/sequelize/sequelize/issues/10858 is resolved. I'll wait a bit more and close if there are no more reports
