### ISSUE TITLE
Truncate with cascade does not work

### ISSUE THREAD

**Issue by AnthonyTsang** [sequelize/sequelize#8183]
## What you are doing?
I am trying to reset the database records for each testcase. I tried 2 ways to do it.
```js
function () {
    const jobs = Object.values(entities)
        .map(e => e.destroy({ truncate: true, cascade: true }));

    return Promise.all(jobs);
};

function () {
    return sequelize.truncate({cascade: true})
};
```

## What do you expect to happen?
I want all records to be removed from all entities.

## What is actually happening?
`SequelizeDatabaseError: Cannot truncate a table referenced in a foreign key constraint`

__Dialect:__ mysql
__Database version:__ mariadb:10.3.0
__Sequelize version:__ sequelize@4.5.0

**Comment by sushantdhiman** [comment]
You cant truncate a table which is referenced by other table https://stackoverflow.com/a/5452798

**Comment by mschipperheyn** [comment]
@sushantdhiman So, how do you do it then? It's a common scenario in testing to want to eliminate all records.

**Comment by AnthonyTsang** [comment]
@mschipperheyn Turns out it somehow work with MEMORY storage engine. You may try. I guess memory engine has looser constraint than other engine.

**Comment by uzair004** [comment]
What's use of `cascade: true` if it cannot truncate tables with foreginkey reference ? It should be able to do it

**Comment by uzair004** [comment]
There exist a `removeConstraint()` method on `queryInterface` class. try using

`await sequelize.queryInterface.removeConstraint(
      "your_table_name",
      "your_constraint_name_here"
    );`
    
 However, It wasn't working for me, throwing no constraint found error.
 
 So get away with using Raw Sql query. 
 `sequelize.query(
      "ALTER TABLE your_table_name DROP CONSTRAINT your_constraint_name_here;"
    );`
    
   It working for me.
