### ISSUE TITLE
Ordering of the columns is inconsistent

### ISSUE THREAD

**Issue by ruchevits** [sequelize/sequelize#8188]
## What you are doing?

a) Setting all three fields
```js
const a = await MyModel.create({
  name: 'Albert',
  surname: 'Hofman',
  vehicle: 'bicycle'
})
```

a) Setting only two fields
```js
const b = await MyModel.create({
  name: 'Albert',
  vehicle: 'bicycle'
})
```

## What do you expect to happen?

I expect the order of fields to be the same.

## What is actually happening?

a) Setting all three fields
```js
console.log(a)
```
```bash
{
  name: 'Albert',
  surname: 'Hofman',
  vehicle: 'bicycle'
}
```

a) Setting only two fields
```js
console.log(b)
```
```bash
{
  name: 'Albert',
  vehicle: 'bicycle',
  surname: null
}
```

__Dialect:__ `postgres`
__Database version:__ `9.6`
__Sequelize version:__ `[Node: 7.8.0, CLI: 2.8.0, ORM: 4.7.1]`

**Comment by sushantdhiman** [comment]
https://stackoverflow.com/a/5525820
