### ISSUE TITLE
Setting Association doesn't immediately persist the reference

### ISSUE THREAD

**Issue by jasonbodily** [sequelize/sequelize#8189]
## What you are doing?
A stage has many tasks, but only one active task at a time. The model is as follows:

```js
var Stage = sequelize.define('Stage', {  /** attrs **/ });
var Task = sequelize.define('Task',  { /** attrs **/ });

Stage.hasMany(Task, { as: 'tasks' });
Stage.belongsTo(Task, { as: 'task', foreignKey: 'task_active_id', constraints: false }); 
Task.belongsTo(Stage);

Stage.addScope('defaultScope', {
  include: [{ model: Task, as: 'task' }]
}, { override: true });

Stage.create().then(stage => {
  // Create a new task for this stage
  return Task.create({ stage_id: stage.id }).then(task => {
    // Set that task as the active task
    stage.setTask(task).then(() => {
      console.log(stage.task); //<-- This is the point of confusion
    })
  });
})

```

## What do you expect to happen?
I would expect the `console.log(stage.task)` to output the associated `task` object. If you log the `stage.task_active_id` it is correctly that task's id.

NOTE: I could add `stage.task = task`, but when I serialize that back as JSON, the stage's `task` is not included. If I add `this.reload` and serialize, it is. What's the difference and why wouldn't the association be persisted when `setAssociation` is triggered?

## What is actually happening?
The `console.log(stage.task)` outputs `null`

Dialect: postgres
Sequelize version: 3.30.4

Thanks for your consideration!

**Comment by jasonbodily** [comment]
On this same vein, removing the relationship doesn't remove the object either:

```
stage.setTask(null).then(() => {
  console.log(stage.task_active_id); // <-- null
  console.log(stage.task); <-- task obj logged. Why?

  stage.reload().then(() => {
    console.log(stage.task); // <-- null, that's good
    console.log(JSON.stringify(stage)); <-- includes task obj!? Why?
  });
})
```

**Comment by lafiosca** [comment]
I'm curious about this as well. If this is intended behavior, I think the documentation could be more friendly.

**Comment by sushantdhiman** [comment]
FYI: set and remove method always persist their respective change but they dont add or remove association accessors (like `.task` here) on source instance. You can use `reload` to get current version.

Main issue https://github.com/sequelize/sequelize/issues/3424
