### ISSUE TITLE
Same second query for paranoid tables returning soft deleted records

### ISSUE THREAD

**Issue by Samenai** [sequelize/sequelize#8202]
## What you are doing?

```js
sequelize.define('user', {
  //...column definitions
}, {
  paranoid: true
});

User.find({
  where: {
    id: req.params.id
  }
}).then((user) => {
  console.log(user);
  user.destroy().then(() => {
    User.find({
      where: {
        id: req.params.id
      }
    }).then((deletedUser) => {
      console.log(deletedUser);
      console.log(new Date(new Date().toUTCString()).toISOString());
    });
  });
});

//run a second later
User.find({
  where: {
    id: req.params.id
  }
}).then((user) => {
  console.log(user);
});
```

## What do you expect to happen?
Second console.log should return null.

## What is actually happening?
Second console.log is returning the object again with a deletedAt field entered that matches the third console.log's output.  Remote MySQL server runs in UTC time.  Occurs on local development stations in EST as well as servers running in UTC time.  Similar to #7204.

Running another query a second later will return null.

__Dialect:__ mysql
__Database version:__ 5.7.11
__Sequelize version:__ 4.7.5

**Comment by Samenai** [comment]
Is it possible that NTP drift causes a difference of timestamps between the web server/local development station and the mysql's CURRENT_TIMESTAMP?

Can the destroy function instead set deletedAt to mysql's CURRENT_TIMESTAMP (or less if necessary) to successfully delete the object?

**Comment by Samenai** [comment]
Working around this by adding a 'deletedAt: null' to all my find/findAll queries, making sequelize act like it did in v3.x.x

**Comment by deployable** [comment]
I'm seeing the same thing, though #7290 mentions moving from `$gte` to `$gt` was meant to be a fix for it.

The `find*` queries use `table.deleted_at > CURRENT_TIMESTAMP` in the where clause. 
```
SELECT `id`, `group`, `created_at`, `updated_at`, `deleted_at` 
FROM `groups` AS `group`
WHERE (`group`.`deleted_at` > CURRENT_TIMESTAMP OR `group`.`deleted_at` IS NULL);`
```
It might be related to `CURRENT_TIMESTAMP` only being second resolution, but datetime is millisecond
```
sqlite> select strftime('%Y-%m-%d %H:%M:%f', CURRENT_TIMESTAMP);
2017-09-12 09:10:12.000
```
Running manual queries with constructed dates including milliseconds works as expected:
```
sqlite> update groups set deleted_at = strftime('%Y-%m-%d %H:%M:%f', 'now'); select * from groups where deleted_at > strftime('%Y-%m-%d %H:%M:%f', 'now');
sqlite> 
```
Whereas using `CURRENT_TIMESTAMP` returns the "deleted" record like sequelize:
```
sqlite> update groups set deleted_at = strftime('%Y-%m-%d %H:%M:%f', 'now'); select * from groups where deleted_at > CURRENT_TIMESTAMP;
9e7453ca-4424-44f4-98fc-8f71e073c55a|test|2017-09-12 08:23:21.707 +00:00|2017-09-12 08:23:21.707 +00:00|2017-09-12 09:12:59.802
```

**Comment by deployable** [comment]
The same test suite I found the problem with on sqlite works as expected in mysql/maria.

**Comment by apricote** [comment]
A fix that is working for me is contained in PR #8204 
There is a test case missing though, so it can not be merged yet.
