### ISSUE TITLE
Cannot query field \"createdAt\" on type...

### ISSUE THREAD

**Issue by strongui** [sequelize/sequelize#8205]
## What you are doing?

I've created a simple DB with one table in it, to test out sequelize on my localhost. 

My JS code looks like this:

```
const connection = new Sequelize('mydb', 'testuser', 'test', {
  host: 'localhost',
  dialect: 'mysql',
  pool: {
    max: 5,
    min: 0,
    idle: 10000
  }
});

const Post = connection.define('post', {
  id: {
    type: Sequelize.BIGINT,
    primaryKey: true
  },
  uuid: {
    type: Sequelize.STRING
  },
  title: {
    type: Sequelize.STRING,
  },
  votes: {
    type: Sequelize.INTEGER
  },
  url: {
    type: Sequelize.STRING
  }
}, { timestamps: false });
```

## What do you expect to happen?
Now, if I query for data, everything is fine. I can get any fields I want, however I cannot get the createdAt, updatedAt, and deletedAt fields to return any value. Anytime I specify any one of these fields, as a field I'd like to get returned, I get an error like this:

**"Cannot query field \"createdAt\" on type \"Post\".",**

The weird thing is that I can even send into the ORDER part of the query any one of those fields and it will order corectly ASC / DESC on createdAt or updatedAt, but I still cannot get a return value for those fields. I am not sure what is wrong.

In my database all 3 of those fields are of type **DATETIME**.

__Dialect:__ mysql
__Database version:__ MYSQL 5.7.14
__Sequelize version:__ 4.7.5

**Comment by caiquecastro** [comment]
Is the createdAt column being created on database?

**Comment by strongui** [comment]
@caiquecastro What do you mean being created? The table and column already exist, they don't need to be created, I just need them to be read. Maybe I'm misunderstanding the question.

**Comment by Alexsey** [comment]
@caiquecastro 
1. Sequelize would only create a table on `define` call if the table doesn't exists
2. If there is already a created table with fields that model don't have - you will map your model only to those fields.
3. If there is already a created table with lack of fields defined in model - you would get en error when you would try to contact them

Probably you have called the `define` with no `timestamp: false` the first time, before the table has been created in the database. So it has been created with `createdAt` column. Now your model don't have it - so you are not obtaining it any more. The fact that you can order on it may be considered as an accidental undocumented feature... or a minor bug

**Comment by strongui** [comment]
@Alexsey 

I don't fully understand what you are trying to say.

My process is this: 

1. I created the DB and the table with phpMyAdmin. I did not use sequelize to create the table. I'm only trying to use it to query on the table. 

2. I did **initially** care the table WITHOUT fields createdAt, updatedAt, deletedAt, and only added them later. Does my `connection.define('post',` code cache the initial table model or something? I am running this all on a local server, and I shut down / restart my server between .js and DB changes, so I don't understand why the fields don't work.

Do I need to drop my table completely and re-create it or?

**Comment by Alexsey** [comment]
Do you want a table without `createdAt`, `updatedAt` or have an ability to query them? If first - drop them or drop the table and Sequelize would create a table for you with fields specified in your model. If you wont to be able to query `createdAt`, `updatedAt` - remove `{ timestamps: false }` from table definition

**Comment by strongui** [comment]
@Alexsey 

That is what I was trying to do. And I had it before without any **timestamp: XXX** definition, and it wasn't working. So I went to forums asking for help and someone told me to put that. However, even with removing that, I still can't query the field. Here is what I have now:
```

const Post = connection.define('post', {
  id: {
    type: Sequelize.BIGINT,
    primaryKey: true
  },
  uuid: {
    type: Sequelize.STRING
  },
  title: {
    type: Sequelize.STRING,
  },
  votes: {
    type: Sequelize.INTEGER
  },
  url: {
    type: Sequelize.STRING
  },
  createdAt: {
    type: Sequelize.DATE
  },
  updatedAt: {
    type: Sequelize.DATE
  },
  deletedAt: {
    type: Sequelize.DATE
  }
});
```

Then my query:

`Executing (default): SELECT 'id', 'uuid', 'title', 'votes', 'url', 'createdAt', 'updatedAt', 'deletedAt' FROM 'posts' AS 'post' ORDER BY 'post'.'createdAt' DESC LIMIT 0, 10;`

And I still get:

`"message": "Cannot query field \"createdAt\" on type \"Post\".",`

I can query any other field, and still sort by createdAt, it just refuses to actually give me back data on those fields :/

**Comment by Alexsey** [comment]
Post the code that may be copy/paste and executed that would gives the error

**Comment by strongui** [comment]
@Alexsey I've posted everything above. Do you need anything else?
