### ISSUE TITLE
Include attributes with scopes

### ISSUE THREAD

**Issue by sluchznak** [sequelize/sequelize#8211]
## What you are doing?

```js
Project.loadScopes = (models) => {
    Project.addScope('withFavorited', userId => ({
      attributes: {
        include: [
          sequelize.literal(`exists(SELECT created_at FROM favorites f WHERE f.project_id = "Project"."id" AND f.user_id = ${userId}) as favorited`),
        ],
      },
    }));
    Project.addScope('withLiked', userId => ({
      attributes: {
        include: [
          sequelize.literal(`exists(SELECT created_at FROM project_likes f WHERE f.project_id = "Project"."id" AND f.user_id = ${userId}) as liked`),
        ],
      },
    }));
  };
```

## What do you expect to happen?
```sql
select *, exists(...from favorites), exists(...from project_likes)
```

## What is actually happening?
```sql
select *, exists(...from favorites)
```

_Output, either JSON or SQL_

__Dialect: postgres
__Database version: 9.6
__Sequelize version:4.6.0

**Comment by alvelig** [comment]
Супер!!! 

Great examples on sequelize.fn and scope functions. 

But addScope only defines the scope. Do you merge scopes somewhere?

**Comment by sluchznak** [comment]
I'm not use `scopes: {}` in model definition

**Comment by alvelig** [comment]
I mean `addScope('withFavorited')` is the same that `scopes: { withFavorited: {} }`.
To use scope you need to `Project.scope([ 'withFavorited' ])`.

**Comment by sluchznak** [comment]
I don't remember why do this, but think some scopes include diff models (realations) with other scopes and if I define scopes in model definitions then receive sequelize error with "missed association".

**Comment by sluchznak** [comment]
Now i do two steps:
1. Associate
```js
Project.associate = (models) => {
    Project.hasMany(models.ProjectTag, {
      as: 'projectTags',
      foreignKey: 'project_id',
    });
}
```

2. loadScopes (example in topic)

**Comment by sluchznak** [comment]
I'm not merge scopes
