### ISSUE TITLE
TypeError: Cannot read property 'hasBrand' of undefined

### ISSUE THREAD

**Issue by toantd90** [sequelize/sequelize#8214]
## What you are doing?

I have two models _User_ and _Brand_.  
```js
        // user.js
    	const User = sequelize.define('User', {
			id: {
				type: DataTypes.UUID,
				defaultValue: DataTypes.UUIDV4,
				primaryKey: true,
			},
            hasBrand: {
				type: DataTypes.BOOLEAN,
				defaultValue: false,
			},
    	})
    	User.associate = models=> {
			User.belongsToMany(models.Brand, {
				through: models.UserBrand,
				foreignKey: 'user',
			})
        }
```
```js
        // brand.js
    	Brand.belongsToMany(models.User, {
			through: models.UserBrand,
			foreignKey: 'brand',
		})
```

A user can have **many** brands.

A brand can belong **many** users. 

I defined another model for many-to-many associations. It named *UserBrand*. 

```js
        // userBrand.js
    	const UserBrand = sequelize.define('UserBrand', {
			status: {
				type: DataTypes.INTEGER,
				allowNull: false,
			},
			title: {
				type: DataTypes.STRING,
				defaultValue: '',
			},
    	})

    	UserBrand.associate = models=> {
    		UserBrand.belongsTo(models.User, { foreignKey: 'user', targetKey: 'id' })
    		UserBrand.belongsTo(models.Brand, { foreignKey: 'brand', targetKey: 'id' })
    	}
```

## What do you expect to happen?
_I wanted application run!_

## What is actually happening?
_But an error occurs_ TypeError: Cannot read property 'hasBrand' of undefined
I can not find any relation between *hasBrand* and *association*, but remove *hasBrand* it works

How can I fix it in case I still want to keep *hasBrand* field?

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 4.2.1

**Comment by Maxobat** [comment]
I would just rename the hasBrand field. In the belongs-to-many association, Sequelize will generate association methods based on the names of the models used in the association. For example, in your case, Sequelize is generating a method called hasBrand. This method allows you to pass in an ID of a brand to see if that brand is associated with a user. This is where you are running into an issue. The conflict itself isn't directly the issue, but it looks like there is some logic in place to prevent method conflicts. In this logic, it's trying to retrieve a key's value on an undefined value. This is where the error comes into play.

**Comment by Maxobat** [comment]
The error is coming from the get accessor on the model instance. It seems it's expecting the model instance to be hydrated with field data and trying to retrieve a a value from an object that has not been initialized.
