### ISSUE TITLE
Bulk hooks documentation is controversial  

### ISSUE THREAD

**Issue by Alexsey** [sequelize/sequelize#8215]
1. In [Hooks docs](docs.sequelizejs.com/manual/tutorial/hooks.html) in the beginning of "Model hooks" section there is an example of `beforeBulkCreate`:
```js
Model.beforeBulkCreate((records, fields) => {
  // records = the first argument sent to .bulkCreate
  // fields = the second argument sent to .bulkCreate
})
```
with second argument `fields` while at the end of the same section there is an example of `beforeBulkCreate`:
```js
User.beforeBulkCreate((users, options) => {
  for (const user of users) {
    if (user.isMember) {
      user.memberSince = new Date();
    }
  }

  // Add memberSince to updatesOnDuplicate otherwise the memberSince date wont be
  // saved to the database
  options.updatesOnDuplicate.push('memberSince');
});
```
with second argument `options`. So what would be the second argument?

2. At the beginning of [Hooks docs](docs.sequelizejs.com/manual/tutorial/hooks.html) in the beginning of "Model hooks" section docs says "Some model hooks have two or three parameters sent to each hook depending on it's type" but there is not a single example of three parameters hook and nothing says about what hooks would have two parameters and what hooks would have three.

3. The example of `beforeBulkCreate` hook
```js
Model.beforeBulkCreate((records, fields) => {
  // records = the first argument sent to .bulkCreate
  // fields = the second argument sent to .bulkCreate
})

Model.bulkCreate([
  {username: 'Toni'}, // part of records argument
  {username: 'Tobi'} // part of records argument
], ['username'] /* part of fields argument */)
```
Uses `bulkCreate` with second argument as an array, but according to [Working in bulk documentation](http://docs.sequelizejs.com/manual/tutorial/instances.html) second argument should be an object. Is the example valid and just not documented? I think documentation should not use undocumented features in it's own examples - it's quite confusing :(

**Comment by Alexsey** [comment]
The source has some abstractions, but as far as I can see [all hooks should obtain the same arguments](https://github.com/sequelize/sequelize/blob/master/lib/hooks.js#L85) that are not depends on the hooks type. Am I correct?

**Comment by sushantdhiman** [comment]
As you can see in https://github.com/sequelize/sequelize/blob/master/lib/hooks.js#L7 (hooks file), atleast `validationFailed` has three arguments, some of them two and some even have one argument.

**Comment by Alexsey** [comment]
Ah, I didn't mention that because it's not using anywhere in the code below :). Ok, after reading the code of execution of hooks in [lib/mode.js](https://github.com/sequelize/sequelize/blob/master/lib/model.js) I can see that all calls are making with `options` or with `instance(s), options`. I think that means that documentation should be like
```js
Model.beforeBulkCreate((records, {fields}) => {
  // records = the first argument sent to .bulkCreate
  // fields = the second argument sent to .bulkCreate
})
```
while according to [beforeBulkUpdate code call](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2651)
```js
Model.beforeBulkUpdate((attributes, where) => {
  // attributes = first argument sent to Model.update
  // where = second argument sent to Model.update
})
```
it is just incorrect - it will have only one argument, so it should be
```js
Model.beforeBulkUpdate(({attributes, where}) => {
  // attributes = first argument sent to Model.update
  // where = second argument sent to Model.update
})
```

Ok, generally I have understand the idea. I'm not promising but may be I will make a PR to fix the docs. @sushantdhiman should I close the issue or it should remain open until some one fix docs?

**Comment by sushantdhiman** [comment]
Lets keep it open until we fix that documentation

**Comment by Alexsey** [comment]
@sushantdhiman PR ready https://github.com/sequelize/sequelize/pull/8219
