### ISSUE TITLE
How to define an NVARCHAR(MAX) field?

### ISSUE THREAD

**Issue by joniba** [sequelize/sequelize#8218]
Is it possible to define an NVARCHAR(MAX) data type in sequelize? (If so how?)

**Comment by danfsd** [comment]
Hi @joniba, yes it is. `NVARCHAR(length)` is actually a `DataType.STRING(length)`, so you could define it this way:

```js
content: {
    type: DataTypes.STRING(64)
}
```

You **could additionally** add a `validate` function to check whether the value trying to be stored on the `content` attribute is bigger than the length, but it's optional.

**Comment by joniba** [comment]
Hi @danfsd, if I define DataTypes.STRING(64) I get NVARCHAR(64), which is not what I want. I've gone over the documentation and also searched elsewhere on the www ether and have found nothing...

**Comment by danfsd** [comment]
What is exactly what you want? I thought that you were trying to define an attribute as `NVARCHAR` supplying a max-length to it.

**Comment by joniba** [comment]
Thanks @danfsd, I got an answer [on stackoverflow](https://stackoverflow.com/questions/45937174/how-to-define-an-nvarcharmax-field-with-sequelize).
