### ISSUE TITLE
Querying parent model with associations only return queried association

### ISSUE THREAD

**Issue by caiquecastro** [sequelize/sequelize#8220]
## What you are doing?
I have a model Project. The project has many tasks. When I query the projects that contain a specific task, it returns only the tasks matching the where for the association.

```js
Project.findAll({
  include: [{
     model: Task,
     as: 'tasks',
     where: {
       id: 'xxxx',
     },
  }],
});

```

## What do you expect to happen?
I expect it to return all the tasks from the project that contains the queried task.

## What is actually happening?
For example: The project A contains the tasks X and Y. When I query the project with the task X. It returns the Project with only one task: Task X. But I want it to fetch all its tasks: the project A, with the tasks X and Y associated.

**Comment by Alexsey** [comment]
Try [Top level where with eagerly loaded models: '$nested.column$'](http://docs.sequelizejs.com/manual/tutorial/models-usage.html#eager-loading)

**Comment by caiquecastro** [comment]
Didn't work for me. Still only fetching the task with the id I queried.

**Comment by Alexsey** [comment]
It will work like this
```js
  Project.hasOne(Project, {as: 'self', foreignKey: 'id'})

  Project.findAll({
    where: {id: Sequelize.col('self.id')},
    include: [{
      model: Task,
      as: 'tasks',
    }, {
      model: Project,
      as: 'self',
      include: [{
        model: Task,
        as: 'tasks',
        where: {
          id: 'xxxx'
        }
      }]
    }]
  })

```
It will get the necessary data in one SQL request. But unless you are writing it manually and this is all you need - I don't recommend you to use this because it will bring you to some bugs, like `attributes` will have no effect and `limit` will give you a random result. Possible some other additional parameters could break the request

**Comment by caiquecastro** [comment]
I think i will have to make two queries. One to fetch all the project id's and then a second one to fetch all the attributes and tasks from this project.
