### ISSUE TITLE
LOCK.UPDATE not creating correct SQL

### ISSUE THREAD

**Issue by PCFNode** [sequelize/sequelize#8221]
## What you are doing?
I am trying to lock on a findOne so that no-one can read until a transaction is complete

```js
let t = await models.sequelize.transaction({ autocommit: false }); //get transaction

try {
  let getThisUser = await models.User.findOne({ attributes: ['id', 'status'], where: { id: 18 }, lock: t.LOCK.UPDATE, transaction: t } );
  if (getThisUser.status != "Active") {
    throw Error("Not Active");
  }
  //various updates, creates... imagine this takes a while  

  let updateUser = await models.User.update({ status: "NotActive" }, { where: { id: 18 }, transaction: t }); // now we can update the user

  await t.commit();

} catch(err) {
  await t.rollback();
  throw err;
} 
```

## What do you expect to happen?
I expect a lock to be inserted, so noone else is able to read that particular user until the transaction has been committed or rolled back. Then, once it has been successfully commited, the second person running the code, after being blocked on the read, now reads the updated `status`

## What is actually happening?
The outputted SQL does not state anything to do with a lock (see output below). If I run two instances of the code (in debug), when one transaction starts, calls the findOne, then a breakpoint is set on the if statement. The second transaction is able to go through and read also. This means, if two people call the method at the same time, there is a window where they can both carry out every single line of the transaction. This is a MASSIVE issue, as some of the code omitted is a load of insert statements which are duplicated!!

_Output, SQL_

Executing (351b3c0cb4ba06fabc03): BEGIN TRANSACTION;
Executing (351b3c0cb4ba06fabc03): SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (351b3c0cb4ba06fabc03): SELECT [id], [status] FROM [Users] AS [User] WHERE [User].[id] = 18;

__Dialect:__ mssql
__Database version:__ Not sure, its an Azure SQL database
__Sequelize version:__ 3.29

**Comment by Alexsey** [comment]
I have extend your code to something that may be copy/paste/execute (just set your db credentials)
```js
'use strict'

const Sequelize = require('sequelize')

const dbConfig = {
  type: 'mysql', user: 'root', password: 'root',
  database: 'db', host: 'localhost'
}

;(async () => {
  const sequelize = new Sequelize(
    dbConfig.database, dbConfig.user, dbConfig.password, {
      host: dbConfig.host,
      dialect: dbConfig.type,
      pool: {max: 100, min: 0, idle: 10000},
      dialectOptions: {
        charset: 'utf8_general_ci',
      }
    }
  )
  await sequelize.authenticate()

  const User = sequelize.define('User', {
    id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
    status: {type: Sequelize.STRING, defaultValue: 'Active'}
  }, {timestamps: false})

  await sequelize.sync()

  await User.create()

  let t = await sequelize.transaction({ autocommit: false }) //get transaction

  try {
    let getThisUser = await User.findOne({ 
      where: { id: 1 }, 
      lock: 
      t.LOCK.UPDATE, 
      transaction: t 
    })

    //various updates, creates... imagine this takes a while

    let updateUser = await User.update({
        status: "NotActive"
      }, {
        where: { id: 1 },
        transaction: t 
    }) // now we can update the user

    await t.commit()
  } catch(err) {
    await t.rollback()
    throw err
  }
})()
```
And it generates the SQL
```sql
Executing (default): SELECT 1+1 AS result
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER auto_increment , `status` VARCHAR(255) DEFAULT 'Active', PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Users`
Executing (default): INSERT INTO `Users` (`id`,`status`) VALUES (DEFAULT,'Active');
Executing (624dfc4b-2b97-41e6-9ff1-ecd572104a75): START TRANSACTION;
Executing (624dfc4b-2b97-41e6-9ff1-ecd572104a75): SET autocommit = 0;
Executing (624dfc4b-2b97-41e6-9ff1-ecd572104a75): SELECT `id`, `status` FROM `Users` AS `User` WHERE `User`.`id` = 1 FOR UPDATE;
Executing (624dfc4b-2b97-41e6-9ff1-ecd572104a75): UPDATE `Users` SET `status`='NotActive' WHERE `id` = 1
Executing (624dfc4b-2b97-41e6-9ff1-ecd572104a75): COMMIT;
```
With `SELECT ... FOR UPDATE` as expected

**Comment by PCFNode** [comment]
Thanks @Alexsey for your help (again). Where I can see that your output does what will work in MySQL, I am using MsSQL (SQL Server). So I don' think `SELECT ... FOR UPDATE` is actually possible.

Googling it, it seems `SELECT ... FROM tab1 WITH (UPDLOCK) WHERE ...` is what I need. Is this even possible? Or is there a way you can try on a MsSQL database?

**Comment by Alexsey** [comment]
@PCFNode sorry, I didn't notes this :( hope someone with experience with MsSQL may answer

**Comment by PCFNode** [comment]
I guess this can be closed. Researching MsSQLs locking, along with the Sequelize source, Locking isnt supported. Who knows how to actually do what I want to do, however this is a more generalised SQL server question than a Sequelize one

**Comment by tony-gutierrez** [comment]
@PCFNode You ever figure out locking in mssql transaction via sequelize?

**Comment by mgibson91** [comment]
Personally, I feel like this should be a pretty essential part of Sequelize

**Comment by bkang003** [comment]
@PCFNode Did you get the chance to try table hints with sequelize?
