### ISSUE TITLE
npm install --save sequelize sequelize-cli, graceful-fs v3.0.0 and before will fail on node releases

### ISSUE THREAD

**Issue by webmobiles** [sequelize/sequelize#8230]
## What you are doing?
npm install --save sequelize sequelize-cli

## What is actually happening?
sequelize install different versions of graceful-fs, one is not compatible with node 8
`
graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.`

I did:

npm ls graceful-fs

and i get this:

npm ls graceful-fs
```
serversequelize@0.0.0 /Users/cherdave/projects/serversequelize
└─┬ sequelize-cli@2.8.0
  ├─┬ fs-extra@4.0.1
  │ ├── graceful-fs@4.1.11 
  │ └─┬ jsonfile@3.0.1
  │   └── graceful-fs@4.1.11  deduped
  ├─┬ gulp@3.9.1
  │ └─┬ vinyl-fs@0.3.14
  │   ├─┬ glob-watcher@0.0.6
  │   │ └─┬ gaze@0.5.2
  │   │   └─┬ globule@0.1.0
  │   │     └─┬ glob@3.1.21
  │   │       └── graceful-fs@1.2.3 
  │   └── graceful-fs@3.0.11 
  └─┬ yargs@8.0.2
    └─┬ read-pkg-up@2.0.0
      └─┬ read-pkg@2.0.0
        └─┬ load-json-file@2.0.0
          └── graceful-fs@4.1.11  deduped

```

**Comment by sushantdhiman** [comment]
Issue moved to https://github.com/sequelize/cli/issues/344 

CLI use `gulp@3` which include this dependency

https://github.com/sequelize/cli/issues/441 v4 is coming soon, where gulp is no longer used by cli
