### ISSUE TITLE
Nested includes

### ISSUE THREAD

**Issue by sluchznak** [sequelize/sequelize#8233]
## What you are doing?

```js
export default (sequelize, DataTypes) => {
  const Comment = sequelize.define('Comment', {
    // ...
  }, {
    // ...
  });

  Comment.associate = (models) => {
    Comment.belongsTo(models.Project, { as: 'project', foreignKey: 'project_id' });
    Comment.hasMany(models.Comment, { as: 'replies', foreignKey: 'parent_id' });
  };

  Comment.loadScopes = (models) => {
    // ???
  };

  return Comment;
};

```

I want to load only replies recursive without a project and other available associations.
```js
{
  "replies": [
    {
      "replies": [
        {
          ...
        }
      ]
    }
  ]
}
```

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect: postgres
__Database version: 9.5
__Sequelize version:4.6.0

**Comment by Alexsey** [comment]
[sequelize-hierarchy plugin](https://github.com/overlookmotel/sequelize-hierarchy) might be the thing you are looking for
