### ISSUE TITLE
Can't delete sqlite file even after explicit closing all connections

### ISSUE THREAD

**Issue by Deilan** [sequelize/sequelize#8235]
## What you are doing?
I am creaing a sqlite3 db file, add some data to it, close all connections and delete the file.

See a [repo](https://github.com/Deilan/sequelize-typescript-issue-117) with a sample code.

0. `git clone https://github.com/Deilan/sequelize-typescript-issue-117.git`
1. `yarn install` or `npm install`
2. `npm start`

## What do you expect to happen?
Connections to be closed and file to be deleted successfully. Here's a snippet:
```typescript
async function main(): Promise<void> {
    const { path, cleanupCallback } = await tmpAsync.file();
    // tslint:disable:object-literal-sort-keys
    const sequelize = new Sequelize({
        name: "db",
        dialect: "sqlite",
        username: "",
        password: "",
        storage: path,
    });
    // tslint:enable:object-literal-sort-keys
    sequelize.addModels([Product, User, Address]);
    await sequelize.sync();
    await createProduct();
    const closeResult = await sequelize['connectionManager'].close();
    cleanupCallback();
}
```

## What is actually happening?
Error while trying to delete the file with `cleanupCallback();`:
```
Exception has occurred: Error
Error: EBUSY: resource busy or locked, unlink 'C:\Users\Deilan\AppData\Local\Temp\tmp-7516IuPpqkkQO1rX.tmp'
    at Object.fs.unlinkSync (fs.js:1081:18)
    at _removeCallback (c:\Dev2\sequelize-typescript-issue-117\node_modules\tmp\lib\tmp.js:391:10)
    at _cleanupCallback (c:\Dev2\sequelize-typescript-issue-117\node_modules\tmp\lib\tmp.js:446:7)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:19:9
    at Generator.next (<anonymous>)
    at fulfilled (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:4:58)
```

__Dialect:__ sqlite
__Database version:__ 3.1.9
__Sequelize version:__ 4.8.0

**Comment by rensrongen** [comment]
I ran across the exact same problem.
A possible solution was mentioned by @nadrane last year, but it appears to have never been implemented, and the issue ran stale. (https://github.com/sequelize/sequelize/issues/6798)

It would be great if there were at least a temporary workaround.

**Comment by rensrongen** [comment]
Alright, I found this workaround that enabled me to close the sqlite connection manually:

```
var queryInterface = sequelize.getQueryInterface();
queryInterface.sequelize.connectionManager.connections.default.close(); // manually close the sqlite connection which sequelize.close() omits
sequelize.close();
fs.unlinkSync(file.path); // file can now be unlinked
```

I'll be using this until the library has been fixed.

**Comment by itrew** [comment]
@rensrongen Thanks!
Using `models.sequelize.connectionManager.connections.default.close()` instead of `models.sequelize.close()` worked for me. I was just spinning up a temp database for a unit test and destroying after the tests are done. Now it creates, tests, and removes the db.

**Comment by Deilan** [comment]
This one isn't stale.

**Comment by cjreysayago** [comment]
Hi
If someone of you are using Jest as testing framework, be carefull of parallel test execution.
Me and my team, face this trouble even after explicitly close the connection with the methods exposed above in this thread.

Our Setup and Teardown was:
```javascript
beforeEach(async () => {   
    return migrator.up()
})

afterEach(async () => {
   User.sequelize.getQueryInterface().sequelize.connectionManager.connections.default.close()
   User.sequelize.close()
   return migrator.down()
})
```

And one of the tests:

```javascript
test('A User can be created', async () => {
    const userFactory = new User({
        name: 'admin'
    })
    const user = await userFactory.save()
    expect(user.name).toBe('admin')
})
```

When a new tests was added into our workflow _EBUSY_ related error appeared
------------------------------------
Solution we found was set a new execution parameter to the `jest` command that makes Jest run tests in a non parallel mode

Now, our test command is `jest --runInBand`

Also, if your using **Umzug** as migration library. You must close that connection. This one is related to Sequelize instance you pass as a parameter to Umzug

Settin UMZUG instance
```javascript
this.sequelize = new Sequelize(this.sequelizeConfig)
    return new umzug({
      storage: 'sequelize',
      storageOptions: {
        sequelize: this.sequelize
      },
      migrations: {
        params: [
          this.sequelize.getQueryInterface(),
          Sequelize
        ],
        path: this.migrationPath,
      }
})
```
And then close the connection
```javascript
this.sequelize.getQueryInterface().sequelize.connectionManager.connections.default.close()
this.sequelize.close()
```

Hope can help anyone facing the same trouble 👍

**Comment by Deilan** [comment]
Not stale.

**Comment by sushantdhiman** [comment]
Connections are now properly closed with any extra files removed https://github.com/sequelize/sequelize/pull/9851
