### ISSUE TITLE
 sequelize support stream now ?

### ISSUE THREAD

**Issue by xihuanhh** [sequelize/sequelize#8241]
just as the title, sequelize support stream now ?
i has checked the document, i can not find any function which  implement Stream already.
if it has been implement, can everyone give me some example?
thanks a lot!

## What you are doing?

```js
// code here
```

## What do you expect to happen?
**Model.find().stream().pipe()**

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Database version:__ XXX
__Sequelize version:__ XXX

**Comment by sushantdhiman** [comment]
No
