### ISSUE TITLE
How do I prevent an association from being created if it already exists?

### ISSUE THREAD

**Issue by booboothefool** [sequelize/sequelize#8242]
Given the following tables:
```
events: id(pk) place_id(fk) ...
places: id(pk) google_place_id ...
```
models:
```
const Event = sequelize.define('event', {
  // id(pk)
  name: {type: Sequelize.STRING},
  description: {type: Sequelize.STRING},
  date_range: {type: Sequelize.RANGE},
  logo: {type: Sequelize.STRING},
}, {
  timestamps: false,
  underscored: true,
});

const Place = sequelize.define('place', {
  // id(pk)
  google_place_id: {type: Sequelize.STRING},
  name: {type: Sequelize.STRING},
  geom: {type: Sequelize.GEOMETRY('POINT')},
}, {
  timestamps: false,
  underscored: true,
});
```
associations:
```
Event.Place = Event.belongsTo(Place);
Place.Events = Place.hasMany(Event);
```
If I ran this code twice with the same `place` information, it would create the same `Place` twice, just with different `id(pk)`. Said differently, there would be 2 'Willy Wonka's Chocolate Factory' in `places` table because `id(pk)` is different, when this should be only one unique place.
```
const place = {
          google_place_id: 'ChIJrTLr-GyuEmsRBfy61i59si0',
          name: 'Willy Wonka's Chocolate Factory',
          geom: { type: 'Point', coordinates: [-69.5398914,20.8829067] },
        };

Event.create({
        name: 'Some Event',
        place,
        description: 'It's fun!',
        date_range: [2017-09-01, 2017-09-03],
        logo: 'http://website.com/image.png',
      }, {
        include: [{
          association: Event.Place,
        }],
      });

Event.create({
        name: 'Some Other Event At The Same Place',
        place,
        description: 'It's NOT fun!',
        date_range: [2017-09-04, 2017-09-05],
        logo: 'http://otherwebsite.com/image.png',
      }, {
        include: [{
          association: Event.Place,
        }],
      });
```
How do I prevent this duplication from happening? I want to only create that `place` association if it doesn't already exist.

I was thinking perhaps I could do `google_place_id(pk)` since those should be unique, but am not sure if this is the right approach.
```
events: id(pk) google_place_id(fk) ...
places: google_place_id(pk) ...
```

**Comment by booboothefool** [comment]
Okay so I tried the second method where: 
```
events: id(pk) google_place_id(fk) ...
places: google_place_id(pk) ...
```
Now when I run `Event.create()`, it doesn't create the `Event` at all and returns with `SequelizeUniqueConstraintError: Validation error`. I guess this is kind of on the right track because I think it is realizing the `Place` already exists. 

Back to my question: How can I get the `Event` to still create, but not create a duplicate `Place`?

**Comment by booboothefool** [comment]
This seems to do what I want it to do, but do let me know if there is a better way with Sequelize! 👍 

```
      const placeAlreadyExists = await.Place.findById(place.id);

      if (placeAlreadyExists) {
        return Event.create({
          name,
          place_id: place.id,
          description,
          date_range,
          logo,
        });
      }

      return Event.create({
        name,
        place: {
          id: place.id,
          name: place.name,
          geom: { type: 'Point', coordinates: [place.geom.y,place.geom.x] },
        },
        description,
        date_range,
        logo,
      }, {
        include: [{ association: Edit.Place }],
      });
```

**Comment by brettvitaz** [comment]
Once you have the Event and Place instances, you can can use `event.setPlace(place)`. This will not create a new Place.

**Comment by isabellachen** [comment]
This is actually a good question. Isn't there a way to create a belongsTo item with a foreign key that already exists without actually having to go find that key first and put it in?
