### ISSUE TITLE
Resource not currently part of this pool every day at 11 AM

### ISSUE THREAD

**Issue by bilby91** [sequelize/sequelize#8243]
__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.2.1

Hello, 

We are getting `Resource not currently part of this pool` this error every day at 11 AM UTC. It's like a clock, we have it every single day and is the only time during the day that happens. 

Anyone has any idea of why this could be happening  ? We couldn't figure out the issue.

**Comment by lext-7** [comment]
Perhaps, you get a sql error which is not throw correctly. See https://github.com/sequelize/sequelize/pull/8247.

**Comment by bilby91** [comment]
@lext-7 Thanks for the tip. We have updated to the latest version to see if is this help. Good thing is that since is happening at a particular time every day it will be easy to verify 😃

**Comment by bilby91** [comment]
Latest version seem to solve the issue.
