### ISSUE TITLE
Instance.decrement doesn't work with negative value

### ISSUE THREAD

**Issue by dotpack** [sequelize/sequelize#8253]
## What you are doing?

I'm calling ```Instance.decrement``` with the negative value.
```js
const assert = require('assert');
const Sequelize = require('sequelize');
const sequelize = new Sequelize('database', 'username', 'password', {
  // dialect: 'postgres',
  dialect: 'sqlite',
  storage: ':memory:'
});

const User = sequelize.define('user', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
    defaultValue: Sequelize.UUIDV4
  },
  username: {
    type: Sequelize.STRING,
    allowNull: false
  },
  balance: {
    type: Sequelize.INTEGER,
    defaultValue: 0
  }
});

sequelize.sync()
  .then(() => User.create({ username: 'alice' }))
  .then(user => user.decrement({ balance: -5 }))
  // UPDATE `users` SET `balance`=`balance`--5,`updatedAt`='2017-09-05 07:44:49.742 +00:00' WHERE `id` = 'db0fb06a-c4ea-465a-8974-744c521f684d'
  //                                       --^ sql comment
  .then(user => user.reload())
  .then(user => assert(user.balance === +5))
;
```

## What do you expect to happen?
I wanted the user balance to be +5

## What is actually happening?
But the balance of the user has not changed

~~__Dialect:__ any~~
~~__Database version:__ any~~
~~__Sequelize version:__ 4.8.0~~

__Dialect:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ 4.8.0

__Dialect:__ sqlite
__Database version:__ 3.16.0
__Sequelize version:__ 4.8.0

**Comment by Alexsey** [comment]
Works ok in MySQL. So **Dialect** is at list not "any"

**Comment by dotpack** [comment]
__Dialect:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ 4.8.0

__Dialect:__ sqlite
__Database version:__ 3.16.0
__Sequelize version:__ 4.8.0
