### ISSUE TITLE
How to backup sqlite through sequelize?

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#8257]
## What you are doing?
I want backup sqlite to sql file through sequelize,i havn't find it in dcoument.

## What do you expect to happen?
how to do?

__Dialect:sqlite 
__Database version:3
__Sequelize version:4.0

**Comment by abhiuser** [comment]
Do we have a solution to this ?

**Comment by asifalikhokhar** [comment]
I think this issues hasn't been addressed yet !

**Comment by zailushang1996** [comment]
How to backup sqlite through sequelize?

**Comment by radiorz** [comment]
How to backup sqlite through sequelize? maybe just copy sqlite  database file may work
