### ISSUE TITLE
Docs: read replication not explained, unclear what that exactly means (for you)

### ISSUE THREAD

**Issue by COLABORATI** [sequelize/sequelize#8271]
On the frontpage of this project you are using the term `read replication` but these words are not explained anywhere. I found one very short [description](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor) of `options.replication`, but it does not explain any concepts or strategies behind that setting.

I would like to better understand this feature and your take on it. As there are many different implementations of some kind of "replication" that come with different DB engines, it is very interesting to understand your ideas and how sequelize handles that. As this feature is important enough to be mentioned in the first sentence of the project description it is strange not to read anything about it in the docs. 

Thank you very much for your attention!

**Comment by sushantdhiman** [comment]
An entire document was missing from documentation hosting. Its now restored. You can find details about read replication [here](http://docs.sequelizejs.com/manual/installation/usage.html#read-replication)
