### ISSUE TITLE
[mssql] dropAllSchemas does nothing

### ISSUE THREAD

**Issue by RoelRoel** [sequelize/sequelize#8273]
## What you are doing?
Trying to completely remove all tables from a test database for automatic testing 

## What do you expect to happen?
dropAllTables should remove all tables and views

## What is actually happening?
Nothing. The only query that it executes is:

`SELECT "name" as "schema_name" FROM sys.schemas as s WHERE "s"."name" NOT IN ( 'INFORMATION_SCHEMA', 'dbo', 'guest', 'sys', 'archive' ) AND "s"."name" NOT LIKE 'db_%'`

__Dialect:__ mssql
__Database version:__ 
__Sequelize version:__ 3.30.4

**Comment by sushantdhiman** [comment]
Please try with latest version, I dont think any member will ever try to fix a bug for v3 :)

**Comment by damien-git** [comment]
I'm seeing the same issue with sequelize 5.21.2, tedious 8.2.0, and mssql from the docker image mcr.microsoft.com/mssql/server:2019-latest. The same code works with mysql, but with mssql dropAllSchemas() does not drop the tables. I use it for cleanup with jest.

**Comment by damien-git** [comment]
Should there really be quotes around "name" in that query ???
https://github.com/sequelize/sequelize/blob/5822bc793abe1cffd6220ba7888a5f925c51cb02/lib/dialects/mssql/query-generator.js#L93

```
1> SELECT "name" as "schema_name" FROM sys.schemas as s
2> go
schema_name
-----------
name       
name       
name       
name       
name       
name       
name       
name       
name       
name       
name       
name       
name       
```

Also this query returns nothing for me even after I fix the syntax. Nothing is listed with `select name from sys.schemas` beyond what is explicitly excluded (`INFORMATION_SCHEMA` etc).

**Comment by damien-git** [comment]
For anybody else with the same issue: I found that using `sequelize.drop()` instead of `sequelize.dropAllSchemas()` does what I was looking for (dropping all tables). The issue with `dropAllSchemas()` is that it's going to drop all tables with mysql, but will not with mssql when using the default (`dbo`) schema.
