### ISSUE TITLE
Automatically pass transactions to all queries in automanaged transaction not works

### ISSUE THREAD

**Issue by alexey2baranov** [sequelize/sequelize#8279]
## What you are doing?
two operations inside automatic transaction

```js
    result = await models.sequelize.transaction(async() => {
      model = await models[type].create(plain)
      attachment = await models.File.findById(EACH_ATTACHMENT)
    })
```

## What do you expect to happen?
i wana see transaction and two operations (create and select) inside it 

## What is actually happening?
transaction opened, then create operation inside it, then select operation outside it (see logs)

_Output, either JSON or SQL_

> [2017-09-09 22:44:40.329] [INFO] console - Executing (6d360132-f594-46c3-8355-74ad34aa759e): START TRANSACTION;
> [2017-09-09 22:44:40.330] [INFO] console - Executing (6d360132-f594-46c3-8355-74ad34aa759e): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
> [2017-09-09 22:44:40.338] [INFO] console - Executing (6d360132-f594-46c3-8355-74ad34aa759e): INSERT INTO "Zemla" ("id","name","level","obshinaSize","path","created_at","updated_at","parent_id") VALUES (DEFAULT,'unit test',0,0,'/1/','2017-09-09 17:44:40.331 +00:00','2017-09-09 17:44:40.331 +00:00',1) RETURNING *;
> [2017-09-09 22:44:40.352] [INFO] console - Executing (default): SELECT "id", "name", "path", "note", "mimeType", "size", "created_at", "updated_at", "deleted_at", "kopa_id", "owner_id", "zemla_id", "kopnik_id", "predlozhenie_id", "slovo_id", "golos_id", "registration_id" FROM "File" AS "File" WHERE ("File"."deleted_at" IS NULL AND "File"."id" = 1);
> [2017-09-09 22:44:57.603] [INFO] console - Executing (default): UPDATE "File" SET "zemla_id"='180',"updated_at"='2017-09-09 17:44:57.590 +00:00' WHERE "id" = '1'

__Dialect:__postgres
__Database version:9.5
__Sequelize version:3.30.4

**Comment by Alexsey** [comment]
Your callback should accept an instance of transaction and you should pass it to all operations you want it to be in same transaction as `transaction` field of second argument. See the first example of [transaction documentation page](http://docs.sequelizejs.com/manual/tutorial/transactions.html)

**Comment by Alexsey** [comment]
Actually it looks like a bug that `INSERT` operation is performing in transaction

**Comment by alexey2baranov** [comment]
This is not bug.  iI use  Automatically pass transactions to all queries
feature.

11 сент. 2017 г. 7:26 PM пользователь "Alexsey" <notifications@github.com>
написал:

**Comment by Alexsey** [comment]
Are you using [CLS](https://github.com/othiym23/node-continuation-local-storage)?

**Comment by alexey2baranov** [comment]
Yes i do

**Comment by Alexsey** [comment]
Ok, then sorry - no experience with this stuff. Maybe some one else could help

**Comment by alexey2baranov** [comment]
this short test illustrates issue. as you can see there are two equal tests. first one is in new async/await syntax, second one is old-school promise then.then.then syntax. Old-school works perfect. But new async/await syntax execute first query in tran only. 
```js
    describe.only('cls transaction github issue', () => {
      it('async/await syntax', (done) => {
        models.sequelize.transaction(async (t1) => {
          await model.sequelize.query("select 1", {type: model.Sequelize.QueryTypes.SELECT})
          await model.sequelize.query("select 2", {type: model.Sequelize.QueryTypes.SELECT})
          await model.sequelize.query("select 3", {type: model.Sequelize.QueryTypes.SELECT})
          if (models.sequelize.Sequelize.cls.get('transaction') !== t1) {
            done("transaction !== t1")
          }
        })
      })

      it('then.then.then syntax', (done) => {
        models.sequelize.transaction((t1) => {
          return model.sequelize.query("select 1", {type: model.Sequelize.QueryTypes.SELECT})
            .then(() => {
              return model.sequelize.query("select 2", {type: model.Sequelize.QueryTypes.SELECT})
            })
            .then(() => {
              return model.sequelize.query("select 3", {type: model.Sequelize.QueryTypes.SELECT})
            })
            .then(() => {
              if (models.sequelize.Sequelize.cls.get('transaction') !== t1) {
                done("transaction !== t1")
              }
              else {
                done()
              }
            })
        })
      })
    })
```

> Executing (be60f2c1-ec61-49b3-b728-a5f1b9ca97af): START TRANSACTION;
> Executing (be60f2c1-ec61-49b3-b728-a5f1b9ca97af): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
> Executing (be60f2c1-ec61-49b3-b728-a5f1b9ca97af): select 1
> Executing (default): select 2
> Executing (default): select 3
> Executing (be60f2c1-ec61-49b3-b728-a5f1b9ca97af): COMMIT;
> 
> Error: done() invoked with non-Error: transaction !== t1
>     at models.sequelize.transaction (test/Infrastructure.Test.js:50:13)
>     at <anonymous>
> Executing (a2652943-2001-4a56-a389-33083d3325b6): START TRANSACTION;
> Executing (a2652943-2001-4a56-a389-33083d3325b6): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
> Executing (a2652943-2001-4a56-a389-33083d3325b6): select 1
> Executing (a2652943-2001-4a56-a389-33083d3325b6): select 2
> Executing (a2652943-2001-4a56-a389-33083d3325b6): select 3
> Executing (a2652943-2001-4a56-a389-33083d3325b6): COMMIT;

**Comment by Alexsey** [comment]
I think the issue could be because `Sequelize` uses `bluebird` for promises while `async/await` would use native promises. You could try to compile `async/await` to `bluebird` promises with `babel` and see what happened

**Comment by alexey2baranov** [comment]
I did babel as a temp workaround. But i would like to know when it will
work without babel.

13 сент. 2017 г. 1:42 PM пользователь "Alexsey" <notifications@github.com>
написал:

**Comment by Alexsey** [comment]
So babel did work and this is really the issue?

**Comment by alexey2baranov** [comment]
Babel must die. It must work with native async/await i think

13 сент. 2017 г. 3:01 PM пользователь "Alexsey" <notifications@github.com>
написал:

**Comment by Alexsey** [comment]
Yes, it probably should work. But this is an issue and here should be clear explanation of what is wrong and any clues that could help someone who would try to fix it

**Comment by alexey2baranov** [comment]
It doesn't work without babel. This is my issue.

13 сент. 2017 г. 3:14 PM пользователь "Alexsey" <notifications@github.com>
написал:

Yes, it probably should work. But this is an issue and here should be clear
explanation of what is wrong and any clues that could help someone who
would try to fix it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sequelize/sequelize/issues/8279#issuecomment-329123312>,
or mute the thread

**Comment by Alexsey** [comment]
@eyelidlessness at first, the only who will receive a notification about your comment is me and topic starter

At second, CLS is not working with async/await and never will - it's not a Sequelize issue. It might work if async/await would be transformed with babel to generators or callbacks... but it isn't.  Not sure that it's a bug. Probably it's a feature request. But now all maintained versions of Node supports async/await natively so no one is interesting to make it work with transpiled code

You may try to use [CLS-hookes](https://github.com/Jeff-Lewis/cls-hooked/blob/master/README.md) and make a new issue if it wouldn't work

**Comment by Alexsey** [comment]
@eyelidlessness https://github.com/othiym23/node-continuation-local-storage/issues/98#issuecomment-375080556 is saying that he got it work with CLS-hooks
