### ISSUE TITLE
docs did not talk about importing models

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/sequelize#8290]
- sequelize@4.2.0
- electron@1.6.11
- electron-builder@10.17.3
- dialect: sqlite

```js
import fs from 'fs';
import path from 'path';
import sequelize from '../main_process/Database';
import Sequelize from 'sequelize';

let basename = path.basename(__filename);
let db = {};

fs.readdirSync(__dirname)
.filter(function(file) {
  return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
})
.forEach(function(file) {
  let model = sequelize['import'](path.join('../../', __dirname, file));
  db[model.name] = model;
});

Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

The code above will import all my models into the `models/index.js` so when I need my models I simply need to `import models from '../models';` which will then allow me to make transactions via `models.my_model`.

It works while on development, but when I package my app with `electron-builder` the `models directory` will no longer exist and if I run the app it will throw an error saying that it cannot find the `models directory`.

I bundle all my renderer files into one file called `app.js` and also bundle my main process files into a separate file called `main.js`. I actually don't want to include the `models directory` to the package since I bundle all my files it doesn't make sense to do that but `fs.readdirSync` would require the `models directory`.

I have tried importing all my models in my `index.js` one by one, but it didn't work.

```js
import model_name from './model_name';

db['model_name'] = model_name;
```

I was hoping that you can somehow tell me or point me to a solution that will import all the models into the `models/index.js` file so that I don't have to include the `models directory` in the package and I will be able to use my models by doing

```js
import models from '../models'; // will import index.js from the models directory

ipcMain.on(...., (event, args) => {
  models.my_model.all(....)
  .then(....)
  .catch(....);
});
```

I read the docs and can't find anything related to this.

**Comment by aprilmintacpineda** [comment]
I already found a way that works.

**Comment by lysla** [comment]
@aprilmintacpineda Hi if you could kindly share with me what was your solution about this. I replied on your similar issue in https://github.com/sequelize/express-example/issues/71

Thanks in advance
