### ISSUE TITLE
QueryType not set in getForeignKeysForTable

### ISSUE THREAD

**Issue by ChrisWint** [sequelize/sequelize#8291]
In the getForeignKeysForTable, the QueryType is not set to FOREIGNKEYS
https://github.com/sequelize/sequelize/blob/de0fbff2e7ced52da3f9bef560def83ef6db6f94/lib/query-interface.js#L447

This leads to issues with the result parsing as the intended parsing methods are not used then, e.g. for Postgres:

https://github.com/sequelize/sequelize/blob/de0fbff2e7ced52da3f9bef560def83ef6db6f94/lib/dialects/postgres/query.js#L158

is not triggered.

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/a6c1f8f9355497648ac35dfeda3c0b37f3ceaca4
