### ISSUE TITLE
Bug in code on site.

### ISSUE THREAD

**Issue by LohitakshTrehan** [sequelize/sequelize#8292]
Syntax of code is wrong link:  `http://docs.sequelizejs.com/manual/tutorial/models-usage.html`

please see image and `count()` section of the page (image included)
![screen shot 2017-09-12 at 2 57 24 pm](https://user-images.githubusercontent.com/22133083/30318583-2d6bf7f0-97cb-11e7-9feb-632ec244e9f9.png)

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/02050875a5473a4f6f5192b10fb9295a21a69a68

**Comment by LohitakshTrehan** [comment]
👍
