### ISSUE TITLE
How to correctly retry transactions

### ISSUE THREAD

**Issue by depoulo** [sequelize/sequelize#8294]
> Please note this is an issue tracker, not a support forum.
> For general questions, please use StackOverflow or Slack.

Why I'm asking here anyway:

> ![grafik](https://user-images.githubusercontent.com/4457202/30326090-a3a80a20-97c7-11e7-9940-094254411924.png)

Now to the question: I'd like to know what to put into [retry-as-promised](https://github.com/mickhansen/retry-as-promised)'s `match` option when retrying transactions. I want to catch everything worth retrying (deadlocks, connection  errors and the like), and nothing not worth retrying (syntax errors,  error responses from the DB like "Data too long for column" etc.).  This is what I currently have (MySQL):

```js
match: [ // Must match error signature (ala bluebird catch) to continue
    Sequelize.ConnectionError,
    Sequelize.ConnectionRefusedError,
    Sequelize.ConnectionTimedOutError,
    Sequelize.OptimisticLockError,
    Sequelize.TimeoutError,
    'SequelizeDatabaseError: Deadlock found when trying to get lock; try restarting transaction',
    'ER_LOCK_DEADLOCK'
]
```

It would make me feel safer if anybody could assure me I'm not missing anything here.

**Comment by sushantdhiman** [comment]
I am not sure about `SequelizeDatabaseError: Deadlock found when trying to get lock; try restarting transaction`, may be just the message. Rest looks ok to me

**Comment by depoulo** [comment]
Thanks, that one I know for sure that I need it, I have tests starting concurrent transactions which fail without it. That's actually the heart of the problem: There, the deadlock is just a plain `SequelizeDatabaseError`, like SQL syntax errors for instance. But I'll give it a try with just the message. Still feeling a bit uncomfortable since if the message changes only slightly (say, between versions, or between MariaDB and MySQL) the transaction won't be retried.

**Update:** Just found out that [retry-as-promised also takes RegExps](https://github.com/mickhansen/retry-as-promised/blob/master/index.js#L61), thus I'd be better off replacing the last two entries with something like something like `/Deadlock/i`.

**Comment by sushantdhiman** [comment]
Both MariaDB and MySQL are fully compatible. As for changing messages or error type we try our best to follow SEMVER, so same message is pretty much guaranteed for a major Sequelize version.

Regex options seems good way to cover that error :)

I think we can close this issue

**Comment by depoulo** [comment]
Alright, thanks and greetings to Chandigarh :)

**Comment by rubens21** [comment]
@depoulo Which MySQL version are you using?
Apparently, some MySQL versions rollback the whole transaction if a dead lock is detected (https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlock-detection.html). And Sequelize retry only the last failed query.
To avoid it you may disable the deadlock detection (innodb_deadlock_detect) and the ensure that innodb_rollback_on_timeout if off (off is the default).

Please let me know if a said something wrong @sushantdhiman

**Comment by depoulo** [comment]
@rubens21 MariaDB 10.1.12 for development, for production it's MySQL, version I don't know, nor do I care ;)

Please see [my comment here](https://github.com/sequelize/sequelize/issues/8352#issuecomment-332126781). In my project I have multiple tests running 3 simultaneous transactions each on both managed and unmanaged transactions (Sequelize terms), and haven't experienced any inconsistencies.

**Comment by dskvr** [comment]
How to retry without conditions? `{ retry: {} }`. Documentation is incomplete, no examples.

**Comment by cirosantilli** [comment]
> How to retry without conditions?
> 
> `{ retry: {} }`
> 
> Documentation is incomplete, no examples.

Likely:

```
{ retry: { max: 999999999999, /.?/ } }
```

Max is mandatory, retry never happens without: https://github.com/mickhansen/retry-as-promised/blob/5adc050ead38f513891c7afb3c94222dee33f739/index.js#L84 as `undefined <` n is always false.

PostgreSQL workaround: https://stackoverflow.com/questions/68427796/sequelize-transaction-retry-doenst-work-as-expected/70204395#70204395

**Comment by sebakc** [comment]
> How to retry without conditions?
> 
> `{ retry: {} }`
> 
> Documentation is incomplete, no examples.

You can use something like

`{ retry: { max: Infinity, match: [/.?/] } }`

I use something similar and I haven't had any problem yet
