### ISSUE TITLE
How to update records in multiple association  models 

### ISSUE THREAD

**Issue by rahulopenxcell** [sequelize/sequelize#8296]
## What you are doing?

return db.product.findById( 75759,{
                    include: [
                        {
                            model: db.productDescription
                        }
                    ]})
                .then(product => {
                    var rahulpro = {};
                    Object.assign(rahulpro,product);
                    // console.log(rahulpro.product_description.description);
                    rahulpro.name = "44444";
                    rahulpro.product_description.dataValues.description = "rahul";
                    product.updateAttributes(rahulpro);
                  });
                 

## What do you expect to happen?
we want to update data of description model

## What is actually happening?
Nothing  changed database of description

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Database version:__ mysql 5.7
__Sequelize version:__ 4.8.3

**Comment by MikeDabrowski** [comment]
Have you managed to solve this?
