### ISSUE TITLE
Connections are not evicted, regardless of configuration

### ISSUE THREAD

**Issue by freitagbr** [sequelize/sequelize#8298]
## What you are doing?
I have configured the connection pool to evict connections after 60 seconds:

```js
const sequelize = new Sequelize(uri, {
    logging: false,
    pool: {
        max: 10,
        min: 5,
        idle: 10000,
        evict: 60000
    }
});
```

## What do you expect to happen?
Idle connections should be evicted after 60 seconds (or whatever is configured).

## What is actually happening?
Connections are not evicted. I have diagnosed this issue, though. Sequelize configures `generic-pool` with [`autostart: false`](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L200). `generic-pool`, however, only evicts connections [once the pool is started](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L364). Normally, this happens automatically if [`autostart` is set to `true`](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L119). But in sequelize, `autostart` is hard-coded to `false` , and the `start()` method is never called, so connections are never evicted, no matter the configuration.

__Dialect:__ any
__Database version:__ any
__Sequelize version:__ 4.8.3

**Comment by jtan25** [comment]
Running into the same issue

**Comment by jtan25** [comment]
Temp fix found for me :  https://github.com/sequelize/sequelize/pull/7924#issuecomment-325378123

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/48a7690c37f955cb7c61578cb05df4241f9fb05f
