### ISSUE TITLE
[Feature request] Setting to make logs useful

### ISSUE THREAD

**Issue by aledalgrande** [sequelize/sequelize#8299]
## What you are doing?
Trying to debug the queries I wrote.

## What do you expect to happen?
I should be able to get just a line in the logs describing what SQL was generated. Nothing else. Maybe it should be the default setting for the logger.

## What is actually happening?
I either can have no logs, or a humongous quantity of logs which makes development very frustrating.

__Dialect:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ Node: 8.2.1, CLI: 2.8.0, ORM: 4.4.2

**Comment by sushantdhiman** [comment]
I dont get what issues you are having, but Sequelize have good log filtering 

1) Query / Method level

```
findAll({
   logging: console.log
})
```
Or 

```js
sequelize.query("", { logging: console.log });
```

2) System level logs

You can log all queries by passing `logging` option to Sequelize constructor

3) Debug support

You can get various different log levels using `DEBUG=sequelize*`, then filter them as per your need and as explained by debug module https://github.com/visionmedia/debug

**Comment by ivolucien** [comment]
For anyone finding this looking for details, checkout the Wildcards section in the [debug repo](https://github.com/visionmedia/debug)
**and** search for 'debugContext' in the source code. There are a bunch of contexts you can filter by, like `sql:mysql`, `pool`, `connection:mariadb`, `hooks`, etc.
