### ISSUE TITLE
How to use instanceMethods toJSON - v4

### ISSUE THREAD

**Issue by DavidVeloso** [sequelize/sequelize#8303]
## What you are doing?

Hi!

I'm trying use toJSON instanceMethods to 'custom return'

Before in v3 this worked:
```js
    instanceMethods: {
      toJSON: function () {
        // this.get() - return object
        let values = Object.assign({}, this.get())
        values.something = 'foo'
        return values
      } 
   }
```
In v4 I'm trying:
```js
   1-
       Model.prototype.toJSON = () => {
           let values = this.get() //return undefined
       }

   2-  Model.prototype.toJSON = (values) => {
            values //return 0
       }

```

Any help ? (: 

__Dialect:__ mysql
__Database version:__ 14.14
__Sequelize version:__ 4.8.0

**Comment by zamrq** [comment]
using Model.build

**Comment by DavidVeloso** [comment]
@zamrq Hi! (: 
Model.build create a new Sequelize model instance, but I need use a instance coming of database and manipulate it. Ex.: return of findOne an findAll

**Comment by janmeier** [comment]
Don't use an arrow function - It's not possible to overwrite the `this` in an arrow function

**Comment by sushantdhiman** [comment]
👆

**Comment by DavidVeloso** [comment]
Thanks!!! I remove arrow function and works!
