### ISSUE TITLE
About sequelize.query get duplicate data

### ISSUE THREAD

**Issue by wazsq** [sequelize/sequelize#8307]
## This is my sequelize
`
sequelize.query(`
            select cu.ID id, cu.customer_group_id, cu.customer_unit_name, cu.contact_name
            from customer_unit cu, customer_group cg
            where cu.ID = '${id}' and cg.id = cu.customer_group_id`);
`

## Desired result
`
[ TextRow {
      id: 'a6f5adc9-0b4a-4f0c-9661-13aa0b9f2024',
      customer_group_id: '116386c0-e12e-4e7b-b9d5-c8bc77edf19c',
      customer_unit_name: '测试组名称',
      contact_name: '联系人姓名' } ]
`
## Actual results
`
[ [ TextRow {
      id: 'a6f5adc9-0b4a-4f0c-9661-13aa0b9f2024',
      customer_group_id: '116386c0-e12e-4e7b-b9d5-c8bc77edf19c',
      customer_unit_name: '测试组名称',
      contact_name: '联系人姓名' } ],
  [ TextRow {
      id: 'a6f5adc9-0b4a-4f0c-9661-13aa0b9f2024',
      customer_group_id: '116386c0-e12e-4e7b-b9d5-c8bc77edf19c',
      customer_unit_name: '测试组名称',
      contact_name: '联系人姓名' } ] ]
`

**Comment by janmeier** [comment]
http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-method-query 

```js
sequelize.query('SELECT...').spread((results, metadata) => {
  // Raw query - use spread
});

sequelize.query('SELECT...', { type: sequelize.QueryTypes.SELECT }).then(results => {
  // SELECT query - use then
})
```

**Comment by wazsq** [comment]
Thank you very much @janmeier
