### ISSUE TITLE
Bug -  belongsTo with targetKey

### ISSUE THREAD

**Issue by zamrq** [sequelize/sequelize#8311]
const User = this.sequelize.define('user', {/* attributes */})
const Company  = this.sequelize.define('company', {/* attributes */});

User.belongsTo(Company, {foreignKey: 'fk_companyname', targetKey: 'name'});

User.sync();
Company.sync();

-------------------

const User = this.sequelize.define('user', {/* attributes */})
 TypeError: Cannot read property 'define' of undefined

**Comment by sushantdhiman** [comment]
Please follow the issue template, strictly
