### ISSUE TITLE
afterSave hooks fire when update transaction fails

### ISSUE THREAD

**Issue by ckee83** [sequelize/sequelize#8314]
## What are you doing?

I'm would like to use a hook to address a cross-cutting concern, but am running into an issue where the hook is executing despite the hook trigger failing. I am using the `afterSave` hook because the logic expects the update to have happened and the database to reflect the new values. The save itself does not error, but is part of a transaction that fails following the save.

Specifically the hook is to queue an email notification job when a record status changes. This hook needs to not happen if the update fails.

```js
const Foo = sequelize.define('foo', {
  text: { type: Sequelize.STRING, defaultValue: 'initial text' },
});

const updateFooAndThrow = method((id, text) => {
  const execTransaction = transaction => {
    return Foo
      .findById(id, { transaction })
      .then(foo => {
        // assuming foo exists
        foo.text = text;
        return foo.save({ transaction });
      })
      .then(() => {
        throw new Error('I will break this transaction');
      });
  };

  return sequelize.transaction(execTransaction);
});

let count = 0;
Foo.afterSave(foo => {
  // This logic assumes a successful update!
  const msg = `"afterSave" hook called ${++count} times\n`;
  console.log(msg, inspect(foo.get({ plain: true }), { depth: null }));
});

Foo.create()
  .then(foo => updateFooAndThrow(foo.id, 'some text'))
  .then(() => {
    console.log('This line should be unreachable');
    process.exit(0);
  })
  .catch({ message: 'I will break this transaction' }, () => {
    console.log('foos table should contain initial text');
    process.exit(0);
  })
  .catch(err => {
    console.error(err.stack);
    process.exit(1);
  });
```

## What do you expect to happen?
I expected the `afterSave` hook not to fire. If the hook triggers after an update, I expect the database to reflect that update at the time of hook execution.

## What is actually happening?
The hook executed even though the update was rolled back due to a failed transaction

__Dialect:__ postgres
__Dialect version:__ 9.6.1
__Database version:__ 9.6.1
__Sequelize version:__ 4.7.4
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Hooks are still fired, but `transaction` instance is passed to hooks option. Any thing affecting database can use that `transaction` so no stale data got saved or updated

**Comment by ckee83** [comment]
I understand that the data is correct, the problem is that a hook fired even though an update did not occur. The transaction is no help in this case because the hook logic neither reads nor writes to the database. Also, the transaction will not be in a fail state until after the hook resolves.

To reiterate, my use-case is to add an email notification to the job queue when a record's status property changes. Hooking into `afterSave` works as expected when the `save()` is not part of a transaction, but my implementation requires a transaction and I need to prevent the hook from firing when a later part of the transaction fails, rolling back the update. Is there presently a way to accomplish this?

**Comment by ckee83** [comment]
@mickhansen pointed me to issue #2805 which encompasses my problem. I will continue pursuing a solution there.

**Comment by sushantdhiman** [comment]
Yeah for non database related changes, `afterCommit` makes sense. It was my assumption that you want to handle database change in after hooks
