### ISSUE TITLE
through: {}

### ISSUE THREAD

**Issue by DoctypeRosenthal** [sequelize/sequelize#8316]
I am a Sequlize user who upgraded from v3 to v4.
Now I read this:
http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

Previous:
`user.addProject(project, { status: 'started' })`

New:
`user.addProject(project, { through: { status: 'started' }})`

My question is: **WHY DID YOU DO THIS??**

The old API was much clearer and intuitive to use! 
Now I have to check all my associations and all my add/set/create Methods. This is really tricky. I wish you hadn't made this design choice!

**Comment by sushantdhiman** [comment]
What if you want to have a through table with field `transaction` and still want to use `transaction`

**Comment by DoctypeRosenthal** [comment]
Can you provide example code?

**Comment by sushantdhiman** [comment]
```js
var A = db.define('A', {});
var B = db.define('A', {});

// through model with field called transaction
var AB = db.define('A', {
   transaction: db.STRING
});

db.transaction(async function (transaction) {
   const a = await A.create({}, { transaction });
   const b = await B.create({}, { transaction });

   await a.setABs([b], {
       through: { transaction: 'Big Client' },
       transaction
   });
});
```

You cant do same with v3 @DoctypeRosenthal ,

**Comment by sushantdhiman** [comment]
Closing issue as I have explained my case

**Comment by DoctypeRosenthal** [comment]
Sorry that I didn't answer but I am unfortunately too busy right now. That doesn't necessarily mean, I agree with you. I just have too much other stuff on my agenda to have a profound look at this new API. You shouldn't have changed a running horse imo.

**Comment by sushantdhiman** [comment]
@DoctypeRosenthal Study my code sample in free time, we all are busy.

But I assure you we aren't changing things just for fun, there is a reason as I have explained for this change. This change was introduced in a major version, where you can always expect breaking changes
