### ISSUE TITLE
[docs] Documented pool.evict value is 0 (disabled), but code appears to use a value of 60000

### ISSUE THREAD

**Issue by caseyduquettesc** [sequelize/sequelize#8324]
The documentation shows that in the Sequelize constructor, options.pool.evict defaults to 0 (disabled), but the default options in the abstract connection manager uses a value of 60000.

[abstract connection manager defaults](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L16)
[doc reference for constructor options](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor)

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/commit/0f8417a2bef429698cd3eb4de34cf25f26d10873
