### ISSUE TITLE
Many-to-many model not created automatically

### ISSUE THREAD

**Issue by galioy** [sequelize/sequelize#8328]
## What are you doing?
I am initializing 2 models and declaring a M:M relation between them, which should automatically create a model in-between them.
It used to work on `v3.30.4`, but doesn't work afterwards.

```js
// Project model
associate: (models) => {
        project.belongsToMany(models.registration, {
          as: 'Registrations',
          through: 'project_registration',
          timestamps:false,
          foreignKey: 'project_id'
        });

// Registration model
associate: (models) => {
        registration.belongsToMany(models.project, {
          as: 'Projects',
          through: 'project_registration',
          timestamps: false,
          foreignKey: 'registration_id'
        });
```
So, the `project_registration` model used to be created automatically (and mapped to the `project_registration` table in the DB behind), but since I upgraded Sequelize, it is not created anymore.

__Dialect:__ postgres
__Sequelize version:__ 4.8.4
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Have you read http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html ? Are you using `classMethods` / `instanceMethods` ?

**Comment by galioy** [comment]
Yes, `associate` is a `classMethod` in my case. I haven't read that doc before, but now I did. I guess this can be marked as solved (even though I haven't tested with changes).
