### ISSUE TITLE
Model.update does not take into account paranoid

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#8338]
## What are you doing?

```js
// define a paranoid model
const User = sequelize.define('user', {/* ... */}, { paranoid: true });

// run an update query on said model
User.update({/* ... */}, { where: {/* ... */} });
```

## What do you expect to happen?
The resulting `UPDATE` query should only affect non-deleted records. In other words, I would expect a `WHERE deleted_at IS NOT NULL` clause.

At the very least, I would expect `Model.update` to accept a `paranoid` option much like the `Model.find` family of functions do.

## What is actually happening?
No `deleted_at` clause is added. Adding `paranoid: true` also has no affect.

__Dialect:__ postgres
__Dialect version:__
__Database version:__ 9.6
__Sequelize version:__ 4.8.3
__Tested with master branch:__ No (but relevant code hasn't changed on master)

**Comment by petersg83** [comment]
Hi,
was something done for this bug ?
I have the opposite problem :

I would like to update deleted records but there is no `paranoid` option on the `update` method. It only updates non-deleted records.
