### ISSUE TITLE
Different finds with same id get different instances

### ISSUE THREAD

**Issue by pablodgonzalez** [sequelize/sequelize#8345]
I'm get a registry in two different points in my app. While the app is running the instances is updated from those different points. The problem happen with the hooks. The "save" hook is triggered from the "same registry" when it is updated but this happened from two different functions.  

So, I'm expected the instances when I call find get the repository version and the second time, the instance in memory, so, there is just only one version, and updates and hooks are always from the same instance.

(just for clarify, the two different functions changes differents fields, so there isn't any kind of race condition o something like that.)

Maybe I'm losing something?

**Comment by sushantdhiman** [comment]
I need to see some code and please follow the issue template. Present your issue with a test case which can lead to quick resolution.

**Comment by pablodgonzalez** [comment]
Ok, when I have time I will do. But the issue is too simple (the most of ORM work in this way)
You call find(1) => get entity with id 1
You call find(1) => get (the reference to) the same instance loaded in memory previously instead of select the DB again.

**Comment by sushantdhiman** [comment]
What if id: 1 is deleted or updated between these two requests ? If we load from memory we will end up having stale data
