### ISSUE TITLE
Don't log entire values for large blobs in queries by default

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#8346]
Whenever I create create a model with a fairly large blob as one of its attributes, Sequelize logs the entire blob of data (in hex) in the query printed to the console.  This sometimes seems to cause my OS X terminal to freeze for awhile, at least when I try to search in it.

It think it would be better by default if Sequelize truncates the data in the query printed to the console.

**Comment by jedwards1211** [comment]
This is still an issue AFAIK

**Comment by sushantdhiman** [comment]
With v5 all INSERT operations are using bind parameters, so this issue is no longer valid
