### ISSUE TITLE
X is not associated to Y

### ISSUE THREAD

**Issue by yooouuri** [sequelize/sequelize#8349]
I know this is nog a bug, StackOverflow and Slack didn't helped me :(

## What are you doing?
Associating two models

```js
// task model
'use strict';

module.exports = (sequelize, DataTypes) => {
  const Task = sequelize.define('Task', {
    name: DataTypes.STRING
  });

  Task.associations = function (models) {
    Task.belongsTo(models.User, {
      as: 'owner'
    });
  };

  return Task;
};

// user model
'use strict';

module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    first_name: DataTypes.STRING,
    last_name: DataTypes.STRING,
    email: DataTypes.STRING
  }, {
    underscored: true
  });

  User.associations = function (models) {
    User.hasMany(models.Task, {
      as: 'tasks'
    });
  };

  return User;
};

// users route
const models = require('./../models');
const express = require('express');
const router = express.Router();

router.get('', function (req, res) {
  models.User.findAll({
    include: [
      {
        model: models.Task,
        as: 'tasks'
      }
    ]
  }).then(function (users) {
    res.send(users);
  });
});

module.exports = router;
```

## What do you expect to happen?
An array with task objects.

## What is actually happening?
The following error occur: `Unhandled rejection SequelizeEagerLoadingError: Task is not associated to User!`

__Dialect:__ mysql
__Dialect version:__ mysql  Ver 14.14 Distrib 5.7.19, for osx10.13 (x86_64) using  EditLine wrapper
__Database version:__ XXX
__Sequelize version:__ 4.8.4
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by maxim-usikov** [comment]
@yooouuri 

u should walkthrough this steps:
1. Import models
2. Call class "associate" method if exists (in your example is "associations" method)
3. Export
 
Example for your code:
```js
// models/index.js
import fs from 'fs';
import path from 'path';
import Sequelize from 'sequelize';
import config from './config';

const sequelize = new Sequelize(config.db.url, config.db.options);

const DB = {};

// Import models
fs
  .readdirSync(__dirname)
  .filter(file => (file.indexOf('.') !== 0) && (file !== path.basename(__filename)) && (file.slice(-3) === '.js'))
  .forEach((file) => {
    const model = sequelize.import(path.join(__dirname, file));
    DB[model.name] = model;
  });

// Here u should call class method for associations
Object.keys(DB).forEach((modelName) => {
  if ('associations' in DB[modelName]) {
    DB[modelName].associations(DB);
  }
});

DB.sequelize = sequelize;
DB.Sequelize = Sequelize;

export default DB;
```

**Comment by kannan007** [comment]
Have you solved this issue?

**Comment by klaaz0r** [comment]
@maxim-usikov when I use `associations` the model loading does not work, however when I user `associate` it does work and loads the relationships.

**Comment by Ronal0007** [comment]
same error in here ... any details? so far? but when i use include : [{all:true}] works
