### ISSUE TITLE
Inconsistency between docs and implementation of `omitNull`

### ISSUE THREAD

**Issue by acroca** [sequelize/sequelize#835]
The `omitNull` documentation says:

```
  // disable inserting undefined values as NULL
  // - default: false
  omitNull: true,
```

Regardless it's name, I was expecting it to ignore undefined values, but it also ignores defined values to `null`.

The problem is that it's not possible to update a value to `null` once that field have value.
To solve this I'm just discarding `undefined` values and allowing `null`.

Any thoughts?

**Comment by bblack** [comment]
is there a way to accomplish this yet? (that is, not omitting nulls, but omitting unpassed/undefined values on a `create()` call)

**Comment by mickhansen** [comment]
@bblack undefined values should be omitted by default these days, if not it's likely a bug.
