### ISSUE TITLE
Documentation missunderstanding in model definition

### ISSUE THREAD

**Issue by didac-wh** [sequelize/sequelize#8353]
## What are you doing?

Go to http://docs.sequelizejs.com/manual/tutorial/models-definition.html
Do Ctrl + F, look for "model:" (note the double colon).
The displayed value (Bar) should actually be a table name. not an object. Please, replace Bar with 'bar' or something like this, and explain it in the comment above the line.

**Comment by sushantdhiman** [comment]
It can be a model as well
