### ISSUE TITLE
Recent change to remove sort order from outer query broke sorting

### ISSUE THREAD

**Issue by slickmb** [sequelize/sequelize#8359]
## What are you doing?

```js
MyModel.findAll({
  "include": [
    {
      "as": "include_alias",
      "attributes": [
        "id"
      ],
      "model": <my_sub_model>
    }
  ],
  "limit": 50,
  "offset": 0,
  "order": [
    [
      "id",
      "ASC"
    ]
  ],
  "distinct": true
}).then(results => {
   console.log(_(results).pluck('id')); // want results to be in order by id, but they are not anymore!
});
```

## What do you expect to happen?
I wanted my results in order by id.

## What is actually happening?

Results were in random order because the outer query sort was removed and postgres does NOT guarantee order when operating on nested queries.  Outer query sort is required on both the inner query (for pagination to work) and the outer query (for the selected elements to remain sorted).

https://github.com/sequelize/sequelize/commit/a8310bf#diff-def52474024b12c7d133bb504cdf57d1R1684

_Output, either JSON or SQL_
```sql
SELECT
  "my_model".*,
  "include_alias"."id" 
FROM (SELECT
        "my_model"."id",
        "my_model"."other_columns"
      FROM "my_model" AS "my_model"
      ORDER BY "my_model"."id" ASC
      LIMIT 50
      OFFSET 0) AS "my_model" LEFT OUTER JOIN "my_sub_model" AS "include_alias"
    ON "my_model"."id" = "include_alias"."my_model_id";
```

__Dialect:__ postgres 
__Database version:__ 9.6.3
__Sequelize version:__ 4.10.0

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Reverted https://github.com/sequelize/sequelize/commit/79485c3c59a62d43db70e1bad0765e2a7c7d0d50

Will be released soon

**Comment by carlosscheffer** [comment]
I believe I have the same problem in v4.16.1 and v19.0
