### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by 07amir86** [sequelize/sequelize#8361]
## What are you doing?

```js

 "dialect": "postgres",
  "database": "database1",
  "schema": "_schema1",
  "freezeTableName": true,
  "timestamps": true,
  "logging": false,
  "underscored": true,

client model 

module.exports = (sequelize, DataTypes) => {
   const model = sequelize.define(options.tableName, {
      client_id: {
         type: DataTypes.UUID,
         primaryKey: true,
         allowNull: false,
          defaultValue: DataTypes.UUIDV4
      },
      client_name: {
         type: DataTypes.STRING,
         allowNull: false,
          unique: 'composite_client'
      },
       group_id: {
           type: DataTypes.INTEGER,
           allowNull: false,
           unique: 'composite_client'
       },
   }, options);

   model.associate = (models) => {
       model.hasMany(models.user_client, {foreignKey : 'client_id'})
   };

   return model;
};

user :
module.exports = (sequelize, DataTypes) => {
   const model = sequelize.define(options.tableName, {
      user_id: {
         type: DataTypes.UUID,
          primaryKey: true,
          allowNull: false,
          defaultValue: DataTypes.UUIDV4
      },
       user_type: {
           type: DataTypes.STRING,
           allowNull: false
       },
      user_name: {
         type: DataTypes.STRING,
         allowNull: false,
          unique : true
      }
   }, options);

role :
module.exports = (sequelize, DataTypes) => {
   const model = sequelize.define(options.tableName, {
      role_id: {
         type: DataTypes.UUID,
         primaryKey: true,
         allowNull: false,
          defaultValue: DataTypes.UUIDV4
      },
      role_name: {
         type: DataTypes.STRING,
         allowNull: false,
          unique: true
      }
   }, options);

```
user_client 
module.exports = (sequelize, DataTypes) => {
    const model = sequelize.define(options.tableName, {
        id: {
            type: DataTypes.UUID,
            primaryKey: true,
            allowNull: false,
            defaultValue: DataTypes.UUIDV4
        },
        user_id: {
            type: DataTypes.UUID,
            allowNull: false,
            unique: 'composite_user_client'
        },
        client_id: {
            type: DataTypes.UUID,
            allowNull: false,
            unique: 'composite_user_client'
        },
        role_id: {
            type: DataTypes.UUID,
            allowNull: false,
            unique: 'composite_user_client'
        }
    }, options);

    model.associate = (models) => {
        model.belongsTo(models.user, {foreignKey : 'user_id'});
        model.belongsTo(models.client, {foreignKey : 'client_id'});
        model.belongsTo(models.role, {foreignKey : 'role_id'});
    };

    return model;
};

post method issues 
 // use one transaction to create all components
        return req.models.sequelize.transaction(t => {
            // const transaction = {transaction: t};
            let user_client_body = {};
            //return req.models.user.findOrCreate({where: {user_name: req.body.user_name, user_type: req.body.user_type}, transaction: t})

            return req.models.user.findOrCreate({where: {user_name: req.body.user_name}, defaults : { user_type: req.body.user_type}, transaction: t})
                .then(
                    user_result => {
                        user_client_body.user_id = user_result[0].user_id;
                        return req.models.client.findOrCreate({where: {client_name: req.body.client_name}, defaults : { group_id: req.body.group_id}, transaction: t})
                    },
                    error =>{
                        log.error("controllers.user_client", "user_results", error);
                        throw error;
                    }
                ).then(
                    client_result => {
                        user_client_body.client_id = client_result[0].client_id;
                        return req.models.role.findOrCreate({where: {role_name: req.body.role_name}, transaction: t})
                    },
                    error =>{
                        log.error("controllers.user_client", "client_results", error);
                        throw error;
                    }
                )

## What do you expect to happen?
No failure 

## What is actually happening?
error: 2017-09-23|11:34:23.238|controllers.user_client|client_results|ERROR|TypeError: Cannot read property 'toString' of undefined
error: 2017-09-23|11:34:23.238||controllers.user_client|role_results|ERROR|TypeError: Cannot read property 'toString' of undefined

_Output, either JSON or SQL_

__Dialect: postgres 
__Dialect version: pg@6.4.2 / pg-hstore@2.3.2
__Database version: postgres:latest
__Sequelize version: 4.10.2
__Tested with master branch: Yes

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Please try to cleanup this issue. If you expected help from others try to present your problem in clean way, dont just copy paste in haphazard way.

As far as I can grasp, do you think there is a chance `options.tableName` is undefined? As I dont see options defined.

**Comment by Taylor123** [comment]
Has there been any update on this? I seem to be running into the same error message, but it does not specify where exactly it's coming from

**Comment by sushantdhiman** [comment]
@elmeister Can you share some code that reproduce this issue, so it can be fixed with tests

**Comment by elmeister** [comment]
Well, we monkeypatched it in our version. Though apparently it should be easy to fix.

**Comment by epicbagel** [comment]
@07amir86 @Taylor123 @elmeister try removing the following line, it should then resolve the issue. `this.this.fieldRawAttributesMap` returns a map, with the field as an underscore rather than the casing used in your model definition. 

So, it doesn't find a match on the property and fails when trying to call `.toString()`

```
"underscored": true,
```

**Comment by JohnAdamsy** [comment]
For now using `findCreateFind` instead of `findOrCreate` helps avert this issue. 

_Dialect_: **postgres**
_Dialect version_: **pg@7.7.1 / pg-hstore@2.3.2**
_Database version_: **postgres:9.6.1**
_Sequelize version_: **4.42.1**

**Comment by zeeshan1212** [comment]
I am facing the same issue :
const model = await Model.update(data, { where: { id:1 } });
Error: TypeError: Cannot read property 'toString' of undefined

**Comment by luix013** [comment]
I got the same error, but I found that it was the id column.

this is my column

id: {
        type: Sequelize.INTERGER,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
      }

someone know this issue ?

**Comment by xsvato01** [comment]
Also make sure you got **all** the columns which you assing to FindOrCreate function in the where clause to be set as indexes in the model! Especially if you are using more columns in the "where" condition.
