### ISSUE TITLE
1:M relationship: Query where association.column = value

### ISSUE THREAD

**Issue by oliv23** [sequelize/sequelize#8364]
Hi,

I have two models: **Product** and **Pin**. 
The Pin model has one property:
```
var Pin = sequelize.define("pin", {
	account_name: {type: Sequelize.STRING, allowNull: false}
});
```

And I've set a 1 to many relationship like so:
`Product.hasMany(Pin, {as: 'pins'});`

### What I'm trying to do

Now, I'm trying to query for Products where the associated Pins (if any exist) do not contain a pin with the `account_name` property equal to a specific value (let's say "hello").

### What I'm expecting

In other words, if I run the query, I am expecting to get all Products **without** any associated Pins AND all Products where existing associated Pins' `account_name` property do not match the defined value (we are using "hello")

### What I tried

```
models.Product.findAll({
	where: {
		is_published: true
	},
	include: [
		{
			model: models.Pin,
			as: 'pins',
			where: {
				account_name: {$not: 'hello'}
			}
		},
        ]
});
```

Now this solution does not return a product if it does not have any associated pins or if the only pin associated has the unwanted value (which is good). **But** if it does have additional Pins with other `account_name` values, then it will return the Product, and those other Pins **even though one of the Pins contains the unwanted value**! That's not what I want.

So it seems I need to move the `where: { account_name: {$not: 'hello'} }` condition up one level, at the Product level, for this to work. I'm guessing something like
```
where: {
	is_published: true,
        'pins.pin.account_name': {$not: 'hello'}
}
```
But so far I've been googling and trying all sorts of weird things and nothing has worked.

Could anyone please advise? Answers much appreciated!
Thank you!

**Comment by sushantdhiman** [comment]
Next time please follow issue template, I dont know which version you re working with.

Have you tried passing `required: false` in include ?
