### ISSUE TITLE
Atomic upsert with PostgreSQL and JSONB fields?

### ISSUE THREAD

**Issue by PabloMessina** [sequelize/sequelize#8366]
I'm just wondering if it's possible to do an atomic upsert (PostgreSQL INSERT ON CONFLICT UPDATE) using Sequelize ORM when a given field type is JSONB? As a workaround I tried using sequelize.query('INSERT INTO table (col1, col2, col3) VALUES (?,?,?) ON CONFLICT (col1, col2) DO UPDATE SET col3 = ?', { replacements: [id1, id2, val, val], type: sequelize.QueryTypes.SELECT }) where val is the object I want to save in the JSONB column col3, but this throws a parsing error. Do I need to use JSON.stringify(val) instead? Besides, is there a ORM way of accomplishing the same without using raw string queries? I know you could simulate an upsert by first checking whether the row exists and then create or update depending on the result, but that would not be a single atomic operation.

**Comment by adavia** [comment]
No updates on this?

**Comment by PabloMessina** [comment]
No updates it seems

**Comment by sushantdhiman** [comment]
Duplicate of #4324

You should be able to do atomic upsert operation using `Model.upsert` which doesn't use `ON CONFLICT` but rather use PL/SQL function and error handling to perform this.

https://github.com/sequelize/sequelize/issues/4324 is tracking `ON CONFLICT` support

**Comment by rmnboiko** [comment]
My solution for this just stringify your JSONB object befor inserting.
