### ISSUE TITLE
Error is thrown on migration changing Column type to JSON

### ISSUE THREAD

**Issue by colideum** [sequelize/sequelize#8370]
## What are you doing?

`
	up: function (queryInterface, Sequelize) {
		return queryInterface
			.changeColumn('users', 'merchant_id', Sequelize.JSONB)
	}
`

## What do you expect to happen?
_I want to change column type from string to jsonb_

## What is actually happening?
_error was thrown: SequelizeDatabaseError: column "affiliate_id" cannot be cast automatically to type jsonb_

{ error: column "affiliate_id" cannot be cast automatically to type jsonb
       at Connection.parseE (/home/user/app/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/home/user/app/node_modules/pg/lib/connection.js:391:17)
       at Socket.<anonymous> (/home/user/app/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:548:20)
     name: 'error',
     length: 183,
     severity: 'ERROR',
     code: '42804',
     detail: undefined,
     hint: 'You might need to specify "USING affiliate_id::jsonb".',
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'tablecmds.c',
     line: '7923',
     routine: 'ATPrepAlterColumnType',
     sql: 'ALTER TABLE "users" ALTER COLUMN "affiliate_id" DROP NOT NULL;ALTER TABLE "users" ALTER COLUMN "affiliate_id" DROP DEFAULT;ALTER TABLE "users" ALTER COLUMN "affiliate_id" TYPE JSONB;' }

It seems that on changing column type it is additionally needed to put "USING fieldName::jsonb" to the end

__Dialect:__ postgres
__Database version:__ 9.5.4
__Sequelize version:__ 3.30.4

**Comment by sushantdhiman** [comment]
Version v3.30.4 is no longer supported, apart from critical security fixes there wont be any development on that version.

Additionally I dont know why you are trying to cast INTEGER column to JSON but that wont work
