### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'replace' of undefined when running migration on Heroku

### ISSUE THREAD

**Issue by hhimanshu** [sequelize/sequelize#8374]
## What are you doing?
I have a Heroku Application which is hooked up with PostgreSQL. My app works fine (and migration succeeds) on local PostgreSQL (via Docker container).  

**db/config.js**
```js
module.exports = {

    development: {
        username: 'postgres',
        password: 'contactdb',
        database: 'contacts',
        host: '127.0.0.1',
        dialect: 'postgres',
        seederStorage: "sequelize",
        seederStorageTableName: "SequelizeData"
    },
    production: {
        use_env_variable: "DATABASE_URL",
        seederStorage: "sequelize",
        seederStorageTableName: "SequelizeData"
    }
};
```

On Heroku, I have following variables set
```bash
➜  contactz git:(master) heroku config --app contactzz
=== contactzz Config Vars
DATABASE_URL: postgres://tvbxrkbviqsdfdzp:091e9910345643ff9f678fc4fc5e7df90587ce93bfabf25f4a5792b83196817aa@ec2-54-163-230-219.compute-1.amazonaws.com:5432/d3b4cibkapn4aa
NODE_ENV:     production
```  

I run the migration as  
```bash
➜  contactz git:(master) heroku run sequelize db:create --app contactzz
Running sequelize db:create on ⬢ contactzz... up, run.5645 (Free)

Sequelize CLI [Node: 6.9.5, CLI: 3.0.0, ORM: 4.10.3]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "db/config.js".
Using environment "production".
Unhandled rejection TypeError: Cannot read property 'replace' of undefined
    at Object.removeTicks (/app/node_modules/sequelize/lib/utils.js:416:11)
    at Object.quoteIdentifier (/app/node_modules/sequelize/lib/dialects/postgres/query-generator.js:848:35)
    at QueryInterface.quoteIdentifier (/app/node_modules/sequelize/lib/query-interface.js:1162:32)
    at Object.<anonymous> (/app/node_modules/sequelize-cli/lib/commands/database.js:38:80)
    at next (native)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/app/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```
## What do you expect to happen?
The migration should have worked out to be fine

## What is actually happening?
The migration failed. Please see the stacktrace above  

The codebase is available at https://github.com/hhimanshu/contactz

Thank you

**Comment by hhimanshu** [comment]
Any help on this please?

**Comment by andre991** [comment]
+1

**Comment by hhimanshu** [comment]
Folks, I continued to work on this and realized that we do not need to create the database on Heroku, Heroku creates one for us. That means we do **not** need to run 
```
heroku run sequelize db:create --app contactzz
```
We can directly run the following  
```
heroku run sequelize db:migrate --app contactzz
heroku run sequelize db:seed:all --app contactzz
```

For complete running example on Heroku, please see my repository @ https://github.com/hhimanshu/contactz

Hope that helps solve the issue. Thanks!

**Comment by UniWrighte** [comment]
I'm getting the same error on the first model of my initial migration.

**Comment by rvbonfimm** [comment]
@mittalyashu and @UniWrighte , I had the same issue in my project. To resolve the problem, I did the steps showed below:

     I was creating four models for my project:
      - Person;
      - Ticket;
      - SocialNetwork;
      - Secretary;

     The Person and Ticket model "depends" of SocialNetwork and Secretary - hasone/hasmany dependencies. 

But, I created the People and Ticket models first of the others. Because of It I was facing the problem. The sequelize db:migrate command execute the migrations based on the filename date.

Changing the Person and Ticket migration filename, I was able to execute the migrations on the right order.

Another problema that I was facing, I was inserting a Model Object into the Reference keyword (inside of the migration file). But, the sequelize expects the tablename:

    `references: {
            model: 'social_networks', // Name of the created table
            key: 'id',
            onUpdate: 'CASCADE',
            onDelete: 'CASCADE'
    }`

**Comment by brendoLoR** [comment]
@rvbonfimm thanks man!!!
