### ISSUE TITLE
belongsToMany.add returns nested array of array

### ISSUE THREAD

**Issue by neves** [sequelize/sequelize#8377]
# Sequelize Version 4.11.0 through 4.11.7 and master branch
## Look for console.log(userProject)

```js
const Sequelize = require('sequelize')

var sequelize = new Sequelize('lab', 'root', 'root', {
  host: '127.0.0.1',
  dialect: 'mysql',
  define: {
    timestamps: false,
    constraints: false
  }
})

const User = sequelize.define('User')
const Project = sequelize.define('Project')
const UserProject = sequelize.define('UserProject')
const Task = sequelize.define('Task')
User.belongsToMany(Project, {through: 'UserProject'})
Project.hasMany(Task)
exec()

async function exec () {
  await sequelize.sync({force: true})

  var user = await User.create()
  var project = await Project.create()
  var userProject = await user.addProject(project)
  console.log(userProject) // wrongly returns a array of array, instead of just UserProject
  // [ [ UserProject {
  //   dataValues: [Object],
  //   _previousDataValues: [Object],
  //   _changed: [Object],
  //   _modelOptions: [Object],
  //   _options: [Object],
  //   __eagerlyLoadedAssociations: [],
  //   isNewRecord: false } ] ]
  
  userProject = await user.createProject() // correctly returns a project
  console.log(userProject.toJSON()) // { id: 2 }

  var task = await project.createTask()
  console.log(task.toJSON()) // { id: 1, ProjectId: 1 }

  return sequelize.close()
}

```

## What do you expect to happen?
The output from `console.log(userProject)` should be
```js
UserProject {
    dataValues: [Object],
    _previousDataValues: [Object],
    _changed: [Object],
    _modelOptions: [Object],
    _options: [Object],
    __eagerlyLoadedAssociations: [],
    isNewRecord: false }
```

## What is actually happening?
But the output is a array of array of UserProject:
```js
[ [ UserProject {
    dataValues: [Object],
    _previousDataValues: [Object],
    _changed: [Object],
    _modelOptions: [Object],
    _options: [Object],
    __eagerlyLoadedAssociations: [],
    isNewRecord: false } ] ]
```

If this behaviour is intentional, I would like to know why, since `user.createProject` or `project.createTask` works as expected.

**Comment by sushantdhiman** [comment]
I dont know what Sequelize version you are using. Please follow issue template properly.

**Comment by neves** [comment]
@sushantdhiman It's version 4.11.0

**Comment by sushantdhiman** [comment]
@neves This is how API is designed, add expects single / multiple instances to add. To keep API consistent for both cases we return an array

**Comment by neves** [comment]
@sushantdhiman, there's no difference between addProject and addProjects?
So, if I need to get the created project, I should do:
```js
var userProjects = await user.addProject(project)
var userProject = userProjects[0][0]
```
Is this by design?

**Comment by sushantdhiman** [comment]
It should have returned an array of instances, rather than array of array of instances. Are you 100% sure its not an array of instances?

**Comment by neves** [comment]
Reproducible code
```js
// https://github.com/sequelize/sequelize/issues/8377
// yarn add sequelize sqlite3
const Sequelize = require('sequelize')

var sequelize = new Sequelize('sqlite://:memory:', {
  define: {
    timestamps: false,
    constraints: false
  }
})

const User = sequelize.define('User')
const Project = sequelize.define('Project')
const UserProject = sequelize.define('UserProject')
const Task = sequelize.define('Task')
User.belongsToMany(Project, {through: 'UserProject'})
Project.hasMany(Task)
exec()

async function exec () {
  await sequelize.sync({force: true})

  var user = await User.create()
  var project = await Project.create()
  var userProject = await user.addProject(project)
  console.log(userProject) // wrongly returns a array of array, instead of just UserProject
  // [ [ UserProject {
  //   dataValues: [Object],
  //   _previousDataValues: [Object],
  //   _changed: [Object],
  //   _modelOptions: [Object],
  //   _options: [Object],
  //   __eagerlyLoadedAssociations: [],
  //   isNewRecord: false } ] ]

  userProject = await user.createProject() // correctly returns a project
  console.log(userProject.toJSON()) // { id: 2 }

  var task = await project.createTask() // correctly returns a task
  console.log(task.toJSON()) // { id: 1, ProjectId: 1 }

  return sequelize.close()
}
```

**Comment by neves** [comment]
Does this behaviour is intentional?

**Comment by sushantdhiman** [comment]
Just tested this, I confirm this odd behaviour

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/pull/9700

**Comment by antonioidalecio** [comment]
> Reproducible code
> 
> ```js
> // https://github.com/sequelize/sequelize/issues/8377
> // yarn add sequelize sqlite3
> const Sequelize = require('sequelize')
> 
> var sequelize = new Sequelize('sqlite://:memory:', {
>   define: {
>     timestamps: false,
>     constraints: false
>   }
> })
> 
> const User = sequelize.define('User')
> const Project = sequelize.define('Project')
> const UserProject = sequelize.define('UserProject')
> const Task = sequelize.define('Task')
> User.belongsToMany(Project, {through: 'UserProject'})
> Project.hasMany(Task)
> exec()
> 
> async function exec () {
>   await sequelize.sync({force: true})
> 
>   var user = await User.create()
>   var project = await Project.create()
>   var userProject = await user.addProject(project)
>   console.log(userProject) // wrongly returns a array of array, instead of just UserProject
>   // [ [ UserProject {
>   //   dataValues: [Object],
>   //   _previousDataValues: [Object],
>   //   _changed: [Object],
>   //   _modelOptions: [Object],
>   //   _options: [Object],
>   //   __eagerlyLoadedAssociations: [],
>   //   isNewRecord: false } ] ]
> 
>   userProject = await user.createProject() // correctly returns a project
>   console.log(userProject.toJSON()) // { id: 2 }
> 
>   var task = await project.createTask() // correctly returns a task
>   console.log(task.toJSON()) // { id: 1, ProjectId: 1 }
> 
>   return sequelize.close()
> }
> ```

I'm currently facing this issue! I'm using sequelize version "^4.42.0"
