### ISSUE TITLE
Loop through results and run another query for each result... Best practice?

### ISSUE THREAD

**Issue by joshparolin** [sequelize/sequelize#838]
Hey all. I'm having trouble looping through a results set and then running another query for each result in order to attach some additional data. 

Below is my code. "Pages" is a result from a Sequelize query. For each page, I'm trying to attach it's respective mentions. What's the best practice here?

Oddly, the below code actually renders the association to my view on localhost. But when pushed to Heroku, it does not.

``` javascript

// pages == an object    
    // for each page, get mentions
   for(var k in pages) {
      // build query
     var query = 'SELECT m.url, b.name, b.icon_path FROM "Page_has_Mentions" h ';
         query +='join "Mentions" m on m.id = h.mention_id ';
         query +='join "Blogs" b on b.id = m.blog_id ';
         query +='where h.page_id = \'' + pages[k].id + '\'';
      // get and attach mentions
     global.db.sequelize.query(query)
     .success(function(mentions) {
       pages[k].mentions = mentions;
     });
    }

```

**Comment by mota57** [comment]
Nice thanks mick and jagge
