### ISSUE TITLE
Inserting / Updating belongsToMany Association with additional attributes

### ISSUE THREAD

**Issue by heckenpenner** [sequelize/sequelize#8381]
## 

```js
User = sequelize.define('user', {....})

User.belongsToMany(theDB.mail, {
  through: {
    model: 'user_mails',
  },
})

Mail = sequelize.define('mail', {....})

Mail.belongsToMany(theDB.offerer, {
  through: {
    model: 'user_mails',
  },
})

I created the Association with additional attributes

UsersMails = sequelize.define('user_mails', {
id: {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    sendDate: {
      type: DataTypes.DATE,
      allowNull: true
    },
    posted: {
      type: DataTypes.BOOLEAN,
      defaultValue: true
    },
    hasError: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },
    skipped: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },
    messageId: {
      type: DataTypes.STRING,
      defaultValue: 'So is it before'
    },
    count: {
      type: DataTypes.INTEGER
    }
},
{
tableName: 'user_mails',
})
```
This are my two tables with one Association (belongsToMany).
The user_mails table has five additional attributes (columns)
Parts of the Association table has default values for test purposes.
In the sequelize doc's it is described so:
```js
user.addProject(project, { through: { status: 'started' }})
```
**I try this:**
```js
mail.addUser(user, {
  through: {
    // fields: ['skipped', 'messageId'], // works also with this Array
    skipped: true,
    messageId: 'new message id'
} }
```
Creating an new entry inserts only the default values
Omitting the fields Array changes nothing
```js
INSERT INTO `user_mails` (`id`,`posted`,`hasError`,`skipped`,`messageId`,`createdAt`,`updatedAt`,`mailId`,`userId`) VALUES (NULL,true,false,false,'So is it before','2017-09-27 20:15:20','2017-09-27 20:15:20',9,3);
```
Changing an existing enty only update the updateAt field:
```js
UPDATE `user_mails` SET `updatedAt`='2017-09-27 20:17:09' WHERE `mailId` = 9 AND `userId` = 3
```
**Then I try this:**
```js
mail.addUser(user, {
    skipped: true,
    messageId: 'new message id'
})
```
All works fine by a new Association:
```js
INSERT INTO `user_mails` (`id`,`posted`,`hasError`,`skipped`,`messageId`,`createdAt`,`updatedAt`,`mailId`,`userId`) VALUES (NULL,true,false,true,'new message id','2017-09-27 20:30:57','2017-09-27 20:30:57',9,3);
```
Also by an update:
```js
UPDATE `user_mails` SET `skipped`=true,`messageId`='new message id',`updatedAt`='2017-09-27 20:34:49' WHERE `mailId` = 9 AND `userId` = 3
```
## What do you expect to happen?
* is there a new documentation of which I know nothing
* I think(hope) my model configurations are not the reason
* are there some side effect of which I know nothing

## What is actually happening?
If I give the options direct to the addUser all work's fine, but why there are the problem when I use it with the **through** parameter

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ mysql
__Database version:__ 5.7.18
__Sequelize version:__ 4.0.0-2
__Tested with master branch:__ No

**Comment by sushantdhiman** [comment]
Sequelize docs clearly states breaking changes for **v4** http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html , not its pre-releases.

You are trying to use v4 features in pre-release v4.0.0-2, what do you expected :)

**Comment by heckenpenner** [comment]
Better to read the docs ;-)
But ?
Was it one of the last change before 4.0.0 (final)
