### ISSUE TITLE
Model.create() not closing connection. Process hangs

### ISSUE THREAD

**Issue by JamesTheHacker** [sequelize/sequelize#8388]
## What are you doing?

```js
createFactoid(title)
  .then((data) => {
    // Do some stuff

    // Store in database
    return factoid.create({
      title: titleize(title),
      slug: slugify(title),
      facts: sentences.join(' '),
      moderated: false,
    });
  })
  .then(() => console.log('All Done :)'))
  .catch(err => console.error(err));
```

## What do you expect to happen?

I expect `factoid.create()` to close the connection so the node process can exit. `console.log('All Done :)')` should be called after the data has been created in the database.

## What is actually happening?

The data is created in the table, but the node process hangs. I've left it running for 10 minutes and the process is still hanging in the terminal. As a result, the code within the last `then` chain does not get called.

__Dialect:__ mysql
__Database version:__ mysql  Ver 14.14 Distrib 5.7.19, for osx10.10 (x86_64) using  EditLine wrapper
__Sequelize version:__ 4.11.1
__Tested with master branch:__ Yes

**Comment by JamesTheHacker** [comment]
Closing. This wasn't an issue with the library. Fixed like so:

```js
  .then(() => console.log('All Done :)'))
  .catch(err => console.error(err))
  .then(() => process.exit());
```

**Comment by Rukeith** [comment]
@JamesTheHacker I also have this issue. But I can't fix by your solution, I even can't go to `process.exit`

**Comment by sylv3r** [comment]
Same problem here while doing tests with Mocha.
`process.exit()` is definitely not a solution !
Anyone has an idea why and how to fix this ?

**Comment by rsshilli** [comment]
You have the same problem as https://github.com/sequelize/sequelize/issues/8468

**Comment by Cardoso222** [comment]
@sylv3r your solution works for me. Thanks!

**Comment by spearmootz** [comment]
i tried this but its not working :(

**Comment by maruware** [comment]
I had the problem with mocha, too.
And I wrote the following code. Then, it worked with a single test file, but did not work with multi test files.

```js
after(() => { sequelize.close() })
```

After that, I found the folloing issue.
https://github.com/mochajs/mocha/issues/3044

I solved the problem by attaching an option ```--exit```.

e.g.
```
npx mocha --exit test/**/*.js
```
