### ISSUE TITLE
Defining Sequelize class methods results in Typescript errors

### ISSUE THREAD

**Issue by stringbeans** [sequelize/sequelize#8392]
## What are you doing?

I'm trying to add class methods onto the model in Sequelize V4. 

```js
import * as Sequelize from 'sequelize'

const AccessToken = (sequelize: Sequelize.Sequelize, DataTypes) => {
  const AccessToken = sequelize.define('AccessToken', {
    id: {
      field: 'id',
      type: DataTypes.STRING,
      primaryKey: true
    },
    ttl: {
      type: DataTypes.INTEGER,
      field: 'ttl'
    },
    created: {
      type: DataTypes.DATE,
      field: 'created',
      defaultValue: DataTypes.NOW
    },
    userId: {
      type: DataTypes.INTEGER,
      field: 'userId'
    }
  }, {
    timestamps: false,
    freezeTableName: true
  })

  AccessToken.loadRelations = (models) => {
    models.AccessToken.belongsTo(models.User, {
      as: 'user',
      foreignKey: 'userId'
    })
  }
  return AccessToken
}

export default AccessToken
```

## What do you expect to happen?

I'd like to not see any typescript errors on the line where I define the `loadRelations` class method. There does not seem to be a way to specify what you want additional class methods to be in the typescript generics accepted by `sequelize.define`. I can confirm I am using the latest `@types/sequelize` at version 4.0.75

## What is actually happening?

I'm getting a Typescript error on the line where I define the `loadRelations` class method. `Property 'loadRelations' does not exist on type 'Model<{}, {}>'.`

__Sequelize version:__ 4.11.1
__Tested with master branch:__ No

I was only able to work around this by CASTING `sequelize.define` to return `as Sequelize.Model<{}, {}> & {loadRelations: Function}`

**Comment by eseliger** [comment]
Try types/sequelize, I guess it's better maintained 🙈

**Comment by stringbeans** [comment]
@eseliger ive switched the types and am now using `types/sequelize` and i can see the typing is slightly different... however with the above example im still getting the TS error. any tips on how to handle the error now that im using the up-to-date `types/sequelize` ?

**Comment by eseliger** [comment]
Ah now I'm getting your problem. `loadRelations` is not a member of model. But you could use the class syntax and extend Model to add your method, which is recommended for ts. But this is a general question and it would be great if you could try to solve your problem on stackoverflow first, so the issue tracker keeps clean :) 
Also, this is not really a problem related to sequelize itself, because sequelize is just javascript

**Comment by stringbeans** [comment]
@eseliger thanks!! you're right this probably does belong on stackoverflow. i think initially i thought there was a generic type or something missing from `@types/sequelize` 😖 

you mention using the class syntax and extending Model. could you point me towards some documentation or examples around this? Thanks in advance :) :)

**Comment by eseliger** [comment]
https://github.com/types/sequelize#usage

which also works well for me:
https://www.npmjs.com/package/sequelize-decorators (which basically eliminates the init call)

**Comment by basimhennawi** [comment]
@stringbeans Did you solve your problem? If yes, how?

**Comment by stringbeans** [comment]
@basimhennawi in my original post i explain at the end that as a workaround i cast the type returned by the `.define`... 

so it ends up looking something like this...

```
sequelize.define('StudentQuote', {...}) as Sequelize.Model<{}, {}> & {<your additional methods typing here>}
```
