### ISSUE TITLE
Add getter after all models are loaded

### ISSUE THREAD

**Issue by yss14** [sequelize/sequelize#8402]
Is it possible to add getter and setter methods to my models after all are loaded?
At the moment I am using the `associate` function to add my scopes via `addScope` and also trying to add custom getter and setter.

```
Song.associate = (models) => {
        //Associations...

        Song.addScope('defaultScope', {
            //Some inclues, they actually work
        }, { override: true });

        Song.getterMethods = {
            librarySongs(libID) {
                return this.findAll();
            }
        }
```

`DB.Song.getLibrarySongs(library.id)`throws an error 

```
TypeError: DB.Song.getLibrarySongs is not a function
```

**Comment by sushantdhiman** [comment]
getterMethods / setterMethods support is also removed in v4, you should define getters directly on class https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by yss14** [comment]
So you mean by adding it directly to my class?

```
Library.getLibrarySongs = () => {
        console.log("getter is called")
        return DB.Song.findAll({
            include: [{
                model: DB.Library,
                as: 'library',
                where: { libID: 1 }
            }]
        })
    }
```

Unfortunately, this throws the same error.
