### ISSUE TITLE
Paranoid overrides [Op.or] query

### ISSUE THREAD

**Issue by vladmiller** [sequelize/sequelize#8406]
## What are you doing?
For the login functionality, I am trying to find a user who has username or email equal to X. `User` model has paranoid mode turned on.

```typescript
const userPromise = User.findOne({
      where: {
        [Op.or]: [
          {
            username
          },
          {
            email: username
          },
        ],
      },
    })
```

## What do you expect to happen?
```sql
SELECT `userId`, `username`, `email`, `displayName`, `active`, `password`, `createdAt`, `updatedAt`, `deletedAt` FROM `User` AS `User` WHERE (`User`.`deletedAt` > CURRENT_TIMESTAMP OR `User`.`deletedAt` IS NULL) AND (`User`.`username` = 'vladmiller' OR `User`.`email` = 'vladmiller')  LIMIT 1;
```

## What is actually happening?
But generated SQL query ignored my [Op.or] statement. Seems like `paranoid` mode overrides any `or` statement included in the query.

```sql
SELECT `userId`, `username`, `email`, `displayName`, `active`, `password`, `createdAt`, `updatedAt`, `deletedAt` FROM `User` AS `User` WHERE (`User`.`deletedAt` > CURRENT_TIMESTAMP OR `User`.`deletedAt` IS NULL) LIMIT 1;
```

__Dialect:__ mysql
__Sequelize version:__ 4.13.2
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/commit/e695b92c9235f7c228513edc5fc28463c931083c

Thanks for properly reporting this issue :)
