### ISSUE TITLE
Sqlite Enable Index Where Support

### ISSUE THREAD

**Issue by ameily** [sequelize/sequelize#8407]
## What are you doing?
I'm trying to declare a unique index that contains a `where` clause targeting Sqlite. The idea is that objects with out a category set (`category_id IS NULL`) has a unique `name`:

```js
sequelize.define('something' {
  name: {
    type: Sequelize.STRING
  },
  category_id: {
    type: Sequelize.INTEGER
  }
}, {
  indexes: [{
    name: 'category_root_index',
    fields: ['name'],
    where: {
      category_id: null
    }
  }]
});
```

## What do you expect to happen?

I was expecting to see an index created with:

```sql
CREATE UNIQUE INDEX `category_root_index` ON `something` (`name`) WHERE `category_id` IS NULL;
```

## What is actually happening?
Here's the `CREATE INDEX` statement I'm seeing:

```sql
CREATE UNIQUE INDEX `category_root_index` ON `something` (`name`);
```

It looks like the core issue is that the Sqlite dialect does not support `index.where`. I just edited the Sqlite dialect to set `supports.index.where = true` and verified that this fixed the issue. Sqlite documentation says that partial index support has been around since 3.8.0 (https://sqlite.org/partialindex.html#supported_versions):

> Partial indexes have been supported in SQLite since version 3.8.0 (2013-08-26).

So, would it be safe to just enable `index.where` for the Sqlite dialect in Sequelize?

__Dialect:__ sqlite
__Dialect version:__ 3.8.0
__Database version:__ 3.20.0
__Sequelize version:__ 4.13.2
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Yeah we should enable this flag for SQLite.

You can open a PR with this change. Probably need to find index where tests for other dialects and make sure they are running for SQLite (Ideally they will be checking for index.where as well, but there might be some tests which are just using dialect name)

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/8495
