### ISSUE TITLE
Backticks format

### ISSUE THREAD

**Issue by jandersonld** [sequelize/sequelize#8409]
## Mysql don't understand backticks format

I have a defined model with schema and tableName options configured. 
```js
sequelize.define(modelname, attributes, {
    schema: 'foo',
    tableName: 'table'
})
```

But 
when I executa a query method (ex: findAll) receive SequelizeDatabaseError
with query:

```sql
`schama.table` AS `foo` 
```
and mysql dont found this table.

The format that works is 
```sql
`schema`.`table` AS `foo`
```
How can I solve this?

Thanks.

**Comment by luisAzcuaga** [comment]
Any luck with this?

**Comment by gdroid7** [comment]
Anything on this ? i am trying to query two databases on same instance and i need to have a database name as a prefix.
