### ISSUE TITLE
sync doesn't work anymore and is not related to pg

### ISSUE THREAD

**Issue by renoken** [sequelize/sequelize#8413]
## public.sync() or Model.sync() produces error

Since upgrading to version 4, the sync() function produces an error: 
TypeError: this.model.bulkBuild is not a function

We downgraded our pg also to pg@6, but that doesn't seem to be related.

We have investigated this and we followed the execution path. The issue is that the CREATE TABLE sql statement that is produced in the sync is treated as a type of QueryTypes.SELECT. This results in the error above later in the execution path, because it tries to build the model based on the return, but Postgres doesn't return anything that can be used for this.

We backtracked it to line 511 in lib/sequelize.js:
`      if (!options.type) {
        if (options.model || options.nest || options.plain) {
          options.type = QueryTypes.SELECT;
        } else {
          options.type = QueryTypes.RAW;
        }
      }
`
If I change as a test the line 512 to:
`if ((options.model || options.nest || options.plain) && sql.indexOf('CREATE TABLE') == -1) {`
then it works fine, because then the result will be treated as RAW.

Our models are created like this:
In models/language.js:
`"use strict";
module.exports = function(sequelize, DataTypes) {
	var Language = sequelize.define("Language", {
		LanguageID: {
			type: DataTypes.UUID,
			defaultValue: DataTypes.UUIDV4,
			primaryKey: true
		},
		LCID: { type: DataTypes.STRING, allowNull: false, unique: true },
		Name: { type: DataTypes.STRING, allowNull: false, unique: true }
	}, {
		tableName: 'CMSLanguages'
	});
	return Language;
};`

In models/index.js:
`"use strict";
var fs        = require("fs");
var path      = require("path");
var Sequelize = require("sequelize");
var config    = require('../config');
if (config.sqllog) {
	config.logging = console.log;
} else {
	config.logging = false;
}
var sequelize = new Sequelize(config.database, config.username, config.password, config);
var db        = {};
fs
	.readdirSync(__dirname)
	.filter(function(file) {
		return (file.indexOf(".") !== 0) && (file !== "index.js");
	})
	.forEach(function(file) {
		var model = sequelize.import(path.join(__dirname, file));
		db[model.name] = model;
	});
Object.keys(db).forEach(function(modelName) {
	if ("associate" in db[modelName]) {
		db[modelName].associate(db);
	}
});
db.sequelize = sequelize;
db.Sequelize = Sequelize;
db.LibraryUpdateDate = new Date();
module.exports = db;`

__Dialect:__ postgres
__Dialect version:__ ?
__Database version:__ psql (PostgreSQL) 9.4.12
__Sequelize version:__ 4.13.2
__Tested with master branch:__ No

Thanks for investigating this further!

Kind regards,

Reno

**Comment by sushantdhiman** [comment]
All these tests https://github.com/sequelize/sequelize/blob/master/test/integration/model/sync.test.js , they pass.

If you can submit a test case which fails I will reopen this issue. I am sure this is an userland problem
