### ISSUE TITLE
CHANGELOG is gone

### ISSUE THREAD

**Issue by thieman** [sequelize/sequelize#8418]
There are references in your v4 release notes (and I'd imagine other places) to a CHANGELOG: http://docs.sequelizejs.com/manual/changelog/changelog.html

This CHANGELOG seems to be gone, which is a shame because they are very useful. Would be great to have that back.

**Comment by thieman** [comment]
Extra info: there's a potential dupe of this issue that was closed without explanation: https://github.com/sequelize/sequelize/issues/7808

Not sure if that was intentional so I wanted to resurface the issue

**Comment by thieman** [comment]
Extra extra info: okay, I'm terrible at GitHub. The previous issue was closed as a redirect to the individual release notes.

If that's an official maintainer statement of "we aren't maintaining a changelog any more" then I guess that's the decision. Still wanted to check to make sure that was intentional.

**Comment by eseliger** [comment]
It was intentional, we are using [semantic-release](https://www.npmjs.com/package/semantic-release) now to publish new versions of sequelize, which generates the [changelog](https://github.com/sequelize/sequelize/releases) in the release view of Github automatically from the commit messages.
