### ISSUE TITLE
node_modules/.bin/sequelize db:seed:undo not working

### ISSUE THREAD

**Issue by OscarHYCheung** [sequelize/sequelize#8421]
Hi there, after running `node_modules/.bin/sequelize db:seed:undo`, the data created by the latest seed are still in the DB.

However, `node_modules/.bin/sequelize db:seed:undo:all` is working fine to undo all seeds.

I'm not sure is that related to the warning CLI v3 is not fully compatible to Sequelize v4.

Thanks.

## What are you doing?
I would like to undo the last data seed with
```shell
node_modules/.bin/sequelize db:seed:undo
```

## What do you expect to happen?
The latest seed should be reverted

## What is actually happening?
No data removed, and got the follow output:

```
Sequelize CLI [Node: 6.11.1, CLI: 3.0.0, ORM: 4.13.2]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "config/database.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13
```

__Dialect:__ postgres
__Dialect version:__ `pg: 7.3.0, pg-hstore: 2.3.2`
__Database version:__ `PostgreSQL 9.6.5 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit`
__Sequelize version:__ 4.13.2
__Sequelize CLI version:__ 3.0.0
__Tested with master branch:__ No

**Comment by sushantdhiman** [comment]
Report this issue to CLI repo please

> I would like to undo the last data seed with

`seed:undo` doesn't undo last ran seed, read its description. It undo a specific seed

**Comment by OscarHYCheung** [comment]
@sunshinewyin Thanks for your quick reply. If what you said is true, then there is a problem in the documentation: http://docs.sequelizejs.com/manual/tutorial/migrations.html#undoing-seeds

### Undoing Seeds
Seeders if they are using any storage can be undo. There are two commands available for that

If you wish to undo most recent seed
`node_modules/.bin/sequelize db:seed:undo`

If you wish to undo all seeds
`node_modules/.bin/sequelize db:seed:undo:all`

**Comment by Dbroqua** [comment]
Still not working.

Only `db:seed:undo:all` works.

Regards

**Comment by luisfrocha** [comment]
> Report this issue to CLI repo please
> 
> > I would like to undo the last data seed with
> 
> `seed:undo` doesn't undo last ran seed, read its description. It undo a specific seed

Directly copied from documentation (as of today 2108-12-12): http://docs.sequelizejs.com/manual/tutorial/migrations.html#undoing-seeds

```
If you wish to undo most recent seed

node_modules/.bin/sequelize db:seed:undo
```

**Comment by gabrielsimpsons** [comment]
I've figured it out running 
`NODE_ENV=sandbox sequelize db:seed --seed seeders/seed_file.js` seeders is a folder in the root of my project

**Comment by foodaka** [comment]
I'm running the undo seeds successfully but the data is still persistent in the database. Is this the expected behaviour or?

`npx sequelize-cli db:seed:undo:all`

    "sequelize": "5.21.5",
    "sequelize-cli": "^6.1.0",

**Comment by StphnLwnga** [comment]
Check that you've implemented a **`down`** method in your seeder file  
  ```javascript
  down: async (queryInterface, Sequelize) => {
      await queryInterface.bulkDelete(TABLE_NAME, null, {});
  }
  ```

> I'm running the undo seeds successfully but the data is still persistent in the database. Is this the expected behaviour or?
> 
> `npx sequelize-cli db:seed:undo:all`
> 
> ```
> "sequelize": "5.21.5",
> "sequelize-cli": "^6.1.0",
> ```
