### ISSUE TITLE
[regression] Operator symbols not enumerable in `for .. in` loops!

### ISSUE THREAD

**Issue by louisremi** [sequelize/sequelize#8423]
*EDIT: I initially thought the new *Operator Symbols* introduced in 4.12.0 were only incompatible with `_.isEmpty`. I quickly realized they're incompatible with `for .. in` loops and the implications are far more serious!*

I've found an important regression that occurred when Operator Symbols were introduced in 4.12.0: every time `_.isEmpty` is used against an object that contains only Symbol keyed props, it returns `true` :-(
Indeed, [isEmpty's documentation](https://lodash.com/docs/4.17.4#isEmpty) states that *"Objects are considered empty if they have no own enumerable **string** keyed properties."* (emphasis is mine).

The first important regression I've spotted is when using the paranoid option on a model. The function [`_paranoidClause`](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L52) might override `options.where` because of the incorrect result of [`_.isEmpty(options.where)`](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L86). In my app, where I constantly use this option, many queries were completely messed up.

Other occurrences of _.isEmtpy might introduce equally severe regressions. I advise we replace them all with a custom implementation of that method.

I'll try to find some time to write a first PR fixing this in the evening, if no one else does.

**Comment by louisremi** [comment]
Here's a possible implementation of a future `Utils.isEmpty`:
```js
const isEmpty = require('lodash/isEmpty');

Utils.isEmpty = function(value) {
  if ( value == null ) {
    return true;
  }
  return isEmpty(value) && Object.getOwnPropertySymbols(value).length === 0;
};
```

**Comment by sushantdhiman** [comment]
Yeah this issue was recently noted by https://github.com/sequelize/sequelize/issues/8406

**Comment by louisremi** [comment]
I realize Symbols used as object keys are [not considered enumerable in `for .. in` loops](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Symbols_and_for...in_iteration). So there are far more potential bugs than just with `_.isEmpty`. I've a bad feeling we'll uncover many in the coming weeks :-/

**Comment by gabegorelick** [comment]
Has anyone started work on this? Otherwise I have #8435 up where I plan to tackle this.

**Comment by sushantdhiman** [comment]
I am not closing this issue as our tests are still running String based operators, I would like to run all those tests on Symbol operators. That might help us uncover any other potential issues, community reported issues are also a good guideline about improvement we need to make.

**Comment by louisremi** [comment]
I believe this should stay open as, see comment https://github.com/sequelize/sequelize/issues/8423#issuecomment-335209624

**Comment by sushantdhiman** [comment]
In v5-beta now all tests are running with Operators and regressions I am aware of are already fixed
