### ISSUE TITLE
String based operators are now deprecated.

### ISSUE THREAD

**Issue by davidkoplik** [sequelize/sequelize#8427]
## What are you doing?

```js
let sequelize = new Sequelize('mysql://user:pass@localhost:port/db');
```

## What do you expect to happen?
_I expected Sequelize to run without deprecation warnings._

## What is actually happening?
_This is the message I always receive:_

`sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators WebstormProjects/Ravenstein/node_modules/sequelize/lib/sequelize.js:236:13`

I do **not** use String based operators, this happens anytime I connect to the database.
This is the line of code that is triggering it:
src: `node_modules/sequelize/lib/sequelize.js:236:13`
`if (this.options.operatorsAliases === true) {`
Should I set the operatorsAliases to false each time? Is it intended to be like this?

__Dialect:__ mysql
__Dialect version:__ 1.4.2
__Database version:__ 5.7.19
__Sequelize version:__ 4.13.5
__Tested with master branch:__ No

**Comment by sushantdhiman** [comment]
Yes, you are supposed to set `operatorsAliases` even when initializing. This is to keep developers aware that dont depend upon String operators at all or at-least limit them. if you know what you are doing and sanitize your database inputs this is just a warning to ignore till v5.

Moved to https://github.com/sequelize/sequelize/issues/8417
