### ISSUE TITLE
allowNull:false attribute cannot rely on asynchronous update from setting of another attribute

### ISSUE THREAD

**Issue by CAD97** [sequelize/sequelize#8428]
## What are you doing?

Hashing a password using an `async` API into a `allowNull: false` field. (This would behave the same without the `async/await` sugar.)

```js
const User = sequelize.define('user', {
  password: {
    type: Sequelize.VIRTUAL,
    async set (val) {
      this.setDataValue('password', val)
      this.passwordHash = await Password.hash(val)
    }
  }
  passwordHash: {
    type: Sequelize.CHAR(60),
    allowNull: false
  }
})

User.sync().then(() => {
  User.create({ password: 'test' })
})
```

## What do you expect to happen?

The record to be created and synced to the database.

## What is actually happening?

An error is thrown: `passwordHash cannot be null`:

```text
Unhandled rejection SequelizeValidationError: notNull Violation: passwordHash cannot be null
    at Promise.all.then (sequelize\lib\instance-validator.js:77:15)
    at tryCatcher (bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (bluebird\js\release\promise.js:512:
31)
    at Promise._settlePromise (bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (bluebird\js\release\promise_array.js:1
44:14)
    at Promise._settlePromise (bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (bluebird\js\release\async.js:133:16)
    at Async._drainQueues (bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

__Dialect:__ any (tested with mysql, but errors before talking to the network)
__Dialect version:__ n/a
__Database version:__ n/a
__Sequelize version:__ 4.13.5
__Tested with master branch:__ Yes (4.13.5 is up to date with master)

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

## Currently working workaround

```js
const User = sequelize.define('user', {
  password: {
    type: Sequelize.VIRTUAL,
    set (val) {
      this.setDataValue('password', val)
      this.passwordHash = '<WILL BE REPLACED>'
    }
  }
  passwordHash: {
    type: Sequelize.CHAR(60),
    allowNull: false
  }
}, {
  hooks: {
    async beforeCreate (model, options) {
      model.passwordHash = await Password.hash(model.password)
    }
  }
})
```

`Password.hash(pasword)` returns `Promise<string>` and is roughly equivalent to `BCrypt.hash(password, 10)`.

**Comment by sushantdhiman** [comment]
`before` hooks are good place to do it.

In your example you never updated `passwordHash` with new value, how you suppose Sequelize will know its changed. You are only setting `password` in setter method

**Comment by CAD97** [comment]
`password/set` is an `async` function that sets `passwordHash`. It is being set, it's just sequelize doesn't realize that the `set` function is asynchronous and wait for it.

I understand if this is a won't-fix, since there is obviously a easy workaround of setting `passwordHash` to a dummy value from the `password` setter synchronously and then updating it asynchronously from `beforeCreate`.

However, (having not read the code) it seems like a simple cause, though now that I think about it, one likely without a fix. `set` here is `async` and the calling code is not respecting that, only using the synchronous part. However, property getter/setters are synchronous; you can't make `name = value` an asynchronous operation.

It would be nice if the hook `beforeCreate` ran before the validation step that catches the null (because I just tested, and removing the assignment to `passwordHash` in the workaround causes the validation error still), but other than that I don't think anymore that the original formulation could be made to work.

**Comment by sushantdhiman** [comment]
I will say again

```js
this.passwordHash = await Password.hash(val)
```

doesnt not update `passwordHash` at all, that method is only updating `password` in model data store but not updating `passwordHash` data store at all

**Comment by CAD97** [comment]
If we ignore the fact that it's `await` and pretend it's synchronous, though, it does. The fact that the workaround works with the same syntax proves that it works.

```js
    set (val) {
      this.setDataValue('password', val)
      this.passwordHash = '<WILL BE REPLACED>'
    }
```

I don't know if it's _guaranteed_ to work _by the library_, but `this.passwordHash = <value>` is equivalent to `this.passwordHash.set(<value>)`, by [the definition of the set function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set)

**Comment by sushantdhiman** [comment]
But if that was true for sequelize why would you do this

```js
this.setDataValue('password', val)
```

You would be doing something like this

```js
this.password = val;
```

**Comment by CAD97** [comment]
Because doing `this.password = <value>` means `this.password.set(<value>)`, and the function we are writing is `this.password.set`. Infinite recursion doesn't work, so we set the backing property directly, using the function the docs tell us to.

**Comment by CAD97** [comment]
This behavior is [mentioned in the docs for getters & setters in the context of the library](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#defining-as-part-of-the-model-options). (Just found this.)

**Comment by DiegoRBaquero** [comment]
Might want this behavior: 

```js
  User.beforeSave(async (user, options) => {
    if (user.changed('password')) {
      const salt = await bcrypt.genSalt(10)
      const hash = await bcrypt.hash(user.password, salt)
      user.password = hash
    }
  })
```

This will cover create and update, only when a new password is set.

**Comment by CAD97** [comment]
I want to have `password`/`passwordHash` separate for clarity. But that said, what I am asking here doesn't make sense as you can't have an asynchronous setter in JavaScript. That the documentation says validations run on `create`, `update`, and `save`, but a validation pass (for not-null at the very least) happens before `beforeCreate` may be an issue, but it is not this issue. I may open a different issue for that later, but this is a non-issue.
