### ISSUE TITLE
Setting an association in a belongsToMany relationship

### ISSUE THREAD

**Issue by lautaromss** [sequelize/sequelize#8431]
## What are you doing?

Trying to set/add an association to instances using the setter methods:

```js
// N:M
dbSchema.Vendor.belongsToMany(dbSchema.Regions, {through: dbSchema.Vendor_as, foreignKey: 'vendor_guid'});
dbSchema.Regions.belongsToMany(dbSchema.Vendor, {through: dbSchema.Vendor_as, foreignKey: 'region_guid'});

dbSchema.Vendor.addScope(
  'withIncludes', 
  {include: [{model:dbSchema.Regions, attributes: {exclude:['vendors']}}]}
);

dbSchema.Vendor.scope('withIncludes').findById(1).then(my_vendor => {

    my_vendor.setRegions(1).then(
        function () {
            console.log('Done')
        }
    )
});
```

## What do you expect to happen?
I expected the model to be updated with the new region, so I can then use the save() method to push the changes to my database.

## What is actually happening?
Instead the console shows Sequelize trying to select a row through the table vendors_as_region that doesn't exist (as my vendor didn't have that region yet), and then throws an AggregateError because it creates a vendors_as_number instance with id null.

> Executing (default): SELECT [vendor_as_guid], [as_number], [lastupdateby], [lastupdatedate], [inactive_indicator], [vendor_guid], [region_guid] FROM [nvs_central].[vendor_as_number] AS [vendor_as] WHERE [vendor_as].[vendor_guid] = 1;
> Executing (default): DELETE FROM [nvs_central].[vendor_as_number] WHERE [vendor_guid] = 1 AND [region_guid] IN (2); SELECT @@ROWCOUNT AS AFFECTEDROWS;
> 
> Unhandled rejection AggregateError: aggregate error

__Dialect:__ mssql
__Sequelize version:__ ^4.10.0

**Comment by lautaromss** [comment]
Update: I also tried changing the last bit of my code to this:

```js
  var my_region = dbSchema.Region.build({region_guid: 1, region: "NA", vendor_region: false});

  my_vendor.addRegion(my_region).then(
      function () {
          console.log('Done')
      }
  );
```

But throws the same AggregateError for the same reasons

**Comment by lautaromss** [comment]
Ok after thinking that this belongsToMany way wasn't implemented and writting more than 100 lines of difficult code trying to implement it, I found out what my original problem was.

The error was caused by Sequelized trying to create a null ID because I didn't put "autoIncrement: true" in the model. Now it's fixed.

```
dbSchema.Vendor_as = sequelize.define('vendor_as', {
  vendor_as_guid: {
    type: Sequelize.INTEGER,
    allowNull: false,
    autoIncrement: true,
    primaryKey: true
  }
}
```

**Comment by Vi-jay** [comment]
thanks ! you fixed my problem.
