### ISSUE TITLE
assassination setter with scope deletes unrelated records  

### ISSUE THREAD

**Issue by amit034** [sequelize/sequelize#8438]
## What are you doing?

when trying to create assassination methods for readOnlyUsers and readWriteUsers the setReadOnlyUsers deletes all records that are not in the readOnlyUser List
```js
models.Project.belongsToMany(models.Users, {
                    through: {
                        model: models.ProjectUsers,
                        scope: {
                            isViewOnly: 1
                        }
                    },
                    foreignKey: 'projectId',
                    otherKey: 'userId',
                    as: 'readOnlyUsers'
});
models.Project.belongsToMany(models.Users, {
                    through: {
                        model: models.ProjectUsers,
                        scope: {
                            isViewOnly: 0
                        }
                    },
                    foreignKey: 'projectId',
                    otherKey: 'userId',
                    as: 'readWriteUsers'
});
...
project.setReadOnlyUsers(2);
```
currently in db 
project_id   user_id   is_view_only
1100   4   0
 1100  7   0  

what appends is: 
DELETE FROM `project_users` WHERE `project_id` = 1100 AND `user_id` IN (7, 4)
INSERT INTO `project_users` (`user_id`,`project_id`,`is_view_only`) VALUES (2,1100,true);
## What do you expect to happen?
i whould expect that the delete operation will remove only is_view_only =1 records that are not in the readOnlyUsers list
## What is actually happening?
what actually append it deleted all project_users including the readWriteUsers

Dialect: mysql
Sequelize version: 3.28.0

**Comment by sushantdhiman** [comment]
v3 is no longer supported
