### ISSUE TITLE
Generate Raw SQL Queries for DB migrations

### ISSUE THREAD

**Issue by borislemke** [sequelize/sequelize#8441]
As suggested by @PascalPflaum [Collaborator at Umzug], I'm re-opening this issue from `umzug`s repo:

In rails, generating migrations will also generate an .sql file to be used with SQL.
E.g, when creating a new migration, it will be accompanied with something like this file:
`2103232813.sql`

```
ALTER TABLE `products` CHANGE `group` `group` varchar(50) DEFAULT NULL
ALTER TABLE `products` CHANGE `person` `person` varchar(50) DEFAULT NULL
ALTER TABLE `products` CHANGE `store_name` `store_name` varchar(50) DEFAULT NULL
```

Is this possible with `sequelize` as well? At our company, engineers do not have access to production servers so we usually give the raw queries to our devops which they use to execute migrations on our production database.

I would appreciate if someone could guide me to the right direction to achieve this functionality.

**Comment by rcarubbi** [comment]
anyone else with this need? In my company we don't have permission to connect in production environment database to execute sequelize db:migrate, we need to send the sql scripts to DBA's. 
I tried to find out some way to just generate scripts instead execute them via sequelize cli but with no success at this moment.

**Comment by sushantdhiman** [comment]
Please report this to https://github.com/sequelize/cli/ , I can't guarantee anything but this is something cli should support. We can keep feature request open so some day it can be implemented / contributed

**Comment by Javad-Alirezaeyan** [comment]
I am strongly looking for this. If someone has a solution for that, let me know please

**Comment by kevin-bermudez** [comment]
I have this same need using sequelize
