### ISSUE TITLE
[Regression with v4] Nested include cannot work without an empty where clause

### ISSUE THREAD

**Issue by NicolasBiehler** [sequelize/sequelize#8442]
## What are you doing?

I have a model Element that can belongs to different Users. A User can come from an archived Folder or not. 

Models:
```js
  User.hasMany(Element)
  Element.belongsTo(User)
  Folder.hasMany(User)
  User.belongsTo(Folder)
```

Class method:
```js
Element.filterByNonArchivedUsers = function (where) {
    return this.findAll({
      where,
      include: [
        {
          model: User,
          include: [
            {
              model: Folder,
              where: {
                name: { $ne: 'archive' }
              }
            }
          ]
        }
      ]
    })
  }
```

## What do you expect to happen?

Before switching to sequelize v4 (I was using v 3.30.4), I would get the Elements coming from non archive Folders' Users. With sequelize v4, I get all the Elements matching the original where clause, disregarding the include clause.

## Temporary workaround

When I add an empty clause to the first include, I get the result I had before switching version:

```js
Element.filterByNonArchivedUsers = function (where) {
    return this.findAll({
      where,
      include: [
        {
          model: User,
          where: {},
          include: [
            {
              model: Folder,
              where: {
                name: { $ne: 'archive' }
              }
            }
          ]
        }
      ]
    })
  }
```

__Dialect:__ postgres
__Dialect version:__  <http://github.com/brianc/node-postgres> v6.4.2
__Database version:__ 9.5
__Sequelize version:__ 4.10.3 to 4.13.6, all 4.x.x versions seem affected
__Tested with master branch:__ Yes

**Comment by STEVEOO6** [comment]
You'll want to add 'required: true' inside the include object, to ensure that results are filtered by those that match the nested query

**Comment by NicolasBiehler** [comment]
It appears that you are right:

```js
Element.filterByNonArchivedUsers = function (where) {
    return this.findAll({
      where,
      include: [
        {
          model: User,
          required: true,
          include: [
            {
              model: Folder,
              where: {
                name: { $ne: 'archive' }
              }
            }
          ]
        }
      ]
    })
  }```

This gives the correct result.

**Comment by NicolasBiehler** [comment]
Alright I was wondering if it made sense or not to let the issue open since I still feel that it was a regression between v3 and v4, but the fact that it was working without the required field previously might have been a 'bug' between the different dependencies we have here (pg, sequelize, etc).

So I learned a new thing that way, thanks again, and unless someone realizes this is in fact the symptom of a bigger problem, I think I can close and we are done here.
