### ISSUE TITLE
when using sequelize.where(), default scope is ignored

### ISSUE THREAD

**Issue by FranckFreiburger** [sequelize/sequelize#8443]
## What are you doing?

```js
const Address = sequelize.define('address', {
	name: {
		type: Sequelize.TEXT,
	},
	latitude: {
		type: Sequelize.FLOAT,
	},
	longitude: {
		type: Sequelize.FLOAT,
	},
	active: {
		type: Sequelize.BOOLEAN,
		defaultValue: false
	}
},{
	paranoid: true,
	defaultScope: {
		where: {
			active: true
		}
	},
});

var addresses = await Address.findAll({
  where: { latitude: { [Sequelize.Op.gt]: 1 } }
});
/* sql:
... WHERE
      (("address"."deletedAt" > CURRENT_TIMESTAMP OR "address"."deletedAt" IS NULL)
      AND ("address"."latitude" > 1 AND "address"."active" = true));
*/

var addresses = await Address.findAll({
  where: sequelize.where(sequelize.col('latitude'), '>', 1)
});
/* sql:
... WHERE
      (("address"."deletedAt" > CURRENT_TIMESTAMP OR "address"."deletedAt" IS NULL)
      AND "latitude" > 1);
*/
```

## What do you expect to happen?
using sequelize.where() keep the default scope

## What is actually happening?
default scope is not taken in account when using `where: sequelize.where()`

__Dialect:__ postgres
__Dialect version:__ ???
__Database version:__ 9.6.1
__Sequelize version:__ latest npm
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by FranckFreiburger** [comment]
However, I found that the following form is accepted:
```
await Address.findAll({
	where: { '': sequelize.where(...) }
})
```
Is it expected ?

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/8473
