### ISSUE TITLE
cascade delete does not work

### ISSUE THREAD

**Issue by onerciller** [sequelize/sequelize#8444]
i associated lines with orders like following but  I want to delete them as relational but it didn't work, 
 what could be reason for this ?

```js
 associate: function(models) {
      Orders.hasMany(models.lines, { onDelete: 'cascade' });
    }
```

**Comment by pbishop16** [comment]
I had the same issue. I was missing `hooks: true,`. Adding it solved the issue. Recommend trying the below:
```
Orders.hasMany(models.lines, { 
  onDelete: 'cascade',
  hooks: true, 
});
```
I was able to find some insight here: http://docs.sequelizejs.com/manual/tutorial/hooks.html#associations

**Comment by subotin94** [comment]
Ofcourse its still an issue...

**Comment by huyb1991** [comment]
The problem is missing `CONSTRAINT` in schema. So, the solution is add a migration script to add foreign key field into table:

Here's my answer on SO: [Sequelize.js onDelete: 'cascade' is not deleting records sequelize
](https://stackoverflow.com/a/55323664/5456204)
```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.addColumn(
      'Product', // name of Source model
      'categoryId', // name of the key we're adding 
      {
        type: Sequelize.INTEGER,
        references: {
          model: 'Category', // name of Target model
          key: 'id', // key in Target model that we're referencing
        },
        onUpdate: 'CASCADE',
        onDelete: 'CASCADE',
      }
    );
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.removeColumn(
      'Product', // name of Source model
      'categoryId' // key we want to remove
    );
  }
};
```

Hope this help!

**Comment by HuzaifaJH** [comment]
I have once ran the migration file and now i am adding `onDelete: 'CASCADE'`, this in it. So will re-running it add this thing to the table in my DB without messing any other thing up?

**Comment by ryan-harris** [comment]
this may be related to this bug: https://github.com/sequelize/sequelize/issues/6586

**Comment by kubal-s** [comment]
This bug still exists

**Comment by okomura** [comment]
> The problem is missing `CONSTRAINT` in schema. So, the solution is add a migration script to add foreign key field into table:
> 
> Here's my answer on SO: [Sequelize.js onDelete: 'cascade' is not deleting records sequelize ](https://stackoverflow.com/a/55323664/5456204)
> 
> ```
> 'use strict';
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.addColumn(
>       'Product', // name of Source model
>       'categoryId', // name of the key we're adding 
>       {
>         type: Sequelize.INTEGER,
>         references: {
>           model: 'Category', // name of Target model
>           key: 'id', // key in Target model that we're referencing
>         },
>         onUpdate: 'CASCADE',
>         onDelete: 'CASCADE',
>       }
>     );
>   },
>   down: (queryInterface, Sequelize) => {
>     return queryInterface.removeColumn(
>       'Product', // name of Source model
>       'categoryId' // key we want to remove
>     );
>   }
> };
> ```
> 
> Hope this help!

This helped me!

**Comment by ltbittner** [comment]
+1 Deleting something with a hasMany relationship does not cascade delete

**Comment by ZhenKasp** [comment]
I had the same issue, fixed it with changing the order of associations declaration. The `hasMany` need to be declared before the `belongsTo`.
```
User.hasMany(Book, { onDelete: 'CASCADE', hooks: true });
Book.belongsTo(User);
```

**Comment by saikrishnakethan** [comment]
Same issue. Solved by changing this
```
const user = await User.destroy({
    where: {
      id: '1394',
    },
 });
```
 to
 ```
const user = await User.findOne({
    where: {
      id: '1394',
    },
 });
 await user.destroy();
```
 No sure how this is solving is

**Comment by cmuentes** [comment]
> Same issue. Solved by changing this
> 
> ```
> const user = await User.destroy({
>     where: {
>       id: '1394',
>     },
>  });
> ```
> 
> to
> 
> ```
> const user = await User.findOne({
>    where: {
>      id: '1394',
>    },
> });
> await user.destroy();
> ```
> 
> No sure how this is solving is

This just solved it for me as well - I wonder what could be different between both methods? This requires 2 calls to MySql now which is just lame

**Comment by nationalcodecare** [comment]
> Same issue. Solved by changing this
> 
> ```
> const user = await User.destroy({
>     where: {
>       id: '1394',
>     },
>  });
> ```
> 
> to
> 
> ```
> const user = await User.findOne({
>    where: {
>      id: '1394',
>    },
> });
> await user.destroy();
> ```
> 
> No sure how this is solving is

Not sure how does it solving, but it works. Thanks!

**Comment by x8848** [comment]
I couldn't manage latest `"sequelize": "^6.6.5"` association cascade to work with any of mentioned here tips so had to replace it with a model `beforeDestroy` hook below

```
User.beforeDestroy(async user => {
  await Role.destroy({ where: { userId: user.id } })
})
```

**Comment by pforprince** [comment]
Two points to note:
1. Has Many relationship should come before the BelongsTo
2. BelongsTo should also contain the foreign Key option with same key as in hasMany

```
Donor.hasMany(Donation, {
  foreignKey: "donorId",
  onDelete: "cascade",
});
Donation.belongsTo(Donor, { foreignKey: "donorId" });
```

This worked for me

**Comment by talhakhadim** [comment]
> I had the same issue, fixed it with changing the order of associations declaration. The `hasMany` needs to be declared before the `belongsTo`.
> 
> ```
> User.hasMany(Book, { onDelete: 'CASCADE', hooks: true });
> Book.belongsTo(User);
> ```

this solves my issue.
thanks

**Comment by lumpov** [comment]
I don't imagine, that this bug not resolved for 5 years. Karl, 5 years!

- Sequelize version: sequelize@6.25.4, @sequelize/core@7.0.0-alpha.10
- Node.js version: v16.15.1
- If TypeScript related: TypeScript version: N/A
- Database & Version: MySQL v16.15.1
- Connector library & Version: mysql2@2.3.3

My case:

``` javascript
'use strict';

const { Sequelize, DataTypes } = require('sequelize');

(async () => {
	const sequelize = new Sequelize('x', 'x', 'x', {
		host: 'localhost',
		dialect: 'mysql',
		define: {
			charset: 'utf8mb4',
			freezeTableName: false,
			createdAt: 'created_at',
			updatedAt: 'updated_at',
			deletedAt: 'deleted_at',
			timestamps: true,
			underscored: true,
			paranoid: true,
		},
		//logging: (...msg) => console.log(msg),
	});

	const resus = await sequelize.define('resus', {
		id: {
			type: 'BIGINT UNSIGNED',
			allowNull: false,
			primaryKey: true,
			autoIncrement: true,
			comment: null,
		},
		label: {
			type: 'VARCHAR(250)',
			allowNull: false,
			defaultValue: '',
			primaryKey: false,
			autoIncrement: false,
			comment: null,
		},
	});

	const fils = await sequelize.define('fils', {
		id: {
			type: 'BIGINT UNSIGNED',
			allowNull: false,
			primaryKey: true,
			autoIncrement: true,
			comment: null,
		},
		label: {
			type: 'VARCHAR(250)',
			allowNull: false,
			defaultValue: '',
			primaryKey: false,
			autoIncrement: false,
			comment: null,
		},
		resource_id: {
			type: 'BIGINT UNSIGNED',
			allowNull: false,
			comment: null,
		},
	});

	fils.hasMany(resus, { onDelete: 'CASCADE' });
	resus.belongsTo(fils, {});

	await fils.sync({ alter: true });
	await resus.sync({ alter: true });

	const resu = await resus.create({ label: 'resu label' });
	console.log('resu:', resu.toJSON());

	const fil = await fils.create({
		label: 'fil label',
		resource_id: resu.id,
	});
	console.log('fil:', fil.toJSON());

	const d = await resus.destroy({
		where: {
			id: fil.id,
		},
		logging: (...msg) => console.log(msg),
	});

	console.log('d:' + d);
})();
```

I cannot explain why `cascade: false,` in debug log of `destroy()`:

```
x % node cascade
Executing (default): CREATE TABLE IF NOT EXISTS `fils` (`id` BIGINT UNSIGNED NOT NULL auto_increment , `label` VARCHAR(250) NOT NULL DEFAULT '', `resource_id` BIGINT UNSIGNED NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `deleted_at` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
Executing (default): SHOW FULL COLUMNS FROM `fils`;
Executing (default): SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'fils' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='adminas' AND REFERENCED_TABLE_NAME IS NOT NULL;
Executing (default): ALTER TABLE `fils` CHANGE `label` `label` VARCHAR(250) NOT NULL DEFAULT '';
Executing (default): ALTER TABLE `fils` CHANGE `resource_id` `resource_id` BIGINT UNSIGNED NOT NULL;
Executing (default): ALTER TABLE `fils` CHANGE `created_at` `created_at` DATETIME NOT NULL;
Executing (default): ALTER TABLE `fils` CHANGE `updated_at` `updated_at` DATETIME NOT NULL;
Executing (default): ALTER TABLE `fils` CHANGE `deleted_at` `deleted_at` DATETIME;
Executing (default): SHOW INDEX FROM `fils`
Executing (default): CREATE TABLE IF NOT EXISTS `resus` (`id` BIGINT UNSIGNED NOT NULL auto_increment , `label` VARCHAR(250) NOT NULL DEFAULT '', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `deleted_at` DATETIME, `fil_id` BIGINT UNSIGNED, PRIMARY KEY (`id`), FOREIGN KEY (`fil_id`) REFERENCES `fils` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
Executing (default): SHOW FULL COLUMNS FROM `resus`;
Executing (default): SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'resus' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='adminas' AND REFERENCED_TABLE_NAME IS NOT NULL;
Executing (default): ALTER TABLE `resus` CHANGE `label` `label` VARCHAR(250) NOT NULL DEFAULT '';
Executing (default): ALTER TABLE `resus` CHANGE `created_at` `created_at` DATETIME NOT NULL;
Executing (default): ALTER TABLE `resus` CHANGE `updated_at` `updated_at` DATETIME NOT NULL;
Executing (default): ALTER TABLE `resus` CHANGE `deleted_at` `deleted_at` DATETIME;
Executing (default): SELECT CONSTRAINT_CATALOG AS constraintCatalog, CONSTRAINT_NAME AS constraintName, CONSTRAINT_SCHEMA AS constraintSchema, CONSTRAINT_TYPE AS constraintType, TABLE_NAME AS tableName, TABLE_SCHEMA AS tableSchema from INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE table_name='resus' AND constraint_name = 'resus_ibfk_1' AND TABLE_SCHEMA = 'adminas';
Executing (default): ALTER TABLE `resus` DROP FOREIGN KEY `resus_ibfk_1`;
Executing (default): ALTER TABLE `resus` ADD FOREIGN KEY (`fil_id`) REFERENCES `fils` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
Executing (default): SHOW INDEX FROM `resus`
Executing (default): INSERT INTO `resus` (`id`,`label`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?);
resu: {
  id: 9,
  label: 'resu label',
  updated_at: 2022-11-21T12:14:10.810Z,
  created_at: 2022-11-21T12:14:10.810Z
}
Executing (default): INSERT INTO `fils` (`id`,`label`,`resource_id`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?,?);
fil: {
  id: 8,
  label: 'fil label',
  resource_id: 9,
  updated_at: 2022-11-21T12:14:10.819Z,
  created_at: 2022-11-21T12:14:10.819Z
}
[
  'Executing (default): UPDATE `resus` SET `deleted_at`=? WHERE `deleted_at` IS NULL AND `id` = ?',
  {
    plain: false,
    raw: false,
    logging: [Function: logging],
    showWarnings: false,
    where: { id: 8 },
    hooks: true,
    individualHooks: false,
    force: false,
    cascade: false,
    restartIdentity: false,
    type: 'BULKUPDATE',
    model: resus,
    dialect: 'mysql',
    dialectModule: null,
    dialectModulePath: null,
    host: 'localhost',
    protocol: 'tcp',
    define: {
      charset: 'utf8mb4',
      freezeTableName: false,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      deletedAt: 'deleted_at',
      timestamps: true,
      underscored: true,
      paranoid: true
    },
    query: {},
    sync: {},
    timezone: '+00:00',
    standardConformingStrings: true,
    omitNull: false,
    native: false,
    replication: false,
    ssl: undefined,
    pool: {},
    quoteIdentifiers: true,
    retry: { max: 5, match: [Array] },
    transactionType: 'DEFERRED',
    isolationLevel: null,
    databaseVersion: '8.0.31',
    typeValidation: false,
    benchmark: false,
    minifyAliases: false,
    logQueryParameters: false,
    allowNull: [],
    bind: [ '2022-11-21 12:14:10', 8 ]
  }
]
d:0
```

**Comment by HelenoSalgado** [comment]
> Same issue. Solved by changing this
> 
> ```
> const user = await User.destroy({
>     where: {
>       id: '1394',
>     },
>  });
> ```
> 
> to
> 
> ```
> const user = await User.findOne({
>    where: {
>      id: '1394',
>    },
> });
> await user.destroy();
> ```
> 
> No sure how this is solving is

This problem is old but still today this is what solved it for me. If anyone knows a simpler way let me know.

**Comment by Yxn16a** [comment]
> > I had the same issue, fixed it with changing the order of associations declaration. The `hasMany` needs to be declared before the `belongsTo`.
> > ```
> > User.hasMany(Book, { onDelete: 'CASCADE', hooks: true });
> > Book.belongsTo(User);
> > ```
> 
> this solves my issue. thanks

This did not work for me

**Comment by apostolides** [comment]
Banging my head on the same issue. Basically I have items and outfits. I want to have many items that can possibly belong to many outfits. When I delete an item, I want to also delete every associated outfit. Ended up like this:
```javascript
const { Sequelize, Model, DataTypes } = require('sequelize');

const sequelize = new Sequelize('sqlite::memory:');

const Item = sequelize.define('Item', {
    name: DataTypes.STRING,
});

const Outfit = sequelize.define('Outfit', {
    name: DataTypes.STRING,
});

Item.belongsToMany(Outfit, {through:'Item-Outfit', onDelete:'CASCADE', hooks:true});
Outfit.belongsToMany(Item, {through:'Item-Outfit'});


(async ()=>{
    await sequelize.sync();
    // Create some items.
    let shoes = await Item.create({name:"shoes"});
    let pants = await Item.create({name:"pants"});

    // Create an outfit.
    let outfit = await Outfit.create({name:"mynewoutfit"});

    // Add items to outfit.
    await outfit.addItem(shoes, {through:'Item-Outfit'});
    await outfit.addItem(pants, {through:'Item-Outfit'});

    // Print outfit.
    let result = await Outfit.findOne({where:{name:'mynewoutfit'}});
    console.log(result); 

    // Destroy one item included in outfit.
    let shoe = await Item.findOne({where:{name:"shoes"}});
    await shoe.destroy();

    // Lookup outfit (should return null).
    result = await Outfit.findOne({where:{name:'mynewoutfit'}});
    console.log(result);
})();

```
Look-up then destroy + the hooks:true did the trick. It's not optimal, I don't like 2 calls for one deletion but I think it does work.

**Comment by jgudo** [comment]
> Same issue. Solved by changing this
> 
> ```
> const user = await User.destroy({
>     where: {
>       id: '1394',
>     },
>  });
> ```
> 
> to
> 
> ```
> const user = await User.findOne({
>    where: {
>      id: '1394',
>    },
> });
> await user.destroy();
> ```
> 
> No sure how this is solving is



> Same issue. Solved by changing this
> 
> ```
> const user = await User.destroy({
>     where: {
>       id: '1394',
>     },
>  });
> ```
> 
> to
> 
> ```
> const user = await User.findOne({
>    where: {
>      id: '1394',
>    },
> });
> await user.destroy();
> ```
> 
> No sure how this is solving is

This works for single deletion. However,  for multiple deletions, cascade does not work
```
   await DB.GISDB.models.BusMaster.destroy({
         where: {
               bus_id: {
                        [Op.in]: [1, 2, 3]
                }
         },
          transaction
      });
```

**Comment by ephys** [comment]
I couldn't reproduce this issue on Sequelize 7 anymore.

If you're still experiencing the issue, please fill out a new bug report with the relevant information, including the Sequelize version
