### ISSUE TITLE
Op.or failing with Op.like

### ISSUE THREAD

**Issue by MicroDroid** [sequelize/sequelize#8448]
## What are you doing?
Trying to query using `LIKE`

```js
const articles = await models.articles.findAll({
  where: {
    [Sequelize.Op.or]: [
      {title:       {[Sequelize.Op.like]: '%' + keywords + '%'}},
      {description: {[Sequelize.Op.like]: '%' + keywords + '%'}},
    ]
  },
  limit: 10,
  include: ...
});
```

## What do you expect to happen?
I expect only matching models to be returned, *I also expect the executed SQL to contain the `LIKE` operator*

## What is actually happening?
All models are being returned, the executed SQL does not even contain the `LIKE` or `OR` operators

__Dialect:__ mysql
__Dialect version:__ 1.4.2
__Database version:__ 10.1.28
__Sequelize version:__ 4.10.0
__Tested with master branch:__ No

**Comment by sushantdhiman** [comment]
Should be fixed after https://github.com/sequelize/sequelize/releases/tag/v4.13.7

Let me know if it isnt

**Comment by MicroDroid** [comment]
That worked, thanks :)

**Comment by developer-man-ui** [comment]
now its 6.21.6 and am tring to find a selotion XD
