### ISSUE TITLE
Why datatype Time in model  after i query don't have +00:00 

### ISSUE THREAD

**Issue by zeing** [sequelize/sequelize#8455]
## What are you doing?

 I have MODEL from your library "sequelize-auto"

this is my sequelize connection :
```
const  connection = new Sequelize({
    host: config.mode[prefix].host,
    username : config.mode[prefix].user,
    password : config.mode[prefix].password,
    database : config.mode[prefix].database,
    dialect: config.mode[prefix].dialect,
    pool: {
        max: 30,
        min: 0,
        idle: 10000
    },
    define: {
        timestamps: false
    }
});
```

## What do you expect to happen?
i want data which have time type +00:00  from database ( datetime in my database  i collect  +00:00   UTC ) So  data in database == data after query
e.g.  2017-10-10 04:53:29 from database and when i query i get 2017-10-10 04:53:29 (or  like +00:00 datetime ) 
## What is actually happening?
in database
![image](https://user-images.githubusercontent.com/20161393/31390395-f6e2c6de-adfd-11e7-8c8c-424c2e6744e0.png)
i capture from Sequel Pro on MacOS

data query : 
![image](https://user-images.githubusercontent.com/20161393/31390434-1214e630-adfe-11e7-957b-aa1dcf380f2e.png)

__Dialect:__ mysql 
__Dialect version:__ ^1.4.2
__Database version:__ 5.7.16
__Sequelize version:__ 4.13.8
__Tested with master branch:__ Yes

sorry for my english , thank you

**Comment by sushantdhiman** [comment]
JavaScript doesn't support timezones, all dates are in local timezone offset to UTC.

What you are explaining here is default stringification of a date object. If you want to represent your date with proper timezone offsets you need to use moment, which can take in a js date and convert it to various formats of your liking.

Again this is not related to Sequelize :) This is how JS works. If you need more control on formats use moment

**Comment by zeing** [comment]
thank you :)
