### ISSUE TITLE
timestamp with default NOW will be created with no milliseconds

### ISSUE THREAD

**Issue by amasad** [sequelize/sequelize#8460]
## What are you doing?

A timestamp, say `createdAt` property that has the `DataTypes.NOW` in the definition will be inserted with no milliseconds.

```js
sequelize.define('foo', {  
  time_created: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW,
  }, {
      timestamps: true,
      createdAt: 'time_created',
      updatedAt: false,
      deletedAt: false,
  }
});

// Later

Foo.create({}) // Creates an insert query with a timestamp missing milliseconds
```

```sql
INSERT INTO "foo" ("time_created") VALUES ('2017-10-10 20:59:44.000 +00:00') RETURNING *;                                                                                   
```

## What do you expect to happen?
Expect to see milliseconds

## What is actually happening?
seeing 00 in place of millis.

Tested on postgres but probably applies to others.

Seemingly related to #4539

**Comment by ktret** [comment]
Need to pass the dialect to Utils.toDefaultValue() so it can pass it to now().  Minimum changes below.  Might want to change everywhere else that model.js uses Utils.toDefaultValue also.  Working for me on create() with postgres.  Sorry, don't have time to figure out to submit a PR right now.

https://github.com/sequelize/sequelize/blob/master/lib/model.js#L994
`
this._defaultValues[name] = _.partial(Utils.toDefaultValue, definition.defaultValue, this.sequelize.options.dialect);
`

https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L302
`
function toDefaultValue(value, dialect) {
`
https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L315
`
return now(dialect);
`

**Comment by ericf89** [comment]
I'm using  `defaultValue: () => new Date()` for now as a work around.  Seems to work with postgres at least.

**Comment by cameront** [comment]
Was this fixed for bulkCreate too?
