### ISSUE TITLE
Database creation fails when Sequelize.ENUM is used

### ISSUE THREAD

**Issue by tuomash** [sequelize/sequelize#8463]
## What are you doing?
Defined a model which has an attribute with type Sequelize.ENUM.

## What do you expect to happen?
The database creation process not to fail.  

## What is actually happening?
When the application is started for the first time (no tables, types or anything in the database), Sequelize fails. On the second run it completes successfully.

The log output before failure:

```text
Executing (default): DROP TYPE IF EXISTS "public"."enum_table”;
Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_table’ GROUP BY 1
Executing (default): DROP TYPE IF EXISTS "public"."enum_table”; CREATE TYPE "public"."enum_table” AS ENUM(‘value1’, ‘value2’, ‘value3’, ‘value4’, ‘value5’);
```

The error message:

```text
Oct 10 15:23:50 ticker[25721] ERROR: Cannot read property '0' of undefined
  err: TypeError: Cannot read property '0' of undefined
      at query.catch.then.then.queryResult (/path-to/node_modules/sequelize/lib/dialects/postgres/query.js:112:17)
  From previous event:
      at Query.run (/path-to/node_modules/sequelize/lib/dialects/postgres/query.js:97:8)
      at retry (/path-to/node_modules/sequelize/lib/sequelize.js:543:32)
      at /path-to/node_modules/retry-as-promised/index.js:39:21
      at retryAsPromised (/path-to/node_modules/retry-as-promised/index.js:29:10)
      at Promise.try.then.connection (/path-to/node_modules/sequelize/lib/sequelize.js:543:14)
```
Seems to be related to #8005.

The database creation process doesn't fail if I comment out the attribute with the enum definition.

Also downgrading dialect version from 7.3.0 to 6.4.2 fixes this issue.

__Dialect:__ postgres
__Dialect version:__ 7.3.0
__Database version:__ 9.6
__Sequelize version:__ 4.13.8
__Tested with master branch:__ No

**Comment by sushantdhiman** [comment]
pg v7 is not supported, Please use pg v6 for now
