### ISSUE TITLE
connection.query(...).on is not a function

### ISSUE THREAD

**Issue by sathishadi** [sequelize/sequelize#8469]
**Can some one look into this Issue . Its urgent Got struck badly from last 3 days....................**
![conn_issue](https://user-images.githubusercontent.com/32728575/31483049-77b0b9ba-af48-11e7-9267-041b8e454b5a.png)

versions followed : 
  **PostGreSql** : postgresql-10.0-1-windows-x64
**pg**:7.3.0
**pg-host**: 2.3.2
**Sequilize-auto**: 0.4.28

**Comment by sushantdhiman** [comment]
Report this at `sequelize-auto` repo
