### ISSUE TITLE
Postgres range inclusive property lost in JSON format

### ISSUE THREAD

**Issue by kingjerod** [sequelize/sequelize#8471]
## What are you doing?
Querying a Postgres table with a daterange column and returning it as JSON.

```js
const Timeline = Sequelize.define({
   id: {type: Sequelize.INTEGER, primaryKey: true},
   date_range: {type: Sequelize.RANGE(Sequelize.DATEONLY)}
});
const range = [
   {value: new Date(Date.UTC(2017, 0, 1)), inclusive: true},
   {value: new Date(Date.UTC(2017, 6, 1)), inclusive: false},
];
await Timeline.create({id: 1, date_range: range});
const row = await Timeline.findById(1);
console.log(JSON.stringify(row)); // No inclusive property
```

## What do you expect to happen?
When returning the data as JSON, the inclusive data should not be lost. 

In the docs, there is this optional format for updating, this would be better because it can be turned into JSON without losing any information:
```js
const range = [
  { value: '2017-01-01', inclusive: false },
  { value: '2017-07-01', inclusive: true },
];
```

## What is actually happening?
The inclusive property is lost. This is because the inclusive property is set on an array, and array properties are not converted into JSON (like Array.length).

```js
{id:1, date_range: ['2017-01-01', '2017-07-01']}
```

__Dialect:__ postgres
__Dialect version:__ 9.6
__Database version:__ 9.6
__Sequelize version:__ 4.4.3
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/9364
