### ISSUE TITLE
Symbol operators in scoped where not applied

### ISSUE THREAD

**Issue by seally1186** [sequelize/sequelize#8473]
(This is potentially related or a similar issue to #8423.)

## What are you doing?
When creating a scope with a where clause containing a Symbol operator, the subclause is lost.

```js
const Test = db.sequelize.define("Test", {
  a: DataTypes.INTEGER,
  b: DataTypes.INTEGER,
  c: DataTypes.INTEGER
}, {
  scopes: {
    foo: { where: { [Op.or]: { a: 1, b: 2 }, c: 3 } }
  }
});
sequelize.sync().then(() => {
  console.log(Test.scope("foo")._scope);
  Test.scope("foo").findAll();
});
```

## What do you expect to happen?
Query should be `(a = 1 OR b = 2) AND c = 3`.

## What is actually happening?
```
{ where: { c: 3 } }
Executing (default): SELECT `id`, `a`, `b`, `c`, `createdAt`, `updatedAt` FROM `Tests` AS `Test` WHERE `Test`.`c` = 3;
```

The issue appears to be that `_.assign` does not handle Symbols:

```js
> _.assign({}, {[Symbol("abc")]:123})
{}
```

__Dialect:__ any
__Sequelize version:__ 4.13.10
__Tested with master branch:__ Yes

**Comment by iamjoyce** [comment]
Hi @sushantdhiman, are there any alternatives to solve this?

**Comment by seally1186** [comment]
Hi @iamjoyce, currently my workaround is to set `operatorsAliases = Sequelize.Op.Aliases` (which suppresses the deprecation warning) and use string operators in scopes (like `"$or"`). Not ideal, but keeps the system running.

**Comment by skn3** [comment]
can also confirm that this breaks when using the extend() module. The following fails:

```
        options = extend(true, {}, options, {
            where: {
                [Sequelize.Op.or]: or,
            },
        });
```

**Comment by gkaran** [comment]
Same behavior with `Object.assign`.

**Comment by ahlwong** [comment]
This is a huge problem because it inadvertently runs unscoped queries

**Comment by iamjoyce** [comment]
Can anyone else verify that this has been fixed correctly? I am using version 4.31.2, and this isn't working correctly on my end.

For example,
```
// Does not work
Test.scope("foo").findAll();

// Works as expected
AnotherTest.findAll({
    include: [{
        model: Test.scope("foo")
    }]
})
```

Can we reopen this issue if this is the case?

**Comment by danistefanovic** [comment]
Same here. Symbol operators are still ignored when they're defined in scopes. Tested with 4.31.2.

**Comment by sushantdhiman** [comment]
Can you give me an example what does not work, [this test](https://github.com/sequelize/sequelize/pull/8863/files#diff-4d2476c07748527bad2cab47f73630d5R60) not sufficient?

**Comment by iamjoyce** [comment]
@sushantdhiman Looking at [that test case](https://github.com/sequelize/sequelize/pull/8863/files#diff-4d2476c07748527bad2cab47f73630d5R60), my initial suspicion would be `findOne` works, but scope on `findAll` will not work. Please refer to the initial example that I have provided above.

**Comment by sushantdhiman** [comment]
Mostly all `find*` methods call `findAll`, and that is where we inject scope. I have added [more tests](https://github.com/sequelize/sequelize/pull/8926/files#diff-4d2476c07748527bad2cab47f73630d5R71) and it seems to be working with `findAll` as well

**Comment by danistefanovic** [comment]
It seems like it's just not working with `[Op.or]`.

(I've tried to create a failing test but I always get a `SequelizeUnknownConstraintError: [object Object]` error)

**Comment by iamjoyce** [comment]
@sushantdhiman I think @danistefanovic could be right. Both issue creator and my codes are using `Op.or`

**Comment by sushantdhiman** [comment]
Ok I have again [expanded test](https://github.com/sequelize/sequelize/pull/8933/files#diff-4d2476c07748527bad2cab47f73630d5R44), query and results both looks ok to me

```sql
SELECT "id", "username", "email", "access_level", "other_value", "createdAt", "updatedAt"
FROM "ScopeMes" AS "ScopeMe"
WHERE ("ScopeMe"."access_level" = 3 OR "ScopeMe"."other_value" = 10)
AND "ScopeMe"."access_level" = 5
```

**Comment by sushantdhiman** [comment]
`lodash.defaults` does not copy Symbol keys from sources. I have addressed that in https://github.com/sequelize/sequelize/pull/8937 , it should fix this and any other potential issue related to `lodash.defaults` behaviour
