### ISSUE TITLE
Next values in raw query become null when selecting 'null' as a value before other values

### ISSUE THREAD

**Issue by sijmenvos** [sequelize/sequelize#8475]
## What are you doing?
When using sequelize.query, selecting values AS null before real values out of a table, all values return as null. The strange thing is that if you select the value before 'test', it does work.

Table example:
```sql
CREATE TABLE `sequelize_test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `value` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Query:
```js
sequelize.query(`
  SELECT
  NULL AS test,
  value AS value
  FROM sequelize_test
`, {
  type: models.sequelize.QueryTypes.SELECT,
})
```

## What do you expect to happen?
To return the value: 
```js
[ { test: null, value: 6 } ]
```

## What is actually happening?
It returns an empty value:
```js
[ { test: null, value: null } ]
```

__Dialect:__ mysql
__Database version:__ 5.7.18 MySQL Community Server (GPL)
__Sequelize version:__ 4.13.10
__Tested with master branch:__ yes

**Comment by sushantdhiman** [comment]
This issue is due to a bug in `mysql2`, I have submitted a test case https://github.com/sidorares/node-mysql2/pull/652

Hopefully will fix it when reason is clear.

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sidorares/node-mysql2/pull/652

Issue will be fixed in next release of mysql2

**Comment by sushantdhiman** [comment]
https://github.com/sidorares/node-mysql2/commit/97a88530db72c656c16f071a710701ad2830b38d
