### ISSUE TITLE
Postgres range insertion cannot parse single expression

### ISSUE THREAD

**Issue by kingjerod** [sequelize/sequelize#8479]
## What are you doing?
Using the alternate form for ranges to insert a row. 

```js
const Timeline = Sequelize.define({
   id: {type: Sequelize.INTEGER, primaryKey: true},
   date_range: {type: Sequelize.RANGE(Sequelize.DATEONLY)}
});
const range = [
   {value: new Date(Date.UTC(2017, 0, 1)), inclusive: true},
   {value: new Date(Date.UTC(2017, 6, 1)), inclusive: true},
];
await Timeline.create({id: 1, date_range: range});
```

## What do you expect to happen?
The generated SQL will have this for date_range: 
```js
'["2017-01-01","2017-07-01"]'
```

## What is actually happening?
The generated SQL is today's date, with inclusive + exclusive:  
```js
'["2017-10-13","2017-10-13")'
```
It seems to not know how to parse the alternate form that is mentioned in the docs.

__Dialect:__ postgres
__Dialect version:__ 9.6
__Database version:__ 9.6
__Sequelize version:__ 4.4.3
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/9364
