### ISSUE TITLE
sync({ alter: true }) is raising error

### ISSUE THREAD

**Issue by matt212** [sequelize/sequelize#8488]
## What are you doing?
I am implemeting sync({ alter: true }) in order to sync alter model  modification to my database

**js**
`models.sequelize.sync({ alter: true })`

**model**

```
        createdAt: {
            field: 'created_at',
            type: DataTypes.DATE,
            defaultValue:DataTypes.NOW,
            allowNull: false
        },
```

## What do you expect to happen?
I wanted my alter column statement should be able to  execute changes like name change, datatypes change , add and remove columns 

## What is actually happening?
it is throwing error , if i remove the **{ alter: true }** the error goes aways and everything works as expected.
![error1](https://user-images.githubusercontent.com/1698139/31603500-0106ea30-b27e-11e7-9948-06a240f22c00.png)

also even if remove  **allowNull: false** attribute of column create_at there is another error 

![error4](https://user-images.githubusercontent.com/1698139/31604720-c83eae00-b281-11e7-9af1-ebef843b7d29.png)

my consolidate model code looks like this

```
module.exports = function(sequelize, DataTypes) {
    return sequelize.define('employees', {
        employeesid: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        birth_date: {
            field: 'birth_date',
            type: DataTypes.DATE
        },
        first_name: {
            type: DataTypes.STRING(14),
            allowNull: false
        },
        last_name: {
            type: DataTypes.STRING(16),
            allowNull: false
        },
        gender: {
            type: DataTypes.ENUM('M', 'F'),
            allowNull: false
        },
        recordstate: {
            type: DataTypes.STRING(45),
            allowNull: true,
            defaultValue: 'active'
        },
        createdAt: {
            field: 'created_at',
            type: DataTypes.DATE
        },
        updatedAt: {
            field: 'updated_at',
            type: DataTypes.DATE
            
        },
    }, {
        tableName: 'employees'
    });
};
```

__Dialect: postgres
__Dialect version:lastest
__Database version:9.6
__Sequelize version:4.14.0

**Comment by matt212** [comment]
Hi, 
for time being since error does not damage my database integrity .
i had modified my existing code snippets to avoid this error below is promise error catch mechanism

```
models.sequelize.sync({alter:true}).then(function() {
  var server = app.listen(app.get('port'), function() {
    console.log('Express server listening on port ' + server.address().port);
  });
}, function(err) {
 console.log(err)
})
```
awaiting for valid  response for this issue !

**Comment by rzorzal** [comment]
I have this same error. And after I upgrading my Sequelize to v4, all relations is gone.

**Comment by sushantdhiman** [comment]
@matt212 ALTER is trying to change column from nullable to non null state, there is no way we can tell what valid data to fill in that row. Possible combinations will be endless.

If you want alter to work in this case, make sure all null data is filled before running sync with alter.

Do NOT use sync with "alter" on production, its insane. Use migrations instead.
