### ISSUE TITLE
`TypeError: Cannot read property 'field' of undefined` when findOrCreate encounters unique constraint violation and defaults has nonexistent attribute

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#8492]
## What are you doing?
```js
it('should error correctly when defaults contain a unique key and a non-existent field', function() {
  const User = this.sequelize.define('user', {
    objectId: {
      type: DataTypes.STRING,
      unique: true
    },
    username: {
      type: DataTypes.STRING,
      unique: true
    }
  });

  return User.sync({force: true}).then(() => {
    return User.create({
      username: 'gottlieb'
    });
}).then(() => {
    return expect(User.findOrCreate({
      where: {
        objectId: 'asdasdasd'
      },
      defaults: {
        username: 'gottlieb',
        foo: 'bar' // field that's not a defined attribute
      }
    })).to.eventually.be.rejectedWith(Sequelize.UniqueConstraintError);
});
```

## What do you expect to happen?
Test should pass

## What is actually happening?
Test fails with TypeError.

__Dialect:__ any (but tested in PG)
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ master
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/b505723927305960003dae2a8b64e1f291a5f927

**Comment by Mathiasduc** [comment]
https://github.com/sequelize/sequelize/commit/b505723927305960003dae2a8b64e1f291a5f927
Any chances for it to be merged into v4?

**Comment by nikiben** [comment]
I have the same issue. See stackoverflow [](https://stackoverflow.com/questions/55187960/sequelize-findorcreate-including-associates-cannot-read-property-field-of-u)
