### ISSUE TITLE
Difference between `dialectOptions.ssl=true` and `dialectOptions.encrypt=true`

### ISSUE THREAD

**Issue by chriddyp** [sequelize/sequelize#8497]
## What are you doing?
I'm working an open source SQL client: https://github.com/plotly/falcon-sql-client. 

I'm exposing some of the `dialectOptions` through a user interface.

For MSSQL, I see both the `dialectOptions.encrypt=true` property (used in connections to Azure) and the general `dialectOptions.ssl=true` which, from the documentation, seems to apply to every type of connection.

Searching through the code, I only see one reference to `ssl` and that's in creating the postgres query string: https://github.com/sequelize/sequelize/blob/c933bed708ba0b4b02a804ebc3eb4524bada54b6/lib/dialects/postgres/query-generator.js#L652

Is this correct? Is `dialectOptions.ssl` used in other connections? Ultimately, I'm wondering if I should expose this parameter for users attempting to connect to `mssql`.

Thank you!

__Dialect:__ mssql

**Comment by chriddyp** [comment]
aw @stale, that's sad! yeah, i'm still curious about this but it's not immediately pressing.

**Comment by sushantdhiman** [comment]
`dialectOptions` applies to database connectors like `pg` (postgres), `mysql2` and `tedious` (mssql), they are used when we are creating a connection for those dialects. Like [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L87-L90) and [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/connection-manager.js#L64-L66)

Yes, I think you should expose these options so user can configure low level configuration for connector libraries
