### ISSUE TITLE
Support for Presto or Guide to develop new Connector? 

### ISSUE THREAD

**Issue by gowtham-sai** [sequelize/sequelize#8507]
Can we connect to presto(connected to MySQL and Postgresql) instead of connecting to multiple sources (MySQL and Postgresql​) again and extracting data ?

Or can you provide documentation to develop new Connector?

**Comment by sushantdhiman** [comment]
@gowtham-sai If you wish to work on its support feel free to open a PR and maintainers will help you if you get stuck. But we dont have much time to implement a new dialect, it has to be contributed with a plan to support future work on that dialect.

**Comment by ali-habibzadeh** [comment]
Checking in 3 years later. Any updates here?
