### ISSUE TITLE
version3.30.4 UPDATE occur an error,  'val.replace is not a function'?

### ISSUE THREAD

**Issue by ruanjiayou** [sequelize/sequelize#8511]
## What are you doing?

I define Article model in a file. define it's method in ArticleBLL(like DAO in JAVA) in other file.
I can UPDATE an article running ArticleBLL. But when i require BLL file in other place it occured error!
val.replace is not a function
```js
// problem resolved so code isn't necessary
//in file: node_modules_sequelize@3.30.4@sequelizelibdialectsabstractquery-generator.js 
//after line 473, I added: if(typeof value == 'function') continue;
//problem resolved!
```

## What do you expect to happen?
_UPDATE data_

## What is actually happening?
_when i debug, i see function comment:  Escape a value (e.g a string, a number or a date). but the value is a function_

_Output, either JSON or SQL_

__Dialect:__ mysql
__Dialect version:__XXX
__Database version:__ 5.5.20
__Sequelize version:__ 3.30.4
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Sorry v3 is no longer supported.

val.replace is usually an issue where you pass incorrect type of data like Object instead of string.
