### ISSUE TITLE
how to query many to one relationship but return all rows on many side

### ISSUE THREAD

**Issue by reltubttam** [sequelize/sequelize#8513]
## What are you doing?
Using MySQL, I have two tables with a many to one relationship, these are setup with with ```hasMany``` and ```belongsTo``` relationships in sequelize.  I would like to use ```findAll()``` on the one side to find by filtering on the many side BUT then get all rows on the many side, not just those that match the condition.  

Additionally I would like to be able to select fields and sort on both tables.

I understand that currently (4.15.0) explicit sub queries are not supported, what is the recommended approach to this situation?  Is it possible for sequelize to generate a single query for this or is one query needed to get ids and a second to actually get the many side rows?

## What do you expect to happen?
If i have a 'houses' table and 'residents' table defined below, I would like to find houses in the city 'London' where residents with the job 'dentist' live, I also would like included all residents of these houses (including dentists and non-dentists).

houses:
* id
* createdAt
* updatedAt
* address
* city

residents
* id
* createdAt
* updatedAt
* houseId // link to house.id
* name
* job

Later I find too much data is returned and want to just receive the houses' address field and the residents' names.  I also decide to page through results using an offset and order by the houses' createdAt field.  How would this be achieved?

I would expect a sql query with the same effect as the following to be generated:
```sql
SELECT 
  `house`.`address`, 
  `residents`.`name` AS `residents.name`
FROM 
  `houses` AS `house`,
  `residents` AS `residents` 
WHERE `house`.`id` = `residents`.`houseId`
AND `house`.`city` = 'London'
AND `house`.`id` IN (
  SELECT
    `residents`.`houseId` 
  FROM 
    `residents` AS `residents` 
  WHERE `residents`.`job` = 'dentist'
)
ORDER BY `house`.`createdAt` DESC
LIMIT 4;
```

**Comment by mhombach** [comment]
Hi there,
please read the documentaion about queries in Sequelize as this should solve your question about query-filters and also query-filters for nested Models. Your questions about query-options like Offset and order should also be explained in detail within the documentation :)

**Comment by reltubttam** [comment]
@mhombach I could find no reference in the documentation for explicit sub queries.  With reference to issue #3961, perhaps `sequelize.dialect.QueryGenerator.selectQuery` is what you are referring to?  If there are notes on it's usage please let me know where :).

My understanding is still that sub queries are not supported (if this is not the case I will close this issue).  My question is if there is a recommended work around, can the interface to `selectQuery` above be considered stable for example.

**Comment by mhombach** [comment]
Let's say we have a model "User", a model "UserStatus" and botz are linked by:
`User.belongsTo(UserStatus);`.
You then can for example search for a `User` with specific name or password AND which `UserStatus` is `active`:
```js
User.findOne({
            where: {
                name: 'my name',
                password: 'my password'
            },
            include: [
                {
                    model: UserStatus,
                    where: {
                        name: 'active'
                    }
                }
            ] 
        })
```

If you read carefully you can see the 2nd "where"-clause within the included model. This does NOT search for some UserStatus with "active", it searches for a User that has a LINKED UserStatus, that is "active" (and the name/password from the 1st part).
You can find more information here (http://docs.sequelizejs.com/manual/tutorial/querying.html), search for "Relations / Associations", i hope this helps :)

**Comment by reltubttam** [comment]
I believe you will find that query does not return all rows on the many side.  Instead it will return the correct `User`'s but only the `UserStatus`'s with `name = active`.  This issue is concerned with how best to return all `userStatus`'s for each `User`.

For clarity the query in the issue is desired behaviour.  Not the following:
```sql
SELECT 
  `house`.`address`, 
  `residents`.`name` AS `residents.name`
FROM 
  `houses` AS `house`,
  `residents` AS `residents` 
WHERE `house`.`id` = `residents`.`houseId`
AND `house`.`city` = 'London'
AND `residents`.`job` = 'dentist'
ORDER BY `house`.`createdAt` DESC
LIMIT 4;
```

**Comment by mhombach** [comment]
My example was the other way around, my USER has ONE userstatus but ONE userstatus has MANY users :)
If you want, in my example, get all UserStatus-Entries with all users that have each status, then do i do the following;
```js
return UserStatus.findAll({
            include: [
                {
                    model: User
                }
            ]
        });
```
To accomplish that, i first need to link both models together:
```js
User.belongsTo(UserStatus);
UserStatus.hasMany(User);
```

Just so you believe me, this is the (censored) output i get from the above code:

```js
"statii": [
        {
            "id": 1,
            "name": "active",
            "niceName": "Aktiv",
            "beschreibung": "Aktiver Nutzer",
            "users": [
                {
                    "id": 3,
                    "name": "*user1*",
                    "password": "*pw1*",
                    "createdAt": "2018-01-15T17:54:37.214Z",
                    "updatedAt": "2018-01-15T17:54:37.610Z",
                    "userStatusId": 1
                },
                {
                    "id": 2,
                    "name": "*user2*",
                    "password": "*pw2*",
                    "createdAt": "2018-01-15T17:54:36.714Z",
                    "updatedAt": "2018-01-15T17:54:37.085Z",
                    "userStatusId": 1
                },
                {
                    "id": 1,
                    "name": "*user3*",
                    "password": "*pw3*",
                    "createdAt": "2018-01-15T17:54:36.302Z",
                    "updatedAt": "2018-01-15T17:54:36.571Z",
                    "userStatusId": 1
                }
            ]
        },
        {
            "id": 2,
            "name": "disabled",
            "niceName": "Deaktiviert",
            "beschreibung": "Deaktivierter Nutzer",
            "users": []
        },
        {
            "id": 3,
            "name": "deleted",
            "niceName": "Gelöscht",
            "beschreibung": "Gelöschter Nutzer",
            "users": []
        }
    ]
```

If you sitll can't get it to work, please give us details information-snippets on your model-definitions, your linking and your exact query :)
Hope i can help you ^^

**Comment by reltubttam** [comment]
That clarifies the relationship between your `User`'s and `UserStatus`'s, there is no need for a sub query in your example however.  Maybe if we try a simpler problem redefined in terms of your suggested models as follows:

How would you find all users with the same status as the user with `name` = `"*user1*"`?

Sequelize is a powerful tool and can be used a few ways to achieve this in a single DB call, my ACTUAL question is which is recommended as it is not documented.

I also am unclear what information-snippets and model-definitions you are requesting beyond what is in the original issue.
