### ISSUE TITLE
$or returns an AND in the SQL query

### ISSUE THREAD

**Issue by SavSamoylov** [sequelize/sequelize#8514]
When attempting to query the database using the `$or` operator using the code below, the SQL query turns that OR into an AND.

```js
function grabPosts(query, callback){

  db.post.findAll({
    where:{
      name: {$like: "%" + query + "%"},
      $or: { postbody: {$like: '%' + query + '%'}}
    },
    order: [['createdAt', 'DESC']]
  })
  .then(function(posts){

    if (posts != null){
      callback(posts)
    } else {
      callback(false)
    }

  });

}
```
_Output
Executing (default): SELECT `id`, `name`, `zip`, `location`, `postbody`, `address`, `phone`, `price`, `obo`, `notifications`, `archive`, `createdAt`, `updatedAt`, `userId`, `categoryId` FROM `posts` AS `post` WHERE `post`.`name` LIKE '%truck%' AND (`post`.`postbody` LIKE '%truck%') ORDER BY `post`.`createdAt` DESC;

__Dialect:__ mysql 
__Sequelize version:__ 4.7.5

**Comment by SavSamoylov** [comment]
I was able to get around the issue by placing both `name` and `postbody` inside the $or object.

```js
function grabPosts(query, callback){

  db.post.findAll({
    where:{
      $or: {
        postbody: {
          $like: '%' + query + '%'
        },
        name: {
          $like: '%' + query + '%'
        }
      }
    },
    order: [['createdAt', 'DESC']]
  })
  .then(function(posts){

    if (posts != null){
      callback(posts)
    } else {
      callback(false)
    }

  });

}
```
The SQL query became:
Executing (default): SELECT `id`, `name`, `zip`, `location`, `postbody`, `address`, `phone`, `price`, `obo`, `notifications`, `archive`, `createdAt`, `updatedAt`, `userId`, `categoryId` FROM `posts` AS `post` WHERE (`post`.`postbody` LIKE '%truck%' OR `post`.`name` LIKE '%truck%') ORDER BY `post`.`createdAt` DESC;

But I would still expect the first way I was doing it to have done the same.

**Comment by sushantdhiman** [comment]
2nd example is how $or works, these operators are not exact SQL. $and / $or both wrap condition given to them in respective operators
