### ISSUE TITLE
How to find all contacts where email doesn't exists (using include)

### ISSUE THREAD

**Issue by ShaktiDas** [sequelize/sequelize#8528]
I have 2 tables named Contacts and Emails. How to find the contacts where email doesn't exists? 
I want to use sequelize include instead of raw query. 

It works by raw query but I need model attributes also.
  
```
"SELECT * FROM Contacts
LEFT JOIN (
   SELECT SUM(id) as totalEmails, contactId FROM Emails GROUP BY ContactId) AS e
   ON e.contactId = Contacts.id 
WHERE e.totalEmails is Null";
```

**Comment by sushantdhiman** [comment]
Please use follow contribution guidelines and use issue reporter for bugs or feature requests only
