### ISSUE TITLE
Better Documentation With More Examples

### ISSUE THREAD

**Issue by lacivert** [sequelize/sequelize#8534]
## What are you doing?

Reading documentation to understand. As an example, I want to learn how to use options of hasOne() method. I see only one example without options.

```js
User.hasOne(Profile)
```

## What do you expect to happen?
_I think there should be many more examples for options, the second argument of the method. I think also there should be SQL outputs to make things easier to understand too_

## What is actually happening?
_There is no example for it, no SQL output either..._

_The rest of the docs are full of the same issue_

__Dialect:__ any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with master branch:__ No

**Comment by imankit** [comment]
Yes am facing the same issue with the documentation. There are not enough code examples to explain the method/constructor.

Thank you.
