### ISSUE TITLE
Add Model.decrement

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#8540]
## What are you doing?

Sequelize has `Model.increment`, `Model.prototype.increment` (AKA `instance.increment`), and `Model.decrement`. However, it does not implement `Model.prototype.decrement`.

```js
Model.increment('foo'); // works
Model.build().increment('foo'); // works
Model.build().decrement('foo'); // works
Model.decrement('foo'); // nope
```

## What do you expect to happen?
`Model.decrement` should be supported for symmetry with `increment`.

## What is actually happening?
`TypeError: decrement is not a function`

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ master
__Tested with master branch:__ Yes

**Comment by warriorpostman** [comment]
I ran into the same issue. Is decrement missing by design?

**Comment by Hazyzh** [comment]
it's troubled me too.

**Comment by felipe-muner** [comment]
Its not working yet?

i cant use .decrement?
