### ISSUE TITLE
getting validators directly from schema's to avoid mistakes

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#8546]
One of the things I deal with is that validations on the front end can differ from those defined in a sequelize model. 

This means, that someone can successfully submit a form without client side validation exceptions and then get an unspecified validation error back from the server. "Something went wrong" basically. 

Therefore I would like to retrieve my validations directly from sequelize schema's. 

One way would be to process a schema and use the defined validations during the front end validation process. I see some issues with this. For one, it would mean exposing my schema to a potential hacker. It feels unsafe.

Another approach would be to process validations schema's in a separate build process and extract validation rules from the schema. 

I'm curious how other people are dealing with this and what you think about the options.

**Comment by iamjochem** [comment]
hi,

regarding "feeling unsafe": you are already exposing the shape of your data in your client side app and the potential hacker can already view interaction with your API, therefore exposing structured information about how data structure, types and "basic" validation rules add little to the attack surface area - in short security through obscurity isn't.

I don't think it is technically [very] feasible to embed your models in your client code ... chances are they are way too tied into the server/node app's setup/resources (e.g. hooks, custom async validators, etc, etc) ... alot of that stuff is irrelevant to the client side and does not belong there ... indeed you shouldn't be exposing any of the implementation details that live behind your API.

So you need something that uses your Models to generate something structured, e.g. JSON-Schema definitions along side something that generates validation definitions that exist in your models.

with regard to JSON-Schema I used [this](https://github.com/chaliy/sequelize-json-schema) as inspiration to build a custom JSON-schema generator.

with regard to validation definitions you can expose the 3rd party validator that is included with sequelize (they use [this](https://github.com/chriso/validator.js)) in your client side code and write code to extract validator definitions from your models and (I assume) expose that data via your API, if you go down that route you will need to take the following into account:

1. custom validator functions can't (generally) be transported to the clientside (unless they are pure functions, which is not something you can [easily?] do programatically).
2. any RegExp instances can be transported but you'll need to write code to "encode" the regex and it's modifiers into something your can `JSON.stringify` (I choose to encode them as an array containing 2 strings)

With regard to the problem to unspecified validation errors, this is indeed a problem, currently sequelize ValidationErrorItems (found in the `errors` property of a ValidationError) tell you next nothing about which attribute, value, validator and/or validator-arguments triggered the error, therefore you have nothing on which to base a structured "error response" whose content you can then map to your UI ... but with a bit of luck #7557 will land soon and if so you'll have the structured data you need (you can fork sequelize and merge the branch relevant to #7557 and start using it today ... this is what I do)

rgds.
