### ISSUE TITLE
Cannot read/iterate 1 billion+ rows

### ISSUE THREAD

**Issue by nengine** [sequelize/sequelize#8550]
## What are you doing?
Trying to copy 1 billion+ rows from one table to another and it is freezing at the findAll() step.  Is there an efficient way to iterate over very large data sets?  Thanks a lot.

```js
function read() {
  Fill.findAll()
  .then(fills => {
    fills.forEach(fill => {
      console.log(JSON.stringify(fill));
    })
  })
}
```

## What do you expect to happen?
Output row data

## What is actually happening?
Nothing happens and freezes.

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version: 5.7.19
__Sequelize version:^4.13.2
__Tested with master branch: N/A

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by ggrimbert** [comment]
Try using offset and count to limit your query; use it in a loop to fetch the next records

**Comment by sushantdhiman** [comment]
@nengine MySQL cli client will be a better way to copy data from one table to another, why you want to use Sequelize to copy.

1 billion rows are just too much, I have never tried this. Even with benchmarks I have tried only 1500 findAll https://github.com/sushantdhiman/sequelize-benchmark

If you really want to to use Sequelize here, try batch your `findAll / create` in small segments with incremental use of limit and offset. So first get may be 10k rows, copy them, increase offset and continue

**Comment by nengine** [comment]
Thank you both @ggrimbert @sushantdhiman I will try that.
