### ISSUE TITLE
Create multiple INNER JOINS with Sequelize ORM

### ISSUE THREAD

**Issue by tmcyfy** [sequelize/sequelize#8559]
I'm using Sequelize ORM with Node.js and I can't get my head around on how to build the following query with it.

`SELECT b.* FROM mp_user a INNER JOIN mp_collection b on b.uid=a.id  WHERE ( a.id=44 )`

This query works and runs fine when I try it on DateGrip. The complication is that the Client model has no direct relation with Service, so when trying to do this :

```
MpUser.findAll({
        include: [{
          model: MpCollection,
          as: 'collection',
          required: true,
        }],
        where: {
          id: uid,
        },
        order: [[ 'Field', 'collection.*' ]],
      });
```
I get the following error :

`nodejs.SequelizeEagerLoadingError: mp_collection is not associated to mp_user!
`

How to build that query?

**Comment by joewoodhouse** [comment]
@tmcyfy  Did you work this out? Looking at a similar issue
