### ISSUE TITLE
Adding Association getOrCreateProject, getProjectById

### ISSUE THREAD

**Issue by shtse8** [sequelize/sequelize#8562]
Considering this association:
```
User hasMany Projects
```

ATM, we have `user.getProjects()` and `user.createProject()` in `User` models to get or create the association. It's better to have one more `user.getOrCreateProject()` and `user.getProjectById()`.

**Comment by sushantdhiman** [comment]
No I am afraid Sequelize dont create such mappings for now. But I would say it is fairly easy to achieve this with current getProject / createProject running inside an transaction as a class method

**Comment by shtse8** [comment]
@sunshinewyin I know it is fairly easy to achieve this with current get and create. but I would prefer to request this feature in sequelize.
