### ISSUE TITLE
Update documentation for order: group:

### ISSUE THREAD

**Issue by rusekr** [sequelize/sequelize#8563]
Hello!

Just migrated from 3.30.4 to 4.19.1. Fixed deprecated "order as string" places but in instruction it's still present:

http://docs.sequelizejs.com/manual/tutorial/models-usage.html#manipulating-the-dataset-with-limit-offset-order-and-group

Can you update this with actual variants of grouping/ordering?

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/28c6574da9e899be1e049a627fe637f3cac3639b
