### ISSUE TITLE
Sequelize is logging more than I need

### ISSUE THREAD

**Issue by BruceHem** [sequelize/sequelize#8573]
I'm using "debug" module here for logging. I just want to see the query being executed. But in the below image, it's showing more than I need. How can I remove the logging object in that image?

![screen shot 2017-11-01 at 3 36 33 pm](https://user-images.githubusercontent.com/15667259/32266918-f29cca32-bf1b-11e7-8ca9-5437aee9d09d.png)

**Comment by iamjochem** [comment]
hi,

the reason your are seeing this is that your logging function is part of the options object that is  
given your logging function (along with the message) in that context particular context.

I recommend that you don't use an instance of the `debug` module as your sequelize logging function:

1. `debug` is for debug output which is not exactly the same as logging
2. sequelize uses `debug` internally, you can include `sequelize:*` as part of your DEBUG env var specification and it will output stuff like this: `sequelize:sql:mysql executed(default) : SELECT ... ` (trying running with `DEBUG=*`, you might be surprised at the number of modules that use it!)

I recommend you check the docs for `options.logging` & `options.benchmark` [here](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html) ... basically you have to figure out some kind wrapper function for the "proper" logger of your choice and pass that into sequelize (I use `bunyan`).

hope that helps.

**Comment by BruceHem** [comment]
Thanks
