### ISSUE TITLE
Where does `.authenticate()` go?

### ISSUE THREAD

**Issue by aichholzer** [sequelize/sequelize#8579]
While trying to manage multiple database connections, I came across what looks like an issue to me. Calling `.authenticate()` somehow manages to hang the entire process. See the code below (tested on Node `V6.11.5` and `V8.9`):

```
const Sequelize = require('sequelize');
const instance = new Sequelize({
  database: 'local',
  username: 'local',
  password: 'local',
  dialect: 'postgres',
  logging: false,
  operatorsAliases: Sequelize.Op
});

Promise.all([instance.authenticate()]).then(() => {
  console.log('YES');
}).catch(() => {
  console.log('NO');
});
```

Run the above code; it will log `YES`, but the process does not exit, it remains running and can only be terminated via `ctrl+c`.

If you were to modify the `Promise.all()` to immediately resolve (or reject), like:

```
Promise.all([Promise.resolve(1)]).then(() => {
  console.log('YES');
}).catch(() => {
  console.log('NO');
});
```

then it will also log `YES` (as expected), but the process will exit this time (as there is nothing left in the event loop). This is the behavior I would expect from a promise.

Having that said, why is `.authenticate()` hanging on to the process?

**Comment by iamjochem** [comment]
try this:

```js
const Sequelize = require('sequelize');
const instance = new Sequelize({
  database: 'local',
  username: 'local',
  password: 'local',
  dialect: 'postgres',
  logging: false,
  operatorsAliases: Sequelize.Op
});

Promise.all([instance.authenticate()]).then(() => {
  console.log('YES');
  instance.close();
}).catch(() => {
  console.log('NO');
});
```

your promise chain is not the problem (`.authenticate()` is resolving), but deep down there is something managing DB connections and that in turn has active handlers that keep the event loop "alive" (most likely socket handlers) ... there are plenty of people that can/have explained the vent loop much better than I could: https://www.google.nl/search?q=nodejs+event+loop+explained (a couple of those top results are really worth a read)

**Comment by aichholzer** [comment]
@iamjochem -I know how the event loop works. Thank you for pointing that out but that was not my question. I also tried the `instance.close();` and it's not the solution either as the instance is basically useless after you close it.

**Comment by iamjochem** [comment]
@aichholzer - I can't image you fully understand the event-loop and also question why the process "hangs" - these two facts are, I think, somewhat mutually exclusive - no offense meant, I personally think the gritty details of node's event-loop are quite a difficult even though conceptually it is simple.

the fact is that `.authenticate()` is creating a DB connection which is most likely a stream wrapped in an EventEmitter which by way of it's/their active event handlers is keeping the event loop running ... and so the process won't exit. 

if you want the process to exit then use `.close()`, if not then there is no problem, the process is not hung it is merely "active", your snippet outputs "YES" showing that the call to `authenticate()` resolves (and so your code can continue and do whatever it's job is).

**Comment by aichholzer** [comment]
@iamjochem -The question was not about understanding the event loop. Again, it was about what `.authenticate()` is doing or -more broadly- what Sequelize is doing. A promise, once resolved, is out of the event loop, thus despite `.authenticate()` being resolved, there is still something that remains in the event loop and that is what I was asking about.

**Comment by iamjochem** [comment]
ack - I guess it's now clear that it's the underlying DB connections that `authenticate()` triggered are the reason the event-loop is still busy.

**Comment by rsshilli** [comment]
This shouldn't be closed, unless because it's a duplicate of https://github.com/sequelize/sequelize/issues/8468

Lots of people are getting stuck on this.
