### ISSUE TITLE
Proposal: Operator alias to function

### ISSUE THREAD

**Issue by Crusader4Christ** [sequelize/sequelize#8580]
Moving from waterline to sequelize. Waterline have default filter "contains" that work as `field LIKE "%value%"`. It will be fine to be able to do something like:

```js
operatorsAliases: {
    'contains': Op.function((value, field) => {return `${field} LIKE '%${value}%'`}),
    'startsWith': Op.function((value, field) => {return `${field} LIKE '${value}%'`}),
    'endsWith': Op.function((value, field) => {return `${field} LIKE '%${value}'`}),
}
```
So this way anybody can add own operators

**Comment by sushantdhiman** [comment]
Sorry no plan for this yet, want to keep operators simple for now

**Comment by Crusader4Christ** [comment]
@sushantdhiman can I create and add my own operators?
