### ISSUE TITLE
undefined fields in where options are treated as NULL

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#8583]
## What are you doing?
```js
User.findAll({
  where: {
    name: req.query.name
  }
});
```

## What do you expect to happen?
If `name` param wasn't passed, then this should find all users.

## What is actually happening?
`SELECT ... FROM users WHERE name IS NULL`, i.e. if a field in `where` is `undefined`, it's treated as `NULL`. 

This is especially confusing because it treats `undefined` in Javascript two different ways. If the value is present but `undefined`, then it's `NULL`. But if it's missing and `undefined`, then it's obviously not included in the WHERE clause at all. This means that consumers can't rely on `where.name !== undefined` to know whether a clause will be included. Instead you have to use the relatively obscure `in` operator.

__Dialect:__ any, but tested on Postgres
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ master
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
This is a point of discussion, I mostly agree `undefined != null`. This is going to be a breaking change.

We also need to find other API that may also treat `undefined` as `null`, I can think of `update` atleast

**Comment by gabegorelick** [comment]
Yeah this will be a huge breaking change. It may be wise to hide it behind an option first (something like `Model.find({where: {foo: undefined}, treatUndefinedAsNull: false})` and then change the default behavior in a future major version release.

**Comment by rokoroku** [comment]
I totally agree with `undefined != null` too.
We can also add a flag like `treatUndefinedAsNull` to the global configuration object. It won't cause a big change.

**Comment by leahciMic** [comment]
I think this might actually be a dangerous route...

Imagine this in a destroy scenario:

```js
comments.destroy({
  where: {
    id: comment.id,
    userId: user.id,
  },
});
```

Currently, if `comment.id` is `undefined` Sequelize wont destroy every comment belonging to a particular user. I think the current working way is much safer and a much saner default. 

I can't see any good reason to make this change.

If a `key` is defined but is `undefined`, then treat it like `null`. This change could result in unintentional loss of data through application errors and the like.

@gabegorelick Could you not write/ find a function that recursively strips undefined? Here is a poor man's version:

```js
function stripUndefined(obj) {
  return JSON.parse(JSON.stringify(obj));
}
```

And use it where necessary?

**Comment by gabegorelick** [comment]
> Currently, if comment.id is undefined Sequelize wont destroy every comment belonging to a particular user.

Fair point, but you could argue you still have this problem if `id` is omitted entirely. If you're really concerned about accidentally deleting everything, there are a lot of alternatives (`LIMIT`, enforcing filters in hooks or a DAO layer, etc).

> Could you not write/ find a function that recursively strips undefined? Here is a poor man's version

That is indeed what we do. But it's cumbersome to have to filter all our `where` options throughout the app when this should arguably be the default behavior.

**Comment by Alexsey** [comment]
Hm. How can you achieve this behavior? If I'll execute code
```js
const Sequelize = require('sequelize')

const sequelize = new Sequelize(
    'db', 'root', 'root', {
        host: 'localhost',
        dialect: 'mysql',
        pool: {max: 100, min: 0, idle: 10000},
        dialectOptions: {
            charset: 'utf8_general_ci',
        },
    }
)

;(async () => {
    await sequelize.authenticate()

    const User = sequelize.define('User', {
        id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
        name: {type: Sequelize.STRING, allowNull: true}
    })

    await sequelize.sync({force: true})

    await User.findAll({where: {name: undefined}})
})()
```
I'll get in MySQL
```sql
SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`name` = NULL;
```
And in SQL Server
```sql
SELECT [id], [name], [createdAt], [updatedAt] FROM [User] AS [User] WHERE [User].[name] = NULL;
```

Are you sure that issue is still actual?

**Comment by Alexsey** [comment]
@sushantdhiman @janmeier @eseliger could you, please, consider to include this in the v5 scope? Otherwise, we would need to wait for another year or so before v6

**Comment by eseliger** [comment]
I think it was more a bug than a feature, so I am totally up for fixing it for the v5 release. `undefined` is definitely not the same as `null` in javascript.
=> PRs welcome, if others agree as well!

**Comment by mschipperheyn** [comment]
Just ran into this bug. Would be in favor of a 4.x fix + option in sequelize options to activate the "fixed" behavior
