### ISSUE TITLE
instance.save() gives "has no comperator" Error

### ISSUE THREAD

**Issue by vladikus10** [sequelize/sequelize#8589]
Basically, I'm making changes to the client instance and in the and use the save() function to save yet getting an error.

```
client.save().then((result) => {
    console.log('Save was successful');
  }, (error) => {
    console.log(`Failed to save client with id = ${client.id}`);
    console.log(error);
  });
```

## What do you expect to happen?
I expect it to save or give a validation error.

## What is actually happening?
I get this: Error: Error: id and 1 has no comperator

 at Object._joinKeyValue (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2254:13)
 at Object.whereItemQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2091:17)
 at Utils.getComplexKeys.forEach.prop (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1944:25)
 at Array.forEach (native)
 at Object.whereItemsQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1942:35)
 at Object.whereQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1915:24)
 at Object.updateQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:367:19)
 at QueryInterface.update (/app/node_modules/sequelize/lib/query-interface.js:936:37)
 at Promise.try.then.then.then (/app/node_modules/sequelize/lib/model.js:3593:56)
 at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
 at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
 at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
 at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
 at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
 at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
 at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
 at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
 at runCallback (timers.js:672:20)
 at tryOnImmediate (timers.js:645:5)
 at processImmediate [as _immediateCallback] (timers.js:617:5)

__Dialect:__ mysql
__Database version:__ 5.7.17
__Sequelize version:__ v4.22.2
__Tested with master branch:__ Yes

**Comment by alditis** [comment]
Extract of code:

```
  _joinKeyValue(key, value, comparator, prefix) {
    if (!key) {
      return value;
    }
    if (comparator === undefined) {
      throw new Error(`${key} and ${value} has no comperator`);
    }
    key = this._getSafeKey(key, prefix);
    return [key, value].join(' '+comparator+' ');
  },
```
Your model used associations? How?

**Comment by vladikus10** [comment]
@alditis No associations, it's actually the only model/table in the database currently.

**Comment by sushantdhiman** [comment]
Can you show me a proper example for what values or under which condition this error occurs.

There are considerable numbers of tests running on save which indicate you might be doing something wrong.

**Comment by vladikus10** [comment]
@sushantdhiman For simplicity, I made a simple model define (unlike using using the current singleton, to see if something is with that), but I get the same issue: 

```
  let Sequelize = require('sequelize');
  let seq = new Sequelize(process.env.DB_NAME, process.env.DB_USERNAME, process.env.DB_PASSWORD, {host: process.env.DB_URL, dialect: 'mysql'});
  seq.authenticate().then((result) => {
    clientModel = seq.define('client', {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            allowNull: false,
            autoIncrement: true
        },
        messenger_id: {
            type: Sequelize.STRING,
            allowNull: false
        },
        first_name: {
            type: Sequelize.STRING
        },
        last_name: {
            type: Sequelize.STRING
        },
        profile_pic: {
            type: Sequelize.STRING
        },
        city: {
            type: Sequelize.STRING
        },
        street: {
            type: Sequelize.STRING
        },
        house_number: {
            type: Sequelize.STRING
        },
        flat: {
            type: Sequelize.STRING
        },
        state: {
            type: Sequelize.STRING,
            defaultValue: "initial"
        }
    }, {
      underscored: true,
      indexes: [
        {
          unique: true,
          fields: ['messenger_id']
        }
      ]
    });
    seq.sync({force: true}).then((result) => {
      console.log("Database synced at: " + new Date());

    }, (error) => {
      console.log("Error accured during syncing: ", error);
    });
  }, (error) => {
    console.log(error);
  });
```
Note, clientModel is defined before, so I create the client after receiving the message from messenger and receiving the result from the Facebook profile API: 

```
if (!error && response.statusCode == 200) {
	let result = JSON.parse(body);
	clientModel.create({
		messenger_id: senderID,
		first_name: result.first_name,
		last_name: result.last_name,
		 profile_pic: result.profile_pic
	}).then((client) => {
                console.log(client);
		handleMessage(client);
	}, (err) => {
		console.log(err);
	});
}
```
I did put the result client in to console and indeed it created the a new instance correctly. So after the message is processed, what should happen is that the client's state needs to change so at the end before sending the message I do something like this:

```
client.set('state', 'idle');
client.save().then((result) => {
    console.log('Save was successful');
 }, (error) => {
    console.log(`Failed to save client with id = ${client.id}`);
    console.log(error);
});
```
And that's where I get the error. Tried using **update** instead, same thing. Interestingly, I started to get the same error with the find functions as well, like when I do:

```
clientModel.findOne({where: {messenger_id: event.sender.id}}).then((client) => {
        if(!_.isNull(client)){
            handleMessage(client, message);
        }
        else {
            createNewClient(event.sender.id, message);
        }
    }, (error) => {
        console.log('Error when finding a client');
        throw error;
});
```
I get this error:
`Error: messenger_id and '1638597395723496' has no comperator`
I tried using **eq** from Sequelize.Op, then I get:
`Cannot ready property IndexOf of undefined`
I used the following structure:
```
const {eq} = require('sequelize').Op
clientModel.findOne({where: {messenger_id: {[eq]: event.sender.id}}})...
```
However, it does find fine if I don't use **where** (meaning it finds whatever it can and not what I want)

**Comment by vladikus10** [comment]
One thing I just don't understand, is why that error appears on the **save** function? Shouldn't it automatically use the **=** comperator on the primary key (in this case **id**) ?

**Comment by sushantdhiman** [comment]
I am afraid this example is still very broad, Can you at least show what SQL queries are executing and what data I should supply to replicate this issue?

Also there are so many un-handled promises, I hope you are taking care of that in actual code and this is just a sample code.
