### ISSUE TITLE
Solve circular references

### ISSUE THREAD

**Issue by hytromo** [sequelize/sequelize#8595]
## What are you doing?
If I have 2 models, a `Client` and a `Location`, if the `Client` model tries to reference the `Location` and the `Location` tries to reference the `Client`, there's a problem.

What I'm trying to do is declare the models used by each model outside the model's methods, so the methods don't have to do `sequelize.import` all the time.

So, something like that:
```js
// location.js 
module.exports = function (sequelize, DataTypes) {
    // variable to be used in Location methods
    let Client = sequelize.import('./client');
    let Location = sequelize.define('locations', { schema here });
    Location.belongsTo(Client, { foreignKey: 'client_id', onDelete: 'restrict' });
    ....
    Location.createSafe = function (data) {
        // no need to do Client = sequelize.import('./client') again!
        Client.doSomething();
    }
}
```

## What do you expect to happen?
I expect to be able to use the models without having to re-import them each time inside each Model method.

## What is actually happening?

I have a circular dependency problem and I get
```
RangeError: Maximum call stack size exceeded
```

## What I've tried

I've tried lazy loading the models using a `Proxy`

```js
module.exports = function (sequelize, path) {
    let loadedObj;
    return new Proxy({}, {
        get: function (obj, prop) {
            if (!loadedObj) {
                loadedObj = sequelize.import(path);
            }
 
            return loadedObj[prop];
        }
    });
}
// used like let Client = lazyLoad(sequelize, '/path/to/client.js');
```

In the few tests I've done this seems to work OK, but is there a guarantee that this is going to work?

__Dialect:__ any
__Sequelize version:__ 4.20.3
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Please study https://github.com/sequelize/express-example to see how to manage multiple models situation. You are falling for classical cross reference
