### ISSUE TITLE
Instance method for getting all attributes?

### ISSUE THREAD

**Issue by flockonus** [sequelize/sequelize#86]
Hello, your ORM is awesome, really.

Now, to business..

when I first ran `.attributes` and got a Array of fields I was kind like.. _wtf?_ so, I am adding this function to all my models, so, i'd suggest adding this function to core. // Or making a plugin out of it should be a better option?

```
/**
* @type {Object}
* Map all attributes of the registry
* (Instance method useful to every sequelize Table)
* @this {SequelizeRegistry}
* @return {Object} All attributes in a Object
*/
var map_attributes = function() {
  var obj = new Object(),
      ctx = this;
  ctx.attributes.forEach(
    function(attr) {
      obj[attr] = ctx[attr];
    }
  );
  return obj;
};

db.define('user',
{ .. },
{
  instanceMethods: {
    mapAttributes: map_attributes
  }
}
```

Anyway, still feels some strange behavior to `.attributes`, it feels like a classMethod `.fields` for me

**Comment by rsshilli** [comment]
To help the next person, modelInstance.attributes is an array and modelInstance.dataValues is a map of key to value pairs.  There's no modelInstance.values.

I wrote this fun little program to figure out how to do it:

    CommonDB.User.findOne({where: {id: 124}}).then(function (user) {
        console.log("Found user with " + user.id);
        console.log("Values = " + CommonUtils.stringify(user.dataValues));
        console.log("Attributes = " + CommonUtils.stringify(user.attributes));
        for(let att in user.dataValues) {
            console.log("Found att = " + att);
        }

        for(let func in user) {
            console.log("Found func = " + func);
        }
    });

And the output I got was:

    Executing (default): SELECT `id`, `firstName`, `lastName`, `email`, `group`, `title`, `role`, `lastLogin`, `enabled`, `status`, `username`, `createdAt`, `updatedAt`, `companyId` FROM `users` AS `user` WHERE `user`.`id` = 124;
    Found user with 124
    Values = {
            "id": 124,
            "firstName": "Ryan",
            "lastName": "Rocket",
            "email": "qdbvision-test@mytest.com",
            "group": null,
            "title": null,
            "role": "Administrator",
            "lastLogin": "2017-03-30T17:04:57.000Z",
            "enabled": true,
            "status": "CONFIRMED",
            "username": "qdbvision-test",
            "createdAt": "2017-03-30T16:32:50.000Z",
            "updatedAt": "2017-03-30T17:04:57.000Z",
            "companyId": 76
    }
    Attributes = [
            "id",
            "firstName",
            "lastName",
            "email",
            "group",
            "title",
            "role",
            "lastLogin",
            "enabled",
            "status",
            "username",
            "createdAt",
            "updatedAt",
            "companyId"
    ]
    Found att = id
    Found att = firstName
    Found att = lastName
    Found att = email
    Found att = group
    Found att = title
    Found att = role
    Found att = lastLogin
    Found att = enabled
    Found att = status
    Found att = username
    Found att = createdAt
    Found att = updatedAt
    Found att = companyId
    Found func = dataValues
    Found func = _previousDataValues
    Found func = _changed
    Found func = $modelOptions
    Found func = $options
    Found func = hasPrimaryKeys
    Found func = __eagerlyLoadedAssociations
    Found func = isNewRecord
    Found func = _customGetters
    Found func = _customSetters
    Found func = validators
    Found func = _hasCustomGetters
    Found func = _hasCustomSetters
    Found func = rawAttributes
    Found func = attributes
    Found func = _isAttribute
    Found func = Model
    Found func = $Model
    Found func = getCompany
    Found func = setCompany
    Found func = createCompany
    Found func = where
    Found func = toString
    Found func = getDataValue
    Found func = setDataValue
    Found func = get
    Found func = set
    Found func = setAttributes
    Found func = changed
    Found func = previous
    Found func = _setInclude
    Found func = save
    Found func = reload
    Found func = validate
    Found func = hookValidate
    Found func = update
    Found func = updateAttributes
    Found func = destroy
    Found func = restore
    Found func = increment
    Found func = decrement
    Found func = equals
    Found func = equalsOneOf
    Found func = setValidators
    Found func = toJSON

**Comment by sahiljain2497** [comment]
Object.keys(ModelName.rawAttributes)
