### ISSUE TITLE
Doc is out

### ISSUE THREAD

**Issue by BrunoQuaresma** [sequelize/sequelize#8601]
Hi, when I try access the doc http://docs.sequelizejs.com/ this error is displayed 

```
Oops!
SOMETHING WENT WRONG
Looks like someone forgot to renew their DNS hosting service. If you are the administrator for this domain, please log into your DNS Made Easy account and renew your services. If you do not have a DNS Made Easy account, please contact your hosting provider.
```

**Comment by nmihaica** [comment]
[Google Cache] (http://webcache.googleusercontent.com/search?q=cache:http://docs.sequelizejs.com/)

**Comment by MatthewAry** [comment]
@nmihaica Thanks for the mirror link.

**Comment by Parasin** [comment]
Looks like it's back up: http://docs.sequelizejs.com/manual/
