### ISSUE TITLE
How to update the field nested in jsonb? 

### ISSUE THREAD

**Issue by jettangs** [sequelize/sequelize#8604]
## What are you doing?

```js
//postgres
const Ployee = sequelize.define('ployee', {
    name: { type: Sequelize.STRING },
    age: { type: Sequelize.INTEGER },
    child: { type: Sequelize.JSONB },
}, {
    tableName: 'ployee',
    timestamps: false
});

await Ployee.insert({ child: { name: 'john', age: 12 }} // id=1

//after update: {child: { age: 10}}
await Ployee.update({ 'child.age': 10 }},{ where: { id: 1 }})

//doesn't work
await Ployee.increment(['child.age'], { by: 1, where: { id: 1 } })

//work, but a single one.
let ployee = await Ployee.findOne({ where: { id: 1 }})
ployee.set({ 'child.age': 15 })
await ployee.save()
```

## What do you expect to happen?
update: {child: {name: 'john', age: 10}}
increment: {child: {name: 'john', age: 13}}

## What is actually happening?
update will reset the field, the increment does't work.

**Comment by emclab** [comment]
//work, but a single one.
      let ployee = await Ployee.findOne({ where: { id: 1 }})
      ployee.set({ 'child.age': 15 })
      await ployee.save()

This is the one working for me. ployee.update overwrites the whole JSONB field and can only be used when the whole field is updated.

**Comment by igordeoliveirasa** [comment]
how to delete age, for example?

**Comment by igor-radivojevic** [comment]
@igordeoliveirasa 
Set it to undefined. Just tried it and it works.
`ployee.set({ 'child.age': undefined })`

**Comment by kasvith** [comment]
This need to be added to docs

**Comment by 11AA8R4** [comment]
exemple : model.**yourJsonB**.userName

```
model.yourJsonB.userName = "Lisa"  // traditional prop change
model.changed("yourJsonB",true)   //< forces sequelize to understand this json has be updated
model.save()
```

I found the res on the docs:
https://sequelize.org/master/manual/upgrade-to-v6.html

**Comment by mariusa** [comment]
The best solution would be to use jsonb_set(), not to read the field first. Does this work with sequelize?

**Comment by matias-gmg** [comment]
> exemple : model.**yourJsonB**.userName
> 
> ```
> model.yourJsonB.userName = "Lisa"  // traditional prop change
> model.changed("yourJsonB",true)   //< forces sequelize to understand this json has be updated
> model.save()
> ```

You need to add `await` before `model.save()`.
