### ISSUE TITLE
can't pass authentication on PostgreSQL. 

### ISSUE THREAD

**Issue by SuperManEver** [sequelize/sequelize#8606]
I try to authenticate on PostgreSQL using a code with sequelize.

the code itself from example usage:

```
const sequelize = new Sequelize('test_db', 'postgres', 'some_password', {
  host: 'localhost',
  dialect: 'postgres',

  pool: {
    max: 5,
    min: 0,
    idle: 10000,
  },
});

sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });
```

it should be very straightforward. I use account/password which I use for login to CLI session on PostgreSQL, but I get `password authentication failed for user "postgres"` even for a correct combination of login/password.

I guess a problem with my PostgreSQL configuration and I think I don't have enough expertise with PostgreSQL to solve it on my own. 

So I need your help!

here is a list of DBs I have in PostgreSQL
![image](https://user-images.githubusercontent.com/2178264/32501926-28f5b9c0-c3fb-11e7-9e04-c0f51ef79b01.png)

and here is my pg_hba.conf
![image](https://user-images.githubusercontent.com/2178264/32501987-54889b7a-c3fb-11e7-96d6-1bd03db36d5b.png)

**Comment by sushantdhiman** [comment]
Please use this issue tracker for reporting bugs or feature requests only. For any general questions use Stackoverflow or [Slack](sequelize.slack.com)
