### ISSUE TITLE
get error when accessing belongsTo association

### ISSUE THREAD

**Issue by kasinau** [sequelize/sequelize#8607]
## What are you doing?
I'm using sequelize in a node app, having the following relations:

```js
Department = sequelize.define('Department', {
id_department: {
type: DataTypes.INTEGER,
allowNull: false,
primaryKey: true,
},
.
.
.
}, {
tableName: 'department',
timestamps: false,
});

Department.associate = (models) => {
    Department.hasMany(models.User, {
        foreignKey: 'id_department',
        as: 'users',
    });
};





User = sequelize.define('User', {
    id_user: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
    },
    username: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    id_department: {
        type: DataTypes.INTEGER,
        allowNull: false,
    },
    .
    .
    .
}, {
    tableName: 'user',
    timestamps: false,
});

User.associate = (models) => {
    User.belongsTo(models.Department, {
        foreignKey: 'id_department',
        onDelete: 'CASCADE',
    });
};
```

## What do you expect to happen?
Here I have a problem: When I try to access the user's department:

```
User.getDepartment().then(function (result) { return result; });
```

I get the following error: "User.getDepartment is not a function"

Accessing the users from a department:

```
users = Department.getUsers(filter).then(result => { return result; });
```

seems to work ok, and this problem seems to appear for "belongsTo" relation, because in my app I have more entities with different relation, and for each "hasMany" works ok, but trying to retrieve "belongsTo" relation throws the mentioned error.

Please, any help is appreciated, thank you!

## What is actually happening?
Accessing:

```
User.getDepartment().then(function (result) { return result; });
```

I get the following error: "User.getDepartment is not a function"

__Dialect:__ mysql
__Dialect version:__ MySQL 5.5.57-0ubuntu0.14.04.1
__Database version:__ MySQL 5.5.57-0ubuntu0.14.04.1
__Sequelize version:__ 4.15.0
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by mcmlxxxiii** [comment]
Getting "is not a function" in your examples is absolutely normal. It seems that what's happening is just a slight confusion about the class/instance methods usage. The methods you're trying to use are added to instance level while you're trying to use them on class ones.

Try this instead: 
```javascript
User.get(1).
    then(user => user.getDepartment()).
    then(department => { /* your code */ });
```

And this:
```javascript
Department.get(1).
    then(department => department.getUsers()).
    then(users => { /* your code */ });
```
