### ISSUE TITLE
Dont log options to custom log function (other then console.log) by default

### ISSUE THREAD

**Issue by rusekr** [sequelize/sequelize#8615]
Hello!
After going to version 4 logging through debug module prints not only query but large object after.

Found 
https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1043 
that you cut this object for "console.log" function.

Can I cut it with some options instead of wrapping debug to something like:
```  
var debug  = require('debug')('cloud-candy:DB');
  function seqLog () {
    var args = Array.prototype.slice.call(arguments, 0);
    args.splice(args.length-1, 1);
    return debug.apply(debug, args);
  }
```

p.s. don`t understand why it was needed to print options with every query anyway.

**Comment by iamjochem** [comment]
the options _can_ be very important to understanding what is going on (e.g. transaction/attribute/where clause info), as such they should be made available to the logging function (it is impossible to say from within sequelize whether someone does or does not want this information in any particular context). 

the `debug` module is for "debugging", I recommend not using it as the implementation for your sequelize logging function ... sequelize logging function is meant for logging not debugging.

sequelize uses the `debug` module internally so there is no real reason to define a sequelize logging function for the purpose of development work ... you can simply set your DEBUG env var to something like `cloud-candy:*,sequelize:*`

(I made the [same argument here](https://github.com/sequelize/sequelize/issues/8573))

if you do keep you `debug` based logger then performing the arguments slice as you showed is the right way to go ... it keeps you in control (for that one time where you do want to revert to dumping the options

> peronally I would argue that dropping `options` if the logger is `console.log` is not the right thing to do. I do think that sequelize should be dropping the `logging` property from the `options` object passed to the logger because the logger *is* the `logging` property instance (it seems completely pointless to have it log itself!)

**Comment by rusekr** [comment]
Mmmm. I don`t suggest completely remove logging of options - just to make its logging configurable.
My arguments:
We are using debug module as general purpose logger setting logging scopes where needed.
We need our prefix in logs to filter instead of 'sequelize.*' (sequelize is wrapped in our project)
We use --inspect to debug our code, not console. In console for us in some cases queries are enough.
It is no harm to make logging of additional data (like options) switchable off through config like 
{ loggingOptions: true|false} or make it more sensitive with config like { loggingFilter: ['query', 'options', 'transactions' ...]} with defaults you like

**Comment by rusekr** [comment]
And main argumet: it has been cut for "console.log" (default logging function) and when people try to use its own logger and it logs more info then default - seem very strange.
