### ISSUE TITLE
sequelize does not work with webstorm autocomplete/highlighting 

### ISSUE THREAD

**Issue by skn3** [sequelize/sequelize#8616]
For example:
![image](https://user-images.githubusercontent.com/324644/32657523-fa4ae0d6-c60d-11e7-878b-d4c8f48efb26.png)

I have tried installing the available lib stubs to no avail. Is the format of the sequelize inline docs not compatible? Any advice please...

**Comment by AzureusSme** [comment]
+1

**Comment by micksatana** [comment]
Can you show the declaration line of `Sequelize`?

```
const Sequelize = require('sequelize');

Sequelize.DataTypes.STRING; // Auto-completion is working here
```

When I code as above, I have auto-complete.
I'm using PHPStorm, which based on the same IDE engine as WebStorm.

**Comment by skn3** [comment]
![image](https://user-images.githubusercontent.com/324644/35639787-41dd2478-06b3-11e8-949d-9ab870382122.png)

Doesn't work for me...

**Comment by essana3** [comment]
same problem here

**Comment by ImaiM** [comment]
I had same problem on VSCode and it have been solved for me.

before:
```javascript
const Sequelize = require('sequelize');
```
after:
```javascript
const Sequelize = require('sequelize').Sequelize;
```
try:)
