### ISSUE TITLE
Insertion with raw queries doesn't return any value

### ISSUE THREAD

**Issue by sberlinches** [sequelize/sequelize#8618]
Hi there,

I've had to change the handy method "create" for the "query" one (to throw raw queries). Now the rows are still being persisted, but I do not get any value back.

```js
Model.method = function(object) {
    // return Model.create(object);
    return Model.sequelize.query(
        "INSERT INTO table (id, column) VALUES (DEFAULT, :column);",
        {
            model: Model,
            replacements: {column: object.column},
            type: sequelize.QueryTypes.SELECT
        }
    );
};
```
Is there something that I am missing?

Dialect: mysql
Sequelize version: 4.19.0

**Comment by sushantdhiman** [comment]
INSERT queries doesn't return records created, they only return id for inserted record (dialect dependent). You have to manually do SELECT on last inserted id, or write a stored procedure to solve this issue

**Comment by DiegoRBaquero** [comment]
@sushantdhiman How can I get the ID? I've tried setting the type to RAW, SELECT, INSERT, using plain, using raw, I always get an array with only the affected rows number.

**Comment by sushantdhiman** [comment]
@DiegoRBaquero If you pass no type at all you should receive raw row packet, which should contain `insertId` or something like that (dialect specific)
