### ISSUE TITLE
'order by' not working in select statement with sequelize postgres

### ISSUE THREAD

**Issue by shajunr88** [sequelize/sequelize#8626]
The following is the code using order by in postgres and sequelize
`Grid.findAll({where: {view_id: view_id}},{order: [[{model: Grid},'block_id','ASC']]})
.then((grids)=>{
    const resObj = grids.map(grid => {
    return Object.assign(
      {},
      {
        block_id: grid.block_id
        title: grid.title,
        x: grid.x,
        y: grid.y,
        w: grid.w,
        h: grid.h,
        resizable: grid.resizable,
      })
    });
     res.json(resObj);

})`

But the query executing does not contain the order by syntax.
`SELECT "id", "view_id", "block_id", "x", "y", "w", "h", "resizable", "title", "created_at", "updated_at" FROM "grids" AS "grids" WHERE "grids"."view_id" = '1';`

**Comment by pareshvpatil** [comment]
this issue is still there,
not able to use **order by** in postgreSQL

**Comment by mazaharul** [comment]
**order by** in postgreSQL is not working at all, I have tried with { override: true } too still nothing changes in the response.
`Listings.findAll({
        where: {
            status: {
                [Op.eq]: null
            },
            vin: {
                [Op.ne]: null
            }
        },
        order: [
            ['platform', 'ASC']
        ],
    },{ override: true })`

**Comment by muhammadafifpratama** [comment]
STILL NOT WORKING THE EXECUTING QUERY does not contain the order by syntax.
