### ISSUE TITLE
model.findAll({where: { field: {eq: 'value'} }) not valid

### ISSUE THREAD

**Issue by nyenye** [sequelize/sequelize#8627]
I know that model.findAll({where: { field: 'value' } }) defaults to using equal. Yet it's giving me a headache when trying to use it with GraphQL, given that it doesn't support UNIONs as argument. (Either A or B would be a Union).

Is there a specific reason for disabling the object notation ( { eq: 'value'} ) for equal comparisons?

Can't both be implemented?

**Comment by sushantdhiman** [comment]
Can you elaborate, Do you want automatically handling arrays if passed to `eq` ?

**Comment by nyenye** [comment]
@sushantdhiman Nothing of the sort, just the same functionality that Model.findAll({where: { field: 'value' } }), has but with another syntax; Model.findAll({ where: { field: { eq: 'value' } } }).

The reason is so people who use Sequelize with GraphQL, could benefit from this standard syntax, given the strong typed nature of GraphQL args. My use case is when doing quries with filtering.

Thanks!

**Comment by sushantdhiman** [comment]
So what is the difference between `eq` and `direct property` that you want to be common?

**Comment by nyenye** [comment]
Basically, it doesn't work with `eq`.

From the docs: `where` generally takes an object from `attribute:value` pairs, where value can be primitives for equality matches or keyed objects for other operators.

**Comment by sushantdhiman** [comment]
So you are saying `name: name` works but `{ name: { eq: name } }` doesnt?

**Comment by nyenye** [comment]
Yes, and if there is a way for it to work?

**Comment by sushantdhiman** [comment]
But `$eq` is supported, you want us to support `eq` as well?

**Comment by nyenye** [comment]
Supporting the `eq`

![image](https://user-images.githubusercontent.com/11387253/33062514-d77a123a-ce9f-11e7-9445-d907b151b545.png)

**Comment by sushantdhiman** [comment]
Asking again, you want us to support `eq` beside `$eq` as well

**Comment by nyenye** [comment]
Edited sorry,

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-aliases

You can map `eq` to be equal to `Op.eq` and use that throughout your code

**Comment by nyenye** [comment]
That makes so much sense... Sorry about all the confusions with graphql. Thanks again!
