### ISSUE TITLE
n:m relationship error when using uuidv1 for default id.

### ISSUE THREAD

**Issue by solemidas** [sequelize/sequelize#8630]
## What are you doing?
I have two models that have a n:m relationship,  I would like to use uuids for my ids, but it fails on creating the joint table. I get this message from my express server. link to my repo is [here](https://github.com/solemidas/sequelize-typescript-express)
```js
// my Team model
export default (sequelize, DataTypes) => {
  const team = sequelize.define('team', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV1,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING,
      unique: true,
    },
  });

  team.associate = (models) => {
    team.belongsToMany(models.user, {
      through: 'member',
      foreignKey: 'id',
      as: 'teamId',
    });
    team.belongsTo(models.user, {
      foreignKey: 'owner',
    });
  };

  return team;
};

// My user model

export default (sequelize, DataTypes) => {
  const user = sequelize.define('user', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV1,
      primaryKey: true,
    },
    username: {
      type: DataTypes.STRING,
      unique: true,
    },
    email: {
      type: DataTypes.STRING,
      unique: true,
    },
    password: DataTypes.STRING,
  });

  user.associate = (models) => {
    user.belongsToMany(models.team, {
      through: 'member',
      foreignKey: 'id',
      as: 'userId',
    });
  };

  return user;
};


```

## What do you expect to happen?
I expected to have my members table to be created

## What is actually happening?
Executing (default): DROP TABLE IF EXISTS "member" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "member" ("id" UUID  SERIAL  REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONENOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Failed to connect syntax error at or near "SERIAL".

__Dialect:__ postgres
__Dialect version: 7.4.0
__Database version: 9.6
__Sequelize version: 4.22.6
__Tested with master branch:__ yes

**Comment by scotdalton** [comment]
@solemidas, I had a similar issue and upgrading the underlying `pg-types` module fixed it.

**Comment by DanFerro** [comment]
I believe in the documentation somewhere you must define the through model, i.e member and then reference the model for each of the n:m relations vs string. I believe this is necessary if you are using anything other than int auto increment.

**Comment by sushantdhiman** [comment]
You need to define `member` model with

```js
id: {
  type: DataTypes.UUID,
  defaultValue: DataTypes.UUIDV1,
  primaryKey: true,
}
```

As you are using non increment primary key type UUID, its important to define it in that way. Sequelize by default try to add a Integer based auto increment primary key, which will fail for UUID
