### ISSUE TITLE
Nested eager loading sequelize ( belongsTo and belongsToMany in a same query )

### ISSUE THREAD

**Issue by getechdev** [sequelize/sequelize#8633]
__NodeJS:__ 8.6.0
__Express:__ 4.15.2
__Dialect:__ mysql 
__Database version:__ 5.1.17
__Sequelize version:__ 3.30.0

Hello,

 I'm facing the following "simple" use-case : ( Don't pay attention to table name ;)) I have this model defined :

```js

tableName: 'Child',
classMethods: {
    associate: function(models) {
        this.belongsToMany(models.Parent, { as :{ singular: 'child',                 plural: 'children' }, through: 'Parent_Child'} );

        this.belongsTo(models.Son, {foreignKey : 'fkSon', as :'son' });
    }

```
I want to get in a same query all related models to Child. My model definition works fine. I can get Parent related to Child and Son related to Child but not both.

Here the query I try to run unfortunately (inspired by sequelize doc http://docs.sequelizejs.com/manual/tutorial/models-usage.html#nested-eager-loading

I have the following error : 

Many Thanks in advance :)

## What are you doing?

```js
models.Child.findAll({
include : [{model : models.Son, as:'son',
include : [{model : models.Parent, as : 'children', through:    'Parent_Child' , require : true}]

}]
```

## What do you expect to happen?

Something like :
```
[
    {
       "label"  : "tioo"
        "son": [{
            "Son":
              { 
                "label": "tito"
                }
              }],
        "children": [
            {
                
                "Parent": {
                    "label": "toto"
                    
                }
            },
            {
                
                "Parent": {
                    "label": "titi"
                    
                }
            }
        ]
    }
  ] 
```

## What is actually happening?

```
Error: Parent (children) is not associated to Son!
```

Thanks a lot

**Comment by sushantdhiman** [comment]
You need to define reverse relationship as well

**Comment by jesuslas** [comment]
woooowwww impresionante respuesta @sushantdhiman
