### ISSUE TITLE
Deleting a model instance (belongsToMany) does not delete the associated record in through table

### ISSUE THREAD

**Issue by mcranston18** [sequelize/sequelize#8636]
## What you are doing?
Deleting a model instance that has a `belongsToMany` relationship. The model instance is correctly deleted but I would expect the record in the "through" table to be deleted. [Working code example](https://github.com/mcranston18/sequelize-has-many/blob/master/belongs-to-many.js)

## Steps to reproduce
1. Create models and `belongsToMany` relationship
```
  const Film = db.define('film', {
    id: {
      type: Sequelize.UUID,
      defaultValue: Sequelize.UUIDV4,
      primaryKey: true
    },
    name: {
      type: Sequelize.STRING
    }
  }, {
    underscored: true
  });

  const Festival = db.define('festival', {
    id: {
      type: Sequelize.UUID,
      defaultValue: Sequelize.UUIDV4,
      primaryKey: true
    },
    name: {
      type: Sequelize.STRING
    }
  }, {
    underscored: true
  });

  const FilmFestival = db.define('film_festivals', {}, {});

  Film.belongsToMany(Festival, {
    through: FilmFestival,
    foreignKey: {
      name: 'film_id',
      allowNull: false
    },
    onDelete: 'CASCADE'
  });

  Festival.belongsToMany(Film, {
    through: FilmFestival,
    foreignKey: {
      name: 'festival_id',
      allowNull: false
    },
    onDelete: 'CASCADE'
  });
```

2. Create and associate model instances
```
models.Film.create({name: 'Aviator'}).then(...);
models.Festival.create({name: 'TIFF'}).then(...);
filmInstance.setFestivals([festivalInstance]).then(...)
```

3. Delete model instance
```
// get film instance of just created film
filmInstance.destroy().then(...);
festivalInstance.destroy().then(...);
```

## What do you expect to happen?
- `films` table will be empty
- `festivals` table will be empty
- `film_festivals` table will be empty

## What is actually happening?
- [x] `films` table is empty
- [x] `festivals` table is empty
- [ ] `film_festivals` is not empty. It has one record of the association between the initial film and festival instance

## Which dialect you are using (postgres, mysql etc)?
PostgreSQL 9.6.3

## Which sequelize version you are using?
4.4.2

**Comment by lummish** [comment]
Currently having this same issue. Tried also calling ```destroy``` on each of the associated instances for a given member in a belongsToMany relationship. Seems to work fine on Postgres-9.6.5 (macOS) but not 9.6.6 (CentOS).

**Comment by vapurrmaid** [comment]
@mcranston18 did you ever come up with a suitable solution or workaround?

**Comment by lummish** [comment]
@vapurrmaid One less than optimal solution is to define an additional relationship where the join model belongs to the model that's being destroyed.
