### ISSUE TITLE
Can't save and set associations

### ISSUE THREAD

**Issue by neoziro** [sequelize/sequelize#864]
Before 1.7 alpha3, i did: 

```js
var article = Article.create(),
  comment1 = Comment.build(),
  comment2 = Comment.build();

article.setComments([comment1, comment2]).done(function () {
  // comment1 and comment2 are saved
});
```

Since 1.7 alpha3, it has changed:

```js
var article = Article.create(),
  comment1 = Comment.build(),
  comment2 = Comment.build();

article.setComments([comment1, comment2]).done(function () {
  // comment1 and comment2 are not saved
});
```

I must do:

```js
var comment1 = Comment.create(),
  comment2 = Comment.create();
```

But if i do this, i can't have a strong foreign key constraint on comments.

So, is it a bug ? A feature ? How to do with a strong foreign key constraint ?

**Comment by matmar10** [comment]
+1

**Comment by mickhansen** [comment]
belongsTo relations now support `{save: false)` when calling a setter.

**Comment by mshahriarinia** [comment]
This doesn't work on belongsToMany:

```
Product.belongsToMany(models.Aisle, { through: 'AisleProduct' }); 
Aisle.belongsToMany(models.Product, { through: 'AisleProduct' });

 var product = models.Product.build({});
product.setAisles([1,2], {save: false});
product.save();
```

This causes

`Unhandled rejection SequelizeDatabaseError: null value in column "productId" violates not-null constraint`

`setAisles` tries to save an unpersisted object. `{save:false}` didn't work

**Comment by mickhansen** [comment]
@mshahriarinia As stated it's only supported for belongsTo.

**Comment by jbarros35** [comment]
we need a better ORM for Node.js this tool are making me crazy and providing me nothing, only headaches.

**Comment by matmar10** [comment]
@jbarros35 pull requests welcome :-)

**Comment by jbarros35** [comment]
I dont have time for this. I need something which were suposed to work like creation of nested relationships.
your documentation is very bad.

**Comment by mshahriarinia** [comment]
Dude! This is an open source project. You are not paying for it. Either contribute or Have some respect.

**Comment by corbanb** [comment]
@jbarros35 :-1: contribute or move on.

**Comment by mickhansen** [comment]
@jbarros35 Nested creation is only in early beta so we haven't officially written docs for it yet.
https://github.com/sequelize/sequelize/pull/3386

The syntax is roughly:

```
Model.create({
  // values
  includeKey: {{ //values}}
}, {
  include: [ // model / association / model|as pair ]
});

**Comment by EralpB** [comment]
Is it still the case what @tmont said couple of messages ago after years, couldn't spot in documentation? Sorry for unnecessary notification, I couldn't find how to quote.

**Comment by mickhansen** [comment]
@EralpB belongsTo supports `{save: false}`

**Comment by sw-tt-harishyadav** [comment]
What happened about the issue

**Comment by PorterK** [comment]
Was having this issue, using async await you can just do like so

```js
await event.setSomething(something);
await event.setSomethingElse(somethingelse);
```

and it works perfectly. I was having so much trouble with this, hope it helps someone 👍

**Comment by athbharat** [comment]
set save to false as mentioned here https://stackoverflow.com/questions/32102725/how-to-set-association-at-the-time-of-save-create-in-sequelizejs

**Comment by papb** [comment]
See #11836
