### ISSUE TITLE
Selecting rows without association

### ISSUE THREAD

**Issue by gbyonivo** [sequelize/sequelize#8647]
Given this:
Course.belongsToMany(News, { through: 'course_news', foreignKey: 'course_id' });
News.belongsToMany(Course, { through: 'course_news', foreignKey: 'news_id' });

How do I select news without courses.
I tried
` return News.findAll({
            include: [
                {
                    model: Course,
                    required: false,
                    where: {
                        id: null
                    }
                }
            ]
        });`

**Comment by aryeharmon** [comment]
why is this issue closed?
