### ISSUE TITLE
Association getters/setters don't obey underscored: true

### ISSUE THREAD

**Issue by 0x62** [sequelize/sequelize#8648]
## What are you doing?
I use `underscored: true` on all my models and associations. For example:

```
User.hasMany(PushToken, {
        as: 'push_tokens',
        foreignKey: 'user_id',
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION'
});
```

## What do you expect to happen?
When getting data for an association, you can use `instance.getAssociationName()`. It automatically formats based on the association name, so `pushTokens` would get converted to `instance.getPushTokens()` which makes sense. However, when using underscores instead of camel case, the conversion isn't great. In the example above, `push_tokens` gets converted to `instance.getPush_tokens()`.

Instead, if `underscored: true` is used, I'd expect it to be converted to `instance.get_push_tokens()`.

__Dialect:__ postgres
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
underscore is used to control naming of auto-generated `field`, it doesnt control naming of association. beside snake case method is not a JS thing. 

We have plans for `underscore` to control all database fields not only the auto generated ones. But what you are requesting is not on our roadmap
