### ISSUE TITLE
Async await in express middleware?

### ISSUE THREAD

**Issue by AdityaAnand1** [sequelize/sequelize#8649]
Pardon me if this is off-topic, but I would absolutely love to see an example of multiple sequeilize queries made using async await in express middleware routes. 

* Is this possible?
* Anybody know of a sample repo or something?

**Comment by baptistemanson** [comment]
That should work:
```js
app.get('/user-and-pref', async(req, res) => {
    const user = await models.user
        .findOne({
            where: {
                id: req.headers.userid
            },
        })
    if (!user) { 
         return res.status(404)
           .json({ errors: [{ message: 'User not found.' }] })
    }
    const pref = await models.pref
        .findOne({
            where: {
                userId: user.id
            },
        })
    return res.send('Found the user and its preferences!')
})
```
Make sure your nodejs version is >=7.6 to support async await with no flag. You can get your current version with
```sh
$node --version
v8.7.0
```

**Comment by sushantdhiman** [comment]
Its unrelated to Sequelize so I am closing this. Please keep your general questions to Stackoverflow or Slack
