### ISSUE TITLE
`this` is undefined on instance methods

### ISSUE THREAD

**Issue by HarleyKwyn** [sequelize/sequelize#8652]
## What are you doing?
I'm trying to add a instance method to a DB model that will perform a custom serialization of the model it to send to an external service. However, `this` is not defined when calling the instance method. I'm expecting `this` to be a reference to the instance that the method was called on.

```js
 const StreetAddress = db.define('StreetAddress', {
    id: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      field: 'street_address_id',
      autoIncrement: true
    },
    streetName1: DataTypes.STRING
  });

  StreetAddress.prototype.toCreatePayload = () => {
    console.log('this', this);
    return { streetName1: this.streetName1 };
  };
const instance = StreetAddress.build({id: 1, streetName1: 'foo'})
const payload = instance.toCreatePayload();
```

## What do you expect to happen?
console.log(this) should log the instance of `StreetAddress`

## What is actually happening?
console.log(this) logs `undefined`

__Dialect:__ mysql2
__Dialect version:__  1.4.2
__Database version:__  mysql 5.7.19
__Sequelize version:__ 4.17.0
__Tested with master branch:__ Yes

**Comment by lauren** [comment]
I'm also having this issue!

**Comment by sansumbrella** [comment]
I believe the arrow-function has a lexically-bound `this` from the scope it was defined in. Where it's written, that may indeed be undefined. Have you tried defining with `function` instead, which uses dynamic `this`-binding?

**Comment by HarleyKwyn** [comment]
@sansumbrella solution fixed my problem... learning more and more about ES6 every day 💫

**Comment by TK-one** [comment]
@sansumbrella you fixed my problem.. Thanks!!

**Comment by tibyte** [comment]
@sansumbrella It works!! Thanks... I have forgot this..

**Comment by zharfan104** [comment]
Thankssssssssssssss!!!!!!!!!!!!!!!!!!!!!!!!!! i'm so confused for an hour for this things..

**Comment by vittaljk** [comment]
@kwyn, kyle explains the right way of using es6 features in the link below
 https://freetutorials.ca/video/es6-the-right-parts/0/1
