### ISSUE TITLE
Support for unaccent postgres extension

### ISSUE THREAD

**Issue by fabioespinosa** [sequelize/sequelize#8653]
After doing an extensive search I couldn't find support for unaccent extension in sequelize queries.

They are particularly useful for doing search.

Would love to know if there are any plans to make this possible, or if raw queries are the way to go.

Thanks a lot for all the amazing work 👍 💯

**Comment by fareshan** [comment]
+1 any news on this ?

**Comment by fabioespinosa** [comment]
I went raw on this:

Example with prepared statement:

```
sequelize.query(
			`SELECT
				"People"."phone",
			 FROM "Table"
			 WHERE
			         unaccent("People"."name") ilike unaccent(:name)
			`,
			{
				model: People,
				replacements: {
					name: `%${input_name_to_search}%`
                                  }
                         })
```

**Comment by adrianovieira** [comment]
+1

**Comment by ephys** [comment]
You can already use unaccent today using `fn`. I don't see what we could add?

Let me know if I'm wrong and I'll reopen
