### ISSUE TITLE
Sequelize.import() pass parameters to models, Sequelize return type structure - function or object?

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#8654]
Let say I do this...

```
  var Sequelize = require('sequelize')
    console.log('type: ' + typeof(Sequelize))  // returns 'function', but I want it to be an 'object'

 var app = require('express')
    Sequelize.app = app

```

I cannot append objects to  function, only objects to an object.
My main objective actually is to pass objects to my models when using sequelize.import()

So I guess this is two separate issues, but I am raising awareness on a structural change that could be beneficial.

**Comment by sushantdhiman** [comment]
Please study https://github.com/sequelize/express-example to learn how to properly structure your models and other sequelize stuff
