### ISSUE TITLE
"unique: true" creates duplicate indexes

### ISSUE THREAD

**Issue by galki** [sequelize/sequelize#8656]
## What are you doing?
i was defining a unique index on field `alias`:
```
const User = sequelize.define('user', {
       alias: {
		type: DataTypes.STRING(50),
		allowNull: false,
		unique: true,
	},
})
```
## What do you expect to happen?
i expected a unique `user_alias` index to be created

## What is actually happening?
2 separate indexes were created for the `alias` field:
1. `alias`
2. `user_alias_unique`

the solution was to remove `unique: true` and instead set the index explicitly:
```
indexes: [
	{ fields: ['alias'], unique: true },
],
```

__Dialect:__ mysql
__Database version:__ MariaDB 10.1.28
__Sequelize version:__ 4.13.2

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/6134

**Comment by thomasgauvin** [comment]
Doing unique: 'user' also works well, as suggested in issue #6134
https://github.com/sequelize/sequelize/issues/6134#issuecomment-256171208
