### ISSUE TITLE
AutoIncrement but not primary key

### ISSUE THREAD

**Issue by AdityaAnand1** [sequelize/sequelize#8658]
My model:

```
   const User= sequelize.define("User", {
        index: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
        },
        username: {
            type: DataTypes.STRING
        },
    });
```

Create a row:

```
User.findOrCreate({
            where: {
                username: "whatever"
            }
        })
```

And what happens is that I get null in `index` instead of `1, 2, 3....` in each row. I really can't think of a more minimal example and I'm not sure what could possibly be going wrong here?

For some reason, if I also make the field a primary key, then it works just fine. I'm on SQLite by the way. I prefer my primary keys to be UUIDs and I really do have a need for a monotonically increasing field on every row in the table.

Edit: I just dug up that [SQLite](https://sqlite.org/autoinc.html) explicitly states that AUTOINCREMENT only works on integer primary key fields :/

My question is, is there a workaround for this? I want an auto incrementing field which is not the primary key.

**Comment by sushantdhiman** [comment]
Well you can achieve same with `beforeCreate` + `isNewRecord` combination. It wont be ACID compliant AFIAK.

I will suggest triggers https://sqlite.org/lang_createtrigger.html, a before/after insert trigger will work perfectly for your use case.
