### ISSUE TITLE
Issue with using the new [Op.gt] symbols across library boundaries 

### ISSUE THREAD

**Issue by mansona** [sequelize/sequelize#8663]
I know this may seem like a bit of an edge case, but I thought it was prudent to bring it up as a different issue even though it is related to the discussion here: https://github.com/sequelize/sequelize/issues/8417

I am developing a "common" library that is to be used between different node applications using the same Sequelize models and connections. I am in the process of splitting out the Sequelize code but I couldn't understand why something was not working. I'll try my best to lay out the scenario below: 

The API application has the following dependencies in package.json:
```
    "@company/sequelize-common": "^1.18.7",
    "sequelize": "^4.22.8",
```

and the sequelize-common libarary has the following dependency:
```
    "sequelize": "^4.22.8",
```

The API code has the following (cut down) code to check Access Tokens: 
```
const { Op } = require('sequelize');
const { db } = require('@company/sequelize-common');

module.exports = (req, res, next) => {
    db.token.findOne({
      where: {
        token: req.query.token,
        expires: {
          [Op.gt]: new Date(),
        },
      },
    }).then((token) => {
      // do stuff with token
    });
};
```

Now this code was failing *every time*, no matter what I did it would never find the right token that would expire in the future even though I confirmed with the database multiple times.

It's only when I saw the debug log of the SQL that I saw the problem: 
```
SELECT "token"."token", "token"."expires" FROM "token_table" AS "token" WHERE "token"."token" = 'big_long_token' AND "token"."expires" = '2017-11-20 14:54:26.100 +00:00';
```

Even though I was querying:
```
        expires: {
          [Op.gt]: new Date(),
        },
```
it was using `=` as the operator!?

And this is where it hit me that the above `sequelize.Op.gt` is *not the same symbol* as the internal Sequelize *inside* the `@company/sequelize-common` module. Because of the context switch it didn't understand the Op symbol and *defaulted to eq*.

Now I had a bad feeling about this change, and I understand your reasoning for the security of what you are doing but I *strongly recommend* that you reconsider your choice to a) make this a deprecation or b) any plans to make this a required default behaviour in the future. 

A lot of developers have already tripped up on this issue as it says here: https://github.com/sequelize/sequelize/issues/8417 and would imagine that there are more cases like mine that will cause *actual real bugs in production code* based on slight misunderstandings of the subtleties of this change.

**Comment by sushantdhiman** [comment]
Your concern is very real and this could potentially break many tools and libraries.

Initially we wanted to make sure everyone is aware about our security concerns of un-sanitized user input and switch to Symbol operators. There is option to keep using string operators without any warning using `operatorAliases`

To solve particular issue at hand we can try making Symbols global or shared among all Sequelize instances so this particular issue is fixed.

>Now I had a bad feeling about this change, and I understand your reasoning for the security of what you are doing but I strongly recommend that you reconsider your choice to a) make this a deprecation or b) any plans to make this a required default behaviour in the future.

We are monitoring that thread and all issues users are raising. We are discussing internally about this choice. We have plans to make this a default behaviour in `v5`, but its not final yet. It all depends upon how smoothly this feature can be released.

**Comment by sushantdhiman** [comment]
Fixed with https://github.com/sequelize/sequelize/commit/14864d48d73e4fd96ea9096d888eee52410291ef

With using `Symbol.for` now Sequelize can share symbols using run-time global lookup

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for
