### ISSUE TITLE
cannot set comment for column actually

### ISSUE THREAD

**Issue by marswong** [sequelize/sequelize#8666]
## What are you doing?

create a model by [sequelize-cli](https://github.com/sequelize/cli), and then try to add some comments for the columns.

```js
module.exports = (sequelize, DataTypes) => {
  const TestComment = sequelize.define('test_comment', {
    id: {
      type: DataTypes.BIGINT(20),
      allowNull: false,
      primaryKey: true,
      comment: 'This comment should be set actually',
    },
  });

  return TestComment;
};
```

## What do you expect to happen?

it should set comments for columns actually:

![image](https://user-images.githubusercontent.com/10388933/33050071-f7d6be90-ce9d-11e7-9e0d-8aff8c08662c.png)

## What is actually happening?

it didn't set comments at all:

![image](https://user-images.githubusercontent.com/10388933/33050144-525dd5b0-ce9e-11e7-996c-d73ca254c4e4.png)

__Dialect:__ mysql
__Dialect version:__ 1.5.0
__Database version:__ 5.6.38
__Sequelize version:__ 4.22.8
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/4386
