### ISSUE TITLE
add support for async builtin validator

### ISSUE THREAD

**Issue by FranckFreiburger** [sequelize/sequelize#8668]
## What are you doing?

I need to define a "global" async validator:

```js

Sequelize.Validator.zipcode = function(value) {
  return new Promise(function(resolve, reject) {

    remotely_check_zipcode_validity(resolve);
  });
}
```

## What is actually happening?

`_invokeBuiltinValidator` does not support async validators

The reason why I cannot use custom validators (functions or promise) Is because I need my validators to remain descriptive since I sent them (model.attributes.*.validate) to the front-end.

__Dialect:__ any
__Sequelize version:__ latest (4.22.11)
__Tested with master branch:__ No

**Comment by fzn0x** [comment]
Complex async validations should be outside models and should be executed before calling any data modifying operations,  I believe async validations are only present in `version 2.0` as it's breaks backward compatibility.
