### ISSUE TITLE
Problem with SUM and include

### ISSUE THREAD

**Issue by Danter7** [sequelize/sequelize#8670]
When I try to sum by m:n association I get an error "..id must appear in GROUP BY clause". I found [that issue](https://github.com/sequelize/sequelize/issues/3256), but {raw: true} doesn't solves my problem. I searched in source code for an answer and found that I can pass {includeIgnoreAttributes: false}. Is it right to use it?

```js
const Sequelize = require('sequelize');

const sequelize = new Sequelize({
	database: 'test',
	username: 'test',
	password: 'password',
	host: '127.0.0.1',
	port: 5432,
	dialect: 'postgres',
	logging: console.log,
	operatorsAliases: false
});

const ProductPool = sequelize.define('ProductPool', {
	id: {type: Sequelize.DataTypes.INTEGER, autoIncrement: true, primaryKey: true},
	price: {type: Sequelize.DataTypes.INTEGER, allowNull: false},
	type: {type: Sequelize.DataTypes.STRING, allowNull: false}
}, {
	timestamps: false,
	tableName: 'productPools'
});

const Product = sequelize.define('Product', {
	id: {type: Sequelize.DataTypes.INTEGER, autoIncrement: true, primaryKey: true}
}, {
	timestamps: false,
	tableName: 'products'
});

const Customer = sequelize.define('Customer', {
	id: {type: Sequelize.DataTypes.INTEGER, autoIncrement: true, primaryKey: true},
	type: {type: Sequelize.DataTypes.STRING, allowNull: false}
}, {
	timestamps: false,
	tableName: 'customers'
});

Product.belongsTo(ProductPool, {
	as: 'pool',
	foreignKey: 'productPool'
});

Product.belongsToMany(Customer, {
	as: 'customers',
	through: 'productsToCustomers',
	foreignKey: 'productId',
	otherKey: 'customerId',
	timestamps: false
});

Product.findAll({
	attributes: [
		[sequelize.fn('count', '*'), 'total'],
		[sequelize.fn('sum', sequelize.col('pool.price')), 'money']
	],
	include: [{
		model: ProductPool,
		as: 'pool',
		attributes: [],
		where: {type: 'some type'}
	}, {
		model: Customer,
		as: 'customers',
		attributes: [],
		through: {attributes: []},
		where: {type: 'some type'}
	}],
	raw: true
}).catch((err) => {
	console.error(err);
}).then(() => {
	process.exit(0);
});
```
The sql that is generated is:
`SELECT count('*') AS "total", sum("pool"."price") AS "money", "customers->productsToCustomers"."productId" AS "customers.productsToCustomers.productId", "customers->productsToCustomers"."customerId" AS "customers.productsToCustomers.customerId" FROM "products" AS "Product" INNER JOIN "productPools" AS "pool" ON "Product"."productPool" = "pool"."id" AND "pool"."type" = 'some type' INNER JOIN ( "productsToCustomers" AS "customers->productsToCustomers" INNER JOIN "customers" AS "customers" ON "customers"."id" = "customers->productsToCustomers"."customerId") ON "Product"."id" = "customers->productsToCustomers"."productId" AND "customers"."type" ='some type';`

But I want it to not include "customers->productsToCustomers"."productId" and "customers->productsToCustomers"."customerId", because it calls an error.

__Dialect:__ postgres
__Sequelize version:__ 4.13.8

**Comment by sushantdhiman** [comment]
Sorry I have reopened that issue, I wasn't aware stale bot had closed it.

Migrated to https://github.com/sequelize/sequelize/issues/3256

**Comment by sushantdhiman** [comment]
For deduplication we need to include those ids, apparently there is no way to turn them off completely

**Comment by Danter7** [comment]
Can I use {includeIgnoreAttributes: false}? It works

**Comment by sushantdhiman** [comment]
I am not aware of that option, if it works then its ok for now. But its not a public API atleast
