### ISSUE TITLE
Add Custom Method to Model from Object

### ISSUE THREAD

**Issue by ervan23** [sequelize/sequelize#8675]
## What are you doing?

```js
const model = Database.define('User', {
  ...
});

const method = {
 someMethod(){}
};
```

## What do you expect to happen?
_How to add someMethod() to model like model.someFunction_

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`model.someMethod = method.someMethod` ?

**Comment by ervan23** [comment]
No sushan,  i need all of methods inside const method are added to model.

**Comment by sushantdhiman** [comment]
https://lodash.com/docs/4.17.4#assignIn

**Comment by sushantdhiman** [comment]
Not really related to Sequelize, a general question I think. In any case `assignIn` should help assigning all methods from one object to Model
