### ISSUE TITLE
Sequelize 4 no longer set required to true anymore

### ISSUE THREAD

**Issue by rickli1989** [sequelize/sequelize#8681]
I have a simple query doing nested query below
const event =  await models.Event.findOne({
        where: {
      Event_Id: eventId
    },
    include: [
      {
        model: models.Scenario,
        include: [
          {
            model: models.Phase,
            where: { External_Reference_Id: externalId }
          }
        ]
      }
    ],
    transaction
  })

Previously in V3, if the where condition failed, I will get a null object which my application expects, but now it returns an object. I have to manually add required: true after model: models.Scenario so that I can get the exact same behavior as before.

Is there an easy configuration I can config so that I don't have to pass required: true everywhere in my application

__Dialect: mysql
__Sequelize version: 4.22.12

**Comment by sushantdhiman** [comment]
No there isnt I am afraid. You will have to pass `required: true`. You can use hooks `beforeFind` to achieve that though

**Comment by jifeon** [comment]
@sushantdhiman probably need to add this info into http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html ? Should I create a PR? Also considering the fact that `required` is not `true` if `where` clause is not null anymore, is this docs http://docs.sequelizejs.com/manual/tutorial/models-usage.html#-findandcountall-search-for-multiple-elements-in-the-database-returns-both-data-and-total-count are correct?

**Comment by sushantdhiman** [comment]
@jifeon yes a PR for v4 upgrade guide sounds good.

> The query above will only count users who have an active profile, because required is implicitly set to true when you add a where clause to the include.

Perhaps we should add a test to verify this

**Comment by jifeon** [comment]
@sushantdhiman not sure I have time for writing tests ;( 

Before adding docs I tried to fix the initial issue with a hook and have couple of related questions now:

1. Is this code looks correct to you? It consider that all parent `include`s should be `required` as well.

```js
function whereRequiredLikeInV3(modelDescriptor, ) {
  if (!modelDescriptor.include) {
    return false;
  }

  return [].concat(modelDescriptor.include).some(relatedModelDescriptor => {
    const childDescriptorRequired = whereRequiredLikeInV3(relatedModelDescriptor);

    if ((relatedModelDescriptor.where || childDescriptorRequired) && typeof relatedModelDescriptor.required === 'undefined') {
      relatedModelDescriptor.required = true;
    }

    return relatedModelDescriptor.required;
  });
}

const sequelize = new Sequelize(..., {
  define: {
    hooks: {
      beforeFind: whereRequiredLikeInV3
    },
  },
});
```

2. I have not found any mentioning about `beforeFind` hook in docs, only some issues. Probably should include this in PR as well. But then I need to know the list of all possible hooks. Maybe create another docs PR about hooks?
