### ISSUE TITLE
mariadb seemed to disappear from 4.22.15

### ISSUE THREAD

**Issue by edwardsmarkf** [sequelize/sequelize#8683]
hello - 
**v3.30.4** includes mariadb support, while **4.22.15** does not appear to have mariadb support anymore.  was mariadb support eliminated?

example:

4.22.15 line 234:  
`throw new Error('The dialect ' + this.getDialect() + ' is not supported. Supported dialects: mssql, mysql, postgres, and sqlite.');`
3.30.4  line 231:  
`throw new Error('The dialect ' + this.getDialect() + ' is not supported. Supported dialects: mariadb, mssql, mysql, postgres, and sqlite.');`

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html
