### ISSUE TITLE
Camel_snake_Case in the model methods

### ISSUE THREAD

**Issue by leonormes** [sequelize/sequelize#8694]
## What are you doing?
I have associated models

```js
db.cardSets.belongsTo(db.phonicSchemes);
db.phonicSchemes.hasMany(db.cardSets);

```

## What do you expect to happen?
And I was expecting helpful getter methods to be added so that I could do `cardSet.getPhonicSchemes().`
This did not work and the error message said that `cardSet.getPhonicSchemes().` was not a function. I tried different combinations and ways of writing the method to no avail. 

## What is actually happening?
I then realised I could log the instance and see what was on the object to use and the method is called `.getPhonic_schemes()`
This seems to be a combination of camel and snakecase and was confusing. Is it possible to make it consistent OR have it made clear in the docs that this happens? I wasted a lot of time and in the end, before discovering the real name of the method, I had to get the association manually.

**Comment by abhiburk** [comment]
Same issue
