### ISSUE TITLE
Unexpected behaviour of otherKey option while creating a n:m (belongsToMany) association

### ISSUE THREAD

**Issue by anshulsahni** [sequelize/sequelize#8696]
## What are you doing?

```js
User.belongsToMany(Restaurant, { as: 'workplaces', through: RestaurantEmployee, otherKey: 'workplaceId' });
Restaurant.belongsToMany(User, { as: 'employees', through: RestaurantEmployee, otherKey: 'employeeId' });
```

## What do you expect to happen?
_A table in mysql with columns workplaceId and employeeId other than columns of its own_

## What is actually happening?
_The table contains column `employeeId` (which is correct) but another column name is `restaurantId` (which is the default key name). If I change the **order of lines written** in above snippet the `workplaceId` appears and instead of `employeeId` the column comes as `userId`_

_Output, either JSON or SQL_
-

__Dialect:__ mysql
__Dialect version:__ 1.5.1
__Database version:__ 5.7.20-0ubuntu0.16.04.1
__Sequelize version:__ 4.23.1
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by janmeier** [comment]
Remember to use `foreignKey` on both sides of the association as well
