### ISSUE TITLE
Release spam

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#8701]
When I added semantic-release a year ago, the goal was to ensure we follow semantic versioning 100%, to release fast and to always have proper changelogs. I think the current situation takes it to far - if I look at the release page, the last 6 releases have **no changelog** (i.e. no relevant changes) at all.
- `v4.23.1`: Corrects some typos in a markdown file https://github.com/sequelize/sequelize/commit/b8cfde9d67f70b742b72113f4e0149880030ecc8
- `v4.23.0`: (a minor, i.e. **feature** release): Adds ESLint rules https://github.com/sequelize/sequelize/commit/703d4feb16849fe13500296f31411f216428d478
- `v4.22.16`: Fixes a typo in a markdown file https://github.com/sequelize/sequelize/commit/2b3193045712f8bb031dddcd9c6475f53b852db1
- `v4.22.15`: Changes some example in a markdown file https://github.com/sequelize/sequelize/commit/398c1ce7226b401ff9db1e01cd39f7446c671bdd
- `v4.22.14`: Updates markdown files https://github.com/sequelize/sequelize/commit/7a801408b48661ccc9162dfaaffd71be640e0a59
- `v4.22.13`: Updates markdown files https://github.com/sequelize/sequelize/commit/7fe6da1e42f7e48e07a2aafe88813040616aa42f

The goal of semantic-release and semantic versioning (which the readme says Sequelize follows) is 

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

It is _not_ to release on _every_ commit, it is to release on every commit _that fulfils one of the above criteria_. With these criteria, none of the above examples should have triggered any kind of release.
[And configuring semantic-release to have a possibility to trigger a manual, unsemantic release](https://github.com/sequelize/sequelize/blob/b8cfde9d67f70b742b72113f4e0149880030ecc8/package.json#L154) is [intentionally disallowed by semantic-release](https://github.com/semantic-release/semantic-release#can-i-manually-trigger-the-release-of-a-specific-version):

> ### Can I manually trigger the release of a specific version?
> 
> You can trigger a release by pushing to your GitHub repository. You deliberately cannot trigger a _specific_ version release, because this is the whole point of `semantic-release`. Start your packages with `1.0.0` and semver on.

Everyone who has something like Greenkeeper, dependencies.io or Sibbel set up currently gets countless PRs or notifications for versions that contain no changes in behaviour. Libraries that depend on Sequelize without a lockfile can rarely cache the dependency.

I would like to propose to go back to the semantic-release default settings to reduce the spam and follow semver correctly.

Documentation is released on every commit, markdown should not be included in the npm package and other releases are frequent enough to get docblock updates in (and not every editor uses them anyway, Visual Studio for example uses TypeScript typings).

A refactor should never trigger a release as its definition is to not change any behavior - if it introduces a bug, there is no gain in getting that out fast. If it gets out, it will in the next release, and users can still rollback.

As I recently also worked a lot with the new semantic-release v11, if the current maintainers are fine with this, I would be happy to prepare a PR to update to that and restore the defaults.

**Comment by eseliger** [comment]
I totally agree with you. I really like that we release every important change to the codebase immediately, but we definitely don't have to trigger patch and even **minor** releases on documentation changes or refactors, which might not even be packed into the npm package. 
@sequelize/core if you agree too, I'd accept a PR for adjusting the behavior.

**Comment by sushantdhiman** [comment]
I agree with the fact that SEMVER is not properly followed by Sequelize, that was entirely because of my personal preferences.

But there are obviously lots of unnecessary releases going on. I have reset release preference https://github.com/sequelize/sequelize/commit/84e00ae89d36924e6c7eee131211c7f03a043190 again to follow SEMVER.

Now only `fix` ( OR `perf`) as patch and  `feat` as minor version will be released.
