### ISSUE TITLE
JSON columns returned differently depending on whether MySQL or MariaDB is used

### ISSUE THREAD

**Issue by ivokund** [sequelize/sequelize#8702]
## What are you doing?

When loading json columns from the database, `toJSON()` behaves differently depending on whether MySQL or MariaDB is used
```js
// connect
const sequelize = new Sequelize(process.env.MYSQL_URI);
await sequelize.authenticate();

// create schema
const model = sequelize.define('test', { jsonColumn: { type: Sequelize.JSON } });
await sequelize.sync({ force: true });

// create and fetch some data
await model.create({ id: 1, jsonColumn: {a: 1}});
const fetchedModel = await model.findById(1);

// output
console.log(fetchedModel.toJSON().jsonColumn);
console.log(typeof fetchedModel.toJSON().jsonColumn);
```

## What do you expect to happen?
_The json column should be returned as a json-decoded object_

## What is actually happening?
Output on `5.7.20-0ubuntu0.17.04.1` (correct):
```
{ a: 1 }
object
```
Output on `10.2.10-MariaDB-log` (incorrect):
```
{"a":1}
string
```

__Dialect:__ specified above
__Sequelize version:__ 4.23.1
__mysql2 version:__ 1.5.1
__Tested with master branch:__ No

**Comment by ivokund** [comment]
I also note that a quick-hack that fixes the issue is to define a manual getter in the column definition as this:
```js
{
        type: Sequelize.JSON,
        get () {
            return typeof this.getDataValue(field) === 'string' ? JSON.parse(this.getDataValue(field)) : this.getDataValue(field);
        },
    }
```
But I assume that this is not supposed to be required?

**Comment by sushantdhiman** [comment]
I would like to clarify that Sequelize only supports MariaDB because they (used to?) follow MySQL implementation and maintain API compliance.

If MariaDB and MySQL are diverging then I am afraid we cant fix this as there is no "real" MariaDB dialect in Sequelize

**Comment by SimonSchick** [comment]
@sushantdhiman I ran into this bug as well today, wouldn't it be possible to incorporate this workaround/getter into sequelize? It's only about 5 loc.

**Comment by knoxcard** [comment]
dialect: 'mariadb' has been reintroduced back into Sequelize, so this can now be used to create logic for both MySQL/MariaDB.

**Comment by soryy708** [comment]
According to [the manual](https://sequelize.org/master/manual/data-types.html), JSON is not supported for MariaDB dialect.

**Comment by papb** [comment]
@soryy708 I am pretty sure that is a mistake in the docs, I will look into it

**Comment by jfkz** [comment]
Still reproduced. Mariadb dialect is not supported in Sequelize but this construction works only with this snippet.
