### ISSUE TITLE
Migration Sequelize.NOW not working for "mssql"

### ISSUE THREAD

**Issue by alexvicegrab** [sequelize/sequelize#8715]
## What are you doing?
I'm trying to update a table on MS SQL Server using a migration like this...

```js
'use strict';

module.exports = {
    up: (queryInterface, Sequelize) => {
        return queryInterface.addColumn(
            'myTable',
            'createdAt',
            {
                type: Sequelize.DATE,
                allowNull: false,
                defaultValue: Sequelize.NOW
            }, {
                logging: console.log
            }
        );
    },

    down: (queryInterface, Sequelize) => {
        return queryInterface.removeColumn(
            'myTable',
            'createdAt'
        );
    }
};
```

## What do you expect to happen?
I wanted this to update my existing databases with a required createdAt field.

## What is actually happening?
Instead I see the following:

```
Executing (default): ALTER TABLE [officer] ADD [createdAt] DATETIMEOFFSET NOT NULL;

ERROR: ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'createdAt' cannot be added to non-empty table 'officer' because it does not satisfy these conditions.
```

I can fix this with MS-SQL specific code such as:

```js
defaultValue: Sequelize.fn("GETDATE")
```

resulting in:

```
Executing (default): ALTER TABLE [officer] ADD [createdAt] DATETIMEOFFSET NOT NULL DEFAULT GETDATE();
```

while 

```js
defaultValue: Sequelize.fn("NOW")
```

...does not work in MSSQL.

My working dirty fix really does defeat the purpose of using an ORM, so I'd rather Sequelize.NOW worked correctly, but not sure where the issue lies.

_Output, either JSON or SQL_

__Dialect:__ mssql / any
__Dialect version:__ XXX
__Database version:__ Azure SQL server (not important, as query is incorrectly specified.
__Sequelize version:__ CLI: 3.1.0, ORM: 4.23.2
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by Deepankar01** [comment]
`defaultValue: Date.now` this works
