### ISSUE TITLE
attribute named "toString"

### ISSUE THREAD

**Issue by jharting** [sequelize/sequelize#8719]
## What are you doing?

In our project we have an attribute called _toString_ on one of our models. With Sequelize v3 this was not a problem but after upgrading to v4 the attribute no longer works. Instead of the proper value, `[object Object]` is returned every time.

## What do you expect to happen?
I expect the value of the attribute named _toString_ to work as any other argument

## What is actually happening?
I am getting `[object Object]` instead.

__Dialect:__ mysql
__Database version:__ 10.1.26
__Sequelize version:__ 4.23.1
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Bug indeed but `toString` is an odd name for column, just saying :)

**Comment by jharting** [comment]
@sushantdhiman I totally agree :-)

**Comment by jharting** [comment]
Workaround: `<Model>._dataTypeSanitizers.toString = _.identity;`

**Comment by plit** [comment]
This fix broke our getters/setters.

On the field definition we had this: 
```
const _createGetter = function () {
    if (/* condition */) {
        return function () {
            /*getter function*/
        }
    } else {
        return;
    }
}

id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
    get: _createGetter(),
}
```

Before this fix, when the returned value of `_createGetter` was `undefined`, the field got the default getter. Now it gets an `undefined` value as getter function, which (when I'm calling `field.id`) leads to this error:
```
13:24:15 0|nodeserv |   TypeError: Cannot read property 'call' of undefined
13:24:15 0|nodeserv |       at User.get (/opt/server/node_modules/sequelize/lib/model.js:3143:40)
13:24:15 0|nodeserv |       at User.funcs.(anonymous function) (/opt/server/node_modules/sequelize/lib/model.js:910:25)
13:24:15 0|nodeserv |       at User.findRoles (/opt/server/nodeserver/server/model/mysql/user.js:463:42)
```
