### ISSUE TITLE
Can not update if column's name is "status"

### ISSUE THREAD

**Issue by reservce** [sequelize/sequelize#8730]
## What are you doing?
I'm using Postgresql.
I got an stranger issue when a column is named "status".
I want to update status column, from current value to "deleted",
so I use:
```javascript
var profile = ProfileModel.findOne({where:{id: 12}, raw: false, attributes:['id', 'status', 'age']});
console.log(profile);
/*===> { id: 12, status: 'actived', age: 18}`*/
profile.update({ 'status': 'deleted', age: 20 });
```
With Profile model:
```javascript
import {Model, DataTypes} from 'sequelize';
import uuidV4 from 'uuid/v4';
import sequelize from '../../configs/connections/pg';
import {Options, Attributes} from 'sequelize-decorators';

@Options({
    sequelize,
    tableName: 'profile'
})

@Attributes({
    id: {
        type: DataTypes.UUIDV4,
        allowNull: false,
        defaultValue: function () {
            return uuidV4();
        },
        primaryKey: true
    },
    age: {
        type: DataTypes.INTEGER,
        allowNull: false
    },
    status: {
        type: DataTypes.STRING,
        allowNull: true,
        primaryKey: true
    },
})

export default class Profile extends Model {
    getId() {
        return this.id;
    }

    setId(id) {
        this.id = id;
    }

    getAge() {
        return this.age;
    }

    setAge(age) {
        this.age = age;
    }

    getStatus() {
        return this.status;
    }

    setStatus(status) {
        this.status = status;
    }
}
```

## What do you expect to happen?
It should has "status" = 'deleted' in the query:
```console
UPDATE "profile" SET age = 20, "status" = 'deleted' WHERE "id" = '12' AND "status" = 'actived' AND "age" = 18
```
## What is actually happening?
The "status" = 'deleted' is missing:
```console
UPDATE "profile" SET age = 20 WHERE "id" = '12' AND "status" = 'actived' AND "age" = 18
```
So the status is not updated.

When I change the column name to "statuss", it gens correctly as my expect:
```console
UPDATE "profile" SET age = 20, "statuss" = 'deleted' WHERE "id" = '12' AND "status" = 'actived' AND "age" = 18
```

**Sequelize version**: 4.7.5
**Postgre**: 9.6
Pls help me on this issue, thanks

**Comment by reservce** [comment]
Pls give more info when closing this.

**Comment by sushantdhiman** [comment]
Please follow the issue template and respect our [guideline](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) around issues

**Comment by reservce** [comment]
Sorry.
I updated folow guideline and other issues.

**Comment by sushantdhiman** [comment]
Is there any hook involved that might be changing parameters on update?

**Comment by reservce** [comment]
I'm sure that nothing else.
I just get sequelize instance from findOne() function, and then call .update() with new data.
And after I changed column into a non keyword, e.g: "statusss", the query is right as I expect.

**Comment by sushantdhiman** [comment]
Try with latest version

**Comment by reservce** [comment]
Yes, I update to `-- sequelize@4.23.4
But the incorrect query is still there.

**Comment by sushantdhiman** [comment]
Can you reproduce this issue with bare Sequelize setup outside your application, I cant help you unless I have a way to reproduce this

**Comment by reservce** [comment]
I tried to reproduce in this source code: [https://drive.google.com/file/d/1u0uB1WRr3_asJdJHWm3BmNirU-jqXQ4X/view?usp=sharing](url)
I also generate database DDL script in readme.md
Could take a look, pls?

**Comment by reservce** [comment]
I tried to log data in update(values, options) (in node_modules/sequelize/lib/model.js)
Somehow it ignores new data in "status" fields.
