### ISSUE TITLE
bulkCreate messes up id values

### ISSUE THREAD

**Issue by jharting** [sequelize/sequelize#8731]
## What are you doing?

In my seed test database script I am using `bulkCreate`. The list of entity values contains predefined ids for the auto increment column.

```js
Person.bulkCreate([{
    id: 1,
    name: 'Alpha'
}, {
    id: 2,
    name: 'Bravo'
}]))
```
Then, I use the returned value.

## What do you expect to happen?
I expect to get the input values back wrapped in Sequelize model objects. The ids should be as defined.

`[ { id: 1, name: 'Alpha' }, { id: 2, name: 'Bravo' } ]`

## What is actually happening?
Oddly, here's what I get back from the bulkCreate call:

`[ { id: 2, name: 'Alpha' }, { id: 3, name: 'Bravo' } ]`

i.e. the ids are shifted. If I subsequently query the table, the stored entities have the correct values:
`[ { id: 1, name: 'Alpha' }, { id: 2, name: 'Bravo' } ]`

Therefore, to me it looks like there's an odd bug somewhere which alters the id values although that is not necessary in this case.

I was able to reproduce with mysql and sqlite.

At this point you may think it doesn't make sense to provide values for an auto-increment column and even expect bulkCreate to return id values but for seeding test data into a clean db table this was the best way I found.

__Dialect:__ mysql
__Database version:__ 10.1.26
__Sequelize version:__ 4.23.4
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
> At this point you may think it doesn't make sense to provide values for an auto-increment column and even expect bulkCreate to return id values but for seeding test data into a clean db table this was the best way I found

I have submitted a PR that should keep user supplied primary key values for `bulkCreate`.

Please note with both MySQL / SQLite its not possible to return inserted ids for bulk inserted records. We are just regenerating possible auto increment values for MySQL / SQLite (for bulkInsert) by looking at last insert id and affected rows.

So its very possible that bulkCreate may return incorrect auto increment values (for MySQL / SQLite i.e.), but if you are passing ids yourselves then it can be prevented and we can reuse those ids

**Comment by jharting** [comment]
@sushantdhiman thanks for the fix! I verified it works as expected in our environment.

**Comment by jakedetels** [comment]
This bug appears to have resurfaced at some point.  I get identical behavior as the OP.

```js
const UserModel = sequelize.define('user', {
  id: {
    field: 'userID',
    primaryKey: true,
    autoIncrement: true,
    type: INTEGER(11),
  },
  username: { type: STRING },
});

const results = await UserModel.bulkCreate([
  { id: 1, username: 'Alpha' },
  { id: 2, username: 'Bravo' },
]);
console.log(results.map((r) => r.id)); // logs: [2, 3]
```

I found that when I omit the `autoIncrement` property from the `id` attribute, I get the expected results.   Can we reopen this issue, or should I file a new issue?

**Comment by octalpixel** [comment]
> This bug appears to have resurfaced at some point. I get identical behavior as the OP when testing in version 5.21.8 and using the MariaDB dialect.
> 
> ```js
> const UserModel = sequelize.define('user', {
>   id: {
>     field: 'userID',
>     primaryKey: true,
>     autoIncrement: true,
>     type: INTEGER(11),
>   },
>   username: { type: STRING },
> });
> 
> const results = await UserModel.bulkCreate([
>   { id: 1, username: 'Alpha' },
>   { id: 2, username: 'Bravo' },
> ]);
> console.log(results.map((r) => r.id)); // logs: [2, 3]
> ```
> 
> I found that when I omit the `autoIncrement` property from the `id` attribute, I get the expected results. Can we reopen this issue, or should I file a new issue?

Having the same issue, did you find a workout other than removing autoIncrement ? . Because it works for me locally but gets this error on heroku

**Comment by robertsLando** [comment]
I'm having this issue too, any suggestions?

**Comment by ephys** [comment]
@robertsLando Which version of Sequelize are you using? Is it also only with autoIncrement-ed attributes?

**Comment by robertsLando** [comment]
@ephys Sequelize version: 6.13.0

I have fixed by doing this: 

```js

const destroyOptions: DestroyOptions = {
  where: {},
  truncate: true,
  restartIdentity: true,
};

const bulkCreateOptions: BulkCreateOptions = {
  ignoreDuplicates: true,
};

await User.destroy(destroyOptions);
await User.bulkCreate(users as any, bulkCreateOptions);
```

BTW I think there should be a better way

**Comment by nawlbergs** [comment]
why was this closed... a co-worker is getting back in-correct ids... very dangerous.

**Comment by WikiRik** [comment]
> why was this closed... a co-worker is getting back in-correct ids... very dangerous.

Are you experiencing the exact same bug as in the original post? If not it might be better to create a new issue with a SSCCE detailing your issue
