### ISSUE TITLE
Consider using an async map for bulkBuild in model

### ISSUE THREAD

**Issue by DiegoRBaquero** [sequelize/sequelize#8744]
Hey guys,

I stumbled some event-loop blocking code here: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1957

I had 27k rows and it blocked the event loop for over 200-600ms.

I'm not talking about the library async, but rather making the map async.

**Comment by DiegoRBaquero** [comment]
Would you guys accept a PR?

**Comment by papb** [comment]
@DiegoRBaquero Hello, sorry to take so long to reply...

What is the status of this in the latest sequelize? Do you still face the same problem? Are you still willing to submit a PR? Thank you very much.

**Comment by papb** [comment]
Similar: #8745

**Comment by papb** [comment]
This is being tracked at #8745 now
