### ISSUE TITLE
Consider using async `for` for _groupJoinData in query

### ISSUE THREAD

**Issue by DiegoRBaquero** [sequelize/sequelize#8745]
Hey guys,

I stumbled some event-loop blocking code here: https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query.js#L520

I had 27k rows and it blocked the event loop for over 200-400ms.

I'm not talking about the library async, but rather making the `for` async.

**Comment by DiegoRBaquero** [comment]
Would you guys accept a PR?

**Comment by sushantdhiman** [comment]
Yes we always accept reasonable fixes, as this is performance issue you need to show some benchmarks before that PR gets merged

**Comment by papb** [comment]
What is the status of this in the latest sequelize? Do you still face the same problem? Are you still willing to submit a PR? Thank you very much.

**Comment by papb** [comment]
Hi @DiegoRBaquero may I ask why you closed the issue? Did you find a workaround, did your problem stop, or something else? Thanks

**Comment by papb** [comment]
Let's track #8744 here as well
