### ISSUE TITLE
Sequelize : Get Subquery/Raw Query as model for include

### ISSUE THREAD

**Issue by vivek-zaptech** [sequelize/sequelize#8746]
I have gone through the Sequelize doc, but can't find anything helpful

What I want to do is to add raw query or custom model in `include`, is it possible ?

    model.Post.findAll({
                include: [{
                        model: model.User,
                        attributes: ['fullname', 'profilepic'],
                    },
                    {
                        model: model.PostComments,
                    },
                    {
                        model: "Raw Query"
                    }
                ]
            }

What I want to achieve is like :

    Select post_id, count(*) as total_likes from post_likes group by post_id
    
I can't achieve this by using simply `include`, so what I want to do is create a table/model from above query and then use it inside include.

If I use group by withing `include` it gives group by from top level, and I want to apply `group` by just for the `post_like` table.

Please let me know, if it found confusing or not clear.

Dialect: postgres

**Comment by sushantdhiman** [comment]
Please follow the issue template

**Comment by cubbuk** [comment]
Hi,

Could someone explain if what @vivek-zaptech mentioned is possible or not? Basically can we add a raw query to be used inside a join?  
````
model.Post.findAll({
            include: [
                {model: model.User},
                 "Raw Query",
            ]
        });
````

Thanks

**Comment by sushantdhiman** [comment]
No its not possible, we can only refer relationship on association and models not on raw query. This will require some sort of query builder which I am afraid sequelize does not support.

**Comment by cubbuk** [comment]
Thanks @sushantdhiman. I proceed with the approach suggested on this article http://srlm.io/2015/02/04/sequelize-subqueries/. I added the attribute using sub query with literals.

````
sequelize.literal(`
                 (
                 SELECT AVG(price) AS averagePrice
                    FROM prices
                    WHERE record.id = prices.record_id
                            AND prices.day >= '${startDay}'
                            AND prices.day < '${endDay}'
                            AND prices.price > 0
                 ) AS averagePrice`);
````

**Comment by harpcio** [comment]
I have a lot of problems with PostreSQL vs MySQL compatibility.
This is working for both.

```
let ordersCountSQL = sequelize.dialect.QueryGenerator.selectQuery('orders', {
    attributes: [
        [sequelize.fn('COUNT', sequelize.col('orders.id')), 'orders_count']
    ],
    where: {
        customer_id: {
            [Op.eq]: sequelize.col('Customer.id')
        }
    }
}).slice(0, -1);

let totalPurchaseSQL = sequelize.dialect.QueryGenerator.selectQuery('orders', {
    attributes: [
        [sequelize.fn('SUM', sequelize.col('orders.total')), 'total_purchase']
    ],
    where: {
        customer_id: {
            [Op.eq]: sequelize.col('Customer.id')
        }
    }
}).slice(0, -1);

const customers = await Customer.findAndCountAll({
    attributes: {
        include: [
            [sequelize.literal('(' + ordersCountSQL + ')'), 'orders_count'],
            [sequelize.literal('(' + totalPurchaseSQL + ')'), 'total_purchase'],
        ],
    },
    include: [
        {
            association: 'orders',
            model: Order,
            attributes: [],
        },
    ],
    subQuery: false,
    group: ['Customer.id']
});
```

**Comment by papb** [comment]
@harpcio That looks like an ugly workaround, but interesting regardless... Would you be willing to open a feature request posting what problem did you encounter (with example) and then showing your workaround for now? I think Sequelize should be able to solve what you're trying to do in a better way. Thanks!
