### ISSUE TITLE
FEATURE or QUESTION: how can I write some calculated column?

### ISSUE THREAD

**Issue by cybermerlin** [sequelize/sequelize#8747]
## What are you doing?
Hi, I need help with this:
```SQL
select
    birthday, sex,
    concat( lastname, '  ', firstname) as name
from person
where
    name like '%pupi%'
```
but I try use sequelize like a big trueman:
```javascript
class Person {
    @Column({type: 'text'})
    firstname;
    @Column({type: 'text'})
    lastname;
    @Column({type: 'datetime'})
    birthday;
    @Column({type: 'tinyint'})
    sex = 1;

    //                           what need I write to do this?
    name;
}

let persona = new Person();
persona.find({name: 'pupi', limit: 1});

console.info(persona.name);
```

__Dialect:__  any 
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

You can use VIRTUAL where you can combine two or more fields data, but you have to define those fields which are used in calculation. 

But you cant query using VIRTUAL fields, they are unknown to database.
