### ISSUE TITLE
Transactions hanging for Postgres

### ISSUE THREAD

**Issue by ryan-wong** [sequelize/sequelize#8758]
## What are you doing?
I was migrating my database from mysql to postgres. This code worked in mysql but ever since I switch to postgres, it hangs. I've been trying everything for 2 days and no luck.
I checked the postgres log and I see this:
Executing (97aafa00-5fa5-4580-8557-ddf27dfb6909): START TRANSACTION;
Executing (97aafa00-5fa5-4580-8557-ddf27dfb6909): SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

```js
sequelize.db.transaction({
            isolationLevel: 'SERIALIZABLE'
        }).then(function (t) {
            return sequelize.models.fb_vendor.find({
                where: {
                    id: vendorId
                }
        }, { transaction: t }).then(function (user) {
            return sequelize.models.fb_users.find({
                where: {
                    id: user_id
                }
            }, { transaction: t });
        }).then(function (user) {
            return t.commit();
        }).catch(function (err) {
            return t.rollback();
        });    
});
```

## What do you expect to happen?
not to hang and run

## What is actually happening?
hangs and won't execute

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ 3.27.0
__Tested with latest release:__ No (If yes, specify that version)
__pg version: 6.4.1

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by rsshilli** [comment]
Ryan, how did you fix this?

**Comment by sachinB94** [comment]
@ryan-wong same issue, how did you fix this?

**Comment by rsshilli** [comment]
I figured it out: https://github.com/sequelize/sequelize/issues/8468

You need to call Sequelize.close() everywhere as of Sequelize v4.  Super annoying.

**Comment by sachinB94** [comment]
@rsshilli So, after every transaction, I should call `sequelize.close()`? Won't that close all the connections with sequelize?

**Comment by liviuignat** [comment]
We are experiencing some transaction problems as well, was this issue fixed? Why was it closed?

**Comment by rsshilli** [comment]
Sorry @sachinB94 , I just saw this.  Yes, you need to call sequelize.close() constantly.  For us, it was such a deal breaker that we rolled back to Sequelize 3 and we're happy there.

**Comment by devdemi** [comment]
We have the same problem as @ryan-wong described.
