### ISSUE TITLE
In beforeUpdate hook, instance.changed()  returns all attributes as changed, when update is called on instance returned by bulkCreate

### ISSUE THREAD

**Issue by wolframkleis** [sequelize/sequelize#8762]
## What are you doing?
* I create a model with attributes "id","s1","s2","s3" 
* I create an instance with `bulkCreate`
* Then i call `update()` on the instance returned by bulk create
* the update changes just attribute "s3" and leaves several others unchanged
* in the `beforeUpdate` hook, I call `instance.changed()` to find out what is  about to be changed 
```js
const Model = sequelize.define('Model',{
 id: {type: Sequelize.INTEGER, primaryKey: true},
 s1: {type: Sequelize.STRING(10)},
 s2: {type: Sequelize.STRING(10)},
 s3: {type: Sequelize.STRING(10)}
},{
  timestamps: false,
  hooks: {
    beforeUpdate: function (instance){
      console.log("changed: " + instance.changed());
  }
}
});
sequelize.sync({force: true,logging: false})
.then(() => Model.bulkCreate([{id: 2,s1: "Alpha",s2: "Beta",s3: "Gamma"}],{logging: false}))
.then(rows => rows[0].update({s3: "Updated!"}));
```

## What do you expect to happen?
I expected that `instance.changed()` returns `["s3"]` 

## What is actually happening?
instead `instance.changed()` returns all attributes!
`["id","s1","s2","s3"]`

console output: 
``` 
changed: id,s1,s2,s3
Executing (default): UPDATE "Models" SET "s3"='Updated!' WHERE "id" = 2
```
(the SQL is correct and the update is successful, that is not the problem)

The update is executed correctly, but `changed()` function seems to have a problem.
I if call `update()` on an an instance returned by `create()` or `findAll()` or `find()`, it works as expected. 
Correctness of `changed()` function seems to depend on how the instance was retrieved?

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.27.0
__Tested with latest release:__ Yes, 4.27.0

**Comment by weblemur** [comment]
It looks like `bulkCreate` doesn't map `_previousDataValues` to the created instances. It'd probably be worth adding that capability... Until then, you can work around this by using `individualHooks: true` which will force a `.save()` on each instance.
