### ISSUE TITLE
Bug: bulkCreate updateOnDuplicate:true does not work in MSSQL

### ISSUE THREAD

**Issue by johncade** [sequelize/sequelize#8766]
## What are you doing?

   Trying to do a simple bulk update or insert into a MSSQL database.
```js
// code here
   db.demoModel.bulkCreate(models, {updateOnDuplicate:true})
```

## What do you expect to happen?
_The database should be successfully updated_

## What is actually happening?
_Sequelize throws an error. _

__Dialect:__  mssql 
__Dialect version:__ 16
__Database version:__ 2016
__Sequelize version:__ 4.11.0
__Tested with latest release:__ No (If yes, specify that version)

Some may say this is not a bug, however I disagree. First let me say, that in most cases Sequelize is a Godsend, and very useful. So you guys do a great job. However, bulk updates/inserts are an important component of interacting with a database and it seems absurd that Sequelize cannot do this with a MSSQL db. Is the plan really to force users to go outside of the ORM to break up their design pattern and interact with DB manually? If there is an existing solution, it has escaped my searches for the last 3 days. Is there a technical reason why this `bug` exists in Sequelize?

**Comment by sushantdhiman** [comment]
This is not a bug, MSSQL doesnt support a key feature `ON DUPLICATE KEY` which is used to detected duplicate rows then updating them. If database engine doesnt support it then we cant do any thing.

http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-bulkCreate

> Fields to update if row key already exists (on duplicate key update)? (only supported by mysql). By default, all fields are updated.

`updateOnDuplicate` is only supported for MySQL
