### ISSUE TITLE
`findAll` with empty `include` array ignores the `where` condition.

### ISSUE THREAD

**Issue by Axure** [sequelize/sequelize#8771]
## What are you doing?
```js
    const relations = await UserReferUser.findAll<UserReferUser>({
      where: {
        referrerId: id
      },
      include: []
    });
```

## What do you expect to happen?
Find the relations associated with a given user.

## What is actually happening?
It returns the all the relations. I'm not sure if it's intended or not.

```sql
Executing (default): SELECT "id", "deleted", "referrerId", "refereeId", "createdAt", "updatedAt" FROM "UserReferUser" AS "UserReferUser";
```

__Dialect__: postgres
__Database version:__ 10.1-1
__Sequelize version:__ 4.27.0
__Tested with latest release__: Yes

**Comment by dynk** [comment]
I had the same problem and I also think this is a bug.

**Comment by sushantdhiman** [comment]
May be related to TypeScript setup, this bug is not related to Sequelize, I have added a test for that
