### ISSUE TITLE
Associations to 2 levels deep?

### ISSUE THREAD

**Issue by alnorris** [sequelize/sequelize#8772]
Apologies if this has been done before, I couldn't find anything. I have a list of companies that have many products, and those products have many reviews. I'd like to get all reviews for that company in this format, without any mention of the product. Is this possible with one findAll?

```
{
    id: 1,
    comapnyName: 'Samsung'
    reviews: [{
        title: 'review title',
        body: 'asdlkjad'
    }, {
        title: 'review title',
        body: 'asdlkjad'
    }]
}
```

**Comment by aakashmalhotra** [comment]
@alnorris found anything?

**Comment by alnorris** [comment]
@aakashmalhotra Due to the lack of responses I feel its unlikely its a possibility currently :(

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/3935
