### ISSUE TITLE
Migrations and Sequelize V4

### ISSUE THREAD

**Issue by radcapitalist** [sequelize/sequelize#8773]
I'm using Sequelize version 4 and am about to look at implementing migrations.  Migrations require sequelize-cli.  However, I see that the version of sequelize-cli that is compatible with Sequelize version 4 is not yet production.  So, can I reliably do migrations in Sequelize version 4?  I reckon I have three choices:

1. Stay at sequelize 4.x and move to the pre-release sequelize-cli 4.x
2. Stay at sequelize 4.x but keep using sequelize-cli 3.x
3. Go back to sequelize 3.x and use it with its compatible sequelize-cli 3.x

Any suggestions on how to choose between these strategies?  Can you expound on what sequelize-cli 3.x being "not fully compatible with Sequelize v4" means in practice?  In what scenarios can we expect things to go wrong?  Associations?  Should I just keep my migrations as raw SQL queries in the meantime?

Thanks,

Eric

**Comment by deankostomaj** [comment]
+1. I would also like to hear a few words about that.

**Comment by sushantdhiman** [comment]
You can use `sequelize-cli@3` (There is no `sequelize-cli@4.x` or pre production version yet), it will work with `sequelize@4`. Only incompatibility will be this https://github.com/sequelize/cli/pull/470

So just your auto generated models will need some editing by hand, everything else should work.

**Comment by radcapitalist** [comment]
That's very manageable.  Thanks very much for clarifying!

Eric
