### ISSUE TITLE
Soft delete with cascade

### ISSUE THREAD

**Issue by pirmax** [sequelize/sequelize#8775]
I have lots of relationships between tables, I want **soft delete** entities with cascade.

I found **cascade** option in destroy method but it doesn't works.
Soft delete work but not cascading.

    return await Database.destroy({
        where: {
            uuid
        },
        force: false,
        cascade: true
    }) > 0;

**Comment by sushantdhiman** [comment]
Duplicate of https://github.com/sequelize/sequelize/issues/2586

Just for clarification, CASCADE is something that database engine controls. But we can potentially issue a delete command for paranoid model when `cascade: true`, hence the feature request.

**Comment by mranon0007** [comment]
> Duplicate of #2586
> 
> Just for clarification, CASCADE is something that database engine controls. But we can potentially issue a delete command for paranoid model when `cascade: true`, hence the feature request.

has the feature been added yet?

**Comment by papb** [comment]
@mranon0007 @2586 is still open, so no.
