### ISSUE TITLE
Include inside jointure table between two associations

### ISSUE THREAD

**Issue by dm67x** [sequelize/sequelize#8777]
Hello,

I have a little problem :)
I have four tables and two of them is associated with the third to make a belongsToMany association realisable. But inside of my jointure table i want to make an association with the fourth table who contains some informations. I search it through internet but i didn't find an answer. 

My jointure table :

```javascript
module.exports = function (sequelize, DataTypes) {

    var contient_ingredient = sequelize.define("Contient_Ingredient", {
        qte: DataTypes.INTEGER
    });

    contient_ingredient.associate = function (models) {
        contient_ingredient.belongsTo(models.Unite);
    };

    return contient_ingredient;

};
```

I made this associations inside my others table

```javascript
// Recette table
recette.belongsToMany(models.Ingredient, { through: models.Contient_Ingredient });
// Ingredient table
ingredient.belongsToMany(models.Recette, { through: models.Contient_Ingredient });
// And Unite table
unite.hasMany(models.Contient_Ingredient);
```

Sorry for my english, i know it's very bad :)
Thank you for your answer ;)

**Comment by sushantdhiman** [comment]
Follow the issue template
