### ISSUE TITLE
Values for ENUM have not been defined

### ISSUE THREAD

**Issue by dschinkel** [sequelize/sequelize#8778]
New sequalize user.  Looked at your docs.  Looked at stack.  No luck

```
sequelize.js:1119
 throw new Error('Values for ENUM have not been defined.');
^

Error: Values for ENUM have not been defined.

```

What am I missing?

my migration file:

```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('media', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      uuid: {
        type: Sequelize.UUID
      },
      status: {
        type: Sequelize.ENUM('Injesting', 'Uploaded', 'Processing', 'Transcoded', 'Failed')
      },
      status_code: {
        type: Sequelize.INTEGER
      },
      created_at: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updated_at: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updated_by: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('media');
  }
};
```

**Comment by dschinkel** [comment]
Christ, can anyone update the docs?

`Sequelize.ENUM('Injesting', 'Uploaded', 'Processing', 'Transcoded', 'Failed')`

should be

`Sequelize.ENUM(['Injesting', 'Uploaded', 'Processing', 'Transcoded', 'Failed'])`

I'm surprised that has not been updated after all this time

**Comment by dschinkel** [comment]
resolved, defined enum in model instead of migration

```
    status: {
      type: DataTypes.ENUM,
      values: ['Injesting', 'Uploaded', 'Processing', 'Transcoded', 'Failed']
    },
```

**Comment by akhilthakurmusic** [comment]
Facing issue..

sequelize.js:1235
        throw new Error('Values for ENUM have not been defined.');
        ^

**Error: Values for ENUM have not been defined.**



**Migration File**

'use strict';

const { DataTypes, Model } = require("sequelize/types");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.createTable('Categories', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      name: {
        type: Sequelize.STRING(50),
        allowNull:false
      },
      status: {
        type: Sequelize.ENUM('1','0'),
        defaultValue: '1'
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE,
        defaultValue:Sequelize.literal("CURRENT_TIMESTAMP")
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE,
        defaultValue: Sequelize.literal("CURRENT_TIMESTAMP")
      }
    });
    
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.dropTable('Categories');
  }
};



**Model File**

'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class Category extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  };
  Category.init({
    name: DataTypes.STRING,
    status: DataTypes.ENUM('1', '0')
  }, {
    sequelize,
    modelName: 'Category',
  });
  return Category;
};
