### ISSUE TITLE
MSSQL - automatic timestamps don't use SQL functions

### ISSUE THREAD

**Issue by moliver-bb** [sequelize/sequelize#8779]
## What are you doing?
Using the mssql dialect and the automatic createdAt/modifiedAt timestamps, Sequelize is passing a timestamp created by the node server instead of using a SQL function.

## What do you expect to happen?
The UPDATE command should use SQL function rather then pass Datetime. Would be great if we can define the function to be used in the Model configuration, I would much rather use GETUTCDATE() instead of just GETDATE()

## What is actually happening?
info: Executed (default):
```sql
UPDATE [Markups] SET [private]=1,[modifiedAt]=N'2017-12-13 23:17:07.675 +00:00' OUTPUT INSERTED.* WHERE [id] = N'F9C9E4EA-332F-433D-B42D-09001E1096DD' 
```
Query Execution Time: 15ms

__Dialect:__ mqsql
__Dialect version:__ tedious 2.1.1
__Database version:__ SQL Server 2016
__Sequelize version:__ 4.28.1
__Tested with latest release:__ yes, 4.28.1

**Comment by moliver-bb** [comment]
to be clear, my Model configuration looks like: 

```js
{
  timestamps: true,
  updatedAt: 'modifiedAt',
}
```

**Comment by iamjoyce** [comment]
Why? What's wrong with the current method?

**Comment by moliver-bb** [comment]
the main issue is clock drift when you have multiple node servers, we use SQL server as our source of truth for time. (this is primarily used/valuable for auditing purposes)

**Comment by becauseinterwebs** [comment]
I'm noticing the same issue.  I am using MySQL the createdAt fields are being set to 6 hrs in the future.  I don't see a place to configure that.  It SHOULD be using the SQL server date/time functions, or at least allow for an offset configuration.  The application has a lot of time-based alerts so it it causing an issue.

**Comment by moliver-bb** [comment]
still an issue.
