### ISSUE TITLE
node process doesn't terminate with sequelize 4.28.1

### ISSUE THREAD

**Issue by sfali16** [sequelize/sequelize#8781]
## What are you doing?

When using sequelize 4.28.1 to connect to a postgres db and sync schema, the node process never terminates. If i switch to sequelize 4.28.0, the node process terminates just fine.

```js
// code here

const sequelize = new Sequelize('postgres', 'postgres', 'pass', {
  host: 'localhost',
  dialect: 'postgres',
  logging: (query) => {
    console.log(`PG QUERY: ${query}`);
  },
});

const minimist = require('minimist');
const Promise = require('bluebird');
const Sequelize = require('sequelize');

const args = minimist(process.argv.slice(2), {
});
return sequelize.authenticate()
  .then(() => {
    console.log('Successfully connected to database');
    return sequelize.sync()
      .then(() => {
        console.log('Successfully synced tables');
        return Promise.resolve(true);
      })
      .catch((err) => {
        console.error('Error encountered when syncing tables: ' + err);
        return Promise.rejected(false);
      });
  })
  .then(() => {
    sequelize.close();
    return Promise.resolve(true);

  })
  .catch((err) => {
    console.error('Error encountered when connection to postgres: ' + err);
    sequelize.close();
    return Promise.rejected(false);
  });
```

## What do you expect to happen?
Throw the above code in a file.js and run 
> node file.js

The node command will output 'Successfully synced table' and then terminate.

## What is actually happening?
The node command displays the output but never terminates - you have to hit Ctrl+C. If you switch to 4.28.0, it terminates successfully.

_Output, either JSON or SQL_

__Dialect:__ postgres (I have not tried other dialects)
__Dialect version: pg 6.4.2
__Database version: postgres 10.1
__Sequelize version: sequelize 4.28.1
__Tested with latest release:Yes

**Comment by sushantdhiman** [comment]
Lets remove https://github.com/sequelize/sequelize/blob/ccee348cd24719d4bd87a6acee5d4a9a6486110f/lib/dialects/abstract/connection-manager.js#L46 and depend upon `close` entirely
