### ISSUE TITLE
Online documentation down

### ISSUE THREAD

**Issue by pakokrew** [sequelize/sequelize#8794]
Hey, I know this is not the first issue about this, but the online documentation is down so often...

Free and available hosting for open source project is so common (github pages, netlify...) could you migrate to one of this one ?

You have a great library, let us read the doc when we need !

**Comment by janmeier** [comment]
We are actually paying for surge.sh hosting so it's troubling to hear that it's sometimes not available.

I haven't personally experienced this. Where are you trying to access the site from?

**Comment by pakokrew** [comment]
It's not always broken, and I tried from many different locations. When it's broken for me, the root page is working (http://docs.sequelizejs.com/) but the others url are not (ex: http://docs.sequelizejs.com/manual/tutorial/models-definition.html)
Today its working.
