### ISSUE TITLE
sequelize findOrCreate not working

### ISSUE THREAD

**Issue by shajunr88** [sequelize/sequelize#8799]
## What are you doing?
I tried to use findOrCreate in sequleize  in postgres DB 

```js
try{
       let newUserInfo = {};
        const user_info_update = await UserInfo.findOrCreate({defaults:newUserInfo,where:{user_id:user_id}});
        if (!user_info_update) {
          throw new Error('could_not_update_user');
        }

    } catch(error) {
    console.log(error);
    return res.status(400).send({ status: false,message: 'Failed to update user.Try Again!.'});
    }
```

## What do you expect to happen?
If rows does not exists,new row should be added and if row already exists,it should be updated

## What is actually happening?
Executing (ad00b6c9-a2f9-4ea5-a66e-2866180d9919): START TRANSACTION;
Executing (ad00b6c9-a2f9-4ea5-a66e-2866180d9919): SELECT "id", "user_id", "phone", "address1", "address2", "country", "image", "created_at", "updated_at" FROM "user_info" AS "user_info" WHERE "user_info"."user_id" = 112 LIMIT 1;
Executing (ad00b6c9-a2f9-4ea5-a66e-2866180d9919): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "user_info", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_eeb50f277aa84eda880b34ec3dd207a1$ BEGIN INSERT INTO "user_info" ("id","user_id","phone","address1","address2","country","image","created_at","updated_at") VALUES (DEFAULT,112,'8129466679','tc 16-1790 thycaud po jagathy ','trivandrum','india','test_image','2017-12-19 05:40:41.941 +00:00','2017-12-19 05:40:41.941 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_eeb50f277aa84eda880b34ec3dd207a1$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
Executing (ad00b6c9-a2f9-4ea5-a66e-2866180d9919): COMMIT;
TypeError: Cannot read property '0' of undefined

_Output, either JSON or SQL_

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ 9.5
__Sequelize version:__ 4.26.0
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/8043
