### ISSUE TITLE
Sequelize failed to find 'array_append'

### ISSUE THREAD

**Issue by aeroxy** [sequelize/sequelize#8800]
## What are you doing?

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('node', 'abc', '123', {
  host: '1.2.3.4',
  dialect: 'postgres',
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
  operatorsAliases: false
});
var postgres = sequelize.define('transactions', {
  transaction: Sequelize.STRING,
  result: Sequelize.INTEGER,
  kind: Sequelize.STRING,
  timestamp: Sequelize.STRING,
  durations: Sequelize.ARRAY(Sequelize.FLOAT),
  traces: Sequelize.JSONB
});
postgres.sync();
var data = [{
  transaction: 'test',
  result: 200,
  kind: 'request',
  timestamp: '2017-07-07',
  durations: [1.01234, 2.02345, 3.02345]
}];
data.forEach((transaction, key)=>{
  if (!!transaction.timestamp) {
    var obj = transaction;
    obj.traces = {a: 'hello'};
    postgres.create(obj);
    postgres.update({
      durations: sequelize.fn('array_append', sequelize.col('durations'), 4.02345),
    },{
      where: {
        transaction: obj.transaction,
        result: obj.result,
        kind: obj.kind,
        timestamp: obj.timestamp
      }
    }).catch(e => console.log(e));
  }
});
```

## What do you expect to happen?
transactions => obj => durations = [1.01234, 2.02345, 3.02345, 4.02345]

## What is actually happening?

>      error: function array_append(integer[], numeric) does not exist
> name: 'error',
>      length: 225,
>      severity: 'ERROR',
>      code: '42883',
>      detail: undefined,
>      hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
>      position: '39',
>      internalPosition: undefined,
>      internalQuery: undefined,
>      where: undefined,
>      schema: undefined,
>      table: undefined,
>      column: undefined,
>      dataType: undefined,
>      constraint: undefined,
>      file: 'parse_func.c',
>      line: '523',
>      routine: 'ParseFuncOrColumn',
>      sql: 'UPDATE "transactions" SET "durations"=array_append("durations", 4.02345),"updatedAt"=\'2017-12-19 11:20:03.481 +00:00\' WHERE "transaction" = \'test\' AND "result" = 200 AND "kind" = \'request\' AND "timestamp" = \'2017-07-07\''
>      Unhandled rejection SequelizeDatabaseError: malformed array literal: "[1.01234,2.02345,3.02345]"

__Dialect:__ postgres
__Dialect version:__ 7.4.0
__Database version:__ XXX
__Sequelize version:__ 4.28.6
__Tested with latest release:__ Yes

**Comment by subashCognitive** [comment]
Is there any update on this issue?

**Comment by aeroxy** [comment]
> Is there any update on this issue?

Nope. I just stopped using Sequelize.
