### ISSUE TITLE
Virtual field behavior documentation

### ISSUE THREAD

**Issue by darkalor** [sequelize/sequelize#8801]
## What are you doing?
Trying to use a VIRTUAL field in a model and getting unexpected (from my point of view) results. The documentation does not provide a clear picture of how it's supposed to work.
It is not clear whether it's actually an issue with me misunderstanding the expected behavior or a problem with the library.

Define model:
```js
  const User = connection.define('User', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    index: DataTypes.VIRTUAL,
  }, {
    tableName: 'users',
    timestamps: false,
  });
```

Create tables:
```
sequelize.sync({force: true});
```
Gives an error, despite what the docs say "A virtual value that is not stored in the DB"
```
[13:37:42] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER auto_increment , `index` VIRTUAL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VIRTUAL, PRIMARY KEY (`id`)) ENGINE=InnoDB' at line 1
```

Find records:
```
User.findAll()
```
Gives an error, as it tries to select the virtual field from the DB. Not clear why it tries to select a field "that is not stored in the DB"
```
[13:42:31] Executing (default): SELECT `id`, `index` FROM `users` AS `User`;
(node:3152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SequelizeDatabaseError: Unknown column 'index' in 'field list'
```

## What do you expect to happen?
Either:
a) VIRTUAL fields not being added to queries, or 
b) Clear documentation on the expected behavior, as the current documentation implies that these work similarly to the `get/set` methods.

__Dialect:__ mysql 
__Dialect version:__  5.7.20
__Database version:__ XXX
__Sequelize version:__ 4.28.6
__Tested with latest release:__ yes

**Comment by hereisfun** [comment]
got the same problem.
Tried to just paste the code from documentation: 
```js
sequelize.define('user', {
  password_hash: DataTypes.STRING,
  password: {
    type: DataTypes.VIRTUAL,
    set: function (val) {
       // Remember to set the data value, otherwise it won't be validated
       this.setDataValue('password', val);
       this.setDataValue('password_hash', this.salt + val);
     },
      // ...
  }
})
```

which results in the same error

And it makes me confused that Sequelize execute SQL like:
```sql
'password' VIRTUAL NOT NULL
```

which seems an invalid SQL

wondering the correct usage of `DataTypes.VIRTUAL`

**Comment by darkalor** [comment]
We just gave up on using on sequelize to actually create tables and added `except` to selects :man_shrugging:
