### ISSUE TITLE
Single Server multiple database connection

### ISSUE THREAD

**Issue by Akshayprmar** [sequelize/sequelize#8811]
## Have create a sequelize connection and request time i have change the database name.
`sequelize .config.database = "DatabaseName";`
`sequelize .connectionManager.config.database =  "DatabaseName";`

## What do you expect to happen?
Database name change but it's not giving previous database data.

## What is actually happening?
first call it's giving previous database response but second call it's giving updated database response.

**Comment by janmeier** [comment]
Sequelize uses a connection pool - Probably the first request are getting a cached connection to the old database. In theory you can empty the pool, but I would very much recommend creating a new sequelize instance instead.
