### ISSUE TITLE
MySQL - JSON column should not have a DEFAULT value when creating table

### ISSUE THREAD

**Issue by njLT** [sequelize/sequelize#8814]
## What are you doing?
Assigning a default value to a JSON field.

```js
  permissions: {
    type: Sequelize.JSON,
    defaultValue: [],
  }
```

## What do you expect to happen?
work as expected

## What is actually happening?
error on creating table - invalid syntax 

_Output, either JSON or SQL_
CREATE TABLE IF NOT EXISTS ... `permissions` JSON DEFAULT ,  ...  ENGINE=InnoDB;

SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `password_hash` VARCHAR(255), `password_salt` VARCHAR(255), `created_at` DATETI' at line 1

__Dialect:__ mysql
__Dialect version:__ 1.5.1
__Database version:__ 5.7
__Sequelize version:__  4.26.0
__Tested with latest release:__ 4.28.6 (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

JSON columns do not [support](https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html) a default value in MySQL. [This](https://github.com/sequelize/sequelize/blob/v4.28.6/lib/dialects/mysql/query-generator.js#L324) should include JSON and GEOMETRY as well so as not to assign a default value.

**Comment by mccabemj** [comment]
I have added a pull request for this issue, stopping the SQL adding the default values if provided for all non-allowed data types #8839

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/74d2b5f1da49fb80575543efc52d99a3495720d0
