### ISSUE TITLE
"is" executes as "is not"

### ISSUE THREAD

**Issue by rodic** [sequelize/sequelize#8816]
## What are you doing?

```ts
function delete(anId: number): Promise<number> {
  return Model.destroy({
    where: {
      anId,
      completedAt: { [Op.is]: null }
    }
  });
}
```
## What do you expect to happen?
```
Executing (default): DELETE FROM "Models" WHERE "anId"= 55 AND "completedAt" IS NULL 
```

## What is actually happening?
```
Executing (default): DELETE FROM "Models" WHERE "anId"= 55 AND "completedAt" IS NOT NULL 
```

__Dialect:__ postgres
__Dialect version:__ 
__Database version:__ 9.5.10
__Sequelize version:__ 4.28.0
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by iamjoyce** [comment]
FYI, You can use `completedAt: { [Op.eq]: null }` to get `"completedAt" IS NULL`

**Comment by rodic** [comment]
hi @iamjoyce thanks. yes, i'm using that.

**Comment by mccabemj** [comment]
@rodic no you are not. You are using Op.is. Use Op.eq for equal.

**Comment by iamjoyce** [comment]
@mccabemj I think @rodic is using `Op.eq` for his system. He is right about the bug where `Op.is` translates to `IS NOT NULL` in SQL statement, which is incorrect.

**Comment by iamjoyce** [comment]
@mccabemj I think @rodic is using `Op.eq` for his system. He is right about the bug where `Op.is` translates to `IS NOT` in SQL statement, which is incorrect.

**Comment by mccabemj** [comment]
@iamjoyce sorry, I misunderstood the issue.

@rodic I am actually able to recreate the issue and I think its a bug. Line 2392 of /sequelize/lib/dialects/abstract/query-generator.js

I believe that should be 
`} else if (value === null && comparator ===  this.OperatorMap[Op.ne]) {`

At the moment its evaluating that `Op.ne` is in the `OperatorMap` (which it obviously is) so using `this.OperatorMap[Op.not]`. It then never gets to line 2396 to use the `IS`.

I'm new to GitHub, but I am actively trying to get involved, so would like to do a pull request if people confirm the bug.

**Comment by mccabemj** [comment]
Added pull request to fix this - https://github.com/sequelize/sequelize/pull/8835

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/commit/3397b237db2c673b6e7df84c99b773f989bcea0b
