### ISSUE TITLE
Querying over a model connected with n:m relation returns join table in response.

### ISSUE THREAD

**Issue by kevinvugts** [sequelize/sequelize#8818]
## What are you doing?

I've got 2 models: Venue and Employee. There are connected with a many-to-many relation in mysql dialect. I've wired up the relations like following:

``` js
models.Venue.belongsToMany(models.Employee, { through: 'EmployeeVenues' }) 
models.Employee.belongsToMany(models.Venue, { through: 'EmployeeVenues' })
```

I am trying to query for example all Venues for employee with id equals to 1:

```js
router.get('/api/v1/users/:employee_id/venues', (request, response) => {
  var employeeId = request.params.employee_id;

  models.Employee.find({
    where: {id: employeeId},
    include: [
      {
        model: models.Venue
      }
    ]
  }).then((employee) => {

    if(!employee) { return response.status(400).send("Employee doesnt have a venue registered yet.")}
    var venues = employee.getVenues().then((venues) => {
      response.status(200).send(employee);
    })
  })
});
```

## What do you expect to happen?

I expect the result to be:

``` {
    "id": 1,
    "user_id": 2,
    "group_id": 1,
    "Venues": [
        {
            "id": 1,
            "capacity": "400",
            "venue_name": "Club Lotte",
            "venue_description": "Club in Rotterdam"
        },
        {
            "id": 2,
            "capacity": "400",
            "venue_name": "Club Dino",
            "venue_description": "Club in Rotterdam"
        }
    ]
}
```

## What is actually happening?
The output includes the join table as well which should not be. I've found an issue here on the github that solves it by adding: through: { attributes: [] }. However this is not in the docs, so is this the way it should be?

```
{
    "id": 1,
    "user_id": 2,
    "group_id": 1,
    "Venues": [
        {
            "id": 1,
            "capacity": "400",
            "venue_name": "Club Lotte",
            "venue_description": "Club in Rotterdam",
            "EmployeeVenues": {
                "employee_id": 1,
                "venue_id": 1
            }
        },
        {
            "id": 2,
            "capacity": "400",
            "venue_name": "Club Dino",
            "venue_description": "Club in Rotterdam",
            "EmployeeVenues": {
                "employee_id": 1,
                "venue_id": 2
            }
        }
    ]
}

```

__Dialect:__ mysql
__Dialect version:__mysql2 1.5.1
__Database version:__ Sequel Pro 1.1.2
__Sequelize version:__ 4.22.8
__Tested with latest release:__ No (If yes, specify that version)

**Comment by mccabemj** [comment]
As its a many-to-many relationship you need to explicitly say you don't want the EmployeeVenues attributes, so yes, adding `through: { attributes: [] }` is the way to do it. I can add this to the documentation

**Comment by janmeier** [comment]
@mccabemj Is correct. The option is mentioned in the API docs (http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll), but it would be fine to add this to the tutorial as well

**Comment by kevinvugts** [comment]
@janmeier thank you!

**Comment by kevinvugts** [comment]
@janmeier @mccabemj 

How can I do the same with the automagically added methods from Sequelize (e.g) 

Is it like this? 

```
user.getVenues({
 through: { attributes: [] }
})
```

**Comment by mccabemj** [comment]
I believe you can specify the join table attributes

`user.getVenues({ joinTableAttributes: [] });`

I haven't tried it myself. Let me know if it works

**Comment by kevinvugts** [comment]
@mccabemj that solved the problem, thanks. Where did you found this in the docs?

**Comment by mccabemj** [comment]
@kevinvugts http://docs.sequelizejs.com/manual/tutorial/associations.html#associating-objects

**Comment by musicformellons** [comment]
The 
```
        through: {
          attributes: []
        }
```
also works for [join-table you configured yourself](https://stackoverflow.com/questions/52150349/can-you-hide-output-from-a-not-automatically-generated-join-table-using-sequel) (so not auto-magically via `belongsToMany`.
