### ISSUE TITLE
There are no docs for QueryInterface.bulkUpdate()

### ISSUE THREAD

**Issue by ataujenis** [sequelize/sequelize#8820]
## What are you doing?
I'm trying to find the docs for `QueryInterface.bulkUpdate()`.

## What do you expect to happen?
I see this is an available public method in the source code and I would expect to find docs: https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L967

## What is actually happening?
I can't find any documentation on the `QueryInterface.bulkUpdate()` method: http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html

__Tested with latest release__

**Comment by sushantdhiman** [comment]
I think you meant `bulkUpdate` (your link point to `bulkInsert`) https://github.com/sequelize/sequelize/blob/bb2d0bd9c1765940024974a6de3e05d07830a388/lib/query-interface.js#L1003

Tagging as documentation

**Comment by ataujenis** [comment]
@sushantdhiman That link I provided was to a specific line-number in the source file. It looks like that source file was updated 4 hours ago and changed the line positions. You are correct: the link should point to the `bulkUpdate` method.

**Comment by cyrilchapon** [comment]
Any update on this ?

Even on update method ?

**Comment by cyrilchapon** [comment]
related https://github.com/sequelize/sequelize/issues/8687

**Comment by Songkeys** [comment]
Any update after half a year...?

**Comment by ptimson** [comment]
+1

**Comment by chaim1221** [comment]
💀

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/10005
