### ISSUE TITLE
support create / drop database with query interface

### ISSUE THREAD

**Issue by MatheusVellone** [sequelize/sequelize#8821]
## What are you doing?
I'm trying to create a new schema with mysql using migrations

```js
module.exports = {
  up(queryInterface) {
    return queryInterface.createSchema('admin')
  },
  down(queryInterface) {
    return queryInterface.dropSchema('admin')
  },
}

```

## What do you expect to happen?
The schema to be created

## What is actually happening?
Schema not being created :cry: 

## Aditional info
Did a little research to understand what's happening and found this line https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query-generator.js#L19, which returns the `SHOW TABLES` SQL instead of a `CREATE DATABASE`

As a workaround, I could change the `queryInterface.createSchema` with `queryInterface.sequelize.query` and put my `CREATE DATABASE` query, which gives me exactly what I need. Just reporting a broken functionality (i guess it's broken)

If you need more info about it, just let me know :)

EDIT: Just to avoid confusion
> CREATE DATABASE creates a database with the given name. To use this statement, you need the CREATE privilege for the database. CREATE SCHEMA is a synonym for CREATE DATABASE.

https://dev.mysql.com/doc/refman/5.7/en/create-database.html

__Dialect:__ `mysql`
__Dialect version:__ `1.5.0`
__Database version:__ `8.0.3-rc-log`
__Sequelize version:__ `4.28.6`
__Tested with latest release:__ Yes, versions above

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by MatheusVellone** [comment]
Found this issue #1379 which reported the same problem.

Despite being a massive breaking change, I didn't fully got why not to support multiple schemas through prefixes.
In my case the prefixes would not only solve this `createSchema` problem, but also all my multi-tenant queries, which I would be able to just prefix the table with any schema in my database.

I'm open to provide more details/use cases if you need or want to.
Also, I can try contributing with some PRs to help with these changes.

**Comment by sushantdhiman** [comment]
Schema and batabase are different concept, they may be interchangeable in MySQL but are very different for other databases.

What you are looking for is `createDatabase / dropDatabase` statement which I am afraid we dont support yet. But I will be happy to accept an PR which add `create/drop database` support to query interface
