### ISSUE TITLE
Transaction rollback fails

### ISSUE THREAD

**Issue by ahmedkhan847** [sequelize/sequelize#8822]
## What are you doing?
I am unable to rollback a transaction after its creation. I am using Sync to sync one of my function I am logging in then if response comes true I want to commit transaction else rolls back it.
```js
sequelize
          .transaction({autocommit:false},function(t) {
            return sequelize.models.Customer.create(params, { transaction: t })
              .then(function(data) {               
                helpers.Sync(function() {
                  var result = general.sendRequestBilling.sync(
                    null,
                    helpers,
                    "/create-customer",
                    "POST",
                    params
                  );
                  
                  if (result.status) {

                    callback(null, { status: false, data: data });
                  } else {
                    apiError = result;
                    status = result.status;
                    return t.rollback();
                  }
                });
                
              })
              .catch(function(error) {
                var errors = {};
                if (helpers.general.count(error) > 0)
                  errors = helpers.general.mapErrors(
                    error.errors,
                    sequelize.models.Customer.lables
                  );

                callback(null, { status: false, data: errors });
              });
          })
          .catch(function(err) {
            callback(null, { status: false, data: { error: apiError } });
          });
```

## What do you expect to happen?
I want my transaction to commit back if that fails. 

## What is actually happening?
it is not rolling back

##Log
Executing (default): SELECT `partnerID`, `userName`, `password`, `partnerKey` FROM `partner` AS `Partner` WHERE `Partner`.`userName` = 'STORM' AND `Partner`.`password` = '123456' AND `Partner`.`partnerKey` = 'key2' LIMIT 1;
Executing (37ff09dc-694d-41c7-8489-5bdeaef9551c): START TRANSACTION;
Executing (37ff09dc-694d-41c7-8489-5bdeaef9551c): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (37ff09dc-694d-41c7-8489-5bdeaef9551c): SET autocommit = 0;
Executing (default): SELECT `partnerID`, `userName`, `password`, `partnerKey` FROM `partner` AS `Partner` WHERE `Partner`.`partnerID` != 3 AND (`Partner`.`partnerID` = 2) LIMIT 1;
Executing (default): SELECT `communityID`, `zappwareCommunityID`, `communityTitle`, `createAt`, `updateAt` FROM `community` AS `Community` WHERE `Community`.`communityID` = '1';
Executing (37ff09dc-694d-41c7-8489-5bdeaef9551c): INSERT INTO `customer` (`customerCellNo`,`passwordKey`,`customerEmail`,`customerPassword`,`customerFullName`,`customerAddress`,`partner_partnerID`,`status`,`isPaid`,`communityID`,`createDate`,`modifiedDate`) VALUES ('03452122184','pLL5ob6b54fZpyXA4gXR7JxTVnzrg5eTSIIJMyhJSXVgtZ3qtf','ahmed.khan84@laksol.com','02d333a464a20bd99e1d2a2d06e0731f98f06917622f3a0b0f021d2446a1166b67ff7d2ad0305694a3d41113dfcf3018F2xE2z9C2D6Pqk5uQYwu6g==','Ahmed Khan','1160 15 F B Area Dastagir Karachi',2,'Disabled',0,'1','2017-12-29 15:44:39','2017-12-29 15:44:39');
Executing (37ff09dc-694d-41c7-8489-5bdeaef9551c): COMMIT;
Executing (default): INSERT INTO `api_log` (`api_logID`,`apiName`,`request`,`results`,`type`,`externalSystem`,`callingEntity`,`isFailed`,`partner_partnerID`,`timestamp`) VALUES (NULL,'undefined undefined','http://localhost:4000/create-customer','{\"status\":false,\"BillingCustomerID\":63,\"message\":\"scucess\"}','External','Billing',NULL,false,NULL,'2017-12-29 15:44:39');
Executing (default): INSERT INTO `api_log` (`api_logID`,`apiName`,`request`,`results`,`type`,`callingEntity`,`isFailed`,`partner_partnerID`,`timestamp`) VALUES (NULL,'POST /add-customer?token=key2','{\"mobile_number\":\"03452122184\",\"email\":\"ahmed.khan84@laksol.com\",\"fullname\":\"Ahmed khan\",\"address\":\"1160/15 F.B. Area Dastagir Karachi\",\"password\":\"Ahmedkhan923\",\"community_id\":\"1\",\"userid\":2}','{\"status\":false,\"message\":\"Customer save failed\",\"data\":{},\"errors\":{\"error\":{\"status\":false,\"data\":{\"status\":false,\"BillingCustomerID\":63,\"message\":\"scucess\"}}}}','Internal','Partner',1,2,'2017-12-29 15:44:39');
POST /customers/add-customer?token=key2 200 1238.773 ms - 162

__Dialect:__ mysql 
__Dialect version:2.12.0
__Database version:5.6
__Sequelize version:3.24.6
__Tested with latest release: No

**Comment by janmeier** [comment]
Where is `callback` coming from? It seems you mixing callbacks and promises.
`.transaction` return a promise, you can use `.transaction(....).asCallback(callback)` in order to work with APIs that require callbacks. http://bluebirdjs.com/docs/api/ascallback.html

When you pass a function to `.transaction` the transaction will be managed (http://docs.sequelizejs.com/manual/tutorial/transactions.html#managed-transaction-auto-callback-) which means you don't have to call commit or rollback yourself - The transaction is comitted / rolled back depending on the result of the promise you return

**Comment by ahmedkhan847** [comment]
Callback is coming from Sync library which use to make sync node js execution. It is coming from my controller.

**Comment by ahmedkhan847** [comment]
I have also tried to use Unmanaged transaction but when I extend my code I am unable to rollback the transaction.

**Comment by sushantdhiman** [comment]
Transaction rollback works properly, here are some tests https://github.com/sequelize/sequelize/blob/1fff80fde139ab748e927589ba0275e300deccb0/test/integration/transaction.test.js#L49

There is something wrong with code flow in your application, possibly improper use of promises causing this issue.

I am closing this issue as its a userland bug, if you can isolate this issue and submit a test case with bare sequelize I will reopen it
