### ISSUE TITLE
model.getAssociations() can't get updated results after remove/add/update associated models

### ISSUE THREAD

**Issue by pangz1** [sequelize/sequelize#8825]
I am trying to get the updated records after calling removeAssociations() on one of my models, the records have been removed successfully, but the results remain unchanged at the moment when the getAssociations() was called.

here is my code
```js
function deleteOrderDetails(orderId, idsToDelete) {
   return db.sequelize.client.transaction(async t => {
    return db.sequelize.Orders.findOne({
      where: {
        id: orderId
      },
    })
     .then(order => {
          if (order) {
               return order.removeOrderDetails(idsToDelete, { transaction: t })
                      .then(_ => {
                           return order.getOrderDetails()
                      })
          }
     })
     .then(orderDetails => {
            let plainDetails = orderDetails.map(item => item.get({ plain: true }))
            console.log( plainDetails )   // still get the removed records
      })
   
}

```

my models
```js
const Orders = sequelize.define('Orders', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    user_id: {
      type: DataTypes.INTEGER,
      allowNull: false
    }
  }, {
    underscored: true
  })
const OrderDetail = sequelize.define(
    'OrderDetail',
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true
      },
      qty: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: 1
      },
      price: {
        type: DataTypes.FLOAT,
        allowNull: false
      },
    },
    {
      underscored: true,
    }
  )
Orders.hasMany(models.OrderDetail)
OrderDetail.belongsTo(Orders)
```
here is the log from the terminal

id = 44 was removed, but still shows up when executing the query

Executing (777d8f21-8374-4cf1-80e1-a5b00df66b50): UPDATE `OrderDetail` SET `order_id`=NULL,`updated_at`='2017-12-31 14:25:00' WHERE `order_id` = 11 AND `id` IN (44)
Executing (default): SELECT `id`, `qty`, `price`, `status`, `created_at`, `updated_at`, `order_id`, `product_info_id` FROM `OrderDetail` AS `OrderDetail` WHERE `OrderDetail`.`order_id` = 11;
[ { amount: 22.77,
    id: 43,
    qty: 3,
    price: 7.59,
    status: 1,
    created_at: 2017-11-22T15:15:49.000Z,
    updated_at: 2017-11-22T15:15:49.000Z,
    order_id: 11,
    product_info_id: 20 },
  { amount: 30.36,
    id: 44,
    qty: 4,
    price: 7.59,
    status: 1,
    created_at: 2017-11-22T15:15:49.000Z,
    updated_at: 2017-11-22T15:15:49.000Z,
    order_id: 11,
    product_info_id: 21 } ]

**Comment by janmeier** [comment]
You need to pass `transaction` to `getOrderDetails` or commit the transaction
