### ISSUE TITLE
Ability to do use table hints per query with MSSQL

### ISSUE THREAD

**Issue by mccabemj** [sequelize/sequelize#8830]
## What are you doing?
If I want only one target table to require a lock-less state, this is not possible. You can only set the isolation level to the entire transaction. I'd like to be able to set the NOLOCK table hint (or any other table hint) to limit that isolation level or suggest other options to the specific query.

## What do you expect to happen?
To be able to set NOLOCK on a specific select query, not the entire transaction

## What is actually happening?
This is not possible.

I'd like to take a stab at this, if someone thinks it would be beneficial.

__Dialect:__ mssql
__Dialect version:__ 6.4.2
__Database version:__ XXX
__Sequelize version:__ 4.28.6
__Tested with latest release:__ Yes

**Comment by janmeier** [comment]
Sounds good to me, go for it!

**Comment by mccabemj** [comment]
Upon coding this, I decided it would be better to allow other table hints, instead of just allowing NOLOCK. So I have changed the title and description of this issue and have done a pull request for the feature #8843

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/11ff7764819f2812018f3a7b8fa16ba1851e8c4d
