### ISSUE TITLE
postgres replication - use master if replica connection fails

### ISSUE THREAD

**Issue by contra** [sequelize/sequelize#8832]
## What you are doing?

One write master, one read replica.

## What do you expect to happen?

If the read replica goes offline or fails to connect, read queries should be executed on the master.

## What is actually happening?

If the read replica goes offline all read-only queries fail to execute.

__Dialect:__ postgres
__Database version:__ 9.6.1
__Sequelize version:__ all

(duplicate of #7180 which got closed by the buggy @stale bot)

**Comment by sushantdhiman** [comment]
I have reopened https://github.com/sequelize/sequelize/issues/7180, so closing this one.

Now @stale bot wont close issues with label like `feature` / `bug` etc but it still keep closing issues older than last config update
