### ISSUE TITLE
One Post From Each User query via Sequelize

### ISSUE THREAD

**Issue by personapp** [sequelize/sequelize#8834]
I am trying to write a query resolver via Sequelize and node.js

There are 3 models as `Group`, `Post` and `User`. I want to fetch Posts (one post from each user) that sent to Group. The associations are like that.

```
Group.belongsToMany(Post, { through:'GroupPost' });

Post.belongsToMany(Group, { through:'GroupPost' });

Post.belongsTo(User, { as:'creator' });

User.hasMany(Post, { as:'createdPosts' }); 
```
And my actual resolver for `Group.inbox` is:

```
Post.findAll({
    where: { targetId: group.id },
    order: [['id', 'DESC']],
    limit: first || last,    // I use Relay-Cursor-Connections
    include: [{
        model: User,
        association: 'creator',
        duplicating: false,
    }]
});
```
But this resolver does not give me the expected result. It returns all the Posts that sent to Group.

I want to fetch Posts (one post from each user) that sent to Group.

How can I do that ???

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
