### ISSUE TITLE
When a fk is defined both with a relation and a model, the onDelete is set to CASCADE instead of SET NULL if "allowsNull" is not set to true even if it is its default value

### ISSUE THREAD

**Issue by petersg83** [sequelize/sequelize#8837]
When a fk is defined both with a relation and a model, the onDelete is set to CASCADE instead of SET NULL if "allowsNull" is not set to true in the model definition even if it is its default value.

We can easily see it there: https://github.com/sequelize/sequelize/blob/3397b237db2c673b6e7df84c99b773f989bcea0b/lib/associations/has-many.js#L125
The default values are not taken into account if the fk is defined in the model whereas the attributes are not defined.

I don't think it is a wanted behavior so I'll propose a fix.

Please, tell me if I misunderstood something

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/8838#issuecomment-382740925
