### ISSUE TITLE
N:M Check associations is not working as mentioned in the docs

### ISSUE THREAD

**Issue by bharathvaj1995** [sequelize/sequelize#8844]
## What are you doing?

```js
// code here
From Sequelize docs
// check if all associated objects are as expected:
// let's assume we have already a project and two users
project.setUsers([user1, user2]).then(() => {
  return project.hasUsers([user1]);
}).then(result => {
  // result would be false
  return project.hasUsers([user1, user2]);
}).then(result => {
  // result would be true
})
```

## What do you expect to happen?
It must work as documented

## What is actually happening?
Not working as documented

```
// Example Scenario
Returns true instead of false for this scenario
If project as 2 users user1, user2
project.hasUsers([user1]);  // => returns true instead of false
````

__Dialect : Mysql
__Database version: 5.7
__Sequelize version:__4.13.5

**Comment by sushantdhiman** [comment]
> If project as 2 users user1, user2
project.hasUsers([user1]);  // => returns true instead of false

This is correct behaviour, `has*` check if one or more instance(s) are associated with current instance.

As `user1` is linked to `project` it correctly returns `true` for `project.hasUsers([user1])`

**Comment by bharathvaj1995** [comment]
@sushantdhiman But your docs says false for the example right?

**Comment by sushantdhiman** [comment]
Can you link docs?

**Comment by bharathvaj1995** [comment]
Sure . [here](http://docs.sequelizejs.com/manual/tutorial/associations.html#check-associations)

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/bf7a55babf4a8aacbf05c30c3ac6ef549fe14ffa
