### ISSUE TITLE
Feature request: way for validators to return metadata in the `ValidationErrorItem`s

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#8852]
## What are you doing?

I'm using `flow-runtime` to validate properties within a JSON attribute, and I would like to throw a `ValidationError` with the full path to the invalid attribute, so that I can display the error message in the correct `redux-form` field on the client.

**Basically, I need to include my own metadata in the error thrown when an attribute is invalid, but Sequelize doesn't provide any clean way to do that.**  My only option right now is to serialize the metadata into the error message itself and parse it in my GraphQL resolver. 

```js
import {reify} from 'flow-runtime'
import type {Type} from 'flow-runtime'
import {get} from 'lodash'

import {ValidationError, ValidationErrorItem} from 'sequelize'

function validateFlowRuntimeType(instance, attributeName, type) {
  const value = instance[attributeName]
  const {errors} = validate(type, value)
  if (errors.length) {
    throw new ValidationError(
      `invalid value for ${attributeName}`,
      errors.map(([path, message]: {path: Array<any>, message: string}) => {
        new ValidationErrorItem(
          message,
          'Validation Error',
          [attributeName, ...path].join('.'),
          get(value, path),
          instance
        )
      })
    )
  }
}

type Config = {
  safeState: 0 | 1,
  reversePolarity: boolean,
}
const ConfigType = (reify: Type<Config>)

const Channel = sequelize.define('Channel', {
  config: {
    type: Sequelize.JSON,
    allowNull: false,
    defaultValue: 'DISABLED',
  }
}, {
  validate: {
    validateConfig() {
      validateFlowRuntimeType(this, 'config', ConfigType)
    }
  }
})

await Channel.create({config: {safeState: 0, reversePolarity: 2}})
```

## What do you expect to happen?
Sequelize re-throws my custom `ValidationError` from `validateFlowRuntimeType` (which contains a `ValidationErrorItem` with `path: 'config.reversePolarity'`), or at least copies over the `ValidationErrorItems` from my error.

## What is actually happening?
Sequelize creates its own `ValidationError` with only the `message` from mine, and `path: config` in the `ValidationErrorItem`, and my metadata about the path within the JSON is lost.

__Dialect:__ any
__Sequelize version:__ 4.28.6
__Tested with latest release:__ Yes (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Can you propose an API design how Sequelize will get that extra meta data for error, I suppose it will be different per query.

**Comment by jedwards1211** [comment]
@sushantdhiman I would be happy with it if I could put a `metadata` prop on the `Error` I throw from a custom validate function, and Sequelize would copy that `metadata` prop onto the `ValidationErrorItem` it generates

**Comment by sushantdhiman** [comment]
Seems like a reasonable feature

**Comment by jedwards1211** [comment]
@sushantdhiman actually, I didn't notice that Sequelize attaches the original error to `ValidationErrorItem.__raw`.  This ought to be a "public" property (`raw` instead of `__raw`), so that harvesting metadata from it is officially supported.

**Comment by sushantdhiman** [comment]
We can actually support `original` like `DatabaseError` do, https://github.com/sequelize/sequelize/blob/3cea5c4f84e0b7a5c0ef5548d318d786d495eb4e/lib/errors/index.js#L124

So you can access actual error if you want to

**Comment by jedwards1211** [comment]
When a custom validate throws an error, it generates a ValidationErrorItem that gets combined with other items into a single ValidationError.  So the ValidationError's original field isn't an error that I threw from a custom validator.

**Comment by sushantdhiman** [comment]
`ValidationErrorItem` can contain `original` error, `ValidationError` on other hand contains `errors` so it wont make sense to include original in `ValidationError` directly

**Comment by jedwards1211** [comment]
@sushantdhiman like I was saying, Sequelize already puts the original error in `ValidatorErrorItem.__raw`.  I wouldn't be against renaming that field to `original` though.

**Comment by sushantdhiman** [comment]
renaming it to `original` will align error api

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/commit/efb1f2f40ff393188c9dd0ab6dc692d18b5b4fef
