### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by kamontat** [sequelize/sequelize#8870]
## What are you doing?

- Model
```js
module.exports = (sequelize, DataTypes) => {
  var Food = sequelize.define('Food', {
    name: DataTypes.STRING, 
    allowNull: false, 
    unique: true
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return Food;
};
```

- Controller
```js
 list(req, res) {
        return Food.all()
            .then(foods => res.status(200).send(foods))
            .catch(error => res.status(400).send(error));
}
```

## What do you expect to happen?
List all Food inside database

## What is actually happening?
Error 
```json
{
    "name": "SequelizeDatabaseError",
    "parent": {
        "name": "error",
        "length": 109,
        "severity": "ERROR",
        "code": "42703",
        "position": "22",
        "file": "parse_relation.c",
        "line": "3293",
        "routine": "errorMissingColumn",
        "sql": "SELECT \"id\", \"name\", \"allowNull\", \"unique\", \"createdAt\", \"updatedAt\" FROM \"Food\" AS \"Food\";"
    },
    "original": {
        "name": "error",
        "length": 109,
        "severity": "ERROR",
        "code": "42703",
        "position": "22",
        "file": "parse_relation.c",
        "line": "3293",
        "routine": "errorMissingColumn",
        "sql": "SELECT \"id\", \"name\", \"allowNull\", \"unique\", \"createdAt\", \"updatedAt\" FROM \"Food\" AS \"Food\";"
    },
    "sql": "SELECT \"id\", \"name\", \"allowNull\", \"unique\", \"createdAt\", \"updatedAt\" FROM \"Food\" AS \"Food\";"
}
```

__Dialect:__ `postgres`
__Dialect version:__ `6.4.2`
__Database version:__ `postgres (PostgreSQL) 10.1`
__Sequelize version:__ `4.29.3`
__Tested with latest release:__ No (If yes, specify that version)
__Other version:__ `Sequelize CLI [Node: 9.3.0, CLI: 3.2.0, ORM: 4.29.3]`

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
By default Sequelize create timestamp columns, you defined them in your actual table?

http://docs.sequelizejs.com/manual/tutorial/models-definition.html#timestamps

**Comment by Gecko222** [comment]
Shouldn't your definition lookls like this?:

`var Food = sequelize.define('Food', {
    name: {
        type: DataTypes.STRING, 
        allowNull: false, 
        unique: true
    }
  },`

**Comment by kamontat** [comment]
Oh, I see. Sorry
