### ISSUE TITLE
Autogenerated getter randomly fails to get value from dataValues

### ISSUE THREAD

**Issue by idahogurl** [sequelize/sequelize#8871]
The code below is my model for User. In my Express requests, I have a middleware that queries for the user. It stores the user in the request. I use that user in my graphQL requests. The graphQL resolver receives the request as a parameter.  Sometimes when I call request.id (which is the sequelize user object), I get undefined for id and other times it works.

```js

module.exports = function user(sequelize, DataTypes) {
  return sequelize.define('user', {
    id: { type: DataTypes.UUID, primaryKey: true, defaultValue: DataTypes.UUIDV4, allowNull: false },
    uid: {
      type: DataTypes.STRING,
      unique: true,
    },
    token: {
      type: DataTypes.STRING,
      defaultValue: '---',
    },
    meta: {
      type: DataTypes.JSON,
      defaultValue: {},
    },
    deletedAt: {
      type: DataTypes.DATE,
      defaultValue: null,
    },
  }, {
    paranoid: true,
    indexes: [{
      name: 'user_deletedAt_index',
      method: 'BTREE',
      fields: ['deletedAt'],
    }],
    classMethods: {
      associate({ Publication, User, License }) {
        User.belongsToMany(Publication, { through: License, allowNull: false })
      },
    },
  })
}

//Express middleware
req.user = await User.findById(id)
```
__Dialect:__ postgres
__Database version:__ 10
__Sequelize version:__ 3.X
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Odd behaviour, but cant think of a reason for id to return undefined. Will be able to help if can get reproducible test case

**Comment by idahogurl** [comment]
I'm not sure what I did but its' working now. Thanks for replying.
