### ISSUE TITLE
why sequelize can not get the instance properties of the model，like java's entity class?

### ISSUE THREAD

**Issue by souljessi** [sequelize/sequelize#8875]
## What are you doing?
I want to get each instance attribute of the model before saving and updating, not a custom object，like java entity get and set

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.23.2
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
Please elaborate with proper examples and use-case scenarios
