### ISSUE TITLE
TimeoutError: ResourceRequest timed out at ResourceRequest._fireTimeout

### ISSUE THREAD

**Issue by arun-awnics** [sequelize/sequelize#8877]
## What are you doing?

Trying to run basic CRUD operations
```js
{
    "username": "localhost@arun",
    "password": "",
    "database": "test",
    "host": "localhost",
    "dialect": "mysql",
    "pool": {
      "max": 5,
      "min": 0
    }
  }
```

## What do you expect to happen?
Run the code without any errors.

## What is actually happening?
Server starts normally. After a few calls to the APIs, it stops the server and displays the following issue: 

{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (C:\Users\arun-awnics\Documents\workspace\node-samples\mm-node\node_modules\generic-pool\lib\ResourceRequest.js:58:17)
    at Timeout.bound (C:\Users\arun-awnics\Documents\workspace\node-samples\mm-node\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) name: 'TimeoutError' }

__Dialect:__ mysql
__Dialect version:__ 2.15.0
__Database version:__ 10.1.24-MariaDB
__Sequelize version:__ 4.22.5
__Tested with latest release:__ No

**Comment by justintien** [comment]
这问题似乎发生好久了…

我目前也还没找到解决方案

**Comment by justintien** [comment]
as title,

这个问题存在好几个版本了
一直看到没有修复，却关闭 issue ( 不知道为何要关闭 )

#8133 #8008 #8014 #7884 

事实上，不知道如何复现问题

目前生产环境 我们是使用 azure mysql db
目前有一个 db instance: a
当我使用 mysqldump 备份 某一个 database 时 (当备份时间超过 4分钟)
则 sequelize 不明原因 connection pool 会坏掉，且不会释放
此时 所有 app 使用 sequelize 的, always got TimeoutError: ResourceRequest timed out at ResourceRequest._fireTimeout,
且无法 auto 重新释放 pool & create connection
* 可是我创建 copy instance a to b, 执行相同操作 却不会发生 (无解)

我自行补捉 TimeoutError & 重新 new Sequelize() 可以解决 
(但这应该不是好的处理方式)

当  connection pool 时，该如何正确的补捉 & release pool?
sequelize 似乎没有做这些处理 (是否我们要自行处理?)
但 sequelize 使用的 generic-pool 没有暴露出来 interface 让我们使用?

若有人有方法重现 fake bad connection pool 会更有帮助 (我不知道怎么制造 bad pool)

这个问题在生产环境应该是严重的

help to resolve 

希望能解决

Dialect: mysql
Dialect version: 1.5.1 (mysql2)
Database version: mysql 5.6
Sequelize version: 4.23.2
Tested with latest release: No

sequelize config use default {
'pool': {
      min: 0,
      max: 5,
      idle: 10000,
      acquire: 10000,
      evict: 10000,
      handleDisconnects: true
    }
}

**Comment by sushantdhiman** [comment]
If you to see this solved please provide me a good test case, because these default config on our tests

**Comment by justintien** [comment]
@sushantdhiman 

in fact, I don't know how to fake bad pool to reduce this issue...

I guess it's connection pool to crash or bad, but it didn't release the pool...

**Comment by arun-awnics** [comment]
Hey @sushantdhiman thank you... I am linking my question on stackoverflow which shows the code. Kindly take a look at it. [link](https://stackoverflow.com/questions/48181669/unhandled-rejection-timeouterror-resourcerequest-timed-out-in-nodejs-express)

I see the issue here is that, as the number of requests increase sequelize is unable to manage those transactions. As I increase the pool size, I can hold more requests. But that has its limits too. Kindly look into the matter since I see there are issues similar to this which has been persistent. We are using sequelize in our project to handle multiple APIs and our project will go into production soon. It would be great if we can fix this issue or at least find a work around for this. Thank you again.

**Comment by arun-awnics** [comment]
Hi @sushantdhiman I have created a [repository](https://github.com/arun-awnics/sequelize-test.git) to reproduce this issue.

While running test cases, I found out that the issue is wrt **GET** requests.

Tests pass when I try to run **POST** and **UPDATE** but fails for **GET** calls.
One more observation is that the server runs fine until it reaches the max pool size. For instance: 

```
var sequelize = new Sequelize('database', 'root', '', {
    host: 'localhost',
    dialect: 'mysql',
    operatorsAliases: false,
    logging: false,
    pool: {
        max: 5,
        min: 0,
        idle: 10000,
        acquire: 10000,
        handleDisconnects: true,
        evict: 60000,
        connectRetries: 5,
        operatorsAliases: false
    }
});
```

The above config can hold up to 5 **GET** calls, i.e., the server runs fine without any issues until 5 **GET** requests but it throws the following error if I try the same **GET** request the 6th time.

```
Unhandled rejection TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (C:\Users\arun-awnics\Documents\workspace\node-samples\sequelize-test\node_modules\generic-pool\lib\ResourceRequest.js:62:17)
    at Timeout.bound (C:\Users\arun-awnics\Documents\workspace\node-samples\sequelize-test\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Hence max pool size = max number of **GET** requests. After that it throws the above error.

**Comment by sushantdhiman** [comment]
Hi @arun-awnics 

Please provide me a SSCCE. It will help me understand your problem quickly.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

Your repository looks a small scale project in itself, I dont have time to go through and understand its implementation. Please check example SSCCE, if you can provide a good SSCCE I will take care of fixing this bug as I have done in past with many other issues

**Comment by arun-awnics** [comment]
Hi @sushantdhiman 

I spoke with @mickhansen yesterday in slack and resolved this issue. I was using transactions in my **GET** methods but didn't manage them properly. Hence the pool was getting filled with transactions and causing the issue.

```
return sequelize.transaction().then(function(t) {
            userModel.user.findAll({ transaction: t }).then((user) => {
                callback(user);
            });
        });
```

Now I changed my code to look like this(without transactions):

```
userModel.user.findAll().then((user) => {
            callback(user);
        });
```

It works fine now. You may close the issue. Thank you for your time.

**Comment by sushantdhiman** [comment]
Great

**Comment by leosj** [comment]
@justintien 解决了吗？小哥哥

**Comment by nodepaladin** [comment]
@justintien I share my case, hope to help you。In my case,my code magic lead to the transaction not commit or rollback,in other words,it's not released.So when the pool has been exhausted,I wanted to access DB,that error occured.
Release the transaction in time

**Comment by justintien** [comment]
@leosj 增加 pool 数量 (若 db 资源允许的话) 可以得到缓解，
```js
let options = {
    'pool': {
      min: 0,
      max: 50,
      idle: 10000,
      acquire: 10000,
      evict: 10000,
      handleDisconnects: true
    },
}
```
这个 error 发生的原因通常是 某个 sql 执行很久没有 commit 导致

```js
// 例如这个执行 10秒后 TimeoutError
  let jobs = []
  for (let i = 1; i <= 6; i++) {
    jobs.push(db.sequelize.transaction((t) => {
      return db.user.findOne({where: {id: 1}}).then((row) => {
        console.log(row, '@')
      })
    }))
  }
  await Promise.all(jobs)
```

`TimeoutError: ResourceRequest timed out at ResourceRequest._fireTimeout`

通常等到 慢执行/慢查询结束以后，可以得到解决…

但有其他不明原因的 bad pool, 我至今 仍无法复现，

所以我做了一件 not good 的事, 就是 连续 几次 TimeoutError 若一直无法处理时

reconnect db (sequelize.close() + new 新的 instance)

**Comment by justintien** [comment]
@nodepaladin I know this issue maybe are the transaction not commit,
but still have many situation I can't or I don't know how to get reason,
I guess it's related with db/network/firewall ....

anyway, I add pool size & reconnect method.....

**Comment by RifeWang** [comment]
@justintien how to catch all TimeoutError in one place with so many db models and methods ?

**Comment by justintien** [comment]
@RifeWang 
I use `expressjs`,

just simple...describe
```js
// my db object
const db = {
  connect (config = _config) {
    console.log('[db] connect')
    let tables = {}
    let sequelize
    if (process.env.DATABASE_URL) {
      sequelize = new Sequelize(process.env.DATABASE_URL, config)
    } else {
      sequelize = new Sequelize(config.database, config.user, config.password, config)
    }

    // load all table into db[table]
    fs
      .readdirSync(__dirname)
      .filter(function (file) {
        return (file.indexOf('.') !== 0) && (file !== 'index.js')
      })
      .forEach(function (file) {
        let model = sequelize.import(path.join(__dirname, file))
        tables[model.name] = model
      })

    Object.keys(tables).forEach(function (modelName) {
      if ('associate' in tables[modelName]) {
        tables[modelName].associate(tables)
      }
    })

    this.sequelize = sequelize

    // merge table model into db object (this)
    _.merge(this, tables)
    console.log('[db] connection created.')
    return sequelize
  },
  async reconnect () {
    console.log('[db] reconnect')
    if (this.sequelize) {
      console.log('[db] close')
      this.sequelize.close()
      this.sequelize = null
    }
    return this.connect()
  }
}

app.get('/test', async (req, res) => {
    await db.model.findOne({})
})

// error handler
let count = 0
app.use((err, req, res, next) => {
  // here, you can write some error handle logic..
  // e.g.
  if (err.message && err.message.match(/ResourceRequest timed out/)) {
    count++;
    if (count >= 10) {
        count = 0;
        db.reconnect();
    }


  }
})
```

**Comment by bugall** [comment]
@justintien Make sure, has any transaction logic in your project? the connection can not be reused if you not commit or rollback on the connection. timed release connection helps release the cache.

**Comment by bugall** [comment]
> @justintien Make sure, has any transaction logic in your project? the connection can not be reused if you not commit or rollback on the connection. timed release connection helps release the cache.

I think the problem is not egg business

**Comment by Tokyocsd** [comment]
{ SequelizeConnectionAcquireTimeoutError: Operation timeout
    at pool.acquire.catch.error (/www/wwwroot/doumi/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
  name: 'SequelizeConnectionAcquireTimeoutError',
  parent:
   Error: Operation timeout
       at Timeout._timeout.setTimeout (/www/wwwroot/doumi/node_modules/sequelize-pool/lib/Deferred.js:19:19)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10),
  original:
   Error: Operation timeout
       at Timeout._timeout.setTimeout (/www/wwwroot/doumi/node_modules/sequelize-pool/lib/Deferred.js:19:19)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) }
There are occasional errors, and the only solution is to restart

**Comment by Tokyocsd** [comment]
{ SequelizeConnectionAcquireTimeoutError: Operation timeout
    at pool.acquire.catch.error (/www/wwwroot/doumi/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
  name: 'SequelizeConnectionAcquireTimeoutError',
  parent:
   Error: Operation timeout
       at Timeout._timeout.setTimeout (/www/wwwroot/doumi/node_modules/sequelize-pool/lib/Deferred.js:19:19)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10),
  original:
   Error: Operation timeout
       at Timeout._timeout.setTimeout (/www/wwwroot/doumi/node_modules/sequelize-pool/lib/Deferred.js:19:19)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) }
There are occasional errors, and the only solution is to restart
