### ISSUE TITLE
Pass scope through Model.create Method

### ISSUE THREAD

**Issue by mkaufmaner** [sequelize/sequelize#8880]
## What are you doing?

Currently, the model's scope is not injected inside of the Model.create method.  However, I want to be access this scope in an `afterCreate` so I can rollback a transaction.

## What do you expect to happen?
The scope to be passed through the create method.

## What is actually happening?
The scope is not being injected.

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ 4
__Tested with latest release:__

**Comment by sushantdhiman** [comment]
>  I want to be access this scope in an afterCreate so I can rollback a transaction.

Can you elaborate, I don't get your usecase :) Transaction can be rollbacked without scopes

**Comment by mkaufmaner** [comment]
@sushantdhiman Basically, I want pass an object through the create and in hook rollback the transaction if needed.  However, upon further investigation and thought, I should be sanitizing the input instead.
