### ISSUE TITLE
`attributes` is not work for me

### ISSUE THREAD

**Issue by AntSworD** [sequelize/sequelize#8882]
## What are you doing?
I want to select some attributes, but it is select all

```js
return model.Notify.findOne({
    where: { id },
    attributes: [ 'content' ]
});
```

## What do you expect to happen?
```sql
SELECT `content` AS `content` FROM `xxx` AS `xxx` WHERE ((`xxx`.`deleted_at` > '2018-01-12 03:31:29' OR `xxx`.`deleted_at` IS NULL) AND `xxx`.`id` = 23);
```

## What is actually happening?
```sql
SELECT `content` AS `content`, `enable` AS `enable`, <other attributes> FROM `xxx` AS `xxx` WHERE ((`xxx`.`deleted_at` > '2018-01-12 03:31:29' OR `xxx`.`deleted_at` IS NULL) AND `xxx`.`id` = 23);
```

__Dialect:__ mysql
__Sequelize version:__ 4.28.6
__Tested with latest release:__ No (If yes, specify that version)

**Comment by mhombach** [comment]
Just to make sure we aren't talking about a typo on your side:
Within your provided query you are writing `where: { id }`, where it should be for example `where: { id: 23 },`.
To ensure we can analyse this problem, please replace the provided code-snippet with the exact code you are using :)

**Comment by AntSworD** [comment]
sorry, my fault
