### ISSUE TITLE
Has database create hook?

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#8883]
I want excute some code before database(sqlite) file created,but i can't find any way form document.

__Dialect:__ sqlite 
__Dialect version:__ 3
__Database version:__ 3
__Sequelize version:__3.30.3
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
You can try `beforeConnect / afterConnect` hook, but there is no specific hook for SQLite file creation
