### ISSUE TITLE
Queries getting queued and processed in series

### ISSUE THREAD

**Issue by dhans** [sequelize/sequelize#8886]
## What are you doing?
I have an express app with multiple routes that often get called around the same time, each triggering a multi-second sequelize query. I upgraded from v3 to v4. 

## What do you expect to happen?
I expect all queries to execute in parallel, as was the case in v3.

## What is actually happening?
Queries appear to get queued. Some of the fast queries only complete once some of the slow queries are done. The overall performance of the set of queries is an order of magnitude worse. Setting the connection pool to have a min of 10 does not appear to have a positive impact. Unfortunately, setting min = max = 0 makes the queries strictly in series. 

This behavior is happening both on Windows and in an AWS Elastic Beanstalk environment.

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.31
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Please consider this test case

If queries are executing serially then this test will take at-least `4 + 4 + 4 + 5 = 17 sec` to execute. If queries are executing in parallel it will take about `5 sec`.

```js
console.time('execute');
const results = await Sequelize.Promise.join(
  sequelize.query('SELECT pg_sleep(4); SELECT 1;', { type: sequelize.QueryTypes.SELECT }),
  sequelize.query('SELECT pg_sleep(4); SELECT 2;', { type: sequelize.QueryTypes.SELECT }),
  sequelize.query('SELECT pg_sleep(4); SELECT 3;', { type: sequelize.QueryTypes.SELECT }),
  sequelize.query('SELECT pg_sleep(5); SELECT 4;', { type: sequelize.QueryTypes.SELECT })
);
console.timeEnd('execute');
```

```sql
Executing (default): SELECT pg_sleep(4); SELECT 1;
Executing (default): SELECT pg_sleep(4); SELECT 2;
Executing (default): SELECT pg_sleep(4); SELECT 3;
Executing (default): SELECT pg_sleep(5); SELECT 4;
execute: 5053.369ms
```

**Comment by papb** [comment]
As sushantdhiman said above, this shouldn't be the case. If you are still experiencing this issue, please provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen.
