### ISSUE TITLE
Feature Req: TextRow.toArray() or TextRow.get()

### ISSUE THREAD

**Issue by jeremybradbury** [sequelize/sequelize#8889]
`TextRow.prototype.toArray()` 

TextRow is actually just an array made into a more complex object, so even if the developers still needed this ugly thing for some strange reason... we could just convert it into data we can actually use without looping the object after doing a raw query. 

Otherwise this can be simplified further... just return an array OR object like the other queries:
```
[
  {id: "2d343a"},
  {name: "Joe"}
]
```
OR (even better)
```
{
  id: "2d343a",
  name: "Joe"
{
```
Many library/user problems can solved by providing consistent data output regardless of what kind of query is used. Perhaps there is some other way to accomplish this that isn't immediately clear... if that's the case feel free to close this after pointing me to the documentation. But even if that's true... what I said above is still important: consistency.

All I am asking for here is a way to make raw query outputs provide data formatted the same way as other queries. `.get()` and `.get({plain: true})` do not work for raws because of this almost useless TextRow result. 

If you do just close this, I would love to hear more about what the TextRow is for and how to use it better when working with raw queries.

EDIT: note that TextRows even though they look like arrays or objects break when passed into another where: `{where: TextRow}` or `{where: TextRow[0]}`

**Comment by sushantdhiman** [comment]
Please read documentation on [Raw Queries](http://docs.sequelizejs.com/manual/tutorial/raw-queries.html)

You need to pass `type: Sequelize.QueryTypes.SELECT` to get internal data converted to proper consumable form.

**NOT THIS**
```js
sequelize.query("SELECT * FROM `users`")
```

**USE THIS**

```js
sequelize.query("SELECT * FROM `users`", { type: sequelize.QueryTypes.SELECT})
  .then(users => {
    // We don't need spread here, since only the results will be returned for select queries
  })
```

Please let me know if it doesn't solve your issue, I will reopen for further discussion

**Comment by bertolo1988** [comment]
This should be changed. The query code should be self explanatory.

**Comment by abubakarcp** [comment]
Here you go: 
 suppose we have data in students object:
```
 let finalArray = new Array();
    for (var k in students ) {
      finalArray.push(students[k])
    }

 console.log(finalArray) // Normal JSON array object :)
```

**Comment by waqas10075** [comment]
Here you go:
suppose we have data in students object:

 let finalArray = new Array();
    for (var k in students ) {
      finalArray.push(students[k])
    }

 console.log(finalArray) // Normal JSON array object :)
