### ISSUE TITLE
TimeoutError: ResourceRequest timed out at ResourceRequest._fireTimeout

### ISSUE THREAD

**Issue by justintien** [sequelize/sequelize#8895]
as title,

这个问题存在好几个版本了
一直看到没有修复，却关闭 issue ( 不知道为何要关闭 )

#8133 #8008 #8014 #7884 

事实上，不知道如何复现问题

目前生产环境 我们是使用 azure mysql db
目前有一个 db instance: a
当我使用 mysqldump 备份 某一个 database 时 (当备份时间超过 4分钟)
则 sequelize 不明原因 connection pool 会坏掉，且不会释放
此时 所有 app 使用 sequelize 的, always got TimeoutError: ResourceRequest timed out at ResourceRequest._fireTimeout,
且无法 auto 重新释放 pool & create connection

我自行补捉 TimeoutError & 重新 new Sequelize() 可以解决 
(但这应该不是好的处理方式)

当  connection pool 时，该如何正确的补捉 & release pool?
sequelize 似乎没有做这些处理 (是否我们要自行处理?)
但 sequelize 使用的 generic-pool 没有暴露出来 interface 让我们使用?

若有人有方法重现 fake bad connection pool 会更有帮助 (我不知道怎么制造 bad pool)

这个问题在生产环境应该是严重的

help to resolve 

希望能解决

Dialect: mysql
Dialect version: 1.5.1 (mysql2)
Database version: mysql 5.6
Sequelize version: 4.23.2
Tested with latest release: No

**Comment by sushantdhiman** [comment]
I dont understand 在生产环境应该是严重的 ....?, duplicate of https://github.com/sequelize/sequelize/issues/8877

**Comment by justintien** [comment]
sorry 我把 comment 移过去...

**Comment by Wendell220** [comment]
Hi @justintien Do you solve this problems? From the case #8877,  the transaction usage  has issue.  Do you try to  reproduce this case and fixed this case? Thanks
