### ISSUE TITLE
"order by" appeared twice in generated sql which cause side effect - " Unknown column 'question.created_at' in 'order clause'"

### ISSUE THREAD

**Issue by yellowstar1014** [sequelize/sequelize#8897]
## What are you doing?
I'm trying to do a query:

```js
models.User.findAll({
      limit:limit,
      order:[['createdAt','DESC']],
      include : [
      {
        model:models.Question,
        as:"questions"
      },]
    })

// models are as below
module.exports = db.sequelize.define('user', {
  // id is added automatically
  createdAt: {
    type: Sequelize.DATE,
    field: 'created_at'
  }
})

module.exports = db.sequelize.define('question', {
  // id is added automatically
  userId: {
    type: Sequelize.BIGINT,
    field: 'user_id'
  }
})

User.hasMany(Question,{foreignKey:'userId',as:'questions'})
```

## What do you expect to happen?
I expected that this query could run smoothly but..

## What is actually happening?
I came across an exception : "SequelizeDatabaseError: Unknown column 'user.created_at' in 'order clause'"

_Output, either JSON or SQL_: 
Generated sql is: 
SELECT user.* FROM (SELECT user.id, _**user.created_at AS createdAt**_ FROM user AS user **ORDER BY user.created_at DESC** LIMIT 10) AS user LEFT OUTER JOIN question AS questions ON user.id = questions.user_id **ORDER BY user.created_at DESC**

seems the 'Order by' was applied twice.  At the second time, the 'created_at' was renamed as 'createdAt' that's why it complains "cannot find 'created_at'". Obviously the second 'order by user.created_at' is not necessary. If we could remove this clause, the problem will be resolved.

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ mysql
__Database version:__   
__Sequelize version:__ ^4.4.2
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Have you defined `created_at` column in table? How are you creating this table?

**Comment by yellowstar1014** [comment]
yes, I have created_at column in table. I created table manually.

**Comment by yellowstar1014** [comment]
I'm pretty sure the table schema is right.  I run the generated sql in mysql, it doesn't work. If you check the generated sql and my comment carefully, it has problem obviously.

**Comment by sushantdhiman** [comment]
Can you try with latest version?

**Comment by PurnimaLambaSG** [comment]
I am facing this same issue

**Comment by theromie** [comment]
Any workaround?

**Comment by saoud-ahmed-khan** [comment]
I am still facing the same, this is a reason I am not a big fan of ORMs. they come up with these types of issues.

**Comment by Wagkart** [comment]
Facing the same issue due to which query is slowing down in MY SQL 8.0 by 5 times though it works well in MY SQL 5.7
