### ISSUE TITLE
HasOne and BelongsTo Issue

### ISSUE THREAD

**Issue by kkotwal94** [sequelize/sequelize#8898]
I dont know if my logic is wrong or anything, but im trying to define a HasOne / BelongsTo Relationship

Heres my models:

Students:
```
id
ClassificationTypeId: int
name
address

associate(models) {
        Students.belongsTo(models.ClassificationTypes, {as: 'ClassificationTypes', foreignKey: 'classificationTypeId'});
```

ClassificationTypes:

```
id
name
description
displayOrder

classMethods: {
      associate(models) {
        ClassificationTypes.hasOne(models.Students, {foreignKey: 'classificationTypeId'});
    }
```

Now this populates, when i query students i get a object for ClassificationTypeID, but this makes no sense to me. I spent a hour trying to figure out why this worked instead of student having this relationship
```
 Students.hasOne(models.ClassificationTypes, {as: 'ClassificationTypes', foreignKey: 'classificationTypeId'});
```
and classificationsType having this one

```
ClassificationTypes.belongsTo(models.Students, {foreignKey: 'id'});
```
Is this intended or a bug? My train thought would make me think if a Student has a classification, then there is a hasone relationship where the classificationId is on the hasOne source table.

**Comment by sushantdhiman** [comment]
Follow the issue template

**Comment by kkotwal94** [comment]
@sushantdhiman is this good enough

**Comment by sushantdhiman** [comment]
No
