### ISSUE TITLE
Transactions not working properly

### ISSUE THREAD

**Issue by AhmadMurtaza1** [sequelize/sequelize#8899]
## What are you doing?
I want to run 2 insert queries and created a transaction but not working properly

## js
return sequelize.transaction({ autocommit: false }, function(t){
        
        var q1 = queryString.format("INSERT INTO users (email, password) VALUES (?, ?)", [data.email, data.password]);
        var q2 = queryString.format("INSERT INTO themes (theme_id, theme_name) VALUES (?, ?)", [data1.theme_id, data1.theme_name]);

        return sequelize.query(q1, { 
            type: Sequelize.QueryTypes.INSERT 
        }, {transaction: t}).then(function (user) { 
            
            return sequelize.query(q2, { 
                type: Sequelize.QueryTypes.INSERT 
            }, {transaction: t}); 

        }).then(function(){
            return t.commit();
        }).catch(function (err) {
            return t.rollback();
        })
    })

## What do you expect to happen?
If both the transactions are fulfilled then It inserts a record in the db else not.

## What is actually happening?
If first transaction fulfills and second fails then It inserts a new record for first transaction

_Output, 
{
    "isFulfilled": false,
    "isRejected": false
}

__Dialect:__ mysql
__Maria DB version:__ 10.2.8
__Sequelize version:__ 4.31.2
__Tested with latest release:__ Yes (4.31.2)

**Comment by sushantdhiman** [comment]
If you want both records to be created together use only one transaction and pass it to both queries.

`{
"isFulfilled": false,
"isRejected": false
}` is Promise. Please read more about how to use Promises in Node.js here

http://docs.sequelizejs.com/manual/installation/getting-started.html#promises
http://bluebirdjs.com/docs/why-promises.html

**Comment by AhmadMurtaza1** [comment]
To create both records together, I have used 1 transaction and passed it to both queries(You can check above code) but if one query fails then It will stores 1 record. 
However what I want is, if success then store both records else not

**Comment by kamal123prd** [comment]
I have similar issue, where I have two update and one insert query associated with single transaction. The query order is : update1, update2, insert3. If I rollback on insert 3, update1 and update2 doesn't rollback (they get committed), only insert3 rollback happens.

**Comment by jcfinnerup** [comment]
Having similar issues

**Comment by AmbroiseVuaridel** [comment]
Having similar issues

**Comment by qqaimh** [comment]
> I have similar issue, where I have two update and one insert query associated with single transaction. The query order is : update1, update2, insert3. If I rollback on insert 3, update1 and update2 doesn't rollback (they get committed), only insert3 rollback happens.

Me too

**Comment by Messilimeng** [comment]
@qqaimh yes when i insert1 and insert 2 use type=“INSERT” then get error,but  when i delete type="insert" then it works
 uncaughtException  TypeError: Cannot convert undefined or null to object  
can you tell me how to do?
