### ISSUE TITLE
BelongsToMany; model not associated

### ISSUE THREAD

**Issue by karim73** [sequelize/sequelize#8901]
Hi,

I meet a lot of problems when I try to implement belongsToMany.
I Have 2 mdels: organisation and user
An organisation can have many users; and furthrmore; user can belong to many organisation. The jointure table is 'organisation_user'

This my code:

**Organisation model**
```js
module.exports = (sequelize, DataTypes) => {
  const Organisation = sequelize.define(
    'organisation',
    { /* */ });

  Organisation.associate = models => {
    Organisation.belongsToMany(models.User,{
        through: 'organisation_user',
        foreignKey: 'organisation_id',
        as: 'users'
    });
};
return Organisation;
}
```
**User model**
```js
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define(
    'user',
    {
     /* */
    }
  );
  User.associate = models => {
    User.belongsToMany(models.Organisation, {
      through: 'organisation_user',
      foreignKey: 'user_id',
      as: 'organisations'
    });
  };
  return User;
};
```
**Organisation_user model**
```js
module.exports = (sequelize, DataTypes) => {
  const Organisation_user = sequelize.define(
    'organisation_user',
    {
      user_id: { type: DataTypes.INTEGER, allowNull: false},
      organisation_id: { type: DataTypes.INTEGER, allowNull: false}
    },
    {
      //underscored:true,
      freezeTableName: true
    }
  );

  Organisation_user.associate = models => {
    models.Organisation_user.belongsTo(models.Organisation, {
      foreignKey: 'organisation_id'
    });

    models.Organisation_user.belongsTo(models.User, {
      foreignKey: 'user_id'
    });
  };
  return Organisation_user;
};
```
**Fin querying (1)**
```js
// 1 way
    Organisation.findById(req.params.id)
        .then(orga => {
            orga.getUsers()
                .then(users=> res.status(200).json(users))
                .catch(err=> res.status(400).json(err))
        })
        .catch(err=> res.status(400).json(err))
```
**Failed with: TypeError: orga.getUsers is not a function**

**Fin querying (2)**
```js
    Organisation.findById(req.params.id,{
            include:[{ model:User , as:'users' }]
        })
        .then(orga => res.status(200).json(orga ))
        .catch(err=> res.status(400).json(err))
```
**Failed with: SequelizeEagerLoadingError: user is not associated to organisation!**

Both of them failed,

I'm missing something ?

Thank you

**Comment by mhombach** [comment]
Hey there,
some things seem a little off:
Are you sure that
```js
Organisation.associate = models => {
    Organisation.belongsToMany(models.User,{
        through: 'organisation_user',
        foreignKey: 'organisation_id',
        as: 'users'
    });
```
Is the correct way in your code-structure to associate those?
You could try to define all models without association and then associate them in your main/index file by simply using `Organisation.belongsToMany({...})`...

Also you have an error because you `through: 'organisation_user',`. But later create some "Organisation_user model".
You can link m:n in Sequelize by using a MODEL or by using a manual way. But if you want to go the MODEL-way, then it should realyl be the MODEL and not a string with the value of the model... So:
```js
User.belongsToMany(models.Organisation, {
      through: Organisation_user,
      foreignKey: 'user_id',
      as: 'organisations'
    });
```

I didn't test the rest of the code but since you get the error `orga.getUsers is not a function` this means, that regardless of errors within your linking-model, `getUsers()` isn't even referenced to the `orga`, so there must by a problem with the linking itself, because even just `Organisation.belongsToMany` should create a function `getUsers()`, even if it won't return the correct data.
Hope you can try to analyse your problem further :)

**Comment by shuaibq3** [comment]
having same issue. sequelize version: 4.38.0, node version: 8.11.3

Models: 
`//Group model
  module.exports = (sequelize, DataTypes) => {
  const Group = sequelize.define(
    "Group",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false
      }
    },
    { freezeTableName: true, tableName: "Group" }
  );

  Group.associate = function(models) {
    Group.belongsToMany(models.Camera, {
      through: models.CameraGroupUserMapping,
      as: "groupCameras",
      foreignKey: 'groupId',
      otherKey: 'cameraId',
      onDelete: "CASCADE"
    });
  };

  return Group;
};`

`//camera model
  module.exports = (sequelize, DataTypes) => {
  const Camera = sequelize.define(
    "Camera",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false
      },
      address: {
        type: DataTypes.STRING
      },
      lat: {
        type: DataTypes.FLOAT
      },
      lon: {
        type: DataTypes.FLOAT
      }
    },
    { freezeTableName: true, tableName: "Camera", timestamps: false }
  );

  Camera.associate = function(models) {
    Camera.belongsToMany(models.Group, {
      through: models.CameraGroupUserMapping,
      as: "cameraGroups",
      foreignKey: 'cameraId',
      otherKey: 'groupId',
      onDelete: "CASCADE"
    });
  };

  return Camera;
};`

`//CameraGroupUserMapping model
  module.exports = (sequelize, DataTypes) => {
  const CameraGroupUserMapping = sequelize.define(
    "CameraGroupUserMapping",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      status: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
    }
    },
    { freezeTableName: true, tableName: "CameraGroupUserMapping" }
  );

  CameraGroupUserMapping.associate = function(models) {
    // associations can be defined here
    CameraGroupUserMapping.belongsTo(models.Camera, {
      type: "FOREIGN KEY",
      name: "cameraId",
      references: {
        table: "Camera",
        field: "id"
      },
      onDelete: "CASCADE"
    });

    CameraGroupUserMapping.belongsTo(models.Group, {
      type: "FOREIGN KEY",
      name: "groupId",
      references: {
        table: "Group",
        field: "id"
      },
      onDelete: "CASCADE"
    });
  };

  return CameraGroupUserMapping;
};
`

query:

`models.Camera.findAll({
    include: [{
        model: models.Group,
        as: "cameraGroups"
      },
    ]
  });`

error:  "Group is not associated to Camera!"

any idea what i am doing wrong?

**Comment by covationlabs** [comment]
It should be closed! The same issues 2023!

**Comment by ephys** [comment]
Please open a new bug report with the necessary information and a reproducible example if you're experiencing a bug
