### ISSUE TITLE
Custom validation not documented completely

### ISSUE THREAD

**Issue by dbettini** [sequelize/sequelize#8905]
## What are you doing?
Extending `Sequelize.Validator` with a custom validator for an array of urls, according to [this](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#validations), by just throwing an error if the format is wrong. The reason I used that is because I could not find `Validator.extend` documented anywhere.

```js
function validateUrlArray(urls) {
  const urlArray = urls.split(',');

  if (urlArray.find((url) => !Validator.isUrl(url))) {
    throw new Error('Array contains invalid urls!');
  }
}

Validator.extend('isUrlArray', validateUrlArray);
```

## What do you expect to happen?
The validation passes for an array of valid urls, otherwise it throws.

## What is actually happening?
The validation throws correctly for invalid array (throws `Array contains invalid urls!` error). However, for an array of valid urls, it throws `Validation isUrlArray on images failed`.
The reason this happens is [this](https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js#L281) line. If the validator function doesn't return a truthy value, the generic error with the `validatorType` and `field`is thrown.

It seems that extending Validator adds a new built in validator, instead of a custom one. However, built in validators seem to return falsy values instead of throwing (like custom ones do). And since `Validator.extend` isn't documented anywhere, nor is writing new built in validators, this creates a problem. Basically, the way I fixed this was just making my validator return true or false, but I think the docs should be updated with this use case **or** by making `Validator.extend` add a new **custom** validator.

__Dialect:__ postgres
__Database version:__ 10
__Sequelize version:__ 4.28.1
__Tested with latest release:__ No, but the mentioned line of code is unchanged since this version

**Comment by sushantdhiman** [comment]
`Sequelize.Validator` is just a copy of https://github.com/chriso/validator.js, if you your validator to throw custom error message just define new validator extension and use that in a field's `validate` method

Or simply

```js
{
    attribute: {
         validate: {
              isURLArray() {
                  const urlArray = urls.split(',');

                  if (urlArray.find((url) => !Validator.isUrl(url))) {
                       throw new Error('Array contains invalid urls!');
                  }
              }
         }
    }
}
```

**Comment by sushantdhiman** [comment]
Its all here http://docs.sequelizejs.com/manual/tutorial/models-definition.html#validations

**Comment by dbettini** [comment]
I'm aware of that. You linked the same documentation that I linked in my post. Using a custom function in the `validate` property doesn't allow for the reuse of that validator. On the other hand, using `Validator.extend` puts it in the global validator, so you could reuse it just by using `validate: { isUrlArray: true }`, and that's what I tried to achieve. However, I did find [this](https://github.com/chriso/validator.js/pull/496#issuecomment-183996213) - it seems they decided to drop it from validator.js, so I guess it shouldn't be used.
