### ISSUE TITLE
mysql data-types.js incorrect use of moment-timezone

### ISSUE THREAD

**Issue by knightzac19** [sequelize/sequelize#8906]
## What are you doing?
```sql
select NOW();
```

## What do you expect to happen?
I wanted my output to be in the timezone I set.

## What is actually happening?
Came back as UTC..

https://github.com/sequelize/sequelize/blob/6931c795a89ff70722c6718e6b151121edad5c94/lib/dialects/mysql/data-types.js#L103 Should be `moment.tz(value, options.timezone).format();`. Using toDate() strips the timezone information and thus makes the use of moment-timezone pointless. Please refer to https://github.com/moment/moment-timezone/issues/309 for more info.

https://github.com/knightzac19/sequelize/commit/a226b77bbfbbf511b39a93c6561c05a4522679d5?diff=split

__Dialect:__ mysql
__Dialect version:__ latest
__Database version:__ 5.7
__Sequelize version:__ 4.31.1
__Tested with latest release:__ Yes

**Comment by ramsgoli** [comment]
I've been looking for a first contribution so I'd love to write the patch and tests for this!
