### ISSUE TITLE
"SKIP LOCKED" support (request)

### ISSUE THREAD

**Issue by themetalfleece** [sequelize/sequelize#8910]
I have noticed that sequelize does not support "SKIP LOCKED" selects.

A query example with "FOR UPDATE" and "SKIP LOCKED" would be
```
SELECT "id" FROM "Customers" WHERE "Customers"."AccountBalance" > 5 LIMIT 3 FOR UPDATE SKIP LOCKED;
```

"SKIP LOCKED" is useful for job queues.

https://www.postgresql.org/docs/9.5/static/sql-select.html#SQL-FOR-UPDATE-SHARE

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/7b163084bc40349563e2b758d1c1b385e97bba2b
