### ISSUE TITLE
Associated the relations between 3 tables chained i.e., 1 to 2 and 2 to 3, But it says table1 is not associated to table3

### ISSUE THREAD

**Issue by Eshwar9990** [sequelize/sequelize#8915]
entities.DB_LSVehicle.hasOne(entities.DB_Vehicle_Tracking, { foreignKey: 'VehicleId' });
entities.DB_Vehicle_Tracking.belongsTo(entities.DB_Driver, { foreignKey: 'DriverId' });
entities.DB_LSVehicle.findAll({
            include: [
            {
                model: entities.DB_Driver,
                attributes: [ 'DriverName' ]
            }
        ],
        }).then(function(data) {
            if (!data) {
                res.send('not found');
            }
            res.json(data);
        });

**Comment by sushantdhiman** [comment]
Follow issue template if you are reporting an issue, ask questions on Stackoveflow or our Slack channel.
