### ISSUE TITLE
findOrBuild doesn't create instance with includes

### ISSUE THREAD

**Issue by smassin** [sequelize/sequelize#8919]
## What are you doing?

```
ModelA.findOrBuild({
  defaults : data,
  where : where,
  include : [{
    model : ModelB
  }]
})
```

## What do you expect to happen?
I expected the include to be passed along to the new instance. findOrCreate does pass this along so the inconsistency was unexpected.

## What is actually happening?
The instance is only built with values and not options.

I'm using v3 currently until we find time to upgrade but its still the same in v4: https://github.com/sequelize/sequelize/blob/3cea5c4f84e0b7a5c0ef5548d318d786d495eb4e/lib/model.js#L2059

Changing the line to `instance = this.build(values, options);` solves the issue.

**Comment by clairecliu** [comment]
I would like to give this a try.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/8938
