### ISSUE TITLE
queryInterface.changeColumn(...) doesn't seem to work for changing ENUM set.

### ISSUE THREAD

**Issue by ashok-sc** [sequelize/sequelize#8920]
## What are you doing?
I'm doing the following in my migration file:
```module.exports = {
  up: (queryInterface, Sequelize) => {
    queryInterface.changeColumn('data', 'sourceType', {
      type: Sequelize.ENUM(
        'FILE',
        'API',
      ),
      defaultValue: 'API'},
    )
  },

  down: (queryInterface, Sequelize) => {
    queryInterface.changeColumn('data', 'sourceType', {
      type: Sequelize.ENUM(
        'FILE',
        'API',
      ),
      defaultValue: 'API'},
    )
  }
};
```

## What do you expect to happen?
Migrate the table and change existing `sourceType` column to be the new ENUM type.

## What is actually happening?
I'm seeing the following error when running the migration:

```
Unhandled rejection SequelizeDatabaseError: type "enum_data_sourceType" already exists
```

__Dialect:__ postgres
__Dialect version:__ (PostgreSQL) 10.0
__Database version:__ XXX HUH?
__Sequelize version:__ Sequelize CLI [Node: 8.7.0, CLI: 3.0.0, ORM: 4.31.2]
__Tested with latest release:__ No (If yes, specify that version)

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

3.0.0

... Just seeing this. Gonna post anyway to confirm (sorry) but does it sound like I need to update? Or is what I'm doing actually not supported?

**Comment by sushantdhiman** [comment]
You are missing `return` in your migrations?

**Comment by sushantdhiman** [comment]
Looking at your code it looks like you just missed return in your migration methods, Let me know if that is not the case

**Comment by SvemirskiHod** [comment]
I have the same problem, `error: type "FIELD" already exists` when altering enum values.

```
module.exports = {
  up(queryInterface, Sequelize) {
    return queryInterface.changeColumn('subscriptions', 'role', {
        type: Sequelize.ENUM('teacher', 'student', 'author', 'co-teacher'),
        allowNull: false
      });
  },
  down(queryInterface, Sequelize) {
    return queryInterface.changeColumn('subscriptions', 'role', {
        type: Sequelize.ENUM('teacher', 'student', 'author'),
        allowNull: false
      });
  }
};

```
"sequelize": "^3.33.0",
"sequelize-cli": "^2.5.1",

**Comment by ashok-sc** [comment]
I would highly recommend not using enums with Sequelize. Moving forward I'm just using text in the DB and letting the code control the enum. It's not worth the pain of migrating enums.

**Comment by artjoms-faltins** [comment]
> Looking at your code it looks like you just missed return in your migration methods, Let me know if that is not the case

`return` does not influence on error appearance. The issue still exist in  "sequelize": "^4.42.0", "sequelize-cli": "^5.4.0"

**Comment by papb** [comment]
> Btw I've discovered that calling `Sequelize.sync()` once you have defined the new ENUM values in the model does the updates correctly.

@SvemirskiHod Can you open a new issue about this?

**Comment by papb** [comment]
> > Looking at your code it looks like you just missed return in your migration methods, Let me know if that is not the case
> 
> `return` does not influence on error appearance. The issue still exist in "sequelize": "^4.42.0", "sequelize-cli": "^5.4.0"

@artjoms-faltins Does the problem happen with sequelize v5 as well?

**Comment by drc-tjuszczyk** [comment]
Also seeing this with ENUMs and postgres. Does anybody know what the actual issue is?

**Comment by papb** [comment]
@drc-tjuszczyk Can you please open a new issue filling the template and linking to this issue?
