### ISSUE TITLE
JSON attribute parsing and changed()

### ISSUE THREAD

**Issue by seally1186** [sequelize/sequelize#8936]
## What are you doing?
JSON attributes aren't parsed when returned, and (possibly as a result) are marked as changed even when set to the same value:

```js
const Test = db.sequelize.define("Test", {
  a: DataTypes.JSON
});
async function main() {
  await Test.sync({force: true});
  let t = new Test;
  t.a = {};
  await t.save();

  t = await Test.findOne();
  console.log(util.inspect(t.a));
  t.a = {};
  console.log(util.inspect(t.a));
  console.log(t.changed());
}
main();
```

## What do you expect to happen?
```
{}
{}
false
```

## What is actually happening?
```
'{}'
{}
[ 'a' ]
```

Is the intention that I should `JSON.parse` the value I get back? Even if so, `changed()` should recognize that the new value is the same as the old.

__Dialect:__ mysql
__Database version:__ MariaDB 10.2
__Sequelize version:__ 4.32.1
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
I am running this code against MySQL 5.7 

**Code**
```js
await Model.sync({ force: true });

  let item = await Model.create({});

  item.a = { a : 1 };

  console.log(item.a);

  await item.save();

  console.log(item.a);

  item = await Model.findOne();

  console.log(item.a);
```
**Output**
```
{ a: 1 }
{ a: 1 }
{ a: 1 }
```

Now I think issue you are facing may be MariaDB specific. But note we don't "support" MariaDB dialect, its only supported becuase its API matches to MySQL
