### ISSUE TITLE
Sequelize with MS SQL using tedious getting two same arrays in result.

### ISSUE THREAD

**Issue by rahulkulmi** [sequelize/sequelize#8940]
I am using "tedious": "2.2.3" and "sequelize": "4.31.2" and call stored procedures.
Then i will getting response in array and inside that array i am getting two same array instant one array. So please fix this problem as soon as possible.

This is my stored procedures code for MS SQL database
```
CREATE PROCEDURE myuser
AS
BEGIN
  SELECT * FROM users where username='rahul';
END
```

And this is my sequelize code used inside the Node Express app.
```
sequelize.query("EXEC myuser;", { type: sequelize.QueryTypes.RAW})
    .then(function(summary) {
     return callback(null, summary);
    })

OR

sequelize.query('myuser').then(function (response) {
      return callback(null, response);
    }).catch(function (err) {
      return callback(err);
    });
```

Here is the sample response
```
"responseData": [
        [
            {
                "id": 1,
                "username": "rahul",
                "password": 12345,
                "phone": 1234,
                "createdAt": "2018-01-19T11:54:51.642Z",
                "updatedAt": "2018-01-19T11:54:51.642Z"
            }
        ],
        [
            {
                "id": 1,
                "username": "rahul",
                "password": 12345,
                "phone": 1234,
                "createdAt": "2018-01-19T11:54:51.642Z",
                "updatedAt": "2018-01-19T11:54:51.642Z"
            }
        ]
    ]
```

**Comment by rahulkulmi** [comment]
I am also conform from tedious team here is the github issue link for more detail

https://github.com/tediousjs/tedious/issues/688#issuecomment-359513800

**Comment by rahulkulmi** [comment]
@sushantdhiman 
Can you please tell me why you close this issue. Is this a wrong issue or some other region.

**Comment by sushantdhiman** [comment]
It was not following issue template. If its a question please ask on Stackoverflow or Slack, if you want to report a bug with Sequelize please create a new issue properly following issue template.
