### ISSUE TITLE
autocommit support for multiple async/await functions in sequelize.transaction

### ISSUE THREAD

**Issue by tsu710785** [sequelize/sequelize#8942]
## What are you doing?

I use sequelize.transaction to handle a function for a series of tasks.
It looks like: 
```js
sequelize.transaction(async function () {
  const firstObj = await firstModule.find(query); // first execution which is implemented by Model.findOne
  const results = await Promise.all(_.map(params, param => {
    return SecondModule.create(param)             // second execution which is implemented by Model.create
  }));
  return Promise.resolve(results);
}).then( async (results) => {
    // success, should be COMMIT
}).catch ((error) =>{
    // fail, should be ROLLBACK
});
```
I expected that all of the function should be executed in same transaction.
But the result I got is : 
```js
Executing (c6b9064b): START TRANSACTION;
Executing (c6b9064b): SELECT `id` ...        (FirstModule.find)
Executing (default): INSERT INTO ...         (SecondModule.create)
Executing (default): INSERT INTO ...         (SecondModule.create)
Executing (c6b9064b): ROLLBACK;
```
only first `await` function is in that transaction 

I have tried several cases below:

1.  If I turn `await` into Promise chain, it work as expected.

2. If I put those executions in one `Promise.all` with `await` , it work as expected, too.

It seems that `autocommit` for transaction is only valid for first `await` function given these cases I tried.
But some of our function need to be done in sequence. We knew that we can pass `{transaction: t}` param into sequelize model. However, It's not that effective and difficult to maintain.

My question is: 

1.  Is that by design on purpose or it's just a bug?  

2. And if I want to add a fail unit case and create a PR, which file does this case belong to?

 

 
  

thx a lot!

## What do you expect to happen?
_I expected that all of functions should execute in the same transaction._
_Is that because that we used it in inappropriate way?_

## What is actually happening?
_After I print the mysql log, I found that all `await` function except the first one are executed in default_
_transaction rather than in specific transaction. And it will cause some unexpected behaviors._

__Dialect:__ mysql 
__Dialect version:__ GCP MySQL 2nd Gen 5.7
__Database version:__ MySQL 2nd Gen 5.7
__Sequelize version:__ 4.32.1
__Tested with latest release:__4.32.1

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Didn't get your context, are you using CLS?

Without CLS you just have to pass `transaction` option to all queries you want to run under that transaction. Which I think is better approach than automagically injecting transaction to a context.

> Is that by design on purpose or it's just a bug?

If you aren't using CLS, this is by design. Any method / query will run in no transaction mode, you have to pass `transaction` option to every method / query you want to run under that transaction


> And if I want to add a fail unit case and create a PR, which file does this case belong to?

Not sure that will be needed, lets discuss more here first


Please read more about how to use CLS [here]( http://docs.sequelizejs.com/manual/tutorial/transactions.html)

**Comment by tsu710785** [comment]
Thanks for reply and sorry for insufficient information given.

Yes, we already used CLS in our code. 

our code structure is like this: 
```js
const cls = require('continuation-local-storage');
const namespace = cls.getNamespace('n');

sequelize.transaction(async function (t) {
  await Promise.all(_.map(objects, id => {
    return new Promise(async (resolve) => {
      // 1
      await AModule.find(query);
      // 2
      await BModule.find(query);
      // 3
      await CModule.remove(panoramaObj);
    });
  });
}).then(()=>{
});
```
I printed some info at location marked as 1,2,3 and got results like these:
```js
// 1 
console.log('t1', namespace.get('transaction') === t);
// => true
console.log('namespace',namespace);
// => namespace Namespace {
//  name: 'n',
//  active: transation object,
// }
```
```js
// 2
console.log('t2', namespace.get('transaction') === t);
// => false
console.log('namespace',namespace);
// => namespace Namespace {
//  name: 'n',
//  active: null,
// }
```
```js
// 3
console.log('t3', namespace.get('transaction') === t);
// => false
console.log('namespace',namespace);
// => namespace Namespace {
//  name: 'n',
//  active: null,
// }
```
Only at "1" there was a transaction object and that was what actually happened. 
I'm wondering that why BModule & CModule were not included in transaction even if I used the CLS?

Thanks again!

**Comment by mrene** [comment]
`continuation-local-storage` doesn't track contexts through async-await (unless you transpile your code to promises) - there are some projects implementing it using async_hooks (like `node-async-context`) which could help.
