### ISSUE TITLE
Model.findAll produces promise warnings.

### ISSUE THREAD

**Issue by dmead** [sequelize/sequelize#8944]
## What are you doing?
getting a list of users. this code is inside an express 4 route. it seems to be causing the request to hang.

```js
User.findAll({})
      .then(users => {
        console.log(users);
        return users;
      })
      .catch(function(err) {
        console.log(err);
        return err;
      });
```

## What do you expect to happen?
I want to do stuff to a list of users inside the .then call
## What is actually happening?
the http call through express doesn't terminate. i want this to return gracefully and I *seem* to be following the docs correctly.

_Output, either JSON or SQL_

__Dialect:__  postgres 
__Dialect version:__ 7.4.1
__Database version:__  9.6.3 
__Sequelize version:__ 4.32.1
__Tested with latest release:__ (unsure)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by dmead** [comment]
I've tried several variations, including writing a raw query. Every way i do this produces a runaway call that makes the request hang.

**Comment by sushantdhiman** [comment]
Are you sending response back after promise is resolved?. From your description it looks like you forgot to send response back after Promise is resolved

Can you include a short version of your route handler, so I can help
