### ISSUE TITLE
Sequelize connection error Net.Connect is not a function

### ISSUE THREAD

**Issue by gj1118** [sequelize/sequelize#8955]
Hi, 
I tried asking this question on [SO](https://stackoverflow.com/questions/48456208/sequelize-connection-error-is-failing-with-the-message-net-connect-is-not-a-fu) and Slack but unfortunately , I could not find an answer which is why I am asking this question here.

My apologies for breaking the norm.  

I am getting the following error 
https://slack-imgs.com/?c=1&url=https%3A%2F%2Fdha4w82d62smt.cloudfront.net%2Fitems%2F1M0X0I3Q431D0F0W191S%2FImage%25202018-01-26%2520at%25208.52.24%2520AM.png

I have a `Connection.js` which looks like this 

```javascript
const Sequelize = require('sequelize');

// const Connection = new Sequelize('Executions','gjanjua', '' , {
//     host: '10.105.130.21',
//     dialect: 'mysql'
// });


const Connection = new Sequelize('mysql://gjanjua@10.105.130.21:3306/executions');


module.exports = {
    Connection
}
```

I have another `model` class that looks like this 

```javascript
const { Connection } = require('./Connection');
const Sequelize = require('sequelize');


const Results = Connection.define('results', {
    controller_ip: Sequelize.STRING,
    plan_name: Sequelize.STRING,
}, { freezeTableName: true, timestamps: false })

module.exports = {
    Results
}
```

and I am using it as such in my code

```javascript
import {Results} from './Executions'
Results.findOne().then(result => {
        console.log(result)
      })
```

the dependencies section of my package.json looks like this 

```json
  "dependencies": {
    "dns": "^0.2.2",
    "mysql2": "^1.5.1",
    "pg-hstore": "^2.3.2",
    "sequelize": "^4.32.2",
    "tedious": "^2.2.4",
    "vue": "^2.5.2"
  },
```

Can you please let me know what I am doing wrong ?  

Thanks
Gagan

**Comment by sushantdhiman** [comment]
Follow the issue template

**Comment by gj1118** [comment]
I have updated the report. Can you please reopen this issue?  

thanks
Gagan
