### ISSUE TITLE
Sequelize connection error Net.Connect is not a function

### ISSUE THREAD

**Issue by gj1118** [sequelize/sequelize#8959]
Hi, 
I tried asking this question on [SO](https://stackoverflow.com/questions/48456208/sequelize-connection-error-is-failing-with-the-message-net-connect-is-not-a-fu) and Slack but unfortunately , I could not find an answer which is why I am asking this question here.

My apologies for breaking the norm.  

I have a `Connection.js` which looks like this 

```javascript
const Sequelize = require('sequelize');

// const Connection = new Sequelize('Executions','gjanjua', '' , {
//     host: '10.105.130.21',
//     dialect: 'mysql'
// });


const Connection = new Sequelize('mysql://gjanjua@10.105.130.21:3306/executions');


module.exports = {
    Connection
}
```

I have another `model` class that looks like this 

```javascript
const { Connection } = require('./Connection');
const Sequelize = require('sequelize');


const Results = Connection.define('results', {
    controller_ip: Sequelize.STRING,
    plan_name: Sequelize.STRING,
}, { freezeTableName: true, timestamps: false })

module.exports = {
    Results
}
```

and I am using it as such in my code

```javascript
import {Results} from './Executions'
Results.findOne().then(result => {
        console.log(result)
      })
```

the dependencies section of my package.json looks like this 

```json
  "dependencies": {
    "dns": "^0.2.2",
    "mysql2": "^1.5.1",
    "pg-hstore": "^2.3.2",
    "sequelize": "^4.32.2",
    "tedious": "^2.2.4",
    "vue": "^2.5.2"
  },
```

## What do you expect to happen?
I want to get a record from the Results table.

## What is actually happening?
I am getting the following error 
https://slack-imgs.com/?c=1&url=https%3A%2F%2Fdha4w82d62smt.cloudfront.net%2Fitems%2F1M0X0I3Q431D0F0W191S%2FImage%25202018-01-26%2520at%25208.52.24%2520AM.png

_Output, either JSON or SQL_
None. Since I believe this is happening when the connection handshake happens and it errors out. 

__Dialect:__ mysql 
__Dialect version:__ "mysql2": "^1.5.1",
__Database version:__ MySql Community Version 5.7
__Sequelize version:__ 4.32.2
__Tested with latest release:__ Yes

Can you please let me know what I am doing wrong ?  

Thanks
Gagan

**Comment by sushantdhiman** [comment]
Follow the issue template please, I dont like closing issues repeatedly. You have just copy pasted last closed issue

**Comment by andrefbsantos** [comment]
I have the same when I ran my mocha tests.
I can run my express application without any issues, but when I run my tests I get the following error: 
```
Unhandled rejection SequelizeConnectionError: Net.connect is not a function
    at Utils.Promise.tap.then.catch.err (p/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
    at tryCatcher (p/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (p/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (p/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (p/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (p/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (p/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (p/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (p/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

sequelize.js:
```
import * as Sequelize from 'sequelize';

export const sequelize = new Sequelize('p', 'root', 'super_root_password', {
  host: 'localhost',
  dialect: 'mysql',
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
});

export default sequelize;
```

message.js:
```
import { sequelize } from '../sequelize';
import * as Sequelize from 'sequelize';

export const Message = sequelize.define('message', {
  content: {
    type: Sequelize.STRING
  }
});

export default Message;
```

package.json's dependencies:
```
"dependencies": {
    "body-parser": "~1.18.2",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.9",
    "express": "~4.15.5",
    "jade": "~1.11.0",
    "morgan": "~1.9.0",
    "mysql2": "^1.5.1",
    "npm": "^5.6.0",
    "sequelize": "^4.32.3",
    "serve-favicon": "~2.4.5"
  },
  "devDependencies": {
    "chai": "^4.1.2",
    "mocha": "^5.0.0",
    "node-mocks-http": "^1.6.6"
  }
```

What extra information can I provide?

**Comment by gj1118** [comment]
@sushantdhiman, I modified the issue (the one that I created earlier ) and then asked you if you will be kind enough to reopen it. After waiting a couple of days (if I remember correctly, pardon me if I don't), I created this new ticket because you never responded after you closed the original issue. 

Yes, I am pretty sure that I am using mysql2 :) 
 
I **produced the entire code** that generates the error. I took the error screenshot and pasted it here because it has the entire stack trace. My only motive when I produced the image was to make it easier for anybody looking at it, to easily decipher where the issue is. 

As far as the node versions are concerned, please find both the NODE version as well as NPM version below. 

NODE: 8.4.0
NPM: 5.3.0
