### ISSUE TITLE
Break out of hook without throwing an error

### ISSUE THREAD

**Issue by alonewarrior** [sequelize/sequelize#8962]
## What are you doing?

```
sequelize.addHook('beforeFind', (data) => {
  if (data in cache)
    end hook
  else
    continue with hook lifecycle
});
```

## What do you expect to happen?
I was hoping that when I hit the beforeFind hook, I would be able to break out of it given certain circumstances without being forced to throw an error, thus allowing me to resolve the promise and not query the database.

## What is actually happening?
I am unable to actually break out of the lifecycle without throwing an error, forcing me to write additional logic for errors that aren't really supposed to be errors but instead are results that should follow the same success pathway as if the error had never been thrown.

__Dialect:__ mysql
__Sequelize version:__ 4.32.2
__Tested with latest release:__ Yes

Being able to end the cycle early without errors would be incredibly useful for introducing some sort of caching mechanism that could be baked into the sequelize code and not require additional logic outside of it. I may be overlooking something significant, or not realizing a manner in which to resolve this issue given the current tools, but I'm at a loss at the moment. Any assistance or potential updates to permit this would be greatly appreciated!

**Comment by sushantdhiman** [comment]
Hooks arent suitable for this kind of logic, a resolved promise from hooks means we are ok to continue any operation we were supposed to do.

I suggest using shimmer like library and overload any finder method

```js
shimmer.wrap(Model, 'findAll', function (original){
    return function(options) {
        if ( /* in cache */) {
            // return cached
        } else {
           return original.call(this, options);
        }
    }
})
```

Or better use https://github.com/facebook/dataloader
