### ISSUE TITLE
MySQL: Sequelize.TIME(3) ignores precision and declares column as time instead of time(3)

### ISSUE THREAD

**Issue by npapagna** [sequelize/sequelize#8963]
## What are you doing?
Im writing a migration that adds a column to a model in which i need to track time with millisecond precision:

```js
//...
duration: {
  allowNull: false,
  type: Sequelize.TIME(3)
},
//...
```

## What do you expect to happen?
I wanted the db schema to be altered and the new column be declared as `time(3)`.

## What is actually happening?
The column is declared as `time` instead of `time(3)` and thus losing precision.
Note that this is working for columns of type `Sequelize.DATE(3)`.

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ 5.7.21
__Sequelize version:__ 4.32.2
__Tested with latest release:__ yes, 4.32.2

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Time does not support precision at the moment, tagging this as feature request
