### ISSUE TITLE
ENUM validation on mySQL doesn't fully propagate errors

### ISSUE THREAD

**Issue by NoxPhoenix** [sequelize/sequelize#8965]
mySQL databases will log errors without throwing on ENUM datatype validation unless the sql mode is set to strict.

There is no way to set the SQL mode outside of a raw query either...

Here is my model...
```js
module.exports = (database) => {
  return database.define('transaction', {
...
    startingCurrency: {
      type: Sequelize.ENUM,
      values: ['BTC', 'ETH', 'LTC'],
      unique: 'compositeIndex',
      allowNull: false,
    },
...
```

And when I create with it...
```
Transaction.create({
    date: '0000-00-00',
    exchange: 'Coinbase',
    amount: 0.332,
    startingCurrency: 'Not Valid',
    endingCurrency: 'BTC',
    type: 'Purchase',
    userId: id,
  }, { validate: true }))
  .then((created) => {
    console.log(created);
  });
```

Still makes the row without any warning there was a validation issue. In the startingCurrency column, it truncated the value to an empty string.

I expected this to throw a TypeError for the not valid value in the enum column, but it creates the row.

**Comment by sushantdhiman** [comment]
Please note your issue is not following issue template so I wont answer it but someone from community my help you :)

**Comment by sushantdhiman** [comment]
Looks like no one commented :)

Enum was incorrectly defined in original example

```js
type: Sequelize.ENUM('BTC', 'ETH', 'LTC')
```
