### ISSUE TITLE
Reuse or export database connection / pool

### ISSUE THREAD

**Issue by adriaanvanrossum** [sequelize/sequelize#8967]
## What are you doing?
_I have sequelize running inside my express app. It works great. I also have a worker running which also uses the same database that sequelize uses. They both use pooling and I would love to share that same database connection with both parts (sequelize and worker) inside my app._

## What do you expect to happen?
_To be able to export the database connection so I can use it inside my app as well._

## What is actually happening?
_I'm not able to find anything that exports the database connection to something outside sequelize_

__Dialect:__ postgres

**Comment by sushantdhiman** [comment]
What I am about to recommend is private API and can change at any moment in same major semver (chances are very rare though)

```js
// this will get one raw connection from pool
const connection =  sequelize.connectionManager.getConnection();
```

**Comment by adriaanvanrossum** [comment]
Awesome, thank you!
