### ISSUE TITLE
Get the last/latest record in each mysql group

### ISSUE THREAD

**Issue by sketchminds** [sequelize/sequelize#8968]
Hi,

Cannot find any answer on any forums, so maybe someone here could help me out?

I'm trying to get the last/latest record In each mysql group. The query that I'm trying to convert is something like this:

SELECT id, category_id, post_title
FROM posts
WHERE id IN (
    SELECT MAX(id)
    FROM posts
    GROUP BY category_id
);

Ref. link: https://paulund.co.uk/get-last-record-in-each-mysql-group

I tried to play around with attributes, group and order but I can't accomplish the results I need.

Thanks.

**Comment by smithaitufe** [comment]
You should follow the issue template. It makes it easier to help you.

**Comment by sketchminds** [comment]
Thanks, I already solved this.

https://stackoverflow.com/questions/48514254/sequelize-find-latest-record-per-group-of-id/48515909#48515909
