### ISSUE TITLE
MSSQL bulkInsert and upsert do not use hasTrigger

### ISSUE THREAD

**Issue by smassin** [sequelize/sequelize#8972]
## What are you doing?
The MSSQL implementation of bulkInsert and upsert don't use options.hasTrigger from the function call or the model definition.

```
var Model = sequelize.define('model', {
  ... fields...
}, {
  hasTrigger:true
});

Model.upsert({
  ...
})
```

## What do you expect to happen?
SQL query should be wrapped with a temporary table output like insertQuery.

## What is actually happening?
The feature is ignored and a DB error is thrown because the table has a trigger.

__Dialect:__ mssql
__Sequelize version:__ Current using v3 but v4 also has  the issue.

### Part 1

From v4 see line https://github.com/sequelize/sequelize/blob/f36db54dd5b031427fd8c52296c614c56421e4ba/lib/dialects/mssql/query-generator.js#L439

Needs to be changed to:

```
query += ` WHEN MATCHED THEN UPDATE SET ${updateSnippet} WHEN NOT MATCHED THEN INSERT ${insertSnippet}`;
//To capture output rows when there is a trigger on MSSQL DB
if (options.hasTrigger) {
  var tmpTable = 'declare @tmp table ([$action] nvarchar(6)); ';
  query = tmpTable + query;
  query += ' OUTPUT $action into @tmp; select * from @tmp;';
}
else {
  query += ' OUTPUT $action, INSERTED.*;';
}
```

Note: At this time INSERTED.* in the output is never used so we can exclude that data. If it is desired to be used at a future time then a more complex solution would be needed like used in https://github.com/sequelize/sequelize/blob/f36db54dd5b031427fd8c52296c614c56421e4ba/lib/dialects/abstract/query-generator.js for insert query.

### Part 2

From v4 see line
https://github.com/sequelize/sequelize/blob/f36db54dd5b031427fd8c52296c614c56421e4ba/lib/query-interface.js#L925

Needs to be changed to:

````
options = _.clone(options);
options.hasTrigger = model.options.hasTrigger;
````

I didn't implement a solution for bulkInsert but it would be fairly similar to insert.

**Comment by sushantdhiman** [comment]
`INSERTED.*` is now used for upsert with `returning:true` to return primary key value

**Comment by smassin** [comment]
Thanks for the response. I can change the solution code to preserve this however this poses a tricky situation. Can you help me answer the following questions before i make the change?
1) Composite primary keys are not supported in the upsert return. Is that on purpose? I can see value in supporting it for tables with no identity column.
2) In the case where a unique key is used instead of a primary key, the primary key doesn't get added to the match so it would return undefined. Is this the desired behaviour or should we be injecting the primary key(s) if they don't exist?

**Comment by sushantdhiman** [comment]
> Composite primary keys are not supported in the upsert return. Is that on purpose? I can see value in supporting it for tables with no identity column.

Yes, Sequelize actually does not support composite primary key, You can define two or more attribute with primaryKey:true but lots of things will break

> In the case where a unique key is used instead of a primary key, the primary key doesn't get added to the match so it would return undefined. Is this the desired behaviour or should we be injecting the primary key(s) if they don't exist?

Good question, current implementation is limited in that sense, but you are right we should be checking for unique condition that upsert is using and find new record based of that unique condition.

But Sequelize model without primaryKey will also break some things, so this can probably be ignored for now. When we actually start some serious work related to primaryKey less models, we can support this

> the primary key doesn't get added to the match so it would return undefined

Wasn't actually aware of this could happen, if primary key is not supplied by us then database default should be used, in either UPDATE/INSERT case it is guaranteed to return primaryKey, but that is based on my assumption that model will have a primaryKey defined.

**Comment by smassin** [comment]
Thanks for answering my questions. 

>> the primary key doesn't get added to the match so it would return undefined

> Wasn't actually aware of this could happen, if primary key is not supplied by us then database default should be used, in either UPDATE/INSERT case it is guaranteed to return primaryKey, but that is based on my assumption that model will have a primaryKey defined.

Oops, seems I was mistaken. While it is possible to do a merge on any match condition that results in a single inert/update per row, merging will always return the full row even if the primary key is not provided.

I will go ahead and update the solution to include the primary key in the output.
