### ISSUE TITLE
Include with limit duplicating registers

### ISSUE THREAD

**Issue by ThiagoMiranda** [sequelize/sequelize#898]
Hi.
Thanks for the Sequelize module. It helped me a lot in my project. But I ran into a little issue ( maybe it's a not good use of the framework, I don't know ).

I have 2 tables: Episodes and Files. Episodes hasMany Files and Files belongsTo Episodes. In my actual scenario I have 2 files for each episode.
When I do a query like this:

```
 Episodes.find({limit: 0,6}, include: [Files]).success(function(episodes){
     console.info(episodes);
 });
```

It returns 3 unique episodes ( instead of 6 ). Using the same query that Sequelize uses in the mysql console I get 6 registers but they are duplicated ( 2 equals episodes ). I guess its because of the LEFT OUTER JOIN ( using without the duplicate returns the right amount of rows ). Can I do something about it? For now I'm just duplicating the limit ( like 0,12 ) for each place in my App that I do this query.

**Comment by joshuadmatthews** [comment]
I am still seeing this issue.

**Comment by mickhansen** [comment]
@joshuadmatthews please open a new issue with a SSCCE.
