### ISSUE TITLE
queryInterface.removeConstraint in Mysql lowercases table name

### ISSUE THREAD

**Issue by UnbrandedTech** [sequelize/sequelize#8981]
## What are you doing?
Trying to remove a unique constraint from a model in a migration. 

```js
//model
return sequelize.define('TableInQuestion', {
        id: {
            type: DataTypes.UUID,
            primaryKey: true,
            defaultValue: DataTypes.UUIDV4
        },
        unique_field: {
            type: DataTypes.UUID,
            allowNull: false
        }
    }, {
        timestamps: true,
        freezeTableName: true,
        underscored: true,
        indexes: [
            { fields: ['unique_field'], unique: true }
        ]
    })

//Migration command
return queryInterface.removeConstraint('TableInQuestion', 'table_in_question_unique_field')
```

SQL actually being executed
```sql
DROP INDEX `table_in_question_unique_field` ON `tableinquestion`;
```

## What do you expect to happen?
I wanted it to drop the key.

## What is actually happening?
It dropped the key in question but also lowercased my table name.

## How do I think we should fix this?
I know this is a "bug" in mysql and not Sequelize but I purpose we use the table name from the function and not the table name from returned from `INFORMATION_SCHEMA.TABLE_CONSTRAINTS`. The output from there is determined by a casing variable in the Database variables not what the table casing accualy is.

By changing line 67 in the mysql/query-interface.js from this:
```js
query = this.QueryGenerator.removeIndexQuery(constraint.tableName, constraint.constraintName);
```
to this:
```js
query = this.QueryGenerator.removeIndexQuery(tableName, constraint.constraintName);
```

It should fix it...

[Reported Bug in MySQL Core](https://bugs.mysql.com/bug.php?id=20356)

*Side Note:* I learned today that if you alter a table with a different casing, it set it's casing to whatever [`lower_case_table_names`](https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html) is set too.

![the-more-you-know](https://user-images.githubusercontent.com/1107773/35647291-48c63f28-068f-11e8-804b-e3bf00828d44.gif)

__Dialect:__ mysql (MariaDB)
__Dialect version:__ 10.2.11-MariaDB
__Database version:__ 5.7.20 (innodb)
__Sequelize version:__ XXX
__Tested with latest release:__ Yes (v4.32.1)

**Comment by Avizacherman** [comment]
If nobody has done this yet would love to contribute (it'd be my first open source contribution).

**Comment by paulmowat** [comment]
Seems like this one still hasn't been done. I'll take a look and do a PR for it.

**Comment by paulmowat** [comment]
I've just tried replicating this on 5.0.0-beta.9 using mysql 5.7

```javascript
var Sequelize = require('../sequelize')

var sequelize = new Sequelize('sequelize_test', 'sequelize_test', 'sequelize_test', {
  host: 'localhost',
  port: 8999,
  dialect: 'mysql'
})

var TableInQuestion = sequelize.define('TableInQuestion', {
  id: {
      type: Sequelize.DataTypes.UUID,
      primaryKey: true,
      defaultValue: Sequelize.DataTypes.UUIDV4
  },
  unique_field: {
      type: Sequelize.DataTypes.UUID,
      allowNull: false
  }
}, {
  timestamps: true,
  freezeTableName: true,
  underscored: true,
  indexes: [
      { fields: ['unique_field'], unique: true }
  ]
})

return TableInQuestion.sync({ force: true })
  .then(() => {
    return sequelize.queryInterface.removeConstraint('TableInQuestion', 'table_in_question_unique_field')
  })
  .then((data) => {
      console.log(JSON.stringify(data, null, '\t'))
  })
  .catch((err) => {
    console.log(err)
    process.exit(1)
  });
```

Code below generates SQL statement

```sql
DROP INDEX `table_in_question_unique_field` ON `TableInQuestion`
```

When viewing the table after the above has executed it's name is still `TableInQuestion`.

Do you have anymore information or is it now working as you'd expect on the above version?

**Comment by sushantdhiman** [comment]
Looks like it's fixed https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L708

**Comment by uzair004** [comment]
> Looks like it's fixed https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L708

link shows 404 error.

**Comment by WikiRik** [comment]
> > Looks like it's fixed https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L708
> 
> link shows 404 error.

Yes, query-interface.js is now here; https://github.com/sequelize/sequelize/blob/7f57a0d7f6cde2006df865ae7f5bb10eab7fb3af/lib/dialects/abstract/query-interface.js but in which line it was fixed I would not be able to find quickly. Are you still experiencing a similar issue?

**Comment by uzair004** [comment]
> > > Looks like it's fixed https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L708
> > 
> > 
> > link shows 404 error.
> 
> Yes, query-interface.js is now here; https://github.com/sequelize/sequelize/blob/7f57a0d7f6cde2006df865ae7f5bb10eab7fb3af/lib/dialects/abstract/query-interface.js but in which line it was fixed I would not be able to find quickly. Are you still experiencing a similar issue?

First of all your documentation link is still not working, in fact 70% google too searches doc links in google shows 404 error.

I tried using `sequelize.queryInterface.removeConatraint` It didn't work, while raw query did work even though they are suppose to do same thing

**Comment by ephys** [comment]
@uzair004 documentation url breakage was resolved https://github.com/sequelize/sequelize/issues/13864

If you're still experiencing this issue (the removeConstraint issue), can you open a new bug report with your SSCCE so we can investigate?

**Comment by uzair004** [comment]
> @uzair004 documentation url breakage was resolved #13864
> 
> If you're still experiencing this issue (the removeConstraint issue), can you open a new bug report with your SSCCE so we can investigate?

documentation url is still broken

**Comment by ephys** [comment]
@uzair004 can you post the documentation url that's broken?

**Comment by uzair004** [comment]
> > > Looks like it's fixed https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L708

for instance, clicking this one shows 404 error. so are many google searches results

**Comment by ephys** [comment]
That's not a documentation link, it's the source code. `master` branch was renamed to `main`, & query-interface was moved to https://github.com/sequelize/sequelize/blob/7f57a0d7f6cde2006df865ae7f5bb10eab7fb3af/lib/dialects/abstract/query-interface.js

The documentation urls listed in google search did break but #13864 should have resolved it. If you do still have a google search result that still leads to a 404 feel free to send it to us so we can fix it too.
