### ISSUE TITLE
Using OR statements in findOrCreate WHERE statement

### ISSUE THREAD

**Issue by henit** [sequelize/sequelize#9003]
Trying to run a `.findOrCreate`, with `options.where` using an OR:

```js
    UserModel.findOrCreate({
        where: {
            [Op.or]: [
                { foo: 'foo' },
                { bar: 'bar' }
            ]
        },
        defaults: {
            // ...
        }
    });
```

When it does not find any rows, and inserts a row, the insert works (and the row gets added to the database-table, including setting an AUTO_INCREMENT id), but after that, I get:

    Cannot convert undefined or null to object    
        at create.then.catch.err (.../node_modules/sequelize/lib/model.js:2138)

The error gets thrown at this Sequelize code:

```js
      return this.create(values, options).then(instance => {
        if (instance.get(this.primaryKeyAttribute, { raw: true }) === null) {
          // If the query returned an empty result for the primary key, we know that this was actually a unique constraint violation
          throw new this.sequelize.UniqueConstraintError();
        }

        return [instance, true];
      }).catch(this.sequelize.UniqueConstraintError, err => {
        const flattenedWhere = Utils.flattenObjectDeep(options.where);
        const flattenedWhereKeys = _.map(_.keys(flattenedWhere), name => _.last(_.split(name, '.')));
        const whereFields = flattenedWhereKeys.map(name => _.get(this.rawAttributes, `${name}.field`, name));
        const defaultFields = options.defaults && Object.keys(options.defaults).map(name => this.rawAttributes[name].field || name);
        
        if (defaultFields) {
          if (!_.intersection(Object.keys(err.fields), whereFields).length && _.intersection(Object.keys(err.fields), defaultFields).length) {
            throw err;
          }
        }
```

After a bit of debugging, I found that the following happens:

1. The instance (from `this.create`) above has a dataValues that includes the defaults I sent in `findOrCreate`, but with `id: null`
2. `this.primaryKeyAttribute` is 'id'
3. It throws the error (UniqueConstraintError)
4. In the catch, err.message is `SequelizeUniqueConstraintError: Validation Error`, pluss the following properties:
    - name: 'SequelizeUniqueConstraintError',
    - errors: {},
    - fields: undefined,
    - parent: { sql: '' },
    - original: { sql: '' },
    - sql: ''
5. The undefined err.fields cause `if (!_.intersection(Object.keys(err.fields), whereFields)` to throw the error (`Cannot convert undefined or null to object`)

Am I using Sequelize wrong, or is this a bug?

__Dialect:__ mysql
__Database version:__ 5.7.21
__Sequelize version:__ 4.32.6

**Comment by henit** [comment]
Ok, after a lot of digging, I found that the problem was due to autoIncrement not being set in the model definition. So even while the database row got an ID (because the table was created with auto_increment), the row did not get that id when running create/save operations in Sequelize. Hard problem to find, I would suggest more intuitive error messages.

**Comment by emarcelino3** [comment]
you save my life!

**Comment by steveheaven** [comment]
@henit you're a genius! Adding no ID in the model helps, sequelize will do it for you automatically.
