### ISSUE TITLE
Many to Many relation with a foreign key field on the link table is not joining the foreign key data

### ISSUE THREAD

**Issue by rgottumu** [sequelize/sequelize#9014]
I have posted this to stackoverflow, but haven't received any answer. I also saw couple of questions very similar to this which are unanswered and are more than an year old. So I am not sure if this is an implementation issue on my end or this is a product limitation.

## What are you doing?
I am trying to create a many to many relationship between two tables, User and School. Each user will have a role for a school.  My link table "user_school" will have a role_id along with user_id and school_id.
Now when finding users, I would like to load school details (which is successful) along with role name (failing here) not just the role_id.

```
Models.user = sequelize.define('user', {
        user_id: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
        name: Sequelize.TEXT
    });

    Models.school = sequelize.define('school', {
        school_id: { type: Sequelize.INTEGER, primaryKey: true },
        name: Sequelize.TEXT
    });

    Models.role = sequelize.define('role', {
        role_id: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
        name: Sequelize.TEXT
    });

    Models.userSchool = sequelize.define('user_school', {
    });

    Models.user.belongsToMany(Models.school, { through: Models.userSchool, foreignKey: 'user_id', otherKey: 'school_id' });
    Models.school.belongsToMany(Models.user, { through: Models.userSchool, foreignKey: 'school_id', otherKey: 'user_id' });
    Models.userSchool.belongsTo(Models.role, { foreignKey: "role_id" });

    Models.user.findAll({
            include: [{ all: true, nested: true }]
        }).then(function (result) {
            console.log(result);
        })
```
## What do you expect to happen?
I would like to see the result to contain role information.
```
{
   "user_id":1,
   "name": "test",
    "schools":[{
          "school_id":1,
           "name":"s1",
           "user_school": [
                 "user_id":1,
                 "school_id":1,
                 "role_id":1,
                  "roles":{
                      "role_id":1,
                       "name":"role 1"
                  }
           ]
     }]
}
```

## What is actually happening?
I cannot see any role information loaded.

```
{
   "user_id":1,
   "name": "test",
    "schools":[{
          "school_id":1,
           "name":"s1",
           "user_school": [
                 "user_id":1,
                 "school_id":1,
                 "role_id":1
           ]
     }]
}
```

__Dialect:__  postgres 
__Dialect version: node-postgres 7.4.1
__Database version:__ 10.1, 9.6.6
__Sequelize version:__ 4.32.7
__Tested with latest release:__ yes

**Comment by rgottumu** [comment]
any help here?

**Comment by sushantdhiman** [comment]
Please provide me a SSCCE. It will help me understand your problem quickly.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
