### ISSUE TITLE
Support Node 6 and up

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#9015]
https://github.com/nodejs/Release#release-schedule

Node 4 Maintenance LTS is ending soon (on 2018-04-30) and all cloud function providers AWS, Google, Azure and IBM supports Node v6

**Comment by sushantdhiman** [comment]
Included in v5 branch

**Comment by SimonSchick** [comment]
Would it be possible to skip right to v8, seeing that v8 and v10 are both LTS?

**Comment by sushantdhiman** [comment]
No

**Comment by SimonSchick** [comment]
> No.

Is there any particular reason why?

**Comment by dijonkitchen** [comment]
Probably because version 6.x is supported as an LTS until 2019.

**Comment by sushantdhiman** [comment]
Main reason is already stated

> all cloud function providers AWS, Google, Azure and IBM supports Node v6

**Comment by SimonSchick** [comment]
@sushantdhiman all cloud providers you named now fully support v8.
v6 LTS ends in ~4 months, I think it would be sensible to release v5 targeting v8 instead.

**Comment by sushantdhiman** [comment]
I agree @SimonSchick , I planned v5 to be a quick iteration but release has been stretched further. Now it make sense to bump directly to Node 8 at least.

`cls` is a blocker atm, will have to look into implementing https://github.com/Jeff-Lewis/cls-hooked

**Comment by SimonSchick** [comment]
Can you elaborate what it is blocking exactly?

**Comment by sushantdhiman** [comment]
@SimonSchick first we have to migrate our codebase to use `cls-hooked`, probably locking Node to 8.10 or above (no real issue with that), then we have to write tests for functionality using cls with native async await especially important for transactions.

Migration to cls-hooked is required as `continuation-local-storage` itself is using `AsyncListener` which wont work for Node 8 or up

This is mostly some (easy) modernization work with tedious rewrite (of tests) overall but real blocker if we want to support cls in Node 8

**Comment by SimonSchick** [comment]
I assume you are going to do this?
I'm not exactly familiar with the cls stuff since I've never used it.

**Comment by ayushnigamsworld** [comment]
> @SimonSchick first we have to migrate our codebase to use `cls-hooked`, probably locking Node to 8.10 or above (no real issue with that), then we have to write tests for functionality using cls with native async await especially important for transactions.
> 
> Migration to cls-hooked is required as `continuation-local-storage` itself is using `AsyncListener` which wont work for Node 8 or up
> 
> This is mostly some (easy) modernization work with tedious rewrite (of tests) overall but real blocker if we want to support cls in Node 8

Yes I think that is utterly needed. We are using Node 8, with async-await waterfall, cls simply fails. Then we used cls-hooked with Sequelize managed transactions and till now it's been working like a beauty for past 6 months. Moving to production with cls-hooked now. Anyone differ, do comment.
