### ISSUE TITLE
`order` in `scopes` is ignored (for "belongsToMany"-associations)

### ISSUE THREAD

**Issue by Ajaxy** [sequelize/sequelize#9018]
## What are you doing?
I'm trying to associate a scoped model. It's scope contains `order` field.

```js
const Tag = sequelize.define('tag', {
  // ...
}, {
  scopes: {
    ordered: {
      order: [['name', 'DESC']]
    }
  }
});

const User = sequelize.define('user', {
  // ...
}, {
  classMethods: {
    associate({ Tag }) {
      User.belongsToMany(Tag.scope('ordered'), {
        through: 'usersTags'
      })
    }
  }
}

const { tags } = await User.findOne({ include: [Tag] })
```

## What do you expect to happen?
`tags` to be ordered by `name`.

## What is actually happening?
`tags` are randomly ordered.

__Dialect:__ postgres
__Dialect version:__ pg@^6
__Sequelize version:__ 3.31.1
__Tested with latest release:__ No

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by Ajaxy** [comment]
`defaultScope` does not work either.

**Comment by sushantdhiman** [comment]
Sorry we don't support v3 any longer, even if this bug is there we wont fix it (we dont have many active contributors to support multiple versions)

Please update to latest v4

**Comment by dshiells2** [comment]
Having the same issue in v5.
