### ISSUE TITLE
Sync with alter true always re-create constraints and add them to the old ones 

### ISSUE THREAD

**Issue by abdoolly** [sequelize/sequelize#9020]
I am running sequelize sync with alter option true and force to false 

```js
models.sequelize.sync({ force: false ,alter:true})
.then(() => {})
.catch(err => {
    console.log('can not sync ', err)
  });
```
I have the following model with the following attributes and unique constraints

```js
sequelize.define('myModel', {
    name_english: { type: DataTypes.STRING, unique: true },
    name_arabic: { type: DataTypes.STRING, unique: true },
    short_code: { type: DataTypes.STRING, unique: true },
    bic_code: { type: DataTypes.STRING, unique: true },
    short_bic_code: { type: DataTypes.STRING, unique: true }
  });
```

- alter works correctly and if the unique constraints exist it should not re-create them

- but , what actually happens is that the sync works perfectly but , the constraints are re-created and appended to the constraints that already exists which made the indexes reach 64 from just a couple of alters.

Dialect: mysql
Dialect version: 1.5.2
Database version: 10.1.30-MariaDB
Sequelize version: 4.33.1
Tested with latest release: yes, 4.33.1

**Comment by sushantdhiman** [comment]
Duplicate https://github.com/sequelize/sequelize/issues/8984
