### ISSUE TITLE
queryInterface.createTable: "uniqueKeys" option does not work anymore

### ISSUE THREAD

**Issue by wolframkleis** [sequelize/sequelize#9041]
## What are you doing?

In a migration file, I used the following snippet to create a table, and specified the "uniqueKeys" option to create a unique constraint.
```js
sequelize.queryInterface.createTable("MyModel",  {
    id:   {   type: Sequelize.INTEGER, primaryKey: true},
    col1: {   type: Sequelize.INTEGER},
    col2: {   type: Sequelize.INTEGER}
  },
  {  "uniqueKeys": { "col1_col2_unique": { "fields": ["col1","col2"]}}
});
```

## What do you expect to happen?
I wanted Sequelize to create a unique constraint on columns `col1` and `col2`.
Up to  4.33.2 this used to work. The generated SQL was:
```sql
CREATE TABLE IF NOT EXISTS "MyModel" 
("id" INTEGER , "col1" INTEGER, "col2" INTEGER, 
UNIQUE ("col1", "col2"), PRIMARY KEY ("id"));
```

## What is actually happening?
With 4.33.3 this is no longer working.
The "uniqueKeys" option is now ignored
Generated SQL no longer has the `UNIQUE ("col1", "col2")` part
```sql
CREATE TABLE IF NOT EXISTS "MyModel" 
("id" INTEGER , "col1" INTEGER, "col2" INTEGER, 
PRIMARY KEY ("id"));
```

__Dialect:__ postgres
__Dialect version:__ 9.6
__Database version:__ 9.6
__Sequelize version:__ 4.33.3
__Tested with latest release:__ 4.33.3

**Comment by sushantdhiman** [comment]
For now you can fix this by setting `customIndex: true`

```js
"uniqueKeys": { "col1_col2_unique": { "fields": ["col1","col2"], customIndex: true } }
```

**Comment by SimonSchick** [comment]
I just traced this down as well: https://github.com/sequelize/sequelize/issues/9041

Can you please mark this as a breaking change?
This caused us quite some headache today.

**Comment by SimonSchick** [comment]
@sushantdhiman Are you suggesting `uniqueKeys` shouldn't be used? Is there a better way to define unique keys, maybe via attributes in `createTable`?

**Comment by sushantdhiman** [comment]
It seems there is no API other than `uniqueKeys` although `indexes` should be available on `createTable`, making this a breaking change.

But I can't revert that fix. So as I said I will try to come up with a strategy to keep that fix while making it a non breaking

**Comment by SimonSchick** [comment]
I came up with:

```typescript
  // Begin patch https://github.com/sequelize/sequelize/issues/9041
  const proto = seq.getQueryInterface().constructor.prototype;
  const old = proto.createTable;
  proto.createTable = function(
    tableName: string | { schema?: string; tableName?: string },
    attributes: ModelAttributes,
    options?: QueryInterfaceCreateTableOptions,
  ): Bluebird<void> {
    if (options && options.uniqueKeys) {
      for (const [, value] of Object.entries(options.uniqueKeys)) {
        if (value.fields.length > 1) {
          (<any> value).customIndex = true;
        }
      }
    }
    return old.call(this, tableName, attributes, options);
  };
  // End patch
```

Do you think this will have any side unwanted side effects?

**Comment by sushantdhiman** [comment]
@SimonSchick Looks good, I see no potential issues with this patch

**Comment by SimonSchick** [comment]
@sushantdhiman have you had any time to apply my `patch` to the code base?

**Comment by SimonSchick** [comment]
poke, this is still kind of un-intuitive

**Comment by TannerS** [comment]
> customIndex

sorry for bringing up an old thread, what does `customIndex` actually mean/do?
