### ISSUE TITLE
Equivalent to "mysql" npm module's "on result" functionality

### ISSUE THREAD

**Issue by pkokorev** [sequelize/sequelize#905]
In the mysql npm module there is a way to pass a callback to a single row returned from the database and stream the result directly to the caller. This is particularly interesting in case of large number of records returned from the select query as it avoids creating enormous arrays of objects in memory. Looks like this functionality is missing in "sequelize". This could be a nice improvement to the "findAll" feature.

I am currently using the "mysql" module in my project and recently started looking for some ORM solution as it is getting quite boring to code similar CRUD stuff for every new entity I add to the model. For the moment, this "on result" feature is the only thing that blocks migration to "sequelize".

**Comment by janmeier** [comment]
Closing in favor of https://github.com/sequelize/sequelize/issues/2454 since that has more activity
