### ISSUE TITLE
Raw query replacements in MySQL INSERT query

### ISSUE THREAD

**Issue by Kirill89** [sequelize/sequelize#9050]
```js
db.query('INSERT INTO product (a, b) VALUES ?;', {
        replacements: [[['a', 'b'], ['c', 'd']]],
        type: Sequelize.QueryTypes.INSERT
});
```

## What do you expect to happen?

```mysql
INSERT INTO product (a, b) VALUES ('a', 'b'), ('c', 'd');
```

## What is actually happening?

```mysql
INSERT INTO product (a, b) VALUES 'a','b','c','d';
```

__Dialect:__ mysql
__Sequelize version:__ 4.32.3

So, the question is, how to insert non-determined number of items in one query?

**Comment by sushantdhiman** [comment]
Have you tried

```js
db.query('INSERT INTO product (a, b) VALUES (?), (?);', {
        replacements: [['a', 'b'], ['c', 'd']],
        type: Sequelize.QueryTypes.INSERT
});
```

Might be possible, but not sure

**Comment by Kirill89** [comment]
@sushantdhiman yes, it will work. But how to do that if I don't know number of items?

**Comment by sushantdhiman** [comment]
Well you can repeat, `(?)` to length of your array

```js
db.query(
  `INSERT INTO product (a, b) VALUES ${data.map(a => '(?)').join(',')};`,
  {
     replacements: data,
     type: Sequelize.QueryTypes.INSERT
  }
);
```

**Comment by Kirill89** [comment]
@sushantdhiman, but most of MySQL drivers can do it from the box.

I probably need to describe my case. In my project we are doing a migration from plain queries to ORM. As a first step we decide to use sequelize library to perform all SQL requests. And it was bad news for me that it's not compatible with usual placeholder syntax (like [here](https://github.com/mysqljs/mysql)).

**Comment by sushantdhiman** [comment]
We are using `mysql2`, I dont think it support array replacement

**Comment by sushantdhiman** [comment]
Can you test if `mysql2` can handle that sort of replacement, if it can I am willing to tag this as a feature request

**Comment by Kirill89** [comment]
@sushantdhiman, in `mysql2` it works.

```javascript
const mysql = require('mysql2');
const connection = mysql.createConnection({host: 'localhost', user: 'root', database: 'test', debug: true});

connection.query(
    'INSERT INTO product (a, b) VALUES ?;',
    [[['a', 'b'], ['c', 'd']]],
    (...args) => console.log(args)
);
```

In debug log: `Sending query command: INSERT INTO product (a, b) VALUES ('a', 'b'), ('c', 'd');`

**Comment by Kirill89** [comment]
@sushantdhiman, can you please review the pull request I did. It's almost copy from [SqlString](https://github.com/mysqljs/sqlstring/blob/master/lib/SqlString.js) library, which is used in `mysql2`. If it's looks suitable for you, I will add tests and update documentation.

**Comment by Kirill89** [comment]
Thank you!
