### ISSUE TITLE
how sequelize return to user just json?

### ISSUE THREAD

**Issue by LeoLfL** [sequelize/sequelize#9055]
## What are you doing?
I have a little question. When i console.log(answer) , where the answer is the result sequelize function f.e findAll it show me big json object like this 

```js
  _previousDataValues:
   { email: 'asfsgs1afg',
     password: 'sha1$18d616ea0090$4$c29fe292e7276d29c2f4b2ebf20c3fdbd3daa036',
     created: 2018-02-15T14:01:55.000Z,
     id: 112,
     username: undefined },
  _changed:
   { email: false,
     password: false,
     created: false,
     id: false,
     username: false },
  _modelOptions:
   { timestamps: true,
     validate: {},
     freezeTableName: true,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: { email: 'asfsgs1afg' },
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [],
     name: { plural: 'users', singular: 'user' },
     omitNull: false,
     createdAt: false,
     updatedAt: false,
     sequelize:
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [MysqlDialect],
        queryInterface: [QueryInterface],
        models: [Object],
        modelManager: [ModelManager],
        connectionManager: [ConnectionManager],
        importCache: [Object],
        test: [Object] },
     hooks: {},
     uniqueKeys: {} },
  _options:
   { isNewRecord: true,
     _schema: null,
     _schemaDelimiter: '',
     attributes: undefined,
     include: undefined,
     raw: undefined,
     silent: undefined },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false }

```

## What do you expect to happen?
But when i send this obj to user    res.send(answer); the user sees

`{
        "id": 112,
        "email": "asfsgs1afg",
        "created": "2018-02-15T14:01:55.000Z",
password: 'sha1$18d616ea0090$4$c29fe292e7276d29c2f4b2ebf20c3fdbd3daa036',
    }`

## What is actually happening?
But how and what sequalize did with this object? he use get({plain:true} before send to user or what??? Why user does not see all this object?

**Comment by sushantdhiman** [comment]
Model class implements a method called [toJSON](https://github.com/sequelize/sequelize/blob/196a381d3a9b9011b92a6a8484f9bcbb2dfa2ff8/lib/model.js#L4061), which returns plain values for instance.

When `res.send` is called it try to stringify object passed to it by using `JSON.stringify`. `JSON.stringify` internally[ calls `toJSON`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior) if its defined on object.

**Comment by onadeem1** [comment]
Thanks I was wondering this myself, I am curious, the same thing happens when we do a `findAll()` but we cannot run `.get({plain: true})` on the array when doing json. Is there a check somewhere in the library that maps over the array to get the plain values?
