### ISSUE TITLE
sequelize.sync with alter:true fails on mssql due to SYS.* tables and columns not found

### ISSUE THREAD

**Issue by jsanta** [sequelize/sequelize#9056]
## What are you doing?
As my app starts it tries to sync my model definitions with the actual database tables.
I know using alter: true is not recommended in production, but anyway I need to have this options for development.

```js
sequelize.sync({
        force: false,
        logging: dbLog,
        alter: true
    }).then(function () { /* ...  */ });
```

## What do you expect to happen?
Database sync and alter table queries executing  without problems due to un-existing tables, columns or objects.

## What is actually happening?
ERROR: SYS.* tables not found due to uppercase table and column names. MS Sql is case sensitive for both all database objects.

## Solution
On query_generator.js file replace all ```'.CONSTRAINT_TYPE'``` with lowercase ```constraint_type``` .

SQL on function ```_getForeignKeysQueryPrefix``` (line 653) must be corrected to include the catalog name if required:
```js
_getForeignKeysQueryPrefix(catalogName) {
    return 'SELECT ' +
        'constraint_name = OBJ.NAME, ' +
        'constraintName = OBJ.NAME, ' +
        (catalogName ? `constraintCatalog = '${catalogName}', ` : '') +
        'constraintSchema = SCHEMA_NAME(OBJ.SCHEMA_ID), ' +
        'tableName = TB.NAME, ' +
        'tableSchema = SCHEMA_NAME(TB.SCHEMA_ID), ' +
        (catalogName ? `tableCatalog = '${catalogName}', ` : '') +
        'columnName = COL.NAME, ' +
        'referencedTableSchema = SCHEMA_NAME(RTB.SCHEMA_ID), ' +
        (catalogName ? `referencedCatalog = '${catalogName}', ` : '') +
        'referencedTableName = RTB.NAME, ' +
        'referencedColumnName = RCOL.NAME ' +
      'FROM ' + (catalogName ? catalogName + '.' : '') + 'sys.foreign_key_columns FKC ' +
        'INNER JOIN ' + (catalogName ? catalogName + '.' : '') + 'sys.objects OBJ ON OBJ.OBJECT_ID = FKC.CONSTRAINT_OBJECT_ID ' +
        'INNER JOIN ' + (catalogName ? catalogName + '.' : '') + 'sys.tables TB ON TB.OBJECT_ID = FKC.PARENT_OBJECT_ID ' +
        'INNER JOIN ' + (catalogName ? catalogName + '.' : '') + 'sys.columns COL ON COL.COLUMN_ID = PARENT_COLUMN_ID AND COL.OBJECT_ID = TB.OBJECT_ID ' +
        'INNER JOIN ' + (catalogName ? catalogName + '.' : '') + 'sys.tables RTB ON RTB.OBJECT_ID = FKC.REFERENCED_OBJECT_ID ' +
        'INNER JOIN ' + (catalogName ? catalogName + '.' : '') + 'sys.columns RCOL ON RCOL.COLUMN_ID = REFERENCED_COLUMN_ID AND RCOL.OBJECT_ID = RTB.OBJECT_ID';
  },
``` 

__Dialect:__ mssql
__Dialect version:__ 4.29.2
__Database version:__ MSSQL 2017 running on Linux (Same hapens using MS SQL 2014 on Windows)
__Sequelize version:__ 4.29.2
__Tested with latest release:__ No

**Comment by jsanta** [comment]
A note on this is that the case sensititvity for the database will depend on its collation. As pointed out [here](https://www.webucator.com/how-to/how-check-case-sensitivity-sql-server.cfm) BIN and CS are Case Sensitive, and CI collations are Case Insensitive.
So checking the database collation would be a nice to have.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/9337
