### ISSUE TITLE
Memory perf: When retrive 37MB data(35k objects), the connectionManager holds 788MB in memory

### ISSUE THREAD

**Issue by Huan9** [sequelize/sequelize#9062]
## What are you doing?
We make a request to sql to retrieve the user list of apps including the app creator informaion . This require us join 4 tables: 'apps' (store app object), ''owners' (store owner object) and 'app_users'(store app user mapping) table and `table1` for a small table that store some app properties.

```js
// code here
```
`models.App.findAll(appQuery)
`
```
 const appsQuery: Sequelize.FindOptions = {
    include: [
      {
        model: models.Account,
        as: 'Owner',
        required: true,
        attributes: CommonResponseAttributes.APP_OWNER_ATTRIBUTES
      },
      {
        model: models.AppMembership,
        required: true,
        where: {
          user_id: userId,
          permissions: {
            $between: [APP_PERMISSIONS_TYPE.Manager, permission]
          }
        }
      },
      {
        model: models.table1,
        attributes: CommonResponseAttributes.TABLE1_ATTRIBUTES
      }
    ],
    order
  };
```
## What do you expect to happen?
The memory usage is promotion to the raw data size

## What is actually happening?

There are 35k apps, the raw size of data is 37MB, but the memory usage hold by the ConnectionManager is like 788MB

__Dialect:mssql
__Database version: V12 (azure sql)
__Sequelize version:3.31.1
__Tested with latest release:No

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Have you tried this against latest version (v4) where I would like to fix this if reason is bit clear

**Comment by Huan9** [comment]
Yes, the issue still repring. When we try to retrieve large number of items from sql, it cause memory spike.

**Comment by chenfengjw163** [comment]
same problem.
dialect:pg  sequlize:4.37.7 raw data is about 3163k objects, memory up to 4.5G, and node crashes.

**Comment by sushantdhiman** [comment]
Can you share this as a git repository, will be easier to resolve

**Comment by chenfengjw163** [comment]
```
{
"D_date_id":"20180524",
"D_app_key":"xxxxx",
"A_product_skn":"50003513",
"A_product_name":"EmelySweetie珠片简约欧美风短袖T恤",
"B_brand_name":"Emely Sweetie",
"C_middle_sort_name":"T恤",
"D_exp_pv":"2",
"D_exp_uv":"2",
"D_click_pv":"2",
"D_click_uv":"2",
"D_cart_pv":"0",
"D_cart_uv":"0",
"D_send_order_num":"0",
"D_send_order_uv":"0",
"D_pay_order_amount":"0",
"D_send_goods_num":"0",
"D_pay_goods_num":"0",
"D_send_order_amount":"0",
"D_pay_order_num":"0",
"D_pay_order_uv":"0",
"D_storage_amount_30":"0",
"D_storage_amount":"0"
}
```
Every object like this. There are 3163k results

**Comment by tony-gutierrez** [comment]
Im also having this issue with mssql in 4.37.10

**Comment by tony-gutierrez** [comment]
similar in 5.0.0-beta.7 with logging:false

**Comment by tony-gutierrez** [comment]
4.30.2 does not exhibit the issue.

**Comment by tony-gutierrez** [comment]
I think it was introduced in 4.32.7

**Comment by tony-gutierrez** [comment]
Anyone tested for this in a later version?

**Comment by byatis** [comment]
We are using sequelize 5.0.0-beta.14 and our API code runs smoothly for like 8-10 minutes under load test but then suddenly freezes for like 30 secs.  When I run locally I see error on heap memory. Disabling logging pushed a problem a bit further but didn't fix the symptom.  If I make the API call simple so it outputs only static json without using sequelize we can't make this happen.

**Comment by skliarovartem** [comment]
Same problem here. App uses a lot of memory and objects which you receive from sql requests are big and there a lot of nested objects in.

**Comment by gunar** [comment]
This PR might have fixed it in v5-beta.14
https://github.com/sequelize/sequelize/pull/10047

**Comment by papb** [comment]
Thanks @gunar - I will close the issue for now, but if it is still a problem for someone I will reopen. Thanks!
