### ISSUE TITLE
Sequelize querying column that doesn't exist

### ISSUE THREAD

**Issue by REX500** [sequelize/sequelize#9064]
## What are you doing?
Querying a database table with .all() function.

## What do you expect to happen?
I should get all the entries currently in the table.

## What is actually happening?
Error code: 42703
Sequelize returning modelName.columnThatDoesntExist doesn't exist.
So mappings table has 5 columns: id, yearId, clientId, createdAt, updatedAt.
Checked trough pgAdmin and also models/migrations. 
There is no reason sequelize should also query mappingsId column...
Mappings table has sub table called mappingStatus. Each mappings table can have many mappingStatuses which have mappingId column which is foreign key connected to mappings id column.
I tried including mappingStatus and no charm...
Note that this issue wasn't here until I deleted the tables and migrated again.

_Output, either JSON or SQL_
 name: 'error',
     length: 102,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '62',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3194',
     routine: 'errorMissingColumn',
     sql: 'SELECT "id", "clientId", "yearId", "createdAt", "updatedAt", "mappingId" FROM "mappings" AS "mappings";' },
  sql: 'SELECT "id", "clientId", "yearId", "createdAt", "updatedAt", "mappingId" FROM "mappings" AS "mappings";' }

__Dialect: postgres 
__Dialect version: 9.5.10
__Sequelize version: 3.2.0
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Please provide me a SSCCE. It will help me understand your problem quickly.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
