### ISSUE TITLE
Granular rejectOnEmpty configuration

### ISSUE THREAD

**Issue by pzanitti** [sequelize/sequelize#9066]
## What are you doing?
I want findOne and findById to reject on `null` result, and findAll to resolve with [] on empty result. It's so coding on Express and axios is easier. Axios resolves on 2xx and rejects on anything else, so I want the status to be something nicer than the defaults.

```
model.someModel.[findAll/findById/findOne](params)
    .then(responseHandler)
    .catch(error => {
      if (error instanceof Sequelize.EmptyResultError) {
        return res.status(404).send()
      } else {
        return res.status(500)
      }
    })
```

Testing with:

```js
db.someModel.findOne({ where: { id: 3 } }).then((res) => console.log('findOne resolves', res))
  .catch((err) => console.log('findOne rejects', err))

db.someModel.findById(3).then((res) => console.log('findById resolves', res))
  .catch((err) => console.log('findById rejects', err))

db.someModel.findAll().then((res) => console.log('findAll resolves', res))
  .catch((err) => console.log('findAll rejects', err))
```

## What do you expect to happen?
```
findById rejects SequelizeEmptyResultError
findAll resolves []
findOne rejects SequelizeEmptyResultError
```

I went ahead and overrode the prototypes like this guy did https://github.com/sequelize/sequelize/issues/8892

```
const originalFindById = Sequelize.Model.findById

Sequelize.Model.findById = async function (...args) {
  const obj = await originalFindById.call(this, ...args)
  if (obj === null) {
    throw new Sequelize.EmptyResultError()
  }

  return obj
}

const originalFindOne = Sequelize.Model.findOne

Sequelize.Model.findOne = async function (...args) {
  const obj = await originalFindOne.call(this, ...args)
  if (obj === null) {
    throw new Sequelize.EmptyResultError()
  }

  return obj
}
```
No problems yet but I wonder if I'll run into any. For example, findByOne internally calls findAll. If I overrode findAll most likely findByOne would break?

## What is actually happening?
```
findById resolves null
findAll resolves []
findOne resolves null
```

And if I turn on `rejectOnEmpty`: 

```
findById rejects SequelizeEmptyResultError
findAll rejects SequelizeEmptyResultError
findOne rejects SequelizeEmptyResultError
```

I wish I could set a middle ground using individual flags.

__Dialect:__ any
__Dialect version:__ -
__Database version:__ -
__Sequelize version:__ 4.33.4
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Why dont you set `rejectOnEmpty` when calling `findOne / findById`.

There is no configuration to make this a default option, override is a good option. There is a chance that Sequelize may call your overloaded method internally.

PR https://github.com/sequelize/sequelize/pull/8831 which will prevent overloaded methods from being used, but needs some work
