### ISSUE TITLE
include alias

### ISSUE THREAD

**Issue by skn3** [sequelize/sequelize#9067]
## What are you doing?

here is my association definition:

```js
assignment: {
    type: 'belongsToMany',
    schema: 'assignment',
    options: {through: schema.lookup('assignmentService'), constraints: true},
},
```

here is my scope:
```js
withStaff: {
    include: [
        {
            model: schema.lookup('assignment').unscoped(),//we dont want to pull tons of information!
            as: 'staff',
            required: false,
            include: [
                {
                    model: schema.lookup('staff').unscoped(),//we dont want to pull tons of information!
                    required: true,
                },
            ],
        }
    ],
},
```

## What do you expect to happen?
As you can see I have an assignment association on my container object. Inside the assignment object i then have *services* and *staff* associations. I need my association to be named *"assignment"* as that is what it is. I am trying to create a scope that utilises this structure but outputs the information under `instance.staff.foo` instead of `instance.assignments.foo`.

Is this even possible?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
