### ISSUE TITLE
Warning: Could not find any test files matching pattern: $npm_package_options_mocha

### ISSUE THREAD

**Issue by jerfowler** [sequelize/sequelize#9089]
The normal `npm test` fails on Windows because it is using $npm_package_options_mocha to pass in the command line parameters to mocha. Those command line variables aren't supported in Windows. Not sure why this was changed or how it works. Recommend reverting back to how `npm run cover` works.

https://github.com/sequelize/sequelize/blob/ce39d3893928c28919797c9eab6f6a817c39a8e9/package.json#L113
https://github.com/sequelize/sequelize/blob/ce39d3893928c28919797c9eab6f6a817c39a8e9/package.json#L103

**Comment by sushantdhiman** [comment]
Fixed #9576
