### ISSUE TITLE
How to sync mysql with sqlite

### ISSUE THREAD

**Issue by fsabreu** [sequelize/sequelize#9092]
Hello everyone

I am using this github as the basis for my sqlite sequelize.

[Git](https://github.com/waldemarnt/testable-nodejs-api)

And I'm creating a sequelize for mysql.

And I'm wondering how I can do to synchronize between banks.

Can you tell me if there is any function for this? or just using CRUD is possible for this.

Thank you so much.

**Comment by aprilmintacpineda** [comment]
I don't understand what you actually want to achieve. What do you mean "Synchronize between banks"?

Seems like your question has more to do with the programming rather than sequelize itself.

**Comment by fsabreu** [comment]
Sorry about my english. 

Let me try to explain it better. I have an online database (mysql) from where I will read the data and a local database (sqlite) where I will store this data for offline use if necessary.

My doubt is if, with some sequelize function I can do that synchronization.

I hope I have been able to explain now.

Thank you very much

**Comment by aprilmintacpineda** [comment]
@fsabreu Thanks. Sequelize on its own wouldn't be able to do that as far as I know, but you can do that programmatically.

**Comment by fsabreu** [comment]
@aprilmintacpineda Thank you! 

I've never done programming like this before.
Do you think that only with CRUD is it possible to do this?

**Comment by aprilmintacpineda** [comment]
@fsabreu yes it is.

**Comment by fsabreu** [comment]
@aprilmintacpineda Thank you!.

**Comment by fsabreu** [comment]
Sorry for reopening this issue

But I still can not find a solution to this problem.

Could you help me with some simple example?

Thank you.

**Comment by sushantdhiman** [comment]
If you want to move data or sync data between two different "banks" as you said, one being mysql other is sqlite, there is no inbuilt solution in sequelize.

You may need to initialize two instance one for mysql other for sqlite but still need to actually write code to sync or copy data between two databases.

IMO sequelize is not a appropriate tool to moving data like you are trying to do, for simple one off cases I will just dump data as csv, prepare it for other engine and dump to new database. For more complex cases if you are developing an application that regularly move data or sync data between different engine, as said above you need two different instances then write code to sync based on business rules
