### ISSUE TITLE
unique property on BelongsToMany association does not work

### ISSUE THREAD

**Issue by Kxze** [sequelize/sequelize#9093]
## What are you doing?
I have the following structure:

```js
const User = sequelize.define('user', {
  name: DataTypes.STRING
});

const Song = sequelize.define("Song", {
    name: DataTypes.STRING,
    mbid: DataTypes.STRING,
});

const Listen = sequelize.define("Listen", {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    }
});

User.belongsToMany(Song, { as: "Listens", through: { model: Listen, unique: false }});
Song.belongsToMany(User, { as: "Listens", through: { model: Listen, unique: false }});
```

## What do you expect to happen?
Table `listens` should be able to hold many values with the same foreign keys.

## What is actually happening?
Table `listens` is instead updated whenever I run `User.addSong(song)`.

__Dialect:__ mysql
__Dialect version:__ 5.7
__Database version:__ 5.7
__Sequelize version:__ 4.33.4
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Where did you learned about `unique: false` property

**Comment by Kxze** [comment]
Here: https://github.com/sequelize/sequelize/issues/2459

**Comment by Kxze** [comment]
Still an issue.

**Comment by sushantdhiman** [comment]
This is the default behaviour of `add*` it checks for rows first and update them if found any. If you want to create additional rows you need to do so manually using `JunctionModel.create`

In case of N:M there is a bug as well that multiple non unique rows wont return https://github.com/sequelize/sequelize/issues/3493
