### ISSUE TITLE
Transaction rollback performs partial rollback.

### ISSUE THREAD

**Issue by kamal123prd** [sequelize/sequelize#9105]
## Using transaction to update and insert data and manually rollback.

 have two update and one insert query associated with single transaction. The query order is : update1, update2, insert3. If I rollback on insert 3, update1 and update2 doesn't rollback (they get committed), only insert3 rollback happens.

```js
return sequelize.transaction().then(function(t) {
        return Indent.update({ 
            state_manager : timeStamp
        }, {
            where: {
                temp_indent_no : tempIndentNo,
                state_manager  : -100
            }
        },{
            transaction: t
        }).then(function() {
            console.log('1st update')
            return IndentItems.update({ 
                state_manager : timeStamp
            }, {
                where: {
                    temp_indent_no : tempIndentNo,
                    state_manager  : -100
                }
            },{
                transaction: t
            }).then(function() {
                console.log('2nd update')
                // return t.commit().then(function() {
                    // return sequelize.transaction().then(function(t) {
                return Indent.bulkCreate(rowsIndent, {
                    transaction: t
                }).then(function() {
                    console.log('1st insert')
                    return IndentItems.bulkCreate(rowsIndentItems, {
                        transaction: t
                    });
                }).then(function() {
                    console.log('2nd insert')
                    return t.commit().then(function() {
                        event.sender.send("updateDone");
                    });
                }).catch(function(err) {
                    console.log('1st rollback')
                    return t.rollback();
                })
            }).catch(function(err) {
                console.log('2nd rollback')
                return t.rollback();
            })
        }).catch(function(err) {
            console.log('3rd rollback')
            return t.rollback();
        });
    });
```

## What do you expect to happen?
_If it the trnsaction rollback, all the query associated to it should rollback._

## What is actually happening?
_only last query associated to this transaction rollbacks, earlier two update query gets committed.
In log I see following log getting printed : 1st update, 2nd update, 1st insert, 1st rollback. _

_Output, either JSON or SQL_

__Dialect:__ postgres 
__Dialect version:__ XXX
__Database version:__ 7
__Sequelize version:__ 4.33.4 
__Tested with latest release:__ 4.33.4

**Comment by sushantdhiman** [comment]
Please provide me a SSCCE. It will help me understand your problem quickly.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
