### ISSUE TITLE
I have some tables with exactly the same schema, how to define them as the same model?

### ISSUE THREAD

**Issue by jeasonstudio** [sequelize/sequelize#9108]
## What are you doing?

Because of the amount of data we have to shard, such as `asr_info_20180220`, `asr_info_20180221`, these table's schema are exactly the same.  
My understanding is that they can be defined as the same model. It does not yet support a model for multiple tables.

```js
/**
  * @param {String} [options.tableName] Defaults to pluralized model name, unless freezeTableName is true, in which case it uses model name verbatim
  */
```

## What do you expect to happen?

I may need a lot of `union like` operations. What should I do?

## What is actually happening?

Dialect: mysql
Sequelize version: latest

## Sample

* tableNames: `asr_info_201*`
* schema: 

| fieldName | type |
| --- | --- |
| id | INT |
| value | VARCHAR(20) |

I want find all effected rows:
1. `where value = 'test'`
2. `limit 100`
3. `RAND()`

Thanks a lot!

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by bqbs** [comment]
@jeasonstudio 您好！请问你是怎么解决这个问题的呢？
