### ISSUE TITLE
add association hooks

### ISSUE THREAD

**Issue by FranckFreiburger** [sequelize/sequelize#9113]
I wondering if it is possible to add hooks for Associations (like `beforeDefine`, `afterDefine`, ... for model)

## What are you doing?

```js
const User = db.define('user');
const Tag = db.define('user');

User.belongsToMany(Tag, { through: UserTag }); // trigger association created hook here
Tag.belongsToMany(User, { through: UserTag }); // trigger association created hook here
```

Currently, the best I can do is:
```js

var prev = Association.BelongsTo.prototype.injectAttributes;
Association.BelongsTo.prototype.injectAttributes = function() {
  // my hook here
  return prev.apply(this, arguments);
}

// ... and same for HasOne, BelongsToMany, HasMany
```

__Sequelize version:__ latest version

**Comment by lukeed** [comment]
Add a `*Create` hook on your `UserTag` model.

**Comment by FranckFreiburger** [comment]
I agree that this will work for belongsToMany because of the through model,
however I also need callback for new BelongsTo, HasOne and HasMany associations.

**Comment by sushantdhiman** [comment]
You want to modify association option using these hooks I assume, currently there are no such hooks available but should be easy to add them. I am tagging this as a feature request.

**Comment by NicolasNarvaez** [comment]
I need this to transparently keep track of references to a model, do you know another way to do it?

**Comment by sushantdhiman** [comment]
Implemented in https://github.com/sequelize/sequelize/pull/9590

`beforeAssociate / afterAssociate`
