### ISSUE TITLE
findAndCountAll wrong count when calling scope.

### ISSUE THREAD

**Issue by yusbel80** [sequelize/sequelize#9115]
When including an association on a scope, the count returned from findAndCountAll is wrong.

For example. I am including a 'telephones' table associated to a user, in which the user has many telephones. Querying by the user's id to get a total of one results, if the associated table 'telephones' has more than 1, the count returned from findAndCountAll is that of the 'telephones' table count.
So if the 'telephones' table returns 5 results, the count is 5. Not 1.

If I try adding distinct property inside the scope. I get an sql error.

My workaround is to not use scope and add the distinct, and includes in the method. That way findAndCountAll returns the correct count.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
