### ISSUE TITLE
Possibility of having an ARRAY datatype with CITEXT fields

### ISSUE THREAD

**Issue by adriaanvanrossum** [sequelize/sequelize#9116]
## What are you doing?

I am trying to add a custom datatype for CITEXT as part of an ARRAY. I search the database with case insensitive because I don't control the search terms. Is this possible to do with sequelize?

I tried this:

```js
export default (sequelize, DataTypes) => {
  class CITEXT extends DataTypes.TEXT {
    constructor () {
      super()
      this.key = 'CITEXT'
    }
  }

  const Model = sequelize.define('artist', {
    id: {
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
      type: DataTypes.INTEGER
    },
    slug: {
      allowNull: false,
      type: 'CITEXT' // <-- here I use a custom class, this works
    },
    names: {
      allowNull: false,
      type: DataTypes.ARRAY(CITEXT) // <-- but this does not work
    }
  });

  return Model;
};
```

## What do you expect to happen?
That I could access the ARRAY in sequelize like a normal JS array.

## What is actually happening?
This is what I got in the console (which looks correct)

```sql
CREATE TABLE IF NOT EXISTS "artists" ("id" SERIAL, "slug" CITEXT NOT NULL, "names" CITEXT[] NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
```

But this is what I get in the JS code

```js
sequelize.sync({ force: true }).then(() => {
  return models.artist.create(
    slug: 'cali-dubuque',
    names: ['Cali DuBuque']
  }).then(artist => {
    console.log('===> artist.names', artist.get('names'))
    // ===> artist.names {"Cali DuBuque"}
  });
});
```

`artist.get('names')` should output an array `['Cali DuBuque']` instead of a string `'{"Cali DuBuque"}'`

__Dialect:__ postgres
__Dialect version:__ 7.4.1 (node package `pg`)
__Database version:__ 10.2 (`psql --version`)
__Sequelize version:__ 4.34.1
__Tested with latest release:__ yes

**Comment by adriaanvanrossum** [comment]
Nice, thanks pray 🙏

**Comment by hyber1z0r** [comment]
Is it not possible to somehow combine `$contains` and `sequelize.fn('lower')` to achieve this instead?

**Comment by adriaanvanrossum** [comment]
Could be but I don't use Sequelize anymore.
