### ISSUE TITLE
Model QueryInterface()

### ISSUE THREAD

**Issue by hisorange** [sequelize/sequelize#9118]
Aye! 
Got into a weird situation and wanted to discuss about the topic before making a PR on it.
So, the Model has a get QueryInterface() accessor and it is used in most of the code it's wrapper for: 

```js
return this.sequelize.getQueryInterface()
```

And it's awesome, we have a special tenant setup and this looked a good place to hook into the flow to inject our custom solution. 

But... there is 6 occurence of the __this.sequelize.getQueryInterface__ directly, this affects the save, delete, increment and update calls. Now my question would be: Is those calls are survivors of a code refactoring or has any deep reason to be called in this way? If not, I would gladly make a PR to find and unify those calls!

- Accessor [here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L43)
- Direct calls: [0](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2998) [1](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3000) [2](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3652) [3](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3863) [4](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3877)

Thanks for your anwser, and keep up this awesome work!

**Comment by sushantdhiman** [comment]
Old code fragment, will be happy to accept this change :+1:
