### ISSUE TITLE
sequelize.literal() not working correctly across library boundaries

### ISSUE THREAD

**Issue by MayaYL** [sequelize/sequelize#9121]
## What are you doing?

Much like https://github.com/sequelize/sequelize/issues/8663, I'm trying to use `Sequelize.literal` across library boundaries. We have a persistence library that provides an interface for other node repositories to interact with the models and connections that are contained within. Both the persistence library and the calling code are using Sequelize 4.35.0.

In this particular case we are trying to increment the value of a column by one, in the update clause:

```js
{ retries: sequelize.literal('retries + 1') }
```

## What do you expect to happen?
The result of evaluating `sequelize.literal('retries + 1')` should be recognized as an instance SequelizeMethod in query-generator.js, but it isn't- we get an error instead. However, if we run that directly in the persistence library, it works as expected and increments the value of `retries` by 1.

## What is actually happening?
It appears that when calling across library boundaries, query-generator.js is trying to interpret the value as a string, unsuccessfully:

```
Error: Invalid value Literal { val: 'retries + 1' }
at Object.escape (/home/project/node_modules/persistence_library/node_modules/sequelize/lib/sql-string.js:66:11)
at Object.escape (/home/project/node_modules/persistence_library/node_modules/sequelize/lib/dialects/abstract/query-generator.js:927:22)
at Object.updateQuery (/home/project/node_modules/persistence_library/node_modules/sequelize/lib/dialects/abstract/query-generator.js:360:58)
at QueryInterface.bulkUpdate (/home/project/node_modules/persistence_library/node_modules/sequelize/lib/query-interface.js:1030:37) 
```

We have tried initializing a `sequelize` object with the proper dialect (postgres) in the code calling the persistence library, but the same error occurred.

__Dialect:__ postgres
__Dialect version:__ 6.4.2
__Database version:__ 6.4.2?
__Sequelize version:__ 4.35.0
__Tested with latest release:__ Yes: 4.35.0 5b6dae7

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
We usually share multiple sequelize instances by using rough replica from https://github.com/sequelize/express-example/blob/master/models/index.js

I assume you are trying to "require" sequelize in those dependent repositories whenever you want to use `literal / fn`. I suggest just share one singleton as `express-example` then use `literal` from main exported `sequelize` instance of that singleton.

```js
const models = require('some-shared-models');
const Sequelize = require('sequelize');

// Sequelize.literal wont be same as literal used by `some-shared-models`

const models = require('some-shared-models');

// use models.literal directly assuming shared models loaded
// using https://github.com/sequelize/express-example/blob/master/models/index.js
```
