### ISSUE TITLE
Table Valued Parameters Support or Tedious Core Function Support

### ISSUE THREAD

**Issue by npshubh** [sequelize/sequelize#9122]
I need a function that can execute with TVP in sequelize. As of now, I'm using Tedious function to achieve that but I need to add some extra connection and connection pooling code for that.

Is there any way by which either I can execute tedious function on sequelize pooling or is there any method in sequelize that can work for me?

**Comment by sushantdhiman** [comment]
```js
// get pooled connection
sequelize.connectionManager.getConnection() // Promise<ConnectionLock>

// releasing pooled connection
sequelize.connectionManager.releaseConnection(connection) // Promise
```

**Comment by npshubh** [comment]
Thanks @sushantdhiman, can you please let me know how it can help me to run tedious function "connection.callProcedure(request)" using this connection? I was not able to run tedious function using this connection promise.

**Comment by sushantdhiman** [comment]
I hope you know how to use promises, here is a general example of what you need to do with async / await

```js
const lock = await sequelize.connectionManager.getConnection();
const connection = lock.unwrap(); // for mssql only

// do anything you want with raw tedious connection
connection.query(...)

// release real connection lock once you are done
await sequelize.connectionManager.releaseConnection(lock);
```

**Comment by npshubh** [comment]
This is how we connect to tedious 
`let Connection = require('tedious').Connection;
let config = {
    userName: 'dbuser1',
    password: 'r00tMssql',
    server: 'mssqldbinstance.crhtk6bskfig.us-west-2.rds.amazonaws.com',
    options: {database: 'testdb', rowCollectionOnRequestCompletion: true}
};
let connection = new Connection(config);

connection.on('connect', function(err) {
	if (err) {
		console.log(err);
	} else {
		console.log("connected");
	}
});`

and then we use tedious function 
`connection.callProcedure(request);`

But as you know that sequelize uses tedious for MSSQL, so can I use seqeulize connection to run this tedious function of calling a TVP query
`connection.callProcedure(request);`
using sequelize connection?

Getting only connection obejct will not help me to run tedious function.

**Comment by peveuve** [comment]
With Sequelize 6.6 unwrapping the connection is not necessary anymore.
