### ISSUE TITLE
Sync alter ignored the model field settings

### ISSUE THREAD

**Issue by winsontam** [sequelize/sequelize#9139]
If i defined

        createdAt: {
            type: DataTypes.DATE,
            allowNull: false,
            field: 'created_at'
        },

it will compare the column name by "createdAt" but not by "created_at".

**Comment by sushantdhiman** [comment]
> it will compare the column name by "createdAt" but not by "created_at".

It will compare with an alias `createdAt` backed by `created_at`

**Comment by winsontam** [comment]
No, the situation is when i run sync({alter: true})  in the first time.
It created "created_at" column.
but if i run the sync({alter: true}) again, it will delete "created_at" column and add "createdAt" column.

**Comment by sushantdhiman** [comment]
Can you tell me 

1. Database version
2. Sequelize version
3. Queries executed (with a bit formatting so I can read)

Or open a new issue properly following issue template
