### ISSUE TITLE
sqlite: password is not set

### ISSUE THREAD

**Issue by muccix** [sequelize/sequelize#9140]
## What are you doing?

I'm using sequelize with sqlite3 inside an electron app

```js
const Sequelize = require('sequelize');

const sequelize = new Sequelize('database', 'username', 'password', {
  dialect: 'sqlite',
  storage: '/home/me/TEMP/database.sqlite'
})


sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });


const User = sequelize.define('user', {
  firstName: {
    type: Sequelize.STRING
  },
  lastName: {
    type: Sequelize.STRING
  }
});


User.sync().then(() => {
  // Table created
  return User.create({
    firstName: 'John',
    lastName: 'Hancock'
  });
});
```

## What do you expect to happen?
I would expect the created DB to be password protected but I can access the DB without credentials (using http://sqlitebrowser.org/)

__Dialect:__ sqlite
__Dialect version:__ 3.1.13
__Sequelize version:__ 4.35.2
__Tested with latest release:__ Yes

**Comment by muccix** [comment]
I think I found the issue: see [node-sqlite3 readme](https://github.com/mapbox/node-sqlite3#custom-builds-and-electron). sqlite3 need to be rebuilt to preserve sqlcipher in a nelectron app.

**Comment by Vovka19** [comment]
ok. Thank you:)
