### ISSUE TITLE
Index aliasing in sequelize migrations

### ISSUE THREAD

**Issue by glalaj** [sequelize/sequelize#9146]
## What are you doing?
During migrations I can create unique keys using addIndex(tablename, attributes, options, rawtableName). The name of the index is automatically appointed by sequelize. 

While creating a composite key made of 4 fields I got an error complaining that the key name was too long. 

## What do you expect to happen?
I think it would be a nice feature to be able to define the key name. Ex. 
```
addIndex(tableName, attributes, indexName, options, rawtableName){
      //creates an index with the name passed in the param indexName
}
```

## What is actually happening?
```
addIndex(tableName, attributes, options, rawtableName){
       //assuming attributes = ['col1', 'col2', 'col3', 'col4', ...]
       //creates an index where the name is tableName_col1_col2_col3_col4...
       //Sometimes this is a way too long name and fires an error
}
```

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addIndex

> options.name | String | optional | Name of the index. Default is <table><attr1><attr2>
