### ISSUE TITLE
order produces incorrect SQL

### ISSUE THREAD

**Issue by UKNC** [sequelize/sequelize#9147]
## What are you doing?

```js
    const users = await User.findAll({order: ["email", "DESC"] })
```

## What do you expect to happen?
Correct SQL:

```sql
SELECT "id", "email" FROM "users" AS "user" ORDER BY "user"."email" DESC
```

## What is actually happening?
Incorrect SQL:
```sql
SELECT "id", "email" FROM "users" AS "user" ORDER BY "user"."email", "user"."DESC"
```
__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.35.2
__Tested with latest release:__ 4.35.2

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sethbonnie** [comment]
What you want is an array `["email", "DESC"]` rather than the string`"email"` as your first element

```js
const users = await User.findAll({order: ["email", "DESC"] })
```

should be

```js
const users = await User.findAll({order: [["email", "DESC"]] })
```

**Comment by janmeier** [comment]
@sethbonnie Is correct
