### ISSUE TITLE
Sequelize.ENUM does not support the substring COMMENT

### ISSUE THREAD

**Issue by Poupouch** [sequelize/sequelize#9149]
## What are you doing?
I am creating a table with a column of type `ENUM` with a string containing the substring `COMMENT`.

```js
const sequelize = new Sequelize();
sequelize.define('table', { column: Sequelize.ENUM(['COMMENT']) });
sequelize.sync({ force: true });
```

## What do you expect to happen?
I want the `sync` to create a table named "table" with the column "column" with a type "enum_table_column" with the value "COMMENT".

## What is actually happening?
The `sync` errors while creating the table. This error occurs for any string containing the substring `COMMENT`. It seems that Sequelize is interpreting the keyword `COMMENT` as the SQL COMMENT operator.

_CREATE TABLE IF NOT EXISTS "contacts" ("id"   SERIAL , "col" ENUM(', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id")); COMMENT');_

__Dialect:__ postgres
__Dialect version:__ 9.6.6
__Sequelize version:__ 4.32.7
__Tested with latest release:__ No

**Comment by hisorange** [comment]
Define it like this:
```
const sequelize = new Sequelize();
sequelize.define('table', { column: Sequelize.ENUM('COMMENT', 'VALUE2') });
sequelize.sync({ force: true });
```

Based on this [source](https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L642)

**Comment by Poupouch** [comment]
@hisorange Thank you for your response, unfortunately we have the same result using `Sequelize.ENUM('COMMENT')`, as well as `Sequelize.ENUM('COMMENT', 'OTHER_VALUE')`.
We've tried using [Sequelize.literal](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#static-method-literal), [Sequelize.cast](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#static-method-cast), nothing do!

**Comment by hisorange** [comment]
@Poupouch Sorry! I was tired when found the issue and didn't read it well, ofc it will not solve your issue. But gona look into it, got curious now :D

**Comment by dspigarelli** [comment]
I believe the issue is this `.indexOf('COMMENT')` is too broad and catching non-comment strings: https://github.com/sequelize/sequelize/blob/9b1ca37b5a4533507f5cc87fe99e33877a557fa4/lib/dialects/postgres/query-generator.js#L50
