### ISSUE TITLE
How can I format raw query results to sequelize model has associate?

### ISSUE THREAD

**Issue by shuperry** [sequelize/sequelize#9155]
![bf4ca4ad-2a03-4de2-910e-6117d9f94aba](https://user-images.githubusercontent.com/12183336/37129789-9b5360e8-22bb-11e8-915a-cfbe333aa6aa.png)

Can I use include in the second parameter named model like this:
![43e78af4-17cf-4d53-b47b-d68a0d572b68](https://user-images.githubusercontent.com/12183336/37129854-d82afbe8-22bb-11e8-8bda-eebe0e894273.png)

Or, is there any way to format standard query results to sequelize model instance?

**Comment by sushantdhiman** [comment]
See https://github.com/sequelize/sequelize/issues/5685
