### ISSUE TITLE
findAndCountAll returns invalid results 

### ISSUE THREAD

**Issue by shajunr88** [sequelize/sequelize#9160]
Iam using sequelize findAndCountAll to select from the postgres db.Following is the code 
`const invoices = await Invoice.findAndCountAll({attributes:['invoice_amount','bill_period_from','bill_period_to'],where:db.sequelize.literal("invoices.user_id ="+user_id+" and date_part('year', bill_period_from) = date_part('year', current_date)")});
`
The query executed is shown as 
`SELECT "invoice_amount", "bill_period_from", "bill_period_to" FROM "invoices" AS "invoices" WHERE invoices.user_id =112 and date_part('year', bill_period_from) = date_part('year', current_date);`
When executing the query in database,it returns two rows But from the sequelize it returns only one rows.Why this happens

**Comment by jharting** [comment]
@shajunr88 what version?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
