### ISSUE TITLE
Certain query results not properly mapping to instance fields for BelongsToMany models

### ISSUE THREAD

**Issue by simonsayscode** [sequelize/sequelize#9167]
Discovered this bug while doing something like Model.update(values, { returning: true }).

I expected the returned object to be set to my model instance, and that field names would be correctly mapped. However, that wasn't the case and only a small subset of fields was returned and mapped. 

Dug into Sequelize code more and verified that mapToModel was being set to true on (https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L337) in the updateQuery function.

However, the problem was at fieldMap (https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L462) because the model.fieldAttributeMap was only a small subset of features that should be properly mapped. 

Digging even deeper, I discovered that the first time the Model was defined, and it reached refreshAttributes from the init function, it properly constructed the rawAttributes and subsequently the fieldAttributeMap from fieldRawAttributesMap (https://github.com/sequelize/sequelize/blob/master/lib/model.js#L964)

However, since the Model was included in a belongsToMany association, refreshAttributes is being called once again from the injectAttributes function which has a more complex rawAttributes than the first time. When it goes through the _.each loop again creating the fieldRawAttributesMap, the field that occurs later in the rawAttributes overwrites the previous defintion, and since the key for many is equal to the fieldName (https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1035).

This causes the fieldAttributeMap to be incorrect when used for any query for that Model that relies on the fieldAttributeMap. A reason why this issue isn't more immediately noticeable is that for any find query, the SELECT statement properly organizes the database query to return field names already mapped to the desired Sequelize name as opposed to the update queries which returning * (https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L338).

There's also an additional issue with the fact that for some reason the createdAt timestamps field isn't being set in the rawAttributes and the same overwriting because of object key ordering and key === value.fieldName is deleting it from the fieldAttributeMap.

Please take a look at the following Webstorm debugging screenshots for more visual clarity for the detail above.

First call to refreshAttributes from Model.init on Sequelize model definition.
![screen shot 2018-03-09 at 5 19 16 pm](https://user-images.githubusercontent.com/1683230/37232695-1fe24dee-23be-11e8-8fc8-86cb29d8ed56.png)

Generated fieldRawAttributesMap and fieldAttributeMap after first refreshAttributes run through.
![screen shot 2018-03-09 at 5 34 00 pm](https://user-images.githubusercontent.com/1683230/37233178-2a0fe446-23c0-11e8-98f1-ecc797aea9a1.png)

Second call to refreshAttributes from BelongsToMany.injectAttributes, showing that rawAttributes is now populated with additional values, namely the database field names in addition to the model field names. A single opened example of lessonId vs lesson_id to show the contents
![screen shot 2018-03-09 at 5 59 41 pm](https://user-images.githubusercontent.com/1683230/37234050-b4d13f50-23c3-11e8-8d8d-4e6ca82ed163.png)

Generated fieldRawAttributesMap and fieldAttributeMap after the second refreshAttributes run through. Note how there is considerably less in the fieldAttributesMap that is later used for mapToModel options in query returns.
![screen shot 2018-03-09 at 5 39 50 pm](https://user-images.githubusercontent.com/1683230/37233403-04af6b9e-23c1-11e8-94da-06eb3a8abec3.png)

Again, also note how started_at is treated and how it is different than other fields, which is odd given the Model defintion example code below.

## What are you doing?

```js
const LessonStatus = sequelize.define('lesson_status', {
    id: {
      primaryKey: true,
      allowNull: false,
      type: Sequelize.INTEGER,
      autoIncrement: true,
    },
    lessonId: {
      type: Sequelize.INTEGER,
      field: 'lesson_id',
      unique: 'lesson_statuses_user_id_lesson_id_unique',
      allowNull: false,
      references: {
        model: 'lessons',
      },
    },
    userId: {
      type: Sequelize.INTEGER,
      field: 'user_id',
      unique: 'lesson_statuses_user_id_lesson_id_unique',
      allowNull: false,
      references: {
        model: 'users',
      },
    },
    status: {
      type: Sequelize.ENUM,
      values: ['started', 'completed'],
      allowNull: false,
    },
    startedAt: {
      type: Sequelize.DATE,
      field: 'started_at',
    },
    completedAt: {
      type: Sequelize.DATE,
      field: 'completed_at',
    },
  }, {
    timestamps: true,
    updatedAt: false,
    createdAt: 'started_at',
    underscored: true,
  });

// Later on used in a belongsToMany association...
// Assume that Users exists and Lessons exist.
    User.belongsToMany(models.Lesson, {
      as: 'lessonStatuses',
      through: models.LessonStatus,
    });

// Then later on usage....
LessonStatus.update(lessonStatusData, {
    where: {
      id: lessonStatusId,
    },
    returning: true,
  })
```

## What do you expect to happen?
Expected the returned rows to be LessonStatus instances with the field names properly mapped.

## What is actually happening?
The _dataValues didn't not contain mapped attributes for many of the fields. The majority had the database naming variation as opposed to the Sequelize model naming.

If I had to guess, I would say that the issue is stemming from how rawAttributes is generated in model.js which changes between the first and second run through of refreshAttributes.

Note, as a workaround, rather than just relying on the returned value from the update operation, doing a findById and returning that.

__Dialect:__ postgres 
__Dialect version:__ 7.4.1
__Database version:__ 9.6.1
__Sequelize version:__ 4.35.2
__Tested with latest release:__ Yes (4.35.2)

**Comment by kkotwal94** [comment]
Out of curiosity how are you debugging this?

**Comment by simonsayscode** [comment]
I use Webstorm for a more interactive and visual IDE. It allows me to put breakpoints in and step into the node_modules/sequelize code.

**Comment by dhans** [comment]
Just wanted to report that I'm hitting this issue as well. Current work-around is manually mapping field names or doing an extra DB call that uses SELECT.
