### ISSUE TITLE
JSON schema definitions for JSON/JSONB field content

### ISSUE THREAD

**Issue by wimolivier** [sequelize/sequelize#9168]
Hi,

Please add the capability to define the JSON schema of JSON/JSONB fields in tables, i.e. for a PostgreSQL JSONB field, similar to how MongooseJS does this for MongoDB.

This will help a lot in sticking with the JSON schema and not drifting off it by accident when inserting data.

Is there a package out there that perhaps can do this for Sequelize/Postgres?

Thanks,
Wim

**Comment by sushantdhiman** [comment]
I have not used it myself but `sequelize-joi` should help

- https://github.com/sequelize/sequelize/wiki/Add-ons-&-Plugins#miscellaneous
- https://www.npmjs.com/package/sequelize-joi

**Comment by wimolivier** [comment]
Thanks sushantdhiman,

I will give it a go.

Regards,
Wim
