### ISSUE TITLE
Problems running sequelize -m on Heroku

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [sequelize/sequelize#917]
Hi, does anybody here knows how to avoid this error on heroku?

Error: Failed to authenticate for PostgresSQL. Please double check your settings

I need to run some migrations using `sequelize -m` and I can't do it because my node app is running there.

**Comment by rahul1346** [comment]
How did you solve this?

**Comment by caio-ribeiro-pereira** [comment]
Hi, I just create a npm alias, to run theses commands: `sequelize -m && node app`
