### ISSUE TITLE
" through: { attributes: [] } " does not work during "getTableName()"

### ISSUE THREAD

**Issue by Noolie** [sequelize/sequelize#9170]
## What are you doing?
belongsToMany: 
```
  const projects = await models.user.getProjects({
    model: models.project,
    through: {
      attributes: [], // <= doesn't work
    },
    attributes: ['name', 'date'],  // <= works fine.
  });
```

## What do you expect to happen?
Expecting exclude **through** field

## What is actually happening?
Getting **through** table in outgoing data

__Dialect:__ mysql
__Sequelize version:__^4.32.2,

**Comment by pkyeck** [comment]
any luck with that so far?

**Comment by leonardorb** [comment]
Also having this issue here. Getting an extra attribute here based on the `belongsToMany` association.
```
{
  "id": "abc84701-512c-4aae-8e0e-f20fdb772321",
  "name": "Documents",
  "members_modules": {
    "created_at": "2018-05-11T17:41:28.044Z",
    "updated_at": "2018-05-11T17:41:28.044Z",
    "member_id": "e1f03652-e26d-4b8c-9053-8ed95377f27c",
    "module_id": "abc84701-512c-4aae-8e0e-f20fdb772321"
  }
}
```
Tried: `through: { attributes: [] }`, no luck.

**Comment by tresdev** [comment]
When I'm useing find(..) function with a model class, `through: { attributes : [] }` is working right.
But when I'm using `getTableName()`, it just doesn't.
I think we an need an update for that.

**Comment by stephenheard** [comment]
I'm having a similar issue, where I can't get the through attributes to not be selected, and it is causing my query to fail because it uses aggregations.  Using `through: { attributes: [] }` is not working.

**Comment by stephenheard** [comment]
#9401 worked for me.
