### ISSUE TITLE
Is it possible to achieve single inheritance in sequelize just like active record in rails. 

### ISSUE THREAD

**Issue by jawadakram20** [sequelize/sequelize#9174]
## What are you doing?

```js
// code here
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by jawadakram20** [comment]
@janmeier @sdepold

**Comment by janmeier** [comment]
You clearly already found this issue https://github.com/sequelize/sequelize/issues/1243

If the feature was implemented, that issue would have been closed :)

**Comment by jawadakram20** [comment]
@janmeier I was wondering if I can implement single table inheritance and needed help regarding that.
