### ISSUE TITLE
How to define multiple unique constraints having a common column

### ISSUE THREAD

**Issue by daole** [sequelize/sequelize#9176]
I have a requirement to create a table like this
{
            id: {
                field: "id",
                type: sequelizeModule.INTEGER,
                primaryKey: true,
                autoIncrement: true
            },
            passengerId: {
                field: "passenger_id",
                type: sequelizeModule.INTEGER,
                allowNull: false,
                unique: "passenger_event_schedule"
            },
            eventScheduleId: {
                field: "event_schedule_id",
                type: sequelizeModule.INTEGER,
                allowNull: false,
                unique: "passenger_event_schedule"
            },
            code: {
                field: "code",
                type: sequelizeModule.STRING(45),
                allowNull: false,
                unique: "event_schedule_code"
            }
}
I placed a composite unique constraint "passenger_event_schedule" on passenger_id and event_schedule_id as it's obvious that there should be only 1 record of a passenger on an event. Now i want to add another unique constraint on event_schedule_id and code because each passenger is assigned a unique code on an event but I don't know how to do so. Could anyone please teach me how to achieve that?

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#indexes

**Comment by ibrahimazam11** [comment]
the link is not working. can anyone post the solution here or add a valid link?
