### ISSUE TITLE
.increment() returns wrong SQL and an error

### ISSUE THREAD

**Issue by NicTorgersen** [sequelize/sequelize#9180]
## What are you doing?
Trying to increment an INTEGER in a `postgres` database.

Model
```js
var Article = sequelize.define('article', {
    id: {
      type: DataTypes.UUID,
      unique: true,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4,
    },
    title: DataTypes.STRING,
    content: DataTypes.TEXT,
    timesViewed: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
  }, {
    paranoid: true,
    timestamps: true,
    underscored: false,
    freezeTableName: true,
    tableName: 'articles',
  })
```

Code
```js
var article = await models.article.findOne({where: {id: 1}})
article.increment(['timesViewed'], {by: 1, silent: true})
article.reload()
```

## What do you expect to happen?
That the `timesViewed` column is incremented by 1.

## What is actually happening?
The transaction fails, and sequelize returns an error:

`Unhandled rejection SequelizeDatabaseError: column "0" of relation "articles" does not exist`

```sql
UPDATE "articles" SET "timesViewed"="timesViewed"+ 1,"0"='id',"1"='title',"2"='content',"3"='timesViewed',"4"='created',"5"='updated' WHERE "id" = 1 RETURNING *
```

As is apparent, the SQL is mangled. Is this because I'm using a complex defaultScope with multiple attributes?

Edit: Tested with a scope that only had timesViewed as an attribute, and I got the same error:

```sql
UPDATE "articles" SET "timesViewed"="timesViewed"+ 1,"0"='timesViewed' WHERE "id" = NULL RETURNING *
```

__Dialect:__ postgres
__Dialect version:__ 10.3
__Database version:__ 10.3
__Sequelize version:__ 4.36.1
__Tested with latest release:__ Yes, 4.36.1

**Comment by sushantdhiman** [comment]
Try with unscoped model, last query is using `"id" = NULL`??. Can you show me full test case that reproduce this

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
