### ISSUE TITLE
feature request: more flexible attribute selection with include:[{ all:true, nested:true }]

### ISSUE THREAD

**Issue by FranckFreiburger** [sequelize/sequelize#9185]
## What are you doing?

I have a simple configuration: manager, shop, product, image, moderation
- manager has many shops
- shop has many products
- product has many images

image is moderable (using association scopes (wonderful)) through the following model:

moderation
	- moderable: string
	- moderableId: integer
	- ...

Now, when an image has been moderated, I need to notify the manager (there is no direct relation between the image and the manager).
I simply use nested eager loading including all:

```js
var all = await image.findById(1, { attributes:[], include:[{ all:true, nested:true }] });
var manager = nestedFindFirstManagerModel(all); // that simply recussively look for the first manager model
```
done, I have my manager.

This process is quite long and I would like to minimise the number of attributes for included models (like for the main one, `attributes:[]`)

Then I use `image.findById(1, { attributes:[], include:[{ all:true, nested:true, attributes:['id'] }] })` that works properly because at the moment my pk are always 'id'. This is 60% faster now.

What I propose is the following enhancement:

`[{ all:true, nested:true, attributes:genAttributes }]`

where genAttributes is a function:
example:
```
function genAttributes(model) {

	if ( model instanceof managerModel )
		return undefined; // all attributes, like if attributes where not specified
	else
		return model.primaryKeyAttributes; // returns only pk
}
```

**Comment by sushantdhiman** [comment]
Sorry @FranckFreiburger but I am not willing to add this, `[{ all: true, nested: true }]` should do what its supposed to with minimum configuration option.

Your case can be solved with 3 level of includes and is a better option which gives you more control over how you want those attributes to be selected
