### ISSUE TITLE
Op.and with Op.like

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#9195]
This should be so simple, I just can't find a good example.  I have a column named "name" and I want to do a LIKE search on two or more words.  For example "tree collective", %tree% AND %collective, so the name must contain both words.  What am I doing wrong??

```
		dispensary.findAndCountAll({
			where: {
				[DataTypes.Op.and]: {
					name: { 
						[DataTypes.Op.like]: ['%tree%']			
					},
					name: { 
						[DataTypes.Op.like]: ['%collective%']			
					}				
				}
			},
```

**Comment by sushantdhiman** [comment]
It seems to work properly

```js
'use strict';

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const Model = sequelize.define('Model', {
  name: Sequelize.STRING
});

Model
  .sync({ force: true })
  .then(() => {
    return Model.bulkCreate([
      { name: 'tree' },
      { name: 'root' },
      { name: 'long long tree and deep deep roots' }
    ]);
  })
  .then(() => {
    return Model.findAll({
      logging: console.log,
      where: {
        [Sequelize.Op.and]: [
          {
            name: {
              [Sequelize.Op.like]: ['%tree%']
            }
          }, {
            name: {
              [Sequelize.Op.like]: ['%root%']
            }
          }
        ]
      }
    });
  })
  .then(records => {
    console.log(records.length);
    console.log(records[0].toJSON());
  });
```

```bash
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `Models` AS `Model` WHERE (`Model`.`name` LIKE '%tree%' AND `Model`.`name` LIKE '%root%');
1
{ id: 3,
  name: 'long long tree and deep deep roots',
  createdAt: 2018-03-19T04:09:02.641Z,
  updatedAt: 2018-03-19T04:09:02.641Z }

```

Please in future follow the issue template, it helps me understand your issue properly. Respect our community guidelines

**Comment by knoxcard** [comment]
Oh wow, I was just missing another set of parenthesis, GOOD GRIEF!

Thank you @sushantdhiman for pointing this out.  Personally, I ended up going with a raw sql solution to better fit my use case, but this ticket will serve as a great reference to future readers.

**Comment by knoxcard** [comment]
This example should be put in the Sequelize docs, I couldn't find any other example of this particular situation online.  As a matter of fact, I found a lot of people posting about custom SQL builders to get over problems such as this!

**Comment by knoxcard** [comment]
Also, I converted my raw SQL back into this proper format.  Don't want a case of SQL injectionitus!

**Comment by TOMMY0809** [comment]
thanks a lot!
