### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by opichon** [sequelize/sequelize#9198]
## What are you doing?

```js
        AccessToken.destroy({ where: { userId: user.id } })
          .then(() => { return null } )
          .catch(err => {
            return done(err)
          })
```

## What do you expect to happen?
No warnings

## What is actually happening?

(node:78735) Warning: a promise was created in a handler at ... but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/node_modules/sequelize/node_modules/bluebird/js/release/method.js:29:9)

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.37.1
__Tested with latest release:__ No

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
```js
AccessToken.destroy({ where: { userId: user.id } })
   .then(() => { return null } )
   .catch(err => {
      return done(err)
    })
```

Your code is using `done`, Please include code that reproduce this warning.

It seems you are missing `done` in `then` callback

```js
AccessToken.destroy({ where: { userId: user.id } })
   .then(() => { return done() } )
   .catch(err => {
       return done(err)
   })
```
