### ISSUE TITLE
Update with nested associations

### ISSUE THREAD

**Issue by MikeDabrowski** [sequelize/sequelize#9199]
I think I dug deep enough (2016) and found only hints that such feature would be awesome to have but is not yet supported.

**What is current best way to update models with associations?** I understand it might be hard to implement, but I couldn't find in the docs how to do it on your own.

**Comment by amgv** [comment]
I think that feature isn't supported yet. you can fetch a row from any table and it will be a model instance, so if you include associated models  they will be model instances too. for example: 

`Student.find({
where: {age: 14},
include: [Classroom],}).
then((student) => {}) `

`student.Classroom` will be an instance of model Classroom and you can call `student.Classroom.save()` to update classroom. but calling `student.save() only update students atributes

**Comment by acanimal** [comment]
Maybe #9204 can help you

**Comment by sushantdhiman** [comment]
Duplicate of https://github.com/sequelize/sequelize/issues/9233

**Comment by papb** [comment]
This has been centralized in #11836
