### ISSUE TITLE
Seed and migrate in application code

### ISSUE THREAD

**Issue by milesalex** [sequelize/sequelize#9203]
How do I do rake style commands in my test file (Jest) with sequelize seeder files?

I'm trying to do the same thing as this, but with sequelize.

```
describe('routes : movies', () => {

  beforeEach(() => {
    return knex.migrate.rollback()
    .then(() => { return knex.migrate.latest(); })
    .then(() => { return knex.seed.run(); });
  });

  afterEach(() => {
    return knex.migrate.rollback();
  });


});```

**Comment by heisian** [comment]
Why would you post a question like this when the template specifically says to ask questions elsewhere? This is only for bug reports.

**Comment by sushantdhiman** [comment]
In my projects and mostly other projects which I have seen with Sequelize (even Sequelize tests itself) following approach works well

```js
describe('api', function() {
  beforeEach(function() {
    /** Either sync individual model or whole sequelize instance **/
    return db.sync({ force: true });
  });

  beforeEach(function() {
    /**Create any data you may need for your tests**/
    return db.Model.bulkCreate([/***/]);
  });

  after(function() {
    return db.sync({ force: true });
  });

  it('my assertions', function() { });
});
```

An example from Sequelize tests https://github.com/sequelize/sequelize/blob/master/test/integration/hooks/find.test.js

I hope you know what `sync` does, it basically create tables, constraints and indexes for defined models

- http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-method-sync
- http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-sync
