### ISSUE TITLE
Instance.build not refresh properties when save method has fields config.

### ISSUE THREAD

**Issue by sant123** [sequelize/sequelize#9207]
## What are you doing?

```js
const role = Role.build({ id: 7845, name: "Administrator", type: 1 })
info.save({ fields: ["name", "type"] })
```

## What do you expect to happen?
`role.id === [generated]`

## What is actually happening?
`role.id === 7845`

> INSERT INTO `roles` (`type`,`name`,`updated_at`,`created_at`) VALUES (2,'Administrator','2018-03-20 18:44:42','2018-03-20 18:44:42');

__Dialect:__ mysql
__Dialect version:__ 1.5.2
__Database version:__ 5.7.21
__Sequelize version:__ 4.37.3
__Tested with latest release:__ Yes

However the generated id is stored in the DB, but is not reflected in the property `id`.

**Comment by sushantdhiman** [comment]
Why are you supplying `primaryKey` and expect it to be refreshed, its the `primaryKey` that uniquely identify that record.

Just use

```js
Role.build({ name: "Administrator", type: 1 })
```
