### ISSUE TITLE
SQLite Array type

### ISSUE THREAD

**Issue by jaulz** [sequelize/sequelize#9209]
## What are you doing?
Do you think it's worth to introduce the array type to SQLite dialect as well? Though SQLite does not support arrays we could try to imitate it via JSON type. Please let me know if you would accept a pull request at all for this. Something like this:

```js
    function ARRAY() {
      if (!(this instanceof ARRAY)) {
        const obj = Object.create(ARRAY.prototype);
        ARRAY.apply(obj, arguments);
        return obj;
      }
      DataTypes.ARRAY.apply(this, arguments);
    }
    inherits(ARRAY, DataTypes.ARRAY);

    ARRAY.prototype.toSql = function toSql() {
      return 'JSON'
    };
    ARRAY.prototype._stringify = function _stringify(value, options) {
      return `${options.escape(JSON.stringify(value))}`;
    };
```

By the way, currently I add this new data type manually via `DataTypes.sqlite.ARRAY = ARRAY;`. Is that the recommended way?

## What do you expect to happen?
Simple array type in SQLite.

## What is actually happening?
SQL dump when using arrays: SequelizeDatabaseError: SQLITE_ERROR: near \"[]\": syntax error

_Output, either JSON or SQL_
```sql
CREATE TABLE IF NOT EXISTS `scopes` (
  `scope` VARCHAR(255)[] NOT NULL DEFAULT ARRAY[]::VARCHAR(255)[], 
  `userAlias` VARCHAR(255) NOT NULL REFERENCES `users` (`alias`) ON DELETE CASCADE
);
```

__Dialect:__ sqlite
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.37.2
__Tested with latest release:__ 4.37.2

**Comment by sushantdhiman** [comment]
I am reluctant to add this datatype as SQLite doesn't actually support array type. With array type you also get features like array of numbers, strings and thus engine level validations. For Postgres we even support Array(ENUM) which I dont think will work properly in SQLite.

Your patch looks OK, if it works for your case you can continue using it

**Comment by jaulz** [comment]
I understand your hesitation but shouldn't sequelize at least support some basic functionality and warn the user that certain features are not supported. There are already plenty of examples across the dialects:
https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/data-types.js#L128
https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/data-types.js#L336
https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/data-types.js#L157

Since we anyway reuse JSON type we already ensure on engine level that only valid arrays can be stored.

Thanks already for your feedback!

**Comment by papb** [comment]
If you are still willing to create this PR, with a thorough documentation description (not only in API Reference but also in the manual), I think that would be great!

**Comment by jaulz** [comment]
Great. I already use my workaround since a year and will start working on the PR next week.

**Comment by ephys** [comment]
As specified in https://github.com/sequelize/sequelize/pull/11259, we don't want to implement `DataTypes.ARRAY` for dialects that do not actually support arrays. Use `JSON` if you want to use JSON
