### ISSUE TITLE
Getter on id field not working?

### ISSUE THREAD

**Issue by lookapanda** [sequelize/sequelize#9217]
## What are you doing?
I added a `get()` to the `id` field of a model.

```js
id: {
        type: DataTypes.BIGINT,
        allowNull: false,
        primaryKey: true,
        get() {
            return `SomeModificationForDemonstration:${this.getDataValue(
                'id'
            )}`;
        },
    },
```

## What do you expect to happen?
I expected it to change the `id` in the result to `SomeModificationForDemonstration:<id>`

## What is actually happening?
It executed the `get()` function (added a console log into it) but in the Sequelize result, the `id` field remained unchanged.
It worked the way it was supposed to work for any other field.

__Dialect:__ mysql
__Dialect version:__ 
__Database version:__ AWS Aurora MySQL 5.7
__Sequelize version:__ ^4.33.2
__Tested with latest release:__ 4.37.4

**Comment by knoxcard** [comment]
Hmm..what if you do this?

```
get() {
   return 'SomeModificationForDemonstration:' + this.getDataValue('id')
},
```

**Comment by lookapanda** [comment]
@knoxcard It was just an example, and no, your example is invalid with my ESLint config. I was using template strings.

**Comment by knoxcard** [comment]
Nice, glad it worked out.  Going forward, it would have been helpful if you'd had included that additional information as well in the original post.  Thanks.

**Comment by lookapanda** [comment]
@knoxcard That is not what I meant. My original issue has not been resolved at all.

**Comment by sushantdhiman** [comment]
Seems to work on latest master

```js
const Model = sequelize.define('Model', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true,
    get() {
      return `MyId:${this.getDataValue('id')}`;
    }
  }
});

Model.sync({ force: true })
  .then(() => Model.create({}))
  .then(m => {
    console.log(m.toJSON());
    console.log(m.get('id'));
  });
```

```bash
{ id: 'MyId:1',
  updatedAt: 2018-04-02T07:20:07.026Z,
  createdAt: 2018-04-02T07:20:07.026Z }
MyId:1

```
