### ISSUE TITLE
Is there a way to close connection and be able to reconnect without exiting the process?

### ISSUE THREAD

**Issue by bertolo1988** [sequelize/sequelize#9220]
In my tests i want to be able to `await server.start()` and `await server.stop()` in start and end of each of my test suite independently. During this stop action we close every connection we establish in a graceful manner.

The reason behind this is because we need run this suites separately.

I noticed that Sequelize is not allowing me to do that because of the way `ConnectionManager.prototype.close` is written. From my understanding it expects me to close the process.

Could this be changed?

**Comment by sushantdhiman** [comment]
You should be able to use https://github.com/coopernurse/node-pool#draining on `sequelize.connectionManager.pool` if you are not using replication
