### ISSUE TITLE
The HasOne association support sourceKey option

### ISSUE THREAD

**Issue by flybluewolf** [sequelize/sequelize#9221]
I try change the code of  the HasOne association and support sourceKey option.
source file: has-one.js

old code:
`  this.sourceIdentifier = this.source.primaryKeyAttribute;
    this.sourceKey = this.source.primaryKeyAttribute;
    this.sourceKeyIsPrimary = this.sourceKey === this.source.primaryKeyAttribute;`

changed code:

`  this.sourceKey = this.options.sourceKey || this.source.primaryKeyAttribute;
    this.sourceIdentifier = this.sourceKey;
    this.sourceKeyIsPrimary = this.sourceKey === this.source.primaryKeyAttribute;`

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
