### ISSUE TITLE
Migration ERROR: Cannot add foreign key constraint

### ISSUE THREAD

**Issue by ajainvivek** [sequelize/sequelize#9224]
## What are you doing?
I am trying to set the foreign key constraint to the field but it always fails 

```js
module.exports = function (Sequelize) {
	return {
		id: {
			type: Sequelize.INTEGER,
			primary: true,
			autoincrement: true
		},
		name: {
			type: Sequelize.STRING,
			allowNull: false,
			unique: true
		},
		themeId: {
			type: Sequelize.INTEGER,
			allowNull: false,
			references: {
				model: {
					tableName: "theme",
					schema: "bloge"
				},
				key: "id",
				onUpdate: "cascade",
				onDelete: "cascade"
			}
		},
		updatedAt: Sequelize.DATE,
		createdAt: Sequelize.DATE
	}
}
```

## What do you expect to happen?
I wanted this to pass but fails

## What is actually happening?
```
== 20180323065742-create_site_template: migrating =======

ERROR: Cannot add foreign key constraint
```

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
