### ISSUE TITLE
Get last id, auto increment

### ISSUE THREAD

**Issue by dyankastutara** [sequelize/sequelize#9226]
Is there a way to get the last inserted ID, or actually, the id of the row inserted?

case, if the data in the table has filled 3 records. so it has id 1,2, and 3. but if create function is executed it will error, and not continue to be 4. and function will run again if it has tried to input 3 times. What's the solution?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by EmileCA** [comment]
@dyankastutara No, there is no way to do it in Sequelize out of the box. I am already looking for an alternative ORM library, but I have to refactor three sites. Which makes Sequelize legacy code :O

**Comment by amdp** [comment]
https://github.com/sequelize/sequelize/issues/5499#issuecomment-480528090
