### ISSUE TITLE
Unexpected deleting of associated records (possibly mutability issue)

### ISSUE THREAD

**Issue by Ajaxy** [sequelize/sequelize#9230]
## What are you doing?
I have a model *X* that _belongs to_ 3 other models with `{ foreignKey: { allowNull: false }, onDelete: 'cascade' }`:
```js
X.belongsTo(A, { foreignKey: { allowNull: false }, onDelete: 'cascade' });
X.belongsTo(B, { foreignKey: { allowNull: false }, onDelete: 'cascade' });
X.belongsTo(C, { foreignKey: { allowNull: false }, onDelete: 'cascade' });
```
And if I understand it right, it means that if one of the associated records is deleted, the *X*-record itself should be deleted. And it all worked well until I extracted this object of options into a constant to avoid code duplication and started using it as:
```js
const NOT_NULL = { foreignKey: { allowNull: false }, onDelete: 'cascade' };
X.belongsTo(A, NOT_NULL);
X.belongsTo(B, NOT_NULL);
X.belongsTo(C, NOT_NULL);
```
Then I realized that once I delete _X_-record, associated records from _A_, _B_ and _C_ **are also deleted**. As far as the obvious reason was extracting that common constant, I was able to fix it with _cloning_ it to avoid mutability:
```js
import { cloneDeep } from 'lodash';

const NOT_NULL = { foreignKey: { allowNull: false }, onDelete: 'cascade' };
X.belongsTo(A, cloneDeep(NOT_NULL));
X.belongsTo(B, cloneDeep(NOT_NULL));
X.belongsTo(C, cloneDeep(NOT_NULL));
```
This looks like a quite dangerous issue.

__Dialect:__ postgres
__Dialect version:__ pg@6.4.2
__Database version:__ postgres (PostgreSQL) 9.5.11
__Sequelize version:__ sequelize@3.32.1
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
v3 is no longer supported and will only receive security patches officially
