### ISSUE TITLE
Self reference not working in MSSQL

### ISSUE THREAD

**Issue by magyarb** [sequelize/sequelize#9238]
## What are you doing?
```js
db.HierTest = sequelize.define('HierTest', {
    name: {
        type: Sequelize.STRING,
        allowNull: true
    }
}, {
    freezeTableName: true,
    timestamps: false,
    paranoid: false
});

db.HierTest.belongsTo(db.HierTest, {as: 'parent'});
```

## What do you expect to happen?
_I wanted to create a self reference._

## What is actually happening?
_I get an error message in the MSSQL server:_

Introducing FOREIGN KEY constraint 'FK__HierTest__parent__4C364F0E' on table 'HierTest' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.

The code sequelize generates:

IF OBJECT_ID('[pult].[HierTest]', 'U') IS NULL CREATE TABLE [pult].[HierTest] ([id] INTEGER NOT NULL IDENTITY(1,1) , [name] NVARCHAR(255) NULL, [parentId] INTEGER NULL, PRIMARY KEY ([id]), FOREIGN KEY ([parentId]) REFERENCES [pult].[HierTest] ([id]) ON DELETE SET NULL);

The code that works (i think sequelize should generate this):

IF OBJECT_ID('[pult].[HierTest]', 'U') IS NULL CREATE TABLE [pult].[HierTest] ([id] INTEGER NOT NULL IDENTITY(1,1) , [name] NVARCHAR(255) NULL, [parentId] INTEGER NULL, PRIMARY KEY ([id]), FOREIGN KEY ([parentId]) REFERENCES [pult].[HierTest] ([id]) ON DELETE NO ACTION);

__Dialect:__ mssql
__Dialect version:__ ?
__Database version:__ 14.0.1000
__Sequelize version:__ 4.37.4
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
When defining association you can pass `onDelete`

```js
db.HierTest.belongsTo(db.HierTest, {as: 'parent', onDelete: 'NO ACTION' });
```

**Comment by magyarb** [comment]
Thanks for the help. Maybe NO ACTION should be the default when creating self references with this dialect, but this is an easy workaround.
