### ISSUE TITLE
Declaring references and associations such as belongsTo duplicates the column names

### ISSUE THREAD

**Issue by leolorenzoluis** [sequelize/sequelize#9244]
## What are you doing?

If a model definition has a reference declare such as: (The rest of the model definition are omitted)
```
roleId: { 
           field: 'ROLE_ID'
           references: {
               model: 'ROLE',
               key: 'ROLE_ID',
          }
``` 

with references declared and another declaration such as `user.belongsTo(Role, { foreignKey: 'ROLE_ID' });` and MS SQL Triggers are on for the Users table

and we simply call `User.create(newUser);`. 

## What do you expect to happen?
I want to either raise an exception that I'm doing something horribly wrong or really why is there a duplicate in the first place?

## What is actually happening?
The generated temporary table duplicates the column name `ROLE_ID`.

__Dialect:__ mysql
__Dialect version:__ latest
__Database version:__ MS SQL Server 2012
__Sequelize version:__ 4.33.4
__Tested with latest release:__ Yes (If yes, specify that version)

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by leolorenzoluis** [comment]
Lol. I assume you didn't fully read my expectations. It is a bug because it's generating multiple column names. O well.
