### ISSUE TITLE
Nulls, auto increment values and validation

### ISSUE THREAD

**Issue by runk** [sequelize/sequelize#925]
I'm working with postgres and sequelize `v1.7.0`. Is there any other way to use autoincrement fields rather than setting `omitNull` to `true` in config? 

The problem is that I need to be able to set some values to null, but when `omitNull` enabled these values skipped from update queries.

Thoughts?

**Comment by jbarros35** [comment]
No, you guys made a serious mistake.
The issue still remains.

POST /quote/ 200 29.353 ms - 42
Executing (default): INSERT INTO "quotes" ("author","message") VALUES ('join','h
i') RETURNING *;
Unhandled rejection SequelizeDatabaseError: el valor null para la columna «id» v
iola la restricción not null
    at Query.formatError (C:\Users\jlopesde\node\myapp\template\template\node_mo
dules\sequelize\lib\dialects\postgres\query.js:420:14)
    at null.<anonymous> (C:\Users\jlopesde\node\myapp\template\template\node_mod
ules\sequelize\lib\dialects\postgres\query.js:104:19)
    at emit (events.js:95:17)
    at Query.handleError (C:\Users\jlopesde\node\myapp\template\template\node_mo
dules\pg\lib\query.js:99:8)
    at null.<anonymous> (C:\Users\jlopesde\node\myapp\template\template\node_mod
ules\pg\lib\client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (C:\Users\jlopesde\node\myapp\template\template\node_m
odules\pg\lib\connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)

**Comment by mickhansen** [comment]
@jbarros35 You'd have to be more specific to this serious mistake. You haven't even shown your model definition, but apparently your id column is improperly setup.

**Comment by janmeier** [comment]
@jbarros35 Please provide some more context - model definitions, function calls, sequelize version and an error message in english - We have _nothing_ to go on from what you just posted.

Please post it in a new issue - You can reference old issues, but its hard for us to keep track of bug reports in closed issues. Please read [contributing.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md) before posting

**Comment by aray12** [comment]
So I was just having the same problem and realized I was declaring autoIncrement prior to primaryKey

```
id: {
    type:Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true
}
```

When I switched those it worked

```
id: {
    type:Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true
}
```

I could be way off base but it is defining it using SERIAL. SERIAL only works at table creation and is simply a shortcut for declaring a sequence. If the underlying process only has the ability to use SERIAL, using autoIncrement without dropping the table will fail.

Hope this helps someone

**Comment by brain64bit** [comment]
+1 
I am still experiencing with this problem, here my snippet of model definition:

```
var Job = Connection.getDatabase().define('Job', {
  id:          { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
  message:  { type: Sequelize.STRING, defaultValue: null },
  status:      { type: Sequelize.STRING, defaultValue: StatusCodes.PROCESSING },
  progress:    { type: Sequelize.FLOAT, defaultValue: 0.0 }
}
```

But when i try to recreate the database and rerun the migration, i am not getting the error anymore.

**Comment by janmeier** [comment]
@brain64bit What error? Is this related to `.sync` or to migrations?

**Comment by brain64bit** [comment]
@janmeier the error thrown when i try to save the object,

here my snippet:
```javascript
var job = Job.build({ message: "lorem ipsum", status: "created", progress: 0 });
job.save().success(successCallback).error(function(error){
   logger.error(error.stack);
});
```
because i am still in development process, currently my workaround just dropdb and create again. I am using Postgresql 9.3

**Comment by janmeier** [comment]
@brain64bit And what error are you getting :) ?

**Comment by brain64bit** [comment]
Oh ya sorry, it seem because sequelize explicitly set the id with null:

```
error: null value in column "id" violates not-null constraint
    at Connection.parseE (/project/path/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/project/path/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/project/path/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
```

And from PostgreSQL log  file:
```
ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, lorem ipsum, created, 0).
STATEMENT:  INSERT INTO "Jobs" ("id","message","status","progress") VALUES (NULL, 'lorem ipsum', 'created', 0) RETURNING *;
```

**Comment by janmeier** [comment]
The example you posted works fine for me 

```sql
 INSERT INTO "jobs" ("id","message","status","progress") VALUES (DEFAULT,'lorem ipsum','created',0) RETURNING *;
```

Can you create a full self-contained example, or perhaps a pull request with a failing test?

And if you can - please do so in a new issue :)
