### ISSUE TITLE
Upsert try to update first instead of creating and throwing an exception

### ISSUE THREAD

**Issue by evangow** [sequelize/sequelize#9251]
previously at: https://github.com/sequelize/sequelize/issues/5711

## What are you doing?
```javascript
const test = sequelize.define('test', {
    id: {
        primaryKey: true,
        type: Sequelize.INTEGER.UNSIGNED,
        field: 'my_id'
    },
    val1: {
        type: Sequelize.STRING(36),
        allowNull: false,
        field: 'value_1'
    },
    val2: {
        type: Sequelize.STRING(36),
        allowNull: false,
        field: 'value_2'
    }
});
test.sync().then(function () {
    test.upsert({
        id: 1,
        val1: 'hello',
        val2: 'world'
    }).then(function () {

        // I was expecting this to partially update the row
        test.upsert({
            id: 1,
            val2: 'world222222'
        }).then(function () {
            console.log('Expected')
        }).catch(function (err) {
            // That's what really happens
            console.error(err);
        });
    });
});
```

## What do you expect to happen?
val2 should be updated

## What is actually happening?
throwing a 'SequelizeDatabaseError: null value in column "val1" violates not-null constraint' error

## Suggested fix
As can be seen in the function generated for the upsert below. It first tries to insert the values and if it throws a unique_violation exception, then it will try updating that row.

However, if there is a not_null constraint on one of the columns not being updated, then that column with throw a not_null exception before the unique_violation exception is thrown

```javascript
CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $func$ BEGIN INSERT INTO table(columns) VALUES(...); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE SET ...; RETURN 2; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
```

I think the plpgsql should instead try updating a row and if it doesn't exist, then it should create it.

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.37.4
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Thanks for pointing to old issue, I have reopened it. As most of discussion is already there, I am closing this new one
