### ISSUE TITLE
suggestion: just put model field to instance, NOT by get/set method

### ISSUE THREAD

**Issue by guotie** [sequelize/sequelize#9253]
sometimes, I have Sequelize instance, then, I should use get/set to get or set model field; sometimes, some function return toJSON() object, then, I should get or set field directly.

so, when a function return Sequelize instance and I use the model field directly, those bug is **very** difficult to find.

I suggest the model field directly put in Sequelize instance

**Comment by sushantdhiman** [comment]
Actual data is under `dataValues` and there is also old data storage `prevDataValues`, this allow us to separate and compare old and new data, which provide tracking of what data is changed. I dont see a good way to replicate this using attribute keys directly on instance.

I am interested in what **bug** you encountered when using direct key access opposed to using getters, which I see could be a problem with custom getters but should be ok for most cases
