### ISSUE TITLE
bulkCreate does not populate dataValues correctly

### ISSUE THREAD

**Issue by kaxelson** [sequelize/sequelize#9274]
## What are you doing?
When calling bulkCreate:

## What do you expect to happen?
I expect it to populate the dataValues like save does:

https://github.com/sequelize/sequelize/blob/07092263753f79194d76669e805865420ca584de/lib/model.js#L3722

## What is actually happening?
bulkCreate incorrectly invokes the set function when populating the model's dataValues:

https://github.com/sequelize/sequelize/blob/07092263753f79194d76669e805865420ca584de/lib/model.js#L2462

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
@sequelize/orm anyone remember why we do that for `bulkCreate`

**Comment by janmeier** [comment]
Nope, I don't recall why we would want to do that

**Comment by sushantdhiman** [comment]
Fixed by #9797
