### ISSUE TITLE
When I am using findAll and include I get error “cannot read property ‘table_name’ of undefined”. 

### ISSUE THREAD

**Issue by hsallabas** [sequelize/sequelize#9277]
## What are you doing?
When I am using findAll and include I get error “cannot read property ‘table_name’ of undefined”. I am not getting errors in different eager loading API it is not stable. It's a bug and it's been talked about solved, but it's still going on. I try solve the problem a long time but I can’t. Please help me. Good day Thanks.

```js
router.get('/preRegClasses/test5', function (req, res) {
    console.log(db.pRegs)
    db.schools.findAll({
        attributes: ['id'],
        include: [{
            model: db.years,
            attributes: ['id'],
            include: [{
                model: db.pClasses,
                attributes: [],
                include: [{
                    model: db.pRegs,
                    attributes: ['reserve_order'],
                    include: [{
                        model: db.pStudents,
                        attributes: ['name', 'surname', 'id_number', 'call_priority'],
                        include: [{
                            model: db.pParents,
                            attributes: ['name', 'surname', 'parent_type'],
                        },
                        {
                            model: db.pSiblings,
                            attributes: [],
                        }]
                    }]
                }]
            }]
        }]
    }).then(function (result) {
        res.send(result);
        console.log(result);
    }).catch(function (error) {
        res.send(error)
        console.log(error);
    });
});
```

I HAVE ERROR
![error1](https://user-images.githubusercontent.com/35194503/38454726-fa655eb2-3a74-11e8-93cf-51c4b359f682.PNG)

Dialect: postgres 
Dialect version: 9.6
Database version: 9.6
Sequelize version: 4.37.5

**Comment by sushantdhiman** [comment]
**change**

```js
model: db.pClasses,
attributes: [],
```

**to this**
```js
model: db.pClasses,
attributes: ['id'],
````

This is fixed by latest commit on master but not relased yet

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by hsallabas** [comment]
thanks for helps I will consider your suggestions the open issue
