### ISSUE TITLE
Include/nested grouping produces unknown column

### ISSUE THREAD

**Issue by icarusmiles** [sequelize/sequelize#9279]
## What are you doing?
I have a query built with a limit and offset that fetches products and the corresponding latest prices for each source. In order to fetch unique prices per product I have to use `GROUP BY`. Unfortunately `GROUP BY` is not able to fetch the column and produces `Unknown column 'prices.unique' in 'group statement'`. 

```js
models.products.findAll({
  where: Sequelize.where(Sequelize.fn('CONCAT_WS', ' ', Sequelize.col('brand'), Sequelize.col('name')),{ $like: `%${searchQuery}%`}),
  limit: limit,
  offset: offset,
  order: [
    [Sequelize.fn('CONCAT_WS', ' ', Sequelize.col('brand'), Sequelize.col('name'))]
  ],
  include: [{
    model: models.prices,
    attributes: [
      [Sequelize.fn('CONCAT', Sequelize.col('prices.productId'), '-', Sequelize.col('prices.sourceId')), 'unique']
    ]
  }],
  group: [Sequelize.literal('`prices.unique`')]
});
```

## What do you expect to happen?
Not exactly "expect", but required for this query to work.  The `GROUP BY` needs to end up inside of the `LEFT OUTER JOIN`

The query below is fully functional:

```
SELECT 
    `products`.*,
    `prices`.`id` AS `prices.id`,
    CONCAT(`prices`.`productId`,
            '-',
            `prices`.`sourceId`) AS `prices.unique`
FROM
    (SELECT 
        `products`.`id`,
            `products`.`type`,
            `products`.`name`,
            `products`.`brand`,
            `products`.`sku`,
            `products`.`upc`,
            `products`.`model`,
            `products`.`description`,
            `products`.`createdAt`,
            `products`.`updatedAt`
    FROM
        `products` AS `products`
    WHERE
        CONCAT_WS(' ', `brand`, `name`) LIKE '%50mm%'
	
    ORDER BY CONCAT_WS(' ', `brand`, `name`)
    LIMIT 0 , 12) AS `products`
        LEFT OUTER JOIN
    `prices` AS `prices` ON `products`.`id` = `prices`.`productId`
    GROUP BY `prices.unique`
ORDER BY CONCAT_WS(' ', `brand`, `name`);
```

## What is actually happening?
The `GROUP BY` ends up under the `WHERE`  statement, causing the query to throw `Unknown column 'prices.unique' in 'group statement'`. Placing the `group:` inside the `include:` is not supported and causes the query to ignore the group statement entirely.

```
SELECT
    `products`.*,
    `prices`.`id` AS `prices.id`,
    CONCAT(`prices`.`productId`,
            '-',
            `prices`.`sourceId`) AS `prices.unique`
FROM
    (SELECT
        `products`.`id`,
            `products`.`type`,
            `products`.`name`,
            `products`.`brand`,
            `products`.`sku`,
            `products`.`upc`,
            `products`.`model`,
            `products`.`description`,
            `products`.`createdAt`,
            `products`.`updatedAt`
    FROM
        `products` AS `products`
    WHERE
        CONCAT_WS(' ', `brand`, `name`) LIKE '%50mm%'
        GROUP BY `prices.unique`
    ORDER BY CONCAT_WS(' ', `brand`, `name`)
    LIMIT 0 , 12) AS `products`
        LEFT OUTER JOIN
    `prices` AS `prices` ON `products`.`id` = `prices`.`productId`
ORDER BY CONCAT_WS(' ', `brand`, `name`);
```

__Dialect:__ mysql
__Dialect version:__ 5.7.18
__Database version:__ 5.7.18
__Sequelize version:__ 4.37.6
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Can you try with ```group: [Sequelize.literal('`prices`.`unique`')]```

**Comment by miles-collier** [comment]
Thanks for the suggestion @sushantdhiman, same result.

**Comment by sushantdhiman** [comment]
Can you submit a SSCCE so i can take a look

**Comment by miles-collier** [comment]
@sushantdhiman Sorry, but I don't have the time to do any major diagnosis/isolation. I barely have time to program this project with my free-time.  :(

So there is no way to place/move group by as in this example: https://i.imgur.com/rSPeUof.png
This would be a great feature, I read countless Google results and every document Sequelize has pertaining grouping and includes.

**Comment by King-Success** [comment]
Currently having this issue, happen to have a solution yet?
