### ISSUE TITLE
Problem with many to many queries

### ISSUE THREAD

**Issue by shererere** [sequelize/sequelize#9283]
Hello everyone. I'm struggling to perform queries that use many-to-many associations. I made following relations: 

```
db.quizzes.belongsToMany(db.questions, {
  through: {
    model: db.quizzes_questions,
  },
});

db.questions.belongsToMany(db.quizzes, {
  through: {
    model: db.quizzes_questions,
  },
});
```

Later, i made a query:
```
  db.questions.findAll({
    include: [{
      model: db.quizzes,
      where: {
        id: req.params.quiz,
      },
      attributes: ['id'],
    }],
  })
```

And my output is:
![image](https://user-images.githubusercontent.com/22204457/38511978-250df9c4-3c2a-11e8-9b7a-786363ce8b9f.png)

As you can see, it prints whole question info, quizzes that it is related with, and data from 'connecting table'. I just want to get data from 'questions' and its id from 'quizzes_questions'. In sql, It would look like: 
```
SELECT questions.*, quizzes_questions.id as qqID FROM questions, quizzes_questions WHERE questions.id = quizzes_questions.question_id AND quizzes_questions.quiz_id = GIVEN_ID;
```
However, I have no idea how to do that is Sequelize.

**Comment by sushantdhiman** [comment]
Have you tried setting `attributes` on `through`

```js
  db.questions.findAll({
    include: [{
      model: db.quizzes,
      through: {
        attributes: []
      },
      where: {
        id: req.params.quiz,
      },
      attributes: ['id'],
    }],
  })
```

**Comment by shererere** [comment]
```
db.questions.findAll({
    include: [{
      model: db.quizzes,
      through: {
        attributes: ['id'],
      },
      where: {
        id: req.params.quiz,
      },
      attributes: ['id'],
    }],
  })
```
![image](https://user-images.githubusercontent.com/22204457/38566629-6cd4b3b4-3ce4-11e8-85b7-77f9de17ce70.png)

Not quite what i meant. Guess that will be easier to understand from a drawing.
![image](https://user-images.githubusercontent.com/22204457/38567345-387c53a4-3ce6-11e8-8abf-4114500aa111.png)

**Comment by sushantdhiman** [comment]
Have you tried including that column in main `attributes`?

**Comment by shererere** [comment]
How do i do that, when it is another's table column?

**Comment by sushantdhiman** [comment]
something like `sequelize.literal('include_table.through_table.my_col')`

**Comment by shererere** [comment]
```
  db.questions.findAll({
    attributes: [
      [db.sequelize.literal('quizzes.quizzes_questions.id'), 'second_id'],
    ],
    include: [{
      model: db.quizzes,
      through: {
        model: db.quizzes_questions,
      },
      where: {
        id: req.params.quiz,
      },
    }],
  })
```
Do you mean like that? It fails with "Unknown column 'quizzes.quizzes_questions.id' in 'field list'", Sorry for being really dumb right now but seriously I have no clue

**Comment by heisian** [comment]
Why don't you use a `DataTypes.VIRTUAL` for this?

```node
// Where ever the model definition is...
  ...
  somethings: {
    type: DataTypes.VIRTUAL,
    defaultScope: true,
    get() {
      if (this.quizzes_questions) {
        return this.quizzes_questions.map(qq => qq.id)
      }
    }
  }
  ...
```

**Comment by allicanseenow** [comment]
Is there a specific answer to this issue?
