### ISSUE TITLE
Postgres: TimeoutError/SequelizeConnectionError until node restart

### ISSUE THREAD

**Issue by cavinsmith** [sequelize/sequelize#9286]
Hi! I have issues using Sequelize with Postgres on Azure.

At the random moment (after 3, 5, 10 days of normal use) all SQL queries using PostgreSQL are starting to serve pool error `TimeoutError: ResourceRequest timed out at ResourceRequest._fireTimeout (/generic-pool/lib/ResourceRequest.js:62:17)` and sequelize `SequelizeConnectionError: Connection terminated unexpectedly
at connection.connect.err (/sequelize/lib/dialects/postgres/connection-manager.js:132:20)`

I guess problem starts with SQL server connection problem (but I have no proofs) but  is not handled and is freezing service until node restart. If I will not restart node - it will capture this errors forever.

My db settings:
```js
{
    dialect: 'postgres',
    pool: {
      max: 5,
      min: 0,
      idle: 10000,
    },
    dialectOptions: {
      ssl: true,
    },
    operatorsAliases: false,
}
```

As a DB server I'm using PostgreSQL server provided by Azure. The only logs that are corresponding to this situation look like `could not receive data from client: An existing connection was forcibly closed by the remote host.` and this logs are not shown anymore after node restart

My current workaround is process.exit() when receiving error `TimeoutError` or `SequelizeConnectionError` which is not the best of course(

__Dialect:__ postgres
__Dialect version:__ pg@7.4.1
__Database version:__ PostgreSQL 9.6.7, compiled by Visual C++ build 1800, 64-bit (Azure Postgres server)
__Sequelize version:__ 4.37.5
__Tested with latest release:__ 4.37.5

UPDATE:

On development server (same versions, with own 9.6 Postgres) tried stopping postgres, trying requests to running node app and then starting postgres and trying node requests again. 

Result: errors while postgres is down: `SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432` and immediate reconnection when postgres is up.

This means that source of problem is not connection drop itself, but something else.

**Comment by heisian** [comment]
What is your `max_connections` setting in your postgres config? This can happen if your clients are trying to open too many concurrent connections. The postgres server will drop or not respond once `max_connections` is exceeded.

**Comment by cavinsmith** [comment]
@heisian first of all i need to mention that my postgres server has only two clients - it's pool of that node.js app (hosted on azure) and development app connection from my local machine.

Local connection has no problems when production one has as long as any postgres client.

Another thing is that postgres logs has no errors except `could not receive data from client: An existing connection was forcibly closed by the remote host.` or any signs of more then 1-2 connections at a time which doesn't look like `max_connections` problem

P.S. I'm using very basic Azure Postgres  with 50 maximum connections. 
P.P.S. I will try to simulate "too many connections" anyway to check your suggestion.

**Comment by heisian** [comment]
Yeah, check what queries are being run and how long they're taking at a granular level first. AFAIK Postgres can handle a **lot**.. easily process 10K+ read/writes on a mediocre box in a few minutes.

**Comment by rasjani** [comment]
Ended up into this issue from google. Im also  having somewhat similar issues with Sequalize but with Aurora & mysql. 

If and when i come up with some findings and they fit here, i'll drop more info.

**Comment by cavinsmith** [comment]
@rasjani yesterday moved to another postgresql server and everything is now even worse! Received 3 problems in 3 hours

**Comment by cavinsmith** [comment]
@bsenyk what is you `pg` version you're using with `sequelize`?

**Comment by bsenyk** [comment]
@cavinsmith I'm on `sequelize` 4.37.6 and `pg` 7.4.1

**Comment by cavinsmith** [comment]
@bsenyk my next step will be downgrading to `pg@6`, there were no problems with 6 for me

**Comment by cavinsmith** [comment]
Really interesting results:
1) I made cluster of two independent backend processes running on same db
2) Instances were started with 20s difference
3) They received errors at same time, so it looks like db issue, not `pg` driver or `sequelize` itself? Nope! I received bunch of this errors during several days and...
4) I downgraded `pg@7` driver to `pg@6` and... no errors during last 5 days.
5) What to do next?

**Comment by milesalex** [comment]
Same here :(

**Comment by cavinsmith** [comment]
@milesalex @ricardopolo @bsenyk @rasjani 
I was investigating phenomena with Azure support for month now.

What I see now:

1) This is mostly not problem of Sequelize or driver or something.

2) When problem happens, entire database freezes for 20-120 seconds and all existing connections and queries are working, but will respond only after downtime. So if you have 200 seconds tiemout for example - you'll receive results in 200 seconds. Not only using Sequelize but any other client including binary.

3) Problem is still not solved and there are no clues of what is causing it. It can happen 10 times per day or hide for two weeks, it's not connected to your db activity anyhow and not connected with specific requests, pool size, etc.

4) For Azure it was not connected with region (I used db in Singapore and US with same problems)

5) Local db (using ssl+password) is absolutely ok (yep, I moved to local db)

6) My db was only 2mb size, so size is also not a problem.

**Comment by cavinsmith** [comment]
Actually Azure is now fixing problem in Postgres. Problem is not connected with Sequelize and I can say that Sequelize reacts to it normally, this thread could be closed.

**Comment by pm-trey** [comment]
> I'm seeing a similar issue using sequelize with AWS Aurora postgresql 9.6. I'm running my service on ECS on around 30 docker containers. Basically, after a few days of running, one of the containers will start timing out on every single request to the db until I shut it down and start a new container.
> 
> Here are my pool settings:
> 
> ```
> pool: {
>       max: 2,
>       min: 1,
>       idle: 10000
>     }
> ```
> 
> I set the min connections to 1 to try to fix this problem, but it doesn't appear to have had an impact.

Had my minimum connection count set to 0.
