### ISSUE TITLE
`updateOnDuplicate` problem when set to true.

### ISSUE THREAD

**Issue by aasmm7x** [sequelize/sequelize#9288]
Looking the code of `updateOnDuplicate` looks like we can set an array of fields or a boolean . If we pass a boolean `true`, the bulkCreate tries to update the primary key field as well, trowing an `SequelizeForeignKeyConstraintError SequelizeForeignKeyConstraintError: Cannot delete or update a parent row` error.

Code: https://github.com/sequelize/sequelize/blob/66fb6b67a74c107bfaf72304db315bf600c37921/lib/model.js#L2348`

**Comment by sushantdhiman** [comment]
I will remove boolean support and just keep array option as docs say

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/commit/8b937dd7a44ba946f7004a30db3d62c98fcb332a
