### ISSUE TITLE
Sequelize raw query does not returns  the exact result from the Postgres DB

### ISSUE THREAD

**Issue by shajunr88** [sequelize/sequelize#9291]
## What are you doing?
I have a sequelize raw query to select some values from the database.But when running the query in postgres ie generated by sequelize gives 2 rows and in sequelize output ,it returns only 1 row.

```js
const db = require('../models');
const invoices = await db.sequelize.query("SELECT invoice_amount, bill_period_from, bill_period_to FROM invoices  WHERE invoices.user_id="+user_id+" and date_part('year', bill_period_from) = date_part('year', current_date) order by bill_period_from", { type: db.sequelize.QueryTypes.SELECT});
Query from the console
SELECT invoice_amount, bill_period_from, bill_period_to FROM invoices  WHERE invoices.user_id=112 and date_part('year', bill_period_from) = date_part('year', current_date) order by bill_period_from
```

## What do you expect to happen?
Output from Postgres DB has two rows but from the sequelize it has only one row

## What is actually happening?
output from the console
[ { invoice_amount: '120.000',
    bill_period_from: 2018-01-31T18:30:00.000Z,
    bill_period_to: 2018-02-27T18:30:00.000Z } ]

output from the DB
300.000;"2018-01-01 00:00:00+05:30";"2018-01-31 00:00:00+05:30"
120.000;"2018-02-01 00:00:00+05:30";"2018-02-28 00:00:00+05:30"

__Dialect:__ postgres 
__Dialect version:__ XXX
__Database version:9.5
__Sequelize version:3.0.0
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Sorry we don't support v3 now

Have you tried with `QueryType.RAW` ?

**Comment by shajunr88** [comment]
QueryTypes.RAW also gives only one record
[ [ anonymous {
      invoice_amount: '120.000',
      bill_period_from: 2018-01-31T18:30:00.000Z,
      bill_period_to: 2018-02-27T18:30:00.000Z } ],
  Result {
    command: 'SELECT',
    rowCount: 1,
    oid: null,
    rows: [ [Object] ],
    fields: [ [Object], [Object], [Object] ],
    _parsers: [ [Function], [Function: parseDate], [Function: parseDate] ],
    RowCtor: [Function: anonymous],
    rowAsArray: false,
    _getTypeParser: [Function: bound ] } ]

**Comment by sushantdhiman** [comment]
Try printing this sql query and then execute it directly on postgres client, see if you get two rows there, looks like your query is only selecting one row actually

**Comment by shajunr88** [comment]
https://stackoverflow.com/questions/49796983/sequelize-raw-query-does-not-returns-the-exact-result-from-the-postgres-db
![seqelize_output](https://user-images.githubusercontent.com/21968310/38678602-0ba8f960-3e51-11e8-9fe8-a925a525db25.png)
![invoices_table_structure](https://user-images.githubusercontent.com/21968310/38678735-67d63202-3e51-11e8-96f5-0ec589248fa6.png)
![query_otput](https://user-images.githubusercontent.com/21968310/38678771-86c209f2-3e51-11e8-9738-dbad36edca65.png)

**Comment by may215** [comment]
I am facing the same issue, return only the first row of the results, and return the query text, very weird ....

**Comment by skk2142** [comment]
Has this issue been resolved?

**Comment by sushantdhiman** [comment]
Reproduce before resolve :D

**Comment by thallesrv** [comment]
Has this issue been resolved?

**Comment by thallesrv** [comment]
> Has this issue been resolved?

Has this issue been resolved?

**Comment by thallesrv** [comment]
> ## What are you doing?
> I have a sequelize raw query to select some values from the database.But when running the query in postgres ie generated by sequelize gives 2 rows and in sequelize output ,it returns only 1 row.
> 
> ```js
> const db = require('../models');
> const invoices = await db.sequelize.query("SELECT invoice_amount, bill_period_from, bill_period_to FROM invoices  WHERE invoices.user_id="+user_id+" and date_part('year', bill_period_from) = date_part('year', current_date) order by bill_period_from", { type: db.sequelize.QueryTypes.SELECT});
> Query from the console
> SELECT invoice_amount, bill_period_from, bill_period_to FROM invoices  WHERE invoices.user_id=112 and date_part('year', bill_period_from) = date_part('year', current_date) order by bill_period_from
> ```
> 
> ## What do you expect to happen?
> Output from Postgres DB has two rows but from the sequelize it has only one row
> 
> ## What is actually happening?
> output from the console
> [ { invoice_amount: '120.000',
> bill_period_from: 2018-01-31T18:30:00.000Z,
> bill_period_to: 2018-02-27T18:30:00.000Z } ]
> 
> output from the DB
> 300.000;"2018-01-01 00:00:00+05:30";"2018-01-31 00:00:00+05:30"
> 120.000;"2018-02-01 00:00:00+05:30";"2018-02-28 00:00:00+05:30"
> 
> **Dialect:** postgres
> **Dialect version:** XXX
> __Database version:9.5
> __Sequelize version:3.0.0
> **Tested with latest release:** No (If yes, specify that version)
> 
> **Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

Has this issue been resolved?

**Comment by Gautam17** [comment]
I'm facing a similar issue, any solution?

**Comment by tejashwikalptaru** [comment]
Any solution so far? I am also facing this issue, the query generated by Sequelize is fine, and I manually run the query in Postgres, it provides the correct rows (total 16), but the rows provided by Sequelize is only 15

**Comment by singulart** [comment]
Facing the same issue.

**Comment by navigantcase** [comment]
Same here in my case. When will this be fixed?

**Comment by ephys** [comment]
Please open a new bug report with a reproducible example. This bug report is from Sequelize 3 which is 8 years old
