### ISSUE TITLE
Foreign Key relations are not being created but query logging has the feilds

### ISSUE THREAD

**Issue by Swati020494** [sequelize/sequelize#9293]
```javascript
let database=require('../../config/db')
let sequelize=database.sequelize
let connection=database.connection

let init = function(){
    return curriculum = connection.define('curriculum',{
        id : {
            type:sequelize.INTEGER,
            primaryKey:true,
            autoIncrement:true
        },
        name : {
            type:sequelize.STRING,
            allowNull:false,
        },
        status : {
            type : sequelize.BOOLEAN,
            allowNull: false,
            defaultValue : true
        },
        frozen : {
            type : sequelize.BOOLEAN,
            allowNull: false,
            defaultValue : false
        }
    },{
        classMethods:{
            associate:function(model){
                let curriculum = model.curriculum
                let department = model.department
                let academicYear = model.academic_year
                let semester = model.semester
                curriculum.findAll()
                .then((values) => {
                }).catch((error) => {
                    console.log("Error, Inside getAllCuriculum catch: ", error);
                });
                curriculum.belongsTo(department,{
                    foreignKey:"department_id"
                });
                curriculum.belongsTo(academicYear,{
                    foreignKey:"academic_year_id"
                });
                curriculum.belongsTo(semester,{
                    foreignKey:"semester_id"
                });
            }
        }
    })
}
module.exports=init
```
In the above code:
1. Associations(foreign key relations) are not getting created
2. curriculum.findAll is written to check the fields that are being create and the query is logged
````javascript
('SELECT "id", "name", "status", "frozen", "created_at", "updated_at", "department_id", "academic_year_id", "semester_id" FROM "curriculum" AS "curriculum";' })
````
3. it gives the following error:
>{ error: column "department_id" does not exist
    at Connection.parseE (/Users/cronj/Documents/student-management-system-web/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/cronj/Documents/student-management-system-web/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/cronj/Documents/student-management-system-web/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     name: 'error',
     length: 113,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '70',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3293',
     routine: 'errorMissingColumn',
     sql: 'SELECT "id", "name", "status", "frozen", "created_at", "updated_at", "department_id", "academic_year_id", "semester_id" FROM "curriculum" AS "curriculum";' },

#### 2. How is the query being fired correctly

**Comment by sushantdhiman** [comment]
Looks like you are using v3, unfortunately we do not support it any more.

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
