### ISSUE TITLE
Running sequelize:seed for Postgres with autoIncrement key breaks SERIAL data type in tables

### ISSUE THREAD

**Issue by Darmikon** [sequelize/sequelize#9295]
## What are you doing?
I'm trying to use migrations to create tables with autoIncrement key in Postgres
It is said here
http://docs.sequelizejs.com/manual/advanced/legacy.html
that adding `autoIncrement: true` // Automatically gets converted to SERIAL for postgres

// my migration
```
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Books', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      ...
```

// my model
```
let Book = sequelize.define(
    'Book', {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
	  ...
```
// run command	  
`sequelize:migrate`

// on server I run
```
Book.create({title: 'title', author: 'author'});
```
## What do you expect to happen?
I expect that new book is added to database

## What is actually happening?
But I see an error:
`duplicate key value violates unique constraint \"Books_pkey\""`

However without sequelize migrations database works without problems.
```
CREATE TABLE "Books" (
	id     SERIAL PRIMARY KEY,
	title  VARCHAR(100) NOT NULL,
	author VARCHAR(100) NULL
);

--I can insert without problems
INSERT INTO "Books" (id, title, author) VALUES (DEFAULT, 'title', 'author');
INSERT INTO "Books" (id, title, author) VALUES (DEFAULT, 'title', 'author');
```

__Dialect:__ postgres
__Dialect version:__ 10.3.0
__Database version:__ 10.3.0
__Sequelize version:__ 4.37.5
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by Darmikon** [comment]
Addition: it stops working after using `sequelize:seed` to insert several lines to table. Is any way to sync somehow sequelize models with latest id in table?

**Comment by Cuxs** [comment]
Same happens to me, after I seed data from a previous existing database. When I try to add a new record the error:
```sql
ERROR:  duplicate key value violates unique constraint "ImageGroups_pkey"
DETAIL:  Key (id)=(15) already exists.
```
appears.

**Comment by heisian** [comment]
You do NOT need to add the `id` attribute to your model definition.

Do it like this:

```node
let Book = sequelize.define('Book', {
  /*
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  */

  ...myAttributes,
}
```

**Comment by Darmikon** [comment]
@heisian I wouldn't say it's expected behavior. And as I said it stops working only if `sequelize:seed` was executed. Without `sequelize:seed` everything works fine with this model definition

**Comment by lukeed** [comment]
Confirmed. Running any seeding operation with `id` values included in the seed data will break Sequelize. 

I've tried with `items.map(o => User.create(o)`, `User.bulkCreate(items)`, `... { individualHooks:true }` and `Q.bulkInsert('users', items)`. The data is entered fine, but Sequelize totally "loses track" of how many items there are in the database, so any new inserts or updates will throw the error @Darmikon mentioned.

Worth noting that the `id` Sequelize wants to use is always wrong. It also varies. It can be `(id=1)` or `(id=89)`.. no rhythm to the number it tries to use.

**Comment by lukeed** [comment]
So the indexing is incorrect on the database side (too?). I'm really not familiar with Sequelize code, so not sure if it's relying on the DB index only or if it had its own.

Temporary workaround (to fix the DB sequence) is to run an `ALTER` sequence after the appropriate seeder has run:

```js
await DB.query(`ALTER SEQUENCE users_id_seq RESTART WITH ${users.length + 1}`);
```

**Comment by Darmikon** [comment]
In my case I was forced to use UUID instead of INTEGER. So no more autoIncrement and INTEGER for my id fields

**Comment by kaiyuanneo** [comment]
Also having this issue. I want to seed data in a "Cities" table but also have the option to add cities to this table later on. Running `create` after executing the relevant seeder causes `SequelizeUniqueConstraintError`. Is it possible to use IDs of data type INTEGER for this?

**Comment by sushantdhiman** [comment]
Postgres serial needs to be reset if you want to supply your own ids. This error appears when serial counter is ahead than the id you are trying to insert.

https://dba.stackexchange.com/questions/60802/fixing-table-structure-to-avoid-error-duplicate-key-value-violates-unique-cons

**Comment by kaiyuanneo** [comment]
I got past this issue by setting `id` attribute to <Model>.max('id') + 1 during creation of model instance after seeding.

**Comment by MichaelLeeHobbs** [comment]
For anyone that stumbles onto this 😄 
```    
return await model.bulkCreate(bulk)
        .then(async () => db.query(`ALTER SEQUENCE "${model.tableName}_id_seq" RESTART WITH ${await model.count() + 1}`))
        .catch(error => {
            if (error.message.indexOf('already exists') > -1) return
            console.error(error)
            // logger.error(error)
        })
```

**Comment by Cuxs** [comment]
I ended up doing something similar to what @lukeed did. A new seed with this code:
```javascript
const { Users } = require('../models');


module.exports = {
  up: async (queryInterface, Sequelize) => {
    const extistingUsers = await Users.count();
    await queryInterface.sequelize.query(`ALTER SEQUENCE "Users_id_seq" RESTART WITH ${extistingUsers + 1}`);
  },


};

```

**Comment by lukeed** [comment]
I found a better solution since last visiting this issue. At least in my case, some the `id` value doesn't necessarily correlate with how many records there are (eg, deletions).

Assuming you know the sequence name, you can just do this:

```js
await DB.query(`
  select setval('users_id_seq', (select max(id) from users), true);
`);
```

If you had 100 records, for example, but your largest `users.id` value is `126` then relying on `Users.count()` alone will set you up for conflict, since `101` (the next ID) probably/can already exist.

You can verify what the next `id` value will be with this:

```sql
select nextval('users_id_seq');
```

**Comment by Cuxs** [comment]
Yes, @lukeed you are right. Since I run these seeds only on the initial set of my database, there are no deleted users. But that it's just my case, your way is better.

Greetings!

**Comment by ryannewton** [comment]
@Darmikon Did you find a solution for this? I'm encountering the same error and am also using UUIDs.

**Model definition**
```
const uuid = require('uuid/v4')
...

  const Quote = sequelize.define('quote', {
    quote_id: {
      type: DataTypes.UUIDV4,
      primaryKey: true,
      defaultValue: uuid(),
      allowNull: false,
    },
...
```

**Query**
```
  const new_records = quotes.map(quote => ({ quote, book_id }))
  try {
    await Quote.bulkCreate(new_records)
  } catch(err) {
    console.log('Error: ', err)
  }
```

When I send a single element in `new_records` it runs fine. Doing this a 2nd time creates the error (or when `new_records` has more than 1 element).

**Comment by ryannewton** [comment]
For anyone who stumbles across this, my mistake was `defaultValue: uuid()` instead of `defaultValue: uuid`. `defaultValue` was being set to a static value rather than generating a new uuid each time a record was created.

**Comment by hmtuapp** [comment]
I have this same problem, I'm running a seeder that creates N records and Sequelize drops me an unique identifier error N times, one for every record created on the seeder, what can I do to avoid this?

**Comment by papb** [comment]
@hmtuapp None of the suggestions above worked for you?

**Comment by hmtuapp** [comment]
@papb It doesn't work when the key is higher than 1500. I don't know why.

**Comment by papb** [comment]
@hmtuapp Hmmm this is strange, I would need a SSCCE to help you further.

**Comment by airon-tark** [comment]
For multiply tables

```
'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {

    const tables = [
      'users', 'asset_groups', 'actions', 'allowed_locations', 'allowed_times',
      'assets', 'frequencies', 'frequency_hours', 'frequency_months', 'frequency_weekdays', 'permissions', 'rules'
    ]

    for (const tableName of tables) {
      const count = await getCount(queryInterface, tableName)
      await alterSequence(queryInterface, `${tableName}_id_seq`, count)
    }
  },
};

async function getCount(queryInterface, tableName) {
  return (await queryInterface.sequelize.query(`select count(*) from ${tableName}`))[0][0]['count'];
}

async function alterSequence(queryInterface, tableSeqName, count) {
  return queryInterface.sequelize.query(`ALTER SEQUENCE "${tableSeqName}" RESTART WITH ${count + 1}`);
}
```

**Comment by Hydrock** [comment]
Thanks a lot, thanks to the ideas above I solved this problem. As a result, I got the following:

**Model:**
`
module.exports = (sequelize, DataTypes) => {
  const Course = sequelize.define(
    'course',
    {
      title: {
        type: DataTypes.STRING,
        allowNull: false
      },
      subtitle: {
        type: DataTypes.STRING,
        allowNull: false
      },
      image: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      version: {
        type: DataTypes.STRING,
        allowNull: false
      },
    },
    {
      tableName: 'courses',
      timestamps: true,
    }
  );

  return Course;
}
`

**Seed File:**
`
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('courses', [
      {
        id: 1,
        title: 'New Course',
        subtitle: 'JavaScript',
        image: 'https://url',
        version: '0.0.1',
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ], {
      ignoreDuplicates: true
    });

    // Updating the index after inserting the data
    **await queryInterface.sequelize.query("SELECT setval('courses_id_seq', max(id)) FROM courses;");**
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('courses', null, {});
  }
};
`
