### ISSUE TITLE
[Feature request] Get cache or make request to db

### ISSUE THREAD

**Issue by crutch12** [sequelize/sequelize#9299]
Hi

That would be great, if we could get associations like in Rails, when you don't have to include associations to use them right on instace. What do I mean:

Example association: Vendor, Sellers.
```js
Vendor.hasMany(models.Seller);
```

If we write
```js
var vendor = await db.Vendor.find(where: {id : 1});
console.log(vendor.Sellers); // undefined (doesn't make request to db)
console.log(await vendor.getSellers()) // array (makes request to db)

var populatedVendor = await db.Vendor.find(where: {id : 1}, include: [db.Seller]);
console.log(populatedVendor.Sellers) // array (doesn't make request to db)
console.log(await populatedVendor.getSellers()) // array (anyway makes request to db, although we recently populated Sellers for this Vendor)
```

That would be very helpful, if we could use ```await populatedVendor.getSellers({tryLocal: true: true})``` and sequelize, looking at flag "tryLocal: true", first would try take ```Sellers``` from the ```populatedVendor``` instance
And if ```populatedVendor.Sellers``` is null, then it would make request to db to get Sellers for this Vendor.

Now, to implement the similar functionality, I use in Vendor's instance tricks like:
```js
var sellers = this.Sellers ? this.Sellers : await this.getSellers();
// if populated, get cached Sellers, else - make request to db
```
__Main benefit:__ I make request to db only when I need
__Disadvantage of my implementation:__ a lot of code

I would like to write smth like
```js
var sellers = await this.getSellers({tryLocal: true});
```
And dont think: _did I populate Seller, or have to make request to db?_

Maybe Sequelize already has similar features, but I don't know how to use it?

Thanks

**Comment by k-j-kleist** [comment]
Not sure caching etc. should be done by an ORM, rather by a layer above such as [Breeze](http://breeze.github.io/doc-main/)

**Comment by eseliger** [comment]
Yes, such things should be handled by another layer. Usually you would want the cache to be distributed between many nodes, whereas sequelize runs independently on all the nodes.

**Comment by crutch12** [comment]
Why?

I don' talk about another layer.

With sequelize if I populated associations, I can write
```js
var sellers = vendor.Sellers;
```
If I didn't
```js
var sellers = await vendor.getSellers();
```

I'm sure, this is not hard shift
```js
vendor.Sellers ? vendor.Sellers : vendor.getSellers();
```
right inside ```getSellers``` method
```js
...
if (opts.tryLocal) {
 return this.Sellers ? this.Sellers : await this.getSellers();
}
```

I don't talking about "cache"
I mean take data straight from instance, if instace has this data and flag ```tryLocal``` is active

And if we have all Sellers on this instance and write smth like
```js
var sellers = await vendor.getSellers({tryLocal: true, where: {status: 'busy'}});
```
sequelize won't make request to db with where condition
it would make same filter using javascript

**Comment by sushantdhiman** [comment]
@crutch12 What if `vendor.Sellers` got stale between first and second call to `getSellers`

**Comment by crutch12** [comment]
@sushantdhiman That's why I offer use flag ```tryLocal```, because in this case I'm sure data didn't change.

Without transactions data always may got stale, so I don't think this is big problem

If you write
```js
var sellers = await vendor.getSellers();
//... async code
//... await ...
// somewhere here sellers already could get stale, so
// sellers already != await vendor.getSellers()
```
So if this works so now, I don't see such problem in my solution because this problem exists without my example.
Hello cache problem :)

**Comment by eseliger** [comment]
But if you are sure data didn't change, aren't you sure then whether you already loaded the include or not? 

And what about concurrency, say, you have two nodes, couldn't it be possible the other node modified your sellers already? 🤔

**Comment by sushantdhiman** [comment]
No because `getSellers` is a contract that returns sellers known to database at time the it was called.

```js
// at this point you know sellers are what most recent data available to Sequelize
let sellers = await Model.getSellers();

// lots of code, passing sellers
// async operation could have changed sellers in between

// you know sellers is stale, so you can refresh
// but you are suggesting this should still return local data with { tryLocal: true }
sellers = await Model.getSellers();
```
As you can see this becomes a problem, `getSellers` now returning stale data with `tryLocal`, breaking its contract. This becomes a problem because its confusing when to use tryLocal and can cause some interesting bugs

I suggest using a new caching layer with https://github.com/mickhansen/dataloader-sequelize, it works really nicely and provides separation of concerns
