### ISSUE TITLE
Sequelize SQLite Busy Error when Initiated by multiple Users

### ISSUE THREAD

**Issue by LaserStony** [sequelize/sequelize#9302]
## What are you doing?
I am trying to handle multiple user calls to create or Fetch Data. But When a user calls the fetch function while another user called a create function, the SQLite Busy Error pops in the terminal.
```js
await  client.db.Project.findOrCreate({
				where: {
					name: projectTitle,
					abbr: projectAbbr,
					statusAbbr: Status
				}
			}).spread((prjct, created) => {
				//project.setStatus();
				if (!created) {
					client.db.currentGuild.getProjects({where: {abbr: prjct.abbr}}).then(prjcts => {
						if (prjcts.length === 0) {
							client.db.currentGuild.createProject({
								name: prjct.name,
								abbr: prjct.abbr,
								statusAbbr: prjct.statusAbbr
							}).then(prjcct => {
								client.db.Status.findOne({where: {abbr: Status}}).then(stat => {
									prjcct.setStatuses([stat]);
									//console.log(stat);
								});
								//
								client.helper.addMsgToDel("Done!");
								msg.channel.send("Done!");
							});
						} else {
							//client.helper.addMsgToDel("Project ");
							msg.channel.send(`A Project With ABBR => **${prjct.abbr.toUpperCase()}** already Exist. Named as => **${prjct.name}**`).then(mssssg => {
								setTimeout(function () {
									mssssg.delete();
								}, 7000);
							});
						}
					});
				}
				setTimeout(function () {
					msg.delete();
				}, 3000);
			});
```

## What do you expect to happen?
I expected the code to execute without any errors.

## What is actually happening?
I am getting the SQLite Busy error when multiple calls are made to the Database. Is there Any Way to resolve this?

__Dialect:__ sqlite
__Dialect version:__ 4.0.0
__Database version:__ (Don't know what this is)
__Sequelize version:__ 4.37.6
__Tested with latest release:__ No (If yes, specify that version)

**Comment by k-j-kleist** [comment]
https://www.sqlite.org/faq.html#q5

**Comment by LaserStony** [comment]
@k-j-kleist Can Transactions help solve this issue? or will I have to queue the access manually?

**Comment by sushantdhiman** [comment]
SQLite does not support multiple transaction at same time, `findOrCreate` use transaction internally. Here are some ideas to resolve this issue

1. Use `findCreateFind` which does not use transaction but rather depends upon unique constraint
2. Use sequelize.options.retry http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

```js
     retry: {
        match: [
          /SQLITE_BUSY/,
        ],
        name: 'query',
        max: 5
      },

```

**Comment by LaserStony** [comment]
@sushantdhiman Dude, Love you... You just saved me a Ton of coding... Hopefully this will solve my issue. Thanks. SO, What are Transactions for? Do they work same as [async](https://caolan.github.io/async/docs.html) to execute code sequentially?

**Comment by sushantdhiman** [comment]
Transactions are used whenever you want to make some changes to database that your can either commit or rollback as a whole.

Suppose a user is registering by Facebook, you first need to create a row in `User` table then create another row in `Oauth` table. What happens if your connection dropped between these two operations? In situations like this you use transactions, to either insert those two rows or nothing at all. This is just an example of transaction use case, there is lot more to them.

> Do they work same as async to execute code sequentially?

For SQLite, only one transaction at a time is supported for entire server (DB instance to be percise). Even if you are using async or other module, if another user is able to trigger another transaction you will get LOCK / BUSY error. A general solution is to retry in such cases.

**Comment by LaserStony** [comment]
Ooo... I get it now. Transactions are quite helpful then... Thanks once Again.

**Comment by sushantdhiman** [comment]
No problem :)
