### ISSUE TITLE
Optional foreign key creation

### ISSUE THREAD

**Issue by alfaproject** [sequelize/sequelize#9303]
## What are you doing?
I'm trying to get Sequelize to skip creation of foreign keys, but can't find any such option in the documentation, so I'm assuming it doesn't exist.

## What do you expect to happen?
I expect that Sequelize allows the consumer to set whether or not foreign keys will be created.

## What is actually happening?
I have no such option.

__Dialect:__ mysql
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ 4.28.5
__Tested with latest release:__ no

**Comment by sushantdhiman** [comment]
`constraints: false` does not works?

**Comment by alfaproject** [comment]
@sushantdhiman that option doesn't seem to be doing anything. I have to relations on this table:
```sql
CREATE TABLE `Transaction` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('deposit','withdrawal') NOT NULL,
  `status` enum('canceled','completed','failed','pending','pending_approval','started') NOT NULL,
  `amount` decimal(16,8) NOT NULL,
  `userId` int(10) unsigned NOT NULL,
  `merchantId` int(11) NOT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `userId` (`userId`),
  KEY `merchantId` (`merchantId`),
  CONSTRAINT `Transaction_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `Transaction_ibfk_2` FOREIGN KEY (`merchantId`) REFERENCES `Merchant` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

`User` relation doesn't have `constraints: false`
`Merchant` relation has `constraints: false`

**Comment by alfaproject** [comment]
I managed to do a reduced test case and it actually seems to work:

```js
const Transaction = sequelize.define('Transaction', {
  id: {
    type: Sequelize.INTEGER.UNSIGNED,
    primaryKey: true,
  },
});

Transaction.belongsTo(User, {
  constraints: false,
});
```

That doesn't create the foreign key.
I'll close this and sorry for wasting your time.
