### ISSUE TITLE
Run defaultValue function on adding a column for existing rows!

### ISSUE THREAD

**Issue by techsin** [sequelize/sequelize#9305]
## What are you doing?

```js
module.exports = {
	up: (queryInterface, Sequelize) => {
		queryInterface.addColumn("Customers", "code", {
			type: Sequelize.STRING,
			defaultValue: function () {
				return randomAsciiString(8);
			},
			allowNull: false,
			unique: true
		});

	},

	down: (queryInterface, Sequelize) => {}
};
```

## What do you expect to happen?
have function run for all existing rows and set default value of empty rows

## What is actually happening?
defaultValue is set when you do Customers.create, not when you do migration.
But if I do set default value to some string 'test12234' then existing rows do get that value. :/

I'm using latest version, I did npm update this week.

**Comment by sushantdhiman** [comment]
Next time use Google search first!! https://stackoverflow.com/a/17083488/4021724


Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
