### ISSUE TITLE
Add ability to define a Model without a database connection.

### ISSUE THREAD

**Issue by joe-spanning** [sequelize/sequelize#931]
For unit testing, I need to be able to mock my Sequelize models.  However, you can't define a Model without a database connection. 

It would be very helpful to be able to define a model that doesn't require a real database connection.

**Comment by rafis** [comment]
Reopen please.

I came from PHP world. I started with Express 4 - very pleasant, then Passport - also very liked architecture, then Sequelize - very frustrating in all ways. SOLID principles are completely unmet.

**Comment by janmeier** [comment]
@rafis there is plenty of unit testing in sequelize itself which works fine without a database connection. If you have a specific issue, please show some code

**Comment by mickhansen** [comment]
@rafis and people posting issues without showing code that doesn't work can be equally frustrating :)

**Comment by rafis** [comment]
I will share how I see it.
1) I have seen many web frameworks and most of then had a nice SOLID respectful architecture. In turn Sequelize trying to aggregate three modules inside one, namely ORM, Model Manager, Database connection manager which turns Sequelize into a mess. It should be three different modules (npm packages): `sequelize-orm`, `sequelize-connection-manager`, `sequelize-model-manager`. Developers should be able to defined model without connection, for example, `./models/user.js`:

    var sequelizeOrm = require('sequelize-orm');

    var User = sequelizeOrm.define({username: sequelizeOrm.STRING, password: sequelizeOrm.STRING});

    module.exports = User;

Next we should store ORM definitions in some Model manager, but it should not be forced to be in `./models/index.js`. If a developer wants he should be able to cumulate models then configuring app, for example, I'm using idea of initializers from LocomotiveJS, I want to cumulate models there. Now about connection Model manager should have method to `setDefaultConnectionManager()`, but each model instance can have invidual connection.
2) Configuration should not be forced to be in `./config/config.json`. I think it is more common sense to get it from `require('./config')` i.e. `./config/index.js`. It should return anything compatible with javascript `Object` (prefebably with `set()` and `get()` methods like in localStorage, sessionStorage).

Currently, I had to revert all my code back to paradigms Sequelize currently forces:
https://github.com/rafis/nodejs-express-passport-sequelize-example

**Comment by mickhansen** [comment]
@rafis That has absolutely nothing to do with this issue or unit testing models without a connection.

There are existing issues for decoupling model definitions and the sequelize instance.

I know that splitting everything into a bunch of modules is very popular, but we still prioritize being able to solve real work with Sequelize, and that requires both database connections and models to be defined.

You seem to have very specific ideas about how an ORM should work, i so i suggest you either go look at other Node.js ORMs, or build your own, or maybe tone down the privilege and contribute in a meaningful way (we are always looking to improve design, but Sequelize has been running production systems for 4 or more years, so there's a great deal of legacy involved).

**Comment by rajaavsk1937** [comment]
here i want only defining model , without database connectivity ,but here it shows an error that ,model is not defined or something like that:- here is the code

const Sequelize = require('sequelize');

    var player = sequelize.define('player', {
        title: {
          type: Sequelize.STRING
        },
 
        mess: {
         type: Sequelize.STRING
       },
       content: {
          type: Sequelize.STRING
        }
      }, {
        freezeTableName: true
      });

**Comment by kevmt** [comment]
This is somehow very important, define models, connect later.. specially in microservices --pattern where it shares common store.
