### ISSUE TITLE
mssql dialect escaping values incorrectly if they contain single quote

### ISSUE THREAD

**Issue by chihangc** [sequelize/sequelize#9312]
if, for example, a where clause in Sequelize specifies a value containing a single quote in raw query **replacements** (e.g. "McDonald's" ), Sequelize escapes the value as 

`\'mcdonald\'s\'` instead of `'mcdonald''s'`

The correct one should be adding one more quote instead of a dash

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
