### ISSUE TITLE
Using limit + offset and ordering by an associated entity results in two order by statements being generated

### ISSUE THREAD

**Issue by tylerjgarland** [sequelize/sequelize#9314]
Using limit + offset and ordering by an associated entity results in two order by statements being generated. 

## What are you doing?

Here is my options statement. I am wanting to order by the project's name where project is an included association.
```
    const options = {
      limit: params.pageSize,
      offset: ((params.pageNumber - 1) * params.pageSize),
      include: [{
        model: this.models.Projects,
        as: 'Project',
        where: projectWhere
      }, {
        model: this.models.Employee,
        as: 'Employee',
        include: [
_...more includes..._
]
      }],
      where: params.where,
      order: [
        ['Project', 'name']
      ]
    }
```
*query-generator.js* code is below and shows what happens. When addLimitAndOffset is called, it has adds an order by if there is a subquery.

```
addLimitAndOffset(options, model) {
_...code..._
    if (options.limit || options.offset) {
      if (!options.order || options.include && !orders.subQueryOrder.length) {
        fragment += options.order && !isSubQuery ? ', ' : ' ORDER BY ';
        fragment += this.quoteTable(options.tableAs || model.name) + '.' + this.quoteIdentifier(model.primaryKeyField);
      }

      if (options.offset || options.limit) {
        fragment += ' OFFSET ' + this.escape(offset) + ' ROWS';
      }

      if (options.limit) {
        fragment += ' FETCH NEXT ' + this.escape(options.limit) + ' ROWS ONLY';
      }
    }

    return fragment;
  }
```
The SQL generated then shows two order bys. 

```
WHERE [ProjectEmployees].[IsDeleted] = 0
	AND [ProjectEmployees].[EmployeeId] = x
ORDER BY [Project].[Name]
ORDER BY [ProjectEmployees].[ProjectEmployeeId] 
OFFSET 0 ROWS

FETCH NEXT 5 ROWS ONLY;
```
## What do you expect to happen?
Ordered by the property passed in, not by the default ID.

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__  mssql
__Dialect version:__ 14.0.1
__Database version:__ 14.0.1
__Sequelize version:__ "^4.37.6"
__Tested with latest release:__ No (If yes, specify that version)

**Comment by lerit** [comment]
already resolved by this pr #9307,but not released
