### ISSUE TITLE
Sequelize afterCreate and afterUpdate hooks are not firing - Sqlite

### ISSUE THREAD

**Issue by victorabraham** [sequelize/sequelize#9316]
## What are you doing?
Trying to add afterCreate and afterUpdate hooks on orderItem model on sequelize sqlite db.

```
const updateStockSingle = (orderItem, option, next) => {
  console.log('***********', orderItem);
};

const updateStockBulk = (orderItems) => {
  console.log('***********', orderItems);
};

module.exports = (sequelize, DataTypes) => {
  const OrderItem = sequelize.define('OrderItem', {
    id: {
      allowNull: false,
      primaryKey: true,
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4
    },
    name: {
      type: DataTypes.STRING
    },
    quantity: {
      type: DataTypes.DECIMAL(5, 2),
      defaultValue: 1
    },
    price: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
    },
  }, {
    hooks: {
      afterCreate: updateStockSingle,
      afterUpdate: updateStockSingle
    }
  }
);

  OrderItem.associate = function (models) {
    OrderItem.belongsTo(models.Order, {
      foreignKey: 'orderId',
      onDelete: 'CASCADE',
    });
    OrderItem.belongsTo(models.Product, {
      foreignKey: 'productId',
      onDelete: 'CASCADE',
    });
  };

  return OrderItem;
};

```
## Expectation
beforeValidate is firing. I expect afterCreate and afterUpdate hooks also to fire.

## What is actually happening?
afterCreate and afterUpdate hooks are not firing :(

__Dialect: sqlite
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version: 4.35
__Tested with latest release: YES

**Comment by sushantdhiman** [comment]
**SSCCE**

```js
const afterCreate = orderItem => {
  console.log('after create');
};

const afterUpdate = orderItem => {
  console.log('after update');
};

const OrderItem = sequelize.define('OrderItem', {
  id: {
    allowNull: false,
    primaryKey: true,
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4
  },
  name: {
    type: Sequelize.STRING
  },
  quantity: {
    type: Sequelize.DECIMAL(5, 2),
    defaultValue: 1
  },
  price: {
    type: Sequelize.DECIMAL(10, 2),
    allowNull: false,
  },
}, {
  hooks: {
    afterCreate,
    afterUpdate
  }
});

OrderItem.sync({ force: true })
  .then(() => {
    return OrderItem.create({
      name: 'abc',
      quantity: 12.3,
      price: 122.01
    });
  })
  .then(item => {
    return item.update({
      name: 'xyz'
    });
  });
```

```bash
after create
after update

```

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
