### ISSUE TITLE
Support replacements or bind parameters in attributes

### ISSUE THREAD

**Issue by martinb3** [sequelize/sequelize#9317]
## What are you doing?

I'd like to see bind parameters or some sort of replacement option on attributes; is there a way to use replacements functionality or bind parameters when specifying raw attributes?

I'm currently doing:

```js
model.findAll({
      attributes: { include: [
        [Sequelize.literal('MATCH(name) AGAINST(?)'), 'score'],
      ]},
...
});
```

## What do you expect to happen?

```js
model.findAll({
      attributes: { include: [
        [['MATCH(name) AGAINST(?)'), 'some_name_value'], 'score'],
      ]},
...
});
```

## What is actually happening?

An internal server error occurred (developmentMode: SequelizeDatabaseError: ER_PARSE_ERROR.

__Dialect:__ mysql
__Dialect version:__ not sure
__Database version:__ 5.6.22
__Sequelize version:__ 3.17.1
__Tested with latest release:__ Yes

**Comment by martinb3** [comment]
Hi there @heisian -- I need to put it in an `attributes:` clause, not a where clause.

**Comment by sushantdhiman** [comment]
This is already supported in v4 and v5


**SSCCE**

```js
const User = sequelize.define('User', {
  username: Sequelize.TEXT,
  rate: Sequelize.INTEGER
});

return User
  .sync({ force: true })
  .then(() => User.create({ username: 'user1', rate: 10 }))
  .then(() => User.create({ username: 'user2', rate: 10 }))
  .then(() => {
    return User.findAll({
      attributes: [
        [Sequelize.fn('sum', Sequelize.literal('$1 + rate')), 'my_sum']
      ],
      bind: [10],
      logging: console.log
    });
  })
  .then(users => {
    console.log(users[0].toJSON());
  });
```

```bash
Executing (default): SELECT sum(? + rate) AS `my_sum` FROM `Users` AS `User`;
{ my_sum: 40 }
```

**Comment by Omnia-Wahid** [comment]
you will need to change the apostrophe ' to ` and add  ${} like the following example:
model.findAll({
      attributes: { include: [
        [Sequelize.literal(`MATCH(name) AGAINST(${variable})`), 'score'],
      ]},
...
});

**Comment by ephys** [comment]
Do not inline variables in literals, it will make your application vulnerable to SQL injection attacks.

Use the replacements or bind parameters, they are supported:

```ts
model.findAll({
  attributes: { 
    include: [
      [literal(`MATCH(name) AGAINST(:myVariable)`), 'score'],
    ]
  },
  replacements: {
    myVariable: 'something that will be properly escaped',
  }
});
```
