### ISSUE TITLE
destroy() in paranoid mode does not persist properties updated in a beforeDestroy hook

### ISSUE THREAD

**Issue by ddolcimascolo** [sequelize/sequelize#9318]
I'm opening a pull request for this in a minute, but I wanted to raise the issue first.

## What are you doing?

I have a model in paranoid mode. This model gets a `beforeDestroy` hook attached in order to update a property on deletion (`updatedBy` which is a FK to another model, but this is not related to the problem described here).
When calling `destroy()`, instances are correctly soft deleted by my changed property is not persisted.

```js
const ParanoidUser = this.sequelize.define('ParanoidUser', {
  username: Sequelize.STRING,
  updatedBy: Sequelize.INTEGER
}, {
  paranoid: true,
  hooks: {
    beforeDestroy: instance => instance.updatedBy = 1
  }
});

return ParanoidUser.sync({ force: true })
  .then(() => ParanoidUser.create({ username: 'user1' }))
  .then(user => user.destroy())
  .then(() => ParanoidUser.findOne({ paranoid: false }))
  .then(user => console.log(user.updatedBy));
```

## What do you expect to happen?
_1_

## What is actually happening?
_null_

__Dialect:__ mysql / sqlite
__Dialect version:__ 5.7
__Database version:__ 5.7
__Sequelize version:__ 4.36.1
__Tested with latest release:__ Yes, 5.0.0-beta2

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Other hooks like `beforeCreate / beforeUpdate` can modify instance and modified value will be save, I would say `beforeDestroy` should allow that too when dealing with paranoid models which is internally updating records.

**Comment by heisian** [comment]
@sushantdhiman I feel like that could have unintended consequences unless it's really made clear in the docs what the discrepancy in behaviours between different hook types are.

**Comment by tomprogers** [comment]
@heisian The [official documentation](http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks) states very explicitly that you can make arbitrary changes to the model, and they will be persisted:

> Arguments to hooks are passed by reference. This means, that you can change the values, and this will be reflected in the insert / update statement.

The example code below that text very strongly suggests that simple assignment of new values to model attributes is sufficient.

If callers must manually invoke save/update within the hook (in some or all cases), then the documentation needs to be corrected.

**Comment by danedavid** [comment]
Wouldn't calling `save()` or `update()` trigger `beforeUpdate()` ? If so , does it happen synchronously, that is, is the instance deleted only after `beforeUpdate` has completed execution ?
If not, I think @tomprogers 's case would be justified.
