### ISSUE TITLE
Issue in using custom Getter to work with find() and findAll()

### ISSUE THREAD

**Issue by alexvicegrab** [sequelize/sequelize#9324]
## What are you doing?

For one of my models, I have created a DATEONLY field, to track the birthday of an individual.

I'm using MS SQL (SQL Server) to host the data, and have had issues getting the field out in a simple format: "2018-04-19" so I tried to recur to the custom getters to try and reformat the dates into strings using Moment.

```
get() {
       return moment.utc(this.getDataValue('dob')).format('YYYY-MM-DD');
},
```

This works neither for

```
User.findAll().then( users => {
    // This ends up calling the custom getter but after the patients are returned as a users array
})
```

but not here:

```
User.find({where: {id}}).then( user => {
    // This does not call the custom getter at all
})
```

I'm using: Sequelize CLI [Node: 9.3.0, CLI: 4.0.0, ORM: 4.37.4]

## What do you expect to happen?
I expect for the custom getter to be always called when using find, not only findAll

## What is actually happening?

The custom getter is not working in the find(where {some_condition})

__Dialect:__ mssql
__Dialect version:__ N/A
__Database version:__ Lastes SQL Server on Azure
__Sequelize version:__ Sequelize CLI [Node: 9.3.0, CLI: 4.0.0, ORM: 4.37.4]
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
It make no sense to call getters when user is not trying to access that data, once you try to get data by `.get` or `.toJSON`, those getters will be called

**SSCCE**

```js
const moment = require('moment');

const Book = sequelize.define(
  'books',
  {
    name: Sequelize.STRING,
    publishedAt: {
      type: Sequelize.DATEONLY,
      get() {
        return moment.utc(this.getDataValue('publishedAt')).format('YYYY-MM-DD');
      }
    }
  },
  { timestamps: false }
);

Book
  .sync({ force: true })
  .then(() => {
    return Book.create({
      name: 'August',
      publishedAt: new Date()
    });
  })
  .then(book => {
    console.log(book.get('publishedAt'));

    return Book.findAll();
  })
  .then(books => {
    console.log(books[0].get('publishedAt'));

    return Book.find({
      where: {
        name: 'August'
      }
    });
  })
  .then(book => {
    console.log(book.get('publishedAt'));
  })
  .catch(e => {
    console.dir(e);
  });
```

```bash
2018-04-20
2018-04-20
2018-04-20

```

**Comment by alexvicegrab** [comment]
toJSON() works, thank you.
