### ISSUE TITLE
UUID validation fails on SQLite

### ISSUE THREAD

**Issue by alexvicegrab** [sequelize/sequelize#9326]
I have a user table with an id field that should be a UUID:

```
id: {
      allowNull: false,
      type: DataTypes.UUID,
      unique: true,
      validate: {
           isUUID: 4
      }
},
```

When I try to save an item, the validation fails.

## What do you expect to happen?

I expect Sequelize to save the item.

## What is actually happening?

```
[ ValidationErrorItem {
       message: 'Validation isUUID on id failed',
       type: 'Validation error',
       path: 'id',
       value: '46611cb5-3044-522b-bc49-05535b812bc5',
       origin: 'FUNCTION',
       instance: [clinic],
       validatorKey: 'isUUID',
       validatorName: 'isUUID',
       validatorArgs: [Array],
       __raw: [Error] } ]
```

_Output, either JSON or SQL_

__Dialect:__  sqlite
__Dialect version:__ N/A
__Database version:__ 3.20.1
__Sequelize version:__  Sequelize CLI [Node: 9.3.0, CLI: 4.0.0, ORM: 4.37.4]
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
You are trying to validate a UUID v5 against v4. Sequelize validation is correct here :)
```
The UUID is 46611cb5-3044-522b-bc49-05535b812bc5, It is UUID Version 5.
```

**Comment by alexvicegrab** [comment]
Thank you, my bad entirely.
