### ISSUE TITLE
Repeated & Dotted Rows for Raw SQL query

### ISSUE THREAD

**Issue by UmerIftikhar** [sequelize/sequelize#9329]
I have created numerous associations for managing my DB Tables via Sequelize, however there are cases where I have not explicitly defined the associations, but I would want to query and include the results with those tables as well (which I have not associated explicitly). However, doing so in Sequelize throws an error stating the tables are not associated :/
Other way I tried to solve the issue, was using the raw query, which return dotted keys and lot of repeating rows. However, looking at the Sequelize docs, I could not find the solution to this problem.
What is the work around for it?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
