### ISSUE TITLE
The id is setting to NULL with sqlite

### ISSUE THREAD

**Issue by dancespiele** [sequelize/sequelize#9331]
## What are you doing?

```js
  module.exports = function User(sequelize) {
    return sequelize.define("activities", {
        id: {
            type: Sequelize.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        activity_type: Sequelize.STRING,
        user_id: Sequelize.INTEGER,
        start_time: Sequelize.DATE,
        end_time: Sequelize.DATE,
        start_coordinates: Sequelize.JSON,
        end_coordinates: Sequelize.JSON,
        calories: Sequelize.INTEGER,
        createdAt: Sequelize.DATE,
        updatedAt: Sequelize.DATE,
    });
};
```

## What do you expect to happen?
the Id set automatically 

## What is actually happening?
_But the output was bar!_
The id set to NULL

_Output, either JSON or SQL_
Executing (default): INSERT INTO `activities` (`id`,`activity_type`,`user_id`,`start_time`,`end_time`,`start_coordinates`,`end_coordinates`,`calories`,`createdAt`,`updatedAt`) VALUES (NULL,'cycling',1,'2018-04-22 12:00:43.301 +00:00','2018-04-22 12:00:43.301 +00:00','{"lat":12.399,"long":19.339}','{"lat":40.503,"long":30.45}',100,'2018-04-20 12:00:43.309 +00:00','2018-04-20 12:00:43.309 +00:00');

__Dialect:__ sqlite /
__Dialect version:__ 4.0.0
__Database version:__ 3.21.0
__Sequelize version:__ 4.37.6
__Tested with latest release:__ yes 4.37.6 (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`VALUES (NULL,...` means use next auto increment id, if you actually see the returned data or inspect SQLite store you will see `id`.

Also it is impossible to have NULL primary key :)
