### ISSUE TITLE
[BUG]Wrong Values being Returned IF Values INT >= 18(size)

### ISSUE THREAD

**Issue by LaserStony** [sequelize/sequelize#9335]
## What are you doing?
I am trying to get the Previously saved Snowflake Id of a User. But Not Matter Which User, It Always Returns The Wrong One (Which Doesn't Exist). I Tried all Options INTEGER,BIGINT and both With (18) and UNSIGNED and SIGNED as well.

```js
// model
const Sequelize = require("sequelize");
const sequelize = new Sequelize("database", "username", "password", {
	host: "localhost",
	dialect: "sqlite",
	logging: false,
	retry: {
		match: [
			/SQLITE_BUSY/,
		],
		name: "query",
		max: 5
	},
	storage: "./data/database.sqlite"

});
sequelize.define("User", {
			id: {
				type: Sequelize.INTEGER,
				autoIncrement: true,
				primaryKey: true
			},
			mainID: {
				type: Sequelize.INTEGER,
				allowNull: false,
				defaultValue: 0
			},
                         bestFriendID: {
				type: Sequelize.INTEGER,
				allowNull: true,
				defaultValue: 0
			},
                          girlFriendID: {
				type: Sequelize.INTEGER,
				allowNull: true,
				defaultValue: 0
			},
			name: {
				type: Sequelize.STRING,
				allowNull: false
			},
			isAdmin: {
				type: Sequelize.BOOLEAN,
				defaultValue: false
			}
		});

```

## What do you expect to happen?
I Set the Users and Their ID's are Set To:
430628086183100417
285858730447208448
430628086183100419

I Explored the Database and It actually does have these Values stored. At the Correct Location AS Well. (I checked 3 Times and the Database Only has this Single Row)
![image](https://user-images.githubusercontent.com/34425251/39082350-1eefe936-456b-11e8-9925-97ef8e9b1407.png)
```
User.findOne({where: {mainID: theuserID}}).then(usr => {
	console.log(`mainID: ${db.usr.getDataValue("mainID")}`);
	console.log(`bestFriendID: ${db.usr.getDataValue("bestFriendID")}`);
	console.log(`girlFriendID: ${db.usr.getDataValue("girlFriendID")}`);});
//I Tried Logging it the Other two ways as Well, but still the Same Results.
        //console.log(`mainID: ${db.usr.get("mainID")}`);
	//console.log(`bestFriendID: ${db.usr.get("bestFriendID")}`);
	//console.log(`girlFriendID: ${db.usr.get("girlFriendID")}`);});
        //console.log(`mainID: ${db.usr.mainID}`);
	//console.log(`bestFriendID: ${db.usr.bestFriendID}`);
	//console.log(`girlFriendID: ${db.usr.girlFriendID}`);
});
```
## What is actually happening?
I Am Getting these Instead.
430628086183100400
285858730447208450
430628086183100400
Checked them via Console.
![image](https://user-images.githubusercontent.com/34425251/39082481-2fd1b62e-456d-11e8-997f-0a9d5e12afa5.png)

__Dialect:__  sqlite3
__Dialect version:__ 4.0.0
__Database version:__ XXX
__Sequelize version:__ 4.37.6
__Tested with latest release:__ No (If yes, specify that version)

**Comment by phengus** [comment]
@Laser, hey, sorry I couldn't get to your message in discord. It's not a sequelize issue. It's Discord.JS. the ID's are held as Snowflakes or Strings in this case. So what you want to do is to store it as a String in the DB. Happened to me too awhile a go.

**Comment by laser** [comment]
Sounds good.

**Comment by LaserStony** [comment]
hmm... Interesting... Will Give it a Go...
