### ISSUE TITLE
Postgres not contains doesn't work, getting values.map is not a function

### ISSUE THREAD

**Issue by Marswang92** [sequelize/sequelize#9338]
Trying to query Postgres for the rows with an array column not contain a specific element
Tried both
```js
          where: {
            locations: {
              [Op.not]: {
                [Op.contains]: [1]
              }
            }
          }
```
```js
          where: {
            [Op.not]: {
              locations: {
                [Op.contains]: [1]
              }
            }
          }
```

## What do you expect to happen?
Should get the rows which doesn't contain the element

## What is actually happening?
Got `values.map is not a function` error

**Comment by benlester** [comment]
I too am getting this error, as mentioned on [my SO question here.](https://stackoverflow.com/questions/52954784/sequelize-does-not-contain-a-string-within-a-postgresql-array-query). Can this be reopened?

**Comment by baloran** [comment]
Hey,

Same here in 4.41.0, caused by
```js
myArrayOfString: {
  $not: {
    $contains: ["my-id"],
  },
},
```

Inside `data-types.js` the values is not like expected. `values` params equal
```
{ [Symbol(contains)]: [ 'my-id' ] }
```

Thanks ! 🙂
