### ISSUE TITLE
Setter with belongsToMany with undefined value error

### ISSUE THREAD

**Issue by Raphoik** [sequelize/sequelize#9349]
## What are you doing?
I have a `User` model that has multiple phone numbers through the `Phone` model. It isn't a required field, so it can be undefined. I set it through the setter generated by the association `belongsToMany`.

```js
user.save({ transaction: t })
  .then(user => user.setCreatedBy(req.user, { transaction: t }))
  .then(user => user.setPhones(undefined, { transaction: t }))
  .then(user => res.json(user));
```

## What do you expect to happen?
I expect the setter to update the updatedAt field, not throw an error and send the user back in the next `.then` just like the setter `setCreatedBy` with the `belongsTo` association.

## What is actually happening?
It inserts into the join table a record with the `UserId` but no `PhoneId` and throws an error since both are required fields.

## Output
`SequelizeDatabaseError: null value in column "PhoneId" violates not-null constraint.`

__Dialect:__ postgres
__Dialect version:__ 10.3
__Database version:__ 10.3
__Sequelize version:__ 4.37.5
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Can you try with

```js
  .then(user => user.setPhones([], { transaction: t }))
```

**Comment by Raphoik** [comment]
It doesn't throw an error, but doesn't return the `user` object, but only an empty array so I can't chain it.

**Comment by sushantdhiman** [comment]
```js
.then(user => user.setPhones(undefined, { transaction: t }).then(() => user))
```
