### ISSUE TITLE
Returing float for decimal types with MsSql

### ISSUE THREAD

**Issue by abacha** [sequelize/sequelize#9353]
Using sequelize connecting to a SQL Server database

> sequelize: 4.37.6
> tedious: 2.0.0

I've created a model with a DECIMAL field:

```
net_value: {
  type: data_types.DECIMAL
}
```

And when I render it on my controller, its being parsed to float

```
[
  {
    ...
    "net_value": 28142.030000000002,
    ...
  }
]
```

**Comment by sushantdhiman** [comment]
Just like `MySQL / Postgres`, `MSSQL / SQLite` should return decimal values as string to preserve precision

**Comment by sushantdhiman** [comment]
`tedious` driver does not support this https://github.com/tediousjs/tedious/issues/163, so we can;t implement this change
