### ISSUE TITLE
Error running application (.exe) on windows

### ISSUE THREAD

**Issue by renatosistemasvc** [sequelize/sequelize#9356]
Electron version:
current

Operating system:
windows 7

Last known working Electron version:
working in ubuntu 16

Expected behavior
application work in windows and linux environment

Actual behavior
[imagem de erro](https://scontent.fvdc1-1.fna.fbcdn.net/v/t1.0-9/31357712_1050640795074487_5161791133415636992_o.jpg?_nc_cat=0&oh=3fce7b9e2771caf12a3104bab45bf3bf&oe=5B978619)

How to reproduce
I started an eletronic project and did the integration with the database sequelize (sqlite). the following error appeared: please install sqlite3 package manually.

I solved the ubuntu problem by running: electron-rebuild
But the same error is displayed when I build to generate .exe to run on windows.
I developed it in ubuntu and want to generate .exe to run on windows.
Can someone help me?

**Comment by sushantdhiman** [comment]
Not sure how this is related to Sequelize

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )
