### ISSUE TITLE
SequelizeDatabaseError: Invalid object name

### ISSUE THREAD

**Issue by nestor-gm** [sequelize/sequelize#9357]
## What are you doing?

I' m trying to use Model Definition  
My suspicion is that I'm not specifying the schema or database correctly.
```js
const sequelize = new Sequelize('TESTDB', 'user', 'password', {
  host: 'localhost',
  dialect: 'mssql',
  operatorsAliases: false,
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  }
});
```
```js
const Departamento = sequelize.define('DEPARTAMENTO', {
    CD: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        allowNull: false
    },
    D: Sequelize.STRING(60)
})
```
```js
Departamento.findOne({ where: {CD: 1} }).then(resultado => {
})
```
## What do you expect to happen?
Get the query correctly 

## What is actually happening?
Unhandled rejection SequelizeDatabaseError: Invalid object name 'DEPARTAMENTOs'.

__Dialect:__  mssql
__Dialect version:__ 2.3.1 (Tedious)
__Sequelize version:__ 4.37.6

**Comment by dryqiao** [comment]
How did you solve it ?

**Comment by troyberg** [comment]
@nestor-gm I am Also curious. I have several other model definitions that work fine, but I've recently added one that throws this error. It looks like it's adding an 's' to the end.

**Comment by troyberg** [comment]
@dryqiao If you haven't already figured this out, according to the docs, "sequelize will automatically transform all passed model names (first parameter of define) into plural"

To override this set `freezeTableName: true,`

[http://docs.sequelizejs.com/manual/tutorial/models-definition.html#configuration](url)

**Comment by Wolfie010** [comment]
I have freezeTableName set to true. I have the correct table name listen as well. 

Still getting this error.
