### ISSUE TITLE
create with nested includes pointing to the wrong instance

### ISSUE THREAD

**Issue by Marie000** [sequelize/sequelize#9362]
I have three tables: paths, steps and listItems with the following relationships:
```js
db.path.hasMany(db.step);
db.step.belongsTo(db.path);

db.step.hasMany(db.listItem, {as: 'checklist', foreignKey: 'itemStepId'});
db.listItem.belongsTo(db.step, {as: 'checklist', foreignKey: 'itemStepId'});
```
I am doing a .create to make a deep copy of a path:
```js
db.path.create(path.dataValues, {
        include: [{
          model: db.step,
          as:'steps',
          include: [{
            model: db.listItem,
            as: 'checklist',
            fields: ['question', 'answer', 'user_feedback', 'comments', 'itemStepId']
          }],
          fields: ['title', 'description', 'url', 'type', 'optional', 'notes', 'progress', 'timeEstimate', 'pathId']
        }],
        fields: ['title', 'description', 'start', 'goal', 'open', 'private','confirmed', 'pathAuthorId', 'originalId']
      })
```

I wanted to have the copied steps to belong to the new path instance (they do! their pathId is correct)
and I wanted the copied listItems to belong to the new corresponding steps (they don't!). All the new copy of listItems belong to the original steps, not the new ones. itemStepId is the id of the original step.
So I end up with a new copy of the path, with its steps, but those steps contain no listItems.

Versions used: 
__Dialect:mysql
__Dialect version:"mysql2": "^1.5.3"
__Database version:5.5.5
__Sequelize version:4.37.6
__Tested with latest release:yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Can you show inspected `dataValues`?

**Comment by Marie000** [comment]
Here is what I get when I return the dataValues for the path returned after I do the nested create: 
```
{
    "title": "tiowureiowre new title2",
    "description": "adding a description",
    "start": "",
    "goal": "",
    "open": true,
    "confirmed": true,
    "pathAuthorId": "auth0|5ae1e7c841aacd1daa8a7e43",
    "originalId": 1,
    "steps": [
        {
            "id": 1,
            "title": "werwerew",
            "description": "",
            "url": "",
            "type": "",
            "optional": false,
            "notes": null,
            "progress": 0,
            "timeEstimate": 0,
            "date_started": null,
            "date_finished": null,
            "createdAt": "2018-04-26T14:53:21.000Z",
            "updatedAt": "2018-05-01T00:35:25.961Z",
            "pathId": 49,
            "checklist": [
                {
                    "id": 647,
                    "question": "item",
                    "answer": null,
                    "user_feedback": null,
                    "comments": null,
                    "createdAt": "2018-04-26T14:53:21.000Z",
                    "updatedAt": "2018-05-01T00:35:26.089Z",
                    "itemStepId": 1
                },
                {
                    "id": 648,
                    "question": "item 2",
                    "answer": null,
                    "user_feedback": null,
                    "comments": null,
                    "createdAt": "2018-04-26T14:53:21.000Z",
                    "updatedAt": "2018-05-01T00:35:26.089Z",
                    "itemStepId": 1
                }
            ]
        }
    ],
    "updatedAt": "2018-05-01T00:35:25.931Z",
    "createdAt": "2018-05-01T00:35:25.931Z",
    "id": 49
}
```
One thing I hadn't noticed before, those dataValues return a nested step with id 1, which is the id of the original step. In the database, it does create a new step (id 47) which points to the new path. 
But all the checklistItems are pointing to the original step, as indicated by their itemStepId of 1. This is also what ends up in the database: a new listItem belonging to the old step.

**Comment by sushantdhiman** [comment]
Can you show me a failing case, its hard to pin point this issue or even understand it. Just create a SSCCE then I will see if it can be fixed

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
