### ISSUE TITLE
Having an issue with data duplicating on my table

### ISSUE THREAD

**Issue by karosi12** [sequelize/sequelize#9367]
### I am having an issue with data duplicating on my table For example, I have this data
` let data = [{ name: Tope},{ name: Wale},{ name: Tope}];`

  `models.sequelize.Promise.map(data, pValue => {`
   ` return models.User.findOrCreate({`
      `where: {`
        `name: pValue.name,`
      `},`
     ` defaults: {`
        `name: pValue.name,`
        `organization_id: req.user.org_id`
     ` }`
    `}).then(result => {`
      `let resultData = result[0], `
          `created = result[1];  // i am getting true 3x`
        `console.log(created);`
       ` console.log(resultData.get());`
    `})`
  `});`

I have used this link, but the flow did not work for me https://stackoverflow.com/questions/31815076/node-sequelize-how-to-check-if-item-exists-before-adding-async-confusion/31815254

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
