### ISSUE TITLE
Some semicolons are missing

### ISSUE THREAD

**Issue by pscheich** [sequelize/sequelize#9368]
## What are you doing?
I recognized that some semicolons of the SQL statements  in the file _sequelize/blob/master/lib/dialects/mysql/query-generator.js_ are missing.

For example Line 274-276
```js
   showIndexesQuery(tableName, options) {
    return 'SHOW INDEX FROM ' + this.quoteTable(tableName) + ((options || {}).database ? ' FROM `' + options.database + '`' : '');
  }
```

And in other lines there are semicolons Line 489-491:
  getForeignKeysQuery(tableName, schemaName) {
```js
    return 'SELECT ' + this._getForeignKeysQueryFields() + ' FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = \'' + tableName + /* jshint ignore: line */
      '\' AND CONSTRAINT_NAME!=\'PRIMARY\' AND CONSTRAINT_SCHEMA=\'' + schemaName + '\' AND REFERENCED_TABLE_NAME IS NOT NULL;'; /* jshint ignore: line */
  },
```

## What do you expect to happen?
Having a nice consistent code.

## What do you expect to happen?
Fix it or leave it.
This isn't a real bug, but a bit inconsistent.

**Comment by sushantdhiman** [comment]
Yeah lots of old code is like that, I will accept PRs with intent to fix inconsistencies like this
