### ISSUE TITLE
Suggestion: Remove all aliases in v5

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#9372]
Not sure if I'm too late here but over the years Sequelize has create many many aliases functions. I think it would be a good idea to remove the aliases with the next major release.

- [ ] `find` vs. `findOne`
- [ ] `findById` vs. `findByPrimary`
- [ ] `afterBulkDestroy` vs `afterBulkDelete`
- [ ] `addHook` v. `hook`
- [ ] `VIRTUAL `vs `NONE`

_**Edit**_: Formatting

**Comment by sushantdhiman** [comment]
I have edited your post for better readability.

Good idea overall, we need to deprecate duplicate cases first, then remove them from master. This change should be easy to implement in small PRs

**Comment by SimonSchick** [comment]
@sushantdhiman I'll see if I can do that.

**Comment by frlinw** [comment]
As requested by @sushantdhiman 

## Based on @SimonSchick PR
| Remove | Keep | 
|---|---|
| insertOrUpdate | upsert |
| findByPrimary | findById |
| find | findOne |
| findAndCount | findAndCountAll |
| findOrInitialize | findOrBuild |
| afterBulkDelete | afterBulkDestroy |
| afterDelete | afterDestroy |
| hook | addHook |
| hasHooks | hasHook |
| updateAttributes | update |
| DOUBLE PRECISION | DOUBLE |
| NUMERIC | DECIMAL |
| NONE | VIRTUAL |
| asIs | literal |
| Sequelize.condition | Sequelize.where |
| Sequelize.prototype.Utils | Sequelize.Utils |
| Sequelize.prototype.Promise | Sequelize.Promise |
| Sequelize.prototype.TableHints | Sequelize.TableHints |
| Sequelize.prototype.Op | Sequelize.Op |
| Sequelize.prototype.Transaction | Sequelize.Transaction |
| Sequelize.prototype.Model | Sequelize.Model |
| Sequelize.prototype.Deferrable | Sequelize.Deferrable |
| Sequelize.prototype.Error| Sequelize.Error |
| Sequelize.prototype[error] | Sequelize[error] |

## Suggestions
| Remove | New | 
|---|---|
| upsert, insertOrUpdate | updateOrCreate |
| findById, findByPrimary | findByPk |

## Question
Should we add deprecation message or just add the migration table in the changelog ?

**Comment by SimonSchick** [comment]
Yea sorry, been super busy, cudos to @frlinw for taking over.

**Comment by frlinw** [comment]
I started to work on it. I'm doing some reorg for imports (require) in test files because it's a mess, will make a PR after that.

**Comment by frlinw** [comment]
beforeConnection added to the list, it's not used internally and it's the last hook alias

**Comment by sushantdhiman** [comment]
Implemented in https://github.com/sequelize/sequelize/pull/9933

**Comment by SimonSchick** [comment]
Hey, what about all the `prototype` aliases eg.

```
Sequelize.prototype.fn = Sequelize.fn;
Sequelize.prototype.col = Sequelize.col;
Sequelize.prototype.cast = Sequelize.cast;
Sequelize.prototype.literal = Sequelize.literal;
Sequelize.prototype.and = Sequelize.and;
Sequelize.prototype.or = Sequelize.or;
Sequelize.prototype.json = Sequelize.json;
Sequelize.prototype.where = Sequelize.where;
Sequelize.prototype.validate = Sequelize.prototype.authenticate;
```

and more?

**Comment by sushantdhiman** [comment]
They are ok for now

**Comment by SimonSchick** [comment]
One more, what about the `new DATATYPE()` vs. `DATETYPE()` calls?

**Comment by sushantdhiman** [comment]
`new DATETYPE()` is sure more verbose than `DATETYPE`, I prefer short functional syntax in this case. Once I tried to convert datatypes to classes but stopped just because of this issue

**Comment by SimonSchick** [comment]
Another alias I came across is `Transaction.LOCK` vs. `transactionInstance.LOCK`, all other `enum`s like that are static, why is that one available on the instance as well?

Also at the same time that section should be optimized, accessing enums shouldn't invoke object creation, we should just Object.freeze and assign it directly :)
