### ISSUE TITLE
Merge ssacl-attribute-roles into Sequelize

### ISSUE THREAD

**Issue by davidbarratt** [sequelize/sequelize#9373]
https://github.com/mickhansen/ssacl-attribute-roles from @mickhansen is a really simple library that has a lot of use cases. I was wondering if the functionality should be merged into this repository?

**Comment by sushantdhiman** [comment]
Sorry this goes beyond scope of Sequelize as an ORM

**Comment by davidbarratt** [comment]
I figured that might be the case... I'm actually not sure where this functionality should exist (within an API), is it the concern of the server (i.e. should be a hapi/express plugin) or is it the concern of the ORM?

At first I thought it should be the concern of the server, but then I wondered... well if validation is the concern of the ORM (even if that validation is not required by the database) isn't this just a form of validation (input and output)?

**Comment by sushantdhiman** [comment]
This is bit different than validation which is a concern of ORM as data is flowing through it, ORM should provide a way to validate data input.

Here we are trying to whitelist / blacklist attributes based on user roles. Sequelize should provide a way to include/exclude attributes which it does, with using those basic blocks an server level plugin or may be some user-land code should implement whitelist / blacklist by roles.

As this is strictly related to Sequelize model, ideally it should exists as a sequelize plugin, you can fork current one and improve it
