### ISSUE TITLE
Trouble to filter on cross table

### ISSUE THREAD

**Issue by wl1711** [sequelize/sequelize#9375]
## What are you doing?

contract.findAll({
                include: [{
                    model: contractAwardee,
                    required: false,
                    where:{
                        parentId: null
                    }
                }],
                where: {
                    deleted: false,
                    isSubContract: true
                }
            }

## What do you expect to happen?
I  want to filter on deleted = false and isSubContract = true and parentId is null, but I can't add the parentId: null to the 2nd where clause since the parentId is only in the cross table(ContractAwardee)

## What is actually happening?
SELECT
----
FROM
   "public"."Contract" AS "Contract" 
   LEFT OUTER JOIN
      "public"."ContractAwardee" AS "ContractAwardees" 
      ON "Contract"."id" = "ContractAwardees"."childId" 
      **AND "ContractAwardees"."parentId" IS NULL**
WHERE
   "Contract"."deleted" = false 
   AND "Contract"."IsSubContract" = true;

I need to move the bold line to the 2nd where clause

_Output, either JSON or SQL_
__Dialect:__postgres
__Dialect version:__ not sure
__Database version:__ 9.4
__Sequelize version:__ 4.27
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
