### ISSUE TITLE
Update performs Insert when model.isNewRecord = true

### ISSUE THREAD

**Issue by jkruse14** [sequelize/sequelize#9379]
## What are you doing?
I have implemented a caching system in which I call `build(<model data>)` then eventually call `model.update(...)` elsewhere. However, when build is used, by default the built model has isNewRecord set to true. When `model.update` is called, it attempts an INSERT instead of UPDATE, which fails due to uniqueness constraints.

## What do you expect to happen?
I expected model.update to *always* perform an update since there is an `upsert` method, or at least have this functionality documented here:
http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-update

## What is actually happening?
`model.update` performs an `INSERT INTO` when `model.isNewRecord = true`

__Dialect:__ mysql
__Dialect version:__ 5.7.20
__Database version:__ XXX
__Sequelize version:__ ^4.3.2
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
This is what `isNewRecord` means, it will perform INSERT as its a new record. When you are building instance why don't you try to `findOrCreate` it first rather than `build`

**Comment by jkruse14** [comment]
I am adding JSON representations of the model to a Redis cache. When I retrieve them from cache, I use `build` to create a sequelize model and return it to the app. When an update is performed on this model with `isNewRecord = true`, it tries to insert. This can be mitigated by setting `isNewRecord = false` at the time of build.

All I'm suggesting is that `update` **only** ever perform and UPDATE query because it is not documented that `update` will perform and INSERT and because there is an `upsert` method which has the well defined functionality to UPDATE **or** INSERT. Otherwise you technically have two functions that do the same thing, but one is not documented with the full functionality.

**Comment by nicodeg87** [comment]
Hi, was this issue closed with a solution/answer? I also have the same concern... update method should not do INSERT calls to the database.

**Comment by jkruse14** [comment]
@sushantdhiman - any news on this? Why was this closed? `update` behaves like `upsert` and it is not documented as such. Update should **only update** since there is a specific method to update or insert.

**Comment by alemarcha** [comment]
Any update about this? I have the same issue when I try to update my instance after a build is made because of that instance have isNewRecord property set to true when I built.

**Comment by SerdarSanri** [comment]
this kind of stuff makes me regret using sequelize. 
very simple query, 
```
 const company = await models.Company.findOne({where: {id: xxx}})
 company.firstName = 'Test Company';
 await company.save();
```
fails. when I put a breakpoint at user.firstName, I find that user.isNewRecord = true. but also has all the properties from the table. and I confirm, primary key is id as well as xxx exists.

![image](https://user-images.githubusercontent.com/651202/106348347-9ab1f300-6293-11eb-85e6-191570465fb1.png)

![image](https://user-images.githubusercontent.com/651202/106348333-8968e680-6293-11eb-89a3-b0f45f69c02b.png)

![image](https://user-images.githubusercontent.com/651202/106348327-7f46e800-6293-11eb-96a1-2cfba6e0bb28.png)

**Comment by Kemorave** [comment]
I stumbled upon this too just today while learning to use sequelize i couldn't find any solutions to it, unless i manually set the flag to false it will always perform insert 
ApiClient.findByPk(req.params.id).then((client) => {
            client.set(req.body);
            client.isNewRecord = false;
            if (client.changed())
                client.save()
                .then(() => res.status(200).json(client))
                .catch((err) => {
                    res.status(500).json(err);
                });
        }).catch((err) => {
            res.status(500).json(err);
        });

> 
> 
> this kind of stuff makes me regret using sequelize.
> very simple query,
> 
> ```
>  const company = await models.Company.findOne({where: {id: xxx}})
>  company.firstName = 'Test Company';
>  await company.save();
> ```
> 
> fails. when I put a breakpoint at user.firstName, I find that user.isNewRecord = true. but also has all the properties from the table. and I confirm, primary key is id as well as xxx exists.
> 
> ![image](https://user-images.githubusercontent.com/651202/106348347-9ab1f300-6293-11eb-85e6-191570465fb1.png)
> 
> ![image](https://user-images.githubusercontent.com/651202/106348333-8968e680-6293-11eb-89a3-b0f45f69c02b.png)
> 
> ![image](https://user-images.githubusercontent.com/651202/106348327-7f46e800-6293-11eb-96a1-2cfba6e0bb28.png)
