### ISSUE TITLE
Make documentation of attributes/fields more clear

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#9380]
The documentation makes it really hard to understand what "attribute" and "field" really mean in Sequelize terminology...

> An object, where each attribute is a column of the table. Each column can be either a DataType, a string or a type-description object, with the properties described below:

I think we can improve this definition, as an attribute is not by definition a column of the table but rather a bundle of information about a column in a table

About `attributes.column.field`, the docs have the following to say:

> If set, sequelize will map the attribute name to a different name in the database

This doesn't explain if the column name in the database is the `column` or the `field` in `attributes.column.field` and which one is the key in the `Model`'s data values.

I wanted to get clarifications on this and then make a PR to update the docs.

**Comment by sushantdhiman** [comment]
Attribute is part of model definition, which may be mapped to a table column (or not like VIRTUAL). For simpler cases `attribute` is Sequelize representation of some database column.

`field` is part of attribute definition, which is name of column some attribute definition points to. When not explicitly defined by user it defaults to attribute name.

Consider this model

```js
var User = sequelize.define('User', {
   email: {
      type: Sequelize.STRING
   },
   phoneNumber: {
      type: Sequelize.STRING,
      field: 'phone_number'
   }
});
```

Here `email` and `phoneNumber` are attributes, which maps to `email` and `phone_number` column of `Users` table

**Comment by jedwards1211** [comment]
Okay thanks.  I wonder why people decided to use the term "field" instead of column?

**Comment by fncolon** [comment]
> Okay thanks. I wonder why people decided to use the term "field" instead of column?

A column is collection of cells aligned vertically in a table. A field is an element in which one piece of information is stored, such as the received field.

The correct way to define this is `field`, column is representation from the design, not the actual benefit from its features.

**Comment by jedwards1211** [comment]
FWIW it doesn't seem like there's any general consensus on the distinction between these terms: https://dba.stackexchange.com/questions/65609/column-vs-field-have-i-been-using-these-terms-incorrectly

**Comment by jedwards1211** [comment]
Also notice how @papb said " maps to email and phone_number **column** of Users table". `phoneNumber: { type: Sequelize.STRING, column: 'phone_number' }` would be much less confusing.
