### ISSUE TITLE
Upgrading from 3 to 4.37

### ISSUE THREAD

**Issue by moseleyi** [sequelize/sequelize#9388]
We have been using Sequelize 3.15 for a while, locally I upgraded to 4.37 to check if our app would be working. 

I checked the documentation about upgrading and what has changed but one thing that's not working for me hasn't been referenced.

In few places I access the associations of Models like this `Project.associations.ProjectDetail` or if I need more levels `Project.associations.ProjectDetail.target.associations.SomethingElse` but the problem is that `associations` object is now empty. Has this been changed?

**Comment by sushantdhiman** [comment]
Closing this issue as it is not following issue template, but we can continue discussion.

`classMethods` were removed in v4, Are you sure `associate` method is properly defined and being called?

AFAIK there was no change in `associations` property
