### ISSUE TITLE
[Read Endpoint] Get data from two models

### ISSUE THREAD

**Issue by abhishekchotaliya** [sequelize/sequelize#9390]
Using association, I can request `/book/2/chapters`, which will give me chapters data of book 2(But no book data).

But is there any 'hack' by which I can get **book data + chapters data** from the same url? something like this?

```
{
    "book": {
        ... all book 2 data ... ,
        "chapters": {
            ... all book 2 chapters data ....
        }
    }
}
```

If not, then is it possible to get similar result with the use of middleware?

**Comment by sushantdhiman** [comment]
You can use `include` provided that book and chapter model are related to each other, possibly by hasMany.

Read more about associations [here](http://docs.sequelizejs.com/manual/tutorial/associations.html) (see eagar loading association chapter)

**Comment by sushantdhiman** [comment]
And issue was closed because it was not following issue template :)

**Comment by abhishekchotaliya** [comment]
@sushantdhiman 
How can I use **"include"** with my default get endpoint?
```
var bookResource = finale.resource({
  model: db.Books,
  associations : true,
  endpoints: ['/book', 'book/:id']
});
```

**Comment by sushantdhiman** [comment]
```js
var bookResource = finale.resource({
  model: db.Books,
  associations : true,
  endpoints: ['/book', 'book/:id']
});
```

That looks like some userland wrapper on Sequelize, whose internals I dont know. Basic idea is you need to pass `include` option with association you want to eagar load
