### ISSUE TITLE
Save file into blob 

### ISSUE THREAD

**Issue by Sbolder** [sequelize/sequelize#9392]
## What are you doing?

```js
paramsWebDocumentiData.blobData = fs.readFileSync(req.files.blobData.path, 'hex');

      let tmp = webDocumentiData.build(paramsWebDocumentiData);
      return tmp.save();
    })
    .then(() => {
      res.send(201);
    })
    .catch(error => {
      logger.error("Error create: ", error);
      return next();
    });
```

## What do you expect to happen?
I want save in my blob field on th edatabase the pdf file.
I sent pdf file with http/post 

## What is actually happening?
SequelizeDatabaseError: ORA-01704:

node 6 
resitfy 7 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
It is not possible to throw `ORA-01704` as Sequelize does not support Oracle DB
