### ISSUE TITLE
SMALLINT Data Type fails with postgres when autoIncrement = true

### ISSUE THREAD

**Issue by mjy78** [sequelize/sequelize#9397]
## What are you doing?
Creating a table with a SMALLINT field that has autoIncrement enabled using Postgres

```js
sequelize.define('Model', {
    testField: {
      field: 'test_field_id',
      type: DataTypes.SMALLINT,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    })
```

## What do you expect to happen?
Table should be generated when running sequelize.

## What is actually happening?
Table creation fails with syntax error `syntax error at or near "SERIAL"`

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.37.6
__Tested with latest release:__ Yes

The query generator for postgres (~/lib/dialects/postgres/query-generator.js) has specific handling for BIGINT with autoIncrement, but not SMALLINT.

To resolve the issue I believe we need to change
```
    if (_.includes(dataType, 'SERIAL')) {
      if (_.includes(dataType, 'BIGINT')) {
        dataType = dataType.replace(/SERIAL/, 'BIGSERIAL');
        dataType = dataType.replace(/BIGINT/, '');
      } else {
        dataType = dataType.replace(/INTEGER/, '');
      }
      dataType = dataType.replace(/NOT NULL/, '');
    }
```
to this
```
    if (_.includes(dataType, 'SERIAL')) {
      if (_.includes(dataType, 'BIGINT')) {
        dataType = dataType.replace(/SERIAL/, 'BIGSERIAL');
        dataType = dataType.replace(/BIGINT/, '');
      } else if (_.includes(dataType, 'SMALLINT')) {
          dataType = dataType.replace(/SERIAL/, 'SMALLSERIAL');
          dataType = dataType.replace(/SMALLINT/, '');        
      } else {
        dataType = dataType.replace(/INTEGER/, '');
      }
      dataType = dataType.replace(/NOT NULL/, '');
    }
```

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/9406
