### ISSUE TITLE
[Docs] Document on the Associations page that you can pass an object to foreignKey

### ISSUE THREAD

**Issue by davidbarratt** [sequelize/sequelize#9405]
I had to go through and read the source code to find this out, but you can pass an object to `foreignKey` rather than a string. This is helpful if you want to pass additional options. This should probably be added to the documentation somewhere (perhaps just in one of the examples?)

**Comment by sushantdhiman** [comment]
It is mentioned in http://docs.sequelizejs.com/class/lib/associations/base.js~Association.html but we can certainly add this to https://github.com/sequelize/sequelize/blob/master/docs/associations.md for better exposure
