### ISSUE TITLE
Valid raw query will not execute through sequelize, but executes perfectly in every other mysql console

### ISSUE THREAD

**Issue by dskvr** [sequelize/sequelize#9408]
## What are you doing?
Conditional insert on duplicate key update. 

```js
sequelize.query(`INSERT INTO public_keys (address, public_key, block_number) VALUES ('${record.address}', '${record.public_key}', ${record.block_number}) ON DUPLICATE KEY UPDATE block_number = IF(block_number > VALUES(block_number), VALUES(block_number), block_number)`)
```

## What do you expect to happen?
![screen shot 2018-05-07 at 2 18 29 pm](https://user-images.githubusercontent.com/299465/39701484-9dc2b304-5201-11e8-8c9a-97806e30be9a.png)

## What is actually happening?
The **valid query** is throwing an error at line 1. When I console.log that query, and copy paste it to **any** MySQL console (CLI or GUI based), it works as expected without any issues.

```
Unhandled rejection Error: SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `public_keys` (`address`, `public_key`, `block_number`) VALUES ('0x0' at line 1
    at query.public_keys_bulk_upsert.then.catch.e (***134:15)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at save_rows (***s:132:13)
    at web3.eth.getBlock.then.block (***:103:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```
\
__Dialect:__ mysql
__Dialect version:__  5.6.37
__Database version:__  5.6.37
__Sequelize version:__ 4.37.6
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
You have an error in SQL statement, as error says. Show me the logged query

**Comment by dskvr** [comment]
@sushantdhiman  I repeat: I take the exact query given to Sequelize, place it into Mysql CLI, Sequel Pro, Mysql Administrator, and get NO ERROR, X ROWS affected.

**Comment by dskvr** [comment]
Still an issue.
