### ISSUE TITLE
raw query to create function got fail

### ISSUE THREAD

**Issue by Rukeith** [sequelize/sequelize#9414]
## What are you doing?
Run raw query to create function at migration

```js
  sequelize.query(`
    DELIMITER $$
    DROP FUNCTION IF EXISTS get_local_time_zone $$
    CREATE FUNCTION get_local_time_zone() RETURNS VARCHAR(32)
    BEGIN
    DECLARE ret_val VARCHAR(32);
    SET ret_val=(select substring_index(timediff(now(),utc_timestamp()),':',2));
    IF (LENGTH(ret_val) < 6) THEN
    SET ret_val=CONCAT('+',ret_val);
    END IF;
    RETURN ret_val;
    END $$
    DELIMITER ;
  `);
```

## What do you expect to happen?
Success create function

## What is actually happening?
Got parse syntax error

![2018-05-08 11 05 29](https://user-images.githubusercontent.com/7069605/39735785-be417396-52af-11e8-8210-24d2e36a0937.png)

If I paste the sql to Sequel Pro to execute, it work fine. But I use same sql to sequelize got fail.

__Dialect:__ mysql
__Dialect version:__ 5.7.17
__Sequelize version:__ 3.30.2
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
v3 is no longer supported

**Comment by Rukeith** [comment]
@sushantdhiman I test with latest release still got this error before 10 mins ago.

**Comment by sushantdhiman** [comment]
Your SQL is invalid https://www.eversql.com/sql-syntax-check-validator/

**Comment by Rukeith** [comment]
@sushantdhiman I think that isn't correct. I connect to mysql and execute same sql, it work success.

**Comment by sushantdhiman** [comment]
I am not sure what could be the reason for that, but you can see yourself syntax validator I linked which has nothing to do with Sequelize says there is an issue with syntax

**Comment by PatrickGeyer** [comment]
It's because DELIMITER isn't a MySQL feature, it's only supported by the clients that you connect to MySQL with. The sequelize client doesn't support it, neither do most other clients.
As for a solution... No clue.

**Comment by ryan-sandy** [comment]
Try breaking your queries into multiple raw calls and drop the DELIMITER.
