### ISSUE TITLE
Sequzlie return invalid number of deleted rows

### ISSUE THREAD

**Issue by wexoni** [sequelize/sequelize#9417]
## I have a issue that happens periodically. It does not depend of the quantity of the rows to be deleted. I was not able to find a patters. In another words it can happen with 2 rows, or even with 100!

Issue: I send an array of ID's for the rows that I wish to be deleted. Deletion is always a success (Cant find the rows after). Sequalize (3.24.6) sometimes returns it deleted 0 rows, while I know for the fact it made proper deletion.?

```
MyRepository.js:
deleteAccountProfileEntries(idArray) {
        return this.storage.deleteProfileEntries(idArray).then((erasedCount) => {
            if (idArray.length !== erasedCount) {
                throw new Error('invalid amount of records removed');
            }
        });    
    }

MyStorage.js
deleteProfileEntries(profileEntryIds) {
        if (!Array.isArray(profileEntryIds)) {
            throw new Error('Expected an array as an input');
        }
        return model.profile_entries.destroy({
            where: {
                id: {
                    $in: profileEntryIds
                }
            }
        });
    }
```

## What do you expect to happen?
If I send 10 rows for deletion, I expect the number of returned deleted rows to be also 10.

## What is actually happening?
Sometimes (can't find the pattern). If I send 10 rows for deletion, reply is 0. Please note, the deletion is always carried properly. Problem is in the reply. 

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version:__ 5.6.33
__Sequelize version:__ 3.24.6
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
I am sorry but we don't support v3 any more.

May be some of the rows you trying to deleted are already deleted
