### ISSUE TITLE
v3 depends on vulnerable version of lodash

### ISSUE THREAD

**Issue by thom-nic** [sequelize/sequelize#9418]
lodash <4.17.5 is vulnerable to prototype pollution: https://nodesecurity.io/advisories/577

I haven't looked into how sequelize uses lodash exactly but either way, if v3 is still actively maintained, it would be nice to get a version bump to keep security checks green.  We haven't been able to prioritize an upgrade to sequelize v4 yet so support for v3 would be appreciated.

**Comment by sushantdhiman** [comment]
v3 is not actively maintained but we can always fix security issues. Released `v3.33.0` with updated lodash version

**Comment by thom-nic** [comment]
Thank you!
