### ISSUE TITLE
Model options.scopes should be an Object instead of an Array ?

### ISSUE THREAD

**Issue by FranckFreiburger** [sequelize/sequelize#9423]
https://github.com/sequelize/sequelize/blob/addceb642861c4bbf96a6e01b235f4b7ca24bcd9/lib/model.js#L872

I wondering why model.options.scopes is an Array instead of an Object ?

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/7b7b23d5b79b08eae45c914b090f2d41e8b20d98

Some old code
