### ISSUE TITLE
Incorrect usage of association names (documentation)

### ISSUE THREAD

**Issue by JanisE** [sequelize/sequelize#9424]
I wanted to suggest correcting the documentation regarding associations. When I was reading [this](http://docs.sequelizejs.com/manual/tutorial/associations.html), it confused me, until I learned to ignore the incorrect usage (at least, it seems that to me) of relation DB table association type names.

A CapitalCity-Country would be a good example of "one-to-one" relationship, but all the Country-City, Team-Player, and Project-User are examples of "many-to-one" relationship.

I see that they are still good examples for describing functionality of `belongTo` method, but this method may be used to establish both "one-to-one" and "many-to-one" relationships, and all the examples in the documentation are "many-to-one" despite being given under the header of the "one-to-one" relationship.

For example, see [Wikipedia entry](https://en.wikipedia.org/wiki/One-to-one_(data_model)) on one-on-one relationship.

**Comment by aercolino** [comment]
@JanisE , you're totally right. The documentation on associations is confused and confusing. I forked the project just to try to fix that.
