### ISSUE TITLE
Generated sql returns 4 row but sequelize array contains 3 objects

### ISSUE THREAD

**Issue by ArtashMardoyan** [sequelize/sequelize#9434]
### SQL
```sql
SELECT
  "Table"."id",
  "Table"."userId"
FROM "Table" AS "Table"
 LEFT OUTER JOIN "AnotherTable" AS "AnotherTable" 
ON "Table"."id" = "AnotherTable"."TableId"
LIMIT 10
OFFSET 0;
```
# Returns 4 row

### Model find
```js
  const data = await Table.findAndCountAll({
                subQuery: false,
                include: [
                    {
                        model: 'AnotherModel',
                        as: 'users',
                        attributes: ['AnotherModelField']
                    }
                ]
            limit,
            offset
        });
```

# Returns array length 3

**Comment by ArtashMardoyan** [comment]
@sdepold could you help ?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by ArtashMardoyan** [comment]
@sushantdhiman  I think it's bug.I want to get not grouped data but sequelize returns me grouped.
No options to skip _groupJoinData function.So I can get data without grouping.

**Comment by tumdav** [comment]
Some
