### ISSUE TITLE
How to skip sequelize _groupJoinData 

### ISSUE THREAD

**Issue by ArtashMardoyan** [sequelize/sequelize#9435]

**Comment by ArtashMardoyan** [comment]
@mickhansen  can you help ?

**Comment by mickhansen** [comment]
@ArtashMardoyan i'm not an active maintainer. Maybe `raw: true` works, i don't really recall.

**Comment by ArtashMardoyan** [comment]
@sdepold
@janmeier
@durango
@sushantdhiman
@greenkeeperio-bot
@overlookmotel
@mbroadst
@thanpolas
@felixfbecker
@optilude
@iamjochem
@saschagehlich
@seth-admittedly
@Verdier
@lemon-tree
@reedog117
@v12
@DavidTPate
@elliotf
@harshithkashyap
@vpontis
@clkao
@greenkeeper[bot]
@sveinnfannar
@terraflubb
@josephpage
@jharting
@SohumB
@treythomas123
@danielschwartz
@gabegorelick
@quiddle
@bulkan
@EToreo
@mweibel
@alitaheri
@tremby
@bromanko
@guersam
@xdarklight
@schonfeld
@ricardograca
@ryanpon
@3ch01c
@n3o77
@fixe
@jonathana
@OtaK
@mkaufmaner
@snit-ram
@Americas
@smihica
@tornillo
@mdarveau
@alubbe
@yonjah
@ns3777k
@alekbarszczewski
@domasx2
@eveiga
@vlmonk
@alexstrat
@mdpauley
@ackerdev
@watson
@ekmartin
@gutobortolozzo
@pola88
@Alexsey
@bencevans
@bgw
@FredKSchott
@LJ1102
@dizlexik
@x-warrior
@MichaelKearnsSoftwire
@mex
@nadrane
@nrmitchi
@ClimbsRocks
@tadman
@stowns
@harimohanraj89
@jtschoonhoven
@sevastos
@tngraessler
@mccabemj
@faceleg
@Dahlgren
@nullivex
@frogcjn
@dejanr
@alum
@gustavpursche
@little-big-h
@crossman
@joshperry
@mlegenhausen
@Znarkus
@axetroy
@azeemba
@lucasBertola
@rbtnguyen
@btroo
@aweary
@bskari
@direvus
@bcg
@brettvitaz
@1o1brian
@briandamaged
@blundin
@doowb
@rufengch
@bsapot
@chentsulin
@csreid
@cweckesser
@carterchung
@watsoncj
@caiquecastro
@chuntley
@DeviaVir
@ChrisAntaki
@noderat
@cdibbs
@chrisjensen
@chriskalmar
@cgrinaldi
@streeter
@madebyherzblut
@cdmcnamara
@Hoten
@connyay
@connor4312
@cscheye
@Khez
@cyrusbowman
@danconnell
@dallasread
@visualfanatic
@damianb
@dwchung
@dancrumb
@djsiroky
@danielmhanover
@DanielRHayes
@sheltond
@xkjyeah
@davidjb
@dchester
@hacker112
@davidlanger
@davidtsai
@denisazevedo
@dgb
@diosney
@Domiii
@dpatti
@dylanlingelbach
@EamonnMR
@edlin
@edtsech
@onzag
@pixel2
@McPo
@ekosz
@ErichBSchulz
@euqen
@masad-frost
@phodal
@francescoinfante
@franciscocardoso
@Frank0628
@FrederikNS
@firatkucuk
@ghernandez345
@GabeIsman
@garethflowers
@garrett-gottlieb
@garrypolley
@gavri
@GeoffreyPlitt
@Ghost141
@gbau
@grantcarthew
@tomfun
@ggrimbert
@hackreactor-students
@harish2704
@sklirg
@iansu
@dotpack
@yachaka
@israeldelahoz
@iamakulov
@idmontie
@Bibernull
@gjacobrobertson
@johngiudici
@jdstep
@jorrit
@josemando
@jfred
@elhoyos
@kjvalencik
@kevinsimper
@kranrao
@manmar92
@marswong
@weblemur
@matthewheck
@gauthierm
@mjy78
@mikrofusion
@arcana261
@iizukanao
@natesilva
@nchase
@osagie
@hippich
@percyperez
@pranavrajs
@rplopes
@rmzg
@rmi22186
@defunctzombie
@ryanalane
@sankethkatta
@geekmug
@seanjh
@swoodtke
@sstoiana
@sunshinewyin
@kiddouk
@User4martin
@kioopi
@hisorange
@Wsiegenthaler
@wbyoung
@alexwl
@corpix
@denysonique
@edgarsilva
@freezy
@fundon
@gtelljohann
@iuriaranda
@ivesdebruycker
@ksmithut
@mcarboni-redant
@musicformellons
@oss92
@paulmaszlik
@rogerc
@sonnym
@tjmehta
@turbofoxwave
@sangpire
@contactakagrawal
@lauzierj
@b3ntly
@AckerApple
@kainolophobia
@alanbueno
@albertosouza
@a0viedo
@p0vidl0
@alexahn
@alexpls
@alexschneider
@alexturek
@AJamesPhillips
@Kuzmin
@alexanderreiff
@ali-essam
@aminRX
@kytwb
@amasad
@pronebird
@jifeon
@eddieajau
@hessloch
@AndrewSouthpaw
@amuzalevskiy
@andriis
@jedwards1211
@andywhite37
@Nshul
@amarcadet
@adrukh
@abegines
@arikfr
@witem
@guzart
@ashlux
@aslakhellesoy
@austinjalexander
@austindebruyn
@mliszewski
@tiblu
@reacuna
@dickie81
@grayt0r
@rfink
@sorin
@maximeCony
@mulderr
@adamsch1
@tomchentw
@pmhpereira
@siyangbi
@bookercodes
@mekanics
@peaches
@ajfranzoia
@Ghirro
@selfcontained
@cmwilhelm
@codeinvain
@dantman
@db6edr
@topikachu
@idris
@interlock
@jrmurad
@jValdron
@jeff-french
@dijonkitchen
@kenjitayama
@nemisj
@mohlman3
@scragg0x
@megshark
@delucco
@MrVoltz
@nunofgs
@poying
@sarme
@sebastianhoitz
@shaunrader
@simong
@ysagal
@skleeschulte
@vanderhoopnbc
@vickenstein
@yjwong
@XadillaX
@contra
@jchbh
@netsgnut
@syldor
@whito
@zapatek
@triptec
@ruifortes
@calvintwr
@toastynerd
@aceew
@pensierinmusica
@swarthy
@atorkhov
@allanca
@kirla3092
@accerqueira
@andyburke
@paolord
@ashokfernandez
@braddunbar
@brendonboshell
@cpitt
@holm
@christopher4lis
@craigbeck
@dankohn
@danawoodman
@curiousdannii
@duhruh
@ElliotChong
@eseliger
@evantahler
@hieven
@fabioespinosa
@frantzmiccoli
@gabrielfalcao
@gazoakley
@gorangajic
@guilhermef
@GuilhermeReda
@coderbuzz
@melkior
@jamelt
@jasonku
@RebootJeff
@jcombes
@jsatk
@jjclark1982
@joeylgutierrez
@johanneswuerbach
@sdepold
@janmeier
@durango
@sushantdhiman
@greenkeeperio-bot
@overlookmotel
@mbroadst
@thanpolas
@felixfbecker
@optilude
@iamjochem
@saschagehlich
@seth-admittedly
@Verdier
@lemon-tree
@reedog117
@v12
@DavidTPate
@elliotf
@harshithkashyap
@vpontis
@clkao
@greenkeeper[bot]
@sveinnfannar
@terraflubb
@josephpage
@jharting
@SohumB
@treythomas123
@danielschwartz
@gabegorelick
@quiddle
@bulkan
@EToreo
@mweibel
@alitaheri
@tremby
@bromanko
@guersam
@xdarklight
@schonfeld
@ricardograca
@ryanpon
@3ch01c
@n3o77
@fixe
@jonathana
@OtaK
@mkaufmaner
@snit-ram
@Americas
@smihica
@tornillo
@mdarveau
@alubbe
@yonjah
@ns3777k
@alekbarszczewski
@domasx2
@eveiga
@vlmonk
@alexstrat
@mdpauley
@ackerdev
@watson
@ekmartin
@gutobortolozzo
@pola88
@Alexsey
@bencevans
@bgw
@FredKSchott
@LJ1102
@dizlexik
@x-warrior
@MichaelKearnsSoftwire
@mex
@nadrane
@nrmitchi
@ClimbsRocks
@tadman
@stowns
@harimohanraj89
@jtschoonhoven
@sevastos
@tngraessler
@mccabemj
@faceleg
@Dahlgren
@nullivex
@frogcjn
@dejanr
@alum
@gustavpursche
@little-big-h
@crossman
@joshperry
@mlegenhausen
@Znarkus
 **Guys it's very urgent please help**

**Comment by sushantdhiman** [comment]
Closed for not following issue template and spam.

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
