### ISSUE TITLE
How to match unique key and foreign key in inlcude instead of primary key and foreign key

### ISSUE THREAD

**Issue by suriyakumarcs** [sequelize/sequelize#9436]
## What are you doing?
There are two tables [bow detail and item detail]. I'm actually done the association between two tables

```js
 var BomDetail = sequelize.define('BomDetail', {
        bomId: {
            type: DataTypes.STRING,
            field: 'bom_id',
            unique: true
        },
        createdBy: {
            type: DataTypes.STRING,
            field: 'created_by'
     },
BomDetail.hasMany(models.ItemDetail, {
     foreignKey: 'bomId',
     sourceKey: 'bomId',
     onDelete: 'cascade'
});

var ItemDetail = sequelize.define('ItemDetail', {
        itemId: {
            type: DataTypes.STRING,
            field: 'item_id',
            unique: true
        },
        holdDate: {
            type: DataTypes.DATE,
            field: 'hold_date',
        },
        bomId: {
            type: DataTypes.STRING,
            field: 'bom_id'
        },
ItemDetail.associate = function(models) {
        ItemDetail.belongsTo(models.BomDetail, {
            foreignKey: 'bomId',
            targetKey: 'bomId',
            onDelete: 'cascade'
        });
    };
```

## What do you expect to happen?
When i do

 Models.ItemDetail.findAll({
        include: {
            model: Models.BomDetail
        }
    })

normal result that is bomdetail inside the item detail will come

{
        "id": 3,
        "itemId": "2397saf8enaeflk8",
        "productId": "afsggfg14fhg43t",
        "productName": "Siemens meter",
        "quantity": 3,
        "followUpDate": "2018-05-15T18:30:00.000Z",
        "leadTime": 10,
        "releaseDate": "2018-05-20T18:30:00.000Z",
        "holdDate": "2018-05-31T18:30:00.000Z",
        "bomId": "azcpspp02_07141700_07_00_M00",
        "status": "hold",
        "created_at": "2018-05-14T09:20:15.658Z",
        "updated_at": "2018-05-14T09:20:15.658Z",
        "BomDetail": {
            "id": 50,
            "bomId": "azcpspp02_07141700_07_00_M00",
            "createdBy": "azcpspp02",
            "createdByName": "Siemens BLR -nry85322",
            "bomCreatedDate": "2018-02-26T00:00:00.000Z",
            "soldToAcc": "30000006",
            "status": "hold",
            "created_at": "2018-05-11T11:58:46.267Z",
            "updated_at": "2018-05-11T11:58:46.267Z"
        }
    },

but when i do 

Models.BomDetail.findAll({
    include: {
          model: Models.ItemDetail: 
    }
})

## What is actually happening?

Error will come..
Conversion failed when converting the nvarchar value 'azcpspp02_07141700_07_00_M00' to data type int.

it compares primay key that is generated by sequelize in BomDetail table and foreign key of ItemDetail
like
...LEFT OUTER JOIN [lta_item_detail] AS [ItemDetails] ON  **[BomDetail].[id] = [ItemDetails].[bom_id]**;

_Output, either JSON or SQL_
But i want to compare unique key(bomId) of BomDetail table and corresponding foreign key of ItemDetail table (BomId)..

(i.e)...LEFT OUTER JOIN [lta_item_detail] AS [ItemDetails] ON  **[BomDetail].[bom_id] = [ItemDetails].[bom_id]**;

What should i do for this!!?

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
