### ISSUE TITLE
Unique column with duplicated null values

### ISSUE THREAD

**Issue by caiquecastro** [sequelize/sequelize#9438]
I'm creating a unique column that accepts null values (nullable column).

SQLServer, differently from Postgres and MySQL, doesn't allow duplicated null values on a unique column.

## What do you expect to happen?
If it's unique and accepts null, we can make some adjusts on index creation to allow null and still be unique:

```js
sequelize.define(
        'User',
        {
            email: {
                type: DataTypes.STRING,
                unique: true,
                allowNull: true
            }
        }
)
```

```sql
CREATE UNIQUE INDEX Index_Name ON TableName(ColumnName)
WHERE ColumnName IS NOT NULL
```
Example: 
```sql
CREATE UNIQUE INDEX Users_email_unique ON Users(email)
WHERE email IS NOT NULL
```

__Dialect:__ mssql
__Dialect version:__ sql server 2017
__Sequelize version:__ 4.37.7
__Tested with latest release:__ Yes (If yes, specify that version)

If you are OK with it. I can create a PR.

**Comment by sushantdhiman** [comment]
I can accept a PR with this change :)

**Comment by sushantdhiman** [comment]
Hmm, I misunderstood this issue at first, yeah indexes with conditions are supported. With `createTable` you can pass `uniqueKeys` (Please also refer to this issue https://github.com/sequelize/sequelize/issues/9041)
