### ISSUE TITLE
findAndCountAll fails when "where" contains conditions related to associations

### ISSUE THREAD

**Issue by joakimbeng** [sequelize/sequelize#944]
As for now (v.2.0.0-beta.0) the `findAndCountAll` removes the "include" key from the options hash for the count query, and therefor when the "where" conditions contains a condition related to an association, it fails.

**Example:**

When I execute:

``` javascript
User.findAndCountAll({include: [Role], where: ["Roles.name = ?", "administrator"]})
```

I get:

```
Error: ER_BAD_FIELD_ERROR: Unknown column 'Roles.name' in 'where clause'
```

Because the generated sql is as follows:

``` sql
SELECT count(*) as `count` FROM `Users` WHERE Roles.name = 'administrator'
```

This is quite annoying, because I like the convenience of the `findAndCountAll` method, but this makes it useless for a lot of common queries.

**Comment by noisyneuron** [comment]
Is there a way to specify what to count with findAndCountAll? The behaviour I need is what was problematic for OP - I want to use findAndCountAll with an include, but only count the parent model. Possible with this function?

**Comment by mickhansen** [comment]
@noisyneuron it should only count the parent by default.

**Comment by noisyneuron** [comment]
Seems to be an issue then... if an include is present, it returns count of all children. I have an `Artist` model which has children `Paintings`.  I am trying to do something like this: 
```javascript
db.Artist.findAndCountAll({include: [ db.Painting ]})
    .then(function(result) {
         console.log(result.count);
    })
```
This is the SQL query generated:
```sql
SELECT COUNT(`Artist`.`id`) AS `COUNT` FROM `Artists` AS `Artist` LEFT OUTER JOIN `Paintings` AS `Paintings` ON `Artist`.`id` = `Paintings`.`ArtistId`;
```
