### ISSUE TITLE
add oracle support

### ISSUE THREAD

**Issue by ezequielzacca** [sequelize/sequelize#9442]
please this is the onle big database engine missing, i think sequelize is great and i've used it several times with really great developer experience, i dont see why you wouldnt support one of the biggest databases and one that is used by a lot of companies

**Comment by kaven276** [comment]
I wonder why sequelize do not support ORACLE too ?

**Comment by liangwenzhong** [comment]
I wonder why sequelize do not support ORACLE too ?

**Comment by Rakkoc** [comment]
I wonder why sequelize do not support ORACLE too ?

**Comment by ezequielzacca** [comment]
is there any update on this?
