### ISSUE TITLE
Order By with "customTable" Generate not  works!

### ISSUE THREAD

**Issue by rogeriomq** [sequelize/sequelize#9444]
```js
order.findAll({
    include: [
      { model: req.$models.user, required: true },
      { model: req.$models.client, required: true },
      {
        model: req.$models.productOrder,
        include: [ { model: req.$models.product } ]
      },
      { model: req.$models.accountReceive }
    ],
    where: {
      [Op.or]: {
        userId: {
          [Op.like]: `%${filter}%`
        },
        'clientId': {
          [Op.like]: `%${filter}%`
        }
      }
    },
    offset: limitOffset,
    limit: limitRows,
    order: [[`${sortBy}`, `${descending === 'true' ? 'DESC' : 'ASC'}`]],
    paranoid: isParanoid(req.query)
  })
```
ERROR:
When replacing 'updatedAt' by 'client.name', i have the below error:
TypeError: Cannot read property 'type' of undefined...

But if I run this SQL passing in the ordering 'client.name' works perfectly in MysqlWorkBench!

_Output, either JSON or SQL_
SELECT `order`.*,
       `productOrders`.`id` AS `productOrders.id`,
       `productOrders`.`orderId` AS `productOrders.orderId`,
       `productOrders`.`productId` AS `productOrders.productId`,
       `productOrders`.`quantity` AS `productOrders.quantity`,
       `productOrders`.`createdAt` AS `productOrders.createdAt`,
       `productOrders`.`updatedAt` AS `productOrders.updatedAt`,
       `productOrders`.`deletedAt` AS `productOrders.deletedAt`,
       `productOrders`.`valueUnt` AS `productOrders.valueUnt`,
       `productOrders`.`obs` AS `productOrders.obs`,
       `productOrders->product`.`id` AS `productOrders.product.id`,
       `productOrders->product`.`description` AS `productOrders.product.description`,
       `productOrders->product`.`billingType` AS `productOrders.product.billingType`,
       `productOrders->product`.`sts` AS `productOrders.product.sts`,
       `productOrders->product`.`createdAt` AS `productOrders.product.createdAt`,
       `productOrders->product`.`updatedAt` AS `productOrders.product.updatedAt`,
       `productOrders->product`.`deletedAt` AS `productOrders.product.deletedAt`,
       `productOrders->product`.`value` AS `productOrders.product.value`,
       `accountReceives`.`id` AS `accountReceives.id`,
       `accountReceives`.`orderId` AS `accountReceives.orderId`,
       `accountReceives`.`value` AS `accountReceives.value`,
       `accountReceives`.`dueDay` AS `accountReceives.dueDay`,
       `accountReceives`.`payDay` AS `accountReceives.payDay`,
       `accountReceives`.`valueReceive` AS `accountReceives.valueReceive`,
       `accountReceives`.`wayPayment` AS `accountReceives.wayPayment`,
       `accountReceives`.`discount` AS `accountReceives.discount`,
       `accountReceives`.`otherDiscount` AS `accountReceives.otherDiscount`,
       `accountReceives`.`tax` AS `accountReceives.tax`,
       `accountReceives`.`interest` AS `accountReceives.interest`,
       `accountReceives`.`amercement` AS `accountReceives.amercement`,
       `accountReceives`.`otherAddition` AS `accountReceives.otherAddition`,
       `accountReceives`.`obs` AS `accountReceives.obs`,
       `accountReceives`.`createdAt` AS `accountReceives.createdAt`,
       `accountReceives`.`updatedAt` AS `accountReceives.updatedAt`,
       `accountReceives`.`deletedAt` AS `accountReceives.deletedAt`,
       `accountReceives`.`sts` AS `accountReceives.sts`
FROM
  (SELECT `order`.`id`,
          `order`.`userId`,
          `order`.`clientId`,
          `order`.`obs`,
          `order`.`billedByDominio`,
          `order`.`textPrintOrder`,
          `order`.`createdAt`,
          `order`.`updatedAt`,
          `order`.`deletedAt`,
          `user`.`id` AS `user.id`,
          `user`.`fullName` AS `user.fullName`,
          `user`.`userName` AS `user.userName`,
          `user`.`pass` AS `user.pass`,
          `user`.`email` AS `user.email`,
          `user`.`fone1` AS `user.fone1`,
          `user`.`fone2` AS `user.fone2`,
          `user`.`type` AS `user.type`,
          `user`.`createdAt` AS `user.createdAt`,
          `user`.`updatedAt` AS `user.updatedAt`,
          `user`.`deletedAt` AS `user.deletedAt`,
          `client`.`id` AS `client.id`,
          `client`.`code` AS `client.code`,
          `client`.`name` AS `client.name`,
          `client`.`fantasyName` AS `client.fantasyName`,
          `client`.`cpfCnpj` AS `client.cpfCnpj`,
          `client`.`type` AS `client.type`,
          `client`.`place` AS `client.place`,
          `client`.`district` AS `client.district`,
          `client`.`adjunct` AS `client.adjunct`,
          `client`.`city` AS `client.city`,
          `client`.`zipCode` AS `client.zipCode`,
          `client`.`fone1` AS `client.fone1`,
          `client`.`fone2` AS `client.fone2`,
          `client`.`numAgreement` AS `client.numAgreement`,
          `client`.`email` AS `client.email`,
          `client`.`createdAt` AS `client.createdAt`,
          `client`.`updatedAt` AS `client.updatedAt`,
          `client`.`deletedAt` AS `client.deletedAt`
   FROM `order` AS `order`
   INNER JOIN `user` AS `user` ON `order`.`userId` = `user`.`id`
   AND (`user`.`deletedAt` > '2018-05-16 17:38:07'
        OR `user`.`deletedAt` IS NULL)
   INNER JOIN `client` AS `client` ON `order`.`clientId` = `client`.`id`
   AND (`client`.`deletedAt` > '2018-05-16 17:38:07'
        OR `client`.`deletedAt` IS NULL)
   WHERE ((`order`.`deletedAt` > '2018-05-16 17:38:07'
           OR `order`.`deletedAt` IS NULL)
          AND (`order`.`userId` LIKE '%%'
               OR `order`.`clientId` LIKE '%%'))
   ORDER BY `order`.`updatedAt` ASC
   LIMIT 0,
         10) AS `order`
LEFT OUTER JOIN `productOrder` AS `productOrders` ON `order`.`id` = `productOrders`.`orderId`
AND (`productOrders`.`deletedAt` > '2018-05-16 17:38:07'
     OR `productOrders`.`deletedAt` IS NULL)
LEFT OUTER JOIN `product` AS `productOrders->product` ON `productOrders`.`productId` = `productOrders->product`.`id`
AND (`productOrders->product`.`deletedAt` > '2018-05-16 17:38:07'
     OR `productOrders->product`.`deletedAt` IS NULL)
LEFT OUTER JOIN `accountReceive` AS `accountReceives` ON `order`.`id` = `accountReceives`.`orderId`
AND (`accountReceives`.`deletedAt` > '2018-05-16 17:38:07'
     OR `accountReceives`.`deletedAt` IS NULL)
ORDER BY `order`.`updatedAt` ASC;

__Dialect:__ mysql2 
__Dialect version: 1.5.3
__Database version: 5.7.22
__Sequelize version: 4.37.6
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Looks like `${sortBy}` is undefined but I have no way to confirm this. Please isolate your issue from userland code so it can be tested by others. Follow the issue template, present your problem as SSCCE

----------------------------
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by sushantdhiman** [comment]
# CAN YOU SHOW ME AN SSCCE AS I ASKED BEFORE!!!!
