### ISSUE TITLE
TypeError: "sequelize" is not a constructor while compilingTypescript for ES6 target

### ISSUE THREAD

**Issue by TitaneBoy** [sequelize/sequelize#9447]
## What are you doing?
Trying to compile an es5 typescript project code to es6. But when starting the node project, it fails a the creation of sequelize object instance. I'm using babel-register in order to be able to compile on es6 target

Sequelize version: "4.37.7"
NodeJS version: 8.11.1 & 10.1.0
vscode version: 1.23.1

**Dev Dependencies:**
![image](https://user-images.githubusercontent.com/15614466/40200671-f303f530-59ea-11e8-8ea6-857562498b18.png)

**Here is my tsconfig.json compiler options:**

![image](https://user-images.githubusercontent.com/15614466/40200724-08625854-59eb-11e8-8115-04da00829634.png)

**Here is my launch.json configuration**
![image](https://user-images.githubusercontent.com/15614466/40200809-3ef0c95a-59eb-11e8-82cf-57b8b48a55ce.png)

Here's my typescript code where it fails.

```
import * as path from 'path';
import * as sequelize from 'sequelize';
import { LimitsName, Measurement, Units } from './../types/measurements';
import { IResumeReadings } from './../types/resume.readings';
import { AlarmType, AlarmValue, IStatusAlarm } from './../types/status.alarm';
import { IStatusIO } from './../types/status.ios';
import { IStatusReadings } from './../types/status.readings';
import { IStatusRelays, RelayAction, RelayCondition, RelayConditionState } from './../types/status.relays';

let Sequelizer: sequelize.Sequelize = null;
let readingsData: IResumeReadings[];

function LocalSequelize(): sequelize.Sequelize {
  const postgresqlDatabaseUrl = 'postgres://postgres:postgres@localhost:5432/calisto_cortex';

  if (Sequelizer == null) {
    Sequelizer = new sequelize(
      postgresqlDatabaseUrl,
      {define: {timestamps: false}, logging: false, operatorsAliases: false});
  }
  return Sequelizer;
}
```

## What do you expect to happen?
I expect that sequelize does not crash when debugging with es6 target

## What is actually happening?

It shows a type error saying that "sequelize" is not a constructor

![image](https://user-images.githubusercontent.com/15614466/40200440-481a3b48-59ea-11e8-920e-9c011d3f1a9a.png)

__Dialect:__ postgres 
__Sequelize version:__ 4.37.7

**Comment by lomby92** [comment]
Try to use *sequelize* as a function:

```typescript
import * as sequelize from "sequelize";

Sequelizer = sequelize(
      postgresqlDatabaseUrl,
      {define: {timestamps: false}, logging: false, operatorsAliases: false}
);
```

**Comment by TitaneBoy** [comment]
@lomby92 ... Thanks for your answer and sorry for the delay...

When I try to use sequelize as a function, I have a typescript error issue as you can see below:

![image](https://user-images.githubusercontent.com/15614466/44366790-e265ab00-a49b-11e8-936a-339837296316.png)

And when trying to execute it, it gives me another error: "sequelize is not a function", as you can see below

![image](https://user-images.githubusercontent.com/15614466/44366937-48523280-a49c-11e8-9529-67868a691afe.png)
