### ISSUE TITLE
Invalid MSSQL Fetch/Next Queries

### ISSUE THREAD

**Issue by chriseaton** [sequelize/sequelize#9448]
## What are you doing?
Trying to query a table in SQL Server 2014 with paging (limit + offset).
This seems to be the same issue @stefanobider was calling out in issue #4404, but that bug was closed (never fixed?)

*Note: ID is the PK of table Users.*
```
findAndCountAll({
  limit: 5,
  offset: 0,
  order: [ [ 'ID', 'ASC' ] ]
})
```
generates this invalid sql:
```
SELECT [User].[ID], [User].[RoleID], [User].[FirstName], [User].[LastName], [User].[Email], [User].[Title], [User].[Department], [User].[ADUserName], [User].[Photo], [User].[DateCreated], [User].[DateUpdated], [User].[DateDeleted], [Role].[ID] AS [Role.ID], [Role].[Name] AS [Role.Name], [Role].[Admin] AS [Role.Admin] FROM [Users] AS [User] LEFT OUTER JOIN [Roles] AS [Role] ON [User].[RoleID] = [Role].[ID] AND ([Role].[DateDeleted] > N'2018-05-17 23:46:46.232 +00:00' OR [Role].[DateDeleted] IS NULL) WHERE (([User].[DateDeleted] > N'2018-05-17 23:46:46.232 +00:00' OR [User].[DateDeleted] IS NULL) AND ([User].[ID] = N'1')) 
ORDER BY [User].[ID] ASC, [User].[ID] OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
```
Specifically, the "ASC, __[User].[ID]__ OFFSET" is not valid.
```
SequelizeDatabaseError: A column has been specified more than once in the order by list. Columns in the order by list must be unique.
```
^ The above shouldn't happen, as I am not specifying that column to sort twice. For some reason, the inclusion of limit and offset adds the PK column name before the OFFSET statement.

If I remove the sort option, it still generates invalid SQL, as SQL needs the ORDER BY clause to do the fetch/next but it is not placed in the generated query (see near end of query):
```
SELECT [User].[ID], [User].[RoleID], [User].[FirstName], [User].[LastName], [User].[Email], [User].[Title], [User].[Department], [User].[ADUserName], [User].[Photo], [User].[DateCreated], [User].[DateUpdated], [User].[DateDeleted], [Role].[ID] AS [Role.ID], [Role].[Name] AS [Role.Name], [Role].[Admin] AS [Role.Admin] FROM [Users] AS [User] LEFT OUTER JOIN [Roles] AS [Role] ON [User].[RoleID] = [Role].[ID] AND ([Role].[DateDeleted] > N'2018-05-17 23:54:47.022 +00:00' OR [Role].[DateDeleted] IS NULL) WHERE (([User].[DateDeleted] > N'2018-05-17 23:54:47.022 +00:00' OR [User].[DateDeleted] IS NULL) AND ([User].[ID] = N'1')), [User].[ID] OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
```

```
SequelizeDatabaseError: Invalid usage of the option NEXT in the FETCH statement.
```

## What do you expect to happen?
The query to run without failing.

## What is actually happening?
The query fails differently depending on whether I include a sort of the PK or not.
```
SequelizeDatabaseError: A column has been specified more than once in the order by list. Columns in the order by list must be unique.
```

```
SequelizeDatabaseError: Invalid usage of the option NEXT in the FETCH statement.
```

If I include a sort of any other column, *other* than the PK, it works ok.

__Dialect:__ mssql
__Dialect version:__ tedious 2.3.1
__Database version:__ 13.0.5026.0 MS SQL2014 SP2
__Sequelize version:__ 4.37.7
__Tested with latest release:__ Yes 4.37.7

**Comment by chriseaton** [comment]
Heyo!!! Solved it. Here's the resolution:

In js, an empty array is truthy - and so the ternary check in /dialects/mssql/query-generator.js:896 will actually return true when options.order equals an empty array.
```
fragment += options.order && !isSubQuery ? ', ' : ' ORDER BY ';
```
Given that the spec allows arrays, I think we just need to up the logic on this check to include an
```
(Array.isArray(options.order) && options.order.length) || (!Array.isArray(options.order) && options.order)
```
to account for empty arrays.

If I can I'll make a pull request soon for this update. In the interim, anyone facing this problem can eliminate it by simply not setting a query functions option "order" property with an empty array.

**Comment by lerit** [comment]
@chriseaton  i face this problem for a long time,and I'd appreciate it if you could give a pull request and fix it :)

**Comment by markablov** [comment]
fixes duplication of PK in order clause - https://github.com/sequelize/sequelize/pull/9936

**Comment by swimclan** [comment]
@markablov thank you for your comment `// for MSSQL` you saved me many many many hours of pain.  Cheers!

**Comment by dsbert** [comment]
I'm seeing a similar error even when I do pass in a non-empty array.

In this example, I'm sorting on an associated column
```
    const data = await model.findAndCountAll({
      order: order, // [['otherModel', 'dateField', 'desc']]
      include: [
        {
          model: db.otherModel,
        }
      ]
    });

// Results in 
// ... 
// ORDER BY [otherModel].[dateField] DESC 
// ORDER BY [model].[id] 
// OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

```
