### ISSUE TITLE
password leaking on error message

### ISSUE THREAD

**Issue by peecky** [sequelize/sequelize#9456]
## What are you doing?

```js
    const model = sequelize.define('_temp_event_item', {
        event_id: {
            type: Sequelize.BIGINT,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
        },
        item_id: {
            type: Sequelize.BIGINT,
                allowNull: false
        }
    }, {
        timestamps: false
    });

    try {
        const item_id = 2, event_id = 1;
        await sequelize.transaction(async (transaction) => {
            // await model.update({ item_id }, { where: { event_id }, transaction }); // what I intended
            await model.update({ item_id }, { where: { event_id, transaction } }); // what I actually do
        });
    }
    catch(e) {
        console.error(e.message); // print Database password
    }
```

## What do you expect to happen?
An error message that does not contains the database password.

## What is actually happening?
Due to a small typo, an error is occurred. The error message (also the JavaScript error object) contains the database password. We are using remote logging systems to log errors. Therefore the password also sent to that systems.

example of output:
```
Invalid value Transaction {
  sequelize: 
   Sequelize {
     options: 
      { dialect: 'mysql',
        dialectModulePath: null,
        ... blah blah ...
      },
     config: 
      {
        ... blah blah ...
        username: <db username>,
        password: <db password>,
        ... blah blah ...
      },
     ... blah blah ...
```

__Dialect:__ mysql
__Dialect version:__ mysql2@1.5.3
__Database version:__ 5.7.17
__Sequelize version:__ 4.37.8
__Tested with latest release:__ No (If yes, specify that version)

**Comment by eseliger** [comment]
In my opinion, the code should have never gotten into an environment, where remote logging occurs, because this could easily have been catched by a test and I think it is not the frameworks concern to watch out what the consumer of the API feeds into it

**Comment by sushantdhiman** [comment]
```Invalid value Transaction {``` 

It must have occurred when you accidentally passed transaction to `where` option. I think I agree with @eseliger simple test case should have caught this.

This wont happen for every error but only for one specific case where where value is passed with something that has reference to `sequelize` instance.

But in real world, as per my experience, there are MANY projects without any sort of tests. I think we should either set `depth` parameter to https://github.com/sequelize/sequelize/blob/efb1f2f40ff393188c9dd0ab6dc692d18b5b4fef/lib/sql-string.js#L66 to may be `2` OR replace password from final error string OR may be both.

Thoughts?

**Comment by Jolg42** [comment]
@sushantdhiman 

I had this issue as well and I think not leaking the database URI (including password) would be a better default.
Because even if it's not sent to a remote it will be in the logs and once it leaked on a production db the password should be changed asap.

My guess is that a lot of people won't see it leaking or too late so if we can say that sequelize doesn't leak by default that's better for everybody and it is the assumed default for me.

What do you think?

**Comment by sushantdhiman** [comment]
As I suggested earlier we can set inspect depth so we are not logging whole sequelize object, that will prevent logging password for most cases. I'll accept a PR with that change.

**Comment by dsullivan7** [comment]
Was there any update on this issue? I ran into this recently and find it a very serious security issue. I would assume logging the error message and even returning an error message to the relevant client to be fairly standard.
