### ISSUE TITLE
Postgress Raw query type cast issue

### ISSUE THREAD

**Issue by karankapur999** [sequelize/sequelize#9460]
## What are you doing?

I am trying to run a sequalize raw Query for postgress databse

var queryToCheckConflicts = "select * from appointment_details where business_id =:businessId  and line_type='Appointment' and \"local_start_time\"::TIME BETWEEN (:startTime  - interval ':bufferHoursStart hours') and (:startTime  + interval ':serviceDuration hours')  and date in(:dateArray) and assigned_id = (:assignedId) LIMIT 10000;" ;
    
      return global.sequelize.query(queryToCheckConflicts, { replacements: { businessId: businessId, startTime: appointmentLocalStartTime, bufferHoursStart: bufferHoursStart, serviceDuration: hoursForServiceDuration, dateArray: arrayOfDates, assignedId: staffId }, type: sequelize.QueryTypes.SELECT }).then(results => { })

The Query in consoles when ran using postico on postgress is running fine

select * from appointment_details where business_id =187  and line_type='Appointment' and "local_start_time"::TIME BETWEEN ('13:35'  - interval '0 hours') and ('13:35'  + interval '1 hours')   and assigned_id = ('316') LIMIT 10000;

But sequelize giving following error

            "name": "SequelizeDatabaseError",
            "message": "syntax error at or near \" \"",
            "parent": {
                "name": "error",
                "length": 85,
                "severity": "ERROR",
                "code": "42601",
                "position": "133",
                "file": "scan.l",
                "line": "1054",
                "routine": "scanner_yyerror",
                "sql": "select * from appointment_details where business_id =187  and line_type='Appointment' and \"local_start_time\"::TIME BETWEEN ('13:35'  - interval '0 hours') and ('13:35'  + interval '1 hours')   and assigned_id = ('316') LIMIT 10000;"

 

```js
// code here
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Does this query works when you directly run with pg connector (ie `node-postgres`)

**Comment by karankapur999** [comment]
@sushantdhiman I have tried running directly on postgress  . It worked perfectly fine their!

**Comment by sushantdhiman** [comment]
No, I meant `node-postgres` the client library, not cli or postios.

**Comment by sushantdhiman** [comment]
https://github.com/brianc/node-postgres , this is what used by Sequelize to connect with Postgres database server and execute various queries.

To ensure this bug is indeed related to Sequelize you have to try execute that same query using `node-postgres` bare setup and see if that works.

Some related issues

- https://github.com/sequelize/sequelize/issues/9414
- https://github.com/sequelize/sequelize/issues/9408

**Comment by karankapur999** [comment]
@sushantdhiman 

Same error with node-postgress


Building DB Indexes !!!!!
{ error: syntax error at or near " "
    at Connection.parseE (/Users/karankapur/Desktop/beagle-backend/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/karankapur/Desktop/beagle-backend/node_modules/pg/lib/connection.js:366:17)
    at TLSSocket.<anonymous> (/Users/karankapur/Desktop/beagle-backend/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)
  name: 'error',
  length: 85,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '151',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1054',
  routine: 'scanner_yyerror' } undefined

**Comment by sushantdhiman** [comment]
So not related to Sequelize. But odd problem, several other users has reported similar issues.

Are you using some special encoding or special parameters when connecting to Postgres via CLI (or GUI) that is missing during. Using SSL etc? May I see your connection string :D

**Comment by karankapur999** [comment]
const client = new Client({
  user: 'user',
  host: 'IP.compute-1.amazonaws.com',
  database: 'name',
  password: 'Pass',
  port: 5432,
  ssl : {
    rejectUnauthorized : false
  }
})
client.connect()

client.query("select date,local_start_time from appointment_details where business_id = 187 and line_type='Appointment' and local_start_time::TIME BETWEEN ('01:15'  - interval '10 hours') and ('01:15'  + interval '0.5 hours')   and assigned_id in (316) LIMIT 10000", (err, res) => {
  console.log(err, res)
  client.end()
})

**Comment by karankapur999** [comment]
@sushantdhiman how should i proceed now ?

**Comment by sushantdhiman** [comment]
Not sure, If you can leave more info about database setup in details I will try to replicate this issue later on if I get some free time

**Comment by karankapur999** [comment]
client.query("select * from appointment_details where business_id =187  and line_type='Appointment' and CAST (local_start_time AS TIME) BETWEEN ('13:35'  - interval '0 hours') and ('13:35'  + interval '1 hours')   and assigned_id = ('316') LIMIT 10000;", (err, res) => {


This Query also failing !

**Comment by karankapur999** [comment]
@sushantdhiman i have tried with 2 different db (with different setup ) same error in both
