### ISSUE TITLE
new Buffer deprecation warning in Node.js v10+

### ISSUE THREAD

**Issue by dwjft** [sequelize/sequelize#9464]
## What are you doing?

Simply import `sequelize` in a Node.js v10+ environment and you will trigger the deprecation warning.

```js
import * as Sequelize from 'sequelize';
```

## What do you expect to happen?

No warning.

## What is actually happening?

```
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

https://github.com/sequelize/sequelize/search?utf8=%E2%9C%93&q=%22new+Buffer%22&type=

The above search shows a bunch of the instances / occurrences of `new Buffer`.

**Comment by caiquecastro** [comment]
I think it's a good first issue. In most cases, it's a simple find/replace by Buffer.from(value).

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/commit/c3b65136d332a63165a4ac21f6a81335752d0f02
