### ISSUE TITLE
Double save() creates double records

### ISSUE THREAD

**Issue by homakov** [sequelize/sequelize#9465]
```
var p=Payment.build({invoice: 123})
for(i=0;i<100;i++){
  p.save()
}
```

Would create 100 payment records but the intent here is obviously to save it once. I wonder about a way to prevent it with a patch or fix it in the core? Seems like nothing to lose and way to prevent race conditions.

The first save() must put some kind of a lock on saving it again and only unlock after obtaining the newly created record id.

**Comment by sushantdhiman** [comment]
Use `findOrCreate` OR you can put unique constraint on values passed to `build`. If you perform two or more async create operation then its database server best suited to handle race conditions.
