### ISSUE TITLE
Setting the unique property on the column definitions does not create an unique index

### ISSUE THREAD

**Issue by ivanquirino** [sequelize/sequelize#9475]
This piece of the documentation is misleading:
```javascript
// The unique property is simply a shorthand to create a unique constraint.
 someUnique: { type: Sequelize.STRING, unique: true },

 // It's exactly the same as creating the index in the model's options.
 { someUnique: { type: Sequelize.STRING } },
 { indexes: [ { unique: true, fields: [ 'someUnique' ] } ] },
```
Because in postgres setting only the unique property at the column only creates the unique constraint, does not create an index. Declaring an index will create and index, but will not create a constraint

**Comment by ephys** [comment]
According to postgres' documentation:

> Adding a unique constraint will automatically create a unique B-tree index on the column or group of columns listed in the constraint

https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS
