### ISSUE TITLE
Sequelize findAndCountAll returns wrong count

### ISSUE THREAD

**Issue by tumdav** [sequelize/sequelize#9477]
When I'm adding more then one include models sequelize returns count of root table rows plus associated tables' rows count.

Sequelize version : 4.37.8
Dialect : postqre

Please don't mark issue as an duplicate:I  have read all related bugs,issues and topics.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by ArtashMardoyan** [comment]
+1

**Comment by alixanyan** [comment]
some

**Comment by anidav** [comment]
+1

**Comment by gevkhanyan** [comment]
some

**Comment by Anubis91** [comment]
Yeah it's still problem

**Comment by lianatumikyan** [comment]
+1

**Comment by rhanesoghlyan** [comment]
some +1

**Comment by Mariam13** [comment]
+1

**Comment by GhValentina** [comment]
+1 Anyone can help solve this problem,Please!

**Comment by Anush17** [comment]
I have the same problem, Please fix it !

**Comment by sushantdhiman** [comment]
Issue is closed because you refused to follow issue template, how I am supposed to help you when you wont help me?

**Comment by Notifium** [comment]
@tumdav 
Just a though, have you tried the following?

```
const posts = Post.findAndCountAll({
    include: ['attachment', 'users', 'x count of models'],
    distinct: 'id'
});
```


Andy

**Comment by KobzarDenis** [comment]
@sushantdhiman You are fuc*ing foolish !! This issue must be fixed already !! Go fuc*ing out of the project if you can't fix this bug so many years !!

**Comment by calmdev** [comment]
Begging choosers with salty attitudes are the true fools. Especially those with barely any activity demanding things from project maintainers.

**Comment by leouze** [comment]
+1 having the same issue

**Comment by davidadas** [comment]
Why is this closed?

**Comment by rajeman** [comment]
+1

**Comment by SysOpsNet** [comment]
+1
