### ISSUE TITLE
Raw Queries - $bind no longer working in sequelize 4 with IN(array)

### ISSUE THREAD

**Issue by nawlbergs** [sequelize/sequelize#9479]
## What are you doing?
While upgrading to 3 to 4, I found the raw query $bind method no longer works for IN([]):
http://docs.sequelizejs.com/manual/tutorial/raw-queries.html

Maybe the documentation is not updated... but something has changed and I'm having issues getting it to work. 

I googled around and any similar issues were very old (2014/15):
 - https://github.com/sequelize/sequelize/issues/8140  (is postgres issue... and the ANY() workaround does not work for me in mysql)

This is an extremely simplified version of my query:
```js
let query = 'SELECT id FROM users WHERE userId IN($userIds);'  // WONT WORK
let query = 'SELECT id FROM users WHERE userId $userId;'       // WORKS

let bindings = {
    userIds: ['foo123', 'bar123'],
    userId: 'foobar321'
}

return sequelize.query(query, {
    type: sequelize.QueryTypes.SELECT,
    bind: bindings
})
```

NOTE: If I switch from using bind to replacements... it does work.
```js
let query = 'SELECT id FROM users WHERE userId IN(:userIds);'  // THIS WILL WORK
return sequelize.query(query, {
    type: sequelize.QueryTypes.SELECT,
    replacements: bindings
})
```

## What do you expect to happen?
An array of users to be returned.

## What is actually happening?
An empty array is returned.  No error.

_Output, either JSON or SQL_
```
(logging:console.log)
Executing (default): SELECT id FROM users WHERE userId IN(?)
```

__Dialect:__ mysql
__Dialect version:__ 5.7.16
__Sequelize version:__ "4.37.8"

**Comment by sushantdhiman** [comment]
Under v3 MySQL never supported "bind", they were actually replacements under the hood. Only Postgres and SQLite did supported real bind in v3.

So when you were using bind in v3, it was replacing actual values in query like this

```js
sequelize.query('SELECT id FROM users WHERE userId IN ($userIds)', {
      type: sequelize.QueryTypes.SELECT,
      replacements: {
        userIds: ['foo123', 'bar123'],
        userId: 'foo123'
      }
});

Executing (default): SELECT id FROM users WHERE userId IN ('foo123','bar123')
[ { id: 1 }, { id: 2 } ]
```

You can confirm this by logging your queries.

With v4 Sequelize now got real MySQL "bind" support (I think all dialects support bind now).

AFAIK there is no way to bind list to `IN` for MySQL at least, you will have to either use replacements or generate `n` parameters for `IN($1, $2, ...)` manually

**Comment by nawlbergs** [comment]
Thank you for the response - we love this library.
I might suggest this gets added to the upgrade guide as a breaking change... its very breaking.
:)

**Comment by sushantdhiman** [comment]
Guide was updated and I have added a section on raw queries with this change information https://github.com/sequelize/sequelize/commit/ec7c474028e7a2a4b4e10b48e8109e23fbfb1fb3
