### ISSUE TITLE
getters do not run on model.get( { raw:true } )

### ISSUE THREAD

**Issue by nawlbergs** [sequelize/sequelize#9480]
## What are you doing?
Im am upgrading from version 3 to 4 using the upgrade guide.
Trying to get a raw/plain object from the model instance after a query.

--THIS might just be an issue missing from upgrade guide--

```js
getterMethods:{
    // gets the best name possible for a user
    displayName:function(){
        if(this.getDataValue('email'))          
           return this.getDataValue('email');
        // if all else fails return userId
        return this.getDataValue('userId');
    }
}

```
After a query... we would often convert user into a plain object:
```js
userInResponse.get( { raw:true } )
```

NOTE: 
```js
// seems to be what we want now but nothing is mentioned in upgrade guide.
userInResponse.get( { plain:true } ) 
```

## What do you expect to happen?
displayName to have a value.

## What is actually happening?
displayName is undefined and did not run.

_Output, either JSON or SQL_
```js
displayName:undefined
email:"test@test.com"
firstName:"testFirstName"
...
```

__Dialect:__ mysql
__Database version:__ 5.7.16
__Sequelize version:__ "4.37.8"

**Comment by sushantdhiman** [comment]
Added this to guide https://github.com/sequelize/sequelize/commit/ec7c474028e7a2a4b4e10b48e8109e23fbfb1fb3
