### ISSUE TITLE
built-in type validators missing useful information

### ISSUE THREAD

**Issue by contra** [sequelize/sequelize#9488]
## What are you doing?

We expect to be able to return useful validation errors for our API users/UI to understand - to do so we need the field name the error is for. With custom validation errors, we get that information and can use it to highlight fields in the UI - with any core type, we get no information other than the value that failed. It would be extremely useful if all validation errors were the same, no matter if it was a core type or custom type. If you agree I can send a PR shortly since this is a pretty easy fix.

```js
Model.validate({ id: '1234' })
```

## What do you expect to happen?

An error resembling other validation errors, complete with an `errors` array, each item containing `validatorKey`, `path`, `value`, and `message`.

## What is actually happening?

The only information in the error is the `message` attribute:
```
"1234" is not a valid uuid
```

__Dialect:__ any
__Sequelize version:__ 5.x
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Good idea

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/9660
