### ISSUE TITLE
Please install mysql2 package manually

### ISSUE THREAD

**Issue by wuxiaolan91** [sequelize/sequelize#9489]
## What are you doing?
when I run 'node app.js' ,throw error 'new Error('Please install mysql2 package manually');'
but i'm installed mysql2.
my local client haven't this problem, just my ubuntu 14 server have it.

```js
You must set the NODE_ENV environment variable
/home/www/test/tougao-server/node_modules/_sequelize@4.37.10@sequelize/lib/dialects/mysql/connection-manager.js:38
        throw new Error('Please install mysql2 package manually');
        ^

Error: Please install mysql2 package manually
    at new ConnectionManager (/home/www/test/tougao-server/node_modules/_sequelize@4.37.10@sequelize/lib/dialects/mysql/connection-manager.js:38:15)
    at new MysqlDialect (/home/www/test/tougao-server/node_modules/_sequelize@4.37.10@sequelize/lib/dialects/mysql/index.js:14:30)
    at new Sequelize (/home/www/test/tougao-server/node_modules/_sequelize@4.37.10@sequelize/lib/sequelize.js:239:20)
    at Object.<anonymous> (/home/www/test/tougao-server/controllers/adController.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/www/test/tougao-server/router/ad.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/www/test/tougao-server/router/index.js:37:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/www/test/tougao-server/router/index.js:36:4)

```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql
__Database version:_5.5.60
__Sequelize version: 4.37.10
__Tested with latest release: no

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Try removing your `node_modules` folder then make sure both dependencies are installed locally. I am closing this issue as it seems to be a dependency issue, feel free to comment if it still doesn't works.

**Comment by pasha1307** [comment]
..I am having the same issue with the error  when try to run db:migrate
Sequelize CLI [Node: 11.2.0, CLI: 5.3.0, ORM: 4.41.2] Loaded configuration file "config/config.json".
Using environment "development".
ERROR: Please install mysql2 package manually.
Tried all the above and more - does not help. Is there any explanation why and how to fix it?

**Comment by vmarushkoossystem** [comment]
Hi!

Try to understand real trouble. You need to find the following code and add `console.log()` for displaying error's description:

File: `node_modules/sequelize/lib/dialects/mysql/connection-manager.js`

Place:

```
class ConnectionManager extends AbstractConnectionManager {
  constructor(dialect, sequelize) {
    super(dialect, sequelize);

    this.sequelize = sequelize;
    this.sequelize.config.port = this.sequelize.config.port || 3306;
    try {
      if (sequelize.config.dialectModulePath) {
        this.lib = require(sequelize.config.dialectModulePath);
      } else {
        this.lib = require('mysql2');
      }
    } catch (err) {
// HERE!!! ---^
      if (err.code === 'MODULE_NOT_FOUND') {
        throw new Error('Please install mysql2 package manually');  // <--- It is not real error that you get!
      }
      throw err;
    }

    this.refreshTypeParser(DataTypes);
  }
```
After that you will be able to understand what is actually happened.

**Comment by catamphetamine** [comment]
If you're bundling with Webpack, my workaround for `v5` is:

```js
// Fix "Please install mysql2 package manually".
import mysql2 from 'jitu/node_modules/mysql2';
if (options.dialect === 'mysql') {
  options.dialectModule = mysql2;
}
new Sequelize(options)
```

**Comment by arielrahmane** [comment]
@catamphetamine I'm sorry if it is a rookie question, but in which file should I place that correction? 

> ```js
> // Fix "Please install mysql2 package manually".
> import mysql2 from 'mysql2';
> if (options.dialect === 'mysql') {
>   options.dialectModule = mysql2;
> }
> new Sequelize(options)
> ```

**Comment by MaximusMcCann** [comment]
@arielrahmane wherever you import sequelize you can set the `dialectModule` in the options.  Example below.
```
import Sequelize from 'sequelize';
import mysql2 from 'mysql2'; // Needed to fix sequelize issues with WebPack

const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    dialect: 'mysql',
    dialectModule: mysql2, // Needed to fix sequelize issues with WebPack
    host: process.env.DB_HOST,
    port: process.env.DB_PORT
  }
)

export async function connectToDatabase() {
  console.log('Trying to connect via sequelize')
  await sequelize.sync()
  await sequelize.authenticate()
  console.log('=> Created a new connection.')

  // Do something 
}

```

**Comment by nahumzs** [comment]
The previous solution works correctly from MySql, but for Postgres is not working. I was able to go passed the `Please install pg package manually` error, and got stuck with an error complying about `undefined of indexOf`.

Because I'm trying to use sequelize and serverless for a prototype, I changed my db selection to mysql, and simply move forward.

**Comment by CovertIII** [comment]
I got this working with Postgres. As noted above use the `dialectModule` option when initializing Sequelize v5 like so:

```
const Sequelize = require('sequelize');
const pg = require('pg');

const sequelize = new Sequelize(process.env.DATABASE_URL, {
  dialectModule: pg
});

module.exports = sequelize;
```

To get past the `undefined of indexOf` error add this to the webpack config: 
```
  plugins: [new webpack.IgnorePlugin(/\.\/native/, /\/pg\//)]
```
See these related issues: 
https://github.com/brianc/node-postgres/issues/1187
https://github.com/serverless-heaven/serverless-webpack/issues/78

**Comment by benbowler** [comment]
I had this issue deploying to now.sh and was able to fix to add this dialectModule option directly in my Sequalize config:

```
const config = {
  username: process.env.DATABASE_USERNAME,
  password: process.env.DATABASE_PASSWORD,
  database: process.env.DATABASE_NAME,
  host: process.env.DATABASE_HOST,
  dialect: "mysql",
  dialectModule: "mysql2"
};
```

**Comment by valentinho27** [comment]
in my case i use it !

add

const mysql2 = require('mysql2');

"development": {
    "username": DB_USERNAME,
    "password": DB_PASS,
    "database": DB_NAME,
    "host"    : DB_HOST,
    "dialect" : "mysql",
    "dialectModule" : mysql2 // Needed to fix sequelize issues

  }

**Comment by knowself** [comment]
I was working through the Apollo GraphQL Tutorial ... https://www.apollographql.com/docs/tutorial/introduction/

... and ran into a brick wall until I did this ...

==============================
const {Sequelize} = require('sequelize');
const {sqlite} = require('sqlite3'); // Needed to fix sequelize issues with WebPack

module.exports.paginateResults = ({
.
.
.
module.exports.createStore = () => {
  const db = new Sequelize({
    dialect: 'sqlite',
    dialectModule: sqlite, // Needed to fix sequelize issues with WebPack
    storage: './store.sqlite'
  });
.
.
.
==============================

Dead in the water until this post ... Thanks!!!

**Comment by papb** [comment]
Hello, I will concentrate all efforts involving Webpack problems in this new issue: #13169 - Please help me there if possible.

**Comment by Sky-walker-only** [comment]
`npm install mysql2 --global`,    `npm install mysql2 --save`;  it's done;

**Comment by Mnabawy** [comment]
npm install --save mysql2

**Comment by SumitJadiya** [comment]
> npm i sequelize
> npm i mysql2
 
repeating above queries fixed my problem

**Comment by a-hamadneh** [comment]
> I had this issue deploying to now.sh and was able to fix to add this dialectModule option directly in my Sequalize config:
> 
> ```
> const config = {
>   username: process.env.DATABASE_USERNAME,
>   password: process.env.DATABASE_PASSWORD,
>   database: process.env.DATABASE_NAME,
>   host: process.env.DATABASE_HOST,
>   dialect: "mysql",
>   dialectModule: "mysql2"
> };
> ```

What happens when you add it?

**Comment by Kaleb11** [comment]
> I had this issue deploying to now.sh and was able to fix to add this dialectModule option directly in my Sequalize config:
> 
> ```
> const config = {
>   username: process.env.DATABASE_USERNAME,
>   password: process.env.DATABASE_PASSWORD,
>   database: process.env.DATABASE_NAME,
>   host: process.env.DATABASE_HOST,
>   dialect: "mysql",
>   dialectModule: "mysql2"
> };
> ```

**Comment by Kaleb11** [comment]
Correct! thank you man

**Comment by wildy13** [comment]
> mysql2

```
require('dotenv').config();

const Sequelize = require('sequelize');
const mysql2 = require('mysql2')
const sequelize = new Sequelize(
    process.env.DB_NAME,
    process.env.DB_USERNAME,
    process.env.DB_PASSWORD,
    {
        host : 'localhost',
        dialect : process.env.DB_DIALECT,
        dialectModule: mysql2,
        dialectOptions: {
            dateStrings: true,
            typeCast: true,
        },
        pool: {
            max: 10,
            min: 0,
            idle: 10000,
        },
          
    }
)

const config = {
    host : process.env.BACKEND_HOST,
    port : process.env.BACKEND_PORT,
    secret: { session: process.env.SESSION_KEY },
}

module.exports = { sequelize, config }
```

but I'm still error,
>Error: Please install mysql2 package manually

**Comment by moxinnai** [comment]
> If you're bundling with Webpack, my workaround for `v5` is:
> 
> // Fix "Please install mysql2 package manually".
> import mysql2 from 'mysql2';
> if (options.dialect === 'mysql') {
>   options.dialectModule = mysql2;
> }
> new Sequelize(options)
> The bug is in the code:
> 
>   _loadDialectModule(moduleName) {
>     try {
>       if (this.sequelize.config.dialectModulePath) {
>         return require(this.sequelize.config.dialectModulePath);
>       }
>       if (this.sequelize.config.dialectModule) {
>         return this.sequelize.config.dialectModule;
>       }
>       return require(moduleName);
> 
>     } catch (err) {
>       if (err.code === 'MODULE_NOT_FOUND') {
>         if (this.sequelize.config.dialectModulePath) {
>           throw new Error(`Unable to find dialect at ${this.sequelize.config.dialectModulePath}`);
>         }
>         throw new Error(`Please install ${moduleName} package manually`);
>       }
> 
>       throw err;
>     }
>   }
> `require(moduleName)` won't work with Webpack.

use import * as mysql2 from 'mysql2'  instead of import mysql2 from 'mysql2' 
is worked for me
