### ISSUE TITLE
Using Knex to manage dialects and build queries

### ISSUE THREAD

**Issue by snit-ram** [sequelize/sequelize#949]
Knex (http://knexjs.org/) is a query builder that supports the same dialects that sequelize supports.

I thing that sequelize can benefit a lot from using knex to build queries. This would remove a lot of code from sequelize, and remove the need of having dialect/adapter specific code in sequelize.

Sequelize could also benefit from any new dialect support that may be added in knex. Also, any new dialect implemented in sequelize, would actually be implemented in knex, tunelling the benefit for all knex consumers.

What do you guys think about it? I'm planning to contribute with a pull request for this change soon, but would like to know your opinion in advance.

Regards,
Snit

**Comment by franciscocardoso** [comment]
Hi,

Is there anyone thinking in revisiting this topic? Knex supports [pooling](http://knexjs.org/#Installation-pooling) as you can see and it would be great to have a query builder available.

**Comment by mickhansen** [comment]
@franciscocardoso Knex and Bookshelf have widely different styles, we'll likely look to support mongo-sql as a query builder instead.

**Comment by franciscocardoso** [comment]
Ok. Thanks for the quick reply @mickhansen.
