### ISSUE TITLE
Instance.changed() has keys with false intentionally?

### ISSUE THREAD

**Issue by markhealey** [sequelize/sequelize#9493]
## What are you doing?
Updating 1 property on an instance already in the database.

```js
db.findOne(...).then(instance => ... // { id: 123, "foo": "who" }
// now update
instance.set("foo", "bar");
instance.save({ silent: true });
instance.changed(); // { "foo": false }
```

## What do you expect to happen?
I expect:

1. `instance.changed()` to return affirmatively that data changed 
2. `instance.dataValues["foo"]` and `instance._previousDataValues["foo"]` to be different

## What is actually happening?
1. `instance.changed()` returns `{ "foo": false }` (note the `false`) 
2. `instance.dataValues["foo"]` and `instance._previousDataValues["foo"]` are the same

It looks like [this line in model.js](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3796) is what is setting `changed["foo"]` explicitly to `false` and the line above it setting the `dataValues` and `_previousDataValues` to be equal ... before returning the Promise. 

Dialect: postgres
Dialect version: `10.x`
Sequelize version: `4.37.9`
Tested with latest release: Yes, latest `4.37.9`

**Comment by markhealey** [comment]
Anyone seen this behavior? Thanks.

**Comment by sushantdhiman** [comment]
Have you tried this with `master`?
