### ISSUE TITLE
TimeoutError: ResourceRequest timed out upon Multiple Updates

### ISSUE THREAD

**Issue by bo3OU** [sequelize/sequelize#9495]
## What are you doing?
Using Mysql on windows
Simple model to reproduce : 

**Test.js**
```
module.exports = function(sequelize, DataTypes) {
    const test =  sequelize.define('test', {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
      }
    }, {
      tableName: 'test',
      timestamps: false,
      underscored : true
    });

  
    return test;
  }; 
```
**Bot.js**

```
const   express = require('express')
const   models = require('./models');
var     app = express();

for(let i = 1;i<4000;i++)
    models.test.update({id : (i+1)},
    {where: {
        id: i
    }});
```

## What do you expect to happen?
I expect all rows to be updated
i tried the same code but with create instead of update and it works, it created 4000 rows

## What is actually happening?

upon updating some rows ( approx 3000 ) it generates multiple errors of this sort : 

**Output :** 

>Unhandled rejection TimeoutError: ResourceRequest timed out
>   at ResourceRequest._fireTimeout (b:\homeback\node_modules\generic pool\lib\ResourceRequest.js:62:17)
>    at Timeout.bound (b:\homeback\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
>   at ontimeout (timers.js:471:11)
>   at tryOnTimeout (timers.js:306:5)
>    at Timer.listOnTimeout (timers.js:266:5)

**Comment by sushantdhiman** [comment]
Follow the issue template, Increase your `acquire` timeout period, increase pool size
