### ISSUE TITLE
Type 'symbol' cannot be used as an index type

### ISSUE THREAD

**Issue by lomby92** [sequelize/sequelize#9498]
I have a TypeScript project where package.json has `"typescript": "^2.7.2"` dependence.
After release 2.9 of TypeScript i have an error on compile:

```js
Type 'symbol' cannot be used as an index type.
143 query.where[sequelize.Op.and].push({ userId: req.query.userId });
```
Is this an error of Sequelize?

__Dialect:__ postgres
__Dialect version:__ ???
__Database version:__ 9.6
__Sequelize version:__ 4.37.10

**Comment by Carrotzpc** [comment]
There are two issues of typeScript may help you:

[https://github.com/Microsoft/TypeScript/issues/24587](https://github.com/Microsoft/TypeScript/issues/24587)
[https://github.com/Microsoft/TypeScript/issues/1863](https://github.com/Microsoft/TypeScript/issues/1863)

I downgraded the version of typeScript to 2.8.
