### ISSUE TITLE
How to get the new obj created in a transaction before commit

### ISSUE THREAD

**Issue by liuzhenji** [sequelize/sequelize#9502]
## What are you doing?

```js
serviceA.js
async create(params) {
   sequelize.transaction(async t => {
      const newObj = await model.create(body);
      params.newObjId = newObj.id;
      const ret = await serviceB.create(params);
      return ret;
   }); 
}
serviceB.js
async create(params) {
   const newObjId = params.newObjId;
   const newObj = await newObjModel.findOne({
      where: {
         id: newObjId
      }
   });
   const someNewObjProp = newObj.someProp;
   xxxxxx.......
}
```

## What do you expect to happen?
I want to get the newObj in serviceB method without passing it.

## What is actually happening?
get null from await newObjModel.findOne({});

**Comment by iranianpep** [comment]
Any suggestion for this problem? Why it's closed without any comment?!

**Comment by sushantdhiman** [comment]
I think because issue template was not followed, ` newObjModel.findOne({});` need current transaction object to access any rows created during that transaction.

**Comment by iranianpep** [comment]
Thanks for the clarification and quick response.
