### ISSUE TITLE
UnknownConstraintError#message ends up as an object rather than a string

### ISSUE THREAD

**Issue by papandreou** [sequelize/sequelize#9505]
## What are you doing?

```js
(async () => {
  try {
    await sequelize.query(`DROP INDEX i_do_not_exist`);
  } catch (err) {
    console.log(err.message);
  }
})();
```

## What do you expect to happen?
A string ('Unknown constraint error') is logged.

## What is actually happening?
An object is logged.

_Output, either JSON or SQL_

```js
{ message: 'Unknown constraint error',
  constraint: undefined,
  fields: undefined,
  table: undefined,
  parent: [...]
  id: 1,
  transaction: 
   { finished: undefined,
     id: '43cd28c2-77ed-4b22-84ac-c9783657d75b' } }
}
```

This is breaking some error handling libraries I'm using because they expect `err.message` to be a string (which is reasonable).

As far as I can tell from the source code, it is the intention to leave `message` as a string, but when an object is passed to the constructor [here](https://github.com/sequelize/sequelize/blob/6f1584909b1fb0ec023ad5f0f6682483120d0e86/lib/dialects/postgres/query.js#L353-L359), it's interpreted as a string [here](https://github.com/sequelize/sequelize/blob/6f1584909b1fb0ec023ad5f0f6682483120d0e86/lib/errors/index.js#L212-L220). Perhaps the intention was to always take an options object like the error class defined above? https://github.com/sequelize/sequelize/blob/6f1584909b1fb0ec023ad5f0f6682483120d0e86/lib/errors/index.js#L193

__Dialect:__ postgres
__Dialect version:__ ?
__Database version:__ 9.6
__Sequelize version:__ 4.37.10
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Your observation is correct, `UniqueConstraint` constructor should be accepting `options` like all other errors

**SSCCE**

```js
const User = sequelize.define('user', {
  email: Sequelize.STRING
});

sequelize
  .sync({ force: true })
  .then(() => {
    return sequelize.query('ALTER TABLE users DROP CONSTRAINT i_do_not_exist');
  })
  .catch(e => {
    console.log(JSON.stringify(e, null, 2));
  });
```

```sql
{
  "name": "SequelizeUnknownConstraintError",
  "parent": {
    "message": {
      "message": "Unknown constraint error",
      "parent": {
        "name": "error",
        "length": 124,
        "severity": "ERROR",
        "code": "42704",
        "file": "tablecmds.c",
        "line": "7748",
        "routine": "ATExecDropConstraint",
        "sql": "ALTER TABLE users DROP CONSTRAINT i_do_not_exist"
      }
    }
  },
  "original": {
    "message": {
      "message": "Unknown constraint error",
      "parent": {
        "name": "error",
        "length": 124,
        "severity": "ERROR",
        "code": "42704",
        "file": "tablecmds.c",
        "line": "7748",
        "routine": "ATExecDropConstraint",
        "sql": "ALTER TABLE users DROP CONSTRAINT i_do_not_exist"
      }
    }
  }
}
```

**Comment by Ankit7991** [comment]
Is it possible withour {force: true},

**Comment by Ankit7991** [comment]
Or I should take backup, then force: true and put backup data back in mysql.
