### ISSUE TITLE
Unsigned BIGINT primary key incorrect (precision loss) after querying sqlite database

### ISSUE THREAD

**Issue by lasa01** [sequelize/sequelize#9522]
## What are you doing?

Create a new sqlite database with a single table containing an unsigned BIGINT primary key.
Insert a row into the table, and query the row from the table with the primary key.
Primary key is now incorrect, and any attempts at updating the row will fail because of this.

```js
const Sequelize = require('sequelize');

const sequelize = new Sequelize('database', 'username', 'password', {
    dialect: 'sqlite',
    storage: 'db.sqlite'
});

const Test = sequelize.define('test', {
    id: {type: Sequelize.BIGINT.UNSIGNED, primaryKey: true},
    name: Sequelize.STRING
});

sequelize.sync().then(() => {
    //Create an entry with a large id
    Test.create({id: '352475172290166785', name: 'test'}).then(query => {
        console.log('query id correct:', query.id);
        //Find the entry with the same id
        Test.findById('352475172290166785').then(query => {
            console.log('query id incorrect:', query.id);
            query.name = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15); // Random string
            query.save().then(()=>{
                console.log('Incorrect id, not saved');
            });
        });
    });
});
```

## What do you expect to happen?
_Property query.id should be correct in both print statements and the database should be saved properly._

## What is actually happening?
_After finding the entry by id, the query id seems to have suffered a loss of precision and is incorrect, because of this the database saving also fails._

_Output:_
```
node dbtest.js
Executing (default): CREATE TABLE IF NOT EXISTS `tests` (`id` BIGINT UNSIGNED PRIMARY KEY, `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`tests`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_tests_1`)
Executing (default): INSERT INTO `tests` (`id`,`name`,`createdAt`,`updatedAt`) VALUES ('352475172290166785','test','2018-06-10 12:43:23.809 +00:00','2018-06-10 12:43:23.809 +00:00');
query id correct: 352475172290166785
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `tests` AS `test` WHERE `test`.`id` = '352475172290166785';
query id incorrect: 352475172290166800
Executing (default): UPDATE `tests` SET `name`='l3t0t69p63vaytmwsq1da',`updatedAt`='2018-06-10 12:43:23.888 +00:00' WHERE `id` = 352475172290166800
Incorrect id, not saved
```

__Dialect:__ sqlite
__Dialect version:__ sqlite3@4.0.0
__Database version:__ sqlite3
__Sequelize version:__ sequelize@4.37.10 and sequelize@5.0.0-beta.7
__Tested with latest release:__ Yes, look above

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`node-sqlite3` doesn't return string for BIGINT and simply return incorrect result for out of range integer values

I have submitted an issue, but so far no real progress https://github.com/mapbox/node-sqlite3/issues/922 

When this is fixed at dialect level, Sequelize will handle BIGINT for SQLite properly

**Comment by lasa01** [comment]
A note could be added about this to the documents [here](http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes) in case other people run into the same issue.
