### ISSUE TITLE
Model.create with hasTrigger true return typeError attribute.type.toSql is not a function

### ISSUE THREAD

**Issue by Medesko** [sequelize/sequelize#9525]
Hi Everybody, 

When I set hasTrigger true in Model.create, I have this TypeError : 
attribute.type.toSql is not a function
    at Object.insertQuery (/Users/momo/www/api.test.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:128:90)

Could someone please help me?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
