### ISSUE TITLE
Raw retrieval should retrieve disconnected objects

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#9527]
## What are you doing?
I'm trying to retrieve a raw javascript object that avoids toJSON because I override toJSON to remove some security sensitive properties. In some cases, however I do need the properties that are removed by default. 

I would expect `raw` retrieval would result in this (as well), bypassing `toJSON`. 
However, `raw` retrieval results in a connected instance that changes with underlying instance change.

```js
export const update = async (securityObj, data, id) => { // data.firstName = 'John'
  const currentItemDb = await get(securityObj, id); // currentItemDb.firstName = 'Peter'
  const currentItem = currentItemDb.get({ raw: true }); // currentItem.firstName = 'Peter'
  console.log('1', currentItem); // currentItem.firstName = 'Peter'
  await currentItemDb.cache().update(data); // currentItem.firstName = 'John'
  console.log('2', currentItem); // currentItem.firstName = 'John'
  console.log('2a', currentItemDb.get()); // currentItem.firstName = 'John'
  await createHistory(securityObj, currentItem, id);
  return currentItemDb;
};
```

## What do you expect to happen?
I would expect `firstName` at `2` to equal `Peter. 

## What is actually happening?
Since it remains connected, it is `John`

The workaround is to `JSON.stringify` `currentItem` and then parse it again after updating the object. But it would be nice to have a faster and better solution.

__Dialect:__ mysql
__Dialect version: MySql
__Database version: 5.7.x
__Sequelize version: 4.37.10
__Tested with latest release:__ Yes

**Comment by mschipperheyn** [comment]
Perhaps there should be an extra option, although the word, like `js`

**Comment by sushantdhiman** [comment]
Can you please provide me an SSCCE so its bit easy to understand?

**Comment by mschipperheyn** [comment]
I'm not really sure how to explain it better than in the example above. I don't really have time to set up a test case. Perhaps you guys have a Codepen handy so forking is easy?

**Comment by sushantdhiman** [comment]
( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
