### ISSUE TITLE
Incorrect or undocumented behaviour when `where` is an array

### ISSUE THREAD

**Issue by LaurentVB** [sequelize/sequelize#9530]
Hello, I just ran into a case for which I couldn't find any documentation and which seems a bit weird:
When I pass an array as the `where` option in a `findAll` call, the query is generated but the field names are not mapped.
E.g:

```js
const User = sequelize.define('user', {
  username: {
    type: Sequelize.STRING,
    field: 'user_name'
  }
});

sequelize.sync()
  .then(() => User.findAll({
    where: [
      { username: 'foobar' },
      sequelize.literal('1 = 1')
    ]
  }));
```

I'd expect the generated query to use the mapped field name (`user_name`), but instead, it generates the following query, which fails: 
```sql
    Executing (default): SELECT "id", "user_name" AS "username", "created_at", "updated_at", "deleted_at" FROM "users" AS "user" WHERE (("user"."deleted_at" > '2018-06-13 10:53:35.054 +00:00' OR "user"."deleted_at" IS NULL) AND (("user"."username" = 'foobar' AND 1 = 1)));
```

Ironically, the error message does the mapping correctly 😄 

```
    Unhandled rejection SequelizeDatabaseError: column "user_name" does not exist
```
I guess the behaviour comes from this code: https://github.com/sequelize/sequelize/blob/b66f9ddc36720aef1523d677dbbfb9f257afa472/lib/utils.js#L183-L185

I couldn't find any documentation about using an array as `where` option. It seems like for now, if that's the case, the array is properly transformed into WHERE clauses, but without attributes mapping.
If that's unsupported (but I found it used in one test about scope), how would you mix a "regular" `where` hash with some literal sql code?

**Comment by sushantdhiman** [comment]
`where` accepts object not array, you can mix multiple operations something like this

```js
where: {
    [Op.and]: [
       { username: 'foobar' },
       sequelize.literal('1 = 1')
    ]
 }
```

**Comment by LaurentVB** [comment]
Thanks Sushant. Makes total sense.
fyi, the "array as where option" is used in the tests over here: https://github.com/sequelize/sequelize/blob/master/test/unit/model/scope.test.js
