### ISSUE TITLE
using mysql2 package results error

### ISSUE THREAD

**Issue by justechn** [sequelize/sequelize#9534]
## What are you doing?

I am following the example found on this page http://docs.sequelizejs.com/manual/installation/getting-started.html#your-first-model However when I try and start it, I get the following error 
```
Error: The dialect mysql is not supported. (Error: Please install mysql package manually)
```
After running 
```
npm i mysql --save
```
it works.

The documentation should be updated to change 
```npm install --save mysql2```
to
```npm install --save mysql```

## What do you expect to happen?
a working example

## What is actually happening?
broken example

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Looks like you installed v3 by mistake, v4 and later use `mysql2` https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/connection-manager.js#L37

And follow the issue template
