### ISSUE TITLE
model.sync({ alter: true }) will add new index

### ISSUE THREAD

**Issue by bgyhnddr** [sequelize/sequelize#9536]
`
module.exports = function(sequelize, DataTypes) {
  return sequelize.define(
    "emp_dict_type",
    {
      id: {
        type: DataTypes.INTEGER(11),
        allowNull: false,
        unique: "true",
        autoIncrement: true
      },
      code: {
        type: DataTypes.STRING(45),
        primaryKey: true,
        allowNull: false
      },
      name: {
        type: DataTypes.STRING(45),
        allowNull: false
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: true
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: true
      }
    },
    {
      tableName: "emp_dict_type",
      underscored: true
    }
  );
};
`

every time you run  
`model.sync({ alter: true });`

you will find a new index be added to database table

such as id_1  id_2  id_3 id_n

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by te-online** [comment]
> Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions.

Haha, definition of bug could be interesting to know here. 😉  For me it feels like a bug!
