### ISSUE TITLE
Q: Sequelize deprecated warning when running migrations

### ISSUE THREAD

**Issue by markomiljkovic** [sequelize/sequelize#9537]
Hello guy Im new to Sequalize,and I know this has been posted multiple tims but Im constanlty getting warning when running migrations on my db
I have read their offical docs, read your github post but still Im getting warning :

`GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:236:13`

Here is my sample connections.js file that Im using for connecting with db.
[](https://pastebin.com/5NKfExib)
But Im not getting error when starting my server.
My sequalize version is : 4.28.5

**Comment by sushantdhiman** [comment]
Can you link me what posts you have read

**Comment by markomiljkovic** [comment]
this one:
https://github.com/sequelize/sequelize/issues/8417

**Comment by sushantdhiman** [comment]
@markomiljkovic So discussion involved in #8417 was not clear?

**Comment by sushantdhiman** [comment]
@markomiljkovic Did you traced if it's your code or cli itself printing the warning?

**Comment by markomiljkovic** [comment]
Sorry Im a bit new to this, how can I trace to see if its code or cli ??
I have a gulp file where I init my database and 
It is happening when Im runing this code:


```
        execSync('./node_modules/.bin/sequelize db:drop');
    console.log('INIT DB: proceeding with db create...');
    execSync('./node_modules/.bin/sequelize db:create');
    console.log('INIT DB: db created.');
    console.log('INIT DB: initializing db structure with init migrations');
    execSync('./node_modules/.bin/sequelize db:migrate');
    console.log('INIT DB: initializing data through seeds:');
    execSync('./node_modules/.bin/sequelize db:seed --seed 2017110112022323-init_data');
    console.log('INIT DB: finished.');
```

**Comment by markomiljkovic** [comment]
Hello I fixed it by adding Sequalize.op
 to my migrtations.config.js

const Sequelize = require("sequelize");
module.exports = {
  "development": {
  "username": "test",
  "password": "test",
  "database": "db_test",
  "host": "localhost",
  "dialect": "postgres",
  "seederStorage": "sequelize",
  "operatorsAliases" : Sequelize.Op,
  },
  "test": {
  "username": "test1",
  "password": "test1",
  "database": "db_test1",
  "host": "127.0.0.1",
  "dialect": "postgres",
  "logging": true,
  "operatorsAliases" : Sequelize.Op,
  },
  "production": {
  "username": "production",
  "password": "production",
  "database": "db_production",
  "host": "127.0.0.1",
  "dialect": "postgres",
  "operatorsAliases" : Sequelize.Op,
  }
}

And warning dissapeared :)
My question is do I need to use Sequalize.op in my connection.js file above or is it enough that I added it to migrations.config.json

**Comment by sushantdhiman** [comment]
As advised in the main post set `operatorsAliases: false` to prevent Hash injection attacks, it's already a default in v5

**Comment by markomiljkovic** [comment]
Yes but why should I set it to false whe in offical docs it states:

> For better security it is highly advised to use Sequelize.Op and not depend on any string alias at all. You can limit alias your application will need by setting operatorsAliases option, remember to sanitize user input especially when you are directly passing them to Sequelize methods.

http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-security

**Comment by sushantdhiman** [comment]
>  but why should I set it to false when in offical docs it states to use Sequalize.Op:

Official docs are not advising to set `operatorsAliases: Sequelize.Op`, it's saying use `Sequelize.Op` in your code instead of `$or / $and` etc

> For **better security** it is highly advised to use Sequelize.Op and **not depend on any string alias at all**

When you set `operatorsAliases: any-object`, you are choosing string based operators, which are open to hash injection. `operatorsAliases: Sequelize.Op` is probably the laziest thing you can do to get rid of this warning and keeps you wide open for hash injection attack.

`operatorsAliases: { my limited operators }` is just a way for application to migrate slowly without breaking change.

**Comment by markomiljkovic** [comment]
aa okay thank you very much again @sushantdhiman so if I understand you well
I should set my 
`operatorsAliases: false`
in migrations.config.json and also when connecting to db 
```
 sequelize = new Sequelize(config.database, config.username, config.password, Object.assign({}, config, {
        pool: dbConst.pool,
        operatorsAliases: false,
    })
```
and in my method calls I shoud use Sequelize.Op.$not insted of $not or other way around ?
```
// method sample
 const getAllUsers = async () => {
        const query = { username: { $not: 'GOD4ALL' } }; // intead of $not use Sequelize.Op.$not
        const users = JSON.parse(JSON.stringify(await users.getUsers(User, query, null)))

        return users;
    };
```

**Comment by sushantdhiman** [comment]
simply `Op.not`, there is no `Op.$not` operator

**Comment by markomiljkovic** [comment]
thank you very much again  @sushantdhiman  :) :+1: 
so this above is the proper configuration 
use Op in quearies and set operatiosAliases to false in migrations and when connecting to db :) ???

**Comment by sushantdhiman** [comment]
Yeah, use `Op.[operator]` everywhere in your code, set to `operatiosAliases: false` in v4, for v5 you don't need to set `operatiosAliases` as it will be `false` by default

**Comment by markomiljkovic** [comment]
thanks I will close issue now :)
