### ISSUE TITLE
I can not set two belongsToMany association on one model

### ISSUE THREAD

**Issue by mohammad-khooie** [sequelize/sequelize#9540]
**I write this codes** 
```
// BusinessOrder_BusinessOrderStatusSeller
BusinessOrder.BusinessOrderStatusSellers = BusinessOrder.belongsToMany( BusinessOrderStatusSeller, { "as": "sellerBusinessOrderStatuses", "foreignKey": "businessOrderId", "through": { "model": BusinessOrderBusinessOrderStatusSeller } } );
BusinessOrderStatusSeller.BusinessOrders = BusinessOrderStatusSeller.belongsToMany( BusinessOrder, { "as": "businessOrders", "foreignKey": "sellerBusinessOrderStatusId", "through": { "model": BusinessOrderBusinessOrderStatusSeller } } );
// User_BusinessOrderStatusSeller
User.BusinessOrderStatusSellers = User.belongsToMany( BusinessOrderStatusSeller, { "as": "sellerBusinessOrderStatuses", "foreignKey": "userId", "through": { "model": BusinessOrderBusinessOrderStatusSeller } } );
BusinessOrderStatusSeller.Users = BusinessOrderStatusSeller.belongsToMany( User, { "as": "users", "foreignKey": "sellerBusinessOrderStatusId", "through": { "model": BusinessOrderBusinessOrderStatusSeller } } );
```

**but wen I see my table in database there is not businessOrderId field on it**
Dialect: postgresql
__Database version: 10.4
__Sequelize version: 4.37.10

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
