### ISSUE TITLE
Explicit identity insert is ignored when id value is falsey

### ISSUE THREAD

**Issue by Undre4m** [sequelize/sequelize#9542]
## What are you doing?
I'm trying to explicitly insert the identity value of a table column.

```js
const Perfil = sequelize.define('Perfil', {
    idPerfil: {
        type: DataType.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    nombre: {
        type: DataType.STRING(90),
        allowNull: false,
        unique: true
    }
}, {
    timestamps: true,
    paranoid: true,
    createdAt: 'fechaAlta',
    updatedAt: false,
    deletedAt: 'fechaBaja',
    name: {
        singular: 'perfil',
        plural: 'perfiles'
    },
    tableName: 'Perfiles'
});
```
```js
Perfil.create({
    idPerfil: 0,
    nombre: 'Empleado Registrado'
});
```

## What do you expect to happen?
_IDENTITY_INSERT_ to be set to **ON** and the identity value **inserted**
```sql
SET IDENTITY_INSERT [Perfiles] ON;
INSERT INTO [Perfiles] ([idPerfil],[nombre],[fechaAlta]) OUTPUT INSERTED.* VALUES (0,N'Empleado Registrado',N'2018-01-01 00:00:00.000 +00:00');
SET IDENTITY_INSERT [Perfiles] OFF;
```

## What is actually happening?
Identity field is **ignored**
```sql
INSERT INTO [Perfiles] ([nombre],[fechaAlta]) OUTPUT INSERTED.* VALUES (N'Empleado Registrado',N'2018-06-16 03:55:09.172 +00:00');
```

Happens when identity value is a falsey value (0, null, '', etc).

__Dialect:__ mssql
__Dialect version:__ XXX
__Database version:__ MSSQL Server 2017 Express Edition
__Sequelize version:__ 4.37.10
__Tested with latest release:__ Yes, 4.37.10

**Comment by sushantdhiman** [comment]
Try `idPerfil: sequelize.literal('0')`

**Comment by Undre4m** [comment]
@sushantdhiman hi, thanks for the quick response. Yes that, and other non-falsey values work. I already worked it around but it introduced some unwanted changes.

I didn't have time to properly test this, but if it helps i suspect the issue could be here: https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L210

**Comment by sushantdhiman** [comment]
This is not a issue, Sequelize filters falsy primary key values. For your special case `sequelize.literal('0')` should be ok.
