### ISSUE TITLE
Postgres formatError inconsistent return

### ISSUE THREAD

**Issue by bernardobelchior** [sequelize/sequelize#9546]
Checking the `formatError` function in `query.js` for postgres dialect, I found that the way of returning is generally using `return new Error`, but [here](https://github.com/sequelize/sequelize/blob/d46e2070432c6f22b09aa095995f08f74c7b7384/lib/dialects/postgres/query.js#L353) the error is being thrown. 
It seems ok, but [here](https://github.com/sequelize/sequelize/blob/d46e2070432c6f22b09aa095995f08f74c7b7384/lib/dialects/postgres/query.js#L86), the return of `formatError` is being thrown, so I am unsure if it is supposed to be like that.

**Comment by sushantdhiman** [comment]
In both cases it will throw, result is not changed
