### ISSUE TITLE
Setting `required` to `false` always returns empty array in association

### ISSUE THREAD

**Issue by FreeLineTM** [sequelize/sequelize#9555]
## What are you doing?
Querying a `belongsToMany` with `required: false`.

`Tournament`
```js
guild_id: {
  type: DataTypes.STRING,
  allowNull: false
},

start_date: {
  type: DataTypes.DATE,
  allowNull: false,
  defaultValue: DataTypes.NOW
},

end_date: DataTypes.DATE
```
`User`
```js
discord_id: {
  type: DataTypes.STRING,
  primaryKey: true
},

in_queue: {
  type: DataTypes.BOOLEAN,
  allowNull: false,
  defaultValue: false,
  set(val) {
    this.setDataValue('in_queue', val);
    if (val) this.setDataValue('queued_since', new Date());
    else this.setDataValue('queued_since', null);
  }
},

queued_since: DataTypes.DATE,

rating: {
  type: DataTypes.INTEGER,
  allowNull: false,
  defaultValue: 1000
}
```
Associations
```js
Tournament.belongsToMany(User, { as: 'Participants', through: TournamentParticipant });
User.belongsToMany(Tournament, { as: 'Tournaments', through: TournamentParticipant, foreignKey: 'participant_discord_id' });
```
Query
```js
User.findById('someId', {
  include: [ {
    association: 'Tournament',
    required: false,
    where: {
      guild_id: msg.guild.id,

      $or: [
        {
          end_date: null
        },
        {
          end_date: { $gt: new Date() }
        }
      ]
    }
  } ]
});
```

## What do you expect to happen?
If `User` is in any tournaments, return them. If not, still return the `User` with an empty `Tournaments` array.

## What is actually happening?
The `Tournaments` array is empty regardless if any `Tournament`s match the query. I have confirmed that the `User` has a relation to `Tournament`s matching the query by `Tournament.getParticipants()`. It works fine with `required: true` but `User` would be `null` if it did not have a relation to any `Tournament`s.

```js
{ discord_id: '179256560139108352',
  in_queue: false,
  queued_since: null,
  rating: 1016,
  created_at: 2018-06-18T17:15:26.626Z,
  updated_at: 2018-06-18T17:15:35.529Z,
  Tournaments: [] }
```

__Dialect:__ sqlite
__Database version:__ sqlite3
__Sequelize version:__ 4.37.10 (latest)
__Tested with latest release:__ Yes

**Comment by FreeLineTM** [comment]
What is the point of `required` at all if it is expected to always return an empty association array?

**Comment by sushantdhiman** [comment]
`required: true` will not return parent record, if include record is missing so basically a inner join. `required: false` will return parent record even of child record was not found, so a outer join

**Comment by FreeLineTM** [comment]
Why not just remove the association in the query altogether if you only want the parent record?

**Comment by sushantdhiman** [comment]
`required: false` does not mean there will be no child record, it means I dont care if child record exists or not I always want parent record, but if child exists please get that too.

if we support what you are suggesting it will look something like this

```json
[
  {
    "name": "abc",
    "Tournaments": [
      {
        "name": "xyz"
      }
    ]
  },
  {
    "name": "def"
  },
  {
    "name": "ghi",
    "Tournaments": [
      {
        "name": "raa"
      }
    ]
  }
]
```

As you can see `Tournaments` "holes", now we can't be sure if `user.Tournaments` exists or not, if it does will it be an array or `undefined`

I guess what you actually need it not exists? something like that is not directly supported by Sequelize, you will need to do custom `Op.and` query

**Comment by FreeLineTM** [comment]
What do you mean? My issue is that the child record is *never* there *regardless* of any relationships between them and the parent with `required: false`>

**Comment by sushantdhiman** [comment]
:D I totally misunderstood your issue, can I get something that I can test like a SSCCE as this is a very basic feature and we have plenty of test for this.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by FreeLineTM** [comment]
Sorry for the late response, I haven't been at home for the past two weeks. I will try to get a SSCCE up but I found a way around this though I'd like to solve it. Will try to be as fast as possible!

**Comment by alihamza-datics** [comment]
@EirikFA  did you find any workaround for this? if yes please share it
