### ISSUE TITLE
V4 HasMany bad rawAttributes check?

### ISSUE THREAD

**Issue by cisox** [sequelize/sequelize#9556]
## What are you doing?
I'm trying to setup an association between two tables using `sourceKey` and `foreignKey`. Both values are set to the actual field names which are underscored and not the camelcased name that I'm using for the attribute names. When working on the associations, I received this error:

```
node_modules/sequelize/lib/associations/has-many.js:83
      this.sourceKeyField = this.source.rawAttributes[this.sourceKey].field || this.sourceKey;
                                                                      ^
TypeError: Cannot read property 'field' of undefined
```

When looking at the `has-many.js` file, I noticed that the code is checking `this.target.rawAttributes` for `this.sourceKey` before trying to access the field in `this.sourceKeyField = this.source.rawAttributes[this.sourceKey].field || this.sourceKey;`. It seems to be that it should be checking `this.source.rawAttributes` instead. It looks like it's been changed in `master` but it would be very helpful to fix that in V4. 

Here is the code in question: https://github.com/sequelize/sequelize/blob/v4.37.10/lib/associations/has-many.js#L82

I've played around with the `sourceKey` and `foreignKey` values and I can get around the error but then I get another error from MySQL about the field not being defined.

__Dialect:__ mysql
__Database version:__ 5.7.21
__Sequelize version:__ 4.37.10
__Tested with latest release:__ 4.37.10

**Comment by sushantdhiman** [comment]
As you noticed this is already fixed in master, but PR https://github.com/sequelize/sequelize/pull/9304 is big and breaking change, so I can't backport this.

If you want you may pick fragment of that code with one failing test and I will add this fix to v4 as well.
