### ISSUE TITLE
support for using mssql db config property multiSubnetFailover while instantiating Sequelize instance

### ISSUE THREAD

**Issue by swamy526** [sequelize/sequelize#9560]
## What are you doing?
Trying to use mssql db config property multiSubnetFailover, but, not working.

```js
var sequelizeInstance = new Sequelize(dbConfig.database, dbConfig.user, dbConfig.password, {
    dialect: dbConfig.driver,
    host: dbConfig.host,
    port: 1433,
    options: {
        multiSubnetFailover: true
    }
});
```

## What do you expect to happen?
_sequlize should send this 'multiSubnetFailover:true' to tedious while creating connection._

## What is actually happening?
_ConnectionError: Failed to connect to <hostname:port> in 15000ms
       at ConnectionError (node_modules\tedious\lib\errors.js:12:12)
       at Connection.connectTimeout (node_modules\tedious\lib\connection.js:637:28)
       at ontimeout (timers.js:380:14)
       at tryOnTimeout (timers.js:244:5)
       at Timer.listOnTimeout (timers.js:214:5)
     message: 'Failed to connect to <hostname:port> in 15000ms',
     code: 'ETIMEOUT' }_

__Dialect:__  mssql
__Dialect version:__ 4.0.4
__Database version:__ SQL Server 13.0.4466.4
__Sequelize version:__ 4.37.10
__Tested with latest release:__ yes, 4.37.10

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by swamy526** [comment]
Issue resolved after changing from options to dialectOptions.

**Comment by TiagoCunhaF** [comment]
Thanks swamy!
