### ISSUE TITLE
Multiple scopes

### ISSUE THREAD

**Issue by Aleksaas** [sequelize/sequelize#9564]
This is not a bug reporting, it is only a question, you can close it after. 
When I get `Users` from DB I have something like this in my where clause `'$customer.name$'` where `customer` is property on `User`. 
Because of that I need to put this in `User` scope: `include: [() => Customer]`. If I don't do that I would get error: `missing from-clause entry for table`.
So far so good, but the problem is that doing so it will also return `Customer` inside `User` as a response, and I don't want that, I only included it so `where` clause doesn't throw an error.
Is there a way to use one scope to support `where` clause and another scope as a result of query? Because what you need in `WHERE` is not the same as what you want in `SELECT`. 
If this is not possible, is there any other approach to solve this problem?

**Comment by josemando** [comment]
If you something like this, you won't have any value from Customer on the result
```
User.findOne({
  include: [{
    model: Customer,
    as: 'customer',
    attributes: [],
    where: {
      name: "something here"
    }
  }],
  where: {
    ...
  }
```

**Comment by sushantdhiman** [comment]
^
