### ISSUE TITLE
increment function generates strange sql

### ISSUE THREAD

**Issue by fareshan** [sequelize/sequelize#9572]
I am trying to increment a field:
`
user.increment({ lastCheckingEmailSendingNumber: 1 });
`
The increment operation does not work. And I get this error:
error.message: "column "0" of relation "User" does not exist"
error.sql: "UPDATE "User" SET "lastCheckingEmailSendingNumber"="lastCheckingEmailSendingNumber"+ 1,"0"='id',"1"='email',"2"='firstName',"3"='lastName',"4"='phoneNumber',"5"='birthdate',"6"='nationalId' WHERE "id" = 1 RETURNING *"

I don't understand where this part `"0"='id',"1"='email',"2"='firstName',"3"='lastName',"4"='phoneNumber',"5"='birthdate',"6"='nationalId'`
comes from, even though emai, firstName, ... are columns in User Table !?

I am using sequelize-typescript version 0.6.5

__Dialect:__ postgres
__Dialect version:__ pg 6.4.2
__Database version:__ 9.6
__Sequelize version:__ 5.0.0-beta.8
__Tested with latest release:__ yes, 5.0.0-beta.8

**Comment by kayorl** [comment]
same problem.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by fareshan** [comment]
@sushantdhiman
It is a bug.
And I followed the template.

**Comment by sushantdhiman** [comment]
@fareshan I am not closing issues randomly, I see nothing in your issue report that could help me reproduce this issue. If you want to report an issue or seeking help, atleast try to present a proper example or even better a SSCCE

**Comment by lessu** [comment]
It seems it have something to do with DefaultScope.attributes.exclude.
after removed `exclude`,no error shows any more

**Comment by fareshan** [comment]
@lessu That was a year ago. I don't remember how I fixed it. But I just looked to the code and I see that I am using `user.increment("lastCheckingEmailSendingNumber", { by: 1 });` instead of `user.increment({ lastCheckingEmailSendingNumber: 1 });`
So I fixed it with this change or by updating Sequelize.
