### ISSUE TITLE
runHooks blocks the event loop badly

### ISSUE THREAD

**Issue by yocontra** [sequelize/sequelize#9575]
## What are you doing?

- No hooks defined

```js
Model.findById('1234')
```

## What do you expect to happen?

It finds it without blocking the event loop.

## What is actually happening?

The event loop is blocked for somewhere between 100 and 1000ms (updates are ~800ms, finds are ~100ms). Gathered using https://github.com/naugtur/blocked-at

```
warn: event-loop Blocked for 128.54258999633788ms, operation started here:
     at Function.runHooks (/Users/contra/Projects/staeco/node_modules/sequelize/lib/hooks.js:124:20)
    at Promise.try (/Users/contra/Projects/staeco/node_modules/sequelize/lib/model.js:1672:21)
    at Function.findAll (/Users/contra/Projects/staeco/node_modules/sequelize/lib/model.js:1668:23)
    at Function.findOne (/Users/contra/Projects/staeco/node_modules/sequelize/lib/model.js:1867:17)
```

__Dialect:__ any
__Sequelize version:__ latest master
__Tested with latest release:__ Yes

## Potential Solutions

- Allow users to disable hooks entirely via a global option, most people don't use this feature and they shouldn't have poorly performing applications
- Automatically detect when users have no hooks and skip this routine completely
- Rewrite the hooks running so it doesn't block the event loop

**Comment by papb** [comment]
Hello, is this still an issue with latest sequelize v5?

**Comment by contra** [comment]
@papb I can check, but AFAIK no changes were made in v5 for hooks so I don't think it would be fixed yet.

**Comment by AntoineGrandchamp** [comment]
Is there something that has been found? I also have some delay in the event loop that seems to come from Sequelize V6.

**Comment by Keimeno** [comment]
@AntoineGrandchamp can you provide an example of your findings? I tried the following with sequelize 6.6.2:

```ts
for (let i = 0; i < 10; i++) {
	console.time('timings');
	Model.findByPk('1234');
	console.timeEnd('timings');
}
```

and got the following timing results:
```ts
timings: 1.312ms
timings: 0.265ms
timings: 0.323ms
timings: 0.431ms
timings: 0.269ms
timings: 0.155ms
timings: 0.114ms
timings: 0.116ms
timings: 0.101ms
timings: 0.095ms
```

Also, `blocked-at` did not report anything. Maybe this is/was only a sequelize v4 (and v5) problem

**Comment by AntoineGrandchamp** [comment]
I am using `monitorEventLoopDelay` from Node to get the delay in the event loop. Here is the [documentation](https://nodejs.org/api/perf_hooks.html#perf_hooks_perf_hooks_monitoreventloopdelay_options). Unfortunately, I do not have a repo with a demo to offer you. 

Here is the code that I am running : 

```
import { monitorEventLoopDelay } from 'perf_hooks';

const h = monitorEventLoopDelay({ resolution: 20 });

h.enable();

const userCalendarModules = await models.UserCalendarModule.findAll({
  where: { UserGroupCourseId: [ 1, 2, 3, 4, 5 ] }, // Fictitious ids
  attributes: ['relativeDate', 'UserId', 'ModuleId'],
  raw: true,
});

h.disable();
console.log({
  min: `${Math.round(h.min / 1000000)} ms`, // Convert from nanoseconds to milliseconds
  max: `${Math.round(h.max / 1000000)} ms`,
  mean: `${Math.round(h.mean / 1000000)} ms`,
  stddev: `${Math.round(h.stddev / 1000000)} ms`,
  percentiles: h.percentiles,
  percentile50: `${Math.round(h.percentile(50) / 1000000)} ms`,
  percentile99: `${Math.round(h.percentile(99) / 1000000)} ms`,
  exceeds: h.exceeds,
});
```
The output: 
```
{
  min: '111 ms',
  max: '115 ms',
  mean: '113 ms',
  stddev: '2 ms',
  percentiles: Map {
    0 => 111017984,
    50 => 111017984,
    75 => 114884608,
    100 => 114884608
  },
  percentile50: '111 ms',
  percentile99: '115 ms',
  exceeds: 0
}
```

**Comment by Keimeno** [comment]
I've tried it with `monitorEventLoopDelay` and couldn't reproduce the error. Also, the event loop is not blocked at that time, we can check that by setting an interval that runs in the background:

```ts
import { monitorEventLoopDelay, performance } from 'perf_hooks';
setInterval(() => console.log(performance.now()), 0);

(async () => {
	const h = monitorEventLoopDelay({ resolution: 20 });

	h.enable();

	for (let i = 0; i < 10; i++) {
		await User.findByPk('1234');
	}

	h.disable();
	console.log({
		min: `${Math.round(h.min / 1000000)} ms`, // Convert from nanoseconds to milliseconds
		max: `${Math.round(h.max / 1000000)} ms`,
		mean: `${Math.round(h.mean / 1000000)} ms`,
		stddev: `${Math.round(h.stddev / 1000000)} ms`,
		percentiles: h.percentiles,
		percentile50: `${Math.round(h.percentile(50) / 1000000)} ms`,
		percentile99: `${Math.round(h.percentile(99) / 1000000)} ms`,
		exceeds: h.exceeds,
	});
})()
```

I've also tried running a raw query with `await sequelize.query('SELECT * FROM users WHERE id=1234');`, and remove the hooks in the source code, resulting in the same output:
```
{
  min: '19 ms',
  max: '20 ms',
  mean: '19 ms',
  stddev: '0 ms',
  percentiles: Map(4) {
    0 => 18890752,
    50 => 18890752,
    75 => 19808256,
    100 => 19808256
  },
  percentile50: '19 ms',
  percentile99: '20 ms',
  exceeds: 0
}
```

Can you check if `setInterval(() => console.log(performance.now()), 0);` runs while the query is awaiting results? Because if it would be blocked for `120ms` we shouldn't get any results from `performance.now()` for 120ms

**Comment by Keimeno** [comment]
Now after replacing `setTimeout` with `setImmediate` to get more precise results it jumps from `432.2179000079632ms` to `440.3032999932766ms`, having a delay of ~8ms +/- 1ms. However, after removing `monitorEventLoopDelay` this goes down to ~3ms +/- 1ms, and about `1.5ms` of that comes from having logging turned on in sequelize.

If this actually is an error, it might come from an overly inefficient recursive function somewhere within sequelize, but I can't reproduce it on my side.

**Comment by AntoineGrandchamp** [comment]
I believe that I found my problem. My array that I pass in the `where` clause contains 2200 items. It probably get stucks when it gets transformed in the query. If I remove it, the delay goes away. Is there a better way to pass a big list of ids that can match?
```
const userCalendarModules = await models.UserCalendarModule.findAll({
  where: { UserGroupCourseId: [ 1, 2, 3, 4, 5 ] }, // Array with 2200 items
  attributes: ['relativeDate', 'UserId', 'ModuleId'],
  raw: true,
});
```

**Comment by Keimeno** [comment]
If that array holds 2,200 items, it might just be your database that takes its time, or serializing might take a while.

**Comment by AntoineGrandchamp** [comment]
I am suspecting that it is the serializing that takes a while. It seems to block the event loop. I am guessing that there is a `.join(', ')` that is made. That would block the event loop. I suppose that it is not really a problem that Sequelize should address. I might need to do it  differently with such a big array.

**Comment by ephys** [comment]
At least in the latest version of the code, `runHooks` is just a loop that calls each callback. I would expect the issue to then come from one of the callbacks, but these are user-defined. 

Hooks can be disabled, and a future feature will allow disabling them individually: https://github.com/sequelize/sequelize/issues/14053

Based on the last posts in this thread, I think this thread can be closed
