### ISSUE TITLE
how to use table sharding with sequelize?

### ISSUE THREAD

**Issue by ccj22** [sequelize/sequelize#9578]
i need to implement table sharding, i create table everyday, like create bills_20180622,bills_20180621........
how to use one model define bills and does't need restart app to bills_20180622.findAll() bills_20180621.findAll()

**Comment by ccj22** [comment]
dynamic tables name to relate modle..

**Comment by sushantdhiman** [comment]
It not supported at the moment, moved to main issue https://github.com/sequelize/sequelize/issues/3806
