### ISSUE TITLE
My stored procedure is broken

### ISSUE THREAD

**Issue by YourDeveloperFriend** [sequelize/sequelize#959]
I tried running sequelize.query('call <stored_procedure>') and the exact query works find in mysql workbench, but returns something funky in sequelize. The first select query in the procedure looks like this:

SELECT @percentageFee := settingValue + 0.00 FROM Settings where SettingName = ''feePercentage''; 

and the results I get back are: [ { '@percentageFee := settingValue + 0.00': 0.25 } ]

What's weird is that this was working fine a few weeks ago (when I was on the beta version). I tried rolling back to the beta version, but this is still happening. If I rollback my entire code base to before I updated sequelize, then it works.

Any idea what's happening and how to fix it?

**Comment by AdvancedCat** [comment]
One example, the stored procedures will return two results,how can I get these two results with sequelize.query('call my_procedures()',{replacement:{...}}) ?

The procedure like this:
*****
select * from table1;
select * from table2;
*****
