### ISSUE TITLE
require('uuid') is deprecated 

### ISSUE THREAD

**Issue by vajahath** [sequelize/sequelize#9591]
https://github.com/sequelize/sequelize/blob/719f95b7da04e44a6a840d7c0b49ad6dfac4a41d/lib/dialects/abstract/query-generator/transaction.js#L3

https://github.com/sequelize/sequelize/blob/8a6b9b0889491dfaca9de8eec4eb5576b1a8339a/lib/dialects/mysql/query.js#L6

[and in all other places]

Is this `require('uuid')` format deprecated?

Do we need to change this to `require('uuid/[v1|v3|v4|v5]')` according to their [docs](https://github.com/kelektiv/node-uuid#quickstart---commonjs-recommended) ?

**Comment by bennygenel** [comment]
@sushantdhiman I would like to work on this if no one is since this is a fairly simple job and a really good first issue.
