### ISSUE TITLE
sequelize belongsToMany not fetch nested data

### ISSUE THREAD

**Issue by blackxMan** [sequelize/sequelize#9592]
Hello i have one problem with fetching data for belongsToMany relationship here is my implementation:

Activity -< DeliveryServer >- Server
Server Class :
`
"use strict";

module.exports = function(sequelize, DataTypes) {

  var Server = sequelize.define('server', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        len: {
          args: [1, 250],
          msg: "Server name must be between 1 and 250 characters in length"
        },
      }
    },
    
  }, {
    underscored: true,
    freezeTableName: true,
    timestamps: false,
    tableName: 'servers',
    associate: function(models) {
      Server.belongsToMany(models.activity, { as: 'activities', through: models.deliveryServer, foreignKey: 'server_id',otherKey: 'activity_id'});
    }
  });
  return Server;
};
`
Activity class:
`
"use strict";

module.exports = function(sequelize, DataTypes) {

  var Activity = sequelize.define('activity', {
    name: {
      type: DataTypes.STRING,
      field: 'name',
      allowNull: false,
      validate: {
        len: {
          args: [1, 250],
          msg: "name must be between 1 and 250 characters in length"
        },
      }
    },
    
  }, {
    underscored: true,
    freezeTableName: true,
    timestamps: false,
    tableName: 'activities',
    associate: function(models) {
      Activity.belongsToMany(models.server, {as: 'servers', through: models.deliveryServer, foreignKey: 'activity_id',otherKey:'server_id'});
      
    }
  });
  return Activity;
};
`

Code Of DeliveryServer:
`
"use strict";

module.exports = function(sequelize, DataTypes) {

  var DeliveryServer = sequelize.define('deliveryServer', {
    vhosts: {
      type: DataTypes.JSON,
      isArray: true,
      field: 'vhosts'
    },
    createdAt: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
      field: 'created_at'
    },
    updatedAt: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
      field: 'updated_at'
    },
  }, {
    underscored: true,
    freezeTableName: true,
    timestamps: false,
    tableName: 'activity_delivery_server',
    associate: function(models) {
    }
  });
  return DeliveryServer;
};
`

And at final here the find query:
`
Activity.findAndCountAll({
   order: column+' '+orderType,
   offset: offset,
   limit: limit,
   where:{deletedAt:{$eq: null}},
   include: [{ model: Server, as: 'servers', through: { attributes: ['domainName','masterIP'] }}],
   attributes: ['id', 'name', 'status','subject','from','returnPath','limit','queueIndex','emailProvider','dataTags','headers','serverPushTimeUnit', 'serverPushTimeValue', 'serverPush','createdAt','updatedAt', 'type']
})
.then(function(result) {
  res.json(result);
}).catch(function(err){
  console.log(err);
  if(err)
    res.json({count:0,rows:[]});
});
`

Thank you

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
