### ISSUE TITLE
Confused with evict and idle

### ISSUE THREAD

**Issue by Lighting-Jack** [sequelize/sequelize#9595]
## What are you doing?
I use pool to connect the database
And I set idle=15000,  evict=10000

```js
const db1 = new sequelize(
    'xxx',
    'xxx',
    'xxx',
    {
        host: 'localhost',
        port: 3306,
        dialect: 'mysql',
        pool: {
            "max": 20,
            "min": 0,
            idle: 15000,
            evict: 10000
        }
    }
);
db1
    .authenticate()
    .then(res => {
        console.log('db connected')
    })
    .catch(e => {
        console.log(e)
    })
```

## What do you expect to happen?
I thought the idle connection would be released in 15s, but it would be released in 10s which made me
confused.Please give me some advices

## What is actually happening?
I checked my database connections by sql 'show processlist', and saw the connection would released in 10s

**Comment by sushantdhiman** [comment]
Sequelize use `generic-pool` and internals are explained here https://github.com/coopernurse/node-pool/issues/178#issuecomment-327110870

Basically, `idle` decides if a connection is idle or not, say if connection is not used for 15sec then it is idle. Being "idle" does not mean it will get removed from pool. It is `evict` that will remove any idle connection. As per your config, evictor will run every 10sec and check if there are any idle connection to remove.

If we combine both `evict` and `idle`, your first connection should be removed at `20th sec`

**Comment by Lighting-Jack** [comment]
Thanks u very much
It realy helps me
