### ISSUE TITLE
isEmail validation fails on valid emails since upgrade to version 4.38.0

### ISSUE THREAD

**Issue by davesag** [sequelize/sequelize#9597]
## What are you doing?

My user model has an `email` field defined as per

```js
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
        lowercase: true,
        validate: {
          isEmail: true,
          notEmpty: true
        }
      },
```

## What do you expect to happen?

In my test code I expect the email value `miller_macejkovic99@gmail.com` (generated by Fakerjs) to pass validation

## What is actually happening?

```
  errors:
   [ ValidationErrorItem {
       message: 'Validation isEmail on email failed',
       type: 'Validation error',
       path: 'email',
       value: 'miller_macejkovic99@gmail.com',
       origin: 'FUNCTION',
       instance: [User],
       validatorKey: 'isEmail',
       validatorName: 'isEmail',
       validatorArgs: [Array],
       __raw: [Error] } ],
```

__Dialect:__ `postgres`
__Dialect version:__ `pg version 7.4.3` + `pg-hstore version 2.3.2`
__Database version:__ `circleci/postgres:10.3-alpine`
__Sequelize version:__ 4.38.0
__Tested with latest release:__ Yes. Version 4.38.0

This all worked fine with the previous version of sequelize.

**Comment by sushantdhiman** [comment]
`miller_macejkovic99@gmail.com` is an invalid gmail address

https://github.com/chriso/validator.js/issues/853
https://github.com/chriso/validator.js/issues/825
https://github.com/chriso/validator.js/pull/832

**Comment by davesag** [comment]
Hm, okay.  So the answer then is for my tests to tell `fakerjs` not to use real domains when generating test emails. Fair enough.

**Comment by Aukhan** [comment]
running into the same issue and mostly because of faker.
Version `4.38.0` upgrades validator to `10.4.0` from `9.4.1` causing faker scripts to break.
@davesag did you find a way to tell faker to handle that ?

**Comment by davesag** [comment]
`faker.internet.exampleEmail()` will do it.
