### ISSUE TITLE
Sorting according to timestamps by default

### ISSUE THREAD

**Issue by keskinsaf** [sequelize/sequelize#9607]
## What are you doing?

We call the function as:
model.findAll(condition).then(async.apply(callback, null)).catch(callback);

Associations:
models.machineData.belongsTo(models.machine, {onDelete: 'NO ACTION', foreignKey: 'machine_id'});

Model:
var model = sequelize.define(toSnake(path.parse(__filename).name), {
		machine_id: {
			type: Sequelize.INTEGER,
			primaryKey: true,
			allowNull: false
		},
		timestamp: {
			type: Sequelize.BIGINT,
			primaryKey: true,
			allowNull: false
		},
		type: {
			type: Sequelize.INTEGER,
			primaryKey: true,
			allowNull: false
		},
		value: {
			type: Sequelize.FLOAT,
			allowNull: false
		}
	},
	{
		indexes: [
			{
				fields: ['timestamp']
			}
		],
		underscored: true,
		underscoredAll: true
	}
);
```js
// code here
```
sequelizeAdaptor.findAll(model, condition, callback);
## What do you expect to happen?

I am writing a query that sorts data according to integer typed values, but when the data is returned from findAll method, I see that the data is sorted firstly according to integer typed values and then according to timestamp typed values. It is like they are grouped by integer values and then sorted according to timestamp. How can I get the data sorted only by integer values?

## What is actually happening?
It is sorted first sorted by value then sorted by timestamp (it is sorted by value, but the timestamps are also sorted for same values).

The query executed by sequelize is: SELECT `machine_id`, `timestamp`, `type`, `value` FROM `machine_data` AS `machine_data` WHERE `machine_data`.`machine_id` IN (1, 2) AND (`machine_data`.`value` >= 4570 AND `machine_data`.`value` <= 4572) ORDER BY `machine_data`.`value` desc LIMIT 0, 10;

Output produced by sequelize:
![exceldata](https://user-images.githubusercontent.com/17712763/42026251-4c7b1670-7acf-11e8-8e3d-3b42df9b46d4.png)
that is sorted by date(timestamp), too

Output produced by mysql when the query is executed directly:
![workbenchdata](https://user-images.githubusercontent.com/17712763/42026298-6d157934-7acf-11e8-9cfc-080e29cd3688.png)

__Dialect:mysql
__Dialect version:mysql
__Database version:5.7.22-0ubuntu0.16.04.1
__Sequelize version:sequelize@3.33.0
__Tested with latest release:Yes (sequelize@3.33.0)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
We no longer support v3

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
