### ISSUE TITLE
Webpack and `require(sequelize.config.dialectModulePath)`

### ISSUE THREAD

**Issue by catamphetamine** [sequelize/sequelize#9608]
We've enabled AWS X-Ray SDK in our project to benchmark and trace SQL calls.

It requires [this](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-sqlclients.html):
```js
var AWSXRay = require('aws-xray-sdk');
var mysql = AWSXRay.captureMySQL(require('mysql2'));
```

So you do have `sequelize.config.dialectModulePath` for a custom (wrapped) `mysql2` instance but it is fully dynamic:

```js
if (sequelize.config.dialectModulePath) {
  require(sequelize.config.dialectModulePath)
}
```

It won't work in Webpack because Webpack won't bundle anything for such require and will only throw "Module not found: mysql2".

Now, we've worked around it in a hacky way by using `string-replace-loader` which is set up to patch the library:

```js
const sequelizeMySQLDialectStuffPath = path.resolve(basePath, 'node_modules/sequelize/lib/dialects/mysql/connection-manager.js');
if (!fs.existsSync(sequelizeMySQLDialectStuffPath)) {
  throw new Error(`[build error] Sequelize MySQL dialect file not found: ${sequelizeMySQLDialectStuffPath}`);
}
const sequelizeMySQLDialectStuff = fs.readFileSync(sequelizeMySQLDialectStuffPath, 'utf-8');
const sequelizeMySQLDialectStuffRequire = 'require(sequelize.config.dialectModulePath)';
if (sequelizeMySQLDialectStuff.indexOf(sequelizeMySQLDialectStuffRequire) < 0) {
  throw new Error(`[build error] Sequelize MySQL dialect file doesn't match.`);
}

{
  test: /\.js$/,
  include: sequelizeMySQLDialectStuffPath,
  use: [{
    loader: 'string-replace-loader',
    options: {
      search: sequelizeMySQLDialectStuffRequire,
      replace: `require("${path.resolve(basePath, '/mysql2-wrapped-with-aws-xray.js').replace(/\\/g, '\\\\')}")`,
    }
  }]
}
```

So as you can see it's hacky and a bit fragile.

You could support something like this instead:

```js
if (sequelize.config.dialectModulePath) {
  require(sequelize.config.dialectModulePath)
} else if (sequelize.config.dialectModule) {
  // use the `sequelize.config.dialectModule` directly.
}
```
And the config would be:
```js
{
  options: {
    dialectModule: require('path/to/custom/dialect.js')
  }
}
```

**Comment by sushantdhiman** [comment]
Will accept PR

**Comment by catamphetamine** [comment]
@sushantdhiman Created a PR: https://github.com/sequelize/sequelize/pull/9609

**Comment by yvele** [comment]
Why not passing directly the module with a new option `sequelize.config.dialectModule`? 🤔 

Then instead of requiring the module it self, Sequelize will also be able to directly use the module.

I'm also struggling setting Sequelize with Webpack (and AWS X-Ray)

**Comment by sushantdhiman** [comment]
Anyone want this feature can takeover #9609 and complete tests https://github.com/sequelize/sequelize/pull/9609#issuecomment-401034305 , I'll merge it

**Comment by sallyzoughaib** [comment]
Please help me with this. I am minifying and bundling a Node.js TypeScript backend project that uses Sequelize to connect with a database. I used Webpack for this task and successfully generated the 'bundle.js' file. However, when I ran 'node dist/bundle.js,' the server started, but any request requiring a database connection resulted in an error. After debugging and investigating, I discovered that I am missing Sequelize configurations in my 'web.config.js' file. Could you please help me identify what's missing?
 this is my webpack.config.js:
var path = require('path');
var fs = require('fs');

```
var nodeModules = {};
fs.readdirSync('node_modules')
  .filter(function (x) {
    return ['.bin'].indexOf(x) === -1;
  })
  .forEach(function (mod) {
    nodeModules[mod] = 'commonjs ' + mod;
  });

module.exports = {
  mode: 'development',
  target: 'node',
  entry: './src/server.ts',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  resolve: {
    extensions: ['.ts', '.js'],
    alias: {
      '@': path.resolve(__dirname, 'src'),
      '@config': path.resolve(__dirname, 'src/config'),
      '@controllers': path.resolve(__dirname, 'src/controllers'),
      '@dtos': path.resolve(__dirname, 'src/dtos'),
      '@exceptions': path.resolve(__dirname, 'src/exceptions'),
      '@interfaces': path.resolve(__dirname, 'src/interfaces'),
      '@middlewares': path.resolve(__dirname, 'src/middlewares'),
      '@models': path.resolve(__dirname, 'src/models'),
      '@routes': path.resolve(__dirname, 'src/routes'),
      '@services': path.resolve(__dirname, 'src/services'),
      '@utils': path.resolve(__dirname, 'src/utils'),
      '@sentry/profiling-node': path.resolve(__dirname, 'node_modules/@sentry/profiling-node'),
    },
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.node$/,
        loader: 'node-loader',
      },
    ],
  },
  externals: [nodeModules],
  devtool: 'source-map',
};
```
