### ISSUE TITLE
node-gyp error while running npm install

### ISSUE THREAD

**Issue by bennygenel** [sequelize/sequelize#9610]
## What are you doing?

Trying to install sequelize on my local machine so I can work on possible contributions.

## What do you expect to happen?
`npm install` command to run with no problems.

## What is actually happening?
I get the error below while the install script running `node-gyp rebuild`

```
C:\stacktest\sequelize>npm install

> libpq@1.8.8 install C:\stacktest\sequelize\node_modules\libpq
> node-gyp rebuild


C:\stacktest\sequelize\node_modules\libpq>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  connection.cc
  connect-async-worker.cc
  addon.cc
  win_delay_load_hook.cc
..\src\connection.cc(804): warning C4996: 'Nan::MakeCallback': was declared deprecated [C:\stack
test\sequelize\node_modules\libpq\build\addon.vcxproj]
  C:\stacktest\sequelize\node_modules\nan\nan.h(929): note: see declaration of 'Nan::MakeCallbac
  k'
LINK : fatal error LNK1181: cannot open input file 'libpq.lib' [C:\stacktest\sequelize\node_modu
les\libpq\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\stacktest\sequelize\node_modules\libpq
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN marked-terminal@3.0.0 requires a peer of marked@^0.4.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libpq@1.8.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libpq@1.8.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bünyamin\AppData\Roaming\npm-cache\_logs\2018-06-28T13_07_07_942Z-debug.log
```

__Dialect:__ -
__Dialect version:__ -
__Database version:__ -
__Sequelize version:__ 5.0.0-beta.9
__Tested with latest release:__ Yes

__NodeJS version:__ 8.11.1
__NPM version:__ 5.6.0
__OS:__ Windows 10

I can happily provide any other necessary information when needed.

**Comment by sushantdhiman** [comment]
Unless you are working on a feature directly related to postgres native, there is no need to install it. So this error can be ignored.

If you really want to install "native" postgres module then you can follow https://github.com/brianc/node-pg-native#install

**Comment by bennygenel** [comment]
Thank you for your really quick response @sushantdhiman.

I checked the page you directed and saw that I already have everything needed for the install. Problem on my specific case was the version of PostgreSQL. I had version 10 and the mentioned warning was causing the issue as I am guessing. I uninstalled version 10 and installed 9.3 as it was the version on pg-native's install page and everything worked fine.

Although mine was a really specific case, I wanted to give a quick response on my situation for future readers.

Thank you again

**Comment by josechavarriacr** [comment]
> Unless you are working on a feature directly related to postgres native, there is no need to install it. So this error can be ignored.
> 
> If you really want to install "native" postgres module then you can follow https://github.com/brianc/node-pg-native#install

This solution worked for me, thanks
