### ISSUE TITLE
Contributing with a new feature

### ISSUE THREAD

**Issue by superrandres** [sequelize/sequelize#9611]
## Contributing
_I needed to divide the folders into folders to better organize my code, but I realized that the synchronization no longer worked so I decided to modify the "index.js" file in my "models" folder_

![image](https://user-images.githubusercontent.com/8306417/42039025-03a4ae74-7ab2-11e8-9d7f-09734a9051fb.png)

## What are you doing?

```js
const find = require('find')
find.fileSync(__dirname).forEach(function (file) {
  if ((file.indexOf('.') !== 0) && (!file.includes(basename)) && (file.slice(-3) === '.js')) {
    var model = sequelize['import'](file)
    db[model.name] = model
  }
})
```

## What do you expect to happen?
_I hope that this fragment can help someone, I share it because I also think that this way I should read sequelize the models_

## What is actually happening?
_It only reads the top folder because it uses readdirsync_

**Comment by sushantdhiman** [comment]
Thanks, I suggest you setup a example repository for others. You may share with your coworkers, friends using Node or write a blog about this :)

I am closing this issue as it is neither a bug nor a feature request discussion.
