### ISSUE TITLE
Cannot override rejectOnEmpty

### ISSUE THREAD

**Issue by LordJimBeam** [sequelize/sequelize#9613]
## What are you doing?
If I set rejectOnEmpty to true during initialization I cannot override it in a query anymore. I would guess the error is https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1681

```js
const sequelize = new Sequelize({
  define: {
    rejectOnEmpty: true
  }
});

model.findAll({
  rejectOnEmpty: false
});
```

## What do you expect to happen?
```findAll resolves with []```

## What is actually happening?
```findAll rejects with SequelizeEmptyResultError```

__Dialect:__ mysql (tested only mysql but suppose other dialects are affected too)
__Dialect version:__ mysql2@1.5.3
__Database version:__ 10.1.26-MariaDB-0+deb9u1 Debian 9.1
__Sequelize version:__ sequelize@4.38.0
__Tested with latest release:__ Yes, latest release is 4.38.0

**Comment by sushantdhiman** [comment]
Fixed, will be released in `v5.0.0-beta.10`
