### ISSUE TITLE
Inserting record with associations HasOne and BelongTo

### ISSUE THREAD

**Issue by Cariaga** [sequelize/sequelize#9616]
UserInfo Inserting
`app.get('/Api/v1/UserInfo/Add/:UserAccountID/:Email/:PhoneNumber/:TelephoneNumber', function (req, res) {
  //USAGE /Api/v1/UserInfo/Add/UserAccountID/Email/PhoneNumber/TelephoneNumber
  let UserAccountID = req.params.UserAccountID;
  let Email = req.params.Email;
  let PhoneNumber = req.params.PhoneNumber;
  let TelephoneNumber = req.params.TelephoneNumber;
  if(!isNullOrEmpty(UserAccountID)&&!isNullOrEmpty(Email)&&!isNullOrEmpty(PhoneNumber)&&!isNullOrEmpty(TelephoneNumber)){
  //Models.UserInfo.sync(/*{force:true}*/);//only use force true if you want to destroy replace table
    var item1 = Models.UserInfo.build({
      UserAccountID:UserAccountID,
      Email:Email,
      PhoneNumber:PhoneNumber,
      TelephoneNumber:TelephoneNumber
    });
    
    item1.save()
    .then(Success => {
      res.send("Inserted");
    })
    
    .catch(error => {
      // mhhh, wth!
      console.log("error inserting");
      res.send("error inserting " +error);
    });
  }
});`
UserInfo Displaying
`
app.get('/Api/v1/UserInfo', function (req, res) {
  let Offset =  req.query.Offset;
  let Limit =  req.query.Limit;
  let Sort =  req.query.Sort;
  if(isNullOrEmpty(Offset)&&isNullOrEmpty(Limit)&&isNullOrEmpty(Sort)){
    Models.UserInfo.sync();
    let result = Models.UserInfo.findAll({ 
      where: {
        UserInfoID: {
          ne: null//not null
        }
     }
    }).then(function(result) {
      let Data = result.map(function(item) {
          return item;
          
      });
     
      res.send(beautify(Data, null, 2, 100));
    }).catch(function(result) {//catching any then errors

      res.send("Error "+result);
    });
  }
});
`
Models.js
`
//UserInfo
const UserInfo =sequelize.define('UserInfo', {
  UserInfoID: {//PK
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true 
  },
  UserAccountID:{
    type: Sequelize.STRING,
    allowNull: false,
    foreignKey: true,
    references: {
      model: 'UserAccount',
      key: 'UserAccountID'
    }
  }
  ,
`UserAccount
const UserAccount =sequelize.define('UserAccount', {//the main schema
  UserID: {//PK only used in this part
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true 
  },
  UserAccountID:Sequelize.STRING,//primary key to connect keys
  AccessID: Sequelize.STRING,//FK 1 account can have many access control
  UserName:  {
    type :Sequelize.STRING,
    allowNull: false,
    unique: true
  },
	Password:{
    type :Sequelize.STRING,
    allowNull: false,
  },
  Verify:  Sequelize.BOOLEAN,
  ValidKey: Sequelize.STRING,
  RegisteredDate:Sequelize.DATE,
	RegisteredTime: Sequelize.TIME,
});
UserAccount.associate= function(models){
  UserAccount.hasOne(models.UserInfo,
    {
      foreignKey: 'UserAccountID'
   })
};`

  Email: {
    type :Sequelize.STRING,
    allowNull: false,
    unique: true
  },
  PhoneNumber: Sequelize.STRING,
  TelephoneNumber: Sequelize.STRING
});
UserInfo.associate= function(models){
   UserInfo.belongsTo(models.UserAccount);
};
`

## What do you expect to happen?
_I wanted to insert to UserInfo it already works without the association but i need the association for joining

## What is actually happening?
_But the output was SequelizeDatabaseError: Table 'sampledb.UserInfos' doesn't exist

_Output, either JSON or SQL_

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ ^2.15.0
__Sequelize version:__ ^4.38.0
__Tested with latest release:__ No (If yes, specify that version)

**Comment by Cariaga** [comment]
unable to insert anything on this table if i use foreignKey

`const UserInfo =sequelize.define('UserInfo', {
  UserInfoID: {//PK
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true 
  },
  UserAccountID:{
    type: Sequelize.STRING,
    allowNull: false,
    foreignKey: true,
    references: {
      model: UserAccount,
      key: 'UserAccountID'
    }
  }
  ,
  Email: {
    type :Sequelize.STRING,
    allowNull: false,
    unique: true
  },
  PhoneNumber: Sequelize.STRING,
  TelephoneNumber: Sequelize.STRING
});

UserInfo.associate= function(models){
   UserInfo.belongsTo(models.UserAccount);
};

UserAccount.hasOne(UserInfo, {
  foreignKey: 'UserAccountID',
  constraints: false,
});`

**Comment by sushantdhiman** [comment]
If you are looking for help please try to present this issue properly not just paste random unformatted stuff, extract your issue as SSCCE so it can be reproduced by others.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
