### ISSUE TITLE
Official UPSERT support with sqlite 3.24.0 (2018-06-04)

### ISSUE THREAD

**Issue by aguynamedben** [sequelize/sequelize#9629]
Thanks for the time you put into making sequelize great!

## What are you doing?
sqlite 3.24.0 (2018-06-04) added Postgres-like UPSERT support last month. https://sqlite.org/lang_UPSERT.html

The Sequelize docs say the Model.upsert for sqlite is implemented as 2 queries
> SQLite - Implemented as two queries INSERT; UPDATE. This means that the update is executed regardless of whether the row already existed or not
From http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-upsert

## What do you expect to happen?
It would be nice if Sequelize used sqlite's UPSERT. I presume it would be better for performance, and I'm doing a lot of UPSERTS. Maybe Sequelize could automatically detect the sqlite version and use UPSERT if the version is 3.24.0 or higher.

## What is actually happening?
UPSERTs work fine, but seem slow-ish. I haven't done any sophisticated benchmarking, though.

__Dialect:__ sqlite
__Dialect version:__ 3.24.0 (2018-06-04)
__Database version:__ 3.24.0 (2018-06-04)
__Sequelize version:__ 4.38.0
__Tested with latest release:__ Yes

**Comment by aguynamedben** [comment]
Here's a helper function that builds a SQLite UPSERT query using [sequelize.escape()](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-method-escape). Anecdotally, SQLite UPSERT seems insanely fast compared to the current implementation in this library (INSERT+UPDATE a single record at at time for SQLite). I'm performing UPSERTs in 100 record batches for several thousand records, and it's at least a few orders of magnitude faster. Very promising!

```js
/**
 * Build a SQLite UPSERT query using sequelize.escape()
 * https://sqlite.org/lang_UPSERT.html
 * This syntax became available in SQLite 3.24.0 (2018-06-04)
 * @author Ben Standefer
 *
 * @param {string} tableName - The table to insert the records into. This table
 * should have createdAt and updatedAt columns you wish to be automatically updated.
 * @param {string[]} columns - The columns (from the records param) to insert.
 * Do not include createdAt or updatedAt.
 * @param {Object[]} records - The objects to insert. Columns not listen in the
 * columns param will be ignored. Do not include createdAt or updatedAt, those
 * values are automatically generated.
 * @param {string[]} conflictTargets - The conflict targets that cause the
 * insert to become an update.
 *
 * @example
 * const tableName = 'phonebook';
 * const columns = ['name', 'phonenumber'];
 * const records = [{ name: 'Alice', phonenumber: '704-555-1212' }];
 * const conflictTargets = ['name'];
 * const sql = buildUpsertQuery(tableName, columns, records, conflictTargets);
 * // returns `INSERT INTO phonebook (name,phonenumber,createdAt,updatedAt) VALUES ('Alice','704-555-1212',datetime('now'),datetime('now')) ON CONFLICT(name) DO UPDATE SET phonenumber=excluded.phonenumber,updatedAt=excluded.updatedAt;`
 * await sequelize.query(sql, { type: sequelize.QueryTypes.INSERT });
 */
function buildUpsertQuery(tableName, columns, records, conflictTargets) {
  const columnsSql = columns
    .concat(['createdAt', 'updatedAt'])
    .join(',');

  // Convert the records to a SQL values string
  // ('record1column1value','record1colum2value'),('record2column1value','record2column2value')
  // Append `datetime('now')` as last 2 values to set createdAt and updatedAt
  const valuesSql = records.map(record => (
    columns
      .map(column => sequelize.escape(record[column]))
      .concat([`datetime('now')`, `datetime('now')`])
      .join(',')
  ))
    .map(recordValuesString => `(${recordValuesString})`)
    .join(',');

  const conflictSql = conflictTargets.join(',');

  // Exclude conflictTargets from the set
  // Update updatedAt, leave createdAt at it's original value (record already
  // exists)
  const setSql = columns
    .filter(column => !conflictTargets.includes(column))
    .map(column => `${column}=excluded.${column}`)
    .concat(['updatedAt=excluded.updatedAt'])
    .join(',');

  const sql = [
    `INSERT INTO ${tableName} (${columnsSql}) VALUES ${valuesSql} `,
    `ON CONFLICT(${conflictSql}) DO UPDATE SET ${setSql};`,
  ].join('');

  return sql;
}
```

**Comment by lracicot** [comment]
This is not an issue, this is a feature request and an important one.

**Comment by aguynamedben** [comment]
+1
