### ISSUE TITLE
How to disable SAVEPOINT and ROLLBACK TO SAVEPOINT on Mysql

### ISSUE THREAD

**Issue by muyu66** [sequelize/sequelize#9631]
**When trying to do :**
When i try to use TIDB (https://github.com/pingcap/tidb), it's throw a mistake "not support SAVEPOINT".So i want to learn about how to use transaction without SAVEPOINT

**Version:**
"sequelize": "^4.37.10"
"mysql2": "^1.5.3"

**PLATFORM:**
ubuntu 16.04.2
mysql 5.7

**SAMPLE CODE**
```
START TRANSACTION;
UPDATE `department` SET `actual_people`=66,`updated_at`='2018-07-04 17:37:38' WHERE `id` = '155115';
 SAVEPOINT `f1ce547a-e46d-45b1-b4c2-8811cb8e2659-sp-1`;
UPDATE `department` SET `actual_people`=65,`updated_at`='2018-07-04 17:37:38' WHERE `id` = '155115';
 ROLLBACK TO SAVEPOINT `f1ce547a-e46d-45b1-b4c2-8811cb8e2659-sp-1`;
rollback;
```

**SHOTSNAP**
It's SQL in normal MYSQL 5.7
![222](https://user-images.githubusercontent.com/20837526/42273507-f05fd83e-7fbb-11e8-8574-2ee4d811e0d8.PNG)

It's SQL in TIDB
![111](https://user-images.githubusercontent.com/20837526/42273452-c65f4920-7fbb-11e8-93b8-32874cd81627.PNG)

**Comment by muyu66** [comment]
I found it exist in FindOrCreate function.

**Comment by sushantdhiman** [comment]
I am afraid there is no option to disable savepoints, as we officially only support `mysql` I am closing this issue. `TIDB` should support this API if they claims to be MySQL compatible
