### ISSUE TITLE
Docs correction for Querytypes

### ISSUE THREAD

**Issue by ianengelbrecht** [sequelize/sequelize#9643]
In http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-method-query and http://docs.sequelizejs.com/manual/tutorial/raw-queries.html, I suggest capitalizing sequelize.QueryTypes.SELECT to Sequelize.QueryTypes.SELECT to avoid confusion as to where the QueryTypes object is located and to be consistent.

**Comment by sushantdhiman** [comment]
`QueryTypes` and most other constant types are available on both `prototype` and `constructor`
