### ISSUE TITLE
Release a new version whiteout de pg-native bug

### ISSUE THREAD

**Issue by ricardopolo** [sequelize/sequelize#9652]
Can you release please a new npm version that include this merged PR https://github.com/sequelize/sequelize/pull/9551?

The bug is stopping our project!

Thanks!

**Comment by sushantdhiman** [comment]
Ah https://github.com/sequelize/sequelize/pull/9551 was never merged, it failed for `postgres-native` and I didn't have enough time to dig in for this.

A better solution could be to replace `cloneDeep` with `Utils.cloneDeep` in internal sequelize code base.

@ricardograca how this bug is affecting you, are you trying to clone `sequelize` or some other condition is triggering this.

**Comment by ricardopolo** [comment]
The issue was fixed for me 
It was caused for a high CPU server, when the the server is 100% CPU, the error starts to happen. 

We identify the reason behind the high CPU consumption and don’t see the error again.

**Comment by lxcid** [comment]
@sushantdhiman I'm facing this issue as well, it cause memory to build up until it crashes. In the meantime the server become unresponsive. It happen fairly recently. I'm on `sequelize 4.37.10` and `pg v7.4.3`

Multiple log always show that the server hang soon after the following line in log

```
Cannot find module 'pg-native'
```

But I have no idea which code in my codebase triggering it. Any suggestion I can trace this issue?

**Comment by sushantdhiman** [comment]
Not sure what is the reason behind this, you may find more hints in https://github.com/sequelize/sequelize/issues/3781

My assumption: under heavy load Sequelize code takes some path which is trying to clone either Sequelize instance or connection (may be as part of `options`)

Been unable to pinpoint that specific condition as I lack a reliable test case

**Comment by ricardopolo** [comment]
I agree  this happens only when very heavy load. In our case and code bug with and infinite
Loop writing in the DB.

**Comment by lxcid** [comment]
> My assumption: under heavy load Sequelize code takes some path which is trying to clone either Sequelize instance or connection (may be as part of options)

This is interesting behavior to keep in mind of. If we can print out the stack trace when the pg-native is not found thrown, we might be able to get some more information?

I downgraded my sequelize/pg to see if its still happening.

I look at my metrics log and didn't notice and weird build up of cpu usage. If I have more info, I'll try to keep you guys updated. :)

**Comment by acao** [comment]
also seeing this issue
os: macOs 10.13.5
node: v8.11.3
yarn: 1.7.0
versions: 5 betas, 4.38.0 and 4.37.10

**Comment by lxcid** [comment]
fyi, downgrade didn't work for me. If there's a way for us to see find out what trigger the codepath, it will help us work around the issue though. Is there any technique you guys have in mind when deal with this kind of situation?

**Comment by lxcid** [comment]
Just want to shared that I have identify the issue to be caused by Raven having CPU spike on my server. So same issue with @ricardograca 

https://github.com/getsentry/raven-js/issues/1395

**Comment by Ricardonacif** [comment]
I can reproduce this bug consistently under no load at all with: 

```const Sequelize = require('sequelize');
const { cloneDeep } = require('lodash');

const sequelize = new Sequelize({
  dialect: 'postgres'
});

cloneDeep(sequelize);
```

Gonna try to debug this further.

**Comment by Ricardonacif** [comment]
@ricardopolo can you reopen this?
