### ISSUE TITLE
Stick to TypeScript for types declarations in comments

### ISSUE THREAD

**Issue by aercolino** [sequelize/sequelize#9654]
The comment above `Model.save` documents the return value this way:

```js
  /**
   * Validate this instance, 
   ...
   * @return {Promise<this|Errors.ValidationError>}
   */
  save(options) {
```

But [in TypeScript](https://github.com/Microsoft/TypeScript/issues/7588#issuecomment-198700729) the generic type `T` in `Promise<T>` only documents the type of the success path of a promise. 

Instead, `ValidationError` goes on the failure path because in `instance-validator.js` we read

```js
      if (this.errors.length) {
        throw new sequelizeError.ValidationError(null, this.errors);
      }
```

Besides, `ValidationError` is just one of many thrown errors.

Additionally, `this` is not a type (class) but a value (instance).

Thus, the correct return type for `Model.save` which makes sense in TypeScript is `Promise<Model>`.

A correct documentation could be:

```js
  /**
   * Validate this instance, 
   ...
   * @return {Promise<Model>} success: this, failure: Error | Errors.ValidationError
   */
  save(options) {
```

**Comment by sushantdhiman** [comment]
We follow js docs which does not support separate promise rejection API, https://github.com/jsdoc3/jsdoc/issues/1197#issuecomment-312948746 is what it will look like in future.

Not sure how TypeScript docs supports rejection type, do they have something like `@reject` if yes it will perfectly align with current setup.

Our doc are currently generated by `es-docs`, but it should still be able to print this format, you will need to locally run `npm run docs` to verify

**Comment by SimonSchick** [comment]
Closing since we ship with TS now, the docs still aren't ideal but we will work on it.
Regarding specifying rejection types isn't supported in either JSDoc or TS.
