### ISSUE TITLE
Double set() of field's value causes previous() return invalid value

### ISSUE THREAD

**Issue by oleg-tsalabionak** [sequelize/sequelize#9666]
Each call to set() overwrites 'previous()' value.

I wants to think about 'previous' values as about a 'values last saved in DB'
But now this is the 'value before last 'set' '

Example:
Accept we have 1 user with id == 1 and name == 'user' in the DB.

<pre>const User = require('./models/user');
User.findById(1).next(user => {
    console.log(user.get('name'); // output: user  OK
    console.log(user.previous('name'); // output: user  OK
    user.set('name', 'new user 1');
    console.log(user.get('name'); // output: new user 1  OK
    console.log(user.previous('name'); // output: user  OK
    user.set('name', 'new user 2');
    console.log(user.get('name'); // output: new user 2  OK
    console.log(user.previous('name'); // output: new user 1  WRONG !!! should be: user
})

**Comment by sushantdhiman** [comment]
Follow the template please

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
