### ISSUE TITLE
Seed values to primary key column on MSSQL 

### ISSUE THREAD

**Issue by hesamd** [sequelize/sequelize#9671]
## What are you doing?
For bad design decisions, we need to seed our tables with predefined primary keys, `id` in our case. However, we're getting the following error
`Seed file failed with error: Cannot insert explicit value for identity column in table 'NursingHome' when IDENTITY_INSERT is set to OFF`

Setting IDENTITY_INSERT explicitly in that seeder doesn't help as well.

```js
module.exports = {
    up: async (queryInterface) => {
        const organizations = await queryInterface.sequelize.query(
          'SELECT id from Organization;'
        );
        const organizationsRows = organizations[0];
        const ignoreSettingPk = await queryInterface.sequelize.query(
          'SET IDENTITY_INSERT NursingHome ON;'
        );
        return queryInterface.bulkInsert('NursingHome', [{
            id: 1,
            organization: organizationsRows[0].id,
```

## What do you expect to happen?
To be able to set the `IDENTITY_INSERT` in the seeder

## What is actually happening?
Keep getting the same error.

__Dialect:__ mssql
__Dialect version:__ latest
__Database version:__ mssql docker on linux
__Sequelize version:__ 4.38
__Tested with latest release:__ Yes

**Comment by mubaidr** [comment]
Any update or guidance on this issue?
