### ISSUE TITLE
dialect: mariadb

### ISSUE THREAD

**Issue by knoxcard** [sequelize/sequelize#9677]
dialect: 'mariadb', it is time...
should now be using this DB connector instead of **mysql2**...
https://github.com/MariaDB/mariadb-connector-nodejs (_Released 13 days ago_)

MariaDB provides benchmarks comparing the Connector with popular Node.js MySQL clients, including:
promise-mysql version 3.3.1 + mysql version 2.15.0
mysql2 version 1.5.3
promise-mysql  : 1,366 ops/sec ±1.42%
mysql2         : 1,469 ops/sec ±1.63%
mariadb        : 1,802 ops/sec ±1.19%

**Comment by sushantdhiman** [comment]
They don't support prepared statements just placeholder replacement? Any way as MariaDB API is close to MySQL I have no problem accepting this new dialect.

**Comment by knoxcard** [comment]
They have placeholders...check it out, i didn't notice it the first time either..

https://github.com/MariaDB/mariadb-connector-nodejs
Hit ctrl+f, then search "placeholder" (12 results on the page)

**Comment by knoxcard** [comment]
the ops/sec efficiency is making me drool!!

**Comment by sushantdhiman** [comment]
`mariadb` support is being discussed here https://github.com/MariaDB/mariadb-connector-nodejs/issues/3

**Comment by rusher** [comment]
time to close it, done in https://github.com/sequelize/sequelize/pull/10192

**Comment by knoxcard** [comment]
Correct! Thanks for the reminder.
