### ISSUE TITLE
Not able to pass TVP as an input parameter to a Stored Procedure.

### ISSUE THREAD

**Issue by DivyanshGothwal** [sequelize/sequelize#9683]
## What are you doing?
I am trying to call a stored procedure which takes TVP(Table Valued parameter) as input parameter.

```js
const Sequelize = require('sequelize');

const sequelize = new Sequelize('DbName','username','password',{
    host: 'servername',
    dialect:'mssql'
});

sequelize.authenticate().then(()=>{
    console.log("connected");
sequelize.query(' StoredProcedureName @Input1 = :input1, @Input2 = :input2'
, 
      {replacements: {  input1: 3950,   input2 : ???(How to pass a TVP?)  },
      type : sequelize.QueryTypes.SELECT
  }).then(function(results) {
    console.log(results)
}).catch((err)=>{
    console.log(err + ' Not connected');
})});

```

## What do you expect to happen?
I want to pass a TVP to the stored procedure as input2

## What is actually happening?
Not able to pass TVP to the SP

Dialect:mssql
Database version:SQL Server 2016 
Sequelize version:4.38.0

**Comment by sushantdhiman** [comment]
Sequelize does not support SP / TVP etc which is specific to MSSQL. Please refer to https://github.com/sequelize/sequelize/issues/9122 to see how you can access raw `tedious` connection to execute use stored procedures etc
