### ISSUE TITLE
Sequelize is chopping of nested key length

### ISSUE THREAD

**Issue by rahuldpi** [sequelize/sequelize#9684]
I have a model named `ManufacturerGuideline` which is nested at the 4th level. When I try to fetch the record, its chopping of `ManufacturerGuideline` keys length to 5 characters. Although the Key value stored in postgreSQL table has full length.

**Routes:**

    router.get('/:manufacturer_id', function(req, res) {
      var manufacturer_id = req.params.manufacturer_id;
      models.Manufacturer.findAll({
        where: {
          id: manufacturer_id
        },
        order: [[models.ManufacturerTab, 'sequence', 'ASC']],
        include: [{
                    model: models.ManufacturerTab, 
                    include: [{
                      model: models.ManufacturerField, 
                      include: [models.ManufacturerGuideline]
                  }]
                }
            ]
      }).
      then(function(manufacturers) {  
          res.status(200).json(manufacturers);  
      }, function(error) {  
         res.status(500).send(error);  
      });  
    });

So if the column name is `Manufacturer` it displays as `Manuf`. This issue is only appearing with `ManufacturerGuideline` table and not with the parent associated table.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by AMoreaux** [comment]
# What you are doing?

I make a query with 5 levels of include : 

``` javascript
Models.Library.findOne({
        distinct: true,
        where: {
          id: request.params.id,
          organizationId: request.auth.credentials.organizationId
        },
        include: [{
          model: Models.Section,
          include: [{
            model: Models.Category,
            include: [{
              model: Models.Subcategory,
              include: [{
                model: Models.UiComponent,
                include: [{
                  model: Models.User,
                  foreignKey: 'updated_by_user_id',
                  as: 'updated_by'
                }, {
                  model: Models.User,
                  foreignKey: 'created_by_user_id',
                  as: 'created_by'
                }]
              }]
            }]
          }]
        }]
      });
```

# What do you expect to happen?
```json
{
    "library": {
       "sections": [{
              "categories": [{
                     "subcategories": [{
                            "uiComponents": [{
                                   "updated_by": {
                                        "email": "",
                                        "firstname": "Antoine",
                                        "lastname": "Henri",
                                        "github": "",
                                        "gitlab" : "",
                                        "id":"17faa1c6-a995-40bb-872c-f8c506375cfc"
                                   }
                            }]
                     }]
              }]
       }]
}
```
# What is actually happening?
```json
{
    "library": {
       "sections": [{
              "categories": [{
                     "subcategories": [{
                            "uiComponents": [{
                                   "updated_by": {
                                        "email": "",
                                        "first": "Nicolas",
                                        "lastn": "Henri",
                                        "githu": "",
                                        "gitla": "",
                                        "id": "17faa1c6-a995-40bb-872c-f8c506375cfc"
                                   }
                            }]
                     }]
              }]
       }]
}
```

At the last step where there is the `updated_by` object, its keys are cut to only five characters. 

Dialect: postgresql
Database version: 10.3
Sequelize version: 4.37.0

**Comment by derekchan916** [comment]
@rahuldpi was there a solution to this problem?

**Comment by rahuldpi** [comment]
Actually the object key is only getting chopped while trying to output in the developer console. However, I'm able to use the whole key within the routes.

**Comment by derekchan916** [comment]
@rahuldpi interesting, i'll check it out. thanks!

**Comment by Bhanu36** [comment]
same problem i am facing now , any update on this issue?

**Comment by chanmathewrbc** [comment]
I'm running into the same issue, the object key is truncated in the response, anyone have a fix?

**Comment by AdamAld** [comment]
This is still an issue in v6. In my case, a first level association with a long key name (length: 43 characters) is being chopped off. 

Is it possible to re-open this issue?

**Comment by arpan8** [comment]
re bhai iska solution bata do koi porsu production hai

**Comment by HamzaAnis** [comment]
Use the states tag which results after chopping off the key or maybe use smaller key.

**Comment by lakinmohapatra** [comment]
Use "separate: true" .  It will work. 
`include: [{
  separate: true,
  model:  "Model name"
}]`

**Comment by ephys** [comment]
This is caused by the database having a character limit for identifiers. [`minifyAliases`](https://sequelize.org/api/v7/interfaces/options#minifyAliases) is designed to bypass the problem.

**Comment by muhammedaksam** [comment]
> Use "separate: true" . It will work. `include: [{ separate: true, model: "Model name" }]`

Separate only works for has many, right? What about belongs to many associations?
