### ISSUE TITLE
Two different tables returned by an SP are being mapped to one model

### ISSUE THREAD

**Issue by DivyanshGothwal** [sequelize/sequelize#9685]
## What are you doing?
If two different tables are returned by a Stored Procedure, i want them to be mapped to different models

```js

const Sequelize = require('sequelize');

const sequelize = new Sequelize('DbName','username','password',{
    host: 'servername',
    dialect:'mssql'
});

sequelize.authenticate().then(()=>{
    console.log("connected");
sequelize.query(' StoredProcedureName @Input1 = :input1, @Input2 = :input2'
, 
      {replacements: {  input1: 3950,   input2 : 12334 },
            model: shipments, // i am not able to specify 2 models which will be mapped to 2 tables returned by SP
      type : sequelize.QueryTypes.SELECT
  }).then(function(results) {
    console.log(results)
}).catch((err)=>{
    console.log(err + ' Not connected');
})});

```

## What do you expect to happen?
I want to specify 2 models which will be mapped to 2 tables returned by SP

## What is actually happening?
2 different tables returned by SP are mapped to same model

__Dialect:__ mssql 
__Database version:__ SQL Server 2016
__Sequelize version:__ 4.38.0

**Comment by sushantdhiman** [comment]
We dont support multiple table return, not sure how API will look like. Again with other dialects sending multi statement query will return multiple results.

For now Sequelize only supports mapping to single model and raw query mapping is still very limited, we are trying to improve that https://github.com/sequelize/sequelize/issues/5708
