### ISSUE TITLE
Return datetime without timezone when OS is linux

### ISSUE THREAD

**Issue by taozi0818** [sequelize/sequelize#9693]
`
pg: 6.4.0,
pg-hstore: 2.3.2,
sequelize: 4.37.6
`
There is a column defined as `DATE` in models.Some time data are stored in pg DB with timezone, e.g. +08:00. 

When i use `psql` tool and some GUI program to query data, it can return correct datetime with timezone.

But when i query data in code, it returns value without timezone, both `models.find` and `sequelize .query`.

And it occurs in Linux OS, e.g. CentOS, but not MacOS and Windows OS.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
