### ISSUE TITLE
Sync (force true) Not Adding New Columns

### ISSUE THREAD

**Issue by jpreese** [sequelize/sequelize#9695]
## What are you doing?

I added a couple PKs awhile ago, and am now trying to add another column, say "Another".

```js
  var ClientTenantAccess = sequelize.define('ClientTenantAccess', {
    primaryOne:
    {
      type: DataTypes.UUID,
      primaryKey: true,
      field: 'Primary_One'
    },
    primaryTwo:
    {
      type: DataTypes.UUID,
      primaryKey: true,
      field: 'Primary_Two'
    },
    Another:
    {
      type: DataTypes.BOOLEAN,
      field: 'another',
      defaultValue: true
    }
  },
    { // options
      freezeTableName: true,
      createdAt: false,
      updatedAt: false,
      underscored: true,
      tableName: 'My_Table'
    });
```

## What do you expect to happen?

  models.sequelize.sync({
    logging: console.log,
    force: true
  })

The console output should say it's adding the 'Another' column.

## What is actually happening?
Executing (default): DROP TABLE IF EXISTS `My_Table`;
Executing (default): CREATE TABLE IF NOT EXISTS `My_Table`` (`Primary_One` UUID NOT NULL REFERENCES `Primary_One` (`Primary_One`) ON DELETE CASCADE ON UPDATE CASCADE, `Primary_Two` UUID NOT NULL REFERENCES `Primary_Two` (`Primary_Two`) ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY (`Primary_One`, `Primary_Two`));

**Notice Another is not there**

Resulting in
>SequelizeDatabaseError: SQLITE_ERROR: table My_Table has no column named Another

__Dialect:__ sqlite 
__Sequelize version:__ 4

**Comment by sushantdhiman** [comment]
Sequelize does not support multiple primary keys
