### ISSUE TITLE
bulkCreate returns invalid instance

### ISSUE THREAD

**Issue by kasora** [sequelize/sequelize#9696]
## What are you doing?
```js
const Test = sequelize.define('myTest',
  {
    helloId: {
      field: 'hello_id',
      type: Sequelize.STRING,
      allowNull: false
    }
  }
);

const start = async () => {
  await Test.sync({ force: true });

  const testInstanceList = await Test.bulkCreate([
    { helloId: 'a' }
  ]);

  try {
    await testInstanceList[0].save();
  } catch (err) {
    console.log('boom');
  }
};

start();
```

## What do you expect to happen?
I want the instance from bulkCreate can use save function

## What is actually happening?
There are two params "helloId" and "hello_id" in the instance, and the helloId is undefined.

__Dialect:__ mysql
__Dialect version:__ 5.7.22
__Database version:__ 5.7.22
__Sequelize version:__ 3.31.1
__Tested with latest release:__ yes 3.33.0

**Comment by sushantdhiman** [comment]
v3 is not supported and it is not the latest version. This is fixed in v4 latest and `master`
