### ISSUE TITLE
Can I set sequelize response raw data(json object) globally without instance

### ISSUE THREAD

**Issue by sirius1024** [sequelize/sequelize#9697]
## What are you doing?

I wanna get javascript object(json) or array[json object] with sequelize queries.

```js
export const userToken = async userId => User.findOne({
    attributes: ['userToken'],
    where: {
        userId,
    },
    raw: true,
});
```

## What do you expect to happen?
I wan't set "raw: true" globally but no document. tried define: {raw: true} not working.

## What is actually happening?
I have to set raw:true everywhere.

__Dialect:__ mysql
__Database version:__ 5.7
__Sequelize version:__ ^5.0.0-beta.9

**Comment by sushantdhiman** [comment]
Yes, there no global option for that and I dont think I would like to support one

**Comment by sirius1024** [comment]
@sushantdhiman Well man, I read the document and try to code some data access layer then I think I know why you don't wanna support this. Really nice repo, thanks for your great work!
