### ISSUE TITLE
Unable to get results with associations on findOrCreate method

### ISSUE THREAD

**Issue by vicvarros** [sequelize/sequelize#9699]
Hi guys!

## What are you doing?
Having a "Customer" model which has many "Phone Numbers" models. 

Note that this relationship is not mandatory, a "Customer" may not have a "PhoneNumber".
Note that "factory" functions on the code are invoked to create correct objects for models.
Note that SQL output has been edited for better readability.

Fields for "Customer": governmentId and email.
Fields for "PhoneNumber": number.

I want to find or create based on "OR" conditions:

```js
models.Customer.findOrCreate({
  where: {
    [models.sequelize.Op.or]: [
      { governmentId: '11111111X' },
      { email: 'test@gmail.com' },
      { '$PhoneNumbers.number$': '+11 111 11 11 11' },
    ],
  },
  include: [models.PhoneNumber],
  defaults: customerFactory({
    governmentId: '11111111X',
    email: 'test@gmail.com',
    PhoneNumbers: [phoneNumberFactory({ number: '+11 111 11 11 11' })],
  }),
})
```

## What do you expect to happen?
Knowing that findOrCreate looks for a row instead of multiple rows.
I expected the query to be similar as the findAll:

```js
models.Customer.findAll({
  where: {
    [models.sequelize.Op.or]: [
      { governmentId: '11111111X' },
      { email: 'test@gmail.com' },
      { '$PhoneNumbers.number$': '+11 111 11 11 11' },
    ],
  },
  include: [models.PhoneNumber],
})
```
The SQL output is:

```sql
 SELECT
	 [Customer].[governmentId],
	 [Customer].[email], 
	 [PhoneNumbers].[number] AS [PhoneNumbers.number]
 FROM [Customer] AS [Customer] 
 LEFT OUTER JOIN 
 	[PhoneNumber] AS [PhoneNumbers] ON 
 	[Customer].[id] = [PhoneNumbers].[customerId] AND ([PhoneNumbers].[deletedAt] > '2018-07-20 08:42:29.117 +00:00' OR [PhoneNumbers].[deletedAt] IS NULL) 
WHERE (
	([Customer].[deletedAt] > '2018-07-20 08:42:29.117 +00:00' OR [Customer].[deletedAt] IS NULL) AND 
	(
		[Customer].[governmentId] = '11111111X' OR 
		[Customer].[email] = 'test@gmail.com' OR 
		[PhoneNumbers].[number] = '+11 111 11 11 11'
	)
)
```

## What is actually happening?
The subselect query has no join generated for Phone Number associated model. 
So Sequelize is giving the next error: 'The multi-part identifier "PhoneNumbers.number" could not be bound.'
The SQL output is:

```sql
SELECT 
	[Customer].*, 
	[PhoneNumbers].[id] AS [PhoneNumbers.id], 
	[PhoneNumbers].[number] AS [PhoneNumbers.number], 
	[PhoneNumbers].[createdAt] AS [PhoneNumbers.createdAt], 
	[PhoneNumbers].[updatedAt] AS [PhoneNumbers.updatedAt], 
	[PhoneNumbers].[deletedAt] AS [PhoneNumbers.deletedAt], 
	[PhoneNumbers].[version] AS [PhoneNumbers.version], 
	[PhoneNumbers].[customerId] AS [PhoneNumbers.customerId] 
FROM (
	SELECT 
		[Customer].[governmentId], 
		[Customer].[email],
	FROM [Customer] AS [Customer] 
	WHERE (
		([Customer].[deletedAt] > '2018-07-20 07:46:41.308 +00:00' OR [Customer].[deletedAt] IS NULL) 
		AND (
			[Customer].[governmentId] = '53274736C' 
			OR [Customer].[email] = 'vicvarros@gmail.com' 
			OR [PhoneNumbers].[number] = '+34 652 86 25 96'
		)
	) ORDER BY [Customer].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
) AS [Customer] 
LEFT OUTER JOIN [PhoneNumber] AS [PhoneNumbers] ON [Customer].[id] = [PhoneNumbers].[customerId] AND ([PhoneNumbers].[deletedAt] > '2018-07-20 07:46:41.308 +00:00' OR [PhoneNumbers].[deletedAt] IS NULL);
```
__Dialect: mssql
__Dialect version: 2.3.1 (tedious)
__Database version: Used with Docker container (microsoft/mssql-server-linux:2017-latest)
Microsoft SQL Server 2017 (RTM-CU9) (KB4341265) - 14.0.3030.27 (X64) 
	Jun 29 2018 18:02:47 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)
__Sequelize version: 4.37.6
__Tested with latest release: No (4.37.6)

Am I doing something wrong or the result is unexpected?
Can anyone take a look on this?

Thanks you!

**Comment by gabrielemontano** [comment]
+1
