### ISSUE TITLE
Include by Association Alias

### ISSUE THREAD

**Issue by nova706** [sequelize/sequelize#970]
As documented, you cannot eagerly load (include) an association via its alias when using a finder:

> "If an association is aliased (using the as option), you must specify this alias when including the model."

This makes it difficult to construct a finder when the query is coming from a restful client. The client would have to send the name of the model and the alias name in order for the server to perform the include in the query and the client would therefore need to know details of the data model which it should not.

I assume since the associations and there aliases are defined with the models, it should not be too difficult to perform a lookup when provided a string value to match an alias to its defined association. If that is true, it would be possible to perform a query to find an object and include its association via the association's alias.

What I would like to do is this:

``` javascript
Contact.hasMany(PhoneNumber, {as: 'phoneNumbers'});

Contact.find({
    where: { id: someId },
    include: [ 'phoneNumbers' ]
});
```

As a note, I am using the Odata v3 standard on the client side and interpreting on the server to construct the finder.

**Comment by schovi** [comment]
Its been 2 years since last post, but I am new there and this is really annoing to write almost whole association again and again. I am long time developer of Rails, where each association has exactly one name and that is all. I dont understand, why association have to be declared by model and some name (alias).
Why associations cant be just map of alias pointing to some definition. It is larger configuration, because you have to declare each one, but usage `include: ['subcategory', 'category]` across whole app will save lot of pain.

```javascript
{
  associations:  {
    subcategory: () => Lesson.belongsTo(models.Subcategory, { foreignKey: "subcategory_id"}),
    category: () => Lesson.belongsTo(models.Category, {foreignKey: "category_id"}),
    lessonContents: () => Lesson.hasMany(models.LessonContent, {foreignKey: "lesson_id"}),
    validLessonContent: () =>Lesson.hasOne(models.LessonContent.scope('valid'), {foreignKey: "lesson_id"})
  }
}
```
I am just curious and except this Sequelize is really awesome project and save us lot of time :)

**Comment by nathanmarks** [comment]
@schovi did you come up with an elegant solution for string includes?

**Comment by yozi-developer** [comment]
I had the same need - I do not want to duplicate the definition of relations everywhere.

My need is solved as follows:

   include: [
                     Model.associations.fooAlias
                 ]

In Model.associations  we have Relations grouped by aliases. I do not understand why  sequelize puts relations in "associations" property, uses them like getFooAlias() but does not apply in inclide [ 'fooAlias']

**Comment by mickhansen** [comment]
@yozi-developer `Model.associations` is an internal thing. Your choice to use it, `Model.Foo = Association` works just aswell.

We've discussed string includes and will welcome a well covered PR that just maps to `Model.associations`

**Comment by bradodarb** [comment]
I use a repository pattern that encapsulates a given Model and allows me to register includes on a hash that I can reference during queries. 


First you need to save the association on the Model during declaration:

```

'use strict';

module.exports = (sequelize, DataTypes) => {

  let tag = sequelize.define('tag', {
      id: {
        type: DataTypes.BIGINT.UNSIGNED,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false
      },
      modifiedBy: {
        type: DataTypes.BIGINT.UNSIGNED,
        allowNull: false
      }
    },
    {
      classMethods: {
        associate: (models) => {
          tag.eventIncludes = tag.belongsToMany(models.event,{through: 'eventTags'});
        },
        scopes: () => {
          tag.addScope('minimal', {
            attributes: {
              exclude: ['modified', 'modifiedBy', 'created']
            }
          });
        }
      },
      timestamps: true,
      createdAt: 'created',
      updatedAt: 'modified',
      deletedAt: 'deleted',
      paranoid: true
    });

  return tag;

};
```

Then in a Model's repository I register the includes that I want on an object hash:

```

'use strict';

const Path = require('path');
const Promise = require('bluebird');
const Repository = require(Path.join(__dirname, '../dao'));

function TagRepository(dao) {
    Repository.call(this, dao);
    this.__includeHash.events = {
        association: dao.eventIncludes,
        through: { attributes: [] }
    };
    
}

TagRepository.prototype = Object.create(Repository.prototype);

module.exports = (server) => {

    return {
        name: 'TagRepository',
        instance: new TagRepository(server.plugins.dal.models.tag)
    };

};

```


Now you can call the repository methods and pass in an array of strings for the includes you want:


```

  getById: function (id, attributes, includes) {

    var op = new Promise((resolve, reject) => {
      let q = {};

      if (attributes) {
        q.attributes = attributes;
      }
      if (includes) {
        q.include = [];
        includes.forEach(include => {
          if (this.__includeHash[include]) {
            q.include.push(this.__includeHash[include]);
          }
        });
      }
      this.__dao.findById(id, q)
        .then((result) => {
          resolve(result);
        })
        .catch((err) => {
          console.error('Error getting object', err, err.stack);
          reject({error: err, message: 'Error getting object'});
        });
    });

    if (this.__isRaw) {
      return Repository.result(op);
    } else {
      return op;
    }
  }

```




 Not quite as easy as having it built in but works pretty well.

**Comment by reinert** [comment]
Does `include: ['subcategory', 'category]` work?

**Comment by bradodarb** [comment]
@reinert, yep.

https://github.com/bradodarb/repository-rdbms-dal/

**Comment by kapad** [comment]
Has support been added for matching the the include values by a string that equals the association alias?

**Comment by BigMurry** [comment]
I have encountered the same issue as @kapad mentioned.

**Comment by mattcoll** [comment]
@kapad Try this: 
`User.findOne(
{
     where: {
          id: someId
     }
},
{
     include: [
     { model: Phone, as: 'phones' }
     ]
})
.then(function whatever(user) {
  // do something with user
});`

**Comment by kapad** [comment]
@mattcoll That works, but it isn't a fix for my comment. It's simply defining the alias for the specific query. I want to be able to use the same alias name that I have defined in the models files. That isn't possible and throws an error, though the docs clearly say that it is possible.

**Comment by miguelalche** [comment]
Exactly the same is happening to me! 
It also generates me doubts, because, lets say a user hasOne Media as 'profile_picture' and hasMany media as 'photos' 
how do you query the user including just the profile picture?

**Comment by kapad** [comment]
I don't think this issue is as yet fully fixed and should still be open. Re: [my previous comment](https://github.com/sequelize/sequelize/issues/970#issuecomment-306068003)

**Comment by hypeJunction** [comment]
I think what would make sense is to allow `include` to be a callback function, which receives a model self. The problem I am facing is that associations are defined after the model is defined, so if I were to add `include` to `defaultScope` there are no concretes to use as Model or Association (in a situation where models cross-reference in each with foreign keys, it's a total nightmare).

```
include: (models, associations) => {
     return [
        {
            model: models.PhoneNumber,
            as: 'phone_number',
        },
        {
             association: associations.Avatar,
             as: 'avatar',
         }
    ]
}
```

**Comment by hypeJunction** [comment]
Here is what I ended up doing, in case it helps anyone. Note the unfortunate name collision for Associations (I am working with a pre-existing database that had Associations as in Groups/Organizations).

```js
User.associate = (models) => {
        User.Avatar = User.belongsTo(models.Upload, {
            as: 'avatar',
            foreignKey: 'avatar_id',
            constraints: false,
        });

        User.ReferredWithCode = User.belongsTo(models.ReferralCode, {
            as: 'referred_with_code',
            foreignKey: 'referral_code_id',
            constraints: false,
        });

        User.Associations = User.hasMany(models.AssociationMembership, {
            as: 'associations',
            foreignKey: 'user_id',
        });

        User.addScope('defaultScope', {
            include: [{
                association: User.Associations,
                attributes: ['id', 'active', 'memb_number'],
                include: [{
                    model: models.Association,
                    as: 'association',
                }],
            }, {
                association: User.Avatar,
            }, {
                association: User.ReferredWithCode,
            }],
            attributes: {
                exclude: ['avatar_id', 'referral_code_id'],
            },
        }, {
            override: true,
        });
    };
```

**Comment by cubo1123** [comment]
one of my biggest problems using ES6 to declare the associations it was because the static method is never called by himself so i has to call it before start doing requests

```
const schema = new ApolloServer({
  typeDefs,
  resolvers,
  playground: {
    endpoint: "/graphql"
  },
  context: {
    CostPostgreSql: CostPostgreSql.init(sequelize),
    PricePostgreSql: PricePostgreSql.init(sequelize),
    ProductPostgreSql: ProductPostgreSql.init(sequelize)
  }
});
ProductPostgreSql.associate(sequelize);
PricePostgreSql.associate(sequelize);
CostPostgreSql.associate(sequelize);

const app = express();
schema.applyMiddleware({ app });

app.listen(3000, () => {
  console.log("Live on http://localhost:3000/graphql");
});
```

i declare my relations as follows in the products model, the id of each product is inside of each cost and price element so i use belongsTo when the id is going to be on the source and hasMany when the id is going to be on the target
```
static associate({ models }) {
    this.belongsTo(models.Unit, { foreignKey: "id" });
    this.belongsTo(models.Provider, { foreignKey: "id" });
    this.hasMany(models.Cost, { foreignKey: "product" });
    this.hasMany(models.Price, { foreignKey: "product" });
  }
```

and on the costs and prices models i declare something like 

```
  static associate({ models }) {
    this.belongsTo(models.Product, { foreignKey: "id" });
  }
```
to the moment of make a query i did something like 
```
import { CostPostgreSql } from "../models";
import { PricePostgreSql } from "../models";
db
    .findAll({
      where: { id },
      include: [
        {
          model: CostPostgreSql
        },
        {
          model: PricePostgreSql
        }
      ]
    })
    .then(response => {
      console.log("Exito");
      console.log(JSON.stringify(response));
      return response;
    })
    .catch(err => {
      console.log("fracaso");
      console.log(err);
      return err;
    });
```

**And everything is going well**

**Comment by DanielOverdevestPZH** [comment]
Hi all, for persons who also had issues with `includes` of aliased models. This is my generic code to dynamic include (aliased) associated models.

```nodejs
            let params = { order: [ ['createdAt', 'DESC'] ] }
            let models = require('../models/index');
            let model = models['NAMEOFYOURMODEL'];
            // Filter results based on params.id
            if (req.params.id) {
                params.where = { id: req.params.id }
            }
            // Dynamic include other models using a special `include` header.
            if ('include' in req.headers) {
                params.include = req.headers.include.split(',').filter(modelAlias => modelAlias in model.associations).map(modelAlias => ( {
                        model: model.associations[modelAlias].target,    // <---------- THIS IS WHERE THE MAGIC HAPPENS (.target)
                            as: modelAlias,
                            // where: { deletedAt: { $eq: null } },
                            required: false
                            }));
            }
            
            params.limit = req.query.limit;
            params.offset = req.skip;
            
            // Build sorting for query.
            if (req.query.sort) {
                params.order = Object.entries(req.query.sort);
            }
            // If filter for status is present, add to query.
            if (req.query.filter) {
                // Exclude projects without status.         
                params.where = {}
                for (const [key, value] of Object.entries(req.query.filter)) {
                    params.where[key] = { [Op.in]: value.split(',')};
                }
                // Object.assign({}, whereClause.status, {
                //     [Op.in]: req.query.filter.split(',')
                //     })
            }
            model.findAndCountAll(params)
                .then(results => {
                    const itemCount = results.count;
                    const pageCount = Math.ceil(results.count / req.query.limit);
                    res.json({
                        [model.name]: results.rows,
                        pageCount,
                        itemCount,
                        pages: paginate.getArrayPages(req)(3, pageCount, req.query.page)
                    });
          }).catch(error => res.status(500).json({error: error.message}))
```
