### ISSUE TITLE
Order By multiple Columns

### ISSUE THREAD

**Issue by yangjiedage** [sequelize/sequelize#9705]
## Order by multiple columns

I want to order the query result by multiple columns.But I don't know how to do.

This code can order the result by 'created_at'.Actually, the sql is 'order by created_at DESC'
```js
model.findAll({
    order: [
      ['created_at', 'desc']
    ],
    where: {}
  })

//Sql
select * from 'table_name' order by 'created_at' DESC
```

But How to realize the order by multiple columns?
Is there any syntax like the code below in sequelize ?
```js
model.findAll({
    order: [
      [['created_at', 'id'], 'desc']
    ],
    where: {}
  })

// Sql
select * from 'table_name' order by 'created_at', 'id' DESC
```

**Comment by sushantdhiman** [comment]
```js
order: [
   ['created_at', 'desc'],
   ['id', 'desc']
]
```

```js
order: [
   [sequelize.literal('created_at, id'), 'desc']
]
```

**Comment by yangjiedage** [comment]
Thanks bro!

**Comment by yangjiedage** [comment]
@sushantdhiman Thanks bro!

**Comment by karankapur999** [comment]
@sushantdhiman 

Can you please check the error in this syntax 

order: [global.SequelizeModule.literal(["date", "ASC"],["header_id", "ASC"],["group_id", "ASC"],["line_type", "ASC"])]
 I am using     "sequelize": "5.12.3",  "pg": "6.4.1",
?
