### ISSUE TITLE
Joining table multiple times results in correlation name being used multiple times

### ISSUE THREAD

**Issue by me21** [sequelize/sequelize#9706]
I have the following models:

```
const User = orm.define('user', {
    login: Sequelize.DataTypes.STRING,
    password: Sequelize.DataTypes.STRING,
    is_manager: Sequelize.DataTypes.BOOLEAN,
    notes: Sequelize.DataTypes.STRING
});

const Bike = orm.define('bike', {
    model: Sequelize.DataTypes.STRING,
    photo: Sequelize.DataTypes.BLOB,
    color: Sequelize.DataTypes.STRING,
    weight: Sequelize.DataTypes.FLOAT,
    location: Sequelize.DataTypes.STRING,
    is_available: Sequelize.DataTypes.BOOLEAN
});

const Rate = orm.define('rate', {
    rate: Sequelize.DataTypes.INTEGER
});
Rate.belongsTo(User);
User.hasMany(Rate);
Rate.belongsTo(Bike);
Bike.hasMany(Rate);
```

And I'd like to select bikes with their average rates, plus all rates of the current user:

```
        Bike.findAll({
            attributes: {include: [[Sequelize.fn('AVG', Sequelize.col('rates.rate')), 'rate_avg']],
            },
            include: [{
                model: Rate,
                attributes: []
            }, {
                model: Rate,
                include: [{
                    model: User,
                    where: {
                        login: req.user.login
                    }
                }]
            }],
            group: Object.keys(Bike.rawAttributes).map(key => 'bike.' + key) // group by all fields of Bike model
        })
```

It constructs the following query: `SELECT [bike].[id], [bike].[model], [bike].[photo], [bike].[color], [bike].[weight], [bike].[location], [bike].[is_available], AVG([rates].[rate]) AS [rate_avg], [rates].[id] AS [rates.id], [rates].[rate] AS [rates.rate], [rates].[userId] AS [rates.userId], [rates].[bikeId] AS [rates.bikeId], [rates->user].[id] AS [rates.user.id], [rates->user].[login] AS [rates.user.login], [rates->user].[password] AS [rates.user.password], [rates->user].[is_manager] AS [rates.user.is_manager], [rates->user].[notes] AS [rates.user.notes] FROM [bikes] AS [bike] LEFT OUTER JOIN [rates] AS [rates] ON [bike].[id] = [rates].[bikeId] LEFT OUTER JOIN ( [rates] AS [rates] INNER JOIN [users] AS [rates->user] ON [rates].[userId] = [rates->user].[id] AND [rates->user].[login] = N'user' ) ON [bike].[id] = [rates].[bikeId] GROUP BY [bike].[id], [bike].[model], [bike].[photo], [bike].[color], [bike].[weight], [bike].[location], [bike].[is_available];`

And fails: `SequelizeDatabaseError: The correlation name 'rates' is specified multiple times in a FROM clause.`

How do I write the query right? Please consider fixing it if it's impossible to do what I need at the moment.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by me21** [comment]
Done: https://stackoverflow.com/questions/51480266/joining-same-table-multiple-times-with-sequelize. @sushantdhiman could you please take a look?
