### ISSUE TITLE
connect to amazon rds over ssl in sequelize

### ISSUE THREAD

**Issue by dagda1** [sequelize/sequelize#9712]
I am trying to connect to a mysql amazon RDS connection over ssl from sequelize:

my config looks like this:

```
      "production": {
        "username": "aa",
        "password": "aa",
        "database": "db",
        "host": "hots.eu-west-1.rds.amazonaws.com",
        "dialect": "mysql",
        "port": "3306",
        "logging": true,
        "pool": { "maxConnections": 5, "maxIdleTime": 30 },
        "language": "en",
        "ssl": true,
        "dialectOptions": { "ssl": true }
      }

```
I am getting a `SequelizeConnectionError: connect ETIMEDOUT` error.

Do I have to reference the `ca` in the `dialiectOptions` or is `ssl: true` enough?

Is there a way to get more logging as to what is going on?

**Comment by dagda1** [comment]
`"ssl": true` is enough :)

**Comment by tylercollier** [comment]
For anyone else who comes here, the `"ssl": true is enough` phrase is referring to what needs to go within the `dialectOptions` section. The other `"ssl": true` outside of `dialectOptions` does nothing.
