### ISSUE TITLE
Has Many relation issue when using sourceKey

### ISSUE THREAD

**Issue by sivamsis** [sequelize/sequelize#9713]
## What are you doing?
To get the associated table results

Hi,

I'm trying to select hasMany relation results when using the same table and same field and it results in an error because the source table field which is used for the join is the wrong one (primary key instead of the configured source key).

var Child = sequelize.define('child', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        field: 'state_id'
    },
    intakeID: {
        type: DataTypes.STRING(45),
        allowNull: false,
        field: 'intake_number',
        references: {
            model: "intakes",
            key: "intake_number"
        }
    }
})

var Parent = sequelize.define('parent', {
    _id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        field: 'intake_id'
    },
    id: {
        type: DataTypes.STRING(45),
        allowNull: false,
        unique: true,
        field: 'intake_number',
        defaultValue: ''
    }
})

Parent.states = Parent.hasMany(Child, {
    onDelete: 'cascade',
    foreignKey: "intakeID",
    sourceKey: "id",
    as: "states"
});

## What do you expect to happen?
To get the associated table results

## What is actually happening?
An error is thrown because the key field that is used in the final join is the primary key instead of the field real name - "Intake_number"
LEFT OUTER JOIN [intake_states] 
 AS [states] ON [intakes].[intake_id] = [states].[intake_number] 

After looking at the code, I believe that the problem is in the lib/associations/has-many.js file, lines 88-89. I think instead of this.sourceKey it should be this.sourceKeyField.
After replacing this variable and testing, it seems to work great.

// This lines - 88-89
if (this.source.fieldRawAttributesMap[this.sourceKey]) {
  this.sourceKeyAttribute = this.source.fieldRawAttributesMap[this.sourceKey].fieldName;

// Should be maybe changed to
if (this.source.fieldRawAttributesMap[this.sourceKeyField]) {
  this.sourceKeyAttribute = this.source.fieldRawAttributesMap[this.sourceKeyField].fieldName;

__Dialect:mssql 
__Dialect version:4.37.8
__Database version:_Sql Server 2012
__Sequelize version:4.37.8
__Tested with latest release:yes, 4.38.0

**Comment by sushantdhiman** [comment]
Fixed in master https://github.com/sequelize/sequelize/blob/master/lib/associations/has-many.js#L84
