### ISSUE TITLE
model.create call is not returning an id sometimes

### ISSUE THREAD

**Issue by dbrinda-db** [sequelize/sequelize#9722]
Sometimes calling model.create does not return a model with an id, even though the row is created.

model:

sequelize.define(
    'Template',
    {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
      },
      hashCode: {
        type: DataTypes.CHAR(64),
      },
      name: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      template: {
        type: DataTypes.TEXT,
      },
      attrs: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
    }, {
      indexes: [
        {
          unique: true,
          fields: ['hashCode'],
        },
      ],
      timestamps: true,
      paranoid: true,
    },
  );

call:

 model.create(
          template,
          { fields: ['template','name','attrs','hashCode'], logging: false })
          .then(val => {
            const id = val.get({ plain: true }).id;
            if (!id) {
              logger.error('Sequelize failed to return id for some reason.', val.get({ plain: true }));
            }
          })

## What do you expect to happen?
"val" should have an id since it was added to the database.

## What is actually happening?
sometimes it does not have an id.

{ id: null,
  name: 'abc',
  hashCode: 'ea2e1f00f7ce5cf401a44e82353c563ec3b96f22ab8ca1b50bb78bc5d05bb727',
  template: 'test',
  updatedAt: 2018-07-26T00:44:02.866Z,
  createdAt: 2018-07-26T00:44:02.866Z
 }

__Dialect:__ mysql
__Database version:__ 5.6.10
__Sequelize version:__ 4.38
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Not sure of reason, do you have any hooks? Can you isolate this issue as something related to Sequelize?
