### ISSUE TITLE
sequelize.sync() should add missing columns by default

### ISSUE THREAD

**Issue by oger000** [sequelize/sequelize#9731]
## What are you doing?
I try to use sequelize.sync() to add missing tables and columns in a non-destructive manner to an existing database.

## What do you expect to happen?
`sequelize.sync()` should add missing columns without the 'alter' option.

The two main reasons for databases being out of sync are missing tables and missing columns. The current default behaviour of sequelize.sync() without options is to automatically add missing tables to the database, but not missing columns.
Both can be done without the risk of loosing data - so it should be done.

`sequelize.sync({alter: true})` does add missing columns by now, but is too dangerous because of loosing content.
Sequelize-migration is a powerful tool, but in many cases it os overkill.

I will prepare a pull-request.

## What is actually happening?
Missing columns are not added to tables.

__Tested with latest release:__ v4.38.0
__Tested with latest release:__ v5.0.0-beta.10

**Comment by sushantdhiman** [comment]
`sync` without `alter: true` should not modify / add / remove columns

Please check https://github.com/sequelize/sequelize/pull/9732#issuecomment-409099129

**Comment by sostenesapollo** [comment]
This Works fine. `alter: true`, thanks
