### ISSUE TITLE
findAndCountAll with virtual columns and "having", drops virtual column in the count query.

### ISSUE THREAD

**Issue by subatomicglue** [sequelize/sequelize#9739]
__Dialect:__ mysql
__Database version:__ 5.7
__Sequelize version:__ 3.30

**Query with findAll()   (works)**:
the `attributes`:
```
attributes = [
    'id',
    [sequelize.literal( `select 1` ), `has_access`]
];
```
obviously I have different code than `select 1` but you get the idea: I am creating a virtual column to filter the results by some permission logic.

and `having`:
```
having = {'$has_access$': 1};
```

This works using `findAll()`

**Using findAndCountAll()   (doesn't work)**
`findAndCountAll` makes 2 queries, and in the _count_ query seems to be dropping all attributes but the `count(id)` - which causes an error with the `having` referring to unknown column.   

sequelize is generating the following:
```
SELECT count(mytable.id) AS count FROM mytable having has_access=1
```

Which is missing my virtual column attribute!   
Is there a way to include my attribute / virtual column?

**Alternate way:  Using count() and findAll()   (which doesn't work)**
```
let [countResult, findResult] = await Promise.all([ mytable.count(optionsObj), mytable.findAll(optionsObj) ]);
let result = {count: countResult, rows: findResult};
```

and virtual column is now more complicated
```
attributes = [
    'id',
    [sequelize.literal( `SELECT permission from mytable_permissions
                                 where mytable_id=mytable.id` ), `has_access`],
];
```

which generates:
```
SELECT `mytable`.`id`,
         (SELECT permission from mytable_permissions where mytable_id=mytable.id) AS `has_access`, 
         count(`mytable`.`id`) AS `count` FROM `mytable` HAVING `has_access` = 1;
```

which creates a different error:
```
ER_MIX_OF_GROUP_FUNC_AND_FIELDS: In aggregated query without GROUP BY, expression #1 of
 SELECT list contains nonaggregated column 'mytable.id'; this is incompatible with
 sql_mode=only_full_group_by
```

Seems like a bug... or unsupported feature of using subqueries.   Any ideas?

Have you considered using `SQL_CALC_FOUND_ROWS` and `SELECT FOUND_ROWS()` as an alternate way to count?   Perhaps I can generate a raw MySQL query with `findAll()`, and wrap with   `SQL_CALC_FOUND_ROWS` and `SELECT FOUND_ROWS()`...

**Comment by sushantdhiman** [comment]
v3 is no longer supported, please try with `master`

**Comment by subatomicglue** [comment]
Using 
MySQL 5.7
Sequelize 4.38

Same error, still valid as above:
```
 "err": {
        "name": "SequelizeDatabaseError",
        "parent": {
            "code": "ER_BAD_FIELD_ERROR",
            "errno": 1054,
            "sqlState": "42S22",
            "sqlMessage": "Unknown column 'has_access' in 'having clause'",
            "sql": "SELECT count(`mytable`.`id`) AS `count` FROM `mytable` AS `mytable` HAVING `has_access` = 1;"
```

**Comment by subatomicglue** [comment]
please re-open
