### ISSUE TITLE
Creating with associations - still buggy?

### ISSUE THREAD

**Issue by ghs** [sequelize/sequelize#9742]
## What are you doing?
I've commented some weeks ago in #4708 but most probably old issues are filtered :)
So, copy paste from there:

@mickhansen most probably I am doing something wrong but I am still getting the same error even on v.5.0.0-beta.9
This is what I have and get:

```js
Items = db.define('items', {
  id: {
    type: Sequelize.INTEGER,
    allowNull: true,
    primaryKey: true
  },
  name: {
    type: Sequelize.STRING,
    allowNull: false
  },....
});

ItemSettings = db.define('settings', {
  item_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
    primaryKey: true
  },
  photo: {
    type: Sequelize.STRING,
    allowNull: false
  },....
});

Settings = Items.hasOne(ItemSettings, {
  foreignKey: 'item_id',
  as: 'setting'
});


Item.create({
    name: 'test'
    setting: { photo: 'file.jpg' }
  }, {
    include: [
      Settings
    ]
  })
```

## What do you expect to happen?
Create two records within the two tables.

## What is actually happening?
The response is : { SequelizeValidationError: notNull Violation: settings.item_id cannot be null
A record in items table is created correctly but fails for settings.

**Comment by janmeier** [comment]
When testing on latest master I get ` null value in column "id" violates not-null constraint`, because of a missing `autoIncrement: true` on item. After adding that it works fine

**Comment by IgorSzymanski** [comment]
> When testing on latest master I get `null value in column "id" violates not-null constraint`, because of a missing `autoIncrement: true` on item. After adding that it works fine

Please, elaborate. I have no idea what you mean by "on item". What item? If I set `autoIncrement: true` on both foreign key and the ID, I get `Invalid Instance definition. Only one autoincrement field allowed.`

**Comment by asyba** [comment]
I have the same bug

**Comment by asyba** [comment]
If I have autoIncrement: true and aslo in my DB I have " seq_id int auto_increment not null," the associaton item to insert got this error "notNull Violation: xxxx be null"
