### ISSUE TITLE
Bug passing parameters to umzug

### ISSUE THREAD

**Issue by ricardopolo** [sequelize/sequelize#9743]
## What are you doing?
Configuring sequelize client for migrations, using a `.sequelizerc` file that looks like this:

```js
const path = require('path');

module.exports = {
  'config': path.resolve('migrations/config'),
  'migrations-path': path.resolve('migrations'),
  'seeders-path': path.resolve('migrations/seeders'),
  'models-path': path.resolve('migrations/models')
};
```

## What do you expect to happen?
This should work without alerts.

## What is actually happening?
It's throwing warnings 
<img width="516" alt="image 2018-07-30 at 11 43 25 am" src="https://user-images.githubusercontent.com/1263856/43410825-d9dafd32-93ed-11e8-9415-c45cb4c638b1.png">
Related to this line in umzug https://github.com/sequelize/umzug/blob/3f7c126bedd81e5572721e00282644112cc2d2a7/src/index.js#L471

Looks like you are not passing `config.js` and `model.js` to umzug, but just passing `config` and `models`, which does not match the expected pattern.

Dialect:  postgres
Sequelize version: v4.38.0
Tested with latest release: Yes

**Comment by sushantdhiman** [comment]
Please report this issue to CLI project, better submit a PR with test and I will merge / release it
