### ISSUE TITLE
Defining toJSON() as instance method no longer works

### ISSUE THREAD

**Issue by hallvors** [sequelize/sequelize#9745]
## What are you doing?

```js
sequelize.define('user', {
  name: Sequelize.STRING,
  adminSecret: Sequelize.STRING,
}, {
    instanceMethods: {
      toJSON: function() {
        var values = Object.assign({}, this.get());
        delete values.adminSecret;
        return values;
      }
    }
});

// then, in Express code

models.user.findOne({where: {id: req.params.id}})
.then(req.json);

```

## What do you expect to happen?
_Sending a JSON serialisation without an *adminSecret* property._

## What is actually happening?
_Sequelize's own toJSON() is called instead of the instance method. Hence *adminSecret* is included in the serialisation and the API response._

This is a regression from a previous Sequelize version (although perhaps the reason was that Sequelize didn't define a toJSON() method in that previous version? Not sure)

__Dialect:__ postgres (assumed to be any)
__Sequelize version:__ 
├─ sequelize-cli@4.0.0
└─ sequelize@4.38.0
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Read v4 migration guide first http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

**Comment by hallvors** [comment]
Oh, apologies. I missed that because I've bookmarked the apparently older docs on http://sequelize.readthedocs.io - might those be either updated or removed?

**Comment by sushantdhiman** [comment]
We are hosting v3 docs on readthedocs but moved to selfhosted domain for v4 and future docs
