### ISSUE TITLE
afterFind hook not modifies the amount of models in result set.

### ISSUE THREAD

**Issue by vasilich6107** [sequelize/sequelize#9746]
## What are you doing?
I am trying to modify the result set. I am interested in excluding some records.
For example findAll returns 3 records. And I want to leave only first one relying on amount of different criteria.

```js
hooks: {
  afterFind(result) {
    // the input result contains three models

    // some iterations over result set that will exclude unnecessary items goes here
    // ...

    return [result[0]];
  },
},
```

## What do you expect to happen?
I expect that afterFind hook will leave only one model.

## What is actually happening?
But there are still three models in result set.

**Comment by vasilich6107** [comment]
Why it was closed?

**Comment by sushantdhiman** [comment]
Issue template
