### ISSUE TITLE
Group by is propagating to separated includes

### ISSUE THREAD

**Issue by mjamado** [sequelize/sequelize#9748]
## What are you doing?
I have structures like this:

`News » hasMany » NewsTranslations`
`News » hasMany » Sections » hasMany » SectionsTranslations`

Sometimes I need the full structure, sometimes half, sometimes there's a where condition to the title of one of the translations. Bottom line is, I have semi-demi-ORM before the Sequelize ORM which builds (among other things) the necessary includes.

Because the `findAndCountAll` is sort of broken in v4 (I've heard it's fixed on v5, but can't upgrade on account of other stuff), I opted to `separate: true` the `hasMany` associations **if and only if** that association is not being used on `where` or `order`. If it is, I need to `group` by the main table primary key.

The problem arises because Sequelize applies that same `group` to the `separate`'d queries - which, of course, breaks them.

## What do you expect to happen?
Not apply `group` to associations which are `separate`.

## What is actually happening?
All hell breaks loose.

## Suggestion
A simple modification to [`model.js` on line 1681](https://github.com/sequelize/sequelize/blob/2c3a6e715d8684a489daac75ce588de3ef807689/lib/model.js#L1681) works:
```js
        // _.omit(options, 'include', 'attributes', 'order', 'where', 'limit', 'offset', 'plain'),
        _.omit(options, 'include', 'attributes', 'order', 'where', 'limit', 'offset', 'plain', 'group'),
```
But can it be done? Will it break something else for someone? Can it land on v4, or only for v5?

**Comment by sushantdhiman** [comment]
Will accept PR with short test case

**Comment by mjamado** [comment]
If somebody could pretty please include the pull request on v5.0.0-beta.11 and release it... :pray:

**Comment by sushantdhiman** [comment]
Thanks for the PR, fix will be released as `5.0.0-beta.11`, may be this weekend :)

**Comment by sushantdhiman** [comment]
Sorry my main work laptop is out of commission, which contain Sequelize dev setup. I wanted to include a few more changes to new release, you will have to wait for a few more days.

Meanwhile you can directly use `sequelize/sequelize` (for master branch) in your `package.json`

**Comment by mjamado** [comment]
Wow, 5+ years of dealing with `package.json` and `npm`, didn't know that repository trick. Thanks a lot!

**Comment by tizzyapunkt** [comment]
It seems that this issue still exists.
I am on 5.8.6 and the GROUP BY clause gets added to the `separate: true` include. 
@mjamado, can you confirm that?
