### ISSUE TITLE
Question on onUpdate/onDelete

### ISSUE THREAD

**Issue by usubram** [sequelize/sequelize#9756]
## What are you doing?

I see onUpdate and onDelete is wrapped within references. Why? is this is intentional or a bug? i'm trying to do `updatedAt timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),`

```js
sequelize.define('table', {
    createdAt: {
      type: DataType.TIMESTAMP,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    },
    updatedAt: {
      type: DataType.TIMESTAMP,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP'),
      onUpdate: 'CURRENT_TIMESTAMP'
    }
)
```

## What do you expect to happen?
```
CREATE TABLE `pairings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
```

## What is actually happening?
```
CREATE TABLE `pairings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP)
```

This is because of https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query-generator.js#L363 expecting `references` to include for on update and on delete.

```if (attribute.references) {
     ....

      if (attribute.references.key) {
        template += ' (' + this.quoteIdentifier(attribute.references.key) + ')';
      } else {
        template += ' (' + this.quoteIdentifier('id') + ')';
      }

      if (attribute.onDelete) {
        template += ' ON DELETE ' + attribute.onDelete.toUpperCase();
      }

      if (attribute.onUpdate) {
        template += ' ON UPDATE ' + attribute.onUpdate.toUpperCase();
      }
    }
```

__Dialect:__ mysql
__Sequelize version:__ latest
__Tested with latest release:__ 4.38.0

**Comment by sushantdhiman** [comment]
If you are using migrations or managing schema in any way other than `sync`, I suggest you just define type as `Datatypes.DATE` and define actual default value on actual table itself.

You can define a custom type in this way as well

```js
updatedAt: {
  type: 'timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
}
```

If you are going to use only Sequelize to insert records then I suggest you go with standard [timestamps](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#timestamps) which Sequelize will automatically manage for you.

**Comment by sushantdhiman** [comment]
> I will try it. from what i understand the below definition with timestamps:true will create both createdAt and updateAt column for me and will automatically update timestamp at updateAt on update to the record. does that sound right?

Yes, that is correct.

> Either way, i don't get the rational behind tying onUpdate with references.

Because these options are used to set constraint cascade specification which only work with `references`. So you defined `references` and optionally `references.onUpdate, references.onDelete` to define behaviour of child record when parent record primary key gets updated or row got deleted.
