### ISSUE TITLE
server requires auth switch but no auth switch handler provided

### ISSUE THREAD

**Issue by liangtongzhuo** [sequelize/sequelize#9758]
server requires auth switch but no auth switch handler provided

Please help me.

![image](https://user-images.githubusercontent.com/16540329/43639678-a235ed8c-974f-11e8-81bd-bb81aed88785.png)

**Comment by liangtongzhuo** [comment]
![image](https://user-images.githubusercontent.com/16540329/43939438-c63eae9c-9c9c-11e8-87c8-ca5ace478cc6.png)

Look at the parameter, solved。

**Comment by ivanninet** [comment]
@liangtongzhuo pls help, how you solved problem?
