### ISSUE TITLE
Insert with existing ID

### ISSUE THREAD

**Issue by homakov** [sequelize/sequelize#9759]
I don't have a reproduction case but our app randomly had this error:

```
{ SequelizeUniqueConstraintError: Validation error
message: 'id must be unique',
  sql: 'INSERT INTO `users` (`id`,`has_debts`,`pubkey`,`nonce`,`balance1`,`balance2`) VALUES (11,0,X\'a79438b87e07f8c62b4adf01b0a3d79572a8be182748c85b79f6834339c97374\',0,1000,0);' },
```

So it somehow has id set to 11 but tries to use INSERT instead of UPDATE. We never set id manually for sure. How is it even possible?

**Comment by sushantdhiman** [comment]
Follow the issue template
