### ISSUE TITLE
ERROR: null value in column "createdAt" violates not-null constraint

### ISSUE THREAD

**Issue by frederikhors** [sequelize/sequelize#9767]
## What are you doing?
I'm following the tutorial here: http://docs.sequelizejs.com/manual/tutorial/migrations.html#creating-first-model-and-migration-

But when I do:

`node_modules/.bin/sequelize db:seed:all`

it gives to me:

```log
ERROR: null value in column "createdAt" violates not-null constraint
```

I tested in a new `npm init` project with a new Postgres DB 10.4.

__Dialect:__ postgres
__Dialect version:__ "pg": "7.4.3",
__Database version:__ 10.4
__Sequelize version:__ "sequelize": "4.38.0"
__Tested with latest release:__ No

Maybe this is a way to go? http://mmiyauchi.com/?p=2057

**Comment by sushantdhiman** [comment]
When seeding you need to pass value for `createdAt`, you are not passing that value in seed, may be using `bulkInsert`

**Comment by frederikhors** [comment]
@sushantdhiman I don't understand. I need to pass some value myself with `bulkInsert` also for createdAt?

**Comment by sushantdhiman** [comment]
`createdAt` is set a not null, so you need to pass a value for this column, you can pass `new Date()`

**Comment by Luomusha** [comment]
Update doc,maybe?
