### ISSUE TITLE
the default foreign key is not overwritten with the foreignKey option

### ISSUE THREAD

**Issue by mail2nitinraj** [sequelize/sequelize#9768]
## What are you doing?
creating association between two model classes: Product and ProductPhoto[One product can have many photos]
where product_id from Product table should be foreign key in ProductPhoto table.

```js
Product Model :
var product = sequelize.define('product', {
    product_id:{
        allowNull: false,
        type:DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement:true,
    },
    productName: {
      type:DataTypes.STRING,
      field:'product_name'
    }
, {
    underscored: true,
    freezeTableName: true
  });
  product.associate = function(models) {
  product.hasMany(models.productPhoto,{foriegnKey:'product_id'});
   }
}
ProductPhoto Model:
var productPhoto = sequelize.define('productPhoto', {
  	 productPhotoId:{
        allowNull: false,
        type:DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement:true,
        field:'product_photo_id'
      },
    productPhotoPath: {
      type:DataTypes.STRING,
      field:'product_photo_path'
    }
}
productPhoto.associate = function(models) {
    productPhoto.belongsTo(models.product, {foreignKey: 'product_id'});

  }
```

## What do you expect to happen?
When i execute sync to create database tables ,name product and productPhoto, the foreign key with name product_id in table productPhoto should be created.

## What is actually happening?
sequelize is generating foriegn key product_product_id, it is not taking foreignKey option.

_Output, either JSON or SQL_

 CREATE TABLE IF NOT EXISTS `product` (`product_id` INTEGER NOT NULL auto_increment , `product_name` VARCHAR(255), `product_price` FLOAT, `product_description` TEXT, `product_sku` VARCHAR(255), `product_stock` INTEGER, `product_brand` VARCHAR(255), `product_title` VARCHAR(255), `product_fabric` VARCHAR(255), `product_manufacturer_info` VARCHAR(255), `product_country_of_origin` VARCHAR(255), `product_style` VARCHAR(255), `product_sold_by` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, PRIMARY KEY (`product_id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `product` FROM `ecommerse_db_dev`

CREATE TABLE IF NOT EXISTS `productPhoto` (`product_photo_id` INTEGER NOT NULL auto_increment , `product_photo_path` VARCHAR(255), `product_photo_alt` VARCHAR(255), `createdAt` DATETIME, `updatedAt` DATETIME, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `product_product_id` INTEGER, PRIMARY KEY (`product_photo_id`), FOREIGN KEY (`product_product_id`) REFERENCES `product` (`product_id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `productPhoto` FROM `ecommerse_db_dev`

__Dialect:__ mysql
__Dialect version:__ 1.6.1
__Database version:__ 5.7.21
__Sequelize version:__ 4.37.10
__Tested with latest release:__ Yes (sequelize@4.38.0)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
> ```product.hasMany(models.productPhoto,{foriegnKey:'product_id'});```

Spelling mistake `foriegnKey` should be `foreignKey`

**Comment by mail2nitinraj** [comment]
Thanks! now it worked as expected :)
