### ISSUE TITLE
LEFT OUTER JOIN works not correctly

### ISSUE THREAD

**Issue by YuraMalakhovSky** [sequelize/sequelize#9772]
I have two tables Venue and SystemMetrics
and I try to do LEFT OUTER JOIN

```js
Venue.hasMany(SystemMetric, { foreignKey: 'venueId', sourceKey: 'id', as: 'Metrics' });
SystemMetric.belongsTo(Venue, { foreignKey: 'venueId', targetKey: 'id' });

 const options = {
        where: {},
        include: [{ 
            model: systemMetric, 
            as: 'Metrics',
            required: false,
            where: { 'values.status.description': 'Sleep' }
        }],
        order: getSortParams(sort)
 };
 return venue.findAndCountAll(options);
```

sequelize create next query which doesn't work properly.

SELECT count("venue"."id") AS "count" FROM "venues" AS "venue" LEFT OUTER JOIN "systemMetrics" AS "Metrics" ON "venue"."id" = "Metrics"."venueId" AND ("Metrics"."values"#>>'{status,description}') IN ('Sleep');

count | 100

It ignors '("Metrics"."values"#>>'{status,description}') IN ('Sleep')' condition

I expect:
SELECT count("venue"."id") AS "count" FROM "venues" AS "venue" LEFT OUTER JOIN "systemMetrics" AS "Metrics" ON "venue"."id" = "Metrics"."venueId" WHERE ("Metrics"."values"#>>'{status,description}') IN ('Sleep');

count | 5

__Dialect: postgres
__Dialect version: 7.4.3
__Database version: postgresql 9.3
__Sequelize version: 4.38.0
__Tested with latest release: yes

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
