### ISSUE TITLE
through: { where: condition } is working? Is this in the docs? scope not working

### ISSUE THREAD

**Issue by onadeem1** [sequelize/sequelize#9775]
## What are you doing?

```js
//User Model
module.exports = db => {
  const User = db.define(
    'user',
    {
      firstName: {
        type: STRING
      },
    },
    {
      scopes: {
        friends: function() {
          return {
            through: {
              where: {
                accepted: true
              }
            }
          }
        }
      }
    }
  )
  return User
}

module.exports.associations = (User ) => {
  User.belongsToMany(User, { through: Friendship, as: 'friends' })
}

//Friendship Model
module.exports = db => {
  const Friendship = db.define(
    'friendship',
    {
      accepted: {
        type: BOOLEAN,
        defaultValue: false
      },
      originalRequest: {
        type: BOOLEAN,
        defaultValue: false
      }
    },
  )
  return Friendship
}

//this works correctly and returns only friends where accepted = true
router.get(
  '/',
  asyncHandler(async (req, res, next) => {
    const friends = await req.requestedUser.getFriends({
      through: { where: { accepted: true } },
      logging: console.log
    })
    res.json(friends)
  })
)

//this does not work
router.get(
  '/',
  asyncHandler(async (req, res, next) => {
    const friends = await req.requestedUser.getFriends({
      scope: 'friends',
      logging: console.log
    })
    res.json(friends)
  })
)
```

## What do you expect to happen?
Hello all I am trying to query based on a condition from the through table where Users are related to Users through friendship. It seems to work correctly but I couldn't find this option in the docs anywhere. Is this a new feature or can someone link to where it is mentioned? I was trying to apply a scope which would return a query from the through table but that does not work correctly. Any reason this would work one way but not the other?

## What is actually happening?
The query is working with the through condition but not with the scope. Looking for information on querying the through table based on association methods & also curious how to apply scope to a through table.

__Dialect:__ Postgres
__Sequelize version:__ 5.0.0-beta.10
__Tested with latest release:__ Yes (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by doc82** [comment]
I am having the same issue
