### ISSUE TITLE
Please document ModelManager

### ISSUE THREAD

**Issue by tomprogers** [sequelize/sequelize#9776]
This is not a defect.

The ModelManager (`sequelizeInstance.modelManager`) seems like it's the most correct way to get a list of all the models that have been registered. The boilerplate code that tells us to attach each model to the instance is a hack, and we shouldn't encourage users to do that.

Here's code I'm using to obtain a dictionary of registered models:

```
sequelizeInstance.modelManager.models.reduce( ( hash, model ) => ( {
	...hash,
	[ model.name ]: model
} ), {} )
```

It works perfectly, but I only knew it was possible because I was digging through Sqlz's source code.

Document the ModelManager. Tell us which parts of its API are public and stable, and which we can't rely on. Show us good ways to use it, instead of telling us to hang this data on whatever hook is convenient.

**Comment by sushantdhiman** [comment]
You can use `sequelize.models` https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L240

We can add this to documentation

**Comment by wondie** [comment]
sequelize.models only returns the table names. Is there any way of getting the models with the table name as key or say use something like `sequelize.getModel('table_name')`?
