### ISSUE TITLE
How to get custom response for nested include

### ISSUE THREAD

**Issue by bharatkapse** [sequelize/sequelize#9777]
## What are you doing?
I have four tables join by belongsTo relationship. location belongs to city, city belongs to state and state belongs to country. when i search for a location by id and wish to get city, state and country in the response then I include these model in nested include format like the following.

```
router.get('/getLocation/:id',function(req,res){
location.findOne({
where:{id:req.params.id},
include:[{
model:city,
attributes:['name'],
include:[{
model:state,
attributes:['name'],
include:[{
model:country,
attributes:['name']
}]
}]
}]
}).then(function(Location){
res.json(Location);
});
});




```

## What do you expect to happen?
How can I get the response as following

{
"id": "1",
"displayname": "VimanNagar",
"name": "VimanNagar",
"city":"Pune",
"state":"Maharashtra",
"country":"India"
}

## What is actually happening?
And the response I am getting is like the following

{
"id": "1",
"displayname": "VimanNagar",
"name": "VimanNagar",
"city_id": "3",
"city": {
"name": "Pune",
"state": {
"name": "Maharashtra",
"country": {
"name": "India"
}
}
}
}

**Comment by sushantdhiman** [comment]
Map over result and omit / include any keys you want, you can use https://lodash.com/
