### ISSUE TITLE
allow unique and null values in a column?

### ISSUE THREAD

**Issue by johhansantana** [sequelize/sequelize#9782]
Is there a way to allow a column value to be null and be unique at the same time?

for example, I want an email column to be unique but also it's not required, so it can be empty/null

```
email: {
  type: Sequelize.STRING(50),
  allowNull: true,
  unique: true
},
```

**Comment by BPScott** [comment]
SQL considers null values as part of indexes so if you could do this then you'd only be allowed to have one row with a NULL email in your table and trying to add another would result in SQL claiming uniqueness constraint violations.

**Comment by sushantdhiman** [comment]
Do you want

1) Column with single NULL i.e. unique for NULL as well as values?
2) Column with some unique values and arbitrary number of NULL?

I guess you want (2) which should be possible with just `unique: true` 

```js
email: {
  type: Sequelize.STRING(50),
  unique: true
}
```

Above config will create an email column which can contain any number of `null` values but only unique emails.

**Note:** As you completely disregarded issue template I don't know what database engine we are talking about. If you are working with `MSSQL` then above solution wont work, check https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms191166(v=sql.105)

**Comment by minzarddillah** [comment]
jangan di close belom kejawab juga
