### ISSUE TITLE
GeomFromText in MySQL changed to ST_GeomFromText

### ISSUE THREAD

**Issue by wschamovic** [sequelize/sequelize#9785]
## What are you doing?
inserting into mysql db a geometry point 

```js
const shulInfo = { ...req.body };
    shulInfo.location_point = {
        type: 'Point',
        coordinates: [shulInfo.location.lat, shulInfo.location.lng]
    };
    minyan_locations.create(shulInfo);
  })
```

## What do you expect to happen?
I wanted to insert

## What is actually happening?
Unhandled rejection SequelizeDatabaseError: FUNCTION godaven.GeomFromText does not exist
    at Query.formatError (C:\projects\website\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)

__Dialect:__ mysql 
__Dialect version:latest available
__Database version:latest available
__Sequelize version:latest available
__Tested with latest release:latest available

It worked when I changed your datatypes.js file to the following:  
GEOMETRY.prototype._stringify = function _stringify(value, options) {
  return 'ST_GeomFromText(' + options.escape(Wkt.convert(value)) + ')';
};

Previously it was "GeomFromText", I changed it to "ST_GeomFromText". 
My reasoning was because MySQL now changed its syntax to "ST_GeomFromText".

**Comment by maluramichael** [comment]
If someone finds this Issue first, its a duplicate of this one here #9786
