### ISSUE TITLE
GeomFromText in MySQL changed to ST_GeomFromText

### ISSUE THREAD

**Issue by tschams** [sequelize/sequelize#9786]
## What are you doing?
inserting into mysql db a geometry point

```js
const shulInfo = { ...req.body };
    shulInfo.location_point = {
        type: 'Point',
        coordinates: [shulInfo.location.lat, shulInfo.location.lng]
    };
    minyan_locations.create(shulInfo);
  })
```

## What do you expect to happen?
I wanted to insert

## What is actually happening?
Unhandled rejection SequelizeDatabaseError: FUNCTION godaven.GeomFromText does not exist
at Query.formatError (C:\projects\website\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
_Output, either JSON or SQL_

Dialect: mysql
__Dialect version:latest available
__Database version:latest available
__Sequelize version:latest available
__Tested with latest release:latest available

It worked when I changed your datatypes.js file to the following:
GEOMETRY.prototype._stringify = function _stringify(value, options) {
return 'ST_GeomFromText(' + options.escape(Wkt.convert(value)) + ')';
};

Previously it was "GeomFromText", I changed it to "ST_GeomFromText".
My reasoning was because MySQL now changed its syntax to "ST_GeomFromText".

**Comment by sushantdhiman** [comment]
> These functions are removed in favor of the ST_ names:

 https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-0.html

Looks like we need to change this function based on database version.

**Comment by maluramichael** [comment]
I have this problem too right 
**sequelize 4.38.0
mysql  Ver 8.0.12 for osx10.13 on x86_64 (Homebrew)**

Is there any workaround for this?

**Comment by whittakergroupinc** [comment]
I found this to work:
In this file: node_modules/sequelize/lib/data-types.js
On lines 708 and 726 change GeomFromText --> ST_GeomFromText

**Comment by dragondgold** [comment]
> Until this get's resolved:
> 
> ```js
> const Sequelize = require('sequelize')
> 
> const Wkt = require('terraformer-wkt-parser')
> Sequelize.GEOMETRY.prototype._stringify = function _stringify(value, options) {
>   return 'ST_GeomFromText(' + options.escape(Wkt.convert(value)) + ')'
> }
> Sequelize.GEOGRAPHY.prototype._stringify = function _stringify(value, options) {
>   return 'ST_GeomFromText(' + options.escape(Wkt.convert(value)) + ')'
> }
> 
> const sequelize = new Sequelize()
> ```
> 
> Idea from @whittakergroupinc

This doesn't work anymore with sequelize v5, any workaround for this in v5?

**Comment by MunifTanjim** [comment]
Probably this:

```js
const Sequelize = require('sequelize')

const wkx = require('wkx')
Sequelize.GEOMETRY.prototype._stringify = function _stringify(value, options) {
  return `ST_GeomFromText(${options.escape(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
}
Sequelize.GEOMETRY.prototype._bindParam = function _bindParam(value, options) {
  return `ST_GeomFromText(${options.bindParam(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
}
Sequelize.GEOGRAPHY.prototype._stringify = function _stringify(value, options) {
  return `ST_GeomFromText(${options.escape(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
}
Sequelize.GEOGRAPHY.prototype._bindParam = function _bindParam(value, options) {
  return `ST_GeomFromText(${options.bindParam(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
}

const sequelize = new Sequelize()
```

**Comment by Benjamin-Gardien** [comment]
+1 I've the same issue today. I fix the problem with @MunifTanjim proposition. Can you integrate this fix in new release ? I can help if it's necessary :)

**Comment by papb** [comment]
Hi everyone! This seems related to the v8 release of MySQL, can anyone confirm? If we make this change, would it break for <v8 users?

**Comment by MunifTanjim** [comment]
> Hi everyone! This seems related to the v8 release of MySQL, can anyone confirm? If we make this change, would it break for <v8 users?

`ST_GeomFromText` was introduced in MySQL `v5.6`

**Comment by oliviergf** [comment]
i confirm this is comming from mysql v8

**Comment by stackofy** [comment]
Face the same issue with sequelist 6.3.x, and @MunifTanjim solution is worked for me.

**Comment by blankstar85** [comment]
Are you using typescript? maybe I didn't spend enough time, but its not working for me. any suggestions?

**Comment by MunifTanjim** [comment]
> its not working for me. any suggestions?

Why so? Nobody can give you any suggestions if you don't share enough information. Which TypeScript version are you using? Which Sequelize version? What are the errors? What are the warnings? What are you trying?

**Comment by blankstar85** [comment]
@MunifTanjim Thanks for the quick reply. 
I'm using:
typescript: 3.9.7
sequelize: 5.22.3
sequelize-typescript: 1.1.0
Mysql: 8.0

I just retired to get the error and it works. Sorry I wasted your time, I'm not sure what I did differently. Maybe my installed node packages were all mixed up. Thanks!

**Comment by NoufalBhai** [comment]
Is this fixed?
I'm still getting the same issue.

**Comment by hengki01** [comment]
> > Hi everyone! This seems related to the v8 release of MySQL, can anyone confirm? If we make this change, would it break for <v8 users?
> 
> `ST_GeomFromText` was introduced in MySQL `v5.6`
> `GeomFromText` was deprecated from MySQL `v5.7.6`



> Probably this:
> 
> ```js
> const Sequelize = require('sequelize')
> 
> const wkx = require('wkx')
> Sequelize.GEOMETRY.prototype._stringify = function _stringify(value, options) {
>   return `ST_GeomFromText(${options.escape(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
> }
> Sequelize.GEOMETRY.prototype._bindParam = function _bindParam(value, options) {
>   return `ST_GeomFromText(${options.bindParam(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
> }
> Sequelize.GEOGRAPHY.prototype._stringify = function _stringify(value, options) {
>   return `ST_GeomFromText(${options.escape(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
> }
> Sequelize.GEOGRAPHY.prototype._bindParam = function _bindParam(value, options) {
>   return `ST_GeomFromText(${options.bindParam(wkx.Geometry.parseGeoJSON(value).toWkt())})`;
> }
> 
> const sequelize = new Sequelize()
> ```

It's almost 2 years and still works !

**Comment by Hwan-seok** [comment]
Why is this not being fixed?

**Comment by neel2902** [comment]
I am using

- mysql: 8.0.23
- sequelize: 6.6.2

In node_modules/sequelize/lib/data-types.js
In line 847 and 850, changing GeomFromText to ST_GeomFromText did the job for me.

**Comment by sgambolati-ua** [comment]
> I am using
> 
> * mysql: 8.0.23
> * sequelize: 6.6.2
> 
> In node_modules/sequelize/lib/data-types.js In line 847 and 850, changing GeomFromText to ST_GeomFromText did the job for me.

This works for me. Thanks!
Is there a better way to overload/extend a data type?
