### ISSUE TITLE
Postgres asking for unnecessary column in GROUP BY clause or aggregate function

### ISSUE THREAD

**Issue by aaronfulkerson** [sequelize/sequelize#9800]
## What are you doing?

I added an attribute, 'amount', to the through association between BatchRecords and VendorLots to keep track of the amount of material removed from a VendorLot, so a BatchRecordVendorLot is made of the attributes VendorLotId, BatchRecordId, amount, createdAt and updatedAt. To do so, I created a model called BatchRecordVendorLot and everything works except the following snippet:

```js
  Formula.findOneIncludeBatchRecord = function (id, { models: { BatchRecord, BatchRecordVendorLot, RawMaterial }, col, fn } = sequelize) {
    return Formula.findOne({
      where: { id },
      include: [
        {
          model: RawMaterial,
          through: {
            attributes: ['amount']
          }
        },
        {
          model: BatchRecord,
          attributes: [
            'lot',
            [fn('sum', col('BatchRecords->BatchRecordVendorLots.amount')), 'amount']
          ],
          include: [
            {
              model: BatchRecordVendorLot,
              attributes: []
            }
          ]
        }
      ]
    })
  }
```

## What do you expect to happen?
I expect that I'll get a column called 'amount' in my BatchRecords.

## What is actually happening?
"column "Formula.id" must appear in the GROUP BY clause or be used in an aggregate function"

First of all, I have no idea why it's asking for the Formula ID in the GROUP BY clause and second, if I do add it, it tells me something about FormulaRawMaterials.amount being required in a GROUP BY clause or aggregate function.

If I remove the attribute containing the summing function, everything works fine.

'SELECT "Formula"."id", "Formula"."code", "Formula"."name", "Formula"."createdAt", "Formula"."updatedAt", "RawMaterials"."id" AS "RawMaterials.id", "RawMaterials"."name" AS "RawMaterials.name", "RawMaterials"."code" AS "RawMaterials.code", "RawMaterials"."description" AS "RawMaterials.description", "RawMaterials"."threshold" AS "RawMaterials.threshold", "RawMaterials"."createdAt" AS "RawMaterials.createdAt", "RawMaterials"."updatedAt" AS "RawMaterials.updatedAt", "RawMaterials"."TypeId" AS "RawMaterials.TypeId", "RawMaterials"."SubTypeId" AS "RawMaterials.SubTypeId", "RawMaterials->FormulaRawMaterial"."amount" AS "RawMaterials.FormulaRawMaterial.amount", "RawMaterials->FormulaRawMaterial"."createdAt" AS "RawMaterials.FormulaRawMaterial.createdAt", "RawMaterials->FormulaRawMaterial"."updatedAt" AS "RawMaterials.FormulaRawMaterial.updatedAt", "RawMaterials->FormulaRawMaterial"."FormulaId" AS "RawMaterials.FormulaRawMaterial.FormulaId", "RawMaterials->FormulaRawMaterial"."RawMaterialId" AS "RawMaterials.FormulaRawMaterial.RawMaterialId", "BatchRecords"."id" AS "BatchRecords.id", "BatchRecords"."lot" AS "BatchRecords.lot", sum("BatchRecords->BatchRecordVendorLots"."amount") AS "BatchRecords.amount" FROM "Formulas" AS "Formula" LEFT OUTER JOIN ( "FormulaRawMaterials" AS "RawMaterials->FormulaRawMaterial" INNER JOIN "RawMaterials" AS "RawMaterials" ON "RawMaterials"."id" = "RawMaterials->FormulaRawMaterial"."RawMaterialId") ON "Formula"."id" = "RawMaterials->FormulaRawMaterial"."FormulaId" LEFT OUTER JOIN "BatchRecords" AS "BatchRecords" ON "Formula"."id" = "BatchRecords"."FormulaId" LEFT OUTER JOIN "BatchRecordVendorLots" AS "BatchRecords->BatchRecordVendorLots" ON "BatchRecords"."id" = "BatchRecords->BatchRecordVendorLots"."BatchRecordId" WHERE "Formula"."id" = \'1\';'

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ 10.5
__Sequelize version:__ 4.38
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`SUM` requires `GROUP`, I think that is a basic requirement of all aggregate function in any SQL implementation

**Comment by aaronfulkerson** [comment]
Yes but it shouldn't require me to group based on the Formula's ID if I'm summing columns from a table two relations down.

**Comment by sushantdhiman** [comment]
Then which field your are going to use for grouping?

**Comment by aaronfulkerson** [comment]
If I'm summing BatchRecordVendorLots then it should be grouping by the BatchRecordId. I'm trying to get the total of the BatchRecord by summing all of the BatchRecordVendorLots.

The relations go like this: Formula -> BatchRecord -> BatchRecordVendorLot -> VendorLot

A BatchRecordVendorLot is actually a through association but I created a model to add an attribute called amount which is the column I'm attempting to sum and add to my BatchRecord.

**Comment by sushantdhiman** [comment]
You need to group with `Formula.ID, BatchRecord.ID, BatchRecordVendorLot.ID` to have correct sum, as it is a Formula's BatchRecord for which you want to see VendorLot for each BatchRecordVendorLot

**Comment by aaronfulkerson** [comment]
Thank you for clarifying.
