### ISSUE TITLE
Possible improvement: use depd properly

### ISSUE THREAD

**Issue by charandas** [sequelize/sequelize#9801]
In an unrelated (slightly related) [issue](https://github.com/dougwilson/nodejs-depd/issues/27#issuecomment-412372681), the author of `depd` noted that `sequelize` currently is using `depd` incorrectly.

Like `depd` readme points out:

>this module uses the calling file to get the boundary for the call stacks, so you should always create a new deprecate object in each file and not within some central file.

`sequelize` currently is using a central file, and may wanna consider moving on to individual `depd` instances. Filing this issue as an FYI as it does not impact anything other than deprecation notices.

**Comment by BruceBissett** [comment]
I'm not sure why, but this error (callSite.getFileName is not a function) started when running our function under Azure Kubernetes, but didn't happen outside of Kube.   This is with Sequelize 4.42.0.

Is there an update on this issue, and a fix?
