### ISSUE TITLE
How do i remove a column in the database that has data without having to use sync force

### ISSUE THREAD

**Issue by Cariaga** [sequelize/sequelize#9805]
> const GameHistory =sequelize.define('GameHistory', {
  GameHistoryID: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  UserAccountID:Sequelize.STRING,//FK Many UserAccount can have many GameHistoryID
  SeasonID: Sequelize.STRING,// assigned by the room// every cycle of the room is still considered a single round
  // assigned by the room
	Rank: Sequelize.STRING,
	Score: Sequelize.INTEGER,
	Card: Sequelize.STRING,//card sequence
  Time: Sequelize.TIME,
  Date:Sequelize.DATE,
  BeforePoints:  Sequelize.INTEGER,
  AfterPoints: Sequelize.INTEGER//also called current Points
});

>   module.exports.GameHistory= GameHistory;

the resulting schema when i try to describe it
> {
  "GameHistoryID": { "type": "INT(11)", "allowNull": false, "defaultValue": null, "primaryKey": true },
  "UserAccountID": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "RoundID": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Rank": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Score": { "type": "INT(11)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Card": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Time": { "type": "TIME", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Date": { "type": "DATETIME", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "BeforePoints": { "type": "INT(11)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "AfterPoints": { "type": "INT(11)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "createdAt": { "type": "DATETIME", "allowNull": false, "defaultValue": null, "primaryKey": false },
  "updatedAt": { "type": "DATETIME", "allowNull": false, "defaultValue": null, "primaryKey": false },
  "SeasonID": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false }
}

but i want to remove RoundID

>  {
  "GameHistoryID": { "type": "INT(11)", "allowNull": false, "defaultValue": null, "primaryKey": true },
  "UserAccountID": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Rank": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Score": { "type": "INT(11)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Card": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Time": { "type": "TIME", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "Date": { "type": "DATETIME", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "BeforePoints": { "type": "INT(11)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "AfterPoints": { "type": "INT(11)", "allowNull": true, "defaultValue": null, "primaryKey": false },
  "createdAt": { "type": "DATETIME", "allowNull": false, "defaultValue": null, "primaryKey": false },
  "updatedAt": { "type": "DATETIME", "allowNull": false, "defaultValue": null, "primaryKey": false },
  "SeasonID": { "type": "VARCHAR(255)", "allowNull": true, "defaultValue": null, "primaryKey": false }
}

ps i don't use cli

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
