### ISSUE TITLE
how is query interface executed?

### ISSUE THREAD

**Issue by Cariaga** [sequelize/sequelize#9811]
## What are you doing?

```js
// models.js
const HandHistory = sequelize.define('HandHistory', {
  HandHistoryID: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  UserAccountID:{
    type: Sequelize.STRING,
    foreignKey: true,
    references: {
      model: UserAccount,
      key: 'UserAccountID'
    }
  },
  RoundID:Sequelize.STRING,// formerly SeasonID 
  MoveHand:Sequelize.STRING//action performed by the player
});
  module.exports.HandHistory = HandHistory;
  module.exports = {
    up: function(queryInterface, Sequelize) {
      // logic for transforming into the new state
     return queryInterface.renameColumn('HandHistory', 'SeasonID','RoundID')
    },
   
    down: function(queryInterface, Sequelize) {
      // logic for reverting the changes
    }
  }
```

## What do you expect to happen?
_I wanted to keep the record of SeasonID to RoundID_

## What is actually happening?
_The record gets removed when i rename the SeasonID to RoundID in the define schema_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ mysql
__Database version:__ latest
__Sequelize version:__ latest
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Can I get SSCCE for this. If I understood correctly you are saying renaming a column will destroy all its data. Odd , we got some tests for this.

Please follow issue template, try to provide me a SSCCE 

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
