### ISSUE TITLE
Question: using `include` to join without retrieving data?

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#9817]
I searched on this on SO but the only answer I got was `use raw queries` which is really against what an ORM is for.

What would be the most elegant way to use use a join on a table say:

```js
Book.findAll({
  include: {
    model: Category,
    where: {
      name: 'something',
    },
})
```

without actually pulling the category as I don't need that data?

**Comment by calmdev** [comment]
```js
const category = await Category.findOne({ where: { name } });
const books = await category.getBooks();
```

**Comment by SimonSchick** [comment]
@calmdev that's 2 queries.
Anyways, turns out `{ include: [{ attributes: [], ... }] }` does the job for me.
