### ISSUE TITLE
Querying by virtual attribute doesn't work

### ISSUE THREAD

**Issue by ifvictr** [sequelize/sequelize#9822]
## What are you doing?

```js
// Topic model
const Topic = sequelize.define(
    'Topic',
    {
        name: DataTypes.STRING,
        slug: {
            type: new DataTypes.VIRTUAL(DataTypes.STRING, ['name']),
            get: () => kebabCase(this.get('name'))
        },
        description: DataTypes.STRING
    }
)

// Fetching topic by slug 
Topic.findOne({ where: { slug: 'my-slug' } }).then(topic => {
    console.log(topic)
})
```

## What do you expect to happen?
The topic with the matching slug should be returned.

## What is actually happening?
I'm getting `Unhandled rejection SequelizeDatabaseError: column Topic.slug does not exist`.

__Dialect:__  postgres
__Database version:__ 10+190
__Sequelize version:__ 4.38.0
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
Yes it wont work as column is VIRTUAL, it's only for presentation layer and you should query on composing columns

**Comment by ifvictr** [comment]
Oh, I see. Thanks for clearing that up!
