### ISSUE TITLE
Using an increment on a value of a table does a lot more than just increment one value?

### ISSUE THREAD

**Issue by davidv171** [sequelize/sequelize#9832]
## What are you doing?

```js
				models.user.increment({
					likedByCount: 1
				}, {
					where: {
						id: target_id,
						username: target_username
					}
				}).then((result) => console.log("Result" + result)).catch((err) => console.log("Trouble updating"));
```

I've also tried this:
```js

				models.user.findById(target_id).then(user => {
					return user.increment(['likedByCount'], {by: 1})
				  }).then(user => {
					  console.log("Incremented: ");
					  console.log(user);
					// Postgres will return the updated user by default (unless disabled by setting { returning: false })
					// In other dialects, you'll want to call user.reload() to get the updated instance...
				  }).catch((err)=>console.log(err.message));
```

And got the same results.

## What do you expect to happen?
I wanted to increment the value inside "likedByCount" by 1. So in SQL what I wanted to do was: UPDATE "user" SET "likedByCount" +=1 WHERE "id"=6 AND "username"='express" RETURNING * 
## What is actually happening?

It is setting a bunch of column's values that don't exist. "0" is set to value "id" , "1" to username "2" to likedByCount which is the "index" of columns I guess, just reversed. 

And obviously since I never defined what "0" , "1", and "2" are this throws an error. 

_Output, either JSON or SQL_

Executing (default): UPDATE "user" SET "likedByCount"="likedByCount"+ 1,"0"='id',"1"='username',"2"='likedByCount' WHERE "id" = 6 AND "username" = 'express' RETURNING *

__Dialect:__  postgres
__Dialect version:__     "pg": "^7.4.3",

__Database version:__ I'm using ElephantSQL
__Sequelize version:__     "sequelize": "^4.38.0",
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Looks like scopes or some hooks, need a proper SSCCE to workout something

```js
const user = sequelize.define('user', {
  id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
      unique: true,
      autoIncrement: true,
      required: true
  },
  username: {
      type: Sequelize.STRING,
      unique: true,
      required: true,
      validate: {
          len: [4, 32]
      }
  },
  password: {
      type: Sequelize.STRING,
      required: true,
      protect: true,
      validate: {
          len: [4, 32]
      }

  },
  likedByCount: {
      type: Sequelize.INTEGER,
      defaultValue: 0
  }
});

(async () => {
  await sequelize.sync({ force: true });

  const u = await user.create({
    username: 'abccd',
    password: 'dsdsdds'
  });

  await user.increment({
    likedByCount: 1
  }, {
    where: {
      id: u.get('id')
    },
    logging: console.log
  });
})();
```

```sql
 UPDATE `users` SET `likedByCount`=`likedByCount`+ 1,`updatedAt`='2018-08-28 05:34:35.229 +00:00' WHERE `id` = 1
```
