### ISSUE TITLE
Need a way to compare now/today against a computed date, in the database

### ISSUE THREAD

**Issue by andrew-st-angelo-77media** [sequelize/sequelize#9833]
## What are you doing?
Because Sequelize utilizes JSON for its queries, there doesn't seem to be a (not horrible) way to compare today/now to a computed value, as both are technically computed values.

You can't do any of the following options
```js
myModel.find({
  where: {new Date(): {$gt:  sequelize.fn('dateCompute')}}
});
```
```js
var todayDateTime = new Date();
myModel.find({
  where: { todayDateTime: {$gt:  sequelize.fn('dateCompute')}}
});
```
You absolutely can compare two computed values in SQL, as part of a condition.

## What do you expect to happen?
It would be useful to have a `$today` or `$now` values that could be used in the place of column names, as comparitors.  Such as:
```js
myModel.find({
  where: { $now: {$gt:  sequelize.fn('dateCompute')}}
});
```

Further, a way to dynamically compare two computed values would be extremely useful.  One option could be utilizing some combination of a special operator and a Sequelize function, along the lines of:
```js
myModel.find({
  where: {
    $eval: sequelize.compare( sequelize.fn('dateCompute'), sequelize.fn('GETDATE'), $gt)
  }
});
```

## Clarification
While there are Virtual Columns and Custom Getters/Setters, these are available against the datasets once they are retrieved, to in the query itself.  Our particular use case revolves around notifications, and we are going to want to check against (potentially) millions of records.  I'd prefer to weed out on the database.

Our current course is we're going to create a view, but I'm looking to argue my point that perhaps I shouldn't need to.  Not that views are a new or radical thought, but this will be the first time we've needed to create a db programmable object.

---

__Dialect:__ mssql
__Database version:__ Microsoft SQL Azure (RTM) - 12.0.2000.8
__Sequelize version:__ 3.32.1 (but in the process of upgrading)
__Tested with latest release:__ No (But I've thuroughly read the docs)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by andrew-st-angelo-77media** [comment]
Bump

**Comment by janmeier** [comment]
Your compare example is close - http://docs.sequelizejs.com/manual/tutorial/querying.html, http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#static-method-where
```js
myModel.find({
  where: sequelize.where( sequelize.fn('dateCompute'), '>', sequelize.fn('GETDATE'))
});
```

Or, if you need to combine it with other conditions

```js
myModel.find({
  where: {
    [Op.and]: [
       sequelize.where( sequelize.fn('dateCompute'), sequelize.fn('GETDATE'), '>'),
       { foo: 'bar' }
    ]
  }
});
```

**Comment by andrew-st-angelo-77media** [comment]
@janmeier Thank you, again!!
