### ISSUE TITLE
Documentation for QueryInterface#bulkDelete() is a little unclear 

### ISSUE THREAD

**Issue by broofa** [sequelize/sequelize#9834]
Regarding http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-bulkDelete

It's not exactly obvious what the`identifier` parameter is supposed to be.   An example would be helpful here.  E.g... https://stackoverflow.com/a/48234655/109538

**Comment by yonjah** [comment]
@broofa I wonder why it was done like this and not following the convention of using `options.where` ?
Maybe this method was missed when options were originally merged into a single object.

**Comment by sushantdhiman** [comment]
@broofa I fixed that documentation some time ago https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L1028 , docs website is still running v4 branch so it is not updated. Please check direct code for correct docs until v5 is released as API docs are more improved in master branch

`identifier` is supposed to be `where` conditions hash, as that stackoverflow answer says

@yonjah old and most of query interface / generator methods are like this, historically whenever a new option was included a new param was added which become an issue after some time. v3 did some cleanup work but private api is still full of code like this :D
