### ISSUE TITLE
"Column 'id' in field list is ambiguous"

### ISSUE THREAD

**Issue by newcomein** [sequelize/sequelize#9839]
## What are you doing?

```js
// code here

    ###query code
   ###model code url 
   ###https://gitee.com/newcomein/summerVideoCMS_Service/blob/master/src/models/video.js
  ### https://gitee.com/newcomein/summerVideoCMS_Service/blob/master/src/models/views.js
    const include = [
        {
            model: base_routers.model.user,
            attributes: {
                exclude: ['email', 'phoneNumber', 'trueName', 'password']
            }
        },
        {
            model: base_routers.model.views,
            attributes: {
                include: [[base_routers.sequelize.fn('COUNT', base_routers.sequelize.col('id')), 'viewsCount']]
            }
        }
    ];
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version:__ 5.7
__Sequelize version:__ 5.0.0-beta.10
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Both users and views model got `id`, you need to pass correct table name to `sequelize.col('id')`, possibly pass `user_id` instead of `id`

**Comment by yogithesymbian** [comment]
but ... how about
------
**users**
id
full_name

then
------
**driver**
id
full_name
user_id

------
when we load data for **driver** with _include_ **user**
then implementation **where** **condition** to **search data** ... i got ambiguous for **full_name only** ...
i thinks its bad convention if we change the **full_name** into **driver_full_name**

how do you solve it ?

**Comment by yogithesymbian** [comment]
> ## but ... how about
> **users** id full_name
> 
> ## then
> **driver** id full_name user_id
> 
> when we load data for **driver** with _include_ **user** then implementation **where** **condition** to **search data** ... i got ambiguous for **full_name only** ... i thinks its bad convention if we change the **full_name** into **driver_full_name**
> 
> how do you solve it ? @newcomein

ah solved by ...
```
if(keyword){
      let keywordSplit = keyword.split('&');
      keywordSplit.map(el => {
        const data = el.split("=");
        if (data[0] == 'created_at') {
          advanceSearchCondition.push({
            created_at: {
              [Op.substring]: `${data[1]}`
            }
          });
        } else if (data[0] == 'updated_at') {
          advanceSearchCondition.push({
            updated_at: {
              [Op.substring]: `${data[1]}`
            }
          });
        } else if (data[0] == 'full_name') {
          advanceSearchCondition.push({
            full_name: { // where the driver have full_name ... so need to use like this
              [Op.like]: Sequelize.literal(`\'%${data[1]}%\'`)
            }
          });
        } else if (data[0] == 'phone') {
          advanceSearchCondition.push({ 
            phone: {
              [Op.like]: Sequelize.literal(`\'%${data[1]}%\'`)
            }
          });
        } else {
          winLogger.error(data[0]);
          winLogger.error(data[1]);
          advanceSearchCondition.push({ // then user.full_name , we use like this // solved
            [`$${data[0]}$`]: {
              [Op.substring]: `${data[1]}`
            }
          });
        }
      })
    }
```
