### ISSUE TITLE
Association syntax for order

### ISSUE THREAD

**Issue by frlinw** [sequelize/sequelize#9840]
The initial implementation of order-by-nested https://github.com/sequelize/sequelize/pull/1299 mimic the `include` syntax. It would be great if it could support association option (`{ association: "relatedName" }`) 

__Dialect:__ postgres
__Sequelize version:__  5 beta 10

**Comment by frlinw** [comment]
Feature requests are not allowed ?

**Comment by sushantdhiman** [comment]
Properly explained with use-cases and examples

**Comment by frlinw** [comment]
`include` support `model/as` and `association` syntax
`order` support only `model/as` syntax

If you already use the `association` syntax for `include`, it'll be a nice sugar to have the same syntax for `order`
```js
const instance = models.MyModel.findAndCountAll({
    attributes: ["id"],
    include: [{
        association: "myassociation",
        required: true
    }],
    order: [
      // In this case, It seems more consistent/natural to use :
      // [{ association: "myassociation" }, "createdAt", "ASC"]
      // instead of :
      [{ model: models.MyAssocModel, as: "myassociation" }, "createdAt", "ASC"]
    ]
  })
```

**Comment by sushantdhiman** [comment]
Hmm I thought that was already supported, have you tried passing association instance?

**Comment by frlinw** [comment]
You're right, it's supported as a plain string. The `model/as` syntax led me to think `include` and `order` could share the same syntaxes for association.
