### ISSUE TITLE
getConnection fails with replication when Master disconnected

### ISSUE THREAD

**Issue by lynnlam** [sequelize/sequelize#9845]
## What are you doing?

When using replication, The connection always checking master.

```js
new Sequelize('database-name', null, null, {
        dialect: 'mysql',
        port: 3306,
        replication: {
            read: [{
                host: Slave,
                username: 'username',
                password: 'password',
                pool: {}
            }],
            write: {
                host:  Master,
                username: 'username',
                password: 'password',
                pool: {}
            }
        },
        pool: {
            maxConnections: 20,
            maxIdleTime: 30000
        }
});
```

## What do you expect to happen?
When options.type is SELECT.  The connection should be checking slave (replication.read).

## What is actually happening?
When Master disconnected. The connection always return "connect ECONNREFUSED MASTER"

**Comment by sushantdhiman** [comment]
Follow template

**Comment by lynnlam** [comment]
I check this in connection-manager, It always use config.replication.write to check connection whenever just check something from replication.read?

https://github.com/sequelize/sequelize/blob/342e18fbaddb74be39d6ea1dd117cb291f1c65e0/lib/dialects/abstract/connection-manager.js#L250
