### ISSUE TITLE
instance.isNewRecord is always false in hooks

### ISSUE THREAD

**Issue by mdemblani** [sequelize/sequelize#9846]
The `isNewRecord` key on the instance is always false in the `afterSave` and the `afterCreate` hook.

## What are you doing?
Checking for Model creation in the afterSave hook and afterCreate hook

## What do you expect to happen?
`isNewRecord` should be true for newly created models

## What is actually happening?
`isNewRecord` is false

__Dialect:__ mysql
__Sequelize version:__ 4.38.0

**Comment by chrismatheson** [comment]
@mdemblani Im having a similar experience, can you discuss why you closed this (assuming you don't think its a bug any more?)

**Comment by mdemblani** [comment]
@chrismatheson Have a look at this link. After opening the issue, I landed over here. 

[http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-member-isNewRecord](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-member-isNewRecord)

It basically states that the key is set to `true` only if the record has not yet been persisted to the database.

You can also look at the code in `model.js` file at [https://github.com/sequelize/sequelize/blob/master/lib/model.js#L98](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L98)

And hence on reading that I closed it.

**Comment by Strate** [comment]
Is there any way to check that instance is new on `afterSave` hook?
