### ISSUE TITLE
I want to define the global classMethods.

### ISSUE THREAD

**Issue by acodercat** [sequelize/sequelize#9852]
## What are you doing?
I want to define the global classMethods.

```js
// code here
```

## What do you expect to happen?
I want to define the global classMethods.

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ mysql
__Database version:__ mysql5.7
__Sequelize version:__ last
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
All model extends `Sequelize.Model` you should be able to add methods directly on that class, it will be available on all Models

```js
Sequelize.Model.testy = function () {
  console.log(`Hello from ${this.name}`);
};

var Group = sequelize.define('Group', {
  name: sequelize.Sequelize.STRING
});

var Person = sequelize.define('Person', {
  name: sequelize.Sequelize.STRING
});

Person.testy();
Group.testy();
```

```
Hello from Person
Hello from Group
```
