### ISSUE TITLE
How to define a model with a select instead of a table?

### ISSUE THREAD

**Issue by marcioaffonso** [sequelize/sequelize#9854]
Currently, Sequelize lets you define a model specifying a tableName. But instead of defining it with a table, I wanted to do something like this:

`tableName: '(SELECT * FROM my_table)'`

But that's not possible because sequelize puts quotes on that. So the value is not treated as literal. I'm using mySQL.

**Comment by marcioaffonso** [comment]
@sushantdhiman, the problem is that I can't create the view. I needed to execute a query inside a select without using a view. Would that be possible?

**Comment by sushantdhiman** [comment]
No
