### ISSUE TITLE
hasOne should set the foreign key to unique (or at least optional)

### ISSUE THREAD

**Issue by championswimmer** [sequelize/sequelize#9855]
## What are you doing?
I understand that both the following lines
```js
Player.belongsTo(Team)
Team.hasMany(Player)
```
creates a `teamId` in `players` table. With the difference is this - 

- First line ensures we can do `player.getTeam() -> Team`
- Second line ensures we can do `team.getPlayers() -> Array<Players>`

Now coming to hasOne, which I believe is used for 1:1 relationships, something like

```js
Player.hasOne(PlayerDetails)
```
So I can vertically partion the table and keep details (which are queries less often, in a separate table)
In this case also `playerDetails` table gets `playerId` 

## What do you expect to happen?
I would want `playerDetails.playerId` to be a UNIQUE column, because
Player has **one** details row, which means multiple PlayerDetails cannot have 
the same Player attached to it (if I understand the meaning of "has one" correctly in english).

I would prefer this at least to be an option. 

```js
Player.hasOne(PlayerDetails, {unique: true})
```

## What is actually happening?
`playerDetails.playerId` is just a FOREIGN KEY but not UNIQUE, just like hasMany works. 

__Dialect:__ ALL
__Tested with latest release:__ YES

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
There are two options

1. Pass `foreignKey: { unique: true }`, AFAIR that should work
2. `playerId` is only injected as last resort, if not defined by user already. As a good practice you need to define `playerId` on model, thus you are free to specify any attribute options yourself.

------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by championswimmer** [comment]
`A.hasOne(B, {foreignKey: {unique: true}})` works

It wasn't documented it works for `hasOne` (only for `hasMany`) 
Thanks! 

I'll see to send a PR to update in docs too

**Comment by AZS-99** [comment]
It doesn't work anymore even by adding the unique: true, which honestly we should not be needing to use it in case of 'hasOne'. 
<img width="240" alt="Screen Shot 2020-02-21 at 8 06 29 PM" src="https://user-images.githubusercontent.com/45923420/75085970-c877af00-54fc-11ea-8700-29cba09596a8.png">

**Comment by Fatjon-Gash1** [comment]
As of the latest version, the constraint does not work when defined in the `ForeignKeyOptions`. I tested it using Typescript and received "typescript: Object literal may only specify known properties, and 'unique' does not exist in type 'ForeignKeyOptions'." . 

I haven't tested the `hasMany` association, but that isn't the purpose of this issue. 

For now, what remains to be the most straightforward approach is to define the FK with the unique constraint in the model definition itself.

Although, it would be appreciated to correctly map the schema's FK constraint through the use of the `hasOne` association by default without the need to pass the unique option at all. As its name intends, it should associate models in a 1:1 relation by default.
