### ISSUE TITLE
findOrCreate, passing a function into options.defaults

### ISSUE THREAD

**Issue by calibr** [sequelize/sequelize#9856]
I think it would be useful if sequelize had a support for passing a function into options.default for findOrCreate. For example, if default values are not known in advance and should be computed or fetched from some storage, obtaining them before calling findOrCreate would produce excessive overhead in case the record already exists.

Ideally this should be a function that returns a promise, so sequelize would await on this promise. Code example:

```js
Model.findOrCreate({
  where: {username: 'sdepold'},
  defaults: async function() {
    // fetching some external storage
    let age = ageStorage.getAgeForUser('sdepold')
    return {age}
  }
})
```

Obviously this function should be called only when a record needs to be created.

**Comment by sushantdhiman** [comment]
```js
Model.mySpecialFunc = function (options) {
   let age = ageStorage.getAgeForUser('sdepold');

   return Model.findOrCreate({
     ...options,
     defaults: {
       ...options.defaults,
       age
     }
  });
}
```

**Comment by calibr** [comment]
@sushantdhiman Thank you, but in your example you are still fetching everytime from some storage calling `ageStorage.getAgeForUser('sdepold');`, however value from this storage may not be used at all if the record already already exists in the DB. That's what I meant when I wrote about "overhead" - it could be a network request to fetch some values for `options.default` or something else that takes time and resouces, but may not be used, so can be moved to a special function which is called only when the record needs to be created. Sorry if it was not clear.

**Comment by sushantdhiman** [comment]
No I can't accept this more complicated version to get `defaults`, Network request can be cached it if it is time consuming and it will work without any extra overhead for repeated cases.
