### ISSUE TITLE
Why do aliases have to be unique across different models?

### ISSUE THREAD

**Issue by billybarnum** [sequelize/sequelize#9857]
## What are you doing?
I'm trying to define associations for previously defined models. Note the alias names.

```js
    orm.AccountingPeriod.hasMany(orm.Order, {
        as: 'orders',
        foreignKey: 'billingPeriodId',
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION'
    });

    orm.Customer.hasMany(orm.Order, {
        as: 'orders',
        foreignKey: 'customCustomerId',
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION'
    });

    orm.Product.hasMany(orm.Order, {
        as: 'orders',
        foreignKey: 'customProductId',
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION'
    });
```

## What do you expect to happen?
The alias "orders" appears in multiple models, but not the same model. 

I can see why aliases would need to be unique within a model - property names need to be unique after all. We have also had issues in the past that turned out to be us associations multiple times for the same model - a bug on our part. 

Yet I can't see why aliases would need to be unique **_across different models_**. in fact ... not only is this kind of thing extremely common, but we have multiple projects as recently as v4.13 (and probably more recently as well) where it was NOT a problem.

This is a new project, but I'm really concerned about existing projects. We have several databases with a table of time ranges to which every other table in that database has a FK. And again, we have existing code with aliased associations that all have the same name ... "Schedule"  or "AccountingPeriod". 

I've already checked that I'm not executing the above code multiple times by mistake. Any other ideas what might be happening here? I'm hoping this is just a bone-head error on my part. 

## What is actually happening?
Getting the error
`You have used the alias orders in two separate associations. Aliased associations must have unique aliases.`

__Dialect:__  postgres 
__Dialect version:__ ???
__Database version:__ 10.3
__Sequelize version:__ 4.38
__Tested with latest release:__ No 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by ahmedaabouzied** [comment]
what do you mean a controlled environment ?

**Comment by billybarnum** [comment]
I just meant debugging in vscode using hapijs/lab test library, with a small number of tables and models on a toy database, as opposed to a "real" legacy database with a few dozen tables. 

If I recall it turned out I actually been executing the same sequelize.define() code multiple times. Again, apologies for the fuss.
