### ISSUE TITLE
findOne doesn't generate a corrected SQL with partial primary key

### ISSUE THREAD

**Issue by fenying** [sequelize/sequelize#9859]
## What are you doing?

For following definitions of a model.

```sql
CREATE TABLE ttt (
  key1 CHAR(32) NOT NULL,
  key2 INT UNSIGNED NOT NULL,
  v INT UNSIGNED NOT NULL,
  PRIMARY KEY (key1, key2)
);
```

```ts
const def = {
  key1: {
    "type": Sequelize.CHAR(32),
    "primaryKey": true
  },
  key2: {
    "type": Sequelize.INTEGER(10).UNSIGNED,
    "primaryKey": true
  },
  // ....
};
```

I am trying selecting any a row from a table, only with partial primary key:

```js
model.findOne({
  where: {
    key1: "1234" // only with partial primary key
  }
});
```

## What do you expect to happen?

I think it should return only one row for me.

## What is actually happening?

**Yes, actually it did.**

But my program is almost dead, and sucks full of a CPU core.

Because it generates a SQL, which selects a great many rows.

_Output, either JSON or SQL_

```sql
SELECT `key1`, `key2`, `v` FROM `ttt` AS `ttt` WHERE `ttt`.`key1` = '123';
```

> **NOTICE: `LIMIT 1` is missing.**

__Dialect:__ mysql
__Dialect version:__ 1.6.1
__Database version:__ 5.7.13
__Sequelize version:__ 4.38.0
__Tested with latest release:__ 4.38.0

## Clues

All this is because of the code here, it removes `LIMIT 1` when a unique is
used:

> however, the code is wrong

https://github.com/sequelize/sequelize/blob/2c3a6e715d8684a489daac75ce588de3ef807689/lib/model.js#L1747-L1757

> I can not understand why the `LIMIT 1` should be removed when it's using a unique index.

If you replace `key1` with `key2`, it should works well, while the `primaryKeyAttribute` is assigned to the first primary key in multiple primary keys list:

https://github.com/sequelize/sequelize/blob/2c3a6e715d8684a489daac75ce588de3ef807689/lib/model.js#L1088-L1093

**Comment by sushantdhiman** [comment]
Sequelize at this time does not support partial primary keys, we recommend `id` as primary key
