### ISSUE TITLE
findOne on model with scope returns instance of class that is not derived from Model

### ISSUE THREAD

**Issue by linpekka** [sequelize/sequelize#9860]
## What are you doing?
AModel.findOne() returns an instance of class that extends Model

AModel.scope(['AnotherModel']).findOne() returns and instance of class that extends this

Does not seem to matter which scope I use, but a simple include does trigger it, like below

```js
var AModel = sequelize.define('AModel', {
 ...
}, {
  scopes: {
    AnotherModel: () => {
       return {
          include: [
            {
              model: sequelize.models.AnotherModel
            }
         ]
      }
    }
  }
}
```

## What do you expect to happen?
I want all instances returned to derive from model, scope should not affect it

## What is actually happening?
One is an instance of class extends this.

_Output, either JSON or SQL_

__Dialect:postgres
__Dialect version:(PostgreSQL) 9.6.5
__Database version:(PostgreSQL) 9.6.5
__Sequelize version:4.38.0
__Tested with latest release:4.38.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Have you read https://github.com/sequelize/sequelize/issues/9494

**Comment by linpekka** [comment]
no, sorry, missed that one. Seems to be duplicate, feel free to close this one.

**Comment by linpekka** [comment]
or rather, the workaround suggested does not work for me since we cannot derive the new class back to Model.

**Comment by sushantdhiman** [comment]
So do you have a solution for problem (changing scope from one method should not change scope on other methods) I stated in other thread?

**Comment by linpekka** [comment]
Not really, but i have not given it much though, i assume you have, but could not the new class created still derive from Model, or even subclass AModel in my example?

**Comment by sushantdhiman** [comment]
Yeah probably can be done, instead of creating a new model from `Sequelize.Model` we can create new model by extending current model's class.

I'll tag this as a feature, feel free to implement this if you want to contribute

**Comment by linpekka** [comment]
Thanks the response, I will have to look closer at the code to get a feel for the scope of the work needed, and see if I can allocate time.

**Comment by linpekka** [comment]
Thanks for the link, It made me realize that the scope function actually does subclass itself, since and I just needed to account for a slightly longer chain of inheritance. I'm gonna close this one since it already works as desired.
