### ISSUE TITLE
Models not ready for use in scope definition

### ISSUE THREAD

**Issue by aaronfulkerson** [sequelize/sequelize#9864]
## What are you doing?

```js
module.exports = (sequelize, DataTypes) => {
  const Aardvark = sequelize.define('Aardvark', {
    name: {
      type: DataTypes.STRING
    }
  }, {
    scopes: {
      withAddress: {
        include: [
          sequelize.models.Address // produces an error because this model hasn't loaded yet
        ]
      }
    }
  })

  Aardvark.associate = models => {
    Aardvark.belongsToMany(models.Address, { through: 'AardvarkAddress' })
  }

  return Aardvark
}
```

## What do you expect to happen?
All models are available for use within scope definitions.

## What is actually happening?
Only models with names that precede the current model alphabetically are ready for use.

_Output, either JSON or SQL_
console.log on sequelize.models lists only models with names that alphabetically precede the current model. Using console.log on the models parameter in the associate method yields all models.

__Dialect:__ postgres
__Dialect version:__ latest
__Database version:__ latest
__Sequelize version:__ latest
__Tested with latest release:__ yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by papigers** [comment]
Can you show your model import code? My guess is that you're calling `associate` before all models were imported

**Comment by aaronfulkerson** [comment]
The importing is handled by the file index.js which is generated by the CLI. Associations are fine--if I call console.log(models) within the association block, all models are accounted for. However, if I try to define a scope using include that's where things start breaking down. You should get the same error I'm getting if you try passing undefined as a value in the include array of the scope definition.

**Comment by papigers** [comment]
Oh I get it now.
I'm not sure if there's a better solution for this, but for now you could define the scope as a function, in that case the model reference would be called when using the scope, rather when defining it.

Don't see any other solution since as you said, the other module hasn't been loaded yet.

**Comment by aaronfulkerson** [comment]
I was just doing some research and apparently the documentation mentions this.

http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-addScope

I have no idea where I'm supposed to call this method though. Placing it inside of the associate method works but that just doesn't seem right. In a previous version I think you could call it from loadScopes within classMethods but I think that was removed in v4.

**Comment by sushantdhiman** [comment]
You can either use functional scopes http://docs.sequelizejs.com/manual/tutorial/scopes.html#definition

```js
const Aardvark = sequelize.define('Aardvark', {
    name: {
      type: DataTypes.STRING
    }
  }, {
    scopes: {
      withAddress: () => ({
        include: [
          sequelize.models.Address
        ]
      })
    }
  })
```

You can also use addScope http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-addScope

```js
module.exports = (sequelize, DataTypes) => {
  const Aardvark = sequelize.define('Aardvark', {
    name: {
      type: DataTypes.STRING
    }
  })

  Aardvark.associate = models => {
    Aardvark.belongsToMany(models.Address, { through: 'AardvarkAddress' })
  }

 Aardvark.addScope('withAddress', function () {
   return {
      include: [
        sequelize.models.Address
      ]
    };
 });

  return Aardvark
}
```

**Comment by aaronfulkerson** [comment]
The functional scopes work perfectly, thanks for the tip. I feel like this issue should be in big bold letters in the documentation for scopes.

**Comment by yassernascimento** [comment]
agree with @aaronfulkerson, the functional scopes should be better informed on docs as a possible bug fixer
