### ISSUE TITLE
Sequelize obtain associated model data in the property

### ISSUE THREAD

**Issue by mageshkumaar** [sequelize/sequelize#9868]
I've two models, `User` and `Category`

User model:

    module.exports = (sequelize, DataTypes) => {
      const User = sequelize.define('User', {
        id: {
          type: DataTypes.BIGINT(19),
          allowNull: false,
          primaryKey: true,
          autoIncrement: true
        },
        firstname: {
          type: DataTypes.STRING(150),
          allowNull: false
        },
        lastname: {
          type: DataTypes.STRING(150),
          allowNull: false
        },
        email: {
          type: DataTypes.STRING(255),
          allowNull: false,
          unique: true
        },
        password: {
          type: DataTypes.STRING(255),
          allowNull: false
        }
      }, {
        tableName: 'users',
        timestamps: true,
        createdAt: 'created_at',
        updatedAt: 'updated_at',
        defaultScope: {
          attributes: {
            exclude: ['password']
          }
        },
        scopes: {
          withPassword: {
            attributes: {}
          }
        }
      })
    
      User.prototype.toJSON = function () {
        let values = Object.assign({}, this.get())
        delete values.password
        return values
      }
    
      return User
    }

Category model:

    module.exports = (sequelize, DataTypes) => {
      const Category = sequelize.define('Category', {
        id: {
          type: DataTypes.BIGINT(19),
          allowNull: false,
          primaryKey: true,
          autoIncrement: true
        },
        name: {
          type: DataTypes.STRING(150),
          allowNull: false
        },
        created_by: {
          type: DataTypes.BIGINT(19),
          allowNull: false,
          references: {
            model: 'users',
            key: 'id'
          }
        }
      }, {
        tableName: 'categories',
        timestamps: true,
        createdAt: 'created_at',
        updatedAt: 'updated_at'
      })
    
      Category.associate = (models) => {
        Category.belongsTo(models.User, {
          foreignKey: 'created_by'
        })
      }
    
      return Category
    }

My query to find the category:

    const category = await Category.findOne({
      include: [{
        model: User,
        required: true,
        attributes: ['id', 'firstname', 'lastname', 'email']
      }],
      where: {
        id: req.params.id
      },
      limit: 1
    })

When I execute the query, the response I expected was,

    {
        "id": 1,
        "name": "License",
        "created_by": {
            "id": 1,
            "firstname": "Magesh",
            "lastname": "Kumaar",
            "email": "mk@test.com"
        },
        "created_at": "2018-09-03T07:41:29.000Z",
        "updated_at": "2018-09-03T07:41:29.000Z"
    }

But the response I obtained was,

    {
        "id": 1,
        "name": "License",
        "created_by": 1, // I expected the user information here
        "created_at": "2018-09-03T07:41:29.000Z",
        "updated_at": "2018-09-03T07:41:29.000Z",
        "User": {
            "id": 1,
            "firstname": "Magesh",
            "lastname": "Kumaar",
            "email": "mk@test.com"
        }
    }

The user information is available at both `created_by` as Id and another `User` property that contains other information

I tried the `as` option, but it didn't seem to work. 

I got this error
```
Error: Naming collision between attribute 'created_by' and association 'created_by' on model Department. To remedy this, change either foreignKey or as in your association definition
```

__Dialect:__ mysql
__Dialect version:__ mysql2-1.6.1
__Database version:__ 5.5.61
__Sequelize version:__ 4.38.0
__Tested with latest release:__ Yes

Is there any way to get the user information in the `created_by` key itself.

I've asked the same in [stackoverflow](https://stackoverflow.com/questions/52146602/sequelize-obtain-associated-model-data-in-the-property). I am sorry that I've posted the same at two places. This may not be the right place to even raise this. I apologise in advance.

**Comment by mageshkumaar** [comment]
I tried as in the query but this error was thrown

```
error: SequelizeEagerLoadingError: User is associated to Category using an alias. You've included an alias (created_by), but it does not match the alias defined in your association.
```

**Comment by sushantdhiman** [comment]
Sequelize wont omit foreign key and insert included objected in place of that, that will simply give error you faced when trying to use `as`.

Simplest solution is to remove `created_by` key from main `Category` result and assign it with `User` result included
