### ISSUE TITLE
Should throw on error on unsupported queries like $gte on a date

### ISSUE THREAD

**Issue by hackhat** [sequelize/sequelize#9870]
v4.8

Code:

        operatorsAliases: false,

        const oldRoomServers = await models.RoomServer.findAll({
          where: {
            lastPing: {$lte: new Date()},
          },
          limit: 10,
        });

Creates query:

      Executing (default): SELECT "id", "roomType", "lastPing", "createdAt", "updatedAt" FROM "roomServers" AS "roomServer" WHERE "roomServer"."lastPing" = '2018-09-03 16:00:00.000 +00:00' LIMIT 10;

Should throw an error saying that $gte is deprecated or similar. In the docs doesn't say is deprecated but you should do something about it.

http://docs.sequelizejs.com/manual/tutorial/querying.html

> Sequelize will warn you if you're using the default aliases and not limiting them if you want to keep using all default aliases (excluding legacy ones) without the warning you can pass the following operatorsAliases option -

> For backward compatibility reasons Sequelize sets the following aliases by default - $eq, $ne, $gte, $gt, $lte, $lt, $not, $in, $notIn, $is, $like, $notLike, $iLike, $notILike, $regexp, $notRegexp, $iRegexp, $notIRegexp, $between, $notBetween, $overlap, $contains, $contained, $adjacent, $strictLeft, $strictRight, $noExtendRight, $noExtendLeft, $and, $or, $any, $all, $values, $col

> Currently the following legacy aliases are also set but are planned to be fully removed in the near future - ne, not, in, notIn, gte, gt, lte, lt, like, ilike, $ilike, nlike, $notlike, notilike, .., between, !.., notbetween, nbetween, overlap, &&, @>, <@

**Comment by sushantdhiman** [comment]
Use latest version it will throw deprecation, use v5 where these unsafe operators are removed

**Comment by hackhat** [comment]
V4 is still installed by default, so most people still use that one. I'm not sure I'd migrate right now, as is not a priority. I already learned that it swallows these errors, is more for other people to don't waste time with this kind of silly errors.

**Comment by sushantdhiman** [comment]
I meant latest v4, which throws this warning along with error when your try to use string operators with `operatorsAliases: false`
