### ISSUE TITLE
changeColumn error when updating ENUM value

### ISSUE THREAD

**Issue by WaleedAshraf** [sequelize/sequelize#9874]
## changeColumn: update ENUM value from uppercase to lowercase

```js
up:

return queryInterface.changeColumn(
	'users',
	'v_status',
	{ type: Sequelize.ENUM, values: ['active', 'passive', 'archived', 'deleted'], allowNull: false, validate: { notEmpty: true } }
);


down:

return queryInterface.changeColumn(
	'users',
	'v_status',
	{ type: Sequelize.ENUM, values: ['Active', 'Passive', 'Archived', 'Deleted'], allowNull: false, validate: { notEmpty: true } }
);
```

## What do you expect to happen?
I expted values to change,
from: 'Active', 'Passive', 'Archived', 'Deleted'
to: 'active', 'passive', 'archived', 'deleted'

## What is actually happening?
Error: 
```
Executing (default): ALTER TABLE `users` CHANGE `v_status` `v_status` ENUM() NOT NULL;
{ SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') NOT NULL' at line 1
    at ...node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
```

__Dialect:__ mysql
__Dialect version:__ 5.1.44
__Sequelize version:__ Sequelize [Node: 8.9.0, CLI: 2.8.0, ORM: 3.30.4]

**Comment by sushantdhiman** [comment]
v3 no longer supported

**Comment by WaleedAshraf** [comment]
@sushantdhiman this is also present in latest version.

**Comment by sushantdhiman** [comment]
We close issues as soon as they land to `master` branch, fix already released as `5.0.0-beta.12`

**Comment by WaleedAshraf** [comment]
@sushantdhiman, that's totally fine.
But in this case, you closed it before the fix.

**Comment by sushantdhiman** [comment]
Because you only tested this with v3 so I wasn;t aware if this issue was affecting upstream. We no longer support v3, so those issue get closed by default

**Comment by WaleedAshraf** [comment]
My fix was against upstream which made it clear.

**Comment by sushantdhiman** [comment]
I closed this issue before taking a look at PR, I have lots of issues to look after so I first go through issues then to PRs
