### ISSUE TITLE
JSON field marked changed even if custom setter noops

### ISSUE THREAD

**Issue by aheinz-fe** [sequelize/sequelize#9880]
## What are you doing?

```js
const _ = require('lodash');
const assert = require('chai').assert;
const Sequelize = require('sequelize');

it('custom setter does not mark changed', function() {
  var db = new Sequelize('sequelize_test', 'sequelize_test', 'sequelize_test', {
    dialect: 'postgres',
  });
  db.define('Model', {
    i: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    j: {
      type: Sequelize.JSONB,
      allowNull: true,
      set: function(j) {
        if (!_.isEqual(j, this.getDataValue('j'))) {
          this.setDataValue('j', j);
        } else {
          console.log('noop');
        }
      },
    },
  });
  return db.sync()
    .then(() => db.models.Model.create({
      j: ['a', 'b']
    }))
    .then((instance) => {
      assert.isFalse(instance.changed());
      instance.j = ['a', 'b'];
      assert.isFalse(instance.changed());
      // FIXME: AssertionError: expected [ 'j' ] to be false
    });
});
```

## What do you expect to happen?
I'm using custom setters to deeply compare jsonb values before actually updating the instance.

## What is actually happening?
The instance is being marked changed anyway and is updating the database.

__Dialect:__ postgres
__Database version:__ 9.4.17
__Sequelize version:__ 3.30.4
__Tested with latest release:__ No, but the relevant code doesn't seem to have changed much between v3, v4 and master.
https://github.com/sequelize/sequelize/blob/v3/lib/instance.js#L313-L317
https://github.com/sequelize/sequelize/blob/v4/lib/model.js#L3361-L3368
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3444-L3450

The !Utils.isPrimitive(value) check means that no matter what I do, since JSONB values are not primitives ['string', 'number', 'boolean'], the row will be updated in the database.

**Comment by aheinz-fe** [comment]
Given that Instance.setDataValue also contains logic to mark changed, the changed call in Instance.set seems redundant.
https://github.com/sequelize/sequelize/blob/v3/lib/instance.js#L162-L164
https://github.com/sequelize/sequelize/blob/v4/lib/model.js#L3216-L3218

**Comment by myleshk** [comment]
Any update on this bug?

I have a related problem when I want to detect changes on DATE type value, but it is always marked as changed, and cannot bypass the logic due to same reason as this issue.

**Comment by papb** [comment]
I will close this since I think #10851 has fixed it. If anyone is still experiencing the problem let me know.
