### ISSUE TITLE
How to select Distinct Fields using Sequelize for MSSQL DB

### ISSUE THREAD

**Issue by UmerIftikhar** [sequelize/sequelize#9888]
I have multiple associations with one of my models and I want to select **DISTINCT** fields on all of the Query.
The model looks as follow:    

```
    Parent.hasMany(Child1);
    Parent.hasMany(Child2);
    Child1.belongTo(Parent);
    Child2.belongTo(Parent);
```

I am using the following command to get back the distinct values.

```
    Parent.findAll({
    	distinct: true,
              include: [
    			  {
                      model: Child1,
                      attributes:  ['attr1', 'attr2']
                  },
    			  {
                      model: Child2,
                      attributes:  ['attr3', 'attr4']
                  },			  
    			]
    })	
```	

This query does not add the **DISTINCT** keyword before the generated query.
Am I missing some thing?  

**Question 2:**  
I was also trying distinct values for the Child1 only, so I tried the following query:  

```
    Parent.findAll({
    	distinct: true,
              include: [
    			  {
                      model: Child1,
                      attributes: [
                        [
                          sequelize.fn('DISTINCT', sequelize.col(attr1)), 'attr1'
                        ],
                        [
                          sequelize.fn('DISTINCT', sequelize.col('attr2')), 'attr2'
                        ]
                      ]
                  },
    			  {
                      model: Child2,
                      attributes:  ['attr1', 'attr2']
                  },			  
    			]
    });  
```

But this generated the SQL syntax which is not supported by the MSSQL Server.  
Example:  

    Select Parent.name, Parent.id, Distinct([Child1].[attr1]) as [Child1.attr1] ........

And when this query is executed I get the following error:  

    Incorrect syntax near the keyword 'DISTINCT'.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
