### ISSUE TITLE
notNull: true not working, allowNull: false does

### ISSUE THREAD

**Issue by actuallymentor** [sequelize/sequelize#9905]
## What are you doing?

```js

// The below INCORRECTLY creates an entry with 'name: null'
const Component = db.define( 'component', {
	name: {
		type: Sequelize.STRING,
		notNull: true
	},
	description: Sequelize.STRING
}

// The below INCORRECTLY creates an entry with 'name: null'
const Component = db.define( 'component', {
	name: {
		type: Sequelize.STRING,
		validate: { notNull: true }
	},
	description: Sequelize.STRING
}

// The below CORRECTLY rejects when 'name' is empty
const Component = db.define( 'component', {
	name: {
		type: Sequelize.STRING,
		allowNull: false
	},
	description: Sequelize.STRING
}
```

## What do you expect to happen?
I expected either of the first two to reject when `name: null`

## What is actually happening?
Database entry is created with `name: null`

```json
{ id: 1,
  userId: 1,
  updatedAt: '2018-09-11T08:18:42.720Z',
  createdAt: '2018-09-11T08:18:42.720Z',
  name: null,
  description: null
}
```

__Dialect:__ postgres
__Postgres version:__ 10.5
__Sequelize version:__ 4.38
__Tested with latest release:__ Yes, 4.38.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
1. Incorrect `notNull` is never an attribute option

```js
const Component = db.define( 'component', {
	name: {
		type: Sequelize.STRING,
		notNull: true
	},
	description: Sequelize.STRING
}
```

2. Incorrect, as `notNull` was removed as a validator in v4, AFAIR it prints an error for null case
```js
// The below INCORRECTLY creates an entry with 'name: null'
const Component = db.define( 'component', {
	name: {
		type: Sequelize.STRING,
		validate: { notNull: true }
	},
	description: Sequelize.STRING
}
```
3. Correct

```js
// The below CORRECTLY rejects when 'name' is empty
const Component = db.define( 'component', {
	name: {
		type: Sequelize.STRING,
		allowNull: false
	},
	description: Sequelize.STRING
}
```

In v5 this is slightly changed, Please go through https://github.com/sequelize/sequelize/blob/master/docs/models-definition.md#validators-and-allownull

**Comment by actuallymentor** [comment]
> 1. Incorrect notNull is never an attribute option
> 2. notNull was removed as a validator in v4

If the above is true then [the docs](http://docs.sequelizejs.com/manual/tutorial/models-definition.html) are very out of date. Screenshot for convenience:

![screen shot 2018-09-12 at 09 56 45](https://user-images.githubusercontent.com/9071382/45410527-36664880-b672-11e8-9980-877ba956e3e5.png)

**Comment by sushantdhiman** [comment]
Yes, master docs aren't updated on docs website, it is still serving v4 docs

**Comment by actuallymentor** [comment]
Where can I find the docs contribution protocol?

**Comment by gabooh** [comment]
Docs are still outdated about this, it's really misleading, I've just ran into the same issue, using notNull: true as per the docs details.

**Comment by papb** [comment]
@gabooh I am currently working on improving the docs, stay tuned!

**Comment by gabooh** [comment]
> @gabooh I am currently working on improving the docs, stay tuned!

That's awesome, thank you :)
