### ISSUE TITLE
Case when Then in Having Clause

### ISSUE THREAD

**Issue by nikhildodeja** [sequelize/sequelize#9907]
## Convert pivot field in having clause like case when then and if in max function.
I want to put condition in having clause. And I have a function case when which is working as a pivot table.

SELECT  request.createdBy,MAX(IF(NAME = 'upn', VALUE, NULL)) AS upn,
MAX(IF(NAME = 'town', VALUE, NULL)) AS town
FROM requestData
INNER JOIN request ON request.id = requestData.requestId
WHERE request.createdAt BETWEEN '2018-09-10 00:00:00' AND '2018-09-10 23:59:59'
AND request.processId = 1
GROUP BY requestData.requestId
HAVING MAX(IF(NAME = 'town', VALUE, NULL))  LIKE '%El%'

Can any one help me to convert this query into sequelize js orm form.

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
