### ISSUE TITLE
_warningRow is not iterable

### ISSUE THREAD

**Issue by zyfmix** [sequelize/sequelize#9918]
when i config sequelize log with winston logger with config below,I had set options with `showWarnings: true`

``` javascript
// 标准日志服务组件...
let wsLogs = require(global.appRoot + '/libs/WsLogs');
let sqlLogger = wsLogs.logger('sql');

let sequelizeOptions = {
    operatorsAliases: false,
    //operatorsAliases: Op,
    // 显示 SQL 警告信息...
    showWarnings: true,
    //logging: false,
    //logging: sqlLogger.verbose,
    logging: (msg) => sqlLogger.verbose(msg),
    // disable inserting undefined values as NULL
    // - default: false
    omitNull: false,
    ...db_config[name]
};
```
when i exe a warning sql,it crashed with error: `_warningRow is not iterable`,and can't show any warning msg from mysql,how to work around this?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
