### ISSUE TITLE
SequelizeDatabaseError: Got error -1 from storage engine

### ISSUE THREAD

**Issue by odaymard** [sequelize/sequelize#9920]
I am runing npm test and everything is ok suddenly i run it and got this error SequelizeDatabaseError: Got error -1 from storage engine

```
before(async function() {
  await machines.destroy({
    truncate: true,
    force: true,
    individualHooks: true,
    logging: true
  });
  await machines.create({
    name: "machinetest1",
    description: "machinetest1description",
    individualHooks: true
  });
  await machines.create({
    name: "machinetest2",
    description: "machinetest2description",
    individualHooks: true
  });
  await machines.create({
    name: "machinetest3",
    description: "machinetest3description",
    individualHooks: true
  });
});
```

>     "mysql2": "^1.6.1",
>     "sequelize": "^4.38.0",
>     "sequelize-cli": "^4.1.1"
>      "mysql database": 5.6.34-log

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
