### ISSUE TITLE
Sequelize converts date in logs from UTC to local time

### ISSUE THREAD

**Issue by metuan** [sequelize/sequelize#9922]
## What are you doing?

In database I store model with `myDate` field which is stored in UTC. I also have a query where time period is specified:

`AND p.myDate BETWEEN :dateStart AND :dateEnd`

Using `sequelize.query`, I replace parameters with:

 - `dateStart: 2018-09-11T22:00:00.000Z`
 - `dateEnd: 2018-09-14T14:15:40.609Z`

and now the problem is that I see query is executing however with localTime values: 

`AND p.myDate BETWEEN '2018-09-12 00:00:00' AND '2018-09-14 16:15:40'`

I did not specify `options.timezone` however according to documentation: `default: '+00:00'` from : [doc](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor)

## What do you expect to happen?
I would like to have UTC dates passed to the query as replacements, so it will show it in logs.

## What is actually happening?
It prints:

`AND p.myDate BETWEEN '2018-09-12 00:00:00' AND '2018-09-14 16:15:40'`

so we see that it magically converts dates to local time (Poland CEST)

__Dialect:__ mysql
__Dialect version:__ default one (not specified)
__Database version:__ mysql  Ver 15.1 Distrib 10.2.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
__Sequelize version:__ 4.37.2
__Tested with latest release:__ No

**Comment by abdularis** [comment]
I also have the same problem, in the log it says,
INSERT INTO ...... VALUES ('2018-12-12 08:10:27','2018-12-12 08:10:27');
that's the UTC (+00:00) which is the default, and when I see in the database somehow it converted to local time which is (+07:00) 2018-12-12 15:10:27,

DB: mysql

**Comment by wondie** [comment]
After two years, this issue is still there...
