### ISSUE TITLE
Feature: expose option.database as Sequelize.getDatabaseName()

### ISSUE THREAD

**Issue by zypA13510** [sequelize/sequelize#9924]
When I use raw queries (read use case below), I need to include database/schema name in the query. I noticed that I can retrieve it from [`sequelize.config.database`](/sequelize/sequelize/blob/master/lib/sequelize.js#L191), but this is not documented thus a rather dangerous approach I suppose. So I'm requesting if it is possible to expose the option as a function.

Of course, I know that I can just pass the string along from where the options are supplied, but I think it would be more convenient if we can retrieve it from the sequelize instance since we have it already?

Dialect: MySQL (I'm not sure if this is dialect specific)

### My use case
Get current `AUTO_INCREMENT` value of a table from `information_schema`:
```js
let databaseName// = ???
let tableName = sequelize.models.MyTable.name
let autoIncrementValue
sequelize.query(`
  SELECT AUTO_INCREMENT
  FROM information_schema.TABLES
  WHERE
    TABLE_SCHEMA = '${databaseName}'
    AND TABLE_NAME = '${tableName}'
`, {
  type: Sequelize.QueryTypes.SELECT
}).then(result => {
  autoIncrementValue = result
})
```

**Comment by sushantdhiman** [comment]
Implemented in https://github.com/sequelize/sequelize/pull/9937
