### ISSUE TITLE
as: {singular, plural} not working with include: {all: true}

### ISSUE THREAD

**Issue by actuallymentor** [sequelize/sequelize#9928]
## What are you doing?

I am specifying the singular and plural names of an alias. I then later try to include with the `all: true` option, but that results in a `SequelizeDatabaseError` of `{ name: 'SequelizeEagerLoadingError' }`.

When I specify an `as` without explicit singular/plurals this issue does not arise.

Note: I think the issue is similar to what @raxod502 commented [here](https://github.com/sequelize/sequelize/issues/6007#issuecomment-315431681).

```js
let name = 'theAliasName'

// Below works with include: { all: true }
through: db.define( name, {
		amount: Sequelize.FLOAT,
		unit: Sequelize.STRING,
		dataSource: Sequelize.STRING
	} ),
	as: name + 's'
} )

// Below DOES NOT work
through: db.define( name, {
		amount: Sequelize.FLOAT,
		unit: Sequelize.STRING,
		dataSource: Sequelize.STRING
	} ),
	as: {
		singular: name,
		plural: name + 's'
	}
} )

```

Later these associations are called with:

```js
Model.findOne( {
    where: { id: relevant_id, userId: user_id },
    include: [ { all: true } ]
} ) )
```

## What do you expect to happen?

I expect:
- The alias table to be populated when a relationship is set (happens in both cases, no issue)
- The `include: { all: true }` to load the associated data

## What is actually happening?

Sequelize throws `{ name: 'SequelizeEagerLoadingError' }`

__Dialect:__ postgres
__Database version:__ 10.5
__Sequelize version:__ 4.38.1
__Tested with latest release:__ Yes

Edit 1: added code used to findOne
Edit 2: added error name

**Comment by actuallymentor** [comment]
A little update: I dug a little deeper and the { all: true } seems to trigger the following issue:

`SequelizeEagerLoadingError: <model> is associated to <model> multiple times. To identify the correct association, you must use the 'as' keyword to specify the alias of the association you want to include.`[1]

I see now where sequelize gets confused, but this is something the { all: true } should be able to handle. Is this a known issue?

[1] <model> is me replacing the name of the model with a generic placeholder

**Comment by actuallymentor** [comment]
Through another few painful hours I re-coded my application so that I didn't use `include: [ { all: true } ]` but rather pass an array of:

```js
include: [ { model: modelName, as: associationName }, { model: modelName2, as: associationName2 }, { andso: onward } ]
```

The error I get is identical:

`{ SequelizeEagerLoadingError:<model> is associated to<model> multiple times. To identify the correct association, you must use the 'as' keyword to specify the alias of the association you want to include.`

**Comment by actuallymentor** [comment]
Ok, so how I ended up solving this is manually adding an associations list to every model .

Illustrating the principle:

```js

// Create an array on every model
model.customAssociationList = []

// Populate each array with the relationships
model.customAssociationList.push( { model: childModel, as: 'theAliasUsed' } )

```

Then when calling findOne I used:

```js
include: model.associationList
```

My conclusion remains that this is not expected behavior. Using `include: [ { all: true } ]` should return all child models with known aliases.

**Comment by sushantdhiman** [comment]
Can I get a SSCCE which I can execute directly. You explanation is bit rough

------------------------------

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by actuallymentor** [comment]
Sure thing:

```js
// Make connection
const Seq = require ( 'sequelize' )
const seq = new Seq( 'githubissue', 'postgres', '', {
	dialect: 'postgres',
	host: 'localhost',
	logging: true
} )

// Make some models
const individual = seq.define( 'individual', {
	name: Seq.STRING
} )

const hat = seq.define( 'hat', {
	color: Seq.STRING
} )

const event = seq.define( 'event', {
	type: Seq.STRING
} )

// Set model connections
hat.belongsToMany( individual, {
	through: event,
	as: {
		singular: 'hatwornby',
		plural: 'hatwornbys'
	}
} )

individual.belongsToMany( hat, {
	through: event,
	as: {
		singular: 'personwearinghat',
		plural: 'personwearinghats'
	}
} )

// Sync database
seq.sync( { force: true } )
// Create a person and a hat
.then( f => Promise.all( [
	individual.create( { name: 'Sir Derp' } ),
	hat.create( { color: 'Gold' } )
] ) )
// Set the relationship
.then( items => {
	const [ theperson, thehat ] = items
	return thehat.addHatwornby( theperson )
} )
// Find an individual and include his hats
.then( f => individual.findOne( {
	where: { id: 1 },
	include: [ { model: hat, as: 'personwearinghats' } ]
} ) )
// Console out the person with included hats: THIS WORKS
.then( person => console.log( person.toJSON() ) )
// Now try to eager load the individual with all associations: THIS DOWS NOT WORK
.then( f => individual.findOne( {
	where: { id: 1 },
	include: [ { all: true } ]
} ) )
.then( console.log.bind( console ) )
.catch( console.log.bind( console ) )
```

**Comment by tsasaki609** [comment]
Hello,
I checked the code. It seems that it is not difficult problem and I try to fix now. 
Please wait for a while. 😸

**Comment by tsasaki609** [comment]
I guess it has not been released yet.

@sushantdhiman When will it be?

**Comment by sushantdhiman** [comment]
Will try releasing this weekend
