### ISSUE TITLE
Nested transactions in sqlite gives error : commit has been called on this transaction

### ISSUE THREAD

**Issue by srinivasrk** [sequelize/sequelize#9942]
## What are you doing?
I have a sqlite model which is using unmanaged transactions to insert rows after parsing a csv file.

```
firstUpdateChain = firstUpdateChain .then(() => updateChannelWithRow(row,transaction)).then(() => {
                  row['generator'] = 'raw'
                  rawUpdateChain = rawUpdateChain.then(() => updateChannelWithRow(row,transaction)).then(() => {
                    // create 1 additional entry when the InFlux Edited Data == 'Required' for edited
                    if(record['InFlux Edited Data'] == 'Required') {
                      row['generator'] = 'edit'
                      editUpdateChain = editUpdateChain.then(() => updateChannelWithRow(row,transaction)) // append update-chain with edit
                    }
                  })
                })
```

The actual db operations happen here : 

```
let updateChannelWithRow = (row,transaction) => {
    return db.Site.findOrCreate({where: {name:row.site}, transaction, defaults:{active:false}})
}
```

After all the lines of csv has been completed I have this code : 

```
Promise.all([firstUpdateChain, rawUpdateChain, editUpdateChain]).then(() => {
                transaction.commit()
                console.log(new Date() + " Successfully updated channels database via /api/channels?format=flowfinity");
                res.status(200).send("Successfully updated channels database");
            })
```

## What do you expect to happen?
Transaction to complete without error

## What is actually happening?
Transaction completes and the data is seen in the DB but it logs this error : 

```
 Unhandled Rejection at: Error: commit has been called on this transaction(bb536609-3a51-4424-826f-b8e0dfcd3f76), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
```
-----------------------------------------------------------------------
Update:
Same issue happens when I call ` transaction.rollback() `
------------------------------------------------------------------------
__Dialect: sqlite
__Sequelize version: 4.38.0

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
