### ISSUE TITLE
Models are undefined when imported into other files

### ISSUE THREAD

**Issue by elizajanus** [sequelize/sequelize#9943]
## What are you doing?
I have an express app set up with Sequelize according to the Sequelize recommendations. When I start the server, the database connects and syncs fine; it correctly creates tables based on the model files. However, when I try to go to an api route, such as "localhost:3000/api/trips" I get an error that the property cannot be called on 'undefined.' I console.logged "db.Trip" and "db.Lane" after importing all the models as const db, and they both returned undefined, so I can assume that all the models are returning undefined when they are imported. Here is a repository with the code setup I am referring to: [https://github.com/elizajanus/api-dev-example](https://github.com/elizajanus/api-dev-example).

Examples to get an idea of what's going on:

Trip model:
```
'use strict';

module.exports = (sequelize, DataTypes) => {
  const Trip = sequelize.define('trip', {
    id: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    active: {
      type: DataTypes.TINYINT(1),
      defaultValue: 1,
      allowNull: false
    },
    customer_id: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      references: {
        model: 'customer',
        key: 'customer_id'
      }
    }
  }, {
    tableName: 'trip'
  });
  return Trip;
};
```

models index.js:
```
'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(__filename);
// var env       = process.env.NODE_ENV || 'development';
var config    = require('../config/config.js');
var db        = {};

var sequelize = new Sequelize(config.database, config.username, config.password, config);

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```
controller file:
```
const db = require("../models");

module.exports = {
  findAll: (req, res) => {
    db.Trip
      .findAll({
        order:[['date', 'DESC']]
      })
      .then(dbTrip => res.json(dbTrip))
      .catch(err => res.status(422).json(err));
  },
  findActiveCustomerEntries: (req, res) => {
    var customer_id = req.params.customer_id;
    db.Trip
      .findAll({
        where: {
          customer_id: customer_id,
          active: true
        },
        order:[['date', 'DESC']]
      })
      .then(dbTrip => res.json(dbTrip))
      .catch(err => res.status(422).json(err));
  },
  create: (req, res) => {
    db.Trip
      .create(req.body)
      .then(dbTrip => res.json(dbTrip))
      .catch(err => res.status(422).json(err));
  },
  makeInactive: (req, res) => {
    db.Trip
      .update(
        { active: false },
        { where: { id: req.params.trip_id } })
      .then(dbTrip => res.json(dbTrip))
      .catch(err => res.status(422).json(err));
  },
  update: (req, res) => {
    db.Trip
    .update(
      req.body,
      { where: { id: req.params.trip_id } })
      .then(dbTrip => res.json(dbTrip))
      .catch(err => res.status(422).json(err));
  }
}
```

## What do you expect to happen?
I am expecting the controller file to load the model file so that the table queries can be called based on express router

## What is actually happening?
When I access the api route to "get" trips json:
TypeError: Cannot read property 'findAll' of undefined
    at findAll (/Users/elizajanus/Desktop/api-dev/controllers/tripsController.js:6:8)

Dialect: mysql
Dialect version: ^1.6.1 (mysql 2)
Sequelize version: ^4.38.1

**Comment by sushantdhiman** [comment]
I dont think this is related to Sequelize, you can study working express setup https://github.com/sequelize/express-example

-------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by elizajanus** [comment]
I set up the models with the sequelize cli instead, as well as the executable file instead of the regular server.js, and it works fine now

**Comment by Alexzanderk** [comment]
The same issue

**Comment by Chuck672991** [comment]
did your issue solved?? because im having the same issue right now models are undefine when i m console.log

**Comment by capybara-webkitsubstitut** [comment]
> The same issue





https://klayoxidation.github.io/yFs52wkR6m6kGNbr3z7bnsaC/
