### ISSUE TITLE
Access timestamps from createdAt/updatedAt instead of custom field name

### ISSUE THREAD

**Issue by zypA13510** [sequelize/sequelize#9944]
In current sequelize, when a custom column name has been assigned to one of the timestamps, the timestamp value is no longer accessible from Model.createdAt / updated.At etc.

From my understanding, this [v5 change](/sequelize/sequelize/issues/6423#issuecomment-379472035) will only change the behavior when timestamps are not customized.

I'm a very new user of sequelize, but tbh I think this is inconsistent, isn't it? What is the reason behind this design? (Please consider this as a feature request)

## What are you doing?
```js
const MyTable = sequelize.define('mytable', {
  myField: {
    type: Sequelize.INTEGER,
    field: 'my_column',
  },
}, {
  createdAt: 'my_created_at',
  updatedAt: false,
});
MyTable.create({
  myField: 0,
})).then(myInstance => {
  console.log(myInstance.myField); // 0
  console.log(myInstance.createdAt); // undefined
  console.log(myInstance.my_created_at); // createdAt timestamp
});
```

## What do you expect to happen?
myInstance.createdAt shows the createdAt timestamp.

__Dialect:__ mysql
__Sequelize version:__ 4.38.1

**Comment by sushantdhiman** [comment]
`createdAt: 'my_created_at',` means a new attribute will be created with this name `my_created_at`

If you want to customize just field name you should do something like this

```js
'use strict';

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const MyTable = sequelize.define('mytable', {
  myField: {
    type: Sequelize.INTEGER,
    field: 'my_column',
  },
  createdAt: {
    type: Sequelize.DATE,
    field: 'my_created_at'
  }
}, {
  updatedAt: false,
  timestamps: true
});

sequelize.sync({ force: true }).then(() => {
  return sequelize.authenticate();
}).then(() => {
  return MyTable.create({
    myField: 0,
  }).then(myInstance => {
    console.log(myInstance.myField); // 0
    console.log(myInstance.createdAt); //  createdAt timestamp
    console.log(myInstance.my_created_at); // undefined
  });
});
```

```sql
0
2018-09-21T05:47:30.001Z
undefined
```

**Comment by zypA13510** [comment]
My bad, I forgot the timestamp fields can be modified from the attributes parameter instead of options.
Thanks. Closing this issue.
