### ISSUE TITLE
Unrecognized data type for field name( Vague Error Message)

### ISSUE THREAD

**Issue by TJBrowne** [sequelize/sequelize#9955]
## What are you doing?

```js
const Tea = sequelize.define('tea', {
  name:sequelize.TEXT
})
```

## What do you expect to happen?
I expected a more descriptive error message that pin point where the problem occurred.

I suggest maybe adding information like model name to the error message, and quotes around the column:

```
Unrecognized data type for field "name" for the "tea" model.
```

## What is actually happening?
This is the error message I received
```
Unrecognized data type for field name.
```
_Output, either JSON or SQL_

__Dialect: postgres 
__Dialect version:__ 10.4
__Database version:__ XXX not sure
__Sequelize version:__ 4.38.1
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SaitejaP** [comment]
The message has already been updated to

> Unrecognised datatype for attribute "${this.name}.${name}"

It will be available from version `v5-beta`

**Comment by sushantdhiman** [comment]
^ @TJBrowne

**Comment by JulianAdams4** [comment]
I was getting an
```
  original: Error: Data too long for column 'description' at row 4
```

To change to LONGTEXT, I solved by:
```
  const Model = sequelize.define('TableName', {
    title: {
      type: DataTypes.TEXT,
    },
    description: {
      type: DataTypes.TEXT('long'), // <-- This
    },
    ...moreAttributes
  });
```
