### ISSUE TITLE
Add support for PG `?&` operator

### ISSUE THREAD

**Issue by acodercat** [sequelize/sequelize#9956]
## What are you doing?

client_ids is json field
["0a5dd8ef-380c-48df-94a2-801fd1256646", "123"]

I want select Contain "123" all rows.

```js
// code here
```

_Output, either JSON or SQL_

 SELECT "id", "client_ids" FROM "account" AS "account" WHERE client_ids ?& array[ '123'];

__Dialect: postgres
__Dialect version:last
__Database version:last
__Sequelize version:last
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by acodercat** [comment]
please！！！I need

**Comment by sushantdhiman** [comment]
For now you can do this by something like this

```js
Model.findAll({
   where: {
      [Op.and]: [Sequelize.literal("client_ids ?& $ids")]
   },
   bind: {
      ids: ['123', '234', ....]
   }
})
```
