### ISSUE TITLE
model.create() does not save columns in the database.

### ISSUE THREAD

**Issue by IndeDude** [sequelize/sequelize#9961]
## What are you doing?

**Adding a record to the database**
```js
// code here
const User = require('../models/User');
const authService = require('../services/auth.service');
const bcryptService = require('../services/bcrypt.service');
const UserController = () => {
  const register = async (req, res) => {
    const { email, password, password2 } = req.body;
    if (password === password2) {
      try {
        const user = await User.create({
          email,
          password,
        });
        const token = authService().issue({ id: user.id });
        return res.status(200).json({ token, user });
      } catch (err) {
        console.log(err);
        return res.status(500).json({ msg: 'Internal server error' });
      }
    }
    return res.status(400).json({ msg: 'Bad Request: Passwords don\'t match' });
  };
 // Login etc...
}
```

## What do you expect to happen?
I expect the User.create() to  save all the values passed (in this case email and password)

## What is actually happening?
_Only id, password and timestamps were saved in the database!_
In another test using a user created model nothing except id and timestamps were saved.
_The behaviour was same across different apps and different databases ( viz., Postgresql and Sqlite3)_
_Output, either JSON or SQL_

id | email | password | createdAt | updated at |
1| NULL|$2a$10$/...| timestamp|timestamp

--

**I even tried by cloning this repo [https://github.com/lorenseanstewart/sequelize-crud-101](url) with the same results**

__Dialect:__  postgres / sqlite / 
__Dialect version:__ 10.5
_Database version:__ Ubuntu 10.5-1 pgdg18,04+1
__Sequelize version:__ 4.39.0
__Tested with latest release:__ yes 4.39.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by IndeDude** [comment]
**Tested with latest release ** 5.0.0-beta-12

**Comment by IndeDude** [comment]
sorry. Closed by mistake.

**Comment by sushantdhiman** [comment]
Post your model definitions, `values` and SQL logs. Are you sure email is defined?

**Comment by ati0ns** [comment]
I have this problem when I try to save an array, it has always null as value.
```js
guildsSettings.create({
    administrators: ["236207773166075916"],
    bad_words: [],
    custom_prefix: null,
    delete_commands: false,
    guild_id: foundGuild.id,
    moderators: []
})
.then(result => console.log(result));
```
`result` has the array in `administrators` but when I try to collect the administrators of a the model, it is always null because it looks like it is not saved in the database.
```js
const guildSettings = guildsSettings.findOne({ where: { guild_id: foundGuild.id } });
console.log(guildSettings.get("administrators"));
// null
```
