### ISSUE TITLE
warn if model/key is accidentally used in addConstraint, or if table/field is accidentally used in attribute definition

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#9962]
I'm happy to make a PR for this eventually, just wanted to go ahead and mention this.

There is an unfortunate difference between the `references` config for an attribute definition and an `addConstraint` operation.  In an attribute definition, one uses `model`/`key`.  In an `addConstraint` operation, one uses `table`/`field`.  I understand and agree with the naming differences, but they are begging for devs to make a mistake.

To help devs avoid accidentally using the wrong one, we ought to make `Model.init`, `QueryInterface.createTable`, `QueryInterface.addColumn` etc. warn if `table` is used within `references` for any attribute.  And for `addConstraint` we should warn if `model` or `key` is used within `references`.

**Comment by sushantdhiman** [comment]
> Model.init etc. warn if table is used within references for any attribute. 

This is acceptable 

> And for QueryInterface.createTable, QueryInterface.addColumn, QueryInterface.addConstraint we should warn if model or key is used within references.

This is problematic, practically query interface methods should not depend upon model as they are low level API. I agree there are many case where we are using model in `queryInterface` even `queryGenerator`, I hope we can clean them up someday

**Comment by jedwards1211** [comment]
@sushantdhiman I'm saying if one accidentally passes `model: 'someModelName'` to `queryInterface.createTable` rather than a model class

**Comment by sushantdhiman** [comment]
I think passing `model` as `string` is supported with `createTable` it points to that `table` (It should be called `table`)

**Comment by papb** [comment]
@jedwards1211 Is this still an issue?

**Comment by jedwards1211** [comment]
I don't know, I use raw sql queries for my migrations these days

**Comment by papb** [comment]
I will close this, if anyone thinks this should be reopened feel free to ping me.
