### ISSUE TITLE
Extending datatype to add global setter for this type

### ISSUE THREAD

**Issue by antondc** [sequelize/sequelize#9965]
## What are you doing?

Trying to extend a type in order to set a a global setter for this type
```
function CUSTOM_STRING(length) {
    const options = (typeof length === 'object' && length) || { length };
    if (!(this instanceof CUSTOM_STRING)) {
        return new CUSTOM_STRING(options);
    }
    DataTypes.STRING.call(this, options);
}
util.inherits(CUSTOM_STRING, DataTypes.STRING);

DataTypes.CUSTOM_STRING = CUSTOM_STRING;
DataTypes.CUSTOM_STRING.prototype._get = function _get(value, originalValue) {
    // Logic here
};
```

## What do you expect to happen?
The getter method for this property should be triggered everytime is saved

## What is actually happening?
The extended type is available, but there is no apparent or documented way to define a getter for it.

_Output, either JSON or SQL_

__Dialect:__ mysql
__Sequelize version:__ 4.37.7
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Where are you getting `_get` reference, this is not supported even for Base Types. I don't think I would like to support this in near future as well.

**Comment by antondc** [comment]
Well, I would like to do a task for some items that are STRING types. That task needs the name of the field —lets say `title`, the name of the model —lets say `Projects—` and the value inserted in the field. I know that I can define my type with a setter like so:

```
            custom_string: {
                type: DataTypes.STRING,
                defaultValue: 'Default content for custom string',
                set(field, val) {
                    console.log(field); // Field name
                    console.log(val); // Field value
                    console.log(this); // Model name
                },
            },
```

I would like to extend `STRING` type create a `CUSTOM_STRING` type that will trigger a this getter by default with these parameters. Is it possible?

**Comment by antondc** [comment]
Sorry, there was a misunderstanding: I want to create a global setter, not a getter. But the case remains the same.

The task I want to do in the setter is quite complex, and needs current model, current field and current value. All this is available in `set`. I know I can use a setter in each attribute definition for that, but I would end up repeating a lot of code.

```
custom_string: {
    type: DataTypes.STRING,
    defaultValue: 'Default content for my string',
    set(field, val) {
        // A lot of code here
    },
},
custom_string2: {
    type: DataTypes.STRING,
    defaultValue: 'Default content for my string',
    set(field, val) {
        // Same code here again
    },
},
```

I know also that I can extract this logic to a module, and call it from the setter:
```
custom_string: {
    type: DataTypes.STRING,
    defaultValue: 'Default content for my string',
    set(field, val) {
        setterUtil.call(this, field, val)
    },
},
custom_string2: {
    type: DataTypes.STRING,
    defaultValue: 'Default content for my string',
    set(field, val) {
        setterUtil.call(this, field, val)
    },
},

// ./setterUtil.js
module.exports = {
    // Logic here
}
```

This should work, but as I understand it this is not the cleanest way. 

It would be great to be able to define a `setter` for a specific data type that will trigger everytime this type is saved. Has to be a setter because, as I understand it, is the only way to retrieve the `model`, `value` and `field` name.

**Comment by sushantdhiman** [comment]
If you want to customize what is sent to database you can define [`_stringify`](https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L612) on your custom datatype. This is a private API btw.

**Comment by antondc** [comment]
Thanks! Now I am able to create `CUSTOM_STRING` extending `STRING`, and then overwrite _stringify. From there I access to the related `value`, the `field` and the `model`.

```
import DataTypes from 'sequelize';

class CUSTOM_STRING extends DataTypes.STRING {
    constructor() {
        super();
        this.key = 'CUSTOM_STRING';
    }
}
DataTypes.CUSTOM_STRING = CUSTOM_STRING;

DataTypes.CUSTOM_STRING.prototype._stringify = function _stringify(value, options) {
    console.log(value); // Value
    console.log(options.field.fieldName); // Field name
    console.log(options.field.Model); // Model
    return JSON.stringify(value);
};

const CustomTypes = {
    CUSTOM_STRING: DataTypes.CUSTOM_STRING,
};

const Projects = sequelize.define(
    'Projects',
    {
        custom_string: {
            type: CustomTypes.CUSTOM_STRING,
    },
);
```

I see that `_stringify` is triggered only when the model is initializated, but not when saved. Is there a correct way to link it to update or create?

**Comment by antondc** [comment]
>This is a private API btw.

Why it is important? What are the implications?

**Comment by sushantdhiman** [comment]
private API can change without any warning in same major semver range

**Comment by antondc** [comment]
Thanks, I understand. Then, is there a correct way to extend types with global setters for this type, or achieving similar behaviour?

**Comment by sushantdhiman** [comment]
Not yet, This can be solved by providing some plugin like extensions for custom datatypes.

**Comment by antondc** [comment]
Thanks; then I will stick with this solution until an official API is released for extending types.

I hope this is in the scope for next releases. I worked with Django a while ago, and the possibility of extending types there is really powerful.
