### ISSUE TITLE
Return the results of findAll() as an object with ID-key instead of array

### ISSUE THREAD

**Issue by eduardrock** [sequelize/sequelize#9966]
When I execute findAll I got something like this:

[
      {
            "id": 13647,
            "isSuspended": false,
            "name": "Coca-Cola",
            "bottlesInBox": "6",
       },
      {
            "id": 12223,
            "isSuspended": false,
            "name": "Sprite",
            "bottlesInBox": "6",
       },
      {
            "id":  45463,
            "isSuspended": false,
            "name": "Fanta",
            "bottlesInBox": "6",
       },
]

Is there a way to return it like an object where each key is the id of every item?

{
      13647: {
            "id": 13647,
            "isSuspended": false,
            "name": "Coca-Cola",
            "bottlesInBox": "6",
       },
      12223: {
            "id": 12223,
            "isSuspended": false,
            "name": "Sprite",
            "bottlesInBox": "6",
       },
      45463: {
            "id":  45463,
            "isSuspended": false,
            "name": "Fanta",
            "bottlesInBox": "6",
       },
}

**Comment by sushantdhiman** [comment]
Follow the issue template
