### ISSUE TITLE
MSSQL Date uses DateTimeOffset format, not DateTime or DateTime2

### ISSUE THREAD

**Issue by 3iMichael** [sequelize/sequelize#9967]
## What are you doing?
Trying to write a DateTime value to a MSSQL (SQL Server 2014) DB. Column is defined as sequelize.DATE.

```js
// code here
```

## What do you expect to happen?
As per [microsoft spec](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-2017), sequelize should set the value with a format of 
> YYYY-MM-DD hh:mm:ss[.nnn]

## What is actually happening?
Sequelize tries to set the value with a format of YYYY-MM-DD hh:mm:ss[.nnn] [+|-]hh:mm, resulting in
> SequelizeDatabaseError: Conversion failed when converting date and/or time from character string.

__Dialect:__ mssql
__Dialect version:__ SQL Server 2014, but as per spec this should also affect the current version
__Database version:__ SQL Server 2014
__Sequelize version:__ 4.39.0
__Tested with latest release:__ Yes (latest V4 release anyway, not V5 Beta)

**Comment by sushantdhiman** [comment]
Thanks for following issue template, this bug has already been reported https://github.com/sequelize/sequelize/issues/7930
