### ISSUE TITLE
[Question] BelongsToMany: add[singular](pk) does not trigger individual hooks

### ISSUE THREAD

**Issue by frlinw** [sequelize/sequelize#9969]
## What are you doing?

```js
const Plan= sequelize.define('Plan', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true
  }
  name: Sequelize.STRING,
})

const User = sequelize.define('user', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true
  },
  name: Sequelize.STRING
})

const UserPlan = sequelize.define('UserPlan', {
        id: {
          type: Sequelize.UUID,
          defaultValue: Sequelize.UUIDV4,
          primaryKey: true
        },
        userId: {
          type: Sequelize.UUID,
          references: {
            model: 'User',
            key: 'id'
          },
          onDelete: 'CASCADE'
        },
        planId: {
          type: Sequelize.UUID,
          references: {
            model: 'Plan',
            key: 'id'
          },
          onDelete: 'CASCADE'
        }
})

User.belongsToMany(Plan, {
      as: 'plans',
      foreignKey: 'userId',
      through: UserPlan
})
```

## What do you expect to happen?
Individual hook of `UserPlan` should be triggered on `user.addPlan(planId)`

## What is actually happening?
`user.addPlan(planPk)` does not trigger `UserPlan` individual hooks.
`user.addPlan(planPk, { individualHooks: true })` trigger `UserPlan` individual hooks but the option should not be necessary for a single add 

same thing happens with `.removePlan()`

__Dialect:__ postgres
__Database version:__ 10.x
__Sequelize version:__ 5.x
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
I can say this is a bug but probably occurred because `addSingle` and `addMultiple` share code-base. As you stated this can be solved by `individualHooks: true`

**Comment by frlinw** [comment]
It's ok if I auto-set `individualHooks` to true if it's a pk or a single item array ?

**Comment by sushantdhiman** [comment]
We already have a issue for this https://github.com/sequelize/sequelize/issues/4780
