### ISSUE TITLE
useMaster not persisting through subqueries

### ISSUE THREAD

**Issue by KidA001** [sequelize/sequelize#9971]
## What are you doing?
We are running an AWS Aurora Database with a read replica, and a AWS Lambda GraphQL API. We are running into issues where we create or update a record, and when we return that record, it's null. If we check in the database immediately after, the create/update to that record/field is there.

We were able to pinpoint this (99% sure) to being due to our read replica delay. When we disable replica in our config, the problem does not persist.

Below is the config with have with sequelize for our replica database:

```javascript
const config = {
  dialect: "postgres",
  logging: process.env.IS_OFFLINE ? console.log : false,
  migrationStorageTableName: "sequelizeMeta",
  operatorsAliases: false,
  pool: { minConnections: 0, maxConnections: 1 }
};

let _db;
export default async function() {
  if (_db) {
    return _db;
  }
  let sequelize;

  const databaseUrl = await environment.databaseUrl();
  const databaseConfig = parseDbUrl(databaseUrl);

  const databaseReadReplicaUrl = await environment.databaseReadReplicaUrl();

  if (databaseReadReplicaUrl) {
    const databaseReadReplicaConfig = parseDbUrl(databaseReadReplicaUrl);

    sequelize = new Sequelize(databaseConfig.database, null, null, {
      ...config,
      replication: {
        read: [
          {
            host: databaseReadReplicaConfig.host,
            username: databaseReadReplicaConfig.user,
            password: databaseReadReplicaConfig.password
          }
        ],
        write: {
          host: databaseConfig.host,
          username: databaseConfig.user,
          password: databaseConfig.password
        }
      }
    });
  } else {
    sequelize = new Sequelize(
      databaseConfig.database,
      databaseConfig.user,
      databaseConfig.password,
      {
        ...config,
        host: databaseConfig.host
      }
    );
  }
...
```

After reading around a bit I found the `useMaster: true`  option I could pass to queries. I set `useMaster` in our context so it can be passed around globally,  as some models we return have fields that are subqueries.

## What do you expect to happen?

There are multiple examples of this happening, but this specific example is when we create a `Follower`  record, we return the `User` who was followed, and on that user they have a field called `followingInfo` which is a subquery that returns a status of the following record that was just created (pending/approved).

**Create follower mutation**
```javascript
context.userMaster = true;

const followingUser = await db.User.findOne({
  where: {
    id
  }
},   { useMaster: context.useMaster });

await db.Follower.create({
  followerId: getCurrentUserId(context),
  followingId: id,
  status: followingUser.privateProfile ? "Pending" : "Approved"
});

return followingUser.reload();
```

The `followingUser` that it returns has a field called followingInfo which is a subquery, and should reflect the new `Follower` record that was created:

**followingInfo field on User**
```javascript
followingInfo: {
  type: followerObjectTypes.type(db),
  async resolve(user, args, context) {
    return db.Follower.findOne({
      where: {
        followingId: user.id,
        followerId: getCurrentUserId(context)
      }
    }, { useMaster: context.useMaster });
  }
},
```
## What is actually happening?
The field `followingInfo` is null, and it is not pulling from the master. If we make the query again seconds later, the data is there.

We are not seeing that `useMaster` is forcing queries to use our master DB.

__Dialect:__  postgres
__Database version:__ 9.6.8
__Sequelize version:__ 4.38.0
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
`followingUser.reload()` should be `followingUser.reload({ useMaster: true })`

**Comment by KidA001** [comment]
@sushantdhiman thank you. That seems to have worked. I pushed it up to our staging environment and will see how it works throughout the evening here. I didn't realize you could pass `useMaster` to the `reload()` function. Do all query functions pretty much accept the same arguments?

**Comment by KidA001** [comment]
@sushantdhiman Just a follow up on this. We are still experiencing issues with race conditions that are related to our replica database. I am setting `useMaster` to `true` in our queries, and it doesn't seem to be persisting through to fields defined on our models which are sub-queries (as mentioned above). Our application is experiencing extremely high load and we've had to turn off our replica database due to this issue. 

Do you have any thoughts as to why fields which are subqueries on a model we've called `useMaster` on are not using the writer database? Do we need to wrap the entire query in transaction as well?

We have 3 different engineers who have looked at this, and have tried setting `useMaster` to true on every single query just to see if that would fix the race condition on mutations, and it has not. What are we missing here?

**Comment by sushantdhiman** [comment]
> Just a follow up on this. We are still experiencing issues with race conditions that are related to our replica database. I am setting useMaster to true in our queries, and it doesn't seem to be persisting through to fields defined on our models which are sub-queries (as mentioned above). Our application is experiencing extremely high load and we've had to turn off our replica database due to this issue.

Sub queries here are just nested graphql payload resolution i.e. normal select queries, which if passed with `useMaster` will go through master. If context is passing `useMaster: true` then those queries will go through master all times. If that is not the case, can you demonstrate this in some way I can replicate.

> Do you have any thoughts as to why fields which are subqueries on a model we've called useMaster on are not using the writer database? Do we need to wrap the entire query in transaction as well?

- Make sure you set proper query type for those like `{ type: QueryTypes.SELECT }` etc
- Mutations should all run with `useMaster:true` mode
- If you have any loaders then make sure they also use `useMaster` when available in context

Looks like queries are mixed with `useMaster: true` and `useMaster: undefined`, whenever you find a case which fails to load due to replica lag, add that chain to `useMaster` setup, so they use `useMaster` when resolving from mutation with help of `context.useMaster`
