### ISSUE TITLE
Documentation don't tell all ways to use OR operator!

### ISSUE THREAD

**Issue by techsin** [sequelize/sequelize#9977]
https://stackoverflow.com/questions/52583338/sequelize-are-all-of-these-correct-ways-to-use-or-operator

I've seen 3 ways people use OR operator...

`where: { $or : [ {attr:val}, {attr:val}] } `

`where: { $or : { attr:val, attr:val} } `

`where: { attr: { $or: [val, val] } }`

are all of these valid? and any gotchas?

documentations only explains method 1.
http://docs.sequelizejs.com/manual/tutorial/querying.html#operators

this below is vague..but i hope it means one of the conditions are true and it's possible to do with attributes as well not just other operators.

```
{
  rank: {
    [Op.or]: {
      [Op.lt]: 1000,
      [Op.eq]: null
    }
  }
}

```

**Comment by sushantdhiman** [comment]
IIRC `1` and `3` are valid, `OR` (and `AND`) accepts conditions to be combined with OR or AND keyword. You should use `1` mostly. 

As for case you have given, you can its behaviour by looking at what SQL query is generated but I would avoid this

```js
{
  rank: {
    [Op.or]: {
      [Op.lt]: 1000,
      [Op.eq]: null
    }
  }
}
```

**Comment by techsin** [comment]
hi, thanks for answering, 
so 2 is invalid? as it will throw an error,  or the behavior would be not you expect.

**Comment by sushantdhiman** [comment]
Any cases where `[Op.or]` is accepting object is non-standard, It accepts an array. So `2` is invalid but if it works then it does so by pure chance
