### ISSUE TITLE
Make previousDataValues part of the public API

### ISSUE THREAD

**Issue by devuxer** [sequelize/sequelize#9978]
I'm trying to write an afterUpdate hook that performs a logging action based on values that have *changed* during an update. I'm intending to do this by by taking the simple diff between `instance._previousDataValues` and `instance.dataValues`.

However, when using TypeScript, `_previousDataValues` is not recognized as part of the public API. This can be worked around by doing `(instance as any)._previousDataValues` but this is not clean.

Is there any reason `_previousDataValues` is private? Would anything break if a new property `previousDataValues` were added that was the same thing as `_previousDataValues`? (To avoid duplication, `_previousDataValues` could ultimately be deprecated in a future version.)

Alternatively, is there any way to obtain an object containing only data properties and values that have changed?

**Comment by sushantdhiman** [comment]
You can use `changed` https://github.com/sequelize/sequelize/blob/f7585ac08cf8a44a535ae3b9c42776f9fd4bc22e/lib/model.js#L3509-L3521

**Comment by devuxer** [comment]
Oh that's perfect. I didn't realize you could call `changed` with no arguments to get an array. Thanks.

**Comment by devuxer** [comment]
`previousDataValues` could still be useful, though, if you wanted to know what each value changed from-to.

**Comment by sushantdhiman** [comment]
You can use `previous` for that https://github.com/sequelize/sequelize/blob/053145cd38c16a62b46bc29ccdd5e7d7c195852a/lib/model.js#L3531-L3540

**Comment by devuxer** [comment]
@sunshinewyin,

Ahh, yes. I just realized my problem. My type definition file is from [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript), which shows `previous` and `changed` but doesn't properly document that you can call these with no arguments.

I'm going to close with and take that up with them. Thanks again for your help.
