### ISSUE TITLE
Error "Cannot read property 'use_env_variable' of undefined"

### ISSUE THREAD

**Issue by danimauro** [sequelize/sequelize#9979]
hello

i have a problem with the archive models/index.js in the first line "config.use_env_variable" 
shows the error "Cannot read property 'use_env_variable' of undefined"

===>>> if (config.use_env_variable) { 
    sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
    sequelize = new Sequelize(
        config.database, config.username, config.password, config
    );
}

/*=====================================*/

the archive config/config.json I'm just using for this example "development"
{
    "development": {
        "username": "root",
        "password": "12345",
        "database": "prueba",
        "host": "127.0.0.1",
        "dialect": "mysql",
        "port": "3306"
    },
    "test": {
        "username": "root",
        "password": null,
        "database": "database_test",
        "host": "127.0.0.1",
        "dialect": "mysql"
    },
    "production": {
        "username": "root",
        "password": null,
        "database": "database_production",
        "host": "127.0.0.1",
        "dialect": "mysql"
    }
}

/*=====================================*/

my model 

'use strict';
module.exports = (sequelize, DataTypes) => {
    const Permisos = sequelize.define('Permisos', {
        id: {
            allowNull: false,
            primaryKey: true,
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4
        },
        create: DataTypes.BOOLEAN,
        read: DataTypes.BOOLEAN,
        update: DataTypes.BOOLEAN,
        delete: DataTypes.BOOLEAN
    }, {});
    Permisos.associate = function(models) {
        //un permiso tiene muchos roles
        Permisos.hasMany(models.Rol);
    };
    return Permisos;
};

/*====================================*/
in my routes file I am calling the model as follows

const express = require('express');
const app = express();

const Permiso = require('../models').Permisos;

app.post('/permiso', (req, res) => {

    Permisos.findAll().then(permisos => {
        res.json({
            ok: true,
            permisos
        });
    })

});

module.exports = app;

/*==================================*/

when I make the model call like this:

const Permiso = require('../models/Permisos');

it does not show error, but at the time of making the request post for postman says:

ReferenceError: Permiso is not defined

Could you please help me, sorry for my English

**Comment by sushantdhiman** [comment]
Closing this as this is related to CLI and issue template is blown away

Looks like you are facing cyclic reference issue. Please study this example https://github.com/sequelize/express-example/tree/master to see recommended way of setting up models.
