### ISSUE TITLE
Bind parameters

### ISSUE THREAD

**Issue by jesslilly** [sequelize/sequelize#998]
Sequelize is awesome, but I have an enhancement idea.  Bind parameters.  I am using mostly sequelize for my database queries, but I had a big nasty query that was taking too long.  So I changed the code to use node-sqlite3 instead and use bind variables.  Now the query is much faster.  Could you implement bind variables in sequelize?

**Comment by holm** [comment]
Using prepared statements can make queries significantly faster, especially if the query is complex and returns few rows. This is because the prepared statement will be parsed and analyzed just once, which can be a big part of queries that are fast to execute and return little data.

**Comment by mickhansen** [comment]
@holm In cases where the connection is reused that is definitely true (which should be the case for most saturated pools).
