### ISSUE TITLE
Invite to slack community

### ISSUE THREAD

**Issue by SilencerWeb** [sequelize/sequelize#9981]
Hm, you are linking [closed slack community](https://sequelize.slack.com/) as a way to contact you without telling how and from who people can get an invite. Don't you think it is weird?

**Comment by sushantdhiman** [comment]
Hi where did you get that link, I would replace it with invite app.

You can invite yourself [here](http://sequelize-slack.herokuapp.com/) (as mentioned in https://github.com/sequelize/sequelize#resources)

**Comment by SilencerWeb** [comment]
@sunshinewyin [here](https://github.com/sequelize/sequelize/blob/master/CONTACT.md#via-slack)

And thank you for invite link, I didn't see it in the 'resources' section :)
