### ISSUE TITLE
Sequelize return only parent data that don't have child

### ISSUE THREAD

**Issue by fuadajip** [sequelize/sequelize#9986]
Is there any way of include combination params to return only parent data that don't have child?

For example: 

```js
User.findAll({
  where:
   { type: 'member'}
  },
  include: [
     { model: Cat },
     required: false
  ]
}).then(users => console.log(users)).catch(err => console.log(err));
```

Result:
```
[{id:1, name:'A', cats: [{...},{...}],
 {id:2, name:'B', cats: [{...},{...}],
 {id:3, name:'C', cats: []}
```

How to achieve this?
```
[{id:3, name:'C', cats: []}
```

IMHO We can do with array filter manipulation in first result, but if there have a good way i think it much better

Is this feature already exist in Sequelize or not? because I search in the documentation don't get what it must expected to return only parent that don't have child 

__Dialect:__ mysql
__Dialect version:__ 1.5.2
__Database version:__ latest
__Sequelize version:__ 4.35.1

**Comment by knoxcard** [comment]
```
User.findAll({
  where:
   { type: 'member'}
  },
  include: [
     { model: Cat },
     required: false
  ]
}).then(users => console.log(users)).catch(err => console.log(err));
```

**Comment by fuadajip** [comment]
> Here is a way to do it outside of SQL (Post Process)
> 
> ```
> User.findAll({
>   where:
>    { type: 'member'}
>   },
>   include: [
>      { model: Cat },
>      required: false
>   ]
> }).then(users => {
>   users.foreach(user => {
>      if(users.cats)
>         if(user.cats.length)
>            return
>     console.log(users)
>   })
> })
> ```

Very appreciated, yes you're right I've tried with javascript filter and something like that, but if there any update from the author or other users with the best practice very welcome or if the solution does not exist I think it needs to add as a new feature in next release

**Comment by knoxcard** [comment]
Right, i'd really hate to use my posted solution, more of a band aid on a major injury.  I'd think by now Sequelize has this covered, you just have to dig real deep.  Lets see if I can summon some feedback...

@sushantdhiman

**Comment by sushantdhiman** [comment]
Original feature request https://github.com/sequelize/sequelize/issues/5485

Currently there is no Sequelize way to do this, you can include association and filter `length === 0`. Another way could be `Op.and` in `where` which could use `EXISTS` statement so database don't return records for association when there are some rows
