### ISSUE TITLE
Sequelize delete rows not present in incoming JSON

### ISSUE THREAD

**Issue by antondc** [sequelize/sequelize#9988]
## What are you doing?
I am working with Sequelize and Express/Node. I have a model `ProjectImages`, which is a list of the images of each `Project` model. From my API endpoint `/api/projectsimages` I make a `GET` query:
```
    // Express router
    router.get('/api/projectsimages/:id', function(req, res, next) {
        models.ProjectImages.findAll({
            where: {
                parentId: req.params.id,
            },
        }).then((response) => {
            return res.send(JSON.stringify(response));
        });
    });
```
And in frontend I receive this JSON:
```
    {
    	"Projects": [
    		{
    			"id": 1,
                "url": "https://picsum.photos/200/300/?random",
                "parentId": 1
            },
            {
    			"id": 2,
                "url": "https://picsum.photos/200/300/?random",
                "parentId": 1
            },
            {
    			"id": 3,
                "url": "https://picsum.photos/200/300/?random",
                "parentId": 1
            },
    	]
    }
```
Now in frontend I remove the row with `{ id: 2 }` from the array `ProjectImages`: 
```
    ProjectImages = ProjectImages.filter((item) => {
        return item.id !== 2;
    });
```
So now ProjectImages is:
```
    {
        "ProjectImages": [
            {
                "id": 1,
                "url": "https://picsum.photos/200/300/?random",
                "parentId": 1
            },
            {
                "id": 3,
                "url": "https://picsum.photos/200/300/?random",
                "parentId": 1
            },
        ]
    }
```
Then I send it back to `/api/projectsimages/1` with `PUT`:
```
    return fetch('/api/data', {
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        },
        method: 'PUT',
        body: JSON.stringify(ProjectImages),
    });
```
Now, my question is: given this JSON I'm sending, how do I tell the Express Router to remove the rows I removed from the array in frontend? I suppose I can make a query in the router to retrieve all items with `{ parentId: 1 }`, compare the result with the JSON I'm sending, and remove those not present in the incoming array. But it doesn't seem very efficient. 

Which is the best and proper way to do it?
```
    // Express router
    router.put('/api/projectImages/:id', function(req, res, next) {
        // ???
    });

```
__Dialect:__ mysql 
__Dialect version: ver 14.14 Distrib 5.7.22, for osx10.13 (x86_64) 
__Sequelize version: 4.37.7

**Comment by sushantdhiman** [comment]
I would issue a request to subroute to delete project images as soon as UI action is executed. Suppose user clicked on deleted button for second image, I would send delete request like this

```
DELETE /api/project/1/images/2
```

Alternatively you can keep ids which user has selected to delete and send them all together

```
DELETE /api/project/1/images?ids=2,3,7
```

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
