### ISSUE TITLE
sequelize.findOne seems to be broken.

### ISSUE THREAD

**Issue by dmorr041** [sequelize/sequelize#9990]
## What are you doing?

```js
//=========================== user.js file ===============================//
var bcrypt = require('bcrypt');

module.exports = function(sequelize, type){
    var User = sequelize.define('users', {
        id: {
            type: type.UUID,
            unique: true,
            allowNull: false,
            primaryKey: true
        },
        username: {
            type: type.STRING,
            unique: true,
            allowNull: false
        },
        email: {
            type: type.STRING,
            unique: true,
            allowNull: false
        },
        password: {
            type: type.CHAR(60),
            allowNull: false
        },
        fname: {
            type: type.STRING
        },
        lname: {
            type: type.STRING
        },
        phone: {
            type: type.STRING
        },
        address: {
            type: type.STRING
        }
    }, {
        hooks: {
            beforeCreate: function (user) {
                const salt = bcrypt.genSaltSync();
                user.password = bcrypt.hashSync(user.password, salt);
            }
        }
    });

    User.prototype.validPassword = function(password){
        return bcrypt.compareSync(password, this.password);
    }

    // Create all the defined tables in the specified database
    sequelize.sync()
    .then(() => console.log('Users table has been successfully created, if one doesn\'t exist.'))
    .catch(error => console.log('The following error occured: ', error));

    return User;
};
//========================= user.js file =================================// 


//========================= server.js file ===============================//
//#region Setup
var express = require('express');
var bodyParser = require('body-parser');
var cookieParser = require('cookie-parser');
var session = require('express-session');
var morgan = require('morgan');
var uuidv4 = require('uuid/v4');
var Sequelize = require('sequelize');
var SequelizeStore = require('connect-session-sequelize')(session.Store);
var pgSession = require('connect-pg-simple');
var User = require('./models/user');

// Database connection with Sequelize
const database = new Sequelize('postgres://postgres:<myPassword>@<hostAddress>:5432/Coconut');

database.authenticate()
    .then(() => {
    console.log('Connection established.');
    })
    .catch(err => {
        console.log('Connection failed.');
    });

const UserInstance = User(database, Sequelize);

// Me checking that the users table exists in my sequelize entry point
console.log(database.isDefined('users'));     
console.log(database.model('users'));


// invoke an instance of express application.
var app = express();

// set our application port
app.set('port', 3000);

// Set the view engine to EJS
app.set('view engine', 'ejs');

// set morgan to log info about our requests for development use.
app.use(morgan('dev'));

// initialize body-parser to parse incoming parameters requests to req.body
app.use(bodyParser.urlencoded({ extended: true }));

// initialize cookie-parser to allow us access the cookies stored in the browser. 
app.use(cookieParser());

var coconutStore = new SequelizeStore({
    db: database
});

// initialize express-session to allow us track the logged-in user across sessions.
app.use(session({
    store: coconutStore,
    key: 'user_sid',
    secret: <mySecret>,
    resave: false,
    saveUninitialized: false,
    cookie: { maxAge: 30 * 24 * 60 * 60 * 1000 } 
}));

coconutStore.sync()
    .then(() => console.log('Sessions table has been successfully created, if one doesn\'t exist'))
    .catch(error => ('The following error occured: ', error));
//#endregion

//#region Middleware
// This middleware will check if user's cookie is still saved in browser and user is not set, then automatically log the user out.
// This usually happens when you stop your express server after login, your cookie still remains saved in the browser.
app.use((req, res, next) => {
    if (req.cookies.user_sid && !req.session.user) {
        res.clearCookie('user_sid');        
    }
    next();
});


// middleware function to check for logged-in users
var sessionChecker = (req, res, next) => {
    if (req.session.user && req.cookies.user_sid) {
        res.redirect('/dashboard');
    } else {
        next();
    }    
};
//#endregion

//#region Routes
// route for Home-Page
app.get('/', sessionChecker, (req, res) => {
    res.redirect('/login');
});

// route for user signup
app.route('/register')
    .get(sessionChecker, (req, res) => {
        res.render('register');
    })
    .post((req, res) => {
        UserInstance.create({
            id: uuidv4(),
            username: req.body.username,
            email: req.body.email,
            password: req.body.password
        })
        .then(user => {
            req.session.user = user.dataValues;
            res.redirect('/dashboard');
        })
        .catch(error => {
            console.log(error.stack);
            res.redirect('/register');
        });
    });


app.route('/login')
    .get(sessionChecker, (req, res) => {
        res.render('login');
    })
    .post((req, res) => {
        var username = req.body.username,
            password = req.body.password;

// Me checking the username and password is being grabbed from form. Works.
            console.log(username)
            console.log(password)
// Me checking if the users table exists in database. Works.
        database.query('SELECT * FROM users', {type: database.QueryTypes.SELECT}).then(results=>{
            console.log(results);
        })
// Me checking if the row for user1 exists. Works.
        database.query("SELECT * FROM users WHERE username = 'user1'", {type: database.QueryTypes.SELECT}).then(results=> {
            console.log(results);
        })
// Me trying to log find the user using findOne. FAILS.
        UserInstance.findOne({ where: { username: username } }).then(function (err, user) {
            if(err){
                console.log(err.stack);
            }
            if (!user) {
                console.log('no user')
                res.redirect('/login');
            } else if (!user.validPassword(password)) {
                console.log('invalid pass')
                res.redirect('/login');
            } else {
                req.session.user = user.dataValues;
                res.redirect('/dashboard');
            }
        });
    });


// route for user's dashboard
app.get('/dashboard', (req, res) => {
    if (req.session.user && req.cookies.user_sid) {
        res.render('dashboard');
    } else {
        res.redirect('/login');
    }
});


// route for user logout
app.get('/logout', (req, res) => {
    if (req.session.user && req.cookies.user_sid) {
        res.clearCookie('user_sid');
        res.redirect('/');
    } else {
        res.redirect('/login');
    }
});


// route for handling 404 requests(unavailable routes)
app.use(function (req, res, next) {
  res.status(404).send("Sorry can't find that!")
});
//#endregion

module.exports = User;

//#region Server
// start the express server
app.listen(app.get('port'), () => console.log(`App started on port ${app.get('port')}`));
//#endregion

// ======================== server.js file ================================//


```

## What do you expect to happen?
I expect UserInstance.findOne to return the row for user1 the same way database.query does.

## What is actually happening?
findOne is returning undefined, despite the output showing a correct query string.

_Output, either JSON or SQL_
C:\RengTech\Coconut>node server.js
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:242:13
true
users
App started on port 3000
Executing (default): SELECT 1+1 AS result
Executing (default): CREATE TABLE IF NOT EXISTS "Sessions" ("sid" VARCHAR(32) , "expires" TIMESTAMP WITH TIME ZONE, "data" TEXT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("sid"));
Executing (default): CREATE TABLE IF NOT EXISTS "users" ("id" UUID NOT NULL UNIQUE , "username" VARCHAR(255) NOT NULL UNIQUE, "email" VARCHAR(255) NOT NULL UNIQUE, "password" CHAR(60) NOT NULL, "fname" VARCHAR(255), "lname" VARCHAR(255), "phone" VARCHAR(255), "address" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Connection established.
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Sessions' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Sessions table has been successfully created, if one doesn't exist
Executing (default): CREATE TABLE IF NOT EXISTS "Sessions" ("sid" VARCHAR(32) , "expires" TIMESTAMP WITH TIME ZONE, "data" TEXT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("sid"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Sessions' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Users table has been successfully created, if one doesn't exist.
GET /login 304 12.580 ms - -
user1
user1
Executing (default): SELECT * FROM users
Executing (default): SELECT * FROM users WHERE username = 'user1'
Executing (default): SELECT "id", "username", "email", "password", "fname", "lname", "phone", "address", "createdAt", "updatedAt" FROM "users" AS "users" WHERE "users"."username" = 'user1' LIMIT 1;
[ { id: '1493d805-b16a-4fbc-b345-04caecb756fd',
    username: 'user1',
    email: 'user1@gmail.com',
    password: '$2b$10$NXbVROsKZmnaQeM7o3u09.r9KYeFMNGXNRPmWuQGYo7TXAAr1Qg9q',
    fname: null,
    lname: null,
    phone: null,
    address: null,
    createdAt: 2018-10-03T23:29:11.166Z,
    updatedAt: 2018-10-03T23:29:11.166Z } ]
[ { id: '1493d805-b16a-4fbc-b345-04caecb756fd',
    username: 'user1',
    email: 'user1@gmail.com',
    password: '$2b$10$NXbVROsKZmnaQeM7o3u09.r9KYeFMNGXNRPmWuQGYo7TXAAr1Qg9q',
    fname: null,
    lname: null,
    phone: null,
    address: null,
    createdAt: 2018-10-03T23:29:11.166Z,
    updatedAt: 2018-10-03T23:29:11.166Z },
  { id: 'e15c694f-b137-4cb3-9604-7cd07988d66d',
    username: 'user2',
    email: 'user2@gmail.com',
    password: '$2b$10$7Eku3EoJyDLrkddem4tlWuQEhKOH/gIpWM94zNrGjCADexoG2DHHy',
    fname: null,
    lname: null,
    phone: null,
    address: null,
    createdAt: 2018-10-04T14:56:08.142Z,
    updatedAt: 2018-10-04T14:56:08.142Z } ]
undefined
no user
POST /login 302 93.016 ms - 56
GET /login 200 2.860 ms - 1203

__Dialect:__ postgres
__Dialect version:__ 9.6.6
__Database version:__ ? Not sure what goes here
__Sequelize version:__ 4.39.0
__Tested with latest release:__ Yes, version 4.39.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by dmorr041** [comment]
I apologize for the Output not being strictly JSON, but its important to see the console.log statements to understand what's happening here

**Comment by frlinw** [comment]
`UserInstance.findOne({ where: { username: username } }).then(function (err, user) {`
It's a promise, not a callback error is probably handled in `.catch()`
You should try
```js
UserInstance.findOne({ where: { username: username } }).then(user => {
    console.log(user)
})
```

**Comment by dmorr041** [comment]
Yeah after opening the issue originally I removed the err parameter in the promise, but that didn't fix the issue. What's confusing to me is that when I switch 
const database = new Sequelize('postgres://postgres:<myPassword>@<hostAddress>:5432/Coconut');
to localhost, by replacing <hostAddress> with localhost, everything works perfectly. Users can register, login and logout, and sessions are associated with the user. But when I switch to the remote IP address of my Google Cloud PostgreSQL instance, my '/register' route adds a new user to the remote database (i checked it by querying in pgAdmin3), but users aren't associating with sessions and the login doesn't work. When connected to remote DB, findOne returns undefined. But on localhost, all routes function properly.

**Comment by sushantdhiman** [comment]
>users aren't associating with sessions and the login doesn't work. When connected to remote DB, findOne returns undefined. But on localhost, all routes function properly.

Seems like a problem related to userland code, may be incomplete understanding of Promises. Please read about [async nature of Node](https://blog.risingstack.com/node-hero-async-programming-in-node-js/) and [working with Promises](http://cryto.net/~joepie91/blog/2016/05/11/what-is-promise-try-and-why-does-it-matter/)

We can only offer help when something is broken with Sequelize or a bug, we can;t debug entire application for you. Please get help from one of our colleagues :)
