### ISSUE TITLE
Postgresql error: relation does not exist (relation "myTableName" does not exist)

### ISSUE THREAD

**Issue by Mk-Etlinger** [sequelize/sequelize#9991]
## What are you doing?

**edit2**: Remember folks, when you change your env variables, you have to restart your server/pm2 instance =) This fixed it, although I would expect a more helpful error message when host, port etc. are undefined.

Hey guys, 

I am switching my node/express app from `mysql` to `postgresql`. Everything was pretty seamless except I had to swap some data types. When I try to run the following command I get an error.

**edit**: Looks like something else is up. Sequelize throws the same error for all other queries, including `relation "users" does not exist`. I know this was marked as support, but mysql was working perfectly before changing to postgres, so I imagine it should also work now.

```js
const [ serviceUser, created ] = await ServiceUserAccountModel.findOrCreate({ 
          where: { service_user_id: '123456' },
        });
```

`relation "serviceUserAccounts" does not exist`.  or with users `relation "users" does not exist`
 
```js
const userModel = Sequelize.define('user', {
    // has many ServiceUserAccounts

    id: { 
      type: DataTypes.INTEGER, 
      primaryKey: true, 
      autoIncrement: true 
    },

    email: {
      type: DataTypes.STRING,
      allowNull: false
    },

    age: {
      type: DataTypes.SMALLINT,
      allowNull: false
    },

    gender: {
      type: DataTypes.STRING,
      allowNull: false
    },

    first_name: {
      type: DataTypes.STRING,
      allowNull: true
    },

    last_name: {
      type: DataTypes.STRING,
      allowNull: true
    }
       
  });

    const serviceUserAccountsModel = Sequelize.define('serviceUserAccount', {
      // belongs to User
      
      id: { 
        type: DataTypes.INTEGER, 
        primaryKey: true, 
        autoIncrement: true 
      },

      display_name: {
        type: DataTypes.STRING,
        allowNull: true
      },

      email_address: {
        type: DataTypes.STRING,
        allowNull: true
      },
  
      service_id: { 
        type: DataTypes.SMALLINT,
        allowNull: true,
      },

      service_user_id: { 
        type: DataTypes.STRING,
        allowNull: true,
      },
  
      refresh_token: {
        type: DataTypes.STRING,
        allowNull: true
      },
  
      access_token: {
        type: DataTypes.STRING,
        allowNull: true
      },
  
      token_type: {
        type: DataTypes.STRING,
        allowNull: true
      },
  
      expiration_date: {
        type: DataTypes.INTEGER,
        allowNull: true
      },
  
      storage_limit: {
        type: DataTypes.INTEGER,
        allowNull: true
      },

      storage_usage: {
        type: DataTypes.INTEGER,
        allowNull: true
      },

      trashed_storage_usage: {
        type: DataTypes.INTEGER,
        allowNull: true
      },
      
    });

// Relations

module.exports = function( database ){
  const User = database.models.user.user;
  const ServiceUserAccounts = database.models.user.serviceUserAccounts;
  
  User.hasMany(ServiceUserAccounts);
  ServiceUserAccounts.belongsTo(User);
};
```

## What do you expect to happen?
 As it was working perfectly before with mysql dialect, I expect it to also work with Postgresql. 

## What is actually happening?
`relation "serviceUserAccounts" does not exist`. I'm able to run the query just fine in pgAdmin, so it must be something with sequelize. What am I missing?

Here's the gist with the stacktrace
https://gist.github.com/Mk-Etlinger/569093387a0cb97699acfcba3994f59d

**Any ideas?** I checked my permissions and it came back `public, $user`.

also looked here but no luck:
https://stackoverflow.com/questions/28844617/sequelize-with-postgres-database-not-working-after-migration-from-mysql

https://stackoverflow.com/questions/946804/find-out-if-user-got-permission-to-select-update-a-table-function-in-pos

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ 9.6.2
__Sequelize version:__ ^4.38.1
__Tested with latest release:__ Yes, 4.39.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Name `"userServiceAccounts"` is quoted and I dont see tableName definition in your models. Are you sure table was created as `"userServiceAccounts"` not as `userServiceAccounts` (without quotes)?

Please read this important SO answer on how Postgres quotes affects naming https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive/20880247#20880247

**Comment by Mk-Etlinger** [comment]
Hey @sushantdhiman thank you for your reply. That is a typo by me actually. It should be "serviceUserAccounts".

I get this error when querying anything from the database via sequelize. However, I am able to use pgadmin without any errors with the same queries.

So for "users" I get the same error.

I will read that link and report back. Thanks so much!

**Comment by Mk-Etlinger** [comment]
@sushantdhiman Hey so sorry about this, after viewing the logs, I realized that my env variables were undefined. 

This makes no sense because I was able to authenticate on the db without error. When I viewed the logs though, the Sequelize instance had host, user and pw all undefined and I knew that was it.
