### ISSUE TITLE
Can't include when attributes is empty

### ISSUE THREAD

**Issue by Kilimangaro** [sequelize/sequelize#9997]
## What are you doing?
I want to query a model  with criterias based on a nested association without including the attributes of the association.

```js
const A = sequelize.define('a', {}),
    B = sequelize.define('b', {}),
    C = sequelize.define('c', {
        name: DataTypes.STRING
    });
A.belongsTo(B);
B.belongsTo(C);
const [a, b, c] = await Promise.all([ A.create({}), B.create({}), C.create({ name:'foo' }) ]);
await Promise.all([a.setB(b), b.setC(c)]);
const result = await A.find({
    where: {
        '$b.c.name$': 'foo'
    },
    include: [{
        model: B,
        attributes: [],
        include: [{
            model: C
        }]
    }]
});
expect(result).to.be.ok;
```

## What do you expect to happen?
_A valid result_

## What is actually happening?
`TypeError: Cannot set property 'c' of undefined`

__Dialect:__ any
__Sequelize version:__ v4.39.0 (i think it affect all versions)
__Tested with latest release:__ Yes v4.39.0

**Comment by NexusgsWeb** [comment]
This issue still persists, will it be solved any time soon?

**Comment by ephys** [comment]
See https://github.com/sequelize/sequelize/issues/12671
